### ISSUE TITLE
Attributes on a property's `Type` have no impact on `ModelMetadata`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1000]
We use the `TypeDescriptor` infrastructure when filling in `Attribute` information for model types and their properties in MVC 5.2.  This infrastructure is not used in MVC 6.0, mostly because it's not available in .NET Core.

One impact of this change is we now call `PropertyInfo.GetCustomAttributes()` rather than the `PropertyDescriptor.Attributes` getter.  The two methods do _not_ return the same `Attribute` collection.  Most importantly `PropertyDescriptor` includes attributes from the property's `Type` but `PropertyInfo` does not.

For example,

``` C#
        [HiddenInput(DisplayValue = false)]
        private class HiddenClass
        {
            public string Property { get; set; }
        }

        private class ClassWithHiddenProperties
        {
            [HiddenInput(DisplayValue = false)]
            public string DirectlyHidden { get; set; }

            public HiddenClass OfHiddenType { get; set; }
        }
```

With the above model, both `DirectlyHidden` and `OfHiddenType` would have `ModelMetadata.HideSurroundingHtml == true` in MVC 5.2.  In MVC 6.0, only `DirectlyHidden` has this non-default property value.  The same thing will happen with any `Attribute` we handle that can be applied to a `Type`.

Notes for implementation:
Stepping through the .NET code, it seems the relevant code is in `System.ComponentModel.ReflectPropertyDescriptor`.  The `FillAttributes()` method in that class doesn't simply concatenate the attributes from the `Type` and those from the property (and the property's inheritance hierarchy).  It also has to handle extender properties (a term which appears to mean an indexer) and `AttributeProviderAttribute` complications.

A lot of that likely isn't relevant but we will at least need to deal with correctly merging attribute collections to eliminate those that should be overridden.  `System.ComponentModel.MemberDescriptor.FilterAttributesIfNeeded()` eliminates duplicates using their `Attribute.TypeId` property values.

**Comment by rynowak** [comment]
It sounds like if we ever changed this it would be a subtle breaking change, and no one has asked for this.

Suggest closing /cc @Eilon @dougbu

**Comment by dougbu** [comment]
I'm not sure about this one. IIRC we had a slight breaking change from MVC 5.old / `TypeDescriptor` behaviour. On the other hand, MVC Core.new has been through a full release and has always behaved self-consistently in this area.

**Comment by Eilon** [comment]
This issue is super dead, so closing.
