### ISSUE TITLE
Ensure the behavior of unused sections is the same as MVC 5

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1006]
@javiercn had suggestions on behavior that he expected for aspnet/Razor#79 that aren't covered by https://github.com/aspnet/Mvc/pull/997. Essentially, doing `@section` in Razor views which do not have a Layout specified should also throw. 

We do throw if you defined a section in a page but didn't render it in a Layout but this is a case that is not handled today.

**Comment by danroth27** [comment]
The current behavior is that we silently ignore unused sections when rendering partials. This behavior is consistent with MVC 5 and we think its fine.
