### ISSUE TITLE
Consider whether to support action selection on values that don't ToString in a useful way

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#1011]
Followup of https://github.com/aspnet/Mvc/pull/848#discussion_r16270481

The issue in the PR is when a value comes from a route in we need to compare it to _something_. Right now that _something_ has to be a string https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/RouteDataActionConstraint.cs

The suggestion in the discussion is to implement logic like:
1. If `a` and `b` are both strings, compare them as strings
2. Else compare them as objects

The problem with this is that strings have special rules for route values. `"" == null` (for route values). Also, since we force route data constraints to be strings, we further have the problem that conversions are **useful**.

Consider this:

```
[Version("3")]
public class FooController { }

routes.MapRoute("api/{controller}/{action}", new { version = 3 });
```

The version value coming from routing is an int-3 and the version in action selection is string-3. It's really surprising if these aren't considered equal.

Another idea was to convert to strings **iff** one of them is a string. This has a problem due to hashing. We can decide when comparing two objects whether to convert them or not, we can't decide when doing hashing because it's context free.

All of this comes about when you want use values that don't ToString in a meaningful way **inside action selection**. I don't think there's a consistent way to deal with the issues so I suggest we don't support it.

**Comment by Eilon** [comment]
Closing because we are not planning to implement this.
