### ISSUE TITLE
Make `@Html.Display()` and `@Html.Editor()` order properties by name

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1012]
MVC 5.2 and (soon, see issue #964 and PR #1010) 6.0 order properties in the `@Html.Display()` and `@Html.Editor()` return values using the `ModelMetadata.Order` property.  This produces as stable an order as Linq's `OrderBy()` -- leaves the properties in their original order.  But the order isn't predictable because the CLR doesn't guarantee an order the `Type.GetRuntimeProperties()` extension method returns properties.

The point may be moot if `Type.GetRuntimeProperties()` _happens_ to order properties consistently and not by (say) the order they appear in the IL.  But we could ensure a predictable order by adding `ThenBy(m => m.Name)` to our current sort (in the `ModelMetadata.Properties` lazy-init getter)

Some questions:
- Is this necessary?  That is are properties ordered by name or something equally obvious already?
- Would the additional sorting have any downsides?  For example performance could be an issue because the `Properties` enumeration isn't initialized in our `ModelMetadata` prototype cache.

**Comment by Eilon** [comment]
Closing because we have no plans to support this.
