### ISSUE TITLE
Consider allowing the user to handle an un-parseable media type

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#1015]
As seen here: https://aspnetwebstack.codeplex.com/workitem/2101 sometimes developers have to support a misbehaving client.

In this case it's a file upload where the file-parts have an invalid media-type. We should take a look at this experience and see that users get an escape hatch we're happy with when a client out of their control does something bad.

**Comment by harshgMSFT** [comment]
@Tratcher this would impact strongly typed header parsing...

**Comment by rynowak** [comment]
Per discussion in the review of strongly-typed headers - they are opt-in, so by default everything is available as unparsed. I propose we close this issue as there's nothing to do here.
