### ISSUE TITLE
Make sure that Html Helpers use builder pattern, e.g HtmlTags

### ISSUE THREAD

**Issue by pawelpabich** [aspnet/Mvc#1038]
Hi,

Very often I need to modify html generated by Html Helpers which is very difficult as all I have at my disposal is a raw string. If the return object implemented the builder pattern, e.g. https://github.com/darthfubumvc/htmltags, then this would be much easier. This should be a non breaking change as the builder can implement IHtmlString.

Thoughts ?

**Comment by Eilon** [comment]
Closing because we are not planning to implement this. We instead have tag helpers, which solve part of the problem here.

**Comment by jbogard** [comment]
@pawelpabich in case you're interested, I released a version of the HtmlTags library that targets ASP.NET Core, and lets you use tag helpers along with HtmlTag conventions. Sort of best-of-both-worlds https://www.nuget.org/packages/HtmlTags.AspNetCore/
