### ISSUE TITLE
[implementation] Remove System.Reflection.Compatibility-like helpers from `TypeExtensions`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#105]
Current `TypeExtensions` class(es) contain(s) extension methods such as `IsAssignableFrom()` which may be ambiguous in any consuming class that uses System.Reflection. To create the ambiguity, someone would only need to add the System.Reflection.Compatibility package to the project's dependencies.  In addition we should all be learning about the new Reflection APIs.

Should migrate existing code to use `GetTypeInfo()` directly.  (Another possibility would be to always rely on the System.Reflection.Compatibility package but that is not the preferred direction. Finally could use helpers with unambiguous names -- but such extension methods just hide the new APIs and slow learning.)

**Comment by rynowak** [comment]
I don't have a reference to a specific commit, but this class is gone now, so this was fixed one way or another. Generally the more complex stuff was either moved to `ModelMetadata` or to the common repro.
