### ISSUE TITLE
Automatically convert ViewComponents to tag helpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#1051]
Right now we can invoke/render ViewComponents via ```@Component.Invoke("MyViewComponentName", p1, p2....)```.  We should consider making a "tag helper" alternative to rendering view components where you could do something like:

```<myViewComponentName />```

This would involve automagically converting ViewComponent's into TagHelperDescriptor's.  As for how they'd appear in html it's up for discussion.

**Comment by hakenr** [comment]
My $100 for this feature. ;-)
``<my-view-component-name foo="param value" bar="another value" />``

**Comment by tuespetre** [comment]
@NTaylorMullen: regarding what I meant about 'descendant tags'... I meant what if you nested view component tag helpers within each other, but it looks like that may be sorted out already by the use of self-closing tags.

**Comment by NTaylorMullen** [comment]
@tuespetre the default implementation of ViewComponentTagHelpers for its v1 representation will override its body content. Of course there's opportunity to expand on this later if it seems valuable.

**Comment by ajaybhargavb** [comment]
0cfd5363f8f27b3e5c043f2cc8813730938627b7

**Comment by ajaybhargavb** [comment]
0d782d9d9abb828aa23bf8d1b36ca12a771c55f8 and aspnet/RazorTooling@24a9c542c4af119f1e1ffd2b1cde603515b58429
