### ISSUE TITLE
Need a way to specify "just type" with produces

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#1065]
When you really *want* to use `ObjectResult` but not change the output content types, there's no way to specify the logical return type with `[Produces]`.

Consider this code: There's no way to specify the `Type` without specifying content types.

```
[Produces(typeof(Product))] // does not exist yet
public IActionResult GetProduct(int id)
{
    var product = db.Products.Get(id);
    if (product == null)
    {
        return NotFound();
    }
    return new ObjectResult(product);
}
```

**Comment by kichalla** [comment]
@rynowak, @yishaigalatzer  : Probably this is a stale bug...seems like we already have this ability...links:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Filters/ProducesAttribute.cs#L23

https://github.com/aspnet/Mvc/blob/dev/test/WebSites/ApiExplorerWebSite/Controllers/ApiExplorerResponseTypeOverrideOnActionController.cs#L8

**Comment by kichalla** [comment]
My bad...please ignore my previous comment...i see that we want to specify the Type without the content types...

**Comment by yishaigalatzer** [comment]
Note that this might impact the mapping media types through file extensions feature (and you want to verify it doesn't break any scenarios and add test coverage for that feature as well).

**Comment by yishaigalatzer** [comment]
CC @kulmugdha @rynowak
