### ISSUE TITLE
Consider improving the syntax for FlushPoints

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1080]
Right now using FlushPoints look like this:

```HTML
</head>
@{ await FlushAsync(); }
...
```

The suggestion is to make it look nicer

```HTML
</head>
@await FlushAsync()
...
```

This would require returning a no-op value (`null` / empty `HelperResult`) from `FlushAsync`

**Comment by yishaigalatzer** [comment]
Duplicate of #1547
