### ISSUE TITLE
Let customers use `TypeHelper`, `PropertyHelper`, and perhaps other currently-`internal` classes

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1098]
Everything in our Common project has `internal` access modifiers. specifically `TypeHelper` and `PropertyHelper` not public, it's far from trivial to implement and user code sometimes depends on it in the legacy system" where "it" is "converting anonymous objects or POCO classes to dictionaries".

The current choice was made because multiple assemblies compile in these source files.  If the Common classes were 'public', projects depending on more than one MVC assembly would find full names of the Common classes were ambiguous.

----
This is not a regression from MVC 5.2, but we did find that users are using as an alternative the `routevaluedictionary` class that is significantly less efficient.

**Comment by danroth27** [comment]
@rynowak @dougbu @Eilon Anything still to do here? Close?

**Comment by rynowak** [comment]
I'd prefer us not to make these public unless we got specific feedback. Even then something like this would be better as part of corefx
