### ISSUE TITLE
Add support for using @helper across views

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#1130]
Currently we support using `@helper` in the same view that they are defined...we are seeing users using this across views.

I briefly researched on if ViewComponents would be a replacement for this but the thing here is that ViewComponents are meant to separate `html` and backing code where as the `@helper` stuff mixes `@html` and c# code, which is by design and expected.

**Comment by yishaigalatzer** [comment]
We want to setup a design meeting, mostly to understand the scope and if changes are required to the framework/compilation model. The intent is not to implement for RTM, but to be able to build a preview package

**Comment by pranavkm** [comment]
Based on the design discussion, the plan is to remove support for `@helper` until we have a better design for using and sharing them.

**Comment by alexaku** [comment]
Fucking theorists. In practice, without @helper, I need to add several hundred new files manually to migrate my two websites in MVC 6. Each such file will be a couple of lines of context dependent html-code.
