### ISSUE TITLE
unnecessary css class in default editor template for nullable  Boolean 

### ISSUE THREAD

**Issue by johnciliberti** [aspnet/Mvc#1135]
In the class Microsoft.AspNet.Mvc.Rendering.DefaultEditorTemplates you have the following code:

```htmlAttributes: CreateHtmlAttributes(html, "list-box tri-state"))```

Not sure why you need the extra class in there other then showing off how smart you are by using a nullable  Boolean as a tri-state. Not sure how it adds value from a rendering perspective.

**Comment by weitzhandler** [comment]
The generated class for checkbox `check-box`, is also not compatible with bootstrap, and should be changed to `checkbox`.
Is there a way to identify what version of MVC is running? Or what version of bootstrap is attached?
I'd say `DefaultEditorTemplates` should be pluggable or at least configurable anyway (as a filter config or anything similar on startup).

**Comment by Eilon** [comment]
@ajaybhargavb can you take a look? Seems like @dougbu has some context on this.

**Comment by ajaybhargavb** [comment]
Discussed with @dougbu offline and there isn't anything that we are planning to do here.
