### ISSUE TITLE
Mono Compat Issues

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1174]
Issues running Mvc against Mono observed when updating tests:

* `XmlDictionaryReaderQuotas` settings are not honored for deserialization
* `ClaimsIdentity` does not use `Claims` property for discovering claims in methods like `FindFirst`
* `ValidationAttribute` does not read non-public (internal) properties on resx type.

**Comment by danroth27** [comment]
@pranavkm Could you please make sure the appropriate Mono bugs have been opened and referenced here?

**Comment by danroth27** [comment]
@sornaks Could you please check what the current status is of these Mono issues? Thanks.

**Comment by sornaks** [comment]
Filed 2 issues. Tracked here - https://github.com/aspnet/External/issues/14, https://github.com/aspnet/External/issues/12

**Comment by sornaks** [comment]
- ValidationAttribute issue is fixed - https://github.com/mono/referencesource/blob/mono/System.ComponentModel.DataAnnotations/DataAnnotations/ValidationAttribute.cs#L201
- ClaimsIdentity issue is fixed - https://github.com/mono/referencesource/blob/mono/mscorlib/system/security/claims/ClaimsIdentity.cs#L793
