### ISSUE TITLE
Allow replacement of `Id` sanitization

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1188]
HTML continues to evolve and users may have many different `Id` uniqueness or sanitization requirements.  For example a user who values uniqueness more than Unobtrusive validation or other CSS selectors, might want no sanitization at all.  Others may want to sanitize only characters that are known to cause issues in CSS selectors.

@DamianEdwards and I talked about one way to address these various requirements.  We could make `Id` sanitization a service MVC grabs from DI to meet the above requirement.  Current MVC 6.0 code uses a static method in `TagBuilder` – pretty much the opposite of an extensibility point.

FYI default sanitization will match MVC 5.2.  That provides `Id` values which match HTML 4 requirements.  So by default we could be sacrificing some uniqueness when names contain "invalid" characters.

Including Needs Design label per an offline comment from @yishaigalatzer

**Comment by danroth27** [comment]
@Eilon @dougbu @DamianEdwards Have we had anyone ask for this? Close?

**Comment by dougbu** [comment]
Can't recall whether @DamianEdwards and my conversation on this topic started from a customer request, team comment on a way-back PR, or random ions in that hallway.

**Comment by Eilon** [comment]
I'm not aware of any real-world problems in this space.

**Comment by danroth27** [comment]
Closing, but we would revisit based on customer feedback.
