### ISSUE TITLE
API Explorer: Consider supporting additional data about the response

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#1191]
We should think about the following scenario for API explorer:

An API is servicing a request to create some entity on the server in a long-running task. The API will validate user input and then return an HTTP 201, with a location header specifying the URL of the entity to check for status.

Additionally, the API will dynamically generate a unique requestId and return this in a header.

Right now nothing about our OM let's us specify that the 'success' response code is a 201 or that the caller should look at the location/requestId header. This can be added in the property data of the `ApiDescription` but it's not first class and the user would have to write a provider to discover it.

If this is done with filters/attributes, we could easily surface this data.

**Comment by yishaigalatzer** [comment]
We should work with Matt Gibbs on this before making progress. Moving to post RTM as it is possible today (if not in a super friendly way)

**Comment by rynowak** [comment]
This is definitely still an issue, swagger wants to know what status codes are possible return values from an endpoint and what they mean.

The difference between 200 and 201 is still important. The detail about the location header is a standard behavior so there's no need to document it.

**Comment by rynowak** [comment]
Closing this as we plan to address this in a different way. I don't think this issue contains any valuable information that we don't already track elsewhere.
