### ISSUE TITLE
Provide a base type like InputFormatter for easy creation of input formatters

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#1222]
Currently I have to implement the raw interface `IInputFormatter` to write an input formatter, I was looking to inherit from a base class like `InputFormatter` (just like OutputFormatter)...:

Its for parity in experience with Web API formatter or vNext's output formatter. Like I can just add supported media types and encodings and be sure of being provided the effective encoding when I am trying to deserialize the stream.

Otherwise currently the user would need to implement code to support stuff like...doing media type subset matching, getting the effective encoding...

**Comment by ajaybhargavb** [comment]
13e1c9d5e1509b0df5c7a2317b6380fa1a401784
