### ISSUE TITLE
Documentation: Improve discoverability of "htmlAttributes" entry in `ViewDataDictionary`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1233]
`@Html.Editor()` and `@Html.EditorFor()` special-case an entry named "htmlAttributes" in the `ViewDataDictionary` (optionally augmented using `additionalViewData` parameters) when executing their default templates. MVC 5.2 issue [#2142](https://aspnetwebstack.codeplex.com/workitem/2142) is an indication this feature needs additional documentation. Users will otherwise search for ways to control generated HTML attributes when using these methods.

Couple of details:
- "htmlAttributes" key is case-insensitive
- entry is handled very similarly to the `htmlAttributes` object passed to input helpers such as `@Html.HiddenFor()` and `@Html.TextBox()`

**Comment by Eilon** [comment]
This issue was moved to aspnet/Docs#2009
