### ISSUE TITLE
Tag Helpers: support `ModelExpression` IntelliSense

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1252]
for example if the user is at `|` in the following, IntelliSense should prompt with available fields and properties in the model:
``` c#
  <input type="text" for="|"/>
```

this amounts to design-time support for the quoted expression used at runtime to create a `ModelExpression` instance.  could be as simple as projecting the user to the `|` in the following.
``` c#
  var __unused = CreateModelExpression(model => model.|);
```

**Comment by yishaigalatzer** [comment]
This is already done, tooling needs to verify once the tooling feature lights up. @vkichline
