### ISSUE TITLE
Dispose IDisposable objects in ObjectResult, FileStreamResult and others in exceptional cases

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#1331]
Scenario:
Users typically do the following in Web API. Here the expectation is that the file stream would be closed after the content from the file has been read and written out.
```c#
public HttpResponseMessage DownloadFile()
{
    var response = new HttpResponseMessage();
    response.Content = new StreamContent(File.OpenRead(@"C:\Images\image1.jpg"));
    response.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");
    response.Content.Headers.ContentType = new MediaTypeHeaderValue("image/jpeg");
    return response;
}
```

**Comment by yishaigalatzer** [comment]
Strawman design:

Include all objects that needs disposing on the Response/Request and dispose them with the request unwinds (or when exiting MVC).

`ObjectResult`, can upon setting the `Value` can register the type for disposal if it implement `IDisposable`, similarly `FileStreamResult` can do the same.
