### ISSUE TITLE
ActionModel needs to expose RouteValueDefaults

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#1338]
When generating action model, a key ingeredient to pass extra specific knowledge to the action as runtime is route value defaults (because they can be easily bound).

Also it would be nice to specify properties as key value pairs.

**Comment by danroth27** [comment]
@rynowak @Eilon Close?

**Comment by rynowak** [comment]
`RouteValueDefaults` was removed. Close please :+1:
