### ISSUE TITLE
View Components invoke method async

### ISSUE THREAD

**Issue by jrote1** [aspnet/Mvc#1363]
Currently Component invoke methods cannot be async, you get this error:

System.InvalidOperationException: View components only support returning String, HtmlString or IViewComponentResult.

Will the ability for them the be async be added?

**Comment by VSG24** [comment]
Any improvement planned for this? The current error message is not helpful.

**Comment by rynowak** [comment]
@VSG24 - can you please open a new issue with a code sample and the error message you thing is wrong?
