### ISSUE TITLE
Add extension method to MergeHtmlAttributes from TagHelperContext

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#1365]
Right now we have a `CopyHtmlAttribute` `TagHelperOutput` extension method which copies attributes from the `TagHelperContext` back into the `TagHelperOutput`. We should add a `MergeHtmlAttribute` which gets attributes from the `TagHelperContext` and then merges them into the current `TagHelperOutput.Attributes`. The difference is that the merge would special case `class` and append attributes with spaces if it exists on the `TagHelperOutput`.

**Comment by DamianEdwards** [comment]
This is a nice idea but I think it needs more thought as I'm not sure `class` is the only attribute that has that merge semantic, and what does it do for other attributes where the values differ?

**Comment by NTaylorMullen** [comment]
Hmm, I'd prefer the do-not override approach for other attributes.

**Comment by Eilon** [comment]
@DamianEdwards @NTaylorMullen does this still seem useful?

**Comment by NTaylorMullen** [comment]
Hmm it'd be a nice utility to have but I'm not convinced it's desperately needed. Might not be worth the added API surface area.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
