### ISSUE TITLE
Remove all uses of ITypeActivator and use the static method instead

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#1416]

**Comment by pranavkm** [comment]
@kirthik  - https://github.com/aspnet/DependencyInjection/issues/164

**Comment by kirthik** [comment]
Code checked in - 5de210f5271c385d7bae47af0f866698518fccdc

**Comment by avanderhoorn** [comment]
Why does the `DefaultTypeActivatorCache` leverage a cache of delegates which indirectly call `ActivatorUtilities.CreateFactory(...)` vs just calling `ActivatorUtilities.CreateFactory(...)` directly?
