### ISSUE TITLE
`@Html.Display()` and `@Html.Editor()` should also check for template for declared type

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1432]
`@Html.Display()` and `@Html.Editor()` sometimes do not check for templates matching the declared type (aka `ModelType`) of a property.  this is confusing and likely leads to duplicate templates that must be kept in sync.

my suggestion is to always check the `ModelType` just before `Collection` (or `Object` in the single-valued case) if `ModelType` is an `interface` and the model is non-`null`. this fix is simple but may be controversial if named `interface`s should (for some definition of "should") be checked before one of the instance's base types.

for example, with a model containing

``` c#
  public IEnumerable<string> OwnedAddresses { get; set; }
```

the property may be initially `null`, set to a `List<string>` instance in a subset of action methods, and stored as a `string[]` array in a `ModelStateDictionary` entry. checked templates for each of those types include the following:
1.

```
EditorTemplates/IEnumerable`1
EditorTemplates/Collection
```

2.

```
EditorTemplates/List`1
EditorTemplates/Collection
```

3.

```
EditorTemplates/String[]
EditorTemplates/Array
EditorTemplates/Collection
```

note only `Collection` is common and templates for that may be too general. with my suggestion `EditorTemplates/IEnumerable`1` would also appear in all three lists.

---

root cause is `TemplateRenderer.GetViewNames()` walks the `RealModelType` base types back to `object` but mostly ignores implemented interfaces. since no instance has an interface base type, the declared type is also normally ignored.

**Comment by Eilon** [comment]
Closing because we are not planning to implement this.
