### ISSUE TITLE
Consider Code-Generating helper code for invoking viewcomponents in razor

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#1435]
Related to #612 - this suggestion goes further.

Use razor/roslyn to code generate a wrapper for a view component that will simplify invoking it from Razor, while keeping the authoring experience the same.

Sample code:
```
@inject ViewComponent<TagCloud> TagCloud

@await TagCloud.GetTags(count: 10)
```

The generated methods would have the same names and parameters as the methods defined on the viewcomponent class.

**Comment by danroth27** [comment]
We plan to address view component invocation by supporting invoking view components as tag helpers #1051.
