### ISSUE TITLE
ValidationSummary could provide some way to jump to the field that is wrong

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1469]
`@Html.ValidationSummary()` and `div validation-summary="All"/>` currently generate

``` html
  <div class="validation-summary-errors" data-valmsg-summary="true">
    <ul>
      <li>Something happened with your model.</li>
      <li>Something happened with field Property1.</li>
    </ul>
  </div>
```

Should instead generate

``` html
  <div class="validation-summary-errors" data-valmsg-summary="true">
    <ul>
      <li><label>Something happened with your model.</label></li>
      <li><label for="Property1">Something happened with Property1.</label></li>
    </ul>
  </div>
```

The `<label/>` wrapping for model-level errors ensures the default styles are consistent.
See [original MVC 5.2 request](https://aspnetwebstack.codeplex.com/workitem/2156) for more details.

**Comment by Eilon** [comment]
Closing because we are not planning to implement this.

**Comment by dougbu** [comment]
@Eilon what does closing this imply about #4888 and @DamianEdwards's "Support initial focus" point?

**Comment by Eilon** [comment]
Ah, sure, re-opening for now. Still seems unlikely we'd implement it, though.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
