### ISSUE TITLE
Breakpoints are not hit in .cshtml files

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1491]
Not sure if this is a Runtime, Razor, or MVC bug but let's start here since MVC does the compilation of Razor-generated files.  Using current VS / WTE builds (DP 22228.01 and 2014-10-29_b1886) with the latest origin/dev code, breakpoints in .cshtml files are not hit and are listed with an unusual tooltip.  Breaks on exceptions in the generated classes (e.g. NREs in the MVC sample at `~/Home/Post`) have wildly incorrect locations.  No such issues exist with regular C# classes.

Ex. list of breakpoints:
![breakpoints](https://cloud.githubusercontent.com/assets/6431421/4856730/13293ff4-60c1-11e4-9161-d1715f63b030.png)

Ex. tooltip message:
![breakpoint tooltip](https://cloud.githubusercontent.com/assets/6431421/4856731/1eeb756e-60c1-11e4-9190-e6f2e86ab9a5.png)

Problems occur with both IIS Express and Web Listener.  I was testing with CLR (not Core) configuration.

/cc @pranavkm since he was looking at this issue earlier.

**Comment by dougbu** [comment]
I can hit breakpoints in some cases after my most recent VS re-installation but not when I follow our internal recommendations for VS setup.

If Debug / Options / General / "Require source files to exactly match the original version" is checked at the beginning of a debug session, breakpoints are hit in .cshtml files.  Otherwise they are not.  Changing this setting during a debug session does not change the behaviour.  (Note we've been recommending _clearing_ this setting.)

Still unsure whether the problem exists in Razor, MVC, or VS...

**Comment by yishaigalatzer** [comment]
Get together with @dougbu and @ToddGrun and get a consistent repro

**Comment by yishaigalatzer** [comment]
@mayurid can your team get a consistent repro for this?

**Comment by pranavkm** [comment]
> If Debug / Options / General / "Require source files to exactly match the original version" is checked at the beginning of a debug session, breakpoints are hit in .cshtml files. Otherwise they are not. 

Yup, I'm seeing this behavior. Also seeing this if I click on the breakpoint and tick the "allow the source code to be different from the original version". Seem non-intuitive since you'd expect these flags the make the source file matching less restrictive and not more.

I'm using 14.0.22515.0 WPT with latest WTE.

**Comment by yishaigalatzer** [comment]
This looks like a bug in VS. @mayurid @barrytang can you please investigate?

**Comment by barrytang** [comment]
Opened a VS bug to track.
