### ISSUE TITLE
Easier Controller integration testing

### ISSUE THREAD

**Issue by anpete** [aspnet/Mvc#1504]
Make it easier to integration test controllers. Right now it can be tricky to ensure that a controller instance has had its dependencies correctly wired up. This can be mitigated if the developer is careful to rely only on ModelBinding and ActionResults, but it would probably be good to have a test helper that is capable of returning a fully formed Controller instance.

**Comment by ianhong** [comment]
@anpete I opened the two issues #1772 and #1771 for tracking this, and I think we can resolve this. Please close this after reviewing two related issues.

**Comment by ianhong** [comment]
@anpete, I'm closing this, and let me know if you have more requirements than #1771 and #1772
