### ISSUE TITLE
Some Unit Test for Razor Templating are failing, when global .gitgnore config has core.autocrlf = false

### ISSUE THREAD

**Issue by DerAlbertCom** [aspnet/Mvc#1514]
that's because of the 

.gitignore
```
[core]
	autocrlf = false
```
the the \r\n and \n problem while comparing input and output.

Steps to reproduce on a windows machine

- checkout (in my case release)
- execute build.com

**Comment by pranavkm** [comment]
We decided on using either embedded resource of multiline `@` strings in our tests to work around. There's quite a few strings that are constructed at test runtime using `Environment.NewLine` - these need to be changed.

**Comment by dougbu** [comment]
9c63d1d
