### ISSUE TITLE
Route values sometimes override explicit model values

### ISSUE THREAD

**Issue by wanghaolu** [aspnet/Mvc#1517]
bug display in following picture.
when I use html helper method to display the view model. The html result is the route parameter value, not the view model value.

MVC version is 5.2.2

![2014-11-07_10-11-56](https://cloud.githubusercontent.com/assets/9586655/4947657/d509f9c0-666a-11e4-828a-47847bb19fbc.png)

**Comment by yishaigalatzer** [comment]
@dougbu lets get a design meeting for this, and see if we can improve

**Comment by dougbu** [comment]
title was previously "Html helper method bug"

we will have a design discussion shortly about this issue as well as the proposed #1231 enhancement.

**Comment by dougbu** [comment]
we will make related improvements when fixing #1998 and #1999.  closing this and #1231 as duplicates of those bugs.
