### ISSUE TITLE
Html.EditorFor for an object-typed member with enum contents renders nothing

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#1519]
In 6.0.0-alpha4, I have a simple view model:

``` C#
public class MyModel { public object Value { get; set; } }
```

and try to render an input for this:

``` C#
Html.EditorFor(x => x.Value)
```

When the object stored in Value is of type int, string, or DateTime etc, I get the corresponding input with type="number", type="text", or type="datetime". However, when the stored object is of type enum, only a blank line is rendered instead of an input.

I have looked at the source code of *.Core and experimented accordingly, but now I'm even more confused:
- When I change the type of Value in the view model to my enum type, an input type="text" is rendered
- When I add en EditorTemplate named myenumtype.cshtml, the contents are rendered
- When I add an EditorTemplate named Enum.cshtml, those contents are rendered

**Comment by rynowak** [comment]
> add display and edit templates (either Enum.cshtml or YourEnumType.cshtml). note we added Enum.cshtml support in MVC 5.2.

Given that we have a template for `Enum` in MVC 5.X should we port that forward for parity?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
