### ISSUE TITLE
ActionContext should have a copy ctor which allows us to set the `ActionDescriptor`

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1525]
Alternatively we should just make the `ActionDescriptor` be a publicly settable property. As it stands there isn't an easy way to copy an `ActionContext` that has all the context of an exising `ActionContext` with the `ActionDescriptor` being settable.

**Comment by yishaigalatzer** [comment]
Create a constructor that take also ModelState on top of https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ActionContext.cs#L24-L26

**Comment by rynowak** [comment]
08a578d01f46c918af91c765877af8d78ca45a19
