### ISSUE TITLE
Come up with a design for setting `ModelState.MaxAllowedErrors`

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#1538]
Currently this value is set from options inside the `MvcRouteHandler`. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/MvcRouteHandler.cs#L82

This is confusing from a layering standpoint. We should consider what the right design is for this. There had been some discussion about a filter-stage dedicated to this sort of model-binding concerns.

**Comment by yishaigalatzer** [comment]
We will move the setting to the entry point of model binding.
We will make the default maxerrors on model state the same as the default in mvc options
We will provide a constructor to model state with max errors, and review all uses of the modelstatedictionary default constructor.

**Comment by rynowak** [comment]
42df4cf2eddd92221104c55fe6bc48a42e2b3030
