### ISSUE TITLE
Tag Helpers: Create an 'environment' Tag Helper

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#1553]
A new Tag Helper that utilizes the conditional content mode (aspnet/razor#221) to only render its contents if the current `IHostingEnvironment.EnvironmentName` matches the specified name. The target environment names can be specified as a comma separated list via the `names` attribute (string). In the case of the environment not currently matching, the contents would not even be executed.

### Usage
``` HTML
<environment names="">
</environment>
```
If the `names` attribute is omitted, the contents are always rendered.

### Attributes
Attribute Name | Type | Details
---- | ---- | ----
names | `string` | A comma separated list of environment names in which the content should be rendered

### Example

``` HTML
<environment names="Development">
    <script src="~/js/file1.js"></script>
    <script src="~/js/file2.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="~/js/site.js"></script>
</environment>
`````

**Comment by Bartmax** [comment]
why do you have `name` and `names` ? I suggest to keep only with `names` so one can change from one to multiple only modifying the content.

Also, can this `envitorment` tag would be anything ? so if we have a model like :
```
public bool IsValid {get;set;}
public string Name {get;set;}
```
one my author
```

<conditional IsValid="true"> .. </conditional>
or
<condition name="Bart, Damian"> ... </condition>
```


and for the enviroment example:

```<condition environment="Production, Staging">...</condition>```

or maybe better ```<if environment="Production, Staging"> ... </if>```

**Comment by Bartmax** [comment]
is there a way to implement fallback environment when the enviroment does not match any of listed names ? 
is there a way to implement a NOT condition ? like ```<environment names="!Staging">``` 

I'm afraid we may see lots of duplicated code... or lots of enviroment clauses. Is the view really the responsable to use one or another ?

**Comment by DamianEdwards** [comment]
@Bartmax agree on name/names, I'll change that.

You could certainly build a more generic conditional/if tag helper yourself, but we're not planning on doing it. We see environment being something people often conditionally render content on so we're promoting it as a first class tag helper, but fundamentally we don't to go super generic in the tag helpers (and have Razor end up looking like Spark).

**Comment by NTaylorMullen** [comment]
759fbbd661fe4f8d51203fd8b521e72f3f63e96d
