### ISSUE TITLE
Logging: ViewEngine

### ISSUE THREAD

**Issue by SonjaKhan** [aspnet/Mvc#1563]
Log locations searched to find the view at `LogLevel.Verbose`

**Comment by yishaigalatzer** [comment]
We need to revisit the design here. @kichalla please set up a design meeting with @lodejard and friends to get this going

**Comment by avanderhoorn** [comment]
If you need any input feel free to let me know.

**Comment by kichalla** [comment]
Commit: e7728dde3f98cf02b0951ab8f1ad9108e337b06b
