### ISSUE TITLE
InputTagHelper renders a closing tag for type="submit" and type="button"

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#1571]
The `InputTagHelper` renders a closing tag when type is equal to "submit" or "button". It's likely this is the behavior for all types not specifically understood by the `InputTagHelper` after a quick glance at its code.

It's also possible the issue is that the state of `TagHelperOuput.SelfClosing` does not correctly reflect what is in the source CSHTML and thus the fact the element is already self-closed in the source is lost after parsing (in which case this should be a bug against the Razor repo).

`<input type="submit" value="Log in" class="btn btn-default" />` becomes `<input class="btn btn-default" type="submit" Value="Log in"></input>`

**Comment by ianhong** [comment]
4bb85eeaeb479edf8abff34e9078886c14d32861
and
23e6264715b0055218611b3f36ac45098f6b0fb1

**Comment by NTaylorMullen** [comment]
@ianhong one of the commits is invalid.

**Comment by ianhong** [comment]
The invalid commit number is a Razor one, and the actual commit is https://github.com/aspnet/Razor/commit/23e6264715b0055218611b3f36ac45098f6b0fb1
