### ISSUE TITLE
Flushing a view via FlushAsync breaks AntiForgeryToken via HTML Helper & FormTagHelper

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#1573]
If a view calls `FlushAsync` before a call to `IHtmlHelper.AntiForgeryToken` or the use of the `FormTagHelper` (by way of them being deferred in a declared `section`), then no anti-forgery cookie is sent to the client, as the headers are flushed before the helper can add the cookie to the response. No error is thrown during the GET requests, however any subsequent attempt to POST the form will result in `InvalidOperationException: The required anti-forgery cookie "__RequestVerificationToken" is not present.`

This is most easily demonstrated in the canonical use of `FlushAsync` in flushing the `<head>` element before the result of the view in `_Layout.cshtml`:
``` HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
@{ await FlushAsync(); }
<body>
    @RenderBody()
    @await RenderSectionAsync("Body", required: false)
   ...
```
This will cause the following view to fail upon POST:
``` HTML
@model WebApplication7.Models.LoginViewModel

@{
    ViewBag.Title = "Log in";
}

@section Body {
<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
...
```

## Suggested Fix

To fix this we'll need to come up with a way to coordinate the sending of the cookie header before the helper has run.

Here's a **straw-man** idea to get started:

Have the helpers throw an exception if they attempt to set the cookie but the headers are already flushed. This will alert the dev to the issue they've introduced which can then be mitigated using the change below.

Make the `Flush` method set the anti-xsrf cookie based on a flag that can be set from the view (e.g. a property on the base class or a value in the `ViewBag`). This way, the view and layout page can coordinate to conditionally send the header only when it's required, e.g.

### _Layout.cshtml
``` HTML
...
</head>
@{ await FlushAsync(); } @* This will automatically flush the anti-xsrf cookie if  *@
<body>
    @RenderBody()
    @await RenderSectionAsync("Body", required: false)
...
```
### Login.cshtml
``` HTML
@model WebApplication7.Models.LoginViewModel
@{
    ViewBag.Title = "Log in";
    // Indicate to the layout page that anti-xsrf token must be sent during pre-flush
    ViewBag.RequiresAntiForgeryToken = true;
}
@section Body {
<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @* The helper would need to coordinate with the value already flushed to the client
                      so as to ensure the correct hidden field value is rendered here *@
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
...

```

**Comment by kirthik** [comment]
Checked in - 951ed05893d10beafbbe6449652684c19f2384ae
