### ISSUE TITLE
ScriptTagHelper support for fallback source, e.g. when using CDNs

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#1576]
The `ScriptTagHelper` (#1524) should support specifying a fallback source that should be loaded in the case that the primary source fails. Determination of failure of the primary script is done by way of a fallback test expression that is supplied (required).

The two sources and the fallback test expression are used to render a script block that checks for the successful download of the primary script, and if the test fails, load the fallback script by way of an inline `document.write` in the page to add the `<script>` tag for the fallback script. (Web Forms does this already in its `ScriptManager`)

This enables the common scenario of loading a library from a CDN but falling back to a local copy in the case that the CDN is unavailable.

### Usage
``` HTML
<script src=""
    asp-fallback-src=""
    asp-fallback-test="">
</script>
```

All the attributes are required to be present and non-null for the Tag Helper to perform this action. If any are missing, it will log a warning and no-op.

### Attributes
Attribute Name | Type | Details
---- | ---- | ----
asp-fallback-src | `string` | The URL for the script file to load in case load of the primary src fails
asp-fallback-test | `string` | The JavaScript expression that tests the successful loading of the primary src. Should equate to `true` if the script has loaded successfully.

### Example
Used in conjunction with the proposed `EnvironmentTagHelper`:
``` HTML
<environment name="Development">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validation/jquery.validate.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.1.min.js"
        asp-fallback-src="~/lib/jquery/jquery.min.js"
        asp-fallback-test="window.jquery"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"
        asp-fallback-src="~/lib/jquery-validation/jquery.validate.min.js"
        asp-fallback-test="window.jquery && window.jquery.validate"></script>
</environment>
```

**Comment by Bartmax** [comment]
Just in case someone face a problem, using (copy/pasting) the sample code, the asp-fallback-test should have jQuery with capital Q.

**Comment by NTaylorMullen** [comment]
Thanks @Bartmax, updated the issue to reflect that.

**Comment by Anderman** [comment]
I had the same problem as Bartmax. 
There are a few problem with the current implementation and the solution in 2015RC:
* how do I know/test that the development use the same version as production
* How do I know/test If i use the correct fallback-test (in 2015RC the wrong test is used for bootstrap.js asp-fallback-test="window.jQuery")

I was writing my own implementatie of link and script taghelpers and added a few attributes to solve a number of these problems
```
<script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"
        asp-fallback-src="~/fallback/js/jquery.validate.unobtrusive.min.js"
        asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
        asp-use-src="production,staging"
        asp-use-fallback="development"
        asp-skip-if-loaded="production"
        asp-copy-src-to-fallback="development"
        asp-warn-if-loaded="development">
```
* asp-use-src: The primary source that this enviroment will use
* asp-use-fallback: The primary source that this enviroment will use
* asp-skip-if-loaded: If we use all.min version for production then skip this resource if fallback-test succeed. 
* asp-warn-if-loaded: Before loading the script the fallback-test expression is tested and will give a warning if the test succeed
* asp-copy-src-to-fallback: Copy the CDN version to localdisk to create the fallback copy. Incl. fonts and images.

**Comment by Bartmax** [comment]
That's a great idea, but if you control the path of the 'copied files' you only need

```
<script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"
   asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
```

the rest can be perfectly valid as defaults. (pseudo code)
```
if (src != IsLocalUrl) {
    if (nolocalfiles) downloadFiles;
    if (dev) { warningOnError(); return ScriptWithLocalFiles; }
}
return ScriptWithSourceFiles

if (testFails) create ScriptWithLocalFiles;
```

**Comment by Anderman** [comment]
Oke looks good

For Js I think thats simple. 
But for css there maybe is a problem if the localpath is not too deep 
For example they sometimes referred as ../../someimage.png. 

Maybe this can besolved by a default local copy location wwwroot\fallback\css\extra\ or something.

**Comment by bmbell** [comment]
Could this case still have a potential staleness issue?

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.1.min.js"
        asp-fallback-src="~/lib/jquery/jquery.min.js"
        asp-fallback-test="window.jQuery"></script>

For example, let's say the user loads the page and it falls back to the "~/lib/jquery/jquery.min.js" file.  Then, they come back sometime later, and perhaps the code has been updated so the version number is now 2.1.2.  Bower would also update the ~/lib/jquery/jquery.min.js, but the path remains the same:

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.2.min.js"
        asp-fallback-src="~/lib/jquery/jquery.min.js"
        asp-fallback-test="window.jQuery"></script>

Thus, if the fall back gets hit again, wouldn't the user's browser potentially use it's cached version of ~/lib/jquery/jquery.min.js?

**Comment by DamianEdwards** [comment]
@bmbell yes that could be an issue, albeit a rare one (multiple fallbacks over the life of a single user across versions). That said, you can use the `asp-append-version` attribute to include a version stamp in the rendered URL, [even in the fallback case](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.TagHelpers/ScriptTagHelper.cs#L335).

So your example becomes:
``` HTML
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.2.min.js"
        asp-fallback-src="~/lib/jquery/jquery.min.js"
        asp-fallback-test="window.jQuery"
        asp-append-version="true"></script>
```

**Comment by Fizzleban** [comment]
Thanks - I just wanted to point that out since it's currently part of the default template.  However, I agree it *should* be a rare case (though I'm sure stranger things have happened!). ;)

**Comment by bmbell** [comment]
Thanks - I just wanted to point that out since it's currently part of the default template. However, I agree it should be a rare case (though I'm sure stranger things have happened!). ;)
