### ISSUE TITLE
Action argument of IList<T> will be bound as Null instead of an empty List<T>

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#1579]
Today CollectionModelBinder returns false if a value provider cannot provide a value, it is the mutable object binder which creates a model for it. 
Since it is the ```CollectionModelBinder``` which is responsible for binding collections, it should be the one which creates empty object and not let it slip for other model binders.

**Comment by yishaigalatzer** [comment]
> , it will now in addition to creating top level object will try to bind inner properties and will have all sorts of problems.

@harshgMSFT please provide concrete repro for what is going to break. If you think this is critical for Beta3 milestone please raise a flag

**Comment by harshgMSFT** [comment]
This does not need to be fixed in Beta3 as we have fixed the ```GenericModelBinder``` to return true if there was a model with collection.

**Comment by harshgMSFT** [comment]
Ok .. sorry about not including a code sample : here is the actual issue ( after the Uber dust has settled :smile: ).

```C#
public class HomeController : Controller 
{
           public void Action(IList<Model>  model)
           {
                  // Does something.
           }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            // context.ActionArguments["model"] is null here.
        }
}
```
and consider a URL like so : 
```
http://localhost/home/Action
```

With no value provider having a value for Model or its properties, what happens is the model object created is null.

This is because ```GenericModelBinder``` ( which is the entry point for binding any collection based model) or more specifically ```CollectionModelBinder```, does not create the model when  it does not see a value with a value provider. 

This is contrary to what what we do with models in MVC 6.0. (we always create them).
Ideally the ```CollectionModelBinder``` should have returned true after creating a default (non null) collection.

This is not a MUST fix as the user scenario is not broken but this provides an inconsistency in the system.

**Comment by bgeihsgt** [comment]
We just ran into this in our project and broke a core assumption we had about MVC.  In the beta 3 code, we had different behavior whether an action array parameter was null (when the param was not on the URL) or empty (the param is on the URL but empty).  When we changed to beta 4, the array parmeter is always empty whether you specify anything on the URL or not.  This caused a bug in our code.  We've updated our code based on the new behavior, but wanted to let you know that this is a change that broke  compat with older versions of MVC.

**Comment by dougbu** [comment]
@bgeihsgt we need to confirm the MVC 5 `null` versus empty collection behaviour and should probably align with that -- not the behaviour in earlier MVC 6 releases.  However there's another consistency issue that may be all-important: Action parameters of complex types are always non-`null` but will be uninitialized if the request contains no data.

So, we'll make a call here and pick back-compatibility or consistency.  Either way you'll see a resolution on this issue.  If the result is a further change, we'll also use the [Announcements](https://github.com/aspnet/Announcements) repo.

**Comment by harshgMSFT** [comment]
@bgeihsgt thanks for letting us know, as @dougbu said, we will need to pick back-compat or consistency. MVC 5.0 behavior for collections was to not create the collection (have them null) if there was no data on wire. (hence the back-compat vs consistency argument.

**Comment by rynowak** [comment]
8f38650d1f3f0a31856fe7d05f0e5ca3ee39aa75
