### ISSUE TITLE
Please support nested areas in mvc 6

### ISSUE THREAD

**Issue by mojtabakaviani** [aspnet/Mvc#1595]
This is best time to add nested areas to mvc 6 that can implement advanced pages routing.
for example now just add one level area such as /page/edit or /forum/page/edit...
but with nested area can better manage enterprise sites and hierarchically pages such as /forum/guest/page/edit and more...

**Comment by ynauls** [comment]
Was there any traction in creating an example for supporting SubAreas?

**Comment by rynowak** [comment]
https://github.com/aspnet/Mvc/tree/dev/samples/MvcSubAreaSample.Web

**Comment by TeunKooijman** [comment]
The link is dead! Is there any alternative endpoint where we can find the sample?

**Comment by pranavkm** [comment]
@TeunKooijman it's been moved to https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.SubAreaSample.Web.

**Comment by martin-luo** [comment]
> @TeunKooijman it's been moved to https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.SubAreaSample.Web.

Unfortunately by today (8 October 2018), the link is dead again.

**Comment by pranavkm** [comment]
We renamed our branches recently - the sample's located at https://github.com/aspnet/Entropy/tree/master/samples/Mvc.SubAreaSample.Web
