### ISSUE TITLE
Modelbinding with JSON data

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/Mvc#1602]
Having problems getting model binding to work with an API endpoint that's receiving JSON data. Looking at the MusicStore SPA example code I can see that there's a no parameter API endpoint and then simply using TryUpdateModel().

Tried this in my own example, but I'm unable to make this work.

```c#
        public async Task<Album> Album()
        //public async Task<Album> Album([FromBody] Album postedAlbum)
        {
            int id = 3;// postedAlbum.Id;

            Album album = null;
            if (id < 1)
                album = context.Albums.Add(new Album());
            else
            {
                album = await context.Albums
                    .Include(ctx => ctx.Tracks)
                    .Include(ctx => ctx.Artist)
                    .FirstOrDefaultAsync(alb => alb.Id == id);

                if (album == null)
                    throw new ApiException("Invalid album id", 404);
            }

            // ModelBinding doesn't work right at the moment
            if (!await TryUpdateModelAsync(album, null))
                throw new ApiException("Model binding failed.", 500);

            int result = await context.SaveChangesAsync();

            return album;
        }
```

TryUpdateModelAsync() doesn't fail but it also doesn't update anything. Modelstate is empty.

I've also tried updating by using the parameter - that works - the parameter gets set, but then ModelState still contains no data at which point I can manually update.

I would expect model state to be set in either scenario but currently I don't see ModelState set from JSON data.

**Comment by yishaigalatzer** [comment]
We are planning to resolve this with #1776, the actual work is tracked by #1654 and #1642, we don't plan to build a mapper in the system, we verified our scenarios with AutoMapper on the desktop framework. When AutoMapper becomes available to CoreCLR it will enable the scenario there as well
