### ISSUE TITLE
Logging: Filters

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Mvc#1629]
As a consumer of the logging output for Filters, I would like to be able to tell which filters are registered with the system, when filters execute (including each of the various states it goes through - ing vs. ed) and why (i.e. which controller/view is responsible, etc), etc.

If you are looking for an example of what we are wanting to do with this data, have a look at the following - http://getglimpse.com/Docs/Execution-Tab
![executiontab](https://cloud.githubusercontent.com/assets/585619/5175004/358ff596-73eb-11e4-83fc-e2b7cc24eb36.png)
The above shows the various filters that have run for a given request.

**Comment by danroth27** [comment]
From #1561, log when a filter short-circuits.

**Comment by kichalla** [comment]
687ab258a192198bd3cf6e33cd46ad8a67cb2f45

**Comment by avanderhoorn** [comment]
Thanks!
