### ISSUE TITLE
Modelmetadata provider should throw if it detects more than one  IBinderMetadata associated with a model

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#1638]
Current behavior is using ```FirstOrDefault``` we should change it to ```SingleOrDefault``` with appropriate exception.
https://github.com/aspnet/Mvc/pull/1546/files#diff-4d8c97ccbb19f56bde7a555943db021aL41

**Comment by danroth27** [comment]
Dup of #1597.
