### ISSUE TITLE
Bring back Controller.ValidateModel/TryValidateModel

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#1642]
Talked about this with @yishaigalatzer 

We need to bring back the `Controller.ValidateModel` and `Controller.TryValidateModel` methods to enable easy validation of objects in the scope of an action method.

See http://msdn.microsoft.com/en-us/library/ff356143(v=vs.100).aspx

**Comment by andrewm1986** [comment]
I don't know if it's planned but it would be useful to have DI support for another validation framework

**Comment by kirthik** [comment]
checked in - e41e5066f991c8ca74f8d6d87d2f41590784b634
