### ISSUE TITLE
Binding: Ignore indices of captured array

### ISSUE THREAD

**Issue by am11** [aspnet/Mvc#1647]
Consider the following field-set resides in a form:

``` html
<input type="text" name="Tags[0].Name" id="tags[0].Name" />
<input type="text" name="Tags[1].Name" id="tags[1].Name" />
<input type="text" name="Tags[2].Name" id="tags[2].Name" />
```

When we submit this form, `model.Tags` is assigned the collection with three elements. But if we remove `#tags[1].Name`, it breaks the sequence, and therefore, the parameter binding ignores all elements after `Tags[0].Name`.

Please make it so, that it ignores the index value and we don't even have to provide index in name, as in: `Tags[].Name`. In which case, binding would only follow the order in which the values were presented.

This comes _very_ handy, when we have a UI, where we can add / drop collection properties in one-to-many and many-to-many entity relationships, without caring about maintaining the indices in JavaScript code. Instantly, it would make our JS code _extremely_ simple, when we are dealing with some crazy, complex, n-ary, nested relationships: `Name[i].Place[j].Animal[k].Thing[].TagName`. The index for `Thing[]` would be maintained automatically.

This extends to other types of input as well: multiselect control, set of checkboxes and since so forth.

BTW, this is how it works with `ActiveRecord`, the ROR's answer to `EntityFramework`. :sunglasses: 

Thanks!

**Comment by annayafi** [comment]
I would love to see this feature implemented and to stop worrying about maintaining the indices in sequential order or stop implementing custom model binders every time.
