### ISSUE TITLE
Possible broken API for DropDownList and similar methods

### ISSUE THREAD

**Issue by joanbarros** [aspnet/Mvc#1656]
### Functional Impact
I've found, what I believe to be a small inconsistency in the API and the way the method DropDownList and similar methods are used. This Issue Post is more a question than a bug report. I want to know which is the desired behavior of the API in this case and if this is in fact a bug.

### Minimal repro steps

1. Create a `SelectList` object with a collection of `SelectListItems` and set a default item other than the first one.
2. Create a *View* with a *DropDownList*

### Expected result
I would expect the method to contain an overload that receives a `SelectList` object and take the `selected` item from there.

### Actual result
When you pass a `SelectList` object via the `ViewBag` collection, it successfully uses the selected item specified in the `SelectList` object. But there is no overload for the DropDownList method that takes a `SelectList` and it only accepts a `IEnumerable<SelectListItem>`. Because of this the information in the `SelectList` object is lost.

### Conclusion
So we are seeing a discrepancy where in one case the user of the `SelectList` object is accepted but the other (that should enable the same functionality) does not.

**Comment by rynowak** [comment]
@dougbu can you try and put together a sample demonstrating this?

**Comment by dougbu** [comment]
@joanbarros for example you can change the MVC sample, to show default selection with `SelectList`.

* update https://github.com/aspnet/Mvc/blob/dev/samples/MvcSample.Web/HomeController.cs#L208 to read
```
return new SelectList(addresses, selectedValue: addresses[3]);
```
* update https://github.com/aspnet/Mvc/blob/dev/samples/MvcSample.Web/HomeController.cs#L215 to read
```
return new SelectList(ages, dataValueField: "Age", dataTextField: "Display", selectedValue: 32);
```

with these changes, the /Home/Create page:
![capture1](https://cloud.githubusercontent.com/assets/6431421/5641900/c3791cd0-95f5-11e4-8d09-6f7aa07428c8.png)

now shows default selections:
![capture2](https://cloud.githubusercontent.com/assets/6431421/5641839/a7669276-95f4-11e4-95db-b066718a2273.png)

notes:
- the `SelectList` instances in this sample are treated as `IEnumerable<SelectListItem>` everywhere but where they are created
- nothing deals with default selection elsewhere; the `SelectListItem` items indicate selection
- default selection is visible on the page only when the `DropDownList()` or `ListBox()` expression value is `null` (on initial load in this case); same for the related `*For()` methods

**Comment by joanbarros** [comment]
I see this has been closed. That's great. I've yet to read the outcome. Sorry, something came up that kept me busy.

Anyways here is a gist with the reproduction: [Gist](https://gist.github.com/2f0b57fe91a692fcbf3a.git) 
Better late than never ehh? lol
