### ISSUE TITLE
Consider ConfigureMvc/Routing extensions

### ISSUE THREAD

**Issue by HaoK** [aspnet/Mvc#1669]
Most of the other frameworks have extension methods for Configure<XyzOptions>,

```
Configure<MvcOptions> -> ConfigureMvc
Configure<RouteOptions> -> ConfigureRouting

<!---
@huboard:{"custom_state":"ready"}
-->

**Comment by yishaigalatzer** [comment]
We should also rename the `ConfigureMvc` method in `MvcOptionsSetup` to avoid name collission/confusion.

https://github.com/aspnet/Mvc/blob/9ac37fbc7a0be1138d69493a9a3d50a0a5e04826/src/Microsoft.AspNet.Mvc/MvcOptionsSetup.cs#L24

**Comment by sornaks** [comment]
https://github.com/aspnet/Mvc/commit/6e8cc6ba74089f5d821c2ae8342d7e8ec50448fc
