### ISSUE TITLE
Tag Helpers: Change `ValidationSummaryTagHelper`'s property to `ValidationSummary` type (`enum` not a `string`)

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#1685]
The MVC Tag Helpers include some properties that are enums, e.g. the `ValidationSummaryTagHelper`. Currently they are typed as `string` and attempt to convert the string to the appropriate enum value otherwise they throw. They should just be typed as the enum directly.

**Comment by dougbu** [comment]
previous subject was "Tag Helpers: Enum properties should be typed as the Enum and not attempt any conversion".  `ValidationSummaryTagHelper` is the only MVC tag helper that performs conversion.

**Comment by dougbu** [comment]
@DamianEdwards current helper `throw`s if it cannot parse the `asp-validation-summary` (`string`) value.  once I fix this, the compiler will handle `asp-validation-summary="Garbage"` and similar errors.

what behaviour would you like for undefined `ValidationSummary` values e.g. `asp-validation-summary="ValidationSummary)23"`?  compiler would be happy but should the tag helper `throw` or ignore the value?

**Comment by dougbu** [comment]
talked offline w/ @DamianEdwards:
- undefined `ValidationSummary` values should `throw`
- move the `ValidationSummary` type to the `Microsoft.AspNet.Mvc` namespace so .cshtml authors don't need to type `Microsoft.AspNet.Mvc.TagHelpers.ValidationSummary.All` or add the appropriate `@using`

**Comment by dougbu** [comment]
Fixed via 9b2a9e397649a928f85f323fe44a915af260035a
