### ISSUE TITLE
Create a '<trace />' Tag Helper to show server trace information in the browser

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#1688]
Create a new Tag Helper that enables showing server trace information for the current request in the browser. The canonical use case is to easily see warnings emitted by Tag Helpers to aid in debugging rendering issues.
### Usage

``` HTML
<trace [level=""]
    [sources=""]       
    [output=""] />
```
#### Alternate

``` HTML
<trace [output=""]>
    <source name="" [level=""]>
</trace>
```
### Arguments

| Attribute Name | Type | Details |
| --- | --- | --- |
| level | `Microsoft.Framework.Logging.LogLevel` | The level of log messages to include. The default is `Microsoft.Framework.Logging.LogLevel.Error` |
| sources | `string` | A comma-separated list of `ILogger` names to include. The default is `String.Empty` which means show all. |
| output | `Microsoft.AspNet.Mvc.TagHelpers.TraceOutput` | An enum that specifies where to show the trace messages in the browser. Possible values are: `Console`, `HtmlComment`, `Inline`. Default is `Console` |
#### Console

This mode should log the messages to the browser's debug console by emitting a `<script>` block using the various methods available on the `console` object (https://developer.mozilla.org/en-US/docs/Web/API/Console). Note that this isn't a standards based API so a polyfill shim should also be emitted.
#### HtmlComment

This mode should emit an HTML comment that contains all the log messages formatted appropriately.
#### Inline

This mode should emit an HTML table that contains all the log messages formatted appropriately.
### Example

This will show all warnings emitted by the MVC Tag Helpers in the browser console:

``` HTML
<environment name="Development">
    <trace level="LogLevel.Warning" sources="Microsoft.AspNet.Mvc.TagHelpers" output="TraceOutput.Console" />
</environment>
```

**Comment by yishaigalatzer** [comment]
Talked with @Eilon and @loudej and decided we don't want to address this (even as a side project) for MVC 6 first release.

**Comment by rynowak** [comment]
This is pretty wacky. @DamianEdwards does this still make sense?

**Comment by DamianEdwards** [comment]
Nah
