### ISSUE TITLE
MVC Tag Helpers Options objects

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#1689]
All MVC Tag Helpers should have corresponding options objects to allow applications to globally set default runtime behavior. Each Tag Helper should have its own options object defined along with a `Configure[Name]` extension method. 

### Example
The `FormTagHelper` should have an options object somewhat like the following defined:
``` C#
namespace Microsoft.AspNet.Mvc.TagHelpers {
    public class FormTagHelperOptions {
        /// <summary>
        /// A bool that indicates whether the anti-forgery token should be generated.
        /// </summary>
        /// <value>Defaults to <c>null</c>, which indicates a token will only be generated if the <c>action</c> attribute was not explicitly defined.</value>
        public bool? AntiForgery { get; set; }
    }
}
```

The `FormTagHelper` itself should be updated to retrieve this options object from the DI system and use it to determine default behavior.

The corresponding configure helper extension method that would just call through to `Configure<FormTagHelperOptions>`:
``` C#
public static IServicesCollection ConfigureFormTagHelper(Action<FormTagHelperOptions> configureCallback)
```

**Comment by yishaigalatzer** [comment]
@DamianEdwards do you want come up with the list of options we want to support per tag helper, or should we just assign this to an Engineer that will gather the requirements?

**Comment by DamianEdwards** [comment]
We're changing plans slightly and instead going with a feature that allows simple initialization of Tag Helpers before they're executed. See PR #2135 for initial design discussion.

**Comment by DamianEdwards** [comment]
Reverting this in favor of Tag Helper initializers #2162
