### ISSUE TITLE
TagHelper and RazorPreCompileModule don't work in the same project and reference projects

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#1693]
I have a TagHelper in the web project itself (not as a reference) and I want to use RazorPreCompileModule in that project. This throws during compilation because the preprocess step tries to load the assembly that is currently created and cannot find it (yet).

**Comment by pranavkm** [comment]
FYI - we do `Assembly.Load` to load tag helper assemblies. During precompilation, the `AssemblyResolve` event is not hooked up by KRE so you don't get any of the KRE behavior for assembly loading. Essentially even if you do have TagHelpers in a separate assembly, we fail to load it.

We should consider using the `IAssemblyLoadContext` to load tag helpers assembly. However this does not get flown from the KRE into the application today (both during runtime and precompilation).

cc @davidfowl

**Comment by NTaylorMullen** [comment]
Note that changing to `IAssemblyLoadContext` goes hand in hand with these two issues:

1. https://github.com/aspnet/Razor/issues/254 - **Add a first class extensibility point for assembly resolution of exported types**
1. https://github.com/aspnet/Razor/issues/230 - **Tag Helpers: Investigate Assembly.Load vs. IAssemblyLoader.Load in DTH / Runtime**
