### ISSUE TITLE
Consider a way to turn off generating prefixes for model state keys for `[FromBody]` parameters

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1694]
Consider the action
`public IActionResult PostValue([FromBody] Person postedPerson)`

The Json payload that might get posted to this action would look like:
`{ name: "Person Name", Age: -13 }`

In the event of model validation errors, we prefix the value of the parameter to the property name, so the dictionary would look like:

```C#
{ "postedPerson.Name": "The field Name should have a length of at most 8" },
{ "postedPerson.Age": "Age must be a positive integer." }
```

The generated key names are consistent with 5.2. However for a client to consume this `ModelState` as is, it needs to be aware of the parameter name. In 5.2, the parameter name isn't documented as part of the help page, so it's not particularly discoverable. 

We should consider making the prefix behavior changeable or have `FromBody` use `IModelNameProvider` so a user could change it on a per parameter basis.

**Comment by danroth27** [comment]
@kirthik Could you please investigate what the impact of this behavior is on when doing a JSON serialized jQuery POST to an action that renders a partial view? Do you not get validation errors in that case?

**Comment by kirthik** [comment]
We get do validation errors from ModelState in partial view but validation errors(ModelState keys) are prefixed with parameter name(ex : cat.CategoryName). So if user wants to get validation error on a particular property, he needs to know the parameter name or loop through all validaton errors in modelstate.

**Comment by rynowak** [comment]
I believe we got similar feedback re api-description from @domaindrivendev. The parameter names in user code often aren't relevant.

**Comment by rynowak** [comment]
@kirthik what was the decision here? I see a PR out for review but I don't get what it's supposed to do. Is this behavior configurable? How?

**Comment by Ciantic** [comment]
I hope it's configurable somehow, in my Web Api the parameter names are used as key names in request, so they are meaningful.

**Comment by kirthik** [comment]
@rynowak - the decision was to remove prefix.

**Comment by kirthik** [comment]
Fix checked in - 2b246e7acc50a4a3fc19d5e36578e194d1bd94e3

**Comment by gravikrishna** [comment]
Hi,

In which version of MVC is this fixed. I'm suing 5.2.3 and I can still see the prefix coming for the Model objects in the params.

Thanks

**Comment by davidfowl** [comment]
@gravikrishna This is ASP.NET Core 1.0 MVC. It's not the same thing as MVC 5.x. This repository is for .NET Core, not .NET Framework.

**Comment by gravikrishna** [comment]
@davidfowl  Thanks a lot for the update. Can you please let me know if this feature is available in MVC 5.x ? I'm having this issue here and am not sure how to go about this.

**Comment by dougbu** [comment]
This fix was specific to `[FromBody]` in ASP.NET Core 1.0 MVC. Please file MVC 5.x bugs at http://aspnetwebstack.codeplex.com/workitem/list/basic

**Comment by gravikrishna** [comment]
Thanks @dougbu
