### ISSUE TITLE
Implement respon_to like Rails do

### ISSUE THREAD

**Issue by luizbon** [aspnet/Mvc#1705]
Rails have one really interesting and pratical way to determine not only witch view some action return, but witch type of view it respond based on extension from querystring.
This can be much helpfull to integrate with SPA applications and mobile fliendly web sites.

Basically it looks at the file extension on request and decide witch view will be rendered in response.

So if we want an Action to respond XML, JS, JSON or HTML we'll have three views view.xml.cshtml, view.js.cshtml, view.json.cshtml, view.cshtml respectivelly.

These are some references to rails implementation of respond_to:

http://guides.rubyonrails.org/action_controller_overview.html#rendering-xml-and-json-data
http://apidock.com/rails/ActionController/MimeResponds/InstanceMethods/respond_to

This one this a even more recent and better aproach that is more real to ASP.NET world
http://api.rubyonrails.org/classes/ActionController/Responder.html

**Comment by rynowak** [comment]
We have no plans to add views/html to the content negotiation system by default. Suggest closing this.

/cc @Eilon
