### ISSUE TITLE
MutableObjectModelBinder.GetPropertyValidationInfo should not reflect over `ModelType.Properties`

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1712]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ModelBinding/Binders/MutableObjectModelBinder.cs#L305-L306

In the MutableObjectModelBinder we attempt to look for `BindingBehaviorAttribute` on properties. As part of this, we iterate over all properties on the `ModelType`. This is problematic in

1. There is a mismatch in the properties we discover as part of  `ModelMetadata` and the ones that are   discovered here. For instance `ModelMetadata` ignores indexers versus this does not. Consequently a model with indexers causes an exception to be thrown at https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ModelBinding/Binders/MutableObjectModelBinder.cs#L309.

2. Reflecting on the type as opposed to using property metadata seems to be against the established pattern of reading cached metadata.

**Comment by rynowak** [comment]
Triage: This is a follow-on to the model-metadata work and should be considered for RC.

**Comment by rynowak** [comment]
f3679f214e85b64bc4d7387e34753f4b8e01beb8
