### ISSUE TITLE
Missing overload for registering model binders

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#1724]
In MVC 5 a user can register a modelbinder by specifying the type to bind to, and the model binder type

```
    ModelBinders.Binders.Add(typeof(Person), new PersonModelBinder());
```

In MVC 6, we don't have this overload and the user have to write the code directly in his binder.

For compatibility we should add back this overload, and do the appropriate wrapping to make it work.

@ajaybhargavb please work with @rynowak on design for this.

See SO link - http://stackoverflow.com/questions/27451661/setting-the-type-of-an-object-a-custom-binder-would-apply-to-in-a-vnext-applicat

**Comment by danroth27** [comment]
@rynowak Could you please look at this as part of updating the binder contract?

**Comment by ajaybhargavb** [comment]
There is an open PR for this already. https://github.com/aspnet/Mvc/pull/1779
