### ISSUE TITLE
TagHelper allow hide/show/disable on tag

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1729]
@andrebaltieri said:

Hey guys, do we have a feature on TagHelper to hide/show/enable/disable a piece of HTML based on a Razor condition? Something like:
``` html
<div show="User.IsAuthenticated">
```

Something that bothers me is to have a lot of `if`s on HTML code.

Today we have such similar behavior on AngularJS with `ng-show` for example.
Is it (or will it be) possible with Razor?

Thanks!

**Comment by tuespetre** [comment]
Angular also uses ng-if to determine whether to actually output the element into the HTML at all. Is this something that is even possible with the Tag Helpers API? I haven't actually worked with it yet; can you use it to render other alternate output in a way that represents the current element?

**Comment by tuespetre** [comment]
Excuse me, I meant to say "in a way that replaces the current element".

**Comment by Eilon** [comment]
In Razor you can use an `@if()` statement to control what gets rendered/run.
