### ISSUE TITLE
Getting array from url query

### ISSUE THREAD

**Issue by guy-lud** [aspnet/Mvc#1738]
I wounder if MVC 6 is going to support array of primitive type at from the Url

For example the url http://www.someDomain.com/data=[1,2,3] 

The actionInvoker will bind the json array to int[] data or even IEnumerable<int> data ?

to support such a thing today we override the ActionInvoker, yet on WDCIL talk @yishaigalatzer gave last week he recommended not to override it in MVC 6.

**Comment by yishaigalatzer** [comment]
@guy-lud like @rynowak mentions, you really don't need to override the action invoker for this, neither in MVC 5 or Web API 2.

We don't plan to add this syntax as it's really non standard, feel free to ping us for more advice if the solutions above do not resolve your scenario.
