### ISSUE TITLE
[TagHelper] InputTagHelper should generate the self-closing <Input /> element

### ISSUE THREAD

**Issue by ianhong** [aspnet/Mvc#1739]
When the Input tag helper is used without the "asp-" attributes as follows:

```html
        <input type="submit" />
```

It generates the following HTML elements:

 ```html
       <input type="submit"></input>
```

It should be `<input type="submit" />` instead.

But if using

```html
     <input asp-for="XXX" type=submit" />
```

It will generate correctly with a self closing tag.

**Comment by yishaigalatzer** [comment]
Duplicate of #1571
