### ISSUE TITLE
AuthorizeAttribute(IEnumerable<Claim>) doesn't make sense

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Mvc#1740]
_From @victorhurdugaci on April 29, 2014 20:42_

The constructor overload for AuthorizeAttribute taking an IEnumerable\<Claim\> as argument doesn't make sense because .NET expects all attribute arguments to be compile time constants.

cc @sebastienros 

_Copied from original issue: aspnet/Security#9_

**Comment by rynowak** [comment]
Also, since AuthorizeAttribute is a filter, you can manually construct it and add it as a global filter. Seems like we should leave this around.

**Comment by yishaigalatzer** [comment]
I agree with @rynowak in general, and that was the original intent. Either way we are rewriting the authorize attribute and this overload will does not fit in the new design see #1664.

@HaoK

**Comment by sebastienros** [comment]
Yeah !
