### ISSUE TITLE
Propose updating samples\MvcSample.Web\Views\Home\ValidationSummary.cshtml

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Mvc#1743]
Currently ValidationSummary.cshtml incorrectly displays: 

```<p>Below are all overloads for Html.ValidationSummary.  You should see 5 validation summary titles and 4 validation summary error messages.</p>```

It's missing two new ValidationSummary overloads. I'll add these and clean up the output a bit. In lieu of:

``` 
@Html.ValidationSummary(message: "Hello from validation message summary N.")
```

I'll do something like

```
@Html.ValidationSummary(message: "ValidationSummary overload: excludePropertyErrors,message,htmlAttributes"
```

**Comment by Eilon** [comment]
Fixed in 4b1a708ba16ec19e2b85cec67ed0f6f3b6cca3ca
