### ISSUE TITLE
Proposal: Simple API for configuring Json and Xml Formatters to Preserve References

### ISSUE THREAD

**Issue by tonysneed** [aspnet/Mvc#1744]
When entities are generated from an existing database, they often contain cyclical references, which cannot be handled by the Json and Data Contract serializers by default. Most of the time, developers will add attributes to entities which instruct the serializer to preserve object references: [JsonObject(IsReference=True)], [DataContract(IsReference=True)]. This pollutes entities with attributes pertaining to serialization concerns, which is especially distracting with the DCS, which then requires [DataMember] attributes on each property.

As an alternative to attributes, developers can configure the Json and DC formatters to preserve references, but the API is not as straightforward as it could be. You need to find and/or replace the existing formatters, and in the case if the Xml DC formatters, you need to extend the base class and override CreateDataContractSerializer.

I would like to propose a simpler API for configuring Json and Xml formatters to preserve references.  The form of the API is up for discussion, but the goal would be to make serialization configuration easier and more extensible.

One possibility is a Fluent API style, which would accommodate additional methods for configuring other aspects of the formatters. For example:

```csharp
services.AddMvc()
    .Configure<MvcOptions>(options =>
    {
        options.InputFormatters.Configure<JsonInputFormatter>().PreserveReferences();
        options.InputFormatters.Configure<XmlDataContractSerializerInputFormatter>().PreserveReferences();
    });
```

I'm looking forward to receiving feedback on this proposal.

Cheers,
Tony Sneed

**Comment by danroth27** [comment]
We are happy to consider a pull request that makes configuring formatters easier. We should probably discuss the design further. Can we take a look at your code?

Please note that as part of #1765 we are planning on separating out the XML formatter into its own package.

**Comment by tonysneed** [comment]
Hi Dan,

I'd love to talk about a good design for simplifying configuration of serializers, and especially for handling cyclical references.  One of the first errors I usually get after reverse engineering EF entities is the serializer complaining about cycles.  While there are patterns which solve it, I think it would be nice to easily set an option in startup and have it "just work."

Here is a GitHub repo I set up with my solution for MVC 6:
https://github.com/tonysneed/aspnet-mvc-6-contrib

I also have one for Web API 2, which is helpful for client-side formatter configuration:
https://github.com/tonysneed/aspnet-webapi-2-contrib

For a bit of background, here is a blog post I wrote:
http://blog.tonysneed.com/2015/01/02/handle-cyclical-references-with-asp-net-web-api-2-and-mvc-6

I think it's a good idea to separate Xml and Json formatters.  Also, I plan to help port Protobuf-net, both as a portable lib and for AspNet Core.

Cheers,
Tony

**Comment by yishaigalatzer** [comment]
Hi Tony,

I looked at the design for the Web API 2, and I like the general approach to the design. But I would like to refrain from adding one specific extension method (like the one in the mediatypecollection) right in the framework.

Instead what I would like to do is add a set of extension methods like #1787, that allows direct access to the formatters (and allows removing them/changing them and direct access to the instance etc.).

We can then add the configuration suggestion you have directly to the formatter itself. Although i'm 50/50 on the json one, as it is just a simple assignment, the XML one however seems very useful.

In the meantime make sure you have a CLA signed, so you can take your contributions. Once we lock down the design we would be happy to take both #1787 and this issue from you (if you'd like).

**Comment by tonysneed** [comment]
I signed the CLA and am ready to go.  I can start with #1787 and a set of extension methods providing direct access to the formatters.  Then I can propose a design for modifying the formatters for preserving references in order to handle cyclical references.  Glad I can help!

**Comment by yishaigalatzer** [comment]
@tonysneed this is awesome. Note that we have locked on the API surface we are looking for yet, and we are going to have some discussion early next week. If you have more feedback on the design please bring it on, so we can consider it before finalizing the pattern.

I will also let you know when you CLA was approved so we can actually take the PRs.

Thanks!

**Comment by tonysneed** [comment]
Alright, here's my first pass on the API design for the formatters.  I like the approach that Json.Net takes with its formatter, namely, to expose a SerializerSettings property, which is of type JsonSerializerSettings.  Similarly, the XmlDataContractSerializerInputFormatter should expose a SerializerSettings property of type DataContractSerializerSettings.

That would make it just as easy to configure the DCS as it is to configure the Json.Net serializer.  Furthermore, a reference to serializer settings allows for setting a number of configuration options, including but not limited to preserving references.  Implementing this would be straightforward because you just pass the settings to the ctor of DataContractSerializer in the CreateDataContractSerializer method of the formatter.

If you have either a JsonSerializerSettings or a DataContractSerializerSettings, you could set both the input and output formatter for either Json or Xml to it.  As a convenience, we could also add an extension method to MvcOptions which gets both the input and output formatters for either Json or Xml and configures them in one shot with a serializer settings parameter.

**Comment by tonysneed** [comment]
@yishaigalatzer, just following up to see if my CLA was approved yet and what you think about my proposed API design?

**Comment by yishaigalatzer** [comment]
Your CLA has been approved.

I would start with individual PRs.

PR 1 - First lets make DCS expose settings, note that we are in the process of changing the XML formatters (moving them to another package, and removing XML by default),
also note that DCS unfortunately derives from XML formatter (which we plan to change soon).
PR 2 - Add extension methods to access the formatters by type

I wouldn't do the one shot method, we separated the formatters and I'd rather not have these methods, a user can write two lines of code instead of one.

**Comment by tonysneed** [comment]
Great, I'm now working on getting the Mvc.Core project to build.  I've upgraded to KRE 1.0.0-rc1-10894, following [these instructions] (https://github.com/aspnet/home#running-the-samples). But I'm getting 12 errors when attempting to build the Mvc.Core project.  They are all for Filters\AuthorizeAttribute.cs and most relate to not finding AuthorizationPolicyBuilder.  Any ideas?

**Comment by yishaigalatzer** [comment]
It's a build break, should be resolved soon

**Comment by tonysneed** [comment]
Whew! Thanks for working to get that fixed. :+1:

**Comment by tonysneed** [comment]
@yishaigalatzer, Now we're down to just one error in Microsoft.AspNet.Mvc:
MvcServiceCollectionExtensions.cs(29,22): ASP.NET 5.0 error CS1061: 'IServiceCollection' does not contain a definition for 'AddAuthorization' and no extension method 'AddAuthorization' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

**Comment by tonysneed** [comment]
I resolved issue #1848 by clearing my local packages cache and restoring.  I am now able to build the Mvc solution without errors.

**Comment by tonysneed** [comment]
I've pulled the latest and am working on exposing DCS settings from XmlDataContractSerializerInputFormatter and XmlDataContractSerializerOutputFormatter.

**Comment by yishaigalatzer** [comment]
Assigned to @kichalla so he can merge and close the issue (after we are done with the cleanup PRs as well).  The rest of the work is in #1787
