### ISSUE TITLE
Add `ModelMetadata.AdditionalValues` property bag extensibility point

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Mvc#1758]
I'm trying to create my own `Object.cshtml` which groups properties based on `DisplayAttribute.GroupName` and surrounds them with a `fieldset`.

```c#
var groups = from property in ViewData.ModelMetadata.Properties
    where property.ShowForEdit && !ViewData.TemplateInfo.Visited(property)
    group property by property. // <- GroupName? 
    into g
    orderby g.Key
    select new { Group = g.Key, Properties = g };
```

In previous version of MVC I used the following extension method

```c#
public static string GetGroupName(this ModelMetadata modelMetadata)
{
    if (modelMetadata.AdditionalValues.ContainsKey(ExtendedDataAnnotationsModelMetadataProvider.Key_GroupName))
        return (modelMetadata.AdditionalValues[ExtendedDataAnnotationsModelMetadataProvider.Key_GroupName] as string);
    return null;
}
```

which in turn used a custom

```c#
public class ExtendedDataAnnotationsModelMetadataProvider : DataAnnotationsModelMetadataProvider
{
    public const string Key_GroupName = "GroupName";
    protected override ModelMetadata CreateMetadata(IEnumerable<Attribute> attributes, Type containerType, Func<object> modelAccessor, Type modelType, string propertyName)
    {
        ModelMetadata modelMetadata = base.CreateMetadata(attributes, containerType, modelAccessor, modelType, propertyName);
        DisplayAttribute displayAttribute = attributes.OfType<DisplayAttribute>().FirstOrDefault();
        if (displayAttribute != null)
            modelMetadata.AdditionalValues[Key_GroupName] = displayAttribute.GroupName;
        return modelMetadata;
    }
}
```

Because the `AdditionalValues` property does not exist my code does not work so how could I do something similar using MVC 5?

**Comment by dougbu** [comment]
@marcuslindblom the `AdditionalValues` property bag will come in when we fix #324.  I don't have a good alternative to suggest in the meantime.

Will add comments to #324 about this use case.  That bug is scheduled for the 6.0.0-rc1 milestone, which is the milestone we're currently working on.

**Comment by marcuslindblom** [comment]
@dougbu Ok, thanks!

**Comment by dougbu** [comment]
Reopening since the larger #324 has been postponed.  Work here is to provide the `AdditionalValues` property bag (from MVC 5) in the MVC 6 `ModelMetadata`.

**Comment by dougbu** [comment]
title was "Group properties based on DisplayAttribute.GroupName".  narrowing since aim here is to make that extension possible, not to provide it in MVC.

will do the following:
- add `AdditionalValues` property bag and a few related unit tests
- extend one of the functional tests to use `[DisplayAttribute(GroupName="name")]` as suggested

**Comment by dougbu** [comment]
Fixed in commits 330328628820324ed5073056cfcd5a97a890723c and f93fca1077174d7ca34bfae0eee143aeed45bb37

**Comment by marcuslindblom** [comment]
Is this still the best approach to group model properties or is this supported by default now? @dougbu

**Comment by dougbu** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem
