### ISSUE TITLE
Provide validation attributes for Checkbox control

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#1763]
From http://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/6891847-provide-validation-attributes-for-checkbox-control.

There is currently no good way to provide Required field Validation for a Checkbox control in ASP.NET MVC using Data Annotations. However, validation could easily be provided for ASP.NET Checkbox/Checkbox controls in ASP.NET Web Forms. ASP.NET MVC should be updated with validation support to match what is already available in ASP.NET Web Forms.

**Comment by rynowak** [comment]
I discussed this with @danroth27 and this isn't tracking anything valuable. A `[Required]` on a checkbox wouldn't do anything since our checkboxen always submit a value.
