### ISSUE TITLE
Remove passing password in clear text from MVC sample

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Mvc#1764]
The MVC.Sample includes model with password in clear text:

https://github.com/aspnet/Mvc/blob/dev/samples/MvcSample.Web/Models/User.cs#L27
https://github.com/aspnet/Mvc/blob/dev/samples/MvcSample.Web/HomeController.cs#L138

The password should be removed, it's not needed for the sample and encourages risky coding. I can do a PR with password removed.

**Comment by danroth27** [comment]
Cool, please go ahead and submit a PR. Thanks.

**Comment by danroth27** [comment]
We should look at doing a broader cleanup on the MVC sample

**Comment by Rick-Anderson** [comment]
Agreed, but you'll need a dev to do that.

**Comment by henkmollema** [comment]
@danroth27 @Eilon this can be closed. :smile:
