### ISSUE TITLE
All attributes of SelectTagHelper need to be lowercase

### ISSUE THREAD

**Issue by ianhong** [aspnet/Mvc#1768]
For example, 
            &lt;select asp-for="Products" asp-items="(IEnumerable<SelectListItem>)ViewBag.Items" multiple="multiple" /&gt;
generates the following select element:
            &lt;select Multiple="multiple" id="Products" name="Products"&gt;

The attribute, Multiple, should be 'multiple'. I found this problem from one attribute, multiple, but please make sure all attribute names are lowercase.

**Comment by Eilon** [comment]
@javiercn can you check if this is still an issue? I somehow doubt that it is...

**Comment by javiercn** [comment]
Does not repro anymore, closing it.
