### ISSUE TITLE
[ControllerUnitTest] Make the controller class not to throw an exception for simple unit tests 

### ISSUE THREAD

**Issue by ianhong** [aspnet/Mvc#1771]
This is related to #1504. To make this scenario work, we should update the controller class as follows:

            // Do not override ViewData.Model unless passed a non-null value.
            if (ViewData != null && model != null )
            {
                ViewData.Model = model;
            }
 
            return new ViewResult()
            {
                ViewName = viewName,
                ViewData = ViewData,
                ViewEngine = _viewEngine,
            };

**Comment by yishaigalatzer** [comment]
Fixed with 2cf56c7c83e26b114648e77ee93d7ff26528788a
