### ISSUE TITLE
Write functional tests to verify conventional routing, attribute routing and action selection

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#1775]
Currently we do not have functional tests to verify these. I am going to cover some basic scenarios but this work item is to provide extensive coverage in these areas.

**Comment by danroth27** [comment]
@kichalla Could you please enumerate the specific scenarios that you plan to cover for this? Thanks!

**Comment by danroth27** [comment]
We already have great test coverage in this space.
