### ISSUE TITLE
Make XML formatting behavior more consistent with JSON formatting

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#1777]
The behavior of the XML formatter is substantially different than the JSON formatter in how it handles different types. This means that you can easily get into cases where requesting  JSON just works, but if you request XML then the request might fail. Similarly, there are cases where a JSON request will work just fine, but data from an XML request might get ignored. Regardless of whether the XML formatter is enabled by default or not you should be able to use both XML and JSON and be reasonably confident that your Web API is functional. The current story is that you need to use the Data Contract programming model to get a consistent experience, but it sounds like this doesn't cover some common cases and we should consider going further.

This issue was raised by @nvivo as part of the discussion for #1765 and I have included his comments below:

I also have some serious opinions on whether content negotiation between xml and json by default is a good idea. Simple examples will always work, but in practice it is ridiculously easy to make things break with valid code. Consider this code:

```csharp
public object Get()
{
    return new
    {
        count = 3,
        records = new[] { 1, 2, 3 }
    };
}
```

This is a very common pattern for a web api + javascript, and the xml serializer will just blow up here complaining there is no DataContractAttribute in the anonymous object, while Json just works. 

There are also differences in how both serializers handle things that cause different behavior in applications using json vs xml. Look at this, using a empty web project with latest web api, default settings:

```csharp
public class SomeClass
{
    public SomeClass()
    {
        A = new List<int> { 1, 2 };
        B = new List<int> { 1, 2 };
    }

    public List<int> A { get; set; }
    public List<int> B { get; private set; }
}

public class ValuesController : ApiController
{
    public SomeClass Get()
    {
        return new SomeClass();
    }

    public SomeClass Post([FromBody] SomeClass x)
    {
        return x;
    }
}
```

Now, just get the values with different headers:

```
GET /api/values
Accept: application/json
``` 
```json
{ "A": [1, 2], "B": [1, 2] }
```

Same request with XML:

``` 
GET /api/values
Accept: application/xml
```
```xml
<SomeClass>
  <A>
   <d2p1:int>1</d2p1:int>
   <d2p1:int>2</d2p1:int>
  </A>
</SomeClass>
```

The default xml serializer ignores read only properties, so there is no "B" there, causing different client behavior.

Now for some issues in the input serialization:

```http
POST /api/values
Accept: application/json
Content-type: application/json
{ "A": [3, 4] }
```
Response:
```json
{ "A": [1, 2, 3, 4], "B": [1, 2] }
``` 
And with XML:
```
POST /api/values
Accept: application/xml
Content-type: application/xml
<SomeClass xmlns="http://schemas.datacontract.org/2004/07/WebApplication1.Controllers">
 <A xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
  <d2p1:int>3</d2p1:int>
  <d2p1:int>4</d2p1:int>
 </A>
</SomeClass>
``` 
```xml
<SomeClass>
 <A>
   <d2p1:int>3</d2p1:int>
   <d2p1:int>4</d2p1:int>
 </A>
</SomeClass>
``` 

Here, JSON.NET by default merges lists while the xml serializer replaces it. Those are just some things I found very quickly in real world apps.

**Comment by yishaigalatzer** [comment]
We are not planning to address this. If the DCS serializer will improve we will get the benefit in MVC, but we plan no major action here at this point.
