### ISSUE TITLE
Implement CacheProfiles for ResponseCache

### ISSUE THREAD

**Issue by sornaks** [aspnet/Mvc#1785]
Follow up to https://github.com/aspnet/Mvc/issues/536

**Comment by yishaigalatzer** [comment]
@sornaks please include the design suggestion in the description.

**Comment by sornaks** [comment]
Previously in MVC5 we supported `OutputCacheProfiles` in `Web.config` which is a pre-defined set of parameters for `OutputCache`. This provided a way to reuse the settings in multiple controllers/actions and a centralized place manage all Cache profiles. We do not have an equivalent for this in vNext.
 
<b>It looked like this:</b>
In Web.config:
```xml
<caching>
<outputCacheSettings>
   <outputCacheProfiles>
        <add name="Cache1Hour" duration="3600" varyByParam="none"/>
    </outputCacheProfiles>
</outputCacheSettings>
</caching>
```
 
Accessed in the Action like this:
```c#
[OutputCache(CacheProfile="Cache1Hour")]
public string Index()
{
    return DateTime.Now.ToString("T");
}
```
 
<b>Proposal for vNext:</b>
We can use MvcOptions to achieve the same. It would look something like this:
 
In Startup.cs
```c#
services.Configure<MvcOptions>(options =>
{
    options.CacheProfiles.Add(new CacheProfile() {
         Name = ”Cache1Hour”,
         Duration = 3600,
         VaryByHeader = “Accept”
    });
});
```
And my action would look like:
```c#
[ResponseCache(CacheProfile="Cache1Hour")]
public string Index()
{
    return DateTime.Now.ToString("T");
}
```
ResponseCache’s `OnActionExecuting` will look up the `MvcOptions` and get the `CacheProfile` with the particular name and populate the parameters needed to set the headers.

**Comment by rynowak** [comment]
@sornaks rather than accessing the options in `OnActionExecuting` we probably want to make this an `IFilterFactory` that uses a service. This is a design change we made recently for URL format.

**Comment by sornaks** [comment]
https://github.com/aspnet/Mvc/commit/4691823a5060db135c5672ba5b264183c999f5b3

**Comment by Tratcher** [comment]
@JunTaoLuo
