### ISSUE TITLE
Add support for model binding to immutable types by matching the query string to constructor arguments

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#1786]
I was playing around with SignalR today and there, you can add methods with immutable-type-parameters. When I call these methods from the client, SignalR / Newtonsoft.Json deserializes the sent JSON-object's properties to constructor parameters and it works as expected.

Can't MVC support immutable model types as well in action methods?

**Comment by Tragetaschen** [comment]
To summarize from JabbR:

Right now, Model Binding assumes the outer objects are already constructed when doing the inner ones. This doesn't work with immutable types.

**Comment by yishaigalatzer** [comment]
Seems interesting thing to discuss. Not sure what is the benefit of model binding to immutable types though. Can you elaborate?

**Comment by Tragetaschen** [comment]
My business logic is based on immutable objects. To create these objects from user input now, I have to duplicate them to a public-set, non-immutable version for MVC and on the server construct my immutable object within the request handling. So typically, this middle-man object just lives for about 5 statements within the code.
With the proposed model binding, I can get the corret object immediately.

**Comment by mpawelski** [comment]
:+1: 
I also prefer immutable objects and the fact that I can't share these objects with MVC action is annoying.

**Comment by rynowak** [comment]
As you can see from the backlog tag, we have no immediate plans to build this, but we may consider it if we invest heavily in this area in the future.

Closing this issue for now, this will be tracked by #6549
