### ISSUE TITLE
Separate XML serializers to Microsoft.AspNet.Mvc.Xml

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#1792]
Remove all references to XML Serializers from MVC, and create a new package that will include all the XML formatting concerns.

**Comment by kichalla** [comment]
`SerializableError` in Mvc.Core and `HttpError` in WebApiCompatShim depend on `System.Xml`, so not sure if we can remove the dependency on System.Xml 

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ActionResults/SerializableError.cs#L19

**Comment by kichalla** [comment]
Commit: 5c2dc5db11b63fd7b031aa265e8d51c10f2676f9
