### ISSUE TITLE
ODATA Support in ASP VNEXT? 

### ISSUE THREAD

**Issue by irinalocic** [aspnet/Mvc#1806]
What is the roadmap for upgrading OData assemblies to ASP.NET 5. 
I want to migrate multiple projects from ASP.NET 4 to ASP.NET 5 but  I can't do it because there is no support for ODATA in ASP.NET 5.
To be able to migrate ASP.NET 4 projects to ASP.NET 5 we urgently need a replacement for Microsoft.AspNet.WebApi.OData assembly (System.Web.Http.OData namespace).

**Comment by yishaigalatzer** [comment]
We currently have no firm roadmap for OData in ASP.NET 5 on the server side.

The work for OData (and the team responsible to prioritize the work) tracks the work in - https://github.com/OData/WebApi/issues
