### ISSUE TITLE
ObjectResult with status code and null value does not produce the status code

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#1809]
When a user return an `ObjectResult` with status code other than 200 with no content, the `HttpNoContentFormatter` overrides the status code provided on the result (and set by the result) and instead returns a 204.

Similarly if the user has explicitly set the `StatusCode` on the `Response` we have no way to know it and the formatter will override the user setting.

@Tratcher this keep coming up, it will be really nice to have a way to know if the `StatusCode` was changed by the user.

**Comment by yishaigalatzer** [comment]
When fixing this ignore the status code on the response, but respect the status code from ObjectResult. The NoContentFormatter should still act and short circuit so no json/XML with null is written

**Comment by ajaybhargavb** [comment]
https://github.com/aspnet/Mvc/commit/17aa21dc259a1d988faef80a576ed3b2bd4efc1c
