### ISSUE TITLE
Stress test for tag helpers

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#1812]
Need to build a stress test for Razor pages with tag helpers.

**Comment by Eilon** [comment]
Not planning on doing this at this time.

**Comment by NTaylorMullen** [comment]
We actually kind of do this already in the performance repo. I added a test that runs the default StarterMVC and does register/login/logout etc. all of which have `TagHelper`s heavily used. Not to mention all the usage in the Layout. I'd recommend closing as done :smile:

**Comment by Eilon** [comment]
@NTaylorMullen feel free to update this bug and point to the test(s) for reference.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Performance/commit/a994b64adf116251245fc7227711c001b90fdf04
