### ISSUE TITLE
Allow FlushAsync to work inside of tag helpers.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1819]
Consider a cache tag helper:

``` HTML
<cache>
Some child content
@await FlushAsync()
</cache>
```

The expectation is during the initial request to the page when the content is not cached, the tag helper renders and `FlushAsync` is invoked immediately after. For consecutive requests where the child content is never executed, we need to ensure that the Flush call continues to work.

Note: If the tag helper has multiple Flush calls, they'll be collapsed in to a single Flush.

**Comment by pranavkm** [comment]
Discussed this with @yishaigalatzer and @DamianEdwards. Currently `FlushAsync` or its variants do not work in tag helpers in general. A fix for this would require

1. Supporting `Flush` inside of tag helper blocks. A change to this would have to tie in to https://github.com/aspnet/Razor/issues/296.

2. Add additional behavior to `CacheTagHelper` that allows it to memoize the fact that `Flush` was called the first time content was rendered and replay it when serving the cached value.

**Comment by NTaylorMullen** [comment]
We may want to re-consider this issue given how many HTML elements now have `TagHelper`s acting on them. A good example of this restriction being a significant bother is people trying to append scripts (Glimpse does this) or link tags to their body or head tags. They'll create a `TagHelper` for the `<head>` or the `<body>` tag, essentially making `@await FlushAsync()` useless unless called in-between the `<head>` and `<body>` (unless someone for some reason adds an `<html>` `TagHelper`)

**Comment by Eilon** [comment]
Moving to Backlog because this seems like too big of an item right now. This is understandably important, but it has workarounds, as painful as they may be. I'm guessing the number of people using `Flush()` isn't very high.

**Comment by rynowak** [comment]
We've had no requests for this, and it would be a lot of work. 

Suggest closing /cc @Eilon

**Comment by DamianEdwards** [comment]
The point made about head and body Tags Helpers is now reality in 2.0, so I won't be surprised if this comes up again. I haven't yet tried pre-emptive flushing with Razor Pages but it should actually work **better** now, but this issue could kill it. I'll try it out and report back.

**Comment by DamianEdwards** [comment]
I did some investigation into this over at https://github.com/DamianEdwards/RazorFlushing

The addition of the `<head>` and `<body>` Tag Helpers (which are implicit, so can't be removed) means [this got harder,](https://github.com/DamianEdwards/RazorFlushing/blob/master/RazorFlushing/Pages/_Layout.cshtml#L23) while at the same time the Razor Pages `PageModel` approach makes [doing expensive work during view rendering](https://github.com/DamianEdwards/RazorFlushing/blob/master/RazorFlushing/Pages/FlushingTodos.cshtml) (which is required to get the most out of preemptive flushing) much [more natural](https://github.com/DamianEdwards/RazorFlushing/blob/master/RazorFlushing/Pages/FlushingTodos.cshtml.cs).

As a result, I think we should look at this again in 2.1

**Comment by danroth27** [comment]
@DamianEdwards Moving this to preview 2. Do we need this in 2.1? Should this be part of the Tag Helpers project?

**Comment by rynowak** [comment]
I still don't understand how this would work.
