### ISSUE TITLE
HttpStatusCodeResult should accept HttpStatusCode enumeration

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Mvc#1832]
Currently we have to cast status codes into integers to allow them to be passed into the HttpStatusCodeResult (and to the Response.StatusCode). While it would be better to have WebAPI-style status code helpers, in the absence of that the API should at least be on par with MVC5 which allowed this. In the current rev, this is what the status code looks like:

``` C#
    [HttpPost("")]
    public async Task<ActionResult> Post(Visit newVisit)
    {
      var username = User.Identity.GetUserName();
 
      newVisit.UserName = username;
 
      if (await _repository.AddVisitAsync(newVisit))
      {
        Response.StatusCode = (int) HttpStatusCode.Created;
 
        return Json(newVisit);
      }
 
      return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
    }
```

Ultimately i'd prefer a holistic solution like WebAPI, but can we at least not encourage the hard coding of status codes?

**Comment by yishaigalatzer** [comment]
I do agree with you that we probably don't want the users to have to memorize or cast status codes. The issue for this belongs in Http Abstractions Repo, but we can chat further here on the overall design and then file it in the right place. @Tratcher 

Also some other good news is we made a change (see https://github.com/aspnet/Mvc/commit/692a07240c34ee12c317eddb7cc28d744818b02d) that should alleviate some of this pain,

We tried to streamline the existing results and make them more useful without having to touch the response directly. For example, we added the status code directly to the json result.

For the specific sample in the comment above note that you already have the `CreatedResult` and you can control the fact that it will return json using the `Produces` attribute. (It does require a link, and you should probably provide it).

So your code can just look like:

```C#
    [HttpPost("")]
    [Produces("application/json")]
    public async Task<IActionResult> Post(Visit newVisit)
    {
      var username = User.Identity.GetUserName();

      newVisit.UserName = username;

      if (await _repository.AddVisitAsync(newVisit))
      {
          return Created("location", newVisit); // or use Uri, or CreateAtXXX overloads
      }

      return BadRequest();
    }

Also note that by default the XML formatter is not in, so the produces is not strictly required.

So we are thinking that for most users there is a way to write your code without worrying about hard coding status codes.

**Comment by Tratcher** [comment]
Enum was always a poor type for Http status codes. Static/const ints may be more appropriate. We recently added the following for common header names: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/HeaderNames.cs. Something similar for status codes would be reasonable.

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/issues/174

**Comment by yishaigalatzer** [comment]
@shawnwildermuth please let us know if you expect any other changes other then the ones we completed and aspnet/HttpAbstractions#174, if so please go ahead and reopen the issue.

**Comment by shawnwildermuth** [comment]
Yes, that fix only adds consts for header values, not return values.
