### ISSUE TITLE
SupportedMediaTypes for output formatters are incorrectly updated with charset data during requests

### ISSUE THREAD

**Issue by rmja** [aspnet/Mvc#1836]
To reproduce, configure a custom JsonOutputFormatter in Startup.cs as follows:

    services.AddMvc().Configure<MvcOptions>(options =>
        {
            var formatter = new JsonOutputFormatter();

            formatter.SerializerSettings = new JsonSerializerSettings();
            formatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();

            options.OutputFormatters.Clear();
            options.OutputFormatters.Add(formatter);
        });

In the first two requests, the custom settings are used, and the returned properties are camel case. After the first two requests, the settings are not respected, and the default json formatter settings are used.

I have tracked the problem to CanWriteResult() in OutputFormatter.cs. In the **first request**, the SupportedMediaTypes reads as follows:

    SupportedMediaTypes[0].Charset == null
    SupportedMediaTypes[0].MediaType == "application/json"
    SupportedMediaTypes[0].Charset == null
    SupportedMediaTypes[0].MediaType == "text/json"

and

    SupportedMediaTypes[0] == SupportedMediaTypes.FirstOrDefault(supportedMediaType => supportedMediaType.IsSubsetOf(contentType))

In the **2nd request**, the SupportedMediaTypes reads as follows:

    SupportedMediaTypes[0].Charset == "utf-8"
    SupportedMediaTypes[0].MediaType == "application/json"
    SupportedMediaTypes[1].Charset == null
    SupportedMediaTypes[1].MediaType == "text/json"

In this case:

    SupportedMediaTypes[1] == SupportedMediaTypes.FirstOrDefault(supportedMediaType => supportedMediaType.IsSubsetOf(contentType))

Note the index change. The first supported media type is not found anymore. From now on the SupportedMediaTypes are fully populated with Charset data, and the custom json formatter is not found by the `.FirstOrDefault()`.

**Comment by rynowak** [comment]
@rmja thanks for the thorough report. It looks like the issue might be in OutputFormatter@192. 

```
            var selectedMediaType = context.SelectedContentType;

            // If content type is not set then set it based on supported media types.
            selectedMediaType = selectedMediaType ?? SupportedMediaTypes.FirstOrDefault();

<skipping over a few lines...>

            context.SelectedEncoding = selectedEncoding;

            // Override the content type value even if one already existed.
            selectedMediaType.Charset = selectedEncoding.WebName;
```

`selectedEncoding` might refer to one of the values from `SupportedMediaTypes`. We should be making a copy before mutating it.

**Comment by yishaigalatzer** [comment]
@rmja can you please clarify what your action code looks like?

I assume you are calling return `Json(model)` which is when we might fallback to the default json formatter?

In that case I assume you can just return the model directly (or return `ObjectResult(model)`)

**Comment by rmja** [comment]
@yishaigalatzer correct. I am calling `Json(model)`. I was not aware of `new ObjectResult(model)`. It does not produce the same error.
