### ISSUE TITLE
Refactor anti-forgery code 

### ISSUE THREAD

**Issue by kirthik** [aspnet/Mvc#1856]
Antiforgery code needs to be refactored.As part of this we should use better variable and method names and make it more readable.

**Comment by yishaigalatzer** [comment]
@kirthik we discussed a set of other changes we wanted (which escapes my mind at the moment) please provide more details on the bug, or else its not very actionable.

**Comment by harshgMSFT** [comment]
@stanislavromanov renaming of AntiForgery cookie was always there in options. You could update the cookie name in startup.cs like so 
```c#
   public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.ConfigureMvc(options =>
            {
                options.AntiForgeryOptions.CookieName = "YourCookieName";
            });
        }
```

**Comment by kirthik** [comment]
code checked in - 3c9456e2a33ce0d5a518ebad59b399421b96f87b
