### ISSUE TITLE
Application shutdown unexpectedly without errors.

### ISSUE THREAD

**Issue by Boglen** [aspnet/Mvc#1860]
In my application i'm using dropzone js plugin for file async upload.
View contains this code:

        &lt;form action="~/Storage/UploadFile" method="post" enctype="multipart/form-data" class="dropzone dz-clickable" id="mydropzone"&rt;
            &lt;div class="dz-default dz-message"&rt;
                &lt;span&rt;
                    &lt;span class="text-center"&rt;
                        &lt;span class="font-lg visible-xs-block visible-sm-block visible-lg-block"&rt;
                            &lt;span class="font-lg"&rt;&lt;i class="fa fa-caret-right text-danger"&rt;&lt;/i&rt; Drop here &lt;span class="font-xs"&rt;for upload&lt;/span&rt;&lt;/span&rt;
                            &lt;span&rt;&nbsp;&nbsp;&lt;h4 class="display-inline"&rt; (Click)&lt;/h4&rt;&lt;/span&rt;
                        &lt;/span&rt;
                    &lt;/span&rt;
                &lt;/span&rt;
            &lt;/div&rt;
        &lt;/form&rt;

Controller:

        [HttpPost]
        public IActionResult UploadFile(List<IFormFile> fl)
        {
            var files = Request.Form.Files;

            if (!ModelState.IsValid || files.Count == 0)
            {
                return View();
            }

            foreach (var f in files)
            {
              
                var parsedContentDisposition = ContentDispositionHeaderValue.Parse(f.ContentDisposition);
                var parsedFileName = DecodeFromIso( parsedContentDisposition.FileName.Trim('"') );
                var guid = Guid.NewGuid().ToString();

                var uFile = new FileModel()
                {
                    Identifier = guid,
                    FileName = Path.GetFileNameWithoutExtension(parsedFileName),
                    Extension = Path.GetExtension(parsedFileName),
                    Size = f.Length,
                    DateUploaded = DateTime.Now,
                    ContentType = f.ContentType,
                    isUploaded = true
                };
                uFile.ServerPath = Path.Combine(HostingEnvironment.WebRoot, "Storage", guid);

                _db.Files.Add(uFile);
                _db.SaveChanges();

                f.SaveAs(uFile.ServerPath);
            }
            return View("SuccessUploaded");
        }

After return View, and before i see this view in browser, application is shutdown (IISExpress and KRE).
klr.exe Information: 0 : [ApplicationShutdown]: Requested shutdown.
The program '[1112] klr.exe' has exited with code 0 (0x0).

If i use simple form to upload files, everything is fine.

P.S. (And List<IFormFile> fl parameter have 0 count)

**Comment by davidfowl** [comment]
Looks like it might be a bug with tooling aggressively killing the process on any file change /cc @mayurid @BillHiebert @PradeepKadubandi

**Comment by Boglen** [comment]
It happens after i call IFormFile.SaveAs(string).

I'm try to modify Upload file to use IFormFile.SaveAsAsync
...
'klr.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'tm1msgyg.sbt'. Cannot find or open the PDB file.
'klr.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'xe0fqc5u.fkq'. Cannot find or open the PDB file.
'klr.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'avqdm0ct.eoj'. Cannot find or open the PDB file.
'klr.exe' (CLR v4.0.30319: DefaultDomain): Loaded '51zz0rb0.cfz'. Cannot find or open the PDB file.
'klr.exe' (CLR v4.0.30319: DefaultDomain): Loaded '114dqk4c.dxe'. Cannot find or open the PDB file.
'klr.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'nhamckgr.i5j'. Cannot find or open the PDB file.
'klr.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'jqxeqlhu.x4r'. Cannot find or open the PDB file.
klr.exe Information: 0 : [ApplicationShutdown]: Requesting shutdown.
klr.exe Information: 0 : [ApplicationShutdown]: Requested shutdown.
The program '[16460] klr.exe' has exited with code 0 (0x0).

**Comment by davidfowl** [comment]
That doesn't matter. It looks like an IDE issue.

**Comment by Tragetaschen** [comment]
This is really annoying.

I've got a preprocess compile module that builds a large amount of code and I serialize this code into a *.cs for easier (visual) debugging. This file is in `.gitignore` and in project.json's `exclude`.
The net effekt now is, that I can do exactly one (1) request during debugging before the debugging just stops due to this file changing. Not even the static content files reach the browser.

When I stop writing to that file, debugging again works.

**Comment by Boglen** [comment]
I launch my app without IDE and all work as expected.

**Comment by yishaigalatzer** [comment]
Boglen, so seems there is not much for MVC to do here.

Note that we pushed a change to fix the binding issue you are seeing (assuming you are using the latest nightly build)

Fix issue commit:
https://github.com/aspnet/Mvc/commit/67b078862ee36a846af1b81088e3f2f73f5de3e2

Original commit:
https://github.com/aspnet/Mvc/commit/437eb93bdec0d9238d672711ebd7bd3097b6537d

Please open a separate issue if the binding still doesn't work after getting the latest dev branch.

CC // @ajaybhargavb
