### ISSUE TITLE
TryValidateModel does not validate sub-properties of complex properties on a model

### ISSUE THREAD

**Issue by kirthik** [aspnet/Mvc#1863]
Just to be clear - this scenario did not work on MVC5 and it seems like it was by design based on Brad Wilson's comment in [this blog](http://bradwilson.typepad.com/blog/2010/01/input-validation-vs-model-validation-in-aspnet-mvc.html)
" We also added two new methods to Controller (ValidateModel and TryValidateModel) which run model-level validation, one level deep (i.e., the properties of the model and the model itself, but not any of the sub-properties of complex properties)."

I am just bringing it up to see if sub-properties should be validated in new world.

Here is the scenario - If I have below model
 ```
    public class Product
    {
        public string Name { get; set; }

        [Required]
        public ProductDetails ProductDetails { get; set; }
    }
    public class ProductDetails
    {
        [Required]
        public string Detail1 { get; set; }

        [Required]
        public string Detail2 { get; set; }
    }
```
and I call `TryValidateModel(p)` where 
```
           var p  = new Product
            {
                Name = "MVC",
                 ProductDetails = new ProductDetails
                {
                    Detail1 = "D1"
                }
            }
```
In this case, `ModelState` does not contain a validation error for `Product.ProductDetails.Detail2` (Detail2 has required attribute)
if ProductDetails property is null like below, then validation error is thrown
```
           var p  = new Product
            {
                Name = "MVC"
            }
```

**Comment by yishaigalatzer** [comment]
@GrabYourPitchforks say something if you think we should fix this.

**Comment by oguzhantopcu** [comment]
Why this is closed without any explanation? We need a single method to validate all model with sub-properties.

**Comment by Eilon** [comment]
MVC now deeply validates models when calling `TryUpdateModel`.

This fix was available starting with RC1.

**Comment by neumann1990** [comment]
So TryUpdateModel does deep validation buy TryValidateModel does not? Why don't both do the deep validation, or at least have the option of doing so?

**Comment by DianaKoenraadt** [comment]
I'm thinking that for multi-step forms, the current implementation is good and useful. It seems to be quite common to create one big viewmodel, with nested viewmodels per step. 

    class BigViewModel
    {
        public StepOneModel StepOne { get; set; }
        public StepOneModel StepTwo { get; set; }
    }

    class StepOneViewModel
    {
        [Required]
        public bool Something { get; set; }
    }

What needs to be validated, depends on the step of the form you're at. If the user has not passed step 3 yet, no need to validate the Step3 'sub-property'.

If sub-property validation is added, I would very much be in favor of an optional boolean parameter to enable sub-property validation, with default value false.

**Comment by dougbu** [comment]
@DianaKoenraadt and @neumann1990, a request to change the behaviour of `TryValidateModel()` is separate from this resolved issue. Please open a new issue.

However, please note implementing deep validation in `TryValidateModel()` may frequently be impossible. Model binding gathers a fair amount of information for the validation system.

**Comment by PuttItOut** [comment]
I have a code flow currently that the `TryUpdateModelAsync()` code will not work for and the `TryValidateModel()` does not navigate deeply enough.

The incoming model is based on dynamic types and has been custom formatted in JSON so I have to accept a basic model in the controller, map it to types that have validation attributes, then validate the mapped type. The view is bound to this mapped type so it is only the incoming model that needs massaged and then validated.

```
public ActionResult Save([FromBody] SomeBasicModel model)
{
       //Map
       var domainModel = Map(model);
       //Validate - but this does not fully validate nested collections beyond the first level
       var result = TryUpdateModelAsync(domainModel);
...            
```

Is there any way to validate this "domain model" and get deep validation?

**Comment by dougbu** [comment]
@PuttItOut a request to change the behaviour of `TryValidateModel()` is separate from this resolved issue. Please open a new issue.
