### ISSUE TITLE
Come up with a common way to define directives and merge all existing directives to the new codepath

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#1864]
Specifically Transition @inject parsing code to not trim string output.

Right now our `@inject` parsing code essentially reads to the end of the line and then trims the resulting string content. We should instead do what `@using` does and utilize the `TokenizeBackedParser` methods to parse out our expected inject parameters.

Doing this approach will enable us to correctly throw errors for invalid trailing characters in the `@inject` statement.

**Comment by NTaylorMullen** [comment]
Found out that all existing directives with the exception of `@section` and `@using` perform parsing invalidly for extra/invalid characters, this has been around for ages so the urgency of the issue is definitely less. This will be post-rtm.

/cc @DamianEdwards

**Comment by Eilon** [comment]
@DamianEdwards @NTaylorMullen does it seem worth changing this at this time? I don't recall any customer complaints around this.

**Comment by NTaylorMullen** [comment]
Nah, only time I'd ever think it was worth fixing is if there truly was 0 other items to complete.
