### ISSUE TITLE
MvcSample.Web fails with vague message about determining runtime version.

### ISSUE THREAD

**Issue by MattGal** [aspnet/Mvc#1869]
I wanted to play with the MVC samples, so I cloned the repository and started up the main sample project (MvcSample.Web).  From being familiar with KVM and how to inspect the project system, I though I could figure out how to work around this quickly, but thus far I have tried specifying several different installed KREs and still haven't gotten the message to go away.

Instead of running or getting a useful error message I get:

[InvalidOperationException: Couldn't determine an appropriate version of runtime to run. See http://go.microsoft.com/fwlink/?LinkId=517742 for more information.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +506

[HttpException (0x80004005): Couldn't determine an appropriate version of runtime to run. See http://go.microsoft.com/fwlink/?LinkId=517742 for more information.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9931632
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +191

... it would be good if this FWLink went somewhere other than the Asp.net site, or if searching for this error string on the site yielded results.  From trolling through the repo, I don't see a readme guiding the user out of this issue as well.

**Comment by mbeckenbach** [comment]
I'm having the same issue after updating to VS CTP5. 
I also did a kvm upgrade to 1.0.0-beta3-10921.

File->New Project->Launch

Same for Empty project and starter template. 

I have a existing project using  the 1.0.0-rc1-10870 CLR.
Now i can't even build this one as i get a bunch of errors in startup.cs. I get the same errors as when doing file->new project with the starter web.


Show Details	Severity	Code	Description	Project	File	Line
	Error	CS0246	The type or namespace name 'IHostingEnvironment' could not be found (are you missing a using directive or an assembly reference?)	test.ASP.NET 5.0	Startup.cs	21
	Error	CS0246	The type or namespace name 'IConfiguration' could not be found (are you missing a using directive or an assembly reference?)	test.ASP.NET 5.0	Startup.cs	29
	Error	CS0246	The type or namespace name 'IServiceCollection' could not be found (are you missing a using directive or an assembly reference?)	test.ASP.NET 5.0	Startup.cs	32
	Error	CS0012	The type 'IServiceCollection' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Framework.DependencyInjection.IServiceCollection, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.	test.ASP.NET 5.0	Startup.cs	35
	Error	CS0246	The type or namespace name 'IHostingEnvironment' could not be found (are you missing a using directive or an assembly reference?)	test.ASP.NET 5.0	Startup.cs	44
	Error	CS0246	The type or namespace name 'ILoggerFactory' could not be found (are you missing a using directive or an assembly reference?)	test.ASP.NET 5.0	Startup.cs	44
	Error	CS0012	The type 'ILoggerFactory' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Framework.Logging.ILoggerFactory, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.	test.ASP.NET 5.0	Startup.cs	48

**Comment by yishaigalatzer** [comment]
Lets please separate the issues. @MattGal providing better error messages for startup scenarios doesn't really belong in the MVC repo. Please open an issue on Home or Kruntime.

@mbeckenbach I think you have an incompatible KVM since the VS project templates point to Beta2. Feel free to go on Jabbr or SO for such support questions, this just doesn't seem like an actual bug we need to fix.
