### ISSUE TITLE
Add a property to the CacheTagHelper that allows users to declaratively specify expiration triggers

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1873]
https://github.com/aspnet/Mvc/issues/1867 allows users to specify expiration triggers programatically using `EntryLinkHelpers.ContentLink`. However this code is a bit obtuse and we can make the experience slightly better for scenarios where users can provide an expiration trigger up front.

``` HTML
<cache expiration-trigger="() => CreateTrigger()">
Random child content
</cache>
```

``` C#
public class CacheTagHelper
{
   public Func<IExpirationTrigger> ExpirationTrigger { get; set; }
}
```

We need to determine what the name of property is and what it's signature looks like.

**Comment by pranavkm** [comment]
cc @DamianEdwards \ @yishaigalatzer. I'll set up a design PR for this for next week.

**Comment by Eilon** [comment]
Closing because we are not planning to implement this.
