### ISSUE TITLE
@inject directive loses coloring and allows invalid C# characters in editor.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#1875]
The partial parsing logic for the `@inject` directive results in loss of coloring and unnecessary errors when adding bad C# characters to the end of the directive.

**Reproduction loss of coloring:**  
1. Type `@inject System.String str`
2. Do not hit any extra keys, do nothing.  

**Result:** System.String unhighlights, everything goes black.
**Expected Result:** Coloring persists.

**Reproduction bad C# characters:**   
1. Type `@inject System.String str;`
2. Do not hit any extra keys, do nothing.  

**Result:** Tons of errors
**Expected Result:** No errors

**Comment by yishaigalatzer** [comment]
@DamianEdwards we took a second look, and it seems that other than `@using` no other directive really allows for a trailing `;`

So I'm suggesting we deal with this post RTM, it's nice cleanup, but not something we ever supported. The issue with a lot of errors is an actual Roslyn bug that will get cleaned up at some point.

**Comment by NTaylorMullen** [comment]
@yishaigalatzer moved this one too: https://github.com/aspnet/Mvc/issues/1864

**Comment by Eilon** [comment]
@NTaylorMullen @rynowak does Razevolution fix this?

**Comment by NTaylorMullen** [comment]
@Eilon yes. Adding the extensible directives layer will ensure that all code mappings work as expected.

**Comment by Eilon** [comment]
Awesome. Do we need this issue? Or is this already tracked by something else?

**Comment by rynowak** [comment]
I don't think this issue will track anything especially valuable. We'll basically need to test+verify everything in this area. (yes, I am alive)
