### ISSUE TITLE
Centralized attribute routes

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#1877]
Some users have asked about still maintaining all the routes in a centralized location for a webapi style project.

We explicitly decided not to support conventional routing in this scenario, but with the ApplicationModel its relatively straightforward to write some extension method on top of routes that will allow making an attribute route apply to a controller or an action.

_This is just a strawman suggestion, it needs to be cleaned up_

For the simple case

``` C#
    routes.AddGet("Receipts/{id}", => ReceiptsController.GetReceipt);
```

Or for the fancier user

``` C#
    routes.AddRoute("Receipts/{Id}", => ReceiptsController);
    routes.AddGet("", => ReceiptsController.GetReceipt);
    routes.AddDelete("", => ReceiptsController.DeleteReceipt);

    routes.Add("Patch", "", => ReceiptsController.FixReceipt); // custom Http constraint
```

These will in turn create application models. Since the application models live off the MvcOptions we can change the signature of UseMvc to expose an `IMvcRouteBuilder` instead of `IRouteBuilder` that will provide the access to options. This will not be a breaking change if `IMvcRouteBuilder` implements `IRouteBuilder`. Alternatively we can make this API live off the `MvcOptions`

``` C#
    services.ConfigureOptions<MvcOptions>( options =>
    {
        options.AddRoute ...
    }
```

The downside is that it is not as intuitive.

CC / @rynowak @loudej @davidfowl

**Comment by atrauzzi** [comment]
Would love to see this make it in and be nicely documented!

**Comment by colemickens** [comment]
@filipw has a solution for this. He has a Web API 2 compatible version here: https://github.com/filipw/Strathweb.TypedRouting and blogged about a version for ASP.NET5/MVC6: http://www.strathweb.com/2015/03/strongly-typed-routing-asp-net-mvc-6-iapplicationmodelconvention/

I'm currently using it successfully.

**Comment by yishaigalatzer** [comment]
https://github.com/yishaigalatzer/ResourceController is a simple alrernative

**Comment by ivaylokenov** [comment]
I have built a package, which allows typed route registraion based on the code in the above article. Available here:
https://github.com/ivaylokenov/AspNet.Mvc.TypedRouting

**Comment by khalidabuhakmeh** [comment]
I am one of the maintainers of [Restful Routing]() and love the idea of centralized routes. This is how central registration works via the idea of `resources`.

```csharp
public override void Map(Mapper map)
	{
		map.Root<HomeController>(x => x.Show());
		map.Resource<SessionsController>();
		map.Resources<BlogsController>(blogs =>
		{
			blogs.As("weblogs");
			blogs.Only("index", "show");
			blogs.Collection(x => {
				x.Get("latest");
				x.Post("someaction");
			);
			blogs.Member(x => x.Put("move"));

			blogs.Resources<PostsController>(posts =>
			{
				posts.Except("create", "update", "destroy");
				posts.Resources<CommentsController>(c => c.Except("destroy"));
			});
		});
	}
```

I am hoping to port this routing strategy to asp.net 5 once the routing stabilizes and I get a better understanding of the changes. 

I have found this approach to be much faster when building applications and reduces the discussion around how many actions each controller should have and what functionality should be where. Granted it is opinionated, but [Restful Routing](https://github.com/stevehodgkiss/restful-routing) has ways to break from opinion when it makes sense.

**Comment by jon49** [comment]
Another alternative, if you support Swagger docs:

https://github.com/sergey-tihon/SwaggerProvider

**Comment by bjorn-ali-goransson** [comment]
Nancy style, right?

**Comment by khalidabuhakmeh** [comment]
I have ported the major parts of Restful Routing to ASP.NET Core for anyone interested. It is also available on Nuget. http://www.khalidabuhakmeh.com/initial-port-of-restful-routing-to-asp-net-core

**Comment by rynowak** [comment]
@khalidabuhakmeh - have you tried building this with the application model? This is how we imagined systems like this being built for routing - and this is how attribute routing works in MVC internally.

Sample of something trivial, but you could easily port the same builder API to application model.
https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.CustomRoutingConvention/NameSpaceRoutingConvention.cs

**Comment by khalidabuhakmeh** [comment]
@rynowak The `ApplicationModel` works great, but it doesn't expressly indicate the relationship between controllers. 

Restful Routing takes the nested configuration and maps those relationships and builds out the urls/routes accordingly. I'm not sure it would work, but I may be missing what you are trying to convey. Please let me know if I did.

Also, Restful Routing is on GitHub and I am looking for help :)

**Comment by rynowak** [comment]
@khalidabuhakmeh can you give me an example? Can you link your restful routing repo? maybe it would be good to take the discussion there

**Comment by Eilon** [comment]
No plans to build this into MVC, but using Application Model and conventions it should be possible for others to build this type of feature in a 3rd party library.
