### ISSUE TITLE
Provide predictable ordering of validation summary messages and `@Html.Display()` / `@Html.Editor()` properties

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1888]
to ensure a predictable order using MVC once #964 is fixed, users must annotate all model properties with `[Display(Order=x)]`.  this may be too high a bar but unfortunately `type.GetRuntimeProperties()` and related Reflection methods do not guarantee a predictable or even a stable ordering.

recent decision was to split this issue from #964 and to determine what guarantees exist for the `type.GetRuntimeProperties()` return value.  then, if no guarantees exist (as [MSDN](https://msdn.microsoft.com/en-us/library/kyaxdd3x.aspx) implies), ask for one or add something (perhaps not based on `PropertyName`) to MVC.

__details and history__
see also the StackOverflow [discussion](http://stackoverflow.com/questions/5473455/c-sharp-get-fieldinfos-propertyinfos-in-the-original-order/5473526#5473526) of Reflection ordering as well as the linked [MSDN documentation](https://msdn.microsoft.com/en-us/library/kyaxdd3x.aspx).

in #964:
> MVC 5.2 does not provide a predictable property order when displaying / editing a complex object or filling in the `@Html.ValidationSummary()`. We could do a bit better here and sort by `Order` then by `PropertyName`.

in PR #1866:
> I'm not sure I quite follow the reasoning for adding ordering by Name, is it the same behavior as MVC5? Can you illustrate the benefit?

--
> we had an offline discussion (sorry, not sure who all was there) where we agreed to make the property order predictable. today, it's possible for the HTML `Html.DisplayFor(...)` (for example) generates to change between CLR or Roslyn builds. with this fix in place, the UI will remain consistent no matter how the runtime and compiler choose to order properties.
> MVC 5 does not provide such a predictable property order. the offline discussion basically supported my comment in #964:
>> We could do a bit better here and sort by `Order` then by `PropertyName`.

**Comment by yishaigalatzer** [comment]
Please work with the Roslyn and CLR folks to verify if:

1. Is the order consistent if you use the same compiler and same code.
2. Is the order the definition order if you have a simple POCO.
3. Can the order change at runtime

**Comment by dougbu** [comment]
Too big a surprise for those used to `@Html.DisplayFor()` and so on spitting out fields in the order they placed properties in the original class.
