### ISSUE TITLE
Fix docs for URL helper to indicate what actually IsLocal means

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#1889]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/IUrlHelper.cs#L36-L39

We should indicate that IsLocal means within the App.

Also change `true` and `false` to the right XML linking format `<see`

**Comment by ianhong** [comment]
70efc5ae0a94323fbbd9623f5842f9ae1bb530f4
