### ISSUE TITLE
Add System.Assembly and delegate classes to default ValidationExcludeFilters in MvcSetup

### ISSUE THREAD

**Issue by ashmind** [aspnet/Mvc#1898]
I don't have a proper test at the moment, but it seems that if the body model contains a delegate in WebApi2, the traversal goes into the `MethodInfo` and then to `RuntimeAssembly` and so on. It all ends up valid, but makes the validation and so the request extremely slow.

I'll see if I can make a proper test etc for newer WebApi.

**Comment by yishaigalatzer** [comment]
Why would you have a delegate in your model? or an Assembly? Should this really belong on a DTO?

Fortunately with MVC 6 you can add anything you want us to skip, we don't plan to add additional types that are not commonly used, because that list is pretty much infinite. You have now the capability to add whatever you chose to exclude.

**Comment by ashmind** [comment]
@yishaigalatzer
> Why would you have a delegate in your model?
My model is the following:
```csharp
public class Patch<T> {
    public IDictionary<string, PatchValue<T>> Values { get; private set; }
}

public class PatchValue<T> {
        ...        
        public object Value { get; private set; }
        public Action<T> Apply { get; private set; } // this captures JSON.NET attempt to set corresponding property on TTarget
}
```

Since I plan to release it (and related Json contract resolver) as a NuGet package at some point, this might cause a problem for people unless I don't resolve it somehow.

> Fortunately with MVC 6 you can add anything you want us to skip, we don't plan to add additional types that are not commonly used, because that list is pretty much infinite.

Yes, but the delegate is common type, and the current logic causes immense slowdown instead of outright failure. Developers might miss that slowdown when developing. I think it is important to avoid those scenarios.

You did add `Type`, why not other reflection types including `Assembly`?

**Comment by yishaigalatzer** [comment]
couple of comments: you can have a registration code for your package that adds them to options.

We are planning to add patch support before rtm-ing

-----Original Message-----

**Comment by ashmind** [comment]
> Also note that we are planning to add patch support before rtm-ing, so if you are interested in that kind of support you might want to participate in that feature design when we get closer so it actually happens in the framework.

That sounds interesting, where can I participate?

> though we might want to have proper `[ValidateNever]` attribute

That sounds great. One other thing that might be worth considering is a configurable limit on validation time or count of objects visited, so if something weird happens developers might get an error instead of a random slowdown.

**Comment by yishaigalatzer** [comment]
> One other thing that might be worth considering is a configurable limit on validation time or count of objects visited, so if something weird happens developers might get an error instead of a random slowdown.

We added a limitation on number of errors produced in 

> That sounds interesting, where can I participate?
Start by commenting and suggesting designs as well as following #650
