### ISSUE TITLE
build issues - Predefined type 'System.Object'

### ISSUE THREAD

**Issue by unaizorrilla** [aspnet/Mvc#1904]
With last vs 2015 build 14.0.225.12.0 DP and a new MVC project clone, the build throw errors like

Show Details	Severity	Code	Description	Project	File	Line
	Error	CS0518	Predefined type 'System.Object' is not defined or imported	Microsoft.AspNet.Mvc.Core.ASP.NET 5.0	StringCollectionTextWriter.cs	86

Any idea?

**Comment by yishaigalatzer** [comment]
If you are using the dev branch, you need to be updated with the latest KVM etc. (Note that in the last couple of days we have been renaming folders and commands, and I would suggest to wait a couple of days until the dust settles on that before going back to working on the dev branch.

In any case this is not an MVC issue, if you want further support working on the dev branch which is the current edge of development, best place is to go in to https://jabbr.net/#/rooms/AspNetvNext
