### ISSUE TITLE
Intellisense doesn't find the package

### ISSUE THREAD

**Issue by Samvrie** [aspnet/Mvc#1905]
Hi, 

I've just made a Fresh Install of Windows 10 9926 and Visual Studio 2015 CTP 5.
I tried a new ASP 5 Application at the beginning everything is working fine, but when I closed VS then Intellisence doesn't find my package anymore when I'm coding, what is weird is that my application is still compiling and I can launch it.
I didn't do anything with KVM so i'm still using the `1.0.0-beta2 CLR x86`.
And the MVC package i was using his `Microsoft.AspNet.Mvc": "6.0.0-*`.

I've seen the same thing on the [Testing repo issue 65](https://github.com/aspnet/Testing/issues/65)

I'm not sure if it's the right place to post this issue, I will move it if necessary.
If you have any idea on how to fix it.

**Comment by yishaigalatzer** [comment]
When you are testing the beta build you should not use MVC with `-*` use specifically "Microsoft.AspNet.Mvc": "6.0.0-beta2"`

**Comment by yishaigalatzer** [comment]
The right place for these reports in connect, this is not an MVC issue for sure. @mayurid do you have more info on this?

**Comment by Samvrie** [comment]
I got it working again with unloading and loading the project and changing to beta2.
It seems that I've the problem with the package xunit.runner.aspnet so I will move to the appropriate Repo ;)
Thanks for the help!

**Comment by yishaigalatzer** [comment]
You welcome
