### ISSUE TITLE
Review use of Order

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#1910]
Generated through discussion:

We should review the the use of `Order` properties where they appear in the framework for consistency. 

Examples:
- Attribute Routing
- Nested Providers
  - Action Descriptor Provider
  - API Description Provider
  - Action Invoker Provider
  - Filter Provider
  - Action Constraint Provider
- Filters
- Options
- Action Constraints

**Comment by yishaigalatzer** [comment]
Please provide more details here. Not sure this is actionable.

**Comment by rynowak** [comment]
The suggested task here is to review our uses of `Order` when it's used as a property and make sure they all have *consistent definitions* and *accurate and complete docs*.

Ex: Does a route with higher order run first or last?

**Comment by rynowak** [comment]
Did a review of all of the items here, and all of them are consistent. 

All of our `Order` properties mean "lower number goes first". 90% of the time there's a use of `.OrderBy(_ => _.Order)` in the code.

The remaining work here is to add documentation.

**Comment by rynowak** [comment]
2b4702728d48ee6c34727afa09255c0e7c17b6f9
