### ISSUE TITLE
FromHeader should auto translate properties to kebab casing

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#1930]
Consider the following code

```C#
[FromHeader]
public string UserAgent { get; set; }
```

We should probably generate the lookup to following header `user-agent`.

Similarly `XHttpMethodOverride` should translate to `x-http-method-override`.

**Comment by yishaigalatzer** [comment]
CC // @lodejard @Eilon

**Comment by Eilon** [comment]
How would you know what to translate? There's no transformation that can reliably do this. We could consider doing underscore to hyphen translation, as we do for HTML attributes.

**Comment by yishaigalatzer** [comment]
This would follow the casing, just like we do in tag helpers

-----Original Message-----

**Comment by Eilon** [comment]
The transformation in tag helpers doesn't generally work with HTTP header names. It's also a very different scenario: in tag helpers it's transforming one set of arbitrary strings to another; in this case it's attempting to do a specific transformation.

A great example of why this won't work here is this: would the logic translate a property named `ETag` to `E-Tag`? In fact it should leave `ETag` alone. How would you describe the `X-HTTP-Method-Override` header as a C# identifier?

There are no rules for translating a property name to an HTTP header name with hyphenation, so I urge us not to try. However, converting underscores to hyphens is fairly predictable. An alternative that in my mind is almost as good is to just have a built-in dictionary of all the well-known HTTP header transformation and just use that. If it's not well-known, just leave it alone.

**Comment by yishaigalatzer** [comment]
It's actually pretty straight forward for any one of the samples. If you just follow Pascal casing, but I like the idea of the well know header names (case insensitive translation).

Without it you end up with pretty ugly and none standard looking property names.

Specifically to the samples above:
X-HTTP-Method-Override - XHttpMethodOverride
Etag

The rule is quite simple and easy to understand, however I do have one concern with the fact that the translation is not as clear as it is in tag helpers. In tag helpers you get intellisense for generated html attributes. In html helpers you can see the generated html. Here you are left guessing when it doesn't work like you expected. So perhaps underscore conversion is the way to go.

Will retriage next week.


-----Original Message-----

**Comment by Eilon** [comment]
I believe in those examples the requirement is that developers follow arbitrary rules with uncommon casing to get the desired effect. The property names really should be `ETag` and XHTTPMethodOverride` because those are closest to the HTTP header names, for better or for worse. Add to that any custom headers that of course have no rules whatsoever, and it gets far more confusing. It's not .NET Framework Design Guidelines casing, but that's irrelevant here.

**Comment by rynowak** [comment]
We had also discussed allowing you to plug in our strongly-typed header classes with `[FromHeader]`. That might allow you to express which header you want to bind without having to copy-paste string like `[FromHeader(Name = "ETag")]` - which I think is the intent of this suggestion.

**Comment by yishaigalatzer** [comment]
@harshgMSFT - Please don't get started on this. And I have a related question: What does `[FromHeader]` with no `Name` specified means? Should we just move it to a constructor because it is currently required?

**Comment by harshgMSFT** [comment]
FromHeader with no name means it will use the property or the parameter name for model binding. It should not be in the constructor as it is not required.
