### ISSUE TITLE
Web API 401 should not redirect to login page

### ISSUE THREAD

**Issue by sandorfr** [aspnet/Mvc#1933]
When using WebAPI in an MVC site with Identity enabled and an Api action returns a 401, it redirects automatically to the login page (302 then 200). The issue was already present (http://stackoverflow.com/questions/20149750/unauthorised-webapi-call-returning-login-page-rather-than-401) but there was a fix which does not seem to apply to MVC6.

I think this default behavior for webAPI is a design flaw. Correct me if I'm wrong but I don't really see in which case this default redirect for apis is appropriate.

**Comment by yishaigalatzer** [comment]
@HaoK I believe this is tracked in your redo of `AuthorizationFilterAttribute` but I couldn't find the specific bug/design tracking this.

**Comment by HaoK** [comment]
You can probably just use this bug to track all 401/403 issues for now https://github.com/aspnet/Security/issues/134

**Comment by yishaigalatzer** [comment]
Should we close this one as well https://github.com/aspnet/Mvc/issues/634?
