### ISSUE TITLE
Make MusicStore more unit-testable and add unit tests accordingly 

### ISSUE THREAD

**Issue by ianhong** [aspnet/Mvc#1935]
This is part of #1870

This includes:
3.	Make  MusicStore more unit-testable
  a.	MusicStore controllers’ constructors need to be the default constructor
  b.	Use property injection for UserManager and SignInManager 
  c.	Action method should take CancellationToken
4.	Add unit tests to MusicStore repo

**Comment by ianhong** [comment]
1b502cbee7b86709a0b9a0afd4de4f3c97db52ae

**Comment by danroth27** [comment]
Closing - we've done everything here we wanted to do.
