### ISSUE TITLE
Add DefaultBodyModelValidator unit test for case where same object is encountered in multiple paths.

### ISSUE THREAD

**Issue by sornaks** [aspnet/Mvc#1938]
```c#
// Pop the object so that it can be validated again in a different path
validationContext.Visited.Remove(metadata.Model);
```
Test needs to be added for the above code path in `ValidateNonVisitedNodeAndChildren` in `DefaultBodyModelValidator`.

**Comment by Eilon** [comment]
@harshgMSFT can you verify if we already have a test for this?

**Comment by rynowak** [comment]
I'm not @harshgMSFT - but he did add a testcase for this.
