### ISSUE TITLE
Support Func<Stream> for both StreamOutputFormatter and FileStreamResult

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#1955]
The purpose of this is to delay the stream creation to the action result execution time.

This allows
1. Doing the work only when we know we absolutely have to do it. e.g. the result can be replaced by a filter.
2. Easier dealing with disposal, without this the user is ultimately responsible to dispose the stream if something failed along the way before the action result was executed (and if we don't make setting the stream a registration step for disposal).

``` C#
[MyFilter]
public Stream GetStream()
{
   var stream = new MemoryStream();
   // do more
   return stream;
}
```

Today the user has to write something explicit to be sure disposal happens, perhaps this:

``` C#
// alt1
[MyFilter]
public Stream GetStream()
{
   var stream = new MemoryStream();

   try
   {
      // do more
   }
   catch
   {
      stream.Dispose();
      throw;
   }

   return stream;
}

// alt2
[MyFilter]
public Stream GetStream2()
{
   var stream = new MemoryStream();   
   RegisterForDisposal(stream); // this doesn't exist yet in the framework.

   // do more

   return stream;
}
```

With this suggestion the formatter will just look like:

``` C#
WriteAsync(Func<Stream> func)
{
   using(var stream = func())
   {      
       // validity check

      await stream.CopyToAsync(Response.Body);
   }
}
```

**Comment by Eilon** [comment]
Closing because we have no plans to support this.
