### ISSUE TITLE
Intermittent timeouts in FlushAsync functional tests time

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1958]
Needs some investigation to figure out if something's amiss

**Comment by pranavkm** [comment]
Are folks still seeing this? I haven't see the tests timeout locally or on the CI.

**Comment by rynowak** [comment]
I haven't seen this in a long long time. IMO we'd need a repro or a dump to really investigate this.

**Comment by Eilon** [comment]
Closing this because apparently no one has seen it. If we see it again we can log a new bug.
