### ISSUE TITLE
Razor CompilationFailedExceptions contain design-time-missing content and incorrect line/column information

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#1968]
For instance:  I have an exception that fails with:
Additional information: C:\GIT\DataPoint\Source\DataPoint.Web\shell\default\_shelllayout.cshtml(28,36): error CS0115: 'ASPV__shell_default__shelllayout_cshtml.ExecuteAsync()': no suitable method found to override
... but opening that file up with a text editor, I see that line # 28 looks like: 

            </div>

... and furthermore, I don't have any calls to ExecuteAsync()  in the markup.  There are assorted calls to RenderSectionAsync that this is probably related to, but the end user shouldn't have to guess about this.  

** Update:
- I noted that the markup causing the issue is contained in CompiledContent property of the exception.  The exception text still directs me to the original, not compiled file, but at least the needed data is already there.

From @mattgal

**Comment by yishaigalatzer** [comment]
@pranavkm please comment

**Comment by yishaigalatzer** [comment]
We need mostly a doc that shows what a minimal base type should look like. @danroth27

Need to make it show up in helios/and diagnostics middleware

**Comment by pranavkm** [comment]
This should get addressed as part of https://github.com/aspnet/Mvc/issues/2321
