### ISSUE TITLE
Model validation does not happen for value types decorated with Required annotation

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#1971]
Please take a look at issue #468 for detailed information.

```c#
public class Person
{
	[Required]
	public int Id { get; set; }

	[Required]
	public string Name { get; set; }
}
```

![image](https://cloud.githubusercontent.com/assets/6559784/6077406/6192b376-ada3-11e4-9c4a-67ec45a05328.png)

**Comment by Bartmax** [comment]
Oh this is music to my ears! I wanted this to be resolve for a few years now. I'm happy that 6.0 will solve this. Still I see a little problem on fixing this. All versions of MVC behave like this, and I'm pretty sure most of us are already used to this. What about backcompatibility, how is going to be handled ? I don't think it could have a great impact but I can think of some scenarios. Using it 'wrong' and having `[Required]` on value types; using entities on your views so [Required] is used for EF and now this will propagated. Not sure if anything else. I guess MVC5 or less will not be affected with this fix.

**Comment by kichalla** [comment]
Commits:
c276ddaa39735a8826b1da27b84dd793865a65e4 
f737083c946137dd9a411759c3ca83856a0083a2
