### ISSUE TITLE
Route parameters with indexes in a collection do not work.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#1981]
a route template like 
Company/[action]/{company.Employees[0].TaxId} throws 
Error: While processing template 'Company/[action]/{company.Employees[0].TaxId}', a replacement value for the token '0' could not be found. Available tokens: 'action, controller'.

The problem is that we are not able to parse the route template. 

This bug is to track whether we want to support such a scenario.

what would be more interesting is to support something like 
 [Route("Company/[action]/{id}/{customPrefix.Employees[{id}].TaxId}")]

Details:
Lets say  our controller is something like 
``` c#
 [Route("Company/[action]/{customPrefix.Employees[0].TaxId}")]
    public class CompanyController : Controller
    {
        public Company CreateCompany(Company company)
        {
            return company;
        }
    }
```
where the models are as follows: 
```c#

    public class Company
    {
      public IList<Employee> Employees { get; set; }
    }

    public class Employee : Person
    {
      .....
        [FromRoute(Name = "EmployeeTaxId")]
        public int TaxId { get; set; }

    }
```
we get an invalid operation exception like so:
Error: While processing template 'Company/[action]/{company.Employees[0].TaxId}', a replacement value for the token '0' could not be found. Available tokens: 'action, controller'.

.

**Comment by Eilon** [comment]
The purpose of routing is to extract basic information from a URL. This seems waaay outside the scope of routing, no? This scenario is more about *model binding*, which can certainly feed off of information gleaned from routing.

**Comment by harshgMSFT** [comment]
Sure, the consumer in this case is model binding and there is nothing preventing model binding from consuming if a value provider ( in this case the route value provider) would give a value for ```Company/[action]/{company.Employees[0].TaxId}```. The reason for this bug is today routing layer throws for such a key. We would have to decide if we want to allow such scenarios or explicitly block it ( even then I would say doing it at routing layer does not make much sense).

**Comment by rynowak** [comment]
This seems like a tricky situation. If only there were some way to **ESCAPE** this peril. https://github.com/aspnet/Mvc/blob/af9e9f9113fb88d443c69925d5d77d7b3e450281/src/Microsoft.AspNet.Mvc.Core/ApplicationModels/AttributeRouteModel.cs#L229

If @Eilon were paying attention when we did this feature he might have insisted on adding escaping despite my objections :laughing: https://github.com/aspnet/Mvc/pull/823#discussion_r15145006

**Comment by rynowak** [comment]
I'd agree also with what @Eilon is saying now. This seems like a complicated way to express something simple. If you want to read a collection of values, routing is not a simple way to do that.

Rather than trying to adapt routing to your DTO, adapt your DTO to routing. view-models for request data after-all aren't about  code reuse.

**Comment by yishaigalatzer** [comment]
You can use `[[` to escape the value.

That should be enough.
