### ISSUE TITLE
Cannot easily use IHtmlHelper<T> in a tag helper

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#1986]
In a tag helper, I want to call the `IHtmlHelper<T>.EditorFor` extension method. The main reason is that I get the EditorTemplates infrastructure to work with. My problem is that there isn't a `ViewContext` available where the `.ViewData` matches the T of the `IHtmlHelper<T>` (only in the special case). When `[Activate]`ing the helper the [`Conextualize` call](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/DefaultTagHelperActivator.cs#L59) throws due to a type mismatch.

Right now, I expect a `ViewDataDictionary<T>` and then create a new `ViewContext` and `HtmlHelper<T>` and call Contextualize manually, but that requires more dependencies like `IModelMedatadaProvider` and `IHtmlGenerator`. Newing this up manually also makes unit testing harder than necessary.

Did I miss something? Is there an easier way?

**Comment by dougbu** [comment]
recommend using `HtmlHelper.Editor()` instead e.g. pass a `ModelExpression` instance's `Name` to that method.  or just call `EditorFor()` from a view directly.

**Comment by yishaigalatzer** [comment]
@Tragetaschen can you share a more exact code sample?

CC @DamianEdwards

**Comment by Tragetaschen** [comment]
Sure. Currently I'm doing something like that:
```
var editorContext = new ViewContext(viewContext, viewContext.View, settingViewDataDictionary, viewContext.Writer);
var htmlHelper = new HtmlHelper<ISetting>(htmlGenerator, viewEngine, metadataProvider);
htmlHelper.Contextualize(editorContext);

var setting = Settings.Single(x => x.Name == Name);
htmlHelper.ViewData.Model = setting;

var label = htmlHelper.LabelFor(x => x.Value, Name).ToString();
var input = htmlHelper.EditorFor(x => x.Value, Name).ToString();

label = label.Replace("for=\"Value", $"for=\"{setting.Name}");
input = input.Replace("id=\"Value", $"id=\"{setting.Name}");
input = input.Replace("name=\"Value", $"name=\"{setting.Name}");
```
I have my basic setting objects—basically a name, a value and most importantly infrastructure to apply them at the right place. I create Label and Editor for those settings, which results in `id="Value"` etc. attributes that I replace by the setting's name. These tags are then rendered through a "Setting.cshtml" template. In a View, I just enter `<setting name="Foo"></setting>` and get the correct input element for each setting.

The main advantage here is that a Designer can choose to provide
- An EditorTemplate for the setting's data type like `Int32.cshtml`
- An EditorTemplate for the setting's name like `Foo.cshtml`

and these templates themselves can recurse further using the existing infrastructure.

The original View containing the `<setting/>` is not model-typed `ISetting` and that's why creating the `HtmlHelper<ISetting>` in DI fails.

**Comment by yishaigalatzer** [comment]
Activate != DI

Since there is a single viewcontext it will be the view context of the page. You will need something like a TagHelper<TModel> to understand the type change in the activator.

a few alternatives for now:
Did you consider redirecting through a partial or view component?
You can build a factory for this scenario and di it in to make it more testable.
Make your own base class?

Moving forward we are going to think and see if we can/should improve this scenario.

**Comment by Tragetaschen** [comment]
One of these days I'll wrap my head around the (likely important) difference between activation and dependency injection.

Nontheless: I'm now using a trampoline partial view that is typed and contains the EditorFor code. Now I only have to use the activated ViewDataDictionary<T>.

Thanks!

**Comment by yishaigalatzer** [comment]
Di is when the di container can directly provide the instance.

Activator is a specific class activating some of the mvc components such as controller, view, view component and taghelpers. Each one of these has his own activator.

The activator can do more than what the container for example provide a viewdatadictionary which is an object that flows from the current context of the view but not come from di. Similarly contextualizing the html helper is an activation type activity.

See for example the code for the controller factory here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/DefaultControllerFactory.cs

**Comment by Tragetaschen** [comment]
And now I have discovered `IHmtlHelper.PartialAsync(string, object)` and my `TagHelper` basically lost all its code.

I don't expect this to be a valuable feature anymore.
