### ISSUE TITLE
Prototype one integration test combining JavaScript and generated HTML

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1993]
scenario: extend one of the `<script/>` tag helper functional tests.

testing components:
- use the infrastructure chosen in #1897
- pick whatever [Karma](http://karma-runner.github.io/0.12/index.html) reporter is built-in or looks like it'll play nice in .\build.cmd / .\build.sh
- use [Jasmine](http://jasmine.github.io/) assertions unless that causes problems for our scenarios

**Comment by dougbu** [comment]
moving to RTM milestone per offline discussions.

**Comment by dougbu** [comment]
side note: chosen design is well-suited for JavaScript unit tests but inappropriate for MVC functional tests.  for the functional tests, should instead use [Selenium](http://docs.seleniumhq.org/) and drive the tests from xUnit.  (could drive tests using JavaScript but the result would have analogous components and no major upsides.)

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
