### ISSUE TITLE
Add `ModelStateDictionary` methods to clear or set contained values

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#1998]
- related to scenarios described in #1231 and #1517

- provide new `ModelStateDictionary.ClearValues()` method which removes all values but leaves all errors (and exceptions) alone
 - might require a new `ModelState` property indicating it has no real value or a small change where we read from the dictionary
- provide new `ModelStateDictionary.SetValue<TModel, TValue>([NotNull] Expression<Func<TModel, TValue>> expression, TValue value)` and `ModelStateDictionary.SetValue([NotNull] string expression, object value)` methods
 - methods should create a `ModelState` entry if none exists and overwrite existing entry (leaving any errors or exceptions alone) if any
 - note action author must provide `TModel` explicitly when using first overload e.g. `ModelState.SetValue<Customer>(m => m.Name, "banana")` or `ModelState.SetValue((Customer m) => m.Name, "banana")`
 - in addition action author should update the model passed to the view.  otherwise display helpers or direct use of `@Model.Property` could show something different than `value` passed to these new methods.  (if this turns out to be too confusing, could instead let authors write e.g. `ModelState.ClearValue<Customer>(m => m.Name)` or recommend `ModelState.SetValue<Customer>(m => m.Name, customer.Name)`.)

**Comment by yishaigalatzer** [comment]
Why is this not the fix for #1517 ?

**Comment by dougbu** [comment]
decision after our design discussion was to log new issues (now this one and #1998) and to close #1231 and #1517 as duplicates.  I wanted to talk to you before closing those issues...
