### ISSUE TITLE
Add WebUtilities.Encoders to MvcServices

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#2011]
Add the following to `MvcServices` as singletons:
- `Microsoft.AspNet.WebUtilities.Encoders.IHtmlEncoder`
- `Microsoft.AspNet.WebUtilities.Encoders.IUrlEncoder`
- `Microsoft.AspNet.WebUtilities.Encoders.IJavaScriptStringEncoder`

**Comment by danroth27** [comment]
Tracking this as part of #2015.
