### ISSUE TITLE
Prefer the new encoders over the old WebUtility APIs

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/Mvc#2012]
There are still some call sites in the MVC code base that invoke WebUtility.HtmlEncode.  These call sites should instead use IHtmlEncoder.HtmlEncoder.

**Comment by yishaigalatzer** [comment]
also - Once WebUtility.JavaScriptStringEncode is added by aspnet/HttpAbstractions#72 we should remove our temporary version at src/Microsoft.AspNet.Mvc.TagHelpers/JavaScriptUtility.cs

**Comment by yishaigalatzer** [comment]
Do this in conjuction with https://github.com/aspnet/Razor/issues/304

**Comment by GrabYourPitchforks** [comment]
Should we add a utility static method to HttpAbstractions that registers default instances of all three encoders?

**Comment by GrabYourPitchforks** [comment]
The types `IHtmlEncoder`, `IJavaScriptStringEncoder`, and `IUrlEncoder` are in the Microsoft.AspNet.WebUtilities package. To register them from within your own AddServices method, reference the Microsoft.AspNet.Http.Extensions package and call `AddEncoders`.

**Comment by ajaybhargavb** [comment]
81c3b75980e9e232369e6f18aecdaa478685c39f
