### ISSUE TITLE
Make Unobtrusive Ajax available on Bower

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#2021]

**Comment by yishaigalatzer** [comment]
Related to #2015

**Comment by DamianEdwards** [comment]
Now at https://github.com/aspnet/jquery-ajax-unobtrusive

On bower:
![image](https://cloud.githubusercontent.com/assets/249088/6405356/4f73c15a-bdd7-11e4-8f2c-d4a539bb637f.png)
