### ISSUE TITLE
Consider IFilterFactory pattern for AuthorizeFilter

### ISSUE THREAD

**Issue by HaoK** [aspnet/Mvc#2022]

**Comment by yishaigalatzer** [comment]
@HaoK can you please elaborate.

**Comment by HaoK** [comment]
I don't have a ton of context I just filed it because harsh asked for something like this in the Mvc PR for authZ. I didn't want to make a big change as part of that so I filed this for tracking.

**Comment by yishaigalatzer** [comment]
Looked at the feedback, it doesn't add much value other than following a pattern. It also doesn't affect the public surface much, it does add an extra indirection.
