### ISSUE TITLE
Provide option to extend select list to contain current value

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2027]
Today, if a user passes a select list containing `{ 1, 2, 3, }` to `@Html.DropDownList()`, related methods, or the `<select>` tag helper when the expression value is `4`, the generated `<select/>` will look like nothing is selected.  This is true whether or not `4` would cause a validation error on submission.

Suggest automatically extending the select list to `{ 1, 2, 3, 4, }`, then select and disable the corresponding `<option/>` element.  For back-compatibility and to cover the tag helper case where the Razor source already contains an explicit `<option/>` for `4`, this should be opt-in.  That is, add `bool appendCurrentValue` parameters and `asp-append-current-value` attributes to the relevant HTML and tag helpers.

FYI the MVC 5 `enum` helpers (`@Html.EnumDropDownListFor()`) unconditionally ensured the current `enum` value was included in the generated `<option/>` elements and selected.  Could reuse some of that code (though not all of the semantics -- bit quirky and `enum`-specific in retrospect).

**Comment by yishaigalatzer** [comment]
I'm not sure why we worry about back compat here. Even if there is a knob (which I'm not sure why it should even be there) it should be off by default

**Comment by dougbu** [comment]
I agree with you on this behaviour being off by default @yishaigalatzer.  opt-in was the limit of my "back-compatibility" concern.

I also agree we shouldn't need a "knob" anywhere higher than an individual DDL call, LB call, or `<select/>` tag.  nothing broader than new parameters for the HTML helpers and a new bound attribute for the `<select/>` tag helper.

**Comment by yishaigalatzer** [comment]
I don't know why a knob is needed at all

-----Original Message-----

**Comment by dougbu** [comment]
offline decisions:
- when invoked using an HTML helper, always generate an additional `<option/>` element when the current value would not otherwise be shown
 - this is the correct behaviour and makes the `null` and "unknown" cases visibly distinct
- when invoked using the `<select/>` tag helper, have the contained `<option/>` tag helpers communicate their selection back (base on aspnet/Razor#238 or use existing `ViewContext.FormContext.FormData` approach)
 - change the `<select/>` tag helper to execute children prior to making a decision on generating the additional `<option/>` element
 - make this final decision based in part on whether an `<option/>` tag helper indicated it was selected.
- do not attempt to help / confuse tag helper users by removing duplicates they introduce between explicit `<option/>` (or `<!option/>`) elements and entries in the `asp-items` collection passed to the `<select/>` tag helper

**Comment by dougbu** [comment]
Updated subject to reflect unconditional nature

**Comment by dougbu** [comment]
closing as Won't Fix per offline discussions
