### ISSUE TITLE
Add support for camel casing in the default json contract resolver 

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#2030]
If a custom contract resolver is shipped out of the box to support #468, then it would be difficult for end users to support what `CamelCasePropertyNamesContractResolver` does. 
Example:
If we ship with out of box a custom contract resolver called `JsonContractResolver`, a user `ideally` should derive from this resolver and then configure for camel casing. But Json.net currently doesn't have an easy way to do this and only has the big hammer of using `CamelCasePropertyNamesContractResolver`. But using this resolver will remove all the important settings that we have in custom contract resolver.

So as part of this bug we should have out of box support for camel case and provide an easy way to configure this (probably at our formatter level?...like example: jsonformatter.CamelCasePropertyNames = true)
Code which is usable in this case: https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/Builder/LowerCamelCaser.cs#L64

**Comment by rynowak** [comment]
We use the default contract resolver, so this isn't really relevant.
