### ISSUE TITLE
Research implementation of composite json contract resolver.

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#2031]
Scenario:
a. We have one contract resolver which creates JsonContract where we take care of Required attributes on value types.
b. Users typically want to came case for their property names and want to use  CamelCasePropertyNamesContractResolver.

Question is about creating a composite contract resolver which satisfies `both` the above requirements.
Note that the above scenarios are just an example here. There could be other scenarios where composite resolver is needed.

**Comment by yishaigalatzer** [comment]
@JamesNK if you have thoughts or a recommendation on this, please share here

**Comment by rynowak** [comment]
We use the default contract resolver, so this isn't really relevant.
