### ISSUE TITLE
Null or empty select list values take value from previous lists on the same page

### ISSUE THREAD

**Issue by MelGrubb** [aspnet/Mvc#2039]
I have found some behavior I think it potentially dangerous. I have several select lists on a page together. They are rendered using Html.DropDownListFor, and each has a default option with the text "Select" and an empty string for a value. When the page is rendered, and any one of them has a "real" value selected, any subsequent lists //without// a value will take on the same value as the one before them on the page. These incorrect values will cascade down the page, filling in values on subsequent select lists.

I have created a small example solution to demonstrate the issue at https://github.com/MelGrubb/SanityTest

**Comment by dougbu** [comment]
@MelGrubb agreed there was an issue here.  We fixed the problem earlier in the RC1 milestone.  See #524.  Thanks for your involvement.

**Comment by MelGrubb** [comment]
I'm seeing this on a fresh project using MVC 5.2.3 (Jan 15, 2015). Either this is a regression, or it's not the same issue as #524. Specifically, this is about the selected VALUES in a drop-down taking on values from previous drop-downs on the same page, not the list of options.

**Comment by MelGrubb** [comment]
Oh, you mean rc1 of MVC 6. I see it now.

**Comment by dougbu** [comment]
Yes, we're tracking a similar issue for MVC 5.x at https://aspnetwebstack.codeplex.com/workitem/1913.  That issue may soon be closed due to the back-compatibility concerns @yishaigalatzer mentioned there.

**Comment by MelGrubb** [comment]
I hope so. This has the potential to corrupt data in production systems. Certainly in the one I'm working on, throwing out perfectly valid nulls, and substituting them with arbitrary values based on a completely different field is pretty bad. I'm going to work around it for now by giving the nulls a magic value (-1) instead, and then translating them back to nulls on the post.

**Comment by dougbu** [comment]
@MelGrubb FYI the recommended workaround is to "create separate enumerables, containing distinct `SelectListItem` instances, for each property in your model."

**Comment by MelGrubb** [comment]
I guess that's what I'll do for now. Unfortunately, this particular list is rather lengthy, so my viewmodel just exploded. Fortunately, it's an internal application, so bandwidth is not a problem.
