### ISSUE TITLE
Invoke ViewComponent using javascript

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Mvc#2042]
This is more of a discussion then an issue, I hope this is ok.

I'm developing a simple content management system using `ViewComponent`s and I need to update/rerender a component without rendering the complete page again. Is it possible to invoke a `ViewComponent` using javascript and skip the routing mechanism?

**Comment by yishaigalatzer** [comment]
No, that is not possible. You need a controller that returns a partial view

**Comment by yishaigalatzer** [comment]
You could build a standard proxy for viewcomponents if you'd like though (similarly you could build a proxy to partial views). e.g. you a catchall attribute route on an action

**Comment by marcuslindblom** [comment]
I guess it's the same problem if I have an html form in my viewcomponent and need to handle the posted data, a catch all attribute route on an action is the only way to handle the form post? @yishaigalatzer

**Comment by yishaigalatzer** [comment]
You should think of a viewcomponent as a fancy html helper and not a child action. 

Thus you can and should probably have individual actions to handle the form post rather than a catchall.
