### ISSUE TITLE
Implement an equivalent to AsyncTimeOutAttribute

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#2044]
We would like to be able to signal a timeout to the code below this. The design here is to call `request.Abort`

Related to https://github.com/aspnet/HttpAbstractions/issues/197

**Comment by yishaigalatzer** [comment]
This will be a resource filter (wrapping)

**Comment by kichalla** [comment]
Scenarios:
- Client disconnects while request is being executed on the server.
Example:
An html page could be making ajax calls and when user navigates to other pages, the previous page's ajax calls could cause disconnects.
- Execution timeout set on an action. Once the time elapses the given timeout value, the request should be aborted.

**Comment by kichalla** [comment]
This feature has been cut, so closing it.

**Comment by roterdam** [comment]
Is there guidance on how one can implement this? Can we just copy the code from previous mvc implementations?

**Comment by rynowak** [comment]
@roterdam - this is basically provided by the framework now https://msdn.microsoft.com/en-us/library/hh139229(v=vs.110).aspx

I'd recommend creating a CTS with your desired timeout, and passing it into whatever you want to put a timeout around. 

If you can tell us more about your scenario we can give more specific guidance.

**Comment by rynowak** [comment]
@Eilon @danroth27 - not suggesting we do any work here - just reopening to keep track of the conversation.

**Comment by douglasg14b** [comment]
@rynowak  Is there a way to change the execution limit for a specific controller method in the case of long-running queries?

**Comment by rynowak** [comment]
Closing this since there's no action item for us.

> Is there a way to change the execution limit for a specific controller method in the case of long-running queries? Need a way to run long queries (such as large inserts) without them being killed part way through...

@douglasg14b - there's nothing to change because there is no execution time limit, this feature doesn't exist, you have all of the building blocks if you want to build it.

**Comment by douglasg14b** [comment]
@rynowak 

Any long-running code terminates after exactly 120 seconds, returning a `502 Bad Gateway` response.  Google searches brought me to many StackOverflow posts and github issues related to execution time limits. 

There definitely seems to be some sort of time limit on requests.

**Comment by rynowak** [comment]
Then this is coming from IIS Express

@Tratcher do you have any advice about this

**Comment by Tratcher** [comment]
See requestTimeout https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module

**Comment by douglasg14b** [comment]
@Tratcher Thank you, that's good to know, and will be handy. However, is there a way to configure that for specific controllers and endpoints? I feel like it would be awkward for the entire website to have long timeouts when only a single endpoint needs it.

**Comment by Tratcher** [comment]
Not at the moment. You need to raise the global limit as high as you need and then we can talk about how to add an additional timeout with a lower value on a per controller/action basis. This would be done by supplementing the HttpContext.RequestAborted CancellationToken with an additional timeout value.

**Comment by douglasg14b** [comment]
Oh! I see, that makes sense. 

Thanks.
