### ISSUE TITLE
Consider making Razor's File -> Syntax Tree cache a generalized library function

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#2047]
Razor recently got the ability to cache the syntax trees it generated from View files. For my own project, I could use that exact same functionality and I would guess that this is a common pattern for users of `ICompileModule`.

Please consider generalizing that into a library somewhere between .Mvc.Razor and .Framework.

**Comment by yishaigalatzer** [comment]
We are not planning to provide a general capability here. We have a very specific implementation for are uses, and its super simple to write your own cache (where you will control the lifetime and eviction policies)
