### ISSUE TITLE
Consider using IMemoryCache with sliding expiration for ViewLocationExpanderCache

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#2050]
* We could consider switching the `DefaultViewLocationExpanderCache` to use an `IMemoryCache` instance. This way we could apply sliding expiration policies to evict cached view locations after some time (~5mins?).

* We build keys in `DefaultViewLocationExpanderCache` but don't hash them (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.TagHelpers/CacheTagHelper.cs#L172-L177). Since an arbitrary number of expanders can be added, we should consider hashing to avoid giant dictionary keys.

**Comment by danroth27** [comment]
We should measure the impact on memory given an app with lots of views.

**Comment by pranavkm** [comment]
We're noticing a large number of allocations pertaining to creating keys to lookup cached view locations. Using a `IMemoryCache` limits us to using string keys which would limit any optimizations we could create to resolve these. We'll continue using the current approach of a ConcurrentDictionary but use a custom comparer to avoid allocations.

**Comment by pranavkm** [comment]
Spoke to @davidfowl - apparently `IMemoryCache` keys are no longer string only - but we really don't care about evacuating cache entries either.
