### ISSUE TITLE
Dependency injection in HTML helpers

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Mvc#2056]
What's the recommended way of getting dependencies from the dependency injection container within an `IHtmlHelper` extension method if required?

**Comment by dougbu** [comment]
@Daniel15 use `htmlHelper.ViewContext.HttpContext.RequestServices.GetRequiredService<T>()`.  the `GetRequiredService<T>` extension method is in the `Microsoft.Framework.DependencyInjection` namespace.

TL;DR
not recommended: it is also possible to subclass `HtmlHelper` and `HtmlHelper<T>`, add your required services to the constructor parameters, make the services visible as properties, and replace our default services in the DI container.  but would still need extension methods that down-cast to the new type. the new subclass would also be incompatible when we change parameters in the `HtmlHelper` and `HtmlHelper<T>` constructors.  (framework does not support property injection into services that are themselves property injected e.g. `IHtmlHelper` properties in a Razor page.)

**Comment by Daniel15** [comment]
Thanks @dougbu!
