### ISSUE TITLE
Add unit tests to all nested provider managers to verify order

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#2066]
Required for things that resolve the IEnumerable or array of the following types:

`IActionConstraintProvider`
`IApiDescriptionProvider`
`IFilterProvider`
`IViewComponentInvokerProvider`
`IActionDescriptorProvider`
`IActionInvokerProvider`

and in general interfaces that implement the following pattern

```C#
    public interface IActionInvokerProvider
    {
        int Order { get; }
        void OnProvidersExecuting([NotNull] ActionInvokerProviderContext context);
        void OnProvidersExecuted([NotNull] ActionInvokerProviderContext context);
    }
```

**Comment by danroth27** [comment]
@rynowak Is there any work still to be done here?

**Comment by rynowak** [comment]
I recently reviewed all of this code and it's pretty straightforward. We could add tests, but it's medium-cost low benefit.
