### ISSUE TITLE
Removing _ prefix from views like _Layout.cshmtl

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#2068]
Since now there's a `wwwroot` folder and views are no longer available from the server, is there any reason to leave the `_` on ViewStart, Layout, and even partials ?

**Comment by Muchiachio** [comment]
I believe it was only used as a convention, because you don't necessary need to specify _ in any razor view names.

**Comment by pranavkm** [comment]
`_ViewStart` and now `_GlobalImport` are the only ones that require the `_` prefix. The prefix is optional for other view files. It might be simpler to leave the prefix for `_ViewStart` to make it easier to port applications. Additionally, the plan is to eventually bring back a [Web Pages \ Razor pages](https://github.com/aspnet/Mvc/issues/494) based framework built on top of Mvc which might require the underscore convention to denote files that cannot be directly requested.
