### ISSUE TITLE
Changing wwwroot via enviroment setting

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#2069]
Is it possible to have a `wwwroot` for some build configuration and a `devroot` for other build configuration ?

So my gulp task generate files to `devroot` when developing and the server start on `devroot` but when im doing a build (preparing for publish, when I minify and concatenate all files, etc) I use the wwwroot ?

does it make sense?

I currently have my script and style files inside wwwroot for development and another set of files (min-concat) also inside wwwroot. Normally I just point out to my own folders like Styles or bower_components but since the website cannot access them, I'm wondering what is the expected workflow for this with only one wwwroot ?

**Comment by DamianEdwards** [comment]
The intent is you always use your configured webroot as that what the web server can see. If you want to have different files between different environments, you can configure multiple targets in your grunt config and call them accordingly. You can then use the `<environment>` tag helper along with the `<link>` and `<script>` tag helpers to serve the different files on different environments, e.g.

``` HTML
<environment name="Development">
	<script src="~/lib/jquery/jquery.js"></script>
	<script src="~/lib/jquery-validation/jquery.validate.js"></script>
	<script asp-src-include="js/**/*.js" asp-src-exclude="*.min.js"></script>
</environment>
<environment names="Staging,Production">
	<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.1.min.js"
	        asp-fallback-src="~/lib/jquery/jquery.min.js"
	        asp-fallback-test="window.jquery"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"
	        asp-fallback-src="~/lib/jquery-validation/jquery.validate.min.js"
	        asp-fallback-test="window.jquery && window.jquery.validate"></script>
    <script asp-src="~/js/site.min.js"></script>
</environment>
```
