### ISSUE TITLE
On Mono with beta3, precompilation during build/pack/bundle fails to load tag helpers

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#2075]
I have created a small repro:
https://github.com/Tragetaschen/RazorPrecompileTagHelperIssue

When I do `kpm build`, I get the stack trace from #2074 with the underlying error
```
Cannot resolve TagHelper containing assembly 'Microsoft.AspNet.Mvc.TagHelpers'.
Error: Could not load file or assembly 'Microsoft.AspNet.Mvc.TagHelpers'
or one of its dependencies. The system cannot find the file specified.
```

When I do `k kestrel`, the application starts fine.

In both cases, the `Console.WriteLine` from the compile module's constructor is printed.

**Comment by danroth27** [comment]
Dup of #1693. This is being fixed post beta3.
