### ISSUE TITLE
Manually validate the model. 

### ISSUE THREAD

**Issue by phillip-haydon** [aspnet/Mvc#2078]
Because WebAPI sets parameters to null when there's no arguments to satisfy the creation of the object, I have to create the model itself in an Action Filter.

I tried to do it in a Model Binder but implementing that is far too complicated when all I need is binding to be implemented, as is, with the exception that it doesn't return null.

As a result validation wont work because its done before Action Filters are executed. 

So how can I manually do validation after the model has been fixed?

**Comment by yishaigalatzer** [comment]
This sounds like a Web API 2.X question. This repository tracks MVC 6.
I suggest you open a question in the forums or stackoverflow.

in MVC 6 we will create an object rather than return null by default, so your issue is resolved in this framework. If you change the object in an action filter, you can always call `TryValidate` on it. This wasn't supported in Web API 2.x

**Comment by yishaigalatzer** [comment]
In Web API 2 you can call `Validate<T>(model)` in the action body

**Comment by phillip-haydon** [comment]
@yishaigalatzer cannot, this is done at a filter.

I had to add an action filter to fix the broken design of WebAPI giving null objects, but because that happens after model binding and validation I have to do validation in a action filter myself. 

I just rewrote the validation myself just lacking support for complex models, since we don't have anything complex.

**Comment by yishaigalatzer** [comment]
Here is how you can do it very simply - 

```C#
using System.ComponentModel.DataAnnotations;
using System.Web.Http;
using System.Web.Http.Controllers;
using System.Web.Http.Filters;

namespace WebApplication5.Controllers
{
    public class ValuesController : ApiController
    {
        [SetData]
        public string Get(Foo foo)
        {
            string result = null;
            if (foo == null)
            {
                result += "Was Null\r\n";
            }

            if (ModelState.IsValid)
            {
                result += "Was Valid\r\n";
            }
            else
            {
                result += "Invalid Keys: " + string.Join(", ", ModelState.Keys);
            }

            return result;
        }
    }

    public class SetData : ActionFilterAttribute
    {
        public override void OnActionExecuting(HttpActionContext actionContext)
        {
            var foo = new Foo();
            actionContext.ActionArguments["foo"] = foo;

            ((ApiController)(actionContext.ControllerContext.Controller)).Validate(foo);
        }
    }

    public class Foo
    {
        [Required]
        public string Name { get; set; }
    }
}
```

**Comment by phillip-haydon** [comment]
@yishaigalatzer I have a global action to fix up the null parameters. 

The validate stuff is helpful tho. Thanks a lot.
