### ISSUE TITLE
Is there anything like IDirectRouteFactory

### ISSUE THREAD

**Issue by djanosik** [aspnet/Mvc#2081]
Hi,

is there anything like IDirectRouteFactory? Or - is there any way to modify routes created from attributes?

Thank you!

**Comment by yishaigalatzer** [comment]
There is no `IDirectRouteFactory` you can use the `ApplicationModel` to modify routes (and many other things).

You can start here:
https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ApplicationModelWebSite
or here:
https://github.com/yishaigalatzer/ResourceController
