### ISSUE TITLE
Cannot get controller instance in IExceptionFilter

### ISSUE THREAD

**Issue by aanufriyev** [aspnet/Mvc#2097]
In previous versions there was a way to get controller instance in exception filter like:
<code>var curentController = actionExecutedContext.ActionContext.ControllerContext.Controller;<code> 

In MVC6 this feature seems to be missing from <code>ExceptionContext</code>. In <code>IActionFilter</code>'s <code>ResultExecutingContext</code> Controller property exists.

This stuff is very useful when exception handling requires some sort of knowledge about exception context. For example - exception to status code maps with customization on per controller basis.

**Comment by rynowak** [comment]
Hi @aanufriyev we made this change recently as part of a change to when controllers are instantiated and disposed. This is something we might consider adding back if it impacts some significant scenarios.

We've also anticipated scenarios like yours and have a few alternative ways of accomplishing that.  Would you mind sharing some sample code with us? If you can give me an example I want to take a crack at simplifying it based on the MVC 6 model for filters and get your feedback.

**Comment by aanufriyev** [comment]
Here is gist https://gist.github.com/aanufriyev/4bd6b4b19cec0cd5e755
Just a sample, but controller instance can act as dependency provider. Anyway - type of controller is available, but I think it is not a good idea to create controller instances in filter.

**Comment by rynowak** [comment]
Thanks.  Here's what I'd suggest trying.

This is based on a new pattern that we have in vNext to place arbitrary metadata in filters. So, an `IFilter` might be something that acts (like `IExceptionFilter`) or it might just be data (`ExceptionMappingAttribute`). 

The advantage of this is that it's scoped, so you can have a mapping apply globally, to just the controller, or to an action. It's also not coupled to a particular controller, so you can use the mappings and filters independent of the controller type.

It's also possible now to do DI in filters directly (see `TypeFilterAttribute`), so you don't need to reach into the controller and get its services.

```
private class ExceptionMappingAttribute : IFilter
{
    public ExceptionMappingAttribute(Type exceptionType, HttpStatusCode statusCode)
    {
        ExceptionType = exceptionType;
        StatusCode = statusCode;
    }

    public Type ExceptionType { get; }
    public HttpStatusCode StatusCode { get; }
}

private class MapExceptionsAttribute : Attribute, IExceptionFilter
{
    public void OnException(ExceptionContext context)
    {
        // Could also build a lookup table if desired
        var mappings = context.Filters.OfType<ExceptionMappingAttribute>();
        foreach (var mapping in mappings)
        {
            if (mapping.ExceptionType == context.Exception.GetType())
            {
                context.Result = new HttpStatusCodeResult((int)mapping.StatusCode);
                return;
            }
        }
    }
}

[)]
[ExceptionMapping(typeof(ScimResourceConstraintException), HttpStatusCode.PreconditionFailed)]
[ExceptionMapping(typeof(ScimResourceNotFoundException), HttpStatusCode.NotFound)]
public class FooController : Controller
{
    [ExceptionMapping(typeof(InvalidScimOperationException), HttpStatusCode.BadRequest)]
    [ExceptionMapping(typeof(ScimResourceConflictException), HttpStatusCode.Conflict)]
    public void FooAction()
    {
    }
}

<Startup.cs>

services.ConfigureMvc(options =>
{
    options.Filters.Add(new ExceptionMappingAttribute(
        typeof(NotImplementedException), 
        HttpStatusCode.NotImplemented));
    options.Filters.Add(new MapExceptionsAttribute());

    // or if you need DI in your filter
    options.Filters.Add(new TypeFilterAttribute(typeof(MapExceptionsAttribute)));
});

```

Let me know what you think.. Is this an improvement?

**Comment by aanufriyev** [comment]
This stuff can become messy :) Also factor in some inheritance... And exceptions can be quite granular.

```C#
[ExceptionMapping(typeof(ScimResourceConstraintException), HttpStatusCode.PreconditionFailed)]]
[ExceptionMapping(typeof(ScimResourceConflictException), HttpStatusCode.Conflict)]
[ExceptionMapping(typeof(ScimResourceNotFoundException), HttpStatusCode.NotFound)]
[ExceptionMapping(typeof(InvalidScimOperationException), HttpStatusCode.BadRequest)]
[ExceptionMapping(typeof(SomeParsingException), HttpStatusCode.BadRequest)]
[ExceptionMapping(typeof(InvalidOperationException), HttpStatusCode.BadRequest)]
[ExceptionMapping(typeof(NotImplementedException), HttpStatusCode.NotImplemented)]
public class FooController : Controller
{
    [ExceptionMapping(typeof(ScimResourceConstraintException), HttpStatusCode.PreconditionFailed)]]
    [ExceptionMapping(typeof(ScimResourceConflictException), HttpStatusCode.Conflict)]
    [ExceptionMapping(typeof(ScimResourceNotFoundException), HttpStatusCode.NotFound)]
    [ExceptionMapping(typeof(InvalidScimOperationException), HttpStatusCode.BadRequest)]
    [ExceptionMapping(typeof(SomeparsingException), HttpStatusCode.BadRequest)]
    [ExceptionMapping(typeof(InvalidOperationException), HttpStatusCode.BadRequest)]
    [ExceptionMapping(typeof(NotImplementedException), HttpStatusCode.NotImplemented)]
    public void FooAction()
    {
    }
}
```
Maybe ExceptionMappingAttribute can contain more then one mapping, but it feels a bit strange to have two filters for for exception mapping.

**Comment by rynowak** [comment]
Keep in mind that doing it this way works *with* inheritance and scoping, there's no need to duplicate. So the exception mappings on an action include those on:
1). The action directly
2). The controller
3). Inherited from a base controller
4). Registered in startup (options.Filters)

If your exception mappings are consistent you can register them all during startup. If you want to treat the same exception differently in different scopes/controllers this supports that.

**Comment by aanufriyev** [comment]
I think that filter stuff will be ok. Will move mapping to it. One thing still bugs me:

In old case - controller was owner of knowledge about it own exception mappings. New way - this knowledge is separated into another entity, which is mapped one-to-one with controller and cannot be used in other places(At least in my case. Will be strange to use specific protocol exception maooing with anything other then base protocol endpoint controller).

**Comment by rynowak** [comment]
> In old case - controller was owner of knowledge about it own exception mappings.

I'm not really sure what you mean - you can put the `[ExceptionMapping(...)]` wherever it is meaningful. If you put `[ExceptionMapping(typeof(FooException)...]` on a controller, then it only applies to the actions in that controller.


Same thing with `[MapExceptions]`. You don't have to register it in `options.Filters` -- it could go on a controller/action/controller-base-class, whatever you think is appropriate. If you only use this feature in general for certain controllers, then just add the filter there.

If you want to simplify things further you could do something like this, and you won't need `[MapExceptions]` at all. 
```
private class ExceptionMappingAttribute : IExceptionFilter
{
    public ExceptionMappingAttribute(Type exceptionType, HttpStatusCode statusCode)
    {
        ExceptionType = exceptionType;
        StatusCode = statusCode;
    }

    public Type ExceptionType { get; }
    public HttpStatusCode StatusCode { get; }

    public void OnException(ExceptionContext context)
    {
        if (ExceptionType == context.Exception.GetType())
        {
            context.Result = new HttpStatusCodeResult((int)StatusCode);
            return;
        }
    }
}
```

**Comment by aanufriyev** [comment]
I'm talking about encapsulating knowledge inside entity, that must own it exclusively. Sorry for crappy English

**Comment by rynowak** [comment]
No worries and thanks for your feedback. We still may bring back the ability to see the controller in exception filters, just gathering info for now.

**Comment by aanufriyev** [comment]
Thanks for answers. Will close issue and use suggested way for now.
