### ISSUE TITLE
Pulling helpers into scope in cshtml

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Mvc#2100]
With previous versions of ASP.NET MVC, "using" directives can be added to C# code generated from Razor (cshtml) files by adding them to the `Views\web.config` file (`system.web.webPages.razor` - `pages` - `namespaces`). A NuGet package that includes HtmlHelper extensions can take advantage of this by adding something like this to `Content\Views\web.config.transform`:

```xml
<configuration>
	<system.web.webPages.razor>
		<pages>
			<namespaces>
				<add namespace="MyProject.Mvc" />
			</namespaces>
		</pages>
	</system.web.webPages.razor>
</configuration>
```

So `@Html.Foo()` will work right away if `Foo` is an extension method in the `MyProject.Mvc` namespace.

Is there an equivalent for ASP.NET MVC 6?

**Comment by NTaylorMullen** [comment]
Yup definitely is! :smile: http://stackoverflow.com/questions/28719298/add-namespace-to-all-views-in-asp-net-mvc-6/28729828#28729828

**Comment by Daniel15** [comment]
Is there a way to add the `using` statement to `_GlobalImport.cshtml` automatically when a NuGet package is installed?

**Comment by davidfowl** [comment]
Nope, we don't support content packages right now.

**Comment by Eilon** [comment]
And my personal opinion about a NuGet package doing such a thing is that it's quite evil. If I install a regular NuGet package with a DLL, I don't want it effectively adding a "using" statement to all my *.cs files. I don't want a Razor-related NuGet package doing that either.
