### ISSUE TITLE
StringOutputFormatter fails when HttpNotAcceptableOutputFormatter is used

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#2108]
### Repro
Add the following code to startup and return a `string` from a controller action.
```C#
services.AddMvc().Configure<MvcOptions>(options =>
{
    options.OutputFormatters.Insert(0, new HttpNotAcceptableOutputFormatter());
});
```

### Expected
The string value is written out

### Actual
A 406 result with no content

(This came from a customer code)

**Comment by kichalla** [comment]
Current behavior:

![image](https://cloud.githubusercontent.com/assets/6559784/6511175/bd889290-c31f-11e4-97bc-f24de268538a.png)
