### ISSUE TITLE
Provide a sample that shows how to do post as MVC form from jQuery

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#211]
Similar to the issue mentioned below, we need to have this support in WebFx too.
http://aspnetwebstack.codeplex.com/workitem/1564

```
public class Person
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public IList<Address> Addresses { get; set; }
    }

    public class Address
    {
        public string City { get; set; }

        public string State { get; set; }
    }
```

```
public IActionResult Post(Person p)
        {
            return new JsonResult(p);
        }
```
Following works currently:
Request data: `Id=10&Name=John&Addresses[0].City=Redmond&Addresses[0].State=WA`
Response: `{"Id":10,"Name":"John","Addresses":[{"City":"Redmond","State":"WA"}]}`

Following does not:
Request data: `Id=10&Name=John&Addresses[0][City]=Redmond&Addresses[0][State]=WA`
Response: `{"Id":10,"Name":"John","Addresses":[{"City":null,"State":null}]}`

**Comment by sornaks** [comment]
Checked in. Thanks! https://github.com/aspnet/Mvc/commit/eeabe2760698ea640e113063b546d10bd2737ece
