### ISSUE TITLE
AmbiguousException with query string parameters in API

### ISSUE THREAD

**Issue by StevenVandenBroeck** [aspnet/Mvc#2113]
I have the following actions in my controller : 

```C#
[HttpGet]
public IActionResult GetAll()

[HttpGet]
public IActionResult GetAllPaging([FromQuery]int page, [FromQuery]int pagesize)

[HttpGet]
public IActionResult GetByAuthorIdPaging([FromQuery]int authorid, [FromQuery]int page, [FromQuery]int pagesize)
````

which would enable me to do the following : 
```
GET /myapi/books                                                             for GetAll
GET /myapi/books?page=2&pagesize=10                        for GetAllPaging
GET /myapi/books?authorid=7&page=1&pagesize=10     for GetByAuthorIdPaging
```

When I try any of the above requests, I get an AmbiguousException (Multiple actions matched. The following actions matched route data and had all constraints satisfied...).

Do I need to configure something else to enable the router to match the right action to an URL with query string parameters ?

I'm using K runtime beta4-11094 and MVC packages beta4-12771.

**Comment by rynowak** [comment]
Hi Steven,

MVC 6 by-default doesn't have a feature like WebAPI action overloading - additionally all action parameters are by-default optional. The 'MVC' way to build this would be just use one action with `int?` parameters and decide to page or not inside the action.

If you're not enamored with this idea we have some other options. We've a built a compatibility shim for porting WebAPI applications, which would restore the WebAPI 2 behavior. See  https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.WebApiCompatShim/ApiController.cs

If you're curious about the shim, this is all built on top of the new `IActionConstraint` api, which can let create your own type of semantics for disambiguating between actions. For an example, this is how we do overloading in the shim: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.WebApiCompatShim/OverloadActionConstraint.cs

You could also build something (using the above as a sample) much simpler than this that meets your needs. The above is intended to be exactly compatible with WebAPI2 (including all of its quirks). `IActionConstraint` can be implemented by an `Attribute` class and added directly to an action or controller.

**Comment by StevenVandenBroeck** [comment]
I've tried a custom implementation of an IActionConstraint based on your info and it seems to do what I want.
Thanks.
