### ISSUE TITLE
Mvc ViewEngine not working as expected

### ISSUE THREAD

**Issue by HornerGrahame** [aspnet/Mvc#2115]
Ive created a custom implementation of the RazorViewEngine which overrides the methods and locations for views, I have cleared the viewengine collection of the mvc options and attached the custom view engine type.

 however the view engine fails to resolve? It seems that the view engine hasn't been successfully registered

**Comment by Eilon** [comment]
Can you show any of your registration code from Startup.cs? And any relevant code from your custom view engine?

**Comment by danroth27** [comment]
Take a look at this sample in the MVC tests and let us know if you are doing something different: https://github.com/aspnet/Mvc/tree/dev/test/WebSites/CompositeViewEngineWebSite.

**Comment by danroth27** [comment]
Closing for now.

**Comment by HornerGrahame** [comment]
This was caused by some weird config issue on two of my development systems; a reinstall after finding a number of other issues and everything works as expected? but haven't found root cause as yet :'(
