### ISSUE TITLE
TagHelpers: asp-route with collection of parameters

### ISSUE THREAD

**Issue by Boglen** [aspnet/Mvc#2119]
Will asp-route to take a collection of parameters?

properties = new { id = 21, sort_order = "desc", pageNum = 1}

**Comment by danroth27** [comment]
You can add additional parameters to the route using asp-route-*, where * is the name of the parameter you want to add. Something like this: `<a asp-route="routeName" asp-route-id="23" asp-route-sort_order="desc" asp-route-pageNum="1" asp-route-foo="@foo"></a>`.

**Comment by Boglen** [comment]
I understand. But what if I want to use a dynamic collection of parameters? Or will be available only to the static enumeration?

**Comment by danroth27** [comment]
Ah, makes sense. You can add this yourself right now by deriving from our tag helper and adding the property collection. We can also look at supporting this directly.

**Comment by simon25608** [comment]
Hello,
Some progress on this?

**Comment by rynowak** [comment]
You can do this like this:
```
@{

var routeValues = new Dictionary<string, string>();
...  // Add to routeValues
}
<a ... asp-all-route-data="routeValues">....</a>
```

**Comment by Remleo** [comment]
What if I need to pass a values collection? For example:
```html
<a href="@Url.Action(...., new { Values = new [] { "Foo", "Bar" } })"
```

Is this possible with `asp-all-route-data`?
