### ISSUE TITLE
Components with post form support

### ISSUE THREAD

**Issue by adeel41** [aspnet/Mvc#2124]
I've just started using mvc6 beta3 and don't see a way to post form data to a component? Tried searching on internet but didn't find anything at all. Any help will be appreciated.

Cheers,

**Comment by Eilon** [comment]
From where are you trying to post data? And posting it to where?

**Comment by adeel41** [comment]
lets assume it is a login ViewComponent. So I can display it using ViewComponent but when the user click submit button, I should submit it to the ViewComponent so that if ModelState is invalid then I display those errors. I don't see any way I can do it using ViewComponent. I think I've to create a proper controller for this functionality. 

My initial understanding about ViewComponent is, it is a reusable component which can be displayed on different pages but is it just for HTTP GET type of things ?

**Comment by rynowak** [comment]
A `ViewComponent` is not a public endpoint - it's exactly what you said "a reusable component which can be displayed on different pages". It's not reachable from via any URL or route, it's only part of the pages where you include

If you used a `ViewComponent` for a login form, then have it post to your login controller and redirect to a logic page that can display errors. You might want a bespoke action anyway for a failed login to include things like a password reset.

**Comment by adeel41** [comment]
> and if validation fails, redirect to a login page that can display errors.

This is my issue. If I redirect then I will lost the ModelState information which I needed on my ViewComponent (or any other page) to display ValidationMessage(s).

Secondly I am not creating a login view component, I used it as an example because it is a common control which also post forms data to server.

**Comment by danroth27** [comment]
Some ideas on how you can preserve the validation messages:
- Preserve the data in the query string
- Preserve the data using TempData (coming soon)

Or just post directly to the target controller that can do the validation.
