### ISSUE TITLE
[Testing] Reduce duplication in functional tests

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2140]
Thanks to @HaoK for his [suggestion](https://github.com/aspnet/Mvc/pull/2137#discussion_r26000445) in PR #2137: Switch to a shared `_client` field for functional tests.  In almost-all cases, the server is configured identically for all test methods.  For example,
``` c#
  private readonly HttpClient _client;

  public ActionResultTests()
  {
    var server = TestHelper.CreateServer(_app, SiteName);
    _client = _server.CreateClient();
  }
```

(Might be worth a script to delete the existing `var server` and `var client` initialization lines.  Have about 650 references just to the `CreateServer()` overload shown above and about 75 test classes.)

**Comment by danroth27** [comment]
We decided this isn't worth doing.
