### ISSUE TITLE
Script & Link tag helpers should support generating cache-busting file version hash in URL

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#2141]
The `ScriptTagHelper` and `LinkTagHelper` should support an option that enables the generation of a file version hash of the linked file contents placed in the URL for the purposes of busting client-side cache. The hash should be placed in the query-string (key `v`). The helpers should render the hash by default.

This feature existed in `System.Web.Optimization` so there might be some code we can use from there.

### Example
``` HTML
<link src="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-file-version="true" />
<script src="~/lib/jquery/jquery.min.js" asp-file-version="true"></script>
```

**Comment by BrianVallelunga** [comment]
Any chance we'll get the cache-busting feature for images too?

**Comment by DamianEdwards** [comment]
@BrianVallelunga great idea! The `<img />` tag should support globbing too. Logged #2249 to track it

**Comment by sornaks** [comment]
https://github.com/aspnet/Mvc/commit/0e783ace5898c761435541aa937085a8593a75d0
