### ISSUE TITLE
Cache tag helper should have an Enabled property

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#2142]
The `CacheTagHelper` should have a property `Enabled` that makes it simple to conditionally disable/enable the caching. This can be very useful in debugging scenarios, e.g. disabling caching if a given cookie is present.

``` HTML
<cache enabled="@string.IsNullOrEmpty(Context.Request.Query["cache"])">...</cache>
```

**Comment by sornaks** [comment]
https://github.com/aspnet/Mvc/commit/b08a2154c10a3c297f1ba61138cad5726a7c7dd9
