### ISSUE TITLE
Custom/Detailed Errors on IIS

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#2148]
Right now, on MVC6 project, for displaying detailed errors I included a web.config with :
```
<configuration>
  <system.web>
    <customErrors mode="Off" />
  </system.web>
</configuration>
```

is this still the recommended approach to configure IIS or will be/are other way to specify these settings.?

I have the same question for domain.com redirect to www.domain.com

**Comment by danroth27** [comment]
For ASP.NET 5 there is a new Diagnostics middleware ([Microsoft.AspNet.Diagnostics](https://nuget.org/packages/microsoft.aspnet.diagnostics)) that you can use during development. You can find an example of how to use it at https://github.com/aspnet/Diagnostics/tree/dev/samples. 

The System.Web config section actually has no effect for ASP.NET 5 apps.

**Comment by Bartmax** [comment]
@danroth27  I used it to debug errors after published to azure and it actually displayed the detailed error message instead of the non-informative ysod. 

I will try the diagnostics. Is there any redirection middleware that can I use ? I'm not wondering on developing but after publishing to azure right now.
