### ISSUE TITLE
Anti-forgery token infrastructure not extensible

### ISSUE THREAD

**Issue by stimms** [aspnet/Mvc#2153]
As it currently stands the anti-forgery token infrastructure is perfect for dealing with pages that submit form data. The token is placed in a hidden field and this is submitted along with the rest of the form data. On the server AntiForgeryTokenStore extracts the token from both the form and from the cookie to allow for comparison. 

It is becoming common practice that data is submitted in JSON format over a POST request. This behaviour is supported by MVC currently using the [FromBody] attribute for model binding. The token can easily be extracted client side by taking the value from the form field and including it in the post. However there is no way to instruct the AntiForgeryTokenStore to take its value from the body of the post and not from the form collection. 

My approach would be to create a new implementation of ITokenStore which could take its value from a JSON payload in the body. However ITokenStore is marked internal. It would be nice if this interface could be exposed as an extension point. It seems odd that FromBody is supported but in doing so there is no way to use anti-forgery tokens.

**Comment by danroth27** [comment]
Adding @GrabYourPitchforks @blowdart for their thoughts on this.

**Comment by GrabYourPitchforks** [comment]
Anti-CSRF tokens aren't needed for anything other than typical form submissions where authentication is automatic (e.g., cookie, NTLM). Proper API calls done via XHR should really use an authentication mechanism that isn't susceptible to CSRF attacks. I vote won't fix.
