### ISSUE TITLE
The type or namespace name 'global_asax' does not exist in the namespace 'ASP'

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#2154]
Having a .cshtml file inside App_Code give errors on Visual Studio about the global_asax doesn't exist on namespace ASP.

this is used to have some razor function available application wide.

Compilation and application works ok, it's just the errors that are annoying.

**Comment by danroth27** [comment]
@Bartmax Are you using MVC 5 or MVC 6?

**Comment by Bartmax** [comment]
Oops, you are right, I'm using MVC 5. sorry.

**Comment by orlandow** [comment]
@Bartmax I have the same issue (http://stackoverflow.com/questions/28513532/mvc-5-c6-asp-global-asax-does-not-exist-in-the-namespace-asp)

Did you find a solution?
