### ISSUE TITLE
[Suggestion] MVC should also support route's configs directly in the web.config

### ISSUE THREAD

**Issue by MaleDong** [aspnet/Mvc#2177]
Hello all:)

I'm now doing quite a big MVC program with a lot of complicated routes. It would be nice if you can support MVC routes in the web.config. I mean if I do configs in the web.config, there's almost no need to write down codes again (or less codes) in the RouteConfig.cs.

What I mean in details is:

1) Generally speaking, we say something in the RouteConfig.cs:
routes.MapRoute(……);

2) Now we can just do a lot of complicated configurations in the web.config, we need a "mvcConfig" tag and all of its related things (something like below, maybe Microsoft can deeply consider how to design like this):

![default](https://cloud.githubusercontent.com/assets/6959154/6660993/cc446a02-cbdf-11e4-9f91-10c23d801bb7.PNG)

**Comment by danroth27** [comment]
In ASP.NET 5 there is a new configuration model that replaces the existing web.config model. We have no plans to add a config based model for setting up routes, but it's certainly something you could add for your own projects.

**Comment by MaleDong** [comment]
@danroth27 
It would be nice if ASP.NET MVC5 can include this in the new configuration model (json file) for very complicated configuration routes. Or any torturials to do the self json configuration for routes?

**Comment by danroth27** [comment]
You can find a sample on how to use the config system here: https://github.com/aspnet/Entropy/blob/dev/samples/Config.Sources.Web/Startup.cs. You would need to write a component that reads in routing information from config and sets up whatever route you want.

**Comment by MaleDong** [comment]
@danroth27 
Thanks! Maybe this issue can be considered to be done for the next version of MVC 6 or later. I think this should be useful and practical.
