### ISSUE TITLE
Modelbind dynamic object in Controller

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Mvc#2178]
I have a custom route implementing `IRouter` and in the method `RouteAsync(RouteContext context) {}` I add a `dynamic` object into my `context.RouteData.Values` like this:
```
        public async Task RouteAsync(RouteContext context)
        {
            using (var session = documentStore.OpenAsyncSession())
            {
                var currentPage = await session.LoadAsync<dynamic>("pages/1");
                context.RouteData.Values["controller"] = "Home";
                context.RouteData.Values["action"] = "index";
                context.RouteData.Values["bar"] = currentPage;
                await _target.RouteAsync(context);
            }
        }
```

Then in my `HomeController` I try to take the bar parameter in the `Index`method like this:
```
    public class HomeController : Controller
    {
        public IActionResult Index(Foo bar)
        {
            return View();
        }
    } 
```
But the `ModelBinder` does not bind the `Foo` object but if I change the parameter to `dynamic` it binds to object.

This works in older versions of MVC, are you planning on introducing this again or is it a known issue?

**Comment by dougbu** [comment]
@marcuslindblom please provide more details on where you are updating `RouteData`.

does MVC 6 bind the `bar` parameter if you change the action to `public IActionResult Index([FromRoute] Foo bar) {}`?

**Comment by marcuslindblom** [comment]
@dougbu I have updated the issue with some more details.

It does not work with `[FromRoute]` either.

**Comment by dougbu** [comment]
@marcuslindblom I could not find a special case for this scenario in the MVC 5 code.  might be a bit faster to debug if you could upload a simplified MVC 6 sample that e.g. does not use a database.  easiest for us if you could host the sample in a GitHub repo.

**Comment by rynowak** [comment]
Hi Marcus, follow up question.. if you take the value from `await session.LoadAsync<dynamic>("pages/1");` and manually convert it to an instance of `Foo` in your custom route does that solve the problem?

I'm trying to figure out if there's some conversion code that we're missing or if there's something else broken when using route data.

**Comment by marcuslindblom** [comment]
@rynowak If I create an instance of `Foo` and set the property value on that instance it binds the object correctly in my `Controller` so yes, it solves the problem.
```
var currentPage = await session.LoadAsync<dynamic>("pages/1");
context.RouteData.Values["bar"] = new Foo { Heading = currentPage.Heading };
```

**Comment by danroth27** [comment]
@rynowak Please look into what the current behavior is on MVC 5.

**Comment by rynowak** [comment]
@marcuslindblom - the code that we're using to do the conversion here (between route values and the model) hasn't changed between versions.

Can you share a complete sample of this working on an earlier version of MVC?

**Comment by marcuslindblom** [comment]
@rynowak Yeah sure, maybe I can fix it tonight.

**Comment by yishaigalatzer** [comment]
@marcuslindblom one thing to consider is that this pattern is not really recommended, you can just write a "greedy" model binder instead. With MVC 6 you can now write async model binders, the reason we enabled them is exactly for this kind of scenario.

So although there might be a bug here, this is not the right approach for coding.

**Comment by marcuslindblom** [comment]
@yishaigalatzer I use this pattern because the `Type`:s I'm loading is not known by my application, it is from another assembly, therefor the dynamic is exactly what I need and I don't see any other solution.

Here is a super quick sample using a custom route where I load a dynamic object and it binds correctly in the `HomeController`. http://cl.ly/aHLx

**Comment by yishaigalatzer** [comment]
My comment is not around using dynamic, its around avoiding a custom route handler and using a model under instead.

**Comment by marcuslindblom** [comment]
Ok I see, the reason I'm using a custom route is because I have urls without the controller name and action. My urls are more SEO-friendly and look like http://example.com/lorem-ipsum/dolar/site/amet, and in my custom route I resolve the controller name and action based on the url. Well, that was a side track :)

**Comment by yishaigalatzer** [comment]
You should still do the model binding in a model binder, and leave the custom route to do routing stuff. I'm also not clear about using dynamic, since you obviously know the type in your controller code, why not in the model binder?

Another alternative to using custom routes is to use attribute routes (if that works, not sure about your exact scenario), or provide the action name in the defaults section of the route (if possible of course) + some constraints.

Here is a sample for a greedy model binder:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ModelBinding/Binders/FormCollectionModelBinder.cs

and registration:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc/MvcOptionsSetup.cs#L41

**Comment by marcuslindblom** [comment]
Ok, a little background here. I'm developing a [CMS](https://github.com/brickpile/brickpile) system and the code sample is from the custom routing inside the CMS. As I said before I'm using URL:s that are more readable `page-1/page-2/page-3` and so on, The custom route resolves `page-1/page-2/page-3` to use i.e. `SuperCoolController` and `page-1/page-2/` to `SuperDuperCoolController`.

This is a part of the CMS and a third party developer, developing a web site based on my CMS does not need to care about how a specific [ContentType](https://github.com/brickpile/brickpile/wiki/How-BrickPile-Works#content-types) is routed because I handle that for them. 

So the look up is located in the custom route and the model binding is handled by the default model binder so I don't see the problem? Where can I do a look up and say, for `page-1/page-2/page-3` you should use the `SuperCoolController` if I'm not using a custom route? As far as I know this is exactly what routes should be used for?

**Comment by yishaigalatzer** [comment]
Yes I agree with the part of matching controllers to routes. I don't agree with dropping data in a route value and just let binding take over. You should just write a binder and register it, that's the right way to do it regardless of how this used to work in the past.

**Comment by yishaigalatzer** [comment]
@marcuslindblom I'd be glad to help you with moving a CMS solution forward, I (and others on the team) have done a similar exercise with a few major CMS systems already. Feel free to reach out to me directly, as I think this is starting to pollute this thread.

**Comment by danroth27** [comment]
@marcuslindblom If you have a sample that shows this behavior working on MVC 5 could you please share it with us? We would like to ensure that we haven't regressed any behavior in MVC 6. Thanks.

**Comment by marcuslindblom** [comment]
@danroth27 Yes, I posted this sample two days ago. Here is the link to a quick sample with a custom route using `dynamic` that binds correctly. http://cl.ly/aHLx

Let me know if I can help in any way.

**Comment by rynowak** [comment]
@marcuslindblom - sorry for the delay, I got some time to look at this today.

Even though your `await session.LoadAsync<dynamic>(...)` is typed `dynamic` in the repro you gave me, it's return a `Foo` which happens to be an exact match of your parameter type. 

![](http://i.imgur.com/p1YJ431.png)

This is the critical factor for whether or not model binding will match it up with your parameter, I expected, MVC doesn't have any sort of special conversion code to enable this scenario, it requires the value to match (or have a conversion via `TypeConverter`).

So based on the information that you've given us so far, I can't find any missing features here in MVC6 that are blocking this. Is it possible that the MVC6 code for your route is returning something not assignable to the parameter type? 


I'll second what Yishai said, in my opinion the best way to do this is to write an `IModelBinder` that can look at the route data or value providers. The biggest benefits are that inside a model binder you can see the parameter type, so you know what to convert to, and you can also add validation errors if that's meaningful in your scenario.

**Comment by marcuslindblom** [comment]
@rynowak I see another behavior in MVC 6, maybe this is a RaveDB problem instead, because the loaded object does not return the actual type using the exact same version of RavenDB both in MVC 5 and 6. Can you understand whats going on here and why it's different?

![screen shot 2015-03-21 at 12 25 03](https://cloud.githubusercontent.com/assets/319720/6764854/cc8675a2-cfc5-11e4-8cbd-c711e11c49ff.png)

Creating my own `IModelBinder` is most certainly a good idea but I am satisfied with the functionality and how it works in MVC 5 and I can't seem to wrap my head around how the model binder would look to work with dynamically loaded objects?

**Comment by yishaigalatzer** [comment]
`IModelBinder` is the right abstraction for the job. So although you might be satisfied with how it works in MVC5, you are doing a few things differently than the framework expects:

1. `RouteData` is really intended for both incoming urls and link generation, the code sample you pasted obviously breaks that.
2. Getting the data out of session could be expensive, and if the user code never binds to it, its unnecessary a `modelbinder` will try to read the data only when the user is trying to read the data, saving both compute and memory when that happens.
3. Model binders run at the "right" point in the code making it much easier for you to debug if you use the MVC source code.

For your question above, I would try two things (and they apply also for the use of model binder). Create an action filter around the method, and look at the `ActionExecutingContext.ActionArguments` to make sure binding took place correctly (see https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Filters/ActionExecutingContext.cs).

If binding is correctly happening you can debug into [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ControllerActionExecutor.cs#L120) and [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ControllerActionExecutor.cs#L43)

Hope this helps. And remember MVC6 is not trying to maintain 100% compatibility with MVC5 for every extensibility scenario. And we are morphing the recommended programming model where it makes sense. This is one of these examples.

**Comment by marcuslindblom** [comment]
This is an interesting topic for me and I would like to discuss this further but I don't want to pollute this thread. @yishaigalatzer showed some interest earlier so I'm hoping we can take this forward, with that said I think we can close this issue.
