### ISSUE TITLE
Error with complex Layouts and Sections.

### ISSUE THREAD

**Issue by AerisG222** [aspnet/Mvc#2179]
### Functional impact
The view fails with the following error:

InvalidOperationException: The following sections have been defined but have not been rendered: 'scripts_footer'.

### Minimal repro steps
I have tried to create a small sample that builds in complexity, from working views to a minimal test that fails.  This sample is available here:  [https://github.com/AerisG222/nested_layout_test/](https://github.com/AerisG222/nested_layout_test/).

The README on the repo contains steps showing basic layouts working, then the one that fails.

What appears to be causing the issue is where sections are defined across the layouts.  In the case that is failing, the layout page adds new sections that are referenced by the view, but are not in the parent layouts.  This seems to interfere with also being able to target the sections that are defined on the parent layout.

### Expected result
I was expecting all views to display resulting html w/o the exception

### Actual result
View fails with the exception from above

### Technical Details
Note that I am trying this from Linux, using a mono nightly build from 20150311212449, and the dev aspnet feed (with dnx).   here are version numbers in case this is helpful:

dnx --version
1.0.0-beta4-11271

dnvm list

Active Version              Runtime Location             Alias
------ -------              ------- --------             -----
  *    1.0.0-beta4-11271    mono    ~/.dnx/runtimes      default

mono --version
Mono JIT compiler version 4.1.0 (tarball Wed Mar 11 17:55:29 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

Thanks,
Mike

**Comment by danroth27** [comment]
@dougbu Please investigate what the impact of this issue is. Thx.
