### ISSUE TITLE
Review if a package description is required for these packages

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Mvc#2182]
```
Mvc\src\Microsoft.AspNet.Mvc.Common
```

**Comment by dougbu** [comment]
@Praburaj why?  this is a source package used only when building MVC projects.

**Comment by Praburaj** [comment]
I see. Feel free to close if it does not need a description. I filed bugs across the board for missing description.

**Comment by danroth27** [comment]
This package is part of the build system and does not need a description.
