### ISSUE TITLE
`ModelStateDictionary` contains garbage entries for `DateTimeOffset[]`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2192]
This is a regression from Beta3.   I have not tested with other collecition types.

1. create a model that is a `DateTimeOffset[]` or that contains a property of that array type
2. create an action of the form `public IActionResult Dates([FromForm(Name = "")] DateTimeOffset[] model)` or whatever works for your more complex type
3. create a matching action that invokes a view submitting to above action
4. run in the debugger
5. hit Submit in the browser
6. break on the first line of the action from step 2
7. observe ![garbage in modelstate](https://cloud.githubusercontent.com/assets/6431421/6698093/e9052cf2-ccb2-11e4-88f1-18ff90f0cbfb.png)
8. note that even though the parameter is fully-populated and the model is valid, `ModelState.IsValid` is `false`.
9. a similar scenario using Beta3 (and `[Bind(Prefix ="")]` instead of `[FromForm(Name = "")]`) does not have `Length` or similar entries in the `ModelState`.  `ModelState.IsValid` is `true` when using that version.

/cc @harshgMSFT

**Comment by danroth27** [comment]
@dougbu Is this just for `DateTimeOffset[]` or are other types affected as well?

**Comment by harshgMSFT** [comment]
Should be affecting anything and everything related to a collection.
