### ISSUE TITLE
Validation error is not thrown when a complex type property with required and from body attributes has null value

### ISSUE THREAD

**Issue by kirthik** [aspnet/Mvc#2219]
Assume a model like this
```
public class Customer
{
        public int Id {get; set;}
        [Required]
        [FromBody]
        public Address Address {get; set;}
}

public class Address
{
     public string Street {get; set;}
}
```
And I have an action
```
public IActionResult CreateCustomer(int id)
{
     var c = GetCustomer(id);
     TryUpdateModel(c)
     if (!ModelState.IsValid)
    { ....}
}
````

If I call `CreateCustomer` with empty json in the body, expectation is I will get a model state error saying `Address is required` but `ModelState` does not contain that error.

**Comment by danroth27** [comment]
@kirthik What happens if you don't use `[FromBody]` but just do a form post instead? What is the behavior on MVC 5 when using model binding?

**Comment by kirthik** [comment]
When I do a form post, `ModelState` shows validation error for `Address` property

**Comment by harshgMSFT** [comment]
Not Repro. the issue with @kirthik ran into was she was sending `{}` instead of an empty string ( no body) `{}` binds to a new object and not a null value. Hence the behavior.
