### ISSUE TITLE
Provide alternate ways to add version to a file path for cache busting.

### ISSUE THREAD

**Issue by sornaks** [aspnet/Mvc#2247]
Currently the only way to add version to a file path is query string. That is, `http://someurl.com/hello` becomes `http://someurl.com/hello?v=hashed_string`. But some popular proxies do not cache the query string at all. As a result, it is not cache busted : http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/

An alternate is to provide an option to modify the file name itself. I suggest it look something like: `<script src="js/something.js" asp-file-version="true" asp-file-version-method="filename" />`. Depending on `asp-file-version-method` we could modify the method appropriately.

**Comment by danroth27** [comment]
We can revisit this based on customer feedback.
