### ISSUE TITLE
Attribute routing throws ambiguous exception for base controller 

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#2248]
Consider the following 

```c#
[Route("base/[action]")]
    public class BaseController : Controller
    {
        public virtual void Action()
        {
        }
    }

    [Route("derived/[action]")]
    public class DerivedController : BaseController
    {
        public override void Action()
        {
        }
    }
```

When attempting to hit `base/Action` we get an ambiguous route exception.

**Comment by rynowak** [comment]
@harshgMSFT and I spent some time debugging this, the reason is that the entries for `DerivedController::Action` and `BaseController::Action` each end up defining the route `base/Action`.

**Comment by rynowak** [comment]
46db71cfceae350564135ecd2a810660e70a7c42
8a476b5
