### ISSUE TITLE
Consider renaming [AllowAnonymous]

### ISSUE THREAD

**Issue by blowdart** [aspnet/Mvc#2273]
The move to policy based Authorization allows developers to write authorization that depends on more than just an identity (for example they could add IP address into the mix). This move highlights that [AllowAnonymous] is badly named.

The attribute itself causes requests to bypass any and all Authorization calls that would normally protect access.

The attribute should be renamed to accurately reflect its function, however this is a breaking change.

**Comment by danroth27** [comment]
We discussed this and decided the AllowAnonymous name still works even for policy based authorization.
