### ISSUE TITLE
Types must follow folder hierarchy as namespace hierarchy

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#2275]
Based on discussion here: https://github.com/aspnet/Mvc/pull/2255

We have quite a couple of files in the Mvc repo that do not follow the folder-namespace convention. We should either move them to the folder-appropriate namespace or move them top level.

**Comment by Eilon** [comment]
@rynowak assigning to you because you're doing the namespace cleanup. I'm not super concerned about the exact details of this bug, so just associate it with your rename commit(s), and close this bug when you're done.

**Comment by rynowak** [comment]
Any preference on a pattern when files **can't** follow the convention?

Ex: Microsoft.AspNet.Mvc.ViewFeatures contains files in the following namespaces

- Microsoft.AspNet.Mvc
- Microsoft.AspNet.Mvc.Rendering
- Microsoft.AspNet.Mvc.ViewFeatures
- Microsoft.AspNet.Builder
- Microsoft.Extensions.Builder

**Comment by Eilon** [comment]
We often create fake-ish folders for those.

E.g. have a `src/Microsoft.AspNet.Mvc.ViewFeatures/Builder` folder that has the `Microsoft.AspNet.Builder` namespace in it, or similar.

If it's a very small number of types that are misplaced I would put them in the root of the project.

**Comment by Eilon** [comment]
The goal being to not have a giant mess. Small messes are acceptable.

**Comment by rynowak** [comment]
Ok great, that's what I've done in the existing code.

**Comment by rynowak** [comment]
dd952d8d70bab70f8fe336811b20d793931b80e1
a27616969316043822749302247d3b07e3029702
de3b33caf1a808b6e5c2636e60de4cbaf8f7ffea
8b1bd343ba56152d2a7e677cf041dc9d62b4033f
