### ISSUE TITLE
Remove dependency on Hosting

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#2286]
https://github.com/aspnet/Hosting/issues/172

**Comment by rynowak** [comment]
We can't do this until `IHttpContextAccessor` moves to interfaces. /cc @HaoK

**Comment by davidfowl** [comment]
Yep, that's why it references that bug :smile:

**Comment by davidfowl** [comment]
This is done

**Comment by rynowak** [comment]
c6a1af97b0fffaf04ddf04018e3689a54bbd33e8

**Comment by rynowak** [comment]
Note we now have a dependency on `M.F.Logging` that should be `M.F.Logging.Interfaces` @kichalla will have to clean this up as part of logging work, because we use some classes in logging currently.
