### ISSUE TITLE
Move JsonPatch to its own repo

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#2289]
Seems like it has nothing to do with MVC and should probably exist outside of this repository

**Comment by danroth27** [comment]
@eilon Can we put it in it's own JsonPatch repo?

**Comment by Eilon** [comment]
Yeah either way.

**Comment by Eilon** [comment]
Let's wait until Kevin finishes his current PR and then we can move this to a new repo.

**Comment by Eilon** [comment]
Repo created: https://github.com/aspnet/JsonPatch

**Comment by rynowak** [comment]
f4c5e31ec1ea2fb859a149a6a97a1d0757da53ab
