### ISSUE TITLE
Can we make AntiForgeryTokenFieldName configurable?

### ISSUE THREAD

**Issue by stanislavromanov** [aspnet/Mvc#2290]
Right now AntiForgeryTokenFieldName is set as `private const` as `__RequestVerificationToken`. What if someone wants to change the cookie name to something else?

Can we make it possible to set it as option?

Line in question: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/AntiForgery/AntiForgeryOptions.cs#L14

**Comment by davidfowl** [comment]
Why?

**Comment by davidfowl** [comment]
Wait the cookie name or the form field name?

**Comment by davidfowl** [comment]
Spoke too soon. Seems like everything is overridable and that's just the default value.

**Comment by stanislavromanov** [comment]
@davidfowl 

I would like to edit them both. I see that it's not possible unless I clone repo and change it in the code itself. Maybe I'm wrong and you can configure it?

**Comment by pranavkm** [comment]
Changing `AntiForgeryOptions.FormFieldName` in startup should suffice:

```C#
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.Configure<AntiForgeryOptions>(options =>
    {
        options.FormFieldName = "my-field-name";
    });
}
```

**Comment by stanislavromanov** [comment]
@pranavkm Thank you very much. What about the cookie name?

**Comment by davidfowl** [comment]
CookieName is a property on the same object....
