### ISSUE TITLE
[Script+Link TagHelpers] asp-file-version makes the src file locked

### ISSUE THREAD

**Issue by ianhong** [aspnet/Mvc#2295]
For example, in the following codes, asp-file-version="true" locks down ~/js/Alert.js. So, users cannot modify Alert.js without killing the host process like IIS. 

This is because Alert.js was not released properly once asp-file-version is set to true. @sornaks knows how to fix this. 

With this bug, asp-file-version is not useful since users should restart IIS every time to release the file. 

Thanks,
Youngjune 
```html
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
<html>
<body>
    <script src="~/foo.js" asp-fallback-test="false" asp-fallback-src="~/js/Alert.js" asp-file-version="true">
    </script>
</body>
</html>
```

**Comment by sornaks** [comment]
Checked in - https://github.com/aspnet/Mvc/commit/6e9533ce9cf48536c27a09bf61fd48b113c2107b
