### ISSUE TITLE
JsonPatch: Test operation does not validate equality.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2299]
Providing patch: `{ "op": "test", "path": "Favorite/FirstName", "value": "Taylor1" }` to the object:
```json
{
    "Favorite": {
        "FirstName": "Taylor"
    }
}
```

Results in a `success` test when it should not.

In C# form:
```C#
public class Users
{
    public User Favorite { get; set; }
}

public class User
{
    public string FirstName { get; set; }
}
```

**Comment by kirthik** [comment]
`Test` operation is not supported yet. For reference - https://github.com/aspnet/Mvc/issues/2218
