### ISSUE TITLE
Html.BeginForm improvements

### ISSUE THREAD

**Issue by chaoaretasty** [aspnet/Mvc#2301]
Not sure if this has been addressed or not in MVC6 but a long standing annoyance for me is the inability to keep the URL generating behaviour of Html.BeingForm() if you want to provide custom HTML attributes.

This is actually an annoyance on several elements where you can only specify attributes on some of the longer overloads but BeginForm is particularly bad considering the use cases.

There needs to be a way (on Forms in particular but ideally helpers in general) to provide attributes and keep otherwise default or common use case behaviour.

The biggest problem here is likely to be overload resolution. As a strawman proposal I suggest adding an IHtmlAttribute which derives from IDictionary<string, object> and a .ToHtmlAttribute extension method that can turn a dictionary or object into an IHtmlAttribute and can allow writing code such as Html.BeginForm(new {data_foo="bar"}.ToHtmlAttribute()).

**Comment by dougbu** [comment]
> needs to be a way ... to provide attributes and keep otherwise default or common use case behaviour

@chaoaretasty you have two options
1) pass `null` for parameters you do not need when invoking the shortest HTML helper overload with the parameters you do need
2) use the MVC tag helpers e.g. `<input asp-for="expression" data_foo="bar" />`

we may be missing some overloads that would not create ambiguities.  please let us know if you notice any as you use MVC 6.

`ToHtmlAttribute()` would allow more overloads containing `htmlAttributes` without ambiguity.  but it seems like overkill and could confuse users e.g. "what is the difference between passing an anonymous `object` to this overload and an `IHtmlAttribute` to that?" or "can `IHtmlAttribute` handle multiple attributes?".

**Comment by chaoaretasty** [comment]
Thanks for the reply @dougbu. As mentioned this is giving feedback on fixing an issue from MVC5 so it is possible that these have been resolved in MVC6.

1) Was my initial attempt at fixing this but unfortunately it gives a different behaviour. BeginForm() gives a form element using `HttpContext.Request.RawUrl` which no other overload uses. By passing nulls it gives an action attribute that might not match the current URL in certain complex routing/view scenarios. It also won't include things such as querystrings. I did end up managing to do this via passing the action attribute in as well as my other attributes.

2) This looks like it could work for most elements but BeginForm also does some extra work setting up formcontexts and client validation.

The `ToHtmlAttribute()` was a strawman proposal and based on how we can pass `object` or `RouteValueDictionary` and I can definitely see some issues with it, just trying to start a conversation on a way to provide attributes to a helper in situations where we would otherwise want relatively basic MVC behaviour. I find most of the times I use the complex overloads it's passing `null` a lot just to get to the attributes and it seemed a possible area to clean this up.

**Comment by dougbu** [comment]
> `BeginForm()` gives a form element using `HttpContext.Request.RawUrl` which no other overload uses

hmm, good point.  in MVC 6 we use the raw request URL only when _all_ parameters are `null`.  that special case is only a slight extension of the MVC 5  behaviour.

however we could remove `htmlAttributes` from the condition to better support your scenario.  that would break compatibility slightly but might be justified here; without the history, looks a bit odd to include `htmlAttributes` in the URL calculation.

btw I believe no other HTML helper has a similar "only if every argument is `null`" special case.

**Comment by chaoaretasty** [comment]
That would sort the problem. In terms of making a breaking change anyone who has put all nulls in here for this purpose will:

* have relatively simple routing and been in the situation where default routing gives the `RawUrl`
* have come across this problem and had to find a work around for it where they are no longer putting null everywhere
* have complex routing where the default routing gives a different URL to the current one and this luckily happens to match the URL they did want

So I think it would be a relatively safe change to make anyway when considering the expected behaviour would be to act like the no arguments method.

**Comment by dougbu** [comment]
9eb87d4

**Comment by dougbu** [comment]
thanks to @henkmollema

**Comment by chaoaretasty** [comment]
Thanks
