### ISSUE TITLE
Precompilation + TagHelpers in different project do not recompile changed TagHelpers.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2305]
If you have `TagHelper`s in another project and you're `@addTagHelper`ing them into your own, if using precompilation changes are not reflected in the runtime code.

**Repro:**
`TagHelper` in another project:
```C#
public class FooTagHelper : TagHelper
{
    public string Bar { get; set; }
}
```

```HTML
<foo bar="true" />
```

Change `FooTagHelper`'s `Bar` property to be a `bool`. Razor page doesn't pick up on the modified `TagHelper` even when closing/reopening file. An error occurs. In the case that the tooling is smart enough to not show the error and let you build, runtime fails.

**Comment by pranavkm** [comment]
Addressed as part of https://github.com/aspnet/Mvc/commit/2e32ffc004be74a0a13057349641141239a610ea
