### ISSUE TITLE
How can I create a catch-all route?

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#2308]
I'm wanting to use a client-side router with React to build my application.

I've got this code but it isn't doing what I want it to:

```
app.UseMvc(routes =>
{
	routes.MapRoute(
		name: "catch",
		template: "{*url}",
		defaults: new { controller = "Home", action = "Index" });
});
```

This seems to be in line with what I know about MVC 5 and other answers on StackOverflow and other forums seem to agree with this approach. Is there something I am doing wrong, or is this no longer possible?

**Comment by rynowak** [comment]
@tuespetre by catch-all route, do you mean that you want every url coming into your app to be routed to `Home::Index`? I'd expect what you have there to work fine. 

Can you link to a more complete sample or else post your complete startup and controller code here so we can get to the bottom of this?

**Comment by tuespetre** [comment]
After checking some things, I found that the `Route` attributes on the `HomeController` and its `Index` action were causing the problem. They were both set to `""`. Since the action is intended to be a catch-all, I can remove the attributes and be fine with that. I did notice that having attributes on one or the other (controller or action) also causes the issue. I don't know if this is intended or not.

So now I personally have a solution, I'll leave it up to you to close this issue or whatever you want to do.

Thanks!

**Comment by rynowak** [comment]
@tuespetre - Glad you found a solution.

Routing is either one or the other. If you use attribute routes, then those actions are not reachable via conventional routes defined in startup and vice-versa.

If you did it like this instead:

```
public class HomeController
{
    [Route("{*url}")]
    public IActionResult Index(string url)
    {
    }
}
```

It would have the same effect and you don't need the route in startup.

**Comment by tuespetre** [comment]
Wonderful, I like that much better. Much cleaner startup. I really appreciate the simplified routing system altogether. Thanks for your help.

**Comment by andycmaj** [comment]
note that this will allow your app to serve ANY url anyone anywhere makes to your server, opening you up to DoS attacks among other things...

**Comment by christo8989** [comment]
Here's another answer.

```
routes.MapSpaFallbackRoute(
    name: "spa-fallback",
    defaults: new { controller = "Home", action = "Index" });
```
