### ISSUE TITLE
Unable to use an incomplete `CacheProfile`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2310]
Though `ResponseCacheFilter` has settable properties intended (apparently) to override and supplement the `CacheProfile` passed to its constructor, the constructor contains checks that prevent obvious scenarios.  For example:
``` c#
var partialCacheProfile = new CacheProfile
{
  Location = ResponseCacheLocation.Client,
};
options.Filters.Add(new ResponseCacheFilter(partialCacheProfile) { Duration = 24 });
```
will `throw` on the last line because the intentionally-incomplete `CacheProfile` is checked prior to the `Duration` setting.

The `ResponseCacheAttribute` works around this issue; it creates a complete `CacheProfile` and passes that to the `ResponseCacheFilter` constructor. So issues are specific to scenarios where users set up a default `ResponseCacheFilter` globally.

Suggest postponing the check until `OnActionExecuting()` is called (my preference), removing most `ResponseCacheFilter` setters, or correcting the following comment.
``` c#
// Duration MUST be set (either in the cache profile or in the attribute) unless NoStore is true.
```

**Comment by femiot** [comment]
@danroth27 How do sign up for "up-for-grabs" items should volunteer to contribute to fixing the issue?

**Comment by rynowak** [comment]
70b56f157cc225b0c3668263189404068ad60eb9
