### ISSUE TITLE
Change reference from Microsoft.Framework.Logging to Microsoft.Framework.Logging.Interfaces

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2315]
Right now we depend directly on `Microsoft.Framework.Logging` in `Mvc.Core`. After @kichalla is done with logging updates we should be able to change to `Microsoft.Framework.Logging.Interfaces`

**Comment by kichalla** [comment]
Commit: 20daab2fb59c57f9702fdd1a3656298330e435cf
