### ISSUE TITLE
Type excluded from validation still honors the IValidatableObject implementation on the type.

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#2316]
For the following setup:
```c#
public class Customer
{
    public int Id { get; set; }

    [Required]
    [MaxLength(5)]
    public string Name { get; set; }

    public Address Address { get; set; }
}
public class Address : IValidatableObject
{
    public string City { get; set; }

    public string State { get; set; }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        return new[] { new ValidationResult("Something went wrong, bro!") };
    }
}
//-------------------------------
public class CustomersController : Controller
{
    public IActionResult Create(Customer customer)
    {
        if (!ModelState.IsValid)
        {
            return HttpBadRequest(ModelState);
        }

        return Json(customer);
    }
}
//------------------------------
services.ConfigureMvc(options =>
{
    options.ValidationExcludeFilters.Add(typeof(Address));
});
```

Following is the current behavior:
**Request**
```
POST http://localhost:24628/Customers/Create HTTP/1.1
User-Agent: Fiddler
Content-Type: application/x-www-form-urlencoded
Host: localhost:24628
Content-Length: 54

Id=100&Name=John&Address.City=Redmond&Address.State=WA
```

**Response**
```
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/10.0
X-SourceFiles: =?UTF-8?B?RDpcVmVyaWZ5TW9kZWxWYWxpZGF0aW9uVW5pZmljYXRpb25cU2FtcGxlV2ViQXBwXHNyY1xTYW1wbGVXZWJBcHBcd3d3cm9vdFxDdXN0b21lcnNcQ3JlYXRl?=
X-Powered-By: ASP.NET
Date: Wed, 01 Apr 2015 22:09:41 GMT
Content-Length: 42

{"Address":["Something went wrong, bro!"]}
```

**Expected**: Since the type `Address` was excluded from validation, we shouldn't ideally honor the `IValidatableObject` implementation?

**Comment by kichalla** [comment]
This also happens with a `ValidationAttribute` implementation. Example type:

```c#
public class Customer
{
    public int Id { get; set; }

    [Required]
    [MaxLength(5)]
    public string Name { get; set; }

    [AddressValidator]
    public Address Address { get; set; }
}

public class AddressValidator : ValidationAttribute
{
    protected override ValidationResult IsValid(object value, ValidationContext validationContext)
    {
        return new ValidationResult("Something went wrong, bro!");
    }
}
```

**Comment by Eilon** [comment]
A slightly unusual scenario because why would the type even implement `IValidatableObject` if it wasn't going to be validated. Nevertheless, a valid bug.

**Comment by kichalla** [comment]
Right, the scenario was more from point that the type having the validation is not owned by the user using in his application.

**Comment by Eilon** [comment]
Yeah, it would just seem odd that someone would bother implementing validation logic on something that shouldn't be validated in a scenario (even though the two types are owned by different people). It's certainly *possible*, but seems odd.

**Comment by Eilon** [comment]
@rynowak please check this out, bro.

**Comment by rynowak** [comment]
Investigated this, clearing triage with results.

*Really*, it's clear from looking at the code that the intent of the implementation is to exclude the **properties** of the type from validation.

Ex:
```
public class MyModel
{
    [Required]
    [MyValidationAttribute(Message = "Validator1")]
    public MySpecialType Special { get; set; }
}

[MyValidationAttribute(Message = "Validator2")]
public class MySpecialType
{
    [MyValidationAttribute(Message = "Validator3")]
    public int Id { get; set; }
}
```

If you exclude `MySpecialType` from validation, then the validators on `MyModel.Special` and `MyspecialType` will run, and the validators on `MySpecialType.Id` will never run. We ask the validation system for validators for `MyModel.Special` and 3 will be returned (1 instance of `Required` and 2 instances of `MyValidationAttribute`.

Like was mentioned above, it's a wierd scenario. Asking for validators for a property gives you validators on the property itself, and on the property's type, and I don't think we want to change that. There's nothing unexpected going on in the code, it's doing what it's intended to do.

Recommend won't fix and updating the docs to reflect the real behavior.

**Comment by danroth27** [comment]
@rynowak Is there any particular reason not to change this behavior? My intuition is that if I exclude a type from validation then none of the validators on the type should ever get run.

**Comment by rynowak** [comment]
> @rynowak Is there any particular reason not to change this behavior?

There's no reason we can't/shouldn't as long as we don't impact more-primary scenarios. 

Is the intent to run validators on the **property** but *not the type* or to skip **all** validation?

If the former, it w ill require some extra plumbing that we don't currently have, as we currently look for all validators on both the property and type all the time. If the latter, it's very easy to fix.

**Comment by dougbu** [comment]
@rynowak are you talking about a scenario such as:
``` c#
  public class Model
  {
    [Required]
    public IFormFile File { get; set; }
  }
```
?

If so, I suggest applying the `RequiredAttribute` makes sense even though the `IFormFile` type is excluded from validation. Realize this is a bit more difficult but, fortunately, we already maintain the property and type attributes separately. So we're well on the way to maintaining the validators separately :smiling_imp:

**Comment by Eilon** [comment]
@rynowak it's the former - respecting just the validation on the property declaration itself. That would seem to be the most *logical* approach, even if it's perhaps difficult to implement. (I'm not strongly suggesting we change anything; I'm merely arguing for what I think is the most logical/correct.)

**Comment by rynowak** [comment]
> (I'm not strongly suggesting we change anything; I'm merely arguing for what I think is the most logical/correct.)

It comes back to an earlier discussion we had. An exclude filter (in it's current form), just basically serves to stop traversal of the model graph, for things that have properties but aren't interesting for validation.

If you're using an exclude filter for a type that you attached validators to, then that's a bit strange.

**Comment by Eilon** [comment]
Maybe it's just the wrong feature then... let's discuss tomorrow.

**Comment by danroth27** [comment]
> If you're using an exclude filter for a type that you attached validators to, then that's a bit strange.

What about Required? What about a case where I normally don't care about validating a particular type, but in one exceptional case I do? Or what if I don't like the validation logic on a type I don't control and I want to override it for just one particular case?

**Comment by rynowak** [comment]
`[Required]` only applies to properties. Using `[Required]` on a property with an excluded type will perform validation.

**Comment by danroth27** [comment]
After having discussed this at length let's just close this issue and leave the property as is. The property was added for a very specific use case and is not worth generalizing. The semantics of the property can be clarified in the API ref docs.
