### ISSUE TITLE
MVC6 Basic Authentication - Suggestion.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#2323]
I know in MVC5 we had a lot of auth mechanisms (oauth, ad, etc) but no Basic Auth. While it's 'kinda' trivial to write one, wouldn't it be a good addition to mvc ?

**Comment by Eilon** [comment]
MVC itself has no authentication features - they are implemented as common middleware. Please file an issue here: https://github.com/aspnet/Security/issues

**Comment by Bartmax** [comment]
Sure thanks.
