### ISSUE TITLE
Private Wall (password protected site) - Suggestion

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#2324]
It happened plenty of time before:

I create a website, with authentication, and want to public with a password wall. much like an .htaccess works.

you create a file, set up a password, and you receive a Basic Auth to see the site that doesn't mess up with the user authentication/identity of the site.

Since now we have owin, DI, and project.json, I think this would be a great addon, specially for staging sites on azure. I can confidently upload a staging-site with a wall protected password and having it online for 'testing' without concerns about someone hitting that url and without messing with complex configuration, especially when your ISP does not give you static IPs.

Maybe as a middleware?

**Comment by Eilon** [comment]
htaccess is a not a recommended practice with system such as MVC because there is no relationship between URLs that are served and the layout of the files on disk. As such, where would you place the `.htaccess` file? At most there would be one at the root of the app, but then that's not too different from just enabling authentication middleware to block access to the site.

**Comment by Bartmax** [comment]
What I meant was:
I have a site that I can log in with user A
I want to publish the site but cannot let user even see the site if they don't type a password.

If I enter the password, I enter as unauthenticated, than I can login and logout as user A (using maybe identity)

Enabling an authentication middleware that doesn't gets in the way of the application authentication is exactly what I was looking for. My suggestion is to give an auth middleware out of the box as a nuget package, same as UseWelcomePage(), like UsePasswordedWall("password").

**Comment by Eilon** [comment]
Hmm on the face of it this sounds to me like a more esoteric scenario. I would suggest in the meantime writing a version of this and publishing a NuGet package to do this to gauge interest and see if others have feedback on it.

**Comment by Bartmax** [comment]
Sounds good, I think with azure staging this is coming with more interest over time. I'll try to write one myself in my own repo and let you guys see if you want to get included or not.

**Comment by Eilon** [comment]
Yeah sounds good! BTW please continue the discussion in the aspnet/Security repo once you're ready.
