### ISSUE TITLE
JsonViewComponentResult should use JsonFormatter from output formatters collection

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#2325]
Seems like a difference in behavior between `JsonResult` and `JsonViewComponentResult`:

* https://github.com/aspnet/Mvc/blob/df4b92b1c12dcea122a730b618b33a0b39496561/src/Microsoft.AspNet.Mvc.Core/ActionResults/JsonResult.cs#L114-L121

* https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ViewComponents/JsonViewComponentResult.cs#L68-L69

We should use the user-configured - the formatter in `MvcOptions`.

**Comment by pranavkm** [comment]
cc @rynowak

**Comment by rynowak** [comment]
We opted when building this class to just make it as simple as possible. My suggestion is to just remove it, it's not really clear that there's a good usage scenario here. 

If you want to just emit some JSON, using `ContentViewComponentResult` is pretty simple, and doesn't require us to bring in formatters.

**Comment by ianhong** [comment]
@Eilon decided not to fix this issue now instead of removing JsonViewComponentResult since this is for @DamianEdwards's request.
I'll  remove the milestone label for triage for the future.

**Comment by danroth27** [comment]
The current behavior is fine. The settings used for putting JSON on the wire really are independent from the JSON returned by a View Component for embedding in a view.
