### ISSUE TITLE
We should remove TypeExtensions

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2335]
We should be using `GetTypeInfo` / `TypeInfo` instead of utilizing `TypeExtensions` that make the call for us. This way we're aligning with a more CoreCLR compatible way of writing code :smile:

**Comment by dougbu** [comment]
@triage this is a dupe of #105.

TL;DR
`TypeExtensions` includes a few helper methods not available directly from `TypeInfo` e.g. `IsCompatibleWith()` and `ExtractGenericInterface()`.  for a few other cases, it's probably just as good to use the provided `System.Reflection.Extensions` and `System.Reflection.TypeExtensions` packages.  the remainder are covered by #105.

**Comment by danroth27** [comment]
Agree this is a dup of #105
