### ISSUE TITLE
Shared model metadata across client and server side validations

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#2340]
So, currently in MVC5 localizing display name for specific property can easily be done by overriding ```DataAnnotationsModelMetadataProvider``` and setting it's ```DisplayName``` property. And at first it works great, you get localized labels, client side validation and such without having to use display attribute on each property. But it stops working then server side validation comes into play. Passing incorrect model to the controller results in model state being invalid, but it's errors are no longer being localized completely. Which results in errors like this "Se 'TextPropertyField' requiere campo!", being send back to the user.

The only solution I found to this problem is re-setting display name in each ```DataAnnotationsModelValidator```, which results in a lot of duplicate code.

Are these kind of cases being dealt with in upcoming release?

**Comment by dougbu** [comment]
@harshgMSFT suggest checking if this bug reproduces with a middleware in place that sets the current culture.  likely the behaviour @Muchiachio is seeing comes from the fact we haven't got such a thing yet.

**Comment by Muchiachio** [comment]
Sorry if I was not clear enough, but this behavior happens in the current MVC versions like (Microsoft.AspNet.Mvc 5.2.3), I didn't check MVC6 beta releases. I'm just wondering if this could be fixed with upcoming "MVC6" release.

**Comment by harshgMSFT** [comment]
@Muchiachio 
I was trying out MVC 5.0 scenario, by overriding `DataAnnotationsModelMetadataProvider` and setting it's `DisplayName` property. The error in the model state uses the name specified by the DisplayName property. 
Here is my action
```c#
     public string Action(Person p)
     {
            var entry = ModelState.Single();
            return entry.Value.Errors.Single().ErrorMessage;
     }

    public class Person
    {
        [Required]
        public string Name { get; set; }
    }
```
In my data annotations override I had 
```c#
 var metadata = base.CreateMetadata(attributes, containerType, modelAccessor, modelType, propertyName);

metadata.DisplayName = "XYZ" + metadata.DisplayName;
```
And the error string returned is `The XYZ field is required.` 

Were you trying out something else where it did not work?


Please note that we still need to do some work to get this working in MVC 6.0 and we will be doing this in the current milestone, but just wanted to understand your mvc 5.0 scenario.

**Comment by Muchiachio** [comment]
Hi @harshgMSFT , you can recreate that by using my [MVC repository](https://github.com/NonFactors/MVC.Template), because I didn't fix it up until now.
1. Build the project and run ```update-database``` command on data project.
2. Run the project and login using admin/Admin123? credentials.
2. Go to ```http://localhost:19175/domain/lt/administration/roles/create```.
3. Turn off javascript or otherwise force a post to create action without filling in the "Pavadinimas" field.

You will see that it returns "Laukas 'Name' yra privalomas." even though I have overriden ```DataAnnotationsModelMetadataProvider``` class in ```DisplayNameMetadataProvider``` and set DisplayName to "Pavadinimas".

You can look at various ```DataAnnotationsModelValidator<TAttribute>``` implementations over [here](https://github.com/NonFactors/MVC.Template/tree/develop/src/MvcTemplate.Components/Mvc/Adapters) which suffers from the same problem as required adapter. It returns "Laukas 'Pavadinimas' yra privalomas." in generated text box for client side validation, but model state still contains  "Laukas 'Name' yra privalomas.".

**Comment by harshgMSFT** [comment]
@Muchiachio thanks for sharing your project, there seem to be some issues running your project on vs 2015 (which is what i have on my dev box), would really appreciate if you can create a very simple repro which demonstrates the problem.

**Comment by Muchiachio** [comment]
[Here](https://github.com/Muchiachio/DisplayNameBug) ya go, created it using VS2015 RC ;o

**Comment by harshgMSFT** [comment]
Thanks a ton for providing a simplified repro. The problem in your case is pretty simple, you are overriding `GetMetadataForProperty` (which seems to be the right place, but isnt). The framework actually calls `GetMetadataForType` while doing action paramter binding, which results in your property not being localized. You need to instead override `CreateMetadata` like so

```c#
protected override ModelMetadata CreateMetadata(IEnumerable<Attribute> attributes, Type containerType, Func<object> modelAccessor, Type modelType, string propertyName)
        {
            var metadata = base.GetMetadataForProperty(modelAccessor, containerType, propertyName);
            metadata.DisplayName = "Pavadinimas";

            return metadata;
        }
```

**Comment by harshgMSFT** [comment]
BTW inorder to get you going for a similar scenario for MVC6 , you can try doing the following.
```c#
public class LocalizedModelMetadata : DefaultModelMetadata
{
    public LocalizedModelMetadata(IModelMetadataProvider provider, ICompositeMetadataDetailsProvider detailsProvider, DefaultMetadataDetails details) : base(provider, detailsProvider, details)
    {
    }

    public override string DisplayName
    {
        get
        {
            /// Do your stuff here.
        }
    }
}

public class LocalizedModelMetadataProvider : DefaultModelMetadataProvider
{
    public LocalizedModelMetadataProvider(ICompositeMetadataDetailsProvider detailsProvider): base(detailsProvider)
    {
    }

    protected override ModelMetadata CreateModelMetadata(DefaultMetadataDetails entry)
    {
        return new LocalizedModelMetadata(this, DetailsProvider, entry);
    }
}
```

and then register your metadata provider in startup.cs like so:

```c#
public void ConfigureServices(IServiceCollection services)
{
    //services
    services.AddMvc();
    services.AddTransient<IModelMetadataProvider, LocalizedModelMetadataProvider>();
}
```

**Comment by Muchiachio** [comment]
Thanks for the MVC6 example.
I guess this issue can be closed? Unless you are going to make some adjustments for MVC6?

**Comment by harshgMSFT** [comment]
67d0bf880a2c584c08aa5fd82c94a0408cf8647c
