### ISSUE TITLE
AuthorizeAttribute should use 401 instead of 400

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Mvc#2341]
Currently, when a request fails authorization a 400 status code is returned. Shouldn't this be a 401 instead to differentiate from requests that simpye have an incorrect model?

**Comment by danroth27** [comment]
@borgdylan I'm not seeing the behavior you describe - I see 401's being returned. Can you try this out with our latest bits from the dev branch and send us a simple project that reproduces the issue?

**Comment by borgdylan** [comment]
This is happening in  a complex case with code that I cannot disclose. In some way the 401 is being changed/redirected by the cookie middleware.

**Comment by borgdylan** [comment]
I get:
```
Unable to locate Microsoft.AspNet.RequestContainer >= 1.0.0-beta4-11232
```
when trying to replace all the packages with the latest ones.

**Comment by borgdylan** [comment]
The culprit is one of the security packages which still requires teh request container package which as as I know was nuked some time ago.
```
 Microsoft.AspNet.RequestContainer 1.0.0-beta4-11232
    -> Microsoft.AspNet.Security 1.0.0-beta4-11758
```

**Comment by borgdylan** [comment]
My bad, I was referencing old packages. Now, I get the 401 as expected so that my javascript displays the login view.
