### ISSUE TITLE
Data corrupt when submit form

### ISSUE THREAD

**Issue by Boglen** [aspnet/Mvc#2364]
I'm have simple entity:

    public class PostModel
    {
        [Key]
        public int Id { get; set; }

        public string Caption { get; set; }

        public string Body { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime? CreateDate { get; set; }

        public ICollection<TagModel> Tags { get; set; }
    }

... and controller

    [Authorize]
    public class PostController : Controller
    {
        private readonly SiteDbContext db;
        public PostController(SiteDbContext context)
        {
            db = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        // GET: /Post/Edit/1
        [HttpGet]
        public IActionResult Edit(int PostId)
        {
            var post = db.Posts.Any(p => p.Id == PostId) ? db.Posts.First(p => p.Id == PostId) : new PostModel();

            return View(post);
        }

        // POST: /Post/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PostModel model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = Microsoft.Data.Entity.EntityState.Modified;

                await db.SaveChangesAsync();

                return RedirectToAction("Edit", new { PostId = model.Id });
            }

            return View(model);
        }

    }

When I request a page by route /post/edit?postid=5, the correct form is generated.
When I confirm the form field Id receives an incorrect value (model.Id == 2)
But if I modify action to
        public async Task<IActionResult> Edit([FromForm]PostModel model)
all work fine

**Comment by dougbu** [comment]
please add details of your configured template routes and the view.  in addition, is `model.Id == 2` at a breakpoint in the action (versus when displayed in the view, which would imply the `ModelState` contains unexpected values)?

separately we've fixed a few bugs in model binding lately.  which exact version of MVC are you using  i.e. which DNX feed is configured and what does your project.json contain?

**Comment by Boglen** [comment]
![formidcorrupt](https://cloud.githubusercontent.com/assets/10594440/7075299/48bd515a-df1a-11e4-8489-6dafdfeff3fb.JPG)

**Comment by Boglen** [comment]
project.json 
    "dependencies": {
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta5-*",
        "Microsoft.AspNet.Hosting": "1.0.0-beta5-*",
        "Microsoft.AspNet.Mvc": "6.0.0-beta5-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta5-*",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta5-*",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta5-*",
        "Microsoft.AspNet.Identity": "3.0.0-beta5-*",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta5-*",
        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta5-*",
        "Microsoft.AspNet.Session": "1.0.0-beta5-*",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta5-*",
        "EntityFramework.SqlServer": "7.0.0-beta5-*",
        "EntityFramework.Commands": "7.0.0-beta5-*",
        "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta5-*",
        "Microsoft.Framework.OptionsModel": "1.0.0-beta5-*",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta5-*",
        "Microsoft.Framework.Cache.Distributed": "1.0.0-beta4-*",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta5-*"
    }

Microsoft.AspNet.Mvc version 6.0.0-beta5-13474
dnx-clr-win-x86.1.0.0-beta5-11427

VS2015 CTP6, Windows 10 Pro 10049, Chrome 41.0.2272.118.

Routes:
               .UseMvc(routes =>
               {
                   routes.MapRoute(
                        name: "default",
                        template: "{controller}/{action}/{id?}",
                        defaults: new { controller = "Page", action = "Index", id = 2 },
                        constraints: new { id = @"\d+" }
                        );

                   routes.MapRoute(
                         name: "defaultWithoutAction",
                         template: "{controller}/{id?}",
                         defaults: new { action = "Index" },
                         constraints: new { id = @"\d+" }
                       );
               });

**Comment by kichalla** [comment]
The value of `id` is available in both the request body and the route named `default` (the default value for `id` there is `2`)...in this case looks like the one on the route is being used.

In case of `FromForm` you are explicitly asking to only bound data from the request body form and hence you are seeing the desired behavior.

**Comment by Boglen** [comment]
Now understood . thank a lot!
