### ISSUE TITLE
When not passing a model to the view an instance of the view expecting viewmodel is not created.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#2371]
Maybe this is by design.

in a view having:
```
@model AccountLoginViewModel
```

and controller 
```
 public IActionResult Login()
        {
            return View();
        }
```

and AccountLoginViewModel
```
    public class AccountLoginViewModel
    {
        public bool RememberMe { get; set; } = true;
    }
``` 

The RememberMe option is set to false. I'm not sure what are the internal workings but absolutely mvc is not creating an instance of AccountViewModel. (same happends with code inside a constructor)

obviously this controller code does set the RememberMe as true:

```
 public IActionResult Login()
        {
            ViewData.Model = new AccountLoginViewModel();
            return View();
        }
```

**Comment by pranavkm** [comment]
This might be a gap in how we create `ViewData` instances and get to the model. For the time being, could you pass in your model using property on `ViewResult`: 
`return View(model: new AccountLoginViewModel());`?

**Comment by dougbu** [comment]
@pranavkm there's no gap.  views execute with a `null` model unless the action sets `ViewData.Model`, the action passes a non-`null` value to `View()`, or model binding succeeds (at least partially).  since none of those are true for the original `Login()` action, the view behaves as expected.

**Comment by Bartmax** [comment]
As I suspected this is by design then. Closing.
