### ISSUE TITLE
JsonSerializerSettings on input and output JSON formatters

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Mvc#2388]
Hi

I noticed that the input and output JSON formatters independently create serializer settings.

On the input formatter you are explicitly creating a JsonContractResolver - https://github.com/aspnet/Mvc/blob/5bb69e495e9a7f62ac42bf77e1e8bcbb04af73cf/src/Microsoft.AspNet.Mvc.Core/Formatters/JsonInputFormatter.cs#L40 - while the output formatter is using the default contract resolver.

The problem with doing this is each contract resolver will independently resolve each type, which involves a lot of reflection, possibly some IL gen and dynamic compilation, and will increased memory used.

My question is this necessary? If not, you should avoid it for performance reasons.

**Comment by Eilon** [comment]
@JamesNK we currently have this behavior because the input and output formatters are designed to have separate behaviors. For example, in MVC 6 by default for inputs there is extra behavior added to properties with the `[Required]` attribute to alter its behavior, but for outputs there is no such behavior.

Is there any way to have the contract resolvers share their caches? If it's just internal caching then it seems like maybe they could share a cache because there should never be any conflicts - cached reflection data reflects truths and is thus immutable.

Related to this, is it possible to compose contract resolvers? Currently it seems like the behavior is that you can have only one and the way to compose it is to "wrap" the current one with a custom one. Is that the recommendation for customers? Or is there a way to have a "pipeline" of contract resolvers so that they can compose independently?

**Comment by JamesNK** [comment]
> Is there any way to have the contract resolvers share their caches?

Not right now. When I created the resolver class I imagined the contract resolver would be the cache. I could easily make it so that all reflection and IL generation for getting/setting/creating values is cached in a global static cache. I'm worried that there would then be no way to reclaim that memory. XmlSerializer was fairly infamous for creating unrecoverable memory leaks.

> Related to this, is it possible to compose contract resolvers?

I can't think of a way. This wasn't something I thought about when designing the class. If you have a resolver modifying the contracts returned from another resolver, because those contracts are cached then you will be modifying them for all users of that resolver, regardless of whether it is wrapped. I assume you want to support allowing the user to define their own resolver and have it live along side yours?

**Comment by kichalla** [comment]
> I assume you want to support allowing the user to define their own resolver and have it live along side yours?

Yes right, an example scenario: A user would like to support camel casing of properties(which requires using camel case contract resolver) + our own resolver.

**Comment by JamesNK** [comment]
Hmmm, maybe a way to compose resolvers would be adding some logic to clone the contracts. The wrapping resolver could then modify what it needs, cache it, and then return it as needed.

Its would look completely different from DefaultContractResolver however. All it would have is the ResolveContract method and you would have to search the hierarchy of contracts that are returned, and modify them. And I believe other contracts can be resolved when the initial contract, sometimes being cached to internal fields for performance.

That probably won't work.

**Comment by Eilon** [comment]
Re: Sharing caches

Yeah I agree that sharing caches has memory reclamation problems... don't know a great answer to this. Of course, instead of sharing the cache "dictionary" they can potentially share the cache *entries*, so of resolver 1 used A, B, C, D, E, and resolver 2 used A, B, X, Y, Z the entries (and cost) for A and B could be shared between both resolvers, and the non-overlapping items could be cleared out. Just a thought.

**Comment by JamesNK** [comment]
The simple answer to avoid duplicating the reflection cost for types is to use the same custom contract resolver for both the input and output formatter by default.

**Comment by danroth27** [comment]
We should consider:
- Do we really need a contract resolver at all? Can we make a change to use the RequiredAttribute without any wire semantic?
- If we decide we do want the contract resolver should we use the same resolver by default for input and output?

**Comment by rynowak** [comment]
We could really just make the settings part of MVC options if we want to. This is one of the more frequently touched knobs and that's about as front and centre as we can put it.

**Comment by JamesNK** [comment]
Where are the MVC options? I haven't touched MVC6 yet.

> Do we really need a contract resolver at all? Can we make a change to use the RequiredAttribute without any wire semantic?

Can you point me towards your custom contract resolver? I didn't see it.

> If we decide we do want the contract resolver should we use the same resolver by default for input and output?

I don't see any reason why you wouldn't want to.

**Comment by harshgMSFT** [comment]
>Where are the MVC options? I haven't touched MVC6 yet

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/MvcOptions.cs
Default set of options for MVC ( Gets added when Mvc is configured for an application).
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc/MvcOptionsSetup.cs


>Can you point me towards your custom contract resolver? I didn't see it.

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Formatters/JsonContractResolver.cs

**Comment by JamesNK** [comment]
Thanks.

I think I see a bug in your JsonContractResolver: the MemberInfo passed into CreateProperty could be a PropertyInfo or a FieldInfo. Have you got a unit test where [Required] is on a field?

**Comment by JamesNK** [comment]
You could put a JsonSerializerSettings on the options. It would make it a lot more accessible. Right now I think you would need to do something like:

    var jsonOutput = options.OutputFormatters.OfType<JsonOutputFormatter>().Single();
    jsonOutput.SerializerSettings.Formatting = Formatting.Indented;
    var jsonInput = options.InputFormatters.OfType<JsonInputFormatter>().Single();
    jsonInput.SerializerSettings.Formatting = Formatting.Indented;

Compared to:

    options.JsonSerializerSettings.Formatting = Formatting.Idented;

The input and output formatters (and any other places that use the serializer) could then use these settings unless different settings are explicitly set against them. That provides a mix of easy of use and flexibility.

**Comment by kichalla** [comment]
:+1: on the options idea!

**Comment by JamesNK** [comment]
For your contract resolver issue, one option is I could add support for RequiredAttribute to json.net's DefaultContractResolver. It would have to be disabled by default and enabled by a flag for backwards compatibility, but that would allow someone to set there own contract resolver and then set that flag to true. I did a similar thing before WebAPI was released for ISerializable.

https://github.com/JamesNK/Newtonsoft.Json/blob/629c32062ea039cf2ba82b1ba0ec48180110e409/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L178

**Comment by Eilon** [comment]
@JamesNK you know we've been wondering if our behavior is even correct when it comes to the Required attribute meaning "must be in the JSON." That's somewhat of an abuse of what that attribute means, so we're actually thinking we remove that behavior entirely... in which case it might be easier for us to just use the defaults from Json.NET.

**Comment by JamesNK** [comment]
Ok. I would agree that sticking with the default serialization rules does make things simpler for people.

Quite often people would wonder why Web API serialized some objects differently than others, and the cause was its custom handling of serializable: http://stackoverflow.com/questions/12334382/net-webapi-serialization-k-backingfield-nastiness

**Comment by JamesNK** [comment]
And people can achieve the same behavior with Json.NET attributes:

    public class Videogame
    {
        [JsonProperty(Required = Required.Always)]
        public string Name { get; set; }

        [JsonProperty(Required = Required.AllowNull)]
        public DateTime? ReleaseDate { get; set; }
    }

Although it is a little more long winded than [Required]. Maybe I should add a [JsonRequired] to mirror [JsonIgnore]?

**Comment by Eilon** [comment]
Now that would be interesting...

**Comment by rynowak** [comment]
There's an interesting parallel developing here with: 
`[JsonIgnore]` <-> `[BindNever]`
`[JsonRequired]` <-> `[BindRequired]`

`JsonPropertyAttribute` et al definitely do more than our `BindingBehaviorAttribute`s, but I'm wondering if we can avoid having to double up on attributes if you use a model sometimes for JSON and sometimes for a form post.

Maybe the default contract resolver is good enough for most and we ship a sample or in the box contract resolver that can respect our attributes (or an MMP that can respect Json.net's attributes).

**Comment by JamesNK** [comment]
I noticed [JsonProperty(Required = Required.Always)] is validated when deserializing and serializing. I'm guessing that is why MVC has different contract resolvers for input and output. You don't care about [Required] when serializing.

If I added [JsonRequired] it would be validated in both directions.

**Comment by JamesNK** [comment]
What are the dates around your beta 5? If you want ModelMetadata to use [JsonRequired] then I would need to update Json.NET first.

**Comment by JamesNK** [comment]
On second thought, in ModelMetadata you could use the contract resolver to get a contract for a type and then access JsonProperty and get information like whether a property is ignore or required there. That is available today.

**Comment by Eilon** [comment]
Yeah I don't think we'd need to depend on anything new in Json.NET. The new attribute, should you add it, would be strictly a "convenience attribute" for app developers. MVC would never reference it (except maybe in tests :smile: ).

**Comment by JamesNK** [comment]
I have updated the Newtonsoft.Json package to 7.0.1-beta3. This beta includes a new [JsonRequired] attribute.

**Comment by dougbu** [comment]
de63075 and fcf7b15
@harshgMSFT sorry I missed fact this issue was assigned to you.
@JamesNK thanks again.
