### ISSUE TITLE
Projects in the Visual Studio solution in the dev branch won't load in VS2015

### ISSUE THREAD

**Issue by ChrisKlug** [aspnet/Mvc#2389]
After cloning the dev branch to my machine, I tried to open the Mvc.sln in VS2015. However every single project failed to load due to:

![image](https://cloud.githubusercontent.com/assets/2353256/7157514/b0d934f2-e370-11e4-95c8-37a633e63c15.png)

and:

```
error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\Source Control\GitHub\AspNet\Mvc\src\Microsoft.AspNet.Mvc.Xml\Microsoft.AspNet.Mvc.Xml.xproj
```

Any suggestions on what could be wrong?

**Comment by ChrisKlug** [comment]
The .xproj files include references to $(VSToolsPath)\DNX, which seems to be $(VSToolsPath)\AspNet on my machine. Updating those references seems to work, but is probably not a good idea. Any suggestions on how I might have ended up with the wrong things?

**Comment by josher565** [comment]
I've dropped VS entirely, favouring `dnu build`. However, I don't have a working local copy either. Word has it that the next CTP drop will have xproj support, but that's all conjecture. Maybe someone else has more definitive news?

**Comment by ChrisKlug** [comment]
If you just want to play around with the code in VS, you can modify the xproj file by changing

$(VSToolsPath)\DNX\Microsoft.DNX.Props and $(VSToolsPath)\DNX\Microsoft.DNX.targets with $(VSToolsPath)\AspNet\Microsoft.Web.AspNet.Props and $(VSToolsPath)\AspNet\Microsoft.Web.AspNet.targets

That seems to work at the moment. I assume the props and targets used in the xproj-files will be added in a future VS drop or something... Or I just have a messed up environment...

**Comment by dougbu** [comment]
@ChrisKlug your environment is not messed up.  You simply have older VS tooling than we currently need to use.  That tooling has not yet been released but should be soon.  Switching to the older paths is a fine temporary workaround.  The other option is to use one of our older branches -- something still using the older paths.

**Comment by danroth27** [comment]
Unfortunately the latest ASP.NET 5 bits from our dev branch are not compatible with Visual Studio 2015 CTP 6. We will be releasing new tooling soon that will address this issue. Thank you for your patience!
