### ISSUE TITLE
Q: Missing FormDataCollection

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Mvc#2401]
There was `FormDataCollection` from System.Net.Http.Formatting. 
It was useful for parsing param-value pairs. 

Here's my use-case from WebApi2-era. 
Here's a filter which converts QS-param's value (with key-value pairs) to Request's headers.
It was used for passing headers via QS. It's useful when on the client you can control only URL but not request itself  (like for `<img href=''>` tags on the client)

```c#
    public class UrlParamsToHeadersConverterFilter : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext actionContext)
        {
            var request = actionContext.HttpContext.Request;
            string httpHeaders = request.Query.Get("$headers");
            if (!String.IsNullOrEmpty(httpHeaders))
            {
                var headersCol = new FormDataCollection(httpHeaders).ReadAsNameValueCollection();
                foreach (string name in headersCol)
                {
                    request.Headers.Remove(name);
                    request.Headers.Add(name, headersCol[name]);
                }
            }
        }
    }
```

I start converting the filter to AspNet5 and stuck as there's no FormDataCollection anymore.
What is supposed to use instead of it?
Thanks.

**Comment by pranavkm** [comment]
Does this work as a replacement - https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.WebUtilities/QueryHelpers.cs#L54?

**Comment by evil-shrike** [comment]
@pranavkm Thanks for the tip. Yeah, it looks like the similar concept.

Could you tell me what is right place/way to ask such questions ("I had Xxx thing before, what to use now?"). I already mentioned some troubles in #2380.
It'd be nice to have a single place to asking and documenting all breaking changes. Kind of wiki maybe.. I'm afraid that the [documentation](http://aspnet.readthedocs.org) won't have focus on migration from old Mvc/WebApi. I read all articles on migration, they consider only very simple cases.

**Comment by Eilon** [comment]
I think StackOverflow is a great place to ask these questions is on StackOverflow with the [asp.net-MVC-6](http://stackoverflow.com/questions/tagged/asp.net-mvc-6) tag.
