### ISSUE TITLE
Should we handle `[ModelMetadataType]` on a property's `Type`?

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2403]
Currently `GetMetadataForType()` includes the given `Type`'s metadata as well as that provided by the `Type` referenced in an associated `[ModelMetadataType]` (if any).  Similarly `GetMetadataForProperty()` includes the given property's metadata, that provided by the `Type` referenced in a `[ModelMetadataType]` associated with the property (if any), and the property's `Type`.  However `GetMetadataForProperty()` does not include metadata from a `Type` referenced in a `[ModelMetadataType]` associated with the property's `Type`.  Need to check MVC 5 behaviour for this case and do the Right Thing:tm: to maintain compatibility.

**Comment by danroth27** [comment]
@kirthik Please verify what the MVC 5 behavior was with `[MetadataType]` and align our behavior if needed.

**Comment by Eilon** [comment]
Moving to @dougbu to verify the behavior in MVC 5.

**Comment by dougbu** [comment]
Behaviour w.r.t. `[MetadataType]` or `[ModelMetadataType]` on a property's `Type` in MVC 5 and 6 is consistent: Neither version brings information in from `AnotherType` in the example below i.e. the only visible validators are `PropertyTypeValidatorAttribute` and the adapter for `RequiredAttribute`.
``` c#
    public class MergedAttributes
    {
        [Required]
        public PropertyType Property { get; set; }
    }

    [PropertyTypeValidator]
    [MetadataType(typeof(AnotherType))]
    public class PropertyType
    {
    }

    // Not seen when using MVC 5 or 6.
    [AnotherTypeValidator]
    [HiddenInput]
    public class AnotherType
    {
    }
```

However the two versions are inconsistent in a different way. Will open a new bug for that inconsistency.
