### ISSUE TITLE
Need a way to specify ContentType in ViewResult \ PartialViewResult

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#2408]
`ContentResult` has a way to specify the type and encoding for the result, but we're missing these properties on `ViewResult` \ `PartialViewResult`. It's currently hardcoded to send `text/html; charset=utf8'.

**Comment by pranavkm** [comment]
Related work item: While making this change, we need to ensure that we do not write the preamble \ BOM when a user specifies the Encoding. This is to keep parity with `ContentEncoding` in System.Web. The `StreamWriter` that we use to write to the Response writes the preamble by default.

**Comment by kichalla** [comment]
commit 7e623258c02d8414422605679dc58f260574538b
