### ISSUE TITLE
Compatibility with MVC 5 auth code

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2409]
Reported by @rustd 

This is MVC5 template code - `SignIn` and `SignOut` don't work in MVC6 due to no-content formatter turning a challenge/redirect into a 204
```
    public class AccountController : Controller
    {
        public void SignIn()
        {
            // Send an OpenID Connect sign-in request.
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge(new AuthenticationProperties { RedirectUri = "/" }, 
                    OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
        }

        public void SignOut()
        {
            string callbackUrl = Url.Action("SignOutCallback", "Account", routeValues: null, protocol: Request.Url.Scheme);

            HttpContext.GetOwinContext().Authentication.SignOut(
                new AuthenticationProperties { RedirectUri = callbackUrl },
                OpenIdConnectAuthenticationDefaults.AuthenticationType, CookieAuthenticationDefaults.AuthenticationType);
        }

        public ActionResult SignOutCallback()
        {
            if (Request.IsAuthenticated)
            {
                // Redirect to home page if the user is authenticated.
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
```

The fix for this would be to rewrite the code to use action results instead of returning void.

**Comment by danroth27** [comment]
Should we just remove the behavior of turning void into a 204? How much do we care about the scenario where I write an action method that manipulates the HttpContext directly and I really want the method return type to be meaningless?

**Comment by rynowak** [comment]
The initial hope with this feature was that the HTTP Context would give us a way to tell if the status code had been set, and that was never added.

**Comment by danroth27** [comment]
Detecting if stuff has been set on `HttpContext` seems like a slippery slope. What about headers? Content?

**Comment by danroth27** [comment]
We decided to remove the 204 behavior when returning void.
