### ISSUE TITLE
Should we standardize on the use MediaTypeHeaderValue in ActionResults?

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#2411]
We have seemingly different ways to specify ContentType \ Encoding in various ActionResults:

* `ObjectResult` uses  `MediaTypeHeaderValue` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ActionResults/ObjectResult.cs#L32 :+1: 
* `FileResult` allows specifying `ContentType` but not encoding (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ActionResults/FileResult.cs#L32)
* `ContentResult` allows specifying `ContentType` and `Encoding` separately - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ActionResults/ContentResult.cs#L16-L18
* `ViewResult` \ `PartialViewResult` allows specifying neither (https://github.com/aspnet/Mvc/issues/2408)

Might be more types here that I haven't looked at.

**Comment by rynowak** [comment]
In general the reason for the difference is what back-compat/legacy story each of these has. That's not to say we shouldn't consider improvements, but `FileResult` and `ContentResult` are more related to MVC 5, which didn't have a strongly-typed class for content-types.

**Comment by kichalla** [comment]
commit 7e623258c02d8414422605679dc58f260574538b
