### ISSUE TITLE
Missing RazorPage.RenderPage

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Mvc#2412]
Please consider an example:
Views/Shared/Index.cshtml  - a view for a SPA app. It contains some markup and a reference to a layout-page:

```
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
```

In _Layout.cshtml there're number of includes which are being used via `RenderPage` helper:

```
@RenderPage("~/Views/Shared/_ImportCssInline.cshtml")
@RenderPage("~/Views/Shared/_ImportCssLinks.cshtml")
```

Now in AspNet5 `@RenderPage` helper isn't available. 
It was the method of `WebViewPage`/`WebPageBase`/`WebPageRenderingBase`. Now they were replaced by `RazorPage`. But there's no `RenderPage` method in it.

What should be used instead?

p.s. [SO question](http://stackoverflow.com/questions/29770041)

**Comment by danroth27** [comment]
Yup, we haven't done the work yet to support Web Pages scenarios in MVC 6. For this scenario you can use `@Html.Partial(...)` instead.

**Comment by mpawelski** [comment]
Yes for this scenario (absolute path to view) Html.Partial works, but relative view view doesn't work for Html.Partial and they do for RenderPage :(

**Comment by pranavkm** [comment]
@mpawelski that should get fixed once https://github.com/aspnet/Mvc/issues/3307 is resolved. There's an ongoing PR for it.

**Comment by Eilon** [comment]
This should hopefully be a part of the work for Razor Pages, which is tracked here: https://github.com/aspnet/Mvc/issues/494
