### ISSUE TITLE
PageExecutionContext not called for tag helpers

### ISSUE THREAD

**Issue by jodavis** [aspnet/Mvc#2429]
Functional issue:
When content is generated by a tag helper (or even left unmodified by a tag helper), Browser Link can't map that element back to source.

Repro steps:
1. In a DNX website using MVC, add an IPageExecutionListenerFeature
2. Set a breakpoint in PageExecutionContext.BeginContext and EndContext
3. Run a Razor page that uses Tag Helpers.

Expected result:
BeginContext and EndContext are called for every range of the rendered page

Actual result:
BeginContext and EndContext are called for most of the rendered page, but not the parts rendered by Tag Helpers.

**Comment by Eilon** [comment]
@jodavis @NTaylorMullen let's chat about this one to figure out the right behavior.

**Comment by NTaylorMullen** [comment]
This is a duplicate of https://github.com/aspnet/Razor/issues/172 however this item seems to be more descriptive.
