### ISSUE TITLE
IViewContentLocator interface

### ISSUE THREAD

**Issue by korzh** [aspnet/Mvc#2432]
Currently MVC searches file system when need to find the source (CSHTML) for some view.
We need some simple mechanism to locate view content by name. After that found content will be processed by Razor engine. 
We can add new interface IViewContentLocator with one method: 
   Stream GetViewContent(string viewName);
The default implementation will search for view content on file system but it will be possible to register another implementation of IViewContentLocator which will get view content, for example, from some DB, from resources or any other storage.

**Comment by pranavkm** [comment]
There are two potential solutions already in place for this:
* The `RazorViewEngine` uses the `IFileProvider` from `RazorViewEngineOptions`. You could simply implement a custom file provider so your searches don't hit the physical file provider. See https://github.com/aspnet/Mvc/blob/dev/test/WebSites/RazorEmbeddedViewsWebSite/Startup.cs#L20-L23

* The `RazorViewEngine` also uses a `IVirtualPathRazorPageFactory` which gives you types for paths. This could be replaced to point to a custom location (and comes pretty close to the semantics of your proposal.)

**Comment by korzh** [comment]
The problem with both these approaches is: they are too "coupled" to file system. 
Writing my own IFileProvider will solve the task but:
1. It's not quite correct to operate with "files" (even virtual ones) while we just need to get content for some view.
2. It's not effective since GetFileInfo() method gets something like "/Views/MyController/MyView.cshtml" in parameter and we will need to use RegExp to cut necessary part of the path and get real view name from it.
Moreover, with such approach we do a lot of totally unnecessary operations like:
 * getting a  list of "view locations"
 * navigating through that list and trying to get IFileInfo for each view location.

That's why I offer to add new IViewContentLocator interface (the actual name is not important of course) and place all logic with searching "view locations" and getting file content as a default implementation for this interface.

**Comment by pranavkm** [comment]
Most of what `RazorViewEngine` does is create probing paths for files the file provider. If your intention is to not probe the disk - why not roll a custom view engine? The view engine in itself doesn't deal with parsing \ compilation - so you're not going to get much out of introducing a new extensibility point on it.

**Comment by korzh** [comment]
The thing is: I would like to change current behavior for some views and leave it "as is" for all others.
For example, you may want to establish some kind of blog engine on your site where all posts (with Razor markup) are stored in DB (or other storage). 
So, it would be great to have that special "view locator" for all views under /blog/* path and process all others as usual.

**Comment by danroth27** [comment]
@korzh Is this really for blog posts? It seems a bit odd to allow server-side code in user blog posts. Or did you have another specific scenario in mind? Any information you can give us about your specific scenarios would help us understand what the right solution is here.

**Comment by danroth27** [comment]
Putting on the backlog for now as we are already over booked for the current release. But we can re-evaluate as we understand the scenarios better.

**Comment by korzh** [comment]
OK. 
The scenario is quite simple. Let's suppose we would like to build some kind of CMS system based on MVC and use Razor rendering for content.

**Comment by korzh** [comment]
@danroth27 I would like to explain more in details about the scenario I have in mind.

We are going to create a web-portal for one company which will include the following main components:
 * Admin section (accessed as /Admin/*) - a set of pages where administrators can change different settings, control access to the side, manage Client area users, add new content, etc.
 * Client area (/Client/* ) - where company customers can get support, download some files and get access to some info which is not available to public visitors. This section requires login/password to access as well as Admin section but the list of users for these 2 sections are totally different. 
 * Content area - all other pages on the site which are available to public. Admins can create new pages in this area, specify the route to them (e.g. /products/item1/)  and change the content of those pages through Admin section. Moreover we would like to have an ability to use Razor syntax to define content here. For example we have a product page in Content section and that product page should show different price (or discount) depending on page visitor. Additionally we are going to define several tag helpers and give our content managers a possibility to use those helpers when defining the content.

So my intent is to create usual MVC controller for /Admin and /Client sections and use some special "Dispatcher" controller/action for all other pages on the site. That Dispatcher controller will do the following:
 * takes the route to the page (e.g. /products/soho/myproduct1)
 * find the page content in underlying DB according to its route
 * render that page and write the final result into Response.Output stream

I hope the above makes sense and you will consider the requested interface during the next update of MVC library. 
Or (even better) it would be great if you could suggest more appropriate solution for described task.

**Comment by alexsandro-xpt** [comment]
+1

**Comment by davidshorter** [comment]
+1

**Comment by NeelBhatt** [comment]
+1 

@pranavkm the link you provided in your thread is not working currently! may be some update on that?

**Comment by pranavkm** [comment]
The sample got moved here - https://github.com/aspnet/Mvc/blob/dev/samples/EmbeddedViewSample.Web/Startup.cs#L22

**Comment by mikeandersun** [comment]
+1
https://github.com/aspnet/Mvc/issues/3753

**Comment by pranavkm** [comment]
Getting back to this after a while. Things have changed a bit, as of 2.0, the abstraction that Razor's parsing and code generation works with is the [RazorProjectFileSystem](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/RazorProjectFileSystem.cs). One way to go about doing what you're trying to do here would be to add a composite that augments the default file provider with content from alternate sources, for e.g. an EFContext or the database. 

Here's how we use it in the Razor Sdk to support linked files that appear from outside the project's directory:

* https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Tools/GenerateCommand.cs#L149-L153
* https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Tools/CompositeRazorProjectFileSystem.cs#L11
* https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Razor.Language/VirtualRazorProjectFileSystem.cs#L11

Most of the types listed here are internal, but we could consider making these public if there's sufficient interest in doing so.

Replacing the RazorProjectFileSystem with a composite would be the way to go.

**Comment by rynowak** [comment]
> Replacing the RazorProjectFileSystem with a composite would be the way to go.

Side note, these kinds of techniques will not work at all with build-time Razor and will have non-existent tooling/intellisense support. I'm not sure there's a future where we **ever** provide support this kind of dynamism in MVC.
