### ISSUE TITLE
ModelBinder Issue on Mono

### ISSUE THREAD

**Issue by kvpt** [aspnet/Mvc#2434]
Hi,

I have a ViewModel with ObjectId property, It's a specific Struct from the MongoDB driver.

```cs
public class EntityViewModel
{
      public ObjectId Id { get; set; }
}
```

I send the ViewModel to the server in json and receive it in the controller with the FromBody attribute.
```cs
public IActionResult AddEntity([FromBody] EntityViewModel model) { ... }
```

This work perfectly on Windows.
But on Linux (I use the beta3 docker image) the server return this error.

> An unhandled exception occurred while processing the request.

> InvalidProgramException: Invalid IL code in (wrapper delegate-invoke) \<Module>:invoke_callvirt_DateTime_ObjectId& (MongoDB.Bson.ObjectId&): IL_004d: castclass 0x00000007

> Microsoft.AspNet.Mvc.PropertyHelper.CallPropertyGetterByReference\[ObjectId,DateTime] (Microsoft.AspNet.Mvc.ByRefFunc`2 getter, System.Object target) [0x00000] in \<filename unknown>
> Microsoft.AspNet.Mvc.PropertyHelper.GetValue (System.Object instance) [0x00000] in \<filename unknown>
> Microsoft.AspNet.Mvc.ModelBinding.AssociatedMetadataProvider`1+<>c__DisplayClass9_0[Microsoft.AspNet.Mvc.ModelBinding.CachedDataAnnotationsModelMetadata].<GetMetadataForPropertiesCore>b__0 () [0x00000] in \<filename unknown>
> Microsoft.AspNet.Mvc.ModelBinding.ModelMetadata.get_Model () [0x00000] in \<filename unknown>

I found this [issue](https://bugzilla.xamarin.com/show_bug.cgi?id=25717) closed recently on mono, is this related ?

**Comment by danroth27** [comment]
@sornaks Please confirm this issue has been fixed in Mono and then close as appropriate.

**Comment by sornaks** [comment]
Yes this was fixed in Mono (https://github.com/mono/mono/commit/c73363cee456b32c726ef7a0c4d504f1d07eaad2). You will have to build mono from source to get this change. (Mono issue - https://bugzilla.xamarin.com/show_bug.cgi?id=25717)
