### ISSUE TITLE
ViewAsync() ?

### ISSUE THREAD

**Issue by vncastanheira** [aspnet/Mvc#2437]
Since there's benefits in creating async actions, I was wondering why `Controller` doesn't have something like a **ViewAsync()** method.
So currently I'm doing this:

    public async Task<IActionResult> Index()
    {
        return await Task.FromResult(View());
    }

Is that wrong? Is there a better approach? I'm confused somehow.

**Comment by rynowak** [comment]
@vncastanheira

Calling `View()` doesn't actually execute the view - it just instantiates a `ViewResult` with the data necessary to find it later. The actual view execution will take place later and already is async. 

Take a look here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/FilterActionInvoker.cs

The action returns an `IActionResult` instance, which will be executed later (surrounded by result filters).

**Comment by vncastanheira** [comment]
@rynowak 
Oh, that clarifies a lot! So won't be a problem to declare an Action normally then...

**Comment by rynowak** [comment]
yes, you can safely do async work in a view regardless of how your action is declared

**Comment by vncastanheira** [comment]
Thanks!
