### ISSUE TITLE
Review use of ModelExplorer in validation/modelbinding code

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2438]
There's some branches of the ModelBinding and Validation code that use `ModelExplorer` to access properties and 'walk' the model.

The issue with this is that `ModelExplorer` is based on the runtime type of the model and will access sub-properties based on the runtime type (not the declared type).

Is this the right thing to do for validation?

**Comment by Eilon** [comment]
Need to come up with a scenario and test it in MVC 5.

**Comment by troyschneringer** [comment]
Seems related to #2494

**Comment by rynowak** [comment]
Verified in the code that we're never using `ModelExplorer.Properties` - we always use `ModelMetadata.Properties`.

The goal of this item is to refactor without a behavior change. Moving to beta7 as discussed.

**Comment by rynowak** [comment]
0d6edf240ac9fcb3f691319f4a7a63a1fa411b99
