### ISSUE TITLE
Model State should have values for greedy model binders as well.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#2445]
Currently HeaderModelBinder and BodyModelBinder do not populate the model state by calling `SetModelValue`, for success cases. This means we cannot do a ajax post which uses the populated value.

**Comment by dougbu** [comment]
Based on the tests that are disabled with this bug as the reason, problem is much more broad. All values bound from user input should have `ModelState` entries. This affects `ByteArrayModelBinder`, `FormCollectionModelBinder`, and `FormFileModelBinder` as well as the two mentioned in the original description (`BodyModelBinder` and `HeaderModelBinder`). So, "type-matching" as well as "greedy" binders.

**Comment by dougbu** [comment]
- c4fa402 and 715a0b6
- further cleanup in a170a4e
