### ISSUE TITLE
Model state has spurious entries when binding to a collection where element type has no validators.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#2446]
Consider the following scenario 
```c#
public Action([FromHeader(Name = "Header")]string[] headers)
{
}
```
Input
Header: a, b, c
In this case there should be the following keys in the model state
`Header[0]`
`Header[1]`
`Header[2]`

but there a spurious entry for 
`Header` as well which should not be there. 
This would be the case even for simple scenarios like so

```c#
public Action(string[] parameter)
{
}
```
Query string is 
parameter[0]=foo

in this case there would be two entries
`parameter[0]`
and 
`parameter`

**Comment by Eilon** [comment]
The model state entries should represent the structure of the posted data as opposed to how they were bound.

**Comment by Eilon** [comment]
Also need to check what exactly happens today in MVC5 / MVC6 for the scenarios listed above, plus this one:

```c#
public ActionResult Foo(Person[] people)
{
}

public class Person : IValidatableObject
{
}
```

**Comment by harshgMSFT** [comment]
MVC 5.0

For 
```c#
public ActionResult Foo(Person[] people)
{
}

public class Person : IValidatableObject
{
           public string Name { get; set; }
           public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
            {
                if (Name ==  "c")
                {
                    yield return new ValidationResult("c is not allowed.");
                }

                yield break;
            }
}
```
if there are three people bound
with query string as  `?people[0].Name=a&people[1].Name=b&people[2].Name=c`
there would be FOUR entries 
`people[0].Name`,`people[1].Name`,`people[2].Name`,`people[2]` - this one has an error and no value.

For the other scenario listed in the bug, MVC 5.0 does not add the key with parameter name. (adds only what is bound).

**Comment by dougbu** [comment]
@harshgMSFT could you please clarify the MVC 5 / 6 differences in these scenarios?

**Comment by rynowak** [comment]
88ac4b94e451441da2a03c9f2f5a3c54b73f45cf
