### ISSUE TITLE
Model binding CancellationToken should not be validated or have a model state entry

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#2447]
```c#
public Action(CancellationToken token)
{
}
```
Will have an entry in the model state with 
key:token
validationState: Valid.

This should ideally be marked as skipped.

**Comment by pranavkm** [comment]
Shouldn't we simply exclude `CancellationToken` from validation instead?

**Comment by harshgMSFT** [comment]
That's how we exclude, by marking it as skipped. Note that this also applies in cases when it shows up as property.

**Comment by harshgMSFT** [comment]
In alignment with the agreed principles, we would not be adding any entry in the model state.
