### ISSUE TITLE
`byte[]` model binder should prevent falling back to other binders when the type matches.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#2456]
If the Model Type is `IFormFile` or `IEnumerable<IFormFile>`, even though we return a non null 
`ModelBindingResult`, in cases where the model is not set ( for example when there is no form body ), 
it will result into a ModelBindingResult of null returned to the caller. This is because of 
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/CompositeModelBinder.cs#L107

Ideally FormFileModelBinder should behave like a greedy model binder.

**Comment by rynowak** [comment]
Can you include some sample code and an example of what the user-visible effect of this would be?

**Comment by Eilon** [comment]
The main concern is that this model binder currently allows other model binders to run after it. The correct behavior of this model binder should be to always produce a result, even if it didn't bind anything (e.g. because there was no file or body).

**Comment by rynowak** [comment]
This is also true of `byte[]` model binder. There are numerous cases where it doesn't handle a model of `byte[]`.

**Comment by dougbu** [comment]
Updated title. `ByteArrayModelBinder` is the only type-matching binder that _ever_ returns `null` when the tested property is of the matched type. The rest of the binders work as expected. In particular all other tests skipped supposedly due to this bug had other issues.

**Comment by dougbu** [comment]
e31eab0
