### ISSUE TITLE
For successfully bound models there should be no entry with empty key in the model state dictionary.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#2466]
For example 
```c#

public class DocumentContainer
{
       public Document Document { get; set; }
}
public class Document
{
     [FromHeader]
     public string Version { get; set; }
}

public void Action(DocumentContainer container);
```

In this example currently we fall back to empty prefix and hence the keys in the model state dictionary are like so
`""`
`Document`
`Document.Version`

The first key (and arguably the second key) should not be there. 

MVC 5.0 behavior in a similar scenario (where Version was bound from query instead of header), was have just one key
`Document.Version`

**Comment by Eilon** [comment]
Also need to check what happens in MVC 5 if `Document` implements `IValidatableObject`.

**Comment by harshgMSFT** [comment]
In Mvc 5.0 if `Document` implements `IValidatableObject` there are two entries 
`Document`  and `Document.Version`.
The first entry is added only if there is an error reported by the `IValidatableObject`.

**Comment by rynowak** [comment]
88ac4b94e451441da2a03c9f2f5a3c54b73f45cf
