### ISSUE TITLE
Composite Model Binder should not return a null result if a model binder returns a non-null result.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#2473]
Currently if any model binder returns a MBR like so
`new ModelBindingResult(model: null, isModelSet: false, key:"Key);`
then the composite model binder returns a null result 
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/CompositeModelBinder.cs#L120

The original intent of this code was to ensure we fallback to the empty model in
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/CompositeModelBinder.cs#L40

however there are better ways to achieve it ( for eg. rewriting the condition :smile: ).

**Comment by dougbu** [comment]
@harshgMSFT why is this a bug?  what visible impact do the current choices have?  if there's an impact, suggest filing a bug about _that_.

we discussed the approach at length when making the changes you've highlighted and this was the best idea anyone came up with.  in particular changing the condition leads to a ripple of additional complexity in other parts of the system and unnecessary churn, ending up with no measurable improvement.

**Comment by harshgMSFT** [comment]
>we discussed the approach at length when making the changes you've highlighted and this was the best idea anyone came up with. in particular changing the condition leads to a ripple of additional complexity in other parts of the system and unnecessary churn, ending up with no measurable improvement.

Well the only reason we (or at least I did) agreed that time was we wanted to move forward with the release in mind, having that line in the code is a hack and not a solution. And yes you are right I should have included the user impact. Sorry for the confusion and here is the detailed scenario : 

```c# 

public class Document
{
       [FromHeader]
       [Required]
       public string Version { get; set; }
}

public void Action(Document doc)
{
}
```

In this case if there is no header called `Version` we end up returning 
`new ModelBindingResult(model: null, isModelSet: false, key:"Key");`
which means a composite model binder chooses to return null from https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/CompositeModelBinder.cs#L120

Now in this particular scenario the user visible problem is
We return null from https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/CompositeModelBinder.cs#L52

This results in ComplexDTOModelBinder returning a NON-NULL MBR from https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/ComplexModelDtoModelBinder.cs#L37
which uses constructs a key which is later used to addvalidation errors - And hence the user impact. 

All of this because we chose to hack our way in ComplexModelBinder.

Also consider the following scenario

```c#
public void Action([FromHeader] string Version)
{
}
```
Assume there is no header called Version. In this case because we chose to ignore a non-null ModelBindingResult from a greedy model binder, we fall back to the emtpy prefix case even though we know for a greedy model binder, it should not make a difference.

 
 Please note I took an example of HeaderModelBinder, but this happens with BinderTypeModelBinder, and any other greedy model binder which does not add a model state error with a key :).

**Comment by dougbu** [comment]
not seeing an actual impact in any of this.  you haven't described a difference in whether values are correctly bound, in the `ModelStateDictionary` instance, and so on.  `ModelBindingResult` isn't seen outside the model binding system.

as I said in the test PR, a non-`null` `ModelBindingResult` with `IsModelSet==false` is _only_ a signal to the next `ComplexModelBinder` up.  your test is broken because it mixes a `IsModelSet==true` case with `IsModelSet==false` and they are not the same scenario.

that said, the "greedy" model binders may not be not fitting well into the `MutableObjectModelBinder` / `ComplexModelBinder` world and we may need to _add_ more information to `ModelBindingResult` to handle those differences.

**Comment by harshgMSFT** [comment]
>not seeing an actual impact in any of this. you haven't described a difference in whether values are correctly bound, in the ModelStateDictionary instance, and so on. ModelBindingResult isn't seen outside the model binding system.

As i mentioned ```which uses constructs a key which is later used to addvalidation errors -``` which implies that the model state entries are incorrect. I thought that was obvious. 

I do not want to get into what is the right implementation for the bug- 
I just want to make sure the behavior of the composite model binder is something we agree on. 

Also please note the second scenario as well - there too the model state entries key change because they fallback to the empty prefix and that messes up the keys.

**Comment by dougbu** [comment]
I'm not talking about an implementation issue but think you are.  the greedy model binders are _not_ the general case and we likely need to pass more information for them to integrate correctly.

**Comment by Eilon** [comment]
Not taking any direct action on this right now.

@harshgMSFT feel free to investigate this further in terms of a more major overhaul of where CompositeModelBinder shows up in the hierarchy of model binders.
