### ISSUE TITLE
[Activate] does not work on Controllers in beta4

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#2476]
The following two lines work in a tag helper, but give a stack trace when in a controller:
```
[Activate]
private IHostingEnvironment hostingEnvironment{ get; set; }
```

That stacktrace is
```
InvalidOperationException: The property 'hostingEnvironment' on controller '*.Controllers.somecontroller' cannot be activated.

    Microsoft.AspNet.Mvc.DefaultControllerFactory.CreateActivateInfo(PropertyInfo property)
    System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
    System.Linq.Buffer`1..ctor(IEnumerable`1 source)
    System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
    Microsoft.Framework.Internal.PropertyActivator`1.GetPropertiesToActivate(Type type, Type activateAttributeType, Func`2 createActivateInfo)
    Microsoft.AspNet.Mvc.DefaultControllerFactory.GetPropertiesToActivate(Type type)
    System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
    Microsoft.AspNet.Mvc.DefaultControllerFactory.ActivateProperties(Object controller, ActionContext context)
    Microsoft.AspNet.Mvc.DefaultControllerFactory.CreateController(ActionContext actionContext)
    Microsoft.AspNet.Mvc.Core.ControllerActionInvoker.CreateInstance()
    […]
```

**Comment by rynowak** [comment]
This is a design change - `[Activate]` is for context items like `ActionContext`. Use `[FromServices]` in a controller to access a service (or take it as a constructor parameter).

We have some changes planned for the current milestone to make this consistent across taghelpers/controllers

**Comment by Tragetaschen** [comment]
Makes sense. It looks like view components are  working like tag helpers right now, right?

It might be a different issue, but I'm trying to get an `IApiDescriptionGroupCollectionProvider` into my Controller. In my `ViewComponent`, I can still use `[Activate]` and it works like before. In the controller, though, the situation is:
- Constructor parameter: works
- [Activate]: Cannot activate exception with stack trace
- [FromServices]: property remains `null`

**Comment by rynowak** [comment]
`[FromServices]` on a controller property is expected to work in beta4 - is it a public get/set property?

**Comment by Tragetaschen** [comment]
Ah, that's it. I still had this specified as a private property. That worked with `[Activate]` and still works ViewComponents and TagHelpers.

**Comment by danroth27** [comment]
Note that we plan to clean up the naming of Inject vs Activate vs FromService. See https://github.com/aspnet/Mvc/issues/2151.
