### ISSUE TITLE
JsonResult not serializing Dynamic object's properties

### ISSUE THREAD

**Issue by TravisTheTechie** [aspnet/Mvc#2480]
https://bitbucket.org/atlassian/atlassian-connect-.net/src/e4c5c85e7c2f578859843f7553b141a9c9c7590d/JiraActivity/Controllers/HomeController.cs?at=master#cl-33 has a JSON result that's a dynamic object. This works great in the previous version of MVC (v5.2 I think).

I created a new MVC 6 (`$ yo aspnet` ;  `> WebApplication`) and copied that controller action over into this new app. The action always returns an empty JSON object (`{}`). 

So then I created a simpler example... 

``` csharp
  public class MyObj : System.Dynamic.DynamicObject
    {
        public int OneTwo { get; set; }
    }
    public class TestController : Controller
    {
        public IActionResult Test()
        {
            dynamic obj = new MyObj();
            obj.OneTwo = 3;
            return Json(obj);
        }
     }
```

And this always returns an empty JSON object as well. Then I removed the `: DynamicObject` from `MyObj` and it returns the object correctly. I validated the property was assigned with a value in the debugger with `DynamicObject`.

**Comment by rynowak** [comment]
In the JIRA example - `ConnectDescriptor` also declares properties for all of the data members that are initialized: https://bitbucket.org/atlassian/atlassian-connect-.net/src/e4c5c85e7c2f578859843f7553b141a9c9c7590d/Atlassian.Connect/ConnectDescriptor.cs?at=master

This behavior is part of JSON.Net, and I'm not aware of any changes to it between the version we use in 5.2 and the version we use in 6.0.

If you run **your** code sample in MVC 5 what is the result?

**Comment by TravisTheTechie** [comment]
With MVC 5.2...

``` csharp
public class MyObj : System.Dynamic.DynamicObject
{
    public int OneTwo { get; set; }
}

public class TestController : Controller
{
    [HttpGet]
    public ActionResult Test()
    {
        dynamic obj = new MyObj();
        obj.OneTwo = 3;
        return Json(obj, JsonRequestBehavior.AllowGet);
    }
}
```

Returns 

``` javascript
{"OneTwo":3}
```

Which is the expected behaviour. Again, the property is implemented -- if I remove the `DynamicObject` parent object then it works in MVC 6. The thought is that this is a JSON.NET issue? So should I try to narrow an example down that specifically?

**Comment by rynowak** [comment]
@TravisTheTechie 

Digging a little bit deeper here, I was wrong about this. This code goes through `JavascriptSerializer` in  MVC 5.0 which we're not planning on bringing forward. 

JSON.Net does have different behavior in this regard: See section on Dynamic http://www.newtonsoft.com/json/help/html/SerializationGuide.htm It looks like you can configure the behavior you want using attributes or a custom contract resolver.

**Comment by TravisTheTechie** [comment]
Thanks for digging into this. This makes sense. 

My next question is should this be considered a regression and something you'll fix in the defaults for MVC 6 or do you just consider it an edge case and document the possible problem in the release notes?

**Comment by danroth27** [comment]
We plan to stick with the default JSON.NET behavior.
