### ISSUE TITLE
ModelBinding in beta5 does not support dictionary bindings from querystrings like ?filters[email]=com&filters[role]=client to IDictionary<string, string> ?

### ISSUE THREAD

**Issue by IsaacSee** [aspnet/Mvc#2483]
Trying to bind this using the following action method signature : 
```csharp
public async Task<object> Paginate(ExternalPaginationDefinition model)
```
With ExternalPaginationDefinition being : 
```csharp
public class ExternalPaginationDefinition
{
    public IDictionary<string, string> Filters { get; set; } = new Dictionary<string, string>();
}
```
Request.Query contains the following keys "filters[email]" & "filters[role]" but the "Filters" property from model remains empty.

**Comment by kichalla** [comment]
This is a known issue. You can take a look at this comment to find the supported format as of now:

https://github.com/aspnet/Mvc/issues/1418#issuecomment-84133190

**Comment by IsaacSee** [comment]
Thanks for your quick answer. 
I will not be able to adapt to the Properties[0].Key=Height format since the client part is not in my hands. Will have to create a custom binder (without the Html.NameFor witch we do not use), it feels like an important mapping case.

**Comment by IsaacSee** [comment]
Quick & dirty workaround waiting for proper binder. 
Considering this querystring *?filters[email]=com&filters[role]=client*

```csharp
IDictionary<string, string> filters = Request.Query.ExtractQueryNamedDictionary("filters");
```

```csharp
public static IDictionary<string, string> ExtractQueryNamedDictionary(this IReadableStringCollection collection, string name)
{
    var res = new Dictionary<string, string>();
    var signature = new Regex($@"^{name}\[(?<key>.*?)\]$", RegexOptions.IgnoreCase);
    foreach(var kvp in collection)
    {
        var m = signature.Match(kvp.Key);
        if(m.Success)
        {
            res.Add(m.Groups["key"].Value, kvp.Value.First());
        }
    }
    return res;
}
```

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Mvc/issues/1418
