### ISSUE TITLE
Deployment Issue - You do not have permission to view this directory or page.

### ISSUE THREAD

**Issue by paranoid-android** [aspnet/Mvc#2488]
I have an ASP.NET 5 app. My app runs successfully locally. I can use it by visiting `http://localhost.com:5004`. I have the code checked into a private repository in GitHub. I then have a Microsoft Azure Website that does automatic deployments from the master branch.

The deployments tab in the Azure Website says the deployment was successful. It says that the master branch is the active deployment. However, when I visit the url associated with the site, it says: 

`You do not have permission to view this directory or page.`

What would cause this? How can one fix this?

**Comment by danroth27** [comment]
@davidebbo @davidfowl Thoughts on how to debug this?

**Comment by davidebbo** [comment]
@paranoid-android please open an issue on https://github.com/projectkudu/kudu/issues, and share a sample github repo that demonstrates the problem. Make sure you're using beta4, as earlier betas are no longer supported.

/cc @ahmelsayed
