### ISSUE TITLE
Both travis and appveyor CI are failing at the moment

### ISSUE THREAD

**Issue by jasonwilliams200OK** [aspnet/Mvc#2490]
Some bad PR got merged in haste or accidentally?

**Comment by pranavkm** [comment]
AppVeyor is fixed now. Unfortunately we haven't had Travis build successfully as yet. Tests need to be updated to account for differences in reflection order and exception messages. @sornaks is currently looking into it.

@sornaks is there a work item tracking your effort?

**Comment by sornaks** [comment]
Just opened one. https://github.com/aspnet/Mvc/issues/2492

**Comment by Eilon** [comment]
@NTaylorMullen use this to track any AppVeyor-related work; @sornaks 's bug will track the Travis work.

**Comment by NTaylorMullen** [comment]
Looks as if AppVeyor is passing now. May want to close this issue if it's only tracking AppVeyor work; that is unless the build passing is an anomaly.

**Comment by Eilon** [comment]
I just saw several successful builds on AppVeyor, so I'll assume it's not an anomaly. Will log a new bug if we see additional issues.

**Comment by jasonwilliams200OK** [comment]
:+1:
