### ISSUE TITLE
`TagHelperOutputExtensions.RemoveRange()` does not handle its `attributes` parameter safely

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2491]
the following code:
``` C#
var attributes = tagHelperOutput.Attributes
    .Where(item => item.Name.StartsWith("route-", StringComparison.OrdinalIgnoreCase));
tagHelperOutput.RemoveRange(attributes);
```
`throw`s an `InvalidOperationException` with `Message == "Collection was modified; enumeration operation may not execute."`

`RemoveRange()` should use `ToArray()` or `ToList()` to avoid such issues in its `for` loop.

**Comment by Eilon** [comment]
@ajaybhargavb please write a failing unit test first, TDD style. Then fix.

**Comment by Eilon** [comment]
Need to mark as "Done"?
