### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by sornaks** [aspnet/Mvc#2492]

**Comment by sornaks** [comment]
https://github.com/aspnet/Mvc/commit/68523a3550a288252d48ae147dbf30b091f4bc79

**Comment by rynowak** [comment]
:fireworks:

**Comment by herecydev** [comment]
Travis still broken? Lots of PRs with Appveyor saying [its ok](https://github.com/aspnet/Mvc/pull/3559); appveyor not so much.

**Comment by dougbu** [comment]
@herecydev won't get much visibility commenting on a closed issue. But, yes Travis, is not reliable these days. I'm pushing through the repos to improve this but haven't reached MVC yet.

**Comment by herecydev** [comment]
It seemed senseless to open up a new issue when this one already existed. Maybe you should have some more extensive alerts for comments that are added to closed issues. After all, it's more alarming that fixed items raise comments than those that are in progress.
