### ISSUE TITLE
DefaultControllerActionArgumentBinder should use runtime type for validation

### ISSUE THREAD

**Issue by troyschneringer** [aspnet/Mvc#2494]
I have created a custom model binder to properly bind a derived class based on a value in the request body.  However, the model validation runs against the static parameter type (the base class) rather than the runtime type (the derived class).

The suspect code is the creation of the `ModelExplorer` in `PopulateArgumentsAsync` method of `DefaultControllerActionArgumentBinder`.

Original:
```
var modelExplorer = new ModelExplorer(
    _modelMetadataProvider,
    metadata,
    modelBindingResult.Model);
```
Suggested Change:

```
var modelMetadata = _modelMetadataProvider.GetMetadataForType(modelBindingResult.Model.GetType());
var modelExplorer = new ModelExplorer(
    _modelMetadataProvider,
    modelMetadata,
    modelBindingResult.Model);
```                                                

Example:
```
class ApiModel
{
    public string property { get; set; }
}

class DerivedApiModel : ApiModel
{
    [Required]
    public int subProperty { get; set; }
}

class ApiModelBinder : IModelBinder
{
    private static Type ModelType = typeof(ApiModel);

    public Task<ModelBindingResult> BindModelAsync(ModelBindingContext bindingContext)
    {
        if (!ModelType.IsAssignableFrom(bindingContext.ModelType))
            return Task.FromResult<ModelBindingResult>(null);

        var request = bindingContext.OperationBindingContext.HttpContext.Request;

        using (var reader = new JsonTextReader(new StreamReader(request.Body)))
        {
            var serializer = new JsonSerializer();
            var jObject = serializer.Deserialize<JObject>(reader);
            var apiModel = jObject.ToObject<ApiModel>();

            object model = apiModel.property == "derived"
                ? jObject.ToObject<DerivedApiModel>()
                : apiModel;

            return Task.FromResult(new ModelBindingResult(model: model, key: String.Empty, isModelSet: true));
        }
    }
}
```

When running this the validation is only performed against the base type so that the `subProperty` validation is never fired.

- os: Windows 8.1
- mvc: 1.0.0-beta4
- host: Kestrel

**Comment by Eilon** [comment]
Let's investigate what the MVC 5 behavior was to see if there are any compat concerns.

**Comment by bgeihsgt** [comment]
To accomplish something similar in mvc 5/beta 3 we had to call validation manually manually because validation didn't automatically run against objects bound in our model binder.  Similar to how body model binder worked in beta3.  Fwiw, this approach properly used the runtime type instead of the parameter type for validation.

**Comment by rynowak** [comment]
This is now possible to customize in the new validation system: 8a502dbe5de598eeb07318f44191f0372f7dfed0

Have your model binder create add the appropriate model metadata for your model like this:
```
bindingContext.ValidationState.Add(model, new ValidationStateEntry() { Metadata = metadata });
```

We'll perform validation according to the metadata you provide.
