### ISSUE TITLE
PrecompilationWebSite has troubles building in VS

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2498]
- no problems if site built on its own
- 10 errors if Microsoft.AspNet.Mvc.FunctionalTests or solution built
 - 8 messages are "Cannot resolve TagHelper containing assembly 'PrecompilationWebSite'. Error: Could not load file or assembly 'Microsoft.AspNet.Mvc.Core' or one of its dependencies. The system cannot find the file specified."
 - 2 messages are "Encountered an unexpected error when attempting to resolve tag helper directive '@addTagHelper' with value '*, Microsoft.AspNet.Mvc.TagHelpers'. Error: Could not load file or assembly 'Microsoft.AspNet.Mvc.Core' or one of its dependencies. The system cannot find the file specified."

**Comment by danroth27** [comment]
@davidfowl @Eilon What's the plan for precompilation all up?

**Comment by dougbu** [comment]
See also aspnet/RazorTooling#10

**Comment by dougbu** [comment]
Basically there's two ways to go from here:
1. Fix this bug or aspnet/RazorTooling#10 -- either should get Razor precompilation working reliably across the MVC repo.  Then revert commit 3fbead0.
2. Decide Razor precompilation is unstable and will take a significant (unbudgeted) effort to get working reliably.  Then remove our support for this feature, along with the PrecompilationWebSite.

**Comment by danroth27** [comment]
#2551
