### ISSUE TITLE
Link generation by name is not working in some scenarios

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#2500]
I ran into the following now...for the following controller and code to generate link, I do not get any link

```c#
[Route("api/[controller]", Name = "ProductsApi")]
public class ProductsController : Controller
{
    [HttpGet("{id}")]
    public IActionResult Get(int id)
    {
        throw new NotImplementedException();
    }
}

//---------------------------

Url.RouteUrl(routeName: "ProductsApi", values: new { id = 10 })

```

I debugged into this a bit and noticed this line
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ApplicationModels/AttributeRouteModel.cs#L97

@rynowak ...this is intentional behavior?

**Comment by dougbu** [comment]
@kichalla looks like a typo. What happens if you pass `routeName: "ProductsApi"` into `RouteUrl()`?

**Comment by kichalla** [comment]
oops..that was a typo in my repro code...correct the original post...the behavior is still the same..

**Comment by rynowak** [comment]
:laughing:

**Comment by kichalla** [comment]
Discussed with @rynowak ...this is by design... @danroth27 @Eilon

**Comment by Eilon** [comment]
So what was the issue? Wrong name being used? Bad parameters?

**Comment by rynowak** [comment]
In his example there is not such route as `ProductsApi`. Adding a suffix at the action level makes it a **new route** and the name is not applied. Think about how this would work if it didn't do that :laughing:  almost every controller with a named route would end up having ambiguity.

**Comment by Eilon** [comment]
O I C, makes sense.
