### ISSUE TITLE
Decouple Unobtrusive validation generator

### ISSUE THREAD

**Issue by mrchief** [aspnet/Mvc#2503]
Currently, ASP.NET uses a static class `UnobtrusiveValidationAttributesGenerator.cs` to generate unobtrusive validation attributes which are coupled to Microsoft's legacy implementation.

Does it make sense to decouple this by taking in an `IUnobtrusiveValidationAttributesGenerator` in `DefaultHtmlGenerator.cs` which can set the stage to allow developers to plugin with their own implementation if needed?

Few examples would be using jQuery validator's native unobtrusive validation, and bootstrap validators.

Is something in the pipeline towards this? 

I can take a shot at sending a PR if this generates enough interest.

**Comment by rynowak** [comment]
@mrchief - take a look here at: https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/Validation (everything with 'client' in the name).

You can replace/add your own `IClientModelValidatorProvider` or `IClientModelValidator` implementations. That however is still based on the code in `UnobtrusiveValidationAttributesGenerator` which ultimately writes out the HTML, so if that's tripping you up, then we'd need to do more.

Would what we have today be sufficient for your needs? What part of the behavior do you need to customize?

**Comment by dougbu** [comment]
@mrchief in addition to @rynowak's suggestions, the single call to `UnobtrusiveValidationAttributesGenerator.GetValidationAttributes()` is in a `virtual` method. Your application could add a `DefaultHtmlGenerator` subclass to DI, overriding `GetValidationAttributes()`. This may also suffice for your scenario.  As @rynowak asked, what do you need to customize?

**Comment by mrchief** [comment]
@rynowak Like you said, its the data attributes that gets generated by `UnobtrusiveValidationAttributesGenerator`. It currently writes `data-val-` and there is no way to override that.

As an example, jQuery validation native requires `data-msg-` and `data-rule-` attributes. Now its possible to write your own HTML Helper extensions which generate these for you but I feel that there is no reason for MVC to be tied to one specific implementation (aside from the fact that your markup contains extra attributes which are really not being used or needed).

I see many examples where people have ditched unobtrusive validation _entirely_ since it modifies jQuery validation so much that its very hard to implement your own custom stuff. 

Unobtrusive validation could be updated to address these concerns but then, I was thinking why even bother doing that if we can provide a way to allow people to plugin with their own?

@dougbu: `GetValidationAttributes()` does a bit more than just calling `UnobtrusiveValidationAttributesGenerator.GetValidationAttributes()`. Sure I can copy paste the code today and swap out `UnobtrusiveValidationAttributesGenerator` with my own, but then I run the risk of falling out of line with the core, something I don't prefer.

Again, with so many great things happening with ASP.NET, I don't want people ditching an highly useful feature just because it isn't flexible enough. Makes sense?

**Comment by rynowak** [comment]
@mrchief - totally makes sense. Just wanted a little more clarity on what you were looking to customize :+1:

**Comment by matthewvalimaki** [comment]
@dougbu using RC1 how would I do "Your application could add a DefaultHtmlGenerator subclass to DI"? I did try to look up some documentation or examples for this but failed.

Reason why I want to do this is exactly the same what @mrchief said about `data-val-`. Instead of using jQuery I want to use Angular and I would like to keep my html as clean as possible.

A side note to the actual request:
`GetValidationAttributes` should make a call to a another virtual method which then calls `UnobtrusiveValidationAttributesGenerator.GetValidationAttributes(clientRules)` to prevent having to copy whole `GetValidationAttributes` just to modify one line of code.

**Comment by dougbu** [comment]
An example of how to override the `IHtmlGenerator` implementation in DI:
``` c#
    public void ConfigureServices(IServiceCollection services)
    {
        // Add MVC services to the services container
        services.AddMvc();

        services.AddSingleton<IHtmlGenerator, CustomHtmlGenerator>();
    }
    ...
    private class CustomHtmlGenerator : DefaultHtmlGenerator
    {
        public CustomHtmlGenerator(
            IAntiforgery antiforgery,
            IOptions<MvcViewOptions> optionsAccessor,
            IModelMetadataProvider metadataProvider,
            IUrlHelperFactory urlHelperFactory,
            HtmlEncoder htmlEncoder,
            ClientValidatorCache clientValidatorCache)
        : base(antiforgery, optionsAccessor, metadataProvider, urlHelperFactory, htmlEncoder, clientValidatorCache)
        {
        }
    }
```

In addition HTML generator for Unobtrusive validation has changed significantly in RC2. The `IClientModelValidator` implementations now add the required attributes directly. To use another validation system, I'd recommend overriding the following
``` c#
    protected override void AddValidationAttributes(
        ViewContext viewContext,
        TagBuilder tagBuilder,
        ModelExplorer modelExplorer,
        string expression)
    {
        base.AddValidationAttributes(viewContext, tagBuilder, modelExplorer, expression);

        // Map attribute names and values as you wish...
    }
```

**Comment by mrchief** [comment]
:+1:

**Comment by diryboy** [comment]
Thanks for the info. This thread is somewhat hard to find from the search engine. Most results are about custom validators for jquery.

I'm trying to get MVC emit the unobtrusive validator attributes defined in Metro UI CSS, like the first example shown in [their documentation](http://metroui.org.ua/validator.html). Looks like I could just swap [`StringLengthAttributeAdapter`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/StringLengthAttributeAdapter.cs) with my class with `AddValidation` overridden? But the `Internal` namespace scares me. Is there a better way to do this?

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
