### ISSUE TITLE
Add a Controller.Json(object, JsonSerializerSettings) overload

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Mvc#2506]
Right now JSON settings can only be defined once at an application level on the JsonOutputFormatter. It would be useful to be able to pass a JsonSerializerSettings argument to the Controller.Json method to override the JSON settings on a per result basis, e.g. a developer might want indented JSON, or to use a specific JsonConverter, for only one action in their application.

Current method:
https://github.com/aspnet/Mvc/blob/7e623258c02d8414422605679dc58f260574538b/src/Microsoft.AspNet.Mvc.Core/Controller.cs#L383-L400

**Comment by davidfowl** [comment]
That migh actually be pretty nice

**Comment by rynowak** [comment]
Would be pretty easy for us to add. WebAPI had something similar:
```
        protected internal JsonResult<T> Json<T>(T content, JsonSerializerSettings serializerSettings)
```

**Comment by henkmollema** [comment]
Using `JsonSerializerSettings` will create a hard dependency on Json.NET, which is not desired I guess.

**Comment by JamesNK** [comment]
The underlying JSON formatter doesn't have to be Json.NET - another serializer can read settings from JsonSerializerSettings.

**Comment by henkmollema** [comment]
@JamesNK good point. Was just curious because ASP.NET 5 is all about abstractions and loose couplin. Figured `using Newtonsoft.Json` in the `Controller` class might be a bit odd.

**Comment by rynowak** [comment]
@henkmollema - we're pretty fully-bought into Json.Net at this point. You could use another serializer with MVC/WebAPI if you wanted to, but we don't plan to show an experience where Json.Net isn't a required dependency.

**Comment by henkmollema** [comment]
@rynowak I see, thanks! :smile:

**Comment by nicholasyin** [comment]
Was this only added to Core, and not to MVC 5?

**Comment by ajaybhargavb** [comment]
@nicholasyin yes.
