### ISSUE TITLE
Problem with List<> in HttpPost view.

### ISSUE THREAD

**Issue by maxbundchen** [aspnet/Mvc#2509]
The code from http://forums.asp.net/post/5904623.aspx illustrates a problem using List<> and any Razor html helper in a specific situation when a List<> is posted, changed and passed to the view again.

**Comment by danroth27** [comment]
@maxbundchen What version of MVC are you seeing this on? Could you please also show us the exact output you are seeing and what you expect to be produced?

**Comment by dougbu** [comment]
@maxbundchen looks like you want to prevent the view reading from the `ModelState`. The HTML helpers for inputs (e.g. `EditorFor()` and `TextBoxFor()`) always check `ModelState` first to ensure values round-trip correctly.

To override that behaviour, I recommend executing the following near the top of your `IntegerList(IntegerListViewModel integerListViewModel)` action:
``` c#
  for (var i = 0; i < integerListViewModel.List.Count; i++)
  {
    ModelState.Remove($"List[{ i }]");
  }
```

(If you deal separately with errors, do that before clearing those `ModelState` entries.)

**Comment by maxbundchen** [comment]
@danroth27 I'm using the current stable version (MVC 5 with .Net 4.5.1 and VS 2013). I made a little sample when you can see the problem http://1drv.ms/1ES2lRQ.

@dougbu I never figure out the ModelState could be the problem. I will make some tests, but if it's the case, the "Model" in the view loses for the ModelState, if I can say that, and that could be a potential problem in other situations.

**Comment by dougbu** [comment]
> could be a potential problem in other situations

Giving `ModelState` (the original data from the form) precedence is by design. To do otherwise would mean users are not given an opportunity to make small changes and resubmit.

I provided a workaround for your unusual scenario.

**Comment by maxbundchen** [comment]
@dougbu your workaround works fine, thanks. I found lots of topics like this one before coming here. Not sure if the topic should be closed, so I will leave to you closing it.
