### ISSUE TITLE
Pkg rename: Microsoft.AspNet.Mvc.Common -> Microsoft.AspNet.Mvc.Sources

### ISSUE THREAD

**Issue by muratg** [aspnet/Mvc#2511]

**Comment by rynowak** [comment]
We should just remove this instead, we have a better way of doing common/shared packages now for the things that are actually valuable.

**Comment by troydai** [comment]
@muratg @rynowak @pranavkm 
All right, I talked to @pranavkm. Looks like MVC team plan to remove this package. So I'm not going to touch it. I'll close this issue then.
