### ISSUE TITLE
'#' symbol dissapears from attributes when TagHelpers enabled

### ISSUE THREAD

**Issue by Inok** [aspnet/Mvc#2521]
Example:
```html
<form action="@Url.Action(...)" method="POST" role="form" class="form-horizontal"
              data-ajax="true" data-ajax-mode="replace-with" data-ajax-update="#@panelName">
...
</form>
```
TagHelpers actually not used at this form, just enabled at _GlobalImport.

Result:
```html
<form ... data-ajax-update="name">
```
As you can see, '#' symbol dissapears from first position of **data-ajax-update** attribite.

When I disable TagHelpers, '#' came back. Also @tagHelperPrefix helps to avoid this issue.

data-ajax-update="@('#' + panelName)" helps too.

**Comment by dougbu** [comment]
You are using tag helpers in this scenario.  The `<form/>` tag helper matches all `<form/>` elements, enabling addition of an anti-forgery token even when the `action` is explicit.

Another workaround would be `<!form action="@Url.Action(...)" method="POST" ...>` in the Razor source.

That said, the `#` should not be lost when tag helpers are enabled.

**Comment by rynowak** [comment]
@NTaylorMullen can elaborate further, but didn't we make a change to have taghelpers ignore `data-` attributes completely? 

My guess is that this is fixed in current beta5 builds and that this is a manifestation of aspnet/razor#342

**Comment by NTaylorMullen** [comment]
@rynowak You're absolutely correct, it is indeed a manifestation. I'm going to reopen aspnet/Razor#342 because it seems that the `data-` issue also occurs with unbound `TagHelper` attributes. Thank you @Inok for reporting this.
