### ISSUE TITLE
Improve unit testability for model binding

### ISSUE THREAD

**Issue by bojanrajkovic** [aspnet/Mvc#2523]
Right now, it's not obvious how or if you even can unit test that model binding produces the desired model errors or lack thereof. I've attempted to do it using code that looks somewhat like the following:

```
var controller = new FooController(...) {
    ActionContext = new ActionContext(mockHttpContext, new RouteData(), new ActionDescriptor()),
    BindingContext = new ActionBindingContext(),
    MetadataProvider = new EmptyModelMetadataProvider(),
};
 
controller.TryValidateModel(model);
```

but that throws exceptions in TryValidateModel(Object model, string prefix). 

I suspect that `EmptyModelMetadataProvider` is the problem here, but no `IModelMetadataProvider` is exposed that doesn't require reconstructing the entire chain that's set up by MVC internally (`DefaultModelMetadataProvider` sends you on a massive yak shaving expedition to find all the right instances of things).

**Comment by dougbu** [comment]
@bojanrajkovic Assuming your request is about unit testing a custom model binder or similar extension, you may want to glance at our model binding unit tests e.g. https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.Core.Test/ModelBinding/CompositeModelBinderTest.cs  We use `EmptyModelMetadataProvider` in at least some of those.

Alternatively your example is perhaps a bit more like an integration test. https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.IntegrationTests/MutableObjectModelBinderIntegrationTest.cs and other test classes in that directory fit that category.

The final possibility would be to imitate our functional tests, which include the full request / response pipeline e.g. https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.FunctionalTests/ModelBindingFromQueryTest.cs and https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ModelBindingWebSite

**Comment by bojanrajkovic** [comment]
I think the trick is that what we want to test falls in between the model binding unit tests and the integration/functional tests, in that we're trying to get the model binding infrastructure to "run," without making a full request/response chain.

I think in this case, the best is for us to split the test into two pieces -- a unit test that simply adds an error to the ModelStateDictionary, and a functional test that sets up the server and runs the full request/response pipeline. :)

It's probably fine to close this issue, unless this middle ground is a case you still want to support.

**Comment by harshgMSFT** [comment]
>in that we're trying to get the model binding infrastructure to "run," without making a full request/response chain.

@bojanrajkovic if you closely look at the integration tests pointed by @dougbu, they do operate without needing to set the response pipeline. They do still configure request as that is the place you fetch data from. They do not have to host a site which a functional test would. So in essence they are between unit and functional test and you should be able to write one pretty easily.
