### ISSUE TITLE
Form Collection Model Binder should not fall back to copying the form values from FormCollection

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#2527]
This should get us one step closer to removing MVC's dependency on the concrete implementations of the HTTP abstractions. When fixing this bug, need to check if we can switch to depend just on the HTTP `.Abstractions` package.

**Comment by Eilon** [comment]
@rynowak can you hold on to this and deal with it appropriately?

**Comment by rynowak** [comment]
Yeah!

I'll say again what I've said the last few times this has come up:

> We can't remove this reference because we create an empty `FormCollection` when there's nothing to bind for consistency with other collections. 

There's some code cleanup to do here nonetheless. We all agree on removing support for `FormCollection` directly in user-code and the fallback to copy values.

**Comment by rynowak** [comment]
Resolution here is to remove the fallback.

For the case where there's no form-data, MVC will provide an empty form collection.

**Comment by rynowak** [comment]
1596cd9422ff05955fc1b26680682c2ab6805a39
