### ISSUE TITLE
Problem is running sample projects 

### ISSUE THREAD

**Issue by hanu412** [aspnet/Mvc#2533]
I'd taken a copy of the latest MVC-Dev project. I tried to run the MVCSample.Web project in the Visual Studio 2015 RC. I am getting the following error. 

I had checked the dnx and it seems to be good. I did try restoring the packages couple of times,but it seems to be a different issue. 

Ironically,if I create a File-NewProject and create a ASP.NET5 application,it is running fine. Did anyone encounter this problem while running the samples

Do I need to make any configuration changes?

![dnx](https://cloud.githubusercontent.com/assets/11040896/7551492/cfe03108-f6a7-11e4-8a6e-95f2bd7d50fc.JPG)

![errir](https://cloud.githubusercontent.com/assets/11040896/7551489/c7998efe-f6a7-11e4-83a1-b429208acc97.JPG)

**Comment by davidfowl** [comment]
The samples require beta5 not beta4. Update your dnx if you want to run samples from the latest Mvc branch

**Comment by hanu412** [comment]
I did that. Still unable to get it work. I updated it to v 1.0.0-beta5-11744. I am on windows machine. 
Do I need to make any other changes/upgrades?

**Comment by davidfowl** [comment]
After you updated did you close and open the solution.

**Comment by hanu412** [comment]
Initially I just updated it and rebuilt the solution. After I saw your message,I closed it and opened it and ran. It did not work. Then I noticed that launchSettings.json file was still looking for the old sdk version. Then I manually updated it to the beta5 version and ran the solution. Now I am encountering a new error saying references are missing. 

![newerror](https://cloud.githubusercontent.com/assets/11040896/7551602/40a95da2-f6ac-11e4-9f04-571369518bf2.JPG)

**Comment by davidfowl** [comment]
Looks like a compilation error. Run restore on those projects.

**Comment by hanu412** [comment]
Yes I did it. It worked. Now I am able to run the project.

**Comment by hanu412** [comment]
Solution : Updated the dnx to the latest version. Restored all the packages. Built the solution and boom,the errors went away.
