### ISSUE TITLE
AuthorizeFilter sets null Identity

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Mvc#2534]
I think you have a bug here:

https://github.com/aspnet/Mvc/blob/64e726d2b26422c5452475627e4afaba307edec3/src/Microsoft.AspNet.Mvc.Core/Filters/AuthorizeFilter.cs#L35-L47

This will result in a null ClaimsPrincipal.Identity when the user is not authenticated.

You rather want to create an Identity that is not authenticated.

**Comment by danroth27** [comment]
@blowdart Can you take a look at this?

**Comment by blowdart** [comment]
I already pinged @HaoK.

**Comment by HaoK** [comment]
1ea1cc43387850606d0799b930de66dd8ae838a2

**Comment by vcsjones** [comment]
Is the milestone for this still beta5?

**Comment by danroth27** [comment]
Yup, the fix is in beta5.
