### ISSUE TITLE
Test failure in Microsoft.AspNet.Mvc.Core.Tests

### ISSUE THREAD

**Issue by Alxandr** [aspnet/Mvc#2535]
When trying to build Mvc on my machine, I get a test-failure in `Microsoft.AspNet.Mvc.Core.Tests`. By the looks of it, my guess it's a time-zone related bug, but I haven't looked much into what's causing it.

The test results are as following:

![image](https://cloud.githubusercontent.com/assets/112334/7551698/8f4ee83c-f693-11e4-9d92-d640271ebb45.png)

**Comment by dougbu** [comment]
@Alxandr interested in doing a quick PR?  Looks like the `DateTime` object created [here](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.Core.Test/SessionStateTempDataProviderTest.cs#L189) should either be a `DateTimeOffset` or have `DateTimeKind.Utc`.

**Comment by Alxandr** [comment]
Sorry, but I'm quite fed up with trying to get the Mvc repo to work at the moment. Stuff that works locally doesn't work on the CI and vice versa, making testing and fixing stuff way more painful and time consuming than it really should be.
