### ISSUE TITLE
"controller", "action" and "area" strings should be defined in an Enum

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Mvc#2537]
While it is unlikely these names are to ever change, there are many places where the strings "controller", "action" and "area" are used. To make the code more maintainable, these strings should be moved to an Enum.

At the moment there is no central Enum to use, which means that there are places within the API where programmers have taken it into their own hands to define these values, such as in the following class:
- https://github.com/aspnet/Mvc/blob/64e726d2b26422c5452475627e4afaba307edec3/src/Microsoft.AspNet.Mvc.Razor/RazorViewEngine.cs

Therefore, the Enum should have public visibility allowing for others to make use of it.

The following are some examples of other locations which would benefit from this change:
- https://github.com/aspnet/Mvc/blob/64e726d2b26422c5452475627e4afaba307edec3/test/Microsoft.AspNet.Mvc.Core.Test/KnownRouteValueConstraintTests.cs (multiple places)
- https://github.com/aspnet/Mvc/blob/64e726d2b26422c5452475627e4afaba307edec3/src/Microsoft.AspNet.Mvc.Core/UrlHelper.cs (multiple places)
- https://github.com/aspnet/Mvc/blob/320507604a7045110ebf0b64f669cccddb6d9123/src/Microsoft.AspNet.Mvc.WebApiCompatShim/OverloadActionConstraint.cs (multiple places)

There are a number of ASP.NET repositories which will benefit from this change and should be updated accordingly to use the new Enum.

**Comment by yishaigalatzer** [comment]
If anything should use const strings and no enum

**Comment by Eilon** [comment]
I think it'll be more work to change this than to just keep the code where it is so I'm not sure it's really worthwhile. The keys pretty much can't change because it would be a breaking change from the last 7 years of MVC...
