### ISSUE TITLE
JsonInputFormatter and JsonOutputFormatter consistancy

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Mvc#2538]
[JsonInputFormatter](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Formatters/JsonInputFormatter.cs)
[JsonOutputFormatter](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Formatters/JsonOutputFormatter.cs)

- On JsonInputFormatter the CreateJsonReader and CreateJsonSerializer method are public and virtual.
- On JsonOutputFormatter the CreateJsonWriter and CreateJsonSerializer methods are private.

Should these methods be consistent between input and output formatters?

- JsonOutputFormatter implements IJsonOutputFormatter
- JsonInputFormatter doesn't implement an interface.

Is IJsonOutputFormatter required? It doesn't have any methods and is only used in one place.

**Comment by danroth27** [comment]
Let's deal with the `IJsonOutputFormatter` issue separately: https://github.com/aspnet/Mvc/issues/2715.

We should go ahead and make CreateJsonWriter and CreateJsonSerializer public.

**Comment by ajaybhargavb** [comment]
4a4b8ec87e56db88c1192f33dc755ecd67d85cd4
