### ISSUE TITLE
Changes to ModelMetadata provided by a ModelMetadataDetailsProvider are sometimes lost if the model property is a Nullable<T>

### ISSUE THREAD

**Issue by emisaacson** [aspnet/Mvc#2539]
In one of my projects I have a registered `IDisplayMetadataProvider` that examines the attributes on a model's properties and sets values in `ModelMetadata.AdditionalValues` as necessary. I find that if:

* the model property in question is a `Nullable<T>` AND
* the default value of the property is a value other than null

then the customizations to ModelMetadata are lost by the time the view is rendered.

A minimal project to reproduce the issue is here: https://github.com/emisaacson/MetadataProviderExample

I find with this change I get the expected result (`AdditionalValues` is populated when rendering the view): https://github.com/aspnet/Mvc/compare/dev...emisaacson:vd-type-checking

**Comment by dougbu** [comment]
f10a071
