### ISSUE TITLE
Change the tag helpers `FileVersion` property to something clearer

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#2540]
We have a few tag helpers (`Link`, `Script`, and the upcoming `Image`) that have a `FileVersion` property that indicates whether to add a "version" to the URL to help with cache busting.

The property name is a bit confusing: it looks like *it is* a file version, as opposed to saying whether to *append* a file version.

I recommend changing the property to be `AppendVersion` or similar because that'll be a lot clearer about what it does.

**Comment by danroth27** [comment]
@DamianEdwards thoughts?

**Comment by DamianEdwards** [comment]
Sure

**Comment by dpaquette** [comment]
Any objection to me tackling this one on the weekend?

**Comment by Eilon** [comment]
Yeah that would be great. Let's settle on a name. Here are a few ideas:

* `AppendFileVersion` / `AddFileVersion`
* `AppendVersion` / `AddVersion`
* `AppendFileHash` / `AddFileHash`
* `AppendHash` / `AddHash`
* `CacheBust`

I do kind of like my original suggestion of `AppendVersion` because it's concise and reasonably clear about what it does.

Thoughts?

**Comment by danroth27** [comment]
I can live with AppendVersion. I also like AddFileVersion.

**Comment by dpaquette** [comment]
I like AppendVersion

**Comment by dougbu** [comment]
Is this about just the property name?  Note that's irrelevant in every scenario except unit testing.  The _attribute_ name (what users see in the Razor source) is currently `asp-file-version`.

If we're going to change the attribute as well, would the name there be `asp-append-version`?

**Comment by danroth27** [comment]
Yup.

**Comment by Eilon** [comment]
@dougbu yes it's just the property name and yes we'd rename the tag helper attribute name.

Sounds like everyone wants to go with `AppendVersion`!

**Comment by DamianEdwards** [comment]
:+1:

**Comment by dougbu** [comment]
3fe0490

**Comment by Daniel15** [comment]
The web app template in Visual Studio still uses `asp-file-version`, looks like it wasn't updated.

**Comment by danroth27** [comment]
https://github.com/aspnet/Templates/issues/142

**Comment by Daniel15** [comment]
I get a 404 on that link; is it a private repo?

**Comment by danroth27** [comment]
Yeah, sorry about that. Removing the link to avoid further confusion.
