### ISSUE TITLE
Use custom stream writer for Xml output formatters

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#2541]
Follow up to https://github.com/aspnet/Mvc/issues/2496

Currently Xml output formatters ([DCS](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Xml/XmlDataContractSerializerOutputFormatter.cs#L161) and [XmlSerializer](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Xml/XmlSerializerOutputFormatter.cs#L136)) do not use the custom stream writer.

XmlWriter however provides an [overload](https://msdn.microsoft.com/en-us/library/ms162620%28v=vs.110%29.aspx) which takes in a text writer. We should be able to provide the custom stream writer that we built as part of https://github.com/aspnet/Mvc/issues/2496

**Comment by rynowak** [comment]
This should probably be generalized to 'do a find and replace for non-disposable stream'. There's a bunch of functional tests where the old pattern was used, and we want as much as is feasible our tests to reflect our recommendation for a user writing the code.
