### ISSUE TITLE
InputFormatters should work with the ModelState passed in to TryUpdateModel 

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2546]
See: https://github.com/aspnet/Mvc/pull/2543

There are overloads of `TryUpdateModel` (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ParameterBinding/ModelBindingHelper.cs#L43) that allow you to pass in a `ModelStateDictionary`. These can't work correctly with formatters, which always use `ActionContext.ModelState`.

The change in #2543 **may** have fixed this issue, but we need to add tests and fully investigate.

**Comment by danroth27** [comment]
@rynowak Let us know if you think we need to investigate this for beta5.

**Comment by rynowak** [comment]
This is really an investigate/add-tests should be easy to do.

**Comment by rynowak** [comment]
Did some investigating, and our existing tests verify this well-enough. This was fixed as part of 39fe063aeec41bec2d93eaea3cfcc66c2b8c493d
