### ISSUE TITLE
DI:ServiceProvider holder

### ISSUE THREAD

**Issue by Artur2** [aspnet/Mvc#2548]
All we know about configuring services at startup.
But how can i access ServiceProvider or something like this outside of controller.
For example in Domain Model 

    public class Entity 
    {

       public void DoSomething()
       {
           var someService = ServiceProviderHolder.GetService<ISomeService>();
       }
    }

How can i access to service provider like this ?
Because type in DI ServiceProvider is internal

Добрый день.
Возник вопрос по поводу DI, 
я так и не смог найти одного общего DI контейнера, ServiceProvider в DI помечен как internal,
При этом он копирует все зависимости из более низкого уровня(CallContextServiceLocator)
Как мне получить доступ ко всем зависимостям ?

**Comment by danroth27** [comment]
Instead of relying on statics we recommend passing through the services you need when creating your Entity.

**Comment by henkmollema** [comment]
You can use the `CallContextServiceLocator` to locate the service provider:

```csharp
var someService = CallContextServiceLocator.Locator.ServiceProvider.GetService<ISomeService>();
```

It exists in the `Microsoft.Framework.Runtime.Infrastructure` namespace. See the [dnx](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Abstractions/CallContextServiceLocator.cs) repo.

**Comment by davidfowl** [comment]
Definitely don't use that. Avoid statics.

**Comment by henkmollema** [comment]
I agree, it's very ugly. Is there even any good use case?

**Comment by Artur2** [comment]
@danroth27 , @henkmollema , @davidfowl thanks for answer :D
