### ISSUE TITLE
Protect against null IContractResolver on JsonPatchDocumentOfT

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Mvc#2560]
While working on a pull request I caused many of the JSON patch related tests to fail with null reference exceptions. I fixed the errors in my PR by not assigning null but I noticed that JsonPatchDocumentOfT doesn't have any `[NotNull]` checks on its ContractResolver property and constructor arguments.

https://github.com/aspnet/Mvc/blob/64e726d2b26422c5452475627e4afaba307edec3/src/Microsoft.AspNet.JsonPatch/JsonPatchDocumentOfT.cs

**Comment by kirthik** [comment]
merged 38748b54eb7ef8e7cba2365d0621fcf4826dda4b
