### ISSUE TITLE
Add .gitignore to default project scaffold

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Mvc#2571]
Would be nice if projects shipped with a best-practice `.gitignore` file.

**Comment by Eilon** [comment]
@atrauzzi can you log this in the https://github.com/aspnet/Tooling/issues repo? That's where we track tooling/template issues. Thanks!

**Comment by atrauzzi** [comment]
Done! https://github.com/aspnet/Tooling/issues/74
