### ISSUE TITLE
AuthorizeAttribute with Groups for Group-Based Permissions

### ISSUE THREAD

**Issue by mojtabakaviani** [aspnet/Mvc#2572]
Next version of Asp.Net Identity will be Implementing ['Group Based' Permissions Management](https://github.com/aspnet/Identity/issues/184) for large numbers of users please add groups named parameters to AuthorizeAttribute that easy authorize groups every where.

**Comment by blowdart** [comment]
You can already authorize by roles. That should be sufficient for your needs, groups would be limited to identity administration. If it's not please file an issue in the security repo, where authorization lives.
