### ISSUE TITLE
Model Display Names

### ISSUE THREAD

**Issue by dgee2** [aspnet/Mvc#2577]
Razor does not pick up the DisplayName attribute when calling @Html.DisplayNameFor(x=>x.someValue).

The first example works but the second would just display "someValue".
```C#
[Display(Name = "Hello World!")]
public int someValue { get; set; }
```
```C#
[DisplayName("Hello World!")]
public int someValue { get; set; }
```

6.0.0-beta4 being used.

**Comment by dougbu** [comment]
@dgee2 the `[DisplayName]` attribute does not exist in .NET Core. To avoid inconsistencies between frameworks, MVC 6 does not use this attribute at all. Please use `[Display]`.

**Comment by dgee2** [comment]
Thanks, I hoped that was the case.
