### ISSUE TITLE
Remove dependency of @inject on [Activate]

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2582]
Right now `@inject` creates a public property that's decorated with `[Activate]`. Given the recent push back on how `[Activate]` isn't the best feature we need to bullet proof the Razor code generation to no longer depend on it.

Assigning to beta5 and to myself. Talked to @DamianEdwards

**Comment by pranavkm** [comment]
More context here: https://github.com/aspnet/Mvc/issues/2151#issuecomment-99328254

**Comment by rynowak** [comment]
92dbd8923b3adc22777b7a0a0e767e8997faf62d
