### ISSUE TITLE
If you check out a project and there is no webroot...who makes it?

### ISSUE THREAD

**Issue by shanselman** [aspnet/Mvc#2585]
If you check out a project and there is no webroot...who makes it? VS fails with this. Someone should make it, and not force us to check in placeholders.

(also, not sure when this bug goes) @danroth27 

```` ---------------------------
```` Microsoft Visual Studio
```` ---------------------------
```` The 'webroot' property value 'wwwroot' in the project.json file points to a folder which doesn't exist.
```` ---------------------------
```` OK   
```` ---------------------------

**Comment by danroth27** [comment]
@davidfowl @sayedihashimi Do we want DNX to auto create the webroot folder if it doesn't exist? I'm guessing not. Instead, could VS detect this situation and offer to create the folder for you?

**Comment by danroth27** [comment]
FIled https://github.com/aspnet/Hosting/issues/278 to have the runtime provide a better error message.

**Comment by davidfowl** [comment]
No, we don't. We could put some index.html file in the templates to help mitigate the problem.

**Comment by sayedihashimi** [comment]
In this case what's the command line experience? Visual Studio doesn't usually just create folders in the project directory, but its something we can consider.

Scott, can you expand on why the folder doesn't exist? Is it because it's an empty project and no files under wwwroot means the folder isn't checked in?

**Comment by danroth27** [comment]
On the CLI you get an error saying that the webroot folder doesn't exist.

In tooling we could ask the user if they want to create the folder.

**Comment by sayedihashimi** [comment]
How often are people going to run into this? If its low and we have a good error message perhaps that is good enough?

**Comment by danroth27** [comment]
It often happens because you have a project checked into git that has an empty wwwroot folder, which git then ignores.

**Comment by shanselman** [comment]
Exactly. If there isn't a placeholder file then there's no folder. If you
git clone something then you get an error. This is going to happen all the
time. If webroot is required then it needs to get created by whatever
builds the project.

On Wed, May 20, 2015 at 4:19 PM, Daniel Roth <notifications@github.com>
wrote:

> It often happens because you have a project checked into git that has an
> empty wwwroot folder, which git then ignores.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet/Mvc/issues/2585#issuecomment-104069643>.
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by sayedihashimi** [comment]
So do we need a dialog to tell the user? I think we could just create the missing folder right? Also for cmd line case shouldn't we update the gulp file to create the folder as needed?

**Comment by sayedihashimi** [comment]
Opened an internal bug to track this 1176458.

**Comment by danroth27** [comment]
Tracking this as a tooling issue.
