### ISSUE TITLE
nameof cannot be used for Controller names in methods like RedirectToAction

### ISSUE THREAD

**Issue by rustd** [aspnet/Mvc#2586]
I wanted to use nameof in our templates for controller names and actions. I can use them fine for action names but when I try to use it for Controller names, I get runtime errors about routes not being found,

The following code results in /HomeController/Index instead of /Home/Index
```C#
RedirectToAction(nameof(HomeController.Index), nameof(HomeController))
```

**Comment by rustd** [comment]
@DamianEdwards @Eilon this was for Beta5 for the templates. it would be great if we can get this in. not sure though

**Comment by pranavkm** [comment]
One possible suggestion was to remove the `Controller` suffix in the templates:

`namespace MyApp.Controllers
{
    public class Home : Controller
    {
       public void Index()
       {
       }
   }
}
```

This way we don't have to mess with strings when resolving controller names.

**Comment by danroth27** [comment]
No plans to change anything here.
