### ISSUE TITLE
What is alternative of RouteFactoryAttribute in MVC 6?

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Mvc#2587]
I need to have a version-ed route with some constraints. I did it with a route drive from RouteFactoryAttribute in MVC5 . It seems RouteFactoryAttribute not exists in MVC6.
Thanks to any right point.

**Comment by rynowak** [comment]
Would you mind posting a sample of what your code is doing? There are a number of different ways to approach this and I want to make sure to give the most pertinent advice.

## Building Blocks
In general there are 3 basic building blocks you want to be aware of:
`IActionHttpMethodProvider` - Lets you specify what HTTP methods apply to an action.
`IActionConstraintFactory` - Lets you specify an action constraint for an action (more on that later)
`IRouteTemplateProvider` - Lets you specify the route-template for an action

If your constraint implementations can easily be specified using inline-constraint syntax, then you'll likely only need `IRouteTemplateProvider`.

## About `IActionConstraints`

`IActionConstraint` might sound like a new thing, but it's just a more advanced version of `ActionMethodSelectorAttribute` from MVC5. It's an extensibility point that lets you see what actions are candidates, and then determine which should be selected.

Also, an action *with* an `IActionConstraint` is considered **better** than one without. This is useful for when you want *default* behavior on an action. Eg. Always choose this action when there isn't a more specific match.

## Putting it together

You might also need `IControllerModelConvention`/`IActionModelConvention` if you want to dynamically configure routes and other things. This gives you a mutable data-model for your actions and controllers that you can manipulate - this is way we envision some of the more complex and dynamic `RouteFactoryAttribute` implementions would be implemented.

You can register these in `options.Conventions` in startup code or implement them as attributes.

## Sample

Take a look at a sample/test that we built a while back for versioning. This uses a query parameter, but it would be possible to adapt the approach to a number of strategies.

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/VersioningWebSite

**Comment by mikeandersun** [comment]
Thanks a lot for elaboration description. You open a world to me :+1: 
I need to study again about Microsoft breaking changes :) 
I hope MVC6 will be the last breaking change on Microsoft developing stack.
