### ISSUE TITLE
Start with MVC 6

### ISSUE THREAD

**Issue by ricardopolo** [aspnet/Mvc#2588]
If you would start a project today would you use MVC 6 or MVC 5?

Do you think MVC 6 is stable enough to start and when released final version upgrade? O should stick with MVC 5?

I think that when the project goes to production should be public the final version of MVC6.

Regards

**Comment by danroth27** [comment]
ASP.NET 5 and MVC 6 are still both in preview so they are not officially supported yet and they are generally not ready for production. You can use them in production, but if you do you will need to test your application heavily. We are also still making significant changes to these frameworks so there is no guarantee that your app written against the current preview will work with the final released bits. 

So, if you need something that is production ready *soon* then you are probably better off going with MVC 5.

**Comment by danicomas** [comment]
I do the same question today. When it will be released @danroth27 ? Other thing my intention is to do the following:

- Create DataBase
- Execute cmd with all the tables
- CRUD generated

What is the best way to do this today? Yeoman, MVC 5? Exist some template? Regards

**Comment by danicomas** [comment]
@danroth27 with yeoman I can not do this because I want to get data base and generate the scaffold.

**Comment by danicomas** [comment]
One more thing now in MVC 5 is possible run a cmd scaffold? I would like to create a .bat with all my scaffold instructions similar than MVC 6.

**Comment by danicomas** [comment]
@danroth27 MVC 6 only works with Entity First model?

**Comment by Eilon** [comment]
@danicomas the ASP.NET roadmap and dates are available here: https://github.com/aspnet/Home/wiki/Roadmap

We are working on command line scaffolding. Right now there are the Yeoman scaffolders, but they are not yet finished.

MVC 6 can work with any model. Entity Framework 7 supports only a "Code First" model, but other data access technologies could certainly support other models (though I'm not aware of any).
