### ISSUE TITLE
Rename ~/Views/Shared to ~/Views/_Shared

### ISSUE THREAD

**Issue by jkodroff** [aspnet/Mvc#2589]
So `~/Views/Shared` is a special folder.  It doesn't really go with the other `~/Views/SomeController` folders.  With this in mind, what do we think of renaming it to `~/Views/_Shared`?  The `_Name` convention is popular for non-conventional views (e.g. `_Layout`), and it would push the folder alphabetically to the top of the listing.

Alternatively, we could make [feature folders](http://timgthomas.com/2013/10/feature-folders-in-asp-net-mvc/) the default project structure as I think this will encourage better development practices by encouraging the developer to think about vertical slices of functionality centered around features.

**Comment by danroth27** [comment]
We are maintaining the existing folder name conventions from MVC 5 for compatibility reasons.
