### ISSUE TITLE
Authorize attribute should use same principal merging logic as Authentication

### ISSUE THREAD

**Issue by HaoK** [aspnet/Mvc#2590]
AuthorizeFilter is building a new claims principal as part of authorization, its not using the same logic for merging the principals from each auth middleware that happens during normal authentication.

cc @blowdart

**Comment by danroth27** [comment]
@blowdart How bad is the user impact? Does this need to be fixed for beta5?

**Comment by blowdart** [comment]
It's @HaoK's issue, ask him. I don't know how different the logic is.

**Comment by HaoK** [comment]
I don't think it's that bad so I can do it for beta 6 if no one has run into issues yet. It is an easy fix either way. Basically remove a bunch of the code and call SecurityHelper.AddUserPrincipal.

**Comment by danroth27** [comment]
@HaoK What issues would folks potentially run into if we don't fix this for beta5?

**Comment by HaoK** [comment]
The AddUserPrincipal helper we just fixed recently to promote "IsAuthenticated" identities to the top, so user code which does User.Identity.IsAuthenticated will return true if any user identity is authenticated.  The MVC AuthorizeFilter doesn't have that, so potentially will run into issues if they configure multiple authentication schemes that return unauthenticated identities (unlikely in general, but possible)

**Comment by Eilon** [comment]
@HaoK can you close this?

**Comment by HaoK** [comment]
Actually doesn't look like I made this change in the auth changes I made for MVC, and unfortunately doesn't look like the helper is in the exact shape we need to use for MVC, I'll open a PR in security to make it useable for MVC
