### ISSUE TITLE
Automatically fetch dnx for project

### ISSUE THREAD

**Issue by cwoolum** [aspnet/Mvc#2602]
I'm not sure if this alread exists but it would be nice to be able to run dnvm install in the root of a solution and it just fetch the dnx based on the sdk version in the global.json. 

I tried running this but it wanted a specific version in the CLI. I think this would be super helpful for  build servers that may compiling apps written on varied frameworks.

**Comment by davidfowl** [comment]
Can you file this issue on aspnet/dnvm?
