### ISSUE TITLE
external TagHelpers and Naming

### ISSUE THREAD

**Issue by HornerGrahame** [aspnet/Mvc#2603]
While developing a set of TagHelpers (external to the Web Application Project) adding these to the view using @addTagHelper works without issue; however using/triggering the helper causes a 403.14 error.

also if a TagHelper of the same name exists in a different namespace but with the same name, the system report this as an issue; One or more compilation errors occurred: .. even when the @addTagHelper explicitly is using a given assembly.

**Comment by danroth27** [comment]
Could you please share with us more details on your Tag Helper project so that we can take a look at the 403.14 issue? Can you share the project with us?

**Comment by HornerGrahame** [comment]
The issue looks only to appear when RazorPreCompilation GenerateSymbols = true; I'll provide more info in a couple of days as I'm having break this weekend.

**Comment by danroth27** [comment]
Closing for now - feel free to reopen when you have a moment to share your project with us.
