### ISSUE TITLE
Compilation fails with "You must add a reference to assembly 'System.ObjectModel, ..."

### ISSUE THREAD

**Issue by CodingGorilla** [aspnet/Mvc#2604]
I've been unable to build the Mvc project for a bit over a week now, even after pulling in the latest changes.  I keep getting the following compilation error:

> C:\Users\CodingGorilla\Source\Repos\Mvc\src\Microsoft.AspNet.JsonPatch\Adapters\ObjectAdapter.cs(628,46): error CS0012: The type 'KeyedCollection<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

I can provide a more detailed log if one would be helpful.

**Comment by Eilon** [comment]
@CodingGorilla did you run `git clean -xdf` prior to building? Also, are you using the `build` script in the repo to build from command line or are you building in VS?

**Comment by CodingGorilla** [comment]
I did a `git clean -xdf` and I have tried building both from the `build.cmd' file as well as in visual studio 2015 RC.

**Comment by Eilon** [comment]
Do you have any particular NuGet feeds configured in VS? Or disabled any feeds?

**Comment by CodingGorilla** [comment]
This is what I see when looking at the repository setting in visual studio with the `Mvc.sln` open.

![Image of Nuget Repos](http://content.screencast.com/users/CodingGorilla/folders/Jing/media/91442d78-8f4a-4b34-bd68-4a64fd39e1ed/2015-05-26_1956.png)

The first item there is a corporate nuget repo which is appropriately disabled.  The last item, `api.nuget.org` is something from VS2015 RC or Windows 10 I assume, I don't think I added that; however just to be sure I enabled it, ran:

```
git clean -xdf
.\build.cmd
```

With the same results.

**Comment by CodingGorilla** [comment]
So I cloned this repo directly, and cleared out my `%LocalAppData%\Nuget` folder just to be sure I didn't have any wacky cached package issue going on.  Same results.  Below are the actual errors:

> C:\Users\Mark\Source\Repos\aspnet-mvc\src\Microsoft.AspNet.JsonPatch\Adapters\ObjectAdapter.cs(628,46): error CS0012: The type 'KeyedCollection<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
> C:\Users\Mark\Source\Repos\aspnet-mvc\src\Microsoft.AspNet.JsonPatch\Adapters\ObjectAdapter.cs(628,46): error CS0012: The type 'KeyedCollection<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
> C:\Users\Mark\Source\Repos\aspnet-mvc\src\Microsoft.AspNet.JsonPatch\Adapters\ObjectAdapter.cs(628,46): error CS1579: foreach statement cannot operate on variables of type 'Newtonsoft.Json.Serialization.JsonPropertyCollection' because 'Newtonsoft.Json.Serialization.JsonPropertyCollection' does not contain a public definition for 'GetEnumerator'
> 
> Build failed.
>     0 Warning(s)
>     3 Error(s)
> 
> Time elapsed 00:00:00.7309280
> warn: Exit code -1 from cmd
> verbose: Stack trace:
>    at View1752a6c16bf74dd4bec558f4cdf92b3b.DnuPack(String projectFile, String kpmPackOutputDir, String configuration) in c:\Users\Mark\AppData\Local\Temp\f3da5fcdc035466680ba83f95ca5af97-1.cs:line 945
>    at View1752a6c16bf74dd4bec558f4cdf92b3b.<>c__DisplayClass95.<RenderViewLevel0>b__60(String projectFile) in c:\Users\Mark\AppData\Local\Temp\f3da5fcdc035466680ba83f95ca5af97-1.cs:line 7459
>    at System.Collections.Generic.List`1.ForEach(Action`1 action)
>    at View1752a6c16bf74dd4bec558f4cdf92b3b.<>c__DisplayClass95.<RenderViewLevel0>b__5e() in c:\Users\Mark\AppData\Local\Temp\f3da5fcdc035466680ba83f95ca5af97-1.cs:line 7459
>    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
>    at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
>    at View1752a6c16bf74dd4bec558f4cdf92b3b.<RenderViewLevel0>b__46() in c:\Users\Mark\AppData\Local\Temp\f3da5fcdc035466680ba83f95ca5af97-1.cs:line 2226
>    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
>    at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
>    at View1752a6c16bf74dd4bec558f4cdf92b3b.<RenderViewLevel0>b__47() in c:\Users\Mark\AppData\Local\Temp\f3da5fcdc035466680ba83f95ca5af97-1.cs:line 2243
>    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
>    at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
>    at View1752a6c16bf74dd4bec558f4cdf92b3b.<RenderViewLevel0>b__48() in c:\Users\Mark\AppData\Local\Temp\f3da5fcdc035466680ba83f95ca5af97-1.cs:line 2260
>    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
>    at View1752a6c16bf74dd4bec558f4cdf92b3b.<RenderViewLevel0>b__40() in c:\Users\Mark\AppData\Local\Temp\f3da5fcdc035466680ba83f95ca5af97-1.cs:line 2116
>    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
>    at Sake.Engine.SakeEngine.Execute(Options options)
>    at Sake.Engine.SakeEngine.Execute(String[] args)
>    at Sake.Program.Main(String[] args)

**Comment by davidfowl** [comment]
Try clearing %userprofile%\.dnx\packages

**Comment by CodingGorilla** [comment]
@davidfowl :+1: That seems to have fixed the problem.
