### ISSUE TITLE
Consistent authorization inheritance

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#2607]
Now, you can use ```AuthorizeAttribute``` to specify that controller or action needs authorization. If action can be accessed anonymously, ```AllowAnonymousAttribute``` can be used to override ```AuthorizeAttribute```. But once you add ```AllowAnonymousAttribute``` on your controller you can't override it, which is kind of confusing, especially in situations then controllers inherit from custom base controllers.

Here are some example, demonstrating the confusion:
```C#
[Authorize]
public class HomeController : Controller
{
    [AllowAnonymous]
    public IActionResult Index()
    {
        // Action can be accessed anonymously as expected
        return View();
    }
}

[AllowAnonymous]
public class HomeController : Controller
{
    [Authorize]
    public IActionResult Index()
    {
        // Action can be accessed anonymously, even though authorize attribute is most specific one
        return View();
    }
}

[Authorize]
public class HomeController : BaseController
{
    [Authorize]
    public IActionResult Index()
    {
        // Action can be accessed anonymously, even though authorize attribute is all over the place,
        // but you can't see that AllowAnonymousAttribute is being used on base controller.
        return View();
    }
}
```

Wouldn't it be better to have authorization based on most specific first, similar to [RouteConstraintAttribute](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/RouteConstraintAttribute.cs)?
I believe this would bring some consistency within authorization attribute usage.

**Comment by danroth27** [comment]
@blowdart

**Comment by blowdart** [comment]
By default AllowAnonymous halts all authz at the point it's encountered. 

Needs investigation to see how it currently behaves in previous versions. If this is how it works in previous versions I'd be loathe to change it, it'd be a major breaking change in behaviour that may lead things to be inadvertently exposed if people are depending on the current way it works.

cc @HaoK

**Comment by HaoK** [comment]
Yeah this is how it used to work.  Eilon can confirm but I misunderstood this initially too. Basically allow anonymous means skip all authorization.

**Comment by blowdart** [comment]
Adding @Eilon for comments

**Comment by Muchiachio** [comment]
> @blowdart: It'd be a major breaking change in behavior that may lead things to be inadvertently exposed if people are depending on the current way it works.

I understand that it's a breaking change, this is why I created this issue in MVC6 repo not 5th :smile:
But, I couldn't think of any situation in which my suggested approach would lead to "inadvertently exposed" actions? Would you mind sharing one, maybe I'm just missing something. Because I believe that overriding authorization would only lead to stricter authorization, in this case.

If it's still a no, you can close with won't fix label or something. :+1:

**Comment by danroth27** [comment]
The current logic is pretty simple and we don't think the scenarios are compelling enough to change it, so closing for now.
