### ISSUE TITLE
Cannot use nameof(XController) in asp-controller tag helper

### ISSUE THREAD

**Issue by markrendle** [aspnet/Mvc#2608]
Similar to issue #2586

I'm speaking specifically to tag helpers here, though, and I think this is something developers might reasonably expect to be possible:

`<a asp-controller="@nameof(HomeController)" asp-action="@nameof(HomeController.About)">About</a>`

The workaround of not using the Controller suffix on HomeController doesn't work, it just throws a CompilationFailedException with **The name 'HomeController' does not exist in the current context**

It seems wrong that C# 6 adds the `nameof` operator specifically to avoid magic string problems just like this one, and MVC 6 fails to take advantage of it, for what would surely be a quick check to see whether or not a string ends with "Controller".

It is also inconsistent, because the `asp-action="@nameof(HomeController.Action)"` works fine. The reason why may be obvious to some developers, but to many it won't be.

**Comment by danroth27** [comment]
Technically `asp-action="@nameof(HomeController.Action)"` is problematic as well because you might have `[ActionName("Foo")]` on your action.

Using nameof in this way is may work in some cases (ex you name your controller "Home" instead of "HomeController") but nameof is not aware of the Application Model and so cannot work in all cases.

What we could do is consider providing an API that allows you to get the controller name or action name based on a type.

**Comment by toddlucas** [comment]
Another place where this would be really helpful is the asp-for attribute. For example ```<input asp-for="@nameof(Model.PropertyName)" />```. As of rc1-final, I get the following exception when I try this.

```
System.InvalidOperationException: Templates can be used only with field access, property access, single-dimension array index, or single-parameter custom indexer expressions.
   at Microsoft.AspNet.Mvc.ViewFeatures.ExpressionMetadataProvider.FromLambdaExpression[TModel,TResult](Expression`1 expression, ViewDataDictionary`1 viewData, IModelMetadataProvider metadataProvider)
   at Microsoft.AspNet.Mvc.Razor.RazorPage`1.CreateModelExpression[TValue](Expression`1 expression)
   at Asp.ASPV__Views_Xxx__YyyPartial_cshtml.<<ExecuteAsync>b__24_0>d.MoveNext() in /Views/Xxx/_YyyPartial.cshtml:line 4
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by Eilon** [comment]
Closing because we have no plans to support this.
