### ISSUE TITLE
Integers from JSON don't bind to enums

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#2609]
I have the following setup:
- A Razor `<select>` populated by `GetEnumSelectList`, so the options's values are numbers
- Some client code that creates JSON from the currently selected entry
- A controller, that parses the JSON (now the values are `Int64`!)
- Model binding trying to fill an enum field

This setup fails, because enum binding [is only supported for `Int32`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Abstractions/ModelBinding/ValueProviderResult.cs#L145).

I didn't check, but a failing test looks much like [this `ValueProviderResult` test](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.Abstractions.Test/ModelBinding/ValueProviderResultTest.cs#L163) with the `1` replaced by `1L`.

**Comment by danroth27** [comment]
@Tragetaschen Thanks for reporting this issue! Do you have a simple project you could send us that reproduces this issue so that we can investigate?

**Comment by Eilon** [comment]
We should ideally support value provider results containing all kinds of numeric treasures.

@ajaybhargavb , you can sync with @dougbu on the background for this bug.
