### ISSUE TITLE
Taghelper not generating html in beta5

### ISSUE THREAD

**Issue by janna173** [aspnet/Mvc#2616]
I updated my SDK to beta5 today. After that, the taghelpers don't generate html anymore. The tags e.g. 'asp-for' stay the same while running the application. Is this a bug or something?

I added the taghelper to my view `<@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers">`
I also included those dependencies an some others 
```
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-*"
```
concret from project.lock.json
```
    "Microsoft.AspNet.Mvc/6.0.0-beta5-13991": {
      "serviceable": true,
      "sha512": "0OLW7upeElmkcNm3iRTeB9Xb8JlWhKx61xCvjgjeeigJaYgtXYJsR/iu47wUaJUCcdVBxU6xkbBxvbGVayi/QQ==",
      "files": [
        "Microsoft.AspNet.Mvc.6.0.0-beta5-13991.nupkg",
        "Microsoft.AspNet.Mvc.6.0.0-beta5-13991.nupkg.sha512",
        "Microsoft.AspNet.Mvc.nuspec",
        "lib/dnx451/Microsoft.AspNet.Mvc.dll",
        "lib/dnx451/Microsoft.AspNet.Mvc.xml",
        "lib/dnxcore50/Microsoft.AspNet.Mvc.dll",
        "lib/dnxcore50/Microsoft.AspNet.Mvc.xml"
      ]
```
and

```
      "Microsoft.AspNet.Mvc.TagHelpers/6.0.0-beta5-13991": {
        "dependencies": {
          "Microsoft.AspNet.Mvc.Razor": "6.0.0-beta5-13991",
          "Microsoft.Framework.Caching.Memory": "1.0.0-beta5-11418",
          "Microsoft.Framework.FileSystemGlobbing": "1.0.0-beta5-11446"
        }
```
Does anybody know about this?

**Comment by dougbu** [comment]
@janna173 what DNX version are you using? If running the site from the command line, `dnx --version` shows this information. If running from within Visual Studio, instead check the `global.json` file for a `sdk` / `version` entry.

**Comment by janna173** [comment]
@dougbu I am running the application from Visual Studio using SDK beta 5
This is what `global.json` contains:
```
    "sdk": {
        "version": "1.0.0-beta5-11896"
    }
```

**Comment by dougbu** [comment]
@janna173 I suspect your setup is fine but that you've hit one of the recent breaking changes introduced during Beta 5. If the `@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"` statement is in `_GlobalImport.cshtml`, try renaming that file to `_ViewImports.cshtml`. See [this announcement](https://github.com/aspnet/Announcements/issues/27) for more information.

**Comment by matthewDDennis** [comment]
And upgrade latest pre-release dnx.

**Comment by janna173** [comment]
@dougbu Thanks, renaming _GlobalImport.cshtml solved the problem. Didn't see the announcment.
