### ISSUE TITLE
MessageHandlers

### ISSUE THREAD

**Issue by damienbod** [aspnet/Mvc#2617]
How are Web API Message Handlers supported MVC 6, or what's the recommended way to to this in the new Framework?

greetings Damien

**Comment by darrelmiller** [comment]
You can add a piece of Middleware, similar to the way Owin middleware works.  I have an example here https://github.com/darrelmiller/Mvc6Sandbox/blob/master/src/Mvc6Sandbox/Startup.cs

**Comment by rynowak** [comment]
What Darrel is suggesting is great if you want a message handler that sees all requests coming ing.

If instead you want to attach something like a 'handler' to a specific route that's also possible by implementing `IRouter` and putting it **between** the route and MVC. If you need a sample I could write one up for you - I'm not aware of an existing one that we have.

**Comment by darrelmiller** [comment]
I curious about what the differences in behaviour would be if you were to stick an IRouter in front of the MvcRouteHandler.

**Comment by rynowak** [comment]
> I curious about what the differences in behaviour would be if you were to stick an IRouter in front of the MvcRouteHandler.

The difference in behavior depends on what your `IRouter` implementation does :laughing: 

A key difference between MVC6 and MVC5/WebAPI2 is there there is no difference in interface contract between a *route* and a *handler* - it's all `IRouter`. An `IRouter` implementation might delegate (`TemplateRoute`) or it might produce a response itself (`MvcRouteHandler`) - or it might choose depending on the request. 


For clarification (and posterity) the typical pipeline of an MVC 6 app will look like this:
```
 (Other Middleware) -> (Router Middleware) -> [Route Collection] -> [Template Route "{controller}/{action}/{id?}] -> [MvcRouteHandler]
```

Anything in `(...)` is middleware, and anything in `[...]` is an `IRouter` implementation. If you want to consider attribute routing, replace `[Template Route ...]` with the attribute route.

When you do a `UseMvc(routes => { ... })` we're basically setting up a default configuration for you. The `routes` parameter is getting an instance of `IRouteBuilder` and it's `DefaultHandler` property will be set to an instance of `MvcRouteHandler`. Any calls to `MapRoute(...)` you make are going to instantiate a new `TemplateRoute` instance which will attempt to match the URL and then delegate to the `DefaultHandler`.

So if you do the followin.

**Comment by rynowak** [comment]
> I curious about what the differences in behaviour would be if you were to stick an IRouter in front of the MvcRouteHandler.

The difference in behavior depends on what your `IRouter` implementation does :laughing: 

A key difference between MVC6 and MVC5/WebAPI2 is there there is no difference in interface contract between a *route* and a *handler* - it's all `IRouter`. An `IRouter` implementation might delegate (`TemplateRoute`) or it might produce a response itself (`MvcRouteHandler`) - or it might choose depending on the request. 


For clarification (and posterity) the typical pipeline of an MVC 6 app will look like this:
```
 (Other Middleware) -> (Router Middleware) -> [Route Collection] -> [Template Route "{controller}/{action}/{id?}] -> [MvcRouteHandler]
```

Anything in `(...)` is middleware, and anything in `[...]` is an `IRouter` implementation. If you want to consider attribute routing, replace `[Template Route ...]` with the attribute route.

When you do a `app.UseMvc(routes => { ... })` we're basically setting up a default configuration for you. The `routes` parameter is getting an instance of `IRouteBuilder` and it's `DefaultHandler` property will be set to an instance of `MvcRouteHandler`. Any calls to `MapRoute(...)` you make are going to instantiate a new `TemplateRoute` instance which will attempt to match the URL and then delegate to the `DefaultHandler`.

So if you do the following:
```
app.UseMvc(routes =>
{
    routes.DefaultHandler = new MyHandler(routes.DefaultHandler);

    routes.MapRoute(...);
}
```

Then you get something like the following (middleware omitted):
```
[Route Collection] -> [MyHandler] -> [Template Route "{controller}/{action}/{id?}] -> [MvcRouteHandler]
```

**Comment by darrelmiller** [comment]
Fabulous information!  Thank you.

**Comment by damienbod** [comment]
Super!

Thanks for your time and information.

Greetings and thanks Damien

**Comment by AkbaraliShaikh** [comment]
Hi,

I'm trying to create the middleware which should execute before every request made to the controller (API), 

But i'm facing the problem, when there is a route which executes the action in that case my middleware not going to execute, it only gets executed for those routes where there is no action is pointing.

app.UseMvc();
app.MapWhen(_=>_.Request.Path.Value.Contains("/"), _ => _.UseRequestLogger());

when i hit the URL "http://localhost:5000/rest/api/1/" it executes because there is no action for this route, if i hit the URL "http://localhost:5000/rest/api/1/users" this will not call middleware it calls my api action method

But I'm looking for an solution before each action the middleware has to be executed.

please help me here.

Thanks in advance.

**Comment by Eilon** [comment]
@AkbaraliShaikh please log a new issue for this.
