### ISSUE TITLE
Consider moving anti-forgery out of MVC 6

### ISSUE THREAD

**Issue by brockallen** [aspnet/Mvc#2618]
This is a feature that's sufficiently useful outside of MVC 6 -- perhaps it should be moved to its own library.

**Comment by harshgMSFT** [comment]
It will be interesting to see what scenarios you have in mind. Can you please share what are we trying to achieve?

**Comment by brockallen** [comment]
Nancy. Razor pages stand alone. Pure middleware that needs anti-xsrf.

**Comment by darrelmiller** [comment]
:+1:

**Comment by yishaigalatzer** [comment]
@harshgMSFT is there anything practically blocking the use of antiforgery outside of the MVC pipeline?

**Comment by blowdart** [comment]
:balloon: :lock: :balloon: 

Security party! (We really ought to do this)

**Comment by PinpointTownes** [comment]
Oh yeah, :+1:

**Comment by jason-ap** [comment]
awesome~

**Comment by rynowak** [comment]
You can see progress on this here: https://github.com/aspnet/antiforgery

Will post to announcements when refactoring/layering is done.

**Comment by brockallen** [comment]
Nice, thanks!

**Comment by rynowak** [comment]
Done in Beta6. See here: https://github.com/aspnet/Announcements/issues/34
