### ISSUE TITLE
Extend AntiForgery system to allow other sources for AntiForgery tokens instead of Request Form

### ISSUE THREAD

**Issue by slaneyrw** [aspnet/Mvc#2619]
Consider a single page application that communicates to the server via AJAX.  The Request.Form is not usable as a source for the AntiForgery token.

Please extend the AntiForgery system to allow a custom token store to be injected, so that alternate sources can be used, like request Headers, JSON request, etc.

**Comment by danroth27** [comment]
@blowdart

**Comment by blowdart** [comment]
We'd have to be very context aware, probably too much to be usable. There's no simple way to intercept every HTTP request from a page without a lot of script, and what would work for the current framework de jour probably wouldn't work of the next one everyone adopts a week later.

**Comment by slaneyrw** [comment]
We currently have to create our own ValidationAntiForgeryToken attribute, override the OnAuthorization method, read the inbound token from the headers, call the second overload of the static AntiForgery.Validate method supplying the two tokens - which doesn't handle missing tokens like the no argument overload.

It would be much easier (in ASP.NET 5) to supply an alternative IAntiForgeryTokenStore that can you read the "form" token from another source depending on the request type ( like request headers if AJAX, payload if websocket, etc).  

The AntiForgery class currently HARDCODES the IAntiForgeryTokenStore supplied to the AntiForgeryWorker.  Can you get the implementation from the DI system so we can override it ?

**Comment by danroth27** [comment]
@rynowak @Eilon @blowdart We should chat about what we want to do here.

**Comment by rynowak** [comment]
Fixed here: https://github.com/aspnet/Antiforgery/commit/9eeb1de68f7aa04a9088bd849e21820b00ac4364

Will close this issue when MVC has been updated to use the new Antiforgery codebase.

**Comment by rynowak** [comment]
Done in Beta6. See here: https://github.com/aspnet/Announcements/issues/34

**Comment by slaneyrw** [comment]
Thanks for making this change.  I'll play with the new infrastructure but so far it looks great.
