### ISSUE TITLE
Media Formatter

### ISSUE THREAD

**Issue by damienbod** [aspnet/Mvc#2620]
How do you implement a custom MediaFormatter in MVC 6?

Greetings Damien

**Comment by danroth27** [comment]
`MediaTypeFormatter` has been split into `IInputFormatter` and `IOutputFormatter` in MVC6. You can take a look at the built-in formatters in MVC to get you started. For example:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Formatters/StringOutputFormatter.cs
