### ISSUE TITLE
InvalidCastException in DefaultHtmlGenerator.GetCurrentValues

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#2621]
I'm currently seeing a behavior difference between Windows and Mono wrt the select tag helper for an enum in beta4. On Mono, `DefaultHtmlGenerator.GetCurrentValues` throws an `InvalidCastException`.

I didn't yet dig in very far to check if that's the reason, but at least [the return type of `ConvertEnumToString`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Rendering/Html/DefaultHtmlGenerator.cs#L1122) should be `TEnum`, so the returned `null` has a type other than `object` and the cast from the [delegate invoke in `GetCurrentValues`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Rendering/Html/DefaultHtmlGenerator.cs#L834) doesn't fail.

If I have time, I'll likely look deeper into this. If the above is the offending code path, it shouldn't happen in the first place…

**Comment by dougbu** [comment]
@Tragetaschen which Mono version are you using? What is the minimal repro for this problem? For example does the failure occur only with a `string` that does not match any `enum` value?

Actually even the full stack trace when using the latest Beta 5 bits would help.

BTW [`ConvertEnumFromString()`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Rendering/Html/DefaultHtmlGenerator.cs#L1122) must return `object`, `TEnum?`, or perhaps `Enum`; it must indicate a failed parse to the caller. The caller's [cast to `Enum`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Rendering/Html/DefaultHtmlGenerator.cs#L834) might be acting strange on Mono.

**Comment by Tragetaschen** [comment]
Mono version is 4.0.1 with a patch to fix SignalR's IL_0057 bug.

You are right, I had on my mind that the returned null would have the runtime type `object` and that the downcast to `Enum` then fails.

The stack trace is literally Razor => SettingTagHelper.Process => GetCurrentValues. I'll try to reproduce this with a full stack trace (with source file numbers) in dev when I'm home and find the time. There, I can also easily look into Mono itself.

**Comment by Tragetaschen** [comment]
8188f59

**Comment by dougbu** [comment]
Thanks for the follow-up @Tragetaschen  Nice to see a few of our fixes are of real bugs :smiley_cat:
