### ISSUE TITLE
Simple Example using a tag helper

### ISSUE THREAD

**Issue by jrock2004** [aspnet/Mvc#2627]
I am trying to use tag helpers in MVC6 beta4. In my cshtml I added

    <a controller="Shipping">Help</a>

I have nothing declared in the @using so I am wondering if I am missing something? Should I be wrapping this around an @{}. Thanks

**Comment by dougbu** [comment]
@jrock2004 the syntax is `<a asp-controller="Shipping">Help</a>` and you need `@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"` in the file as well or in your `_GlobalImport.cshtml` file.

**Comment by jrock2004** [comment]
I don't have a _GlobalImport file. Does that @addTagHelper go on top?

**Comment by dougbu** [comment]
Yes, that will work too.

**Comment by jrock2004** [comment]
Getting error

    CompilationFailedException: One or more compilation failures occured:
/Views/Settings/SecurityProfileEdit.cshtml (0,13) Directive 'addTagHelper's value must be surrounded in double quotes.
/Views/Settings/SecurityProfileEdit.cshtml (0,13) Encountered an unexpected error when attempting to resolve tag helper directive '@addTagHelper' with value '*, Microsoft.AspNet.Mvc.TagHelpers";'. Error: The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)

**Comment by jrock2004** [comment]
Here is the code

    @addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers";

And then

    <a asp-controller="Settings">Help</a>

In visual studio there is a little red mark after the addTagHelper

**Comment by dougbu** [comment]
Remove the semicolon at the end of the `addTagHelper` directive.

**Comment by jrock2004** [comment]
That did it, thanks @dougbu
