### ISSUE TITLE
Dynamically Loading Assemblies

### ISSUE THREAD

**Issue by HornerGrahame** [aspnet/Mvc#2628]
Is it possible for ASP.NET 5 running under dnxcore50 to load assembly files at runtime; supporting a plug-in type system.  I have tried obtaining the IAssemblyLoadContext using Microsoft.Runtime.Loader.LoadContextAccessor.Instance.Default without success; I'm trying to achieve this via a TagHelper similar to `<plugin-module path="~/plugins" file="module01", sha=".."></plugin-module>`

am I barking up the wrong tree? is this even possible? any advice/help/pointers would be great.

**Comment by dougbu** [comment]
Recommend using the `IAssemblyLoadContext` in DI. Best to add a parameter of this type to your tag helper's constructor.

Please let us know if this does not work a bit better. Would also appreciate additional details on the failure if problems continue.

**Comment by davidfowl** [comment]
@HornerGrahame Here's an example of a console application https://github.com/aspnet/Entropy/tree/dev/samples/Runtime.CustomLoader
