### ISSUE TITLE
Angular scaffold in MVC 5 or 6 is it or will be possible?

### ISSUE THREAD

**Issue by danicomas** [aspnet/Mvc#2630]
I think that the framework client are winning the battle over server soup tags templates.

Is possible scaffold with angularjs(list, create, update,..)?

I attach the two links as work ruby on rails:

https://github.com/patcito/angularjs_scaffold
http://blog.ricodigo.com/blog/2012/10/14/announcing-the-release-of-angularjs-scaffold/

**Comment by danroth27** [comment]
@sayedihashimi One idea is to add Yeoman generators that scaffold an MVC 6 based Web API backend with an angularjs frontend.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
