### ISSUE TITLE
TagHelper removing ~ from HtmlAttribute

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Mvc#2631]
When HtmlAttribureString a string starts with '~' this is stripped from the value populated into the TagHelper class property.  eg. "~/folder/file.txt" becomes "/folder/file.txt"

**Comment by NTaylorMullen** [comment]
Good find, it even looks like we rely on this behavior a little bit in our own `TagHelper` samples which I believe is wrong. Could you move this issue to the aspnet/Razor repo?

**Comment by danroth27** [comment]
I'll move it.
