### ISSUE TITLE
Template feedback

### ISSUE THREAD

**Issue by glen-84** [aspnet/Mvc#2637]
1. Why `@inject` SignInManager instead of passing it via the controller (the whole point of MVC).
2. Why is System.Collections.Generic and Microsoft.AspNet.Http referenced by Login.cshtml?
3. `asp-controller="Account"` (and Manage) is not necessary, as far as I know. (multiple occurrences)
4. The periods (`.`) at the end of headers (`<h2>, <h4>, etc.`) should be removed.
5. I'm not sure if it's a good idea to have both a validation summary as well as validation messages per field.
6. I think that `asp-route-returnurl` should be `asp-route-returnUrl`. I know that binding is case-insensitive, but camelCase is clearer, matches the action method parameter name, etc.
7. Remove deprecated `<hgroup>` from ExternalLoginFailure.
8. Some of the comments in ManageController show `/Account/` instead of `/Manage/`.
9. `AddPhoneNumber` action missing `[HttpGet]` attribute.
10. `VerifyPhoneNumber` doesn't show usage of `MessageServices`, and also should probably not use the `GET` method.
11. `HasPhoneNumber` helper is never used.
12. Add note about contacting support if no password reset e-mail is received (as they may not be registered, but they'll never know).
13. Consider renaming `ManageLogins` to `ExternalLogins`, so the URL is `/Manage/ExternalLogins` and not `/Manage/ManageLogins`.

Question: Are there any plans to make the project templates public on GitHub?

**Comment by danroth27** [comment]
We are tracking this internally as part of our template work.

**Comment by peterblazejewicz** [comment]
> Question: Are there any plans to make the project templates public on GitHub?

@glen-84 
In case you've missed: templates are now public:
https://github.com/aspnet/Templates

**Comment by glen-84** [comment]
@peterblazejewicz I noticed, thanks. :+1:
