### ISSUE TITLE
ViewComponents in an Area

### ISSUE THREAD

**Issue by logikaljay** [aspnet/Mvc#2640]
I may be doing this wrong (I cannot find any documentation on how to do it any other way).
When you create a ViewComponent in an Area, the Search paths are incorrect:
```
namespace HelloWorld
{
	[Area("Test")]
	public class HelloViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View();
		}
	}
}
```

Instead of searching for the view at `/Areas/Test/Views/Components/Hello/Default.cshtml` the following exception is thrown:

    InvalidOperationException: The view 'Components/Hello/Default' was not found. The following locations were searched:
    /Views/Home/Components/Hello/Default.cshtml
    /Views/Shared/Components/Hello/Default.cshtml.

I am invoking the view by doing the following: (in `/Views/Home/Index.cshtml`)
```
@Component.Invoke("Hello")
```

There does not seem to be a way to include an area to invoke the view from.

Any ideas?

**Comment by rynowak** [comment]
@logikaljay a view component is neither in nor out of an area. **The concept doesn't apply**.

What matters is that for view lookup, the view search paths are based on the calling view/action. So if a controller from an area is calling into a VC, then the area's search paths are used.

**Comment by logikaljay** [comment]
So is there a way to force the search path?
As I understand it ViewComponents are a replacement for PartialView's (correct me if I am wrong)

In MVC5 we would do `@Html.Action("Hello", "Test", new { area = "Test" })` Basically I am just trying to recreate this - however sadly `Html.Action` no longer exists

**Comment by rynowak** [comment]
> As I understand it ViewComponents are a replacement for PartialView's (correct me if I am wrong)

VCs are a simplified replacement for child actions (`Html.Action(...)`). Though they're not intended to do everything that child actions could do. Think of it as a partial view with a little bit of controller code attached.

> So is there a way to force the search path?

A VC has both a short name and a full name. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ViewComponents/ViewComponentConventions.cs

Typically that would looks like this:
```
namespace Contoso.Web
{
    public class TagCloudComponent : ViewComponent
    {
    }
}

Full Name: Contoso.Web.TagCloud
Short Name: TagCloud
```

You can pass a full or short name to any of the methods that call a VC.


> Basically I just need to be able to call "PartialViews" from inside an Area like we used to be able to do in MVC5 - Maybe I am going about this wrong and need to re-think my approach.

Is the VC code actually different or is the view that's being rendered the only piece that's different?

**Comment by logikaljay** [comment]
The View is the only piece that is different.

I am basically looking for a replacement for child actions that works the way I used to use them. I do like the new VC's - its just not allowing me to include a VC that resides in an area from inside non-area views. For example:

If I had an Area called `Blog` this area was shared across 10 different websites and I wanted a list of "Recent blog posts" on both the Blog Detail page URL: `/Blog/Some-Blog-Post/1` and also on the homepage.

Previously I would just `@Html.Action("RecentPosts", "Posts", new { area = "Blog" })` and return a child action on the `Posts` controller in the `Blog` area.

Now I would have to rewrite a lot more code.
