### ISSUE TITLE
How can I add param  while submit  "form "

### ISSUE THREAD

**Issue by lovemory** [aspnet/Mvc#2641]
IN MVC 5 ,I can add param by `new {object = value}`

`Html.BeginForm("AddUserConfirm", "Role", new { RoleID = @ViewBag.RoleID }, FormMethod.Post, new { enctype = "multipart/form-data" })`

IN MVC 6,How can I add param  while submit  `form `

`<form asp-controller="Role" asp-action="Create"  method="post" class="form-horizontal" role="form">`

**Comment by dougbu** [comment]
@lovemory the examples you provided both pass attributes through to the generated HTML. The "MVC 5" example works the same way in MVC 6.
- `Html.BeginForm(..., new { enctype = "multipart/form-data" })` adds `encType="multipart/form-data"` to the `<form>` tag.
` All of the non-`asp-...` attributes in the tag helper example will appear in the `<form>` tag. This doesn't work in MVC 5 of course.

What parameter support is missing?

**Comment by lovemory** [comment]
for example:
http://host/Role/Create?type=xxx
how can I add "type" prameter in post url ?

**Comment by alialdemir** [comment]
You can do this by adding hidden inside forms
for example:
<form asp-controller="Role" asp-action="Create" method="post" class="form-horizontal" role="form">
<hidden id="type" value="xxx" />
</form>

**Comment by Bartmax** [comment]
@alialdemir not exactly the same thing.
I think you are looking after `asp-route-`

```
<form asp-route-type="xxx" asp-controller="Role" asp-action="Create" method="post" class="form-horizontal" role="form">
...
</form>
```

I didn't tested it just found out by looking at the [FormTagHelper.cs](https://github.com/aspnet/Mvc/blob/144c1d3cf440506be6bca9f7fb2f1080d82828bb/src/Microsoft.AspNet.Mvc.TagHelpers/FormTagHelper.cs)

**Comment by lovemory** [comment]
@Bartmax , Great!  You are right!
<form asp-controller="Role" asp-action="Edit" asp-route-type="sss" method="post" class="form-horizontal" role="form">
will be generate html:
<form action="/Role/Edit/2323?type=sss" method="post" class="form-horizontal" role="form">
