### ISSUE TITLE
Question: How to make a route match a form upload?

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Mvc#2643]
I am trying to submit a form that has files attached to it. I cannot switch to JSON since I am adapting code that I did not write in the first place. How do I make the request match an action method without getting a 404. I already tried making a method that accepts POSTs but MVC does not want to co-operate.

**Comment by davidfowl** [comment]
Can you provide an end to end sample that doesn't work so we can reproduce the problem?

**Comment by borgdylan** [comment]
I will try. The code I spotted thison is internal company code so I will have to make a separate repro from scratch.

**Comment by borgdylan** [comment]
After trying a repro the bug did not manifest itself. However I continued to reduce the request's complexity down to a simple get request and I concluded that the action name "Upload" is not liked by Mvc.

**Comment by kichalla** [comment]
MVC doesn't have anything special about the action name "Upload"...without additional details it would be difficult to guess what the issue might be...could you provide details about the request url, route configuration and the skeletal structure of the controller?

**Comment by borgdylan** [comment]
The uri was htpp://localhost:5002/api/Roxy/Upload?siteId=1. The controller had no other overloads of the Upload method. The route config was "api/{controller}/{action}/{id?}" with defaults of "Home" and "Index".

**Comment by danroth27** [comment]
Can you show us your controller type and the Upload method signature?

**Comment by borgdylan** [comment]
The controller inherits from the regular Controller class and the signature was (I changed the name as I had to deliver working code):
```
[Authorize("SiteUser")]
[HttpPost()]
public async Task<ActionResult> Upload(int siteId, [FromForm()] IFormCollection form)
```

**Comment by kichalla** [comment]
With the given information, I was unable to repro the issue...It would help you could provide us a simple standalone repro.

**Comment by borgdylan** [comment]
I could not reproduce the issue in another project.
