### ISSUE TITLE
Fix registration of MVC services

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#2648]
Ideally both of the following configurations should work…i.e a user should be able to call ‘ConfigureMvc’ either before or after AddMvc() and all the options registered would get called in the sequence they were registered.
Currently the issue is that #2 does not work as AddMvc() call doesn’t add options if it was added earlier.

1.	public IServiceProvider ConfigureServices(IServiceCollection services)
{
    services.AddMvc();

    services.ConfigureMvc(options =>
    {
        // This adds both Input and Output formatters based on DataContractSerializer
        options.AddXmlDataContractSerializerFormatter();

        // To add XmlSerializer based Input and Output formatters.
        options.InputFormatters.Add(new XmlSerializerInputFormatter());
        options.OutputFormatters.Add(new XmlSerializerOutputFormatter());
    });

2.	public IServiceProvider ConfigureServices(IServiceCollection services)
{
    services.ConfigureMvc(options =>
    {
        // This adds both Input and Output formatters based on DataContractSerializer
        options.AddXmlDataContractSerializerFormatter();

        // To add XmlSerializer based Input and Output formatters.
        options.InputFormatters.Add(new XmlSerializerInputFormatter());
        options.OutputFormatters.Add(new XmlSerializerOutputFormatter());
    });

    services.AddMvc();

**Comment by pranavkm** [comment]
The change was merged into beta5 release and not in to beta6 dev. Merging it was problematic so I ignored the entire change when we got to beta6 release. This item needs to be redone.

See https://github.com/aspnet/Mvc/issues/2823

**Comment by Eilon** [comment]
This is already fixed.
