### ISSUE TITLE
MVC should depend on Cors.Core not the Cors middleware

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#2660]
Why does MVC need to depend on the Cors middleware itself?

**Comment by rynowak** [comment]
Looks to me like this can just be removed without an refactor needed.

**Comment by ajaybhargavb** [comment]
69e051dab78988f4a9bac9da01a737aa1b53c77b and 6fd84654025701fc4a98fbffe27aeb368db3af76
