### ISSUE TITLE
Microsoft.AspNet.Mvc.Razor should not depend on Diagnostics.Abstractions

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#2661]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/project.json#L8

**Comment by pranavkm** [comment]
It should be removable. This was added back when the compilation exception interfaces were defined in Diagnostics

**Comment by ajaybhargavb** [comment]
fcdbd17e5892803519eff7fd17dd9f0f522b5a07
