### ISSUE TITLE
In Mono, if the name of the action and action filter are same, internal server error is thrown.

### ISSUE THREAD

**Issue by sornaks** [aspnet/Mvc#2669]
```c#
public class SimpleController : Controller
{
    [SimpleAction]
    public string SimpleAction()
    {
        return "Hello World!";
    }
}
```

When I call `http://localhost/Simple/SimpleAction`, I get `InternalServerError`.

**Comment by rynowak** [comment]
What's the exception?

**Comment by sornaks** [comment]
There is no exception. The body is empty. The status code is 500.

**Comment by rynowak** [comment]
Our test websites don't use ErrorPage, so the default would be a 500 with empty body :laughing:. Try adding the diagnostics middleware to the site.

**Comment by sornaks** [comment]
It was returning empty body even after adding `app.UseErrorPage()` to `Startup.cs`..

**Comment by kichalla** [comment]
You could also try the following and see if you can get more info...instead of the errorpage, register the following middleware early in the pipeline...

```C#
app.Use(async (httpContext, next) =>
{
    try
    {
        await next();
    }
    catch(Exception ex)
    {
        Console.WriteLine(ex.ToString());
    }
});
```

**Comment by sornaks** [comment]
This does not happen up to mono 4.0.2.5 alpha bits / 4.0.4 beta bits. It fails in 4.3.0. Filed a bug on mono and is tracked here - aspnet/External#32. Closing this.
