### ISSUE TITLE
In Mono, Action with the name "GetInternalServerErrorException" is not discoverable.

### ISSUE THREAD

**Issue by sornaks** [aspnet/Mvc#2670]
The action looks something like:
```C#
public IActionResult GetInternalServerErrorException()
{
    return InternalServerError(new Exception("Error not passed to client."));
}
```
When I call `http://localhost/api/Blog/ActionResult/GetInternalServerErrorException` it returns `NotFound`. If I change the name of the action to `SomeAction` it works as expected.

**Comment by sornaks** [comment]
Same is the case for `SimpleModel` in test - https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.FunctionalTests/ApiExplorerTest.cs#L731 (Action: https://github.com/aspnet/Mvc/blob/dev/test/WebSites/ApiExplorerWebSite/Controllers/ApiExplorerParametersController.cs#L19)

**Comment by sornaks** [comment]
And for action - https://github.com/aspnet/Mvc/blob/dev/test/WebSites/WebApiCompatShimWebSite/Controllers/ParameterBinding/EmployeesController.cs#L21

**Comment by sornaks** [comment]
And for - https://github.com/aspnet/Mvc/blob/dev/test/WebSites/ModelBindingWebSite/Controllers/RoundtripController.cs#L50

**Comment by rynowak** [comment]
We have a thingy in our test code that's supposed to ensure that **only** the controllers/actions from the specific website in use are loaded. It sounds to me like that's what's broken.

**Comment by rynowak** [comment]
See `TestHelper`@121

**Comment by sornaks** [comment]
This does not happen up to mono 4.0.2.5 alpha bits / 4.0.4 beta bits. It fails in 4.3.0. Filed a bug on mono and is tracked here - aspnet/External#32. Closing this.
