### ISSUE TITLE
Should our Enum conversions in ModelBinding call Enum.IsDefined?

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2673]
See discussion here: https://github.com/aspnet/Mvc/pull/2671#discussion_r31969481

We have code that turns untrusted input into an Enum (that the user likely defined). Why aren't we calling `Enum.IsDefined`?

**Comment by dougbu** [comment]
@rynowak in what way is an undefined `enum` "untrusted"?

**Comment by rynowak** [comment]
The untrusted input is the integer/string value in the request.

There's the potential for a serious expectations gap here between what a user might except to be allowed by validation, and what the server will actually allow.

**Comment by dougbu** [comment]
Disagree on expectations since MVC has never included `Enum.IsDefined()` checks. What you are suggesting amounts to adding `[EnumDataType(typeof(MyEnumType))]` to all properties with an `enum` type. Users can already do that if they wish such validation.

**Comment by danroth27** [comment]
Should this instead be handled through validation? I agree that general users want to use enums as a way to restrict input, but that's not really what they do in .NET. We could add a validation feature to that end, but I don't think we would do anything in model binding.

**Comment by dougbu** [comment]
@danroth27 might need to test it but validation _should_ honour association of `[EnumDataType(typeof(MyEnumType))]` with a property and run that validation server-side.

**Comment by danroth27** [comment]
Ah, ok. I think we can close this issue then.
