### ISSUE TITLE
Support TryUpdateModelAsync from POSTed JSON

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#2677]
I might be overlooking something, but I couldn't find anything. I have created [a quick repository](https://github.com/Tragetaschen/json-post) showing what I want to do.

To test the action methods on the HomeController I use curl:
`curl --header "Content-Type: application/json" -i -X POST -d '{"Name":"Foo"}' http://localhost:22700/Post1`

`Post_ModelBinding` works as expected (obviously).
In `Post_UpdateModel` on the other hand the call to `TryUpdateModelAsync` returns false due to the `Required` attribute). I think the latter should work as well.

As a workaround in my application, I 
- Receive the json as a `[FromBody] JObject` parameter
- Flatten the received object to a `DictionaryBasedValueProvider` (using dots for inner objects)
- Call `TryUpdateModelAsync` with that value provider

**Comment by davidfowl** [comment]
The input formatter handles JSON posted bodies not the model binder.

**Comment by rynowak** [comment]
We've thought about adding a `ModelBindingHelper.DeserializeModel` or something of that nature that **returns** a model object to you. Is this what you're looking for? Or something more akin to how MVC5 and previous versions handled body posts?

**Comment by Tragetaschen** [comment]
Depends on the signature of `DeserializeModel` :) As long as I can call it multiple times per request for different objects, that ought to do the trick.

I didn't use MVC5 and earlier that much, so I cannot comment on that part.

**Comment by Jabe** [comment]
+1 that would be super useful

**Comment by aanufriyev** [comment]
Any progress on that issue? Because now TryUpdateModel is misleading. And even is you hack your way through to InputFormatter - BodyModelBinder and JsonInputFormatter ignore existing ModelBindingContext.Model and always create new one.

**Comment by pranavkm** [comment]
I had a look at this but it looks like neither of the Xml based (de)serializers support populating an existing model. I'm going to close this as since there isn't a way to ship this feature that works correctly for all the formatters that MVC ships.

**Comment by Tragetaschen** [comment]
Yes, my use case is still (wow, that code hasn't really changed in the last three years :D) one posted JSON object, translation into a `RouteValueDictionary` + `RouteValueProvider` (with dots, square brackets etc.) and then multiple calls to `TryUpdateModelAsync(object, Type, string, IValueProvider, Func<>)` with different prefixes and different model (types).

**Comment by pranavkm** [comment]
> one posted JSON object, translation into a RouteValueDictionary + RouteValueProvider (with dots, square brackets etc.) and then multiple calls to TryUpdateModelAsync(object, Type, string, IValueProvider, Func<>) with different prefixes and different model (types).

That's not a scenario we would support out of the box - it's significantly different from how input formatter \ `BodyModelBinder` works. If there's interest, we could expose deserializing the model (closer to what @aanufriyev is attempting to do), but short of that we would close this issue.
