### ISSUE TITLE
@addTagHelper throwes assembly resolving error

### ISSUE THREAD

**Issue by evorine** [aspnet/Mvc#2678]
My project.json file's dependencies section is like:

    "dependencies": {
        "Microsoft.AspNet.Server.IIS": "1.0.0-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta6-12279",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta6-13213",
        "Microsoft.AspNet.Authentication": "1.0.0-beta6-12518",
        "Microsoft.AspNet.Mvc": "6.0.0-beta6-14086",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta4",
        "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta6-13481",
        "Microsoft.AspNet.Razor.Runtime": "4.0.0-beta6-11539",
        "Microsoft.Framework.DependencyInjection.Abstractions": "1.0.0-beta6-11465"
    }

I can't find any `Microsoft.AspNet.Mvc.TagHelpers` nuget package newer than `6.0.0-beta4`

In **_ViewImports.cshtml** file I have this line which makes all the trouble.

    @addTagHelper "LabelTagHelper, Microsoft.AspNet.Mvc.TagHelpers"

This is the error:

> Cannot resolve TagHelper containing assembly 'Microsoft.AspNet.Mvc.TagHelpers'. Error: Could not load type 'Microsoft.AspNet.Http.PathString' from assembly 'Microsoft.AspNet.Http, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

I tried to add many dependencies to solve this problem but couldn't achieve it.
Before a hardworking upgrade to `beta6` from `beta4` it was working.

**Comment by dougbu** [comment]
> I can't find any `Microsoft.AspNet.Mvc.TagHelpers` nuget package newer than `6.0.0-beta4`

This resolution issue is the core problem. The current version is `6.0.0-beta6-14086` this morning.

What error occurs if you restore with `"Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta6-*"` in the project.json file?

**Comment by evorine** [comment]
I can't get `"6.0.0-beta6-*"` or `"6.0.0-beta6-14086"`. VS intellisense only suggests beta4 and when I try to restore packages it can't locate `Microsoft.AspNet.Mvc.TagHelpers >= 6.0.0-beta6-14086`.

**Comment by dougbu** [comment]
What appears in the Output window? Or try `dnu restore` from the command line after confirming you're using the `dev` feed with `dnvm list`.

**Comment by evorine** [comment]
Thank you, I didn't know there was nightly builds out there. I switched to it now and the problem is solved by upgrading to `"6.0.0-beta6-*"`.

**Comment by NTaylorMullen** [comment]
An additional note for people coming across this issue: When adding a specific `TagHelper` from an assembly you must specify the full name. So instead of `@addTagHelper "LabelTagHelper, Microsoft.AspNet.Mvc.TagHelpers"` you'd have to write `@addTagHelper "Microsoft.AspNet.Mvc.TagHelpers.LabelTagHelper, Microsoft.AspNet.Mvc.TagHelpers"`
