### ISSUE TITLE
Improve Mock support for Viewcontexts

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#268]
Discovered during filters work. All of our old context classes in MVC had a no-arg constructor + virtual public property accessors for testability. Need to do a pass

**Comment by ianhong** [comment]
ActionContext will be updated per #1934

**Comment by ianhong** [comment]
@rynowak and @Eilon 

I think I need a little bit more investigation on this. We added the default constructor to ActionContext to improve unit testability of Controllers. 
I think we should do this to improve unit-testability of custom HtmlHelpers, TagHelpers, and ViewComponents. 
So, I'll start from doing unit tests to them to find out more requirements on this. 

I'm wondering if you have any more scenarios to add in addition to  HtmlHelpers, TagHelpers, and ViewComponents. ??

**Comment by rynowak** [comment]
Seems like a good idea to care about testability for TagHelpers and ViewComponents. Custom HtmlHelper implementations, I'm less convinced.

**Comment by Eilon** [comment]
Yeah let's start out with what @rynowak said.

**Comment by ianhong** [comment]
https://github.com/aspnet/Mvc/commit/3ea7daabfe41d986f713134ce09454c0e7c545b8
