### ISSUE TITLE
Default action in the form tag helper

### ISSUE THREAD

**Issue by wjzhou** [aspnet/Mvc#2680]
The form tag helper will add an default action attribute to the form tag.

I think it is reasonable to add this default action in the BeginForm(), However for the form tag, it is a little bit counter-intuitive.

The real problem is when using with angular. The angular will assume it is a server form submission if the form tag has a action attribute. It takes me half an hour to find this hidden default action.

```C#
            if (actionName == null && controllerName == null && routeValues == null && defaultMethod)
            {
                // Submit to the original URL in the special case that user called the BeginForm() overload without
                // parameters (except for the htmlAttributes parameter). Also reachable in the even-more-unusual case
                // that user called another BeginForm() overload with default argument values.
                var request = viewContext.HttpContext.Request;
                action = request.PathBase + request.Path + request.QueryString;
            }
```

**Comment by NTaylorMullen** [comment]
@wjzhou this has been addressed in the latest bits. Issue for referrence: https://github.com/aspnet/Mvc/issues/2581
