### ISSUE TITLE
Can we now use the beta4 release in Production

### ISSUE THREAD

**Issue by ikourfaln** [aspnet/Mvc#2683]
Hi,

We are working on a big project, and we need to build it with ASP.NET 5. But we can't wait anymore for the RTM, so is it safe to start the project with Visual Studio 2015 RC (MVC beta4) ?

Thanx for all your hard work

**Comment by davidfowl** [comment]
There has been minimal to no performance work, stress, security work and we're still making breaking API changes. Do you have a plan if you run into a problem that isn't solved right now or will be solved in a later release? What if you run into a stability issue? We won't be patching beta5 (or any of the betas for that matter).

**Comment by ikourfaln** [comment]
Thanx Mr @davidfowl for reply :+1: 
I think that we will just start with ASP.NET MVC 5.
What about .NET 4.6 is it safe to start a project with it ?

**Comment by jasonwilliams200OK** [comment]
@ikourfaln, your questions on Roslyn https://github.com/dotnet/roslyn/issues/3417, EntityFramework https://github.com/aspnet/EntityFramework/issues/2359 and others are related. The issue tracker is not the best place.
I will highly recommend you to use QA websites such as https://stackoverflow.com/ and others under StackExchange. You can also try public chatrooms such as https://gitter.im/dotnet/corefx.

**Comment by danroth27** [comment]
.NET 4.6 is already at Release Candidate quality and has a go live license, so you are welcome to use it in production.

**Comment by ikourfaln** [comment]
thanx for reply
