### ISSUE TITLE
Best way to register multiple action filters with a single attribute

### ISSUE THREAD

**Issue by IsaacSee** [aspnet/Mvc#2688]
Hello there. 

I'd like your opinion on the solution we used to **register multiple actions filters using a single attribute** (to avoid duplication and enhance lisibility).

We use a single [Api] Attribute marker (inheriting from Attribute) on our controllers.

Then we configure a custom IFilterProvider during the startup phase.
In the OnProvidersExecuting method of this custom FilterProvider, we look in the ActionContext.ActionDescriptor.ControllerTypeInfo.CustomAttributes for the [Api]. It we find one, we add multiple filters we consider mandatory for an [Api] Controller.

It feels kind of awkward to us, so we'd like to know if this a hack and if there is a better solution for this use case.

Thanks.

**Comment by danroth27** [comment]
@rynowak

**Comment by rynowak** [comment]
>It feels kind of awkward to us, so we'd like to know if this a hack and if there is a better solution for this use case.

I can assure this is not a hack, materializing filters is what we intended `IFilterProvider` to do. The part that we need a better explanation for is that your marker attribute should implement the `IFilter` marker interface, so you can avoid having to do the lookup.

There are 4 ways I can think of to specify filters, each with their own reasons for use.
- Create an attribute class that implements `I***Filter` - used for basic scenarios and back-compat
- Create an attribute class that implements `IFilterFactor` - used to access DI
- Create a marker attribute that implements `IFilter` and an `IFilterProvider` - most moving pieces but allows you run arbitrary logic to decide what filter instances apply and how to create them.
- Use Application Model

Application Model allows you to apply start-up time logic (which you write) to apply one of the other techniques. This will give you a mutable model of the actions and controllers in your site and allow you to see and modify the set of filters that apply to them. 

Ex:
```
public class ApiAttribute: Attribute, IControllerModelConvention
{
    public void Apply(ControllerModel controller)
    {
        if (controller.Attributes.OfType<MyAttribute>().Any())
        {
            controller.Filters.Add(new MyFilter1());
            controller.Filters.Add(new MyFilter2());
        }
    }
}
```

You can register conventions by using attributes or by adding them to `options.Conventions` in your startup code.

What you're doing **sounds** to me like a convention, and so I personally would code it up using application model, but there's nothing wrong with the filter provider mechanism.

**Comment by IsaacSee** [comment]
Thanks @rynowak for that very neat answer ! We did not use much Application Model, we will dig in that direction as the implementation feels sharper to me.

**Comment by IsaacSee** [comment]
Is it possible to access DI from Application Model ?

**Comment by rynowak** [comment]
If you're adding Application Model to `options.Conventions` you can get access to services in startup code. An example would be to create a class deriving from `ConfigureOptions<MvcOptions>` and register it as a service.

If you're using Application Model as an attribute then there's no good way to do it.

**Comment by IsaacSee** [comment]
Ok, thanks a lot for your answer. 
We will stick with the IFilterFactory since it provides access to DI.
