### ISSUE TITLE
Please add support for AppendTrailingSlash to RouteOptions

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#2691]
MVC 5 had the RouteCollection.AppendTrailingSlash setting. Please add the same option under the new RouteOptions and perhaps another option to RemoveTrailingSlash for those who prefer not to have one. This is a requirement for Search Engine Optimization.

```
services.ConfigureRouting(routeOptions =>
    {
        routeOptions.AppendTrailingSlash = true;
        routeOptions.LowercaseUrls = true;
    });
```

**Comment by danroth27** [comment]
Moved to https://github.com/aspnet/Routing/issues/188
