### ISSUE TITLE
Guidelines for modularization

### ISSUE THREAD

**Issue by IsaacSee** [aspnet/Mvc#2692]
Hello, 

In order to modulazire our platform, we are investingating into an IApplicationBuilder.Map() solution.

We'd like to be able to have a single website (ie. a single host) with multiple sandboxed-sub sites inside. The main website would only declare things like this : 
- "/" > Project.PublicPages
- "/api" > Project.PublicApi
- "/support" > Project.HelpDeskModule

Each sansboxed site must be defined its own assembly, with a "Startup-like" class to register middlewares and a sandbowed Mvc context (convention discovery of controller from this assembly only).

We checked Mvc Areas but it does not seem enought sandboxed for us.

Using IApplicationBuilder.Map() we are almost there but we can not find a way to sandbox multiple Mvc configurations/contexts in the same website.

An other way to look at this would be to try to add, over multiple Standard Mvc Website, a simple IRouter able to route the request to the right website. 

We could do that with a proxy but it would imply an non-neglgeable overhead on the infrastructure side if the website must listen on multiple local ports.

If someone already encounter this need I'd be glad to share samples and discuss about it.

Regards.

**Comment by danroth27** [comment]
We don't have a great story here - the lack of a good multi-tenancy story has been a long standing issue with MVC. It's unlikely we will be able to address this for this release giving the number of moving parts we are already dealing with in ASP.NET 5. Adding to the backlog.

**Comment by IsaacSee** [comment]
All right, we will implement an hybrid solution to with IApplicationBuilder.Map() even if Mvc areas can not be sandboxed.

**Comment by alexsandro-xpt** [comment]
Needs Design +1

**Comment by Eilon** [comment]
cc @danroth27 because this is related to the new ASP.NET Core Modules ideas.

**Comment by pranavkm** [comment]
At this point, our guidance is to look at a module system such as the one Orchard Core provides. Orchard Core modules allow you to build modules as NuGet packages that can be added to your application on the fly. And you can use them as a low level framework without adopting the entire Orchard CMS infrastructure. Check out https://github.com/OrchardCMS/OrchardCore.Samples to see what this looks like.
