### ISSUE TITLE
How to create a custom AuthorizeAttribute to avoid redirect to Azure login?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Mvc#2698]
1.0.0-beta4
Win10 preview build 10130
dnx451 (but will also need for dnxcore50)
VS 2150 RC

I'm working with AAD SSO, and everything, including Graph API, is working fine. Just one issue: When using `[Authorize]` attributes, such as `[Authorize(Roles = "Company Administrator")]`, if the current user doesn't have a role claim that matches, the browser is redirected to the Azure login page. What I actually want is for the browser to show one of my views. I tried using some overrides to see if I could hook a spot to stop the default behavior ...
```c#
public class CustomAuthorizeAttribute : AuthorizeAttribute, IAuthorizationFilter {

        public void OnAuthorization(Microsoft.AspNet.Mvc.AuthorizationContext context) {
            ...
        }

        protected void HandleUnauthorizedRequest(Microsoft.AspNet.Mvc.AuthorizationContext context) {
            ...
        }

    }
```
with `[Authorize(Roles = "Company Administrator")]` or `[CustomAuthorize(Roles = "Company Administrator")]`, but these attempts are not stopping the redirect.

How can I override the default behavior for unauthorized access to an action to show one of my views?

**Comment by GuardRex** [comment]
I guess I could do this ...
```c#
    public class CustomAttribute : ActionFilterAttribute {

        public string Roles { get; set; }

        public override void OnActionExecuting(ActionExecutingContext filterContext) {
            string[] roles = Roles.Split(',');
            foreach(var role in roles) {
                if (filterContext.HttpContext.User.IsInRole(role)) {
                    return;
                }
            }
            filterContext.HttpContext.Response.Redirect(Uri.EscapeUriString("/Home/Error?message=You are not authorized to access the resource."));
            base.OnActionExecuting(filterContext);
        }
    }
```
... but that sucks. I'd rather `HandleUnauthorizedRequest` and throw them straight to the view if possible.

**Comment by GuardRex** [comment]
Fixed by https://github.com/aspnet/Announcements/issues/40

**Comment by GuardRex** [comment]
I thought https://github.com/aspnet/Announcements/issues/40 my be my savior on this, but no dice. OpenIdConnect (apparently) handles the redirect to AAD when authorization fails.

**Comment by GuardRex** [comment]
Moved to [aspnet/Security#336](https://github.com/aspnet/Security/issues/336).

**Comment by GuardRex** [comment]
Filling this out with the final version of the custom attribute approach in case anyone ever finds this approach useful.
```c#
public class CustomAttribute : ActionFilterAttribute {

    public string Roles { get; set; }

    public override void OnActionExecuting(ActionExecutingContext filterContext) {
        if (Roles == "All") {
            if(filterContext.HttpContext.User.Identity.IsAuthenticated) {
                return;
            }
        } else {
            string[] roles = Roles.Split(',');
            foreach(var role in roles) {
                if(filterContext.HttpContext.User.IsInRole(role)) {
                    return;
                }
            }
        }
        filterContext.HttpContext.Response.Redirect(Uri.EscapeUriString("/Home/Error?message=You are not authorized to access the resource."));
        base.OnActionExecuting(filterContext);
    }

}
```
then in the controller you decorate like this ...
```c#
// No decoration for anything wide open to any user
public IActionResult UserUnauthenticated()
{
    return View();
}

// Roles = "All" for users that are authenticated but with any (or no) roles claims
[Custom(Roles = "All")]
public IActionResult UserAuthorized()
{
    return View();
}

// Roles = "<list of roles>" for authenticated users that have any of the role claims listed
[Custom(Roles = "Company Administrator,Identity Administrators,Password Administrators")]
public IActionResult AdministratorAuthorized()
{
    return View();
}
```
then you just need to establish one or more role claims for whatever roles the user has. Keep in mind that the whole point of all of this is just to hijack the ADAL process of kicking the user to AAD for login and redirecting them to an error response.

**Comment by marcosph** [comment]
Luke, the problem is that the roles are stored in the cookie. I have to
find some solution to update the cookie. When do I remove a roles directly
in the database the cookie is outdated. I think I have update the cookie to
each User request. The example I'm using is on github
https://github.com/aspnet/MusicStore/tree/master/src/MusicStore

**Comment by marcosph** [comment]
I have an MVC 6 intranet application that uses roles. The admin users can
manage all the user roles. However any changes made to a users' roles are
only effective when the user logs on (this makes sense as the roles are
stored as claims in a cookie). The requirement is for role changes to take
effect immediately, like they did in the older asp.net membership and role
managers. How can one achieve this with the new identity models? The only
way that comes to mind is to set some flag that is checked on each request
and if set then update the cookie to reflect the new roles. Do you have any
other suggestions or examples of how to ensure the role changes take effect
immediatley?﻿

**Comment by GuardRex** [comment]
@marcosph My requirements aren't as strict as your's, so I haven't had to think about that yet.

The only thing that jumps to mind is to make the claims timeout really fast. Like let it timeout every few minutes, thus the app would have to hit the IDP every few minutes and would then pickup any changes.

I've read that adding `options.ExpireTimeSpan = new TimeSpan(<hours>, <minutes>, <seconds>);` to `app.UseCookieAuthentication` options and adding `options.UseTokenLifetime = false;` to `app.UseOpenIdConnectAuthentication` options (or something along those lines) will allow you to control the token lifetime, but I haven't tested and really haven't even read up on it in detail.

Any of the other devs here can probably help out more. My issue here was simply stopping the middleware from throwing the user back to AAD everytime they hit an unauthorized resource, and I ended up not using this workaround from above but taking the great advice of @brentschmaltz in https://github.com/aspnet/Security/issues/336.

**Comment by IDisposable** [comment]
As the old adage says, no problem can't be solved with one more layer of indirection.  In this case, don't store the ACTUAL roles in the cookie, rather store a claim string that you use to lookup the roles from the database via. In my typical applications, that claim key is something like MyApp.AuthID and the value is the user's role. Then in the building of the in-memory IIdentity you do a database lookup and add the current roles of the in-memory identity.
