### ISSUE TITLE
Add support for model binding form data such as `numbers[]=1&numbers[]=2`

### ISSUE THREAD

**Issue by evorine** [aspnet/Mvc#2705]
When I post my form data as `numbers[0]=1&numbers[1]=1&numbers[2]=2&numbers[3]=3` or `numbers=1&numbers=1&numbers=2&numbers=3` the default model binder binds my array.

But as I know many frameworks support as `numbers[]=1&numbers[]=1&numbers[]=2&numbers[]=3`. So by default jQuery ajax functions use this format too.

When I send a simple data with ajax:
```javascript
$.ajax({
    url: '@Url.Action("Test1")',
    data: { numbers: [1, 1, 2, 3, 5] },
    method: 'POST'
});
```
It sends this as `numbers[]=1&numbers[]=1&numbers[]=2&numbers[]=3&numbers[]=5`.

Because of that its a little hard to post array data using ajax. I have to convert my arrays to objects whose parameters are indexes like `{"0": 1, "1": 1, "2": 2, "3": 3}` or make some changes in jQuery's ajax functions.

So will MVC support this type of binding by default?

**Comment by danroth27** [comment]
@dougbu Can you confirm we don't support this syntax in MVC 5 & 6?

**Comment by dougbu** [comment]
@danroth27 will do

**Comment by dougbu** [comment]
@danroth27 I have confirmed we do not support the requested parameter syntax in MVC 6. It works in MVC 5. So this is a gap compared to MVC 5.

FYI neither MVC 5 nor 6 support the `[]` syntax in query strings. For example submitting to `...?Numbers%5B%5D=1&Numbers%5B%5D=2` does not work though `...?Numbers%5B0%5D=1&Numbers%5B1%5D=2` is fine (in both versions).

**Comment by dougbu** [comment]
Updated title because this is no longer a question.

**Comment by dougbu** [comment]
bda8501
