### ISSUE TITLE
Why DisplayAttribute is sealed?

### ISSUE THREAD

**Issue by evorine** [aspnet/Mvc#2706]
In MVC5 I could create my own attribute from `DisplayNameAttribute` and override `DisplayName` property.
With this way the application could translate or format these texts dynamically if needed.

But as `DisplayAttribute` is sealed I can't do it anymore.

As I read here before, `DisplayNameAttribute` is no longer supported as it is not cross platform. It was a great power to be able to extend this attribute and customizing its name.

So is there an alternative way in MVC6? If not, isn't it better to allow developers to achieve this?

**EDIT:** Just saw that `DisplayAttribute` is not part of MVC. So I don't know if I asked something impossible. I'm lost now.

**Comment by danroth27** [comment]
These attributes are both part of .NET Core, so you will need to open this issue at https://github.com/dotnet/corefx/issues.

**Comment by cihadsevim** [comment]
Sam here.

**Comment by dougbu** [comment]
As @danroth27 said, this attribute is part of .NET Core and not specific to ASP.NET. Please see duplicate issue from last year in the CoreFx repository: dotnet/corefx#2093.

**Comment by pranavkm** [comment]
`DisplayNameAttribute` exists as part of .NET Core now. We should bring back the support for it if there isn't a particularly bad reason to. In the meanwhile you should be able to add a `IDisplayMetadataProvider` to populate model metadata:

```C#
// Startup.cs
services.AddMvc(options =>
{
      options.ModelMetadataDetailsProviders.Add(new DisplayNameDetailsProvider());
});

class DisplayNameDetailsProvider : IDisplayMetadataProvider
{
    public void CreateDisplayMetadata(DisplayMetadataProviderContext context)
    {
        var displayAttribute = context.Attributes.OfType<DisplayNameAttribute>().FirstOrDefault();
        if (displayAttribute != null)
        {
            context.DisplayMetadata.DisplayName = () => displayAttribute.DisplayName;
        }
    }
}
```

**Comment by dougbu** [comment]
@pranavkm could you file a specific issue about adding (back) `[DisplayName]` support? Shouldn't require more than a bit more code in `DataAnnotationsMetadataProvider` and similar tests to those for `[Display(Name = "...")]`.

Also, which CoreFx release first included the attribute? I can see it was added in March but am not sure how the various releases line up w/ the initial commit.

**Comment by pranavkm** [comment]
Done - https://github.com/aspnet/Mvc/issues/5296.

**Comment by ongun23** [comment]
Prompt field is missing for localization!

**Comment by dougbu** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

In addition, `[Display(Prompt = "a placeholder")]` is supported. It's used as the `placeholder` attribute value for `<textarea>` elements and `<input/>` elements with `type`s `text`, `search`, `url`, `tel`, `email`, `password`, or `number`.

**Comment by ongun23** [comment]
@dougbu The problem is when you customize the attribute for providing multiple language. The problem is DisplayAttribute class is a sealed class and can not be inherit.

**Comment by dougbu** [comment]
@ongun23 as @danroth27 said
> These attributes are both part of .NET Core, so you will need to open this issue at https://github.com/dotnet/corefx/issues.
