### ISSUE TITLE
asp-fallback-href tag helper not working

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#2707]
Moved from https://github.com/aspnet/Home/issues/656

@developer1998

I have missing library at href so technically asp-fallback-href should kick in, but it does not. bootstrap-touch-carousel.min.css is missing, and it won't pick up bootstrap-touch-carousel.css
```
        <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.min.css"
              asp-fallback-href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css" />
```

**Comment by Eilon** [comment]
I think you need to set a test value so that the generated code can determine whether the original script failed. E.g. `<link rel="..." ........ asp-fallback-test-class="someCssClassToTest" .... />`

The generated JavaScript code will test for the existence of a CSS class, property, or value, and if it's not there, it'll load the fallback style.

**Comment by NTaylorMullen** [comment]
Yup @Eilon is 100% correct. Example link tag with functional fallback by specifying:

```HTML
    <link href="site.min.css" rel="stylesheet"
          asp-fallback-href="~/site.css"
          asp-fallback-test-class="someClass"
          asp-fallback-test-property="visibility"
          asp-fallback-test-value="hidden" />
```

**Comment by danroth27** [comment]
We should make it an error case to specify a fallback href without a test value. We should consider doing the same thing for the script tag helper.

**Comment by developer1998** [comment]
Thank you for addressing this.

**Comment by Anderman** [comment]
This code is not easy to test and that will leed to not functional or not optimal code. See the typo's in VS2015RC
Bootstap should not test on window.jQuery but on window.jQuery().modal
```
<script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery">
```
And jQuery is wtih capital Q
```
<script src="//ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"
               asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
               asp-fallback-test="window.jquery && window.jquery.validator && window.jquery.validator.unobtrusive">
```
As Developer I like to see some warnings. 
* Before loading resource the test should not succeed
* After loading the test should succeed.
* And a check if the fallback resource is available incl all reference to image and fonts
* An easy way to sync CDN version with fallback version

**Comment by Eilon** [comment]
@Anderman I think the templates in RC had some bugs and I believe those are fixed for the next update of VS2015 RTM. Sorry about that!

**Comment by Anderman** [comment]
@danroth27. Is it possible to take that depency one step higher and make it intellisence aware.
In the old way we create something like @HTML.someMethode(p1,p2). So HTML attributes should have compareble intelliense

**Comment by ajaybhargavb** [comment]
Note: This case is already being logged as warning in both Link and Script tag helper.

**Comment by DamianEdwards** [comment]
As @ajaybhargavb said, this is already a warning case. We'll be adding a new logger in future template updates to ensure these warnings are seen by default when debugging in VS. Our approach so far has been to **not** throw runtime exceptions for cases like this but rather log warnings as we want to minimize the error logic introduced by tag helpers over and above normal HTML & C# use (which is what Razor is all about).

We can certainly look at enhancing IntelliSense however to make completing logical groups of attributes simpler. I've made aspnet/razor#443 to track that idea.
