### ISSUE TITLE
Provide better support for embedded views.

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Mvc#2708]
Please provide better support for embedded views, historically we have had to use a custom VPP to get around this issue but it would be nice if we could use embedded razor views in a fashion similar to:

```
namespace MusicStore.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public IActionResult Index()
        {
            return View(GetType(HomeController).Assembly, "MusicStore.Views.Home.Index.cshtml");
        }
    }
}
```

The VPP workaround has always felt very much a hack. There are various reasons as to why you would want to avoid using a VPP, performance is one, compatibility with 3rd party software is another.

On SO there are many questions asking if this can be done, Eilon himself has responded to a question where someone has asked if this is supported in an older version of the ASP.NET MVC framework:
http://stackoverflow.com/questions/17466155/mvc3-and-virtual-view-without-virtualpathprovider

**Comment by pranavkm** [comment]
Have you seen our test \ sample for a site that uses embedded view files - https://github.com/aspnet/Mvc/blob/dev/test/WebSites/RazorEmbeddedViewsWebSite/Startup.cs#L22?

**Comment by Matthew-Bonner** [comment]
Sorry I completely missed it. However, after looking it appears this issue can be closed. I'll look at the code examples and review the source then create a pull request which includes more examples. Thanks for your help.

**Comment by alexsandro-xpt** [comment]
And how can I could compile views to resource without Visual Studio and more the one assembly?

`options.FileProvider = new EmbeddedFileProvider(GetType().GetTypeInfo().Assembly, "RazorEmbeddedViewsWebSite.EmbeddedResources");` is a single assembly.
