### ISSUE TITLE
Semantic-UI is Better than Bootstrap

### ISSUE THREAD

**Issue by ikourfaln** [aspnet/Mvc#2709]
Hi,

Im just proposing an enhancement, using Semantic-UI instead of Bootstrap.
I believe that Semantic UI will be the best font-end Framework. check out:
http://beta.semantic-ui.com
SUI v2.0 will be out soon, I think after 2 weeks (the creator said that).

so plz think about that

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/2568.

**Comment by danroth27** [comment]
Moving to https://github.com/aspnet/Tooling/issues/97 as this is really about what we ship in our project templates.
