### ISSUE TITLE
TagHelpers doesn't show errors when using enum type attributes

### ISSUE THREAD

**Issue by evorine** [aspnet/Mvc#2710]
While creating custom tag helpers, if we add an enum type property and populate it on views by passing the value via attribute, something happens and doesn't show any error messages. The page comes blank.

The code samples are:
```csharp
public class DemoTagHelper : TagHelper
{
    [HtmlAttributeName("asp-enum")]
    public AnEnum EnumValue { get; set; }

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        throw new Exception("Let's assume something went terribly wrong... :(");
    }
}
public enum AnEnum
{
    Foo,
    Bar
}
```
```html
<demo asp-enum="TagHelperTest.AnEnum.Foo" />
```

When changing the `EnumValue` property type from `AnEnum` to `string`, I get my error messages back.

I'm on the latest beta6 which is `6.0.0-beta6-14129` at the moment. And the runtime version is `1.0.0-beta5-12021`.
I already posted a very small project on github to reproduce the problem. It is here: https://github.com/evorine/TagHelperTest

**Comment by dougbu** [comment]
@evorine please try updating `global.json` to use a Beta 6 runtime.

**Comment by evorine** [comment]
Tried it with version `1.0.0-beta6-12085` but it's the same.
By the way when I looked it using Chrome the response's status code is **500** but the response itself is empty. So it shows me a blank page. It's like seeing a polar bear in a blizzard.

**Comment by NTaylorMullen** [comment]
@evorine Is this just a design time issue? Aka when you're writing your Razor code you expect a specific error to show up in the editor. Or does this also happen when you run your app?

**Comment by evorine** [comment]
@NTaylorMullen it is happening in run time while running the application.

**Comment by NTaylorMullen** [comment]
@evorine I investigated this and: great find! Turns out the `UseErrorPage` bit in `Startup.cs` was the part that was barfing and therefore showing an empty page. I've filed an issue to fix it here: https://github.com/aspnet/Diagnostics/issues/146.

**Comment by kichalla** [comment]
@NTaylorMullen I am able to repro this outside diagnostics' ErrorHandler middleware too.

**Comment by NTaylorMullen** [comment]
When I debugged through it, the cause was inside the core response handling of the `UseErrorPage` middleware. What are you seeing?

**Comment by kichalla** [comment]
I initially tried debugging to find the cause but I get bunch of unrelated errors in VS...

**Comment by NTaylorMullen** [comment]
@kichalla This can be closed again right?

**Comment by kichalla** [comment]
Oh yes, this can be closed
