### ISSUE TITLE
Slow Views

### ISSUE THREAD

**Issue by matthewDDennis** [aspnet/Mvc#2711]
Earlier using Beta5 sometime prior to this going to the release nightlies, my view would render in under 30 mS on the second display as I was caching the data internally.

Now, since later Beta5 and Beta6 builds, the same view is taking 500+mS, with the call to get the data taking << 1ms, measured as shown.
```c#
        [HttpGet("{id:int}/{*slug}")]
        public async Task<IActionResult> View(int id, string slug)
        {
            Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();
            var result = await _articleQuery.GetAsync(id);
            ViewBag.Duration = stopwatch.Elapsed;

            if (result.IsSuccess)
                return View(result.Value);
            else
                return HttpNotFound(result.Message);
        }
```
I suspect that the compiled view caching is broken or that the cache is registered as transient instead of singleton, but I haven't checked the code.

Update: Even the About page takes 671 mS.

**Comment by matthewDDennis** [comment]
**False alarm**.
If I run a Release Build without Debug it is FAST!!!

**Comment by dougbu** [comment]
@matthewDDennis thanks for letting us know.
