### ISSUE TITLE
UserManager.CheckPasswordAsync DbUpdateConcurrencyException

### ISSUE THREAD

**Issue by toddtsic** [aspnet/Mvc#2713]
SaveChangesAsync that follows UserManager.CheckPasswordAsync fails with DbUpdateConcurrencyException.  Same SaveChangesAsync without preceeding UserManager.CheckPasswordAsync succeeds.

Failing Example (test password followed by table update that involves user being tested):

	bool bCorrectPassword = await UserManager.CheckPasswordAsync(user, model.New_Player_Detail.TSIC_Password);
	if (bCorrectPassword)
	{
	    Family_Members record = new Family_Members()
	    {
	        Family_UserId = model.Family_Details.Family_UserId,
	        Family_Member_UserId = user.Id,
	        modified = DateTime.Now,
	        lebUserID = model.Family_Details.Family_UserId
	    };

	    db.Family_Members.Add(record);
	    await db.SaveChangesAsync();
	    return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Player: {0} has been added to your family account.", model.New_Player_Detail.TSIC_Username) });
	}

Successful Example:

	//bool bCorrectPassword = await UserManager.CheckPasswordAsync(user, //model.New_Player_Detail.TSIC_Password);
	//if (bCorrectPassword)
	//{
	    Family_Members record = new Family_Members()
	    {
	        Family_UserId = model.Family_Details.Family_UserId,
	        Family_Member_UserId = user.Id,
	        modified = DateTime.Now,
	        lebUserID = model.Family_Details.Family_UserId
	    };

	    db.Family_Members.Add(record);
	    await db.SaveChangesAsync();
	    return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Player: {0} has been added to your family account.", model.New_Player_Detail.TSIC_Username) });
	//}

Failure is at dbSaveChangesAsync:
A database operation failed while processing the request. DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded.

Running sql trace across that step shows:

	UPDATE [AspNetUsers] 
	SET [AccessFailedCount] = @p0, [ConcurrencyStamp] = @p1, [Email] = @p3, [EmailConfirmed] = @p4, [FirstName] = @p5, [LastName] = @p7, [LockoutEnabled] = @p8, [LockoutEnd] = @p9, [LockoutEndDateUtc] = @p10, [NormalizedEmail] = @p11, [NormalizedUserName] = @p12, [PasswordHash] = @p13, [PhoneNumber] = @p14, [PhoneNumberConfirmed] = @p15, [SecurityStamp] = @p16, [TwoFactorEnabled] = @p17, [UserName] = @p18, [cellphone] = @p19, [cellphoneProvider] = @p20, [city] = @p21, [country] = @p22, [dob] = @p23, [fax] = @p24, [gender] = @p25, [imageFile] = @p26, [imageFileMimeType] = @p27, [phone] = @p28, [postalCode] = @p29, [state] = @p30, [streetAddress] = @p31, [workphone] = @p32
	WHERE [ConcurrencyStamp] = @p2 AND [Id] = @p6;
	SELECT @@ROWCOUNT;

This same query run in sql management studio SUCCEEDS (even when run while the debugger is on the line "db.SaveChangesAsync".  (If you don't run the command in sql management studio but step the debugger, the above DbUpdateConcurrencyException occurs.

**Comment by danroth27** [comment]
@rustd @HaoK @rowanmiller @divega Can you guys help move this one to the right repo?

**Comment by rowanmiller** [comment]
@rustd could this be because CheckPasswordAsync is causing an update to the row, which in turn causes an update to ConcurrencyStamp?

**Comment by rowanmiller** [comment]
Actually, never mind, from the code it looks like SaveChanges shouldn't even be trying to update the User

**Comment by toddtsic** [comment]
Rowan,

Thanks for looking at this.  I just tried a different approach to validating the password and it works (code below).  The VerifyHashedPassword is returning PasswordVerificationResult.SuccessRehashNeeded.  Can I ignore, or should I deal with that?

Code showing replacement of UserManager.CheckPasswordAsync with PasswordHasher.VerifyHashedPassword:

    Family_Members record = new Family_Members()
    {
        Family_UserId = model.Family_Details.Family_UserId,
        Family_Member_UserId = thisUserId,
        modified = DateTime.Now,
        lebUserID = model.Family_Details.Family_UserId
    };

    PasswordHasher<ApplicationUser> pHasher = new PasswordHasher<ApplicationUser>();
    PasswordVerificationResult pvResult = pHasher.VerifyHashedPassword(user, user.PasswordHash, model.New_Player_Detail.TSIC_Password);

    switch (pvResult)
    {
        case PasswordVerificationResult.Success:
            db.Family_Members.Add(record);
            await db.SaveChangesAsync();
            return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Player: {0} has been added to your family account.", model.New_Player_Detail.TSIC_Username) });
        case PasswordVerificationResult.SuccessRehashNeeded:
            db.Family_Members.Add(record);
            await db.SaveChangesAsync();
            return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Player: {0} has been added to your family account.", model.New_Player_Detail.TSIC_Username) });
        case PasswordVerificationResult.Failed:
            return RedirectToAction("EditFamilyAccount", new { StatusMessage = "Credentials for new player were not valid." });
    }

**Comment by rowanmiller** [comment]
@rustd can help with the question about the result of VerifyHashedPassword 

Glad you found a workaround. On our side, we should still try and get to the route of the issue with your original code.

**Comment by HaoK** [comment]
It's safe to ignore the rehash. It's just a hint.

**Comment by toddtsic** [comment]
After trying many workarounds, I'm feeling the issue is my not understanding the effects on the SecurityTimestamp of the user record by UserManager calls.

All my code is prefaced by:

    ApplicationUser user = await UserManager.FindByNameAsync(model.New_Player_Detail.TSIC_Username);
  

I've followed this with many different UserManager calls or SignInManager calls, each of which result in an DbUpdateConcurrencyException error:

UserManager.CheckPassword
UserManager.RemovePassword
SignInManager.PasswordSignInAsync
Then in attempt to address SuccessRefreshHashNeeded:
  user.PasswordHash = pHasher.HashPassword(user, model.New_Player_Detail.TSIC_Password);
  user.SecurityStamp = Guid.NewGuid().ToString();
  await UserManager.UpdateAsync(user).ConfigureAwait(false);


Can someone help me understand the effect(s) of the original UserManager.FindByNameAsync call on the SecurityTimestamp of the referenced user, and if it is felt that is behaving correctly, what should I be doing to have the UserManager release its hold?   I realize this is a leading statement, so feel free to correct the assumptions I'm making (that SecurityTimestamp and optimistic concurrancy is the core of the issue).

**Comment by divega** [comment]
We should investigate. It is hard to tell at first glance why the exception is being thrown. I have created a new ASP.NET Identity issue to follow up on this: https://github.com/aspnet/Identity/issues/502.
