### ISSUE TITLE
Is there example/documentation of a custom view engine?

### ISSUE THREAD

**Issue by back5576** [aspnet/Mvc#2714]
I see the code for the Razor view engine, but I don't seen how view engines (including Razor) get registered with MVC

**Comment by back5576** [comment]
I think I found what I was looking for in 
Mvc/test/WebSites/CompositeViewEngineWebSite

**Comment by back5576** [comment]
I'm trying that example. But I get this error
File name: 'XslMvc' ---> Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException:
 C:\ShufflePoint\dev\XslMvc\Startup.cs(17,29): error CS1061: 
 'MvcOptions' does not contain a definition for 'ViewEngines' and no extension 
 method 'ViewEngines' accepting a first argument of type 'MvcOptions' could be found  (are you missing a using directive or an assembly reference?)

Which .net version/runtime should I use to test this?

**Comment by back5576** [comment]
The sample I had stumbled upon was a branch with this code

            // Add a view engine as the first one in the list.
            services.AddMvc()
                .ConfigureMvc(options =>
                {
                    options.ViewEngines.Insert(0, typeof(TestViewEngine));
                });
The dev branch has

            services.AddMvc()
                .ConfigureMvcViews(options =>
                {
                    options.ViewEngines.Insert(0, typeof(TestViewEngine));
                });
Using that I get a different error:

 error CS1503: Argument 2: cannot convert from 'System.Type' to 'Microsoft.AspNet.Mvc.ViewEngineDescriptor'

**Comment by dougbu** [comment]
@back5576 sounds like now you've found a sample, you're hitting versioning issues. Make sure you are using Beta 6 packages _and_ runtime when trying the `dev` sample.

**Comment by back5576** [comment]
I'm just starting - and know just enough to be dangerous. How do I assure that I am using Beta6 packages?

I did this to set the runtime
dnvm use 1.0.0-beta6-12032 -r clr -arch x86

**Comment by dougbu** [comment]
You're runtime is the Beta 6 runtime. The `project.json` file lists what packages `dnu restore` should find and `project.lock.json` what it actually found.

**Comment by back5576** [comment]
My project.json is the same as in the example. The project.lock.json has various beta6 versions.

I did a "dnvm upgrade -u" since I hadn't done that in a couple days. Now I get a different errors:

TestPartialView.cs(11,27): 
error CS1983: The return type of an async method must be void, Task or Task<T>

TestPartialView.cs(11,22): error CS0433: The type 'Task' exists in both 'System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

TestPartialView.cs(7,36): error CS0738: 'TestPartialView' does not implement interface member 'IView.RenderAsync(ViewContext)'. 'TestPartialView.RenderAsync(ViewContext)' cannot implement 'IView.RenderAsync(ViewContext)' because it does not have the matching return type of 'Task'.

TestView.cs(11,27): error CS1983: The return type of an async method must be void, Task or Task<T>

The piece of the puzzle I don't get is how to setup to run the provided examples? How does one assure they have the same runtime and packages?

Thanks,
Chris

**Comment by back5576** [comment]
Anyone? Am stuck here.

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/issues/137

**Comment by danroth27** [comment]
@back5576 Looks like you are having an issue resolving the correct `Task` type. This is probably due to a version mismatch or it could be a bad beta6 build. Make sure you are running on beta6 with a consistent set of beta6 packages.

**Comment by back5576** [comment]
I got it working by first running build.cmd in the root folder of the Mvc git project. Now I have to figure out why that worked.
