### ISSUE TITLE
Fix and enable CoreCLR tests

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2717]
Our unit test projects are missing support for CoreCLR, which has caused us to miss a few bugs.

We should do the following:
1. Enable CoreCLR for all test projects
2. ifdef out anything that can't be trivially fixed to work on CoreCLR
3. Check that in and try to reduce the number of things in category 2

The biggest blocker for now is Moq. While that's being resolved we want to make sure any new tests we write can work on CoreCLR.

**Comment by Eilon** [comment]
@pranavkm can confirm but as far as I know this is now all done with the new custom build of Moq.
