### ISSUE TITLE
Using JsonHelper to write indented JSON in a view doesn't write indented HTML

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2718]
Try this:
```
@model Product
<html>
<body>
    <section>
        @Json.Serialize(Model, new Newtonsoft.Json.JsonSerializerSettings()
        {
            Formatting = Newtonsoft.Json.Formatting.Indented,
        })
    </section>
</body>
</html>
```

It will display in a browser as a single line despite rendering with line-breaks and whitespace.
```
<section>
        {
  "Id": 1,
  "Name": "Bald-Head Wax",
  "Price": 19.95
}
    </section>
```

If we wanted to support this, we could do so by letting you pass in a `JsonTextWriter` implementation with the `Newline` and `IndentChar` set up appropriately for HTML.

**Comment by nil4** [comment]
Could use `<pre>@Json.Serialize(...)</pre>` or the [CSS `white-space` property](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) to select the *display* behaviour you need, rather than changing the JSON writer settings.

**Comment by JamesNK** [comment]
`pre` +1

**Comment by danroth27** [comment]
Agreed
