### ISSUE TITLE
Expand `InputFormatterContext` or `IInputFormatter.ReadAsync()` to make errors explicit

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2722]
Need a clear way for input formatters to indicate errors -- without `throw`ing. Handling errors more clearly fixes a bug due to gaps in the current approach.

Also need more tests covering cases where the `JsonInputFormatter` adds `ModelState` errors and other input formatters `throw`.

Currently most `IInputFormatter` implementations `throw` when they encounter an error condition. However the `JsonInputFormatter` adds `ModelState` errors in many cases. As seen in c4fa402 and mentioned in a PR [comment](https://github.com/aspnet/Mvc/pull/2695#discussion_r32681923), the obvious way to check for errors (comparing `ModelState.ErrorCount` before and after) is insufficient. Further `await formatter.ReadAsync(...) == null` is incorrect because the input may be explicitly `null`.

**Comment by danroth27** [comment]
Throwing due to input seems problematic - generally we should return a 400 level response (not a 500) if the request data is bad (ex. invalid JSON or XML).

**Comment by dougbu** [comment]
In this case, the thrown `Exception` is normally caught almost immediately. The `BodyModelBinder` executes input formatters within a `try` block with a `catch (Exception ex)` that adds `ex` to `ModelState`.

Also input formatters themselves don't usually `throw`. It's the lower-level serializers (`DataContractSerializer`, `JsonSerializer`, and `XmlSerializer` in the box) that do. We would need that `try` block in `BodyModelBinder` or most `IInputFormatter` implementations regardless. This bug is about `Exception`s not being the _only_ way to indicate errors.

**Comment by rynowak** [comment]
> Throwing due to input seems problematic - generally we should return a 400 level response (not a 500) if the request data is bad (ex. invalid JSON or XML).

This bug tracks plumbing needed to turn the response into a 400 (errors in modelstate). As @dougbu mentioned, right now errors aren't being reported correctly unless you throw.

**Comment by dougbu** [comment]
42017fa
