### ISSUE TITLE
Middleware per component.

### ISSUE THREAD

**Issue by r3db** [aspnet/Mvc#2726]
Hey guys, I'm pretty new at this middleware stuff.
I'm wondering if I can achieve the following:

I have multiple middleware instances.

``` csharp
app.UseMiddleware<Middleware1>();
app.UseMiddleware<Middleware2>();
```

Each middleware is responsible for serving it's own `razor` views and the respective `webapi`.
The reason for that is because I have a bunch of js components that are complex enough to require it's own `webapi` and views.

I've seen plenty examples of custom middleware.
The problem is that all these examples are pretty simple.
They all end up like this:

``` csharp
public async Task Invoke(HttpContext context)
{
    // They write directly to the stream.
    context.Response.ContentType = "text/html";
    await context.Response.WriteAsync("Some Content");
}
```

I'm searching for something more like this:

``` csharp
public async Task Invoke(HttpContext context)
{
    return await MvcMagic.ResolveAsync(context);
}
```

Each middleware is isolated from each other.
Is this a possibility.
Can you point me somewhere?

Thanks

**Comment by alexsandro-xpt** [comment]
Could I develop like a module development? take a look http://www.codeproject.com/Articles/614767/NET-ASP-NET-MVC-plug-in-architecture-with-embedded I wish work with asp.net vnext thing like that.

Making modular controllers within respective views separade by project, but controllers loading in runtime.

**Comment by danroth27** [comment]
@rynowak

**Comment by Eilon** [comment]
@rynowak this is somewhat related to the discussion around multi-tenancy and modular apps. So this is just for your FYI information for now; no action to take other than considering this scenario.

**Comment by alexsandro-xpt** [comment]
Needs Design +1

**Comment by rynowak** [comment]
Closing this, this is not possible to do out of the box with MVC. I'd encourage you to look at Orchard Core which has lots of great features built around using MVC in a multi-tenant way.
