### ISSUE TITLE
Should FilePathResult support *nix file systems?

### ISSUE THREAD

**Issue by sornaks** [aspnet/Mvc#2727]
It looks like a conscious decision to not support *nix file systems. Should we reconsider? - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/FilePathResult.cs#L188

**Comment by rynowak** [comment]
/cc @javiercn 

I believe the history here is that relative paths were supported in older version of MVC if we could "prove" that they were safe. I think the idea was that we wanted to support the legacy scenarios on Windows without expanding the amount of security-sensitive surface area of this API. Javier would know more.

**Comment by danroth27** [comment]
`FilePathResult` needs to work regardless of which OS you are running on.

**Comment by sornaks** [comment]
Discussed with @Eilon  about this issue and we came up with the following design.
The `FileResult` is trying to solve for two scenarios:
- Files in the current app.
- Files in the Physical file system.

So `/foo.txt` can resolve to `C:/app/foo.txt` (a path inside the app) or `C:/foo.txt` (a path in the file system). So we decided to split this into 2 `FileResult`s - `VirtualFilePathResult` and `PhysicalFilePathResult` - this reduces the complexity and gives more clarity on what each path maps to.

The following are the various inputs and what they get resolved to:

<table>
<tr><th rowspan="2">Input</th><th colspan="2">VirtualFilePathResult</th><th colspan="2">PhysicalFilePathResult</th></tr>
<tr><th>Windows</th><th>*nix</th><th>Windows</th><th>*nix</th></tr>
<tr><td>C:\foo.txt</td><td>FileNotFound</td><td>FileNotFound</td><td>C:\foo.txt</td><td>Error (given `C:` is not a directory)</td></tr>
<tr><td>C:/foo.txt</td><td colspan="4">same as above</td></tr>
<tr><td>\foo.txt</td><td>C:\app\foo.txt</td><td>/app/foo.txt</td><td>C:\foo.txt</td><td>/foo.txt</td></tr>
<tr><td>/foo.txt</td><td colspan="4">same as above</td></tr>
<tr><td>foo.txt</td><td>C:\app\foo.txt</td><td>/app/foo.txt</td><td>Error</td><td>Error</td></tr>
<tr><td>~/foo.txt</td><td colspan="4">same as above</td></tr>
<tr><td>~\foo.txt</td><td colspan="4">same as above</td></tr>
<tr><td>\\bar\foo.txt</td><td>FileNotFound</td><td>FileNotFound</td><td>\\bar\foo.txt</td><td>Error</td></tr>
</table>

Note: Both the `FilePathResult`s converts `\` to `/` before processing. So a filename containing `\` in *nix systems will fail.

**Comment by sornaks** [comment]
https://github.com/aspnet/Mvc/commit/ddc74e5396c5a09e950c5d0029bc23d452bc7783
