### ISSUE TITLE
Replace JSON.NET with Jil?

### ISSUE THREAD

**Issue by ryanelian** [aspnet/Mvc#2730]
https://github.com/kevin-montrose/Jil

Jil is faster and apparently stable (used actively by StackExchange)

I think ASP.NET should consider using Jil instead for that performance boost. Are there any known reason to not to use the library? (Searching "Jil" in issues brings zero result)

**Comment by danroth27** [comment]
Thanks for letting us know about Jil. We don't have any plans to move off of JSON.NET at this time, but you can certainly implement your own custom JSON formatter or JsonResult that uses Jil for handling JSON.
