### ISSUE TITLE
Is this comment wrong in ActionConstraintWebSite

### ISSUE THREAD

**Issue by back5576** [aspnet/Mvc#2732]
ConsumesAttribute_OveridesBaseController.cs
Says
            // should be picked if request content type is application/xml and not application/json.
I assume it should have said
            // should be picked if request content type is text/json and not application/json.
If not, what am I missing?

**Comment by rynowak** [comment]
Yep! The comment is wrong. Fixing it.

**Comment by rynowak** [comment]
2d62553122ac54db3786d9a827e4f3c82990cd73
