### ISSUE TITLE
ImageTagHelper append file version does not work for dynamic or external src paths

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Mvc#2750]
Example:
```html
<img asp-append-version="true" src="/Home/GetImage/" />
<img asp-append-version="true" src="http://www.some.com/thing.png" />
```
Need to figure out what the experience should be for these scenarios.

**Comment by ajaybhargavb** [comment]
cc @Eilon @DamianEdwards

**Comment by DamianEdwards** [comment]
We can either ignore it, log a warning, or throw an exception. In this case given that the path could be a variable value, throwing seems extreme, so I'd lean to ignoring it or logging a warning.

**Comment by ajaybhargavb** [comment]
Currently the first example ignores it but the second one throws an exception when the file provider tries to get FileInfo. We need to change that behavior.

**Comment by DamianEdwards** [comment]
The helper should be ensuring that the string is a valid file path before attempting to load it

**Comment by ajaybhargavb** [comment]
6213354b85ee4b0e7c42d0eb64fc76447e28e9fb
