### ISSUE TITLE
How to set login form url?

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Mvc#2753]
I have an authorize controller decorated with [Authorize] filter. When visit it redirect to "Account/Login.
My login route is "accounts/login.
Where i can set my login url?
Thanks for your time

**Comment by davidfowl** [comment]
MVC doesn't actually redirect to the login page. That is configured in the Cookie middleware. 

https://github.com/aspnet/Security/blob/dev/samples/CookieSample/Startup.cs#L21

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationOptions.cs#L97
