### ISSUE TITLE
Invalidating cached responses using bundling and minification features in ASP.NET MVC 5

### ISSUE THREAD

**Issue by spacecat** [aspnet/Mvc#2755]
I learned today that using cache busting or invalidating cached responses (https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#invalidating-and-updating-cached-responses) helps you as a developer to not have to worry about different static content being served to different users or visitors of your site.

After successfully adding and getting the cache-control header working in IIS I also wanted to enable cache busting for my css and js files in my ASP.NET MVC 5 application. After a couple of second of Googling I found Mad Kristenssens article "Cache busting in asp.net" http://madskristensen.net/post/cache-busting-in-aspnet  but unfortunatelly only covers how make it work in ASP.NET in general and not how to make this work in ASP.NET MVC.

Is this feature going to be available in ASP.NET MVC 6?

Also, are there any plans on adding this feature to ASP.NET MVC 5 in the near future?

**Comment by dougbu** [comment]
@spacecat have a look at the tag helpers in MVC 6 that support the `asp-append-version` attribute, a C# `bool` or `bool?`. These include `<img>`, `<link>`, and `<script>`. All these helpers generate elements with cache-busting URLs when `asp-append-version == true`.

What particular gaps do you see in MVC 5, given the ability to "make it work" there?

**Comment by spacecat** [comment]
Sounds like it shouldn't be a problem solving this in MVC 6 according to those new features you just showed me, which is great.

To be honest, in MVC 5, what I am looking for there is a complete best practice sample because I consider this type of feature an architectural part of a Web app and therefore I believe it should be part of the framework or in the default ASP.NET MVC 5 Default Templates in a File -> New Project.

Perhaps this is a trivial thing to implement but for a not so architectural guy like me it isn't that obvious how to best build those parts.

**Comment by IDisposable** [comment]
@spacecat you might find this one a bit better https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate for MVC5
