### ISSUE TITLE
System.Net.WebRequest in beta 4?

### ISSUE THREAD

**Issue by toddtsic** [aspnet/Mvc#2758]
Is there a workaround for getting System.Net.WebRequest functionality in beta 4?

code:

     System.Net.HttpWebRequest objrequest = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(post_url);

results in:

    Severity	Code	Description	Project	File	Line
    Error	CS0234	The type or namespace name 'HttpWebRequest' does not exist in the namespace 'System.Net' (are you missing an assembly reference?)	TSICV5.DNX Core 5.0	C:\Users\Todd\Documents\Visual Studio 2015\Projects\TSICV5\src\TSICV5\Common\BusinessRulesManager\BusinessRulesManager.cs	86

    

This is the last piece of functionality I need to have fully functional mvc 6 app ready to go upon release, so my fingers are crossed!  (The WebRequest is for posting credit card transactions to Authorize.net)

Thanks,

Todd

project.json:

    {
      "webroot": "wwwroot",
      "userSecretsId": "aspnet5-TSICV5-6aec2867-e934-4174-9f5f-d9c6befae354",
      "version": "1.0.0-*",

      "dependencies": {
        "EntityFramework.SqlServer": "7.0.0-beta4",
        "EntityFramework.Commands": "7.0.0-beta4",
        "Microsoft.AspNet.Mvc": "6.0.0-beta4",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta4",
        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Google": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta4",
        "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta4",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta4",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta4",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta4",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4",
        "Microsoft.AspNet.Session": "1.0.0-beta4",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta4",
        "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta4",
        "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
        "Microsoft.Framework.ConfigurationModel.UserSecrets": "1.0.0-beta4",
        "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta4",
        "Microsoft.Framework.Logging": "1.0.0-beta4",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta4",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta4"
      },

      "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000",
        "gen": "Microsoft.Framework.CodeGeneration",
        "ef": "EntityFramework.Commands"
      },

      "frameworks": {
        "dnx451": {
        },
        "dnxcore50": {
        }
      },

      "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components"
      ],
      "publishExclude": [
        "node_modules",
        "bower_components",
        "**.xproj",
        "**.user",
        "**.vspscc"
      ],
      "scripts": {
        "postrestore": [ "npm install", "bower install" ],
        "prepare": [ "gulp copy" ]
      }
    }

**Comment by Eilon** [comment]
You can use `System.Net.Http.HttpClient`, which I think is generally the preferred HTTP client on .NET.

**Comment by toddtsic** [comment]
Thanks for responding Eilon, will do.

T

**Comment by toddtsic** [comment]
Quick question.

I'm wrestling a bit with HttpClient, not for MVC reasons dependency
reasons, but Authorize.net reasons

One option I have is using Authorize.nets library from nuget
(AuthorizeNet), but as expected I get DNX Core 5.0 compiler complaints.

Can you point me in the right direction on how to incorporate asp.net 4.5
libraries into an MVC 6.  I've tried the usual "dependencies" in
project.json

"frameworks": {
    "dnx451": {
    },
    "dnxcore50": {
    }
  },

but I can't get it to work.  I'm sure this an understanding deficit on my
part and I just need a point in the right direction on how to incorporate
4.5 libraries

Thanks,

T

**Comment by Eilon** [comment]
You use `dnx451` if you want to run on .NET Framework 4.5.1, and `dnxcore50` if you want to run on .NET Core. Or of course you can target both at once (which is what the project templates do).

If you're using a library that works only on .NET 4.x, you'll need to remove the `dnxcore50` from the `project.json`.

**Comment by toddtsic** [comment]
One free round of golf for you in Sedona AZ!

That's a gold mine tip, thanks!

T

**Comment by Eilon** [comment]
It's hot enough in the Seattle area already, thanks :smile:

**Comment by adamreed90** [comment]
@Eilon Were you able to get the Authorize.Net Library working with .NET Core?

**Comment by Eilon** [comment]
@adamreed90 I am not familiar with that library. Can you contact its authors to see what they have planned?

**Comment by adamreed90** [comment]
Tagged wrong person I'm sorry.  @toddtsic
