### ISSUE TITLE
[Suggestion] A New Attribute Needed For a simple parameter when doing "Post" by jQuery in Web Api

### ISSUE THREAD

**Issue by MaleDong** [aspnet/Mvc#2762]
Hello:
   You see that if I let my jQuery call something like this:
   ```
   $.post("http://localhost:8080/……",dataType:"json",data:{"id":"1"},……);
   ```
   And my actual Web Api defines:
  ```
   public int Post([FromBody] string id) {……}
  ```
  This is wrong. And I have to write something like this: 
  ```
  $.post("http://localhost:8080/……",dataType:"json",data:{"":"1"},……);
 ```
  For a single parameter posted, I must leave the "key" empty. However for a complicated type defined in the server, I can combine a json object (something like {"id":"1","name":"Bill Gates"}……). And this will be reflected into the object at the server side.

  In fact, what we want is if I can write something like this below when passing a single value by Post at the server side:
  ```
   public int Post([FromBodyForSingle] string id)   //If I use something like this attribute, "id" will be readout directly through the "Post" method.
```
  And at the client side, I can write:
  ```
   $.post("http://localhost:8080/……",dataType:"json",data:{"id":"1"},……);   //what if we can keep the "id" here to map the parameter name defined in my method, to make it empty is really an ugly thing....
```
  In my mind, the design would be better if:
  1) "FromBodyForSingleAttribute" is a new attribute ONLY FOR a single variable passed by "Post" to a Web Api's method.
  2) "FromBodyAttribute" will actually pass a json object by "Post" to a Web Api's method.
  3) "FromBodyAttribute" can only be used once in a method parameters, "FromBodyForSingleAttribute" can be used many times.

I'm not sure whether this situation also happens in FromUriAttribute?

**Comment by danroth27** [comment]
We don't plan to add an attribute to the framework for this specific case. You can either define a type with an Id property and use that in your action method signature, or you can extend the model binding system to provide a JSON value provider.

**Comment by MaleDong** [comment]
@danroth27 : What do you mean by "You can either define a type with an Id property and use that in your action method signature"?

**Comment by danroth27** [comment]
Instead of 
``` c#
public int Post([FromBody] string id) {……}
``` 
you can write 
``` c#
public int Post([FromBody] Foo foo) {……}
``` 
where `Foo` looks like:
``` c#
public class Foo
{
    public int Id {get; set;}
}
```

You can then send `{"id":"1"}` on the wire and it should bind to the `Foo` parameter.
