### ISSUE TITLE
Escaped characters in url parameters in beta4

### ISSUE THREAD

**Issue by Zeroto** [aspnet/Mvc#2763]
We use webapi for an internal api, but some of the resource identifiers have a \ in their name. I tried escaping those characters in the url, but it looks like that MVC unescapes urls before parsing them for routing causing it to either not find the route, or give the wrong value as a parameter. Added to that, it seems that a \ will be converted to a / so even if I use a greedy parameter it still results in the wrong value.

Examples:
route: "list/{id}" 
url "list/test\" 
Matches route but gives "test" as a value for id

route: "list/{id}"
url "list/test%5C"
Matches route but gives "test" as a value for id

route: "list/{*id}"
url "list/test%5C"
Matches route but gives "test/" as a value for id

**Comment by danroth27** [comment]
@Tratcher Is this happening at the HTTP abstractions layer?

**Comment by Tratcher** [comment]
This happens all the way down in Http.Sys, there's not much we can do about it.
