### ISSUE TITLE
Recommanded way to handle private static folders bound to a vNext Class Library (Package)

### ISSUE THREAD

**Issue by IsaacSee** [aspnet/Mvc#2764]
Hello, 

We are building a multi-site platform using vNext framework.

One of our requirement is to have **shared class libraries with a private static files folder** with the following constraints :
- It should be private and only accessible via file system
- It should be browsable and manualy updatable (even after a publication)
- It should not be the result of a copy into each wwwroot at build or publish time

Right now we rely on the **do not** "Produce outputs on build" build type (dont know if this build/publish difference has a name) in order to keep our class libraries folder structure after publication.

We rely on the fact that all class libraries folders are adjacents with aspnet websites folders, then from 
we compute ApplicationEnvironment.ApplicationBasePath to move a folder up, then find our private folder in the class library subfolder.

It works well but does not feels robust enought, and breaks as soon as we produce DLL on build/publish.

Is there a clean way to retrieve a class library **BasePath** without depending on the build type (aka. retrieve a nuget package folder base or a class library source folder, depending on the dependency resolution) ? And a way to keep our private static folder instact during the packaging process (without including theses files as embeded resouces).

**Comment by rynowak** [comment]
This doesn't seem related to MVC. We don't own publishing or build.

You might want to take a look at orchard core https://github.com/OrchardCMS/Orchard2 which solved a lot of these issues. In particular they allow you to have a content folder that rides along with each project.

/cc @Eilon suggest closing
