### ISSUE TITLE
[Localization]: Fix ViewLocalizer so it works for layouts too

### ISSUE THREAD

**Issue by kirthik** [aspnet/Mvc#2767]
`ViewLocalizer` cannot be used on layout pages since the logic in `Contextualize` method reads current view to get the resources file. Since `ViewContext.View` property does not point to layout,  layout specific resources are not localized. Today we have to use `IStringLocalizer` for this scenario.

We should come up with a solution where `ViewLocalizer` works for layouts too.

**Comment by danroth27** [comment]
@damian

**Comment by Eilon** [comment]
@DamianEdwards do we want this for beta8? If so, we need to discuss a design.

**Comment by dougbu** [comment]
Hit this issue while experimenting. For the same reason, localization does not work as expected in `_ViewStart.cshtml` files e.g. when setting a default `ViewData["Message"]` value. This breaks componentization and means resources must be repeated for all top-level views.

Suggest `ViewLocalizer` [line 101](https://github.com/aspnet/Mvc/blob/490fcf1ab4d416ee6cc140797c2377e352677bda/src/Microsoft.AspNet.Mvc.Localization/ViewLocalizer.cs#L101) should use `viewContext.ExecutingFilePath` and not the current `viewContext.View.Path`. The first changes much more frequently.

**Comment by Eilon** [comment]
Can you clarify? Do you mean that _ViewStart is picking up resources from the real view that's running? If so, I agree that's wrong.

**Comment by dougbu** [comment]
> `_ViewStart` [and `_Layout`] is picking up resources from the real view that's running?

Yes, that's what I and @kirthik meant. Fortunately one design (thinking of the Needs Design label) is a one-line fix.

**Comment by DamianEdwards** [comment]
ViewLocalizer should use ViewContext.ExecutingFilePath when constructing the resource base name
