### ISSUE TITLE
What-if-mode for Routes, Binding and Views

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Mvc#2772]
As a tools author, I would like to be able to create a UI which lets me allow users to do the following for each case: 
- Routes: provide a URI and see how the route is resolved
- Binding: provide binding data to see what the resulting binding is
- Views: provide view data to see what view is targeted

This would be used predominately during development to allow various experiments to take place. It wouldn't replace unit testing, etc, but would serve as a what-if-mode for developers who are learning or trying out various options. 

After talking with @rynowak it looks like there really isn't a happy path for this at the moment, but with a combination of some basic instrumentation and diagnostics APIs (which are under development for other purposes anyway) this could be made possible.

**Comment by Eilon** [comment]
Closing because we have no plans to support this.
