### ISSUE TITLE
TagHelpers won't work in @<text>...</text> code blocks

### ISSUE THREAD

**Issue by evorine** [aspnet/Mvc#2773]
MVC does not support using tag helpers in `@<text></text>` blocks.

I have a method which waits `Func<object, HelperResult>` type argument to accept html codes sent from views.
It is like:
```csharp
public void Html(Func<object, HelperResult> html)
{
    //...
}
```
View code:
```cshtml
@MyObject.Html(@<html><a this-is-a-tag-helper="">Foo</a></html>)
```

And I receive this error:
> The 'await' operator can only be used within an async lambda expression. Consider marking this lambda expression with the 'async' modifier.
```
 __tagHelperExecutionContext.Output = await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
```
and
```
await WriteTagHelperToAsync(__razor_template_writer, __tagHelperExecutionContext);
```

Will this be supported?

**Comment by danroth27** [comment]
Yeah, looks like a bug.

**Comment by NTaylorMullen** [comment]
Moved over to Razor https://github.com/aspnet/Razor/issues/494
