### ISSUE TITLE
Run middleware in MVC pipeline

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#2775]
There is a lot of duplication between the middleware and filters. In other frameworks (ex expressjs) you can run middleware as far away as the pipeline and as close as the action.

**Comment by rynowak** [comment]
:heart_eyes:

**Comment by danroth27** [comment]
@davidfowl Do we have any good concrete scenarios to drive this discussion? What middleware would it make sense to run this way? Any examples from the expressjs world?

**Comment by tugberkugurlu** [comment]
@danroth27 I was thinking about something similar to this. Any idea how this might be done considering the middlewares would have already been run when you reach to a filter.

**Comment by rynowak** [comment]
@tugberkugurlu - if you're thinking about trying something like here, here's some rough design notes from our team's discussion about it.

- build a middleware pipeline that's standalone
- build an `IAsyncResourceFilter` adapter that invokes the pipeline
- as the last item in the middleware, add some code that calls `next()` in the resource filter
- allow control to flow back into middleware as filters are unwinding

Now you have the ability to build a pipeline of middleware, and thanks to filters you can apply it to an arbitrary scope in MVC.

This part is relatively easy to build - the main reason it's on our backlog is that there's a substantial buildup of glue code and configuration helpers required to make it usable for most users.

**Comment by Eilon** [comment]
Closing because we did this! https://github.com/aspnet/Mvc/issues/5161
