### ISSUE TITLE
Model vs. Value Providers Incorrect Precedence

### ISSUE THREAD

**Issue by khalidabuhakmeh** [aspnet/Mvc#2781]
### Model vs. Value Providers Incorrect Precedence 

The model value I pass to a HTML helper from a controller is being taken over by any matching value found in the ValueProviders.

### Functional impact

This interferes with formatting of input and may actual present incorrect data to the user. 

### Minimal repro steps

Full explanation can be found at http://www.khalidabuhakmeh.com/a-bug-with-asp-net-mvc-valueproviders-and-formatting

#### C# Code

```csharp
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(InputModel input)
        {
            return View(input);
        }
    }

    public class InputModel
    {
        public int Number { get; set; }
    }
}
```

#### Razor Code

```html
@model WebApplication3.Controllers.InputModel
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <fieldset>
            <legend>Example</legend>
            @using (Html.BeginForm("Index", "Home", FormMethod.Get))
            {
                <div class="form-group">
                    @Html.TextBoxFor(m => m.Number, "{0:C}", 
                        new { @class = "form-control" })
                </div>
                <input type="submit" value="submit" class="btn-primary" />
            }
        </fieldset>
    </div>
</div>
```

Note, in our call to `TextBoxFor` we are applying a format. Now, let's run our application.

1. Our first step is to visit the form page. In our case that is at the root of the site, or `Home#Index`. We will be presented with our form, which displays our formatted information correctly in the form of  `$0.00`. Nothing surprising here.

![Step1](https://silvrback.s3.amazonaws.com/uploads/4506b91c-46a7-4bab-bbff-1d818fffc31c/Step_1_large.jpg)

2. Our next step is to submit our form with some new input. I just submit the same value of `$0.00` for simplicity sake. I've made this form a `GET` so we can follow the progress via the  querystring. Note that the `$` is in the querystring url encoded as `%24`

![Step 2](https://silvrback.s3.amazonaws.com/uploads/9cd983e9-3172-4bb6-bf47-7a5b7cb3e9da/Step_2_large.jpg)

3. All good so far. What if we change the querystring parameter to reflect another valid value, like `1000`?

![Step 3](https://silvrback.s3.amazonaws.com/uploads/6421ed17-4d8a-4d73-b12e-71ae7a1f18cd/Step_3_large.jpg)

Ok... What is going on?! The formatting of `{0:C}` is no longer being applied. We are getting the raw value from the querystring. Our formatting is not being respected.

### Expected result

The result I pass into the HTML helpers / to my view is the final expected value. Once the model is sent to my view, the view and helpers should not try and hydrate further.

### Actual result

The value in my HTML Helper output is being hydrated by the ValueProviders.

### Workaround

Clear all values from `ModelState` before calling `View()`.

### Further technical details

Can be found at http://www.khalidabuhakmeh.com/a-bug-with-asp-net-mvc-valueproviders-and-formatting

**Comment by danroth27** [comment]
The behavior you are seeing is expected. If the value is in ModelState then it is always used as is without modification. This is so that you can correctly echo back to the user the original input.

**Comment by Eilon** [comment]
It's also worth noting that it's quite rare to have a currency-formatted value in a textbox because the end-user almost never types in the currency. Usually the currency indicator is *outside* the input, and the user types in only the number.
