### ISSUE TITLE
Dependency Injection in Filters

### ISSUE THREAD

**Issue by prasannapattam** [aspnet/Mvc#2782]
Is it possible to do a DI in Filters. I am looking for Property injection. I want to inject SignInManager into my Filter. I would like to see whether user is signed in and if not Signin the user

**Comment by rynowak** [comment]
Yes, you can use DI in filters. 

You have a small decision point to make about whether or not you want the *filter itself* to be registered with DI. I'll provide examples with both. You can find more examples in the MVC sample: https://github.com/aspnet/Mvc/blob/dev/samples/MvcSample.Web/Startup.cs

1. My filter is registered in DI
---

**First** add your filter to the service collection. With the built-in DI system that looks like:
```
services.AddSingleon<MyFilter>(); // Choose whatever service lifetime makes sense
```

Registering the filter class in DI allows you to control the lifetime as well as use an advance features of your DI system that you need.

**Then** Annotate an action or controller with `ServiceFilterAttribute`
```
[ServiceFilter(typeof(MyFilter))]
public void MyAction()
{
}
```

2. My filter is not registered in DI - but needs DI service in the constructor
---

Annotate an action or controller with `TypeFilterAttribute`
```
[TypeFilter(typeof(MyFilter))]
public void MyAction()
{
}
```

Using `TypeFilterAttribute` doesn't require registering the filter class in DI so it has fewer steps.

**Comment by prasannapattam** [comment]
Thanks. I will TypeFilter as I need to pass additional parameters to the Filter as well.
