### ISSUE TITLE
is UseErrorHandler() deprecated?

### ISSUE THREAD

**Issue by back5576** [aspnet/Mvc#2786]
I've seen it in some sample code, but not recently, and I don't see it in the repo.

**Comment by rynowak** [comment]
Error handler middleware and all of these sorts of things live in the diagnostics repo. https://github.com/aspnet/Diagnostics/blob/dev/samples/ErrorHandlerSample/Startup.cs

It's all usable outside of MVC.

**Comment by back5576** [comment]
Thanks

**Comment by back5576** [comment]
I am not getting routed to /home/error on errors. My Configure() has

            app.UseMvcWithDefaultRoute();
            app.UseStaticFiles();
            app.UseRuntimeInfoPage();
            app.UseErrorHandler("/Home/Error");

I can open /home/error directly and it works

**Comment by davidfowl** [comment]
You need to change the middleware order, it is very important

**Comment by back5576** [comment]
Thanks. For those who find this, I changed as follows and it works:
            app.UseErrorHandler("/Home/Error");
            app.UseMvcWithDefaultRoute();
            app.UseStaticFiles();
            app.UseRuntimeInfoPage();
