### ISSUE TITLE
FileStreamResult should be renamed to StreamResult

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#2787]
There's nothing File* about it /cc @rynowak

**Comment by rynowak** [comment]
We need to (briefly) consider legacy. I believe @Eilon was saying the other day that names of action result classes rarely show up in user code.

**Comment by Eilon** [comment]
Yeah the type names we don't super care about. It's the helper factory methods on Controller that matter a lot.

**Comment by Eilon** [comment]
That is to say: we can rename the types all we want. But breaking the helper methods on Controller is bad.

**Comment by ajaybhargavb** [comment]
@davidfowl, spoke to @Eilon and decided not to do this. We can return the stream directly from an action and `StreamFormatter` will take care of it.
