### ISSUE TITLE
Tag helpers are not processed inside IE conditional comments

### ISSUE THREAD

**Issue by Taritsyn** [aspnet/Mvc#2788]
I use ASP.NET 5 Beta 5. In `_Layout.cshtml` file I have the following code:

	

	
		<script src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"
			asp-fallback-src-include="~/scripts/lib/jquery/jquery.min.js"
			asp-fallback-test="window.jquery"
			asp-file-version="true">
		</script>
	

The output I get the following HTML code:

	

	
		<script src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js">
		</script>
	<script>(window.jquery||document.write("<script src=\"\/scripts\/lib\/jquery\/jquery.min.js?v=pXtSQrmprcTB74RsNlFHuJxHK5zXcPrOMx78uWU0ayU\"><\/script>"));</script>
	

From HTML code it is seen, that the tag helper in the first conditional comment was not processed.

**Comment by danroth27** [comment]
@DamianEdwards 

We'd like to avoid adding support for IE conditionals in the Razor parser given that "as of Internet Explorer 10, conditional comments are no longer supported by standards mode" (see https://msdn.microsoft.com/en-us/library/ms537512(v=VS.85).aspx). One thought is that it should be straight forward to create a tag helper that will render the IE conditional for you.

@ajaybhargavb Can you put together a sample for this? Talk to @Eilon for some design ideas.

**Comment by Eilon** [comment]
Something like this:

```html
<conditionalComment mode="DownlevelHidden" expression="lt IE 9">
    <script src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.1.min.js"
        asp-fallback-src-include="~/scripts/lib/jquery-compat/jquery.min.js"
        asp-fallback-test="window.jquery"
        asp-file-version="true">
    </script>
</conditionalComment>

<conditionalComment mode="DownlevelRevealed" expression="gte IE 9">
    <script src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"
        asp-fallback-src-include="~/scripts/lib/jquery/jquery.min.js"
        asp-fallback-test="window.jquery"
        asp-file-version="true">
    </script>
</conditionalComment>
```

**Comment by bandico0t** [comment]
Hello guys.
Is this problem resolved?
I've found this link https://forge.typo3.org/issues/17640.
Am i right, that ieCondition isn't included in the core project? And if I'm right, have you any ideas how to fix this problem?

**Comment by danroth27** [comment]
Take a look at https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.TagHelperSample.Web/TagHelpers/ConditionalCommentTagHelper.cs and see if it addresses your scenario.
