### ISSUE TITLE
Repeatedly loading a view causes out of memeory exception

### ISSUE THREAD

**Issue by JonnySedman** [aspnet/Mvc#2790]
Using VS2015 RC (Win 7 pro), create a new project, choose the asp.net 5 website template. Run the project, the memory usage levels out at about 100mb. 

![mem](https://cloud.githubusercontent.com/assets/13236815/8569784/e0a33e5a-2572-11e5-81e5-db851af24e98.PNG)

Navigate to the other pages a bunch of times. The memory usage climbs and is never released, eventually leading to an out of memory exception. Below is after 12-15 page loads for the template, no code modified.

![bigmempng](https://cloud.githubusercontent.com/assets/13236815/8569803/0e158294-2573-11e5-98e2-fd82737fc53e.PNG)

If you have a large view this can happen very quickly.

**Comment by alexsandro-xpt** [comment]
Bizarre...

**Comment by rynowak** [comment]
Thanks for the report, I'm still investigating, but it looks like browserlink is the culprit.

Remove `app.UseBrowserLink()` from startup and you should see things getting collected.

**Comment by JonnySedman** [comment]
Looks like that's fixed it thanks!
