### ISSUE TITLE
Razor is not caching results for views that don't exist

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2796]
Nothing is cached when looking for a view that doesn't exist, causing us to repeat the file lookup each time it's requested.

This is a big problem when using `EditorFor` because the default templates are frequently requested and rarely customized. Here's the offending code:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/Compilation/CompilerCache.cs#L108

Suggestion from @pranavkm is to fold this case into `OnCacheMiss` and make that method capable of storing data about a file that doesn't exist on disk.

**Comment by davidfowl** [comment]
You don't want this to be unbounded righ? What misses do we want to cache? Also what did mvc 5 do?

**Comment by pranavkm** [comment]
We had a bit of caching using the `IVirtualPathPageFactory` but it was short-lived. In our case, we would cache a null result along with a file watch on that specific path.

**Comment by rynowak** [comment]
>You don't want this to be unbounded righ?

@davidfowl - this isn't based on user input, it's based on pages that the app is programmed to render. In a properly programmed app there will still be lots of misses that aren't errors due to display/editor templates. In the case of editor/display templates, the bounding factor is the number of types used in views.

This bug means we go to disk for every `@Html.EditorFor`

**Comment by rynowak** [comment]
:heart_eyes_cat:
