### ISSUE TITLE
Consider a rename of the ViewLocationExpander

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Mvc#2806]
Please consider renaming the ViewLocationExpander and supporting interfaces/classes to ViewPathProvider or similar.

The reason for this is that the implementation may not result in an expanded location; secondly the location is in fact part of a UNC/URI (minus protocol host port document) path and therefore using naming conversion of ViewPathProvider seems more akin to the actual function performed; namely providing a path for a given View.

**Comment by danroth27** [comment]
Thanks for the suggestion, but we think the current name best reflects the primary intention of the class.
