### ISSUE TITLE
Add URL resolving TagHelper to replace Razor ~ functionality.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2807]
This is in reaction to the conversation: https://github.com/aspnet/Razor/issues/427#issuecomment-120494046

Today Razor special cases `~/` at the beginning of attributes and treats them as "resolve an application relative URL"; however, it does this for every attribute which is overkill/incorrect. After investigating the attributes that have URL capability in Razor the list warrants something less hard coded into the core of Razor to resolve application relative URLs.

The list of HTML5 url based attributes I was able to find are:
- href : `<a>`, `<area>`, `<link>`, `<base>`
- src : `<audio>`, `<embed>`, `<iframe>`, `<img>`, `<input>`, `<script>`, `<source>`, `<track>`, `<video>`
- action : `<form>`
- cite : `<blockquote>`, `<del>`, `<ins>`, `<q>`
- data : `<object>`
- formaction : `<button>`, `<input>`
- icon : `<menuitem>`
- itemid : everything
- manifest : `<html>`
- poster : `<video>`
- archive : `<object>`, `<applet>`

The `TagHelper` should exist in `Microsoft.AspNet.Mvc.Razor` and should be auto-added to Razor pages (much like how we auto add `@inject` directives). It should inspect `TagHelperOutput.Attributes` and `TagHelperOutput.TagName` for the various combinations listed above and resolve URLs if they begin with `~/`. Lastly, it should have an `[EditorBrowsable(EditorBrowsableState.Never)]` attribute to prevent excess highlighting in the Razor editor (will work once https://github.com/aspnet/Razor/issues/447 is completed).

**Comment by Bartmax** [comment]
One question, about data attributes? I may want to do `data-bigImageSource="~/Images/big/"` In this case I should use `data-bigImageSource=@Url.Content("~/images/big/")` ?

**Comment by NTaylorMullen** [comment]
Correct.

**Comment by Bartmax** [comment]
:+1: thank you.

**Comment by NTaylorMullen** [comment]
0ef68eefc898247fe6a3c6d6a8ab8820ea2b34e4
