### ISSUE TITLE
RegularExpressionAttribute has a bug

### ISSUE THREAD

**Issue by zeusro** [aspnet/Mvc#2809]
here is my code.it is almost same as the 

     [RegularExpression(@"^[_a-zA-Z0-9]{6.24}?$", ErrorMessage = "{0}shit")]
     public string Pwd { get; set; }

while Pwd="123456aa",the method IsValid will return false.
but 

            string pwd = "123456aa";
            Regex regex2 = new Regex("^[_a-zA-Z0-9]{6,24}?$");
            Match match = regex2.Match(pwd);
            Console.WriteLine(match.Success && match.Index == 0);
            Console.WriteLine(match.Length == pwd.Length);
they are all true.It really makes no sense.

**Comment by rynowak** [comment]
> ^[_a-zA-Z0-9]{6.24}?$

> ^[_a-zA-Z0-9]{6,24}$

Your working one has a comma, do you think that's the issue? 

Did you look at the errors in `Controller.ModelState` - are you sure it's coming from the regex validator and not something else.

**Comment by zeusro** [comment]
reply rynowak :

        string pwd = "123456aa";
        Regex regex2 = new Regex("^[_a-zA-Z0-9]{6,24}?$");
        Match match = regex2.Match(pwd);
        Console.WriteLine(match.Success && match.Index == 0);
        Console.WriteLine(match.Length == pwd.Length);
the result is still same as I have been said.

**Comment by zeusro** [comment]
And it seem web api   does not supports   IValidatableObject   in  ApiController.Validate.

it seems that it only supposts the ValidationAttribute and will never run IValidatableObject's Validate method.

    public class TestController : BaseApiController
    {

        [System.Web.Http.HttpPost]
        public HttpResponseMessage Register2([FromBody] DRegister2 dto)
        {
            if (!IsValid(dto))
                return base.DefaultHttpResponseMessageCustomModelBindErrorHandle();
             return new HttpJsonResponseMessage<JMobileMsg>(new JMobileMsg(true, "right"), HttpStatusCode.OK);
        }

    }

        public class BaseApiController : ApiController
    {

        protected bool IsValid(object valueObject)
        {
            if (valueObject == null)
                return false;
            Validate(valueObject);
            
            return ModelState.IsValid;
        }

        public HttpResponseMessage DefaultHttpResponseMessageCustomModelBindErrorHandle()
        {
            var errors = ModelState.Values;
            foreach (var item in errors)
            {
                foreach (var item2 in item.Errors)
                {
                    var errorMessage = item2.ErrorMessage;                 
                        return new HttpJsonResponseMessage<JMobileMsg>(new JMobileMsg(false, errorMessage), HttpStatusCode.BadRequest);
                }
            }

        }
    }
    public class JMobileMsg
    {
        public JMobileMsg(bool b, string m)
        {
            Result = b;
            Msg = m;
        }
        public bool Result { get; private set; }

        public string Msg { get; private set; }

        public override string ToString()
        {
            return string.Format("Result:{0};Msg:{1}", Result, Msg);
        }
    }

Here is  my unit test 

        [Test]
        public async Task 注册3()
        {
            var client = new HttpClient();
            string url = WebAPIUtility.CreateUrl("TestController", "Register2");
            Console.WriteLine(url);
            var dto = new DRegister2()
            {
                Pwd = "123456aa",
            };
            await client.PostAsync(url, new ObjectContent(typeof(DRegister2), dto, new JsonMediaTypeFormatter())).ContinueWith(async t =>
            {
                Console.WriteLine(t.Result.StatusCode);
                string result = await t.Result.Content.ReadAsStringAsync();
                Console.WriteLine(result);
                NUnit.Framework.Assert.AreEqual(t.Result.StatusCode, HttpStatusCode.OK);
            });
        }

environment:
Microsoft-IIS/8.5
.net framework 4.5.
web api 5.2.3

**Comment by ctolkien** [comment]
`^[_a-zA-Z0-9]{6.24}?$` doesn't match `123456aa`, `^[_a-zA-Z0-9]{6,24}?$` does.

**Comment by rynowak** [comment]
> environment:
> Microsoft-IIS/8.5
> .net framework 4.5.
> web api 5.2.3

How much of what you've posted here is relevant to ASP.NET 5 / MVC 6? WebAPI 5.X bugs should go to https://aspnetwebstack.codeplex.com/

In your sample controller code, you're calling `Validate<T>(...)` as `Validate<object>(...)`, which means that validation is going to occur treating the model type as `object`. Pass in the right type and you should see it use your `IValidatableObject` implementation.

**Comment by rynowak** [comment]
As, I setup a project using this validation attribute. If I change the regex to `^[_a-zA-Z0-9]{6,24}?$` it works as expected.

**Comment by zeusro** [comment]
@ctolkien  I can't see  any different between

     ^[_a-zA-Z0-9]{6.24}?$ 

and

     ^[_a-zA-Z0-9]{6,24}?$

**Comment by zeusro** [comment]
Reply  @rynowak  :+1: 
sorry for that.Sometimes the symbol is too small to discern.such like '.' and ','
