### ISSUE TITLE
MVC Create controller manualy

### ISSUE THREAD

**Issue by gvx111** [aspnet/Mvc#2811]
How create controller dynamic. I'm using MVC 6 beta 4. 
How can i make custom factory controller.
Also what is alternative of ControllerBuilder? In MVc 6 doesnt exist ControllerBuilder
I try to do dynamic controller with dynamic actions.
Please help me.

**Comment by rynowak** [comment]
Can you give more information about what you're really trying to accomplish? The controller factory exists as a replaceable service, but there's an easier way to do many things that used to be done by replacing it.

**Comment by gvx111** [comment]
I want to create controllers action from database. I have table controller and also actions
action table has properties { ViewPath, ActionName } Where actionName is {Controller}/{ActionName}
I want build pages like this. How can i make it?

**Comment by alexsandro-xpt** [comment]
Nice question.

**Comment by gvx111** [comment]
no one can help us?

**Comment by rynowak** [comment]
The best answer here is probably an explanation and some suggestions about how you could take things further. There are a few big rocks in the framework that you'll be moving, and how you want to do that is something you'll have to figure out based on your requirements. Some of these changes will work with what you're doing and some won't.

It's easiest to think about if you trace what `MvcRouteHandler` does:
1. Discover Actions
2. Select an Action (based on the route data)
3. Create an Invoker
4. Run the Invoker

The biggest change you'll have to deal with is that MVC6 now has a descriptor model for actions, meaning that we assume that we can know at any point in time the set of all actions that exist in the application and how to select them based on route data. See `ActionDescriptor` and `ControllerActionDescriptor`. The key decision point here is if you want your *dynamic* actions to be discoverable. If you do, then you'll want to create and register an `IActionDescriptorProvider` implementation that looks them up and provides a descriptor for each one.

**OR**

You could also create an `IActionDescriptorProvider` that returns a single AD and uses Catch-All route value constraints to match any value for `controller` and `action`. See: https://github.com/aspnet/Mvc/blob/dev/test/WebSites/RoutingWebSite/CountrySpecificAttribute.cs and its usage.

The `DefaultActionSelector` builds a table based on the required route values for all actions, and then matches the incoming route data against the known values.  You probably won't have to customize this, but you should be aware of how it works.

Lastly you'll need to create and register an `IActionInvokerProvider` that knows how to create an invoker for your custom action type.
