### ISSUE TITLE
Checkbox with "disabled" attribute always post back with false value

### ISSUE THREAD

**Issue by zabulus** [aspnet/Mvc#2813]
```.cshtml
@Html.CheckboxFor(x=>x.Checked, new {@disabled="disabled"})
```
No matter what value ```Model.Checked``` has it always posts back as false.
Such behavior is supported by the hidden field, that have ```value="false"``` in all cases and a disabled input field that never posts back his value field.
Is this behavior is by design?

**Comment by dougbu** [comment]
This behaviour is expected. Since the given attributes are added only to the visible `<input>`, you've prevented the `true` value's submission -- even if `checked`.

I suggest adding `@Html.HiddenFor(x=>x.Checked)` prior to the checkbox.

**Comment by zabulus** [comment]
I wonder what the purpose of ```<input ...hidden...``` that added after the checkbox input in that case? Doesn't it double the Checked value in case disabled is absent?
I've made my extension ```DisabledCheckboxFor(x=>x.Checked)``` that works as ```CheckboxFor``` but puts value of ```Checked``` to the hidden input value attribute, and it works fine.
> I suggest adding @Html.HiddenFor(x=>x.Checked) prior to the checkbox.

I've already found a couple of links with this workaround, the question asked for clarification.

**Comment by dougbu** [comment]
> what the purpose of <input ...hidden... that added after the checkbox input in that case? 

Your case is not the normal one. Without the hidden field, no value is submitted when the checkbox is not checked. That leads to model binding errors in most cases.

Separately attributes are not added to the hidden field because most don't apply and many would make the element invalid.

**Comment by zabulus** [comment]
In case I add ```disabled="disabled"``` no value from *checkbox* submitted as well, no matter checked or not. If hidden field workarounds not checked and not disabled checkbox, why don't use it for workarounding checked and disabled checkbox?

**Comment by dougbu** [comment]
> why don't use it to workaround checked and disabled checkbox?

Because the system does not special case your scenario.
