### ISSUE TITLE
ViewData property in ViewResult is Null

### ISSUE THREAD

**Issue by aaron-hammond** [aspnet/Mvc#2814]
HI,

I'm having a little trouble with returning a ViewResult from an orchestrator.

Where in previous versions of MVC we've done this:

        return new ViewResult
        {
            ViewName = "Index",
            ViewData = {Model = _formViewModelBuilder.BuildModel()}
        };

In MVC 6 this throws a null reference exception. Setting the model property of the ViewData is invalid as the value of ViewData is null? I believe this has something to do with dependency injection but i can't find a concrete explanation anywhere as to why this behavior is happening.

The simplest way i can get this to work is something like:

           return new ViewResult
            {
                ViewName = "Index",
                ViewData = new ViewDataDictionary<FormViewModel>(ViewData, model)
            };

This uses the Microsoft.AspNet.Mvc.Controller.ViewData property. I can pass this property through to the orchestrator but i'm not sure if this is just plain wrong and i'm missing a trick here?

Any help would be appreciated.

Thanks

**Comment by dougbu** [comment]
`ViewResult` is much simpler in MVC 6 than MVC 5. Only the methods have behaviour now. And unfortunately for this particular case, it's no longer possible to create a `ViewDataDictionary` instance without a `IModelMetadataProvider` implementation or another `ViewDataDictionary` instance.

What is your general scenario? Why not set `ViewData.Model` and create a `ViewResult` instance as in `Controller.View()`?
``` c#
            // Do not override ViewData.Model unless passed a non-null value.
            if (model != null)
            {
                ViewData.Model = model;
            }

            return new ViewResult()
            {
                ViewName = viewName,
                ViewData = ViewData,
                TempData = TempData
            };
```

**Comment by aaron-hammond** [comment]
@dougbu Thanks for the response. 

In our applications i try to keep a consistent approach with the architecture, we use an orchestrator pattern to keep the controllers as lightweight as possible:

Consider:

public class FormController {

        private readonly IFormOrchestrator _orchestrator;

        public FormController(IFormOrchestrator orchestrator)
        {
            _orchestrator = orchestrator;
        }

        public IActionResult Index()
        {
            return _orchestrator.GetIndexResult();
        }
}


public class FormOrchestrator : IFormOrchestrator {

        public IActionResult GetIndexResult()
        {            
            var model = _formViewModelBuilder.BuildModel();

            return new ViewResult
            {
                ViewName = "Index",
                ViewData = // here is where we would have created the viewdata.
            };
        }
}

Based on the new implementation i'm assuming the best way to achieve what i want is to pass the viewdata property from the controller to the orchestrator as follows?

public class FormController {

        ...

        public IActionResult Index()
        {
            return _orchestrator.GetIndexResult(ViewData);
        }
}


public class FormOrchestrator : IFormOrchestrator {

        public IActionResult GetIndexResult(ViewDataDictionary viewData)
        {            
            var model = _formViewModelBuilder.BuildModel();

            return new ViewResult
            {
                ViewName = "Index",
                ViewData = new ViewDataDictionary<ApplicantFormViewModel>(viewData, model);
            };
        }
}

Thanks for your help in advance.

**Comment by dougbu** [comment]
Your code looks fine.

Side note: Initializing `ViewResult.TempData` using the `FormController.TempData` value may also be required for some scenarios.

**Comment by aaron-hammond** [comment]
brilliant, thanks for the help on this again, really appreciate it.
