### ISSUE TITLE
[Localization]: HtmlEncodeArguments should encode literal characters within format tokens

### ISSUE THREAD

**Issue by kirthik** [aspnet/Mvc#2821]
For this case - `{0:'{{characters that should be escaped}}b'###'b'}` it looks like Html encoding is not happening in `HtmlEncodeArguments` method. we should add some additional logic for such complex cases

**Comment by kirthik** [comment]
In additon Mono build fails for this case during formatting. So when adding a new test case for this scenario, skip running this on Mono.

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by dougbu** [comment]
Does this problem go away (on non-Mono systems) if the `isEncode` special case goes away entirely? That should essentially enforce the invariant that all characters within a format token (i.e. between un-escaped curly braces) are HTML encoded. Would mean the result of `"{{{0:x}}}"` (`"{x}"`) is HTML encoded but that sounds safer than not HTML encoding _valid_ custom format tokens e.g. `"{0:{{00}}}"`.

**Comment by dougbu** [comment]
@kirthik suggest closing this bug and working with @sornaks to file a bug on Mono about that framework's apparent `string.Format()` issues. May want a tracking bug in this repo once you've found or reported the Mono one.

**Comment by danroth27** [comment]
@kirthik It's unclear if the literal characters in the format string should actually be encoded by us. Do we not assume that resource strings are already HTML encoded?

**Comment by kirthik** [comment]
This issue is fixed. I am going to close this. string.format() does not work correctly for some tokens in Mono. I will file a separate bug for that.

@danroth For your above question, yes literals in resource strings are encoded but the ones inside the format tokens were not in the past. For example in this case - `{0:'{{characters that should be escaped}}b'###'b'}` "characters that should be escaped" But I fixed the code. They will be encoded now. Hence will close this bug.

**Comment by dougbu** [comment]
> assume that resource strings are already HTML encoded

This is an over-simplification and something we need to be careful about in our documentation.

I suggested the `"{0:'{{characters that should be escaped}}b'###'b'}"` example to demonstrate an invariant: Everything the format token expands to is HTML encoded; everything in the "fixed text" (outside a format token) is not HTML encoded. That is, the user deals with encoding only of the fixed text in the resource string.

It's certainly possible for users to end up double-encoding things by placing encoded literal characters within a format token e.g. `"{0:'%2F'###}"` but documentation should help here. This possibility is much less problematic than not encoding at all.

I do _not_ recommend complicating our code to the point where it would special-case literal characters: They vary per argument type e.g. `#` is a literal character if the argument is a `string`; checking for back-slashed or quoted characters isn't enough.
