### ISSUE TITLE
Merge back https://github.com/aspnet/Mvc/commit/c1f4bfedab4610564ad2970b6e822d620ae6c04a into dev

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#2823]

**Comment by danroth27** [comment]
Please don't open issues to track dual check-ins. This should have been done when the commit was made to release. If you see this kind of issue just go ahead and fix it.

**Comment by pranavkm** [comment]
The entirety of https://github.com/aspnet/Mvc/issues/2648 was undone because I couldn't figure out how to merge it back in to dev. Should I just reopen the work item and close this?

**Comment by danroth27** [comment]
Sounds reasonable.
