### ISSUE TITLE
[Localization]: Enable localization support in MVC 

### ISSUE THREAD

**Issue by kirthik** [aspnet/Mvc#2824]
this is currently in PR - https://github.com/aspnet/Mvc/pull/2701

**Comment by dougbu** [comment]
@kirthik can this be closed now? That is was it the change that went in for Beta 6?

**Comment by kirthik** [comment]
Merged d8a523a07f76f722b00a2a95f74668b9fc93e6a4

**Comment by pnvpratik** [comment]
@kirthik  is there a sample which shows  how to use the localization with MVC 6 project ? I cant locate any documentations / samples on localization.

**Comment by yhax** [comment]
^ bump

**Comment by michalstepien** [comment]
:up:

**Comment by dougbu** [comment]
@pnvpratik, @yhax, @michalstepien Not exactly a sample but the [localization web site](https://github.com/aspnet/Mvc/tree/dev/test/WebSites/LocalizationWebSite) in the MVC functional test suite demonstrates some of the pieces that work today.

Note in particular the [`TestStringLocalizer`](https://github.com/aspnet/Mvc/blob/dev/test/WebSites/LocalizationWebSite/TestStringLocalizer.cs) used to work around one of the larger gaps in the framework. Issues such as aspnet/dnx#1263 track these gaps.

Expect documentation and stand-alone samples to come after the dust has settled...
