### ISSUE TITLE
Missing `Ok()` in `Controller`

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#2825]
I think there's a missing helper in controller to return an object. or I can't find it :)

```
public virtual ObjectResult Ok(object value);
```

so
```
[HttpGet("{id}")]
public IActionResult Detail(int id)
{
    var ret = xxx.GetById(id);
    if (ret == null) return HttpNotFound($"id {id} does not exist");
    return Ok(ret);
}
```
instead of:
```
return new ObjectResult(ret);
````

**Comment by dougbu** [comment]
@Bartmax this feature is available in the `Microsoft.AspNet.Mvc.WebApiCompatShim` package. Have a look at the `ApiController` class.

One alternative is the `HttpStatusCodeResult` class, which is similar to Web API's `OkResult` and available in both MVC 5 and 6.

**Comment by Bartmax** [comment]
I'm not doing any compatibility stuff here, while Ok is there, I'm not doing any webapi2, so I don't think importing that would actually fit.

I found that ObjectResult (instead of HttpStatusCodeResult) being more accurate, also there's no method on base controller that returns either ObjectResult or HttpStatusCodeResult.

I think there should be a `public virtual ObjectResult Ok(object value);` in the Controller class on the framework or HttpOk like the other methods for the common scenarios.

It feels weird to have HttpBadRequest, HttpNotFound, HttpUnauthorized, Created, but not an HttpOk on base abstract class controller.

This was kind of a question/suggestion.

**Comment by dougbu** [comment]
Updated subject because this is no longer a question.

**Comment by Bartmax** [comment]
:shipit: hehe nice work @dougbu

**Comment by dougbu** [comment]
6106375
