### ISSUE TITLE
Encoding forward slash makes no difference

### ISSUE THREAD

**Issue by recardopatrese** [aspnet/Mvc#2826]
I am trying to submit a URL where the data being passed contains a forward slash, but it is not reaching the controller. If I remove the / from the data to be passed it reaches the controller.

We are using the default routing with the following URL:

    /configuretaxrefs/GetTaxref/025%2F588

but this doesn't reach the controller.

The controller contains:

    [HttpGet]
    public Taxref GetTaxref(String id)
    {

If I change code (underlying data on the database) to '0251588' it reaches the controller.

I can't see what the issue is. Can anyone help?

**Comment by dougbu** [comment]
@recardopatrese we dealt with similar issues when handling forward slashes in OData literal strings. The gotchas are not really in MVC or (then) Web API but in the hosts. Double encoding e.g. `.../025%252F588` _sometimes_ works but is not reliable. Recommend using another separator, preferably one less core to MVC routing and URL semantics.

**Comment by dgee2** [comment]
The problem we have with this is that it is a user entered field from a legacy system and so we kind of need to go with it. Did you then need to unencode it once from within the mvc controller?

**Comment by recardopatrese** [comment]
Thanks @dougbu. Unfortunately as @dgee2 says the data with the forward slash in is from the database so we can't change the data.

**Comment by dougbu** [comment]
@recardopatrese if your code is generating the URL, convert the forward slash to another character or series of characters (maybe "%2F" though that's unreliable) early in that process.

**Comment by danroth27** [comment]
Or you can put it in the query string. The issue here is really that HTTP.SYS is very conservative about encoded slashes in the URI path.

**Comment by evil-shrike** [comment]
Unfortunately the same thing is for back slashes as well

An url like `api/User(domain%5Cuser1)/groups` isn't caught by route `api/{type}({id})/{prop}`

**Comment by PawelTroka** [comment]
That sucks. How could you close this one?

**Comment by danroth27** [comment]
@PawelTroka Because this isn't an MVC issue. The problem is really that IIS/HTTP.SYS aggressively decode the path.

**Comment by PawelTroka** [comment]
Ok, but I also encountered this one in ASP.NET Core, which can be run without IIS. Why is that?

**Comment by davidfowl** [comment]
@PawelTroka do you have a repro?

**Comment by PawelTroka** [comment]
@davidfowl yeah, of course.
Unit test:
https://github.com/PawelTroka/Computator.NET/blob/master/Computator.NET.WebApi.IntegrationTests/CalculateApiTests.cs#L53

Logic:
https://github.com/PawelTroka/Computator.NET/blob/master/Computator.NET.Web/Controllers/CalculateController.cs#L56

**Comment by danroth27** [comment]
@PawelTroka ASP.NET Core still typically runs behind IIS on Windows. IIS will decode the slashes. If you run self hosted you will get the unencoded route value.

**Comment by PawelTroka** [comment]
@danroth27 I am runing self hosted and I am getting bad route.

**Comment by danroth27** [comment]
Hmm, that is odd. We'll need to investigate further. Let me take a look and we'll get back to you.

**Comment by davidfowl** [comment]
@Tratcher is the test host doing bad things?

**Comment by PawelTroka** [comment]
@davidfowl Yes, you are right.... Sorry for not trying this out but in fact it only fails on test host and works normally when self-hosted:
![image](https://user-images.githubusercontent.com/11928766/28237573-d33555da-6942-11e7-9fe8-87a4ea689615.png)

**Comment by Tratcher** [comment]
More likely it's System.Uri decoding it on the client side before HttpClient sends it. Uri is as opinionated as Http.Sys.
