### ISSUE TITLE
asp.net mvc web grid with context menu

### ISSUE THREAD

**Issue by dhanutpk** [aspnet/Mvc#2830]
Hi,

I have requirement for creating asp.net mvc web grid with context menu. 
The context menu should do have capability to View, Add, Edit and Delete operations on each row. This menu should be displayed when I right click on row in the grid.  
It would be great if you could give some samples of examples.

Thanks,
Dhanaraj

**Comment by Eilon** [comment]
Closing because we have no plans to support this.

**Comment by Eilon** [comment]
BTW there are 3rd party components you can get, such as from http://www.telerik.com/aspnet-mvc/mvc6-features.
