### ISSUE TITLE
Do not encode unnecessary characters in HtmlEncoder

### ISSUE THREAD

**Issue by srayuws** [aspnet/Mvc#2831]
The rendered result for the code below

```cshtml
@{var c ="中";}
<div>@c</div>
```

will be `<div>&#x4E2D;</div>` in vnext, and will be `<div>中</div>` in the current stable MVC 5 

I think the escaping for the character '中'([U+4E2D](http://www.fileformat.info/info/unicode/char/4e2d/index.htm)) is absolutely unnecessary. 

And it will transfer much more data, 8 bytes after escape VS 3 bytes in UTF8. The size increment would be significant especially in  non-English sites.

Can we do more precisely checking on checking is the character must be escaped, and do not escape it when it is unnecessary?

**Comment by pranavkm** [comment]
cc @blowdart

**Comment by blowdart** [comment]
Dupe of https://github.com/aspnet/HttpAbstractions/issues/315

By design. Users can configure what is and is not encoded. By default we take a conservative view to protect against potential browser security issues.
