### ISSUE TITLE
Invalid binding prefix for model with single property

### ISSUE THREAD

**Issue by anfomin** [aspnet/Mvc#2834]
I'm trying to bind model with single property:
```C#
public class TimeZoneModel
{
	public double? TimeZone { get; set; }
}

public class MyController : Controller
{
		public async Task<IActionResult> Get(TimeZoneModel model)
		{
				//...
		}
}
```

Property `TimeZone` can't be bound because binding name is `model.TimeZone`. If I add second property to the model then model binding name is `TimeZone` and binding is ok.
```C#
public class TimeZoneModel
{
	public double? TimeZone { get; set; }
	public string SomeOtherProperty { get; set; }
}
```

**Comment by dougbu** [comment]
@anfomin what is submitted and what does "can't be bound" mean exactly?

Note the model binding system will attempt to bind `"model.TimeZone"` and `"model.SomeOtherProperty"` then fall back to `"TimeZone"` and `"SomeOtherProperty"` if the first attempt does not succeed.

**Comment by anfomin** [comment]
I submit value for `TimeZone`, for example:
```HTTP
GET /mycontroller/get?TimeZone=10
```

If there is only one model property then MVC tries to bind only `model.TimeZone` but does not fall back to `TimeZone` without prefix. If you need I can share sample.

**Comment by Muchiachio** [comment]
Tested on Beta5, works as expected.
```HTTP
GET /home/get?TimeZone=10
```
```C#
public class HomeController : Controller
{
    public async Task<IActionResult> Get(TimeZoneModel model)
    {
        // model.TimeZone = "10.0"
    }
}
```
Maybe your URL is bad?
```HTTP
GET /mycontroller/get?TimeZone=10
```
Shouldn't it be?
```HTTP
GET /my/get?TimeZone=10
```

**Comment by danroth27** [comment]
@anfomin If you could share your code that would be great.
@dougbu Could you please try to reproduce this issue?

**Comment by anfomin** [comment]
@danroth27 I'm sorry, I can share sample only tomorrow. I'll post a link...

**Comment by anfomin** [comment]
I have investigated that there is an error with our custom model binder. MVC bind this model correctly.
