### ISSUE TITLE
ReflectedParameterDescriptor equivalent

### ISSUE THREAD

**Issue by toraora** [aspnet/Mvc#2837]
In MVC3, we used ReflectedParameterDescriptor (from ActionDescriptor.GetParameters()) in order to determine whether the user supplied all of the necessary arguments, and display a detailed error page if not. I see that something similar has been done in WebApiCompatShim, but it seems to happen in a stage of the pipeline that cannot modify the response. Is there a way to get this information in perhaps something like an ActionFilter (i.e. it still gets forwarded to a particular action, but will respond with a "param is required" message)?

**Comment by rynowak** [comment]
You can absolutely do this in an action filter.

You'll want to look at `context.ActionDescriptor.Parameters` and `context.ActionDescriptor.BoundProperties` - is something missing that you need?

**Comment by toraora** [comment]
I was using `reflectedParameterDescriptor.ParameterInfo.HasDefaultValue` and `controllerBase.ValueProvider.GetValue(key)` previously to determine if a particular parameter has been satisfied.

I've tried looking through `ParameterDescriptor` and `ParameterType` but can't find anything indicating whether the parameter has a default value.

**Comment by rynowak** [comment]
> I was using reflectedParameterDescriptor.ParameterInfo.HasDefaultValue

Yeah, I think you're right that this is too hard to get at. You can get it the `MethodInfo` by casting `ActionDescriptor` to `ControllerActionDescriptor` but we should make this easier.

`controllerBase.ValueProvider.GetValue(key)` - you can look at `context.ActionArguments` to see what will be passed into the action.
