### ISSUE TITLE
Wiring up scaffolding for CRUD

### ISSUE THREAD

**Issue by NoralK** [aspnet/Mvc#2842]
I do not know where to post this but here - I could not find the repository that has "Microsoft.Framework.CodeGenerators.Mvc", my second choice would be EntityFramework.

I have a basic Model with PERSON_ID as a key and identity and FULLNAME length of 30 and required.
```
            builder.Entity<Person>(b =>
            {
                b.Key(e => e.Person_ID);
                b.Property(e => e.Person_ID).ForSqlServer().UseIdentity();
            });

            builder.Entity<Person>()
                .Property(b => b.First_Name)
                .MaxLength(30)
                .Required();
```
When creating the scaffolding for CRUD Views I type the following command:
```
dnx . gen controller --controllerName PersonController --model Person --dataC
ontext PersonDBContext
```
The Views get created however on the CREATE VIEW I am seeing a label and editor for PERSON_ID - I do not believe this should be there as it breaks the View.  On the other Views seem to be okay.  Once I comment out the DIV surrounding PERSON_ID all is normal.

**Comment by danroth27** [comment]
Moved to correct repo: https://github.com/aspnet/Scaffolding/issues/103
