### ISSUE TITLE
Strange error message when excess @ symbols in source code

### ISSUE THREAD

**Issue by lenardg** [aspnet/Mvc#2843]
In the following situation the error message that Razor gives me is very misleading.

I have the following code in a .CSHTML file:

```C#
@if (Model.Results.Any()) {
	@foreach (var result in Model.Results) {
            // some HTML code and Razor values
            <div>
               @result.SomeValue.
            </div>
            // some more HTML code
        }
}
```

Which results in an error message as follows:

`An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.`

And also: 

`Identifier expected`

The _identifier expected_ references the line `@result.SomeValue.` in it. This line is included in the example above. 

The error goes away if I remove the `@` mark before `@foreach`, and just specify `foreach`

The error is caused by having a . (dot character) after `SomeValue`. I can either make this work by removing the dot or by remove the `@` mark before @foreach. Note the dot character is indeed required, because we want to show the value followed by a dot.

Just to summarize, I am not objecting to how Razor works, but how this error is presented. It took some time to realize what I needed to do. Also, Visual Studio gave no indication something was wrong (VS2015 RTM)

**Comment by danroth27** [comment]
@NTaylorMullen  Is Razor handling the `@` in front of the foreach? It is weird that the error from the missing identifier after the `SomeValue.` goes away if the `@` in front of the foreach is removed. We should see if that is the behavior with the latest bits. Also, let's make sure we are getting red squiggles in the latest tooling update.

**Comment by dougbu** [comment]
@danroth27 agree a red squiggle under the dot should be expected regardless of whether the `foreach` had an extra `@`.

@lenardg an alternate fix to removing the dot would be `@(result.SomeValue).`

**Comment by lenardg** [comment]
Yes, I forgot to mention the parantheses fix :)
Red squiggles would be nice :)

**Comment by NTaylorMullen** [comment]
This is a Razor issue. Moved it here: https://github.com/aspnet/Razor/issues/491
