### ISSUE TITLE
No quick actions (add using statement for namespace) available when editing Razor views

### ISSUE THREAD

**Issue by lenardg** [aspnet/Mvc#2849]
When editing .CS code, if I enter a class name that was not used before, and if I have not referenced the namespace this class belongs to, I am offered quick actions that reference the namespace on my behalf. I do not need to check which namespace the type belongs to, nor do I have to go to the top of the file to add that.

It would be nice if a similar user experience could be enabled in the tooling when editing Razor views. Currently if I enter a class name that is missing a namespace or a using statement, I get the red squiggle under the name but no quick actions or help from Visual Studio. I need to remember or look up the namespace and add the reference by hand. 

(VS2015RTM, ASP.NET beta5)

**Comment by danroth27** [comment]
Moved to https://github.com/aspnet/Tooling/issues/116.
