### ISSUE TITLE
The 'Microsoft.AspNet.Mvc.SessionStateTempDataProvider' cannot serialize an object 

### ISSUE THREAD

**Issue by ynyhn** [aspnet/Mvc#2850]
InvalidOperationException: The 'Microsoft.AspNet.Mvc.SessionStateTempDataProvider' cannot serialize an object of type 'Labijie.Admin.ToastModel' to session state.

Microsoft.AspNet.Mvc.SessionStateTempDataProvider.EnsureObjectCanBeSerialized(Object item)

**Comment by Eilon** [comment]
TempData currently supports only a few limited types, which includes primitive types (string, int, etc.), and dictionaries containing those types. You can see https://github.com/aspnet/Mvc/issues/2276 for further discussion on this (towards the bottom).
