### ISSUE TITLE
DisplayNameFor / tag helpers should correctly translate Camel Case

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Mvc#2852]
Currently, when using `@Html.DisplayNameFor()` or the corresponding tag helpers on properties with Camel Case, it is *always* required to add a `DisplayAttribute` to the corresponding model property to resolve the Camel Case property name to a user friendly, space separated name.

If no localization takes place, the above is true for about 100 % of all applications.

Thus, I suggest to add logic to `@Html.DisplayNameFor()` to recognize Camel Case or underscore separated property names and to automatically apply a text transformation.

By default, property names should be output upper case for the first letter of each fragment:
`    firstName  =>  "First Name"`
`    first_name  =>  "First Name"`

There should be an enumeration introduced to have the text transformation been done in a different way:
`    public enum TextTransform`
`    {`
`      NoTransformation`
`    , FirstFragmentFirstLetterUpperCase`
`    , AllFragmentsFirstLetterLowerCase`
`    , AllFragmentsFirstLetterUpperCase    // default value`
`    , AllFragmentsLowerCase`
`    , AllFragmentsUpperCase`
`    }`

Hence, `TextTransform t = TextTransform.{...}; @Html.DisplayNameFor(m => m.firstMidName, t)` shall result in:

`    @Html.DisplayNameFor(m => m.firstMidName, TextTransform.NoTransformation)  =>  "firstMidName"`
`    @Html.DisplayNameFor(m => m.firstMidName, TextTransform.FirstFragmentFirstLetterUpperCase)  =>  "First mid name"`
`    @Html.DisplayNameFor(m => m.firstMidName, TextTransform.AllFragmentsFirstLetterLowerCase)  =>  "first mid name"`
`    @Html.DisplayNameFor(m => m.firstMidName, TextTransform.AllFragmentsFirstLetterUpperCase)  =>  "First Mid Name"`
`    @Html.DisplayNameFor(m => m.firstMidName, TextTransform.AllFragmentsLowerCase)  =>  "first mid name"`
`    @Html.DisplayNameFor(m => m.firstMidName, TextTransform.AllFragmentsUpperCase)  =>  "FIRST MID NAME"`

and

`    @Html.DisplayNameFor(m => m.first_Mid_nAMe, TextTransform.NoTransformation)  =>  "first_Mid_nAMe"`
`    @Html.DisplayNameFor(m => m.first_Mid_nAMe, TextTransform.FirstFragmentFirstLetterUpperCase)  =>  "First mid nAMe"`
`    @Html.DisplayNameFor(m => m.first_Mid_nAMe, TextTransform.AllFragmentsFirstLetterLowerCase)  =>  "first mid nAMe"`
`    @Html.DisplayNameFor(m => m.first_Mid_nAMe, TextTransform.AllFragmentsFirstLetterUpperCase)  =>  "First Mid NAMe"`
`    @Html.DisplayNameFor(m => m.first_Mid_nAMe, TextTransform.AllFragmentsLowerCase)  =>  "first mid name"`
`    @Html.DisplayNameFor(m => m.first_Mid_nAMe, TextTransform.AllFragmentsUpperCase)  =>  "FIRST MID NAME"`

(OK, the enumeration version is quite verbose. There should be some general method/property to switch text transformation for the whole view, e.g. `@Html.DisplayNameTransformation = TextTransform.FirstFragmentFirstLetterUpperCase`)

**Comment by dougbu** [comment]
@SetTrend this is an interesting idea but it's also incompatible with `DisplayName()` and `DisplayNameFor()` in all earlier MVC releases. We should leave the default behaviour alone.

Would new helpers e.g. `DisplayTransformedName[For]()` or new overloads of the existing helpers that accept a `DisplayNameTransform` argument work for you?

**Comment by ctolkien** [comment]
In MVC 5, you can override the `ModelMetaDataProviders`. With your own `DataAnnodationsModelMetadataProvider` to override some of these defaults. We frequently use one which uses the 'Humanizer' package.

https://github.com/MehdiK/Humanizer#mix-this-into-your-framework-to-simplify-your-life

I haven't checked that this sort of scenario would still be possible in MVC6.

**Comment by rynowak** [comment]
Still possible. The APIs have changed to be more composable and support multiple providers.  See `DataAnnotationsMetadataProvider`

You could do something pretty similar to the above by create an implemention of `IDisplayMetadataProvider` and having it just set the `DisplayName` if the `DisplayName` is set to the property name.
