### ISSUE TITLE
Tag helpers should not display all purple

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Mvc#2853]
I don't think it's a good idea to have tag helpers display all purple.

Sooner or later almost each of a view's HTML tags will be annotated by tag helpers. Then all of the syntax highlighting gets lost.

I would prefer to have tags annotated with tag helpers being displayed with a slightly different background-color or similar.

**Comment by Eilon** [comment]
@SetTrend we have a feature that will do exactly that, but it's only partially implemented.

In https://github.com/aspnet/Razor/issues/447 the Razor system will respect certain attributes to hide them from Intellisense, however VS doesn't *yet* respect that metadata.

The goal is to have only "interesting" tag helpers be purple, and have more mundane ones not show up as anything special.

**Comment by NTaylorMullen** [comment]
In addition to @Eilon's comment you can change the `TagHelper` colors via font options => `HTML Razor Tag Helper Element`/`Attribute`:

![image](https://cloud.githubusercontent.com/assets/2008729/8858761/1b1b6096-312e-11e5-99cf-45f372aedbfa.png)

I would also recommend adding required attributes to limit the applications of `TagHelper`s (`[TargetElement("foo", Attributes = "something-required")]`)
