### ISSUE TITLE
environment tag helper does not work in @section block

### ISSUE THREAD

**Issue by lenardg** [aspnet/Mvc#2857]
Trying to use the `<environment>` tag helper to selectively include script files in a @section block results in a runtime error.

The error message is:
```
An error occurred during the compilation of a resource required to process this request. 
Please review the following specific error details and modify your source code appropriately.
```
And also:
```
The type or namespace name 'TagHelperContent' could not be found (are you 
missing a using directive or an assembly reference?)
        private TagHelperContent __tagHelperStringValueBuffer = null;
```

The same environment setting works without errors if placed outside the @section block.

I would believe this should work. The @section block is used to include page specific script files that are then placed into the layout file at certain positions. These would be minimized in *staging* and *production* but included without transformation in *development*. The environment tag helper can achieve this normally, but not within @section blocks.

**Comment by Eilon** [comment]
Looks like a dup of https://github.com/aspnet/Razor/issues/456.
