### ISSUE TITLE
Cannot set Controller Request for Unit Tests

### ISSUE THREAD

**Issue by danbrunell** [aspnet/Mvc#2858]
Let me know if I'm completely missing something here. Also let me know if I'm just writing bad/hacky code.

Scenario: I have a Controller I am using for REST Responses. I am checking the query string for certain filters when returning the data.

Example:

```C#
if (Request.Query.ContainsKey("nonempty"))
    customers = customers.Where(c => c.orders.Length > 0);
```

However, when I write a unit test, I am getting a "Test Failed (Message: Object reference not set to an instance of an object)" error, because when the unit test invokes the controller it HAS no request (the if statement is comparing an attribute of null). 

I want to be able to spoof the Request (by just making it a generic empty one), and came across [this tutorial for Web API 2](http://www.asp.net/web-api/overview/testing-and-debugging/unit-testing-controllers-in-web-api). It looks like [according to the docs](https://msdn.microsoft.com/en-us/library/system.web.http.apicontroller.request(v=vs.118).aspx) also, controller.Request used to be {get, set}.

```C#
ProductsController controller = new ProductsController(repository);

controller.Request = new HttpRequestMessage { 
    RequestUri = new Uri("http://localhost/api/products") 
};
```

It seems that this doesn't exist in MVC6 however. controller.Request is get only, with no set. What is a boy to do? Is this done some other way now? I know I can check if Request is null before checking the query string value, but that seems like a super hacky solution (I have my limits).

Thanks :)!

**Comment by rynowak** [comment]
You can set it through the `ActionContext` property. Even better, the `DefaultHttpContext` class it designed to used in unit tests. 

```
var controller = new FooController();
controller.ActionContext.HttpContext = new DefaultHttpContext();
```

Doing this will make almost all of the request/response type properties initialized to something you can interact with.
