### ISSUE TITLE
`IMvcBuilder` interface is inflexible

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2861]
Most `IServiceCollection` extensions do the intuitive thing and return the passed `IServiceCollection`. However the minimal ("Core") MVC extension methods, `AddMvcCore()` in particular, return an `IMvcBuilder` implementation with a single property of type `IServiceCollection`. This imposes an unnatural order on `Add...()` methods.

For example the `MvcMinimalSample.Web` project chains extension methods as follows:
``` c#
            services
                .AddMvcCore()
                .AddAuthorization()
                .AddFormatterMappings(m => m.SetMediaTypeMappingForFormat("js", new MediaTypeHeaderValue("application/json")))
                .AddJsonFormatters(j => j.Formatting = Formatting.Indented);
```

This order is imposed and only the `AddAuthorization()` method can move before `AddMvcCore()`. So where would a user call `AddLogging()`? The working options are:
``` c#
            services
                .AddLogging()
                .AddMvcCore()
...
```
or
``` c#
...
                .AddJsonFormatters(j => j.Formatting = Formatting.Indented)
                .Services.AddLogging();
```

A user trying to find the correct method name would likely add a period after `AddJsonFormatters()`, observe the IntelliSense suggestions, and scratch their heads, wondering what `using` or package they forgot.

Suggest changing `IMvcBuilder` to inherit from `IServiceCollection`. At least then adding new services to the end would work -- some flexibility restored. This approach would also continue to hide the low-level extension methods that are not needed when using the full `AddMvc()`.

**Comment by Eilon** [comment]
I'm confused. `AddMvcCore()` takes in an `IServiceCollection` and returns an `IMvcBuilder`. Every other MVC builder extension both takes in and returns an `IMvcBuilder`.

What doesn't work?

BTW making `IMvcBuilder` derive from `IServiceCollection` would completely break the model - every other service extension method would show up.

**Comment by dougbu** [comment]
> Every other MVC builder extension both takes in and returns an IMvcBuilder.

No. Only low-level extensions show up e.g. `AddRazorViewEngine()`. These are mostly additions `AddMvc()` provides in one call when using the whole thing. However none of the high-level `IServiceCollection` extensions are available e.g. `AddLogging()` or our own `AddMvcLocalization()` and `AddWebApiConventions()`.

> every other service extension method would show up.

What's wrong with that? It closely matches the model everywhere else e.g. `AddMvc()` returns the `IServiceProvider` and thus can be chained before or after `AddLogging()`. And it would still allow the low-level builder extensions to be chained -- as long as those remain together.

I know of no `IServiceCollection` extension except `AddMvcCore()` that returns anything but the `IServiceCollection`.

**Comment by dougbu** [comment]
Missed a question...

> What doesn't work?

Adding logging or any other `IServiceCollection` extension anywhere in the chain after `AddMvcCore()`. As shown in my description, `AddLogging()` works if placed first or if the user tries the `Services` property (not particularly discoverable) to switch back to the expected chain.

**Comment by Eilon** [comment]
I'm just guessing, but I don't think the work is entirely done. It might be better to understand the goals of the design and its current state first.

**Comment by Eilon** [comment]
Regarding AddLogging, that's not an MVC method - why should you be able to chain it to AddMvc??

**Comment by dougbu** [comment]
> why should you be able to chain it to `AddMvc`??

You _can_ chain `AddLogging()` (or `AddStaticFiles()` or whatever from our larger system) after `AddMvc()`. The inconsistency / problem here is that doesn't work with `AddMvcCore()`.

**Comment by Eilon** [comment]
There are big changes coming to how this all works. Also, AddMvc is not meant to be the same as AddMvcCore.

**Comment by rynowak** [comment]
> There are big changes coming to how this all works

So much this. It will be consistent once we update the other parts of the system.
