### ISSUE TITLE
Controller.Initialize()

### ISSUE THREAD

**Issue by SenLi325** [aspnet/Mvc#2863]
So i am working on a demo that will use the Controller.Context to create a Shopping Cart Service.
Since the Context is still null inside the Controller Constructor, I need to find a way to initialize my Shopping Cart Service right after the Controller Constructor.

Back to old time in System.web.mvc.controller, there was a method to overrider Controller.Initialize().
I am not sure if that method is still available for .Net 5 since System.web is no longer supported and Controller class is move to the Microsoft.Aspnet.Mvc.

**Comment by Eilon** [comment]
Can you show a little bit more of the structure of your controller and service? You might be able to use Dependency Injection (DI) to achieve everything. Which services does the shopping cart service need?

BTW it might be worth pointing out that a shopping cart service (which is presumably a "business logic layer" component) shouldn't know anything about *controllers*, though it may very well need some other services, such as logging, a repository, caching, etc.

**Comment by dougbu** [comment]
Agree w/ @Eilon that an `Initialize()` method is less needed with MVC 6.

However in those rare cases e.g. all of the actions in the controller need the same values added to `ViewData`, override `OnActionExecuting()` or `OnActionExecutionAsync()`.

**Comment by Eilon** [comment]
The recommended alternatives to `Initialize()` are listed here.
