### ISSUE TITLE
 Add HtmlHelper which will return the files modification timestamp by glob mask.

### ISSUE THREAD

**Issue by tstar** [aspnet/Mvc#2865]
I want to propose to add HtmlHelper which will return the files modification timestamp by glob mask. This will help in scenarios such as RequireJS module configuration to clear the client scripts cache.

I want to present my realisation of this module.

```
using Microsoft.AspNet.FileProviders;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Framework.Caching.Memory;
using Microsoft.Framework.DependencyInjection;
using System;
using System.Linq;

public static class FilesVersionExtensions
{
    public static string FilesVersion(this IHtmlHelper helper, string glob)
    {
        while (new[] { "~", ".", "/", "\\" }.Any(i => glob.StartsWith(i, StringComparison.OrdinalIgnoreCase)))
        {
            glob = glob.Substring(1);
        }

        string Result;
        if (Cache.TryGetValue(glob, out Result)) return Result;

        Result = DateTime.Now.Ticks.ToString();
        var env = helper.ViewContext.HttpContext.RequestServices.GetService<IHostingEnvironment>();
        if (env != null)
        {
            Cache.Set(glob, Result, new MemoryCacheEntryOptions().AddExpirationTrigger(new PhysicalFileProvider(env.WebRootPath).Watch(glob)));
        }
        return Result;
    }

    private static readonly MemoryCache Cache = new MemoryCache(new MemoryCacheOptions());
}
```
Example of use for the monitoring of all the scripts in a folder and subfolders:
```
<script type="text/javascript">
        var require = { urlArgs: "v=@Html.FilesVersion("js/**/*.js")" };
</script>
<script data-main="js/test" src="~/js/require.js" asp-file-version="true"></script>
```

Maybe I did not notice and there is a ready solution?

Thank You.

**Comment by dougbu** [comment]
The `asp-file-version` (`asp-append-version` in more recent MVC builds) attribute works with local files and adds a SHA256 hash of the file's content. Are you looking for an HTML helper that provides a similar hash? If you prefer a timestamp, why?

Separately did you run into any issues adding your `IHtmlHelper` extension?

**Comment by IDisposable** [comment]
Personally I'm happy with hashing, but the value proposition of timestamp vs. hashing is that one is metadata that costs nothing to get, vs. reading the entire file to compute the hash.

**Comment by IDisposable** [comment]
Can we reduce the allocations and conversions in this implementation?

```
public static class FilesVersionExtensions
{
    public static DateTime FilesVersion(this IHtmlHelper helper, string glob)
    {
        glob = glob.TrimStart(s_LeadingCharacters);

        DateTime timestamp;
        if (Cache.TryGetValue(glob, out timestamp)) 
        {
            return timestamp;
        }

        timestamp = DateTime.UtcNow;
        var env = helper.ViewContext.HttpContext.RequestServices.GetService<IHostingEnvironment>();

        if (env != null)
        {
            // TODO is it the expected behavior to add to the options used build the cache? Why or why not?
            Cache.Set(glob, timestamp, s_CacheOptions.AddExpirationTrigger(new PhysicalFileProvider(env.WebRootPath).Watch(glob)));
        }

        return timestamp;
    }

    private static readonly char[] s_LeadingCharacters = new[] { "~", ".", "/", "\\" };
    private static readonly MemoryCacheEntryOptions s_CacheOptions = new MemoryCacheEntryOptions();
// TODO: Is it save to assume static constructor order, or would we be better off with a private property get to ensures it gets newed in correct order?
    private static readonly MemoryCache Cache = new MemoryCache(s_CacheOptions );
}
```

**Comment by Eilon** [comment]
BTW the issue with timestamps is that on distributed systems they are not reliable. This can cause significantly reduced performance on a multi-node system. Hashes, on the other hand, are perfectly reliable.

**Comment by tstar** [comment]
I apologize in advance for my English.

asp-append-version may monitor only one file. My implementation allows tracking many files corresponding to the mask at any depth of folders. It is important for AMD/CommonJS JavaScript loaders like RequireJS. The RequireJS has a special property "urlArgs" that is added to each loaded file that would ensure relevance (cache bust) http://requirejs.org/docs/api.html#config-urlArgs.

When we track a group of files, it is sufficient to only detect the fact of change of any of the files and return any unique value that will be passed as "urlArgs" parameter to the RequireJS.

The unique value may be a number, a time stamp, guid - the main thing that it was a unique on client side in result.

We can not use asp-append-version anywhere, only a limited number of scenarios. HtmlHelper  ideal candidate in this case..

The result of my helper I will show an example:
```
<script type="text/javascript">
        var require = { urlArgs: "v=635736285881592431" };
</script>
<script src="/js/require.js?v=be46SzFnVnmga-TBKwsxBPbfieYlQZTthjkbJ0lWOiY" data-main="js/test"></script>
```
This code was added later by RequireJS.
```
<script src="js/test.js?v=635736285881592431" type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="Test"></script>
<script src="js/jquery.js?v=635736285881592431" type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="jquery"></script>
<script src="js/jquery.js?v=635736285881592431" type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="jquery"></script>
```

**Comment by danroth27** [comment]
We think this is something that could be built on top of MVC as a separate component. For the majority of cases we believe customers will want the hashing behavior.
