### ISSUE TITLE
Question: Equivallent of Response_End in Global.aspx.cs

### ISSUE THREAD

**Issue by mbharodia** [aspnet/Mvc#2866]
Hi, 

What is equivalent of Response_End (available in Global.aspx.cs in earlier versions of Asp.NET MVC)?

MVC app with Asp.NET 5 is not event driven. In this case what should I implement to trigger post response processing?

Any help would be appreciated.

**Comment by Eilon** [comment]
@Tratcher what do you recommend here?

**Comment by Tratcher** [comment]
What kind of work do you want to do?
Have you tried HttpContext.Response.OnCompleted?

**Comment by danroth27** [comment]
Or would simply implementing custom middleware work for your scenario?

**Comment by mbharodia** [comment]
How do I implement custom middleware? Is there any guideline or demo code available? Thanks.
Basically I have unit of work pattern and single repository implemented. I would like to save context during response end. I would like to do it globally so that I can also handle errors and other scenarios in a single place. I have done this in Global.aspx.cs earlier. I would like to port the same application on newer framework.

**Comment by Tratcher** [comment]
The middleware docs are under review here: https://github.com/aspnet/Docs/pull/348/files

**Comment by Eilon** [comment]
If you're specifically using MVC 6, you can use an ActionFilterAttribute and override [OnActionExecuted](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ActionFilterAttribute.cs#L20) to do cleanup work. There are other types of filters in MVC that might be more suited to your scenario, depending on when you want to do the cleanup work.

Writing middleware is also very easy. Here's a blog post I found that shows how to do it: http://www.mikesdotnetting.com/article/269/asp-net-5-middleware-or-where-has-my-httpmodule-gone

Your middleware can be a simple class that's just a few lines of code, and then you register it in your Startup class's Configure method.
