### ISSUE TITLE
`asp-append-version` ignored when running on Mono 4.2 or 4.3

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2867]
The `<img>`, `<link>` and `<script>` tag helpers mostly work on all platforms. However `asp-append-version` does nothing when running on Mono 4.2 or 4.3.

Since `FileVersionProvider` [contains the only](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.TagHelpers/Internal/FileVersionProvider.cs#L59) `Uri.TryCreate()` call in the MVC product code, the root cause is likely aspnet/External#21. Rather than waiting for a Mono fix, should work around the issue e.g. by confirming the new `Uri` has an "http" or "https" scheme.

Note it's been almost two months since @sornaks filed [the Xamarin bug](https://bugzilla.xamarin.com/show_bug.cgi?id=30854) for aspnet/External#21. And we don't know when this bug will reach the Mono [alpha channel](http://www.mono-project.com/docs/getting-started/install/linux/#alpha-update-channel).

Further the `FileVersionProvider` class looks fragile compared with [`FilePathResult`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/FilePathResult.cs). Though the notion of "absolute" is different for the two classes, they should probably share some of the same smarts.

**Comment by danroth27** [comment]
I'm inclined not to fix this as I think the Mono behavior is incorrect. 

What is the issue with `FileVersionProvider` and `FilePathResult`? Sounds like a separate issue.
