### ISSUE TITLE
Rendering a view to string

### ISSUE THREAD

**Issue by aaron-hammond** [aspnet/Mvc#2871]
Hi Guys,

I'm trying to render a view to a string but i'm struggling. I thought i could inject the IRazorViewEngine and then call .FindPartialView() but the DI container isn't able to resolve the IRazorViewEngine which leads me to believe what i'm doing is just wrong.

     public class ViewProvider : IViewProvider
     {
        private readonly IRazorViewEngine _razorViewEngine;

        public ViewProvider(IRazorViewEngine razorViewEngine)
        {
            _razorViewEngine = razorViewEngine;
        }

        public string RenderViewToString(ActionContext actionContext, string viewName, TempDataDictionary tempDataDictionary, ViewDataDictionary viewData)
        {
            var viewEngineResult = _razorViewEngine.FindPartialView(actionContext, viewName);

            using (var writer = new StringWriter(CultureInfo.InvariantCulture))
            {
                var viewContext = new ViewContext(actionContext, viewEngineResult.View, viewData, tempDataDictionary, writer);
                viewEngineResult.View.RenderAsync(viewContext);
                return writer.GetStringBuilder().ToString();
            }
        }
    }

Could anyone tell me what i need to do to achieve this?

Thanks

**Comment by pranavkm** [comment]
@aaron-hammond, view engines aren't in the DI container. There's a `ViewEngines` sequence on `MvcOptions` - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/Rendering/ViewEngine/CompositeViewEngine.cs#L28-L44.

One way to go about it might be:

```C#
    public ViewProvider(ICompositeViewEngine compositeViewEngine)
    {
        _razorViewEngine = ((CompositeViewEngine)compositeViewEngine).ViewEngines.OfType<IRazorViewEngine>().First();
    }

```

Clearly not the nicest of APIs here.

**Comment by pranavkm** [comment]
@aaron-hammond spoke to @rynowak about this API. This was something we wanted to tackle and we can work on cleaning it up so it is a little less wonky to deal with. That said, `MvcOptions.ViewEngines` would be the right location to look for this

**Comment by aaron-hammond** [comment]
@pranavkm thank you for the reply on this, i'll use your suggestions for now. Out of interest how would this be cleaned up? Would you expect the behavior in my original example to work and the DI container resolve an instance of the razor view engine or would i access it by some other means?

Thanks

**Comment by pranavkm** [comment]
@aaron-hammond, I did check in the cleanup changes (https://github.com/aspnet/Mvc/commit/7120b2ff9219e4ec917bc0654d66772c2d2d42c5). We have `IRazorViewEngine` registered in DI now, so your original example should work. 

In addition, `MvcViewOptions` also exposes the list of `IViewEngines` the application uses. So if you care to query all of them, you could use that type.

**Comment by aaron-hammond** [comment]
@pranavkm great, really appreciate the link to the change set. Thanks for your help!
