### ISSUE TITLE
Discussion: Refactoring of MVC packages

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2872]
## What is it?

We've split up the MVC runtime features into a set of more granular packages based on what features they provide and what dependencies they have.

**For most users there will be no change, and you should continue to use `AddMvc()` and `UseMvc(...)` in your startup code.**

**For the truly brave, there's now a configuration experience where you can start with a minimal MVC pipeline and add features to get a customized framework.**

```
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddMvcCore()
        .AddAuthorization()
        .AddJsonFormatters(j => j.Formatting = Formatting.Indented);
}
```

`AddMvcCore()` is an advanced experience that gives an application developer fine-grained control over what features are provided by MVC - you can mix and match dependencies with 3rd party frameworks, or avoid dependencies altogether that aren't needed.

For 3rd party library authors, this change allows you to target a more minimal set of dependencies if your requirements allow it. 
## Breaking Changes

Some options that used to be on `MvcOptions` have moved:
- `AntiforgeryOptions` - use `ConfigureAntiforgery(...)`
- `ClientModelValidatorProviders` - use `ConfigureMvcViews(...)`
- `HtmlHelperOptions` - use `ConfigureMvcViews(...)` 
- `SerializerSettings` (JSON.NET) - use `ConfigureMvcJson`
- `ViewEngines` - use `ConfigureMvcViews(...)`

If you're using `AddMvc()` we don't intend any changes in functionality other than the options changes. 

If you're using `AddMvcCore()` configuring relevant options is more streamlined when adding a feature to the builder. The various `Add<feature>(...)` extensions methods take an `Action<T>` which will point you more directly to what's configurable for that feature.

```
    services
        .AddMvcCore()
        .AddJsonFormatters(SerializerSettings json => json.Formatting = Formatting.Indented);
```
## Feedback

For anyone experimenting with `AddMvcCore(...)` we'd like to know about any surprises you encounter. Does something work that shouldn't? Does something break that should be available?

Regarding the layering, what chunks of features are the right size? What should be broken down smaller? Are things to granular?

Please include what you're trying to accomplish (what kind of site are you building) when leaving feedback. If you don't include this information, I'm just going to ask for it anyway :+1: 
## Description of Packages/Features

Here's an updated listing of each package, as well as what `Add<feature>(...)` methods are exposed by each.
##### Microsoft.AspNet.Mvc.Abstractions

Defines the core abstractions for MVC.
##### Microsoft.AspNet.Mvc.Core

Defines the implementation of the MVC runtime features. This is the only required reference to produce something that can serve requests using `AddMvcCore(...)`.

`AddMvcCore(...)` - adds the minimal runtime services, and returns an `IMvcBuilder` to compose with other features.

Also

`AddFormatterMappings(...)` - adds support for maping file-extensions in the URL to content-types.

And

`AddAuthorization(...)` - adds support for discoving `[Authorize(...)]` attributes on controllers and actions and applying authorization policy. This must be used with an authorization middleware, and only adds support for MVC to recognize the attributes.
##### Microsoft.AspNet.Mvc.ApiExplorer

Defines the implementation of the `IApiDescriptionProvider` and other infrastructure for describing API endpoints in an application. Required if using [Swashbuckle](https://github.com/domaindrivendev/ahoy) or a similar package.

`AddApiExplorer(...)` - adds the API Explorer services.
##### Microsoft.AspNet.Mvc.Cors

Defines the discovery and implementation of CORS policies to be applied at the action or controller level in MVC. Adding these services will allow MVC to recognize `[EnableCors(...)]` and `[DisableCors]` attributes.

`AddCors(...)` - adds the CORS services. Also adds the services from `Microsoft.AspNet.Cors.Core` to the service collection (like calling `services.AddCors()`).
##### Microsoft.AspNet.Mvc.DataAnnotations

Defines the `ModelMetadata` and validation support for the attributes defined in `System.ComponentModel.DataAnnotations`. Almost no request validation will take place without including these validators.

`AddDataAnnotations(...)` - adds model metadata and validation support for data annotations attributes.
##### Microsoft.AspNet.Mvc.Formatters.Json

Includes the JSON input and output formatters and also the JSON-patch input formatter - using [Json.NET](http://www.newtonsoft.com/json). Includes `JsonResult`.

`AddJsonFormatters(...)` - adds the JSON and JSON-patch formatters

Using `AddJsonFormatters(...)` isn't required to use `JsonResult`, but it's the recommended way to configure the shared `SerializerSettings`.
##### Microsoft.AspNet.Mvc.Formatters.Xml

Includes the XML input/output formatters for using `XmlSerializer` or `DataContractSerializer`.

For now for don't have an updated way of configuring these formatters :disappointed:. You'll have to use `options.AddXmlDataContractSerializerFormatter(...)` for DCS, and using `XmlSerializer` is somewhat more manual.
##### Microsoft.AspNet.Mvc.Localization

Includes services for producing localized text in Razor Views.

For now we don't have an updated way of configuring these services. Use `services.AddMvcLocalization(...)`.
##### Microsoft.AspNet.Mvc.Razor

Includes services for using the Razor view engine implementation in MVC.

`AddRazorViewEngine(...)` - adds the Razor view engine. Calling `AddRazorViewEngine(...)` also calls `AddViews(...)` to add the basic view support and rendering features.
##### Microsoft.AspNet.Mvc.Razor.Host

Includes implementation of Razor code generation for MVC. Used as a dependency by `Microsoft.AspNet.Mvc.Razor` and by tooling.
##### Microsoft.AspNet.Mvc.TagHelpers

Includes implementations of TagHelpers for MVC. This remains an optional package which you can just use. Requires `AddViews()`.
##### Microsoft.AspNet.Mvc.ViewFeatures

Includes the definitions of view abstractions `IView`, `IViewEngine` and implementations of `IHtmlHelper`, View Components, `IJsonHelper` and other view rendering features. Includes the definition of `Controller`.

`AddViews(...)` - adds view rendering features. Will also add services for `AddDataAnnocations(...)` as well as Antiforgery, Data Protection, and Web Encoders.

Note that `AddViews(...)` on its own isn't complete, you will need to add a view engine to actually use views.
##### Microsoft.AspNet.Mvc.WebApiCompatShim

This is a compatibility package for porting WebAPI 2 applications. It doesn't mix and match with the `AddMvcCore(...)` experience.
##### Microsoft.AspNet.PageExecutionInstrumentation.Interfaces

Infrastructure for BrowserLink. Ignore this.

**Comment by rynowak** [comment]
### In accordance with the discussion in aspnet/Announcements#47 - this post is for feedback and discussion of aspnet/Announcements#49.

A reminder:

Feedback
------------

For anyone experimenting with `AddMvcCore(...)` we'd like to know about any surprises you encounter. Does something work that shouldn't? Does something break that should be available?

Regarding the layering, what chunks of features are the right size? What should be broken down smaller? Are things to granular?

Please include what you're trying to accomplish (what kind of site are you building) when leaving feedback. If you don't include this information, I'm just going to ask for it anyway :+1:

**Comment by davidpeden3** [comment]
@rynowak I recommend making a "discussion" label to better highlight these types of issues

**Comment by khellang** [comment]
First of all, I think it's nice that `AddMvcCore` returns a separate interface, `IMvcBuilder`. This prevents pollution of the `IApplicationBuilder` interface and weird scenarios where someone would call `AddJsonFormatters` etc. without actually needing it. I'd like to keep `Startup` as clean as possible :wink:

I do have a problem with it as well, though; this prevents chaining other, non-MVC related `Add*` methods after you've called `AddMvcCore`. I also think it's weird that MVC-specific methods looks like they hang right off `IApplicationBuilder` (yes, I know you can nest things differently, but still, some scoping would be nice). IMO it would be nicer if top-level `Add*` method exposed a builder, like `Action<IMvcBuilder>` that you could use to configure the services. That would make it much easier to see which services that are available and configured.

Example:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddMvcCore(mvc => mvc
            .AddAuthorization()
            .AddJsonFormatters(j => j.Formatting = Formatting.Indented))
        .AddEntityFramework(ef => ef
            .AddSqlServer()
            .AddDbContext<BloggingContext>(options => options.UseSqlServer(connection)));
}
```

Either that, or the `IMvcBuilder` should inherit `IApplicationBuilder` so you could keep chaining even after you've called `AddMvcCore`.

What do you think?

**Comment by davidpeden3** [comment]
@khellang +1

**Comment by akoeplinger** [comment]
@khellang 
> This prevents chaining other, non-MVC related  Add*  methods after you've called  AddMvcCore  [...]

I'm not sure this is really a problem, splitting into multiple `services.Add*` calls per component is likely required anyway if you've got a more complex ConfigureServices method (see [here](https://github.com/aspnet/MusicStore/blob/7e922fb49b7836f8a059d3fbbb4e8794f2267f68/test/E2ETests/compiler/shared/Mocks/StartupSocialTesting.cs#L56-L79) for an example).

**Comment by rynowak** [comment]
> I do have a problem with it as well, though. This prevents chaining other, non-MVC related Add* extension methods after you've called AddMvcCore.

/cc @DamianEdwards @davidfowl @lodejard 

We're definitely aware of the inconsistency of `IMvcBuilder` with much of the prior art here. Feedback and suggestions here are definitely welcome, we've spent a fair bit of time mocking up different styles of this API and will likely spend more time before v1 goes final.


Our rough consensus so far was to do the opposite of what's being suggested here and remove chaining of things that aren't related from `IServiceCollection`.

If there's a pivot here, we want to optimize for discoverability and clarity rather than the number of semicolons you have to type in. The biggest problem users face with startup code today is figuring out what options are available and what are relevant. This isn't locked by any means and we haven't done the work.

Eg (some future release):

```
services
    .AddMvcCore()
    .AddJsonFormatters(...);

services
    .AddEntityFramework()
    .AddSqlServer();
```

We also want to have a compatible experience for `AddMvc()` that feels consistent for configuring options.

**Comment by rynowak** [comment]
@davidpeden3 

> @rynowak I recommend making a "discussion" label to better highlight these types of issues

Interesting idea, but I'm not allowed. Will run it by @Eilon.

**Comment by rynowak** [comment]
I've been informed by @dougbu that I made a factual error:

Updated description for TagHelpers:

> Includes implementations of TagHelpers for MVC. This remains an optional package which you can just use. Requires `AddViews()`.

**Comment by khellang** [comment]
> We also want to have a compatible experience for AddMvc() that feels consistent for configuring options.

I also do think it's important that this is consistent with other frameworks coming out of Redmond, like Entity Framework. You're setting a precedent for future (and existing), non-MS frameworks as well here. :smile:

**Comment by rynowak** [comment]
> I also do think it's important that this is consistent with other frameworks coming out of Redmond, like Entity Framework. You're setting a precedent for future (and existing), non-MS frameworks as well here.

That's why I mentioned them in the example I gave :+1:. They're part of the discussion as well.

**Comment by Eilon** [comment]
New label added.

**Comment by burtonrodman** [comment]
I'd prefer multiple services.Add calls for blocks of related functionality as mentioned by @rynowak.

**Comment by khellang** [comment]
> The biggest problem users face with startup code today is figuring out what options are available and what are relevant.

Speaking of what options are available and what are relevant;

> Requires `AddViews()`.

and

> Note that AddViews(...) on its own isn't complete, you will need to add a view engine to actually use views.

How are you supposed to know that in order to add some services, you first have to add some other services? Documentation?

Wouldn't it be better if this was either
 1. Enforced through the API, so once you fire up your app, you know it's not going to blow up (at least not because of incorrect configuration).
 2. The `Add*` methods in question were idempotent and that the ones requiring dependencies implicitly called the required `Add*` methods.

This is something that's very confusing for both services that depend on other services, but also where middleware requires a set of services to work, so you have to call a specific set of `Add*` methods in order for middleware to work at runtime. This can make the whole `Configure`/`ConfigureServices` concept pretty irritating.

It might be a bit off topic, but what are your thoughts around this? :smile:

**Comment by IDisposable** [comment]
Love the nested idea from @khellang

**Comment by Asshiah** [comment]
This would be great if we could have an example as to how to use the new Microsoft.AspNet.Mvc.Localization in a sample starter project.
The one provided here is outdated and do not work anymore: https://github.com/DamianEdwards/i18nStarterWeb

**Comment by ycrumeyrolle** [comment]
I prefer the SignalR / EF way to do for chaining the services. 
SignalR : 

    services
        .AddSignalR()
            .AddSqlServer()
            .Add3rdPartySignalRFeature();

    services
        .AddOtherServices();
EF : 

    services
        .AddEntityFramework()
            .AddSqlServer()
            .Add3rdPartyEntityFrameworkFeature();

    services
        .AddOtherServices();

MVC (proposal) : 

    services
        .AddMvc()
            .WithControllersAsServices([...]) // <== For now, I can write services.WithControllersAsServices([...]) !
            .Add3rdPartyMvcFeature();

    services
        .AddOtherServices();
or 

    services
        .AddMvcCore()
            .AddCors()
            .AddAutorization()
            .Add3rdPartyMvcFeature();

    services
        .AddOtherServices();

The `AddMvc()` and `AddMvcCore()` methods should return both a `IMvcBuilder`.
This would simplify the extensibility for 3rd party components. 

For example I have a thottling middleware. 
Without MVC, I register the services as following :

    services
        .AddThrottling();

With MVC, I have to register like this : 

    services
        .AddMvc()
            .AddMvcThrottling(); // method is AddMvcThrottling() in order to avoid confusion with AddThrottling() without MVC

    // Or with MvcCore 
    services
        .AddMvcCore()
            .AddThrottling() // method is AddThrottling() because it is an extension of IMvcBuilder
            .AddApiExplorer()
             AddAuthorization()
             AddCors()
             AddDataAnnotations()
             AddFormatterMappings()
             AddJsonFormatters()
             AddViews()
             AddRazorViewEngine();

This is confusing because I cannot have the same `AddXxx()` name with or without MVC.
And if I want to use the `AddMvcCore()` just for having a `IMvcBuilder`, I force the end-user to call all the `AddFeature()` methods.

What I would like is :

    services
        .AddMvc()
            .AddThrottling(); // method is AddThrottling() because it is an extension of IMvcBuilder.

**Comment by GuardRex** [comment]
This is a side question but related to the topic: I'm building out a light-weight POCO controller-based Web API app based on `MvcCore` with only ...
```
"Microsoft.AspNet.Mvc.Core": "6.0.0-beta6",
"Microsoft.AspNet.Server.IIS": "1.0.0-beta6",
"System.Runtime.Serialization.Primitives": "4.0.10-beta-*"
```
I don't add `Microsoft.AspNet.Mvc.ViewFeatures`, and I setup POCO controllers. I lose the `Context`. I thought that if I provide ...
```
public ActionContext Context { get; set; }
```
in the controller that I could resurrect the `Context` and be able to do things like ...
```
Context.HttpContext.Response.StatusCode = 200;
```
... but that doesn't seem to be the case. The app compiles and runs, but I get a null reference when the line is hit. How can I pickup `Context` in my POCO controller in this scenario?

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Announcements/issues/28

**Comment by GuardRex** [comment]
Ah! I see ...
```
[ActionContext]
public ActionContext Context { get; set; }

public HttpContext HttpContext => Context.HttpContext;
```
... and I just needed to add ...
```
"Microsoft.AspNet.Mvc.Formatters.Json": "6.0.0-beta6"
```
with
```
services.AddMvcCore().AddJsonFormatters();
```
... to get the JSON body into my `Post()` controller `[FromBody]` parameter.

Works like a charm! @davidfowl thanks again for your help!

**Comment by rynowak** [comment]
Thanks @GuardRex - let us know if you run into any other issues.

**Comment by melcloud** [comment]
Is it possible to add an extension methods to include the `HttpNotAcceptableOutputFormatter` and `HttpNoContentOutputFormatter`? Otherwise, have to setup all json formatters in options.

**Comment by rynowak** [comment]
@melcloud 

Can you explain a little more about what you're tying to accomplish? A code sample would be great if you think something is too hard/clumsy to do.

**Comment by melcloud** [comment]
@rynowak Actually, ignore my request.

I originally thought you have to do 

```csharp
services.AddMvcCore(options =>
    {
        var jsonOutputFormatter = new JsonOutputFormatter();
        jsonOutputFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
    
        options.OutputFormatters.Insert(0, new HttpNotAcceptableOutputFormatter());
        options.OutputFormatters.Add(jsonOutputFormatter);
        options.OutputFormatters.Add(new HttpNoContentOutputFormatter());
    })
    .AddDataAnnotations();
```

then I found out I made a mistake, the `AddJsonFormatters` extension methods actually works. But I think the documentation should be clear about how to add `HttpNotAcceptableOutputFormatter`:

```csharp
services.AddMvcCore(options =>
    {
       // must insert at zero
        options.OutputFormatters.Insert(0, new HttpNotAcceptableOutputFormatter());
        options.OutputFormatters.Add(new HttpNoContentOutputFormatter());
    })
    .AddDataAnnotations()
    .AddJsonFormatters(jsonFormatter => jsonFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver());
```

By the way, do we actually need to add `HttpNoContentOutputFormatter` explicitly? It still gives me 204 response for `null` return if I just added `HttpNotAcceptableOutputFormatter`.

Thanks for looking at this. :)

**Comment by rynowak** [comment]
`HttpNotAcceptableOutputFormatter` gives you back an 415 if content negotiation fails.
`HttpNoContentOutputFormatter` turns `null` and `void-returning` methods into a 204.

**Comment by NeelBhatt** [comment]
I guess the issue with chaining which is mentioned in this discussion has been resolved in beta7. Please look here

https://neelbhatt40.wordpress.com/2015/09/04/mvc-6-0-0-beta7-is-released/

 for other features of MVC 6 beta7 and give comment on post if I am missing something.

**Comment by pebezo** [comment]
+1 for khellang's nesting suggestion. Relying on indentation for scoping is silly.  For example when I see AddAuthorization I may want that before AddMvcCore - it only makes sense that I should be able to rearrange them, no? Or another example is that I may remembering seeing AddAuthorization, I then type it and... error. With nesting it's clear where the boundaries are and we wouldn't rely on indentation - which VS will fight with - i.e. less magic.

**Comment by khellang** [comment]
@pebezo I think that :ship: might have sailed :cry:

**Comment by davidadas** [comment]
@khellang that's too bad as I actually agree with @pebezo personally.  It was the first thought I had when I saw the original example code above.  "Man, the indentation is not intuitive..." :/

**Comment by khellang** [comment]
Another argument against indentation for scoping is code formatting. I don't know about Roslyn or [CodeFormatter](https://github.com/dotnet/codeformatter), but R# would/could automatically adjust chained method calls to the same indentation level.

Example:

```csharp
services
    .AddMvcCore()
        .AddThrottling()
        .AddApiExplorer()
         .AddAuthorization()
         .AddCors()
         .AddDataAnnotations()
         .AddFormatterMappings()
         .AddJsonFormatters()
         .AddViews()
         .AddRazorViewEngine();
```

Hit <kbd>Ctrl</kbd>+<kbd>E</kbd>, <kbd>Ctrl</kbd>+<kbd>C</kbd>, and it turns into this;

```csharp
services
.AddMvcCore()
.AddThrottling()
.AddApiExplorer()
.AddAuthorization()
.AddCors()
.AddDataAnnotations()
.AddFormatterMappings()
.AddJsonFormatters()
.AddViews()
.AddRazorViewEngine();
```

:sob:

**Comment by pebezo** [comment]
Hence my "VS will fight" point.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
