### ISSUE TITLE
Client side validation

### ISSUE THREAD

**Issue by Anderman** [aspnet/Mvc#2873]
I have 4 remarks/issues with the client side validation
__1__
The `[DataType(DataType.EmailAddress, ErrorMessage = "invalid email adress")]` will cause client side validation.

I think it should not do this ([#327](https://github.com/aspnet/Mvc/issues/327)) because, the server side validation is not implemented and on the client side the message is not implemented. It is confusing that some of these datatype attribute are working for a small part.

__2__
It would be nice that a developer knows which attributes can be used for validation.

will work

`[EmailAddress]` (`public sealed class EmailAddressAttribute : DataTypeAttribute`) 
`[Required]` (`public class RequiredAttribute : ValidationAttribute`)

but datatype will not work
`[DataType(DataType.Password)]` (`public class DataTypeAttribute : ValidationAttribute`)
And only clientvalidation with no curstom errormessage

`[DataType(DataType.EmailAddress)]` (`public class DataTypeAttribute : ValidationAttribute`)

Note: If only 1 field validation is set then all field will be validated against the html input-type

__3__
The only datatype that make sense is password. This could be another attribute (`PasswordAttribute` or `PasswordInputAttribute` like `HiddenInputAttribute`). 
The password is a very custom serverside validation that maybe could implemented as validation attribute but maybe to complex as validation rule

__4__
I think it is posible for taghelpers to use the html5 attribute notation see.
([#2503](https://github.com/aspnet/Mvc/issues/2503)) of @mrchief

To clean up a little bit. I like to see something like this
`<form  method="post" asp-browser-validation="false" asp-javascript-validation="true">`

model Attributes for validation en inputtype
* InputTypeHidden
* InputTypePassword
* InputTypeValidationEmail
* InputTypeValidationPhone
* InputTypeValidationNumber
* InputTypeValidation....
* RuleValidationRange
* RuleValidationRegEx
* RuleValidationStringLength
* RuleValidation...

If all MVC validation Attribute in a different namespace then they are easy to find

**Comment by danroth27** [comment]
(1) We think these attributes shouldn't cause any validation - we will investigate why this is happening. @dougbu Could you please take a look?
(2) We will need to document the attributes we support (https://github.com/aspnet/Docs/issues/116)
(3) Opened https://github.com/aspnet/Mvc/issues/2881 for this suggestion
(4) We don't currently support using HTML5 based validation because of browser limitations.

**Comment by dougbu** [comment]
W.r.t. (1) we're not validating at all. In fact many browsers ignore any issues in the field we generate for the `[DataType(DataType.EmailAddress)]` property. Instead the datatype specification causes MVC to generate `<input type="email" .../>` and _some_ browsers complain when users enter an invalid value in the field.

##### Details
With the following model
``` c#
    public class User
    {
        [Required]
        public string Name { get; set; }

        [DataType(DataType.EmailAddress, ErrorMessage = "This is a custom error.")]
        public string Email1 { get; set; }

        [EmailAddress(ErrorMessage = "This is a custom error.")]
        public string Email2 { get; set; }
    }
```
and `@Html.EditorFor(model => model.Name)` and so on for each property, MVC generates
``` html
<input class="text-box single-line" id="Email1" name="Email1" type="email" value="" />
<input class="text-box single-line" data-val="true" data-val-email="This is a custom error." id="Email2" name="Email2" type="email" value="" />
```

Note the `Email1` field does not mention the custom error message or have any attributes (e.g. `data-val`) which hook up unobtrusive validation.

**Comment by dougbu** [comment]
Clearing labels and assignee to kick this back to __@Triage__. Not sure there's any remaining action here since the outstanding issues are now tracked separately.
