### ISSUE TITLE
WebSite  : LocalizationWebSite

### ISSUE THREAD

**Issue by branciat** [aspnet/Mvc#2876]
Hi,

The website example contains errors, in the method GetStringSafely of the class TestStringLocalizer, the search is into the directories "Resources\bin" which not exist, and the extension file that use is resx and not .resources. 
After making changes, the ResourceManager class don't load the strings, the count is zero.

**Comment by danroth27** [comment]
@kirthik Can you please take a look?

**Comment by kirthik** [comment]
Dnx does not support creating .resources files or satellite assemblies yet. I am creating `.resources` as part of localization test. 

@branciat, you could run the code in https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.FunctionalTests/LocalizationTest.cs#L140 passing resource file name for creating .resources as a temporary workaround.

Once dnx supports adding .resources file, this workaround would not be needed.

**Comment by branciat** [comment]
Thanks i look that today.

**Comment by branciat** [comment]
@kirthik  It's all right, the files are converted and the localization also.
I close the issue.
Thank
