### ISSUE TITLE
How to add a ressource file (.resx) to a xproj?

### ISSUE THREAD

**Issue by a99cl208** [aspnet/Mvc#2877]
Hi,

I'm just wondering, how do you add a resx file in a xproj? I've seen some one of them in your Mvc.Core project, but in Visual Studio this kind of file is neither available in the "add file" menu nor in the project properties, and anyway the custom tool genertor does not exists in xproj.

Did i missed something?

Thanks.

**Comment by kirthik** [comment]
We don't have support for this yet. This is a VS tooling issue. cc @danroth27, @rustd.

**Comment by a99cl208** [comment]
Ok, so how have you been able to add those files in the aspnet projets (like mvc core for instance)? Are you maintaining them manually?

Also, any plan to support this on incoming release?

Thanks

**Comment by pranavkm** [comment]
@a99cl208 Seemingly the "Resx" template was removed from the list of DNX item templates. Feel free to file a bug in https://github.com/aspnet/Tooling to track this. 
A workaround for the time being would be to start from a "Text file" and rename it with a `.resx` extension. We use a script - https://github.com/aspnet/Universe/blob/dev/build/_k-standard-goals.shade#L193-L213 - to generate designer files for resx manually. The plan is to eventually have a precompile module that would do this instead.
