### ISSUE TITLE
Add a PasswordInputAttribute for specifying password input

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#2881]
Originally requested by @anderman in https://github.com/aspnet/Mvc/issues/2873

Similar to how we have `HiddenInputAttribute` consider adding a `PasswordInputAttribute` for specifying password input.

**Comment by dougbu** [comment]
One existing workaround is `[UiHint("Password")]` on the property.

**Comment by pranavkm** [comment]
Given that a workaround is available, should we close this?

**Comment by dougbu** [comment]
@pranavkm yes, we don't need `[PasswordInput]`. The only reason `[HiddenInput]` exists is for back-compatibility with MVC 5.2.x.

I shouldn't have called `[UiHint("Password")]` a "workaround". That's the _solution_ we should recommend.
