### ISSUE TITLE
Localization using route data

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#2884]
I asked at aspnet/Localization#57, but it seems that repository doesn't get any love at all :sob:
I was trying to write a culture change middleware which loaded culture from the route data
```
/{language}/{controller}/{action}/{id?}
/en/home/index
/fr/home/index
```
```C#
public async Task Invoke(HttpContext context)
{
    // var controller = RouteData.Values["controller"];
    // var language = RouteData.Values["language"];
    // var action = RouteData.Values["action"];

    await Next(context);
}
```
But I looked through ```HttpContext``` class properties and I could not found any way to reach ```RouteData``` from within ```HttpContext```. Will this localization scenario will be supported in initial release? And how do you generally get route data in similar contexts?

**Comment by rynowak** [comment]
There's currently no way to combine routing and middleware.

I'd suggest taking a look at `IRequestCultureProvider` and its usages in the localization middleware. Write your own one of these to parse the language from the URL.

If you wanted to use routing for this, you could do it using an action filter, but by doing so you're blazing your own trail.

**Comment by Muchiachio** [comment]
I guess I will wait, because parsing it from url is baah :disappointed:, especially with url templates like `{language=fr}/{controller=home}/{action=index}`, because default values may not even be included in the url.
