### ISSUE TITLE
Set cultures with without user override

### ISSUE THREAD

**Issue by paulomorgado** [aspnet/Mvc#2885]
(I don't know if this is the write place or if this has already been discussed)

matching culture setting between the server and client is extremely hard, even with all the frameworks out there.

On top of that, .NET respects user modifications to cultures which can create havoc.

For example, I have the date time information on my user profile set to **pt-PT** but, instead of using the standard date format (**dd/MM/yyyy**), I prefer **yyyy-MM-dd**. And now all handling of dates between client and server are mangled.

One doesn't expect a server to have this kind of problems, but the applications are (still) developed by people and the development system might have these issues.

The solution is very simple. Instead of using the [CultureInfo](http://referencesource.microsoft.com/#mscorlib/system/globalization/cultureinfo.cs) [constructor with just the culture name](http://referencesource.microsoft.com/mscorlib/R/cb4dd1c3262abd32.html), use [the constructor that allows to specify not to use user overrides](http://referencesource.microsoft.com/mscorlib/R/65ff497f51fce595.html).

For now, I'm using this:

```
protected void Application_BeginRequest(object source, EventArgs e)
{
    var currentCulture = Thread.CurrentThread.CurrentCulture;
    if (currentCulture.UseUserOverride)
    {
        Thread.CurrentThread.CurrentCulture = new CultureInfo(currentCulture.Name, false);
    }
}
```

**Comment by danroth27** [comment]
This looks like a question for ASP.NET 4.6 (`Application_BeginRequest`), which we can't really change, but we should consider what we want to do for ASP.NET 5.

**Comment by danroth27** [comment]
Please note that this behavior in ASP.NET 5 is handled by middleware, which you opt into. You can choose to have the behavior you want by substituting your own middleware. The question here is if this behavior should be our default behavior in the middleware we ship.

**Comment by paulomorgado** [comment]
I understand that.

What do you think is the best default?

**Comment by Eilon** [comment]
@DamianEdwards ping on this. Should we be passing in the flag to `CultureInfo` to ignore user modifications? Ultimately I believe this bug should go to the https://github.com/aspnet/Localization/issues/ issue tracker if we decide we should do this.

**Comment by DamianEdwards** [comment]
I'm not sure that overload exists in Core.

**Comment by pranavkm** [comment]
The API exists in .NET Standard - https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.-ctor?view=netstandard-2.0#System_Globalization_CultureInfo__ctor_System_String_System_Boolean_. Populating `RequestLocalizationOptions.SupportedCultures` with instances  of `CultureInfo` constructed using the overload constructor does the job. 

@mkArtakMSFT  should be good to close this, unless @paulomorgado has further concerns.

**Comment by paulomorgado** [comment]
That explicit opt-in seems to be a good solution.
