### ISSUE TITLE
How to access DBContext from CookieAuthenticationNotifications

### ISSUE THREAD

**Issue by ponsaravanan** [aspnet/Mvc#2892]
I am trying to access db context from  CookieAuthenticationNotifications.OnValidatePrincipal for populating some properties from db. But couldn't access it. 

Searched for online documents on how to do the same. But no luck so far. 

MVC6, Beta5. I am using.

Any inputs to guide me will be greatly appreciated.

**Comment by danroth27** [comment]
Moved to https://github.com/aspnet/Security/issues/383
