### ISSUE TITLE
MVC 6 Beta 7 Localization issue.

### ISSUE THREAD

**Issue by pnvpratik** [aspnet/Mvc#2893]
Hi , 

I am running into some dependency resolution issues when I am trying to use the MVC 6 localization packages.

When I add the following 2 packages 

```
  "Microsoft.AspNet.Localization": "1.0.0-beta7-10364",
    "Microsoft.Framework.Localization": "1.0.0-beta7-10364",
```

packages and add the following line in ConfigureServices in the Startup.cs

```
   services.AddMvcLocalization();
```

I get a new error when the IHtmlLocalizer package .

It seems this is only an issue with the localization package as my Startup method in Startup.cs is able to get the dependency resolved for IApplicationEnvironment.

```
  public class HomeController : Controller
    {
        private readonly IHtmlLocalizer _localizer;
        public HomeController(IHtmlLocalizer<HomeController> localizer)
        {
            _localizer = localizer;
        }
          ....
```

Error :

```
An unhandled exception occurred while processing the request.

InvalidOperationException: Unable to resolve service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' while attempting to activate 'Microsoft.Framework.Localization.ResourceManagerStringLocalizerFactory'. Microsoft.Framework.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
```

Cant figure out if its a dependency i am missing or there is a issue in the code

**Comment by danroth27** [comment]
What version of DNX are you running on?

**Comment by pnvpratik** [comment]
I am using beta7-12290 

my dnvm list outout below


Active Version           Runtime Architecture Location                       Alias
------ -------           ------- ------------ --------                       -----
       1.0.0-beta4       clr     x86          C:\Users\pvasani\.dnx\runtimes
       1.0.0-beta5       clr     x64          C:\Users\pvasani\.dnx\runtimes
       1.0.0-beta5       clr     x86          C:\Users\pvasani\.dnx\runtimes default
       1.0.0-beta5       coreclr x64          C:\Users\pvasani\.dnx\runtimes
       1.0.0-beta5       coreclr x86          C:\Users\pvasani\.dnx\runtimes
       1.0.0-beta6       clr     x64          C:\Users\pvasani\.dnx\runtimes
       1.0.0-beta6       clr     x86          C:\Users\pvasani\.dnx\runtimes
       1.0.0-beta6       coreclr x64          C:\Users\pvasani\.dnx\runtimes
       1.0.0-beta6       coreclr x86          C:\Users\pvasani\.dnx\runtimes
       1.0.0-beta7-12290 clr     x64          C:\Users\pvasani\.dnx\runtimes
  *    1.0.0-beta7-12290 clr     x86          C:\Users\pvasani\.dnx\runtimes
       1.0.0-beta7-12290 coreclr x64          C:\Users\pvasani\.dnx\runtimes
       1.0.0-beta7-12290 coreclr x86          C:\Users\pvasani\.dnx\runtimes

**Comment by Eilon** [comment]
In your project.json are you sure you're using the latest set of every package? In `beta7` some breaking changes were made and you have to get a full new set of packages to ensure they are compatible with one another.

**Comment by pnvpratik** [comment]
I have taken the beta7 version of most packages where possible and have done the steps mentioned in the Announcement project here https://github.com/aspnet/Announcements/issues/51



My dependencies in project.json

"dependencies": {
    "EntityFramework.SqlServer": "7.0.0-beta5",
    "EntityFramework.Commands": "7.0.0-beta5",
    "Microsoft.AspNet.Mvc": "6.0.0-beta7-14347",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta7-14376",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta7-12738",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta7-13465",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta7-13465",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta6",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta7-12119",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7-12492",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta7-12222",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta7-13653",
    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta7-11622",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta7-11622",
    "Microsoft.Framework.Configuration.UserSecrets": "1.0.0-beta7-10567",
    "Microsoft.Framework.Logging": "1.0.0-beta7-11626",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta7-11626",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta6",
    "RavenDB.Client": "3.0.3690",
    "NBuilder": "3.0.1.1",
    "RavenDB.Database": "3.0.3690",
    "Microsoft.AspNet.Localization": "1.0.0-beta7-10364",
    "Microsoft.Framework.Localization": "1.0.0-beta7-10364",
    "Microsoft.Dnx.Runtime": "1.0.0-beta7-12290",
    "Microsoft.Framework.CodeGenerators.Mvc":"1.0.0-beta7-12599"
  },

**Comment by Eilon** [comment]
Can you try using `...-beta7-*` for all the packages to see if that makes it work?

**Comment by kirthik** [comment]
I am able to repro this issue. I am investigating the cause now.

**Comment by kirthik** [comment]
Ok. `Microsoft.Framework.Runtime.IApplicationEnvironment` is incorrect since namespace changed now. Change `Microsoft.Framework.Runtime` to `Microsoft.Dnx.Runtime`. It is better to clear your packages cache so all old packages before rename are deleted.

**Comment by pnvpratik** [comment]
@Eilon  & @kirthik  Thanks for the Info , Taking the beta7-* and clearing all the contents of my C:\Users\<me>\.dnx\packages got rid of the error.
