### ISSUE TITLE
Default Razor Directives

### ISSUE THREAD

**Issue by nikmd23** [aspnet/Mvc#2895]
After a quick chat with @NTaylorMullen, I decided to open this feature request.

Right now it's possible to inject a default `@addTagHelper` directive (and other directives) into Razor by implementing a custom MvcRazorHost, as I'm doing here:

``` C#
public class CustomRazorHost : MvcRazorHost
{
    public CustomRazorHost(ICodeTreeCache codeTreeCache) : base(codeTreeCache)
    {
    }

    private IReadOnlyList<Chunk> _overriddenChunks;

    public override IReadOnlyList<Chunk> DefaultInheritedChunks
    {
        get
        {
            if (_overriddenChunks != null)
                return _overriddenChunks;

            var original = base.DefaultInheritedChunks.ToArray();
            var newArray = new Chunk[original.Length + 1];

            original.CopyTo(newArray, 0);

            newArray[original.Length] = new AddTagHelperChunk
            {
                LookupText = "*, MyAssembly"
            };

            _overriddenChunks = newArray;

            return _overriddenChunks;
        }
    }
}
```

The problem is only one of these can be registered, so its a point on contention.

Has any consideration been given to creating first class support for adding a `Chunk`, that doesn't require overriding Razor Host?

**Comment by avanderhoorn** [comment]
@DamianEdwards any thoughts?

**Comment by DamianEdwards** [comment]
There are many things we could do to make the Razor compilation pipeline more extensible. I'd prefer to have a serious look at the problem space and consider all options and ideas together so that we can build a well rounded feature set here, rather than opening up sections on an ad-hoc basis. Right now, the Razor Host is really the thing that extends Razor, and as you said, that's fairly limiting. I don't see us doing anything meaningful in this space until after RTM.

**Comment by avanderhoorn** [comment]
Makes sense. Given that, both us and several other "clients/users" have the need to inject scripts into the payload without the user having to modify their page. Previously, we did this by injecting into the stream directly but that has its own challenges as I'm sure you can imagine.

**Comment by SergeyKanzhelev** [comment]
We are asking customer to use [HtmlHelper for this](https://github.com/Microsoft/ApplicationInsights-aspnet5/wiki/Getting-Started#add-application-insights-javascript-instrumentation-to-the-_layoutcshtml-if-present). However this requires us to take a reference on MVC package and for customer to do it by hand. It will be beneficial for us to have better story here. 

@DamianEdwards, before RTM would you recommend to switch to TagHelpers?

**Comment by pranavkm** [comment]
FYI - most of the current limitations we have are primarily due design time and precompilation support. 
Options configured in startup don't flow to the precompilation module or design time host. Consequently if we were to have options that modified the behavior of the host at runtime, you wouldn't see autocompletion for these in tooling (VS intellisense), nor would they light up for precompiled views.

We had discussions early on to figure out how we could make this work correctly, but afaik it's not being actively being looked at.

**Comment by DamianEdwards** [comment]
@SergeyKanzhelev you could offer both. Tag Helpers make it much easier to compose the source HTML along with the action of the Tag Helper, e.g. add or change an attribute, so that's nice, but in your case probably less likely as you're just returning a `<script>` tag. Although, as a Tag Helper, it would be much easier for people to add things like the `async` and `deferred` attributes if they wanted to, e.g.

``` HTML
<application-insights-script type="text/javascript" async="true" defer="true"></application-insights-script>
```

**Comment by DamianEdwards** [comment]
@avanderhoorn yeah that's what Browser Link does (inject into the response stream). If you want something more "structured" than that, you really need a placeholder in the markup or a server-side DOM, or the concept of a Script Manager like Web Forms has. You could create a Tag Helper that targets the `<body>` tag and inject your script reference after the child contents. Of course that still requires the Tag Helper be registered, which is probably why you're trying to modify the chunk tree.

**Comment by avanderhoorn** [comment]
Exactly :) that's what got us down this path currently. We though tag
helper would be a much better approach to the problem but the tag helper
needs to be registered.

**Comment by Eilon** [comment]
Closing this, but cc @rynowak for FYI information in case this somehow relates to the work and re-work you've been driving in Razor.

**Comment by rynowak** [comment]
`RazorTemplateEngine` has this feature but we don't expose a way to configure it from MVC
