### ISSUE TITLE
Get rid of manual body-read-state-tracking

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#2900]
MVC has custom code to track whether or not the request body has been read, which is easily circumvented. Right now this just prevents a class of common errors like putting `[FromBody]` on two parameters.

We should remove our logic for this and use what's suggested here: https://github.com/aspnet/BasicMiddleware/pull/6/files#r36109498

**Comment by kichalla** [comment]
@rynowak @danroth27 and I discussed about this issue and agreed that adding a check for if a body was read or not to inform users of potential mistakes does not add much value.
