### ISSUE TITLE
ImageTagHelper doesn't work well with other TagHelpers.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2902]
Today, `ImageTagHelper` relies too heavily on it's bound `Src` attribute which in turn makes interactions with other `TagHelper`s insufficient. Aka, if another `TagHelper` modifies `output.Attributes["src"]` the `ImageTagHelper` will trump their value instead of use it.

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by DamianEdwards** [comment]
Hmmmm, this sounds familiar. Oh yeah, I've always said binding those was stupid :P

**Comment by dougbu** [comment]
How would we handle encoding issues after making this suggested change?

**Comment by NTaylorMullen** [comment]
Would there be a problem consuming the value already encoded? If not we could just ensure that values are not re-encoded.

**Comment by NTaylorMullen** [comment]
Talked offline, with @dougbu, this isn't possible today.

**Comment by NTaylorMullen** [comment]
Actually, we can complete this partially. Updated issue to reflect change indirection.

**Comment by DamianEdwards** [comment]
Is meant to be closed still?

**Comment by NTaylorMullen** [comment]
c3e2e6fa0a8888374e3d05127185cea314622ffb
