### ISSUE TITLE
`CompositeValueProvider` does not match `IBindingSourceValueProvider` contract

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2907]
Of the `IBindingSourceValueProvider` implementations in MVC, all but `CompositeValueProvider` have a `Filter()` method that returns `null` when the requested `BindingSource` does not match. `CompositeValueProvider` instead returns an empty `CompositeValueProvider`.

Also have a little code in `CompositeModelBinder` and `MutableObjectModelBinder` that expects the `CompositeValueProvider` behaviour of all `IBindingSourceValueProvider` impelmentations. That is, they need to change slightly to handle the expected / contracted `null` return values from `Filter()`.

**Comment by Eilon** [comment]
Make 'em match!

**Comment by dougbu** [comment]
Teal it is :smiling_imp:

**Comment by dougbu** [comment]
4a81377
