### ISSUE TITLE
JsonPatch: handling casing

### ISSUE THREAD

**Issue by KevinDockx** [aspnet/Mvc#2911]
When applying a patchdoc to an object, I have to find the properties the operations need to be applied to on the class; this search is done regardless of casing.  That's probably how most users would expect it to work (and how it's always been in the original component).  

The downside of this is that when that class contains both "name" and "Name" properties, the first property found will be used (issue logged as per @rynowak's PR comment ).    

Maybe we can look into the best way to handle this?  Leave as is? Or allow configuration (passing in a custom (or case sensitive) comparer)?

**Comment by Eilon** [comment]
I commented in the PR:

> In .NET a CLS-compliant type cannot have members that very only by casing. That is to support languages such as VB, which are case-insensitive. As such, I think it's totally acceptable to have odd, unusual, or bizarre behavior if members vary only by case.
