### ISSUE TITLE
Where is ActionFilterAttribute?

### ISSUE THREAD

**Issue by XiaoweiJia** [aspnet/Mvc#2919]
Which package can I find to create custom action filters? In previous mvc, I can create one by inheriting from ActionFilterAttribute. Now this class seems to have moved. Please help. Thanks

**Comment by rynowak** [comment]
This is still here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ActionFilterAttribute.cs

If you're building a site, you should reference `Microsoft.AspNet.Mvc` which will include this package.
