### ISSUE TITLE
No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered

### ISSUE THREAD

**Issue by rahuldhariya01** [aspnet/Mvc#2921]
I get this issue when i run mycode base with Brand new visual studio 2015 enterprise. it was working fine. i guess it is some dnx update issue. can anyone help ?

Error : No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered

**Comment by rynowak** [comment]
This is almost certainly an issue with mismatched package versions.

Please double check that your version of DNX is compatible. eg. beta-6 DNX only works with beta-6 MVC. You can see this by opening the project's properties in VS.

**Comment by rahuldhariya01** [comment]
@rynowak ,  I have mvc 6.0.0-beta4 in project json and DNX  SDK  is 1.0.0-beta4. 
If i change DNX then i am unable to build my project solutions. 
can you please suggest anything this kind of very urgent.

**Comment by rynowak** [comment]
Where is the error coming from, can you include a callstack?

**Comment by rahuldhariya01** [comment]
Attached is the screenshot  and call stack.

@rynowak , this is runtime error, i dont have complete call stack. 
this is what i am seeing at screen,

[InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

[HttpException (0x80004005): No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.]
   
![error](https://cloud.githubusercontent.com/assets/12662043/9117111/008083b6-3c1d-11e5-8120-67bc90e5e1cf.png)
System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9924184
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

**Comment by rynowak** [comment]
@Tratcher

**Comment by Tratcher** [comment]
This is a known breaking change. We're just waiting for our build to produce the new packages (later today). In the meantime you can use WebListener or Kestrel.

**Comment by rahuldhariya01** [comment]
@Tratcher, As you say this could be fix by eod so i can wait for one day, can you be sure that this can be fixed by eod ?

**Comment by Tratcher** [comment]
It is already fixed, the packages just aren't on the vnext feed yet. ETA is unconfirmed. You can get the packages from https://www.myget.org/F/aspnetvolatile/api/v2 if you're in a hurry, but I don't recommend using this feed normally as it's highly unstable.

**Comment by rahuldhariya01** [comment]
Thanks @Tratcher , Yes i am in hurry. Will this package works with azure web app ?  How to install this package to solutions ?

**Comment by rahuldhariya01** [comment]
@Tratcher  @rynowak  any update ? i am really in hurry.

**Comment by Tratcher** [comment]
It's not a package, it's a nuget feed.  Add it to your nuget feed settings in VS.

However, if you're in that much of a hurry I recommend going back to the stable beta6 packages on nuget.org.

**Comment by rahuldhariya01** [comment]
@Tratcher   beta6 package of what ? i have not changed anything.  Can you please explain this in details ?

**Comment by Tratcher** [comment]
Ah. Go back to the command line and use `dnvm list` to make sure that 1.0.0-beta6 is your `default` and `active`. Close and re-open VS. Open your global.json file and remove any reference to the SDK version. Then open your project.json files and make sure all of the Microsoft.* packages are beta6.

**Comment by rahuldhariya01** [comment]
Thanks @Tratcher , Changed dnvm to latest one and updated project json to latest. Now even if i create new project i see this error , any suggestion ?

Error : Current runtime Target Framework: 'DNX,Version=v4.5 (dnx45)'
 Type: CLR
 Architecture: x86
 Version: 1.0.0-beta6-12256

**Comment by danroth27** [comment]
Where do you see this error? Is it an error dialog in VS? Text in the output window?

Note that the version number suggests that VS is not picking up the official beta6 version. Try doing a `dnvm upgrade` from the command line and then `dnvm alias default 1.0.0-beta6`.

**Comment by danroth27** [comment]
Haven't heard back in a while - closing for now, but let us know if you are still seeing this issue.
