### ISSUE TITLE
More powerful tag helpers

### ISSUE THREAD

**Issue by firelizzard18** [aspnet/Mvc#2928]
I would like to see more powerful tag helpers, particularly generic tag helpers, and a tag helpers that can create context for other helpers. I would like to be able to do something like:

```
<ul>
  <li asp-foreach="MyList"><display asp-for="ListElement_Property" /></li>
</ul>
```

It would be absolutely fantastic to be able to do something like:

```
<table>
  <thead>
    <tr><th><display asp-namefor="ListElement_Property" /></th></tr>
  </thead>
  <tbody>
    <tr asp-foreach="MyList"><td><display asp-for="ListElement_Property" /></td></tr>
  </tbody>
</table>
```

**Comment by Eilon** [comment]
@DamianEdwards I believe you have some thoughts in this space?

**Comment by danroth27** [comment]
@DamianEdwards Moved to backlog

**Comment by rynowak** [comment]
It's really not clear to me what specific action item this is tracking, suggest we close it.

**Comment by DamianEdwards** [comment]
Yeah the examples here fall into the category of supporting code generation and/or templating which are covered in other issues.

**Comment by firelizzard18** [comment]
At least when I last looked at it, tag helpers were missing critical capability (from my perspective) that prevented them from being able to recreate the level of utility that things like `@Html.NameFor` provided.

**Comment by DamianEdwards** [comment]
Not disagreeing, simply that this issue as stated isn't really a good one for tracking specific work.
