### ISSUE TITLE
IsLocalUrl is not what I need

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#2929]
The implementation should be dynamic, or it should be renamed `IsRelativeUrl`, because right now it is not checking if the url is local, just relative, which is a sub-case of local.

It needs at least to check the `HOST` header, and at best a set of custom authority I could pass as a parameter. Ideally it would be a service that I can re-implement. 

Also, please explain what this sentence means, or just remove it from the comment 
> An URL with an absolute path is considered local if it does not have a host/authority part

**Comment by danroth27** [comment]
This method was designed to help prevent open redirects. Sounds like you are trying to do something different. Can you tell us what you are trying to accomplish with this method?

**Comment by sebastienros** [comment]
The issue is that the method is not extensible AND you are using it in places where we need to put more logic. For instance it doesn't work with fully qualified URLs. Not mentioning if my app supports multiple domains.

If only you were not using it, I wouldn't care, but the logic is that the logic is both hard coded and incomplete. Ask Taylor, or Pranav ...

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Wed, Aug 12, 2015 at 9:47 AM -0700, "Daniel Roth" <notifications@github.com<mailto:notifications@github.com>> wrote:


This method was designed to help prevent open redirects. Sounds like you are trying to do something different. Can you tell us what you are trying to accomplish with this method?

-

**Comment by danroth27** [comment]
> you are using it in places where we need to put more logic.

What places are you referring to?

**Comment by sebastienros** [comment]
My bad, let's assume anywhere it's used internally that can't be changed. For instance RedirectResult. Or anywhere the framework or libraries will use it in the future in some places that can't be extended.

Do you at least acknowledge that the current implementation doesn't work with FQDN and that it's a valid scenario to redirect users using FQDN urls?

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Thu, Aug 13, 2015 at 9:01 AM -0700, "Daniel Roth" <notifications@github.com<mailto:notifications@github.com>> wrote:


you are using it in places where we need to put more logic.

What places are you referring to?

-

**Comment by danroth27** [comment]
Would it be sufficient to make IsLocalUrl virtual?

**Comment by sebastienros** [comment]
I will assume you mean `IsLocalUrl` in `UrlHelper`. This would help as in I could reuse all other base implementations to create my own `IUrlHelper`. 

But the fact that `UrlUtility` is another entry point for this method would make things worse, with two implementations in the wild. The fact that `UrlHelper` is a service is perfect otherwise.

My suggestion is to either
- make `UrlUtiliy` a service, which would let me re-implement the logic
- suppress `UrlUtility` and move the implementation in a `virtual bool IsLocalUrl` on the helper. After all I don't see it used anywhere else so far, and the opposite behavior, i.e. `IUrlHelper.Content()` is in there already, so it would be consistent.

Thanks

**Comment by rynowak** [comment]
I don't recall exactly why we put the implementation in a static method. At this point nothing in the framework is calling into it.
