### ISSUE TITLE
Posting object no longer works with Beta 6

### ISSUE THREAD

**Issue by cwoolum** [aspnet/Mvc#2932]
I just upgraded from Beta5 to Beta6 and I can no longer post objects using Web Api. My method is defined as so:

```
[HttpPost]
[Route("")]
async Task<IActionResult> Save(User user)
```

For some reason, user is always a new object. I used to have the [FromBody] tag on User but then it was just null. I did have to change my Json formatter configuration from 

```
services.AddMvc().Configure<MvcOptions>(options =>
            {
                var oldFormatter = options.OutputFormatters.FirstOrDefault(f => f is JsonOutputFormatter);
                options.OutputFormatters.Remove(oldFormatter);

                var settings = new JsonSerializerSettings()
                {
                    ContractResolver = new CamelCasePropertyNamesContractResolver(),
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                };
                var formatter = new JsonOutputFormatter();
                formatter.SerializerSettings = settings;

                options.OutputFormatters.Add(formatter);
            });
```

to 

```
 var mvc = services.AddMvc().ConfigureMvcJson(options =>
            {
                options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            });
```

Did I miss something else in the Beta 6 conversion??

**Comment by rynowak** [comment]
> I used to have the [FromBody] tag on User but then it was just null. I did have to change my Json formatter configuration from

If you're posting JSON data that you want to be read by a formatter, you **must** have `[FromBody]` on your parameter.

```
[HttpPost]
[Route("")]
public async Task<IActionResult> Save([FromBody] User user)
{
}
```

Do you have a repro project we can take a look at to figure out what's going on?

**Comment by danroth27** [comment]
If you could show us the request you sent when you had `[FromBody]` on the action parameter we could investigate more. Closing for now as there isn't enough data here to make progress on this issue.
