### ISSUE TITLE
Add HtmlString constructor that doesn't require ToString for buffers.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2935]
Currently, in order to create a new `HtmlString` you need to provide a base string value. However, in the case that we have a buffer available to us it'd be nice to essentially do `new HtmlString(buffer)` to avoid the `ToString` all together.

**Comment by dougbu** [comment]
As mentioned in the [PR discussion](https://github.com/aspnet/Mvc/pull/2916#discussion-diff-36546352) that led to this bug, passing a buffer when creating an `HtmlString` may not be necessary once @sornaks' changes go in. So this isn't exactly the follow-up bug I suggested.

Instead we might need to have a larger discussion about the MVC / Razor extensibility model given the addition of `IHtmlContent`. In particular an `HtmlString` is no longer the _only_ non-`string` that needs no further HTML encoding. For example any `IHtmlContent` instance might wrap a buffer containing only values that need no further encoding.

Of course it's possible the `ToString` I originally said "ick" about may show up in perf profiles. If / when it does we way want to revisit @NTaylorMullen's approach.

**Comment by danroth27** [comment]
We'll analyze perf and do this as necessary.
