### ISSUE TITLE
Upload file with angularjs using IFormFile.

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Mvc#2938]
What is the correct json data structure that bind to a property type of  IFormFile in server side?

**Comment by kichalla** [comment]
Following sample gives an idea of how to handle multipart requests by yourself(in your case you need to use the JsonInputFormatter out of options to read the section parts which are json), but I think we should add a sample for your scenario too:

https://github.com/aspnet/Entropy/blob/dev/samples/Content.Upload.Multipart/Startup.cs

**Comment by mikeandersun** [comment]
Thanks for response. 
I wait for an angularjs sample. :)

**Comment by jraadt** [comment]
Any updates or suggestions on how to read multipart file uploads?  I'm attempting to upload multiple files using ajax and I'm unsure what the current best practice is to read those files.

**Comment by rynowak** [comment]
If you're using MVC,  you have a few options in how to author the code, I don't think any one of them is necessarily better than the others.

1. Bind each file to a parameter
```
public IActionResult HandleFiles(IFormFile file1, IFormFile file2) { ... }
```

If you know the names of the form fields that will include the files, you can model bind to those names directly.

===============

2. Bind the files collection to a parameter
```
public IActionResult HandleFiles(IEnumerable<IFormFile> files) { ... }
```

============

3. Read the files collection off of the `HttpRequest`
```
public async Task<IActionResult> HandleFiles()
{
    var files = (await Request.GetFormAsync()).Files
}
```

**Comment by pebezo** [comment]
@rynowak The second options didn't work for me (request coming via AJAX; files was set, but the count was always 0), but option 3 did. Thanks.

**Comment by pebezo** [comment]
Oh, and I guess the API changed since you wrote that; I didn't have GetFromAsync on Request, but ReadFormAsync worked.

**Comment by error505** [comment]
I would also like to see one angularjs example or jquery or what ever just to know how to counstruct model that should be sent to IFormFile to accept it... I have already tried with FormData but it doesnt work at all. I always get null. [Take a look here](http://stackoverflow.com/questions/38144194/iformfile-is-always-empty-in-asp-net-core-webapi)

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/issues/948

**Comment by error505** [comment]
I have tried to construct data as it is constructed when you upload from razor form something like this 
dataService.addFile(formdata, {
            contentDisposition: "form-data; name=\"files\"; filename=\"C:\\Users\\UserName\\Desktop\\snip_20160420091420.png\"",
            contentType: "multipart/form-data",
                    headers: {
                        "Content-Disposition": "form-data; name=\"files\"; filename=\"C:\\Users\\UserName\\Desktop\\snip_20160420091420.png\"",
                        'Content-Type': "image/png"
                    },
                    fileName: "C:\\Users\\UserName\\Desktop\\snip_20160420091420.png",
                    name: "files",
                    length : 3563
            }
but still no success, I have tried with a raw file instead of formdata, only data constructed like this and i have no idea what more but anyway it is null on webapi controller.

**Comment by error505** [comment]
Here is solution how to send it with angularjs
`vm.addFile = function () {                      
                    var fileUpload = $("#file").get(0);
                    var files = fileUpload.files;
                    var data = new FormData();
                    for (var i = 0; i < files.length ; i++) {
                        data.append(files[i].name, files[i]);
                    }
                    $http.post("/api/Files/", data, {
                        headers: { 'Content-Type': undefined },
                        transformRequest: angular.identity
                    }).success(function (data, status, headers, config) {

                    }).error(function (data, status, headers, config) {

                    });
}`

**Comment by kichalla** [comment]
There is a new sample in `Entropy` repo which shows file upload with angularjs but it does not use `json` structure though

https://github.com/aspnet/Entropy/tree/1.0.0/samples/Mvc.FileUpload

**Comment by Eilon** [comment]
Closing because there are no plans to expand on this.
