### ISSUE TITLE
IExceptionFilter not being called in views

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#2942]
Given registered exception filter in beta6:
```C#
public class ExceptionFilter : IExceptionFilter
{
    public void OnException(ExceptionContext filterContext)
    {
    }
}

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();
        services.Configure<MvcOptions>(options => options.Filters.Add(typeof(ExceptionFilter)));
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseStaticFiles();
        app.UseMvcWithDefaultRoute();
    }
}
```
And throwing exception in a view
```
@{
    throw new Exception();
}
```
results in
`ExceptionFilter.OnException(ExceptionContext filterContext)` not being called, even though it is called then exception is thrown from the controller. MVC5's ExceptionFilter works in both controller and the view.

Repro
https://github.com/Muchiachio/NoExceptionFilterInViews

**Comment by Eilon** [comment]
@rynowak do you remember if this was a deliberate design change?

**Comment by rynowak** [comment]
@Eilon - yes this was intended. Rationale was that exceptions in a 'result' are rarely recoverable because headers have likely been sent.

**Comment by Muchiachio** [comment]
Oh, okay, as long as it's intended.
