### ISSUE TITLE
input / output formatters stopped working in beta6

### ISSUE THREAD

**Issue by Droritos** [aspnet/Mvc#2943]
* I'm sorry if I'm adding this issue not in the right place ...

I just upgraded from beta4 to beta6 and this code stopped working (it doesn't have an effect):

        // In startup.cs
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            services.ConfigureMvc(o =>
            {
                // Input Formatters.
                var jif = new JsonInputFormatter();
                jif.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                jif.SerializerSettings.DefaultValueHandling = DefaultValueHandling.Ignore;
                jif.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;

                o.InputFormatters.Clear();
                o.InputFormatters.Add(jif);

                // Output Formatters.
                var jof = new JsonOutputFormatter();
                jof.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                jof.SerializerSettings.DefaultValueHandling = DefaultValueHandling.Ignore;
                jof.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
                
                o.OutputFormatters.Clear();
                o.OutputFormatters.Add(jof);
            });
        }

My controller:

    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        // GET: api/values
        [HttpGet]
        public IActionResult Get()
        {
            var responseObject = new TestDto { Result = "Error" };
            var jsonResult = new JsonResult(responseObject)
            {
                StatusCode = (int)HttpStatusCode.OK,
            };

            return jsonResult;
        }

        private class TestDto
        {
            public string Result { get; set; }

            public string Reason { get; set; }
        }
    }

With these settings and controller in beta6 I get this as a server response:

{"Result":"Error","Reason":null }

When downgrading to beta4, everything works again ...

{"result":"Error" }

* I tested it on two default web api projects with no other code or packages added. The project with beta4 worked and the other with beta6 didn't.

**Comment by Droritos** [comment]
While this can be fixed with the following code, why the code I used in my original post doesn't work (separation between input and output formatters) ?

        services.ConfigureMvcJson(o =>
        {
            o.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            o.SerializerSettings.DefaultValueHandling = DefaultValueHandling.Ignore;
            o.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
        });

**Comment by danroth27** [comment]
Yup, this was a deliberate change to JsonResult. Prior to beta6 JsonResult would try to find and use the configured JsonFormatters through some hacky code. In beta6 we changed the behavior so that JsonResult and the JsonFormatters use the same options.
