### ISSUE TITLE
ASP .Net MVC6 (beta6) actions returning strings

### ISSUE THREAD

**Issue by Haplois** [aspnet/Mvc#2944]
I have the following controller and action.

    [Route("/api/simple")]
    public class SimpleController : Controller
    {
        [HttpGet]
        [Route("test")]
        public string Test()
        {
            return "test";
        }
    }

When I call it, I expect action to return `"test"` (which is valid JSON), but instead it returns `test` (without quotation marks) is this a valid behavior, or bug? Am I missing something?

    GET http://localhost:5793/api/simple/test HTTP/1.1
    User-Agent: Fiddler
    Host: localhost:5793
    Accept: application/json
    

    HTTP/1.1 200 OK
    Content-Type: text/plain; charset=utf-8
    Server: Microsoft-IIS/10.0
    X-Powered-By: ASP.NET
    Date: Sun, 09 Aug 2015 14:37:45 GMT
    Content-Length: 4
    
    test

**Comment by rynowak** [comment]
This is expected behavior for the default configuration. There's a formatter configured by default that will return strings verbatim. 

If you want string to go through the normal conneg process, do the following:
```
// In Startup.cs
services.ConfigureMvc(o =>
{
    var stringFormatter = o.OutputFormatters.OfType<StringOutputFormatter>().First();
    o.OutputFormatters.Remove(stringFormatter);
});
```

**Comment by Haplois** [comment]
Thank you :+1: I missed that formatter.
