### ISSUE TITLE
System.Web.Mvc.JavaScriptResult.JavaScriptResult()

### ISSUE THREAD

**Issue by aaron-hammond** [aspnet/Mvc#2953]
Hi,

I was wondering what happened to the System.Web.Mvc.JavaScriptResult.JavaScriptResult() class?

I can't find it in the current implementation of MVC, is there any reason for this?

Thanks

**Comment by Eilon** [comment]
I don't think it was deliberate. We're not sure, however, how important a feature it is. It's somewhat of an anti-pattern when it comes to app development. Sending new dynamically-generated code to the browser would be considered by some<sup>[citation needed]</sup> to be a Very Bad Thing. Having said that, it's certainly quite useful at times.

Have you found it useful before, and you'd like to keep using it?

**Comment by aaron-hammond** [comment]
I agree it can be somewhat of an anti-pattern, however, In a few of our applications we've found it quite useful to solve a common requirement. 

Below is a description of how we use the class, it's very domain specific so i'll leave it to you to decide it this is a likely common scenario.

We heavily track the usage of our site, as each user visits our landing page we fire off a call to a webapi controller and generate a unique set of user information and an ID that relates to that user. 

This data is stored in an SQL database which we can pull from at a later date.

Once the data is stored and the ID has been generated we have conditions whereby this ID may need to be used for tracking purposes by 3rd parties or we may need to append the ID to an outbound URL that navigates to partner pages.

By returning a transformed piece of JavaScript that contains the specific ID for that user the browser will execute any calls / append any data that we require for tracking purposes. 

I've drawn a diagram to try and make this a little clearer:

![javascriptresult](https://cloud.githubusercontent.com/assets/7657318/9205733/ddcd784a-405b-11e5-85f7-d1a07dd676c7.png)

Perhaps we could do this without the use of the JavaScriptResult class but it has always worked quite nicely for us.

**Comment by Eilon** [comment]
I think the recommended "modern" pattern is to have the client make a request to the server to get the new ID, and then the client already has the code it needs to apply the ID to the URLs on the client. If the client doesn't have the code that applies the ID, it can load that scripts independently (by adding a new `<script>` tag that points to a static file).

The idea here is to avoid mixing data (user ID) and code (applying the user ID to URLs). By separating data and code, you gain flexibility such as easier ability to cache the code, and also ability on the client to make new use of the data (such as using the ID for other purposes).

**Comment by manfredk** [comment]
@Eilon 
A very valid use case for this is when initializing AngularJs - there's no way to do a http.get during the  config phase (except when manually bootstrapping angular using e.g. jquery.get). 

@aaron-hammond 
My workaround with aspnet5/mvc6 is:

    public class FilesController : Controller
    {
        public IActionResult TestJs()
        {
            var js = "console.log('test.js for " + User.Identity.Name + "');";
            var jse = Encoding.Convert(Encoding.Unicode, Encoding.UTF8, ByteConverter.GetBytes(js));
            return base.File(jse, "application/x-javascript");
        }
    }

Of course the route has to be mapped in startup.cs:

    app.UseMvc(routes =>
    {
        routes
            .MapRoute("configJs", "test.js", new { controller = "Files", action = "TestJs" })
            .MapRoute("default", "{controller=Home}/{action=Index}/{id?}");
    });

test.js then can simply be included in the html-file as script-tag.

**Comment by maxim-boligatov** [comment]
We need this result to send dynamically generated JavaScript. Of course it can be stupid to make such generation in regular application when we can share our static code using bundler minifier. But sometimes we have to generate something from server side. I personally want to share constants provided by logic written in C#.

**Comment by Eilon** [comment]
Closing because we are not planning to implement this. If this functionality is needed, the recommended alternative is to implement your own `JavaScriptResult` with the desired behavior (it's not much code, and could probably be copied fairly easily from MVC 5.x).
