### ISSUE TITLE
Microsoft.AspNet.Mvc": "6.0.0-* Dependency issue

### ISSUE THREAD

**Issue by stephenstroud** [aspnet/Mvc#2958]
Updated to the latest version, however, the package doesn't resolve due to two missing dependencies. 

    "System.Reflection.Metadata": "1.1.0-alpha-00008",
     Microsoft.CodeAnalysis.CSharp >= 2.0.0-beta1-20150809-02 could not be resolved

These packages aren't on MyGet, where do I get them please?

**Comment by PinpointTownes** [comment]
Make sure to reference the Roslyn/CoreFX MyGet repositories: https://github.com/aspnet/Mvc/blob/dev/NuGet.Config#L6-L7
