### ISSUE TITLE
Strange issue with MVC 6, UTF-8 and Dependency Injection

### ISSUE THREAD

**Issue by BernhardRubow** [aspnet/Mvc#2967]
I have got a strange Problem with strings in an asp.net 5 application, using asp.mvc 6 and the build in dependency injection (this is my conclusion). In a controller I return a custom class created from a class library injected into the controller. To demonstrate the problem, I created a Test Class
 ``` csharp
public class TestContainer
{
    public string Caption { get; set; }
}
```
Then, in a controller, I return a list of these containers; one created in the controller and one created in a class library, which is injected in the controller.

In the controller:
``` csharp
[Route("api/testmethod")]
public List<TestContainer> TestMethod()
{
    var testlocal = new TestContainer()
    { 
        Caption = "aouäöü some name"
    };

    var testdpi = _businessLogic.ReturnTestContainer();

    return new List<TestContainer>() {testlocal, testdpi};
}
```
In the injected libray I use the following method to create the Testcontainer:

``` csharp
public TestContainer ReturnTestContainer()
{
    var test = new TestContainer()
    {
        Caption = "aouäöü some name",
    };

    return test;
}
```
Now the strange thing happens. If I debug the application, it looks as follows:

Images:: 
![local class](https://cloud.githubusercontent.com/assets/5746502/9256799/0a032dc8-41f2-11e5-8f82-0c040d6b7ea4.png)

![class created from injected class](https://cloud.githubusercontent.com/assets/5746502/9256814/2844f690-41f2-11e5-8cf6-063e4ed61d43.png)

For the local generate class, it shows:

aouäöü some name

For the Caption property, but for the class generated by the injected class it shows:

aou��� some name

For the caption property and the output in the browser looks as follows:

[{"Caption":"aouäöü some name"},{"Caption":"aou��� some name"}]

I can´t explain this behavior to myself. Any ideas ?

**Comment by Eilon** [comment]
@pranavkm I'm guessing it's an issue with how we read the CS files from disk for compilation... but who knows...

**Comment by Eilon** [comment]
Or that perhaps the files were saved incorrectly to begin with.

**Comment by pranavkm** [comment]
I see this issue if the file is saved with CodePage-1252 (In VS you can look this up by clicking on File -> Advanced Save Options). We assume UTF8 in DNX https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Compilation.CSharp/RoslynCompiler.cs#L402, but so does Roslyn https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Text/SourceText.cs#L116 and in the absence of a BOM, it parses the file with the effects you see here.

Interestingly compiling this file MsBuild 14.0 (which uses Roslyn under the hoods) gets the right results. My guess is they are probably defaulting to CodePage-1252 although I couldn't figure out where by reflecting over the code.

For the time being, I'd recommend saving the file with UTF8 \ UTF8 with BOM.
I'll port this bug over to DNX so they can follow up on this.

**Comment by BernhardRubow** [comment]
This issue first happened, when I read the string, which is returned, from a SQL Server 2014 Express with Entity Framework 7 Beta. Then I tried to narrow down the Problem.
Would the codepage in which the file is saved still influence the returned string, when this string was read from a Database.

What I didn't tried, was to query the Database directly from inside the Controller.

----- Ursprüngliche Nachricht -----
Von: "Pranav K" <notifications@github.com>
Gesendet: ‎14.‎08.‎2015 21:56
An: "aspnet/Mvc" <Mvc@noreply.github.com>
Cc: "BernhardRubow" <brubow@newvisionsproject.de>
Betreff: Re: [Mvc] Strange issue with MVC 6, UTF-8 and Dependency Injection(#2967)

I see this issue if the file is saved with CodePage-1252 (In VS you can look this up by clicking on File -> Advanced Save Options). We assume UTF8 in DNX https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Compilation.CSharp/RoslynCompiler.cs#L402, but so does Roslyn https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Text/SourceText.cs#L116 and in the absence of a BOM, it parses the file with the effects you see here.
Interestingly compiling this file MsBuild 14.0 (which uses Roslyn under the hoods) gets the right results. My guess is they are probably defaulting to CodePage-1252 although I couldn't figure out where by reflecting over the code.
For the time being, I'd recommend saving the file with UTF8 \ UTF8 with BOM.
I'll port this bug over to DNX so they can follow up on this.
