### ISSUE TITLE
Need support for specifying custom error message for client validation

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Mvc#2969]
Related issue - #2817 
We now have specific error messages for client validation. 
Eg: `The field FieldName must be a number`
There needs to be a way for users to customize the error message that are sent with the `data-val` attributes.

MVC 5 has `GetUserResourceString` for this purpose.
http://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Mvc/ClientDataTypeModelValidatorProvider.cs
```C#
return GetUserResourceString(controllerContext, "FieldMustBeNumeric") ?? MvcResources.ClientDataTypeModelValidatorProvider_FieldMustBeNumeric;
```

Need to have something similar in MVC 6.

cc' @pranavkm @Eilon

**Comment by dougbu** [comment]
@Eilon I could do one message in Beta 8 for #2303 and fill it in for this bug during RC1. Was that the intent in placing this in RC1? If not I'll bring this into Beta 8.

Separately @Eilon and @rynowak do you agree we no longer need the "needs design" label?

**Comment by Eilon** [comment]
I removed the needs design label.

Yeah I was thinking do just the one for beta8, and the rest in RC. If it's somehow completely trivial to do all at once, that's fine with me too.

**Comment by dougbu** [comment]
28aec3f

**Comment by dougbu** [comment]
Reopening. 28aec3f doesn't cover the specific message mentioned above.

**Comment by jln1989** [comment]
@ajaybhargavb @dougbu 

Is customizing the error message available for any one message in Beta8 or else it will be available in RC1 completely? If its available in Beta8 can you tell me what is the specific message and how to use it to override the default message?

**Comment by dougbu** [comment]
@jln1989 customizing error messages is currently available only for a few messages. This issue remains Open because we have not done the work for client-side validation messages.

Have a look at the `Microsoft.AspNet.Mvc.ModelBinding.Metadata.IModelBindingMessageProvider` interface for the few customizations currently available. The easiest way to make changes is e.g.
``` c#
    public void ConfigureServices(IServiceCollection services)
    {
        // Add MVC services to the services container
        services.AddMvc(mvcOptions =>
        {
            mvcOptions.ModelBindingMessageProvider.MissingBindRequiredValueAccessor =
                name => $"A value for the '{ name }' property was not provided.";
        });
    }
```

Of course resources or `IStringLocalizer` implementations may be better in your scenario.

**Comment by dougbu** [comment]
Reassigning to myself since we want this to happen before @kichalla gets back.

**Comment by dougbu** [comment]
@rynowak fixing this will look a lot different once your #3962 PR is in. So I'm taking it out of Working and waiting.

**Comment by dougbu** [comment]
26a14a2
