### ISSUE TITLE
Allow to override the ViewPathFormat in ViewViewComponentsResults

### ISSUE THREAD

**Issue by pmdevers** [aspnet/Mvc#2975]
Please allow changing the ViewPathFormat.

**Comment by rynowak** [comment]
Can you give us more detail about what you're trying to accomplish?

**Comment by pmdevers** [comment]
In mvc5 ik have als controller like LoginController 

In my lay-out I have @Html.Action ("login","login") this will render a partial login view which contains a login form with Ajax postback. So when the user signs in it post it's data to the login controller. And returns a partial view.

I think you know what I mean.

In vnext html.action is replaced with view components however I can figure out how to achieve this.

So I tried a view components to point to the login view to render te login form. Then I noticed that the view components always adds components to the view location

**Comment by danroth27** [comment]
You can fully qualify the view path by prefixing the path with `~/`. Does that meet your needs?

**Comment by danroth27** [comment]
Closing for now, but let us know if the current behavior is insufficient.
