### ISSUE TITLE
asp-append-version not working on Linux

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Mvc#2979]
In my _Layout.cshtml:
```
<link rel="stylesheet" href="~/cache/main.min.css" asp-append-version="true"/>
```

On my development machine (Windows 7, Visual Studio 2015, Kestrel), this correctly appends the version:
```
<link rel="stylesheet" href="/cache/main.min.css?v=GQLFOo4-np2RJQauQG_3iKMNbSjDM5osk_tVLhNAnhE" />
```

However, in my production environment (Mono 4.0.2, Kestrel), no version is appended:
```
<link rel="stylesheet" href="/cache/main.min.css" />
```

Tested on Mono 4.0.2 and ASP.NET 5 Beta 6.

I'm deploying the site by doing `dnu publish` into a temporary directory, then `rsync`ing that temporary directory to the remote server.

**Comment by Daniel15** [comment]
The problematic section of code is this part in `FileVersionProvider.cs`:
```
            Uri uri;
            if (Uri.TryCreate(resolvedPath, UriKind.Absolute, out uri))
            {
				// Don't append version if the path is absolute.
				return path;
            }
```

Mono's implementation of `Uri.TryCreate` is resolving `/foo.css` to `file:///foo.css`, because technically `/foo.css` **is** an absolute path to a file on Linux. Thus, it's just returning `path` unmodified. :sob: 

I think it should either explicitly be checking `IsFile` on the Uri. I'll submit a patch.

**Comment by danroth27** [comment]
@NTaylorMullen @ajaybhargavb 

Yup, looks like something we would love to get a PR for. Thanks for finding the issue!

**Comment by Daniel15** [comment]
I already submitted pull request #2980 to fix this issue :)

**Comment by dougbu** [comment]
a2e53e8
