### ISSUE TITLE
Multiple parameters?

### ISSUE THREAD

**Issue by aliveli186** [aspnet/Mvc#2981]
Is it possible to post by multiple parameters or we have to still create transport objects?

[HttpPost]
public string PostMultipleSimpleValues(string name, int age, DateTime entered, string action = null)
{
    return string.Format("Name: {0}, Age: {1}, Date: {2}, Action: {3}", name, age, entered, action);
}

**Comment by dougbu** [comment]
It's certainly possible to bind multiple parameters to portions of a form submission. Are you seeing a problem?

**Comment by aliveli186** [comment]
Posting with url encoding works but posting json doesn't map to parameters.

---
Content-Type: application/x-www-form-urlencoded
name=john&age=21

This one works.
---
Content-Type: application/json; charset=utf-8
{
  "name": "john",
  "age": 21
}
This one doesn't work.
---

**Comment by dougbu** [comment]
@aliveli186 a JSON request body is a single serialized object and must be mapped to a single action parameter. So this behaviour is by design. In your case, the following would work.
``` c#
[HttpPost]
public string PostMultipleSimpleValues([FromBody] User user)
{
    // ...
}

public class User
{
   public string Name { get; set; }
   public int Age { get; set; }
   public DateTime Entered { get; set; }
   public string Action { get; set; }
}
```

**Comment by aliveli186** [comment]
Thank you.
I came from WCF background, there this was not an issue.

**Comment by NeelBhatt** [comment]
yes [FromBody] certainly works!
