### ISSUE TITLE
Please post breaking changes to aspnet/Announcements channel

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Mvc#2982]
Hello,
The breaking change from 'asp-file-version' to 'asp-append-version' during beta6 was not announced via Asp.Net announcements channel:
https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-beta6
https://github.com/aspnet/Mvc/issues/2540
https://github.com/aspnet/Mvc/commit/3fe0490b9949520b7c803a54320baf810c4736cf

I'm subscribed to Announcements channel to catch some changes that should be reflected for example in `generator-aspnet`.

I think this specific change can be still added to Announcements channel.

https://github.com/aspnet/Mvc/issues/2540#issuecomment-127112284
/cc @Daniel15

Thanks!

**Comment by danroth27** [comment]
We should add the announcement for this change.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Announcements/issues/56

**Comment by peterblazejewicz** [comment]
Thanks!
