### ISSUE TITLE
'Found a malformed 'link' tag helper' error when using link tag and asp-* attribute

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Mvc#2983]
As soon as I add the `asp-*` attribute to link tag **without** trailing slash the application crashes.
```cshtml
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true">
```
```
error   : [Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: One or more compilation failures occured:
/Views/Shared/_Layout.cshtml (55,6) Found a malformed 'link' tag helper. Tag helpers must have a start and end tag or be self closing.
...
```
https://gist.github.com/peterblazejewicz/941cbd70f82920265af8

But if I add trailing slash (like in XHTML doctype):
```cshtml
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
```
the error does not occur.  
Under HTML5 the trailing slash in `link` tag is just optional:
https://developer.mozilla.org/en/docs/Web/HTML/Element/link
http://www.w3.org/TR/html5/document-metadata.html#the-link-element

Can somehow Razor parser be more relaxed?
Thanks!

OSX/beta6:
```
dnu build
Microsoft .NET Development Utility Mono-x64-1.0.0-beta6-12256
```

**Comment by NTaylorMullen** [comment]
This has been fixed via: https://github.com/aspnet/Mvc/pull/2956. In the next release you wont have this issue :smile:

**Comment by peterblazejewicz** [comment]
@NTaylorMullen Thanks a lot! I was not able to locate the proper PR/commit via search (maybe due to different search keywords).
:+1:
