### ISSUE TITLE
`DefaultModelMetadata.PropertyGetter` is not `null`-safe

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2986]
No current MVC code uses `DefaultModelMetadata.PropertyGetter`. If it were used, would find `null` values e.g. `ModelMetadata.PropertyGetter(null)` lead to NREs. Root cause may be the fact `PropertyHelper.MakeNullSafeFastPropertyGetter()` is not referenced.

Experienced this issue while developing PR #2984.

**Comment by rynowak** [comment]
b5c9d905d924c04077aba6ef870cfb7e72ed5448
