### ISSUE TITLE
Unable to disable Url Resolution logic from _ViewImports.cshtml.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2989]
If a user wants to disable URL resolution (~/) they can do:

```
@removeTagHelper "*, Microsoft.AspNet.Mvc.Razor"
```

If done on a single page, everything works well. However, you're unable to add this `@removeTagHelper` in a `_ViewImports.cstml` to get the same effect.

**Comment by danroth27** [comment]
@DamianEdwards 

Why doesn't this work and what is the fix?

**Comment by NTaylorMullen** [comment]
It doesn't work due to the order in which we apply `InheritedChunks` vs `DefaultInheritedChunks` within the `MvcRazorHost`/`ChunkInheritanceUtility`. 

There's a default `@addTagHelper "*, Microsoft.AspNet.Mvc.Razor"` applied to every page; if a user does the corresponding `@removeTagHelper` in a `_ViewImport.cshtml` the `@removeTagHelper` is run before the `@addTagHelper` due to the order of our chunk merging. Therefore, nothing gets removed.

**Comment by DamianEdwards** [comment]
How do we fix it?

**Comment by NTaylorMullen** [comment]
@DamianEdwards Change the order in which we apply default chunks and inherited chunks. It's a relatively easy change.

**Comment by DamianEdwards** [comment]
Ok cool. Let's fix it in beta8

**Comment by pranavkm** [comment]
Fixed in f045c6792b7d62697cd748d45fe38205b1aab136
