### ISSUE TITLE
Hoist uses of `Nullable.GetUnderlyingType()` into `ModelMetadata`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2992]
MVC code contains too many instances of low-level code duplicating
``` c#
!type.GetTypeInfo().IsValueType || Nullable.GetUnderlyingType(type) != null
```
and even more duplicates of
``` c#
Nullable.GetUnderlyingType(type) ?? type
```

The first could be exposed as `ModelMetadata.AllowsNullValue`. Alternatively could provide `ModelMetadata.IsValueType` in addition to the existing `ModelMetadata.IsNullableValueType`, allowing the above to be elevated to
``` c#
!metadata.IsValueType || metadata.IsNullableValueType
```

The second could be exposed as `ModelMetadata.UnderlyingType`.

**Comment by rynowak** [comment]
This, is code cleanup, just do it IMO :+1:

**Comment by dougbu** [comment]
Yeah, don't disagree. Self-assigning this "task".

**Comment by dougbu** [comment]
Decided to add
- `IsReferenceOrNullableType`, just to avoid a `bool` property that isn't named `IsFoo`
- `UnderlyingOrModelType`

**Comment by dougbu** [comment]
bf7e0f1
