### ISSUE TITLE
Collections with different type parameters than expected interface do not bind correctly

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#2993]
The `GenericModelBinder` does not support properties that have a different number of type parameters than the expected interfaces. This occurs whether or not the property type implements that interface.

For example properties of types like the following cannot currently be bound as collections:
``` c#
public class ClosedGenericDictionary : Dictionary<string, string>
{
    // ...
}

public class ClosedGenericList : List<string>
{
    // ...
}

public class ClosedGenericKeyDictionary<TValue> : Dictionary<int, TValue>
{
    // ...
}
```

This is a follow-on issue for #2793. That was about custom collections. This extends the notion of "custom" to the exposed type parameters.

Note a fix for this issue will likely also handle oddball cases such as
``` c#
public class OddballOpenGenericList<int> : List<string>
{
    // ...
}
```

**Comment by danroth27** [comment]
@dougbu Is this a regression from MVC 5?

**Comment by dougbu** [comment]
@danroth27 will test...

**Comment by dougbu** [comment]
@danroth27 yes, this is a regression from MVC 5.

**Comment by dougbu** [comment]
829a5c9
