### ISSUE TITLE
How to register a Model that isn't in the Models folder?

### ISSUE THREAD

**Issue by Fosol** [aspnet/Mvc#2995]
Presently if you attempt to return an object of a Type that doesn't reside in the Model folder serialization fails.  It doesn't throw an error, it still returns a status code of 200, but the response body is empty.

1) How do you register a model that doesn't reside in the Models folder?
2) An exception should occur if serialization fails.

**Comment by Fosol** [comment]
Looks like you need to inform DI of the model if you want it to be serialized.  Not too shabby.

Still should throw an exception however.

**Comment by rynowak** [comment]
Can you provide a code sample of what you're trying to accomplish? 

There's nothing special about the Models folder, that's just a suggested organization of code. 

There's also no requirement that a model type be registered with DI.

**Comment by Fosol** [comment]
I'll post an example tomorrow.

It boils down to creating libraries that contain shared Models.  Those types failed to be returned by the MVC framework.

If I place code file for the type in the Models folder it works.  If I place the code file in a shared library it fails.

To fix it I needed to register the shared type in DI.

**Comment by Fosol** [comment]
Well this morning I ran my same application (no code changes since yesterday).  It now works without having to register the shared type in DI.

I'm starting to think NuGet local caching is causing me the most issues.  Half the time I have to close VS just so that I can delete the .dnx cached packages...

I'll close this ticket as now I can't replicate the issue.

**Comment by NeelBhatt** [comment]
I guess you can disable Nuget Restore if you do not need it @Fosol

**Comment by Fosol** [comment]
disabling NuGet Restore appears to be rather difficult.  I don't want to jump through hoops.  I also don't want to have to check in changes to my project file that affect all other team members.

I just want a purge cache of the packages relevant to my current project.

**Comment by rynowak** [comment]
DNX will cache packages at `%UserProfile%/DNX/packages` - but what you probably want to try first is to delete the `project.lock.json` file for the project and re-run restore.

**Comment by Fosol** [comment]
deleting project.lock.json and running the restore doesn't remove the local cached packages.

The issue I'm having is related to quick changes to shared projects that don't have their version number changed every time I make a minor tweak (to test something).  Essentially restore looks at the local cached version and refuses to update it with a new version on a local NuGet Package share (because the version number hasn't changed).

Pity there isn't a button - Clear Cache & Restore.  This would clear the local cache of ONLY dependencies within the current project/solution.

**Comment by rynowak** [comment]
So, this is a package that you own correct?  @danroth27 may have some ideas.

**Comment by danroth27** [comment]
Would it be easier to reference the project directly instead of referencing the shared project as a package? From within Visual Studio you can Add Reference to both DNX based projects and existing csproj based projects.

**Comment by Fosol** [comment]
As far as I can tell the project.json file doesn't look any different whether they're pulled in as a NuGet Package or a shared project.

I'm only pulling in the projects for debugging purposes.  I want them as NuGet Packages when I check them in.

All packages are owned by me.
