### ISSUE TITLE
aspnet project not responding in VS 2015

### ISSUE THREAD

**Issue by varghesep** [aspnet/Mvc#2997]
There is a serious performance problem with **asp.net mvc 6** project running inside **VS 2015**. 

To reproduce, keep the **aspnet mvc 6** project open in the VS 2015. Then run a javascript package manager in the command line in the project folder. For example, I ran **jspm install react**. Then switch back to the VS 2015 from the command line, and you will see NOT RESPONDING message in the title of the VS 2015. It took at least 30 minutes or so for the VS 2015 to release the UI.

I assume VS 2015 was adding all the files from the **jspm_packages** folder to the project. This operation is required to add the files to the project. But I don't know why it should that long. I also experience VS 2015 not responding when browsing files in the solution folder.

My configuration:

![image](https://cloud.githubusercontent.com/assets/12233474/9346916/2a3fe046-45e8-11e5-9809-bf206c7e4c52.png)

Resharper is active

**Comment by danroth27** [comment]
Moved to https://github.com/aspnet/Tooling/issues/152
