### ISSUE TITLE
Discussion: Image, Script and Link TagHelper's asp-file-version renamed to asp-append-version.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#3002]
## ScriptTagHelper

Old: `<script asp-file-version="true" src="..."></script>`
New: `<script asp-append-version="true" src="..."></script>`
## LinkTagHelper

Old: `<link asp-file-version="true" href="..." />`
New: `<link asp-append-version="true" href="..." />`
## ImageTagHelper

Old: `<img asp-file-version="true" src="..." />`
New: `<link asp-append-version="true" src="..." />`

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
