### ISSUE TITLE
What is the equivalent taghelper to @Html.DisplayNameFor(model => model.derp)? 

### ISSUE THREAD

**Issue by heathyates** [aspnet/Mvc#3003]
The only thing I have found is `<label asp-for=""></label>`. I have seen no example. Thanks.

**Comment by dougbu** [comment]
@heathyates the in-box tag helpers generally map 1:1 to generated HTML elements. MVC includes a few which generate two or more elements, but none that output only text. This matches the element-like syntax for tag helpers.

What is insufficient or incorrect about using `@Html.DisplayNameFor()` in your scenario?

**Comment by heathyates** [comment]
@dougbu Please keep this issue open. I'll work on a demo that will show the issue I am experiencing. Please give me a couple of days to update.

**Comment by Woolear** [comment]
<label asp-for=""></label> not working with IEnumerable<Type> Models, @Html.DisplayNameFor() - does.

**Comment by heathyates** [comment]
@Woolear It doesn't work when I used the taghelper in a for loop. I'm playing around with jsrenderer as a potential workaround. Nothing substantial yet though.

**Comment by Woolear** [comment]
@heathyates the same :) MissingMethodException when i use this code:
`     @foreach (var contract in Model)
        {
            <tr>
                <td><label asp-for="@contract.Number"></label></td>`
if i write ` <td><label asp-for="Number"></label></td>` it fails, because of IEnumerable<> model...

**Comment by dougbu** [comment]
@heathyates and @Woolear sounds like this discussion covers two overlapping concerns. If you agree please split one out into another issue and make it clear which this is about.

1. Have no in-box tag helpers for some HTML helpers, especially ones that do templating e.g. `@Html.DisplayFor()` or return non-tag values e.g. `@Html.DisplayNameFor()`. As I implied earlier this is by design but we're very interested in @heathyates scenario.
2. The `<label/>` tag helper and the `@Html.LabelFor()` HTML helper do not support the `IEnumerable<TModelItem>` special case we have for `@Html.DisplayNameFor()`. They require @Woolear's workaround for headers in a `.cshtml` file with an `IEnumerable` `@model`. That is, no other method has a declaration like:
``` c#
public static string DisplayNameFor<TModelItem, TResult>(
    [NotNull] this IHtmlHelper<IEnumerable<TModelItem>> htmlHelper,
    [NotNull] Expression<Func<TModelItem, TResult>> expression)
```

**Comment by Woolear** [comment]
@dougbu i think? the main question is: why `@foreach (var contract in Model) { <tr> <td><label asp-for="@contract.Number"></label></td>` or `<label asp-for="[EXPRESSION]"></label>` fails with MissingMethodException. Maybe this helper intended to use with global model properties expressions? like ` <label asp-for="PropertyOf@Model"></label>`

**Comment by danroth27** [comment]
@dougbu Why do we get a MissingMethodException in this case?

**Comment by dougbu** [comment]
I'm unable to reproduce the `MissingMethodException` with current bits but may be missing something. @Woolear do you have a small repro?

Separately the following approach can be used to create labels with an enumerable model:
``` html
<label asp-for="Numbers[0].Id"></label>
```

**Comment by danroth27** [comment]
We think DisplayNameFor is sufficient for this scenario, but let us know if there is still an issue here and we can revisit.

**Comment by Woolear** [comment]
@dougbu, i used `<label asp-for="Numbers.First().Id"></label>` and `<label asp-for="@number.Id"></label>`, where `@number` is foreach variable

**Comment by Woolear** [comment]
@danroth27, i thought that `asp-blabla` must replace `@Html.[blabla]`, Am i wrong?

**Comment by danroth27** [comment]
Not in general. Tag Helpers are for tags, not arbitrary content. The problem with using HTML Helpers for tags is that you can't use normal HTML editing to customize the HTML helper output. But for content HTML Helpers should be fine.

**Comment by rsheptolut** [comment]
@danroth27, thanks. But why then can we use <label asp-for="FieldName" /> (in case of a plain viewmodel)? It generates content, but this same code can't be used in IEnumerable<ViewModel> scenario. So your argument "Tag Helpers are for tags" doesn't really stand, IMHO.

**Comment by John0King** [comment]
@dougbu    How are about this: 
Microsoft.AspNet.Mvc.ViewFeatures\Rendering\HtmlHelperDisplayNameExtensions.cs
`public static string DisplayNameFor<TModel, TModelItem, TResult>(
            this IHtmlHelper<TModel> htmlHelper,
            Expression<Func<TModelItem, TResult>> expression
            ) where TModel : IEnumerable<TModelItem>`
@ model  List<News>
@ Html.DisplayNameFor( (News m) => m.Title )

**Comment by dougbu** [comment]
@John0King the current `DisplayNameFor()` signature extends the `IHtmlHelper<List<News>>` in your page and helps the compiler determine `TModelItem`. Casting to another model type on the LHS of the lambda doesn't give the compiler anything to call.

This issue has been closed for a few months now. If there is a problem with the current `DisplayNameFor()` overloads, please open a new issue.

**Comment by alishamsi-p** [comment]
try below code

public class movie
{
       public int ID { get; set; }
        [DisplayName("Movie Title")]
        public string Title { get; set; }
}
///////////////////////////////////////////////////

@model IEnumerable<MvcMovie.Models.Movie>
@{
   // MvcMovie.Models.Movie _movie=Model[0];
}
<h1>Show List Movies</h1>
< label asp-for="ToList()[0].Title">< /label>


@foreach (var movie in Model)
{

    <p>@movie.Title</p>
    
}
