### ISSUE TITLE
CreatedAtActionResult overload with route name

### ISSUE THREAD

**Issue by fabiomaulo** [aspnet/Mvc#3008]
An overload of CreatedAtActionResult ctor accepting the route name is needed in many cases.
To make it even more flexible, perhaps, would be useful an overload accepting an Uri.
Thanks.

**Comment by rynowak** [comment]
`CreatedAtRoute(...)` lets you pass a route name - if you need to pass an action/controller as well, you can do this through the anonymous object. 

And `Created(...)` lets you pass a URL.

**Comment by fabiomaulo** [comment]
hmmm..  IMO is reasonable the presence of 3 implementations (3 classes) with different names but not so the 3 methods with names simply reflecting classes names. Would be much more simple to found every option using just one method name:
CreatedAt(string action, string controller, object routeValues, object value)
CreatedAt(string routeName, object routeValues, object value)
CreatedAt(string routeName, object routeValues, object value)
CreatedAt(Uri uri, object value)

What you think ?

**Comment by danroth27** [comment]
We'd rather keep the different method names different to avoid the potential for future overload conflicts.
