### ISSUE TITLE
Disable response buffering in places where the content is already built/available.

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#3016]
We should check for the presence of `IHttpBufferingFeature` on the context and if present should disable response buffering at least in the following cases:

- https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/FileStreamResult.cs#L77
- https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/StreamOutputFormatter.cs#L43
- https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ContentResult.cs#L70
- https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/FileContentResult.cs#L69

@Tratcher @rynowak

**Comment by rynowak** [comment]
What does this accomplish? Perf?

**Comment by kichalla** [comment]
Discussed offline and the scenario is that with the availability of [response buffering middleware](https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNet.Buffering/ResponseBufferingMiddleware.cs#L11), if a user adds this to their application to enable some scenarios(example: they want to sent a nicer error message when serializing data and exception happens as opposed to sending back partial data), then this might cause issues in other scenarios for example, where user is streaming a file from Sql server etc.
