### ISSUE TITLE
MvcOptions.InputFormatters doesn't work on asp.net vnext

### ISSUE THREAD

**Issue by loudadyassine** [aspnet/Mvc#3018]
My application stopped working after migrating to beta 6/7, after investigating, I have found that my json deserializer is no more used ( Jil ), it's called for writing but not for reading.

It has been now 3 days that I'm searching forums and reading aspnet code but I haven't found the issue.

I noticed that JSON.net is used everywhere in beta 6, a little bit less in beta 7.

Here is my code :
```
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvcCore(options =>
        {
            var jilFormatter = new JilMediaTypeFormatter();
            options.OutputFormatters.Clear();
            options.OutputFormatters.Add(jilFormatter);
            options.InputFormatters.Clear();
            options.InputFormatters.Add(jilFormatter);

            options.FormatterMappings.SetMediaTypeMappingForFormat("json", MediaTypeHeaderValue.Parse("application/json"));

            options.ModelBinders.Add(new DocumentModelBinder());
            options.ModelBinders.Add(new DataTablesBinder());
        });
        services.AddDataProtection();
        services.AddWebEncoders();

    }
```
Even if I do just InputFormatters.Clear() without adding an object, it keeps deserializing the requests, I have no idea how it does it.

And my JIL InputFormatter/OutputFormatter ( the ouputformatter works, I can break in the CanWrite, but nothing happens for CanRead )

```
internal class JilMediaTypeFormatter : IOutputFormatter, IInputFormatter
{
    private static readonly string [] _readableTypes = new[] { "application/json", "text/json", "text/javascript" };
    private static readonly Task<bool> _done = Task.FromResult(true);

    private readonly Options _options = Options.RFC1123ExcludeNullsIncludeInherited;


    public bool CanWriteResult(OutputFormatterContext context, Microsoft.Net.Http.Headers.MediaTypeHeaderValue contentType)
    {
        return contentType ==null || _readableTypes.Contains(contentType.MediaType.ToLowerInvariant());
    }

    public Task WriteAsync(OutputFormatterContext context)
    {
        context.HttpContext.Response.ContentType = "application/json";
        using (var writer = new StreamWriter(context.HttpContext.Response.Body))
        {
            JSON.Serialize(context.Object, writer, _options);
            writer.Flush();
            return _done;
        }
    }

    public bool CanRead(InputFormatterContext context)
    {
        return _readableTypes.Contains(context.HttpContext.Request.ContentType);
    }

    public Task<object> ReadAsync(InputFormatterContext context)
    {
        var reader = new StreamReader(context.HttpContext.Request.Body);
        var result = JSON.Deserialize(reader, context.ModelType, _options);
        return Task.FromResult(result);
    }
}
```

**Comment by rynowak** [comment]
> Even if I do just InputFormatters.Clear() without adding an object, it keeps deserializing the requests, I have no idea how it does it.

Can you give a sample of your action code? Are you using `[FromBody]` in the parameter list? Formatters only apply where `[FromBody]` is used.

**Comment by loudadyassine** [comment]
Thank you very much for putting this clear, with [FromBody] it does work, but I have many controllers with many actions ( > 30 actions ), Is there any way to consider that the biding should be by default from the request body ?

**Comment by rynowak** [comment]
ApplicationModel to the rescue :sunglasses: 

You could do something like this:

```
public class FromBodyConvention : IActionModelConvention
{
    public void Apply(ActionModel action)
    {
        foreach (var parameter in action.Parameters)
        {
            if (parameter.BindingInfo.BindingSource == null)
            {
                parameter.BindingInfo.BindingSource = BindingSource.Body;
            }
        }
    }
}

options.Conventions.Add(new FromBodyConvention);
```

This will set any parameter to `[FromBody]` by default, but still allow you to override if in places if you need to by using the other attributes.

**Comment by loudadyassine** [comment]
Many thanks sir.

**Comment by tugberkugurlu** [comment]
@rynowak regarding this: https://github.com/aspnet/Mvc/issues/3018#issuecomment-133578900 wouldn't it make sense for complex type objects to bind from body by default as it's being done in Web API today?

**Comment by rynowak** [comment]
No, not at all. This breaks MVC's scenarios

**Comment by tugberkugurlu** [comment]
@rynowak Is it possible to elaborate on what are those scenarios are for MVC? I have created the following model convention to sort of mimic the Web API behaviour:

```csharp
    public class ComplexTypeConvention : IActionModelConvention
    {
        public void Apply(ActionModel action)
        {
            foreach (var parameter in action.Parameters)
            {
                var paramType = parameter.ParameterInfo.ParameterType;
                if (parameter.BindingInfo == null && (IsSimpleType(paramType) || IsSimpleUnderlyingType(paramType)) == false)
                {
                    parameter.BindingInfo = new BindingInfo()
                    {
                        BindingSource = BindingSource.Body
                    };
                }
            }
        }

        private static bool IsSimpleType(Type type)
        {
            return type.IsPrimitive ||
                   type.Equals(typeof(string)) ||
                   type.Equals(typeof(DateTime)) ||
                   type.Equals(typeof(Decimal)) ||
                   type.Equals(typeof(Guid)) ||
                   type.Equals(typeof(DateTimeOffset)) ||
                   type.Equals(typeof(TimeSpan));
        }

        private static bool IsSimpleUnderlyingType(Type type)
        {
            Type underlyingType = Nullable.GetUnderlyingType(type);
            if (underlyingType != null)
            {
                type = underlyingType;
            }

            return IsSimpleType(type);
        }
    }
```

Would this cause problems in an MVC 6 application where I have both form and JSON data being posted?

**Comment by dougbu** [comment]
This approach would cause problems for any slightly-complicated form and model binding the submitted data. Forms do not always submit just one simple value.

**Comment by rynowak** [comment]
@tugberkugurlu - MVC pushes you to **mix data from different data sources (route, form, query) in a single DTO**. It's the most common usage of model binding. It's hard to elaborate more, because almost any usage of model binding of MVC will do this.
