### ISSUE TITLE
Add extension methods for adding a parameter model convention 

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3020]
We have sugar for registering a controller model convention or action model convention in options. We should do the same for bound-properties and parameters.

See example here: https://github.com/aspnet/Mvc/issues/3018#issuecomment-133576948

**Comment by pranavkm** [comment]
Fixed via https://github.com/aspnet/Mvc/pull/5640, https://github.com/aspnet/Mvc/commit/dbff416be60ad6accccb4afa33785e7db660152e
