### ISSUE TITLE
Refactor IRazorPage to write output to a IHtmlContent instead of TextWriter

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3030]
The interface contract for a `IRazorPage` \ `RazorPage` is to write to the `TextWriter` instance exposed via `ViewContext.Writer`. In the default case (i.e. the user isn't using a custom `IRazorView`), `ViewContext.Writer` is an instance of `RazorTextWriter` which essentially has the same sort of contract \ behavior as `IHtmlContent`.

We could instead change `IRazorPage` to expose its results as an `IHtmlContent` instead. This change would allow us

a) We can follow the same append pattern we get with appending one `IHtmlContent` to another used through the remainder of the application.

b) Remove the contract that we give special treatment to `TextWriter` instances that implement `IBufferedTextWriter`. Also remove `IBufferedTextWriter`.

Related discussion: Since page instrumentation \ BrowserLink will be affected by this interface change, we can follow up with @jodavis to figure out if they can rely on EventNotification instead our current interface based contract.

**Comment by dougbu** [comment]
`IHtmlContent` isn't a contract used when writing out content. Adapters such as `IBufferedTextWriter` and `TagHelperOutput` support those capabilities. This bug seems to be about how the final content is copied into the next-higher scope. For example could have `RazorTextWriter` also implement `IHtmlContent` or use `RazorTextWriter.BufferedWriter` directly in `RazorPage` (with a few special cases when `RazorTextWriter.Flush[Async]()` is called).

**Comment by pranavkm** [comment]
`RazorPage` does not write out content - the view does. Its behavior is identical to any other component in the Razor rendering pipeline.

**Comment by Eilon** [comment]
@pranavkm can you sync with @rynowak and @dougbu to see what this might look like?

**Comment by rynowak** [comment]
Per discussion with @jodavis and @pranavkm no one depends on the `IBufferedTextWriter` interface. We should remove it as part of the migration to make browserlink use `DiagnosticSource`. I'm not sure what else in this bug is still relevant without talking to @pranavkm

**Comment by pranavkm** [comment]
This depends on https://github.com/aspnet/Mvc/issues/3281.

**Comment by pranavkm** [comment]
The primary issue with this change is that we have to continue exposing the notion of a buffering `TextWriter` on `ViewContext.Output` for things like `@Html.BeginForm` that directly write to the response. The end result looks like a half measure. We'll revive this in case there's a specific need for the refactor, but there's not a lot of utility with this change.
