### ISSUE TITLE
Discussion: HTML5 defined elements with URL accepting attributes are now TagHelpers.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#3036]
## What's the Problem?

Classic Razor would resolve the value of **any** HTML attribute that started with `~/` as an application relative URL. This led to some invalid scenarios where users would provide attribute values such as `~/folder/file.txt` and get inaccurate URL resolutions. In addition, this feature couldn't be easily disabled.
## The Fix

There were multiple locations for a valid fix; we decided that it didn't make sense to hard code the list of HTML5 defined element/attribute combos in the core Razor parser. In addition, the introduction of `TagHelper`s led to some users expecting to see the raw value of their attribute values instead of the intercepted value.

Therefore, we decided to create the [UrlResolutionTagHelper](https://github.com/aspnet/Mvc/blob/f116b91750ee52ab54f39db5390d72037d26c524/src/Microsoft.AspNet.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs) to take over `~/` resolution.

It targets the following attribute/element combos:
- href : `<a>`, `<area>`, `<link>`, `<base>`
- src : `<audio>`, `<embed>`, `<iframe>`, `<img>`, `<input>`, `<script>`, `<source>`, `<track>`, `<video>`
- action : `<form>`
- cite : `<blockquote>`, `<del>`, `<ins>`, `<q>`
- data : `<object>`
- formaction : `<button>`, `<input>`
- icon : `<menuitem>`
- itemid : everything
- manifest : `<html>`
- poster : `<video>`
- srcset : `<img>`, `<source>`
- archive : `<object>`, `<applet>`
## Side effects

Any element that the `UrlResolutionTagHelper` targets now have runtime `TagHelper` restrictions applied to them. Some of these restrictions are:
- Depending on the targets `TagStructure` a tag targeted by the `UrlResolutionTagHelper` may result in an error based on supported syntax. 
  - `TagStructure.WithoutEndTag` = `<tag>` OR `<tag />`
  - `TagStructure.NormalOrSelfClosing` = `<tag></tag>` OR `<tag />`
  - `TagStructure.Unspecified` = Usually same behavior as `TagStructure.NormalOrSelfClosing` unless another `TagHelper` defines a different `TagStructure`.
- C# must not exist in the declaration area of the tag.
  - Invalid: `<a href="..." @myClass>...</a>`
  - Valid: `<a href="..." class=@myClass>...</a>`
- `TagHelper`s that bind URL based attribute values must now resolve them manually.
  - Can be done by taking in the `IUrlHelper` in the constructor (from DI) and calling `IUrlHelper.Content` on the value.

**Note:** These restrictions do not show up during design time due to the [editor browsable attribute](https://github.com/aspnet/Mvc/blob/f116b91750ee52ab54f39db5390d72037d26c524/src/Microsoft.AspNet.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs#L49) on `UrlResolutionTagHelper`. Reason  behind this decision was that the majority of users will never encounter any of these restrictions and the `TagHelper` tooling would be misleading.
## Workarounds

**Disable URL resolution on the page:**  
By default every page essentially has an:
 `@addTagHelper "Microsoft.AspNet.Mvc.Razor.TagHelpers.UrlResolutionTagHelper, Microsoft.AspNet.Mvc.Razor"`

Therefore, to disable `~/` URL resolution for an entire page you can do:
`@removeTagHelper "Microsoft.AspNet.Mvc.Razor.TagHelpers.UrlResolutionTagHelper, Microsoft.AspNet.Mvc.Razor"`
This can be done on the page and there's an [issue](https://github.com/aspnet/Mvc/issues/2989) tracking the ability to do this in `_ViewImports.cshtml`.

**Disable URL resolution on an element:**  
You can also disable the URL resolution capability on a per-element basis via the `TagHelper` opt-out character `!`: `<!href href="~/..." @myAttribute>...</a>`

**Comment by michaldudak** [comment]
Can we somehow force it to resolve URLs on other elements/attributes? I'm thinking about angular's `ng-src` and `ng-href` right now, but I'm sure there will be more places where it will be necessary.

**Comment by dougbu** [comment]
@michaldudak you could use one of the workarounds @NTaylorMullen listed in an HTML or tag helper:
> ... taking in the `IUrlHelper` in the constructor (from DI) and calling `IUrlHelper.Content` on the value.

Or you could use the `IUrlHelper` directly in your view e.g. `<a ng-href="@Url.Content("~/...")">text</a>`.

**Comment by michaldudak** [comment]
Don't you think it may be confusing for developers to see that ~ behaves differently depending on the attribute it's used in? I personally would like it on by default with a possibility tu turn it off (or to escape the ~ character). This would be more consistent, I guess.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
