### ISSUE TITLE
ControllersAsServices.AddControllersAsServices() static method - not an extension method

### ISSUE THREAD

**Issue by BillKrat** [aspnet/Mvc#3040]
I suspect this should be an extension method?

![addcontrollersasservices](https://cloud.githubusercontent.com/assets/10552946/9492811/99ce0a5e-4bc0-11e5-9fd9-4ca7d5a0d983.png)

**Comment by rynowak** [comment]
The extension methods for this are now defined off of `IMvcBuilder` and `IMvcCoreBuilder` - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/DependencyInjection/MvcCoreMvcBuilderExtensions.cs#L34

You can use them like:
```
services.AddMvc().AddControllersAsServices(...);
```

or if you'd prefer:
```
var mvc = services.AddMvc();
mvc.AddControllersAsServices(...);
```
