### ISSUE TITLE
int/unsigned values do not have consistent client side validation for values containing dots.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#3041]
If a user binds an `int` or `uint` value they're unable to type any non-numerical characters in the field due to the way `<input type="number"...` works in the browser. However, they can type `1.23` without any client side validation. It does however get validated on the server.

Example:
Add following to the model: `public int Age { get; set; }`
Add the following to a cshtml form (with `TagHelper`s): 

``` HTML
<input asp-for="Age" class="form-control" />
<span asp-validation-for="Age" class="text-danger"></span>
```
1. Type in `1.23`. (No error occurs in browser)
2. Hit submit. (Errors are shown from validation on the server).

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
