### ISSUE TITLE
unsigned ints have no client side validation for negative numbers.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#3042]
If a user binds a `uint` value they're unable to type any non-numerical characters in the field due to the way `<input type="number"...` works in the browser. However, they can type `-1` without any client side validation. It does however get validated on the server.

Example:
Add following to the model: `public uint Age { get; set; }`
Add the following to a cshtml form (with `TagHelper`s): 

``` HTML
<input asp-for="Age" class="form-control" />
<span asp-validation-for="Age" class="text-danger"></span>
```
1. Type in `-1`. (No error occurs in browser)
2. Hit submit. (Errors are shown from validation on the server).

**Comment by Eilon** [comment]
Closing because we are not planning to implement this.

**Comment by dougbu** [comment]
FYI, users can do this explicitly with `[Range(0, (int)uint.MaxValue)]` on the property if they wish.
