### ISSUE TITLE
UrlResolutionTagHelper should have an option to not throw if custom UrlHelper appends to url

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3044]
Scenario:

I have a custom `IUrlHelper`:

``` C#
public class CdnUrlHelper : UrlHelper
 {
        const string CdnContentVersion = "3.0";
        public CdnUrlHelper(IActionContextAccessor accessor, IActionSelector actionSelector)
            : base(accessor, actionSelector)
        {
        }

        public override string Content(string contentPath)
        {
            return $"//mycdn/{contentPath.Substring(1)}?_v={CdnContentVersion}";
        }
    }
```

Using a ~/ url in the app (`<link href="~/content/css" />`) fails with:

`InvalidOperationException: Unexpected return value from 'IUrlHelper.Content' for URL '~/images/ASP-NET-Banners-01.png'. If the 'IUrlHelper' service has been overridden, change 'Content' to replace only the '~/' prefix. Otherwise, add the following directive to the Razor page to disable URL resolution relative to the application's 'webroot' setting: @removeTagHelper "Microsoft.AspNet.Mvc.Razor.TagHelpers.UrlResolutionTagHelper, Microsoft.AspNet.Mvc.Razor"`

Doesn't seem like there's a way to turn off the exception.

**Comment by danroth27** [comment]
@NTaylorMullen @dougbu @Eilon Why is this return value from Content considered invalid? What check are we trying to do here?

**Comment by NTaylorMullen** [comment]
Given the value `~/foo` the `UrlResolutionTagHelper` checks to see if the returned value of `Content` ends with `foo`. This is to protect against cases when a user does `~/@myUrl`. The reason why it needs to be protected is the evaluated version of `myUrl` is encoded and if we can't determine where that value is accurately we don't know what to encode/not encode.

Essentially `UrlResolutionTagHelper` will encode whatever `~/` expands into and nothing else.

**Comment by Eilon** [comment]
Will revisit in the future.

**Comment by pranavkm** [comment]
We can close this. We haven't had any customer reports of this.
