### ISSUE TITLE
Standardize the behavior of ~ (without slash) paths

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3045]
Seems like a general problem: `Url.Content` resolves `~Text.css` as `/Text.css`. 
However this doesn't work with url resolution in Views: e.g.
`<link href="~Text.css" />` gets printed as is. This also seems to be the behavior in Mvc 5

There are other places in the application (for instance view resolution) where we specifically look for `~/` rather than just `~`.

**Comment by danroth27** [comment]
Sounds like a minor issue with Url.Content. Using `~/` is the supported pattern

**Comment by pranavkm** [comment]
Using `~` is also the supported pattern per https://github.com/aspnet/Mvc/issues/2896 - it just doesn't work everywhere.

**Comment by Eilon** [comment]
Can we just special case `"~"` as being "app path"? Doing `"~foo"` seems esoteric and odd... and *wrong*...

**Comment by pranavkm** [comment]
> Can we just special case "~" as being "app path"

:+1:
