### ISSUE TITLE
Custom Tag Helper not executing if Attribute is Missing

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/Mvc#3046]
I've created a custom tag helper that has a bunch of custom attributes. However, I'm finding that if I don't specify all of the attributes defined on the tag helper, the tag helper silently fails without ever firing.

For example:

```c#
[TargetElement("error-display", Attributes="message,icon,header")]
public class ErrorDisplayTagHelper : TagHelper { }
```

Then defining this works fine:

```html
<error-display  message="Hello World"  icon="info-circle" header="Ping">
</error-display>
```

but this doesn't:

```html
<error-display  message="Hello World"  icon="info-circle">
</error-display>
```

To make sure it isn't the TH code itself I'm just returning a string on its own but it looks like any missing attribute causes a silent failure with the actual tag-helper markup rendered into the HTML output.

I also see the same behavior in the VS editor - unless I have all attributes defined the control doesn't go bold/purple.

Am I missing something that has to be set to specify that an attribute is optional?

**Comment by RickStrahl** [comment]
So, turns out using the Attributes on the `[Target]` attribute definitely cause this problem. 

However, I found that if I don't use that attribute parameter and instead use attributes on properties for binding the attributes then it works. So the following works:

```c#
[TargetElement("error-display")]
public class ErrorDisplayTagHelper : TagHelper
{
    [HtmlAttributeName("message")]
    public string message { get; set; }

    [HtmlAttributeName("header")]
    public string header { get; set; }

    [HtmlAttributeName("header")]
    public string icon { get; set;  }
...
}
```

So is the Attributes parameter in the `[Target]` attribute not recommended any more? I see that the native implementations use both but it seems only one of them is required?

**Comment by NTaylorMullen** [comment]
Hey @RickStrahl when you do `[TargetElement("error-display", Attributes="message,icon,header")]` what you're telling the `TagHelper` system is: Don't run unless the element is named `error-display` and has a `message`, `icon

**Comment by NeelBhatt** [comment]
I guess whatever is specified within "Attributes" of TargetElement is must!

**Comment by NTaylorMullen** [comment]
@NeelBhatt Yup, consider those required attributes. Note you could also do the following:

```C#
[TargetElement("error-display", Attributes="header")]
[TargetElement("error-display", Attributes="icon")]
[TargetElement("error-display", Attributes="message")]
public class ErrorDisplayTagHelper : TagHelper
```
This would make the TagHelper only run if ONE of the attributes were present on the `error-display` element.

**Comment by NeelBhatt** [comment]
Yeah got it thanks @NTaylorMullen

**Comment by RickStrahl** [comment]
Makes sense. Thanks @NTaylorMullen.

So Attributes on target are required, and attributes are mapped automatically onto matching properties. HtmlAttributeName is required only then if you need to map an attribute to a property where then name doesn't match or you have -syntax (ie. header-as-html to headerAsHtml).

Will attributes map exactly and ignore case though? I suppose we probably should use property names that follow CLR conventions rather than matching the attribute naming?

**Comment by NTaylorMullen** [comment]
Attributes will map exactly as provided. Aka `[HtmlAttributeName("PascalCase")]` will map the property to the `PascalCase` HTML attribute. Where as `public int PascalCase { get; set; }` will map to the `pascal-case` HTML attribute. 

The only difference in case that you'll notice is within the editor's IntelliSense. HTML attribute case does not matter when it comes to application of `TagHelper`s or even consumption from the browsers during runtime..
