### ISSUE TITLE
Encoding of JSON results

### ISSUE THREAD

**Issue by UglyDuckling2k** [aspnet/Mvc#3048]
Is there any way to set the encoding of return results from Web API controllers? 

Right now I'm having some trouble with åäö in my JSON result, the client side expects utf-8. My guess is that the encoding is set to iso-8859-1 per default?

Regards!

**Comment by danroth27** [comment]
With `JsonResult` the encoding set on the `ContentType` property will be honored for the response.

When using content negotiation you can configure the set of supported encodings on the `JsonOutputFormatter`.
