### ISSUE TITLE
View location convention should use controller namespace

### ISSUE THREAD

**Issue by newsash** [aspnet/Mvc#3064]
If I have controller "{projectName}.Controllers.Admin.UsersController", I expect framework to search views for this controller in "/Views/Admin/Users/" instead of "/Views/Users/".

**Comment by Antaris** [comment]
MVC as standard doesn't do this, unless you have customised the search paths for your view engine. The default view locations have always been:

        Areas/<area>/Views/<controller>/*.cshtml
        Areas/<area>/Views/Shared/*.cshtml
        Views/<controller>/*.cshtml
        Views/Shared/*.cshtml

You can always subclass the view engine to provide additional view locations.

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorViewEngine.cs

**Comment by davidfowl** [comment]
You can change view locations without subclassing the view engine:

https://github.com/aspnet/Mvc/blob/9d89a8cac3cb5fb6b1aa7138814957708c2c22ca/test/WebSites/RazorWebSite/Services/CustomPartialDirectoryViewLocationExpander.cs

**Comment by ThoughtHaven** [comment]
More and more I'd love this feature out of the box. Wouldn't expect it to be high priority for the team but I feel like every developer who knew it existed would use it.

**Comment by newsash** [comment]
Yes, my issue is about adding this feature out of the box.

**Comment by danroth27** [comment]
We have a [sample](https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRoutingConvention) for a similar scenario, but no plans to put it in the framework.
