### ISSUE TITLE
[Perf] Mvc-only end-to-end test

### ISSUE THREAD

**Issue by benaadams** [aspnet/Mvc#3070]
Perf testing and profiling is very complicated due to the all the parts; might be useful to create a test that starts at MvcRouteHandler.RouteAsync though to a razor view (or just controller like MvcMinimalSample.Web)

You could then wrap this test in a tight for loop and stopwatch it.

The important aspect this would enable is end-to-end load testing in isolation of Mvc and a request per second measure without the extra variables of the server, network, AspNet.Routing and external load generator; which adds an awful lot of noise and complexity; to then try to extract out the Mvc performance.

**Comment by benaadams** [comment]
Also makes it easier if you start doing any jit tracing; haven't done it for a while, hopefully it still works with coreclr

http://blogs.msdn.com/b/clrcodegeneration/archive/2009/05/11/jit-etw-tracing-in-net-framework-4.aspx

http://blogs.msdn.com/b/clrcodegeneration/archive/2010/05/07/jit-etw-tail-call-event-fail-reasons.aspx

**Comment by rynowak** [comment]
What you're suggesting can be a useful tool, but if I could soapbox a bit about our focus right now...

> The important aspect this would enable is end-to-end load testing in isolation of Mvc and a request per second measure without the extra variables of the server, network, AspNet.Routing and external load generator; which adds an awful lot of noise and complexity; to then try to extract out the Mvc performance.

We (asp.net) own all of these, well except for the load generator and the networking stack. If our time is better spent improving Kestrel or Routing, then that's where we should spend it. The big picture in terms of perf is still the most important picture right now.


If you wanted to build something like this, a very low investment way to do it would be to build a test-harness around something like this: https://github.com/Glimpse/Glimpse.Prototype/pull/30/files At this level you're still dealing with HTTP as a protocol, but no network or server abstractions. You could couple that with something like what @rowanmiller built for EF's benchmark tests: https://github.com/aspnet/EntityFramework/tree/dev/test/EntityFramework.Microbenchmarks.Core

**Comment by rynowak** [comment]
If the above sounds useful, I'm happy to share out my repo where I've been building some benchmarks for my own private testing.

**Comment by benaadams** [comment]
> If our time is better spent improving Kestrel or Routing, then that's where we should spend it.

Agreed, but something is slower than it should be and I can't actually tell what it is; there's nothing immediately obvious. ConfgureAwait fit that bill nicely; except the AspSynchronisationContext is gone; so it, as pointed out, it wouldn't improve things. 

Since trying to find out what was slow wasn't working my next approach would be to do the opposite.  Find out what isn't slow and remove it from the equation. Networking is a noisy beast and dependent on so many other factors, as well as being fragile to profiling; so I wanted to look at how the stack performed without it.

Routing is probably easy enough to check in isolation; and again hopefully looking at the Mvc stack in isolation would either show some issues that could be addressed or remove it from the equation.

However; there's an entirely new level of DI going on; which for me means its easier to take an existing test and adapt it; then to try to work out everything that needs to be set up - the Glimpse prototype looks like it might be what I'm after - thank you will check it out

**Comment by rynowak** [comment]
@benaadams Not sure if you saw, I pushed a prototype of something like this here: https://github.com/rynowak/mvc-sandbox/commit/5ced4d1fe0dffa57266519e2f7a95c527bd9f6fa
