### ISSUE TITLE
NullReferenceException in Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService.GetApplicationReferences()

### ISSUE THREAD

**Issue by anfomin** [aspnet/Mvc#3071]
I'm getting error `NullReferenceException` when I try to render any Razor view in `Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService.GetApplicationReferences()`

![2015-09-01 15 04 59](https://cloud.githubusercontent.com/assets/1905503/9601508/81993b48-50bb-11e5-8b5d-84a1a8bcbfb7.png)

**This exception occurs only in Windows Azure environment.** When I run web app locally in IIS Express it is OK. I've investigated, variable `export` is `null` at line 200:
```C#
//...
var export = _libraryExporter.GetAllExports(_environment.ApplicationName);
foreach (var metadataReference in export.MetadataReferences)
//...
```

I'm running latest DNX CLR 1.0.0-beta8-15545.

**Comment by anfomin** [comment]
Also checked, this exception occurs only if I publish with `--no-source` flag:
```ps1
& dnu publish $project --out $publish --configuration Release --no-source --runtime active
```

Razor works if I publish without this flag.

**Comment by pranavkm** [comment]
cc @davidfowl

**Comment by davidfowl** [comment]
@anfomin After doing publish with a --no-source flag, are you running it in full IIS? Or self hosted?

**Comment by anfomin** [comment]
@davidfowl After this command I publish project via *msdeploy* to Windows Azure with full IIS.

**Comment by davidfowl** [comment]
What versions of dnx and mvc are you using?

**Comment by anfomin** [comment]
I've just upgraded to the latest builds from `https://www.myget.org/gallery/aspnetlitedev`:

- DNX CLR v1.0.0-beta8-15547
- MVC v6.0.0-beta8-15601

A little bit more info from 500 error page:
```
.NET Framework CLR version 4.0.30319.42000
DNX x86 version 1.0.0-beta8-15547
Microsoft.AspNet.Loader.IIS version 1.0.0-beta8-15540
IIS version 8.0.9200.16384 (win8_rtm.120725-1247)
Windows 6.2.9200.0
```

**Comment by pranavkm** [comment]
@anfomin, seems  like a DNX issue. Filed a tracking bug (https://github.com/aspnet/dnx/issues/2670) and we'll follow it up as part of DNX
