### ISSUE TITLE
Use route data from middleware, is this possible?

### ISSUE THREAD

**Issue by annexus** [aspnet/Mvc#3073]
Like the title says, I'mtrying to read, add and change route data from a middleware class. But I can't seem to figure out how to even read any route data from my middleware class.

Is this possible? If not, will this ever be possible?

Also, are there any alternatives as where I can read and write to the routeData during runtime?

**Comment by danroth27** [comment]
Not as the system is currently designed - the routing system is itself middleware and the route data is only available within that context.

Can you tell us more about what you are trying to do and why you would need this behavior?

**Comment by Muchiachio** [comment]
I already asked this too, in [Localization using route data](https://github.com/aspnet/Mvc/issues/2884).
Localization through the route data would be a main concern, at least for me.

**Comment by annexus** [comment]
@danroth27 I want to be able to create routes dynamically, letting them all route to the same controller. For example, my appication starts up with the default ValuesController route.

During runtime I want to be able to register templates route like:

api/User (for GET, POST, DEL and PUT)
api/User/Count (GET)
api/Blog  (for GET, POST, DEL and PUT)
api/Blog/Count (GET)

Normally, these routes would resolve to the `UserController` and `BlogController` respectively. But I want to route everything to a `GenericController` as if the requested URL was something like:

api/Generic?entity=Blog

or

api/Generic/Count?entity=Blog (Generic controller and Count action (GET))

So I guess I need to alter the route data if I want to do something like this.

You are probably wondering why on earth I want to do something like this. That's hard to fully explain in a comment, but I'd like to create something similar to how the NodeJS Loopback framework works.

**Comment by csunali** [comment]
Would an `IApplicationModelConvention` implementation help you? You may alter routes using custom conventions.

There are some basic examples at https://github.com/yishaigalatzer/ResourceController

**Comment by rynowak** [comment]
> During runtime I want to be able to register templates route like

There's nothing in the framework that lets you add or modify routes at runtime. 

The one exception is that we **do** have support for updating the attribute routing information if you update the action descriptor collection. I don't rush to call that **supported** either, you'd be building a lot of plumbing to make this work. We'll be taking a look at these kinds of scenarios at some point, no guarantees when.
