### ISSUE TITLE
MVC API review - clean up namespaces

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#3075]
Please create an Announcement after pushing.

**Comment by Eilon** [comment]
The main namespaces we intend to have are:

```
<root>
ActionConstraints
ApiExplorer
ApplicationModel
ActionResults
Actions
Filters
Formatters
Localization
ModelBinding
Razor
Rendering
Routing
TagHelpers
ViewComponents
ViewEngines
WebApiCompatShim
```

**Comment by rynowak** [comment]
Part 1: 229724c

**Comment by rynowak** [comment]
Part 2: 
a318c4599ad718a8fe2ebde79a2129c54e286183
5a8043553427ea79e89ce24e4d1aaadca4bf10d8
9badd9386e6349f80b817277e86eee1330dfa541
4d55a6e62de965047ec593ede76dfeeb793b3128
ccb5ead450519b64b970e719a5131d11c22e1fe5
538cd9c19121f8d3171cbfddd5d842cbb756df3e
046cb976b3e899052a95387b72ea4bee6987bff0
