### ISSUE TITLE
Move HttpResponseStreamWriter to HttpAbstractions

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#3076]
It doesn't belong in MVC.

**Comment by Eilon** [comment]
@Tratcher @rynowak can we get together to determine the fate of this type?

**Comment by rynowak** [comment]
Discussed and agreed to move to RC.

**Comment by ryanbrandenburg** [comment]
As discussed with @rynowak in person, we're also moving HttpRequestStreamReader.

**Comment by ryanbrandenburg** [comment]
Fixed in aspnet/HttpAbstractions/issues/539 and #3940
