### ISSUE TITLE
Implementing a custom ViewResult

### ISSUE THREAD

**Issue by csunali** [aspnet/Mvc#3080]
It is a question rather than an issue.

Imagine a scenario where you need to have a custom action result type that decides which view to use dynamically. Name it `VeryDynamicViewResult` :) and it inherits from `ViewResult`.

The custom view result is smart enough to decide which View to use, having its ViewName property set dynamically - which works perfectly.

As one would expect, it also needs to know what Model data to bind to the view. In MVC 5, achieving that functionality was as easy as below since the `ViewResult` class had a `FindView` method.

```
        protected override ViewEngineResult FindView(ControllerContext context)
        {
            this.ViewName = this.GetType().Name;

            this.ViewData.Model = this.Model;

            return base.FindView(context);
        }
```

MVC 6 does not have such a method and the only place that seems to be appropriate to set the ViewData.Model is `ExecuteResultAsync` method.

However, the ViewData property is still null at that point. I tried instantiating the property myself but its parameters are not somewhere easy to find and could not find enough of documentation.

How could I achieve the above functionality using MVC 6?

```
        public override Task ExecuteResultAsync(ActionContext context)
        {
            ViewName = GetViewNameFromSomewhere();

            ViewData.Model = GetModelFromSomewhere();

            return base.ExecuteResultAsync(context);
        }
```

The method above fails because the ViewData is still null.

Any help is appreciated.

Thank you in advance.

**Comment by pranavkm** [comment]
You'll need to pass in `ViewData` to your `ViewResult` type. See - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/Controller.cs#L262-L267

To get to the `View` instance, you can use `IViewEngine.FindView`:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/Controller.cs#L262-L267
```C#
var viewEngine = context.HttpContext.RequestServices.GetRequiredService<ICompositeViewEngine>();
var view = viewEngine.FindView(context, viewName);
```

**Comment by csunali** [comment]
The issue is that, I am not in a Controller context. I am trying to set the model within the custom ViewResult class.

Just to make it easier for you to imagine, I will try to provide an example:

```
public class FormModel
{
    public string FormHeading { get; set; }
    public string SubmitButtonText { get; set; }
    public string ResetButtonText { get; set; }
    public bool SupportsReset { get; set; }
}

public class FormResult : ViewResult
{
    public FormResult()
    {
        Model = new FormModel();
    }

    public FormModel Model { get; set; }

    public override Task ExecuteResultAsync(ActionContext context)
    {
        ViewName = "/Custom/Path/FormResult.cshtml";

        ViewData.Model = this.Model;

        return base.ExecuteResultAsync(context);
    }
}

public class SomePageController : Controller
{
    public FormResult Index()
    {
        FormResult form = new FormResult();

        form.Model.FormHeading = "Subscription Form";
        form.Model.SubmitButtonText = "Subscribe";
        form.Model.SupportsReset = false;

        return form;
    }
}
```

That is so that my developers can easily create a page that contains a form. I am not actually returning a `View` but a custom `ViewResult` which I expect to have its `ViewName` and `ViewData.Model` set behind the scenes. I was able to set the `ViewName` but not the `ViewData.Model`. (Which I was also able to using MVC 5)

The above code fails when I try to set the `ViewData` using `ViewData.Model = this.Model;`

I understand that I should probably initialize it myself. I see that the `Controller` class has the following comment for the ViewData property:

```    
       By default, this property is activated when <see cref="IControllerActivator"/> activates controllers.
        However, when controllers are directly instantiated in user codes, this property is initialized with
        <see cref="EmptyModelMetadataProvider"/>.
```

Does it actually mean that I should use EmptyModelMetadataProvider to instantiate a `ViewDataDictionary` instance and assign it to `ViewData` prior to using `ViewData.Model = this.Model;`?

**Comment by pranavkm** [comment]
@csunali 

Wouldn't this work:

```C#

public class SomePageController : Controller
{
    public FormResult Index()
    {
        FormResult form = new FormResult();
        form.ViewData = ViewData;
        form.Model.FormHeading = "Subscription Form";
        form.Model.SubmitButtonText = "Subscribe";
        form.Model.SupportsReset = false;

        return form;
    }
}
```
