### ISSUE TITLE
Discussion: Namespace Reorganization in MVC

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3082]
#### This is the place for feedback and discussion on aspnet/Announcements#61
# 
### For beta8 we've begun reorganizing our classes and namespaces in MVC

Our goal is to keep the vast majority of types commonly referred to by name in your _Controller_ and _View_ code in the `Microsoft.AspNet.Mvc` namespace. This reduces bloat when you use intellisense, and hides away things that aren't going to be useful to most developers.

**The changes coming in the first wave will largely focus on moving types out of the `Microsoft.AspNet.Mvc` namespace, and into more focused sub-namespaces.**

Individual changes here are too numerous to detail, here's a summary for some of the more commonly used things that have moved:

Filter interfaces and related contracts: `Microsoft.AspNet.Mvc.Filters`
`IActionResult` implementations: `Microsoft.AspNet.Mvc.ActionResults`
`IActionConstraint` and related contracts: `Microsoft.AspNet.Mvc.ActionConstraints`
Formatter interfaces and implementations (including JSON and XML formatters):  `Microsoft.AspNet.Mvc.Formatters`

Lastly, we've moved a lot of behind the scenes infrastructure into `Microsoft.AspNet.Mvc.Actions`, this is certainly going to be reorganized and changed more in the coming weeks.

**Comment by PureKrome** [comment]
@rynowak really tiny quick favour:

in your announcement, you have some stuff like this:

> Microsoft.AspNet.Mvc is now optimized for types you're likely to use by-name in controller code. Lots of types moved out of this namespace into something more specialized.

can you maybe add an example of what is a type that is likely to be used _by-name_ .. just for extra clarification?

just a thought.

**Comment by rynowak** [comment]
@PureKrome - the best examples are all the attributes you'd put on your controller methods, as well as things you'd likely `new` up or return

```
[HttpPost]
public IActionResult Edit(Person person)
{
}
```

You'd be sad if you had to dig around in other namespaces for `HttpPostAttribute` or `IActionResult`. The goal is to balance that with keeping it simple and straightforward for the 99% case, by avoiding noise in intellisense. 

There's lots of deep extensibility that most users won't touch, and if you do touch it, you won't do it in your controller code.

**Comment by PureKrome** [comment]
Sweet! ta!

**Comment by rynowak** [comment]
And as with the first round... if you think we got something wrong and moved something that you're using frequently in your controller code, please let us know!

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
