### ISSUE TITLE
Wildcard route in MVC6 application not working

### ISSUE THREAD

**Issue by chinookproject** [aspnet/Mvc#3084]
I want to setup a route that matches any request. I used to be able to do this in the older MVC like so:
```
router.MapRoute("Generic", 
    "{*anything}", 
    new { controller = "Generic" }, 
    new { anything = @"^(.*)?$" })
```
So I took exactly that to a MVC6 application. I have this in the Startup.cs:
```
app.UseMvc(router => router.MapRoute("Test", 
    "{*anything}", 
    new { controller = "Test" }, 
    new { anything = @"^(.*)?$" }));
```
I have also created a simple controller class:
```
public class TestController : Controller
{
    [HttpGet]
    public string Get()
    {
        return "aaa";
    }
}
```
So I expect that when I browse to any URL, that this TestController is invoked. But that isn't the case. Not even when I browse to: api/test. They all result in a 404.

How can I fix this issue?

**Comment by rynowak** [comment]
If you're setting up a route like this, you need to specify both the action and controller name, like this:
```
app.UseMvc(router => router.MapRoute("Test", 
    "{*anything}", 
    new { controller = "Test", action = "Get" }, 
    new { anything = @"^(.*)?$" }));
```

This is a difference from WebAPI, but as far as I know this was always required by MVC.

If you want, you can also do this with an attribute route:

```
 [HttpGet("{*anything:regex(^(.*)?$)}"]
public string Get()
{
    return "aaa";
}
```
