### ISSUE TITLE
Localization Issue

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#3085]
If I set no RequestLocalizationOptions and I output @System.Threading.Thread.CurrentThread.CurrentUICulture I see 'es'

If I add in startup cs this:
```
var localizationOptions = new RequestLocalizationOptions()
            {
                SupportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("es-UY"),
                    new CultureInfo("en-US"),
                    new CultureInfo("pt-BR")
                },
                SupportedUICultures = new List<CultureInfo>
                {
                    new CultureInfo("es-UY"),
                    new CultureInfo("en-US"),
                    new CultureInfo("pt-BR")
                }
            };
```

the output of System.Threading.Thread.CurrentThread.CurrentUICulture is en-US.

if I add new CultureInfo("es"), then es is displaying again.

Shouldn't localization fallback to es-UY when the request come using es ? This the behavior I'm seeing on chrome. Edge uses es-UY. Still I think the fallback is not working as expected?

**Comment by Bartmax** [comment]
mmm after some thought I guess the fallback is ok. it cannot fallback to es from a es-UY specific culture info, it does the other way around. am I right ?

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by DamianEdwards** [comment]
Yeah the fallback can only go the other way, i.e. culture specific to culture neutral.

**Comment by Bartmax** [comment]
:+1:
