### ISSUE TITLE
Appending child tag builders to parent one

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#3087]
I see that you changed TagBuilder class and I can't find a way to append two child tag builder contents to a parent one or just two html contents into one. In MVC5 you could do:
```C#
public String CreateTagTree()
{
    TagBuilder firstChild = new TagBuilder("input");
    firstChild.MergeAttribute("type", "hidden");
    firstChild.MergeAttribute("name", "Ids");

    TagBuilder secondChild = new TagBuilder("input");
    secondChild.MergeAttribute("type", "hidden");
    secondChild.MergeAttribute("name", "Ids");

    TagBuilder parent = new TagBuilder("div");
    parent.InnerHtml =
        firstChild.ToString(TagRenderMode.SelfClosing) +
        secondChild.ToString(TagRenderMode.SelfClosing);

    return parent.ToString();
}
```

Is this scenario (will be) supported?

**Comment by rynowak** [comment]
```
    TagBuilder firstChild = new TagBuilder("input");
    firstChild.MergeAttribute("type", "hidden");
    firstChild.MergeAttribute("name", "Ids");
    firstChild.TagRenderMode = TagRenderMode.SelfClosing;

    TagBuilder secondChild = new TagBuilder("input");
    secondChild.MergeAttribute("type", "hidden");
    secondChild.MergeAttribute("name", "Ids");
    secondChild.TagRenderMode = TagRenderMode.SelfClosing;

    BufferedHtmlContent innerHtml = new BufferedHtmlContent();
    innerHtml.Append(firstChild);
    innerHtml.Append(secondChild);
    TagBuilder parent = new TagBuilder("div");
    parent.InnerHtml = innerHtml.
```

If you need to at this point, you can call `parent.WriteTo` with a `StringWriter` to convert it to a `string`, but hopefully you don't have to. We've pivoted HTML helpers and Razor to support `IHtmlContent` as a core abstraction. This way you avoid creating any of the intermediate strings that are used in your sample, we write the text directly to the buffer instead.

**Comment by Muchiachio** [comment]
Yes, it's good that you are writing everything into a buffer but creating complex tag builder objects seems to be way too hard now. Do you have anything planned to make this easier? Writing to a `StringWriter` works for like 1-2 tag levels, but having a lot of them makes a lot of code. Creating html like this is quite a common use case. 
```HTML
<div>
    <div>
        Content
    </div>
    <article>
        Text
    </article>
</div>
```

**Comment by rynowak** [comment]
> Do you have anything planned to make this easier? Writing to a StringWriter works for like 1-2 tag levels, but having a lot of them makes a lot of code. Creating html like this is quite a common use case.

We can look at making this API easier to use, it's just a question of adding the right APIs. It's really not a goal of ours to support the old pattern exactly, it can't perform well.

But I really strongly suggest against `ToString`-ing your `TagBuilder`s unless you have an inflexible requirement that they be strings. Everything in Razor now understands `IHtmlContent`

**Comment by Aveline67** [comment]
Hi all

I have that method working fine (tested) on beta4:

    public static TagBuilder Inner(this TagBuilder tagBuilder, string tagName, string[] cssClass, Action<TagBuilder> child = null)
        {
            var builder = new TagBuilder(tagName);

            foreach (var css in cssClass)
                builder.AddCssClass(css);

            if (child != null)
                child(builder);

            tagBuilder.InnerHtml.Append(builder);

            return tagBuilder;
        }


Which is very useful as I could do something like

  builder
                .Inner("div", new[] { "modal-dialog" },
                    dialog => dialog
                    .Inner("div", new[] { "modal-content" }, content => content
                            .Inner("div", new[] { "modal-header" }, header
                                => header
                                    .Inner("button", new[] { "close" })


So know I am looking for an extension method wich allows me multiple inner content addes to a tag builder

for example

 tagbuilder.Inner("div", new[] { "modal-footer" }, footer =>
                                footer
                                    .Inner("button", new[] { "btn", "btn-default" }, btn => btn.SetInnerText("Close"))
                                    .Inner("button", new[] { "btn", "btn-primary" }, btn =>btn.SetInnerText("Ok"))

**Comment by Muchiachio** [comment]
@rynowak I'm against `ToString`-ing too :+1:
But there is no way to append two html contents into one, that's the main problem :smiley:
Having and `.Append(IHtmlContent)` like `TagHelperContent` does, but for `TagBuilder.InnerHtml`  would be great, so we could do this `parent.InnerHtml.Append(child);`

**Comment by Aveline67** [comment]
I was wrong in my comment,

my code is 
    tagBuilder.InnerHtml  += builder.ToString();

but with new tag builder, that would be cool
    tagBuilder.InnerHtml.Appen(builder) 


(tagBuilder and builder are both TagBuilder in that snippet)

**Comment by rynowak** [comment]
/cc @danroth27 @Eilon - this would be a pretty low impact change to make.


```
public interface IHtmlContentBuilder : IHtmlContent
{
    IHtmlContentBuilder Append(IHtmlContent content);
}

public static class HtmlContentBuilderExtensions
{
    public static IHtmlContentBuilder Append(string unencoded) { }
    public static IHtmlContentBuilder AppendEncoded(string encoded) { }
}

public class TagBuilder : IHtmlContentBuilder { }
```

**Comment by danroth27** [comment]
New proposal is to make InnerHtml not assignable and just support Append. TagBuilder wouldn't implement IHtmlContentBuilder. It would have one instead.

**Comment by leus** [comment]
I tried the beta8 solution and it's really cool, but I'm stuck with beta7 for reasons. What is the workaround if I need to create, say, an ordered list within a tag helper? The workaround proposed (li.innerHtml = bufferedHtml ...) doesn't work at all.

**Comment by staff0rd** [comment]
@rynowak Your example in the second post does not work because TagBuilder.InnerHtml is read-only in beta8.  Is there a new way to do this now?

**Comment by Muchiachio** [comment]
@staff0rd his second example was a " beta7 how to", in beta8 you can write.
```C#
public void Example()
{
    TagBuilder outer = new TagBuilder("div");
    TagBuilder inner = new TagBuilder("div");
    outer.InnerHtml.Append("String");
    outer.InnerHtml.Append(inner);
}
```
