### ISSUE TITLE
Guidance on how, or a 'friendlier' way, to render views to strings (for emails, service calls, etc.)

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#3091]
There are a handful of libraries and snippets floating around out there for how to render a view to a string for use as an email's body or for some other purpose (maybe submitting content to another service, for instance.) 

Would the team consider adding some form of 'official' convenient way of satisfying these use cases? There just seems to be a lot of weirdness around the current methods out there, and I would think those use cases are very common, whether needed by beginner or advanced developers.

I could see asking developers to depend on the `IViewEngine` interface (or the `ICompositeViewEngine` interface as it stands, although I feel `IViewEngine` is a little more obvious/expected :stuck_out_tongue:) in order to obtain the view they wish to render, but when it comes to actually rendering the view, I can't imagine most cases needing more than the simple ability to be able to **take an `IView` instance, pass in a an `object`, and get a `string` out.**

### Resources

- https://github.com/aspnet/Mvc/issues/2871

  Discusses rendering views to strings, but revolves around dependency injection
  and service location rather than encapsulation

- http://stackoverflow.com/questions/31905624/where-are-the-controllercontext-and-viewengines-properties-in-mvc-6-controller

  Recent example for MVC 6

- http://aboutcode.net/postal/

  A popular library that deals some, but not all, of the mailing use cases (in cases I've used, I've still had to do some `HttpContext` rigging and jigging)

### My own working example for MVC6 (using the nightly feed)

This class is registered as a scoped service in Startup. As you can see, there is little in the way of error handling or flexibility. A proper, 'friendly' API could have more public methods for different use cases, and some kind of 'result' class (similar to `ViewEngineResult`.)

`RazorHelper.cs`
```
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Actions;
using Microsoft.AspNet.Mvc.ModelBinding;
using Microsoft.AspNet.Mvc.Rendering;
using System.IO;
using System.Threading.Tasks;

namespace Checkout.AspNet5.Services
{
    public class RazorHelper
    {
        private IHttpContextAccessor httpContextAccessor;
        private IActionContextAccessor actionContextAccessor;
        private ICompositeViewEngine viewEngine;
        private ITempDataProvider tempDataProvider;

        public RazorHelper(
            IHttpContextAccessor httpContextAccessor,
            IActionContextAccessor actionContextAccessor,
            ICompositeViewEngine viewEngine,
            ITempDataProvider tempDataProvider)
        {
            this.httpContextAccessor = httpContextAccessor;
            this.actionContextAccessor = actionContextAccessor;
            this.viewEngine = viewEngine;
            this.tempDataProvider = tempDataProvider;
        }

        public async Task<string> RenderView<TModel>(string name, TModel model, bool partial = true)
        {
            var actionContext = actionContextAccessor.ActionContext;

            var viewEngineResult = partial 
                ? viewEngine.FindPartialView(actionContext, name)
                : viewEngine.FindView(actionContext, name);

            using (var output = new StringWriter())
            {
                var view = viewEngineResult.View;
                var viewContext = new ViewContext(
                    actionContext,
                    viewEngineResult.View,
                    new ViewDataDictionary<TModel>(
                        metadataProvider: new EmptyModelMetadataProvider(),
                        modelState: new ModelStateDictionary())
                    {
                        Model = model
                    },
                    new TempDataDictionary(
                        httpContextAccessor,
                        tempDataProvider),
                    output,
                    new HtmlHelperOptions());

                await view.RenderAsync(viewContext);

                return output.ToString();
            }
        }
    }
}
```

**Comment by tuespetre** [comment]
## Resources

- https://github.com/aspnet/Mvc/issues/2871

  Discusses rendering views to strings, but revolves around dependency injection
  and service location rather than encapsulation

- http://stackoverflow.com/questions/31905624/where-are-the-controllercontext-and-viewengines-properties-in-mvc-6-controller

  Recent example for MVC 6

- http://aboutcode.net/postal/

  A popular library that deals some, but not all, of the mailing use cases (in cases I've used, I've still had to do some `HttpContext` rigging and jigging)

**Comment by danroth27** [comment]
We should discuss more if MVC is really the right framework for these kinds of scenarios. Would it be better to build something more targeted on top of Razor?

**Comment by Bartmax** [comment]
Some common scenario is to have a Controller/View that can be sent based on Model to users and create a static link so you can include a link in the email html to see the view online. If we can have a IActionResult.ToHtml (or ToString) that would be awesome.

**Comment by tuespetre** [comment]
@danroth27 I see your point, but I also see how intertwined MVC and Razor are -- not so much that Razor itself cannot be used without MVC, but the features that developers would want to use in these scenarios are largely dependent on MVC.

With what @Bartmax is saying, I could easily see async message queue worker processes handling the sending of notifications and integrating with other services' APIs, and just making requests to the MVC application for either a full or partial HTML document. For projects that are not really big enough to justify running separate worker processes, they could just send a request to themselves.

At that point I guess it would be a question of whether the overhead of servicing a full request incurs any real performance penalty (I know that in our case, for any of our usage scenarios, it would not.)

**Comment by tuespetre** [comment]
Just popping back in to mention: one of the benefits that Postal provides is the ability to have both `text/plain` and `text/html` representations within a single message.

- More often than not, the `text/plain` representations benefit greatly from having template files outside of the code, especially if you would want to have different versions per culture/language. 
- They also often need the niceties of `Url.Route(...)` and kin. 
- Sending not just one, but two actual HTTP requests to obtain the content for rendering an email is, I'm guessing, unacceptable for most.

**Comment by tuespetre** [comment]
Added my own working example to the original post with some comments.

**Comment by louislewis2** [comment]
After updating to rc1-final from beta7, the code snippet provided by @tuespetre now throws an exception: Value cannot be null. Parameter name: provider. The only provider property I find that is null, is on the RazorPage object called _provider. The property is private making it ever more difficult to sort out.

Has anyone else encountered this perhaps, or maybe have advice to get it up and running again?

**Comment by tuespetre** [comment]
@louislewis2 the same snippet is still going strong for me in rc1 (just upgraded from beta8.)

The `Value cannot be null. Parameter name: provider.` sounds like it is most likely an `ArgumentNullException` for the second argument here:

```
new TempDataDictionary(
    httpContextAccessor,
    tempDataProvider)
```

**Comment by brockallen** [comment]
> We should discuss more if MVC is really the right framework for these kinds of scenarios. Would it be better to build something more targeted on top of Razor?

>> @danroth27 I see your point, but I also see how intertwined MVC and Razor are

This is why it'd be nice to have things like layout templates in razor, and not mvc. @danroth27 this is similar feedback to what we had previously discussed.

**Comment by louislewis2** [comment]
@tuespetre Thanks for the suggestion, I had a few differences from your exact code. Most specifically so that it could be run when no request was present. In my scenario, this call actionContextAccessor.ActionContext would result in ActionContext being null. This is a sample of what I did which was working great up till my upgrade.

```
var actionContext= new ActionContext();
actionContext.RouteData = new Microsoft.AspNet.Routing.RouteData();
actionContext.ActionDescriptor = new ActionDescriptor();
actionContext.HttpContext = new FakeHttpContext(this.serviceProvider);
```

**Comment by louislewis2** [comment]
@tuespetre This is the bulk of my current code, which was based from your initial sample above, as I mentioned the only difference was that I managed to hack it a bit to get it working in the console application / without an http request of any sort.

```
        public async Task<string> RenderView<TModel>(string name, TModel model, bool partial = false)
        {
            try
            {
                IHttpContextAccessor httpContentAccessor = this.httpContextAccessor;
                ActionContext actionContext = null;
                actionContext = actionContextAccessor.ActionContext;

                if (actionContext == null)
                {
                    actionContext = new ActionContext(new FakeHttpContext(this.serviceProvider), new RouteData(), new ActionDescriptor());
                }

                if(httpContextAccessor.HttpContext == null)
                {
                    httpContextAccessor.HttpContext = actionContext.HttpContext; 
                }

                var viewEngineResult = partial
                    ? viewEngine.FindPartialView(actionContext, name)
                    : viewEngine.FindView(actionContext, name);

                IView view = viewEngineResult.View;

                using (var output = new StringWriter())
                {
                    var viewContext = new ViewContext(
                        actionContext,
                        viewEngineResult.View,
                        new ViewDataDictionary<TModel>(
                            metadataProvider: new EmptyModelMetadataProvider(),
                            modelState: new ModelStateDictionary())
                        {
                            Model = model
                        },
                        new TempDataDictionary(
                            httpContextAccessor,
                            tempDataProvider),
                        output,
                        new HtmlHelperOptions());

                    await view.RenderAsync(viewContext);

                    return output.ToString();
                }
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex.Message, ex);
                throw;
            }
        }
```

```
    public class FakeHttpContext : DefaultHttpContext
    {
        public FakeHttpContext(IServiceProvider serviceProvider)
        {
            this.ApplicationServices = serviceProvider;
        }
    }
```

In beta7, after a bit of digging, I found that they only methods required on the HttpContext was 
```
public override IServiceProvider ApplicationServices
public override IServiceProvider RequestServices
```

And for both the above methods, I had a local IServiceProvider which I simply passed in via the constructor.

After my upgrade to rc1, this no longer worked, so I started hunting around. I found that there is now a default http context which I chose to inherit from this time.

But the problem still seems to be on the private property in the RazorPage property on ViewEngineResult.

**Comment by louislewis2** [comment]
For anyone who is interested, its fixed again.

```
    public class FakeHttpContext : DefaultHttpContext
    {
        public FakeHttpContext(IServiceProvider serviceProvider)
        {
            this.ApplicationServices = serviceProvider;
            this.RequestServices = serviceProvider;
        }
    }
```

The RequestServices object was not set.

**Comment by ajaybhargavb** [comment]
Added a sample https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString

**Comment by adrien-constant** [comment]
I could not find a way to use RazorViewEngine.GetView() (or FindView) with a path outside of the project directory (by specifying the full path of the views directory).
Is it possible ? Maybe with IViewLocationExpander?

**Comment by ajaybhargavb** [comment]
@adrien-constant, fixed this issue in https://github.com/aspnet/Entropy/commit/fe79fe6564989dd87f28ab0f64b932e9536b096f.

**Comment by tuespetre** [comment]
@Eilon @danroth27 @ajaybhargavb  I would like to look at some more low-level stuff with Razor sometime as @danroth27 said to 'build something more targeted', but it will definitely be after RC2, probably after RTM. Thanks for keeping this open for discussion as long as you have and thanks for looking into it.

**Comment by Eilon** [comment]
@tuespetre sure, we just closed the issue for now because we think the key features are done. As new requirements and scenarios come up, we'll certainly look at addressing those. If you have thoughts on those, we should create new issues so that we can have targeted discussions on those.

**Comment by tuespetre** [comment]
@Eilon for sure. Getting excited more and more for RC2 and of course eventual RTM! ASP.NET Core has both subtly and radically transformed my development process in amazing ways. Would you happen to know if there will be some documentation written about Razor from a low-level perspective? Or is that something that could be `up-for-grabs`? ;)

**Comment by Eilon** [comment]
@tuespetre thanks for the compliments!

Is there anything particular about Razor you're looking for? We probably don't have low-level documents on it at all. We're about to start work on some updated higher-level docs about using it, the syntax, etc.

**Comment by CarlosOnline** [comment]
Used above solution and another page to get it working.  Had to get the ICompositeViewEngine from the IServiceProvider.  Grab FakeHttpContext from above too.

```
public MyController : Controller
{
...
        public string RenderPartialViewToString(string viewName, object model)
        {
            var engine = ServiceProvider.GetService(typeof(ICompositeViewEngine)) as ICompositeViewEngine;
            if (engine == null)
                throw new Exception("Missing ICompositeViewEngine");

            ActionContext.RouteData = new RouteData();
            ActionContext.ActionDescriptor = new ActionDescriptor();
            ActionContext.HttpContext = new FakeHttpContext(Startup.ServiceProvider) { ApplicationServices = Startup.ServiceProvider };

            ViewData.Model = model;

            using (var sw = new StringWriter())
            {
                var viewResult = engine.FindPartialView(ActionContext, viewName);
                if (viewResult.View == null)
                {
                    Log.Error("Missing viewResult.View");
                    return null;
                }

                var viewContext = new ViewContext(
                    ActionContext,
                    viewResult.View,
                    ViewData,
                    TempData,
                    sw,
                    new HtmlHelperOptions()
                    );

                var t = viewResult.View.RenderAsync(viewContext);
                t.Wait();

                return sw.GetStringBuilder().ToString();
            }
        }

```

usage:

```
var controller new MyController();
controller.RenderPartialViewToString("~/Views/Home/MyView.cshtml", model);

```

**Comment by mythz** [comment]
Is there anyway to change which Layout a View uses at runtime when rendering to string?
