### ISSUE TITLE
Missing Installation details in Nuget page for Mvc 6.0.0-beta7

### ISSUE THREAD

**Issue by NeelBhatt** [aspnet/Mvc#3092]
I have recently found that there is missing details for installation of beta7 from Nuget.

which should be 

```PM> Install-Package Microsoft.AspNet.Mvc -Version 6.0.0-beta7 -Pre```

instead of 

```PM> Install-Package Microsoft.AspNet.Mvc -Pre```

Nuget Link:
https://www.nuget.org/packages/Microsoft.AspNet.Mvc/6.0.0-beta7

Or may be i am missing something then let me know i will close immediately.

**Comment by davidfowl** [comment]
File a bug on NuGet https://github.com/NuGet/Home

**Comment by NeelBhatt** [comment]
Ok thanks and sorry for inconvenience.
