### ISSUE TITLE
How to custom ViewEngines (beta6 vs beta7 diff)

### ISSUE THREAD

**Issue by israelito3000** [aspnet/Mvc#3096]
In beta6:

services.AddMvc().ConfigureMvcViews(options =>
            {
                options.ViewEngines.Clear();
                options.ViewEngines.Add(typeof(ModularViewEngine));
            });

now in beta7?

"ConfigureMvcViews" do not exist.

**Comment by pranavkm** [comment]
Per https://github.com/aspnet/Announcements/issues/62, this has now changed to:

```C#
services
    .AddMvc()
    .AddViewOptions(options =>
    {
        options.ViewEngines.Clear();
        options.ViewEngines.Add(typeof(ModularViewEngine));
    });
```

**Comment by Muchiachio** [comment]
This doesn't work, because `options.ViewEngines` needs an `IViewEngine` instance, not the type.
And it's hard to get application services at this point.

**Comment by israelito3000** [comment]
In fact this does not work...  as Muchiachio said
options.ViewEngines.Add require an instance of IViewEngine, which is almost impossible to generate because the dependencies that require RazorViewEngine

public class ModularViewEngine : RazorViewEngine
    {
        public ModularViewEngine(IRazorPageFactory pageFactory,
                IRazorViewFactory viewFactory,
                IOptions<RazorViewEngineOptions> optionsAccessor,
                IViewLocationCache viewLocationCache)
        : base(pageFactory,
              viewFactory,
              optionsAccessor,
              viewLocationCache)
        { }
.....

Please could you help me to identify how I can set my custom razor ViewEngine ?

**Comment by davidfowl** [comment]
What are you trying to customize?

**Comment by israelito3000** [comment]
I am creating a pluggable modules based on areas, I need to customize: AreaViewLocationFormats

The method I am overriding is:

public override IEnumerable<string> AreaViewLocationFormats
        {
            get
            {
                return base.AreaViewLocationFormats.Select(f => f.Replace("/Areas/{2}/", "/Modules/nsCrm.Module.{2}/"));
            }
        }

**Comment by davidfowl** [comment]
You don't need a custom view engine to change the view locations. You can implement an `https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/IViewLocationExpander.cs`. 

Here's an example:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/LanguageViewLocationExpander.cs

**Comment by Muchiachio** [comment]
This could work, but how do we know that `viewLocations` passed to `ExpandViewLocations` method are  area views, without reading controller's metadata? Because I tried calling few actions and one time I get
```
"/Views/{1}/{0}.cshtml",
"/Views/Shared/{0}.cshtml"
```
other time I get
```
"/Areas/{2}/Views/{1}/{0}.cshtml",
"/Areas/{2}/Views/Shared/{0}.cshtml",
"/Views/Shared/{0}.cshtml"
```
I see that they are cached, so maybe reading controller's metadata is the way to go?

**Comment by pranavkm** [comment]
@Muchiachio, sorry I missed the part where you were trying to initialize a type. Here's how you'd go about setting it up if you choose to continue going down this path: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/MvcRazorMvcViewOptionsSetup.cs.

Getting the Area value out of `ActionContext.RouteData` would be the best way to get to the area value. See https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorViewEngine.cs#L151-L192
and
`var areaName = GetNormalizedRouteValue(expanderContext.ActionContext, "area");`
etc
