### ISSUE TITLE
MVC 6 @Html.RadioButtonFor "checked" not working

### ISSUE THREAD

**Issue by opalrigby834** [aspnet/Mvc#3098]
@Html.RadioButtonFor(model => model.Gender, "Male", new { @checked = "checked" })

@Html.RadioButtonFor(model => model.Gender, "Female", new { Checked = "checked" })

@Html.RadioButtonFor(model => model.Ad, "Male", new { Checked = "" })

I've tried them all. But not working.

version: 6.0.0-beta7

**Comment by opalrigby834** [comment]
ASP.NET 5 / MVC 6 Ajax post Model to Controller

http://stackoverflow.com/questions/28782928/asp-net-5-mvc-6-ajax-post-model-to-controller

**Comment by dougbu** [comment]
@opalrigby834 the StackOverflow thread you mentioned has been answered a number of times. What exactly is the issue you're seeing?

Assuming your concern is the `checked` property in the `htmlAttributes` argument: You've provided an `expression` and a `value` to compare it against. That comparison always overrides a `checked` value from `htmlAttributes`. Other `htmlAttributes` values are visible in the generated HTML.

Please let us know if something is not working as designed.
