### ISSUE TITLE
Controller-specific layout path discovery is inconsistent when named "_Layout" vs otherwise

### ISSUE THREAD

**Issue by axefrog** [aspnet/Mvc#3099]
I'm using ASP.NET MVC beta 7. I have a set of areas with the paths `/Areas/[areaname]/[etc...]` and am using nested layouts in order to refine views based on the concerns of different areas and controllers. I've noticed that if I want a layout that is specific to a controller, given that the controller may have many views, but certain commonalities I'd like to share between those views, then I can't name it `_Layout.cshtml` and expect it to be found, as it would be had I named it something else.

As an example, let's say I have the folder `~/Areas/Admin/Views/Users`. In that folder, if I place a file called `FooLayout.cshtml`, and then within any of the views in that same folder, add:
```cs
@{
    Layout = "FooLayout";
}
```
... the the layout file is correctly located and nested within other layouts as I would expect it to be.

If, however, I name the layout `_Layout.cshtml`, and in the views in that same folder, use the code:
```cs
@{
    Layout = "_Layout";
}
```
... then the local `_Layout.cshtml` file is ignored and the engine falls back to the nearest shared layout by default. The specificity (or lack thereof) of the layout in any nearby _ViewStart file seems to have no bearing on this behaviour.

**Comment by pranavkm** [comment]
@axefrog, I'm not seeing this issue with the latest dev bits. Here's what I tried out - https://github.com/pranavkm/3099-sample. 

I'll close the issue as no-repro - feel free to reopen it in case you're still seeing this.
