### ISSUE TITLE
Circular layout reference leads to OutOfMemoryException

### ISSUE THREAD

**Issue by axefrog** [aspnet/Mvc#3100]
In one of my `views` folders, I renamed a controller-specific layout from the default to something custom. The layout itself referenced a shared layout of the same name prior to renaming. DropBox then, unbeknownst to me, malfunctioned (as it is prone to do) and dropped a copy of the old layout, before it had been renamed, into my views folder, thus creating a situation where the newly-renamed layout was now erroneously trying to use the old layout which it now sat side-by-side with, instead of the old layout's namesake in the shared views folder. As a result, a circular reference was set up and I spent the next 20 minutes trying to figure out why I was getting OutOfMemoryExceptions when I hadn't changed anything significant.

I'd suggest some kind of circular reference detection in layouts and an exception being thrown to that effect, which would help prevent this kind of confusion.

**Comment by Eilon** [comment]
@pranavkm If you merge the fix for this for beta8 please change the milestone of this bug.
