### ISSUE TITLE
Name of TargetElementAttribute should align with other TagHelper attributes 

### ISSUE THREAD

**Issue by andersborum** [aspnet/Mvc#3101]
Going through the `TagHelper` API in MVC 6, I thought about the usual attribute annotation ceremony and the naming of said attributes.

I was surprised at the naming of the `TargetElement` attribute that developers are required to implement prior to proper registration in MVC 6. The attribute goes along with zero or more uses of the `HtmlAttributeName` attribute, but there's no shared naming scheme that suggests that they "go together". In order to make the attributes "go together" and **help the code more clearly state its purpose**, I suggest the `TargetElement` attribute should be renamed.

The Html prefix works well and simply adding it to the `TargetElement` (`HtmlTargetElement`) makes the attributes go better together; however, there's little resemblance between `HtmlTargetElement` and `HtmlAttributeName`.

I therefore suggest renaming `TargetElement` to `HtmlElementName`.

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by DamianEdwards** [comment]
Agreed.

That type is actually in the aspnet/Razor repo so this issue should be over there.

**Comment by NTaylorMullen** [comment]
`HtmlElementName` doesn't entirely suffice though. `TargetElement` does a lot more than provide an HTML element name to target. It allows users to specify `Attributes` without `TagName` or even `TagStructure`.

I'm up for a new name but I'm not sure `HtmlElementName` is the one.

**Comment by DamianEdwards** [comment]
True. How about `HtmlTargetElement` then?

**Comment by NTaylorMullen** [comment]
:+1:

**Comment by andersborum** [comment]
I think `HtmlTargetElement` is a good name as well.

**Comment by NeelBhatt** [comment]
HtmlTargetElement and HtmlTargetAttribute :+1:

**Comment by NTaylorMullen** [comment]
Doesn't really make sense as two attributes. You can combine the two concepts like so:

```C#
[TargetElement("span", Attributes = "asp-validation-summary")]
```

To state that a `TagHelper` targets a `span` tag which has an attribute with the name of `asp-validation-summary`.

**Comment by andersborum** [comment]
What about `TargetElement` and `TargetAttribute` as `TagHelper` doesn't contain the `Html` prefix either. Is that the better option, considering the naming of the rest of the API?

**Comment by NTaylorMullen** [comment]
@andersborum not sure I follow. What would `TargetAttribute` do differently from `TargetElement` (to still enable [the case](https://github.com/aspnet/Mvc/issues/3101#issuecomment-138776324) I mentioned before)?

**Comment by Eilon** [comment]
The name we decided on is:

`HtmlTargetElement`

And not changing anything else.

**Comment by Eilon** [comment]
Closing in favor of https://github.com/aspnet/Razor/issues/516.
