### ISSUE TITLE
RazorPreCompileModule seems to have no effect in beta 7

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#3106]
(Cross post of https://github.com/aspnet/dnx/issues/2636)

Using beta 7, with the following class file in the `./compiler/preprocess` folder:

```
using Microsoft.AspNet.Mvc;
using System;

namespace Checkout.AspNet5
{
    public class RazorPreCompilation : RazorPreCompileModule
    {
        public RazorPreCompilation(IServiceProvider provider) : base(provider)
        {
        }
    }
}
```

This was modelled after [this class file from beta 7](https://github.com/aspnet/Mvc/blob/6.0.0-beta7/test/WebSites/PrecompilationWebSite/compiler/preprocess/RazorPreCompilation.cs), with the only change being the project's namespace. I have also tried re-casing the folders (`./Compiler/Preprocess`, `/Compiler/PreProcess`, etc.) just in case.

I can't seem to get any indication that anything is happening with this, whether I build from command line or Visual Studio 2015.

`dnx` and `dnu` are both at version `CLR-x86-1.0.0-beta7-15532`.

#### Additional notes

I have a blatant syntax error in a view file. Bombs at runtime, not so much as a whimper from DNX at build time.

**Comment by tuespetre** [comment]
Alright, now maybe I'm just mistaken on how this is supposed to work... when I actually run the web application with the syntax errors in a couple of view files, I get the diagnostics page that lists out compilation errors for those views (even when requesting a kind of 'static' view that has no errors.) I thought those were going to be showing up when I ran `dnu build` or when I built the project in Visual Studio. 

Is this behavior correct?

**Comment by tuespetre** [comment]
Overrode `BeforeBuildContext` to inspect the result of calling the base class; the `context.Diagnostics` property does have the errors I am looking for, but it is not spilling out to the console or otherwise failing the build.

**Comment by pranavkm** [comment]
Seems like something DNX might be responsible for. @davidfowl, does this sound familiar?

**Comment by tuespetre** [comment]
After cloning/building/debugging dnx's 1.0.0-beta7 tag, I think I found where the issue lies, and it looks like @davidfowl had already corrected it, though it did not make it into beta7:

https://github.com/aspnet/dnx/blob/7c6e557fc821f9f10d7ef2f72f6437c840fc18a9/src/Microsoft.Dnx.Compilation.CSharp/RoslynProjectReference.cs#L98

I have confirmed it's working as expected now (local dev build of dnx and changing my project to target `1.0.0-*` and the nightly feed)

**Comment by davidfowl** [comment]
Yes that's fixed in beta8 :smile:

**Comment by davidfowl** [comment]
> After cloning/building/debugging dnx's 1.0.0-beta7 tag, I think I found where the issue lies, and it looks like @davidfowl had already corrected it, though it did not make it into beta7:

BTW that's awesome!
