### ISSUE TITLE
Make RazorViewEngine.GetNormalizedRouteValue easier to use outside of Mvc

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3108]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorViewEngine.cs#L151-L192 - it is marked as internal so that other components inside Razor can use it. This would be useful for any user writing a custom view location expander (for instance https://github.com/aspnet/Mvc/issues/3096 where he'd need to get to the area value) or a custom view engine.

Would it make sense to move this method to Core? There's nothing about it that requires it to be present in `RazorViewEngine`.

cc @rynowak

**Comment by rynowak** [comment]
I don't get why it should move to Core, but it makes sense to make it public. In general if something is internal for any reason other than unit testing, it should be public.

**Comment by danroth27** [comment]
OK to make this public.

**Comment by pranavkm** [comment]
:+1:
