### ISSUE TITLE
ViewComponentResult should check if the response has already been sent before setting the ContentType

### ISSUE THREAD

**Issue by ArashSade** [aspnet/Mvc#3111]
Short story:
I'm trying to combine multiple different ViewComponents in one single response. It renders the first viewcomponent but always fails on any succeeding call to vc.ExecuteResultAsync(context).

Long story:
I'm trying to combine multiple different ViewComponents from a controller. The ActionResult of all combined viewcomponents will be rendered to the browser. This is based on an article which does this with PartialViews and updates the PartialViews with ajax. That article is based on previous version of MVC. For more info see: https://www.simple-talk.com/dotnet/asp.net/revisiting-partial-view-rendering-in-asp.net-mvc/

After many hours I came to the following code example. But the problem is that it works only for the first viewComponent. When I change the order of viewcomponents it still renders the first one. So it doesn't seem to have anything with my viewcomponents. Always at second loop it ends at "vc.ExecuteResultAsync(context);" with no errors. So rendering the first one is always successful.

By the way I'm using VS 2015 Enterprise with Beta7 of MVC6 and all other dependencies.
Please see this stackoverflow question: http://stackoverflow.com/questions/32468238/combine-viewcomponents-in-asp-net-5-mvc-6

I guess it is in some way related to this issue: Fix #2338 - Add ViewComponentResult

```c#
// in controller class
public async Task<IActionResult> Dashboard()
    {
        // Combine multiple viewcomponents
        return new MultipleViewResult(
            ViewComponent(typeof(OrdersViewComponent))
            , ViewComponent(typeof(AccountsViewComponent))
            );
    }

    public class MultipleViewResult : ActionResult
    {
    public const string ChunkSeparator = "---|||---";
    public IList<ViewComponentResult> ViewComponentResults { get; private set; }
    public MultipleViewResult(params ViewComponentResult[] views)
    {
        if (ViewComponentResults == null)
        {
            ViewComponentResults = new List<ViewComponentResult>();
        }

        foreach (var v in views)
            ViewComponentResults.Add(v);
    }

    public override async Task ExecuteResultAsync(ActionContext context)
    {
        if (context == null)
            throw new ArgumentNullException(nameof(context));

        byte[] chunkSeparatorBytes = System.Text.Encoding.UTF8.GetBytes(ChunkSeparator);
        var total = ViewComponentResults.Count;
        for (var index = 0; index < total; index++)
        {
            var vc = ViewComponentResults[index];

            // No matter which viewcomponent, this line works only with the first viewcomponent.
            await vc.ExecuteResultAsync(context);

            if (index < total - 1)
            {
                await context.HttpContext.Response.Body.WriteAsync(chunkSeparatorBytes, 0, chunkSeparatorBytes.Length);
            }
        }
    }
}
```

**Comment by Eilon** [comment]
@rynowak any thoughts on this one?

**Comment by opiants** [comment]
This is the [offending line](https://github.com/aspnet/Mvc/blob/6.0.0-beta7/src/Microsoft.AspNet.Mvc.ViewFeatures/ViewComponentResult.cs#L94). I personally think it is a good idea to leave it the way it is, that is, it causes an exception. A more specific exception should be thrown however. I also believe that the response's ContentType property should be checked and only set it if the ViewComponentResult's ContentType property is different to the response's ContentType property - this I think is what needs to be done to fix this issue

    if (!String.Equals(response.ContentType, contentType.ToString(), StringComparison.Ordinal))
    {
        if (response.HasStarted)
        {
            throw new AMoreSpecificException("Cannot set ContentType when response has already sent.");
        }
        
        response.ContentType = contentType.ToString();
    }

**Comment by rynowak** [comment]
We can do for `ViewComponentResult` what we did recently for `ViewResult` - which is to ignore the content type if it has been set.

This is really done in support of scenarios like this:

```
public IActionResult MyAction(...)
{
    HttpResponse.ContentType = "text/plain";
    return new ViewComponentResult(...);
}
```

If you're building any type of framework on top of view components where they are used to render chunks of the page, it's totally off-road.

**Comment by rynowak** [comment]
Changes here b544aabfdb4b6e1612bece65217f35500365a9fa will prevent a view component from trying to set the content type to the default value if it's already been set. 

It feels worth mentioning again, this change is something we were happy to do because it's a good semantic for the result-type to have and is consistent with `ViewResult` and `PartialViewResult`.

We're not in-general looking to support building another framework layer out of view components.
