### ISSUE TITLE
Suggestion: Partial Tag Helper.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#3112]
I think the [PartialTagHelper](https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/TagHelpers/PartialTagHelper.cs) used on live.asp.net it's a great addition to the framework baked taghelpers.

It's beautiful :heart:

**Comment by dougbu** [comment]
This one came first but @DamianEdwards speced it out in #5916.
