### ISSUE TITLE
MVC 6 Beta 7 - wwwroot resources not found

### ISSUE THREAD

**Issue by GregorBiswanger** [aspnet/Mvc#3114]
Hi,
I updated to new MVC 6 Beta 7 version. But unfortunately the page dos not find the static resources (CSS, JS files) from wwwroot folder. What I should change for work?

Cheers,
Gregor

**Comment by Eilon** [comment]
This sounds like you need to enabled static files in your app. Check out this post: https://github.com/aspnet/Announcements/issues/54

**Comment by GregorBiswanger** [comment]
Yes, it helps..
I add the  "Microsoft.AspNet.StaticFiles": "1.0.0-beta5" package and app.UseStaticFiles(); in Startup.cs. and now it works...

**Comment by Eilon** [comment]
Great!

**Comment by aaron4code** [comment]
useful !!
