### ISSUE TITLE
Is it possible to View(...) get a html string as the view?

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Mvc#3119]
I need to stream a html string to browser within a controller action.
How to stream html string to browser?

**Comment by davidfowl** [comment]
Can you be more specific and explain what you mean by stream? chunked responses? Something else?

**Comment by mikeandersun** [comment]
I means to send a html to browser and browser render it to showing the page.Just like what do the  `return View();`

**Comment by mikeandersun** [comment]
I ask this on [SO](http://stackoverflow.com/questions/32519118/how-to-stream-an-html-string-to-browser-within-a-mvc-6-controller-action)

**Comment by davidfowl** [comment]
I'm not sure what you're asking for even makes sense. You want to send a string to the browser in chunks? So you're asking if you can take a string and break it into chunks an send it to the client?

**Comment by davidfowl** [comment]
Did you try calling context.HttpContext.Response.Body.Write(...)

**Comment by mikeandersun** [comment]
The html string is a complete page, not a chunk of page.
What i need is render a html string (not a physical view file).

**Comment by davidfowl** [comment]
Then just return the string from the controller action or write a custom action result and write the string to the response.

**Comment by davidfowl** [comment]
The most naive way would be like so:

```C#
internal class HtmlStreamActionResult : IActionResult
{
    private readonly string _text;

    public HtmlStreamActionResult(string text)
    {
        _text = text;
    }

    public Task ExecuteResultAsync(ActionContext context)
    {
        return context.Response.WriteAsync(_text);
    }
}
```

**Comment by mikeandersun** [comment]
Thanks work fine. I will come in this matters again :)
and the main question:
Is it possible to View(...) get a html string as the view instead of a physical file?

**Comment by tuespetre** [comment]
As we see in the `IView` interface, `Path` is a cemented concept:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/Rendering/ViewEngine/IView.cs

You could write your HTML string out to a temp file, maybe? You might run into issues with `_ViewImports` and `_ViewStart`.
