### ISSUE TITLE
Built-in support for text/html content negotiation

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#3120]
One of killer features of Web API (now MVC 6) and the HTTP-based web as a whole, is content negotiation. MVC 6 does a very good job of facilitating this and offers built-in support for XML and JSON formatting, but developers still need to do one of three things in order to throw HTML views into the mix:

1. Write the conditional code in their controllers to respond with different types of `ActionResult`s
2. Write duplicate (or semi-duplicate) controllers just for their 'API'
3. Write their own output formatter

**Option 1** has been historically facilitated by MVC with the `IsAjaxRequest` extension method, but not every Javascript library adds the 'X-HTTP-Requested-With' header. This means developers need to add that header themselves or add a standard header like `Accept` in order to influence how the server responds. In addition, developers typically need to write the conditional statements throughout their controllers in order to respond appropriately:

```
if (Request.IsAjaxRequest()) 
{
    return Partial(model); // or return Json(model);
}
else
{
    return View(model);
}
```

**Option 2** may make sense when there are a limited number of API calls used by the site, or the models exposed by the API endpoints are incongruent with the models used to render HTML views.

**Option 3** is useful when the site makes heavy use of Javascript or otherwise exposes an extensive API where the models are essentially identical whether rendered as HTML or serialized in some format (think Knockout.) With option 3, controller code can look something like this:

```
[Route("Whatever")]
public class WhateverController
{
    private IWhateverRepository repository;

    public HomeController(IWhateverRepository repository)
    {
        this.repository = repository;
    }

    [HttpGet, Route("")]
    public WhateverIndexViewModel Index()
    {
        return new WhateverIndexViewModel
        {
            Whatevers = repository.GetAllWhatevers()
        };
    }
}
```

Here, the controller doesn't have to worry. The client is the one saying 'give me this resource as `text/html`', or 'give me this resource as `application/json`.'

I've written an example `TextHtmlOutputFormatter`, and it is not very complex (though of course some things probably need to be improved):

https://github.com/tuespetre/html-mvc-aspnet5/blob/master/src/html-mvc-aspnet5/Helpers/TextHtmlOutputFormatter.cs

Is this functionality something that the MVC team would consider including out of the box?

**Comment by danroth27** [comment]
We have no plans to add an HTML formatter to MVC 6 at this time. In general we think the needs of rendering full views are very different than the needs of Web APIs and are best handled by separate controllers. For cases where returning HTML formatted data is still interested we recommend creating a custom HTML formatter that meets your application's needs.
