### ISSUE TITLE
Passing arrays from javascript code to MVC controllers

### ISSUE THREAD

**Issue by sergeyzwezdin** [aspnet/Mvc#3126]
Could you advise how to pass array from javascript to MVC controller at MVC6?

I've created test project and placed it here - https://github.com/sergeyzwezdin/mvc6-arraybinding

I'm trying to do something like this:

Javascript:
```
$.post("/home/test1", {
        items: ["1", "2", "3"]
    })
    .success(function(result) {
        //...
    });
```

MVC controller:
```
[HttpPost]
public IActionResult Test1(string name, string[] items)
{
    // ...
}
```
**Code:**
1. [JavaScript](https://github.com/sergeyzwezdin/mvc6-arraybinding/blob/master/src/ArrayBinding/Views/Home/Index.cshtml#L16-L26)
2. [MVC Controller](https://github.com/sergeyzwezdin/mvc6-arraybinding/blob/master/src/ArrayBinding/Controllers/HomeController.cs#L17-L21)

Another case is the same code on client side and MVC controller is:

```
[HttpPost]
public IActionResult Test2(Model1 model)
{
    // ...
}

// ...

public class Model1
{
    public string[] Items { get; set; }
}
```

**Code:**
1. [JavaScript](https://github.com/sergeyzwezdin/mvc6-arraybinding/blob/master/src/ArrayBinding/Views/Home/Index.cshtml#L27-L37)
2. [MVC Controller](https://github.com/sergeyzwezdin/mvc6-arraybinding/blob/master/src/ArrayBinding/Controllers/HomeController.cs#L23-L28)

In both cases it does not work - array have no elements.

As far as I remember it does work for MVC5 and WebAPI, but seems now something changed.

So which is true way to pass arrays from JS to MVC controllers now?

**Comment by borgdylan** [comment]
You should decorate the model parameter with the FromBodyAttribute and pass the data in JSON format inside the request body.

**Comment by mishfit** [comment]
As @borgdylan said, push JSON instead of form encoded data. It's important to note that when attempting to push JSON (especially from jQuery 2.x where `$.post()` doesn't accept a settings object) you'll have to be very specific about the [contentType](http://api.jquery.com/jQuery.ajax/#jQuery-ajax-settings).

Also, pay attention to the `ModelState` property in controllers where model binding issues occur. Here's an [example](https://github.com/sergeyzwezdin/mvc6-arraybinding/pull/1)

**Comment by sergeyzwezdin** [comment]
Thanks for tips, guys. It's interesting why this was changed :-) I like using `$.post()` instead of `$.ajax()`.

It seems I have to write cusom model binder :-) At least, I don't see any reason not to do this.

**Comment by rynowak** [comment]
/cc @dougbu - there shouldn't be any need to create a custom model binder. 

Can you use a tool like [Fiddler](http://www.telerik.com/fiddler) to capture an example of what the HTTP request looks like?

**Comment by sergeyzwezdin** [comment]
It looks like this:

```
POST http://localhost:27698/home/test1 HTTP/1.1
Host: localhost:27698
Connection: keep-alive
Content-Length: 50
Accept: */*
Origin: http://localhost:27698
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
DNT: 1
Referer: http://localhost:27698/
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4

name=123&items%5B%5D=1&items%5B%5D=2&items%5B%5D=3
```

All what I need is −
1. Pass arrays as part of object via `$.post()` (would be great to avoid any configuring of jquery)
2. Accept arrays as part of model object (maybe some setup at `Startup.cs` will be required - it's fine)

**Comment by mishfit** [comment]
The crux of the matter is that content type: "application/x-www-form-urlencoded"...you'll notice my [PR](https://github.com/sergeyzwezdin/mvc6-arraybinding/pull/1) to your example shows the scenarios in which it fails and which it works:
<img width="460" alt="model-binding-error" src="https://cloud.githubusercontent.com/assets/817064/9840027/b35f6d1a-5a47-11e5-987f-0c8fb320eb05.png">

^^Here, I adjusted the reproduction sample to show the model binding errors.

Also note: if you upgrade to [jQuery 3.x](http://api.jquery.com/jQuery.ajax/#jQuery-ajax-settings) you can send a settings object (and specify the content type) using `$.post()`. **There is no need for custom model binding at all**. But, as in the sample, it is a good idea to check if the `ModelState` is valid

**Comment by sergeyzwezdin** [comment]
Yes, thank you. This is what I mean. It's suprising for me that ASP.NET does not contains "form-urlencoded" content type of of the box while jquery use it to post data to the server. And that's why I mentioned custom model binder for this.

Thanks for mention `ModelState` - I checked it in debug time as well.

So the question is still open. I don't like idea of changing all `$.post()` to `$.ajax()` for all codebase just because of there is no appropriate binder for unknow reason :) Much easier for me is to create custom binder and keep JS code as is.

**Comment by dougbu** [comment]
@sergeyzwezdin are you suggesting that If the browser sends `application/x-www-form-urlencoded`, the server should interpret it as `application/json`?

**Comment by mishfit** [comment]
@sergeyzwezdin I might have to take back my suggestion...here's an [article](https://lbadri.wordpress.com/2014/11/23/web-api-model-binding-in-asp-net-mvc-6-asp-net-5/) about form data...I'll try a little more with the sample to see if I can get the form data into the controller action (which requires removal of the [FromBody] attribute).

**Comment by sergeyzwezdin** [comment]
@dougbu No. I just want to understand why collection (inside object) at server-side is empty for `application/x-www-form-urlencoded` case.
@mishfit cool explanation, thanks, really helpful. Will play around this.

**Comment by dougbu** [comment]
@sergeyzwezdin actually your Fiddler trace looks consistent. What DNX version are you using (check `dnx --version`)? It's possible you're hitting #2705 which was fixed in Beta 7.

**Comment by sergeyzwezdin** [comment]
@dougbu aha! Here is `1.0.0-beta6-12256`. I will check and let you know.

**Comment by sergeyzwezdin** [comment]
Yes, with `1.0.0-beta7` it does works!
@borgdylan, @mishfit, @dougbu, @rynowak - thank you guys for your assistance!
