### ISSUE TITLE
Investigate removing per-test web site configuration from functional tests

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3139]
Even with d03a851 in place, a number of functional tests reuse existing web sites but create per-test `TestServer` instances and reconfigure them with a per-test `configureServices` delegate. This approach allows the test to directly control the site e.g. `WaitService` for `FlushPointTest` or to get additional information back e.g. `TestPageExecutionContext` for `RazorPageExecutionInstrumentationTest`. A few questions:
1. Are these tests still necessary?
2. Would these tests be better done as integration tests?
3. If not, could the functional tests be done in a `MvcTextFixture`-compatible fashion?

Note a few of seemingly-reasonable tests require a one-off configuration e.g. `HtmlGenerationTest.FormTagHelper_GeneratesExpectedContent()` which changes how `FormTagHelper` instances are configured.

**Comment by dougbu** [comment]
Marking as a Task since the questions here do not involve product code.

**Comment by danroth27** [comment]
Please discuss with @rynowak and do the needful

**Comment by dougbu** [comment]
- `FlushPointTest` -> convert to unit test of `RazorPage`
- `HtmlGenerationTest` -> confirm unit tests exercise tag helper initializers
  - confirm unit tests show `<form>` tag helper behaves differently with different `Antiforgery` values
  - have _one_ unit test that changes default property value using an initializer
- `MvcStartupTest` -> nobody cares, delete
- `PrecompilationTest` -> feature removed therefore remove test; test demonstrates a no-op
- `RazorPageExecutionInstrumentationTest` -> convert to unit test, verify instrumentation data
- `WebApiCompatShimBasicTest` -> see #3140; no changes here

**Comment by dougbu** [comment]
- ff19702 (1/3)
- c8c0c53 (2/3)
- dc32f8a (PR comments on 2/3)
- a69a7a6 (3/3)

**Comment by rynowak** [comment]
:dancer: :fireworks: :dancer:
