### ISSUE TITLE
Add AddDbContext services to the service container when AppDbContext is an internal class.

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Mvc#3142]
`// Add EF services to the service container
            services.AddEntityFramework()
                .AddSqlServer();
                //.AddDbContext<AppDbContext>(options =>
                //{
                //    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]);
                //});`
as you see in above code i have to comment related middleware extension because it is an internal class and i don't access to it in setup.cs that is in another project.
How can I achieve this scenario?

**Comment by davidfowl** [comment]
Is that a question or a statement? Make the class public :smile:

**Comment by davidfowl** [comment]
Also not an MVC bug, please file this on ASP.NET/Home

**Comment by mikeandersun** [comment]
I don't want to make `AppDbContext` as public. :)

**Comment by mikeandersun** [comment]
Can you move it to ASP/Home repo ? please :)
