### ISSUE TITLE
Specifying @model in a page ignores value specified by @inherit from a _ViewImport

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3144]
We have code that prevents `@model` and `@inherits` from being specified in the same page. However this check happens at parse time. Consequently specifying an `@inherits MyBase<TModel>` in _ViewImports and `@model CustomModel` doesn't produce an error. Instead, the `@model` wins and resets the base type to the default (`RazorPage<>`).

This seems like a reasonable thing to do - we shouldn't error on it.

Related: https://github.com/aspnet/Mvc/issues/3143

**Comment by danroth27** [comment]
Please chat with @Eilon on the approach for this issue.
