### ISSUE TITLE
Invariant culture for POST

### ISSUE THREAD

**Issue by miloush** [aspnet/Mvc#3146]
> When the values come from POSTed form fields, we know they came from the user and can then apply the user's locale when binding.

That means that the MVC handling of POST requests works or breaks depending on how the server's locale is set up or changed. When is this a reasonable design?

Couldn't we just have a deterministic parameter parsing like in the case of GET?

**Comment by danroth27** [comment]
You can use the Localization middleware to set the locale based on the users request.

**Comment by miloush** [comment]
That does not really answer the question. Also my point is exactly the opposite, it is based on current locale now as per http://forums.asp.net/t/1461209.aspx which causes the deployment-dependent-issues.

**Comment by danroth27** [comment]
Sorry, let me try to clarify:

For query string data we generally assume that the data is not related to any particular culture, so we always use the Invariant culture to parse it.

For form data we generally assume the data was provided by the user. If the user's locale is indicated in the request then we use that to process the data (i.e. via the localization middleware). If the request does not indicate the user's locale then our best guess is to use the server's locale. You can change this default locale via the localization middleware.

**Comment by miloush** [comment]
Thanks. The questions then would be:
1. This obviously does not work if you are posting numbers coming from javascript (an example would be latitude & longitude, duration or any other measurements), which always uses invariant culture. What is the recommended approach when such data is mixed with user input (or has to be in POST, e.g. with file upload)?
2. How can the request indicate user's locale? Is it the Accept-Language which does not necessarily correspond to the user's locale anyway?
3. Why is server's locale more reasonable fallback than the invariant culture that would be consistent with GET requests?

**Comment by danroth27** [comment]
When parsing JSON we use JSON.NET which by default uses the InvariantCulture, but you can configure JSON.NET to use whatever culture you want. If you have a mixture of data you might be able to leverage extensibility to control which culture is used (ex serialization surrogates).

We do use the Accept-Language header by default in our localization middleware (see https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNet.Localization/AcceptLanguageHeaderRequestCultureProvider.cs), and you're correct that it isn't a perfect determination of locale, but you can implement your own `RequestCultureProvider` to determine the culture however you want.

The fallback to the server's locale is based on the heuristic that the server and the client are often "close" to each other (i.e. in the same locale). Obviously this heuristic is far from perfect.
