### ISSUE TITLE
IViewComponentHelper should return IHtmlContent not HtmlString

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3152]
This API needs an update since we added IHtmlContent.

There's a few other things we should review here as well as part of API reviews.

**Comment by rynowak** [comment]
The same is probably true of `IJsonHelper`

**Comment by Eilon** [comment]
Slightly related to https://github.com/aspnet/Mvc/issues/3123.

**Comment by dougbu** [comment]
b3c68de
