### ISSUE TITLE
options.AntiForgeryOptions missing in beta 7

### ISSUE THREAD

**Issue by chassq** [aspnet/Mvc#3155]
I was using options.AntiForgeryOptions in my services.AddMvc().Configure<MvcOptions> section to set a distinct name for my AntiForgery tokens. We upgraded from beta 5 to beta 7 and now it is missing. How do we set this now?

**Comment by rynowak** [comment]
See here: https://github.com/aspnet/Announcements/issues/34

**Comment by chassq** [comment]
Wow! Thanks for the super fast answer!!!
