### ISSUE TITLE
Localization - 

### ISSUE THREAD

**Issue by miroslavsiska** [aspnet/Mvc#3159]
I cant found any possibilities to create localizations via app code. Its important to have in localization some possibilities to add new languages and strings on runtime.
I mean with it:
Create .resx dynamically via C# code and add localized strings to this .resx files. It is important for each translated modular app.
We need to ranslate entity metadata and validation messages too. 
Please see USERVOICE HERE:
https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/2037267-improve-localization-support-in-views-model-metad

**Comment by rynowak** [comment]
See this repo: https://github.com/aspnet/Localization

This is a work in progress, but please register any feedback or concerns there.
