### ISSUE TITLE
Login session time span and sliding expiration

### ISSUE THREAD

**Issue by Vasimovic** [aspnet/Mvc#3160]
Where do you set the login session (cookie) expire time-span and the sliding expiration option?

Preferably in code vs in config file

**Comment by Eilon** [comment]
The `CookieAuthenticationOptions` type has numerous options to control the cookie behavior:

https://github.com/aspnet/Security/blob/dda67b9d7cf523f2147a06b9eafc613bc239b84a/src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationOptions.cs#L73-L84

For additional security-related questions please ask on the https://github.com/aspnet/Security/issues repo, thanks!

**Comment by Eilon** [comment]
Oh, and don't worry about config - everything is always in code :smile:

**Comment by Vasimovic** [comment]
This is perfect, thank you
