### ISSUE TITLE
RazorViewEngine.cs throw MissingMethodException beta8-15793

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Mvc#3163]
![image](https://cloud.githubusercontent.com/assets/2216750/9975024/e2ad9638-5edd-11e5-9973-93ceaac20077.png)

```
var page = _pageFactory.CreateInstance(applicationRelativePath);
```

**Comment by Kagamine** [comment]
Creating an empty beta 7 project by visual studio and using the mvc b8-15793
when return view(), this exception will be thrown.

**Comment by davidfowl** [comment]
Don't mix beta7 and beta8

**Comment by Kagamine** [comment]
I did not mix them.
This is my project.json
```
  "dependencies": {
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta8-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta8-*",
    "Microsoft.AspNet.Mvc": "6.0.0-beta8-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta8-*"
  },
```

**Comment by Kagamine** [comment]
![image](https://cloud.githubusercontent.com/assets/2216750/9975252/c7b88702-5ee7-11e5-924d-ea32b6454dfd.png)

**Comment by davidfowl** [comment]
What's in your global.json

**Comment by Kagamine** [comment]
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-beta7"
  }
}
```
I don't know how to install beta 7.
dnvm upgrade only can update to beta7

**Comment by davidfowl** [comment]
So first, you're mixing beta7 and beta8. Secondly, you need to remove the sdk version if you want VS to use the default. Third, if you do `dnvm upgrade -u` you'll get the latest unstable build.

**Comment by Kagamine** [comment]
Let me have a try

**Comment by Kagamine** [comment]
![image](https://cloud.githubusercontent.com/assets/2216750/9975432/fddce6b4-5eee-11e5-8e73-63e3f61dab94.png)

I have upgrade and dnu restored.

**Comment by davidfowl** [comment]
You're still running beta7, it says it right there in the error message.

**Comment by Kagamine** [comment]
Thanks. The problem has been solved.
