### ISSUE TITLE
ModelState Generic Remove

### ISSUE THREAD

**Issue by mehran63** [aspnet/Mvc#3164]
A generic version of remove could be more helpful and less error-prone than string hard-coded parametric version as mention here:

https://stackoverflow.com/questions/14008561/is-there-a-strongly-named-way-to-remove-modelstate-errors-in-asp-net-mvc/14008604#14008604

I'm ready to implement it.

**Comment by dougbu** [comment]
Are you suggesting a thin veneer over `ModelBindingHelper.ClearValidationStateForModel(Type, ModelStateDictionary, IModelMetadataProvider, string)`? Or is that method sufficient as-is for your purpose?

**Comment by Muchiachio** [comment]
Actually, having generic add and remove methods for model state would be great.
I have an example on extension implementation [here](https://github.com/NonFactors/MVC5.Template/blob/develop/src/MvcTemplate.Components/Extensions/Mvc/ModelStateDictionaryExtensions.cs#L14) too.
This could look like this:
```C#
public ActionResult Create(Account account)
{
    if (account.EmailIsAlreadyUsed())
    {
        ModelState.AddModelError<Account>(model => model.Email, "Email is already being used.");

        return View(account);
    }

    return RedirectToAction("Index");
}
```

**Comment by mehran63** [comment]
Yes, I mean so.

**Comment by danroth27** [comment]
Sure, do you want to send us a PR with a design proposal? Please note that this feature will have some pretty significant test cost, so we need to take that into consideration as well.

**Comment by Muchiachio** [comment]
I can if @mehran63 doesn't want to take this.
What do you mean by a significant test cost?
Last question, should this be implement as an extension (if yes which namespace?) or in same class?

**Comment by mehran63** [comment]
I prefer to leave it to @Muchiachio .

**Comment by rynowak** [comment]
@Muchiachio - it looks like you're the lucky winner! I'd start with the following:

- Extension methods
- put extensions class in `Microsoft.AspNet.Mvc` in the `Microsoft.AspNet.Mvc.Core` project

Send a PR showing the API surface you want to add first so we can discuss.

**Comment by Muchiachio** [comment]
Yes winner! :smile: But there is one problem, this functionality needs `ExpressionHelper.GetExpressionText(LambdaExpression)` from `ViewFeatures` projects which can not be included from the `Core` project, because of circular references :sob:

**Comment by rynowak** [comment]
Ok, then put it in ViewFeatures for now. We might need to look at moving it.

**Comment by dougbu** [comment]
Self-assigning since I'm looking at #3182. @Eilon since @Muchiachio has this PR, should we move this into Beta8? (PR has some rough edges but all solvable.)

**Comment by Eilon** [comment]
@dougbu yeah I put it on your beta8 plate.

**Comment by dougbu** [comment]
b28debf
eff10cd
