### ISSUE TITLE
Rename Controller.Context back to Controller.HttpContext

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#3165]
In MVC 5 the property was called `HttpContext`:

https://msdn.microsoft.com/en-us/library/system.web.mvc.controller.httpcontext(v=vs.118).aspx#P:System.Web.Mvc.Controller.HttpContext

**Comment by davidfowl** [comment]
No need to sign off on your bugs Dan, you used your account :stuck_out_tongue_closed_eyes: :

**Comment by ajaybhargavb** [comment]
9c81b95d1bae130a474db650771aebd092fa1d10
