### ISSUE TITLE
Consider making IExcludeTypeValidationFilter a ModelMetadata setting

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3168]
There's lots of overlap here between `ModelMetadata.IsSimpleType` and what `IExcludeTypeValidationFilter` does **in practice**.

I suggest removing this interface as an extensibility point, and making it just a setting on `ModelMetadata` - something like:
```
public bool ValidateProperties { get; }
```

There's a few concrete benefits we get from putting it on MM:
- Caching
- Discoverability
- Better naming
- Removes an extensibility point and oft-neglected option

We can retain the existing functionality if we want by adding an extension method one-liner to configure a MM provider that will configure this for a type.

**Comment by ajaybhargavb** [comment]
@rynowak, looks like you already fixed this in 96de1dbe4b914734cfe97f271230ff6c6ddcfa11. Should this just be closed or is there more to this?

**Comment by rynowak** [comment]
Yeah, this is done. Ya snooze, ya looze.
