### ISSUE TITLE
Investigate the reason for localization functional test errors on Mono

### ISSUE THREAD

**Issue by kirthik** [aspnet/Mvc#3172]
`Localization_Resources_ReturnExpectedValues` test in `LocalizationTest` of functional test project fails on Mono. The same website when run separately works returns right results. So there is something going on with how functional tests retrieve resources. We need to investigate this issue more.

**Comment by rynowak** [comment]
Take a look at the shenanigans inside of `TestHelper`. We do some stuff to try and sandbox each functional test website into its own location, that's likely not working the same way with the mono `ResourceManager`.

**Comment by dougbu** [comment]
Note `LocalizationTest` does not use anything from `TestHelper`. Look instead at `MvcTestFixture` and `TestApplicationEnvironment`.

Or double-check that nothing in the Localization repo uses `CallContextServiceLocator.Locator.ServiceProvider`. The `MvcTestFixture` does not update that `static`, meaning it's still the functional test's provider and not the web site's.

**Comment by Eilon** [comment]
Putting this in beta8 in case we have time after code complete. But not urgent.

**Comment by kirthik** [comment]
merged fa5f9399e891f60fb9802c89696ba5b30ca2a4b6
