### ISSUE TITLE
Subresource Integrity TagHelper [Discuss]

### ISSUE THREAD

**Issue by benaadams** [aspnet/Mvc#3173]
Something for ScriptTagHelper and maybe a StyleSheetTagHelper?

> The website author includes an integrity attribute on JavaScript and CSS tags, specifying the cryptographic digest of the resource being loaded from the third party. When the browser fetches the resource, it computes the file's digest and compares it with the value from the integrity attribute. If the values match, the resource is loaded. Otherwise, the browser refuses to load the resource.

W3C Working Draft http://www.w3.org/TR/SRI/

GitHub blog on it: http://githubengineering.com/subresource-integrity/

Could have a compute hash with local file type approach

**Comment by Eilon** [comment]
Sounds pretty cool. This isn't in the plan for this release, but certainly worth looking at in the future.

**Comment by dougbu** [comment]
Unclear what we could do that was correct and worked at runtime.

**Comment by ctolkien** [comment]
I'd like to vote to bring this back...

>Unclear what we could do that was correct and worked at runtime.

Given:
```html
<script src="~/dist/vendor.js" asp-append-version="true"></script>
```

You're already [generating a SHA256 hash on the file contents](https://github.com/aspnet/Mvc/blob/1c4b0fcdf38320b2f02c0bb7c31df5bd391ace07/src/Microsoft.AspNetCore.Mvc.TagHelpers/Internal/FileVersionProvider.cs#L111). 

This value, base64 encoded, could be exposed as the `integrity` attribute along with adding the appropriate `cross-origin` attribute.

**Comment by Eilon** [comment]
Re-opening for discussion. The bug triage team will review again.

**Comment by ctolkien** [comment]
@Eilon  - FYI this issue is still closed.

Buuuut I was thinking about this. If we're generating the SRI based on the hash of the file, and our system is compromised, it doesn't actually provide a huge a mount of benefit - we'll just generate a new hash which matches the compromised file and the browser will happily carry on.

It might help in the case where someone meddles with the resource on the wire, but given HTTPS is taking over I'm not sure how much of a concern this is.

**Comment by Eilon** [comment]
Oops, I must have pressed the wrong button! Actually re-opened now.

**Comment by mkArtakMSFT** [comment]
Moved this out to 2.2.0 as we won't be doing this earlier than that.

**Comment by mkArtakMSFT** [comment]
@DamianEdwards, any suggestions regarding this?

**Comment by mkArtakMSFT** [comment]
This is not a priority for the 2.2 release, hence closing again. Let's re visit after 2.2
