### ISSUE TITLE
Use custom JsonFormatter instead of Newtonsoft.Json

### ISSUE THREAD

**Issue by ZOXEXIVO** [aspnet/Mvc#3175]
I try to use custom json formatters at

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvcCore().AddJsonFormatters(settings => )
        }

but all options is hardcoded for Newtonsoft. How to use owb formatter ?

**Comment by rynowak** [comment]
```
services.AddMvcCore(options =>
{
    options.InputFormatters.Add(new MyInputFormatter());
    options.OutputFormatters.Add(new MyOutputFormatter());
}
```
