### ISSUE TITLE
Clean up logic for encoding in ViewResult and friends

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3177]
Example here: #3176

There is a basic priority system to how we determine the content-type/encoding for writing out a `ViewResult`

**content-type**
1. If there is a content-type specified on the result we prefer that - but we add `charset=utf8` if no encoding is specified
2. Else, if there is a content-type specified on the `HttpResponse` we use it verbatim (don't add `charset`)
3. Else, we specify `text/html; charset=utf-8` 

**encoding**
1. If we're here, we use the provided encoding or UTF8 if unset
2. If we're here, we **always** use UTF8 - we don't attempt to parse `response.ContentType`
3. If we're here, we always use UTF8 which matches our charset

The issue of course here is that case 1 and case 2 seem out of whack. If we're going to add `charset` to the content type user-code sets, we should do it consistently and add it in case 2. However, if we're going to detect the encoding from the content-type we should also do the same in case 2.

My suggestion, remove the fixup from case 1, and update case 2 to use the encoding specified in the content-type assuming it's valid.

**Comment by danroth27** [comment]
If the user explicitly sets a header we should leave it be and not modify it. By default we should assume UTF8.
