### ISSUE TITLE
Suggestion: TagHelper Expanding Child Objects into their own HTML Elements

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#3180]
The ASP.NET 5 [TagHelper documentation](http://docs.asp.net/projects/mvc/en/latest/views/tag-helpers/authoring.html) gives the following example:

```
public class WebsiteContext
{
    public Version Version { get; set; }
    public int CopyrightYear { get; set; }
    public bool Approved { get; set; }
    public int TagsToShow { get; set; }
}

public class WebsiteInformationTagHelper : TagHelper
{
    public WebsiteContext Info { get; set; }

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        output.TagName = "section";
        output.Content.SetContent(
            $@"<ul><li><strong>Version:</strong> {Info.Version}</li>
            <li><strong>Copyright Year:</strong> {Info.CopyrightYear}</li>
            <li><strong>Approved:</strong> {Info.Approved}</li>
            <li><strong>Number of tags to show:</strong> {Info.TagsToShow}</li></ul>");
        output.TagMode = TagMode.StartTagAndEndTag;
    }
}
```

This can then be used in your Razor .cshtml as follows:

```
<website-information info="new WebsiteContext {
    Version = new Version(1, 3),
    CopyrightYear = 1790,
    Approved = true,
    TagsToShow = 131 }"/>
```

This will generate the following HTML:

```
<section>
    <ul>
        <li><strong>Version:</strong> 1.3</li>
        <li><strong>Copyright Year:</strong> 1790</li>
        <li><strong>Approved:</strong> true</li>
        <li><strong>Number of tags to show:</strong> 131 </li>
    </ul>
</section>
```

This is pretty ugly tag helper syntax. Is there some way to nest the `website-context` inside the `website-information` and get full intelli-sense so that the only allowed child of website-information can be context? See example below:

```
<website-information>
    <website-context version="1.3" copyright="1790" approved tags-to-show="131"/>
</website-information>
```

There are several reasons to do this: 
1. You already had lots of attributes on `website-information`.
2. `website-context` makes more logical sense being a child element.
3. The `website-context` properties are logically grouped together and would get lost among other properties on `website-information`.
4. You could have multiple `website-context` elements in a collection.

My own real world application is that I have written a TagHelper to generate Twitter Card and Facebook Open Graph meta tags. I currently have to write this:

```
<twitter-card-gallery 
    username="RehanSaeedUK" 
    creator-username="RehanSaeedUK" 
    title="My Title" 
    image0="new TwitterImage("http://example.com/image0.png", 100, 100)"
    image1="new TwitterImage("http://example.com/image1.png", 100, 100)"
    image2="new TwitterImage("http://example.com/image2.png", 100, 100)"
    image3="new TwitterImage("http://example.com/image3.png", 100, 100)"/>
```

But I would really like to write this:

```
<twitter-card-gallery username="RehanSaeedUK" creator-username="RehanSaeedUK" title="My Title">
    <image0 image-url="http://example.com/image0.png" width="100" height="100"/>
    <image1 image-url="http://example.com/image1.png" width="100" height="100"/>
    <image2 image-url="http://example.com/image2.png" width="100" height="100"/>
    <image3 image-url="http://example.com/image3.png" width="100" height="100"/>
</twitter-card-gallery>
```

Related question on [StackOverflow](http://stackoverflow.com/questions/32692857/nesting-taghelpers-in-asp-net-5-mvc-6).

**Comment by Eilon** [comment]
Is this the same as what's being asked for in https://github.com/aspnet/Razor/issues/496 ?

**Comment by Eilon** [comment]
@dougbu @NTaylorMullen @DamianEdwards FYI

**Comment by RehanSaeed** [comment]
Yes. I had not spotted that issue. My suggestion is similar, although I was not advocating the child elements being tag helpers of their own. In both issues we are talking about turning a complex propery into a HTML element but the possibility of converting a collection should also be considered.

**Comment by Eilon** [comment]
This is a feature area we'll take a look at in the future.

**Comment by abhacid** [comment]
This feature in MVC ?

**Comment by NTaylorMullen** [comment]
@abhacid no it is not. It's currently in the backlog to be completed at another time.

**Comment by rynowak** [comment]
We closed the Razor issue for this a little while back. Tag Helpers are a compile-time feature. We have no plans to make it dynamic. https://github.com/aspnet/Razor/issues/496
