### ISSUE TITLE
Question: Dynamic Link (rooting)

### ISSUE THREAD

**Issue by yunuskiran** [aspnet/Mvc#3181]
How can we use dynamic link on the page, 

For example: I create 2 dynamic form. That names, FirstPage,SecondPage and also I have Main Page. When I am on the main page, if User has AdminRole go to the FirstPage else go to the Second Page. But it depends on the role, condition, etc. I use XML firstly but I don't want to use XML. XML example, 

![abc](https://cloud.githubusercontent.com/assets/2011611/10022659/abcdaef2-6156-11e5-86ce-6910d0464efe.png)

**Comment by pranavkm** [comment]
@yunuskiran is this a Mvc6 application?

**Comment by yunuskiran** [comment]
yes @pranavkm

**Comment by Eilon** [comment]
We are not familiar with this XML format. It looks like a custom workflow implementation and is not directly related to ASP.NET MVC itself.

You can use the `[Authorize]` attribute to determine which roles or users can access particular MVC controller actions. You can also implement 

You can also just put specific logic inside the `MainPage` that checks the user's role or identity and redirects them to a different page.
