### ISSUE TITLE
TModel substitution in Razor pages has broken intellisense

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3185]
Mvc supports inheriting injected properties (`@inject`) from applicabe _ViewImports. A feature we support as part of this injection is the substitution of any `TModel` tokens that appear in the type name of `@inject` with the current model type. For e.g

```html
// _ViewImport
@inject CssHelper<TModel> CssHelper

// Index
@model IndexModel
```
The `CssHelper` property on Index would be of type `CssHelper<IndexModel>`. However since `TModel` isn't a real C# token, VS tooling for this is broken:

![capture](https://cloud.githubusercontent.com/assets/174281/10029157/4e272f52-6125-11e5-9deb-f79c91a9d3cb.PNG)

Note squiggly lines under `TModel`. In addition, you do not get any auto completion for this token. Perhaps a fix for this would be to generate a `TModel` identifier in the page at design time. It would also be useful to figure out if there's a nicer way to perform this substitution.

**Comment by pranavkm** [comment]
cc @Eilon \ @NTaylorMullen

**Comment by NTaylorMullen** [comment]
:+1:

**Comment by Eilon** [comment]
:person_frowning: Fine.
