### ISSUE TITLE
Get referenced assemblies

### ISSUE THREAD

**Issue by angelsix** [aspnet/Mvc#3187]
Where do we now get referenced assemblies from an ASP.Net MVC project? 
System.Reflection.Assembly is empty.

I need to find all references in my project so I can search them for implementations of a specific type

**Comment by davidfowl** [comment]
Here's an example https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Infrastructure/DefaultAssemblyProvider.cs#L13

**Comment by angelsix** [comment]
Looks like that just gets Mvc references. I need references to say my own class libraries that are added as references, like normal .Net Assembly.GetReferencedAssemblies used to do.

**Comment by davidfowl** [comment]
@angelsix Sure but look at the code itself, not the fact that it's getting MVC references. Look at *how* it's doing it.

**Comment by angelsix** [comment]
Its a static list of assemblies. It loads them but the original part to get those strings in the first place isnt in there. 

The only thing I can see doing anything dynamic would be _libraryManager, which is an interface that isnt provided there.

Or am I being really stupid and missing something here?

I have a web project, I add a reference to say MyProject.Core which is a class library. Inside ConfigureServices I want to find all references, one of which should be the string full path I can pass to create an Assembly object for MyProject.Core so I can reflect it

**Comment by davidfowl** [comment]
> Its a static list of assemblies. It loads them but the original part to get those strings in the first place isnt in there.

It's not, it using those assemblies as the seed and finding all libraries that reference them in order to find controllers. Take a closer look.

**Comment by angelsix** [comment]
Ok - and how do I get hold of an ILibraryManager at the ConfigureServices stage in Mvc?

**Comment by davidfowl** [comment]
You can take it as a parameter to the Startup constructor.

**Comment by angelsix** [comment]
Perfect. That worked a treat.
