### ISSUE TITLE
Very large views take forever to compile

### ISSUE THREAD

**Issue by poke** [aspnet/Mvc#3196]
Compiling large views, that is views that contain a large number of HTML tags, is really slow. In my example, the view has 10,000 paragraph tags (the kind of tags is actually irrelevant, same with the content of the tags) and that takes almost *two minutes* to compile, during which there is no feedback at all what is going on. Subsequent requests are instant, so it’s not the size of the file that is causing the issue.

The issue only happens for static content, so if you have a for loop generating millions of tags, then thee compiler has no issues with it (the browser probably will though ;P).

I know this is somewhat an exotic edge case, and usually you wouldn’t have static views this large. But in my case, I am prototyping with a lot of static data (which at some point later will be delivered dynamically of course), so I rather want to put it all in there. I could possibly just use a static file for this, but I would like to run this inside of the application’s existing layout.

Anyway, I don’t know why the compiler takes that long to process the file—and in the end do nothing with it (since there are no razor directives etc.). I understand that it needs to look at all attributes to check for tag helpers etc. (although in my test project, I have no tag helpers registered) to make sure that it doesn’t miss anything. But even so, parsing such a file should just take a tiny moment, and processing 10k tags also shouldn’t take this long.

**Comment by m0sa** [comment]
We've had the same issues with roslyn in our Precompilation project. To us it looked like roslyn had a hard time compiling `SourceText` created from (big) strings. For us, replacing `CSharpSyntaxTree.ParseText(string, CompilationOptions)` with `SourceText.From(Stream, Encoding) ` ([here](https://github.com/StackExchange/StackExchange.Precompilation/blob/fb84eca0fb21a6dc29d51cfad8ba3e132a1ff6d5/StackExchange.Precompilation.Build/CSharpParser.cs#L19)) did the trick of speeding up things tremendously. But we were not digging deep enough to find this minimal repro case. If doing that code change speeds things up, this should definitely be forwarded to the roslyn team.

**Comment by m0sa** [comment]
So, roslyn [uses the StringText](https://github.com/dotnet/roslyn/blob/0a481241ab5f8776d8d1b7ff07252d087d0f82b2/src/Compilers/Test/Utilities/CSharp/CSharpTestBase.cs#L246) for it's tests (including perf tests). But the [perf test source file](https://github.com/dotnet/roslyn/blob/0a481241ab5f8776d8d1b7ff07252d087d0f82b2/src/Compilers/Test/Resources/Core/PerfTests/CSPerfTest.cs) only has 3k lines, which is not even the third of your 10k paragraphs, which would also add a bunch of additional `#line` directives - that might be the perf-killer combination.

**Comment by m0sa** [comment]
Ok, nevermind the above, my hunch was incorrect. I [just proved myself wrong](https://gist.github.com/m0sa/33506d5610f0a152bc4d)

**Comment by pranavkm** [comment]
Thanks for the investigations @m0sa! 

@poke, do the HTML tags have associated tag helpers? This would help to narrow down the issue.

**Comment by poke** [comment]
@pranavkm In my test case, I started with an empty ASP.NET 5 project with only registering the necessary stuff. So no, there are no tag helpers registered at all (not even the ones in `Microsoft.AspNet.Mvc.TagHelpers`).

My original problem started with lots of data in tables (so many tr/td tags) but my test project was using paragraph tags only. If you like, I can make the test project public, so you can use it.

**Comment by rynowak** [comment]
That would be really helpful, or even if you want to provide a gist with just the cshtml, that would likely demonstrate the issue.

**Comment by poke** [comment]
Well, the cshtml consists just of 10k `<p>Paragraph</p>` and literally nothing else. I’ve put the project [here](https://github.com/poke/aspnet-mvc-issue3196).

**Comment by pranavkm** [comment]
Thanks @poke

**Comment by Eilon** [comment]
@pranavkm can you profile this to see what's up?

**Comment by rynowak** [comment]
I did a little playing around with this - @NTaylorMullen will have to help me understand what this code is doing. It's definitely a perf issue inside Razor code generation.

![image](https://cloud.githubusercontent.com/assets/1430011/10128967/e772f672-656d-11e5-8eb6-bf60f598eddb.png)

This code is building up massive stringbuilders and lists

**Comment by rynowak** [comment]
This has been fixed by https://github.com/aspnet/Razor/pull/613

I can compile this view now in about 4 seconds. This still isn't great and we have more work in this area that's going to be tracked by more specific work items. This should at least be usable now.
