### ISSUE TITLE
Render view from string to string

### ISSUE THREAD

**Issue by louislewis2** [aspnet/Mvc#3199]
There are a few issues I have seen that touch on this topic, but I have not seen any of them asked in this way. To reference one example: https://github.com/aspnet/Mvc/issues/3091

My question is thus, how can we ask Razor to please render a view from a string to a string.
The last part of the question is already answered as the example above gets that working. I did have to tweak the code slightly further to get it running from a console application, but got it right in the end. At most I had implement my own HttpContext and only implement this method (for now):

```
        public override object GetFeature(Type type)
        {
            return this.serviceProvider.GetService(type);
        }
```

The in the constructor:

```
        public FakeHttpContext(IServiceProvider serviceProvider)
        {
            this.serviceProvider = serviceProvider;
        }
```

I think it is quite common for views to be able to come from "anywhere". We might use embedded resources, we might load from a database, we might load from file, we might create directly in code, that said how would one do the following:

```
            var view = "<h1>Hello @Model.Name</h1>";
            var viewModel = new { Name = "Louis" };
```

Then then ask razor to please render the result?

**Comment by davidfowl** [comment]
This question gets asked all of the time. Views have a ViewContext which is tied to an action and an HttpContext. you have to have an http request to render a view anything else isn't a view, it's something else. What features of view rendering are you expecting to work? It might be best if we distill the requirements instead if asking for the same feature in 3 different ways on separate bugs.

**Comment by daveaglick** [comment]
I have to disagree with the assertion that Razor *requires* an HTTP request to be a "view". Maybe it's just semantics, but being able to treat Razor as a general-purpose templating language has a lot of great use cases including static site generation, email template rendering, etc.

As far as using like a general templating engine, the current version of Razor is already better in this regard than the last one. However, it still requires a fair amount of scaffolding to get working correctly, and then only if you strip stuff out (like the request context, view context, etc. - see https://github.com/Wyamio/Wyam/tree/develop/Wyam.Modules.Razor). This is obviously something folks would like to see (just look at the popularity of RazorGenerator and similar projects).

Maybe this issue should be moved/reopened in the actual Razor project?

**Comment by pranavkm** [comment]
@daveaglick I don't think @davidfowl comments talks about using Razor's templating behavior. We use that in other areas including our scaffolding code\ diagnostics page etc so we've vested interests to keep that behavior working. Granted there's more we could do to make it be easier to use and consume.

The question was along the lines of rendering a Mvc view outside of the context of Mvc \ HTTP request.

**Comment by davidfowl** [comment]
@daveaglick I didn't say Razor, I said the *Views*.

**Comment by daveaglick** [comment]
@pranavkm @davidfowl Ah, okay, that makes sense. Yeah, taking a "view" that was previously designed for use in Mvc and then trying to render it outside the context of a request probably wouldn't work too well.

I'm also happy to hear the team uses Razor as a more general purpose templating language. Really good strides have been made in that direction (thanks) and I know from some discussions with @ntaylormullen that this is something to be looked at further after the big release.

Maybe @louislewis2 can clarify what he was getting at. The final example he gives does look more general, but then further up there is discussion of Mvc views...

**Comment by NTaylorMullen** [comment]
@daveaglick so I can understand you're requirements more clearly, what parts of calling `GenerateCode` on the core Razor template engine [here](https://github.com/aspnet/Razor/blob/67739ea565fc1b49b051b8796b2a4581f2a80016/src/Microsoft.AspNet.Razor/RazorTemplateEngine.cs#L133-L141) or even utilizing the `MvcRazorHost`'s `GenerateCode` to get a more familiar template [here](https://github.com/aspnet/Mvc/blob/ed509f65a23e5d12dfab360a44260ce4234a275b/src/Microsoft.AspNet.Mvc.Razor.Host/MvcRazorHost.cs#L261-L267) break down for your use-case?

**Comment by davidfowl** [comment]
We need to figure out what the features are people want from this generic non mvc, non http request based view engine.

**Comment by louislewis2** [comment]
Regarding terminology when I said view, I mean "something" that contains text which is possibly using Razor syntax. From the discussion, I would say that I am looking for a way to use the Razor engine to Render views with or without a http request, and be able to supply that view myself. I think view template is the wording I should have used.

I think this sudo code example shows what I and other developers are after.
```
 var viewTemplate = "<h1>Hello @Model.Name</h1>";
 var viewModel = new { Name = "Louis" };
 var view = someRazorViewEngine.RenderAsync(viewTemplate, viewModel);
```

where viewTemplate as can be seen above is a string that contains markup that the Razor View Engine understands. The origin of the viewTemplate string is to be determined by the developer.

the view variable may be returned via a normal MVC call return View(view) which may be used in this case as a view model. The view variable could now be returned via web api, as part of a larger view model for a spa application. The view variable could be passed into a email service and the list of use cases really could go on and on.

**Comment by daveaglick** [comment]
I stand corrected - it looks like this specific issue is more about providing view code (as written in Razor) at runtime and having it compiled and executed on the fly. Not quite the same thing as a general purpose Razor template engine. My apologies for hijacking the issue.

As for the more general case of a "non mvc, non http request based view engine", I'd be happy to work up some initial requirements. I'll go ahead and put them in a new issue over on the Razor project since that seems like a more appropriate place.

**Comment by NTaylorMullen** [comment]
Just an FYI, with the bits of code I linked to in my [comment](https://github.com/aspnet/Mvc/issues/3199#issuecomment-143121183) it does not require an `HttpContext`. It does however, generate a page with access to it (not required).

**Comment by pebezo** [comment]
> We need to figure out what the features are people want from this generic non mvc, non http request based view engine.

A big one would be security. This feature may already be there (I haven't looked close enough), but we should be able to control the assemblies that can be loaded from the Razor code. So `@using` should not be available. We should, however, be able to specify a few assemblies that could be used within the Razor code. Limiting the assemblies/namespaces that can be used may not be enough from a security point of view -- not an expert.

Another one would be error reporting. If I'm using this to allow my users to dynamically generate HTML for email it would help if I could give them good/clear information about where and what went wrong. Again, this may already be there.

Lastly, the ability to cache / compile the views (Razor code) so that subsequent requests are faster -- the same way Razor views are faster on subsequent request.

**Comment by pebezo** [comment]
Also, for more advanced uses, give us a way to specify other views that may be required. 

For example, if I am trying to render an HTML email I may have a layout view and a number of other partials that are used by the initial view. I should be able to either specify "here's a list of all the views you may need" ahead of time (for cases where a layout/partial is shared between emails -- think email templates) or have a delegate where I could provide these as needed.

**Comment by MaximRouiller** [comment]
+1 for being to generate HTML from Razor. Another scenario is Integration testing for TagHelpers.

**Comment by dannyvv** [comment]
:+1: running into this as well.
My case is the email scenario as well: On a form submit controller I want to construct html to send using a razor template. Use an email service to push that one and then show the user a confirmation view in the browser. 
There are lots of blogpost out there that do it in older MVC's, but it seems all rely on ControllerContext being available. That was defined on BaseController, but Controller no longer inherits from that in the the MVC that ships with aspnet50

**Comment by CaffeinatedCM** [comment]
To work around this, I'm currently using an extension method to the controller class:

```
public static async Task<string> GenerateEmailFromRazorAsync(this Controller controller, string viewName, object model)
{
     var writer = new StringWriter();
     var tmp = controller.Resolver.GetService(typeof(ICompositeViewEngine)) as ICompositeViewEngine;

     ViewEngineResult viewResult = tmp.FindView(controller.ActionContext, viewName);

     var viewData = new ViewDataDictionary(controller.MetadataProvider, controller.ModelState);
     viewData.Model = model;

     var htmlHelperOptions = new HtmlHelperOptions();
     htmlHelperOptions.ClientValidationEnabled = false;

     var viewContext = new ViewContext(controller.ActionContext, viewResult.View, viewData, controller.TempData,writer, htmlHelperOptions);

     await viewResult.View.RenderAsync(viewContext);
     writer.Flush();

     return writer.ToString();
}
```

**Comment by rynowak** [comment]
We've built a sample of this kind of thing here: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString

If you're having trouble implementing what you want based on that sample please open a new issue and be specific about what you think is missing.
