### ISSUE TITLE
Telemetry Source Before/After events feedback/thoughts

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Mvc#3204]
Currently there are a few places where we have various Before/After events - `BeforeAction`/`AfterAction` and `BeforeActionMethod`/`AfterActionMethod` being amongst them. In both of these cases the `Before` events has more details than the `After` event. This means that for people interested in getting that before data in conjunction with the timing data have to subscribe to both events and either independently store the data from the begin event and carry it though to the after, or correlate the data after the fact. 

In most cases, if the `After` event had the same data as the `Before` event, it would simplify things for the developer with the only thing they would need to store/flow between the two events is the timing information. In our case, it would also mean that we would only need to publish the `After` event to our internal store and/or not have to store this subset of data independently whilst waiting for the post event if we only wanted the one event going through to our internal store. 

For the current Before/After events where there is a difference in parameters that are published, it would seem that the extra data the `Before` event has could easily be made available to the `After` event as well. And moving forward it would seem this pattern would continue as the `After` usual is executed in the same scope as the `Before`.

**Comment by danroth27** [comment]
@rynowak

**Comment by rynowak** [comment]
Discussed this a bit with @avanderhoorn this morning, he thinks the changes here are pretty minimal and is going to send a PR :+1:

**Comment by Eilon** [comment]
@rynowak parking this on your plate for tracking.

**Comment by rynowak** [comment]
a0764faa86e00c77189fb563039a9abbee08ca66

**Comment by avanderhoorn** [comment]
Thanks!
