### ISSUE TITLE
UrlHelper.GenerateLink needs to throw a ArgNull exception if the url parameter is null.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3208]
Based on discussion here: https://github.com/aspnet/Mvc/pull/3206/files#r40468216

This requires code change in AnchorTagHelper to not call into IHtmlGenerator.GenerateLink with a null url. We have functional tests today (such as the test that renders https://github.com/aspnet/Mvc/blob/dev/test/WebSites/HtmlGenerationWebSite/Views/HtmlGeneration_Home/Index.cshtml#L10) where we expect `IHtmlGenerator.GenerateLink` to succeed if the url is null.

**Comment by dougbu** [comment]
What calls `GenerateLink()` outside `DefaultHtmlGenerator`? Suggest instead changing `GenerateActionLink()`, `GenerateRouteLink()`, and other places we call into the `IUrlHelper` to special-case a `null` return value.

**Comment by Eilon** [comment]
@dougbu can you start a discussion with @pranavkm and @NTaylorMullen on this?

**Comment by Eilon** [comment]
Closing because we are not planning to implement this.
