### ISSUE TITLE
Come up with a better behavior for updating a read-only collection

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3210]
In the case where a request contains data that corresponds to a read-only collection, we can't do anything to bind the data to the actual model, and there will be leftover entries in the model state that didn't go anywhere on the model. These extra entries will currently be marked as `Unvalidated`.

**Comment by Eilon** [comment]
Moving to backlog.

**Comment by Eilon** [comment]
Closing instead because we're not clear on the scenario.
