### ISSUE TITLE
Can not pass nullable to ViewComponent Invoke method

### ISSUE THREAD

**Issue by RiteshPahwa** [aspnet/Mvc#3211]
Beta7 Calling a method like:

```c#
 public async Task<IViewComponentResult> InvokeAsync(int id, bool? commentAllowed, int? commentCount)
```

Generates error 

```
InvalidOperationException: Could not find an 'Invoke' or 'InvokeAsync' method matching the parameters.

Microsoft.AspNet.Mvc.ViewComponents.DefaultViewComponentInvoker.<InvokeAsync>d__4.MoveNext()
```

From View as

```
@await Component.InvokeAsync("Comment", Model.Id, Model.CommentAllowed, Model.CommentCount) 
```

**Comment by Eilon** [comment]
@pranavkm can you investigate?

**Comment by RiteshPahwa** [comment]
@pranavkm let me know if you need any help from my side.

This is the page where I wanted to add this functionality
https://github.com/RiteshPahwa/AspNetBlog/blob/master/src/ASPNetBlog/ViewComponents/CommentViewComponent.cs


Thanks, Ritesh

**Comment by pranavkm** [comment]
Thanks for the repro app. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/ViewComponents/ViewComponentMethodSelector.cs#L82 looks suspect.

**Comment by Eilon** [comment]
Ok looks like this might be a real bug, moving to RC.

**Comment by rynowak** [comment]
Yeah, we might need to do something smarter than what we're doing, or provide a richer API for invoking viewcomponents.

**Comment by pranavkm** [comment]
There's a relatively easy for this issue.
However the method resolution is broken when one the arguments to the ViewComponentHelper is null. http://stackoverflow.com/questions/5968860/handle-null-parameters-while-calling-a-method-using-reflection highlights the problem. The workaround seems to be to write a custom binder to do method selection that works with null value.

**Comment by pranavkm** [comment]
Discussed the bug from https://github.com/aspnet/Mvc/issues/3211#issuecomment-145601137 offline with @rynowak and @Eilon. I'll patch the ability to invoke `Invoke` \ `InvokeAsync` with nullable values, however we'll currently not support passing in null values to these methods. @rynowak will update a follow up work item to revisit ViewComponent method selection.
