### ISSUE TITLE
Different model states in controller's constructor and it's action

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#3212]
Given a controller class in beta7
```C#
public class HomeController : Controller
{
    private ModelStateDictionary Dictionary { get; set; }

    public HomeController()
    {
        Dictionary = ModelState;
    }

    public ActionResult Index()
    {
        bool areTheSame = ModelState == Dictionary; // this results in false

        return View();
    }
}
```
results in different model state dictionary instances in constructor and it's action.

**Comment by dougbu** [comment]
This is expected. Your `Dictionary` property is set based on a default `ViewDataDictionary` instance created for unit testing purposes. The `ViewData` property (and therefore the `ModelState` property) is updated during `Controller` activation. Later still, the action executes.

**Comment by rynowak** [comment]
@Muchiachio - I'd really strongly discourage doing **anything** in a controller constructor other than capturing services passed in via DI.

If you need to run code before an action runs, override `OnActionExecuting` and do what you need to in there.

**Comment by Muchiachio** [comment]
I mainly created this, because it's different behavior from MVC5, and I guess there is no way to share model state with the controller services through DI?

I will try setting model state from `OnActionExecuting` and see if it works. :+1:

**Comment by danroth27** [comment]
We populate some of the properties to make testing controller instances easier.
