### ISSUE TITLE
Consider adding tagHelper support for the placeholder attribute in input elements

### ISSUE THREAD

**Issue by roysanchez** [aspnet/Mvc#3213]
Hi,

Right now the only tagHelper for rendering the display text attr is in a label, but there are times when the space requires the text be put in a placeholder.

Please consider adding support for something like this:
```html
<input asp-for="Name" asp-placeholder="Name" />
```

**Comment by Muchiachio** [comment]
You can use placeholder as is, it will render all additional tags as input attributes.
```HTML
<input asp-for="Name" placeholder="Name" />
```

**Comment by roysanchez** [comment]
Yes, but then i would have to repeat it everytime i reference that property, i'm saying for a way to use a placeholder instead of a label.

Let's say i have this ViewModel:

```csharp
public class PartnerViewModel
{
    [Display(Name = "Partner")]
    public string Name { get; set; }
}
```

If i were to use a label, then my razor view would be something like this:

```html
@model PartnerViewModel

<label asp-for="Name" class="col-md-2 control-label"></label>
<input asp-for="Name" class="form-control" />
```

which would render this:

```html
<label for="Name" class="col-md-2 control-label">Partner</label>
<input id="Name" name="Name" type="text" value="" class="form-control" />
```

<br/>

What i'm requesting is to be able to write this:
```html
@model PartnerViewModel

<label asp-for="Name" class="sr-only"></label>
<input asp-for="Name" asp-placeholder="Name" class="form-control" />
```

And render this:

```html
<label for="Name" class="sr-only">Partner</label>
<input id="Name" name="Name" type="text" value="" placeholder="Partner" class="form-control" />
```

<br/>

This is what i'm doing now to get around this problem:

```html
<input asp-for="Name" placeholder="@Html.DisplayNameFor(model => model.Name)" class="form-control" />
```

**Comment by dougbu** [comment]
The HTML 5.0 specification makes the reasons why using `placeholder` instead of a `<label/>` isn't a great idea in [section 4.10.5.3.10](http://www.w3.org/TR/html5/forms.html#attr-input-placeholder). Putting that aside, placeholders commonly say _more_ than just the name of the field.

Could you clarify the value of this enhancement and why `DisplayNameFor()` is insufficient for your somewhat unique scenario?

**Comment by roysanchez** [comment]
Yes, DisplayNameFor solves it. This is what i'm currently doing:
```html
<input asp-for="Name" placeholder="@Html.DisplayNameFor(model => model.Name)" class="form-control" />
```
It's more for syntactic sugar, so as to not mix the razor syntax with the tagHelpers.

But as you pointed out, it shouldn't be used in place of a label, so maybe adding a way to specify a placeholder attribute, but i believe that belongs more in a custom tagHelper.

**Comment by danroth27** [comment]
We think this is best handled using a custom tag helper or the existing HTML helpers.
