### ISSUE TITLE
Routing not work!

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Mvc#3220]
I update packages to latest on the aspnetvnext feed.

I run my app with web command:
http://localhost:9834      work
http://localhost:9834/app   **NOT WORK** 

Where is my mistake?

**Comment by davidfowl** [comment]
No idea. Can you provide some more details?

**Comment by mikeandersun** [comment]
Is there any way i run the on IIS Express on Windows 7?

**Comment by davidfowl** [comment]
Please provide a repro project with instructions on how to reproduce the error.

**Comment by mikeandersun** [comment]
This is the project.json: 
{
    "version": "1.0.0-*",
    "description": "",
    "authors": [ "" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
        "AutoMapper": "4.0.4",
        "EntityFramework.Core": "7.0.0-*",
        "EntityFramework.Relational": "7.0.0-*",
        "EntityFramework.SqlServer": "7.0.0-*",
        "Microsoft.AspNet.Authentication": "1.0.0-*",
        "Microsoft.AspNet.Diagnostics": "1.0.0-*",
        "Microsoft.AspNet.FileProviders.Physical": "1.0.0-*",
        "Microsoft.AspNet.Hosting": "1.0.0-*",
        "Microsoft.AspNet.Hosting.Abstractions": "1.0.0-*",
        "Microsoft.AspNet.Hosting.Server.Abstractions": "1.0.0-beta8-15683",
        "Microsoft.AspNet.Http.Abstractions": "1.0.0-*",
        "Microsoft.AspNet.Http.Extensions": "1.0.0-*",
        "Microsoft.AspNet.Identity": "3.0.0-*",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-*",
        "Microsoft.AspNet.Mvc": "6.0.0-*",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-*",
        "Microsoft.AspNet.Server.IIS": "1.0.0-*",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
        "Microsoft.AspNet.StaticFiles": "1.0.0-*",
        "Microsoft.AspNet.Tooling.Razor": "1.0.0-*",
        "Microsoft.Framework.Configuration": "1.0.0-*",
        "Microsoft.Framework.Configuration.Abstractions": "1.0.0-*",
        "Microsoft.Framework.Configuration.CommandLine": "1.0.0-*",
        "Microsoft.Framework.Configuration.EnvironmentVariables": "1.0.0-*",
        "Microsoft.Framework.Configuration.Ini": "1.0.0-*",
        "Microsoft.Framework.Configuration.Json": "1.0.0-*",
        "Microsoft.Framework.OptionsModel": "1.0.0-*"
    },

    "frameworks": {
        "dnx451": { }
        
    }
}

**Comment by mikeandersun** [comment]
@davidfowl  [here](https://github.com/mikeandersun/experimental) is a experimental repo
It seems the VS.NET build dos not any output DLLs.

**Comment by Eilon** [comment]
@ajaybhargavb can you investigate?

**Comment by mikeandersun** [comment]
Is it the issue related to architecture(x86 or x64) of my machine? 
My OP is x64 but i install  `1.0.0-beta8-15736` clr x86.

**Comment by Eilon** [comment]
x86 should work fine on an x64 machine.

**Comment by mikeandersun** [comment]
I upgrade  to *-rc1-* packages and Runtimes. 
I can debug the application with Kestrel from VS.NET. it meet the controller action but the result is a white page!!!

**Comment by mikeandersun** [comment]
Any Response ?!

**Comment by ajaybhargavb** [comment]
Looks like you have this line in your `_ViewImports` `@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"` but you haven't added the package in `project.json`. This is causing an exception.
You must add `app.UseDeveloperExceptionPage();` to your startup to see the actual error page. Otherwise you'll just get a 500 with a blank page.
