### ISSUE TITLE
ValidationSummary does not list model errors with empty error message

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Mvc#3228]
Discussion https://github.com/aspnet/Mvc/pull/3214#discussion_r40511642.
Currently ValidationMessage shows a generic `The value 'blah' is invalid` message for these exceptions. But ValidationSummary silently ignores it.

Need to investigate and make a decision of what to show/ignore in ValidationSummary.

Related issue - https://github.com/aspnet/Mvc/issues/3043

cc' @dougbu @NTaylorMullen @Eilon

**Comment by danroth27** [comment]
I think we should investigate if we can reduce the number of cases where there is no error message as much as possible.

**Comment by danroth27** [comment]
@ajaybhargavb What was the MVC 5 behavior?

**Comment by ajaybhargavb** [comment]
MVC 5 behaves the same way as MVC 6. It hides the error messages in validation summary. Spoke to @dougbu about this. We have three options,
1. Leave it as it is (keep hiding these messages in validation summary)
2. Add a single generic error message in validation summary. (something like `One or more fields have invalid values`)
3. Show all the error messages in validation summary.
One problem with the third approach is if we have multiple errors for empty values we will have multiple `The value '' is invalid` messages in validation summary which will be confusing as to which field it refers to.
We need to decide which approach to take.
@danroth27 @Eilon

**Comment by ajaybhargavb** [comment]
Spoke to @Eilon and @dougbu. We decided to keep this consistent with the MVC 5 behavior.
