### ISSUE TITLE
Unable to read big json file from Request.Body

### ISSUE THREAD

**Issue by anfomin** [aspnet/Mvc#3235]
I'm trying to read big JSON file (UTF8) from `Request.Body` stream:
```C#
string content;
using (var sr = new StreamReader(Request.Body, Encoding.Default))
	content = sr.ReadToEnd();
```

At the beginning it's ok, but `content` variable contains invalid character sequence after some offset.

Sample repo: https://github.com/anfomin/DNX-MVC-bigfile. There is file `sample.json`. Just run `dnx kestrel` and make:
```http
POST http://localhost:5000
```
with body = `sample.json` file.

You will find mismatches since line 84.

Source:
![2015-09-30 19 58 00](https://cloud.githubusercontent.com/assets/1905503/10196698/9d2e92be-67ad-11e5-8948-254595776df4.png)

Result:
![2015-09-30 19 58 18](https://cloud.githubusercontent.com/assets/1905503/10196702/9e6a8c64-67ad-11e5-8ebc-f5e4432d113f.png)

I've tried latest DNX 1.0.0-beta8-15736 from https://www.myget.org/F/aspnetvnext/api/v2 and 1.0.0-rc1-15775 from https://www.myget.org/F/aspnetcidev/api/v2.

**Comment by Eilon** [comment]
@kichalla can you take a look?

**Comment by kichalla** [comment]
@anfomin I suppose you are running on Mono on Linux? was curious if Encoding.Default was doing something here but looks like some content is entirely missing based on your snapshot above...just to isolate the issue, can you try saving the read content to a file and see if the contents are any different? also does this issue repro consistently for you?

**Comment by anfomin** [comment]
@kichalla I tried this sample both on Windows and Mac, result is the same.

Also I tried to save `Request.Body` to a text file via `File.CreateText("...")`. Result file contains the same corruptions. You can remove `Encoding.Default`, the result does not change.

The problem is `Request.Body` because when I change input stream to `File.Open(...)` then output is correct.

**Comment by kichalla** [comment]
@anfomin you are right, I was able to repro it on a Windows machine now..investigating...

left -> actual file content
right -> content read from request body and saved to a file
![image](https://cloud.githubusercontent.com/assets/6559784/10206427/ad7b9dce-677b-11e5-82a0-c0a9fb0b4bb9.png)

**Comment by Eilon** [comment]
Weird... putting this on RC. Please enlist @halter73 @lodejard @Tratcher @moozzyk if needed because this might even be a Kestrel issue.

**Comment by kichalla** [comment]
Yeah, this seems like a Kestrel issue as I cannot repro it with weblistener

**Comment by Tratcher** [comment]
This issue was moved to aspnet/KestrelHttpServer#234

**Comment by lodejard** [comment]
Certainly could be - that part of the code was updated heavily recently
