### ISSUE TITLE
Using @inherits and @model together gives intellisense errors

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3243]
Create a 'base' page

```
    public abstract class BasePage<TModel> : RazorPage<TModel>
    {
        public IHtmlContent DoThings(object thing)
        {
            return new HtmlString(thing.ToString());
        }
    }
```

Add this to `_ViewImports.cshtml`
```
@inherits Beta8.Web.BasePage<TModel>
```

You'll get squiggles and errors. Eventually the line will stop being colorized by intellisense (try building, and reopening the file).

![image](https://cloud.githubusercontent.com/assets/1430011/10235375/ba011c38-6850-11e5-833b-24d4d201c9e0.png)

**Comment by danroth27** [comment]
@rynowak Where is the `@model`?

**Comment by rynowak** [comment]
In `Index.cshml` - the page renders corectly, these errors come from intellisense.

**Comment by Eilon** [comment]
I think we intended to ask: *what* does the `@model` look like? Just some random POCO class or something esoteric?

**Comment by rynowak** [comment]
Just a POCO

**Comment by pranavkm** [comment]
The change made as part of #3185 didn't work because we do a case sensitive comparison to determine if a file is a `_ViewImports` (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor.Host/MvcCSharpCodeGenerator.cs#L53-L56). However the file path that is passed in from VS is all lower case. Switching to a case insensitive comparison should be fine since this is a design time scenario that primarily affects VS.

**Comment by Eilon** [comment]
Why is VS changing the case of the file? That doesn't sound right...

**Comment by pranavkm** [comment]
@Eilon confirmed with @ToddGrun - it's intentional behavior.

**Comment by Eilon** [comment]
Umm, that still sounds wrong, no? Intentional or otherwise... The casing of files matters, even on Windows, because NTFS is a case-preserving file system.

**Comment by pranavkm** [comment]
If you say so. @ToddGrun, any chance we could fix this in tooling so that the path we pass in is preserved?

**Comment by ToddGrun** [comment]
We could, it's just a bit of an annoyance as the case we were addressing is due to the git scc provider in VS giving us back the wrong casing. It's surprisingly non-trivial to get the proper case, but we could do that.

**Comment by pranavkm** [comment]
Seeing that this is a design time behavior, I think its ok for us to be case invariant (the fix I made). The worst thing that happens is that you get an extra `using TModel = object;` in your design time generated code.

**Comment by Eilon** [comment]
I would think that if there's a problem with the git scc provider that the casing stuff could be kept just for that area of the code, no? What is the relationship between code that interacts with scc providers and code use for the design time host?

**Comment by ToddGrun** [comment]
We don't interact with it directly. If I'm remembering correctly, the scc provider notifies the diff window of the file name (incorrectly cased). This case is then passed into when our razor document is created and thus we used to just pass this name over directly to the host. We get the project root from a different mechanism which appears to always return back correct casing. I started investigating modifying the path to get the correct case, but at the time (after consulting with Taylor), it was determined that mvc/razor only needed consistent casing for this scenario, not necessarily correct casing.

**Comment by hikalkan** [comment]
This is still a problem for me. While it's actually working when I run the application, it has some intellisense problems.

I've a base class like that:

````C#
    public abstract class MyDemoRazorPage<TModel> : RazorPage<TModel>
    {
        //...some methods...
    }
````
First intellisense problem is in _ViewImports.cshtml:

![inherit-01](https://cloud.githubusercontent.com/assets/1210527/16318142/68d447fa-3996-11e6-9222-6f7e7111d31e.png)

TModel is red, as you see.

Second one is in views. It does not regocnize base methods. But it properly works when I run the application.

Do you have an idea? Can that be related to Resharper (I'm using Resharper Ultimate 2016.2 EAP 2, built on 02 July)
