### ISSUE TITLE
MVC Controller Response - Wrong ContentType

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#3245]
_From @Fosol on October 1, 2015 19:13_

The default response ContentType of an endpoint that returns a struct value (i.e. int) is "application/json".  However the body contains invalid json as it only has the int value.

If you attempt to set the Response.ContentType = "text/plain" it ignores you and sets it to "application/json".

If you attempt to set the Response.ContentType = "text/plain" through the Response.OnStarting method it results in a body containing gibberish.

How do you set the Content Type of the response if you are returning a struct value type?

_Copied from original issue: aspnet/HttpAbstractions#424_

**Comment by Tratcher** [comment]
_From @kichalla on October 1, 2015 19:19_

@Fosol what content type do you want to send it as? text/plain?...can you check if you return the int as a string you should see the response as text/plain...otherwise you can use the `ContentResult` to set the content and content-type the way you want

**Comment by Tratcher** [comment]
_From @Fosol on October 1, 2015 19:56_

Here's an example endpoint.


        [HttpGet]
        [Route("add/{value1}/{value2}")]
        public int Add(int value1, int value2)
{
            return value1 + value2;
}

The default response ContentType: application/json.  But the body only has the number and therefore is invalid json.

If you return a string it does by default become text/plain.

**Comment by Tratcher** [comment]
_From @kichalla on October 1, 2015 20:9_

do you want to send the data in json format? if yes, you would need to have that value as a proeprty on an object...example: if your return type is `dynamic`, you can return something like `return new { result = value1 + value 2}`...the response would be in json and `{ "result":30 }`

**Comment by Tratcher** [comment]
_From @Fosol on October 1, 2015 20:41_

You mention the ContentResult object.  Does this only work if you are returning something like a ActionResult?

**Comment by Fosol** [comment]
This is a bug.

Struct value types should not be returned as application/json by default.

**Comment by danroth27** [comment]
A number is actually valid JSON based on the latest RFC (http://www.ietf.org/rfc/rfc7159.txt):

> JSON-text = ws value ws
> value = false / null / true / object / array / number / string

In MVC generally if you return an object that isn't an IActionResult then we default to using an ObjectResult to format the response based on content negotiation. So the behavior you are seeing is _mostly_ expected.

Except, you should be able to explicitly set the content type and not have it get stomped on by the selected formatter. The fact that your content type is overwritten is a bug.

**Comment by Fosol** [comment]
Thanks!  That was informative.

**Comment by kichalla** [comment]
d77655fb7334e4fdde99797b9e2579649aa72aeb
