### ISSUE TITLE
Move AllowAnonymous to Microsoft.AspNet.Authorization

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#3246]
It's a bit odd that `[Authorize]` is in `Microsoft.AspNet.Authorization` yet its companion attribute `[AllowAnonymous]` is in `Microsoft.AspNet.Mvc`. They should both sit together in the same place.

@Tratcher @HaoK @blowdart @rynowak FYI.

**Comment by NeelBhatt** [comment]
Exactly my thought!!

**Comment by ajaybhargavb** [comment]
aspnet/Security@0f78135f5d0bc88e3d009c47aba8971cf00823fe and 6bd97c7c306a9364b86c87acf2168f6bb0078fc9
