### ISSUE TITLE
Exception while encoding/writing view using pooled buffer

### ISSUE THREAD

**Issue by gvx111** [aspnet/Mvc#3252]
on running controller /home/index showing this error
<pre>ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes
System.Text.Encoding.ThrowBytesOverflow()</pre>

Error 2
<pre>Unhandled Exception: System.InvalidOperationException: A LeasedArraySegment was
collected without being returned to the pool. This is a memory leak.
   at Microsoft.Framework.MemoryPool.DefaultArraySegmentPool`1.DefaultLeasedArra
ySegment.Finalize()</pre>

**Comment by rynowak** [comment]
Can you provide some more details? What platform is this on? What's your controller/view code look like?

**Comment by gvx111** [comment]
this is my view.cshtml
<pre>@{
    ViewBag.Title = "Auctions";
    Layout = Url.ModuleArea("Views\\Layouts\\_Layout");
}
@using ITN.TS.UserStore.Extensions
@using ITN.TS.UserStore.Services
@model List<Auction>

<section id="content" class="content_index">
    <div class="title-line">
        <div class="title">მიმდინარე აუქციონები</div>
    </div>
    <div class="product-content">
        @foreach (var item in Model)
        {
            await Html.RenderPartialAsync("_AuctionBox", item);
        }
    </div>
</section>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <i class="fa fa-minus-circle"></i> Attempting to restore connection. Changes made now may not be saved.
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script src="http://ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.0.3.js"></script>
    <script src="~/signalr/hubs" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $('.bxslider').bxSlider();
            var auctionHub = $.connection.Auction;
            $.connection.hub.reconnecting(function() {
                $('#myModal').modal();
            });

            $.connection.hub.reconnected(function() {
                $('#myModal').modal('hide');
            });

            $.connection.hub.disconnected(function() {

            });
            auctionHub.client.onBid = function(account, currentBid, auctionId) {
                $('#auction_' + auctionId).find('#bidvalue').text(currentBid);
                $('#auction_' + auctionId).find('#winnering').text(account);
            };
            auctionHub.client.onLastTime = function(auctionId, extraTime) {
                extraTime = extraTime.replace('-', '/').replace('T', ' ');
                $('#auction_' + auctionId).find('#remain_' + auctionId).countdown(extraTime, function(event) {
                    $(this).text(event.strftime('%D days %H:%M:%S').replace('00 days', ''));
                });
            };

            auctionHub.client.Connected = function(id) {
                $('#myModal').modal('hide');
            };

            $.connection.hub.start().done(function() {
            });


        })
    </script>
    @if (User.Identity.IsAuthenticated)
    {
        <script>
            jQuery(document).ready(function($) {
                $('.makebid').on('click', function(e) {
                    e.preventDefault();
                    auctionHub.server.bid($(this).attr('au-id'), '@User.Identity.GetUser().Id')
                });
            });
        </script>
    }
    <script src='@Url.ModuleArea("Content/plugins/Countdown/jquery.countdown.min.js")'></script>
    <script>
        var _second = 1000;
        var _minute = _second * 60;
        var _hour = _minute * 60;
        var _day = _hour * 24;
        var timer;

        function countDown(obj, date) {
            var epochValue = date // value pulled from server.
            var utcDateVal = new Date(epochValue);
            var actualDate = new Date(utcDateVal.getTime() + (utcDateVal.getTimezoneOffset() * 60 * 1000));
            console.log(actualDate)

            var now = new Date();
            var end = new Date(date);
            var distance = end - now;
            if (distance < 0) {

                clearInterval(timer);
                document.getElementById(obj).innerHTML = 'Closed!';

                return;
            }
            var days = Math.floor(distance / _day);
            var hours = Math.floor((distance % _day) / _hour);
            var minutes = Math.floor((distance % _hour) / _minute);
            var seconds = Math.floor((distance % _minute) / _second);

            document.getElementById(obj).innerHTML = days + 'days ';
            document.getElementById(obj).innerHTML += hours + 'hrs ';
            document.getElementById(obj).innerHTML += minutes + 'mins ';
            document.getElementById(obj).innerHTML += seconds + 'secs';
        }
    </script>
}
@section slider{
    <div class="bx-wrapper" style="max-width: 100%;">
        <ul class="bxslider">
            <li>
                <p class="slide-title">დაიწყე შოპინგი ახლავე!<br />შეღავათიანი ფასებით</p>
                <p class="slide-subtitle">პირველი ონლაინ აუქციონი საქართველოში</p>
                <button name="registration_btn" class="registration_btn">დარეგისტრირდით ახლავე!</button>
                <img src="http://www.fulltrain.com/qbid/icpennybid/images/sliderimage2.png" />
            </li>
            <li>
                <p class="slide-title">დაიწყე შოპინგი ახლავე!<br />შეღავათიანი ფასებით</p>
                <p class="slide-subtitle">პირველი ონლაინ აუქციონი საქართველოში</p>
                <button name="registration_btn" class="registration_btn">დარეგისტრირდით ახლავე!</button>
                <img src="http://www.fulltrain.com/qbid/icpennybid/images/sliderimage2.png" />
            </li>
        </ul>

        <div class="slider-services">
            <div class="service-box">
                <img src="@Url.ModuleArea("Content/images/params.png")" class="params">
                <p class="service-title">რეგისტრაცია</p>
                <p class="service-desc">გახდი Bidway.ge ს მომხმარებელი, დააჭირეთ რეგისტრაციის ღილაკს და შეავსეთ მარტივი სარეგისტრაციო ფორმა..</p>
                <img src="http://www.fulltrain.com/qbid/icpennybid/images/bg.png">
            </div>
            <div class="service-box">
                <img src="@Url.ModuleArea("Content/images/params.png")" class="params">
                <p class="service-title">ბიდების შეძენა</p>
                <p class="service-desc">შეიძინეთ სასურველი რაოდენობის ბიდები, რათა შეძლოთ აუქციონებზე მონაწილეობის მიღება</p>
                <img src="http://www.fulltrain.com/qbid/icpennybid/images/bg.png">
            </div>
            <div class="service-box">
                <img src="@Url.ModuleArea("Content/images/params.png")" class="params">
                <p class="service-title"> ბიდის გაკეთება</p>
                <p class="service-desc">აირჩიეთ სასურველი აუქციონი, გააკეთეთ ბიდი და შეიძინეთ ნივთები 95% მდე ფასდაკლებით</p>
                <img src="http://www.fulltrain.com/qbid/icpennybid/images/bg.png">
            </div>
        </div>
    </div>
}</pre>
When i removed section slider working correct.
dnx: 1.0.0-rc1-15798
platform: windows

**Comment by gvx111** [comment]
this is my view.cshtml [http://textuploader.com/av9vf]

When i removed section slider working correct.
dnx: 1.0.0-rc1-15798
platform: windows

**Comment by gvx111** [comment]
I understand problem. If i have utf8 encoded text in @section script { } than exception.

**Comment by rynowak** [comment]
Working on a fix for this now - there are two issues here:

Dispose method needs to **always** dispose the buffers, even if flush fails

We were computing the usable size of the char buffer incorrectly. `GetMaxCharCount` is for **decoding** - what we need is a `GetMinCharCount` which doesn't exist. I'm changing the design a bit - now the char buffer is a fixed size, and the byte buffer must be big enough to accommodate it.

**Comment by gvx111** [comment]
@rynowak thank you for reply. I'm working on this error 10 hour and i didn't fix this problem. 
How many time need to fix this but?

**Comment by rynowak** [comment]
If you need to have stable builds you shouldn't by using our CI packages, stick to the latest release without a build number in it (right now 'beta7') Using the latest packages means that you're going to be exposed to a lot of churn and unfortunately, sometimes breaks like this..

This will be checked in sometime this morning, and packages available when they are available.

**Comment by gvx111** [comment]
Yes i m using 6.0.0-*. I must change it t beta7?

**Comment by davidfowl** [comment]
beta7 is stable so yes, beta8 will be stable soon.

**Comment by gvx111** [comment]
Error:
Unhandled Exception: System.InvalidOperationException: A LeasedArraySegment was
collected without being returned to the pool. This is a memory leak.
   at Microsoft.Extensions.MemoryPool.DefaultArraySegmentPool`1.DefaultLeasedArr
aySegment.Finalize()

**Comment by gvx111** [comment]
@rynowak Its same problem not corrected. I use dnu restore but same problem

**Comment by rynowak** [comment]
The package for this won't be available until it has time to propagate through our CI.

**Comment by gvx111** [comment]
@rynowak thank you for help. How many time does it need?

**Comment by rynowak** [comment]
This should be available now with version: `6.0.0-rc1-15986`

**Comment by rynowak** [comment]
ad3c257ef56eb944fc9b5d34ead2650c152b54d5
