### ISSUE TITLE
env.IsDevelopment is false when running web

### ISSUE THREAD

**Issue by angelsix** [aspnet/Mvc#3254]
If I run my project in Debug mode using IISExpress env.IsDevelopment() is true and Environment is "Development"

If I run the same thing switching to use the web command (Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001) then it is "Production"

**Comment by davidfowl** [comment]
This is by design. The default is Production (see https://github.com/aspnet/Home/issues/712). If you want to set it to Development then set the environment variable `ASPNET_ENV=Development`
