### ISSUE TITLE
IRuntimeEnvironment wrong in web

### ISSUE THREAD

**Issue by angelsix** [aspnet/Mvc#3255]
If starting the application using the web command instead of IIS, as well as my previously mentioned issue with env.IsDevelopment(), it appears the OperatingSystemVersion is wrong too.

I output details using the following...
$"OS: {runtime.OperatingSystem} ({runtime.OperatingSystemVersion}) ARC: {runtime.RuntimeArchitecture} Type: {runtime.RuntimeType} V{runtime.RuntimeVersion}"

Running Windows 10 and through IISExpress I get:

OS: Windows (10.0.10240.0) ARC: x86 Type: CLR V1.0.0-beta7-15532

Running through web (Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001) I get:

OS: Windows (6.2.9200.0) ARC: x86 Type: CLR V1.0.0-beta7-15532

It thinks windows is version 6?

**Comment by davidfowl** [comment]
This isnt an MVC issue. Please file it on dnx

**Comment by BrennanConroy** [comment]
There is also already an issue https://github.com/aspnet/dnx/issues/2895
