### ISSUE TITLE
Register MvcCore

### ISSUE THREAD

**Issue by gvx111** [aspnet/Mvc#3256]
<pre>Severity	Code	Description	Project	File	Line
Error	CS1061	'IServiceCollection' does not contain a definition for 'AddMvcCore' and no extension method 'AddMvcCore' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	ITN.TS.Hosting.Web.DNX Core 5.0	ServiceCollectionExtensions.cs	16</pre>
Dependecy of project.json
<pre>  "dependencies": {
    "Microsoft.AspNet.Http": "1.0.0-*",
    "Microsoft.AspNet.Http.Abstractions": "1.0.0-*",
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Routing": "1.0.0-*",
    "Microsoft.Dnx.Runtime.Abstractions": "1.0.0-*",
    "Microsoft.Framework.DependencyInjection.Abstractions": "1.0.0-*",
    "Microsoft.Framework.Logging": "1.0.0-*",
  },</pre>
<pre>  services
                .AddMvcCore()
                .AddViews()
                .AddRazorViewEngine();</pre>

**Comment by rynowak** [comment]
The packages and namespaces for DI + Logging were renamed over the weekend: https://github.com/aspnet/Announcements/issues/77

**Comment by gvx111** [comment]
Yes i solved problem but i have one big problem about Unicode 
https://github.com/aspnet/Mvc/issues/3252 please help
