### ISSUE TITLE
Make ActionDescriptor accessible in IModelBinder.BindModelAsync

### ISSUE THREAD

**Issue by djanosik** [aspnet/Mvc#3257]
I've found it would be useful if we could access `ActionDescriptor` in the `IModelBinder.BindModelAsync` method. In Web API 2 there is [another parameter](https://msdn.microsoft.com/en-us/library/system.web.http.modelbinding.imodelbinder.bindmodel(v=vs.118).aspx#M:System.Web.Http.ModelBinding.IModelBinder.BindModel(System.Web.Http.Controllers.HttpActionContext,System.Web.Http.ModelBinding.ModelBindingContext)) of type `HttpActionContext`. Can you bring it back to MVC 6?

**Comment by rynowak** [comment]
What are you trying to accomplish? There's probably a better way to do it now with `ResourceFilters`

**Comment by djanosik** [comment]
I want to decide how to bind the model according to a return value of the action method.

**Comment by rynowak** [comment]
Fixed by 0832365ec264df06e6c601079eece81dd7516daf

`context.OperationBindingContext.ActionContext.ActionDescriptor` - we hope to simplify it more than this, but it's possible for now.
