### ISSUE TITLE
Why Startup class doesn't implement generic interface?

### ISSUE THREAD

**Issue by Yorie** [aspnet/Mvc#3258]
The question is why Startup class, that is automatically created from Visual Studio project template for vNext projects, doesn't implement any interface?

Of course, in simple application it is not required, because it is enough to have one startup class for project.
But if I want to use some (let's say it is abstract) modular system, I would like to create startup classes for each module I implement to be able to initialize each module in the way vNext does.
So, I don't want to remember all startup methods and their arguments, and wouldn't it be nice to just implement startup interface (or even base class to support constructor signature?).
Of course I can create similar interface manually, but shouldn't it be part of framework?

And it is just feeling that Startup class should implement interface or inherited from base class.

**Comment by pranavkm** [comment]
Please file this issue in https://github.com/aspnet/Hosting
