### ISSUE TITLE
Add client-side validation support for DataTypeAttribute

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#327]
Some of the data type options in http://msdn.microsoft.com/en-us/library/cc679282(v=vs.110).aspx are already supported via the sub types. We should add support for these

**Comment by dougbu** [comment]
made subject more specific since we have server-side validation adapters and those seem to be working

**Comment by Eilon** [comment]
No action here. These attributes are to specify data type, not validation. They don't validate on the server, so we shouldn't make them validate on the client.
