### ISSUE TITLE
Diagnostics Source events for View Components

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Mvc#3274]
Originally we had intended to show child actions. View Components are the successor to what child actions where intended to do and we would like to have Diagnostics Source events for the "action"/component resolution and corresponding view resolution.

// @rynowak @Eilon

**Comment by rynowak** [comment]
Would love to see more detail about what this would look like and what kinds of things you expect users to troubleshoot/understand with this experience.

**Comment by avanderhoorn** [comment]
As demonstrated by the various View Components in [MusicStore](https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/Components/CartSummaryComponent.cs#L30-L34), I think it is imagined that a good percentage of users will be doing some sort of out-of-proc work in these (probably mainly db stuff) and because of that it makes sense to show them what is causing that work to occur and what the result it. Hence shoring which View Component have executed, what happened within them and what resulted is really useful. Given this, we would like a before/after for the View Component itself and then for the "view" that results from that. Does that make sense/help?
