### ISSUE TITLE
Setting up project.json file correctly in VS Code Mono

### ISSUE THREAD

**Issue by snapbatch** [aspnet/Mvc#3278]
Im a long time .NET developer but new to using VS Code on my Mac. I am trying to setup references in the project.json file but keep recieving missing ref errors. I am trying different things, but I guess it would help to understand what are all of the tartget frameworks that I can add in my Frameworks Section? I looked on the web and noticied "net45","dnx451","dnx50", etc. but what do they all mean and is there a website that simple explains each Framework I can choose?

Secondly I am very confused at where to actually put the reference?? I have a .net 4.5.1 project that I am converting. I am just putting them in different places and not truly understanding what I am doing. Sometimes it works sometimes it doesnt, but I am not learning. For example one of my Classes has uses the Math.Round function and I cant compile because it says the name 'Math' does not exist in the current context. 

To summarize. Can anyone tell me or share a link about the different frameworks I can choose in my project.json file Framework section? And where do I properly put the reference. For example "System" because system.math is not working. 

My project.json file

        {
        "version": "1.0.0-*",
        "webroot": "wwwroot",
        "packExclude": [
            "**.kproj",
            "**.user",
            "**.vspscc",
            "**.config",
            "**.csproj"
        ],
        "dependencies": {
            "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
            "Microsoft.AspNet.Hosting": "1.0.0-*",
            "Microsoft.AspNet.Mvc": "5.2.3",
            "Microsoft.AspNet.Server.IIS": "1.0.0-*",
            "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
            "Microsoft.AspNet.StaticFiles": "1.0.0-*",
            "Microsoft.Owin": "3.0.1",
            "Microsoft.Owin.Cors": "3.0.1",
            "Microsoft.Owin.Host.SystemWeb": "3.0.1",
            "Microsoft.Owin.Security": "3.0.1",
            "Microsoft.Owin.Security.Cookies": "3.0.1",
            "Microsoft.Owin.Security.OAuth": "3.0.1",
            "Microsoft.AspNet.Cors": "5.2.3",
            "Microsoft.AspNet.Identity.Core": "2.2.0",
            "Microsoft.AspNet.Identity.Owin": "2.2.0",
            "Microsoft.AspNet.Razor": "3.2.3",
            "Microsoft.AspNet.Web.Optimization": "1.1.3",
            "Microsoft.AspNet.WebApi.Client": "5.2.3",
            "Microsoft.AspNet.WebApi.Core": "5.2.3",
            "Microsoft.AspNet.WebApi.Cors": "5.2.3",
            "Microsoft.AspNet.WebApi.HelpPage": "5.2.3",
            "Microsoft.AspNet.WebApi.WebHost": "5.2.3",
            "Microsoft.AspNet.WebPages": "3.2.3",
            "Newtonsoft.Json": "6.0.8"
        },
        "commands": {
            "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
            "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5004"
        },
        "frameworks": {
            "net45": { 
                "frameworkAssemblies": {
                    "System": "4.0.0-*",
                    "System.IO": "4.0.0-*"
                }
            },
            
            "dnx451": {
                "compilationOptions": {//I dont even know what this means
                    "define": [
                        "ASYNC"//This either. Why?? I just seen it online
                    ],
                    "warningsAsErrors": true
                },
                "dependencies": {
                    "System.Net.Http":"4.0.0-*",
                    
                   
                    "Tools": "0.0-*",
                    "BL": "0.0-*"
                },
                "frameworkAssemblies": {
                    
                    "System.Drawing": "4.0.0-*",
                    "System.Web": "4.0.0-*",
                    "System.Net": "4.0.0-*",
                    "System.Xml": "4.0.0-*",
                    "System.Core": "4.0.0-*",
                    "System.Xml.Linq": "4.0.0-*",
                    "System.Configuration": "4.0.0-*",
                    "System.Runtime": "4.0.0-*",
                    "System.Net.Http.WebRequest":"4.0.0-*"                
                }
            }
        }
    }

Errors I am receiving
Application startup exception: Microsoft.Dnx.Compilation.CSharp.RoslynCompilationException: /Users/MY/Desktop/Ci/core/ApiSite/Classes/ImageHelper.cs(8,3): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Flags' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Global.asax.cs(50,32): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Global.asax.cs(50,32): DNX,Version=v4.5.1 error CS0122: 'AsyncMessageProcessor.Dispose(bool)' is inaccessible due to its protection level
/Users/MY/Desktop/Ci/core/ApiSite/Classes/ApiRequestLoggingHandler.cs(49,33): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'HttpRequest' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/ApiRequestLoggingHandler.cs(49,33): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'HttpRequestBase' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/ApiRequestLoggingHandler.cs(49,50): DNX,Version=v4.5.1 error CS1503: Argument 1: cannot convert from 'System.Web.HttpRequest' to 'Microsoft.Owin.IOwinRequest'
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(89,67): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(87,46): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(37,10): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(42,10): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(47,10): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(52,10): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(57,10): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(72,10): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(77,10): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(144,9): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(146,26): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/AppContext.cs(146,26): DNX,Version=v4.5.1 error CS0122: 'ServiceContext.Dispose(bool)' is inaccessible due to its protection level
/Users/MY/Desktop/Ci/core/ApiSite/Classes/ImageHelper.cs(94,15): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'InvalidOperationException' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/ImageHelper.cs(160,8): DNX,Version=v4.5.1 error CS0103: The name 'Math' does not exist in the current context
/Users/MY/Desktop/Ci/core/ApiSite/Classes/ImageHelper.cs(161,8): DNX,Version=v4.5.1 error CS0103: The name 'Math' does not exist in the current context
/Users/MY/Desktop/Ci/core/ApiSite/Classes/ImageHelper.cs(167,21): DNX,Version=v4.5.1 error CS0103: The name 'Math' does not exist in the current context
/Users/MY/Desktop/Ci/core/ApiSite/Classes/ImageHelper.cs(169,22): DNX,Version=v4.5.1 error CS0103: The name 'Math' does not exist in the current context
/Users/MY/Desktop/Ci/core/ApiSite/Classes/UploadedImageProvider.cs(83,11): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/UploadedImageProvider.cs(83,11): DNX,Version=v4.5.1 error CS1674: 'ServiceContext': type used in a using statement must be implicitly convertible to 'System.IDisposable'
/Users/MY/Desktop/Ci/core/ApiSite/Classes/UploadedImageProvider.cs(85,26): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Disposable' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/OAuth/ApiOAuthAuthorizationServerProvider.cs(68,43): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'HttpRequest' could not be found (are you missing a using directive or an assembly reference?)
/Users/MY/Desktop/Ci/core/ApiSite/Classes/OAuth/ApiOAuthAuthorizationServerProvider.cs(68,43): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'HttpRequestBase' could not be found (are you missing a using directive or an assembly reference?)

**Comment by davidfowl** [comment]
> Im a long time .NET developer but new to using VS Code on my Mac. I am trying to setup references in the project.json file but keep recieving missing ref errors

Yep, I don't blame you for being confused. Visual Studio hid a bunch of concepts from .NET developers in general. The new project system exposes some of the things that were always there but they're not in your face. Things are further complicated by the fact that we support both .NET Framework and .NET Core in the same project by default. csproj based projects today only support a single target so each of those frameworks sections would map to a different csproj file normally. Another thing that most people are unaware of is the nuspec fields, project.json is basically a projection of a nuspec file to json (with extra stuff for compiling projects):

Here's the nuspec file for Microsoft.Extensions.Logging

```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>Microsoft.Framework.Logging</id>
    <version>1.0.0-rc1-15644</version>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <description>Logging infrastructure.</description>
    <dependencies>
      <group targetFramework=".NETFramework4.5">
        <dependency id="Microsoft.Framework.DependencyInjection.Abstractions" version="1.0.0-rc1-15644" />
        <dependency id="Microsoft.Framework.Logging.Abstractions" version="1.0.0-rc1-15644" />
      </group>
      <group targetFramework="DNX4.5.1">
        <dependency id="Microsoft.Framework.DependencyInjection.Abstractions" version="1.0.0-rc1-15644" />
        <dependency id="Microsoft.Framework.Logging.Abstractions" version="1.0.0-rc1-15644" />
      </group>
      <group targetFramework="DNXCore5.0">
        <dependency id="Microsoft.Framework.DependencyInjection.Abstractions" version="1.0.0-rc1-15644" />
        <dependency id="Microsoft.Framework.Logging.Abstractions" version="1.0.0-rc1-15644" />
        <dependency id="System.Collections.Concurrent" version="4.0.11-beta-23326" />
        <dependency id="System.Collections" version="4.0.11-beta-23326" />
        <dependency id="System.ComponentModel" version="4.0.1-beta-23326" />
        <dependency id="System.Globalization" version="4.0.11-beta-23326" />
        <dependency id="System.Linq" version="4.0.1-beta-23326" />
        <dependency id="System.Threading" version="4.0.11-beta-23326" />
      </group>
      <group targetFramework=".NETPlatform5.0">
        <dependency id="Microsoft.Framework.DependencyInjection.Abstractions" version="1.0.0-rc1-15644" />
        <dependency id="Microsoft.Framework.Logging.Abstractions" version="1.0.0-rc1-15644" />
        <dependency id="System.Collections" version="4.0.10" />
        <dependency id="System.Diagnostics.Debug" version="4.0.10" />
        <dependency id="System.Linq" version="4.0.0" />
        <dependency id="System.Resources.ResourceManager" version="4.0.0" />
        <dependency id="System.Runtime" version="4.0.20" />
        <dependency id="System.Runtime.Extensions" version="4.0.10" />
        <dependency id="System.Threading" version="4.0.10" />
        <dependency id="System.Threading.Tasks" version="4.0.10" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Collections.Concurrent" targetFramework="DNX4.5.1" />
      <frameworkAssembly assemblyName="mscorlib" targetFramework="DNX4.5.1" />
      <frameworkAssembly assemblyName="System" targetFramework="DNX4.5.1" />
      <frameworkAssembly assemblyName="System.Core" targetFramework="DNX4.5.1" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework="DNX4.5.1" />
    </frameworkAssemblies>
  </metadata>
</package>
```

Here's the project.json

```JSON

{
    "version": "1.0.0-*",
    "authors": ["Microsoft"],
    "owners": ["Microsoft"],
    "description": "Logging infrastructure.",
    "repository": {
        "type": "git",
        "url": "git://github.com/aspnet/logging"
    },
    "dependencies": {
        "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-*",
        "Microsoft.Extensions.Logging.Abstractions": "1.0.0-*"
    },
    "compilationOptions": {
        "define": [
            "TRACE"
        ]
    },
    "frameworks": {
        "net45": {
            "frameworkAssemblies": {
                "System.Collections.Concurrent": { "version": "", "type": "build" }
            }
        },
        "dnx451": {
            "frameworkAssemblies": {
                "System.Collections.Concurrent": ""
            }
        },
        "dnxcore50": {
            "dependencies": {
                "System.Collections.Concurrent": "4.0.11-beta-*",
                "System.Collections": "4.0.11-beta-*",
                "System.ComponentModel": "4.0.1-beta-*",
                "System.Globalization": "4.0.11-beta-*",
                "System.Linq": "4.0.1-beta-*",
                "System.Threading": "4.0.11-beta-*"
            }
        },
        "dotnet": {
            "dependencies": {
                "System.Collections": "4.0.10",
                "System.Diagnostics.Debug": "4.0.10",
                "System.Linq": "4.0.0",
                "System.Resources.ResourceManager": "4.0.0",
                "System.Runtime": "4.0.20",
                "System.Runtime.Extensions": "4.0.10",
                "System.Threading": "4.0.10",
                "System.Threading.Tasks": "4.0.10"
            }
        }
    }
}
```

> I am trying different things, but I guess it would help to understand what are all of the tartget frameworks that I can add in my Frameworks Section? I looked on the web and noticied "net45","dnx451","dnx50", etc. but what do they all mean and is there a website that simple explains each Framework I can choose?

The frameworks section comes from NuGet and .NET in general. Before .NET Core, you could target different frameworks and different versions of those frameworks, net45 - .NET Framework 4.5, sl5 - Silverlight 5.0, wp8 - Windows Phone 8 etc. The full list of targets isn't really documented anywhere yet but will be. For now, there's some good info on Oren's blog https://oren.codes/2015/06/09/pcls-net-core-dnx-and-uwp/.

> Secondly I am very confused at where to actually put the reference?? I have a .net 4.5.1 project that I am converting. I am just putting them in different places and not truly understanding what I am doing. Sometimes it works sometimes it doesnt, but I am not learning. For example one of my Classes has uses the Math.Round function and I cant compile because it says the name 'Math' does not exist in the current context.

This one is hard to explain without some context on .NET Core but since you're targeting .NET 4.5.1 only it should map pretty well to whatever you had before. I'd suggest starting with an empty project and adding dependencies one by one and seeing when things break. 

There are 2 types of references:

**frameworkAssemblies** - When using the dnx45x or net4x monikers these are assemblies that are in the framework. Think of it as things in the GAC. If you use Visual Studio, and you click add reference, you'll see that dialog you'd be familiar with:

**dependencies** - Can be a package or project dependency. This is just a nuget package or a project.

The problem you're having is that you're porting your existing ASP.NET application but you're using all of the existing package, none of the new ones. Those existing packages don't work on dnx451 so you're seeing compilation errors. Most of the dependencies described in your project.json don't work and you should be using the newer packages when porting older code.

http://docs.asp.net/en/latest/

**Comment by snapbatch** [comment]
Thanks @davidfowl this is very helpful. I am looking forward to learning more today and playing around with it to get it to work. By the way. You have some big fans out here in the Cleveland Ohio area and really enjoy your work and help to the community!
