### ISSUE TITLE
System.InvalidOperationException: Unable to load application or execute command 'Microsoft.AspNet.Hosting'

### ISSUE THREAD

**Issue by snapbatch** [aspnet/Mvc#3282]
I am having issues launching my Web API .NET 4.5.1 site on my mac (Yosemite). @davidfowl helped me understand a little more about the various targets that can be used in a project.json. I was able to download the example website and run it fine on my machine. 

First issue. In the example project they have the  "Microsoft.AspNet.Hosting": "1.0.0-*" in the project dependencies, but when I load our project (dnx kestrel) I get the error message (Not sure why): 
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   Microsoft.AspNet.Hosting 1.0.0-rc1-15710

Second issue. I can pass the error above if I add the Microsoft.AspNet.Hosting ref in the "dotnet" framework dependencies, but I receive the error message (Assuming that the project does not know how to run application because I did not provide Hosting ref globally on project):
```
System.InvalidOperationException: Unable to load application or execute command 'Microsoft.AspNet.Hosting'. Available commands: web, kestrel.
  at Microsoft.Dnx.ApplicationHost.Program.ThrowEntryPointNotfoundException (Microsoft.Dnx.Runtime.DefaultHost host, System.String applicationName, System.Exception innerException) <0x107303d20 + 0x001c5> in <filename unknown>:0 
```

Here is my project.json. 
```
{
    "version": "1.0.0-*",
    "webroot": "wwwroot",
    "packExclude": [
        "**.kproj",
        "**.user",
        "**.vspscc"
    ],
    "dependencies": {},
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
        "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5004"
    },
    "frameworks": {
        "dotnet": {
            "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
            "Microsoft.AspNet.Server.IIS": "1.0.0-*",
            "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
            "Microsoft.AspNet.StaticFiles": "1.0.0-*",
            "Microsoft.AspNet.Hosting": "1.0.0-*",
            "Microsoft.AspNet.Cors": "5.2.3",
            "Microsoft.Owin": "3.0.1",
            "Microsoft.Owin.Cors": "3.0.1",
            "Microsoft.Owin.Host.SystemWeb": "3.0.1",
            "Microsoft.Owin.Security": "3.0.1",
            "Microsoft.Owin.Security.Cookies": "3.0.1",
            "Microsoft.Owin.Security.OAuth": "3.0.1",
            "Microsoft.AspNet.Identity.Core": "2.2.0",
            "Microsoft.AspNet.Identity.Owin": "2.2.0",
            "Microsoft.AspNet.Razor": "3.2.3",
            "Microsoft.AspNet.Web.Optimization": "1.1.3",
            "Microsoft.AspNet.WebApi.Client": "5.2.3",
            "Microsoft.AspNet.WebApi.Core": "5.2.3",
            "Microsoft.AspNet.WebApi.Cors": "5.2.3",
            "Microsoft.AspNet.WebApi.HelpPage": "5.2.3",
            "Microsoft.AspNet.WebApi.WebHost": "5.2.3",
            "Microsoft.AspNet.WebPages": "3.2.3",
            "Newtonsoft.Json": "6.0.8"
        },
        "net45": {
            "dependencies": {
               
                "Tools": "0.0-*",
                "BL": "0.0-*"
            },
            "frameworkAssemblies": {
                "System": "4.0.0-*",
                "System.IO": "4.0.0-*",
                "System.Drawing": "4.0.0-*",
                "System.Web": "4.0.0-*",
                "System.Net": "4.0.0-*",
                "System.Xml": "4.0.0-*",
                "System.Core": "4.0.0-*",
                "System.Xml.Linq": "4.0.0-*",
                "System.Configuration": "4.0.0-*",
                "System.Runtime": "4.0.0-*",
                "System.Net.Http.WebRequest": "4.0.0-*"
            }
        },
        "dnxcore50": {
            "dependencies": {}
        }
    }
}
```

**Comment by rynowak** [comment]
You should remove `"Microsoft.AspNet.Server.IIS": "1.0.0-*",` - this isn't supported anymore in RC1.

You can also safely remove the reference to `"Microsoft.AspNet.Hosting": "1.0.0-*",` - this will already be pulled in by the various server implementations.

Do a `dnu restore` followed by `dnu list` at the commandline. Are there any errors during restore? Look at the output of `dnu list` are there any 'mixed' packages? For anything that you're using a `*` in the version string, you should expect to see a version ending with `rc1-<build#>`.

**Comment by snapbatch** [comment]
Hi @rynowak 

I removed the two reference's noted above and ran dnu list and received the following list:

Framework references:
  fx/Microsoft.CSharp 4.0.0.0
  fx/mscorlib 4.0.0.0
  fx/System 4.0.0.0
  fx/System.Configuration 4.0.0.0
  fx/System.Core 4.0.0.0
  fx/System.Drawing 4.0.0.0
  fx/System.IO 4.0.0.0
  fx/System.Net 4.0.0.0
  fx/System.Net.Http.WebRequest 4.0.0.0
  fx/System.Runtime 4.0.0.0
  fx/System.Web 4.0.0.0
  fx/System.Xml 4.0.0.0
  fx/System.Xml.Linq 4.0.0.0

Project references:
  BL 1.0.0
  Tools 1.0.0

**Comment by rynowak** [comment]
did you do `dnu restore`?

**Comment by snapbatch** [comment]
Yes I restored first then list. The project is a Target 4.5.1 WebApi. 

I am now getting a bunch of errors when trying to launch such as DNX,Version=v4.5.1 error CS0518: Predefined type 'System.Int32' is not defined or imported

Here is the updated project.json file:

{
    "version": "1.0.0-*",
    "webroot": "wwwroot",
    "packExclude": [
        "**.kproj",
        "**.user",
        "**.vspscc"
    ],
    "dependencies": {},
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
        "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5004"
    },
    "frameworks": {

        "net45": {
            "dependencies": {
               
              
            },
            "frameworkAssemblies": {
                "System": "4.0.0-*",
                "System.IO": "4.0.0-*",
                "System.Drawing": "4.0.0-*",
                "System.Web": "4.0.0-*",
                "System.Net": "4.0.0-*",
                "System.Net.Http.WebRequest": "4.0.0.0",
                "System.Xml": "4.0.0-*",
                "System.Core": "4.0.0-*",
                "System.Xml.Linq": "4.0.0-*",
                "System.Configuration": "4.0.0-*",
                "System.Runtime": "4.0.0.0"
            }
        },
        "dnx451": {
            "dependencies": {
                "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
                "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
                "Microsoft.AspNet.StaticFiles": "1.0.0-*",
                "Microsoft.AspNet.Cors": "5.2.3",
                "Microsoft.Owin": "3.0.1",
                "Microsoft.Owin.Cors": "3.0.1",
                "Microsoft.Owin.Host.SystemWeb": "3.0.1",
                "Microsoft.Owin.Security": "3.0.1",
                "Microsoft.Owin.Security.Cookies": "3.0.1",
                "Microsoft.Owin.Security.OAuth": "3.0.1",
                "Microsoft.AspNet.Identity.Core": "2.2.0",
                "Microsoft.AspNet.Identity.Owin": "2.2.0",
                "Microsoft.AspNet.Razor": "3.2.3",
                "Microsoft.AspNet.Web.Optimization": "1.1.3",
                "Microsoft.AspNet.WebApi.Client": "5.2.3",
                "Microsoft.AspNet.WebApi.Core": "5.2.3",
                "Microsoft.AspNet.WebApi.Cors": "5.2.3",
                "Microsoft.AspNet.WebApi.HelpPage": "5.2.3",
                "Microsoft.AspNet.WebApi.WebHost": "5.2.3",
                "Microsoft.AspNet.WebPages": "3.2.3",
                "Newtonsoft.Json": "6.0.8",
                "Microsoft.CSharp": "4.0.0.0",
                  "Tools": "0.0-*",
                "BL": "0.0-*"
            },
            "frameworkAssemblies": {
                "System": "4.0.0-*",
                "System.IO": "4.0.0-*",
                "System.Drawing": "4.0.0-*",
                "System.Web": "4.0.0-*",
                "System.Net": "4.0.0-*",
                "System.Net.Http.WebRequest": "4.0.0.0",
                "System.Xml": "4.0.0-*",
                "System.Core": "4.0.0-*",
                "System.Xml.Linq": "4.0.0-*",
                "System.Configuration": "4.0.0-*",
                "System.Runtime": "4.0.0.0"
            }
            
        },
        "dnxcore50": {
            "dependencies": {}
        }
    }
}

**Comment by snapbatch** [comment]
dnu list:

Package references:
  Antlr 3.4.1.9004
  Microsoft.AspNet.Cors 5.2.3
  Microsoft.AspNet.FileProviders.Abstractions 1.0.0-rc1-15651
  Microsoft.AspNet.FileProviders.Physical 1.0.0-rc1-15651
  Microsoft.AspNet.Hosting 1.0.0-rc1-15710
  Microsoft.AspNet.Hosting.Abstractions 1.0.0-rc1-15710
  Microsoft.AspNet.Hosting.Server.Abstractions 1.0.0-rc1-15710
  Microsoft.AspNet.Http 1.0.0-rc1-15662
  Microsoft.AspNet.Http.Abstractions 1.0.0-rc1-15662
  Microsoft.AspNet.Http.Extensions 1.0.0-rc1-15662
  Microsoft.AspNet.Http.Features 1.0.0-rc1-15662
  Microsoft.AspNet.Identity.Core 2.2.0
  Microsoft.AspNet.Identity.Owin 2.2.0
  Microsoft.AspNet.Mvc 5.2.3
  Microsoft.AspNet.Razor 3.2.3
  Microsoft.AspNet.Server.Kestrel 1.0.0-rc1-15731
  Microsoft.AspNet.Server.WebListener 1.0.0-rc1-15692
  Microsoft.AspNet.StaticFiles 1.0.0-rc1-15683
  Microsoft.AspNet.Web.Optimization 1.1.3
  Microsoft.AspNet.WebApi.Client 5.2.3
  Microsoft.AspNet.WebApi.Core 5.2.3
  Microsoft.AspNet.WebApi.Cors 5.2.3
  Microsoft.AspNet.WebApi.HelpPage 5.2.3
  Microsoft.AspNet.WebApi.WebHost 5.2.3
  Microsoft.AspNet.WebPages 3.2.3
  Microsoft.AspNet.WebUtilities 1.0.0-rc1-15662
  Microsoft.CSharp 4.0.0
  Microsoft.Dnx.Compilation.Abstractions 1.0.0-rc1-15798
  Microsoft.Dnx.Runtime.Abstractions 1.0.0-rc1-15798
  Microsoft.Framework.Configuration 1.0.0-rc1-15666
  Microsoft.Framework.Configuration.Abstractions 1.0.0-rc1-15666
  Microsoft.Framework.Configuration.Binder 1.0.0-rc1-15666
  Microsoft.Framework.Configuration.CommandLine 1.0.0-rc1-15666
  Microsoft.Framework.Configuration.EnvironmentVariables 1.0.0-rc1-15666
  Microsoft.Framework.Configuration.FileExtensions 1.0.0-rc1-15666
  Microsoft.Framework.Configuration.Json 1.0.0-rc1-15666
  Microsoft.Framework.DependencyInjection 1.0.0-rc1-15644
  Microsoft.Framework.DependencyInjection.Abstractions 1.0.0-rc1-15644
  Microsoft.Framework.Logging 1.0.0-rc1-15644
  Microsoft.Framework.Logging.Abstractions 1.0.0-rc1-15644
  Microsoft.Framework.OptionsModel 1.0.0-rc1-15642
  Microsoft.Framework.Primitives 1.0.0-rc1-15685
  Microsoft.Framework.WebEncoders 1.0.0-rc1-15662
  Microsoft.Framework.WebEncoders.Core 1.0.0-rc1-15662
  Microsoft.Net.Http.Headers 1.0.0-rc1-15662
  Microsoft.Net.Http.Server 1.0.0-rc1-15692
  Microsoft.Net.WebSockets 1.0.0-rc1-15692
  Microsoft.Owin 3.0.1
  Microsoft.Owin.Cors 3.0.1
  Microsoft.Owin.Host.SystemWeb 3.0.1
  Microsoft.Owin.Security 3.0.1
  Microsoft.Owin.Security.Cookies 3.0.1
  Microsoft.Owin.Security.OAuth 3.0.1
  Microsoft.Web.Infrastructure 1.0.0.0
  Newtonsoft.Json 6.0.8
  Owin 1.0
  System.Diagnostics.Tracing.Telemetry 4.0.0-beta-23326
  System.Globalization 4.0.0
  System.Numerics.Vectors 4.1.1-beta-23326
  System.Resources.ResourceManager 4.0.0
  System.Runtime 4.0.0
  System.Runtime.Extensions 4.0.0
  System.Threading 4.0.0
  WebGrease 1.5.2

Project references:
  BL 1.0.0
  Tools 1.0.0

**Comment by rynowak** [comment]
I'd suggest simplifying things down to the absolute minimum while porting, and then building from there. If `dnu restore` and `dnu list` aren't happy, then your site isn't going to run.

A few things that I'm doing here:
- Removed other configurations besides dnx451, you can add in dnxcore50 later when your dependencies support it. You don't really ever need to build this project for net45 since it's a web app.
- Moving 'common' dependencies to the top-level dependencies node. These are things that aren't part of the CLR. 
- Omitting version numbers for framework assemblies, just not needed. 

Here's an edit to give you and idea:
```
{
    "version": "1.0.0-*",
    "webroot": "wwwroot",
    "packExclude": [
        "**.kproj",
        "**.user",
        "**.vspscc"
    ],
    "dependencies": {},
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
        "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5004"
    },
    "dependencies": {
                "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
                "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
                "Microsoft.AspNet.StaticFiles": "1.0.0-*",
                "Newtonsoft.Json": "6.0.8",
                "Tools": "0.0-*",
                "BL": "0.0-*"
    },
    "frameworks": {
        "dnx451": {
            "dependencies": {
                "Microsoft.AspNet.Cors": "5.2.3",
                "Microsoft.Owin": "3.0.1",
                "Microsoft.Owin.Cors": "3.0.1",
                "Microsoft.Owin.Host.SystemWeb": "3.0.1",
                "Microsoft.Owin.Security": "3.0.1",
                "Microsoft.Owin.Security.Cookies": "3.0.1",
                "Microsoft.Owin.Security.OAuth": "3.0.1",
                "Microsoft.AspNet.Identity.Core": "2.2.0",
                "Microsoft.AspNet.Identity.Owin": "2.2.0",
                "Microsoft.AspNet.Razor": "3.2.3",
                "Microsoft.AspNet.Web.Optimization": "1.1.3",
                "Microsoft.AspNet.WebApi.Client": "5.2.3",
                "Microsoft.AspNet.WebApi.Core": "5.2.3",
                "Microsoft.AspNet.WebApi.Cors": "5.2.3",
                "Microsoft.AspNet.WebApi.HelpPage": "5.2.3",
                "Microsoft.AspNet.WebApi.WebHost": "5.2.3",
                "Microsoft.AspNet.WebPages": "3.2.3"
            },
            "frameworkAssemblies": {
                "Microsoft.CSharp": "",
                "System": "",
                "System.IO": "",
                "System.Drawing": "",
                "System.Web": "",
                "System.Net": "",
                "System.Net.Http.WebRequest": "",
                "System.Xml": "",
                "System.Core": "",
                "System.Xml.Linq": "",
                "System.Configuration": "",
                "System.Runtime": ""
            }   
        }
    }
}
```

Your big project here is to get rid of the dependency on `System.Web`. You can't reasonably expect anything from `System.Web` or that uses `System.Web` to work in vNext. Drop references to the WebAPI packages and use `"Microsoft.AspNet.Mvc": "6.0.0-*"`. You might want to start out using the WebAPI compat package as a porting aid -> https://github.com/aspnet/Mvc/tree/dev/test/WebSites/WebApiCompatShimWebSite

So that would include things like `Microsoft.AspNet.WebApi.WebHost`, and `Microsoft.AspNet.WebPages`. Owin middleware in general can work with an adapter since they don't depend on `System.Web`.

**Comment by snapbatch** [comment]
@rynowak I removed everything even the dnx451 depends and framassem, I run the app and seems like it doesnt even know what a System.String one of the hundreds of errors is  CS0518: Predefined type 'System.String' is not defined or imported. I assume if that can be fixed I am going in the right direction. Any suggestions on how to simply recognize a string?'

r/UserDataFactory.cs(80,58): DNX,Version=v4.5.1 error CS0518: Predefined type 'System.String' is not defined or imported
/r/UserDataFactory.cs(84,13): DNX,Version=v4.5.1 error CS0518: Predefined type 'System.Boolean' is not defined or imported
/r/UserDataFactory.cs(87,8): DNX,Version=v4.5.1 error CS0518: Predefined type 'System.Object' is not defined or imported

**Comment by rynowak** [comment]
>  I removed everything even the dnx451 depends and framassem

What does your project.json look like now?

**Comment by snapbatch** [comment]
@rynowak I am going by 1 by 1 and adding dependencies. My current project.json file is below, but how do I handle ambiguous errors in in the project.json file:
 DNX,Version=v4.5.1 error CS0121: The call is ambiguous between the following methods or properties: 'System.Net.Http.HttpRequestMessageExtensions.CreateErrorResponse(System.Net.Http.HttpRequestMessage, System.Net.HttpStatusCode, string)' and 'System.Net.Http.HttpRequestMessageExtensions.CreateErrorResponse(System.Net.Http.HttpRequestMessage, System.Net.HttpStatusCode, string)'

How does things like System.Math and Disposable references cant be found?
DNX,Version=v4.5.1 error CS0103: The name 'Math' does not exist in the current context

Lastly it seems that I am missing a ton of ASPNET reference like ViewBag,View,AreaRegistration,etc

{
    "version": "1.0.0-*",
    "webroot": "wwwroot",
    "packExclude": [
        "**.kproj",
        "**.user",
        "**.vspscc"
    ],
    "dependencies": {
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
        "Microsoft.AspNet.StaticFiles": "1.0.0-*",
        "Newtonsoft.Json": "6.0.8",
        "Microsoft.AspNet.Mvc": "6.0.0-*",
        "Microsoft.AspNet.Mvc.WebApiCompatShim": "6.0.0-*",
        "Microsoft.Owin": "3.0.1",
        "Microsoft.Owin.Cors": "3.0.1",
        "Microsoft.Owin.Host.SystemWeb": "3.0.1",
        "Microsoft.Owin.Security": "3.0.1",
        "Microsoft.Owin.Security.Cookies": "3.0.1",
        "Microsoft.Owin.Security.OAuth": "3.0.1",
        "Microsoft.AspNet.Cors": "5.2.3",
        "Microsoft.AspNet.Identity.Core": "2.2.0",
        "Microsoft.AspNet.Identity.Owin": "2.2.0",
        "Microsoft.AspNet.Razor": "3.2.3",
        "Microsoft.AspNet.Web.Optimization": "1.1.3",
        "Microsoft.AspNet.WebApi.Client": "5.2.3",
        "Microsoft.AspNet.WebApi.Core": "5.2.3",
        "Microsoft.AspNet.WebApi.Cors": "5.2.3",
        "Microsoft.AspNet.WebApi.HelpPage": "5.2.3",
        "Microsoft.AspNet.WebApi.WebHost": "5.2.3",
        "Microsoft.AspNet.WebPages": "3.2.3",
        "Tools": "0.0-*",
        "BL": "0.0-*"
    },
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
        "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5004"
    },
    "frameworks": {

        "dnx451": {
            "dependencies": {},
            "frameworkAssemblies": {
                "System.Web": "",
                "System.Drawing": "",
                "System.Math":
            }
        }
    }
}

**Comment by rynowak** [comment]
You're getting ambiguities because you have all those WebAPI 5.x packages included. 

You should remove those, as well as:
- `Microsoft.AspNet.WebPages`
- `Microsoft.Owin.Host.SystemWeb`
- `Microsoft.AspNet.Web.Optimization`
- `Microsoft.AspNet.Razor`

You can keep `Microsoft.AspNet.WebApi.Client`

**Comment by snapbatch** [comment]
@rynowak my framework includes sys.web.http. Why am I getting the following error:
The name 'Ok' does not exist in the current context

I am using the IHttpActionResult interface. It uses the system.web.http namespace. I see this alot throughout the error list. 

"frameworks": {

        "dnx451": {
            "dependencies": {},
            "frameworkAssemblies": {
                "System.Web.Http":""

            }
        }
    }

**Comment by rynowak** [comment]
> sys.web.http

`System.Web.Http` is the namespace used by older version of WebAPI. The compat shim package defines a few types there for compatibility, but expect a lot of things to have moved to `Microsoft.AspNet.Mvc`.

> I am using the IHttpActionResult interface. It uses the system.web.http namespace. I see this alot throughout the error list.

Do a find and replace with `IActionResult`. We've merged concepts from WebAPI and MVC where they are compatible.

**Comment by snapbatch** [comment]
Ok great. I fixed all of the reference issues. One last thing( I hope) when trying to launch the app I get an error:
Application startup exception: System.InvalidOperationException: A method named 'ConfigureProduction' or 'Configure' in the type 'CAe.Startup' could not be found.
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindMethod (System.Type startupType, System.String methodName, System.String environmentName, System.Type returnType, Boolean required) in <filename unknown>:line 0
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindConfigureDelegate (System.Type startupType, System.String environmentName) in <filename unknown>:line 0
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.LoadMethods (System.Type startupType, IList`1 diagnosticMessages) in <filename unknown>:line 0
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup () in <filename unknown>:line 0
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices () in <filename unknown>:line 0
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication () in <filename unknown>:line 0

**Comment by rynowak** [comment]
That seems pretty self-explanatory.. This is what startup code looks like in vNext: https://github.com/aspnet/Mvc/blob/dev/samples/MvcSample.Web/Startup.cs

**Comment by snapbatch** [comment]
@rynowak How come its not setup in https://github.com/aspnet/Home/blob/dev/samples/latest/HelloWeb/Startup.cs ?

**Comment by snapbatch** [comment]
Also @rynowak I made some changes but I keep receiving the following errors:

What dependency do I need for IApplicationBuilder and IServiceCollection

Application startup exception: Microsoft.Dnx.Compilation.CSharp.RoslynCompilationException: /Users/MoMoney/Desktop/Crexi/core/ApiSite/Startup.cs(25,22): DNX,Version=v4.5.1 error CS1061: 'IServiceCollection' does not contain a definition for 'AddMvc' and no extension method 'AddMvc' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)
/Users/MoMoney/Desktop/Crexi/core/ApiSite/Startup.cs(41,4): DNX,Version=v4.5.1 error CS1929: 'IApplicationBuilder' does not contain a definition for 'UseCors' and the best extension method overload 'CorsExtensions.UseCors(IAppBuilder, CorsOptions)' requires a receiver of type 'IAppBuilder'
/Users/MoMoney/Desktop/Crexi/core/ApiSite/Startup.cs(46,4): DNX,Version=v4.5.1 error CS1929: 'IApplicationBuilder' does not contain a definition for 'UseOAuthAuthorizationServer' and the best extension method overload 'OAuthAuthorizationServerExtensions.UseOAuthAuthorizationServer(IAppBuilder, OAuthAuthorizationServerOptions)' requires a receiver of type 'IAppBuilder'
/Users/MoMoney/Desktop/Crexi/core/ApiSite/Startup.cs(47,4): DNX,Version=v4.5.1 error CS1929: 'IApplicationBuilder' does not contain a definition for 'UseOAuthBearerAuthentication' and the best extension method overload 'OAuthBearerAuthenticationExtensions.UseOAuthBearerAuthentication(IAppBuilder, OAuthBearerAuthenticationOptions)' requires a receiver of type 'IAppBuilder'

**Comment by rynowak** [comment]
It would help immensely if you would post your project.json **again** each time if you've made changes but are still having errors.

`IServiceCollection` is in the `Microsoft.Extensions.DependencyInjection` namespace, `IApplicationBuilder` is in `Microsoft.AspNet.Builder` and both of these should be referenced if you are referencing `Microsoft.AspNet.Mvc`.

For the second set of errors, those are coming from trying to use the OWIN extensions with the vNext `IApplicationBuilder`. I'd suggest dropping those for now and taking a look at the equivalent functionality we have in the new platform. 
https://github.com/aspnet/Cors
https://github.com/aspnet/security

**Comment by snapbatch** [comment]
@rynowak thanks. I ended up using the Microsoft.AspNet.Builder and Microsoft.Framework.DependencyInjection; to get to work.
