### ISSUE TITLE
RenderSection("sectionname")) is not working properly

### ISSUE THREAD

**Issue by danilodeven** [aspnet/Mvc#3283]
When I want to ignore a section and a body in asp.net 4 on the layout.cshtml page I just write: 
WriteTo(TextWriter.Null, RenderSection("sectionname"));  // works fine
WriteTo(TextWriter.Null, RenderBody()); // works fine

In asp.net 5 beta 7 this works with RenderBody() but not with  RenderSection.
WriteTo(TextWriter.Null, RenderBody()) // works fine
WriteTo(TextWriter.Null, RenderSection("sectionname"));  // don't work - this keep render

**Comment by danroth27** [comment]
It is odd that calling WriteTo with a null TextWriter somehow manages to still render the section - we can take a look as to why that is happening, but calling WriteTo directly isn't something we would recommend. Instead could you put conditional logic around your RenderBody and RenderSection calls? Note you will need to render _something_, either the body or at least one section.

**Comment by pranavkm** [comment]
See: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorPage.cs#L898-L900

We write to the current page Output. An alternative would be to switch the Output out:
```C#
var oldOutput = Output;
Output = TextWriter.Null;
RenderSection("sectionname");
Output = oldOutput;
```

**Comment by danilodeven** [comment]
I use the "section" to make various versions of the views using the same "layout.cshtml" for different browsers, users, permissions and requests types with the same controller and model. Yes, I could put the logic around the RenderSection calls, but would be much more neat if I could somehow "cancel the section" in the layout.cshtml (like I already do in asp.net 4.5) to use the condition logic just once instead of repeat this logic in all *.cshtml files.

**Comment by Eilon** [comment]
Using an alternate writer for rendering sections is definitely not a supported scenario. Neither is resetting the value of the `Output` property.

It sounds like there's a different feature request here: Suppressing the requirement to render the body and/or particular sections.

The problem with all the code samples is that the section/body **will run** and that can have many undesirable side effects.

**Comment by danilodeven** [comment]
it would be better if it doesn't give the exception and just doesn't render the section:
```c#
@if (someLogicIsFalseHere) {
    RenderSection("adminMenu");
}
```
### An unhandled exception occurred while processing the request.
###### InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_Layout.cshtml': 'adminMenu'.

**Comment by Eilon** [comment]
Right, so it sounds like the real request here is much simpler: allow suppressing certain errors. Would you mind opening a new bug that calls out the specific *scenario* we have? I don't think we'll be making changes to enable changing the writers - they're really intended to be plumbing for Razor and could likely change at any time...

**Comment by danilodeven** [comment]
Done! It is in issue https://github.com/aspnet/Mvc/issues/3293

**Comment by Eilon** [comment]
Awesome, thanks! I think the new bug is something we can look into, so closing this bug.
