### ISSUE TITLE
Support 'defaults' with [action] syntax for attribute routes

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3286]
We built a lovely feature to do token replacement on attribute route templates. This will end up generating routes like the following:

```
[Route("[controller]/[action]/{id?}")]
public class HomeController
{
    // Equivalent to [Route("Home/Index/{id?}")]
    public IActionResult Index()
    {
    }

    // Equivalent to [Route("Home/About/{id?}")]
    public IActionResult About()
    {
    }
}
```

The suggestion is that we allow 'defaults' in these tokens like this:

```
[Route("[controller]/[action=Index]/{id?}")]
public class HomeController
{
    // Equivalent to [Route("Home")]
    // Equivalent to [Route("Home/Index/{id?}")]
    public IActionResult Index()
    {
    }

    // Equivalent to [Route("Home/About/{id?}")]
    public IActionResult About()
    {
    }
}
```

**Comment by NeelBhatt** [comment]
Very nice. So after that no need to register for default routes in startup.cs I guess!!

**Comment by rynowak** [comment]
@NeelBhatt - these are alternatives, and many people prefer one or the other for their own reasons :+1: 

Using attribute routes gives you more precise controller over the URL space, but is often more verbose and usually means putting attributes in your controller classes which some people don't like for code-organization reasons.

Using conventional routes (in startup code) is terse and broad and is the way most old school MVC users are used to doing it.


This change is a suggestion to bring some of the terseness of the 'conventional route' way for a pretty common usage pattern.

**Comment by NeelBhatt** [comment]
Okay I got your point and you explained it very nicely :+1:  I have used both previously and I prefer attribute routing as per my experience. But as you said, it totally depends on people's preference.

**Comment by Eilon** [comment]
This doesn't look quite right to me. An entire segment is never omitted from the route. I think that if anything, the attribute route behavior for defaults should be:

```c#
[Route("[controller]/[action=Index]/{id?}")]
public class HomeController
{
    // Equivalent to [Route("Home")] - if the "action" segment is omitted, all subsequent segments must be omitted
    // Equivalent to [Route("Home/Index/{id?}")]
    public IActionResult Index()
    {
    }

    // Equivalent to [Route("Home/About/{id?}")]
    public IActionResult About()
    {
    }
}
```

However, I think that though this behavior would make sense, it's perhaps not super useful because you can achieve 99% of that by declaring this attribute route:

```c#
[Route("[controller]/{action=Index}/{id?}")] // 'action' is a regular parameter
public class HomeController
{
    ...
}
```

The only thing that's different about this compared to my previous example is that it would allow *any* `action` value, so you'd have to constrain it to `Index|About|Contact|...`.

But, having said that, I'm not sure how useful this feature is...

**Comment by rynowak** [comment]
>  it's perhaps not super useful because you can achieve 99% of that by declaring this attribute route

This is explicitly not allowed. You can't use **any** action-selection tokens (`{contoller}`, `{action}`) as parameters in an attribute route.

**Comment by Eilon** [comment]
Ah, well, then nix that :smile: 

But we still have different ideas about what the behavior should be regarding omitted sections. Let's chat tomorrow if it's not clear.

**Comment by rynowak** [comment]
> But we still have different ideas about what the behavior should be regarding omitted sections. Let's chat tomorrow if it's not clear.

That was a mistake, I corrected it in my sample.

**Comment by Eilon** [comment]
Oh, great, because @danroth27 and I were freaking out about that :smile: Well, @danroth27 was being rather patient and *I* was freaking out! :laughing: Not only that, but all the rest of my diatribe no longer makes any sense :trollface: 

So, yeah, now that we all agree about what the feature even is, it's certainly an interesting one.

**Comment by rynowak** [comment]
You should visit Arizona. It's relaxing. :cactus: :cactus: :cactus: :cactus: :cactus: :cactus: :cactus: :cactus:

**Comment by Eilon** [comment]
That sounds like a thorny situation.

**Comment by NeelBhatt** [comment]
This is funny! :) The only real mistake is the one from which we learn nothing. ;)

**Comment by Eilon** [comment]
Moving to backlog.

**Comment by rynowak** [comment]
Just a reminder - I still like this idea.

**Comment by rynowak** [comment]
It's been about 11 months since I last bumped this thread. This item is elegant and cool and I think we should do it.

**Comment by NeelBhatt** [comment]
I still like this idea :)

**Comment by jeff-pang** [comment]
+1

**Comment by mkArtakMSFT** [comment]
@rynowak, will this be a good fit for 2.2?

**Comment by rynowak** [comment]
IMO this is a p3 for dispatcher. If we get an chance to do it, then that would be awesome - but I can't imagine us cutting other work to make this fit.

**Comment by mkArtakMSFT** [comment]
@JamesNK, seems like another issue to be handled as part of the dispatcher work. Will you create a new issue in the routing repo, or just move this one?
