### ISSUE TITLE
Authorize Doesnt work

### ISSUE THREAD

**Issue by gvx111** [aspnet/Mvc#3287]
Authorize attribute doesn't work 
I have parent controller like this

```c#
 [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        protected string AreaName { get; set; }
        protected AdminController()
        {
            AreaName = "Areas/Administrator";
        }
    }
```

**Comment by Eilon** [comment]
What exactly doesn't work? Does the attribute work if you put it on the specific controller (e.g. one that derives from `AdminController`)?

**Comment by gvx111** [comment]
doesn't check user is authorized and if user is in role. AdminController is Parent Controller;
<pre>public class Dashboard : AdminController{
}
and admincontroller has anttribute  [Authorize(Roles = "Administrator")]
</pre>

**Comment by danroth27** [comment]
@blowdart

**Comment by blowdart** [comment]
@HaoK @kichalla  does authorize inherit?

**Comment by HaoK** [comment]
Authorize should be combining all of the attributes into one policy (a sort of union of all of the attributes), which results in an AND of all the requirements...  if that makes sense to anyone but me :)

**Comment by blowdart** [comment]
We have tested inheritance and Authorize works for us as expected.

What authentication method are you using? What creates your identity?

**Comment by gvx111** [comment]
ASPNET.Identity 
Method: Cookie
@blowdart

**Comment by blowdart** [comment]
OK, in that case, assuming you're using the default templates, something strange is going on. Can you post a repo of the stripped down project please so we can see the problem in action?

**Comment by kichalla** [comment]
@gvx111 Could you share a repro?

**Comment by gvx111** [comment]
which repro? @kichalla

**Comment by kichalla** [comment]
@gvx111 we are not able to repro the inheritance issue that you are mentioning so checking if you can share a repro project

**Comment by gvx111** [comment]
It's framework 10 Projects. I can share class:
<pre> [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        protected string AreaName { get; set; }
        protected Guid CurrentSiteId { get; set; }
        protected string SiteName { get; set; }

        protected AdminController(IActionContextAccessor context, IShellSettingsManager manager)
        {
            ActionContext = context.ActionContext;
            AreaName = RouteData.Values["area"].ToString();
            SiteName = context.ActionContext.RouteData.Values.ContainsKey("siteid")
                ? context.ActionContext.RouteData.Values["siteid"].ToString().ToLower()
                : "";
            CurrentSiteId = (manager.LoadSettings().Any(e => e.Name.ToLower() == SiteName) ? Guid.Parse(manager.LoadSettings().First(e => e.Name.ToLower() == SiteName).SiteId) : Guid.Empty);

        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            if (!context.HttpContext.User.Identity.IsAuthenticated)
            {
                context.Result = new RedirectToRouteResult(new RouteValueDictionary(new { action = "Index", controller = "Login" }));
            }
        }

        protected IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Dashboard");
            }
        }</pre>
and 
<pre> public class DashboardController : AdminController
    {
        private IShellSettingsManager _shellSettingsManager;

        public DashboardController(IActionContextAccessor httpcontext, IShellSettingsManager shellSettingsManager) : base(httpcontext, shellSettingsManager)
        {
            _shellSettingsManager = shellSettingsManager;
        }
    
    }</pre>

**Comment by kichalla** [comment]
@gvx111 Ok, I am not exactly clear what you are mentioning here, but following is what I have tried now and it does check if the user is in role

- Create a new Web Application project in VS 2015 (I tested this with Beta8 tooling)
- Replace the code in `Controller\AccountController.cs`'s `Register` action with the following(you may need to resolve namespaces)...here I am just using the Register action to create a user in administrator role if the user being registered has a user name `admin@admin.com`
  ```
[HttpPost]
[AllowAnonymous]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Register(RegisterViewModel model)
{
    EnsureDatabaseCreated(_applicationDbContext);
    if (ModelState.IsValid)
    {
        ApplicationUser user;

        if (model.Email.ToLowerInvariant() == "admin@admin.com")
        {
            const string adminRole = "Administrator";
            var userManager = HttpContext.RequestServices.GetRequiredService<UserManager<ApplicationUser>>();
            var roleManager = HttpContext.RequestServices.GetRequiredService<RoleManager<IdentityRole>>();
            if (!await roleManager.RoleExistsAsync(adminRole))
            {
                await roleManager.CreateAsync(new IdentityRole(adminRole));
            }

            user = await userManager.FindByNameAsync(model.Email);
            if (user == null)
            {
                user = new ApplicationUser { UserName = model.Email };
                var result = await userManager.CreateAsync(user, model.Password);
                await userManager.AddToRoleAsync(user, adminRole);
                await userManager.AddClaimAsync(user, new Claim("ManageStore", "Allowed"));
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }
        else
        {
            user = new ApplicationUser { UserName = model.Email, Email = model.Email };
            var result = await _userManager.CreateAsync(user, model.Password);
            if (result.Succeeded)
            {
                // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=532713
                // Send an email with this link
                //var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                //var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: HttpContext.Request.Scheme);
                //await _emailSender.SendEmailAsync(model.Email, "Confirm your account",
                //    "Please confirm your account by clicking this link: <a href=\"" + callbackUrl + "\">link</a>");
                await _signInManager.SignInAsync(user, isPersistent: false);
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            AddErrors(result);
        }
    }

    // If we got this far, something failed, redisplay form
    return View(model);
}
  ```
- Create following controllers
  ```
[Authorize(Roles = "Administrator")]
public class AdminController : Controller
{

}

public class DashboardController : AdminController
{
    public IActionResult Index()
    {
        return Content("Hello!", contentType: "text/plain");
    }
}
  ```
- Create the admin user using `admin@admin.com` username and you should be able to hit `http://localhost:<port>/dashboard/index` successfully and get a `Hello!` message.
- Create another user, for example:`test@test.com` username and you should be seeing access denied error when accessing `http://localhost:<port>/dashboard/index`message.

**Comment by gvx111** [comment]
can you give me your skype or mail address? I will show details of my code.
my email: givi.bibi@Yahoo.com
@kichalla

**Comment by kichalla** [comment]
Sure kiranchalla@hotmail.com

**Comment by kichalla** [comment]
Closing this as we cannot repro it. If you still see the issue, please send us a repro project.
