### ISSUE TITLE
We need some null checks in Controller

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3289]
I tried this:
`public IActionResult TestFile => File((string)null, "text/plain");` and it failed with 

![image](https://cloud.githubusercontent.com/assets/174281/10382220/9131b6ec-6dd6-11e5-80c0-a9695e04be4f.png)

**Comment by ryanbrandenburg** [comment]
Looks like this was fixed in 3a876e38 if I'm reading the bug right, @pranavkm was the branch you saw this on up to date?

**Comment by Eilon** [comment]
Ah, interesting, so this particular exception already throws an ArgNullException?

**Comment by pranavkm** [comment]
This was beta8 code - so maybe the NotNull checks weren't in?

**Comment by Eilon** [comment]
Yes, but oddly you filed the bug *after* you made the NotNull change :smile:

**Comment by ryanbrandenburg** [comment]
Sounds like we're all in agreement that this is fixed, shall I close it as norepro?

**Comment by pranavkm** [comment]
I'm ok with the current state. However we do have some inconsistencies in terms of where the ArgNull occurs. For instance:

* https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/Controller.cs#L1020-L1023
* https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/Controller.cs#L608-L611

perform null checks wen invoked versus the vast majority expect the underlying code to do it.

**Comment by ryanbrandenburg** [comment]
@Eilon I think what we're getting at here is trying to decide whether we want to make null checks at every level of functions that call each other for safety and to get a slimmer stacktrace, or if we want to only check something at it's lowest possible level so as not to have the top of a function be crowded by null checks when a callee below is going to do that work anyway. Thoughts?

**Comment by Eilon** [comment]
Eh, I think at this point we can take it from direct customer feedback, like the ViewResult thing. So, perhaps no extra work to do here at this point.

**Comment by ryanbrandenburg** [comment]
K, closing it out then.
