### ISSUE TITLE
PhysicalFileResult should not throw FileNotFoundExceptions for non-rooted paths

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3295]
Based on discussions here - https://github.com/aspnet/Mvc/issues/3290#issuecomment-146992010

It's confusing for Mvc to throw a FileNotFoundException. Instead we should throw InvalidOperation or NotSupported so it's clear that the `PhysicalFileResult` does not support non-rooted paths.

**Comment by ryanbrandenburg** [comment]
Fixed in #3308
