### ISSUE TITLE
Default Route not working.

### ISSUE THREAD

**Issue by Fosol** [aspnet/Mvc#3299]
I can't get default routes working for the life of me.  The route works if I enter the full URL, but it doesn't automatically go there if I just hit the root path...

# global.json
`"sdk": {
    "version": "1.0.0-beta6",
    "runtime": "clr",
    "architecture": "x86"
  }`

# project.json
```
"dependencies": {
    "Microsoft.AspNet.Loader.IIS": "1.0.0-beta6",
    "Microsoft.AspNet.Loader.IIS.Interop": "1.0.0-beta6",
    "Microsoft.AspNet.Hosting": "1.0.0-beta6",
    "Microsoft.AspNet.Html.Abstractions": "1.0.0-beta6",
    "Microsoft.AspNet.Identity": "3.0.0-beta6",
    "Microsoft.AspNet.Mvc": "6.0.0-beta6",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta6",
    "Microsoft.AspNet.Razor": "4.0.0-beta6",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta6",
    "Microsoft.Framework.Configuration": "1.0.0-beta6",
    "Microsoft.Framework.Configuration.EnvironmentVariables": "1.0.0-beta6",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta6"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --config hosting.ini"
  },

  "frameworks": {
    "dnx451": { }
  },
```

# Startup.cs
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}");
            });
}
```

# HomeController.cs
```
[Route("[controller]")]
public class HomeController : Controller
{
        [HttpGet]
        [Route("[action]")]
        public ViewResult Index()
        {
            return View();
        }
}
```

**Comment by Eilon** [comment]
The attribute routes (`[Route(...)]`) on your controller/action indicate that the `HomeController.Index` action will respond *only* to `/Home/Index`. You'll need to remove the attribute route to allow the conventional route (`routes.MapRoute(...)`) to take effect.

**Comment by Fosol** [comment]
So if I use the Route attribute it ignores the configuration in the Startup?

**Comment by Fosol** [comment]
Is there a way to still name my controllers outside of convention (i.e. HomeController) and they will still use the configuration in the Startup?

**Comment by Fosol** [comment]
Thanks for the answer.  Now I know why it didn't work!

**Comment by dougbu** [comment]
@Fosol sounds like you've figured things out. Do you still need an answer to a question above? If not please close this issue.
