### ISSUE TITLE
The property with a FromServicesAttribute cannot be null

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Mvc#3301]
The actions of the controller will return nothing if the property with a FromServicesAttribute and it cannot be get from the service provider.

**Comment by rynowak** [comment]
This should throw an exception if the service cannot be found.

Do you have the developer error page set up in your app?
https://github.com/aspnet/Diagnostics/blob/dev/samples/DeveloperExceptionPageSample/Startup.cs#L10

**Comment by dougbu** [comment]
This scenario isn't something we've tested. I created a PR (#3303) filling that gap.

The system is likely not configured correctly when a `[FromServices]` property cannot be bound and an `InvalidOperationException` is sensible by default. But we don't currently have a way to treat a `[FromServices]` property as optional. @Kagamine were you hoping for something like `[FromServices(Optional = true)]`?

@rynowak @Eilon should we consider this issue as a potential future enhancement?

**Comment by Kagamine** [comment]
+1 for Optional = true

**Comment by Eilon** [comment]
If it's optional, why have it as a class-level property? Just bind it as an action parameter on the method that needs it, no?

**Comment by Kagamine** [comment]
In this, I created a BaseController to include these services, but sometimes, some service cannot be solved.

**Comment by Eilon** [comment]
You could acquire the services as `IEnumerable<T>` and check if you got zero or more. So far, that's been the design of the DI. All services are always required. If you want zero or more, you can use an `IEnumerable<T>` and check how many you got.

**Comment by dougbu** [comment]
FYI I updated PR #3303 to ensure we don't break `[FromServices]` with `IEnumerable<TService>` properties in the future.

@Kagamine has this resolved your issue?

**Comment by Kagamine** [comment]
I have changed it into get { return Resolver.GetService<IXXX>(); }

**Comment by dougbu** [comment]
FYI tests are in RC1 (2e2043f).

**Comment by rynowak** [comment]
@Eilon - agreed, we discussed optionality for this feature and didn't want to promote the pattern.
