### ISSUE TITLE
How to make FromJsonAttribute for GET request ?

### ISSUE THREAD

**Issue by ZOXEXIVO** [aspnet/Mvc#3302]
In past version of ASP.NET MVC, I use FromJsonAttribute for my query objects, that use stateless queries from queryString
When I start writing this in vnext version i confused. How to do it ? Fortmatters use FromBody attribute.

```c#
[HttpGet]
public async Task<IActionResult> List([FromJsonUri]QueryObject query)
{
}
```

**Comment by dougbu** [comment]
@ZOXEXIVO neither MVC 5 nor Web API 3 contain a `FromJsonAttribute` or `FromJsonUriAtttribute` class. Are you using an extension such as that discussed on StackOverflow: http://stackoverflow.com/questions/9846158/knockout-and-mvc3-posting-json-to-action-serializing-twice-cant-convert-to-c ?

**Comment by ZOXEXIVO** [comment]
Yes, but my question about using vnext notation for CustomModelBinderAttribute

It use System.Web.Http.ModelBinding, but I want use pure MVC vnext conception

**Comment by dougbu** [comment]
@ZOXEXIVO `System.Web.Http.ModelBinding` doesn't mix with MVC 6. So you're on the right track.

In MVC 6, use `[ModelBinder(BinderType = typeof(JsonModelBinder))]`.

**Comment by ZOXEXIVO** [comment]
Sorry, but it is not usable. We need attribute with GetBinder method, please (like in System.Wen.Http)
And what about access to IServiceCollection in binder ?

**Comment by danroth27** [comment]
Can you please also clarify what your scenario looks like? What does the request look like and what do you want to action method to look like?

**Comment by ZOXEXIVO** [comment]
We use MVC as WebAPI host Single Page Application with AngularJs.
We have many methods for display stateless grids with difficult many-object dynamic filters with select2, sub-objects e.t.c
All filters store in angular query object, that we serialize and request server with it. We need get requests like this and we happy with this experience,
Yes, we can use [ModelBinder(BinderType = typeof(JsonModelBinder))]. but its looks like bad.

http://ovolime.com/transactions/list?query={q: 'abc', organization: { id: 'd34efwe....', name: 'sadasd'}, category: { id: 3}} 

[HttpGet]
public async Task<IActionResult> List([FromJsonUri]TransactionQueryObject query)
{
}

Some spec object for each grid
public class TransactionQueryObject : QueryObject
{
       public ClassifierDto Category { get; set; } 
       ...........
}

Thank you

**Comment by Eilon** [comment]
@ZOXEXIVO just copy the code from https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinderAttribute.cs into your own attribute type, but explicitly set the `BinderType` property to your custom model binder type.

**Comment by ZOXEXIVO** [comment]
Eilon, Thank you!
