### ISSUE TITLE
Question: Areas in WebAPI

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Mvc#3304]
Now when WebAPI and regular Mvc controllers is merged, will it be possible to use the AreaRegistration to split WebAPI controllers into areas?

**Comment by Eilon** [comment]
Should be. If you try something and it doesn't work let us know!

**Comment by danroth27** [comment]
Yup, this is now supported. Web API controllers and MVC controllers both use the same infrastructure in MVC 6. Just add `AreaAttribute` to your Web API controller and add an area route. See http://docs.asp.net/projects/mvc/en/latest/controllers/areas.html for more details.
