### ISSUE TITLE
Can team please help me  working with localization?

### ISSUE THREAD

**Issue by pokakhoaitay** [aspnet/Mvc#3309]
Hi every one,
I am current need implement localization in my project. I follow this example https://github.com/aspnet/Mvc/tree/dev/test/WebSites/LocalizationWebSite but it's too little infomation about new localization implement in MVC. How can I understand about new implement of localization in MVC and how can I apply it to my project right way?
Thanks!

**Comment by kirthik** [comment]
Could you please describe your scenario? What you are trying to do?

**Comment by danroth27** [comment]
@tomarcher

**Comment by pokakhoaitay** [comment]
My scenario is very simple, i am implementing multilanguage for my project using resource file, I want to do something like this: 
http://mysite.com/en/my-page  -> for my page display in English language
and
http://mysite.com/vi/my-page  -> for my page display in Vietnamese language

How can I do that in MVC 6? Because it seems in MVC 6 we are working with resource file in new way!!?

**Comment by TomArcher** [comment]
There are some exciting new localization abilities that I’m currently documenting. That article will be done in the next week or so.

Here’s how to use language-specific views:

1.	Add the following to Startup.ConfigureServices
services.AddMvc().AddViewLocalization();

2.	Add the following to Startup.Configure 
app.UseRequestLocalization();

3.	Create views with format of <action>.<locale>.cshtml

Here’s how to use language-specific subfolders for your views:

1.	Add the following to Startup.ConfigureServices
services.AddMvc().AddViewLocalization(LanguageViewLocationExpanderFormat.SubFolder);

2.	Add the following to Startup.Configure 
app.UseRequestLocalization();

3.	Create subfolder with locale name, that contains your views for that language.
For example: Home->fr-FR->Index.cshtml

**Comment by danroth27** [comment]
To specifically support specifying the current culture using the URI path you will need to do some custom work. Out of the box we provide request culture providers based on the Accept-Language header, a value in the query string and a cookie. If you want to specify the current culture using a value from the URI path you will need to implement a custom IRequestCultureProvider that parses the URI path. Note you will also need to account for the culture path segment in your routes.

**Comment by pokakhoaitay** [comment]
Thank you and team for your helpful information. I will try that. And I am waiting for documents too.
Keep your awesome works.
Good working day!!
