### ISSUE TITLE
AspNet does not exist

### ISSUE THREAD

**Issue by di48l069** [aspnet/Mvc#3312]
Hi can someone please assist me with problem its affecting all my MVC projects not just the one im about show you see image below

![asp](https://cloud.githubusercontent.com/assets/7794777/10447301/af1d5e30-7183-11e5-962a-c0a5f64cd9ee.PNG)

I have googled this error and tried all the solutions they do not work.

**Comment by danroth27** [comment]
Can you share your project with us so that we can take a look?

**Comment by di48l069** [comment]
@danroth27 i could share my project with you but its affecting all my mvc projects not just the one

what could be the cause of that?

Is there anything i can install to fix it

I can invite you to my project

**Comment by NeelBhatt** [comment]
@di48l069 It would be nice if you create a sample project step by step and try to figure out what is causing above issue. If you can not find then just put your sample code in Github and provide link here!

**Comment by di48l069** [comment]
@NeelBhatt Even if create a create a sample project the problem still there, could it be my visual studio?

**Comment by danroth27** [comment]
Go ahead and send us your simple project and we'll take a look. 

It could be that you are just having issues with restoring packages. If you look in the output window in VS and select "Package Manager" from the "Show output from:" drop down what do you see?

Also, if you try to restore packages manually from the command line using `dnu restore` what happens?

It would be great if you could share with us the output of:
- `dnx -- version`
- `dnu feeds list`

**Comment by di48l069** [comment]
@NeelBhatt here is the sample project you asked for started a fresh project and problem still ther https://github.com/di48l069/SampleProject

Where do i type those commands i tried typing them in package console it just throws errors

**Comment by danroth27** [comment]
To setup command-line support for DNX and ASP.NET 5 after installing VS do the following:
- Open the "Developer Command Prompt for VS2015"
- Run `dnvm setup` and then `dnvm upgrade`

You should then be able to run `dnx --version` and `dnu feeds list` from any command prompt. You should the `dnu` command from the same folder as your project.json file.

**Comment by di48l069** [comment]
Okay @danroth27  ran those commands in dev console

C:\Program Files (x86)\Microsoft Visual Studio 14.0>dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-beta7-15532
 Type:         CLR
 Architecture: x86
 OS Name:      Windows
 OS Version:   6.2.9200.0


C:\Program Files (x86)\Microsoft Visual Studio 14.0>dnu feeds list
Feeds in use:
    https://www.nuget.org/api/v2/
      Origin: C:\Users\Nico Travassos\AppData\Roaming\NuGet\NuGet.Config
    https://api.nuget.org/v3/index.json [Disabled]
      Offical NuGet Source, enabled by default

NuGet Config files in use:
    C:\Users\Nico Travassos\AppData\Roaming\NuGet\NuGet.Config

**Comment by di48l069** [comment]
My Nuget.config  in  C:\Users\xxxx\AppData\Roaming\NuGet looks like below

```
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <disabledPackageSources>
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
</configuration>
```
