### ISSUE TITLE
Beta8: Many tag helpers added to completion for elements with restricted children

### ISSUE THREAD

**Issue by vkichline** [aspnet/Mvc#3314]
1. Create an MVC6 project with beta8
2. Open any MVC page
3. Type a tag wich take a specific set of children, like table or dl
4. Type an opening < inside the tag

*Expected Result*
Like Beta7, only show the tags specific to the context.

*Actual Result*
Beta 8:

![image](https://cloud.githubusercontent.com/assets/4530830/10468148/4e7f3fe2-71b2-11e5-8452-9d80e2d7636b.png)

![image](https://cloud.githubusercontent.com/assets/4530830/10468162/62a83244-71b2-11e5-9572-e1834393f396.png)

![image](https://cloud.githubusercontent.com/assets/4530830/10468176/7652f9f0-71b2-11e5-9125-779fec9ecb53.png)

![image](https://cloud.githubusercontent.com/assets/4530830/10468186/84bac0b8-71b2-11e5-9c77-e9b2ff83c96a.png)

**Comment by dougbu** [comment]
@madskristensen is this the same issue as what you @glennc and I were discussing offline?

**Comment by NTaylorMullen** [comment]
Talked with @ToddGrun and this is a tooling issue. There's one already logged and tracked on their end. Closing this out.
