### ISSUE TITLE
WebApi MVC 6 Model State Methods missing ex: ModelState.IsValid and AddModelError

### ISSUE THREAD

**Issue by snapbatch** [aspnet/Mvc#3315]
I am converting a ASP 4 Web Api 2 to the new Asp.Net 5. After removing the old System.Web.Http and System.Web.Http.Description and replacing those NameSpaces with Microsoft.AspNet.Mvc. Now on a simple route in my controller. I am getting an error ModelState does not contain a definition for IsValid. 

if (!ModelState.IsValid)
                 return new HttpStatusCodeResult(305);

This also happens in ModelState.AddModelError

**Comment by Eilon** [comment]
The methods are still there, and have pretty much always been there:
* `IsValid`: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Abstractions/ModelBinding/ModelStateDictionary.cs#L145
* `AddModelError`: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Abstractions/ModelBinding/ModelStateDictionary.cs#L203

**Comment by snapbatch** [comment]
@Eilon I should have mention that I do have the dependency Microsoft.AspNet.Mvc.ModelBinding; but its still giving me the error.

**Comment by pranavkm** [comment]
Is your controller type deriving from `Microsoft.Aspnet.Mvc.Controller`?

**Comment by Eilon** [comment]
Hover over the `ModelState` property and press <kbd>F12</kbd> to go to its definition. I'm guessing it's the wrong type to begin with.

**Comment by Eilon** [comment]
Also, you shouldn't have to import any namespaces to access that. If you're in a controller, you have access to it.

**Comment by snapbatch** [comment]
@pranavkm I thought that in MVC 6 there is no need for base controller classes. I received that information from a video here. https://channel9.msdn.com/Events/dotnetConf/2014/MVC-6

@Eilon I went into the definition. ModelState is using the Controller class in the namespace Microsoft.AspNet.Mvc

**Comment by snapbatch** [comment]
Ok Thanks @Eilon and @pranavkm I had to add  Microsoft.AspNet.Mvc.Controller as a base controller. If I were you guys. I would really look at taking that video down because it clearly states that in MVC6 a base class is not required. If it is required and I just misheard it wrong. The video needs to be more clear at explaining the "why". 

Thanks!

**Comment by Muchiachio** [comment]
It's not required, but if you want to use `ModelState` which is a property of `Microsoft.AspNet.Mvc.Controller`, you have to extend it.
You can't access ModelState from thin air right? :smiley:

**Comment by NeelBhatt** [comment]
@Muchiachio I guess ```ModelState``` is not a property but an instance of class ```ModelStateDictionary.cs``` which has ```IsValid``` propery.
