### ISSUE TITLE
View Components authorization

### ISSUE THREAD

**Issue by mnguyen284** [aspnet/Mvc#3318]
Previously with the use of child action, we can define authorization for the action via AuthorizeAttribute. How can we specify if authentication is required for a View Component?

**Comment by danroth27** [comment]
View Components are different than child actions in that they aren't endpoints for requests. A View Component is just a simple way to have a method that can render part of a view that you can then use in your views. If you want to have an endpoint with authorization logic you should just define a controller with the action you want.
