### ISSUE TITLE
Custom View Path

### ISSUE THREAD

**Issue by gvx111** [aspnet/Mvc#3319]
Hello,
I have custom path like "~/App_data/Sites/SiteNameExample/Templates/"
In template path exists two folder Views and Layouts 
Question: how can i make _ViewStart and _ViewImports for this paths.
I have created _ViewStart and _ViewImports in Template folder and also in Views and Layouts folder but no result.
Please help.
@rynowak

**Comment by gvx111** [comment]
Fixed.

**Comment by dougbu** [comment]
@gvx111 please let us know what was wrong in your application. The information may help others in the same situation. Or we may think of a way to make it harder for others to hit the same situation.

**Comment by gvx111** [comment]
@_ViewStart and @_ViewImport must be in parent folder or same folder. but in same folder doesn't work but in parent folder working cool. 
@dougbu

**Comment by dougbu** [comment]
Ah, sounds like you hit something similar to #3307.

**Comment by gvx111** [comment]
Yes like this 
<pre>     public IActionResult Index(string c, string a, string id = null)
        {
            if (string.IsNullOrEmpty(c) && string.IsNullOrEmpty(a) && _pageRepo.GetHomePage() != null)
            {
                var home = _pageRepo.GetHomePage();
                var path = _appDataFolder.Combine("Sites", _settings.Name, home.ViewPath);
                return View(_appDataFolder.MapPath(path));
            }
            var page = _pageRepo.Get(c, a);
            if (page == null)
            {
                if (_pageRepo.Get("404") !=null)
                {
                    return View(_appDataFolder.Combine(_rootFolder.RootPath, "Sites", _settings.Name, "Templates", _pageRepo.Get("404").ViewPath));
                }
                return Json("Error: Page Not found 404");
            }
            ViewBag.Layout = _appDataFolder.Combine(_rootFolder.RootPath, "Sites", _settings.Name, "Templates", page.LayoutPath);
            return View(_appDataFolder.Combine(_rootFolder.RootPath, "Sites", _settings.Name, "Templates", page.ViewPath));
        }</pre>
