### ISSUE TITLE
FormFileModelBinder doesn't work with dropzone.js

### ISSUE THREAD

**Issue by egorpavlikhin** [aspnet/Mvc#3322]
Dropzone.js appends [n] to each parameter name, see here: http://www.dropzonejs.com/#configuration

> The name of the file param that gets transferred. Defaults to file. NOTE: If you have the option uploadMultiple set to true, then Dropzone will append [] to the name.

https://github.com/aspnet/Mvc/blob/eef6c3883a7e27b8387b0925f0b6a88df0a484c5/src/Microsoft.AspNet.Mvc.Core/ModelBinding/FormFileModelBinder.cs#L109

This line checks for exact match between parameter name and the name on the wire, which won't match as it has [n] appened to it.

FormFileModelBinder should follow the same convention as everywhere else for enumerables, i.e. accepting multiple values with the same name, or with [], or with [n] at the end.

**Comment by SinaSoltanii** [comment]
The "Dropzone" is an open source library so you can simply modify the file "dropzone.js". All you need is just removing  the following statement:

 + (this.options.uploadMultiple ? "[]" : "") + 

The statement above is repeated 2 times in the file, so you need to remove all of them.
By doing this, the model binder will work correctly and passes all of files to the action method with parameter of type "IEnumerable<HttpPostedFileBase>". The parameter name will be the exact name as you set on the dropzone option "paramName".

I hope that it can help you..

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
