### ISSUE TITLE
Beta 7 Build / DNU restore -- fails on three test projects - "Kestrel" not found

### ISSUE THREAD

**Issue by BillKrat** [aspnet/Mvc#3323]
The following Test projects are affected (reference image below):
* mvc\tests\WebSites\ValidationWebSite
* mvc\tests\WebSites\ActionConstraintsWebSite
* mvc\tests\Microsoft.AspNet.Mvc.FunctionalTests  

_**ValidationWebSite**_ and _**ActionContraintsWebsite**_ were fixed by replacing the following in Project.json:

   **"Kestrel": "1.0.0-*"**
with
   **"Microsoft.AspNet.Server.Kestrel": "1.0.0-beta7"**

_**FunctionalTests**_ was fixed by adding
   **"Microsoft.AspNet.Server.Kestrel": "1.0.0-beta7"**

_Note: after the above updates the build fails with timeout on one test in FunctionalTests._

![Build Error](http://www.global-webnet.com/BlogEngine/Images//BuildError.png)

**Comment by pranavkm** [comment]
Thanks for noticing this
