### ISSUE TITLE
Rename ModelState (the type) -> ModelStateEntry

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3326]
See: https://github.com/aspnet/Mvc/issues/3315

`ModelState` (the type) rarely appears in user-code. Users will generally interact with the MSD directly using `AddModelError` or something similar. Seeing `ModelState` (the type) in user-code is usually a mistake. We should rename it raise our sanity level and prevent mistake-making by future generations of humans and cyborgs alike.

**Comment by Eilon** [comment]
A cyborg would never make this mistake.

**Comment by Eilon** [comment]
Done? :smile:

**Comment by dougbu** [comment]
A cyborg would never make this mistake.
