### ISSUE TITLE
How can I use Application variable in asp.net 5 & mvc 6?

### ISSUE THREAD

**Issue by fazilmajeed** [aspnet/Mvc#3328]
How can I use Application variable in asp.net 5 mvc 6? 

In asp.net 4.5, we can use HttpContext.Application.  like

Application["AppVar"] = "hello";

string appVar = HttpContext.Application["AppVar"]

Is there any way to do this in asp.net 5 ?

**Comment by davidfowl** [comment]
Nope. There is no global dictionary called application. You can store a static variable somewhere though.

**Comment by fazilmajeed** [comment]
Thank you David ,  For your confirmation about Application global dictionary in ASP.NET 5.
