### ISSUE TITLE
How we can do portable area registration in ASP.NET 5 ?

### ISSUE THREAD

**Issue by fazilmajeed** [aspnet/Mvc#3329]
How we can register or configure areas from referenced dlls?

I had done this by using mvccontrib in mvc5. 

Is there any way to do this in ASP.NET 5?

I didn't seen any official documents on areas in ASP.NET 5. Just curios to know about the areas implementation on ASP.NET 5.

**Comment by NeelBhatt** [comment]
You can use areas by giving Area name in attributes as below:

```
[Area("MyArea")]
public class HomeController : Controller
{
}
```

**Comment by davidfowl** [comment]
There's no official portable area support in ASP.NET 5

**Comment by fazilmajeed** [comment]
Do we have area support in ASP.NET 5 like  MVC 5 ?

**Comment by Muchiachio** [comment]
Yes areas are supported like in MVC5. It has a few changes like, using `AreaAttribute`, but it's basically the same.

**Comment by fazilmajeed** [comment]
I went through the sample application in github, There I noticed that, We have to specify the Area name in each of the controllers. raight ?

Suppose, if we have hundreds of controllers in an area, It is bit difficult to manage when we want to change the area name from a to b. Am I right ?

**Comment by Muchiachio** [comment]
Renaming `[Area("Administration")]` to `[Area("Admin")]`, shouldn't be too hard, knowing that the same area name is not used anywhere else.

**Comment by fazilmajeed** [comment]
If we are managing a big application with multiple areas and hundreds of controllers. 
We may want to move one controller from one area to another. 
There might be  a great  chance to make mistakes on area names.

**Comment by Muchiachio** [comment]
Wouldn't it be the same in MVC5? Moving the controller from one folder to another, but forgetting to change the namespace? I believe this solves itself with at least a little bit of testing.

**Comment by fazilmajeed** [comment]
Ya.. We should have a kind of testing on this.

**Comment by rynowak** [comment]
> There's no official portable area support in ASP.NET 5

As @davidfowl said, this is a known gap in vNext. This is something we'd like to provide guidance on how to do, and we haven't gotten there yet.

> Wouldn't it be the same in MVC5? Moving the controller from one folder to another, but forgetting to change the namespace? I believe this solves itself with at least a little bit of testing.

Namespaces have no impact on what area a controller belongs to in MVC6. 

> I went through the sample application in github, There I noticed that, We have to specify the Area name in each of the controllers by AreaAttribute. right ?

You can also author an `IControllerConvention` and configure this according to any logic you'd prefer.
```
public class AreaConvention : IControllerConvention
{
    public void Apply(ControllerModel controller)
    {
        var area = GetAreaName(controller);
        controller.RouteConstraints.Add(new AreaAttribute(area));
    }
}
```

**Comment by Eilon** [comment]
Moving to Backlog as there is no feature work planned in this area (hah-hah) for the current version.

**Comment by Eilon** [comment]
cc @danroth27 , this is your stuff!

**Comment by tupunco** [comment]
Look at this `gist`, is it helpful for you. LNK: [DefaultAreaConvention.cs](https://gist.github.com/tupunco/d4bc4bb745ed02867a6f7bb99dcb8102)
---------------------------
# ASP.NET Core Default Namespace Area Register Convention, like MVC5 AreaRegistration
## DefaultAreaConvention.cs
```csharp
using System.Text.RegularExpressions;

using Microsoft.AspNetCore.Mvc.ApplicationModels;

namespace TupMvcCore.Conventions
{
    /// <summary>
    /// Default Area Load ControllerModelConvention
    /// </summary>
    public class DefaultAreaConvention : IControllerModelConvention
    {
        private static readonly string s_Area_RouteKey = "area";
        private static readonly Regex s_Area_Reg = new Regex(@"\.Areas\.(?<area>[\w\d]+)\.Controllers\.[\w\d]+Controller$", RegexOptions.IgnoreCase);
        public void Apply(ControllerModel controller)
        {
            var rValues = controller.RouteValues;
            if (rValues.ContainsKey(s_Area_RouteKey))
                return;

            var cfName = controller.ControllerType.FullName;
            var areaMatch = s_Area_Reg.Match(cfName);
            if (!areaMatch.Success)
                return;

            var areaName = areaMatch.Groups["area"].Value;
            rValues.Add(s_Area_RouteKey, areaName);
        }
    }
}
```

## Startup.cs
```csharp
    public class Startup
    {
        //.....
        public void ConfigureServices(IServiceCollection services)
        {
            //.....
            services.AddMvc(options =>
            {
                //.....
                options.Conventions.Add(new DefaultAreaConvention());
                //.....
            });
            //.....
        }
    }
```

**Comment by danroth27** [comment]
For a full solution for doing modular development with ASP.NET Core, I highly recommend looking at the [modularity support in Orchard Core](https://github.com/OrchardCMS/OrchardCore.Samples).

**Comment by danroth27** [comment]
Given the support in Orchard Core, there are no plans to do this in ASP.NET Core.
