### ISSUE TITLE
Rename ViewComponent.Context to HttpContext

### ISSUE THREAD

**Issue by DmitrySikorsky** [aspnet/Mvc#3332]
Because now we have this property named 'HttpContext' in the Controller, so it is strange to have different name in the ViewComponent.

**Comment by Muchiachio** [comment]
And if we are on this, then [RazorPage](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorPage.cs) and [ApiController](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.WebApiCompatShim/ApiController.cs) too?

**Comment by DmitrySikorsky** [comment]
Yes. I think they all have to have some one name.

**Comment by rynowak** [comment]
For `RazorPage` and `ApiController` we need to be consistent with previous versions

**Comment by henkmollema** [comment]
:+1: this is pretty confusing at the moment: http://stackoverflow.com/q/33212908

**Comment by Eilon** [comment]
@pranavkm can you have a look at the PR and merge?

**Comment by pranavkm** [comment]
Thanks for the PR!

**Comment by henkmollema** [comment]
You're welcome :smile: 
Does this need an announcement or some other breaking change notice?

**Comment by pranavkm** [comment]
@danroth27, thoughts on the announcement question?

**Comment by rynowak** [comment]
@pranavkm Might as well make an announcement grouping all of the similar changes we did like this, it's a change affecting a very common surface area :+1:

**Comment by pranavkm** [comment]
@rynowak could you point me to the "similar changes" so I could add it to the announcement?
