### ISSUE TITLE
Changed behavior of RouteAttribute template

### ISSUE THREAD

**Issue by andrzejpindor** [aspnet/Mvc#3333]
Hi,
in 6.0.0-beta7 something like this works:

````c#
[Route("[controller]s")]

public OrganizationController(LegalContext context)
{
    ...
}

````
url was: /organizations

In 6.0.0-beta8 it stopped working - Controller isn't created and web server returns:

````http
HTTP/1.1 500 Internal Server Error
Date: Fri, 16 Oct 2015 09:25:15 GMT
Content-Length: 0
Server: Kestrel

````

Is it by design or somethings didn't work as expected?

**Comment by andrzejpindor** [comment]
Ok, strange, but it now starts working - maybe this was problem related to something else.
Sorry for the confusion.

**Comment by rynowak** [comment]
If you start seeing 500s, I strongly recommend hooking up a debugger or the error page middleware https://github.com/aspnet/Diagnostics/blob/dev/samples/DeveloperExceptionPageSample/Startup.cs#L10 so you can see what's failing.

**Comment by Eilon** [comment]
Closing for now. Please re-open or log a new bug if you see anything odd again.
