### ISSUE TITLE
Unexpected Url.Action output with areas

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#3340]
This is basically the same as #2859, it works without areas, but doesn't always work then area is used
Again this works as expected in MVC5
Given routing in beta8:
```C#
app.UseMvc(routes =>
{
    routes.MapRoute(
        "DefaultPartArea",
        "{part}/{area:exists}/{controller}/{action}/{id?}",
        new { controller = "Home", action = "Index" },
        new { part = "second" });

    routes.MapRoute(
        "DefaultArea",
        "{area:exists}/{controller}/{action}/{id?}",
        new { part = "first", controller = "Home", action = "Index" },
        new { part = "first" });

    routes.MapRoute(
        "DefaultPart",
        "{part}/{controller}/{action}/{id?}",
        new { controller = "Home", action = "Index" },
        new { part = "second" });

    routes.MapRoute(
        "Default",
        "{controller}/{action}/{id?}",
        new { part = "first", controller = "Home", action = "Index" },
        new { part = "first" });
});
```
And calling this from a controller in area with part = first
```C#
@Url.Action("Index", new { part = "second" })
```
results in
```
{empty}
```
while expected output is
```HTTP
/second/admin/accounts
```
Another strange thing is that it can form a normal url then changing from second part to first one

Repro
[Here](https://github.com/Muchiachio/InvalidSelection/archive/master.zip)

**Comment by Muchiachio** [comment]
Bump

**Comment by Eilon** [comment]
@ajaybhargavb please take a look.

**Comment by ajaybhargavb** [comment]
Thanks for reporting this and for the repro. I tried this scenario. I can confirm that there is a difference in behavior from MVC 5. Area is not picked up from AmbientValues if a segment before that has changed. MVC 5 did something different in this case. We are discussing what we should do about this scenario.

**Comment by ajaybhargavb** [comment]
cc' @Eilon @danroth27 @rynowak

**Comment by Eilon** [comment]
Hmm interesting. Yeah I do vaguely recall some special codes in MVC for areas. Though, if I had to guess, I'd be very surprised if that code didn't *inadvertently* bring this behavior to URL generation. It certainly seems to "violate" a behavior of URL generation, which is to invalidate ambient values that come after a changed parameter... but yes, let's discuss in person.

**Comment by rynowak** [comment]
> Yeah I do vaguely recall some special codes in MVC for areas.

http://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Mvc/RouteCollectionExtensions.cs

Yep. This thing again. It almost destroyed Orchard.

**Comment by ajaybhargavb** [comment]
We discussed about this. It looks like the current area behavior in MVC 5 was not the intended behavior. We have decided not to bring back the same behavior in MVC 6. To make this work you need to explicitly specify the area in the route values.
