### ISSUE TITLE
Consistent html content ToString implementation

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#3341]
Current implementation of [HtmlString] (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/Rendering/HtmlString.cs#L54) overrides `ToString` method with content return. But classes like [BufferedHtmlContent](https://github.com/aspnet/HttpAbstractions/blob/8ecb14733258afa8a8086ac8e53dc2cd0bfdf545/src/Microsoft.Extensions.BufferedHtmlContent.Sources/BufferedHtmlContent.cs#L98) are not. Wouldn't it be better if all `IHtmlContent` implementations overrode `ToString` to output their content? Or didn't override `ToString` at all?

I'm asking because I see quite a lot of devs using `IHtmlContent.ToString()` (as a legacy from MVC5), which now, given this scenario, sometimes works and sometimes doesn't. And I believe you are trying to move away from `ToString`-ing.

**Comment by Eilon** [comment]
Was `IHtmlString.ToString()` ever correct? I believe it was only ever correct to call `IHtmlString.ToHtmlString()`.

**Comment by Muchiachio** [comment]
Not sure if it "was correct", but it worked in MVC5.
I guess people tried `Html.CheckBoxFor(model => model.IsChecked).ToString()`, it worked and they kept using it. On the other hand if it didn't, they would look for `HtmlString`.

**Comment by rynowak** [comment]
`ToString()` is a fail in general because the encoder implementation is replaceable, and you won't get 'your' encoder from services using `ToString()`

What are you trying to accomplish by calling `ToString()`?

**Comment by Muchiachio** [comment]
Me nothing, I'm just saying that the framework "sometimes" allows valid to `ToString` usage, which should be removed?

**Comment by Eilon** [comment]
Yeah the tricky thing here is that the `.ToString()` implementation is more for debugability. I'd sooner change the `ToString` to say something like `return "HTML: " + ToHtmlString();` to make it effectively unusable.

**Comment by Muchiachio** [comment]
Yes @Eilon or to `DebuggerToString` like [BufferedHtmlContent](https://github.com/aspnet/HttpAbstractions/blob/8ecb14733258afa8a8086ac8e53dc2cd0bfdf545/src/Microsoft.Extensions.BufferedHtmlContent.Sources/BufferedHtmlContent.cs#L98) does.

**Comment by danroth27** [comment]
No plans to make any changes here.
