### ISSUE TITLE
Route Parameters No Longer Url Decoded

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Mvc#3342]
Is this a design change or a regression? I am seeing this in Beta8.  

``` C#
  [Route("api/values")]
  public class ValuesController : Controller
  {
    // GET: api/values
    [HttpGet]
    public JsonResult Get()
    {
      return Json(new string[] { "value1", "value2" });
    }

    // GET api/values/5
    [HttpGet("{id}")]
    public JsonResult Get(string id)
    {
      return Json(id);
    }

  }
```

For example, if I do a GET to /api/values/Hello%20World I get:

![image](https://cloud.githubusercontent.com/assets/568272/10566515/1393a6ee-75b7-11e5-9675-ea312f1ed123.png)

This is a breaking change from Beta 7. Just want to know whether I need to allow for this.

**Comment by Kukkimonsuta** [comment]
Seems more like [Kestrel](https://github.com/aspnet/KestrelHttpServer) bug - when using `Microsoft.AspNet.Server.WebListener`, everything works fine. Looks like somewhere along the like the request path gets encoded again.

**Comment by rynowak** [comment]
@shawnwildermuth - there's no intended change here, we need to look into this. @halter73

**Comment by shawnwildermuth** [comment]
@rynowak and @Kukkimonsuta - I've replicated this behavior in Beta 7 with Kestrel. Clearly that's where the problem lies. It's not a new code change. I was using WebListener and IISExpress in the course before so that's why it worked. Once I moved the Beta 7 version and tried it in Kestrel it happened. Problem a bug. /cc @halter73

**Comment by Eilon** [comment]
This is the same as https://github.com/aspnet/KestrelHttpServer/issues/124, right?

**Comment by shawnwildermuth** [comment]
@Eilon  - looks the same, as long as we'll end up in RC with an unescaped parameter values, I'm happy.

**Comment by Eilon** [comment]
Yep, we have an engineer working on it!

**Comment by troydai** [comment]
Hi @shawnwildermuth, I'm working on unescapes the Url path. As of now the fix is targeting rc1.

**Comment by shawnwildermuth** [comment]
@troydai Perfect.  Thanks!

**Comment by davidfowl** [comment]
Closing
