### ISSUE TITLE
Add LocalRedirectResult class and helper method

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#3346]
Add a new `LocalRedirectResult` class that does a redirect if `Url.IsLocalUrl` returns `true`, and throws otherwise.

Also need to add a `LocalRedirect` factory method on the Controller base class.

**Comment by Eilon** [comment]
The doc comments for the factory method and type need to mention that it helps to protect against open redirects.

@blowdart FYI

**Comment by danroth27** [comment]
@rustd Do we need this for RC1?

**Comment by rustd** [comment]
If we can. It will help clean up the template.
