### ISSUE TITLE
Reconsider behavior around clearing ModelStateDictionary errors for collections

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3360]
This comment: https://github.com/aspnet/Mvc/pull/3327#discussion-diff-42335129 led us down an interesting rabbit hole. Previous versions of MVC/WebAPI never had the code in question.

What this code does, is like a prefix like `Name` be considered a match for a key like `[0].Name`. This was changed after introducing `ModelBindingHelper.ClearValidationStateForModel(...)` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/ModelBindingHelper.cs#L709

This is called by `TryUpdateModel` to clear the existing validation state of the model we're attempting to bind.

`ModelBindingHelper.ClearValidationStateForModel(...)` tries to be precise and clear only what's going to be model-bound, but it's impossible to be precise with a collection - because you can't a priori know what indexes/keys will be used - hence the fuzzy matching that ignores an 'index' at the start of a model key.

---

My _vague_ suggestion after discussion with @dougbu is that we correct the implementation of `FindKeysWithPrefix` back to the MVC5 behavior, and rethink the problems associated with `TryUpdateModel` to do something simpler but still reasonable.

**Comment by dougbu** [comment]
My suggestion is `ClearValidationStateForModel()` should do something reasonable but not attempt perfection. In particular it should remove entries matching properties of a POCO model and _every_ entry that starts with `modelKey + "["` if the model is a collection type.

In particular, should remove the weird attempt to remove all properties of all elements of a collection that's currently in that method. That doesn't work for `int[]` for example. We're basically handling the complex case but not the simple one at the moment.

**Comment by Eilon** [comment]
Moving to backlog.

**Comment by rynowak** [comment]
This behavior was fixed in b557ca55d9f66e361b05e788cae7521c9ae72542

`ModelBindingHelper.ClearValidationState` does a best effort attempt to deal with the quirky collection cases.
