### ISSUE TITLE
Proposal - Split Model Binding into separate packages

### ISSUE THREAD

**Issue by Antaris** [aspnet/Mvc#3368]
Hi Team,

I've got a number of small projects that I am utilising a form of the model binding sub-framework from the MVC packages, examples being:

- A dynamic query engine that translates a JSON query object to a set of Linq expressions - `ModelMetadata` is used to identify string expressions which can be used to construct Linq expressions.
- A dynamic data grid that supports inline-editing - model metadata is used to understand the grid model more when generating columns, binding rules, etc.
- [FuManchu](https://github.com/Antaris/FuManchu/tree/master/src/FuManchu/Binding) my .NET implementation of Handlebars.

In each instance, I've wanted to use the same model binding/metadata framework that MVC utilises, because it's already battle tested and proved, so my approach so far has been to replicate the parts of the model binding/metadata that I need so as not to require a dependency on the MVC packages. This has the side effect of potentially running a couple of parallel `i*MetadataProviders` in memory with associated caching - which whilst the decoupling is good, there is that inherent in-efficiency because there is no shared cache space between these separate implementations.

Could a consideration be made to split the model binding parts into two new packages - maybe `Microsoft.Extensions.ModelBinding.Abstractions` and `Microsoft.Extensions.ModelBinding` to allow their use outside of the context of MVC?

**Comment by davidfowl** [comment]
@Antaris it would help if you hacked the code out yourself so that you could see what pieces you'd want to reuse. It's harder for us to split it apart without a consumer but if you have a pretty good idea of what you'd want to use then it can be used as feedback into our potential refactoring. 

PS: Model binding was split out and we put it back in because it made things harder to achieve (had to abstract types and split layering for imaginary scenarios).

**Comment by Antaris** [comment]
@davidfowl Sure thing, I'll see if I can look into a potential example over the next week, cheers for feedback :+1:

**Comment by Eilon** [comment]
At this point in time model binding is intended as a feature of MVC and not outside of it. While it might be an interesting scenario, the amount of design work to achieve that so far doesn't seem to be outweighed by the benefits.
