### ISSUE TITLE
Produced assembly reflects project folder name, not project name (beta8)

### ISSUE THREAD

**Issue by andersborum** [aspnet/Mvc#3370]
Hi,

not sure if this bug belongs in the MVC repository, but I couldn't find a better place. Please move the bug to a better location, if applicable.

Building an ASP.NET 5 project produces an assembly with the name of the project directory, not the project name. I was expecting that changing the name of the project also changed the name of the produced assembly. Regardless of this is being a bug or intentional, I think the correct behavior should be that the name of the produced assembly always reflects the name of the project.

As of beta8, the current workaround is to remove the project from the solution, rename the project folder, and add the project to the solution again (or similar approach by manually editing the solution file).

**Comment by pranavkm** [comment]
Please file this bug in https://github.com/aspnet/dnx. Seems like a dup of https://github.com/aspnet/dnx/issues/692
