### ISSUE TITLE
Link and Script tag helpers violates Content Security Policy CSP 'unsafe-inline'

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#3371]
the code rendered by the `link` and `script` tag helpers prevent the use of CSP headers.

The rendered HTML is:
```html
<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js">
            </script>
<script>(window.jQuery||document.write("<script src=\"\/lib\/jquery\/dist\/jquery.min.js\"><\/script>"));</script>
```

which will trigger this browser error 
```
Refused to load the script 'https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline'".
```

when using a header like:
```
Content-Security-Policy:default-src 'self'; script-src 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' *
```

**Comment by blowdart** [comment]
What script or link tag automatically adds jquery to the mix? That seems odd.

**Comment by DamianEdwards** [comment]
When using CSP you'll have to explicitly enable loading of JS files (and CSS files, etc.) from other domains. In this case, the templates are set up to load certain JS files from our CDN, thus you'll need to allow the CDN domain in your CSP profile, or change the CSHTML to load the JS files from your own, allowed domain name. See http://content-security-policy.com/

**Comment by Bartmax** [comment]
You are right, I misinterpreted the issue here. TH are ok! :+1:
