### ISSUE TITLE
FormCollection always null

### ISSUE THREAD

**Issue by freshe** [aspnet/Mvc#3372]
This worked in Beta7. (Maybe this is a breaking change and the expected behavior?)
FormCollection is always null. Changing it to IFormCollection solves the problem.

```html
<form method="post" action="~/Start/FormTestPost">
    <input type="hidden" name="test1" value="1" />
    <input type="hidden" name="test2" value="2" />
    <button class="btn btn-primary" type="submit">Post</button>
</form>
```

```csharp
public ActionResult FormTest()
{
        return View();
}

[HttpPost]
public ActionResult FormTestPost(FormCollection form)
{
        return RedirectToAction("FormTest");
}
```

**Comment by rynowak** [comment]
You should only reference `IFormCollection`. This was an intended change to force you to code that we won't break again in the future.

**Comment by freshe** [comment]
Thank you for clarifying
