### ISSUE TITLE
Using PrecompiledViewsCompilerCacheProvider with Multiple Dynamically Invoked Modules

### ISSUE THREAD

**Issue by ToddThomson** [aspnet/Mvc#3373]
How do we use PrecompiledViewsCompilerCacheProvider with multiple nuget packages ( each nuget package assembly type has it's own source of precompiled views )?

**Comment by ToddThomson** [comment]
Once the PrecompiledViewsCompilerCacheProvider has been activated/created with a set of assemblies containing precompiled razor views there is no method to add additional assemblies with additional precompiled razor views.
I would like to add component class library packages with controllers and precompiled views to my application. Each component then adds its precompiled views to the overall application.

**Comment by ToddThomson** [comment]
OK. I've looked through the MVC source and I can use the StaticAssemblyProvider class in my app startup sequence. Each application module ( class library package ) can then add to the provider if it supports precompiled views.
Although I've always had DI in MVC, MVC6 with ASP.NET 5 DI has allowed me to cut my code base substantially - thanks!

**Comment by Eilon** [comment]
@pranavkm @rynowak any thoughts on this? How much will this change with CLI? Still unknown?

**Comment by pranavkm** [comment]
We might change how compile modules work in CLI, but this is more about the runtime discovery of precompiled views. The current model should work - you have to know at Startup what assemblies contain views and register these. Auto discovering views from random dependencies has never been the goal.

**Comment by Eilon** [comment]
@pranavkm ok, so then would there be any further work for this issue?

**Comment by pranavkm** [comment]
@ToddThomson seems to have figured a work around. So I guess not

**Comment by ToddThomson** [comment]
@pranavkm I've written my own provider to cover my needs, so I'm fine.

**Comment by ToddThomson** [comment]
@pranavkm I now add an EmbeddedFileProvider using razor view engine options for each discovered "Plugin" in my solution ( each plugin is an asp.net core class library ).
My plugins are complete "areas" or subsets of a modular asp.net core MVC application.
Within each plugin I would also like to include "immutable" js and less/sass content files. I would like to be able to use the EmbeddedFileProvider for this purpose and have a Nuget command line extension to "manage" these embedded resources. I understand the troubles that are involved with adding content to projects, but I just cannot come to terms with have a self contained component be shipped with nuget bits and and bower/npm bits.
Can you please point me in the right direction to get started.

**Comment by davidfowl** [comment]
It's not a first class feature, all we have are building blocks and it hasn't been a scenario. If you don't get specific details to do *exactly* what you're trying to do it's because we haven't thought it through either. There's no out of the box solution for having a all facets of a component shipped as a nuget package and  consumed as part of your MVC application.
