### ISSUE TITLE
ViewLocalizer behavior

### ISSUE THREAD

**Issue by JuergenGutsch** [aspnet/Mvc#3376]
Hi All,

the ViewLocalizer behaves a little different than expected and different than announced here: http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx

> The IViewLocalizer is an IHtmlLocalizer service that looks for a resource based on the current view name. 

Reading this sentence, I would expect the "view name" is important. I see that the view name is not really unique. 
Aniway, what I really didn't expect is that the complete path **and** the whole view file name was  important to find the right resource file. At the end I have resource files with that kind of names: **Views.Home.About.cshtml.de-DE.resx** and **Views.Home.About.cshtml.en-US.resx**

Would it possibly make more sense to use a combination of controller name and view name to find the resource files like this: **Home.About.de-DE.resx** and **Home.About.en-US.resx**? Instead of using the complete file path including the file extension? 

From my perspective the current solution could be confusing in the future. What do you guys think?

Cheers,
Juergen

**Comment by SirajArMVT** [comment]
Yes It confusing 

I do not like to make one set of resx file for each view

**Comment by damienbod** [comment]
@JuergenGutsch  @SirajArMVT I've just created a global issue for this, could you give your views here?

https://github.com/aspnet/Home/issues/1142

Greetings Damien

**Comment by DamianEdwards** [comment]
Please see #3718 and #2767 for changes we're making to the `ViewLocalizer` lookup behavior. It sounds like you'd also prefer you didn't have to include the file name extension (cshtml) which I agree is clunky, so I updated the issue to reflect that too.

Remember, you can always inject an `IHtmlLocalizerFactory` directly into the view (or anywhere else) and call its `Create` method to manually specify the name you want. `IViewLocalizer` is an opinionated convenience type. You could also create your own opinionated helper type that uses whatever rules you like for constructing the resource location name based on the view, controller, action, route data, etc.
