### ISSUE TITLE
Optimize Allocations in retrieving validators

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3379]
Here's allocations from 3000 requests to an API with a very simple model (3 properties):

![image](https://cloud.githubusercontent.com/assets/1430011/10650772/1df05ad8-7800-11e5-98ec-e1dd7aff6cf0.png)

The total allocations for this sample is about 90mb, so the 3mb of allocations here is about 3% and pretty significant. Consider also that when we have buffer pooling for input formatters, the total allocations for this will be around 70mb.

Notice the multiples here - anything allocated 27000 times is allocated per-property-per-request. The `List<IModelValidator>` that's allocated 54000 times means that it's twice per property. This is bad scaling for a central infrastructure piece.

Suggested improvements - 

Don't sort validators by `IModelValidator.IsRequired`. We should remove this property and have the validator provider put validators in the correct order. This can avoid duplicating the list and doing the sort using Linq.

Have the `ValidationVisitor` cache the `ModelValidatorProviderContext` - this would mean that we'd allocate it once per request instead of N-times (N is the number of nodes we need to validate). We could do something more exotic in the future if needed. Reducing the number of `MVPC` instances would also allow us to reuse lists and arrays that they in-turn allocate.

**Comment by rynowak** [comment]
> Have the ValidationVisitor cache the ModelValidatorProviderContext

Some more evidence here - sampling data from 3000 requests of the same site.
![image](https://cloud.githubusercontent.com/assets/1430011/10775437/89496b70-7cc5-11e5-8cad-6fae89f47192.png)

Creating new lists and using Linq inside the validation code is too expensive.

**Comment by ajaybhargavb** [comment]
f7a211c09531f145329d76fe71d6676d5c4f3685
