### ISSUE TITLE
Select tag helper with static options

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#3386]
Given a select tag bound to a model property using `asp-for` that has only a few static options, the option matching the value of the model property is not automatically selected. I understand that the select options could be moved out into a getter on the model but it's also kind of nice just having them in the view. Not sure if this is a `wontfix` or not so I'm posting it here. Thanks for looking!

Using beta8

**Comment by dougbu** [comment]
Please provide more information on what you're seeing.

The `<select>` and `<option>` tag helpers work together to ensure the correct `<option>` element(s) is / are selected. If something is going wrong here, it's a scenario variant we aren't currently testing.

**Comment by tuespetre** [comment]
I was having this problem in two cases:

1. Error on my part, was not binding correctly in the controller.
2. When the static options were text (like, full comments or sentences) and did not have the 'value' attribute set

So the first case was my bad; the second case is IMO a discrepancy between how HTML works (per spec) and how the tag helper resolves selected values. In HTML, the value of an `<option>` is equivalent to its `textContent` IDL attribute when there is no value attribute defined. That's kind of what I thought the first case was going to be too.

For now I will just move the static options for my second case into a group of constant values and use an `IEnumerable<SelectListItem>` getter on my view model to spit them out, assigning the constants to both the `Text` and `Value` properties of `SelectListItem` so the tag helper picks up their values.

Assuming this will be a `wontfix`, go ahead and close if you feel the same :)

**Comment by dougbu** [comment]
> Assuming this will be a `wontfix`

Not a good assumption.

The `<option>` tag helper checks its body if the `value` attribute is not provided. So this should work. Could you upload a repro project to a GitHub repo?

**Comment by tuespetre** [comment]
> Not a good assumption

Sorry! Nothing on your (team's) part, just that I didn't know how much ripple effect something like that would cause. I will look closer at what I'm doing and report back. Thanks for your help!

**Comment by tuespetre** [comment]
Alright. Cloned `Mvc` and `Common` and added them to my solution's `global.json` to debug.

Here is a sample of the HTML:

```
<select class="form-control" asp-for="@Model.CpniQuestion">
  <option></option>
  <option>The last 4 digits of the primary account holder’s Social Security number</option>
</select>
```

Here is the value of `childContent.GetContent()`:
`"The last 4 digits of the primary account holder’s Social Security number"`

Here is the value of `encodedValues.First()`:
`"The last 4 digits of the primary account holder&#x2019;s Social Security number"`

Encoding apostrophes and quotes makes sense within attributes, but I don't know about text content.

For now I have decided to wrap the text contents of all of my static options like so: `<option>@("The last 4 digits of the primary account holder’s Social Security number")</option>`

**Comment by dougbu** [comment]
> For now I have decided to wrap the text contents of all of my static options like so: `<option>@(...`

That's a fine workaround. So is using `&#x2019;` directly in the `.cshtml` file.

We could compare the child content against `selectedValues` entries as well. Those aren't encoded. I'm not sure whether that change would have unintended consequences.

**Comment by Eilon** [comment]
@dougbu is there any work remaining here?

**Comment by dougbu** [comment]
@Eilon yes, as I said earlier:
> We could compare the child content against `selectedValues` entries as well

Right now we only match an `<option>` body if it's fully-encoded as the default `HtmlEncoder` does it. So literal text that doesn't bother to encode everything cannot match. Checking against the original values as well would fix that.

**Comment by Eilon** [comment]
Got it, thanks!

**Comment by dougbu** [comment]
fa8c2ea
