### ISSUE TITLE
Consider transitioning `TagHelper` property `null` checks into `TagHelper.Init` methods.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#3395]
In today's default `TagHelper`s there are several instances where we check that we've been provided the correct set of `TagHeper` properties. We should consider moving all of our `if (null) => throw` checks into the `Init` method.

**What does this buy us?**
When multiple `TagHelper`s are running on a single element if one ends up eventually exploding due to invalid parameters being passed in it ensures that the rest of the `TagHelper`s in the pipeline have not had their `Process`/`ProcessAsync` methods called. You could imagine this being valuable in the case that a user for some reason persists some sort of data in a `ProcessAsync` method only to have the rest of the pipeline fail.

**Comment by Eilon** [comment]
@NTaylorMullen / @DamianEdwards any concern if I close this? Do we really need this? This scenario sounds fairly contrived to me. Tag helpers don't really "persist" things...

**Comment by NTaylorMullen** [comment]
I'm alright with closing this. Investigated what it'd do with our TagHelpers and turned out to be a lot of code churn for little benefit.
