### ISSUE TITLE
Add ILibraryManager in MvcServices

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#3399]
Yank this code from:
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/WebHostBuilder.cs#L101

And move it into here:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L58

/cc @avanderhoorn You'll need to do the same for glimpse.

**Comment by avanderhoorn** [comment]
What does this mean for people who aren't using MVC and want to use LibraryManager???

**Comment by Eilon** [comment]
@pranavkm @davidfowl is this still needed for CLI?

**Comment by pranavkm** [comment]
This was fixed in https://github.com/aspnet/Mvc/commit/6467d0d47530920c7723844905661d801186fe5f
