### ISSUE TITLE
How to create Resources.Designer.cs automatically in asp.net 5 projects?

### ISSUE THREAD

**Issue by wulixu** [aspnet/Mvc#3400]
I found *.designer.cs file in mvc project. and see below comment.
```C#
// <auto-generated />
```
so I want to use this customer tool in my own project. any suggestions.

**Comment by pranavkm** [comment]
The beta8 tooling should auto-generate designer files for you from resx files. Also this would be a question for https://github.com/aspnet/Tooling

**Comment by Eilon** [comment]
VS (as of ASP.NET beta 8) will automatically generate a .designer.cs file for non-culture files. That is, it will generate the .designer.cs file for MyResources.resx, but will not generate one for MyResources.en-US.resx (which is the same as the behavior has always been).
