### ISSUE TITLE
Suggestion: Consolidate namespaces HTML and tag helper authors both need

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3402]
Currently tag helper authors frequently need the following `using`s:
``` c#
using Microsoft.AspNet.Html.Abstractions;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.AspNet.Mvc.ViewFeatures;
using Microsoft.AspNet.Razor.Runtime.TagHelpers;
```

One way forward would be to move the shared pieces into `Microsoft.AspNet.Html`. That would include at least `IHtmlContent`, `IHtmlContentBuilder`, `IHtmlGenerator`, `TagBuilder` and related extension classes.

Could go further and move pieces intended for tag helper authors into `Microsoft.AspNet.Html.TagHelpers` (these aren't that tied to Razor) and those for HTML helper authors into `Microsoft.AspNet.Html.HtmlHelpers` (admittedly, these are quite tied to MVC).

Should probably also revisit the `Microsoft.AspNet.Mvc.Rendering` / `Microsoft.AspNet.Mvc.ViewFeatures` split with an eye toward specific MVC extension scenarios.

##### Details
Without `Microsoft.AspNet.Html.Abstractions`, `TagHelperContent` properties lack extension methods such as `AppendHtmlLine()`. We re-implemented some but not all `IHtmlContentBuilder` extension methods in `TagHelperContent` to improve discoverability. But that approach doesn't scale and doesn't help with properties of the interface type e.g. `TagBuilder.InnerHtml`.

Without `Microsoft.AspNet.Mvc.Rendering`, tag helper authors don't have access to infrastructure shared with HTML authors such as `TagBuilder`.

Without `Microsoft.AspNet.Mvc.ViewFeatures`, tag helper authors lack access to shared infrastructure such as `IHtmlGenerator`.

For similar reasons HTML helper authors (developers writing `IHtmlHelper` extension methods, subclassing `HtmlHelper`, or creating similar helpers for `@inject` use) frequently need all but `Microsoft.AspNet.Razor.Runtime.TagHelpers`. In this case _all_ `IHtmlContentBuilder` extension methods are hard to discover.

(For an example of the current state, see the **After** example in a later comment on aspnet/Announcements/issues/89.)

**Comment by rynowak** [comment]
> Should probably also revisit the Microsoft.AspNet.Mvc.Rendering / Microsoft.AspNet.Mvc.ViewFeatures split with an eye toward specific MVC extension scenarios.

Specifically, `Microsoft.AspNet.Mvc.Rendering` to contain only types commonly used by name in views. `ViewFeatures` contains both reusable and non-reusable infrastructure.

**Comment by Eilon** [comment]
Closing this as we think all the key items are already done.
