### ISSUE TITLE
beta4 project completely broken with beta 8

### ISSUE THREAD

**Issue by bdelaney** [aspnet/Mvc#3406]
Hmmm, I started a brand new Win10 instance and installed the VS2015 Community edition. Installed beta8 from asp.net vnext site. Then cloned an asp.net MVC project from VSonline, using Git. Upon opening first time it seems to update nuget packages. When completed I am unable to open any files in editor from solution. And when I reopen the project, it just hangs with 'Preparing Solution' progress bar. May be similar to this issue: [github issue](https://github.com/aspnet/Tooling/issues/21)

**Comment by davidfowl** [comment]
Yes, we don't keep compatibility that far back.

**Comment by bdelaney** [comment]
Okay, so the answer is to hand edit project.json, startup.cs and try to reconstitute this project?

**Comment by davidfowl** [comment]
beta4 to beta8 is insanity, I would make a new project and copy things over.

**Comment by davidfowl** [comment]
The amount of breaking changes between there might turn you off :smile:

**Comment by bdelaney** [comment]
Okay, thanks for the sanity check. It was fun to see VS 2015 paralyzed...
