### ISSUE TITLE
The response headers cannot be modified because the response has already started.

### ISSUE THREAD

**Issue by GVX111** [aspnet/Mvc#3411]
<pre>An unhandled exception occurred while processing the request.

InvalidOperationException: The response headers cannot be modified because the response has already started.<pre>
On authorize

**Comment by rynowak** [comment]
This means what it says. If the response has already been sent to the user, you can't modify the headers anymore, they have already gone out. 

Can you provide some more information about what you're trying to do?

**Comment by gvx111** [comment]
on signin authorization with Authenticationmanager .

**Comment by Eilon** [comment]
@GVX111 can you share some sample code that reproduces this issue?
