### ISSUE TITLE
How to set/add assembly with strongly typed view model type definition?

### ISSUE THREAD

**Issue by DmitrySikorsky** [aspnet/Mvc#3413]
I have package (dll) with views as resources (like here: https://github.com/aspnet/Mvc/tree/dev/test/WebSites/RazorEmbeddedViewsWebSite). I have main web app that loads that dll (like here https://github.com/aspnet/Entropy/tree/dev/samples/Runtime.CustomLoader). It works. I can show the view from the dll using the controller from that dll without reference to that dll in project.json of the main app.

But if I make the view strongly typed (with some type defined inside that dll) it can't compile the view on runtime. I have "Type not found" exception.

How can I tell the compiler to take view model type from specific assembly?

(I used to do this by BuildManager.AddReferencedAssembly in MVC 5).

Thank you very much!

**Comment by DmitrySikorsky** [comment]
I have to add, that it will work if I make the views in the dll precompiled and then set the dll as services.AddMvc().AddPrecompiledRazorViews(myAssembly). But I want to understand how it works and to have the choice.

**Comment by davidfowl** [comment]
There's no way to add references at runtime today to the razor compilation

**Comment by DmitrySikorsky** [comment]
Thank you for the answer David! So the only way to have views and view models from another dll without reference in the project.json is views precompilation? Is this good idea, maybe there are some problems I can have with such approach? Thanks!

**Comment by davidfowl** [comment]
Is this specific for views? We could expose something to make this easier (the roslyn API maybe). If you really want to dig in, you can implement your own ILibraryExporter that wraps the original one and exposes your assembly reference as a reference to use fore view compilation.

**Comment by DmitrySikorsky** [comment]
Existing services.AddMvc().AddPrecompiledRazorViews(assemblies) is very useful for precompiled views. Maybe it is possible to add such thing to set additional assemblies for runtime compilation later too. It would be very helpful.

A lot of people had same problem in the previous version of MVC, there is solution, it works but it is not very simple: http://shazwazza.com/post/Developing-a-plugin-framework-in-ASPNET-with-medium-trust

Thanks for ILibraryExporter tip, will look at it.

**Comment by Eilon** [comment]
@pranavkm is there a way to do this today?

**Comment by DmitrySikorsky** [comment]
Yes. Use assembly parts.

**Comment by Eilon** [comment]
Ah, of course, indeed, so then closing this.
