### ISSUE TITLE
RegularExpressionAttribute generates wrong data-val-regex message

### ISSUE THREAD

**Issue by sanchobear** [aspnet/Mvc#3414]
Using the RegularExpressionAttribute with beta8 like C# data object:
```
[RegularExpression("X4[27]|X8[0-9]", ErrorMessage="Should be like RegEx ....")]
public string ProjectCode { get; set; }
```
and cshtml view: 
```
<input asp-for="ProjectCode" class="form-control" />
```
generates html:
```
<input name="ProjectCode" class="form-control valid" id="ProjectCode" type="text" value="" 
    data-val="true" data-val-regex-pattern="X4[27]|X8[0-9]" data-val-regex="ProjectCode" >
```
instead of: 
```
data-val-regex="Should be like RegEx ...."
```
During validation failure the field Name is displayed instead of the ErrorMessage text.
If the ErrorMessage parameter is **NOT** used, then the standard text for data-val-regex is correct.

**Comment by Muchiachio** [comment]
I am unable to reproduce this neither on beta8 nor on latest bits.
Could you upload a repro project to a GitHub repo?

**Comment by sanchobear** [comment]
You are right, I built a small project out of the bigger one => and it 
works as expected.

But I am also right, because this behavior continues in the bigger app.

Consequence: I'm clueless how to proceed



Von:    Muchiachio <notifications@github.com>
An:     aspnet/Mvc <Mvc@noreply.github.com>
Kopie:  sanchobear <bodo.probst@esg.de>
Datum:  26.10.2015 17:29
Betreff:        Re: [Mvc] RegularExpressionAttribute generates wrong 
data-val-regex message (#3414)



I am unable to reproduce this neither on beta8 nor on latest bits.
Could you upload a repro project to a GitHub repo?
—
Reply to this email directly or view it on GitHub.

_____________________________________________________________________________________________________________________

ESG Elektroniksystem- und Logistik-GmbH
Rechtsform/Legal Form: Gesellschaft mit beschränkter Haftung
Sitz/Registered Office: München
Handelsregister/Commercial Register: Registergericht München, HRB 219422
Vorsitzender der Geschäftsführung/CEO: Kai Horten, 
Geschäftsführer/Managing Director: Götz Graichen

**Comment by Muchiachio** [comment]
It will most likely be something from your startup configuration, you could try adding more and more of your original configuration to your newly created repro until you start seeing incorrect behavior.

**Comment by sanchobear** [comment]
Excellent hint:
```
services.AddMvc().AddDataAnnotationsLocalization(); 
```
the AddDataAnnotationsLocalization caused that behavior!

**Comment by Muchiachio** [comment]
Yes, I was able to reproduce it too.

For the team: it happens, because of newly added localization [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.DataAnnotations/DataAnnotationsClientModelValidatorOfTAttribute.cs#L61), string localizer returns no resource found and [defaults](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L85) to display name.
