### ISSUE TITLE
Tag Helper Intellisense

### ISSUE THREAD

**Issue by Fosol** [aspnet/Mvc#3415]
Is there a way to get intellisense working?

I have a _ViewImports.cshtml file.
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"

**Comment by NTaylorMullen** [comment]
Ensure you have the `Microsoft.AspNet.Tooling.Razor` package in your application.

**Comment by Fosol** [comment]
That worked, Thanks!

**Comment by brockallen** [comment]
Is this dependency the long-term plan for VS/intellisense support? If so, is there a way to mark is as a dev-time only dependency in project.json? Is this sufficient config to get it only during dev:
```
  "dependencies": {
    "Microsoft.AspNet.Tooling.Razor": {
      "type": "build", "version": "1.0.0-beta8"
    }
  },
```

**Comment by NTaylorMullen** [comment]
@brockallen As of today there's no great way. A while back there was an issue filed on aspnet/Dnx for a design-time only dependency alternative. /cc @glennc @muratg do you guys happen to know the link to that issue? I looked but couldn't find one.
