### ISSUE TITLE
ValidationAttribute - How To?

### ISSUE THREAD

**Issue by Fosol** [aspnet/Mvc#3419]
Can someone point me to documentation on ValidationAttributes?

I've applied a DataTypeAttribute to a data member and it doesn't show up anywhere?

Reviewing the InputTagHelper I'm unable to figure out how to add additional validation related 'things' in the Startup.Config().

Any help would be appreciated.

**Comment by danroth27** [comment]
The MVC 5 docs on validation should still apply for the most part: http://www.asp.net/mvc/overview/getting-started/introduction/adding-validation

Basically you just add data annotations to your model properties and they should get honored by the HTML input and tag helpers. To show validation errors use the `ValidationSummary` and `ValidationMessage` HTML helpers.

**Comment by Fosol** [comment]
That only contains 11 ValidationAttributes.  It does not contain them all (i.e. DataTypeAttribute).

**Comment by Fosol** [comment]
Since it's been impossible for me to step through the open source code  while debugging I'd love to know how the validation attributes get added.  If need be I can add additional ones.
