### ISSUE TITLE
To await or not to await in controller action

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Mvc#3422]
Consider this code in a controller:
```csharp
public async Task<JsonResult> SomeAction()
{
	// Both tasks are independent of each other.
	Task someTask = ExecuteSomeTask();
	Task<object> resultValueTask = GetSomeResultAsync();
	
	await someTask;
	return Json(resultValueTask);
}
```

I have two options here, either await the result using `return Json(await resultValueTask)` or just `return Json(resultValueTask)`. `resultValueTask` could possibly take some time.  Both seem to work, but I'm not sure what the best practice is here.

**Comment by rynowak** [comment]
I'm really surprised that `return Json(resultValueTask)` would do what you want. Are you sure that you're not seeing the `Task` instance serialized (which includes the `.Result` property)? If this is working, it is likely the case that JSON.Net handles this for you.

> I'm not sure what the best practice is here

It's not really a matter of best practice, if you need to interact with the result of a task, you **need** to `await` it (`return Json(await resultValueTask)`).

**Comment by henkmollema** [comment]
Wow, my bad.. It does indeed return a serialized `Task<T>`. :tired_face: 

/close
