### ISSUE TITLE
Make `ModelBinderAttribute.BindingSource` setter `protected`

### ISSUE THREAD

**Issue by genusP** [aspnet/Mvc#3428]
For this code
```
public IActionResult Add(
            string entity, 
            [ModelBinder(BinderType = typeof(EntityViewModelBinder), BindingSource = BindingSource.Form)]
            object viewModel
            )
        {
...
}
```

Result:
Error	CS0655	'BindingSource' is not a valid named attribute argument because it is not a valid attribute parameter type	WebApplication2.DNX 4.5.1

.NET Framework Clr version 4.0.30319.42000   |   DNX x86 version 1.0.0-beta8-15858   |   Microsoft.AspNet.Hosting version 1.0.0-beta8-15756   |   Windows 7.0

**Comment by danroth27** [comment]
You need to derive your own attribute to specify the BindingSource.

We should make this clearer by making the BindingSource setter protected.

**Comment by geniusP** [comment]
I derive my attribute:
```
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Property | AttributeTargets.Parameter, AllowMultiple = false, Inherited = true)]
    public class EntityViewModelBinderAttribute:ModelBinderAttribute
    {
        public EntityViewModelBinderAttribute()//:base()
        {
            BinderType = typeof(EntityViewModelBinder);
            BindingSource = Microsoft.AspNet.Mvc.ModelBinding.BindingSource.ModelBinding;
        }
    }
```
And set this attribute to parameter:
```
public IActionResult Add(
            string entity, 
            [EntityViewModelBinderAttribute]
            object viewModel
            )
        {
```
Result. My binder not calling. Why?

**Comment by dougbu** [comment]
MVC itself never subclasses `[ModelBinder]`. Instead `[FromBody]` and similar attributes implement `IBindingSourceMetadata` themselves. Wondering about removing the setter for `ModelBinderAttribute.BindingSource` entirely. Getter would remain as-is, indicating whether the `BinderType` had been set (making it a `BindingSource.Custom` binder).

@Eilon / @danroth27 / @rynowak thoughts?

**Comment by Eilon** [comment]
Why not just make it protected?

**Comment by dougbu** [comment]
> Why not just make it `protected`?

We have a simple way to create an attribute that specifies the `BindingSource` e.g.
``` c#
    [AttributeUsage(AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class FromPathAttribute : Attribute, IBindingSourceMetadata
    {
        public BindingSource BindingSource { get { return BindingSource.Path; } }
    }
```

My question is do we need
``` c#
    public class FromPathAttribute : BindingSourceAttribute
    {
        FromPathAttribute()
        {
            BindingSource = BindingSource.Path;
        }
    }
```
as well?

If we want an additional way to create this `FromPathAttribute`, another option is to remove the `BindingSource` setter but make the property `virtual`. Then
``` c#
    public class FromPathAttribute : BindingSourceAttribute
    {
        public override BindingSource BindingSource => BindingSource.Path;
    }
```

**Comment by rynowak** [comment]
I seem to recall we discussed this and agreed on making it `protected` a few weeks ago.

**Comment by Eilon** [comment]
Let's stick with the design.

**Comment by dougbu** [comment]
Updated title to better match chosen update.

**Comment by dougbu** [comment]
45ff0a2
