### ISSUE TITLE
File upload broken on latest version of MVC

### ISSUE THREAD

**Issue by Niekess** [aspnet/Mvc#3429]
### Functional impact
The ability to upload a file isn't possible.

### Minimal repro steps

1. Create a page with a simple form to upload one or more files.
2. Create an action that receives the uploaded files and saves them to the wwwroot.
3. Ensure you're on the latest MVC version (rc1-16028 at time of writing).
4. Upload a file using the created form.

### Expected result
An except copy of the file in the wwwroot folder of the file(s) you selected.

### Actual result
There are no files in the folder if you have choosen to upload a single file.
If you choose to upload multiple are some files in the folder but they are corrupt. (There is one file as example in the sample project)

### Further technical details
[Sample project I created for this bug](https://github.com/Niekess/FileUpload)

**Comment by rynowak** [comment]
I'm trying to repro this on newest bits. It's very likely that this was a manifestation of https://github.com/aspnet/KestrelHttpServer/issues/270 - which lead to all sorts of request corruption.

aspnet/KestrelHttpServer#270 was fixed as of build 15890.

I'll update here with results.

**Comment by rynowak** [comment]
I can confirm that this is working for me on the latest build of kestel.

When this fails for you do you still see "Done" (the response) or do you get a white screen and a 500? I'd suggest adding the developer exception page https://github.com/aspnet/Diagnostics/blob/dev/samples/DeveloperExceptionPageSample/Startup.cs#L10 if you still hit this issue. There's no default 'yellow screen of death' if your app throws, you just get a 500 now.
