### ISSUE TITLE
Invalid media type 'text/plain; charset=utf-8'

### ISSUE THREAD

**Issue by flipchart** [aspnet/Mvc#3433]
In a Controller action:

    return File(stream, "text/plain; charset=utf-8");

throws `'System.FormatException'` in `Microsoft.Net.Http.Headers.dll` with message `Invalid media type 'text/plain; charset=utf-8'`

**Comment by Eilon** [comment]
@kichalla @dougbu @rynowak I feel like one of you has some knowledge on this - do we assume only a MIME type here with no extra header-ish values? Is there another way to pass in extra values such as `charset`?

**Comment by rynowak** [comment]
What @flipchart is doing here is intended to be supported. I'll take a quick look at what's the issue here.

**Comment by rynowak** [comment]
The causes of the overstrictness is here - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/VirtualFileResult.cs#L34
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/MediaTypeHeaderValue.cs#L33

The **constructors** of `MediaTypeHeaderValue` are intended to be used only with media-types, and are used for imperatively building a header value upon which you'll then call `ToString()` to write.

The `.Parse` method is what we should be using. I'll do a pass for other similar cases.

**Comment by rynowak** [comment]
It looks like all of the fileresults have this issue.

There's one tricky case: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/Controller.cs#L487

This one takes a `string` and an encoding. But everywhere else we let you specify the `string` that string might contain the encoding. Suggest that we tolerate passing in a `string` like `"text/plain; charset=utf-8"` but if you also specify an encoding, the encoding wins.

**Comment by dougbu** [comment]
> intended to be used only with media-types

The code you referenced should support parameters in the `string`. Is the intolerance at a significantly lower level than `GetMediaTypeExpressionLength()`?

**Comment by dougbu** [comment]
Nevermind, I missed the second part of the condition on line https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/MediaTypeHeaderValue.cs#L484
