### ISSUE TITLE
`asp-for` generating unexpected output

### ISSUE THREAD

**Issue by bitcrazed** [aspnet/Mvc#3437]
In my `form`, the following code ...

    <input asp-for="@account.LoginProvider" type="hidden" />
    <input asp-for="@account.ProviderKey" type="hidden" />

... generates the following HTML:

    <input type="hidden" id="account_LoginProvider" name="account.LoginProvider" value="Facebook" />
    <input type="hidden" id="account_ProviderKey" name="account.ProviderKey" value="..." />

This HTML is incorrect - the `account.` and `account_` prefixes are unnecessary and causes the receiving controller method to not receive these values:

    public async Task<IActionResult> RemoveLogin(string loginProvider, string providerKey)

The HTML should be:

    <input id="loginProvider" name="loginProvider" value="Facebook" type="hidden" />
    <input id="providerKey" name="providerKey" value="..." type="hidden" />

The latter HTML will be dispatched correctly to the receiving controller

**Comment by dougbu** [comment]
If `account` is equal to the current `Model`, you just need `<input asp-for="LoginProvider" .../>`. Otherwise the prefix is correct for the general case and you probably need to include explicit `id` and `name` attributes in the `.cshtml` for your case.

**Comment by bitcrazed** [comment]
Thanks @dougbu, but this doesn't work when, for example iterating the `Model.CurrentLogins` in the site template's [ManageLogins.cshtml](https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Views/Manage/ManageLogins.cshtml#L24-L25).

**Comment by dougbu** [comment]
That's never going to work. Linq can't give the framework sufficient information about the `account` variable. Recommend
### old
``` c#
  @foreach (var account in Model.CurrentLogins)
  {
     ... asp-for="@account.LoginProvider" ...
  }
```

### new
``` c#
  @for (var index = 0; index < Model.CurrentLogins.Count; index++)
  {
     ... asp-for="@Model.CurrentLogins[index].LoginProvider" ...
  }
```

**Comment by bitcrazed** [comment]
Having to change iteration idioms in order to overcome an issue in the way a part of the implementation works makes this 'solution' feel very fragile and is likely to cause a great deal of confusion. 

Can the HTML generator not just omit the

**Comment by dougbu** [comment]
Suspect you didn't change to `asp-for="@Model.CurrentLogins[index].LoginProvider"`.

**Comment by bitcrazed** [comment]
Ugh - apologies - you're right: My caffeine stream appears to have too much blood in it this morning ;)

However, your solution ...

    <input asp-for="@Model.CurrentLogins[index].LoginProvider" type="hidden" />
    <input asp-for="@Model.CurrentLogins[index].ProviderKey" type="hidden" />

... now generates:

    <input type="hidden" id="CurrentLogins_0__LoginProvider" name="CurrentLogins[0].LoginProvider" value="Facebook" />
    <input type="hidden" id="CurrentLogins_0__ProviderKey" name="CurrentLogins[0].ProviderKey" value="10153738038264809" />

Not sure this is an improvement - I still think the `id` and `name` attributes should just be the unadorned name of the property.

**Comment by dougbu** [comment]
> I still think the id and name attributes should just be the unadorned name of the property.

Then model binding would not work. Names are important :smiley_cat:

**Comment by bitcrazed** [comment]
How so? 

In the example above, how will a form's `input` elements be mapped to a controller's POST handler's argument's if they're named "CurrentLogins[0].LoginProvider", or "account.LoginProvider" for example?

Do the handler's arguments need to be renamed?

**Comment by dougbu** [comment]
In the above example a form data entry named `"CurrentLogins[0].LoginProvider"` will be model bound to the `LoginProvider` property of the `0`th element in the `Model.CurrentLogins` collection. That's just how model binding works.

Parameter names in an action are sometimes relevant but not in this case. The input field is not submitting a top-level object named `LoginProvider`.

You _may_ be able to do what you want by naming the parameter in your `foreach` `model`. But that's magical and not particularly maintainable code. Better to bind the entire POCO model and its contained collections in one go, as I suggested.

**Comment by bitcrazed** [comment]
Thanks for your thoughts on this. 

I think, perhaps, the template's code to render a form to allow one to remove a registered login is incorrect and should instead explicitly render the `input` element's `id` and `name`:

    @foreach (var account in Model.CurrentLogins)
    {
        <! -- BLAH -->
        <form asp-controller="Manage" asp-action="RemoveLogin" method="post" class="form-horizontal" role="form">
            <div>
                <input id="loginProvider" name="loginProvider" value="@account.LoginProvider" type="hidden" />
                <input id="providerKey" name="providerKey" value="@account.ProviderKey" type="hidden" />

                <input type="submit" class="btn btn-default" value="Remove" title="Remove this @account.LoginProvider login from your account" />
            </div>
        </form>
    }

**Comment by dougbu** [comment]
Well, those names won't work very well if there's more than one element in the collection the surrounding `foreach` is running through.

I agree `ManageLogins.cshtml` should be fixed in the [`MusicStore`](https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/Views/Manage/ManageLogins.cshtml#L15-L25) and [`Templates`](https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Views/Manage/ManageLogins.cshtml#L15-L25) repos. The general issue is "Correct generated names for `CurrentLogins` fields".

Unless you object, I'll move this issue to the `Templates` repo.

**Comment by dougbu** [comment]
BTW the `<form>` happens to be inside the `foreach` in this case and that avoids `name` uniqueness concerns. But the `name`s don't currently work w/ the `RemoveLogin()` action and we should find an approach that avoids duplicate `id`s on the page.

**Comment by dougbu** [comment]
This issue was moved to aspnet/Templates#296

**Comment by bitcrazed** [comment]
Thanks @dougbu.
