### ISSUE TITLE
IViewLocalizer not changes when have custom StringLocalizer on CoreCLr

### ISSUE THREAD

**Issue by Codenator81** [aspnet/Mvc#3439]
When I have custom Localizer and change culture in OnActionExecuting:
```
CultureInfo.CurrentCulture = culture;
CultureInfo.CurrentUICulture = culture;
```
 IViewLocalizer still not changed but IHtmlLocalizer works great. 
My code is:
Controller: https://github.com/WeebDo/WeebDo.CMF/blob/master/src/WeebDoCMF/Controllers/HomeController.cs#L10
View: https://github.com/WeebDo/WeebDo.CMF/blob/master/src/WeebDoCMF/Views/Home/Index.cshtml

P.S. When I try localization from cookies IViewLocalizer react and change translation strings.

**Comment by Muchiachio** [comment]
Yes this doesn't seem to work.
I couldn't manage to make my `*.resx`'es work with current (ui) culture either.

**Comment by damienbod** [comment]
Do you start from the console and not from Visual Studio?

Greetings Damien

**Comment by Codenator81** [comment]
I start from console. I think it should be all way tested from console becouse on linux no VS.

**Comment by Eilon** [comment]
@Codenator81 can you simplify the scenario to help isolate the problem? We did recently fix a number of issues in this area so this might already work on the latest RC2 preview bits.
