### ISSUE TITLE
Unexpected (or strange) behavior while searching for referenced assemblies

### ISSUE THREAD

**Issue by DmitrySikorsky** [aspnet/Mvc#3440]
I have the main app (AssemblyA). It loads the dll (AssemblyB) (using the approach described here: https://github.com/aspnet/Entropy/tree/dev/samples/Runtime.CustomLoader) which contains controller. In the ConfigureServices of AssemblyA I register my custom AssemblyProvider, that copies assemblies from DefaultAssemblyProvider and adds AssemblyB to the list. Everything works.

Now, If I set AssemblyB to compile the views by adding the RazorPreCompilation class AND then call services.AddMvc().AddPrecompiledRazorViews(AssemblyB) in AssemblyA I have runtime exception "Assembly can't be loaded". To fix this I only need to put System.Reflection.dll version 4.1.0 to the same folder as AssemblyB.

If I try to use actionExecutingContext.HttpContext.User.Identity.IsAuthenticated in the AssemblyB, I also have exception that it can't load System.Security.Claims.dll. If I comment out the lines, error goes away. If I use it in AssemblyA I don't have any error.

So the question is why does it need the dll to be in the same location with AssemblyB? Why it doesn't take it from the .dnx folder? How can it be fixed?

Thanks!

**Comment by leo9223** [comment]
Same problem with me also

**Comment by Eilon** [comment]
Closing because we haven't seen any issues in this space in quite a while. Since this bug was opened we made a lot of changes (and improvements!) to how assemblies are loaded, so presumably this is fixed. If you're still seeing an issue, please log a new issue with additional information. Thanks!
