### ISSUE TITLE
Proposal.  Microsoft.AspNet.Mvc.Xml For Beta 8? (DNX 4.5.1) - MVC 6

### ISSUE THREAD

**Issue by crupak** [aspnet/Mvc#3448]
I was wondering if you could make the xml serializer libraries available for the next beta.  Using Beta 5 of the libraries causes a server 500 error (any request). Using Beta 6 seems to work (testing now).

**Comment by rynowak** [comment]
This package was renamed to `Microsoft.AspNet.Mvc.Formatters.Xml` https://github.com/aspnet/Announcements/issues/49
