### ISSUE TITLE
LinkTagHelper's fallback meta tag isn't W3C compliant

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Mvc#3449]
This generated markdup isn't valid W3C compliant markup:

```html
<meta name="x-stylesheet-fallback-test" class="invisible" />
```
Running it through the W3C validator produces this error:

`Element meta is missing one or more of the following attributes: "content", "property".`

**Comment by NTaylorMullen** [comment]
This should be rc2. /cc @Eilon @danroth27

**Comment by NTaylorMullen** [comment]
Played around with this and I'm proposing we go with: `<meta property="x-stylesheet-fallback-test" content class="..." />`.

Meta tags aren't valid in the body with a `name` tag sadly.

**Comment by NTaylorMullen** [comment]
decf8823414146fe6feaba0ed9fcfe4044258e04
