### ISSUE TITLE
Access Access ModelState In Middleware?

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Mvc#3454]
Is it possible to access the `ModelStateDictionary` in a middleware class? I am looking to write a "catch all" `ModelState.IsValid` handler for every request for my API via middleware so I do not have to do the check in the controller actions all over the place.

**Comment by dougbu** [comment]
@kspearrin `ModelStateDictionary` is a MVC-specific feature. It's not filled in until model binding and validation occur -- just before invoking an action method.

However it's possible to write catch-all `ModelState.IsValid` checks other ways. For example the MVC functional test web sites include a couple of `ActionFilterAttribute` subclasses that do this -- [`ModelStateValidationFilterAttribute`](https://github.com/aspnet/Mvc/blob/dev/test/WebSites/FormatterWebSite/Filters/ModelStateValidationFilterAttribute.cs) and the more complicated / specific [`ValidateBodyParameterAttribute`](https://github.com/aspnet/Mvc/blob/dev/test/WebSites/FormatterWebSite/ValidateBodyParameterAttribute.cs). `ActionFilterAttribute` is not the only approach: E.g. `IActionFilter`s and `IAsyncActionFilter`s can be added through the application model.

**Comment by Eilon** [comment]
Right, a global MVC filter is the way to do this. That would apply the filter to *every* MVC controller action method. Middleware is simply the wrong layer for this.

**Comment by kspearrin** [comment]
Totally makes sense now that I think about it. Thanks for the tips.
