### ISSUE TITLE
Question about TagHelpers.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#3458]
having a model like : `SomethingViewModel` as
```
public class SomethingViewModel {
    public class IEnumerable<Something> Somethings { get; set; }
}
```
where Something is:

```
public class Something {
    public string Name { get; set; }
}
```

Can I make a taghelper that in the cshtml works like this? :

```
<repeat collection="Somethings">
    <p>@Name</p>
</repeat>
```

so the context inside the repeat taghelper became something different than the context outside of it ? or should I use a partial for this kind of scenarios?

Thanks!.

**Comment by dougbu** [comment]
@Bartmax tag helpers cannot change `ModelType` within the targeted element. You could have the `<repeat>` tag helper place a `Something` in a well-known slot in `ViewData`. But `@Name` would need to be `@ViewData["Well-Known"].Name` and nested tag helpers would still be using the view's `Model` and `ModelType`. All-in-all, a partial seems the better choice.

**Comment by Bartmax** [comment]
Thank you @dougbu ! I wasn't sure and yes partial feel better then!
