### ISSUE TITLE
inlcuding package in dependencies part of project.json

### ISSUE THREAD

**Issue by OlegKi** [aspnet/Mvc#3459]
I posted [the pull request](https://github.com/aspnet/Mvc/pull/3456) before, but the answers reduced my suggestion to successful building of MVC beta8. Thus I open better new issues with the following question:

 - **Which packages should be included in `"dependencies"` part of `project.json`?**

[The line 308](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/Compilation/RoslynCompilationService.cs#L308) of `RoslynCompilationService.cs` of `Microsoft.AspNet.Mvc.Razor.xproj`  **uses directly** enum `PEStreamOptions.PrefetchMetadata` from the namespace `System.Reflection.PortableExecutable`, defined in [System.Reflection.Metadata](https://www.nuget.org/packages/System.Reflection.Metadata/). Thus I correct to **include ** `System.Reflection.Metadata` in `dependencies` part of `project.json`. I suggest to add the following line
```
    "System.Reflection.Metadata": "1.1.0-*"
```

**Please explain the common rule of including packages in `dependencies` part of `project.json`.** Should one include all packages referenced *directly* in the code or not?

**Comment by dougbu** [comment]
The choice of which dependencies to list beyond the minimum needed for correct compilation and execution is a developer's choice. In most of the ASP.NET 5 / MVC 6 / EF 7 codebase, we have chosen to list _only_ the minimum required. We have occasionally double-checked listed dependencies and removed those referenced transitively.

**Comment by OlegKi** [comment]
Sorry, but "double-checked listed dependencies" seems to me not a strong enough rule. By examining of **the current** dependencies you suppose that **the next version** of all the dependencies will stay *the same*. If one follow the rule then the project can be broken after publishing one new version from direct or indirect depended package. Moreover I can imagine that the existing rules of resolving dependencies produce different results depend on the order of recursive resolving of dependencies.

The analyse of `project.lock.json` shows that `System.Reflection.Metadata` is included (currently) in the 4-th level of dependencies of `Microsoft.AspNet.Razor.Runtime.Precompilation` and `Microsoft.Dnx.Compilation.CSharp.Common`. To be exact one have
```
"Microsoft.AspNet.Razor.Runtime.Precompilation/4.0.0-beta8"
  "Microsoft.Dnx.Compilation.CSharp.Abstractions/1.0.0-beta8"
    "Microsoft.CodeAnalysis.CSharp/1.1.0-beta1-20150928-02"
      "Microsoft.CodeAnalysis.Common/1.1.0-beta1-20150928-02"
        "System.Reflection.Metadata": "1.1.0-alpha-00014"

"Microsoft.Dnx.Compilation.CSharp.Common/1.0.0-beta8"
  "Microsoft.Dnx.Compilation.CSharp.Abstractions/1.0.0-beta8"
    "Microsoft.CodeAnalysis.CSharp/1.1.0-beta1-20150928-02"
      "Microsoft.CodeAnalysis.Common/1.1.0-beta1-20150928-02"
        "System.Reflection.Metadata": "1.1.0-alpha-00014"
```
together with **direct** dependency to `System.Reflection.Metadata` (in version >= 1.1.0-* or >= 1.\*.\*-* probably). Thus publishing of **any new version of**  `Microsoft.Dnx.Compilation.CSharp.Abstractions`, `Microsoft.CodeAnalysis.CSharp`, `Microsoft.CodeAnalysis.CSharp` or `Microsoft.CodeAnalysis.Common` can break the dependency to `System.Reflection.Metadata`. Isn't so?

I formulate my question as common question about including dependencies in `package.json`. The project `Microsoft.AspNet.Mvc.Razor.xproj` is just an example. Probably placing the question to https://github.com/aspnet/Mvc was wrong and it would be better to place it in some other repository of https://github.com/aspnet (but which one)?

Sorry, but I don't understand why one not includes **all modules, which will be used directly** in the project. It's not really important, whether the list will contains 9 packages or 90. One can use tools, which scan source code for dependencies (like ReSharper) or which examine the final binary (like IDL, or Fuslogvw.exe, ildasm.exe, NetReflector and so on) to scan for direct dependencies. One can create the tools and include there in the SDK.

**It seems that the state of cached packages from `%userprofile%\.dnx` influence the current building process.** It's very dangerous! The request to NuGet repository(s) about metadata information of all direct (or even indirect) used packages could work quick enough. The backend (NuGet service) could makes the resolution of all dependencies based on the metadata of all dependent packages published on NuGet. Why one don't make the request(s) first of all? Only after building the full list of dependencies, *based on the latest information from NuGet*, one can uses packages from the cache, but only if **the exact versions** are already cached. Such building process will be free from side effect from existing of old version of packages in the cache (on `%userprofile%\.dnx`).

**Comment by dougbu** [comment]
This issue was moved to aspnet/dnx#3113
