### ISSUE TITLE
Not able to perform code analysis or collect metrics? 

### ISSUE THREAD

**Issue by alexdresko** [aspnet/Mvc#3460]
It looks like it's not possible to collect code metrics or run a code analysis on an ASP.NET beta 8 project.. Is this something that is expected to be fixed, or is there a mitigation plan or recommendation? 

![image](https://cloud.githubusercontent.com/assets/333022/10890760/de1627dc-8167-11e5-8978-994457118006.png)

![image](https://cloud.githubusercontent.com/assets/333022/10890767/e44acb44-8167-11e5-90e8-90b473b7249a.png)

Thanks!

**Comment by Eilon** [comment]
Already logged here: https://github.com/aspnet/Tooling/issues/255

Thanks!

**Comment by alexdresko** [comment]
Aha! Makes sense why I wasn't able to find that issue when searching this repo. It's an ASP.NET 5 project, not MVC...  

Bonus question since I've realized that: Why is MVC a separate repo from the collective now known as ASP.NET? Is it simply because WebForms is a separate assembly (and thankfully so)?

**Comment by Eilon** [comment]
@alexdresko the 'aspnet' org on GitHub has all the newest open source components from Microsoft for ASP.NET. MVC is just one of dozens of repos here that are part of ASP.NET. Web Forms is in ASP.NET 4.x, whereas almost all the repos here are for ASP.NET 5.

**Comment by alexdresko** [comment]
That is helpful, @Eilon! Thank you.

**Comment by RehanSaeed** [comment]
Is there any reason why the linked issue was closed? This issue was also closed. I suspect this is a mistake.

**Comment by alexdresko** [comment]
@RehanSaeed The issue I created here is being tracked separately at https://github.com/aspnet/Tooling/issues/255 so there is no need to keep my issue open.
