### ISSUE TITLE
Convert.ChangeType(valueResult, typeof(T)) throws Object must implement IConvertible

### ISSUE THREAD

**Issue by RiteshPahwa** [aspnet/Mvc#3462]
```var ret = (valueResult == null) ? default(T) : (T)Convert.ChangeType(valueResult, typeof(T));```

throws exception: Object must implement IConvertible. It was working in Beta7

It was implemented like

```c#
private static T GetValue<T>(IReadableStringCollection valueProvider, string key)
{
            try
            {
                var valueResult = valueProvider[key]; 
                var ret = (valueResult == null) ? default(T) : (T)Convert.ChangeType(valueResult, typeof(T));
                return ret;
            }
            catch (Exception e) { 
                // throws e here saying:Object must implement IConvertible.
            }
            return default(T);
}
```

And calling it like:

```c#
iDisplayLength = GetValue<int>(valueProvider, "length");
sSearch = GetValue<string>(valueProvider, "search[value]");
```

For more reference see file:
https://github.com/RiteshPahwa/AspNetBlog/blob/6ca501284a7ef263bda86ebfbc990aa053fe4ae4/src/ASPNetBlog/App_Common/Paging/DataTables.cs
Line# 79 onwards

**Comment by pranavkm** [comment]
cc @Tratcher - guess this is related to `StringValues`.

**Comment by Tratcher** [comment]
Ah, it would probably work if you did `var valueResult = valueProvider[key].ToString();`

**Comment by RiteshPahwa** [comment]
Ahh. Thx Chris, great!






On Mon, Nov 2, 2015 at 1:54 PM -0800, "Chris R" <notifications@github.com> wrote:












Ah, it would probably work if you did var valueResult = valueProvider[key].ToString();
