### ISSUE TITLE
@Model.XXX will throw Argument encoder does not implement MaxOutputCharsPerInputChar correctly 

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Mvc#3465]
```
      An unhandled exception has occurred: Argument encoder does not implement MaxOutputCharsPerInputChar correctly.
      System.ArgumentException: Argument encoder does not implement MaxOutputCharsPerInputChar correctly.
         在 System.Text.Encodings.Web.TextEncoder.EncodeCore(TextWriter output, Char* value, Int32 valueLength)
         在 System.Text.Encodings.Web.TextEncoder.Encode(TextWriter output, String value, Int32 startIndex, Int32 charac
terCount)
         在 Microsoft.AspNet.Mvc.Razor.RazorPage.WriteTo(TextWriter writer, HtmlEncoder encoder, Object value, Boolean e
scapeQuotes)
         在 Microsoft.AspNet.Mvc.Razor.RazorPage.WriteTo(TextWriter writer, Object value)
         在 Microsoft.AspNet.Mvc.Razor.RazorPage.Write(Object value)
         在 Asp.ASPV__Views_Status_Show_cshtml.<ExecuteAsync>d__33.MoveNext() 位置 /Views/Status/Show.cshtml:行号 76
```

**Comment by Eilon** [comment]
@Kagamine using which version of MVC + DNX?

@Tratcher maybe related to your change?

**Comment by Kagamine** [comment]
The rc2 latest. If your string contains an unknown encoding charactor, it will throw this.

**Comment by Kagamine** [comment]
I think throw an exception is dangerous. When you developed a blog, someone submit a comment with the unknown encoding char to some post, your site will crash down.

**Comment by davidfowl** [comment]
If an exception in a text box can crash your site then you have bigger problems

**Comment by Eilon** [comment]
@Tratcher can you do a quick initial investigation?

**Comment by Kagamine** [comment]
Should I write a repro? @Eilon

**Comment by Tratcher** [comment]
That would help. Preferably something that calls html encoder directly.

**Comment by Tratcher** [comment]
At the very least it would be good to know what the text was that failed.

**Comment by cesarbs** [comment]
This looks like a bug in corefx, I've filed an issue: https://github.com/dotnet/corefx/issues/4455. Notice the repro is really simple.

**Comment by dougbu** [comment]
Why file a CoreFx issue about a bug seen when using Mono? Or is this actually a problem when using .NET core?

**Comment by Kagamine** [comment]
This ouccurred with System.Text.Encodings.Web
