### ISSUE TITLE
mvc model binding json ajax requests

### ISSUE THREAD

**Issue by david-whitehead** [aspnet/Mvc#3466]
iv noticed when doing an ajax post request using content type 'application/json' in beta 8, its always throwing a json exception before hitting the controller action, and no data/ variables are passed to the action method. Although this works when the content type is set to ''application/x-www-form-urlencoded" as its coming through in [fromForm] mode not [fromBody].

```
var postData = { abd: '1', d: '2'};

$.ajax({
type: "POST",
contentType: "application/json",
dataType: "json",

data: postData //or data: JSON.stringify(postData)
})
```

Exception:

```
Event Type	Event	Time	Duration	Thread	Detail Description
Exception	Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll ("Error reading string. Unexpected token: StartObject. Path '', line 1, position 1.")	1,980.82s		[9108]
```

**Comment by Eilon** [comment]
@kichalla can you take a look and see what's going over the wire and where Json.NET is throwing?

**Comment by kichalla** [comment]
I am unable to repro this...the data is bound properly...I tried with the following:

```
function sendData() {
    var postData = { abd: '1', d: '2'};
    $.ajax({
        url:"api/values",
        type: "POST",
        contentType: "application/json",
        dataType: "json",
        data: JSON.stringify(postData)
    });
}
```
@david-whitehead can you share how the raw request looks like (if you are using Chrome you can copy the request/response details by doing `Copy all as HAR`)

**Comment by david-whitehead** [comment]
Hi, thanks for getting back to me, After doing some reason digging i have found some more information out which might be useful.

when using the ajax like below is perfectly fine with specific situations.

ContentType: "application/json",
data: JSON.stringify(postData)

this does does work but only when we are specifically telling the action method parameters to be bound to an object and not directly. For example, the code below will work perfectly fine:-

public class TestDetails
{
[Required]
public string testing1
}

//in mvc not web api
public JsonResult apiEndpoint([fromBody] TestDetails details)
{
.......
}


but the following will not work and is what causes the newton json exception:

public JsonResult apiEndpoint([fromBody] string testing1)
{
.....
}

**Comment by Eilon** [comment]
In the case of this code:

```c#
public JsonResult apiEndpoint([fromBody] string testing1)
{
.....
}
```

That parameter is saying the JSON itself must be a string (e.g. `'foo'` was sent over the wire), but it isn't, it's an object.

**Comment by david-whitehead** [comment]
But if thats the case what would be required for more than one parameter,  as it would have to be sent in object format due to multiple parameters but still has the same issue

**Comment by kichalla** [comment]
You cannot have multiple parameters that have `[FromBody]`. You would need to have a single type encapsulating all that information.

**Comment by david-whitehead** [comment]
But with the other content types you can have multiple fromForm variables should this not be the same for all versions?

**Comment by kichalla** [comment]
Your observation is correct. In case of `FromBody`, the formatters like json and xml and their respective serializers take full control of how the request body is bound to an type. I will let @rynowak @Eilon @dougbu  to give more detailed explanation

**Comment by david-whitehead** [comment]
@kichalla  just wanted to say thanks for this discussion,
 
so generically were saying you should really encapsulate every request in its own object? 

does that not cause quite a bit of excess code that is not really needed for smaller requests i.e. 1 or 2 parameters which do very little, It just seems were creating classes for the sake of it rather than pre-defining our requirements and making the decision on whether or not we should require the parameters to be encapsulated for further needs i.e. validation etc.

**Comment by Eilon** [comment]
You can check out the MusicStore sample app to see how an AJAX request can send the anti-forgery tokens: https://github.com/aspnet/MusicStore/blob/221bf3049219d66730d308f538f4a613cf2c9430/src/MusicStore/Views/ShoppingCart/Index.cshtml

**Comment by danroth27** [comment]
@david-whitehead Yes, to bind data using formatters you need to define a type for the body as the formatter abstraction is a stream to object conversion.

**Comment by cwe1ss** [comment]
Hi, so just to confirm, it is expected behavior that a POST with the body `{ country = "AT" }` can NOT be bound to `public IActionResult Index(string country) { ... }` or `public IActionResult Index([FromBody] string country)`? 

Instead, we need to create a class like this:
```
public class CountryDto { 
  public string Country { get; set; } 
}
``` 
... and use `public IActionResult Index([FromBody] CountryDto country) { ... }` ?

**Comment by dougbu** [comment]
@cwe1ss so confirmed.
