### ISSUE TITLE
Razor page's are not thread safely cached.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#3469]
If two requests are running lock-step two sets of Razor pages will be emitted.

**Comment by Eilon** [comment]
Pointer to teh codez?

**Comment by NTaylorMullen** [comment]
So what's happening is we're attempting to retrieve values from a cache and then setting the cache values non-thread safely.

[Here](https://github.com/aspnet/Mvc/blob/940fb7ba78219301addd42288a08294b20b023bf/src/Microsoft.AspNet.Mvc.Razor/Compilation/CompilerCache.cs#L82-L85) is were we're attempting to retrieve the cache value and then [here](https://github.com/aspnet/Mvc/blob/940fb7ba78219301addd42288a08294b20b023bf/src/Microsoft.AspNet.Mvc.Razor/Compilation/CompilerCache.cs#L124) is were we're finally setting it. If two requests are running in lock-step they'll both enter into the [CreateCacheEntry](https://github.com/aspnet/Mvc/blob/940fb7ba78219301addd42288a08294b20b023bf/src/Microsoft.AspNet.Mvc.Razor/Compilation/CompilerCache.cs#L94) method and then both create a Razor page and set the cache (overriding each other).

If it's only two requests then two dynamic view assemblies will be emitted:
![image](https://cloud.githubusercontent.com/assets/2008729/10954726/00149812-8304-11e5-8871-03a0dfa37e38.png)

This may also be the reason why duplicate break points are created on run if a breakpoint exists in the view.

**Comment by pranavkm** [comment]
@Eilon this is done.
