### ISSUE TITLE
Display(Name = ..) data annotation not being picked up by `span asp-validation-for` for DateTime

### ISSUE THREAD

**Issue by ksk100** [aspnet/Mvc#3476]
Hi,

I think we've come across a bug to do with data annotations not always being picked up - I hope this is the right place/way of reporting this issue (and I hope I haven't missed any open issues which already treat it).  

I'm using `1.0.0-beta8` and find that data annotations of form `Display(Name = "Pretty label")` are not being reflected in the messages printed with `<span asp-validation-for=....>` elements for properties of type `DateTime`.

I can re-create problem with a clean ASP.NET project.  Steps to reproduce:
* Create new project
* Create a form with a `DateTime` field (and a `string` field, for comparison), using appropriate `<label asp-for...>`, `<input asp-for...>` and `<span asp-validation-for...>` elements.
* Create a model to be used by the form
* Mark the string field as required on the model
* Create data annotations for both fields
* Create an action to handle the post
* Submit the form

Results: the data annotation for the `string` is reflected both in the `label` and the error `span` but the data annotation for the `DateTime` is reflected only in the `label` and **not in the error `span`**.

For example, here are the results from my test form (brand new project with steps above followed):

![image](https://cloud.githubusercontent.com/assets/6615834/10938204/330f1206-82f0-11e5-8453-97443b86f4c8.png)

(This date value is being correctly marked as invalid because I'm in the UK).

Thanks.

**Comment by dougbu** [comment]
Are you using Beta 8 or earlier? We fixed bug #3227 in the RC1 milestone and RC1 will be released soon.

**Comment by ksk100** [comment]
Yes beta 8.

Great, thank you.
