### ISSUE TITLE
Component View Location

### ISSUE THREAD

**Issue by mdmoura** [aspnet/Mvc#3477]
Hello,

By default component views location is:

    Views/NameOfControllerUsingComponent/Components/ComponentName/Default.cshtml
    Views/Shared/Components/ComponentName/Default.cshtml

Is it possible to change it to:

    Views/NameOfControllerUsingComponent/Components/ComponentName.cshtml
    Views/Shared/Components/ComponentName.cshtml

It feels strange to have a folder with component name with only default.cshtml in it ...

Can this behavior be changed?

Thank You,
Miguel

**Comment by ShaneCourtrille** [comment]
You are only considering very simple components.  The folder lets you structure more complex components.

**Comment by Eilon** [comment]
@dougbu @pranavkm can you use view location expanders for this? Or just tweak the view engine's search locations or behavior through some interface?

BTW we have no plans to change the current default behavior.

**Comment by dougbu** [comment]
@mdmoura `"Default"` is indeed the default view name for view component views. But `ViewComponent.View()` has overloads such as `View(string viewName)` to override that default.

@Eilon view location expansion provides mostly the beginning of the paths e.g. `Views/NameOfControllerUsingComponent/{0}.cshtml` and `Views/Shared/{0}.cshtml` in the paths @mdmoura showed in the description. But absolute paths override everything -- including the `Components/ComponentName/` bit unconditionally added to a bare view name for view components.

**Comment by Eilon** [comment]
@dougbu sure, but is there another view-resolution-related service that can be used? I don't remember what all services we have these days :smile:

**Comment by dougbu** [comment]
@Eilon not really. The "`Components/ComponentName/` bit" is hard-coded in `ViewViewComponentResult` unless that is given a path instead of a name. View location expanders just add to the places that'll be searched.

**Comment by Eilon** [comment]
@dougbu ah ok that's actually good news then. That means that by re-using code from https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/ViewComponents/ViewViewComponentResult.cs it's fairly easy to customize, if desired.

**Comment by Eilon** [comment]
Closing this because we aren't planning to change the default patterns.
