### ISSUE TITLE
Consider renaming `project.lock.json` to avoid confusion

### ISSUE THREAD

**Issue by robrich** [aspnet/Mvc#3478]
`project.lock.json` is right between `project.json` and `package.json`.  This causes confusion as both `package.json` and `project.json` are very user-centric files edited frequently, and `project.lock.json` is not meant to be edited.  I grant Visual Studio hides this file, but it's not hidden by Visual Studio Code, Sublime, Brackets, or other editors.

Consider renaming this file to `.project.lock.json` or `.lock.json` or `.assembly.json`.  With a leading dot, it's hidden by default on unix filesystems, emphasizing the "non-user" nature of the file.  Renaming it to avoid the word `project` helps differenciate its use from project.json.

**Comment by pranavkm** [comment]
This would be a bug for the runtime \ NuGet. Please file this in https://github.com/aspnet/dnx

**Comment by robrich** [comment]
Thanks for the redirect.  Posted to https://github.com/aspnet/dnx/issues/3133.
