### ISSUE TITLE
FromServices doesnt work in Beta8

### ISSUE THREAD

**Issue by angelsix** [aspnet/Mvc#3483]
I have a controller with a public property decorated with [FromServices]... I have multiple, but all of them are classes available in the service provider.

If I add the properties to the constructor of the controller they get injected (so proves they are in the service provider and available to be injected).

If I add [FromServices] to the public properties they are always null.

**Comment by Muchiachio** [comment]
I'm unable to repro this under beta8.
Seems like your DI configuration is not correct, could you share a small repro project?

**Comment by Eilon** [comment]
@angelsix can you share some more code? Maybe upload a project to GitHub?

**Comment by angelsix** [comment]
I'm in a bit of a rush for a deadline at the moment so cant create a fresh project to test. However there is nothing special. In the ConfigureServices I use the app.ApplicationServices.AddInstance or any other overload to add my classes to. Then when the app is up and running and a controller gets called, which as a public {get;set;} property with [FromServices] on it, and inside the controller constructor and actions they are always null. But doing provider.GetService gets them fine

**Comment by davidfowl** [comment]
> app.ApplicationServices.AddInstance

That's not even a thing. You mean services.AddInstance right?

**Comment by angelsix** [comment]
Yea I was just typing off memory it's on the services


-------- Original message --------

**Comment by dougbu** [comment]
> inside the controller constructor and actions

Which are you actually looking at? MVC does not set (cannot set) controller properties until the instance exists so `null` in the constructor is expected.

**Comment by angelsix** [comment]
They are null in the actions too so no different.

If you place them in the constructor as parameters that works too. The only thing that doesn’t is the [FromServices] which does nothing.


On 6 Nov 2015, at 16:40, Doug Bunting <notifications@github.com<mailto:notifications@github.com>> wrote:


inside the controller constructor and actions

Which are you actually looking at? MVC does not set (cannot set) controller properties until the instance exists so null in the constructor is expected.

**Comment by dougbu** [comment]
:ok: we need to see exactly what you're doing because `[FromServices]` is fairly well tested. You could be doing something slightly different than what we test.

> @angelsix can you share some more code? Maybe upload a project to GitHub?

**Comment by angelsix** [comment]
Ok I made a project from scratch and it worked. I looked back at mine and noticed... I have the setter as private. That was the issue. Overlooked it multiple times.
