### ISSUE TITLE
Proposal: Remove OAuth2 Authorization Server provider application code from Web API project template

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Mvc#3485]
Creating a Web API project with OAuth2 authentication option *Individual User Accounts* selected creates a fairly cryptic OAuth2 Autorization Server provider file with about 100 lines of infrastructural OWIN code.

I admit I feel irritated about so much technical and rather inevitable code supposed to be belonging to a project by default.

To me it doesn't feel right to read in default application code about opaque property collections being shifted from one OWIN `context` to another or to read about the creation of two different `ClaimsIdentity` objects just for the sake of creating an OWIN ticket with no distinctive application intend. *(Moreover, I feel irritated about the prevalence of the word "context". It seems everything not being inherited from a legacy technology is labelled "context" nowadays.)*

Most of the above mentioned code is usually not supposed to be tampered with by the application programmer. It's plain OWIN related code.

I believe that a meaningful, empty project template should come along with almost no source code at all - or at least as little code as possible. A default project template should not deluge the project with infrastructural code.

I believe only *deviant* and *inevitably project individual amendments* should be set, by means of properties and derived classes.

So I propose to redo the Web API OWIN classes and the Web API template in a way that the `ApplicationOAuthProvider` class can be removed. In case any inevitable project individual, deviant configuration needs to be made, these should be added to `OAuthAuthorizationServerOptions` as properties, consisting of lambdas, delegates and derived classes, being utilized by `OAuthAuthorizationServerProvider`. - And if such inevitable project individual properties exist, then they should become parameters of the `OAuthAuthorizationServerOptions` constructor. So it'll become clear that setting these properties is *not* optional, but mandatory.

**Comment by Eilon** [comment]
@SetTrend is this about ASP.NET Web API 2.x, or is this about the new ASP.NET 5 templates?

BTW all the new ASP.NET 5 templates are open source and can be seen here: https://github.com/aspnet/Templates/

**Comment by SetTrend** [comment]
Hi Eilon, this is about Web API 2.2. ASP.NET Web API project templates currently don't allow for Individual User Accounts authentication in Visual Studio 2015.

**Comment by Eilon** [comment]
@SetTrend ah, yes, I think the reason for that is that ASP.NET does not include an authorization server. That is, there is no built-in feature that allows exchanging the Individual Auth username/password for a bearer token, which is what an API would typically use.

Adding @rustd and @blowdart to see if they have any further thoughts.

**Comment by blowdart** [comment]
Pull it all out

**Comment by Eilon** [comment]
@rustd can you work with @blowdart on what changes we want to make here and file a new bug in the appropriate repo?

Also @danroth27 FYI because I'm sure you have some thoughts on this too...

**Comment by SetTrend** [comment]
@eilon : Thanks for sheding light on this for me. Is there a hyperlink to a doc describing how the same behaviour (OAuth2, local + external) is suggested to be done with the new project template?

**Comment by danroth27** [comment]
If you switch the authentication option for the Web API 2.2 template to "No authentication" then this code all goes away.The authorization server code is only included in the Web API 2.2 template if you have the "Individual Accounts" option selected.

**Comment by SetTrend** [comment]
@danroth27 : I comprehend.

But I fell that all of this "sample" implementation should not be in the default template, even with "Individual User Accounts" selected ... No `ApplicationOAuthProvider`, no `ChallengeResult`, no `ApplicationUserManager`, no `ApplicationUser`, just to name a few.

The "Individual User Accounts" template should be able to run right from the beginning with just using the precompiled framework classes (like `OAuthAuthorizationServerProvider`).

If the user would not like the default behaviour coming along with having no code in the project, then he/she will still be able to create their own versions of those classes. Default project templates are not expected to come with sample implementation suggestions, altering an already existing "precompiled sample implementation".

**Comment by danroth27** [comment]
We don't have any plans to change the model for Web API 2.2. We are still in the process of investigating how support for Web API authentication in MVC 6 will work.
