### ISSUE TITLE
Model binder doesn't properly rebind arrays when invalid values are present

### ISSUE THREAD

**Issue by axefrog** [aspnet/Mvc#3489]
I have a model with a property which is an array of nullable floats. An example might look like this:

``` c#
class MyViewModel {
    public float?[] amounts
}
```

In my razor code, I iterate over the length of the array, producing a field for each value. In my own code, it looks like this:

``` razor
@for(var j = 0; j < Model.Categories.Length; j++)
{
  var cat = Model.Categories[j];
  <div class="field edit-value">
    <input asp-for="Tails[i].Values[j]" />
  </div>
}
```

You'll note that my model is actually a nested array of models, so that may be related to this problem- I'm not sure.

In my test case, I have 10 sets of 5 `float?` values for `Tails`. The problem is this: If I enter a non-numeric value in one of the fields, e.g. the second field, then the actual bound model loses any trailing values in the array, even if they're valid. So if the array would have a length of 5 because there are 5 fields, but when posted the second element is invalid, the posted array ends up being only of length 1, and the other posted values that should populate the subsequent array elements are discarded.

So in my code razor above, there are actually 5 entries for `Tails[i].Values[j]`. The second one is invalid, and indices 2, 3, and 4 are discarded, even though they were valid. Instead, the array should be populated with the subsequent values.

In my immediate window in VS2015, I confirmed the following, during rendering after posting the invalid value:

```
ViewContext.ModelState.GetValidationState("Tails[0].Values[0]")
Valid
ViewContext.ModelState.GetValidationState("Tails[0].Values[1]")
Invalid
ViewContext.ModelState.GetValidationState("Tails[0].Values[2]")
Unvalidated
ViewContext.ModelState.GetValidationState("Tails[0].Values[3]")
Unvalidated
ViewContext.ModelState.GetValidationState("Tails[0].Values[4]")
Unvalidated
```

However, `Tails[i].Values.Length == 1`.

**Comment by dougbu** [comment]
@axefrog your experience matches what I expect. Model binding stops as soon as it hits a value that cannot be converted. More generally, properties and collection entries after a model binding error are ignored. This should be consistent for all model binding errors in part because most model binding errors are expensive.

Note that validation continues until either the entire model is checked or `ModelStateDictionary.MaxAllowedErrors` is reached.

**Comment by axefrog** [comment]
Ok, fair enough, though if you're providing a `MaxAllowedErrors` property, the implication is that it is the developer's choice how much of an impact to their performance they're willing to endure; I would imagine that should carry over to collections too. Why is there a performance distinction being made here? The fact that we're talking about a collection should make no difference; whether it's an element of a collection or a named property, the framework doesn't have enough context about the application to make such a decision.

For what it's worth, the property doesn't really apply in my case anyway because I only had one error in the form. The other values were actually valid, and would not have caused any performance issues.

Really, I think that the framework should be processing values that have been posted, up to the `MaxAllowedErrors` value. If that value is hit, then sure, stop validating anything else, but until that point, the fact that the posted field is part of a collection rather than explicitly named is neither here nor there. It's valid user input which is being discarded, and the model is being left in a start where the form UI can't be reproduced upon validation failure.

**Comment by dougbu** [comment]
My comment about `MaxAllowedErrors` and validation was a FYI. Just letting you know model binding and validation are separate systems with separate semantics. Within either there's nothing very different about collections.

**Comment by axefrog** [comment]
Either way, I can't say the behaviour makes sense to me.

> Model binding stops as soon as it hits a value that cannot be converted.

Why? Performance is not the issue, as we seem to have established. For a good user experience, preservation of input values should have precedence here. The current behaviour throws those values away needlessly. Is there some technical limitation in play here?

> More generally, properties and collection entries after a model binding error are ignored.

Why? I'm guessing you mean properties on collection elements, as opposed to properties in general, or the whole idea of a model validation summary would be pointless. Even so, why do you expect this behaviour? It really makes no sense to me at all. If a value is posted, I'd expect some evidence of that fact in the model.

**Comment by axefrog** [comment]
Even though I don't agree with the behaviour, I need to get on with the task at hand. How should I write this line so that it doesn't throw an exception?
```
<input asp-for="Tails[i].Values[j]" />
```

I need the field to be generated as per the relevant data type and collection index, but I'm going to get an `IndexOutOfRangeException` after an invalid post. It would be nice if it could fail gracefully and fall back to a default value or something.

**Comment by dougbu** [comment]
One workaround would be to use `Tails[i].Values.Length` as the limit of your inner loop in the view. Another would be to allocate an array of the length your view expects in the action.

**Comment by axefrog** [comment]
I guess I'll have to iterate through my model looking for arrays of incorrect length and "fix" them. I'm still interested in commentary on the two points I made above though.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
