### ISSUE TITLE
[Bug] OpenID authentication not working correctly with Authorize attribute

### ISSUE THREAD

**Issue by ArieJones** [aspnet/Mvc#3494]
We are experiencing an issue with the Authorize attribute in the current beta 8 build. We noticed it in the current application that we are porting over to MVC 6. 

In the simplest reproduction, we create a default website using the newest templates and select "Work and School Accounts" option for authentication because we will be utilizing Azure AD. Once the project is created we can build and login through our Azure AD domain perfectly. No issues. 

However, when we try to access the Contact or About pages, we are immediately sent back through the Azure AD authentication gauntlet and back to the base URL page. In observing traffic in Fiddler ... we can see 

GET https://localhost:44300/Home/About
302 Redirect to https://login.microsoftonline.com/common/oauth2/authorize?client_id=xxxxx

POST https://localhost:44300/
200 OK (text/html)

GET http://localhost:21847/44ed8f0d7883416d99ee102ebb08d2fa/browserLink
200 OK (text/javascript)

GET https://localhost:44300/Home/Contact
302 Redirect to https://login.microsoftonline.com/common/oauth2/authorize?client_id=xxxxx

POST https://localhost:44300/
200 OK (text/html)

GET http://localhost:21847/44ed8f0d7883416d99ee102ebb08d2fa/browserLink
200 OK (text/javascript)

GET https://localhost:44300/Home/About
302 Redirect to https://login.microsoftonline.com/common/oauth2/authorize?client_id=xxxxx

POST https://localhost:44300/
200 OK (text/html)

We then add another controller into the project ( TestController ) and configure a simple link on the current HomeController's Index page. On the TestController we do not use the Authorize attribute and instead set a breakpoint so that we can observe the User.Identity and find that it is empty. 

If add the Authorize back onto the TestController then we get the same behavior as before with the Azure AD roundabout back to the home page.

**Comment by ThreeSevenths** [comment]
I had the same problem. It turned out that the authorization cookie was only being added to the HTTPS connection, and when I redirected the user back to HTTP, the cookie was lost forcing the 302. My solution was to move the entire app to HTTPS only using URL Rewrite in IIS.

**Comment by ArieJones** [comment]
The only issue is that we are not redirecting the user back to HTTP. The HTTP calls above are from browserlink. When this is disabled then those would go away and you still receive the same outcome. As you can see in the Fiddler output above everything is basically HTTPS calls. 

At first we thought the issue was something with code we had written in the application we are porting but the example above is with the default templates. 

It would be helpful if someone from the team could maybe address this and let us know where we are going awry since it is theoretically going to RTM here.

**Comment by ArieJones** [comment]
It should also be noted that with 4.5.2 MVC templates hooked up with the same Azure AD that the same behavior is not happening. So this looks like a bug to our group here. If we are doing something incorrectly that the templates are not setting up for us out of the box then please let us know.

**Comment by Eilon** [comment]
@rustd have you seen this with Azure AD in the default templates?

**Comment by rustd** [comment]
I don't see this issue with the RC1 templates. Here is what I did:
- Create ASP.NET 5 Web App with Work & School Accounts and Single Sign on
- Run the app and login with Azure AD
- After successful login, click About and Contact pages.
I was able to access them without being redirected back to login with Azure AD

**Comment by ArieJones** [comment]
Is this possibly related just to beta8? 

 Additionally, we wondered if it was our development machines since we are running Windows 10 so we tried the following: 
1. Deployed to Azure => same result 
2. Access Azure Website from 2 other machines( WIndows 7 and Windows 8.1 ) => same result 

The Azure AD that we are utilizing is a secondary Azure AD (for development) with logins that are external to the domain so we also tried: 
1. Creating a user internal to the domain => same result 

Again this is with everything beta 8.

**Comment by ArieJones** [comment]
I guess we should preface this with we don't think that it is necessarily the templates that are the problem here but  with whatever process is supposed to ensure that the security token goes from point A to point B. We're just going to chalk it up to something being broken in the beta 8 build. 

@rustd could you provide us with the build number you are currently using or possibly the sample project it would be appreciated. One of my devs attempted to go with the most recent nightly one and was getting wrapped up in namespace changes and a problem with the dependency on Microsoft.IdentityModel.Protocols.OpenIdConnect  not being found.

**Comment by rustd** [comment]
I was using rc1 builds. The templates are open sourced and you can see the source here https://github.com/aspnet/Templates/tree/release/src/Rules/StarterWeb/OrganizationalAuth/Single
You can check the Startup.cs and compare it with your app.

**Comment by danroth27** [comment]
@rustd Are you able to reproduce this issue with beta8?

**Comment by ArieJones** [comment]
@danroth27 I can confirm that once we upgraded to rc1-final yesterday that it was smooth sailing....everything was back to a working state....

**Comment by rustd** [comment]
Thanks! Closing this out.
