### ISSUE TITLE
Expose ViewResult.Model

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#3495]
For code portability from MVC 5:

https://msdn.microsoft.com/en-us/library/system.web.mvc.viewresult(v=vs.118).aspx

**Comment by Muchiachio** [comment]
:+1: really get's in a way when porting tests.

**Comment by NTaylorMullen** [comment]
Is this still needed? You can do `viewResult.ViewData.Model`. By adding an accessor to `ViewResult` we'd just be adding a 1-off shortcut.

**Comment by pranavkm** [comment]
@NTaylorMullen , isn't this a compat requirement?

**Comment by NTaylorMullen** [comment]
Ya. I just don't see the value in bringing it forward when you can just do `.ViewData.Model`.

**Comment by Muchiachio** [comment]
This doesn't look much, but testing model values returned from the controller actions is already long enough :smile:
```C#
ControllerModel actual = ((controller.Edit(controllerModel) as ViewResult).ViewData.Model as ControllerModel);
```

**Comment by NTaylorMullen** [comment]
29ea696c5ae4f0fbea66ae576147dca9f922446e
