### ISSUE TITLE
Proposal: Project templates should come in two flavours: With scaffolding code and without.

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Mvc#3498]
Many Visual Studio project templates - particularly ASP.NET project templates - come with a vast amount of scaffolding/sample code.

It's nice to get this scaffolding code when learning a new version of the framework.

But later, when creating new projects from the same template, this scaffolding code becomes redundant and subject to immediate deletion. This is particularly true when new versions of auxiliary client/server frameworks emerge (e.g. jQuery, Entity Framework), thereby rendering the scaffolding code obsolete.

Wouldn't it be good to have two versions of each project template: One providing "how-to" scaffolding code, and another, providing nothing but project settings, app.config and one initial application start-up file (if any).

Here's my suggestion: I suggest to add a general checkbox to the "New Project" wizard in Visual Studio, providing an option to have Visual Studio create the project with scaffolding code added, or without.

A checkbox like `□ add scaffolding code` would do.

If the "add scaffolding code" option was checked, the following procedure might take place:
 1. the empty template is created (mandatory)
 1. additional scaffolding files, tagged as something like "IsScaffoldingItem" in the project template manifest, are added to the template

**Comment by Eilon** [comment]
@SetTrend please log this in https://github.com/aspnet/Templates/issues.

Thanks!
