### ISSUE TITLE
Why is OAuthAuthorizationServerProvider coming with callbacks and virtuals?

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Mvc#3499]
I just had a look at the `OAuthAuthorizationServerProvider` class.

It comes with a bunch of `virtual` functions doing nothing but calling callback functions, stored in properties.

This implementation seems rather tautological to me: A derived class may decide whether to override the virtual functions or to overwrite the properties? Or even both?

Is there a reason for this design decision? Otherwise I would suggest to decide for one dropping of them.

**Comment by Eilon** [comment]
@HaoK can you answer this regarding the pattern?

**Comment by Eilon** [comment]
Actually, wait a sec, what type is `OAuthAuthorizationServerProvider`? I don't see it here or in the Security repo...

**Comment by Eilon** [comment]
Is this a template issue?

**Comment by HaoK** [comment]
Perhaps this is an issue regarding katana/old templates (pre ASPNet 5)

**Comment by Eilon** [comment]
@SetTrend which version of ASP.NET / MVC / Web API is this?

**Comment by SetTrend** [comment]
It's v2.2. Perhaps I'm a little late :)

Here's the source I'm referring to: (OAuthAuthorizationServerProvider.cs)(http://www.symbolsource.org/MyGet/Metadata/aspnetwebstacknightly/Project/Microsoft.Owin.Security.OAuth/2.0.1-rtw1-20921-638-dev/Release/.NETFramework,Version%3Dv4.5/Microsoft.Owin.Security.OAuth/Microsoft.Owin.Security.OAuth/Provider/OAuthAuthorizationServerProvider.cs?ImageName=Microsoft.Owin.Security.OAuth)

**Comment by Eilon** [comment]
@SetTrend ah, yes, it's old*er* but not yet old :smile: 

My recollection is that the pattern exists to support a number of different programming patterns:

1. The interface exists in order to allow plugging in a self-contained set of a new behavior. Maximum control.
2. The class implements the interface so that someone wishing to just override a single method can do that without having to stub out all the ones they don't care about.
3. The class has extra properties/methods on it to allow someone *outside* of the class to plug extra things in, such as registering a delegate (you don't have to override/implement anything to do that).

@HaoK and @Tratcher can correct me if I'm wrong here.

**Comment by SetTrend** [comment]
Sure, but ... Anyone implementing a different class (1 or 2) may not call (3), sot basically this design has its flaws.

The flaw is to have the member functions being virtual. They should have been fixed and call the `On...`, like they currently do. That'd have catched all the other cases and would've been water-proof.

**Comment by PinpointTownes** [comment]
> The flaw is to have the member functions being virtual. They should have been "sealed" and themselves call the On..., as they currently do. That'd have catched all the other cases and would've been water-proof. 

Except that overriding a method is simpler and clearer than assigning a delegate in a constructor. If you're not happy with this pattern, nothing prevents you from using your own `IOAuthAuthorizationServerProvider`. Note that it's not specific to the OAuth2 server middleware, as all the security middleware share the same pattern.

> Plus: The OAuthAuthorizationServerProvider doesn't do anything useful. You are actually required to override all the necessary functions because none of the OAuthAuthorizationServerProvider's functions renders a successful result. So (2) acutally doesn't exist.

You don't have to override all the methods, just the most basic ones: `ValidateRedirectUri` if you want to support interactive flows, `ValidateClientAuthentication` for grants using the token endpoint. All the other events are for advanced usage (to validate specific parameters of an authorization request for instance).

> That said - and that was my original intention of this issue - the whole class is basically redundant as one needs to implement it thoroughly in a derived class; mandatory by either overriding the virtuals or implementing the On... callbacks.

> OAuthAuthorizationServerProvider has no use and I believe it should be deleted.

`OAuthAuthorizationServerProvider` (like any other events class) is just here for convenience. If you don't like it, don't use it.

**Comment by SetTrend** [comment]
I'm beginning to understand. Thank you very much for enlightening me on this.

And yes, you are right. One can replace that class by the interface.

I just wanted to state that I feel it's basically redundant. Creating such class from an interface is a single step in Visual Studio.
