### ISSUE TITLE
Removing formatters on a given type only works on collections in MVC options

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#3503]
Currently a formatter can be removed by using the [`RemoveType`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Formatters/FormatterCollection.cs#L19) method on the formatters collection on MVC options 

Example: `options.OutputFormatters.RemoveType<StringOutputFormatter>()`

We have collection of formatters exposed through other areas of the framework like [`ResourceExecutingContext`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Abstractions/Filters/ResourceExecutingContext.cs#L35) where this method cannot be used. An example scenario here is a user trying to have a per-controller specific list of formatters, which he can achieve using  a resource filter

Should we have the formatter collections on MVC options to be just `List<T>` and have an extension method on `IList<T>` which can achieve this scenario? I know this is very generic and need not apply to formatters only

Example:
```
public static class MyExtensions
{
    public static void RemoveType<T>(this IList<T> list, Type itemType)
    {
        var itemTypeInfo = itemType.GetTypeInfo();
        for (var i = list.Count - 1; i >= 0; i--)
        {
            var item = list[i];
            if (itemTypeInfo.IsAssignableFrom(item.GetType().GetTypeInfo()))
            {
                list.RemoveAt(i);
            }
        }
    }
}
```

One observation...`FormatterCollection` is under `Mvc.Formatters` namespace which makes discovering `RemoveType<>` hard

**Comment by Eilon** [comment]
The shown extension method definitely can't be used - we don't usually write such generic extension methods for public consumption. Can `T` be restricted to a particular interface?

**Comment by rynowak** [comment]
> Should we have the formatter collections on MVC options to be just List<T> and have an extension method on IList<T> which can achieve this scenario? I know this is very generic and need not apply to formatters only

We should just make the property on ResourceExecutingContext have the appropriate type.

**Comment by Eilon** [comment]
Sounds good to me.

**Comment by kichalla** [comment]
982c7abea8fc540142dc6566353508f42c4dc352
