### ISSUE TITLE
MVC6 ViewComponent using Anonymous Type as dynamic view model cause "RuntimeBinderException: 'ob...

### ISSUE THREAD

**Issue by wolfgangschneider** [aspnet/Mvc#3504]
Hi

Using anonymos Types as dynamc paramater  is working in C' 6.0

Example (works in Linqpad):
================================================
    void Main()
    {
	    dynamic dyn = new
	    {
		    Prop ="Hallo World"
	    };
        myFunction(dyn);
    }

    public void myFunction(dynamic dyn)
    {
        Console.WriteLine(dyn.Prop);
    }
==================================================
If i try to do this in ASP.net MVC 6 ViewComponent

Controler:
==================================================
     public IViewComponentResult Invoke(int shortTermId)
        {
            dynamic shortTerm = new 
            {
                Name = "Hallo World",
            };
            return View(shortTerm);
       }
====================================================
ViewComponent:
====================================================
    @model dynamic

    <div class="vertTextContainer2">
        <p class="vertical-text2">@Model.Name</p>
    </div>"
=====================================================
Bring up an Binding Error

Same issue on App.Net Forum 

http://forums.asp.net/t/2076846.aspx?MVC6+ViewComponent+using+Anonymous+Type+as+dynamic+view+model+cause+RuntimeBinderException+object+does+not+contain+a+definition+for+

**Comment by dougbu** [comment]
Is this seen in a debugger when catching first-chance `Exception`s? If not exactly how is the `RuntimeBinderException` surfaced?

**Comment by wolfgangschneider** [comment]
RuntimeBinderException: 'object' does not contain a definition for 'Id'

CallSite.Target(Closure , CallSite , Object )


System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)


Asp.ASPV__Views_Accountability_Components_AOPCluster_Default_cshtml.<ExecuteAsync>d__17.MoveNext() in dqt31hmy.xvt


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.Razor.RazorView.<RenderPageAsync>d__17.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()


Microsoft.AspNet.Mvc.Razor.RazorView.<RenderAsync>d__16.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.ViewComponents.ViewViewComponentResult.<ExecuteAsync>d__19.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.ViewComponents.ViewViewComponentResult.Execute(ViewComponentContext context)


Microsoft.AspNet.Mvc.ViewComponents.DefaultViewComponentInvoker.Invoke(ViewComponentContext context)


Microsoft.AspNet.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCore(TextWriter writer, ViewComponentDescriptor descriptor, Object[] arguments)


Microsoft.AspNet.Mvc.ViewComponents.DefaultViewComponentHelper.Invoke(String name, Object[] arguments)


System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)


Asp.ASPV__Views_Accountability_Components_ShortTerm_Default_cshtml.<ExecuteAsync>d__17.MoveNext() in Default.cshtml







14.      @Component.Invoke("AOPCluster", @aop.Id)








--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.Razor.RazorView.<RenderPageAsync>d__17.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()


Microsoft.AspNet.Mvc.Razor.RazorView.<RenderAsync>d__16.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.ViewComponents.ViewViewComponentResult.<ExecuteAsync>d__19.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.ViewComponents.ViewViewComponentResult.Execute(ViewComponentContext context)


Microsoft.AspNet.Mvc.ViewComponents.DefaultViewComponentInvoker.Invoke(ViewComponentContext context)


Microsoft.AspNet.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCore(TextWriter writer, ViewComponentDescriptor descriptor, Object[] arguments)


Microsoft.AspNet.Mvc.ViewComponents.DefaultViewComponentHelper.Invoke(String name, Object[] arguments)


Asp.ASPV__Views_Accountability_Index_cshtml.<ExecuteAsync>d__24.MoveNext() in Index.cshtml







75.                            @Component.Invoke("ShortTerm", Model.ShortTerm[0])








--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.Razor.RazorView.<RenderPageAsync>d__17.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()


Microsoft.AspNet.Mvc.Razor.RazorView.<RenderAsync>d__16.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__1.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.ViewResult.<ExecuteResultAsync>d__24.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultAsync>d__53.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultFilterAsync>d__52.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__51.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResourceFilterAsync>d__46.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__41.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()

**Comment by dougbu** [comment]
@wolfgangschneider should this issue still be open?

**Comment by wolfgangschneider** [comment]
In my opinion it is a bug, and should be open.

**Comment by wolfgangschneider** [comment]
Yes

**Comment by wolfgangschneider** [comment]
Yes

**Comment by pranavkm** [comment]
The generated anonymous type is internal to the Controller assembly. Views are compiled into a different assembly than your Controller. Consequently it can only see the public API surface (i.e. things exposed by an object). You'd need to return a model that is visible outside your assembly for this to work.
