### ISSUE TITLE
Visual Studio tag helper syntax highlighting not working per project

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Mvc#3506]
In one of my ASP.NET 5 projects, the syntax highlighting and intellisense in cshtml files doesn't work. Another project on the same machine works fine, leading to the belief it is in the project configuration?

I have the `@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"` in _ViewImports.cshtml and everything renders fine, but the tooling seems to be broken for this specific project.

Is there another place this would be disabled/wrongly configured?

**Comment by Kukkimonsuta** [comment]
What runtime version are you targetting? The tooling seems to only work for exact version that it was installed with. So for instance latest VS tooling is `beta8`, so the tag helpers are highlighted only for `beta8` projects, but once I switch to `rc1` or `rc2` the highlighting goes away.

**Comment by Eilon** [comment]
@NTaylorMullen @ToddGrun any ideas on this?

**Comment by NTaylorMullen** [comment]
Today, here's the criteria to have `TagHelper` IntelliSense:

- IF you want the built-in `TagHelper`s ensure the package is in the `project.json` (`Microsoft.AspNet.Mvc.TagHelpers`).
- `Microsoft.AspNet.Tooling.Razor` package
- `@addTagHelper "*, TheAssemblyWithTagHelpers"`
- targeting framework dnx451.

**Comment by damienpontifex** [comment]
Thanks @NTaylorMullen it was the `Microsoft.AspNet.Tooling.Razor` package I was missing.

**Comment by NTaylorMullen** [comment]
Awesome, glad to hear it worked out :+1:

**Comment by damienpontifex** [comment]
I can't remember, but I may have generated the project with yeoman and hence missed the tooling package. As I didn't find this info before filing this issue, is there somewhere this should be documented for me to make a pull request against?

**Comment by NTaylorMullen** [comment]
I believe we have it documented over at https://docs.asp.net/en/latest/
