### ISSUE TITLE
Taghelper [Bug]

### ISSUE THREAD

**Issue by GVX111** [aspnet/Mvc#3508]
<pre>Encountered an unexpected error when attempting to resolve tag helper directive '@addTagHelper' with value '"*, Microsoft.AspNet.Mvc.TagHelpers"'. Error: The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"</pre>

**Comment by davidfowl** [comment]
More info please.

**Comment by GVX111** [comment]
<pre> "dependencies": {
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-*"
  },
_ViewImports.cshtml
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
</pre>

**Comment by davidfowl** [comment]
That's not good enough. Try making a runnable sample and putting it on github so we can run it and see the error.

**Comment by Kukkimonsuta** [comment]
This error is thrown when using latest bits and not removing quotes from `@addTagHelper`s value.

See https://github.com/aspnet/Announcements/issues/103

**Comment by Eilon** [comment]
Yeah this sounds like the quotes issue. On the latest dev builds just remove the quotes from the directive and you're good to go.

**Comment by GVX111** [comment]
Great. Thank you.
Fixed. @Kukkimonsuta
