### ISSUE TITLE
on returning Json( )

### ISSUE THREAD

**Issue by GVX111** [aspnet/Mvc#3509]
<pre>InvalidOperationException: No service for type 'Microsoft.AspNet.Mvc.Infrastructure.JsonResultExecutor' has been registered.</pre>

**Comment by davidfowl** [comment]
@GVX111 Can you provide some more context for your bugs. Error messages are appreciated but it would be great if you could provide a sample application with versions of things being used so it would help us narrow it down.

**Comment by GVX111** [comment]
@davidfowl I fixed now. I have added  services.TryAddSingleton<JsonResultExecutor>(); Before UseMvcCore()
Can you help me on https://github.com/aspnet/Mvc/issues/3508

**Comment by rynowak** [comment]
If you're using `JsonResult` make sure to include `.AddJsonFormatters` in your startup

**Comment by GVX111** [comment]
@rynowak  in rc1 AddJsonFormatter doesn't need after update to rc2 it must include in startup?
I solve with services.TryAddSingleton< JsonResultExecutor >();
