### ISSUE TITLE
Mocking MVC

### ISSUE THREAD

**Issue by ankitbko** [aspnet/Mvc#3511]
I have multiple development team - Client side development, Service Development and others. Client side is a SPA. Is there a way to mock controllers so as my client side development can happen independently.

**Problem Statement:**
Client side needs data to test, however my service is not complete. My service might not be returning data for multiple reasons - service not implemented, underlying layers are not implemented, no data in DB etc. However I do have well defined models which will be serialized and returned from service. I also have sample data in json format.

One of the current practice is to mock the service call in client side. For example, in case of Angular, mock the angular service, use $httpbackend to mock the service call or just point to json file containing sample data instead of calling actual service. However I see few issues with this approach-
* I do not actually call my service, which might be doing additional work in middleware. 
* Each client side framework has different way to mock calls.

**What is needed:**
Controller's Action should be mocked. Client should not be aware whether data being returned by service is mocked(fake) or real. Client should call the service endpoint passing required headers. When a call hits my service, it should proceed though middlewares till it hits the appropriate Controller's Action. At this point, I intercept the call to action and return a response with sample data. 
This needs to be configurable, i.e for each action I can configure whether it is mocked or not.

**Result:**
This would definitely make client side development easier. I can configure for an action to be mocked, and need not wait till its underlying development is done. Once my service is developed, I can just switch off the mocking from config and service now returns actual data.

What is the best practice to do it? How is this done in industry currently?  Is something of this sort readily available for .net webapi/mvc?

**Comment by Eilon** [comment]
I would recommend mocking the data service layer, not the MVC actions.

You could use environments to control this when you set up your application.

E.g. you'd have an `IDataRepository` interface and two implementations of it: a real one (eventually) that talks to real data. And a fake one that returns fake data. Depending on the app's current configuration, you would choose which implementation of the interface to register: the real one or the fake one.

**Comment by ankitbko** [comment]
That's one way to do it. However I was looking at something that is plugable from outside. The problem with the above approach is that I'll have to create two implementations. This clutters the codebase and for any change I'll have to rebuild the project. 
The project I am working is quite huge. In fact there are multiple teams and 50+ developers. Moreover we have Microservice architecture resulting in lots of services. This was main reason why I wanted to decouple this with actual development. Though the above solution will still work I was thinking of any elegant solution.

We already have all the metadata about services available from ApiExplorer (same way as  Swashbuckle does for swagger docs generation), maybe we can handle this in a middleware.
I was grooming about this and thought whether we can create a middleware similar to DeveloperExceptionPage and overwrite Response object's properties based on the configuration.
Can this be achieved? Can a middleware overwrite Response object? If this can be done, an independent framework can be created and used across projects.

**Comment by Eilon** [comment]
I still don't feel that mocking an API at the *controller action* layer is correct. That is really just an implementation detail of a service. I think mocking it at a much more distant layer makes more sense:

1. Mock it at the call site and avoid *all* the implementation details, including that it even goes over a network. That's my preference.
2. Mock it at the destination, but at a very low layer. For example, you could have a web server that traps certain URLs and returns canned responses for them.

**Comment by ankitbko** [comment]
I understand your viewpoint to mock at either end. Mocking at client side makes me loose benefits of middlewares such as Authorization, versioning etc. Also the mocking implementation differs with different client side framework.
We do mock each layer on server side for unit testing. However creating a fake implementation of underlying layer just makes codebase large. 
I was looking at something similar to SoapUI mocking or mockable.io which integrates with asp.net while preserving the middlewares as mentioned above.
I will check how we can achieve this for our project and see how well each of these process fits.

Thank you for quick responses.
