### ISSUE TITLE
Return type based on content negotiation

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Mvc#3521]
Considering MVC & Web API are now merged and can be served from the same controller, I was wondering if there is a way to return an appropriate type for the requested content type?

For example, consider a POST request that was successful:
From a form/MVC we may `return RedirectToAction("Index")`
From a REST call with JSON, `return new ObjectResult(newObject);`

Is there a return type that either the route or object could be returned as appropriate?

**Comment by dougbu** [comment]
@damienpontifex MVC 6 provides content negotiation. What in particular are you looking for?

**Comment by damienpontifex** [comment]
Say a simple post method you would have in your controller like this to respond to a form submission on a page:
```c#
[HttpPost]
public IActionResult Post(MyModel model)
{
    if (ModelState.IsValid)
    {
        // Save model as appropriate
        return RedirectToAction("Index");
    }

    return View(model);
}
```

Vs I have been writing this for an API endpoint for a JSON result
```c#
[HttpPost]
public IActionResult Post(MyModel model)
{
    if (ModelState.IsValid)
    {
        // Save model as appropriate
        return CreatedAtRoute("Details", new { id = model.Id }, model);
    }

    return HttpBadRequest(ModelState);
}
```

Can I merge these methods (only have one POST method) and still get the same functionality as their only difference is the return objects? i.e. first returns HTML, second returns JSON.

**Comment by Eilon** [comment]
@damienpontifex so you are looking to do action selection based on the request's Accept header?

I *think* you're looking for the `[Consumes]` attribute: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ConsumesAttribute.cs#L19

And here's an example: https://github.com/aspnet/Mvc/blob/eef6c3883a7e27b8387b0925f0b6a88df0a484c5/test/WebSites/ActionConstraintsWebSite/Controllers/ConsumesAttribute_NoFallBackActionController.cs#L9-L22

**Comment by damienpontifex** [comment]
@Eilon actually the exact opposite really. I want to merge the methods, but not have to do a check to determine whether to return JSON or HTML.

**Comment by Eilon** [comment]
Ah I see. I don't believe there's any built-in feature of MVC for this. You could write an ActionExecutedFilter to sniff the header and convert the result. Do you want to give that a try?

**Comment by damienpontifex** [comment]
Haven't done one in the past, but very happy to give it a try. Do you have a link on the documentation/source for implementing one?

**Comment by danroth27** [comment]
I think you could create a ViewOrJsonActionResult and return that. The action result would decide based on the accept header whether to render the view or render JSON.
