### ISSUE TITLE
Strings should not be Localized before localization is called

### ISSUE THREAD

**Issue by Anderman** [aspnet/Mvc#3522]
I have the following code.
```
  [EmailAddress]
        public string Email { get; set; }
```
and added this to my mvc config
```
)
                .AddViewLocalization(options => options.ResourcesPath = "Resources")
                .AddDataAnnotationsLocalization()
```

See https://github.com/aspnet/Mvc/issues/3434.

The errormessage is already  localized before 
```
errorMessage = _stringLocalizer[Attribute.ErrorMessage];
```
is called

This is done in project Microsoft.Aspnet.MVC.Viewfeatures in RemoteAttrribute.cs
```
public override string FormatErrorMessage(string name)
        {
            return string.Format(CultureInfo.CurrentCulture, ErrorMessageString, name);
        }
```

I thought is is not the only one  and looked for all reference to the `Format(culture,...`
Which give me this list of 150 possible issue about localization.

It is not clear to me how this should work. Should all system generated error message bypass the localization framework. Or should all displayname and error messages go through the localization framework.

It would be nice if all displaynames and error message go through StringLocalizer[] and if 
`stringLocalizer[Attribute.ErrorMessage,displayName].ResourceNotFound == true` the fallback is called.
` string.Format(CultureInfo.CurrentCulture, ErrorMessageString, name);`

**Comment by dougbu** [comment]
Do you have a scenario in which the error message for `RemoteAttribute` is not localized as you expect? I ask because `ValidationAttribute.ErrorMessage` does not call `FormatErrorMessage()`.

**Comment by Anderman** [comment]
@dougbu I Use Beta8 and I see a lot of issue with the localization. see https://github.com/aspnet/Mvc/issues/3434

Is it correct that only custom error message can be localized?

If that is the case: 
Then this issue is caused by not correct  checking if a custom errormessage is set on an attribute

**Comment by Eilon** [comment]
I think only a custom error message should be localized through `IStringLocalizer`. There's no reliable way to know what the system default error message is, or whether it's already localized.

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by Eilon** [comment]
This is by design because ASP.NET can't localize content that might already have been localized by .NET itself. You need to set your own neutral culture (e.g. English) message, and then provide your own localized versions of that message.
