### ISSUE TITLE
Remove MvcSample and add an MvcSandbox instead

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#3529]
MvcSample served its purpose and can now be buried.

MvcSandbox is a minimal MVC app that:
1. Has a basic startup.cs with basic code
2. Has a HomeController with an Index action
3. Has a Home/Index.cshtml view and a shared layout page
4. And add a .gitignore file to that folder to prevent people from inadvertently checking into this folder

**Comment by ryanbrandenburg** [comment]
Also check that ajax requests validate as form data. If they don't then make another sample which uses Mvc.js to write data which will be auto-magicaly Model-Bound.

**Comment by ryanbrandenburg** [comment]
Upon investigation Mvc.js doesn't need saving because you can easily just do:

var person = {
    Person: {
        Name: "ryan",
        Job: "Engineer"
    }
};

$.post("Home/Ajax", person);

and it will bind now.

**Comment by ryanbrandenburg** [comment]
Fixed in #3574
