### ISSUE TITLE
    No errormessage is added to the validation rule    [DataType(DataType.EmailAddress, ErrorMessage = "Not a valid Email address")]

### ISSUE THREAD

**Issue by Anderman** [aspnet/Mvc#3533]
With  [DataType(DataType.EmailAddress, ErrorMessage = "Not a valid Email address")] attribute

The field will be validated in the browser but the error message is from jquery validation.js
``` HTML
<div class="form-control-wrapper">
<input class="form-control input-validation-error" type="email" id="Password" name="Password" value="" aria-invalid="true" aria-describedby="Password-error">
<div class="floating-label" for="Password">PwPassword(NL)</div>
   <span class="text-danger field-validation-error" data-valmsg-for="Password" data-valmsg-replace="true">
     <span id="Password-error" class="">Please enter a valid email address</span>
   </span>
</div>
```

**Comment by dougbu** [comment]
@Anderman please add the relevant bits of your `.cshtml` file.

**Comment by dougbu** [comment]
Also, does `[EmailAddress(ErrorMessage = "Not a valid Email address")]` work more like you expect?

**Comment by Anderman** [comment]
@dougbu that's correct I should use that


With the DataType Attribute you can also set a ErrorMessage

        [DataType(DataType.EmailAddress,ErrorMessage ="Field {0} is not a valid email address")]
        public string Email { get; set; }

So I expected this html

```
<input class="form-control" type="email" data-val="true" data-val-email="Field Email is not a valid email address" id="Email" name="Email" value="">
``` 

But I got this
```
<input class="form-control" type="email" id="Email" name="Email" value="">
```

**Comment by danroth27** [comment]
You need to use `[EmailAddress(ErrorMessage = "Not a valid Email address")]`. Although the `DataTypeAttribute` is a `ValidationAttribute` it doesn't actually validate anything and is only for display and formatting purposes.
