### ISSUE TITLE
Optimize allocations in UrlResolutionTagHelper when it no-ops

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3534]
The usage patterns for doing things like reading taghelper attributes need to allocation free for the kinds of things done in this taghelper.

![image](https://cloud.githubusercontent.com/assets/1430011/11107730/705b82c0-8895-11e5-9e95-ec55189209b6.png)

**Comment by pranavkm** [comment]
The `Enumerable.Where` has already been removed as part of https://github.com/aspnet/Razor/issues/599. We could go one step further and have `TryGetAttribute` return an `IReadOnlyList<T>` instead (it allocates a `List<T>` internally, so it wouldn't be much of a code change. Thoughts?

cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
@pranavkm sounds fine with me :smile:
