### ISSUE TITLE
MaxLentghAttribute should be localized with two parameters

### ISSUE THREAD

**Issue by Anderman** [aspnet/Mvc#3535]
MaxLength attribute should be localized with two paramters

return _stringLocalizer[Attribute.ErrorMessage,displayName,Attribute.Length];
remarks
* To be consistent: Displayname should also be localized

setup
```
        [MaxLength(10, ErrorMessage = ""Het veld {0} moet een tekenreeks- of matrixtype zijn met de maximumlengte '{1}'.")]
        [Display(Name = "PwPassword", ResourceType = typeof(loc))]
        public string Password { get; set; }

```

**Comment by Eilon** [comment]
Closing as an effective dup of https://github.com/aspnet/Mvc/issues/3537.
