### ISSUE TITLE
Minlength should be localized with 2 parameters

### ISSUE THREAD

**Issue by Anderman** [aspnet/Mvc#3536]
See https://github.com/aspnet/Mvc/issues/3535

setup

        [MinLength(10, ErrorMessage = "Field {0} minlength is {1}")]
        [Display(Name = "PwPassword", ResourceType = typeof(loc))]
        public string Password { get; set; }

**Comment by Eilon** [comment]
Closing as an effective dup of https://github.com/aspnet/Mvc/issues/3537.
