### ISSUE TITLE
Required should has 2 parameters to localize

### ISSUE THREAD

**Issue by Anderman** [aspnet/Mvc#3539]
RequieredAttribute has 2 paramaters and should be localized like

_stringLocalizer[Attribute.ErrorMessage,displayName]

setup

        [Display(Name = "PwPassword", ResourceType = typeof(loc))]
        [Required(ErrorMessage = "field {0} is req ")]
        public int Custom { get; set; }

**Comment by Eilon** [comment]
Closing as an effective dup of https://github.com/aspnet/Mvc/issues/3537.
