### ISSUE TITLE
StringLength attribute should be localized with 3 parameters

### ISSUE THREAD

**Issue by Anderman** [aspnet/Mvc#3540]
StringLength Attribute has 3 paramaters and should be localized like

_stringLocalizer[Attribute.ErrorMessage,displayName, max,min]

Remark.
* Support 2 version?? like https://github.com/Microsoft/referencesource/blob/master/System.ComponentModel.DataAnnotations/DataAnnotations/StringLengthAttribute.cs

setup

        [Display(Name = "PwPassword", ResourceType = typeof(loc))]
        [StringLength(10,MinimumLength =1,ErrorMessage = "The field {0} must be a string with a minimum length of {2} and a maximum length of {1}")]
        public int Custom { get; set; }

**Comment by Eilon** [comment]
Closing as an effective dup of https://github.com/aspnet/Mvc/issues/3537.
