### ISSUE TITLE
Logging: Suggest adding more output at `LogLevel.Verbose`, removing some 

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3541]
My general metric is that `LogLevel.Verbose` should output at least three times as many _useful_ messages as `LogLevel.Information`. Logging from the MVC repo does not currently meet this expectation.

On the not-so-useful side, a few `Verbose` messages subset `Information` or other `Verbose` output:
```
verb: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[1]
      Executing action MusicStore.Controllers.HomeController.Index
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method MusicStore.Controllers.HomeController.Index with arguments () - ModelState is Valid'
```
...
```
verb: Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor[0]
      The view 'Index' was found.
info: Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
```
and perhaps (wouldn't look redundant if other information was logged while executing the view component)
```
verb: Microsoft.AspNet.Mvc.ViewComponents.DefaultViewComponentInvoker[1]
      Executing view component MusicStore.Components.GenreMenuComponent
verb: Microsoft.AspNet.Mvc.ViewComponents.DefaultViewComponentInvoker[2]
      Executed view component MusicStore.Components.GenreMenuComponent in 0.0031ms and returned Microsoft.AspNet.Mvc.ViewComponents.ViewViewComponentResult
```

In addition some `Verbose` messages describe result types, not interesting contents e.g. the `ViewName`.
```
verb: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[2]
      Executed action method MusicStore.Controllers.HomeController.Index, returned result Microsoft.AspNet.Mvc.ViewResult.'
```
and
```
verb: Microsoft.AspNet.Mvc.ViewComponents.DefaultViewComponentInvoker[2]
      Executed view component MusicStore.Components.GenreMenuComponent in 0.0031ms and returned Microsoft.AspNet.Mvc.ViewComponents.ViewViewComponentResult```
```

On the other hand, some view features really come alive at the `Verbose` level -- view components in particular. But need at least a summary of all pages executed (view starts, layouts, partials, templates) for a request.

Similarly
- An additional level of detail about the model binding system beyond `ModelState is Valid` would be to list binders used and a count of `ModelStateDictionary` entries.
- What `Exception`s were silently handled e.g. were our favourite `NullReferenceException`s caught while evaluating user expressions? Might help to document that avoiding these `Exception`s can improve the perf of a site.
- What custom filters were invoked?
- ...

**Comment by Eilon** [comment]
Where did the idea of verbose should be ~3 times as chatty as informational come from? We have no such guideline, nor do I think that is a particularly useful metric to use...

But I agree that there's some cleanup warranted in MVC's logging.

**Comment by danroth27** [comment]
Let's hold off on doing additional tweaks here until we get some customer feedback on the current logging data.
