### ISSUE TITLE
app.Map() changed behavior or stopped working as intended

### ISSUE THREAD

**Issue by jupdidu** [aspnet/Mvc#3543]
Since I switched to beta 8 of MVC I have problems getting app.Map() to work.

Here is the Configure method of my Startup class:

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        app.Map("/modules/someModule", builder =>
        {
            app.UseMvc();
        });
    }

This code worked as expected in Version 5.2.3, e.g. I had to enter the URL http://localhost:5000/modules/someModule/api/values to access the example ValuesController. However in the new beta 8 I get a 404 response this way and the resource is located under http://localhost:5000/api/values instead. The app.Map() does not seem to do anything at all at the moment.

I am running the testproject under version 1.0.0-beta8 of the .NET Core and x64 architecture. Also I am using the Kestrel server as host. This is my project.json:

    {
      "commands": {
        "kestrel": "Microsoft.AspNet.Server.Kestrel"
      },
      "dependencies": {
        "Microsoft.AspNet.Mvc": "6.0.0-beta8",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8"
      },
      "exclude": [
        "node_modules"
      ],
      "frameworks": {
        "dnxcore50": { }
      },
      "publishExclude": [
        "**.user",
        "**.vspscc"
      ],
      "version": "1.0.0-*"
    }

**Comment by davidfowl** [comment]
This code:

```C#
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.Map("/modules/someModule", builder =>
    {
        app.UseMvc();
    });
}
```

Should be:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.Map("/modules/someModule", builder =>
    {
        builder.UseMvc();
    });
}
```

**Comment by jupdidu** [comment]
I feel so stupid now... sorry for the issue...

**Comment by Eilon** [comment]
Hah, I had to read @davidfowl 's code THREE times until I saw the difference! :smile:

**Comment by Hiblet** [comment]
I'm here because I did the same thing.  Triple Doh!
