### ISSUE TITLE
PasswordHasher without AspNet.Identity references

### ISSUE THREAD

**Issue by angelsix** [aspnet/Mvc#3545]
I'm creating a password hasher that is not in the Web layer so wont have references to Asp.Net.

I cannot find KeyDerivationPrf or KeyDerivation.Pbkdf2(...).

From source it appears the it is in the Microsoft.AspNet.Identity that they are inside Microsoft.AspNet.Cryptography.KeyDerivation. Yet it doesnt find that reference, I cannot find that reference, and nowhere on github in these source files can I find it. So I cannt implement the password hasher.

**Comment by pranavkm** [comment]
Referencing `Microsoft.AspNet.Cryptography.KeyDerivation`  should work.

**Comment by angelsix** [comment]
I dont want to reference Asp.Net thats the whole point (first part of the message). I also cannot find the source to Microsoft.AspNet.Cryptography.KeyDerivation in order to copy the code out of the Asp.Net reference.

**Comment by henkmollema** [comment]
It's here: https://www.nuget.org/packages/Microsoft.AspNet.Cryptography.KeyDerivation.

I used it to port the PasswordHasher using ASP.NET 5 data protection stack: https://github.com/henkmollema/CryptoHelper.

**Comment by angelsix** [comment]
Thanks but that also doesnt work on CoreCLR only normal .Net. I need it on a platform that runs CoreCLR DNX50

**Comment by henkmollema** [comment]
Why not? The package targets DNX Core 5.0. Use the [beta8](https://www.nuget.org/packages/CryptoHelper/1.0.0-beta8) package if you want it to use with beta8 bits.

**Comment by angelsix** [comment]
Oh yeah sorry I didn't look far. The #if defines made it uncompilable, but I just updated them to checks for CoreCLR flags and it looks usable. Thanks

**Comment by angelsix** [comment]
Actually no it doesnt work. The Rfc2898DeriveBytes class is in DNX451 only, not available in DNX50 as its in System.Security.Cryptography?

**Comment by henkmollema** [comment]
That's why it uses `#if` def's. It uses [`KeyDerivation.Pbkdf2`](https://github.com/henkmollema/CryptoHelper/blob/fc63745e12594f4dd79a1eeffe9e45a8c746aea4/src/CryptoHelper/Crypto.cs#L173) on DNX Core 5.0.

**Comment by angelsix** [comment]
Ah yes sorry, I messed up my #if's as I have DNX451 not NET4... so when I was naming a few and re-organizing a moved it to the wrong place. Building fine now thanks
