### ISSUE TITLE
Where did Request.UserLanguages go?

### ISSUE THREAD

**Issue by rhegner** [aspnet/Mvc#3549]
In ASP.NET 4.5 Controllers I was able to query the user's preferred languages using 

    Request.UserLanguages

This does no longer seem to be available. What are alternatives?

**Comment by Eilon** [comment]
@rhegner I believe you just read the header yourself. Or, use the new ASP.NET 5 [localization middleware](https://github.com/aspnet/Localization/blob/dev/samples/LocalizationSample/Startup.cs#L61) to enable parsing of the culture header, and then get the desired value through [`IRequestCultureFeature`](https://github.com/aspnet/Localization/blob/dev/samples/LocalizationSample/Startup.cs#L75).

**Comment by rhegner** [comment]
Thanks, that helped! I'm using the localization middleware now.

**Comment by Eilon** [comment]
Great!
