### ISSUE TITLE
Pool JsonSerializer instances

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3550]
See data here:

![image](https://cloud.githubusercontent.com/assets/1430011/11124519/514e15ca-891a-11e5-82e6-88a4db8a59a9.png)

See comment from @JamesNK here: https://github.com/aspnet/Mvc/issues/3542#issuecomment-156200726

**Comment by rynowak** [comment]
Partial fix here: e75eebbed000541f05dda8e9f524b445ba0722ff for output formatters. 

Fixing input will take some doing.

**Comment by JamesNK** [comment]
Keep in mine that JsonSerializerSettings is mutable. Changing configuration on it without updating the JsonSerializer could confuse some users.

**Comment by rynowak** [comment]
Load balancing this to a Pranav

**Comment by pranavkm** [comment]
Merged in cf9221df073467f0e6bae910f65a6957cd29523e
