### ISSUE TITLE
Potential invalid operation exception?

### ISSUE THREAD

**Issue by herecydev** [aspnet/Mvc#3558]
Just scanning some code out of curiosity when I spotted [this](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/FileResult.cs#L74).

If you're specifying it's a required service then line 74 doesn't need the `?.`. 
Otherwise, if that was changed to `GetService` then you could have a null reference exception [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/FileResult.cs#L91).

**Comment by davidfowl** [comment]
Seems like a mistake to be doing `?.`

**Comment by Eilon** [comment]
My guess is that it was to make our own testing easier. The null would probably be harmless in the real world. But might as well clean up the code.

**Comment by Eilon** [comment]
Oh sorry didn't see there's a PR for it: https://github.com/aspnet/Mvc/pull/3559

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/db94a8ed19e626b4e094cc283abe0dfe4f39871f
