### ISSUE TITLE
Check WhiteSpace in Microsoft.AspNet.Mvc.AreaAttribute constructor

### ISSUE THREAD

**Issue by sparraguerra** [aspnet/Mvc#3560]
I think AreaAttribute constructor should raise an exception when areaName parameter is WhiteSpace.
This code
```cs
if (string.IsNullOrEmpty(areaName)) 
{ 
      throw new ArgumentException("Area name must not be empty", nameof(areaName)); 
} 
```

Should be?
```cs
if (string.IsNullOrWhiteSpace(areaName)) 
{ 
      throw new ArgumentException("Area name must not be empty", nameof(areaName)); 
}
```

**Comment by pranavkm** [comment]
There are plenty of instances in Mvc \ Razor \ Routing where we only check for null or empty for string parameters. Why would this one in particular be any different?

**Comment by Eilon** [comment]
Whitespace isn't that special. If someone typed it in, keep it. It would be somewhat arbitrary to check for whitespace here (or almost anywhere).
