### ISSUE TITLE
UAP 10.0 and Microsoft.AspNet.Mvc

### ISSUE THREAD

**Issue by meriturva** [aspnet/Mvc#3561]
Any way to run Asp.net 6 on Windows IoT ? Actually i'm trying to integrate on a Universal Windows project a simple controller but no way, no package compatible with UAP, do i have to move to adapt different solution like netmf web servers?

is it related to: 
https://github.com/NuGet/NuGet.Client/pull/105
https://github.com/aspnet/dnx/issues/2302
?

**Comment by davidfowl** [comment]
Nobody has tried it so I doubt it works. It's not a priority at the moment but we're OSS so if you'd like to try that would be a good first step.

**Comment by meriturva** [comment]
Just to know....will be possible in the future to embed a Owin VNext asp application into a UAP project?
What do you think?

**Comment by Eilon** [comment]
@meriturva it would depend on there being a proper HTTP listener / server for UAP, and I don't know if that's the case. Ultimately, something has to listen on some port. The rest of MVC would then possibly work.

**Comment by meriturva** [comment]
I'm really confused actually.....on one hand we have the possibility to create a Windows IoT project (Universal Windows) but not to use ASP.NETvNext because is not compatible with UAP 10.0
On the other hand we have a way to run ASP.NETvNext on ARM with DNX as for example: https://github.com/DamianEdwards/PiDnx

Do you think that the only solution here to have a modern WebServer and a simple XAML UI on Windows IoT is to deploy two different projects (DNX for WebApi + UAP for UI) running together but based on different .net frameworks? What about the future?

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by meriturva** [comment]
Hi @danroth27 ... any news?
So thanks.

**Comment by Eilon** [comment]
@meriturva it's simply not a scenario we've spent any time investigating. ASP.NET is primarily a technology for web servers and not UAP apps. If you want to experiment in this area we can certainly chat, but we are not planning to do any work here ourselves at this time.

**Comment by meriturva** [comment]
Thanks for the answer @Eilon ,
actually i'm making few sample projects to find a way to use vNext on IoT device.
I'm deployed a web project on Raspberry but it dosen't work because of: https://github.com/aspnet/KestrelHttpServer/issues/216

On the other hand i sure have to use GPIO inside "web api controllers" (we are on a Raspberry to use serials ports and I/O) so i try to include the package: Microsoft.NETCore.UniversalWindowsPlatform into the vNext project without success.

So now new question:
* How do i have to use GPIO inside a vNext project?

I don't see any concrete way to develop a system that has vNext Self Hosted Web Api controllers acting on GPIO interface. Do i have to move to a different rest/web socket solution and still on a simple UWP project? But why? We are on the same ARM platform architecture! No?

**Comment by Eilon** [comment]
Closing because we are not planning to make any changes in MVC related to this.

cc @davidfowl @DamianEdwards does anything here resonate w/ stuff we're doing for non-HTTP based servers?
