### ISSUE TITLE
Property validation 

### ISSUE THREAD

**Issue by hanu412** [aspnet/Mvc#3562]
I have a scenario where I am querying the database and creating a collection of elements. I need to perform certain data validations before I can process this data to the UI. Initially the requirement was simple - I needed to validate individual properties like MinLength, Required , Regex etc.
Now,the business requirement is complex which needs me to validate a property based on the value of another property in the same class. 

Ex : I have a student class with props - Id,Age,Roll,Standard
I need to validate Standard based on Age & Roll 
 if(Age>12 && Age <=16 && Roll >228) { some business code..}

I considered data-annotations initially but now I with these complex validations(I have 300+ properties),I am stuck. I tried writing if-else blocks but that actually increased my code-complexity due to more branches. 

Is there a possibility to perform these type of validations in .net in a better/cleaner manner? If not, can somebody point to me how do I write better code for this type of validations?

**Comment by dougbu** [comment]
@hanu412 I recommend using data annotations as much as possible, especially for single-property validations. That works well in MVC and is generally simpler than other approaches. For example the system can automatically generate attributes for client-side validation.

Annotating your type with `[CustomValidation]` or an attribute implementing `IModelValidator` may end up with similar complications. But the `IModelValidator` will be invoked with slightly more context information (see [`ModelValidationContext`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Abstractions/ModelBinding/Validation/ModelValidationContext.cs)). If that's not quite flexible enough, your application can get directly involved in the validation discovery, adding to the `MvcOptions.IModelValidatorProvider` list. Really up to you and the specific requirements of your application which of these approaches is cleanest for your multi-property validations.

**Comment by atrauzzi** [comment]
Just doing some research into validation options in MVC, but has any thought been put into creating some kind of API/facility for contextual validation?

A lot of the discussion around validation seems to involve tagging properties on "model" objects, but it often makes more sense to check incoming state before even involving domain objects.  Especially when the incoming data may not always map 1:1 to domain objects.
