### ISSUE TITLE
HTTP DELETE causes 404

### ISSUE THREAD

**Issue by afmuller** [aspnet/Mvc#3563]
I created an empty ASP.NET 5 project, added MVC and a standard Web API controller (used the default ValuesController).

Sending an HTTP DELETE (e.g.: DELETE /api/values/1) (I used Fiddler Web Debugger) with anything in the request body (even only an empty JSON object {}) caused a subsequent request to fail with a 404. With Kestrel it is usually the next request that fails with a 404. With IIS it is usually a few requests later.

Sending an HTTP DELETE with an empty request body works as expected.

Using beta8 on Windows 10.

**Comment by Eilon** [comment]
@ryanbrandenburg can you try to repro this?

**Comment by Tragetaschen** [comment]
That's KestrelHttpServer#270

**Comment by Eilon** [comment]
@Tragetaschen ah cool.

Closing as a dup of https://github.com/aspnet/KestrelHttpServer/issues/270.
