### ISSUE TITLE
Hyperlinks are not rendered at all when inside an Area

### ISSUE THREAD

**Issue by bastienJS** [aspnet/Mvc#3566]
I have created an area.

When the a-tags are defined within my Area "Application" then those a-tags are not rendered with an href=""

Maybe the root cause could be that Razor intellisense is also not working? Thats just a side note.

![image](https://cloud.githubusercontent.com/assets/5945955/11193320/5af3dad0-8ca6-11e5-8109-12ec904e6a2d.png)

I use VS 2015, .NET 4.6.1, asp.net 5.0 Beta 8.

Thats a sample repro:

https://www.sendspace.com/file/e81spx

Repro steps:

1. Click the hyperlink in the main navbar "Evaluate Application"
2. The Areas _Layout is loaded
3. Investigate the Schoolyears hyperlink.
4. See that the a-tag is not rendered just literally displayed.

If all this is a user bug ;-) please let  me know that I can proceed :-)

**Comment by Eilon** [comment]
Any chance you can upload the app to a GitHub repo? A lot easier to browse :smile: 

A common cause is that the area/controller/action combination doesn't exist in the app (URLs to non-existent places are not rendered - but we're soon changing that behavior to allow it).

**Comment by bastienJS** [comment]
Have fun: https://github.com/bastienJS/AreaHyperlinkIssue

**Comment by Eilon** [comment]
A total head-scratcher, but I figured it out :smile: 

The issue is that the default tag helpers are all registered in `~/Views/_ViewImports.cshtml`, and that file isn't in a parent folder of the area views.

You can either:
1. Move the `_ViewImports.cshtml` file to the root of the app
2. Copy the file into `~/Areas/` or `~/Areas/Application/Views`

These files are found by walking up the folder hierarchy from wherever the view is located, so if there's no imports file, you get no tag helpers.

**Comment by Eilon** [comment]
It's fine to not have those files, so there can't really be any error for it.

**Comment by bastienJS** [comment]
OK. If you allow a side question also regarding my sample .sln. When you loaded the solution did you have intellisense for the razor directive?

**Comment by Eilon** [comment]
I didn't reuse your solution - I just created a new solution to try it out.

But once I added the missing `_ViewImports.cshtml` file, and then re-opened the view page, I got purple tag helpers in there.

**Comment by bastienJS** [comment]
Can I post a razor intellisense bug also here on the forum or do I have to post it on visual studio forum? because in my .sln razor does not work.

**Comment by Eilon** [comment]
For Razor Intellisense post here: https://github.com/aspnet/Tooling/issues/
