### ISSUE TITLE
ViewComponents should try find partial views from its own view location

### ISSUE THREAD

**Issue by opiants** [aspnet/Mvc#3569]
Using beta8, calling Html.Partial in a ViewComponent razor file will cause an InvalidOperationException even though the partial file exists in the current view location directory.

Suppose I have a `_MyPartial.cshtml` inside `~/Views/Shared/Components/MyViewComponent/` directory. Given this ViewComponent class:

    public class MyViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }

and a `Default.cshtml` razor file in the `~/Shared/Components/MyViewComponent/` directory with the ff contents:

    @Html.Partial("_MyPartial.cshtml")

will throw an this

    InvalidOperationException: The partial view '_MyPartial' was not found. The following locations were searched:
    /Views/<Name Of CurrentController>/_MyPartial.cshtml
    /Views/Shared/_MyPartial.cshtml

The view locator should also search in `~/Views/Shared/Components/MyViewComponent/` the directory.

**Comment by dougbu** [comment]
MVC 6 does not currently support relative paths when finding relative views. That will change once I submit the fix for #3307 (PR #3380). For now this request looks like a duplicate of #3307.

**Comment by opiants** [comment]
I haven't done the digging to find out how it looks for the views yet but if it can find the `Default.cshtml`, it should find the partial view inside that same directory, right?

Without reviewing your commit, will your PR fix that? If it does, then I'm gonna close this.

**Comment by dougbu** [comment]
Yes, the path `_MyPartial.cshtml` will be interpreted relative to the currently-executing view.

**Comment by opiants** [comment]
Cool thanks. I'm closing this now.
