### ISSUE TITLE
Remove use of `WebUtility.HtmlEncode()` and `...HtmlDecode()`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3571]
`ContentViewComponentResult` uses both `System.Net.Http.WebUtility.HtmlEncode()` and `...HtmlDecode()`. Looks like a dusty legacy corner.

Use `System.Text.Encodings.Web.HtmlEncoder.Encode()` instead of `WebUtility.HtmlEncode()`. And if we don't yet have HTML decoders, perhaps the `ContentViewComponentResult` pattern should be rethought.

**Comment by davidfowl** [comment]
Yah

**Comment by rynowak** [comment]
We should just delete the constructor that takes `HtmlString`. You can return `HtmlString` directly from a VC so it's not really important.

**Comment by dougbu** [comment]
eb70b1c

**Comment by dougbu** [comment]
@danroth27 @Eilon the fix for this bug also added support for view components returning `IHtmlContent` (not just `HtmlString`). Should this `task` thus be considered a (fixed) `bug` or perhaps even an `enhancement`?

**Comment by Eilon** [comment]
Doubt it matters.
