### ISSUE TITLE
How can I accept .js files in aspnet 5?

### ISSUE THREAD

**Issue by danicomas** [aspnet/Mvc#3572]
I have a js folder and a razor page with scripts. Then I receive a not found error when it tries to get the js files.

**Comment by NTaylorMullen** [comment]
Are you placing your JS files in the configured webroot folder? And are you using the static file package/middleware.

**Comment by danicomas** [comment]
Yes @NTaylorMullen It is.

**Comment by davidfowl** [comment]
@danicomas Can you provide a repro site on github so that we can take a look?

**Comment by danicomas** [comment]
@davidfowl @danroth27 My repository:
https://github.com/danicomas/Angular2Aspnet5

If you run the project and open in your browser: http://localhost:5000/js/hello.js you will see that is not working well.

**Comment by davidfowl** [comment]
There's a bunch of problems with your project:

- Your project.json has references to beta5, beta6, beta7 and beta8, which is wrong and will never work
- Your project.json references **Microsoft.AspNet.Server.IIS** which is no longer relevant
- Your wwwroot folder has `bin/AspNet.Loader.dll` which will load the wrong server

My recommendation is to read this blog post http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx and properly update to beta8. It includes some critical changes required to your project to use with the new tooling. 

I'd recommend creating a new project and copying things over. This project is small enough that it shouldn't be a problem.

**Comment by danicomas** [comment]
Thanks @davidfowl I have update all my dependencies to beta8 and it works now:

```
"Microsoft.AspNet.Server.WebListener": "1.0.0-beta8",
"Microsoft.AspNet.NodeServices.Angular": "1.0.0-alpha5",
 "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8",
"Microsoft.AspNet.StaticFiles": "1.0.0-beta8",
"Microsoft.AspNet.Diagnostics": "1.0.0-beta8",
"Microsoft.Framework.Runtime": "1.0.0-beta5",
"Microsoft.Dnx.Runtime": "1.0.0-beta8",
"Microsoft.AspNet.Mvc": "6.0.0-beta8",
 "Microsoft.AspNet.Http.Abstractions": "1.0.0-beta8"
```

**Comment by davidfowl** [comment]
> "Microsoft.Framework.Runtime": "1.0.0-beta5", This is still wrong

**Comment by danicomas** [comment]
@davidfowl  Should I to remove it?

**Comment by davidfowl** [comment]
yes

**Comment by danicomas** [comment]
Nice. Done. Thanks.
