### ISSUE TITLE
CacheTagHelper needs to buffer before storing a value in the cache

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3575]
This code https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.TagHelpers/CacheTagHelper.cs#L162 is putting a `TagHelperOutput` in the memory cache. With our newer rendering model this might include a pooled buffer or other random objects. We should write the content out to a stringbuilder before caching it.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/ff34c5404a7f3cfdd5c9fb80af1d6463d3510f67
