### ISSUE TITLE
Middleware Adding Headers

### ISSUE THREAD

**Issue by Fosol** [aspnet/Mvc#3576]
I'd like to be able to add a Response Time header to all responses.  However in many cases if I attempt to add the response time header value at the end of the actual execution it will throw an exception because it no longer can make changes to the response...

So how do you add a header at the end of a response?

I was hoping the following would work;
```
context.Response.OnStarting(async () => {
context.Response.Headers.Add("XResponseTime", "value");
});
```

**Comment by pranavkm** [comment]
This would be a bug for https://github.com/aspnet/HttpAbstractions/

**Comment by Fosol** [comment]
Should I close and repost?

**Comment by pranavkm** [comment]
Yup, it'd have better visibility there.
