### ISSUE TITLE
Adding timing information to Diagnostics Source events

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Mvc#3584]
A large percentage of Diagnostics Source events define both a `begin` and `end` event to allow tracking the boundary of a given action. Beyond just marking the boundaries, it was intended that consumers could use this to track the duration of the target event. 

There are a few challenges with this approach:
- If a consumer wants to simply know what the duration of an "event", they need to have infrastructure to carry the state that tracks the time between events. This isn't that hard per se, but relatively speaking its more than you should have to write to simply track the duration and can have gotchas
- Additionally, if the user is using multiple tools in combination (i.e. logging and glimpse), because the onus is on the consumers to derive the time, each consumer will calculate a slightly different time and hence the user wont have a consistent experience
- Lastly, though out the code base, the system has already start to collect this timing information for the purposes of logging, so there are cases that this data is already available.

Given the above, the proposal is that we make timing information available on the existing diagnostics events. 

Ideally, so that we don't have to track both the start and end events to derive duration, the system would simply add a `TimeSpan` or something similar to the `end` event. If this can't be done, a fallback which adds the `tickCount` from `Environment.TickCount` to each event could also work.

@rynowak // @Tratcher @anpete might also be interested

**Comment by rynowak** [comment]
> Additionally, if the user is using multiple tools in combination (i.e. logging and glimpse), because the onus is on the consumers to derive the time, each consumer will calculate a slightly different time and hence the user wont have a consistent experience

Would dropping any sub-millisecond precision solve this issue in the general case? Trying to convery the difference between .001ms and .0015ms to the user with accuracy was never really the goal with the timing info that we added to logging. If we just logged the number of milliseconds without any additional precision it's very likely that this difference in calculation would go away.

> Lastly, though out the code base, the system has already start to collect this timing information for the purposes of logging, so there are cases that this data is already available.

I'm not opposed to the idea in general, but we specifically identified a few places we wanted to do it for logging. Providing a duration for all events where we have a clear begin/end pair is a separate concern.

> a fallback which adds the tickCount from Environment.TickCount to each event could also work.

This is subject to the same kinds of perturbation via measurements that you're concerned about. If we send a 'starttime' before running an operation, then the duration includes the time spend calling glimpse, logging, etc.

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/Diagnostics/pull/207/files#diff-85232ab1b9a364dba71847b560310534R28

**Comment by Eilon** [comment]
Moving to backlog for now.

**Comment by avanderhoorn** [comment]
> Would dropping any sub-millisecond precision solve this issue in the general case? Trying to convery the difference between .001ms and .0015ms to the user with accuracy was never really the goal with the timing info that we added to logging. If we just logged the number of milliseconds without any additional precision it's very likely that this difference in calculation would go away.

It would help, but I think the problem would still exist. Its not inconceivable that the listeners in the pipeline could take > 0.5 - 1ms to do their work and this being the case we would still end up with different numbers.

> I'm not opposed to the idea in general, but we specifically identified a few places we wanted to do it for logging. Providing a duration for all events where we have a clear begin/end pair is a separate concern.

Thats what this issue is about :D But in truth, I'm not sure that the delta between the two is going to be that significant. If it is determined to be significant, at the very least we could get the duration for the most significant events.

> This is subject to the same kinds of perturbation via measurements that you're concerned about. If we send a 'starttime' before running an operation, then the duration includes the time spend calling glimpse, logging, etc.

Agreed, but whether this is an issue is subject to the implementation. For instance, the following could work, it wouldn't include the observer time, all the observers would have the same time and observers wouldn't have to tract state between events simply for duration. The only difference here is that we are capturing the `finishTime` as well as the `startTime`

```
// https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Internal/HostingEngine.cs#L99-L130

if (diagnosticSource.IsEnabled("Microsoft.AspNet.Hosting.BeginRequest"))
{
	diagnosticSource.Write("Microsoft.AspNet.Hosting.BeginRequest", new { httpContext = httpContext });
}

using (logger.RequestScope(httpContext))
{
	var startTime = 0;
	var finishTime = 0;
	try
	{
		logger.RequestStarting(httpContext);

		startTime = Environment.TickCount;
		await application(httpContext);
		finishTime = Environment.TickCount;

		logger.RequestFinished(httpContext, startTime, finishTime);
	}
	catch (Exception ex)
	{
		logger.RequestFailed(httpContext, startTime);

		if (diagnosticSource.IsEnabled("Microsoft.AspNet.Hosting.UnhandledException"))
		{
			diagnosticSource.Write("Microsoft.AspNet.Hosting.UnhandledException", new { httpContext = httpContext, exception = ex, duration = new TimeSpan(finishTime - startTicks) });
		}
		throw;
	}
}
if (diagnosticSource.IsEnabled("Microsoft.AspNet.Hosting.EndRequest"))
{
	diagnosticSource.Write("Microsoft.AspNet.Hosting.EndRequest", new { httpContext = httpContext, duration = new TimeSpan(finishTime - startTicks) });
}
```
or
```
var startTime = 0;
var finishTime = 0;
try
{
	context.RouteData = newRouteData;

	_diagnosticSource.BeforeAction(actionDescriptor, context.HttpContext, context.RouteData);

	using (_logger.ActionScope(actionDescriptor))
	{
		_logger.ExecutingAction(actionDescriptor);

		startTime = Environment.TickCount;
		await InvokeActionAsync(context, actionDescriptor);
		finishTime = Environment.TickCount;

		context.IsHandled = true;

		_logger.ExecutedAction(actionDescriptor, startTime, finishTime);
	}
}
finally
{
	_diagnosticSource.AfterAction(actionDescriptor, context.HttpContext, context.RouteData, startTime, finishTime);

	if (!context.IsHandled)
	{
		context.RouteData = oldRouteData;
	}
}

**Comment by avanderhoorn** [comment]
Just wondering if there are any thoughts on this?

**Comment by avanderhoorn** [comment]
Can we resurrect this discussion... there has been more movement in Hosting on this front - https://github.com/aspnet/Hosting/pull/543.

**Comment by benaadams** [comment]
The three places that I've come across that do diagnostic timings; also do logging timing and for logging they create store the start state so they can generate a TimeStamp to pass to logging - so its kinda done in a way - other than the data format for diagnostics.

TimeStamp would probably be the more sensible data type as its units clearly defined?

**Comment by avanderhoorn** [comment]
Given the work you did in 543, totally agree about TimeStamp.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
