### ISSUE TITLE
MVC6 RC1 New App - HomeControler Instanciated Twice!

### ISSUE THREAD

**Issue by PopovMP** [aspnet/Mvc#3585]
I just created a new app and noticed that Index() action method is called twice (no styles, scripts, images. Layout removed).

Further to that found out the the Home constructor is called twice also.

Please see full report here: http://stackoverflow.com/questions/33795079/mvc-6-homecontroler-index-called-twice

**Comment by danroth27** [comment]
This is VS sending a separate request to setup debugging. If you try to run the app outside of VS you shouldn't see this extra request.

**Comment by Eilon** [comment]
See https://github.com/aspnet/Tooling/issues/261 for more info.
