### ISSUE TITLE
`CompilationFailuresAreListedByErrorPageMiddleware` functional tests fail on Mac

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3587]
See last two failures in [Travis job 3915.2](https://travis-ci.org/aspnet/Mvc/jobs/92083777). Looks as if `CompilationFailedException`s are propagating though the `ErrorPageMiddleware`. But without debugging further, can't be sure where the problem lies. Need to investigate and file the appropriate CoreFx, DNX or `ErrorPageMiddleware` issue or resolve in this repo.

**Comment by dougbu** [comment]
Nice, @Eilon must be buying me a Mac :smiley_cat:

**Comment by Eilon** [comment]
Use the Mac you borrowed :wink:

**Comment by ryanbrandenburg** [comment]
As @pranavkm said, it looks like this one's fixed. Closing.
