### ISSUE TITLE
Will there be a ResponseTypeAttribute in asp.net 5?

### ISSUE THREAD

**Issue by sgwatgit** [aspnet/Mvc#3592]
I use the (ResponseTypeAttribute)[https://msdn.microsoft.com/en-us/library/system.web.http.description.responsetypeattribute(v=vs.118).aspx] currently to document my code and provide information to (Swashbuckle)[https://github.com/domaindrivendev/Swashbuckle] for the Swagger UI.

I realize that this is in System.Web.Http.Description so it's not available in the Core framework.

Is this going to be re-added in some way for use with MVC/Web API?

**Comment by dougbu** [comment]
@sgwatgit does `Microsoft.AspNet.Mvc.ProducesAttribute` meet your needs?

**Comment by rynowak** [comment]
@sgwatgit `[Produces(typeof(MyType))]` is the intended replacement.
