### ISSUE TITLE
ModelMetadata.ConvertEmptyStringToNull meaning in codebase

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#3593]
Hi, I saw that [simple type model binder](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/SimpleTypeModelBinder.cs#L39) use `ModelMetadata.ConvertEmptyStringToNull` to null out empty **and white space** string values, like this:
```C#
if (bindingContext.ModelMetadata.ConvertEmptyStringToNull &&
    string.IsNullOrWhiteSpace(modelAsString))
{
    model = null;
}
```

Is using `string.IsNullOrWhiteSpace(modelAsString)` correct here?
Because MVC5 nulls out empty values too, but strings containing only white space are left in tact.

**Comment by dougbu** [comment]
/cc @pranavkm this `IsNullOrWhiteSpace()` came in when you initially ported over model binding (see #20). Wasn't talked about at all in the PR discussion.

Was there a reason to start converting whitespace? If not, this is a breaking change we should revert.

**Comment by Eilon** [comment]
That may have came from Web API, which possibly had all kinds of checks like this.

We should remove the whitespace check. And while we're at it, @pranavkm , can you look for any other mysterious whitespace checks?

**Comment by pranavkm** [comment]
@dougbu like @Eilon mentioned, it was ported over from WebAPI: https://github.com/ASP-NET-MVC/aspnetwebstack/blob/4e40cdef9c8a8226685f95ef03b746bc8322aa92/src/System.Web.Http/ModelBinding/ModelBindingHelper.cs#L97-L98 \ Mvc Futures https://github.com/ASP-NET-MVC/aspnetwebstack/blob/4e40cdef9c8a8226685f95ef03b746bc8322aa92/src/Microsoft.Web.Mvc/ModelBinding/ModelBinderUtil.cs#L79

**Comment by dougbu** [comment]
:ok: I'll remove that "feature". Likely rarely if-ever depended upon in the old world and just inconsistent in the new.
