### ISSUE TITLE
Getting a 500 Internal Server Error - Unable to resolve service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' 

### ISSUE THREAD

**Issue by eduralph** [aspnet/Mvc#3596]
I setup an ASP.NET Application and obviously messed it up so bad that I can't figure out what is wrong. I'm getting the exception 
"System.InvalidOperationException
Unable to resolve service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' while attempting to activate 'WindexCards.WebAPI.Startup'."
when I try to load a configuration in the Startup class like this

public Startup(IHostingEnvironment env,IApplicationEnvironment appEnv)
        {
           var builder = new ConfigurationBuilder()                            
                            .SetBasePath(appEnv.ApplicationBasePath)
                            .AddJsonFile("config.json")
                            .AddJsonFile($"config.{env.EnvironmentName}.json", optional: true);

Creating a new solution with Visual Studio executes fine, so obviously I misconfigured something. My project.json is
[project.txt](https://github.com/aspnet/Mvc/files/40619/project.txt)

Any ideas what I'm missing?

**Comment by rynowak** [comment]
You have a beta6 package reference in that `project.json`. You can't mix different releases. I'd try just straight up removing that package (you shouldn't need to reference that one anyway).

**Comment by eduralph** [comment]
Thanks for putting me on the right path. I was mistakenly referencing Microsoft.Framework.Runtime Namespace instead of Microsoft.Dnx.Runtime. The first reference exists only in beta6 which is why it was included.
