### ISSUE TITLE
a TagHelper generates url for controller in another project

### ISSUE THREAD

**Issue by phenombox** [aspnet/Mvc#3601]
I have a VS2015 solution that includes a WebApi and a WebSite.

All packages are rc1 in both solutions.

Since my project is in early development I'm referencing the WebApi project direclty from the WebSite project in order to get the Model classes/objects to deserialize responses from the WebApi. This will be changed to use of DTOs later.

There is a UsersController.cs in both projects.

The issue is that when using TagHelper <a> to generate url for the users controller in the website:
`<a asp-controller="Users" asp-action="Index">Users</a>`
is not generating localhost/Users (WebSite Controller), but localhost/api/Users (WebApi) controller instead.

This results in a (misleading) exception: 
`InvalidOperationException: Unable to resolve service for type 'Px.Dealership.WebApi.Models.DealershipContext' while attempting to activate 'Px.Dealership.WebApi.Controllers.UsersController'.`

It's probably since I'm referencing the webapi project direclty and both projects have a UsersController, this will of course be changed later on.

Not sure if it's a bug, but shouldn't the tag helper prioritize controllers in its own project first?

**Comment by phenombox** [comment]
Alright same thing with html.ActionLink, seems I'll just fix DTOs straight away.

**Comment by rynowak** [comment]
This is the expected default behavior if you're referencing multiple projects with controllers.

If you want to configure MVC to just use one assembly, add the following to your `ConfigureServices` in startup.
```
services.AddSingleton<IAssemblyProvider>(new StaticAssemblyProvider()
{
    CandidateAssemblies = new List<Assembly>()
    {
        typeof(SomeControllerType).GetTypeInfo().Assembly,
    },
}
```

Depending on what version of packages you are using - you either need `AddInstance` or `AddSingleton`

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Infrastructure/StaticAssemblyProvider.cs
