### ISSUE TITLE
Can we retrieve view content from database

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/Mvc#3607]
Hi,

I'm looking for a solution that can pull the content of view cshtml and layout cshtml from database.
Is custom RazorViewEngine a solution ( public class CoolViewEngine : RazorViewEngine)? If yes, please kindly provide some sample code to write a custom RazorViewEngine

Thanks lot
Gary

**Comment by tuespetre** [comment]
See: [Guidance on how, or a 'friendlier' way, to render views to strings (for emails, service calls, etc.)](https://github.com/aspnet/Mvc/issues/3091)

**Comment by Eilon** [comment]
Here's a sample: https://github.com/aspnet/Mvc/tree/dev/test/WebSites/RazorEmbeddedViewsWebSite
