### ISSUE TITLE
Docker deploy issues w/ RC1

### ISSUE THREAD

**Issue by mguinness** [aspnet/Mvc#3608]
I've had multiple issues when publishing from VS 2015 to a custom docker container after upgrading from Beta8 to RC1.

In the publish web dialog, the image name was empty - previously it defaulted to project name (in lowercase).  I had entered a name starting with uppercase which was rejected by docker, so validation is required on this field to use the same regex as docker does.

On publish, if the container already existed on docker the publish would fail.  Fixed that with:
`<DockerRemoveConflictingContainers>True</DockerRemoveConflictingContainers>`

After publishing the browser would not automatically start, do I fixed that with:
`<LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>`

Both of the above were in Beta 8 template, not sure why they were removed in RC1.

The next issue was after starting, the web server was listening on port 5000 as below:

> Hosting environment: Production
> Now listening on: http://localhost:5000
> Application started. Press Ctrl+C to shut down.

I specified Container port as 8080, so this port entry should be used instead.

However, there is interface binding issue raised in https://github.com/OmniSharp/generator-aspnet/issues/472, so I had to manually change the following:

`"web": "Microsoft.AspNet.Server.Kestrel",`
to
`"web": "Microsoft.AspNet.Server.Kestrel --server.urls http://*:8080",`

Finally, although this was raised in https://github.com/aspnet/EntityFramework/issues/3089, I got 
> EntryPointNotFoundException: sqlite3_close_v2 error.

Had to fix this by adding the following to the docker file.  I had done this in Beta 8 as well but I thought the packages would've been fixed for RC1.

`RUN echo 'deb http://ftp.us.debian.org/debian jessie main' >> /etc/apt/sources.list && apt-get update && apt-get -y install libsqlite3-dev`

I hope these issues can be looked at, but also to document these in case it helps others.

**Comment by atrauzzi** [comment]
Just wanted to make a note here that I'm encountering this issue right now as well when running the current mono based container.

**Comment by Eilon** [comment]
Hi folks, this seems like an issue with the Docker tooling and publishing experience. We contacted the team that owns that experience and let them know about this issue.

**Comment by carolynvs** [comment]
Is there a github issue for the "docker tooling and publishing experience" team that we can subscribe to?

**Comment by Eilon** [comment]
@carolynvs not that I'm aware of, but when I contacted the team that works on that I asked them if there is such a place, or if they can update this issue with their finding. If I hear anything from them I will also update this issue.

**Comment by CawaMS** [comment]
Thanks everyone for the feedback. The fixes for the following problems will be included in the next release:
1. Publishing to a VM with an existing container passes. It's not longer failing as described above

2. Browser would automatically open the URL pointing to the newly deployed site

3. In the publishing UI if port number mapping is changed, the site's port number would change. No additional configuration will be required

Thanks

**Comment by mguinness** [comment]
I encountered another issue when using MSDeploy to publish a website to a remote server.  As the build process copies the output to a new folder every time, MSDeploy copies *all* files as it uses file time stamps from source to determine changes against the target.

Therefore the only appropriate action for MSDeploy is to instead use CRC checksums for file comparisons.  Adding the line below to the pubxml file resolves this problem by copying only files that are changed, but really the -useChecksum should be set by default.

`<MSDeployUseChecksum>true</MSDeployUseChecksum>`

**Comment by grennis** [comment]
+1
