### ISSUE TITLE
difficult to track the error when an I have errors serializing action result

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Mvc#3611]
Hi,
  I'm writing a sample application and I wrote this action to send the client some data.
```
        public IEnumerable<Attivita> GetLatest(int last) {
            var atts = db.Attivita
                .Include(att => att.Cliente).Include(att => att.Commessa).Include(att => att.Fattura).Include(att => att.Locazione)
                .Include(att => att.Pagamento).Include(att => att.Tipo).Include(att => att.Progetto)
                .OrderByDescending(att => att.Data).ThenByDescending(att => att.AttivitaNo)
                .Take(last).ToList();

            return atts;
}
```
I tried the action but I started to receive **502 (Bad Gateway)** error and an empty result: Just giving a look was clear the problem, and I solved creating a model class to send the data avoiding the usual nested serialization issues, but this is not the real problem.  
Trying to debug the action I don't have any exception, the simple answer is this http response code and no details. Looking in the debug window I found the real message error

```
Microsoft.AspNet.Server.Kestrel: Error: An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'Cliente' with type 'MyLibrary.Model.Cliente'. Path '[0].Cliente.Locazioni[0]'.
   in Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   in Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   in Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
```

In the Configure method I added 

```
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
```
but this doesn't help.

The answer, in this situation, is a bit hard to understand, and I don't understand how to write clients that can handle these situation. Am I missing something?

**Comment by lucamorelli** [comment]
I gave another look to this issue, and I see than the reason is slighly different from what I tought at the beginning: I tought that the problem was the ef lazy loading of ef, that was fetching the data, but ef 7 actually I think doesn't support lazy loading, so the problem is that I a referencing loop in the model is just detected.
If this is the reason, this is a problem: when I add a relationship between entities in ef, I always add navigation properties to both the sides of the relation, so if I have a order entity that refers a customer object, I always have a list of orders in the customer entity.
This was the only way to avoid the problem is create a vm class specular to the ef entity jsut for serialization, that is annoying.

**Comment by danroth27** [comment]
There isn't much we can do if there is an exception when writing out the body of the response, but you can see errors like these by looking at the logging output. By default we log to the console and to the debug output window.

**Comment by lucamorelli** [comment]
FYI, I found the solution. 
I write because it may be useful to someone else who had the same problem: The referencing loop detection is a Json.Net feature that may be configured is the serializerSettings.
At the moment, in the controllers who I have this problem I added this:
```
 public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);

            var lstFormatters = this.BindingContext.OutputFormatters.ToList();
            foreach (var formatter in lstFormatters)
            {
                Microsoft.AspNet.Mvc.Formatters.JsonOutputFormatter jsonFormatter = formatter as Microsoft.AspNet.Mvc.Formatters.JsonOutputFormatter;
                if (jsonFormatter != null) {
                    jsonFormatter.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
                }
            }
        }
```
this way I change the settings to every call to the controller: I'm sure I can do this application level in the startup, but at the moment it's fine to me.

About the exception when writing out the response I understand: my problem is not under development but in production: generally speaking I don't have idea when I can have problems in this phase, but I don't see an easy way to monitor and handle this situation, checking the error type and deciding if to send, for example sending an email  for immediate check.
