### ISSUE TITLE
MVC functional test cleanup (part 1) (ETA 12/4)

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#3612]
https://github.com/aspnet/Mvc/blob/dev/samples/MvcSample.Web/wwwroot/Scripts/Mvc.js
-	Does it still need to exist?
-	If so, make into its own sample
-	If not, deletify (I think we already decided to delete this, right?)

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ActionConstraintsWebSite
-	Good scenarios
-	Move to another existing site because there’s no unique setup for it aside from enabling DCXS

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ActionResultsWebSite
-	Delete

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ActivatorWebSite
-	Delete

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/AntiforgeryTokenWebSite
-	Merge into another test

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ApplicationModelWebSite
-	Already exists a bug on adding more samples to this
-	Fix spelling of “lisence” [sic]

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/BasicWebSite
-	Keep this
-	Move most other mergeable tests into here

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/BestEffortLinkGenerationWebSite
-	Delete

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/CompositeViewEngineWebSite
-	Delete
-	Check whether there are existing unit tests to verify multi-view-engine scenarios

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ContentNegotiationWebSite
-	Move to an existing site

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ControllerDiscoveryConventionsWebSite
-	Delete

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/CorsMiddlewareWebSite
-	Move to CORS repo

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/CustomRouteWebSite
-	Move to /samples, but keep the test

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/FilesWebSite
-	Keep the MVC stuff (controllers that return FileResults)
-	Move the SendFile stuff to another repo

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/FormatFilterWebSite
-	Move to /samples, but keep the test

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/InlineConstraintsWebSite
-	Move to samples

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/JsonPatchWebSite
-	Move to /samples

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/LocalizationWebSite
-	Move to /samples

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/LoggingWebSite
-	Delete

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/LowercaseUrlsWebSite
-	Delete

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ModelBindingWebSite
-	Delete

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/RazorEmbeddedViewsWebSite
-	Move to /samples

**Comment by dougbu** [comment]
> I think we already decided to delete this, right?

Right. @ryanbrandenburg just needs to squash and push #3574.

**Comment by Eilon** [comment]
Cool.

**Comment by ryanbrandenburg** [comment]
@dougbu I pushed #3574

**Comment by dougbu** [comment]
sub-part 1: 19e6fb5

**Comment by dougbu** [comment]
subpart 2: 59824dc w/ minor touch-up in 900663b
One last part coming in Cors repo (aspnet/Cors#57).

**Comment by dougbu** [comment]
last bit: aspnet/CORS@c3c0b45
