### ISSUE TITLE
TagHelperContext.Items empty in parent tag helper

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Mvc#3614]
I am trying to render scripts from a view component into the bottom of the body (i.e. after traditional jquery & bootstrap src)

Under `TagHelperContext.Items` it has the summary "Gets the collection of items used to communicate with other Microsoft.AspNet.Razor.TagHelpers.ITagHelpers." but items added to this dictionary in my child tag helper don't appear in the parent `Items` dictionary.

I am currently running 1.0.0-rc1-final clr x86. An example use:

```c#
public class BodyTagHelper : TagHelper
{
	[ViewContext]
	public ViewContext ViewContext { get; set; }

	public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
	{
		await output.GetChildContentAsync();

		// context.Items here has zero keys
		if (context.Items.ContainsKey(nameof(PostBodyScriptTagHelper)) && context.Items[nameof(PostBodyScriptTagHelper)] is HtmlString)
		{
			var scripts = context.Items[nameof(PostBodyScriptTagHelper)] as HtmlString;
			output.PostContent.Append(scripts);
		}
	}
}

[HtmlTargetElement("postbodyscript")]
public class PostBodyScriptTagHelper : TagHelper
{
	[ViewContext]
	public ViewContext ViewContext { get; set; }

	public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
	{
		var content = await output.GetChildContentAsync();

		var script = content.GetContent();
		var htmlScript = new HtmlString(script);
		context.Items[nameof(PostBodyScriptTagHelper)] = htmlScript;

		output.SuppressOutput();
	}
}
```

So in a view component Default.cshtml file I may have 
```html
<div>Content</div>

<postbodyscript>
    <script type="text/javascript">
        // Some jquery here
    </script>
</postbodyscript>
```

When debugging, the `PostBodyScriptTagHelper` has it's `ProcessBodyAsync` method called first, but when the `BodyTagHelper` is executed, the `Items` dictionary is empty.

Is this the proper behaviour? If so, how are we meant to pass data to the parent from inside a view component?

**Comment by NTaylorMullen** [comment]
@damienpontifex the reason behind this is that `context.Items` is copy on write. Therefore, if you want a child to communicate to the parent the parent needs to put some sort of mutable object into the `context.Items` bag that the child then retrieves and modifies.

**Comment by damienpontifex** [comment]
@NTaylorMullen but the `PostBodyScriptTagHelper` is executed before the body helper, so if I try and access something added by the body tag helper in the `PostBodyScriptTagHelper`, it throws an exception as the key doesn't exist.

Is this because the `PostBodyScriptTagHelper` is being executed inside a view component?

**Comment by NTaylorMullen** [comment]
@damienpontifex The only way your post body script taghelper could be executed prior to the `BodyTagHelper` would be if it existed in the `<head>` element.

**Comment by damienpontifex** [comment]
Basic structure is
```html
<html>
<head>
</head>
<body>
    @RenderBody()
</body>
</html>
```

And inside my Details.cshtml file from `RenderBody` I have a call to `@Component.Invoke`. Debugging the flow, it consistently hits the tag helper inside the view component before the body helper.

**Comment by NTaylorMullen** [comment]
Ah I see @damienpontifex. So there's one restriction to `context.Items`. And that's `Views`. `context.Items` does not translate across them. If you want to gain that functionality I recommend using `ViewContext.ViewData` to pass information.

**Comment by damienpontifex** [comment]
I've changed it to use `ViewContext.ViewData` and when run inside the body tag helper, it doesn't have the newly added key.

See https://github.com/damienpontifex/TagHelperInComponent/blob/master/src/ComponentTagHelper/TagHelpers/PostBodyScriptTagHelper.cs for example and using it in the About.cshtml page

**Comment by NTaylorMullen** [comment]
@damienpontifex `ViewContext.ViewData` is also copy on write so you'll need to add a mutable object to it that the child can then modify.

**Comment by damienpontifex** [comment]
@NTaylorMullen again though, I am still getting the `PostBodyScriptTagHelper` execute before `BodyTagHelper` in this blank project when it is inside a ViewComponent. Hence it is empty when accessing in `PostBodyScriptTagHelper` and adding it in `BodyTagHelper` means I just get an empty List.

I've updated the file in the repo above to reflect these changes.

**Comment by NTaylorMullen** [comment]
So your sample now looks correct. If you're unable to communicate to a sub-View (invoked via ViewCOmponent) then I'd view that as unexpected behavior. /cc @rynowak

**Comment by NTaylorMullen** [comment]
@damienpontifex Ah, sorry. This is what happens when I don't have my coffee for today/night. So what's happening is by design. A view determines what `Layout` it requires therefore it must run first. So you're seeing your `PostBodyScriptTagHelper` run prior to your `BodyTagHelper` due to this functionality. 

I'd recommend throwing your scripts inside of an `@section` element corresponding to script tags to get your desired behavior.

**Comment by damienpontifex** [comment]
Using `@section scripts` inside my cshtml as part of a ViewComponent doesn't seem to get rendered into the scripts section in my layout.

And using `@RenderSection` inside my parent view throws the error "RenderSection can only be called from a layout page"

Is there a way of getting sections from a ViewComponent into the layout?

**Comment by NTaylorMullen** [comment]
@damienpontifex nope, you'd need to move it out of a `ViewComponent`.

I played around a little bit with your scenario and sadly, `ViewComponent`s can't currently communicate up to the calling view via `ViewContext.ViewData` either (via `TagHelper` or directly).

/cc @rynowak is this by design or a known limitation ?

**Comment by NTaylorMullen** [comment]
Ahh, scratch that, nm @rynowak . 

I made my own mistake. If you push a mutable item into `ViewData` in your page (not your layout) and then add to it in the `ViewComponent`'s View you can flow it up to the `_Layout.cshtml`.

So in `Index.cshtml`:

```HTML
@{
    Layout = "_Layout";
    ViewData[typeof(FooTagHelper).FullName] = new List<string>();
}

@Component.Invoke("Foo") <!-- Just invokes the FooViewComponentView.cshtml -->
```

FooViewComponentView.cshtml:
```HTML
<foo></foo>
```

FooTagHelper.cs:
```C#
public class FooTagHelper : TagHelper
{
    [ViewContext]
    public ViewContext ViewContext { get; set; }

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        var list = (List<string>)ViewContext.ViewData[typeof(FooTagHelper).FullName];
        list.Add("From the Foo TagHelper");
    }
}
```

BodyTagHelper.cs (which is used in _Layout):
```C#
public class BodyTagHelper : TagHelper
{
    [ViewContext]
    public ViewContext ViewContext { get; set; }

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        var list = (List<string>)ViewContext.ViewData[typeof(FooTagHelper).FullName];

        output.PostContent.Append(string.Concat(list));
    }
}
```

All this results in a `From the Foo TagHelper` appended t the end of the body.

**Comment by damienpontifex** [comment]
Beautiful! I never thought of instantiating the List in the cshtml file there.

Thanks for your persistence and help @NTaylorMullen
