### ISSUE TITLE
Make ModelExplorer a struct

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3616]
For our BasicView benchmark, this is about 1% of allocated bytes, but it's in the top 15 on allocated objects.

![image](https://cloud.githubusercontent.com/assets/1430011/11342503/9719c644-91bc-11e5-9306-5fb3def010cf.png)

**Comment by Eilon** [comment]
Moving to backlog.

**Comment by mnltejaswini** [comment]
ModelExplorer has a cyclic struct that needs to be broken. This involves redesigning the way the explorer object is structured. Like representing the hierarchy of the explorer as some array and have indexes within the explorer. As this involves some design changes, we will hold on this for now.

**Comment by Eilon** [comment]
Not planning on making further changes here.

**Comment by dougbu** [comment]
@Eilon "won't fix" instead of ready?

**Comment by Eilon** [comment]
We often don't label things that aren't 3-Done.
