### ISSUE TITLE
Could we find a new home for EnvironmentTagHelper?

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3620]
A la `Microsoft.Web.Helpers` for TagHelpers that are less interesting? `EnvironmentTagHelper` is essentially an `if` statement.

**Comment by pranavkm** [comment]
cc @DamianEdwards

**Comment by DamianEdwards** [comment]
No

**Comment by pranavkm** [comment]
We ended up with a whole slew of abandonware with `Microsoft.Web.Helpers` where bugs \ features would invariably end up in backlog because we had no interest in addressing them. This has all the qualities of being in that some group.
