### ISSUE TITLE
MVC functional test cleanup (part 2) (ETA 12/4)

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#3624]
https://github.com/aspnet/Mvc/tree/dev/test/WebSites/RequestServicesWebSite
-	Merge into BasicTests

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ResponseCacheWebSite
-	Change to a unit test

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/TempDataWebSite
-	Merge into BasicTests

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/UrlHelperWebSite
-	Change into a sample

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ValidationWebSite
-	TryUpdateModel/TryValidateModel change to integration tests
-	RemoteAttribute test merge into another site

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ValueProvidersWebSite
-	Delete

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ViewComponentWebSite
-	Delete

See related item https://github.com/aspnet/Mvc/issues/3612 and discuss with @dougbu and @rynowak if you have questions.

**Comment by dougbu** [comment]
:shipit: from me but get @rynowak's squirrel too

**Comment by Eilon** [comment]
This is an issue, you can't :shipit: on an issue :smile:

**Comment by dougbu** [comment]
Hah, I just did. Of course it was by mistake but it was a _successful_ mistake!

**Comment by rynowak** [comment]
:watch:

**Comment by DonaldTrumpOnAspNet** [comment]
ETA 12/4

Nothing to add, really!

**Comment by kichalla** [comment]
57b88baad0372d3fe3f4bc8b9534d2643ddbf2dd
