### ISSUE TITLE
Encoding in scaffolded Items

### ISSUE THREAD

**Issue by BFISoft** [aspnet/Mvc#3627]
When creating a scaffolded item in MVC6 project there seems to be an inconsistency with file encodings.

Normal files (without scaffolding) are created as UTF-8
Scaffolded controllers and views are created as ANSI

Which means that text containing äüöü in _Layout is displayed correctly but in the scaffolded view the same text shows some weird symbols.

Microsoft Visual Studio Community 2015
Version 14.0.24627.00 Update 1 RC
Microsoft .NET Framework
Version 4.6.01040

ASP.NET and Web Tools 2015 (RC)   14.1.11116.0
ASP.NET and Web Tools 2015 (RC)

ASP.NET Web Frameworks and Tools 2012.2   4.1.40928.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

**Comment by pranavkm** [comment]
Could you file this bug in https://www.github.com/aspnet/Scaffolding?
