### ISSUE TITLE
Code base clean up

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#3628]
I was just wondering if the team would be interested in a series of PRs of MVC code base clean ups? One PR per solution project or something~. First doing something simple like removing unused code, shortening if statements and maybe later on increasing code efficiency by simplifying the actual implementation and stuff? Or I shouldn't bother? :smiley_cat:

**Comment by rynowak** [comment]
Thanks for asking, I'll let @Eilon give an official answer, but my (officially non-binding) thoughts

> doing something simple like removing unused code

Absolutely. We're always interested in this. Ex: https://github.com/aspnet/Mvc/pull/3623 If you find somewhere that we have dead code then please log an issue or send a PR :+1: 


> shortening if statements

That really depends. Shorter isn't always better. For me personally, I have a high tolerance for ugly code compared to others on the team :smiling_imp: 

If you can turn something absolutely heinous into something simple then that's great. If we're talking about moving 1-2 statements around or renaming a local variable, just remember that lots of people party on this code and if we all rewrote the parts we don't like stylistically it wouldn't end.


> increasing code efficiency by simplifying the actual implementation and stuff

If you mean perf, bring measurements. Not just to justify that your change is an improvement, but also that it's an improvement in the big picture.

If you don't mean perf, and if you can simplify a piece of code substantially without eliminating functionality then go for it. Just expect to get it wrong a few times, no harm no foul :+1: 

-----------------

I noticed we don't really have any issues marked as up-for-grabs in MVC. Feel free to volunteer if you see something come across the wire that you're interested in.

**Comment by Eilon** [comment]
@Muchiachio please let us know more specific details. We don't want to change any code formatting in this repo or any others. But if you have some substantial changes you're thinking of, please log specific bugs on those issues and we can discuss. Thanks!
