### ISSUE TITLE
Simplify RouteValueProvider/RouteValueProviderFactory

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3629]
We should rename https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/DictionaryBasedValueProvider.cs to `RouteValueProvider`. Our other VPs have distinct class names.

We should also add a `protected set` `CultureInfo` property to all of our VPFs so that scenarios like [this one](https://github.com/aspnet/Routing/issues/237) are easier to address.

**Comment by Eilon** [comment]
The rename sounds fine to me.

For the culture issue, I'm not sure that's the right solution to the problem. I think the scenario (including the specific linked scenario) is that *one* particular property on *one* particular type (or *one* particular action parameter) needs to have some particular culture rule.

I was instead imagining some kind of model-binding attribute like `[ModelBindCultureBehavior(ModelBindingCultureBehavior.CurrentCulture)]` (or pass in `.InvariantCulture`, or even pass in a string name of a culture, e.g. `en-US`). And model binding would see these and then flow it through to wherever it needed to, such as value providers, and Do The Right Thing<sup>:tm:</sup>.

**Comment by Eilon** [comment]
I split off the culture part to here: https://github.com/aspnet/Mvc/issues/3819 (and moved to backlog).

For now let's just rename.
