### ISSUE TITLE
Compilation big rocks moving to dotnet CLI

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#3633]
Now that we don't have the DNX providing compilation services, we need to figure out how to handle a few things:

- [x] Getting compilation options
- [x] Getting reference assemblies
- [x] Remove dependency on `Microsoft.Extensions.CompilationAbstractions`

/cc @anurse @pakrym

**Comment by pakrym** [comment]
And target framework too

**Comment by davidfowl** [comment]
@pakrym target framework will come from IApplicationEnvironment. Once we have the CLR feature then it'll just work.

**Comment by pakrym** [comment]
I was able to run MVC with dotnet cli by:
1. Overriding `IAssemblyProvider` to `StaticAssemblyProvider` with entry assembly added (At this point it was able to find controllers) 
2. Adding naive implementation of `ICompilerOptionsProvider`
3. Adding naive implementation of `ILibraryExporter`
3. Overriding `IApplicationEnvironment` and returning not null `RuntimeFramework`

**Comment by rynowak** [comment]
nice!

**Comment by pakrym** [comment]
Compilation options provider shouldn't be a big problem, we can infer most of settings at runtime from `IHostringEnvironment` and `IRuntimeEnvironment`

**Comment by pakrym** [comment]
For `ILibraryExporter` we can Embed `project.json` into assembly (something like "embedProjectMetadata" compilation option) and  and add API to read from it, so MVC can implement its own logic on top

**Comment by davidfowl** [comment]
Well that one is a bit tricky. The dotnet cli would need to do that and it's bit weird to always do it. Also you need the lock file not just the project.json file. Also you need access to the reference assemblies, which aren't always available unless we make them available.

**Comment by pranavkm** [comment]
@pakrym wouldn't we need the project.json to look at things like LanguageVersion, Defines, WarningAsErrors?

**Comment by pakrym** [comment]
Or we hardcode them to some default values :)

**Comment by pranavkm** [comment]
At that point, isn't it much simpler to just have an alternate way of configuring views (e.g. via options). It also separates oddities like figuring out which properties to exclude (code signing, `emitEntryPoint`) from the primary project and plays nicely with binaries containing embedded cshtml. @davidfowl doesn't particularly like this solution though.

**Comment by davidfowl** [comment]
I think we can have everything on razor options. All we're talking about is defaults. Let's start by treating the razor view engine as a separate compilation system that can be fully configured in Startup. Then we figure out where the defaults come from.

**Comment by pakrym** [comment]
@davidfowl  So we remove dependency on ILibraryExporter?

**Comment by davidfowl** [comment]
Also consider the precompile case.

**Comment by davidfowl** [comment]
I think ILibraryExporter needs some special care. I'm also going to see what the Roslyn team thinks about this. We could say that the only abstraction we expose for razor is the Roslyn API for references and compilation options (we don't need to a abstract it). That leaves the burning question, what set of assemblies do we pass to the razor view compilation process by default and how do we locate them.

I'm like 99% sure that we'Il need a tool chain changes.

**Comment by davidfowl** [comment]
We need to decide if we should fallback to runtime assemblies or fail when they aren't available.

**Comment by davidfowl** [comment]
Need to move some compilation options from here https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Compilation.CSharp.Common/CompilerOptionsExtensions.cs#L29 as defaults.

**Comment by davidfowl** [comment]
https://github.com/davidfowl/dotnetcli-aspnet5/tree/master/HelloMvc/Infrastructure

When this folder is gone, this issue can be closed.

/cc @pakrym @pranavkm

**Comment by pranavkm** [comment]
The repo is gone, so I think we should be good to close this issue
