### ISSUE TITLE
Have a way to set metadata on TagHelperDescriptor

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#3638]
When providing `TagHelperDescriptor` instances dynamically, for instance from a database, I am targeting the same `TagHelper` type. I'd like it to get the descriptor it was called for, with some contextual data that is known when the descriptor is created.

**Comment by Eilon** [comment]
Log in https://github.com/aspnet/Razor?

**Comment by sebastienros** [comment]
Moved here https://github.com/aspnet/Razor/issues/627
