### ISSUE TITLE
Microsoft.Framework.CodeGenerators.Mvc templates have problems

### ISSUE THREAD

**Issue by blanceok** [aspnet/Mvc#3640]
Microsoft.Framework.CodeGenerators.Mvc templates have problems:
1、*.cshtml's archive encoding is not UTF8,Cause some language can not be normal, such as Chinese.
2、Server Model data validation, error message can not be normal display.The reason shows that the `<span/>` has a problem with the error message, and the `<span></span>` can be displayed as normal.

**Comment by pranavkm** [comment]
@blanceok could you file this in https://github.com/aspnet/Scaffolding? My guess is this a dup of https://github.com/aspnet/Scaffolding/issues/144
