### ISSUE TITLE
asp-route-parameter absence does not make optional parameter to null

### ISSUE THREAD

**Issue by mdmoura** [aspnet/Mvc#3641]
Hello,

I have the following route:  

    [Route("ebooks/{categorySlug?}"), HttpGet]
    public IActionResult Index(String categorySlug) {
    } // Index

And the following link:

    <a asp-controller="EBook" asp-action="Index">EBooks</a>

Which renders correctly as "/ebooks" ...

However, if I am in route "/ebooks/xyz" the previous link will render "/ebooks/xyz" instead of "/ebooks".

The way to "fix" this is using the link:

    <a asp-controller="EBook" asp-action="Index" asp-route-categorySlug="">EBooks</a>

So why not setting categorySlug to null when asp-route-categorySlug is not defined?

Thank You,
Miguel

**Comment by dougbu** [comment]
> if I am in route "/ebooks/xyz"

@mdmoura do you mean "if executing the `Index(String categorySlug)` action with a non-empty `categorySlug` value"? Or does this occur when executing a different action that also has a `categorySlug` parameter?

**Comment by mdmoura** [comment]
@dougbu:

If I understood your question the problem happens when executing the same action with asp-route-categorySlug not even defined on the link ...

I have only one action:

    public class EBookController : Controller {    
       [Route("ebooks/{categorySlug?}"), HttpGet]
       public IActionResult Index(String categorySlug) {
          return View();    
       }
    }

with only one view: Index where I have the following links:

    <a asp-controller="EBook" asp-action="Index">EBooks</a>
    <a asp-controller="EBook" asp-action="Index" asp-route-categorySlug="xyz">EBooks</a>

The behavior is:

    Current route = "/ebooks" then previous links render as "/ebooks" and "/ebooks/xyz"

    Current route = "/ebooks/xyz" then previous links render as "/ebooks/xyz" and "/ebooks/xyz"

To fix this problem on "/ebooks/xyx" I need to explicity tell that asp-route-categorySlug is empty:

    <a asp-controller="EBook" asp-action="Index" asp-route-categorySlug="">EBooks</a>
    <a asp-controller="EBook" asp-action="Index" asp-route-categorySlug="xyz">EBooks</a>

Is this what you asked?

**Comment by dougbu** [comment]
Yup that's what I asked. `categorySlug` is _always_ defined as an ambient value in your scenario. Since the value comes from the current request, you need to override it as you've shown.

You have a few other options e.g. define a separate action with `[Route("ebooks"), HttpGet, Name = "bare"]` and use `asp-route="bare"` instead of `asp-controller="EBook" asp-action="Index"` in the view.

**Comment by mdmoura** [comment]
@dougbu:

Sure, I know that I can add a different route or use the route parameter as empty as I did.

For me both solutions are fine ... But the question is:

When a route parameter, e.g. asp-route-categorySlug, is missing in the link should not its value be set to null? It seems a more predictable behavior, no?

**Comment by Eilon** [comment]
@mdmoura the routing system picks up so-called "ambient values" from the current request and applies them if possible (there are some rules around this). To ensure the value is empty, the code has to set the value to be empty.

I agree this is confusing in some cases, but it also helps in other cases. E.g. if in the view page you want to link from the current category to other categories, you can just use `<a asp-route-categorySlug="scifi">Sci-Fi</a>` and the current controller and action will be used.

**Comment by mdmoura** [comment]
@Eilon sure, the reason why I posted this is because I wasn't sure if you were aware of the behavior which, as I described, in same cases it feels strange because it feels like "a initialized variable" has a value different from null which in is the opposite of C# and other languages ... 

BTW, I see the advantage but I ask: will anyone set a route without Controller and Action? Probably not because their first though will be "if I don't set the controller or the action" then both are null ... ;-)

I think you should maybe include some information about this on ASP.NET docs.

**Comment by Eilon** [comment]
Yeah the docs are still in progress. There exist docs on the routing in ASP.NET MVC 5, which is largely the same as in MVC 6 (certainly with respect to this behavior it's the same).
