### ISSUE TITLE
Can we define FileProvider for Layout?

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/Mvc#3650]
I have tried RezorViewEngineOptions.FileProvider, it works very well to provide a different view file provider.

```c#
 services.Configure<RazorViewEngineOptions>(options =>
            {
                options.FileProvider = new ViewFileProvider(ViewWatch);
            });
```

Can we do the same to Layout file? 

Thanks
Gary

**Comment by davidfowl** [comment]
Not sure what you mean. This is for any razor view engine file (including the layout.cshtml if that's what  you mean).

**Comment by PrimeObjects** [comment]
When I debug, it seems looking for view files only in the following sequence. 
_ViewStart.cshtml
Views/_ViewStart.cshtml
Views/{Controllers}/_ViewStart.cshtml
_ViewImports.cshtml
Views/_ViewImports.cshtml
Views/{Controllers}/_ViewImports.cshtml

But it does not look for Layout files for example from /Shared/_Layout.cshtml

Thanks
Gary

**Comment by PrimeObjects** [comment]
So I have successfully develop a new FileProvider to provide view file from database. How can I provide Layout file from database by using similar solution?

**Comment by Eilon** [comment]
@dougbu might also know some of this codebase because he recently did a massive cleanup of how stuff is found.

**Comment by pranavkm** [comment]
@PrimeObjects, are you specifying a `Layout = "_Layout"; or `Layout = "Views/Shared/_Layout.cshtml"`in your page / _ViewStart? RazorViews don't look for Layouts by default.

**Comment by PrimeObjects** [comment]
Hi pranavkm,
I want the content of the layout comes from database instead of from a file. I have made view files from database.

**Comment by davidfowl** [comment]
But did you set the property

**Comment by pranavkm** [comment]
@PrimeObjects, once you set it the page would query the view engine for it. You should be able to return contents from the DB at that point.

**Comment by PrimeObjects** [comment]
Cool, good to know that, I will give it a try. I thought if I don't define Layout explicitly, it should at least look for the default one in the Shared folder and it did not happen.

I will try it this evening and update you later.

Cheers
Gary

**Comment by PrimeObjects** [comment]
Hi guys,

After I give the Layout definition in the view content, the file path was seen in the new FileProvider. My bad, I should have given it a try. 

@{
    Layout = "~/Views/Whatever.cshtml";
}

Thank you all for the help!

Gary
