### ISSUE TITLE
DataType.MultilineText does not generate textarea

### ISSUE THREAD

**Issue by madmunsterdaddy** [aspnet/Mvc#3651]
In MVC5 you could do something like:

    public class ApplicationUser : IdentityUser
    {
        [DataType(DataType.MultilineText)]
        public string Bio { get; set; }
    }

That would generate a textarea tag to make it multi-line. Not working in MVC6 (rc1)

**Comment by dougbu** [comment]
@madmunsterdaddy this feature exists in MVC 6 and should be working fine. What are you using in your view to create a field for the `Bio` property? And does your `Startup.ConfigureServices()` method call `services.AddMvc()`?

**Comment by madmunsterdaddy** [comment]
It's easy to reproduce. I just used the default template with individual accounts. Add that member to ApplicationUser, create a new Controller w/ Views for the Application User class. That field on create/edit views is not multi-line.

**Comment by dougbu** [comment]
Ah, I get it; this is a Scaffolding issue: The generated view uses `<input asp-for="Bio" class="form-control" />`. Scaffolding should instead generate a `<textarea/>` element or use the more-general `@Html.EditorFor()` HTML helper.

The workaround is to use
``` c#
@Html.EditorFor(m => m.Bio, additionalViewData: new { htmlAttributes = new { @class = "form-control" }})
```
or
``` html
    <textarea asp-for="Bio" class="form-control"></textarea>
```

Please instead open this in the Scaffolding repo. I'd own the issue if I moved this issue over.

**Comment by madmunsterdaddy** [comment]
Thanks, Doug. I'll post there.
