### ISSUE TITLE
RC1 spams Fiddler - What's going on?

### ISSUE THREAD

**Issue by Fosol** [aspnet/Mvc#3655]
I started a simple RC1 web application project.  The result was Fiddler went wild...  It's capturing a ton of constant traffic.  Interestingly the port the application is running on is different.

This may be a Visual Studio issue...

Here's an example request;
```
http://localhost:49160/vshub/da8c29cf529049448e1f0b55b97f48f3/DataWarehouseModule/dataWarehouse/getStatus/
```
```
http://localhost:49160/vshub/da8c29cf529049448e1f0b55b97f48f3/DataWarehouseModule/dataWarehouse/getResult/
```
I just confirmed this happens even when a project is created from the default template.

This is almost definitely VS2015 RC1 related (unless you have some secret code in MVC).

**Comment by Eilon** [comment]
@jodavis is this Browser Link?

@Fosol check if the browser-link middleware is registered in your `Startup.cs`: `app.UseBrowserLink();`. It's used only at development time and is normally not used in production. You can certainly remove it if you don't use the feature.

**Comment by rynowak** [comment]
Or perhaps: https://github.com/aspnet/Tooling/issues/261

**Comment by Fosol** [comment]
@Eilon I don't have BrowseLink middleware registered.  This only started happening after installing RC1 Tooling.  So perhaps it's a tooling issue.

**Comment by jodavis** [comment]
It's not Browser Link. If it was, it would have "browserLink" in the URL.

This is from VSHub, which is a VS feature that communicates with an external process using SignalR. I don't know exactly what VSHub is for, but it can be really noisy in Fiddler if it can't use WebSockets.

It's interesting that it just started happening after installing RC1. Did you also install VS Update 1? That's more likely to have changed the behavior of VSHub.

**Comment by Fosol** [comment]
I've installed VS Update 1.  Still same issue.

**Comment by Eilon** [comment]
@jodavis any idea who owns that?

**Comment by tschlarm** [comment]
Also happening here. Hard to find what you are looking for. 

So far update 1 has been a mess for me. After updating, VS2015 came back up throwing ActivityLog messages all over and it removed some DLLs and prevented the DiagnosticsHub from loading. I had to do an uninstall/reinstall and then a repair after that to get back to a usable state.

I'd go back to RTM, but the install seemed to automatically updates to Update 1. Not a huge fan of this particular update so far.

**Comment by Eilon** [comment]
I found some contacts who work on VsHub so I'll share this issue with them and see what they say.

**Comment by tschlarm** [comment]
Thanks. I worked around the issue by filtering vshub in Fiddler, but hope it gets fixed.

**Comment by geowittejr** [comment]
I am also seeing this behavior after I installed VS2015 Update 1.  I was able to filter it out in Fiddler, but I think the constant flow of hits to localhost is slowing down the other traffic I care about on my dev machine.

**Comment by Gonkers** [comment]
I updated to VS2015 Update 1 2 days ago and I am now seeing the same issue. However I'm just using an .net451/MVC5 project none of the new stuff. I wanted to report that I'm seeing it too. However this probably isn't the place to report this 'bug'.

**Comment by punkouter** [comment]
I was brought here.. me too.. trying to debug a REST call in fiddler and spammed with this vshub thing

**Comment by cdickson123** [comment]
I also seeing the same behavior.The issue started after the VS 2015 updates installed.

**Comment by dr-noise** [comment]
Same behavior after installing VS2015 Update 1.

**Comment by Feanathiel** [comment]
Disabling the ASP.NET debugger in the project properties (Web-tab) will get around the huge amount of log lines for the moment (if you're not required to debug ASP.NET specific code).

**Comment by Eilon** [comment]
I've sent an email to some VS experts to get to the bottom of this and I'll update this issue when I find out more.

**Comment by AArnott** [comment]
This behavior has nothing to do with ASP.NET or the web site it hosts. VS offloads some of its work to other processes via a process we call VSHub. The transport we use for inter-process communication is HTTP. The VSHub processes act as HTTP servers using random ports with high numbers. Fiddler catches this localhost traffic along with the traffic of your actual web site. As several folks in comments above have reported, Fiddler can be configured to filter this out and from what I'm told, once the filter is configured, it can persist so that you don't see it any more.
If you see this in update 1 more than RTM, that may be because new features of VS use VSHub more heavily than they did before, but VSHub is in RTM as well.

We are looking at ways to reduce or eliminate the HTTP traffic in a future release of VS.

**Comment by Eilon** [comment]
@AArnott indeed, closing this.

Here's a quote from Anson Horton, who works on VsHub:

> There isn’t any traffic to the user’s site; this is localhost traffic that is being used as an IPC between devenv.exe and the VS Hub. There was a change to System.Net that caused this to start appearing in Fiddler – System.Net used to ignore proxy settings for localhost.  The volume of traffic is high due to a change that the diagnostics hub team made away from using SignalR to use polling instead. This information is used to populate the graphs on the diagnostics tools page.

> ... 

> I put an answer up on StackOverflow a couple of weeks ago that you can point to here - http://stackoverflow.com/questions/33837163/visual-studio-2015-vshub-is-spamming-fiddler/33928841#33928841.

**Comment by wstaelens** [comment]
Same problem (I'm not using AngleSharp, just asp.net mvc with bootstrap).

I used this to solve it: http://stackoverflow.com/a/34186109/187650

**Comment by Tomk77** [comment]
Just to let anyone know that's still having this issue, I solved it by disabling the diagnostic tools in the option menu.

![image](https://cloud.githubusercontent.com/assets/4995468/13392140/d4d94eb4-ded8-11e5-8225-9ff8e233c4f4.png)

**Comment by ikourfaln** [comment]
Thanx @Tomk77 but I think the right solution is to just disable the Memory/CPU monitoring in the Diagnostic Tools dialog box. Why ? bcz sometimes we need to profile other things (for example RAW SQL made by EF), so :

* Open the Diagnostic Tools window (Debug -> Show Diagnostic Tools)
* Click the "Select Tools" drop-down and un-check Memory Usage and CPU Usage. 

Now you should no longer see the requests being made to vshub

**Comment by chadcampbell** [comment]
There are two ways to address this:

1.  Update your diagnostic tools settings or
2.  Use a filter in Fiddler.

Personally, I prefer the latter as diagnostic tools offers some additional value. I wrote a blog post and provided a video on YouTube detailing this. The blog post can be seen [here](https://ecofic.com/about/blog/start-debugging-using-fiddler-while-vshub-is-running).

**Comment by navyjax2** [comment]
For me, those 2 options, going to Debug -> Windows -> Show Diagnostic Tools and removing the checkmarks on Memory and CPU monitoring on the "Select Tools" dropdown, or the one Tomk77 had with removing the checkmark on the "Enable Diagnostic Tools while debugging" -- neither of these worked to stop the requests.  I saw the Diagnostic Tools stop monitoring, within that window, and I didn't end my debug session, but it still kept making the requests, as far as Fiddler saw.  I just made a filter on "vshub" like it has here, instead, and this has been bringing me back to sanity:  https://stackoverflow.com/questions/33837163/visual-studio-2015-vshub-is-spamming-fiddler#
