### ISSUE TITLE
AmbiguousMatchException: Ambiguous match found.

### ISSUE THREAD

**Issue by himadrinath** [aspnet/Mvc#3656]
running mvc 6 in 1.0.0-rc1-final also have 2 different Class Library added as reference in this project. one of them class library used for maintain sqlserver data model with identity and another is for maintain sqlite data model. after creating relationship between models and updating database every thing works fine. and then when i created a mvc form which has 3 entities one parent entity (a) and other two (b) and (c) both of them has  one-to-one relationship with entity (a)

<b>builder.Entity&#60;a&#62;()
          .HasOne(u => u.b)
          .WithOne(t => t.a)
          .HasForeignKey&#60;b&#62;(b=> b.pubID).IsRequired()
          .OnDelete(Microsoft.Data.Entity.Metadata.DeleteBehavior.Cascade);</b>

<b>builder.Entity&#60;a&#62;()
            .HasOne(u => u.c)
            .WithOne(u => u.a)
            .HasForeignKey&#60;c&#62;(b => b.pubID).IsRequired()
            .OnDelete(Microsoft.Data.Entity.Metadata.DeleteBehavior.Cascade);</b>

and the post controller <b>public async Task&#60;IActionResult&#62; Create(A a)</b>.

when i submitting this single form with (a) and (c) entities its working fine but when i include (b) entity and submitting this form i getting an error.
 I can't figure it out. i tried to debug using break point but no luck. 

[System.Reflection.AmbiguousMatchException.txt](https://github.com/aspnet/Mvc/files/45487/System.Reflection.AmbiguousMatchException.txt)

**Comment by rynowak** [comment]
Does your model class have two properties with the same name but different casings, or perhaps a property that uses `new` to hide a base class property?

/cc @Eilon

**Comment by himadrinath** [comment]
some how i solved the problem but know i stuck with new one

https://github.com/aspnet/EntityFramework/issues/3923

thanks for your suggestions

**Comment by Eilon** [comment]
@himadrinath can you show the exact model code you have?

**Comment by himadrinath** [comment]
here is my 3 entities


[Advertisement.txt](https://github.com/aspnet/Mvc/files/48120/Advertisement.txt)
[Contact.txt](https://github.com/aspnet/Mvc/files/48121/Contact.txt)
[CellPhone.txt](https://github.com/aspnet/Mvc/files/48122/CellPhone.txt)

**Comment by Eilon** [comment]
Indeed, I see many public properties that differ only by case:

```c#
        [DefaultValue("NA")]
        [Required(ErrorMessage = "select a type")]
        [Display(Name = "Commercial")]
        [RegularExpression(@"Offering|Wanted|NA")]
        [Column("commercial", TypeName = "nvarchar(30)")]
        public string commercial { get; set; }

        [NotMapped]
        public Dictionary<string, string> Commercial;
```

**Comment by Eilon** [comment]
We could look at fixing this in MVC but it's definitely strongly recommended to *avoid* having public properties that different only by case.

**Comment by himadrinath** [comment]
thank you. i really appreciate it

**Comment by Eilon** [comment]
@rynowak any thoughts on what we'd want to do here?

**Comment by rynowak** [comment]
Make model binding case-sensitive? :trollface: 

Supporting this would mean adding case-insensitivity to a lot of infrastructure that has historically always been case-sensitive (model-metadata, and all rendering code).

**Comment by Eilon** [comment]
Could/should model binding proactively fail if it tries to bind such a property and say it isn't supported? (As opposed to failing in Reflection.)

**Comment by rynowak** [comment]
We could definitely throw a better exception, but it probably would happen when model metadata is initialized if we're being thorough.

**Comment by Eilon** [comment]
How bad would it be to throw when model metadata is initialized? Would the exception be thrown from a place that would make sense to someone? E.g. the first time that type is run through model binding?

**Comment by rynowak** [comment]
> How bad would it be to throw when model metadata is initialized? Would the exception be thrown from a place that would make sense to someone? E.g. the first time that type is run through model binding?

There's a few places this might show up:
- Model Binding
- Validation
- HtmlHelpers/TagHelpers

**Comment by Eilon** [comment]
Moving this to the backlog.

Ultimately, this is not a supported scenario in MVC. MVC cannot bind types that have properties that differ only by case.

**Comment by Eilon** [comment]
Closing because we have no plans to support this.
