### ISSUE TITLE
Triplicate null checks in CORS APIs

### ISSUE THREAD

**Issue by Jeffiy** [aspnet/Mvc#3657]
Hey, the code of https://github.com/aspnet/Mvc/blob/dev/src%2FMicrosoft.AspNet.Mvc.Cors%2FCorsAuthorizationFilter.cs#L54-L67, https://github.com/aspnet/Mvc/blob/dev/src%2FMicrosoft.AspNet.Mvc.Cors%2FCorsAuthorizationFilterFactory.cs#L39-L52 and https://github.com/aspnet/Mvc/blob/dev/src%2FMicrosoft.AspNet.Mvc.Cors%2FDisableCorsAuthorizationFilter.cs#L32-L45 are triplicate, is there any special purpose? 
Thanks.

**Comment by alexsandro-xpt** [comment]
LOL, it's fun.... at my knowledge, it's not make any sense... :full_moon_with_face:

**Comment by Jeffiy** [comment]
Should be fix ?

**Comment by Eilon** [comment]
Just needed to be *extra* sure the value wasn't `null` :smile:

**Comment by alexsandro-xpt** [comment]
:laughing:

**Comment by Eilon** [comment]
@pranavkm I assigned the PR to you.
