### ISSUE TITLE
Remove [InternalsVisibleTo] unit test projects

### ISSUE THREAD

**Issue by lodejard** [aspnet/Mvc#3666]
On one hand it can causing build errors when your tooling is out of date or isn't signing exactly right.

More importantly it enables poor design and test choices ten times more often than it enables correct testing. Far better to be confronted with and solve the question of "how can I test this component using its public api".

**Comment by Eilon** [comment]
@lodejard can you do a first pass and see if you can identify some obvious culprits that warrant deeper analysis?

**Comment by lodejard** [comment]
ROI is pretty bad on this one
