### ISSUE TITLE
Remove TextWriter.ToString from RazorPage

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3668]
Based on discussion here - https://github.com/aspnet/Mvc/pull/3664#discussion_r46205297

There's code in RazorPage (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorPage.cs#L267) where we invoke `ToString` on a `TextWriter` instance. This is likely to succeed only with specific kinds of `TextWriter`s such as `StringWriter`. We should remove this behavior.

**Comment by dougbu** [comment]
Isn't the issue a bit more general? Don't we call `ToString()` on `TextWriter`s elsewhere?

**Comment by pranavkm** [comment]
Not sure, but I'll look out for it.

**Comment by pranavkm** [comment]
I couldn't find any other instances where the framework calls ToString on a TextWriter. We have a couple of places where we invoke it on user provided objects but that wouldn't count.
