### ISSUE TITLE
Make TemplateRoute fields protected

### ISSUE THREAD

**Issue by oliverw** [aspnet/Mvc#3669]
`TemplateRoute` is a pretty good starting point for implementing custom routes. Unfortunately most of class's fields are neither `protected` nor exposed as properties which greatly diminishes the usefulness of `TemplateRoute` as a Base-class for custom route implementations.

**Comment by rynowak** [comment]
@danroth27 @Eilon - this is something I'm planning to do as part of routing improvements.

**Comment by Eilon** [comment]
@rynowak cool I guess I'll see it in the PR then.

**Comment by rynowak** [comment]
@oliverw - this is fixed by aspnet/Routing@36180ab6d0e48c42a1b69569897bdfb362f28c0c

If this doesn't meet your needs or satisfy your extensibility scenarios, please reopen.
