### ISSUE TITLE
Add test coverage for Flags enum binding in integration tests

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#3670]
As part of task https://github.com/aspnet/Mvc/issues/3624, the ValueProvidersWebSite is being deleted. Currently it covers some scenarios related to binding to Flags enum based parameters...I checked to see if there is existing coverage for this in integration tests but couldn't find any. So this task is to keep track of it.

**Comment by rynowak** [comment]
This is also a good candidate for the unit tests of `SimpleTypeModelBinder`

**Comment by kichalla** [comment]
ceaa9a92514bf4af87b5a0fae0a6c7e74c23b900
