### ISSUE TITLE
Add configuration option for tag helpers to generate dashed-case element IDs

### ISSUE THREAD

**Issue by CMircea** [aspnet/Mvc#3672]
At the moment tag helpers will generate element IDs using the same case as the C# property (eg. UserName, Profile_Email).

It would be great if there was a configuration option to customize the casing, such as dashsed-case. Even better if we could register a function that would be passed the generated ID and transform it to our liking.

At the coment this might be possible by extending DefaultHtmlGenerator, which itself would be a pain to do (overload every Generate\* function).

**Comment by Eilon** [comment]
The `id` attributes have to match the property names so that model binding can match them up on the way back in. There could probably be some kind of attribute like `[ModelBindingAlternateName(...)]` that would do this and it would have to be supported in both the HTML helpers and in model binding and it would transform and reverse the transform as needed.

Having said that, this is not a feature that we are planning to build at this time, but thank you for the suggestion.

**Comment by CMircea** [comment]
The ID attributes have nothing to do with model binding. That is for the name attribute, which is what specified what key that form element will have in the request. The ID attributes are visible only to the browser, thus locking them to be the exact same as the property is not ideal, as there are different conventions for client code.

It is possible to do this by extending the DefaultHtmlGenerator and replacing the ID attribute if present, but there are a lot of methods to override to cover all elements processed by MVC and is quite fragile.

**Comment by Eilon** [comment]
@CMircea ah you're right, thank you for the clarification. If you have suggestions on how we could make building such a feature a bit easier (e.g. refactoring some interface or something) do let us know, as that is something we are more likely to consider at this time.

**Comment by CMircea** [comment]
`DefaultHtmlGenerator` calls `tagBuilder.GenerateId(fullName, IdAttributeDotReplacement)` when generating form fields, which in turn calls the static `CreateSanitizedId`.

I think either there should be a constructor parameter to TagBuilder (an enum) which tells it how to generate the ID: CamelCase, lowerCase, dashed-case, snake_case; as well as a static default option, so we could override it globally (and have the existing CamelCase as the default). This would be useful when using TagBuilder manually.

The other option is to add either the same enum option to DefaultHtmlGenerator, or a method that would receive the name and return the ID that we could override, or even a method that would get the processed ID and change it. The latter is what I'm doing by overriding every `Generate*` method, by changing the ID in the `TagBuilder` object that is returned.

Here is my implementation: https://gist.github.com/CMircea/67da04f7f3fe1a556d2d

**Comment by Eilon** [comment]
@CMircea thanks for the update. I'm not sure I see the full feature being built-in to MVC at this time (e.g. an enum with options), but the idea of having a consistent way for custom code to configure/tweak/modify the HTML attributes doesn't seem out of the question.

One thing to note is that whatever ends up happening here, it wouldn't affect arbitrary HTML tags on a page. So if you had a plain old `<a href="..." id="UglyEvilCasing">...</a>` there's no code that runs for that, and it will be rendered verbatim. Would that be an issue for you?

@dougbu do you know of any easier way of tweaking all the HTML that's rendered by HTML helpers / tag helpers? Is the way shown by @CMircea 's gist the best current way?

**Comment by Eilon** [comment]
(Re-opening for discussion.)

**Comment by dougbu** [comment]
> do you know of any easier way of tweaking all the HTML that's rendered by HTML helpers / tag helpers?

The problem w/ adding a `TagBuilder` constructor parameter is instances are created everywhere. Would rather do something which could take advantage of the misnamed `HtmlHelperOptions` or which could be overridden in DI.

For the first, could pass more than the generated name and `IdAttributeDotReplacement` into `CreateSanitizedId()` but I'd rather move away from `TagBuilder` filling in the `id`, making the second approach sound better. If we made that step more explicit in `DefaultHtmlGenerator` and moved `GenerateIdFromName()` over from `HtmlHelper` (`virtual` of course), a `DefaultHtmlGenerator` subclass could do whatever anyone wants with the `id`s.

**Comment by CMircea** [comment]
Pretty much, yes. Dealing with the IDs is pretty common for me, I have to style particular elements, add JS events, initialize jQuery UI widgets, or even create custom inputs, keeping all the generated attributes (especially validation).

Why should the client-side element IDs match the server-side properties exactly? WebForms cared, but MVC shouldn't (and it doesn't) and provide a way to customize the generated one.

**Comment by Eilon** [comment]
My experience in these scenarios is to use `data-*` HTML attributes to control what happens to which elements, or to use other kinds of CSS selectors, such as child selectors.

In the case of `data-*` attributes I might apply something like a `data-showtooltip="This is a tooltip"` attribute, and then use a jQuery selector to locate all those attributes and apply some behavior to them.

Or with child selectors I might wrap a bunch of `<input>` tags in a `<div>` that has a well-known name and use child selectors to select all the `input` elements within that `div`.

Both of these techniques avoid needing to control the exact `id` elements of the tags.

Thoughts on this?

**Comment by mikes-gh** [comment]
+ 1 for this.

@danroth27  Nearly all modern apps deal with ids all the time in client side scripting.  I think you may be thinking of the name attribute.
Having the option to camel case or snake case or dash case will keep our JavaScript styles consistent..

**Comment by CMircea** [comment]
@Eilon using data-* attributes is not ideal, as multiple elements might have the same value and you might want to target just one. Furthermore lookup by data-* attributes is quite slow, the browser having to pretty much look at every single element.

**Comment by Eilon** [comment]
We will re-evaluate this in a future release. At this point we're working on stabilizing the current feature set.

**Comment by lvv83** [comment]
It will be nice to have some option to disable id attribute generation by default.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
