### ISSUE TITLE
Anti forgery token is not generated when form does not have tag helpers inside

### ISSUE THREAD

**Issue by alvipeo** [aspnet/Mvc#3674]
Create a form with no MVC tag helpers inside and anti-forgery token does not get generated.

**Comment by dougbu** [comment]
@alvipeo the different behaviour actually relates to the attributes you've included in the `<form>` tag, not to tag helpers inside the element. The `FormTagHelper` does nothing (i.e. the `<form>` element just has HTML semantics) unless you include an `asp-` attribute. If all you want is the antiforgery token, add `asp-antiforgery="true"`.

**Comment by alvipeo** [comment]
ok. here's my form:

    <form asp-action="godown" role="form" method="post" class="appointment">

Still no hidden field in the source.

**Comment by dougbu** [comment]
Hmm, that's odd. (I was also incorrect in my earlier comment: The no-op case occurs only if the `action` attribute is included in the `<form>` tag.)

Did you leave out the `</form>` end tag or self-close the element? Need a place to stick the `<input type="hidden" .../>` element.

**Comment by alvipeo** [comment]
ok, here's something weird - I had this issue https://github.com/aspnet/Home/issues/1144 and I fixed it and now I get the token.

**Comment by dougbu** [comment]
@alvipeo glad you're all set. Closing this issue.
