### ISSUE TITLE
Prototype Formatters without MediaTypeHeaderValue

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3683]
We should experiment with avoiding the `MediaTypeHeaderValue` abstraction in content-negotiation to see how much we can reduce allocations. This would reduce the amount of work that content-negotiation has to do, at the cost of some code duplication (moving parsing code into static methods).

We could still accept `MediaTypeHeaderValue` as an input for convenience (configuring the formatters), but at runtime all processing would be done using `StringSegment` and `StringValues`.

Some data based on the current state.... this is allocations from 3000 requests to an action reading JSON and returning JSON with a `CreatedAtRouteResult`. The request includes these headers to make sure content-negotiation has some work to do:
```
Accept: application/json; q=0.9, application/xml; q=0.6
Accept-Charset: utf-8
```

The total allocations from this sample are approx 49.9mb. Anything that's allocating more than 500,000 bytes is over 1% of the total and something we'd very likely want to address.

**MediaTypeHeaderValue** and related types:
![image](https://cloud.githubusercontent.com/assets/1430011/11566718/7bb31cf0-9998-11e5-915b-9f457405d479.png)

![image](https://cloud.githubusercontent.com/assets/1430011/11566874/3533051e-9999-11e5-9d42-a06599af6c62.png)

Just the cost of making this class part of our abstractions is too high.

**strings** (just showing relevant bits)

![image](https://cloud.githubusercontent.com/assets/1430011/11566756/a950e426-9998-11e5-8428-0c125d4fc828.png)

![image](https://cloud.githubusercontent.com/assets/1430011/11566775/bd42c3fa-9998-11e5-8a20-0f2a20e5cc0f.png)

![image](https://cloud.githubusercontent.com/assets/1430011/11566789/cd41076c-9998-11e5-9979-7bef2bd68aab.png)

If we can make this code allocation-free, then there's about 2.5mb of allocations we can rid ourselves of, that's 5% of the total :+1:

**Comment by davidfowl** [comment]
:smile:

**Comment by javiercn** [comment]
![image](https://cloud.githubusercontent.com/assets/6995051/12283914/153bdeca-b960-11e5-9518-72309e1cfd88.png)

The improvement is about 2525KB or 2.5MB

**Comment by dougbu** [comment]
@javiercn is the order of the screen snips above after then before?
