### ISSUE TITLE
Area tag helper - no error message until _ViewImports.cshtml is not included in Area/Views

### ISSUE THREAD

**Issue by miroslavsiska** [aspnet/Mvc#3685]
I use in my project Areas. I have area folders as follows: Areas/MyArea/Views/Shared In folder Shared is Layout.cshtml file for MyArea. I use Tag helpers in this Layout, but if you do not include in Folder Areas/MyArea/Views/   this file:   _ViewImports.cshtml no error occured and tag helper are not rendered correctly. View engine render to browser this line:

     <a  asp-route-area="AppManage" asp-controller="Home" asp-action="Index">Statistics</a>
instead of correct < a > html element. 
I believe, that it can be nice to show some error message for this scenario...

**Comment by dougbu** [comment]
From what you've said, your folders contain:
```
Areas/
  MyArea/
    Views/
      Shared/
        Layout.cshtml
      _ViewImports.cshtml
```
Where is the *.cshtml file that's referenced from your controller? Am I correct the _ViewImports.cshtml file sets the `Layout` property to `"Layout"`? And exactly what error is occurring or not occurring and when?

**Comment by danroth27** [comment]
@DamianEdwards 

I believe the feedback here is that it would be nice to get some sort of warning/error if you write Razor content that looks like it is using tag helpers, but you haven't actually enabled them.

I don't think there is much that we can do here. There isn't a way that we can accurately detect that the intent was to use tag helpers. The best we could do is heuristics.

**Comment by miroslavsiska** [comment]
Sorry for my delay.
@danroth27 Yes. This is right.
If is not included _ViewImports.cshtml in Area folder, you recieve no error message, until tag helpers are not generated properly...
If is difficult to show some error message, close this issue, Each one can see in html output, that tag helpers are not generated properly and solve this...

**Comment by danroth27** [comment]
Yeah, I don't think there is realistically any error message that we can give in this case.
