### ISSUE TITLE
Need to Set Layout in Controller

### ISSUE THREAD

**Issue by Tessalator** [aspnet/Mvc#3688]
The removal of the overloads View(view, layout) could be a significant breaking change, and is for me. I think being able to set the layout in the controller is important, especially in an enterprise settings where you have an enterprise library of layouts, and in domain driven architectures. 

Here is an approach I use that is no longer supported. 
I have an enterprise library of layouts (and other things). My project has business domain folders at the root. I created an attribute called "Layout". Now if I want to use a layout from the enterprise library I just decorate my controller with [Layout("~/Folder/_EnterpriseLayout.cshtml")] (I also have [LayoutPath("~/folder")], and [LayoutName("Name"). These are merged in a derived-from WebViewPage class. 

Another (to me) extremely valuable use of this is managing domain landing pages like "Index". I use the attributes at the action level too. When you enter a domain (e.g., controller) I want all of the home/index pages for all domains to have a common look, but the other pages in the domain/controller have their own look. If I decorate the Index action with these attributes I can have just the home page have its own layout and all of the other actions on the controller use a different layout. In my example the [Layout...] on the controller.

I have derived a custom WebViewPage ("ViewPage") that "overrides" the View(0 methods - like, new ActionResult View(view, layout, model){ base.View(view, layout, model) and handles all of the attribute fetching and resolution. This provides the ability to work with enterprise libraries.

An ideal fix would be to restore the ability to set layouts the way I have - create [LayoutPath(..)], [Layout.Name(...)] name attributes. This would allow the capabilities I need, and still remove the View() overloads that expose Layout. 

Out of curiosity, can you please let me know what lead to the decision to remove the layout parameter from the View methods?

[Added] This also gives better capability to move things in my project structure. By being able to contain file paths at the controller level I can move domains around without breaking anything.

**Comment by Eilon** [comment]
Thanks for the feedback. I honestly don't remember why we removed it. I think a more accurate way to look at it is that we *didn't add it back* -- MVC 6 started back from zero and we added things in.

One possible reason is that though layout pages are certainly *common*, they are not a universal feature of view engines, and even of view engines that support it, they might have completely different policies around how to configure them.

We can certainly look at adding this back - I'll discuss with the team.

**Comment by Tessalator** [comment]
Thanks Eilon. Where in the framework are the layouts and views merged? Maybe I can look at that and see if I can find a way to inject my layouts there.

**Comment by Eilon** [comment]
The Razor view does it: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorView.cs

**Comment by danroth27** [comment]
The ability to specify the layout via the controller was removed in part to keep the details of layout separate from the controller logic. It's really a feature of the view engine. So we think a custom layout should be specified in the view. 

You should be able to accomplish your scenario using a filter to pull out the layout metadata from the action and then use a custom view page base class to apply the layout.
