### ISSUE TITLE
In-View Support for LESS or Supporting Code in CSS 

### ISSUE THREAD

**Issue by Tessalator** [aspnet/Mvc#3689]
This enhancement may be in the works because I see the style type=text/less style tag. Some of the best features of LESS are the reusability features like variables and mixins, and doing math is valuable for layouts. Implementing these features in css is difficult, bloats the code, and makes the code cryptic.

In LESS I have a fixed layouts using absolute (px) width that have treeview and details layout divs I can use an `@pagewidth` in a top level LESS style sheet and use math for my widths. If I change `@pagewidth` at the top level the math on the pages adjusts everything.

There is a way I get similar capability without in-view LESS that is essentially a hack - but part of this I would call this a bug. 

I create a class for layout:

```c#
    public class sitestyles{ 
        public const int ViewPortWidthNumeric = 1080; 
        public static UnitsToString(string number){...} 
    }
```

In my View:

```c#
    @functions { 
      private class pagestyles : sitestyles{ 
        // Calculations 
        public const int TreeWidthNumeric = 300;
        public const int DetailsColumnWidthNumeric = ViewPortWidthNumeric - TreeWidthNumeric;
        // String Conversions 
        public static string TreeWidth = pagestyles.UnitsToString( TreeWidthNumeric );
        public static string ViewportWidth = pagestyles.UnitsToString( ViewPortWidthNumeric );
        public static string DetailsColumnWidth = pagestyles.UnitsToString(DetailsColumnWidthNumeric; } }
```

In my page css I can

```html
    <style>	#ActivityDetailsLayout { 
        width: @pagestyles.DetailsColumnWidth; }
    </style>
```

One (of several) problems with this approach it that once you add an @ in the css the IDE doesn't recognize the block as css and you lose all intellisense and error checking in the block. This is what I would consider a bug. I do see that implementing the @ in LESS conflicts with the Razor @ in some ways making implementing problematic across the board. Fixing

```html
	<style type="text/css">
```

to accept @classname may be a bugfix that helps implement css styling using C# code.

**Comment by danroth27** [comment]
The `@` character has specific meaning in Razor files and needs to stay consistent. You can escape the `@` by using `@@`.
