### ISSUE TITLE
DataAnnotationsLocalization does not cover [Display] attribute

### ISSUE THREAD

**Issue by yossarianeq** [aspnet/Mvc#3691]
I updated LocalizationWebSite's User.cs model with [Display(Name="UserName")]. 
Also, I added key-value UserName->UserNameTranslated into the resx file for given model.

I expected that /Home/GetInvalidUser?culture=fr will have UserNameTranslated as label for first textbox.
Actual result is 'UserName'.

**Comment by dougbu** [comment]
@yossarianeq I suspect you're asking for a #3518 fix. Correct?

**Comment by yossarianeq** [comment]
@dougbu Yes. Sorry for the duplicate, I was not able to find it.
