### ISSUE TITLE
Intellisense Broken in View <style> When Using Variables

### ISSUE THREAD

**Issue by Tessalator** [aspnet/Mvc#3694]
I broke this out of #3689 because I think it is a bug.

## Problem
Using variables in a View style block breaks Intellisense. This bug is not new to 6, but also exists in 5.

A C# variable in a View can be referenced in a style block. Everything works from a functional perspective. But Intellisense and error checking don't understand this, so editing this is just editing plain text without Intellisense help. 

### Code in View
Basic code:

	@functions{
	public class PageStyles{
		public string CssValue => "1080px";
	}}

	<style>
	   .PageSize{ height: @PageStyles.CssValue; }
	</style>

Intellisense/auto-complete and error checking are not functioning in the style block.

## Use Case
This is case where this functionality is used.

### Description
The example uses a layout that has a tree div on the left and a details div on the right. These are inside a container div. If we set the tree div width the details div width should be calculated to fill the container. The values can be changed at site level (ContainerWidth) or at the Layout (or View) level (TreeColumnWidth). C# code manages all of the changes and calculation, setting new property values.

CSS is used to implement the widths. Since the styles are local (#) to the page it makes sense to declare the CSS in the Layout/View. But it has dependencies on variables declared outside of these. By using C# properties/variables in the styles - height: @CssScope.CssValue - we get things like CSS Namespaces/Scope and the ability to change a variable in one place and let the C# process the CSS changes across the site without touching the CSS itself.

##### Comment
There are no new concepts here. This just extends the concept of having C# build and merge html in the view, to having it build and merge CSS too.

### Code

    @functions{
	public class LayoutPageStyles : SiteStyles {

		// Values are defined as numbers to do math
		// ContinerWidthValue is defined in SiteStyles, a site-level style class
		protected const int TreeColumnWidthValue = 300;
		protected const int DetailsColumnWidthValue = ContainerWidthValue - TreeColumnWidthValue;

		// Convert numbers to strings with units (e.g., 300px) for use in CSS 
		public static string TreeColumnWidth => Format.ValueToStringPx( TreeColumnWidthValue ); 
		public static string DetailsColumnWidth => Format.ValueToStringPx( DetailsColumnWidthValue );
	}

	// This class lives in a utility class file
	public static class Format {
		public static string ValueToStringPx( int value ) => value.ToString() + "px";
	}

	// This class lives at site level and contains values available in derived classes
	public class SiteStyles {
		protected const int ContainerWidthValue = 1920;
		public static string ContainerWidth => Format.ValueToStringPx( ContainerWidthValue );
	}}

    <style>
	    #OuterContainer{ width: @SiteStyles.ContainerWidth; }
	    #TreeColumn { width: @LayoutPageStyles.TreeColumnWidth; }
	    #DetailsColumn { width: @LayoutPageStyles.DetailsColumnWidth; }
    </style>

    
    <style>
	    .LayoutDiv{ padding: 0; margin: 0; border: none; border-width: 0; display: inline-block;}
    </style>

    
    <div id="OuterContainer">
	    <div id="TreeColumn" class="LayoutDiv">@RenderSection("TreeContent")</div>
	    <div id="DetailsColumn" class="LayoutDiv">@RenderSection("DetailsContent")</div>
    </div>

**Comment by Eilon** [comment]
Does it all work fine at runtime? Is it just VS that's not working here?

**Comment by Tessalator** [comment]
It is just the Intellisense/error checking part that doesn't work.

**Comment by Eilon** [comment]
Got it, thanks.

@NTaylorMullen can you see where the bug is, and if necessary, move the bug to Tooling?

**Comment by NTaylorMullen** [comment]
Will do. By the way @Tessalator well really well written bug :+1:

**Comment by NTaylorMullen** [comment]
@Tessalator I'm playing around with this and I'm seeing IntelliSense happening in Styles:

![image](https://cloud.githubusercontent.com/assets/2008729/11694292/1ec447f6-9e5e-11e5-873c-bfa028b888a0.png)

But i'm not seeing coloring. Is that what you were referring to?

**Comment by Tessalator** [comment]
If you complete that and then start typing "width" you won't get the CSS Intellisense.

**Comment by NTaylorMullen** [comment]
I see! Alright, this seems to be a tooling issue. Moving it there.

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Tooling#333
