### ISSUE TITLE
"exclude" section in the project.json didn't work correctly

### ISSUE THREAD

**Issue by VeselovAndrey** [aspnet/Mvc#3695]
I have following folder in my project that I want to exclude
[web project root]/Scripts/.bower_components
I tried different ways to add this folder to "exclude" section of the project.json like
Scripts/.bower_components
Scripts/.bower_components/**/*
Scripts/.bower_components/**/*.*
but fail. This folders and all it's files still added to project always.

Any suggestions?

**Comment by Eilon** [comment]
In what way is it not working?

**Comment by davidfowl** [comment]
The exclude section in `project.json` doesn't apply to the solution explorer (right now).

**Comment by VeselovAndrey** [comment]
Is there any way to exclude bower_components folder from solutions like node_components? It has many files that mess with search and trying to check-in into TFS.

**Comment by danroth27** [comment]
Tooling support for exclude tracked by https://github.com/aspnet/Tooling/issues/142

**Comment by danroth27** [comment]
Closing this bug in MVC since this is really a Tooling issue.
