### ISSUE TITLE
Html Helper missing RenderPartial

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Mvc#3705]
Mvc/src/Microsoft.AspNet.Mvc.ViewFeatures/Rendering/IHtmlHelper.cs

Does not contain RenderPartial.

I was upgrading my mvc5 project to mvc6 and came across this issue.

In the above file we have

Partial
PartialAsync
RenderPartialAsync

So I dont think its by design since if render methods were removed/depreciated I would also expect RenderPartialAsyc to be missing.

Even if we should be using a new methodology eg  @await Html.PartialAsync ?  its going to cause pain for upgraders.  What is the official line.  I am quite happy to find and replace but it seems unclear to me which way to go,

Thanks

Mike

**Comment by danroth27** [comment]
@rynowak @dougbu Do you guys remember why we don't have RenderPartial anymore?

**Comment by pranavkm** [comment]
We have the synchronous version of other Html \ Razor APIs, there's no reason for this one to not exist.

**Comment by Eilon** [comment]
Done?

**Comment by javiercn** [comment]
@Eilon Yes, I just changed the tag
