### ISSUE TITLE
Consistent names in framework-provided messages for Resources.ModelBinding_NullValueNotValid

### ISSUE THREAD

**Issue by renattomachado** [aspnet/Mvc#3711]
In issue #3226 it was asked that:

* `SimpleTypeModelBinder` adds `Resources.ModelBinding_NullValueNotValid` messages when no data is provided for a non-`Nullable` value type property or collection entry. This message includes the value but no property name or path.

But in the commit 40b7636b720298a06b9a42017a8bcace34132fad was not change this.

I wonder if this will be done?

**Comment by dougbu** [comment]
Issue #3226 was not fixed. MVC must avoid unnecessary information disclosure.

**Comment by renattomachado** [comment]
Excuse me, I think I did not understand. But you said that the property name is unnecessary?
