### ISSUE TITLE
Add the donut caching to MVC and make it work with sql dependency

### ISSUE THREAD

**Issue by rustd** [aspnet/Mvc#3721]
Copying this issue from the User Voice site. Please triage as needed.
https://aspnet.uservoice.com/admin/forums/41201-asp-net-mvc/suggestions/5401286-add-the-donut-caching-to-mvc-and-make-it-work-with

Donut Caching is important to make sure some part of a web page are not cached. But it doesn't work with SQL Dependency . 
For example in our website, we have blocs on the right col that must be refresh each time the page is reloaded. 
The main col must be refresh only when a new content is published (sql dependency)

**Comment by Eilon** [comment]
Not planned for the current release.

**Comment by mkArtakMSFT** [comment]
Closing this as there has been no community interest in this issue during this time and it's not planned to happen in the near future.
