### ISSUE TITLE
Support for polymorphic model binding

### ISSUE THREAD

**Issue by rustd** [aspnet/Mvc#3722]
Copying from UserVoice site https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/2215338-support-for-polymorphic-model-binding
Please triage as appropiate

MVC currently has a nice story around polymorphic models for display purposes using templates. However, this breaks down when you try to post back to the controller.

If your base class is abstract, then you get an error that MVC can't create the abstract type (which you don't want anyways because you want it to instantiate the concrete type). If you try to use multiple action methods that differ only by parameter (to handle each subclass) then you get errors about ambiguity.

I'd like to see two things added to MVC. First, support overloaded action methods within the same set of attributes.

Second, I'd like to see the default model binder able to figure out the concrete type and instantiate that, passing it to either the action method with the right parameter or to the base class parameter.

**Comment by khalidabuhakmeh** [comment]
Actually this would be very helpful. I've written something like this for previous versions of ASP.NET MVC. I actually wrote a [blog post about it](http://www.khalidabuhakmeh.com/fixing-asp-net-mvc-tryupdatemodel) at http://www.khalidabuhakmeh.com/fixing-asp-net-mvc-tryupdatemodel.

> Second, I'd like to see the default model binder able to figure out the concrete type and instantiate that, passing it to either the action method with the right parameter or to the base class parameter.

I could imagine a `hidden` input with a specific name. If it is present, it basically tells the model binding mechanism in ASP.NET MVC what the target type is rather than depending on the parameter of the `ActionResult`.

**Comment by Eilon** [comment]
We recommend building a custom model binder to do this. Having this as a general purpose feature can introduce security concerns (e.g. using a `hidden` field to allow *arbitrary* types to be created).

**Comment by clarkis117** [comment]
@Eilon Is there anywhere I can find information about building a custom model binder for MVC 6?

**Comment by Eilon** [comment]
@clarkis117 unfortunately that's an area that's not very well documented at this time. There are several built-in model binders in MVC, though, so you could use those as examples.

**Comment by clarkis117** [comment]
@Eilon I'm trying to deserialize covariant json arrays, where each object in the covariant json array shares the same base type. The wall I'm currently running into is that MVC during input is removing json.net's TypeNameHandling from the json, so all the type discriminators are removed before json.net gets a chance to discriminate which type is which.

**Comment by rynowak** [comment]
You can modify the JSON.Net settings we use

```
services.AddMvc().AddJsonOptions(options => options.Settings ...)
```

**Comment by clarkis117** [comment]
@rynowak  I've done that and added the CustomCreationConverters for Json.net, but as I mentioned before I still can't get around MVC removing the json.net TypeNameHandling from the json during input. Let me summarize this a little differently, during serialization I have json.net produce a '$type' variable on each json object that needs a type discriminator, i.e. the objects in the covariant arrays. However, when I take that same json and send it back to MVC, somewhere before the converters are called, all the '$type' variables are removed from the json. So, the CustomCreationConverters never see the type discriminators.
