### ISSUE TITLE
Render placeholder tag with Display data annotation

### ISSUE THREAD

**Issue by rustd** [aspnet/Mvc#3723]
Copying from UserVoice site https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/3397091-render-placeholder-tag-with-display-data-annotatio

Support Display(Prompt="...") data annotation in order to render HTML5 placeholder tag with this value

**Comment by Eilon** [comment]
@rynowak assigning to you to track the PR at https://github.com/aspnet/Mvc/pull/3788

**Comment by rynowak** [comment]
8b726ddc0ce208b41a07194af7052dbe14eed99f
