### ISSUE TITLE
EditorFor templates referencing from different mvc areas

### ISSUE THREAD

**Issue by rustd** [aspnet/Mvc#3724]
Feedback from UserVoice site https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/2080561-editorfor-templates-referencing-from-different-mvc
Please triage as needed.
Allow support for when using EditorFor that you can reference a template that is in a different area

**Comment by Eilon** [comment]
We have this support - just pass in an app-relative path to the custom CSHTML template:

```c#
@Html.EditorForModel("~/Views/CustomTemplate.cshtml")
```
