### ISSUE TITLE
ImageActionLink like we have ImageButton in asp.net webforms

### ISSUE THREAD

**Issue by ehsansajjad465** [aspnet/Mvc#3731]
It would be good to add ImageActionLink helper method by default in the mvc framework, so that we don't have to write our own extension method in project and there can be more helpers that are generally needed but this one i think should be in it.

**Comment by Eilon** [comment]
We recommend using tag helpers for this scenario:

`<a asp-action="Index" asp-controller="Home"><img src="..." alt="..." /> There's an image <b>and</b> text <i>and</i> HTML here!!!!!!!!</a>
