### ISSUE TITLE
Revisit Controller discovery conventions

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3732]
We have a complicated set of rules for controller discovery that involve looking at names, names of base-classes, which assembly defines a class/base-class, and which assemblies are referenced from an assembly.

We should figure out if/how we can streamline these rules. Some questions to discuss:
----------

**Should we require you to register assemblies that we use for discovery?**

**Should we require the ...Controller suffix in all cases**?

**Do we need opt-out/opt-in attributes**?

**Comment by rynowak** [comment]
A humble proposal:
- Options has a list of assemblies to look at - we pre-populate it with the 'main project' 
- Controller suffix applies only to the class we're looking at (not to base-classes)
- Provide a [Controller] attribute that is "Inherited" - you can put it on your class or a base-class

This is identical to what we're already doing for View Components

**Comment by danroth27** [comment]
Why would the attribute be inherited but not the suffix convention?

What would the experience be for project-to-project scenarios where my controllers are in a referenced project?

What would it look like if I have to use a common controller base time (ex from a package) for all of my controllers?

**Comment by rynowak** [comment]
> Why would the attribute be inherited but not the suffix convention?

Putting the attribute on a type makes a strong statement about its identity and role in your app. Names don't (`SqlTransactionController`). You don't get to change the name of your base class (other than choosing not to inherit from it).

> What would the experience be for project-to-project scenarios where my controllers are in a referenced project?

@lodejard and I both like the idea of having a 'list of assemblies' but having this list be populated by all assemblies in your app that reference MVC.

> What would it look like if I have to use a common controller base time (ex from a package) for all of my controllers?

```
[Controller]
public abstract class MyBaseController
{
}
```

**Comment by pranavkm** [comment]
Could we summarize what the design for this change is going to look like here?

**Comment by javiercn** [comment]
A class is considered a controller if:
* Inherits from a class with [Controller] (includes our base-classes)
* Use the suffix "Controller"

**Comment by jods4** [comment]
I hope this is a good place to discuss aspnet/Announcements#165 as there was no link over there...

Could you please summarize what class would have been considered a Controller in RC1 and work ok and not work anymore in RC2?

Reading the description I don't think we are impacted but we have lots of controllers...

**Comment by javiercn** [comment]
The following scenario

```C#
public class BaseController { }
```

```C#
public class Product : BaseController { }
```

Product would have been considered a controller as long as BaseController was in an assembly that referenced MVC. (We would look up on the inheritance chain and see if a base type ended in controller and was in an assembly that referenced MVC)

https://github.com/aspnet/Mvc/commit/de9ffb13c76d4f8225f388bc00309352d3bceac6#diff-d59fc41d7e9bd47511cc7c791e31ac4aL94

**Comment by darrelmiller** [comment]
In the announcement here https://github.com/aspnet/Announcements/issues/165 it says the following:

We now consider a type to be a controller if **all** of the following rules apply:
- The type is a public, concrete, non open generic class.
- [NonController]  is not applied to any type of the hierarchy.
- The type name ends with controller.
- [Controller]  is applied to the type or to one of its ancestors.

and then gives this example

     public class PocoController { } // controller name: Poco

But that class does not meet the last rule.  Am I mis-reading or should there be an OR between those last two rules?

**Comment by pranavkm** [comment]
Think there's an OR between the last two clauses - the type name either needs to have a `Controller` suffix or must have a `ControllerAttribute` applied.

**Comment by javiercn** [comment]
@darrelmiller What @pranavkm says is correct, I've changed the announcement post. Thanks for noticing and reporting!

**Comment by sunsided** [comment]
For unit testing, is there a way to detect controllers in a different assembly (e.g. my main server project)? That seems to be broken for me at the moment.

**Comment by javiercn** [comment]
@sunsided, I'm not sure I understood what you meant. Are you saying that controllers on separate assemblies are not showing up on your app? If that is the case, can you look at the list of application parts in IMvcBuilder (returned from AddMvc()) and see if the assembly is there? It will also be useful to know if you are using dnx or dotnet CLI and if you have preserveCompilationContext: true on your project json (this is required for dotnet CLI in order for MVC to discover assemblies in your app)

Thanks!

**Comment by sunsided** [comment]
@javiercn That was quick, thanks. Will have a look at all that tomorrow and report; it's a `net451` project built with `dotnet`, using the xUnit console runner as a workaround, unit tests are in a separate assembly using the `TestServer`. (Used to work back in `dnx451` days.)

**Comment by sunsided** [comment]
@javiercn `preserveCompilationContext: true` in the unit test assembly did the trick, thanks alot!
