### ISSUE TITLE
adding TagHelpers breaks existing <select> elements with Razor in the option tags

### ISSUE THREAD

**Issue by tom-cognify** [aspnet/Mvc#3733]
if I add `@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"`

existing `<select>` elements like this:
``` html
<select>
  @foreach (var item in MyList)
  {
    <option value="@item.Value" @if (item.Value == Model.ToString()) { <text> selected="selected" </text> }>@item.Key</option>
  }
</select>
```

That have inline razor code throw an error "the tag helper 'option' must not have C# in the element's attribute declaration area.

Why does it assume the option is a taghelper? Is there a way to override this?

sorry about the code formatting, could not figure out how to make github format this...

**Comment by NTaylorMullen** [comment]
Yup, this is by design. We currently have an issue over in Razor tracking this: https://github.com/aspnet/Razor/issues/96.

As a workaround I'd recommend doing the following for your option tag:

```HTML
<option value="@item.Value" selected="@(item.Value == Model.ToString())">@item.Key</option>
```

**Comment by dougbu** [comment]
Another option is to use `<!option ...>...</!option>` to ensure Razor does not associate the element with a tag helper.

FYI I reformatted your example.

**Comment by tom-cognify** [comment]
ok, thanks, yeah the ` <!option ..> ` was what I was looking for, I know I can rework these, but I have a lot of legacy code that I ported over from MVC 5 so that will be a lot easier for now.

**Comment by rickythefox** [comment]
<!option ...>...</!option> does not seem to work inside foreach loops.

**Comment by dougbu** [comment]
@rickythefox could you provide more detail on what doesn't work w/ `<!option>` w/in a `foreach`?

**Comment by rickythefox** [comment]
Sure! The code below does not compile in a Razor view (trivial example, will set all options to selected):
```
<select class="form-control">
    <option value="-1">None</option>
    @foreach (var item in Html.GetEnumSelectList<MyEnum>())
    {
        var selected = " selected";
        <!option value="@item.Value" @selected >@item.Text</!option>
    }
</select>
```

**Comment by dougbu** [comment]
@rickythefox since you're doing everything manually, you must set `selected` to `string.Empty` in at least some cases.

##### Details
Your code _explicitly_ sets the `selected` attribute for all generated `<option>`s. Tag helpers are not doing anything in this example: The `SelectTagHelper` matches the `<select>` element but no-ops. And, the `OptionTagHelper` matches (just) the first `<option>` element but also no-ops. (The earlier problem was the `OptionTagHelper` matched all `<option>` elements but tag helpers do not support `@selected` and similar attribute name / value expansions.)

**Comment by rickythefox** [comment]
@dougbu my bad, the code is marked as invalid by VS so I assumed it would not compile. In reality the `selected`var gets its value from somewhere, this is just a trivial example so i hardcoded it to a string. :)

![image](https://cloud.githubusercontent.com/assets/1675955/12273628/45f591c6-b967-11e5-9564-9eb30c8258fd.png)

**Comment by mikethetike** [comment]
I went with this option, which doesn't get highlighted as invalid in VS.

```
<select class="form-control">
      <option value="-1">None</option>
      @foreach (var item in Html.GetEnumSelectList<MyEnum>())
      {
           
           @: <option value="@item.Value" @(item.Selected ? "selected" : "") >@item.Text</option>
       }
</select>
```
