### ISSUE TITLE
Simplify extending the framework's default behavior

### ISSUE THREAD

**Issue by dotnetjunkie** [aspnet/Mvc#3739]
With the current versions of ASP.NET MVC and Web API it is really easy to extend the default configuration with your own code, by wrapping framework behaviour in your own code. A very common practice is to create a decorator for a framework provided abstraction that extends the framework behaviour and that internally delegates to the original behaviour. This prevents recreating complete (and possible complex) framework logic.

Since in MVC and Web API all framework abstractions are singletons, that are available at the time user code runs, we can simply grab the default implementation, wrap it in our decorator and replace the original implementation. We can repeat this as often as we want.

ASP.NET 5 however, gives us a completely new configuration model, where we add/replace configurations to a collection of `ServiceDescriptor` objects. Replacing a default implementation is still straightforward, for instance:

    services.Add(ServiceDescriptor.Instance<IHttpContextAccessor>(
        new NeverNullHttpContextAccessor()));

However, wrapping an original implementation seems really awkward. It is of course very common to extend framework behaviour this way. For instance:

``` c#
IHttpContextAccessor original = // grab the original: but how exactly?

services.Add(ServiceDescriptor.Instance<IHttpContextAccessor>(
    new NeverNullHttpContextAccessorDecorator(original)));
```

Do note that the use of the `IHttpContextAccessor` is just an example, but does effectively show the problem. The `services` collection contains `ServiceDescriptor` objects, and in the case of the `IHttpContextAccessor`, the `ImplementationInstance` and `ImpementationFactory` properties are empty, making it impossible to get that original instance or to get some func for getting it. We can't inject an `IServiceProvider` into the decorator to delay the registration, because once we request an `IHttpContextAccessor` inside our decorator, we will get that same decorator back, which will cause a stackoverflow exception.

One way to do this is by using an intermediate service provider, like this:

``` c#
var innerSp = services.BuildServiceProvider();
var original = innerSp.GetService<IHttpContextAccessor>();
services.AddInstance<IHttpContextAccessor>(new HttpContextAccessorDecorator(original));
```

This however feels really hacky and might even be very performance heavy.

We absolutely need a better solution for this very common use case.

**Comment by dotnetjunkie** [comment]
Updated and fixed the original post.

**Comment by davidfowl** [comment]
You can't do this with arbitrary services but if you can point out some of the things you'd want to wrap it might make sense to take a look at those. There's no easy way to express the decorator pattern using DI systems like this.

> With the current versions of ASP.NET MVC and Web API it is really easy to extend the default configuration with your own code, by wrapping framework behaviour in your own code. A very common practice is to create a decorator for a framework provided abstraction that extends the framework behaviour and that internally delegates to the original behaviour. This prevents recreating complete (and possible complex) framework logic.

Can you give examples of things you used to do and how you used to do it? That'll be a good starting point for this discussion.

**Comment by ploeh** [comment]
> There's no easy way to express the decorator pattern using DI systems like this.

What does that tell us about the current design of that system?

**Comment by davidfowl** [comment]
> What does that tell us about the current design of that system?

You tell me.

BTW, this wasn't easy before either. That's why I asked for examples. If you can show me what used to work and what doesn't work then it'll be a good starting point. 

I'm not here to discuss philosophy :smile:

**Comment by dotnetjunkie** [comment]
> BTW, this wasn't easy before either.

I'm sorry to say, but it actually IS much easier today. For instance, this is how to do it in Web API:

``` c#
config.Services.Replace(typeof(IHttpControllerActivator),
    new ExtendedControllerActivator(config.Services.GetHttpControllerActivator()));

config.Services.Replace(typeof(IContentNegotiator),
    new CustomContentNegotiator(
        (IContentNegotiator)config.Services.GetService(typeof(IContentNegotiator))));
```

**Comment by davidfowl** [comment]
@dotnetjunkie great!

The key difference being you can get single instances? 

```C#
new ExtendedControllerActivator(config.Services.GetHttpControllerActivator())
```

This one is as bad as what we have today:

```C#
config.Services.Replace(typeof(IContentNegotiator),
    new CustomContentNegotiator(
        (IContentNegotiator)config.Services.GetService(typeof(IContentNegotiator))));
```

The difference being that you can't get ahold of any instances until after container build up. 

Will think about this a little bit. It does suck that you'd have to make an intermediate container (but that's basically what you're doing with the above anyways. You're resolving the original `IContentNegotiator` and replacing the in box one with the wrapped one.

**Comment by ploeh** [comment]
> Will think about this a little bit.

Sounds good. If you need inspiration, you can always re-read my article on [DI-friendly frameworks](http://blog.ploeh.dk/2014/05/19/di-friendly-framework) :smile:

**Comment by dotnetjunkie** [comment]
> This one is as bad as what we have today

Not exactly. With building an intermediate service provider we lose one important promise. That is the promise that singletons are guaranteed to have only one instance. My previous example actually demonstrates this problem:

``` c#
var innerSp = services.BuildServiceProvider();
var original = innerSp.GetService<IHttpContextAccessor>();
services.AddInstance<IHttpContextAccessor>(new HttpContextAccessorDecorator(original));
```

This code looks pretty innocent, but what if the framework's original `IHttpContextAccessor` depends on a component X that is registered as singleton? Building the intermediate service provider and resolving the `IHttpContextAccessor` will create a single instance of X as well. But once the final service provider is built, that component X will be created again, breaking the promise that there will be at most one instance of X. Whether or not this will cause problems depends on the implementation of X, but breaking such guarantee is actually a quite serious problem, because now the framework's registrations can't be trust anymore.

You might argue that the `IHttpContextAccessor` implementation doesn’t have any dependencies at all, and this might be true, at this moment in time, but there is no way for the user to know (without diving into the framework’s source code) and this might change in a future version of the framework.

Also note that it doesn’t really matter whether we resolve the `IHttpContextAccessor` from the intermediate service provider directly, or we inject a delegate into our custom `HttpContextAccessorDecorator ` that allows resolving from the intermediate provider later on; the promise of X being a singleton is still broken.

The following registration might be ugly:

``` C#
config.Services.Replace(typeof(IContentNegotiator),
    new CustomContentNegotiator(
        (IContentNegotiator)config.Services.GetService(typeof(IContentNegotiator))));
```

But in Web API we have the guarantee that this doesn't break any singleton guarantees. In other words, this 'ugly' registration is actually safe and guaranteed to work correctly, in the current version of Web API and in any possible future versions of Web API as well.

**Comment by tuespetre** [comment]
@ploeh:

> What does that tell us about the current design of that system?

Challenge accepted.

I get a `StackOverflowException` if I try to resolve the wrapped service within an implementation factory, and I get a 'Circular Dependency' exception if I try to depend on the wrapped service in the constructor of the wrapping service, so that tells me that the DI system could switch to using a stack for its implementation in order to allow later-registered services to depend on earlier-registered services with the same registered type. :fist:

**Comment by davidfowl** [comment]
Not "the" DI system, *all* DI systems.

**Comment by ploeh** [comment]
> Not "the" DI system, *all* DI systems.

With [Pure DI](http://blog.ploeh.dk/2014/06/10/pure-di), it's *trivial* to compose object graphs that include [Decorators](https://en.wikipedia.org/wiki/Decorator_pattern) and [Composites](https://en.wikipedia.org/wiki/Composite_pattern).

[Castle Windsor](http://www.castleproject.org/projects/windsor) *natively* understands both Decorators and Composites, and correctly composes object graphs with these included.

**Comment by davidfowl** [comment]
autofac? Structure map? How does it work?

**Comment by davidfowl** [comment]
Just want to say, we have no plans on exposing instances the way we did before, now that we have a DI system.

**Comment by ploeh** [comment]
Autofac, StructureMap, and other DI Containers I know of, don't understand these well-known design patterns (which are as recent as 1994, so I'm guessing these libraries are still catching up), but you can still make them. In addition to Castle Windsor, where *it just works*, I cover how to do this with Autofac, StructureMap, Spring.NET, Unity, and MEF in [my book](http://amzn.to/12p90MG).

**Comment by dotnetjunkie** [comment]
@davidfowl I still like to know how you are going to address the 'failing singleton promise' problem I described above.

**Comment by dotnetjunkie** [comment]
> autofac? Structure map? How does it work? 

I can't speak for Autofac and StructureMap, but with Simple Injector, using the following model:

``` c#
interface IValidator<in T> { 
    void Validate(T instance); 
}

class CustomerValidator1 : IValidator<Customer> { ... }
class CustomerValidator2 : IValidator<Customer> { ... }
class ProductValidator : IValidator<Product> { ... }

class CompositeValidator<T> : IValidator<T> {
    private IEnumerable<IValidator<T>> validators;
    public CompositeValidator(IEnumerable<IValidator<T>> validators) {
        this.validators = validators;
    }
    public void Validate(T instance) { 
        validators.ToList().ForEach(v => v.Validate(instance)); 
    }
}

class LoggingValidatorDecorator<T> : IValidator<T> {
    IValidator<T> decoratee;
    public ValidatorDecorator(IValidator<T> decoratee) {
        this.decoratee = decoratee;
    }
    public void Validate(T instance) {
        Logger.Log("validating " + instance.GetType().Name);
        decoratee.Validate(instance);
    }
}
```

We can make the following registrations:

``` c#
container.RegisterCollection(typeof(IValidator<>), myAssemblies);
container.RegisterSingleton(typeof(IValidator<>), typeof(CompositeValidator<>));
container.RegisterDecorator(typeof(IValidator<>), typeof(LoggingValidatorDecorator<>));
```

What this registration does is:
 - Batch-register all non-generic implementations of `IValidator<T>` (found in supplied list of `Assembly` instances) as registrations of `IEnumerable<IValidator<T>>`.
 - It registers a composite validator. This composite will be resolved when a single `IValidator<T>` is requested, and it will be injected with the previously registered collection of validators.
 - Each resolved validator (both the composite and each validator in the collections) will be wrapped with the `LoggingValidatorDecorator<T>`.

**Comment by Eilon** [comment]
This is ultimately not an MVC issue but rather a general DI pattern. Closing this out in favor of https://github.com/aspnet/DependencyInjection/issues/340, which covers the general problem.
