### ISSUE TITLE
Url's Without Trailing Slashes

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#3740]
If I turn on `AppendTrailingSlash` so that all URL's created by `IUrlHelper are created with a trailing slash like so:

```
// All generated URL's should append a trailing slash.
routeOptions.AppendTrailingSlash = true;
```

Now I want to create an action in my controller that looks like it returns a file e.g. robots.txt like so:

```
[Route("robots.txt")]
[NoTrailingSlash]    // Proposed filter attribute
public IActionResult RobotsText()
{
    string content = this.GetRobotsContent();
    return this.Content(content, "text/plain", Encoding.UTF8);
}
```

In this case I don't want this URL to have a trailing slash as I want it to be treated as a file. when I create a URL, I have to add a `TrimEnd('/')` like so:

```
@Url.RouteUrl(HomeControllerRoute.GetManifestJson).TrimEnd('/')
```

However, this is very error prone and I always forget to add the `TrimEnd('/')` to the link. Is there some way for me to create a `[NoTrailingSlash]` attribute which can be added to the action and hooks into an extensibility point for IUrlHelper and remove the trailing slash for me?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
