### ISSUE TITLE
Microsoft.AspNet.Mvc package won't install in .Net 4.6 or .Net 4.5.1 class libraries

### ISSUE THREAD

**Issue by johnnyoshika** [aspnet/Mvc#3742]
I'm trying to get `Microsoft.AspNet.Mvc 6.0.0-rc1-final` package to install in .Net 4.6 or .Net 4.5.1 class libraries so that I can share View Components in multiple web projects, but the installation fails and NuGet needs to roll back.  Here's what I see:

![image](https://cloud.githubusercontent.com/assets/504505/11749846/ef97b3f4-9fe4-11e5-8342-59f4a9efb555.png)
...
![image](https://cloud.githubusercontent.com/assets/504505/11749857/fd64aac8-9fe4-11e5-98f7-a10823348831.png)

**Comment by davidfowl** [comment]
I'd recommend using a Class Library (Package) instead.

**Comment by johnnyoshika** [comment]
Thank you.  `Class Library (Package)` worked!  Closing.
