### ISSUE TITLE
Layout set from base RazorPage is overwritten

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#3745]
When using a custom `RazorPage` base class which assigns a default `Layout` value for instance in its constructor, it will be overwritten by null when there are no `ViewStart` available or when no `ViewStart` is defining a Layout, hence losing the default Layout value.

The code here https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorView.cs#L174 should not overwrite the `RazorPage.Layout` if `layout` is null.

The view is executed after this step, so if is not impacted by this change and will always win which is expected.

**Comment by dougbu** [comment]
1b7e672
