### ISSUE TITLE
Make extending `IUrlHelper` easier by exposing context info

### ISSUE THREAD

**Issue by Kukkimonsuta** [aspnet/Mvc#3749]
What is the recommended strategy to extend `IUrlHelper`?

In previous version of MVC, there was public property `RequestContext` on `UrlHelper` allowing access to request info from within static extension method. Similar properties exist in current version of `UrlHelper`, but are all protected which prevents us from extending the helper and forcing us to use inheritance instead. This works when user wants to customize `UrlHelper` and inject it into his application, but denies extending `UrlHelper` from multiple locations (libraries).

**Comment by tuespetre** [comment]
Do you have a particular scenario for an extension method for `IUrlHelper` or `UrlHelper` within ASP.NET 5? Perhaps there is another way to achieve what you desire.

**Comment by Kukkimonsuta** [comment]
My scenario are the following helpers:

* `Is(object values)` - check whether the current request contains given `values`
* `Has(params string[] keys)` - check whether the current request contains given `keys` regardless of their values
* `Current(object with = null, string[] without = null)` - returns current url with given values (`with`) and without given keys (`without`)

Note that all of these work on all of `RouteData.Values`, `RouteData.DataTokens` and `Request.Query` at the same time, so for path `/users/index?page=10` `Url.Current(with: new { sort = "name" })` would return `/users/index?page=10&sort=name` and not just `/users/index?sort=name` like `Url.Action(null, new { sort = "name" })` would.

MVC 5 implementation: https://github.com/Kukkimonsuta/Clutch/blob/master/src/Clutch.Web.Mvc/CurrentUrlHelper.cs

MVC 6 implementation or `Is`:
```c#
public bool Is(object values)
{
	var actionContext = ActionContext;

	var query = actionContext.HttpContext.Request.Query;
	var routeValues = actionContext.RouteData.Values;
	var dataTokens = actionContext.RouteData.DataTokens;

	foreach (var pair in new RouteValueDictionary(values))
	{
		var value = pair.Value.ToString();

		if (query[pair.Key].Any(v => string.Equals(v, value, StringComparison.OrdinalIgnoreCase)))
			continue;

		var routeValue = default(object);
		if (routeValues.TryGetValue(pair.Key, out routeValue) && string.Equals(routeValue?.ToString(), value, StringComparison.OrdinalIgnoreCase))
			continue;

		var dataToken = default(object);
		if (dataTokens.TryGetValue(pair.Key, out dataToken) && string.Equals(dataToken?.ToString(), value, StringComparison.OrdinalIgnoreCase))
			continue;

		return false;
	}

	return true;
}
```

However this done by inheriting `UrlHelper` and injecting the new implementation instead, which effectively breaks any sort of similar extension.

**Comment by Eilon** [comment]
One option is to write your own distinct helper instead of reusing/replacing `IUrlHelper`.

That is, just invent your whole new thing:

```c#
public interface ISuperUrlHelper
{
    bool SomeSuperMethod(...);
}

public class MySuperUrlHelper : ISuperUrlHelper
{
    public MySuperUrlHelper(IDependency1 dep1, IDependency2 dep2, ...)
    {
        ...
    }

    public bool SomeSuperMethod(...)
    {
        return dep1.Whatever + dep2.Whatever2;
    }
}
```

And then register this service in your app's `Startup`. And then in your controllers and/or views use your new super service.

Ultimately, the problem here is somewhat of a philosophical one: how far should you be able to extend an interface beyond its current limits? What if your method needs some completely random service like `IFrobulator`? That will never be added to `UrlHelper` or `IUrlHelper` because it is too specialized.

So, the philosophy here would indicate that if you're doing something that is beyond what `IUrlHelper` does then you probably don't belong on `IUrlHelper`.

**Comment by Kukkimonsuta** [comment]
> Ultimately, the problem here is somewhat of a philosophical one: how far should you be able to extend an interface beyond its current limits? What if your method needs some completely random service like IFrobulator? That will never be added to UrlHelper or IUrlHelper because it is too specialized.

If the extensions needed to work with other services, that's probably where I'd draw the line, but I believe these helpers should be extensible within their intended use. `IUrlHelper` should expose `ActionContext` because it's reasonable to assume, that every implementation will depend on it and extensions will need it. The same works for `IHtmlHelper` already, which exposes `ViewContext` ( https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ViewFeatures/Rendering/IHtmlHelper.cs#L45 ).

**Comment by rynowak** [comment]
> IUrlHelper should expose ActionContext because it's reasonable to assume, that every implementation will depend on it and extensions will need it. The same works for IHtmlHelper already, which exposes ViewContext

This is something we could do. We already expose it as a protected property on the concrete class for scenarios where you subclass.

**Comment by Eilon** [comment]
Yeah I agree we might as well expose it. Pretty useless otherwise.

**Comment by Eilon** [comment]
Let's expose the context through the interface so that extension methods can use it.
