### ISSUE TITLE
How to return static file content as View?

### ISSUE THREAD

**Issue by neilyoung** [aspnet/Mvc#3751]
Hi,
I'm trying to combine ember with aspnet5/mvc.

```c#
    namespace api.Controllers
    {
        [Route("/")]
        public class HomeController : Controller
        {
        	private readonly IApplicationEnvironment _appEnvironment;
            public HomeController(IApplicationEnvironment appEnvironment) {
                _appEnvironment = appEnvironment;
            }
            // GET: /<controller>/
            public IActionResult Index()
            {
                return View(_appEnvironment.ApplicationBasePath + "/client/dist/index.html");
               
            }
        }
    }
```

But this seems to not work because I'm getting this in the console while running  "dnx web"

```
fail: Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor[0]
      The view '/Users/me/Projects/api/client/dist/index.html' was not found. Searched locations: /Users/me/Projects/api/client/dist/index.html
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[3]
      Request finished in 0,0247ms 500
fail: Microsoft.AspNet.Server.Kestrel[13]
      An unhandled exception was thrown by the application.
      System.InvalidOperationException: The view '/
Users/me/Projects/api/client/dist/index.html' was not found. The following locations were searched:
      /Users/me/Projects/api/client/dist/index.html.
```

However, the file is there.

**Comment by brockallen** [comment]
Use the `FileResult` or `File()` helper from the `Controller` base class. This is essentially the same as prior versions of MVC.

**Comment by neilyoung** [comment]
Thanks, but File() was the first I tried. Lead to the same result: IOException File not found.

**Comment by brockallen** [comment]
`File` is relative to your `wwwroot` folder.

**Comment by neilyoung** [comment]
Ah, ok. Then it cannot work. Kind of same manipulation works in ASP .net 4.x, MVC5

**Comment by brockallen** [comment]
Look at the `FileStreamResult` class -- it looks like it supports streaming files.

**Comment by Eilon** [comment]
`return View()` is reserved for returning the result of a view execution, i.e. a Razor CSHTML page. You can't use an HTML page for that.

As @brockallen mentioned you need to use one of the various file-based result types. There are ones for when you have a virtual path (relative to the app root), ones for `byte[]` contents, and ones for when you have a `Stream`.

I would think that this should work:

```c#
return File("~/client/dist/index.html");
```
