### ISSUE TITLE
TemplateEngine

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Mvc#3753]
Is is possible to have something like these template engines in ASP.NET 5 foundation?
http://twig.sensiolabs.org. The flexible, fast, and secure template engine for PHP.
http://freemarker.incubator.apache.org.  A Java library to generate text output (HTML web pages, e-mails, configuration files, source code, etc.) based on templates and changing data.

**Comment by dougbu** [comment]
@mikeandersun what is your remaining question? I answered the "Is it possible" question in aspnet/Razor#642:
> one approach is to create your own IViewEngine implementation and add it to MvcViewOptions.ViewEngines in a site's Startup.

**Comment by Eilon** [comment]
Not clear what's being asked here. It is possible to write custom view engines based on any templating language...
