### ISSUE TITLE
Add logging for view compilation

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#3755]
For each page compiled:

- View -> CS file
- CS file -> Assembly
- Show cache hits and misses 

/cc @rynowak @pranavkm @lodejard

**Comment by pranavkm** [comment]
Slightly related - do we want to make the generated code available somewhere? The Glimpse folks weren't super interested in it.

**Comment by rynowak** [comment]
@davidfowl why? Just for funzies or is there a scenario in mind?

**Comment by davidfowl** [comment]
Super useful for getting a rough idea of where time is spent when loading views.
