### ISSUE TITLE
Is there still something like ValidateInput

### ISSUE THREAD

**Issue by chassq** [aspnet/Mvc#3756]
I am trying to allow any characters to come through on a singleaction method. For this specific method we will handle the data cleansing manually. MVC 4 had the ValidateInput attribute. What would we use in MVC 5?

Thanks!

**Comment by davidfowl** [comment]
There is nothing like validate input in ASP.NET 5 (that includes MVC 6). You'll need to write something yourself.

**Comment by chassq** [comment]
Ok, thanks David!

**Comment by cottsak** [comment]
@davidfowl But what does this mean for the default behaviour?

By default, will active scripts, etc be rejected (exception thrown) when detected in input like previous MVC?

**Comment by Eilon** [comment]
@blowdart this is your area of expertise.

**Comment by blowdart** [comment]
Request validation no longer exists. It hasn't worked well for years, and frankly acted as a false sense of security. It won't be coming back.

Given that Razor encodes all output by default, it's a lot harder to sneak a script tag in that it was during webforms where there was no consistency between controls over what was and what wasn't encoded.

**Comment by cottsak** [comment]
@blowdart Thanks mate. Prob for the best then.

// @JakeGinnivan
