### ISSUE TITLE
cannot use string value for "asp-for"

### ISSUE THREAD

**Issue by huoshan12345** [aspnet/Mvc#3759]
I'm using Musicstore project. In login.cshtml, there are some codes:
```html
<div class="form-group">
	<label asp-for="Email" class="col-md-2 control-label"></label>
	<div class="col-md-10">
		<input asp-for="Email" class="form-control" />
		<span asp-validation-for="Email" class="text-danger"></span>
	</div>
</div>
```
I make some changes like this:
```html
@{
	string e = "Email";
	<div class="form-group">
		<label asp-for=@e class="col-md-2 control-label"></label>
		<div class="col-md-10">
			<input asp-for=@e class="form-control" />
			<span asp-validation-for=@e class="text-danger"></span>
		</div>
	</div>
}
```
Then it cannot work, since it generates wrong codes:
```html
<div class="form-group">
	<label class="col-md-2 control-label" for="e">e</label>
	<div class="col-md-10">
		<input class="form-control" type="text" id="e" name="e" value="Email" />
		<span class="text-danger field-validation-valid" data-valmsg-for="e" data-valmsg-replace="true"></span>
	</div>
</div>
```

The reason why I try to do that is because I want to select some properties of an entity in the controller and use loop to show the properties in the view.For example:
In the controller file:
```C#
public IActionResult Edit(string id)
{
	var model = GetModel(id);
	var columnNames = new List<string>()
	{
		"Name",
		"Email"
		// add some column names
	};
	ViewData["ColumnList"] = columnNames;
	return View(model);
}
```
In the view file:
```html
@{
	var columnNames = (List<string>)ViewData["ColumnList"];
	foreach (var item in columnNames)
	{
		<div class="form-group">
			<label asp-for="@(item)" class="col-md-2 control-label"></label>
			<div class="col-md-3">
				<input asp-for="@(item)" class="form-control" />
				<span asp-validation-for="@(item)" class="text-danger"></span>
			</div>			
		</div>
	}
}
```

How should I do?
Is it possible in razor?

**Comment by dougbu** [comment]
Need to include more information in the Linq expressions for the helpers to generate the correct `id` and `name` attributes. Recommended approach is a `for` loop e.g.
``` c#
   for (var i = 0; i < Model.Count; i++)
  {
    <input asp-for="@Model[i]" />
  }
```

However tag builders deal with Linq expressions, not `ViewData` entries. Recommend using a view model rather than populating `ViewData`.

**Comment by huoshan12345** [comment]
@dougbu I'm so sorry i didn't make myself clear(-_-My poor English)

In my case, I want to write a Edit.cshtml for an entity, so the model is an entity not a list of entities. I want to pass some properties of the entity from the contraller through the ViewData to the view and use for loop to generate label, input and validation for each property, otherwise I have to write the following code many times:

	<div class="form-group">
		<label asp-for="Email" class="col-md-2 control-label"></label>
		<div class="col-md-10">
			<input asp-for="Email" class="form-control" />
			<span asp-validation-for="Email" class="text-danger"></span>
		</div>
	</div>
	
	<div class="form-group">
		<label asp-for="Name" class="col-md-2 control-label"></label>
		<div class="col-md-10">
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
	</div>

    // and so on.

**Comment by dougbu** [comment]
@huoshan12345 don't use tag helpers for this scenario. Instead use the `string`-based HTML helpers e.g.
```
    foreach (var item in columnNames)
    {
        <div class="form-group">
            @Html.Label(item, htmlAttributes: new { @class="col-md-2 control-label" })
            <div class="col-md-3">
                @Html.TextBox(item, value: null, htmlAttributes: new { @class="form-control" })
                @Html.ValidationMessage(item, htmlAttributes: new { @class="text-danger" })
            </div>
        </div>
    }
```

**Comment by huoshan12345** [comment]
@dougbu 
Thanks.  I got it.
