### ISSUE TITLE
FormatFilter overrides content type set explicitly by the developer

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#3762]
If the user sent a request with url like `api/values.json` and the developer set a content-type as `application/xml` on ObjectResult, I would have expected the one set by the developer to picked as he is explicitly setting the content-type.

**Expected**: application/xml
**Actual**: application/json

@rynowak

**Comment by Eilon** [comment]
Please confirm with @rynowak that this is a bug, but it certainly sounds broken to me.

**Comment by kichalla** [comment]
7a955bcbc09d34a4096ba20ca4248eebdc0b9df3
