### ISSUE TITLE
Fix format filter functional tests to include accept header

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#3763]
Currently the following tests do not send an accept header when making a request. This is an important criteria to add (i.e since users do not have a way to modify headers when browser makes a request, they user request url extension but the browser sends the accepts headers always). We need to verify if we still honor the url mapping if a valid accept header is provided.

https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.FunctionalTests/FormatFilterSampleTest.cs#L54-L72

**Comment by dougbu** [comment]
@kichalla how often are controllers using URL mappings invoked from a browser? Seems like a fairly `curl`ish thing to do.

If we need functional tests involving clients sending an `Accept` header to services using a format filter, suggest they should be added and not replacements for existing tests.

More importantly we should not add less-common scenarios to a _sample_. Whichever we think is less mainstream should be tested using the `FiltersWebSite` or `FormatterWebSite` instead.

**Comment by Eilon** [comment]
I would think that URL mapping are reasonably common from a browser, because that's one of the few cases where there isn't any other way to control the content type. With CURL, XHR, HttpClient, etc. there are ways to set headers, but from the browser address bar there isn't.

**Comment by Eilon** [comment]
Anyway, either way I don't think it's worth updating a whole lot of tests. If we have just one or two tests for this case (with an actual typical browser Accept header) then I'd say we're good to go.

**Comment by kichalla** [comment]
f888ced1f22532dd7bb998690afb15cb2b02dc37
