### ISSUE TITLE
HttpPost route receive 404 Not Found on Azure

### ISSUE THREAD

**Issue by itsfelipesan** [aspnet/Mvc#3769]
I have a WebApp on Azure, but any HttpPost route receive 404 Not Found.

All the HttpGet routes work fine, but all the HttpPost routes don't work.

This happens only on Azure, that is, in the localhost the HttpPost route works normally.

Here is an example:

    [Route("contact")]
    public class ContactController : Controller
    {
        private IContactMessageRepository _contact;
        private ILogService _log;
        public ContactController(IContactMessageRepository contact, ILogService log)
        {
            _contact = contact;
            _log = log;
        }

        
        [HttpPost("send")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SendMessage(ContactMessageViewModel model)
        {

        }
     }

...azurewebsites.net/contact/send -> NOT FOUND
   localhost/contact/send                -> WORKS FINE

I'm trying to POST throught ajax.

I have already enable CORS.

**Comment by Eilon** [comment]
What if you remove the `ValidateAntiForgeryToken`?

**Comment by Eilon** [comment]
@javiercn can you try to repro this in Azure?

**Comment by javiercn** [comment]
@itsfelipesan can you please provide us the following information to help investigate the bug?
Target framework (CLR, Core CLR)
Version of the MVC package used (Beta8, RC1)

Stack trace/logs/response from the server.
Stack trace/logs of the Console Developer Tools in the browser.
.
Is it CORS enabled on Azure Websites?
jQuery code used to do the post request?
Startup code used to configure CORS?

I was able to successfully create two apps, upload them to azure websites, send a cross domain request and get the response.
