### ISSUE TITLE
How do you return dynamically generated javascript?

### ISSUE THREAD

**Issue by Fosol** [aspnet/Mvc#3778]
I've tried a few different things and the result is annoyingly the same.  Mvc keeps deciding I'm returning "text/plain" regardless of what I set the Response ContentType.

How can I create an endpoint that returns javascript?

**Comment by pranavkm** [comment]
`public IActionResult Index() => Content("{ hello: 'world' }", contentType: "application/json")`

**Comment by kichalla** [comment]
:+1: on what @pranavkm mentioned. You should use action results whenever possible as they make unit testing easy.

**Comment by Fosol** [comment]
Just created a custom JavascriptResult.  Not sure how custom OutputFormatters play into that?

**Comment by kichalla** [comment]
Output formatters come into picture only when the result type is `ObjectResult` or JsonResult... ObjectResult runs the content-negotiation process when executing.
