### ISSUE TITLE
Object declared type not being passed to Json output formatter

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#3782]
While working on a solution for the following SO question, I noticed that we are not giving information about the 'declared type' to the JsonOutputFormatter.
http://stackoverflow.com/questions/34326013/how-to-specify-polymorphic-type-in-asp-net-mvc-6

Code of interest (There is an overload here which takes in a parameter for 'object type'): https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Formatters.Json/JsonOutputFormatter.cs#L81

Also currently its not simple to supply this information on `JsonResult`, should we expose a property to enable users to supply the declared type explicitly? (the obvious workaround is to use ObjectResult)

**Comment by rynowak** [comment]
We really really really really strongly discourage serializing a 'type' in JSON. A client can use HTTP to 'new' up any CLR type.

**Comment by Eilon** [comment]
@rynowak so by-design on this? But one thing I'm confused on is that the SO question was about deserialization, yet the code of interest is about serialization...

**Comment by rynowak** [comment]
By design IMO. I don't think we're giving up anything valuable here.

**Comment by kichalla** [comment]
@Eilon just fyi...more detailed example: 

**Server:**
```
public BaseClass GetInfo()
{
   return new Foo() { } 
   OR 
   return new Bar() { }
}
```
**Client:**
`jsonSerializer.Deserialize<BaseClass>(jsonReader)` ...this should create an instance of `Foo` or `Bar`...i think the user is saying that without the type info in the serialized data, the deserialization would create an instance of `BaseClass` instead

**Comment by Eilon** [comment]
I long liked using `obj.GetType()` to determine what to serialize, but I think the world is against people like me. And maybe people like you :smile: 

However, to many people the signature is a contract, and only aspects of that contract can be present. Anything not in the contract is a violation. If you said you're returning a `BaseClass` then only *those* properties may be present - nothing more.
