### ISSUE TITLE
Anchor tag helper not working when angular binding

### ISSUE THREAD

**Issue by jaganjan** [aspnet/Mvc#3789]
what is the proplem
``<div class="browse-movie-wrap col-lg-2 col-md-2 col-sm-3 col-xs-6" ng-repeat="movie in movies | filter:{IsPublished:true}">``

 ``{{ movie.Id }}  it works expected ``

``<a asp-controller="Movie" asp-action="MovieDetail" asp-route-movieId="{{ movie.Id }}"  > ``
``Is not worked ..``

``</div>``

Generate Html element

``<div class="browse-movie-wrap col-lg-2 col-md-2 col-sm-3 col-xs-6 ng-binding ng-scope" ng-repeat="movie in movies | filter:{IsPublished:true}">``
           
``228  //id is binded``

 ``<a class="browse-movie-link" href="/Movie/MovieDetail?movieId=%7B%7B%20movie.Id%20%7D%7D"> ``

``//but not binded anchor tag helper``
 
 my entire page data binding is works expected ,but when i use anchor tag helper its not working.
 
 
 any suggestion for this

**Comment by jaganjan** [comment]
stackoverflow thread http://stackoverflow.com/questions/34353425/anchor-tag-helper-not-working-in-mvc-6-and-angular-js

**Comment by jaganjan** [comment]
angular is marked issue on MVC Side https://github.com/angular/angular.js/issues/13582#event-495744974

**Comment by MaximRouiller** [comment]
Here's what you are doing.

You are sending [tag:angularjs] code to ASP.NET. Do you see the issue? You're telling ASP.NET:

> My movie ID is `{{ movie.Id }}`

So ASP.NET takes `{{ movie.Id }}` and encodes it into your URL.

You're using client-side code in a server side concept.

**Comment by jaganjan** [comment]
So what is the solution.

**Comment by jaganjan** [comment]
Which way to overcome to this issue. I was wondering to say this is a bug.

**Comment by MaximRouiller** [comment]
This is not a bug. It's a misunderstanding in usage. I'll now answer on the SO question only since this can be closed.

**Comment by jaganjan** [comment]
I moved to client side URL generation its OK for now ..
