### ISSUE TITLE
View compiled by Roslyn throws FileNotFound exception for dynamically loaded assembly

### ISSUE THREAD

**Issue by B-Esmaili** [aspnet/Mvc#3795]
I am trying to load my asp.net 5 application plugins dynamically in runtime.Everything works currectly but suddenly i ended up with a "type not found exception" inside RazorView when running application.after some search i found out that i can change the implementation of RoslynCompilationService.cs so that my dynamically loaded assemblies make count when compiling view.Now the problem is, the compiled View (which references my dynamically loaded assemblies) throws FileNotFoundException exception when i call GetExportedTypes() method on view type (see RoslynCompilationService.cs - line 150), which occurs because my dynamically compiled projects are not on disk and they are compiled on memory.so whats the solution? how can i tell rozlyn pick my dynamically loaded assemblies?

**Comment by davidfowl** [comment]
Views don't use loaded assemblies as references. We've added a new API in rc2 to allow adding reference assemblies to the razor compilation.

**Comment by pranavkm** [comment]
Here's the API @davidfowl is talking about - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/RazorViewEngineOptions.cs#L59

**Comment by B-Esmaili** [comment]
@davidfowl thanks for you'r info , but as a temporary workaround i create an `IAssemblyLoader`  implementation and that did the job.i'll wait for final release to make a decision about final change.

**Comment by Eilon** [comment]
@pranavkm @davidfowl I'm closing this because this appears to be resolved.
