### ISSUE TITLE
[HttpsRequired] causes loop http-> https ->http -> https etc on rc2 1.0.0-*

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Mvc#3798]
My startup url is https.
IN theory I should never drop down to http.
I start IIS express and navigate to HttpsRequired controller.  All works fine.

I update my project to rc2 using 1.0.0-* in project.son and dnvm update -u

Any controller with [RequireHttps] when hit loops between http and https until it gives up.
Basically I can't navigate to any controller with [HttpsRequired] attribute.

Can anyone else repo this?

**Comment by Eilon** [comment]
@pranavkm can you investigate?

**Comment by pranavkm** [comment]
Seems like a quirk of how the HttpPlatformHandler + Kestrel works. In Mvc, the protocol header shows up as http which causes us to redirect.
 
https://github.com/aspnet/KestrelHttpServer/issues/365 might be related. @halter73 would @mikes-gh  have to use `OverrideHeaderMiddleware` to get his app to be behave?

**Comment by mikes-gh** [comment]
This is local development using vs 2015 update 1 and IIS express on windows 7
rc1 works fine for same app.

**Comment by davidfowl** [comment]
@mikes-gh Did you try adding that middleware?

**Comment by rynowak** [comment]
Do we need to look at `IsSecure` in MVC rather than the scheme?

**Comment by davidfowl** [comment]
No, the scheme should be correct.

**Comment by mikes-gh** [comment]
Could you let me know how to add `OverrideHeaderMiddleware` to my code.  Is it a Startup.cs thing.

**Comment by davidfowl** [comment]
There's a sample here https://github.com/aspnet/BasicMiddleware/blob/dev/samples/HttpOverridesSample/Startup.cs

**Comment by mikes-gh** [comment]
Looking at this today.
Packages upgraded to 1.0.0-* 
Runtime 1.0.0-rc2-16357

However cant run project.

IIS express starts then shuts down.

Console shows below
Did some research but cant find out how to debug dnx to see what Ive done wrong.
'
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.Dnx.Host.Clr'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16357\bin\Microsoft.Dnx.Host.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16357\bin\Microsoft.Extensions.PlatformAbstractions.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16357\bin\Microsoft.Dnx.Loader.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16357\bin\Microsoft.Dnx.ApplicationHost.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16357\bin\Microsoft.Dnx.Runtime.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16357\bin\Microsoft.Dnx.Compilation.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16357\bin\Microsoft.Extensions.CompilationAbstractions.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\packages\Microsoft.AspNet.Server.Kestrel\1.0.0-rc2-16236\lib\dnx451\Microsoft.AspNet.Server.Kestrel.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\packages\Microsoft.AspNet.Hosting.Server.Abstractions\1.0.0-rc2-16161\lib\net451\Microsoft.AspNet.Hosting.Server.Abstractions.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\packages\Microsoft.AspNet.Http.Features\1.0.0-rc2-16106\lib\net451\Microsoft.AspNet.Http.Features.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\packages\Microsoft.Extensions.Configuration.Abstractions\1.0.0-rc2-15952\lib\net451\Microsoft.Extensions.Configuration.Abstractions.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\packages\Microsoft.Extensions.Logging.Abstractions\1.0.0-rc2-15958\lib\net451\Microsoft.Extensions.Logging.Abstractions.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\packages\System.Numerics.Vectors\4.1.1-rc2-23623\lib\portable-net45+win8\System.Numerics.Vectors.dll'. Cannot find or open the PDB file.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\packages\Microsoft.Extensions.Primitives\1.0.0-rc2-15967\lib\net451\Microsoft.Extensions.Primitives.dll'. Cannot find or open the PDB file.
The program '[6972] dnx.exe: Program Trace' has exited with code 0 (0x0).
The program '[6972] dnx.exe' has exited with code 1 (0x1).
The program '[4412] iisexpress.exe: Program Trace' has exited with code 0 (0x0).
The program '[10736] iexplore.exe' has exited with code -1 (0xffffffff).
The program '[4412] iisexpress.exe' has exited with code -1 (0xffffffff).
'

**Comment by mikes-gh** [comment]
OK so I spent some time on this today.  Once I got past the new hosting model (BTW Hosting:Environment in project properties no longer works) I tested again latest rc2 bits and latest clr.  clicking on the https link to account login.

Results

RC1 it works
RC2 I get the redirect loop as before.

```
0x800a139e - JavaScript runtime error: SyntaxError
Microsoft.AspNet.Hosting.Internal.WebApplication: Information: Request starting HTTP/1.1 GET http://localhost:44323/reports2/default/Account/Login  
Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker: Warning: Authorization failed for the request at filter 'Microsoft.AspNet.Mvc.RequireHttpsAttribute'.
Microsoft.AspNet.Mvc.RedirectResult: Information: Executing RedirectResult, redirecting to https://localhost:44323/reports2/default/Account/Login.
Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler: Information: Executed action Reports2.Controllers.AccountController.Login in 0.0015ms
Microsoft.AspNet.Hosting.Internal.WebApplication: Information: Request finished in 31ms 301 
Microsoft.AspNet.Hosting.Internal.WebApplication: Information: Request starting HTTP/1.1 GET http://localhost:44323/reports2/default/Account/Login  
Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker: Warning: Authorization failed for the request at filter 'Microsoft.AspNet.Mvc.RequireHttpsAttribute'.
Microsoft.AspNet.Mvc.RedirectResult: Information: Executing RedirectResult, redirecting to https://localhost:44323/reports2/default/Account/Login.
Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler: Information: Executed action Reports2.Controllers.AccountController.Login in 0ms
Microsoft.AspNet.Hosting.Internal.WebApplication: Information: Request finished in 15ms 301 
Microsoft.AspNet.Hosting.Internal.WebApplication: Information: Request starting HTTP/1.1 GET http://localhost:44323/reports2/default/Account/Login  
Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker: Warning: Authorization failed for the request at filter 'Microsoft.AspNet.Mvc.RequireHttpsAttribute'.
Microsoft.AspNet.Mvc.RedirectResult: Information: Executing RedirectResult, redirecting to https://localhost:44323/reports2/default/Account/Login.
Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler: Information: Executed action Reports2.Controllers.AccountController.Login in 0.0032ms
Microsoft.AspNet.Hosting.Internal.WebApplication: Information: Request finished in 32ms 301 
Microsoft.AspNet.Hosting.Internal.WebApplication: Information: Request starting HTTP/1.1 GET http://localhost:44323/reports2/default/Account/Login  
Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker: Warning: Authorization failed for the request at filter 'Microsoft.AspNet.Mvc.RequireHttpsAttribute'.
Microsoft.AspNet.Mvc.RedirectResult: Information: Executing RedirectResult, redirecting to https://localhost:44323/reports2/default/Account/Login.
Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler: Information: Executed action Reports2.Controllers.AccountController.Login in 0ms
Microsoft.AspNet.Hosting.Internal.WebApplication: Information: Request finished in 0ms 301 
```
and so on.


Now something very strange if I add the  OverrideHeaderMiddleware  as suggested

I get the following

```
Microsoft.AspNet.Hosting.Internal.WebApplication: Information: Request starting HTTP/1.1 GET http://localhost:44323/reports2/default/Account/Login  
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker: Information: Executing action method Reports2.Controllers.AccountController.Login with arguments () - ModelState is Valid'
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Collections.Concurrent\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Linq\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\mikes\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16357\bin\Microsoft.Dnx.Compilation.CSharp.Common.dll'. Cannot find or open the PDB file.
Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request
Microsoft.AspNet.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
/Views/Account/Login.cshtml(18,131): DNX,Version=v4.5.1 error CS0117: 'ValidationSummary' does not contain a definition for 'ValidationSummary'
   at Microsoft.AspNet.Mvc.Razor.Compilation.CompilationResult.EnsureSuccessful()
   at Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.CreateCacheEntry(String normalizedPath, Func`2 compile)
   at Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at Microsoft.AspNet.Mvc.Razor.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNet.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNet.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNet.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNet.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNet.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNet.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultFilterAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

and so on .
Hopefully this can point someone to what is happening.

**Comment by davidfowl** [comment]
Looks like a compilation error in your view. If you could push a sample to github showing the *running* application with the current error you're getting it would be great.

**Comment by mikes-gh** [comment]
OK but why is RC1 working?
The view is the one shipped with the asp.net starter project

```
@using System.Collections.Generic
@using Microsoft.AspNet.Http
@using Microsoft.AspNet.Http.Authentication
@model LoginViewModel
@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["Title"] = "Log in";
}

<h2>@ViewData["Title"].</h2>
<div class="row">
    <div class="col-md-8">
        <section>
            <form asp-controller="Account" asp-action="Login" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal" role="form">
                <h4>Use a local account to log in.</h4>
                <hr />
                <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Email" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            <input asp-for="RememberMe" />
                            <label asp-for="RememberMe"></label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-default">Log in</button>
                    </div>
                </div>
                <p>
                    <a asp-action="Register">Register as a new user?</a>
                </p>
                <p>
                    <a asp-action="ForgotPassword">Forgot your password?</a>
                </p>
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section>
            <h4>Use another service to log in.</h4>
            <hr />
            @{
                var loginProviders = SignInManager.GetExternalAuthenticationSchemes().ToList();
                if (loginProviders.Count == 0)
                {
                    <div>
                        <p>
                            There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkID=532715">this article</a>
                            for details on setting up this ASP.NET application to support logging in via external services.
                        </p>
                    </div>
                }
                else
                {
                    <form asp-controller="Account" asp-action="ExternalLogin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal" role="form">
                        <div>
                            <p>
                                @foreach (var provider in loginProviders)
                                {
                                    <button type="submit" class="btn btn-default" name="provider" value="@provider.AuthenticationScheme" title="Log in using your @provider.DisplayName account">@provider.AuthenticationScheme</button>
                                }
                            </p>
                        </div>
                    </form>
                }
            }
        </section>
    </div>
</div>

@section Scripts {
    @{ await Html.PartialAsync("_ValidationScriptsPartial"); }
}
```
I am pretty sure I haven't changed it at all.

**Comment by davidfowl** [comment]
Because between RC1 and RC2 changes were made. https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2. In particular, the one affecting you for the redirect is https://github.com/aspnet/Announcements/issues/123. As for the compilation error, I couldn't tell you off the top of my head without something that I could look at and debug.

**Comment by mikes-gh** [comment]
Wow I completely missed that announcements section that is great info.  I think I understand it now enough to debug.  If not I am pretty sure I can sort a working repro from the standard template.

**Comment by mikes-gh** [comment]
In the above view if I comment out

```
@*<div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>*@
```
 the view works.  I guess that's another issue all together? if so I'll close this as a known breaking change resolved by OverrideHeaderMiddleware.  Still not sure why that change was made but I'll endeavour to understand it through more research.

**Comment by mikes-gh** [comment]
And I fact

<div asp-validation-summary="@ValidationSummary.All" class="text-danger"></div>

not sure where this belongs (razor tag helpers identity)
Looks like tag helpers need @ on the enum
Would you open a case in the correct place and link here please.

**Comment by dougbu** [comment]
Change `asp-validation-summary="ValidationSummary.All"` to `asp-validation-summary="All"`. See aspnet/Announcements#96 for more information.

**Comment by mikes-gh** [comment]
Got it I see the templates have already changed  apologies for missing the announcements section.

Closed as known breaking changes
