### ISSUE TITLE
WebApi Documentation Generation

### ISSUE THREAD

**Issue by ahirmayur** [aspnet/Mvc#3802]
Hi everyone,

Is there any workaround or similar package to `Microsoft.AspNet.WebApi.HelpPage` which can automatically generate documentation for MVC 6/EF 7 projects?

I was following http://www.asp.net/web-api/overview/getting-started-with-aspnet-web-api/creating-api-help-pages for all previous MVC 5/EF 6 based projects.

Thanks in advance.

PS: I already tried adding `"Microsoft.AspNet.WebApi.HelpPage": "5.2.3"`, to the project and no luck.

**Comment by pranavkm** [comment]
cc @rynowak

**Comment by Eilon** [comment]
Yes! Check this out: https://github.com/domaindrivendev/Ahoy

It's not an exact substitute, but it's overall much more powerful, flexible, and generally better than the old Web API help page.
