### ISSUE TITLE
Consider supporting range requests, cache headers, head requests, with FileResult ActionResult

### ISSUE THREAD

**Issue by pauldotknopf** [aspnet/Mvc#3803]
The [StaticFileMiddleware](https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNet.StaticFiles/StaticFileMiddleware.cs) supports pretty much every scenario needed for serving up static files. I think it would be awesome to have feature parity between the middle-ware component and the `FileResult` action result.

**Comment by rynowak** [comment]
As of 2.0.0 we have done all of this!

**Comment by rynowak** [comment]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/FileResultExecutorBase.cs
