### ISSUE TITLE
Can't return absolute file paths with VirtualFileResult.

### ISSUE THREAD

**Issue by theonlylawislove** [aspnet/Mvc#3804]
```c#
public class ImageController : BaseController
{
    public ActionResult Image()
    {
        return File(@"C:\test.jpg", "image/jpeg");
    }
}
```
I get this.

> FileNotFoundException: Could not find file: C:\test.jpg

The file exists.

I suspect it is because ```VirtualFileResult``` uses the ```IHostingEnvironment.WebRootFileProvider``` by default.

This worked in previous versions of MVC.

**Comment by pranavkm** [comment]
You need `return PhysicalFile(@"C:\test.jpg", "image/jpeg");`. Like you mentioned,`File` \ `FileResult` uses the file system specified by `WebRootFileProvider`

**Comment by theonlylawislove** [comment]
Perfect!

**Comment by ferflores507** [comment]
Thank you very much
