### ISSUE TITLE
Make RazorViewEngineOptions.FileProvider a list instead of a single item

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3806]
See comment here: https://github.com/aspnet/Mvc/issues/3750#issuecomment-164474888

This has become a pretty common task for building anything modular. It would be nice if we just make `FileProvider` into a list so it was obvious that you can do this.

**Comment by pranavkm** [comment]
cc @lodejard

**Comment by pranavkm** [comment]
![follow-your-dreams](https://cloud.githubusercontent.com/assets/174281/11969389/d2f60aec-a8cd-11e5-8df7-e3cca9527d0b.gif)
