### ISSUE TITLE
TagHelperContext not contains GetChildContentAsync

### ISSUE THREAD

**Issue by blueskybcl** [aspnet/Mvc#3807]
code:
public class EmailAsyncTagHelper:TagHelper
    {
        private const string EmailDomain = "contoso.com";
        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            output.TagName = "a";    // Replaces <email> with <a> tag
            var content = await context.GetChildContentAsync();//tooltip GetChildContentAsync method not contain in TagHelperContext  class
            var target = content.GetContent() + "@" + EmailDomain;
            output.Attributes["href"] = "mailto:" + target;
            output.Content.SetContent(target);
        }
    }

source at https://github.com/blueskybcl/AuthoringTagHelpers
why?
please help me!

**Comment by NTaylorMullen** [comment]
It was moved to `TagHelperOutput`. See: https://github.com/aspnet/Announcements/issues/90

**Comment by blueskybcl** [comment]
@NTaylorMullen Thank you
