### ISSUE TITLE
Incorrect Content-Type: application/json;charset=UTF-8

### ISSUE THREAD

**Issue by B-Esmaili** [aspnet/Mvc#3809]
I have a view with angular `$http.post` method to save data in server , but when i click save button i end up with an `Incorrect Content-Type: application/json;charset=UTF-8` message. i toke a look at `FormFeature.cs` class but couldn't find something related to json parsing, do it means `content-type:application/json` hasn't been implemented ?

**Comment by rynowak** [comment]
You're going to have to provider more information.. a link to repo (or sample controller/model code) and a description of what you're trying to accomplish would let us help you. 

My guess from the error message is that you're trying to access the `request.Form` property for a json request, which won't work. If you're trying to read the body as JSON, then write a model class and use `[FromBody]` like this

```
public void MyAction([FromBody] MyModel model)
{
}
```

**Comment by B-Esmaili** [comment]
@rynowak  yes you guessed it right and you'r workaround solved my problem. tkanks!
