### ISSUE TITLE
Http Error 500 Using If in razor view

### ISSUE THREAD

**Issue by Eneuman** [aspnet/Mvc#3810]
Using the following line of code in a MVC 6 razor view generates a Server Error 500, why ?
I have double checked the model and it works fine, The problem only occurs when I add the if statement.
The code is working fine in MVC5.

```
<div class="form-group" style="@if (Model.Id=="") {<Text>display:none;</Text>}">
</div>

**Comment by Eneuman** [comment]
Doing a bit more of testing and the following code also works:

```
<div class="form-group" style="@(Model.UniktId=="" ? "display:none" : "")">
</div>

**Comment by rynowak** [comment]
If you add the developer exception page, you should be able to see the exception message.
https://github.com/aspnet/Diagnostics/blob/dev/samples/DeveloperExceptionPageSample/Startup.cs#L11

**Comment by Eneuman** [comment]
Yeah, that's what's strange.
I have it enabled, still only getting the HTTP 500 error crash without any more info.

**Comment by rynowak** [comment]
Is your environment set to `Development`? Are you launching from VS or from the console? If console, set `ASPNET_ENV=Development`

**Comment by Eneuman** [comment]
Launching from VS and have the ASPNET_ENV=Development .
However, when I started a new ASP 5 Web project and added the following code to the Index.cshtml page:

<div class="form-group" style="@if (ViewBag["Id"]=="") {<Text>display:none;</Text>}">
  Hide Me
</div>

The following error occurred:
Not all code paths return a value in lambda expression of type 'Func<TextWriter, Task>'

See attached screen shoot
![image](https://cloud.githubusercontent.com/assets/12099277/12022553/1dd63df8-ad91-11e5-8c9e-c22830d51230.png)

**Comment by pranavkm** [comment]
Can you list your project.json and perhaps a screenshot of the References node in vs expanded to list the versions of Mvc and Razor being used? The lambda generated as parameter to `WriteAttributeValue` should be async as of beta8 (this would be the Razor issue tracking the change - https://github.com/aspnet/Razor/issues/494).

**Comment by Eneuman** [comment]
Sure thing:

{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}
![image](https://cloud.githubusercontent.com/assets/12099277/12023804/87947d5c-ad9d-11e5-8943-08dd13e8432a.png)

**Comment by Eneuman** [comment]
Here is an example project, showing the problem.
Just run the app and it will show the error.
[BugHunt.zip](https://github.com/aspnet/Mvc/files/73462/BugHunt.zip)

**Comment by NTaylorMullen** [comment]
Duplicate of: https://github.com/aspnet/Razor/issues/594

Is fixed for next release :smile:

**Comment by Eneuman** [comment]
Nice :)

**Comment by VSG24** [comment]
I also face this. So annoying but at least ternary syntax works for now.
