### ISSUE TITLE
AreaAttribute - Doesn't work as expected

### ISSUE THREAD

**Issue by Fosol** [aspnet/Mvc#3812]
The basic behavioural flow of using the RouteAttribute on a Controller implementation results in all actions within the controller that don't start with a forward slash to inherit the controller's route template.  This is true even when you don't include your own RouteAttribute on the Controller.

This convention doesn't work with the AreaAttribute however.  The only way I have been able to get the various RouteAttributes (i.e. HttpGet) to include the area is to add the keyword "[area]" within the action's route template.  This results in the loss of conventional and expected behaviour.  I can no longer apply a global route change to a controller through the top template.

Am I doing something incorrect?  Or is this just a 'feature'?

**Comment by Fosol** [comment]
Ummm... Not sure what's going on but after a few builds this behaviour started working correctly.  I haven't changed anything that I can see that would have caused this though...  I'll close this for now unless I see it occurring again.

**Comment by rynowak** [comment]
If you can post a link to some code I can take a look. 

> Am I doing something incorrect? Or is this just a 'feature'?

It's intended that attributes work like you typed them. There's no magic here besides substitution of tokens like `[area]`
