### ISSUE TITLE
Improve culture behavior for model binding

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#3819]
From https://github.com/aspnet/Mvc/issues/3629

From @rynowak:

> We should also add a `protected set` `CultureInfo` property to all of our VPFs so that scenarios like [this one](https://github.com/aspnet/Routing/issues/237) are easier to address.

And from me:

> For the culture issue, I'm not sure that's the right solution to the problem. I think the scenario (including the specific linked scenario) is that *one* particular property on *one* particular type (or *one* particular action parameter) needs to have some particular culture rule.
>
> I was instead imagining some kind of model-binding attribute like `[ModelBindCultureBehavior(ModelBindingCultureBehavior.CurrentCulture)]` (or pass in `.InvariantCulture`, or even pass in a string name of a culture, e.g. `en-US`). And model binding would see these and then flow it through to wherever it needed to, such as value providers, and Do The Right Thing<sup>:tm:</sup>.

**Comment by rynowak** [comment]
If you do what I suggested, then it's possible to do what you suggest in a resource filter. (That's why I suggested it...)

**Comment by Eilon** [comment]
This would be a per-property setting, though - not a per-request setting. How would a resource filter affect the model binding culture of one specific property/parameter?

**Comment by rynowak** [comment]
yeah, you're right, that would be per-request. I just want to avoid having another model binding concept.

**Comment by Eilon** [comment]
Yeah this is a very low priority feature.

**Comment by danroth27** [comment]
Closing - we can revisit this based on customer feedback.
