### ISSUE TITLE
HttpStatusCodeResult return description along with code?

### ISSUE THREAD

**Issue by muratg** [aspnet/Mvc#3820]
_From @a11smiles on December 23, 2015 19:54_

In .Net < 5, there was an overloaded constructor that allowed us to create an HttpStatusCodeResult with status code and a description.

Apparently, in .Net 5, I can no longer add a description?

Should we be using an alternative result type (i.e. ObjectResult or ContentResult)?

Please advise.

_Copied from original issue: aspnet/dnx#3283_

**Comment by muratg** [comment]
_From @davidfowl on December 24, 2015 12:9_

This is an MVC question ask on that repository.

**Comment by rynowak** [comment]
We don't recommend using status description/reason phrase  https://github.com/aspnet/HttpAbstractions/issues/395#issuecomment-139328869.

**Comment by Eilon** [comment]
Also dup of https://github.com/aspnet/Mvc/issues/3455.
