### ISSUE TITLE
Discussion: Updating MVC's dependency on JSON.NET

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3827]
This is the discussion thread for aspnet/Announcements#134

---

As of **RC2** MVC's dependency on JSON.NET has been upgraded to version 8.0.1

Not only is ASP.NET 5 / MVC 6 a good opportunity to upgrade our minimum version, we've made significant performance investments that require a new build. Big thanks to @jamesnk, @sokket, and @KrzysztofCwalina for their help in putting this together.

@jamesnk has blogged about the release here: http://james.newtonking.com/

We don't expect any surprises from the upgrade. If you encounter any problems or surprises, let us know.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
