### ISSUE TITLE
Ensure view compilation inherits the right settings from the project's compilation settings

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#3831]
From @cesarbs in https://github.com/aspnet/Razor/issues/598:

If you strong name a web app, Razor fails to compile pages:

    An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

    /Views/Home/Index.cshtml

    Error signing output with public key from file 'C:\Users\cesars\Documents\Visual Studio 2015\Projects\RC1StrongNameValidation\src\RC1StrongNameValidation\Key.snk' -- Assembly signing not supported.

Apparently this happens because no strong name provider is being set for Roslyn (see https://github.com/dotnet/roslyn/issues/4953 and https://github.com/aspnet/dnx/blob/1bb5a1d24fcd7d21d2278528c243e2b9f181c43d/src/Microsoft.Dnx.Compilation.CSharp/RoslynCompiler.cs#L205).

**Comment by Eilon** [comment]
@pranavkm parking this on your plate, though I'm not sure how actionable this issue is right now.

@davidfowl can this be done already for CLI?

**Comment by pranavkm** [comment]
This is likely to be covered by https://github.com/aspnet/Mvc/issues/3633

**Comment by Eilon** [comment]
Ah, ok, let's hold onto this bug anyway to ensure the scenario is covered after the full switch.

**Comment by pranavkm** [comment]
We switched over to the CLI in https://github.com/aspnet/Mvc/commit/80b6996701ca240b8b4b1ba8f56c7ecae3e69b60 and haven't seen issues with this feature.
