### ISSUE TITLE
Relative path in appsettings.json

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Mvc#3832]
There's never a clear way where to put sqlite database file securely, should we put it under wwwroot or application file path? How to specifies it on appsettings.json?

appsettings.json
```
{
  "Data": {
    "DefaultConnection": {
      "ConnectionString": "Data Source=data.db3;"
    }
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Verbose",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```

Run these 2 commands via command prompt
```
dnx ef migrations add initial
dnx ef database update
```

This will produce data.db3 inside application path (This one contains asp.net identity table)
![image](https://cloud.githubusercontent.com/assets/12871379/12049702/18f1068c-aeeb-11e5-91fb-e0ef5be0a3c1.png)

BUT, when we call

```
 var result=await _userManager.CreateAsync(new ApplicationUser()
            {
                UserName = username,
                Email = email
            }, password);
```

It is somehow expect the file under wwwroot and creating empty data.db3
![image](https://cloud.githubusercontent.com/assets/12871379/12049720/4748a224-aeeb-11e5-8136-e73ce285d616.png)

which makes creating user fails due its empty

If we have something like 
```
{
  "Data": {
    "DefaultConnection": {
      "ConnectionString": "Data Source=|DataDirectory|\\data.db3;"
    }
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Verbose",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```
there should be no confusion for the runtime on where to look for the file

**Comment by pranavkm** [comment]
This looks like it belong in https://github.com/aspnet/EntityFramework/

**Comment by Eilon** [comment]
Indeed, please log this in https://github.com/aspnet/EntityFramework/.

I should add that it is absolutely never a good idea to store the database in `wwwroot` - that folder is reserved exclusively for serving *public* static content, such as JS/CSS/HTML files. You must never put secret data in there (such as a database).

The database can go just about anywhere else, such as in the app root, but definitely never in `wwwroot`.

@divega FYI in case you already have seen this or have thoughts on this.
