### ISSUE TITLE
Get rid of 'long form' dispose on MvcForm

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3834]
MvcForm has the 'long form' dispose implementation that's only really needed if you use native resources and need finalization. We can remove this.

I did a search and there are 3-4 other places that include `GC.SuppressFinalize` include (gasp) Controller and ApiController. None of these have finalizers.

**Comment by Eilon** [comment]
In general get rid of all the calls to SuppressFinalize, and in MvcForm completely remove the fancy long-form dispose and keep a simple dispose.
