### ISSUE TITLE
Consider an opt-out for IFilter on `Controller`

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#384]
Now that our base class for `Controller` implements `IActionFilter` you have no way to short circuit the pipeline for perf reasons with this class. We saw serious perf gains in webapi from short-circuiting when no filters were in use.

Consider adding an opt out in a few ways:
 - `IgnoreFiltersAttribute` - says that a controller/action doesn't use filters
 - `IAmNotAFilter` marker interface - says that a controller doesn't use the `IActionFilter` extensibility point
 - Removable `FilterProvider` which handles the controller-related part

**Comment by yishaigalatzer** [comment]
@Eilon that's a neat idea.

Other suggestions - With the new application model, you can just write a `ControllerConvention` to turn it off, or decorate the built in methods with a non inheritable attribute.

**Comment by rynowak** [comment]
> Other suggestions - With the new application model, you can just write a ControllerConvention to turn it off, or decorate the built in methods with a non inheritable attribute.

Currently, the discovery of whether or not the controller is-a filter takes place inside `DefaultFilterProvider`, so the decision of whether or not the controller is-a filter is not is **not** configurable via application model. 

We could change this by having the ADP do the detection and add a 'Controller Filter' which is an `IFilterFactory` that just returns the controller instance. (Or the 'Controller Filter' is a delegating instance of particular filter types - this would address some of the ordering concerns we've been discussing). The indirection is needed obviously because the controller has not yet been constructed during the ADP phase.

This would have the benefit of moving something hardcoded down into the metadata layer, rather than a built-in behavior of a service. If we make this change, we should consider also whether the signature of the `IFilterFactory` gets access to the `ActionContext`. Right now it just gets services.

**Comment by rynowak** [comment]
We're doing this now as part of the redesign of when the controller factory runs.

**Comment by rynowak** [comment]
e1069dbf65182e5f13ba6ee863711b61521a2b81
