### ISSUE TITLE
DataAnnotations Metadata Not Loaded in View

### ISSUE THREAD

**Issue by rmhw** [aspnet/Mvc#3840]
I have a large module of autogenerated EF code which I periodically regenerate and which is compiled against .NET 4.5. Manually adding to classes within this module is undesirable, as they will be lost on regeneration.

Consequently, I'm trying to add data annotations using a metadata class - for example:

```c#
public partial class Thing // Autogenerated
{
    public int Id { get; set; }
}

[MetadataType(typeof(ThingMetadata)]
public partial class Thing // Manual
{
}

public class ThingMetadata
{
    [Display(Name = "Unique Identifier")]
    public int Id { get; set; }
}
```

I then reference this class from an ASP.NET MVC6 web application, and utilise my class as the model for a view.

However, the data annotation is ignored by the view engine.

If I then move my data annotation into the autogenerated class, the view engine respects the annotation.

Is this a bug, or am I missing something needed to pull these metadata annotations into the view layer as they used to work with MVC4 etc?

**Comment by Eilon** [comment]
@rmhw there is support in MVC 6 for "buddy metadata types" but it's using a new attribute, `ModelMetadataTypeAttribute`. The behavior is the same as the old attribute, so the usage is the same.

So, you'd do this:

```c#
[ModelMetadataType(typeof(ThingMetadata)]
public partial class Thing // Manual
{
}
```

The reason for the new attribute is that the old attribute doesn't exist in .NET Core, so MVC created its own attribute that is available everywhere.

Note: You might want to specify *both* attributes if the model needs to be compatible with both MVC 6 as well as other frameworks.

**Comment by rmhw** [comment]
Thanks @Eilon - I'll give it a whirl.
