### ISSUE TITLE
[FromBody] resolves NULL when using POST in a Web API controller

### ISSUE THREAD

**Issue by maxmantz** [aspnet/Mvc#3841]
This applies to version `1.0.0-rc2-16770` used with dnx clr `1.0.0-rc2-16357 x86` on Windows 10.
When using POST on a controller, the value after the `[FromBody]` tag gets resolved as `null`.
Tried hosting with Kestrel and WebListener. Both had the same effect.

**Comment by davidfowl** [comment]
@maxmantz Can you provide a complete sample? A github repo would be awesome.

**Comment by maxmantz** [comment]
@davidfowl Of course, [here](https://github.com/maxmantz/MvcPostBug) is my repo.

**Comment by davidfowl** [comment]
How are you posting to the controller?

**Comment by maxmantz** [comment]
@davidfowl I have made an error with the view model and it works fine. The issue is not with MVC but with my usage of it, so my apologies.

**Comment by davidfowl** [comment]
No problem
