### ISSUE TITLE
Cannot get IViewLocalizer or IHtmlLocalizer with .resx working, rc1-final

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Mvc#3846]
Please see the reference project here: https://github.com/kspearrin/LocTest

Using rc1-final I cannot seem to get localization working in my views.

Startup.cs

```
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Localization;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace LocTest
{
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            // Set up configuration sources.
            var builder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; set; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services
                .AddMvc()
                .AddViewLocalization(options => options.ResourcesPath = "Resources")
                .AddDataAnnotationsLocalization();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            RequestLocalizationOptions rlOptions = new RequestLocalizationOptions
            {
                SupportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("es-ES")
                },
                SupportedUICultures = new List<CultureInfo>
                {
                    new CultureInfo("es-ES")
                }
            };

            app.UseRequestLocalization(rlOptions, new RequestCulture("en-US"));

            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            if(env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseIISPlatformHandler();

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }

        // Entry point for the application.
        public static void Main(string[] args) => WebApplication.Run<Startup>(args);
    }
}
```

I have a resource file in `/Resources/Views.Home.Index.cshtml.es-ES.resx` with `Hello => Hola`.

I have a `/Views/Home/Index.cshtml` with a `@inject IViewLocalizer LocString` and 

```
@LocString["Hello"]<br />
@DateTime.UtcNow.ToString("g")<br />
```

I switch the cultures via query string: `?culture=es-ES&ui-culture=es-ES`.

I can see the date time on the page, but the hello string does not.

Also, I cannot seem to inject `IHtmlLocalizer` into my controller. I get errors that it is not available in the DI container.

```
    public class HomeController : Controller
    {
        private readonly IHtmlLocalizer _localizer;

        public HomeController(IHtmlLocalizer localizer)
        {
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["HelloString"] = _localizer["Hello"];

            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
```

> InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNet.Mvc.Localization.IHtmlLocalizer' while attempting to activate 'LocTest.Controllers.HomeController'.

What am I doing wrong?

**Comment by Eilon** [comment]
@DamianEdwards ?

**Comment by nitzul** [comment]
bump

**Comment by pranavkm** [comment]
also cc @ryanbrandenburg

**Comment by ryanbrandenburg** [comment]
Some clarification here @kspearrin , when you say the hello string does not, do you mean NOTHING shows there or that you get hello instead of hola?

Also, sort of preemptively because a lot of localization issues are affected by this, please double check that your problem still happens if you run the site from dnx command line instead of VS. If it doesn't repro under DNX then you've run into https://github.com/aspnet/dnx/issues/3047

In the mean time I'll look through your sample and see if I can't locate the source of your DI woes.

**Comment by kspearrin** [comment]
@ryanbrandenburg I mean it always prints "Hello"

**Comment by kspearrin** [comment]
@ryanbrandenburg I just tested this by launching the website via the `web` command (accessing from localhost:5000), rather than the normal `IISExpress` in VS and experience the same issue. Is this what you were referring to?

**Comment by kspearrin** [comment]
@ryanbrandenburg And finally, if I run the site via `dnx web` from the command line, the "Hello" string does not even appear at all. Neither does the formatted `DateTime` string in my example. This seems to be a different issue than any of the other scenarios I have tried from within VS.

**Comment by DamianEdwards** [comment]
I just cloned the app and it all worked perfectly fine for me if I run from the command line (`dnx web`). I tried it with both full CLR and Core CLR.

(Note, I added the "Home Page" heading)

![image](https://cloud.githubusercontent.com/assets/249088/12124623/3f407bc4-b39b-11e5-8a0d-6f6d1e420edc.png)

**Comment by DamianEdwards** [comment]
@kspearrin not seeing anything at all when you run from the command line is due to there not being any minified CSS files. Make sure to run `gulp min` first, or switch to development environment by setting environment variable `ASPNET_ENV` to "Development" so it loads non-minified files.

**Comment by kspearrin** [comment]
@DamianEdwards Ah whoops. Fixed that and it shows "Hola"properly now using `dnx web`. So I guess this means it's back to the problem that @ryanbrandenburg originally brought up with aspnet/dnx#3047 ? Is this an issue outside of running the app in VS? When I deploy it to Azure for instance, will it work?

**Comment by DamianEdwards** [comment]
aspnet/dnx#3047 is not related. Your issue is that loading of resources doesn't work when running the app from Visual Studio. It will work from the cmd line and after you publish just fine.

**Comment by kspearrin** [comment]
> Your issue is that loading of resources doesn't work when running the app from Visual Studio.

Is that not a issue? I'm confused.

**Comment by Eilon** [comment]
@kspearrin it's a known bug that is being tracked separately. It will be fixed before RTM.

**Comment by Bibo1978** [comment]
it works only if you add a class in resources file without any implementation and name the resource file with the full namespace for than new class then use the generic version of IHtmlLocalizer<HomeControllerResources> if you named the class HomeControllerResources

**Comment by follesoe** [comment]
I know this is an old closed issue, but it's the one that best describes my issue. I can't get `IViewLocalizer` to return localized values when running from command line on a mac. Same project hosted in Azure works just fine.

When printing the culture in the `Index` action I can verify it is set through the query string:

```csharp
public IActionResult Index()
{
    _logger.LogInformation($"Current UI Culture: {CultureInfo.CurrentUICulture.Name} - Host: {Request.Host.Host}");
    return View();
}
```

The localization configure is as follow:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    // Add framework services.
    services.AddLocalization(options => options.ResourcesPath = "Resources");
    services.AddMvc().AddViewLocalization(options => options.ResourcesPath = "Resources");
}

// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole(Configuration.GetSection("Logging"));
    loggerFactory.AddDebug();

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseBrowserLink();
    }
    else
    {
        app.UseExceptionHandler("/Home/Error");
    }

    app.UseStaticFiles();

    var supportedCultures = new List<CultureInfo> {
        new CultureInfo("en-US"),
        new CultureInfo("nb-NO")
    };

    var localizationOptions = new RequestLocalizationOptions {
        DefaultRequestCulture = new RequestCulture("en-US"),
        SupportedCultures = supportedCultures,
        SupportedUICultures = supportedCultures
    };

    localizationOptions.RequestCultureProviders.Clear();
    localizationOptions.RequestCultureProviders.Add(new QueryStringRequestCultureProvider());
    app.UseRequestLocalization(localizationOptions);

    app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "{controller=Home}/{action=Index}/{id?}");
    });
}
```

The resource file is named `Views.Home.Index.nb-NO.resx` and used in the `Index.cshtml` of the default ASP.NET MVC project (`dotnet new mvc`).

Target framework: `<TargetFramework>netcoreapp1.1</TargetFramework>`.

Printing a localized value like this `<h1>@Localizer["Hello World"]</h1>` only display the default value.

**Comment by Eilon** [comment]
@follesoe sorry for the delay responding to you - we rarely check back on old closed issues. Can you log a new issue w/ this info so we can investigate?
