### ISSUE TITLE
IViewComponentHelper InvokeAsync changes

### ISSUE THREAD

**Issue by christiannagel** [aspnet/Mvc#3848]
How should I invoke the new version of the InvokeAsync method of the IViewComponentHelper?

The IViewComponentHelper.InvokeAsync changed from

```c#
Task<IHtmlContent> InvokeAsync(string name, params object[] arguments);
```

to

```c#
Task<IHtmlContent> InvokeAsync(string name, object arguments);
```

Now I tried to invoke the new version with 

```c#
@await Component.InvokeAsync("EventList", new object[] { new DateTime(2016, 4, 10), new DateTime(2016, 4, 24) })
```

Inside my view component, the method InvokeAsync is called, but the parameters are initialized to the default values:

```c#
public Task<IViewComponentResult> InvokeAsync(DateTime from, DateTime to) =>
            Task.FromResult<IViewComponentResult>(View(EventsByDateRange(from, to)));
```

Thanks,
Christian

**Comment by pranavkm** [comment]
@christiannagel, the second argument needs to be either a dictionary of parameter names and values or an anonymous  object with property names that map to arguemnt names. In your case, this would be

`@await Component.InvokeAsync("EventList", new { to = new DateTime(2016, 4, 10), from = new DateTime(2016, 4, 24) })`

or 
```
var arguments = new Dictionary<string, object>
{
     ["to"] = new DateTime(2016, 4, 10),
     ["from"] = new DateTime(2016, 4, 24)
};

@await Component.InvokeAsync("EventList", arguments);
```

**Comment by christiannagel** [comment]
Many thanks for the answer!
