### ISSUE TITLE
Add doc comments for filter attributes (e.g. RequireHttpsAttribute)

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#3851]
[RequireHttpsAttribute](https://github.com/aspnet/Mvc/blob/43226fe54de140db30746336f3d46130be47c0e4/src/Microsoft.AspNet.Mvc.Core/RequireHttpsAttribute.cs) is definitely missing it. Not sure about other attributes.

**Comment by dougbu** [comment]
eda647e into `release`
Also merged into `dev`
