### ISSUE TITLE
MVC tag helpers are inconsistent about initially `Clear()`ing content

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3852]
Moving an issue mentioned in aspnet/Razor#621 over.

> There's also a bug in how MVC uses `SetContent()`: Those tag helpers currently _assume_ `Content` is empty but should be clearing what other tag helpers have done.

MVC tag helpers that change `Content`, `PostContent` or `PostElement` currently fall into two groups. These groups should be brought together as much as possible, consistently handling tag helpers that run earlier.
1. Some e.g. `FormTagHelper`, `InputTagHelper`, `RenderAtEndOfFormTagHelper`, and `ValidationSummaryTagHelper` initially append. A couple (`LabelTagHelper` and `ValidationMessageTagHelper`) check `output.IsContentModified` before calling `content.SetContent()`, which also takes previous tag helpers into account (here, giving tag helpers that run before them complete control of the content).
2. Others e.g. `LinkTagHelper`, `ScriptTagHelper` and `TextAreaTagHelper` start with a call to `content.SetContent()` to implicitly reset that content. A couple (`CacheTagHelper` and `EnvironmentTagHelper`) explicitly call `output.SuppressOutput()` to reset _all_ output content.

Despite my words in aspnet/Razor#621, my suggestion is to remove all use of `SetContent()` in MVC tag helpers. `CacheTagHelper` and `EnvironmentTagHelper` are likely special cases (because they do not target HTML 5 elements) but Group 1 seems like the winner. (Other options include using `SetContent()` everywhere or consistently using `SetContent()` for `output.Content` and `Append[Html]()` for other `TagHelperOutput` properties.)

/cc @DamianEdwards 

Side notes:
1. No MVC tag helpers append to a `TagHelperOutput` property more than once. But `LinkTagHelper` and `ScrpitTagHelper` have a useless `DefaultTagHelperContent` that both always add to `PostElement`. Should instead use `PostElement` throughout.
2. Can ignore MVC tag helpers e.g. `UrlResolutionTagHelper` that only change attributes.
3. No MVC tag helpers change `PreContent` or `PreElement`.
4. No MVC tag helpers directly call `content.Clear()`.

**Comment by Eilon** [comment]
Moving to backlog. Not clear that there are any actual bugs at this time.

**Comment by rynowak** [comment]
If there is no actual problem can we just close this?

**Comment by DamianEdwards** [comment]
Would seem so.

**Comment by dougbu** [comment]
The problems that would occur relate only to interaction between our tag helpers and others'. Without looking at our sources or experimenting (per-element), tag helper authors can't be sure how to `Order` theirs to get the `Content` needed.

**Comment by dougbu** [comment]
See #5713 for the `<textarea>` tag helper. Don't worry about losing the content of `<script>` elements when globbing.
