### ISSUE TITLE
Exception in JsonConverter results in "HTTP Error 502.3 - Bad Gateway" (no developer exception page shown)

### ISSUE THREAD

**Issue by bluemmc** [aspnet/Mvc#3856]
In most cases app.UseDeveloperExceptionPage() means that I get a nice page describing the exception in ASP.NET 5 RC1 but if I use services.AddMvc().AddJsonOption and add a json converter to options.SerializerSettings.Converters and that converter throws an exception, then I get a very different screen shown by IIS that bypasses everything else.

**Comment by Eilon** [comment]
@ryanbrandenburg can you try to repro this and see what's going on here?

**Comment by ryanbrandenburg** [comment]
Hey @bluemmc could you try this again and post a link to a repro project if it still happens? I tried to reproduce this from what you said here and it's either already been fixed or I'm missing an important part of the repro, because I get the standard developer exception page.

**Comment by Eilon** [comment]
@Tratcher any idea what could cause this error with HttpPlatformHandler? I think I've seen a few mentions of the gateway error here and there and wondering if there's a more general problem or error case that needs to be handled.

**Comment by Tratcher** [comment]
Is the error occurring part way through a response body? The developer exception page can only handle exceptions thrown before the response body starts.

**Comment by Eilon** [comment]
@Tratcher what can cause the bad gateway error?

**Comment by Tratcher** [comment]
Any communication failure with the back-end process. I'd be curious to see the repro.

**Comment by Eilon** [comment]
@Tratcher ok let's give it a couple days to see if we get a repro.

**Comment by rynowak** [comment]
> Is the error occurring part way through a response body? The developer exception page can only handle exceptions thrown before the response body starts.

I would expect this is the case since it's a JsonConverter that's throwing at runtime.

**Comment by bluemmc** [comment]
[Issue253.zip](https://github.com/aspnet/Mvc/files/100392/Issue253.zip)

This project reproduces the error. Run it and hit "api/values" and you will get "HTTP Error 502.3 - Bad Gateway" instead of the configured developer page.

**Comment by ryanbrandenburg** [comment]
@bluemmc I don't get a Bad Gateway error. The most descriptive thing I got was ERR_INCOMPLETE_CHUNKED_ENCODING (in chrome) which seems like a reasonable response to the request ending in the middle. What browser did you see the 502.3 in?

**Comment by ryanbrandenburg** [comment]
After consulting with @Tratcher we've decided that this is as expected. Throwing an exception in a formatter will cause the request to end early and can't be intercepted to provide error messages.

If you're getting exceptions in your formatter that can't be avoided our suggestion is to do them before beginning the response, where the exception will be properly caught.

**Comment by bluemmc** [comment]
@UseDeveloperExceptionPage I got the bad gateway error using chrome.

I think it is bad that error messages can not be provided in specific cases.I guess, you could solve this by allowing buffering when using the developer exception page (UseDeveloperExceptionPage(buffering = true/false). With buffering on, there should be no problem reseting output and showing an exception page instead.

**Comment by Eilon** [comment]
@bluemmc the logging system should report the error no matter what.

**Comment by Tratcher** [comment]
@bluemmc I'd avoid mixing concerns like that. Instead, I'd add the UseResponseBuffering middleware after the UseDeveloperExceptionPage if you needed to debug errors during responses. Don't leave it in longer than needed though, as it causes non-trivial behavior changes for your app.
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Buffering/ResponseBufferingMiddlewareExtensions.cs
