### ISSUE TITLE
Should BeginForm and FormTagHelper include an antiforgery token for GET

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3868]
We could be smart and skip the antiforgery token in the form when it's for a `GET`.

We'd probably want to have the same behavior for `BeginForm` and `<form>` taghelper

**Comment by NTaylorMullen** [comment]
Ooo, That'd be fancy. :+1: I like.

**Comment by Eilon** [comment]
Yeah we don't want it on GETs by default. But the user should be able to force it on or off always. So let's make sure the anti-forgery option in each of these mechanisms is a nullable `bool`, with `null` meaning "auto".
