### ISSUE TITLE
[Proposal] Simpify TagHelper value context for types

### ISSUE THREAD

**Issue by sgjsakura** [aspnet/Mvc#3873]
Hi all,
I'm now working on MVC projects and trying to design new tag helpers. Some tag helper attributes need to input a type as its value. e.g. The TagHelper may defined as:
```C#
public class MyTagHelper : TagHelper
{
  [HtmlAttributeName("asp-data-type")]
  public Type DataType {get;set;}
}
```
In the rozar view page, the current usage should be:
```HTML
<input asp-data-type="typeof(int)" />
<input asp-data-type="a" /> <!-- a is a C# variable of System.Type --> 
```
I suggest the new grammer be:
```HTML
<input asp-data-type="int" />
<input asp-data-type="@a" />
```

Thank you~

**Comment by NTaylorMullen** [comment]
This would definitely be interesting. We have a similar (but not duplicate) issue [here](https://github.com/aspnet/Razor/issues/200). Going to move this issue to Razor.

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Razor#655
