### ISSUE TITLE
Null passed as arguments to controller method parameters when no InputFormatter matches

### ISSUE THREAD

**Issue by bluemmc** [aspnet/Mvc#3874]
if the request's content-type is missing or not matching any InputFormatter then controller methods are passed null as arguments where data need to be deserialized. In the example below 'employee' is then null when the method is called. Instead the code 415 should be returned and the controller method should NOT be called.

```public IActionResult UpdateEmployee(uint employeerId, [FromBody] Employee employee)```

P.S:
A workaround is to create a middleware the code below to force the error it is not very pretty and breaks if other content types than json is added because I am not aware how to check properly any of the registered InputFormatter's match rather then hardcoding it.

```
       async Task Invoke(HttpContext context)
        {
          string method = context.Request.Method;
          if (method == "PUT" || method == "POST" || method == "PATCH")
          {
                RequestHeaders typedHeaders = context.Request.GetTypedHeaders();
                MediaTypeHeaderValue contentType = typedHeaders.ContentType;
                if (contentType==null || contentType.SubType!=@"json")
                {
                    context.Response.StatusCode = Status415UnsupportedMediaType;
                    return;
                }
          }

          await next.Invoke(context);
        }
```

**Comment by rynowak** [comment]
If you want this behavior add `[Consumes("application/json", "text/json")]`. You can add this to the list of  global filters if you want to configure it application-wide.

```
services.AddMvc(options => options.Filters.Add(new ConsumesAttribute(...)));
```

**Comment by bluemmc** [comment]
@rynowak I can not confirm this. I tried adding the consumes attribute to the base controller for all my controllers and it does not change the behavior. I still get null passed to the employee argument if content-type is missing for my PUT request to the update method UpdateEmployee.

**Comment by rynowak** [comment]
@bluemmc - this is definitely at odds with how the feature was intended to work - https://github.com/aspnet/Mvc/issues/1782

It looks like this code has remained mostly unchanged since it was added aspnet/Mvc@60fa4a6f

I'll dig in and see what I can figure out.

**Comment by rynowak** [comment]
This case, and the surrounding comment just don't really fit the intent of the feature. I think we've had this bug for a while because no one was paying attention to what happens when you don't have a content type!

https://github.com/aspnet/Mvc/commit/60fa4a6f#diff-69de547dc02178bc5eb004e33185ce7cR78

I'd suggest the following changes to the handling when there's no ContentType specified in the body:
- If another action exists without consumes, call it
- If no other action exists (your case) - this should be a 415
- If multiple other actions exist (overloaded on `[Consumes(...)]` - this should be a 415

**Comment by bluemmc** [comment]
Thanks for looking at this. I think behavior should depend on missing/wrong content-type AND if there are arguments that needs serialization or not. If there is no content content-type is not  required. if There is content-type should be required.

**Comment by fiksen99** [comment]
Based on ghost's comment: 

> Thanks for looking at this. I think behavior should depend on missing/wrong content-type AND if there are arguments that needs serialization or not. **If there is no content content-type is not required**. if There is content-type should be required.

This behaviour is not currently honoured in Mvc v2.0.2.
calling a POST method with a null body and null Content-Type is also returning 415 status code. It sounds like the intended behaviour is to allow null input with no content-type specified. The parameter in the controller action should then be null.

**Comment by javiercn** [comment]
The behavior is to return 415 when you have an argument that would need to be deserialized, Independent of whether you sent content type or not, and to let requests without content type go through when they aren’t deserializing arguments from the body.

**Comment by fiksen99** [comment]
So in my example of:
Controller action has a [FromBody] argument of type object, and [HttpPost]
annotation
POSTing to that action's route with an empty body, and no Content-Type
header.

Status code 415 is or is not expected in this case? I would argue that we
should expect the action to be hit with an argument of default(T). What we
actually observe is 415 returned at model binding time (i.e. the action is
not hit).

**Comment by fiksen99** [comment]
as per HTTP/1.1 spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.2.1

> Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body. If and only if the media type is not given by a Content-Type field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource. **If the media type remains unknown, the recipient SHOULD treat it as type "application/octet-stream".**

[emphasis mine]

Based on this deinition, ASP.NET Core is not going against a "must"/"must not" portion of the spec. However the bolded section indicates that there should be a default value. 

So in the request received pipeline - empty content-type should be coerced into "application/octet-stream" and then model binding should be performed on the null data, with the null object passed into the controller action method. The action should handle null data input.

**Comment by javiercn** [comment]
> If the media type remains unknown, the recipient SHOULD treat it as type "application/octet-stream"
Old Web API used to have that behavior and it was a frequent source of issues for customers. The current behavior, while not "fully compliant" is less surprising to our customers and results in a better experience.

The result in the general case would be the same as we don't have any formatter that handles application/octect-stream and there is no useful way the framework can provide a mapping between application/octect-stream and a given type.

If you want to have this behavior you can just write your own input formatter and plug it in.

**Comment by fiksen99** [comment]
> If you want to have this behavior you can just write your own input formatter and plug it in.

This is what I'd already ended up doing via a ResourceFilter: https://gist.github.com/fiksen99/61cef3d1e9af8830e12933e70a2437af

However it still feels like this behaviour is broken. Why should the existence of Content-Type matter when the body of a request is null? Regardless of Content-Type, we should be able to map this to a null/Default(T), and have my controller handle the request, instead of failing at model biding time.
