### ISSUE TITLE
Object as route parameter when using AnchorTagHelper

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Mvc#3875]
If I use the `UrlHelper` to generate the href I can pass a complex object as a route parameter but the `AnchorTagHelper` adds all parameters as strings. Are there any plans on adding support for objects as route parameters?

This is a working example using the `UrlHelper`:

``` c#
<a href="@Url.Action("About", new { page = ViewBag.Page })">About</a>
```

This is what I would like to do using the `AnchorTagHelper`:

```
c#
<a asp-action="Index" asp-action="About" asp-route-page=@ViewBag.Page>About</a>
```

**Comment by NTaylorMullen** [comment]
Currently there's no plan to do that. It may be interesting though to have a way to provide the entire route value dictionary in the form of `<string, object>` in addition to what we have today though.

**Comment by marcuslindblom** [comment]
I tried to create my own tag helper and change the dictionary to `<string, object>`, that did not do the trick though, any ideas?
```c#
[HtmlAttributeName(DictionaryAttributePrefix = RouteValuesPrefix)]
public IDictionary<string, object> RouteValues { get; set; } =
    new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase);
```

**Comment by NTaylorMullen** [comment]
@marcuslindblom When you say you created your own taghelper are you saying your own that targeted the cache tag? What's not working?

**Comment by marcuslindblom** [comment]
@NTaylorMullen I created a new tag helper that targets the anchor tag like this:

```c#
[HtmlTargetElement("a", Attributes = ActionAttributeName)]
[HtmlTargetElement("a", Attributes = ControllerAttributeName)]
[HtmlTargetElement("a", Attributes = RouteValuesPrefix + "*")]
public class AnchorTagHelper : TagHelper
{
    private readonly IUrlHelper _urlHelper;

    private const string ActionAttributeName = "asp-action";
    private const string ControllerAttributeName = "asp-controller";
    private const string RouteValuesPrefix = "asp-route-";

    public AnchorTagHelper(IHttpContextAccessor contextAccessor)
    {
        _urlHelper = contextAccessor.HttpContext.RequestServices.GetService<IUrlHelper>();
    }

    [HtmlAttributeName(ActionAttributeName)]
    public string Action { get; set; }

    [HtmlAttributeName(ControllerAttributeName)]
    public string Controller { get; set; }

    [HtmlAttributeName(DictionaryAttributePrefix = RouteValuesPrefix)]
    public IDictionary<string, object> RouteValues { get; set; } =
        new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase);

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        if (output == null)
        {
            throw new ArgumentNullException(nameof(output));
        }

        var tagBuilder = new TagBuilder("a");
        tagBuilder.MergeAttribute("href", _urlHelper.Action(Action, Controller, RouteValues));

        output.MergeAttributes(tagBuilder);
    }
}
```
But when I use it like this `<a asp-controller="Home" asp-action="About" asp-route-page="@ViewBag.Page">About</a>` the `RouteValues` property is empty.

**Comment by dougbu** [comment]
@marcuslindblom are the MVC tag helpers enabled in your view? If for example `_ViewImports.cshtml` contains `@addTagHelper *, Microsoft.AspNet.Mvc.TagHelpers`, you could try adding
```
  @removeTagHelper Microsoft.AspNet.Mvc.TagHelpers.AnchorTagHelper, Microsoft.AspNet.Mvc.TagHelpers
```
That may at least narrow the issue down.

**Comment by marcuslindblom** [comment]
@dougbu I figured out what was wrong, when I pass in a value from the `ViewBag`, I need to cast it to the correct type like this: `asp-route-page="@((Page)ViewBag.Page)"`. 

The above tag helper works if I use it like this: 

```html
<a asp-controller="Home" asp-action="About" asp-route-test="@("test")" asp-route-page="@Model.CurrentPage">About</a>
```
That is not exactly what I was looking for because I need to use the `@("test")` syntax to pass in a string as a parameter but I guess thats how things are?

**Comment by Eilon** [comment]
@marcuslindblom can you show more about the scenario you're trying to implement? Do you have a custom route or route constraint that is expecting a particular data type?

**Comment by marcuslindblom** [comment]
@Eilon Yes, I have a custom made route and when I get the `VirtualPathData` in this my routes `GetVirtualPathData` it expects a particular data type as a route value parameter. For this I was thinking about using the `asp-route-*` attribute but that is maybe a bad decision, maybe I should use a another attribute like `asp-for` or something? Are there any best practices regarding this scenario?

This is somewhat how my `GetVirtualPath` looks like today:

```c#
 // Handle when the page is added as a route parameter
object value;
if (virtualPathContext.Values.TryGetValue("page", out value))
{
    var page = value as Page;
    if (page == null) return null;
    
    // code here ...
}
```

**Comment by Eilon** [comment]
Moving to Backlog. We'll take another look at this in the next release.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
