### ISSUE TITLE
why log show 2 times request

### ISSUE THREAD

**Issue by blueskybcl** [aspnet/Mvc#3887]
Code:

```c#
public void ConfigureLogInline(IApplicationBuilder app, ILoggerFactory loggerfactory)
        {
            loggerfactory.AddConsole(minLevel: LogLevel.Information);
            var logger = loggerfactory.CreateLogger("LogInline");
            app.Use(async (context, next) =>
            {
                logger.LogInformation("Handling request.");
                await next.Invoke();
                logger.LogInformation("Finished handling request.");
            });

            app.Run(async context =>
            {
                await context.Response.WriteAsync("Hello from LogInline");
            });
        }
```

request url: http://localhost:5000/maptest

response in web command is

```
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://localhost:5000/maptest
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://localhost:5000/maptest
info: LogInline[0]
      Handling request.
info: LogInline[0]
      Handling request.
info: LogInline[0]
      Finished handling request.
info: LogInline[0]
      Finished handling request.
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0266ms 200
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0266ms 200
```

why???

**Comment by danroth27** [comment]
Could you please share with us the complete project that reproduces the issue so we can take a look? Thanks!

**Comment by blueskybcl** [comment]
source at https://github.com/blueskybcl/ContosoBooks/

**Comment by blueskybcl** [comment]
source at https://github.com/blueskybcl/ContosoBooks/

2016-01-12 

a364711322 



发件人：Daniel Roth <notifications@github.com>
发送时间：2016-01-12 01:53
主题：Re: [Mvc] why log show 2 times request (#3887)
收件人："aspnet/Mvc"<Mvc@noreply.github.com>
抄送："blueskybcl"<a364711322@sina.com>

Could you please share with us the complete project that reproduces the issue so we can take a look? Thanks!

**Comment by danroth27** [comment]
Looks like this code adds the Console logger twice:
https://github.com/blueskybcl/ContosoBooks/blob/master/Startup.cs#L39
https://github.com/blueskybcl/ContosoBooks/blob/master/Startup.cs#L81

**Comment by blueskybcl** [comment]
Thank you.

2016-01-14 

a364711322 



发件人：Daniel Roth <notifications@github.com>
发送时间：2016-01-14 01:47
主题：Re: [Mvc] why log show 2 times request (#3887)
收件人："aspnet/Mvc"<Mvc@noreply.github.com>
抄送："blueskybcl"<a364711322@sina.com>

Looks like this code adds the Console logger twice:
https://github.com/blueskybcl/ContosoBooks/blob/master/Startup.cs#L39
https://github.com/blueskybcl/ContosoBooks/blob/master/Startup.cs#L81
