### ISSUE TITLE
Failed Dependency Inject during Startup Issue

### ISSUE THREAD

**Issue by Fosol** [aspnet/Mvc#3891]
Within The Startup after all my code in the ConfigureServices has run and before my Configure has started any failed dependency injection error results in a hard crash that provides no exception information.

Running it bare bones with DNX you can get the exception but you can't step through to debug (i.e. dnx web).

**Comment by Fosol** [comment]
The reason for the exception itself was a coding mistake.  I was trying to add a scoped service and initialize it with an interface.
```
services.AddScoped<IName, IName>();
```
Obviously a coding mistake that should have been much easier to catch.  Not sure if this should be moved to Kestrel issues or Visual Studio Tooling.

**Comment by davidfowl** [comment]
What did you see?

**Comment by Fosol** [comment]
Nothing within Visual Studio.  

But if I ran it through a separate command prompt then I could see the exception details in the cmd window.

**Comment by Fosol** [comment]
The exception in the command prompt was the normal descriptive one - you can't create an instance of an interface.

**Comment by pranavkm** [comment]
Did you have the `DeveloperExceptionMiddleware` configured - https://github.com/aspnet/Mvc/blob/dev/samples/TagHelperSample.Web/Startup.cs#L30?

**Comment by Fosol** [comment]
Yes I do have that in my Configure however it never reaches it if the ConfigureServices fails in the behind code (not my libraries).

**Comment by pranavkm** [comment]
Ahh, I guess it's failing as part of constructing the service provider. Switching to kestrel in VS shows the stack trace, but running it via IIS Express causes it to spin forever. Seems like an issue with the platform handler failing to show proper diagnostics when the underlying process crashes. I'll ask around on to figure out who should address this issue.

**Comment by pranavkm** [comment]
Moved it here - https://github.com/aspnet/Tooling/issues/363.
