### ISSUE TITLE
Hanging FlushPoint test

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Mvc#3893]
I have disabled the Microsoft.AspNet.Mvc.FunctionalTests.FlushPointTest.FlushPointsAreExecutedForPagesWithComponentsPartialsAndSections test in https://github.com/aspnet/Mvc/commit/c68f742dd0860a3dbde40c84f09ff9add6112b39 since this test hangs on our CI's Other Platforms/Windows projects. I took a brief look but didn't spot anything suspicious. 

More thorough investigation is needed before turning this test back on.

**Comment by ryanbrandenburg** [comment]
Do you happen to have the test runs that failed somewhere?
