### ISSUE TITLE
Consider removing some basic senario dnx commands from project.json for simplicity

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Mvc#3899]
I understand that these are commands that can be used by dnx but with the move to dotnetcli I think they may become a source of confusion.
Given with the new hosting model all projects will have an entry point of Main, is it still needed at least for web/run/kestrel?

Also could we move the ef commands to dotnetcli?
I had a chicken and egg scenario yesterday where I wanted to re - reverese enginner from my database but because my assembly wasn't in a build state I had to comment lots of stuff out then build before I could run the ef command.  Seems like the revengineer tool wouldn't use reflection and could easily live outside?

I understand there is also the  test command with I haven't looked into yet and maybe code analysis when it arrives maybe these have to stay for reflection purposes?

**Comment by danroth27** [comment]
Yup, all of these commands are being moved to the .NET CLI model. You can track the progress in the various repos. Closing this issue as there really isn't anything to do here for MVC.
