### ISSUE TITLE
Optimize invoking action method

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3903]
Here's a quick look at an execution profile for an MVC app rendering a pretty significant Razor View.

![image](https://cloud.githubusercontent.com/assets/1430011/12243799/4283d3a8-b855-11e5-8c8c-f573820e7e28.png)

Notice that `RuntimeMethodInfo.Invoke` is eating about 3% of execution time. We should experiment with computing a cached delegate here.

**Comment by rynowak** [comment]
@Eilon @danroth27 - recommending next milestone for this one. Low pri and no public API impact.

**Comment by Eilon** [comment]
@rynowak what do you define "next milestone" as? We'd like to get things done in RC2, or post-RTM. We have only a small window in between those.

**Comment by rynowak** [comment]
> what do you define "next milestone" as?

I'd start by putting this below wherever your cutline is for RC2. If there's time then we can pull it back. We can definitely ship RTM without doing this and it has no public API impact.

**Comment by Eilon** [comment]
That'd be the backlog :smile: We're already in the process of trimming down RC2 items, so unfortunately that means this will have to wait as well.

**Comment by SajayAntony** [comment]
@rynowak do you think you want to assign this to @mnltejaswini ?

**Comment by rynowak** [comment]
Sounds good.
