### ISSUE TITLE
redesign ValueProviderFactory

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3904]
Here's an execution profile from an MVC app rendering a pretty significant Razor Page:
![image](https://cloud.githubusercontent.com/assets/1430011/12243892/b8418856-b855-11e5-95e4-abd844eb2888.png)

This is also a significant source of per-request allocation because VPF returns a `Task<IValueProvider>` but rarely goes async. We should consider redesigning this api.

Change:
```
public Task<IValueProvider> CreateValueProvider(ActionContext c);
```

Change:
```
public Task CreateValueProvider(ActionContext c, IList<IValueProviders> vps);
```

Or maybe a bespoke context instead of two-args. You get the idea.

**Comment by benaadams** [comment]
`ValueTask`?

**Comment by Eilon** [comment]
We could instead do this:

```c#
public Task CreateValueProvider(ValueProviderFactoryContext c);

public class ValueProviderFactoryContext
{
    public ActionContext ActionContext { get; }
    public IList<IValueProviders> ValueProviders { get; }
}
```

**Comment by ajaybhargavb** [comment]
We also decided to rename methods that adds stuff to a context and returns void but is named `Get***()`. `IValidationMetadataProvider`, `IDisplayMetadataProvider`, `IBindingMetadataProvider`, `IModelValidatorProvider` and `IClientModelValidatorProvider`

**Comment by Eilon** [comment]
:+1:
