### ISSUE TITLE
Consider adding custom asp-key attribute to CacheTagHelper

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#3909]
Currently the `CacheTagHelper` utilizes `context.UniqueId` in combination with its configuration properties to determine its cache key. This value changes whenever the app is rebooted. We should add an ability to provide a key to be something like:

``` C#
<cache asp-key="1234">
...
</cache>
```

This way it'd be easy to lookup information in the cache for debugging purposes or even enable a distributed cache scenario on top of the current `CacheTagHelper` implementation.

**Comment by pranavkm** [comment]
@NTaylorMullen should we close this? We haven't had any customer asks for this as yet

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
