### ISSUE TITLE
@Model in top of cshtml still rendered

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Mvc#3912]
```
@model PaperToolbarModel
<paper-toolbar>
    @if (Model.ShowMenuIcon)
    {
        <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
    }
    <div class="title">@Model.Title</div>
    <div class="right">@User.Identity.Name</div>
</paper-toolbar>
```

```
@Model PaperToolbarModel
<paper-toolbar>
    @if (Model.ShowMenuIcon)
    {
        <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
    }
    <div class="title">@Model.Title</div>
    <div class="right">@User.Identity.Name</div>
</paper-toolbar>
```

Notice the difference on "M" within "@model"

I believe @model supposed to be case sensitive
if you use @Model, the page still properly rendered but with model name rendered as its ToString

Either to make it case insensitive or give warn when cshtml page use @Model

**Comment by NTaylorMullen** [comment]
@andrew-vandenbrink Using `@Model` is valid. It shows that you're trying to access the `Model` property of the page. What if you do `@model string`? Doing `@Model` then becomes the only appropriate way to render said model.

**Comment by Eilon** [comment]
As @NTaylorMullen said, `@model SOME_TYPE` is a Razor directive to specify the model type that will be used for the page's `Model` property (and elsewhere).

On the other hand `@Model` is referencing `this.Model`, which is of the type specified in `@model`.

**Comment by andrew-vandenbrink** [comment]
This is correct, just like @NTaylorMullen explained
```
@model PaperToolbarModel
@Model
```

This one should generate warning or maybe make the behavior same like above
```
@Model PaperToolbarModel
@Model
```

**Comment by Eilon** [comment]
Unfortunately there's no way to know that it should be a warning. It could be perfectly legitimate code. Warnings are reserved for stuff that's almost certainly wrong or unintentional.
