### ISSUE TITLE
Tag helper asp-route for dates works differently to Url.Action Link

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Mvc#3913]
Given the following UK dates

StartDate = 01/01/2016
EndDate = 31/01/2016

```
@Url.Action("GetStatement", "Statement",new { accountNo = Model.TradingPartner.AccountNo,startDate = Model.StartDate,endDate = Model.EndDate}, null)">
```
Gives a link
```
https://localhost:44323/reports2/aes/Statement/GetStatement?accountNo=216305&startDate=01%2F01%2F2016%2000%3A00%3A00&endDate=01%2F31%2F2016%2000%3A00%3A00
```

and

```
<a asp-controller="Statement" asp-action="GetStatement" asp-route-AccountNo="@Model.AccountNo" asp-route-StartDate="@Model.StartDate" asp-route-EndDate="@Model.EndDate">@statementDate.Display</a>
```
Gives a link
```
https://localhost:44323/reports2/aes/Statement/GetStatement?AccountNo=216305&StartDate=01%2F01%2F2016%2000%3A00%3A00&EndDate=30%2F01%2F2016%2000%3A00%3A00
```
Note using the UrlAction renders the EndDate as US and tag helper renders the date as UK.
(which causes an SQL exception in EF).
Now I can go ISO dates on this to fix (probably better anyway) but I thought I would point it out as it caught me.

Out of interest where is the locale taken from for dates.

**Comment by dougbu** [comment]
@mikes-gh the difference in your two examples is in what your code is passing. The anonymous object used when you call `Url.Action()` passes `DateTime` (or `DateTimeOffset`) instances to the underlying code. The `Dictionary<string, string>` backing attributes such as `asp-route-StartDate` forces `ToString()` in the Razor file. In the first case, the routing code uses the invariant culture for conversions and that looks like a US date.

**Comment by mikes-gh** [comment]
I see so the routing code uses invariant culture which just happens to be US style.  I guess thats at the heart of dot net.  I guess a better invariant culture date would be ISO date which I have now changed it to. Thanks for your help.

**Comment by Eilon** [comment]
@mikes-gh unfortunately the tag helper can't distinguish between how to format certain properties, especially with dictionary-based properties such as `asp-route-XYZ`. The tag helper itself doesn't even participate in that conversion. It's just an aspect of tag helpers in general. And, in general, I think that using CurrentCulture is the correct culture for most cases (e.g. displaying data to the user in a normal way).

I agree this isn't ideal but there isn't a good way to control the culture automatically.

As such, I always recommend formatting the string in the specific format you want before passing the data to routing or other components that might require or expect a particular format.
