### ISSUE TITLE
Reduce `string`s allocated when generating in nested context or for Linq expressions

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3918]
`TemplateInfo.GetFullHtmlFieldName()`, `ExpressionHelper.GetExpressionText()` and `TagBuilder.CreateSanitizedId()` are frequently used in almost all HTML and tag helpers. Unfortunately they each do a significant amount of relatively inefficient `string` manipulation, leading to large numbers of `string` allocations per request.

In particular
- `TemplateInfo.GetFullHtmlFieldName()` concatenates `string`s when `HtmlFieldPrefix` and the given field name are not empty. But real views often use multiple helpers (e.g. `LabelFor()`, `DisplayFor()`, and `ValidationSummaryFor()`) for the same field.
- `ExpressionHelper.GetExpressionText()` uses a lot of Linq (e.g. `Aggregate()`) whenever it's called. Again, it caches no information about the given Linq expression.
- `TagBuilder.CreateSanitizedId()` must create a new `string` when given a name containing either `'.'` or `'['. That often happens in partials and other "inner" views. And, again, field names are often repeated even within a single view e.g. `LabelFor()` and whichever helper is used to display / edit the value.

**Comment by dougbu** [comment]
Updated the truncated description.

**Comment by dougbu** [comment]
For a simple view using tag helpers with a collection model where each element has seven fields, almost all of the topmost allocators are within these three methods:
![capture](https://cloud.githubusercontent.com/assets/6431421/12281482/5dea8668-b94b-11e5-90c8-2f06d1b1d972.png)

**Comment by Eilon** [comment]
@dougbu @rynowak moving to backlog as we're a bit overbooked. This doesn't seem to involve API changes so we can pick this up another time.

**Comment by rynowak** [comment]
No complaint from me. Seems like this is something we could do at any time.

**Comment by dougbu** [comment]
:ok: by me :two:

**Comment by Eilon** [comment]
@dougbu if you can come up with a design for this, then we can reassign to someone to implement the fix.

**Comment by Eilon** [comment]
Moving to post-v1 because we can improve this at any time.

**Comment by dougbu** [comment]
In recent versions, `string` allocations have mostly shifted from `string.Concat()` to `StringBuilder.ToString()`. But these three methods still account for more than 5% of the allocations in the main BigViews scenario. Note the correct breakdown is visible only when profiling Debug builds (though the numbers are obviously elevated).
![before](https://cloud.githubusercontent.com/assets/6431421/17041948/aed5aea0-4f5e-11e6-801c-351f06347659.png)

**Comment by dougbu** [comment]
Have done a lot of work on this but focusing on quicker issues right now.

**Comment by dougbu** [comment]
Splitting into 3 parts.

First part added to dev as  a04f5cb. Thanks very much to @benaadams!

**Comment by dougbu** [comment]
Part 2 of a likely 4: 4cca6b0

**Comment by dougbu** [comment]
Part 3 implemented in aspnet/HtmlAbstractions@0781b5a and eea2979.

**Comment by dougbu** [comment]
Part 4 implemented in 4e1ec39.

I'll do another check of memory profiles now these four fixes are in. Hope to close this bug or (worst case? 😈) find another low hanging fruit or two.

**Comment by dougbu** [comment]
Closing given the gains from 4 commits described above. Will file more targeted bugs about one or two remaining potential improvements.
