### ISSUE TITLE
Remove uncached Reflection in `ExpressionHelper.GetExpressionText()`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3921]
The `IsSingleArgumentIndexer()` helper method performs uncached Reflection. `ModelMetadata` could be available in this code. Or cached information about the Linq expression could be reused.

**Comment by danroth27** [comment]
Does this show up when profiling?

**Comment by rynowak** [comment]
Yes, that's how we found it :+1: I don't have the data in front of me though, I was looking over @dougbu 's shoulder

**Comment by dougbu** [comment]
`GetCustomAttribute<T>()` is responsible for a fair number of different allocations. Hard to see the total using these tools. But those calls cost more than 1% of the top two allocated types.

See `object[]`:
![object](https://cloud.githubusercontent.com/assets/6431421/12430575/2b6d130e-bea5-11e5-8058-23433c583e25.png)

And `string`:
![string](https://cloud.githubusercontent.com/assets/6431421/12430587/3aac54ce-bea5-11e5-920b-2c8c6a2a830a.png)

**Comment by dougbu** [comment]
Hmm, since `string` allocations are part of this, we could consider this issue as a detail of #3918.

**Comment by Eilon** [comment]
@dougbu @rynowak moving to backlog as we're a bit overbooked. This doesn't seem to involve API changes so we can pick this up another time.

**Comment by mnltejaswini** [comment]
We optimized the current ExpressionHelper to the commonly occurring scenarios (which is also the targeted scenarios)  like member access. However, for the indexer expression, there is still cost from compiling the expression every time. This fix for this issues is not straightforward and needs more analysis. As indexer expressions are not the targeted scenarios, this performance issue will be closed as resolved. However we will track the issues with the indexer expressions separately based on the priority.
