### ISSUE TITLE
ASP.Net 5 and URLRewrite

### ISSUE THREAD

**Issue by Gonkers** [aspnet/Mvc#3922]
I am currently running VS2015 with ASP.Net 5 RC1 and I am able to successfully use URLRewrite in most cases. When I add the rule below I get the error `"An error occurred attempting to determine the process id of the DNX process hosting your application."`

```
        <rule name="Redirect to HTTPS">
          <match url="(.*)" />
          <conditions>
            <add input="{HTTPS}" pattern="^OFF$" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" redirectType="Permanent" />
        </rule>
```

I have no issues with this when I use ASP.Net 4.6 mvc 5. Any thoughts?  Thanks.

**Comment by Gonkers** [comment]
For some additional information, I wanted to be clear, I received the above error message while debugging in VS2015.

**Comment by danroth27** [comment]
@Tratcher @BillHiebert Thoughts on what could be happening here?

**Comment by BillHiebert** [comment]
VS makes an http request with the Debug verb to get the httpPlatformHandler to start the dnx.exe process to get its process ID and attach the debugger to it. Most like the url rewrite is interfering with this.

**Comment by danroth27** [comment]
Looks like you could do something like this:

```xml
<add input="{REQUEST_METHOD}" matchType="Pattern" pattern="DEBUG" ignoreCase="true" negate="true" />
```

**Comment by Gonkers** [comment]
Thanks @danroth27 I'll give it a whirl.
