### ISSUE TITLE
Creating TagHelpers is surprisingly expensive

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3924]
This page has a lot of use of `UrlResolutionTagHelper` https://github.com/rynowak/mvc-sandbox/blob/master/workloads/LargeStaticView/Views/TagHelpers/Index.cshtml

![image](https://cloud.githubusercontent.com/assets/1430011/12282784/b003c036-b955-11e5-8294-4505a3d4818a.png)

17% of the execution time of the page is spend just new-ing these up.

**Comment by Eilon** [comment]
Notes for future us: one option to consider is pooling the tag helpers somehow some way somewhere.

**Comment by Eilon** [comment]
Or just make them cheaper by optimizing current code paths.

**Comment by rynowak** [comment]
Some more data here, from BasicViews:
![image](https://cloud.githubusercontent.com/assets/1430011/13584573/18705b48-e46c-11e5-8a3c-31e9083bb8fc.png)

Activating TagHelpers is 12% of the View's execution time.

**Comment by Eilon** [comment]
Moving to 1.0.0.

**Comment by Eilon** [comment]
Let's collect some new data on this using Music Store and see if there's still a major trouble spot here. Then we'll see if there's any work to do.

**Comment by rynowak** [comment]
Updated Data from BasicViews 5/23

![image](https://cloud.githubusercontent.com/assets/1430011/15488820/1c0d7706-210f-11e6-9ccd-5feda94361c0.png)

This is roughly 10% of view execution time for the (simple) app.

**Comment by rynowak** [comment]
Moving this to 1.0.1 - I have some ideas here, but this isn't high priority compared to some of the other issues we have.

**Comment by rynowak** [comment]
Nothing happening here in 2.0.0

**Comment by mkArtakMSFT** [comment]
Closing this as this is not a priority for now.
