### ISSUE TITLE
Reference Controller instance from ViewComponent

### ISSUE THREAD

**Issue by chassq** [aspnet/Mvc#3925]
Hey,

Was just trying to figure out if there is a way to see the current controller instance from a ViewComponent? Is it there as part of the ViewComponent objects or would I have to inject it?

Hope my question makes sense.

Thanks!

**Comment by rynowak** [comment]
What do you need the current Controller instance for? Wondering if there's a better way to accomplish what you really need?

**Comment by chassq** [comment]
Right now I run all my session (using Redis) management through the base controller and wanted to access it through the View Component. Just wanted one place where session variables could be accessed and managed.  I guess I could bring session mgmt. out of the base controller and created a separate class just for it but it would just be easier in my situation to just have a reference to the current controller instance in the View Component if one was available. If not I could always put a ref to the BaseController instance in a ViewBag item and pass the item in where I invoke the Component in the cshtml. Kinda hacky though... Hope that helps...

**Comment by rynowak** [comment]
I'd recommend creating a model object or business service to encapsulate the state you need to share between the controller and view/view-component. This is going to be more testable and maintainable than try to tie your VC directly to the session state.

Do you have some sample code? I could make more specific suggestions.

**Comment by chassq** [comment]
Thanks!

I think I will go the model component route to be shared between the VC and the rest of the app. Thanks for the advice.
