### ISSUE TITLE
TryUpdateModelAsync fails with argument null exception Parameter name: metadataProvider

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Mvc#3926]
I have an API controller with a `Post` method like this:

```c#
[HttpPost]
public async void Post([FromBody]Page page)
{
    if(ModelState.IsValid) {
        using (var session = _documentStore.OpenAsyncSession())
        {
            var p = await session.LoadAsync<Page>(page.Id);

            if (await TryUpdateModelAsync(p))
            {
                await session.StoreAsync(p);
                await session.SaveChangesAsync();
            }
        }
    }
}
```

I issue the request using Fiddler like this:

![screen shot 2016-01-13 at 20 31 27](https://cloud.githubusercontent.com/assets/319720/12305363/b0925b9a-ba34-11e5-9441-4abee193b1d0.png)

The model binds correctly:

![screen shot 2016-01-13 at 20 28 33](https://cloud.githubusercontent.com/assets/319720/12305385/d327fade-ba34-11e5-95e9-2112ecaff9bc.png)

But `TryUpdateModelAsync` fails with the following exception:

![screen shot 2016-01-13 at 20 29 01](https://cloud.githubusercontent.com/assets/319720/12305412/f9b565b0-ba34-11e5-8f58-a12c2ae433d3.png)

```
System.ArgumentNullException was unhandled by user code
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: metadataProvider
  ParamName=metadataProvider
  Source=Microsoft.AspNet.Mvc.Core
  StackTrace:
       at Microsoft.AspNet.Mvc.ModelBinding.ModelBindingHelper.TryUpdateModelAsync[TModel](TModel model, String prefix, HttpContext httpContext, ModelStateDictionary modelState, IModelMetadataProvider metadataProvider, IModelBinder modelBinder, IValueProvider valueProvider, IList`1 inputFormatters, IObjectModelValidator objectModelValidator, IModelValidatorProvider validatorProvider)
       at Microsoft.AspNet.Mvc.Controller.TryUpdateModelAsync[TModel](TModel model, String prefix, IValueProvider valueProvider)
       at Microsoft.AspNet.Mvc.Controller.TryUpdateModelAsync[TModel](TModel model, String prefix)
       at Microsoft.AspNet.Mvc.Controller.TryUpdateModelAsync[TModel](TModel model)
       at src.Controllers.PageController.<Post>d__4.MoveNext() in C:\Projects\Sandbox\aspnet5\src\Controllers\PageController.cs:line 44
  InnerException: 
```

Is this an issue or am I doing something wrong?

**Comment by marcuslindblom** [comment]
The problem only seems to appear when I use Fiddler or Javascript to post my data, not if I put the same code on my `HomeController` and post the form, `TryUpdateModelAsync` works as expected?

**Comment by rynowak** [comment]
This seems really strange. Is there a repo somewhere we could look at?

**Comment by marcuslindblom** [comment]
@rynowak Sure, here is the [controller](https://github.com/marcuslindblom/aspnet5/blob/master/src/Controllers/PageController.cs#L39) I use and here is the [script](https://github.com/marcuslindblom/aspnet5/blob/master/src/wwwroot/js/site.js#L108) I use to post the data. The [HomeController](https://github.com/marcuslindblom/aspnet5/blob/master/src/Controllers/HomeController.cs#L38) works with the exact same code.

**Comment by rynowak** [comment]
Your issue here that the action method is declared as `async void` - it should be `async Task`

**Comment by rynowak** [comment]
See: https://github.com/aspnet/Mvc/issues/3901#issuecomment-170610622

**Comment by Eilon** [comment]
@rynowak I'd love to throw in that case but as you said yourself, it is difficult to reliably do so.

Closing this bug as it's effectively a dup of https://github.com/aspnet/Mvc/issues/3901

**Comment by marcuslindblom** [comment]
Changed the return type to `Task` and it seems to work as it should, thanks @rynowak for your the help!
