### ISSUE TITLE
Suggestion: error message indicates layout instead of current view.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#3930]
When having a layout with a `RenderSection` required, and then you go to a View without that section defined, the error message is:

```
Section 'sectionName' is not defined in path '/Views/Shared/_Layout.cshtml'.
```

but I think it should be:

```
Section 'sectionName' is not defined in path '/Views/Home/Index.cshtml'.
```

**Comment by Eilon** [comment]
Indeed that looks backwards!
