### ISSUE TITLE
Default model validation messages

### ISSUE THREAD

**Issue by miroslavsiska** [aspnet/Mvc#3935]
Is please possible customize default model validation messages? I would like use client side validation before ajax call base on culture for decimal type.
For example: Data-val-number="The field {0} must be a number.   ...is still only in english.
 No simmilar question on internet found for mvc 6...
Thank you
Miroslav

**Comment by dougbu** [comment]
Sounds like a dupe of #2969. If you agree @miroslavsiska, please close this issue.

**Comment by Eilon** [comment]
Yup, dup of https://github.com/aspnet/Mvc/issues/2969.
