### ISSUE TITLE
How to override controllerselector

### ISSUE THREAD

**Issue by Varorbc** [aspnet/Mvc#3943]
How to override controllerselector

**Comment by davidfowl** [comment]
What are you trying to do? (And don't say override the controller selector :smile: )

**Comment by Varorbc** [comment]
@davidfowl I want to version control in web api,so i need overridde controller selector,but i don't know how to do

**Comment by davidfowl** [comment]
I assume this can be done using the new application model in MVC 6 but you'd need to provide a little more detail on how you were doing things before.

/cc @rynowak

**Comment by rynowak** [comment]
We have a same here of using action constraints to implement a version policy: https://github.com/aspnet/Mvc/tree/dev/test/WebSites/VersioningWebSite

We really don't recommend replacing the action selector
