### ISSUE TITLE
Razor view will not allow <div></div> to be split

### ISSUE THREAD

**Issue by gkochanowsky** [aspnet/Mvc#3944]
This code will not run.

```
@if (1 == 1) {
    <div> }
        <dl>
            <dt>some label</dt>
            <dd>some text</dd>
        </dl>
@if (1 ==1) {
     </div> }
```

**Comment by salerth** [comment]
Ignoring whether this should fail or not, you can ask Razor nicely to render as text to get around it:

http://stackoverflow.com/questions/4809694/razor-doesnt-understand-unclosed-html-tags

**Comment by gkochanowsky** [comment]
I've already worked around it. I'm just reporting what used to work in previous versions and doesn't work now.

**Comment by gkochanowsky** [comment]
In RC1 this works:
@if (1 == 1) { @Html.Raw("`<div>`") }
	`<div>`some content`</div>`
@if (1 == 1) { @Html.Raw("`</div>`") }

But this doesn't:
@if (1 == 1) { @:`<div>` }
`<div>`some content`</div>`
@if (1 == 1) { @:`</div>` }`

**Comment by tuespetre** [comment]
I suppose it would be pertinent to ask: does it ever make sense to split up opening and closing tags like this? I can't think of a scenario that would truly require such a split, and given how Razor operates in MVC6 for TagHelpers to work, I wouldn't expect this to change.

**Comment by gkochanowsky** [comment]
Normally I would avoid it like the plague. But I'm switching my modal SCRUD from jQuery UI to bootstrap and bootstrap favors HTML over jQuery. So I have the case where I want to create a modal version of a view via ajax and a non-modal version of the same view also via ajax. I usually try the simplest thing first and thus I found myself splitting <div> tags.

I have a workaround where I am no longer doing this by using a little jQuery to move things around after the ajax modal div is loaded. It appears that no matter how I do it, its a bit of a kludge.

**Comment by NTaylorMullen** [comment]
I'm allowed to do `@: <div>` and `@: </div>` inside of an if block. VS complains with a green squiggly but no error occurs otherwise.

**Comment by Eilon** [comment]
Using this code:

```
@if (1 == 1) { @:<div> 
    }
    <div>some content</div>
@if (1 == 1) { @:</div>
}
```

As shown in https://github.com/aspnet/Mvc/issues/3944#issuecomment-172215744, is the correct solution.
