### ISSUE TITLE
Razor intellisense for mvc6 taghelpers not working when creating a project from scratch rather than using website template

### ISSUE THREAD

**Issue by arundh93** [aspnet/Mvc#3945]
I had created the project from an empty template. My project.json contains the "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final" but the taghelpers such as 'asp-action' (from the 'formTagHelper) are not being recognized in the cshtml files.

To cross check I created a sample project using WebApp template and in that the taghelpers are working fine. Tried to google this issue but could really find anything.

This is same as this issue: https://connect.microsoft.com/VisualStudio/feedback/details/1325343/razor-intellisense-for-mvc6-taghelpers-not-working-when-creating-a-project-from-scratch-rather-than-using-website-template

**Comment by NTaylorMullen** [comment]
@arundh93 in order to have `TagHelper` IntelliSense you must also add the `Microsoft.AspNet.Tooling.Razor` package.
