### ISSUE TITLE
Url.Action's definition of protocol is inconsistent with Request's protocol

### ISSUE THREAD

**Issue by Suchiman** [aspnet/Mvc#3947]
I've noticed that some `Url.Action` overloads take a `string protocol` which is supposed to be `"http" or "https"` but `Request.Protocol` is `"HTTP 1.1"` while `Request.Scheme` is `"http" or "https"`, so the overloads should probably renamed to `string scheme` to be consistent.

**Comment by Eilon** [comment]
This would be a tiny breaking change for anyone who used named parameters before (which probably isn't too unusual for methods that have so many parameters).

However, I like having good names and the break is quite small.

Putting this in RC2 to see if we have time to fix it.

**Comment by ctyar** [comment]
So basically in all extension methods of `UrlHelperExtensions`, `protocol` should be renamed to `scheme` and all the related tests, right?

**Comment by ctyar** [comment]
It seems `UrlRouteContext` and `UrlActionContext` both have the same `Protocol` property
and there are things like this in `UrlHelper`:
```
public virtual string Link(string routeName, object values)
{
    return RouteUrl(new UrlRouteContext()
    {
        RouteName = routeName,
        Values = values,
        Protocol = HttpContext.Request.Scheme,
        Host = HttpContext.Request.Host.ToUriComponent()
    });
}
```
We should rename these too?

**Comment by Eilon** [comment]
@ctyar ah yes this seems to go a bit further than I had expected. I'm thinking maybe we shouldn't do this at the time. The value isn't that great, even though consistency is always nice.

Closing this as it's an unnecessary breaking change.

**Comment by ctyar** [comment]
I was hopping for an easy up-for-grabds, seems I have to wait :smile:

**Comment by Eilon** [comment]
@ctyar yeah sorry about that :smile:
