### ISSUE TITLE
502.3 - Bad Gateway when returning anonymous object from WebApi

### ISSUE THREAD

**Issue by lszomoru** [aspnet/Mvc#3948]
I have a simple WebApi that uses entity framework to query data from a SQL database. I have noticed that if the WebApi tries to return an anonymous object it would fail with a `502.3 - Bad Gateway` error. Here is the source of the WebApi that I can reproduce the issue:

```
[HttpGet("{id}")]
public IActionResult Get(int id)
{
    var notifications = from notification in _dbContext.Notifications
                        where notification.NotificationId == id
                        select new
                        {
                            NotificationId = notification.NotificationId,
                            Subject = notification.Title,
                            IncidentId = notification.IncidentId.Value
                        };

    return Ok(notifications);
}
```

After more debugging, it looks like the error is related to `notification.IncidentId.Value`. IncidentId is defined as `int?` and changing the code to `notification.IncidentId` fixes the problem. Is this expected behavior? Am I missing something? Thanks for your help!

**Comment by tuespetre** [comment]
This is probably better suited for the aspnet/EntityFramework repository. I want to say I ran into the same limitation before as well.

**Comment by brent-russell** [comment]
I usually see this error when there is a problem with serializing the data being sent to the client. Things like circular references that would cause an infinite serialization loop. Calling .Value on a nullable object could yield a null reference exception, which might be your problem. (I also don't see a materialization method being called, but I'll assume it just got left out - AsEnumerable/ToArray/ToList)

If you want to allow null values to be represented in the output, then excluding .Value like you have already said is correct. If not, try using GetValueOrDefault() to force a non-null value.

**Comment by rynowak** [comment]
The first thing to do is to add the developer exception page `app.UseDeveloperExceptionPage()` so you can see the exception message and callstack.

**Comment by davidfowl** [comment]
Another tip would be to turn on logging (usually the console logger) to the Debug, that'll show you *everything*.

**Comment by brent-russell** [comment]
It's worth noting that when the error happens after returning an object from an action method, during what I assume is the serialization process, UseDeveloperExceptionPage doesn't trap/handle the error. I don't know what the pipeline looks like in this case, but it seems like serialization happens outside the scope of the exception handling. (my experience with rc1-update1).

**Comment by Eilon** [comment]
Yeah the problem here is that errors during serialization happen *super* late. The start of the response has already been sent, so it's too late to show any error.
