### ISSUE TITLE
Can I reference AspNet dependencies from a class library in RC1?

### ISSUE THREAD

**Issue by dburriss** [aspnet/Mvc#3949]
Starting with a working ASPNET 5 MVC app (created from RC 1 update 1) I am trying to refactor out some OWIN middleware into a class library (package based one from dnx templates).

I need HttpContext and IServiceProvider.

The class is targeting "dotnet5.4" but I have tried with straight "dnx46" as well.
When referencing "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc1-final"  as a dependency I get "The dependency Microsoft.Extensions.DependencyInjection.Abstractions >= 1.0.0-rc1-final could not be resolved.

I also tried with 1.0.0-*

Is this possible currently? If so any ideas on what I could be doing wrong?

Examples of what I have tried.
```JSON
"dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc1-final"
  }
```
AND (not at same time)

```JSON
"dotnet5.4": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516\".",
        "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
        "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc1-final"
      }
}
```

AND

```JSON
"dnx46": {
      "dependencies": {
        "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
        "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc1-final"
      }
    }
  }
```

Currently no nuget config setup in project. Running dnu restore on the working mvc app I get the following which does look like it points to an issue:

```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

c:\users\deebo\documents\visual studio 2015\projects\mvcframework\src\mvcframework>dnu restore
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231

  CACHE https://api.nuget.org/v3/index.json
Restoring packages for c:\users\deebo\documents\visual studio 2015\projects\mvcframework\src\mvcframework\project.json
  GET https://api.nuget.org/v3-flatcontainer/mvcframework/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/mvcframework/index.json 1493ms
Unable to locate Dependency mvcframework >= 1.0.0
Writing lock file c:\users\deebo\documents\visual studio 2015\projects\mvcframework\src\mvcframework\project.lock.json
Restore complete, 1689ms elapsed

Errors in c:\users\deebo\documents\visual studio 2015\projects\mvcframework\src\mvcframework\project.json
    Unable to locate Dependency mvcframework >= 1.0.0

NuGet Config files used:
    C:\ProgramData\NuGet\Config\JustMock.Config
    C:\Users\deebo\AppData\Roaming\NuGet\nuget.config

Feeds used:
    https://api.nuget.org/v3-flatcontainer/
    C:\Program Files (x86)\Telerik\JustMock\Libraries\NuGet\
```

**Comment by davidfowl** [comment]
All of the things you tried should have worked. What's strange is the thing it cannot resolve is `mvcframework` which looks like the name of the project your are in. Can you reproduce this same behavior if you made a new project?

**Comment by dburriss** [comment]
Yes that is the name of the project. It basically is a File > New Project I did over the weekend. Almost nothing done on it. I will do another to check. I will also upload the project ot github. I am giving a talk on aspnet tomorrow and was hoping to demo the use of the "dotnet" alias. "netstandard" wouldnt work yet right? 
Thanks. Also... not complaining but shouldn't you be asleep?

**Comment by davidfowl** [comment]
> I am giving a talk on aspnet tomorrow and was hoping to demo the use of the "dotnet" alias. "netstandard" wouldnt work yet right? 

Not yet.

> Thanks. Also... not complaining but shouldn't you be asleep?

@dburriss I'm in the UK.

**Comment by ivaylokenov** [comment]
@dburriss I was having the same issue but got it working like a charm after upgrading with `dnvm upgrade` in the console and recreating the project - Class Library (Package). My project.json is:

```
{
  "version": "0.5.0",
  "description": "MyTested.Mvc Class Library",
  "authors": [ "Ivaylo Kenov" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-*" // added only to test your case
  },

  "frameworks": {
    "net451": { },
    "dotnet5.4": { }
  }
}
```
When I add `Microsoft.Extensions.DependencyInjection.Abstractions` it is resolved successfully.

**Comment by dburriss** [comment]
@davidfowl  The new project works. I am going to see if I can get the old project working trying what @ivaylokenov suggested. Would be good to know there is a fix if this happens on a class library that is not trivial to recreate.

**Comment by dburriss** [comment]
Soooo... not sure if it was Visual Studio or what but when I re-opened the project it restored.
Thanks for the help. Good to know it works and useful to know "netstandard" not available yet on RC1.
Although to be honest I am not sure if it is tied to aspnet implementing it, nuget not supporting it yet, or the runtime dnx/dotnet. /Waves hands and invokes "dotnetCore".

**Comment by davidfowl** [comment]
> Although to be honest I am not sure if it is tied to aspnet implementing it, nuget not supporting it yet, or the runtime dnx/dotnet. /Waves hands and invokes "dotnetCore".

All of the above. NuGet though is the main hold up. It's all being implemented for RC2.

**Comment by khellang** [comment]
@dburriss You don't happen to work from a UNC path? I have issues with restore when using Parallels and sharing the code folder... I have to change the project.json and save a couple of times for it to "resolve" the packages. Not sure why :disappointed:

**Comment by dburriss** [comment]
@khellang nope I don't. Now that you mention it though I think I may have started this project in VS Code on my Mac but I don't think that has any bearing here. The class library was created on Windows in full VS. The ol' restart VS sorted my issue out though. Lame I know.

**Comment by dburriss** [comment]
@davidfowl Tell me if I am totally off here but based on the net standard doc and my current understanding wouldn't it be more correct if *project.json* section

"frameworks": {
    "net451": { },
    "dotnet5.4": { }
  }

was instead named

"platforms": {
    "net451": { },
    "dotnet5.4": { }
  }

**Comment by davidfowl** [comment]
Sure, we we're not renaming it at this point. It's a target framework.

**Comment by dburriss** [comment]
Understood.
