### ISSUE TITLE
Try to addScoped abstract class

### ISSUE THREAD

**Issue by markusvt** [aspnet/Mvc#3950]
I just came across the following problem:

In the Startup.cs in the configureServices Method I added the following line
`services.AddScoped<GenericRepository>();`

When I tried to start the application locally, the Browser only showed "Please wait" and when trying to debug the whole IIS crashed.
I looked into it an saw, that my GenericRepository was accidentally marked as *abstract*. So I removed that and all worked fine.

Maybe it is possible for you to throw an Exception in such a case, so that not the whole IIS crashes on such a developer error.

**Comment by tuespetre** [comment]
You may want to close this issue and re-open it [in the aspnet/DependencyInjection repo.](https://github.com/aspnet/DependencyInjection/issues)
