### ISSUE TITLE
TagBuilder.CreateSanitizedId Why sanitized tag ID returns null when it does not begin with a letter ?

### ISSUE THREAD

**Issue by Krishjs** [aspnet/Mvc#3951]
TagBuilder.CreateSanitizedId Why sanitized tag ID returns null when it does not begin with a letter ?

**Comment by dougbu** [comment]
`TagBuilder.CreateSantizedId()` should never return `null`. Please provide a repro project, preferably a GitHub repo.

**Comment by Eilon** [comment]
@dougbu can you try to repro this and possibly add a test? I don't see any tests for exactly this scenario.

**Comment by dougbu** [comment]
@Eilon I created a few tests and submitted #3982.

@Krishjs these tests run fine with current RC2 bits i.e. I haven't reproduced your issue. What specific strings have you seen cause `TagBuilder.CreateSanitizedId()` to return `null`?

Though I don't think we've changed this code in a long while, what DNX version and `Microsoft.AspNet[Core].Mvc` package version are you using?

**Comment by dougbu** [comment]
d696f26

**Comment by dougbu** [comment]
@Krishjs please reopen this bug or file a new one if there is a specific case where this method returns `null`.

**Comment by dougbu** [comment]
Corrected commit: 7dddd06
