### ISSUE TITLE
ViewComponentDescriptor.Type should be a TypeInfo instance instead of a Type instance

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#3952]
ViewComponentDescriptor.Type is of type System.Type while ControllerActionDescriptor.ControllerTypeInfo is of type TypeInfo. 

We should change ViewComponentDescriptor.Type to ViewComponentDescriptor.TypeInfo and change the type of the property to be TypeInfo.

In general, TypeInfo represents the information of a type, while Type respresents a type at runtime. We should use TypeInfo through the stack and do AsType where we need an instance of Type.

I'm not sure if there is a scenario where AsType might return null and if we should guard against that.

**Comment by Eilon** [comment]
I doubt we need null checks for this. Please time box the work so we don't spend a lot of time on it.

**Comment by rynowak** [comment]
Agreed, we should be using `TypeInfo` here and other places. Please look at `ParameterDescriptor` as well and make sure it's consistent.

> I'm not sure if there is a scenario where AsType might return null and if we should guard against that.

This seems excessive :laughing:

**Comment by Eilon** [comment]
Oh wait a sec I could have swore yesterday that we agreed that `Type` was the right thing to use and `TypeInfo` is just an artifact of history. I guess I don't care much either way but this doesn't sound like what we discussed.
