### ISSUE TITLE
Mvc6ControllerWithContextScaffolder encoding templates for views

### ISSUE THREAD

**Issue by Kabanets** [aspnet/Mvc#3957]
This wizard creates views in ANSI encoding. I think encoding must be UTF-8. Am I wrong?

**Comment by pranavkm** [comment]
This issue probably belongs in [Scaffolding](https://github.com/aspnet/Scaffolding) - https://github.com/aspnet/Scaffolding/blob/dev/src/Microsoft.Extensions.CodeGenerators.Mvc/Templates/ControllerGenerator/MvcControllerWithContext.cshtml

**Comment by Kabanets** [comment]
Thanks, you are right. I was wrong.
