### ISSUE TITLE
How to remove X-Frame-Options: SAMEORIGIN from response header

### ISSUE THREAD

**Issue by wolfgangschneider** [aspnet/Mvc#3958]
How to remove X-Frame-Options: SAMEORIGIN from response header

When I'm using ASP.Net 5 RC1 and MVC 6 there is always a X-Frame-Options: SAMEORIGIN in the response header . Unfortunately I have to embed this page in SharePoint. How to remove X-Frame-Options: SAMEORIGIN?

thx

Wolfgang

http://forums.asp.net/t/2082693.aspx?remove+X+Frame+Options+SAMEORIGIN+from+response+header

**Comment by khellang** [comment]
Are you, by any chance, calling `SetAntiforgeryCookieAndHeader` anywhere in your views?

**Comment by khellang** [comment]
There's also a `SuppressXFrameOptionsHeader` property on the `AntiforgeryOptions` that you can set to `true`.

**Comment by wolfgangschneider** [comment]
Thanks
Additional info : 
https://github.com/aspnet/Mvc/issues/3155 and https://github.com/aspnet/Announcements/issues/34

**Comment by rynowak** [comment]
Thanks @khellang  :+1:
