### ISSUE TITLE
502 Bad Gateway - can we get a stack trace / exception?

### ISSUE THREAD

**Issue by joshmouch** [aspnet/Mvc#3967]
Sometimes when I write bad code, DNX/MVC/ASP.NET 5 will stop responding correctly (either with the expected page or else with the DeveloperException page), and instead, give me a 502 Bad Gateway.  Up until now, I think this has always been when there is a StackOverflowException (i.e. an infinite loop somewhere).

However, I just added some code that I'm pretty sure isn't causing an infinite loop, but it's still causing ASP.NET 5 to return this 502 Bad Gateway.

So, my question is: is there a way to get a stack trace or an exception page instead of a non-helpful 502 Bad Gateway response?

**Comment by Eilon** [comment]
Not quite an MVC bug. @Tratcher should this bug go to https://github.com/aspnet/Hosting/, https://github.com/aspnet/IISIntegration/, or perhaps somewhere else?

**Comment by Tratcher** [comment]
IISIntegration, at least until there are more details available.

**Comment by Eilon** [comment]
Moved to https://github.com/aspnet/IISIntegration/issues/76
