### ISSUE TITLE
[Performance] Model binding/validation time grows exponentially on large models

### ISSUE THREAD

**Issue by Kukkimonsuta** [aspnet/Mvc#3969]
When trying to bind a large model with an array the performance goes exponentially down:

![screenshot 2016-01-22 17 18 47](https://cloud.githubusercontent.com/assets/737093/12516154/3f33f842-c12c-11e5-985f-5d35738f4b84.png)

From what I've been able to gather it's due to `ModelState` getting filled with too many keys making prefiexed lookup very slow ( https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNet.Mvc.Abstractions/ModelBinding/ModelStateDictionary.cs#L737 ).

Test project: https://github.com/Kukkimonsuta/MvcBindingTest

**Comment by Kukkimonsuta** [comment]
I've tried to fix the problem and somewhat succeeded without affecting functionality with indexing/caching the prefixed arrays:

https://github.com/Kukkimonsuta/Mvc/commit/59969dedcc4301c5e91419b31d1681ab692c44a9

I'm pretty sure it's not very effective memory-wise, but it affects only requests where the model state gets over 1000 entries.

![screenshot 2016-01-24 02 25 58](https://cloud.githubusercontent.com/assets/737093/12533879/e02d8b76-c241-11e5-98ad-838833b242c5.png)

**Comment by davidfowl** [comment]
Might be better to change the model state dictionary into a prefix tree. 

/cc @rynowak

**Comment by Kukkimonsuta** [comment]
With some more testing I've found that this only works when all values of the model are bound, otherwise it's falling back to the slow `PrefixedEnumerator`. This means once index is available, it needs to contain all possible prefixes:

https://github.com/Kukkimonsuta/Mvc/commit/f22a65817b2db1f2ef34293902a8d0ab892dc33c


@davidfowl That was my original thought too, however I was worried it could negatively affect performance of smaller requests. It's probably somewhat uncommon to have more than 1000 entries in the `ModelState` anyway. I'll be very happy either way if this gets fixed though.

**Comment by Eilon** [comment]
Model binding is generally used for form posts, which even on the rather extreme side would rarely have more than maybe 100 fields on it.

For binding thousands of items I would recommend using a formatter and serialization as it will likely be more efficient and produce better results.

@rynowak can you check this out and see that the behavior of these functions grows linearly?

**Comment by Eilon** [comment]
And when I say `linearly` I mean `close to linearly`.

**Comment by Eilon** [comment]
Closing because we don't think there's much action to take here. Posting forms with more than ~100 elements is extremely uncommon. Formatters are far better suited for handling large and complex data structures and should be preferred in this type of scenario.
