### ISSUE TITLE
ViewComponent param is null when passed to InvokeAsync()

### ISSUE THREAD

**Issue by esargent** [aspnet/Mvc#3970]
This is my first ViewComponent. Seems straightforward enough after reading Dave Paquette and the example on the aspnet docs site, but the parameter is always getting passed in as null, even though it isn't null from the call in the view.

In the view:

    <span>@Component.InvokeAsync("RoleName", roleId).Result</span>  *{roleId = '03bfa663-d484-404c-b9ed-cc16abc7af86' }*

the ViewComponent:

         public class RoleNameViewComponent : ViewComponent

        public RoleNameViewComponent(RoleManager<IdentityRole> roleManager)
        {
            foreach (var r in Enum.GetNames(typeof(MyRoles)))
            {
                roleNameDictionary.Add(
                    roleManager.GetRoleIdAsync(
                        new IdentityRole(r)).Result,
                    r);
            }
        }

         public async Task<IViewComponentResult> InvokeAsync(string roleId)    *{roleId=null}*
        {
            string name = string.Empty;
            if (roleId == null) { name = "null"; }
            else
            {
                if (!roleNameDictionary.TryGetValue(roleId, out name)) { name = "no match"; }
            }
            return Content(name);

        }

(I see this isn't the best design as the constructor gets called again with every call to the viewcomponent on that page. I'll fix that later. Although I wonder if it is really necessary to have a new instance of the ViewComponent for every call? But that's a separate issue.)

**Comment by ArieJones** [comment]
Is the roleId provided by the Model or the ViewBag or is it some type of javascript object?

**Comment by esargent** [comment]
@ArieJones It is calculated with Razor script from the Model.

The Model is `@model IEnumerable<Revelar.Models.ApplicationUser>`, which is the EF7 ApplicationUser. When debugging I can see that this is getting populated and the roleID is being determined correctly in the View when it makes the call to Component.InvokeAsync. 

Here are the details:

     @foreach (var item in Model)
    {
        <tr>
           <td>@Html.DisplayFor(modelItem => item.Email)</td>
           
            <td>
                @{
                    if (item.Roles.Count > 0)
                    {
                        string roleId = item.Roles.First().RoleId;
                        <span>@Component.InvokeAsync("RoleName", roleId).Result</span>
                    }
                    else
                    {
                        <span>None</span>
                    }
                }
    }

and the controller method, which is working,

            public async Task<IActionResult> Index()
        {
            var users = await _context.ApplicationUsers.AsNoTracking().Include(u=>u.Roles).ToListAsync();
            return View(users);
        }

The goal here is just to display a quick admin view of users and their application roles. And also to write a ViewComponent because I wanted to learn how to do that. ;-)

**Comment by ArieJones** [comment]
It doesn't look like you have done anything wrong here. I tried this out and on a local project and it worked without issue. 

I am on RC-1 Update 1 ... so it could just be a version issue that has been addressed ...

**Comment by esargent** [comment]
I'm using rc2-16770. Can you repo with that?

One of the things I noticed was a big refactor that eliminated the ability to call Invoke(), and now only allows InvokeAsync()  that could have impacted this, although it looks like the test coverage should have found something like this so I'm not sure that's it. And I didn't have any ViewComponents before I moved to RC2 so I don't have a baseline.

**Comment by rynowak** [comment]
We made some changes here that it looks like we forgot to announce, mostly around streamlining how VCs are invoked, and removing cases that seem like they should work, but don't.

Expect an official announcement post **soon**. /cc @pranavkm 

We removed `@Component.Invoke()` - view components almost always do async work, or render another view (which is async). We removed the sync invoke to streamline things and remove forever all questions about 'which one should I use?'

Additional, we removed overloading on parameters for VC methods, and change the style of `InvokeAsync` to use anonymous objects instead of `params object[]`. This eliminated a bunch of corner cases around conversions - since there's no overloading on VC methods, we know the exact types of parameters and can do conversions correctly.

So your call site should look like:
```
  <span>@await Component.InvokeAsync("RoleName", new { roleId = item.Roles.First().RoleId })</span>
```

**Comment by pranavkm** [comment]
My bad, I forgot to create an announcement thread as part of my change. Here's the [announcement](https://github.com/aspnet/Announcements/issues/145) and https://github.com/aspnet/Mvc/issues/3973 has discussions for the change.

**Comment by esargent** [comment]
@rynowak @pranavkm That fixed it. Thank you. And I think the change is good overall - it made sense immediately when I saw it, at least the async part.

It might be helpful to update the documentation from
      /// <param name="arguments">Arguments to be passed to the invoked view component method.</param>

Although that comes from the Interface, so maybe the concrete DefaultViewComponentHelper could override the comments to be specific about its expectations? That would have helped a lot. 'object' is a little vague.

BONUS: It would be great if it could operate similar to the way the DisplayAttribute works for view models, although that might be asking too much since you'd have to resolve the class in order to know what the specific ViewComponent is wanting. I'm not sure how far you can take intellisense with that scenario.

(Just saw the announcement post - do you want me to move this suggestion over there?)

**Comment by pranavkm** [comment]
@esargent  Filed https://github.com/aspnet/Mvc/issues/3974 to track the doc improvement.

**Comment by DaanTacoSchool** [comment]
Since Component.Invoke is removed (is now InvokeAsync) how is it possible to call this component explicitly NOT async? since that is not possible in my current situation.

**Comment by Eilon** [comment]
@DaanTacoSchool this is a pretty old issue - can you file a new issue describing what you're trying to do? That is, why do you need to call the component synchronously?

**Comment by DaanTacoSchool** [comment]
For one, that the method is called from synchronous code directly, but
equally important, it is really difficult to unit test this.

Op 18 sep. 2017 05:18 schreef "Eilon Lipton" <notifications@github.com>:
