### ISSUE TITLE
AuthorizationContext conflicts with type in Microsoft.AspNet.Authorization

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#3979]
We really shouldn't be conflicting with our own system. Can we rename the AuthorizationContext in MVC to FilterAuthorizationContext or something?

/cc @rynowak @Eilon @danroth27

**Comment by davidfowl** [comment]
Scratch that, we have to rename it https://github.com/aspnet/Security/issues/670#issuecomment-174341114

**Comment by davidfowl** [comment]
I wonder if we should have an `MvcAuthorizationHandler<TRequirement>`:

```C#
public abstract class MvcAuthorizationHandler<TRequirement> : AuthorizationHandler<TRequirement, Microsoft.AspNet.Mvc.Filters.AuthorizationContext> where TRequirement : IAuthorizationRequirement
{

}
```

/cc @blowdart

**Comment by blowdart** [comment]
Why would mvc a handler all of its own? We worked hard not to link it to mvc.

It's not so much a clash as an actual design decision. It won't be that often you need the mvc specifics. Auth on route info or request properties is odd.

**Comment by davidfowl** [comment]
By default the resource that MVC passes to the AuthHandler its own AuthorizationContext (which is actually quite handy, see the issue linked). This would just be a shortcut for that.

**Comment by blowdart** [comment]
(So basically no. We should not start having handlers for each framework. The context rename I don't care about though)

**Comment by davidfowl** [comment]
@blowdart Sure we don't have to have a type, the user can just declare the MVC specific resource. No biggie.

**Comment by Eilon** [comment]
So let's rename `Microsoft.AspNetCore.Mvc.Filters.AuthorizationContext` to `Microsoft.AspNetCore.Mvc.Filters.AuthorizationFilterContext`.
