### ISSUE TITLE
AuthorizeFilter should allow passing a string policyName

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#3980]
Seems like I can only pass concrete policies to the `AuthorizeFilter` in MVC. If I wanted to add a global filter with a specific policy that I had configured in my auth system I can't reuse it without resolving the `AuthenticationOptions.PolicyMap` and digging it out myself. Seems like this should be easier.

**Comment by brockallen** [comment]
Dup of: https://github.com/aspnet/Mvc/issues/3708

**Comment by Eilon** [comment]
Backlog

**Comment by rynowak** [comment]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L74

We actually did this
