### ISSUE TITLE
Simplify functional testing with MVC

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#3981]
Customers that try to test MVC always run into the fact that they need to override the `IApplicationEnvironment`. 

See https://github.com/mattridgway/MvcIntegrationTests#failing-tests

Our MvcFixture solves this nicely (it can even be reduced further). We should expose some type of helper to make this easier.

https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.FunctionalTests/MvcTestFixture.cs#L51-L72

**Comment by Eilon** [comment]
Backlog
