### ISSUE TITLE
Compile failure on controller/code should not crash entire website

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Mvc#3985]
I add new controller/code during runtime, that code contains something that makes the compilation failed. I believe the framework should not crash the whole website due this error.
![image](https://cloud.githubusercontent.com/assets/12871379/12552596/01d29ef6-c373-11e5-9149-b71cad353707.png)

It should be error at least when browser request to the new controller.
This will makes website more robust.

**Comment by davidfowl** [comment]
@andrew-vandenbrink Can you make a working repository in a github issue so we can take a look at what you did?

**Comment by andrew-vandenbrink** [comment]
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace CodeKamer.BrinkEngine.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
//THIS SLASH BELOW WILL BROKE THE WHOLE WEBSITE
/
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}
```

I just add "intentionally" broken code to the application during runtime and get that 500 error.

**Comment by andrew-vandenbrink** [comment]
The idea is I can just add/update/remove controller/code when the website is deployed.
A compile error on one controller file should not broke the whole website.

At this moment it is quite hard to recover from compile error, once I upload broken controller to the website, it's end of story.
If i upload broken HomeController and its only broke Home, I can still have another page to fix the controller and recover from compile error.

**Comment by davidfowl** [comment]
> The idea is I can just add/update/remove controller/code when the website is deployed.
A compile error on one controller file should not broke the whole website.

At this moment it is quite hard to recover from compile error, once I upload broken controller to the website, it's end of story.
If i upload broken HomeController and its only broke Home, I can still have another page to fix the controller and recover from compile error.

That's not going to be fixed. Thats' how C# works. The entire project is compiled once. If you're looking for something more custom that'll be some work (and it's not trivial either). You'd effectively be treating controllers like views, they'd each get their own assembly. Once you start down that path then you need to figure out how they reference each other (and you need to support cycles too).

**Comment by Eilon** [comment]
Yup, unlike scripting languages in C# everything is compiled into one assembly. If any part of the project doesn't compile, it's game over. (Razor views are a slightly different story.)

**Comment by andrew-vandenbrink** [comment]
@davidfowl @Eilon I upload the same text with name TestViewComponent.cs

It shows compile errors on visual studio but not crashing the whole website. 

![image](https://cloud.githubusercontent.com/assets/12871379/12607206/65a3a5d6-c4d3-11e5-8150-c90f7cd5b5be.png)

**Comment by andrew-vandenbrink** [comment]
Therefore it's should be possible to not crash the whole website when I upload broken controller class.

**Comment by Eilon** [comment]
Depending on the project's settings there might already be an existing compiled version of the site that's running.
