### ISSUE TITLE
Inconsistent log message formatting due to different helper frameworks

### ISSUE THREAD

**Issue by Mertsch** [aspnet/Mvc#3986]
Notice how the time is formatted once with ```.``` and once with ```,```
Maybe the asp.net teams can find a way to share the logger helper code and have a concise way of localizing error messages?

https://github.com/aspnet/Mvc/blob/25eb50120eceb62fd24ab5404210428fcdf0c400/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreLoggerExtensions.cs
produces the following output
```
info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
      Executed action XXX in 0.0141ms
```
while
https://github.com/aspnet/Hosting/blob/e62ceb852827d386b492abc9cc6801b1a8c70263/src/Microsoft.AspNetCore.Hosting/Internal/HostingLoggerExtensions.cs
```
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0,0797ms 200 application/json; charset=utf-8
```

**Comment by Eilon** [comment]
Error messages in exceptions localized, but log messages are at present deliberately not localized. The idea is that error messages are often immediately seen by the caller and thus the current locale is more likely to apply to that person. However with logs it is often the case that the reader of the log is not the person immediately seeing the site, so for the moment we decided to avoid figuring out how to localize it and are sticking with just English.

So I think the interesting case here is why is Hosting returning a localized value - it should not.

I logged https://github.com/aspnet/Hosting/issues/597 to track the fix there.
