### ISSUE TITLE
Need way to lookup controller, actions and HTTP verbs for a URL

### ISSUE THREAD

**Issue by ghost** [aspnet/Mvc#3994]
It would be very useful if one could dynamically lookup what controller, action(s) and HTTP verb(s) that a URL can map to according to configured routing etc. The lookup should work inside both middelware and mvc controllers.

My use cases:
1) Generating a custom accept header for HTTP HEAD with list of other HTTP verbs that may be used for the current endpoint (needed for jsonapi standard implementations).
2) Generating hypermedia.

**Comment by bluemmc** [comment]
BTW: I assume this functionality is missing and not hidden away somewhere. Please let me know if I am wrong?

**Comment by davidfowl** [comment]
Seems like you would need to sit in front of routing to get any information like that (since mvc is built on top of routing).

I'd like to understand the use cases more. What would the pseudo code look like for each of those?

**Comment by danroth27** [comment]
We have some introspection support via ApiExplorer, which enables scenarios like generating Swagger documents. You can find a sample here: https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ApiExplorerWebSite. Let us know if it meets your needs.

**Comment by bluemmc** [comment]
@davidfowl I would like more or less the reverse of IUrlHelper that I can get injected where I need it (controller or middleware). Giving a URL (REST endpoint), I would like to look up what routing knows about the Controller type and the list of matching C# method(s) along with their HTTP method (GET/POST/DELETE/PUT/PATCH/HEAD etc.). I would for instance like to use it to implement a header with a list of allowed HTTP verbs when issuing a HEAD request to a REST resource as noted in section "How can I discover a resource's supported actions?" for the JSONAPI standard on  "http://jsonapi.org/faq/". My best idea would be to create middleware which looks at the request, extracts the URL and add a header with allowed HTTP methods for the URL to the response using the inverse IUrlHelper.

**Comment by bluemmc** [comment]
@danroth27 Thank you very much for the ApiExplorer tip. It seems very complex though and I have yet to understand how to use (if possible) it as a kind of reverse IUrlHelper that I need as noted above. It is also a very big hammer for this relatively smaller need that I am concerned might affect performance or have some other negative effect if I use it on regular basis when accepting normal requests in production as It appears the primary use case for ApiExplorer  is way different from mine.

**Comment by Eilon** [comment]
The ApiExplorer should still come in handy here - it has the information you need to determine which URL patterns are available. What's missing is the component that can match a "candidate URL" to the list of available URL patterns in the ApiExplorer. You'd need to run the "candidate URL" through the routing system to see which route pattern matched it, and then look up that pattern in ApiExplorer's list, and from that see which verbs are allowed.

Moving this to the backlog as we are not planning on building first class support for this, but we will reconsider in the future.
