### ISSUE TITLE
Html.JavaScriptStringEncoder.JavaScriptStringEncode could be shorter

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#4001]
I don't think there is such usage of `JavaScriptStringEncoder` in a view outside of just encoding a string hence calling `JavaScriptStringEncode`. I think it could be shorter for the sake or readability. If a user really wants to use the service they can still inject it.

`@Html.JavaScriptStringEncode` would be an improvement.

Or another helper like `@JavaScript.Encode()`

**Comment by rynowak** [comment]
This is actually here for the case where you're writing another extension method on `IHtmlHelper` that needs to encode something. You're in a static method, so you don't get DI (hence `IHtmlHelper` exposing its dependencies).

I'd suggest writing an extension method that does what you want :trollface:.

**Comment by Eilon** [comment]
@sebastienros can you add this helper method? I think I'd add it as an extension method rather than adding it to the `IHtmlHelper` interface.

@dougbu thoughts on interface vs. extension method?

**Comment by Eilon** [comment]
Nevermind, not going to do this.

**Comment by blowdart** [comment]
#4033
