### ISSUE TITLE
Bug: PartialView returns sometimes the whole page:

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/Mvc#4002]
I have written a mvc webapp using mvc6.
sometimes, in very seldom, when the action tries to return some partialview, the server will return the whole page except <HTML Directive>, meaning header+body, just like View() ActionResult. If I refresh the page, it will works normally again.
It happens very seldom. Sorry for having no stack information for you to debug.
Could You please help to check?
Thanks in advance.

**Comment by rynowak** [comment]
We're going to need to a code sample to investigate this. Do you have a repo we could take a look at?

**Comment by Eilon** [comment]
@kichalla can you poke around the code to see if there's any obvious way this could happen? We don't have a repro but please have a look to see if there are any suspicious code paths.

**Comment by kichalla** [comment]
> the server will return the whole page

I am guessing by this you mean that a layout is being applied to the partial view...layouts are not supposed to be applied to partial views...@kennywangjin, is this what you are noticing?

**Comment by Eilon** [comment]
Layouts can be applied to partials if they are explicitly set in the partial. But the layout of an "outer page" of course shouldn't be automatically applied to partials (or anything else, aside from the page that specified it).

**Comment by kichalla** [comment]
@kennywangjin It would be helpful to investigate if you can give us a repro. Feel free to re-open it with additional details and repro code.
