### ISSUE TITLE
Missing the client-side `DateModelValidator` from MVC 5

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4005]
When we moved client-side validation forward, the `DateModelValidator` got left behind. We have the equivalent of the similar `NumericModelValidator` (`NumericClientModelValidatorProvider` in the new world). Might need to add this code to MVC Core 1.0.

Perhaps was `DateModelValidator` was left behind on purpose e.g. because `type="datetime"` works better in modern browsers or because locale-specific validation remains difficult in JavaScript, especially with the Validation package we use. @ajaybhargavb any history here?

**Comment by ajaybhargavb** [comment]
The `NumericClientModelValidator` was added as part of https://github.com/aspnet/Mvc/issues/2817. And as per @pranavkm's comment https://github.com/aspnet/Mvc/pull/2950#issuecomment-129649961, I don't think we left out `DateTime` on purpose. I guess I just didn't create an issue for the follow-up.

**Comment by ajaybhargavb** [comment]
>because type="datetime" works better in modern browsers or because locale-specific validation remains difficult in JavaScript.

Could be the reason we didn't do it in the first place.

**Comment by ctolkien** [comment]
I can offer a an end user perspective. Client side date validation has relied on parsing the string into the `new Date(x)` constructor. All browsers use the Month / Day / Year format - which is valid format in the USA and nearly nowhere else.

That leads you down the path of Globalize.js, cldr, trying to get a hold of the appropriate cldr data and including just the right amount of localisation bits that you need. A colossal pain in the butt.

If this does make a comeback, I would love for it to not follow the old model.

**Comment by Eilon** [comment]
Several years ago Microsoft released a bunch of globalized parsers that could be used with jQuery Validation, though those seem to have been supplanted by CLDR. I've never used CLDR so I couldn't say what it's like to use it.

But yeah, date parsing is just about the most complex "simple" data there is...

**Comment by Eilon** [comment]
Moving this to backlog as I don't think we'll have time to think through the complexities of the design in the time we have left for this release.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
