### ISSUE TITLE
Request for guidance. Where do I find the value for UIHint() in a custom tag helper?

### ISSUE THREAD

**Issue by gkochanowsky** [aspnet/Mvc#4006]
I'm trying to create a custom tag helper and it appears that I can use `base.For.Metadata.DataTypeName` to determine the attribute values for model property decoration `[DataType(DataType.Date)]`, I have been unable to figure out how to retrieve the value for `[UIHint("somehint")]`.

Please advise.

**Comment by dougbu** [comment]
@gkochanowsky a `[UIHint(...)]` attribute is used to set `ModelMetadata`'s `TemplateHint` property.

**Comment by gkochanowsky** [comment]
Thanks @dougbu!
