### ISSUE TITLE
Strange behaviour with Routing 

### ISSUE THREAD

**Issue by wolfgangschneider** [aspnet/Mvc#4008]
Hi

I'm working on an asp.net core 1.0 project everything looks fine and I like it. But most of the time I spend to understand Routing. Its a nightmare or I'm to stupid to understand it. One of my challenges is: 
Using Attribute routing:

    [Route("[controller]")]
    public class AOPController : Controller
    {
        [HttpGet("{year:int}/{aopid:int}",Name ="A99")]
        public IActionResult Index(int year,int aopid)
        {
                 .......
        }

        [HttpPost]
        public IActionResult GetAop(AOPViewModel vm)
        {
             return RedirectToAction("Index", new {year=vm.Year, aopid = vm.AopId });  
        }
    }

This works like expected:
* When I call the controller /AOP/2016/2  the index(int,int) function will be called
* When I submit the Form GetAop is called, and redirect to /AOP/2016/22 this will call the index(int,int) function

Ok. But when I add a second Index method        
    
    [HttpGet()]
    public IActionResult Index()
    {
           .......
    }

it never works like before
* When I call /AOP the new Index() Function -> fine
* When I call the controller /AOP/  the index() function will be called
* When I call the controller /AOP/2016/2  the index(int,int) function will be called

* When I submit the Form GetAop function is called, but now it redetect to **/AOP?year=2016&aopid=12  and this will call the index()**

What Im doing wrong ? However adding a method should not change the behavior from an other method.

B.R. Wolfgang

**Comment by rynowak** [comment]
> However adding a method should not change the behavior from an other method.

That's not an accurate statement unfortunately. Constructs like `RedirectToAction("Index", ...)` are based on names of actions and controllers. By adding another candidate for `action = "Index"` - you're giving the routing system two viable routes to choose from.

If you gave `Index()` a different method/action name than `Index(int, int)` this wouldn't happen. You can also use `RedirectToRoute("A99", ...)` since you gave that action a route-name.

---

That said, this still looks like the wrong behavior. @ryanbrandenburg fixed some bugs in this area not too long back, I'm wondering if we broke something. I'll try to reproduce this on latest bits.

**Comment by rynowak** [comment]
Are you running on RC1? I'm not seeing this problem in latest/RC2.

**Comment by wolfgangschneider** [comment]
Thanks for your answer

I am running 1.0.0-rc1-final  dnvm  upgrade find no rc2

*  using RedirectToRoute  solve the issue in the controller but  adding the Index() function also breaks all @Url.Action)  functions. the Url.Action now generate a Query string,  before it generates a Rest like url. I chaned all to Url.RouteUrl

* I don't want to use  different names because I want to achieve the goal that AOP/ display everything and AOP/2016/12 display filtered.  I also played with optional parameter but had no success

* Using  [HttpGet("[controller]/{year:int}/{aopid:int}", Name ="A99")]  cause an 404  

.... That's not an accurate statement unfortunately ....  In my opinion it can't  be that adding a function with the wrong name destroy a whole Application. RederictToAction and Url.Action   produce different urls in case of function names. I also wondering why Url filed in in the browser are working but this two function didn't  (if this is fixed in RC2 I can wait)

BTW: Using the [controller] Attribute destroy default mapping from   app.UseMvc in Starup.cs I'll post this as ab separate issue.

**Comment by rynowak** [comment]
> BTW: Using the [controller] Attribute destroy default mapping from app.UseMvc in Starup.cs I'll post this as ab separate issue.

This is intended. Attribute routing and conventional routing don't overlap. Actions reachable via attribute routes aren't reachable via conventional routes.


> I don't want to use different names because I want to achieve the goal that AOP/ display everything and AOP/2016/12 display filtered. I also played with optional parameter but had no success

The action/method name really has nothing to do with the URL if you're using attribute routing.


> Using [HttpGet("[controller]/{year:int}/{aopid:int}", Name ="A99")] cause an 404

Route attributes concatenate between the controller and action. Use `/` or `~/` at the beginning of a route template to turn off this behavior.

```
[Route("[controller]")]
public class FooController : Controller
{
    // concats to [controller]/[controller]/Values
    // expands to Foo/Foo/Values
    [HttpGet("[controller]/Values")] 
    public IActionResult GetValues()
}
```

**Comment by wolfgangschneider** [comment]
Thanks
>This is intended. Attribute routing and conventional routing don't overlap. Actions reachable via attribute routes aren't reachable via conventional routes

Ok got it, How to set default page with Attribute Routing?
> The action/method name really has nothing to do with the URL if you're using attribute routing.

Got it now- thanks
>In your scenario the longer route  [controller]/{year:int}/{aopid:int}  should be chosen.

That s, what I don't understand

What I have to do that /aop?year=2016 and aop/2016 raouts to the same function ?

**Comment by rynowak** [comment]
> That s, what I don't understand
> What I have to do that /aop?year=2016 and aop/2016 raouts to the same function?

This is a bug that we fixed for RC2. 

If you want to be explicit you can give your shorter route a larger value of Order. This should force the routing system to try the longer route first.
```
[Route("[controller]")]
public class AOPController : Controller
{
    [HttpGet(Order=1)]
    public IActionResult Index()
    {
             .......
    }

    [HttpGet("{year:int}/{aopid:int}")]
    public IActionResult Index(int year, int aopid)
    {
             .......
    }
}
```

**Comment by wolfgangschneider** [comment]
Thanks a lot
