### ISSUE TITLE
~ TagHelper

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4009]
Using Azure Storage, is it possible to extend the ~ TagHelper on `<img src="">` tags so it goes to a CloudStorage url like `http://127.0.0.1:10000/devstoreaccount1/` ?

Or what is the recommended approach to get dynamic url locations for images?

**Comment by NTaylorMullen** [comment]
You could add an img `TagHelper` that rewrites the `src` attribute. I did something similar in one of my SOCAL code camp talks where I made img tags src's redirect to potential "cdn"s: 

https://github.com/NTaylorMullen/SOCAL_CodeCamp_TagHelpers_2015/blob/master/TagHelperDemo/TagHelpers/ImgTagHelper.cs

**Comment by Bartmax** [comment]
Thank you @NTaylorMullen 

I ended up using this:

```
[HtmlTargetElement("img")]
    public class ImgTagHelper : TagHelper
    {
        private readonly string BASEPATH = "upfiles";
        private readonly IFileRepository fileRepository;
        public override int Order => int.MinValue;
        public ImgTagHelper(IFileRepository fileRepository)
        {
            this.fileRepository = fileRepository;
        }

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            var match = $"~/{BASEPATH}";
            var srcAttribute = output.Attributes["src"];
            var src = srcAttribute.Value.ToString();
            var repositoryRootFolder = await fileRepository.GetRootAsync();
            if (!string.IsNullOrWhiteSpace(repositoryRootFolder) && src.StartsWith(match))
                srcAttribute.Value = src.Replace(match, repositoryRootFolder);
        }
    }
```

can't said I'm happy with the outcome tho. too app-specific, magic strings and `IFileRepository` dependent. I will review the design later to see if I can make it more like a 'generic' thing.
