### ISSUE TITLE
Too much string allocation in Model Binding

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4016]
With a large model binding operation (~100 form fields) - MVC is allocating way too many strings for binding.

Across 3000 requests, there's about 267mb of string being allocated. 41mb of that is the parsed representation of the form data. The other 226mb is MVC's overhead.

![image](https://cloud.githubusercontent.com/assets/1430011/12690175/81dc3776-c696-11e5-9148-6d7b1bf5964e.png)

**Comment by SajayAntony** [comment]
What test are you using to get measure this? Do you have this in the [performance repo](https://github.com/aspnet/Performance/tree/dev/testapp)?

**Comment by rynowak** [comment]
These are here: https://github.com/rynowak/mvc-sandbox/tree/master/workloads/BigModelBinding

**Comment by SajayAntony** [comment]
Nice. @sivagms we need to work with @rynowak @troydai to get this into the perf repo :)

**Comment by rynowak** [comment]
In order of importance, underlying issues here:

1). `PrefixContainer` allocates a comparer and a copy of the key for each lookup. This can happen 4x N / request, where N is the number of keys. Since we're using binary search, we likely don't need the allocation, we could iterate from the point of the first binary search. See comment here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/PrefixContainer.cs

Do we even need `PrefixContainer`? We could also likely do much better than binary search by using a 'real' prefix tree here if we care about lookup speed.

2). We generate lots and lots of strings for model names `ModelNames.CreatePropertyModelName` - should we cache these? Should we choose a different representation other than string?

3). Using jQuery Form Value Provider duplicates every key when using form data (can we remove this as a default?)

**Comment by benaadams** [comment]
Hopefully halved strings created by form parsing with last commit of https://github.com/aspnet/HttpAbstractions/pull/550

**Comment by rynowak** [comment]
That will definitely help, but unfortunately MVC is an order of magnitude worse than that code :scream:

**Comment by benaadams** [comment]
Update, with captured data from recent changes plus post form reader+valuetask analysis 30k requests big model

String.Concat (2) allocs

![string-concat](http://aoa.blob.core.windows.net/aspnet/string-concat.png)

StringBuilder.ToString

![stringbuilder](http://aoa.blob.core.windows.net/aspnet/stringbuilder.png)

String.Concat (3) allocs

![stringconcat-3](http://aoa.blob.core.windows.net/aspnet/string-concat-3.png)

**Comment by rynowak** [comment]
We're looking into some thorough design measures here to get this number under control. I don't expect any immediate action here.

**Comment by Eilon** [comment]
@rynowak parking on your plate until you make a decision here.

**Comment by Eilon** [comment]
Moving to 1.0.0.

**Comment by Eilon** [comment]
Closing because there are no plans to make further improvements in this area.
