### ISSUE TITLE
Namespace confusion on imported "wrap" library

### ISSUE THREAD

**Issue by dythim** [aspnet/Mvc#4021]
I'm attempting to create a new ASP.NET front end for our existing Silverlight application and ran into what seems like a bug for imported projects.  It seems like if there is a namespace "collision" -- the same namespace in two referenced assemblies, ASP.NET does not aggregate all the classes across all referenced assemblies.

We have a `MyApp.DataAccess.Security.User` object which previously lived in a `MyApp.DataAccess.Security.dll` project.  It was extracted so that we could move it to a portable class library, but the namespace remained the same.  It now lives in `MyApp.DataModel.dll`.
I generated "wrap" project.json files for each of those libraries (`MyApp.DataAccess.Security.dll`, `MyApp.DataModel.dll`) and see both of them as referenced by the ASP.NET project.  
When I type `new MyApp.DataAccess.Security.` I only get classes from the `MyApp.DataAccess.Security.dll` and I do not get `MyApp.DataAccess.Security.User`.  Entering the full name only gives me a compile error.

Any help would be greatly appreciated.

I'm on VS 2015 Update 1 Community, with ASP.NET 5 RC1-Update 1.  I did not see a known issue filed against this -- sorry if I missed it.

**Comment by Eilon** [comment]
@dythim can you log this in the https://github.com/aspnet/dnx/issues/ repo? This isn't specific to MVC.
