### ISSUE TITLE
Route to generic action/controller by list of types

### ISSUE THREAD

**Issue by newsash** [aspnet/Mvc#4022]
Is it possible to somehow bind following action to `/api/{category}/send/{type}` if list of types by category is available at service configuration?
``` c#
public async Task<IActionResult> Send<TModel>(TModel model)
{
    //...Authorization...
    return new ObjectResult(await messageBus.Send<TModel>(model));
}
```

**Comment by Eilon** [comment]
There's no built-in way, but perhaps @rynowak can think of something with ApplicationModel where something like that could be hacked up?

**Comment by newsash** [comment]
@rynowak Thank you for this link, I'll try it. I want to use one generic action/controller for a bunch of model types with a sensible routing and to utilize all pros of model binding without need to create separate action/controller for each model type.

**Comment by newsash** [comment]
Not tested properly yet, but seems to work. However, [FromServices] attribute doesn't work in this controller, I had to use constructor injection.

``` c#
    public class CustomControllerTypeProvider : DefaultControllerTypeProvider
    {
        private IEnumerable<Type> queryTypes;

        public CustomControllerTypeProvider(
            IAssemblyProvider assemblyProvider, 
            IEnumerable<Type> queryTypes) : base(assemblyProvider) 
        { 
            this.queryTypes = queryTypes;
        }

        public override IEnumerable<TypeInfo> ControllerTypes
        {
            get
            {
                return base.ControllerTypes.Concat(queryTypes.Select(type =>
                    typeof(QueryController<>).MakeGenericType(type).GetTypeInfo()));
            }
        }
    }
```

``` c#
    public class QueryRoutingConvention : IApplicationModelConvention
    {
        private Regex regex = new Regex(@"Modules\.(.*)\.Contract\.Queries\.(.*)");

        public void Apply(ApplicationModel application)
        {
            var queryControllers = application.Controllers.Where(cm =>
                cm.ControllerType.IsGenericType &&
                cm.ControllerType.GetGenericTypeDefinition() == typeof(QueryController<>));

            foreach (var controller in queryControllers)
            {
                var queryType = controller.ControllerType.GetGenericArguments()[0];
                var matches = regex.Match(queryType.FullName).Groups;
                var template = $"/{matches[1].Value}/query/{matches[2].Value}";

                var attributeRouteModel = new AttributeRouteModel();
                attributeRouteModel.Template = template;

                controller.AttributeRoutes.Add(attributeRouteModel);
            }
        }
    }
```

**Comment by rynowak** [comment]
> Not tested properly yet, but seems to work. However, [FromServices] attribute doesn't work in this controller, I had to use constructor injection.

Take a look at the action parameters `ParameterModel` are those populated as you would expect?

**Comment by newsash** [comment]
@rynowak something strange happened: to test population of ControllerParameters I switched back from constructor injection to property injection, and now it works. The whole ControllerModel populated as I expect (similar to other controllers).

**Comment by Eilon** [comment]
Looks like this question was answered. If you have any further questions please let us know.
