### ISSUE TITLE
Is there a way to get a list of controllers at runtime (ControllerActionDescriptor)?

### ISSUE THREAD

**Issue by KlausEvenEnevoldsen** [aspnet/Mvc#4023]
We are trying to build a menu system which is dynamic and not based on some sort of sitemap.

We would like to create some custom attributes which we could put on controllers and on actions. These attributes (along with attributes from ASP.NET Identity) would control whether a user should be able to see a menu item and also how the menu items are organized in the menu system (grouping, ordering, etc).

In order to make such a dynamic menu system, we would need access to a list of controllers (with actions) to reflect on the custom attributes.

Is there a way to get a list of the controllers in a given web application?

When looking in the source code of MVC it appears that it is the class Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor that I need to have a list of instances of.

**Comment by ivaylokenov** [comment]
@KlausEvenEnevoldsen There is [ActionDescriptorCollectionProvider](https://github.com/aspnet/Mvc/blob/25eb50120eceb62fd24ab5404210428fcdf0c400/src/Microsoft.AspNetCore.Mvc.Core/Internal/ActionDescriptorCollectionProvider.cs) registered in the services collection by the MVC framework. You can get in your code by requesting `IActionDescriptorCollectionProvider` from the services and analyze it for your needs. All items of `ControllerActionDescriptor` type in the provided collection contain information about controllers and actions. You can check it out as it may work for your particular case.

**Comment by KlausEvenEnevoldsen** [comment]
@ivaylokenov Thank you! It looks like something we could use. I spent a few hours looking in the repository, but I must have missed it.
