### ISSUE TITLE
Middleware not called for the API route

### ISSUE THREAD

**Issue by AkbaraliShaikh** [aspnet/Mvc#4029]
I'm trying to create the middleware which should execute before every request made to the controller (API),

But i'm facing the problem, when there is a route which executes the action in that case my middleware not going to execute, it only gets executed for those routes where there is no action is pointing.

app.UseMvc();
app.MapWhen(=>.Request.Path.Value.Contains("/"), _ => _.UseRequestLogger());

when i hit the URL "http://localhost:5000/rest/api/1/" it executes because there is no action for this route, if i hit the URL "http://localhost:5000/rest/api/1/users" this will not call middleware it calls my api action method

But I'm looking for an solution before each action the middleware has to be executed.

please help me here.

Thanks in advance.

**Comment by BrennanConroy** [comment]
Switch the two lines of code, if a middleware handles the request then it doesn't get passed to the next middleware.

**Comment by AkbaraliShaikh** [comment]
I have tried it by switching, in that case also the same behavior, Can you please suggest me the way, how I can do it,

I want to execute my middle ware code for all the routes before every API is called.

**Comment by Eilon** [comment]
@AkbaraliShaikh can you show the exact code you have? The code you showed doesn't compile due to syntax errors.

**Comment by AkbaraliShaikh** [comment]
@Eilon This is my startup code, My code compiles fine, what error do you see in my above code

 public static void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMvc();
            app.MapWhen(_=>_.Request.Path.Value.Contains("/"), _ => _.UseRequestLogger());
            app.UseIISPlatformHandler();

            using(var services = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
            {
                services.ServiceProvider.GetService<BugTracDbContext>().EnsureSeedData();
            }

        }

**Comment by Eilon** [comment]
It's worth noting that `UseIISPlatformHandler` needs to be called first, though I'm not sure that that affects this at all.

**Comment by Eilon** [comment]
@Tratcher any thoughts on this?

**Comment by AkbaraliShaikh** [comment]
When I switched below two lines, after that middleware is getting called but not controller action method

`public static void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.MapWhen(_ => _.Request.Path.Value.Contains("/"), _ => _.UseRequestLogger());
            app.UseMvc();
            app.UseIISPlatformHandler();

            using(var services = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
            {
                services.ServiceProvider.GetService<BugTracDbContext>().EnsureSeedData();
            }

        }`

**Comment by Tratcher** [comment]
Map creates branches, matched requests do not continue on to the rest of the pipeline. Try this instead:
```
app.Use((context, next) =>
{
  if (SomeCondition)
  {
    // Do some work
  }
  return next();
});
app.UseMvc();
```
Note calling next is optional, you could also handle the response directly.

**Comment by AkbaraliShaikh** [comment]
How can I create a handler and register which can execute before every request?  Like DelegateHandler in Web API.

I want to execute the handler e.g: if the URL starts with "/rest/secure/", How Can I do this?

**Comment by AkbaraliShaikh** [comment]
@Tratcher  Thank you, for now using like below:

```
`app.Use((context, next) =>
            {
                if((context as DefaultHttpContext).Request.Path.StartsWithSegments("/rest/api/1"))
                {
                    //somework
                }

                return next();
            });`
```

**Comment by Tratcher** [comment]
FYI: drop the cast to DefaultHttpContext. The normal HttpContext should be adequate.

**Comment by AkbaraliShaikh** [comment]
@Tratcher : thank you, last question, except app.use() there is no way to do this ? middleware ?

**Comment by Tratcher** [comment]
app.Use is just the simplest form of middleware. A full middleware class can do the same thing. See https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.HttpOverrides/HttpMethodOverrideMiddleware.cs#L32

**Comment by Eilon** [comment]
Looks like this question was answered. If you have any further questions please let us know.

**Comment by AkbaraliShaikh** [comment]
Yes, I have the below middle ware class which is working fine now:

```
public class RequestValidatorMiddleware
    {
        private readonly RequestDelegate _next;

        public RequestValidatorMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task Invoke(HttpContext context)
        {
            if (context.Request.Path.StartsWithSegments("/rest/api"))
            {
                //somework
            }

            await _next.Invoke(context);
        }
    }
```

But It only woks fine if I have to register it before app.UseMvc(), if i register after it, looks like the mvc pipeline override the behavior ?

works:
```
 app.UseRequestValidator();
 app.UseMvc(); 
```

does not work:
```
app.UseMvc();
app.UseRequestValidator();
```

**Comment by rynowak** [comment]
Registration of middleware is ordered. So anything you register before MVC will run before MVC.

MVC "handles" the request if it matches a URL that MVC can handle. Anything you register after MVC will only handle the request if MVC fails to match the URL.

**Comment by AkbaraliShaikh** [comment]
@rynowak  Thank you, its very helpful information.
