### ISSUE TITLE
Highlight sterling performance work

### ISSUE THREAD

**Issue by benaadams** [aspnet/Mvc#4030]
I'd just like to extend my personal thanks to @rynowak and team for the amazing performance strides being made in MVC.

**Comment by Eilon** [comment]
cc @DamianEdwards @SajayAntony 

:smiley_cat:

**Comment by Eilon** [comment]
@danroth27 should we move this to the Backlog? :smile:

**Comment by Eilon** [comment]
Oh, and where do I log the same bug but to thank @benaadams for all his hard work and contributions???

**Comment by rynowak** [comment]
:blush:

**Comment by SajayAntony** [comment]
:+1:

**Comment by ctolkien** [comment]
:fireworks:  :+1:  :heart_eyes:

**Comment by PureKrome** [comment]
![awesome](https://31.media.tumblr.com/751b9113f1b9084c2858d9ca8129c260/tumblr_inline_n4rt6dgDo51solpjm.gif)

**Comment by benaadams** [comment]
@Eilon my great hope is one day people will move past the defeatist argument that it doesn't matter because "my database is slow". That's like saying I might as well use php in interpreted mode because "my database is slow". There is so much more potential to the platform!

We were going custom for the performance; but we've come back to aspnet because of the improvements in Kestrel; and now we are coming back to to the full stack for the great strides in performance and direction of MVC. So I just wanted to say thank you.

Also saves us a bunch of work :wink:

**Comment by benaadams** [comment]
It begins... https://stevedesmond.ca/blog/performance-is-paramount /cc @stevedesmond-ca

**Comment by MJomaa** [comment]
:+1: :yum:

**Comment by stevedesmond-ca** [comment]
LOL @ the timing of this -- I was trying to find the time to finish that post for days!

But seriously, thanks! I wish I had the cycles to contribute more directly, but you're all doing great work!

**Comment by Eilon** [comment]
@stevedesmond-ca great blog post!

**Comment by stevedesmond-ca** [comment]
:blush:

**Comment by Eilon** [comment]
Closing because this is an old discussion. We always appreciate the kind words 😄
