### ISSUE TITLE
How to set up default route for WebApi Controllers in MVC 6?

### ISSUE THREAD

**Issue by giancarloa** [aspnet/Mvc#4040]
Hello...

So it appears that in MVC 6 there is no difference between MVC controllers and WebApi controllers. They both derive from the same base class and anything that applies to one applies to the other, at least that's my understanding. However I was wondering if there's any way to set up a default route for WebApi controllers that is different from the default route set up for MVC controllers? In my startup class I have the following code:

 app.UseMvcWithDefaultRoute(); 

This sets up the default route for all controllers, both MVC and WebApi. If I have a WebApi controller decorated with a Route(api/[controller]) attribute, then that overrides the default route. However I don't want to do this in all of my WebApi controllers because that code will always be the same. Instead I would prefer to set up a default route for WebApi controllers. But I am not sure how to do this since in MVC6 both categories of controllers are considered to the same, such that each does not appear to have it's own sort of routing pipeline. I guess I could use a base class for all my WebApi controllers and the route attribute used in the base class. But I was wondering if there's another way. Any ideas? This is one of those things I miss about MVC6, how each category of controller could have its own routing defined independently. Thanks

**Comment by Eilon** [comment]
@giancarloa using a base class is certainly one way to do it.

Another option is to use MVC's new Application Model feature that enables you to create "conventions" that dictate certain behaviors in MVC. We have a [sample](https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ApplicationModelWebSite) that shows application model in general, and with the list of [built-in conventions](https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels) you should be able to modify the sample to create a convention that works for your app/site.

**Comment by giancarloa** [comment]
@Eilon .... thank you... i will check it out...
