### ISSUE TITLE
[Question] Use Layout in ViewComponent

### ISSUE THREAD

**Issue by genusP** [aspnet/Mvc#4042]
Why the Layout page is not searched in the Shared Directory?

**Comment by dougbu** [comment]
Exactly how are you setting the `Layout` property in your view (or `_ViewStart.cshtml` file)? We support search strings, relative paths, and absolute paths.

**Comment by Eilon** [comment]
I don't think _ViewStart runs for View ViewComponent results, does it? It's not a "main page". But if you set the layout page in the view itself, it should work. Though maybe there's some issue with the search paths in that case?

**Comment by dougbu** [comment]
@Eilon right, I shouldn't have mentioned `_ViewStart.cshtml` files. But my question to @genusP remains important. If the `Layout` setting is just in a view start, problem solved -- move it to the view component view. Otherwise, need to look at the exact string used.

**Comment by Eilon** [comment]
@dougbu can you test if that works? In particular, that it searches the Shared folder for the layout.

**Comment by genusP** [comment]
If i define layout template in View for
```
@{ Layout = "_Layout.cshtml";}
```
when redering error occurs:
```
InvalidOperationException: The layout view '_Layout.cshtml' could not be located. The following locations were searched:
 /Views/Shared/Components/Index/_Layout.cshtml
```

**Comment by Eilon** [comment]
Yeah that seems to me like a bug... I would think that even if a view component was rendering a layout page that the view engine would search the appropriate shared location. But I could be wrong and maybe there's some good reason it doesn't...

**Comment by dougbu** [comment]
If you include the `.cshtml` extension, MVC looks for a file with the given name relative to the current file. Your view component view must have a path like `/Views/Shared/Components/Index/Default.cshtml`.

@genusP instead just pass the layout file's base name to search for it i.e. `@{ Layout = "_Layout";}`

**Comment by Eilon** [comment]
Oh yeah, that :smile:

**Comment by dougbu** [comment]
Glad we're on the same page @Eilon :sweat_smile: 

BTW view component views check the same search paths as any other view. In the above case, MVC will look for `/Views/{controller name}/_Layout.cshtml` then `/Views/Shared/_Layout.cshtml`. Neither path includes the component name, making a name like `_ComponentLayout` helpful.

**Comment by genusP** [comment]
Wow. So work. Thanks.
