### ISSUE TITLE
SelectTagHelpers: asp-items shouldn't require/depend on asp-for.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4047]
In the `SelectTagHelper` you can't use `asp-items` without specifying `asp-for`.

This does **NOT** work:
```html
<select asp-items="@Model.Categories"></select>
```

I can think of multiple scenarios where this might be a valid use case, the simplest one is when I want to provide my own `name` attribute without having a property on the view model.

Another is to use with client-side libraries for client-side content behavior not even involving using a form (my current situation)

Workaround (this **DOES** work):
```html
@{ 
    int? empty=null;
}
<select asp-for="@empty" asp-items="@Model.Categories"></select>
<!-- or -->
<select name="my-custom-name" asp-for="@empty" asp-items="@Model.Categories"></select>
```

**Comment by Eilon** [comment]
@DamianEdwards @dougbu any idea if this was deliberate for some reason? Or just oops?

**Comment by DamianEdwards** [comment]
I ran into this myself in the [localization sample](https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Views/Shared/_SelectLanguagePartial.cshtml#L19) and forgot to log an issue. I think was just an oops, and we should try to fix it.

**Comment by dougbu** [comment]
:smiling_imp: Well, the better excuse is the MVC tag helpers were originally modelled after the HTML helpers. `DropDownListFor()` and `ListBoxFor()` have a similar restriction; the passed expression must not be `null`. :smiling_imp: 

My only concern is a need to muck with the `IHtmlGenerator` APIs to enable this scenario. It's definitely doable, just not in an hour.
