### ISSUE TITLE
Provide any way to access a view's IHtmlHelper from inside a TagHelper

### ISSUE THREAD

**Issue by rwasef1830** [aspnet/Mvc#4048]
Currently, there is a [ViewContextAttribute] that can be placed on a ViewContext type property with public setter to have razor automagically inject the current ViewContext into the tag helper instance.

We need a similar thing for IHtmlHelper. The problem now is that it is reachable via ViewContext.View and doing reflection to get the Html property but that is extremely ugly.

Alternatively, it is possible to just add an attribute to the tag helper and pass `@Html` from the view, but that is very ugly.

```csharp
@model MyModel

<my-custom-tag asp-for="Property" html="@Html" /> @* ugly boilerplate ! *@
```

```csharp
    [HtmlTargetElement("my-custom-tag", Attributes = "asp-for")]
    public class MyCustomTagHelper : TagHelper
    {
        [HtmlAttributeName("asp-for")]
        public ModelExpression For { get; set; }

        [HtmlAttributeName("html")]
        public IHtmlHelper Html { get; set; }

        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
               /// ...
        }
    }
```

This is important for people who are trying to write tag helpers that construct composite output using older regular html helpers.

Note: Asking for IHtmlHelper in tag helper constructor doesn't work because we get a new HtmlHelper which needs to have Contextualize called on it (but the *Contextualize* method isn't exposed via the IHtmlHelper interface).

I hope the team considers adding a public API for this scenario.

**Comment by dougbu** [comment]
@rwasef1830 the main issue here is a bit lower-level: `ICanHasViewContext` is a hack and it's named to remind us of that fact. Unfortunately we haven't implemented a better solution for handling `ViewContext` in classes retrieved from DI.

As-is, you could:
- Ignore `IHtmlHelper` and get an instance of `IHtmlGenerator` from DI. Pass the tag helper's `ViewContext` property value when calling methods on that `interface`.
- If you need something that `IHtmlGenerator` does not itself support, get an instance of `IHtmlHelper` from DI and contextualize it: `(_htmlHelper as ICanHasViewContext)?.Contextualize(viewContext);`
- Use the workarounds you've described.
- Use lower-level stateless classes such as `TagBuilder`.

If `IHtmlGenerator` and `[ViewContext]` (for example) does not work for your scenario, please provide additional information. (For our part, we have yet to implement a tag helper that need an HTML helper. We did it once in a functional test but that was faked -- what it really needed was an `HtmlEncoder`.)

**Comment by rwasef1830** [comment]
Currently, I've gone with the second one (constructor DI of IHtmlHelper followed by attempted cast and calling contextualize), but I think that will break in future versions.

Accessing the html helper like this would have been much more workable (and less likely to break):
```csharp
(this.ViewContext.View as RazorView)?.RazorPage.Html
```

But the Html property is not exposed on the IRazorPage interface, but rather code-generated as a property of each individual view class.

Was this implemented as such to avoid the the IRazorPage and IRazorPage<TModel> (and explicit interface ugliness) problem ? 

Is it possible to add it the IRazorPage before RTM or has there been some consensus to not do that ?

**Comment by dougbu** [comment]
@rwasef1830 quick warning: `ViewContext.View` references the initial page loaded from a controller, view component, et cetera. In particular it is _not_ updated when processing layout pages.

So something like `(ViewContext.View as RazorView)?.RazorPage.Html` could easily retrieve an `IHtmlHelper` instance containing state inconsistent with the current view. Not positive what will be out of sync but I'd be wary.

**Comment by NTaylorMullen** [comment]
@dougbu couldn't you also get a link to the non-model based `IHtmlHelper` via DI and then contextualize it via an injected `ViewContext`?

**Comment by dougbu** [comment]
@NTaylorMullen yes, I suggested that [above](https://github.com/aspnet/Mvc/issues/4048#issuecomment-180168461).

**Comment by Eilon** [comment]
The recommended solution is indeed what @dougbu and @NTaylorMullen mentioned:

> get an instance of `IHtmlHelper` from DI and contextualize it: `(_htmlHelper as ICanHasViewContext)?.Contextualize(viewContext);`

**Comment by AndreiMaz** [comment]
How can we get IHtmlHelper<TModel> (and not just IHtmlHelper) in tag helpers?

**Comment by Eilon** [comment]
@AndreiMaz please log a new issue so we can take a look. Posting on old, closed issues means we're likely to miss the comment 😄

**Comment by AndreiMaz** [comment]
@Eilon please see our tag helper code at https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/TagHelpers/Admin/NopEditorTagHelper.cs

We have to invoke "EditorFor" method of HtmlHelper<TModel>. It's not available in standard HtmlHelper. That's the original issue we experience.
