### ISSUE TITLE
UrlHelper doesn't give access to a context

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#4049]
There is no way to get access to `HttpContext` in a `UrlHelper` extension, for instance to request some services. `HtmlHelper` however lets you access it.

**Comment by Eilon** [comment]
Wait a sec - I see an `IUrlHelper.ActionContext` property: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/IUrlHelper.cs#L13-L16

Isn't that enough? It's on the interface, so it's always "public", regardless of the concrete `UrlHelper`, though it also has a `public` property implementing it.

**Comment by sebastienros** [comment]
I see it has been added recently, this is why I couldn't use it (rc1).

Duplicate of
https://github.com/aspnet/Mvc/issues/3749

**Comment by Eilon** [comment]
Ah, nice :smile:
