### ISSUE TITLE
Consistency in formatters

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/Mvc#4059]
In Web API 2, we could use the default formatters to seriallize from and to any stream (not only the request/response bodies). Here we are tightly coupled to the HTTP context in most of the formatters and they cannot be used for other purposes. For example I can see the `JsonOutputFormatter` has public method `WriteObject` which can be used with any `TextWriter` and object but there is no equalent in `JsonInputFormatter` as there is no `ReadObject` method. String formatters does not support it either. Do you plan to add such public methods to all formatters so that they can be used outside of the request/response context?

**Comment by Eilon** [comment]
@ivaylokenov there are no current plans for this. Were you using Web API 2 formatters outside of Web API?

**Comment by ivaylokenov** [comment]
@Eilon My use case is quite rare I guess. I am writing a testing framework similar to [this one](https://github.com/ivaylokenov/MyTested.WebApi) but for the new MVC where you can assert routes like:

```c#
MyMvc
      .Routes()
      .ShouldMap(request => request
            .WithLocation("/My/Action/1")
            .WithMethod(HttpMethod.Post)
            .WithJsonBody(new { Integer = 1, String = "Text" }))
      .To<MyController>(c => c.Action(1, new SomeModel
      {
            Integer = 1,
            String = "Text"
      }));
```

This should respect all configured by the developer model binders, formatters, etc. `WithJsonBody` method just searches for a formatter which can process `application/json` and use it on the provided object. Afterwards your routing mechanisms and model binders kick in to resolve all needed values. In Web API 2 the formatters were not dependent on the HTTP request and response so I initially thought that in MVC will be the same. However, only the `JsonOutputFormatter` has such functionallity and all others do not so I decided to ask whether it is planned in order to have consistency in all formatters.

The above code is now working flawlessly by using fake HttpContext, writing JSON string on its response, reading the response sream, reset it, and then put it on the request, which is passed to the routing system to select the action. Quite hacky, but I do not see any other solution.

BTW, I noticed some interesting behaviour in the model binders while playing around. Will examine more and report it, if it is something worthy.

**Comment by rynowak** [comment]
It sounds like there's no action here for us. Please reopen or create a new issues if you think there's a problem here.
