### ISSUE TITLE
Remove Microsoft.NetCore.Platforms from class libraries

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#4061]
E.g. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/project.json#L30

cc @davidfowl

**Comment by ryanbrandenburg** [comment]
Turns out this is blocked by moving Mvc to dotnet. Giving it back to @pranavkm to do once that work is finished.

**Comment by pranavkm** [comment]
Addressed as part of https://github.com/aspnet/Mvc/commit/80b6996701ca240b8b4b1ba8f56c7ecae3e69b60
