### ISSUE TITLE
Adding path to native dll search paths

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Mvc#4063]
At this moment I can use 

```
[DllImport("kernel32.dll", CharSet = CharSet.Ansi, SetLastError = true)]
public static extern bool SetDllDirectory(string lpPathName);
```

This works in windows, naturally not in another platform, is there any api to use to put search path  native dll load?

**Comment by Eilon** [comment]
@andrew-vandenbrink this sounds like a general .NET question so I recommend asking on https://github.com/dotnet/coreclr/. However, the short answer as far as I know is that there's no automatic way. Instead you can have different sets of `DllImport`s and use the right one based on runtime OS detection. As far as changing the search paths, I'm really not sure and you'd need to ask the .NET / CoreCLR folks.

You can see some patterns that ASP.NET uses in Kestrel:
* https://github.com/aspnet/KestrelHttpServer/blob/00b8a13b5526bad646e35da64c00c176a942f057/src/Microsoft.AspNetCore.Server.Kestrel/Networking/Libuv.cs
* https://github.com/aspnet/KestrelHttpServer/blob/b062f851dcb1fc9013952fe72e9a087ae36323fe/src/Microsoft.AspNetCore.Server.Kestrel/Networking/PlatformApis.cs
