### ISSUE TITLE
generate input prefix in partial view

### ISSUE THREAD

**Issue by markusvt** [aspnet/Mvc#4068]
Would it be possible to auto-generate prefixes for input elements in a partial view?

I'm trying to accomplish the following: I have a partial view that is used in several other views. All of those views are forms that post data to their specific controller. Now i would like to bind the posted model from my partial view to a specific prefix, so i can easily access these data in the controller.

As far as is know right now, i would need to prefix every input element in my partial view on its own. 
So as i am using it as a partial view, is it possible to give the partial view a parameter or anything like that so MVC names the input elements in my partial view automatically with the prefix?

I saw a lot of posts, that in older MVC Versions, that was possible, e.g. with the following:

```@Html.Partial("_AddHobby", Model.HobbyModel, new ViewDataDictionary { TemplateInfo = new TemplateInfo { HtmlFieldPrefix = "hobby" } })```

Edit: I played a bit more with those fields and found that it actually works with the following:
```
@{
                    var vd = new Microsoft.AspNet.Mvc.ViewFeatures.ViewDataDictionary(ViewData);
                    vd.TemplateInfo.HtmlFieldPrefix = "Vehicle";
                }
                @Html.Partial("_Formular", Model.Vehicle, vd)
```
Just that constructor changed. Sorry to bother you :)

**Comment by rynowak** [comment]
No worries :laughing:
