### ISSUE TITLE
Add formatting possibility for Html.GetEnumSelectList

### ISSUE THREAD

**Issue by topguss** [aspnet/Mvc#4071]
Enum html helper is great and with formatting possibility I think that it could cover all user cases.

In some user cases, we have request to show code before text in DorpDownList. If we add code in enum's localization, it will be displayed wherever we show them, but we need it only in DorpDownList.

It would be great if the helper had parameter 'format'. Eg:

`Html.GetEnumSelectList<EnumType>(string format = "T")`

Format should recognized T and V tokens: T for Text and V for value. 

Default format  should be "T" and it will be generated SelectList as it works now.

If we provide format string, Eg. "V - T", when generating SelectListItem text show Value - Enum localized Text.

**Comment by danroth27** [comment]
Moving to backlog since we are not looking to add new features to the current release.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
