### ISSUE TITLE
Redirect to login page on IIS HTTPS problem

### ISSUE THREAD

**Issue by tstar** [aspnet/Mvc#4072]
After I publish my application on IIS server with enabled HTTPS I have problem with login page after accessing to page that required authorization. For some reason it is redirected to the login page without the https protocol. As a result, I get a 404 error. If I allow http protocol on the IIS server, then there is no problem. I can make an authorization on the http protocol. Then I can again enter https address and continue to work normally. I do not understand why identity sends me on an unprotected protocol for authentication?

I use Microsoft.AspNetCore.Mvc 1.0.0-rc2-17051.

Thanks for the help.

**Comment by danroth27** [comment]
@Tratcher Can you take a look at this?

**Comment by Tratcher** [comment]
When you're running Kestrel behind IIS, IIS forwards all requests to kestrel using http. If the request was originally https, IIS will include the `x-forwarded-proto: https` header. In RC1 the UseIISPlatformHandler middleware would take that header and update the request scheme. In RC2 this functionality has moved to UseForwardedHeaders. See https://github.com/aspnet/Announcements/issues/123

**Comment by tstar** [comment]
This code in Startup.cs solved my problem:
```
app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});
app.UseHttpMethodOverride();
```
This is a temporary solution or not?

**Comment by Tratcher** [comment]
That is the recommended pattern, though you don't need UseHttpMethodOverride.

**Comment by tstar** [comment]
Sorry for the stupid question. If the problem has been solved, do I have to close this issue or is it a global problem and does it require other solution?
