### ISSUE TITLE
Rename ICanHasViewContext to IViewContextAware

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4073]
Design notes here: https://github.com/aspnet/Mvc/issues/3973#issuecomment-182476618

**Comment by Eilon** [comment]
@pranavkm can you work with folks to get confirmation on the design?

**Comment by pranavkm** [comment]
The design per https://github.com/aspnet/Mvc/issues/3973#issuecomment-182476618 ran into limitations around the ability to inject types that were closed over the view model. There isn't a way to represent `IViewContextAwareFactory<IHtmlHelper<>>` during registration that works for this scenario. To this effect, we're keeping the type but renaming it to `IViewContextAware` until we can come up with a better design.
