### ISSUE TITLE
dnx-clr-win-x86.1.0.0-rc2-16357 getting 404 on every endpoint.

### ISSUE THREAD

**Issue by ltheONEl** [aspnet/Mvc#4074]
I have upgraded an RC1 project to RC2-16357  DNX4.5.1 only.

my configure method:

        public void Configure(IApplicationBuilder app)
        {
            app.UseStaticFiles();
            app.UseMvcWithDefaultRoute();
         }

Program.cs Main:
```
    public static class Program
    {
        public static void Main(string[] args)
        {
                 var host = new WebHostBuilder()
                    .UseDefaultConfiguration(args)
                    .UseIISPlatformHandlerUrl()
                    .UseStartup("MyTestApi")
                    .Build();

            //
                foreach (var feature in host.ServerFeatures)
                {
                    foreach (var address in ((KestrelServerInformation)feature.Value).Addresses)
                    {
                        Debug.WriteLine($"***>>> {address.ToString()}");
                    }

                 }
            host.Run();
}}}
```

httpplatfrom - stdout:

Process Id: 14024
Waiting for the debugger to attach...
Debugger attached.
Hosting environment: Development
Application base path: D:\vsRepos\MyTestApi\Api\SMyTestApi\src\MyTestApi
Now listening on: http://localhost:18188
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 DEBUG http://localhost:57287/ text/html 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:57287/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 87.9662ms 404 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 87.9678ms 404 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:18188/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1.584ms 404 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:18188/home  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1.2505ms 404 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:18188/home/index  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.9996ms 404 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:18188/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2.7883ms 404 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:18188/wwwroot  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1.3461ms 404

**Comment by ltheONEl** [comment]
I copied the syntax for .UseStartup() from music store sample.

**Comment by Tratcher** [comment]
`UseStartup<Startup>()` would be better, but regardless you'd get an error if it was wrong, not 404s. The most common cause of 404s is messed up routing like https://github.com/aspnet/IISIntegration/issues/14.  You should also check IHostingEnvironment.WebRootPath (by injecting it into your Startup.Configure method).

**Comment by ltheONEl** [comment]
I tried: env.WebRootPath = "http://localhost:57287/";  this did not work.

I also tried hitting the kestrel server directly: http://localhost:18188 the port specified in the stdout log.  Still getting 404s

**Comment by rynowak** [comment]
Can you include your **complete** `Startup.cs`?

**Comment by ltheONEl** [comment]
I got it,  I was not calling Configure() from ConfigureDevelopment().
