### ISSUE TITLE
Button tag helper

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#4075]
It would be nice to have a tag helper for `<button>` elements to maintain consistency of syntax with other elements (i.e., not having to use `Html.NameFor` when all other elements use `asp-for`.) This may be petty and aesthetic but I thought I would ask anyways. :lollipop:

**Comment by danroth27** [comment]
Seems reasonable. We're trying to avoid adding features at this point in the current release, but sounds like something we could look at adding in a future release.

**Comment by Eilon** [comment]
Closing because we have no plans to support this.

**Comment by tuespetre** [comment]
Thank @Eilon!

**Comment by dougbu** [comment]
Note we do now have a tag helper in the box which targets `<button>` elements: The `FormActionTagHelper` does this and generates `formaction` attributes based on `asp-controller`, `asp-action`, &hellip; attributes in the `.cshtml` file. But we don't support reading `asp-for` and generating `id`, `name` or `value` attributes based on it.

**Comment by tuespetre** [comment]
Nice, I didn't catch that that was added. Thanks for the update!
