### ISSUE TITLE
Add Scaffolded Item in MVC 6 - View

### ISSUE THREAD

**Issue by twentytwokhz** [aspnet/Mvc#4077]
I started the 

> Create a new ASP.NET 5 project tutorial

 on http://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html#create-a-new-asp-net-5-project.

When you create a new scaffolded item in Visual Studio Community 2015 Version 14.0.24720.00 Update 1 the Edit.cshtml View seems to lack the AuthorID field. Should have this:

`<input type="hidden" asp-for="AuthorID" />`

Is this a Visual Studio tooling support issue or something else?

**Comment by Eilon** [comment]
Hi @twentytwokhz I took a look at this and are you sure that there needs to be a hidden input for the AuthorID? The AuthorID is already in the URL so I would think that works just fine for model binding and the database update. Are you seeing otherwise?

**Comment by danroth27** [comment]
@barrytang thoughts on this scaffolding issue?

**Comment by twentytwokhz** [comment]
To be more clear: this is the crash I encountered on Edit Book page
> Microsoft.Data.Entity.DbUpdateException was unhandled by user code
>   HResult=-2146233088
>   Message=An error occurred while updating the entries. See the inner exception for details.
>   Source=EntityFramework.Relational
>   StackTrace:
>        at Microsoft.Data.Entity.Update.AffectedCountModificationCommandBatch.Consume(DbDataReader reader)
>        at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
>        at Microsoft.Data.Entity.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
>        at Microsoft.Data.Entity.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
>        at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
>        at Microsoft.Data.Entity.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
>        at Microsoft.Data.Entity.DbContext.SaveChanges()
>        at WebApplication2.Controllers.BooksController.Edit(Book book) in D:\Projects\Visual Studio 2015\Projects\WebApplication2\src\WebApplication2\Controllers\BooksController.cs:line 89
>   InnerException: 
>        Class=16
>        ErrorCode=-2146232060
>        HResult=-2146232060
>        LineNumber=2
>        Message=The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Book_Author_AuthorID". The conflict occurred in database "aspnet5-WebApplication2-46d3f3ab-edff-45a9-b520-02d1c78191fc", table "dbo.Author", column 'AuthorID'.
>        Number=547
>        Procedure=""
>        Server=(localdb)\mssqllocaldb
>        Source=.Net SqlClient Data Provider
>        State=0
>        StackTrace:
>             at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>             at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>             at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>             at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>             at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
>             at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
>             at System.Data.SqlClient.SqlDataReader.Read()
>             at Microsoft.Data.Entity.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, DbDataReader reader)
>             at Microsoft.Data.Entity.Update.AffectedCountModificationCommandBatch.Consume(DbDataReader reader)
>        InnerException: 
> 

![savechangescrash](https://cloud.githubusercontent.com/assets/15191469/13027025/b88a0156-d247-11e5-85cf-c9302f9960ca.png)

**Comment by twentytwokhz** [comment]
And this is the problem encountered on the Edit Author page:
![editauthorpage](https://cloud.githubusercontent.com/assets/15191469/13027068/83b26cc8-d249-11e5-91e4-1daaff885b86.png)

![editauthordata](https://cloud.githubusercontent.com/assets/15191469/13027067/6cf599b0-d249-11e5-8479-e1aa8d574fcc.png)

**Comment by barrytang** [comment]
@twentytwokhz, thanks for reporting the issue. I opened an internal tracking bug (TFS#190842) and my team will look into this.

**Comment by twentytwokhz** [comment]
@barrytang Ok. Great! I will close this one
