### ISSUE TITLE
TagBuilder can't build valueless attributes

### ISSUE THREAD

**Issue by geertdoornbos** [aspnet/Mvc#4078]
The Tagbuilder can't build a tag that had attributes with no value, like:

`<script src="..." async></script>`

It is currently possible to build alternatives:
`<script src="..." async=""></script>`
or
`<script src="..." async="async"></script>`

All three ways should be possible, where the first is the most clean way.

**Comment by dougbu** [comment]
Suspect you'd be better served using `TagHelperOutput`. On one hand `TagBuilder` is intended for HTML generation from code and we long-ago chose to emit only XHTML syntax. On the other, `TagHelperOutput` is intended to maintain the original syntax (from a `.cshtml` file) when filtering that HTML through a tag helper.

In any case `TagBuilder` does not support minimized attributes, sorts the generated attributes alphabetically by name, and more.
