### ISSUE TITLE
Problem with tag helpers not supporting C# in the element's attribute.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4080]
I use C# variables all the time to define clases or attributes in html tags like this:

```
@{
    string prev = !Model.HasPreviousPage ? "disabled" : "";
}
<a class="btn btn-ironhide" @prev>back</a>
```
which render (in case Model.HasPreviousPage = false):
```html
<a class="btn btn-ironhide" disabled>back</a>
```

this works fine until I use a tag helper

```
<a asp-action="Index" class="btn btn-ironhide" @prev>back</a>
```

This gives the following error:
```
The tag helper 'a' must not have C# in the element's attribute declaration area.
```

Is this by design or a limitation of tag helpers? any suggested work around?

**Comment by dougbu** [comment]
This is a current limitation of tag helpers. The issue is tracked in aspnet/Razor#96.

**Comment by Bartmax** [comment]
thank you @dougbu don't know if I should close this.

**Comment by dougbu** [comment]
Yup :smiley_cat:
