### ISSUE TITLE
Link tag helper should include original element's attributes in fallbacks

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4084]
E.g. `.cshtml` contains:
```html
    <link rel="stylesheet" data-extra="test"
          asp-fallback-href="~/styles/site.css"
          asp-fallback-test-class="hidden"
          asp-fallback-test-property="visibility"
          asp-fallback-test-value="hidden">
```

Generated HTML with a few extra newlines:
```html
    <link rel="stylesheet" data-extra="test">
<meta name="x-stylesheet-fallback-test" content="" class="hidden" />
<script>
!function(a,b,c){
var d,e=document,
  f=e.getElementsByTagName("SCRIPT"),
  g=f[f.length-1].previousElementSibling,
  h=e.defaultView&&e.defaultView.getComputedStyle?e.defaultView.getComputedStyle(g):g.currentStyle;
if(h&&h[a]!==b)
  for(d=0;d<c.length;d++)
    e.write('<link rel="stylesheet" href="'+c[d]+'"/>')
}("visibility","hidden",["\/styles\/site.css"]);
</script>
```

Note the `data-extra` is not included in the `<link>` element in the JavaScript, ready to be written into the document. Should it?

**Comment by DamianEdwards** [comment]
Given cases like http://codepen.io/tigt/post/async-css-without-javascript where you'd want extra attributes to get different behavior, then yes, it should probably preserve the extra attributes. I actually thought I remembered writing the code to do that... Does it work in the script TH?

**Comment by dougbu** [comment]
> Does it work in the script TH?

For some definition of "work" i.e. modulo #4083, yes.

**Comment by NTaylorMullen** [comment]
d60ed06c1998ced0af09ce1b86aa9f4b774495be
