### ISSUE TITLE
Controller helper inconsistency: HttpNotFound(), Ok()

### ISSUE THREAD

**Issue by cottsak** [aspnet/Mvc#4085]
I can `return HttpNotFound()` or I can `return Ok()` from a Controller. Why the inconsistent naming?

It should be one of these two alternatives IMO:

*  `return HttpNotFound()` and `return HttpOk()`, or
*  `return NotFound()` and `return Ok()`

I personally prefer the latter like the previous MVC incarnations. Thoughts folks?
cc @JakeGinnivan

**Comment by miloush** [comment]
I personally prefer the former if that results in the respective HTTP responses, as it is clear from names what it does. I would expect the latter to be application specific.

**Comment by cottsak** [comment]
To be honest I just want consistency.

**Comment by danroth27** [comment]
I think we can remove the Http prefixes at this point. I mean, it's all HTTP in MVC, right? HttpNotFound was the method name in MVC 5, but now that we are a v1 product I think we can relax the strict compat constraint.

**Comment by rynowak** [comment]
Does that include the action result classes?

**Comment by codnee** [comment]
I agree with @danroth27. The prefix is only making everything more verbose than it needs to be.

**Comment by danroth27** [comment]
I think the prefix on the result classes is also unnecessary and should be removed, but that's a bigger change. @Eilon ?

**Comment by miloush** [comment]
@danroth27 While it's all HTTP in MVC, application specific responses might not be in pair with actual HTTP codes (e.g. WebDav). However, like @cottsak I am not strongly opinionated on that, as long as it is consistent.

**Comment by Eilon** [comment]
I don't feel strongly on renaming the result types. I'm somewhat inclined to say that we keep them as they are now, just to minimize churn.

**Comment by codnee** [comment]
@Eilon isn't a little churn one of the things you can allow yourself do when creating something from scratch?

**Comment by dneimke** [comment]
+1 for making them consistent.  Agreee with @codnee re. a little churn now to save confusion and frustration later.

**Comment by cottsak** [comment]
Thanks guys.

I'll fix the tests etc when I can build/stuff is not [broke](https://ci.appveyor.com/project/aspnetci/mvc/history). If anyone has any tips, I'd appreciate it. 
Any eta on `master` getting green @davidfowl?

**Comment by Eilon** [comment]
@codnee certainly there is churn when the value is sufficient, but with the result types the value is dramatically less. The type names of the results are used very rarely. Generally at most in some unit tests, and more advanced customization scenarios reference the types.

**Comment by Eilon** [comment]
@cottsak the `master` branch shouldn't be used, only `dev`, and we've had some problems with dependencies that we're working on fixing.

**Comment by cottsak** [comment]
@Eilon I'm not sure what you mean re "result types the value is dramatically less". This is not about renaming the result types. It's about renaming the `ControllerBase` helper methods like `HttpNotFound()` right?

**Comment by cottsak** [comment]
@Eilon re `dev` branch: So what I should have done was pull `dev` and branch from there?

**Comment by Eilon** [comment]
@cottsak yes, we're all agreed on renaming the factory methods! :smile: I'm just not too concerned about renaming the underlying result types, which are rarely seen or heard.

**Comment by cottsak** [comment]
@Eilon I see. @kichalla changed the types too. yeh that's not what we want.

**Comment by Eilon** [comment]
@cottsak I ended up having my arm twisted by my colleagues and they convinced me that we might as well just go change everything.

**Comment by cottsak** [comment]
@Eilon fair enuf.

When can we expect these PRs to get merged? What's the time frame on the stability of `dev`?

**Comment by Eilon** [comment]
@cottsak merged very soon. `dev` has been a bit sick lately, but is getting better.

**Comment by rynowak** [comment]
This seems like this is announcement-worthy

**Comment by kichalla** [comment]
:+1: I just created one.
