### ISSUE TITLE
AddControllersAsServices should add controller types to the existing ControllerTypeProvider instead of replacing

### ISSUE THREAD

**Issue by stratever** [aspnet/Mvc#4086]
Hello everyone!

I have two different source of controller types and I want to add these controllers as a service like this:
```
services.AddMvc()
             .AddControllersAsServices(extLibraryControllerTypes)
             .AddControllersAsServices(dynamicControllerProvider.GetControllerTypes())
```
The first call with `extLibraryControllerTypes` doesn't have any effect because these controller types will be replaced by `dynamicControllerProvider.GetControllerTypes()` .

My understanding is that AddControllersAsServices should add controllers to the existing  controllerTypeProvider instead of creating a new ControllerTypeProvider (which only contains the given types passed as parameter) and replacing the existing ControllerTypeProvider  through the ControllersAsServices.AddControllersAsServices method.

Please rename the extension method/ControllersAsServices.AddControllersAsServices method or change the implementation to merge/concat these types.

**Comment by dazinator** [comment]
+1 this API caught me out too, had to remember to also include the existing assembly when "Adding" constrollers, as really it was replacing not adding.

**Comment by rynowak** [comment]
:+1: - yeah this seems like an oversight that it doesn't do the right thing if you call it multiple times.

**Comment by ajaybhargavb** [comment]
fd6d28d9eb8aa8c736c7f1d018647ad48d210fa4
