### ISSUE TITLE
Question: Unable to build Mvc.sln

### ISSUE THREAD

**Issue by izvictor** [aspnet/Mvc#4094]
Hello,
First of all sorry if this is not the right place to ask this kind of question, guide me if I'm wrong.

I have cloned the MVC repository form https://github.com/aspnet/Mvc.git, everything went well the dependent pacages were downloaded and all the stuff , the problem is when I try to rebuild the solution Mvs.sln I get the following errors:
![image](https://cloud.githubusercontent.com/assets/98562/13033151/72ef069e-d30c-11e5-91ef-14a374c47122.png)

Am I missing something ?

Thanks for help,

Regards,
Victor

**Comment by benaadams** [comment]
You might have to go volatile at the moment e.g. add to the `nuget.config` in the root:
`<add key="AspNetVolatile" value="https://www.myget.org/F/aspnetvolatiledev/api/v3/index.json" />`
You also don't want to use it for long, as its more unreliable, so revert when you can...

**Comment by izvictor** [comment]
Hi,
Thanks for help, passing to aspnet AspNetVolatile resolved all the build issues.

Regards,
Victor

**Comment by davidfowl** [comment]
Let me repeat this: DO NOT USE THE VOLATILE FEED. It it *NOT* for humans to use. It's strictly for making the CI machine to use. Using it will leave you broken 90% of the time. Our builds are unstable now because of the switch to dotnet CLI. It is coming back online quickly I'd recommend not building until then.

**Comment by benaadams** [comment]
^----- what he says :)

**Comment by benaadams** [comment]
^----- what he says - you only really want to use it for testing a "from source" compilation change; when the normal feed isn't working with the source. When the normal feed isn't working its because the tests are broken - which means you shouldn't use the volatile...

**Comment by izvictor** [comment]
OK understood :) I reverted to the original feed and the solution builds without errors.
