### ISSUE TITLE
Possible Bug in HttpNoContentOutputFormatter 

### ISSUE THREAD

**Issue by devteamexpress** [aspnet/Mvc#4096]
Hey Guys

We just upgraded our app to asp.net 5 and I have to say pretty awesome!!

I saw it mentioned that any response returned with either void or Task should trigger a 204 response but this is not happening. 

I tried manually adding the line OutputFormatters.Add(new HttpNoContentOutputFormatter()), and i see that it gets skipped whenever the result is empty. Kinda feels like no output formatters are used when there is no response. 

I tried returning void and Task and both of those had no effect. 

Just wondering if this is a bug, a known issue, or what the story is

Thanks.

**Comment by khellang** [comment]
What happens if you insert it into the start of the formatter collection?

```csharp
options.OutputFormatters.Insert(0, new HttpNoContentOutputFormatter());
```

**Comment by devteamexpress** [comment]
Tried that too it Never gets there has no effect.

What happens if you insert it into the start of the formatter collection?

options.OutputFormatters.Insert(0, new HttpNoContentOutputFormatter());

—
Reply to this email directly or view it on GitHub
<https://github.com/aspnet/Mvc/issues/4096#issuecomment-184128805>.

**Comment by rynowak** [comment]
@devteamexpress - can you please include your controller code and startup code that is having this issue so we can take a look? Nothing's changed here in a while :eyes:

**Comment by danroth27** [comment]
We did change the behavior to return a 200 by default (see #2409). However, I did confirm that if you manually add the formatter it doesn't change the result. 

@kichalla Could you please take a look and see why this is?

**Comment by kichalla** [comment]
We return an EmptyResult in case of action returning `void` or just `Task`.

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionInvoker.cs#L137-L141

Workaround: return a NoContentResult instead.

**Comment by Eilon** [comment]
@kichalla yes, but shouldn't the formatter work? When @danroth27 added the formatter it still didn't work - and if it doesn't work in this case, then what is it for?

**Comment by kichalla** [comment]
Yeah I agree this is a bug but wondering if need this formatter at all. Sending a status code response from a formatter seems a bit odd.

**Comment by rynowak** [comment]
The purpose of the formatter is that it will turn `null` into a 204. I agree that it's of limited value.

**Comment by danroth27** [comment]
Yeah, you get a 204 when you return null without having to do anything. It's only the case when you return void that you end up with a 200. I believe this behavior is expected.
