### ISSUE TITLE
Question: Is it possible to run vnext under an nested application in IIS?

### ISSUE THREAD

**Issue by SebastianStehle** [aspnet/Mvc#4098]
Hi,

I want to run an application under a nested application in IIS, /mobile but I have several problems:

1. @Url.Content("~/") points to / and not /mobile
2. Most routes are not resolved correctly.
3. Request.PathBase is "/"

**Comment by John0King** [comment]
Same question.
I really want  asp.net 5 can support subapplication in self host too.

**Comment by SebastianStehle** [comment]
I couldnt solve it, what I have done is this:

if (string.Equals(env.EnvironmentName, "TestingMain", StringComparison.OrdinalIgnoreCase))
            {
                app.Map("/m", p => ConfigureForEnvironment(p, env, loggerFactory));
            }
            else if (string.Equals(env.EnvironmentName, "TestingFeature", StringComparison.OrdinalIgnoreCase))
            {
                app.Map("/f", p => ConfigureForEnvironment(p, env, loggerFactory));
            }
            else
            {
                ConfigureForEnvironment(app, env, loggerFactory);
            }

Not the best solution, but it works for me.

**Comment by danroth27** [comment]
@Tratcher Could you please help out here?

**Comment by Tratcher** [comment]
https://github.com/aspnet/IISIntegration/issues/14

**Comment by Tratcher** [comment]
@John0King, what do you mean by subapplications in self-host? That should already work with WebListener, but it can't with kestrel because it can't share ports.

**Comment by John0King** [comment]
@Tratcher   In PHP, They can create a Forums Application and let this application run in any folder ( embed this application in any existing website). How to do this in asp.net 5

**Comment by Eilon** [comment]
Seems like the primary issue here was resolved. If there are further issues/questions, please log a new issue with more info/details and we can discuss there.
