### ISSUE TITLE
StatusCode Metadata

### ISSUE THREAD

**Issue by chadboyer** [aspnet/Mvc#4101]
Will there be a way to add metadata to my API actions depicting the different status codes it returns?

For example:
```
[ResposeType( HttpStatusCode.OK, typeof(Customer) ]
[ResponseType( HttpStatusCode.BadRequest, typeof(ValidationException)]
```

I believe this will be useful for the various tooling ( Swagger Generators and Help Doc Generators ) to understand the types of HTTP status codes your Web API can return.

**Comment by danroth27** [comment]
Swashbuckle defines it's own response attributes for specifying the additional metadata needed for Swagger generation.

@rynowak Should we have built-in attributes for capturing this metadata and make the metadata available via ApiExplorer?

**Comment by chadboyer** [comment]
Yes, status codes should be available via the ApiExplorer too.    Right now, each vender is creating their own custom attribute to get around this limitation.    

Almost all tooling around Web APIs needs to know about the status codes.   - help docs, swagger, ect.

**Comment by chadboyer** [comment]
Knowing the status codes is every bit as important as knowing the response type.

**Comment by danroth27** [comment]
@domaindrivendev FYI

**Comment by domaindrivendev** [comment]
Awesome!

**Comment by chadboyer** [comment]
+1 - Awesome!

**Comment by rynowak** [comment]
Some design notes on this:

**Example**

```
[Produces("application/json, Type = typeof(Widget)]
[ProducesResponseTypeAttribute(typeof(Errors), StatusCodes.BadRequest)]
public IActionResult DoThing() { }
```

Update `IApiResponseMetadataProvider`
```
public class IApiResponseMetadataProvider
{
    int StatusCode { get; set; }
}
```

Update `ProducesAttribute` and set `StatusCode` to 200 by default

Add `ProducesResponseTypeAttribute` (allow multiple)

```
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
public class ProducesResponseTypeAttribute : Attribute, IFilterMetadata, IApiResponseMetadataProvider
{
    public ProducesResponseTypeAttribute(Type type, int statusCode)
    public int StatusCode { get; }
    public Type Type { get; }
}
```

Move `ApiDescription.ResponseModelMetadata` and `ApiDescription.ResponseType` to `ApiResponseFormat`. Add `StatusCode` to `ApiResponseFormat`

Update the `DefaultApiDescriptionProvider` to take the cross product of "content-type" X "tuple(status code, type)" and run it through conneg.

**Comment by rynowak** [comment]
@kichalla - added some design notes

@domaindrivendev - any concerns with this?

**Comment by danroth27** [comment]
Should the ProducesAttribute still have a Type property if we are going to introduce a ProducesResponseTypeAttribute?

**Comment by kichalla** [comment]
:+1: on what @danroth27 mentioned.

**Comment by rynowak** [comment]
I think it's nicer to have as a shorthand for when you only want to specify one + you're already specifying a content type.

**Comment by khellang** [comment]
One thing; would you flip the order of the `int` and `Type` parameters?

I think it makes more sense to specify which status code produces which model, instead of the other way around:

```csharp
[ProducesResponseTypeAttribute(200, typeof(Customer))]
[ProducesResponseTypeAttribute(500, typeof(GenericError))]
[ProducesResponseTypeAttribute(422, typeof(ValidationError))]
public IActionResult DoThing() { }
```

**Comment by kichalla** [comment]
I like @khellang's suggestion here. One of the scenarios I am encountering where this makes more sense is with overriding. Example:

```c#
[ProducesResponseType(500, typeof(GenericError))]
public class TestController
{
      [Produces("text/json", "application/json", typeof(ProductDetails))]
      [ProducesResponseType(500, typeof(MoreSpecificErrorForThisAction))]
      public IActionResult Details()
      {
              ....
      }
}
```

So for the `Details` action and for the `500` status code, the more specific error is used and for the rest of the actions, the one on the controller is used.

@rynowak thoughts?

**Comment by rynowak** [comment]
The overriding part just falls out of the nature of being a filter.

re: the ordering of parameters, let's come up with a name that we like and let that dictate what order we use. `ProducesResponseType` was just a strawman to start work :laughing:
