### ISSUE TITLE
VirtualFilePathResult is not intuitive

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Mvc#4103]
https://github.com/aspnet/Mvc/pull/3039

```
if (System.IO.File.Exists(fullPath))
                {
                    return File(fullPath, "application/octet-stream");
                }   

Microsoft.AspNet.Mvc.FileResult: Information: Executing FileResult, sending file as 
Exception thrown: 'System.IO.FileNotFoundException' in Microsoft.AspNet.Mvc.Core.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request
```

Not quite sure what is the idea of VirtualFilePathResult especially this introduce breaking change for those who port and those who read this dead simple code. Why a framework unable to return a file that  exists with FileNotFoundException?

**Comment by davidfowl** [comment]
/cc @Eilon @rynowak 

Is there a reason we don't see if the path is rooted to determine which to use?

**Comment by Eilon** [comment]
"Rooted" is ambiguous in a cross-platform scenario. The reason we split the former single "FileResults" into Physical and Virtual is that paths that start with `/` are ambiguous. On *nix/Mac it could mean "root of the filesystem" or "root of the app", whereas on Windows it more typically means "root of the app". By having two different types the ambiguity is removed, and the onus is on the caller to use the right type.

**Comment by danroth27** [comment]
For web applications you generally care about the files within your application. Also in hosted scenarios you often want to prevent apps from reading arbitrary files anywhere on the machine. Hence most file APIs in ASP.NET Core deal with virtual paths rooted at the application instead of physical paths for native file system. The File method on Controller uses virtual paths.

To check for the existence of a file using a virtual path you can use the `IFileProvider` from the `IHostingEnvironment` service.

**Comment by andrew-vandenbrink** [comment]
It's up to you to decide but ideally the intend of the code must be explicit

Anyway,
in the end I have to code it like this
```
return File(new System.IO.FileStream(fullPath, System.IO.FileMode.Open), "application/octet-stream", new System.IO.FileInfo(fullPath).Name);
```

**Comment by Eilon** [comment]
@andrew-vandenbrink you can do `return PhysicalFile(...)` if you have a full path (e.g. `c:\dir\file.txt`, or on \*nix `/usr/user123/file.txt`).
