### ISSUE TITLE
Extend asp-for with prefixing 

### ISSUE THREAD

**Issue by lothistvan** [aspnet/Mvc#4105]
I use same Address class in many models: Employe.MailingAddress, Company.PhisycalAddress, Company.BillingAddress, etc. I'd like to create a ViewComponent to generate Address fields into forms.
Code of ViewComponent is very simple:

```
    public class AddressViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(AddressViewModel model)
        {
            return View(model);
        }
    }
```

Default.cshtml:
```
@model AddressViewModel

<div class="form-group row">
    <label asp-for="Country" class="col-md-3"></label>
    <column class="col-md-9">
        <input asp-for="Country" />
        <span asp-validation-for="Country"></span>
    </column>
</div>
<div class="form-group row">
    <label asp-for="City" class="col-md-3"></label>
    <column class="col-md-9">
        <input asp-for="City" />
        <span asp-validation-for="City"></span>
    </column>
</div>
...
```
And I invoke this component from view :
```
<form ...>
...
<span>Home address:</span>
@Component.Invoke("Address", Model.HomeAddress)
<span>Mailing address:</span>
@Component.Invoke("Address", Model.MailingAddress)

</form>
```
The problem: asp-for generates names and id-s without the original property name - and this is the correct method because in the component there is no complex property. My suggestion is a new taghelper: "asp-for-propertyname" or "asp-for-prefix" (or something similar) to let us decorate the generated identifiers with prefix - as in case of complex model properties. 

The code below
```
<input asp-for="Country" asp-for-propertyname="HomeAddress" />
```
should generates the following output:
```
<input type="text" name="HomeAddress.Country" id="HomeAddress_Country" />
```

**Comment by dougbu** [comment]
@lothistvan a tag helper attribute like `asp-for-prefix` wouldn't scale very well. Further the view component view should be reusable and a hard-coded prefix goes against that.

Suggest that you instead change the main view to:
```html
<span>Home address:</span>
@{
  var savePrefix = ViewContext.TemplateInfo.HtmlFieldPrefix;
  ViewContext.TemplateInfo.HtmlFieldPrefix = Html.NameFor(m => m.HomeAddress);
}
@Component.Invoke("Address", Model.HomeAddress)
<span>Mailing address:</span>
@{
  ViewContext.TemplateInfo.HtmlFieldPrefix = Html.NameFor(m => m.MailingAddress);
}
@Component.Invoke("Address", Model.MailingAddress)
@{
  ViewContext.TemplateInfo.HtmlFieldPrefix = savePrefix;
}
```

**Comment by lothistvan** [comment]
@dougbu I don't want to hard-code the the prefix - of course. In my plan I'll extend the model / parameter list of ViewComponent with that property.
I don't know TemplateInfo yet - I'll check it.

**Comment by lothistvan** [comment]
Thank you very much! The TemplateInfo solves my problem The following code denerates the correct name for inputs:

```
@model MyProject.Web.Components.Address.AddressViewModel
@{
    ViewContext.ViewData.TemplateInfo.HtmlFieldPrefix = Model.PropertyName;
}

<div class="form-group row">
    <label asp-for="Country" class="col-md-3"></label>
    <column class="col-md-9">
        <input asp-for="Country" />
        <span asp-validation-for="Country"></span>
    </column>
</div>
...
```

**Comment by bobske3** [comment]
Is TemplateInfo something available as a taghelper? I'm using the above approach, but I'm invoking viewcomponent as a vc taghelper (asp 1.1)

`<div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                @{ 
                    ViewContext.ViewData.TemplateInfo.HtmlFieldPrefix = "Settings";
                }
                <vc:settings mdtid="@Model.Id" settings-type="@SettingsType.Role"></vc:settings>
                @*<vc:settings role-id="@Model.Id"></vc:settings>*@
            </div>`

This will not put prefix in front of Description, but it will on my view components, which contains form-groups aswell similar. My ViewModel have a sub-model called Settings.

I think it would be much cleaner and simple to just write:

`<vc:settings mdtid="@Model.Id" settings-type="@SettingsType.Role" prefix="Settings"></vc:settings>`

Which would be an opt-in feature.

**Comment by dougbu** [comment]
@bobske3 this is a closed issue. If you're having a similar problem, suggest opening a new issue.

That said, your description above isn't clear. Are you saying `TemplateInfo.HtmlFieldPrefix` is cumbersome? In the normal case, it's set automatically and you can avoid it here too: Place the `<vc:settings>` helpers in editor templates for the types of interest, then invoke those templates using `@Html.Editor(...)` or `@Html.EditorFor(...)`.

**Comment by bobske3** [comment]
Ok thanks, it's not an issue, I just wrote here to help others. I'll try the editor trick thanks. It's not cumbersome (well maybe a little :D), but I just thought that it would be more consistent with taghelpers, so I could re-use the vc component again and again without having to remember to put it in editor/make a prefix. I also thought that taghelpers would be the popular choice nowadays instead of razor syntax (if it supports the same functionality that is)
