### ISSUE TITLE
TagHelper not working in external Razor View

### ISSUE THREAD

**Issue by dazinator** [aspnet/Mvc#4110]
I have noticed that this works fine within a View within my Web Application:

```
@section CssIncludes {
    <environment names="Local,Development">
        <link rel="stylesheet" href="~/css/home.css" />
    </environment>
    <environment names="Staging,Production,Test">
        <link rel="stylesheet" href="~/css/home.min.css" asp-append-version="true" />
    </environment>
}

```

But if I do the same in a View that's in a project referenced from the Web Application, I end up with this rendered to the browser:

 
![image](https://cloud.githubusercontent.com/assets/3176632/13116682/aa960202-d594-11e5-8cc3-fe6fe7c34baf.png)

Moving it outside of the `Section` made no difference either.

Am I doing something wrong?

**Comment by danroth27** [comment]
For tag helpers to work you need to add them using the `@addTagHelper` directive. I'm guessing you have this in your _ViewStart.cshtml file in your app project, but it only gets applied to views within the folder hierarchy. Try copying your _ViewStart.cshtml file to the Views folder in your referenced project.

**Comment by dazinator** [comment]
Thanks, I had actually put the following directly in my razor view:

```
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"

```

But I was still getting the problem, and it turns out I was getting hit by a known problem (I know there was an issue raised for this on github somewhere but can't find it now) that when changes are made to razor view files that are in seperate projects, they don't take effect when you then run the web application - it's using an old version of the file cached somewhere. You actually have to _change some code _ to force some kind of cache invalidation that is happening. Once I did this (just modified some whitepace in a class and re-built) the updated razor view took effect, and with the tag helper imported, it worked fine :)

I can't until this compilation issue is solved!
