### ISSUE TITLE
Question: Errors when opening any cshtml view

### ISSUE THREAD

**Issue by izvictor** [aspnet/Mvc#4111]
Hello,

I have a strange error when opening any of cshtml views :
Error	CS0234	The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?.

Below a screenshot from VS 2015:
![image](https://cloud.githubusercontent.com/assets/98562/13123075/a84b26c8-d5ba-11e5-8758-22de1273ea2c.png)

Has anyone come across this issue, am I missing something ?

Thanks for help,
Regards,
Victor.

**Comment by NTaylorMullen** [comment]
This is due to our recent `AspNet` => `AspNetCore` renames. The tooling is still on pre-renamed bits so it generates files with the AspNet naming. Your error will be resolved once new tooling is released :smile:
