### ISSUE TITLE
RequireHttpsAttribute doesn't change the port

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#4112]
RequireHttpsAttribute changes the scheme but not the port, so `http://localhost:44380/` gets redirected to `https://localhost:44380/`, which is invalid because you can't serve both http and https on the same port.

The only way this ever worked was if the original request's host header did not include the port (e.g. `localhost` rather than `localhost:80`)

There's even a (wrong) test:
https://github.com/aspnet/Mvc/commit/25838cee55216bd02432390996b95c5480b23e94#diff-ba666c0ff94ddf047b6f11caa0ac94c9R42

@sebastienros @blowdart @javiercn

**Comment by Eilon** [comment]
Kind of related to https://github.com/aspnet/Mvc/issues/4093

In the default case we should indeed drop the port number when redirecting to HTTPS, and fix the offending test.

**Comment by Eilon** [comment]
3-Done?
