### ISSUE TITLE
API Response to the MVC Action Output?

### ISSUE THREAD

**Issue by gencebay** [aspnet/Mvc#4114]
I have an Interface to API definitions (Contracts)

	public interface IGuidelineApi : IBaseApi
	{
	    ApiResult Operation(int i, string s, long l);
	}

and Server Side API implementation prototype is like that:

	[Route("api/[controller]")]
	public class GuidelineController : IGuidelineApi
	{
	    [HttpGet]
	    public ApiResult Operation([FromQuery]int i, [FromQuery]string s, [FromQuery]long l)
	    {
	    	// ApiResult inherits ActionResult
	        return new ApiResult(new { intVal = i, strVal = s, longVal = l });
	    }
	}

To execute any API method from any client ( MVC client app or mobile ) that using DispatchProxy can Invoke them via (API Interface) Dependency Injection

	private readonly IGuidelineApi _guidelineApi;
	public AccountController(IGuidelineApi guidelineApi)
	{
	    _guidelineApi = guidelineApi;

	     // DispatchProxy magic here!
	    _guidelineApi.Operation(1, "hello", 617);
	}

So question is that, can I transfer the API Response to the MVC Client output (IActionResult) as directly without serialization. 
Trying just replace - override the actual response (StreamContent of Client)

**Comment by Eilon** [comment]
@gencebay we generally do not recommend controllers (or anything) directly calling other controller actions. The problem with directly calling the methods is that it bypasses middleware, filters, model binding, action result processing, and a lot of other components.

Instead we recommend these two approaches:
1. Do another web request to the URL of the other controller and have the full request processing run (auth, caching, filters, model binding, etc.).
2. Put all the app logic/model in a separate class and call *that* class from all the controllers.

Both of these options indicate good layering of an application.

Controllers directly calling other controllers is generally bad layering because controllers are designed to respond to HTTP requests, not direct method calls.

**Comment by gencebay** [comment]
@Eilon  thanks! We have already done that as you said! DispatchProxy -> Invoke method doing a request with HttpClient via generated proxy:

    protected override object Invoke(MethodInfo targetMethod, object[] args)
    {
        if (CallBeforeInvoke != null)
            CallBeforeInvoke(targetMethod, args);

        // HttpClient
        using (var proxy = _proxyHelper.CreateProxy())
        {
            try
            {
                // Prepare request
                RequestDescriptor descriptor = _proxyHelper.Request(targetMethod, args, _underlyingType);

                // Call and get HttpResponseMessage from DMZ API call
                response = proxy.SendAsync(descriptor.Request).Result;
                
                // trying response override here its working like that 
                // but need custom ActionFilterAttribute to set Result property as NoContentResult
                // Direct stream transport
                if (response.Content is StreamContent)
                {
                    descriptor.ActionContext.HttpContext.Response.ContentType = Globals.ContentTypeWithEncoding;
                    descriptor.ActionContext.HttpContext.Response.Headers.Add(Globals.MetadataInnerHeader, metadataInner);
                    descriptor.ActionContext.HttpContext.Response.Headers.Add(Globals.MetadataHeader, metadata);

                    // Sync call wait all response!
                    ((StreamContent)response.Content).CopyToAsync(descriptor.ActionContext.HttpContext.Response.Body).Wait();

                    // Action filter will handle the Response actual result!
                    return null;
                }
            }
            catch (Exception ex)
            {
                // TODO logging, trace etc...
                throw ex;
            }
            finally
            {
                if (CallAfterInvoke != null)
                    CallAfterInvoke(targetMethod, args);
            }
        }
    }

This method getting result object from API layer (DMZ - local network) to the MVC 6 client web app then it takes care of the rest (serializations, validations and respond to browser)
