### ISSUE TITLE
Question: How to change search path for views and controllers?

### ISSUE THREAD

**Issue by Emdot** [aspnet/Mvc#4122]
My views are at `./back-end/Views` rather than at `./Views`. MVC convention doesn't find them. How can I change that convention in my application? I'd guess `MvcOptions.Conventions`, but I haven't found anyone writing about it so far.

```
fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The view 'Index' was not found. The following locations were searched:
      /Views/Home/Index.cshtml
      /Views/Shared/Index.cshtml.
      System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
      /Views/Home/Index.cshtml
      /Views/Shared/Index.cshtml.
```

**Comment by Muchiachio** [comment]
You should implement your own `IViewLocationExpander`
```C#
public class ViewLocationExpander : IViewLocationExpander
{
    public IEnumerable<String> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<String> viewLocations)
    {
        return new[]
        {
            "/back-end/Views/{1}/{0}.cshtml",
            "/back-end/Views/Shared/{0}.cshtml"
        };
    }
    public void PopulateValues(ViewLocationExpanderContext context)
    {
    }
}

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services
            .AddMvc()
            .AddRazorOptions(options => options.ViewLocationExpanders.Add(new ViewLocationExpander()));
    }
}
```

**Comment by Emdot** [comment]
Sweet, that worked. I wouldn't have guessed that it's part of razor. Thanks so much!

**Comment by Eilon** [comment]
Another option is to set the `ViewLocationFormats` and `AreaViewLocationFormats` on the `RazorViewEngine`:

https://github.com/aspnet/Mvc/blob/8b1bd343ba56152d2a7e677cf041dc9d62b4033f/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngine.cs#L76-L102

This would avoid having to do any "calculation" at runtime in the view expander to figure out how to modify the path to match what you want.

And yet another option is to change the `IFileProvider` used by the `RazorViewEngine` to one that is rooted in the sub-folder you want: https://github.com/aspnet/Mvc/blob/8b1bd343ba56152d2a7e677cf041dc9d62b4033f/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngineOptions.cs#L36

But view expanders work quite well as well!
