### ISSUE TITLE
how to reference System.Drawing assembly in dotnet5.4

### ISSUE THREAD

**Issue by blueskybcl** [aspnet/Mvc#4124]
1. how to reference System.Drawing assembly in dotnet5.4 framework for library?
i want to generate validate code

2. how to open unsafe switch in mvc 6 of visual studio 2015?

**Comment by davidfowl** [comment]
> how to reference System.Drawing assembly in dotnet5.4 framework for library?
You can't because it's not available as part of .NET Core. See https://github.com/dotnet/corefx/issues/5921.

> how to open unsafe switch in mvc 6 of visual studio 2015?
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/project.json#L53

**Comment by blueskybcl** [comment]
@davidfowl  thank you !
