### ISSUE TITLE
Add tool to do razor compilation to .cs file for razor views

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#4126]
We should have a tool that converts .razor files to .cs files with a specified host. Less generic would be an mvc specific view precompiler.

/cc @pranavkm @danroth27 @Eilon

**Comment by NTaylorMullen** [comment]
We built a sample that does this most of the way. We've definitely talked about toolifying it more but haven't done it yet.

https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString

**Comment by danroth27** [comment]
@davidfowl is this needed to enable a specific scenario in v1?
