### ISSUE TITLE
What happened to the @helper directive in Razor ?

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4127]
```
@helper BgImage(string url){
    <a style="background-image:url(@url)"></a> 
}
````
result:
`The helper directive is not supported.`

**Comment by NTaylorMullen** [comment]
`@helper` was removed a while back due to Razor content now being async. At some point we had intention to re-add it but it's sense fallen out of scope.

**Comment by Bartmax** [comment]
ok, ty .
