### ISSUE TITLE
Call to AddMvc is ambiguous

### ISSUE THREAD

**Issue by christiannagel** [aspnet/Mvc#4128]
I'm getting the error that the call to AddMvc is ambiguous. The error doesn't really help as ambiguity is between the same types: 

C:\Source\ProfessionalCSharp6\WebAPI\BooksServiceSample\src\BooksServiceSample\Startup.cs(31,22): error CS0121: The call is ambiguous between the following methods or properties: 'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(Microsoft.Extensions.DependencyInjection.IServiceCollection)' and 'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(Microsoft.Extensions.DependencyInjection.IServiceCollection)'

Did the package where MvcServiceCollectionExtensions is defined change, and I included the old and the new one? What else could be the reason?

**Comment by davidfowl** [comment]
Can you upload your sample project to github?

**Comment by christiannagel** [comment]
The BooksServiceSample project has this problem:
https://github.com/ProfessionalCSharp/ProfessionalCSharp6/tree/master/WebAPI/BooksServiceSample/src/BooksServiceSample

Using dotnet tools 1.0.0-beta-001494
dotnet restore
dotnet build

dotnet build shows this error.

**Comment by PinpointTownes** [comment]
Your issue is likely caused by the fact you're using Swashbuckle (whose last public version targets RC1) with the latest ASP.NET Core packages. Sadly, you can't reference both RC1 and RC2 packages in the same project.

**Comment by davidfowl** [comment]
You need to update everything to RC2 (if that's even possible)

**Comment by Dima4ka** [comment]
Hi all,

This issue is still happening to me.
Here is the build output

`Startup.cs(55,13): error CS0121: The call is ambiguous between the following methods or properties: 'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(Microsoft.Extensions.DependencyInjection.IServiceCollection)' and 'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(Microsoft.Extensions.DependencyInjection.IServiceCollection)'
`

Here are my usings for Startup.cs:

```
using System;  
using Microsoft.AspNetCore.Builder;  
using Microsoft.AspNetCore.Hosting;  
using Microsoft.Extensions.Configuration;  
using Microsoft.Extensions.Logging;  
using EShop.Services;  
using Microsoft.AspNetCore.Http;  
using System.IO;  
using Microsoft.Extensions.DependencyInjection  
```

I feel like it sees also `Microsoft.AspNet` (not Core) library, but how shall I fix it?

**Comment by PinpointTownes** [comment]
> I feel like it sees also Microsoft.AspNet (not Core) library, but how shall I fix it?

Maybe you can ping the author of the offending library and offer him some help to port it to ASP.NET Core RC2?

**Comment by Dima4ka** [comment]
I don't think that this library is offending. It is a core component, I am sure it works. I just don't know why it does not work in my particular situation.

**Comment by PinpointTownes** [comment]
AFAICT, there's no official version for RC2 on NuGet.org: https://www.nuget.org/packages/Swashbuckle/6.0.0-rc1-final

Trying to use a package relying on RC1 bits will bring incompatible packages in your project, explaining the error you're seeing.

**Comment by Dima4ka** [comment]
I do not use Swashbuckle library (see my list of usings in Startup.cs).

**Comment by PinpointTownes** [comment]
Many projects use the `Microsoft.AspNetCore.Builder` namespace for their `IApplicationBuilder` extensions to make them easier to find so I'm not sure it's really relevant :smile: 

Instead, you should post your `project.json`. I bet there's a package referencing RC1 bits somewhere (it's easy to confirm by looking at the `project.lock.json` file)

**Comment by Dima4ka** [comment]
It might be true... My `project.lock.json` is really large and I am not sure what it is and how to see anything from it.

However, let me post my `project.json` file.
Thank you for your help!

```
{
	"userSecretsId": "aspnet5-EShop-58a1b196-f710-4cff-9654-b95ee66598f8",
	"version": "1.0.0-*",
	"dependencies": {
		"Microsoft.NETCore.Platforms": "1.0.1-rc2-*",
		"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-final",
		"EntityFramework7.Npgsql": "3.1.0-rc1-3",
		"EntityFramework7.Npgsql.Design": "3.1.0-*",
		"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
		"Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0-rc2-final",
		"Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-rc2-final",
		"Microsoft.EntityFrameworkCore.Sqlite.Design": "1.0.0-rc2-final",
		"Microsoft.EntityFrameworkCore.InMemory": "1.0.0-rc2-final",
		"Microsoft.ApplicationInsights.AspNet": "1.0.0-rc1",
		"Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
		"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-*",
		"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
		"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
		"Microsoft.AspNetCore.Mvc": "1.0.0-*",
		"Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
		"Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
		"Microsoft.AspNetCore.Razor.Tools": "1.0.0-*",
		"Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
		"Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
		"Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
		"Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-final",
		"Microsoft.Extensions.Logging": "1.0.0-rc2-final",
		"Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
		"Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
		"NetTelegramBotApi": "3.7.50926"
	},
	"frameworks": {
		"netcoreapp1.0": {
			"imports": [
				"dnxcore50",
				"portable-net45+win8"
			]
		}
	},
	"runtimes": {
		"osx.10.11-x64": {},
		"ubuntu.14.04-x64": {},
		"win7-x64": {}
	},
	"runtimeOptions": {
		"gcServer": false,
		"gcConcurrent": true
	},
	"buildOptions": {
		"emitEntryPoint": true,
		"preserveCompilationContext": true,
		"compile": {
			"exclude": [
				"wwwroot",
				"node_modules"
			]
		}
	},
	"publishOptions": {
		"include": [
			"wwwroot",
			"Views"
		],
		"exclude": [
			"**.user",
			"**.vspscc"
		]
	},
	"scripts": {
		"prepublish": [
			"npm install",
			"bower install  --allow-root"
		]
	}
}
```

P.S. It is the first time I am trying to migrate to RC2. Sorry for silly mistakes :)

**Comment by PinpointTownes** [comment]
As expected, you're mixing RC1 and RC2 packages, which can't work. Try to update these packages:

```
"EntityFramework7.Npgsql": "3.1.0-rc1-3",
"EntityFramework7.Npgsql.Design": "3.1.0-*",
"Microsoft.ApplicationInsights.AspNet": "1.0.0-rc1",
"Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
"Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final"
```

**Comment by Dima4ka** [comment]
Thank you! I will try.

**Comment by Dima4ka** [comment]
Let me confirm that your suggestion actually does fix the issue!

In case somebody needs it, here are the updated dependencies:

```
"dependencies": {
		"Microsoft.EntityFrameworkCore.Tools": "1.0.0-*",
		"Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.0-*",
		"Npgsql.EntityFrameworkCore.PostgreSQL.Design": "1.0.0-*",
		"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
		"Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0-*",
		"Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-*",
		"Microsoft.EntityFrameworkCore.Sqlite.Design": "1.0.0-*",
		"Microsoft.EntityFrameworkCore.InMemory": "1.0.0-*",
		"Microsoft.ApplicationInsights.AspNetCore": "1.0.0-*",
		"Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
		"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-*",
		"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
		"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
		"Microsoft.AspNetCore.Mvc": "1.0.0-*",
		"Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
		"Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
		"Microsoft.AspNetCore.Razor.Tools": "1.0.0-*",
		"Microsoft.Extensions.Configuration.Json": "1.0.0-*",
		"Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-*",
		"Microsoft.Extensions.Logging": "1.0.0-*",
		"Microsoft.Extensions.Logging.Console": "1.0.0-*",
		"Microsoft.Extensions.Logging.Debug": "1.0.0-*",
		"NetTelegramBotApi": "3.7.50926"
	}
```

@PinpointTownes thank you!

**Comment by PinpointTownes** [comment]
You're welcome :clap:

**Comment by nhtbtmz** [comment]
If you use RC2 solution with nuget packages which are using RC1 you may get this error. I got this error with Kendo UI

**Comment by pranavkm** [comment]
@nhtbtmz we don't recommend against mixing packages from earlier releases with the current one.

**Comment by sophisma** [comment]
@nhtbtmz were you able to solve the ambiguity in AddMvc() because of kendo ui?
I'm having the same problem, if I remove the reference to Kendo.Mvc form Project.json the ambiguity disappears.

**Comment by nhtbtmz** [comment]
@sophisma nope I couldn't. You should wait for kendo ui rc2 support
you ll see details here 
http://www.telerik.com/forums/asp-net-core-1-0-rc2-support
https://github.com/telerik/kendo-ui-core/issues/1682

**Comment by sophisma** [comment]
@nhtbtmz Thank you very much.
