### ISSUE TITLE
`FormFileModelBinder` and `HeaderModelBinder` are inconsistent with `GenericModelBinder`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4129]
The `GenericModelBinder` group of binders (`CollectionModelBinder` et cetera) always create a collection instance (even if binding fails) when `IsTopLevelObject == true`. `FormFileModelBinder` and `HeaderModelBinder` do not.

The `GenericModelBinder` group of binders add to an existing collection (i.e. cast `Model` to an `ICollection<T>` and `Add()` to it) whenever `Model != null`. Those binders also create a new collection instance only if `Model == null` (and either `IsTopLevelObject == true` or binding succeeds). `FormFileModelBinder` and `HeaderModelBinder` never add to an existing collection and will overwrite `Model` whenever binding succeeds. Note `MutableObjectModelBinder` assumes _all_ model binders for `IEnumerable` types can add to an existing collection.

-----

This is _not_ a suggestion to restore special case collection handling in `MutableObjectModelBinder`. Doing so would not fix `TryUpdateModelAsync()` scenarios with a top-level collection of headers or files.

**Comment by dougbu** [comment]
`FormFileModelBinder` and `HeaderModelBinder` silently ignore read-only collection properties even if non-`null`. And, unlike `ArrayModelBinder`, these binders appear to succeed with read-only collection properties. That means `[BindRequired]` checks won't fire.

Side note: My mention of `TryUpdateModelAsync()` in final paragraph above doesn't realistically apply to `HeaderModelBinder` scenarios. `[FromHeader]` cannot be applied to a type.

**Comment by danroth27** [comment]
This will get fixed as part of #3482.
