### ISSUE TITLE
Make HTML generation for collections easier to use

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4132]
We have a number of HTML generation gotchas when handling elements of a collection. Things usually work fine when creating a display view or have a `<form>` for each element. But `name`s, `id`s and `ModelState` lookups quickly get messy otherwise.
#4106 is one recent case where `foreach` led to issues. #3519 may be related. And aspnet/Razor#53 suggests one Razor syntax that might get us out of jail here. Think someone suggested a tag helper approach as well (though that would go somewhat against the usual similarity between .cshtml content and generated HTML with existing tag helpers).

In any case, the basic idea would be to make it easy and obvious to get a useful indexer when iterating over a collection. Alternatively, work to make the indexer unnecessary.

Examples...

``` c#
  var index;
  while (Html.ForEach(m => m.List, out index))
  {
    @Html.TextBoxFor(m => m[index].Name)
  }
```

``` c#
  foreach (var index = Html.EachFor(m => m.List))
  {
    ...
  }
```

From aspnet/Razor#53:

``` c#
@Html.Form<UserInputModel>(@=>(builder, i) {
    @builder.Input(x=>x.List[i].Name)
}
```

Or `builder` could be another `HtmlHelper` with correct `ViewDataDictionary` and other context already set up for the item:

``` c#
@Html.Form<UserInputModel>(@=>(builder) {
    @builder.TextBoxFor(item => item.Name)
}
```

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
