### ISSUE TITLE
NOT IN Doesnt work

### ISSUE THREAD

**Issue by GVX111** [aspnet/Mvc#4133]
IN RC1-Final doesnt work Contains filter.
I have like this query: 
_tsContext.Hotels.Where(e => hotelCities.Contains(e.CityId))
but it generate this query:
SELECT [e].[HotelId], [e].[CategoryId], [e].[CityId], [e].[HotelTitle], [e].[IsRecommended], [e].[Latitude], [e].[LocalityId], [e].[Longitude], [e].[ParentId], [e].[Web]
      FROM [TS].[Hotels] AS [e]

there is not (IN Function) doesn't filtering.

**Comment by danroth27** [comment]
Please open this issue in the https://github.com/aspnet/entityframework repo.

**Comment by GVX111** [comment]
So sorry
