### ISSUE TITLE
Enable template and attribute based routing work together

### ISSUE THREAD

**Issue by chaliy** [aspnet/Mvc#4135]
I was in hope to define template based routing to controller and then attribute based for actions. My scenario is that controllers are in the library and I need to allow prefix for them, so template based routing works here, however my controllers are actually RESTFull services, and so it will be nice to have HttpGet, HttpPost support with templates, this is why attribute based routing is needed. 

Something like:

    public class Foo : Controller
    {
        [HttpGet]
        public object Get()
        {
            return new
            {
                ID = "A"
            };
        }

        [HttpPost]
        public object Create([FromBody]dynamic entity)
        {
            return new
            {
                ID = "B"
            };
        }

    }

Route

    app.UseMvc(routes =>
            {
                routes.MapRoute("Settings", "settings/api/foo",
                        new { controller = "Foo" }
                );
            });

And I expect this to work:

    GET /settings/api/foo
    POST /settings/api/foo

Unfortunately it is not a case. It looks like route attributes are ignored. I tried to nest TemplateRoute and AttributeRoute but no lack, AttributeRoute matches whole path. 

Copy on SO - http://stackoverflow.com/questions/35563609/how-to-combine-template-and-attribute-based-routing-in-asp-net-core

**Comment by Eilon** [comment]
You can certainly do this in ASP.NET Core MVC (and do very similar things in all previous versions of MVC as well).

I [answered on SO](http://stackoverflow.com/a/35570516/31668), and here's the post as well:

---------

The trick here is to route the URL to a specific controller *and* action. Then use action method *overloading* with an action method selector to switch between the GET and POST.

Change your route setup code to this:

    app.UseMvc(routes =>
    {
        routes.MapRoute(
            "Settings",
            "settings/api/foo",
            new {
                controller = "Foo", // specific controller
                action = "DoThing", // AND specific action
            }
        );
    });

And change the controller to have both action methods (or however many you want - one for each HTTP verb) to have the *same name*, but using different action methods selectors:

    public class FooController : Controller
    {
        [HttpGet] // different action method selector!
        public object DoThing() // same name!
        {
            return new
            {
                ID = "A"
            };
        }

        [HttpPost] // different action method selector!
        public object DoThing([FromBody]dynamic entity) // same name!
        {
            return new
            {
                ID = "B"
            };
        }
    }

This way MVC will route all the requests for that URL to an action called `DoThing` on controller `Foo`. Once it gets there it sees "oh my, oh my, there are two actions with the same name!" But then it sees the `[HttpGet]` and `[HttpPost]` action method selectors, and whichever one of them says it can handle the request will win.
