### ISSUE TITLE
DependencyContextAssemblyProvider assumes the entry assembly has a .deps.json file

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Mvc#4136]
Tests in the aspnet/Performance repo are failing because [`DependencyContextAssemblyProvider.GetCandidateLibraries()`](https://github.com/aspnet/Mvc/blob/25eb50120eceb62fd24ab5404210428fcdf0c400/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/DependencyContextAssemblyProvider.cs#L64) assumes that `DependencyContext.Default` is not null. Our tests are throwing a `System.NullReferenceException` when accessing `DependencyContext.Default` as it's null.

Note that the current implementation of [`DependencyContext.get_Default()`](https://github.com/dotnet/cli/blob/master/src/Microsoft.Extensions.DependencyModel/DependencyContext.cs#L50) allows for it to be null when the entry assembly (in our case xunit.console.exe) doesn't provide a dependencies description file (in our case xunit.console.deps.json).

Let me know if I'm interpreting something wrong, this has the Performance repository blocked aspnet/Performance#62.

@NTaylorMullen @muratg @SajayAntony

**Comment by davidfowl** [comment]
That's fixed in https://github.com/aspnet/Mvc/pull/4088

**Comment by muratg** [comment]
@pranavkm will check his change in soon, so this should be a non-issue soon.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/5b805bb12db3e47b380038cf6aa5d149f9f02421

**Comment by pranavkm** [comment]
We still null ref with this change. Should we throw an exception stating you should set the `preserveCompilationContext` flag if `DependencyContext.Load` returns null?

**Comment by pranavkm** [comment]
Self assigning since this would be a relatively small fix.

**Comment by davidfowl** [comment]
Then we need 2 APIs. TryLoad and Load

**Comment by davidfowl** [comment]
Why are we still null reffing?

**Comment by pranavkm** [comment]
There's an obvious bug in my code (I call `DependencyContext.Default`) - but what happens when `DependencyContext.Load` returns null? Do we only look at the assembly specified by `IApplicationEnvironment.ApplicationName` for controllers? Or should we throw an error saying you probably forgot to include the setting in project.json?

**Comment by davidfowl** [comment]
> There's an obvious bug in my code (I call DependencyContext.Default) - but what happens when DependencyContext.Load returns null? 

There's no deps file so act like it returns 0 results.

> Do we only look at the assembly specified by IApplicationEnvironment.ApplicationName for controllers?

Yes. `IApplicationEnvironment.ApplicationName` is ASP.NET's abstraction over entry assembly.

> Or should we throw an error saying you probably forgot to include the setting in project.json?

This is tricky. Right now I would say don't throw. Especially in light of this https://github.com/dotnet/cli/commit/acd581c376c622743480176f75d7aed3088d5462
