### ISSUE TITLE
RenderAction should be independent of http method

### ISSUE THREAD

**Issue by dotnetchris** [aspnet/Mvc#4141]
When using ``` @{ Html.RenderAction("ActionName", "ControllerName") } ``` MVC should return the specified action independent of the current http method.

See http://stackoverflow.com/questions/4227930/renderaction-calls-wrong-action-method and http://stackoverflow.com/questions/16941317/a-public-action-method-was-not-found-on-controller for more information

**Comment by davidfowl** [comment]
`RenderAction` is gone in ASP.NET Core so this doesn't apply. Should this be an MVC bug?

**Comment by dotnetchris** [comment]
Am I in the wrong MVC?

**Comment by dougbu** [comment]
@dotnetchris you likely want MVC version 5.x. That's available at https://aspnetwebstack.codeplex.com/ This repo is for ASP.NET 5 MVC, a rewrite that works on.NET Core.

**Comment by dotnetchris** [comment]
Assuming that there is no comparable situation here. (And my god does Microsoft not know how to name anything)
