### ISSUE TITLE
readme needs updated

### ISSUE THREAD

**Issue by dotnetchris** [aspnet/Mvc#4144]
The readme needs updated to make it clear that it is not *that* .NET but this *other* .NET so anyone has any idea what this repo is for.

**Comment by dotnetchris** [comment]
I forked the readme myself and i just gave up because i don't even know how to properly clarify it.

**Comment by danroth27** [comment]
We'll update the readme to say ASP.NET Core MVC

**Comment by dotnetchris** [comment]
:+1:

**Comment by Eilon** [comment]
Everything in this repo should now be ASP.NET Core / ASP.NET Core MVC. Thanks!
