### ISSUE TITLE
Consider storing a Task<> in cache tag

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4147]
We're wondering if the concurrency behavior of #CacheTag is quite right.

Since we store the computed content in a `StringBuilder` - on cache miss, every thread to reach that block needs to recompute the content. If the content takes a long time to compute, it could mean a lot of extra DB calls or just general processing.

It seems beneficial to have the cache store `Task<>` so that we can quickly address the 'miss' and have other threads aside from the one computing the data wait on the task.

**Comment by sebastienros** [comment]
We do that in Orchard by locking on the cache key (`String.Interned`), and talking with Ryan `Task` is better in that case. Something else we do and might be worth considering is to continue to serve stale data if one thread is already processing the __new__ value, which means only return the `Task` if there is no current value. This could be an option on the cache entry to opt-out this behavior.

**Comment by scanham** [comment]
Thanks for reporting this @rynowak! :+1: 

I really like that @sebastienros. That's a model I've used for caching layers in the past and would love to see it here too. I would want this behavior for every instance in which I'm using the CacheTag on my current project.
