### ISSUE TITLE
How to manually process/render TagHelpers?

### ISSUE THREAD

**Issue by SimonOrdo** [aspnet/Mvc#4148]
I'm trying to figure out if there is any provided functionality to accomplish the following:

I have the following in a view which uses the built-in cache tag helper as well as a custom tag helper with targets DIV elements.
```
<cache expires-after="@TimeSpan.FromSeconds(5)">
    <div custom-tag-helper-parm="9289"></div>        
</cache>
```

I now have a HTML helper to try and render out the above.  It looks something like so:

```
public static HtmlString RenderContent(this IHtmlHelper HtmlHelper, string customTagHelperParm)
{              
        var output = $@"<cache expires-after='{@TimeSpan.FromSeconds(5)}'>
                            <div custom-tag-helper-parm = '{customTagHelperParm}'>
                            </div>
                        </cache>";      

        return new HtmlString(output);
}
```

As expected, this HTML helper puts out the literal HTML specified into the final HTML of the view.  No processing of the tags is happening.

Is there a way to process the tags in the HTML code in the HtmlString the same way the view engine would process/interpret them (including the custom taghelper)?

**Comment by NTaylorMullen** [comment]
You can new up the CacheTagHelper yourself and provide the appropriate parameters:

```C#
var cacheTagHelper = new CacheTagHelper(...);
cacheTagHelper.ExpiresAfter = ...
```

And so forth

**Comment by danroth27** [comment]
Tag Helpers are a feature intended to be used from within Razor syntax. HTML helpers produce HTML, not Razor.
