### ISSUE TITLE
Where is the repo for `TestServer`?

### ISSUE THREAD

**Issue by cottsak** [aspnet/Mvc#4155]
I'm looking for the repo that contains `TestServer` as used https://github.com/aspnet/Mvc/blob/80b6996701ca240b8b4b1ba8f56c7ecae3e69b60/test/Microsoft.AspNetCore.Mvc.FunctionalTests/MvcTestFixture.cs#L24

I need to raise an issue regarding how the pipeline is apparently not serializing results passed into `IActionResult`.

Can someone point me in the right direction please?

**Comment by davidfowl** [comment]
https://github.com/aspnet/Hosting

**Comment by cottsak** [comment]
@davidfowl thanks. [Issue raised](https://github.com/aspnet/Hosting/issues/614).
