### ISSUE TITLE
Why Not add more Models parameters  from Controllers and  Let ControllerName and ActionName more easy get in View?

### ISSUE THREAD

**Issue by sgf** [aspnet/Mvc#4156]
### Why Not add more Models parameters  from Controllers
In HomeController.cs
`return View(Index,userinfo,msglist,...); //userinfo is a model,msglist are  models`  <br>
maybe a limit for count of the models parameters ( Max best most is 8 too much model limit is meaningless)

and in Home/Index.cshtml

`
Model1,Model2,Model3,Model4,Model5,Model6,Model7,Model8
 if(Model1.HasValue)
{
 <a asp-for='Name' value='Model1.Name'>....
}
`

### Let ControllerName and ActionName more easy get in View?

In Index.cshtml
`
\<h2\>@:this.ControllerName / @:this.ActionName \</h2\>
`
### another problem is why not let route system more easy use?
i know currently the route system of asp.net mvc is very strong!
but its still little complex !

im a noob and i just hope MVC framework more easy to use and more and more popular !

i think if (u,me,we,all asp.net mvc ) want to grow,need study good(merit) from competitor.
discard the dross and select the essence !

**Comment by Eilon** [comment]
You can already easily pass in however much data you want to the view using ViewData/ViewBag:

```c#
ViewData["model1"] = model1;
ViewData["model2"] = model2;
...
ViewBag.Model1 = model1;
ViewBag.Model2 = model2;
```

And you can read these just as easily from the view.

To get the controller name and action name from the view you can access RouteData values and read the "controller" and "action" keys.

The reason these aren't first-class items is that they are not very common patterns.
