### ISSUE TITLE
Providing Default Values for TagHelper Properties

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#4157]
If I have the following tag helper for implementing [Subresource-Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) (Available soon [here](https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d) for those interested):

```
[Flags]
public enum SubresourceIntegrityHashAlgorithm
{
    SHA256 = 1,
    SHA384 = 2,
    SHA512 = 4
}  

[HtmlTargetElement("script", Attributes = "asp-subresource-integrity")]
public class SubresourceIntegrityTagHelper : TagHelper
{
    [HtmlAttributeName("asp-subresource-integrity")]
    public SubresourceIntegrityHashAlgorithm HashAlgorithms { get; set; } 
        = SubresourceIntegrityHashAlgorithm.SHA256;

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        // ...
    }
}
```

I would like to use the default value I have given on the property above so that I do not have to provide the property with a value when using it:

```
<script asp-subresource-integrity src="..."></script>
```

Instead of:

```
<script asp-subresource-integrity="SubresourceIntegrityHashAlgorithm.SHA256" src="..."></script>
```

Related [StackOverflow](https://stackoverflow.com/questions/35623845/default-values-for-asp-net-core-taghelper-properties) question.

**Comment by NTaylorMullen** [comment]
Adding `Attributes = "asp-subresource-integrity"` to your `HtmlTargetElement` says that your `TagHelper` MUST have that attribute present in order to run. Therefore, if you change your `HtmlTargetElement` to: `[HtmlTargetElement("script")]` your `TagHelper` will run on every `script` tag.

**Comment by RehanSaeed** [comment]
I'd rather it not run on every script tag, only script tags using a CDN.

**Comment by NTaylorMullen** [comment]
Of course, so when it's present it'll use whatever the user provides and when it's not it'll use your default (which you set). I think I'm missing a piece of the functionality you want.

**Comment by RehanSaeed** [comment]
It does not make sense to add subresource integrity to script tags which point to local resources, only CDN resources. In fact, you will soon be able to add it to anything with a src or href attribute so I've split the tag helper in two and changed the tag helper to only require these attributes:

```
[HtmlTargetElement(Attributes = "href,asp-subresource-integrity")]
public class HrefSubresourceIntegrityTagHelper : SubresourceIntegrityTagHelper { ... }

[HtmlTargetElement(Attributes = "src,asp-subresource-integrity")]
public class SourceSubresourceIntegrityTagHelper : SubresourceIntegrityTagHelper { ... }

public class SubresourceIntegrityTagHelper  : TagHelper
{
        [HtmlAttributeName("asp-subresource-integrity-hash-algorithm")]
        public SubresourceIntegrityHashAlgorithm HashAlgorithms { get; set; } 
            = SubresourceIntegrityHashAlgorithm.SHA512;
}
```

I have also turned `asp-subresource-integrity` into a placeholder property and added another `asp-subresource-integrity-hash-algorithm` property. This is not ideal, so now I have to do this:

```
<!-- Default -->
<script asp-subresource-integrity 
        src="..."></script>

<!-- Customized -->
<script asp-subresource-integrity 
        asp-subresource-integrity-hash-algorithm="SubresourceIntegrityHashAlgorithm.SHA256"
        src="..."></script>
```

Instead of this:

```
<!-- Default -->
<script asp-subresource-integrity 
        src="..."></script>

<!-- Customized -->
<script asp-subresource-integrity="SubresourceIntegrityHashAlgorithm.SHA256"
        src="..."></script>
```

**Comment by Eilon** [comment]
Moving to backlog. FYI @DamianEdwards @NTaylorMullen

**Comment by rynowak** [comment]
@NTaylorMullen @Eilon do we know what the feature is that's being asked for here?

Can Tag Helper intializers solve this problem?

**Comment by DamianEdwards** [comment]
Not sure on this one, there might still be something here.

**Comment by dougbu** [comment]
Given the way tag helpers work, we don't think there's anything we can do here.
