### ISSUE TITLE
Rename dnxcore50 to netcore50

### ISSUE THREAD

**Issue by ToddThomson** [aspnet/Mvc#4158]
I'm not sure if this is in the works or not with dnx -> cli, but "dnxcore50" is confusing ( at least to me ).

**Comment by pranavkm** [comment]
We're going to rename all our TFMs shortly. https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md has some specs on what the TFMs are going to look like going forward.
