### ISSUE TITLE
ScriptTagHelper include ordering

### ISSUE THREAD

**Issue by chrispickford** [aspnet/Mvc#4163]
The `asp-src-include` directive does not allow for the ordering of script libraries where some might be dependent on others.

For example, `bootstrap.js` is dependent on `jquery.js` but because the files are included in alphanumerical order, the dependency is broken.

    <script asp-src-include="~/js/*.js"></script>

Produces:

    ...
    <script src="/js/bootstrap.js"></script>
    <script src="/js/jquery.js"></script>
    ...

Gives error:

> Uncaught TypeError: Cannot read property 'fn' of undefined

**Comment by dougbu** [comment]
Where these relationships exist, recommend _not_ using globbing. For example, the templates that ship with VisualStudio include the following in `_Layout.cshtml` files:
``` html
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
```

**Comment by Eilon** [comment]
Indeed, this is just not a scenario where globbing should work. What some people do (though I don't necessarily recommend it) is rename their script files to be 00_somescript.js, 01_anotherscript.js, 02_coolscript.js, etc.

Or just don't use globbing.
