### ISSUE TITLE
Model passed in post request into action is always null, if WebApplication.Run called in Task.Run

### ISSUE THREAD

**Issue by flcl42** [aspnet/Mvc#4164]
If I code entry point as:

 ```
public static void Main(string[] args)
{
    Task.WaitAll(
        Task.Run(() => Microsoft.AspNet.Hosting.WebApplication.Run<Startup>(args))
        );
    ...
}
```

but not in default way like: 

```
public static void Main(string[] args)
{
    Microsoft.AspNet.Hosting.WebApplication.Run<Startup>(args))
}
```

I get `null` in form data variable in my action, which looks like:

```
public void Post(string id, [FromBody]InputData data)
```

**Comment by kichalla** [comment]
@flcl42 why are you doing this?
```
Task.WaitAll(
        Task.Run(() => Microsoft.AspNet.Hosting.WebApplication.Run<Startup>(args))
        );
```

**Comment by flcl42** [comment]
@kichalla cos I build app with interactive console and want to run server in separate non-blocking thread. It also required while develop modular apps.

**Comment by kichalla** [comment]
@flcl42 if the data in the request body is of content type `application/x-www-form-urlencoded`, then you must not be using `FromBody` attribute. This attribute is for content types like `application/xml`, `application/json` etc. Try your scenario again by removing FromBody and let us know

**Comment by flcl42** [comment]
@kichalla but am using `application/json`

**Comment by kichalla** [comment]
In that case

- In the controller' action, can you check if the `ModelState` is valid and see if it has any errors.
- Can you share how your json data looks like and also of the `InputData` parameter?

**Comment by kichalla** [comment]
Closing this issue. Feel free to re-open it with more details.

**Comment by rynowak** [comment]
This is the likely issue:

`I get null in form data variable in my action,`

`public void Post(string id, [FromBody]InputData data)` 

`[FromBody]` is for JSON/XML data and doesn't work with form data
