### ISSUE TITLE
async calls during controller initialization

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Mvc#4165]
Hi all,
  I need to do some async calls during the intialization of a mvc controller, to inizialize the status once for every action

first step

>       public CentraleController(TraceContext db, UtentiCrud utentiCrud)
>         {
>             this._db = db;
>             this._utentiCrud = utentiCrud;
> 
>         }
> 

since I need to access the user I can't do anyway the calls here, since User.Identity.Name is not initialized. At this point I thought to move this code in the OnActionExecuting

>         public override void OnActionExecuting(ActionExecutingContext context)
>         {
>             base.OnActionExecuting(context);
> 
>             var user = _utentiCrud.FindByNameAsync(User.Identity.Name).Result;
>             utente = _db.Utenti.FirstOrDefault(ute => ute.AspNetUserId == user.Id);
>         }
> 

and it works, but I have to add the **.Result** in the end of the async call to make it work.
Since I would like to avoid calls to .Result or any other trick, I can try the async version of OnActionExecuting

>         public override Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
>         {
>             var user = await _utentiCrud.FindByNameAsync(User.Identity.Name);
>             utente = _db.Utenti.FirstOrDefault(ute => ute.AspNetUserId == user.Id);
> 
>             return base.OnActionExecutionAsync(context, next);
>         }
> 

It returns a task but it's not async so I have problems anyway. There is some clean way to do async calls during the controller initialization?

**Comment by pranavkm** [comment]
```C#
public override async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
{
    var user = await _utentiCrud.FindByNameAsync(User.Identity.Name);
    utente = _db.Utenti.FirstOrDefault(ute => ute.AspNetUserId == user.Id);

    await base.OnActionExecutionAsync(context, next);
}
```

Wouldn't this work?

**Comment by lucamorelli** [comment]
Ok, it's friday, I tried to add async but I have tried to replace the return with await.
thanks, now it's working.
