### ISSUE TITLE
(MVC 6) How to get an instance of IServiceProvider after a class is instantiated.

### ISSUE THREAD

**Issue by Serjster** [aspnet/Mvc#4167]
Unfortunately, as of right now, MVC requires that it be added as a service in ConfigureServices before Autofac is Built() that means for a Custom Model Binder that needs IServiceProvider can't get it injected in the constructor.

We add our model binder like this:

            services.AddMvc().AddMvcOptions(options =>
            {
                options.ModelBinders.Clear();
                options.ModelBinders.Add(new IoCModelBinder());

            });

and the binder itself looks like this:

    public class IoCModelBinder : IModelBinder
    {
        internal static IServiceProvider ServiceProvider { get; set; }

        public Task<ModelBindingResult> BindModelAsync(ModelBindingContext bindingContext)
        {
            var model = ServiceProvider.GetService(bindingContext.ModelType);
            bindingContext.Model = model;

            var binder = new GenericModelBinder();
            return binder.BindModelAsync(bindingContext);
        }
    }

At this point, we have to manually set the ServiceProvider  property from ConfigureServices after the DI is built! I know, super hacky. We'd like to somehow resolve it inside our BindModelAsync method. Basically make it look like this:

    public class IoCModelBinder : IModelBinder
    {
        private IServiceProvider serviceProvider;

        public Task<ModelBindingResult> BindModelAsync(ModelBindingContext bindingContext)
        {
            if (serviceProvider == null)
                serviceProvider = RESOLVETHISTHING<IServiceProvider >();

            var model = serviceProvider .GetService(bindingContext.ModelType);
            bindingContext.Model = model;

            var binder = new GenericModelBinder();
            return binder.BindModelAsync(bindingContext);
        }
    }

How do we do it?

**Comment by Serjster** [comment]
Of course, if we could somehow have IoCModelBinder be resolved for us that would work too, but since the DI hasn't been set up at this point yet, not sure how to do it. Or, if we could services.AddMVC() after creating the IServiceProvider in ConfigureServices that would work too. but every time we do that now... we get an exception in the Configure method at

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

Exception:
An exception of type 'System.InvalidOperationException' occurred in Microsoft.AspNet.Mvc.Core.dll but was not handled in user code
Additional information: Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddMvc()' inside the call to 'IApplicationBuilder.ConfigureServices(...)' or 'IApplicationBuilder.UseMvc(...)' in the application startup code.

Our ConfigureServices now:

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.Configure<RazorViewEngineOptions>(options =>
            {
                var expander = new CustomViewLocationExpander(ClientName);
                options.ViewLocationExpanders.Add(expander);
            });

            services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));

            services.AddSingleton(serviceType => Configuration);
            services.AddInstance<IConfiguration>(Configuration);

            services.AddCaching();
            services.AddSession();
            services.AddMvc().AddMvcOptions(options =>
            {
                options.ModelBinders.Clear();
                options.ModelBinders.Add(new IoCModelBinder());

            });

            var config = new ConfigurationBuilder()
                    .AddJsonFile(@"Configuration\autofac.json")
                    .AddJsonFile($@"Configuration\autofac.{ClientName}.json");

            var builder = new ContainerBuilder();
            builder.RegisterModule(new ConfigurationModule(config.Build()));
            builder.RegisterSource(new AnyConcreteTypeNotAlreadyRegisteredSource(x => x.Name.Contains("ViewModel")));
            builder.Populate(services);

            var container = builder.Build();
            var serviceProvider = container.Resolve<IServiceProvider>();
            IoCModelBinder.ServiceProvider = serviceProvider;

            return serviceProvider;
        }

This is all part of the bigger question started here:
http://stackoverflow.com/questions/35616035/mvc-6-custom-model-binder-with-dependency-injection

Of course the easiest thing would be to have a setting to enable the built-in Generic Model binder do the resolving for us automatically. Maybe in the next version?

**Comment by davidfowl** [comment]
This is already built into MVC https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ServicesModelBinder.cs. Just add a `[FromServices]` to your parameter or model object.

**Comment by dougbu** [comment]
Or, from the `BindModelAsync()` method, use `bindingContext.OperationBindingContext.ActionContext.HttpContext.RequestServices`. Bit uglier of course.

**Comment by Serjster** [comment]
Awesome! [FromServices] is exactly what we were looking for though bindingContext.OperationBindingContext.ActionContext.HttpContext.RequestServices helps too... at least for further reference. Thansk!
