### ISSUE TITLE
Preventing sensitive data from logging

### ISSUE THREAD

**Issue by gustafsonk** [aspnet/Mvc#4168]
What's the recommended approach for dealing with sensitive data from logs? Here's an example of what I'm seeing in RC1:

```
[Information] Protocol: HTTP/1.1  Method: GET  ContentType:   ContentLength:   Scheme: http  Host: somehost  PathBase:   Path: /device/authenticate  QueryString: ?id=someid&key=somesecret
Executing action method "Controllers.DeviceController.AuthenticateDevice" with arguments (["someid", "somesecret"]) - ModelState is Valid'
```

In this example, I'd like to remove the 'somesecret' part from these kinds of logs. The obvious answer is to turn off logging or at least increase the level above Info, but is there something else I'm missing?

**Comment by tuespetre** [comment]
If your secret is included in the request URI, all bets for privacy are off. The Basic authorization scheme exists for a reason.

**Comment by gustafsonk** [comment]
That's completely unrelated. We're using an OpenID Connect server as our authority and validating these kinds of calls with bearer tokens. We also use HTTPS so the request URL is protected. This is just an example of a call we make on the backend to integrate with another system.

**Comment by Eilon** [comment]
@blowdart / @lodejard any thoughts on this?

**Comment by blowdart** [comment]
Turn logs off or don't put it in the url. This is really no different to Apache or iis logging, both of those include the query string by default.

**Comment by rynowak** [comment]
We could also log the parameters or not depending on what level we're logging at, or have an option for this like EF.

**Comment by Eilon** [comment]
Not planning to do this at this time.

**Comment by brockallen** [comment]
perhaps it should be well documented that logging does not guarantee that sensitive stuff doesn't end up in the logs and thus should be discouraged for production scenarios.

**Comment by Eilon** [comment]
@brockallen I don't think that's the guidance we want to give. Just because they contain potentially sensitive data doesn't mean it shouldn't be used in production. It just means you need to secure the logs and control access to them, which I should hope any real service does anyway.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
