### ISSUE TITLE
Performance Scenario: Basic API

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4176]
**This is top-level performance scenario for 1.0.0. We're using this item to track the status and all of the individual improvements.**

Code here: https://github.com/aspnet/Performance/tree/dev/testapp/BasicApi
#### Summary

This is a simple API app that accepts a JSON post, updates a database, and returns JSON for a 201 created (including `Location` header). This should be naively written, and very similar to an 'update' API that a developer would generate with scaffolding.
- Attribute Routing (add 20-30 actions to build a bigger route table)
- Database (localdb)
- Bearer Token authentication
- Startup code similar to project template
- JSON body including 20-30 fields
# 
#### Variations

(None)
# 
#### Status

Scenario Status: **complete**

Known Investigations/Improvements:
- [ ] #4362  Carry the current ModelStateEntry on the ModelBindingContext

**Comment by rynowak** [comment]
Some allocation data after the updates - allocations for 3000 requests (as usual):

![image](https://cloud.githubusercontent.com/assets/1430011/13863377/8c145bb6-ec56-11e5-9c07-6a2a21800ccc.png)

**Comment by rynowak** [comment]
Update - Added a **GetById** variation that just reads pre-seeded data from the database:
![image](https://cloud.githubusercontent.com/assets/1430011/13992508/965883c2-f0d9-11e5-9c30-68b27ec3a38b.png)

**Comment by Eilon** [comment]
Moving to 1.0.0.

**Comment by rynowak** [comment]
**Update 5/23**

Allocation Data: 3000 requests

![image](https://cloud.githubusercontent.com/assets/1430011/15508619/0a705ac4-2185-11e6-98a4-0799e481f070.png)

The vast vast majority of allocation expense here is coming from EF and from the JWT authentication middleware. No regressions in the MVC/ASP.NET data and we should be in a much better place with reductions in Kestrel (headers) and MVC URL generation.


Sampling data is hard to summarize here - ~45% of request time is spent in the JWT middleware, and 37% in the action method itself (doing EF things). There are still a few areas of improvement for MVC.

-------------

Validation is about 4% of request time and seems like it could be improved by doing something similar to #4362 for validation or lazily creating strings used in validation. 

![image](https://cloud.githubusercontent.com/assets/1430011/15508841/f1399416-2185-11e6-9337-374545760c0a.png)

Searching the MSD is responsible for about 25% of validation's time.
