### ISSUE TITLE
Performance Scenario: Razor Code Generation

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4177]
**This is top-level performance scenario for 1.0.0. We're using this item to track the status and all of the individual improvements.**

Code here: https://github.com/aspnet/Performance/tree/dev/testapp/RazorCodeGenerator
#### Summary

This is a micro-benchmark for Razor code-generation of a large and complex `.cshtml` page.
- Big (~300kb)
- Lots of taghelper usage
- As close as possible to what runs in the editor for an MVC project
# 
#### Variations

(None)
# 
#### Status

Scenario Status: **complete**

Known Investigations/Improvements:
- [ ] aspnet/Razor#676 Don't use Span.Content
- [ ] aspnet/Razor#675 Cache Razor Tokens

**Comment by Eilon** [comment]
@NTaylorMullen please talk to @rynowak and see what data we need to collect for this scenario.

**Comment by rynowak** [comment]
**Update 5/23**

Allocation Data 10 iterations of code generation on MSN.cshtml
![image](https://cloud.githubusercontent.com/assets/1430011/15509250/a93498d0-2187-11e6-9e8f-660b5c070a4e.png)

Allocation Data 10 iterations of code generation on MSN.cshtml *with MVC TagHelpers*
![image](https://cloud.githubusercontent.com/assets/1430011/15509269/bd1a9750-2187-11e6-806f-485537230397.png)

The only really significant thing turned out from sampling was that 32% of time was spent in GC. On my machine, an iteration of code-generating MSN.cshtml takes about a second. The best way to improve this more is to focus on memory, by doing some of the things that have already been discussed in this thread.
