### ISSUE TITLE
Performance Scenario: Complex Views

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4178]
**This is top-level performance scenario for RC2. We're using this item to track the status and all of the individual improvements.**

Code here: TBD

#### Summary

This is a complex browser-based app that uses a variety of ASP.NET features. This should be written in an optimized, professional style with emphasis on features that would appear in a production application. The starting point for building is to evolve one of the more complex pages in Music Store
- Authentication (cookie)
- Database (localdb)
- Session
- Cache TagHelper
- Custom TagHelpers
- Layout Page
- View Components and Partials
- Diagnostics (logging)
- Localization

====================================

#### Variations
(None)

====================================

#### Status

Scenario Status: incomplete
- [ ] Write the code :laughing: 

Known Investigations/Improvements:
- [ ] TBD: Update with known issues

**Comment by rynowak** [comment]
Closing this. We're going to just track Music store's home page since that's already built and does most of the above already.

**Comment by dougbu** [comment]
@rynowak is this a "won't fix"er?
