### ISSUE TITLE
Duplicate Data in JSON Response

### ISSUE THREAD

**Issue by dontbesorry80** [aspnet/Mvc#4182]
I'm trying to use an ASP.NET 5 Controller to load data into the DataTables plugin. However I'm getting duplicate rows. I examined the response in Fiddler and I am receiving duplicated data in the separate chunks that are returned.

How do I stop this?

My function is pretty simple:

```
public IActionResult GetData()
{
    TableData tableData = new TableData();
    tableData.data = _db.DatatbaseObject.ToList();
    return Ok(tableData);
}
```

Please can you help me sort this out... I would post the result but it has some sensitive data in but looks something like this:

```
2000
{"data":[{dataObj1},{dataObj2}].....
2000
{"data":[{dataObj3},{dataObj1}].....
```

I've looked at various middleware articles to try and stop it chunking. But the chunking should be fine. It's the duplicate data that's the problem. Am I doing something wrong or is this not working. I'm using rc1-update1

**Comment by dontbesorry80** [comment]
Sorry it appears that the chunking isn't responsible for the duplicate data. Although I haven't discovered the problem for this.

**Comment by rynowak** [comment]
What is 

>  the DataTables plugin

I've never heard of this before... what this is, we're going to try to serialize as JSON, that's where I'd start looking.
