### ISSUE TITLE
Routes.IgnoreRoute not implemented?

### ISSUE THREAD

**Issue by ChrisFelstead** [aspnet/Mvc#4184]
Is routes.IgnoreRoute implemented in MVC6 yet? Is it coming? I can't seem to find any reference to it and need it to negate a wildcard route I have.

**Comment by Eilon** [comment]
@ChrisFelstead the work is being tracked here: https://github.com/aspnet/Routing/issues/47

But it's not currently planned for this release.

Can you add your scenario to the other issue so we can continue the discussion there? Thanks!
