### ISSUE TITLE
Razor Views Fail To Compile because DependencyContext does not load deps.json dependencies

### ISSUE THREAD

**Issue by guylando** [aspnet/Mvc#4185]
Since I upgraded to 1.0.0-rc2-16551 my project fails to compile razor views at runtime.
The errors I get are that the System namespace and other namespaces can not be resolved.
I debugged the issue into asp.net code and found that the problem is in DefaultRoslynCompilationService.cs which is supposed to compile the code using assemblies references taken from the current running assembly, however the list of referenced assemblies is empty in:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/DefaultRoslynCompilationService.cs#L110
I found that the referenced assemblies are attempted to be found using DependencyContext class in Microsoft.Extensions.DependencyModel namespace. 
The DependencyContext  class attempts to get the references from {project_name}.deps.json file which does not exist: https://github.com/dotnet/cli/blob/acd581c376c622743480176f75d7aed3088d5462/src/Microsoft.Extensions.DependencyModel/DependencyContext.cs#L52

This is an urgent bug which prevents me from continuing development. Please deal with this soon.

More information:
I am running asp.net mvc with target framework dnx451.

I tried to both compile the project with "preserveCompilationContext": true and without and it did not help. This flag is supposed to create the .deps.json resource according to: https://github.com/aspnet/Announcements/issues/149 but it does not create it.

**Comment by davidfowl** [comment]
> This is an urjent bug which prevents me from continuing development. Please deal with this soon.

If it's urgent why don't you downgrade to what used to work? It's Saturday and you can't expect this to be fixed until Monday at the very least.

**Comment by guylando** [comment]
Unfotunately my project.json files had rc2-* in all the dependencies (changed it now to concrete versions) and I have many projects in my solution so I don't know which version worked, and in addition I have upgraded all my code with the new changes (like the change in the HttpOkResult and HttpBadRequest, etc) so to revert all changes will hurt.

I do not expect this to be fixed soon if its really a bug in your code, however I would like to know if its really a bug in your code or is it a bug in my code.

**Comment by davidfowl** [comment]
> I do not expect this to be fixed soon if its really a bug in your code, however I would like to know if its really a bug in your code or is it a bug in my code.

Expecting any sort of investigation on the weekend is too much. Unless you already figured it out I wouldn't expect anything that will unblock you immediately.

**Comment by PinpointTownes** [comment]
@guylando the compilation errors you're seeing are probably caused by this (deliberate) change: https://github.com/aspnet/Mvc/pull/4139.

Luckily, https://github.com/aspnet/Mvc/pull/4171 will bring a new MVC/DNX compatibility package fixing these errors.

**Comment by guylando** [comment]
@PinpointTownes Thanks for your answer, you are probably right. Followup questions:
1)Do you know in which version of the packages did #4319 occure? (i am new to github, is there a way to see such information?)
2)Do you know when #4171 will be available on aspnetcidev feed?
Thanks!

**Comment by pranavkm** [comment]
@guylando, the package should be on the feed now.

**Comment by guylando** [comment]
That fixed my bug. Thanks!
Will never use wildcard * in my project.json again.
