### ISSUE TITLE
The trade mark "™" is turned into &#xFFFD; "�"

### ISSUE THREAD

**Issue by sumtec** [aspnet/Mvc#4195]
Hi,

I am not sure whether it is as designed but I feel really weird as it's not unicode &#xFFFD;.

``` csharp
@{
    ViewData["Title"] = "Hello world™";
    Layout = "_Layout";
}
<h1>@ViewData["Title"]</h1>
```

This shows:
Hello�

The html will be:
```html
<h1>Hello&#xFFFD;</h1>
```

What I expect is that it should be "&#x2122;" in the html. 

Regards,
Frank

**Comment by sergey-litvinov** [comment]
Are you sure that you specified correct value and saved view file with correct encoding? It works fine for me and here is working sample: https://dotnetfiddle.net/R3auoU for the same code as yours.

**Comment by Eilon** [comment]
Indeed, check that you have saved the file as UTF-8 or similar. If the file is ASCII/ANSI the special character would likely show up as a missing char.

**Comment by sumtec** [comment]
@Eilon , I think you are right. However, the VS can show the ™ instead of � even with a ANSI encoding. I think that make it hard to find out the cause. However, if you open that file in VS and save it with ANSI encoding by using a notepad, you can see it becomes �.

I guess the cause is that it assumed the file as UTF-8 encoding or similar if it can't figure out which encoding it is, e.g.: no preamble bytes offered.

**Comment by Eilon** [comment]
Different readers of files make different assumptions about the "default" encoding to use for an unknown file. See https://en.wikipedia.org/wiki/Bush_hid_the_facts for some examples :smile:

**Comment by sumtec** [comment]
Yes, it is. :smile:
