### ISSUE TITLE
ASP.NET Core 1.0 Cookies empty on subdomain

### ISSUE THREAD

**Issue by tdesmas** [aspnet/Mvc#4197]
I'm currently developing an ASP.NET Core 1.0 website but I've got a problem. The context is that my website is using a subdomain like sub.domain.com I set cookies on my application and it's working great.

When I go to the domain.com application, some cookies are set too.

Then, when I come back to sub.domain.com, the first cookies are still set and sent to the application but if I debug the application I see that the request context doesn't contain any cookie, nor the one I sent, nor any other one.

Do you have any idea ?

**Comment by Eilon** [comment]
@Tratcher any idea on this?

**Comment by Tratcher** [comment]
Invalid cookies? https://github.com/aspnet/HttpAbstractions/issues/515

**Comment by danroth27** [comment]
@tdesmas Can you confirm that your cookies are well formed? The RC1 bits are pretty strict in how they parse cookies.

**Comment by danroth27** [comment]
Closing for now. Please reactivate with the requested data.
