### ISSUE TITLE
Add docs for ApplicationModel and its related models

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#4199]
https://github.com/aspnet/Mvc/pull/4198#issuecomment-190838503

**Comment by danroth27** [comment]
Conceptual content is tracked by https://github.com/aspnet/Docs/issues/138. Presumably this is for API reference docs.

**Comment by Eilon** [comment]
@danroth27 that is correct.

**Comment by Eilon** [comment]
Closing due to lack of demand.
