### ISSUE TITLE
Trouble creating a basic MVC project

### ISSUE THREAD

**Issue by TJSoftware** [aspnet/Mvc#4200]
### Title
Trouble creating a basic MVC project

### Functional Impact
I am able to return a string from an MVC method in a controller, however when I set a controller method to return type of `IActionResult` I am unable to see the associated cshtml file.  Also, if I am running via Visual Studio I am not able to run this project at all (VS debugging crashes).

### Reproduce Steps
I have all the code here https://github.com/TJSoftware/MVCTesting
After I run `dotnet restore` then (optionally `dotnet build`) `dotnet run` I can use either IE or Chrome to go to `localhost:5000/home/index/1`, the page fails to load (blank in Chrome, displays 500 in IE).  If I navigate to `localhost:5000/returnstring/1` my string is returned.  

##### Chrome Debugger Tools
Console shows the error "Failed to load resource, the server responded with a status of 500".  No further details.

Network does not have any new infomation

##### IE Debugger tools
Console shows the error "SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request. GET - localhost:5000/home/index/1". no further details

Network does not have any new infomation

### Expected Result
Because I have `Views/Home/Index.cshtml` I would expect that the content of that page to be displayed.

### Actual Result
500 error

### Further tech details
λ dotnet
.NET Command Line Tools (1.0.0-beta-001584)

Project created with VS 2015, most edits were done in VS Code.

Package Feeds in VS 2015
![image](https://cloud.githubusercontent.com/assets/4823412/13443760/d57c3dbc-dfbf-11e5-9547-86423a99c290.png)

### What I have tried
I have tried to look at the samples in this repo, but I have not been able to get them to build.  See above if I am missing a package feed that is needed, but I verified that the items I am looking for exist.  Most the time I just turn off VS then `dotnet restore` then reopen VS and I am able to load all the dependencies, this has not worked for me on the MVC project.

Changing the startup configure to each of the following. `app.UseMvc()`, `app.UseMVC(routes => ...`, `app.UseMvcWithDefaultRoute()`.  Adding/Removing route tags to the controller (`[Route("[controller]")]`) and methods (`[HttpGet("Index/{id}")]`).

### What would be helpful
If there is something that I can be doing to debug this better I would appreciate it if you point me in that direction.

**Comment by rynowak** [comment]
Have you tried adding the developer exception page? https://github.com/aspnet/Mvc/blob/dev/samples/MvcSandbox/Startup.cs#L25

**Comment by TJSoftware** [comment]
Ugh, it is always a simple debugger add, I had the Diagnostics.  There is still an error in finding the cshtml file.  It is looking in the locations that I have.  Here is the new error.

```
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
```
P.S. My corgie is jelous of your corgie's fame ;).

**Comment by pranavkm** [comment]
@TJSoftware you'll have to specify the application base when using `dontet run`. From https://github.com/aspnet/Mvc/issues/4189#issuecomment-190028247, you'll need to run `dotnet run -- --applicationbase $PWD`.

**Comment by TJSoftware** [comment]
Thank you both for taking time to look at this.  I switched from Cmder to PowerShell to run the command so I could use the `$PWD` process working directory.  I kept it simple for the time being and I did not go into setting this in a config.  When I run the command `dotnet run -- --applicationbase $PWD` (after a `dotnet restore` and `dotnet build` (no errors) I see the following output...

```
PS C:\Projects\MyTesting\Frameworks\MVCTesting\src\MVCTesting> dotnet restore
log  : Restoring packages for C:\Projects\MyTesting\Frameworks\MVCTesting\src\MVCTesting\project.json...
info :   GET https://www.myget.org/F/aspnetcidev/FindPackagesById()?id='Microsoft.AspNetCore.Diagnostics'
info :   GET https://www.myget.org/F/aspnetcidev/FindPackagesById()?id='Microsoft.AspNetCore.IISPlatformHandler'
info :   GET https://www.myget.org/F/aspnetcidev/FindPackagesById()?id='Microsoft.AspNetCore.Server.Kestrel'
info :   GET https://www.myget.org/F/aspnetcidev/FindPackagesById()?id='Microsoft.AspNetCore.Mvc'
info :   GET https://www.myget.org/F/aspnetcidev/FindPackagesById()?id='Microsoft.AspNetCore.Mvc.Core'
info :   OK https://www.myget.org/F/aspnetcidev/FindPackagesById()?id='Microsoft.AspNetCore.Server.Kestrel' 938ms
info :   OK https://www.myget.org/F/aspnetcidev/FindPackagesById()?id='Microsoft.AspNetCore.Mvc' 936ms
info :   OK https://www.myget.org/F/aspnetcidev/FindPackagesById()?id='Microsoft.AspNetCore.Mvc.Core' 1148ms
info :   OK https://www.myget.org/F/aspnetcidev/FindPackagesById()?id='Microsoft.AspNetCore.Diagnostics' 1330ms
info :   OK https://www.myget.org/F/aspnetcidev/FindPackagesById()?id='Microsoft.AspNetCore.IISPlatformHandler' 1317ms
info : Committing restore...
log  : Restore completed in 2489ms.
NuGet Config files used:
    C:\Users\tj\AppData\Roaming\NuGet\NuGet.Config
Feeds used:
    https://www.myget.org/F/aspnetcidev/
PS C:\Projects\MyTesting\Frameworks\MVCTesting\src\MVCTesting> dotnet build
Project MVCTesting (.NETFramework,Version=v4.5.1) will be compiled because some of its inputs were newer than its oldest
 output.
Compiling MVCTesting for .NETFramework,Version=v4.5.1

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.3755202


PS C:\Projects\MyTesting\Frameworks\MVCTesting\src\MVCTesting> dotnet run -- --applicationbase $PWD
Project MVCTesting (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
Hosting environment: Development
Application base path: C:\Projects\MyTesting\Frameworks\MVCTesting\src\MVCTesting
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```
When I nav to the site using Chrome/IE I see ...
![image](https://cloud.githubusercontent.com/assets/4823412/13446609/1bd6c9dc-dfd2-11e5-94cc-fb7547f4c585.png)

I also cloned the https://github.com/aspnet/cli-samples that David Fowler suggested.  When I run that with the suggested parameters I receive a 404 error.  I did modify the Startup.cs code to add `app.UseDeveloperExceptionPage();`, I always forget that one, but that did not give me any new information.

![image](https://cloud.githubusercontent.com/assets/4823412/13446849/16d8c8fc-dfd4-11e5-9b49-5b5b20bffe5f.png)

I'm sorry, I am completely lost at this point.

**Comment by pranavkm** [comment]
Does your application have a `preserveCompilationContext`: true setting: https://github.com/aspnet/Mvc/blob/dev/samples/MvcSandbox/project.json#L8

**Comment by TJSoftware** [comment]
@pranavkm `preserveCompilationContext: true` took care of it.  Thanks for getting my project fixed.

When I compared my `project.json` to the HelloMvc example in https://github.com/aspnet/cli-samples I noticed some KVP settings that I was not familiar with (either I had not used them or they are new for `RC2`).  Looking at https://github.com/aspnet/Home/wiki/Project.json-file I found content, but no description.  I did not see tools on that page at all.  Is the home wiki the best place to find descriptions for project.json attributes?

**Comment by TJSoftware** [comment]
P.S.  I only needed to run the command `dotnet run`, allowing me to continue to use Cmder as I did not need to figure out the application base command there.

One more pet for this thread :wink: 

![img_20160202_115838](https://cloud.githubusercontent.com/assets/4823412/13465345/81cbf9f8-e052-11e5-8f35-4bfdbfc20d5b.jpg)

**Comment by TJSoftware** [comment]
Additional note, if using netstandardapp1.5 you must use the additional `--applicaitonbase` parameter.  I was only using net451 originally.

**Comment by jaseonline** [comment]
@rynowak This exception can be caused due to the Views folder not being published [for whatever reason]. As was the case for me. I don't know why it didn't publish the Views folder even though it was selected to be published.

**Comment by pranavkm** [comment]
@jaseonline are you hitting this issue - https://github.com/dotnet/cli/issues/3286?

**Comment by jaseonline** [comment]
@pranavkm Wow, sorry for the delayed response. I believe I was.
