### ISSUE TITLE
RazorCompilationService should throw a meaningful error when a user produces an application without `preserveCompilationContext`

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#4202]
When the compilation service encounters an application that has been compiled without the `preserveCompilationContext` flag - it attempts to compile the application without any reference assemblies. This invariably fails with messages such as `The type or namespace System could not be found.` See - https://cloud.githubusercontent.com/assets/4823412/13446609/1bd6c9dc-dfd2-11e5-94cc-fb7547f4c585.png. We should instead throw an exception that instructs users to add this flag to their project.json.

cc @davidfowl

**Comment by Eilon** [comment]
I'm fine doing this as long as it's a reliable thing to throw on. That is, if there are any legitimate cases where I have Razor views yet don't want `preserveCompilationContext` then we should reconsider this. But if it's truly needed 100% of the time then let's do it.
