### ISSUE TITLE
[Question] IOverrideFilter analog

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aspnet/Mvc#4203]
MVC5 used to have IOverrideFilter which allowed for authorization overrides on actions. Is there an analog in Core?

**Comment by danroth27** [comment]
IOverrideFilter is not currently available in Core. Do you have a specific scenario where you need it?

**Comment by MaximBalaganskiy** [comment]
I have a controller with most of actions available to admins only. Only a couple of them can be called by less privileged ones. Having an override would allow me to mark only a few actions.

Not a critical thing though, just thought I might be missing an existing filter...

**Comment by danroth27** [comment]
Not sure we we would add this specific feature back as it was implemented in MVC 5, but we could consider doing something to make this scenario easier.

**Comment by Eilon** [comment]
Closing because we have no plans to support this.
