### ISSUE TITLE
Bug unable to retrieve object when the object name is one object attribute

### ISSUE THREAD

**Issue by VGib** [aspnet/Mvc#4205]
Hello,
Tell me if I post in the right place.
Here is a program which reproduces the problem:
For the asp.net mvc controller:

```c#
 public class Obj
        {
            public string[] Values { get; set; }
        }

 [HttpPost]
        [Route("Sample")]
        public  ActionResult Index(Obj values)
        {
            return Content(string.Join(",", values.Values));
        }
```

For the testing program, which calls our controller:

```c#
public class Obj
        {
            public string[] Values { get; set; }
        }

        static void Main(string[] args)
        {
            var client = new HttpClient();
            var resp = client.PostAsJsonAsync("http://localhost:4093/Sample", new Obj { Values = new string[] { "a", "b" } });
            resp.Wait();
            var result = resp.Result.Content.ReadAsStringAsync();
            result.Wait();
            Console.WriteLine(result.Result);
        }
```

When you run this program, you'll have a null reference exception in the Controller's Index method. This is because the object values is null as there is already a property Values in the object.

I think, this is a bug, are you agree?

please let me know.

**Comment by VGib** [comment]
I've test version 5.2.3 of asp.net MVC

**Comment by dougbu** [comment]
This repository is for ASP.NET Core MVC, not MVC 5.2.3. Suggest filing this in the MVC 5.2.3 [repository](https://aspnetwebstack.codeplex.com/workitem/list/advanced).

On the other hand, it looks very much like you're submitting JSON to an action that handles only form-URL-encoded POST bodies (and query strings). Either change the controller to a Web API controller (`ApiController`) or submit for-URL-encoded data.
