### ISSUE TITLE
How to use the latest cidev build in a class library

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/Mvc#4209]
Hi, guys! Sorry to bother you but I am stuck for hours with no luck.

I have class library using the latest `cidev` builds of the `Microsoft.AspNetCore.Mvc` package. Today I updated and tried to use the new `netstandard1.5` (with or without the imports) framework but without any success. I have installed the latest .NET CLI but the project just does not compile at all (errors are quite a lot - `System.Object is not defined or imported` or similar). Tried from both Visual Studio and from the command line with `dotnet build`. SDK is `1.0.0-rc2-16566`.

Any help with compiling, running unit tests and eventually debugging them will be kindly appreciated. Thank you in advance!

**Comment by Eilon** [comment]
@pranavkm can you help out?

**Comment by pranavkm** [comment]
If you're referencing it from a `net4x` target (e.g. `net451`, `net46` etc) - you might have to add a frameworkAssembly reference to `System.Runtime`. See https://github.com/aspnet/Options/commit/689c754af91598b00752655e898f476ecc857d85#diff-4d79399e9d56c91059fe3d8f4a4416f9R21 for an example.

**Comment by ivaylokenov** [comment]
@pranavkm Thank you, superhero! 

Actually, when I updated everything to latest version, it **automagically** worked with this `project.json`:

```c#
{
  "title": "MyTested.Mvc",
  "description": "MyTested.Mvc is a powerful unit testing library providing easy fluent interface to test the ASP.NET MVC Core framework.",
  "version": "1.0.0-beta",
  "authors": [ "Ivaylo Kenov" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "compilationOptions": {
    "warningsAsErrors": true,
    "xmlDoc": true
  },

  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Session": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.TestHost": "1.0.0-rc2-*"
  },

  "frameworks": {
    "net451": { },
    "netstandard1.5": { }
  }
}
```

Closing the issue, as my question was answered. Thank you again! :+1:
