### ISSUE TITLE
Validating value type properties with [Required] attribute

### ISSUE THREAD

**Issue by gzak** [aspnet/Mvc#4211]
Because value types are non-nullable, they are assigned a default value during model binding. So for instance, if you have a `Birthday` property of type `DateTime` which is required on your model, and a date isn't supplied in the data posted to the controller, it will be assigned the value of `default(DateTime)`.

At that point, it's too late for model validation to enforce the `[Required]` attribute on that property, because even `default(DateTime)` counts as a value and therefore passes the `[Required]` validator.

One way to handle this is to run model binding in two phases, one pre-phase which only resolves where in the model each posted property will go (along with the validation attributes on the model at that destination), then a post-phase which does the actual assignment. In between, you can run the model validation on the posted object directly, with the validation information coming from the model based on the pre-phase.

**Comment by dougbu** [comment]
Use the framework-specific `[BindRequired]` attribute to ensure a value was included in the submission. (MVC pretty much calls `IsValid()`on `ValidationAttribute`s and does not reinterpret the results.)

FYI the `System.ComponentModel.DataAnnotations` namespace is part of CoreFx. You can find relevant sources at https://github.com/dotnet/corefx/tree/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations or file issues at https://github.com/dotnet/corefx/issues.

**Comment by gzak** [comment]
Is that supposed to be used in conjunction with the regular '[Required]` attribute? Or does this replace it? FWIW, I just tried using the `[BindRequired]` attribute, and the `TryValidateModel` still returns true.

What might be happening is that since I'm posting the object from C# in an integration test, and in the C# class it's a value type, it gets submitted with a default value in the request. Which means for C# integration tests at least, there's no way to catch it with the built-in attributes.

Let me know if I'm missing something here.

**Comment by dougbu** [comment]
`[BindRequired]` affects model binding only and that comes before validation. So nothing will change for your integration test around `TryValidateModel()`. However a real action will see errors in the `ModelStateDictionary` if a property with `[BindRequired]` is not bound (aka no data is provided for it).

> used in conjunction with the regular `[Required]` attribute? Or does this replace it?

The two attributes serve different purposes and should be used however your application requires. If the application needs to confirm data was submitted, use `[BindRequired]`. If the application needs to confirm a value is not `null`, use `[Required]`.

**Comment by gzak** [comment]
Nope, my hypothesis is false. I just tried posting an object of anonymous type with only a subset of the model's fields, so there's no way it could have filled in defaults for them. On the receiving end, `TryValidateModel` still returned true.

**Comment by dougbu** [comment]
`TryValidateModel()` does not model bind and `[BindRequired]` is not relevant if that's all you're doing. Either add a parameter to your action with the type i.e. do model binding automatically or call `TryUpdateModelAsync()`

**Comment by gzak** [comment]
I believe my action already has a parameter with the type, so model binding should be happening automatically. Something like this:

```
[HttpPost]
public async Task Post(MyModel m) { ... }
```

If I omit the properties of `MyModel` which are marked with the `[BindRequired]` attribute, the action is still invoked and `m` has defaults filled in.

I think I'm missing something here...

**Comment by dougbu** [comment]
In the scenario you're describing, there's no need to call `TryValidateModel()`. Check `ModelState.IsValid` and it should be `false` if no data is provided for the `[BindRequired]` properties.

**Comment by gzak** [comment]
Aha, perfect, that was exactly my problem. Thank you!

**Comment by gzak** [comment]
I swear I saw it work before I closed the ticket, but now this doesn't work. I posted an object with `[BindRequired]` value properties where those properties weren't set in the client (C# client, specifically), and `ModelState.IsValid` returns true in the controller. Something like this:

```
public class A { [BindRequired] Guid G { get; set; } }

await Client.PostAsync("some_url", new A().ToJsonContent()); // custom extension method which does what you think

// controller's ModelState.IsValid returns true when the request arrives
```

I still think it has something to do with the fact that when C# serializes an instance of `A`, because `G` is a value type, it gets assigned a default value (the generated JSON confirms this). This fools the `[BindRequired]` attribute. But I know for a fact that I've seen it work, and I was surprised that it did work, because that would imply the `Client

**Comment by gzak** [comment]
The only workaround I can think of is to make all value types nullable with `?`, then just use the `[Required]` attribute. This works 100% of the time, without any ambiguity.

**Comment by dougbu** [comment]
Is the action using `[FromBody]`? If yes, you must use Json.NET to control errors it adds. `[BindRequired]` doesn't apply in this new scenario.

**Comment by gzak** [comment]
It does, so that's likely my problem. I don't quite understand the fix, would you mind illustrating?

**Comment by gzak** [comment]
So why would this not be a bug / design flaw? It doesn't seem right that changing where in the request the object comes from (or changing the JSON library you're using) should allow the object to suddenly start bypassing the `[BindRequired]` attribute.

I suspect I know why it worked just fine earlier, and that's because the framework automatically decided that the object should be pulled from the body, without the `[FromBody]` attribution, and at that point the `[BindRequired]` attribute was working fine. I guess I made some kind of change, and suddenly the model parameter was coming in as `null`. I fixed it by adding the `[FromBody]` attribute, but then `[BindRequired]` stopped working. To me, that's a bug. Or why is that the expected behavior? It was certainly unexpected to me.

**Comment by dougbu** [comment]
`[BindRequired]` customizes the MVC model binding system . That's its purpose and it's working as designed.

`[FromBody]` switches the affected property or parameter into the different world of input formatting. Each input formatter (e.g. Json.NET and a small MVC-specific wrapper) can be considered a separate system with its own customization. The model binding system has no knowledge the details of JSON (or any other) deserialization.

In an ideal world, we would have a common set of attributes that work everywhere. Pragmatically that is not currently possible and, even if it were, every serializer / deserializer would still have its own additional attributes.

**Comment by Ciantic** [comment]
> The only workaround I can think of is to make all value types nullable with ?, then just use the [Required] attribute. This works 100% of the time, without any ambiguity.

I also find this odd behavior. To make a value required, you have to make it nullable and then add Required attribute? 

From users perspective it makes no sense, now you have nullable property which is guarenteed to have a value. It may make sense in a API level, but not when you are using the API.

**Comment by nikibobi** [comment]
How does [BindNever] work with value types? Does my type have to be nullable? Also I'm using [FromBody] as well and none of the attributes are working. What is a workaround? I have a simple POST action method that it needs to accept JSON. Do I have to remove the [FromBody] atribute or do I have to use key value url pairs for that? Sorry if that's a lot of questions

**Comment by dougbu** [comment]
> How does `[BindNever]` work with value types?

The model binding system will not attempt to bind the value.

> Does my type have to be nullable?

No, it will be left at its default value.

> What is a workaround?

Your problem is not clear. Please open a new issue describing what you're doing, what you expect, and and what is happening instead.
