### ISSUE TITLE
Move IUrlHelper to an abstractions assembly

### ISSUE THREAD

**Issue by strohhut** [aspnet/Mvc#4214]
I have a standard class library that provides ASP.NET specific utility methods that are independent from the app specific logic of concrete ASP.NET projects. For example I have a bunch of extension methods for `HttpRequest`.

Would it be possible to move `IUrlHelper` to an abstractions assembly so I can implement utility methods outside of the web project that require an `IUrlHelper`? Otherwise I have to implement my own `IUrlHelper` interface in my class library and then a class in my web project that implements it and that is a wrapper around the real `IUrlHelper`.

I can use `IActionResult` in a standard class library for instance. It would be nice if this was possible with `IUrlHelper` too.

**Comment by rynowak** [comment]
@strohhut - are you talking about moving it to `Microsoft.AspNetCore.Mvc.Abstractions`?

/cc @Eilon - I don't really see any reason why we couldn't do this.

**Comment by strohhut** [comment]
@rynowak Yes that's what I'm talking about.

I just saw that `UrlRouteContext` and `UrlActionContext` which `IUrlHelper` uses are also not inside `Microsoft.AspNetCore.Mvc.Abstractions` so my wrapper workaround cannot be implemented that easily. Also this means only moving `IUrlHelper` into `Microsoft.AspNetCore.Mvc.Abstractions` won't work then I guess.

**Comment by rynowak** [comment]
We would move all three types. Those two contexts are just parameter-objects they don't have any behavior.

**Comment by strohhut** [comment]
Sounds great. It makes it easier for helper libraries.
