### ISSUE TITLE
ServiceLocator: AddImports class RazorPage,ControllerBase,ViewComponent

### ISSUE THREAD

**Issue by HaoK** [aspnet/Mvc#4216]
Things like these can be roundtripped together once:

```
                    _tagHelperActivator = services.GetRequiredService<ITagHelperActivator>();
                    _bufferScope = services.GetRequiredService<IViewBufferScope>();
                    _typeActivatorCache = services.GetRequiredService<ITypeActivatorCache>();
```

**Comment by Eilon** [comment]
Perhaps the RazorPage activator should just set these because they're always needed anyway.

**Comment by javiercn** [comment]
Round-tripping these things together is tricky, we can group them in a new class ControllerBaseDependencies and so on that we can register on DI and we can make all the properties in the class try to access that property if the value for their field is null, but these classes are normally part of a hierarchy (ControllerBase,Controller), (RazorPage, RazorPageOf<T>) and it would have an impact in  unit testing scenarios (They would need to register this extra class for some unit tests to pass).

Many of the mentioned dependencies are optional (You don't need a UrlHelperFactory if you don't use Url on controller and so on) and are designed that way to allow for easy unit testing.

The technical solution to do this would be something like this:
```C#
class ControllerBaseDependencies{
   public ControllerBaseDependencies(IUrlHelperFactory factory, ...)
   {
      ...
   }
   ...
}

class ControllerDependencies{
   public ControllerDependencies(IUrlHelperFactory factory, ...)
     : base(factory, ...)
   {
      ...
   }
   ...
}


class ControllerBase {
   internal virtual ControllerBaseDependencies {
     get 
     {
          if(_dependencies == null)
          {
              _dependencies = HttpContext.RequestServices.GetRequiredService<ControllerBaseDependencies>();
          }
         return _dependencies;
     }

   public IUrlHelper Url
   {
      get
      {
           if(_urlHelper == null){
              _urlHelper = ControllerBaseDependencies.UrlHelperFactory.CreateUrlHelper(ControllerContext);
          }
         return _urlHelper;
      }
   }
}

class Controller : ControllerBase {
   internal override ControllerBaseDependencies {
     get 
     {
          return ControllerDependencies;
     }

  internal ControllerDependencies {
    get
    {
          if(_dependencies == null)
          {
              _dependencies = HttpContext.RequestServices.GetRequiredService<ControllerDependencies>();
          }

         return _dependencies;
    }

    public IViewEngine ViewEngine 
   {
      get
      {
           if(_viewEngine == null){
              _viewEngine = ControllerDependencies.ViewEngine;
          }
         return _viewEngine;
      }
   }
  }
} 
```

It's a lot of code for not a lot of benefit as this GetRequiredService calls are emitted only in case the properties are accessed and are null, so I think this bug can wait post 1.0.0. if we want to do anything at all.

Thoughts? @Eilon @rynowak @dougbu

**Comment by Eilon** [comment]
Yeah this is totally not worth it.

**Comment by dougbu** [comment]
@javiercn "won't fix"?
