### ISSUE TITLE
ServiceLocator: Review AuthorizeFilter.OnAuthorize

### ISSUE THREAD

**Issue by HaoK** [aspnet/Mvc#4219]
```
            var httpContext = context.HttpContext;
            var authService = httpContext.RequestServices.GetRequiredService<IAuthorizationService>();

            // Note: Default Anonymous User is new ClaimsPrincipal(new ClaimsIdentity())
            if (httpContext.User == null ||
                !httpContext.User.Identities.Any(i => i.IsAuthenticated) ||
                !await authService.AuthorizeAsync(httpContext.User, context, Policy))
            {
                context.Result = new ChallengeResult(Policy.AuthenticationSchemes.ToArray());
            }

```

**Comment by javiercn** [comment]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L76 is the only place where we use DI, the filter doesn't do any logging which we might want to do? (for example unauthorized requests). In any case, the solution in this case would be to change the code to have a FilterFactory that creates an instance of the filter that is not reusable, as it requires a transient service (DefaultAuthorizationService). While this is more "correct" from a design perspective, it only introduces an extra layer without too much benefit (The filter factory receives an instance of the service provider, so is just moving the composition root one layer above). I'm inclined to leave this one as is unless we decide we want to do some logging here (in which case it'll be good to have a known composition root).

Thoughts @rynowak @Eilon

**Comment by Eilon** [comment]
If the value is low, skip it.

Adding logging would be a different task unrelated to this.

**Comment by Eilon** [comment]
Removing 3-Done because we didn't "do" it.

**Comment by dougbu** [comment]
@Eilon does that make this one "won't fix"? More generally, is a bare "task" fine to close w/o further clarification?

**Comment by ewan-derivco** [comment]
On the point of logging. Is it even possible for a developer to log authorization failures using [Authorize]? It seems like you have to write your own Attribute and Filter if you want to get any detail other than 'is the result a 401/403?'

**Comment by rynowak** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
