### ISSUE TITLE
ServiceLocator: Make DefaultDisplay/EditorTemplate => service

### ISSUE THREAD

**Issue by HaoK** [aspnet/Mvc#4221]
Currently static helpers that GetRequiredService, convert into a service instead.

**Comment by javiercn** [comment]
There is a cyclic dependency between DefaultEditorTemplates, TemplateBuilder and TemplateRenderer

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/DefaultEditorTemplates.cs#L107
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/TemplateBuilder.cs#L125
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/TemplateRenderer.cs#L42

We can do some changes to create a TemplateRenderingContext class containing all the singleton services to prevent multiple calls for resolving singleton services, but we can't remove the calls to GetRequiredService for IHtmlHelper as it needs to be unique per item in the recursion tree.

All the classes involved are internal so we have room in the future to change them if we want to fix this, so this can wait post 1.0.0.

**Comment by dougbu** [comment]
> we can't remove the calls to `GetRequiredService` for `IHtmlHelper` as it needs to be unique per item in the recursion tree

Technically `TemplateRenderer` _must_ have a distinct `IHtmlHelper` instance from its caller (either another `IHtmlHelper`, `Default[Display|Editor]Templates.CollectionTemplate()`, or `Default[Display|Editor]Templates.ObjectTemplate()` -- always via `TemplateBuilder`). But we could refactor things so the `DefaultDisplayTemplates` and `DefaultEditorTemplates` methods reuse and re-`Contextualize()` a single `IHtmlHelper` instance. Would reduce the number of `GetRequiredService<IHtmlHelper>()` calls but not get rid of them.

`HtmlHelper` already gets the singletons that would go into a `TemplateRenderingContext`: `ICompositeViewEngine`, `IModelMetadataProvider`, `IViewBufferScope`. Could be a `HtmlHelperContext` used throughout these classes.

@javiercn why did you close this issue? Shouldn't it remain open but in the Backlog or perhaps `1.0.1`?

**Comment by javiercn** [comment]
@dougbu @eilon suggested I close it, but feel free to move it to backlog if you feel we might want to tackle it in the future.

**Comment by Eilon** [comment]
We decided to close this, not backlog. The value here is negligible.

**Comment by dougbu** [comment]
Got it.

Related Ryan-related question (for @rynowak): Do `HtmlHelper`, `TemplateBuilder` or `TemplateRenderer` show up in recent memory profiles enough for pooling them to be worthwhile? Reusing any of them across properties of a complex type, collection elements, view component views, and partials might be relatively simple and could leverage existing services e.g. `RazorPageActivator`. Would solve the `GetRequiredService()` issue that led to this one.

**Comment by rynowak** [comment]
I've seen `TemplateBuilder` + `TemplateRenderer` show up in memory profiles, though not as super high impact. With this subsystem is more concerned about sampling/execution.

I'm OK with closing this for 1.0.0. It seemed like a straightforward win at the time of filing, but it seems clear now that it's not. 


Bonus Opossum:

![](https://s-media-cache-ak0.pinimg.com/736x/8f/fc/d0/8ffcd09b1cf3425b45a866cb130d43a7.jpg)

**Comment by dougbu** [comment]
@javiercn should this be labelled as won't fix?
