### ISSUE TITLE
Edge not refreshing data

### ISSUE THREAD

**Issue by bdelaney** [aspnet/Mvc#4229]
At first thought this was only an issue when running IISexpress and project locally. Gave up on using Edge for any kind of debugging because even with aggressive refreshing it was not updating various things, including javascript changes. But mostly data.
Began running all the time in Chrome and everything was refreshing just fine.

Now deployed the RC1 MVC app to Azure. Running in Edge I can create new data, but it never updates, no matter what I do with local browser cache, and it does not change even when I restart the web app.
Meantime Chrome is merrily accepting data updates and displaying them without any aggressive refreshing.

Tried opening new private window in Edge and it picked up all the old changes, but then when I created new data, it also failed to update.
This behavior only with my new aspnet web app. Other MVC 5 apps that are database backed like this one are working fine in Edge.

I should mention this is over https.
Clearing browser cache and refreshing does help.

**Comment by javiercn** [comment]
Do you see the same response comming back if you use a tool like fiddler? Do you see edge performing a network request when you reload the page?

**Comment by Eilon** [comment]
If this really seems like an Edge-specific issue I recommend using Edge's menu option to launch the Windows Feedback app and report the issue there.

**Comment by bdelaney** [comment]
Done! Entered problem in Windows Feedback app.
