### ISSUE TITLE
Integration tests and Startup.cs / appsettings.json

### ISSUE THREAD

**Issue by gzak** [aspnet/Mvc#4230]
We're using `Microsoft.AspNet.TestHost.TestServer` to host an instance of our application within the context of integration tests in an adjacent test project within our solution (the usual setup, in other words). We have several environments in which we'd like to have these integration tests run, and the application project itself has the usual `appsettings.*.json` files set up for each environment along with a `Startup` class to get it all bootstrapped.

The test project reuses the same `Startup` class from the main project in its `TestServer` initialization.

I tried setting the `Hosting:Environment` environment variable to Development within the test's `.xproj` file, but when the test executes within VS, the environment still resolves to Production (which appears to be the default value for that property). How do I set environment variables for test projects?

More generally, I'm curious what the best practices are for integration testing:
- Should there be a custom `TestStartup` class for integration test projects?
- Should there be a separate set of `appsettings.*.json` files specifically for the test project?
- Is it common to have integration tests run in multiple environments, or is it more typical to have a single dedicated integration testing environment?

**Comment by davidfowl** [comment]
> I tried setting the Hosting:Environment environment variable to Development within the test's .xproj file, but when the test executes within VS, the environment still resolves to Production (which appears to be the default value for that property). How do I set environment variables for test projects?

I'm curious how you even set environment variables in the .xproj. With an MSBuild property? 

We don't really have any best practice guidance as yet but:

> Should there be a custom TestStartup class for integration test projects?

I'd say no, you can author your `Startup` class with the idea that configuration settings and other things have the ability to be set from the hosting envrionment.

> Should there be a separate set of appsettings.*.json files specifically for the test project?

Seems like a fine thing to do. 

> Is it common to have integration tests run in multiple environments, or is it more typical to have a single dedicated integration testing environment?

I think the latter is more common.

**Comment by gzak** [comment]
> I'm curious how you even set environment variables in the .xproj. With an MSBuild property?

From the docs [here](https://docs.asp.net/en/latest/fundamentals/environments.html#development).

**Comment by davidfowl** [comment]
Oh, launch profiles are fine, you just set the wrong variable name. `Hosting:Environment` is deprecated.

**Comment by gzak** [comment]
Changed to `ASPNET_ENV`, still returns Production...

**Comment by danroth27** [comment]
@gzak Are you sure you are specifying the env var for the correct launch profile? I think you would need to set it in the profile for the test command. Could you show us your project file where you specify the env var?

**Comment by gzak** [comment]
Here's the entire body of the `launchSettings.json` file:
```
{
  "profiles": {
    "test": {
      "commandName": "test",
      "environmentVariables": {
        "ASPNET_ENV": "Development"
      }
    }
  }
}
```

**Comment by gzak** [comment]
And here's a screenshot of the corresponding project properties view in VS:

![capture](https://cloud.githubusercontent.com/assets/817765/13579476/a102dc8e-e452-11e5-9dcc-b79251e68051.PNG)

**Comment by danroth27** [comment]
@BillHiebert @barrytang @rynowak Any ideas why the env var in the test launch profile would not get honored when running unit tests?

**Comment by Eilon** [comment]
Seems related: https://github.com/aspnet/Testing/issues/202

**Comment by barrytang** [comment]
@vijayrkn?

**Comment by vijayrkn** [comment]
Currently the VS Test adapter only looks are the target runtime information from the test profile. VS test adapter does not pass the environment variables from the test profile to the Unit test runner process.

**Comment by Eilon** [comment]
I moved the bug here: https://github.com/aspnet/Tooling/issues/456

So closing this one.
