### ISSUE TITLE
AuthorizationFilterAttribute returns UnauthorizedResult rather than ChallengeResult

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#4233]
RE: https://github.com/aspnet/Security/issues/720#issuecomment-192490540

This regressed at some point. Authorization failures should result in a challenge. The auth middleware will take over and decide what to do with it.
@blowdart @HaoK

**Comment by blowdart** [comment]
What will ChallengeResult end up with if there's no auth middleware?

**Comment by Tratcher** [comment]
An error saying nobody accepted the challenge. `[Authorize]` without auth providers is nonsensical.

**Comment by rynowak** [comment]
Authorize requires an auth policy now, so presumably a configuration without providers would have failed earlier right?

**Comment by PinpointTownes** [comment]
> Authorization failures should result in a challenge. The auth middleware will take over and decide what to do with it.

IMHO, this design has always been absolutely evil and semantically "nonsensical". The only place where we know exactly why authorization failed (not authenticated?, lack of permissions?) is in the authorization service. Taking such a decision at the authentication middleware level (by trying to determine whether `AuthenticateAsync` returned a principal or not) is just wrong.

A while ago, I had designed a prototype moving the challenge/forbidden decision to the authorization service and introducting an `AuthorizationResult` determining why the authorization process failed: https://github.com/PinpointTownes/Security/commit/7ac1a2515015a98dc6f4919f28baa9db33beb50a

**Comment by rynowak** [comment]
Do we need to provide `AuthorizationFilterAttribute` as a base-class? IMO we shouldn't make it easy to replace the auth system.
