### ISSUE TITLE
Debugging on MacOS - When will we get it?

### ISSUE THREAD

**Issue by johnvpetersen** [aspnet/Mvc#4236]
Realistically - how far are we from being able to debug server side code on the Mac? I ask because as it stands right now, that is the one major thing missing from the dev experience.

**Comment by Eilon** [comment]
Any Mac debugging experience would presumably be done primarily through Visual Studio Code, so I recommend asking on the VS Code repo: https://github.com/Microsoft/vscode

Thanks!

**Comment by johnvpetersen** [comment]
Interesting answer. Very well, I'll take it up with them.
