### ISSUE TITLE
Re-instate tests on Mono

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#4238]
In #4234 we disabled some tests on mono due to dotnet/cli#1613. Once that is resolved we should re-instate these tests.

**Comment by dougbu** [comment]
Reopening because @rynowak's commit did not relate.

**Comment by ryanbrandenburg** [comment]
Isn't the task for this now to remove Mono specific things from the code?

**Comment by dougbu** [comment]
@ryanbrandenburg what labels should this issue have i.e. is it "done" again? I know @rynowak's commit was unrelated but am not sure whether this and #4153 were dupes.

**Comment by ryanbrandenburg** [comment]
#4153 led to this, so they are not dupes. I seem to remember @Eilon telling me to just close this, though I don't remember exactly why (a lesson to me to always give a reason when closing out an issue).

@Eilon do you remember why that was?

**Comment by Eilon** [comment]
This is a bug about some mono test. Why does it matter?
