### ISSUE TITLE
Should we use the Razor file name being compiled in constructing the assembly name being codegened by DefaultRoslynCompilationService?

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#4239]
Right now we use a randomly generated assembly name. Using the modules window to look up which assembly maps to a specific view is pretty impossible. We could add the view name \ view path to the codegened-assembly to make it a bit easier for diagnostics.

**Comment by rynowak** [comment]
That would be pretty cool - are there real scenarios where you'd need to do this? We already do this for the type name.

**Comment by pranavkm** [comment]
I ran into this when adding tests for the compilation service - haven't had a real life use case for it as yet. Just thought it might be nice to have

**Comment by pranavkm** [comment]
We haven't had any user requests for this. Closing this for now. We could always choose to do this since it doesn't affect any user facing API.
