### ISSUE TITLE
How to save form data after submitted

### ISSUE THREAD

**Issue by bivokasaju** [aspnet/Mvc#4241]
I have a bunch of select tags whose option value I want to save even after the form is submitted. Currently, the value resets to the top value after submission.

I tried the following method but it doesn't work! It selects the last option of the `for ` loop in this code.

```
        <select class="form-control" id="selYear" name="selYear">
                @for (var i = 2016; i > 1999; i--)
                {            
                    if(IsPost)
                    {
                        <option value="@i" selected='@(Request.Form["selYear"].Equals(i.ToString()) ? "selected" : "")'>@i</option>
                    }
                    else
                    {
                        <option value="@i" >@i</option>
                    }
                                       
                }
            </select>
```

Does anyone have a solution for this? Please provide some sample codes/examples.

**Comment by tuespetre** [comment]
This seems more appropriate for http://stackoverflow.com/questions/ask

**Comment by Eilon** [comment]
Indeed, this general type of question is more suitable to StackOverflow.

Having said that, I recommend using the `<select>` tag helper or `Html.DropDownList[For]()`, which will automatically preserve the selected value.
