### ISSUE TITLE
RazorPage activation is too expensive

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4244]
Sampling data, with 100% set to time executing the view (30% of request total)

Update: this was largely due to a temporary regression in GetRequiredService. We need to remeasure.

This is what it looks like now: 
![image](https://cloud.githubusercontent.com/assets/1430011/13678898/fff26c00-e6a5-11e5-83b8-2851ced196fd.png)

Activation is about 7.5% of view execution, and of that half is the VDD creation which is being worked on actively. Still worth looking at.

Certain things that are part of the activator's workload are singletons that we can close over. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorPageActivator.cs#L125

We should use the `GetRequiredService` calls as a guide for things we can cache and handle specially.
![image](https://cloud.githubusercontent.com/assets/1430011/13679047/9bfbbee4-e6a6-11e5-9279-65d41d8f1797.png)

**Comment by sebastienros** [comment]
Is it including the first hits or is the view _warmed up_?

**Comment by rynowak** [comment]
> Is it including the first hits or is the view warmed up?

Assume it's always warm unless otherwise specified

**Comment by rynowak** [comment]
Update: this was largely due to a temporary regression in GetRequiredService. We need to remeasure.

**Comment by rynowak** [comment]
Some fresh data here - bottom up sampling of HelloWorldMvc 
![image](https://cloud.githubusercontent.com/assets/1430011/14117175/4b89572c-f598-11e5-98f1-b768e03f01aa.png)

We should avoid hitting the service provider when we know it's a singleton.

**Comment by rynowak** [comment]
The work here is to have the `RazorPageActivator` special case some of the things that are known to be singletons so that we can avoid roundtripping to the service provider.
