### ISSUE TITLE
CacheKey equatable object in CacheTagHelper

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#4246]
- Prevent string allocations
- Fix hash collision by checking the serialized key with the actual content for `DistributedCacheTagHelper`

**Comment by danroth27** [comment]
@sebastienros Could you please provide more details on what the issue is here and what the proposed change is?

**Comment by sebastienros** [comment]
@lodejard 's recommendations. We are building/serializing the key for every request and comparing strings, where we could just store a structure representing the key in memory and compare instances in the case of the `CacheTagHelper`.

Then for the `DistributedCacheTagHelper` we need to store the key with the data, because the key is hashed (SHA256) and there could be hash collisions, hence potential leak of information if a request gets forge to get the value from another cache key. Serializing the key with the data will let us check that the returned content is for the intended key (like a dictionary handles key collisions).

So yes, you need to open it for RC2 and assign it to me.
