### ISSUE TITLE
How to bypass StrongName Verification or workaround!

### ISSUE THREAD

**Issue by ShrenikOne** [aspnet/Mvc#4254]
We are having issue with Strong Name signing where we have sign our projects with snk key. While one of the Third-Party dll (Kendo.Mvc) for ASP.NET 5, doesn't have signed assemblies which making runtime error. In normal project under <runtime> tag in configuration file we can bypass StrongNameVerification by application (https://msdn.microsoft.com/en-us/library/cc713694(v=vs.110).aspx), How we can do it DNX?

**Comment by Eilon** [comment]
Everything right now has moved to [.NET CLI](https://github.com/dotnet/cli/), and DNX is going away. If you still see the issue with .NET CLI, please log an issue at https://github.com/dotnet/cli/issues.
