### ISSUE TITLE
Consider adding SignInResult/SignOutResult and SignIn/SignOut

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Mvc#4258]
MVC 6 has really cool authentication-specific `ActionResult`s and helpers for `Forbid` and `Challenge`, but nothing for `SignIn` and `SignOut`.

It would really make this kind of actions much clearer:

```csharp
[HttpPost("~/connect/logout"), ValidateAntiForgeryToken]
public async Task<IActionResult> Logout() {
    var response = HttpContext.GetOpenIdConnectResponse();
    if (response != null) {
        return View("Error", response);
    }

    // ...

    // Ask the cookies middleware to delete the local cookie created
    // when the user agent is redirected from the external identity provider
    // after a successful authentication flow (e.g Google or Facebook).
    await HttpContext.Authentication.SignOutAsync("ServerCookie");

    // Redirect the user agent to the post_logout_redirect_uri specified by the client application.
    await HttpContext.Authentication.SignOutAsync(OpenIdConnectServerDefaults.AuthenticationScheme);

    return new EmptyResult();
}
```

-> 

```csharp
[HttpPost("~/connect/logout"), ValidateAntiForgeryToken]
public async Task<IActionResult> Logout() {
    var response = HttpContext.GetOpenIdConnectResponse();
    if (response != null) {
        return View("Error", response);
    }

    // ...

    return SignOut("ServerCookie", OpenIdConnectServerDefaults.AuthenticationScheme);
}
```

I'm fine submitting a PR if you like the general idea :clap:

**Comment by rynowak** [comment]
If it would make the templated controller code more understandable/declarative then it seems like a good idea. I'm not familiar enough with this part of the system on my own to understand how much of this could be refactored into a result type.

@blowdart thoughts?

**Comment by louislewis2** [comment]
I like the general thoughts behind this idea. Seeing this included would certainly be a plus.

**Comment by PinpointTownes** [comment]
For some reasons, I'm seeing weird issues with DependencyModel in the MVC tests.
Restoring doesn't seem to help. I'll investigate.

![image](https://cloud.githubusercontent.com/assets/6998306/13643380/c3a1e9a4-e620-11e5-9120-a05e6fab62c5.png)

**Comment by PinpointTownes** [comment]
```js
"Microsoft.Extensions.DependencyModel/1.0.0-dev-1452673922": {
  "type": "package",
  "dependencies": {
    "Newtonsoft.Json": "7.0.1",
    "System.Dynamic.Runtime": "4.0.11-rc2-23616",
    "System.IO.FileSystem": "4.0.1-rc2-23616",
    "System.Linq": "4.0.1-rc2-23616",
    "System.Reflection": "4.1.0-rc2-23616",
    "System.Runtime": "4.0.21-rc2-23616"
  },
  "compile": {
    "lib/dotnet5.4/Microsoft.Extensions.DependencyModel.dll": {}
  },
  "runtime": {
    "lib/dotnet5.4/Microsoft.Extensions.DependencyModel.dll": {}
  }
}
```

Hum, another buggy package... I'll wipe my packages folder :smile:

**Comment by pranavkm** [comment]
@PinpointTownes the DependencyModel packages went back in time. Delete the `Microsoft.Extensions.DependencyModel` from your packages directory (%UserProfile%/.dnx/packages and %UserProfile%/.nuget/packages) and try restoring again.

**Comment by blowdart** [comment]
@HaoK would have a better opinion than I

**Comment by HaoK** [comment]
Seems reasonable and shouldn't hurt to have.  Identity takes care of some of this stuff for you already, so things like signing in with the identity created claims principal might not feel great with a SignInResult

**Comment by PinpointTownes** [comment]
> @PinpointTownes the DependencyModel packages went back in time.

@pranavkm that's so sneaky :smile: 
Thanks for the tip.

PR sent: https://github.com/aspnet/Mvc/issues/4259

**Comment by danroth27** [comment]
Not a bad idea, but we're trying to lock down for a stable 1.0.0 release. I think this can wait until post 1.0.0.

**Comment by PinpointTownes** [comment]
@danroth27 it could wait until post-RTM, but it's really a trivial change. Actually, it's more a copy/paste of existing code (which is itself a tiny wrapper around the authentication APIs) to polish the API a little bit than a real new feature.

**Comment by Eilon** [comment]
@rynowak parking this on your plate, @PinpointTownes has a PR out for it: https://github.com/aspnet/Mvc/pull/4259

**Comment by rynowak** [comment]
f9d24a8521fbdc82234544068d4a832ca8f3a53a
