### ISSUE TITLE
StackOverflowException causes  dnx.exe to crash

### ISSUE THREAD

**Issue by John0King** [aspnet/Mvc#4264]
Views/
    Home/
        _aside.cshtml   (  file B )
        Index.cshtml
    shared/
        _aside.cshtml  ( file A )
        _Layout.cshtml

This is file B's content
` @Html.Partial("_Aside")  //I want to Render file A  `
,
 I know this is wrong , I shoud write " ../shared/_aside " , but It should not causes dnx.exe  to crash.

**Comment by davidfowl** [comment]
Yes it should absolutely crash. Stackoverflows always crash the process.
