### ISSUE TITLE
Catch all routes

### ISSUE THREAD

**Issue by Aghyad-Khlefawi** [aspnet/Mvc#4265]
i'm trying to create a route to catch all the routes that doesn't start with /Home
and reroute them to /home but the "{*url}" syntax is not working
im using the following in the Configure section

```c#
app.UseMvc(routes =>
            {
                routes.MapRoute("default", "{controller}/{action}/{id?}",new { controller = Home",action="Index"},new { controller = "Home"});
                routes.MapRoute("angular", "{*url}", new { controller = "Home",action="Index"});
            });
```

**Comment by Aghyad-Khlefawi** [comment]
I'm using angular route in my application so i want to reroute all the request that starts with something other than /home to the home controller, what im expecting is the first MapRoute to take the requests that are sent to home controller and the other MapRoute to take all the other requests.
the first MapRoute configurations is working fine so the requests to the home controller are working as expected but the second one is not recognizing the other requests. 
I have the same route configurations running on an MVC 5 application and I'm trying to upgrade it to MVC 6 but when im requesting like /locations it's not rerouting to home controller it just returns an empty response

**Comment by Eilon** [comment]
@Aghyad-Khlefawi we tried the code and it seemed to work fine. All requests to the Home controller actions went there, and all other URLs all went to the Home/Index action.

Are you running this on IIS? Or directly on Kestrel?

**Comment by Aghyad-Khlefawi** [comment]
Thank you for you help everything is working now :)
the problem was that i was calling UseStaticFiles() after  UseMvc().
i moved  the UseMvc call to the end of the Configure method and now it's working.

**Comment by Eilon** [comment]
Ah, yes, the ordering of the middleware is critical because each middleware gets to decide whether it wants to handle the request, and whether to continue execution to the next middleware or stop execution.
