### ISSUE TITLE
MVC app without preserveCompilationContext has no controllers

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4266]
Without `preserveCompilationContext: true` - MVC's `IAssemblyProvider` won't include any assemblies, and thus the app won't find any controllers.

**Comment by pranavkm** [comment]
@pakrym,  what's the work item tracking this: https://github.com/aspnet/Mvc/pull/4261#issuecomment-194603013?

**Comment by pranavkm** [comment]
This looks like it's fixed with the newest `DependencyContext` (which we have a private copy of now). I'll leave this open until we pick up a new build.

**Comment by pranavkm** [comment]
This is fixed in the most recent builds of Mvc. Should remain fixed when we move to the newest build of DependencyModel.
