### ISSUE TITLE
JsonInputFormatter fails to use custom SerializerSettings

### ISSUE THREAD

**Issue by kwaclaw** [aspnet/Mvc#4270]
Using MVC as of today, March 10, 2016.
Modifiying SerializerSettings like so:

	public void ConfigureServices(IServiceCollection services)
	{
		var mvc = services.AddMvc(config => {
			ConfigureJson(config);
		});
		...
	}

	void ConfigureJson(MvcOptions config) {
		var jsonSettings = new JsonSerializerSettings();
		...
		jsonSettings.Binder = new Json.KnownTypesSerializationBinder(KnownTypes.Map);
		jsonSettings.TypeNameHandling = TypeNameHandling.All;

		var jsonInputFormatters = config.InputFormatters.OfType<JsonInputFormatter>();
		foreach (var jif in jsonInputFormatters)
			jif.SerializerSettings = jsonSettings;

	}

The custom binder is never called. It looks like the new SerializerSettings are ignored altogether.
Looking at the **JsonInputFormatter** code: 

	protected virtual JsonSerializer CreateJsonSerializer()
	{
		if (_jsonSerializerPool == null)
		{
			_jsonSerializerPool = _objectPoolProvider.Create<JsonSerializer>();
		}

		return _jsonSerializerPool.Get();
	}

I don't see how the SerializerSettings get applied.
This is in contrast to the **JsonOutputFormatter**:

        protected virtual JsonSerializer CreateJsonSerializer()
        {
            if (_serializer == null)
            {
                _serializer = JsonSerializer.Create(SerializerSettings);
            }

            return _serializer;
        }

**Comment by kwaclaw** [comment]
I resolved this temporarily by creating a "fixed" JsonInputFormatter that overrides CreateJsonSerializer.

However, this shows another problem:
- constructing a JsonInputFormatter requires an ILogger instance
- but int he startup sequence, logging is configured lattr - there is no configured logger factory available in ConfigureServices
So I had to use a mock logger.

Maybe logging configuration should be done earlier?

**Comment by kwaclaw** [comment]
Just curious: Is there a reason why the JsonOutputFormatter does *not* use an object pool for the Json serializer?

**Comment by rynowak** [comment]
The objectpool isn't needed for output because we can use a single shared instance. 

For input we need to attach to the "errors" callback so each `JsonSerializer` is stateful while it's being used

**Comment by rynowak** [comment]
This should be fixed now. Also @kwaclaw FYI the recommended way to set JSON.Net settings is with the `AddJsonOptions(...)` api on the builder.

```
services.AddMvc().AddJsonOptions(json => 
{
    json.SerializerSettings.Binder = new Json.KnownTypesSerializationBinder(KnownTypes.Map);
});
```

Doing it this will way affect all of the places in MVC where we use JSON.Net.

Your way should work too, but will only affect the input formatter, just an FYI.

**Comment by kwaclaw** [comment]
Good to know, thanks.
In my case though I want only the input formatter configured like that.
