### ISSUE TITLE
HtmlHelper.ViewData and HtmlHelper<T>.ViewData are not the same instance

### ISSUE THREAD

**Issue by ristona** [aspnet/Mvc#4271]
`HtmlHelper.ViewData` and `HtmlHelper<T>.ViewData` are not the same instance

**Comment by dougbu** [comment]
Do you have a demonstration of this? In any view, there's only one property of type `HtmlHelper<TModel>` and, while `HtmlHelper<T>.ViewData` has a different type from `HtmlHelper.ViewData` i.e. uses `new`, there's just one runtime instance (of type `ViewData<T>`).

**Comment by Eilon** [comment]
Looking at the code shows that the two should always be the same, but just in case, I ran this code in a view page:

```
@object.ReferenceEquals(((IHtmlHelper)Html).ViewData, Html.ViewData)
@object.ReferenceEquals(Html.ViewData, ViewContext.ViewData)
@object.ReferenceEquals(((IHtmlHelper)Html).ViewData, ViewContext.ViewData)
```

And it rendered `True True True`.

**Comment by ristona** [comment]
@Html.DropDownList(string.Empty, Html.ViewData.GetDataSourceOfSelectList(), Html.BuildFirstOptionLabel("please select", "all"))

public static IEnumerable<SelectListItem> GetDataSourceOfSelectList(this ViewDataDictionary viewData)
        {
        ...
        }

public static string BuildFirstOptionLabel<TModel>(this HtmlHelper<TModel> html, string optionInEditor, string optionInQuery, string separator = "-")
        {
//it is ok!
}
public static string BuildFirstOptionLabel<TModel>(this HtmlHelper html, string optionInEditor, string optionInQuery, string separator = "-")
        {
//it is error!
}


mvc source code:
 public class HtmlHelper<TModel> : HtmlHelper
    {
        public HtmlHelper(ViewContext viewContext, IViewDataContainer viewDataContainer, RouteCollection routeCollection)
            : base(viewContext, viewDataContainer, routeCollection)
        {
              //this is new ViewDataDictionary instance
            _viewData = new ViewDataDictionary<TModel>(viewDataContainer.ViewData);
        }

        public new ViewDataDictionary<TModel> ViewData
        {
            get { return _viewData; }
        }
}

public class HtmlHelper
{
       public ViewDataDictionary ViewData
        {
              //this is old ViewDataDictionary instance.
            get { return ViewDataContainer.ViewData; }
        }
}

**Comment by dougbu** [comment]
You are looking at MVC 5 source code and filing an issue in the MVC Core repository. You will not see anything similar when using MVC Core.

But even in MVC 5, the single instance (of type `HtmlHelper<TModel>`) on the page will contain all values previously added to the `ViewDataDictionary` regardless of which `ViewData` property you use. Since `BuildFirstOptionLabel()` _reads_ the dictionary, it isn't clear what breaks your scenario.

**Comment by ristona** [comment]
Index.cshtl
@Html.Partial("_Model",Html.ViewData)//viewData is custom ViewDataDictionary
----------------------------------------------
_Model.cshtml
@Html.Editor("Category")
----------------------------
public class Content
{
[UIHint(("DropDownList")]
public string Category{get;set;}
}
-----------------------------------
@Html.DropDownList(string.Empty, Html.ViewData.GetDataSourceOfSelectList(), Html.BuildFirstOptionLabel("please select", "all"))
DropDownList.cshtml
