### ISSUE TITLE
TagHelper [asp-validation-for] doesn't work on server side

### ISSUE THREAD

**Issue by John0King** [aspnet/Mvc#4277]
This is the code i write:

``` html
<input asp-for="Title" class="form-control" />
<span asp-validation-for="Title" class="text-danger"  />
```

And this is the code that Generated:

``` html
<input name="Title" class="form-control input-validation-error" id="Title" type="text" value="sfdsfd" data-val="true" data-val-length-max="2" data-val-length="字段 Title 必须是最大长度为 2 的字符串。">
 <span class="text-danger field-validation-error" data-valmsg-replace="true" data-valmsg-for="Title">
</span>
```

**Comment by dougbu** [comment]
If the actual generated HTML is `<span ... />`, everything is behaving as expected. The error message isn't visible because the self-closing element has no body.

Change the source to
``` html
...
<span asp-validation-for="Title" class="text-danger"></span>
```

**Comment by John0King** [comment]
Is the a bug of  visual studio web tools ?

**Comment by dougbu** [comment]
We've had a few discussions related to this experience and aspnet/Tooling#398 remains open. But the onus today is on `.cshtml` authors; they must not write a normal HTML element as self-closing.

Side note: aspnet/Tooling#398 is about the opposite problem: VS does not warn when users write a void element with an end tag e.g. `<input ...></input>`.

**Comment by John0King** [comment]
I think Razor View is missing some usefule method: 
```C#
//get  every error message of  Model's property
public IEnumerable<string> GetModelErrorsFor( Action<model> action )
// get single error message of Model's property , sometimes i want  show only one error
public string GetFirstModelErrorFor(Action<model> action)
// get validation-summary
public IEnumerable<string> GetModeErrors( ValidationSummary options )

// and also  DisplayNameFor 
```

those method work like HtmlHelpers or TagHelpers ,  but  they only return pure string rather than full HTML mark; So we can use them in any cases!

**Comment by Eilon** [comment]
Moving to backlog.
