### ISSUE TITLE
How can i add "WebApiCore" dependencies ?

### ISSUE THREAD

**Issue by endink** [aspnet/Mvc#4280]
I'd like a more lightweight WebAPI program without razor views, taghelper etc, but if i use "AddMvcCore" method i cant use POCO object (like  IEnumerable<String>) as my action result.

I tried the following methods , but it doesn't work:
``` javascript
var mb = services.AddMvcCore()
                    .AddApiExplorer()
                    .AddAuthorization()
                    .AddJsonFormatters()
                    .AddFormatterMappings()
                    .AddDataAnnotations()
                    .AddJsonHelper()
                    .AddCors();

```

Please tell me for using POCO action result witch feature i need to add if i use AddMvcCore? thanks!

**Comment by Eilon** [comment]
@rynowak do you know the answer to this?

**Comment by henkmollema** [comment]
In which way does it not work? A similar configuration like yours works for me.

**Comment by Eilon** [comment]
@endink it might also help if you show what your controller looks like. There might be some other error somewhere.

**Comment by rynowak** [comment]
Can you give us more information than "it doesn't work"? Is there an exception? Is there log output?

**Comment by endink** [comment]
@Eilon sorry, because my colleague override the json output formatter and his code have some issue, it not a asp.net bug, i will close this, thanks @Eilon @henkmollema @rynowak ! sorry again!
