### ISSUE TITLE
Can't access to action parameter attributes in dnxcore50

### ISSUE THREAD

**Issue by ZOXEXIVO** [aspnet/Mvc#4282]
At previous versions of ASP.NET we use custom validation attribute using FluentValidation like this

```
[HttpPost]
public async Task<IActionResult> SavePersonalSection([Validation(typeof(PersonalCardValidator))]PersonalCardDto obj)
{
       return Ok(await _personalCardDataManager.SavePersonalSectionAsync(obj));
 }
```

```
public class ValidationFilter : Attribute, IAsyncActionFilter
{
    public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
    {
         //need access to action parameter attribute
    }
}
```

And in action validation filter we trying to validate parameter.
Not i can't access to the parameter binding and it GetCustomAttributes method

 ```
var validationTasks = actionContext.ActionDescriptor.ActionBinding.ParameterBindings
.Select(x => new   
{
      Value = actionContext.ActionArguments[x.Descriptor.ParameterName],
      Validators = x.Descriptor.GetCustomAttributes<T>().Select(y => y.ValidatorType).Select(......Resolve.....).Cast<IValidator>()
})
.SelectMany(x => x.Validators.Select(y => y.ValidateAsync(x.Value)));
```

```
public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
{
     
} 
```

Any workaround ?

**Comment by rynowak** [comment]
You should have access to the parameter descriptors, and related `ParameterInfo` objects through the `ActionDescriptor`, you just need to do a downcast to get at the reflection related bits.

```
context.ActionDescriptor.ParameterDescriptors.Cast<ControllerParameterDescriptor>().Select(x =>
{
    Value = context.ActionArguments[x.Name];
    Validators = x.ParameterInfo.GetCustomAttributes<...>()....
});
```

I'd recommend building your own cache rather than doing reflection on each call. One approach might be a register a convention using `IParameterModelConvention` that will build the cache on startup and store it in `ActionDescriptor.Properties`.

**Comment by ZOXEXIVO** [comment]
I use dnxcore50 version and i can't find ParameterDescriptors property:

`context.ActionDescriptor.ParameterDescriptors`

**Comment by rynowak** [comment]
Sorry, it should just be `Parameters`. Updated my example: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Abstractions/ActionDescriptor.cs#L39

**Comment by ZOXEXIVO** [comment]
You think, that I don't try use all properties and make issue after first problem ?
I make issue, because i can't access to the action parameter attibutes.
If you show me, how it possible, I say thank you!
