### ISSUE TITLE
Make JsonOutputFormatter use camel case by default

### ISSUE THREAD

**Issue by glennblock** [aspnet/Mvc#4283]
It's not the 1990s, everyone expects their JSON to be camel case :-)

Can we get this to be the default so we don't have to do this: https://gist.github.com/shahiddev/e82fea1c85d5e3faa710

I am curious if anyone actually desires pascal case to even be an option.

**Comment by petarrepac** [comment]
+1 for camelCase by default

**Comment by larsw** [comment]
Word!

**Comment by tmutton** [comment]
**makeJsonCamelCaseAgain**

**Comment by longchiwen** [comment]
![doit](https://cloud.githubusercontent.com/assets/1258717/13750517/17027b5c-ea06-11e5-859a-8e7b2da4f0fe.jpg)

**Comment by khellang** [comment]
While we're at it; can we propose to set `NullValueHandling` to `Ignore` as well? It's just a waste of bytes, IMO.

I assume that a high percentage of JSON returned from an API is consumed by JavaScript, where both `null` and `undefined` are falsy, so `if (json.someProperty) { /* do something */ }` would have the same results.

It should also be no problem if the consumer is using Newtonsoft.Json, where `MissingMemberHandling` is set to `Ignore` by default. This would simply set properties to `default(T)`.

**Comment by petarrepac** [comment]
@khellang create new issue if you want, let's keep this one focused just on camelCase

**Comment by NeelBhatt** [comment]
Go Go Go just do it 😃

**Comment by Gutek** [comment]
+3.14 :) And more :)

**Comment by spboyer** [comment]
As a compliment to https://github.com/aspnet/Mvc/issues/1765 makes perfect sense. cc/ @danroth27

**Comment by shawnwildermuth** [comment]
+1

**Comment by dotnetjalps** [comment]
+1

**Comment by ptrstpp950** [comment]
Take my vote

**Comment by glennblock** [comment]
Thanks all. Make sure you use the upvote feature if you +1d

**Comment by JamesNK** [comment]
I see +1's are alive and well even after github reactions.

Camel case makes sense with JavaScript but I think JSON is more than just JavaScript. It is a simple change to enable camel case with Json.NET. I think the default is better left taking what the user has defined and making it clear in the documentation how to config MVC to use camel case everywhere if that is what the user wants.

**Comment by Gutek** [comment]
> I see +1's are alive and well even after github reactions.

Mobile version of page does not allow to add reaction.

**Comment by spboyer** [comment]
@JamesNK is this an 80/20 thing? Like @khellang states above
> I assume that a high percentage of JSON returned from an API is consumed by JavaScript...
Or as in the case of #1765 
Can this be the default, and have the developer do the 20% exception?

**Comment by JamesNK** [comment]
If you do want to make this change then I think global naming needs a better feature in Json.NET. There are some problems with `CamelCasePropertyNamesContractResolver` that I haven't yet got around to fixing: it applies to both property names and dictionary names, it doesn't compose well and it always overrides the name from `JsonPropertyAttribute`.

A better solution would be adding some sort of `INamingStrategy` exposed on `DefaultContractResolver`  that supports finer grained control.

**Comment by bsimser** [comment]
Where do I submit my PR for this? Make it so!

**Comment by Mpdreamz** [comment]
@jamesNK that would be awesome, we default to camelCase in elasticsearch's .NET client but need some hoops to make sure verbatim properties work e.g dictionaries/json properties/client mappings

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/VerbatimDictionaryKeysConverter.cs#L15

And

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonAbstractions/SerializationBehavior/ElasticContractResolver.cs#L180

A more directly supported approach would be awesome!

**Comment by nemichandjat** [comment]
+1

**Comment by Eilon** [comment]
After much deliberation (and discussions with @JamesNK), we have decided by default to support:

![camel-case](https://cloud.githubusercontent.com/assets/202643/15563453/70fdb0e6-22bd-11e6-82c0-9eee1813955a.png)

----
Source images:
* [Camel](https://commons.wikimedia.org/wiki/File:07._Camel_Profile,_near_Silverton,_NSW,_07.07.2007.jpg)
* [Bookcase](https://commons.wikimedia.org/wiki/File:Books_in_my_room.JPG)

**Comment by rynowak** [comment]
Yay! we're like everyone else now!

**Comment by Eilon** [comment]
@rynowak - tell me the truth. Was the ❤️ for the change, or for the amazing MS Paint job?

**Comment by JamesNK** [comment]
Ah, one issue is INamingStrategy isn't in 8.0.4-beta1

**Comment by Eilon** [comment]
Yeah, "small" snafu... we would likely only do this feature if we had `INamingStrategy` because using the pre-existing techniques might be too big of a hammer (e.g. affecting dictionary keys, ignoring `[JsonProperty]`, etc.).

**Comment by glennblock** [comment]
Yay!!

**Comment by JamesNK** [comment]
Here is NamingStrategy (I changed it to an abstract base class instead of an interface) mostly finished - https://github.com/JamesNK/Newtonsoft.Json/pull/922

It would be nice to get some other eyes on it if you have time for a code review.

**Comment by dougbu** [comment]
@javiercn is working get us to @JamesNK's new https://www.nuget.org/packages/Newtonsoft.Json/9.0.1-beta1 version.

**Comment by rynowak** [comment]
> tell me the truth. Was the :heart: for the change, or for the amazing MS Paint job?

Huh, I wasn't even aware there was an image here. I usually browse github in text mode on a feature phone. This is a dope change, and I'm glad we finally agree with everyone else on the planet on how JSON is usually formatted.

**Comment by dougbu** [comment]
- 62803d5
- aspnet/Entropy@6c53784

**Comment by JamesNK** [comment]
I suggest you add a couple of unit tests for behavour of serializing dictionary keys (e.g. IDictionary<string, string>) and properties with JsonProperty("name") to make sure you're happy with how those serialize.

**Comment by SBArbeit** [comment]
So... if I have existing ASP.NET 4.6 code that reads/writes JSON the default way it's been for many years now, and that JSON is stored as a string, and I want to use .NET Core to read it... will I be able to just read the existing data as-is, or do I have to do a convert-to-camel-case on my data as part of the migration to get it to deserialize into the .NET Core objects? Or is there a PascalCaseNamingStrategy I could use?

**Comment by Eilon** [comment]
@SBArbeit I believe you can clear out the naming strategy and that'll work. Or, it might just work anyway, depending on the exact scenario (not everything is always case-sensitive).

**Comment by JamesNK** [comment]
When deserializing Json.NET will first attempt to match a property exactly, e.g. "firstName" in JSON will attempt to be deserialize to a .NET property called firstName, but if it doesn't find that it will do a case insensitive look for properties, and will match a property called FirstName.

You can set NamingStrategy to null.

**Comment by SBArbeit** [comment]
@Eilon, @JamesNK Thank you for the clarification. That makes it super easy.

**Comment by John0King** [comment]
@JamesNK  @rynowak 
I really don't like this change, this's will effect thousands of developers who will upgrade to dotnet Core, but seems like many people like came case ,I suggest some feature like this:
```C#
[cameCase] //should provide by json.net
public class Persion
{
    public int Id { get; set; }
    public string Name { get; set; }
}

```
I think this will give more controllable .


Json is not javascript And it not only use by javascript, it's a **data formate** now use in many languages .
And MVC shouldn't  limit the data by default.
Think about this : 
```json
// this is a line in project.json 
"Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
```
will be
```json
"microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
```

Please rethink about this change.

**Comment by JamesNK** [comment]
> [cameCase] //should provide by json.net

There is that feature.

> Json is not javascript And it not only use by javascript, it's a data formate now use in many languages > And MVC shouldn't limit the data by default.

All those other languages are either camel casing or snake casing.

It's just a default and it is one line to turn it off.

**Comment by jpsingleton** [comment]
Beyond just casing, I find `CamelCasePropertyNamesContractResolver` behaves better. I've had issues in the past where the default contract resolver would serialize private properties, might be fixed by now though.

**Comment by John0King** [comment]
@JamesNK  Can We use `DefaultContractResolver` in a few of specific Method  when the defalut `CamelCaseResolver  ` turn on ?

**Comment by Mike-EEE** [comment]
Have we consulted the Xamarin and enterprise folks on this issue, yet? :wink: 

So to summarize:
- C#/Code is PascalCase by default.
- Serialized version of said code (as data) is camelCase by default.

Please help me see what I am missing here that makes me say that this is inconsistent and fosters (more like festers) context-switching between two the areas of concern.

Maybe I found it here:
> It's just a default and it is one line to turn it off.

Thank you for saving my sanity @JamesNK. :smile:  That's encouraging.  The problem is that C# increasingly appears to be the "odd duck" by holding onto PascalCase as its established default naming convention, and it seems that more and more tech -- MSFT tech, even and this is a good example -- is moving away from it.  This is especially so when you view the Azure code samples that are coming out.  It seems like everything BUT C# is camelCase.

But alas, we still use C# and hinge upon it for our solutions, generally speaking.

I am all for consistency, but if you are building your application in C#, you simply lose that consistency by deviating from its defaults.

FWIW, I have always felt this way.  I was not (and am not) a fan of .NET Configuration's (app/web.config) approach, either.

BTW, this is (yet another reason) why Xaml rocks so hard, as it has 100% parity to what it serializes/deserializes. :stuck_out_tongue:  The class definition **IS** the schema.

**Comment by glennblock** [comment]
HTTP is not tied to a particular runtime stack, it is not a serialization
mechanism, it is a message transfer protocol. We are building solutions for
a HTTP clients to consume not .NET clients. The majority of the JSON APIs
in existence are camelCase. Why should a client have to know or care that
the backend implementation is .NET. The whole purpose of HTTP is to
abstract away the implementation details of the clients and servers.

**Comment by Mike-EEE** [comment]
Yet we have chosen to tightly-couple our entire design and infrastructure upon HTTP, which seems a little incongruous.  Why must we know of HTTP within our code?  If there is any abstraction to be done, it would seem that designing a protocol-agnostic system is the place to start.  As great as HTTP is with its natural-lending verb and design elements, I still cringe whenever I see anything that requires it (or its concepts) to be in code.  I have always found it strange that no one questions why we are coupling design with a protocol.

But I digress. I do appreciate your explanation @glennblock.  Thank you for taking the time to do so.  I realize I am in the minority here, and I am not looking to reverse community consensus (ok, maybe a little :smile: ).  The best I can hope for is to point out the solution inconsistency we have introduced here from a _.NET perspective_.  And although I appreciate the aim of playing along nicely with others going forward, we have done so at a cost towards what has gotten us here to date.

**Comment by fatagun** [comment]
yeah just do it and let the rest of the world waste their time searching for a solution. Great!!
