### ISSUE TITLE
AuthorizeFilter prevents unauthenticated requests to be handled by IAuthorizationService

### ISSUE THREAD

**Issue by malekpour** [aspnet/Mvc#4287]
Current implementation of `AuthorizeFilter` only calls `IAuthorizationService.AuthorizeAsync` when request is authenticated.

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/AuthorizeFilter.cs#L78

I think `DenyAnonymousAuthorizationRequirement` should be used instead, otherwise there is no way to use authorization requirements without being authenticated.

**Comment by Eilon** [comment]
@blowdart @Tratcher thoughts?

**Comment by Tratcher** [comment]
@HaoK?

**Comment by blowdart** [comment]
By design. Why go into policies when you don't have an identity to evaluate anyway?

**Comment by PinpointTownes** [comment]
> By design.

Bad design then. The authorization service is already responsible of determining whether unauthenticated requests (= no principal/identity) are acceptable or not depending on the specific policy that applies, so there's no reason to have a duplicated logic in MVC.

What's the whole point of `DenyAnonymousAuthorizationRequirement` and `policy.RequiredAuthenticatedUser()` if the authorization service is not invoked when the user is not authenticated?

**Comment by malekpour** [comment]
For example you can have a requirement to grant or deny access by IP address only or you may grant guest users access in restricted hours.

**Comment by blowdart** [comment]
For your IP example you're now attempt to authorize on something that isn't an identity at all. So you either write an authentication middleware which builds an identity from an IP address, or you go the filter route.

**Comment by malekpour** [comment]
This authentication vs. authorization has always been controversial. I've seen systems using IP, MAC address or computer name to identify and authorize group of users (e.g. Kiosk devices).

Considering the modular nature of AspNetCore, it does not make sense if MVC handles security, since the security project can take care of it very well.

In fact unauthenticated users have their own identity which is Anonymous. Lets have security project take care of them. The following code block functionality in the `AuthorizeFilter` can be replaced by a new requirement like `AllowAnonymousAuthorizationRequirement`

```c#
// Allow Anonymous skips all authorization
if (context.Filters.Any(item => item is IAllowAnonymousFilter))
{
    return;
}

**Comment by PinpointTownes** [comment]
> What's the whole point of DenyAnonymousAuthorizationRequirement and policy.RequiredAuthenticatedUser() if the authorization service is not invoked when the user is not authenticated?

Still no answer to this crucial question, it's a bit worrying IMHO.

**Comment by HaoK** [comment]
[Authorize] with nothing else specified uses the default policy of requiring authenticated user.  So this requirement and method exists mostly for that scenario

**Comment by PinpointTownes** [comment]
But isn't the authorization filter always rejecting unauthenticated requests without invoking the authorization service no matter if you specify a policy?

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L77-L79

**Comment by HaoK** [comment]
Yeah the authorize filter probably shouldn't do that explicit check and leave that to the Authorization service.  This seems like a legit bug to fix.

**Comment by Eilon** [comment]
@HaoK @blowdart any thoughts on whether this would regress any MVC 5.x behavior? I want to make sure there isn't too big a leap for someone updating their app and getting very different or unexpected behavior.

**Comment by Eilon** [comment]
@HaoK @blowdart ping for my last question regarding possible behavior changes.

**Comment by blowdart** [comment]
It would be a regression, yes. However you could address that by making the plain [Authorize] always just check for authenticated users. As we didn't have a policy in previous versions it's arguable we can make the behaviour there what we like.

**Comment by PinpointTownes** [comment]
@blowdart well, AFAIK, that's how it works with the current bits: when `[Authorize]` doesn't specify a policy, `AuthorizationPolicy.Combine` returns the default one, which blocks unauthenticated requests by default.

**Comment by HaoK** [comment]
Empty authorize already requires authenticated users by default I believe.

**Comment by blowdart** [comment]
Yup, I am just emphasising that can't change.

**Comment by malekpour** [comment]
I think the default behavior is to require authentication:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization/AuthorizationOptions.cs#L19

**Comment by Eilon** [comment]
Right, just plain `[Authorize]` means "authenticated" and nothing more.

**Comment by Eilon** [comment]
So is this bug ok to close, then?

**Comment by PinpointTownes** [comment]
Not really, the abusive check in the MVC authorization filter still needs to be removed.

**Comment by HaoK** [comment]
Yeah my PR removes the preemptive check that blocks the AuthZ service from even being checked since unauthenticated requests never make it out of the filter

**Comment by Eilon** [comment]
Then how happy are we with https://github.com/aspnet/Mvc/pull/4385? @HaoK do we just need a signoff there (perhaps from @rynowak and/or @blowdart ) and we're good to go?

**Comment by HaoK** [comment]
Yeah its a pretty straight forward change, so just need a sign off and I can merge

**Comment by blowdart** [comment]
I am confused by Pinpoint's point on #4385

**Comment by PinpointTownes** [comment]
@blowdart what's confusing... my remark about the fact MVC always uses `ChallengeResult` and relies on some voodoo magic in `AuthenticationHandler` to dynamically determine whether 401 or 403 should be returned? :smile:

**Comment by blowdart** [comment]
Oh that's what you were talking about? Hah, no, I actually like that. Devs don't need to think about what the right status code is.

**Comment by PinpointTownes** [comment]
Maybe, but it's both nonsensical and incorrect:
* A challenge is necessarily the consequence of a 401 response.
* Asking the authentication handler if it can extract an authentication ticket from the request to determine the right status code prevents a simple (yet fundamental) scenario: asking the caller to authenticate again (if you return a `ChallengeResult`, a 403 will be returned if the request was authenticated).

**Comment by blowdart** [comment]
Nothing stops you from return a 401 or a 403 though.

Is the name the problem?

**Comment by PinpointTownes** [comment]
And BTW, users wouldn't have to think about the right status code if the authorization stack was better designed. `IAuthorizationService` should tell its caller why authorization failed and the caller should return the appropriate code (in MVC, it should be done by the authorization filter).

**Comment by PinpointTownes** [comment]
> Nothing stops you from return a 401 or a 403 though.

Well, try it: calling `ChallengeResult`/`AuthenticationManager.ChallengeAsync` will result in a 403 response if a token/cookie was successfully retrieved from the request, even if I *really* want the caller to re-authenticate (a 403 is not appropriate in this case) :smile:

**Comment by Tratcher** [comment]
That results in infinite auth loops.

**Comment by HaoK** [comment]
f54a9648156d040fa455daffb680001a9928167d
