### ISSUE TITLE
Create a separate handler for each attribute route

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4293]
Right now we have a big global action selection table that includes all actions. This table is largely moot because attribute routes have their own selection criteria. We can solve this by using a per-route-entry handler.

This will also allow us to remove the 'fixup' code from the handler that adjusts the route values.

**Comment by Eilon** [comment]
@ajaybhargavb please discuss with @rynowak regarding the approach for this.

@rynowak, reminder to ping @davidfowl to discuss this as well.

**Comment by Eilon** [comment]
@rynowak close?
