### ISSUE TITLE
Removing `Resolver` from ControllerBase in MVC

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#4296]
We're removing the `Resolver` IServiceProvider from ControllerBase in MVC.

If you are affected by this change you can simply replace any instance of `Resolver` with `HttpContext?.RequestServices` to get identical behavior.

**Comment by davidfowl** [comment]
> If you are affected by this change you can simply replace any instance of Resolver with HttpContext?.RequestServices to get identical behavior.

Or use the constructor, and avoid the service locator pattern like the plague.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
