### ISSUE TITLE
MVC 6 ViewComponents InvokeAsyn() method is not really async

### ISSUE THREAD

**Issue by javedsha** [aspnet/Mvc#4299]
Hi,
I am trying to use the MVC 6 ViewComponents InvokeAsync() feature to render a component asynchronously. But this is not working. The whole page is not rendering until the component (long running task) has completed.
My view component and view code is very much similar to what we have in samples: http://docs.asp.net/en/latest/mvc/views/view-components.html
Also, I am using the layout page which we get when we create a new ASP.NET 5 application.
Any help, much appreciated.

Code:
**Component View:**
```C#
@await Component.InvokeAsync("List", "D0");
```

**Component InvokeAsync Signature**

```C#
public async Task<IViewComponentResult> InvokeAsync(string id)
        {
             return View("List", await LongRunningCall(id));
        }
```

**Packages:**
```
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final"
```

**Comment by davidfowl** [comment]
That sounds like it's working fine to me. You might be confusing asynchronous javascript calls with async server calls. What behavior were you expecting? Are you trying to flush the page contents before your call returns? That's another feature completely.

/cc @NTaylorMullen @DamianEdwards

**Comment by DamianEdwards** [comment]
Yep, MVC and Razor will still buffer the output of the entire view rendering process before sending any bytes back to the browser (this is to allow for showing a friendly error page in the case that something fails during rendering). If you want to preemptively flush the response buffer so that the browser can start rendering the HTML, you can do that in the view like thus, but be sure you understand the trade-offs in doing so:

``` HTML
@await FlushAsync();
@await Component.InvokeAsync("List", "D0");
```
