### ISSUE TITLE
AntiForgery: Add a 'Diagnostic User Name' to the AF token for better diagnosibility

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#430]
The fall back in case identity does not contain a name identifier is to hash the entire claims identity. In order for the app developer to have a better understanding of what is going wrong, it is desirable to have a diagnostic only user name as part of the AF token.  This serves only for error and tracing scenarios.

| 223 | 10506 | Reported By: Harsh Gupta |

**Comment by danroth27** [comment]
We decided not to do this.
