### ISSUE TITLE
Cannot Debug in visual studio if VS is Elevated.

### ISSUE THREAD

**Issue by ltheONEl** [aspnet/Mvc#4301]
I have a curious issue.  To publish to IIS in my dev machine I run visual studio as administrator (bad ok!).
While visual studio is elevated I cannot debug an MVC project  either VS cannot attach or IIS Express dies or kestrel does. not sure which.  I don't get any error. VS just exits debug mode.

If I restart VS as normal (Not Elevated) I can debug perfectly.

Has anyone else seen this?

**Comment by danroth27** [comment]
Please open this issue in the https://github.com/aspnet/tooling repo.
