### ISSUE TITLE
Problem building MVC project using Visual studio

### ISSUE THREAD

**Issue by MariovanZeist** [aspnet/Mvc#4307]
I am having problems building a MVC project suing Visual Studio 2015 (Community edition)

One issue is that building a library with Visual studio will result in lots of errors mostly of the format 

`The type 'IList<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
`
Where IList<> can be Object or other basic types

But when building the same project using dotnet build I get no errors and the project compiles

The other problem (Which might or not might be related) is an downgrade warning to "System.Runtime, Version=4.0.0.0" when adding some MVC libraries. This can be seen when running dotnet restore on the library

I have uploaded a very small repro that will highlight both issues
[Github repo](https://github.com/MariovanZeist/VSBuildBugRepo)

I am uncertain if I have to file this under the dotnet/cli, or  aspnet/mvc or another repository, So if this is on the wrong repository please forward to the correct one

This comment is made in response to [(https://github.com/dotnet/cli/issues/1860)]

**Comment by danroth27** [comment]
Yeah, the existing RC1 tooling has very limited support for the latest RC2 bits. It's likely you will just need to wait for an RC2 tooling build.

**Comment by cwe1ss** [comment]
Any experimental/preview version of this tooling build would be greatly appreciated since this issue is quite annoying. It makes creating pull requests a lot harder.

**Comment by MariovanZeist** [comment]
FYI I was able to resolve the problem temporarily by removing the net451 framework moniker from all my libraries, I am now only building using the netstandard1.5 moniker in my libraries, and using dnxcore50 in my application.

**Comment by danroth27** [comment]
Sounds like you were able to resolve your issue.
