### ISSUE TITLE
UrlResolutionTagHelper doesn't work with TagHelpers that run before and supress output.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#4317]
If a user has a `TagHelper` and sets its order to `int.MinValue`, it'll run before the `UrlResolutionTagHelper`. Now, if that same `TagHelper` calls `output.SuppressOutput()` it will then force the `TagHelperOutput`s tag name to `null`. The problem this introduces is the `UrlResolutionTagHelper` relies on the `TagName` not being `null` when looking up corresponding attribute values for the tag so it ends up exploding [here](https://github.com/aspnet/Mvc/blob/fd984563c3f7e32c41a37c2d21040b6e4490d39c/src/Microsoft.AspNetCore.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs#L129).

We should check if `TagName == null` and if so, bail early.

**Comment by javiercn** [comment]
Would other taghelper types be affected by this same issue? the code that has the error seems applicable in many tag helpers (do we have more cases like this on our codebase)? /cc: @NTaylorMullen

**Comment by NTaylorMullen** [comment]
Very possible. Would have to give them a closer look or build out a sample to verify. When we wrote them initially ensuring they could react to other `TagHelper`s in the pipeline was lower priority. We covered a lot of cases but obviously not everything :smile:

**Comment by javiercn** [comment]
I looked up the implementation of all tag helpers I could find, I didn't see a similar pattern, so I think it's just this one
