### ISSUE TITLE
CandidateAssemblies should always include the entry assembly?

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#4318]
Scenario, I'm running MVC Sandbox and I get a 404 on startup.

Default assembly manager does this:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/DefaultAssemblyProvider.cs#L75

```C#
        public IEnumerable<Assembly> CandidateAssemblies
        {
            get
            {
                if (_dependencyContext == null)
                {
                    // Use the entry assembly as the sole candidate.
                    return new[] { _entryAssembly };
                }

                return GetCandidateLibraries()
                    .SelectMany(l => l.Assemblies)
                    .Select(Load);
            }
        }
```

GetCandidateLibraries only includes dependent assemblies (which for MVCSandbox only contains the MVC assemblies)

I believe the list of candidate assemblies should always contain the entry assembly plus optionally a set of referenced assemblies based on whether or not the DependencyContext is available.

**Comment by pranavkm** [comment]
> GetCandidateLibraries only includes dependent assemblies that's not true though. It should include the entry assembly if it references Mvc. What's the specific issue you were seeing?

**Comment by javiercn** [comment]
Running MVCSandbox, the MVCSandbox assembly wouldn't be included. @pakrym is investigating and I believe he has more context

**Comment by pakrym** [comment]
This is fixed in latest Cli+DependencyModel

**Comment by Eilon** [comment]
If you have a bug/PR number that would be good.

**Comment by pakrym** [comment]
Fixed == It's not broken there. Cli and dependency model being out of sync in mvc causes it.

**Comment by pranavkm** [comment]
Yeah, I haven't noticed this using 1.0.0-beta-001718 CLI + the DependencyModel clone we have in Mvc.

**Comment by Eilon** [comment]
Ah so we think it's fixed in newer builds?

**Comment by pakrym** [comment]
Yes

**Comment by Eilon** [comment]
Ok, we'll just hold onto this issue until we can verify. Thanks!

**Comment by NTaylorMullen** [comment]
Using dotnetcli `001718` and finding that my applications runtime library does not have any listed assemblies for it when published. However, if I choose not to publish and do `dotnet run` all works fine.

![image](https://cloud.githubusercontent.com/assets/2008729/14003417/b40a7a2a-f10f-11e5-8802-b167456f5274.png)

**Comment by NTaylorMullen** [comment]
Alright, turns out this happens if you don't do `.UseContentRoot(Directory.GetCurrentDirectory())` in your `Main`. Yay :dizzy_face: 

Ignore me.

**Comment by pranavkm** [comment]
Looks like this is fixed with the newest DependencyModel. @NTaylorMullen, the other issue is to make view discovery work and we could consider adding it to MvcSandbox to make our work flow bit easier.

**Comment by Eilon** [comment]
This is now fixed.
