### ISSUE TITLE
Inside area: relative url when no area defined in link

### ISSUE THREAD

**Issue by nooxnet** [aspnet/Mvc#4319]
I'm not sure if this is intended behavior or I've missed something when I moved from RC1 to RC2 Nightly yesterday:

I have this url inside _Layout.cshtml (under the main Views/Shared/ directory):

	<a asp-controller="Home" asp-action="Index">Home</a>

With RC1 this link has always been rendered as

	<a href="/">Home</a>

Now with RC2 it is rendered as "/" only when I'm on a page in the root directory But as soon as I'm on a page in the /Admin directory (area) it's rendered as:

	<a href="/Admin/Home">Home</a>

This behavior can be fixed by adding an empty area:

	<a asp-controller="Home" asp-action="Index" asp-area="">Home</a>

This also applies to 

	@Html.ActionLink("Home", actionName: "Index", controllerName: "Home")
	// fixed:
	@Html.ActionLink("Home", actionName: "Index", controllerName: "Home", routeValues: new { area = "" }, htmlAttributes: null)

My routes:

	app.UseMvc(routes =>
	{
		routes.MapRoute(
			name: "areaDefault",
			template: "{area:exists}/{controller=AreaRoot}/{action=Index}/{id:int?}" 
			);
		routes.MapRoute(
			name: "default",
			template: "{controller=Home}/{action=Index}/{id?}");
	});

Is this a bug? Is there a global setting? If this is intended then one has to add asp-area="" to links on root pages as soon as an area is added.

**Comment by pranavkm** [comment]
Seems like a result of https://github.com/aspnet/Mvc/issues/4013. cc @javiercn

**Comment by javiercn** [comment]
I believe the behavior you are seeing is correct in both cases. I don't think #4013 has anything to do with it.

When you are inside of an area, and try to generate a link outside of the area you need to specify the area explicitly, (the other area you want to generate the link to or null or empty string in case you want to generate a link to an action outside of any area).

What is happening in your situation is that you are inside of an Admin area, when you try to generate a link, the area is implicitly defined in the route values (as you hit an action within the area). When the link generation algorithm goes through the list of routes, it tries the first one (the one with the area and it matches it.

**Comment by rynowak** [comment]
This is an intended change in behavior: https://github.com/aspnet/Announcements/issues/120

**Comment by nooxnet** [comment]
Yes, it's a consistent behavior. If you don't specify a controller the current controller is used. If you don't specify an area, the current area is used. 

But I assume that many will stumble over this when they have some sort of menu and introduce an area later on. They will end up with broken links. It's probably a more common scenario than reusing an area-relative link in different areas (but not in the home directory).

Maybe 'area=""' should be added to menu links in samples and templates?

**Comment by danroth27** [comment]
No plans to make a change in behavior here.

**Comment by ermithun** [comment]
<form  asp-action="Register" asp-controller="Account" asp-route-area="Global"> in RC1
It gives
<form method="post" action="Global/Account/Register/">
========================================================
But RC2
<form  asp-action="Register" asp-controller="Account" asp-route-area="Global">
gives
<form method="post" action="/Account/Register?area=Global">
Need help

**Comment by Muchiachio** [comment]
What's your route configuration?

**Comment by ermithun** [comment]
@Muchiachio  
My route config
  app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
               
                routes.MapRoute(name: "areaRoute",
    template: "{area:exists}/{controller=Home}/{action=Index}");
            });
        }

**Comment by Muchiachio** [comment]
Try swapping them around, so that area route would be the first to be evaluated.

**Comment by ermithun** [comment]
@Muchiachio  Thanx

**Comment by rynowak** [comment]
Please see the announcement post here for explanation https://github.com/aspnet/Mvc/issues/3665
