### ISSUE TITLE
ControllerActionDescriptorProvider should take a collection of IControllerTypeProvider 

### ISSUE THREAD

**Issue by Sidoine** [aspnet/Mvc#4320]
In the current version of `ControllerActionDescriptorProvider`, the constructor takes an unique `IControllerTypeProvider`. It prevents to register several `IControllerTypeProvider`, for example if a third party assembly needs to add its controllers by type, without relying on the default conventions that may have been superseded by the application.

It should take an `IEnumerable<IControllerTypeProvider>` and enumerate on these values in the `BuildModel` method.

**Comment by rynowak** [comment]
We're already working on improving this scenario in another way: https://github.com/aspnet/Mvc/issues/4089
