### ISSUE TITLE
Allow specifying the controller name in ControllerAttribute

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#4323]
This is a follow up issue for #3732. See https://github.com/aspnet/Mvc/pull/4316#discussion_r56843279 for more details.

Currently we can mark that a class is a controller using ControllerAttribute as shown below.

``` C#
[Controller]
public MyControllerClass
{
    ...
}
```

This bug is to allow the user specifying the name of the controller as part of marking it a controller:

``` C#
[Controller("ControllerName")]
public MyControllerClass
{
    ...
}
```

**Comment by Eilon** [comment]
FYI @javiercn @rynowak moving to backlog.

**Comment by javiercn** [comment]
Yes, we can decide to tackle this at a later point in time. It's orthogonal to #4316

**Comment by Eilon** [comment]
Closing because we have no plans to support this.
