### ISSUE TITLE
Simplify assembly load on CoreCLR

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#4328]
Just use the default load context for razor views. We get no benefit from having a custom load context. Now that we can load things directly into the default load context, we don't need it.

/cc @pranavkm

**Comment by Eilon** [comment]
@davidfowl needed for RC2?

**Comment by davidfowl** [comment]
Nah, can wait until RTM. Though the change is minimal.

**Comment by Eilon** [comment]
Ok will do in RTM.
