### ISSUE TITLE
AddUserSecrets

### ISSUE THREAD

**Issue by Charmatzis** [aspnet/Mvc#4331]
One question..... If I use AddUserSecrets() when I deployed to the azure web app, have I have to do anything like to import the secrets in the Application settings in "App Settings", or that stuff happens automatically with VS?

**Comment by Eilon** [comment]
@blowdart would you use user secrets on Azure, or would you use it only at dev time on a local machine?

**Comment by Charmatzis** [comment]
Well, they are saved the "secrets" in my local machine and I want them to be moved in web app azure.

**Comment by blowdart** [comment]
Only at dev time. Azure web apps have settings in their control panels, I'd use those.

**Comment by cwe1ss** [comment]
Azure Key Vault is another great (and pretty cheap) solution for storing connection strings and other sensitive data. The [Tailspin sample app](https://github.com/Azure-Samples/guidance-identity-management-for-multitenant-apps) contains a [Configuration-provider](https://github.com/Azure-Samples/guidance-identity-management-for-multitenant-apps/tree/master/src/Tailspin.Surveys.Configuration.KeyVault) for Key Vaults. This means, you can use Key Vault secrets like all other configuration values in your code.

**Comment by Eilon** [comment]
You can learn more about "user secrets" on the ASP.NET docs site: https://docs.asp.net/en/latest/security/app-secrets.html

As mentioned by @blowdart , the user secrets (also known as secret manage) stuff is for dev-time only. When running on a hoster such as Azure Web Sites, there is a control panel for the site where you can add the secret settings, and then you can easily pick them up using the environment variable config provider (which is included by default).
