### ISSUE TITLE
Cache Tag Helper -inside Partial View-

### ISSUE THREAD

**Issue by SimonOrdo** [aspnet/Mvc#4333]
Steps:
1. Cache tag helper inside of a partial view.  Pass data into the body of the cached section via Model data.  Something like...

`<cache>
    <span id="@Model.SectionHtmlId">
        @Model.Content
    </span>
</cache>`

2. Render partial view multiple times on same page, but with different content (via model)

3. Cached areas are all rendered the same as the very first instance of the partial renderings.

I assume this is because the cache tag helper code resolves the cache key to the same thing since it comes out of the same partial, i.e. it looks to the cache tag helper like it is actually the same content.

I can overcome this issue by creating a more complex vary-by parameter for each partial call, but I'm wondering if this is intended behavior or if it's something that you'd want to fix?

**Comment by pranavkm** [comment]
Assuming the code looks like this:

```
@Html.Partial("_CachePartial", content1)
@Html.Partial("_CachePartial", content2)
```
what would the uniquely identifying parameter be? Varying by the model wouldn't be correct in the general case.

**Comment by SimonOrdo** [comment]
Maybe I'm thinking about it wrong, but how is that different from something like this?

(Assuming this is in the same view)
```
<cache> <div>content 1</div> </cache>

<cache> <div>content 2</div> </cache>
```

Doesn't the caching engine recognize that as two different entries?

**Comment by pranavkm** [comment]
Razor generates a unique id per instance of `<cache>` when parsing it - so those two entries have different identifiers (which get added as keys). In your case, it's the same "instance" so they get the same id. Varying by the page path wouldn't help either since that's going to be the same.

**Comment by SimonOrdo** [comment]
Gotcha, so it is as I suspected - Razor resolves it as the same instance because it "physically" is the same one.  

In the specific case of rendering a cached item from a partial, however, I think that re-use is implied (by convention).  Intuitively I expected the cache key generated to be different for each instance rendered by a call to `@HtmlPartial`.

It sounds like modifying the `vary-by` parameter manually for each instance rendered is probably the clearest way to more explicitly define the behavior.

**Comment by danroth27** [comment]
Correct, you need to explicitly specify what you want to vary-by.
