### ISSUE TITLE
Fix Microsoft.AspNetCore.Mvc.Dnx to avoid referencing System.IO/Reflection/Runtime

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Mvc#4334]
`Microsoft.AspNetCore.Mvc.Dnx` currently references `System.IO`, `System.Reflection` and `System.Runtime` at the global dependency level, which causes weird issues on .NET Desktop: https://github.com/dotnet/cli/issues/1993#issuecomment-200512200

@pranavkm do you remember why you had to add these packages?

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Dnx/project.json#L20-L22

/cc @davidfowl

**Comment by pranavkm** [comment]
There was an issue with the CLI where it would add multiple entries to the project.lock.json (a package reference and a framework reference) which would cause `dotnet build` to fail. This was addressed in https://github.com/NuGet/NuGet.Client/pull/389, but we haven't updated to a build of the CLI with the fix (it was a bit unstable when I checked last week). We're working on updating our packages to the newest CoreFx packages and perhaps that might resolve the the problem that surfaced the restore bug. We'd be able to address it once that's taken care of.

**Comment by PinpointTownes** [comment]
Thanks for the explanation :clap:

**Comment by Eilon** [comment]
@pranavkm also just parking this on your plate until we can verify.

**Comment by pranavkm** [comment]
Looks like updating the packages wasn't enough. We're working on updating the cli next which should allow us to remove this hack..

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/330e98d1fc9318a799d5af792ceccd7c4d414029

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/330e98d1fc9318a799d5af792ceccd7c4d414029
