### ISSUE TITLE
Scaffolding Error when working with EF Fluent API 

### ISSUE THREAD

**Issue by hernandemczuk** [aspnet/Mvc#4336]
I have a **Data Acces Logic (Entity Framework)** project, a **Model** project with my POCOs classes and a last one with the **MVC Application**. In my DAL project, I configure some validations on my Model and its schema information on the database using **Fluent API**. That means that I use the following method in order to add these configurations:

`protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new Model1Configuration());
        }
`

When I try to add a new controller to my MVC application I select the option **MVC Controller with views, using Entity Framework**, which leads me to pick a **Data Context Class** and a **Model Class**. I mark **Generate Views** and write a **Controller Name** to finally click on **Add...**

Then the following alert shows up:

![error](https://cloud.githubusercontent.com/assets/4275069/14003095/05c05a5a-f12f-11e5-8da1-a7f94c7a1ec5.png)

I know it has something to do with the Fluent API, because if I comment out the previuos method I mentioned I can scaffold without any problem.

I'm using MVC v5.2.3 , Entity Framework v6.1.3

**Comment by danroth27** [comment]
@rowanmiller @phenning Are there known limitations with using the EF fluent API and scaffolding?

**Comment by rowanmiller** [comment]
@hernandemczuk have you confirmed that this only happens during scaffolding? If you just run the app, and perform data access using the views etc. you already have, does it successfully build the model and perform data access?

**Comment by hernandemczuk** [comment]
Yes, I have. It successfully built and performed data access the way It should. I also tried out using Data Annotation instead of the Fluent API with the same model and It worked perfectly.

**Comment by rowanmiller** [comment]
@hernandemczuk thanks for confirming. Will need someone from scaffolding to dig into this one - I'm assuming we are running some code to get the entity into the model that is running before OnModelCreating.

**Comment by danroth27** [comment]
@prafullbhosale Could you please take a look? Please note this is MVC 5 scaffolding.

**Comment by prafullbhosale** [comment]
Taking a look.

**Comment by prafullbhosale** [comment]
Looks like the issue is due to the fact that scaffolding internally adds the configuration on its own for each of the entity types and also invokes the OnModelCreating for the DbContext. So when calling the OnModelCreating, the configuration is already added and leads to this error. 

I have filed a TFS bug to address this.

**Comment by hernandemczuk** [comment]
I want to add a workaround I found to solve this issue without the need of using DataAnnotation. Instead of having separated Configuration files, each one having an Entity Configuration like this:

`public class ApplicationUserMapConfiguration : EntityTypeConfiguration<ApplicationUserMap>
{
    public ApplicationUserMapConfiguration()
    {
        ToTable("ApplicationUserMap", "Users");
        HasKey(c => c.Id);
     }
}

And then adding this configuration to the DbContext:

`protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
   modelBuilder.Configurations.Add(new ApplicationUserMapConfiguration()); 
}

I just added the whole configuration inside the DbContext for every entity:

`protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        //ApplicationUser

        modelBuilder.Entity<ApplicationUser>().HasKey(c => c.Id);
        modelBuilder.Entity<ApplicationUser>().ToTable("ApplicationUser", "Usuario");

        //Other entities...
    }`

**Comment by vipasane** [comment]
@prafullbhosale is there any link that you could share to follow up this issue or bug in TFS?

**Comment by Eilon** [comment]
I moved the bug to https://github.com/aspnet/Scaffolding/issues/199.
