### ISSUE TITLE
No lib folder in wwwroot

### ISSUE THREAD

**Issue by chriship** [aspnet/Mvc#4338]
Yesterday I created a project in OSX by typing:

yo aspnet
...
dnu restore
dnu build
dnx web

It created the project and put a lib folder (which included bootstrap, jQuery etc.) in the wwwroot folder.

Today when I do the same there is no lib folder.

I also get a lot of errors when typing dnu build:
  Unable to resolve dependency fx/mscorlib 
  Unable to resolve dependency fx/System 
  Unable to resolve dependency fx/System.Core 
  Unable to resolve dependency fx/Microsoft.CSharp 
  Unable to resolve dependency fx/System.Collections 
  Unable to resolve dependency fx/System.ComponentModel.DataAnnotations 
  Unable to resolve dependency fx/System.Diagnostics.Debug 
  Unable to resolve dependency fx/System.Diagnostics.Tools 
  Unable to resolve dependency fx/System.Globalization 
  Unable to resolve dependency fx/System.Linq 
  Unable to resolve dependency fx/System.Linq.Expressions 
  Unable to resolve dependency fx/System.Linq.Queryable 
  Unable to resolve dependency fx/System.ObjectModel 
  Unable to resolve dependency fx/System.Reflection 
  Unable to resolve dependency fx/System.Reflection.Extensions 
  Unable to resolve dependency fx/System.Resources.ResourceManager 
  Unable to resolve dependency fx/System.Runtime 
  Unable to resolve dependency fx/System.Runtime.Extensions 
  Unable to resolve dependency fx/System.Threading 
  Unable to resolve dependency fx/System.Data 
  Unable to resolve dependency fx/System.Transactions 
  Unable to resolve dependency fx/System.IO 
  Unable to resolve dependency fx/System.Text.Encoding 
  Unable to resolve dependency fx/System.Threading.Tasks 
  Unable to resolve dependency fx/System.Net.Http 
  Unable to resolve dependency fx/System.Security 
  Unable to resolve dependency fx/System.Xml 
  Unable to resolve dependency fx/System.Xml.Linq 
  Unable to resolve dependency fx/System.Configuration 
  Unable to resolve dependency fx/System.Collections.Concurrent

**Comment by Eilon** [comment]
@sayedihashimi any idea on the Yeoman templates? Are they all `dotnet` now?

**Comment by danroth27** [comment]
@chriship Did the "dnu restore" command succeed?

**Comment by chriship** [comment]
@danroth27 No errors on dnu restore. Have just tried again and none of the dnu build errors are showing this time so maybe that is a red herring. Still no lib folder though.

**Comment by danroth27** [comment]
Could you please you share the generated project.json file?

**Comment by chriship** [comment]
Sure:

```
{
  "version": "1.0.0-*",
  "userSecretsId": "aspnet5-coretest-9917aa98-1551-47bb-860b-dc40166463a5",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "tooling": {
    "defaultNamespace": "coretest"
  },

  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.Sqlite": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Dnx.Runtime":"1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [
      "npm install",
      "bower install",
      "gulp clean",
      "gulp min"
    ]
  }
}
```

**Comment by sayedihashimi** [comment]
Maybe we need to add the lib files to `yo aspnet`. @chriship can you file an issue at https://github.com/OmniSharp/generator-aspnet/issues?

**Comment by davidfowl** [comment]
It's because you're using code clr to build. Remove dnx451 from the project

**Comment by chriship** [comment]
Seems the issue was related to this: https://github.com/OmniSharp/generator-aspnet/issues/294

Running bower install created the lib folder.
