### ISSUE TITLE
confused about the update to "netstandard"

### ISSUE THREAD

**Issue by ciel** [aspnet/Mvc#4343]
The latest comments say that the libraries are "Updating to NetStandard.Library 1.5.0", but when I look at the source for the samples, [such as this one](https://github.com/aspnet/Mvc/blob/dev/samples/MvcSandbox/project.json), they still say "netstandardapp1.5" - while the newest is just "netstandard1.5". I'm confused about which we should be using.

**Comment by Eilon** [comment]
I heard from @richlander that @terrajobst is working on some guidance for library authors as to which TFMs to use, etc. I think once that's published it'll clarify exactly the question you have.

**Comment by Eilon** [comment]
BTW the simplest thing I can say right now is that `netstandard` is for libraries, and `netstandardapp` is for applications (which includes console apps, web sites, and tests). So that explains why you're seeing `netstandardapp` in that sample web site.

**Comment by Eilon** [comment]
Found some docs that explain a lot of this:
* https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md
* https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-standard-applications.md

**Comment by terrajobst** [comment]
That's correct. I'm working on an overall "packaging guidance" docs that talks about how to build packages for the .NET platform.

**Comment by ciel** [comment]
Thank you SO MUCH for this info and these links. It helps a ton. Also, please don't go forward with "netstandardapp1. 5". I don't think my poor OCD can take it.

I still think it'd be better to define an outer framework and then a version interior, like this...
````
" netstandardapp1" : {
      '1.5": { 
            "dependencies": { 
                   //...///
            }
       }
}
````

**Comment by davidfowl** [comment]
I think your OCD will have to take it :smile: . You can define multiple frameworks like that but it's only common for class libraries that are targeting more than one. e.g.

https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/project.json#L13-L64
https://github.com/autofac/Autofac/blob/master/src/Autofac/project.json#L22-L74

etc.

**Comment by ciel** [comment]
Being a programmer with OCD is maddening.

So is it pretty much settled then? 
````
netstandardapp1. 5
netstandard1.5
netcoreapp1.0
netcore1.0
````
These four are the finalized names/strings?

**Comment by davidfowl** [comment]
You're really asking different questions here and need to be more specific. If you're looking for an uber list of target frameworks there isn't any but we should have one. Here's a set https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#specific-platform-mapping but it doesn't include the newer ones like netstandardapp and netcoreapp.

**Comment by poimis** [comment]
Isn't netstandardapp going away in favor of netcoreapp?

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
