### ISSUE TITLE
Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken in Microsoft.Extensions.DependencyModel.DependencyContextJsonReader

### ISSUE THREAD

**Issue by miguellira** [aspnet/Mvc#4349]
### Steps to reproduce
install latest dotnet cli
git clone https://github.com/aspnet/cli-samples.git
update `project.json` with the following framework settings:
```json
    "frameworks": {
        "netstandardapp1.5": {
            "imports": [
                "dnxcore50",
                "portable-net451+win8"
            ],
            "dependencies": {
                "NETStandard.Library": "1.5.0-*"
            }
        }
    }
```
dotnet restore
dotnet build
dotnet run
launch a browser to `http://localhost:5000`
### Expected behavior
HTML with a static image and "Hello World"
### Actual behavior
The following error:
```console
An unhandled exception has occurred while executing the request
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(JObject root)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultAssemblyProvider..ctor(IHostingEnvironment environment)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```
### Environment information:
```console
.NET Command Line Tools (1.0.0-beta-001998)

Product Information:
 Version:     1.0.0-beta-001998
 Commit Sha:  cd35ba2a1a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

**Comment by pranavkm** [comment]
The most recent version of the CLI that we've tested against is 1.0.0.001718. We're working on updating to a newer version, but we using versions that we haven't tested (especially when the CLI is churning so much) is probably not a good idea.

**Comment by miguellira** [comment]
@pranavkm Yep. That's what I've come to find out.

But just to be clear, if I somehow find version `1.0.0.001718` of the dotnet CLI for OS X - everything should work out of the box correct?

Or is there some framework version that will work with the latest CLI drop?

**Comment by ciel** [comment]
oh man, I'm hitting this problem too. I'm not even sure how to go back to `1.0.0.001718`. Is there any way to do this?

**Comment by pranavkm** [comment]
Our latest bits (from aspnetcidev) were built using `1.0.0001718` and tested* on Travis + internal CIs so it should just work. 

* - we use in memory servers for our tests, so we don't get coverage for tests over Kestrel and IIS. We get that indirectly via MusicStore which seems to be doing ok on OSX with that build of CLI + latest of Mvc.

**Comment by miguellira** [comment]
@pranavkm Thanks for the info.

I just pulled the latest MusicStore and ran it against my current CLI (`1.0.0-beta-001998`) and ran into the `Failed to initialize CoreCLR, HRESULT: 0x80004005` others have also hit.

I'll try to find the `1.0.0-beta-001718` binaries or installer, downgrade and hopefully get back to a stable build.

**Comment by ciel** [comment]
If you find a link to that version, please share it. I’m hunting for one as well now. I have the file for `0.0.0-beta-001897` and it was working for me last night, but I’m not sure how it will fare against today’s nightly libraries.

If you need `0.0.0-beta-001897`, let me know and I'll put in a dropbox for you.

**Comment by pranavkm** [comment]
https://github.com/dotnet/cli/tree/rel/1.0.0/scripts/obtain/install.sh has a way to specify the version to install.

**Comment by ciel** [comment]
I tried that, it didn't work. I used `git clone [repo]` and went to the right directory, and ran `.\install.ps1 -version #.#.#.#` and it simply gave me an error.

```
PS C:\Users\Ciel\Documents\.NET\cli\scripts\obtain> .\install.ps1 -version 1.0.0.001718
dotnet_install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0.001718/dotnet-dev-win-x64.1.0.0.001718.zip
Invoke-WebRequest : BlobNotFoundThe specified blob does not exist.
RequestId:08a42a89-0001-007e-50b2-86f94a000000
Time:2016-03-25T16:20:20.8293200Z
At C:\Users\Ciel\Documents\.NET\cli\scripts\obtain\install.ps1:321 char:13
+     $resp = Invoke-WebRequest -UseBasicParsing $DownloadLink -OutFile ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebReques
   t], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCo
   mmand
PS C:\Users\Ciel\Documents\.NET\cli\scripts\obtain>
```

**Comment by kwaclaw** [comment]
Hitting me too. Is there a way this can be fixed on the input side (what JSON is it reading)?

**Comment by Eilon** [comment]
@pranavkm why would the version of the CLI affect the runtime of an ASP.NET app and which versions of Json.NET it's referencing?

**Comment by pranavkm** [comment]
@Eilon, there might be breaking changes in the DependencyModel json that gets produced by the CLI. They don't have a versioning scheme and their format is not backwards compatible - so older DependencyModel code might not be able to read it.

**Comment by Eilon** [comment]
Oh so it's not a real Json.NET version issue, but more likely some schema issue.

**Comment by miguellira** [comment]
For the record, out of pure curiousity... since I still had DNX installed on my machine I decided to try those tools to run MusicStore.

I upgraded to the latest runtime:
```console
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-final      coreclr x64          darwin          
       1.0.0-rc1-update1    coreclr x64          darwin          
  *    1.0.0-rc2-20222      coreclr x64          darwin          default
```
Removed the `net451` framework from `project.json`, ran `dnu restore`, `dnu build`, and `dnx web` and ran into this issue:
```console
      An unhandled exception has occurred while executing the request
System.InvalidOperationException: The Razor page '/Views/Home/Index.cshtml' failed to compile. Ensure that your application's project.json sets the 'preserveCompilationContext' compilation property.
```
Digging through GH issues looks like this is all related to changes to `DependencyModel` as @pranavkm elluded to.

**Comment by pranavkm** [comment]
@miguellira see https://github.com/aspnet/Announcements/issues/154

**Comment by miguellira** [comment]
@pranavkm Thanks. I'm subscribed to that repo and am usually good at remembering those announcements.

Updated per instructions, `dnu restore`, `dnu build`, and `dnx web` and now I get a new exception:
```console
An unhandled exception has occurred while executing the request
System.MissingMethodException: Method not found: 'System.Reflection.MethodInfo[] System.Reflection.TypeExtensions.GetMethods(System.Type, System.Reflection.BindingFlags)'.
```
At some point this all worked fine and I'm hopeful I can "undo" my changes and get back to a working enviornment.

I truly hope that this thread is helping your team get to a more stable RC2 or at the very least serves as a place where others running into the same issues can feel some sort of comfort that they are not alone - but really there's no need in chasing down ghosts.

**Comment by miguellira** [comment]
For those parties interested... I managed to get back to a "working enviornment".

As @pranavkm suggested, getting back to version `1.0.0-beta-001718` was the solution.

The `install.sh` file, however, is currently adding a `-dev` in the URL which results in an invalid download so I googled, found this [Travis CI log](https://travis-ci.org/aspnet/Diagnostics/jobs/116759598) and long story short... 

These are the dotnet CLI bits you are looking for: https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0.001718/dotnet-osx-x64.1.0.0.001718.tar.gz

```console
.NET Command Line Tools (1.0.0-beta-001718)

Product Information:
 Version:     1.0.0-beta-001718
 Commit Sha:  5b0afe7880

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

Although `dotnet-publish-iis` results in many of the following warnings:
```console
warn : Detected package downgrade: System.Dynamic.Runtime from 4.0.11-rc2-23923 to 4.0.11-rc2-23911 
warn :  bin (>= 1.0.0) -> dotnet-publish-iis (>= 1.0.0) -> Microsoft.DotNet.ProjectModel (>= 1.0.0-beta-001943) -> Microsoft.CSharp (>= 4.0.1-rc2-23911) -> System.Dynamic.Runtime (>= 4.0.11-rc2-23923) 
...[snip]...
```
I was able to run the HelloMvc app **without** modification.

**Comment by ciel** [comment]
Thank you so much for the file.

I really, really hope all this craziness settles soon. Right now I just have to grin and bear it because I know the teams are doing their best and pushing themselves as hard as they can to get this all up and running... But I never realized how much of the work Visual Studio abstracted away for me.

This whole .net core experience has made me appreciate Visual Studio and even ASP.NET MVC more than before.

**Comment by miguellira** [comment]
@ciel You're welcome. Glad this long thread has helped someone.

I totally agree with your comment. My main work is on a Windows 10/VS2K15 setup and though I have all of the tooling up to date there I use my Mac to try out all the .NET Core bits - porting small ASP.NET apps (usually rich client side ones) with little or no dependency on .NET full. 

Definitely looking forward to working with all this stuff on Visual Studio. Good luck!

**Comment by GuardRex** [comment]
@miguellira @pranavkm @Eilon I just hit this under `dotnet cli` -2076 on Win10 with a `netcoreapp1.0` app. Is the workaround really to go all the way back to -1718?
```
.NET Command Line Tools (1.0.0-beta-002076)

Product Information:
 Version:     1.0.0-beta-002076
 Commit Sha:  8df6f5405d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
```json
"dependencies": {
    "AppExceptions": "1.0.0",
    "ContactLog": "1.0.0",
    "CustomMvcRazorHost": "1.0.0",
    "Email": "1.0.0",
    "Microsoft.AspNetCore.Antiforgery": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.AspNetCore.Tooling.Razor": "1.0.0-*",
    "Microsoft.Extensions.Configuration": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "NETStandard.Library": "1.5.0-*",
    "StyleScriptInlining": "1.0.0",
    "WindowsAzure.Storage": "6.2.2-preview"
},
"frameworks": {
    "netcoreapp1.0": {
        "imports": [ "dnxcore50", "portable-net451+win8" ]
    }
},
"runtimes": {
    "win81-x64": {}
},
```

**Comment by Eilon** [comment]
That CLI might be too new, you need 1718.

**Comment by davidfowl** [comment]
or you might be able to work around it by replacing the right services...

**Comment by GuardRex** [comment]
In case anyone wants the Win version of -1718, the binaries can be obtained at ...
```
https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0.001718/dotnet-win-x64.1.0.0.001718.zip
```
However and as I expected, that's a really, really old `dotnet cli`, so trying to use that resulted in this ...
![capture](https://cloud.githubusercontent.com/assets/1622880/14113177/6e43f228-f597-11e5-8e2d-e710c609ab96.PNG)

I'd like to try your, @davidfowl, suggestion next. Besides getting past the OP exception, I want latest `dotnet cli` sauce for my goose.

I'm going to look into the casting situation in `Microsoft.AspNetCore.Mvc.Infrastructure.DefaultAssemblyProvider` and see what's what, but any additional tips on "replacing the right services" would be greatly appreciated.

It's also worth asking @pranavkm: When you say "We're working on updating to a newer version," I don't guess there is an open issue on that that we can track? Whatever I do today to get around this, I'd like to know when "nightly" `dotnet cli` and "nightly" CoreFX are holding hands again :heart:, so I can drop whatever I end up putting into place today.

**Comment by miguellira** [comment]
@GuardRex FWIW... I decided to take your `project.json`, remove any private libraries and try it out against the latest CLI drop on OS X (`1.0.0-beta-0021111`) and was able to **successfully** run a simple MVC app without runtime errors. Here's what I got:

**project.json**
```json
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },
    "dependencies": {
        "Microsoft.AspNetCore.Antiforgery": "1.0.0-*",
        "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc": "1.0.0-*",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
        "Microsoft.AspNetCore.Tooling.Razor": "1.0.0-*",
        "Microsoft.Extensions.Configuration": "1.0.0-*",
        "Microsoft.Extensions.Logging.Console": "1.0.0-*",
        "NETStandard.Library": "1.5.0-*",
        "WindowsAzure.Storage": "6.2.2-preview"
    },
    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dnxcore50",
                "portable-net451+win8"
            ]
        }
    }
}
```
**NuGet.config**
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="aspnetcidev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
**Program.cs**
```c#
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace GuardRex
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                        .UseServer("Microsoft.AspNetCore.Server.Kestrel")
                        .UseContentRoot(Directory.GetCurrentDirectory())
                        .UseDefaultHostingConfiguration(args)
                        .UseStartup<Startup>()
                        .Build();

            host.Run();
        }
    }
}
```
**Startup.cs**
```c#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace GuardRex
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(LogLevel.Debug);

            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.All
            });

            app.UseStaticFiles();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvcWithDefaultRoute();
        }
    }
}
```
It's important to note that although I did **_not_** receive any runtime errors, I did get a restore error:
```console
Errors in /Users/miguellira/Desktop/GuardRex/project.json
    System.Xml.XmlSerializer 4.0.0-beta-23109 provides a compile-time reference assembly for System.Xml.XmlSerializer on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with osx.10.11-x64.
    One or more packages are incompatible with .NETCoreApp,Version=v1.0 (osx.10.11-x64).
```
Not sure if this will fair as well on Windows 10, I'll try later and update the thread. Cheers.

**Comment by GuardRex** [comment]
@miguellira I did get it running a few hours ago after it was failing earlier this morning, and I think something changed this morning in packages/runtime/tooling to make that possible.

The `System.Xml.XmlSerializer` issue is because the Azure Storage team pegged the dep to an old package for `WindowsAzure.Storage`. I think the next version of the Azure Storage library will clear that one up. In the meantime, I was given the good advice by Eric StJohn to add `"System.Xml.XmlSerializer": "4.0.11-*"` to the deps to shut-up the exception, and that seems to be working fine. https://github.com/dotnet/corefx/issues/6801#issuecomment-197553984
