### ISSUE TITLE
@Html.Raw(null) stops rendering the view

### ISSUE THREAD

**Issue by nooxnet** [aspnet/Mvc#4350]
I have a view which outputs raw HTML for a text editor:

	@Html.Raw(Model.Description)

Description is often null. With RC1 this worked. With the nightly built from last week the output which is received by the browser stops some lines (some 100 bytes) above the code with @Html.Raw(null). No exception. Just missing HTML output. The output stops even within HTML tags or attributes.

Workaround:

	@Html.Raw(Model.Description ?? "")

**Comment by Eilon** [comment]
Well that's just weird...
