### ISSUE TITLE
Cleanup assembly discovery in ApplicationParts

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#4353]
We currently look up the IHostingEnvironment instance on AddMvcCore() from the ServicesCollection instance in the services collection that is passed during startup. This is fragile and we do it for assembly discovery purposes, we shoud find a better way of doing this.

**Comment by Eilon** [comment]
Putting this in RTM. Let's make sure we have a good discussion with a good set of people on this because I want to make sure whatever we come up with is a genuinely good fix.

**Comment by javiercn** [comment]
This is an example of why looking at the service collection is problematic https://github.com/aspnet/Mvc/issues/4399

**Comment by javiercn** [comment]
This is another example of how this is problematic https://github.com/aspnet/Mvc/issues/4479

**Comment by javiercn** [comment]
After a brief discussion we've decided to keep the current implementation and just check that the HostingEnvironment that we find has a valid application name and fallback to an empty list of application parts if it doesn't.

In the general scenario, this will not be a problem, the only case in which this might not work is stated on the bugs above, in which for tooling or for testing someone adds or modifies the hosting environment instance themselves.
