### ISSUE TITLE
Consider making "feature folders" the default layout for views.

### ISSUE THREAD

**Issue by poimis** [aspnet/Mvc#4356]
Maybe RazorViewEngine could use feature folders as a default? See discussion here: 
https://github.com/aspnet/Templates/issues/462

**Comment by Eilon** [comment]
This is an interesting suggestion, but as per my comments in the other issue, we are not planning on changing the defaults. However, if you find that there are limitations in RazorViewEngine or elsewhere in MVC that make it rather difficult for someone to *use* "feature folders", we would certainly like to discuss how to make those scenarios easier.

**Comment by cwe1ss** [comment]
fyi, we are using feature folders with a custom `IViewLocationExpander`:

```csharp
public class FeatureFolderViewLocationExpander : IViewLocationExpander
{
    public void PopulateValues(ViewLocationExpanderContext context)
    {
        /* no-op */
    }

    public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
    {
        // {0} - Action Name
        // {1} - Controller Name
        // {2} - Area name

        object area;
        if (context.ActionContext.RouteData.Values.TryGetValue("area", out area))
        {
            yield return "/Areas/{2}/{1}/{0}.cshtml";
            yield return "/Areas/{2}/Shared/{0}.cshtml";
            yield return "/Areas/Shared/{0}.cshtml";
        }
        else
        {
            yield return "/Features/{1}/{0}.cshtml";
            yield return "/Features/Shared/{0}.cshtml";
        }
    }
}
```

this allows the structure described [in my blog post about  MVC 5](http://www.chwe.at/2014/07/feature-folders-controllers-and-views/)
