### ISSUE TITLE
ViewComponent search algorithm enhancement request

### ISSUE THREAD

**Issue by brianro** [aspnet/Mvc#4357]
The algorithm searching for view component files assumes the component used is in a sub-folder of the controller class. When invoking the controller or in the meta-data of the controller definition, I want to define a controller path on the search path.

Currently when you are using re-using a view component from another area of the application, the view component can't locate its files. If I use the Shared area all the time, my application slowly migrates into the shared area.

For example: the view for editing customer information may be in the customers application area. When you are completing a check-out, you may want to provide the opportunity for them to update the customer profile. I want to re-use the customer profile view component from the check-out controller, but the algorithm searches for the files relative to the check-out controller, not the customer controller.

Hope you understand the issue. Thanks, B.

**Comment by dougbu** [comment]
@brianro the relevant code (in [ViewViewComponentResult](https://github.com/aspnet/Mvc/blob/7bd7b32fcb71311bbc5b9f2a3d4761f7eb4784a8/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewComponents/ViewViewComponentResult.cs#L87-L115)) already supports a few alternatives. E.g. your view component could return `View("full path.cshtml")` or `View("relative path.cshtml")`. In addition a view name (lacking the `.cshtml` suffix) will be searched for in any `/Components/{Component Name}` subdirectory of the regular view search path.

**Comment by brianro** [comment]
Thanks Doug,

 

I do understand these options exists, but they are fairly high maintenance.

 

It would be really great if I could pass a different controller class or type into either the attribute declaration or the invoke method to have that controllers location used in the search pattern instead of the current running controller.

 

Thanks,

B.

**Comment by Eilon** [comment]
The intended design of View Components is that their views are located in the `Shared/Components` folder by default. Or you can use any of the options that @dougbu mentioned.
