### ISSUE TITLE
Should we restore X-HTTP-Method-Override ?

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#436]
Legacy MVC supports a X-HTTP-Method-Override request header.  The value may be set using `@Html.HttpMethodOverride()` and is read at multiple points in the pipeline, including the `[AcceptVerb]` attribute.  Ask here is to decide if we need this feature (helpers et cetera) in WebFx.

| 214 | 10428 | Reported By: Doug Bunting (AAPT) |

**Comment by yishaigalatzer** [comment]
Moved to hosting repo - aspnet/Hosting#138
