### ISSUE TITLE
Carry the current ModelStateEntry on the ModelBindingContext

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4362]
See: #4179

![image](https://cloud.githubusercontent.com/assets/1430011/14088926/050c5ba2-f4e7-11e5-8c14-f2aefd85688e.png)

A lot of this time is spent looking up the 'current' model state node. Since we turned MSD into a prefix tree, we can push/pop nodes as part of the `ModelBindingContext`. This way when we create an entry we just need to append a child to the current node, not to look up the current node.

**Comment by Eilon** [comment]
@dougbu can we see if this:

1. Is beneficial?
2. Can be done without a breaking change?

**Comment by dougbu** [comment]
Nice idea but I tried 3 approaches and none were clearly beneficial.

FYI approaches from worst to best of the bad lot were:

1. Allocate lambdas on entry to a new model binding scope and allocate the `ModelStateEntry` only when required.
2. Allocate the `ModelStateEntry` on entry to a new model binding scope.
3. Allocate the `ModelStateEntry` for a scope either when required e.g. a binder sets its value or just before entering a new model binding scope.

**Comment by dougbu** [comment]
See #5495 for details of approach 3.
