### ISSUE TITLE
Should we support TypeActivating a per-request model binder

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4365]
BinderTypeModelBinder supports providing a type to the model binding system that will be type activated and used to model bind **each** time the binder is called.

Do we need this? What kinds of scenarios do we envision using it for? Note that this isn't the same as per-request, the unit of work here is the individual property being bound.

**Comment by Eilon** [comment]
@rynowak is the suggestion to remove the per-property behavior and change it to be per-request? Or to have both behaviors available? Or something else?

**Comment by rynowak** [comment]
The suggestion is that all model binders created this way have singleton-lifetime (like other model binders)

**Comment by Eilon** [comment]
Ah sure. That makes a lot more sense.

**Comment by Eilon** [comment]
Discussed in person, we're alright with leaving this feature in place.
