### ISSUE TITLE
Remove DefaultAssemblyPartDiscoveryProvider.GetAssemblyName

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#4366]
We have a copy of the GetAssemblyName method from the CLI because it is currently static. This can be removed once once https://github.com/dotnet/cli/pull/2117  lands.

**Comment by Eilon** [comment]
https://github.com/dotnet/cli/pull/2117 is merged so hopefully we can get this into RC2 soon.

**Comment by dougbu** [comment]
@pranavkm was this done?
