### ISSUE TITLE
Investigate overhead of ControllerActivator in TechEmpower scenarios

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4367]
Sampling data from HelloWorldMvc:
![image](https://cloud.githubusercontent.com/assets/1430011/14115987/7556c93c-f592-11e5-9e62-a95d2c8db717.png)

This validation might be too expensive to do per-request

**Comment by Eilon** [comment]
Moving to 1.0.0.

**Comment by Eilon** [comment]
@mnltejaswini needs to be marked as done?
