### ISSUE TITLE
Authorize based on multiple policies

### ISSUE THREAD

**Issue by markusvt** [aspnet/Mvc#4374]
I use claim-based authorization in my application. Now I have a scenario, in which an action should be accessible by users that have either Claim A or Claim B. 

While reading the docs I found that and "AND" is quite easy possible with those claims but for an "OR" I would need to write multiple custom handlers for a requirement. Is that correct so far or is there an easier way to manage the "OR" policy authentication?

**Comment by Eilon** [comment]
@blowdart ?

**Comment by blowdart** [comment]
You would put the OR inside a single policy handler, with a custom requirement. For example;

    public class OneOrTheOtherRequirement: AuthorizationHandler<OneOrTheOtherRequirement>, 
                                           IAuthorizationRequirement
    {
        protected override void Handle(AuthorizationContext context, 
                                       OneOrTheOtherRequirementrequirement)
        {
            if (!context.User.HasClaim(c => c.Type == "one") && 
                !context.User.HasClaim(c => c.Type == "theother"))
            {
                return;
            }
            context.Succeed(requirement);
        }
    }

You could parameterise the requirement and have a list of claims you wanted to OR to make it more flexible.
