### ISSUE TITLE
Error when using multiple where clauses in EF7 / Dot Net Core RC1

### ISSUE THREAD

**Issue by Yablargo** [aspnet/Mvc#4375]
Hello,

I have the following query, which executes without any issue:

`List<Patch> allPatches = (from p in _context.Patches where p.Software.Any(s => softwareIds.Contains(s.SoftwareId)) select p).ToList();
`
However, when I add a second where clause, things go belly up:

`
List<Patch> allPatches = (from p in _context.Patches where p.Software.Any(s => softwareIds.Contains(s.SoftwareId)) && p.Id < 500 select p).ToList();
`

I get the following error from the server:

> A database operation failed while processing the request.
> 
> SqlException: An expression of non-boolean type specified in a context where a condition is expected, near 'AND'. 
> 

This seems to occur whenever I add multiple where clauses, and may be related to the 'old-style' query writing? I will post more info as I obtain it.

**Comment by CaffeinatedCM** [comment]
This sounds like an issue for Entity Framework, not MVC. Maybe try posting it at [that issue page instead] (https://github.com/aspnet/EntityFramework/issues).

**Comment by Eilon** [comment]
Yes, please log an issue in the EF repo - that's where the EF experts hang out.
