### ISSUE TITLE
Question: how do you set the innerHtml of a TagBuilder?

### ISSUE THREAD

**Issue by Villason** [aspnet/Mvc#4382]
TagBuilder anchor = Generator.GenerateActionLink(
                    linkText: "hello",
                    actionName: null,
                    controllerName: null,
                    protocol: null,
                    hostname: null,
                    fragment: null,
                    routeValues: new { before = Before },
                    htmlAttributes: null);

How do I add html to that anchor? linkText just accepts text. And there are no clear properties to add the html.

Guys, this implementation of TagHelpers is a bit confusing and over-conventionalized. Not intuitive at all.

**Comment by dougbu** [comment]
`TagBuilder.InnerHtml` is of type `IHtmlContentBuilder`. So add text to it using `Append(string)` or if it's already encoded `AppendHtml(string)`. Call `Clear()` if you don't like what `GenerateActionLink()` added.

I'm curious: Exactly how are you using the `IHtmlGenerator`?

**Comment by Villason** [comment]
Thank. That works. Another stupid question. Is it possible to render the
TagBuilder into a string in rc1? It would be handy in some cases instead of
appending them to the output.

About your question, I am building navigation bootstrap taghelpers which
automatically set the proper "active" class based on the route and
querystring data. The anchor tags are generated on the fly and I saw you
use the Generator property in your own code.

**Comment by dougbu** [comment]
Thanks for the information on your scenario.

> Is it possible to render the `TagBuilder` into a `string` in rc1?

Any `IHtmlContent` implementation supports the following:
``` c#
            using (var writer = new StringWriter())
            {
                content.WriteTo(writer, HtmlEncoder.Default);
                return writer.ToString();
            }
```

**Comment by Villason** [comment]
Thank you Doug. You might agree that's too verbose!

**Comment by dougbu** [comment]
> You might agree that's too verbose!

`TagBuilder` and other `IHtmlContent` implementations exist to efficiently render HTML-encoded and literal strings to an HTTP response. Creating intermediate strings is not the primary purpose and allocating such strings is a major performance headache.

When using `TagBuilder`s in a tag helper, add it to the appropriate `TagHelperOutput` property e.g. `output.Content.Append(tagBuilder)`.

**Comment by dougbu** [comment]
Closing because we've strayed far from the original question which you've said has been answered.
