### ISSUE TITLE
[Dependency Injection] How can I get IServiceProvider outside controller ?

### ISSUE THREAD

**Issue by GregH44** [aspnet/Mvc#4386]
Hi everyone,

I try to work with native dependency injection of ASP.NET Core 1.0. I work with rc1 update 1 version.

I have an n-tiers application. I would like to get IServiceProvider into DataLayer to obtain my DbContext by service with AddTransient.

Many examples show how to get my DbContext with my controllers like this :

`public MyController(IDbContext dbContext)
{
}`

This exemple works very well. But I don't want to use this method because I have to pass my DbContext through my layers.

My question is : How can I get IServiceProvider outside ASP.NET Core scope ?

Thank you for your help.

Greg

**Comment by GregH44** [comment]
Moved to DependencyInjection

**Comment by NkululekoMakhubu** [comment]
Hi @gregoryhervin ,

I have a similar issue. Could you please share how moving to Dependency Injection helped resolve your issue?

Thanks

**Comment by gregoryhervin** [comment]
Hi @NkululekoMakhubu,

Could you explain what do you want to do ? This is for the DbContext ?
Could you share your source code to help you ?

Thanks

**Comment by NkululekoMakhubu** [comment]
Hi Greg,

I posted a question on Stack Over Flow. 
Please have a look if you can.
https://stackoverflow.com/questions/46670359/how-register-service-type-for-microsoft-odata-edm-iedmmodel

Thanks

**Comment by GregH44** [comment]
Hi !

So, this is the wrong way to do that.
You pass your controller in parameter of InvokeForTest. You can do it but that is not what you want.
You should pass your IEdmModel instead of a controller.

Why ? The instance of IEdmModel will be created when your controller will be called.
So, your constructor about your controller can be :
`public MyController(IEdmModel myEdmModel)`

Now, you have to configure your service and lifetime in your startup. See the **Registering Your Own Services** in the [ASP.NET Core docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection).

Have fun ;-)

**Comment by NkululekoMakhubu** [comment]
Hi Greg,

I'm not sure I follow. Could you provide a small example?

Thanks in advance

**Comment by GregH44** [comment]
Of course :-)

First of all, in ASP.NET Core project, you should have a "Startup" class and in that class, you should have a method named **ConfigureServices** like :
```
public void ConfigureServices(IServiceCollection services)
{...}
```
Into that method, add :
`services.AddScoped<IEdmModel, EdmModel>();`
Now, you have registered your EdmModel in the container.

Then, your controller should be like :

```
namespace MyProject
{
  public class MyController : Controller
  {
    private IEdmModel edmModel;
    public MyController(IEdmModel myEdmModel)
    {
      edmModel = myEdmModel;
    }

    public IActionResult Index()
    {
      edmModel.InvokeForTest(method, entitySetName, relativeSubPathUri, expression);
    }
  }
}
```

What do you want to do with your extension ? Because you use your instance of ODataController to call InvokeForTest. I don't understand why !
