### ISSUE TITLE
An item with the same key has already been added. 

### ISSUE THREAD

**Issue by jcsotoo92** [aspnet/Mvc#4389]
I get this error when i try to run my app with the command dotnet run

An item with the same key has already been added. Key: Microsoft.DotNet.ProjectModel.ProjectContextBuilder+LibraryKey

**Comment by Eilon** [comment]
@jcsotoo92 which version of `dotnet`? (run `dotnet --version` to find out) And which version of MVC? (Please share your `project.json` file).

@pranavkm any idea?

**Comment by pranavkm** [comment]
This should be fixed when you update to the CLI that Mvc is building with - `1.0.0-beta-002202`

**Comment by jcsotoo92** [comment]
My dotnet version is 1.0.0-beta-001598, how can i update it?

**Comment by Eilon** [comment]
@jcsotoo92 links to all the installers are in the readme file here: https://github.com/dotnet/cli/

**Comment by Eilon** [comment]
Closing because as far as we know this issue is fixed in the latest builds.

**Comment by andriysavin** [comment]
I'm getting similar message with the latest (1.0.0-rc2-002498) version:
"An item with the same key has already been added. Key: Microsoft.CSharp"

**Comment by davidfowl** [comment]
File a bug in the cli with specific repro steps
