### ISSUE TITLE
Support `RemoteAttribute`, including its client-side validation

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#439]
One we have `UrlAttribute` working end-to-end.  But MVC-specific validation attributes do not yet exist.   And the infrastructure for their client-side validation (`IClientValidator`) is also not yet in place.

Note we have no other non-obsolete attributes inheriting from `IClientValidator`.  This may be an opportunity to decide whether to carry forward that particular extensibility point.  `IClientValidator` is easy to use but forces a single class to mix validation with a client-side adaptor.

**Comment by dougbu** [comment]
fixed in commits 1af158330252d56e5828687b74506839febdbd33 to 6cc5cfeae205c934189459d4e827a277155dc93f
