### ISSUE TITLE
How to implement a global business

### ISSUE THREAD

**Issue by BruinY** [aspnet/Mvc#4390]
I have a business background, is the first in first out queue task.Startup can normal visit, regardless of how long to wait for can be normal execution.But when I visit other page after the controller, the business cannot be carried out properly.I don't know why, I want to know how to implement such a global, and only one fifo queue task.
I have tried, static objects is invalid. my project version is asp.net 5 RC1.

**Comment by Eilon** [comment]
We are unable to understand this issue. You can still use global static fields in ASP.NET Core (ASP.NET 5).
