### ISSUE TITLE
`ViewContext.ViewData` should `throw` if set to `null`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4394]
A `ViewContext` instance cannot be created with `ViewData == null`; even the test-only constructor sets the property appropriately. However the `ViewData` property has no `null` checks in its setter and downstream code compensates for the odd possibility of `context.ViewData = null` in user code. We should disallow that possibility i.e. `throw` an `ArgumentNullException` and remove `ViewExecutorTest.ExecuteAsync_ViewResultAllowNull()` -- the only code that uses this "capability".

**Comment by Eilon** [comment]
Not sure I see any big problem allowing it. If anyone does this, they either know exactly what they're doing, or they don't, and they'll see the error in their ways when they get a NullRef.
