### ISSUE TITLE
`ViewExecutor.ExecuteAsync()` should `throw` if passed `viewData: null`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4395]
The part of 0b8fe87 (from PR #3310) which allowed `viewData: null` to be passed into `ViewExecutor.ExecuteAsync()` is no longer necessary. `Controller.ViewData` ensures `[Partial]ViewResult.ViewData` is non-`null` when created. So user code would need to manually set `[Partial]ViewResult.ViewData` to `null` or instantiate a result directly and never set the property for `ViewExecutor.ExecuteAsync()` to see `viewData: null`. Other than two tests specifically for the `ExecuteAsync()`, nothing uses this "capability".

See also #4394.

**Comment by dougbu** [comment]
Oops, submitted too soon...

Could go further and have `[Partial]ViewResult.ViewData` `throw` an `ArgumentNullExeception` if set to `null`. But that would require backing fields in those classes. Further it wouldn't help the `new PartialViewResult()` case. I suggest we leave it at having `ViewExecutor.ExecuteAsync()` do the `throw`ing.

**Comment by dougbu** [comment]
BTW the `ViewExecutor.ExecuteAsync()` that compensates for the `viewData: null` possibility is using an `internal` constructor. Much better to remove the possibility than add yet-another `public` `ViewDataDictionary` constructor.

**Comment by rynowak** [comment]
I'm pretty sure we added this in response to some user-ask. I don't recall what, but I'll bet it's in the history.

**Comment by dougbu** [comment]
> we added this in response to some user-ask

[This conversation](https://github.com/aspnet/Mvc/pull/3310#discussion-diff-41957489) makes it seem I made the suggestion. My bad and we now have more unit test support in `ViewContext`, `Controller` and so on. E.g. action code must ignore `Controller.ViewData` (which cannot be `null`) to construct a result w/ `ViewData == null`. Why support that corner case?

I suspect we were worrying about `TempData` and thought, "What about `ViewData`?" without considering all the ways the two are different.

**Comment by Eilon** [comment]
Would a user ever do this on purpose or by accident? What are we trying to protect here?

**Comment by dougbu** [comment]
> What are we trying to protect here?

As I said above, I think this was about customers doing unit testing. But we have loads of protections elsewhere now and this one looks redundant.

**Comment by Eilon** [comment]
Redundant, as in there's nothing to do here for this issue?

**Comment by rynowak** [comment]
Here's the original discussion https://github.com/aspnet/Mvc/issues/3284

We allowed this on purpose yo.

**Comment by dougbu** [comment]
> We allowed this on purpose yo.

That issue was about `TempData` and `ViewData` was thrown in for grins. Since then other classes such as `ViewContext` have removed the cases where `ViewData` could be `null`.

**Comment by dougbu** [comment]
> Redundant, as in there's nothing to do here for this issue?

Redundant as in this is code that uselessly adds complexity.

**Comment by Eilon** [comment]
This bug is asking to *add* code, isn't it? What code do we want to remove?

**Comment by dougbu** [comment]
Remove
``` c#
            if (viewData == null)
            {
                var services = actionContext.HttpContext.RequestServices;
                var metadataProvider = services.GetRequiredService<IModelMetadataProvider>();
                viewData = new ViewDataDictionary(metadataProvider, actionContext.ModelState);
            }
```

Add (back) just a bog-standard `null` check of the `viewData` parameter.

**Comment by Eilon** [comment]
Sorry, doesn't seem to be enough bang for the buck here.
