### ISSUE TITLE
"dotnet <dll>" doesnt work from the publish folder. refs folder doesn't have required dlls

### ISSUE THREAD

**Issue by sivagms** [aspnet/Mvc#4398]
App: 
https://github.com/aspnet/Performance/tree/sivag/reliability/testapp/HelloWorldMvc

Install dotnet 
clone https://github.com/dotnet/cli
Cd cli
./scripts/obtain/install.ps1

C:\Users\<username>\AppData\Local\Microsoft\dotnet\dotnet.exe restore
C:\Users\<username>\AppData\Local\Microsoft\dotnet\dotnet.exe publish -o pub1
cd pub1
C:\Users\<username>\AppData\Local\Microsoft\dotnet\dotnet.exe .\HelloWorldMvc.dll

Curl http://localhost:5000

   An unhandled exception has occurred while executing the request
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
0g00cmtj.ze2(5,18): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you mi
ssing an assembly reference?)
0g00cmtj.ze2(9,18): error CS0234: The type or namespace name 'Threading' does not exist in the namespace 'System' (are y
ou missing an assembly reference?)
0g00cmtj.ze2(11,86): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required
 type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
0g00cmtj.ze2(11,86): error CS0518: Predefined type 'System.Boolean' is not defined or imported
0g00cmtj.ze2(11,45): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(19,16): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(19,16): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(19,63): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(21,16): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(21,16): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(21,79): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(23,16): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(23,16): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(23,75): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(25,16): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(25,16): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(25,63): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(25,63): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(25,63): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required
 type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
0g00cmtj.ze2(25,63): error CS0518: Predefined type 'System.Boolean' is not defined or imported
0g00cmtj.ze2(25,84): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(30,36): error CS1983: The return type of an async method must be void, Task or Task<T>
0g00cmtj.ze2(30,31): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(30,31): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(30,31): error CS0246: The type or namespace name 'Task' could not be found (are you missing a using directi
ve or an assembly reference?)
0g00cmtj.ze2(30,36): error CS0508: '_Views_Home_Index_cshtml.ExecuteAsync()': return type must be 'Task' to match overri
dden member 'RazorPage.ExecuteAsync()'
0g00cmtj.ze2(30,36): error CS0012: The type 'Task' is defined in an assembly that is not referenced. You must add a refe
rence to assembly 'System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(14,9): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(18,10): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(18,10): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(18,50): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a
 reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(18,10): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(20,10): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(20,10): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(20,50): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a
 reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(20,10): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(22,10): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(22,10): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(22,50): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a
 reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(22,10): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(24,10): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(24,10): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(24,50): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a
 reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(24,10): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(14,16): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(32,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
0g00cmtj.ze2(32,29): error CS0518: Predefined type 'System.Int32' is not defined or imported
0g00cmtj.ze2(32,33): error CS0518: Predefined type 'System.Boolean' is not defined or imported
0g00cmtj.ze2(32,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(32,13): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(32,13): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(33,26): error CS0518: Predefined type 'System.String' is not defined or imported
0g00cmtj.ze2(33,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(33,13): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(33,13): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(34,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a re
ference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
0g00cmtj.ze2(34,13): error CS0518: Predefined type 'System.Object' is not defined or imported
0g00cmtj.ze2(34,13): error CS0518: Predefined type 'System.Void' is not defined or imported
0g00cmtj.ze2(30,36): error CS0161: '_Views_Home_Index_cshtml.ExecuteAsync()': not all code paths return a value
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationResult.EnsureSuccessful()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String normalizedPath, Func`2 compile)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath,
Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocati
onCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pag
eName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage
)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean
isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult
 viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultFilterAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResourceFilterAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
dbug: Microsoft.AspNetCore.Server.Kestrel[6]
      Connection id "0HKQQH32DGMSV" received FIN.
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HKQQH32DGMSV" communication error
Microsoft.AspNetCore.Server.Kestrel.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HKQQH32DGMSV" disconnecting.
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HKQQH32DGMSV" communication error
Microsoft.AspNetCore.Server.Kestrel.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HKQQH32DGMSV" stopped.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2090.6763ms 500 text/html; charset=utf-8
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[5]

**Comment by sivagms** [comment]
@SajayAntony @davidfowl

**Comment by sivagms** [comment]
@pranavkm  @davidfowl  
This fix is not present in 2202 build. so are we taking build newer than 2209 ?

**Comment by pranavkm** [comment]
Yeah - we're working on getting an updated CLI.
