### ISSUE TITLE
System.ArgumentNullException at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Mvc#4399]
Let me know if this is just from churn (will wait) or if you need a repro, and I'll get right on it.
## Exception
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: assemblyName
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts(String entryPointAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services, Action`1 setupAction)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at www_guardrex_com.Program.Main(String[] args)
```
## Environment data
```
.NET Command Line Tools (1.0.0-beta-002198)

Product Information:
 Version:     1.0.0-beta-002198
 Commit Sha:  813049dabe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by davidfowl** [comment]
Please provide a repro

**Comment by GuardRex** [comment]
@davidfowl ... will do. I'll get right on it.

**Comment by javiercn** [comment]
I'll look unto this when i get home

**Comment by GuardRex** [comment]
@javiercn I'm working on the repro now. I have to strip a lot of crap out of this app, but I'll have it up asap.

**Comment by javiercn** [comment]
@davifowl Is there any circumstance in which IHostingEnvironment.ApplicationName can be null? https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L77 We can definitely check for a null ApplicationName, but I don't think this would even work before the application parts changes, as default assembly provider uses the same code.

**Comment by GuardRex** [comment]
FYI: I don't set it. I was driving from SoCal to Pensacola, Florida. I may have missed an Announcement if its required now.

**Comment by javiercn** [comment]
@GuardRex it should be populated by default from the host. I'll investigate more once I get home. If you could provide a repro that would gel a lot. Thanks!

**Comment by GuardRex** [comment]
@javiercn repro almost done ... few more minutes

**Comment by GuardRex** [comment]
@javiercn Got it.

Publishing with `dotnet publish --configuration Release --runtime win81-x64` and then firing off the `.exe`.

https://github.com/GuardRex/repro

```
.NET Command Line Tools (1.0.0-beta-002198)
Product Information:
 Version:     1.0.0-beta-002198
 Commit Sha:  813049dabe
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by davidfowl** [comment]
Should never be null.

/cc @JunTaoLuo

**Comment by GuardRex** [comment]
@davidfowl ... well ... [You didn't guess that @guardrex would find this! :smile: Com'on man.]

https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L268

**Comment by davidfowl** [comment]
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L166

**Comment by GuardRex** [comment]
I want to see `hostingServices.BuildServiceProvider()` next.

**Comment by davidfowl** [comment]
I can repro the bug with your repository.

**Comment by GuardRex** [comment]
I just want to dig a little deeper than I normally do on these.

**Comment by davidfowl** [comment]
So the issue is that MVC is looking at the raw `IServiceCollection` before it's fully built up and we haven't even assigned the name as yet.

**Comment by GuardRex** [comment]
I see ... so nothing wrong on this side of the ledger ... MVC being a little naughty here. :stuck_out_tongue_winking_eye:

**Comment by javiercn** [comment]
I've pushed a fix to hosting that will initialize the hosting environment instance earlier until we figure out an alternative solution for MVC. https://github.com/aspnet/Hosting/commit/4cbda0358b8401ee603421316cf1f3f8f8fb3745

**Comment by GuardRex** [comment]
@javiercn Thanks.

Is #4353 sufficient to track the main repair for this? If so, we can close here. I'm good. Thanks again.

**Comment by javiercn** [comment]
Yeah
