### ISSUE TITLE
Occasional hanging test ProcessAsync_ExceptionInProcessing_DoesntBlockConcurrentRequests

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Mvc#4407]
I am seeing occasional hangs of this test https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.TagHelpers.Test/DistributedCacheTagHelperTest.cs#L606 on Linux (http://aspnetci/viewLog.html?buildId=79739&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR&tab=buildLog#_focus=80061) and have been able to reproduce it on a local machine. 

I'm not too sure what the test does or why it's hanging. @sebastienros I see you have been fixing races related to cache tag helpers, care to take a look?

**Comment by sebastienros** [comment]
I should take care of this. When you say locally, you still mean Linux?

**Comment by JunTaoLuo** [comment]
Yes I reproduced it on my local linux vm.

**Comment by BrennanConroy** [comment]
This is also happening on Windows
http://aspnetci/viewLog.html?buildId=80003&buildTypeId=XPlat_Windows_Win10Universe&tab=buildLog#_focus=97433

**Comment by sebastienros** [comment]
Thanks, that helps. I already have a fix locally that I am testing, but it should just be an issue with the unit test itself, not the feature. The test is trying to test a specific multi-thread scenario and it appears it can go in a wrong state. I have already fixed a similar issue on the same unit test, apparently it's not enough.
