### ISSUE TITLE
is there some replacement for HttpUtility.HtmlAttributeEncode

### ISSUE THREAD

**Issue by omuleanu** [aspnet/Mvc#4411]
I would like to know what are we supposed to use in asp.net 5 / mvc 6 instead of HttpUtility.HtmlAttributeEncode, 
WebUtility has only HtmlEncode

**Comment by dougbu** [comment]
Use `HtmlEncode()` (or `@Html.Encode()` if in a view). The prior distinction between attribute encoding and "regular" encoding was confusing and neither safe nor faster.

/cc @blowdart

**Comment by omuleanu** [comment]
I presume WebUtility.HtmlEncode(str)
and also now it doesn't matter if you're using single or double quotes for your attributes ( with attribute encode double quotes was required )

**Comment by blowdart** [comment]
HtmlEncode now does what is necessary for attribute encoding too. Which is why you can use @ in your views in either case.

**Comment by omuleanu** [comment]
also, I see we get an IHtmlEncoder in 
`public void WriteTo(TextWriter writer, IHtmlEncoder encoder)`
is calling this encoder like this: `encoder.HtmlEncode` any different from
`WebUtility.HtmlEncode`

**Comment by blowdart** [comment]
Yes. WebUtility only replaces the minimum of characters, using a blacklist approach. IHtmlEncoder uses a white listing approach and is more configurable.

I'd strongly suggest taking an IHtmlEncoder into wherever you need to encode.

**Comment by omuleanu** [comment]
WebUtility can be accessed anywhere whereas IHtmlEncoder only in WriteTo afaik,
can we do something like this:
var urlhelper = Html.ViewContext.HttpContext.RequestServices.GetRequiredService<IUrlHelper>()
var encoder = Html.ViewContext.HttpContext.RequestServices.GetRequiredService<IHtmlEncoder>()
?

**Comment by blowdart** [comment]
I need way more context about where you're trying to encode. If you register your classes in DI you can take an IHtmlEncoder in your constructor quite happily.

**Comment by omuleanu** [comment]
well sometimes I'm encoding strings before rendering the html for the helper/component where I have the IHtmlEncoder from the WriteTo method
but there's also a situation like this:
public class Content{
...
private string content;
public string Content
{
     get{ return content.Encode(); }
}
}
used to have an internal extension Encode that was calling AttributeEncode

**Comment by blowdart** [comment]
Honestly I'd leave rendering to the point of output, for example the view.

**Comment by omuleanu** [comment]
well, a collection of these Content objects are loaded via ajax and used in js to generate html, so that would mean encoding them in js, or leaving the responsibility of encoding on the user of the Content class

**Comment by blowdart** [comment]
Oh no no no don't do it that way. Create DOM objects in JS. That way everything gets encoded correctly for the context it's used in.

**Comment by omuleanu** [comment]
you mean doing something like this in js:
str // not encoded,may contain ' or "
var html = "<input value='"+str+"' name='x1' />";

**Comment by blowdart** [comment]
https://stackoverflow.com/questions/8314712/how-do-i-dynamically-populate-html-elements-with-json-data-with-javascript-not-j

That might give you guidance, it's kinda out of scope here :)
