### ISSUE TITLE
Migrating RC1 to RC2. Static files not working

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4414]
I migrated a project from RC1 to RC2 to the point I could build and run.

I'm facing a problem where static files is not working. css, js, etc are not picked up.

I have the `app.UseStaticFiles()` middleware.

project json also has:
```
  "content": [
    "wwwroot",
    "Views"
  ],
```

any idea how can i debug this?

**Comment by Eilon** [comment]
This should be a working sample: https://github.com/aspnet/Mvc/tree/dev/samples/MvcSandbox

Can you compare your app to this and see what differences there are?

**Comment by Bartmax** [comment]
Thank you. I figured it out. turned out to be folder structure error on my side.

**Comment by Eilon** [comment]
Great!
