### ISSUE TITLE
Assembly conflicts with the latest vnext nugets

### ISSUE THREAD

**Issue by bbehrens** [aspnet/Mvc#4417]
I'm just taking a best guess as to the proper repository to report this issue in.  Please move to the correct one if this is wrong.

### Title
After upgrading to the latest version of the dev nugets 20466 I'm getting a bunch of assembly reference errors running 1.0.0-rc2-16595

### Functional impact
Code won't compile, run etc

### Minimal repro steps
My project.json

https://gist.github.com/bbehrens/4e775a12ccf1251b359e502b9ee68ec2

Startup.cs

https://gist.github.com/bbehrens/b1996bc012de5000e654e411fc3a3e86

### Expected result
No compilation errors, dependencies resolve properly

### Actual result
I'm getting a lot more errors similar to this, but I commented out all my code in hopes of providing a concise example.  Here's a list of the errors I'm getting:

![image](https://cloud.githubusercontent.com/assets/61767/14322015/05b709c0-fbe1-11e5-8140-e52e265d91e5.png)

Also note that Microsoft.AspNetCore.Dnx cannot resolve CSharp.Abstractions, CSharp.Common, PlatformAbstractions >= 20222.  These libraries are on the cidev feed, not aspnetvnext.

**Comment by danroth27** [comment]
@pranavkm @davidfowl The RC2 packages are broken with DNX right now. We are investigating options.

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/dnx/issues/3397.
