### ISSUE TITLE
service locator to use in static context

### ISSUE THREAD

**Issue by omuleanu** [aspnet/Mvc#4419]
is there a service locator in mvc 6
I need to use IApplicationEnvironment  (replace old Server.MapPath) 
but inside an html helper (static method), so I don't have a constructor to resolve this service

**Comment by Muchiachio** [comment]
In RC1, there may be a shorter way, but who knows
```C#
Html.ViewContext.HttpContext.ApplicationServices.GetService<IApplicationEnvironment>()
```

**Comment by omuleanu** [comment]
I'm using Microsoft.AspNet.Mvc 6.0.0-rc1-final
and it tells me that `IServiceProfived.GetType(Type) cannot be used with type arguments`
so I have to do something like this:
```
var t = html.ViewContext.HttpContext.ApplicationServices.GetService(typeof (IApplicationEnvironment));
 var path = ((IApplicationEnvironment)t).ApplicationBasePath;
```

**Comment by pranavkm** [comment]
You need to include `Microsoft.Extension.DependencyInjection`. The `IServiceProvider.GetSerivce<T>` extension method is located in it.

**Comment by omuleanu** [comment]
thnx, this compiles
