### ISSUE TITLE
Updating jQuery Unobtrusive Ajax scripts

### ISSUE THREAD

**Issue by rustd** [aspnet/Mvc#4420]
We are using these scripts in MVC 5 as well. Today we are only updating them in bower and npm.
Should we update the NuGet package (https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Ajax/) for MVC 5 as well.

**Comment by danroth27** [comment]
@DamianEdwards Thoughts on this?

**Comment by Eilon** [comment]
This issue was moved to aspnet/jquery-validation-unobtrusive#47
