### ISSUE TITLE
Loading strongly typed views from external assemblies which are loaded runtime

### ISSUE THREAD

**Issue by DavidEmanuelsen** [aspnet/Mvc#4423]
Hi,

We are currently working on an application which needs to load external asssemblies containing strongly typed views and models which are to be used in a generic controller. We've gotten as far as loading the assemblies using a custom AssemblyProvider, and we're able to load the views using either a custom file provider loading the views from the database or using the new EmbeddedFileProvider, but we are having issues when the views are compiled runtime - the model classes isn't being resolved.

It is a requirement that new class libraries / models should be made available without having to restart the application.

What are we missing? After adding the AssemblyProvider for loading assemblies from a custom directory we are able to resolve the type when creating an instance of the dynamically loaded model, but the type is still not resolved during runtime compilation of the razor views.

Any input is very much appreciated

**Comment by davidfowl** [comment]
There's no real nice way to plug this in in RC1, we added an API to do it in RC2.

**Comment by rynowak** [comment]
@pranavkm - can you provide an example of how to configure the Razor compilation assemblies?

**Comment by pranavkm** [comment]
There's a callback on `RazorViewEngineOptions` that lets you configure the Roslyn compilation context:

```C#
var previous = options.CompilationCallback;
options.CompilationCallback = (context) => 
{
    if (previous != null)
    {
        previous(context);
    }
    
    var references = myAssemblies.Select(Assembly.Load).ToArray();
    context.Compilation = context.Compilation.AddReferences(references);
};
```

**Comment by davidfowl** [comment]
That's RC2 the RC1 way is well, super hard 😄

**Comment by davidfowl** [comment]
btw does this actually work?

>     var references = myAssemblies.Select(Assembly.Load).ToArray();

**Comment by pranavkm** [comment]
If it's a sequence of `AssemblyName` instances, it should. Essentially what we do during controller discovery.

**Comment by davidfowl** [comment]
The references are roslyn metadata references not assemblies.

**Comment by pranavkm** [comment]
Oops, fixed the sample.

**Comment by DavidEmanuelsen** [comment]
Thank you very much for the responses. I've now implemented this using the callback described above and it works mostly as I'd expect it to. The issue I'm seeing is that the compilation fails as soon as there is a dependency version conflict between an assembly referenced by the assembly loaded runtime and the running application. This is the error message I'm getting:

Assembly 'CoreSampleService' with identity 'CoreSampleService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Collections, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Collections' with identity 'System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Not sure if this is the correct place to ask these questions, but I thought I'd give it a shot
