### ISSUE TITLE
View Name Searching is case sensitive on Linux/Mac

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Mvc#4426]
I accidently named a view ./Views/Root/index.cshtml (note the lowercase i) and it works on windows fine but when I deployed it to a Linux image, it failed to find it. The controller looks like this:

```
  public class RootController : Controller
  {
    [HttpGet("")]
    public IActionResult Index()
    {
      return View();
    }
  }
```

I changed it to fix it by capitalizing the view name, but I wonder if this is a bug or a feature. Is this expected behavior or should it work the same regardless of what platform it is hosted on?

**Comment by pranavkm** [comment]
We intentionally use the casing used in the action name. You could use a `ViewLocationExpander` to produce paths with a specific casing if you'd like.

**Comment by shawnwildermuth** [comment]
Just don't want there to be differences on different platforms.  If case is important it should fail on Windows too

**Comment by Bartmax** [comment]
totally agree with @shawnwildermuth this is **not** a minor issue.

**Comment by danroth27** [comment]
The view discovery convention is file system based and we don't have any plans to change that. It is not a goal of ASP.NET Core to completely eliminate the differences between platforms.

**Comment by Vasimovic** [comment]
Hi @danroth27, however, there is no easy way to find out if the view path is going to fail, we need to know while developing if the view path is going to fail or not when published or even when publishing on windows platform with precompiled views

**Comment by shawnwildermuth** [comment]
Wouldn't the better solution be to make it case sensitive (would only break some .NET Core apps, not the millions of other app) on all platforms? Making it case sensitive or at least having to match case on Windows would be an easier fix to me (but I am probably over-simplifying).

**Comment by Bartmax** [comment]
That's for the windows team to fix it first. You can't even rename a file to alter casing

**Comment by shawnwildermuth** [comment]
Ok, valid point.

**Comment by hardhub** [comment]
Any news on this? It is still not clear which behavior will be finally implemented on all platforms: case sensitive or not?

**Comment by pranavkm** [comment]
@hardhub the RazorViewEngine uses the same case as the names specified in the controller \ action \ area. However we do not attempt to enforce case sensitivity on the OS's file system's behavior. For e.g.
for `Controller` = `Home`, `Action` = `About`, one of the lookups will be `Views/Home/Index.cshtml`.

If the file is named `views/Home/index.CSHTML` (i.e does not match the exact case as listed above):
* On Windows, the lookup will succeed if you're using runtime view compilation (i.e. without precompilation). 
* On Windows, the lookup will fail if you publish your app with precompilation enabled.
* On non-Windows, the lookup with fail both both using runtime compilation and when the app is published with precompilation.

Our guidance is to match the ensure the casing matches the names of controller, action and area names.

**Comment by Bartmax** [comment]
Since razor compilation will be on by default on the publish stage, more people will be affected by this.

The issue I see here is that people developing on windows will hit this at runtime on production while errors will be silent at development time.

I'm ok with being careful (casing and relative paths) or to need an extra step of publish locally to test everything is working as expected. being said that, any tool/step that can improve the experience will be very appreciated.

**Comment by pranavkm** [comment]
@Bartmax - created a work item to track your suggestion
