### ISSUE TITLE
Revisit expecting an NRE when evaluating Linq expressions (prototype)

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#443]
Helpers such as `@Html.TextBoxFor()` and `@Html.ValueFor()` evaluate user-provided Linq expressions after minor simplifications.  This fails with NREs whenever an intermediate-level property is `null`.  (`IndexOutOfRangeException` should also occur frequently but we don't guard for that case.)  The result is noise when debugging applications using MVC helpers and, potentially, performance degradation.  If there is a performance impact, it should be largest for "Create" views.

One possibility, that's likely been tried before, is to enhance `CachedExpressionCompiler` to convert each property dereference in the expression tree into a conditional expression.

I mention "tried before" because [~eilonlipton] mentioned there's a significant amount of history on this topic.  @GrabYourPitchforks is the one to talk with -- once he's back from //Build.

| 185 | 10343 | Reported By: Doug Bunting (AAPT) |

**Comment by yishaigalatzer** [comment]
@KKhurin I'm assuming you didn't actually hit any real issue here. So I'm moving post RTM where we can try and take a second look.

**Comment by Eilon** [comment]
No plans to change this behavior.
