### ISSUE TITLE
Many unused instances of ModelErrorCollection during model validation

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Mvc#4435]
Class `ModelStateDictionary` initializes a root `ModelStateNode` and then creates new child nodes during validation of a model. Class `ModelStateNode` inherits `ModelStateEntry` which has a non-null complex field of type `ModelErrorCollection`. This field is non-null as it's initialized on the constructor of `ModelStateEntry`, which is unnecessary.

We should lazily initialize the field with a ModelErrorCollection only when required. Each allocation spends 72 bytes. After only 1500 API calls we're already allocating and collecting 108,000 bytes.

**Comment by dougbu** [comment]
`ModelStateDictionary` checks `Errors.Count` on `ModelStateNode` multiple times. Would be surprising if lazy initialization saved many `ModelErrorCollection` instances. Have you measured that part of this PR on its own?

**Comment by DavidObando** [comment]
Yes, the count of elements went down to zero in my memory profile. I'll add more details when I get back to my workstation.

**Comment by DavidObando** [comment]
@dougbu @rynowak I ran a test of 1500 POST calls with JSON payloads ranging between 14 KB and 500 KB. Here's the instance count of types with the text "Error" in it, before the change:

![image](https://cloud.githubusercontent.com/assets/950290/14436404/60174350-ffd1-11e5-9170-87b82407d1d7.png)

This is what I see after the change:

![image](https://cloud.githubusercontent.com/assets/950290/14436412/69c537ae-ffd1-11e5-8fff-e9de952c05ea.png)

I'm currently working to get this test into the Performance repository.

**Comment by rynowak** [comment]
So 1 instance allocated/saved per request for what you're measuring :laughing:. I think you'd have to look at a model-binding (non-JSON) scenario to get any significant data.

My opinion: go ahead with the change you proposed, but leave the bug open. I think we need to measure more scenarios.

**Comment by DavidObando** [comment]
Yes, 1 per request. It's not much, but it's an easy gain to put less pressure on the GC. I'll continue with the PR, leave this item open, and will sync up with you later offline regarding the additional scenarios you mentioned. Thanks!

**Comment by Eilon** [comment]
Moving to post-v1; can do this fix at any time.
