### ISSUE TITLE
validate Viewmodel without ModelState/post/controller

### ISSUE THREAD

**Issue by omuleanu** [aspnet/Mvc#4437]
hi,
having a viewmodel with attributes defined

```
public class PersonInput {
[Required]
public string Name { get; set; }
...
}
```

is it possible to validate it without going through the form post
something like 

```
var input = new PersonInput();
setvalues(input);
IDictionary<string,string> errors = ModelValidator.Validate(input); 

```

**Comment by dougbu** [comment]
Use the `TryValidateModel()` methods available in your controller if you've inherited from `Controller`.

**Comment by omuleanu** [comment]
this  returns a bool,
I need to pass in an instance of an object and get a dictionary (field, error message)
actually I would do this in a loop for many objects, 
is this possible now ?

**Comment by dougbu** [comment]
Look at the `ModelStateDictionary` if the method returns `false`.

**Comment by omuleanu** [comment]
so basically 
call TryValidateModel
if false, get the dictionary result from ModelStateDictionary
repeat as many times as needed
any plans to make this functionality accessible directly, not via controller and modelstate ?

**Comment by dougbu** [comment]
`ModelStateDictionary` _is_ an `IReadOnlyDictionary<string, ModelStateEntry>` (`IDictionary<string, ModelStateEntry>` in RC1 and earlier). What's indirect?

More generally why repeatedly set values in your model until it's valid? If you're mapping those values from user input i.e. a form submission, I'd expect a one-shot process.

**Comment by omuleanu** [comment]
it's not about setting the model until it's valid, 
it's for batch editing,
the user modifies multiple items at once and the changes are sent via js/ajax to the server and I would need to pass back the errors (if any) for each item
the model received doesn't contain the ViewModel that I'm validating but rather a collection of tuples {id, "Property", NewValue}
after I would get the items from the Db,
apply the changes,
and validate them

**Comment by Eilon** [comment]
Parking in Backlog because we will not have time to do this for v1.

**Comment by rynowak** [comment]
I'm adding this to a meta-issue that I'm collecting for improvements to the model binding system #6549

We have no plans to add this feature as a one-off, but it would be part of a major rewrite if we decide to do it.
