### ISSUE TITLE
Move ExpressionFingerprintChain over from legacy MVC

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#444]
Ask here is to determine whether `CachedExpressionCompiler`'s performance is slow, once we have performance profiles.  Then, if it is slow, decide whether the legacy `CachedExpressionCompiler.CompileFromFingerprint()` method addresses the issues and (perhaps) move that method, associated cache, and supporting classes over.

Legacy MVC's `CompileFromFingerprint()` uses infrastructure built up from
- `ExpressionFingerprintChain` (an equatable list of `ExpressionFingerprint` instances)
- `Hosted` (a delegate)
- `HoistingExpressionVisitor` (a Linq `ExpressionVisitor`)
- `FingerprintingExpressionVisitor` (another Linq `ExpressionVisitor`)
- `ExpressionFingerprint` (an abstract class)
- 11 classes derived from `ExpressionFingerprint`

This infrastructure was apparently included in `CachedExpressionCompiler` for performance reasons.  But it's a lot of code to copy over without confirming performance concerns in the new world.

| 184 | 10342 | Reported By: Doug Bunting (AAPT) |

**Comment by danroth27** [comment]
@rynowak @NTaylorMullen @Eilon  Is this issue still tracking relevant work? Should we just close it?

**Comment by rynowak** [comment]
Further study is needed. We should try to collect some data on the current performance and then make a decision

**Comment by dougbu** [comment]
Agree with whichever Ryan that was. @mnltejaswini did lots of perf work in this area but we haven't checked whether `ExpressionFingerprintChain` would address any remaining slowness or memory use.
