### ISSUE TITLE
Remote Validation action is not executed

### ISSUE THREAD

**Issue by mdmoura** [aspnet/Mvc#4445]
Hello,

I am using ASP.NET CORE RC1 and I have the following model:

    public class AccountSignUpModel {

      [EmailAddress(ErrorMessage = "Email is invalid")]
      [Required(ErrorMessage = "Email is required")]
      [Remote("IsEmailAvailable", ErrorMessage = "Email already used", HttpMethod = "Post")]
      public String Email { get; set; }

    }

And I have the following controller:

    public class ValidationController : Controller {
      [HttpPost(Name = "IsEmailAvailable")]
      public IActionResult IsEmailAvailable(String email) {
        return new JsonResult(false);
      }
    }

I also tried the following:

    public class ValidationController : Controller {
      [HttpPost(Name = "IsEmailAvailable")]
      public IActionResult IsEmailAvailable(AccountSignUpModel model) {
        return new JsonResult(false);
      }
    }

When I submit the model the Remote validation is never executed ...

I placed a breakpoint inside the IsEmailAvailable action and it does not get there.
I tried many variations of this code but the action is never executed ...

I don't get any exception ... Any idea what might be wrong? 

Thank You,
Miguel

**Comment by dougbu** [comment]
> Any idea what might be wrong?

Is client-side validation enabled? That is, confirm the following or the CDN equivalent appears in your layout:
``` html
<script src="~/lib/jquery/jquery.js"></script>
<script src="~/lib/jquery-validation/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
```

**Comment by mdmoura** [comment]
Yes, I have those scripts on my master page an no error there.

A side question: 
Can an Entity Framework DbContext be injected in a custom validator in ASP.NET Core?

**Comment by dougbu** [comment]
@mdmoura we need additional information to determine what is going on here. Please upload a minimal repro, preferably to a public GitHub repo.

**Comment by dougbu** [comment]
> Can an Entity Framework `DbContext` be injected in a custom validator in ASP.NET Core?

As long as the `DbContext` is in DI, I'd recommend implementing `IModelValidator` in an `Attribute` subclass. Use `context.ActionContext.HttpContext.RequestServices.GetService...` in your `Validate()` implementation. Then associate that attribute with the property or type of interest.

**Comment by Eilon** [comment]
@mdmoura can you perhaps use a tool such as your browser's network trace or Fiddler and see if the request is even being made by the browser? That would help narrow down if it's a client-side issue or server-side.

**Comment by dougbu** [comment]
@mdmoura I experimented w/ `[Remote]` over the weekend. Other than when using a corrupt `jquery.validate.unobtrusive.min.js` I downloaded, I did not see any issues. Please provide a repro project or the client-side / server-side information @Eilon requested.

**Comment by mdmoura** [comment]
@Eilon Sorry for the delay but I was away and came back only today.

I just uploaded an example here: https://github.com/mdmoura/AspNetCoreValidation
When you run it you can see a form which submits a model that has the Remote attribute.
The Validation action in Home does not fire when I submit the form ...

To be honest I am not very familiar with Attribute Validation since I always used Fluent Validation.
I'm using Attribute Validation since Fluent Validation does not have yet a Core compatible version.

Does the example helps?

**Comment by dougbu** [comment]
@mdmoura your views contain no references to the `FormModel` type or a property of that type. If you want MVC involved in HTML generation, you must use HTML or tag helpers e.g.
``` html
@using AspNetCoreValidation.Models
@model FormModel
...
<input asp-for="Name" data-ng-model="vm.data.name" name="vm.data.name" placeholder="name" type="text" /><br />
```

The project has additional problems, mostly due to the hard-coded field names for Angular e.g. must update the validation method to bind correctly:
``` c#
[HttpPost(template: "form/validate", Name = "IsNameAvailable")]
public IActionResult IsNameAvailable([FromForm(Name = "vm.data.name")] string name)
```

Note the `[HttpPost]` attribute ignores the `Name` unless you're using attribute routing. That change is included above.

**Comment by mdmoura** [comment]
@dougbu Got it! In this case it won't work for me as I will have all HTML in html files under wwwroot and using Angular. But I decided to either go for FluentValidation and wait a while for its Core compatible version or maybe creating a simple validation framework that works for me. I think it would be great that ASP.NET Core would have some type of validation closer to Fluent Validation instead of Validation by Attributes. In largest projects validation by attributes it not very friendly.

**Comment by dougbu** [comment]
Turning this into a Task issue because we aren't currently testing `[Remote]` with a route name. And the existing test site can't be tested manually to confirm it works end-to-end.

**Comment by dougbu** [comment]
e3db547

**Comment by wgutierrezr** [comment]
I have this issue with ASP.Net Core 2.1.5 MVC.
