### ISSUE TITLE
Poll on file watch

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Mvc#4451]
Moved from here https://github.com/aspnet/Razor/issues/733

cc @DamianEdwards @Eilon

**Comment by pranavkm** [comment]
We realized there isn't any work in Mvc. https://github.com/aspnet/FileSystem/issues/181 will handle Mvc's scenarios.

**Comment by pranavkm** [comment]
Fixed in FIleProvider via https://github.com/aspnet/FileSystem/issues/181
