### ISSUE TITLE
Problem with Services.AddSingleton<IConfiguration>(_=>Configuration) 

### ISSUE THREAD

**Issue by jcsotoo92** [aspnet/Mvc#4453]
I can´t add the configuration by dependency injection, i have this line:

 Services.AddSingleton<IConfiguration>(_=>Configuration) ;

and it shows an error, i've tried to found the correct syntax but i could not.

**Comment by davidfowl** [comment]
Are you using RC1?

**Comment by jcsotoo92** [comment]
im using 1.0.0-rc2-20221

**Comment by mikes-gh** [comment]
Services.AddSingleton<IConfiguration>(_ => { return Configuration });

**Comment by mikes-gh** [comment]
Ps if there's a better more readable way I would like to know

**Comment by jcsotoo92** [comment]
@mikes-gh It shows an error still

**Comment by mikes-gh** [comment]
Post your error and your Startup.cs

**Comment by jcsotoo92** [comment]
using Microsoft.AspNetCore.Builder;
using System;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Hosting;

namespace grole.src
{

    public class Startup
	{
		
		public IConfiguration Configuration { get; set; }

        public Startup()
        {
            var builder = new ConfigurationBuilder().AddJsonFile("Config.json");
            Configuration = builder.Build();
        }
		
		public void ConfigureServices(IServiceCollection Services)
		{

            Services.AddMemoryCache();
            Services.AddSession(o =>
            {
                o.IdleTimeout = TimeSpan.FromDays(1);
            });
            Services.AddAuthentication();
            Services.AddSingleton<IConfiguration>(_ => { return Configuration; }); 
            
            Services.AddMvc();
            Services.AddMvcDnx();
        }
		
		public void Configure(IApplicationBuilder app)
		{
            app.UseIISPlatformHandler();
            app.UseSession();
            app.UseDeveloperExceptionPage();

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                ExpireTimeSpan = TimeSpan.FromDays(1),
                AutomaticAuthenticate = true,
                LoginPath = "/Account/Login"
            });
            app.UseStaticFiles();
			app.UseMvcWithDefaultRoute();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}");

                // Uncomment the following line to add a route for porting Web API 2 controllers.
                // routes.MapWebApiRoute("DefaultApi", "api/{controller}/{id?}");
            });
        }

        public static void Main(string[] args)
        {
            var application = new WebHostBuilder()
                .UseDefaultHostingConfiguration(args)
                .UseIISPlatformHandlerUrl()
                .UseKestrel()
                .UseStartup<Startup>()
                .Build();

            application.Run();
        }

    }
	
}



and the error:

The type 'IServiceProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ComponentModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by mikes-gh** [comment]
https://github.com/aspnet/DependencyInjection/issues/385

**Comment by pranavkm** [comment]
You can replace your code `Services.AddSingleton<IConfiguration>(_ => { return Configuration; });` `Services.AddSingleton<IConfiguration>(Configuration);` and the error should go away. Alternatively add the reference in your `project.json` under the `frameworkAssembly` node:` "frameworkAssemblies": { "System.ComponentModel": "4.0.0" }`
.

**Comment by jcsotoo92** [comment]
it works, thanks
