### ISSUE TITLE
Confusing overloads of Controller.CreatedAtRoute()

### ISSUE THREAD

**Issue by chaim770** [aspnet/Mvc#4454]
Following this StackOverflow post:
http://stackoverflow.com/questions/36560239/asp-net-core-createdatroute-failure/36560599

It's very easy to confuse the overloads of the `CreatedAtRoute` method:

```
CreatedAtRoute(string routeName, object value)
CreatedAtRoute(string routeName, object routeValues, object value)
```

Coming from MVC 5 background (even though I briefly looked in the source code of the method here in GitHub), I was unable to notice the difference between `objectValue` and `routeValues`.

**Comment by brentarias** [comment]
The problem is not merely that it is "confusing," it is also that the overloads are simply wrong.  Here is what they should be:

    CreatedAtRoute(string routeName, object routeValues);
    CreatedAtRoute(string routeName, object routeValues, object value);

It appears one of the overloads should be completely removed:

   CreatedAtRoute(object routeValues, object value);

...unless somebody can explain how the above works, and when it would ever be used.

**Comment by Eilon** [comment]
@ajaybhargavb can you take a look at this?

**Comment by ajaybhargavb** [comment]
Discussed with @Eilon and @rynowak. We think that all the overloads we currently have are useful in some cases. So we are not going to change anything here. For your case, we recommend using this overload `CreatedAtRoute(string routeName, object routeValues, object value)` and pass in `null` to the `value` parameter.

**Comment by dougbu** [comment]
@ajaybhargavb should this be labelled was won't fix, invalid or by design?

**Comment by ajaybhargavb** [comment]
Done

**Comment by timeshifter** [comment]
Passing null into the value parameter results in a literal string "null" being returned as the body. I'm with @brentarias, the parameter names are confusing and deceptive, and should be clarified.
