### ISSUE TITLE
Can not find runtime target for framework '.NETFramework,Version=v4.5.1'

### ISSUE THREAD

**Issue by jcsotoo92** [aspnet/Mvc#4456]
i get this error when i try to run my app with the command dotnet run

Can not find runtime target for framework '.NETFramework,Version=v4.5.1' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.

**Comment by pranavkm** [comment]
This would be a question for the CLI: https://github.com/dotnet/cli. You might be able to make it work with `dotnet restore --infer-runtimes` depending on the version of the CLI you're using.
