### ISSUE TITLE
Optimize processing of indexer expressions in ExpressionHelper.InsertIndexerInvocationText

### ISSUE THREAD

**Issue by mnltejaswini** [aspnet/Mvc#4458]
If a Razor view has several indexer expressions in HtmlHelpers/TagHelpers as shown below

```c#
for (var i = 0; i < Model.Count; i++)
{
            
            <div class="contact-card">
                @Html.LabelFor(m => Model[i].HomePhone)
                <b id="@Html.IdFor(m => Model[i].HomePhone)">@Model[i].HomePhone</b>
                <br />

                @Html.LabelFor(m => Model[i].Mobile)
                <b id="@Html.IdFor(m => Model[i].Mobile)">@Model[i].Mobile</b>
                <br />

                @Html.LabelFor(m => Model[i].MailId)
                <b id="@Html.IdFor(m => Model[i].MailId)">@Model[i].MailId</b>
                <br />

                @Html.LabelFor(m => Model[i].CurrentJob)
                <b id="@Html.IdFor(m => Model[i].CurrentJob)">@Model[i].CurrentJob</b>
                <br />

                @Html.LabelFor(m => Model[i].PastJobs)
                @Html.ActionLink("Edit", "Edit", new { id = Model[i].MailId })
            </div>
}
```

ExpressionHelper.InsertIndexerInvocationText is invoked to resolve the value of the indexer "i" each time it is used. In the above case, it is invoked 13 times per iteration.  
The value of the indexer expression is resolved by using CachedExpressionCompiler.Process. 
This is fairly expensive as it goes through the CompileSlow path causing the expression to be compiled each time. 

![image](https://cloud.githubusercontent.com/assets/8011073/14509883/6c4e0c54-0183-11e6-84d6-644a15feca4a.png)

When an expression is a member access within a captured local, CachedExpressionCompiler caches the delegate. In our case each of the indexer expression is originally a Member Access Expression over a captured local, but the cache is not used because of the following 
 var converted = Expression.Convert(indexExpression, typeof(object));  that we do before calling into CachedExpressionCompiler.Process . This conversion is needed because CachedExpressionCompiler is a generic class on the result type of expression. 

One possible solution is to create a separate non generic version of CachedExpressionCompiler that returns an object specifically to be used by ExpressionHelper.InsertIndexerInvocationText or any other better solutions need to be explored. 
 Related : #3921

**Comment by dougbu** [comment]
What is a valid scenario that involves "several indexers"? This sounds like a documentation issue: We should demonstrate how to avoid repeated evaluation of index expression. This also sounds like the exact reason we decided to close #3921 when we did.

**Comment by mnltejaswini** [comment]
Talked @dougbu  offline. This issue is logged to track the performance issue with indexer expressions. This will be handled based on the priority.

**Comment by rynowak** [comment]
@mnltejaswini - can you please update the initial comment to include some sample code. Otherwise this will be lost to the sands of time.

**Comment by mnltejaswini** [comment]
@rynowak  Do you think it would be helpful to check in a new view to BigViews scenario that will have several  indexers?

**Comment by rynowak** [comment]
No, I think it would be helpful to update the initial comment to include some sample code. We can't prioritize the bug without and understanding of what code leads to this problem.

**Comment by Eilon** [comment]
Though this might be an area that could use some optimizations, my feeling is that the amount of work it would take to correctly resolve this would be huge - perhaps at least a week of work. The hard part is fingerprinting the expressions with the appropriated captured state to know what's a cache hit and what's a miss.
