### ISSUE TITLE
Map int[] with many dropdownList

### ISSUE THREAD

**Issue by tango-charly** [aspnet/Mvc#4460]
Hi,

I have to map a int[] with many @dropdownlist

  ```
@Html.DropDownList("MyModel.MyIntArray[0]", this.Model.MySelectList,
  new {@class = "form-control" @id ="MyModel_MyIntArray_[0]" })
// value = 4
@Html.DropDownList("MyModel.MyIntArray[1]", this.Model.MySelectList,
  new {@class = "form-control" @id ="MyModel_MyIntArray_[1]" })
// value = 5
```
When i wrote this, i got MyModel.MyintArray { 4 }
But, I exptected {4,5}

How to map a int array with many dropdownlist with Razor ? 
And where is the official documentation for razor ?

Thank's a lot :)

**Comment by dougbu** [comment]
Use `@Html.ListBox()` if you want multi-selection.

**Comment by Eilon** [comment]
@tango-charly can you clarify what kind of UI you are trying to generate and what the models look like?

**Comment by Eilon** [comment]
Sorry, it is unclear what is being asked here.
