### ISSUE TITLE
Razor View Issue - The Name 'ViewData' does not exist in the current context.

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Mvc#4462]
I should start by saying my project runs OK
This happens in my project but for the sake of repro I have used known sample.

**Steps to repro.**

Clone Mvc Repo
Open MvcSandbox xproj from the Mvc repo
Open the Index Razor View.

**Result**

![context](https://cloud.githubusercontent.com/assets/16208742/14495262/9ac31d56-0186-11e6-832c-fd78bb250c7d.png)

Also happens with eg ViewContext,Model ViewBag .  Not all types are affected though.

**Comment by dougbu** [comment]
The Razor tooling isn't used in that project -- or any web site in the Mvc repo. @ryanbrandenburg might make that change as part of #4429.

**Comment by NTaylorMullen** [comment]
Similar conversation [here](https://github.com/aspnet/Razor/issues/596#issuecomment-209535322) with @mikes-gh. Probably the same outcome.

FYI: `dotnet-razor-tooling` is only for `TagHelper` IntelliSense.

**Comment by NTaylorMullen** [comment]
Ah, so you're using the MvcSandBox site. Here's what could be causing your issue:

IF You've modified the source:
- You removed `Microsoft.AspNetCore.Mvc.Razor` from the project (and thus it doesn't have a `RazorPage` class anymore.
- You added an `@inherits` directive somewhere in the application that effects the page.

IF you have not modified the source or none of the above apply:
- Packages did not restore correctly (dotnet restore).
- Your tooling may be broken
  - @mikes-gh With this guy, does doing file new => web application => starter web give you IntelliSense in the editor? If not, your issue could link back to not being able to restore properly. Could be an incompatibility in dnu with our new TFMs

**Comment by mikes-gh** [comment]
@NTaylorMullen 
- I have update 2 installed so TFMs should be OK and restore seems to be ok.
- Most intellisense works i.e. not all of it is broken.
- I deleted all the files in ComponentModelCache dir didn't help.
- I used the MvcSandbox as is no code changes.
- I guess I need to reinstall vstudio if no one else is seeing this.

**Comment by NTaylorMullen** [comment]
@mikes-gh If you try the same thing with a new project do you see errors in your Razor files? If so then yes, your VS would be busted. However, if not i'll have to poke around a bit more :smile:

**Comment by mikes-gh** [comment]
Ok will report back however I don't think starter web template will work as its still rc1 in vstudio.  How do you want me to do new project

**Comment by NTaylorMullen** [comment]
Even rc1 in VisualStudio will be fine. I want to validate that your Razor tooling bits are working as intended. If they're broken, it shouldn't matter if it's rc1 templates; it'll broken no matter what :smile:

**Comment by mikes-gh** [comment]
New web project using aspnet 4.6 and aspnet 5 rc1 templates is working fine.
That would seem to indicate my razor syntax highlighting autocomplete  is working.

Would be nice to know if someone else can report my issue with mvcsandbox

**Comment by NTaylorMullen** [comment]
@mikes-gh Does everything work in VS if at the command line you run `dotnet restore --infer-runtimes`?

**Comment by mikes-gh** [comment]
Get a load of errors about packages not being compatible with dnxcore50.  Probably due to the template being rc1

**Comment by mikes-gh** [comment]
@NTaylorMullen Have you tried opening the mvcsandbox sample?  Would be good to see if this is reproducible.

**Comment by mikes-gh** [comment]
@NTaylorMullen 

Smallest repro possible

https://github.com/mikes-gh/WebApplication4
Currently set to rc1-final

note I am using aspnetvnext feed in visualstudio but you could use an NUget.config is doing command line.
- restore packages
- open index.cshtml all ok
- change project.json to reference rc2 version

**before**
```
Microsoft.AspNet.Mvc": "6.0.0-rc1-final"
```
**after**
```
Microsoft.AspNetCore.Mvc": "1.0.0-rc2-*"
 ```
- restore packages
- reopen index.cshtml
- wait a few seconds to see the problem

**Comment by NTaylorMullen** [comment]
@mikes-gh Ahh yes if you're trying to upgrade the template there's a lot that needs to be done in addition to changing the versions. If you do the `dotnet restore --infer-runtimes` on the MvcSandbox does all work well in the editor?

**Comment by mikes-gh** [comment]
@NTaylorMullen I thought the sample I gave was version agnostic .  Did you try repro steps?

>  dotnet restore --infer-runtimes  

Gives same result 
The Name 'ViewData' does not exist in the current context

**Comment by mikes-gh** [comment]
> Ahh yes if you're trying to upgrade the template there's a lot that needs to be done in addition to changing the versions

Its not a template its a bare bones MVC reference and index.shtml to demo the issue.
I am aware rc1 templates are far away from rc2 stuff thats why I created the repo.

**Comment by mikes-gh** [comment]
Please could someone try my github repo and  repro steps. (time < 5 mins).
If tooling needs fixing for rc2 time is running out.
If not I can reinstall vstudio and report back but Id rather someone confirm either way first.

**Comment by NTaylorMullen** [comment]
Hey @mikes-gh I took a look at your repro. When I open the project with it referencing aspnet.mvc it red squiggles the `ViewData` but then once I upgrade it to aspnetcore.mvc it highlights fine.

This leads me to beleive that your `dotnet` may be out of date. What does `dotnet --info` return for you?

**Comment by mikes-gh** [comment]
Strange I get the opposite behaviour.  Red squiggle in aspnetcore rc2  but not in aspnet.rc1.
What updates are you running for visual studio?
Either way shouldn't it work for both rc1 and rc2?
dotnet downloaded a few days ago 2372

**Comment by NTaylorMullen** [comment]
@mikes-gh Ooo, I see. Sorry, I've been stuck in RC2 world for so long I forget that the tools that I use on a daily basis are pre-release and not available to the general public quite yet. The reason why you're seeing what you're seeing is that in your tooling, Razor is generating using statements to `Microsoft.AspNet.X` because it's RC1 tooling and happened before the `AspNetCore` rename. However, once you change your project.json to point to an RC2 project all of your references then bring in `Microsoft.AspNetCore.X`. Since tooling is generating code behind the scenes that expect there to be packages referencing `Microsoft.AspNet.X` and your project doesn't actually include them (you upgraded it) your base type for your view can't be resolved (there is no `ViewData` property available on a type that can't be resolved :smile: ).

Once new tooling is released all your issues will be resolved. Sorry for the inconvenience!

**Comment by mikes-gh** [comment]
Ah i see makes sense.  Tooling is either rc1 or rc2.  You get opposite behaviour because you are on rc2 tooling and I am on rc1 tooling.

I look forward to the rc2 tooling.  Is there anywhere I can track that.

**Comment by NTaylorMullen** [comment]
@mikes-gh I'd recommend keeping up-to-date with the ASP.NET standups; that's where release dates will most likely hit the public first. You can watch them [here](http://live.asp.net). Other then that once RC2 is released tooling will come with it :smile:

**Comment by mikes-gh** [comment]
@DamianEdwards said the rc2 tooling would support rc1 and rc2 in community standup.
I'm fine with leaving rc1 behind but pinging here in case that was the intention and this issue got missed.

At the moment from what you're saying it sounds like rc2 tooling doesn't support rc1 references in terms of razor page intelisense.

**Comment by NTaylorMullen** [comment]
Oh, no the current plan is for RC2 tooling to support both RC1 and RC2 projects. Sorry if what I said mislead you.
