### ISSUE TITLE
Move netstandardapp1.5 references to netcoreapp1.0

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#4464]
With the move to netcoreapp1.0 we'll need to go through and remove references to netstandardapp1.5 including in places like [this](https://github.com/aspnet/Mvc/pull/4429/files#diff-c8165f798a2bc357e363dd68cc81cc4fR18).

**Comment by TrabacchinLuigi** [comment]
+1

**Comment by Eilon** [comment]
@ryanbrandenburg I assume you mean "with the move to **netcoreapp1.0**", right?

**Comment by Eilon** [comment]
And also I assume where you say `netstandard` you mean `netstandardapp`?

**Comment by davidfowl** [comment]
Yea this issue title is ambiguous

**Comment by ryanbrandenburg** [comment]
Correct on both counts, will update.

**Comment by Eilon** [comment]
Ok 😄

**Comment by Eilon** [comment]
@pranavkm @NTaylorMullen @ryanbrandenburg I'm not super up-to-date on exactly who's doing which part of this already. Are one of you already working on this for RC2?

**Comment by ryanbrandenburg** [comment]
I'm doing part of this in #4429 but we'll also have to go back as the packages under us move to netcoreapp1.0 and remove netstandardapp1.5 from it's imports.

**Comment by Eilon** [comment]
Do we need to do anything for RC2? I guess this is just tests and samples so it can wait?

**Comment by ryanbrandenburg** [comment]
Yeah, not super urgent as far as I know, 1.0.0 would probably be fine as a milestone unless @pranavkm knows better.

**Comment by Eilon** [comment]
Ok I'll park in 1.0.0 for now.

**Comment by ryanbrandenburg** [comment]
Looks like this has already been taken care of, no instances of netstandard1.5 in the code now.
