### ISSUE TITLE
Form Tag Helper Breaks with atypical html comments

### ISSUE THREAD

**Issue by avietech** [aspnet/Mvc#4465]
Recieving the error ```Found a malformed 'form' tag helper. Tag helpers must have a start and end tag or be self closing.``` with the following razor view:

```
@model PracticeEditViewModel

@{
    Layout = null;
}

<div class="form-horizontal" style="padding-left:15px;">
    <form asp-controller="Practice" asp-action="PracticeEdit" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal" role="form">

        <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>

        <input asp-for="practice.AccountGuid" class="form-control" type="hidden" />

        <fieldset>
            <!--- column 1 --->
            <div class="col-sm-6">

                <div class="form-group">
                    <label asp-for="practice.AccountGuid" class="col-md-4 control-label">Account Guid</label>
                    <div class="col-md-6">
                        <p class="form-control-static">@Model.practice.AccountGuid</p>
                    </div>
                </div>

            </div><!--- end column 1 --->
            <!--- column 2 --->
            <div class="col-sm-6">

                <div class="form-group">
                    <label asp-for="practice.AddressLine1" class="col-md-4 control-label">Address</label>
                    <div class="col-md-6">
                        <p class="form-control-static">@Model.practice.AddressLine1</p>
                    </div>
                </div>


            </div><!--- end column 2 --->
        </fieldset>

        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-default">Update</button>
            </div>
        </div>

    </form>
</div>
```

**Please note that if you change the comment ```<!--- end column 2 --->``` to ```<!-- end column 2 -->``` with two dashes instead of three, the view compiles as expected.**

**Comment by dougbu** [comment]
Comments ending with more than two dashes are not valid HTML. See https://www.w3.org/TR/html5/syntax.html#comments

**Comment by Eilon** [comment]
Indeed, that is not valid HTML, though I wonder if we can be more relaxed about it. There's tons of invalid HTML that Razor gladly allows (such as random garbage unencoded entities, certain other malformed tags, attributes, etc.).

@NTaylorMullen putting this on your plate to consider for 1.0.0. If it's too complex to handle, we can move to Backlog.

**Comment by avietech** [comment]
Even if the non-standard comment is not allowed, maybe make the error message more accurately reflect the true nature of the problem. Thanks!

**Comment by Eilon** [comment]
@avietech fair enough - the error is indeed quite misleading.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Razor/commit/d0bf6bf841c47ade8b767aeb3213fcdc65b59f9d
