### ISSUE TITLE
Reduce allocations in Link/Script TagHelper

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4468]
Allocation data from BasicViews:

![image](https://cloud.githubusercontent.com/assets/1430011/14510446/5b4c50fc-0186-11e6-942a-5bf301099b56.png)

Looking here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/LinkTagHelper.cs#L259

We create a new `DefaultTagHelperContent` object which we fill with content, and then ultimately add to the output builder. The output builder already gets recycled, we can just use it directly.

**Comment by rynowak** [comment]
@mnltejaswini - please work with @dougbu to answer any questions you have about this code

**Comment by dougbu** [comment]
FYI the fix for this bug will likely not change the allocations @rynowak showed above. Instead this will save initial `DefaultTagHelperContent` and `List<object>` allocations. Some `DefaultTagHelperContent` somewhere will still be expanded. But it's a nice fix and simplifies the code :smiley_cat:

**Comment by mnltejaswini** [comment]
@dougbu  It did reduce the allocations in the code path pasted by @rynowak 
Scenario:  https://github.com/aspnet/Performance/tree/dev/testapp/BasicViews
loadtest.ps1
Before Optimization 
------------------------
![image](https://cloud.githubusercontent.com/assets/8011073/14578213/d738722a-0336-11e6-8135-341e03b54b99.png)


After Optimization
-----------------------
![image](https://cloud.githubusercontent.com/assets/8011073/14578205/ace303e6-0336-11e6-9d03-3c1c67bce6a8.png)
