### ISSUE TITLE
RazorPage.CreateModelExpression is allocating expression names

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4469]
This is allocation data from BasicViews. All of these expressions are simple property accessors and should be cached, so something isn't working right.

![image](https://cloud.githubusercontent.com/assets/1430011/14511650/dd83d098-018d-11e6-8742-0739ed12a6ba.png)

**Comment by mnltejaswini** [comment]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorPageOfT.cs  has a private property named ExpressionTextCache. But this property is not listed in the result of type.GetRunTimeProperties() when querying for properties to activate in PropertyActivator<ViewContext>.GetPropertiesToActivate(). Ideally type.GetRunTimeProperties()  should return all properties including private as the binding flags include BindingFlags.NonPublic. 
But as per MSDN https://msdn.microsoft.com/en-us/library/kyaxdd3x(v=vs.110).aspx " Specify BindingFlags.NonPublic to include non-public properties (that is, private, internal, and protected properties) in the search. Only protected and internal properties on base classes are returned; **private properties on base classes are not returned**. ", 

This applies to our scenarios where all the  razor pages have the base type as RazorPage<TModel>. Hence the ExpressionTextCache is not listed in the runtime properties and there by the cache is not used in the ExpressionHelper. Can we change the property ExpressionTextCache in RazorPageOfT.cs to protected?

**Comment by mnltejaswini** [comment]
@rynowak , @dougbu

**Comment by dougbu** [comment]
> ideally `type.GetRunTimeProperties()` should return all properties including `private` as the binding flags include `BindingFlags.NonPublic`.

I don't agree that would be ideal. The `ExpressionTextCache` is not a member of the generated `RazorPage<T>` subclass. So it would be strange if it showed up and I would expect the setter wouldn't be available on an instance of the subclass.

> Can we change the property `ExpressionTextCache` in `RazorPageOfT.cs` to `protected`?

Frankly, ick, but what I want may be impossible here: Would be good to have the property activated like other `RazorPage<T>` properties. But at the same time, this isn't a property that should be visible to users -- it's infrastructure they don't need to know about.

One alternative would be to use the service locator pattern, as we've already done in the same method where `ExpressionTextCache` is used:
``` c#
    if (_provider == null)
    {
        _provider = Context.RequestServices.GetRequiredService<IModelMetadataProvider>();
    }
```

@rynowak what do you think? Separately do we need an `interface` that `ExpressionTextCache` implements?

**Comment by rynowak** [comment]
IMO it would be best if the cache were a detail of something else. Would `IHtmlGenerator` be appropriate?

Failing a good solution, service locating wouldn't be **awful** in this case, but it's not ideal either.

**Comment by dougbu** [comment]
> a detail of something else

Are you suggesting `IHtmlGenerator` would have an `ExpressionTextCache` property? If so, I like the idea in general but not w.r.t. the `IHtmlGenerator`. Would prefer if it were an `IHtmlHelper<TModel>` property since the implementation of that `interface` already needs the text cache. Also good `RazorPage<TModel>` has an `IHtmlHelper<TModel>` property already -- though that's automatically `@inject`ed today, meaning `RazorPage<TModel>` can't use it as-is.

Along similar lines, we could add `CreateModelExpression<TValue>` to `IHtmlHelper<TModel>` and gen calls using the `@inject`ed `Html` property

**Comment by mnltejaswini** [comment]
I see IHtmlHelper<TModel> has public facing methods like TextFor etc. @dougbu  Is it fine if we add CreateModelExpression<TValue> to it and is visible publicly?

**Comment by dougbu** [comment]
> Is it fine if ...

I was throwing out a few ideas. Suggest you experiment and decide which works best.

One warning: `RazorPage` and `RazorPage<TModel>` are not the only possible base classes for the C# generated from a `.cshtml` file. The current tag helper reliance on bits only available in these classes is a bug. Try not to make that bug worse here.

**Comment by mnltejaswini** [comment]
@dougbu  Can we have a provider for ModelExpression something like IModelExpressionProvider that has GetModelExpression. The implementation of the provider will contain the detail of ExpressionTextCache. This IModelExpressionProvider can be injected using InjectChunk in the Razor page
