### ISSUE TITLE
Modify rendering to utilize HelperResults

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#447]
Our HTML helpers will always return HtmlString with the variety that take a HelperResults will allow us to write directly to streams and never write to strings. and thus avoid LOH allocations (and consume less memory)

Conversation discussing the topic: https://github.com/aspnet/WebFx/pull/155#discussion_r11055448

**Comment by sornaks** [comment]
https://github.com/aspnet/Mvc/commit/b6a109e2a3f6fac94a3cbec0d16ea1adf526e1d8
