### ISSUE TITLE
Review use of Activator.CreateInstance

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4470]
We've made changes in a variety of places to avoid `Activator.CreateInstance` but we still have more of these (for example `DefaultRazorPageFactory`).

The issue is that `Activator.CreateInstances` uses a cache with a small number of slots. If we're activating user-code or razor page types, we'll quickly exhaust these slots.

**Comment by rynowak** [comment]
@mnltejaswini - the first task here is to look for usages try to understand which of them could run per-request, or involve user-code. Then we'll come up with a strategy for each one.

**Comment by mnltejaswini** [comment]
The following are the places where Activator.CreateInstance is used

| Location | Usage | Action |
|----------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|------------------------------------------------------------------|
| src\Microsoft.AspNetCore.Mvc.Core\Formatters\InputFormatter.cs(38) | return Activator.CreateInstance(modelType) | Needs to be investigated |
| src\Microsoft.AspNetCore.Mvc.Razor\Internal\DefaultRazorPageFactoryProvider.cs(85) | var page = (IRazorPage)Activator.CreateInstance(compiledType); | This will be fixed to use cached delegate |
| \src\Microsoft.AspNetCore.Mvc.Core\Internal\ControllerActionExecutor.cs(61): | Activator.CreateInstance(parameterInfo.ParameterType) | This is quite rare but will be investigated |
| src\Microsoft.AspNetCore.Mvc.Core\ModelBinding\Binders\*ModelBinderProvider.cs(29): | return (IModelBinder)Activator.CreateInstance(binderType, elementBinder); | This will execute once per app and will not be fixed |
| src\Microsoft.AspNetCore.Mvc.Core\ModelBinding\Binders\CollectionModelBinder.cs(150): | return Activator.CreateInstance(targetType); | Will be fixed to use cached delegate |
| src\Microsoft.AspNetCore.Mvc.Core\ModelBinding\Binders\ComplexTypeModelBinder.cs(348): | return Activator.CreateInstance(bindingContext.ModelType); | Will be fixed to use cached delegate |
| src\Microsoft.AspNetCore.Mvc.Core\ModelBinding\ModelBindingHelper.cs(884): | return (ICollection&lt;T&gt;)Activator.CreateInstance(modelType); | Needs to be investigated  |
| \src\Microsoft.AspNetCore.Mvc.Core\ModelBinding\ModelBindingHelper.cs(959): | return type.GetTypeInfo().IsValueType ? Activator.CreateInstance(type) : null; | This path execution doesn't get hit often and will not be fixed. |

**Comment by rynowak** [comment]
Thanks for the detailed notes - we should look at trying to get rid of the code in `ModelBindingHelper` - I'll log a separate issue for that.

**Comment by mnltejaswini** [comment]
@rynowak 

" Thanks for the detailed notes - we should look at trying to get rid of the code in  ModelBindingHelper  - I'll log a separate issue for that. "

If there is a bug for this item, we can close this bug as done.
