### ISSUE TITLE
MVC built-in support Markdown parser

### ISSUE THREAD

**Issue by mojtabakaviani** [aspnet/Mvc#4473]
Markdown is famous syntax for text editor in web and growth everyday. please add built-in support for parsing and TagHelper.

**Comment by benaadams** [comment]
http://commonmark.org/

**Comment by Eilon** [comment]
@mojtabakaviani I'm not sure what exactly you're asking for. A library for working with Markdown? If so, the link from @benaadams is likely what you want.

Other than that, there's no particular relationship between MVC and Markdown.

**Comment by JamesNK** [comment]
https://github.com/Knagis/CommonMark.NET

Add that to your project, wrap it in a tag helper and you're good to go. I'm sure at some point in the future someone will create a tag helper for it and put it on NuGet

**Comment by jasonwilliams200OK** [comment]
https://github.com/Knagis/CommonMark.NET/issues/82

**Comment by jasonwilliams200OK** [comment]
Here we go:

Package (by @dpaquette): https://www.nuget.org/packages/TagHelperSamples.Markdown

Blog: http://blog.decayingcode.com/post/creating-a-simple-aspnet-5-markdown-taghelper

Sample from https://github.com/dpaquette/TagHelperSamples/blob/master/TagHelperSamples/src/TagHelperSamples.Web/Views/Samples/MarkdownTagHelper.cshtml:

```html
<markdown>
A First Level Header
====================

A Second Level Header
---------------------

Now is the time for all good men to come to
the aid of their country. This is just a
regular paragraph.

The quick brown fox jumped over the lazy
dog's back.
### Header 3
> This is a blockquote.
>
> This is the second paragraph in the blockquote.
>
> ## This is an H2 in a blockquote
</markdown>
```

Remember to [import the tag helper](https://github.com/dpaquette/TagHelperSamples/blob/master/TagHelperSamples/src/TagHelperSamples.Web/Views/_ViewImports.cshtml) in `~/Views/_ViewImports.cshtml` first:

```cshtml
@addTagHelper "*, TagHelperSamples.Markdown"`
```

Thanks @knagis for pointing this out.

**Comment by dpaquette** [comment]
@jasonwilliams200OK thanks for linking to my project. Just a note that this is available as a NuGet package:

http://www.nuget.org/packages/TagHelperSamples.Markdown/

**Comment by mojtabakaviani** [comment]
I think but built-in parser is better.

**Comment by Eilon** [comment]
@mojtabakaviani why would it be built-in? There is nothing MVC-specific about Markdown, is there? MVC doesn't have its own imaging library, PDF formatter, or lots of other things, either. There are many great libraries out there that solve this problem.

**Comment by davidfowl** [comment]
This sounds like something that would be great in ASP.NET contrib https://github.com/aspnet-contrib

**Comment by Eilon** [comment]
BTW I still don't get what "built-in support for Markdown in MVC" even means. What would it do?

**Comment by mojtabakaviani** [comment]
Ok, maybe better that open this issue in Razor project.

**Comment by Eilon** [comment]
@mojtabakaviani if you log a new bug, please provide more details about what this feature would do, and how it would be different from just using an existing Markdown library. Thanks!
