### ISSUE TITLE
Validation TagHelper for properties doesn't work for self-closing tags

### ISSUE THREAD

**Issue by akamud** [aspnet/Mvc#4475]
I'm getting a weird behavior on validation taghelpers on `RC1-update1`. If you have an input with validation declared like this:

``` HTML
<div class="form-group">
    <label asp-for="UserName" class="col-md-2 control-label"></label>
    <div class="col-md-10">
        <input asp-for="UserName" class="form-control"/>
        <span asp-validation-for="UserName" class="text-danger" />
    </div>
</div>
```

And you are doing any kind of server-side property validation, either with Attributes or `ModelState.AddModelError("UserName", "Invalid")`, the field gets highlighted in red but the error doesn't show up when the page is returned.

![capturar](https://cloud.githubusercontent.com/assets/954102/14528759/7bd331e6-0227-11e6-9744-1da061d38eb5.PNG)

To address this, you must change the code above to:

``` HTML
<span asp-validation-for="UserName" class="text-danger"></span>
```

Then it will show up.

Is this by design? If so, is this specified somewhere?

Here's a repro sample: https://github.com/akamud/ValidationTagHelperSample

**Comment by dougbu** [comment]
This is expected. The MVC tag helpers do not change whether an element is self-closing or not. We've discussed changing the behaviour but everything we've come up with was both too magical and had too many surprising corner cases.

aspnet/Tooling#398 is about making the problem more obvious in the VS editor.

**Comment by akamud** [comment]
Maybe this should be added to the validation docs (I couldn't find it) so people know this is expected?

I could make a PR for that if you think this is valid.

**Comment by dougbu** [comment]
> validation docs (I couldn't find it)

The right place would be with the rest of the tag helper documentation. Nothing about this behaviour is specific to the validation tag helpers.

**Comment by akamud** [comment]
I understand that it is not specific, but it could cause confusion with some users.

How about add this to the Tag Helper docs **and** make just a note about this behavior on the Validation docs, linking to the tag helper docs?

**Comment by Eilon** [comment]
@danroth27 @DamianEdwards thoughts on how to resolve this type of confusion?

**Comment by danroth27** [comment]
I agree the current behavior is surprising. There's nothing that prevents a tag helper from changing the rendering style of a tag - it's just not something the built-in MVC tag helpers will do for you. There also really isn't a single place in the docs where we can let people know about this behavior (maybe the intro to tag helpers doc?). 

@DamianEdwards If we get this feedback a lot would we consider changing the behavior?

**Comment by tuespetre** [comment]
*(FWIW, `<span>` elements' closing tags are not omissible: https://www.w3.org/TR/html5/single-page.html#the-span-element)*

**Comment by dougbu** [comment]
@tuespetre if you want to write a tag helper than fixes the `.cshtml` author's HTML errors, there's nothing stopping you. However the MVC tag helpers doing that for the few elements they target would be worse.

**Comment by Eilon** [comment]
@DamianEdwards any thoughts on this? This would be a significant behavior change so it's now or never. I doubt we would change this after v1.

**Comment by DamianEdwards** [comment]
Something about the idea of auto-expanding these elements via the tag helpers leaves a bad taste in my mouth. Thinking...

**Comment by Eilon** [comment]
Ok not planning on doing anything here at this time. We'll revisit this behavior in the future and perhaps find a way to alert a developer that something odd is going on.

**Comment by akamud** [comment]
For now I believe just a note in the documentation would help programmers and decrease the number of issues raised around this.

**Comment by martingbrown** [comment]
There is a SO question regarding this http://stackoverflow.com/questions/39464226/asp-validation-for-tag-helper-is-not-working-for-server-side-validation-errors

**Comment by rynowak** [comment]
> Ok not planning on doing anything here at this time. We'll revisit this behavior in the future and perhaps find a way to alert a developer that something odd is going on.

I'm closing this in favor of https://github.com/aspnet/Razor/issues/433

The fix for this would come from Razor/VS and would probably be a warning in VS, warning on pre-compilation. This would make it pretty visible.
