### ISSUE TITLE
The configuration file 'Config.json' was not found and is not optional.

### ISSUE THREAD

**Issue by jcsotoo92** [aspnet/Mvc#4481]
i try to run my app and it shows this error:
Excepción no controlada: System.IO.FileNotFoundException: The configuration file 'Config.json' was not found and is not optional.

i declare my config.json as following:

public IConfiguration Configuration { get; set; }

        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder().AddJsonFile("Config.json");
            Configuration = builder.Build();
        }

**Comment by Eilon** [comment]
Is it running on Linux, where the file system is case-sensitive? Can you upload your project to GitHub?

**Comment by jcsotoo92** [comment]
im running it in windows

**Comment by kichalla** [comment]
@jcsotoo92 which version of MVC are you running? is it the latest out of dev?, if yes then you might need to set the base path ex: https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Startup.cs#L24

**Comment by jcsotoo92** [comment]
im using the latest, i put the base path and the problem continue

**Comment by kichalla** [comment]
Could you share a repro project?

**Comment by jcsotoo92** [comment]
https://github.com/jcsotoo92/ProjectGrole.git

**Comment by jcsotoo92** [comment]
[https://github.com/jcsotoo92/ProjectGrole.git](url)

**Comment by kichalla** [comment]
Thanks for the repro project. Looks like you need to update the `project.json` file to have the `"content"` node and have `Config.json` specified here.

Example: https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/project.json#L22

**Comment by jcsotoo92** [comment]
Thanks @kichalla !! it works

**Comment by re3el** [comment]
@kichalla @jcsotoo92 could you kindly check my similar problem [here](http://stackoverflow.com/questions/38660383/file-not-found-exception-visual-studio-2015/38660566?) I didn't quite understand when you asked to update` project.json` file to have `content `node with `config.json` specified there. It would be of great help if you post a snippet to solve my issue.

Thanks

**Comment by Vitali-Dettling** [comment]
In project.json include all files:

   "publishOptions": {
        "include": [
            "wwwroot",
            "web.config",
            "config.json"
        ]
    },
