### ISSUE TITLE
How sign in from a HttpClient?

### ISSUE THREAD

**Issue by endink** [aspnet/Mvc#4484]
When use CookieAuthentication for a webapi site, how to make HttpClient can be access a controller that the AuthorizeAttribute was applied?

If i use SignInManager.PasswordSignInAsync(user, password, false, false) in a api controller, i can get the http header in http response: 

> Set-Cookie: .AspNetCore.Identity.TwoFactorUserId=CfDJ8PgS8b7uVtlIjbndCTtQoWFF7WAixU-cKyg9SVvBycXohKy4YyN5WX35Q9lyLt9z8RL2yMdDoJ-APN2SQj8uFN1C0QpqxALIPBLyqljKZKBFOyOe6PmQbQfYecfGqCPJyewtaR4huH1nXBjKzsSW0Sk7pHIG3DgSAkYFwx-uy7TtZ8ET4W_U18OiaRnbiwQ6RPwI_Ad3v1lnp3bNKS6V_Ggg2yLXFb-QoqWfjI-rTd1VWsEk0s2rqWqU-cUOaganZ7s6uOZG2N1RWxxmumHNzARPdMfgvxdb_Z9TSeOyYyMHCG2atSBtllbzYYUhTSw_FG3ZYwnZ7SOuQQNA_MFrk-3C0rVVFqA3Bbg7zHoKriEY; path=/; httponly

and i put them to Httpclient,
```
request.Headers.TryAddWithoutValidation("Cookie", cookieHeader);
```

and request the action,  I still get 401 Unauthorized or redirect to Login url (from IdentityOptions).

What am I missing?

**Comment by endink** [comment]
BTW, how to disable redirect to LoginPath when use an AuthorizeAttribute?

**Comment by Eilon** [comment]
@Tratcher @HaoK @blowdart any ideas?

**Comment by blowdart** [comment]
Aside from don't use cookie auth? 

Given the cookie name above it looks like 2fa is enabled, so it's a bit of a non-starter, because that needs an interactive browser session

**Comment by Eilon** [comment]
I guess that pretty much answers it. Forms/cookies auth is meant for interactive clients. Use OAuth or OIDC for non-client access to APIs.
