### ISSUE TITLE
DefaultCollectionValidationStrategy .GetEnumeratorForElementType might produce unexpected IEnumerator

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Mvc#4489]
During #4436 it became evident that method `DefaultCollectionValidationStrategy .GetEnumeratorForElementType` is vulnerable to producing the wrong IEnumerator on types which implement multiple non-generic `GetEnumerator`.

> We might want to think more carefully about the issue that this code solves and see if there's a better way.

> This is for cases where a type implements multiple kinds of `IEnumerator<T>`. We've already decided what we think `T` is, but there can be problems calling the non-generic `GetEnumerator` because we don't know which enumerator it's going to return.... Maybe we want to no-op if the results don't match our expectations.... Calling non-generic `GetEnumerator` doesn't require any tricks or reflection or caches :laughing: 

> We hit this case with `JObject`.

We'll need to produce a test to verify how this situation can occur.

**Comment by rynowak** [comment]
No `GetEnumeratorForElementType` is the fix for this bug. This is the test https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.Core.Test/Internal/DefaultCollectionValidationStrategyTest.cs#L92

**Comment by Eilon** [comment]
So is there a bug here? The test that @rynowak pointed at seems to be this scenario. What else is there to be done?

**Comment by rynowak** [comment]
There's nothing else to do here - this was addressed before we shipped RC1.
