### ISSUE TITLE
Change `JsonOutputFormatter` to pool serializers

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4493]
The fix for #3550 updated the JSON input formatters but not `JsonOutputFormatter`. We should apply the same `JsonSerializerObjectPolicy` and so on. Haven't measured but expect a solid allocation improvement with a fix here.

**Comment by rynowak** [comment]
This was already done. You don't need a pool because the serializer is stateless for output.

**Comment by dougbu** [comment]
> You don't need a pool because the serializer is stateless for output.

I'm missing something. Why is it fine for the output formatter to always create a new serializer? (`JsonSerializerObjectPolicy` doesn't do anything to reset the serializer's state.)

**Comment by rynowak** [comment]
What you're missing is that it creates one instance of the serializer:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonOutputFormatter.cs#L131

**Comment by javiercn** [comment]
Yep, the reason why JsonInputFormatter pools serializer settings is because we attach to an event in the json serializer settings for catching errors during model binding. @rynowak

**Comment by dougbu** [comment]
Thx to @rynowak for setting me straight. No issue here because the serializer's lifetime is the same as the output formatter's.
