### ISSUE TITLE
Web page how to obtain a visitor IP

### ISSUE THREAD

**Issue by BruinY** [aspnet/Mvc#4494]
Web page how to obtain a visitor IP
in asp.net core rc1

**Comment by Muchiachio** [comment]
```C#
public IActionResult Index()
{
    return View(HttpContext.Connection.RemoteIpAddress);
}
```

**Comment by cwe1ss** [comment]
I think this does not work in RC1 if you use Kestrel as this was not yet implemented there. It is fixed in RC2.

**Comment by BruinY** [comment]
@Muchiachio rc1 not have this methods.

**Comment by BruinY** [comment]
@cwe1ss rc2 release time is ?????

**Comment by cwe1ss** [comment]
there is no release date yet. the weekly standups on https://live.asp.net are your best source for updates.

**Comment by BruinY** [comment]
release in 20 Apr, 2016 ?? Hope is really, RC1 there are too many defects, cannot bear to continue

**Comment by Muchiachio** [comment]
RC1 has this method, don't know if it works or not on remote, but it returns :::1 on local as I would expect.

**Comment by BruinY** [comment]
@Muchiachio  Can't works on remote

**Comment by Eilon** [comment]
@Tratcher any idea on this?

**Comment by Tratcher** [comment]
Wait for RC2, there were lots of issues with this on RC1.
https://github.com/aspnet/IISIntegration/issues/17

**Comment by Eilon** [comment]
@Tratcher so as far as we know this was fixed in RC2?

**Comment by Tratcher** [comment]
Yes

**Comment by Eilon** [comment]
Ok then that's the answer: this is fixed in RC2. You can get the latest RC2 nightly builds from here: https://www.myget.org/gallery/aspnetrelease

**Comment by wgutierrezr** [comment]
Hi
I'm still having HttpContext.Connection.RemoteIpAddress issues, it returns ::1

I'm using Asp.Net Core 1.1 MVC

Regards

**Comment by Tratcher** [comment]
@wgutierrezr please open a new issue in BasicMiddleware, I expect you're having an issue with the forwarded headers for the remote IP. Please share the request headers as received by the server.
