### ISSUE TITLE
When RC2 release???

### ISSUE THREAD

**Issue by BruinY** [aspnet/Mvc#4495]
Milestone of the repair order is almost finished processing, can clear when release RC2 now?Now RC1 in the project, the problem of too much, can no longer go on.RC2 has been delayed so long.Really can't stand it.Hope to have a clear the release of the time.

**Comment by mikes-gh** [comment]
https://github.com/aspnet/Home/wiki/Roadmap

**Comment by mvermef** [comment]
http://www.hanselman.com/blog/AnUpdateOnASPNETCore10RC2.aspx

**Comment by BruinY** [comment]
@mikes-gh roadmap is not definite

**Comment by Kurira** [comment]
It's not definite, because they are still deciding on the date (that's why TBD).
If you are developer you should know that estimating time is hard.

**Comment by BruinY** [comment]
The problem is already delayed for a long time.

**Comment by LeandroPT** [comment]
@BruinY 

I had same problem , however i was able to retarget the project to RC2 (currently RC1 in prodution RC2 waiting ready but waiting dead and cold).

I use Azure App service which is waiting on this: aspnet/IISIntegration#133

For what i see, much of the reengineering is done, alot has changed in my project.

I see alot of packages with weird build numbers, and alot of them with RC3 tag, i think they are targeting for late April (i think mid May) (many of the projects had their miletones updated to 29th of april).

My recomendation to you... Prepare for both and check your deployment.

**Comment by BruinY** [comment]
@LeandroPT 

Yes, RC2 relative RC1 change is too big, release and delay too long time, has a very big effect on my project, and even made me feel there is a big risk.I hope these days can release RC2, in order to have enough time to do adjustment.RC2 serious delay time is really too bad.Thought will be released in April before, and now have to wait for a worse time

**Comment by Eilon** [comment]
Hi all, we are focusing on just stabilizing the RC2 release at this time. The MyGet feed at https://www.myget.org/gallery/aspnetrelease has the latest stable bits for RC2.

As mentioned, we do not have a specific date for the RC2 release, but we are working as hard as possible to get it out.

**Comment by mikes-gh** [comment]
@Elion 
Whats the difference between aspnetrelease and aspnetcirelease?

**Comment by BruinY** [comment]
@Eilon 
RC2 development environment related information in where? to install something?

**Comment by Eilon** [comment]
@BruinY right now you can use Visual Studio Code if you want a good cross-platform IDE to use with project.json-based projects.

**Comment by BruinY** [comment]
Hope to hurry up to come out, had better be in 5 month ago
