### ISSUE TITLE
Gets 404 with [FromBody] IEnumerable<int>, but not with [FromBody] List<int>

### ISSUE THREAD

**Issue by paalmoest** [aspnet/Mvc#4496]
I am getting a 404 with the same route and same input, just different type

This results in a 404:
` [FromBody] IEnumerable<int> foo`

This does not:
`[FromBody] List<int> foo`

Setup:
docker image:  mono:4.2.3.4 
dnx version: 1.0.0-rc1-update1
running on Kestrel behind nginx 1.9.9

**Comment by dougbu** [comment]
Suggest trying your scenario with either Mono 4.0.5.1 (later versions don't get along w/ MVC action selection) or .NET Core.

**Comment by Eilon** [comment]
Actually, we recommend using .NET Core only, Mono is not a fully supported configuration.

**Comment by Eilon** [comment]
@dougbu do we know of any issues in this area, though? Or do you expect it to work?

**Comment by dougbu** [comment]
> Or do you expect it to work?

We know of issues w.r.t. action selection in every version after 4.0.5.x. Other dragons likely exist.

I do _not_ expect any Mono version except 4.0.5.x to work. But I'm not sure of the exact scenarios that will or won't behave correctly.

**Comment by Eilon** [comment]
@dougbu I assume we have a test for this scenario too?

**Comment by dougbu** [comment]
> we have a test for this scenario too?

We don't normally exhaustively test the underlying serializers.

In this case, no we don't have tests of opt-level collections that I could find. I wrote a few new `JsonInputFormatter` unit tests and didn't get any failures. Could add those or even extend the model binding integration tests to cover top-level collections. LMK

**Comment by Eilon** [comment]
@dougbu can you try this out on .NET Core and .NET Framework quickly just to see if anything stands out? But yeah it'd be good to add some tests for top-level collections w/ formatters - that's a fairly common scenario.

**Comment by dougbu** [comment]
Submitted #4500. Letting Travis test new scenarios w/ Mono 4.0.5.x.

**Comment by dougbu** [comment]
Self-assigning since I seem to be working on this :smiley_cat:

**Comment by dougbu** [comment]
Tests added in d9141d6
