### ISSUE TITLE
ModelBinderConfig does not exist in the new world

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#450]
The type's name seems like a misnomer but it essentially provides a way for the user to specify custom error strings during model binding (type conversion failed error messages) and validation (required field error messages).

| 175 | 10333 | Reported By: Pranav K |

**Comment by rynowak** [comment]
We have an updated design for this, and the remaining work is tracked in bugs with more information:
https://github.com/aspnet/Mvc/issues/3215
https://github.com/aspnet/Mvc/issues/2969
