### ISSUE TITLE
Model Binding goes into an infinite loop when the view model has a Func<>

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#4505]
This is my model:

```
    public class ContentFieldInfo
    {
        public string FieldTypeName { get; set; }

        [BindNever]
        public Func<ContentPartFieldDefinition, object> Factory { get; set; }
    }
```

It's part of a bigger view model, but this is what makes the app fails when it's added to the view model.
If a request tries to model bind it in an action, the process never ends and keeps increasing memory. A memory dump shows a _cycle_ in `DefaultMetadataDetails`. It doesn't even breaks in the action, the controller is instantiated though.

I will provide a sample. Just filing now with the information I have in case something obvious comes to mind.

**Comment by Eilon** [comment]
Any chance you want to take a crack at fixing it?

**Comment by sebastienros** [comment]
Can confirm I can repro with MvcSandbox by just adding a `Func` property in a view model.
