### ISSUE TITLE
Do we need Name and DisplayName on ActionDescriptor

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4506]
It's not clear what the difference is between these. I think we probably want to remove `Name` and add `ActionName` to `ControllerActionDescriptor` - the more specialized type

**Comment by Eilon** [comment]
No we don't need both on AD. We should rename `Name` to `ActionName` and move it to ControllerActionDescriptor. And DisplayName should stay as-is because it's just for debugging; it has no programmatic usage.

**Comment by Eilon** [comment]
3-Done? 😄

**Comment by javiercn** [comment]
Done done

**Comment by senritsu** [comment]
Now that `Name` is moved, how would i go about getting the action name inside an `IActionFilter`? The methods only get a parameter of type `ActionExecutingContext`. That in turn contains the `ActionDescriptor`, but no `ControllerActionDescriptor`. Do i just cast it?

**Comment by Asshiah** [comment]
I have the same issue as @senritsu as I am trying to migrate my project to RTM

**Comment by rynowak** [comment]
You can either use `RouteData.Values["action"]` which may vary on casing or cast it. Can you clue me in to what this is for?

If this is for logging, the framework already logs enter/exit, what can we fix in the framework to make this meet your needs?

**Comment by senritsu** [comment]
I *think* it is used for excluding a few actions from a global action filter. Why it does not use attributes or something to achieve that, i don't know. If casting works that is fine for now, the code will have to be refactored in any case to be not horrible.

**Comment by rynowak** [comment]
> I think it is used for excluding a few actions from a global action filter.

I'd suggest doing something like this to make *not horrible* as you put it :laughing:. This is a common pattern that we've used inside the framework, [example here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ValidateAntiforgeryTokenAuthorizationFilter.cs#L61)

```
public interface IFooConcernFilter
{
    // Just a marker
}

public class MyGlobalFooConcernFilter : IFooConcernFilter, IActionFilter
{
    public void OnActionExecuting(...)
    {
        if (!IsClosestFooConcernFilter(context)
        {
            return;
        }
    }

    private bool IsClosestFooConcernFilter(FilterContext context)
    {
            // Determine if this instance is the 'effective' foo concern policy.
            for (var i = filters.Count - 1; i >= 0; i--)
            {
                var filter = filters[i];
                if (filter is IAntiforgeryPolicy)
                {
                    return object.ReferenceEquals(this, filter);
                }
            }

            Debug.Fail("The current instance should be in the list of filters.");
            return false;
    }
}

public class IgnoreFooConcernAttribute : Attribute, IFooConcernFilter
{
    // Also just a marker
}
```

This gives `[IgnoreFooConcern]` overriding behavior. If you slap that on a controller or action, then the global filter knows to shut itself off.
