### ISSUE TITLE
Url.RouteUrl XML Documentation is incorrect.

### ISSUE THREAD

**Issue by brentarias** [aspnet/Mvc#4507]
For the `Url.RouteUrl` function, intellisense documentation says that it "Generates a fully qualified or absolute URL...".  

That is incorrect.  It generates a relative URL.  As is, there is already another function that provides an absolute URL, and that is `Url.Link(...)`

**Comment by Eilon** [comment]
Assigning to you because it's somewhat related to https://github.com/aspnet/Mvc/issues/4245.

**Comment by Eilon** [comment]
Moved.

**Comment by dougbu** [comment]
15f25d5
