### ISSUE TITLE
LisenceController is spellt wrong

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/Mvc#4520]
https://github.com/aspnet/Mvc/blob/dev/test/WebSites/ApplicationModelWebSite/Controllers/LisenceController.cs

Class is name `LicenseController` but file is named `LisenceController`.

**Comment by Eilon** [comment]
Ah oops looks like the filename is wrong, but everything else is right.

**Comment by stanislavromanov** [comment]
https://github.com/aspnet/Mvc/pull/4532

**Comment by Eilon** [comment]
@stanislavromanov thanks, I'll have @javiercn merge.
