### ISSUE TITLE
Remove MVC.DNX

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#4525]
It doesn't work anymore.

/cc @Eilon @DamianEdwards  RC2

**Comment by javiercn** [comment]
I had a PR out for it, ir you guys give the ok, I'll update it and merge it.

**Comment by davidfowl** [comment]
@javiercn where is it

**Comment by javiercn** [comment]
https://github.com/aspnet/Mvc/pull/4379

**Comment by Eilon** [comment]
Ok I give up, let's do this for RC2.

**Comment by javiercn** [comment]
Closing this one as it's a dupe of https://github.com/aspnet/mvc/issues/4187

**Comment by javiercn** [comment]
059ec0f3531cbbd04258c6ea5b4951ca27eecc92
