### ISSUE TITLE
Cannot restore packages

### ISSUE THREAD

**Issue by rumnha** [aspnet/Mvc#4526]
I'm getting error like below when I try to restore packages or during the build - 
"netcoreapp1.0" is an unsupported framework
How do I get netcoreapp1.0 installed? 

My Enviroment:
VS 2015 Update 2 on Windows 8

dotnet --info

```

.NET Command Line Tools (1.0.0-rc2-002476)

Product Information:
 Version:     1.0.0-rc2-002476
 Commit Sha:  1a8d393b9b

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.2.9200
 OS Platform: Windows
 RID:         win8-x64
```

Update:
This - https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/244 - says, VS does not have tooling available yet for it. Right?

**Comment by BrennanConroy** [comment]
Run dotnet restore from the command line

**Comment by rumnha** [comment]
@BrennanConroy, yep, did that as well. Restore is failing with 4014 errors :(

**Comment by Eilon** [comment]
@rumnha can you show your `project.json` file and the exact errors you're getting? Unfortunately there isn't enough information here to investigate the issue.

For now you do have to do restore/build from the command line. DNX no longer works with the latest packages, which means that VS support is limited. You can, however, use Visual Studio Code (which works on Windows, Mac, and Linux).
