### ISSUE TITLE
Avoid holding on to DependencyContext instances

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#4527]
They are pretty memory heavy and we should avoid keeping them around. Based on https://github.com/aspnet/Mvc/pull/4522#discussion_r60835905

**Comment by Eilon** [comment]
Please run this through a profiler first to see what the gains are, and to verify that the fix correctly releases the memory.

**Comment by rynowak** [comment]
Some prior art here: https://github.com/aspnet/Mvc/issues/4335

Note that the size of dependency context is going to scale with the number of dependencies your app has.

**Comment by Eilon** [comment]
Done?
