### ISSUE TITLE
how to use ssl with iisplatformhandler for aspnet core (rc2) ?

### ISSUE THREAD

**Issue by endink** [aspnet/Mvc#4528]
is there a document or sample application for this (rc2 version : 1.0.0-rc2-20100)?

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by Eilon** [comment]
@endink what have you tried? Did something not work? BTW IIS Platform Handler has been replaced with the new AspNetCoreModule, see https://github.com/aspnet/Announcements/issues/164.

**Comment by endink** [comment]
@Eilon  I tried use client x509certificate, but always get http 403.7 error, can u determine client certificate was supported or not for version 1.0.0-rc2-20100?

**Comment by Eilon** [comment]
@blowdart you are being invoked.

**Comment by blowdart** [comment]
*a plume of smoke appears*

I believe you need the new core module for this and the IIS integration stuff turned on, but @Tratcher would know best.

**Comment by Tratcher** [comment]
@endink it sounds like you're trying to use an invalid client certificate. The 403.7 is coming from IIS, not Asp.Net. Do you have IIS configured to 'accept' or 'require' client certs?

Unrelated, but 1.0.0-rc2-20100 is a very old version. We're up to 20682 now. Set your dependencies to 1.0.0-rc2-* and see what you get.

**Comment by endink** [comment]
@Tratcher OK, thanks, i will check my code , We decided to stay in this version 20100 until the VS CLI tooling released.
