### ISSUE TITLE
Bug in Custom Validation

### ISSUE THREAD

**Issue by markusvt** [aspnet/Mvc#4529]
I found the following problem:
I have the following class 
```
class Booking {
  DateTime Start {get;set;}
  DateTime End {get;set;}
  CustomBehaviour Behaviour {get;set;}
}
```
The CustomBehaviour Class looks like the following:
```
public class CustomBehaviour {
  public Booking booking;
  public CustomBehaviour(Booking b){
    this.booking = b;
  } 

  DateTime Start {
    get { return booking.Start; }
    set { booking.Start = value;}
  }
  ...
}
```

So essentially the `CustomBehaviour` also has those `Start` and `End` DateTimes. I use a PartialView with the `CustomBehaviour` as model to update these Data. 
Then I added a Custom ValidationAttribute to the Booking "Start" Property to ensure that Start is always before End.

Now I ran into the following problem: when I generate a new Booking, everything works fine. But I have some old data which are incorrect (Start is after End). If I try to save it, I get the Validation Error 2 times: one for the "Booking.Start" itself, and the other for "CustomBehaviour.Booking.Start". And when I enter correct data, there is always 1 ErrorMessage displayed (the Booking.Start one).

Could it be, that the Annotation or Validation has a problem to see that "Booking" and "CustomBehaviour.Booking" are the same object in this case?

**Comment by dougbu** [comment]
Please provide your exact model, including the applied validation attribute(s). May also help to see the exact content of the `ModelState` (the keys and associated error messages) when the error message is displayed twice. And where, exactly, is the error message displayed twice?

**Comment by Lidingxiang** [comment]
# ddd**dddd**
