### ISSUE TITLE
Unit tests for HtmlHelper

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#453]
Have added quick confirmations to views in MVC Sample.  Need to add real unit tests, preferably copying over the bulk of HtmlHelper / extensions tests from legacy MVC.  Skip the NRE checks :)

| 170 | 10328 | Reported By: Doug Bunting (AAPT) |

**Comment by yishaigalatzer** [comment]
The idea is to complete porting over the HtmlHelper tests and see if we come up with any new bugs. The code doesn't have to be comitted into the Beta3 branch but the work has to happen before we are shipping Beta3 to find any issues we might have missed.

**Comment by dougbu** [comment]
@pranavkm has greatly improved the coverage of many HTML helpers.  some remaining gaps:
- functional tests of HTML helpers (not exactly matching the bug title but also not covered elsewhere)
- `@Html.DropDownList()` / `@Html.ListBox()`
- `@Html.RadioButton()`
- `@Html.Raw()`
- `@Html.TextArea()`
- `@Html.TextBox()` (yup, no kidding)
- `@Html.ValidationMessage()` / `@Html.ValidationSummary()`

a few other methods are exposed publicly but used in other helpers (and therefore tested indirectly, or will be):
- `@Html.Encode()`
- `@Html.FormatValue()`
- `@Html.GenerateIdFromName()`
- `@Html.GetClientValidationRules()`
- `@Html.GetFormMethodString()`

**Comment by dougbu** [comment]
Crossed out a couple of items in earlier comments.

Some details on remaining `DropDownList` and `ListBox` test gaps.  Test do not currently:
- use non-`null` `optionLabel` and `htmlAttributes` arguments
- confirm value sources and their priorities
- mock an `IHtmlGenerator` and confirm how it is called
- mock an `IHtmlHelper` and confirm how extension methods call that

**Comment by ajaybhargavb** [comment]
Crossed out some items from previous comment. Following are the remaining items.
- `@Html.Raw()`
- Indexers and deeply nested lambdas for the various `*For` e.g `InputFor`, `DisplayFor` etc
- Scenarios gap compared to 5.2
- a few other methods are exposed publicly but used in other helpers (and therefore tested indirectly, or will be). Need to write a few tests to cover usage that isn't already handled indirectly.:
 - `@Html.Encode()`
 - `@Html.FormatValue()`
 - `@Html.GenerateIdFromName()`
 - `@Html.GetClientValidationRules()`
 - `@Html.GetFormMethodString()`
- Some details on remaining `DropDownList` and `ListBox` test gaps.  Test do not currently:
 - use non-`null` `optionLabel` and `htmlAttributes` arguments
 - confirm value sources and their priorities
 - ~~mock an `IHtmlGenerator` and confirm how it is called~~ (@dougbu, I think we decided not to do this and the below item. Could you confirm?)
 - ~~mock an `IHtmlHelper` and confirm how extension methods call that~~

From @dougbu's PR comments:
>"confirm value sources and their priorities" is important in general and a big part of "Scenarios gap compared to 5.2". Other than expression vs. explicit values, that isn't covered in any of the new test classes. Need to show `ModelStateDictionary` values, `ViewDataDictionary` values, and their precedence. (Or, in the case of, `Password[For]()` those values being ignored.) Have a look at tests like `HiddenUsesValuesFromModelState_OverExplicitSpecifiedValueAndPropertyValue()` in `HtmlHelperHiddenTest`.

>`htmlAttributes` is another "value source". Not sure even the existing test classes cover including `checked`, `id`, `name`, `type` or `value` properties in the `htmlAttributes` object.
FYI the generated HTML might override a `name` and `value` (when the `value` argument is non-`null`) but `htmlAttributes` should "win" in general.

>`HtmlHelperValidationMessageExtensionsTest` covers all extension methods but only when the property is valid and client-side validation is enabled. Need to confirm what happens for all combinations of those two characteristics e.g. invalid properties cause a <span> to be generated even if client-side validation is disabled.

@dougbu, please add if I missed something.

**Comment by dougbu** [comment]
>  - ~~mock an `IHtmlGenerator` and confirm how it is called~~ (@dougbu, I think we decided not to do this and the below item. Could you confirm?)
 - ~~mock an `IHtmlHelper` and confirm how extension methods call that~~

Agreed.

**Comment by dougbu** [comment]
> please add if I missed something.

Nothing I can think of at the moment. Going the other way, I crossed out a few more bullets in earlier comments.

**Comment by ajaybhargavb** [comment]
726ebb7a053c405c0c12abfb7cbf3c8549eeade9

**Comment by ajaybhargavb** [comment]
5238a8f16ec03965465ff0db0caeae957cebc3e8

**Comment by Eilon** [comment]
Moving to 1.0.0.

**Comment by pranavkm** [comment]
:fireworks:
