### ISSUE TITLE
How to remove X-Frame-Options: SAMEORIGIN from response header in RC1

### ISSUE THREAD

**Issue by michaelvolz** [aspnet/Mvc#4530]
I need to embed my Asp.Net 5 RC1 webapp into an iframe. I tried via Middleware to remove the "X-Frame-Options" header, but that did not work for MVC views.

I do not add or configure a separate Antiforgery package.

Is there a recommended way to remove this header? I am really stuck without it.

**Comment by michaelvolz** [comment]
Not adding the package was my error. This did the trick.

            services.AddAntiforgery();
            services.ConfigureAntiforgery(options =>
            {
                options.SuppressXFrameOptionsHeader = true;
            });

Ticket can be closed.

**Comment by Eilon** [comment]
Ah, ok, closing this out!
