### ISSUE TITLE
Create a filter/sample that shows how to configure form size limits

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4535]
We want an example of a filter that shows how to configure the limits used to read the form (by replacing `FormFeature`). This should be an `IAuthorizationFilter` configured to run before antiforgery.

See aspnet/Mvc#4533 for more information

**Comment by kichalla** [comment]
86147eda46a476b8acc409df0eaa9b0eca730e94

**Comment by M-Curtis** [comment]
Has this sample been published anywhere??

**Comment by pranavkm** [comment]
@M-Curtis it's located here - https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Controllers/RequestFormLimitsController.cs
