### ISSUE TITLE
Dependency issue when referencing another project in the solution NU1007

### ISSUE THREAD

**Issue by connde** [aspnet/Mvc#4541]
Hello, any ideas why I'm getting this warning on my Asp.Net project after referencing another project I have?

![image](https://cloud.githubusercontent.com/assets/1514559/14853665/d5f4995e-0c62-11e6-8bc3-610e5ab30d56.png)

**Comment by Eilon** [comment]
Can you show your `project.json` file?

**Comment by connde** [comment]
The project reference where the issue occurs is on is XXX.YYY.BusinessLayer": "1.0.0-* and its dependencies

{
  "userSecretsId": "aspnet5-Upm.BioForest.WebApi-20160420113805",
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.ApplicationInsights.AspNet": "1.0.0-rc1",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx461": {
      "dependencies": {
        "XXX.YYY.BusinessLayer": "1.0.0-*"
      }
    },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}

**Comment by Eilon** [comment]
Can you share the `project.json` from `XXX.YYY.BusinessLayer`? This file looks fine to me so far...

**Comment by connde** [comment]
BusinesssLayer is a .Net 4.6.1 class library, can this be the problem?

**Comment by connde** [comment]
Package.config
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Autofac" version="3.5.2" targetFramework="net461" />
  <package id="NLog" version="4.3.2" targetFramework="net461" />
</packages>

**Comment by Eilon** [comment]
@pranavkm can you take a look?

**Comment by Eilon** [comment]
@anurse @pakrym @davidfowl do any of you guys have an idea on this? (Note that this was with RC1.)

**Comment by davidfowl** [comment]
Are any csproj files in the picture?

**Comment by pranavkm** [comment]
Do you have a lock file you could share?

**Comment by pranavkm** [comment]
@connde - bump

**Comment by Eilon** [comment]
BTW I set up a quick mtg for Monday to discuss this.

**Comment by connde** [comment]
Hello, sorry for the delay, We migrated to RC2 and this was fixed, apparently..
