### ISSUE TITLE
Tag Helper asp-for generating bad name attribute for a model's class

### ISSUE THREAD

**Issue by Nucs** [aspnet/Mvc#4544]
Consider the following class:
```
class Model {
	public SubModel Sub {get;set;}
}

class SubModel {
	public string Field {get;set;}
}
```

Now when generating HTML Form via Tag Helper like this:
`<input asp-for="Sub.Field"/>`
It generates
`<input type="text" id="Sub_Field" name="Sub.Field">`

The issue comes with the name attribute, where you cannot do the following:
```
[HttpPost]
public IActionResult FormSubmittedAction(string Sub.Field) {
		...
}
```

The fix is obvious - replace the dot in the name attribute into a underscore and then the following is possible (And tested after a manual rename):
```
[HttpPost]
public IActionResult FormSubmittedAction(string Sub_Field) {
		...
}
```

**Comment by Nucs** [comment]
Quick js temporary fix
```
$('input[name*="."]').each(function() {
    $(this).attr('name', $(this).attr('name').replace('.', '_'));
});
```

**Comment by dougbu** [comment]
Better fix:
``` c#
public IActionResult FormSubmittedAction([Bind(Prefix = "Sub.Field")] string field) {...}
public IActionResult FormSubmittedAction([FromForm(Name = "Sub.Field")] string field) {...}
public IActionResult FormSubmittedAction([FromQuery(Name = "Sub.Field")] string field) {...}
```
et cetera

**Comment by Eilon** [comment]
The fix I would suggest is to change the action method to bind a `Model` type, which has the `Sub` property on it:

```c#
[HttpPost]
public IActionResult FormSubmittedAction(Model m) {
        ...
}
```

And then the default model binder will dive into `Model m` and see that there's a sub-property `Sub` on it, with a sub-sub-property `Field` on it and assign the value.

Or any of the other suggestions here would all work as well.
