### ISSUE TITLE
Add an Option to set the Razor view location formats

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#4550]
To customize the set of path formats that the Razor view engine will look at you need to customize the view engine itself. You need to either derive from RazorViewEngine, override the list of formats, and add that to the list of view engines, or you have to instantiate RazorViewEngine itself, set the list of formats, and add that to the list of view engines.

This is the property in question: https://github.com/aspnet/Mvc/blob/af58c2e6b619697a1a57736e9e996bb4d7e6e7ee/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngine.cs#L76
(Plus the one for areas.)

We already have a Razor View Options class (https://github.com/aspnet/Mvc/blob/af58c2e6b619697a1a57736e9e996bb4d7e6e7ee/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngineOptions.cs) so we should have the default list of view location formats there instead.

**Comment by Eilon** [comment]
@rynowak for your FYI information this is the bug we talked about.

**Comment by dougbu** [comment]
@pranavkm didn't you remove `ViewLocationFormats` settability an age (just one age, not ages :smiley_cat:) ago? What was the reasoning then?

**Comment by nmtoan07** [comment]
How can i add my custom view engine to framework?
Example: MyCustomRazorViewEngine : RazorViewEngine

services.AddMvc().AddViewOptions(options =>
            {
                options.ViewEngines.Clear();
                options.ViewEngines.Add(???????????);
            });

**Comment by kichalla** [comment]
You would need to do `services.AddSingleton<IRazorViewEngine, MyCustomRazorViewEngine>(); ` as the base type `RazorViewEngine` depends on some services from DI.

@pranavkm can you give more details regarding the options here?

**Comment by nmtoan07** [comment]
@kichalla Many thanks for your quick reply.
I tried your way before but it still error

services.AddMvc();
services.AddSingleton<IRazorViewEngine, MyRazorViewEngine>();

Error detail:

> InvalidOperationException: The view '~/myfolder/myfile.cshtml' was not found. The following locations were searched: ~/myfolder/myfile.cshtml
> 
> Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
> 
> Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()

Note: The reason i want to try to extend RazorViewEngine because of AngularJS, i use another folder for structure the project. (Not Views folder anymore, replaced by app/views/....).
