### ISSUE TITLE
TagHelper: How to use a form model that is not the same as the view model

### ISSUE THREAD

**Issue by audacity76** [aspnet/Mvc#4551]
I use a view model to transport my data from the controller to the view. Inside the view I have a html form which posts data to a controller action. The post action model is different to my view model. How can I achieve that the TagHelper react to another model?

For HtmlHelper I can create a separate instance of type HtmlHelper<PostModel> and use this with razor syntax. But TagHelpers work with a ModelExpression that automatically binds to the view model.

**Comment by dougbu** [comment]
@audacity76 one approach would be to make your form model a property of the view model. Then post back only that important part of the view model.

Another approach would be to create a variable named `model` that references your form model. Then use `model` in the tag helpers e.g. `<input asp-for="@model.Name" />` would bind a `ModelExpression` with the `Name` "Name".

**Comment by audacity76** [comment]
@dougbu thanks, both approaches are working great. It's worth mentioning that these strategies are leaving a prefix (the view model property name or the variable name) in the html name (and id) fields. Therefore the parameter in the post action needs to be the same as the prefix otherwise the model binder doesn't work.
