### ISSUE TITLE
Keep routdata in generate urls to different controller (using anchor tag helper)

### ISSUE THREAD

**Issue by gdelaossat** [aspnet/Mvc#4552]
Hello!

At the **startup.cs** file, I have changed the default MapRoute

 ```
routes.MapRoute(
                name: "default",
                template: "{controller=home}/{company=-1}/{action=index}/{id?}");

```
It works properly when you create url links  (using the anchor tagHelper) from the same controller which you are visiting.

But I'm losing the Company value, when I create a link to another controller:
`<a asp-action="index" asp-controller="AnotherController" >TEST</a>`

For example if I'm visiting http://localhost/testcontroller/22     (Company=22)
The generated URL to another controllers is http://localhost/AnotherController
The generated URL to the same controllers is correct: http://localhost/testcontroller/22/otherAction

What are the correct way to perform this?

Thanks!

**Comment by dougbu** [comment]
You'll need to explicitly pass the `company` value when referring to another controller e.g.
``` html
<a asp-action="index" asp-controller="AnotherController" asp-route-company="@Model.Company">TEST</a>
```
and use a view model that includes the correct `company` value (bound from the route data).

The important thing is that link generation does not use the ambient values (e.g. `company` in this case) when going someplace else.

**Comment by gdelaossat** [comment]
Dougbu, thanks for your help. I used the current routedata to pass the company value.
