### ISSUE TITLE
Assemblies with a transitive dependency to  MVC are not included as part of the list of discovered assemblies

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#4555]
When an application in Assembly A references an Assembly B which in turn references an Assembly C that contains a reference to MVC, we won't include B as part of the list of discovered assemblies. For example:

MusicStore.dll references MusicStore.Data which references MusicStore.Models which in turn references Mvc, but MusicStore.Data doesn't get included in the list of discovered assemblies.

The issue is that RuntimeLibrary.Dependencies only lists direct dependencies and the filtering method that we have only looks on the list of dependencies for a reference to any of the reference MVC assemblies.

```C#
private static bool IsCandidateLibrary(RuntimeLibrary library)
{
    Debug.Assert(ReferenceAssemblies != null);
    return !ReferenceAssemblies.Contains(library.Name) &&
        library.Dependencies.Any(dependency => ReferenceAssemblies.Contains(dependency.Name));
}
```

project.json for MusicStore.Models
```
{
  "version": "1.0.0",
  "dependencies": {
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.0.0-*",
    "Microsoft.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0-*",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
    "NETStandard.Library": "1.5.0-rc2-24018"
}
```

Debug session ilustrating the failing condition

![image](https://cloud.githubusercontent.com/assets/6995051/14896157/393aaf34-0d31-11e6-8a32-9f0b195fb607.png)

**Comment by Eilon** [comment]
Remember to consider the perf of this at startup time.

**Comment by Eilon** [comment]
And need to discuss with @rynowak to see if there were any especially compelling reasons why we didn't always do this.

**Comment by rynowak** [comment]
> And need to discuss with @rynowak to see if there were any especially compelling reasons why we didn't always do this.

This is a bug. Transitive references were always supposed to be considered

**Comment by Eilon** [comment]
@rynowak I'm quite glad to hear that 😄

**Comment by Eilon** [comment]
We were wondering if perhaps it was for perf reasons or similar but it seems like even if that was a theoretical concern, no one ever measured it both ways, and that no matter what, it could presumably done very performantly anyway.

**Comment by Eilon** [comment]
@javiercn please test the scenario at https://github.com/aspnet/Mvc/issues/4674 as well when working on the fix (manually at least, but automate if possible).
