### ISSUE TITLE
Using Antiforgery In jQuery and Angular Puts

### ISSUE THREAD

**Issue by markolbert** [aspnet/Mvc#4559]
I'm used to the pre-MVC6 setup for antiforgery, which involved including the client-side antiforgery token in the header of jQuery and angular puts. Those puts were then validated through a custom attribute, which compared the value in the antiforgery cookie to the value submitted via the headers.

I've been able to duplicate most of that under MVC6, except that I can't seem to find the name of the cookie holding the antiforgery token. I can see the token in the list of cookies -- the value is pretty unique :) -- but it's name is gibberish.

Pre MVC6 there was a property -- I forget the name -- which held, among other things, that cookie's name. I haven't been able to find it under MVC6. Is it available? Or is there some other way to identify the antiforgery cookie?
- Mark

**Comment by dougbu** [comment]
The cookie name is intended to be unique to the application. It's calculated using a cryptographic hash to keep that aspect of your application buried.

Use `AntiforgeryOptions.CookieName` to read the value. E.g. in your `Startup.ConfigureServices(IServiceCollection services)` method:
``` c#
string cookieName = null;
services.AddAntiforgery(options => cookieName = options.CookieName);
```

**Comment by markolbert** [comment]
Thanx. I tried exactly what you suggested before posting here, but it turns out there's a recently identified bug in VS2015 Update 2 -- and an even more recent patch -- which prevents you from accessing local variables in the debugger under certain situations. That lead me to believe the code construct was failing for some obscure reason.

The patch is available from Microsoft at http://go.microsoft.com/fwlink/?LinkID=785969&clcid=0x409. The discussion of the problem is at https://connect.microsoft.com/VisualStudio/feedback/details/1038150/visual-studio-2015-debugger-doesnt-recognize-a-variable.

BTW, it doesn't really matter, but burying the name of the cookie, and even giving it a cryptographic hash name, strikes me as a little odd. One could authenticate by simply checking the antiforgery form token against every cookie in the request until a match was found. The odds on matching the correct cookie's 128 (or longer?) character string at random is essentially zero.

- Mark

**Comment by dougbu** [comment]
Antiforgery helps prevent cross-site request forgery, primarily a concern after authentication. The cookie name doesn't need to be buried but does need to be unique without exposing internal information about the application.

@blowdart probably has better words.

**Comment by blowdart** [comment]
You shouldn't need to do any of this manually.

    services.AddAntiforgery(options => options.HeaderName = "X-XSRF-TOKEN");

This will look for, and automatically compare the value in that header against the cookie value.

https://github.com/aspnet/Antiforgery/blob/dev/samples/AntiforgerySample/Startup.cs has an angular sample.

**Comment by markolbert** [comment]
I've been trying to work through what looks like the same example (http://www.fiyazhasan.me/angularjs-anti-forgery-with-asp-net-core/), but am having some difficulty.

What I'm trying to do is have put/post/delete requests coming from angular get routed to a specific controller, ApiController. I have this in startup.Configure():

```
            app.Use( next => context =>
            {
                if( context.Request.Path.Value.ToLower().StartsWith( "/api/" ) )
                {
                    var tokens = antiForgery.GetAndStoreTokens( context );
                    context.Response.Cookies.Append( "XSRF-TOKEN", tokens.FormToken, new CookieOptions() { HttpOnly = false } );
                }

                return next( context );
            } );

            app.Map( "/api", a => a.Run( async context =>
            {
                switch( context.Request.Method.ToLower() )
                {
                    case "get":
                        break;

                    case "post":
                    case "put":
                    case "delete":
                        await antiForgery.ValidateRequestAsync( context );
                        break;
                }
            } ) );
```

On the client side, I have this:

```
    app.controller( '@ViewBag.AngularController', function ( $scope, $http ) {
        $scope.deleteSite = function ( siteID ) {
            if ( !confirm( "Are you sure?" ) ) return;

            var postHeaders = {
                'Content-Type': 'application/json; charset=utf-8',
            };

            $http.post( '/api/DeleteDataset', JSON.stringify( {'siteID': siteID} ), {
                headers: postHeaders,
            } )
            .then(
                function ( resp ) {
                    var a = 1;
                },
                function ( resp ) {
                    var b = 1;
                }
            );
        };
    } );

```

If everything worked, this should result in the following method in ApiController getting called:

```
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteDataset( int siteID )
        {
            Site site = _context.Sites.SingleOrDefault( s => s.ID == siteID );
            if( site != null )
            {
                _context.Sites.Remove( site );
                _context.SaveChanges();
            }

            return RedirectToAction( nameof( DatasetController.ChooseDataset ), "DatasetController" );
        }

```

But DeleteDataset never gets called. I can see the app.Map call get executed, followed by return next(context) in the app.Use code block. But I presume the validation fails, because DeleteDataset doesn't get called.

**Comment by markolbert** [comment]
Forgot to mention that immediately after the call to app.Map in startup I have this:

```
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

```

**Comment by rynowak** [comment]
There are a few things I can help with based on the sample code you provided...


` app.Map( "/api", a => a.Run( async context => ...);`

The sample code you provided for this middleware doesn't call `next` so it terminates the request pipeline after validating the token.

==============

In general though your second middleware (validating the token) isn't needed if you're using MVC. `[ValidateAntiForgeryToken]` will also do this.

Think of it this way - generally middleware applies to a pipeline or a prefix (using `Map`). Filter attributes (like `[ValidateAntiForgeryToken]`) apply to an action or set of actions. We often provide both ways of applying policies like antiforgery or CORS that you can choose based on your needs. You don't need both, they do the same thing.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
