### ISSUE TITLE
anchor tag helper does not support multiple parameters with the same name

### ISSUE THREAD

**Issue by ScorchedHands** [aspnet/Mvc#4560]
I have an action that looks like:
```
[HttpGet("/search")]
IActionResult Search(Status[] stat)
```
Where "Status" is an enum, which doesn't really matter for this issue but I thought I'd mention just in case.

I have a form that submits to the action using a multiple select list box for the "stat" parameter.  This works as intended, generating a url that looks like:

/search?stat=New&stat=Closed&stat=InProgress

The url is parsed properly and everything works.

Now my problem is that I want to make an anchor tag that utilizes that same action but the asp-route-\* tag helper will not allow me to pass multiple values.  I've tried the following:

`<a asp-action="Search" asp-controller="Something" asp-route-stat="InProgress" asp-route-stat="New" asp-route-stat="Closed">`

This only uses the last value for asp-route-stat and gives me "/search?stat=Closed".

`<a asp-action="Search" asp-controller="Something" asp-route-stat="@(new[] { "InProgress", "New", "Closed" })">`

This gives me a url that looks like "/search?stat=System.String%5B%5D"

Is what I am trying to do even possible right now?  I'm going to look into inheriting from the existing tag helper, but I feel like this should be something that the framework supports out of the box.

**Comment by ScorchedHands** [comment]
I forgot to mention, I've also tried using the enum directly as well in the array:

`<a asp-action="Search" asp-controller="Something" asp-route-stat="@(new[] { Status.InProgress, Status.New, Status.Closed })">`

This gives me a url that looks like "/search?stat=Status%5B%5D"

**Comment by NTaylorMullen** [comment]
When a TagHelper encounters a duplicate attribute same name that's bound it treats all other duplicate attributes as "unbound" (will flow to the output as is). The reason this happens is because currently TagHelpers have no way to represent attributes with duplicate names. We have special casing for dictionaries but even then dictionaries only support single key to single value entries.

To properly support what you're asking for would involve adding support for a specific type of list like value where attributes with same name would result in `list.Add`.

So, for work arounds. You could scavenge your remaining asp-route-stat values from `output.Attributes`, this way you'd build a list and send it on its way. Another alternative would be for what you've already tried, passing in a list directly. Sadly, I'm not aware of how one passes an enumeration of route information which then generates an appropriate link; i'm going to hand that specific question off to @rynowak or @dougbu

**Comment by Eilon** [comment]
We added a feature a short while back where you can provide an `IEnumerable<>` to routing and it will generate `key=value1&key=value2&key=value3&...` for it.

Here's a unit test from the PR that added it: https://github.com/aspnet/Routing/pull/269/files#diff-c319fbfa8af0228ab225d5742f8c19ffR640

So while you can't use tag helpers to specify the key multiple times, you can instead specify something like a `List<string>` and that should work.

**Comment by dougbu** [comment]
@Eilon yes but...

The `<a>` and `<form>` tag helpers handle route values using `IDictionary<string, string>` dictionaries. We discussed this w/ @rynowak ages ago and his sentiment was that non-`string` values are just `ToString`ed anyhow. In addition a `IDictionary<string, object>` dictionary wouldn't give users worthwhile IntelliSense for the common case.

If we wanted to support the `IEnumerable<>` feature, probably best to limit it to `IEnumerable<string>`. We'd need to change these properties to `IEnumerable<KeyValuePair<string, string>>`, add a custom backing store that consolidates repeated keys into an `IEnumerable<string>`, and support such properties in Razor.

**Comment by Eilon** [comment]
Oh yeah I forgot we have that restriction in our tag helpers.

This sounds far more complicated now - not just some simple fix.

Another outside-the-box idea (that I don't especially like) is:

```html
 <a asp-action="Search" asp-controller="Something"
    asp-routecollection-stat="new[] { "InProgress", "New", "Closed" }"> 
```

In other words, we'd have a new `asp-routecollection-*` tag attribute that accepts `IEnumerable<string>` values and passes those through to routing.

**Comment by Eilon** [comment]
Putting in Backlog as this is a new feature.

**Comment by tysonnero** [comment]
Hi - Any update on this or existing workaround?

**Comment by Eilon** [comment]
@tysonnero still no plans to make changes here.

Do you have thoughts on what this feature would look like? We have to be cautious regarding breaking changes, which is what makes improvements here potentially a bit tricky.

**Comment by tysonnero** [comment]
@Eilon I know with `@Url.Action`, you can pass and `object values` parameter, right? I know it supports collections such as saying `new { items = Model.SomeCollection }`. I'm don't think asp-route-data-all supports an object argument, and if it doesn't could we have another tag helper that does?

**Comment by rynowak** [comment]
> still no plans to make changes here

If we have no plans to change this should we just close it then? /cc @Eilon
