### ISSUE TITLE
Model Binder: invalid value in property makes model null

### ISSUE THREAD

**Issue by mdmoura** [aspnet/Mvc#4564]
I have the following ASP.NET Core controller action:

    public async Task<IActionResult> Post([FromBody]Model model) { }

The Model is the following:

    public class Model {
      public String Name { get; set; }
      public Int32? Age { get; set; }
    }

I the post the following model to the API:

    model = { name: "John", age: "Ab" }

On my controller the model becomes null. If I pass an int as age then it works fine:

    model = { name: "John", age: 30 }

If a property has an invalid type should not the model get the default value for that property?

Instead of just setting the entire model to null?

**Comment by m4nd1cm4rk0** [comment]
This is all about Angular.js, Angular raises an "invalid field type" error.

**Comment by mdmoura** [comment]
@m4nd1cm4rk0 This is not an angular problem ... I also tested it with PostMan. I just updated my question to better explain the problem ... I am not sure if this is by design or something not expected. But if it is by design I don't think a model should be null when one of the properties has an invalid value.

**Comment by dougbu** [comment]
> I don't think a model should be null when one of the properties has an invalid value.

What is your reasoning for this preference?

In any case, it's up to the formatter or, in this case, the JSON.Net deserializer to instantiate the model. JSON.Net `throw`s when it encounters an error. Eventually it returns `null` to MVC. Suggest you file a bug at https://github.com/JamesNK/Newtonsoft.Json/issues if you feel that's incorrect.

**Comment by mdmoura** [comment]
> What is your reasoning for this preference?

Well, that way I will be able to validate the other properties of the model and say which ones are valid or not ... For those not being defined I could always compare with the default value and emit something ...

I mean, how do you do validation if the model is null? You can only say "The model is invalid".

Let me know your opinion ... Maybe I am missing something here ...

**Comment by dougbu** [comment]
>  how do you do validation if the model is null?

When JSON.Net `throw`s an `Exception` during deserialization, MVC adds the information to the `ModelStateDictionary`. Later validation isn't relevant because, as you point out, the model is `null`.

`JsonSerializerSettings` may include an option to continue after encountering an error. I didn't see anything like that last I looked at their code. I also wouldn't recommend using such an option because recovery from input corruption isn't at all reliable.

Again, I suggest you file a bug at [https://github.com/JamesNK/Newtonsoft.Json/issues](https://github.com/JamesNK/Newtonsoft.Json/issues) if you feel that's incorrect.

**Comment by Eilon** [comment]
This is indeed a regular behavior of formatters: they rarely return a partially-constructed object; it's usually all-or-none.

If you instead use MVC's Model Binding feature, you will get partial construction as well as full ModelState describing all the errors.

**Comment by Rickvanderwaal** [comment]
@Eilon How can i use the MVC's Model Binding feature so that i will get partial construction as well as full ModelState describing all the errors ?

**Comment by Eilon** [comment]
@Rickvanderwaal I don't think you need to do anything special. Action method parameters get bound using model binding by default, which in general will get you partial construction. If you apply the `[FromBody]` attribute to a parameter, it will use a formatter, and then it's up to the formatter to do whatever it does, which is typically *not* partial construction.

**Comment by Rickvanderwaal** [comment]
Well i have a problem related to this issue and i don't see partial construction.
Maybe i should create a new issue.

Let's suppose i have the following model with validation:
```csharp
public class Car
{
    [Required(ErrorMessage = "Please provide a brand")]
    public string Brand { get; set; }

    [Required(ErrorMessage = "Please provide a color")]
    [MaxLength(10, ErrorMessage = "Color can be maximum 10 characters")]
    public string Color { get; set; }

    [Required(ErrorMessage = "Please provide a price")]
    public int Price { get; set; }
}
````

The following controller accept this car in the body:
```csharp
[Route("api/[controller]")]
public class CarController : Controller
{
    [HttpPost]
    public IActionResult CreateCar([FromBody]Car form)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

         return Ok();
    }
}
```

When i send the following request, providing a valid brand and  a invalid color and price.
I want to show all the validation errors to the customer.
```json
POST http://localhost:64829/api/car
{
	"brand": "Audi",
	"color": "very dark black",
	"price": ""
}
```
The response gives me only one error.
```json
{
    "price": [
        "The input was not valid."
    ]
}
```


When i provide a valid price, then the remaining validation messages showing up.
```json
POST http://localhost:64829/api/car
{
	"brand": "Audi",
	"color": "very dark black",
	"price": "7"
}
```
Response
```json
{
    "Color": [
        "Color can be maximum 10 characters"
    ]
}
```

I want to show all the errors to the customer so he can fill the form correctly.
But the response only tell me that the price was not valid.
Also the form given in the CreateCar method is null. I expect that it was filled with the valid remaining data. (partial construction?)

Framework: .NET Core 2.0

When i use .NET 4.6.1 for the same example. I get all the validation errors with the first request.
```json
{
    "Message": "The request is invalid.",
    "ModelState": {
        "form.price": [
            "Error converting value {null} to type 'System.Int32'. Path 'price', line 4, position 13."
        ],
        "form.Color": [
            "Color can be maximum 10 characters"
        ]
    }
}
````

I do like to hear from you about this issue.

**Comment by Eilon** [comment]
Right, that's pretty much what I described. I suggested *not* using `[FromBody]`, which will cause it to use *model binding* instead of *formatters*.

**Comment by Rickvanderwaal** [comment]
Thanks for your help. The project is working without [FromBody].

But now i have to use 'application/x-www-form-urlencoded' instead of 'application/json' for the body.
Is there any solution for that?

**Comment by Eilon** [comment]
There's no built-in solution for this that I know of.

**Comment by Rickvanderwaal** [comment]
Thank you

**Comment by ruchanb** [comment]
For 1 year of using Asp.net core I though now on you can only use `HttpPost` with `[FormBody]`. This is a true revelation for me 😮
