### ISSUE TITLE
Logging ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by smbecker** [aspnet/Mvc#4575]
I am not sure if this should go here or in [aspnet/Logging](https://github.com/aspnet/Logging) but [this log message](https://github.com/aspnet/Mvc/blob/73dc7bf48b76c2b82ef09dd56714d1d3fe2948f1/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreLoggerExtensions.cs#L177) causes a ArgumentOutOfRangeException when you attempt to enumerate over the values. Looks like another case of [aspnet/Logging@410](https://github.com/aspnet/Logging/issues/410) where the LoggingMessage definition is using Define<string> when it should be using Define().

**Comment by BrennanConroy** [comment]
@Eilon @muratg 
The define needs to be fixed

**Comment by BrennanConroy** [comment]
Found another one in MVC https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/MvcJsonLoggerExtensions.cs#L20

**Comment by muratg** [comment]
@BrennanConroy Can we check what else is impacted?  

@Eilon RC2?

**Comment by BrennanConroy** [comment]
Did a quick scour of our repos and couldn't find anymore cases of this.

**Comment by Eilon** [comment]
@kichalla this is for RC2, thanks!

**Comment by kichalla** [comment]
Vow. This pattern seems error prone and is only caught when logging is enabled. I think we should validate the format when the define method is called. From what I have found, seems like there is some validation that we can do. Will send out a PR for this.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Logging/issues/413

**Comment by kichalla** [comment]
Ah thanks!

**Comment by Eilon** [comment]
Done?

**Comment by muratg** [comment]
Yep, this was done.  @kichalla Updated the bug tag for you :)

**Comment by kichalla** [comment]
Thanks :-)
