### ISSUE TITLE
RequireHttps should be redirect 302 (not 301)

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#4578]
See https://github.com/aspnet/Mvc/issues/4561.

In this bug we just want to change the default, nothing more. In the other bug we'll make it configurable.

**Comment by Eilon** [comment]
@kichalla another RC2 gift for you 😄

**Comment by khellang** [comment]
I have a PR ready for this. Do you want it on the release branch?

**Comment by Eilon** [comment]
@khellang release would be great. Then @kichalla can port to `dev`.

**Comment by khellang** [comment]
I started out the PR looking at #4561, so it also includes the configurability. I hope that's OK :smile:

**Comment by Eilon** [comment]
@khellang I mentioned this in the PR (thanks for submitting it!) but unfortunately I think for `release` (RC2) we want to take just the change for 302. We are trying to minimize the risk as much as possible.

**Comment by kichalla** [comment]
3c2bdfd368f1b0ed81e92f9287f43a58be06e6e0
