### ISSUE TITLE
WebAPI WebSockets in self host mode not working

### ISSUE THREAD

**Issue by r3db** [aspnet/Mvc#4583]
Not entirely sure if this is the correct place.
But I've seen plenty of code like this:

```csharp
class SomeController : ApiController
{
    public HttpResponseMessage SomeAction()
    {
        if (HttpContext.Current.IsWebSocketRequest)
        {
            // This line is the important part.
            HttpContext.Current.AcceptWebSocketRequest(new SomeSocketHandler());
            return Request.CreateResponse(HttpStatusCode.SwitchingProtocols);
        }
        
        return Request.CreateResponse(HttpStatusCode.BadRequest);
    }
}
```

It's basically doing websockets.
This example does not work in self-hosted scenarios because of: `HttpContext.Current` will always be `null`.

My question is: Is there any way to have this example running from a console application?
Or webapi does not support websockets + self-host.

I haven't found a single of example of that anywhere.

Thanks :+1:

**Comment by davidfowl** [comment]
@r3db This repository has nothing to do with WebAPI. Looks like System.Web code. The bug should be filed on aspnetwebstack.codeplex.com.

**Comment by r3db** [comment]
Thanks and sorry for posting in the wrong location ;-)
