### ISSUE TITLE
Binding URI path parameters

### ISSUE THREAD

**Issue by BadriL** [aspnet/Mvc#4584]
I have a URI with a semi-colon (;) for the path parameter, like so - http://localhost:5000/api/values;foo=9

Any suggestion as to how I can bind the value in my action method?
public IActionResult Get(int foo) { }

I believe semi-colon is used to denote the fact that foo is just a path parameter and is not associated with hierarchy. So, ideally I cannot use the URI of /api/values/9 and have the HttpGet("{foo}") applied on the action.

**Comment by rynowak** [comment]
We've produced samples of something similar in the past: http://aspnet.codeplex.com/SourceControl/latest#Samples/WebApi/RouteConstraintsAndModelBindersSample/RouteConstraintsAndModelBindersSample.Server/ModelBinders/MatrixParameterModelBinder.cs

=====

Here's what I'd suggest - you can write routes like this:

`[HttpGet("/api/products;{params}")]` - This will capture the rest of the path portion of the URL after the semicolon and stick it in the route value `params`.

Then replace the `RouteValueProviderFactory` (see `MvcOptions`) with a value provider that parses the `params` route value into components.

It sounds like the rest should 'just work' without needing a custom implementation of `Route`, but please let me know if you hit any surprises.

**Comment by BadriL** [comment]
Okay, this is my URI - `http://localhost:5000/api/values;name=b,score=20/coord;x=1,y=2/foo`

This is my action method.
```c#
[HttpGet("/api/values;{matrixparam1}/coord;{matrixparam2}/{xyz}")]
public async Task Get(string name, int score, int x, int y, string xyz) {}
```

I created a value provider and added it to the end of the existing list of providers.

```c#
public bool ContainsPrefix(string prefix)
{
    return _values.Keys.Any(k => k.StartsWith("matrixparam"));
}

public ValueProviderResult GetValue(string key)
{
    var values = _values.Keys.Where(k => k.StartsWith("matrixparam"))
                                                        .Select(k => _values[k].ToString());
    foreach (string value in values)
    {
        var dictionary = Microsoft.AspNet.WebUtilities.QueryHelpers
                                                 .ParseQuery(value.Replace(",", "&"));

        if (dictionary.ContainsKey(key))
        {
            return new ValueProviderResult(dictionary[key], Culture);
        }
    }

    return ValueProviderResult.None;
}
```
That gets the binding working. Is something drastically wrong here or is it okay?

**Comment by Eilon** [comment]
@BadriL from my quick glance this looks fine to me. You could always get fancier with the parser, but whatever works for you ought to be fine. There might also be ways to optimize this code, if that's a measurable concern for you.

**Comment by rynowak** [comment]
Yeah this seems fine
