### ISSUE TITLE
Too many redirect when using RequireHttpsAttribute

### ISSUE THREAD

**Issue by endink** [aspnet/Mvc#4588]
if a use RequireHttps in a controller class:
```
[RequireHttps(Order = int.MinValue)]
[Authorize]
[Route("[action]")]
public class XXXController
```
if i remove RequireHttpsAttribute, it will work well.

in Microsoft Eage will always loading, in chrome show "ERR_TOO_MANY_REDIRECTS".

**Comment by imranbaloch** [comment]
Are you running behind Load Balancer e.g, Amazon, Azure F5. Normally, the traffic between load-balancer and your server not use https. You can check X-Forward-Proto header http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html

You can override RequireHttpsAttribute to check X-Forwarded-Proto header(hopefully  your load balancer set the X-Forwarded-Proto header correctly). https://github.com/aspnet/Mvc/blob/3c2bdfd368f1b0ed81e92f9287f43a58be06e6e0/src/Microsoft.AspNetCore.Mvc.Core/RequireHttpsAttribute.cs

**Comment by endink** [comment]
@imranbaloch 
yes i will deploy my application on Azure VM ( windows iis) finally, but this issues appeared when i deploy it on my local PC (windows 10) IIS for testing.

BTW, does X-Forwarded-Proto support for Azure ( virtural machine) ?

**Comment by imranbaloch** [comment]
Oh you are running localhost. Check this how to configure self signed cert http://mobilemancer.com/2016/02/20/asp-net-5core-iis-express-and-ssl/

**Comment by endink** [comment]
@imranbaloch 
I use OpenSSL generate self signed cert , and openning "https://locahost/Index" in browser is Ok, issue only appeared the controller with RequireHttpsAttribute applied.

**Comment by imranbaloch** [comment]
If you can debug the source and check filterContext.HttpContext.Request.IsHttps == true https://github.com/aspnet/Mvc/blob/6.0.0-rc1/src/Microsoft.AspNet.Mvc.Core/RequireHttpsAttribute.cs#L22

**Comment by endink** [comment]
@imranbaloch
I can copy code to a custom filter attribute for debug, but I can't use ssl in development environment, because iisexpress wasn't supported in RC2(1.0-rc2-20100)

**Comment by endink** [comment]
@imranbaloch
BTW, azure use X-ARR-SSL header for check？

**Comment by imranbaloch** [comment]
I haven't used this Azure Load Balancer but look like you are correct https://tomasz.janczuk.org/2013/12/secure-by-default-with-ssl-in-windows.html

**Comment by Eilon** [comment]
@sebastienros can you have a look?

**Comment by sebastienros** [comment]
202

**Comment by Eilon** [comment]
cc @Tratcher @BrennanConroy - are you guys looking at the same issue possibly in the IISIntegration repo?

**Comment by Eilon** [comment]
@JunTaoLuo I wonder if maybe this is what you were running into as well with Hubbup?

**Comment by sebastienros** [comment]
Can you try to remove the `Order` from the `RequireHttps` attribute, I wonder if there could be a conflict between the `Authorize` redirection and the https one.

**Comment by sebastienros** [comment]
Also, can you confirm that you are running https on 443? As you are not setting it in the code and I don't see your configuration, the default behavior is to drop the port during the redirection, which implies 443.
Would be nice to see a trace of the redirects, either with Fiddler or Chrome extensions.

Thanks

**Comment by Tratcher** [comment]
I don't think this is related to https://github.com/aspnet/IISIntegration/issues/140#issuecomment-215135928, that's azure specific.

**Comment by Eilon** [comment]
@Tratcher ah yes good point.

**Comment by sebastienros** [comment]
I can't repro the issue, I have tried adding the attribute with default `[RequireHttps(Order=0)]`, and your example `[RequireHttps(Order=int.MinValue)]` and also with the `[Authorize]` attribute.
I am doing it locally with IISExpress on RC2 official, and SSL works correctly. I am correctly redirected to the authentication page under SSL, and when authenticated to the actual page. Works also when logging off and it stays on https.

It would be great if you could provide us with the redirection loop details to understand where the issue occurs.
Could you also confirm it repros for you with the RC2 release?

**Comment by endink** [comment]
I think it because Authorize attribute auto redirect to LOgin action (http) and Login auto redirect to http . Is there a option to specific https for login path?

**Comment by sebastienros** [comment]
I tried this scenario and it worked for me. Then is no such specific login path for https.
If you could answer the previous questions I posted that could help understanding what happens in your case. Thanks.

**Comment by endink** [comment]
think it because Authorize attribute auto redirect to LOgin action (http) and Login auto redirect to https . Is there a option to specific https for login path?

**Comment by endink** [comment]
ok I will post loop log when I at office today, please wait , sorry. Now I am not in office

**Comment by kichalla** [comment]
I am also unable to repro this issue with RC2 bits + local IIS. The filter that gets created when `Authorize` attribute is used has an Order of `0` and since you specifically set the order of `RequireHttpsAttribute` to min value, the `RequireHttpsAttribute` would be the first one to execute.

Would it be possible for you to give us a repro sample? We are eager to see if there is any real issue here to be fixed for the next major `1.0` release.

**Comment by endink** [comment]
when i upgrade to latest rc2 version , the issue was disappeared, maybe the issue only exsit in RC2 20100

**Comment by Eilon** [comment]
@sebastienros if you are satisfied with this, please close.

**Comment by Eilon** [comment]
Remove 3-Done, adding `no repro` (because we didn't fix anything).

**Comment by mkarlsson** [comment]
I have this problem since upgrading to RC2, but only when publishing to Azure. Vijay Ramakrishnan have been helping me problem solving the problem but only removing the Require attribute solved the issue. I have a customer that need help upgrading in the coming weeks so if anyone knows a workaround to get RequireHttps attribute to work on RC2(worked for months on beta8 and RC1) please let me know.

**Comment by Tratcher** [comment]
@mkarlsson see https://github.com/aspnet/IISIntegration/issues/140#issuecomment-215135928 for Azure https issues.

**Comment by mkarlsson** [comment]
@Tratcher Great, that solved my issue.

**Comment by AhmedMozaly** [comment]
For me, it is really wired behavior need to be changed 
assuming that hosting environment is load-balancer-free is nor the right assumption, ASP.NET MVC should be cloud-ready by default 

I should not spend much time before figuring out that ASP.NET MVC can't see the giant thing in front of it, so called load-balancer 
---
PLEASE RE-OPEN THIS ISSUE

**Comment by Eilon** [comment]
@Tratcher @sebastienros thoughts?

**Comment by sebastienros** [comment]
This is new valuable information that it's related to request forwarding, that could explain why we couldn't repro. I need to look at how we should handle the scenario, will check with Chris as he probably already knows.

**Comment by sebastienros** [comment]
@AhmedMozaly did you see this comment https://github.com/aspnet/IISIntegration/issues/140#issuecomment-215135928 ?
Looks like it might solve the issue you are seeing.

**Comment by sebastienros** [comment]
Tried again on Azure App Services, and it worked without any issues for me.

**Comment by plioi** [comment]
Rather than discard the built-in attribute in favor of one that peeks at the forwarding headers, leverage the UseForwardedHeaders method so that HttpContext.Request will have accurate properties in the first place. It took a lot of digging to even know this was an option:

    app.UseForwardedHeaders(new ForwardedHeadersOptions {
        RequireHeaderSymmetry = false,
        ForwardedHeaders = ForwardedHeaders.XForwardedProto | ForwardedHeaders.XForwardedFor
    });

So, this might not really count as a bug.
