### ISSUE TITLE
Rc2 milestone has been completed, why still pending, and when it's time to clear the release date

### ISSUE THREAD

**Issue by BruinY** [aspnet/Mvc#4589]
Rc2 milestone has been completed, why still pending, and when it's time to clear the release date?

**Comment by davidfowl** [comment]
When he entire product is tested and done, not a second before 😄

**Comment by BruinY** [comment]
Too slow, wait until the heart

**Comment by cwe1ss** [comment]
Damian said during yesterday's community standup that they will present an updated schedule next week.

**Comment by BruinY** [comment]
According to this situation, it is estimated that also waiting for two weeks, it beats the wait too long, isn't it?Dare to dare not to release next Friday, can give some surprise?

**Comment by Eilon** [comment]
@BruinY this is a huge release that include ASP.NET Core, .NET Core, Visual Studio, and lots of other things. We will release as soon as it's ready!

**Comment by filipw** [comment]
is there a tag or a branch representing the code version that made the cut?

**Comment by davidfowl** [comment]
The release branch (which is ter===k

**Comment by filipw** [comment]
thanks 👍

**Comment by imranbaloch** [comment]
Are you guys update the project.json version before release? For example in RC1 we have, https://github.com/aspnet/Mvc/blob/6.0.0-rc1/src/Microsoft.AspNet.Mvc.Core/project.json#L3

but in release tag we have, https://github.com/aspnet/Mvc/blob/release/src/Microsoft.AspNetCore.Mvc.Core/project.json#L3

**Comment by pranavkm** [comment]
@imranbaloch we do that as part of creating the `master` branch and the `1.0.0-rc2-final` branch. My guess is it'll be 1.0.0 since the packages got renamed and reversioned after RC1.
