### ISSUE TITLE
AspNet MVC Question

### ISSUE THREAD

**Issue by di48l069** [aspnet/Mvc#4591]
Hi,

I would like to create a site with new asp.net 5 MVC 6 is it stable? If further releases come out will i be able to update the nugets or must i create a new project to get latest features and bug fixes?

**Comment by cwe1ss** [comment]
I would wait until RC2 is released. If you begin now with RC1 you have to learn a lot of concepts that are no longer relevant for RC2 (DNX, DNVM). 

However there's still no release date for RC2. In the last community standup they said, that they will publish a new schedule next week.

**Comment by di48l069** [comment]
@cwe1ss Thank you for your response
