### ISSUE TITLE
Property naming of HttpContext is inconsistent across View and Controller

### ISSUE THREAD

**Issue by anurse** [aspnet/Mvc#4592]
In a Controller, the `HttpContext` is accessed through the `HttpContext` property, but in a view it is accessed through `Context`. This seems a little inconsistent. It's not too bad since IntelliSense makes it pretty clear.

Certainly doesn't seem RC2-blocking, but it felt a little odd while I was testing.

**Comment by Eilon** [comment]
We should look at what the naming was in MVC 5.x. I vaguely recall that we kept this naming, inconsistent or not, due to legacy.

**Comment by Eilon** [comment]
I checked and it's the same as MVC 5.x, and we did keep it consistent on purpose.

**Comment by anurse** [comment]
Sounds like a good enough reason to me :). Thanks for checking!

**Comment by Eilon** [comment]
Well it's a pretty bad reason really, but, you know, because reasons 😄

**Comment by rynowak** [comment]
Maybe we need to add a `[PlzJustStopThisIsTheWayItIsBecauseBackCompat]` attribute so we can have a tool auto-respond to these kind of issues.

**Comment by anurse** [comment]
Or we just make the breaking changes now, while we can ;)

**Comment by cwe1ss** [comment]
+1 for [breaking all the things!!!](https://cdn.meme.am/instances/54765812.jpg) :dancers:

I guess, at this point no one cares about further breaking changes, especially if they can be fixed with search&replace.

Honestly, I'm not sure if I can still deal with a stable API. I'm afraid working with RTM will get really boring. How should I start my day without my build server telling me that stuff broke again?!? :D

**Comment by ivaylokenov** [comment]
You guys already made a breaking change with removing the "Http" prefix from some action results like "HttpBadRequest". The explanation was that the Core 1.0 is a new framework and it is fine. I believe for consistency, this one here can be made "HttpContext" in the views.

**Comment by Eilon** [comment]
@ivaylokenov the distinction we've made on these types of breaking changes is whether an app's code is likely to reference this type by name or not. In the case of Context/HttpContext it's quite often in user's code, so it could be an annoying change. The ActionResult types however appear less frequently in code. Most code uses the "factory" methods on Controller, e.g. `return BadRequest(...)` as opposed to `return new BadRequestResult(...)` (or whatever). So the actual type name is normally hidden.

**Comment by ivaylokenov** [comment]
@Eilon I was talking about the factory methods in the controller class too. This was the breaking change and I believe a lot of app's code bases used these:
https://github.com/aspnet/Mvc/commit/75c05be2f71837c1094eb42ad8c283979bbdfbef

**Comment by Eilon** [comment]
@ivaylokenov wow, your memory is far better than mine!

**Comment by ivaylokenov** [comment]
@Eilon Well, I am stalking these repositories like they are my own. I know more than 60% of the code maybe. There is no better place for C# design and performance know-how in my opinion. 👍
