### ISSUE TITLE
Performance Scenario: MusicStore 

### ISSUE THREAD

**Issue by mnltejaswini** [aspnet/Mvc#4593]
**This is top-level performance scenario for 1.0.0. We're using this item to track the status and all of the individual improvements.**

Code here: https://github.com/aspnet/MusicStore/tree/dev/src/MusicStore
#### Summary

This is a complex browser-based app that uses a variety of ASP.NET features. This is also our most prominent sample and had lots of eyes on it for coding style and feature set.

For simplicity we're measuring the home page.
- Authentication (cookie)
- Database (localdb)
- Session
- Cache TagHelper
- Layout Page
- View Components and Partials
- Diagnostics (logging)
# 
#### Variations

(None)
# 
#### Status

Scenario Status: **complete**

Known Investigations/Improvements:
- [ ] TBD: Update with known issues

**Comment by mnltejaswini** [comment]
@rynowak  Didn't find any issue related to MusicStore scenario. Hence logged a new one.

**Comment by mnltejaswini** [comment]
### 1. Analysis for MusicStore.GetCartAlbumTitles() 
https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Models/ShoppingCart.cs#L102 
 Linq BinaryExpression compare is causing MethodInfo[] allocations which is 1.75% of total memory allocations. By changing the Where expression to  .Where(cart => cart.CartId.Equals(_shoppingCartId)) we got rid of MethodInfo[] allocations. 

The profile after the change is 
![image](https://cloud.githubusercontent.com/assets/8011073/15200108/c8310d16-1798-11e6-989f-9a88d7eabee7.png)

**Comment by mnltejaswini** [comment]
2: ViewBufferTextWriter,  ViewBufferPage[], ViewBuffer allocations .
Most of these allocations are coming from 
![image](https://cloud.githubusercontent.com/assets/8011073/15200136/0442bce6-1799-11e6-9b32-b8e2c52e7e7d.png)

RazorPage.StartTagHelperWritingScope() is always followed by RazorPage.EndTagHelperWritingScope(). The code within Razor page executes synchronously and hence each RazorPage can have a simple List based pool for ViewBuffer and ViewBufferTextWriter. They can be rented in the StartTagHelperWritingScope() and can be returned in EndTagHelperWritingScope()

Prototype of these changes resulted in 3.4% saving in total bytes as shown below
![image](https://cloud.githubusercontent.com/assets/8011073/15200316/7d9657a0-179a-11e6-9694-8c1aa01625dc.png)

**Comment by mnltejaswini** [comment]
### 3. String Allocations from UrlHelper.GenerateUrl

![image](https://cloud.githubusercontent.com/assets/8011073/15200330/a303089e-179a-11e6-8b6a-027383ac114b.png)

UrlHelper.GenerateUrl does many things when there are values for protocol, host, fragment and the virtual path doesn't start with /. In most common cases, it is identified that the URL generated by the UrlHelper is same as virtual path. Hence we can have a fast get where there is not need for string builder and the resulting string.

Prototype of these changes resulted in 1.11% savings in total bytes allocated

![string](https://cloud.githubusercontent.com/assets/8011073/15200383/33fe7a4a-179b-11e6-9e6b-ad10ec154aa3.PNG)

**Comment by mnltejaswini** [comment]
### 4. Optimize  TemplateBinder.GetValues() to reuse the RouteValueDictionary. 

![image](https://cloud.githubusercontent.com/assets/8011073/15200432/9527b624-179b-11e6-8205-290ae4302f76.png)

The values dictionary that is passed to TemplateBinder.GetValues  can be reused to create AcceptedValues with some refactoring to the private struct TemplateBindingContext
With this refactoring, there is a good saving of 4.8% as shown below 

![image](https://cloud.githubusercontent.com/assets/8011073/15200496/4f6a83ea-179c-11e6-9f03-7ed46370dca6.png)

**Comment by mnltejaswini** [comment]
### 5. Make TagHelperAttribute a struct. 
One of the top allocations are coming from TagHelperAtrribute 
![image](https://cloud.githubusercontent.com/assets/8011073/15200534/9ec9bf64-179c-11e6-8f1d-ee3195d73ea8.png)

TagHelperAttribute is immutable and can be a candidate for being struct. A prototype of this change indicated a saving of 2% of total bytes allocated

![image](https://cloud.githubusercontent.com/assets/8011073/15200573/e9b4dbf8-179c-11e6-8588-77f42bf2654a.png)

**Comment by mnltejaswini** [comment]
### 6. Lazy initialization of Items in TagHelperContext


![image](https://cloud.githubusercontent.com/assets/8011073/15200615/4515b116-179d-11e6-8b8c-4af4f7e45189.png)

Each call to TagHelperScopeManager.Begin allocates a Dictionary object that is meant to be used to communicate between parent and child execution context.  I was able to track the usage of these items only in SelectTagHelper and OptionTagHelper. Hence we can postpone this allocation until it is used.

Prototype of this change saved 1.8% of total allocations. 
![image](https://cloud.githubusercontent.com/assets/8011073/15200739/426e80d6-179e-11e6-8907-c5c082e6effa.png)

**Comment by mnltejaswini** [comment]
From sampling profile, need to investigate

![image](https://cloud.githubusercontent.com/assets/8011073/15201232/9060b372-17a3-11e6-9144-15c1962ca213.png)

![image](https://cloud.githubusercontent.com/assets/8011073/15201290/45d9383c-17a4-11e6-9572-63814048a5b8.png)

![image](https://cloud.githubusercontent.com/assets/8011073/15201317/95e2bda8-17a4-11e6-9f6e-df550780fefa.png)

**Comment by mnltejaswini** [comment]
### 7. Reuse the StringBuilder used for the StringWriter in TagHelperOutput.CopyAttributesTo(IHtmlContentBuilder destination)

TagHelperOutput.CopyAttributesTo() creates a new StringWriter. This will allocate a new StringBuilder 
internally. We are pooling the TagHelperOutput and hence we can have a single StringBuilder that can be cleared and reused to create the StringWriter. 

Prototype of this change saves 0.6% of total bytes allocated and will reduce the StringBuilder and Char[] allocations
![image](https://cloud.githubusercontent.com/assets/8011073/15221127/fbd8bf34-181e-11e6-92b3-4bf8678966eb.png)

**Comment by mnltejaswini** [comment]
8. Replace Contains with IndexOf in TagHelperOutput.CopyAttributesTo() 
![image](https://cloud.githubusercontent.com/assets/8011073/15222843/5bbb5734-1826-11e6-81aa-9c558c458ef9.png)

2.64% of CPU time is spent in IndexOf() when checking whether the HtmlContent has single quotes in it as pasted below

` if (htmlEncodedString != null && !htmlEncodedString.Value.Contains("\""))
                    {
                        destination.AppendHtml(htmlEncodedString);
                    }`

As here we are looking for a single character, we can use faster version of IndexOf(char) overloaded method to speed up this comparison. I replaced it with 

`if (htmlEncodedString != null && htmlEncodedString.Value.IndexOf('"') == 0)
                    {
                        destination.AppendHtml(htmlEncodedString);
                    }`

This profile after this change is 
![image](https://cloud.githubusercontent.com/assets/8011073/15222970/edf11a1c-1826-11e6-8a68-5b911ac98c28.png)

**Comment by mnltejaswini** [comment]
![image](https://cloud.githubusercontent.com/assets/8011073/15224000/06f194b0-182c-11e6-9caf-808ce7ad8ccb.png)

1.82% is spent in string.Compare() . 
`if (environment.Equals(currentEnvironmentName, StringComparison.OrdinalIgnoreCase))
                    {
                        // Matching environment name found, do nothing
                        return;
                    }`

Here we compare the stringsegment with a string and the comparison type is  OrdinalIgnoreCase. In this scenario, string.Equals() is the fastest method to reduce the cost. 

`if (environment.Buffer.Equals(currentEnvironmentName, StringComparison.OrdinalIgnoreCase))
                    {
                        // Matching environment name found, do nothing
                        return;
                    }`

This change saved the cost as shown below
![image](https://cloud.githubusercontent.com/assets/8011073/15224178/d877612c-182c-11e6-9635-52b8e678f234.png)

**Comment by rynowak** [comment]
**Updated 5/23**

Allocation Data: 3000 requests
![image](https://cloud.githubusercontent.com/assets/1430011/15488891/b3df9d02-210f-11e6-9bf8-ddb9a45bfc04.png)

Note that this profile is using EF + SqlClient - the other profiles here were taken without SqlClient so data isn't directly comparable.

The major costs here are:
- EF (services)
- URL generation (`string`, `RouteValueDictionary` and related types)
- TagHelpers (`StringWriter`, `TagHelperAttribute`)

=====

Sample data for this is hard to represent here. EF is the most significant factor for sampling.
