### ISSUE TITLE
Any functionality for digital signature validation in coreclr?

### ISSUE THREAD

**Issue by Yablargo** [aspnet/Mvc#4594]
Hello,

This may be dumb/obvious, but I find msyelf wanting to validate a digital signature (created externally in CAPICOM) and I would use System.Security.Cryptography.Pkcs and build a contentinfo and check the hash.

Is there any solution on the dnx5.0 side of things to do this sort of operation? Are there platform-specific implementations to download? e.g. if this is running on windows, can I hit the windows CA store? or is this not really possible?

I'm just investigating my options at this point, and my client is also validating the signatures and it is a .net 461 app, so I'm not particularly worried if this sort of functionality has to be deferred.

Thanks
-Matt

**Comment by Eilon** [comment]
cc @blowdart 

@Yablargo ultimately that's a general .NET Core question, so I recommend posting the question in https://github.com/dotnet/corefx/issues/. Thanks!

**Comment by blowdart** [comment]
It's coming - https://github.com/dotnet/corefx/pull/8083

**Comment by Eilon** [comment]
Closing as external. Thanks!
