### ISSUE TITLE
Consider exposing model attributes in ModelExpression.Metadata for a TagHelper

### ISSUE THREAD

**Issue by Vasimovic** [aspnet/Mvc#4597]
I need to get the MaxLength and or the StringLength property attributes form the Model to build a custom input tag with the html maxlength attribute

Example:
`<input type="text" maxlength="10">`

Currently I use this code to retrieve the attribute from the TagHelper ModelExpression:

`var maxLengthAttribute = ((DefaultModelMetadata)ForExpression.Metadata).Attributes.PropertyAttributes.OfType<MaxLengthAttribute>().FirstOrDefault();`

Consider exposing ModelExpression.Metadata.Attributes to allow something like this:

`var maxLengthAttribute = ForExpression.Metadata.Attributes.PropertyAttributes.OfType<MaxLengthAttribute>().FirstOrDefault();`

**Comment by dougbu** [comment]
@Vasimovic probably better to avoid Reflection per-request. Suggest instead using
``` c#
modelExpression.Metadata.ValidatorMetadata.OfType<MaxLengthAttribute>().FirstOrDefault()
```

**Comment by Vasimovic** [comment]
Thanks @dougbu, this is exactly what I needed, don't know howI missed the ValidatorMetadata!

**Comment by Eilon** [comment]
Looks like this was answered, so closing this. If you have further questions please let us know. Thanks!

**Comment by Muchiachio** [comment]
@dougbu what if the attribute I want to check for isn't validation one? Now, I'm using this in my model binding
```C#
context
    .ModelMetadata
    .ContainerType?
    .GetProperty(context.ModelMetadata.PropertyName)?
    .IsDefined(typeof(TrimmedAttribute), false) == true
```
which involves a lot of reflection even though it's available in `DefaultModelMetadata`.

**Comment by dougbu** [comment]
Fair point though I'm not positive increasing the `ModelMetadata` surface is necessary for that use case either. It is _an_ option:

1. You could cast the `ModelMetadata` to `DefaultModelMetadata`.
2. You could write an `IDisplayMetadataProvider` implementation which copies `context.Attributes` (or `PropertyAttributes` or `TypeAttributes` or a subset of any of these) into e.g. `context.DisplayMetadata.AdditionalValues[typeof(TrimmedAttribute)]`.
3. We could move a few things around i.e. move `ModelAttributes` from `...Mvc.Core` into `...Mvc.Abstractions` and expose the `Attributes` property in `ModelMetadata`. (But the `static` methods in `ModelAttributes` don't belong in `...Mvc.Abstractions`.)

**Comment by Eilon** [comment]
Reactivated, but moved to Backlog, as we are not planning to implement it at this time.
