### ISSUE TITLE
[Question] IBinderTypeProviderMetadata inherits from IBindingSourceMetadata, why?

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Mvc#4598]
I was going to use IBinderTypeProviderMetadata implemented on an attribute with which I can just set the BinderType to allow us to do some data converting and shaping before it gets set on the model. But it seems I also need to add a getter for BindingSource, why? I don't know the BindingSource when I add this attribute on a property in the model at compile time.

Can I just return null, is that a compatible/safe way? 
As going forward I could imagine code (MetadataDetailsProviders) or maybe even MVC code populating that and a binder down the line expecting it to be. My attribute now overrides this with null and would kill that. 

Please advise:
- Go this route as it's ok-ish (it feels hacky)
- Create your own MetadataDetailsProvider that checks for a separate attribute type which only exposes a BinderType and set that on the ModelMetadata

**Comment by Eilon** [comment]
@dougbu @rynowak any idea?

**Comment by dougbu** [comment]
I suspect this looks as it does only for historical reasons. Don't see anywhere that handles `IBinderTypeProviderMetadata` and doesn't separately handle `IBindingSourceMetadata`. Not sure it's a big deal either way.

> Can I just return `null`, is that a compatible/safe way?

Yes, returning `null` is just fine.

**Comment by rynowak** [comment]
Returning null is fine. The only real reason these are tied together is because you'd likely want to specify a source if you're using ApiExplorer/Swagger

**Comment by Eilon** [comment]
@dougbu @rynowak thanks!

Closing this as the question was answered: there's no great reason, but it's not too harmful either.

**Comment by NinoFloris** [comment]
@dougbu BindingInfo.cs does the scanning for these attributes. Is
BindingInfo also legacy?
I found it quite hard to grok all the flows and especially the roles of all
the different classes as they have quite some overlap in their
functionality. Also not everything from older mvc's hold up anymore so the
code was my documentation in this case.
