### ISSUE TITLE
Support validation and model binding attributes on action parameters

### ISSUE THREAD

**Issue by MicahZoltu** [aspnet/Mvc#4603]
``` c#
[HttpGet]
[Route("")]
public async Task<IActionResult> Get([FromQuery(Name = "name")] String name)
{
    if (!ModelState.IsValid)
        throw new Exception();
}
```

In the above snippet, if you call the action without any query string parameters the `ModelState` evaluates as valid and no exception is thrown.

Unfortunately, `BindRequiredAttribute` is not allowed on method parameters and there doesn't appear to be any other tools for marking a parameter as required.  Of course, I can manually go through and null check everything, but I would much rather leverage `ModelState.IsValid` and `HttpBadRequest(ModelState)`.

**Comment by Eilon** [comment]
@dougbu / @rynowak any reason not to allow `[BindRequired]` and friends to apply to parameters as well as properties/classes?

**Comment by dougbu** [comment]
@Eilon if we changed the code so that attribute and its friends actually did something there, no.

**Comment by rynowak** [comment]
I think it would be nice to support validation attributes on parameters, as well as the attributes which affect model binding.

**Comment by dougbu** [comment]
See also https://github.com/aspnet/Mvc/issues/4750#issuecomment-230624120

**Comment by danroth27** [comment]
This was done as part of https://github.com/aspnet/Mvc/issues/6790
