### ISSUE TITLE
Improve the log message for view location cache miss

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#4609]
For example, its currently "View lookup cache miss for view 'About' in controller 'Home'"

Many people might not care about it but we could just make it clear for anyone interested to understand how the system works.

![image](https://cloud.githubusercontent.com/assets/6559784/15156104/5140cede-169a-11e6-975d-fd5367b27c4f.png)

**Comment by Eilon** [comment]
@kichalla what is the suggestion?

**Comment by rynowak** [comment]
Logging can't teach people how the product works sadly, that's what documentation does

**Comment by Eilon** [comment]
@kichalla any thoughts?

**Comment by kichalla** [comment]
Maybe something like the following? 

- Unable to find location of view 'About' in cache for controller 'Home'
- Found location of view 'About' in cache for controller 'Home'

**Comment by rynowak** [comment]
I don't think that these suggestions are a significant improvement, that's just a different way of saying what the existing message says.

I recommend we close this unless we find a significant way to improve this /cc @Eilon
