### ISSUE TITLE
Parameterless RouteAttribute constructor

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Mvc#4610]
`RouteAttribute` today requires the template to be specified. So, you can end up with the below look on your controller:

``` csharp
    [Route("cars")]
    public class CarsController : Controller 
    {
        [Route("")]
        public IEnumerable<Car> GetCars()
        {
            // Impl goes here
        }
    }
```

However, it would be nice to have a parameterless constructor on `RouteAttribute` to indicate that it relies on the class level template. 

``` csharp
    [Route("cars")]
    public class CarsController : Controller 
    {
        [Route]
        public IEnumerable<Car> GetCars()
        {
            // Impl goes here
        }
    }
```

There might be caveats on the usability of the type here though. Some might go ahead and annotate an action with `RouteAttribute` without giving it a template where the controller itself doesn't have one. However, it's still worth exploring. Another option would be to bring back `RoutePrefixAttribute` which can be only applied to a controller.

**Comment by javiercn** [comment]
If I remember correctly we will not consider the action attribute routed if the combined path of the controller and the action is null or empty.

Having an empty Route attribute applied to the controller can be tricky as makes the actions look like attribute routed when they are not.

Is there a reason why you can't use HttpGet/Post or HttpMethod on the action instead?

**Comment by rynowak** [comment]
I agree with @javiercn - it's intentional that `Route` always takes a parameter. In the scenario that you identified above, the `[Route]` on the action is redundant.

Recommend we close as wont fix /cc @Eilon
