### ISSUE TITLE
Modify Action Parameters Safely

### ISSUE THREAD

**Issue by SamuelEnglard** [aspnet/Mvc#4611]
Is there a way to modify `ActionDescriptor.Parameters` safely so that it is only done once and does not cause threading issues? Right now I'm doing it in a Resource Filter and have to lock. I'd much prefer to do something on startup for example.

**Comment by javiercn** [comment]
Use ApplicationModel. I'm not sure of the exact thing you are trying to accomplish but it sounds like you should do it using application model. @pranavkm where is the sample for this? I remember there was one. You can look at https://github.com/aspnet/Mvc/blob/dev/test/WebSites/ApplicationModelWebSite/Conventions/FromHeaderConvention.cs as an example

**Comment by SamuelEnglard** [comment]
I'm adding parameters passed on attributes (obviously the methods don't have direct access to them but other parts of the pipeline do)

**Comment by rynowak** [comment]
Modifying action descriptors and related objects after startup is never safe. You can modify the application model to influence the ADs that will be generated, or you can implement an `IActionDescriptorProvider` so modify the ADs during startup.

If you can give us a little more information about what you're trying to accomplish we can try to help.

**Comment by javiercn** [comment]
I'm not sure I understand your scenario. Do you intend to pass those parameters as arguments to the action or is it just a bag of properties that you want to pass around and is associated with a given action? See https://github.com/aspnet/Mvc/blob/dev/test/WebSites/ApplicationModelWebSite/Conventions/ActionDescriptionAttribute.cs

**Comment by SamuelEnglard** [comment]
I actually looked into the `IActionDescriptorProvider`s but got lost.

What I'm trying to do is have parameters that are used in every step of the pipeline (model binding, validation, filters, routing, etc) but are actually not in the method use the method can't use them

**Comment by Eilon** [comment]
Perhaps you could have a very low-priority (i.e. have a higher Order value) global action filter that removes the parameter from the parameters dictionary?

That is, in the action filter, modify this dictionary:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Filters/ActionExecutingContext.cs#L49

?

**Comment by SamuelEnglard** [comment]
That is a thought, but then the method has the parameters still

**Comment by Eilon** [comment]
@SamuelEnglard can you provide a more concrete example of what you're trying to do? I'm a bit confused about where the parameters are, and where you're trying to prevent them from being used. Some examples of what your filters, controllers, and actions look like would be useful. Thanks!

**Comment by SamuelEnglard** [comment]
Hopefully this will help https://gist.github.com/SamuelEnglard/04466b6b72bc3ab54af72826dfe6b693

**Comment by Eilon** [comment]
Interesting. I admit I didn't fully understand the scenario, but it seems to me like what you really want is a model binder or value provider that manufactures a parameter. What is the reason that wouldn't work? It might be best if you can describe in words what the scenario is. It's fairly easy to get caught up in why certain code doesn't work, but without us understanding what the scenario is it's difficult to say what's right.

**Comment by SamuelEnglard** [comment]
Can do.

So I'm building a [WMS](https://en.wikipedia.org/wiki/Web_Map_Service) server. Of the parameters the client sends with a request some are needed by the function, others by the "pipeline". In the sample I gave the client sends the MIME of the format they want the response in as a parameter. The Action doesn't need to know about this since it just returns a .NET object. On the flip side by not making it a parameter of the Action method binding does not occur (Admittedly converting a `string` to a `MediaTypeHeaderValue` is really easy but other types are not). 

Also, while not shown in the example code I gave, I have filters that make sure the request contains all required parameters:

```csharp
public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
{
    IModelMetadataProvider metadataProvider = new EmptyModelMetadataProvider();
    Model.ServiceExceptionReport exceptionReport = new Model.ServiceExceptionReport();
    if (context.ActionArguments.ContainsKey("version"))
    {
        exceptionReport.Version = ((Version)context.ActionArguments["version"]).ToString();
    }
    foreach (ControllerParameterDescriptor p in context.ActionDescriptor.Parameters.OfType<ControllerParameterDescriptor>())
    {
        if (context.ActionArguments.Keys.Any(PredicateExtensions.In<ControllerParameterDescriptor, string>((pn, cpd) => pn.Equals(cpd.Name, StringComparison.OrdinalIgnoreCase), p)))
        {
            continue;
        }
        if (p.GetCustomAttribute<DefaultValueAttribute>() == null && p.GetCustomAttribute<OptionalAttribute>() == null)
        {
            exceptionReport.ServiceExceptions.Add(new Model.ServiceException() { Locator = p.Name, Value = $"Parameter '{p.Name}' was not sent", Code = "MissingParameter" });
        }
    }
    if (exceptionReport.ServiceExceptions.Count > 0)
    {
        throw new ActionResultException(new BadRequestObjectResult(exceptionReport));
    }
    await next();
}
```

Doing this is much simpler with them as parameters to the action. But I don't want the action having them as parameters because it doesn't need them (and in some cases shouldn't know).

Hope that helps :)

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
