### ISSUE TITLE
Consider removing IValueProvider and only using IBindingSourceValueProvider or another variant

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#4613]
Having the `IValueProvider` AND `IBindingSourceValueProvider` interfaces made me believe I could build a value provider that sat next to the other value providers and then modify values (a value not from a source). Seeing that all of our value providers are binding source value providers and the infrastructure around them expects a certain behavior, having the `IValueProvider` interface only adds confusion.

**Comment by Eilon** [comment]
Unfortunately not high enough value here.
