### ISSUE TITLE
Consider adding an allow list behavior for model binding

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#462]
Levib had a suggestion on improving model binding based on feedback he's received from customers. The essence of the feature is to be able to opt into model binding on a per property basis. We'd have to make this optional (perhaps by annotating the model type with an attribute) and would then only bind things that have a HttpBindingBehavior (or equivalent) attribute. 

| 148 | 10306 | Reported By: Pranav K |

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Mvc/issues/4718.
