### ISSUE TITLE
Use lighter, more optimized dictionaries for route sensitive TagHelpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#4624]
We currently use Dictionaries to track route data for things like `AnchorTagHelper`. We can be smarter and use things like `RouteValueDictionary` to make for a more performant implementation.

@mnltejaswini can provide perf numbers.

**Comment by rynowak** [comment]
There's more to it than just this.

Binding an attribute like `asp-route-genre=@genre` in a `<a>` to a string is pretty expensive. We want to also investigate support for `asp-routevalues=new { genre }` as a more performant alternative. This would work pretty similar to the approach the HtmlHelpers use, and would work nicely with the above.

**Comment by dougbu** [comment]
@rynowak Razor and MVC already support assigning directly to the dictionary. In the `<a>` and `<form>` cases, set the `asp-all-route-data` attribute to set the `IDictionary<string, string> RouteValues` property.

**Comment by NTaylorMullen** [comment]
@dougbu Even when assigning to the dictionary directly those `TagHelper`s still need to construct an `<object, object>` version to pass to the generators.
