### ISSUE TITLE
Clean up our TestCommon

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4627]
We have a few things in `Mvc.TestCommon` that require you to reference the rest of MVC to use the package (`TestModelMetadataProvider` and similar types). It's kinda gross, and creates a big knot in our dependency graph because each test project needs to depend on all of the various packages.

It would be nicer if the stuff in `Mvc.TestCommon` only depended on `Mvc.Abstractions` and `Mvc.Core`. 

We should look at how these types are used, and move the and the related tests into functional tests or integration tests where it's appropriate to reference the entire framework.

**Comment by rynowak** [comment]
Another reason to do this... I was working on `Mvc.Core` today - rerunning tests in that project requires rebuilding all of the other product assemblies :cry: So it cuts both ways..

**Comment by Eilon** [comment]
Moving to 1.2.

**Comment by rynowak** [comment]
Nothing happening here in 2.0.0

**Comment by rynowak** [comment]
Make up your mind @glennc

**Comment by javiercn** [comment]
I do believe that this is at this point of negligible value and we should just go ahead and close it.

**Comment by rynowak** [comment]
Why?

**Comment by javiercn** [comment]
* The build is faster now than when this work item was filed.
* The difference in time is not likely to be significant.
* Most of our work these days happens elsewhere.
* The effort to untangle this is not trivial.
* We've been punting this for a long time, if we still haven't done it after so long is because its not clear what the ROI of doing this is, so we should accept that and close it.

**Comment by mkArtakMSFT** [comment]
@javiercn , @rynowak is this something we can push out further? Maybe even RC milestone?

**Comment by javiercn** [comment]
@mkArtakMSFT Definitely. We haven't cared about getting it done in past releases.

**Comment by mkArtakMSFT** [comment]
Moving this to 2.2 milestone as it seems this is not a high priority item.
