### ISSUE TITLE
Wrong Custom error message in server side validation for MVC6 TagHelper

### ISSUE THREAD

**Issue by vigneshc91** [aspnet/Mvc#4630]
In the MVC6 TagHelper i have created two text box and binded model for that with custom error message one textbox of type string and other of type int during the post back the custom error message specified in the data annotation is not rendered properly for type other than string.

My Controller is

```
public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Index(Sample model)
    {
        return View(model);
    }
}
```

The Model class is

```
public class Sample
{
    [Required(ErrorMessage = "String value is needed")]
    public string StringValue { get; set; }

    [Required(ErrorMessage = "Int value is needed")]
    public int IntValue { get; set; }

}
```

And My Html Tag Helper code is

```
@model ValidationMessage.Models.Sample
<form method="post" action="/Home/Index">
    <label>String</label>
    <input asp-for="StringValue" type="text" />
    <span asp-validation-for="StringValue"></span>
    <br />

    <label>Int</label>
    <input asp-for="IntValue" type="text" />
    <span asp-validation-for="IntValue"></span>
    <br />

    <input type="submit" />
</form>
```

Here am checking the server side validation alone, If i click the submit button the first text box span validation shows String value is needed but the second text box span validation shows The value '' is invalid. instead of Int value is needed.

Making the model property to nullable working as expected, but i cannot give nullable property in all cases. Is it possible to make it work without making it as nullable because in MVC5 its working fine.

**Comment by dougbu** [comment]
The `IntValue` property in your model cannot be `null`. Therefore the `[Required]` attribute (from Data Annotations, not MVC) will never mark it as invalid.

Suggest using MVC's `[BindRequired]` on the `IntValue` property if you prefer to use only server-side validation.

> checking the server side validation alone

Are you sure this is the case? The only validation that _should_ be occurring for the `IntValue` property is done client-side. MVC automatically adds client-side validation types ensuring non-`Nullable` value types are set.

Could you upload the source of the generated HTML page, especially `<input>`, `<span>` and `<script>` tags?

**Comment by vigneshc91** [comment]
Here are the generated html page,

This is the generated html during the page load
[inital_pageSource.txt](https://github.com/aspnet/Mvc/files/267398/inital_pageSource.txt)

This is the generated html after the post back showing the server-side validation error message
[after-postBack.txt](https://github.com/aspnet/Mvc/files/267399/after-postBack.txt)

**Comment by dougbu** [comment]
Both error messages in your original scenario are as-expected.
- The `"String value is needed"` error message comes from server-side validation, specifically the `[Required]` attribute.
- The `"The value '' is invalid."` error message comes from model binding. The empty `string` cannot be converted into an `int`.

To make the messages more consistent, I updated `Startup` as follows:
``` c#
services
    .AddMvc()
    .AddMvcOptions(options =>
        options.ModelBindingMessageProvider.ValueMustNotBeNullAccessor = _ => "Int value is needed");
```

The above changes the error message model binding adds globally. To do something more complicated e.g. to vary the message depending on the property, implement `IBindingMetadataProvider` and change `context.BindingMetadata.ModelBindingMessageProvider.ValueMustNotBeNullAccessor` there. Add your implementation to `MvcOptions.ModelMetadataDetailsProviders` in `Startup`.

**Comment by dougbu** [comment]
Cleared the `investigate` label.
