### ISSUE TITLE
Remove `ActionFilterAttribute` et cetera

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4639]
We have three `abstract` classes that provide little value. All of the following are `Attribute`s that also implement `IOrderedFilter`.
- `ActionFilterAttribute` that implements `IAsyncActionFilter` and `IActionFilter` as well as (for some reason) `IAsyncResultFilter` and `IResultFilter`
- `ExceptionFilterAttribute` that implements `IAsyncExceptionFilter` and `IExceptionFilter`
- `ResultFilterAttribute` that implements `IAsyncResultFilter` and `IResultFilter`

But if I choose to implement a synchronous filter, why base my implementation on something that also does the same asynchronous filter (and visa versa)? The MVC filter invocation infrastructure handles both asynchronous and synchronous filters just fine.

The code I write is almost identical when using one of the above `abstract` classes or the `interface` I actually care about. The difference is that the `abstract` base is less prescriptive i.e. helpful. We use these classes in tests but that looks like code coverage and and not a requirement. The best that can be said is that I can choose to implement the `ing` method and ignore the `ed` method -- 4 lines saved :smiling_imp: 

The fact `ActionFilterAttribute` is also a result filter and the lack of an `abstract` resource filter makes these classes look odd.

**Comment by Eilon** [comment]
These attribute base classes exist both for compatibility and for convenience. Though it's perhaps a tad confusing that there are seemingly-duplicate methods to override, I'm open to suggestions on how to make that less confusing, yet maintain both the flexibility and ease of use already present.
