### ISSUE TITLE
Some public `Attribute`s lack doc comments

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4641]
A fairly complete list below. Hit `[NonAction]` then found the rest.

Might have missed one or two. Was also only looking for doc comments on the classes; didn't check that every constructor and property was documented.
- `[NonAction]`
- `[BindingBehavior]`
- `[BindNever]`
- `[BindRequired]`
- `[ActionName]`
- `[Area]`
- `[ViewComponent]`
- `[UseWebApiActionConventions]`
- `[UseWebApiOverloading]`
- `[UseWebApiParameterConventions]`
- `[UseWebApiRoutes]`

**Comment by Eilon** [comment]
See if we can copy some of the text from MSDN for the ones that already existed. No need to get too fancy.

**Comment by dougbu** [comment]
1f6bbf9 .. b5a6303
