### ISSUE TITLE
Rationalize `IViewEngine` / `ICompositeViewEngine` impedance mismatch

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4643]
`ViewResult`, `ViewViewComponentResult`, ... have `ViewEngine` properties of type `IViewEngine`. However, the default value is found looking up the `ICompositeViewEngine` interface in DI. This is both counter-intuitive and overly-restrictive. For example, users can't register the `RazorViewEngine` itself as the default view engine (disabling `MvcViewOptions.ViewEngines` because they don't need that indirection). Suggest we instead register the `CompositeViewEngine` using the `IViewEngine` interface.

Note `ICompositeViewEngine` is basically a marker interface wrapping `IViewEngine`; it just adds a property used only in tests. Nothing is currently registered as an `IViewEngine` in DI.

**Comment by Eilon** [comment]
This is indeed a bit icky but not icky enough to warrant a change at this time.
