### ISSUE TITLE
Should resource filters affect model binding and validation?

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4644]
Wondering if we should make resource filters more powerful...

The factories and providers used for model binding and validation are locked-in (i.e. stored as arrays in `readonly` fields) before the filter pipeline executes. This means resource filters, though they run before model binding, cannot change what model binding or validation do. Resource filters and action filters can temporarily change e.g. `MvcOptions.ValidatorProviders` but that will not even affect `TryUpdateModelAsync()` and `TryValidate()` since the `ControllerContext` is now instantiated in the `FilterActionInvoker` constructor.

Input formatters are even more constrained. The actual formatter instances are locked-in before the filter pipeline starts executing.

@rynowak recently did work (#4531) to avoid creation of value providers when actions have no parameters. But that didn't enable per-action value provider choices beyond `BindingSource` filtering. The `ControllerContext` remains available only to the `ControllerActionInvoker` and `FilterActionInvoker`.

Further at least some of the providers are not given enough information to change their behaviour on a per-resource basis. For example, `ModelBinderProviderContext` contains information about the parameter (not the full `ParameterInfo`) and its `BindingInfo` but nothing about the action or controller.

**Comment by Eilon** [comment]
Why would you want to change any of these things in a resource filter? What is the scenario?

**Comment by dougbu** [comment]
The scenario may certainly be contrived but I was trying to use a `ComplexTypeModelBinder` subclass to special-case a particular type in a particular controller.

Coming at this the other way, one special thing about resource filters is that they run before model binding and validation. So I asked myself how much they could actually affect model binding and validation. The answer appears to be formatter mappings, short-circuits, and not much more.

**Comment by rynowak** [comment]
> The scenario may certainly be contrived but I was trying to use a ComplexTypeModelBinder subclass to special-case a particular type in a particular controller.

It's not super-contrived, but I'd offer the following two thoughts.
1. You can do this today by writing a different model class - you can pretty much always just write another DTO to solve binding issues in MVC.  Any time we provide another workaround in MVC for writing another DTO, it just gets you to the next clickstop.
2. You can do this today by setting the binder type in application model

**Comment by Eilon** [comment]
Given that we have reasonable solutions to this question, I am closing it.
