### ISSUE TITLE
Default MVC project.json is not taking Areas into consideration for publishing.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4645]
The default template of MVC have a `project.json` with this content:

```
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },
```

If you add an Area, those are not copied when publishing.

I think it's safe to make the default template as:
``` 
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },
```
unfortunatelly, that glob pattern doesn't work.

**Comment by tuespetre** [comment]
For the time being, `Areas/**/*.cshtml` seems to get the job done.

**Comment by emailtowalter** [comment]
Tried this workaround on version 1. Does not seem to work. Any idea?

**Comment by tuespetre** [comment]
@emailtowalter 

This works:

```
  "publishOptions": {
    "include": [
      "**/*.cshtml",
      "web.config",
      "wwwroot"
    ]
  },
```

I don't have the link handy but I recall a team member saying that the default templates are going to start using that pattern.

**Comment by rynowak** [comment]
yes, that's the change we're making to the templates

**Comment by emailtowalter** [comment]
It is sort of not working. when I publish to a folder outside of project foder, none of the folders are copied. But if I use the default location, things work. Should I log a separate issue?

dotnet publish -r ubuntu.14.04-x64 -o ..\..\publish\ubuntu\

**Comment by rynowak** [comment]
@emailtowalter please log an issue on CLI https://github.com/dotnet/cli

**Comment by deathrowe** [comment]
I'm seeing the same thing as @emailtowalter. I created https://github.com/dotnet/cli/issues/3951

**Comment by rynowak** [comment]
This change has now gone into the VS templates and `dotnet new` for 1.0.1
