### ISSUE TITLE
Controllers cannot usefully implement `IOrderedFilter`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4647]
Controllers that are also action or result filters execute with `Order == int.MinValue` for back-compat reasons. This is somewhat counter-intuitive since most other framework-provided filters execute with the default `Order`. But more importantly the only way to change the execution order of these filters involves updating the relevant `ControllerModel.Filters.OfType<ControllerActionFilter>().Order` value or doing the same for `ControllerResultFilter`s. We at least need a `MvcViewOptions` knob setting the default value for these `Order` properties.

Could go further and instantiate controller instances early enough for `DefaultApplicationModelProvider` to add the controller themselves as filters, doing away with the delegation. That would enable controllers to usefully implement `IOrderedFilter`.

Probably also need more documentation since the default execution order of these filters isn't visible w/o looking at the `ControllerActionFilter` / `ControllerResultFilter` code.

**Comment by Eilon** [comment]
Not clear what the scenario is here. There are already easy ways to achieve controlling the order: just create a filter that has the logic you need and apply an order to it.

**Comment by DuaneJackson** [comment]
> There are already easy ways to achieve controlling the order: just create a filter that has the logic you need and apply an order to it.

That doesn't work for Controller level filters as per the docs at http://jakeydocs.readthedocs.io/en/latest/mvc/controllers/filters.html

"The Controller class’s methods always run before and after all filters. These methods are not implemented as IFilter instances and do not participate in the IFilter ordering algorithm"
