### ISSUE TITLE
Try to find a home for code in ModelBindingHelper.GetCompatibleCollection

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4649]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ModelBindingHelper.cs#L739

This code makes use of `Activator.CreateInstance` to create collections of `T`. We can't really avoid the use of `Activator` here (see #4470) because we don't have enough context to do better as this is just a static method. 

We should try to find a smarter way to factor this code to reduce the coupling and provide enough context that we don't have to use `Activator`.

**Comment by javiercn** [comment]
Maybe https://github.com/aspnet/Mvc/issues/4523?

**Comment by Eilon** [comment]
Given that in https://github.com/aspnet/Mvc/issues/4615 we're moving MBH to a `.Internal` namespace, I'm moving this to Backlog.

**Comment by rynowak** [comment]
I don't think there's much value in changing this. Suggest just closing
