### ISSUE TITLE
CS1591 warning if xmlDoc enabled

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#4653]
Originally posted to https://github.com/aspnet/Razor/issues/752

If ```xmlDoc``` is set to true in ```project.json``` for an MVC application using ASP.NET Core 1.0 RC2, then a compiler warning is emitted for ```*.cshtml``` files when opened in Visual Studio. For example:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1591	Missing XML comment for publicly visible type or member '_Page_Views_Shared_Error_cshtml'	API..NETCoreApp,Version=v1.0	.\src\API\Views\Shared\Error.cshtml	1	Active

```

Issue found while migrating [a project](https://github.com/martincostello/api/tree/03e2dd99e566c685703592d7756ba44231201011) from RC1 to RC2 in Visual Studio 2015 Update 2 on Windows 10.

Apologies if this is the wrong repo, if this needs to be in Roslyn as it's compiler-related I'll move it.

**Comment by pranavkm** [comment]
cc @pakrym

**Comment by Eilon** [comment]
We could look at disabling this warning for Razor pages. However, it's probably somewhat uncommon to enable doc comments for an *application*, so not a high priority.

**Comment by pranavkm** [comment]
I couldn't immediately tell where we copy this setting from the project. We skip a couple of options (such as `signKey`). We could choose to ignore this property too since generated docs aren't going to help a great deal.

**Comment by Bartmax** [comment]
@Eilon I think using swagger on api (hence using xml docs) and having mvc in the same app is not that *uncommon* ?

**Comment by martincostello** [comment]
My use case was that I put ```///``` comments on my code members, and then enable XML comment generation so they get a level of validation for completeness/presence by the compiler. It's an approach that's worked OK in .NET Framework. I guess I've more been using the _process_ of generating the XML documentation than the _output_ for this.

Tools like [StyleCop.Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) do a good job of this now as an alternative, but like the comment by @pranavkm above states, it doesn't make much sense to generate them for dynamically produced code.

**Comment by martincostello** [comment]
@Bartmax Great point also. I hadn't thought of that yet as I haven't tried plugging Swagger into ASP.NET Core yet.

**Comment by Eilon** [comment]
@Bartmax ah you're right I hadn't thought of that scenario. We'll definitely look into fixing, just not sure when we will be able to implement the fix.

**Comment by pranavkm** [comment]
@martincostello I scanned through our code and I couldn't find any references to the option that enables documentation validation for Razor views. Are you changing `RazorViewEngineOptions.ParseOptions` to specifically enable this behavior? I couldn't tell from looking at https://github.com/martincostello/api/tree/03e2dd99e566c685703592d7756ba44231201011  but it doesn't look like it's been migrated to rc2 as yet.

**Comment by martincostello** [comment]
@pranakm No, I'm not setting anything specifically on the view engine. The repo is definitely at RC2 as of the latest commit. https://github.com/martincostello/api/commits/master

**Comment by pranavkm** [comment]
Seems to be a tooling thing. The page works fine at runtime but VS seems to be compiling it with `/doc`.
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	CS1591	Missing XML comment for publicly visible type or member '_Page_Views_Home_Index_cshtml'	API..NETCoreApp,Version=v1.0	D:\temp\api\src\API\Views\Home\Index.cshtml	1	Active	The /doc compiler option was specified, but one or more constructs did not have comments.
```
cc @barrytang

**Comment by davidfowl** [comment]
@BillHiebert

**Comment by BillHiebert** [comment]
The doc comments switch is passed to intellisense just like any other compiler option. This allows intellisense to warn about incorrect or missing doc comments. The workaround would be to suppress the error.

**Comment by pranavkm** [comment]
@BillHiebert - there isn't a whole lot of utility in having doc comments for Razor views (the user doesn't have the ability to provide comments for most things in the generated code). Would not passing this flag be a better alternative here?

**Comment by BillHiebert** [comment]
For razor yes, but razor pages share the same intellisense project with the .cs files. If we turn it off for razor we need to turn it off everywhere. Or create a new intellisense project just for razor pages

**Comment by davidfowl** [comment]
@BillHiebert we need a new intellisense project per razor file.

**Comment by pranavkm** [comment]
@martincostello sorry for bumping you around again. Moved this to the Tooling repo - https://github.com/aspnet/Tooling/issues/498 for tracking.
