### ISSUE TITLE
Discussion: `HtmlString` has been moved from `Microsoft.AspNetCore.Mvc.Rendering` => `Microsoft.AspNetCore.Html`

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#4659]
We removed the `HtmlString` class from Mvc and renamed the `HtmlEncodedString` in HtmlAbstractions to `HtmlString`. Mvc now depends on the HtmlAbstractions `HtmlString` that exists under the `Microsoft.AspNetCore.Html` namespace.

If you were using `HtmlString` directly in your Razor views you will now need to add a using statement for `Microsoft.AspNetCore.Html`.

Announcement issue: https://github.com/aspnet/Announcements/issues/178

**Comment by Bartmax** [comment]
What's the label of this issue? RTM?

**Comment by NTaylorMullen** [comment]
@Bartmax Correct.

**Comment by MaximRouiller** [comment]
Or to be more specific: `1.0.0`.

The milestone is on the original issue.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
