### ISSUE TITLE
limited scalability returning JSON due to ArrayPool contention

### ISSUE THREAD

**Issue by nathana1** [aspnet/Mvc#4660]
When running an mvc json benchmark (https://github.com/aspnet/benchmarks/blob/dev/src/Benchmarks/Controllers/HomeController.cs#L22) on a 48 core machine I'm unable to get above 75% cpu with profiles showing a lot of time blocked in Rent and Return in System.Buffers.DefaultArrayPool.

The issue appears to be that the ArrayPool partitions its locks based on buffer size (https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/src/Microsoft.AspNetCore.Mvc.Core/Internal/MemoryPoolHttpResponseStreamWriterFactory.cs#L65) and only one size of buffer is requested from the byte and char pools (https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/src/Microsoft.AspNetCore.Mvc.Core/Internal/MemoryPoolHttpResponseStreamWriterFactory.cs#L65), so all requests will wait on one bucket.

We seem to need another level of indirection/partitioning here, not sure if MVC or the ArrayPool is the best place.

**Comment by rynowak** [comment]
/cc @KrzysztofCwalina @stephentoub @jonmiller

@nathana1 - how many RPS is this running at?

We did some investigations here in the past but didn't encounter a scenario where the contention was significant after making some changes to fix it. https://github.com/dotnet/corefx/issues/7727

**Comment by nathana1** [comment]
This is about 400k rps.

**Comment by Eilon** [comment]
Parking this in post-v1 for now. When we have more data we can figure out when exactly to take a change related to this.

**Comment by rynowak** [comment]
@nathana1 it's probably a good time to start taking a look at this now.

What kind of data do we have that points to the array pool as an issue?

Do we know for sure that we were using the implementation of `ArrayPool<>` with the fix for https://github.com/dotnet/corefx/issues/7727 ? Note that we did **not** ship the fixed version of this in RC2.

**Comment by nathana1** [comment]
This still repro's in the rtm bits.  I'm working on some profiles and I'll send them to you.

**Comment by nathana1** [comment]
Hi @rynowak,

In the various profiles I'm seeing 5-10% spent in spinning in the ArrayPool and the thread time profiles show another 5% spent sleeping in those same locks.

I did a quick and dirty prototype (https://github.com/nathana1/corefx/commit/b5ae2a974c5e129b09bb4eb967d9f8048fff4c53) where I partition the ArrayPool buckets into subbuckets and lock at that level instead, I see throughput go from **330k rps to 460k rps** (and cpu saturation).

/cc @stephentoub @sajaya @sivagms

**Comment by Eilon** [comment]
@rynowak can you follow up with @davidfowl on what we wish to do here?

**Comment by stephentoub** [comment]
Is this still an issue after https://github.com/dotnet/coreclr/pull/8209 ?

**Comment by rynowak** [comment]
Yeah. We should close this.
