### ISSUE TITLE
Multi-trageting basic class library with VS2015

### ISSUE THREAD

**Issue by gzak** [aspnet/Mvc#4662]
Check out the following issue I'm encountering with the package manager: https://github.com/NuGet/Home/issues/2773

I haven't gotten a response yet, so I'm posting it here in case I posted the issue in the wrong place.

**Comment by Eilon** [comment]
The best place is probably the https://github.com/dotnet/cli/issues/ repo, but as I just mentioned in the NuGet issue you linked to, your best bet is to re-try with .NET Core RC2, which was just released yesterday.
