### ISSUE TITLE
Asp.Net project with Build platform x86

### ISSUE THREAD

**Issue by sadjadbp** [aspnet/Mvc#4663]
I have a asp.net project that reference a native dll via Nuget package. This native DLL is only build for x86. I've changed my project.json to set buildOptions
`"platform": "x86"`

But when I build this asp.net project via visual studio, it creates "bin\Debug\net46\win7-x64" as oppose to "win7-x86". If I run the resulting ".exe" file it would crash.

I've tried to use "dotnet build -r win7-x86" and it would create the right folder "bin\Debug\net46\win7-x86"  and then I can run the ".exe" file.

Still cannot test the application in x86 mode.

**Comment by pranavkm** [comment]
Could you file this bug in the CLI repo - https://github.com/dotnet/cli?
