### ISSUE TITLE
unknown keyword platform RC2

### ISSUE THREAD

**Issue by takazm** [aspnet/Mvc#4668]
I have installed the recently release CORE R2 Tooling and created a new project. An attempt to restore packages fails with the above given error.
 Here the command: dotnet restore
 error: TODO: unknown keyword platform
 unknown keyword platform

Any reason why this is happening

**Comment by ivaylokenov** [comment]
Some possible solutions:

1. Check your global.json or projects properties. You may be specifing old runtime.
2. Have you uninstalled all previous versions of .NET CLI (if any)
3. Have you installed the latest NuGet Package Manager Extension? Available here: https://dist.nuget.org/visualstudio-2015-vsix/v3.5.0-beta/NuGet.Tools.vsix
4. Check your NuGet feeds - they should be the official ones.

**Comment by davidfowl** [comment]
You have an old version of the RC2 tooling. Run `dotnet --version` on the command line to see what version is being used.

**Comment by takazm** [comment]
@davidfowl I downloaded the tooling installation file about 5 hours ago based on the link provided on http://dot.net page.

**Comment by Eilon** [comment]
@takazm can you share your project.json file, and if you have any particular NuGet.config file that you're using?

@pakrym @anurse @pranavkm any idea what this error might be?

**Comment by pakrym** [comment]
'type:platform'  vs 'target:platform' should be the first one.

**Comment by pranavkm** [comment]
@takazm , can you run `dotnet --version`. It's quite likely you have an older dotnet CLI installed somewhere on your disk.

**Comment by takazm** [comment]
running dotnet --version gives me the following output:

.NET Command Line Tools (1.0.0-beta-001598)                                                                                                                                                                                                                                                                                     Product Information:                                                                                                                                             Version:     1.0.0-beta-001598                                                                                                                                  Commit Sha:  7582649f88                                                                                                                                                                                                                                                                                                        Runtime Environment:                                                                                                                                             OS Name:     Windows                                                                                                                                            OS Version:  10.0.14342                                                                                                                                         OS Platform: Windows                                                                                                                                            Runtime Id:  win10-x64 
I have also noticed that when I create a new project using VS or through dotnet new; when I open the project it says dotnet is not installed but I did install and can see the files in the folder specified in the path

**Comment by takazm** [comment]
my global.json looks like this:

{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview1-002702"
  }
}

and the project.json:


{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

**Comment by pranavkm** [comment]
The CLI version is pretty ancient. I'd recommend uninstalling older versions of the CLI (check Control Panel -> Programs & Features) and also remove anything under `%LocalAppData%\Microsoft\dotnet`. You can install the CLI from https://go.microsoft.com/fwlink/?LinkID=798398. Odd that the tooling you installed didn't install the right CLI with it.

**Comment by takazm** [comment]
trying to uninstall old version but, i dont see %LocalAppData%\Microsoft\dotnet or the entry in programs in control panel (see image)
![dot](https://cloud.githubusercontent.com/assets/5674007/15396409/5031b9ec-1ddc-11e6-987e-d77850e57c52.PNG)

**Comment by pranavkm** [comment]
Can you run `where dotnet` to figure out where it's picking up the version of dotnet you have?

**Comment by takazm** [comment]
i did run that one and its in \program files\dotnet
Do i just delete the files or have to do a proper uninstall of which i dont see an uninstaller

**Comment by pranavkm** [comment]
Removing `C:\Program Files\dotnet` from your path might be an alternative to deleting it. Once done, reinstall the CLI from https://go.microsoft.com/fwlink/?LinkID=798398 for good measure.

**Comment by takazm** [comment]
Did install just fine on separate my personal laptop and seems to have no issue at all. I will have to uninstall everything including VS and try again. Thanks guys

**Comment by Eilon** [comment]
@takazm I'm glad you got it working. There were at a few points in time some issues with the installers, especially for those who installed nightly builds and then the official release. So hopefully it was just a one-time issue.
