### ISSUE TITLE
AssemblyLoadContext.Default.LoadFromAssemblyPath doesn't load assembly with dot in name

### ISSUE THREAD

**Issue by DmitrySikorsky** [aspnet/Mvc#4669]
Doesn't work:
AssemblyLoadContext.Default.LoadFromAssemblyPath(@"C:\X.Y.dll");

Works:
AssemblyLoadContext.Default.LoadFromAssemblyPath(@"C:\XY.dll");

**Comment by pranavkm** [comment]
Please file this at https://github.com/dotnet/coreclr/issues.
