### ISSUE TITLE
Template home page has a UTF-8 BOM at the beggining

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#4671]
_From @AustinWinstanley on May 18, 2016 6:25_

It works fine in Edge and Firefox.

Every page in Chrome is messed up with the unicode character &#65279; being inserted at the top causing the <head> content to be inserted in the body. It happens on all pages. Tested first on an upgraded site and then on a default web project created through Visual Studio.

[Referred from Core](https://github.com/dotnet/core/issues/94)

![untitled](https://cloud.githubusercontent.com/assets/4576933/15349270/377ea46e-1c97-11e6-955d-97f13c797a55.png)

_Copied from original issue: aspnet/KestrelHttpServer#838_

**Comment by Tratcher** [comment]
_From @AustinWinstanley on May 18, 2016 6:43_

Running through the command line does not have the problem.

`dotnet restore`
`dotnet run`

![untitled](https://cloud.githubusercontent.com/assets/4576933/15349636/d7ddbf92-1c99-11e6-8702-5d720906ed1f.png)

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/StaticFiles/issues/130

**Comment by Tratcher** [comment]
I've been able to repro this. The site is sending a BOM at the beginning:
```
???<!DOCTYPE html>
<html>
<head>
```
This happens for both Kestrel and IIS Express. It's only visible in Chrome when using IIS Express, and I think this is because IIS Express is adding dynamic gzip compression and Chrome is handling it differently.

@rynowak why are there BOMs coming from MVC / Razor?

**Comment by Tratcher** [comment]
_From @halter73 on May 18, 2016 22:2_

@Tratcher should we move this issue again? As much as @davidfowl might object it doesn't appear that it's a Kestrel issue :wink:

**Comment by Tratcher** [comment]
_From @rynowak on May 18, 2016 22:6_

@Tratcher - I'll come by to see your repro - Everywhere I can think of in MVC we use `HttpResponseStreamWriter` which doesn't write a BOM https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/HttpResponseStreamWriter.cs#L14

**Comment by benaadams** [comment]
BOM in file getting directly piped to output?

**Comment by muratg** [comment]
:eyes:

**Comment by Eilon** [comment]
Hmm, weird. It looks like a BOM from a partial view (or something?) is getting rendered in the output, which seems wrong. At most the BOM from the outer-most layout (or content) page should get rendered, but not from any child-layout, child-page, or partial.

**Comment by AustinWinstanley** [comment]
@Eilon It doesn't seem (to me) to be a BOM from a partial. At least not one that is being introduced in VS or VS Code. (I don't know if it could be some partial issue with the engine, although it is reproducible in IIS Express and Kestrel).

I confirmed all my files were encoded in UTF-8 and reproduced it with the bare minimum of markup in both _Layout and my home Index all written from scratch by hand In Visual Studio with a brand new file I initiated as a text file and changed to cshtml, just to be sure. This was also the case in a partial created directly from VS. I then used Notepad++ to convert the files to UTF-8 also just to make sure after rewriting them from scratch. This was reproducible with a brand new web project in VS.

However, I created a brand new project using ``dotnet new`` and VS Code creating the project from scratch and the BOM did not show up. I'm attaching it here. I'm not sure what is being added with the VS template or VS in general, but this project works fine with just VS Code.

To run:

``dotnet restore``
``dotnet build``
``dotnet run``

Open Chrome
Navigate to http://localhost:5000


[tester.zip](https://github.com/aspnet/Mvc/files/271890/tester.zip)

**Comment by Tratcher** [comment]
The image is misleading, the BOM is at the start of the stream, it just confuses chrome.

**Comment by Eilon** [comment]
Ok we'll have @dougbu take a look.

**Comment by pakrym** [comment]
Caused by: https://github.com/aspnet/BrowserLink/issues/24

**Comment by cyclone321** [comment]
also getting this after upgrading, any feedback ?
also the caused by link provided by @pakrym is 404'ing.

**Comment by dougbu** [comment]
The repo @pakrym referenced is currently private. In any case, the workaround is to remove `app.UseBrowserlink()` from your `Startup` code.
