### ISSUE TITLE
partial controller not supported

### ISSUE THREAD

**Issue by xyting** [aspnet/Mvc#4675]
The following code will throw 
_Microsoft.AspNet.Mvc.Infrastructure.AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:
Top.SaaS.Contracts.Api.Controllers.ContractController.GetApply
Top.SaaS.Contracts.Api.Controllers.ContractController.GetApply
at Microsoft.AspNet.Mvc.Infrastructure.DefaultActionSelector.SelectAsync(RouteContext context)_

POSTMANT GET http://localhost:5000/api/contract/apply/1

``` C#
[Route("api/[controller]")]
    public partial class ContractController : Controller {
        [HttpGet("apply/{id}")]
        public async Task<ContractApplyDetailModel> GetApply(int id) {
            var query = new ContractQuery(_unitOfWork, _apiUrls, _mapper);
            return await query.GetApplyAsync(id);
        }
}
```

``` C#
[Route("api/[controller]")]
    public partial class ContractController : Controller {
        [HttpGet("{id}")]
        public async Task<ContractModel> Get(int id) {
            var query = new ContractQuery(_unitOfWork, _apiUrls, _mapper);
            return await query.GetAsync(id);
        }
}
```

**Comment by davidfowl** [comment]
Partial classes are just a C# compiler feature. It's actually a single class at runtime. You don't need the [Route] attribute declared twice on the same controller.

**Comment by xyting** [comment]
@davidfowl Makes sense. Thanks for the answer!
