### ISSUE TITLE
Having a hard time to understand how to implement TagHelper based on the output of another TagHelper.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4679]
something like:

```
<img src="A"/>
TagHelper1: If (src == "A") src = "B";
TagHelper2: if (src == "B") src = "C";
```

expected ouput:

```
<img src="C"/>
```

I tried different mixes of context/output but I can't find to get a real understanding on how does it works.
I also experienced some weird behavior overriding the Order property.

I'm looking for some guidance on the lifecycle of taghelpers and how a developer have access to properties/values in the way. Something that will help me understand how to make the pseudo snippet above.

**Comment by dougbu** [comment]
The `TagHelperOutput` passed into tag helpers targeting the same element is shared. So, as long as `TagHelper1` runs before `TagHelper2`, the number two will see what number one changed.

Since the order tag helpers run is normally arbitrary, you may need to override the `Order` property in one helper or the other.

**Comment by Bartmax** [comment]
That definitely helped @dougbu ! I found out that if no tag helper run before, the output is empty and I should access the Src property or context.

So the recommended approach, for a tag helper that you may not know if it will be the only and/or first to process a tag, should be something like:

TryToGetFromOutput and if it's empty, get it from context / property?

I also found out that ~ tag helper run at -9999 so I had to have less than that if I want my tag helper to run before the MVC one. I will take a closer look at the ~ tag helper to see how it manages stuff. I'm worried that if I run a tag helper before the ~, then the ~ can produce undesired output.

I will keep doing some tests and let you know how it goes Thanks!

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
