### ISSUE TITLE
Research what is the default JsonContractResolver

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#468]
We use JsonContractResolver to handle required properties in special ways. I've written code where I replace the contract resolver with the CamelCasePropertyNamesContractResolver without realizing this was being affected. It might be useful to determine what this contract resolver does and if there's a better way to handle what it does. 

| 140 | 10240 | Reported By: Pranav K |

**Comment by kichalla** [comment]
One of the settings that JsonContractResolver is changing is how it behaves with `Required` data annotation attribute. It sets the setting called `Required` to `AllowNull` which states `The property must be defined in JSON but can be a null value`. For example, following scenario is broken currently without this:

Value types having `Required` annotation do not trigger model state errors. This gets triggered in case of form-url-encoded correctly but not in Json. (xml formatters do not understand this annotation so that's a different story)
```c#
public class Person
{
	[Required]
	public int Id { get; set; }

	[Required]
	public string Name { get; set; }
}
```

![image](https://cloud.githubusercontent.com/assets/6559784/6077406/6192b376-ada3-11e4-9c4a-67ec45a05328.png)

@harshgMSFT @pranavkm

**Comment by kichalla** [comment]
Just FYI...if we decide to fix going by the ContractResolver approach, then as you know it would only work for Json and not for Xml. 

In Web API, we had something called `InvalidModelValidatorProvider` which used to make a requirement that if a value type is decorated with `Required` attribute, then it must also be decorated with `DataMember(IsRequired=true)` attribute. 

The scenario behind this was that Web API used to support Json and Xml formatters out of the box. It was considered a security issue if validation got triggered when posting via Json but not via Xml. In MVC 6, Xml is not exactly out of the box as users have to explicitly add it, so not sure if we should consider this scenario.

That said, in Web API `InvalidModelValidatorProvider` used to be added out of the box but it proved to be an annoyance to users as some users would be working only with Json or bound from Uri but are forced to add reference to `System.Runtime.Serialization` and decorate with `DataMember(IsRequired=true)` attribute, so it was later removed from default validation providers list.

Snippet from the following reference:
```c#
// Validate that value-typed properties marked as [Required] are also marked as [DataMember(IsRequired=true)]
// Certain formatters may not recognize a member as required if it's marked as [Required] but not [DataMember(IsRequired=true)]
// This is not a problem for reference types because [Required] will still cause a model error to be raised after a null value is deserialized
if (metadata.ModelType.IsValueType && attributes.Any(attribute => attribute is RequiredAttribute))
{
    if (!DataMemberModelValidatorProvider.IsRequiredDataMember(metadata.ContainerType, attributes))
    {
        yield return new ErrorModelValidator(validatorProviders, Error.Format(SRResources.MissingDataMemberIsRequired, metadata.PropertyName, metadata.ContainerType));
    }
}
```
Reference:
http://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Http/Validation/Providers/InvalidModelValidatorProvider.cs

**Comment by kichalla** [comment]
Commits:
c276ddaa39735a8826b1da27b84dd793865a65e4 
f737083c946137dd9a411759c3ca83856a0083a2
