### ISSUE TITLE
[RC2] web page flashes white blank on load

### ISSUE THREAD

**Issue by jemala** [aspnet/Mvc#4684]
I just upgraded my project from RC1 to RC2 and now it has a strange behaviour. Everytime a new page is loading, the browser shows a white blank page for half a second (until the new page is loaded). My webpage has a dark background, that's why it really doesn't look good.

This problem occurs on Google Chrome (latest version) but not on Firefox. I am 99% sure it's caused by RC2, because I didn't have this problem with RC1.

**Comment by Eilon** [comment]
Can you run your browser's network trace tools to perhaps see where the time is being spent? Is it network? Rendering? JavaScript? CSS? It might be good to compare the two browsers where you're seeing the different behavior. That might help narrow it down.

**Comment by jemala** [comment]
Hi @Eilon , I just used the network trace tools. The difference between RC1 and RC2 seems to be the following:

On RC1, the current page is still shown when the new page loads. After loading a few stuff, let's call this time X, it changes to the new page, which then finishes loading.

On RC2, the current page switches immediately to the new page, showing a blank page. Then when it reaches time X, the new page is shown and finishes loading.

Here is a screenshot where i cancelled loading shortly before time X was reached:

![image](https://cloud.githubusercontent.com/assets/18643746/15422136/3081012a-1e77-11e6-87b7-4af6cdef15b9.png)

**Comment by jemala** [comment]
The problem can be reproduced very easily:

In Visual Studio create a new Asp Net Core Web Application. Then start the page in Google Chrome and hit the "About"-Button several times. You will notice how for a very short amount of time the page is totally white, causing an unpleasant experience.

**Comment by Eilon** [comment]
Hmm, well, at a fundamental level, the default background in every browser I know of is white, so while it's loading "the next page" it's reasonable to expect there to be some default (i.e. white) background. But, I'm not sure why that would be different between RC1 and RC2...

**Comment by jemala** [comment]
No, I don't think it is reasonable. Normal behaviour sould be to keep the current background color at least until the background color of the next page is loaded, whereby a seamless toggle can happen. Otherwise we have this disturbing white flash.
As I mentioned before, in Firefox this doesn't happen, the "toggle" works seamless.

**Comment by Eilon** [comment]
@jemala this is regular browser behavior, I don't know if there's much that a server framework can do about it. The browser decides when to redraw the background of the page. It might do it immediately after the user clicks, it might do it the moment the server responds to the request (but before sending any data back), or it might wait until it has downloaded all of the destination's HTML, CSS, and JavaScript.

**Comment by jemala** [comment]
@Eilon I agree. It's just strange that this behaviour appears in RC2 but not RC1. I'll do some more investigation and close this issue. Thank you for your help!

**Comment by Eilon** [comment]
@jemala thanks I understand. I definitely agree it's unusual behavior to see that kind of change. Perhaps ASP.NET Core RC2 starts sending a response to the browser faster, so the browser "prepares itself" by clearing the rendering of the page... that's why I was curious with the network trace. I'm curious if you have a comparison of RC1 and RC2 behavior in the affected browser. Perhaps we'll see some difference there that would explain it. (Though, even if we learn that, I'm still not sure there's anything we could reasonably do.)

**Comment by jemala** [comment]
@Eilon I wasn't able to reproduce this problem when the webpage is deployed, that's why I am fine with this issue now. I think it has something to do with running the webpage locally over Visual Studio.

**Comment by rynowak** [comment]
It's possible that this is caused by https://github.com/aspnet/Mvc/issues/4671 The root cause of that issue is that browserlink is inserting a BOM and causing chrome to do wierd things.

@jemala have you tried removing browserlink?

**Comment by jemala** [comment]
@rynowak I just tried it out and removed app.UseBrowserLink(); and the problem still occurs. But as I mentioned before, I am finde with it, since production environment on my server doesn't have this issue.

**Comment by jemala** [comment]
@rynowak You got it! I removed app.UseBrowserLink(); and now everything is working like a charm!
