### ISSUE TITLE
 cultureinfo in Views is always "en-Us" despite in controller CurrentCulture is different. I'm using rc2

### ISSUE THREAD

**Issue by NGancevich** [aspnet/Mvc#4692]
I have the following supported cultures. 

```c#
var supportedCultures = new CultureInfo[]
            {
                new CultureInfo("be-By"),
                new CultureInfo("en-Gb"),
                new CultureInfo("ru-Ru"),
                new CultureInfo("uk-UA"),
                new CultureInfo("pl-PL"),
        
            };

            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                SupportedCultures = supportedCultures,
                SupportedUICultures = supportedCultures,
                
                RequestCultureProviders = new List<IRequestCultureProvider>
                {
                    new QueryStringRequestCultureProvider { },
                    new CookieRequestCultureProvider { CookieName = "CULTURE"},
                    
                },
                
                //DefaultRequestCulture = new RequestCulture(new CultureInfo("en-Gb"))

            });
```

In controller is see {be-BY} for System.Threading.Thread.CurrentThread.CurrentCulture but View displays {en-Us}

**Comment by Jupakabra** [comment]
Hi, any news on this? I can't get my web site to work in any other languages in RC2.

**Comment by Eilon** [comment]
@pranavkm can you investigate?

**Comment by Muchiachio** [comment]
Seems like setting the culture inside a controller, doesn't get shared between the middleware or views.
While setting it in middleware before it get's processed by the controller works.

**Comment by NGancevich** [comment]
So what is the way to get this fixed?

**Comment by Eilon** [comment]
@NGancevich we are investigating. In the meantime you could probably work around this by saving the current culture in the controller (e.g. in a filter), and then in the view set that culture back again.

**Comment by pranavkm** [comment]
Sorry for the delay - I'm going to look into this today.

**Comment by pranavkm** [comment]
@NGancevich \ @Muchiachio - is this with an application targeting `net4x` (desktop)?

**Comment by Muchiachio** [comment]
@pranavkm yes, I'm targeting `net46`.

**Comment by Muchiachio** [comment]
@pranavkm I created a repro solution [here](https://github.com/Muchiachio/Loc), and while I did that I saw that localization works with `net452`, but doesn't with `net46` for some reason.

**Comment by NGancevich** [comment]
My project is targeting net452 and there is bug.  You can add the following:

- app.UseRequestLocalization
- AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
- AddDataAnnotationsLocalization(); 

It can happen if we attaching these functionality

**Comment by NGancevich** [comment]
I have found details for the bug.
 cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddRange(sqlParams);

            try
            {
                await cmd.Connection.OpenAsync();
                var sqlReader = await cmd.ExecuteReaderAsync();

during the last operation (cmd.ExecuteReaderAsync()) it set culture to en-us for global context!

**Comment by NGancevich** [comment]
Changing await cmd.ExecuteReaderAsync() to  cmd.ExecuteReader solves the issue.

**Comment by Eilon** [comment]
Seems like something @stephentoub / @davidfowl would know more about. Async not preserving the thread culture perhaps?

**Comment by davidfowl** [comment]
This only works on .NET 4.6 but it should work on .NET Core out of the box.

**Comment by pranavkm** [comment]
@Muchiachio thanks for the repro. The issue is pretty easy to understand given how Mvc action execution happens. I'll have a talk with @davidfowl and @DamianEdwards to figure out what we need to do to address this.

**Comment by rynowak** [comment]
> Seems like setting the culture inside a controller, doesn't get shared between the middleware or views. While setting it in middleware before it get's processed by the controller works.

This is part of how async-local/call-context work. The mechanism used to propagate culture in .NET Core only applies to the current call chain.

Setting the culture inside a resource filter would apply to both the action and view.

**Comment by Muchiachio** [comment]
Thanks @rynowak using `IResourceFilter` works, I was afraid it will not contain `RouteData`, but it does :relieved:

**Comment by NGancevich** [comment]
Any Entityframework await context in asp.net core changes View and Controller culture to en-us.

For example

public async Task<string> GetLanguageIdDefaultAsync(string host)
        {
            return await ctx.Sites
                .Where(o => o.Domain == host)
                .Select(o => o.DefaultLangualgeId).FirstOrDefaultAsync();
        }


will set global culture to en-Us

**Comment by pranavkm** [comment]
@NGancevich - could you include more of your code? Where does your method get called from?

**Comment by NGancevich** [comment]
For example:

public async Task<IActionResult> Index()
        {
            string currentLanguageId = await GetCurrenyLanguageIdAsync();
            string currentCountryId = await GetCurrentCountryIdAsync();

            ViewData["LanguageId"] = currentLanguageId;
            //_logger.LogInformation(1, _htmlLocalizer["Hello"].Value);
            //_logger.LogInformation(1, _localizer["Hello"]);

            try
            {
                List<Tuple<string, string>> topRoutes = await _rp.MostPopularRoutesAsync(currentCountryId, currentLanguageId, 21) as List<Tuple<string, string>>;
                ViewData["TopRoutes"] = topRoutes;
            }
            catch (Exception ex)
            {
                _logger.LogError(1, "Error getting top routes", ex);
                //throw;
            }

            return View();
        }

  private async Task<string> GetCurrenyLanguageIdAsync()
        {
            

            string languageId;
            if (Request.Cookies.ContainsKey(CookieHelper.LanguageIdCookieName))
            {

                //byte.TryParse(Context.Request.Cookies["currencyId"], out currencyId);
                languageId = Request.Cookies[CookieHelper.LanguageIdCookieName];

            }
            else
            {
                string host = Request.GetUri().Host;
                languageId = await _rp.GetLanguageIdDefaultAsync(host);
            }

            return languageId;
        }

        private async Task<string> GetCurrentCountryIdAsync()
        {
            string countryId;
            if (Request.Cookies.ContainsKey(CookieHelper.CountryIdCookieName))
            {
                countryId = Request.Cookies[CookieHelper.CountryIdCookieName];
            }
            else
            {
                string host = Request.GetUri().Host;
                countryId = await _rp.GetCountryIdDefaultAsync(host);
            }

            return countryId;
        }

        private async Task<byte> GetCurrentSiteIdAsync()
        {
             string host = Request.GetUri().Host;
            var result = await _rp.GetSiteIdDefaultAsync(host);
            return result;


        }

**Comment by pranavkm** [comment]
@NGancevich where are you setting the culture in any of this? Or does that come from the Localization middleware?

**Comment by NGancevich** [comment]
{
                new CultureInfo("be-BY"),
                new CultureInfo("en-GB"),
                new CultureInfo("ru-RU"),
                new CultureInfo("uk-UA"),
                new CultureInfo("pl-PL"),
        
            };

            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture(new CultureInfo("en-GB")),
                SupportedCultures = supportedCultures,
                SupportedUICultures = supportedCultures,
                
                RequestCultureProviders = new List<IRequestCultureProvider>
                {
                    new QueryStringRequestCultureProvider { },
                    new CookieRequestCultureProvider { CookieName = CookieHelper.CultureCookieName},
                    //new CustomRequestCultureProvider()
                    
                },
                
                

            });



----

 services.AddMvc()
                .AddJsonOptions(opts => { })
                .AddMvcOptions(opts =>
                {;
                    opts.Filters.Add(typeof(DomainConfigurationActionFilter));
                    opts.CacheProfiles.Add("ImagesProfile", new CacheProfile
                    {
                        Duration = 1 * 24 * 60
                    });
                    //opts.ModelBinders.Add(new BaseTypeBinder());
                    //opts.
                })
                .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
                .AddDataAnnotationsLocalization(); 

---

public class DomainConfigurationActionFilter : ActionFilterAttribute
    {

        private readonly IBusRepository _rp;

        public DomainConfigurationActionFilter(IBusRepository rp)
        {
            _rp = rp;
        }

        public override void OnActionExecuting(ActionExecutingContext actionContext)
        {
            var request = actionContext.HttpContext.Request;
            var response = actionContext.HttpContext.Response;

            string host = request.GetUri().Host;

            if (!request.Cookies.ContainsKey(CookieHelper.LanguageIdCookieName) || !request.Cookies.ContainsKey(CookieHelper.CultureCookieName))
            {

                LanguageModel language = Task.Run(async () => await _rp.GetLanguageDefaultAsync(host)).Result;

                response.Cookies.Append(CookieHelper.LanguageIdCookieName, language.LanguageId,
                    new CookieOptions {Expires = DateTime.Today.AddYears(1)});
                response.Cookies.Append(CookieHelper.CultureCookieName, $"c={language.CultureInfo}|uic={language.CultureInfo}",
                    new CookieOptions {Expires = DateTime.Today.AddYears(1)});


                response.Redirect(request.GetUri().PathAndQuery);

#if NET452
                //Thread.CurrentThread.CurrentCulture = new CultureInfo(language.CultureInfo);
                //Thread.CurrentThread.CurrentUICulture = new CultureInfo(language.CultureInfo);

#else
                //CultureInfo.CurrentCulture = new CultureInfo(language.CultureInfo);
                //CultureInfo.CurrentUICulture = new CultureInfo(language.CultureInfo);
#endif

                //Thread.CurrentThread.CurrentCulture = new CultureInfo(language.CultureInfo);
                //Thread.CurrentThread.CurrentUICulture = new CultureInfo(language.CultureInfo);
            }
//            else
//            {
//                //var cultureInfo = request.Cookies[CookieHelper.CultureCookieName];
//                string cultureText = request.Cookies[CookieHelper.CultureCookieName];
//                string cult = cultureText.Substring(cultureText.IndexOf("=") + 1, 5);

//#if NET452
//                Thread.CurrentThread.CurrentCulture = new CultureInfo(cult);
//                Thread.CurrentThread.CurrentUICulture = new CultureInfo(cult);

//#else
//                CultureInfo.CurrentCulture = new CultureInfo(cultureInfo);
//                CultureInfo.CurrentUICulture = new CultureInfo(cultureInfo);
//#endif
//            }


            //initialize countryId for host
            if (!request.Cookies.ContainsKey("CountryId"))
            {
                string countryId = Task.Run(async () => await _rp.GetCountryIdDefaultAsync(host)).Result; 
                response.Cookies.Append("CountryId", countryId, new CookieOptions { Expires = DateTime.Today.AddYears(1) });
            }


            if (!request.Cookies.ContainsKey(CookieHelper.CurrencyIdCookieName) 
                || !Task.Run(async () => await _rp.IsCurrencyFoundAsync(request.Cookies[CookieHelper.CurrencyIdCookieName])).Result)
            {

                string currencyId = Task.Run(async () => await _rp.GetCurrencyIdDefaultAsync(host)).Result;
                response.Cookies.Append(CookieHelper.CurrencyIdCookieName, currencyId, new CookieOptions { Expires = DateTime.Today.AddYears(1) });
              
            }


            
     
            base.OnActionExecuting(actionContext);
        }

**Comment by pranavkm** [comment]
@NGancevich are you running your app on desktop (net452)? If so, you must change it to run on NET46 for `CultureInfo` to propogate between async calls. I couldn't repro the issue outside of this.

**Comment by NGancevich** [comment]
I can't find way on visual studio to change .net version in project from 452 to 46. Could you help?

**Comment by pranavkm** [comment]
@NGancevich - update the framework node in your project.json to `net46` from `net452`. You'd also have to update your `ifdef`s to `NET46`.

**Comment by NGancevich** [comment]
Changing to ne46 resolved a lot of issue but I still can't set Culture for first time (when cookie isn't set yet).  I'm trying to do this the following way

public override void OnActionExecuting(ActionExecutingContext actionContext)
        {
            var request = actionContext.HttpContext.Request;
            var response = actionContext.HttpContext.Response;


            string host = request.GetUri().Host;

            if (!request.Cookies.ContainsKey(CookieHelper.LanguageIdCookieName) || !request.Cookies.ContainsKey(CookieHelper.CultureCookieName))
            {

                LanguageModel language = Task.Run(async () => await _rp.GetLanguageDefaultAsync(host)).Result;

                response.Cookies.Append(CookieHelper.LanguageIdCookieName, language.LanguageId,
                    new CookieOptions {Expires = DateTime.Today.AddYears(1)});
                response.Cookies.Append(CookieHelper.CultureCookieName, $"c={language.CultureInfo}|uic={language.CultureInfo}",
                    new CookieOptions {Expires = DateTime.Today.AddYears(1)});



                CultureInfo.CurrentCulture = new CultureInfo(language.CultureInfo);
                CultureInfo.CurrentUICulture = new CultureInfo(language.CultureInfo);

For instance depending on domain name I try to set culture pl-Pl from db. But it doesn't effect in Views. 
The second get request I get expected info as cookies already set

**Comment by pranavkm** [comment]
Like @rynowak said in https://github.com/aspnet/Mvc/issues/4692#issuecomment-223671462, you would need either a middleware or a resource filter to do this.

**Comment by NGancevich** [comment]
I have implemented this in resourcefilter and it's working now. Thanks!

**Comment by dougbu** [comment]
@pranavkm is Investigate the correct label for a closed issue?

**Comment by pranavkm** [comment]
@dougbu I'm not sure. What's the write label here?

**Comment by dougbu** [comment]
Reads like "by design" to me. But I'm not whether to write that that's right.
