### ISSUE TITLE
.NET Framework libraries in CoreFx

### ISSUE THREAD

**Issue by kjanshair** [aspnet/Mvc#4693]
Greetings, 

I'm using RC1 in production for my web application and it uses .NET Mail Service assemblies for sending mails using **MailMessage** and **SmtpClient**. These are only available on .NET Framework, when I'll get these libraries as a part of CoreFx so that I can port my application on .NET Core and avoid using 3rd party libraries.

Regards,

**Comment by pranavkm** [comment]
This would be a question for https://github.com/dotnet/corefx. Possibly a dupe of https://github.com/dotnet/corefx/issues/1006
