### ISSUE TITLE
FormUrlEncodedMediaTypeFormatter doesn't work with HttpClient Model Binding.

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Mvc#4694]
https://github.com/aspnet/Mvc/blob/1f93977729f9998c3971567268e025ef4ae76ed6/test/Microsoft.AspNetCore.Mvc.FunctionalTests/WebApiCompatShimBasicTest.cs#L66

I am using a web service that implements FormUrlEncoded responses.
I saw FormUrlEncodedMediaTypeFormatter was missing from the above test for core but I know my Actions in my Controller do automatic binding to FormUrlEncoded data.
Shouldn't the automatic model binding in HttpClient should have parity with an MVC action.

I was looking to use FormUrlEncoded model binding with HttpClient like this.
(ignore poor use of async its just testing).

```
 using (var client = new HttpClient())
            {
                using (var repeatResponse = client.PostAsync(_config["SomeProvider:GatewayDirectUrl"], byteContent).Result)
                {
                    if (!repeatResponse.IsSuccessStatusCode)
                    {
                        // throw an appropriate exception
                    }

                    var result = repeatResponse.Content.ReadAsAsync<RepeatTransactionResponse>().Result;
                }
            } 

            return View();
```

AFAIK ReadAsAsync default constructor uses the default set of formatters.  But FormUrlEncoded doesn't seem to be supported.

**Comment by Eilon** [comment]
@mikes-gh I want to make sure I understand this: are you asking about the formatters used by HttpClient *on the client* or the formatters used by MVC (and the Web API shim) *on the server*?

In ASP.NET Core as far as I know there's no connection between those. In Web API 1.x/2.x the same formatters were compatible on both (though they weren't necessarily all enabled in both).

**Comment by mikes-gh** [comment]
@Eilon You're right.  The post is not that clear

Perhaps if I repost 2 simple questions

- Is HttpClient  the new way of consuming web services?
- Does HttpClient have any functionality to help with model binding FormUrlEncode data from a response?  I have resolved this by using a UrlDecode -> Dictionary -> Object methodology but can't help thinking I'm reinventing the wheel here.

**Comment by Eilon** [comment]
Well I'd say that `HttpClient` is both the old way *and* the new way 😄 It used to work great and it still does!

Can you clarify the second question? Are you trying to parse the result of an HttpClient call into an object graph? Ultimately there's never any "model binding" on the client side because "model binding" is specifically an MVC feature, and we don't have plans to enable it anywhere else. On the client side generally all you have is either serializers (e.g. Json.NET), or custom code that does whatever.

**Comment by mikes-gh** [comment]
Yes you are right I was expecting model binding. don't know why.  Anyway I used a url to  dictionary to class mapping methodology.  It just seemed like I was reinventing the wheel.
I would have thought model binding when consuming a web service would be a common requirement.

**Comment by mikes-gh** [comment]
>  Ultimately there's never any "model binding" on the client side because "model binding" is specifically an MVC feature, and we don't have plans to enable it anywhere else. On the client side generally all you have is either serializers (e.g. Json.NET), or custom code that does whatever.
@Eilon I am not sure you are right on that one.  By The way 

http://stackoverflow.com/questions/9874808/webapi-httpclient-response-string-model-binding

**Comment by davidfowl** [comment]
He's right

**Comment by Eilon** [comment]
@mikes-gh, there's an MVC/Web API feature called "model binding" and uses the various `IModelBinder` interfaces - that's the one I'm talking about.

Otherwise there are formatters/serializers, which are in some sense "simpler" because they are "just" persistence formats. Model binding is unlike formatting/serialization in that it can get data from multiple sources, has extensible behavior for both object creation and validation, and so forth.

But ultimately I'm just saying that this exact feature doesn't exist "on the client."

**Comment by mikes-gh** [comment]
Ah OK sorry I am still confused with the difference between model binding and de-serialization.  Sorry about that 😊 
I guess we are back to the original point that `FormUrlEncodedMediaTypeFormatter` doesn't seem to exist on dotnet core.  Is that something we should add?

**Comment by javiercn** [comment]
@eilon @mikes-gh I think you should be able to use the old Web API formatters on the client side. They live in a portable class library on System.Web.Http.Formatters. The Web API compat shim uses them on the server side if I recall correctly, you should be able in theory to reference the nuget package on your application and use them

**Comment by Eilon** [comment]
@mikes-gh if you're using regular old HttpClient, you can use @javiercn 's suggestion and use the pre-existing formatters from Web API. They work just as well as they already have. The one place where it falls a bit short is that the pre-existing formatters don't directly support the new `netstandard` system, but I'm guessing with the right `import` statements in `project.json` they'll just work. We do plan to update it to `netstandard` but that work isn't yet scheduled.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
