### ISSUE TITLE
ASP.NET Core Web Application template not running properly

### ISSUE THREAD

**Issue by gokalpi** [aspnet/Mvc#4695]
I installed Visual Studio 2015 CE and .NET Core 1.0.0 RC2 - VS 2015 Tooling Preview 1 and created a new web project using ASP.NET Core Web Application template. When I want to run it in Visual Studio 2015, it waits for a time and HTTP Error 502.3 - Bad Gateway error comes up.

When I run the application (dotnet run) in Command Prompt, it is working properly.

dotnet --info output is as follows:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by javiercn** [comment]
@gokalpi What happens if you press F5 a few seconds later, does the page come up?

**Comment by Eilon** [comment]
Moved to https://github.com/aspnet/Tooling/issues/513.
