### ISSUE TITLE
Building a .NET Core project not working

### ISSUE THREAD

**Issue by chinookproject** [aspnet/Mvc#4697]
I'm not sure if this is the right place to post this issue, but I'm having problem with building a .NET Core Web application. Visual Studio isn't generating any files in my `bin` folder.

I have this problem with every .NET Core Web Project that I create. Both with `ASP.NET Core Web Application (.NET Core)` and `ASP.NET Core Web Application (.NET Framework)`. I then choose a default `Web API` project or a default `Web Application` project. But both don't produce any files in my `bin` folder when I built the project. Even though Visual Studio says the build completed successfully:
```
1>------ Rebuild All started: Project: EfCoreTest2, Configuration: Debug Any CPU ------
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

I don't have this problem when I create a `ASP.NET Web application (.NET Framework)` project. This only happens with the `.NET Core` projects.

I did a reinstall of VS2015. But that didn't solve my problem.

Is there anything else that I can try to fix this issue?

**Comment by Eilon** [comment]
@chinookproject I moved the issue to https://github.com/aspnet/Tooling/issues/512 because this appears to be an issue with VS and compilation. Thanks!
