### ISSUE TITLE
Add ExceptionHandled to ExceptionContext

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4700]
https://msdn.microsoft.com/en-us/library/system.web.mvc.exceptioncontext.exceptionhandled(v=vs.118).aspx#P:System.Web.Mvc.ExceptionContext.ExceptionHandled is missing from `ExceptionContext`. Our other 'after' context classes have it.

We should add this since this is the place you're most likely to use it.

**Comment by ryanbrandenburg** [comment]
Yes, it's done. Thanks for the reminder.
