### ISSUE TITLE
RC2 Model binding hangs on POCO classes

### ISSUE THREAD

**Issue by DSmith307** [aspnet/Mvc#4704]
When a class from a set of interconnected simple POCO classes is included in the constructor of a controller action, the POST request to it hangs.

Steps to reproduce:

1. Start a new .NET Framework Web Application template straight from the RC2 release templates in Visual Studio 2015
2. Add the attached poco.txt as a CS file with the namespaces renamed to match the new project

[poco.txt](https://github.com/aspnet/Mvc/files/275770/poco.txt)

3 . Change the function arguments of AccountController's Register POST action to         

public async Task\<IActionResult> Register(RegisterViewModel model, string returnUrl = null, **requirements requirements = null**)

where "requirements" is a class included in the poco.txt file. It could be any POST action changed but I chose this one to demonstrate.

4 . Add a breakpoint to the first line of the Register action

5 . Run the website. Register an new account. The POST request hangs and says "pending" forever on all browsers. It never reaches the breakpoint.

Windows 7 64-bit, ASP.NET Core RC2 public version, Visual Studio 2015 Update 2, Chrome, Firefox and IE

The below poco.txt (poco.cs) contains a set of simple classes that only reference each other.

[poco.txt](https://github.com/aspnet/Mvc/files/275770/poco.txt)

This issue is preventing conversion of a working rc1 application to rc2, as all GET and POST requests using these classes as model classes hang.

**Comment by javiercn** [comment]
@rynowak Can this be the same case as https://github.com/aspnet/Mvc/issues/4666? @DSmith307 there's a workaround for a similar/the same issue in #4666 you could try that out to see if it solves your problem and confirm its the same issue

**Comment by DSmith307** [comment]
@javiercn Thanks, it is the same issue and the workaround in #4666 solves my problem.
