### ISSUE TITLE
Strange “&#65279” character after upgrading to RC2

### ISSUE THREAD

**Issue by mrahhal** [aspnet/Mvc#4706]
[The question on SO.](http://stackoverflow.com/questions/37361375/strange-65279-character-after-upgrading-to-asp-net-core-rc2)

![d](http://i.stack.imgur.com/aMWOM.png)

I was porting a production project to RC2 last night. Didn't deploy yet but ported the whole application and I was hitting this.

This is definitely a problem that occurs only on RC2. I did a restart for good measures and tested this with a brand new default project without touching it and the same thing happened. This seems to be happening only on Google Chrome.

Strange thing is that I got it working one or two times when I was tinkering. I'm not sure but this seems random but with a very high chance of happening (to me at least).

Anybody else hitting it?

**Comment by benaadams** [comment]
https://github.com/aspnet/Mvc/issues/4671 ?

**Comment by mrahhal** [comment]
Alright! BrowserLink does seem to be the cause. I can't find the referenced BrowserLink#24 issue though. So what should I do? Is there a workaround? Do I remove it?

BTW, what does BrowserLink even do (feature wise)? The webpage already doesn't update when I edit css files since the start with dnx and nothing changes when I completely remove it.

**Comment by Eilon** [comment]
@mrahhal yep this is the same issue. The BrowerLink repo is private right now (we hope to be able to change that at some point in the future).

In the meantime you can certainly just disable BrowserLink (remove the NuGet package reference, and remove the 1 line of code from Startup.cs).

The keyboard shortcut for BrowserLink is <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Enter</kbd>. So, for example, make a change to a CSS, JS, or CSHTML file in your app, save it, then press that keyboard shortcut, and all the "attached" browsers will update.

**Comment by chemitaxis** [comment]
Ok, thanks...
