### ISSUE TITLE
Response cookie not delivered if exception thrown in action

### ISSUE THREAD

**Issue by billboga** [aspnet/Mvc#4707]
Given this code:

```csharp
public class HomeController : Controller
{
    public IActionResult Index()
    {
        Response.Cookies.Append("test", "value");

        throw new Exception("No cookie received");

        return View();
    }
}
```

I do not get the expected cookie. Before, you could supposedly override `OnException` (ref. http://stackoverflow.com/a/20568049). Is there a new approach?

**Comment by billboga** [comment]
I'll still get a session-cookie if I use `Session` before the `throw`. I just can't seem to make the connection how the two differ in their approach to setting the cookie.

**Comment by billboga** [comment]
If I wrap the original `Response.Cookies...` statement with:

```csharp
HttpContext.Response.OnStarting(() =>
{
    HttpContext.Response.Cookies.Append("test", "value");

    return Task.FromResult(0);
});
```

then I get the cookie (borrowed from the [Session implementation](https://github.com/aspnet/Session/blob/dabd28a5d9ac7837afbfce7c8dfa2805a9559857/src/Microsoft.AspNetCore.Session/SessionMiddleware.cs#L138).

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
What component catches and handles the exception? UseExceptionHandler, UseDeveloperExceptionPage, or does it make it all the way up to the server?

The exception handlers intentionally clear the response headers so they can provide their own response. I'm not sure it makes sense for the session cookie to be included either. Is your cookie truly independent of your response? Why not catch and handle the exception yourself if you're expecting it?

**Comment by billboga** [comment]
> Is your cookie truly independent of your response?
Yes. I have a library for handling "flash" messages and need to make sure the current state of the message-collection is preserved even when exceptions occur. I'm fine with using `OnStarting`, but wanted to make sure there was not a preferred approach before continuing.

Ref. https://github.com/billboga/motleyflash/

**Comment by Eilon** [comment]
Yeah at present this is by design. Once there's an "unhandled exception" the systems needs to clear out as much partially-completed work as possible so that it can render a proper error. The system has no way of knowing what's safe to clear and what's not, so it does it's best to clear as much as possible (which is totally safe from the perspective of rendering an error).
