### ISSUE TITLE
Design problem: MvcRazorHost.Dispose

### ISSUE THREAD

**Issue by hikalkan** [aspnet/Mvc#4709]
Hi,

MvcRazorHost class injects IChunkTreeCache and assigns it to _chunkTreeCache field (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.Host/MvcRazorHost.cs#L70). That's a good DI usage, no problem.
But then in MvcRazorHost.Dispose, it disposes the _chunkTreeCache (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.Host/MvcRazorHost.cs#L348).

Isn't that a design problem? I think a class should not dispose an object if it's injected (not created by this class).

With Dependency injection, IChunkTreeCache's lifetime may not be same as MvcRazorHost. Beside that, DI framework will already dispose IChunkTreeCache when needed. This design can lead to double Dispose of _chunkTreeCache. Maybe this works since MvcRazorHost is somehow singleton, but it's conceptually wrong.

So, a class should only dispose an object if this object is directly created by that class, not injected.

I come across to this situation while debugging my Castle Windsor DI adapter (https://github.com/volosoft/castle-windsor-ms-adapter/tree/master/src).

What do you think?

**Comment by Eilon** [comment]
Ah, seems like a fair point. This is where `IChunkTreeCache` is registered with the container:
https://github.com/aspnet/Mvc/blob/574ecbb3ebfbb53697be3b1ad69a0a0232a548db/src/Microsoft.AspNetCore.Mvc.Razor/DependencyInjection/MvcRazorMvcCoreBuilderExtensions.cs#L144

What was the issue you saw while debugging?

The reason I ask is I'm trying to figure out the urgency of fixing this. Given that the service is a singleton, I think I'm a bit less worried about fixing this urgently, but I'm not certain.

**Comment by hikalkan** [comment]
Hi,

I don't think it's urgent. Just backlog it.

I found that by my mistake. Since MvcRazorHost is registered as transient (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/DependencyInjection/MvcRazorMvcCoreBuilderExtensions.cs#L161), when it's disposed it disposed the singleton IChunkTreeCache. But actually MvcRazorHost should not be disposed since it's used by a singleton class (as commented here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/DependencyInjection/MvcRazorMvcCoreBuilderExtensions.cs#L157). I fixed my DI implementation and it runs good now. Actuallyi, this design problem helped me on finding my mistake :)
Anyway, as I said, it's not urgent but will be good to fix it.

Thanks.

**Comment by Eilon** [comment]
Oh, wait, now I'm worried even more 😄 

If the transient service is disposing the singleton service, then that could cause mayhem.

The transient service could be disposed *a lot* because its lifetime is relatively short. It's certainly possible that despite being a transient service, that it is effectively used as if it was a singleton, but that's still not right.

We'll try to get this fixed ASAP.

**Comment by dougbu** [comment]
@hikalkan and the comment he highlighted are correct. The `IMvcRazorHost` dependency tree is fairly simple -- almost no branches. The usage eventually trickles up to `RazorViewEngine` and that is registered as a singleton. Of course fixing this means the odd disposal of a service goes away and nothing will break in the future if we change the dependency tree or lifetimes.

**Comment by pranavkm** [comment]
Should we remove the `IDisposable` contract from the interface? It's only used to dispose the `_chunkTreeCache`

**Comment by Eilon** [comment]
@pranavkm that sounds fine.
