### ISSUE TITLE
Identify if we can reduce the number of contexts we create during model binding \ model validation

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#471]
We create multiple contexts as we walk the object graph during binding and validation. These have shown up in perf in the past.

| 137 | 10237 | Reported By: Pranav K |

**Comment by yishaigalatzer** [comment]
Duplicate of #1550 that has more data

**Comment by rynowak** [comment]
@yishaigalatzer this isn't the same. #1550 is about the lifetime of a particular service. This bug was about the number of model binding contexts we new up in code (1-per-property) and the number of validation contexts we new up in code.
