### ISSUE TITLE
Update Json.NET

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Mvc#4711]
https://www.nuget.org/packages/Newtonsoft.Json/8.0.4-beta1

Targets netstandard1.0 - no more imports!

**Comment by henkmollema** [comment]
Is there a reason it's still a beta version?

**Comment by PinpointTownes** [comment]
FYI, JSON.NET is also used by a few other ASP.NET Core/.NET Core projects (e.g the OAuth2/OIDC middleware or IdentityModel). That would be great to update it everywhere at the same time to avoid package resolution warnings during `dotnet restore` :smile:

**Comment by Eilon** [comment]
Yes, we will update it across as much as possible.

See https://github.com/dotnet/cli/issues/3198 for some info regarding some issues we have to resolve.

**Comment by javiercn** [comment]
Done. Here is the command I used to verify that we updated all our dependencies across repos. Clone universe, run build pull and then ```Get-ChildItem -Recurse project.json | select-string "Newtonsoft"```

**Comment by dougbu** [comment]
@javiercn `build pull` doesn't pull a number of repos. One of them that _does_ use Json.NET is Coherence.

Suggest using `build pull-all` instead. Probably also need to double-check at least the Performance repo.

**Comment by javiercn** [comment]
I didn't know about pull-all. At least everything we need to build the product is in pull. I'll try pull all later and update any missing dependency, thanks for the tip!

**Comment by javiercn** [comment]
@dougbu Did a pull all, the only one not in 9.0.1 was Coherence\src\CoherenceBuild\project.json:7:    "Newtonsoft.Json": "8.0.3", so it's fine

**Comment by dougbu** [comment]
@javiercn suggest a PR to make Coherence consistent. It's low-priority but we don't have a reason to stick w/ 8.0.3.

**Comment by javiercn** [comment]
@dougbu it's already ipsa
