### ISSUE TITLE
Nuget pkgs disappearing?

### ISSUE THREAD

**Issue by bc3tech** [aspnet/Mvc#4713]
We're referencing `System.Buffers | 4.0.0-rc2-23623` and recently our builds started failing with a 404 from the myget servers. Is the team actually *removing* nuget pkgs from the repo? If so, is there any communication as to what consumers should do?

Thanks.

**Comment by davidfowl** [comment]
Packages are always removed from myget servers. You *cannot* rely on them for stable builds. You should be using nuget.org or mirroring packages if you need builds to stay around forever.

**Comment by Eilon** [comment]
@bc3tech we currently keep about 5 - 10 builds of every package on the `aspnetvnext` feed, which has our "nightly" builds. This has been the behavior for the last few years. Otherwise the feed would take up terabytes of space.

**Comment by bc3tech** [comment]
thanks for the insight, guys! 👍

**Comment by davidfowl** [comment]
Nope
