### ISSUE TITLE
Add a secure binding option to model binders

### ISSUE THREAD

**Issue by blowdart** [aspnet/Mvc#4718]
Secure binding would **only** bind to a safelisted list of fields in the [Bind] attribute. 

If a class has no [Bind] attribute an exception would be thrown if they're used as an action parameter, or as a field in an action parameter.

If a class has the [Bind] attribute and a field is specified for binding which is not specified in the safe list an exception would be thrown.

If we're really paranoid we'd also refuse to bind to EF models.

Ideally we'd turn this on by default, but it would break too many people.

**Comment by Eilon** [comment]
Definitely an interesting feature idea... will certainly consider in the next release.

**Comment by rynowak** [comment]
I recommend we create a meta-issue to track collected feedback around model binding enhancements, and put this there.

**Comment by rynowak** [comment]
I'm closing this in favor of tracking with the meta issue #6549
