### ISSUE TITLE
MVC 6 / Asp.net VNEXT how to use shared, separate Resource DLL with IViewLocalizer or IHtmlLocalizer and .resx 

### ISSUE THREAD

**Issue by MrWinky** [aspnet/Mvc#4723]
There are lots of great VNEXT articles explaining how to use RESX resources when the \Resources folder are in the VNEXT  application's sub folder path.   

However, I have an MVC application which requires I place the RESX files in a separate VNEXT class library dll in the solution and share it among projects (assume the separate project is called MyResourceProject).   Maybe I should be using a different project type for sharing resource strings in a  RESX?

The following does not work:

```c#
 services.AddLocalization(options => options.ResourcesPath = "MyResourceProject .Resources");
```

and

```c#
  services.AddMvc()
          .AddViewLocalization(options => options.ResourcesPath = "MyResourceProject .Resources")
```

How do I point to a separate library path in an MVC VNEXT application?

**Comment by Eilon** [comment]
@MrWinky I moved this bug to https://github.com/aspnet/Localization/issues/246 as I think it's a more general localization issue.

**Comment by MrWinky** [comment]
Thanks.   I see this as a bug if external paths aren't permitted.
