### ISSUE TITLE
ViewComponent returns objects(?)

### ISSUE THREAD

**Issue by CezaryRynkowski** [aspnet/Mvc#4725]
Hi, i successfully migrate my project from RC1 to RC2 but i have a issue with Components. I change 
`@Component.Invoke("ContactField")`
to
`@Component.InvokeAsync("ContactField")`.
But now in view i have text -> System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Html.IHtmlContent]

What can i do with this issue?

**Comment by PBeckerr** [comment]
Im not sure if you can await in a razorview, but if not use @Component.InvokeAsync("ContactField").Result to get the underlaying Result of the Task.

**Comment by CezaryRynkowski** [comment]
Thanks :)

**Comment by rynowak** [comment]
Announcement for this change here: https://github.com/aspnet/Announcements/issues/145

**Comment by paultechguy** [comment]
You just need to await the result:

@await Component.InvokeAsync("ContactField")
