### ISSUE TITLE
FromRoute with constructor parameters

### ISSUE THREAD

**Issue by herecydev** [aspnet/Mvc#4727]
When using the `FromRoute` attribute with a POCO such as:

``` c#
public class ChangePassword
{
    public string Password { get; set; }
}
```

The model is populated and everything works fine. However if the POCO was:

``` c#
public class ChangePassword
{
    public ChangePassword(string password)
    {
        Password = password;
    }

    public string Password { get; }
}
```

It throws with a`System.MissingMethodException: No parameterless constructor defined for this object.` The message is self-explanatory, and work arounds are possible but it would be nice to know if this can be done?

**Comment by Eilon** [comment]
The default system doesn't allow using constructor parameters. It can construct only object that have get/set properties. You could either use the get/set pattern, or you could write a custom model binder that knows how to construct this type (or other types that follow a similar pattern).

**Comment by drovani** [comment]
Are there any good resources for learning more about doing custom model binding that utilizes an explicit constructor? I have found plenty that talk about creating a custom binding handler, but they all are too generic and simple cases that don't dig deep enough to talking about this level of customization.

**Comment by rynowak** [comment]
@drovani - here's an example someone did where they create the model from DI https://github.com/Serjster/IOCModelBinderExample/tree/ASPNETRTMVersion/src/IOCModelBinderExample/Infrastructure

If if you can be more specific about what you want to see I can try to help

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
