### ISSUE TITLE
TempData within a ViewComponent

### ISSUE THREAD

**Issue by bfolder2001** [aspnet/Mvc#4728]
It seems that `ViewData` and `ViewBag` are available from within `ViewComponent.Invoke()`, but that `TempData` isn't. Is this by design or an oversight?

**Comment by rynowak** [comment]
It's available via `ViewContext.TempData`. We should add a convenience property... seems like just an oversight to me.

**Comment by bfolder2001** [comment]
@rynowak I was sure I'd checked there, but you're quite right! Thanks. A convenience property would certainly clear things up.

**Comment by dougbu** [comment]
94fa34c

**Comment by dougbu** [comment]
Thanks @ctyar!
