### ISSUE TITLE
Where did IControllerTypeProvider go in RC2?

### ISSUE THREAD

**Issue by dotnetjunkie** [aspnet/Mvc#4730]
In rc1, a call to `AddMvc` ensured the registration of an `IControllerTypeProvider` implementation. In rc2 however, no such registration is made and while browsing through the source code there seem to be no usage of `IControllerTypeProvider` (although the Github repository search might invalidly return not the right results).

Why is no `IControllerTypeProvider` registration made and what is currently the way to request a list of controller types from MVC?

**Comment by pranavkm** [comment]
`IControllerTypeProvider` and the surrounding infrastructure was replaced by application parts, specifically `ControllerFeature`. See https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionDescriptorProvider.cs#L96-L102 for usage.

Oddly `IControllerTypeProvider` continues to exist in the code base but isn't used anywhere. It needs to be deleted.

**Comment by pranavkm** [comment]
cc @javiercn

**Comment by Eilon** [comment]
@pranavkm yeah let's remove `IControllerTypeProvider`.

**Comment by pranavkm** [comment]
https://github.com/aspnet/Mvc/pull/4735 < PR for it

**Comment by pranavkm** [comment]
@dotnetjunkie - I removed the type as part of https://github.com/aspnet/Mvc/commit/15f113ddb17708f642fc7afb187d52c0aaf5582d. Let me know if you have issues working with the `ControllerFeature`.

**Comment by javiercn** [comment]
@pranavkm is correct

**Comment by dotnetjunkie** [comment]
@pranavkm, using the example in the code base you postef at, I managed to get this working.

From an API perspective the creation of a feature onject and sending it to the part manager feels a bit weird though; there might be an abstraction or extension method missing, although admittingly a request for all controller types might not be a very common use case.
