### ISSUE TITLE
Enable supplying location of antiforgery request token in ValidateAntiforgeryToken attribute

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#4734]
From: https://github.com/aspnet/Entropy/pull/123/files#r64092095

In case of file uploads(via Ajax) + antiforgery, the request token is sent via header. In this case we want to make sure we read the token _only_ from the header and not from the body. The reason being that by default Antiforgery system first looks for the token in the header and if it couldn't find there falls back to reading the body.

@Tratcher @rynowak

**Comment by Eilon** [comment]
Critical for 1.0.0? Or a nice-to-have that we can add later?

**Comment by Tratcher** [comment]
Incremental improvement, nice to have.

**Comment by danroth27** [comment]
@Eilon This doesn't sound critical - should we move this to the backlog?

**Comment by Eilon** [comment]
Yeah sure, we can wait for customer demand.

**Comment by rynowak** [comment]
We haven't had any customer demand for this yet. Given that we plan to make antiforgery totally transparent, I'd suggest closing this
