### ISSUE TITLE
Consider switching to `IConfigureOptions` instead of `ConfigureOptions` in OptionsSetup

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#4736]
The API for using `IConfigureOptions<>` is a bit more traditional than using the lambda overload that `ConfigureOptions<>` has:

Consider what we have
```C#
public class MvcCoreRouteOptionsSetup : ConfigureOptions<RouteOptions>
{
    public MvcCoreRouteOptionsSetup()
        : base(ConfigureRouting)
    {
    }

    public static void ConfigureRouting(RouteOptions options)
    {
        options.ConstraintMap.Add("exists", typeof(KnownRouteValueConstraint));
    }
}
```
versus

```C#
public class MvcCoreRouteOptionsSetup : IConfigureOptions<RouteOptions>
{
    public void Configure(RouteOptions options)
    {
        options.ConstraintMap.Add("exists", typeof(KnownRouteValueConstraint));
    }
}
```

**Comment by rynowak** [comment]
FYI , I asked @pranavkm to file this, it's just code cleanup. The `ConfigureOptions` base class is kludgy to use when you have constructor parameters

**Comment by Eilon** [comment]
The type `MvcCoreRouteOptionsSetup` is in a `.Internal` namespace. Can we clean this up later?

**Comment by rynowak** [comment]
We can do this like 10 years from now :laughing:

**Comment by Eilon** [comment]
Got it.
