### ISSUE TITLE
Different encoding case from UrlEncoder and UrlHelper.Action

### ISSUE THREAD

**Issue by audacity76** [aspnet/Mvc#4743]
There are different capitalization rules for url encodings:

UrlEncoder.Default.UrlEncode(':') returns '%3**A**'
UrlHelper.Action("Controller","Action",new { param = ':' }) returns /Controller/Action/%3**a**

My solution is running on RC1

**Comment by rynowak** [comment]
It's likely already been addressed https://github.com/aspnet/Routing/issues/214

The RC1 version of the routing code was off doing it's own thing with respect to encoding, and not going through the new `HtmlEncoder` api.

**Comment by Eilon** [comment]
Yup, closing as dup of https://github.com/aspnet/Routing/issues/214.
