### ISSUE TITLE
RC2: Controllers that have RequireHttpsAttribute won't load on Azure

### ISSUE THREAD

**Issue by madmunsterdaddy** [aspnet/Mvc#4745]
With RC2 any controller that I have decorated with RequireHttpsAttribute won't load on Azure. It is just a flood of 302s and eventually times out.

Interestingly, I can access the site with HTTPS, but any controller that has that no longer works.

**Comment by kichalla** [comment]
@sebastienros and I are investigating.

**Comment by sebastienros** [comment]
We are about to test on Azure App Services, are you using another setup?

**Comment by madmunsterdaddy** [comment]
Nope, just Azure App Services. Just like you'd create a new web app in VS Azure tools.

**Comment by kichalla** [comment]
We were informed that this is a known issue which was mentioned in the Release notes. You can look at the section `HTTPS requests appear as HTTP in Azure Web Sites` in the following release notes for a workaround.
https://github.com/aspnet/Home/releases/tag/1.0.0-rc2-final

**Comment by madmunsterdaddy** [comment]
Ahhh.. gotcha! Thank you.

**Comment by Eilon** [comment]
Yeah this is a dup of https://github.com/aspnet/IISIntegration/issues/140.
