### ISSUE TITLE
Restore support for data annotations adapter registrations

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#475]
The following methods were removed as part of porting over:

RegisterAdapter
RegisterAdapterFactory
RegisterDefaultAdapter
RegisterDefaultAdapterFactory
RegisterValidatableObjectAdapter
RegisterValidatableObjectAdapterFactory

from DataAnnotationsModelValidatorProvider. We'll need to revive this once we finalize on the design of validation.

| 116 | 10216 | Reported By: Pranav K |

**Comment by dougbu** [comment]
/cc @Eilon @danroth27 this is the missing extensibility point I mentioned in PR #3649. See https://github.com/aspnet/Mvc/pull/3649#discussion-diff-46242525 in particular. Users who create `ValidationAttribute` subclasses can't register client-side support for that attribute.

Fallback is to implement  `IClientModelValidator` in the custom `ValidationAttribute` or write an `IClientModelValidatorProvider`.

**Comment by rynowak** [comment]
We've had no requests to port forward these old extensibility points.

Suggest closing /cc @Eilon @dougbu
