### ISSUE TITLE
Support GlobbingUrlBuilder overrides

### ISSUE THREAD

**Issue by csteeg** [aspnet/Mvc#4751]
Microsoft.AspNetCore.Mvc.TagHelpers.LinkTagHelper and Microsoft.AspNetCore.Mvc.TagHelpers.ScriptTagHelper
don't call the UrlHelper to generate the final url's.

I've replaced the UrlHelper on the current httpcontext (HttpContext.Items[typeof(IUrlHelper)], to generate full server url's, but this doesn't work with these helpers (eg. asp-href-include)

It would als be nice to replace the UrlHelper somewhat more friendly (eg let UrlHelperFactory resolve IUrlHelper instead of getting it from the HttpContext.Items)

**Comment by dougbu** [comment]
What scenario is currently broken?

Also please clarify your comment about using `HttpContext.Items[typeof(IUrlHelper)]` versus the `protected IUrlHelperFactory UrlHelperFactory { get; }` property that's already available in both the `<link>` and `<script>` tag helpers (from their base class).

**Comment by Eilon** [comment]
I should note that the value in `HttpContext.Items[typeof(IUrlHelper)]` is just an implementation detail. The correct way to replace the `IUrlHelper` is to do so via the dependency injection container.

**Comment by csteeg** [comment]
@dougbu what is broken (or incorrect), is that the link- & scripttaghelper don't call the IURLHelper methods at all. It generates the links by calling GlobbingUrlBuilder.BuildUrlList for example. The GlobbingUrlBuilder is also not calling the IUrlHelper, it generates url's on it's own. The GlobbingUrlBuilder is created 'manually' in EnsureGlobbingUrlBuilder, so I cannot inject that one as well.
So, to summarize, if I want those 2 taghelpers to generate full-server urls including a domain and scheme for the following code:
`<link rel="stylesheet" asp-href-include="~/css/site.css,~/css/vendor.css,~/css/niteflight.css" />`
I have to create my own taghelpers completely instead of just replacing the IUrlHelperFactory as I can do with the 'normal' UrlResolutionTagHelper:
`<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"  />`

@Eilon Sorry for that comment indeed, I overlooked something there and it can be injected through DI indeed.

**Comment by dougbu** [comment]
The `<link>` and `<script>` tag helpers are both `UrlResolutionTagHelper` subclasses and both rely on an `IUrlHelper` to handle `~/` in static URLs e.g. `href` and `src`. `~/` in globbing patterns (like `asp-href-include`) is ignored but generated URLs include the `RequestBasePath` value.

@csteeg what HTML is generated and what do you expect? For example, do you want the scheme and host included in URLs generated for matched files?

**Comment by csteeg** [comment]
I've created my own IUrlHelper implemenation:
`public class FullUrlHelper : UrlHelper
    {
        private readonly CdnSettings _cdnSettings;

        public FullUrlHelper(ActionContext actionContext, IOptions<CdnSettings> cdnSettings) : base(actionContext)
        {
            _cdnSettings = cdnSettings.Value;
        }

        public override string Content(string contentPath)
        {
            return expandUrl(base.Content(contentPath));
        }

        private string expandUrl(string contentPath)
        {
            var stringBuilder = new StringBuilder();
            stringBuilder.Append(_cdnSettings.Scheme);
            stringBuilder.Append("://");
            stringBuilder.Append(_cdnSettings.Host);
            stringBuilder.Append(contentPath);
            return stringBuilder.ToString();
        }
    }
`
This urlhelper generates url's to my CDN instead of to the local version. It works fine for `href `and `src` on `<link>` and `<script>`, since they call my IUrlHelper. But since `asp-href-include` does not call my UrlHelper, I have to copy the entire code from the `LinkTagHelper` and `ScriptTagHelper`. As far as I can see there is no simple way to hook into the url-generation when globbing patterns are used.

**Comment by dougbu** [comment]
Correct, globbing patterns intentionally work with local files. Neither the `GlobbingUrlBuilder` nor the `FileVersionProvider` are replaceable.

I'm not sure how your scenario could work end-to-end. The CDN would need to cooperate, globbing available files and providing file versions. Even then the ASP.NET Core site would need to poll the CDN frequently to ensure cached information remains valid; file watchers aren't an option.

**Comment by csteeg** [comment]
I understand what you're saying, that would be the ideal situation.
But my request is, to just make it possible to hook into the `GlobbingUrlBuilder`'s url generation somehow. Hence it would even be fine if the GlobbingUrlBuilder would be injectable by DI instead of being constructed in `EnsureGlobbingUrlBuilder`, that way I'd be able to just override the `BuildUrlList` method

**Comment by dougbu** [comment]
@csteeg I suggest renaming your request to something like "Support GlobbingUrlBuilder overrides".

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to how this works.
