### ISSUE TITLE
Redo IModelValidator to not depend on ModelMetadata hierarchy

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#476]
For some reason, ModelMetadata has a Model property that is the actual instance. This seems to conflate the notions of model and value and runs into issues with caching. IModelValidator seems to be the only thing that uses this hierarchy to walk the object graph

| 112 | 10212 | Reported By: Pranav K |

**Comment by rynowak** [comment]
We already removed `ModelMetadata.Model`, so this is stale.
