### ISSUE TITLE
Resource.designer.cs issue

### ISSUE THREAD

**Issue by DandY30** [aspnet/Mvc#4763]
The baseName value of **ResourceManager** changes (to wrong path) every time I add a new row to my .resx.

The working baseName value should be "Namespace.Resources.Resource" and it changes to Namespace.Resource.

**Comment by Eilon** [comment]
@DandY30 so you're saying while you're in VS and editing the RESX file, the .designer.cs file changes in an incorrect manner?

If that's the case, we'll move the bug to https://github.com/aspnet/Tooling/issues/.

**Comment by DandY30** [comment]
@Eilon yes that's exactly what I'm saying

**Comment by Eilon** [comment]
@DandY30 thanks, I moved the bug to here: https://github.com/aspnet/Tooling/issues/554
