### ISSUE TITLE
documentation for global.json

### ISSUE THREAD

**Issue by ciel** [aspnet/Mvc#4767]
I wasn't really sure where this needed to go, but I've learned that in order for Visual Studio 2015 to properly pick up and use your libraries, the top-level folders where your projects are need to be declared in a `config.json` at the root of your project.

For example, I had the following project structure;

```
.../
.../src
.../src/core
.../src/identity
.../src/advanced
.../src/api
.../models
.../models/core
.../models/advanced
.../test
.../test/installers
```

And I didn't have the `models` folder in my `config.json`. I thought Visual Studio was just wigging out, because trying to reference those libraries in other parts was failing and I just could not get them to work. Then it occurred to me to check that;

The following `config.json` rectified the problem.

```
{
  "projects": [
    "src",
    "test",
    "models",
    "service"
  ],
  "sdk": {
    "architecture": "x64",
    "runtime": "clr",
    "version": "1.0.0-preview2-002886"
  }
}
```

**Comment by Eilon** [comment]
@ciel the `global.json` file is now part of .NET CLI, so I recommend logging an issue at https://github.com/dotnet/cli/issues, or I can copy it there for you.

**Comment by ciel** [comment]
I'll post it. Thank you. I should have thought that through before posting it here. It makes complete sense that it's part of the cli and has nothing to do with ASP.NET.

**Comment by Eilon** [comment]
Actually, apparently the place to log bugs is at https://github.com/dotnet/core-docs/issues, so please log a new issue there (or see if there's an existing issue).
