### ISSUE TITLE
FindView in RC2 vs RC1

### ISSUE THREAD

**Issue by mguinness** [aspnet/Mvc#4772]
Using Microsoft.AspNet.TestHost in RC1 I was able to return a view from an action with:

`return View("~/Test");`

After upgrading to Microsoft.AspNetCore.TestHost in RC2 that no longer worked, I had to use:

`return View("~/Test.cshtml");`

Normally when a view name is given (or not specified) it would use the following locations:

```
public virtual IEnumerable<string> ViewLocationFormats { get; } = new[]
{
    "/Views/{1}/{0}" + ViewExtension,
    "/Views/Shared/{0}" + ViewExtension,
};
```

But when a path is included like "/Test" or "~/Test" is any location searching performed?  In RC1 it seems to try the path provided and if not found it then appended ".cshtml" (ViewExtension).

I know that a custom IViewLocationExpander could be used (https://github.com/aspnet/Mvc/issues/4122), but I was curious as to why this worked in RC1 and not RC2.

**Comment by dougbu** [comment]
We improved the view lookup process to support relative paths in RC2. One of the minor changes in that process was that absolute paths (those starting w/ `'/` or `~/`) no longer get the view extension added automatically -- it's an absolute path and must be complete.
