### ISSUE TITLE
aspnetcore RC2 via IIS is serving "oddly formed" html?

### ISSUE THREAD

**Issue by uxp** [aspnet/Mvc#4773]
I'm seeing some really interesting output from an unmodified application served via IIS Express. Basically, from what I can tell, the HTML comes across the wire correct (as exampled in the output of the cURL request below), but WebKit-based browsers in particular have trouble rendering the page. I think it has some correlation with encoding, as the second screenshot below shows that all of the content within the html `<head>` tag has been dumped into the beginning of the `<body>` tag, and an html encoded 'ZERO WIDTH NO BREAK SPACE', (aka: utf-8 Byte Order Mark) gets thrown into the beginning of the element, presumably where different Razor template partials begin.

![terminal](http://cloud.selectivebyt.es/1q0i0M3D0a2F/Screen%20Shot%202016-05-29%20at%2010.58.23%20AM.png)

![rendered](http://cloud.selectivebyt.es/340o0B2p0r3u/Screen%20Shot%202016-05-29%20at%2010.53.14%20AM.png)

Switching the project to serve the application via Kestrel (eg, `dotnet run`) does not exhibit this behavior.

**Comment by davidfowl** [comment]
Duplicate of https://github.com/aspnet/Mvc/issues/4671

**Comment by uxp** [comment]
So it is. Thanks! Somehow missed that while searching existing issues.
