### ISSUE TITLE
[Question] Some questions regarding the ApplicationModelConvention

### ISSUE THREAD

**Issue by Dresel** [aspnet/Mvc#4774]
I'm currently developing a localization library which should extend existing attribute routes via the given ApplicationModel.

Considering the given controller

    [Route("products")]
    public class ProductController : Controller
    {
        [Route("{productId}/preview")]
        public IActionResult Preview(int productId)
        {
            return Content("Preview!");
        }
    }

this would end up with one route ("/products/{productId}/preview").

The library should support certain use cases like

- Apply (default) culture to all existing attribute routes (would modify the above route to "/en/products/{productId}/preview" for example)
- Add additional translations (would add "/de/produkte/{productId}/vorschau" for example)

Playing with the ApplicationModel I managed to achieve this use cases, but I'm not sure if I use it correctly.

- Is it ok to store processing information (e.g. the culture) in the Properties property of ControllerModel and ActionModel? If not, where would you store this information?
- Is it ok to have multiple ControllerModels pointing to the same controller but with different selectors? This is how I currently implemented the translation part, copying ControllerModels and modifying the AttributeRouteModel's Template of the Selectors - my first intention was to just add additional Selectors to existing Controller- / ActionModels, but then you could use mixed routes like "/en/products/{productId}/vorschau".

**Comment by javiercn** [comment]
I think you are on the right path.
The properties on ActionModel and controller model are exactly for that, they will get copied to the ActionDescriptor properties bag, which is meant to allow people to put their own metadata.


> Is it ok to have multiple ControllerModels pointing to the same controller but with different selectors?

I think you mean action descriptors? If you are translating the routes, I would suggest you prefix every translated route with the language prefix and the translated route, for example, for 
/products/{productId}/
would become
/en/products/{productId}
/es/productos/{productId}
and you could store the culture on each action descriptor.

@rynowak might be able to give you other alternative solutions.

**Comment by Dresel** [comment]
When I said selectors, I meant the [SelectorModel](https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/SelectorModel.cs) class.

If I understood it correctly, the attribute routes are stored in the [AttributeRouteModel](https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/AttributeRouteModel.cs) property of the selectors? For each attribute route attribute there is one selector with the corresponding attribute route model. To modify existing routes I can modify the template property of the attribute route model? To add new routes I have to add new selectors (with attribute route models)?

And because selectors / attribute route models can exist on controller model and action model instances, my guess was to copy the controller model (without selectors), add one selector to the controller with attribute route model template set to "/de/produkte/" and to add another selector to the action with attribute route model template set to "{productId}/vorschau" - or simplified one copied controller model per language.

Because otherwise if I just add selectors with attribute route models to the existing controller / action model all combinations of controller and action selectors would be taken for route generation:

- /en/products/{productId}/preview
- /en/products/{productId}/vorschau
- /de/produkte/{productId}/preview
- /de/produkte/{productId}/vorschau

That's why I asked if it's ok to have multiple ControllerModels (one per language) pointing to the same controller but with different selectors (attribute route models)?

**Comment by rynowak** [comment]
> Is it ok to store processing information (e.g. the culture) in the Properties property of ControllerModel and ActionModel? If not, where would you store this information?

You can store anything in `.Properties` that you want to be cached for the lifetime of the application. It sounds like what you're doing is exactly what this feature is intended for.

> Is it ok to have multiple ControllerModels pointing to the same controller but with different selectors? 

Yes. You can have multiple `ControllerModel`s or multiple selectors. The pivot here is whether or not you would want to customize the `ControllerModel` instances for each combination. For example, you might want to add a `.RouteValue` to your models for the culture/language name for link generation purposes.

```
controllerModel.RouteValues.Add("lang", "en");
```

This makes the `lang` required for link generation, and also "sticky" for link generation. If you're familiar with how areas work, this will behave similarly.

**Comment by Dresel** [comment]
Yep that makes sense, thanks for the explanation. So that's the current workflow I'm using:

- Copy `ControllerModel` (only done for the first translation added, afterwards use the existing controller model)
 - Add a culture / language value to `RouteValue` and/or `Properties` (guess I don't need both)
 - Remove all `Selector`s on the controller model and action models
- For each specified translation add a new `Selector` (copied from the "original" controller / action model) and set the `Template` of `AttributeRouteModel` to the specified translation

How would you handle copying `AttributeRouteModel`s with `Name` set to avoid

    Attribute routes with the same name '{name}' must have the same template:

exceptions?

My first guess was to modify the name to something like {name}:{culture}, so "originalname" would be modified to "originalname:de" for a german translation. But I don't know if that's the best solution.

**Comment by rynowak** [comment]
> My first guess was to modify the name to something like {name}:{culture}, so "originalname" would be modified to "originalname:de" for a german translation. But I don't know if that's the best solution.

This is what I'd recommend. The token-replacement feature for route names is meant to support cases where you want to use use names, but also want to set the routes with a convention.

Note that the syntax would actually be `[name][culture]` (square braces)

**Comment by Dresel** [comment]
That's great, didn't know that token-replacement is supported for route names also.

Thanks for all the explanations and your time, I think I'll have enough information for now. If you have more (advanced) resources / documentation (I did not found too much) about application model conventions I would be happy to hear about.

Nevertheless I will close this for now.
