### ISSUE TITLE
Tag Helper seems to include random Whitespace

### ISSUE THREAD

**Issue by wallace-eduardo** [aspnet/Mvc#4776]
![image](https://cloud.githubusercontent.com/assets/11624755/15654169/d38286b0-265f-11e6-9925-3d6f766fd98b.png)

Random white space (see above, BOM mark + newlines?) appears on my page when I use Tag helpers in Chrome (latest version 50+) 
I traced int to a simple drop down if  I remove asp-items="Model.Data" the random white space disappears, reason why this matters is because the white space is messing with my layout. Any help would be appreciated, Thanks!

```HTML
<select asp-for="Data" data-placeholder="Choose a Specialty" asp-items="Model.Data" class="chosen-select">
    <option value=""></option>
</select>
```

**Comment by ctyar** [comment]
check this
https://github.com/aspnet/Mvc/issues/4706#issuecomment-220808090

**Comment by Eilon** [comment]
Yup, same issue that @ctyar mentions, it's a dup of https://github.com/aspnet/Mvc/issues/4706#issuecomment-220808090.

Just remove the call to `UseBrowserLink` from your Startup.cs file and that will clear this up.
