### ISSUE TITLE
Enabling browserlink produces "weird" artifact on body tag

### ISSUE THREAD

**Issue by pekkah** [aspnet/Mvc#4777]
I just noticed that when I enable browserlink `app.UseBrowserLink();` weird artifacts is produced in the html page pushing the content down. This seems to be Chrome specific as with Edge I could not produce it.. (that == $0 is just chrome dev tool tip, but what comes after is the artifact)

![browserlink-artifacts](https://cloud.githubusercontent.com/assets/822416/15655431/cf4c0922-26a5-11e6-93df-7def34c8d296.PNG)

dependencies:
```
 "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final"
```

**Comment by ctyar** [comment]
Yeah it's already reported
https://github.com/aspnet/Mvc/issues/4706#issuecomment-220808090

**Comment by Eilon** [comment]
Yup, dup of https://github.com/aspnet/Mvc/issues/4706#issuecomment-220808090.

Workaround is to remove the call to `UseBrowserLink` from Startup.cs.
