### ISSUE TITLE
RC1 FileProviders.Composite

### ISSUE THREAD

**Issue by Serjster** [aspnet/Mvc#4778]
In order to use external ViewComponents, our projects need reference to **FileProviders.Composite**

We used to be able to get one that works with RC1 4.6 here:
https://www.myget.org/F/aspnetvnext/api/v3/index.json

Now, it is no longer there.

In the below announcement:
https://github.com/aspnet/Announcements/issues/143

We can see that the namespace has been renamed.... but also the version that worked with RC1 4.6 has been removed. We can not work with RC2/5.0 yet because other dependencies we need (like Swagger) do not have an RC2 compatible version yet. So we are now in a broken state. The easiest solution that I can see is to rerelease the version compatible with RC1 4.6. 

Please do so as soon as possible as our projects are in a broken state right now.

Thanks.

**Comment by Serjster** [comment]
It is showing as still here:
https://dotnet.myget.org/feed/cli-deps/package/nuget/Microsoft.AspNet.FileProviders.Composite

Is that a different feed?

**Comment by Serjster** [comment]
Anyways, unless you can point out what the feed URL is for those so that my projects can find those deps automatically, this issue is closed.

**Comment by davidfowl** [comment]
That's not right. This is what you want https://www.nuget.org/packages/Microsoft.Extensions.FileProviders.Composite/1.0.0-rc2-final

**Comment by Serjster** [comment]
Actually that's not right. That version does not work with RC1 4.6... the version I posted above does.
