### ISSUE TITLE
 Circular Object References using JSon

### ISSUE THREAD

**Issue by divega** [aspnet/Mvc#4782]
_From @DJKampouris on May 31, 2016 18:55_

I am using AspNetCore RC2 and I am tring to remove Circular Object References using JSon

With RC1 I could add the following snippet to my Startup.cs and it would work.

```
services.AddMvc().AddMvcOptions(options => {

options.OutputFormatters.RemoveType<JsonOutputFormatter>();
var jsonOutputFormatter = new JsonOutputFormatter();
jsonOutputFormatter.SerializerSettings.ReferenceLoopHandling 
  = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
options.OutputFormatters.Insert(0, jsonOutputFormatter);
});
```

In RC2 it doesn't work anymore and I would rather not revert to using  [JsonIgnore] on my model navigation properties.

Any suggestions ?

_Copied from original issue: aspnet/EntityFramework.Docs#178_

**Comment by javiercn** [comment]
@DJKampouris the better way of achieving your scenario is through a call AddJsonOptions(). See https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/DependencyInjection/MvcJsonMvcBuilderExtensions.cs#L19 for details.

Can you be more specific on what works and what doesn't?

**Comment by DJKampouris** [comment]
Thanks. 

I have followed your suggestions and changed my code to use the AddJsonOptions which was much simpler.

```
services.AddMvc().AddJsonOptions(options =>
    {
	options.SerializerSettings.ReferenceLoopHandling 
	  = ReferenceLoopHandling.Ignore;
    });

```

**Comment by javiercn** [comment]
@DJKampouris Did this fix your issue? Was your issue related to writing a response or with reading a request. It would be good if you can give us more details to rule out that there is a bug. Thanks!

**Comment by DJKampouris** [comment]
Yes this did fix my issue.

When using the old code snippet I was getting compilation errors and did not know how to work around them and convert the code to comply with RC2

```
Error	CS0122	'JsonOutputFormatter.SerializerSettings' is inaccessible due to its protection level	
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'serializerSettings' of 'JsonOutputFormatter.JsonOutputFormatter(JsonSerializerSettings, ArrayPool<char>)'	

```

Thanks.
