### ISSUE TITLE
Microsoft.AspNetCore.Mvc vs Microsoft.AspNetCore.Mvc.Core

### ISSUE THREAD

**Issue by BadriL** [aspnet/Mvc#4785]
I see that VS 2015 adds `Microsoft.AspNetCore.Mvc` to project.json for both Web app and Web API. That said, are there any scenarios/UCs I should be using Microsoft.AspNetCore.Mvc.Core instead of regular MVC?

**Comment by javiercn** [comment]
@BadriL Microsoft.AspNetCore.Mvc core is for advanced scenarios in which you want to fine tune the MVC configuration. Many of the default services (like views, view components, formatters) are not plugged in when you use Mvc Core. In general its best to stick with MVC unless you know what you are doing.

**Comment by pranavkm** [comment]
We used to have a MvcMinimal sample that showed how you'd use Mvc.Core to set up a website without any rendering components. @dougbu - any idea why SimpleWebsite references Microsoft.AspNetCore.Mvc and not Mvc.Core if it was meant to be coverting the sample to a test website - (https://github.com/aspnet/Mvc/commit/6a16681ed460ae59dd0b06807282074661af1b2d)?

**Comment by dougbu** [comment]
@pranavkm IIRC someone realized Mvc.Core use was an ultra-extra-advanced scenario and not something we should demonstrate for all.

**Comment by brockallen** [comment]
> 

@pranavkm IIRC someone realized Mvc.Core use was an ultra-extra-advanced scenario and not something we should demonstrate for all.

Really? Ultra advanced? It's just what you'd use when you're just building APIs. @danroth27 showed it at the MVP summit and at build and it makes sense to use it when appropriate.

**Comment by javiercn** [comment]
I would avoid qualifying as ultra-advanced or anything like that, I'd rather say what I mentioned  above:
> In general its best to stick with MVC unless you know what you are doing.

**Comment by brockallen** [comment]
Yea, I wasn't trying to be argumentative... it's just that the wording seemed to minimalize the cognitive capabilities the expected dev audience.

**Comment by BadriL** [comment]
As mentioned by @brockallen, I saw Daniel Roth demoing MVC Core for building web APIs. So, my question is, what is the benefit of using MVC Core for web APIs. Using MVC core means services related to rendering components are not registered and that we have to pretty much add even basic things like formatters, formatter mappings, data annotations, cors, etc ourselves. But what does it mean to us? I was hoping someone will provide some insight on what the benefit is, if there is any.

"stick with MVC unless you know what you are doing" is unfortunately not very helpful. Unless someone tells me what MVC core is intended for and the benefits, I will not know much and I cannot do anything with it. Or, is that what the intention is? Just don't bother using MVC core at all, since there is no benefit?

**Comment by Eilon** [comment]
@BadriL I think one way to look at it is this:

* If you use `.AddMvc()` then you get a lot of "opinionated" features, e.g. what kind of app are you building, which formatters are registered and in what order, which application conventions are there by default.
* If you use `.AddMvcCore()` ("and you know what you're doing 😄) then the behavior of your application will be decided by your own opinions and not the built-in default opinions.

**Comment by brockallen** [comment]
@BadriL I think the comment for the `ControllerBase` from the Mvc.Core library best summarizes it:

https://github.com/aspnet/Mvc/blob/941da9264bc5fea83b070cba0685d9fd6ddd16cb/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs#L25

**Comment by chuanboz** [comment]
Asp.net used to have WebApi vs. MVC difference, In the new asp.net core, I do not see WebApi related class, is that replaced by MVC and if so, shall we use Mvc.Core if we do not need any UI but just for the traditional WebApi?

I also see there is AddMvc vs. AddMvcCore extensions.

is there any public document talking about pure WebApi experience in the new asp.net core world?

**Comment by khellang** [comment]
@chuanboz If you do want to use Mvc.Core, you should check out [this blog post](http://benfoster.io/blog/bare-metal-apis-with-aspnet-core-mvc) which explains a bit more and shows you how to set up a bare metal API using it.

**Comment by chuanboz** [comment]
thanks @dougbu  and @khellang , the link you two give are very helpful and answered my questions.
