### ISSUE TITLE
Supporting partial downloads in FileResult

### ISSUE THREAD

**Issue by mrahhal** [aspnet/Mvc#4786]
Related: aspnet/StaticFiles#135

Add support for partial downloads through `accept-ranges` and `content-range` headers.

`StaticFiles` already has all the functionality in [`StaticFileContext`](https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/StaticFileContext.cs) but it's internal.

**Comment by danroth27** [comment]
@Eilon Candidate for 1.1?

**Comment by Eilon** [comment]
@jbagga - is this all covered by your mega-feature?

**Comment by jbagga** [comment]
Yes, I believe so. See https://github.com/aspnet/Mvc/issues/3702

**Comment by Eilon** [comment]
Ok, then closing as dup.
