### ISSUE TITLE
Modular website approach.ApplicationParts  Question   

### ISSUE THREAD

**Issue by developer9969** [aspnet/Mvc#4788]
Hi
I am about to build a website and I would like this to be modular.
In the past I have achieved this using the RazorGenerator and areas.
what I want to achieve is this kind of folder structure

MyCompany.Web
Modules (Folder)
    MyCompany.Modules.Admin (class library .net core with Views-ViewModels-Controllers etc..)
    MyCompany.Modules.Security (class library .net core Views-ViewModels-Controllers etc..)
    etc....

I have seen that Orchard uses applicationParts.

Now to my question.
What is the approach that should be taken to build a modular website using asp.net mvc Core 1.0?
Is there a noddy example how to build a modular website/documentation using applicationParts
any suggesions/pointers /samples would be great.

Will this be part of the RTM?

Many thanks

**Comment by javiercn** [comment]
Hi,

the goal of application parts is to make easier for people to customize the parts of the MVC framework where we do discovery, (like controllers, view components, tag helpers, etc.) and to make those things easy to customize.

Building a modular application involves many other concerns that application parts don't handle, (like configuration, deployment of files to the right folders, module management, etc.)

For building a modular application application, something like Orchard is better suited for the scenario you are mentioning. @sebastienros can give you some pointers.

**Comment by developer9969** [comment]
thanks for your reply.
I knew that my question was too vague.
Building modular applications using asp.net /mvc has never been something that came out of box or well documented.
I totally understand that was out of the rimmet of what you guys provide.
I will look into it and possibly ask @sebastienros if he has any simpler example than orchard.

thanks again

**Comment by dazinator** [comment]
The `ApplicationParts` system does make it a lot easier to wire up MVC components from your modules. Your application must first determine where it's modules are (detection) which ones should be loaded (whitelisting / blacklisting?) and then once it has the candidates, it can ask MVC to include them when scanning for its various parts like Controllers, TagHelper's etc - and this last bit is where the ApplicationParts API comes in. In addition to that though, be careful if you have Razor files that also reference these "external" assemblies, as in that case you will also need to configure Razor's CompilationOptions to include those references. 

The area I have struggled with the most out of all this, is with Content. This massively changed from RC1 to RC2. When you have content in seperate projects (like .js files, .cshtml files etc) and you build,   that content is not output into the main applications output directory - even when setting "copyToOutput" in project.json. To workaround this I went down the path of "embedding" content within the assembly (as the referenced assembly ovbiously does end up in the output directory of the application), and then using `EmbeddedFileProvider`'s within my application to allow StaticFiles to served, and Content to be located, from within my Module assembies. This last part is a massive pain as all Embedded content seemingly ends up in one directory in the compiled assembly and you essentially lose the original directory information. This makes it tricky to set up different FileProviders, for example, to set up one `EmbeddedFileProvider` to serve only static files (wwwroot) and another to serve Content (i.e Views/**), and so if you are not careful you can end up using an EmbeddedFileProvider for StaticFiles and serving not just embedded static files, but also embedded code files (.cshtml etc)

**Comment by rynowak** [comment]
> Your application must first determine where it's modules are (detection) which ones should be loaded (whitelisting / blacklisting?) and then once it has the candidates, it can ask MVC to include them when scanning for its various parts like Controllers, TagHelper's etc - 

Note that this is only required if you need to include modules that you **don't** reference as project references. MVC should detect everything that do you do reference. If this isn't working correctly, it's a bug, please let us know :laughing: 

When you do an assembly that you don't reference, adding it as an application part should like up all of the concerns that use part.

> In addition to that though, be careful if you have Razor files that also reference these "external" assemblies, as in that case you will also need to configure Razor's CompilationOptions to include those references.

Again this should only be a problem if you have Razor files that have dependencies that weren't referenced. In 1.0.0 we should be adding all of the assemblies for you as references, so this won't be a manual process unless you're not adding it as a reference or a part.


===========

> When you have content in seperate projects (like .js files, .cshtml files etc) and you build, that content is not output into the main applications output directory - even when setting "copyToOutput" in project.json.

/cc @davidfowl @pranavkm - what are the expectations here?

> To workaround this I went down the path of "embedding" content within the assembly (as the referenced assembly ovbiously does end up in the output directory of the application), and then using EmbeddedFileProvider's within my application to allow StaticFiles to served, and Content to be located, from within my Module assembies. This last part is a massive pain as all Embedded content seemingly ends up in one directory in the compiled assembly and you essentially lose the original directory information. 

/cc @davidfowl - this seems unintended and broken, I'd suggest opening an issue on https://github.com/dotnet/cli


We recognize that right now the content part of this picture is pretty manual. We'd like to make it better in the future and have started to have some conversations about it internally. Nothing really to share besides that at this point, but you're not alone in giving us feedback about it.

**Comment by pranavkm** [comment]
The `copyToOutput` issue is known - https://github.com/dotnet/cli/issues/2902.

**Comment by dazinator** [comment]
Thanks.

> Note that this is only required if you need to include modules that you don't reference as project references. MVC should detect everything that do you do reference. If this isn't working correctly, it's a bug, please let us know :laughing:

Yep - working as described.

> Again this should only be a problem if you have Razor files that have dependencies that weren't referenced. In 1.0.0 we should be adding all of the assemblies for you as references, so this won't be a manual process unless you're not adding it as a reference or a part.

Yep - working as described.

"Dependencies that aren't references" are not really dependencies - not sure how best to describe this, perhaps the word "Extension" is better. So yes, I was referring to loading Extensions :) 

>  what are the expectations here?

This issue is tacking this: https://github.com/dotnet/cli/issues/2902 - however I am not really sure what the outcome is or how / when / if it will be addressed.

> We recognize that right now the content part of this picture is pretty manual. We'd like to make it better in the future and have started to have some conversations about it internally. Nothing really to share besides that at this point, but you're not alone in giving us feedback about it.

That's great. One big area about content and copying, is the inevitable "If i edit a .js file in the project, can i then just refresh the browser".

Because in RC2 content is now `copied` to the output directory - this would imply that editing a .js file in your project directory does nothing - now we have to rebuild the project so that it is copied to the output dir, and then reload. This is not a nice development workflow. You suffer from the same problem if using EmbeddedFile providers.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
