### ISSUE TITLE
TagBuilder MergeAttribute with null value bug?

### ISSUE THREAD

**Issue by DmitrySikorsky** [aspnet/Mvc#4790]
TagBuilder tb = new TagBuilder("input");

tb.MergeAttribute("value", null);

This will make tb unusable with NullReferenceException. It worked with no problems in RC1. (Null attributes just haven't been rendered.)

Is it correct behavior and should I add checking for null of value argument everywhere?

**Comment by ctyar** [comment]
Already fixed in https://github.com/aspnet/Mvc/issues/4710
you can use `string.Empty` as a workaround for now

**Comment by DmitrySikorsky** [comment]
Thanks!
