### ISSUE TITLE
Follow RESTful conventions in new Web App project template

### ISSUE THREAD

**Issue by eavonius** [aspnet/Mvc#4794]
I have been messing around with the aspnet core 1.0 rc2 release and I'd like to make a few suggestions. When you create a new aspnet core "Web Application" using the template and "Individual User" authentication, the default controllers and views that are generated are a mish-mash of actions and views that don't enforce good RESTful MVC resource naming conventions.

In most MVC apps (rails, ASP.NET MVC, expressjs, etc.) models and their relationships are the heart of the application's structure. If the models and their relationships are designed well, the rest of the application's controllers and views follow suit by consistently following the resource naming conventions.

As an example, the devise framework used in many rails applications also provides user authentication, profile management, and typical things like password recovery as is also the case in this generated code. However, that framework follows RESTful MVC conventions and so the generated code's conventions are no different than that which a developer would create themselves. 

I would like to see the generated Account and Manage controllers restructured to follow RESTful resource conventions. Account should have its own create, edit, update, show views. Edit is currently essentially the Manage->Index view. Manage is not a resource/model, so why is it a controller? Passwords should have their own controller if there are separate views for editing your password for example, not shoved into the Manage controller.  For example, if your app allows users to edit a password, this goes in the Passwords controller, Edit action. If passwords don't need an index or show page, just don't create them - but don't bundle password management into "Manage". Login should be Sessions->New and logout Sessions->Destroy. Again, take a look at devise - they do this very well.

Another suggestion would be to have a ViewModels root folder instead of adding it as a sub-directory of Models, with sub-directories named after the controller. For example ViewModels\Account or ViewModels\Password. The classes within are named after the action, for example ViewModels\Account\Create.cs, ViewModels\Account\Edit.cs.

Thanks for your consideration.

**Comment by pranavkm** [comment]
@rustd, should this go in the Templates repo - https://github.com/aspnet/Templates?

**Comment by eavonius** [comment]
Sorry guys, still getting the lay of the land on all the dotnet core repos :)

**Comment by rustd** [comment]
@eavonius can you please repost it in https://github.com/aspnet/Templates

**Comment by eavonius** [comment]
Done. Thanks folks, closing this issue.
