### ISSUE TITLE
Model metadata provider based on runtime config

### ISSUE THREAD

**Issue by RickBlouch** [aspnet/Mvc#4795]
I am looking to tie into the model binding & Metadata provider system so that I can create html forms based on customer configurations.  I have a single c# model object that represents the html form, its fields and their data annotation validation attributes.  In MVC4 I achieved this by creating a custom model binder, a model metadata provider, and a model validator provider.  Based on the specific screen & tenant, I load the above object and include it as part of my viewmodel.  I have a PartialView & EditorTemplates that handle rendering the UI which in turn utilize the ModelMetadataSystem to generate the appropriate client side validation attributes.

I believe a key component to making this work was the ModelMetadataProvider abstract class method overrides which provided a modelAccessor.  Through this accessor I was able to retrieve the runtime configurations on the model object and create the appropriate ModelMetadata.

```
public abstract ModelMetadata GetMetadataForProperty(Func<object> modelAccessor, Type containerType, string propertyName);
public abstract ModelMetadata GetMetadataForType(Func<object> modelAccessor, Type modelType);
```

I am trying to move that same concept over to RC2 now and I have noticed that the IModelMetadataProvider & DefaultModelMetadataProvider do not provide the same modelAccessor.  What I haven't been able to figure out yet is if there is a new way to do the same thing as I was doing before.

In my RC2 solution, I have the view & modelbinding portion working which is creating my model object, retrieving the form values from the valueProvider & loading the specific customer configurations.  I am now mostly concerned with how I should add the validation metadata so that the appropriate client side attributes are created & the appropriate server side checks are performed.

I have tried implementing IValidationMetadataProvider but since the metadata I need is based on runtime configurations that are part of the model object & there is no modelAccessor I can't load them here.

I then tried to override DefaultModelMetadataProvider 
```
public virtual IEnumerable<ModelMetadata> GetMetadataForProperties(Type modelType);
public virtual ModelMetadata GetMetadataForType(Type modelType);
```
but again, without the modelAccessor I'm not sure how I can get access to the model so that I can create the metadata based on its configuration.  As part of this attempt I tested simply hardcoding a RequiredAttribute and that seemed to give me the desired outcome, with the obvious issue that now every field is required all the time regardless of the configuration.  I have also noticed that the DefaultModelMetadataProvider is doing some caching based on Type. In my scenario the Type would be the same for many different customer configurations so I need to somehow cause this Type not to be cached.

Is there some other way to accomplish this feature in RC2?

Thanks!

**Comment by dougbu** [comment]
The `ModelMetadata` system in ASP.NET Core MVC is entirely `Type`- and property-based. `IMetadataDetailsProvider` implementations are invoked once per type and one per property. Then the details are cached for the lifetime of the application.

Some parts of the system especially HTML generation (HTML and tag helpers in particular) use `ModelExplorer` instances which combine metadata and the current `Model` accessor. But the `ModelMetadata` cannot vary as the accessor or the `object` it references change. Doubtful this is what you're looking for.

Could you clarify "runtime configurations"? We may have support for your scenario but it's not clear from your description.

**Comment by RickBlouch** [comment]
Thanks for the detailed information.  That more or less confirms my understanding after reading through the source code.  The term runtime configurations was probably not the best choice.  My original intent was to retrieve `List<ValidationAttribute>` from a config (stored in my database) and attach them as validation metadata to a property on my model at runtime.  In MVC4 this was possible through a custom `ModelMetadataProvider` using its `modelAccessor`. 

I can provide a sample project next week that better demonstrates the scenario, but a stripped down version of the workflow would look like the following.  The idea is that on a GET action method, an instance of ConfigurableForm is hydrated from the DB and passed to a view for rendering.
```
public class ConfigurableForm
{
     public string FormName { get; set; }
     public List<TextBox> FormInputFields;
}
```
```
public class TextBox
{
     public string Id { get; set; }
     public string Label { get; set; }
     public string Value { get; set; }
     public string Placeholder { get; set; }
     public List<ValidationAttribute> ValidationAttributes;
}
```
In a view I would loop over the FormInputFields which calls an EditorFor for TextBox. I use the input tag helper to render the textbox and use the Value property as the property that will hold the user input.  
```
<input asp-for="Value" Type="text" ... />
```

Then in a custom model binder for ConfigurableForm, I load the same config as was loaded previously based on the form name.  I then gather and populate the Value property for each textbox from the value provider.  At this point I have an instance of ConfigurableForm that has the raw user input (Not validated yet) and a list of validation attributes to be applied to each TextBox's Value property.

Again, my original thought was to provide a custom `ModelMetadataProvider` that would use a `modelAccessor` to inspect each Textbox's ValidationAttributes and create the appropriate `ValidationMetadata` for 

So since I can't tie into the ModelMetadataProvider with this scenario because my metda, how else can I get the input TagHelper to merge the correct data annotation validation attributes

**Comment by dougbu** [comment]
One possibility may be subclassing [`DefaultHtmlGenerator`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs) to override [`AddValidationAttributes()`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L1299-L1340). That method should be passed all the information you need.

**Comment by RickBlouch** [comment]
That worked.  I did as you suggested to handle generating the client side validation attributes, and handled server side validation directly in the custom model binder.  Thanks!

**Comment by achingono** [comment]
@RickBlouch I'm trying to do the same thing. Would you mind showing me how you did it either in MVC4 or in ASP.NET core?
