### ISSUE TITLE
Naming of/in/around ActionDescriptor, ParameterDescriptor, IControllerArgumentBinder, etc.

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#4797]
### Context

- The `ActionDescriptor` has two `IList<ParameterDescriptor>` properties, `Parameters` and `BoundProperties`:

  - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Abstractions/ActionDescriptor.cs#L42
  - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Abstractions/ActionDescriptor.cs#L47

- `BoundProperties` appears to be used only for binding to controller properties:

  - https://github.com/aspnet/Mvc/blob/e63f094a5fce193de079c9ec117415b5fdbe39d4/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerArgumentBinder.cs#L75

- There are two subclasses of `ParameterDescriptor`, called `ControllerParameterDescriptor` and `ControllerBoundPropertyDescriptor`:

  - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Controllers/ControllerParameterDescriptor.cs
  - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Controllers/ControllerBoundPropertyDescriptor.cs

-  There are two types called `IControllerArgumentBinder` and `ControllerArgumentBinder`:

  - https://github.com/aspnet/Mvc/blob/e63f094a5fce193de079c9ec117415b5fdbe39d4/src/Microsoft.AspNetCore.Mvc.Core/Controllers/IControllerArgumentBinder.cs
  - https://github.com/aspnet/Mvc/blob/e63f094a5fce193de079c9ec117415b5fdbe39d4/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerArgumentBinder.cs

### Comments

The naming is inconsistent between `Parameters` and `BoundProperties` on `ActionDescriptor`. They should both be either prefixed with `Bound` or not. Because `ActionDescriptor` already has a property called `Properties`, the logical choice would be to add the prefix to the `Parameters` property of `ActionDescriptor`.

It seems kind of like `ActionDescriptor` is 'pretending' to be agnostic of where the action parameters can be bound to by exposing the same `ParameterDescriptor` type as two separate properties that clearly hint at different targets. I don't see anywhere that the `ParameterInfo` or `PropertyInfo` properties of `ControllerParameterDescriptor` or `ControllerBoundPropertyDescriptor` are retrieved, or where a `ParameterDescriptor` is cast to one of those types or otherwise checked for its type, though I could imagine there being reason for a developer or library author to make use of that at some point. It would be more 'up-front' for the `ActionDescriptor` to reference those two types specifically for its properties (which means moving those two types to the same folder/namespace of `ParameterDescriptor` and giving them more appropriate 'generic' names.) If possible, `ParameterDescriptor` should then be marked `abstract`.

There is a naming and concept struggle going on with `ParameterDescriptor` (plus its subclasses) and `IControllerArgumentBinder`/`ControllerArgumentBinder` (plus some of their method names.) If it were just method parameters, I could see saying that we were binding to the arguments passed to the method for it to use as its parameters, but since we are binding to properties as well, it would seem more sensible to think of 'parameter' in the sense of an 'action parameter' rather than a 'method parameter'. Because of this, and in addition to the previous paragraph, I feel that the `IControllerArgumentBinder`/`ControllerArgumentBinder` types (and their relevant methods) should be renamed something that sufficiently indicates what they do without becoming entangled in the muddied usages of the words 'argument' and 'parameter'.

### Summary

- Rename `ActionDescriptor.Parameters` to `ActionDescriptor.BoundParameters`
- Rename `ParameterDescriptor` to something like `ActionBindingTargetDescriptor`; mark with `abstract` if feasible
- Rename `ControllerParameterDescriptor` to `ActionParameterDescriptor`; move it to `Microsoft.AspNetCore.Mvc.Abstractions/Abstractions`
- Rename `ControllerBoundPropertyDescriptor` to `ActionPropertyDescriptor`; move it to `Microsoft.AspNetCore.Mvc.Abstractions/Abstractions`
- Rename `IControllerArgumentBinder` and `ControllerArgumentBinder` to `IControllerActionBinder` and `ControllerActionBinder`
- Rename `IControllerArgumentBinder.BindArgumentsAsync` to `IControllerArgumentBinder.BindActionAsync`

**Comment by rynowak** [comment]
It's intended that all of the `ControllerActionDescriptor` related types are in the core package and not in the abstractions package. If we get substantial feedback about real scenarios where they are needed we can move them in the future, but `.Abstractions` is intentionally light.

Regarding the comments about the descriptors and having two collections vs polymorphism, I agree that it could be better but I don't think the suggestions here really address this issues. Along with the design of `IControllerArgumentBinder` this is something we're likely to revisit in a real way in a future breaking changes release (like a 2.0.0). 

==== 

I think the intent (in the future) would be to have the binding infrastructure be able to work directly from `ActionDescriptor.Parameters` instead of requiring a downcast to `ControllerActionDescriptor`. Then we wouldn't be 'pretending' as you rightly point out. This isn't going to happen for 1.0.0 though.

**Comment by tuespetre** [comment]
Thanks!
