### ISSUE TITLE
Range Requests support

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#480]
https://aspnet.codeplex.com/SourceControl/latest#Samples/WebApi/HttpRangeRequestSample/ReadMe.txt

| 92 | 10188 | Reported By: Kiran Challa |

**Comment by danroth27** [comment]
@Eilon I think we can close this as a duplicate of #4786. I believe the main scenario for range requests is partial file downloads.

**Comment by danroth27** [comment]
We can revisit adding more general support for range requests based on customer feedback.
