### ISSUE TITLE
Naming inconsistency between ExcludeBindingMetadataProvider and ValidationExcludeFilter

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#4801]
`ExcludeBindingMetadataProvider` follows the convention of being some kind of `IBindingMetadataProvider`, but `ValidationExcludeFilter` does not follow the convention of being some kind of `IValidationMetadataProvider`. It should be renamed to `ExcludeValidationMetadataProvider` to be consistent.

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidationExcludeFilter.cs
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Metadata/ExcludeBindingMetadataProvider.cs

Also, I am not sure why `ValidationExcludeFilter` should be in the `Validation` folder/namespace when `ExcludeBindingMetadataProvider` is not. It seems like they could be siblings.

**Comment by rynowak** [comment]
Yeah, I think you're right about this. `ValidationExcludeFilter` was a legacy name based on an older name for the feature. We don't have any particular strong feelings about 'conventions' on things like this but the naming isn't good.

**Comment by rynowak** [comment]
31ec88526ad236b7261fed1e88fa6c536c45f60e
