### ISSUE TITLE
Placement and naming inconsistency of some Controller-related types

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#4803]
I count ~~five~~ four Controller-related interfaces:

    - `IControllerActivator` (`Microsoft.AspNetCore.Mvc.Controllers`)[`Core/Controllers`]
    
        - `DefaultControllerActivator` (`Microsoft.AspNetCore.Mvc.Controllers`)[`Core/Controllers`]
    
        - `ServiceBasedControllerActivator` (`Microsoft.AspNetCore.Mvc.Controllers`)[`Core/Controllers`]
    
    - `IControllerArgumentBinder` (`Microsoft.AspNetCore.Mvc.Controllers`)[`Core/Controllers`]
    
        - `ControllerArgumentBinder` (`Microsoft.AspNetCore.Mvc.Internal`)[`Core/Internal`]

    - `IControllerFactory` (`Microsoft.AspNetCore.Mvc.Controllers`)[`Core/Controllers`]
    
        - `DefaultControllerFactory` (Microsoft.AspNetCore.Mvc.Controllers)[`Core/Controllers`]

    - `IControllerPropertyActivator` (`Microsoft.AspNetCore.Mvc.Controllers`)[`Core/Controllers`]
    
        - `DefaultControllerPropertyActivator` (`Microsoft.AspNetCore.Mvc.Internal`)[`Core/Internal`]
        
        - `ViewDataDictionaryControllerPropertyActivator` (`Microsoft.AspNetCore.Mvc.ViewFeatures`)[`ViewFeatures/ViewFeatures`]

- It seems that `ControllerArgumentBinder` should follow the `Default` convention and become `DefaultControllerArgumentBinder`
- It seems that `ControllerArgumentBinder` and `DefaultControllerPropertyActivator` belong in the `Controllers` sub-namespace and subfolder rather than `Internal`. This is apparent when comparing these interfaces/classes among themselves but also when comparing this set of Controller-related types to, say, the ViewComponent-related types.

**Comment by javiercn** [comment]
> IControllerTypeProvider` (`Microsoft.AspNetCore.Mvc.Controllers`)[`Core/Controllers`]
> 
>     - `DefaultControllerTypeProvider` (`Microsoft.AspNetCore.Mvc.Controllers`)[`Core/Controllers`]
> 
>     - `StaticControllerTypeProvider` (`Microsoft.AspNetCore.Mvc.Controllers`)[`Core/Controllers`]

I don't think any of these interfaces/classes exist anymore.

**Comment by tuespetre** [comment]
You're right. I must have derailed onto an old head off of a search. Thanks!

**Comment by rynowak** [comment]
We're going to move the interfaces `IControllerArgumentBinder` and `IControllerPropertyActivator` to `.Internal` for 1.0.0. We don't believe that the design in these areas is 100% baked for the long term future, and so we want to reserve the right to make changes. 

> It seems that ControllerArgumentBinder should follow the Default convention and become DefaultControllerArgumentBinder

Sure, but it's going to remain in internal. We don't think the API surface here is baked yet.

**Comment by rynowak** [comment]
baf0b6a5c7ed49ac734d7a2cf137f40750f50542
