### ISSUE TITLE
Enabling Randomized Hashes

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#4805]
How can I enable [randomized hashes](https://msdn.microsoft.com/library/jj152924.aspx) in an xproj project. Normally done like so:

```
<?xml version ="1.0"?>
<configuration>
   <runtime>
      <UseRandomizedStringHashAlgorithm enabled="1" />
   </runtime>
</configuration>
```

Do I use the web.config file? Do I use the `runtimeOptions` section of project.json? Is this setting available and working for .NET Core? Lots of questions about this obscure setting.

**Comment by pranavkm** [comment]
This would be a question for the CLI - https://github.com/dotnet/cli

**Comment by RehanSaeed** [comment]
Closed and moved: https://github.com/dotnet/cli/issues/3382
