### ISSUE TITLE
Split up MVC route handler

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4807]
We should split up the code paths for conventional routing and attribute routing **during** the routing phase so we can remove a few warts and hacks.

More details copied from the PR:

> This change splits up the conventional routing path from the attribute
routing path inside routing, instead of inside MvcRouteHandler. Each
attribute route group now gets its own instance of
MvcAttributeRouteHandler which just knows about the actions it can
reach.

> This removes the concept of a route-group-token and removes the lookup
table entirely for attribute routing. This also means that the
DefaultHandler on IRouteBuilder will not be used for attribute routes,
which we are OK with for 1.0.0.

> The action selector's functionality is now split into two methods. We
think this is OK for 1.0.0 because any customization of IActionSelector
up to now had to implement virtually the same policy as ours in order to
work with attribute routing. It should now be possible to customize the
selector in a meaningful way without interfering with attribute routing.

**Comment by rynowak** [comment]
Approved by @Eilon for 1.0.0

**Comment by ajaybhargavb** [comment]
Dup of #4293

**Comment by dougbu** [comment]
@rynowak should this be labelled as a dupe instead of Ready?

**Comment by ajaybhargavb** [comment]
Done
