### ISSUE TITLE
ViewResult and PartialViewResult classes are inconsistent

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/Mvc#4813]
Currently, to get the model from a `ViewResult`, you have direct property `.Model`. On the other hand `PartialViewResult` does not have such property and to access the model, you need to write `.ViewData?.Model`. I believe both classes should be consistent in their public properties.

**Comment by dougbu** [comment]
`ViewResult` and `PartialViewResult` in MVC 5 both have a `Model` property because they subclass `ViewResultBase` and the property lives there.

**Comment by Eilon** [comment]
Yeah we could definitely add some more convenience properties. Should look at ViewComponentViewResult or whatever it's called as well.

**Comment by cjqian** [comment]
cc @NTaylorMullen
