### ISSUE TITLE
1.0.0-rc2-final version of ASP.NET Core 1.0 has ModelClientValidationRule missing

### ISSUE THREAD

**Issue by vdshett** [aspnet/Mvc#4816]
1.0.0-rc2-final version of ASP.NET Core 1.0 has ModelClientValidationRule missing. So how do we do custom unobtrusive validation now?

**Comment by javiercn** [comment]
@rynowak

**Comment by Eilon** [comment]
cc @dougbu as well.

Was it there, but we took it away? If so, why, and what is the alternative, if any?

**Comment by Eilon** [comment]
Ah, this is perhaps something @rynowak removed and now we have https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/ModelBinding/Validation/IClientModelValidator.cs instead.

**Comment by Eilon** [comment]
And indeed, this is mentioned here: https://github.com/aspnet/Announcements/issues/179

**Comment by vdshett** [comment]
Hi. Thanks for the prompt reply.

I yet do not understand how this can be used for the validation rule to be inserted on client side.

Sample Code in RC1

 public class PhoneNumberIsValidValidationRule : ModelClientValidationRule
    {
       public PhoneNumberIsValidValidationRule(string errorMessage) : base("phonenumberisvalid",  errorMessage)
    {
       }
   }


Client side script then refers to : phonenumberisvalid

**Comment by kroniak** [comment]
+1 

I dont understand refactoring too.

In RC1 was in ValidationAttribute:

```c#
public IEnumerable<ModelClientValidationRule> GetClientValidationRules(ClientModelValidationContext context)
		{
			yield return new ModelClientValidationRule("checkrequired", FormatErrorMessage(context.ModelMetadata.GetDisplayName()));
		}
```

and on client side:

```js
 <script>
        if ($.validator) {
            // Checkbox Validation
            $.validator.addMethod("checkrequired", function (value, element) {
                var checked = $(element).is(":checked");
                return checked;
            }, "");
            if ($.validator.unobtrusive) {
                $.validator.unobtrusive.adapters.addBool("checkrequired");
            }
        }
    </script>
```

How to convert to 1.0.0?

**Comment by dougbu** [comment]
The JavaScript is unchanged. But implement `IClientModelValidator` in the new world. It's easiest if the implementation is an `Attribute`.

See https://docs.asp.net/en/latest/mvc/models/validation.html#client-side-validation for more information.

**Comment by christiandelbianco** [comment]
Ok, but how can I know - within the code of my ValidationAttribute implementing IClientModelValidator, the html name or ID assigned to the html rendered control ? In previous ersion, this was possible using:

public IEnumerable<ModelClientValidationRule> GetClientValidationRules(ModelMetadata metadata, ControllerContext context)
    {
        **ViewContext vwContext = context as ViewContext;
        var fieldId = vwContext.ViewData.TemplateInfo.GetFullHtmlFieldId(metadata.PropertyName);**

This was very usefull expecially if you have to create a custom validation attribute that compare this property with another one present in the same ViewModel.

Now, how can I do that ?

**Comment by dougbu** [comment]
@christiandelbianco `TemplateInfo.HtmlFieldPrefix` is always an empty string in an action. So, just use `metadata.PropertyName` to match your previous code.

Of course, the calculated `fieldId` won't indicate where the validated property is relative to the top-level model. Validators simply don't have that information and didn't get it in earlier versions. This is why `[Remote]` uses `"*." + propertyName` for example. In other cases, client-side JavaScript handles converting property names to CSS selectors.

**Comment by christiandelbianco** [comment]
Hi Doug Bunting, thanks for your replay. I have to admit that my previous explanation was not clear.
What I need is a ViewModel custom attribute with client side check.

```
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, AllowMultiple = false)]
    public abstract class ConditionalValidationAttribute : ValidationAttribute, IClientValidatable
    {
        protected readonly ValidationAttribute InnerAttribute;
        public string DependentProperty { get; set; }
        public object TargetValue { get; set; }
        protected abstract string ValidationName { get; }

        protected virtual IDictionary<string, object> GetExtraValidationParameters()
        {
            return new Dictionary<string, object>();
        }

        protected ConditionalValidationAttribute(ValidationAttribute innerAttribute, string dependentProperty, object targetValue)
        {
            this.InnerAttribute = innerAttribute;
            this.DependentProperty = dependentProperty;
            this.TargetValue = targetValue;
        }

        protected ConditionalValidationAttribute(ValidationAttribute innerAttribute, string dependentProperty)
        {
            this.InnerAttribute = innerAttribute;
            this.DependentProperty = dependentProperty;
        }

        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var containerType = validationContext.ObjectInstance.GetType();
            var field = containerType.GetProperty(this.DependentProperty);
            if (field != null)
            {
                var dependentvalue = field.GetValue(validationContext.ObjectInstance, null);

                if ((dependentvalue == null && this.TargetValue == null) || (dependentvalue != null && dependentvalue.Equals(this.TargetValue)))
                {
                    if (!InnerAttribute.IsValid(value))
                    {
                        return new ValidationResult(this.ErrorMessage, new[] { validationContext.MemberName });
                    }
                }
            }
            return ValidationResult.Success;
        }

        public IEnumerable<ModelClientValidationRule> GetClientValidationRules(ModelMetadata metadata, ControllerContext context)
        {
            var rule = new ModelClientValidationRule()
            {
                ErrorMessage = FormatErrorMessage(metadata.GetDisplayName()),
                ValidationType = ValidationName,
            };

            string depProp = BuildDependentPropertyId(metadata, context as ViewContext);
            rule.ValidationParameters.Add("dependentproperty", depProp);

            if (this.TargetValue != null)
            {
                string targetValue = (this.TargetValue ?? "").ToString();
                if (this.TargetValue is bool)
                {
                    targetValue = targetValue.ToLower();
                }
                rule.ValidationParameters.Add("targetvalue", targetValue);
            }

            foreach (var param in GetExtraValidationParameters())
            {
                rule.ValidationParameters.Add(param);
            }
            yield return rule;
        }

        private string BuildDependentPropertyId(ModelMetadata metadata, ViewContext viewContext)
        {
            string depProp = viewContext.ViewData.TemplateInfo.GetFullHtmlFieldId(this.DependentProperty);

            var thisField = metadata.PropertyName + "_";
            if (depProp.StartsWith(thisField))
            {
                depProp = depProp.Substring(thisField.Length);
            }
            return depProp;
        }
    }
```

With **viewContext.ViewData.TemplateInfo.GetFullHtmlFieldId(this.DependentProperty);** I could have the generated "client side ID" for another html element that I will use to generate the JQUERY validation function client side.

**Comment by dougbu** [comment]
@christiandelbianco I suggest you have a look at the [`CompareAttributeAdapter`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/CompareAttributeAdapter.cs) and its associated [JavaScript](https://github.com/aspnet/jquery-validation-unobtrusive/blob/master/jquery.validate.unobtrusive.js#L362-L369). Note the jQuery code determines the full element IDs.

But the original questions in this closed issue have been answered and this is turning into a discussion, something we don't track on GitHub (except for w.r.t. breaking changes). Please take follow-ups to StackOverflow.

**Comment by christiandelbianco** [comment]
Thanks !!!!
