### ISSUE TITLE
AttributeRouting with multiple layers causes server errors and 404's

### ISSUE THREAD

**Issue by seijikun** [aspnet/Mvc#4817]
In an ASP.NET (rc1-final1) project, I've got the following routes:
`/api/sessions/{sessionId}`
`/api/sessions/{sessionId}/slides`
`/api/slides/{sessionId}`

### Title
AttributeRouting with multiple layers causes server errors and 404's

### Functional impact
Routes are not detected properly and some routes suddenly generate server errors.

### Minimal repro steps
- Scaffold a new rc1-final Web-API project (I can not use rc2 since my linux distro is not supported yet).
- Delete the `ValuesController`
- Add two new controllers: `SessionsController`, `SlidesController`
- Put the following code into `SessionsController`:
```
using Microsoft.AspNet.Mvc;
namespace test.Controllers {
    [Route("api/[controller]")]
    public class SessionsController : Controller {
        [HttpGet("{sessionId}")]
        public IActionResult getSession(ulong sessionId){
            return new ObjectResult(sessionId.ToString());            
        }
        
        [HttpGet("{sessionId}/slides")]
        public IActionResult getSessionSlides(ulong sessionId){
            return new ObjectResult(sessionId.ToString());            
        }
    }
}
```
- Put the following code into `SlidesController`:
```
using Microsoft.AspNet.Mvc;
namespace test.Controllers {
    [Route("api/[controller]")]
    public class SlidesController : Controller {
        [HttpGet("{slideId}")]
        public IActionResult getSlide(ulong slideId){
            return new ObjectResult(slideId.ToString());            
        }
    }
}
```

### Expected result
- A request to `/api/sessions/0` maps to `test.Controllers.SessionsController.getSession()`
- A request to `/api/sessions/0/slides` maps to `test.Controllers.SessionsController.getSessionSlides()`
- A request to `/api/slides/1` maps to `test.Controllers.SlidesController.getSlide()`

### Actual result
- A request to `/api/sessions/0` generates a Server error (500)
- A request to `/api/sessions/0/slides` results in a 404
- A request to `/api/slides/1` results in a 404

Is this not supported by AttributeRouting, or did I do something wrong?

**Comment by megawebmaster** [comment]
I've got similar issue using RC2-final - when I create more than 4 layers of routing it stops working:
* api/documents/1/objects - works
* api/documents/1/objects/related - 404
* api/documents/1/objects/related/1 - 404
* api/documents/1/related - works

It does not depend on HTTP verb used. Any reason for this weird behaviour?

**Comment by javiercn** [comment]
We fixed this issue a few days ago https://github.com/aspnet/Routing/issues/316. Can you try using the nightly builds to see if that fixes your problem?

**Comment by kichalla** [comment]
As part of my verification, I tried to repro this. This does not repro for me. Looks like @javiercn fix resolves this.

**Comment by seijikun** [comment]
I upgraded my project to rc2 and the issue for the example above was gone for me as well.

**Comment by javiercn** [comment]
Thanks for reporting the issue. I'm glad the fix worked.
