### ISSUE TITLE
Add extensibility to the new CodeTree implementation of Razor.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#483]
We need to discuss, design and implement extensibility features for Razor now that it supports a CodeTree.

| 89 | 10185 | Reported By: N. Taylor Mullen |

**Comment by danroth27** [comment]
@NTaylorMullen @DamianEdwards @Eilon Is there anything specific that this issue is still tracking? Should we just close it?

**Comment by NTaylorMullen** [comment]
Nothing specific currently. This was logged back when I moved Razor away from CodeDOM and we didn't have enough bandwidth to complete the design for extensibility. As for closing this, I know @rynowak was taking a second look at the code generation system. If he feels that this issue can be re-purposed for what he's working on then awesome! Otherwise, close :+1:

**Comment by danroth27** [comment]
Close. We can open a new issue if there is anything specific we need to track.
