### ISSUE TITLE
Missing abstraction for injection into taghelpers

### ISSUE THREAD

**Issue by Reonekot** [aspnet/Mvc#4830]
Implementing SimpleInjector as an alternative DI has proven troublesome, because it looks like there still is some missing abstractions when you won't/can't replace the whole DI implementation (IServiceCollection). Currently it looks like there is no way to resolve taghelpers from another container and I'm unsure about services injected with @inject into views.

For controllers and view components there is IControllerActivator and IViewComponentActivator, but it seems there is missing a "ITagHelperActivator" or similar.

This is related to this issue pre RC2 #3752 and my discussion with Steven@SimpleInjector here: https://github.com/simpleinjector/SimpleInjector/issues/247

Currently we can work around this by cross-wiring services, but it's unfortunate that this is missing, since there are scenarios not working out of the box and where I need to educate the rest of the company about these "gotcha's".

**Comment by javiercn** [comment]
There is support for it, but you need to opt in using ```services.AddMvc().AddTagHelpersAsServices() ```https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/ITagHelperActivator.cs
