### ISSUE TITLE
RC2 : EF6.1.3 tooling

### ISSUE THREAD

**Issue by marcusien** [aspnet/Mvc#4832]
Hi,

I'd like to use code first migrations from EF6.1.3 toolings.
But even if I have the EF package in my project, the package manager console tells me this

The EntityFramework package is not installed on project 'TreeViewBuilder.Data'.

Have the same usage of EF on other projects (WPF for instance) and it works perfectly. Is there a workaround ?

**Comment by pranavkm** [comment]
Could you file this bug in https://github.com/aspnet/EntityFramework?

**Comment by pranavkm** [comment]
In that case, http://entityframework.codeplex.com/ would be the place to post this question.
