### ISSUE TITLE
Provide consistent experience of status code in api description when an action returns a DTO vs void

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#4838]
**Current Behavior**
For this action an apidescription would have status code information as 200 OK
```c#
public Product Get()
```

For this action we do NOT provide a response type description(which contains status code info)
```c#
public void DoSomething()
```

From here:
https://github.com/aspnet/Mvc/pull/4831#discussion_r66485808

cc @rynowak

**Comment by Eilon** [comment]
Should `void` result in a `204` status code automatically?

**Comment by rynowak** [comment]
This breaks the MVC. We tried this earlier

**Comment by Eilon** [comment]
Ah sure.

**Comment by Eilon** [comment]
@jbagga - please remove "Working" and add "Done" - thanks!
