### ISSUE TITLE
Discussion for MVC: IRouteBuilder.DefaultHandler not used for Attribute Routes

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4840]
#### Summary

We've made some changes for 1.0.0 to streamline the control flow of routing for attribute routes in MVC.  Conceptually, each unique route entry now has it's own handler (instance of `MvcAttributeRouteHandler`) rather than going through the same code path as conventional routes (`MvcRouteHandler`).

The effect of this is that `IRouteBuilder.DefaultHandler` is not used by attribute routes. Previously user code could configure a handler that delegated to MVC to run application after routing but before action selection. This will continue to function for conventional routes in 1.0.0 and is no longer supported for attribute routes. We plan to bring a similar feature back in a future release (see aspnet/Routing#321).
#### Changes

Affected code looks like the following... If you are not setting `DefaultHandler` **or** are not using attribute routes you will not be affected.

```
app.UseMvc(routes =>
{
    routes.DefaultHandler = new MyHandler(routes.DefaultHandler);
    ...
});
```
#### Workarounds

If you want to run some code for all actions, the most general suggestion is to implement a resource filter instead, (`IResourceFilter` or `IAsyncResourceFilter`). Resource filters run after action selection and authorization, but before model binding.

If you need to run some code before action selection then implement an `IActionConstraint` to customize disambiguation of actions. Action selection for attribute routes is not based on route values so it's likely that `IActionConstraint` can subsume these uses.

**Comment by MaximRouiller** [comment]
Thanks for giving us workarounds for potential scenarios. It's appreciated.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
