### ISSUE TITLE
BUG: Error when having a Dictionary<T, Dictionary<T2, T3>> as a @model

### ISSUE THREAD

**Issue by brunosaboia** [aspnet/Mvc#4843]
If you have a `@model` such as:

`Dictionary<string, Dictionary<string, Dictionary<int, Dictionary<int, Dictionary<int, int>>>>>`

(I know that this structure is bad, that is not the point, so don't be angry at me :smiley: )

Then Intellisense stops working for that view, and trying to access you give a compilation error, which I am attaching.

Workaround: If you wrap this weird data structure in a class, then you can access it normally.

![capture](https://cloud.githubusercontent.com/assets/1746033/15945113/c9354eca-2e5e-11e6-9402-0c3c11706e5b.PNG)

**Comment by codnee** [comment]
Look at the error line. You have '{' instead of a ',' after the key of the Dictionary.

<img width="175" alt="screen shot 2016-06-09 at 8 38 15 pm" src="https://cloud.githubusercontent.com/assets/5662780/15950996/23c31df4-2e82-11e6-9a33-60fcf04a9027.png">

**Comment by brunosaboia** [comment]
I do not, this is not my class, but the generated view class

**Comment by imranbaloch** [comment]
I am sure that you are seeing this in ASP.NET 5.x.x or before because it is fixed in ASP.NET Core(tested on RC2). Here is bug detail http://stackoverflow.com/questions/6098649/asp-net-mvc-3-razor-view-strongly-typed-list-of-tuple-problem

**Comment by brunosaboia** [comment]
How can I be sure? My Visual Studio help shows the following:

![image](https://cloud.githubusercontent.com/assets/1746033/15993781/bae3218c-30be-11e6-8b98-f02933e673e8.png)

**Comment by imranbaloch** [comment]
What I said that you are using ASP.NET MVC 5.x.x and not using ASP.NET Core. For getting ASP.NET Core. Here is the link of getting ASP.NET Core https://www.microsoft.com/net/core#windows
