### ISSUE TITLE
MapAreaRoute constraint not escaped

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#4846]
On this line: https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcAreaRouteBuilderExtensions.cs#L134

The area is a string that is used for the defaults, and the constraints. But in the case of constrains the string is evaluated as a regular expression. In my case the are looks like `"Orchard.Setup"` which would make it not work as expected because of the dot.

**Comment by sebastienros** [comment]
I would like a solution when on this extension method the constraint would be built using a `StringRouteConstraint` to exactly match the string passed as the area name. That would be equivalent to a Regex escaped solution, with the perf gain.

**Comment by rynowak** [comment]
Good find

**Comment by iscifoni** [comment]
I would like to do this issue
i have a question,  all the contraints are defined into Routing repository, the contraint StringRouteConstraint will be defined on it ?

**Comment by rynowak** [comment]
@iscifoni that's a good question

@Eilon - will we want MVC 1.1.0 to require routing 1.1.0? If we're going to add a constraint as general as this, it would be better to define it in routing, but that will make MVC require 1.1.0.

**Comment by Eilon** [comment]
MVC 1.1.x depending on Routing 1.1.x seems perfectly reasonable. Don't we need to do this for @kichalla 's RouteCreationException thing anyway?

**Comment by rynowak** [comment]
Yes we do.

Ok so @iscifoni - you'd want to add `StringRouteConstraint` to routing first, and then add usage of it to MVC.

@Eilon are you concerned about the breaking change behavior change here? We never intended to treat the area name as a regex.

**Comment by Eilon** [comment]
Yeah let's just fix this and have it be treated as a string. No idea why it was ever treated as a regex - I cannot possibly imagine that it was deliberate.

**Comment by rynowak** [comment]
Fixed by  6e5187c1ae731b09ff2bd94d65fc6c670be735f3 and aspnet/Routing@88de3d5
