### ISSUE TITLE
MapAreaRoute override existing area constraint

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#4847]
When using `MapAreaRoute` with an existing set of constraints containing the `area` entry, the entry will be overriden by the area name passed as a parameter. I would expect it to be kept in this case.
For example, I want to pass an explicit constraint object for `area` instead of a string to prevent Regex comparisons on this route.

**Comment by iscifoni** [comment]
@Eilon  This is in up-for-grabs.. I can do it ?

**Comment by rynowak** [comment]
I'm not @Eilon - but yes! 

`up-for-grabs` means that we're definitely interested in a fix and it's also a good issue for someone unfamiliar with the code to take a crack at. Please do

**Comment by iscifoni** [comment]
ok Thanks :)

**Comment by Eilon** [comment]
Yup, go for it!

**Comment by Eilon** [comment]
@ajaybhargavb assigning this to you to track @iscifoni 's PR at https://github.com/aspnet/Mvc/pull/4954.

**Comment by ajaybhargavb** [comment]
b4677a44daef94fdd0cc1890011d211e6d7e04f7

**Comment by ajaybhargavb** [comment]
Thanks! @iscifoni
