### ISSUE TITLE
Multiple Models in View

### ISSUE THREAD

**Issue by numankizilirmak** [aspnet/Mvc#4849]
will mvc support multiple models in a view in next versions?

for example with alias
@model  ...User as userModel
@model  ...Role as roleModel

**Comment by Eilon** [comment]
There are two options we recommend for this situation:

1. Create a new type, e.g. `CombinedUserAndRoleModel` that has properties for each of the sub-models.
2. Use ViewData to store the extra models, e.g. `ViewData["User"] = new UserModel();`

**Comment by numankizilirmak** [comment]
@Eilon I know that ways, I did not ask how to do that in mvc, I asked will mvc support multiple models.
because this way will be more elegant and does not CombinedUserAndRoleModel  break single responsibility?

**Comment by Eilon** [comment]
@numankizilirmak there are no plans to support that in a direct fashion.
