### ISSUE TITLE
Html string sanitizer for display

### ISSUE THREAD

**Issue by mariusWeceipt** [aspnet/Mvc#4850]
There used to be a **Sanitizer** to remove unwanted **Html fragments** for display in a view.

Is it still there under some other name / will it be supported again in the future ? If not, do you have a good solution to share ?

Thanks

**Comment by Eilon** [comment]
MVC will fully HTML-encode a string that is being rendered. We don't have any plans to support sanitizing HTML fragments.

cc @blowdart
