### ISSUE TITLE
Controllers are not dependency injected

### ISSUE THREAD

**Issue by hikalkan** [aspnet/Mvc#4855]
Hi,

Maybe I'm wrong but as I tested deeply (and checked Mvc source code), Controllers are not resolved from IServiceProvider, but only constructor arguments of them are resolved from IServiceProvider.

Is that by design? I'm very suprised. Because, I'm using a different DI framework which supports property injection. And I can not use property injection since Controller instances are not requested from IServiceProvider.

**Comment by hikalkan** [comment]
My current solution is to implement IControllerFactory and resolve from DI framework. But I think it should be resolved from IServiceProvider as default. Because, this is more proper to nature of dependency injection.

**Comment by pranavkm** [comment]
Have you added `AddControllersAsServices` in your Startup (https://github.com/aspnet/Mvc/blob/ab76f743f4ee537939b69bdb9f79bfca35398545/test/WebSites/ControllersFromServicesWebSite/Startup.cs#L37)

**Comment by hikalkan** [comment]
Did not know that. It worked. Thank you very much.

**Comment by hikalkan** [comment]
It's same for filters. Is there a way of getting them from dependency injection, so we can use property injection?
Thanks.

**Comment by javiercn** [comment]
You can implement a filter factory for your filter

**Comment by hikalkan** [comment]
Thanks, I will check it.

**Comment by rynowak** [comment]
`[ServiceFilter(typeof(...))]` is an attribute you can use when a filter needs to be retrieved from DI. Due to programming limitations of attributes we can't globbally retrieve all filters from DI.

**Comment by hikalkan** [comment]
@rynowak Thank you for more information. I registered my filter like that:

````
services.AddMvc(options =>
            {
                options.Filters.Add(typeof(AbpAuthorizationFilter));
                ....
````

So, actually it can try to get it from DI. But OK, I will also check ServiceFilter if it works as I want. Thanks.

**Comment by rynowak** [comment]
You'll want to use `.AddService(typeof(AbpAuthorizationFilter));` if you're doing it that way.

`https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Filters/FilterCollection.cs#L73

**Comment by hikalkan** [comment]
Oh, that seems exactly what I want. I'll try it. Thank you very much :)

**Comment by hikalkan** [comment]
This worked as expected. Thanks again.
