### ISSUE TITLE
Microsoft.AspNetCore.Mvc.TagHelpers.Internal.FileVersionProvider is in too specific namespace

### ISSUE THREAD

**Issue by sekera** [aspnet/Mvc#4857]
### Summary
The `Microsoft.AspNetCore.Mvc.TagHelpers.Internal.FileVersionProvider` is IMO in the wrong namespace, I'd like to use the class for resource versioning within my own components (e.g. i'd like to write an extension method which produces a HTML markup containing an image, and I would like to use the `FileVersionProvider `without using the `ImageTagHelper`)

Also the `Internal` part of the namespace suggests like that it should be used by the ASP.NET libs only - I don't see a reason why people writing their own components could not reuse the class.

### Potential fix
So, I'd like to propose to move the class to another, more generic (not under `TagHelpers` and `Internal`) parts of the namespace.

**Comment by Eilon** [comment]
At this time the type is internal because it wasn't designed to be general purpose, and we might make breaking changes to it in the future given the needs of the components that currently use it.

**Comment by tuespetre** [comment]
@Eilon any chance of adding support for a `UrlHelper` extension or something that can be used in place of `Url.Content`? I could start a new issue for it...

**Comment by Eilon** [comment]
@tuespetre please open a new issue with the specifics and we'll take a look, thanks!
