### ISSUE TITLE
How to achieve ASP.NET Core Web API documentation?

### ISSUE THREAD

**Issue by avikenjale** [aspnet/Mvc#4859]
Hello, with ASP.NET WebAPI 2.0 we could abe to manage documentation of API using `HelpPage`. Is this feature continuing with ASP.NET Core or has introduced new approach to achieve this?

**Comment by danroth27** [comment]
We don't plan to ship our own help page feature. Instead you can use the really nice Swagger documentation support that is already available from the community. Checkout out https://github.com/domaindrivendev/ahoy

**Comment by davidsmithgf** [comment]
As far as I know, the classical webapi2 help page + webapi test client (https://www.nuget.org/packages/WebApiTestClient/) is equal to swagger UI(https://github.com/domaindrivendev/Swashbuckle.AspNetCore). Am I right?

**Comment by danroth27** [comment]
@davidsmithgf Yes
