### ISSUE TITLE
Without Visual Studio template, How does the "return View();" find the right *.cshtml?

### ISSUE THREAD

**Issue by billshooting** [aspnet/Mvc#4861]
I start a new ASP.NET Core project with command line and edit it with VS Code. The code added is as below.
In StartUp.cs:
```C#
public class StartUp
{
    public StartUp(IHostingEnvironment env){}

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseStaticFiles();
        app.UseMvc(routes=>{
            routes.MapRoute(
                name:"Rule1",
                template:"{controller=Home}/{action=Index}/{id?}"
            );
        });
    }
}
```

In HomeController.cs:
```C#    
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
        public string Hello(string name)
        {
            if(name == null)
            {
                name = "";
            }
            string str = @"This a hello " + name + " from Home/Hello";
            return str;
        }
    }
```
And the files and folders inside the folder "Views" are placed as convention.

The routing function does run properly, Url like **"http://localhost:5000/Home/Hello?name=Bill"** can get the right response. But Url like **"http://localhost:5000/Home/Index"** can't. It seems the code "return View()" can't render properly. I do have the file Index.cshtml in folder Views/Home.

How to fix it?

**Comment by rynowak** [comment]
Is there an exception being thrown when you go to `/Home/Index`? This will be looking for a file like `/Views/Home/Index.cshtml` by default.

Add the [developer exception page](https://github.com/aspnet/Diagnostics/blob/dev/samples/DeveloperExceptionPageSample/Startup.cs#L11)

**Comment by javiercn** [comment]
Is also recommended that you compare your project.json and your startup code against the MvcSandbox. You might need to call UseContentRoot(Directory.GetCurrentDirectory()) and copy your views to the output as content. The exception will give us more information

**Comment by billshooting** [comment]
@rynowak @javiercn 
I should have added`UseDeveloperExceptionPage()`, that's a easy fix. I forgot to add the option: `"preserveCompilationContext": true` in `project.json`. 
Does this option mean to allow the viewengine render the *.cshtml file into *.html file in runtime?

**Comment by javiercn** [comment]
No, preserve compilación context is used to tell dotnet to embed the settings that were

**Comment by billshooting** [comment]
@javiercn So without compilation context, cshtml files can't be compiled at runtime?

**Comment by pranavkm** [comment]
@billshooting - you could add enough references (via adding custom `ApplicationPart` instances, `RazorViewEngineOptions.MetadataReferences` or `RazorViewEngineOptions.CompilationCallback`) to make the compilation work plus using the `CompilationCallback` to any `buildOptions` you might want (like `#define`s). Preserving the compilation context does these for you and is the expected workflow.
