### ISSUE TITLE
asp.net core rc2 stringlengh attribute with localization

### ISSUE THREAD

**Issue by NGancevich** [aspnet/Mvc#4864]
One more possible bug

[StringLength(100, ErrorMessage = "The Password must be at least {2} characters long.", MinimumLength = 6)]

On the interface I got

The Password must be at least 100 characters long.
but should be 6 characters long instead

Value in resx file:
The Password must be at least {2} characters long.

**Comment by dougbu** [comment]
Thanks @NGancevich 

Parameters are in the wrong order in the [`StringLengthAttributeAdapter`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/StringLengthAttributeAdapter.cs#L54-L58).

**Comment by cjqian** [comment]
c319ae51a5a575d2bd6a100f6892ab269648a5f3

**Comment by pranavkm** [comment]
Do we need a breaking change announcement for this?

**Comment by dougbu** [comment]
> Do we need a breaking change announcement for this?

No.

**Comment by NGancevich** [comment]
I have updated to asp.net core RTM (net46) but issue still exist.  Parameter {2} is still maxlength but ought to be minlength.

**Comment by dougbu** [comment]
@NGancevich fix is in next release, not 1.0.0.
