### ISSUE TITLE
AuthenticateResult.Fail(failreason) fails to propagate failreason through the stack

### ISSUE THREAD

**Issue by gvessere** [aspnet/Mvc#4865]
I am writing my own authentication middleware and upon returning AuthenticateResult.Fail("fail reason") in HandleAuthenticateAsync() I am expecting this to result in a challenge and somehow use this information during the challenge.

the "fail reason" string gets lost at some point when I would like to be able to see it passed to HandleForbiddenAsync or HandleAuthenticateAsync during the challenge. I've narrowed it down to perhaps having some properties passed in the challenge result from the result of authentication. At https://github.com/aspnet/Mvc/blob/c7a46e4caf0d1f25dd5f8bcd385af50b34b0f5dd/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L118 I wonder if the challenge result shouldn't be authenticated with properties derived from the authentication step at 
https://github.com/aspnet/Mvc/blob/c7a46e4caf0d1f25dd5f8bcd385af50b34b0f5dd/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L92

it seems that this would resolve the issue I'm seeing as the rest of the stack seems to properly pass along this informationg to HandleForbiddenAsync and HandleAuthenticateAsync.

**Comment by gvessere** [comment]
Also I would like to be able to select between different deny behaviors in my middleware (Unauthorized vs Forbidden), it seems that upon executing the challenge the behavior that is passed is always Automatic, and this always leads to HandleUnauthorizedAsync. According to https://github.com/aspnet/Security/blob/5cd236c1b069cebecf53dbe6380e39933986eb47/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L317 the Principal should be null. But there is no way to create a ticket with a null principal since the property setter is private.

**Comment by HaoK** [comment]
You shouldn't be setting the ticket directly, but you can call AuthenticateResult.Fail to return a result with a null ticket in your HandleAuthenticateAsync() method.

To change the behavior of Authorize, you should be able to IAsyncAuthorizationFilter and implement OnAuthorizationAsync however you like I believe.

**Comment by HaoK** [comment]
For your original question of how to flow the failure message out of Authenticate, that's not something we are doing today, as its mostly an internal error for the handler (logging/debugging remote auth errors mostly).  As you mention you could certainly flow your error information in the AuthenticationProperties that is returned by your Auth middleware, and then pass it along in your call to challenge.

**Comment by gvessere** [comment]
I haven't been able to trigger Forbidden, if the ticket is null, then the behavior becomes UnAuthorized.

**Comment by HaoK** [comment]
Yep, that is the behavior for Automatic that comes from the AuthenticationHandler base class.  You can always implement an Auth middleware without using that base class too.

**Comment by rynowak** [comment]
@HaoK is this still relevant?

**Comment by HaoK** [comment]
Nope, challenge behavior was removed in preview 2, so Challenge/ForbidResult give you full control now

**Comment by rynowak** [comment]
OK, closing this then since it doesn't seem to relevant for the future.
