### ISSUE TITLE
Controller in IDisplayMetadataProvider

### ISSUE THREAD

**Issue by lammia07** [aspnet/Mvc#4867]
Hi.
Is it somehow possible to access the called controller in the CreateDisplayMetadata Method of a IDisplayMetadataProvider?

BR Michael

**Comment by dougbu** [comment]
The `ModelMetadata` will be cached per-type and thus potentially used in multiple controllers. Suggest creating distinct view models where you would like your `IDisplayMetadatProvider` to provide different information.

**Comment by lammia07** [comment]
Okay thanks.
