### ISSUE TITLE
Inconsistency in API between Html.EditorFor and Html.DropDownListFor

### ISSUE THREAD

**Issue by Eneuman** [aspnet/Mvc#4868]
When adding custom htmlattributes to Html.EditorFor you do it like this:

@Html.EditorFor(model =>model.Value, new { **htmlAttributes** = new { (a)class = "form-control gray-input" } })

But when you add custom html attributes to a Html.DropDownListFor you do it like this:

@Html.DropDownListFor(m => m.Värde, Model.Alternativ, "", new { (a)class = "form-control gray-input" } )

Not only is this inconsistent but when adding the html attributes to the DropDownListFor, the intellisense says you need to add "**htmlAttributes**".

I think this is really confusing.

**Comment by dougbu** [comment]
The `DisplayFor()` and `EditorFor()` methods have `additionalViewData` parameters and those make no sense for methods such as `DropDownListFor()`. Hence the inconsistent arguments when providing HTML attributes.

Separately the IntelliSense for `DropDownListFor()` is correct -- the parameter is named `htmlAttributes`.

**Comment by Eneuman** [comment]
Yeah, I can see differences but I still think the intellisens message should change.
It says it wants an object. and it says it needs htmlAttributes but the message gives you no information about what to type in and how to do it.
