### ISSUE TITLE
Add ITagHelperActivator abstraction

### ISSUE THREAD

**Issue by dotnetjunkie** [aspnet/Mvc#4869]
Since very early on ASP.NET Core MVC contained the proper interception point for the creation of controller types using the `IControllerActivator` abstraction. Since RC2, MVC also contains the proper interception point for the creation of another root type: view components. Interception of the creation of view components is done through the `IViewComponentActivator` abstraction.

Yet another root type that is resolved using the new (DI based) configuration system is the `TagHelper`. Just as with controllers and view models, the user might want to inject his application services into his tag helpers. Currently however, there is no way to intercept the creation of tag helpers as we can do with controllers and view components.

Please add the proper abstraction so that the creation of TagHelpers can be intercepted. For instance: `ITagHelperActivator`.

**Comment by NTaylorMullen** [comment]
@dotnetjunkie is [ITagHelperActivator](https://github.com/aspnet/Mvc/blob/1.0.0-rc2/src/Microsoft.AspNetCore.Mvc.Razor/ITagHelperActivator.cs) not sufficient?

**Comment by dotnetjunkie** [comment]
Not sure how I was able to miss that interface. That does seem sufficient.
