### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#487]
We want to discuss with core - is this a middleware in the new world

OR:
We want to be able to set different error handlers per (TBD - controller, action that returns HTML, action that returns Json payload), the point is converting exceptions into helpful user payload.

We want to be able to log all errors.

This needs to be reconciled with core

| 77 | 10173 | Reported By: Yishai Galatzer |

**Comment by yishaigalatzer** [comment]
There is nothing to do here.

The general Error handling will come from middleware, as a note we have modified the filter pipeline it currently looks like this:

![image](https://cloud.githubusercontent.com/assets/1238711/5749571/f8a65e22-9bfe-11e4-92f3-9b11706fe280.png)
