### ISSUE TITLE
MapAreaRoute does not work if `{area}` segment not specified in template

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#4875]
For a request url like `/Admin/Home/Index`,

This does not work(404 response):
`routeBuilder.MapAreaRoute(name: "adminDefaultRoute", areaName: "Admin", template: "{controller}/{action}");`

This works: 
`routeBuilder.MapAreaRoute(name: "adminDefaultRoute", areaName: "Admin", template: "{area}/{controller}/{action}");`

@rynowak

**Comment by kichalla** [comment]
I could have used `MapRoute` where I supply the `area` in the template here, but the name MapAreaRoute seemed more appealing to use.
Another question would be is that If I still need to supply `area` in template when using `MapAreaRoute`, what does this extension give when I can just use `MapRoute`

**Comment by javiercn** [comment]
It's probably there for back compat with MVC

**Comment by rynowak** [comment]
https://github.com/aspnet/Announcements/issues/120

**Comment by Eilon** [comment]
From looking at https://github.com/aspnet/Announcements/issues/120, it seems that specifying the area token in the route template is *not* required.

So then what was @kichalla seeing?

**Comment by rynowak** [comment]
For the request `/Admin/Home/Index`, it's not expected that `{controller}/{action}` would match. You'd define the template as `/Admin/{controller}/{action}`

**Comment by Eilon** [comment]
Oh, well, derp, then 😄 

@kichalla can you confirm which URL you were expecting to match? If it didn't even match the pattern at all then of course it won't match, regardless of areas 😄
