### ISSUE TITLE
ContentResult forcing chunked encoding

### ISSUE THREAD

**Issue by lodejard** [aspnet/Mvc#4876]
It looks like the ContentResult is disabling response buffering in order to skip the memory allocation. But it's not setting the content length before doing the write, so it's forcing the result to be chunked. Would be much better to encode to buffer pooled bytes and set the content length before doing the write from bytes.

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ContentResult.cs#L71

Returning an ObjectResult of the string as a workaround gives the desired effect - the response buffering middleware `return "OK"` comes back with Content-Length: 2

**Comment by Eilon** [comment]
Sounds legit to me. @kichalla please consult with @rynowak and @Tratcher as needed.

**Comment by Tratcher** [comment]
DisableResponseBuffering doesn't have any affect in a default app, Kestrel doesn't implement it.

**Comment by Eilon** [comment]
BTW here's why we added it: https://github.com/aspnet/Mvc/issues/3016

**Comment by Eilon** [comment]
And this is why this sounded familiar: https://github.com/aspnet/Mvc/issues/4766

> Remove disable buffering feature from our action result classes

Perhaps we can close this bug as a dup of #4766?

**Comment by Tratcher** [comment]
ContentResult should still set Content-Length.

**Comment by Eilon** [comment]
Ah ok so not a dupe, but we want to do both.

**Comment by kichalla** [comment]
Wondering if we need to do #4766 ...Having it doesn't hurt anything and also why have the `IHttpBufferingFeature` if its not supported yet.

**Comment by Tratcher** [comment]
You're using an undefined feature for an undefined benefit. If the user wants buffering, who are you to second guess them?

**Comment by lodejard** [comment]
Tratcher is right - "If the user wants buffering, who are you to second guess them?" - in this case the application was configured with response buffering for a reason, and the ContentResult was unexpectedly counteracting that choice. I'll add a note to #4766 also. I do like that the feature exists, and that it is implemented by the ResponseBufferingMiddleware.cs, but it shouldn't be used unless there's a specific functional reason an action doesn't work with buffering enabled. Signalr server-sent events would be the only case I can think of.

https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.Buffering/ResponseBufferingMiddleware.cs 

The mvc action results should only set the content length if known, writeasync the bytes, but not call flush or disable buffering because that messes with the response handling.
