### ISSUE TITLE
Discussion: device detection mechanism

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/Mvc#4877]
I was unable to found any built-in mechanism that allow developer to build adaptive web site (css media queries not count).
It would be really nice to have some mechanism that allow me as a developer to introduce some mobile or tablet specific layout, views and behaiviors.  For some developers this feature is critical.

Adaptive web site should adjust his behaivior according to current device. Adaptive site should also have preference mechanism, with ability to switch between preferences, not matter for device (like github for example).
This could help a lot of developers to build rich and adaptive websites.

I propose to add such mechanism as separate nuget package with `Mvc` bundle. 

API could be something like this:
Firstly we need to include `Mvc.Mobile` or simillar package.
Than we should register required service and specify some options:
You could just add device detector:

```
services.AddDeviceDetector();
```

After this configuration new ViewLocationExpanders will be applied and start to search device specific views from prefixes or subfolders. Device would be detected from user agent according to lite device detection mechanism (simillar to _http://projects.spring.io/spring-mobile/_).

You could also add preference switcher mechanism, to enable switch:

```
services.AddDeviceSwitcher<UrlSwitcher>(switcherOptions => { }, deviceOptions => { });
```

If you specify device switcher, you should also map this switcher to some route:

```
route.MapDeviceSwitcher();
```

After that, you will have an ability to override default agent detetection with some preference, by calling URL in format: `/choose/{device}`.
Mechanism should provide following extensibility point:
1. Allow developer to change device codes, and aliases
2. Allow developer to use own device implementation, by adding specific device factory
3. Allow developer to introduce new device types expect regular table and mobile
4. Allow developer to switch between Switcher mechanism (by default, it should store preference in cookies, but also should be have ability to use URL switcher)
5. Allow developer to change URL generation rules

Implementation for such mechanism would not require a lot of effort, and not break anything (since it  could placed completely separate). 

Any thought on this one?

**Comment by wangkanai** [comment]
I like it better if it was implement on top of `IMvcBuilder` like this.
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc()
        .AddDeviceDetection();
}
```
And if you add options to the device detection service framework like this.
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc()
        .AddDeviceDetection(options =>
        {
            options.Mobile = MobileSubArea,
            options.Tablet = TabletSubArea,
            options.Desktop = DesktopSubarea
        });
}
```

**Comment by Eilon** [comment]
Hello, we reviewed the proposal and the PR and we don't think this is a good fit for including in ASP.NET. This could be a good fit for a community-maintained project, which we would be happy to link to.

**Comment by laskoviymishka** [comment]
@Eilon this already presented here _https://github.com/laskoviymishka/MvcDeviceDetector_ and also as nuget packeg `MvcDeviceDetector` in nuget.

**Comment by Eilon** [comment]
@laskoviymishka ah, very cool then! If you'd like to add a link to the readme here please send a PR and we can get it updated.
