### ISSUE TITLE
Trying to use a IViewLocalizer in a language-view location expanded page is confusing

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#4881]
Consider

```
/Resources:
  Views.Home.Index.fr.resx
/Views
   /Home
     Index.cshtml
```

Using `ViewLocalizer["Hello world"]` correctly picks up resources from `Views.Home.Index.fr.resx`. However, if a location specific view is added, i.e. `/Views/Home/Index.fr.cshtml`, the resource file now has to be renamed to `View.Home.Index.fr.fr.resx`. Should `IViewLocalizer` be made aware of the view location expander so that the original resx file continues to work?

**Comment by Eilon** [comment]
More info in this dup bug: https://github.com/aspnet/Mvc/issues/4881

But moving this to Backlog, which is where the other bug already was (because it's super complicated to fix this).

**Comment by rynowak** [comment]
The dupe bug points back here... I think you mean https://github.com/aspnet/Mvc/issues/5441

Should we just close this? Should we reimagine it totally?

**Comment by pranavkm** [comment]
I'd rather we close this until we have a user ask for this.

**Comment by Eilon** [comment]
Closing this due to lack of complaints about this. Either people are happy with how things work, or just haven't run into this issue. We'll revisit if it comes up again.
