### ISSUE TITLE
BUG: ViewComponents model inconsistency with MVC Views.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4882]
Based usage setting the model to `ViewData.Model` property on a `ViewComponent` result in the model being null on the view:

// NRE when invoking Default.cshtml
```
ViewData.Model = new SomeModel();
return View();
```

// works ok!
```
var model = new SomeModel();
return View(model);
```

**Comment by NTaylorMullen** [comment]
7036e2b0f500c8bd43f3fcffdd05909872792ea1
