### ISSUE TITLE
Generate html from razor view outside of an Mvc action

### ISSUE THREAD

**Issue by mrahhal** [aspnet/Mvc#4884]
I was looking at a way to generate html for sending emails (instead of  writing the body by hand). Now there are a couple of frameworks to do that (spark for example) but we already have razor and nothing really prevents it from doing it outside of an Mvc action.

I got as far as getting a `ViewEngineResult` and constructing a `ViewContext` by hand but a `RazorView` uses the `HttpContext` and this is where everything comes to a halt.

Is there a way to do this now? If not, this is really a missing piece in Mvc and Razor (for example, rails already has that built in box with Action Mailer). Is it something you're considering?

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString

**Comment by mrahhal** [comment]
Awesome! Though creating an `HttpContext` feels like a hack around the whole thing (there doesn't seem to be a need for the razor engine to require an `HttpContext` instead of a more relaxed model to me). But well if it works. Thanks.

**Comment by davidfowl** [comment]
Razor doesn't require an http context, MVC's view engine requires a viewcontext which has an http context. If you want to use Razor in a more primitive manner then look at https://github.com/aspnet/Diagnostics/blob/dev/src/PageGenerator/Program.cs

**Comment by mrahhal** [comment]
Nice, good to know.

**Comment by benaadams** [comment]
I feel a static site generator coming on...

**Comment by davidfowl** [comment]
@pakrym wrote one based on mvc that's pretty cool

**Comment by benaadams** [comment]
Generate to wwwroot + StaticFiles + ResponseCaching; database used in the "prepare" step - high perf blogging platform / slow changing portion of website

**Comment by mrahhal** [comment]
Wow, I can imagine it. That would be super cool.
