### ISSUE TITLE
Add handling of standard messages

### ISSUE THREAD

**Issue by eavonius** [aspnet/Mvc#4885]
In rails projects (upon which MVC is based) redirecting to another route as the result of finishing an action can show messages very easily. The actions do not need to declare a parameter to take the messages on the querystring - if flash[success] or flash[notice] or flash[error] are passed on the querystring, there is a partial view used by all views that just "works".

I'd like to see this added to ASP.NET MVC. I have a sample project based off ASP.NET Core RC2 where I've defined a partial that can be rendered anywhere on the page where flash messages would need to appear:

https://github.com/eavonius/aspnetcore-restful-auth-https://github.com/eavonius/aspnetcore-restful-auth-sample/blob/master/src/WebApplication1/Views/Shared/_ActionMessages.cshtml

Currently in addition to this, each action in ASP.NET MVC needs to declare these 4 parameters and then set them explicitly. What I'd propose is some way to intercept the View() method that returns an actionresult where the QueryString is checked and if any of these 4 parameters are set the ViewData would be updated automatically. If there is a concern that the names I've used here are too easy to create conflicts, perhaps it could be changed to use ViewData["Messages[Success]"] or ViewData["Messages[Error]"] instead.

**Comment by eavonius** [comment]
I've added an example pattern of how better to solve this to the repo above.

To clarify: the goal is to enable controllers to specify notification messages when they redirect to another action as the result of an action. For example, after saving an edit to the user at the /Users/Edit/Id path, the user is redirected to /Users/Details/Id with a message "Your profile has been updated successfully". This is a "success" message and typically uses bootstrap's alert-success class.

Another example is when hitting the /Users/Details/Id path, if the user doesn't exist, redirecting to /Home/Index with a message "Invalid user specified". This is an "error" message and typically uses bootstrap's alert-danger class.

To make this easier (built in) I've updated the sample project above in the following ways. I'd appreciate it someone could look at it and I am totally open to better/other ways of doing this. The goals I set out to achieve are:

* Don't require parameters on the action method signature for methods. The existing template code would have to define InfoMessage, SuccessMessage, ErrorMessage etc. as separate string parameters to any controller action method. I've found on rails projects this notification message pattern if implemented unobtrusively is used all over the site and leads to consistent communication.

* The existing code (pre-refactoring) declared Message IDs as an enum and passes these on the querystring instead of the actual string message to display. I assume this is to allow for localization - rails just passes the actual message to display in the querystring. I kept this in place with the assumption that localization was the purpose. If not, the pattern I'm proposing could be simplified even more.

* Allow views to render a partial wherever they want that will automatically display any of the four types of messages with appropriate bootstrap styling. Of course if you used materialize or some other css framework you'd just need to update that one partial.

The implementation is as follows:

* There are 4 standard querystring parameters that can be passed to any controller action dealing with messages:

https://github.com/eavonius/aspnetcore-restful-auth-sample/blob/master/src/WebApplication1/ActionMessages.cs

* The ApplicationController is a base class in my sample project that overrides the "View" methods to automatically detect any of the 4 standard message types being passed in on the querystring. If one is passed, a "Messages" dictionary that maps keys (for localization) of messages to their values is used to look up the right message to display. In the code below, ignore everything from "RedirectToLocal" method and down - these were helpers included with the new project template. I could see this code related to ActionMessages added to the base Controller class in ASP.NET MVC if it were determined a valuable pattern:

https://github.com/eavonius/aspnetcore-restful-auth-sample/blob/master/src/WebApplication1/ApplicationController.cs

* Each controller that wants to display messages declares an Enum (as with the existing pre-refactored code) with the names of the messages that are possible to display as a result of any of the actions of that controller. In the constructor, those names are mapped to their actual values. See the MessageNames enum at the top of this class and its constructor as an example:

https://github.com/eavonius/aspnetcore-restful-auth-sample/blob/master/src/WebApplication1/Controllers/UsersController.cs

* When a controller action redirects at its conclusion, any of these standard messages can be passed using the enum value. This causes the message to display. See the "Details" method of the class above for an example where ErrorMessage is passed as a route parameter. Note that the Index action of the HomeController does NOT have ErrorMessage defined - it is handled by the base ApplicationController class.

**Comment by ctolkien** [comment]
The mechanism you should use is `TempData[key]` - this is specifically used for response messages back from actions.

**Comment by eavonius** [comment]
This has been updated to use TempData. Even cleaner, but I still think this should be out of the box!

Thanks for the help!

Jayme

**Comment by rynowak** [comment]
Closing out since this has been answered
