### ISSUE TITLE
POST to an action that accepts View Model with "User" property (regardless of the type) fails

### ISSUE THREAD

**Issue by gdoron** [aspnet/Mvc#4887]
Version: RC2-final
Request just hangs until timeout, from the log:

![image](https://cloud.githubusercontent.com/assets/6141009/16204010/9290b36c-3725-11e6-9e90-0b950f3793cb.png)

**Comment by javiercn** [comment]
This sounds like a bug we fixed recently (post RC2) @rynowak or @dougbu can provide a workaround

**Comment by dougbu** [comment]
@gdoron if your `User` type is relatively complex, you may have hit #4666. Try the workaround @rynowak describes at the top of [this comment](https://github.com/aspnet/Mvc/issues/4666#issuecomment-220156872).

Please let us know whether or not that works. If not, we'll need more information or (better) a small GitHub repo that demonstrates the issue.

**Comment by gdoron** [comment]
@javiercn  @dougbu  thanks, it was a complex type (I put it in the ViewModel for convenient but assigned it myslef and overridded the assigned potentially assigned value from the user)

Thanks.

**Comment by gdoron** [comment]
@dougbu @rynowak  BTW, why the error message was regarding POSTs not allowed?

**Comment by dougbu** [comment]
>  why the error message was regarding POSTs not allowed?

Basically the system is falling apart (often running out of memory) and the exact way it falls seems a bit random.
