### ISSUE TITLE
Error Layout and render body with ASP.NET RC2

### ISSUE THREAD

**Issue by chemitaxis** [aspnet/Mvc#4889]
I'm testing RC2, and I have found a bug testing an new example from VS2015 Community (Windows 10).

Steps: 
1. Create a ASP.NET Core Web Project using VS2015 template 
2. Restore Packages
3. Compile and debug

If you see the Layout.cshtml and the Home/Index.cshtml you will see that the generated code is not correct, the render body is not working fine:

As you can see in the screen captures, the RenderBody is in the Layout, after head tag, but the code is render on a bad way:

1.- Layout code:
![screen shot 2016-06-21 at 09 13 11](https://cloud.githubusercontent.com/assets/1420409/16220998/a8f68fa8-3790-11e6-9ca0-842d3f628aa6.png)

2.- Index code:
![screen shot 2016-06-21 at 09 13 02](https://cloud.githubusercontent.com/assets/1420409/16221009/b5f88f3a-3790-11e6-8cba-4a2b2a306a08.png)

3.- Render code:
![screen shot 2016-06-21 at 09 13 55](https://cloud.githubusercontent.com/assets/1420409/16221017/c7be0a56-3790-11e6-890a-3a4c69b61da5.png)

**Comment by ctyar** [comment]
Duplicate of https://github.com/aspnet/Mvc/issues/4706 check this comment for workaround
https://github.com/aspnet/Mvc/issues/4706#issuecomment-220808090

**Comment by chemitaxis** [comment]
Thanks, I will close... very crazy this RC2 :-1:
