### ISSUE TITLE
Optimize GetCurrentPage in PagedBufferedStringWriter

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4894]
This is some sampling data shared by a customer.

![image](https://cloud.githubusercontent.com/assets/1430011/16248617/0f4971c4-37c5-11e6-9656-9c55f94cb9f0.png)

We should create a fast-path for `PagedBufferedStringWriter.GetCurrentPage()` as it's often called in tight loops. There's a lot of code here. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/PagedBufferedTextWriter.cs#L165

**Comment by rynowak** [comment]
@kichalla - this code was recently improved by @Yves57 :+1: - this is likely fixed, but we need to collect data to verify. I suggest using https://github.com/aspnet/Performance/tree/dev/testapp/LargeStaticView

The only other change we might want to make here would be to break up the current code into a 'fast page' and 'slow path' so that it can be inlined. Let me know when you've collected data and I'll help you look at it.

**Comment by Yves57** [comment]
@rynowak I would be very proud to have fixed this issue too, but I have optimized `ViewBuffer`. And I suppose that this issue is in `PagedCharBuffer`, no? :-)

**Comment by rynowak** [comment]
Yeah, I think you're right, but that's had some work done recently as well. So we need to recollect this data and see if we have anything to do.

**Comment by rynowak** [comment]
Suggesting we close this. This area was redone by @Yves57 in 1.0.0 and a few others. This bug currently isn't tracking anything.
