### ISSUE TITLE
OptimizationLevel specified in the dependency context \ primary assembly's project.json is never used when compiling views

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#4902]
`DependencyContextViewEngineOptionsSetup` and `RazorViewEngineOptionsSetup` modify compilation options - the first based on what's specified in the dependency context and second based on `IHostingEnviornment.EnvironmentName`. However the former setup's option values are always overwritten by `RazorViewEngineOptionsSetup` which runs second.

Additionally, the value set in `OptimizationLevel` determined in `DependencyContextViewEngineOptionsSetup` is incorrect - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/DependencyContextRazorViewEngineOptionsSetup.cs#L60-L62 needs to be inverted so that when your project.json says `optimize`, we choose `Release`.

**Comment by rynowak** [comment]
What's the impact of this? Does this mean we're compiling optimized views for Debug and un-optimized for Release?

If I'm a user and I want to correct this setting, what's my best bet?

**Comment by pranavkm** [comment]
@rynowak - the current behavior is `Development` -> `Debug`, `Staging` \ `Production` etc -> `Release`, so it's not entirely too bad. However, if you had `"optimize": true` in your project.json while in `Development`, views would continue to compile in `Debug`. You can use the `RazorViewEngineOptions.CompilationOptions` to change this:

```c#
services
.AddMvc()
.AddRazorOptions(options => 
{
  options.CompilationOptions = options.CompilationOptions.WithOptimizationLevel(
#if DEBUG
   OptimizationLevel.Debug
#else
   OptimizationLevel.Release
#endif
);
});
```

**Comment by pranavkm** [comment]
Self assigning. The code change is pretty minimal, most of the change here would be to add tests.
