### ISSUE TITLE
BUG: [Display(Prompt="...")] not working on textarea elements.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4903]
Model:
```
[DataType(DataType.MultilineText)]
[Display(Prompt =nameof(Issue))]
public string Issue { get; set; }
```

Using input:
*`placeholder` attribute render correctly*
```
<input asp-for="Issue" class="form-control" />

<input class="form-control" 
       type="text" 
       id="Issue" 
       name="Issue" 
       placeholder="Issue" 
       value=""
       data-val="" data-val-required="The Issue field is required."  />
```

Using textarea:
*`placeholder` attribute missing from output*
```
<textarea asp-for="Issue" class="form-control"></textarea>

<textarea class="form-control" 
          data-val="true" 
          data-val-required="The Issue field is required." 
          id="Issue" 
          name="Issue">
</textarea>

```
![image](https://cloud.githubusercontent.com/assets/3386797/16325157/ee79702e-3991-11e6-983f-15ee4e189c5b.png)

Expected:
Both textarea and input should have the `placeholder` attribute populated.

**Comment by dougbu** [comment]
A small feature gap. We implemented support for `placeholder` only in `<input>` elements i.e.`DefaultHtmlGenerator.GenerateTextArea()` lacks code we have in `DefaultHtmlGenerator.GenerateInput()`.

**Comment by Haplois** [comment]
I implemented that, and pretty sure it works. But solution wont compile now, so I'm not sure. As soon as I can compile and test I'll send a pull request.

**Comment by Eilon** [comment]
@dougbu assigning to you for PR https://github.com/aspnet/Mvc/pull/4907.

**Comment by dougbu** [comment]
a852352
