### ISSUE TITLE
Are there any rules for community related projects?

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/Mvc#4905]
Hi, guys! I want to ask whether there are any rules for the featured community related projects in the README (besides the fact that they should have something in common with ASP.NET Core MVC). Also how can a developer submit a project for a review and a featured link there? I believe in the near future a lot of packages will emerge and some sort of easy submit process may be helpful, if you want to list the best libraries out there.

**Comment by Eilon** [comment]
@ivaylokenov no particular rules, aside from the MVC team has to find the project reasonably interesting 😄 

If we get "too many" people submitting projects to include in the list, we'll want to revisit that (we obviously don't want to have 100's of projects linked from here).

**Comment by ivaylokenov** [comment]
@Eilon I am asking because I would be happy if you feature another project of mine, tightly coupled with ASP.NET Core MVC - https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc. It was featured in the latest ["This week in .NET"](https://blogs.msdn.microsoft.com/dotnet/2016/06/28/the-week-in-net-6282016/).

I hope the MVC team find it reasonably interesting :smile:

**Comment by Eilon** [comment]
@ivaylokenov just send us a PR to the readme.md file and we can merge. Looks like a cool project!

**Comment by ivaylokenov** [comment]
@Eilon Thank you very much! PR is now open :+1:

**Comment by Eilon** [comment]
Merged, thanks!

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
