### ISSUE TITLE
Missing ViewResult tests

### ISSUE THREAD

**Issue by cjqian** [aspnet/Mvc#4906]
[Here](https://github.com/aspnet/Mvc/tree/dev/test/Microsoft.AspNetCore.Mvc.ViewFeatures.Test/Internal). Should add tests similar to those of _[PartialViewResult](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.ViewFeatures.Test/Internal/PartialViewResultTest.cs)_

**Comment by Haplois** [comment]
@Eilon  @cjqian I can add these tests tomorrow if it is still up for grabs.

**Comment by Eilon** [comment]
@Haplois yes, of course! Thank you!

**Comment by Eilon** [comment]
@javiercn I'm parking this on your plate to track, then you can review @Haplois 's PR when that comes in.

**Comment by Haplois** [comment]
I migrated tests of from `PartialViewResultTest` class into same namespace and folder. But (https://github.com/aspnet/Mvc/pull/4939#issuecomment-229744040) there is a test for this already, and it's nearly the same.

What's the correct folder/namespace for these tests? Is it `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.Mvc.ViewFeatures.Internal`?

**Comment by rynowak** [comment]
The correct namespace is `Microsoft.AspNetCore.Mvc` - the namespace should be the same as the thing its testing.

Looks like `PartialViewResultTest` is in the wrong

**Comment by Haplois** [comment]
Then I'll fix that instead :)

**Comment by javiercn** [comment]
https://github.com/aspnet/Mvc/commit/4fe758240fcc4a51039565122923fe51b1920354
