### ISSUE TITLE
Question: How to customize id/name attribute names generated by Tag Helpers

### ISSUE THREAD

**Issue by alaatm** [aspnet/Mvc#4908]
Currently, tag helpers such as `InputTagHelper`, etc.. will use the CLR field name as the element id and name attributes. For example:

    public class Person
    {
        public string Firstname { get; set; }
    }

    <input asp-for="Firstname" />

will render:

    <input id="Firstname" name="Firstname" /> 

I find Pascal case ids weird for HTML. Are there any guides on how can one change this behavior? For example I might want it to be `firstname` instead.

I was looking into ways to make them camel case. It seems like id's are generated here: https://github.com/aspnet/Mvc/blob/42dd4499e0ba395d1ec45ddc549402c9c199b59f/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Rendering/TagBuilder.cs#L174

But I am not sure how I can override this behavior. Any tips would be much appreciated.

**Comment by dougbu** [comment]
@alaatm MVC doesn't currently have a single place where `id` and `name` values are determined though [`ExpressionHelper`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ExpressionHelper.cs) does a lot of the work and [`TemplateInfo.GetFullHtmlFieldName()`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/TemplateInfo.cs#L68) is responsible for merging `HtmlFieldPrefix` and (relative) expression names.

I don't recommend changing these values. For example different `name`s can easily break model binding.

**Comment by alaatm** [comment]
@dougbu Thanks for the reply and the info.
