### ISSUE TITLE
AddModelError show error on Model but not on Property/Field.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4909]
When adding model errors manually on the controller like this:

```
ModelState.AddModelError<CreateBindingModel>(m => m.Title, "already exists");
ModelState.AddModelError("title", "already exists");
ModelState.AddModelError("Title", "already exists");

```

The errors are not displayed on the property/field `Title` using this cshtml:

```
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Title" class="col-md-2 control-label"></label>
    <div class="col-md-10">
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger" />
    </div>
</div>
```

using `asp-validation-summary="All"` does display the error on the validation summary `div` but not on the property/field.

Isn't supposed that those errors, when specifying the property/field, be part of the metadata and displayed on the property/field span ( `<span asp-validation-for="Title" class="text-danger" />` ) ?

If I recall correctly, that is how it worked on MVC5. May I be missing something?

**Comment by dougbu** [comment]
The `<span>` element in your repro is invalid and will never contain server-side validation errors. Change it to
``` html
<span asp-validation-for="Title" class="text-danger"></span>
```

**Comment by Bartmax** [comment]
oh man! i can't tell you how many times I get that. Problem is scaffolding created those. Thanks and sorry. wish the taghelper will at least emit a warning on self-closing tags that weren't supposed to be self-closed.

Thanks!

**Comment by Eilon** [comment]
This is essentially a dup of https://github.com/aspnet/Razor/issues/433, which is about providing better errors/warnings when doing things with tag helpers.
