### ISSUE TITLE
RC2 - StaticFiles, Razor, and EmbeddedFilesProvider

### ISSUE THREAD

**Issue by dazinator** [aspnet/Mvc#4913]
Let's say we have a project called "ModuleA" and we embed the following files:

- wwwroot.client.js
- server.js
- Views.Shared.view.cshtml

Then in our main application, we reference ModuleA:

1. How can I configure `StaticFiles` middleware with an `EmbeddedFileProvider` that only returns the embedded files that are safe to serve up to the client (i.e ones prefixed `wwwroot`) so that it doesn't also serve up non safe embedded files such as `server.js` and `view.cshtml`.

2. How can I configure `Razor` so that it discovers the view "view.cshtml".

Note: My suspicion is that I'd need to derive my own FileProviders from `EmbeddedFileProvider` with the filtering logic. I'd then register 2 seperate `EmbeddedFileProviders` (each with the correct filtering logic), one instance for static files, and the other with Razor.

**Comment by pranavkm** [comment]
`EmbeddedFilesProvider` allows specifying a base namespace. You could assign the `StaticFilesMiddleware` an instance of `EmbeddedFilesProvider` with the namespace `MyLibNamespace.wwwroot`, my guess is that would work. For the view, you could register a different instance of `EmbeddedFilesProvider` with the root namespace.

**Comment by dazinator** [comment]
@pranavkm - thanks that does indeed work. Nice to know i didn't have to derive my own providers. Cheers.
