### ISSUE TITLE
RC2 - @addTagHelper error 

### ISSUE THREAD

**Issue by dazinator** [aspnet/Mvc#4918]
There is an assembly containing an `ViewComponent`, and it's Razor files (embedded as resources)
I load the assembly from disk:

```
var assy = Assembly.Load(somePath);
```

I register it with MVC using `ApplicationParts`

```

 var mvcBuilder = services.AddMvc();
 mvcBuilder.AddApplicationPart(assy);

```

Then I configure Razor, with an `EmbeddedFileProvider` so it can discover the Razor view, and it's `CompilationContext` so that it compile the Razor view with a reference added for the assembly itself (as that where it's model is):

```
            mvcBuilder = mvcBuilder.AddRazorOptions((options) =>
            {

                var previous = options.CompilationCallback;
                options.CompilationCallback = (compilationContext) =>
                {
                    if (previous != null)
                    {
                        previous(compilationContext);
                    }

                  compilationContext.Compilation.AddReferences(
                        MetadataReference.CreateFromFile(assy.Location));
                };
            

                var  fileProvider = new EmbeddedFileProvider(assy, "Gluon.Module.ThemeSwitcher"));
                options.FileProviders.Add(fileProvider);
            });

```

In my application, I search for, and invoke the ViewComponent dynamically - as the application doesn't have a dependency on it:

```

 public class ViewComponentHelper : IExtendedViewComponentHelper
    {
        private readonly IViewComponentDescriptorCollectionProvider _descriptorProvider;
        private readonly IViewComponentSelector _selector;

        public ViewComponentHelper(
          IViewComponentDescriptorCollectionProvider descriptorProvider,
          IViewComponentSelector selector)
        {
            _descriptorProvider = descriptorProvider;
            _selector = selector;
        }

        public Task<IHtmlContent> InvokeIfExistsAsync(IViewComponentHelper componentHelper, string name, object arguments = null)
        {
            if (!Exists(name))
            {
                return Task.FromResult<IHtmlContent>(new HtmlString(string.Empty));
            }

            if (arguments == null)
            {
                return componentHelper.InvokeAsync(name, null);
            }

            return componentHelper.InvokeAsync(name, arguments);

        }      

        private bool Exists(string name)
        {
            var comp = _selector.SelectComponent(name);
            bool exists = comp != null;
            return exists;
        }     
    }

```

The `ViewComponent` get's invoked, but there is this error during Razor compilation:

![image](https://cloud.githubusercontent.com/assets/3176632/16425653/89c42b86-3d5d-11e6-958e-2ef5c64f7bdb.png)

Any ideas what the problem might be?

Here is the contents of the Razor file:

```
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@model Gluon.Module.ThemeSwitcher.ViewModels.ThemeSwitcherViewModel

@{
    ViewData["Title"] = "Gluon";
}

<li class="dropdown themeswitcher" data-bind="visible: $root.visible">
  
</li>

```

If I remove that `addTagHelper` line in the razor file, it then complains about it again in `_Layout.cshtml`

![image](https://cloud.githubusercontent.com/assets/3176632/16425820/3b9289e8-3d5e-11e6-80b7-872ad998472f.png)

If I remove it from there too, it seems to work. Can you not have duplicate addTagHelper calls or something in the View heirarchy?

**Comment by NTaylorMullen** [comment]
Looks like it's an issue with the quotes. Duplicate of https://github.com/aspnet/Razor/issues/744

**Comment by dazinator** [comment]
@NTaylorMullen - Nice spot - yep this is indeed the issue. Was pulling my hair out.

**Comment by dazinator** [comment]
Ah damn spoke too soon.

If I remove the quotes I get this:

![image](https://cloud.githubusercontent.com/assets/3176632/16428438/c84fb1ca-3d69-11e6-9c06-f918ddf05f48.png)

**Comment by dazinator** [comment]
Ah sorry my bad! Wrong namespace that time haha
