### ISSUE TITLE
Embed and serve static files

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Mvc#4919]
I embed my views using the embedded file provider like this:
```
services.Configure<RazorViewEngineOptions>(options =>
{
    options.FileProviders.Add(new EmbeddedFileProvider(
        GetType().GetTypeInfo().Assembly,
        baseNamespace: "hwapp.EmbeddedResources"));
}); 
```
Inside the _EmbeddedResources_ directory I have my my _/js_ files which I would like to serve via _some/url_ to my views. is this possible today?

**Comment by pranavkm** [comment]
You can use `StaticFileOptions.FileProvider` to have it serve embedded content.

```C#
app.UseStaticFiles(new StaticFileOptions
{
   RequestPath = new PathString("/js"),
   FileProvider = new EmbeddedFileProvider(
     GetType().GetTypeInfo().Assembly,
     baseNamespace = "hwapp.EmbeddedResources.js"
});
```

**Comment by marcuslindblom** [comment]
@pranavkm Cool, thanks!

**Comment by marcuslindblom** [comment]
@pranavkm the `baseNamespace` seems to refer to the name of the directory where the `Startup.cs` is located, in my case `hwapp`. Is it possible to configure the namespace from the `project.json` or how can I register the `EmbeddedFileProvider` so it works regardless of the name of the parent directory?

**Comment by pranavkm** [comment]
@marcuslindblom, you can use `namedResource` to specify the "full name" for a resource. 
```
"namedResource": {
  "CustomNamespace.File.js": "Test.js"
}
```

That said, this question is probably more appropriate for the CLI (https://github.com/dotnet/cli/). You should get more visibility for the project.json format and compilation there.

**Comment by marcuslindblom** [comment]
Ok, thanks!
