### ISSUE TITLE
Virtual Path Helper

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#492]
Server paths:

Convert "~/" in razor to the virtual site path. - Do we even need it?

We use this in Razor views (specifying partials \ layouts etc). This is required for recognizing rooted paths. 

| 60 | 10156 | Reported By: Yishai Galatzer |

**Comment by danroth27** [comment]
@NTaylorMullen Don't we support this now with the UrlResolutionTagHelper?

**Comment by NTaylorMullen** [comment]
Yup, this is done.
