### ISSUE TITLE
Reevaluate try/catch in input formatters

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4920]
Right now we have a try/catch around input formatters to allow them to throw and have us treat it as a model state error. I think we're possibly swallowing more errors than we should here, and turning them into 400s instead of 500s.

See https://github.com/aspnet/Home/issues/1605#issuecomment-229158767

The root cause of this issue was a package mismatch, but it became a model state error instead.

**Comment by Eilon** [comment]
We think the best way to fix this would be a breaking change, so putting this in the 2.x milestone.

**Comment by rynowak** [comment]
This failed to happen during 2.0 😢

**Comment by Eilon** [comment]
Then maybe it's reasonable to just close this issue?

**Comment by another-guy** [comment]
@Eilon how is it reasonable if this change has not happen/the issue was not resolved?

**Comment by Eilon** [comment]
@another-guy this issue has not had much attention so it seems as a relatively low priority item, especially considering that it's a breaking change, so the next time we could fix this is in the 3.0 release (we're nearly shut down in the 2.0 release). I talked to @rynowak earlier and we think we might be able to incorporate this into some future "Better Model Binding" implementation.

**Comment by another-guy** [comment]
@Eilon makes sense. Thank you for clarification!

**Comment by rynowak** [comment]
@Eilon - if this is for 3.0 can we close this in favor of tracking it with https://github.com/aspnet/Mvc/issues/6549?

**Comment by kichalla** [comment]
https://github.com/aspnet/Mvc/commit/83c3ac62fb9187c75689a26e9749046825cdd04b
