### ISSUE TITLE
JsonResult will be forced to modify the properties name in RTM version.

### ISSUE THREAD

**Issue by micli** [aspnet/Mvc#4922]
For example:
I have a class Product.

```c#
class Product
{
public string ProductName{get;set;}
public string ProductID{get;set;}
}
```

if an instance of Product converts to a JSON string before RTM, it will be:

```json
{"ProductName" :"AAAA", "ProductID": "1"}
```

RTM version will be:

```json
{"productName" :"AAAA", "productID": "1"}
```

It affects a lots of clients who consume JSON string especially Apache Cordova and Xamarin.
Why you did this change?

**Comment by javiercn** [comment]
See https://github.com/aspnet/Announcements/issues/194 for details of the reasons that drove this change and for how to change it if you want to keep the old behavior.
