### ISSUE TITLE
Multiple forms with Html.AntiForgeryToken() creates multiple headers

### ISSUE THREAD

**Issue by dazbradbury** [aspnet/Mvc#4924]
Every call to:

`@Html.AntiForgeryToken()`

Adds a response header of:

`X-Frame-Options: SAMEORIGIN`

If there is a page with multiple forms, then every time a token is created, a new header is added to the response. If you have a page with hundreds of forms, you add hundreds of headers, and run the risk of causing fallover in multiple, hard to debug, places - think load balancer / nginx. Protections often in place to stop header injection attacks. 

It's also unneccessary, and adds no further protection.

If you change every call to:

`Response.Headers.Remove("X-Frame-Options");
@Html.AntiForgeryToken()`

The issue disappears, but of course, this is not an ideal solution.

The real fix is to ensure only a single header is added, no matter how many times an anti-forgery token is generated in the same response.

**Comment by rynowak** [comment]
@dazbradbury - what release are you using? I believe this was addressed in 1.0.0  https://github.com/aspnet/Antiforgery/issues/60

**Comment by dazbradbury** [comment]
This could well be the wrong repo, I was directed here from codeplex, but since the change to Core perhaps this isn't relevant here, my apologies. It seems the issue is in System.Web.WebPages.

The relevant code (with bug) is here:

https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/System.Web.WebPages/Helpers/AntiXsrf/AntiForgeryWorker.cs#L101

I was linked to this repo from: 

http://aspnetwebstack.codeplex.com/workitem/2057
