### ISSUE TITLE
Sakura.AspNetCore doesnot contains defination of to ToPagedList<>

### ISSUE THREAD

**Issue by ermithun** [aspnet/Mvc#4926]
Error CS1061: **'IQueryable' does not contain a definition for 'ToPagedList' and no extension method 'ToPagedList' accepting a first argument of type 'IQueryable' could be found (are you missing a using directive or an assembly reference?) NETCoreApp,Version=v1.0**

 ```
public async Task<IActionResult> Index(int? page, int? pageSize)
        {
            int no = page ?? 1;
            int size = pageSize ?? 3;
            var data = from i in _context.Products select i;
            IPagedList<Products>lst= data.ToPagedList(size, no);
            return View(lst);
        }`
```

I have install package
"Sakura.AspNetCore.PagedList.Abstractions": "1.0.1",
"Sakura.AspNetCore.Mvc.PagedList": "2.0.2"
in my project

**Comment by Eilon** [comment]
@ermithun this sounds like an issue with https://github.com/sgjsakura/AspNetCore - can you log an issue there?

**Comment by ermithun** [comment]
@Eilon  Thankyou 

Got Solution
https://github.com/sgjsakura/AspNetCore/issues/7#issuecomment-229569150
