### ISSUE TITLE
The type or namespace name 'IModelExpressionProvider' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.ViewFeatures'

### ISSUE THREAD

**Issue by bigteejay** [aspnet/Mvc#4930]
## Issue
After updating VS and .Net Core (installing "vs2015.3" and "DotNetCore.1.0.0-VS2015Tools.Preview2", respectively) I now get the following error being reported by VS when I open a cshtml file that reported no errors previously...

> Error	CS0234	The type or namespace name 'IModelExpressionProvider' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.ViewFeatures' (are you missing an assembly reference?)	

Was there a breaking change or something else I need to update?  This code was working just fine previously.  I can still run the project in VS without issue.

Googling has't returned anything yet (but I just saw the updates posted today, perhaps I'm just the first guinea pig ;-) )

## Environment data
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
Version: 1.0.0-preview2-003121
Commit SHA-1 hash: 1e9d529

Runtime Environment:
OS Name: Windows
OS Version: 6.1.7601
OS Platform: Windows
RID: win7-x64

**Comment by dougbu** [comment]
@bigteejay the [`IModelExpressionProvider`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/IModelExpressionProvider.cs) class hasn't changed since it was introduced in April (f1fe5e26). Could you share your `project.json` file?

**Comment by bigteejay** [comment]
@dougbu - You bet, `project.json` [here](http://pastebin.com/PPpnJ9yv).  It hadn't changed since the updates (but perhaps I have some mismatched versions/syntax/etc.)

On your mention of project.json, I started going through and checking versions and mismatches.  I got a fair way into essentially updating all dependencies with "rcX" or "previewX" in their version to "1.0.0", but that seemed to be diving into a rabbit hole that only caused more problems (and it seemed wise to wait for you to weigh in on what I have currently before getting myself in a much worse spot!)  I started getting warnings about DNX versions (which seemed wrong given the transition away from the "dnx" monikers.)

**Comment by dougbu** [comment]
Don't see anything glaring in the `project.json` but `IModelExpressionProvider` wasn't in RC2. I recommend moving everything to `1.0.0` and `1.0.0-preview2-final`:
- `Microsoft.NETCore.App`: `1.0.0`
- `Newtonsoft.Json`: `9.0.1` or remove because it's brought in transitively
- all at `1.0.0-preview1-final`: `1.0.0-preview2-final`
- all at `1.0.0-rc2-final`: `1.0.0`
- optionally, you can remove most of the `imports` under `tools`. Think `Microsoft.EntityFrameworkCore.Tools` is one of the exceptions where you can't do that but I don't remember the full list.

Please let us know if this resolves your issue.

**Comment by bigteejay** [comment]
@dougbu - Are the type properties still useful/required?

**Comment by bigteejay** [comment]
@dougbu - updated `project.json` [here](http://pastebin.com/dr6U1BA1).

Current errors upon `dotnet restore`...

>     Unable to resolve 'ProjName (>= 1.0.0)' for 'DNX,Version=v4.5.1'.
>     Unable to resolve 'ProjName (>= 1.0.0)' for 'DNXCore,Version=v5.0'.

There is a "restore failed" (following the errors mentioned directly above) and then later a "restore completed".

Current errors appearing in VS "Error List" now...

> Error		1. The project has not been restored or restore failed - run `dotnet restore`	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262	
> 
> Error		2. The project does not list one of 'win7-x64' in the 'runtimes' section.	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262	
> 
> Error		3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262	
> 
> Error		Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win7-x64'. Possible causes:	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262

"The project does not list one of 'win7-x64' in the 'runtimes'" is true, no where in my project.json is my development pc arch referenced (win7-x64), but it never has been and worked previously.  Is this referring to "portable-net451+win8" import under framework?  I was given the impression that that was a current/standard import to use.

This is for an MVC web app that is eventually deployed to Azure.

**Comment by davidfowl** [comment]
How did you create this project? It doesn't look like what file -> new project creates.

**Comment by SpikeMelbost** [comment]
I have same issue.

The error only displays when I have the default.cshtml for one of my view components open in visual studio.

I have a couple of live projects and was hoping to keep one using RC2, so would be good if I can get this issue resolved.

The project I moved to v1.0 also had the same issue which is resolved by moving to v1.0. Note I did need to edit project.json for the following:

    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },

ie, I needed to specify type

**Comment by kspearrin** [comment]
I'm having the same problem now as well with an existing RC2 project after I installed Update 3 tooling and .NET Core 1.0 RTM on my machine.

**Comment by bigteejay** [comment]
@davidfowl - you are correct. This is a project that I started back around beta 7 and I've been trying to upgrade and maintain going forward with revisions.

**Comment by dougbu** [comment]
> Are the type properties still useful/required?

Not sure what you mean. `IModelExpressionProvider` was _added_ in 1.0.0 and is useful.

> `Unable to resolve 'ProjName (>= 1.0.0)' for 'DNX,Version=v4.5.1'.`

That indicates you need to update the lower-level `ProjName` to 1.0.0 as well.

> upgrade and maintain going forward with revisions

Probably fastest to create a new 1.0.0 project in VS and either start w/ the `project.json` it contains or copy your existing code into it. That will also make it easier to get to solid `Program.Main()` and `Startup` class.

**Comment by Eilon** [comment]
@bigteejay if you still have stuff around from beta7, I would recommend creating a *new* project in Visual Studio, and then copy over all your code and other required files and settings.

**Comment by bigteejay** [comment]
@dougbu - 

> Not sure what you mean. IModelExpressionProvider was added in 1.0.0 and is useful.

My apologies, I was referring to the type attributes in the project.json (as below from my original project.json)...

```
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
```

> That indicates you need to update the lower-level ProjName to 1.0.0 as well.

What does that mean?  The first line in my project.json is as follows...

>  LINE 2: `"version": "1.0.0-*",`

@dougbu & @Eilon & @davidfowl - That is good input.  As mentioned earlier, I have been following upgrading/revisions to project files along the way as best as I was able to find/discover migration information, and it **was** working until the latest upgrades mentioned.  So, there **shouldn't** be any beta7 bits in there still... but I'll try from a fresh copy (new project/solution) and see if that works.

**Comment by bigteejay** [comment]
Something else I am noticing, and it seems worth note (perhaps elsewhere, I'm unsure where that would be) is that it is unfortunate that the package restore popup that shows up at the top of the solution window in VS doesn't appear to be fully capturing the outcome of that restore process.

It often will show red text and indicate if an issue occurred.  However, in my case thus far, it gives no indication that the process being discussed currently has failed (simply disappears as if successful.)

**Comment by bigteejay** [comment]
Interestingly, a new default project compiles, and running `dotnet restore` in its folder only tries the restore once and gives (only once) a single `restore completed` message.

I've done my best to get my actual solution's project's [project.json ](http://pastebin.com/A8nsdgHN)to match the [default ](http://pastebin.com/6MEjRHdd)one, and yet I still first get the error, then I get a success, then finally it reports the first error.

**Comment by bigteejay** [comment]
Ah ha!  I just realized, the first issue (of the two messages that were being generated when I did `dotnet restore`), the output mentioned something in `ProjName/bin/release`.  I deleted everything in `bin/` and did another `dotnet restore` and now no errors, just the success message!  Apparently it was finding an old `project.json` in the release build bin output folder and trying to process it (and it was failing.)

**Comment by bigteejay** [comment]
As far as the issues that were appearing in the "Error List", they too are now gone and everything seems to be working smoothly, thanks for your help everyone!

I'll go back, revert to the broken `project.json` and try and determine exactly what was causing this issue as well in the event anyone else ends up here.

**Comment by bigteejay** [comment]
Oddly, reverting to the "broken" `project.json`, and running `dotnet restore` works without issue (no restoration related failures, and no errors reported in the "Error List".)

I can only presume that the issue stemmed from the old build artifacts found in `ProjName\bin`.  Should anyone have similar issues, try deleting/clearing that out.

**Comment by scottdorman** [comment]
The original issue reported still exists.

> Error CS0234 The type or namespace name 'IModelExpressionProvider' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.ViewFeatures' (are you missing an assembly reference?) 

For what it's worth, this is definitely an issue related to an upgrade scenario. I had a project created using what was released just before the 1.0 release and had this error. After making a backup copy of the project, creating a new one using the 1.0 bits and then copying my views, controllers, etc. back over I no longer see this error.

**Comment by kspearrin** [comment]
I have tried clearing all my artifacts and it still doesn't seem to resolve the problem.

**Comment by scottdorman** [comment]
@kspearrin I found that as well. I tried removing the bin and obj folders, as well as the .vs folder and still got the same errors. It wasn't until I created a brand new project and then copied just my code and views back over did the error go away.

**Comment by kspearrin** [comment]
Unfortunately my project is massive and that would be very difficult to do.

**Comment by dougbu** [comment]
@scottdorman, @kspearrin, @bigteejay it's possible our documentation for some upgrade cases is incomplete. We should probably move this over to https://github.com/aspnet/Docs/issues In the meantime,
1. Which version did you each start with?
2. Anything obviously missing or significantly different in your broken `project.json` file and `Program` and `Startup` classes?
3. Just in case the tooling could be improved as well, did any of you hit upgrade issues when using VS Code or another non-VS editor to bring everything to 1.0.0?

**Comment by SpikeMelbost** [comment]
If it helps, this is a summary of the problems / workarounds.

I started with RC1, moved to RC2 then moved some projects to 1.0 with one staying at RC2.

Moving a project from RC2 to 1.0 works for me if I update the Microsoft.NETCore.App entry in project.json to:
"Microsoft.NETCore.App": {
  "version": "1.0.0",
  "type": "platform"
},


However, I also have one project that needs to stay on RC2 for now - so I have the 1.0 tools building an RC2 project. I get the IModelExpressionProvider error only if I have one or more cshtml files open in the editor (VS2015) - definitely if it is for a component.

If I open the project on another PC that is still using the RC2 tools that doesn't show any errors.

So my work-around is to ignore the errors (project still builds & runs OK on both PCs)

**Comment by dougbu** [comment]
FYI the issue here is Visual Studio uses 1.0.0 bits to parse `.cshtml` files but the project's RC2 bits to compile the generated C#. 1.0.0 generated code references the newly-added `IModelExpressionProvider` interface. Visual Studio no longer supports generating RC2-compatible code for tag helpers.

There's actually a few workarounds:

1. Upgrade the project to 1.0.0. Note all projects in an application must be upgraded simultaneously. This is the recommended approach.
2. Ignore this one (IntelliSense-only) compilation error shown when you have a `.cshtml` file open.
3. Temporarily use the drop-down in the Error List window to select only Build errors and warnings. This will of course disable warnings and errors about problems that will affect the project at runtime. 

/fyi @ToddGrun @NTaylorMullen
