### ISSUE TITLE
How to Create a Multipart HTTP Response With ASP.NET Core

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#4933]
I would like to create an action method in my ASP.NET Core controller which returns a Multipart HTTP Response containing several files. I know that using a .zip file is the recommended approach for websites but I am considering using such a request for an API.

The examples I have been able to [find](https://github.com/aspnet/Performance/blob/db01b20b80be94a14fc41b4a09047b61e9de1ddd/testapp/MultipartPOST/MultipartPOST/Controllers/UploadController.cs) in the ASP.NET Core samples are to do with multipart HTTP requests when uploading files. In my case, I want to download files.

[StackOverflow Question](https://stackoverflow.com/questions/38069730/how-to-create-a-multipart-http-response-with-asp-net-core)

**Comment by Eilon** [comment]
@Tratcher ?

**Comment by kichalla** [comment]
I don't think we currently have a way to write out multipart responses( @Tratcher can confirm this ). One way I can think of is to use `System.Net.Http.MultipartContent`.  You would need to subclass it to provide the ASP.NET Core's response stream for the SerializeToStreamAsync method. An output formatter for this content (ex: we have a formatter for the `string` type) which deals with setting content type and triggers serialization should give a not so bad experience.

**Comment by Tratcher** [comment]
No, we don't have a built in formatter for it. That said, the multipart format is much easier to generate than it is to parse. See https://github.com/dotnet/corefx/blob/bfdd0b7694a99838760fbccc8185ee53c7b451cd/src/System.Net.Http/src/System/Net/Http/MultipartContent.cs#L216-L237

**Comment by Tratcher** [comment]
Also note that downloads don't normally use multipart. You can just set the content-disposition header on a normal response.

**Comment by RehanSaeed** [comment]
Thanks @Tratcher @kichalla.

My use case is that I have clients for my API with **very** low internet bandwidth/connectivity in Africa and need to send them multiple zip files. I'm trying to decide between creating a zip of zips or a Multipart response. I realize that using a multipart response is not a good method of downloading files from a browser due to lack of support but I am writing an API and have a client which I also control.

**Comment by kichalla** [comment]
Based on what you mention probably byte ranges support is what you are looking for? That said I don't know much about byte ranges with respect to multiparts.

**Comment by Tratcher** [comment]
This sounds like the old WebApi request batching feature. Is that still in the compat shim?

**Comment by kichalla** [comment]
No it's not part of the shim. Shim is mostly about the controller, it's helper methods and it's action selection process. Batching in webapi was more involved with a delegating handler splitting into individual requests and combining them back.

**Comment by Eilon** [comment]
We are not planning to build anything for this at this time. I think in your case because you control the client and the server you have more flexibility around the data format, so you could relatively easily build up a custom way of "packing" multiple files into one response.

We'll have to see if we get more interest from the broader community around generating these responses.

**Comment by RehanSaeed** [comment]
I've written an `ActionResult` class which simplifies creating multipart responses. There is more to it than I first thought, so it wraps a fair bit of functionality.

# Usage Example

```
[Route("[controller]")]
public class MultipartController : Controller
{
    private readonly IHostingEnvironment hostingEnvironment;

    public MultipartController(IHostingEnvironment hostingEnvironment)
    {
        this.hostingEnvironment = hostingEnvironment;
    }

    [HttpGet("")]
    public IActionResult Get()
    {
        return new MultipartResult(
            new List<MultipartContent>()
            {
                new MultipartContent()
                {
                    ContentType = "image/jpg",
                    Name = "blue.jpg",
                    Stream = this.OpenFile("blue.jpg")
                },
                new MultipartContent()
                {
                    ContentType = "image/jpg",
                    Name = "red.jpg",
                    Stream = this.OpenFile("red.jpg")
                },
                new MultipartContent()
                {
                    ContentType = "image/jpg",
                    Name = "green.jpg",
                    Stream = this.OpenFile("green.jpg")
                }
            });
    }

    private Stream OpenFile(string relativePath)
    {
        return System.IO.File.Open(
            Path.Combine(this.hostingEnvironment.WebRootPath, relativePath),
            FileMode.Open,
            FileAccess.Read);
    }
}
```

# Implementation

```
/// <summary>
/// The multipart/byteranges media type includes two or more parts, each with its own Content-Type and Content-Range fields.
/// The parts are separated using a MIME boundary parameter.
/// </summary>
/// <seealso cref="Microsoft.AspNetCore.Mvc.ActionResult" />
public class MultipartResult: ActionResult
{
    private const int BoundaryMaxLength = 70;
    private const int BoundaryMinLength = 1;

    private const int ContentTypeHeaderLength = 14;
    private const int ContentDispositionHeaderLength = 42;
    private const int ContentRangeHeaderLength = 23;

    private readonly string boundary;
    private readonly IEnumerable<MultipartContent> contents;

    public MultipartResult(IEnumerable<MultipartContent> contents, string boundary = null)
    {
        if (contents == null)
        {
            throw new ArgumentNullException(nameof(contents));
        }

        this.contents = contents;
        if (boundary == null)
        {
            this.boundary = "--===============" + Guid.NewGuid();
        }
        else
        {
            if (boundary.Length < BoundaryMinLength || boundary.Length > BoundaryMaxLength)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(boundary),
                    $"Boundary length out of range. Length:<{boundary.Length}> Minimum:<{BoundaryMinLength}> Maximum:<{BoundaryMaxLength}>.");
            }

            this.boundary = boundary;
        }
    }

    /// <summary>
    /// Gets or sets the boundary value that separates the parts.
    /// </summary>
    public string Boundary { get { return this.boundary; } }

    public IEnumerable<MultipartContent> Contents { get { return this.contents; } }

    public override async Task ExecuteResultAsync(ActionContext context)
    {
        var response = context.HttpContext.Response;

        response.ContentLength = this.GetContentLength();
        response.ContentType = $"multipart/byteranges; boundary={this.Boundary}";

        await this.WriteBoundary(response);

        var position = 0L;
        foreach (var content in this.Contents)
        {
            var length = await this.WriteContent(response, content, position);
            position += length + 1;
            await this.WriteBoundary(response);
        }

        await response.Body.FlushAsync();
    }

    private static long CountDigits(long n)
    {
        if (n == 0)
        {
            return 1;
        }

        return (long)Math.Floor(Math.Log10(n) + 1);
    }

    private long GetContentLength()
    {
        var contentLength = 0L;

        // Boundary
        contentLength += this.Boundary.Length;
        contentLength += Environment.NewLine.Length;

        var fileCount = 0;
        var position = 0L;
        foreach (var file in this.Contents)
        {
            var length = file.Stream.Length;

            // Content Type
            contentLength += ContentTypeHeaderLength;
            contentLength += file.ContentType.Length;
            contentLength += Environment.NewLine.Length;

            if (file.Name != null)
            {
                // Content Disposition
                contentLength += ContentDispositionHeaderLength;
                contentLength += file.Name.Length;
                contentLength += Environment.NewLine.Length;
            }

            // Content Range
            contentLength += ContentRangeHeaderLength;
            contentLength += CountDigits(position);
            contentLength += CountDigits(position + length);

            // Content
            contentLength += length;

            // Boundary
            contentLength += this.Boundary.Length;
            contentLength += Environment.NewLine.Length;

            ++fileCount;
            position += length + 1;
        }

        // Content Range - The content length is added to the Content Range header.
        // We also re-adjust if adding the content lengths causes the content length to get longer.
        var contentLengthDigitsBefore = CountDigits(contentLength);
        contentLength += (fileCount * contentLengthDigitsBefore);
        var contentLengthDigitsAfter = CountDigits(contentLength);
        if (contentLengthDigitsAfter > contentLengthDigitsBefore)
        {
            contentLength += (fileCount * (contentLengthDigitsAfter - contentLengthDigitsBefore));
        }

        return contentLength;
    }

    private async Task WriteBoundary(HttpResponse response)
    {
        await response.WriteAsync(this.Boundary);
        await response.WriteAsync(Environment.NewLine);
    }

    private async Task<long> WriteContent(HttpResponse response, MultipartContent content, long position)
    {
        var length = content.Stream.Length;

        await response.WriteAsync("Content-type: ");
        await response.WriteAsync(content.ContentType);
        await response.WriteAsync(Environment.NewLine);

        if (content.Name != null)
        {
            await response.WriteAsync("Content-disposition: attachment; filename=");
            await response.WriteAsync(content.Name);
            await response.WriteAsync(Environment.NewLine);
        }

        await response.WriteAsync("Content-range: bytes ");
        await response.WriteAsync(position.ToString());
        await response.WriteAsync("-");
        await response.WriteAsync((position + length).ToString());
        await response.WriteAsync("/");
        await response.WriteAsync(response.ContentLength.Value.ToString());
        await response.WriteAsync(Environment.NewLine);

        await response.WriteAsync(Environment.NewLine);
        await content.Stream.CopyToAsync(response.Body);
        await response.WriteAsync(Environment.NewLine);

        content.Stream.Close();
        return length;
    }
}
```

**Comment by Tratcher** [comment]
Looks promising.
- You can't use Environment.NewLine, it will give you the wrong output on unix. The multipart format always requires `\r\n`.
- Read about `filename*` for non-ascii file names.
- I don't think that's the correct usage of content-range. It should start with the offset in the file from which you are starting, not the offset in the generated response stream.

**Comment by RehanSaeed** [comment]
Thanks @Tratcher

- Yep, I forgot that web stuff is all `\r\n`. Updated the code above to switch from `Environment.NewLine` to a `"\r\n"` constant.
- I discovered the `ContentDispositionHeaderValue` class in ASP.NET Core which is a delight to use, updated the code to use it.
- I'm a bit confused by the `Content-range` HTTP header and what the start and end values should really mean. I've struggled to find a decent example, also [Google](https://stackoverflow.com/questions/31406022/how-is-an-http-multipart-content-length-header-value-calculated) does not include it altogether. Any pointers on the subject?

**Comment by Tratcher** [comment]
Content-range is only needed when you're sending part of a resource. e.g. you're only sending back half of the file, or you're sending the file in multiple segments. The values should refer to positions within the original file.

**Comment by RehanSaeed** [comment]
It seems I was massively misled by the StackOverflow [answer](https://stackoverflow.com/questions/38069730/how-to-create-a-multipart-http-response-with-asp-net-core) which was so detailed, I thought it had to be right. I've updated the implementation above by taking @kichalla's idea and using `System.Net.Http.MultipartContent` which simplifies things a lot.

All working now, thanks for the pointers.

**Comment by 4996wsu** [comment]
Any chance someone has an example of how to make a request to this? I've tried a number of things but always get errors about the connection closing unexpectedly. If I read the content line by line, it at least gets all the data, but an exception gets thrown at the end. 

```
HttpWebRequest http = (HttpWebRequest)WebRequest.Create("http://localhost:1362/api/values/getstream");
WebResponse response = http.GetResponse();
	
var stream = response.GetResponseStream();
StreamReader sr = new StreamReader(stream);
sr.ReadToEnd();
```

**Comment by Tratcher** [comment]
@4996wsu what have you got so far?
