### ISSUE TITLE
Absolute Paths for Views not working

### ISSUE THREAD

**Issue by markusvt** [aspnet/Mvc#4936]
I had a running RC1 project in which I use the following code to load a view
```
 public IViewComponentResult Invoke(DataTablesTagHelper model)
        {
            return View("~/ViewComponents/DataTables/View", model);
        }
```
I updated the project to Core 1 now an use net451 as Framework 
```
"frameworks": {
    "net451": {}
```

After my update the view isnt found anymore any i get the following error:
```
The view 'Components/DataTablesVC/~/ViewComponents/DataTables/View' was not found. The following locations were searched:
 ~/ViewComponents/DataTables/View
 /Areas/Core/Views/Benutzer/Components/DataTablesVC/~/ViewComponents/DataTables/View.cshtml
 /Areas/Core/Views/Shared/Components/DataTablesVC/~/ViewComponents/DataTables/View.cshtml
 /Views/Shared/Components/DataTablesVC/~/ViewComponents/DataTables/View.cshtml
```
Have there been any changes to absolute paths of views?

**Comment by pranavkm** [comment]
@markusvt see https://github.com/aspnet/Mvc/issues/3307#issuecomment-150004428. You'd have to change your view path to include the extension when using absolute paths i.e. `~/ViewComponents/DataTables/View.cshtml`

**Comment by markusvt** [comment]
Thank you very much! That saved my day :)

**Comment by markusvt** [comment]
Another Problem just arrised:

i got the following class to render a view programmatically (I call that via ajax to change parts of a view based on certain selections of a user)

```
public class RazorViewToStringRenderer
    {
        private IRazorViewEngine _viewEngine;
        private ITempDataProvider _tempDataProvider;
        private IServiceProvider _serviceProvider;

        public RazorViewToStringRenderer(
            IRazorViewEngine viewEngine,
            ITempDataProvider tempDataProvider,
            IServiceProvider serviceProvider)
        {
            _viewEngine = viewEngine;
            _tempDataProvider = tempDataProvider;
            _serviceProvider = serviceProvider;
        }

        public string RenderViewToString<TModel>(string name, TModel model, String prefix = "")
        {
            var actionContext = GetActionContext();
            var viewEngineResult = _viewEngine.FindView(actionContext, name, false);

            if (!viewEngineResult.Success)
            {
                throw new InvalidOperationException(string.Format("Couldn't find view '{0}'", name));
            }

            var view = viewEngineResult.View;

            using (var output = new StringWriter())
            {
                var viewDataDictionary = new ViewDataDictionary<TModel>(
                        metadataProvider: new EmptyModelMetadataProvider(),
                        modelState: new ModelStateDictionary())
                {
                    Model = model,
                };
                viewDataDictionary.TemplateInfo.HtmlFieldPrefix = prefix;

                var viewContext = new ViewContext(
                    actionContext,
                    view,
                    viewDataDictionary,
                    new TempDataDictionary(
                        actionContext.HttpContext,
                        _tempDataProvider),
                    output,
                    new HtmlHelperOptions());

                view.RenderAsync(viewContext).GetAwaiter().GetResult();

                return output.ToString();
            }
        }

        private ActionContext GetActionContext()
        {
            var httpContext = new DefaultHttpContext();
            httpContext.RequestServices = _serviceProvider;
            return new ActionContext(httpContext, new RouteData(), new ActionDescriptor());
        }
    }
``` 

Before I updated to Core 1.0  it worked. Now it says 
```
Couldn't find view '~/Areas/Company/Views/Adress/_MainAdressFormular.cshtml'
``` 
I already tried to remove the ~ or the .cshtml  and made sure that view actually exists in that location.

**Comment by pranavkm** [comment]
If you print the `SearchedLocations` from `viewEngineResult` it might say what locations its trying to look up.

**Comment by dougbu** [comment]
Alternatively, your `project.json` might be missing the `Areas` folder. Look for
``` json
  "publishOptions": {
    "include": [
      "Views",
      "..."
    ]
  },
```

**Comment by markusvt** [comment]
I did print the ```SearchedLocations``` and it was empty. I did the following:
```

**Comment by pranavkm** [comment]
If you haven't modified `RazorViewEngineOptions.FileProviders`, the view engine is going to look for the view at `Path.Combine(IHostingEnvironment.ContentRoot, "Areas/Company/Views/Adress/_MainAdressFormular.cshtml")`. Could you check if the view exists at this location?

**Comment by markusvt** [comment]
No I didn't modify it. I just double-checked the location of that view and it is where it is supposed to be
![image](https://cloud.githubusercontent.com/assets/2082863/16552333/7d4fa224-41c0-11e6-8105-d336c0c379bb.png)

Can I somehow configure the `SearchedLocations` of the view engine as a workaround? As at the moment it seems that it doesnt search anything (output of those locations was empty)

By the way: if i load the view normal in another Razor View, it works:
```
  @Html.Partial("~/Areas/Company/Views/Adress/_MainAdressFormular.cshtml", Model)
```

So it seems I miss something with the viewEngine in my `RazorViewToStringRenderer`

**Comment by markusvt** [comment]
Okay after some trying out with a custom view engine and looking in existing code and tests i found the solution to my problem:
In my `RenderViewToString` I need to call 
```
_viewEngine.GetView(executingFilePath: viewPath, viewPath: viewPath, isMainPage: false);
```
where `viewPath` contains the absolute path (with ~/...) to the view. So the "FindView" method iis not working for that. Also if i user anything but the absolute path for the `viewPath` parameter it is not working.
Actually I dont know why it works, as i saw in the `RazerViewEngine` that there is also a test, that the given path must not be absolute / app-relative.

**Comment by dougbu** [comment]
@markusvt have a look at the doc comments for `IViewEngine`. That makes the distinction between `GetView()` and `FindView()` pretty clear. In short, `GetView()` starts with an absolute or relative path while `FindView()` starts with a view name and uses view locations, et cetera.
- https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewEngines/IViewEngine.cs
- https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Mvc/ViewEngines/IViewEngine/index.html#Microsoft.AspNetCore.Mvc.ViewEngines.IViewEngine

**Comment by nukuuk** [comment]
@dougbu thank you, using getview fixed it for me!

**Comment by sven5** [comment]
@dougbu 
Would you rather recommend to use GetView() when dealing with Areas?
That would mean that FindView() doesn't work for Areas.


Thanks
Sven

**Comment by dougbu** [comment]
@sven5 no, I would recommend using both `GetView(...)` and `FindView(...)` in all cases. The methods do different things but both are relevant (and work) when dealing with areas. `GetView(...)` handles paths relative to the current location while `FindView(...)` searches in the view locations.

The following fallback pattern is what we do within MVC:
``` c#
var viewEngineResult = _viewEngine.GetView(ViewContext.ExecutingFilePath, partialName, isMainPage: false);
var getViewLocations = viewEngineResult.SearchedLocations;
if (!viewEngineResult.Success)
{
    viewEngineResult = _viewEngine.FindView(ViewContext, partialName, isMainPage: false);
}
```
