### ISSUE TITLE
Move IRazorViewEngineFileProviderAccessor and ExpressionRewriter to the public namespace

### ISSUE THREAD

**Issue by DavidEmanuelsen** [aspnet/Mvc#4938]
An application we're building has ended up needing to implement a modified version of `DefaultRoslynCompilationService` to avoid caching of the list of compilation references. In the modified version we still depend (as far as I can see) on `IRazorViewEngineFileProviderAccessor` and `ExpressionRewriter` which are both in the `.Internal`-namespace.

Is there any chance this can be moved to the public namespace to minimize risks of breaking changes in the future?

See https://github.com/aspnet/Mvc/issues/4497 for history

**Comment by Eilon** [comment]
@NTaylorMullen @pranavkm @rynowak thoughts on this? Would it make sense to move these types to a public namespace?

**Comment by davidfowl** [comment]
No, if you ended up rewriting the default service then we have a gap somewhere in our extensibility.

**Comment by rynowak** [comment]
@davidfowl - we did identify a gap here... remember when we designed compilation factory and reference manager?

We should make an abstraction for https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/RazorReferenceManager.cs and make it public, that's the part you're asking for right @DavidEmanuelsen ?

**Comment by Eilon** [comment]
@rynowak I'm parking this on your plate. If you think we can get this in, let's do it, but if not, I think we should close it.

**Comment by rynowak** [comment]
c3f76137259bea68d4add1aa0d2f79b77a86cfa6
