### ISSUE TITLE
Why the "Controller" suffix requirement?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [aspnet/Mvc#4940]
Why are we required to name our controllers "LoremIpsum**Controller**" when it's technically sufficient to just look for concrete classes extending Controller, to find the right classes to register?

Would a lot of stuff break removing this requirement? (I guess not.)

**Comment by brockallen** [comment]
Not all controller classes extend the `Controller` base class.

**Comment by pranavkm** [comment]
Types deriving from the `Controller` don't require the suffix. Here's the list of conventions used during controller discovery: https://github.com/aspnet/Announcements/issues/165

**Comment by bjorn-ali-goransson** [comment]
(Hello @brockallen)

Okay, nice, I thought that was still the case from MVC 5.

**Comment by brockallen** [comment]
Yep, interesting news to me as well!
