### ISSUE TITLE
Areas not getting published

### ISSUE THREAD

**Issue by freshe** [aspnet/Mvc#4942]
Areas/\*\*/Views in template does not seem to work.
Areas/\*\*/\*.cshtml still works fine.

**Comment by pranavkm** [comment]
Could you file this bug in https://github.com/dotnet/cli?

**Comment by freshe** [comment]
Sorry, found and open issue in CLI https://github.com/dotnet/cli/issues/3286 
and MVC milestone 1.1 as well #4645

**Comment by pranavkm** [comment]
Great. Feel free to close this issue if it's being addressed elsewhere.
