### ISSUE TITLE
Feature request: Comments with name of view file, RazorView customization

### ISSUE THREAD

**Issue by ShadowDancer** [aspnet/Mvc#4944]
Use case:
Comments with currently rendered viewName in development environment. For example:

```

<!-- View: "~/Views/MyController/MyAction.cshtml" -->
<div> some stuff </div>
<!-- End of view: "~/Views/MyController/MyAction.cshtml" -->
```

In case you want to know - "Hey why this div is here" without checking whole view hierarchy.

In rc1 there used to be IRazorViewFactory, where I could create my view on top of razorView, that would write comment to body before and after base.RenderAsync. There is no IRazorViewFactory anymore, and views are new'd in RazorViewEngine.CreateViewEngineResult.

**Comment by Eilon** [comment]
One possible issue with doing this is that it assumes that the contents of the view are necessarily HTML, which isn't always the case. E.g. a partial view might render a JavaScript snippet or other type of content that is then embedded in a larger HTML document.

Certainly an interesting idea, but no plans to implement it at this time.

**Comment by ShadowDancer** [comment]
Still it would be great if there was extensibility point, so I can do it myself without replacing RazorViewEngine :)

**Comment by Eilon** [comment]
@ShadowDancer understood. If you can spot where we could potentially improve the extensibility we can take a look. At this time this isn't a high priority, but if you can help point out to us what the improvement could be we'll take a look.

**Comment by ShadowDancer** [comment]
@Eilon Sorry, I missed your comment. I hope it is not too late already :)

I think that bringing back RazorViewFactory would be good idea, so RazorViewEngine would request view from it instead of newing it up [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngine.cs#L472). RazorView,RenderAsync is already [virtual](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorView.cs#L93), so it would work.

There is one issue though - both layout and page contents are rendered in RazorView.RenderAsync. It would be great if I could wrap just page (contents of @RenderBody) in comments, because some tools don't like comments before `<html>` tag (and people like to know where page starts too). Simplest solution would be to make RazorView.[RenderPageAsync](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorView.cs#L109) and RazorView.[RenderLayoutAsync](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorView.cs#L202) protected, so my derived class would wrap them in comment instead of wrapping whole RenderAsync.

I may prepare code samples if You wish.

**Comment by Eilon** [comment]
@rynowak @pranavkm @DamianEdwards thoughts on this?

**Comment by pranavkm** [comment]
I vaguely recall speaking to @DamianEdwards about separating the view with the thing that executes it (they're intermingled today). Perhaps if we separate it. and we have the luxury of doing this since none of the implementation methods of the view are public today, it might be easier to do changes like this rather than subclass the type. Is that something we want to consider?

**Comment by Eilon** [comment]
@pranavkm sure we can consider. Perhaps set up a mtg for later this week? Include me, @rynowak @DamianEdwards @danroth27 @davidfowl ?

**Comment by rynowak** [comment]
I don't think this is any easier today, then it was in the past, but this isn't won't be straightforward to do unless we give the whole view engine a coat of paint. 

Is this something we want to do? If that's the case, can we create a meta-issue for that and track it there. Otherwise I propose closing as wont fix. /cc @Eilon

**Comment by danroth27** [comment]
I don't think we've heard enough customer demand to make this worthwhile. I would close.

**Comment by Eilon** [comment]
I agree w/ closing, the use case seems very limited, and the value doesn't seem to be there compared to the potential cost.
