### ISSUE TITLE
Manually creating a ViewModel is different that the way it's created by the framework.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#4951]
I won't pretend I understand how this works, just wanted to tell you about something I noticed that may be a bug but probably is by design. And it would be great to have it documented (couldn't find).

```
public class ImageCreateViewModel: IOrderableFormFile
{
    [Required]
    public IFormFile FormFile { get; set; }

    public int Order { get; set; } // int type, should be 0 by default.
}

public IActionResult Create()
{
    // ViewData.Model = new ImageCreateViewModel(); // <-- interesting line
    return View();
}
```

When we render a view without explicit creating a view model instance, the Order value is "empty" (note the type is `int`)

```
<input class="form-control" type="number" 
data-val="true" data-val-required="The Order field is required." 
id="Order" name="Order" 
value="" />
```

if I explicit create the ViewModel (uncommenting the commented line):
```
<input class="form-control" 
type="number" data-val="true" data-val-required="The Order field is required." 
id="Order" name="Order" 
value="0" />
```

Note value now has the *correct* value 0.

I expected both scenarios should be similar.

**Comment by ivaylokenov** [comment]
The framework does not create new object like you do - the model remains null and that is why values are empty. When you create an object, you initialize it with all default values. The default value of int is 0 - you receive 0 in the input.

**Comment by Eilon** [comment]
Yeah as far as I know it's exactly what @ivaylokenov says.

@dougbu @rynowak can you confirm?

**Comment by javiercn** [comment]
Yep, I would say this is by design

**Comment by Bartmax** [comment]
Thank you.
