### ISSUE TITLE
The provided antiforgery token was meant for a different claims-based user

### ISSUE THREAD

**Issue by mcgear** [aspnet/Mvc#4953]
Hi,

So i am trying to work with AspNetCore Antiforgery.  First, i'll setup where i am at:

1)  Added to Startup the following (configured 2nd, after Application Inisghts Telemetry):

``` c#
        protected virtual void configureAntiforgeryServices(IServiceCollection services)
        {
            services.AddAntiforgery(o =>
            {
                o.HeaderName = "X-XSRF-TOKEN";
            });
        }
```

2)  Added to Startup the following (configured 1st, before anything else)

``` c#
        protected virtual void configureAntiforgery(IApplicationBuilder app, IAntiforgery antiforgery)
        {
            app.Use(next => context =>
            {
                var tokens = antiforgery.GetAndStoreTokens(context);

                context.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken, new CookieOptions()
                {
                    HttpOnly = false
                });

                return next(context);
            });
        }
```

3)  I have a controller method that uses the ValidateAntiForgeryTokenAttribute

If i have a user that is not logged in, i am able to take the value from the XSRF-TOKEN cookie and submit it to the API and everything works.  I am using this on a signin API, so once successful, an ASPNETCORE cookie is created for the user.

Once signed in, if i refresh and get a new Antiforgery token, once i submit it to the API i get an error:
The provided antiforgery token was meant for a different claims-based user.

Is there something additional i need to do when writing the Cookie in the page response so that it is for the current user?

**Comment by mcgear** [comment]
I wanted to add, that if i just delete the '.AspNetCore.Cookies' cookie prior to submitting to the API, then the generated antiforgery token works in the API.  So it seems to be something about having the .AspNetCore.Cookies cookie present?...

**Comment by mcgear** [comment]
Also probably important to note that my project.json targets net 4.5.1....  Fifty280.Presentation brings in antiforgery reference:

`
{
	"dependencies": {
		"Autofac.Extensions.DependencyInjection": "4.0.0-rc2-240",
		"Fifty280.Presentation": "1.0.0-*",
		"Microsoft.AspNetCore.Mvc.Core": "1.0.0-rc2-final",
		"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
		"Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final"
	},

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {
    "net451": {}
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

**Comment by timdows** [comment]
I guess you are using IdentityServer and also want to use the AntiForgery

I was able to work around this by having app.UseIdentity() before the XSRF part

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IAntiforgery antiforgery)
{
    loggerFactory.AddConsole(Configuration.GetSection("Logging"));
    loggerFactory.AddDebug();

	app.UseIdentity();

	app.Use(next => context =>
    {
        var tokens = antiforgery.GetAndStoreTokens(context);
        context.Response.Cookies.Append(
            "XSRF-TOKEN", 
            tokens.RequestToken,
            new CookieOptions() {HttpOnly = false}
        );

        return next(context);
    });
//.....
}
```

**Comment by stephenyao** [comment]
This solution seems to work, but only from the second requests after the user has logged i n.

So if a API has just processed a login request, and returns a anti forgery token, then the API receives it's next request using that anti forgery token, the API would then throw the same exeception: `The provided antiforgery token was meant for a different claims-based user.`

I am guessing this is because once the user logs in, whatever antifogery token was set for that request is now invalid, because the API now expects the next request to have an antifogery token that contain's the user's username, while in the previous request the antiforgery token was generated before the user logged in (as useMVC is the last step in the middleware pipeline).

If anyone has had this issue and has resolved it, please let me know!

**Comment by fhinchey** [comment]
I'm trying this approach but don't see a "RequestToken". Only formtoken and cookietoken. I tried using those instead with no luck. Ideas?

**Comment by Eilon** [comment]
Hi all, we have a full sample of using AJAX + antiforgery w/ MVC + Identity for login. You can see the sample here: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.AjaxAntiforgeryAuth.Web

**Comment by webbkvalite** [comment]
@stephenyao: I had the same issue as you and fixed it by adding a call to
`antiforgery.GetAndStoreTokens(context.HttpContext);`
in the callback from the IdentityAuthentication Middleware.
Simplified like this:
`app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions("MyAuthProvider")
            {
                 ...
                 Events = new OpenIdConnectEvents
                {
                     OnTicketReceived = context =>
                    {
                    ...
                    antiforgery.GetAndStoreTokens(context.HttpContext);
                    }
                }
           }`

**Comment by Systemdir** [comment]
@Eilon The url to the sample is outdated.

I solved our issue with AspNet Core Identity & AntiforgeryToken by setting the HttpContext.User using the SignInManager before calling the GetAndStoreTokens method.

    // send anti forgery token
    HttpContext.User = await _signInManager.CreateUserPrincipalAsync(user);
    AntiforgeryTokenSet tokens = _antiforgery.GetAndStoreTokens(HttpContext);
    HttpContext.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken,
                new CookieOptions() { HttpOnly = false });

**Comment by Eilon** [comment]
Ah, we moved the samples a while ago, I updated the URL to: https://github.com/aspnet/Entropy/tree/dev/samples/Antiforgery.MvcWithAuthAndAjax
