### ISSUE TITLE
label-for displays 2 red asterix when view model property is set to required

### ISSUE THREAD

**Issue by chassq** [aspnet/Mvc#4955]
We are getting 2 red asterix displayed when we have a property using the RequiredAttribute using the label for tag helper in a tag helper form. I am going to look into extending or overriding the taghelper but just wanted to let someone know and see if there is any guidance on how to fix in the interim.

Thanks!

**Comment by chassq** [comment]
Sorry, created the original issue too soon.  Let me be more specific about what is happening. We upgraded a RC2 web application (MVC) to RTM recently. When running in dev we get **one** asterix appearing on our labels which using the label tag helper and a view model with the requisite Required attribute on the property used by asp-for attribute on the tag helper. This is expected behavior. 

However, when we deploy to an Azure WebApp we are seeing 2 red asterix instead of 1 when the site renders our labels. We are running on net461 in dev. The webapp on azure is pointed to net46 (there is no 461 option that we see). We also deleted our original webapp entirely from Azure and created a new one to see if something had persisted on the Azure side and we made sure our publish settings were set to remove additional files during publish. But we still get the same problem.

Not sure if this issue goes here or over to the Azure group. Anyone else seen this?

Thanks!

**Comment by dougbu** [comment]
MVC forms do not display an asterisk by default. Does your project include code adding that display for validation errors?

If not, sounds like one or more JavaScript files is not being downloaded, likely `jquery.validate.unobtrusive.js` / `jquery.validate.unobtrusive.min.js`. Check using F12 in your browser.

**Comment by chassq** [comment]
Yes, we have included jquery.validate.unobtrusive.js  /  jquery.validate.unobtrusive.min.js . You can see it here: https://hxs-dev-hub-webapp.azurewebsites.net/agency/appointment/getstarted . Site is currently in Dev/Test.

**Comment by dougbu** [comment]
@chassq what adds the `<span style="color:red"> *</span>` elements to the `<label>`? Nothing in MVC does this.

**Comment by chassq** [comment]
Its my understanding that placing the [Required] attribute data annotation on the ViewModel property will display the red asterix on a label where label asp-for is used. Am I wrong?

**Comment by dougbu** [comment]
> will display the red asterix on a label where label `asp-for` is used

No, MVC doesn't do this. Other code in your application must be changing the generated HTML or updating the DOM in your browser.

**Comment by chassq** [comment]
Ok, got it thanks.. I will keep looking...
