### ISSUE TITLE
Default values for attribute routing are ignored, after migrating from ASP.NET Core RC2 to RTM

### ISSUE THREAD

**Issue by lalibi** [aspnet/Mvc#4956]
Code like the following, used to work with RC2, and the default value (`=1`) was honored.

	[Route("[controller]/[action]")]
	public class FooController : Controller
    {
        [HttpGet("{id:int=1}")]
        public IActionResult Bar(int id)
        {
            ViewData["Message"] = $"Id: {id}";
            return View();
        }
    }

With RC2, URLs `/Foo/Bar/1` and `/Foo/Bar` gave the same results. After upgrading To RTM, `/Foo/Bar` gives a 404 error.

**Comment by javiercn** [comment]
Its a known bug in atribute routing. The workaround is to use two routes and provide the default value in the method parameter. See https://github.com/aspnet/routing/issues/324

**Comment by lalibi** [comment]
Thanks for letting me know.

**Comment by ststeiger** [comment]
Instead of fixing the bug...

**Comment by javiercn** [comment]
This bug was fixed as of https://github.com/aspnet/Routing/commit/ffa0ee5222783f8f267fc86fba7b63668cc639ea
