### ISSUE TITLE
mvc packages netstandard 1.5 and 1.6

### ISSUE THREAD

**Issue by dazinator** [aspnet/Mvc#4958]
I am upgrading my application from RC2 to RTM

I was previously using the RC2 version of the following package: [Microsoft.AspNetCore.Mvc.Razor](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor/)

The RC2 version was compatible with netstandard1.5, and in the RTM version this has been changed to netstandard 1.6.

So I changed my project.json to target netstandard1.6 but I still cannot get it to pull in the NuGet package - it looks like its still under the illusion that my project is targeting 1.5 - see screenshot:

![image](https://cloud.githubusercontent.com/assets/3176632/16567520/7ea1be30-4217-11e6-89ea-44ea8cad629d.png)

This seems odd :-) I have run `dotnet restore` multiple times and this error isnt going away. Have also saved, closed and re-opened the project.json file.

Also why the breaking change from netstandard 1.5 to 1.6?

**Comment by ivaylokenov** [comment]
Have you tried deleting the project.json.lock files in solution? That fixed the packages problems for me.

**Comment by dazinator** [comment]
- Sorry hadn't tried that, however I did a rebuild and then that seemed to fix it ;)

**Comment by Eilon** [comment]
Sounds like everything is fine now, so closing...
