### ISSUE TITLE
RouteValueAttribute not working as expected

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/Mvc#4959]
Steps to reproduce:

1.Create new Web Project and leave only this controller

```c#
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }
        
        public IActionResult Contact(int id)
        {
            return this.View();
        }
    }
```

2.Run the application and navigate to '/Home/Contact/1' - action should be executed correctly.
3.Add the following route value attribute:

```c#
    public class MyRouteConstraintAttribute : RouteValueAttribute
    {
        public MyRouteConstraintAttribute(string routeKey, string routeValue)
            : base(routeKey, routeValue)
        {
        }
    }
```

4.Add this second controller:

```c#
    [MyRouteConstraint("controller", "CustomController")]
    public class RouteConstraintController : Controller
    {
        [MyRouteConstraint("action", "CustomAction")]
        [MyRouteConstraint("id", "5")]
        [MyRouteConstraint("key", "value")]
        public IActionResult Action(int id, int anotherId)
        {
            return null;
        }
    }
```

5.Run the app and navigate to '/Home/Contact/1' - this time the response is 404 and it should not be as the HomeController never changed.

It seems that the RouteValueAttribute applies the restrictions globally somehow and I believe this is a bug because the documentation of that attribute states otherwise.

**Comment by rynowak** [comment]
This is definitely intended as of 1.0.0.

What are you trying to accomplish? There's probably a better way to do it.

**Comment by ivaylokenov** [comment]
@rynowak I do not try to acomplish anything, I am just toying around quite a lot because of my libraries I am writing for ASP.NET Core. The reason I opened this issue is because on the RouteValueAttribute the documentation states:

```
When placed on an action, the route data of a request must match the expectations of the route
constraint in order for the action to be selected.
```

I understand from this sentence that only the action I put the attribute on will require 'id' route value that is equals to 5 as per the example above. I wonder why the other controller requires the same parameter while it is not decorated with the attribute. Is the documentation wrong?

**Comment by rynowak** [comment]
We should either improve the docs here or refer to this section -> https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Routing/IRouteValueProvider.cs#L22 which is quite detailed.

**Comment by ivaylokenov** [comment]
@rynowak Got it. That interface describe it well enough. There was parameter - require key or something. Why was that removed?

**Comment by rynowak** [comment]
It was removed because it adds a lot of complexity to action selection, and it conceptually meant the same thing as using an `IActionConstraint` to check the route value. Sample here: https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.ActionConstraintSample.Web/CountrySpecificAttribute.cs

**Comment by ivaylokenov** [comment]
@rynowak Thank you for the information. You can close this issue now or if you prefer to remind you of the documentation fix of RouteValueAttribute, you can leave it open. I do not have anything else to add or ask.

**Comment by Eilon** [comment]
@rynowak assigning to you to update docs as appropriate.
