### ISSUE TITLE
JSON Serializer Contract Resolver defaulting to CamelCaseContractResolver after RC1 to 1.0 port

### ISSUE THREAD

**Issue by iamthemovie** [aspnet/Mvc#4961]
We ported our RC1 ASP.NET Core project over to RTM last week and noticed the JSON serializer settings no longer default to the DefaultContractResolver, instead it defaults to the CamelCasePropertyNamesContractResolver leading us to have to use the following:

```cs
services
    .AddMvc()
    .AddJsonOptions(options =>
    {
        // JSON serialization not defaulting to default?
        options.SerializerSettings.ContractResolver = new DefaultContractResolver();
    });
```
Our app sends serialized object output in Upper Camel case for property names.

What is the position on the default output serialization format for ASP.NET Core anyway?

While the de facto standard in most JSON API's is generally lower camel case, would it not be worth having CamelCase named "Default" and "UpperCamelCase" as the one I'm after in general if the default has changed?

**Comment by ctyar** [comment]
you might want to take a look at these:
https://github.com/aspnet/Mvc/issues/4283
https://github.com/aspnet/Mvc/issues/4842

**Comment by iamthemovie** [comment]
Thanks!

**Comment by iamthemovie** [comment]
For anyone coming to this in the future, these classes are part of JSON.NET and not ASP.NET. 

Will close.
