### ISSUE TITLE
Add IMvcCoreBuilder.AddJsonOptions extension method

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#4967]
We don't have this defined for `IMvcCoreBuilder` only `IMvcBuilder`. This would be great to have even though you can setup options as part of `AddJsonFormatters`. Most of our examples refer to `AddJsonOptions`.

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/DependencyInjection/MvcJsonMvcBuilderExtensions.cs#L19

**Comment by javiercn** [comment]
My two cents https://github.com/aspnet/Mvc/issues/4965#issuecomment-230587224. This would be a good up for grabs

**Comment by Eilon** [comment]
Agreed.

**Comment by iscifoni** [comment]
I can do it ?

**Comment by Eilon** [comment]
@iscifoni I don't know, *can* you? 😄 If you want to give it a try, please let us know if you're working on it and we'll expect a PR from you!
