### ISSUE TITLE
List<Dictionary<string,object>> not automatically camel cased

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Mvc#4969]
```
public class Person
{
    public int Id { get; set; }

    public string FullName { get; set; }
}
```
serialized to (automatically camel cased
```
{"id":9000,"fullName":"John Smith"}
```

But

```
Dictionary<string,object> person=new Dictionary<string,object>()
{
{"Id",9000},
{"FullName","John Smith"}
};
```
NOT automatically camel cased
```
{"Id":9000,"FullName":"John Smith"}
```

fyi I don't like this change https://github.com/aspnet/Mvc/issues/4842

**Comment by javiercn** [comment]
The behavior is intended and configurable on JSON.NET. See https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/CamelCaseNamingStrategy.cs

**Comment by dougbu** [comment]
@andrew-vandenbrink if you prefer to treat your dictionary keys as code,
``` c#
services
    .AddMvc()
    .AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver
    {
        NamingStrategy = new CamelCaseNamingStrategy
        {
            ProcessDictionaryKeys = true,
        },
    });
```

Or apply the following to a `Dictionary` subclass with non-data keys:
``` c#
[JsonDictionary(
    NamingStrategyType = typeof(CamelCaseNamingStrategy),
    NamingStrategyParameters = new object[] { true, false })]
```

**Comment by andrew-vandenbrink** [comment]
Thanks, too bad its not the default behavior... should be more consistent...
