### ISSUE TITLE
Question: Should non-`ValueType` action parameters _always_ be non-`null`?

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4971]
`object`s are created for unbound POCO parameters only when using `ComplexTypeModelBinder`. This leads to the following inconsistent behaviours:
- `[FromBody]` parameters are left `null` when the incoming request has an empty body. See #4750 for example.
- POCO types with a `string` converter (i.e. `SimpleTypeModelBinder` handles them) are left `null` when the form contains no corresponding data.
- `IFormFile` parameters are left `null` when no matching files are submitted.

Empty collections are created in most unbound and `IsTopLevelObject` cases due to activation code in `CollectionModelBinder`, `HeaderModelBinder` et cetera. But `byte[]` arrays are often left `null` e.g. when the corresponding `<input/>` was left blank.

The question is whether we should address these inconsistencies in 1.1.0. Should certainly check how earlier Web API and MVC releases handle the above cases. But might decide these inconsistencies are warts regardless. Or could split the scearios into "API" and "view" groups, then make separate decisions for each.

**Comment by Eilon** [comment]
What's the actual problem here? What observed behavior is odd, unusual, or difficult to work with?

**Comment by Eilon** [comment]
The first bullet point is handled by the associated bug.

The second bullet point doesn't seem concerning.

The third bullet point already has the right behavior: if no file is provided, there's no data. That seems to provide the best developer experience.
