### ISSUE TITLE
Model Validation based on multiple attributes

### ISSUE THREAD

**Issue by markusvt** [aspnet/Mvc#4976]
I have a model called `Booking` that has the following properties:
- Start (DateTime)
- End (DateTime)
- Places (IEnumerable<Place>)

when saving the model I want to validate, that there are no other Bookings of those places between the given dates, so I wrote a custom ValidationAttribute and assigned it to the Places property.

Inside the validation method, I do the following to get the model-object to be able to get the Start and End values: 
`Booking CurrentBooking = (Booking)validationContext.ObjectInstance;`

Unfortunately, when I change the values of those attributes on client-side and then hit the save button, at validation time there are always only the old values in my `CurrentBooking` object. 
How can I access the new values of those properties inside my validation method?

**Comment by dougbu** [comment]
@markusvt are you sure the "save" button results in correct model binding? For example, might remove your validation attribute and check the property values of your `Booking` action parameter.
