### ISSUE TITLE
Chinese string in cshtml is compiled to garbage characters.

### ISSUE THREAD

**Issue by lanwilliam** [aspnet/Mvc#4977]
`<input asp-for="Price" data-val-number="字段 {0} 必须是一个数字。" class="form-control" />`
vs2015 use default file encode ansi.
So,when i run the page in chrome,show  garbage characters.
If I change file encode into utf8,it works ok.

**Comment by lanwilliam** [comment]
And I don't know why data-val-number is not a resources .It's easy for localization.This applies equally to the jquery-validation script.

**Comment by seriouz** [comment]
Did you try this? http://www.skorkin.com/2012/07/how-to-set-the-default-encoding-for-all-files-saved-in-visual-studio/

**Comment by Eilon** [comment]
@lanwilliam for Visual Studio issues you can log an issue here: https://github.com/aspnet/Tooling/issues/

It's indeed an issue with file encoding during save, so once you change it (or change the default), it should work.

You can put your validation messages in resources by using Data Annotations and ASP.NET Core's new localization system. We have a complete sample here: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.LocalizationSample.Web

**Comment by lanwilliam** [comment]
@seriouz I know this,but I don't want to change it.
@Eilon Thx,Wish asp.net core could do better.
