### ISSUE TITLE
Change access modifier for InputTagHelper.GetInputType

### ISSUE THREAD

**Issue by marcusien** [aspnet/Mvc#4979]
For now I copied some source code from Mvc but It could be better to change private by protected on InputTagHelper for the method GetInputType

**Comment by NTaylorMullen** [comment]
@marcusien what are you building that could use `GetInputType`?

**Comment by marcusien** [comment]
I'm creating an InputTagHelper where I need to know which kind of input I'm facing of. I find it dumb to remake something existing in the base class.

And my need is very basic, I doubt to be the only one who needs it

**Comment by NTaylorMullen** [comment]
Fair enough. Not a horrible idea :+1:

**Comment by Eilon** [comment]
@NTaylorMullen please add some stellar doc comments to this API because it's not super clear to me what the parameters mean 😄

**Comment by NTaylorMullen** [comment]
663f6a1718447e46dbbfa868c4017000d767107e
