### ISSUE TITLE
How to use  ADO.NET  in asp.net core 1.0?

### ISSUE THREAD

**Issue by ermithun** [aspnet/Mvc#4980]
Please guide me to use ADO.NET in AspNetCore 1.0 with sample

**Comment by pranavkm** [comment]
Could you file this in https://github.com/aspnet/Home? This doesn't seem Mvc specific.

**Comment by Eilon** [comment]
@ermithun though we don't plan on having a sample for this, it's no different than using ADO.NET anywhere else. So, any example you find using ADO.NET on previous versions of MVC or in any other environment should be pretty much the same. MVC doesn't have any specific features or behaviors related to ADO.NET.

**Comment by ermithun** [comment]
@Eilon Thanks for your response .
