### ISSUE TITLE
Take AutoGenerateField into account for GetEnumSelectList

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#4982]
It would be convenient if the `GetEnumSelectList` helper methods only returned `SelectListItem`s for those enum values that either don't have a `DisplayAttribute` or do have a `DisplayAttribute` with `AutoGenerateField` set to `false`.

**Comment by Eilon** [comment]
It would be a breaking change to start doing that by default. Do you have any thoughts on what an API would look like that supports this? In general we like to avoid complex rules that are both difficult to describe and difficult to understand. E.g. in this case would someone be better off just having a different `enum` that they use for generating the list? Or just writing their own custom logic that processes the `enum` in a particular way and produces a `SelectList` that has only the desired items?

**Comment by tuespetre** [comment]
> Or just writing their own custom logic that processes the `enum` in a particular way and produces a `SelectList` that has only the desired items?

This.

Thanks!
