### ISSUE TITLE
502 Bad Gateway using File(fileContents, contentType, fileDownloadName)

### ISSUE THREAD

**Issue by recalde** [aspnet/Mvc#4984]
After updating from RC2 to RTM, the FileContent seems to be failing with 502 bad gateway.

`ControllerBase.File(fileContents, contentType, fileDownloadName)`

> Response	HTTP/1.1 502 Bad Gateway
> Content-Type	text/html; charset=utf-8
> Response Body
> {"FileContents":"UEsDBBQAAAAIAJN...

```
byte[] fileBytes = reportGenerator.GenerateWorkbook(...); // returns xlsx byte[]
string excelFormat = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
string reportName = "test.xlsx";
// 502 Bad Gateway
return File(fileBytes, excelFormat, reportName);
```

I see there is a commit that changes the FileContentResult.cs and adds a new FileContentResultExecutor.cs - I think this change may have something to do with it, and I'm looking through to see if maybe I can work around this -
https://github.com/aspnet/Mvc/commit/8493064fe5ac9a14eb0dbe970717b1821cdc7ad8

**Comment by recalde** [comment]
@javiercn any idea if something could have broken here?

**Comment by recalde** [comment]
Sorry this was my fault - old RC2 code seems to have supported an object return type for FileContentResult, though I'm not sure why it was used here... 

```
[HttpGet("GenerateReport/{id}")]
public **_object_** GenerateReport(string id)
{
}
```
Changing this fixes the issue.
```
[HttpGet("GenerateReport/{id}")]
public **_FileContentResult_** GenerateReport(string id)
{
}
```

**Comment by nil4** [comment]
@recalde the response body starts with `{"FileContents":...` and thus I think you may be hitting #4960 -- if so, be aware that all ActionResult subclasses seem to be affected.

**Comment by recalde** [comment]
@nil4 thanks that looks like it's the issue!
