### ISSUE TITLE
Html.ValidationSummary(ValidationSummary.All) throws NullReferenceException

### ISSUE THREAD

**Issue by rsheptolut** [aspnet/Mvc#4989]
This started after I've updated my project from RC1 to ASP.NET Core 1.0. The tag helper also throws this exception.
If instead you specify ValidationSummary.ModelOnly, there's no exception. But also no property-level errors, which is bad.
Workarond: traverse ViewData.ModelState.Values manually and generate appropriate html markup.

Stack trace:
```
System.NullReferenceException.
   в Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidationHelpers.Visit(ModelStateDictionary dictionary, ModelStateEntry modelStateEntry, ModelMetadata metadata, List1 orderedModelStateEntries)
   в Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidationHelpers.Visit(ModelStateDictionary dictionary, ModelStateEntry modelStateEntry, ModelMetadata metadata, List1 orderedModelStateEntries)
   в Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidationHelpers.GetModelStateList(ViewDataDictionary viewData, Boolean excludePropertyErrors)
   в Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateValidationSummary(ViewContext viewContext, Boolean excludePropertyErrors, String message, String headerTag, Object htmlAttributes)
   в Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.GenerateValidationSummary(Boolean excludePropertyErrors, String message, Object htmlAttributes, String tag)
   в Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.ValidationSummary(Boolean excludePropertyErrors, String message, Object htmlAttributes, String tag)
   в Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperValidationExtensions.ValidationSummary(IHtmlHelper htmlHelper)
```

**Comment by dougbu** [comment]
We definitely test w/ `ValidationSummary.All`. This issue is likely specific to your model types. Please share those class definitions.

**Comment by rsheptolut** [comment]
@dougbu No, nothing specific to a model, this fails on all my models.

Example (simplified, but verified):
```c#
[Table("Currency", Schema = "dic")]
public class Currency
{
    [Timestamp]
    [Column(Order = int.MaxValue)]
    public byte[] Ts { get; set; }

    [Key]
    [StringLength(3, MinimumLength = 3)]
    [Column(TypeName = "nchar")]
    public string Id { get; set; }

    [StringLength(3)]
    public string CurrencySymbol { get; set; }
}

public class CurrencyController
{
    [ValidateAntiForgeryToken]
    [HttpPost]
    [ActionName("Edit")]
    public IActionResult ApplyEdit(Currency model)
    {
        ModelState.AddModelError(nameof(model.CurrencySymbol), "Lame!");
    }
}
```
Currency/Edit.cshtml (simplified, I posted values to it via refreshing browser which remembers 'real' post values)

```cshtml
@model object
@Html.ValidationSummary();
```

Debugger says that Model is of type "Currency", so is ModelMetadata.ModelType == typeof(Currency), so everything seems legit. And my other 100 tons of code that depend heavily on ModelMetadata continue to work perfectly.

**Comment by dougbu** [comment]
Looks like a straightforward bug in `ValidationHelpers.Visit()`. That method (specifically [this block](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ValidationHelpers.cs#L93-L99)) doesn't handle cases where a collection property is not bound. Just needs a `null` check on `modelStateEntry.Children`.

**Comment by dougbu** [comment]
Reassigning to _do_ the straightforward fix.

**Comment by pranavkm** [comment]
@dougbu is there a workaround for this in 1.0.0 (besides the option @rsheptolut suggested)?

**Comment by dougbu** [comment]
> is there a workaround for this in 1.0.0

Since the problematic property is get-only outside `ModelStateDictionary`, @rsheptolut's workaround is about it. With respect to that workaround, probably best to create a `DefaultHtmlGenerator` subclass that overrides `GenerateValidationSummary()`. More generally, stick with `ModelOnly` and use validation message helpers to ensure property-level issues are visible.

**Comment by dougbu** [comment]
e5cb6f9

**Comment by genusP** [comment]
Workarond for 1.0.0
```c#
private void HackModelState(string key)
{
      var modelStateEntry = ModelState[key];
      var nodeType = modelStateEntry.GetType();
      nodeType.GetMethod("GetNode").Invoke(modelStateEntry, new object[] { new Microsoft.Extensions.Primitives.StringSegment("--!!f-a-k-e"), true });
      ((System.Collections.IList)nodeType.GetProperty("ChildNodes").GetValue(modelStateEntry)).Clear();
}
```

**Comment by gdoron** [comment]
Would it be possible to add it to 1.0.1?
It can't break anything, having to wait several months for it would be a shame.

**Comment by prophetal** [comment]
can someone give me a hint how to implement the Workarond for 1.0.0 ?

**Comment by rsheptolut** [comment]
I use the following workaround in my production code for now:
```cshtml
<form class="form-horizontal" asp-antiforgery="true">
    <fieldset>
        // All of this instead of @Html.ValidationSummary() due to a bug in ASP.NET Core 1.0
        @if (!@ViewData.ModelState.IsValid)
        {
            var errors = ViewData.ModelState.Values.Select(item => item.Errors.FirstOrDefault()?.ErrorMessage).Where(item => item != null);
            <div class="alert alert-danger">
                <span>@Localizer["There are problems with your input:"]</span>
                <ul>
                    @foreach (var error in errors)
                    {
                        <li>@error</li>
                    }
                </ul>
            </div>
        }
    </fieldset>
</form>
```

**Comment by prophetal** [comment]
Thanks rsheptolut that works great!

I had a multi file upload field that throw that error i think there are a lot of people that will need this workaround before the 1.0.1 release.

public ICollection<IFormFile> AttachmentFiles { get; set; }

**Comment by gdoron** [comment]
It seems like for some reason, it will be released only in 1.1.0

**Comment by genusP** [comment]
need call HackModelState for each enumerable property
```c#
public class ClOrderViewModel
{
...
 public AttachmentViewModel[] Attachments { get; set; }
...
}
class OrdersController:Controller
{
...
[HttpPost]
        public IActionResult Index(int? id, ClOrderViewModel vm, [FromServices] IClOrderRepository repository)
        {
            if (ModelState.IsValid)
            {
                if (id.HasValue)
                    repository.UpdateOrder(id.Value, vm);
                else
                    id = repository.InserOrder(vm);
                return RedirectToAction(nameof(Index), new { id = id.Value });
            }
            HackModelState(nameof(vm.Attachments));
            return View("ClOrder", vm);
        }
...
}
```

**Comment by dougbu** [comment]
@danroth27 @Eilon should we include this in 1.0.2? @gdoron suggested that above (https://github.com/aspnet/Mvc/issues/4989#issuecomment-242229755) and in aspnet/EntityFramework#6760.

**Comment by Eilon** [comment]
@dougbu you mean like https://github.com/aspnet/Mvc/issues/5157? 😄

**Comment by dougbu** [comment]
@Eilon hmm, yeah. Fairly similar. 😈

**Comment by dougbu** [comment]
Ported to rel/1.0.2 in f8f9bbc
