### ISSUE TITLE
Making DefaultAssemblyPartDiscoveryProvider more generic

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Mvc#4990]
Wondering if there are any thoughts on making [`DefaultAssemblyPartDiscoveryProvider`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/DefaultAssemblyPartDiscoveryProvider.cs) more generically available?

This would involve putting the type in a more generally available package (maybe one of the `Microsoft.Extensions.*` packages or something more central), making it so that the `ReferenceAssemblies` can be externally provided and `DependencyClassification.MvcReference` be updated to be something a little more generic.

Thoughts?

// @davidfowl @loudej

**Comment by javiercn** [comment]
You can do that through MvcBuilder.ApplicationPartManager. What's your scenario?

**Comment by avanderhoorn** [comment]
Unfortunately that would mean taking a dependency on MVC, which is what I'm
trying to avoid. My scenario is similar to the one that
of DefaultAssemblyPartDiscoveryProvider already caters for, except instead
of finding any DLLs that depend on MVC packages, I want to know about any
DLLs that depend on Glimpse packages.

**Comment by brockallen** [comment]
There are many APIs coupled to MVC that would be nice to be separate.

**Comment by davidfowl** [comment]
I think @avanderhoorn just wants logic that given the application's assemblies and some framework assemblies, find the application assemblies that are referenced by the framework assemblies.

**Comment by avanderhoorn** [comment]
Pretty much what @davidfowl said except not just limited to application assemblies that are referenced by the framework assemblies. I want that logic to be find the assemblies in the applications dependency graph that are referenced by the framework assemblies - which is what this class does, except that the framework assemblies its targeting are hardcoded and it requires taking a dependency on MVC.

**Comment by avanderhoorn** [comment]
Currently I have taken an exact copy of the code in `DefaultAssemblyPartDiscoveryProvider` and just modified the framework list. It would be nice not to have to maintain this code.

**Comment by rynowak** [comment]
It really seems like if anything this would be a candidate including in dependency context, I'd suggest moving it to dotnet/cli

**Comment by avanderhoorn** [comment]
So whats the next step for something like this happening?

**Comment by davidfowl** [comment]
File an issue here https://github.com/dotnet/cli/issues

/cc @pakrym

**Comment by Eilon** [comment]
Yup, this would be a good API to have in general in .NET Core apps. The MVC one is still needed for MVC-specific scenarios.
