### ISSUE TITLE
Production Website ASP.NET Core 1.0 gives 404 NOT FOUND - The server has not found anything matching the requested URI. (XHR): GET - https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/dist/css/bootstrap.css

### ISSUE THREAD

**Issue by Ponant** [aspnet/Mvc#4992]
We deployed an ASP.NET Core app to Azure. The website runs, but it shows an HTTP 404 error in Edge Browser F12 Dev Tools

NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/dist/css/bootstrap.css

with a delay time in the request of approximately 1.2 seconds, which we need to overcome. We reproduced the step with the template only, thereby confirming that the bug is not due to our own code:

**_Steps to reproduce**_
In Visual Studio 2015 Community Edition Update 3:
.NET Framework 4.6.1
ASP.NET Core Web Application (.Net Core)
Web Application Template, No Auth
Upload to Azure + F12 on Edge

I assume the issue is related to the _Layout.cshtml
`<environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>`

Can anyone reproduce this issue (you must be in production/staging)?
Since we are in production, we would highly appreciate a feedback on how to solve this issue.
Thanks

**Comment by NikolayIT** [comment]
This issue is not related to ASP.NET MVC.

The URL you have specified (`https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/dist/css/bootstrap.css`) does not exist on Microsoft servers.

For staging and production you should be using `https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css`.

**Comment by Ponant** [comment]
I received an email which somewhat does not appear on github. It states that this issue is not related to ASP.NET MVC and that we are not using the correct url. I am sorry but this is not true. Our code snippet is shown above, it uses the url

https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css (Staging Production)

and recall that we used the ASP.NET Core 1.0 Web App template without modification.
The issue occurs once we browse on the production website, it tries to download another file,
https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/dist/css/bootstrap.css
which indeed does not exist.
Why is that?

**Comment by danroth27** [comment]
This seems to be happening due to the bootstrap source map:

```json
{"version":3,"sources":["less/normalize.less","less/print.less","bootstrap.css","dist/css/bootstrap.css",
```

Browser developer tools will download these files so that they can understand the minified versions. It looks like the CDN doesn't have `dist/css/bootstrap.css`.

@sayedihashimi

**Comment by RocketJSC** [comment]
I'm having the same issue.  Is there a work-around?

Mark

**Comment by danroth27** [comment]
@DamianEdwards Do we need to make a CDN update to address this?

**Comment by wyshmily** [comment]
Having the same issue. 
it costs about 1 second for Every request.

**Comment by rowlandg** [comment]
Any updates?

**Comment by Eilon** [comment]
@rowlandg we're taking a look now, sorry for the delay.

**Comment by DamianEdwards** [comment]
We need to get those files added to the CDN (might need to look at jQuery, etc. too)

**Comment by ChrisSfanos** [comment]
I've added the /css/dist/css files for both 3.3.6 and 3.3.7 of bootstrap on the CDN

**Comment by Eilon** [comment]
Thanks, @ChrisSfanos !
