### ISSUE TITLE
Publishing Areas would copy cs files too

### ISSUE THREAD

**Issue by sadjadbp** [aspnet/Mvc#4993]
With an MVC site with Areas folder that has Controllers and Views folder under each Area in the project.json we should have 

`"publishOptions"` : {"include": [ "Areas" ] }`

With RC1 it was ok, now with RTM Core 1.0, it will copy the controller and cs files inside those Areas folders.

**Comment by sadjadbp** [comment]
@danroth27 Thanks, I've just tried that but now the whole "Areas" folder won't get published. I'm trying via Visual Studio 2015, publish menu with Asp.Net Core 1.0

**Comment by rynowak** [comment]
Sorry, it looks like we steered you into a bug - https://github.com/dotnet/cli/issues/3286

Try `"Areas/**/Views/*.cshtml"` - if there's other files beyond cshtml that you need to publish from there you'll need to add more globbing patterns

**Comment by sadjadbp** [comment]
@rynowak seems more like `Areas/**/Views/**/*.cshtml` to support different controllers under areas

**Comment by tuespetre** [comment]
@rynowak @sadjadbp `**/*.cshtml`? :trollface:

**Comment by rynowak** [comment]
That's actually what we're planning on changing it to
