### ISSUE TITLE
 Microsoft.AspNetCore.Mvc 1.0.0 does not support framework .NETCoreApp,Version=v1.0.

### ISSUE THREAD

**Issue by NVentimiglia** [aspnet/Mvc#4999]
When I do a *dotnet build* I get the following error. 

>  The dependency Microsoft.AspNetCore.Mvc 1.0.0 does not support framework .NETCoreApp,Version=v1.0.

- Project is a minimal MVC site with EF, SQLITE, and a Websocket
- This works fine on windows
- I am running on a mac
- I have updated to the latest dotnet release
- 'new' projects restore, build, and run fine

Full project can be found.

https://github.com/NVentimiglia/DotNetCoreUnity3d/tree/master/Server/src/CoreWeb1

Full Terminal Log below.

> nick-macbook28:CoreWeb1 loanercomputer$ dotnet restore
log  : Restoring packages for /Users/loanercomputer/Desktop/CoreWeb1/Server/src/CoreWeb1/project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.mvc/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iisintegration/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.kestrel/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.staticfiles/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlite/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.environmentvariables/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.fileextensions/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.json/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.console/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.debug/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.debug/index.json 305ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlite/index.json 375ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.kestrel/index.json 383ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.fileextensions/index.json 379ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.mvc/index.json 415ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.console/index.json 386ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.json/index.json 387ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.staticfiles/index.json 402ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iisintegration/index.json 405ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.environmentvariables/index.json 402ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/index.json 431ms
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in /Users/loanercomputer/Desktop/CoreWeb1/Server/src/CoreWeb1/project.json...
error: Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
log  : Restoring packages for tool 'Microsoft.EntityFrameworkCore.Tools' in /Users/loanercomputer/Desktop/CoreWeb1/Server/src/CoreWeb1/project.json...
error: Package Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
error: Package Microsoft.AspNetCore.Mvc 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNetCore.Mvc 1.0.0 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
info : Committing restore...
log  : Writing lock file to disk. Path: /Users/loanercomputer/Desktop/CoreWeb1/Server/src/CoreWeb1/project.lock.json
log  : /Users/loanercomputer/Desktop/CoreWeb1/Server/src/CoreWeb1/project.json
log  : Restore failed in 2579ms.

> Errors in /Users/loanercomputer/Desktop/CoreWeb1/Server/src/CoreWeb1/project.json
    Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
    Package Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
    Package Microsoft.AspNetCore.Mvc 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNetCore.Mvc 1.0.0 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

> NuGet Config files used:
    /Users/loanercomputer/.nuget/NuGet/NuGet.Config

> Feeds used:
    https://api.nuget.org/v3/index.json
nick-macbook28:CoreWeb1 loanercomputer$ dotnet build
Project CoreWeb1 (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling CoreWeb1 for .NETCoreApp,Version=v1.0
/Users/loanercomputer/Desktop/CoreWeb1/Server/src/CoreWeb1/project.json(8,40): error NU1002: The dependency Microsoft.AspNetCore.Mvc 1.0.0 does not support framework .NETCoreApp,Version=v1.0.

> Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.0233537

**Comment by NVentimiglia** [comment]
@pranavkm thanks for the quick reply !

1.0.0-preview1-002702

This looks wrong. I just downloaded and installed dotnet-dev-osx-x64.1.0.0-preview2-003121.

My guess is I am still working with outdated bits, is there an official guide for uninstalling and reinstalling ?

**Comment by pranavkm** [comment]
https://www.microsoft.com/net/core#macos should have instructions on how to go about updating. I think it should take care of updating old bits if they're already installed.

**Comment by NVentimiglia** [comment]
@pranavkm 

Yes, Ive been using that link as my download source. There are no uninstall instructions for preview 1. Installing preview 2 on-top does not work.

**Comment by davidfowl** [comment]
> Yes, Ive been using that link as my download source. There are no uninstall instructions for preview 1. Installing preview 2 on-top does not work.

It does but you need to change the following.

https://github.com/NVentimiglia/DotNetCoreUnity3d/blob/master/Server/global.json#L4

**Comment by NVentimiglia** [comment]
@davidfowl  Thanks so much, I didn't even think to look in that file.
