### ISSUE TITLE
How do I use ControllerFeature instead of IControllerTypeProvider?

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Mvc#5004]
In RC1 I used the `IControllerTypeProvider` in my custom router to check if one controller has a specific action. In RC2 it seems to be removed and maybe replaced with [ControllerFeature](https://github.com/aspnet/Mvc/issues/4730#issuecomment-221352713)? I tried to replace `IControllerTypeProvider` with `ControllerFeature` but that guy is null.

This is how I used the `IControllerTypeProvider` and now I want to replace it with the `ControllerFeature`, I think?
```c#
public ControllerMapper(IControllerTypeProvider controllerTypeProvider)
{
  foreach (var type in controllerTypeProvider.ControllerTypes)
  {
    ControllerMap.TryAdd(type, type.Name.Replace("Controller", ""));
    var methodNames = type.GetMethods().Select(x => x.Name).ToArray();
    ControllerActionMap.TryAdd(type.Name.Replace("Controller", ""), methodNames);
  }
}
```

**Comment by rynowak** [comment]
You can populate a `ControllerFeature` like so:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionDescriptorProvider.cs#L96 (DI a reference to `ApplicationPartManager`). 

What is it you're trying to do exactly? Looking at the types of controllers is going to miss some of the metadata that affects how actions are mapped.

**Comment by rynowak** [comment]
You shouldn't have to register the `ApplicationPartManager` - `AddMvc()` does that.

If you want to use `ApplicationPartManager` outside of calling `AddMvc()` then you'll have to decide how to populate the list of parts (assemblies).

**Comment by marcuslindblom** [comment]
@rynowak Ok, changed it to this and it seems to work, at least with one assembly.

```c#
services.AddMvc().ConfigureApplicationPartManager(manager =>
            {
                var feature = new ControllerFeature();
                manager.PopulateFeature(feature);
                services.AddSingleton<IControllerMapper>(new ControllerMapper(feature));
});
```
