### ISSUE TITLE
Mobile Specific Views / Device Detection

### ISSUE THREAD

**Issue by tysonnero** [aspnet/Mvc#5006]
In the .NET Core docs there is a page titled "Building Mobile Specific Views" but is under construction: https://docs.asp.net/en/latest/mvc/views/mobile.html.

Does anyone have some insight on building mobile views or successfully doing device detection?

**Comment by danroth27** [comment]
Currently you can build mobile specific views using view location expanders. We are still working on documentation for this scenario.  See https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.SubAreaSample.Web/SubAreaViewLocationExpander.cs for an example of using a view location expander.

**Comment by tysonnero** [comment]
@danroth27  Thanks for the info! To get Mobile Views working, however, I'm assuming one would have to do device detection via user-agent, correct? Seems like a lot of devs nowadays are shying away from the tactic.

**Comment by wangkanai** [comment]
Any progress on building mobile specifics views documentation?

**Comment by pranavkm** [comment]
@wangkanai see https://github.com/aspnet/Razor/issues/751.

**Comment by wangkanai** [comment]
I wrote my own implementation of mobile specific views 
[https://github.com/wangkanai/Responsive](https://github.com/wangkanai/Responsive)
Might see it useful for others. The concept is to use file extensions;
- index.cshtml
- index.tablet.cshtml
- index.mobile.cshtml
it will fall back the list if the extension is not available.

**Comment by frankabbruzzese** [comment]
@tysonnero , I think the best option is features detection on the client side. Once detected features, page may adapt dynamically via Css and JavaScript, or it may package all relevant support data in a cookie and then redirect to the original page, so a more adequate View may be chosen. 

The User Agent way has the disadvantage one must rely on pre-collected infos about all devices capabilities.
