### ISSUE TITLE
DataAnnotationsClientModelValidatorProvider not always using IValidationAttributeAdapterProvider

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#5009]
I was trying to localize my app, but I found out that my `IValidationAttributeAdapterProvider` doesn't get called then a value type is assigned `[Required]` attribute by default. [I think the problem lies here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/DataAnnotationsClientModelValidatorProvider.cs#L102). It's always using default required adapter implementation.

Workaround is to add `[Required]` attribute on value types.

**Comment by danroth27** [comment]
@dougbu Thoughts on this?

**Comment by dougbu** [comment]
@danroth27 the class in question already has the `IValidationAttributeAdapterProvider`. Fix is just a matter of using it.

**Comment by dougbu** [comment]
Cleared Investigate label and assignee since investigation is done.``

**Comment by dougbu** [comment]
Much appreciated @rynowak

**Comment by dougbu** [comment]
35cc5b6
