### ISSUE TITLE
[Question] Using ModelBinderAttribute vs IModelBinderProvider

### ISSUE THREAD

**Issue by BadriL** [aspnet/Mvc#5010]
I have a `IModelBinder`. Now, I have two options to use the binder.

(1) Use `ModelBinderAttribute` and specify the `BinderType` against my action method parameter.

(2) Create a `IModelBinderProvider` that returns an instance of my binder class in the `GetBinder` method. Add the model binder provider to the list of `ModelBinderProviders`.

Why should I use one over the other and what is the difference please?

**Comment by rynowak** [comment]
/cc @dougbu 

A provider is app-wide, so you will need to be able to look at individual models and properties and make a decision about whether or not you want to bind them. You also have to deal with issues or ordering and where your providers should be in the list of providers. This is complex but powerful.

Using the attribute applies your binder exactly where you want it, so use it if:
- your binder applies to a specific set of model types
- your binder applies to specific properties

Remember, you can use `[BinderType(...)]` on parameters, properties, and types.


In general prefer the attribute unless you're building a system that you're going to ship to 3rd parties.
