### ISSUE TITLE
Output formatters should not use TypedHeaders to parse Accept-Charset

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5013]
Data from TechEmpower (Json)
![image](https://cloud.githubusercontent.com/assets/1430011/16783465/efff68c6-4838-11e6-855b-f905ec58cc4f.png)

This is about 2% of CPU time. We don't need the typed headers object, which is large. We should just parse the `Accept-Charset` ourselves

**Comment by danroth27** [comment]
@javiercn Please start by figuring out with @Tratcher what it would take to do this.

**Comment by Tratcher** [comment]
Please avoid duplicating parser code. Have you tried to optimize the existing parser code?

**Comment by rynowak** [comment]
We want to avoid using typed headers, it would be great to reuse the existing parsing code without having to go through typed headers.

**Comment by Tratcher** [comment]
So you just want to avoid creating the MediaTypeHeaderValue objects? What output would you generate instead?

**Comment by javiercn** [comment]
Would this follow a similar approach as the one we did for the Accept header?

**Comment by rynowak** [comment]
The goal is to avoid allocating anything if possible. Especially in the common case where `Accept-Charset` isn't set. Right now we do a lot of work just to find out that the header isn't present.

**Comment by Eilon** [comment]
Moved to 1.2.
