### ISSUE TITLE
Get rid of Linq in [Produces]

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5017]
`ProducesAttribute` is on the hot path for techempower and other high throughput API scenarios. There's no need for Linq here. 

Perfview data here from techempower JSON:
![image](https://cloud.githubusercontent.com/assets/1430011/16812901/110f445e-48e4-11e6-9370-a1b2814d9c4d.png)

The highlighted line is at least 2% of CPU time spent inside of Kestrel

**Comment by ryanbrandenburg** [comment]
I assume that this work item includes profiling it afterward to confirm that removing Linq has fixed it.

**Comment by rynowak** [comment]
You assume correctly. Track me down if you need help
