### ISSUE TITLE
Discussion: Looking to contribute Authorized taghelper

### ISSUE THREAD

**Issue by mirkogeffken** [aspnet/Mvc#5018]
I started with a PR (PR #4996) for this and was pretty quickly schooled on some concepts new to me (specifically Policies) by @blowdart, @dougbu, and @davidfowl. Adding @NTaylorMullen as he seemed interested in providing something like this.

My plan was to offer an `<authorized />` taghelper that would display content only for authenticated/authorized users. Usage was going to be (before schooling):

```
<authorized>You are authenticated</authorized>
<authorized is-inverted="true">You are not authenticated.</authorized>
<authorized roles="role1,role2">You are in role1 or role2</authorized>
<authorized roles="role1,role2" is-inverted="true">You are neither a role1 nor a role2</authorized>
```

I was not in love with my is-inverted property already and policies seem to make a lot more sense as they would allow for inversion of role/requirements checks. This would be in kind what the `[Authorize]` tag is also using. 

Having said that the ASP.NET team obviously opted for retaining the roles property on the authorize attribute (for the obvious reason that while policy based access makes testing easy and is super flexible may be overkill for some super simple scenarios). 

Unfortunately the `[Authorize]` attribute also has the distinct advantage of being able to NOT be applied essentially allowing for an easy unauthenticated story. I would hate for the taghelper story to have to require people to define policies as a requirement and would prefer to allow to also let people specify roles optionally. The problem this leaves is the unauthenticated story, which is probably in the 99% percentile for use-cases. (Not being in a role is clearly a more advanced usage scenario which I think policies would handle nicely).

So I am looking for some opinions before giving this another go:

1) Stick with only a policy attribute

```
<authorized>You are authenticated</authorized>
<authorized policy="Unauthenticated">You are not authenticated via policy</authorized> <-- Icky
<authorized policy="FooOrBar">You are in the foo or bar role via policy</authorized> <-- Icky as it requires policies to be defined for everything
```

2) Allow for both roles and a policy attribute

```
<authorized>You are authenticated</authorized>
<authorized policy="Unauthenticated">You are not authenticated via policy</authorized> <-- Still Icky
<authorized roles="Foo,Bar">You are a foo or a bar via roles</authorized>
<authorized policy="FooOrBar">You are a foo or a bar via policy</authorized>
<authorized roles="Qux" policy="FooOrBar">You are a Qux AND either foo or bar via roles and policy</authorized> <-- Not sure the AND here is intuitive, but would in spirit match the [Authorize] attribute behavior
```

3) Add additional tags (The exact wording is not so important for now) with roles and policy

```
<authorized>You are authenticated</authorized>
<unauthorized>You are not authenticated</unauthorized>
<authorized roles="Foo,Bar">You are a foo or a bar via roles<authorized>
<unauthorized roles="Foo,Bar">You are neither a foo nor a bar via roles<unauthorized>
<authorized policy="FooOrBar">You are a foo or a bar via policy<authorized>
<unauthorized policy="FooOrBar">You are neither a foo nor a bar via policy<unauthorized>
<authorized roles="Qux" policy="FooOrBar">You are a qux AND foo or a bar via roles and policy<authorized>
<unauthorized roles="Qux" policy="FooOrBar">You are NOT (a qux and either a foo or a bar) via policy and roles<unauthorized>
```

Here the `<unauthorized>` would always show with exactly the opposite rules from the `<authorized>`

4) 3) with simplification of the `<unauthorized />` tag to only accommodate the unauthenticated scenario (so no roles or policy attribute at all) as that covers 99% of common use cases still and any other case can be accomplished via policy if needed

5) Insert better ideas here ...

I am leaning towards 3) as that most closely mirrors the `[Authorize]` attribute and adding the inverse use-case needed. I am presuming the 99% case for all authenticated sites to be to at least have the need to show a difference between authenticated and not authenticated users (log in/log out etc.). These cases should be easy to get in without having to setup a policy for it. Besides this I think many will want to just trim by roles and not have the additional policy setup hassles. If we had wanted to force (ahem entice) people into the (arguably) better policy model always, then the `[Authorize]` attribute should have foregone the roles property as well.

Sorry for the TL;DR

Thoughts on approach as well as interest in having something like this with the framework vs. contribs?

**Comment by blowdart** [comment]
Roles was kept for back compatibility with the previous version of Authorize, which only accepts a list. If you wanted to support roles I'd limited yourself to the comma is an OR syntax alone, and let anyone who wants to be more complicated use a policy. Nesting would provide the AND syntax anyway.

**Comment by mirkogeffken** [comment]
I agree. Advanced scenarios can be handled via Policy. Not sure I was suggesting anything but above. The unauthorized taghelper however would flip this to effectively AND behavior by inverting the check. If that was not to happen that way I think the rules would be harder to reason about.

As an aside, I was just trying out some stuff and oddly the Roles property on the `[Authorize]` attribute now seems to be case sensitive to roles. (So if the role in the DB is Qux and you specify "qux" that is no longer a match. I do not recall the property being case sensitive before. Am I missing something? If I didn't then it isn't all that back compatible even :)

**Comment by blowdart** [comment]
I'd have hoped the old version was case sensitive, but given we now map JWT roles too, it needs to be this time around.

**Comment by mirkogeffken** [comment]
@blowdart 

1) Do you think it would be better to drop Roles and get people used to defining policies? Maybe offer roles, but throw an exception with default settings requiring something like `AllowRolesOverPolicies` to be flicked to true under some appropriate options somewhere? If so, maybe add the same exceptions when Roles are used on `[Authorize]` attributes. I honestly think developers appreciate being hinted to using things the right way, but also want to do things quickly intentionally sometimes.
2) Do you think multiple policies with Roles-like OR semantics should be supported? `<authorized policies="InFooRole,InBarRole" />` This would allow for some composition (with the AND covered by nesting). The only way this is supported in taghelpers to my knowledge would be via comma separated strings again (I was hoping violating html attribute rules would just have worked and assigning multiple policy="Foo" and policy="Bar" would have been nicely mapped to a `string[]` property or `List<string>`, but that was not to be)
3) Do you think we should have the inverse taghelper? Something like `<unauthorized />` (I am specifically not looking forward to having to define a "NotAuthenticated" or "CanSignIn" policy, which would be needed in 100% of all systems for the log in button). 
4) If you are against 3) and instead in favor of having to define a policy, then should policy be required on the taghelper always for even the authenticated only scenario? Meaning you would define "CanSignIn", "CanSignOut", etc. policies.

**Comment by blowdart** [comment]
Please keep in mind, I'm only the security person for .NET. My feelings around design and apis are always coloured by that. I feel a simple API surface for security works best because there's less change for folks to use it wrong.

1. I think you should support both, just because the attribute does. Mirroring that is easiest for folks to understand in my opinion

2. Yes, I'd have the list as OR and let nesting do the AND. Again this mirrors the attribute behaviour

3. Makes sense :) Have the roles and policies optional, so you can support the "Not logged in" scenarios.

**Comment by brockallen** [comment]
@mirkogeffken related: https://github.com/aspnet/Mvc/issues/3785

**Comment by mirkogeffken** [comment]
@brockallen Thanks for the related pointer. Would be great to have both actually since sometimes it is needed to mask just content and have the element disappear in the process. 

Wondering if it wouldn't almost be better to have more generic prefixes for both and then add the type of check for specifics (akin to `ng-show`/`ng-hide`, so `asp-show="Model.True"`, `asp-hide="Model.True"`), then expand with `asp-show-policies="P1,P2"`, `asp-show-roles="R1,R2"`, etc.). 

For element taghelpers, shouldn't they be prefixed as well? HTML standards in the future could otherwise introduce clashing ones, so regardless of naming otherwise, should they not be `<asp-*>` as well?

**Comment by brockallen** [comment]
> akin to ng-show/ng-hide

Related: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Host/UI/TagHelpers/HideShowTagHelpers.cs

**Comment by dougbu** [comment]
@mirkogeffken 

> For element taghelpers, shouldn't they be prefixed as well?

The convention for the in-box MVC tag helpers is that none use an element prefix. Those targeting existing HTML elements prefix their attributes with `asp-` but that's it. (Of course they're all affected if users add a `@tagHelperPrefix` directive.)

Suggest you follow the `<environment>` pattern here: No prefix for the element or its attributes.

**Comment by Eilon** [comment]
Closing because there are no plans to build this, but we will have a sample package with these: https://github.com/DamianEdwards/TagHelperPack/issues/5

And here's the source codez for it: https://github.com/jongalloway/aspnetcore-app-workshop/blob/master/src/FrontEnd/TagHelpers/AuthzTagHelper.cs
