### ISSUE TITLE
asp.net core project occurs MissingMethodException

### ISSUE THREAD

**Issue by lunyi** [aspnet/Mvc#5019]
Hi all 

I create a new project with ASP.NET Core Web Application(.NET Core). And it can work after building and running it.

I create a class library with .NET Core and move the files under Service folder in the web project to the library, then add the reference and change namespace in the controllers.

It occurs MissingMethodException after registering a new user.
Asp.net core project seems not able to use class library outside the web project.

The detailed message is as the below.

An unhandled exception occurred while processing the request.

MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<!0> System.Threading.Tasks.ValueTask`1.op_Implicit(System.Threading.Tasks.Task`1<!0>)'.
Microsoft.AspNetCore.Server.Kestrel.Http.MessageBody.ForContentLength.ReadAsyncImplementation(ArraySegment`1 buffer, CancellationToken cancellationToken)

**Comment by rynowak** [comment]
This is due to a breaking change in some .NET apis that happened between RC2 and 1.0.0. You'll see this error when mixing versions of Kestrel with older versions of dotnet. Check that you are using 1.0.0 versions of everything.

Can you post your project file and `dotnet --version` output?

**Comment by lunyi** [comment]
hi rynowak

Do you mean the below in project.json ?

"frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

**Comment by davidfowl** [comment]
@lunyi No, the versions in the dependencies section of your project.json and the version of the `dotnet` command line tool used.

**Comment by lunyi** [comment]
hi rynowak

Here should be you want 


  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    }
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    },
    "Microsoft.Extensions.SecretManager.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

**Comment by davidfowl** [comment]
Seems like you're using RC2. Did you make the class library and the Web project at different times? Do they both target rc2?

**Comment by lunyi** [comment]
hi davidfowl 

Do you mean the below ? it is really different between web project and class library. 
 "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },

**Comment by davidfowl** [comment]
That's part of it. Most of your packages have RC2 in the version strings.

**Comment by lunyi** [comment]
Hi davidfowl 

I change all class libraries to RC2 and remove "NETStandard.Library": "1.6.0".
It can work now, thanks for your big help.

**Comment by davidfowl** [comment]
No problem!
