### ISSUE TITLE
[Perf] AuthorizeFilter uses Linq and constructs a new AuthorizationPolicy per request

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#5022]
While profiling #5017 I found that AuthorizationFilter was using Linq in a couple places and building a new AuthorizationPolicy every time.

Investigate what kind of improvements we can get from resolving those issues.

![linq allocations](https://cloud.githubusercontent.com/assets/14987221/16857049/6b7038d8-49d2-11e6-9b61-a2d353526da2.jpg)

**Comment by rynowak** [comment]
@HaoK - this is running every request - is there a reason why we can't cache this value?
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L80

**Comment by HaoK** [comment]
This was changed fairly recently to be dynamic to fix https://github.com/aspnet/Security/issues/841 and support IPolicyProviders which may create different Policies per request.  cc @blowdart

**Comment by HaoK** [comment]
We could cache if the policy provider is the default implementation. That might be enough to avoid the perf hit for the vast majority of users?

**Comment by Eilon** [comment]
@ryanbrandenburg can you work with folks to see how best to mitigate this?

**Comment by ryanbrandenburg** [comment]
Here are the results of my profiling. First, here's what things look like without any changes:
![nochanges](https://cloud.githubusercontent.com/assets/14987221/16934014/5bfbd316-4d07-11e6-8590-1037fda881be.PNG)

Now here's what things look like if we remove the OfType<AuthorizeAttribute>:
![linqremoved](https://cloud.githubusercontent.com/assets/14987221/16934037/93b41d90-4d07-11e6-9580-06cc470d19ac.PNG)

Now if we "cache" the policy on the AuthorizeFilter as @HaoK suggested:
![cachedpolicy](https://cloud.githubusercontent.com/assets/14987221/16934050/ad71da74-4d07-11e6-938d-2e8ffa109dce.PNG)

I read this data as follows. Removing both of the OfType<> would remove ~.6MB, while caching the Policy saves ~1MB, this suggests to me that we should cache in the allowed instances, but also remove the OfType<>'s so that people not using the Default Provider can reap a most of the benefits too.

**Comment by ryanbrandenburg** [comment]
@rynowak noticed that we were making a Filter for every controller and action, whether it was doing anything or not. Here's what the perf looks like if we stop that:
![onlyneededfilters](https://cloud.githubusercontent.com/assets/14987221/16967422/a97b796e-4dbd-11e6-8a80-77f59490a5e9.PNG)
Significant savings are made with fewer `FulterItem`'s, `Int32[]`'s and `Dictionary<string,object>`'s.

In all this saves ~2.5MB out of ~113MB baseline over 3000 requests.

**Comment by ryanbrandenburg** [comment]
Fixed in #5044.
