### ISSUE TITLE
"Load" a partial view from a string

### ISSUE THREAD

**Issue by eamodio** [aspnet/Mvc#5031]
Is there any way to load a partial view from a string rather than a `.cshtml` file on disk?

I'm thinking about having razor stored in a DB that I would like to have rendered as a partial view inside of a main view.

Thanks!

**Comment by pranavkm** [comment]
You could register an `IFileProvider` backed by the db to `RazorViewEngineOptions.FileProviders`. The RazorViewEngine looks for specific paths from file provider instances. As long as you're able to map the path to a db entry, it should just work.
