### ISSUE TITLE
Caching and View Components

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#5033]
Have there been any thoughts/discussion surrounding the cacheability of view components? 
- Given that view components will often load their own data from some source, they seem like very good candidates for caching.
- I don't want to have to write the same `<cache>` or `<distributed-cache>` tag helper snippet (including the construction of the key, the expiration options, etc.) every single place I want to use the component.
- Using the `<cache>` tag helper within the view component's own view template, like to wrap the whole thing, is too late. (No, I didn't try it, yes, I thought it might be a good idea at first :wink:)
- [I suggested injectable/directly-usable view components here](https://github.com/aspnet/Mvc/issues/4812#issuecomment-232773636) and while I still would like to see that happen, it wouldn't be compatible with the caching goals of this issue.
- How would the (distributed or not) caching bit be layered with the view components architecture? Perhaps the caching is an amenity that the `IViewComponentHelper` provides and is responsible for.
- How would the caching be configured per view component? Perhaps through attributes, or perhaps the `ViewComponent` class could have a `virtual` method that can be overridden to return some kind of `CacheOptions` object or `null`. Problem here is when constructing the cache item key and how to get needed values from the passed arguments.

**Comment by danroth27** [comment]
> I don't want to have to write the same <cache> or <distributed-cache> tag helper snippet (including the construction of the key, the expiration options, etc.) every single place I want to use the component.

Are there things about using the cache tag helper that are cumbersome today that we could improve to make this usage simpler? Or do you simply not want to have to deal with the cache tag helper at all?

**Comment by Eilon** [comment]
There are no plans to do anything automatic here, though there are certainly a lot of building blocks to implement this, as you have noted.
