### ISSUE TITLE
column attribute for <textarea> is incorrect

### ISSUE THREAD

**Issue by KLuuKer** [aspnet/Mvc#5039]
for a `<textarea>` columns="123" is incorrect it should be cols="123"

[https://github.com/aspnet/Mvc/blob/a852352223f94406094315ee9ee51e16eb288571/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L661](https://github.com/aspnet/Mvc/blob/a852352223f94406094315ee9ee51e16eb288571/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L661)

[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea)

so according to what spec should the attribute be named columns instead of cols ?

**Comment by dougbu** [comment]
Yeah. Looks like we spell-corrected the attribute name way back when (112a5dd) :frowning:

**Comment by dougbu** [comment]
581a5ea

**Comment by dougbu** [comment]
Thanks @iscifoni :grey_exclamation:
