### ISSUE TITLE
No way to localize password policy messages

### ISSUE THREAD

**Issue by NGancevich** [aspnet/Mvc#5040]
I'd like to localize the following validation errors

    Passwords must have at least one non alphanumeric character.
    Passwords must have at least one lowercase ('a'-'z').
    Passwords must have at least one uppercase ('A'-'Z').

I have this in ViewModel

[Required(ErrorMessage = "The Password field is required.")]
        [StringLength(100, ErrorMessage = "The Password must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]

**Comment by Eilon** [comment]
cc @HaoK @blowdart 

I think you customize the `IdentityErrorDescriber` service to control the text in these messages. That way you can plug it into your own RESX files, localization database, etc.

**Comment by HaoK** [comment]
Yep, see test https://github.com/aspnet/Identity/blob/dev/test/Microsoft.AspNetCore.Identity.Test/UserManagerTest.cs#L1407 for an example of how to plug in your own describer.
