### ISSUE TITLE
asp-format not always honored for DateTime

### ISSUE THREAD

**Issue by ipjohnson** [aspnet/Mvc#5043]
When attaching the following asp-format="{0:MM/dd/yyyy}" to an input control the proper format is used for most cases but there seems to be an issue when a query string parameter is provided with the same name as the property being bound.

I'm attaching an example project that shows the behavior. I would expect the format to be MM/dd/yyyy in both cases. 

[DateTimeFormatTest.zip](https://github.com/aspnet/Mvc/files/372236/DateTimeFormatTest.zip)

**Comment by dougbu** [comment]
Please host the project somewhere we can view it. Downloading a Zip from the Internet isn't a great idea.

That said, it sounds like you're expecting `asp-format` to affect both HTML generation and model binding. The attribute is relevant only for HTML generation. However, it is true that `string`s the user submitted have higher precedence than a formatted `DateTime` or `DateTimeOffset` value.

**Comment by ipjohnson** [comment]
I actually don't have a place to host the example project. 

I'm not looking for the asp-format to affect both html generation and model binding.  Value is bound correctly to the model and I can see the value properly in the controller. It's with the HTML generation. 

Am I to understand you correctly that if I have a model with a property name StartDate, it won't be used if there is a query string parameter name StartDate? 

`
<input class="form-control" asp-for="StartDate" asp-format="{0:MM/dd/yyyy}"/>
`

**Comment by dougbu** [comment]
If you've got a GitHub account, you can create GitHub repositories.

W.r.t. query string parameters, the behaviour isn't that specific. One way to think of it: `ModelStateDictionary` values e.g. `ModelState["StartDate"].RawValue` have precedence over expression values e.g. the `StartDate` property on the model. And `asp-format` can't reformat something that's already a `string`, as `ModelState["StartDate"].RawValue` would be.

MVC works this way to ensure form submission data that fails validation round-trips correctly. Is the model valid in your case? Why do you wish to display something other than what the user submitted?

**Comment by ipjohnson** [comment]
Ok I've created a repository for this [Here](https://github.com/ipjohnson/AspFormat) ...

The model is valid, I was looking to truncate the time stamp off when displaying in the textbox as the user didn't put the value in it was carried over in the query string from a different page. Depending on use case the value is in the query string sometimes it's not.  

While it may have been designed this way it sure does seem like odd behavior.

**Comment by dougbu** [comment]
Ah, I see two oddities in your application

The following block won't be particularly relevant if model binding encountered invalid data for `StartDate`. Probably best to special case `!ModelState.IsValid` before doing this e.g. remove `ModelState["StartDate"]`.
``` c#
            if (!model.StartDate.HasValue)
            {
                model.StartDate = DateTime.Now;
            }
```

The `<a>` links to the `Test()` action should use the same format you expect from a user e.g. `DateTime.Now.ToString("MM/dd/yyyy")`.

**Comment by ipjohnson** [comment]
It's actually much hard in our real app to format the timestamp as it's coming from JS. 

That said I think the final answer is that format is really only applied initially when the view is first load, after that ModelState is used with no formatting. 

I can work around this now that I fully understand the behavior. Thanks for the help.
