### ISSUE TITLE
1.0 publish to iis ,how to use iis virtual directories

### ISSUE THREAD

**Issue by BruinY** [aspnet/Mvc#5047]
Published to the iis after, cannot use iis virtual directory Settings, not be able to access the virtual directory file, also can't upload files stored in the virtual directory, could you tell me how to achieve this requirement

**Comment by davidfowl** [comment]
There's no way (that I'm aware of) to access a vdir mapped inside of the same application. How are you using them?

**Comment by BruinY** [comment]
I don't know how to deal with, I have no idea at all.Very convenient mvc5 using iis virtual directory.So I want to know the core after 1.0 can implement the corresponding requirements

**Comment by BruinY** [comment]
@davidfowl Please help me

**Comment by davidfowl** [comment]
.NET Core running in IIS doesn't have support for accessing the resolved physical path from an IIS virtual directory. How are you using them in the application?

**Comment by BruinY** [comment]
I need through the iis virtual directory to store website pictures, and can be normal access

**Comment by davidfowl** [comment]
There's no API for doing this today.

**Comment by BruinY** [comment]
@davidfowl 
website path : d://website/test
image save path : d://image.  This directory before you can use the iis virtual directory, you should now how to do?
I need to store website to upload files to the corresponding directory, and can be accessed through http://www.xxx.com/image/xxx

**Comment by davidfowl** [comment]
2 questions for you:
- What does the code look like that saves the uploaded images to `d:\images`
- You should be able to use IIS to serve images from the vdir like you did before but you might have to use a `web.config` in the vdir folder to disable our the ASP.NET Core module.

**Comment by BruinY** [comment]
1.
public IActionResult Upload(IFormFile file){
Image image = Image.FromStream(file.OpenReadStream(), true, true);
....
image.save(path);
}

2.Don't know how to use this

3.I found through the app. UseFileServer can access files to another location

**Comment by davidfowl** [comment]
I'm even more confused now... If you don't care about the vdir because you are using physical paths in your application, what are you asking for exactly?

**Comment by BruinY** [comment]
Need a larger disk space for storing files.So need users to upload files to other physical path, it and the website is not a directory or disk.

**Comment by davidfowl** [comment]
Yes, but you were specifically asking about an IIS vdir and those answer to my 2 questions weren't very clear. Are you hardcoding the physical path to `d://images` for uploads and for the static file middleware?

**Comment by BruinY** [comment]
no use hardcoding, need to do this?

**Comment by davidfowl** [comment]
There's no API in ASP.NET Core to resolve a physical path for an IIS virtual directory.

**Comment by BruinY** [comment]
There is no API, do you have any other way to achieve this requirement?

**Comment by davidfowl** [comment]
You need the physical path.
