### ISSUE TITLE
It is not possible to copy text to clipboard from error message on development page.

### ISSUE THREAD

**Issue by maxim-boligatov** [aspnet/Mvc#5048]
When exception occurs development page is displayed in browser.  
Sometimes it significantly increases productivity when it is possible to copy error text or sample message from error page.  
For example for the following example I can just find RenderSection line in source:

```
         <!-- Styles -->
         @this.RenderSection("styles", required: false)
        </head>
        <body>
            @RenderBody()
        </body>
        </html>

```

But due to interactivity added to development page (all mouse events are handled) I cannot copy text to clipboard easy. So I have to extract it from HTML using firebug...
How can it be fixed/improved? What do you think?

**Comment by pranavkm** [comment]
Could you file this bug in the [Diagnostics](https://github.com/aspnet/Diagnostics) repo?

**Comment by maxim-boligatov** [comment]
This issue was moved to aspnet/Diagnostics#319
