### ISSUE TITLE
get IUrlHelper inside the Html Helper's method

### ISSUE THREAD

**Issue by omuleanu** [aspnet/Mvc#5051]
hi,
is there an easy way to get the IUrlHelper inside the extension method of an IHtmlHelper, besides passing it as a parameter from the view
I tried this:
```
html.ViewContext.HttpContext.RequestServices.GetService(typeof(IUrlHelper));
```
but no luck

**Comment by dougbu** [comment]
Get the `IUrlHelperFactory` and use that to create an `IUrlHelper`.

**Comment by omuleanu** [comment]
@dougbu  ```urlHelperFactory.GetUrlHelper``` asks for `ActionContext` as a parameter, can I get from `IHtmlHelper` ?

**Comment by dougbu** [comment]
> can I get from `IHtmlHelper`?

Yes, `ViewContext` is an `ActionContext` subclass and that's exposed in `IHtmlHelper`.

**Comment by omuleanu** [comment]
Thank You, it works
