### ISSUE TITLE
TagHelpers not working inside script blocks

### ISSUE THREAD

**Issue by msmolka** [aspnet/Mvc#5059]
On Razor view following code 
`<label asp-for="Id"></label>` 
is working

However the template one is not working:
```
<script type="text/x-kendo-template" id="toolbar-template">
    <label asp-for="Id"></label>
 </script>
```

Normal extension methods are working properly in both places:
 @Html.LabelFor(m => m.Id)

**Comment by NTaylorMullen** [comment]
@msmolka currently Razor only supports TagHelpers in script tags that have type text/html.
