### ISSUE TITLE
Performance when generating the Assembly name in Razor

### ISSUE THREAD

**Issue by Yves57** [aspnet/Mvc#5064]
Using the Visual Studio Profiler file of #5060 (with "Show All Code activated" @rynowak ),

It is possible to see that `DefaultRoslynCompilationService.Compile()` (54% of inclusive percentage) spends itself 4.7% of time in `Path.GetRandomFileName()`.

Just to try, I have made the two following tests:
```
var assemblyName = Guid.NewGuid().ToString("N");
--> No performance improvement

var assemblyName = Interlocked.Increment(ref _assemblyNameCounter).ToString();
--> Processing too small to be visible in the Profiler, and the method goes down to 49,6% of inclusive percentage.
```

Everything seems to work fine. Is it necessary to generate a real file name?

**Comment by rynowak** [comment]
I'm sure we can find a better way to do this. `Path.GetRandomFileName()` is [cryptographically secure](https://msdn.microsoft.com/en-us/library/system.io.path.getrandomfilename(v=vs.110).aspx) and I'm not sure we need that guarantee.

**Comment by pranavkm** [comment]
The convention came from what System.Web \ BuildManager did which wrote assemblies to disk. It really shouldn't matter for our use case. 
My only concern with Guids would be to verify that it does not affect the debugger in anyway. Incrementing integers seem ok. An alternative is to use the view name (See https://github.com/aspnet/Mvc/issues/4239).

**Comment by Yves57** [comment]
I'm not sure to understand the 2.25% number.
When navigating in the `Compile()` source code, I see 4.7% in front of the line. So for me it's 4.7% of overall CPU time.
When comparing old method with the 'number increment' method, it gives 54% - 49.6% = 4.4% (so more or less 4.7%).

I suppose the 'number increment' is faster.
And I imagine that the name must be unique for a same application run, You know that better than me, but there is no name collision risk if two views with the same name are in a different directory?

I propose to send a PR with the number increment method.

**Comment by rynowak** [comment]
It would be nice to generate something recognizable IMO and not just an incrementing integer... But we also have to make sure the names are unique or else you get runtime errors... Should we do both?

**Comment by blowdart** [comment]
It cannot be predictable, otherwise we could have a planting attack. So an increment doesn't work. Nor will the view name.

You might be better bringing this up on the clr repo and ask them to improve performance.

**Comment by davidfowl** [comment]
Can we start with a random seed then increment?

**Comment by Yves57** [comment]
I was thinking about this problem, and I have found that the problem is maybe... in the Profiler:

Test 1: in the following image, I have changed the 'startTimestamp' line to be sure it to make as fast as possible.
![image](https://cloud.githubusercontent.com/assets/11701094/17076999/7594a146-50c1-11e6-8975-accae95ebe8b.png)
We see that the  'startTimestamp' line does not take significant time and that `Path.GetRandomFileName()` takes the famous 4.7%.

Test 2: in this second image, I have changed the 'startTimestamp' line and replaced the `GetRandomFileName()` by the number increment.
![image](https://cloud.githubusercontent.com/assets/11701094/17077016/da4c6862-50c1-11e6-891f-cf57366ae262.png)
And now it is the 'startTimestamp' line that takes 4.7%.

Test 3: To confirm that it is not a problem with `GetRandomFileName()`I have created a little console application that calls one million times `Path.GetRandomFileName()`. Time to run: 320ms.

And in all cases the `Compile()` method inclusive percentage remains more or less the same. I don't reproduce the first 49.6% performance improvement.

Bonus test: several lines in comments.
![image](https://cloud.githubusercontent.com/assets/11701094/17077104/60f6c5cc-50c4-11e6-83f1-65e1996def45.png)

If someone understands something...

**Comment by rynowak** [comment]
You're using a sampling profiler, which is statistical in nature. If you need really precise data then you need to run through a lot of iterations.

Also depending on how the profiler measures time (CPU time vs Thread Time) your measurements can be thrown off by GC if you hit a long pause while that method is on the stack.

**Comment by rynowak** [comment]
I had a chance to speak with @blowdart about this - the concern is that if we use predictable names, an assembly somewhere on the system could conflict and take precedence (like in the GAC). 

However, we're using the `LoadStream` method to load the compiled assembly, so we're not sure that there's a risk here. We need to confirm that `LoadStream` will ignore names/load paths to really know.

**Comment by Eilon** [comment]
@ryanbrandenburg we'll need to do some more profiling here and make sure we narrow down the exact problem.

Please consult with @rynowak .

**Comment by ryanbrandenburg** [comment]
I profiled this and consulted with @rynowak, we didn't see any evidence that `Path.GetRandomFileName()` was taking an inordinate amount of time, the big time spenders in there appear to be the IO methods like Emit and ParseText, while `Path.GetRandomFileName` didn't even run long enough to have had a sample taken. It was likely a statistical fluke that `Path.GetRandomFileName` showed as a hotpath for you, so I'm closing this one out.
