### ISSUE TITLE
Calling ToString on a UrlResolutionTagHelper resolved attribute value does not retrieve the value.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#5067]
For instance if you create a TagHelper that runs after UrlResolutionTagHelper and do this in the Process method:
```C#
var value = output.Attributes["src"].Value.ToString();
```
value ends up being equal to the ToString'd version of [this](https://github.com/aspnet/Mvc/blob/49a48a0a3352135b38a373c7d7a9cbbdc9ee97bf/src/Microsoft.AspNetCore.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs#L347) type name.

I believe for all other attributes that Mvc TagHelpers generate you can call Value.ToString() to retrieve the corresponding value. For instances when a user does not have a custom encoder having the ToString method return a defaultly encoded Url would be consistent/nice.

**Comment by dougbu** [comment]
Why does your code use `ToString()` without checking whether `Value is IHtmlContent`? Why is this question specific to `UrlResolutionTagHelper`?

I don't believe we've made any guarantees about `Attributes["name"].Value` stronger than it is mostly an `IHtmlContent` implementation or a `string`. And generally i.e. with the exception of `HtmlString` (for legacy reasons), `StringBuilder` and most value types, `ToString()` returns information useful only in the debugger.

**Comment by NTaylorMullen** [comment]
We haven't made any guarantees but currently this is the only API with this inconsistency. I ran into this while prepping for a talk and it took a bit of investigation to figure out why things weren't working. 

Another alternative for this would be to add a nice extension method to `TagHelperAttribute` to get a string value. It could do the `IHtmlContent` checking for users..

**Comment by Eilon** [comment]
What's the scenario here? Prepping a talk doesn't count for much 😄 

Also, what are negative consequences to "fixing" this? Would we be encouraging bad programming in some manner?

**Comment by NTaylorMullen** [comment]
The scenario is writing a TagHelper that wants to consume the output of the `UrlResolutionTagHelper`. In my example I was writing a TypeScript TagHelper that inspected the outputs src attribute. I was trying to let the UrlResolutionTagHelper do its magic without me having to manually resolve the ~/ at the beginning of the Url. Turns out to do that I need to do all the magic of checking what the attribute value "might" be, IHtmlContent vs string vs. another object.

`ToString`ing may encourage bad programming since other TagHelper developers may put non-tostringable values into TagHelperAttribute's (completely doable and we don't have guidance). Leaning towards my [other comment](https://github.com/aspnet/Mvc/issues/5067#issuecomment-234794289) to add an API to extract TagHelperAttribute values as strings. If we wanted to go down that path this issue would then become a Razor one.

**Comment by dougbu** [comment]
@NTaylorMullen the "inspection" aspect of this scenario seems suspect. Why "consume the output" of another tag helper?

In any case, any API that assumes it's appropriate to use a fixed HTML encoder or that ignores the inefficiency of creating a `string` unless absolutely necessary sounds worse than the "bad programming" of layering additional semantics on top of `ToString()`.

**Comment by NTaylorMullen** [comment]
Hu?

> Why "consume the output" of another tag helper?

TagHelpers are additive in nature; multiple can run on a single element. Part of that is communicating between TagHelpers on a single element (a supported scenario). Why do the work of another TagHelper if it's already running? We currently have `IUrlHelperFactory` instances injected into a few MVC TagHelpers that duplicate work already done because as a framework we can't guarantee that the `UrlResolutionTagHelper` hasn't been removed from the page. As the application developer you know if you've removed it or if you haven't. Therefore, given the choice it'd be better not do the url resolution work twice.



> In any case, any API that assumes it's appropriate to use a fixed HTML encoder or that ignores the inefficiency of creating a string unless absolutely necessary sounds worse than the "bad programming" of layering additional semantics on top of ToString().

We could provide an API that optionally accepts an encoder. As for inefficiently creating a string, you do even more work to duplicate the url resoution that was already done for you. Again, it'd be nice to enable an alternative for application developers to retrieve a `TagHelperAttribute`s value but more importantly support multiple `TagHelper`s working together better.

**Comment by dougbu** [comment]
We created a `TagHelperAttribute` which avoids the implication that attribute values are simple `string`s. Your API suggestion moves away from that, which is not a positive step.

On the original idea, we have numerous `IHtmlContent` implementations and only `HtmlString` overrides `ToString()`. Note a few have `[DebuggerDisplay]` attributes for help when debugging.

The general guidance is "consuming" tag helpers should treat `TagHelperAttribute.Value` as `string`, `IHtmlContent` or (rarely but possible) some `object` to `ToString()`. The `UrlResolutionTagHelper` does this just fine (despite ignoring the `object` possibility).

Your tag helper does not need to repeat `UrlResolutionTagHelper`'s logic. It can work as the `<link>` and `<script>` tag helpers do, subclassing `UrlResolutionTagHelper` and using its methods. Or your helper can handle expected `TagHelperAttribute.Value` types correctly itself.

**Comment by NTaylorMullen** [comment]
> We created a TagHelperAttribute which avoids the implication that attribute values are simple strings. Your API suggestion moves away from that, which is not a positive step.

My API suggestion enables users to consume the `TagHelperAttribute`'s `Value` as a `string` which is the most common way to do consume it. It doesn't change the fact that the Value would still be an object, it'd just be an extension method like `TagHelperAttribute.GetValueAsString()`.

> Your tag helper does not need to repeat UrlResolutionTagHelper's logic. It can work as the <link> and <script> tag helpers do, subclassing UrlResolutionTagHelper and using its methods. Or your helper can handle expected TagHelperAttribute.Value types correctly itself.

That duplicates the logic and runs the code a second time at runtime. Not to mention it's extra code that I'd rather not have to worry about since the work is already being done by another `TagHelper` in the system.




> The general guidance is "consuming" tag helpers should treat TagHelperAttribute.Value as string, IHtmlContent or (rarely but possible) some object to ToString(). The UrlResolutionTagHelper does this just fine (despite ignoring the object possibility).

The `TagHelperAttribute.GetValueAsString()` can embody this guidance.

**Comment by dougbu** [comment]
> The `TagHelperAttribute.GetValueAsString()` can embody this guidance.

Converting an often-multipart container into a simple `string` cannot embody the guidance. Note for example that the `UrlResolutionTagHelper` creates different `TagHelperAttribute`s depending on `Value`'s original type.

**Comment by NTaylorMullen** [comment]
Lets talk offline with @Eilon

**Comment by Eilon** [comment]
@dougbu @NTaylorMullen did we decide something on this? I don't remember if we actually met 😄

**Comment by dougbu** [comment]
Think we had a couple of offline conversations but no formal meeting.

My feeling is calling `ToString()` on an `IHtmlContent` implementation is simply a bug and we shouldn't do anything to encourage that. (I recently fixed this type of bug in the `object` HTML template.) I would also discourage an extension method like `GetValueAsString()` because it would send the wrong message about what an `IHtmlContent` is for and (in most cases) hide `StringBuilder` allocations and bury the `HtmlEncoder` choice.

For `TagHelperAttribute.Value` in particular, my recommendation is to keep the consuming code explicit for the reasons above and because `string`, `IHtmlContent` and `object` often need different special cases in different contexts. MVC examines these values in a couple of places and the requirements are different for each.

**Comment by Eilon** [comment]
Closing because there's no customer request for this. I actually could see us providing such a utility method in the future, even though there are perf issues with it. Most scenarios don't require a lot of performance. And the strings being created here aren't necessarily very large either. I'd guess they're generally *not*. And yet code written using such an API would likely look very clean and have better maintainability.

But not today 😄
