### ISSUE TITLE
Tag Helper in TemplateEditor doesn't bind depending on TemplateEditor's location

### ISSUE THREAD

**Issue by rjpaulsen** [aspnet/Mvc#5068]
I'm using areas to divide up my application and everything works as expected, including an EditorTemplate -- but only if the editor template in a certain location.  My Project works when it is setup like this (note the location of MyEditor.cshtml):

    \Areas\Area1\Controllers\TestController.cs
    \Areas\Area1\Views\Test\Index.cshtml
    \Areas\Area1\Views\Shared\EditorTemplates\MyEditor.cshtml

I am using an EditorTemplate (`MyEditor.cshtml`) inside `MyViewIndex.cshtml` and it works fine when I put it in the location listed above.

I can then move `MyEditor.cshtml` to the following location where MVC finds it, but doesn't render the Tag Helpers (even though something like @DateTime.Now will render): 

    \Views\Shared\EditorTemplates\MyEditor.cshtml

So instead this Tag helper...

    <input asp-for="Hello1" type="text" />

...rendering like this:

    <input value="ABC" type="text" id="Hello1" name="Hello1" />

...it's output to the browser like it was never processed:

    <input asp-for="Hello1" type="text" />

Inside the view Index.cshtml I have:

    @Html.EditorFor(model => model.Hello1, "MyEditor")

Inside MyEditor.cshtml I have:

    Hello<br/>
    @DateTime.Now<br/>
    <input asp-for="OneEditorProperty1" type="text" />

I know it's finding the editor template because it outputs "Hello" and I know it's processing it to some degree because I see the DateTime.Now value. For some reason the Input Tag Helper doesn't get processed -- which is why I think it is a bug.

**Comment by dougbu** [comment]
Where are your `@addTagHelper` directives? You may for example have a `Areas\Area1\Views\_ViewImports.cshtml` but not a `Views\_ViewImports.cshtml` file.

**Comment by rjpaulsen** [comment]
Oh, man I hate it when the answer is under a title like "Introduction to Tag Helpers". Gracias.
