### ISSUE TITLE
Turn on PUT/DELETE verbs for MVC

### ISSUE THREAD

**Issue by chassq** [aspnet/Mvc#5069]
Just wondering how we go about making MVC honor PUT/DELETE HTTP verbs. I think at one time we had to uninstall WebDAV and change the web.config. Would that method still apply to Core on IIS Express? My code now uses POST just fine but just switching over to PUT (HttpPut attribute and setting method="put") causes the request to go to the HttpGet method.

Thanks!

**Comment by Eilon** [comment]
@chassq all HTTP verbs are supported by MVC. Can you show your code and show what doesn't work?

If you're using IIS and you have some IIS modules or settings that prevent ASP.NET Core from seeing those verbs, of course you'll need to change those settings 😄

**Comment by khellang** [comment]
Sounds like #5038?

**Comment by chassq** [comment]
Hey,

Included an attached zip with src but in short I simply created a new ASP NET Core web application and did the following:

1) Created a ViewModel with one public property
2) Create 3 action methods in a controller. Each had its own allowed verb attribure (HttpGet, HttpPut and HttpPost). Also added a route attribute for each action method all named the same (e.g. 'testme'). The ViewModel in the input parameter for the put and post action methods.
3) Created a single view that switched from a view of the post or put html form based on a number I passed in via the ViewBag.

When I first hit the testme url the HttpGet invokes as expected. I am initially presented with the Html Form I configured for PUT, which is correct. However, when I hit the put submit button it looks like all the parameters are all on the query string? I tried to use the FromForm attribute on the action method input param but got the same result. So I reconfigured my test by showing the post form initially instead of the put form. When I hit the post form submit button everything works as expected. I post right to the HttpPost configured action method.

Am I doing something wrong?

[WebApplication7.zip](https://github.com/aspnet/Mvc/files/381013/WebApplication7.zip)

**Comment by Eilon** [comment]
@javiercn can you take a look and see if it's related to https://github.com/aspnet/Mvc/issues/5038 ?

**Comment by javiercn** [comment]
Hi,

I tried with fiddler and it works fine for me, so I doubt its #5038. I tried to see what your repro is doing and it is sending a get request. I believe web browsers don't understand other verbs than get and post, so  given a put method, the browser defaults to get. See https://www.w3.org/TR/html401/interact/forms.html#h-17.13.1 for details

I don't think there is any work/issue here.

**Comment by chassq** [comment]
Ah, that must be it. 

Found this bug was being tracked ( https://www.w3.org/Bugs/Public/show_bug.cgi?id=10671 ) but is now flagged as resolved/wont fix.

I will close this issue.
