### ISSUE TITLE
Wrong JsonSerializationSettings behaviour.

### ISSUE THREAD

**Issue by maxim-boligatov** [aspnet/Mvc#5070]
In case of the following setup:

```C#
services.AddMvc()
        .AddJsonOptions(options =>
         {
             options.SerializerSettings.ContractResolver = new OutputJsonResolver();
             options.SerializerSettings.Converters.Add(new DataConverter());
         });
````
we will got the following errors:

**1) DataConverter (derived from JsonConverter) will not be called at all... never...**
I am trying to parse data sent to method of controller. It is used to provide some API for client side and JS sends JSON data with Content-Type: application/json. I need to instantiate custom object to pass it to controller as input parameter. In Web Api 2 it works very well.

**2) OutputJsonResolver is not called in some cases.**
if I will simply return data (for example some complex object with properties) from controller then OutputJsonResolver will be called and all will be processed correctly.

In case when I need to output custom IActionResult... for example OutputResult derived from JsonResult then OutputJsonResolver will not be called. And it looks OK because JsonResult requires JsonSerializerSettings in constructor... so by default it should not be related. 

Although, to achieve required behavior (where resolver will participate) I want to pass settings originally provided in AddJsonOptions call. So I used JsonSerializerSettingsProvider.CreateSerializerSettings()".. but it does not work... and it is clear why... if we will look at the code of [this method](https://github.com/aspnet/Mvc/blob/62803d5979b13e3dcd4929a04274a40cc242a449/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonSerializerSettingsProvider.cs)... it uses some defaults and not settings from MVC options.

OK, if I cannot change default settings then I want to change all formatters and setup all with my settings.

```C#
    public class SerializerSettingsSetup : IConfigureOptions<MvcOptions>
    {
        #region Constructors
        public SerializerSettingsSetup(ILoggerFactory loggerFactory, ArrayPool<char> charPool, ObjectPoolProvider objectPoolProvider)
        {
            this.loggerFactory = loggerFactory;
            this.charPool = charPool;
            this.objectPoolProvider = objectPoolProvider;
        }
        #endregion

        #region Fields
        private readonly ILoggerFactory loggerFactory;
        private readonly ArrayPool<char> charPool;
        private readonly ObjectPoolProvider objectPoolProvider;
        #endregion

        #region IConfigureOptions<MvcOptions> Members
        public void Configure(MvcOptions options)
        {
            JsonSerializerSettings inputSettings = JsonSerializerSettingsProvider.CreateSerializerSettings();
            JsonSerializerSettings outputSettings = JsonSerializerSettingsProvider.CreateSerializerSettings();

            inputSettings.Converters.Add(new DataConverter());

            inputSettings.ContractResolver = new InputJsonResolver();
            outputSettings.ContractResolver = new OutputJsonResolver();

            var jsonInputLogger = this.loggerFactory.CreateLogger<JsonInputFormatter>();
            var jsonInputPatchLogger = this.loggerFactory.CreateLogger<JsonPatchInputFormatter>();

            options.InputFormatters.RemoveType<JsonInputFormatter>();
            options.InputFormatters.RemoveType<JsonPatchInputFormatter>();
            options.OutputFormatters.RemoveType<JsonOutputFormatter>();

            options.InputFormatters.Add(new JsonInputFormatter(jsonInputLogger, inputSettings, this.charPool, this.objectPoolProvider));
            options.InputFormatters.Add(new JsonPatchInputFormatter(jsonInputPatchLogger, inputSettings, this.charPool, this.objectPoolProvider));
            options.OutputFormatters.Add(new JsonOutputFormatter(outputSettings, this.charPool));
        }
        #endregion
    }
```

Configure method will be called during application startup (transient was added correctly and after AddMvc) but it is still not possible to get working converters and resolvers.

**Summary**: we cannot create / get json settings for each formatter separately. We even cannot do that for input / output separately. And even in case when we try to setup it only once for whole application it still does not work as expected.

So current ASP.Net Core serialization behavior is acceptable for "Hello World" app. But it is absolutely not acceptable  for real life application. This issue is one of critical features which does not allow me to move my projects from Web API 2 or NancyFX to ASP.Net Core.

**Comment by maxim-boligatov** [comment]
I guess I have figured out at least some of above questions.
I got converter code working (DataConverter : JsonConverter) when I used [FromBody] attribute.
It looks in comparison to Web Api 2 that attribute is mandatory in ASP.Net Core.

But issues related to JsonSerializerSettingsProvider, settings in JsonResult and different formatters settings are still actual but not so critical.. I think I can add this attribute everywhere in "API" controllers.

**Comment by Eilon** [comment]
@kichalla can you investigate?

**Comment by kichalla** [comment]
If you are trying to access the json options (that you had setup in Startup.cs) in your controller, you can inject the service `IOptions<MvcJsonOptions>`.

But note that you must never change these settings on a per-request basis because these options are applied globally..i.e they would effect all requests to all controllers.

An example of how you can supply serializer settings to JsonResult is below:
https://github.com/aspnet/Mvc/blob/1.0.0/test/WebSites/BasicWebSite/Controllers/JsonResultController.cs#L33
Note that I mention the example above as caching(i.e settings are `static`) the contract resolver is important from performance perspective.

If this is not answering your question, probably I am missing something. Could you provide a small repro code of the issue in that case?

**Comment by maxim-boligatov** [comment]
In your example for JsonResult json settings are obtained from
 _customSerializerSettings = JsonSerializerSettingsProvider.CreateSerializerSettings();

How can I obtain here settings used application-wide (provided in Startup.cs)?

It looks really reasonable to have something like: 
 _customSerializerSettings = JsonSerializerSettingsProvider.GetGobalSettings();
 _customSerializerSettings = JsonSerializerSettingsProvider.CopyGobalSettings();

So we have 3 cases of usage JsonSerializerSettingsProvider:
1) Use JsonSerializerSettingsProvider.CreateSerializerSettings() to create new app-default settings (like it is now).
2) Use JsonSerializerSettingsProvider.GetGobalSettings() to reference original settings provided in Startup. You said global settings are used everywhere. But it is not correct for JsonResult it will always use own settings. And I want to make my descendant of JsonResult to be dependent on global settings.
3) Use JsonSerializerSettingsProvider.CopyGobalSettings() to create copy of global settings and override only required options.

I guess now it is not necessary to provide any demo code and your sample code is enough to discuss original question. But if you still need some code let me know.

**Comment by kichalla** [comment]
> How can I obtain here settings used application-wide (provided in Startup.cs)?

You can inject `IOptions<MvcJsonOptions> options` into your controller. It is these settings I was referring to about not modifying on a per-request basis.

> Use JsonSerializerSettingsProvider.GetGobalSettings() to reference original settings provided in Startup. You said global settings are used everywhere. But it is not correct for JsonResult it will always use own settings. And I want to make my descendant of JsonResult to be dependent on global settings.

This is not correct. JsonResult, if used without constructor taking in settings, uses the settings from the global MvcJsonOptions.

**Comment by maxim-boligatov** [comment]
> This is not correct. JsonResult, if used without constructor taking in settings, uses the settings from the global MvcJsonOptions. 

OK, it sounds correct BUT it is not exactly so... to be honest JsonResult will not use any global settings. If I understand source code correctly JsonResult will not provide own settings in case of default constructor (with value only). So since settings property is not initialized - default settings will be used during serialization.

But it makes a significant troubles for classes derived from JsonResult.
If I understand right to consider app-wide json settings I have to inject `IOptions<MvcJsonOptions>` to controller, manually copy all existing settings to new settings instance, pass it to instance of MyJsonResult (derived from JsonResult), update settings inside for it's own purposes and output this result from controller method.

It looks a bit overkill...
I still think we should allow cloning of app-wide json settings from any point of application or at least from such classes like JsonResult.
Of course if it breaks original conception I can do it only for my solution (I even can do it inside configuration as some trick without injecting to constructor). But there is obviously a disadvantage in this conception...

**Comment by rynowak** [comment]
> OK, it sounds correct BUT it is not exactly so... to be honest JsonResult will not use any global settings. If I understand source code correctly JsonResult will not provide own settings in case of default constructor (with value only). So since settings property is not initialized - default settings will be used during serialization.

This is what JsonResult does - you can provide your own settings if you want, but by default it uses the settings from `MvcJsonOptions` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/JsonResultExecutor.cs#L118

> But it makes a significant troubles for classes derived from JsonResult.

Can I ask why you need to make a derived class of JsonResult? Is there an enhancement we should make that would remove your need to do this?

> I still think we should allow cloning of app-wide json settings from any point of application or at least from such classes like JsonResult.

If you really want something like this you can easily build it yourself, but you're opting out of DI.

```
public static class GlobalSettings
{
    public SerializerSettings Default  { get; set; }

    public SerializerSettings CreateCopy() { ... }
}

...

public void Configure(IApplicationBuilder app, IOptions<MvcJsonOptions> json)
{
    GlobalSettings.Default = json.Value.SerializerSettings;
}
```

The alternative (if you need a custom JsonResult class) would be to register an 'executor' service which is responsible for actually writing the output. Then you don't need to inject options everywhere it's used. This is the best pattern we were able to come up with mixing DI + user-creatable action results.

If you can tell us more about what you need to accomplish we can try to help.

**Comment by maxim-boligatov** [comment]
> This is what JsonResult does - you can provide your own settings if you want, but by default it uses the settings from MvcJsonOptions https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/JsonResultExecutor.cs#L118

Yes, it is exactly what is mentioned in my previous post. And this makes troubles since I cannot get this default settings in easy way.

> If you really want something like this you can easily build it yourself, but you're opting out of DI.

> public static class GlobalSettings
> {
>     public SerializerSettings Default  { get; set; }
> 
>     public SerializerSettings CreateCopy() { ... }
> }

Yes something like this and of course I can create some service to handle settings creation/cloning and register this service on startup. But I thought that JsonSerializerSettingsProvider can be such service.

For now as you mentioned (and some guys in this thread) to meet DI requirements I have 2 options:
1) Inject in controller mvc options to create copy of app json settings and pass it to MyJsonResult.
2) Create own executor (maybe derived) and register it to process my json result (desired json settings will be prepared inside).

Either of them really looks a bit complicated...
When I am able to derive from JsonResult I should be able to use logic on which it is based.
It is not very good to get desired behavior by controlling execution of result and not result itself.
But in any case it is acceptable solutions. Just more code in comparison to MVC5.

> Can I ask why you need to make a derived class of JsonResult? Is there an enhancement we should make that would remove your need to do this?

I need custom data transformation. I must control how data serialized, what should be serialized and what not... For example I control serialization of custom global unique identifiers... I do not allow to serialize anything except permitted interfaces and so on... So I simply want flexible way to control serialization settings.

**Comment by kichalla** [comment]
> Yes something like this and of course I can create some service to handle settings creation/cloning and register this service on startup. But I thought that JsonSerializerSettingsProvider can be such service.

I am not even sure if cloning of settings is a safe thing to do. For example, what does it mean to clone the ContractResolver (which maintains a cache). This would be a question for Json.net.

> Create own executor (maybe derived) and register it to process my json result (desired json settings will be prepared inside).

I am not sure if you need to go that far. Following is an example that I tried now. Of course, if you made any changes to JsonOptions in Startup.cs it wouldn't show up here, but as @rynowak mentioned you could maintain your own helper to build up the custom settings and apply it in Startup and as well as use in the custom result.

```
   public class MyJsonResult : JsonResult
    {
        private static readonly JsonSerializerSettings _serializerSettings;
        private readonly object _value;

        static MyJsonResult()
        {
            _serializerSettings = // get settings from the helper
        }

        public MyJsonResult(object value)
            : base(value, _serializerSettings)
        {
            _value = value;
        }

        public override Task ExecuteResultAsync(ActionContext context)
        {
            var wrappedValue = new MyWrapperClass() { ActualValue = _value };
            this.Value = wrappedValue;

            return base.ExecuteResultAsync(context);
        }
    }

    public class MyWrapperClass
    {
        public object ActualValue { get; set; }
    }
```

**Comment by maxim-boligatov** [comment]
> For example, what does it mean to clone the ContractResolver (which maintains a cache).    

It will be shallow copy of json settings. So cache will not be a problem..
After cloning I want to get new settings instance but with the same instance of ContractResolver.
So it is simply shallow copy... And if I want to add own resolver I will do that in this copy without impact on original settings.

>  _serializerSettings = // get settings from the helper

I want to get access to original settings here^. I do not need even wrapper. I can do desired transformation on JSON serialization level (with data converter or contract resolver). So I want to get original settings, create its shallow copy, apply custom options for example custom JsonConverter to this copy. And all of that should be in MyJsonResult. Exactly here:

>// get settings from the helper

And as it was mentioned previously we have only 2 ways for now to get original settings:
>1) Inject in controller mvc options to create copy of app json settings and pass it to MyJsonResult.
>2) Create own executor (maybe derived) and register it to process my json result (desired json settings will be prepared inside)... 

Because for now I cannot prepare such settings in JsonResult.
We do not have service allowing me to reference original json settings (from startup) or create new settings based on that instance. JsonSerializerSettingsProvider is not a service.. it is just static class with very simple factory method, which creates always new _default_ instance and _not based_ on MvcOptions.

**Comment by dougbu** [comment]
Reminders: Never `new` up `JsonSerializerSettings` in an MVC app. Instead call `JsonSerializerSettingsProvider.CreateSerializerSettings()` and make any customization from that starting point. And, of course, use or customize the instance in `MvcJsonOptions` unless you need a _different_ instance for some purpose.

It's still not clear to me why the original `AddJsonOptions(options => { ... })` isn't working perfectly. Have we figured that out?

**Comment by maxim-boligatov** [comment]
dougbu, please read carefully whole thread... I do not know how to reply for your question... all information is present in above messages... And I never mentioned direct settings creation!

**Comment by dougbu** [comment]
> I never mentioned direct settings creation!

That was a reminder only.

> I do not know how to reply for your question... all information is present in above messages

I've read the thread and see your description of the symptoms. But I don't see _why_ the changes you made in the `AddJsonOptions()` call aren't honoured. Really a question for @kichalla.

**Comment by kichalla** [comment]
```c#

// Create a DI service which has your custom settings
public sealed class LegacyAppJsonSerializerSettings
{
    private readonly JsonSerializerSettings _serializerSettings;

    public LegacyAppJsonSerializerSettings(IOptions<MvcJsonOptions> mvcJsonOptions)
    {
        var globalSerializerSettings = mvcJsonOptions.Value.SerializerSettings;

        // TODO: create a copy of the above globalSerializerSettings and set it to _serializerSettings
    }

    public JsonSerializerSettings GetSettings()
    {
        return _serializerSettings;
    }
}

// Creating this as a singleton so that the contract resolver is cached
services.AddSingleton<LegacyAppJsonSerializerSettings>();

// Injecting into an action directly
[HttpGet]
public IActionResult ActionWithSpecificJsonSettings([FromServices] LegacyAppJsonSerializerSettings jsonSerializerSettings)
{
    return Json(
        new Product { Id = Guid.NewGuid(), Name = "iPhone 6s" },
        jsonSerializerSettings.GetSettings());
}

// injecting into a controller
public class Test1Controller : Controller
{
    private readonly JsonSerializerSettings _serializerSettings;

    public Test1Controller(LegacyAppJsonSerializerSettings jsonSerializerSettings)
    {
        _serializerSettings = jsonSerializerSettings.GetSettings();
    }
```

**Comment by kichalla** [comment]
```c#
// Create a DI service which has your custom settings
public sealed class MyCustomJsonSerializerSettings
{
    private readonly JsonSerializerSettings _globalSerializerSettings;

    public MyCustomJsonSerializerSettings(IOptions<MvcJsonOptions> mvcJsonOptions)
    {
        _globalSerializerSettings = mvcJsonOptions.Value.SerializerSettings;
    }

    public JsonSerializerSettings GetSettings()
    {
        var serializerSettings = new JsonSerializerSettings();

        serializerSettings.MissingMemberHandling = _globalSerializerSettings.MissingMemberHandling;
        serializerSettings.MaxDepth = _globalSerializerSettings.MaxDepth;
        serializerSettings.TypeNameHandling = _globalSerializerSettings.TypeNameHandling;

        // copy other properties...

        return serializerSettings;
    }
}

// Creating this as a singleton so that the contract resolver is cached
services.AddSingleton<MyCustomJsonSerializerSettings>();

// Injecting into an action directly
[HttpGet]
public IActionResult ActionWithSpecificJsonSettings([FromServices] MyCustomJsonSerializerSettings jsonSerializerSettings)
{
    return Json(
        new Product { Id = Guid.NewGuid(), Name = "iPhone 6s" },
        jsonSerializerSettings.GetSettings());
}

// injecting into a controller
public class Test1Controller : Controller
{
    private readonly JsonSerializerSettings _serializerSettings;

    public Test1Controller(MyCustomJsonSerializerSettings jsonSerializerSettings)
    {
        _serializerSettings = jsonSerializerSettings.GetSettings();
    }
```

**Comment by kichalla** [comment]
Closing this issue now as there are already ways to achieve the scenario being asked for here.
