### ISSUE TITLE
 can we get IUrlHelper in Startup.ConfigureServices ?

### ISSUE THREAD

**Issue by omuleanu** [aspnet/Mvc#5071]
I need to set `context.DisplayMetadata.AdditionalValues` with a value generated by `IUrlHelper`, so I think I need something like this: 
```
public void ConfigureServices(IServiceCollection services)
{
    var urlhelper = GetUrlHeper(); // pseudo code
    var provider = new MyDisplayMetadataProvider(urlhelper); // IDisplayMetadataProvider        

    services.AddMvc(o =>
    {
        o.ModelMetadataDetailsProviders.Add(provider);
    });
    ...
}
```
is this possible now ?

**Comment by Eilon** [comment]
@rynowak any thoughts/tips/tricks on this?

**Comment by dougbu** [comment]
@omuleanu LGTM. Did you file this issue because you hit a problem?

**Comment by dougbu** [comment]
Oh, wait. Get the `IUrlHelperFactory` and grab the `IUrlHelper` per-request.

**Comment by davidfowl** [comment]
@omuleanu You need to register an `IConfigureOptions<MvcOptions>` to get access to services when building up options:

```C#
public class MyConfigureMvcOptions : IConfigureOptions<MvcOptions>
{
    private readonly IUrlHelperFactory _urlHelperFactory;
    public MyConfigureMvcOptions(IUrlHelperFactory urlHelperFactory)
    {
        _urlHelperFactory = urlHelperFactory;
    }

    public void Configure(MvcOptions options)
    {
        var provider = new MyDisplayMetadataProvider(_urlHelperFactory); // IDisplayMetadataProvider        
        options.ModelMetadataDetailsProviders.Add(provider);
    }
}
```

**Comment by omuleanu** [comment]
@davidfowl how do I register `MyConfigureMvcOptions` ? 
I presume should be something like `services.AddMvc().AddOption<My ..`. ?

**Comment by davidfowl** [comment]
I updated my sample showing how

**Comment by omuleanu** [comment]
Thank You,
would it also be possible to get the urlHelper in the Startup.ConfigureServices
something like this;
```
public void ConfigureServices(IServiceCollection services)
{
    var urlhelper = GetUrlHeper(); // pseudo code
    var provider = new MyDisplayMetadataProvider();
    provider.Add("key1", url.Action(... // adds the value to a static field
    provider.Add("key2", url.Action(...
    provider.Add("key3", url.Action(...
```
basically this would let me calculate all the needed urls in advance at startup

**Comment by davidfowl** [comment]
The URL helper requires an `HttpContext`, that's not available at `Startup`

**Comment by omuleanu** [comment]
I'm trying to set `DisplayMetadata.AdditionalValues` with values returned by urlhelper, and it seems to me that this isn't possible,
I can pass the `IUrlHelperFactory` to the `MyDisplayMetadataProvider` via constructor, but in
```
public void CreateDisplayMetadata(DisplayMetadataProviderContext context) 
{
      var url = urlHelperFactory.GetUrlHelper
```
I don't have the ActionContext to pass to the `urlHelperFactory.GetUrlHelper`

**Comment by dougbu** [comment]
`AdditionalValues` is not appropriate for values which are created for a specific request. For example you could generate URLs containing `localhost` and use them responding to a request from another machine.

More generally `ModelMetadata` contains only static information about a specific `Type`.

Recommend creating a new service implementing an `interface` with methods that accept a `ViewContext`, `ActionContext` or `HttpContext` (whichever you need). This service could be instantiated with an `IUrlHelperFactory` if necessary.

**Comment by omuleanu** [comment]
in mvc5 I was using `url.Action` in an `IMetadataAware` attribute, so I was trying to do same thing here,

but I can get around the limitation by passing the parameters (controller, action), and letting the html helper in the view call url.Action
