### ISSUE TITLE
Route, template and querystring

### ISSUE THREAD

**Issue by cherici-simone** [aspnet/Mvc#5073]
We've migrate our web api project from RC1 to core 1 and we notice a couple of strange behavior. The "worst" one is that it seems that when using wildcard as last parameter in the route template the querystring version of the http call doe not work. Here is an example (the controller name is SpaceController).

The action:
**_[HttpGet("Details/{*fullPath}")]
public async Task<IActionResult> GetSpaceDetails(string fullPath)_**

**<= RC1:**
- https://localhost:44310/api/Space/Details/Test --> **OK**
- https://localhost:44310/api/Space/Details?fullPath=%2FTest -->**OK**

**Core 1**
- https://localhost:44310/api/Space/Details/Test --> **OK**
- https://localhost:44310/api/Space/Details?fullPath=%2FTest -->**KO**

In core 1 the result of a call with the url that use the querystring is that variable **fullPath** is null.

Another strange behavior (that in RC1 work correctly) is that when using default value as parameter value in action the parameter is always null. For example (the controller name is SpacesController):

**_[HttpGet("{*SpacePath}")]
public async Task<IActionResult> GetTree(string SpacePath = "/")_**

In this case in the call to https://localhost:44310/api/Spaces **SpacePath** parameter doesn't take the default value and is always null

**Comment by Eilon** [comment]
@javiercn can you take a look? I have this sneaking suspicion that at least part of this is by design, e.g. due to the ordering of value providers in model binding. But I'm not sure, especially about the second part of the report.

**Comment by javiercn** [comment]
Will do

**Comment by javiercn** [comment]
I've tried the following and everything works.
Products/Bread/Glutten/Free gives back Bread/Glutten/Free
If you use [FromQuery] as you see below, you can also do Products?fullPath=Glutten/Free
If you don't specify anything, the default value is used and the result is "something".

```C#
        [HttpGet("Products/{*fullPath}")]
        public IActionResult Products([FromQuery] string fullPath = "something")
        {
            return Content(fullPath);
        }
```

**Comment by javiercn** [comment]
If this is still happening to you, can you provide a small repro project?

**Comment by ingAlfano** [comment]
Hi I am writing on behalf of simone.

I've tried the following:
```
[Route("api/[controller]")]
public class PathController : Controller
{
    [HttpGet("{*fullPath}")]
    public async Task<IActionResult> Get([FromQuery] string fullPath = "something")
    {
        return Ok(fullPath);
    }
}
```

api/Path?fullPath='foo'      returns "foo"
api/Path/foo                      returns  "something" (default value)

when removing  [FromQuery]
```
[Route("api/[controller]")]
public class PathController : Controller
{
    [HttpGet("{*fullPath}")]
    public async Task<IActionResult> Get(string fullPath = "something")
    {
        return Ok(fullPath);
    }
}
```
api/Path?fullPath='foo'      returns null
api/Path/foo                      returns  foo

Thank you for your help

**Comment by javiercn** [comment]
Whats happening here is that the route value data provider provides the empty string when queried about full path and that takes priority over the query string parameter value. This has been the behavior in past versions of MVC and we decided to make it the same in ASP.NET MVC Core for backward compatibility reasons.

**Comment by ingAlfano** [comment]
This seems to me a braking change from betaX/rcX to 1.0, we based part of our javascript code on this "feature" at our risk and we can accept it.
How about the default value overriding? Is this also by design? (please refer to my edit above)

Thanks
Alessandro

**Comment by Eilon** [comment]
@ingAlfano the main reason we changed it was that it was always a mistake that we just didn't realize, and we didn't want to break compat with previous versions of MVC (1 - 5).

You can change the order of the value providers in MVC's options if you require a different order.
