### ISSUE TITLE
TryUpdateModelAsync is not binding with a collection model

### ISSUE THREAD

**Issue by branciat** [aspnet/Mvc#5075]
Hi,

When i use TryUpdateModelAsync on the whole collection objects, the properties values for each entity are updated but without using the binding.

Here the code that i wrote with 3 case Single, Collection, Collection update with prefix on each entity.

Controller
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplicationBasic.Controllers
{
    public class HomeController : Controller
    {
        WebApplicationBasicContext _db;
        public HomeController(WebApplicationBasicContext _ctx)
        { _db = _ctx; }

        public IActionResult Single()
        {
            TestModel test = _db.TestModel.First();
            return View(test);
        }

        public IActionResult Collection()
        {
            List<TestModel> test = _db.TestModel.ToList();
            return View(test);
        }

        public IActionResult CollectionWithPrefix()
        {
            List<TestModel> test = _db.TestModel.ToList();
            return View("Collection", test);
        }

        [HttpPost]
        public IActionResult Single([FromForm] TestModel model)
        {
            System.Console.WriteLine("*** SINGLE VERSION ***");
            TestModel original = _db.TestModel.Single(f => f.Id == model.Id);
            System.Console.WriteLine("model original");
            ShowEntityProperties(original);                
            System.Console.WriteLine("model request");
            ShowEntityProperties(model);                
            System.Console.WriteLine("try update model on original");
            TryUpdateModelAsync(original);
            System.Console.WriteLine("model original after try update model");
            ShowEntityProperties(original);                
            
            return new OkResult();
        }

        [HttpPost]
        public IActionResult Collection([FromForm] List<TestModel> model)
        {
            System.Console.WriteLine("*** COLLECTION VERSION ***");
            int[] ids = model.Select(f => f.Id).ToArray();
            List<TestModel> origins = _db.TestModel.Where(f => ids.Contains(f.Id)).ToList();
            System.Console.WriteLine("model origin");
            foreach (TestModel original in origins)
            {
                ShowEntityProperties(original);                
            }
            System.Console.WriteLine("model request");
            foreach (TestModel mod in model)
            {
                ShowEntityProperties(mod);                
            }
            System.Console.WriteLine("try update model on the whole collection");
            TryUpdateModelAsync(origins);
            foreach (TestModel original in origins)
            {
                System.Console.WriteLine("model original after try update model");
                ShowEntityProperties(original);                
            }
            return new OkResult();
        }

        [HttpPost]
        public IActionResult CollectionWithPrefix([FromForm] List<TestModel> model)
        {
            System.Console.WriteLine("*** COLLECTION WITH PREFIX VERSION ***");
            int[] ids = model.Select(f => f.Id).ToArray();
            List<TestModel> origins = _db.TestModel.Where(f => ids.Contains(f.Id)).ToList();
            System.Console.WriteLine("model origin");
            foreach (TestModel original in origins)
            {
                ShowEntityProperties(original);                
            }
            System.Console.WriteLine("model request");
            foreach (TestModel mod in model)
            {
                ShowEntityProperties(mod);                
            }
            for(int i = 0; i < origins.Count; i++)
            {
                System.Console.WriteLine("try update model for each entity with prefix");
                var up = TryUpdateModelAsync(origins[i], $"[{i}]");
                System.Console.WriteLine("model original after update");
                ShowEntityProperties(origins[i]);                
            }
            return new OkResult();
        }

        protected void ShowEntityProperties(object entity)
        {
            PropertyInfo[] props = entity.GetType().GetProperties();
            foreach (PropertyInfo propInfo in props)
            {
                System.Console.WriteLine(propInfo.Name + " : " + propInfo.GetValue(entity));
            }
        }        
    }
}

```
View Single
```
@model TestModel

@using(Html.BeginForm()){
    @Html.HiddenFor(m => m.Id)
    @Html.EditorFor(m => m.PropA)
<input type="submit"/>
}
```
View Collection
```
@model List<WebApplicationBasic.TestModel>

@using(Html.BeginForm()){
    @for(int i = 0; i < Model.Count; i++)
    {
        @Html.HiddenFor(m => Model[i].Id)
        @Html.EditorFor(m => Model[i].PropA)
    }
<input type="submit"/>
}
```
The model

```
using Microsoft.AspNetCore.Mvc;

namespace WebApplicationBasic
{
    [Bind("Id", "PropA")]
    public class TestModel
    {
        public int Id {get;set;}
        public string PropA {get;set;}
        public string PropB {get;set;}
        public string PropC {get;set;}
    }    
}
```

And below the output to single
*** SINGLE VERSION ***
model original
Id : 1
PropA : A1
PropB : B1
PropC : C1
model request
Id : 1
PropA : test
PropB : 
PropC : 
try update model on original
model original after try update model
Id : 1
PropA : test
PropB : B1
PropC : C1

All is fine as expected

Next the ouput to collection

*** COLLECTION VERSION ***
model origin
Id : 1
PropA : A1
PropB : B1
PropC : C1
Id : 2
PropA : A2
PropB : B2
PropC : C2
Id : 3
PropA : A3
PropB : B3
PropC : C3
model request
Id : 1
PropA : test 1
PropB : 
PropC : 
Id : 2
PropA : test 2
PropB : 
PropC : 
Id : 3
PropA : test 3
PropB : 
PropC : 
try update model on the whole collection
model original after try update model
Id : 1
PropA : test 1
PropB : 
PropC : 
model original after try update model
Id : 2
PropA : test 2
PropB : 
PropC : 
model original after try update model
Id : 3
PropA : test 3
PropB : 
PropC : 

Here the property "PropA" for each object is correctly updated, but the values of 2 others properties are lost !!! The entites were not binding.

Here the collection with update on each object using prefix version
*** COLLECTION WITH PREFIX VERSION ***
model origin
Id : 1
PropA : A1
PropB : B1
PropC : C1
Id : 2
PropA : A2
PropB : B2
PropC : C2
Id : 3
PropA : A3
PropB : B3
PropC : C3
model request
Id : 1
PropA : prefix 1
PropB : 
PropC : 
Id : 2
PropA : prefix 2
PropB : 
PropC : 
Id : 3
PropA : prefix 3
PropB : 
PropC : 
try update model for each entity with prefix
model original after update
Id : 1
PropA : prefix 1
PropB : B1
PropC : C1
try update model for each entity with prefix
model original after update
Id : 2
PropA : prefix 2
PropB : B2
PropC : C2
try update model for each entity with prefix
model original after update
Id : 3
PropA : prefix 3
PropB : B3
PropC : C3

All objects are correctly updated but this requires knowing how objects were passed by the view.
personally I expected behavior of the collection as parameter of TryUpdateModelAsync with automatic binding for each object.

**Comment by Eilon** [comment]
@kichalla can you investigate?

**Comment by kichalla** [comment]
@branciat Thanks for providing a simple repro

This behavior is by design. For example, you the following test in MVC explicitly tests this:
https://github.com/aspnet/Mvc/blob/1.0.0/test/Microsoft.AspNetCore.Mvc.IntegrationTests/TryUpdateModelIntegrationTest.cs#L109

cc @dougbu for any more comments he might have

**Comment by dougbu** [comment]
@branciat a bit more background: `TryUpdateModelAsync()` can only preserve the top-level `object` it's passed and any properties that are completely untouched. Unless a collection property is not bound, it will be cleared and then filled with new elements.

Bottom line, the approach you took here is what I'd recommend:
``` c#
for (int i = 0; i < origins.Count; i++)
{
    // ...
    var up = TryUpdateModelAsync(origins[i], $"[{i}]");
    // ...
}
```

**Comment by branciat** [comment]
Ok thank you for these explanations. i'll override the TryUpdateModelAsync method to help manage collections of my controllers in a simple manner, while retaining the binding behavior.
