### ISSUE TITLE
question: How to replace UrlResolutionTagHelper.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#5078]
How can I replace the default `UrlResolutionTagHelper` with my own custom one?

**Comment by NTaylorMullen** [comment]
## Service way:
```C#
public class CustomUrlResolutionTagHelper : UrlResolutionTagHelper
{
    public CustomUrlResolutionTagHelper(
        IUrlHelperFactory urlHelperFactory,
        HtmlEncoder htmlEncoder)
        : base(urlHelperFactory, htmlEncoder)
    {
    }

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        base.Process(context, output);

        output.Attributes.SetAttribute("custom", "true");
    }
}
...
services
    .AddMvc()
    .AddTagHelpersAsServices();

services.AddTransient<UrlResolutionTagHelper, CustomUrlResolutionTagHelper>();
...
```
Note: This does not require any additional `@addTagHelper` directives. It simply returns the `CustomUrlResolutionTagHelper` when the default one is requested.

## Non-ServiceWay:
- `@removeTagHelper Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper, Microsoft.AspNetCore.Mvc.Razor` - This will remove the default
- `@addTagHelper CustomUrlResolutionTagHelper, AssemblyWithMyCustomUrlResTagHelper` - Add your own :smile:

**Comment by Bartmax** [comment]
Thank you @NTaylorMullen !! excellent!

**Comment by Bartmax** [comment]
I suspect Url.Content will NOT use the custom `CustomUrlResolutionTagHelper` logic ?

**Comment by NTaylorMullen** [comment]
Nope.

**Comment by dougbu** [comment]
It also doesn't change URL resolution in subclasses -- the `<img>`, `<link>` and `<script>` tag helpers.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
