### ISSUE TITLE
Needed assistance in dealing with nested data table structure

### ISSUE THREAD

**Issue by Panda-Srujan** [aspnet/Mvc#5081]
Hi everyone,

I'm new to MVC. I've a situation where I've a data source (3 tables) from which I'm getting the data and need to display in a table format in such a way that when I click on a row of first table, it should expand into another (child) table and when clicked on one of the rows of child table, it should expand into its another (sub child) table. And each table, either sub child or child or master table should be provided with the provision for sorting and searching for the record.

Additionally each row of main table along with child and sub child table rows/records needs to be edited (inline), deleted and there must be a provision to add a new record (inline) for all main table, child and sub child tables.

The above was the task assigned to me. As I'm new to MVC, I couldn't analyse what would be the best way to accomplish the task. 

Any help or advice will be highly appreciated.

Thanks in advance.

**Comment by Eilon** [comment]
@Panda-Srujan this kind of question might be better suited to a forum such as StackOverflow. I recommend using the following tag: http://stackoverflow.com/questions/tagged/asp.net-core-mvc

**Comment by Panda-Srujan** [comment]
Hi Eilon,

Thanks for your suggestion.
