### ISSUE TITLE
How to use razor / TagHelper for collections?

### ISSUE THREAD

**Issue by gdoron** [aspnet/Mvc#5085]
Hi,

I'm not sure if there's a web standard for how collections should formed and sent.
e.g.

	Images[0]=http://foo.com/0&Images[1]=http://foo.com/1&Images[2]=http://foo.com/2
	vs
	Images=http://foo.com/0&Images=http://foo.com/1&Images=http://foo.com/2
Both work for .NET, but the latter seems (according to [this Stackoverflow answer](http://stackoverflow.com/a/9547490/601179)) to take the last value on PHP.

Problem is, when using the first syntax, if an item gets removed from the DOM and the request is something like:

	Images[0]=http://foo.com/0&Images[2]=http://foo.com/2
ASP.NET's model binder won't bind the second item in the collection, basically it ignores all items after the gap.

OK, so just use the second syntax, right?
Yes and No.
Yes it does work, No I couldn't find a way to generate it using Razor and TagHelpers.

Using:
	
	@for (int i = 0; i < Model.Images.Count; i++)
	{
		<input type="hidden" asp-for="Images[i]" class="hidden-image" />
		Or
		@Html.HiddenFor(x=> x.Images[i])
	}
Generates*: 

	<input type="hidden" name="Images[0]" id="Images_0_" value="0" />
	<input type="hidden" name="Images[1]" id="Images_1_" value="1" />
	<input type="hidden" name="Images[2]" id="Images_2_" value="2" />

Also see [this StackOverflow question](http://stackoverflow.com/q/38473487/601179) (of mine) 

*
 
1. Why the geneared HTML has `_` suffix in the id?
2. Why does sometimes the generated HTML is PascalCase(like here) and sometimes it's camelCase?

Thanks

**Comment by gdoron** [comment]
BTW, this is how I overcome it, but it didn't utilize the TagHelpers or HtmlHelpers:

    @for (int i = 0; i < Model.Images.Count; i++)
    {
        <input type="hidden" name="Images" value="@Model.Images[i]" class="hidden-image"/>
    }

**Comment by javiercn** [comment]
There is no rule in HTML that dictates how to post a collection of elements to the server. Each server technology has its own convention to do this. In the MVC case, as you mention, I believe both approaches are supported. Images[index] and Images.

Regarding the casing, I believe you are asking the reason why some things like Images is capitalized and some other thing like value is not. The reason is because Images is the name of the property in your model and we just respect that casing. HTML is case insensitive so there is no need to do extra work to make it camel cased or any other format.

Finally, the _ happens due to the fact that MVC defines a bidirectional mapping between properties in your model and names in form inputs that are used during model binding and as part of that, simbols like '.', '[' and ']' get replaced by _. 
There might be a small bug here if HTML helpers don't produce the same name (if they don't add the suffix) but as long as the mapping works for model binding both approaches are valid.

**Comment by gdoron** [comment]
@javiercn Thanks for the **extremely** fast response! 

So in cases where elements can be removed from the collection, I cannot use TagHelpers and HtmlHelpers? 

Why not always use the `Property` syntax instead of the `Property[index]` syntax.
It works even if items are removed from the DOM.
Or alternatively, make the ModelBinder bind collections with gaps.

Thanks for your answers!

BTW, you got to love web standards... :crystal_ball:

**Comment by javiercn** [comment]
I'll let @dougbu answer whether the modelbinder can or can not bind collection with gaps, but I would say that  if you are doing DOM manipulation on the client, it is probably a better option to have a model on the client and use AJAX to post some JSON to the server at that point. Another option is to have a specific form for removing elements from the collection (with checkboxes or something like that). The reason for this is that if the client didn't support JavaScript or had it disabled for some reason (I know its the 21st century but these things happen) the functionality on your webpage will be crippled.

The point that i'm trying to make is that while there might be room for improvement in the modelbinder (i'll let @dougbu comment on that), there are alternative designs that might be simpler and avoid you all the trouble with updating collections with modelbinding.

Hope this helps.

**Comment by rynowak** [comment]
There are three styles the model binder supports for collections. I'll use query string in the examples, form data and route data behave the same. In all of these cases, assume we're binding an `ICollection<int>` to a property `items`.

Single-Element: `/Some/Path?items=1,2,3`
Sequential-Indexing: `/Some/Path?items[0]=1&items[1]=2&items[2]=3`
Explicit-Indexing: `/Some/Path?items.index=0,1,2&items[0]=1&items[1]=2&items[2]=3`

The last format (Explicit-Indexing) is supported with gaps, non-zero starting index, and really any arbitrary keys. The most significant thing is that the order of the `items.index` property determines the order of the items in the collection.

`/Some/Path?items.index=foo,bar&items[bar]=1&items[foo]=2` would result in the collection `{ 2, 1 }`

**Comment by gdoron** [comment]
@javiercn in general I do follow this principal of supporting clients with javascript disabled, but in this case, it's just not possible,
The experience of uploading / edit images without js is horrific.
If your javascript is off, currently, all of our website will function as normal, except for this.
I do not want to fallback to checkboxes, it doesn't worth the effort and the experience is bad anyway.

**Comment by gdoron** [comment]
@rynowak I wasn't aware of _Explicit-Indexing_.
You didn't mention the `items=1&items=2` way, is there a reason you ignored it?

I'm not sure why you need so many options though...
And still, none of the ways will work when javascript is disabled or shouldn't be in use.
See [this question](http://stackoverflow.com/q/38473487/601179) for example where there is a list of checkboxes and the checked checkboxes aren't guarantee to be in order.

Only the `items=1&items=2` way is viable here, but that seems to not be available with Razor and TagHelpers.

Manipulate the DOM with javascript to produce querystring like `/Some/Path?items.index=0,1,2&items[0]=1&items[1]=2&items[2]=3` so the model binder will be able to bind the collection seems extremely wrong.

**Comment by rynowak** [comment]
> You didn't mention the items=1&items=2 way, is there a reason you ignored it?

Yeah you're right, this is actually the correct one.

**Comment by gdoron** [comment]
@rynowak so is it possible to make the TagHelpers output that syntax?
It's a breaking though :( maybe it can be opt-in configuration at startup?

**Comment by gdoron** [comment]
@rynowak Currently is there a way to use a TagHelper/HtmlHelper for something like in the [SO question I linked](http://stackoverflow.com/q/38473487/601179)?
I think there is not.

**Comment by dougbu** [comment]
@gdoron this conversation seems to be bouncing between the name formats model binding supports and the name formats tag helpers generate. The two overlap of course but model binding is broader because it also supports clients that are not submitting a form on a generated Razor view. Is your question mainly about model binding or HTML generation?

Going back to your original questions:
> Why the geneared HTML has `_` suffix in the `id`?

That's a replacement for the closing `]` in the `name`. MVC limits itself to `id` characters allowed in HTML 4.01 for backward compatibility. What issue does this cause?

> Why does sometimes the generated HTML is PascalCase(like here) and sometimes it's camelCase?

Where are you seeing camel case generated HTML? MVC mainly changes case in the far different case of serializing JSON for a response. Otherwise case should match the C# classes in the model.

**Comment by Bartmax** [comment]
I don't agree HTML doesn't specify how the format should be.
If you make a <form with method="GET"> you will see that the actual format is the single item one.

To use that on tag helpers is simple as specifying the name value.

```
@for (int i = 0; i < Model.Images.Count; i++)
{
    <input type="hidden" asp-for="Images[i]" name="@nameof(Model.Images)" class="hidden-image" />
}
```
and you can use nameof to avoid magic strings.

**Comment by gdoron** [comment]
@dougbu 

> MVC mainly changes case in the far different case of serializing JSON for a response. Otherwise case should match the C# classes in the model.

I see, that clarifies a lot, I got confused with JSON responses, thanks.

@Bartmax Thanks for the `nameof` tip, interested in knowing the reasons it's not the default too.

**Comment by dougbu** [comment]
> you can use `nameof` to avoid magic strings

`nameof` is fine for properties with the simplest of ASCII C# names at the top level of the `Model`. They don't work when accessing something further down.

In this particular case, the generated HTML will contain multiple `<input/>` elements with the same `name`. Probably fine here but not useful when generating fields for say `Images[0].Name`, `Images[0].File`, `Images[1].Name`, ...

**Comment by Bartmax** [comment]
You can use name="images" if you don't want to use nameof that wasn't the point here. 

The idea is to have same name, that's what make this all works and how html works internally but you already know that. Not sure I understand what's your point. 

Also, the order is preserved so you can use name="image.name" and "image.type" for collections of fields. Why that would be a problem? I'm pretty sure I have multiple stuff working that way but I need to check them out to be sure.

**Comment by gdoron** [comment]
@rynowak 

> Single-Element: /Some/Path?items=1&items=2&items=3
Sequential-Indexing: /Some/Path?items[0]=1&items[1]=2&items[2]=3
Explicit-Indexing: /Some/Path?items.index=0,1,2&items[0]=1&items[1]=2&items[2]=3

Only (the awkward IMHO) _Explicit-Indexing_ option worked for me when I needed to send a complex object over HTTP GET:

	{
		Paragraphs: [{
			Title = "My Title",
			Body: "My Body"
		}]
	}
_Sequential-Indexing_ worked only for HTTP POST.
_Single-Element_ didn't work at all.

Is this a bug?
Do you want me to open a new issue or is it by-design?

**Comment by rynowak** [comment]
If you're doing a complex object then 'Single-Element' won't work. 

I'm curious what exactly wasn't working for using 'Sequential-Indexing' - can you capture a trace of the HTTP request using your browser and let me see what the form data looks like?

**Comment by gdoron** [comment]
@rynowak 

`$` is obviously here jQuery

	$.param({Paragraphs:[{Text:"text",
					    Title:"title", Id:1}]})
Produces:

> Paragraphs%5B0%5D%5BText%5D=text&Paragraphs%5B0%5D%5BTitle%5D=title
	
	decodeURIComponent("Paragraphs%5B0%5D%5BText%5D=text&Paragraphs%5B0%5D%5BTitle%5D=title"):
"Paragraphs[0][Text]=text&Paragraphs[0][Title]=title"

This doesn't work on GET.
But If I change from

`"Paragraphs[0][Text]=text&Paragraphs[0][Title]=title"`
To
`"Paragraphs[0].Text=text&Paragraphs[0].Title=title"`
It does work.

Though I might be naive, but isn't there a standard? Everything has standards these days, but how to send collections and complex object don't have? That's odd.

**Comment by gdoron** [comment]
Not that I think about it, maybe it works not because of the explicit indexing but because of using 
`.Property` instead of `[Property]` (jQuery's way)
I made both of the changes because of this old blog post:
http://haacked.com/archive/2008/10/23/model-binding-to-a-list.aspx/

**Comment by gdoron** [comment]
@rynowak If you asked if I'm using this value in the querystring, the answer is yes
I'm using this code:

	var params = $('#addStoryForm').serialize();
	var win = window.open('@Url.Action("Preview", "Story")?' + params, 'previewWindow');
LMK if I misunderstood your question.

**Comment by dougbu** [comment]
> is this something the jQuery value provider should address?

We don't have a jQuery value provider for anything but the form content. For the query string, we basically use what we're given in the request object. I suspect this difference comes from an expectation that only the simplest information will come in the query string.

**Comment by rynowak** [comment]
ok @gdoron could you open a new issue for this. Right now this isn't expected to work, we should discuss whether to support this in the future.

**Comment by gdoron** [comment]
Done
#5123
