### ISSUE TITLE
How to run Asp.net core RTM on mono with Arm based Linux

### ISSUE THREAD

**Issue by techcap** [aspnet/Mvc#5088]
Now Asp.net core rtm doesn't work on mono.
There's workaround which I tested.
1. MVC dynamic compilation does not work on mono. Now I used Publish option using right click over project item in solution explorer, Visual Studio.
2. Copy 1st step's publish files to linux machine.
3. System.Runtime.InteropServices.RuntimeInformation.dll is only for windows machine, if I compiled it on windows machine. So I have to replace the file to packages\System.Runtime.InteropServices.RuntimeInformation.4.0.0\runtimes\unix\lib\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll.
4. System.Native is required. Kestrel server only use one function, GetUnixName.
   @Tragetaschen made libSystem.Native project. https://github.com/aspnet/Home/issues/1610
   Below is compile and installation script.

```
git clone https://github.com/Tragetaschen/libSystem.Native
cd libSystem.Native/src
cc -c -o libSystem.Native.o GetUnixName.c -fpic
cc -shared libSystem.Native.o -o libSystem.Native.so
/usr/bin/install -c -m 644 libSystem.Native.so /usr/local/lib
echo "/usr/local/lib" | tee /etc/ld.so.conf.d/local.conf 
sudo ldconfig -v
```
1. Run with mono
   > mono TestWeb.exe

When will Asp.net core support arm platform or mono?

**Comment by Eilon** [comment]
ASP.NET Core support for Mono isn't planned; we don't do anything to specifically *block* it, but we also don't test on it. If you have some safe changes that would enable ASP.NET Core / MVC to run on Mono, we can certainly work with you to get those changes made.

**Comment by techcap** [comment]
After reviewing the source code, I found how to run Asp.net core RTM on linux completely.

Microsoft.Extensions.DependencyModel searches Reference Assemblies inside xbuild-frameworks/.NETFramework/v{.NET Version}.

For working MVC dynamic compilation, use this script.

```
cd /usr/lib/mono
mkdir xbuild-frameworks
cd xbuild-frameworks
mkdir .NETFramework
cd .NETFramework
ln -s ../../4.5 v4.5.2
```

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
