### ISSUE TITLE
data model property name localization support?

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/Mvc#5092]
Currently we could use `IStringLocalizer["Hello World"]` to localize cshtml view.
But when we come to `DisplayAttribute` of model property, its `Name` property could not contain white space like above sample. I have to add new item in RESX file like "Hello_World" to support property name localization, which is very annoying.
Is there any plan to unify these localization tools /ways? Or should I have separate RESX files for codes and cshtml views?

**Comment by Eilon** [comment]
Duplicate of https://github.com/aspnet/Mvc/issues/3518.
