### ISSUE TITLE
Unable to refresh the view after performing operation.

### ISSUE THREAD

**Issue by Panda-Srujan** [aspnet/Mvc#5095]
Hi everyone,

I've a situation where I'm displaying the data in table format in my view.

I've called the appropriate action to perform necessary operation like delete, edit and update. I've used RedirectToAction to the main action method to reload the data and refreshes the page.

But unfortunately, the issue is that the page isn't refreshing. Please let me know how to refresh the page.

Thanks in advance.

**Comment by NTaylorMullen** [comment]
@Panda-Srujan could you provide a simple repro project for what you're seeing? You should be able to see updates in your views on refresh.

**Comment by Eilon** [comment]
There's no server or client caching by default so this should all just work by default. Can you debug your app to see what's happening? Are you sure the data is reloading on the server? Can you check if any HTTP headers are being set that might affect caching? Unfortunately there isn't enough information here for us to investigate.

**Comment by Panda-Srujan** [comment]
Hi Eilon,

I've debugged the code, the code flow is perfect as expected, both in controller and the view after operation being performed except the thing that page is not loading for some reason.

**Comment by Eilon** [comment]
So where is the issue? Is the right data being rendered, but the web browser isn't seeing it?

**Comment by Panda-Srujan** [comment]
Seems so. The page after redirecting to another controller and back to the view is not at all refreshing in the browser.

**Comment by Eilon** [comment]
Sorry, I still don't understand where the problem is. We can investigate the problem once we know where the problem is. At what point is the data/rendering correct, and at what point is it wrong?
