### ISSUE TITLE
Feature: Enhance GetEnumSelectList html helper to support Flags enum.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#5096]
see based on https://github.com/aspnet/Mvc/issues/5084#issuecomment-236336854 for some more info.

Make `Html.GetEnumSelectList` enum support flag attribute

Framework can switch from simple value select to a multiple `<select multiple>` tag.
And selected options will be all those that HasFlag for the enum.

sample boilerplate output will be:

```
<select multiple>
<option>1</option>
<option selected>2</option>
<option>3</option>
<option selected>4</option>
```

**Comment by dougbu** [comment]
Haven't tested it recently but I believe this feature request is incomplete as described. The model binding system converts a collection of values into a single value by grabbing the first value, not ORing them together. There are no special cases in the model binding system for `[Flags]` `enum`s.

I recommend a view model containing an `IEnumerable<TEnum>` property and a bit of code to OR the values together into the actual value. `TEnum` could be a non-`[Flags]` `enum` containing the subset of values you actually want in the UI.
