### ISSUE TITLE
Unique ids for radio button inputs, support for collection backed checkbox sets

### ISSUE THREAD

**Issue by artiomchi** [aspnet/Mvc#5098]
For a while now generating multiple radio buttons with labels has been somewhat troublesome, since all the radio buttons would get the same `id` attribute, and we had to manually pass an id attribute in the htmlAttributes anonymous object, then pass the same value to the label's for attribute

Added to this, the checkbox helpers will only create checkboxes for boolean properties. In fact, the tag helpers in asp.net core will throw an exception if a non boolean type is passed to the input helper with type=checkbox

This pull request tries to achieve two things:
1. Append the serialised value of the radio button to it's id attribute to generate a unique id for each input
2. Add the ability to create checkboxes for collection properties, and generate unique ids for each
3. Extend the label tag helper to generate the same ids as above, to simplify development

Specifically, given this model classes:

```
public class EditModel
{
    public int ID { get; set; }
    public int[] Roles { get; set; }
    public Gender Gender { get; set; }

    public Role[] AllRoles() => new[]
    {
        new Role { ID = 1, Title = "Role 1" },
        new Role { ID = 2, Title = "Role 2" },
    };
}

public class Role
{
    public int ID { get; set; }
    public string Title { get; set; }
}

public enum Gender
{
    Male = 1,
    Female = 2,
}
```

And this razor view:

```
<li>
    <label>Gender</label>
    @foreach (Gender gender in Enum.GetValues(typeof(Gender)))
    {
        <input asp-for="Gender" type="radio" value="@gender" />
        <label asp-for="Gender" asp-for-value="@gender">@gender</label>
    }
    <input asp-for="Gender" type="radio" value="@Gender.Male" id="Gender_Male_Custom" />
    <label asp-for="Gender" for="Gender_Male_Custom">@Gender.Male (custom id)</label>
</li>
<li>
    <label>Roles</label>
    @foreach (var role in Model.AllRoles())
    {
        <input asp-for-collection="Roles" type="checkbox" value="role.ID" />
        <label asp-for="Roles" asp-for-value="role.ID">@role.Title</label>
    }
    <input type="checkbox" name="Roles" value="3" id="Roles_3" />
    <label for="Roles_3">Role 3 (custom id)</label>
</li>
```

Generates the following:

```
<ul>
    <li>
        <label for="ID">ID</label>
        <input type="number" data-val="true" data-val-required="The ID field is required." id="ID" name="ID" value="0">
    </li>
    <li>
        <label>Gender</label>
        <input type="radio" value="Female" data-val="true" data-val-required="The Gender field is required." id="Gender_Female" name="Gender">
        <label for="Gender_Female">Female</label>
        <input type="radio" value="Male" id="Gender_Male" name="Gender">
        <label for="Gender_Male">Male</label>
        <input type="radio" value="Male" id="Gender_Male_Custom" name="Gender">
        <label for="Gender_Male_Custom">Male (custom id)</label>
    </li>
    <li>
        <label>Roles</label>
        <input id="Roles_1" name="Roles" type="checkbox" value="1">
        <label for="Roles_1">Role 1</label>
        <input id="Roles_2" name="Roles" type="checkbox" value="2">
        <label for="Roles_2">Role 2</label>
        <input type="checkbox" name="Roles" value="3" id="Roles_3">
        <label for="Roles_3">Role 3 (custom id)</label>
    </li>
</ul>
```

The current code has a couple specific issues that prevents this from happening:
- The radio buttons are all generated with the same id attribute, which is kind of wrong, since that makes them useless. `document.getElementById` (and jQuery's $('#{0}') accessor will only return the first element with the matching id value.
- The standard checkbox html generator can't be used, since it enforces a boolean type internally.
- There is no support for checking the value against a collection/array in the backing model property.

Changing the first point is relatively easy, I've updated the radio button html generator to append a sanitised version of it's value to the id attribute making it unique. I've also added support for this to the label tag helper via the `asp-for-value` attribute (and the `idModifier` parameter in the `IHtmlGenerator`'s code

For the checkbox support with the backing array, I've created a `CollectionInputTagHelper`, which can generate a radio button or a checkbox, backed by a collection (any array, enumerable, list etc) property. It uses the code that generates a radio button, and sets the `checked` property if the value of the input is present in the collection.

To optimise this check, the `value` of the input is bound to an object (unlike the string based value that's bound in `InputTagHelper`). This way I don't have to convert every value of the array when checking for a match. (see [this](https://github.com/artiomchi/Mvc/blob/ee87c205e2e363eec750cd869e1a878d6f6996d1/src/Microsoft.AspNetCore.Mvc.TagHelpers/CollectionInputTagHelper.cs#L100) line of code)

Checkboxes can be created by creating an input like this:

```
<input asp-for-collection="Roles" type="checkbox" value="role.ID" />
```

The pull request can be seen here: aspnet/Mvc#5097

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this? I've already closed the PR as there were a lot of conflicts already (we had been too slow on responding to it).

**Comment by pranavkm** [comment]
Using https://github.com/aspnet/Mvc/issues/599 to track the remainder of the work here. We need a bit of design around what the tag helper looks like since it affects things like labels as you noted.
