### ISSUE TITLE
How To use Bundleconfig in Mvc Core 1.0

### ISSUE THREAD

**Issue by ermithun** [aspnet/Mvc#5099]
How To use Bundleconfig in Mvc Core 1.0 ??
Need Help

**Comment by rynowak** [comment]
There's some documentation here: https://github.com/madskristensen/BundlerMinifier

/cc @madskristensen

**Comment by Eilon** [comment]
If this is about bundleconfig.json, @rynowak 's answer is the place to go.

If this is about BundleConfig.cs, then that was using ASP.NET Bundling & Minification, which was for ASP.NET 4.x only, and is not available for ASP.NET Core.
