### ISSUE TITLE
WebApi not returning expected list

### ISSUE THREAD

**Issue by BillChirico** [aspnet/Mvc#5101]
Hello,

When working with a WebApi controller I am trying to return all of the household objects in the database with the members included in it. This is the code I ended up with:

```
public IEnumerable<Household> Households()
{
    var households = _context.Households.Include(h => h.Members);

    return households;
}
```

The problem is, is that the JSON is only showing the first result and not the two that I have in the list. I tried debugging and there are definitely two household objects in the list. What is even weirder, is when I do not have the include then it shows both households. Any ideas?

Thanks

**Comment by rynowak** [comment]
Look at the console logging output, debugger or developer exception page? Is an exception occurring during serialization?

Does this change if you do `return households.ToList()`?

**Comment by BillChirico** [comment]
@rynowak Actually getting the following serialization exception: 

`Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'household' with type 'Matey.Data.Models.Household'. Path '[0].members[0]'.`

**Comment by rynowak** [comment]
You can also globally configure the behavior you want for JSON.NET in our formatters to have the reference handling (of cycles) you want.
```
services.AddMvc().AddJsonOptions(options => options.SerializerSettings.ReferenceHandling = ...);
```

The JSON.NET docs will describe what the options do.

**Comment by BillChirico** [comment]
@rynowak That fixed it project wide thank you very much.
