### ISSUE TITLE
Disabling client validation breaks TH validation

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#5102]
_From @Rick-Anderson on July 31, 2016 4:34_

From customer DISQUS comment:
https://docs.asp.net/en/latest/tutorials/first-mvc-app/validation.html

If I disable Client Validation using services.AddMvc().
```
AddViewOptions(options =>
{
options.HtmlHelperOptions.ClientValidationEnabled = false;
});
```

Server validation errors are not display with Tag Helper validation. Switching to HTML Helper validation,  errors are displayed.

_Copied from original issue: aspnet/Razor#812_

**Comment by Eilon** [comment]
_From @NTaylorMullen on August 1, 2016 17:11_

@Rick-Anderson could you please file this issue in Mvc? Doesn't seem to be a Razor related issue since the MVC TagHelpers are the ones responsible for dealing with validation logic.

**Comment by dougbu** [comment]
This looks like a Scaffolding issue which was fixed post-1.0.0. Don't remember the number but it's about generating `<span>` elements as (invalid) self-closing tags.

Make sure your `<span>`s have end tags and server-side validation errors should start to show up.

**Comment by dougbu** [comment]
@Rick-Anderson were you able to fix the scaffolded `<span>`s to get the expected client- and server-side validation behaviour?

If not, please provide a small project (preferably a GitHub repo) demonstrating the problem.

**Comment by dougbu** [comment]
Great to hear
