### ISSUE TITLE
MVC doesn't work on FIPS-compliant machines

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#5103]
Related to https://github.com/aspnet/Antiforgery/issues/95

Bad codes:
* https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/src/Microsoft.AspNetCore.Mvc.TagHelpers/Internal/FileVersionProvider.cs#L114
* https://github.com/aspnet/Mvc/blob/341430eae508912d3a868bf636b86ec04155378e/src/Microsoft.AspNetCore.Mvc.TagHelpers/Cache/CacheTagKey.cs#L154

**Comment by NTaylorMullen** [comment]
PR is ready to go in. Waiting for patch-approved.

**Comment by NTaylorMullen** [comment]
edb5baf81c07e3e9db8c3019439414094acb6ef8
6e5fd4f89f6989ae560d219a7c8b4e102a1032d9
