### ISSUE TITLE
Default scope IViewBufferScope causing issues with threaded job.

### ISSUE THREAD

**Issue by SeeWhat** [aspnet/Mvc#5106]
I've got a job which has a number of Tasks which generate emails using the example [RenderViewToString](https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString).

The issue is when running under with concurrent Tasks I get random errors as below.

```
Index was outside the bounds of the array.|System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.MemoryPoolViewBufferScope.GetPage(Int32 pageSize)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer.GetCurrentPage()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer.AppendHtml(String encoded)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.WriteLiteralTo(TextWriter writer, String value)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.WriteLiteralTo(TextWriter writer, Object value)
```

```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index|System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.MemoryPoolViewBufferScope.GetPage(Int32 pageSize)
```

```
Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBufferPage.Append(ViewBufferValue value)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer.AppendHtml(String encoded)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.WriteLiteralTo(TextWriter writer, String value)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.WriteLiteralTo(TextWriter writer, Object value)
```

Looking at the issue, I found that making [IViewBufferScope ](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/DependencyInjection/MvcViewFeaturesMvcCoreBuilderExtensions.cs#L167) Transient, it stops the errors.

Although this appears to fix the issue, is it the underlying cause or am I possibly missing something?

Is making it Transient the correct solution, should it be Transient by default or should I create new scopes per thread? Although the third option isn't easy as I'm using the default DI and there is this issue (https://github.com/aspnet/DependencyInjection/issues/246).

Note: I've tested this against 1.1.0-alpha1-21752

**Comment by pranavkm** [comment]
Could you elaborate on what you're trying to run concurrently?

**Comment by SeeWhat** [comment]
Hi, corrected my initial description., I'm actually kicking off multiple tasks(not threads) and awaiting them with a Task.WhenAll().

Each task will gather the data required for external sources and then generate the email, rendering it as HTML. Only once the email has been generated and queued for sending is that task complete.

**Comment by pranavkm** [comment]
It would've be useful to see a code snippet of what you're doing. That said, the code sample in Entropy isn't designed to be run concurrently. You might be able to add it as a transient service and create a scope for each `Task` that gets executed. But I'm not sure if that necessarily works.

```C#
// ConfigureServices
services.AddTransient<RazorViewToStringRenderer>();

// Run
var serviceScopeFactory = serviceProvider.GetRequiredService<IServiceScopeFactory>();
emailsToProcess.Select(t => Task.Run(() =>
{
  using (var scope = serviceScopeFactory.CreateScope())
  {  
    var renderer = provider.GetRequiredService<RazorViewToStringRenderer>();
    ....
  }   
});
```

**Comment by rynowak** [comment]
`IViewBufferScope` needs to be scoped, it's to used to coordinate use of memory across views and partials as part of the same 'request'. I know in your case there isn't a request, but the right approach is something like what @pranavkm is suggesting - you'll need to await all of the tasks.

**Comment by Eilon** [comment]
Should we update the sample in Entropy? Or is this really just an exercise left to the reader?

**Comment by pranavkm** [comment]
Leave it as an exercise? Doing all the extra stuff probably detracts from the the primary purpose of the sample.

**Comment by SeeWhat** [comment]
Thanks @pranavkm. I guess the perfect example would have been what you provided without the fix (As below for reference). 
```
public Test(RazorViewToStringRenderer renderer)
{
	_renderer = renderer
}
...
public void DoWork()
{
	...
	emailsToProcess.Select(t => Task.Run(() =>
	{
	   _renderer.RenderViewToString("EmailTemplate",model);
	  ...
	});
	...
}
```
I've modified my code as recommended with Transient and scoping and it worked.

It wouldn't hurt to have a comment in the example at least. Also given the solution is to at least have it scoped correctly. The example has it as a singleton which could be misleading.

**Comment by pranavkm** [comment]
If you're up for it, feel free to send a PR to Entropy. You could fix the lifetime of the the service and maybe add a separate method that shows how it could be used to process more than one thing.

**Comment by pranavkm** [comment]
Closing this since it's not specifically and Mvc issue. Feel free to start a discussion in https://github.com/aspnet/Entropy/issues

**Comment by daveaglick** [comment]
Just a note that this same problem also caused me issues (and probably for the same reasons). I'm not using the Entropy library, though am doing something similar with a custom Razor host that relies on many of the existing services. I'm seeing intermittent exceptions from the `MemoryPoolViewBufferScope` class:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.MemoryPoolViewBufferScope.GetPage(Int32 pageSize)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer.GetCurrentPage()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBuffer.AppendHtml(String encoded)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewBufferTextWriter.Write(String value)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.WriteLiteralTo(TextWriter writer, String value)
...
```
In my case, I am scoping the service provider, but the scope encompases many parallel Razor compilations. I could narrow the scope to wrap each individual view compilation, but I'd hate to do that because I'm relying on the scope being broader for other parts of my app.

Is this the only service that gets used during Razor compilation and/or rendering that isn't thread-safe? If so, it does strike me as more of an "MVC issue" since it prevents writing any Razor host that does parallel processing (not just the simple one in Entropy).

**Comment by pranavkm** [comment]
> In my case, I am scoping the service provider, but the scope encompases many parallel Razor compilations.

The error you're seeing here shouldn't happen as part of compilation. It's a result of trying to render one or more views concurrently without the right kind of scoping. Do you still see this error if you create a scope per view execution? 

> would a PR to MemoryPoolViewBufferScope to make it thread-safe be considered? 
There's probably other areas of the code in this area that aren't thread safe, so I'm not sure fixing the `MemoryPoolViewBufferScope` alone would suffice.

**Comment by daveaglick** [comment]
> The error you're seeing here shouldn't happen as part of compilation

It's definitely happening during rendering, I just combine compilation and rendering for each view into a single task and then run those in parallel across all the views that need to be rendered.

> Do you still see this error if you create a scope per view execution?

Nope - limiting the scope appears to resolve the issue. I'm not thrilled about that since I want a broader scope that covers this whole process for my other components.

> There's probably other areas of the code in this area that aren't thread safe

This is the gotcha, I think. I was able to get past this particular problem with the code below, but I'm worried there might be other similar concurrency issues I just haven't hit yet. The alternative is to just render each of the views in sequence, but that'll take much longer for a very large set. I'll fall back to that if I have to though. So far, so good.

Here's how I ended up getting around this in case someone else stumbles on this issue in the future:
```
serviceCollection..AddScoped<IViewBufferScope, SafeMemoryPoolViewBufferScope>();
// ...
internal class SafeMemoryPoolViewBufferScope : IViewBufferScope, IDisposable
{
    private readonly object _lock = new object();
    private readonly MemoryPoolViewBufferScope _pool;

    public SafeMemoryPoolViewBufferScope(ArrayPool<ViewBufferValue> viewBufferPool, ArrayPool<char> charPool)
    {
        _pool = new MemoryPoolViewBufferScope(viewBufferPool, charPool);
    }

    public ViewBufferValue[] GetPage(int pageSize)
    {
        lock (_lock)
        {
            return _pool.GetPage(pageSize);
        }
    }

    public void ReturnSegment(ViewBufferValue[] segment)
    {
        lock (_lock)
        {
            _pool.ReturnSegment(segment);
        }
    }

    public PagedBufferedTextWriter CreateWriter(TextWriter writer) => _pool.CreateWriter(writer);

    public void Dispose() => _pool.Dispose();
}
```

**Comment by rynowak** [comment]
The `IViewBufferScope` is tied to the unit of work - it's designed to manage all of the buffers that are needed by a single run of the page. Making it thread-safe breaks that contract. 

Consider simplifying to something like: https://github.com/aspnet/Mvc/blob/a78f77afde003c4a3fcf5dd7b6dc13dd9c85f825/test/Microsoft.AspNetCore.Mvc.ViewFeatures.Test/Internal/TestViewBufferScope.cs

You don't need to mess with any of the custom stuff we're doing here, you just need `new` and let the GC handle it.



**Despite all that, I want to be absolutely crystal clear that....**

Anything in MVC's services that has a scoped lifetime or uses the `ViewContext` is not thread safe. The fact that what you're doing today works is not a guarantee that it will be supported in the future. A component that is thread safe but scoped today could become non-thread-safe in the future. 

The only supported use of these services is within a 'scoped' container that has the proper lifetime. For views this means creating the scoped container before running the view, running it with a single thread, and then disposing the container.


====================




@pranavkm should we update the sample to use scopes properly?

**Comment by pranavkm** [comment]
Filed https://github.com/aspnet/Entropy/issues/167 to track the Entropy work.

**Comment by daveaglick** [comment]
> Anything in MVC's services that has a scoped lifetime or uses the `ViewContext` is not thread safe

Good to know - thanks for the unambiguous clarification. I'll plan accordingly and remove anything that assumes thread safety.
