### ISSUE TITLE
Model Binding changes from mvc 5 to core

### ISSUE THREAD

**Issue by omuleanu** [aspnet/Mvc#5111]
in mvc 5 posting and empty string 
`$.post('url', { s: "" }`
would bind
`public ActionResult  Hi(string s) // s is empty string in mvc 5`
in core it's `null`

and not posting anything to an action with an array parameter
`$.post('url', { })`
`public ActionResult  Hi(string[] items) // items is null in mvc 5`
in core it's `empty array string[0]`

**Comment by Eilon** [comment]
@rynowak @dougbu thoughts?

**Comment by dougbu** [comment]
@omuleanu posting JSON to an MVC Core endpoint requires `[FromBody]` for correct model binding. The same is true with MVC 5. Are you comparing to Web API behaviour?

**Comment by omuleanu** [comment]
@dougbu no, I was porting some code from mvc 5 and got into some issues because of these differences, I'm not using the mvc5 api controller; 
`$.post -> controller.action`
empty array and null array used to mean different things in my app (now I've added a flag parameter)
and for the empty string it was:
` $.post('url', { s: $('#txt1').val() })`
so I wasn't expecting it to be `null`, and was calling `toLower()`

anyway, I just wanted to make sure you're aware of these changes

**Comment by Eilon** [comment]
Closing because we think the current behavior is acceptable (even if it is different from MVC 5).
