### ISSUE TITLE
How to upload Excel sheet in Asp.Net Core 1.0 

### ISSUE THREAD

**Issue by ermithun** [aspnet/Mvc#5113]
How to upload Excel sheet save in database using  Asp.Net Core 1.0  application  also binding data in model ?

Need Help

**Comment by khellang** [comment]
See http://www.mikesdotnetting.com/article/288/uploading-files-with-asp-net-core-1-0-mvc

**Comment by ermithun** [comment]
@khellang  i had already used this but i didnot got uploaded file in 
```
[HttpPost]
    public async Task<IActionResult> Index(ICollection<IFormFile> files)
    {
        
```
files.count=0 .
so what to do?

**Comment by khellang** [comment]
1. Make sure that your request is `multipart/form-data` and that the name of the file `input` matches the one in your controller.
2. Check `HttpContext.Request.Form.Files` and see if there are any files. I doubt it. If not, that means you haven't uploaded the file correctly/successfully. 
3. Can you post the raw request you sent/received? Put Fiddler or something in between the client and server.

**Comment by damienbod** [comment]
Here's an example, it uses csv with IFormFile
https://damienbod.com/2016/07/15/import-export-asp-net-core-localized-data-as-csv/

**Comment by stanislavromanov** [comment]
Maybe with help questions you should go to https://stackoverflow.com/

**Comment by ermithun** [comment]
@ khellang  
Thankyou
File Uploaded.
