### ISSUE TITLE
Will ASP.NET Core still support DisplayMode?

### ISSUE THREAD

**Issue by dinowang** [aspnet/Mvc#5116]
DisplayMode in ASP.NET MVC 5 is very useful feature. But we couldn't found it in ASP.NET Core.

Have any plan to support DisplayMode in ASP.NET Core?

**Comment by dinowang** [comment]
Found similar question in https://github.com/aspnet/Razor/issues/751

**Comment by Eilon** [comment]
There aren't any plans to bring back Display Modes. I just commented on https://github.com/aspnet/Razor/issues/751 so we can keep the discussion going on there. Thanks!
