### ISSUE TITLE
WebApi Filter Read Json data stream

### ISSUE THREAD

**Issue by 188** [aspnet/Mvc#5120]
Hello, I'm in the Filter in WepApi project data validation, this Api is a Json data stream transmission, after verification in the Filter, and use these data for processing in the Api, so how should operate, thank you

Example
In Filter
``````
using (var sr = new StreamReader(Request.Body))
{
    var json = await sr.ReadToEndAsync();
}
``````
In WebApi
``````
[FromBody]Message message
``````

**Comment by Eilon** [comment]
@188 can you provide more information about what you're trying to do?

You have an ASP.NET Core MVC controller, which has an action method with a parameter such as `[FromBody]Message message`, and you want to write a filter that can perform validation on it?

@dougbu any thoughts on this? I'm not sure I've fully understood but perhaps you have some tips?

**Comment by dougbu** [comment]
@188 if @Eilon has understood your request correctly, have a look at action filters (`IActionFilter` and `IAsyncActionFilter`). Both are invoked with a context (`ActionExecutingContext`) that includes the action's parameters. And the `ModelStateDictionary` is available on the same context if the filter finds additional validation errors.

**Comment by 188** [comment]
Problem has been solve
``````
                    foreach (var postItem in context.ActionArguments)
                    {
                        postJson += postItem.Value.ToJson(JsonHelper.JsonSettingToLower);
                    }
``````
