### ISSUE TITLE
ActionSelector.SelectBestActions method to be passed the RouteContext

### ISSUE THREAD

**Issue by colscott** [aspnet/Mvc#5121]
Would it be possible to have RouteContext passed to SelectBestActions in the ActionSelector source code?

I have an application that has multiple MVC assemblies. The same Controller/Action names might exist across different assemblies. I need to choose an Action based on assembly as well as Controller and Action name.
At first Areas were used to distinguish between MVC assemblies, each assembly having it's own Area. But each assembly has the potential to scale and require Areas to be used more conventionally within each assembly.
Now I'm looking to differentiate between assemblies using a different mechanism. So, each assembly is now given a "module" name. So, I need to differentiate between modules/assemblies when looking for matching Actions.
After looking at the MVC source code the best hook seems to be overriding the SelectBestActions method in the ActionSelector class. I already have the data I need to choose the correct module/assembly in the RouteData. Problem is that the SelectBestActions method is not passed the RouteContext (all other methods do seem to get passed this object). To get around this, I override the whole class rather than extending and just overriding the virtual SelectBestActions.

**Comment by Eilon** [comment]
@rynowak thoughts on this? Would this be a job for conventions, a la https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRoutingConvention ?

**Comment by rynowak** [comment]
@colscott - the best way to build something like this would be with a combination of what's shown in these two samples:
https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.SubAreaSample.Web
https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRoutingConvention

The set of 'keys' used for action selection is extensible. So if you make a `ModuleAttribute` like [this](https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.SubAreaSample.Web/SubAreaAttribute.cs). Then you can add `module` as a key - and it will work like area for the purposes of action selection.

OR

You can then use a convention like [this](https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.CustomRoutingConvention/NameSpaceRoutingConvention.cs) to customize routes or to 'apply' your 'module' route value [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ControllerModel.cs#L109).

**Comment by colscott** [comment]
Thanks, I'll try these out :-)

**Comment by colscott** [comment]
It worked, thanks again.
