### ISSUE TITLE
Before the update why need stop iis webisite??

### ISSUE THREAD

**Issue by BruinY** [aspnet/Mvc#5122]
Before the update why need stop iis webisite?? update website when rc2, don't need to stop iis

Why lose this feature in 1.0. Very inconvenient

**Comment by Eilon** [comment]
With ASP.NET Core it's almost always required to stop the IIS web site while updating because the files are locked. You can instead place an `app_offline.htm` file (with content to show while the app is offline), which will cause the app to effectively be stopped so that you can update its files.
