### ISSUE TITLE
ViewComponents called in wrong HttpContext scope

### ISSUE THREAD

**Issue by colscott** [aspnet/Mvc#5127]
When calling multiple Actions that all return ViewComponents, and calling them at the same time, the ViewComponents are called in the wrong HttpContext. This only seems to occur when the Action returns the ViewComponent. If the ViewComponents are called from the Actions View (cshtml) it works fine.

For example: (apologies for the formatting)
Controller -

```c#
public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PartialA()
        {
            return ViewComponent(nameof(ComponentA), new { actionString = $"{HttpContext.Request.Path} {System.Threading.Thread.CurrentThread.ManagedThreadId}" });
        }

        public IActionResult PartialB()
        {
            return ViewComponent(nameof(ComponentB), new { actionString = $"{HttpContext.Request.Path} {System.Threading.Thread.CurrentThread.ManagedThreadId}" });
        }

        public IActionResult PartialC()
        {
            return ViewComponent(nameof(ComponentC), new { actionString = $"{HttpContext.Request.Path} {System.Threading.Thread.CurrentThread.ManagedThreadId}" });
        }
    }
```

Components -

```c#
public class ComponentA : ViewComponent
    {
        
        public IViewComponentResult Invoke(string actionString)
        {
            return new ContentViewComponentResult($"Action: {actionString} - Component: {HttpContext.Request.Path} {Thread.CurrentThread.ManagedThreadId}");
        }
    }

    public class ComponentB : ViewComponent
    {

        public IViewComponentResult Invoke(string actionString)
        {
            return new ContentViewComponentResult($"Action: {actionString} - Component: {HttpContext.Request.Path} {Thread.CurrentThread.ManagedThreadId}");
        }
    }

    public class ComponentC : ViewComponent
    {

        public IViewComponentResult Invoke(string actionString)
        {
            return new ContentViewComponentResult($"Action: {actionString} - Component: {HttpContext.Request.Path} {Thread.CurrentThread.ManagedThreadId}");
        }
    }
```

View -

> &lt;h1&gt;Hello&lt;/h1&gt;
&lt;script&gt;
    var loadComponentsAtOnce = function()
    {
        testViewComponent("/Home/PartialA", "test1");
        testViewComponent("/Home/PartialB", "test2");
        testViewComponent("/Home/PartialC", "test3");
    }
    var testViewComponent = function(url, id) {
        var request = new XMLHttpRequest();
        request.onreadystatechange = function () {
            var DONE = this.DONE || 4;
            if (this.readyState === DONE) {
                console.log(this);
                document.getElementById(id).innerHTML = this.responseText;
            }
        };
        request.open('GET', url, true);
        request.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        request.send(null);
    }
&lt;/script&gt;
&lt;button type="button" onclick="loadComponentsAtOnce()"&gt;Load all tests&lt;/button&gt;
&lt;div id="test1"&gt;&lt;/div&gt;
&lt;div id="test2"&gt;&lt;/div&gt;
&lt;div id="test3"&gt;&lt;/div&gt;

The output from the three requests is totally random. The first half of each string is the Action HttpContext Path and thread ID, the second half id the ComponentView HttpContext Path and thread ID. Using the code above, the following output is produced when making three XMLHttpRequests at the same time (one to each Action, PartialA, PartialB, PartialC):

> Action: /Home/PartialA 12 - Component: /Home/**PartialB** 12
Action: /Home/PartialB 14 - Component: /Home/PartialB 14
Action: /Home/PartialC 15 - Component: /Home/**PartialB** 15

Hit the load button to load all again and it's different (still wrong though):
> Action: /Home/PartialA 29 - Component: /Home/PartialA 29
Action: /Home/PartialB 31 - Component: /Home/PartialB 31
Action: /Home/PartialC 33 - Component: /Home/**PartialA** 33

Keep hitting the load button and it's random the HttpContext the ViewComponents are called with.

**Comment by Eilon** [comment]
@rynowak is this the same as https://github.com/aspnet/Mvc/issues/4998 ?

**Comment by rynowak** [comment]
Yes this is the same.

@colscott - the workaround [here](https://github.com/aspnet/Mvc/issues/4998#issuecomment-232108479) should fix the issue

**Comment by colscott** [comment]
I did search for an existing issue first but never found it......honestly :-)
Thank you. Better than my workaround of creating views.

**Comment by rynowak** [comment]
No worries, we'd rather get dupes than unreported issues. Thanks!
