### ISSUE TITLE
Overriding Request Form max upload limit

### ISSUE THREAD

**Issue by muratg** [aspnet/Mvc#5128]
_From @Tratcher on May 27, 2016 18:33_

_From @Ryuuke on May 27, 2016 18:30_

Hello, 
I encountered this error when uploading large file (~200MB).

> An unhandled exception occurred while processing the request.
> Multipart body length limit 134217728 exceeded
> at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)

I already tried to modify my web.config file :
httpRuntime maxRequestLength="1073741824" executionTimeout="300000"
and requestLimits maxAllowedContentLength="1073741824"

but still, I get the same error.

I'm using the RC2 version, is there a way to override that limit ?

_Copied from original issue: aspnet/KestrelHttpServer#891_

_Copied from original issue: aspnet/HttpAbstractions#641_

**Comment by muratg** [comment]
_From @Tratcher on May 27, 2016 18:38_

There are limits on the request form. Where are you trying to read the Form, an MVC Controller/Action?

The limits can be adjusted per action like this:
https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Controllers/RequestFormLimitsController.cs#L19

Or for the whole app like this (but don't do this just for one file):
https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Startup.cs#L34

**Comment by muratg** [comment]
_From @davidfowl on May 27, 2016 18:40_

@Tratcher @Eilon @kichalla should that filter be built into mvc?

**Comment by muratg** [comment]
_From @Tratcher on May 27, 2016 18:42_

@rynowak Probably.

**Comment by muratg** [comment]
_From @Tratcher on May 27, 2016 18:43_

https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Filters/RequestFormSizeLimitAttribute.cs

**Comment by muratg** [comment]
_From @Ryuuke on May 27, 2016 19:7_

Hey, thanks for your reply, yeah i'm trying to read the form from the an MVC action, it was the MultipartBodyLengthLimit property inside the FormOptions that I updated to a larger value than the default and It Worked well.

**Comment by muratg** [comment]
_From @victorhurdugaci on July 6, 2016 22:16_

This is something that should be in MVC. cc @kichalla @rynowak

**Comment by muratg** [comment]
_From @Eilon on July 7, 2016 1:52_

Is this the same as https://github.com/aspnet/Mvc/issues/481?

**Comment by muratg** [comment]
_From @Tratcher on July 7, 2016 2:21_

Not quite, this is specific to forms.

**Comment by danroth27** [comment]
We should revisit what exactly we want to do here.

**Comment by rynowak** [comment]
What am I missing? We added upload limits to kestrel by default, and also added an override to MVC in a sample

**Comment by JunTaoLuo** [comment]
I think the proposal was to add a MVC filter to set the available form options here https://github.com/aspnet/HttpAbstractions/blob/8b3c308c226dd61532e543697d9d35bb94aba823/src/Microsoft.AspNetCore.Http/Features/FormOptions.cs. There is a sample in Entropy that illustrate this mentioned above but I think the discussion was whether we should polish that and ship it.

**Comment by jackfacts** [comment]
Setting the MutltiPartBodyLength on for both the whole application and via the attribute are working on a windows development machine, but when I publish to a Linux environment neither setting makes any difference. 

I still get the: An unhandled exception has occurred while executing the request Multipart body length limit 134217728 exceeded.

My settings look like 
      services.Configure<FormOptions>(x =>
                                            {
                                                x.ValueCountLimit = int.MaxValue;
                                                x.MultipartBodyLengthLimit = int.MaxValue;
                                            });


and 
        [RequestFormSizeLimit(valueCountLimit: int.MaxValue, multipartBodyLengthLimit: int.MaxValue, Order = 1)]

I added the attribute from the Entropy project and added the multiPartBodyLengthLimit argument.

**Comment by JasonRowe** [comment]
Upgraded my project to latest versions 1.1.1 along with the tooling upgrade in VS2017. The work around mentioned doesn't seem to work anymore. When I'm debugging I can see the options code gets run and the values are updated. The controller just doesn't seem to recognize the change.

Keep getting "Multipart body length limit 16384 exceeded." even though I have this in my startup.

```
			services.Configure<FormOptions>(options =>
			{
				options.ValueLengthLimit = int.MaxValue;
				options.MultipartBodyLengthLimit = long.MaxValue;
			});

			services.AddMvc()
				.AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
				.AddDataAnnotationsLocalization();
```

**Comment by jackfacts** [comment]
@JasonRowe, I ran into that issue earlier today, I upgraded a project to 1.1.1 yesterday. 

For me I believe having the RequestFromSizeAttribute on the method fixed the problem. I haven't had time to dig in and actually figure out what fixed it.

Heres an example:

 [HttpPost("api/[controller]/upload")]
 [RequestFormSizeLimit(500, 1024*1024*25)] //500 - ValueCount Limit, 25 MB MaxBodyPartLengthLimit
 public async Task<IActionResult> Upload(FileDescription fileDescription){...

**Comment by JasonRowe** [comment]
Also tried adding a form attribute with no luck. Nothing I do seems to effect the MultipartBodyLengthLimit. Anyone have a work around?

**Comment by JasonRowe** [comment]
I also tried the "DisableFormValueModelBindingAttribute" attribute from these old docs and it didn't help.

https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads


https://raw.githubusercontent.com/aspnet/Docs/master/aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Filters/DisableFormValueModelBindingAttribute.cs

**Comment by halter73** [comment]
@rynowak [Here are the Kestrel limits](https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.server.kestrel.kestrelserverlimits) that can be configured today.

While you can set absolute limits for the request line and request headers sizes, there is none for the request body. The MaxRequestBufferSize only limits the number of request body bytes that can sit in Kestrel's internal buffers without the app reading them before back pressure is applied.

**Comment by JasonRowe** [comment]
Not very helpful but suddenly I can't recreate my issue. I did change some settings that made my virtual machine run faster (added additional CPU's). Now I don't appear to need any settings in the startup and the same file works fine via the same form without changes.

**Comment by Tratcher** [comment]
Not if he can't reproduce it. It would be nice to make the sample filter/attribute a shipping thing.

**Comment by dhaligas** [comment]
@davidfowl this doesn't work in 1.1.1.  I cannot believe I can't upload a file in asp.net core over a certain size

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/MultipartReader.cs#L50

It is set to the default and fails here 

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/MultipartReaderStream.cs#L156

Any guidance?

**Comment by Eilon** [comment]
@rynowak / @Tratcher  - how does this relate to some of the limits work that we're doing right now?

**Comment by Tratcher** [comment]
This isn't directly related to IHttpMaxRequestBodySizeFeature, form has always had its own limits. But it does show why we need to do https://github.com/aspnet/Mvc/issues/6352 once there's a global body size limit.

**Comment by rynowak** [comment]
> how does this relate to some of the limits work that we're doing right now?

This is part of the limits work that we're doing right now. This is needed for 2.0

**Comment by Eilon** [comment]
Closing as dup of the newer bug https://github.com/aspnet/Mvc/issues/6352.

**Comment by Tratcher** [comment]
This is not a duplicate of #6352, this bug is about form size limits, not overall request body limits.

**Comment by trevordaniels** [comment]
I'm getting this error on 1.1.1 trying to upload large files in an mvc controller action.

`Multipart body length limit 16384 exceeded`
`at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)`

MultipartReader has a hard-coded HeaderLenghtLimit = 16384. It uses this to set MultipartReaderStream LengthLimit which is used to used to check the body length limit.
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/MultipartReader.cs#L50
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/MultipartReaderStream.cs#L156

There is no way to adjust this limit when using MultipartReader.

**Comment by Tratcher** [comment]
@trevordaniels what's the structure of your upload that includes 16kb of preamble data?

**Comment by trevordaniels** [comment]
Sorry my mistake, this error was caused by using two MultipartReaders. The first one was reading part of the request and tripping up the second reader when it tried to read the stream.

**Comment by rynowak** [comment]
OK, so it sounds like the original issue here is tracking productizing https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Filters/RequestFormSizeLimitAttribute.cs

I don't think we have a good reason to leave this out of the box.

/cc @eilon 2.1.0?

**Comment by Eilon** [comment]
Yeah.

**Comment by kichalla** [comment]
This was already implemented by @jbagga as part of this commit https://github.com/aspnet/Mvc/commit/17f6b17a6dc0e76606b091187a4e43a184656c89

**Comment by Tratcher** [comment]
Are you going to update https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Filters/RequestFormSizeLimitAttribute.cs now?

**Comment by kichalla** [comment]
Sure, good point.
