### ISSUE TITLE
OPTIONS request results in warning when enabling cors in MVC

### ISSUE THREAD

**Issue by karataliu** [aspnet/Mvc#5131]
After following the guidance for CORS:
https://docs.asp.net/en/latest/security/cors.html

The cors functionality works fine, but each OPTIONS request would result in following warning:
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 OPTIONS http://localhost:5000/api/values
warn: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Cors.CorsAuthorizationFilter'.
```

Request:
```
OPTIONS http://localhost:5000/api/values HTTP/1.1
Host: localhost:5000
Access-Control-Request-Method: GET
Origin: http://localhost
```

Looks like it is due to the CorsAuthorizationFilter sets context result, is it expected behaviour?

**Comment by rynowak** [comment]
Yes, it looks like the filter is behaving correctly - we need to fix the log output because it's misleading

**Comment by kichalla** [comment]
This looks like a dup of https://github.com/aspnet/Mvc/issues/5124 which was fixed by @ajaybhargavb recently

**Comment by kichalla** [comment]
Dup of https://github.com/aspnet/Mvc/issues/5124
