### ISSUE TITLE
Feature Request to Add GuestAttribute

### ISSUE THREAD

**Issue by ryanelian** [aspnet/Mvc#5132]
Some other languages' web frameworks have this feature, where a middleware causes certain routes to bounce if users are actually authenticated.

This is the implementation of the said attribute for ASP.NET MVC, but I could be wrong.

``` csharp
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
public class GuestAttribute : Attribute, IActionFilter, IAllowAnonymous
{
    public void OnActionExecuted(ActionExecutedContext context)
    {
    }

    public void OnActionExecuting(ActionExecutingContext context)
    {
        if (context.HttpContext.User.Identity.IsAuthenticated)
        {
            context.Result = new RedirectToActionResult("Index", "Home", null);
        }
    }
}
```

I think this is nice to have in ASP.NET MVC for decorating actions such as login and sign-up page.

Please? :D

**Comment by Bartmax** [comment]
I don't think it adds much value, it's easy enough to implement it if you really want it.

Also, I would let users login as another user even if they are logged in or present the option to logout than to restrict the access and blindly redirect.

**Comment by Eilon** [comment]
I'm curious - what's the scenario where you want an authenticated user to not be able to see content that doesn't require authentication?

We could certainly implement the feature, I'm just not sure what it's for.

**Comment by ryanelian** [comment]
> I'm curious - what's the scenario where you want an authenticated user to not be able to see content that doesn't require authentication?

Like the example I've given above, login and signup page.

For example, facebook.com, if logged in, won't let you see the sign up or the login page anymore and instead redirects you to home / timeline page. (http://www.facebook.com/login.php)

MANY other sites actually do this and I assume this is the golden standard for login page behavior in the internet:
- Bitbucket: https://bitbucket.org/account/signin/
- Gitlab: https://gitlab.com/users/sign_in
- Github: https://github.com/login
- Microsoft: https://login.live.com/

Therefore, there is a need to actually have an attribute that could perform redirection from the login / sign-in page if user is actually logged in, which ASP.NET MVC Core lacks.

**Comment by Tieantono** [comment]
> I don't think it adds much value, it's easy enough to implement it if you really want it.

> Also, I would let users login as another user even if they are logged in or present the option to logout > than to restrict the access and blindly redirect.

I agree with Ryan, never seen much websites that let you do login even after you've logged in into that website. Such famous website would never do something like that, I mean for what kind of purpose that you let the logged in user to do one more login procedure (unless you're on ATM, which you sometimes need to reinsert the PIN number for the verification).

**Comment by Eilon** [comment]
Closing because we aren't planning to add this feature.
