### ISSUE TITLE
How to setup a fallback resource file for all Views

### ISSUE THREAD

**Issue by biserkazinreich** [aspnet/Mvc#5136]
Using `IViewLocalizer `I would like to implement view localization with a default or fallback resource file for words and phrases that appear on multiple pages like for example edit, add, delete... I don't want to add these repetitive phrases in the resource file of all the views where they appear so a fallback recource file would really come handy, but I just can't seem to find any solutions on how to do that.

Currently I'm using `@inject IViewLocalizer Localizer` on my views and I'm getting the localized phrases with `@Localizer["ResourceName"]` from the resource files:

> Resources/Views/{ControllerName}/{ViewName}.{langCode}.resx

This works just fine for each separate view and partial view. Now I would like to have a resource file either in the `Resources/Views` or `Resources` folder that acts as a fallback resource file.

So for example if I say `@Localizer["Edit"]` on one of my views and the "Edit" resource is not found in the `Resources/Views/{ControllerName}/{ViewName}.{langCode}.resx` or `Resources/Views/{ControllerName}/{ViewName}.resx`, it falls back to a default file so that I can use this on all of my views that need the resource "Edit".

**Comment by ryanbrandenburg** [comment]
@biserkazinreich is there a reason you couldn't have 
```
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedResource> SharedLocalizer
```
and then just use whichever is appropriate? That doesn't give you fallback from the view to the Default resource, but you can easily choose which to use for each localization. If you must have fallback you could write your own `IStringLocalizerFactory` and `IStringLocalizer` similar to how we did [here](https://github.com/aspnet/Entropy/tree/dev/samples/Localization.CustomResourceManager) which do fallback. I don't imagine this is a feature we would want to add to our default experience though, but perhaps @Eilon or @DamianEdwards disagree.

**Comment by biserkazinreich** [comment]
@ryanbrandenburg Ok, thank you. That seems like an acceptable solution for my situation.
I'm just having some problems getting the IHtmlLocalizer<SharedResource> to work, but I will open a separate issue regarding that.

**Comment by ryanbrandenburg** [comment]
In that case I'll close this out.
