### ISSUE TITLE
preserveCompilationContext causing failed references for runtime compilation

### ISSUE THREAD

**Issue by Antaris** [aspnet/Mvc#5141]
Hi,

I am having some issues performing an upgrade from RC2 and RTM. I have a set of libraries deployed to an internal NuGet feed, they have `preserveCompilationContext` set to true. This is mostly because we don't have any clear indication as to whether we are supposed to include that in all projects, or just host projects? `preserveCompilationContext` generates a `.deps.json` file describing the dependency tree for that library.

Now, in my host MVC application, the `MetadataReferenceFeatureProvider` is generating metadata references for the Roslyn-based Razor compiler. 

So, given an example dependency `My.Application.Abstractions`, what I am finding, is that for those assemblies that exist in packages, it is trying to load the `DependencyContext` for each one. Because of the `preserveCompilationContext` setting in the `project.json` project file of the source dependency, there is an entry in the `.deps.json` file:

```
{
  // .deps.json shorted for brevity
  "libraries": {
    "My.Application.Abstractions/1.0.0-master": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```
Now, when iterating through the `DependencyContext.CompileLibraries` property to resolve the reference paths, because the `type` key is set to `project`, it means the `PackageCacheCompilationAssemblyResolver` is skipped (https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.Extensions.DependencyModel/Resolution/PackageCacheCompilationAssemblyResolver.cs#L39) and in the `AppBaseCompilationAssemblyResolver` (https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.Extensions.DependencyModel/Resolution/AppBaseCompilationAssemblyResolver.cs#L93) the only directory specified is the application output `./bin/debug/netcoreapp1.0` which doesn't contain the package assembly. Additionally the `PackageCompilationAssemblyResolver` returns `false` because the compilation library is of type `project`. This has a the net result of failing to obtain a reference at all, giving this lovely exception:

`Can not find compilation library location for package `My.Application.Abstractions'

So I have a couple of questions:

1. When using `preserveCompilationContext` in a library, should it be generating `project` as the `type` value?
2. Should we be using `preserveCompilationContext` at all, what are the exact scenarios this *should* be used and for what types of projects?
3. How do I solve my current issue.

It's difficult to try and generate a working example that I can upload, but if I can, I'll update this issue.

I've cross-posted this over at dotnet/CLI (https://github.com/dotnet/cli/issues/4047) as I am unsure as to where this belongs.

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by danroth27** [comment]
The `preserveCompilationContext` option is used to when your app needs to do runtime compilation, and therefor needs to know what to compile against. This option is not needed at all for libraries.

Can you share with us your solution so that we can take a look at what you are trying to do?

**Comment by pranavkm** [comment]
> When using preserveCompilationContext in a library, should it be generating project as the type value?
Most likely not. Seems like a bug and https://github.com/dotnet/cli/issues/4047 could be used to address this.

> Should we be using preserveCompilationContext at all, what are the exact scenarios this should be used and for what types of projects?
`preserveCompilationContext` has two purposes - 

1. It's used to detect what libraries reference Mvc. By default, we specifically look for Mvc specific types, such as Controllers and ViewComponents, in these libraries. 
2. It's used to detect the closure of libraries used to compile the application assembly. This is used to compile views. 

In the most common cases, you shouldn't be using `preserveCompilationContext` in class libraries, just the main application. There might be scenarios around runtime loaded assemblies that require this flag, but it shouldn't be entirely common.

> How do I solve my current issue.
Does removing `preserveCompilationContext` help?

**Comment by Antaris** [comment]
@danroth27  @pranavkm 

Thanks for your feedback. It's now clear to me the use cases for `preserveCompilationContext` and removing it corrects my issue.

I'm using `DependencyContext` in a similar way to MVC, but instead of locating application parts I am using it to locate modules.

Perhaps the `project` type flag should be driven by the presence of `emitEntryPoint` in the build options?

**Comment by pranavkm** [comment]
Perhaps. The alternative might be for DependencyContext to fallback to packages when type is project.
