### ISSUE TITLE
Correctly accept all json and xml media subtypes

### ISSUE THREAD

**Issue by lvermeulen** [aspnet/Mvc#5143]
Currently the json and xml input and output formatters accept only ~/json and ~/xml mediatypes by default. As per [RFC 6839 (json)](https://tools.ietf.org/html/rfc6839#page-4) and [RFC 3023 (xml)](https://tools.ietf.org/html/rfc3023#page-32) all +json and +xml subtypes should be regarded as such. Otherwise many [IANA registered media types](http://www.iana.org/assignments/media-types/media-types.xhtml) will not be handled correctly. This means that application/[...]+json and application/[...]+xml should also be supported by default.

I would submit a PR, but it seems like I would need to create a HttpHeaderParser<MediaTypeHeaderValue> type that can deal with this. That seems ... complicated. :-/

**Comment by Eilon** [comment]
Closing this as a dup of https://github.com/aspnet/Mvc/issues/5273, even though this was opened first (thanks!), but the other issue by now has more discussion. Can you have a look at https://github.com/aspnet/Mvc/issues/5273 and see if you have any further thoughts on it? Thanks!
