### ISSUE TITLE
Autodiscovery and compilation of Razor views via embedded providers

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#5144]
Consider supporting Razor views as embedded resources out of the box.

**Comment by Antaris** [comment]
I'd be interested to know how you plan to enable debugging for these embedded views? I'm already supporting embedded views in my ASP.NET Core app, but can't easily debug them.

**Comment by pranavkm** [comment]
@Antaris an option we were exploring here was to rely on a Roslyn feature that would allow us to embed sources for views in generated pdbs. Here's the discussion for it - https://github.com/dotnet/roslyn/issues/12625. Note: the feature hasn't landed and requires follow up work in the debugger to know how to get to these sources, so it'll be a while for the feature to light up.

At present, you have to point to files on disk for the debugger to find them. You could consider using a `PhysicalFileProvider` that points to the source project when developing locally and switching to an embedded one when you're deploying.

**Comment by Eilon** [comment]
Given that we have good support for pre-compiling Razor views, we are closing this issue.
