### ISSUE TITLE
ModelBindingContext.ValueProvider using [FromBody]

### ISSUE THREAD

**Issue by jeanjn** [aspnet/Mvc#5146]
I have a custom ModelBinder to fill my model and my action in controller receive the data [FromBody] of request by post using ajax.

The problem is: If I send the data using "params" (queryString), the valueProvider works well, but if I send using "data" (body of request), the valueProvider is empty.

So, how can I get the data from body in my custom modelbinder?

The ValueProvider has two providers: RouteValueProvider and QueryStringValueProvider, Maybe a solution is implement and set a new ValueProvider to consider FromBody, but if this is a solution, how can I implement it?

**Comment by pranavkm** [comment]
@jeanjn the default set of value providers get data from query string, route data and form posts. FromBody is handled by input formatters which is responsible for creating the object instance in entirety. 

What is that you're trying to do with a custom ModelBinder that doesn't work out of the box?

**Comment by imranbaloch** [comment]
FWIW, you can read the body like https://github.com/aspnet/Mvc/issues/4962 or https://long2know.com/2016/08/net-core-middleware-request-processing/ but EnableRewind is in internal namespace :).

        public async static Task<T> ReadAsAsync<T>(this HttpContext context)
        {
            var initialBody = context.Request.Body; // Workaround
 
            context.Request.EnableRewind();
            var buffer = new byte[Convert.ToInt32(context.Request.ContentLength)];
            await context.Request.Body.ReadAsync(buffer, 0, buffer.Length);
            var json = Encoding.UTF8.GetString(buffer);
 
            context.Request.Body = initialBody; // Workaround
 
            T retValue = JsonConvert.DeserializeObject<T>(json);
            return retValue;
        }

**Comment by danroth27** [comment]
If you want to use a custom model binder, then you shouldn't use `[FromBody]`. Only formatters are used when a parameter is marked as `[FromBody]`.

**Comment by MaitreDede** [comment]
Hi,

In my case, I post some JSON data to a controller with a single parameter typed as an abstract class. I would like to use a custom model binder to produce the real class type.

What is the right way to do ?

**Comment by dougbu** [comment]
@MaitreDede FYI comments on closed bugs aren't very visible. Your question also seems only slightly related to this issue.

In any case, I recommend creating a custom model binder and associated provider which work similarly to `BodyModelBinder` and `BodyModelBinderProvider`. The provider might instead match on the parameter type instead of the binding source. The binder would pass different `ModelMetadata` in the `InputFormatterContext` than `BodyModelBinder` in the same situation. Your custom binder needs to request an instance of a concrete type. Up to your binder or the provider to determine the concrete type.

What have you tried and what doesn't work?

**Comment by himadrinath** [comment]
@imranbaloch @pranavkm @danroth27 @dougbu 

What are the bast way to read from a View Form post?

is it **bindingContext.ActionContext.HttpContext.Request.Form** or any other options

**Comment by davidfowl** [comment]
Use `ReadFormAsync()` avoid using `Form`

**Comment by himadrinath** [comment]
@davidfowl Thanks

**Comment by jeanjn** [comment]
ReadFormAsync not works because the view send data using json. I not found a solution yet to send data in the body of request and consume in ModelBinder. Until today anybody find a solution?

**Comment by rynowak** [comment]
Please start at https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding

If that doesn't answer your questions please open a new issue and describe what you are you accomplish.
