### ISSUE TITLE
If user submit price value (decimal / int) empty from view, server side model validation show wrong message.

### ISSUE THREAD

**Issue by mukundabrt** [aspnet/Mvc#5148]
There is issue found on model validation server side.

public string Genre { get; set; }
public decimal Price { get; set; }

If user submit price value empty from view, server side model validation show wrong message  ie. the value "" is not valid.

I have checked in controller, the incoming model is showing price value 0 as default but ModelState getting rawValue="". so conflicting with datatype and throw msg.
Please resolve the above issue.

**Comment by dougbu** [comment]
The `SimpleTypeModelBinder` detects that `string.Empty` cannot be converted to a `decimal` value and adds the error you see. What is the issue?

**Comment by mukundabrt** [comment]
ok SimpleTypeModeBinder is detecting string.empty
but model is carring 0 as default (even user submit with empty)   so should validate with 0 not with "" (string.empty).

decimal / int is alwasys getting 0 as default value.

Thanks for prompt reply

**Comment by dougbu** [comment]
We're talking about a model binding error -- some invalid data on the wire gets caught up front. Validation and default values for properties that aren't assigned aren't relevant here.

**Comment by mukundabrt** [comment]
MVC5 is working fine in this. why not working in MVC6? any new idea impleteded in 6?

**Comment by dougbu** [comment]
Either MVC 5 did not show the same error in this situation or it didn't catch the error. Either way, the MVC 6 behaviour is correct -- the submitted value `""` is not valid for a `decimal` property.

More generally why do you prefer a different behaviour? What is your overall scenario that requires this problem _not_ be caught?

For example, if you prefer the model binding problem is ignored, clear the errors for that property in the `ModelStateDictionary`.

**Comment by mukundabrt** [comment]
Thank u very much. Problem solved
I have identified the cause of problem.
