### ISSUE TITLE
Master detail crud operation form creation difficulties .

### ISSUE THREAD

**Issue by mukundabrt** [aspnet/Mvc#5149]
**Developers are getting very difficulties to create master detail crud operation in MVC
with detail table inline editing and bind with detailmodel.**

So many customization and javascripting are required to complete the goal.
I have googled regarding this but still not getting satisfactory result.

If mentined feature or tag helper  available in mvc, it will be more fruitful and easy.

Thanks =D

**Comment by davidfowl** [comment]
Do you have a specific request or are you just asking for us to make it easier?

**Comment by mukundabrt** [comment]
I am just requesting to development community to add feature or tag helper for master detail crud with inline editing table.

**Comment by danroth27** [comment]
Scaffolding will at least give you support for CRUD operations. Check out https://docs.asp.net/en/latest/tutorials/first-mvc-app/index.html to get started.
