### ISSUE TITLE
ASP.NET Core MVC Razor Issue

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/Mvc#5151]
In my ASP.NET Core web app, in the default _LoginPartial view, if I put just a `true` keyword in the `if statement` below it ignores the entire `if{...}` block. **NOTE**:  My real scenario is a bit more complex but for the sake of reporting the issue, I've simplified the scenario here. In the real scenario, I want to replace hard coded `true` with `User.IsInRole("AdminRole")` to display the `if block` contents only if the logged-in user is in AdminRole. But even the following simple scenario is not working:

**_LoginPartial view**:

![capture](https://cloud.githubusercontent.com/assets/10931726/17716126/6f8e4000-63d5-11e6-805b-538976acef47.PNG)

**Comment by NTaylorMullen** [comment]
@saf-itpro there must be some other issue happening when you log in. I tried the same thing on File => new Web Application and did the following in the `_LoginPartial.cshtml`:

![image](https://cloud.githubusercontent.com/assets/2008729/17717384/8b228e42-63c2-11e6-9408-a4a0d51e1aa3.png)


With this, when I log in I get the following:
![image](https://cloud.githubusercontent.com/assets/2008729/17717401/a2905884-63c2-11e6-9e78-95c9641535c2.png)

Which is expected.

**Comment by saf-itpro** [comment]
@NTaylorMullen You are correct. `Hello UserName` was hiding behind an image. After reading your response, I searched for it and found it out behind the image. Thank you for taking your time to help. I'm closing the issue.

**Comment by NTaylorMullen** [comment]
@saf-itpro Glad I could help :+1:
