### ISSUE TITLE
ExcelDataReader for mvc not working in Asp.Net Core 1.0

### ISSUE THREAD

**Issue by ermithun** [aspnet/Mvc#5152]
ExcelDataReader for mvc not working in Asp.Net Core 1.0

Need Help

**Comment by davidfowl** [comment]
I assume you mean this package https://www.nuget.org/packages/ExcelDataReader/? What doesn't work? Are you using ASP.NET Core on .NET Framework or ASP.NET Core on .NET Core?

**Comment by ermithun** [comment]
hi @davidfowl ,   ya  I am developing project using Asp.Net Core and facing this problem how to read excel data in latest .net Core version .
ExcelDataReader.dll  is supporting in .Net Core.

 Need your support

**Comment by davidfowl** [comment]
I don't know what you need. Are you trying to figure out how to use the library in general? Have you used the library before? Have you used it in ASP.NET 4.x? What are you having problems with?

**Comment by damienbod** [comment]
The ExcelDataReader library is a .NET library

**Comment by ermithun** [comment]
@davidfowl 
Thank you for you quick response.

I want to  read uploaded excel data and bind in model and return view  in .net mvc core

**Comment by danroth27** [comment]
This is not an ASP.NET Core MVC issue. Please post your question at https://github.com/ExcelDataReader/ExcelDataReader.
