### ISSUE TITLE
Visual Studio 2015 Export Template Not Working

### ISSUE THREAD

**Issue by TLHamilton** [aspnet/Mvc#5153]
In Visual Studio 2015 I will create a new project File>New>Project>Templates>Visual C#>Web>ASP.NET Core Web Application (.Net Framework).

Once created, I will export a template from the project File>Export Template.

When I try to use this template to create another new project, none of the Template contents shows up.

I have seen a few comments about this on the web, but have not found a solution.

Is this a known problem?  Is there a solution or work around?

Thanks.

**Comment by ThoughtHaven** [comment]
I haven't verified this, but someone may have found a [work around](https://github.com/aspnet/Tooling/issues/306#issuecomment-195498755). Hope this works for us both.

**Comment by TLHamilton** [comment]
Sorry, but I could not get it to work when this work around was purposed and I still cannot get it to work.

I would be very interested if someone can verify this.

**Comment by ThoughtHaven** [comment]
Didn't work for me either, unfortunately. It'll be nice when somebody gets this working.

**Comment by danroth27** [comment]
This issue was moved to aspnet/Tooling#732
