### ISSUE TITLE
Exception thrown if WebHostBuilder config's application name does not correspond to an assembly name

### ISSUE THREAD

**Issue by kierenj** [aspnet/Mvc#5155]
Steps to repro:

1. Configure WebHostBuilder with `.UseSetting(WebHostDefaults.ApplicationKey, "Something")`
2. Ensure `Something.dll` does not exist
3. Call `.AddMvc()` on corresponding `IServiceCollection`

Outcome:

```
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.ni.dll

Additional information: Could not load file or assembly 'Something, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

The docs - https://docs.asp.net/en/latest/fundamentals/hosting.html - don't mention that Application Name is used for loading assemblies.

A bug in the docs or a bug in MVC?

**Comment by davidfowl** [comment]
It's not a bug, it's by design. Sure we can update the docs. What were youa actually trying to do?

**Comment by kierenj** [comment]
My guess would be the Application Name would be useful for different modules sitting on ASP.NET to know the name of the application for error messages, logging, etc.  At least, that's my use case - I'm looking to use `IHostingEnvironment.ApplicationName` for alert emails etc from the app framework I'm building.

To be honest there's already a "Startup Assembly" key - that kind of sticks out as something that specifies an assembly, would it be better to call this "Application Assembly" if that's what it's used for?

(I just found https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Hosting/IHostingEnvironment/ which explains it, but it seems a bit of a hack - like the host would set this to the startup assembly name /by default/ so that you have an Application Name to work with if you don't override... then MVC happens to pick up this string which defaults to an assembly name later on?)

**Comment by davidfowl** [comment]
> My guess would be the Application Name would be useful for different modules sitting on ASP.NET to know the name of the application for error messages, logging, etc. At least, that's my use case - I'm looking to use IHostingEnvironment.ApplicationName for alert emails etc from the app framework I'm building.

Seems fine. Just don't set it. It's possible we should have made it get only. Ah well.

> To be honest there's already a "Startup Assembly" key - that kind of sticks out as something that specifies an assembly, would it be better to call this "Application Assembly" if that's what it's used for?

That's used in very narrow scenarios where you want to change the Startup assembly. It doesn't flow out of Hosting either.

**Comment by kierenj** [comment]
@danroth27 if you don't mind me saying so, updating the docs might still be a good idea?  I've copied an excerpt from https://docs.asp.net/en/latest/fundamentals/hosting.html below, which really does make it seem like ApplicationName can be used ad-hoc, doesn't depend on an assembly with that name existing, and won't throw exceptions?  

## Configuring a Host

The WebHostBuilder provides methods for setting most of the available configuration values for the host, which can also be set directly using UseSetting and associated key. For example, to specify the application name:

```c#
new WebHostBuilder()
    .UseSetting("applicationName", "MyApp")
```

### Host Configuration Values
**Application Name string**
Key: `applicationName`. This configuration setting specifies the value that will be returned from `IHostingEnvironment.ApplicationName`.

**Comment by danroth27** [comment]
@kierenj Yup, I totally agree: https://github.com/aspnet/Docs/issues/1870

**Comment by Vedant-Koditkar** [comment]
I have also tried this but it was giving me same reflection error.
As it always going to throw an exception why can't we make changed to docs and even if possible not allow the user to set this property in first place??

**Comment by danroth27** [comment]
@Vedant-Koditkar Setting the property is still useful for cases where you want to specify the assembly that the dependency context should be loaded from.
