### ISSUE TITLE
Question about TagHelper

### ISSUE THREAD

**Issue by ipjohnson** [aspnet/Mvc#5156]
Is there any documentation or examples showing subproperties being used in a TagHelper. I'm working with a 3rd party vendor and they are looking for some clarity on what exactly is supported and not supported. 

Example:
```
<label asp-for="Property.SubProperty">
<input asp-for="Property.SubProperty"/>
```

Also I was looking to clarify if list syntax is supported by TagHelper

```
<label asp-for="ListProperty[i].PropertyA"></label>
<input asp-for="ListProperty[i].PropertyA"/>
```

**Comment by NTaylorMullen** [comment]
@ipjohnson There's no specific documentation. As for sub-properties, they should just work. Is there something you're seeing that makes think otherwise?

**Comment by ipjohnson** [comment]
No actually I'm fully under the belief that this is functionality that works and is fully supported. It's actually the vendor that for what ever reason is asking for examples as proof that this functionality is supported.

Hopefully your reply will be enough for them to believe this is supported functionality.

**Comment by ipjohnson** [comment]
I'm going to close this, thanks for the help
