### ISSUE TITLE
Port fix for Html.ValidationSummary when model binding a collection

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#5157]
Bug: https://github.com/aspnet/Mvc/issues/4989

**Comment by Eilon** [comment]
@sebastienros @dougbu hmm did we miss this for 1.0.1? Should we try to get this into 1.0.2?

cc @danroth27

**Comment by dougbu** [comment]
I double-checked the rel/1.0.1 branch and e5cb6f9 is definitely not included. So, yes, we missed it for 1.0.1.

Looks like the issue never got assigned. Agree we should aim for 1.0.2.

**Comment by Eilon** [comment]
Yay, our first MVC 1.0.2 bug 😄

**Comment by Eilon** [comment]
@dougbu this patch is **approved**, please ensure it is merged into the correct branch and building as part of the patch train.

**Comment by dougbu** [comment]
f8f9bbc
