### ISSUE TITLE
Question about migrating to ASP Net Core / Controller Versioning

### ISSUE THREAD

**Issue by peterlazzarino** [aspnet/Mvc#5158]
Hey, hope I can get a little bit of insight here. Trying to implement controller versioning through namespaces. An example being folders v1 and v2 each having a controller with the same name. This won't work natively of course but I was hoping to be able to either do this through routes or by possibly overriding the ActionSelector class. I have tried implementing my own and registering it as an IActionSelector but it doesn't seem to work. Not sure if this is possible at this point but it seems like in previous versions of .NET by having a custom IHttpControllerSelector. Thanks!

**Comment by rynowak** [comment]
Please take a look at https://github.com/aspnet/Mvc/tree/dev/test/WebSites/VersioningWebSite

Implementing your own `IActionConstraint` is the right way to do this, and you can use a convention to apply the constraint to controllers/actions as you see fit.

Also see https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRoutingConvention

**Comment by peterlazzarino** [comment]
thanks so much for the help. Got it working using the second example by creating a new IApplicationModelConvention. ![bitmoji](https://render.bitstrips.com/v2/cpanel/9666023-115933825_7-s1-v1.png?transparent=1&width=246)

**Comment by rynowak** [comment]
Awesome, glad we could help.
