### ISSUE TITLE
Generic method RedirectToAction<TController> isn't working properly

### ISSUE THREAD

**Issue by ferry2** [aspnet/Mvc#5163]
Recently I tried to use the generic method RedirectToAction to redirect to the Contact action of the HomeController, but instead of redirecting to **localhost:11822/Home/Contact** I was redirected to url: **localhost:11822/T/Contact**.

Here is my code:

`RedirectToAction<HomeController>(c => c.Contact())`

**Comment by pranavkm** [comment]
Are you using a 3rd party library that has the generic `RedirectToAction` method? It's not part of Mvc's API.

**Comment by ferry2** [comment]
Yes, you're right. It comes from a third party library.

**Comment by ivaylokenov** [comment]
@ferry2 Is the extesion method from https://github.com/ivaylokenov/AspNet.Mvc.TypedRouting ?

**Comment by ferry2** [comment]
@ivaylokenov it's from other library. Never mind :).
