### ISSUE TITLE
DataAnnotationLocalizerProvider not called when configured via DI-registered MvcDataAnnotationsLocalizationOptions

### ISSUE THREAD

**Issue by c-s-n** [aspnet/Mvc#5165]
### Title
A `DataAnnotationLocalizerProvider` lambda is not called for any localizable annotation when configured via dependency injection-registered `MvcDataAnnotationsLocalizationOptions`.

### Functional impact
For our project there should be one central set of language resource files, and not one per class where localization is used. Thus we have a dummy class that is used as the typeparam for any injected `IStringLocalizer`. For the data annotations we want the same and thus configured the `DataAnnotationLocalizerProvider` to have the factory always create a localizer for this dummy class.

For structuring the code, we so far used the pattern of configuring options for middlewares and services separately, that is not passing it directly to the extension method, but registering them with the DI container.

This does not fully work with the `MvcDataAnnotationsLocalizationOptions`, in the sense that a set `DataAnnotationLocalizerProvider` is not invoked when requests happen that load a model having appropriate annotations. The lambda for configuring the options is however executed and the property also set correctly.

The pattern of passing the options directly to the `AddDataAnnotationsLocalization` method works though.

### Minimal repro steps
````
services.Configure<MvcDataAnnotationsLocalizationOptions>(options =>
{
    options.DataAnnotationLocalizerProvider =
        (type, localizerFactory) => localizerFactory.Create(typeof(Localization.SharedStrings));
}

services.AddMvc()
    .AddViewLocalization()
    .AddDataAnnotationsLocalization();
````

```
public class MyViewModel
{
    [Required(ErrorMessage = "test1")]
    [EmailAddress(ErrorMessage = "test2")]
    public string Email { get; set; }
}
```

### Expected result
`DataAnnotationLocalizerProvider` being called and causing strings to be loaded from `Localization.SharedStrings.<culture>.resx`.

### Actual result
`DataAnnotationLocalizerProvider` not called and causing strings to be loaded from default convention-based `<namespace>.MyViewModel.<culture>.resx`.

### Notes
This works as expected when configured like this:
```
services.AddMvc()
    .AddViewLocalization()
    .AddDataAnnotationsLocalization(options =>
    {
        options.DataAnnotationLocalizerProvider =
            (type, localizerFactory) => localizerFactory.Create(typeof(Localization.SharedStrings));
    });
```

### Further technical details
* Visual Studio 2015 with IIS Express
* Windows 10
* .NET Framework 4.5.2 target
* ASP.NET Core 1.0.0

**Comment by danroth27** [comment]
@rynowak What's the expected behavior here?

**Comment by Eilon** [comment]
The reason the bottom code works and the top code doesn't work is that the various "option setup" actions are *all* called, in sequence. So your code correctly sets up the options, but then a moment later MVC's default implementation gets called and overwrites the delegate you set with its own delegate that has different behavior.

So you can either:
1. Use MVC's option builder to set the delegate (this is the recommended pattern)
2. Set your options *after* MVC, in which case both option setup actions will run, but yours will run last, and will "win"
