### ISSUE TITLE
Make ScriptTagHelper work with defer and async script tags.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#5168]
[Script tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) have the ability to provide an async/defer attribute to modify the timing on when they're loaded into the page. This behavior breaks our expectations for our `ScriptTagHelper` and you end up with both the base script and the fallback script loaded.

We should design a route for our script load detection logic to work when these two parameters are present.

**Comment by Eilon** [comment]
@NTaylorMullen @DamianEdwards any chance of us actually doing something here? Is the answer that if you need to do more advanced `<script>` tags then just use a proper script loader?

**Comment by NTaylorMullen** [comment]
We could potentially do something here but the "right" thing would have to be investigated. That ranges from collecting script tags on a page and then collectively rendering them or changing our script injection logic to utilize the DOM. Both these solutions become possible once defer/async come into the picture. Doing this also depends on if we want to invest the time because your latter suggestion is also accurate.

**Comment by Eilon** [comment]
Yeah I have a feeling that if our script tag helper has to render like 10-15 lines of complex JS code then this isn't the right avenue...

**Comment by DamianEdwards** [comment]
What if we **only** do these things if the `defer` or `async` attributes are set? As in, we leave the current behavior as is, but if we see `defer` or `async` we collect up the scripts and load them at the end of the page (via a new `<body>` Tag Helper or similar), using the DOM. We could even make the logic that does this pluggable so folks can easily plug in something that emits different client-side logic for various script loaders.

**Comment by Eilon** [comment]
Is this even worth it then? Just don't use our tag helpers? We could certainly build an extensibility system but it seems easier to just write the code yourself... or write your own tag helpers... ?

**Comment by DamianEdwards** [comment]
Yeah it might be better to just tackle the addition of `<head>`, `<body>`, etc. Tag Helpers such that it's easy for people to create whatever script/asset collection helpers they want.

**Comment by Eilon** [comment]
Given our plans in https://github.com/aspnet/Mvc/issues/5728 to improve the experience of adding scripts in general, I'm closing this issue.
