### ISSUE TITLE
Accessing base model object from EditorTemplates

### ISSUE THREAD

**Issue by bfolder2001** [aspnet/Mvc#5171]
There seems to be some inconsistency in accessing the root model object from within an editor template. 

With a `string` or `decimal` type it's possible to get at the root model via `ViewData.ModelExplorer.Container.Model`

With a `decimal?` type there is no `ViewData.ModelExplorer.Container` object at all and I can't see any reference back to the root model.

Is there a reason for the inconsistency? Is accessing the root model from within an EditorTemplate something that is intended to be supported?

**Comment by danroth27** [comment]
@dougbu

**Comment by dougbu** [comment]
@bfolder2001 the cases you've outlined should be consistent. We don't make much use of the `Container` property but it should work for all properties. That said, `Nullable<T>` may still have a few oddities.

What is your exact scenario? Anything like the following?
``` c#
public class Model
{
    string StringProperty { get; set; }
    decimal DecimalProperty { get; set; }
    decimal? NullableProperty { get; set; }
}

...
// In Index.cshtml
@model Model
@Html.EditorFor(m => m.StringProperty)
@Html.EditorFor(m => m.DecimalProperty)
@Html.EditorFor(m => m.NullableProperty)

...
// In Decimal.cshtml and String.cshtml
@ViewData.ModelMetadata.ContainerType?.FullName
@ViewData.ModelExplorer.Container?.ToString()
```

**Comment by bfolder2001** [comment]
@dougbu Replace the `Index.cshtml` code with `@Html.EditorForModel()` and that's it in essence, yes.

**Comment by bfolder2001** [comment]
If it helps, putting the following code in my `EditorTemplates\Decimal.cshtml` and having a model with just two `decimal` properties, the first standard and the second nullable:

```
@model Decimal
<div>Model: @Model.GetType()</div>
<div>ContainerType: @ViewData.ModelMetadata.ContainerType?.FullName</div>
<div>Container: @ViewData.ModelExplorer.Container?.ToString()</div>
```

Gives the following output:

```
Model: System.Decimal
ContainerType: Project.ViewModels.TestViewModel
Container: Microsoft.AspNetCore.Mvc.ViewFeatures.ModelExplorer

Model: System.Decimal
ContainerType:
Container:
```

**Comment by dougbu** [comment]
This behaviour _might_ make sense if you are using `@model decimal` instead of `@model decimal?`. The template's model should be compatible with all expressions outer views may use.

If that doesn't work, let me know. I'll debug the scenario later today.

**Comment by bfolder2001** [comment]
@dougbu Yes, that does make sense, and I can confirm everything works fine when the model type on the `Decimal.cshtml` is set to `decimal?`. Makes a lot of sense in retrospect, thank you!

**Comment by dougbu** [comment]
Glad we got it figured out.
