### ISSUE TITLE
Async resource filters' short circuited result getting executed more than once.

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#5175]
This issue does not happen with sync filters.

Following PR (is a diff between 1.0 branch code) shows the potential changes that are required in ControllerActionInvoker:
https://github.com/aspnet/Mvc/pull/5174

@rynowak 

This issue happens with latest dev branch too.

**Comment by rynowak** [comment]
Does this happen in 1.0.0 or only in 1.1.0?

**Comment by kichalla** [comment]
> Does this happen in 1.0.0 or only in 1.1.0?

It happens in both.

**Comment by Eilon** [comment]
Not sure this meets the bar for a patch release because we're not aware of this being a broad problem. But if we do get hints of it being broader, we will reevaluate.
