### ISSUE TITLE
Expand cookie configuration options

### ISSUE THREAD

**Issue by andresdsep** [aspnet/Mvc#5176]
Previously, it was possible to configure security attributes to cookies through several means:

http://stackoverflow.com/q/5978667/4918323

Now however, options are very limited as to what can be done to secure cookies, aside of at the moment of creation.

**Comment by rynowak** [comment]
Please open an issue on the aspnet/Security repo and describe what you think needs to be improved. The configuration of cookie auth isn't part of MVC.
