### ISSUE TITLE
Deep debugging with symbols in VS

### ISSUE THREAD

**Issue by lobster2012-user** [aspnet/Mvc#5180]
I want to debug asp net source code (i use nuget)
I try some source server urls. Unsuccessfully.
Add please .PDB files on any symbol server if it not exists.
Thanks.

**Comment by pranavkm** [comment]
@lobster2012-user, we have symbols for our RTM builds available on  https://dotnet.myget.org/F/aspnetcore-master/symbols/. An alternative to using symbols is to use global.json to link to the cloned Mvc repo. This will compile your application against Mvc's sources which would help in cases where the compiler has optimized away chunks of code. https://blogs.msdn.microsoft.com/webdev/2015/02/06/debugging-asp-net-5-framework-code-using-visual-studio-2015/ is a blog post that uses RC1 + DNX, but you should be able to do something similar with RTM + dotnet.

**Comment by pranavkm** [comment]
Follow up work item to enable this for nightlies is here - https://github.com/aspnet/Coherence/issues/124

**Comment by lobster2012-user** [comment]
@pranavkm 
Hm, Routing Hosting StaticFiles missed in
https://dotnet.myget.org/F/aspnetcore-master/symbols/.

**Comment by pranavkm** [comment]
They same to be there
* https://dotnet.myget.org/feed/aspnetcore-master/package/nuget/Microsoft.AspNetCore.Routing
* https://dotnet.myget.org/feed/aspnetcore-master/package/nuget/Microsoft.AspNetCore.Routing.Abstractions
* https://dotnet.myget.org/feed/aspnetcore-master/package/nuget/Microsoft.AspNetCore.StaticFiles

etc (check the symbols node)

**Comment by lobster2012-user** [comment]
@pranavkm 
Yes, all ok. Thanks!
