### ISSUE TITLE
OutputFormatterWriteContext.WriterFactory is not generic enough.

### ISSUE THREAD

**Issue by jterry75** [aspnet/Mvc#5183]
Hello, I am in need of some assistance/feedback when it comes to building custom third party Output/Input formatters that work on binary protocols such as Microsoft Bond or Google Protobuf.

It seems like there is a logical issue from the most basic level of the stack. Here is my best attempt at explaining what I think is a problem:

``` C#
interface IOutputFormatter
{
    Task WriteAsync(OutputFormatterWriteContext context);
}

class OutputFormatterWriteContext : OutputFormatterCanWriteContext
{
    public virtual Func<Stream, Encoding, TextWriter> WriterFactory { get; protected set; }
}

class OutputFormatter : IOutputFormatter, IApiResponseTypeMetadataProvider
{
    public abstract Task WriteResponseBodyAsync(OutputFormatterWriteContext context);
}
```

As you can see from the above code snippets from the very root `IOutputFormatter` a user is not given any ability to use anything other than `OutputFormatterWriteContext` which hard codes the assumption that it is a `TextWriter`. 

Unfortunately .NET does not have `BinaryWriter` and `TextWriter` in any inheritance chain nor do they implement any interface that can be shared for a generic writer. So its unclear to me without introducing a ton of generic's classes how to share a single `IOutputFormatter` interface. Likely a second interface `IBinaryOutputFormatter` will need to be introduced and overloads supplied for the cases when the services have this type registered. 

---

Before I go off prototyping this in I just wanted to see if anyone had thought of this yet or if I was missing something. Thanks!

**Comment by rynowak** [comment]
`OutputFormatterWriteContext` includes the `HttpContext` associated with the current request, you should be able to use `context.HttpContext.Response.Body` if you want to write directly to the stream.

**Comment by jterry75** [comment]
Your correct that I "can" do that. However it seems highly counter intuitive. What is the point of the `context.WriterFactory` pattern then? You could make the same argument that a `TextOutputFormatter` could just do the same and that the actual `OutputFormatterWriteContext` shouldn't contain this at all. IE: because the `formatter` type does not create the `context` and therefore does not set the `WriterFactory` method it seems odd to just simply ignore it when the comment states clearly this is how to create a writer for the response.

**Comment by rynowak** [comment]
So what's the actual suggestion here? Should we improve the documentation?

It's intended that you can write directly to the body as a stream using `context.HttpContext.Response.Body`. 

`WriterFactory` is provided for the common case where you're doing text - it's there to encourage implementors that want a `TextWriter` to take the same, efficient, path that the framework does.

**Comment by jterry75** [comment]
As long as there is no adverse affect from not using `WriterFactory` to create the writer then I guess its just a documentation problem. Just feels odd to me because I don't know what the platform is "not doing" when I skip it. I just can't imagine if its as simple as `new TextWriter(response.Body) { Encoding = encoding }` why we have the many layers of indirection.

**Comment by rynowak** [comment]
Sure, that's probably the best we can do.

**Comment by Eilon** [comment]
@kichalla this is just a doc comment update, should be a quick task.

**Comment by rynowak** [comment]
Poaching this.

**Comment by rynowak** [comment]
3536cf5aade8a67bb610d29586a53b963be96a66
