### ISSUE TITLE
input tag helper not working in a loop

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/Mvc#5186]
In the Index.cshtml view in [this example](http://www.dotnetawesome.com/2013/09/how-to-update-multiple-row-at-once.html) if I replace `<td>@Html.EditorFor(model => model[i].ContactPerson)</td>` with `<input asp-for="ContactPerson" />` it does not work. It complains `List<UpdateMultiRecord.Contact>' does not contain a definition for 'ContactPerson'`.
**Question**:  How can I use [input tag helper](http://www.davepaquette.com/archive/2015/05/13/mvc6-input-tag-helper-deep-dive.aspx) in the above example?

**Comment by NTaylorMullen** [comment]
Use the `@` symbol to override the auto model mechanics of `asp-for`:

`<input asp-for="@Model[i].ContactPerson" />`

**Comment by saf-itpro** [comment]
@NTaylorMullen Thank you - it works.
**Question**: How, will it work in a `foreach loop`. For example, `@foreach(var item in Model){<input asp-for="ContactPerson" />....}` or an example used [here](https://docs.efproject.net/en/latest/platforms/aspnetcore/new-db.html#create-views)

**Comment by NTaylorMullen** [comment]
@saf-itpro same way. So when you do not provide an `@` symbol the default behavior behind the scenes is: `__model => __model.|` where you can imagine your cursor is at the `|`. The second you type `@` it now does this behind the scenes: `__model => |`.

Therefore, to work with a foreach it'd simply be: `<input asp-for="@item.ContactPerson" />`

**Comment by saf-itpro** [comment]
@NTaylorMullen Thank you for coming to my rescue. It works. I could not find an answer online. It seems not many people are yet used to using tag helper. I'll close the issue.

**Comment by NTaylorMullen** [comment]
@saf-itpro note: `foreach` probably will not work as you expect it to with the input `TagHelper`.  The `Html.DisplayFor` pieces that you linked don't care that the bit theyr'e representing is part of a collection so they work just fine; however, in input's case it'll treat the `@item.ContactPerson` as a single item model and nothing more.
