### ISSUE TITLE
Add option to define ChallengeBehavior in ChallengeResult

### ISSUE THREAD

**Issue by juunas11** [aspnet/Mvc#5187]
Today I was trying to get Azure AD B2C to play nicely with ASP.NET Core. I did however run into a problem with it. When the user tries to edit their profile, they would be given a Forbidden error. And so I found the reason for this in the end was that ChallengeBehavior.Automatic was used by the AuthenticationHandler. Could we get a constructor for defining this behavior since the overload for AuthenticationManager.ChallengeAsync() exists already? Also a controller extension for specifying it would be nice.

**Comment by HaoK** [comment]
Seems like a reasonable ask, that's why its there in HttpAbstractions, in case the developer wants explicit control over the behavior.  Exposing it in the challenge result is reasonable, the larger question is whether we should expose it in some way for Authorize to make it easier to use to change the behavior there (maybe a new global option in Mvc?) (cc @blowdart)

**Comment by blowdart** [comment]
Global seems like a good idea too.

**Comment by juunas11** [comment]
Right, AuthorizeAttribute would need similar customizability. A global default setting would be nice, and also being able to set it per usage.

**Comment by danroth27** [comment]
@HaoK Is this issue going to be handle be the work you are doing on auth in 2.0?

**Comment by HaoK** [comment]
Probably you can assign this to me

**Comment by danroth27** [comment]
@Eilon please assign

**Comment by Tratcher** [comment]
Note we want to remove ChallengeBehavior from Authentication in 2.0 and have that decision made more explicitly in Authorization. https://github.com/aspnet/Security/issues/901

**Comment by rynowak** [comment]
@HaoK - has this scenario been improved? Is there any work left to do here in MVC?

**Comment by HaoK** [comment]
Can probably close this, ChallengeBehvaior got nuked, Forbid is first class and MVC already has both Challenge and Forbid results

**Comment by HaoK** [comment]
See 4c2d727e38b593e4c1ebb8cf002618c2552912a2

**Comment by juunas11** [comment]
So if I return a ChallengeResult from an action, it would always run the same behaviour, even if the user is logged in?

**Comment by HaoK** [comment]
Yeah Challenge => 401, Forbid => 403, no more automatic

**Comment by juunas11** [comment]
Awesome, will have to test later.

**Comment by rynowak** [comment]
Perfect, thanks!
