### ISSUE TITLE
Equivalent of @Html.Hidden or @Html.HiddenFor in MVC6 Tag Helper

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/Mvc#5188]
What is the equivalent of the above two HTML helpers in MVC6 `Tag helper`? I want to hide `primary key` of a model (table) in an MVC Core view **using** tag Helper.

**Comment by dougbu** [comment]
For `@Html.HidenFor(m => m.Property)`, use `<input asp-for="Property" type="hidden"/>`.

Tag helpers do not support the older expression name approach. So there's no direct equivalent for `@Html.Hidden()`.

**Comment by saf-itpro** [comment]
@dougbu It works - thank you. I'm closing the issue.

**Comment by Jeroen5356** [comment]
So a value property is not needed?
