### ISSUE TITLE
IHostingEnvironment ContentRootPath for "Startup" class incorrect in Linux (Docker)

### ISSUE THREAD

**Issue by h3smith** [aspnet/Mvc#5193]
Building and deploying with Docker. When we build and test with Windows, ContentRootPath is correct. 

With Docker, we deploy to /root/

`COPY bin/Debug/netcoreapp1.0/publish/ /root/`

When Startup gets the ContentRootPath in Linux, it is showing up as "/" not "/root/" like we'd expect. We have to write some custom logic to handle this use case (Environment variable in Docker) to enable this to work as expected.

**Comment by h3smith** [comment]
Current work around:

Dockerfile
```ENV INSTALL_DOCKER_PATH /root/```

Startup.cs

```
        public Startup(IHostingEnvironment env)
        {
            var envVariable = Environment.GetEnvironmentVariable(@"INSTALL_DOCKER_PATH");

            var builder = new ConfigurationBuilder()
                .SetBasePath(string.IsNullOrEmpty(envVariable) ? env.ContentRootPath : envVariable)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();

            Configuration = builder.Build();

        }

```

**Comment by davidfowl** [comment]
This has nothing to do with MVC. You should change the ContentRoot path in `Program.cs`, not `Startup.cs`.

/cc @glennc for the docker issue

**Comment by h3smith** [comment]
@davidfowl which is the appropriate repository to report this? The behavior is incorrect. It occurs on OS X as well. It isn't limited to Docker.

**Comment by davidfowl** [comment]
Always start with aspnet/Home and we'll re-route appropriately

**Comment by glennc** [comment]
Don't we normally scaffold `.SetBasePath(Directory.GetCurrentDirectory())` now?

**Comment by davidfowl** [comment]
Thats what I thought

**Comment by h3smith** [comment]
@davidfowl @glennc 

To follow up (sorry for the delay), here is what we've had in Program and Startup, respectively. Narrowing this down it seems to be (currently) occurring only within Docker. (Tested more in OS X and Windows)

If I feed it the correct path (Set via ENV variable) all is kosher. 



```

            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseUrls(@"http://*:5959")
                .UseStartup<Startup>()
                .Build();

            host.Run();
```

Startup
```

            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddJsonFile($"appsettings.docker.json", optional: true)
                .AddEnvironmentVariables();
```

**Comment by h3smith** [comment]
As an update, Setting the `WORKDIR` in the Dockerfile fixes this issue. I didn't see this in the documentation but it resolves the issue. My (incorrect it seems) assumption was `Directory.GetCurrentDirectory()` would have pulled the directory `ENTRYPOINT` is in.
