### ISSUE TITLE
urlRewite middleware

### ISSUE THREAD

**Issue by iscifoni** [aspnet/Mvc#5194]
I think that it could be usefull to have a rewriteurl middleware, so if i change the hosting environment i do not have to install and configure a rewriteurl module.

A great goal :

1) Default rewrite url Provider : rewrite url using a regex pattern and group management.
2) Ability to define a custom rewrite url Provider, so user can define rewriteurl role.
3) when a url is rewrited add a custom header to identify if url is rewrited, add the original url and the rewrited url

**Comment by Muchiachio** [comment]
It's tracked in https://github.com/aspnet/BasicMiddleware/issues/67.
