### ISSUE TITLE
Exclude some excessive tag helper associations

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5199]
Once the aspnet/Razor#826 fix is available, exclude the following tag helper associations:
- `<a>` elements that already have an `href` attribute
- perhaps `<input>` elements that already have a `value` attribute

May also be useful to ensure the `InputTagHelper` does not apply to elements associated with the `SubmitTagHelper` and visa versa. That is, prevent `InputTagHelper` association when `asp-action` (et cetera) is specified and prevent `SubmitTagHelper` association when `asp-for` is specified.

I'm sure we can think of other interesting exclusions for the existing MVC tag helpers.

**Comment by danroth27** [comment]
No plans to implement this.
