### ISSUE TITLE
ASP.NET WebFormView error

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/Mvc#5202]
I'm getting the following error when I call a WebForm from my following ASP.NET MVC 6 Action method shown below:

**Error**:
`Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable`

**Controller**:
```
using System.Web.Mvc;
public ActionResult Test()
{
    return View(new WebFormView(this.ControllerContext,"~/WebForm1.aspx"));
}
```
**NOTE**: I'm using [WebFormView](https://msdn.microsoft.com/en-us/library/system.web.mvc.webformview(v=vs.118).aspx) class and .NET 4.6. The WebForm1.aspx file is in the root directory of the Web project

**Comment by danroth27** [comment]
`WebFormViews` are not supported in ASP.NET Core.
