### ISSUE TITLE
[Feature request] Tag helper to inject a class as a validation summary

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#5210]
Like this one: https://github.com/OrchardCMS/Orchard2/blob/master/src/Orchard.DisplayManagement/TagHelpers/ValidationClassFor.cs

Motivation:
In bootstrap, form groups need a custom class when there is a validation error in one of the inputs of the group. There is no way to inject a generic validation error class to an existing tag with the current OOB tag helpers. There are workarounds, but this need might happen often if as people try to target bootstrap with MVC.

**Comment by danroth27** [comment]
Related to https://github.com/aspnet/Mvc/issues/4888

**Comment by rynowak** [comment]
Suggest we close this item and track as part of #4888

**Comment by dougbu** [comment]
As discussed&hellip;
