### ISSUE TITLE
Support non-boolean values with Html.Checkbox

### ISSUE THREAD

**Issue by chris-oswald** [aspnet/Mvc#5211]
I think there is a bug in the DefaultHtmlGenerator.  You should be able to specify values in checkboxes that aren't booleans.  When you specify a non-boolean value and get a model state error, rerendering the checkbox throws an exception.  Everything works fine from a post perspective as long as the model state validation doesn't fail.

These lines assume all values in the model state are a boolean for a checkbox, which is an incorrect assumption in my opinion.

Ln: 1187

```c#
    var modelStateWasChecked = GetModelStateValue(viewContext, fullName, **typeof(bool)**) as bool?;
```

Ln: 1086

```c#
internal static object GetModelStateValue(ViewContext viewContext, string key, Type destinationType)
        {
            ModelStateEntry entry;
            if (viewContext.ViewData.ModelState.TryGetValue(key, out entry) && entry.RawValue != null)
            {
                **return ModelBindingHelper.ConvertTo(entry.RawValue, destinationType, culture: null);**
            }

        return null;
    }
```

**Comment by dougbu** [comment]
This is not technically a bug. But it is a restriction of the current HTML and tag helpers in MVC.

Might be able to address some of this gap in the `<input/>` tag helper and with `CheckBox(string expression, bool? isChecked, object htmlAttributes)`. Unfortunately due to our inability to change `IHtmlHelper<TModel>` before 2.0, doesn't look like we can expand beyond `CheckBoxFor(Expression<Func<TModel, bool>> expression, object htmlAttributes)` anytime soon.

**Comment by chris-oswald** [comment]
I've worked around it by creating my own tag helper so it's not impacting me, but I at least wanted to point it out.  It sound like you're already aware of the limitation.  I'd like to request it as a future enhancement if that's alright.

**Comment by danroth27** [comment]
We enforce currently that check boxes get treated as booleans. The request here is to be able to have more general check box functionality.

**Comment by dougbu** [comment]
@danroth27 , @Eilon should I unassign myself since this one is in the backlog?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
