### ISSUE TITLE
Add a cookie based ITempDataProvider

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#5212]
Using `TempData` today requires the manual configuration of session state. It would be great to have a provider available that uses cookies (protected with Data Protection) to round-trip the temp data information so that session state isn't required.

While we likely can't change this to be the default (:cry:) it would be awesome to have it be available.

Temp data is a great solution for showing form success messages after a Post-Redirect-Get cycle and the need to use session state for that today is overkill.

@rynowak @sebastienros @danroth27

**Comment by brockallen** [comment]
Here's one for MVC 5: https://github.com/brockallen/CookieTempData

**Comment by javiercn** [comment]
+1! (No reactions on mobile)

**Comment by blowdart** [comment]
Ewww. Session in cookies? Remember there's a max size on cookies from a site.

As long as it's ran through data protection, which will increase the size, and the cookies are limited to the app path, and they're HTTP Only and, if you're on HTTPS they're marked secure, then fine.

**Comment by luisgoncalves** [comment]
Already had [one implemented](https://github.com/luisgoncalves/aspnetcore-cookietempdata) as a package... Anyway, maybe you could make the cookie name configurable.

**Comment by John0King** [comment]
@DamianEdwards  Why use Cookie or Session ?  Create a `Dictionary` when Contorller be invoked, and  share it beteen `Controller `, `View `, `PartialView` and `ViewComponent ` ( same reference ) , Is this will do current TempData's Job?

**Comment by ivaylokenov** [comment]
@John0King No. The TempData persists the stored data until the next request.

**Comment by John0King** [comment]
@ivaylokenov   I still don't understand ? Does the second requset will get the TempData ?

**Comment by ivaylokenov** [comment]
@John0King Yes, if you put data in the TempData, it will be there for the current and for the next request by default.
