### ISSUE TITLE
View component tag helpers don't allow generic parameters

### ISSUE THREAD

**Issue by cjqian** [aspnet/Mvc#5216]
View components that are invoked with generic parameters will not be translated into view component tag helpers correctly.
# 1051

**Comment by NTaylorMullen** [comment]
This should be done before https://github.com/aspnet/Mvc/issues/5207

**Comment by cjqian** [comment]
Say you have a view component `Foo` with an invoke method that takes in something like a `Dictionary<int, string> bar`. In the current implementation, if you try to use a view component in your .cshtml file like `<vc:foo bar=...`, I'm not confident that it will get processed correctly.

**Comment by NTaylorMullen** [comment]
## Scenario:
Having a `ViewComponent` with a generic parameter in its `Invoke`/`InvokeAsync` results in broken C# being generated by Razor; resulting in a compilation error when trying to serve a view.

## Reason
We generate a `TagHelperDescriptor`s based on a `ViewComponent`s `Invoke`/`InvokeAsync` method. Razor then consumes these `TagHelperDescriptor`s to render appropriate code for rendering a `TagHelper`. In order for that piece to work we must generate an actual `TagHelper` class based off of the `TagHelperDescriptor` to work at runtime. This means generating `public __TypeName__ __PropertyName { get; set;}` within an actual `TagHelper` where the type name and property name are represented as `string`s in a `TagHelperAttributeDescriptor`. Today we construct a `TagHelperAttributeDescriptor` by saying: `TagHelperAttributeDescriptor.TypeName = ViewComponent.Parameter[x].GetType().FullName;`. The code gen then directly consumes the attribute descriptors type name to generate the get; set; property. Therefore, for generic types the `.FullName` would result in a back tick being generated.

**Comment by Eilon** [comment]
Got it, thanks!

**Comment by dougbu** [comment]
@NTaylorMullen does `DefaultViewComponentHelper` have any issues w/ generic view component types? I ask because no tests cover the scenario. That lack makes it less clear whether generic view component support was intended (anywhere).

**Comment by Eilon** [comment]
What exactly *is* a generic view component? I thought view components by definition need to be concrete, no? How else could you invoke one?

**Comment by NTaylorMullen** [comment]
@dougbu I gave it a shot and it doesn't look like it can support generic ViewComponents, I've filed an [issue](https://github.com/aspnet/Mvc/issues/5380). That aside however, this issue is more geared towards non generic `ViewComponents` where a generic parameter, lets say `List<string>` causes `ViewComponentTagHelper`s to fail. Ex:

```C#
public class XViewComponent
{
    public string Invoke(List<string> values)
    {
        return string.Join(", ", values);
    }
}
```

**Comment by dougbu** [comment]
@Eilon I should have said "`ViewComponent` with a generic `Invoke[Async]()` argument". But @NTaylorMullen thanks for checking on a "`ViewComponent` that _is_ an open generic type".

**Comment by dougbu** [comment]
Back to _this_ issue, @NTaylorMullen are you looking to support `Invoke<T>(List<T> value)` or other open generic **methods** as well? Or is this issue about only parameters of closed generic types in regular 'ole methods?

**Comment by NTaylorMullen** [comment]
@dougbu Oh I wouldn't expect that to work because that'd expect the ViewComponent invocation system to map parameters provided and then back-map said parameter to the InvokeAsync call. When you try it in practice you get the following:

![image](https://cloud.githubusercontent.com/assets/2008729/19199270/12609560-8c78-11e6-9eb1-f4e6a5ddb7fa.png)

**Comment by rynowak** [comment]
Suggestion: When we port TagHelper discovery to use metadata/`ISymbol` instead of reflection, we just fix this there. `ISymbol` (Roslyn) already does the correct formatting of type names for code generation
