### ISSUE TITLE
Make EnumGroupAndName respect DisplayAttribute

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#5217]
We should make EnumGroupAndName respect the DisplayAttribute.Group of enum values, including running `IStringLocalizer` or looking things up on the ResourceType as appropriate. Similar to what we did for Display.Name in #5197 and #4215.

**Comment by dougbu** [comment]
FYI `ResourceType` lookup _should_ initially work correctly though we seem to have a test gap in that area. The code certainly uses `DisplayAttribute.GetGroupName()` (and therefore `ResourceType`) when `EnumGroupedDisplayNamesAndValues` is first evaluated.

Agree the `Group`-related equivalents of #5197 (left out `IStringLocalizer` support) and #5198 (don't re-evaluate the group name for different locales) are real issues.

**Comment by jcemoller** [comment]
Any news on this one? DisplayAttribute data annotations on enums does not seem to localize in 2.0.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
