### ISSUE TITLE
Is there a way to select an action by the content of the body?

### ISSUE THREAD

**Issue by tthiery** [aspnet/Mvc#5218]
I have a REST interface endpoint like

> POST /items/12345/actions

I utilize a generic actions sub collection to be apply to apply changes to 12345 which are not easily mapped to the content or direct other sub collections of it.

My question is the following: Since there could be multiple different action types I identify the action by a JSON property of the content of an uploaded document.

How do I select a action by a part of the JSON body of the request. Is there something possible like...

    [Route("api/v1/items")
    public class ItemsController : Controller
    {
        [HttpPost("{id}/actions")]
        [CheckJsonBody("type", "ActionA")]
        public ActionResult DoActionA(int id, ActionA a)
        {
             // do something Aeish
        }

        [HttpPost("{id}/actions")]
        [CheckJsonBody("type", "ActionB")]
        public ActionResult DoActionB(int id, ActionB b)
        {
             // do something Beish
        }
    }

The request would look like ...

    {
       "type": "ActionA",
       "abc": "xyz"
    }

I have digged myself up into the code till `Microsoft.AspNetCore.Mvc.ActionConstraints.ActionMethodSelectorAttribute`.

However starting from there, I am a bit lost to reach a high-performance solution. So far I understand the current implementation, body decoding happens after route constraints.

ps: And yes, I know I could handle them in one action and do a switch on the "type" property but then I need to handle binding, validation, etc on my own.

@davidfowl @DamianEdwards

**Comment by rynowak** [comment]
If you want something like this you can certainly build it.

First, you'll want to buffer the body by reading it into a memory stream and replacing the `HttpRequest.Body`. We've got a basic version of this [here](https://github.com/aspnet/BasicMiddleware/tree/dev/src/Microsoft.AspNetCore.Buffering) but it's not really production hardened yet.

Then inside your `IActionConstraint`/`ActionMethodSelectorAttribute` you can read up until the first property and then seek the stream back to 0. Depending on the number of actions that you're selecting between, you might want to cache the 'action' in `HttpContext.Items` to avoid reparsing the JSON.

That's where I'd recommend starting.
