### ISSUE TITLE
ASP.NET Core MVC return 404 when startup.cs is in different assembly

### ISSUE THREAD

**Issue by binoypatel** [aspnet/Mvc#5222]
Hi

I have moved startup.cs to different assembly Demo.Bootstrapper which is netcoreapp1.0 assembly. After moving startup.cs to this assembly when I run Demo.Web, it instantiate startup class correctly at runtime but after that it returns 404 when processing actual http request.

If I move startup.cs back to Demo.Web it works fine. Not sure what is the reason. I am using Visual Studio 2015 with Update 3 and asp.net core RTM.

Can you please help? I have attached a sample application.

Thanks,
Binoy
[Demo.Web.zip](https://github.com/aspnet/Mvc/files/453003/Demo.Web.zip)

**Comment by ivaylokenov** [comment]
In Program.cs you can call this method:

```c#
new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseKestrel()
                .UseIISIntegration()
                .UseStartup<Startup>() // CALL THIS METHOD WITH THE CORRECT STARTUP TYPE
                .Build();
```

Of course you need to reference the other project and add `using Demo.Bootstrapper;`. The string version of the method expects full type name - "Demo.Bootstrapper.Startup".

**Comment by binoypatel** [comment]
Hi,

I don't want to reference Bootstrapped to Web project as part of onion architecture. Even without using full name it instantiate startup correctly but it stops processing the request ie. It doesn't show index page.

Thanks
Binoy

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, Sep 3, 2016 at 7:16 AM -0400, "Ivaylo Kenov" <notifications@github.com<mailto:notifications@github.com>> wrote:


In Program.cs you can call this method:

new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseKestrel()
                .UseIISIntegration()
                .UseStartup<Startup>() // CALL THIS METHOD WITH THE CORRECT STARTUP TYPE
                .Build();

Of course you need to reference the other project and add using Demo.Bootstrapper;. The string version of the method expects full type name - "Demo.Bootstrapper.Startup".

-

**Comment by khellang** [comment]
> I don't want to reference Bootstrapped to Web project as part of onion architecture.

I'm curious; why can't you reference something you certainly will use at runtime anyway? Is this something onion architecture dictates? :confused:

Where is your controllers defined? Are you able to hit a breakpoint in a controller? There might be some hoops you have to jump through if your controllers are in different assemblies. Especially if you're not referencing stuff at build-time. Actually I'm not sure that's a supported scenario at all...

**Comment by binoypatel** [comment]
There are many sites that helps you understand, here is one that explains it, http://weblogs.asp.net/imranbaloch/a-sample-of-onion-architecture-with-asp-net-identity, I am also abstracting identity framework, basically Onion architecture provides better separation between layers.

Especially if you're not referencing stuff at build-time. Actually I'm not sure that's a supported scenario at all...
> If that is the case then why startup method accepting string parameter as assemblyname?

It doesn't hit the controller, run the sample attached and you will understand the issue.

Thanks
Binoy

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by ardalis** [comment]
Onion architecture (aka ports-and-adapters, aka hexagonal, aka "clean architecture") doesn't require that UI concerns be extracted out of the UI project. In this case, Startup and other MVC-related classes are UI concerns/responsibilities, and there's little to be gained by trying to move them out of the UI project.

**Comment by binoypatel** [comment]
I guess we are deviating from the actual bug, my point is startup method provides a way to load startup class from different assembly and it works but after loading the startup class it doesn't hit the controller.

Thanks
Binoy

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, Sep 3, 2016 at 2:46 PM -0400, "Steve Smith" <notifications@github.com<mailto:notifications@github.com>> wrote:


Onion architecture (aka ports-and-adapters, aka hexagonal, aka "clean architecture") doesn't require that UI concerns be extracted out of the UI project. In this case, Startup and other MVC-related classes are UI concerns/responsibilities, and there's little to be gained by trying to move them out of the UI project.

-

**Comment by khellang** [comment]
@binoypatel You're conflating things. Startup doesn't necessarily have anything to do with MVC. Sure, you can use Startup from any assembly, as you've figured out, but that doesn't mean MVC will automagically find your controllers.

When I say "pulling controllers from assemblies not referenced at build-time might be an unsupported scenario", I'm talking about MVC.

I try to avoid pulling random uploadef zip-files off the web. Is there any way you could push it to a git repo?

As @ardalis said; I think you're separating things a bit too much. There's no point in pulling Startup into a separate assembly from Web, because Startup *is* Web.

**Comment by binoypatel** [comment]
I understand startup is web but in production application, my startup is also doing complex IoC configuration using Autofac modules and I don't want tightly coupled my web assembly with multiple other assemblies that has actual implementations. All my controllers are part of build-time assembly which is Demo.web in this case.

I am on vacation till Monday, I will put the same code in my git repo and update you with the link.

Thanks
Binoy

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by binoypatel** [comment]
I have put the sample application at [https://github.com/binoypatel/asp.net-sample](url) , as mentioned my startup class in Demo.Bootstrapper assembly and I am calling .Startup("HelpStar.Bootstrapper") in Program.cs in HelpStar.Web which correctly instantiate Startup class but after that it doesn't process controller and returns 404

Thanks,
Binoy

**Comment by binoypatel** [comment]
Ok, I managed to found the root cause, for some reason it needs Demo.Bootstrapper.deps.json along with Demo.Bootstrapper.dll and Demo.Bootstrapper.pbd in output folder of Demo.Web project. Not sure why it needs that file?

Cheers,
Binoy

**Comment by pdushkin** [comment]
Binoy, I am struggling with porting an Onion project to Core also. I believe I have everything mostly set up, but can you tell me how you configured things so your Bootstrapper assembly files get picked up by your Web project at build time? Like you, I don't want to reference the assembly directly and project.json's "copyToOutput" does not work in this scenario.

**Comment by binoypatel** [comment]
Hi pdushkin

In my case, I am copying all dlls from bootstrapper to web, since my bootstrapper have references from other dlls but web. I do it using project.json:

"scripts": {
    "postcompile": [ "xcopy /I /F /Y %compile:OutputDir%\\*.* ..\\My.Web\\bin\\%compile:Configuration%\\netcoreapp1.0\\" ]
  }

Cheers,
Binoy

**Comment by pdushkin** [comment]
Thanks a lot Binoy, that worked perfectly. Much appreciated!

**Comment by kiran-bobade** [comment]
I am facing the same issue. My startup class is in NetStandard 2.0 assembly. I am referring this assembly to Asp.net Core 2.0 API project which does not have **project.json** file.  It works well if I derive a class from that Startup class and use it as Startup. 

Can you help/guide me to resolve this?

**Comment by pranavkm** [comment]
@kiran-bobade you're commenting on a closed \ resolved issue. Could you file a separate issue with specific details \ sample project that reproduces the issue?

**Comment by kiran-bobade** [comment]
@pranavkm Please see #7131
