### ISSUE TITLE
In ASP.NET MVC Core how to keep Bootstrap panel open when a link inside it is clicked

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/Mvc#5230]
In my ASP.NET MVC Core web app I've a page (a view) with a left-side menu with two sub-menus. When page loads the submenus are supposed to collapse. That works since I'm not using `in` class in class="panel-collapse collapse". Also, submanue expand/collapse correctly when you click on it. But I need the submenu to stay open when a user clicks a link inside it. How can I achieve this behavior? Note: Each click calls a specific controller action as shown below:

**View**:

```html
<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#ToolsID">Tools</a>
            </h4>
        </div>
        <div class="panel-collapse collapse" id="ToolsID">
            <div class="list-group">
                <a asp-controller="MyController1" asp-action="MyAction1" class="list-group-item">Controller1 Test</a>
                <a asp-controller="MyController2" asp-action="MyAction2" class="list-group-item">Controller2 Test</a>
            </div>
        </div>
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#ReportsID">Reports</a>
            </h4>
        </div>
        <div class="panel-collapse collapse" id="ReportsID">
            <div class="list-group">
                <a href="#" class="list-group-item">Test1</a>
                <a href="#" class="list-group-item">Test2</a>
            </div>
        </div>
    </div>
</div>```

**Comment by Eilon** [comment]
Hi, this question seems to be about how to use Bootstrap and not MVC, so I recommend asking the question on a more suitable site such as StackOverflow (https://stackoverflow.com/questions/tagged/twitter-bootstrap) or perhaps Bootstrap's GitHub repo (https://github.com/twbs/bootstrap).
