### ISSUE TITLE
Asp.net core webapi return Json set attribute name all lowercase

### ISSUE THREAD

**Issue by 188** [aspnet/Mvc#5235]
Asp.net core webapi return Json set attribute name all lowercase
Such as:
Public class User
{
Public string Name {get; The set; }
Public int the Age {get; The set; }
Public string Address_Info {get; The set; }
}
How to return address_info rather than Address_Info or address_Info

**Comment by dougbu** [comment]
Please see aspnet/Announcements#194 and prior discussion at aspnet/Mvc#4842. You may be particularly interested in the "To restore previous naming strategy" part of aspnet/Announcements#194.
