### ISSUE TITLE
RequireHttpsAttribute throws InvalidOperationException on HEAD request

### ISSUE THREAD

**Issue by PranKe01** [aspnet/Mvc#5236]
Hi there,
I am using the RequireHttpsAttribute in my MVC website together with ELMAH (Error-logging).
I get a lot of InvalidOperationExceptions and when I look into the errors I see, that all used the HEAD request method.

> System.InvalidOperationException: The requested resource can only be accessed via SSL.
   bei System.Web.Mvc.RequireHttpsAttribute.HandleNonHttpsRequest(AuthorizationContext filterContext)
   bei System.Web.Mvc.RequireHttpsAttribute.OnAuthorization(AuthorizationContext filterContext)
   bei System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   bei System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)

Shouldn't the attribute also cover the HEAD requests?

**Comment by khellang** [comment]
> Shouldn't the attribute also cover the HEAD requests?

Isn't that exactly what it's doing? It basically says "someone tried to request a resource which has been restricted to HTTPS-only, using the HEAD method"

**Comment by PranKe01** [comment]
You are right. I am using MVC5. I think this issue can be closed :)

How could I fix this in MVC5? I thought of adding a new Attribute which also handles HEAD requests, but then I found this comment:

```
// only redirect for GET requests, otherwise the browser might not propagate the verb and request
// body correctly.
if (!String.Equals(filterContext.HttpContext.Request.HttpMethod, "GET", StringComparison.OrdinalIgnoreCase))
{
    throw new InvalidOperationException(MvcResources.RequireHttpsAttribute_MustUseSsl);
}
```

Should I just copy the code from here?
https://github.com/aspnet/Mvc/blob/ee2cfa1963ee7f8195130d41330f94d4622ca89a/src/Microsoft.AspNetCore.Mvc.Core/RequireHttpsAttribute.cs

**Comment by khellang** [comment]
You can just derive from `RequireHttpsAttribute` and override the `HandleNonHttpsRequest` method, yes.
