### ISSUE TITLE
Is there a way to create a pluggable host application?

### ISSUE THREAD

**Issue by malhayek2014** [aspnet/Mvc#5237]
Is there a good way to build a plugin base application where we have one application using identity to handle the authentication and the claims. Then we can add "packages/plugins (a small mini mvc application)" to the main application. Similar idea to Areas, but with the ability to compile each area separately. 

The advantage here is that the plugins won't be part of the main application and compiling them will be separate which won't impact the main application.

**Comment by sebastienros** [comment]
You can already take a look at what we have done in [Orchard2](https://github.com/OrchardCMS/Orchard2). It supports modules which can be dropped into your published application. Each module can configure services and middlewares. It's also multi-tenant and each tenant can be based on a different set of modules.

**Comment by danroth27** [comment]
We have no plans to build something directly into ASP.NET Core for this scenario, but you can use an existing community solution, like the modules support in Orchard Core.
