### ISSUE TITLE
Extend the default model binder

### ISSUE THREAD

**Issue by janhartmann** [aspnet/Mvc#5238]
I'm wondering how it is possible to extend the default model binder to bind the `HttpContext.User` to an interface property?

Right now I have:

```cs
public class AddCustomer : ICommand, IUserAware
{
	public string Name { get; set; }

	public int Age { get; set; }

	public Guid UserId { get; set; }
}

public interface IUserAware
{
	Guid UserId { get; set; }
}
```

The controller action:

```cs
public IActionResult Post([FromBody]AddCustomer command)
{
        // Handle the command
	return Ok();
}
```

The model binder I'm trying to construct: 

```cs
public class UserAwareModelBinder : IModelBinder
{
	public Task BindModelAsync(ModelBindingContext bindingContext)
	{
		var user = bindingContext.HttpContext.User;
		if (user != null)
		{
			bindingContext.Result = ModelBindingResult.Success(user.GetUserIdFromClaims());
			return Task.CompletedTask;
		}

		return Task.CompletedTask;
	}
}

public class UserAwareModelBinderProvider : IModelBinderProvider
{
	public IModelBinder GetBinder(ModelBinderProviderContext context)
	{
		return typeof(IUserAware).IsAssignableFrom(context.Metadata.ModelType) ? new UserAwareModelBinder() : null;
	}
}
```

Wiring:

```cs
services.AddMvc(options =>
{
	options.ModelBinderProviders.Insert(0, new UserAwareModelBinderProvider());
});
```

**The model binder is hit, but nothing gets binded and the `command` ends up as null. How can I extend the current model binder functionality - but bind the `IUserAware` property from the `HttpContext.User`?**

In old school MVC, it was possible to extend the `DefaultModelBinder` and do the binding:

```cs
public class UserAwareModelBinder : DefaultModelBinder
{
    protected override object CreateModel(ControllerContext controllerContext, ModelBindingContext bindingContext, System.Type modelType)
    {
        var baseModel = base.CreateModel(controllerContext, bindingContext, modelType);
        var commandModel = baseModel as IUserAware;
        if (commandModel != null) 
        {
             commandModel.UserId = controllerContext.HttpContext.User.GetUserIdFromClaims();
        }

        return baseModel;
    }
}
```

**Comment by dougbu** [comment]
Looks like your binder is associated w/ the whole `IUserAware` implementation but provides only a `Guid` value. Need something like
``` c#
bindingContext.Result = ModelBindingResult.Success(new AddCustomer
{
    UserId = user.GetUserIdFromClaims(),
});
```

**Comment by janhartmann** [comment]
Thanks @dougbu, I would like to have all the other properties mapped from the classic model binder and then only map the `IUserAware` interface property (`UserId`) from the request?

I've tried creating the instance with `Activator.CreateInstance(bindingContext.ModelType)` and casting it to `IUserAware` and setting the property - this works fine, but other properties are not mapped then from the request body (`name`, `age` etc.)

**Comment by djhaley** [comment]
IModelBinderProvider.GetBinder() is called for each property, but is also called for the entire model, which is what your code is currently trying to handle.  You'll want to capture just the call for your UserId property.   context.MetaData has a ContainerType property that you should be able to make the IsAssignableFrom check on, then you can see if ModelType is a Guid.

**Comment by janhartmann** [comment]
Closed as this issue is really my way of working against the concept of the model binder.

As Steven on StackOverflow says: 

> The source of your problem is the fact that your command contains contextual information.
