### ISSUE TITLE
PagedBufferedTextWriter does not flush synchronous data prior to writing data asynchronously to the underlying stream

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#5241]
PagedBufferedTextWriter works in two modes: in sync, it accumulates text in char buffers. In async it writes directly to the underlying stream. However it does not flush any of the buffered contents prior to doing this. All of it's async calls should flush buffered content prior to writing to the underlying writer.

**Comment by rynowak** [comment]
This needs to be fixed because if you called `WriteAsync(...).GetAwaiter().GetResult()` in an `IHtmlContent` you would have out of order writing.
