### ISSUE TITLE
Which project is the codes for web api?

### ISSUE THREAD

**Issue by csharpweb** [aspnet/Mvc#5244]
i want to see the source code about web api,but i could not found the project. anybody tell me?

**Comment by rynowak** [comment]
If you're looking for previous releases of WebAPI 2.x.x and 3.x.x the code is at http://aspnetwebstack.codeplex.com/

WebAPI is part of MVC Core now. Depending on what you're looking for the answer is probably the `Microsoft.AspNetCore.Mvc.Core` project.

If you can be more specific about what you're looking for I can point you in the right direction.
