### ISSUE TITLE
Inject Object From ActionFilter into Controller Method Arguments

### ISSUE THREAD

**Issue by KombuchaShroomz** [aspnet/Mvc#5245]
I'm looking for a way to use an ActionFilter's constructor and OnActionExecuted method (using the query string) to configure an object and then have that object be accessible as an argument to the attached controller method (in the same style as a service would be made available by dependency injection). Something like this example:

The object:
```
    public class ComplexObject
    {
        int setting1;
        int setting2;

        public ComplexObject(int setting1, int setting2)
        {
            // Constructor
        }

        public int doSomething()
        {
            // Do something with the configuration values    
        }
    }
```

The controller method:
```
        [ObjectInjectionFilter(15)]
        public IActionResult Index(ComplexObject complex)
        {
            return View(complex.doSomething());
        }
```

The filter idea:
```
public class ObjectInjectionFilter : ActionFilterAttribute, IActionFilter
    {

        int setting1;

        public ObjectInjectionFilter (int setting1){
            //  Collect configuration info in constructor
            this.setting1 = setting1
        }

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            //  Collect configuration info in OnActionExecuted
            var queryString = context
                                .HttpContext
                                .Request
                                .Query;
            int setting2 = queryString["setting2"];
            
            ComplexObject complex = new ComplexObject(setting1, setting2);

            //  How can I add object to controller arguments?
            context.AddToControllerArguments(complex);
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {

        }
    }
```

Is there any way to do this? Perhaps by attaching the object to some part of the HTTP request that the controller interprets?

For context, I'm looking to wrap pagination functionality into a filter. The idea being that the object in question contains a reference to a data source and a programmer uses the new 'paginator' object (available as a controller argument) to perform their query rather than using the data source directly.

Thanks

**Comment by Muchiachio** [comment]
I think it would be simpler to create a `ComplexObjectBinder`, which would then bind `ComplexObject`, only if it's required by the action. Instead of trying to inject it to all actions.

**Comment by KombuchaShroomz** [comment]
Would that allow for the controller method to look along the lines of my example controller?

**Comment by rynowak** [comment]
For anyone that's curious, you can modify the action arguments like:
`context.ActionArguments["param"] = value`

I agree with @Muchiachio - a model binder is a better fit for this case, since you already write a `Paginator` type. And yes, your controller code would be the same.

I'd start by writing an `IModelBinder` and then use `[ModelBinderAttribute(...)]` to hook that up to your `Paginator` class.
