### ISSUE TITLE
Pagination with a Filter: Applying a Type at Runtime to a Filter

### ISSUE THREAD

**Issue by KombuchaShroomz** [aspnet/Mvc#5246]
I'm looking to write a ResultFilter that can intercept an IQueryable<T> returned from a controller method and paginate the query using information present in the filter's constructor and in the request's query string. A very simple example follows:

The controller:
```
        [PaginationFilter(100)]
        public IQueryable<SomeType> Index()
        {
            IQueryable<SomeType> query = someData.AsQueryable();
            return query;
        }
```

The filter:
```
    public class PaginationFilter : IResultFilter
    {

        private int pageSize;

        public PaginationFilter (int pageSize){
            this.pageSize = pageSize;
        }

        public override void OnResultExecuting(ResultExecutingContext context)
        {
            var queryString = context
                                .HttpContext
                                .Request
                                .Query;
            int pageNum = queryString["pageNum"];

            IQueryable<T> resultQuery = context.Result as IQueryable<T>;
            Paginator<T> paginator = new Paginator(pageSize, pageNum)

            context.Result = paginator.Paginate(resultQuery);
        }

        public override void OnResultExecuted(ResultExecutingContext context)
        {

        }
    }
```

The paginator:
```
    public class Paginator<T>
    {
        int pageSize;
        int pageNum;

        public Paginator(int pageSize, int pageNum)
        {
            this.pageSize = pageSize;
            this.pageNum = pageNum;
        }

        public IQueryable<T> Paginate(IQueryable<T> query)
        {
            return query.Skip((pageNum -1) * pageSize).Take(pageSize);
        }
    }
```

The problem here is that IQueryable.Skip() and IQueryable.Take() both require a type parameter to work, hence why the paginator has a type variable <T> attached. A filter cannot be generic and so my question is, how do I define the type of the paginator at runtime from the controller method?

The idea is that this PaginatorFilter could be applied to any controller returning an IQueryable<T> and told the type T by the controller method and that the HTTP request that causes the controller method to be called can define the page number it would like.

Thanks

**Comment by rynowak** [comment]
`IQueryable<T>` is covariant - https://msdn.microsoft.com/en-us/library/bb351562(v=vs.110).aspx - that's the `out T` in the type declaration. That means for any `T` an `IQueryable<T>` also is an `IQueryable<object>`. Would that do what you need?

Your alternative if you need to preserve `T` is to write a generic method, and then use reflection to call it. You can cache these if necessary or build expression trees if necessary.

```
var objectResult = context.Result as ObjectResult;
if (objectResult == null)
{
    return;
}

var result = objectResult.Value;

var method = GetType().GetTypeInfo().GetMethod("MyGenericMethod", BindingFlags.NonPublic | BindingFlags.Instance);

var genericMethod = method.MakeGenericType(value.GetType().GetTypeInfo().GenericTypeArguments);
genericMethod.Invoke(this, result);

...

private void MyGenericMethod<T>(IQueryable<T> querable)
{
    ...
}
```

**Comment by KombuchaShroomz** [comment]
Thanks rynowak, your suggestion worked perfectly and has allowed me to write a really convenient way to write a pagination mechanism. Where the meat of the filter's ```OnActionExecuted``` method looks like this:
```
            // ...
            var result = objectResult.Value;
            // ...

            var method = _paginator.GetType().GetTypeInfo().GetMethod("Paginate");

            var genericMethod = method.MakeGenericMethod(result.GetType().GetTypeInfo().GenericTypeArguments);
            var paginatedResult = genericMethod.Invoke(_paginator, new Object[] {result});

            context.Result = new ObjectResult(paginatedResult);
```

and _paginator is instantiated with dependency injection in the filter's constructor.

Thanks again!
