### ISSUE TITLE
Script/LinkTagHelper shouldn't use doc.write fallback

### ISSUE THREAD

**Issue by benaadams** [aspnet/Mvc#5248]
Chrome is looking to stop document.write script injection under some circumstances (and they will probably increase)

**Intervening against document.write()**

> (index):34 A Parser-blocking, cross-origin script, https://paul.kinlan.me/ad-inject.js, is invoked via document.write(). This may be blocked by the browser if the device has poor network connectivity.

https://developers.google.com/web/updates/2016/08/removing-document-write

Can it insert a script node on head instead using dom methods?

**Comment by benaadams** [comment]
Suggestion is it won't currently break cdn fallback as the fallback script would be same origin

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by danroth27** [comment]
Probably related to #4722

**Comment by danroth27** [comment]
We should discuss what we want to do here. @NTaylorMullen could you please set up some time to discuss this and #4722?

**Comment by NTaylorMullen** [comment]
@SteveSandersonMS We've done some research here to find an alternative approach to `document.write` without luck. It seems that doing `document.createElement("script")` => `appendChild` doesn't ensure that the appended script tag is executed immediately. This means that following script tags cannot access the added script.

Do you know of any alternatives to doc.write/doc.createElement that ensure ordering?

**Comment by benaadams** [comment]
Initially could validate fallback is local rather than cross origin?

**Comment by SteveSandersonMS** [comment]
@NTaylorMullen From what I can tell, it doesn't look like we should expect there to be any way to inject scripts synchronously. `document.write` was the only approach that worked historically, but as we know, Chrome is trying to discourage that. At one point there *was* going to be a new approach (the `noncanonical-src` attribute, but that's been [removed from the spec](https://github.com/w3c/webappsec/commit/3629390e542a5bc181740f64c5e4d6d6bf4f053c)). 

> Suggestion is it won't currently break cdn fallback as the fallback script would be same origin

[Google's announcement](https://developers.google.com/web/updates/2016/08/removing-document-write) seems unclear about this. Their error message says `A Parser-blocking, cross-origin script...`, which implies they are only intervening for cross-origin scripts. But their list of criteria (on their announcement, search for "when all of the following conditions are met") makes no mention of origins at all, which implies the rule will be enforced even for same-origin. The [lengthy HN discussion](https://news.ycombinator.com/item?id=12604544) doesn't mention it either.

It's probably not something to worry about massively. Among other reasons, these patterns around loading third-party JS libraries from CDNs will become less common as developers increasingly use emerging tools like Webpack 2 and Rollup that perform deep dead-code elimination during bundling, with the result that everyone deploys their own custom stripped-down version of libraries (Angular/React/Bootstrap/etc.) that perfectly matches the usage in their own app. People won't think in terms of some globally-standard binary version of a particular 3rd-party library for much longer.

Plus, this is a *fallback* feature for recovery when something has already gone wrong (your CDN is down, but in a special way where requests fail immediately and don't hang). If the existing code can recover say 90% of the time (e.g., for non-Chrome browsers, or when Chrome detects a good network connection), that's still a better than nothing. Of course, if someone can find a way of doing 100%-reliable synchronous script injection then it would be great to switch over to it, even though the relevance of this feature will decline over time.

**Comment by NTaylorMullen** [comment]
@DamianEdwards I know you showed interest in nuking the feature all together. Does what @SteveSandersonMS said change your mind?

I feel that we should leave it as is because:

- There's no script injection behavior equivalent alternative available.
- If a fallback attempts to occur we do our absolute best to recover from unforeseen circumstances.
- It'd be a massive breaking change by Chrome to change the behavior of `document.write` (especially since it's the only synchronous script injection approach, I'd be shocked if their suggestion got enough traction to force them to change the behavior outright. I could see them potentially limiting this to cross-origin in which case our fallback approach would be sufficient.

**Comment by DamianEdwards** [comment]
Agreed, let's just stick in a holding pattern for now.

**Comment by NTaylorMullen** [comment]
Closing for now, if this becomes a broader issue we can re-open.
