### ISSUE TITLE
Can the Default Assembly Load Context be modified or replaced?

### ISSUE THREAD

**Issue by patricknolan** [aspnet/Mvc#5249]
Can the Default Assembly Load context be modified or replaced for a ASP.NET Core app?

**Comment by davidfowl** [comment]
You mean for Razor assemblies? What exactly are you asking?

**Comment by patricknolan** [comment]
Yes sorry I meant for Razor assemblies. I came across this interesting [article](http://shazwazza.com/post/custom-assembly-loading-with-aspnet-core/) but the solution is not compatible with the latest version of ASP.NET Core.

**Comment by davidfowl** [comment]
Yes, it's not compatible. Those interfaces are gone. Also that article has nothing to do with razor assemblies. What exactly are you trying to achieve?

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
