### ISSUE TITLE
Assemblies missing after build.

### ISSUE THREAD

**Issue by kazeshini178** [aspnet/Mvc#5250]
I currently have a project that has a mixture of PCL (.NetStandard) dependencies and normal .net 4.6 Class library dependencies.
When I build the ASP.net MVC project 3 of the required system dll's are not outputted (namely System.Runtime, System.ObjectModel & System.Collection.Concurrent) to the bin directory of the project.  
As seen in the image.
![image](https://cloud.githubusercontent.com/assets/17514276/18339786/c9302cee-75a1-11e6-9137-a7e938bcb20e.png)

When I build one of the normal .net projects, which itself references a .NetStandard PCL the missing dll's are outputted to the ASP.net bin directory even though the class has no reference to this directory and is the only project built as see below:
![image](https://cloud.githubusercontent.com/assets/17514276/18339826/03215626-75a2-11e6-8d03-7e58ddd50ede.png)
![image](https://cloud.githubusercontent.com/assets/17514276/18339834/11dfb7a2-75a2-11e6-8781-c2cae88e1282.png)

How would I be able to get the same result from just building the ASP.net project, which intern causes the class library to build due to being a dependency?

**Comment by pranavkm** [comment]
Could you file this issue in https://github.com/dotnet/cli?
