### ISSUE TITLE
Replacing IViewComponentHelper can unexpectedly break ViewComponent TagHelpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#5254]
If a user replaces the `IViewComponentHelper` with something that is not `IViewContextAware` you will get an invalid cast exception at runtime when trying to invoke a ViewComponent TagHelper. We should try to cast the `IViewComponentHelper` to `IViewContextAware` and if it can't be cast throw an acceptable exception.

**Comment by dougbu** [comment]
@NTaylorMullen we use `(helper as IViewContextAware)?.Contextualize(ViewContext)` everywhere else. Why isn't that correct here? Why `throw` at all?

**Comment by NTaylorMullen** [comment]
Hmm. Odd we do that elsewhere. I feel like throwing to let the user know that their app is incorrectly configured would be better than silently failing.

**Comment by NTaylorMullen** [comment]
Talked offline. You're absolutely right. If a service doesn't need to be contextualized to work then there's no reason for us to throw.

**Comment by danroth27** [comment]
If a user is using a feature and the component being resolved needs to be `ViewContext` aware and it *isn't* then we should throw.

**Comment by NTaylorMullen** [comment]
@danroth27 It's plausible that a user can create an `IViewComponentHelper` that does not require `ViewContext`.
