### ISSUE TITLE
HttpContent.Read* methods return empty content when using parameter binding in Web API controller

### ISSUE THREAD

**Issue by naamunds** [aspnet/Mvc#5258]
## Repro steps
1. In a Web API application, add a complex type parameter to a controller method.
2. In the controller method, read the content, e.g. with `Request.Content.ReadAsStringAsync`.
3. Run the app, and send an HTTP request with `application/json` content to the URI handled by the controller method.
## Expected behavior

The content returned by the `HttpContent.Read*` method represents the actual request's content.
## Actual behavior

The content returned by `HttpContent.Read*` is empty.

**Comment by naamunds** [comment]
[This StackOverflow answer](http://stackoverflow.com/a/12494758) suggests that in Web API the request content can only be read once by design, but I was able to successfully invoke the Request.Content.Read* methods multiple times within a controller method when not using parameter binding, so it appears that the issue is specific to parameter binding.

**Comment by davidfowl** [comment]
This doesn't have anything to do with ASP.NET Core does it?

**Comment by naamunds** [comment]
@davidfowl I encountered this issue in ASP.NET Web API 2.x (not Core).  Would https://github.com/aspnet/AspNetWebStack instead be the appropriate place to log this issue?

**Comment by dougbu** [comment]
That repo is not yet public -- we're working on the infrastructure. File issues at https://aspnetwebstack.codeplex.com/ until that changes.

**Comment by naamunds** [comment]
I see.  I've logged https://aspnetwebstack.codeplex.com/workitem/2315 for this issue.

**Comment by mahmoud690** [comment]
I have the same error.  I use the latest version of WebApi (5.2.4) but the problem still exists.

**Comment by dougbu** [comment]
Reopened in preparation for move to aspnet/AspNetWebStack

Side note: CodePlex is now in archived state. We never saw https://aspnetwebstack.codeplex.com/workitem/2315

**Comment by dougbu** [comment]
This issue was moved to aspnet/AspNetWebStack#150
