### ISSUE TITLE
Unicode symbols are turned into &#x....

### ISSUE THREAD

**Issue by qibucloud** [aspnet/Mvc#5264]
`<li><a href="/product-6360927752038367106558.html">&#x4EA7;&#x54C1;&#x540D;&#x79F0;</a>16/9/12 &#x4E0A;&#x5348;11:45:20</li>
    <li><a href="/product-6360927751939977806790.html">&#x4EA7;&#x54C1;&#x540D;&#x79F0;</a>16/9/12 &#x4E0A;&#x5348;11:45:19</li>
    <li><a href="/product-6360927751819425905892.html">&#x4EA7;&#x54C1;&#x540D;&#x79F0;</a>16/9/12 &#x4E0A;&#x5348;11:45:18</li>
    <li><a href="/product-6360927749969179902882.html">&#x4EA7;&#x54C1;&#x540D;&#x79F0;</a>16/9/12 &#x4E0A;&#x5348;11:44:59</li>
    <li><a href="/product-6360927750064749706371.html">&#x4EA7;&#x54C1;&#x540D;&#x79F0;</a>16/9/12 &#x4E0A;&#x5348;11:45:00</li>
    <li><a href="/product-6360927750155178409992.html">&#x4EA7;&#x54C1;&#x540D;&#x79F0;</a>16/9/12 &#x4E0A;&#x5348;11:45:01</li>
    <li><a href="/product-6360927749891772708861.html">&#x4EA7;&#x54C1;&#x540D;&#x79F0;</a>16/9/12 &#x4E0A;&#x5348;11:44:58</li>
    <li><a href="/product-6360927749756129504774.html">&#x4EA7;&#x54C1;&#x540D;&#x79F0;</a>16/9/12 &#x4E0A;&#x5348;11:44:57</li>
    <li><a href="/product-6360927748311920405662.html">&#x4EA7;&#x54C1;&#x540D;&#x79F0;</a>16/9/12 &#x4E0A;&#x5348;11:44:43</li>
    <li><a href="/product-6360927747622502901100.html">&#x4EA7;&#x54C1;&#x540D;&#x79F0;</a>16/9/12 &#x4E0A;&#x5348;11:44:36</li>`

**Comment by dougbu** [comment]
This is intended and avoids known issues w/ unencoded characters in an HTML response. Is everything displayed correctly in your browser?

See also duplicate issues such as #4195, #4596 and #4977.

**Comment by Eilon** [comment]
For an example of how to change this behavior, see the example here: https://github.com/aspnet/Razor/issues/807#issuecomment-236724126
