### ISSUE TITLE
Lost porperties migrating to latest version

### ISSUE THREAD

**Issue by chrilith** [aspnet/Mvc#5265]
Hi,

I just tried to migrate from rc1 to latest version of MVC (1.0.0).

I have an implementation of IApplicationModelConvention and I was using some properties that don't seem to exist anymore. So, is there something to replace:

- ControllerModel.AttributeRoutes
- ActionModel.AttributeRouteModel

Thanks!

**Comment by rynowak** [comment]
hi @chrilith - these moved to `model.Selectors`. Conceptually an action/controller has multiple ways of being selected if it has multiple different attribute routes. In general most stuff will have one selector.

**Comment by chrilith** [comment]
OK thanks!
