### ISSUE TITLE
Consider support for limiting the redirect urls on redirect results

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#5266]
Currently a redirect result will allow an application to redirect to any url without restriction. The url being redirected to in many web patterns is based on user input, which might lead to open redirect attacks if the web app doesn't take some precautions. A canonical scenario for this is when a user visits a protected resource in an application, gets redirected to the login page and wants to be redirected back to where he was after a successful log in. Other similar patterns involve performing some action on a website in the context of a larger user task, for example, performing an action that requires confirmation.

It would be good to have built in support for limiting the urls that a given action can redirect a user to, the  redirect result service could make use of a RedirectValidator service to determine if the url being redirected to is acceptable and preventing the redirect otherwise either by returning a 400 result or by redirecting to another page (like the index page or a page explaining the error).

A default implementation could be based on attributes that you specify on the controller or action, for example, if you consider the login/register case, it could be something like.

```
[LocalRedirect]
public async Task<IActionResult> SignUp(SignUpViewModel model, string returnUrl = null)
{
        ... 
        return Redirect(returnUrl);
        ...
}
```

```
[AllowedRedirects("http://www.contoso.com/confirm", "http://www.contoso.com/deny")]
public async Task<IActionResult> SignUp(SignUpViewModel model, string returnUrl = null)
{
        ... 
        return Redirect(returnUrl);
        ...
}
```

**Comment by Eilon** [comment]
cc @blowdart

**Comment by blowdart** [comment]
We have IsLocal() for identity. While OAuth redirects would go to a registered app url, that is very specialized and would need database access and knowledge of schemas. I'm not sure making something generic would help. Redirecting outside the app root shouldn't be a normal case at all.

**Comment by javiercn** [comment]
@blowdart To be clear, the main target for this is RedirectToLocal kind of scenarios for identity and similar scenarios you run into when building larger web applications. 
For OAuth redirects I would not use this, as that's way more dynamic (the url depends on configuration, there might be many redirect urls, etc) and probably something you want to check earlier in the processing on the request.
That said, I still think it's nice to have support out of the box for limiting the places an action can redirect to. 
If it's an attribute like LocalRedirect that you can just put on your controller its way less error prone than having a separate method and relying on calling the right method on each call site.

**Comment by blowdart** [comment]
I have no real objection, but it looks like a solution in search of a problem to me

**Comment by danroth27** [comment]
Closing since we don't really have a customer request for this.

**Comment by javiercn** [comment]
@sebastienros Didn't Orchard want something like this? 

Can we have a conversation about this?

**Comment by Eilon** [comment]
Closing again due to lack of demand/scenario.
