### ISSUE TITLE
save courses removed by jquery when click submit button

### ISSUE THREAD

**Issue by ahmedba** [aspnet/Mvc#5270]
**Problem**

when remove course then click submit not save changes although

it removed from client side by jquery

**Details** 

in edit view for every employee i need to do changes by remove or add new courses for employee

if i add new courses then click submit button it save what i do

but if i remove course from courses then click submit it will not save courses i removed

so that i need to check what is wrong in my code

my code working without any problem  but only have problem

i cannot save courses removed in database in employeecourse table when click submit 

employeecourse table have Id,EmployeeId,CourseId

jquery remove client side attached with my question 

**code** 

my code as following 

```
[HttpPost]  
        public ActionResult Edit(EditEmployeeVm model)  
        {  
            var emp = db.Employees.FirstOrDefault(f => f.Id == model.Id);  
            foreach (var couseid in model.CourseIds)  
            {  
                db.EmployeeCourses.Add(new EmployeeCourse { CourseId = couseid, EmployeeId = emp.Id });  
                db.SaveChanges();  
            }  
        
            return View();  
my(custom model) view model using for that  

 public class EditEmployeeVm  
    {  
        public int Id { set; get; }  
        public List<SelectListItem> Courses { get; set; }  
        public int[] CourseIds { set; get; }  
        public List<CourseVm> ExistingCourses { set; get; }  
    }  
    public class CourseVm  
    {  
        public int Id { set; get; }  
        public string Name { set; get; }  
    }  
}  
```
 to show what i need clearly see image below

![course wrong9](https://cloud.githubusercontent.com/assets/20745093/18471360/bb8af664-79b1-11e6-89b5-d8caef5d38fa.jpg)

[all project.txt](https://github.com/aspnet/Mvc/files/469578/all.project.txt)

**Comment by gdau** [comment]
Sorry maybe I'm misunderstanding what you're trying to do, but I don't see any code in your sample that actually deletes anything from the database? I can see you're managing the list of course id's on the client side but then when you submit, the id that was removed is no longer submitted and there is no code there that would delete anything.

**Comment by ahmedba** [comment]
code of remove in client side found in textfile allproject.txt
but code for delete in server side i not have code for delete in server side
can you tell me how to delete these courses in server side if possible

**Comment by ahmedba** [comment]
i use this code for remove but also nothing removed
```
 public ActionResult Edit(EditEmployeeVm model)
        {
            var existingCourseIds = db.EmployeeCourses.Where(g => g.EmployeeId == model.Id && g.CourseId != null)
                             .Select(f => f.CourseId.Value).ToList();
            var removedCourseIds = existingCourseIds.Except(model.CourseIds);
            //Now loop through these and delete it from db
            foreach (var removedCourseId in removedCourseIds)
            {
                var x = db.EmployeeCourses.Find(removedCourseId);
                if (x!=null)
                {
                    db.EmployeeCourses.Remove(x);
                }
               
              //  db.EmployeeCourses.Remove(x => x.CourseId == removedCourseId);
                db.SaveChanges();
            }
            return View();
        }
and in jquery i using following

 <script>
        $(function () {
            $(document).on("click", ".remove", function (e) {
                e.preventDefault();
                $(this).closest(".course-item").remove();
            });
            $('#AvailableCourses').change(function () {
                var val = $(this).val();
                var text = $("#AvailableCourses option:selected").text();
                var existingCourses = $("input[name='CourseIds']")
                    .map(function () { return this.value; }).get();

                if (existingCourses.indexOf(val) === -1) {
                    // Not exist. Add new
                    var newItem = $("<div/>").addClass("course-item")
              .append(text + ' <a href="#" class="remove" data-id="' + val + '">Remove </a>');
                    newItem.append('<input type="text" name="CourseIds" value="' + val + '" />');

                    $("#items").append(newItem);
                }
            });
        });
        </script>
```

**Comment by ahmedba** [comment]
can any one help me if possible

**Comment by rjwebdev** [comment]
the way i would do it, is create an extra action in your controller, for example DeleteCoure(int courseId, int employeeId). In this action, delete the course with the id passed to this action for the employee with passed id

If someone clicks the delete button, perform an ajax call to this controller action and when deleting the course is done, fetching the other, existing courses and send them back.

Here you have a couple of options: you can send the existing courses back as json and then render the content of the course list in your view in javascript OR you can create a partial view that contains the list of courses and return a partialview from the delete action and replace the content of the original partial view with the one passed back

**Comment by Eilon** [comment]
Hi, this seems like a general usage question about ASP.NET Core MVC, so we recommend asking it in a forum that is better suited to that type of question, such as StackOverflow, using the [asp.net-core-mvc](https://stackoverflow.com/questions/tagged/asp.net-core-mvc) tag.
