### ISSUE TITLE
Move HttpContext property from OutputFormatterWriteContext to OutputFormatterCanWriteContext

### ISSUE THREAD

**Issue by khellang** [aspnet/Mvc#5272]
I'm doing some resource versioning using an `IOutputFormatter` and would like to provide other mechanisms of versioning than just using the `Accept` header, like using a custom header, or even the URI for that matter.

This is not possible today (AFAIK) because the`HttpContext` property sits in `OutputFormatterWriteContext` rather than `OutputFormatterCanWriteContext`.

Would it be possible to move the property up a level? See https://github.com/aspnet/Mvc/compare/dev...khellang:move-http-context-up for an idea of what I'm talking about.

**Comment by danroth27** [comment]
This sounds reasonable to me. @Eilon @rynowak Any concerns?

**Comment by rynowak** [comment]
yeah seems fine, this just seems like an oversight on our part

**Comment by Eilon** [comment]
Looks like https://github.com/aspnet/Mvc/pull/5316 was merged but we forgot to close this issue.
