### ISSUE TITLE
Working with IViewLocationExpander in mvc

### ISSUE THREAD

**Issue by rpundlik** [aspnet/Mvc#5279]
I want to render the view from custom location, so for that I have implemented `IViewLocationExpander `interface in a class. I have registered the same class in startup file as follows.

**Startup.cs file**

```
public void ConfigureServices(IServiceCollection services)
    {
       .....
        //Render view from custom location.
        services.Configure<RazorViewEngineOptions>(options =>
        {
            options.ViewLocationExpanders.Add(new CustomViewLocationExpander());
        });
        ....
    }
```
**CustomViewLocationExpander Class**
```

public class CustomViewLocationExpander : IViewLocationExpander
{
    public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
    {

        var session = context.ActionContext.HttpContext.RequestServices.GetRequiredService<SessionServices>();
        string folderName = session.GetSession<string>("ApplicationType");

        viewLocations = viewLocations.Select(f => f.Replace("/Views/", "/" + folderName + "/"));


        return viewLocations;
    }

    public void PopulateValues(ViewLocationExpanderContext context)
    {

    }
}
```
and my application views structure is as follows

http://i.stack.imgur.com/HyOhW.png

My issue is if I access the Views/Login view from `ViewsFrontend` folder from the url 
[http://localhost:56739/trainee/Login/myclientname]()
and immediately change the url in browser as [http://localhost:56739/admin/Login/myclientname](), then in this case it still refers and renders views from `ViewsFrontend` folder, which is a previous folder and it should refer to `ViewsBackend` folder.

Url with **`trainee`** should refer to `ViewsFrontend` folder and with **`admin`** should refer to `ViewsBackend` folder.

And after changing the url in browser it only calls `PopulateValues` method but not the `ExpandViewLocations` method. My view names are same in both of the folders. I know this is happening because of caching, it seems it only caching the view name and not the entire path of the view.

So how can re-configure this class OR make `ViewLocationExpanderContext` null to work it for other folder ?

Thanks for the help !

**Comment by dougbu** [comment]
Caching includes the `Values` dictionary in its lookup. Unless the `PopulateValues()` method adds distinct information to `ViewLocationExpanderContext.Values`, the `ExpandViewLocations()` method will be called just once per original file name i.e. the initial information is cached from then on.

Move the `folderName` calculation into `PopulateValues()` and add that to the `Values` dictionary w/ a constant key.

**Comment by pranavkm** [comment]
Copying my answer from SO:

`PopulateValues` exists as a way to specify parameters that your view lookup would vary by on a per-request basis. Since you're not populating it, the view engine uses cached values from an earlier request. Add application type to PopulateValues and ExpandValues should get called:

```C#
public class CustomViewLocationExpander : IViewLocationExpander
{
    public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
    {
        string folderName = context.Values["ApplicationType"];
        viewLocations = viewLocations.Select(f => f.Replace("/Views/", "/" + folderName + "/"));

        return viewLocations;
    }

    public void PopulateValues(ViewLocationExpanderContext context)
    {
        var session = context.ActionContext.HttpContext.RequestServices.GetRequiredService<SessionServices>();
        string applicationType = session.GetSession<string>("ApplicationType");
        context.Values["ApplicationType"] = applicationType;
    }
}
```

**Comment by BrainCrumbz** [comment]
@dougbu thanks for your comment. That was somehow expanded in a [SO answer](http://stackoverflow.com/a/41435134/540776). The net result is that this point should be made more clear in official documentation. For example, current sentence found in code comments is not totally clear:

> The calculated values are used to determine if the view location has changed since the last time it was located.

Not sure how/to who submit an issue/PR for this.

**Comment by dougbu** [comment]
@BrainCrumbz this is a closed issue. If you think the [`IViewLocationExpander`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/IViewLocationExpander.cs) docs need further improvement, please open a new issue in this repo.
