### ISSUE TITLE
Working with cookie in mvc

### ISSUE THREAD

**Issue by rpundlik** [aspnet/Mvc#5280]
I have 2 different urls to login into the application as follows

For Trainee:- [http://localhost:56739/trainee/Login/myclientname]()

For Admin:- [http://localhost:56739/admin/Login/myclientname]()

I am logging into the application using the below default login implementation

`var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: true);`

What i observed the method `PasswordSignInAsync `is creating the cookie for logged in user.

However my issue is if I logged in using `trainee` url and tries to access the `admin` url then user is directly getting logged in into the admin application without asking for login, because of the cookie. Means the cookie is getting accessed/shared between trainee and admin.

My views are different for `admin/trainee` but they are in same project with below folder structure. http://i.stack.imgur.com/HyOhW.png

When i checked in the layout page for below line of code when switching between trainee and admin, this `IsAuthenticated`coming true though the admin is still not logged into the application and vice versa.

 `@if (User.Identity.IsAuthenticated)`

I am using core identity framework for user authentication.

How can i maintain the separate cookie while switching between `admin/trainee` ?

Thanks for the help !

**Comment by javiercn** [comment]
This is more an identity question. @haok can you help?

**Comment by HaoK** [comment]
You can configure the authentication scheme for the admin app to be different
```
  AddIdentity(options => options.Cookies.ApplicationCookie.AuthenticationScheme = "Admin")
```

Then check for an identity with AuthenticationType == "Admin" instead of any authenticated identity in your view or you can use `signInManager.IsSignedIn(User)

**Comment by rpundlik** [comment]
Can you please provide some example/source code of it ? as I am not finding the clear way how it should be done ?

**Comment by rpundlik** [comment]
@HaoK Can you please update with my latest comment ?

**Comment by HaoK** [comment]
You should really use a claim for the user to determine which role they are (user vs admin) as opposed to using different urls.  Then you could just use IsInRole("admin") instead.  That is the expected usage for the scenario you are targetting.

**Comment by rpundlik** [comment]
@HaoK Yeah... I have used the same now.. so I am able to work independently for admin/trainee user.
However, I cannot use `User.IsInRole("Admin")` as soon as I signed into the application, I need to redirect some action method(For e.g.Dashboard) and there I am able to get the true/false value return by `IsInRole` method.

If I check in the same Login method, then it always returns false, why is it so ? 
And I am first authenticating the user and then checking roles of user(authorization) OR do I need to vice versa ?
