### ISSUE TITLE
Error message of Custom ValidationAttribute localization

### ISSUE THREAD

**Issue by akanmuratcimen** [aspnet/Mvc#5282]
I have written my own validation rule with extending ValidationAttribute but the error message can not being localized. The code samples below:

```
public class NotEqualToAttribute : ValidationAttribute {
	public NotEqualToAttribute(object value) {
	    Value = value;
	}

	public override string FormatErrorMessage(string name) {
	    return string.Format(CultureInfo.CurrentCulture, ErrorMessageString, name, Convert.ToString(Value));
	}

	public override bool IsValid(object value) {
	    return !string.Equals(Convert.ToString(Value), Convert.ToString(value), StringComparison.CurrentCultureIgnoreCase);
	}

	public object Value { get; set; }
}
```

```
[NotEqualTo("test", ErrorMessage = "The {0} value can not be equal to {1}.")]
public string Content { get; set; }
```

Am I missing something or is there a bug in this case?

**Comment by danroth27** [comment]
@ryanbrandenburg could you please update the https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.LocalizationSample.Web sample to show how to localize a custom validation attribute? 

We should also update the docs to cover this (https://github.com/aspnet/Docs/issues/1878).

**Comment by ryanbrandenburg** [comment]
Localization of `ValidationAttribute` items doesn't happen within the attribute, it happens at the attribute adapters. I've created a PR showcasing this [here](https://github.com/aspnet/Entropy/pull/168).

**Comment by ryanbrandenburg** [comment]
That PR is merged in now so I'm going to close this out, but let us know if you have any questions.
