### ISSUE TITLE
Fast path in 'ViewBuffer' implementation

### ISSUE THREAD

**Issue by Yves57** [aspnet/Mvc#5284]
I have seen that the `ViewBuffer` instances are created several times for a single Razor Page rendering (for example 4 times for the MvcSandbox sample). And they have often only one `ViewBufferPage` inside.

I created a quick proto with a new `ViewBufferPages` struct (not class!) with a fast path when there is only one page:
```
internal struct ViewBufferPages
{
   private ViewBufferPage _page;
   private List<ViewBufferPage> _pages;

   internal int Count......
   internal void Add(ViewBufferPage page)....
   internal ViewBufferPage this[int index].....
   internal void Clear()....
   internal IList<ViewBufferPage> AsList()....
}
```

And it replaces the line `Pages = new List<ViewBufferPage>();`. It may be an interesting idea to avoid allocating  a `List<ViewBufferPage>` for only one page?

Another thing: I have seen that `ViewBufferPage` is not a struct. I'm not sure if it could be better to be a struct instead of a class?

**Comment by pranavkm** [comment]
> It may be an interesting idea to avoid allocating a List<ViewBufferPage> for only one page?

Do you have before and after profiles for what the savings are for doing this? Adding an upgradeable storage model adds a bunch of complexity to the code so it would be nice to know that it's worth the effort \ maintenance costs.

**Comment by Yves57** [comment]
Profiling on 100 requests of `MvcSandbox` with the `List<ViewBufferPage>` replacement, but still with `ViewBufferPage` as class...

Before:
![before](https://cloud.githubusercontent.com/assets/11701094/18585354/b694e8e2-7c16-11e6-8e1e-0449eda61484.png)
After:
![after](https://cloud.githubusercontent.com/assets/11701094/18585360/be98757c-7c16-11e6-9462-aaf4ad2f2efe.png)

The `ViewBuffer` constructor is not visible anymore because there is no more allocation inside. And `AppendHtml()` allocates less memory because nothing  is added to a list.

**Comment by pranavkm** [comment]
Just diffing the inclusive bytes of the highlighted lines (which probably isn't the right way to go about this), work out to about 300 bytes \ request. In addition, the MvcSandbox isn't representative of most pages so we might the List when we have a page with more things in it. I'm not sure the savings here is worth the effort.

**Comment by Yves57** [comment]
I agree that the size benefit is not huge. But it was more to decrease allocation __count__ (8 allocations per request in this case) than allocation __size__ that was intersesting for the GC, in my opinion.
But no problem, it was just an idea :-).

**Comment by rynowak** [comment]
Improving this in general is something we'd like to do. The view buffering system is pretty sophisticated in the large sense, but there are probably plenty of small wins. 

It would be good to look at a larger benchmark

**Comment by Yves57** [comment]
@rynowak 
> It would be good to look at a larger benchmark

I'm not sure to understand. Is it a general remark, or you would like me to benchmark different views to see how `ViewBuffer` and `ViewBufferPage` instances are allocated?

**Comment by rynowak** [comment]
@Yves57 - yeah, it would be good to run this on some larger code samples. Mostly we don't really need to pick nits on a "hello world" kind of application, but we do really want to make sure a change like this is beneficial for a larger site. 

If you've got a branch with your changes someone here could take a look, or you could bring in the project via global.json and try it out yourself on something like aspnet/MusicStore

**Comment by Yves57** [comment]
@rynowak 
I give you profiling results make for 10 requests on MusicStore home page. But profiling is still a mystery for me: the results indicates that `AspNetCore.Mvc.Controller.View()` has allocated 10 objects, so it shows that the right number of requests has been processed. But for example the allocations in `ViewBuffer` is not a multiple of 10...

Before:
![before](https://cloud.githubusercontent.com/assets/11701094/18743557/d89db20a-80b9-11e6-9323-ae18d7be752f.png)

After:
![after](https://cloud.githubusercontent.com/assets/11701094/18743562/e195a25a-80b9-11e6-82f4-d8cb216658a8.png)

Anyway you can see that the highlighted lines go down from 1265 inclusive allocations to 716 (so around 55 less allocations per request).

To do a more precise (and repetable) double check, I have added traces to count the number of `ViewBuffer` instances and there page count:

 | Home page | Genre=Rock page
-----|-----------|-----------------
0 or 1 page ViewBuffer count | 27 | 210
2 or more page ViewBuffer count | 4 | 7

**Comment by rynowak** [comment]
This seems like something we'd be interested in. The important thing here is that we want an any changes we do to be in improvement in both small cases and large cases - or to be the same in small cases and and improvement in large cases.

**Comment by Yves57** [comment]
Do you wnat that I prepare a PR?

**Comment by rynowak** [comment]
yes, please

**Comment by Yves57** [comment]
@rynowak I suppose that you can close the issue now?
And just for curiosity, what means "(connect 4)" in your last comment of #5318?

**Comment by davidfowl** [comment]
@Yves57 https://www.youtube.com/watch?v=oUkCPPJ1CNw

**Comment by Yves57** [comment]
@davidfowl @rynowak 
Ok :-) It is called "puissance 4" (would be translated in "power 4") in France.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/ed3b750ad2e22d2e970a9b571e55ebefbff405e7
