### ISSUE TITLE
The property SslPort has a legacy name

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/Mvc#5285]
The property `SslPort` in the class `MvcOptions` has a legacy name.

SSL is no longer used as it has been superseded by TLS. This property should be named `TlsPort` or the more technology neutral `HttpsPort`.

**Comment by danroth27** [comment]
Thanks for the feedback. Unfortunately renaming the API at this point would be a breaking change and SSL is still widely recognized (if not 100% technically accurate).
