### ISSUE TITLE
ASP.NET MVC Core - View with a for loop is not correctly displaying the data sent via a LINQ OUTER JOIN from a Controller

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/Mvc#5292]
**NOTE**: 

1. To test the following scenario you can download a demo repo from GitHub [here](https://github.com/saf-itpro/ASP_Core_Blogs_GitHub-master).
This ASP.NET MVC Core app was created using VS2015 and from this [official ASP.NET Core tutorial](https://docs.efproject.net/en/latest/platforms/aspnetcore/new-db.html) (with some modifications). I'm using `EF Core`

2. The View displays the correct data if, instead of `for` loop, foreach loop is used. But the `foreach` loop has problems when submitting the data (In a `foreach` loop, the model binder uses the name property of the input elements from the rendered html. Using a for loop with an indexer is the only way to have unique names that the model binder can associate to the model. Ref: [[This](http://stackoverflow.com/a/30094943/1232087) and [this] (http://haacked.com/archive/2008/10/23/model-binding-to-a-list.aspx/) )

**ISSUE**: 

When you click on dropdownlist to select a Year and click on GO button, the POST method `Test(...)` is supposed to display Blogs table records along with related Posts created during the selected year. The LINQ query for that purpose uses a LEFT OUTER JOIN that selects all the records for the selected year along with the records that do not meet join `Blogs.BlogID = Posts.BlogID`. Using Debuger, I've verified that the query is sending the correct records to the View and that the Model.Count() in the `for` loop in View is correct. But, although the number of records in the view is always correct the records displayed are not necessarily the records from the selected year.

**Models**:
```
public class BloggingContext : DbContext
{
    public BloggingContext(DbContextOptions<BloggingContext> options)
        : base(options)
    { }

    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }

    public IList<Post> Posts { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
    public int PostYear { get; set; }
    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}
```

**Controller**: Only relevant action methods are shown.
```
public class BlogsController : Controller
    {
        private readonly BloggingContext _context;

        public BlogsController(BloggingContext context)
        {
            _context = context;    
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            return View(_context.Blogs.ToList());
        }

        // GET: /Blogs/Test
        [HttpGet]
        public async Task<IActionResult> Test(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            ViewBag.YearsList = Enumerable.Range(1996, 29).Select(g => new SelectListItem { Value = g.ToString(), Text = g.ToString() }).ToList();

            //return View(await _context.Blogs.Include(p => p.Posts).ToListAsync());
            var qrVM = from b in _context.Blogs
                        join p in _context.Posts on b.BlogId equals p.BlogId into bp
                        from c in bp.DefaultIfEmpty()
                        select new BlogsWithRelatedPostsViewModel { BlogID = b.BlogId, PostID = (c == null ? 0 : c.PostId), Url = b.Url, Title = (c == null ? string.Empty : c.Title), Content = (c == null ? string.Empty : c.Content) };
            
            return View(await qrVM.ToListAsync());
        }

        // POST: /Blogs/Test
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Test(IList<BlogsWithRelatedPostsViewModel> model, string GO, int currentlySelectedIndex, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            ViewBag.YearsList = Enumerable.Range(1996, 29).Select(g => new SelectListItem { Value = g.ToString(), Text = g.ToString() }).ToList();

            if (!string.IsNullOrEmpty(GO))
            {
                var qrVM = from b in _context.Blogs
                           join p in _context.Posts on b.BlogId equals p.BlogId into bp
                           from c in bp.DefaultIfEmpty()
                           where c == null? true : c.PostYear.Equals(currentlySelectedIndex)
                           select new BlogsWithRelatedPostsViewModel { BlogID = b.BlogId, PostID = (c == null ? 0 : c.PostId), Url = b.Url, Title = (c == null ? string.Empty : c.Title), Content = (c == null ? string.Empty : c.Content) };
                return View(await qrVM.ToListAsync());
            }
            else if (ModelState.IsValid)
            {
                foreach (var item in model)
                {
                    var oPost = _context.Posts.Where(r => r.PostId.Equals(item.PostID)).FirstOrDefault();
                    if (oPost != null)
                    {
                        oPost.Title = item.Title;
                        oPost.Content = item.Content;
                        oPost.PostYear = currentlySelectedIndex;
                        oPost.BlogId = item.BlogID; //according to new post below the blogId should exist for a newly created port - but just in case
                    }
                    else
                    {
                        if (item.PostID == 0)
                        {
                            Post oPostNew = new Post { BlogId = item.BlogID, Title = item.Title, Content = item.Content, PostYear = currentlySelectedIndex }; //need to use currentlySelectedIndex intead of item.FiscalYear in case of adding a record
                            _context.Add(oPostNew);
                        }

                    }
                }
                await _context.SaveChangesAsync();
                //return RedirectToLocal(returnUrl);
                return View(model);
            }

            // If we got this far, something failed, redisplay form
            return View();
        }
}
```

**Test.cshtml View**
```
html
@model IList<ASP_Core_Blogs.Models.BlogPostViewModels.BlogsWithRelatedPostsViewModel>

<div class="row">
    <div class="col-md-12">
        <form asp-controller="Blogs" asp-action="Test" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
            @{
                IEnumerable<SelectListItem> yearsList = (IEnumerable<SelectListItem>)ViewBag.YearsList;
                var currentlySelectedIndex = 0; // Currently selected index (usually will come from model)
            }
            <strong>Select a Post Year</strong>
            <h6>Choose a year and a URL to begin:</h6>
            <label>Year:</label><select asp-for="@currentlySelectedIndex" asp-items="yearsList"></select><input type="submit" class="btn btn-default" name="GO" value="GO" />
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Url</th>
                        <th>Title</th>
                        <th>Content</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i=0; i< Model.Count(); i++)
                    {
                        <tr>
                            <td>@Html.HiddenFor(r => r[i].BlogID)</td>
                            <td>@Html.HiddenFor(r => r[i].PostID)</td>
                            <td>
                                @Html.TextBoxFor(r => r[i].Url)
                            </td>
                            <td>
                                @Html.TextBoxFor(r => r[i].Title)
                            </td>
                            <td>
                                @Html.TextBoxFor(r => r[i].Content)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <button type="submit" class="btn btn-default">Save</button>
        </form>
    </div>
</div>
```

**Demo**:

1. Download a demo repo from GitHub [here](https://github.com/saf-itpro/ASP_Core_Blogs_GitHub-master). Delete the folder `.vs` from the project folder. Open the project in VS2015 (note: if project hangs(sometimes it does - a know issue), force close it by using Task Manager in Windows OS and reopen it).

2. Change the connection string in `StartUp.cs` and `appsettings.json` file to your choice.

3. Run `PM> update-database -context ApplicationDbContext` and  `PM> update-database -context BloggingContext`

4. Run the application and click on the `Blog Create` link on the left side of Home page to create five blogs as follows:
![image](https://cloud.githubusercontent.com/assets/10931726/18613024/5fcb30ac-7d3d-11e6-99aa-a5b288cc8172.png)

5. On the Home page, click on the `Blogs Index` link to verify the five blogs created.

6. Go to the corresponding database and create 4 records in Posts table as follows:
![image](https://cloud.githubusercontent.com/assets/10931726/18613064/fc3064b6-7d3e-11e6-966e-ac8004be7e9f.png)

7. When you click on the `Test` link on the left of Home page, it will call the GET method `Test(...)` that will correctly display all Blogs with or without a join on Posts table as shown in the image below:
![1996_all](https://cloud.githubusercontent.com/assets/10931726/18613085/94616c1c-7d3f-11e6-88ca-81af4b8b123d.PNG)

8. From drop downlist select 1998 and click on GO button. It will call the POST method `Test(...)` that will correctly send the records with BlogID 1, 3, and 5 to the `Test.chtml` view. But the view is displaying wrong records (BlogID 1,2,3) as shown in the image below:
![1998_1_2_3](https://cloud.githubusercontent.com/assets/10931726/18613100/f049a8aa-7d3f-11e6-98d1-363f69fd8cfa.png)
The above wrong display can also be verified from the following portion of html source page of the above view. Likewise, if you select year 1999, view should display 2nd and 5th records but if displays 1st and 2nd record. Same is true for other year 2000:
```
html
<tr>
    <td><input data-val="true" data-val-required="The BlogID field is required." id="z0__BlogID" name="[0].BlogID" type="hidden" value="1" /></td>
    <td><input data-val="true" data-val-required="The PostID field is required." id="z0__PostID" name="[0].PostID" type="hidden" value="1" /></td>
    <td>
        <input id="z0__Url" name="[0].Url" type="text" value="blog1@test.com" />
    </td>
    <td>
        <input id="z0__Title" name="[0].Title" type="text" value="Title1" />
    </td>
    <td>
        <input id="z0__Content" name="[0].Content" type="text" value="Content1" />
    </td>
    </tr>
    <tr>
    <td><input data-val="true" data-val-required="The BlogID field is required." id="z1__BlogID" name="[1].BlogID" type="hidden" value="2" /></td>
    <td><input data-val="true" data-val-required="The PostID field is required." id="z1__PostID" name="[1].PostID" type="hidden" value="2" /></td>
    <td>
        <input id="z1__Url" name="[1].Url" type="text" value="blog2@test.com" />
    </td>
    <td>
        <input id="z1__Title" name="[1].Title" type="text" value="Title2" />
    </td>
    <td>
        <input id="z1__Content" name="[1].Content" type="text" value="Content2" />
    </td>
    </tr>
    <tr>
    <td><input data-val="true" data-val-required="The BlogID field is required." id="z2__BlogID" name="[2].BlogID" type="hidden" value="3" /></td>
    <td><input data-val="true" data-val-required="The PostID field is required." id="z2__PostID" name="[2].PostID" type="hidden" value="3" /></td>
    <td>
        <input id="z2__Url" name="[2].Url" type="text" value="blog3@test.com" />
    </td>
    <td>
        <input id="z2__Title" name="[2].Title" type="text" value="Title3" />
    </td>
    <td>
        <input id="z2__Content" name="[2].Content" type="text" value="Content3" />
    </td>
</tr>
```

**Comment by dougbu** [comment]
Could you please check:

1. The behaviour doesn't change when using `Model.Count` instead of Linq's `Count()` extension method?
2. You are changing nothing else between tests besides `for (...)` -> `foreach (var item in Model)` and `r => r[i].Property` -> `item.Property`?
3. The `IList<BlogsWithRelatedPostsViewModel>` contains exactly what you expect? E.g.
``` c#
var list = await qrVM.ToListAsync();
View(list); // Set breakpoint here and see what's in list.
```

**Comment by saf-itpro** [comment]
@dougbu Per your suggestion, I verified:

1. Replacing `Model.Count()` with `Model.Count` does not change the behaviour

2. When changing `foreach(...)` to `for(...)` I change `IEnumerable<.....>` to `IList<....>` in the @model declaration on top of View.
3. `IList<BlogsWithRelatedPostsViewModel>` indeed contains exactly what I expect. E.g. when selecting year as 1998 it `correctly` displays blogID 1,3, and 5 as shown in the screenshots in debug mode below:

![1998_1](https://cloud.githubusercontent.com/assets/10931726/18677631/629c13d2-7f27-11e6-8438-31dfda227d7b.png)
![1998_3](https://cloud.githubusercontent.com/assets/10931726/18677643/70142860-7f27-11e6-9c63-4101c9e0dfec.png)
![1998_5](https://cloud.githubusercontent.com/assets/10931726/18677647/7859d740-7f27-11e6-94a0-d8e7c03cdad9.png)

**Comment by saf-itpro** [comment]
@dougbu In addition **please note** this behaviour does not happen when using `INNER JOIN`. It's only happening with `OUTER JOIN`.

**Comment by saf-itpro** [comment]
@dougbu I just noticed that the issue occurs with both the `INNER` and `OUTER JOIN`. My observation with **INNER JOIN** was as follows:

1.  If you first select a Year that does NOT have any records  (e.g. 2005) it would correctly display  no records. And then after that if you select a Year that does have some records (e.g. 1998) it would correctly display the first and third records. But if you again select another Year that does have some record(s), e.g. 1999, it would just display the top record (instead of 2nd record). On the other hand if you select a Year again that does not have any record(s) (e.g. 1996) it would correct display no records and then if you select a year that does have some records, e.g. 2000, it would correctly display only 4th record.
So, it seems for INNER JOIN it works only if: you first select a Year that does not have a record and then select a Year that has some record(s). But if you consecutively select two years one by one that have records then the results are unpredictable.

**Comment by dougbu** [comment]
@saf-itpro with the new information you have, please again check whether the collection is correct in the action i.e. verify the `IList<BlogsWithRelatedPostsViewModel>` before the call to `View()`. I suspect this is an EF issue.

**Comment by saf-itpro** [comment]
@dougbu I checked again. The EF is still returning the correct data. It seems it may have something to do with Model Binder that may, in some cases keeping the old data values.

**Comment by danroth27** [comment]
@saf-itpro You're hypothesis is correct and the behavior you are seeing is expected. When you hit Go you are posting back all of the data in the form and the model expressions are actually bound to the model state with that posted data. 

To address this issue I think you should separate out the year filter as a separate form that does a GET request.
