### ISSUE TITLE
Discussion: Refactoring of registering order for MVC default services

### ISSUE THREAD

**Issue by ivamax9** [aspnet/Mvc#5293]
I see several MVC services whose extensions for `IMvcCoreBuilder` calls more than once while application starts. In my test project `MvcServiceCollectionExtensions.AddMvc` method calls only once from `Startup.ConfigureServices` method.

1. Views registration does via `MvcViewFeaturesMvcCoreBuilderExtensions.AddViews` and it calls 2 times (once directly from `MvcServiceCollectionExtensions.AddMvc` and second once from `MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngine`, which also calls from `MvcServiceCollectionExtensions.AddMvc`)
2. Data annotations registration does via `MvcDataAnnotationsMvcCoreBuilderExtensions.AddDataAnnotations` and it calls 3 times (twice because  `MvcViewFeaturesMvcCoreBuilderExtensions.AddViews` executes twice and third once directly from `MvcServiceCollectionExtensions.AddMvc`)

Are there any reasons for this registration flow?

**Comment by dougbu** [comment]
The registrations are all conditional and should not be problematic in themselves. Does the current excess registrations cause an issue in your scenarios?

FYI the duplication probably comes from us ensuring the registrations all occur in common `Startup` classes.

**Comment by ivamax9** [comment]
@dougbu nope, it isn't cause any issues. I've just wanted to pay attention on it, because for me redundant calls looks strange.

**Comment by rynowak** [comment]
These calls are designed to be idempotent and also include their dependencies. A bunch of stuff is reliant on data annotations (for example) and so it harmlessly gets called multiple times.
