### ISSUE TITLE
Could Not Upgrade

### ISSUE THREAD

**Issue by adamreed90** [aspnet/Mvc#5294]
When attempting to upgrade `Microsoft.AspNet.Razor`:
Could not install package 'Microsoft.AspNet.Mvc 6.0.0-beta1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

When attempting to upgrade `Microsoft.AspNet.Mvc`:
`Failed to add reference. The package 'Microsoft.AspNet.Mvc.Core' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance`

**Comment by davidfowl** [comment]
Makes sense, those are old packages. 6.0.0-beta1 is before things were renamed to ASP.NET Core. What exactly are you trying to do? Upgrade from RC1 to RTM? If so follow this guide https://docs.asp.net/en/latest/migration/rc1-to-rtm.html?highlight=upgrade

**Comment by adamreed90** [comment]
I am not using .NET Core, I started a new ASP.NET Project and attempted to upgrade my packages, and it is trying to upgrade to something unsupported.

**Comment by davidfowl** [comment]
These repositories are for ASP.NET Core which from the look of it, you're trying to use...

**Comment by adamreed90** [comment]
@davidfowl I created a new project in Visual Studio 2015, ASP.NET Web Application (.NET Framework), I picked MVC from the ASP.NET 4.6.2 Templates, I then went to Package Manager, and selected Upgrade and checked Include Prerelease, and these errors were produced. I am not using .NET Core.

**Comment by davidfowl** [comment]
Did you look at the error message you posted? Here it is.

> When attempting to upgrade Microsoft.AspNet.Mvc:
Failed to add reference. The package 'Microsoft.AspNet.Mvc.Core' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance

**Comment by davidfowl** [comment]
This is the version you're probably looking for https://www.nuget.org/packages/Microsoft.AspNet.Mvc/5.2.3.

**Comment by adamreed90** [comment]
Yes,  that's what I'm saying just clicking upgrade  on a new empty project template,  and it is trying to reference core as in a dependency of the latest prerelease version of Microsoft.AspNet.Mvc is Mvc.Core. I am unable to upgrade Microsoft.AspNet.Razor or Microsoft.AspNet.Mvc because of it.

**Comment by davidfowl** [comment]
Disable pre-release. This is the reason we renamed it to AspNetCore in the first place.

@DamianEdwards  @Eilon should we unlist all of the previous packages?

**Comment by adamreed90** [comment]
@davidfowl Thanks, I had done that, just wanted to let someone know it was doing this. I assumed it was not intended behavior. =D

**Comment by Eilon** [comment]
@davidfowl yeah probably a good idea to unlist all the old/dead packages. I'll make it so.

**Comment by Eilon** [comment]
Ok this is now done thanks to @pranavkm . We unlisted all packages that matched an id that had a previous RTM release associated with it, but was meant for ASP.NET Core only.

This is the full list of packages we unlisted from nuget.org:

```
Microsoft.AspNet.Cors	1.0.0-beta4
Microsoft.AspNet.Cors	1.0.0-beta5
Microsoft.AspNet.Cors	1.0.0-beta6
Microsoft.AspNet.Cors	1.0.0-beta7
Microsoft.AspNet.Cors	6.0.0-beta8
Microsoft.AspNet.Cors	6.0.0-rc1-final
Microsoft.AspNet.Identity.EntityFramework	3.0.0-beta1
Microsoft.AspNet.Identity.EntityFramework	3.0.0-beta2
Microsoft.AspNet.Identity.EntityFramework	3.0.0-beta3
Microsoft.AspNet.Identity.EntityFramework	3.0.0-beta4
Microsoft.AspNet.Identity.EntityFramework	3.0.0-beta5
Microsoft.AspNet.Identity.EntityFramework	3.0.0-beta6
Microsoft.AspNet.Identity.EntityFramework	3.0.0-beta7
Microsoft.AspNet.Identity.EntityFramework	3.0.0-beta8
Microsoft.AspNet.Identity.EntityFramework	3.0.0-rc1-final
Microsoft.AspNet.Mvc	6.0.0-beta1
Microsoft.AspNet.Mvc	6.0.0-beta2
Microsoft.AspNet.Mvc	6.0.0-beta3
Microsoft.AspNet.Mvc	6.0.0-beta4
Microsoft.AspNet.Mvc	6.0.0-beta5
Microsoft.AspNet.Mvc	6.0.0-beta6
Microsoft.AspNet.Mvc	6.0.0-beta7
Microsoft.AspNet.Mvc	6.0.0-beta8
Microsoft.AspNet.Mvc	6.0.0-rc1-final
Microsoft.AspNet.Owin	1.0.0-beta1
Microsoft.AspNet.Owin	1.0.0-beta2
Microsoft.AspNet.Owin	1.0.0-beta3
Microsoft.AspNet.Owin	1.0.0-beta4
Microsoft.AspNet.Owin	1.0.0-beta5
Microsoft.AspNet.Owin	1.0.0-beta6
Microsoft.AspNet.Owin	1.0.0-beta7
Microsoft.AspNet.Owin	1.0.0-beta8
Microsoft.AspNet.Owin	1.0.0-rc1-final
Microsoft.AspNet.Razor	4.0.0-beta1
Microsoft.AspNet.Razor	4.0.0-beta2
Microsoft.AspNet.Razor	4.0.0-beta3
Microsoft.AspNet.Razor	4.0.0-beta4
Microsoft.AspNet.Razor	4.0.0-beta5
Microsoft.AspNet.Razor	4.0.0-beta6
Microsoft.AspNet.Razor	4.0.0-beta7
Microsoft.AspNet.Razor	4.0.0-beta8
Microsoft.AspNet.Razor	4.0.0-rc1-final
Microsoft.AspNet.SignalR.Redis	3.0.0-beta3
Microsoft.AspNet.SignalR.Redis	3.0.0-beta4
Microsoft.AspNet.SignalR.Redis	3.0.0-beta5
```

**Comment by Eilon** [comment]
cc @muratg @divega @danroth27 @DamianEdwards for FYI information about this.
