### ISSUE TITLE
the best way to routing dynamic action parameter

### ISSUE THREAD

**Issue by xiaoxin1983** [aspnet/Mvc#5298]
here I need to accept a dynamic type to action , some like this;

```
class DataController:Controller{
   [HttpPost]
    public object Invoke(string actionName, [FromBody] object data){ ... }

    //other action
}
```

at background define body's clr type map to which action, but i don't want deserialization in controller action ,like this:

```
public object invoke(string actionName, [FromBody] object data){
    var actionDefine = this.ActionDefineProvider.GetAction(actionName);
    // data is JObject Type
    var data = ConvertType(actionDefine.BodyType,data);
    //do something
}
```

so , first i want  deserialization type parameter with my define before invoke action. 
and the second i need to generate the api helper (use apiexplorer).

i try to change the ApplicationModelConverstions ApplyConventions method , use my ActionDefineProvider to replace reflection, but it's difficult.

so , i need some suggestions , thank you !

xiaoxin

**Comment by dougbu** [comment]
Not exactly sure what you're aiming for here. But would your scenario work end-to-end if you use `JObject` as the `data` type?

**Comment by xiaoxin1983** [comment]
if i define the action parameter type with 'object' , actually it's type of 'jobject' . 

but i want deserialize the http content to my define type where a provider, like this:

```
public class ApiAction{
    public string ActionName{get;set;}
    public ClrClass BodyType{get;set;}
    // other action defines
}

public class ClrClass{
    public string Namespace{get;set;}
    public string Name{get;set;}
    public IList<ClrClassProperty> Properties{get;set;}
    //other class defines
}

public class ClrClassProperty{ ...}

public class ApiActionProvider : IApiActionProvider{
     public ApiAction GetAction(string actionName){...}
}

public static class DynamicTypeBuilder{
     public Type Build(ClrClass class){...}
}
```

the easy way :

```
public class DataActionController: Controller{
    [HttpPost]
    public object Invoke(string actionName, [HttpBody] JObject body){
        var action = this.ActionProivder.GetAction(actionName);
        var bodyType = DynamicTypeBuilder.Build(action.BodyType)
        var bodyValue = Newtonsoft.Json.JsonConvert.DeserializeObject(body.ToString(),bodyType);
        //do something
        return result;
    }
}
```

but i don't think it's the best way to do this , if i can change ControllerModel/ActionModel, is it better ? if do this ,i can use ApiExplorer to generate help page.

thank you!

xiaoxin

**Comment by danroth27** [comment]
@rynowak

**Comment by danroth27** [comment]
@xiaoxin1983 Can you tell us a bit more about your scenario? Why do you need this level of dynamic behavior? Maybe there are other options for accomplishing the scenario.

**Comment by xiaoxin1983** [comment]
@danroth27 

hi , at the previous version (not aspnetcore), the project used entityframework6 and odata ,it's like a lightweight master data services , users can design metadata, design business interface by self, and don't care abuat database, webapi and any underlying technology. 

now , i want to upgrade to aspnetcore without odata:

1. clrtypes model ->  dynamic compile (emit) -> clr types
2. database model -> load or config to database schema
3. map model  -> use clrtype and db model to build entityframework metadata (IModel)
4. action model -> define a action to query data from dbcontext ,use dynamic linq ( lambda)
5. routing & serialization -> this step is my problem.

at the provious version ,i custom odata serialization and built edm model by my self
at now the project it's working, at step5 i want find a better way to do this. 

i tried to use model conversation ,use model binding ,but it's not good enough, i think the best way is modify application model.

so this is my scenario and my thinking ,thinks

xiaoxin

**Comment by danroth27** [comment]
If you just want to move the deserialization logic to before the action invocation then you can do that with an [action filter](http://docs.asp.net/en/latest/mvc/controllers/filters.html#action-filters).
