### ISSUE TITLE
Action return string wouldn't call WriteResponseBodyAsync function in my OutputFormatter

### ISSUE THREAD

**Issue by zfkingth** [aspnet/Mvc#5302]
Action return string wouldn't call WriteResponseBodyAsync function in my OutputFormatter，but when the return type is bool or double，the WriteResponseBodyAsync would be called.

my code:
 ```
   public class ProtobufOutputFormatter :  OutputFormatter
 {
```
        private static Lazy<RuntimeTypeModel> model = new Lazy<RuntimeTypeModel>(CreateTypeModel);

        public string ContentType { get; private set; }

        public static RuntimeTypeModel Model
        {
            get { return model.Value; }
        }

        public ProtobufOutputFormatter()
        {
            ContentType = "application/x-protobuf";
            SupportedMediaTypes.Add(MediaTypeHeaderValue.Parse("application/x-protobuf"));

            //SupportedEncodings.Add(Encoding.GetEncoding("utf-8"));
        }

        private static RuntimeTypeModel CreateTypeModel()
        {
            var typeModel = TypeModel.Create();
            typeModel.UseImplicitZeroDefaults = false;
         
            return typeModel;
        }

        public override Task WriteResponseBodyAsync(OutputFormatterWriteContext context)
        {
            var response = context.HttpContext.Response;
    
            Model.Serialize(response.Body, context.Object);
            return Task.FromResult(response);
        }
    }

config mvc:

            services.AddMvc(options =>
            {
                options.RespectBrowserAcceptHeader = true;
              //  options.InputFormatters.Add(new ProtobufInputFormatter());
                options.OutputFormatters.Add(new ProtobufOutputFormatter());
                options.FormatterMappings.SetMediaTypeMappingForFormat("protobuf", MediaTypeHeaderValue.Parse("application/x-protobuf"));
            });

        }

my action :
```
        [HttpGet]
        public bool GetTest1()
        {
                      return true ;
        }
```
WriteResponseBodyAsync method will be called when return HttpResponseMessage，and the content type is **x-protobuf**。

the issure:
another action

       [HttpGet]
        public string GetTest2()
        {
                      return "test";
        }
WriteResponseBodyAsync method will **not** be called when return HttpResponseMessage，and the content type is actually **plain/text**, even response header contain:  Content-Type: application/x-protobuf; charset=utf-8

Could anybody tell me why?

**Comment by dougbu** [comment]
Insert your `ProtobufOutputFormatter` earlier in the `OutputFormatters` list. The `StringOutputFormatter` is "winning".

**Comment by zfkingth** [comment]
@dougbu how to do this? How to change the default sequence?

**Comment by zfkingth** [comment]
@dougbu  Thank you very much! I have solved by your direction as follow:
  services.AddMvc(options =>
            {
                options.RespectBrowserAcceptHeader = true;
                options.InputFormatters.Add(new ProtobufInputFormatter());
                options.OutputFormatters.Add(new ProtobufOutputFormatter());
                options.FormatterMappings.SetMediaTypeMappingForFormat("protobuf", MediaTypeHeaderValue.Parse("application/x-protobuf"));

                options.OutputFormatters.RemoveType<StringOutputFormatter>();
                options.OutputFormatters.Add(new StringOutputFormatter());
            });

**Comment by dougbu** [comment]
@zfkingth FYI you could just insert the new formatter at the beginning e.g. `options.OutputFormatters.Insert(0, new ProtobufOutputFormatter())`

**Comment by zfkingth** [comment]
A better solution!

**Comment by zfkingth** [comment]
When i used the insert code as you provided：
it will throw a Exception in this function 

        public override Task WriteResponseBodyAsync(OutputFormatterWriteContext context)
        {
            var response = context.HttpContext.Response;
    
            Model.Serialize(response.Body, context.Object);
            return Task.FromResult(response);
        }

even I Changed the aboved code as follow:

        public override Task WriteResponseBodyAsync(OutputFormatterWriteContext context)
        {
            var response = context.HttpContext.Response;

            if (context.Object != null)
                Model.Serialize(response.Body, context.Object);
            return Task.FromResult(response);
        }

the response I got from Fiddler is:

HTTP/1.1 200 OK
Content-Type: application/x-protobuf
Server: Kestrel
X-SourceFiles: =?UTF-8?B?RDpcY29kZVxEYW1PRGF0YVY0LVNlcnZlclxEYW1TZXJ2aWNlM1xBcHBzXEdldE1vZGVsXDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMA==?=
X-Powered-By: ASP.NET
Date: Tue, 20 Sep 2016 23:33:29 GMT
Content-Length: 0

There is a content with zero length，and the client parse fail。

But I use:
 options.OutputFormatters.RemoveType<StringOutputFormatter>();
                options.OutputFormatters.Add(new StringOutputFormatter());

the response is:
HTTP/1.1 204 No Content
Server: Kestrel
X-SourceFiles: =?UTF-8?B?RDpcY29kZVxEYW1PRGF0YVY0LVNlcnZlclxEYW1TZXJ2aWNlM1xBcHBzXEdldE1vZGVsXDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMA==?=
X-Powered-By: ASP.NET
Date: Tue, 20 Sep 2016 23:27:42 GMT

There is no content. The client parse succes!
How could I set the 204 No Content in WriteResponseBodyAsync method!

**Comment by zfkingth** [comment]
@dougbu 
My solution is :

        public override Task WriteResponseBodyAsync(OutputFormatterWriteContext context)
        {
            var response = context.HttpContext.Response;

            if (context.Object != null)
            {
                Model.Serialize(response.Body, context.Object);
            }else
            {
                response.StatusCode = 204;
                response.Headers.Remove("Content-Type");
            }
            return Task.FromResult(response);
        }

config start using your code:
      services.AddMvc(options =>
            {
                options.RespectBrowserAcceptHeader = true;
                options.InputFormatters.Insert(0, new ProtobufInputFormatter());
                options.OutputFormatters.Insert(0, new ProtobufOutputFormatter());
                options.FormatterMappings.SetMediaTypeMappingForFormat("protobuf", MediaTypeHeaderValue.Parse("application/x-protobuf"));

               
            });

Have any better   solution?
