### ISSUE TITLE
NotFound docs unclear on value object

### ISSUE THREAD

**Issue by breyed** [aspnet/Mvc#5303]
The XML comments for `Microsoft.AspNetCore.Mvc.NotFound(object)` that drive the IntelliSense text are missing documentation for the parameter. A fallback is to look at the documentation for the `NotFoundObjectResult` constructor, but this doesn't much either. It says the parameter is "The value to format in the entity body." Entity? What entity? I thought we were talking about an HTTP response here. And what is meant by "format"? Is this a format string, like used by `ToString`? Probably not, but it's not clear by the confusing docs.

**Comment by Eilon** [comment]
Closing because there has been minimal feedback on this.

**Comment by breyed** [comment]
Were you expecting thumbs up on any given documentation specific? That's not very likely. More realistic is general feedback about awesome docs vs. sparse/confusing docs, or somewhere in between.

If making an a highly productive library that's easy for devs to get right the first time is a priority, I'd urge you to put effort into making sure the IntelliSense docs (if possible, and the F1 docs has a fallback) tell the dev everything he needs to know, or link to articles when the concepts exceed what is reasonable to put in the docs of a single method.

In any case, when a dev tries to get info on a given method, he should always be led directly to the detail and concepts needed. If the dev has to turn to Google, StackOverflow, or GitHub source, the docs haven't done their job.

ASP.NET Core MVC is built on a lot of solid design principles. Please consider ensuring that its docs are world-class down to the API details, so it can be a highly productive and robust platform.

**Comment by Eilon** [comment]
We have received no other feedback about this doc (or lack of doc), so we felt that putting more effort into improving this doc would provide very little value. It's just a matter of trade-offs.
