### ISSUE TITLE
Strange Response from IActionResult and JsonResult when returning list of Data from EF

### ISSUE THREAD

**Issue by ruchanb** [aspnet/Mvc#5305]
Db Context
 ```
public class Country
    {
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public virtual ICollection<State> States { get; set; }
    }

    public class State
    {
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public string CountryCode { get; set; }
        public Country Country { get; set; }
    }

    public class MyContext : DbContext
    {
        public MyContext(string connectionString) : base(connectionString)
        {

        }
        public DbSet<Country> Countries { get; set; }
        public DbSet<State> States { get; set; }

       

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            var b = modelBuilder.Entity<Country>();
                b.ToTable("Country");
                b.HasKey(pr => pr.CountryCode);
                b.HasMany(m => m.States).WithOptional(i => i.Country).HasForeignKey(m => m.CountryCode);


            var a = modelBuilder.Entity<State>();
                a.ToTable("State");
                a.HasKey(pr => pr.StateCode);
                a.HasOptional(m => m.Country).WithMany(m => m.States).HasForeignKey(m => m.CountryCode);
           
        }
    }
```
**Case 1** 
Controller
```
public class HomeController : Controller
    {        
        
        // GET: /<controller>/
        public JsonResult Index()
        {                       
            var db = new MyContext("CONNECTION_STRING");
            var x = db.Countries.ToList();
            return new JsonResult(x);
        }
}
```
Here is the image, it has the actual data I need to send.
![image](https://cloud.githubusercontent.com/assets/11032047/18710229/cdef3c84-8023-11e6-91ac-fd408b98aa0b.png)

Now the received data. 
```
[
  {
    "states": [],
    "countryCode": "IND",
    "countryName": "India"
  },
  {
    "states": [
      {
        "stateCode": "BAG",
        "stateName": "Bagmati",
        "countryCode": "NPL"
      }
    ]
  }
]
```
The first item had no states thats good, but there are no properties of Country in second item. There should have been 3 Countries, and multiple states.
Also this received data is very inconsistent according to the list of records.
I tried with the `IActionResult` with the same result. 

**Case 2**
```
 public IActionResult A()
        {
            var list = new List<Country>()
           {
               new Country {CountryName="Nepal",CountryCode="NPL", States= new List<State>
               {
                    new State {StateCode="A", StateName="Test A" },
                    new State {StateCode="B", StateName="Test B" }
               } },
               new Country {CountryName="USA",CountryCode="USA", States= new List<State>
               {
                   new State {StateCode="C", StateName="Test C" }
               } }
           };
            return new JsonResult(list);
        }
```
Return Data
```
[
  {
    "countryCode": "NPL",
    "countryName": "Nepal",
    "states": [
      {
        "stateCode": "A",
        "stateName": "Test A",
        "countryCode": null,
        "country": null
      },
      {
        "stateCode": "B",
        "stateName": "Test B",
        "countryCode": null,
        "country": null
      }
    ]
  },
  {
    "countryCode": "USA",
    "countryName": "USA",
    "states": [
      {
        "stateCode": "C",
        "stateName": "Test C",
        "countryCode": null,
        "country": null
      }
    ]
  }
]
```
This one works as intended. I hope the problem is not the private `_entityWrapper` attribute in EF method.

This also happens in 1.0.0 version of Mvc.

I need a work around for this as soon as possible. Thanks.

OS: Windows 10
framework : net451
Dependencies:
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "EntityFramework": "6.1.3",
    "EntityFramework.Extended": "6.1.0.95",
    "System.Data.Common": "4.1.0",

**Comment by ruchanb** [comment]
I tested it with Entityframework Core and it works fine there. Is the version 6.1.3 the problem? I don't want to be using the Core EF yet.

**Comment by danroth27** [comment]
@rowanmiller

**Comment by rowanmiller** [comment]
Can you try setting `db.Configuration.ProxyCreationEnabled = false` before you run the query. I think the lazy loading proxies we are generating may be causing issues with serialization.

**Comment by ruchanb** [comment]
@rowanmiller  yes this solved the issue. Thanks. Anyway, its conflicting that it works on EF core and doesn't on EF 6.

**Comment by danroth27** [comment]
Closing this here since this isn't an MVC issue. If necessary, please open an issue in the https://github.com/aspnet/entityframework repo to further discuss the EF Core behavior.

**Comment by rowanmiller** [comment]
@ruchanb we don't use dynamic proxies in EF Core, which is why you don't hit the issue. We generally recommend disabling proxy generation for serialization scenarios in EF6.x.
