### ISSUE TITLE
WEB API template greys out option for Authentication with Individual User Accounts

### ISSUE THREAD

**Issue by Ponant** [aspnet/Mvc#5307]
1) Create an ASP.NET Core (.Net Core) project in VS 2015 Community update 3
2) Choose WEB API
3) You cannot set the template to set Auhtentication via Individual Account (the radio button is greyed out).

**Comment by danroth27** [comment]
Yup, this is a known limitation. There is an effort to build in-the-box solution that aligns closely with [Azure AD B2C](https://azure.microsoft.com/en-us/services/active-directory-b2c/), but it's [still a ways off](https://github.com/aspnet/home/wiki/roadmap). In the interim you can use existing community offerings like [IdentityServer4](https://identityserver.io).

Closing this as there really isn't anything to do here in MVC.

@vibronet

**Comment by Ponant** [comment]
Thanks @danroth27 for the clarification and sorry for putting this on ASP.NET MVC; it was not clear to me which repo would be best. I am confused about what this [tuto on mobile services in .Net Core](https://docs.asp.net/en/latest/mobile/native-mobile-backend.html) is for then; can't we set individual Auth there? I am looking at building a web + mobile on top of an API in .Net core with individual sing-in.
greetings

**Comment by danroth27** [comment]
@Ponant The mobile app tutorial is a simple introduction to using Xamarin with an ASP.NET Core mobile backend. We do plan to extend the tutorial to cover authentication, but we want to keep the intro tutorial simple. You can see an example of how to use IdentityServer4 with ASP.NET Core for mobile apps at http://docs.identityserver.io/en/dev/quickstarts/5_hybrid_and_api_access.html.

**Comment by Ponant** [comment]
@danroth27 , thanks a lot Dan, this sounds helpful even though it would have been great to have a full MS offering but I understand we need to be patient. This being said, IdentityServer sounds good at first sight.

**Comment by Ponant** [comment]
Hi @danroth27 , 
I am wondering the following:
While the Individual Account is greyed out when creating an API, I can still create an Web App in VS and choose individual accounts there. Next, I could implement the API controllers. So the question is what is the difference between these 2 approaches and why they evidently differ in the templates (.Net Core does not distinguishes between an API and MVC-->it's all MVC)?

My end goal is to have a website with registration and that can return also JSON to be consumed by a xamarin mobile app.

**Comment by danroth27** [comment]
For web apps you typically use a login form or OpenID Connect to establish a session cookie that is used to establish the user principal. There is often also anti-request forgery mechanisms in place, since the client is a browser. For web APIs you typically use OAuth2.0 and access tokens to authorize requests. The two scenarios have different security configurations.
