### ISSUE TITLE
Remove trailing whitespace from Json

### ISSUE THREAD

**Issue by NormanMann** [aspnet/Mvc#5309]
Using Entity Framework Core I created a POCO with a MaxLength(400) data annotation.
When the object is returned by a WebApi action method the field always gets serialized with a length of 400.
Although the relevant string is much shorter trailing whitespaces are appended.
Is there a way to provide EF with the necessary information for creating the field in the database and not have the json serializer append whitespaces ?

**Comment by rynowak** [comment]
Please open this issue on the https://github.com/aspnet/EntityFramework repository and they may be able to help you. I'd suggest also including your model code (or a simplified version of it).

**Comment by danroth27** [comment]
@rowanmiller @divega

**Comment by NormanMann** [comment]
Never mind. As it turns out that was neither the fault of serialization nor EF. Data was corrupted in database to start out with. 
Sorry guys!
