### ISSUE TITLE
Request payload takes precedence over model in asp-for attributes

### ISSUE THREAD

**Issue by johnnyoshika** [aspnet/Mvc#5315]
`asp-for` attributes uses the request payload to populate its value even when a model is passed to the View from the Controller.  The model values seem to be ignored in this instance.  I provided more information regarding this (including examples) on Stackoverflow: http://stackoverflow.com/q/39666056/188740

I can't tell if this is by design or a bug.

**Comment by brockallen** [comment]
This is how it has been for years (since MVC 1). I asked Phil Haack about it at one point and he says that he was unaware of that behavior and was probably an oversight.

**Comment by dougbu** [comment]
This behaviour is by design and required for round-tripping values even if some fail validation (perhaps causing re-display of the form).

See https://github.com/aspnet/Mvc/issues/4486#issuecomment-210603605 for other  comments on the same subject. Suspect we've had similar exchanges elsewhere.

**Comment by MisterJames** [comment]
I think the side issue here - regardless if folks should be using PRG or not - is that it's non-obvious as to what's happening. I've tripped on this a few times (and to be honest, when I saw the related question on SO it didn't trigger for me). I don't bump up against it too often (this is maybe my third time) as I'm usually doing a redirect, but I seem to be surprised by this each time. 👴

**Comment by brockallen** [comment]
> This behaviour is by design and required for round-tripping values even if some fail validation (perhaps causing re-display of the form).

This makes sense as the original motivator for the behavior, but when the value has no validation errors the behavior is unexpected (and to clarify is really what I asked Haack about and what was a surprise to him).

**Comment by johnnyoshika** [comment]
Closing as the behavior (although obviousness) is by design and does make sense.
