### ISSUE TITLE
How To Use RDLC Reporting in Asp.Net Core 1.0

### ISSUE THREAD

**Issue by ermithun** [aspnet/Mvc#5332]
How can i create RDLC report in asp.net core 1.0 ??

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Home/issues/1528.

**Comment by amh1979** [comment]
[`AspNetCore.Reporting`](http://www.nuget.org/packages/AspNetCore.Reporting)

**Comment by cablackford** [comment]
@amh1979 
How do you implement after installing?
