### ISSUE TITLE
Checkboxes Required Now?

### ISSUE THREAD

**Issue by LorenDorez** [aspnet/Mvc#5333]
I just started a new AspNetCore Project using MVC 6.

Im using the default Login View Model and the RememberMe field is set as a bool which is fine. HOwever the HTML generates a Validation attributes of Required forcing a user to have to check the checkbox. This defaults the purpose of a checkbox if it is forced to be checked.

See code below
```
 public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
```

```
<div class="form-group">
                <input asp-for="RememberMe" />
                <label asp-for="RememberMe" class="control-label"></label>
                <span asp-validation-for="RememberMe" class="text-danger"></span>
            </div>
            <button id="btnSubmit" type="submit" class="btn btn-lg btn-block btn-primary">sign in</button>
        </form>
```

Rendered HTML
```
<div class="form-group">
                <input name="RememberMe" class="k-invalid valid" id="RememberMe" aria-invalid="true" aria-describedby="RememberMe-error" type="checkbox" value="true" data-val-required="The Remember me? field is required." data-val="true">
                <label class="control-label" for="RememberMe">Remember me?</label>
                <span class="k-widget k-tooltip k-tooltip-validation k-invalid-msg field-validation-error" id="RememberMe_validationMessage" role="alert" data-valmsg-for="RememberMe" data-for="RememberMe"><span class="k-icon k-i-warning"> </span> The Remember me? field is required.</span>
            </div>
```

**Comment by dougbu** [comment]
Did you submit this issue based on a problematic behaviour or the source? If a behaviour, please describe the details.

Should be no error for the `.cshtml` snippet you describe because MVC will generate an `<input name="RememberMe" type="hidden" value="false"/>` field at the end of the form.

**Comment by LorenDorez** [comment]
@dougbu 
Im still fairly new to this new setup with aspnetcore and mvc6

II narrowed this down to the Custom Validator plugin im using by Telerik. Im going to submit this to them as a bug as i t appears after much trial and error its with the KendoUI Validator
