### ISSUE TITLE
Inconsistent IFormFile collection binding between model properties and controller parameters

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#5338]
I found some inconsistencies on how IFormFile collection get's binded then used as model property vs being used as controller parameter vs primitive type collection binding. Is this intentional change from MVC5? See collections then 0 elements are selected/entered.

``` HTML
<form action="/" enctype="multipart/form-data" method="post">
    <input type="text" name="strings">
    <input type="text" name="strings">
    <input type="file" name="files" multiple>

    <input type="submit">
</form>
```
### MVC Core

``` C#
public class Model
{
    public IFormFile[] Files { get; set; }
    public String[] Strings { get; set; }
}

[HttpPost]
public IActionResult Index(Model model)
{
    // 0 files selected: model.Files => null
    // 1 file selected : model.Files => [1] { "0.txt" }
    // 2 files selected: model.Files => [2] { "0.txt", "1.txt" }
    return View();
}

[HttpPost]
public IActionResult Index(IFormFile[] Files)
{
    // 0 files selected: Files => [0] { }
    // 1 file selected : Files => [1] { "0.txt" }
    // 2 files selected: Files => [2] { "0.txt", "1.txt" }
    return View();
}

[HttpPost]
public IActionResult Index(Model model)
{
    // 0 strings entered: model.Strings => [2] { null, null }
    // 1 string entered : model.Strings => [2] { "0", null }
    // 2 strings entered: model.Strings => [2] { "0", "1" }
    return View();
}

[HttpPost]
public IActionResult Index(String[] Strings)
{
    // 0 strings entered: Strings => [2] { null, null }
    // 1 string entered : Strings => [2] { "0", null }
    // 2 strings entered: Strings => [2] { "0", "1" }
    return View();
}
```
### MVC 5

``` C#
public class Model
{
    public HttpPostedFileBase[] Files { get; set; }
    public String[] Strings { get; set; }
}

[HttpPost]
public IActionResult Index(Model model)
{
    // 0 files selected: model.Files => [1] { null }
    // 1 file selected : model.Files => [1] { "0.txt" }
    // 2 files selected: model.Files => [2] { "0.txt", "1.txt" }
    return View();
}

[HttpPost]
public IActionResult Index(HttpPostedFileBase[] Files)
{
    // 0 files selected: Files => [1] { null }
    // 1 file selected : Files => [1] { "0.txt" }
    // 2 files selected: Files => [2] { "0.txt", "1.txt" }
    return View();
}

[HttpPost]
public IActionResult Index(Model model)
{
    // 0 strings entered: model.Strings => [2] { null, null }
    // 1 string entered : model.Strings => [2] { "0", null }
    // 2 strings entered: model.Strings => [2] { "0", "1" }
    return View();
}

[HttpPost]
public IActionResult Index(String[] Strings)
{
    // 0 strings entered: Strings => [2] { null, null }
    // 1 string entered : Strings => [2] { "0", null }
    // 2 strings entered: Strings => [2] { "0", "1" }
    return View();
}
```

**Comment by khellang** [comment]
These look Really Bad™ (in both MVC 5 and Core):

```csharp
// 0 files selected: model.Files => [1] { null }
// 0 files selected: Files => [1] { null }

// 0 strings entered: model.Strings => [1] { null }
// 0 strings entered: Strings => [1] { null }
```

Arrays with a single `null`-element in it if no files or strings were passed? That sounds like a recipe for disaster.

**Comment by Muchiachio** [comment]
Having one null is understandable @khellang, because it's the same behavior as binding one property, it exists in the form but is not specified. So for strings we get  `[0] => { null }` or `[0] => { "" }`.
And yes, struct get's bound to default value e.g. `[0] => { 0 }`.

**Comment by dougbu** [comment]
In ASP.NET MVC Core, the `string[]` behaviour is less understandable than the `IFormFile[]` handling. Counting form fields that were left blank isn't particularly useful. But we probably maintained the `string[]` behaviour for backwards compatibility.

What problems does this slight inconsistency lead to? @Muchiachio were you suggesting we add extra `null` entries to `IFormFile[]` when fields are left blank? Or is the `string[]` handling something you'd like to see change?

**Comment by Muchiachio** [comment]
I would expect that `model.Files` and just `Files` parameter would bind the same.
Now `model.Files` binds to `null`, while `Files` parameter bind to empty collection.

I'm not too sure on including `null` tho, MVC 5 did that, but it always felt unnecessary on files, as multiple file input behaves differently than including a lot of text inputs.

**Comment by dougbu** [comment]
> I would expect that `model.Files` and just `Files` parameter would bind the same.

The difference is MVC _intends_ to have an invariant that action arguments are never `null`. Value types may have their default values but POCO types should always be instantiated before calling the action. MVC 5.x was inconsistent here and we're a bit better in ASP.NET Core MVC.

**Comment by Muchiachio** [comment]
Still feels strange that `string[]` would bind to non null object while `IFormFile[]` wouldn't.
This can be closed, if it's not going to be changed.

**Comment by Muchiachio** [comment]
Should this be closed @dougbu?

**Comment by dougbu** [comment]
:ok: @Muchiachio
