### ISSUE TITLE
Investigate cost of eagerly creating property accessors

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5342]
Building the application model at startup creates an 'accessor' delegate for every public controller property.

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/DefaultApplicationModelProvider.cs#L61

This may cause startup speed problems for real world apps. We should be lazy :grinning: 

This data is just a jumping off point to investigate further
![image](https://cloud.githubusercontent.com/assets/1430011/18999946/d325716e-86f4-11e6-96bf-9cc7897078e5.png)

**Comment by kichalla** [comment]
Fixed as part of https://github.com/aspnet/Common/commit/47e8deaf484d5ea9878a6382d3a26f5607675ee6
