### ISSUE TITLE
"Show raw exception details" won't work inside chrome dev tools' network tab

### ISSUE THREAD

**Issue by nvivo** [aspnet/Mvc#5348]
When an exception is thrown in a api call, we can see the error in chrome's dev tools network tab.

The problem is that chrome seems to not allow or limit which scripts run in the preview tab, and the "Show raw exception details" link won't work. When doing GET it's simply to open a new tab, but POSTs are not so simple.

![image](https://cloud.githubusercontent.com/assets/202449/19033688/1a053f54-8936-11e6-8fd1-17522be8ef42.png)

I know it's possible to define a new error handler or use tools like Postman, fiddler, etc. But it would be a lot more convenient if the default exception page to simply show the details directly. It' an exception page for developers, it shouldn't need require an action to show exception details. 

This is a request to either show the raw exception in a PRE tag directly or show the full exception details (file names, line numbers, etc) in the current layout. Either way, it shouldn't require scripts to show this information.

**Comment by danroth27** [comment]
We've fixed a bug that will show more of the exception details in the HTML (aspnet/diagnostics#335). We are also looking at providing API friendly error responses (#5130). No plans to change the developer exception handling page to render without scripting support.
