### ISSUE TITLE
When replacing Controller.Dispose with an explicit implementation the base Dispose is an action

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5352]
```
public class HomeController : Controller, IDisposable
{
        void IDisposable.Dispose()
        {
            Debug.WriteLine("Got disposed");
        }
}
```

If you define this controller, then `/Home/Dispose` will be routed to the `Controller.Dispose()` method and will call it as an action.

Note that this requires you to reimplement `IDisposable` on the subclass. Just overriding the `protected void Dispose()` would not have any deleterious impact.

This is a similar case that also reproduces the bug:

```
public class HomeController : Controller
{
        public new void Dispose()
        {
            Debug.WriteLine("Got disposed");
        }
}
```

**Comment by khellang** [comment]
Shouldn't [this](https://github.com/aspnet/Mvc/blob/b56cab6414401e01c96d9ea8c4eabdd653720d4c/test/Microsoft.AspNetCore.Mvc.Core.Test/Internal/DefaultApplicationModelProviderTest.cs#L279) cover that last case? `DerivedController` (which is being tested) has this; https://github.com/aspnet/Mvc/blob/b56cab6414401e01c96d9ea8c4eabdd653720d4c/test/Microsoft.AspNetCore.Mvc.Core.Test/Internal/DefaultApplicationModelProviderTest.cs#L995-L997

**Comment by rynowak** [comment]
That covers the negative case. `DerivedController.Dispose()` **should** be considered an action since `DerivedController` doesn't declare `IDisposable`
