### ISSUE TITLE
Running vanilla Razor Views from a View Page

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#5358]
The Razor View Engine makes some assumptions about running with an invoker that has Controller defined. When a Razor View is run in the context of a View Page (for instance, Razor Page using a Layout or executing partials), these values would not be available. Some of these scenarios include:
- Conventions for view lookup and cache keys in the View Engine
- ViewLocationExpanders

**Comment by Eilon** [comment]
@rynowak please follow up to dig down and make sense of this. Left. Right.

**Comment by rynowak** [comment]
Closing this in favor of #6019. The details of what we're going to do are at https://github.com/aspnet/Mvc/issues/6073#issue-219381287
