### ISSUE TITLE
Consider caching hashcode for ModelMetadata

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5360]
This is a **backtrace** from a sampling profile of  https://github.com/aspnet/Performance/tree/dev/testapp/LargeJsonApi using the POST test.
![image](https://cloud.githubusercontent.com/assets/1430011/19080515/2fae3168-8a0c-11e6-82f3-49da3f8b6a17.png)

The total time spent processing requests was approx 28sec. `ModelMetadata.GetHashCode()` consumed 918ms of that time, or about 3%. Considering that `ModelMetadata` is cached indefinitely there would seem to be little downside to caching the hashcode value.

**Comment by ryanbrandenburg** [comment]
Scenario|Requests|GetHashCode|% time in GetHashCode
---------|--------|---------------|---
Without Cache|9417|550|5.84%
With Cache|6195|47|0.75%

Above is the results I got in testing this, seems worthwhile, creating a PR now.

**Comment by ryanbrandenburg** [comment]
Closed in #5374.
