### ISSUE TITLE
IValidatableObject.Validate should always be called

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#5366]
Due to this line:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidationVisitor.cs#L243

The `IValidatableObject.Validate` method of a complex type will not be called when any of its child nodes have failed validation.

I feel that this should not be so: consider, for instance, a custom bit of validation logic that needs to assess the values of three properties in relation to each other. Having one other property on the model that uses a data annotation attribute will prevent the error from being displayed to the user. They will think they have corrected their submission according to the details displayed in their browser only to be greeted by a new, different error that should have been displayed the first time.

**Comment by Eilon** [comment]
We did some research and it seems that the behavior in MVC matches what Data Annotations does in its various validation APIs. You can see the logic here: https://referencesource.microsoft.com/#System.ComponentModel.DataAnnotations/DataAnnotations/Validator.cs,360

The object-level validation runs only if the properties are valid.

**Comment by tuespetre** [comment]
I am aware of that behavior... and I am not a fan of it, considering scenarios like the one I outlined. I thought maybe I had already logged an issue with corefx asking for another overload of `TryValidateObject` that doesn't skip object-level validations, but I can't find it, so I guess not.

Is this something where the team would consider adding an option to influence this behavior? Without digging into the source again, my memory is telling me that it wouldn't be a walk in the park to achieve the same result by extending or implementing something (I don't recall if `ValidationVisitor` can even be subbed for something else.)

**Comment by Eilon** [comment]
@rynowak any thoughts on that?

I recall that in MVC1 - 5 there was a way to plug in validation *providers* that could introduce entire new validation paradigms to increase synergy *ahem*. Back in the day there was first an [`IDataErrorInfo`](https://msdn.microsoft.com/en-us/library/system.componentmodel.idataerrorinfo(v=vs.110).aspx) provider (how many of you kids are old enough to remember that interface), and then later the Data Annotations-based provider. And one could easily plug in their own completely custom mechanism.

I'm not sure if ASP.NET Core MVC has this type of extensibility.

**Comment by mvelosop** [comment]
A rough workaround:

```cs
public async Task<IActionResult> ActionName(ViewModel vm)
    {
        ValidateViewModel(vm);

        if (!ModelState.IsValid)
        {
            ...
    }
```

```cs
private void ValidateViewModel(IValidatableObject vm)
    {
        var errors = vm.Validate(null).ToList();

        errors.Where(vr => vr.MemberNames == null)
            .ToList()
            .ForEach(vr => ModelState.AddModelError("", vr.ErrorMessage));

        errors.Where(vr => vr.MemberNames != null)
            .SelectMany(vr => vr.MemberNames.Select(mn => new { MemeberName = mn, vr.ErrorMessage }))
            .ToList()
            .ForEach(vr => ModelState.AddModelError(vr.MemeberName, vr.ErrorMessage));
    }
```
