### ISSUE TITLE
Add log messages to input formatters at Debug level

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Mvc#5367]
I'm having a very odd issue trying to upload a file using ungular 2.

  I have an angular 2 app. and I'm working to a file upload to load files in the app, but trying with 2 different libraries during the upload of the file I have a 415 error (unsupported media type).
  The strange thing is I have another project with angular 1 and there file upload it's working fine, so I checked using chrome tools to understand differences, and try to make equal.
  At this point I have this situation:
![angular1](https://cloud.githubusercontent.com/assets/127777/19130101/267063de-8b4a-11e6-997e-bc732b749258.png)
this is the result of the upload using angular 1.5 and it's workign fine.

![angular2](https://cloud.githubusercontent.com/assets/127777/19130131/408df240-8b4a-11e6-938c-3442a33ab1d1.png)
this one is from the upload with angular2 and gives me error.
  Even configuring the console at trace level I don't find any valuable information, and I don't see any real di difference that justify this kind of error.
  Where have I to look to solve this problem?

**Comment by rynowak** [comment]
The URL used to submit the request is different between the two, as are the names of the form files - `name="titolo"` vs `name="dataImport"`.

However, the best explanation of the 415 response code is that the wrong action is being hit. Can you paste in the signature of your action method?

**Comment by lucamorelli** [comment]
this is the action and the declaration of the angular 2 procedure
 ```
[Route("api/[controller]")]
    public class AllegatiController : Controller
    {
        private IHostingEnvironment _environment;

        private AccountService _account { get; set; }
        public AllegatiController(AccountService account, IHostingEnvironment environment)
        {
            _account = account;
            _environment = environment;
        }

        [AllowAnonymous]
        [Route("test")]
        [HttpPost]
        public async Task<IActionResult> AddAllegato([FromBody] AllegatiPostVm model)
        {
            var uploads = Path.Combine(_environment.WebRootPath, "uploads");
....
```

this is the declaration of the angular 1 procedure that is working

```
        [Route("[action]")]
        [HttpPost]
        public async Task<IActionResult> SimpleExcel(UploadData model)
        {
            var dtImport = Convert.ToDateTime(this.Request.Form["dataImport"], new CultureInfo(1040));
            dtImport = new DateTime(dtImport.Year, dtImport.Month, dtImport.Day);

```

**Comment by lucamorelli** [comment]
Ok, I'm missing something. based on your suggestion I changed the only different thing, the [FromBody] and this solved the problem.
Sorry, but I don't understand why

**Comment by rynowak** [comment]
`[FromBody]` doesn't play with forms

**Comment by lucamorelli** [comment]
Don't worry, after almost 1 working day spent trying to solve this problem is clear.
Could be nice in the future to have better indication at least at logging level, because the message is confusing, and with all the possible source of problems using new client frameworks too, look at this detail is the last thing.
thanks anyway.

**Comment by rynowak** [comment]
which message do you think is confusing? Should we log better data when we report a 415? What information would you like to see?

**Comment by lucamorelli** [comment]
Well, the fact that the presence of the [FromBody] attribute is even blocking for the action call is confusing. Could be that the general idea that mvc and web api has been merged in asp.net core didn't help me in understand the problem.
Now I understand that the unsupported media type answer is related to his presence, but in this situation gave me the impression that there is some general problem with the client component.
I think that change the behavior of the [FromBody], doing nothing when is processing form data is excessive, but give a specific message in the log console when are you using with with the two typical form content type could be useful.

Generally speaking I have to deal quite often with this 415 error message: asp.net core accepts a restricted set of content types while sending json data packets, and I found that several client packages send data in text/html by default, or when you change some options and forget to set explicitly the content type again. 
Since new frameworks has been just release the community libraries are still to an eraly stage: just to do an example, while trying to solve this problem I found at least a couple of upload libraries where setting the content type header explicitly they forget to add the boundary to that line, making unusable.

**Comment by rynowak** [comment]
I'm reopening this issue so we don't lose track of your feedback, thanks!

**Comment by lucamorelli** [comment]
ok, nice to be of help

**Comment by Eilon** [comment]
Let's add log messages to our input formatters that state that they were attempting to handle the request, but couldn't.

Also, the filter that ends up returning the 415 status message should have some new behavior:
* Log this message: `"No formatter could be found to support the content type "{0}" for use with the [FromBody] attribute."`
* If the content type is form data, it should log an additional message stating: `"To use model binding, remove the [FromBody] attribute from the action method's parameter."`

These messages should all be at the `Debug` level.

**Comment by jbagga** [comment]
Hi
