### ISSUE TITLE
Undo change from https://github.com/aspnet/Mvc/pull/5375 once a fix is available

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#5376]
Work item to track: https://github.com/dotnet/core-setup/issues/423

**Comment by dougbu** [comment]
@pranavkm should this issue be closed now?

**Comment by pranavkm** [comment]
Reverted in https://github.com/aspnet/Mvc/commit/c5a09327eb2571323aadbad16c2d925b41d06be7
