### ISSUE TITLE
Trying to bind a date to DateTime object in a model

### ISSUE THREAD

**Issue by sero323** [aspnet/Mvc#5377]
I am trying to POST a date like this "10/05/2016" (using ajax) to a DateTime object in a model. All the objects are binding except the DateTime objects. As you can see in the screen shot, the string value is coming through but the DateTime object is showing 01/01/0001. I'm running VS Code with asp.net core on my mac with the C# extensions. The crazy thing is that running the same code on Visual Studios on windows binds the DateTime objects correctly. Any suggestions?

Here's the excerpt of the web api POST method.
```c#
[HttpPost]
public IActionResult Post([FromBody] SomeModel model)
{...}
```
I have tried the `yyyy-MM-dd` format and even changed the date to the iso format date using `.toISOString()` which produces something like `2016-10-06T20:04:56.035Z`. I have also added the culture settings to Startup.cs like so...
```c#
public void ConfigureServices(IServiceCollection services)
        {                
            services.Configure<RequestLocalizationOptions>(
                options =>
                    {
                        var supportedCultures = new List<CultureInfo>
                        {
                            new CultureInfo("en-US"),
                        };
 
                        options.DefaultRequestCulture = new RequestCulture(culture: "en-US", uiCulture: "en-US");
                        options.SupportedCultures = supportedCultures;
                        options.SupportedUICultures = supportedCultures;
                    });
            ....
        }
```

Debugger screenshot...
![image](https://cloud.githubusercontent.com/assets/22666128/19168773/98cdeae2-8bc6-11e6-8fed-ee4f60440d84.png)

**Comment by sero323** [comment]
Found the solution...for some reason when I declare my DateTime object in the model, it won't bind if I user DateTime?, I also tried Nullable<DateTime> and that didn't work either. but a plain DateTime object works. Interesting...

**Comment by rynowak** [comment]
If you're using `[FromBody]` with JSON, then any conversion or binding here is done with JSON.NET. if you run into other issues like this in the future, their docs are a great starting point.
