### ISSUE TITLE
Validation Tag Helper doesn't allow key in ModelState which is not included in the Model

### ISSUE THREAD

**Issue by mdmoura** [aspnet/Mvc#5381]
On an ASP.NET Core 1.0.1 project I have the following in a form:

```
<input asp-for="Email" type="text" />
<span asp-validation-for="Email" class="error"></span>    
```

This works fine since "Email" is a model property. But when I use:

```
<span asp-validation-for="Result" class="error"></span>    
```

This won't work since Result is not a property of the Model even if it is a Key of the Model State in certain validation scenarios ... 

Is there a way to solve this?

**Comment by dougbu** [comment]
Tag helpers are usually coupled to the `Model` in your view. But there's an escape hatch for any in-scope variable: E.g. `<span asp-validation-for="@Result" class="error"></span>` would reference a `Result` field or property.

But tag helpers cannot find entries in the `ModelStateDictionary` that cannot be expressed as a simple variable / property / element (&hellip;) path. Use `string`-based HTML helpers for that e.g. `@Html.ValidationMessage("Result")`.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
