### ISSUE TITLE
visual studio 2015 update3 crash when edited asp.net core 1.0.0  project project.json

### ISSUE THREAD

**Issue by anuo** [aspnet/Mvc#5385]
i edited a  project project.json file  cause  circular dependency, there is no any tips but visual studio 2015 update3  directly  go crash  ! ! !

**Comment by Eilon** [comment]
This issue was moved to aspnet/Tooling#818

**Comment by Eilon** [comment]
@anuo I moved this to the Tooling repo so you can track this issue there. Thanks!
