### ISSUE TITLE
how to remove courses store in ids in edit post controller

### ISSUE THREAD

**Issue by ahmedba** [aspnet/Mvc#5386]
**In edit http post i need to remove courses stored in ids variable

note i need remove courses selected not edit**

in jquery i store values of removed courses in ids variable

suppose i removed photoshop and flash it will store value of 3,4 in ids variable

below code when click remove it save values of courses removed in variable ids as array

 
```
$("#tb").on("click", ".r", function () {  
$(this).parent().parent().hide();  
$(this).parent().prev().prev().find("input").addClass("remove");  
var ids = [];  
var i = 0;  
$(".remove").each(function () {  
ids[i] = $(this).val();  
i++;  
});  
for (var k = 0; k < ids.length; k++) {  
alert(ids[k]);  
}  
});  
```
i show courses per employee from table EmployeeCourse in edit get as following

```
var index = 0;  
$.ajax({  
url: "/Employeedata/getcoursesbyempid",  
data:{x:$("#hid").val()},  
success: function (res) {  
$.each(res, function (i, e) {  
$("#tb").append("<tr><td><input type = 'hidden' name='empcourses[" + index + "].CourseId' value='" + e.Id + "'/></td><td>" + e.CourseName + "</td><td><input type='button' value='remove' class='r'/></td></tr>")  
index++;  
});  
}  
})  
public JsonResult getcoursesbyempid(int x)  
{  
db.Configuration.ProxyCreationEnabled = false;  
var data = db.EmployeeCourses.Where(a => a.EmployeeId == x).Join(db.Courses, a => a.CourseId, b => b.Id, (a, b) => new { Id = a.CourseId, CourseName = b.CourseName });  
return Json(data, JsonRequestBehavior.AllowGet);  
}  
```
 my model using as following

```
public class Cusomemp2  
{  
    public int Id { get; set; }  
    public string Name { get; set; }  
    public List<EmployeeCourse> empcourses { get; set; }  
}  
```
 
**when remove courses in edit HTTPPOST what i write here**

```
[HttpPost]  
public ActionResult Edit(Cusomemp2 custom)  
{  
//what i write to remove courses saved in ids from table EmployeeCourse  
return View();  
}  
```
![remove ids courses](https://cloud.githubusercontent.com/assets/20745093/19213329/f1131d86-8d69-11e6-808a-9933587f9148.jpg)

see image above for details

**Comment by Eilon** [comment]
Hi, this seems like a general usage question about ASP.NET Core MVC, so we recommend asking it in a forum that is better suited to that type of question, such as StackOverflow, using the [asp.net-core-mvc](https://stackoverflow.com/questions/tagged/asp.net-core-mvc) tag.
