### ISSUE TITLE
ModelState serialization is inconsistent with validation attributes 

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Mvc#5387]
When serializing `Controller.ModelState` to  JSON, the casing of the fields are inconsistent. I am not sure why but there are a few key things I figure that makes the difference.

## Repro Steps

> Also available [here](https://github.com/tugberkugurlu/AspNetCoreSamples/tree/51578d90040158d8ef5e91b68ce7be50e2c84968/repros/ValidationJsonSerialize).

`project.json` file:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

`Program.cs` file:

```
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;

namespace ConsoleApplication
{
    public class PaginatedRequestCommand
    {
        [Range(0, int.MaxValue)]
        public int Skip { get; set; }

        [Range(1, 50)]
        public int Take { get; set; }
    }
    
    public class ValuesController : Controller 
    {
        [HttpGet("values")]
        public IActionResult Get(int skip, int take)
        {
            var requestCommand = new PaginatedRequestCommand
            {
                Skip = skip, Take = take
            };

            return TryValidateModel(requestCommand) ?
                Ok(new [] { "value1", "value2" }) :
                BadRequest(ModelState) as IActionResult;
        }
    }

    public class Startup 
    {
        public void ConfigureServices(IServiceCollection services) 
        {
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app) 
        {
            app.UseMvc();
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
    }
}
```

After having these files under the same directory, call the below commands:

```
dotnet restore
dotnet run
```

after that, send a GET request to `/values?take=100`:

```
curl -D - http://localhost:5000/values?skip=-1
```

## Expected Results

```
Tugberks-MBP:~ tugberk$ curl -D - http://localhost:5000/values?skip=-1
HTTP/1.1 400 Bad Request
Date: Sat, 08 Oct 2016 15:43:51 GMT
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Server: Kestrel

{"skip":["The field Skip must be between 0 and 2147483647."],"take":["The field Take must be between 1 and 50."]}
```

## Actual Results

```
Tugberks-MBP:~ tugberk$ curl -D - http://localhost:5000/values?skip=-1
HTTP/1.1 400 Bad Request
Date: Sat, 08 Oct 2016 15:43:51 GMT
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Server: Kestrel

{"skip":["The field Skip must be between 0 and 2147483647."],"Take":["The field Take must be between 1 and 50."]}
```

The casing of `Skip` and `Take` fields are inconsistent. As far as I can see, it serializes with the correct casing when the value is supplied for the field and the value is invalid. However, it serializes the field name wrongly when the field is not supplied as input at all and its default is invalid. At the first glance, it seems like a bug but not sure which parts of MVC is getting this wrong.

Is there an obvious workaround (e.g. custom serialization setting for `ModelStateDictionary`, etc.) that I can apply to achieve the expected result?

## dotnet CLI Version

```
Tugberks-MacBook-Pro:ValidationJsonSerialize tugberk$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

**Comment by dougbu** [comment]
The `ModelStateDictionary` is case-insensitive. This means whatever adds a key chooses its case. In your `/values?skip=-1` scenario, model binding adds a value for `skip` to the dictionary and validation adds an error to the existing entry in the dictionary. The same doesn't happen with the `Take` property.

To make the keys consistent, could capitalize the `skip` and `take` action parameters. But it'll look less odd to use `PaginatedRequestCommand command` instead.

**Comment by tugberkugurlu** [comment]
@dougbu Ah, OK. I see now. Directly binding the query string to `PaginatedRequestCommand` made it consistent: https://github.com/tugberkugurlu/AspNetCoreSamples/blob/7286f517ee75986c567fd68d1654dacb30d3c855/repros/ValidationJsonSerialize/Program.cs#L21

I keep confusing ASP.NET Web API action selection with ASP.NET MVC Core. That's why I was directly binding to simple types but as they don't take effect on action selection, binding it to complex type makes it more clean overall 👍
