### ISSUE TITLE
Have a way to specify bind prefix for models \ action arguments

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#539]
We're missing something equivalent to http://msdn.microsoft.com/en-us/library/system.web.http.modelbinding.modelbinderattribute.name(v=vs.118).aspx

**Comment by yishaigalatzer** [comment]
This is already supported - 

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ModelBinding/BinderMetadata/ModelBinderAttribute.cs#L78

CC / @harshgMSFT @pranavkm please re-open if this is wrong
