### ISSUE TITLE
`[BindRequired]` does very little when associated with a simple `struct` property

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5391]
Noticed while investigating #4630.

Adding `[BindRequired]` to a `struct` property adds an error message (`"A value for the 'SomeProperty' property was not provided."`) to `ModelState` when users leave the field empty. But, `Html.ValidationMessageFor()` (or similar) almost never shows that error because the `SimpleTypeModelBinder` adds an error (`"The value '' is invalid."`) in the same case -- and does that first.

E.g. the `[BindRequired]` error message will only be visible for the following property if the submitted `<form>` contains no `RequiredInt` field.
``` c#
[BindRequired]
public int RequiredInt { get; set; }
```

Probably need a way for `ComplexTypeModelBinder` to disable the `SimpleTypeModelBinder` error case. Or, need to update documentation to make it clear the same error is displayed for an empty `struct` value whether or not a `[BindRequired]` attribute is associated.

One exception to all of the above is a `struct` that lacks a conversion from `string`. `SimpleTypeModelBinder` won't handle that type. (`KeyValuePairModelBinder` or a custom model binder might handle it.)

**Comment by Eilon** [comment]
There doesn't seem to be a case where this would happen in practice, is there? I.e. a browser would never send such a request because it always posts all values, even if they're empty.

**Comment by dougbu** [comment]
We've said `[BindRequired]` is a suitable replacement for a `[Required]` attribute on a value type. I was looking for a way to make that advice correct.

Put another way, `[BindRequired]` on a value type changes nothing w.r.t. errors users see outside a debugger. I thought it should.

FYI MVC actually honours a `[Required]` attribute on a value type but only when generating attributes for client-side validation. The attribute remains irrelevant w.r.t. server-side validation. That is, the `ErrorMessage` is read but `IsValid()` never fails.
