### ISSUE TITLE
IClientModelValidator MergeAttribute() method

### ISSUE THREAD

**Issue by stap123** [aspnet/Mvc#5392]
Hi, in the docs here (https://docs.asp.net/en/latest/mvc/models/validation.html#id9) an example of implementing IClientModelValidator is given and in that example a method called MergeAttribute() is called. I have looked through the docs and searched around as best I can but I can't find a reference to this method anywhere.

Which assembly/package is it located in? 

Many thanks, keep up the good work.

**Comment by Muchiachio** [comment]
It's declared in [ValidationAttributeAdapterOfTAttribute](https://github.com/aspnet/Mvc/blob/d09e921c4a896865b0bd81bd99e8e69dc19460b7/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/ValidationAttributeAdapterOfTAttribute.cs#L49) type.
You don't really have to use this method, you can simply set it like this
```C#
public override void AddValidation(ClientModelValidationContext context)
{
    context.Attributes["data-val"] = "true";
    context.Attributes["data-val-custom"] = "Error message";
}
```

**Comment by stap123** [comment]
Thanks @Muchiachio , I have done as you suggested for the time being but I was just wondering where it was so that I could use it if I wanted to. I tend to copy what Microsoft do in terms of their elements because I know they have spent more time working out the best/fastest way of developing these things.

**Comment by dougbu** [comment]
The documentation displays snippets of a working sample, not all the pieces you need. While MVC uses a similar method internally, the better place to look is later in [`ClassicMovieAttribute`](https://github.com/aspnet/Docs/blob/master/aspnet/mvc/models/validation/sample/ClassicMovieAttribute.cs#L44-L53). Comments on the doc page such as [this one](https://docs.asp.net/en/latest/mvc/models/validation.html#comment-2909238367) also contain the source.

**Comment by donkitchen** [comment]
I agree with the comments about the documentation being incomplete.  It references a method called GetErrorMessage that is nowhere to be found in the sample code.

**Comment by waelkdouh** [comment]
They have added the GetErrorMessage. Here it is:

private string GetErrorMessage()
{
    return $"Classic movies must have a release year earlier than {_year}.";
}
