### ISSUE TITLE
Changing Layout of RazorPage at runtime doesn't work

### ISSUE THREAD

**Issue by mythz** [aspnet/Mvc#5398]
Using the technique [from this Issue to Render an MVC View to a string](https://github.com/aspnet/Mvc/issues/3091) it doesn't seem possible to change the Layout a RazorPage at runtime. This would be useful for reusing Razor Views in different Layouts, e.g. Emails, Mobile websites, dynamic layouts, etc.

Whilst there's a `Layout` property on `RazorPage`, changing it has no effect:

```csharp
//Changing Layout at runtime has no affect atm
if (layout != null && razorView != null)
    razorView.RazorPage.Layout = layout; //Change layout at runtime

var actionContext = new ActionContext(
    ((HttpRequest) req.OriginalRequest).HttpContext,
    new RouteData(),
    new ActionDescriptor());

using (var sw = new StreamWriter(req.Response.OutputStream))
{
    if (viewData == null)
        viewData = CreateViewData((object)null);

    viewData[Keywords.IRequest] = req;
    var viewContext = new ViewContext(
        actionContext,
        view,
        viewData,
        new TempDataDictionary(actionContext.HttpContext, tempDataProvider),
        sw,
        new HtmlHelperOptions());

    view.RenderAsync(viewContext).GetAwaiter().GetResult();
}
```

It would be ideal if there was an official API we could use to specify which `Layout` page to use.

**Comment by pranavkm** [comment]
Does your page explicitly set the layout i.e does it or a `_ViewStart` have a value that says `Layout = "..";`? If so, the value you set here is getting overriden by the execution. You could always pass in data to your page (for instance via `ViewData`) that sets the Layout value:

e.g.

```
 if (viewData == null)
        viewData = CreateViewData((object)null);

viewData["Layout"] = "MyEmailLayout";
...
```
```
Index.cshtml

@{
  Layout = ViewData["Layout"] ?? "_Layout";
}
```

**Comment by mythz** [comment]
It's set it in the page, i.e. `Layout = "..";`

But this works, thx!

```csharp
Layout = ViewData["Layout"] as string ?? "_Layout";
```
