### ISSUE TITLE
Default behavior for optional parameters

### ISSUE THREAD

**Issue by audacity76** [aspnet/Mvc#5399]
I call a GET action with an optional complex parameter:
`public ActionResult Test(Foo obj = null) ...`

I don't send any query parameters with the call. As an result I get an empty Foo object. Is there a way to change this behavior to get a NULL value instead?

**Comment by dougbu** [comment]
`ControllerActionInvoker`, `ControllerActionExecutor` and `ObjectMethodExecutor` always creates instances of POCO action arguments. The default value provided in the action signature is therefore not relevant.

It is theoretically possible to override the `ControllerActionInvoker` with a custom `IActionInvokerFactory` but I would not recommend it.

Instead, implement an `IActionFilter` or `IAsyncActionFilter`. Change the `ActionExecutingContext.ActionArguments` to whatever values you want in that filter. E.g. detect use of your POCO type and check whether all properties have their default values or add a `[BindRequired]` attribute to a property and use that to decide `null` might be better.

**Comment by Eilon** [comment]
@dougbu @rynowak is there a particular technical reason why the top-level object of the parameter is always created? Or is it perhaps just historical?

@audacity76 can you tell us more about the scenario you have and why you'd like it to be `null`? If you can show some more of your app's code that would be great. Thanks!

**Comment by dougbu** [comment]
> Or is it perhaps just historical?

Yes, our action invocation infrastructure behaves this way for backward compatibility with at least MVC 5.x. I don't remember the Web API behaviour in this area.

**Comment by audacity76** [comment]
@Eilon the reason I want the NULL value is that I need to set default values on the object if it is not given. I don't want to set the default values in the Foo class itself because it is used in other scenarios (controller actions) with other defaults. My current workaround is:

```
public ActionResult Test(Foo obj = null)
{
    if (HttpContext.Request.Query.Count == 0)
        obj = new Foo { ... default values ... };
    ...
}
```

**Comment by Eilon** [comment]
Due to compatibility reasons we have no plans to change this behavior.
