### ISSUE TITLE
Label Tag helper not working when used in a loop

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/Mvc#5404]
**Model**:
```
public class StateName
 {
        public int StateId { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
}
```
**View**:
```html
@model List<myProj.Models.StateName>

<form id="target" asp-controller="TestController" asp-action="TestAction" asp-route-returnurl="@ViewData[" ReturnUrl"]" method="post">
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>
                    State Name
                </th>
                <th>
                    State Code
                </th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count(); i++)
            {
            <tr>
                <td><input asp-for="@Model[i].StateId" type="hidden" /></td>
                <td>
                    <label asp-for="@Model[i].State"></label>
                </td>
                <td>
                    <input asp-for="@Model[i].StateCode" type="text" readonly style="border:0px;"/>
                </td>
            </tr>
            }
        </tbody>
    </table>
    <button type="submit" class="btn btn-default">Save</button>
</form>
```
**Actual Display**: Note that it's displaying the values in the `State Code` column correctly but in `State Name` column its displaying the values as column name instead. Hence the input tag works fine but not the label tag.
![capture](https://cloud.githubusercontent.com/assets/10931726/19320777/a837ed48-9080-11e6-9f64-381320e6eb8a.PNG)

**Expected Display**:
![capture1](https://cloud.githubusercontent.com/assets/10931726/19320790/b249c0c2-9080-11e6-9cd5-177ddd7240ef.PNG)

**Comment by Eilon** [comment]
This is by design because the `<label>` tag helper is showing a *label* for the given property. By default it shows the property name. You can even make it show a localized value if you have annotated the property with Data Annotations.

To have the label render the *value* of the property, you don't need any tag helper at all:

```html
<label>@Model[i].State</label>
```
