### ISSUE TITLE
FromBody not working as hoped if set on a property of a model (JsonReaderException)

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Mvc#5407]
Take a simple case:

```cs
        public class CreateCommand
        {
            [FromBody]
            public string Content { get; set; }
        }

        [HttpPost("/myurl")]
        public void AddNew(CreateCommand command)
        {
            [...]
        }
```

Send it a post with the body:

```json
{ "content": "TestContent" }
```
And see that it errors out with a JsonReaderException. 
Message:
```
Unexpected character encountered while parsing value: {. Path '', line 1, position 1.
```

Why is the FromBody, if set on a simple type property, so rudimentary?

Why is it not allowed to wrap values in a root object?

I would expect it to be good DX (developer experience) for this case to just work.

It seems that modelbinding should have plenty to go on once the formatter has returned the deserialized object graph, why not work with that?

**Comment by leppie** [comment]
I guess `FromBody` should be limited to parameters only... still (as you say) DX fail.

**Comment by dougbu** [comment]
The problem here is the body is a JSON object and not just the string. Send just `"TestContent"` and all should be fine.

**Comment by NinoFloris** [comment]
@dougbu I know how to fix the immediate 'problem' but I'm actually contesting this as I think this should not be a problem at all. 

It's really bad it currently works like that. Considering the amount of effort the other types of binding sources put in to try to parse something into a model FromBody is really too simplistic and just falls short of ASP.NET standards.

I imagine changing FromBody to something useful would be a big BC break. 
Would prototyping something like a FromBodyModel (with backing modelbinding plumbing) be something you'd welcome a PR (RFC) for?

**Comment by dougbu** [comment]
@NinoFloris why would `[FromBody]` reinterpret the submitted JSON? What are you suggesting should happen when the service _is_ expecting a JSON object e.g. the entire `CreateCommand` as your client submits in the original scenario?

**Comment by NinoFloris** [comment]
I'd like to see it being able to map the body to the structure and root of the `CreateCommand` model and try to fill it out from there.

What I aim for is a way to:

- Align the value model object hierarchy (the deserialized json) to the root model `CreateCommand` (so that the start is absolute, not relative as FromBody does) 
- Then for every FromBodyModel attribute bind the best matching value model value by:
    1. Making sure we drilled down to the same graph depth on the value model side as we have on the result model side    
    2. Then based on naming strategy (snake_case to CamelCase) and other distinctions we get the best value from the value model and we bind this value (possibly even running your custom modelbinder) to the blank spot in the result model
    3. Repeat

This allows for quite a few multi source bound model scenario's that are currently quite painful to write.

Say you have a few properties that should be bound from route or query data and other parts of your model are selectively (or broadly, any way you like) built up from the body data.  

This is painful:
```cs
public class Query 
{
    public string Filter { get; set; }
}

public class Route
{
    public int Id { get; set; }
}

public class Body
{
    public string Content { get; set; }
    public string OtherBodyProp { get; set; }
}

public class CreateCommand
{
    public CreateCommand(Query query, Route route, Body body)
    {
       // Tie it all together into this object
    }

     // All props simple and complex type for source values here
}
public async Task AddNew([FromQuery]Query query, [FromRoute]Route route, [FromBody]Body body, [FromServices]IMediator mediator)
{
   // This constructor pieces all the values inside these objects together by mapping them onto its own structure
   var command = new CreateCommand(query, route, body);
   
   var result = await mediator.SendAsync(command);
}
```
I used the word mapping in this comment as that is what modelbinding is good at and that is its job that we are having to do manually here.

To clarify I explicitly want some control over how my result model looks and I also want to weave in, at select places, values from other sources into this model. So a simple "why don't you define a result model with a `public MyType Body { get; set; }` where MyType is a fit for the request body model" is not what I'm aiming for.

**Comment by Wallsmedia** [comment]
I think the answer is very simple:
1. Serialize with JSON the:  "string Content"
2. Use it instead of what you sent via body.
Let us know about results.

**Comment by Eilon** [comment]
I think this is possible to do today by having a custom binding source that would essentially be a "BodyJsonBindingSource", and that would actually be somewhat similar to behavior that existed in ASP.NET MVC 5.x.

I think you'd need a new `FromJsonBody` attribute (similar to https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/FromBodyAttribute.cs), and a new Value Provider (similar to https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/FormValueProvider.cs). That value provider would use JSON to interpret the request body and "slice and dice" it into whatever model binding requests from it.

We have no plans to ship this in the box, but if you end up building something like this we'd be happy to link to it from our home page.

**Comment by Wallsmedia** [comment]
Absolutely agree about attribute "FromBodyJson", but you can use custom binder type. Net Core don't use value providers to parse Json, XML, ... from Body. 
The similar idea for XML is here:
[https://github.com/aspnet/Mvc/pull/5454]
