### ISSUE TITLE
Model Security on Round-Trip

### ISSUE THREAD

**Issue by davimack** [aspnet/Mvc#5412]
When a model is returned to the controller, it is expected that only certain properties of that model will have been updated by the user.  This can be addressed by using a [Bind()] decorator for the model, but this process is currently laborious (e.g. string property names) and decentralized (multiple controllers could manipulate a single model, with multiple developers deciding which properties will be changed, etc.).

I propose that the model itself should be somewhat aware of 1) the methods which will be accepting a user-modified model, and 2) which properties are modifiable by each of those methods.  I further propose that there should be some mechanism for merging a previously-saved version of the model with an incoming version of the model, so that only the expected-to-be-changed properties are merged with the previously-saved data.  Additionally, there should be some mechanism for comparing the properties between the saved and modified versions so that a decision can be made at the controller level about what to do with the modification (I'm thinking that a single method, returning a bool, would be ideal, rather than having to write this on a per-model basis).

There is a further problem with returning modified models to the controller, in that the F12 console allows the modification of pretty much any input, and there's no built-in mechanism to determine whether such a modification has taken place.  This is particularly concerning when you consider the fairly common practice of using hidden inputs to store database identifiers.  Consider the case where an id is embedded in the page and the user modifies this hidden input to another id and happens to hit upon a valid id.  The controller has no way of knowing that such a modification took place, and nor does the back-end database system know that the request isn't valid.

I propose the inclusion of some sort of a checksum or encrypted blob representing the properties which are not expected to be modified at the time the model is returned from the controller to the view.  This would mean that the controller would know, at the time of view generation, which properties should be modifiable by the resultant view; all other properties would be checksummed / encrypted such that the view could preserve that content in a hidden input and reconstitute the model state of those non-modifiable properties upon posting of that particular form.

**Comment by dougbu** [comment]
In what cases do antiforgery tokens not meet your needs? That feature disallows submissions from anywhere but the original `<form>`. Assuming the `<form>` uses hidden `<input>` fields for values that are for correlation only, this feature should be more than you need.

**Comment by davimack** [comment]
Agreed, antiforgery tokens will protect against the F12 modification case alone.

I would like to 1) proactively determine, at the model level, which properties should be modifiable by a given controller method, 2) reconstitute the model state of those properties which should not be modified (but which may have been, given a view which may not have been constructed properly).  I'm not particularly worried about the F12 case, as I put antiforgery tokens into my views & require them on my controller methods.  What I'm worried about, though, is other developers not understanding what the requirements are & inadvertently allowing the user to modify properties which should not be modified in that particular view / controller method.  It seemed to me that rather than using an antiforgery token, if the non-modifiable properties could be serialized in a secure fashion, then this could be used to perform a check at the controller such that any properties which should not have been modified are either flagged or throw an exception or something.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
