### ISSUE TITLE
Can't handle comments in media type strings though some infrastructure supports them

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5417]
Should either add support for comments in `MediaType` (perhaps in `HttpTokenParsingRules.GetWhitespaceLength()`) or remove comment support from `HttpTokenParsingRules`.

[RFC 2045](https://tools.ietf.org/html/rfc2045#page-13) specifically mentions

> In addition, comments are allowed in accordance with [RFC 822](https://tools.ietf.org/html/rfc822) rules for structured header fields.  Thus the following two forms
> - Content-type: text/plain; charset=us-ascii (Plain text)
> - Content-type: text/plain; charset="us-ascii"
> 
> are completely equivalent.

However `MediaType` does not ignore [comments](https://tools.ietf.org/html/rfc822#section-3.4.3). Comments should basically be treated like whitespace but are not.

If we decide we do not need comment support, the extra complexity in `HttpTokenParsingRules.GetExpressionLength()` (for exactly this feature) should be removed. Don't need nesting support for quoted strings for example.

**Comment by rynowak** [comment]
I suggest we move this issue to HttpAbstractions, as it's our goal to move all of the actual parsing logic there.

**Comment by pranavkm** [comment]
Think this is covered as part of sharing code with HttpAbstractions. See https://github.com/aspnet/Mvc/issues/5416 and https://github.com/aspnet/Mvc/issues/6743. I don't think we would want to make changes to the type if the plan is to replace it in the future. Feel free to reopen if you think otherwise.
