### ISSUE TITLE
ViewComponent TagHelpers don't work with IDictionary<string, string> parameter

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5424]
This (legit) ViewComponent doesn't show up as a TagHelper:

```
    public class Sync : ViewComponent
    {
        public Task<string> InvokeAsync(IDictionary<string, string> args)
        {
            args = args ?? new Dictionary<string, string>();
            return Task.FromResult($"<span>{string.Join(", ", args)}</span>");
        }
    }
```

```
    <vc:Sync></vc:Sync> @* does not work *@
    @await Component.InvokeAsync("Sync", new { }) @* works *@
```

**Comment by rynowak** [comment]
Investigated more and found that the issue is with `IDictionary<string, string>` not the naming.

**Comment by Eilon** [comment]
@ajaybhargavb is this a dup of https://github.com/aspnet/Mvc/issues/5216?

**Comment by rynowak** [comment]
#5216 is about open generics no?

**Comment by NTaylorMullen** [comment]
Nah, it's about anything that's generic. This is a dub.

**Comment by Eilon** [comment]
I don't think open generics can even be used here - you're invoking an actual method, so it can't be open at that time.

Closing as dup of https://github.com/aspnet/Mvc/issues/5216.

**Comment by rynowak** [comment]
But I don't want to do open generics 👎
