### ISSUE TITLE
Inconsistency between localization of RequiredAttributeAdapter and NumericClientModelValidatorProvider

### ISSUE THREAD

**Issue by Anks51** [aspnet/Mvc#5428]
Good day

I found an inconsistency between localization of RequiredAttributeAdapter and NumericClientModelValidatorProvider both use in MVC client-side validation. By default 'RequiredAttributeAdapter' use localization since it inherit from ValidationAttribute. However, by default 'NumericClientModelValidatorProvider' don't, since the ressource used only include 'EN'. 

To reproduce the inconsistency :

Culture : en-CA
Culture UI : fr-CA

Html in View
`<input asp-for="TestNum" class="no-focus form-control" />`

Model

```
    public class TestModel
    {
        [Required]
        public decimal TestNum { get; set; }
    }
```

Note : I know that it is possible to change the value in Startup.cs, however I wanted to note this behavior.

```
services.AddMvc(setup =>
            {
                setup.ModelBindingMessageProvider.ValueMustBeANumberAccessor = ModelBindingMessageDescriber.FormatHtmlGeneration_ValueMustBeNumber;
                setup.ModelBindingMessageProvider.ValueIsInvalidAccessor = ModelBindingMessageDescriber.FormatHtmlGeneration_ValueIsInvalid;
            })
```

**Comment by dougbu** [comment]
@Anks51 what would you like to see change? Is something about the `Startup` snippet you showed not working?

Were you hoping `NumericClientModelValidatorProvider` was configured more like a `ValidationAttribute`? If so, I would appreciate suggestions.

Also, is your concern about the `ResourceManager` localization the `ValidationAttribute`s use by default or the `IStringLocalizer` approach available in ASP.NET Core?

----

If you're asking about what `ValidationAttribute`s do out-of-the-box, resources are only available for full desktop .NET and often only when .NET language packs are installed.

If you're asking about the `IStringLocalizer` approach, note the following is not true.
> By default 'RequiredAttributeAdapter' use localization since it inherit from ValidationAttribute.

Must call `services.AddMvc().AddDataAnnotationsLocalization()` and give the `ValidationAttribute` a non-`null` `ErrorMessage`.

**Comment by danroth27** [comment]
Not enough information to really respond to this one. Closing.
