### ISSUE TITLE
Intellisense shows names of generated type names for views

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#5429]
Noticed this when I was trying to work on sign-offs. If you have a cshtml file open, intellisense includes type names for the view's generated cs files:

![image](https://cloud.githubusercontent.com/assets/174281/19535146/75a6ad6c-95fb-11e6-9549-cb453ebd67a5.png)

Might be useful to add a `[EditorBrowsable(EditorBrowsableState.Never)]` to the generated code.

**Comment by dougbu** [comment]
I've seen a similar display under a `.cshtml` file in Solution Explorer i.e. VS treats the file as a regular `.cs` file and nests the contained `class` within it. Not sure exactly when this happens (can't get it to reproduce this morning) but likely related.

**Comment by rynowak** [comment]
I've actually already reported this to @BillHiebert and he opened a TFS issue for it I'm told.

**Comment by BillHiebert** [comment]
@rynowak  Sorry, I don't remember this issue. Is this different than other projects with razor?

**Comment by BillHiebert** [comment]
Sorry, I was confused as to what the issue was. We have the following bug tracking this: 269726 : Razor files should be opened in isolated Intellisense Projects

**Comment by Eilon** [comment]
Oh if we can fix on the tooling side that's great. But from the runtime side we're not super concerned about it either way 😄
