### ISSUE TITLE
MiddlewareFilter: Using a ConfigureType without a parameterless constructor should print a better exception message

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#5431]
I used a `ConfigureType` on a `MiddlewareFilter` that took an argument (in this case I tried using `ILoggerFactory`). It failed with the following stack trace providing me no clue as to what was missing a parameterless constructor:

```
MissingMethodException: No parameterless constructor defined for this object.
System.RuntimeTypeHandle.CreateInstance(RuntimeType type, bool publicOnly, bool noCheck, ref bool canBeCached, ref RuntimeMethodHandleInternal ctor, ref bool bNeedSecurityCheck)
System.RuntimeType.CreateInstanceSlow(bool publicOnly, bool skipCheckThis, bool fillCache, ref StackCrawlMark stackMark)
System.RuntimeType.CreateInstanceDefaultCtor(bool publicOnly, bool skipCheckThis, bool fillCache, ref StackCrawlMark stackMark)
System.Activator.CreateInstance(Type type, bool nonPublic)
System.Activator.CreateInstance(Type type)
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterConfigurationProvider.CreateConfigureDelegate(Type configurationType)
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.BuildPipeline(Type middlewarePipelineProviderType)
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder+<>c__DisplayClass7_0.<GetPipeline>b__1()
System.Lazy.CreateValue()
System.Lazy.LazyInitValue()
System.Lazy.get_Value()
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.GetPipeline(Type configurationType)
Microsoft.AspNetCore.Mvc.MiddlewareFilterAttribute.CreateInstance(IServiceProvider serviceProvider)
```

We should have better diagnostics for this case.

**Comment by pranavkm** [comment]
Slightly related, it's not particularly obvious what the contract for `ConfigureType` is. `Startup` has the benefit of being part of the template versus this is a bit of a guessing game. Plus it doesn't look like it supports the `Configure{Environment}` pattern that startup supports. Was there a reason we don't have a contract interface for `ConfigureType`? It would make discovery a bit easier.

**Comment by rynowak** [comment]
For all of the same reasons we don't have it for startup.

**Comment by Eilon** [comment]
@jbagga need to close this issue?

**Comment by jbagga** [comment]
I was waiting for @pranavkm. He mentioned the Configure

**Comment by Eilon** [comment]
Per discussion, please close this issue, but log a new issue for the `Configure{Env}` thing.
