### ISSUE TITLE
Make Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilter internal

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#5432]
When attempting to add `MiddlewareFilter` (you really want to add `MiddlewareFilterAttribute`) as a global filter, this pops up in the intellisense.  Maybe we can come up with a better name. Particularly crummy since the former matches the attribute on an action.

**Comment by rynowak** [comment]
Or maybe make it internal for realsies?

**Comment by Eilon** [comment]
Yeah let's just make it actually `internal`.
