### ISSUE TITLE
Use action parameter as the model state key when validation fails on the top level object.

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#5433]
```C#
        [HttpPut("ModelBinding/Validations")]
        public IActionResult Validations([FromBody]Validations value){
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            
            return Ok(value);
        }
    }

    public class Validations : IValidatableObject
    {
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield return new ValidationResult("Not cool");
        }
    }
```

The json that comes back is:
`{"":["Not cool"]}` which is not very descriptive. We could make it `{"value":["Not cool"]}`

**Comment by Eilon** [comment]
This would be a breaking change, so it is doubtful we would take this.

Also, are there other cases where the *parameter name* is the sole determiner of what gets put into model state? Often with model binding the parameter name *matches* the posted data, but the essence is really the structure of the posted data, not the action method's parameter's name.

In other words: should changing the parameter name of the method affect the contents of model state? (I'm thinking the answer is a definite "no".)

@dougbu @rynowak thoughts on this?

**Comment by dougbu** [comment]
The default is what it is (`string.Empty` unless the parameter name was used to find the data) for back-compat reasons.

Use `[Bind(Prefix = "...")]` to get a different top-level key for a `[FromBody]` parameter. For most other binding sources, use the `Name` property of the controlling attribute e.g. `[FromForm(Name = "...")]`.

PS.
> should changing the parameter name of the method affect the contents of model state?

Change the parameter name from something that matches the submitted data and you'll get lots of new errors in the model state dictionary 😈

**Comment by javiercn** [comment]
I'm aware what I'm proposing is a behavior change, but I think of it from the point of view of technologies like swagger where the requests have parameters with names it provides for a more consistent experience.
If I have a parameter in my API named "customer" that comes from the body and another parameter "bar" that comes from the query, I would expect any top level error for that parameter to show up under the parameter name key.

**Comment by rynowak** [comment]
@javiercn - a lot of things about our strategy in this area just aren't that useful for API authors. We haven't solved it.

`{"value":["Not cool"]}` - doesn't solve the problem either. Nothing about the name `value` is significant to the client.

**Comment by Eilon** [comment]
Closing this issue because we don't plan to make the change proposed here. But if there's some alternative proposal, we can certainly log a new issue for that.
