### ISSUE TITLE
`ViewLocalizer` can only find resources in the main assembly

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5435]
When using an assembly containing embedded views and resource strings, things **Just Work:tm:** if it is the application assembly. A `ViewLocalizer` in these views finds the correct resources and strings are correctly localized.

However when using the same assembly as a class library, `ViewLocalizer` still looks for resources in the main assembly. It cannot be reconfigured to find resources elsewhere let alone to use different locations for different views.

Note precompiled views do not avoid issues here. `IRazorPage` implementations are compiled into a different assembly than string resources are placed. The associated assembly could be found by reversing the naming convention (maybe) but we also have a layering problem here: Want the localization system to work regardless of the `IViewEngine` implementation and the `interface`s do not expose the view's `Type`. And, use of a `Type` is an implementation detail of our `IViewEngine` implementation.

At least for embedded views using `ViewLocalizer`, we need a wire-up alternative to

``` c#
var embeddedProvider = new EmbeddedFileProvider(typeof(Model).GetTypeInfo().Assembly);
services
    .AddMvc()
    .AddRazorOptions(options => options.FileProviders.Add(embeddedProvider))
    .AddViewLocalization();
```

The alternative could be automatic -- discover and use embedded views and string resources in `ApplicationPart`s _together_. (`ApplicationPart`s are not checked for embedded views at all today.)

Or we could provide something explicit that extends `AddViewLocalization` e.g.

``` c#
public static IMvcBuilder AddViewLocalization(
    this IMvcBuilder builder,
    Assembly assembly)
```

and does everything necessary. Method should be callable multiple times.

Either of the above approaches (and likely any solution) requires additional context carried through the system as well as changes in our MVC infrastructure use of a single `CompositeFileProvider` instance (losing information about the original location of embedded files).

---

Found working with sample application at [dougbu/Localized.1.1-preview](https://github.com/dougbu/Localized.1.1-preview). Execute the `Localized.1.1-preview` application and the user sees everything as expected. Execute the `Wrap.Localized` application and strings localized using a `ViewLocalizer` always display in English.

**Comment by pranavkm** [comment]
This works out of the box with Razor Class libraries. Since it's our recommended pattern for sharing views via class libraries (over embedded files), really nothing to do here.
