### ISSUE TITLE
Must call `AddViewLocalization()` to use `IStringLocalizer<T>` in an application

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5436]
Whether or not a user wants a `LanguageViewLocationExpander` in their application, this method is the one-stop shop for registering `IHtmlLocalizer<T>`, `IStringLocalizer<T>`, and `IViewLocalizer` in an MVC application. On the upside, this one call gives the application _almost_ all available localization capabilities e.g. it registers the [aspnet/Localization](https://github.com/aspnet/Localization) services (as does `AddDataAnnotationsLocalization()`).  However, the method has a narrow (less discoverable) name and does not enable localization of `ValidationAttribute` error messages.

Suggest we need to reduce the `Startup` boilerplate a bit and provide a single method encompassing what `AddDataAnnotationsLocalization()` and `AddViewLocalization()` do. Would at least take us from

``` c#
services
    .AddMvc()
    .AddDataAnnotationsLocalization()
    .AddViewLocalization();
```

to

``` c#
services
    .AddMvc()
    .AddMvcLocalization();
```

May also want another method that enables neither the `LanguageViewLocationExpander` nor localization of `ValidationAttribute` error messages. Users would only get the localization services for their explicit use.

---

Found working with sample application at [dougbu/Localized.1.1-preview](https://github.com/dougbu/Localized.1.1-preview).

**Comment by dougbu** [comment]
Should have said: The potential method that does less than `AddDataAnnotationsLocalization()` or `AddViewLocalization()` would still do more than `services.AddLocalization()` in that `IHtmlLocalizer<T>` and `IViewLocalizer` services would be registered.

**Comment by Eilon** [comment]
@DamianEdwards @ryanbrandenburg , thoughts on this?

Should we do all/some/none of this?

**Comment by DamianEdwards** [comment]
What exactly is being proposed here? I got a little confused with some of the phrasing, but it appears we simply want to add a `.AddMvcLocalization()` extension method that adds all localization features, including the base localization services, along with view (`IViewLocalizer` and locale-based view location exapnder) and data attribute localization. If so, that sounds like a very useful addition.

**Comment by Eilon** [comment]
@DamianEdwards yes I believe that's the request.

@dougbu can you update any relevant samples to use this as necessary?

**Comment by dougbu** [comment]
@Eilon sure. I'll include the samples in the work when I get to this bug.

FYI @DamianEdwards nailed my intention with "add a `.AddMvcLocalization()` extension method that adds all localization features".

----

> May also want another method that enables neither the `LanguageViewLocationExpander` nor localization of `ValidationAttribute` error messages. Users would only get the localization services for their explicit use.

In retrospect, this subset of `MvcLocalizationServices.AddMvcLocalizationServices()` isn't worthwhile. Would operate like the existing method but not add a `LanguageViewLocationExpander`. Users can remove that instance from the `ViewLocationExpanders` collection explicitly.

**Comment by Eilon** [comment]
@ryanbrandenburg let's do what @DamianEdwards  mentioned here: https://github.com/aspnet/Mvc/issues/5436#issuecomment-269367318

**Comment by Eilon** [comment]
Because this is strictly additive, moving to 2.1.0.
