### ISSUE TITLE
ImageTagHelper doesn't work for user defined FileProvider

### ISSUE THREAD

**Issue by korn3l** [aspnet/Mvc#5445]
I want to add versioning for images that I'm not serving from the default 'wwwroot' location, but it seems it doesn't work.

In Startup.cs Configure method I have:
```
app.UseStaticFiles();

app.UseStaticFiles(new StaticFileOptions()
{
    FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), @"images")),
    RequestPath = new PathString("/images")
});
```

In my view i have:
`<img  src="/images/logo.png"  asp-append-version="true">`

logo.png is located in the path defined above. If I move it to wwwroot/images it works as expected.

After looking at the code it seems that the taghelper uses HostingEnvironment.WebRootFileProvider for the FileVersionProvider which explains what I'm experiencing.

**Comment by dougbu** [comment]
Use `IWebHostBuilder.UseWebRoot()` in your `Main()` method to change the base of the `IHostingEnvironment.WebRootFileProvider`. If you prefer to have more than one web root, instantiate a `CompositeFileProvider` containing the file providers you need e.g. in `Startup`
``` c#
public void Configure(IApplicationBuilder app, IHostingEnvironment hosting)
{
    var addedProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "images");
    hosting.WebRootFileProvider = new CompositeFileProvider(hosting.WebRootFileProvider, addedProvider);
    app.UseStaticFiles(new StaticFileOptions()
    {
        FileProvider = addedProvider,
        RequestPath = new PathString("/images")
    });
}
```

**Comment by dazinator** [comment]
Related issue: https://github.com/aspnet/StaticFiles/issues/158
Ended up creating this: https://github.com/dazinator/Dazinator.AspNet.Extensions.FileProviders
It seems that by using a FileProvider that can handle request paths (like the above) = configuring static files middleware with a file provider and a request path then becomes redundant.
