### ISSUE TITLE
Consider adding `IReadOnlyList` support to `MultiSelectList`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5447]
`MultiSelectList` and its `SelectList` subclass contain a lazily-evaluated `IList<SelectListItem>` which is not exposed. Because neither type is itself an `IList<SelectListItem>` the [consuming code](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L1521-L1525) in `DefaultHtmlGenerator.GenerateGroupsAndOptions()` always generates a new `List<SelectListItem>`. This new list is unnecessary and shows up rather high in memory profiles when views use either type.

Note creating a singleton (perhaps `static`) `MultiSelectList` does not help. `GenerateGroupsAndOptions()` allocates every time it is called.

Could add an `IReadOnlyList<SelectListItem>` property to `MultiSelectList` and special-case `MultiSelectList` in `GenerateGroupsAndOptions()`. Or, could change `MultiSelectList` to implement `IReadOnlyList<SelectListItem>` in addition to the current `IEnumerable<SelectListItem>`. I prefer the second choice because it's not clear why `GenerateGroupsAndOptions()` looks for only an `IList<SelectListItem>` in the first place.
##### BigViews

Exercises [Index.cshtml](https://github.com/aspnet/Performance/blob/dev/testapp/BigViews/Views/Home/Index.cshtml) view using [`.\loadtest.ps1`](https://github.com/aspnet/Performance/blob/dev/testapp/BigViews/loadtest.ps1). View uses a partial for 10 elements of a simple collection in a simple "index" page. Partial displays five properties of each POCO element and primarily uses `Html.LabelFor()`, `Html.IdFor()`, and `Model.PropertyName`. Uses a very simple disabled `Html.ListBoxFor()` for one of the five properties (similar to default display of a `bool?`).
###### `SelectListItem`-related allocations

All the allocations matched below are due to the `selectList.ToList()` call in `GenerateGroupsAndOptions()`. They amount to 10.75 MB and about 2% of the allocations for this run.
![bigviews - list of selectlistitem](https://cloud.githubusercontent.com/assets/6431421/19659952/cf28fddc-99e2-11e6-8ddc-b9ebd9eec3d5.png)

**Comment by Eilon** [comment]
Closing because this seems to be of marginal value.
