### ISSUE TITLE
Consider specifying attribute capacity of `AttributeDictionary`s and `TagBuilder`s

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5448]
The `KeyValuePair<string, string>[]` arrays backing attributes held in `AttributeDictionary`s are responsible for between 1.6% and 8% of the memory allocated in BasicViews, BigViews and MusicStoreViews scenarios. Unless all `AttributeDictionary`s contain exactly `4` attributes, a great deal of this memory is wasted.

One approach to reduce these allocations would be to add an `AttributeDictionary(int capacity)` constructor and allocate its backing `List<T>` there. Since that `class` is never used directly, would also need a new `TagBuilder(string tagName, int attributeCapacity)` constructor which uses the new `AttributeDictionary(int)` constructor. Both constructors would not allocate if the given capacity were `0`. Changing consuming code to calculate capacities and use the new constructors will not eliminate the arrays but should save lots of memory.
##### MusicStoreViews

Exercises [AddressAndPayment.cshtml](https://github.com/aspnet/Performance/blob/dev/testapp/MusicStoreViews/Views/Home/AddressAndPayment.cshtml) view using [`loadtest.ps1`](https://github.com/aspnet/Performance/blob/dev/testapp/MusicStoreViews/loadtest.ps1). View uses lambda-expression-based templating HTML helpers (with built-in templates) in a simple "create" form with ten fields, nine bound to a two-level POCO model.
###### `AttributeDictionary` entries

The only use of `KeyValuePair<string, string>[]` arrays is backing the `_items` within `AttributeDictionary`. In this scenario, the arrays are the topmost type used and represent 27.5 MB or about 8% of all memory used.
![musicstoreviews - attributedictionary entries](https://cloud.githubusercontent.com/assets/6431421/19661188/97ca5840-99e7-11e6-8e34-9253735085a5.png)

**Comment by Eilon** [comment]
I don't think we'd change the public API surface of these types, and I'd rather not add internal APIs for it.

If we can instead change this without API changes (e.g. choose smarter default capacities, or delay-create internal data structures), we could consider that instead.
