### ISSUE TITLE
Consider removing Linq use in `ModelExplorer.Properties`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5449]
`ModelExplorer.Properties` lazily loads a `List<ModelExplorer>` and fills this list with a Linq join across `ModelMetadata.Properties` (a `ModelPropertyCollection`) and `PropertyHelper.GetProperties(Type)` (a `PropertyHelper[]` array). This Linq expression could be completely avoided.
##### MusicStoreViews

Exercises [AddressAndPayment.cshtml](https://github.com/aspnet/Performance/blob/dev/testapp/MusicStoreViews/Views/Home/AddressAndPayment.cshtml) view using [`loadtest.ps1`](https://github.com/aspnet/Performance/blob/dev/testapp/MusicStoreViews/loadtest.ps1). View uses lambda-expression-based templating HTML helpers (with built-in templates) in a simple "create" form with ten fields, nine bound to a two-level POCO model.
###### `Properties`-related allocations

The Grouping<T> and `JoinIterator` allocations account for 5.75 MB or just under 1.7% of the total allocations for this scenario.
![musicstoreviews - modelexplorer properties](https://cloud.githubusercontent.com/assets/6431421/19661503/d8ea9b4a-99e8-11e6-812d-4a0f3fa10136.png)
![musicstoreviews - modelexplorer properties 2](https://cloud.githubusercontent.com/assets/6431421/19661506/db924384-99e8-11e6-87b5-030875cdb848.png)

**Comment by Eilon** [comment]
Looks like someone named @dougbu already snuck in and did this!

https://github.com/aspnet/Mvc/commit/7178464ed2e3d16d11a8f4a992bb7d9564424759#diff-c77786ef232a7bbd3a597afb31fde775L210

**Comment by dougbu** [comment]
Also updated to place this in the same milestone as #5499&hellip;
