### ISSUE TITLE
Custom TagHelper question

### ISSUE THREAD

**Issue by BryanFarrell** [aspnet/Mvc#5453]
Hello,

I made a custom tag helper to inject SVG files from my images folder directly into the HTML markup (for logos etc.).  This gives me two big advantages:  It keeps the SVG out of my markup when I do want it to be used as inline SVG.  It also allows me to use css so I can apply styles to the class names I've set on the SVG file paths without having to modify the SVG file directly which will make for a good separation of concerns.

This all works great with one issue.  I gave my tag helper a "src" attribute so I can use it like so:

`<svg src="images/logo.svg" />`

Like I said it works great and the SVG is rendered into the HTML perfectly.  The issue I have is relating to what I believe must be the VS Tools for ASP.NET Core.  For example if I use the LinkTagHelper as soon as I type:

`<link asp-append-version="true" href="`

A context menu comes up giving me the ability to browse the root of my wwwroot folder in the project and select a file and the href attribute is then updated with the relative file path automatically.

What I would like is for my custom TagHelper to also have this same functionality.  As I said I believe this is all part of the VS Tools for ASP.NET Core and not anything in the code itself.  I say this because I tried deriving from the same base class as LinkTagHelper (UrlResolutionTagHelper) and that had no effect so I suspect it's the Tools for VS itself that determines when to pop up the context menu to select files in the wwwroot folder.

My idea is to do the following.  Keeping with doing things by convention, is it possible to update the VS Tools to show that context menu to browse wwwroot any time a TagHelper derived class exposes specific attributes (like "src" and "href")?  This would allow us to write our own custom TagHelpers and give us the intellisense context menu support to quickly select a file from wwwroot.

The alternative now is I have to manually type it in which is not a big deal but I feel this feature would make custom TagHelper's that much more powerful for the end user going forward.

I hope you take my suggestion into consideration.  If there is some way I can do this currently please let me know as I would appreciate it!

Thanks,
Bryan Farrell

**Comment by dougbu** [comment]
Checked around a bit and found there's _probably_ a hack you could do but it's not recommended. The HTML schema files the `.cshtml` editor uses are on disk somewhere and you could add the `<svg>` element and your `src` attribute to that.

A more general feature involves extending Razor to include a new attribute or property on an existing attribute (likely `[HtmlAttributeName]`). Razor already informs Visual Studio of tag helper metadata and could extend that information to include the new detail that particular attributes on particular elements should be handled as local file locations. Right now, the tag helpers include none of that information because the VS editor uses both the Razor information and the HTML schema most MVC tag helpers target.

**Comment by BryanFarrell** [comment]
Thanks for the prompt reply Doug.  I agree hacking around in the HTML schema files doesn't sound like a good idea.  To your latter point that sounds like I'd be diving deep into the implementation of MVC and based on your reply I have a feeling it would be a lot of research to do so.  For me it's definitely easier just to make sure I type the paths in correctly for now.

That being said do you anticipate any kind of feature support like I suggested sometime in the future so custom TagHelpers can have a property decorated with an attribute telling the engine it should be handled as local file locations?  

Or perhaps a section in VS config where we could define statements that could be slip streamed into the schema files that the editor uses (basically add it to the core schema dynamically) without hacking into the framework?

**Comment by dougbu** [comment]
> I'd be diving deep into the implementation of MVC

The issue certainly could be marked as up-for-grabs but let's not start from the assumption you'd do the work.

> you anticipate any kind of feature

I wasn't weighing in on the triage decision but anticipate that will come soon.

> perhaps a section in VS config

Sounds less likely given config isn't a source for IntelliSense in the `.cshtml` editor today.

> start learning how to extend Razor

If you're interested in general, clone the MVC repo and have a look at how it uses the Razor API. Then have a look at the Razor code for additional extensibility opportunities.

But, no external extensibility point exists to provide more information to the editor. And the editor can't be changed externally to consume it. Need a bit more to get what you need for this feature.

**Comment by BryanFarrell** [comment]
Hi Doug,

Thanks for clarifying what you meant. Definely doesn't sound like something I'd work on myself if you guys might consider looking into it as a general feature. 

Looking at this from a different perspective my TagHelper really is a generic raw markup injector. I happen to use it for SVG's but it would work for any raw markup as it just renders the contents of the file to the output. 

Do you guys have any approval process for community TagHelpers getting included in the core repo?  My helper is really only about 20 lines of code and others might find it useful enough to include I your repo. 

Let me know and I'll add it in or just include it here, whatever you would prefer. 

If you think my original suggestion is worth looking into just let me know and I'll keep an eye on this ticket. 

Thanks again,
Bryan

**Comment by dougbu** [comment]
> Do you guys have any approval process for community TagHelpers getting included in the core repo?

Open an issue about the feature of injecting markup from a file. See how that fairs in triage. If accepted, submit a PR for the targeted milestone.

**Comment by BryanFarrell** [comment]
@NTaylorMullen this is the issue I originally created that requested the functionality you proposed in [this issue](https://github.com/aspnet/Razor/issues/429).  Just wanted to give you a heads up so you can close this one as a duplicate of that one if that is your process.

Thanks,
Bryan

**Comment by Eilon** [comment]
No plans to implement this feature, so closing this.
