### ISSUE TITLE
Error NU1001: The dependency Microsoft.AspNetCore.Mvc.Formatters.Xml >= 1.0.1 could not be resolved.

### ISSUE THREAD

**Issue by stanuku** [aspnet/Mvc#5456]
*** This seems to be a common/recurring issue with the dotnet tooling (Error NU1001: The dependency xxxxx could not be resolved) ***

I've a ASP.NET Core 1.0.1 project with a plain vanilla controller returning XML not Json.
This project references a csproj library (4.6.2). I had the solution building fine on the build server until I added the package **Microsoft.AspNetCore.Mvc.Formatters.Xml** reference to the ASP.NET Core project, that is when the build started failing with the error mentioned in the title. 

- Interesting enough, if I reference **Microsoft.AspNetCore.Mvc.Formatters.Json** package instead. The builds succeeds. 

- Also, the project builds and executes fine in VS. However on my build server,  I've been pulling my hair to resolve this build error.

My very simple build steps:
Step 1. Nuget restore MySolution.sln (I also verified that the pacakages are getting installed to the user profile .nuget folder)
Step 2. MSBuild MySolution.sln

- dotnet CLI (1.0.0-preview2-003133)
- Aspnet Core targeting  .NET 4.6.2 using Visual Studio 2015 Update 3
- Nuget 3.4
- TeamCity 

Please help. This is a show stopper and I'm nearing a deadline and I've already spent way too much time.

**Comment by Eilon** [comment]
@yishaigalatzer any ideas?

@stanuku there are pre-release builds of NuGet 3.5 at https://dist.nuget.org/index.html, maybe you could try one of those and see if it fixes it?

@pranavkm perhaps you have some idea on this as well?

**Comment by pranavkm** [comment]
Not entirely sure what the cause could be. Could you include the Package Manager output (View -> Output -> Show output from `Package Manager`) when you restore the project?

**Comment by davidfowl** [comment]
@stanuku do you have a repro project.json?

**Comment by stanuku** [comment]
Thanks for your responses.

@Eilon: NuGet 3.5 didn't help.

@pranavkm: As I stated earlier, it builds and runs fine from VS 2015. The issue is on the build server. I actually installed 2015 community edition with update 3 on my build agent. Didn't help.

@davidfowl: Please see the extract from project.json below:

`{
    "title": "xxxxx",
    "copyright": "xxxx",
    "description": "HTTP JSON API services",
    "version": "1.0.0-*",
    "dependencies": {
        "Microsoft.AspNetCore.Mvc": "1.0.1",
        
        "Microsoft.AspNetCore.Routing": "1.0.1",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
        "Microsoft.AspNetCore.Diagnostics": "1.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "EntityFramework": "6.1.3",
        "Ninject": "3.0.1.10",
         
        "Swashbuckle": "6.0.0-beta902",
        "FAKE": "4.41.5"
    },

    "tools": {
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
    },

    "frameworks": {
        "net462": {
            "dependencies": {
                "xx.xx.Data": {
                    "target": "project"
                },
                "xx.xx.Models": {
                    "target": "project"
                },
                "xx.xx.Utils": {
                    "target": "project"
                }                
            }
        }
    },

    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true,
        "xmlDoc": true,
        "optimize": true,
        "define": [ "DEBUG" ]
    },

    "publishOptions": {
        "include": [
            "wwwroot",
            "**/*.cshtml",
            "appsettings.json",
            "web.config"
        ]
    },

    "scripts": {
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    }
}
`

**Comment by yishaigalatzer** [comment]
Can you share the log? What happens when you run restore from the commandline with verbose level of logging?

**Comment by stanuku** [comment]
@yishaigalatzer: The restore is always successful (from VS, from command line, from build agent).

My two build steps again:
1.  `nuget restore MySolution.sln. `
2.  `MSBuild MySolution.sln` 
**Note**: MySolution.sln is a mix of ASP.NET Core and a couple of class libraries targeting 4.6.2.

This below information might be of some help to you folks - 

After further experiments, what I found is that if I run my build steps from command line (which runs under my login identity) on the build agent server all runs fine. However, the same steps when run under the build agent service identity, the MSBuild fails with the previously stated error.

My understanding is that NuGet 3.+ installs/restores the packages to the %userprofile% nuget cache. My build agent runs as "Local System" and so I checked in the profile folder for 'Local System' which is
 `C:\Windows\SysWOW64\config\systemprofile\.nuget\packages` and I see all the packages. So restore definitely is fine.
However, I think MSBuild is having trouble resolving this dependency alone. If you see my project.json, I have other dependencies that are resolved just fine even from the build agent's process. There is something different  with this package 'Microsoft.AspNetCore.Mvc.Formatters.Xml' and also 'AutoMapper' that has the same issue.

Note: I tried both MSBuild (x86 and x64) and restore installs the packages into the SysWOW64 and System32 respectively. The build steps is what fails and only from the agent's process running as Local System.

Thanks for your time and any insights are appreciated. Just some much to deal with when you have an application to deliver.

**Comment by stanuku** [comment]
@davidfowl @pranavkm @Eilon @yishaigalatzer 

I think I solved (work around) the issue. I created a local user account on the build server and set the build agent's service to this user account. The build steps ran fine. So, apparently MSBuild running under 'Local System' has some sort of issue resolving (some of) the dependencies. Which weird because some  dependencies resolve fine.

**Comment by stanuku** [comment]
Closing the issue, turns out when assigning the "Log on as" for the windows service, the "Allow service to interact with desktop" should be checked. That helped resolve the issue. 

Sorry for the confusion.

**Comment by pranavkm** [comment]
@stanuku that's interesting. We just switched our Windows build agents to run as Local Service Accounts and they've been restoring and building AspNetCore repositories just fine. The build agents don't have the interaction checkbox ticked. The one thing we do as part of building on the CI is specify the NUGET_PACKAGES directory to a subdirectory of the working directory (`%workingDir%/.nuget`). Perhaps that too might help resolve this for you.

**Comment by stanuku** [comment]
@pranavkm: I'm not too convinced either with my solution. However, I have other fishes to fry and get back to meeting the deadline...whether I like it or not

**Comment by OutSorcerer** [comment]
@stanuku Another workwaround for this issue is here https://github.com/NuGet/Home/issues/4277.
Also, there is still hope that it will be fixed.
