### ISSUE TITLE
Request to add a RawTagHelper class

### ISSUE THREAD

**Issue by BryanFarrell** [aspnet/Mvc#5459]
With Razor we can do something like this in MVC:
`@Html.Raw("<span>raw markup</span>");`
or
`@Html.Raw($"<span>{ViewData["Title"]}</span>");`

This works great when wanting to add raw markup to a View by accessing some Model data or even inside a Razor `@foreach` loop.

It would be nice to have a RawTagHelper class that would provide similar functionality but for when we want to add raw markup to a view from a static file.  The main use case I have for this is to inject the markup in my SVG image files inline into a View (in my case I use it to inject my site's logo.svg file into my _Layout.cshtml file).

This allows me to keep the SVG file in the images folder and keeps my _Layout.cshtml from getting too cluttered.  It also allows me to remove style declarations from the SVG file itself and apply class names which can then be styled in my site.css file, which gives a huge amount of flexibility.

I was able to implement this RawTagHelper myself and it works perfectly using the following syntax:
`<raw src="images/logo.svg" />`

There is one issue however that I mentioned in [Issue #5453](https://github.com/aspnet/Mvc/issues/5453).  Basically because my TagHelper is not part of the main MVC project the editor tool does not know that my "src" attribute should be handled as local file locations so the context menu to pick from the wwwroot folder does not open up.

My implementation of the RawTagHelper is only 30 lines of code and the only thing that would need to be done to add it to the main MVC repo beyond my code would be to update the HTML schema files the `.cshtml` editor uses and add the `<svg>` element and the `src` attribute to it so the editor would know to display the context menu to select a file from the wwwroot folder.

Doug suggested that I open this request for your team to triage.  Thank you for your time.

Bryan Farrell

**Comment by pranavkm** [comment]
This sounds more like an `IncludeTagHelper` rather than a Raw. `<text>` should act as a direct replacement for `Html.Raw` for most parts.

**Comment by BryanFarrell** [comment]
@pranavkm Yes from a naming standpoint you are probably right that IncludeTagHelper would be a better name for the intended functionality.  My only concern would be to make sure the TagHelper itself does not output any containing html markup (i.e. it literally will replace the tag helper markup with the contents of the file verbatim).

**Comment by Eilon** [comment]
I don't think there's any difference whether this tag helper comes with MVC or not. I don't think there's special logic for the "src" attribute of arbitrary tags. It's just that MVC's build-in tag helpers mostly enhance existing HTML attributes so the HTML editor in VS already knows how to work with those.

@NTaylorMullen can you confirm that?

**Comment by NTaylorMullen** [comment]
Correct, the file picker logic is not based off of where the TagHelper exists; It's something that the editor knows first hand. I filed [this issue](https://github.com/aspnet/Razor/issues/429) a while back to enable the scenario you're asking for.

**Comment by Eilon** [comment]
@NTaylorMullen ah thanks.

@BryanFarrell we don't have plans to add such a tag helper to MVC.

**Comment by BryanFarrell** [comment]
@Eilon That is totally understandable. After hearing how it works in more detail I agree it's not something that needs to be added to MVC directly.  It is nice to see you guys are considering the issue Taylor mentioned as when that is implemented it will provide the functionality I was looking for in the first place. Thanks again to all of you for your quick response to my issue. It's good to see you guys working actively with the community.

**Comment by Eilon** [comment]
@BryanFarrell no problem.
