### ISSUE TITLE
Describe JsonPatch correctly in ApiExplorer

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#5464]
In the JsonFormatter package we need to register an IApiDescriptionProvider that mutates parameters of type `JsonPatchDocument<T>` into being `Operation[]`.

See https://github.com/domaindrivendev/Ahoy/issues/199 for what some current workarounds are. It would be nice if we had this built-in to avoid the need for workarounds.

**Comment by jbagga** [comment]
@rynowak Any thoughts? Should the IApiDescriptionProvider be in the ApiExplorer package or Formatters.Json? The patch needs JsonPatchDocument<T> to be applied, so it should be mutated to Operation[] after that?

**Comment by rynowak** [comment]
We should consider moving the `IApiDescription` and the stuff needed to implement one to abstractions. We should however keep the infrastructure needed to **read** descriptions in core.
