### ISSUE TITLE
Access/render nested html content in ViewComponent when used as TagHelper

### ISSUE THREAD

**Issue by Dona278** [aspnet/Mvc#5465]
TagHelpers offer html nesting:

``` html
<th-form>
    <!-- Username (Another TagHelper) -->
    <th-input type="Text" placeholder="Username" />

    <!-- Password (Another TagHelper) -->
    <th-input type="Password" placeholder="Password" />

    <!-- Submit (Html) -->
    <button>Login</button>
</th-form>
```

Since 1.1.0, we tried to replace some of our TagHelpers with ViewComponents, as they offer a distinct separation between html and C# code. 

However, we noticed that ViewComponents, when used as TagHelpers, don't render child contents.
Is it by design? Is there a way to manually render/access it?

Thank you.

**Comment by NTaylorMullen** [comment]
@Dona278 are you asking is there a way to manually render/access it from a different TagHelper?

**Comment by Dona278** [comment]
@NTaylorMullen I ask if there is a way to use a ViewComponent and being able to access its content from c# code.
In the previous example from "th-form" c# code i can get child content and, for example, wrap into a new html element.
If i convert "th-form" to ViewComponent i get something like:
```html
<vc:form>
<!-- All html content  present here will be removed -->
<span>Test</span>
</vc:form>
```
where the content are removed and there is no way to get them from c# code.
Another example: i have a ViewComponent that renders a container, how can i pass the html content?
With TagHelper i can write:
```html
<th-custom-container>
<span>This is the content</span>
</th-custom-container>
```
And in c# code i can get and re-set the existings content
```csharp
// In this moment, if are present nested tag helper will be compiled
var actualContent = await output.GetChildContentAsync();
// Create a new element
var customContainer = new TagBuilder("div");
customContainer.Attributes.Add("class", "custom-container");
// And set into them the existing content that i got previously
customContainer.InnerHtml.AppendHtml(actualContent);
output.Content.SetHtmlContent(customContainer);
```

Thank you and i hope i was clear

**Comment by NTaylorMullen** [comment]
Ah, with ViewComponents this is not possible. ViewComponents use cases are geared more towards invoking a modular piece of business logic. You can think of being able to invoke ViewComponents as TagHelpers as syntactic sugar that enables nice type checking but nothing more.

For your case I'd recommend writing a vanilla TagHelper.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by shaunluttin** [comment]
Related https://stackoverflow.com/questions/50889261/in-a-view-component-invoked-as-a-tag-helper-how-can-we-access-the-inner-html
