### ISSUE TITLE
Message from field does not show on asp-validation-for

### ISSUE THREAD

**Issue by mdmoura** [aspnet/Mvc#5467]
On an ASP.NET Core 1.0.1 project I have the following on a View:

``` html
    @{
      String message = "This is a error message";
    }

    <form asp-controller="Account" asp-action="SignIn" method="post">
      <input asp-for="Order.Email" type="text" placeholder="Email" />
      <span asp-validation-for="Order.Email" class="error"></span>
      <input asp-for="Order.Password" type="password" placeholder="Password" />
      <span asp-validation-for="Order.Password" class="error"></span>
      <button class="button" type="submit">Entrar</button>
      <span asp-validation-for="@message" class="error"></span>          
    </form>
```

When I submit the form the `asp-validation for` `@message` never shows.

Am I missing something or this might be a bug?

**Comment by dougbu** [comment]
@mdmoura `asp-validation-for` identifies the model property (or more complicated expression) for which error messages should be listed in the `<span>`. It also appears you've already got `<span>`s to contain errors for the properties in your model. Might want a validation summary instead:
``` html
    <button class="button" type="submit">Entrar</button>
    <div asp-validation-summary="All"><h3>@message</h3></div>
</form>
```
(Use `asp-validation-summary="ModelOnly"` if you don't want the `<div>` to repeat messages shown in the `<span>`s.)

**Comment by mdmoura** [comment]
@dougbu I really want the span messages to be displayed. On the controller I am adding the error messages as follows:

      public virtual async Task<ActionResult> SignIn(AccountSignInViewModel.Order order) {
           List<Error> errors = await _validator.ValidateAsync(order);
           if (errors.Any()) {
              ModelState.AddModelErrors(errors, "Order");
              return View(order);
           }           
           // Call services to signin and if Username/Password are wrong add an error with key "Authentication" to ModelState
      }

Then on the view I have:

    @{
      String authentication = ViewContext.ViewData.ModelState["Order.Authentication"]?.Errors?.FirstOrDefault()?.ErrorMessage;
     }

And finally:

    <span asp-validation-for="@Authentication" class="error"></span>

Shouldn't this work?

**NOTE:** Authentication key is not on the model.

**Comment by dougbu** [comment]
`asp-validation-for` takes a portion of a C# lambda expression and supports arbitrary variable names. But the name of the variable is `authentication`. `m => Authentication` isn't valid C#.

Then, `asp-validation-for` itself looks for errors in `ModelState` using the expression name which should be `"authentication"` in this case. The `authentication` variable might as well be set to `42`. Not sure whether `ModelState` contains `"authentication"` keys:
> add an error with key "Authentication" to `ModelState`
> &hellip;
> `ModelState["Order.Authentication"]`

**Comment by mdmoura** [comment]
@dougbu The ModelState does have an error with key "Order:Authentication" as in the view I am doing

    @{
      String Authentication =   ViewContext.ViewData.ModelState["Order.Authentication"]?.Errors?.FirstOrDefault()?.ErrorMessage;
     }

and I checked that Authentication is not empty so shoudn't asp-validation-for="@Authentication" show the message since it is an in-scope variable?

**Comment by Eilon** [comment]
@mdmoura you don't need to store the message in your own variable - that's what the HTML helper does automatically. The HTML helper automatically looks up the value in Model State and shows the message if the field is invalid.

Your C# code *is* in fact valid (`m => Authentication` is 100% valid C#), but it's not necessary and doesn't work well with HTML helpers because the HTML helpers *parse* that expression to figure out what to read from model state.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
