### ISSUE TITLE
Question/Suggestion: Javascript taghelper for @model

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#5474]
Right now, to get the model in a JSON one uses Newtonsoft.Serialize on the view.
For security reasons it's better to place it on a html tag and then access it via data attributes from js.

So I have a question/suggestion thing.

Is it possible to have a "secure, properly encoded" tag helper `<script asp-model="variableName">console.log(variableName)</script>` that renders something like:

```html
<script>
var variableName = // ..... serialized and properly escaped @Model data .... //
console.log(variableName) // ... here the extra content.
</script>
```` 

If that can be done, wouldn't it be great to have it built in on the frameworks taghelpers? I would love to know your thoughts on this, and if there's interest I can contribute with an implementation.

**Comment by danroth27** [comment]
@DamianEdwards 

> For security reasons it's better to place it on a html tag and then access it via data attributes from js.

@Bartmax Could you please clarify how you would access this data from "data attributes"?

**Comment by frankabbruzzese** [comment]
Something like :
```
<script type = "text/json" id="id based on asp-for+"_json"">
//Json content
</script>
```

it's safe because it is not executed because of the custom type. Moreover it doesn't create JavaScript vars in global scope. Json may be acessed via id, and parsed to get a JavaAcript object.
It is easy to create it also without any TagHelper.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
