### ISSUE TITLE
Remove PageDirectiveFeature once we have switched to Razevolution

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#5475]
Followup work item based on discussion on https://github.com/aspnet/Mvc/pull/5450#discussion_r85364322

**Comment by Eilon** [comment]
@pranavkm - is this work done?

**Comment by pranavkm** [comment]
We have the type, but we removed all of the parsing from it. So should be good to close.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/20c04d099e7fad844ad5617a0652ee06e22fa9c3
