### ISSUE TITLE
ModelBinder won't bind  checkbox group value to  a array string

### ISSUE THREAD

**Issue by John0King** [aspnet/Mvc#5486]
MVC version: 1.0.1
```C#
//  form post :  v=A&v=B&v=C
[HttpPost]
public IActionResutl SomeAction(string options)
{
    // opions  = "A";
     string options2 = Request.Form["options"]; // options2 = "A,B,C"
}
```
The `ModelBinder ` 's  behavior  is  totally different  than `Request.Form/Query`

Another thing I noticed  is that   you can not use `Request.Form` in a GET Request .

**Comment by dougbu** [comment]
If you want to bind all submitted options, use `public IActionResutl SomeAction(string[] options) { // ... }`. MVC consistently binds all submitted values to a collection and the first of them to a non-collection property.

**Comment by John0King** [comment]
what's the reason only give the first value to non-collection property ?
notice: EF does not support array . 
so  how to do this ?
