### ISSUE TITLE
Remove multiple InternalsVisibleTo in Microsoft.AspNetCore.Mvc.Core and .ViewFeatures 

### ISSUE THREAD

**Issue by jbagga** [aspnet/Mvc#5494]
There are IVTs to multiple test assemblies in the runtime assemblies, Microsoft.AspNetCore.Mvc.Core and Microsoft.AspNetCore.Mvc.ViewFeatures. Ideally, the only IVT should be to the runtime assembly's corresponding test assembly.

See https://github.com/aspnet/Mvc/pull/5469#discussion_r85625384 by @Eilon in [this PR](https://github.com/aspnet/Mvc/pull/5469)

**Comment by rynowak** [comment]
@ryanbrandenburg - please try and remove the offensive attributes, and see what breaks and report back if it's not easily fixable.

**Comment by ryanbrandenburg** [comment]
There's only one of these left. There are a lot of "DynamicProxyGenAssembly2"'s left but it seems those allow mocking internals.

**Comment by Eilon** [comment]
Yeah the dynamic proxy stuff is all for Moq, which is just for testing, so those are fine.
