### ISSUE TITLE
DisplayAttribute dont work with <label asp-for="">

### ISSUE THREAD

**Issue by jacobmohl** [aspnet/Mvc#5506]
It seems that on 1.1-preview1 that model properties decorated with `[DisplayAttribute(Name="Something")]` dont get the name value populated when using `<label asp-for="">`-tags in views.

This also seems to be the case with `[Required(ErrorMessage = "Something")]` and `<span asp-validation-for="">`-tags.

**Comment by dougbu** [comment]
I have not been able to reproduce this issue.

Please provide a repro, preferably as a relatively small project hosted in a public GitHub repo. A set of detailed steps to reproduce the issue is a reasonable fallback.

**Comment by jacobmohl** [comment]
The bug is also gone when updating to latest 1.1 version in my repo.

**Comment by dougbu** [comment]
Missed your comment @jacobmohl Glad the problem doesn't exist in the final 1.1 release.
