### ISSUE TITLE
Question: Best way to export large csv file

### ISSUE THREAD

**Issue by wjzhou** [aspnet/Mvc#5509]
Our application need to export csvs that are about 10MB. What will be the best way to export this?

If I understand it right, the byte[] or MemoryStream way will allocate the memory on the LOH.

In the old days (Mvc 4.5), I inherit the FileResult and override its WriteFile method. 
For now, I have to implement my own FileDelegateResult which inherits ActionResult and duplicates the code for setting SetHttpFileName and ContentType.

Is there a better built-in way of handling this?

Thank you.

**Comment by Eilon** [comment]
There are file result types that do this for you:

* https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/VirtualFileResult.cs
* https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/PhysicalFileResult.cs

They will both set the content disposition header, etc., so long as they have the data passed into them.
