### ISSUE TITLE
CookieTempDataProvider hard codes cookie to be secure-only, thus requiring HTTPS to function

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#5511]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/CookieTempDataProvider.cs#L69

The cookie should only be marked secure if the incoming request is itself HTTPS. As it stands, this feature cannot be used unless the site is protected with HTTPS.

**Comment by kichalla** [comment]
07a2f1de06282a3a83ab578e815e7d2428e29e01
