### ISSUE TITLE
Spacing breaks Tag Helper in Visual Studio Code on Mac OS and Windows 10

### ISSUE THREAD

**Issue by Ponant** [aspnet/Mvc#5514]
The following bug does not occur in visual studio community. It occurs in Visual Studio Code, on a Mac and Windows 10.

1) `dotnet new -t web` . Same issue with yeoman. Restore, build and run

2) Got to the about page and paste in the About.cshtml the following code:
```
 <div>
 <a asp-controller ="Home" asp-action ="Index"> Go back home does not work</a>
</div>
 <div>
 <a asp-controller ="Home" asp-action="Index"> Go back home works</a> 
 </div> 
```

The first link does not work, the second one does. The difference is subtle: It is the space between asp-action and the equal sign. If this space exists, the hyperlink is ignored, otherwise it works. The DOM explorer in the browser shows that the first hyperlink is copied as is albeit removing the spacing:
`<a asp-action="Index" asp-controller="Home">Go back home does not work</a>`
whereas the second one is properly transformed,
`<a href="/">Go back home works</a>`

**Comment by NTaylorMullen** [comment]
This is working as intended. It's against the HTML5 spec to have spaces after an attribute name and before an equals. If you do have the space after the attribute name then the attribute is handled as minimized.

**Comment by Ponant** [comment]
I would agree if all attribute follow this rule, but it does not seem to.
This would work for instance
`<a asp-controller="Home" asp-action ="Index">Go back home does not work</a>`
because the space has been removed not from the action but from the controller.

**Comment by NTaylorMullen** [comment]
@Ponant the reason why that one works is because you still have one valid attribute `asp-controller="Home"`. The existence of that attribute lights up the TagHelper.
