### ISSUE TITLE
Add MVC services builder for CookieTempDataProvider

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#5515]
Need to add a builder for adding `CookieTempDataProvider` services (w/ overload for options).

That is, make this line of code simpler: https://github.com/aspnet/Mvc/blob/89bd6dc1cd188772f9b85eb75ec0d79506a3bf2f/test/WebSites/BasicWebSite/StartupWithCookieTempDataProvider.cs#L15

cc @DamianEdwards @kichalla

**Comment by dougbu** [comment]
6d43612
