### ISSUE TITLE
Visual Studio can not resolve the dependency library which i built on my own

### ISSUE THREAD

**Issue by v-zhidu** [aspnet/Mvc#5524]
I built a .net core library based on net45 and netstandard1.3, when I reference this library in my ASP.NET Core MVC site like this
![image](https://cloud.githubusercontent.com/assets/8225531/20124578/668d7adc-a662-11e6-87dd-4629dfa48fca.png)

The Visual Studio 2015 cannot resolve this packge as a dependency, when i call the methods which in library, vs display red font, intelli sense doesn't work well, but compiler succeed.

![test](https://cloud.githubusercontent.com/assets/8225531/20125025/ceb53160-a665-11e6-9de6-c54a7b137e0a.png)

**Comment by Eilon** [comment]
@v-zhidu can you upload your project to GitHub so we can take a look? Or create a simplified repro project that we can take a look at?

@pranavkm thoughts on what might be going on here?

**Comment by pranavkm** [comment]
Doesn't look like the dependency is restored. @v-zhidu can you expand the references node in your project - that should say if there are restore errors. Additionally, when specifying `target: "project"`, the version node isn't required.

**Comment by davidfowl** [comment]
Looks like resharper. Update to the latest resharper and try again.
