### ISSUE TITLE
Model binders get incorrect `FieldName` when binding a collection element

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5526]
`modelBindingContext.FieldName` has unexpected values in `IModelBinder` implementations handling collection elements. This issue has no impact in an MVC application with a default configuration because only `BodyModelBinder` and `HeaderModelBinder` use `FieldName`. `BodyModelBinder` uses `FieldName` only when binding a top-level value and both binders require unusual customization (e.g. a custom `IBindingSourceMetadata` attribute on an element type) before they're used for elements.

Inside most collections, `FieldName` is the index and not the actual name e.g. `"2"` instead of `"[2]"`. Inside a dictionary when the submission used `dictionary[name]=value`, `FieldName` is unchanged from the parent scope e.g. `"dictionary"` instead of `"[name]"` (or `"name"` which would at least be consistent with other element binding).

Suggest updating the `EnterNestedScope()` calls in `CollectionModelBinder.BindComplexCollectionFromIndexes()` and `DictionaryModelBinder.BindModelAsync()` to correct the `fieldName` argument values.

----

Noticed while experimenting for PR #5495 on issue #4362. See https://github.com/dougbu/FieldName for a repro project.

**Comment by Eilon** [comment]
Closing because we have not seen other reports of this.
