### ISSUE TITLE
Display Name Encoding 

### ISSUE THREAD

**Issue by audacity76** [aspnet/Mvc#5529]
I want to use soft hypens in the display name but the data annotation get's completely encoded when used as label:

```
[Display(Name = "Prob&shy;lem")]
public bool Problem { get; set; }
```

`<label asp-for="Problem"></label>`

Output is:
`Prob&shy;lem` because it is is encoded as `Prob&amp;shy;lem`

Is there a trick to get soft hypens working?

**Comment by dougbu** [comment]
@audacity76 use the soft hyphen character rather than the HTML entity:
``` c#
[Display(Name = "Prob\u00ADlem")]
```

**Comment by audacity76** [comment]
@dougbu thanks
