### ISSUE TITLE
'[FromHeader] string Referer' doesn't works in 1.1.0-preview1-final

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Mvc#5531]
@Eilon 
`[FromHeader] string Referer` doesn't work in `1.1.0-preview1-final`
It always returns `null` value.

**Comment by dougbu** [comment]
@Kagamine did you resolve your issue? If so, congratulations.

If for example you made a mistake in your application, the details might help. Please let us know if something was hard to use, undocumented or confusing.

**Comment by Kagamine** [comment]
Sorry, It is not a bug, this issue has been opened by mistake.
