### ISSUE TITLE
Published get BadImageFormatException after upgrade to dot net core 1.1

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Mvc#5542]
It works fine on my developer machine but not when I published to IIS

![image](https://cloud.githubusercontent.com/assets/12871379/20405886/644ba3fc-ad0b-11e6-8ac8-4b69ca15cb48.png)

Windows Server 2012 R2 x64

I can't find dot net core 1.1 Windows Server Hosting runtime, I install Windows x64 runtime
https://www.microsoft.com/net/download/core

```
app.UseResponseCaching();
app.UseMvc(routes =>
{
              

});
app.UseCookieAuthentication(new CookieAuthenticationOptions()
{
              
}
           
```

Between these 3 middle ware is the cause of BadImageFormatException

**Comment by andrew-vandenbrink** [comment]
The problem on UseMvc, is it because I install wrong runtime?

**Comment by Eilon** [comment]
cc @muratg regarding the server hosting installer for Windows.

**Comment by muratg** [comment]
@andrew-vandenbrink You can install Windows Server Hosting bundle from this link: https://aka.ms/dotnetcore_windowshosting_1_1_0. 

(We'll get the downloads page updated with this link as well)

**Comment by Eilon** [comment]
@andrew-vandenbrink once you install the 1.1.0 bundle, can you let us know if you still have the issue? If so, can you upload your project to GitHub so we can take a look? And let us know which version of `dotnet` you're using? (Run `dotnet --version` from the command line.)

**Comment by pranavkm** [comment]
The stack trace is coming from the `ViewsFeatureProvider`: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/ViewsFeatureProvider.cs#L74. Do you have an assembly named `AppName.PrecompiledViews.dll` in your application graph? 

That said, we should possibly ignore more kinds of exceptions here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/ViewsFeatureProvider.cs#L76. Clearly `FileLoadException` isn't sufficient.

**Comment by andrew-vandenbrink** [comment]
@Eilon @muratg I will get back as soon as I have access to my vm... (14 hours++ from now...)

@pranavkm I do have
![image](https://cloud.githubusercontent.com/assets/12871379/20420354/73c283bc-ad5d-11e6-990f-37f687fc9752.png)

**Comment by pranavkm** [comment]
Are you using Razor view compilation? It's odd that it's 0-byte binary.

**Comment by andrew-vandenbrink** [comment]
I still have same issue after installing Windows Server Hosting.

I delete that 0-byte binary and it works!
I still have issue with razor precompile https://github.com/aspnet/Mvc/issues/5546

If it fails to compile, don't generate x.PrecompiledViews.dll
but the issue still BadImageFormatException? which means even if its successfully compiled, I still get issue.

**Comment by pranavkm** [comment]
@andrew-vandenbrink I filed a bug here - https://github.com/aspnet/MvcPrecompilation/issues/35 - to track the issue with 0-byte file. 

The tool returns a non-zero exit code, however, https://github.com/dotnet/cli/issues/2836 prevents it from doing anything pertinent with it. Perhaps you could look at wrapping the tool execution and deleting the precompiled file on a non-zero exit code. I admit it's not ideal, but it should prevent you from having to look at the logs to discover a build failure.

**Comment by andrew-vandenbrink** [comment]
Thanks I will close this issue
