### ISSUE TITLE
Model binding Route and Body into same object

### ISSUE THREAD

**Issue by kjbetz** [aspnet/Mvc#5543]
I would like parameters to model bind to the same object from both the Route and Body.  Example:
```C#
[Route("[controller]")]
public class FoosController
{
    [Route("{id}"]
    [HttpPut]
    public IActionResult Create(Foo foo)
    {
        Foo newFoo EditFoo(foo);
        return new ObjectResult(newFoo);
    }

    public class Foo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
```

And then send the following to `PUT /foos/5`
```json
{
    "name": "Robots",
    "description": "Toy robots for sell in this example."
}
```

And the model to be populated as such:
```C#
foo.Id = 5,
foo.Name = "Robots",
foo.Description = "Toy robots for sell in this example."
```

I've researched and understand that once `[FromBody]` is put into the action method all other binding is not done as it is a separate thing. That being sent off to the de-serializer and bound there.

Is there a way to tap into this? Or have an ActionFilter that will then run the RouteBinding on it too?

Or... can we have definitions like this:
```C#
public class foo
{
    [FromRoute]
    public int Id { get; set; }
    
    public string Name { get; set; }
    public string Description { get; set; }
}
```

Then set up the action to be `public IActionResult Edit([FromBody]Foo foo)` but then anything with a `[FromRoute]` would try to bind that way?

**Comment by kjbetz** [comment]
The main reason I'm asking is because I've set up model validation as an ActionFilter which is occuring right after model binding. So doing this:

```C#
[HttpPut("{id}"]
public IActionResult Edit(int id, [FromBody]Foo foo)
{
    foo.Id = id;
    EditFoo(foo);
}
```
This is giving me model validation errors because when my foo gets validated it still doesn't have the Id set yet.

**Comment by Eilon** [comment]
@dougbu ?

**Comment by dougbu** [comment]
@kjbetz model binding attributes with a type bound using `[FromBody]` are ignored. I haven't tried it but the following should do the trick as long as you adjust your validation to match.
``` c#
public class foo
{
    [FromRoute]
    public int Id { get; set; }

    [FromBody]
    public Bar Bar { get; set; }
}

public class Bar
{
    public string Name { get; set; }
    public string Description { get; set; }
}
```

> I've set up model validation as an ActionFilter which is occurring right after model binding.

Separately, MVC's build in validation runs right after model binding. What do did you mean here? Is this a separate type of validation? (If so, you might consider `foo` implementing `IValidatableObject` instead. Might be a bit more straightforward.)

**Comment by kjbetz** [comment]
@dougbu Yes! Thank you!

> Separately, MVC's build in validation runs right after model binding. What do did you mean here? Is this a separate type of validation? (If so, you might consider foo implementing IValidatableObject instead. Might be a bit more straightforward.)

I was getting things mixed up. I am using MVC's built in model validation (well actually FluentValidation -- but it's tapped into MVC's default.) I have an ActionFilter to automatically do the checks if model was valid.

But, this works. I know have some models set up like this

```C#
public class Foo
{
    [FromRoute]
    public int Id { get; set; }

    [FromBody]
    public FooBody Body { get; set; }
}

public class FooBody
{
    public string Name { get; set; }
    public string Description { get; set; }
}
```

Then my controller just looks like this:
```C#
[HttpPut("{id}")]
public IActionResult Edit(Foo foo)
{
    // do stuff
    return Ok();
}
```

I send this json in the body to `PUT /foos/5`
```json
{
    "name": "foo name",
    "description": "foo description"
}
```
And I can now access all things like this:
```C#
foo.Id = 5,
foo.Body.Name = "foo name",
foo.Body.Description = "foo description"
```

And it's being validated correctly, etc...

Thank you!

**Comment by dougbu** [comment]
Glad everything works for you now.
