### ISSUE TITLE
Dot net core publishing failed with NetStandardLibrary

### ISSUE THREAD

**Issue by deepumi** [aspnet/Mvc#5545]
**IDE** - Microsoft Visual Studio Community 2017 RC
**Version** - 15.0.25914.0 D15REL
**Microsoft .NET Framework** - Version 4.6.01586

1) Create new .Net Core project and select Asp.Net Web API project template.
2) Add new project NetStandard class library named (NetStandardDemoLib)
3) Add NetStandard class library as project reference to Asp.Net Web API project
4) Build successfully, browse the API project  and debugging to netstandard library works fine
6) Publish to file system, got the following following error

**"The type or namespace name 'NetStandardDemoLib' could not be found (are you missing a using directive or an assembly reference?)"**

**Comment by Eilon** [comment]
@moozzyk can you take a look?

**Comment by moozzyk** [comment]
I was able to repro this. Seems like a VS 2017 RC issue where publish will not handle project references correctly. When I try to publish from VS 2017 RC I get: 
![image](https://cloud.githubusercontent.com/assets/1438884/20495206/f23a742e-afd4-11e6-8da9-3b98c2a7f1c3.png)
even though the application by itself builds and runs just fine. 
I tried publishing the app from command line with: `dotnet publish WebApplication1.csproj -o \temp\WebApplication1` and it worked just fine. 

/cc @vijayrkn

**Comment by deepumi** [comment]
@Eilon @moozzyk @vijayrkn 

Finally, I made it work. 

1) Remove the reference
2) Add reference again
3) Published successfully

**Comment by deepumi** [comment]
@Eilon @moozzyk @vijayrkn

Not sure this is also a known issue, 

1) Install a nuget package (ex: System.Data.Common 4.3.0 or System.Data.SqlClient 4.3.0)
2) Package installed successfully.
3) No intellisense or code completion. (I've tried adding namespace does not work and got build error [namespace does not exist]).
4) Close solution and re-open the project works fine.

NOTE : Project type is **.xproj**

**Comment by Eilon** [comment]
@vijayrkn any idea where this issue should go? Can you verify if this is an issue in VS2017 RC?

**Comment by davidfowl** [comment]
@deepumi are you sure it's xproj? It's not vs2017 is it? Because there are known issues with vs2017 rc but that does not have support xproj

**Comment by deepumi** [comment]
@davidfowl my bad :( it is csproj and VS 2017.

I have updated my above comment project type.

**Comment by davidfowl** [comment]
@deepumi https://github.com/dotnet/roslyn-project-system/issues/785

**Comment by Eilon** [comment]
@davidfowl is it safe to close this issue then?

**Comment by deepumi** [comment]
@davidflow thank you.
