### ISSUE TITLE
Areas routing 

### ISSUE THREAD

**Issue by pushist1y** [aspnet/Mvc#5548]
I'm trying to implement in single project MVC-architecture for user views and Webapi-backend which will be used by views. I want to use same names for controllers for mvc and webapi (i.e. UsersController). I'm trying to use Areas concept to distinguish them in the routing stage.

Currently i've defined routing as following:
```c#
.UseMvc(routes =>
            {
                routes.MapAreaRoute("api_route", "Api", "api/{controller}/{id?}");
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
```

The user-views should be accessible via default route and the api controllers should be accessible via api route.

I have an api controller marked with [Area("Api")] and the views controller unmarked.

Url "/users" resolves correctly to the views-controller. But url "/api/users" doesn't get resolved at all and return 404 error. I have implemented an [example](https://github.com/pushist1y/ErrorReproductions/tree/master/AreaRouting)

I can't figure out what should i do for the url to resolve to the right controller.

**Comment by Muchiachio** [comment]
You area template is missing an action, without an action routing doesn't know which action it should run on the mapped api users controller. Here's an example of working route map.
```C#
routes.MapAreaRoute("api_route", "Api", "api/{controller}/{action=Index}/{id?}");
routes.MapRoute(
    name: "default",
    template: "{controller=Home}/{action=Index}/{id?}");
```

**Comment by pushist1y** [comment]
@Muchiachio 
it's Api controller, it should determine correct action by used http method. I.e. if i add `[Route("/api/[controller]")]` to the api controller it resolves correctly with url "api/users" to the `Index()` action

**Comment by Muchiachio** [comment]
Well yes, but how does it know that it's a web api controller?
`[Route("/api/[controller]")]` maps to best candidate which in your case is an index action, if you would add another action to that controller you will get ambiguous action exception.

And I'm not too sure if routing looks at http method being used.

**Comment by pushist1y** [comment]
@Muchiachio 
> maps to best candidate which in your case is an index action, if you would add another action to that controller you will get ambiguous action exception

Yes, it's ok for REST-controllers as they don't have ambiguous methods, methods are distinguished by http-method. In my main app it works. But currently i have api-controllers definitions like that:
`[Route("api/users")]
public class UsersApiController : Controller`

I'd like to keep original controller names (like `UsersController`) and keep global routing pattern (not adding custom routing attribute to every api controller). I wanted to achieve that with Areas but can't make them find proper controller.

**Comment by Eilon** [comment]
@rynowak thoughts on how to handle this?

**Comment by rynowak** [comment]
The best way to handle something like this is to write a convention. [Sample here](https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRoutingConvention)

Please open issues with more specific questions if you get stuck.
