### ISSUE TITLE
Posting large JSON to Controller fails silently

### ISSUE THREAD

**Issue by webprofusion-chrisc** [aspnet/Mvc#5551]
When posting a large JSON file (several MB) to a Microsoft.AspNetCore.Mvc.Controller method, where the method is marked with [HttpPost] the Http Result is 404. Posting a smaller JSON file to the same method works as expected. A descriptive diagnostic message would have saved me a lot of time, but I expect at least this should be returning a different Http Status Code.

Windows 10
VS 2017 RC
.net core 1.1

**Comment by DamianEdwards** [comment]
Can you provide a minimal repro example please? e.g. the code of your `Progam.cs`, `Startup.cs` & controller class, along with the JSON file your posting. Thanks.

**Comment by webprofusion-chrisc** [comment]
Thanks Damian. It's all pretty generic I think:

Program.cs:
```
var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
```

Startup.cs:
```
 public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            if (env.IsEnvironment("Development"))
            {
                // This will push telemetry data through Application Insights pipeline faster, allowing you to view results immediately.
                builder.AddApplicationInsightsSettings(developerMode: true);
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddApplicationInsightsTelemetry(Configuration);

            services.AddMvc();
            services.AddMemoryCache();
     

            services.AddCors(options =>
            {
                options.AddPolicy("AllowAnyOrigin",
                    builder => builder
                    .AllowAnyOrigin()
                    .AllowAnyMethod().AllowAnyHeader().AllowCredentials()
                    );
            });
            services.Configure<MvcOptions>(options =>
            {
                var cors = new CorsAuthorizationFilterFactory("AllowAnyOrigin");
               

                options.Filters.Add(cors);
               
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseApplicationInsightsRequestTelemetry();

            app.UseApplicationInsightsExceptionTelemetry();

            app.UseMvc();

        }
    }
```

Method from controller:
 ```
 [HttpPost]
        [Route("savedesigns")]
        public IActionResult SaveUserDesigns([FromBody] dynamic val)
        {
            return new OkObjectResult(val);
        }
```

Unfortunately I can't provide the JSON in this case, but this one happens to be about 5MB (have now obviously reverted to using smaller chunks of JSON).

**Comment by rynowak** [comment]
Have you looked at the logging output (it should show up in the output window in VS) or will print to the console if you do a `dotnet run`. There should be some information there from routing

**Comment by webprofusion-chrisc** [comment]
@rynowak thanks I'll try and capture an output later. The only notable thing was that as CORS is enabled it tries OPTIONS first and complains the the authorization filter failed (I don't have a special authorization filter but I am posting with and Authorization header and CORS is enabled) but a status code of 200 was returned anyway. Then the POST gets performed by the browser and it simply 404's (nothing in console, almost as if it did nothing).

**Comment by Eilon** [comment]
@jbagga another one for you to investigate.

**Comment by jbagga** [comment]
@webprofusion-chrisc Are you still running into this error? Have you ensured that the request contains the `Content-Type: application/json` header? I tried to run the code you shared. It seems to work just fine for a 5MB json file. Any other relevant information that can help us investigate further?

**Comment by webprofusion-chrisc** [comment]
@jbagga Sorry I haven't been able to recreate this since, it could have been that the file was much bigger than 5MB (the client side app was posting generated images, so 18MB for instance). Feel free to close this though as I cannot reproduce any more, could have been experimental error :)

**Comment by jbagga** [comment]
@webprofusion-chrisc Thank you for getting back to us! Closing this issue as it cannot be reproduced again. I have ensured it works for files up to 20 MB for VS 2015 .NET Core 1.0 and VS 2017 .NET Core 1.1 with the code shared.
