### ISSUE TITLE
Add the RegisterAdapter method to the IValidationAttributeProvider

### ISSUE THREAD

**Issue by MissaouiChedy** [aspnet/Mvc#5553]
# Context
The `IValidationAttributeAdapterProvider` interface represents a contract for a factory class that creates `IAttributeAdapter` instances corresponding to the provided validation attribute. This instantiation is achieved by the `IValidationAttributeAdapterProvider.GetAttributeAdapter(ValidationAttribute attribute, IStringLocalizer stringLocalizer)` method.

# Pain point
The default validation adapter provider: `ValidationAttributeAdapterProvider` available under the `Microsoft.AspNetCore.Mvc.DataAnnotations.Internal` namespace does not provide a way to register custom validation adapters (created by the developer). Furthermore it seems that the creation of adapters for the default validation attributes (such as Required and RegularExpression) is some what "hard coded" under the `ValidationAttributeAdapterProvider.GetAttributeAdapter` method.

According to the following [stack-overflow answer](http://stackoverflow.com/a/40621690/1182189), the only way to use custom validation adapters is to:

1.  Create a custom validation attribute adapter provider that take into account the custom adapters
2.  Add the custom validation attribute provider as a service under `Startup.ConfigureServices` 

# Proposal
Add a `RegisterAdapter<TValidationAttribute>(Func<ValidationAttribute, IAttributeAdapter>adapterFactoryMethod)` to the `IValidationAttributeAdapterProvider` interface.

This method would allow the developer to provide a factory method that will produce the custom `IAttributeAdapter` for the `ValidationAttribute` type that is supplied through the generic argument.

The developer would typically call the `RegisterAdapter` method from `Startup.Configure`. This would prevent the hassle of creating a custom `IValidationAttributeAdapterProvider`.

**Comment by dougbu** [comment]
Replacing the default `IValidationAttributeAdapterProvider` is one way to add adapters for custom validation attributes. That approach is also the only one available if you want to replace the default adapters. But what is the use case for such a replacement?

For custom `ValidationAttribute`s, adapters aren't mandatory. You could also implement `IClientModelValidator` in the custom attribute itself. (Server-side adapters focus on localized strings for error messages and custom attributes can handle that without implementing an additional interface.) This is the approach [`[Remote]`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/RemoteAttribute.cs) (in MVC) and [`[SelfContainedValidation]`](https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.LocalizationSample.Web/SelfContainedValidationAttribute.cs) (in Entropy) use. Does this approach work in your scenario?

**Comment by MissaouiChedy** [comment]
The intent behind creating validation adapters for custom validation attributes is to avoid implementing the `IClientModelValidator` directly in the custom validation attribute when it is required to keep custom validation attributes in the domain model layer.

Usually the domain model layer is isolated in a separate project that has very minimal external dependencies and especially no Web UI Layer dependency.

Since `IClientModelValidator` is part of the ASP.NET Core framework it is preferable to avoid implementing the interface directly in the domain layer. I believe that using the validation attribute adapter facility is an good approach that will help to:

- Keep custom validation attributes in the domain layer
- Add client side specific validation attribute in the web app layer when needed

**Comment by dougbu** [comment]
> Since `IClientModelValidator` is part of the ASP.NET Core framework it is preferable to avoid implementing the interface directly in the domain layer.

:ok: your layering point makes sense. Our reason for the adapters was somewhat similar: We don't own the `ValidationAttribute`s in `System.ComponentModel.DataAnnotations`.

Going back to your original request:
> `ValidationAttributeAdapterProvider` available under the `Microsoft.AspNetCore.Mvc.DataAnnotations.Internal` namespace

The namespace choice was deliberate. We focused on solving a specific implementation issue and not extensibility. But moving it into a public namespace has come up before e.g. in #2503.

> Add a `RegisterAdapter<TValidationAttribute>(Func<ValidationAttribute, IAttributeAdapter>adapterFactoryMethod)`

This would be a significant breaking change, not possible before 2.0. To provide extensibility in this area, we should step back and design something more flexible and less complicated. E.g. the current approach leads to `IAttributeAdapter` implementations that are almost-always tightly coupled to the `ValidationAttribute`s they handle.

One alternative I should have mentioned above: Create an `IValidationMetadataProvider` implementation that adds `IModelValidator` and / or `IClientModelValidator` implementations to `context.ValidationMetadata.ValidatorMetadata` for each custom `ValidationAttribute`. Add an instance to `MvcOptions.ModelMetadataDetailsProviders`. This doesn't avoid the coupling issue I mentioned but does use a fully-supported extensibility point.

**Comment by frankabbruzzese** [comment]
@MissaouiChedy ,
Creating an `IValidationMetadataProvider ` implementation is less painfull that i might appear. It is enough your custom implementation creates an instance of the `IValidationMetadataProvider ` default implementation. This way your implementation just checks your custom attributes and then calls back the original implementation.

In your custom implementation you might add a RegisterAdapter method, so you have your extension point, or better you might create an interface that inherits from `IValidationMetadataProvider `  and adds the RegisterAdapter method and then you might implement this interface as I suggested.

I suggest implementing `IValidationMetadataProvider ` instead of implementing directly `IClientModelValidator ` norwithstanding `IClientModelValidator ` implementations may be easily added to an already existing extension point . This way you may take advantage of all ValidationAttributes specific code and optimizations that exists NOW and that will be implemented in the FUTURE.

**Comment by MissaouiChedy** [comment]
Thank you @dougbu and @frankabbruzzese for pointing out the `IValidationMetadataProvider` lead, I tried it, it works and I believe as you guys mentioned it is better supported than the `IAttributeAdapter` solution.

But like the `IAttributeAdapter` solution it requires creating and registering the implementation of an interface to get the html validation attributes associated with the custom `ValidationAttribute`s.

The aim of the proposal is to allow the developer to exactly:
1 - Create a `IClientModelValidator` for the custom `ValidationAttribute`
2 - Register the `IClientModelValidator` to `ValidationAttribute` mapping somewhere in `Startup.cs`

After what we discussed so far I would like to change the proposal :

Create a `ClientSideValidationMetadataProvider` class as part of the framework, this class implements IValidationMetadataProvider and exposes the `RegisterClientSideValidator<TValidationAttribute>(Func<ValidationAttribute, IAttributeAdapter>adapterFactoryMethod)` method.

The developer that wishes to a map custom `IClientModelValidator`s and `ValidationAttribute`s can use this class in `Startup.ConfigureServices` for example as follows:
```
services.AddMvc( MvcOptions => {
          var provider = new ClientSideValidationMetadataProvider();
          provider.RegisterClientSideValidator<CustomValidationAttribute>((attribute) => (
                   new CustomClientModelValidator(attribute)
               )  
          );
          MvcOptions.ModelMetadataDetailsProviders.Add(new ClientSideValidationMetadataProvider());
});
```
If this proposal makes sense I will be glad to contribute.

**Comment by dougbu** [comment]
@MissaouiChedy what you propose is workable but I'm not sure why it's necessary. Please clarify your objection to implementing `IValidationMetadataProvider`.

**Comment by frankabbruzzese** [comment]
@dougbu 
The same `IValidationAttributeAdapterProvider` would be easier to extend if the DI engine would have
something like:
`
services.ExtendSingleton<T>(Func<T, T> x)
`
That replace the current implementation of T with the instance returned by the factory function, that, in turn, receives  the current implementation as its unique argument.

This way, dlls, and/or Nuget packages might extend a service without removing extensions performed by other packages.

**Comment by frankabbruzzese** [comment]
@dougbu 
The same `IValidationAttributeAdapterProvider `would be easier to extend if the DI engine would have
something like:

`services.ExtendSingleton<T>(Func<T, T> x)`

That replaces the current implementation of T with the instance returned by the factory function, that, in turn, receives the current implementation (ie the implementation before the modification) as its unique argument.

This way, dlls, and/or Nuget packages might extend a service without removing extensions performed by other packages.

**Comment by MissaouiChedy** [comment]
@dougbu what I suggest is not necessary, in my opinion it will just make associating IClientModelValidator implementations with custom validation attributes more convenient for developers.

Keep in mind that currently the developer that wishes to keep his custom validation attribute independent of the IClientModelValidator interface will have to:
1 - Create an `IClientModelValidator` for the custom `ValidationAttribute`
2 - Implement a custom `IValidationMetadataProvider`
3 - Register the custom `IValidationMetadataProvider` under `Startup.ConfigureServices`

What I propose aims to avoid step 2, avoiding step 2 would obviously decrease the amount of work needed. This however raises a couple of questions.

Is the amount of work (in step 2) consequent enough that it makes it worth to introduce this proposal ? 
Is there as well a consequent portion of ASP.NET Core developers that will benefit from this proposal?

I personally have no idea.
@dougbu I would like to know what is your take on the above questions.

**Comment by dougbu** [comment]
My opinion (just an opinion) is a custom `IValidationMetadataProvider` for this purpose would be quite straightforward. Step 3 is also mostly boilerplate e.g.
``` c#
services.AddMvc(options => options.ModelMetadataDetailsProviders.Add(new Provider(...)));
```

**Comment by MissaouiChedy** [comment]
@dougbu 
> a custom IValidationMetadataProvider for this purpose would be quite straightforward.

Do you mean straightforward to implement ?

> Step 3 is also mostly boilerplate

We can add a `ClientSideValidationMetadataProvider` property under `MvcOptions` that would be initialized by default and then it would be possible to call `RegisterClientSideValidator` directly on it, for example:

```
services.AddMvc( options => {
       MvcOptions.ClientSideValidationMetadataProvider
       .RegisterClientSideValidator<CustomValidationAttribute>(
                 (attribute) => (
                         new CustomClientModelValidator(attribute)
                 )  
      );
});
```

**Comment by deap82** [comment]
> For custom ValidationAttributes, adapters aren't mandatory. You could also implement IClientModelValidator in the custom attribute itself. (Server-side adapters focus on localized strings for error messages and custom attributes can handle that without implementing an additional interface.) This is the approach [Remote] (in MVC) and [SelfContainedValidation] (in Entropy) use. Does this approach work in your scenario?

Hi @dougbu,
I've found this thread in my work to also find a way to localize my own custom validation attributes. I want to ensure that I get the same validation message even if validation is only executed serverside, but after looking at the code for the RemoteAttribute and the SelfContainedValidation the accessing of an IStringLocalizer relies on getting the HttpContext through the ClientModelValidationContext. So how can I get access to an IStringLocalizer in a custom attribute that does not implement IClientModelValidator?

It also seems to me that if I do implement the IClientModelValidator I can get the correct error message rendered for the client side validation, but if I comment out the inclusion of jquery unobtrusive validation and rely on server side validation the AddValidation method will not be called so in my override of FormatErrorMessage I have no access to an IStringLocalizer. This would result in getting the resource key displayed as an error message instead of the translated error message. This is all a bit puzzling to me and if you could point me in any kind of direction it would be greatly appreciated.

**Comment by dougbu** [comment]
> So how can I get access to an `IStringLocalizer` in a custom attribute that does not implement `IClientModelValidator`?

If you're talking about the server-side part of this, have a look at the use of `ValidationContext` in [`SelfContainedValidationAttribute`](https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.LocalizationSample.Web/SelfContainedValidationAttribute.cs#L31-L39) and [`MaxLengthTwoAttribute`](https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.LocalizationSample.Web/MaxLengthTwoAttribute.cs#L22-L36).
