### ISSUE TITLE
MvcCoreServiceCollectionExtensions retrieves first registered service instead of last

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#5554]
This line:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L90

Per @danroth27 :

> When you request a service from the built service provider it will give you the last service added, not the first one. This method should mimic the DI behavior.

> This issue doesn't generally affect user scenarios today, because this method is used to extract the hosting environment service and there is typically only one of those. I hit this issue as part of my module prototyping when I added a new hosting environment for each module. The added hosting environment should override the existing one, but currently it doesn't because this method picks the first instead of the last. I'm working around this right now by simply removing the app hosting environment for each module and then replacing it with a new one.

**Comment by dougbu** [comment]
Fix ready in #5540 but I'll get a PR out that builds on that and adds a test.

**Comment by dougbu** [comment]
f32d0f2 and 48546db

**Comment by dougbu** [comment]
Thanks for f32d0f2 @danroth27 !
