### ISSUE TITLE
Set title attribute on label and/or input elements based on model metadata "Description" property

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#5563]
It would be nice to set the `title` attribute of `<label>` and/or `<input>` elements based on the associated model's `Description` property, via the `asp-for` attribute.

We should think about what the defaults should be and how one might want to configure the feature, e.g. enable/disable for different elements, via attributes, Tag Helper initializer, etc.

``` c#
[HtmlTargetElement("label", Attributes = "asp-for")]
public class LabelTitleTagHelper : TagHelper
{
    [HtmlAttributeName("asp-for")]
    public ModelExpression For { get; set; }

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        var description = For.Metadata.Description;
        if (!string.IsNullOrEmpty(description) && !output.Attributes.ContainsName("title"))
        {
            output.Attributes.Add(new TagHelperAttribute("title", description));
        }
    }
}
```

**Comment by RandyBuchholz** [comment]
Isn't the Description attribute more for developers and generally a sentence or more about what the class/method does? I use it mostly to pop-up a message for developers when they hover over a method name to describe what it is and how to use it.

**Comment by DamianEdwards** [comment]
@RandyBuchholz the intent of the Description model property was for it to be shown in the UI by systems that do runtime UI scaffolding using the `System.ComponentModel.DataAnnotations`. See https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.displayattribute.description(v=vs.110).aspx

**Comment by rynowak** [comment]
This isn't model binding

**Comment by DamianEdwards** [comment]
@rynowak ?

**Comment by rynowak** [comment]
It isn't though

**Comment by DamianEdwards** [comment]
@rynowak oh you're talking to @Eilon and his carefree labeling ways. I see now.

**Comment by Eilon** [comment]
We were using that label for all things relating in any way to model metadata, not just strictly for actual model binding.

**Comment by rynowak** [comment]
you were using it **wrong**

**Comment by mkArtakMSFT** [comment]
@DamianEdwards, @rynowak  - do we still need this, or should we close it?

**Comment by mkArtakMSFT** [comment]
We're closing this issue as its not a priority for now.
