### ISSUE TITLE
Specifying the port for action or route url

### ISSUE THREAD

**Issue by strohhut** [aspnet/Mvc#5565]
On my localhost the http port is 1507 and the https port is 44301. When I create a link with `UrlHelperExtensions` from http to https or vice versa via specy specifyingthe protocol I get an absolute url with the correct protocol but it still fails because the url doesn't include the correct port.

How can I specify something like the following?: 

```CSharp
Url.Action("MyAction", "MyController", null, "https", 44301)
```

**Comment by rynowak** [comment]
We have an overload like that, but it would require you to specify the hostname as well. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/UrlHelperExtensions.cs#L144

```
Url.Action("MyAction", "MyController", null, "https", Request.Host + ":44301")
```

**Comment by Eilon** [comment]
Yup, that's the overload to call. You could certainly add your own extension methods that are simpler to use for your scenarios.
