### ISSUE TITLE
/// comment incorrect syntax - list items don't show up

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Mvc#5568]
1. https://review.docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.mvc.rendering.htmlhelperinputextensions
2. search for "Combines HtmlFieldPrefix"
3. List is empty

![capture](https://cloud.githubusercontent.com/assets/3605364/20645682/8842f148-b409-11e6-965c-61188029802b.PNG)

The triple slash comment is written like this:
``` c#
/// <list type="number">
/// <item>
/// <see cref="ModelBinding.ModelStateDictionary"/> entry for <paramref name="expression"/> (converted to a
/// fully-qualified name) if entry exists and can be converted to a <see cref="bool"/>.
/// </item>
```
This is not the right syntax, the content inside `<item>` should be wrapped inside a `<description>` tag, please refer to the following document:
https://msdn.microsoft.com/en-us/library/y3ww3c7e.aspx

**Comment by dougbu** [comment]
@Rick-Anderson the current MVC source code has no examples of the `<list>` syntax you highlighted. Suspect you're looking at something prior to ada42ea.

**Comment by Eilon** [comment]
@dougbu what about https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngineOptions.cs#L48-L55?

**Comment by Eilon** [comment]
@Rick-Anderson indeed, is this just on older doc builds?

**Comment by Rick-Anderson** [comment]
@Eilon  it's on the current doc build for API. See https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.mvc.rendering.htmlhelperinputextensions
cc @danroth27  @bradygaster

**Comment by dougbu** [comment]
So why is the current doc build using an older version of this repo's doc comments?

**Comment by Eilon** [comment]
@Rick-Anderson which version/branch did the doc build pull from? If it was 1.0.x, we hadn't yet fixed it.

@dougbu docs always lag behind the runtime, so in general this isn't surprising.

**Comment by Rick-Anderson** [comment]
@bradygaster  @danroth27  handle API, I only do the non-API and complain.

**Comment by Eilon** [comment]
@Rick-Anderson of course 😄

**Comment by bradygaster** [comment]
@dougbu to be honest, i'd prefer the docs be as immediate as PRs are accepted and merged. @Rick-Anderson i'll create a PR to fix this XML issue compliant with the link you provided earlier.

**Comment by bradygaster** [comment]
@Rick-Anderson checked the code and verified that the items are no longer even in the XML commentary. Will check the build and with dev to make sure things are correct.

**Comment by bradygaster** [comment]
@Rick-Anderson figured out what's awry here (or just not merged yet). The code **without** the "nefariously authored item tags" is still in the master branch, whereas the updated XML commentary is committed to the **dev** branch. To update the documentation, the dev branch would need to be merged to master **or** we'd need to change the branch from which we're pulling the source code. I'll defer to @danroth27 on which option he prefers - Should we start pulling from dev instead of master, or do you guys need to do a merge from dev to master to update the docs?

**Comment by Eilon** [comment]
`master` has the latest released build, which right now is 1.1.0-rtm. We won't update it until we do some kind of 1.2.0-preview, which is probably a few months out.

We could certainly fix just the offending comments in there, but I'm not sure it's worth it for that.

**Comment by Rick-Anderson** [comment]
I'm find with it fixed in the next version.

**Comment by Eilon** [comment]
Ok, then closing this.
