### ISSUE TITLE
Can we have a UrlHelper.Content parameter or overload that appends the file version?

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#5569]
The TagHelpers for `<link>` and `<script>` are awesome. So awesome that I would like to be able to use the same `asp-append-version` functionality for scripts and styles that have to be added dynamically, such as [scripts custom elements that need ES2015 class syntax in browsers that support it but ES5 syntax in browsers that don't.](https://github.com/github/time-elements/pull/67#issuecomment-262793576) Right now to take advantage of this functionality, we have to declare dummy elements -- either `<link>`s with bogus `rel`s or `<script>` with bogus `type`s -- with `id`s so we can retrieve them in JavaScript and get their `src`/`href` values. 

Could this functionality be exposed via `Url.Content`, either via an optional parameter or an overload?

**Comment by ShadowDancer** [comment]
@tuespetre as a workaround you may download source, take service that sits behind asp-append-version and wrap it in extension method on UrlHelper.

**Comment by Eilon** [comment]
Definitely a nice feature idea, but not planned for this release.

**Comment by axelheer** [comment]
Workaround:

    public static string Content(this IUrlHelper url, string contentPath, bool appendVersion)
    {
        if (url == null)
            throw new ArgumentNullException(nameof(url));

        var path = url.Content(contentPath);

        if (appendVersion)
        {
            var serviceProvider = url.ActionContext.HttpContext.RequestServices;

            // compare code of LinkTagHelper.cs for details of this kinda hacky stuff...

            var fileProvider = serviceProvider.GetService<IHostingEnvironment>().WebRootFileProvider;
            var cache = serviceProvider.GetService<IMemoryCache>();
            var requestPathBase = url.ActionContext.HttpContext.Request.PathBase;

            var versionProvider = new FileVersionProvider(fileProvider, cache, requestPathBase);

            path = versionProvider.AddFileVersionToPath(path);
        }

        return path;
    }

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
Also a workaround available.
