### ISSUE TITLE
Error ViewFeatures.ITempDataDictionaryFactory in addmvccore(); 

### ISSUE THREAD

**Issue by patsadow2** [aspnet/Mvc#5572]
Hello,

I found weird thing when i use service.addmvccore(); as a service i get

"Microsoft.AspNetCore.Server.Kestrel[13] Connection id "0HL0O60MNJBT1": An unhandled exception was thrown by the ap plication. System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Mvc. ViewFeatures.ITempDataDictionaryFactory' has been registered.""

but when i use service.addmvc(); everything is okey

any ideas how to solve that problem when we use service.addmvccore();  ?

**Comment by rynowak** [comment]
`services.AddMvcCore().AddViewFeatures()` should include temp-data. `AddMvcCore()` is the "pay as you go" approach and attempts to include the minimal set of features that you ask for. I'd recommend using `AddMvc()` if you're writing an application with Views.
