### ISSUE TITLE
how to use route rule create url

### ISSUE THREAD

**Issue by BruinY** [aspnet/Mvc#5581]
in the class ,how to use route rule create url.
I hope that through a method to generate a url. this method not in controller.But then other libraries

**Comment by rynowak** [comment]
Are you thinking of `IUrlHelper`? https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/test/WebSites/RoutingWebSite/Controllers/BanksController.cs#L22

**Comment by BruinY** [comment]
no. not in controller

**Comment by rynowak** [comment]
Resolve the `IUrlHelperFactory` and use it to create an `IUrlHelper` then
