### ISSUE TITLE
406 Not Acceptable [Content type: video/mp4]

### ISSUE THREAD

**Issue by patsadow2** [aspnet/Mvc#5582]
Hello,
I've got a little problem. I can't get my service to stop converting everything to application/json

I tried:
```
services.AddMvc(config => {config.RespectBrowserAcceptHeader = true;});
```

i was even trying with [Produces("video/mp4")] but it says " doesnt have output formatter "

Still nothing result:
application/json 
or
406 Not Acceptable

How to make it work in .net core 1.0 ?

**Comment by rynowak** [comment]
We're going to need more information about what you're trying to do, including some code from your controller/actions.

If you returns a non-`IActionResult` from an action method, it gets run through the output formatters to try and write it to the response. By default we have the JSON formatter configured.

**Comment by patsadow2** [comment]
Hmm, so is there any output formatters implemented by asp.net core to handle "video/mp4"

This is my controller

```
        [HttpGet]
        [Produces("video/mp4")]
        public HttpResponseMessage Get()
        {
            string videoPath = @"D:\sample.mp4";
            if (System.IO.File.Exists(videoPath))
            {
                HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.OK);
                response.Content = new StreamContent(new FileStream(videoPath, FileMode.Open, FileAccess.Read));
                response.Content.Headers.ContentType = new MediaTypeHeaderValue("video/mp4");
                response.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment")
                {
                    FileName = "sample.mp4"
                };
                return response;
            }
                return new HttpResponseMessage(HttpStatusCode.InternalServerError);
        }
```

**Comment by davidfowl** [comment]
> Hmm, so is there any output formatters implemented by asp.net core to handle "video/mp4"

No.

Here's the equivalent in MVC Core 1.0:


```C#
[HttpGet]
public IActionResult Get()
{
    string videoPath = @"D:\sample.mp4";
    if (System.IO.File.Exists(videoPath))
    {
        return PhysicalFile(videoPath, "video/mp4", "sample.mp4");
    }
    return StatusCode(StatusCodes.Status500InternalServerError);
}
```

**Comment by patsadow2** [comment]
Done :dagger:
