### ISSUE TITLE
Post method request is not firing the application

### ISSUE THREAD

**Issue by LucasArgate** [aspnet/Mvc#5591]
Im using .net core (vNext) application with Kestrel.
When i use GET method it works perfectly request, but when i use POST or PUT method it not do complete request. See, Im using AngularJS $resource .save(data).

Im using Api Controller and i created an attribute filter to do pre-flight in OnActionExecuting to return status code 200. When i do POST method it not works.

see my **OnActionExecuting** method:

```c#
public override void OnActionExecuting(ActionExecutingContext filterContext) 
{
    HttpContext context = filterContext.HttpContext;
    context.Response.Headers.Add("Access-Control-Allow-Origin", "*");
    context.Response.Headers.Add("Access-Control-Allow-Headers", "token, content-type");
    context.Response.Headers.Add("Access-Control-Allow-Methods", "GET, POST, OPTIONS");

    if (context.Request.Method == "OPTIONS")
    {
        filterContext.Result = new StatusCodeResult(200);
        return;
    }
}
```

im trying to enable **CORS** in my startup class:

```c#
public void ConfigureServices(IServiceCollection services)
{
    // Add service and create Policy with options
    services.AddCors(options =>{
        options.AddPolicy("CorsPolicy",
            builder => builder.AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials());
        });
    // Add framework services.
    services.AddMvc();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole(Configuration.GetSection("Logging"));
    loggerFactory.AddDebug();

    app.UseMvc();
    app.UseCors("CorsPolicy");
}
```

Error request:

**XMLHttpRequest cannot load http://192.168.100.100:5000/api/caixa. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 500.**

I don't know what i need do to resolve it, i search it and there isn't any solution. Please, I need help.

*Obs: I will use it in WIndow 10 IoT at Raspberry PI3.

**Comment by benaadams** [comment]
You are receiving an error code `The response had HTTP status code 500.` which would suggest CORS is not added to application errors. Might want to log it out to diagnose what the error message is; or capture the POST with [fiddler](http://www.telerik.com/fiddler) and inspect the return; you will also want to add the `UseDeveloperExceptionPage` to Configure if you take the second route see example in https://github.com/aspnet/Diagnostics/blob/dev/samples/DeveloperExceptionPageSample/Startup.cs#L11

**Comment by leonvanegmond** [comment]
Try putting app.UseCors("CorsPolicy"); before app.UseMvc();

**Comment by LucasArgate** [comment]
@lvanegmond thanks for your awnser! 💯 

It works!
Now the pre-flight works, it was send perfectly! But my post is not returned the correct headers:

This is my pre-flight request (OPTIONS):
![image](https://cloud.githubusercontent.com/assets/349191/20927273/f3dd03d0-bba7-11e6-8f73-7b7d472d3643.png)

This is my post request (POST):
![image](https://cloud.githubusercontent.com/assets/349191/20927300/1d1f106c-bba8-11e6-8733-b73fa949f67d.png)

How can i do the response headers using CORS with asp.net core width POST ?

Thanks so much for your attention :)

**Comment by LucasArgate** [comment]
Heyyy it works!
Thanks so mutch!
i removed EnableCors attribute of Controller and it works perfect!

Thanks! Thanks! Thanks!

**Comment by juunas11** [comment]
@LucasArgate You should close the issue.

**Comment by hotdiggitydoddo** [comment]
@LucasArgate When you got this to work, were you still using your attribute filter?  I followed this directions  (with the exception of the filter attribute) and I get the same result:  OPTIONS works, POST doesn't.  Any help would be appreciated.

**Comment by LucasArgate** [comment]
@hotdiggitydoddo please, show me your Configure method in startup class.

**Comment by hotdiggitydoddo** [comment]
@LucasArgate here you go -- 

`public void Configure(IApplicationBuilder app)
        {
            app.UseOAuthValidation();
            app.UseOpenIddict();
            app.UseCors(x => x.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin());
            app.UseMvc();
        }`

**Comment by LucasArgate** [comment]
my code is this:
You can configure the services:
`public void ConfigureServices(IServiceCollection services)
        {
            // Add service and create Policy with options
            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder => builder.AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials());
            });
            // Add framework services.
            services.AddMvc();


        }`

and use cors apolicy:

`public void Configure(IApplicationBuilder app) {
         app.UseOAuthValidation();
          app.UseOpenIddict();
          app.UseCors("CorsPolicy");
          app.UseMvc();
}`

try it
