### ISSUE TITLE
Input (posted file) is not a valid base-64 string

### ISSUE THREAD

**Issue by dbol55** [aspnet/Mvc#5592]
Well that might be true, however we still would like it to work :) instead of manual binding that works.

**Comment by davidfowl** [comment]
Can you post a specific example?

**Comment by dbol55** [comment]
<input name="seller.Logo" type="file" accept="image/*" />

[HttpPost]
public void SaveLogo(Seller seller)
{
...
   System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength) +12271509
   System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength) +130
   System.Convert.FromBase64String(String s) +42
...
Where seller has a byte array property named Logo, targeting mvc 5.2.3 by the way.

**Comment by davidfowl** [comment]
This repository is for ASP.NET Core, not MVC 5.x. For MVC 5.x bugs go to http://aspnetwebstack.codeplex.com/
