### ISSUE TITLE
UseStatusCodePagesWithReExecute cannot work with ObjectResult. and guideline requirement for MVC error handling

### ISSUE THREAD

**Issue by sgjsakura** [aspnet/Mvc#5593]
In MVC core projects, there's many possible ways to show an error to client, you may even returns any view, however views are always with a status code of 200 defaultly. This code may be not friendly to search engine and webiside recorders. If I want to return a rich view with customs status code, there are many ways, including:
- Change `ViewResult.StatusCode` in controller action context.
- Change `Context.Response.StatusCode` in view context.
- Return an instance of `StatusCodeResult` or any inherited classes.
- Return an instance of `ObjectResult` or any inherited classes and modify the `StatusCode` property.

However there are still some problems in all above manners. 

For methods 1 and 2, you must select a view manually when errors are detected, and you cannot split your code between error generation  and error handling. I want to unify the error handling (not exception handling) in my mvc projects. In the [Error Handling](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling) documentation section, it is recommended that use `UseStatusCodePagesWithReExecute ` to capture and handle client phase errors, the following sample code woks well:

```C#
public IActionResult Index(int id)
{
  return BadRequest();
}
```

This sample is just follows the design patternin the 3rd method listed above. However, it lakes the ability to transfer custom addtional informations to the error handling system. You may using TempData to store temportray data, however I want may code to be more graceful and just tranfer a strong typed error model into the error handling system. The 4th method seems a better choice and the sample code may be:
```C#
public IActionResult Index(int id)
{
  return BadRequest("My Error Information");
}
```
However, this method not works. Looking into the source code of MVC core assembly, it seems that the second sample creates a `BadRequestObjectResult` which inherits from `ObjectResult`, while the `ObjectResult` will format and send the result directly to the client and ignores other middlewares.

So my questions are:
- Is there any guideline for MVC error handling, and which method may be the recommended one?
- If we want to split codes between error genration and capture, is there any way to bind errors together with pass strong typed error objects?
- Will it be a patch to change the way that `ObjectResult` implements considering the `UseStatusCodePagesWithReExecute`?

Thank you all for reading :-)

**Comment by Eilon** [comment]
Hi, this questions looks like it's better suited for a site such as StackOverflow, using the `asp.net-core-mvc` tag: http://stackoverflow.com/questions/tagged/asp.net-core-mvc.
