### ISSUE TITLE
Add a feature that allows binding properties stashed in the TempDataDictionary

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#5600]
This is based on a feature prototype in Razor pages. Essentially properties annotated with `TempData` attribute are round-tripped for a single request. Some cleverness is required to determine if the value of the property was changed to determine if it needs to be stashed again in TempData (https://github.com/aspnet/RazorPages/blob/master/src/Microsoft.AspNetCore.Mvc.RazorPages/TempDataPropertyTracker.cs).

**Comment by pranavkm** [comment]
cc @rynowak \ @DamianEdwards

**Comment by DamianEdwards** [comment]
The idea is we'd implement this as a filter (filters?) so that it would be supported on Controllers and Pages, and possibly even things like Formatters and Tag Helpers. In theory, it could be supported on any MVC primitive that's activated per-request.
