### ISSUE TITLE
TagHelperContext lost in child within a partial view

### ISSUE THREAD

**Issue by shobman** [aspnet/Mvc#5601]
I found that the TagHelperContext is not received by child TagHelper's if the child tag is nested inside a partial view.

If you take the following markup

```
<section id="Body">
   <h1>Heading</h1>
</section>
```
I am able to pass down the section id to the h1 using tag helper context, as follows

```
[HtmlTargetElement("section")]
public class SectionTagHelper : TagHelper
{
    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        var Id = context.AllAttributes["id"].Value.ToString();
        context.Items.Add(typeof(SectionTagHelper), Id);
    }
}

[HtmlTargetElement("h1")]
public class H1TagHelper : TagHelper
{
    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        var sectionId = (string) context.Items[typeof(SectionTagHelper)];
        output.Attributes.Add("section-id", sectionId);
    }
}
```

So the markup example above, will be rendered as

```
<section id="Body">
   <h1 section-id="Body">Heading</h1>
</section>
```

However if the h1 is nested in a partial view, the context is not received by the h1 tag helper, so the h1 cannot render with the section-id attribute.

Main.cshtml
```
<section id="Body">
   @Html.Partial("_Content.cshtml")
</div>
```

_Content.cshtml
```
<h1>Heading</h1>
```

Further, if I specify that the h1 tag helper should only process if the parent tag is a section, then the tag helper does not process for my h1 inside a partial, even though it's parent tag is a section!

```
[HtmlTargetElement("h1", ParentTag = "section")]
```

It's like the tag helpers are processed before the markup is rendered. Does anyone have any insight into what's going on whether what I'm trying is supported? 

And/or can this be added as a feature?

**Comment by NTaylorMullen** [comment]
This is by design. `TagHelperContext.Items` does not persist outside of the current view. If you want to persist data across views you can use `ViewContext.ViewData`

**Comment by shobman** [comment]
Hi @NTaylorMullen, thanks for the quick reply.  But it doesn't look like ViewData is accessible from within a TagHelper.  Do you know if this feature is on the roadmap?

**Comment by dougbu** [comment]
> on the roadmap to persist `TagHelperContext.Items` across views?

Not currently.

> doesn't look like `ViewData` is accessible from within a TagHelper.

Add something like the following to your tag helper. Then use `ViewContext.ViewData` in your code.
``` c#
[HtmlAttributeNotBound]
[ViewContext]
public ViewContext ViewContext { get; set; }
```

**Comment by shobman** [comment]
Yes, that does the trick!  Thanks for pointing this out @dougbu  :beers: :beers: :beers:
