### ISSUE TITLE
IModelBinder: Timeouts are not support exception

### ISSUE THREAD

**Issue by markolbert** [aspnet/Mvc#5603]
I am looking at ways to parse multipart post payloads which incorporate file uploads. I have a working solution which processes the raw request stream, but I thought I'd convert it to a custom model binder so it would blend in with the usual mvc semantics (e.g., public IActionResult Action([ModelBinder(...) SomeModelType model...).

FYI, this is intended to handle situations where some client-side angular code executes a POST against an MVC Core action.

The custom model binder binds information from the request stream to the target model, but as soon as BindModelAsync() returns I get a "timeouts are not supported on this stream" exception. The exception occurs in what appears to be an unrelated piece of middleware (which was working fine for quite a while). But I've seen exceptions pop up in unexpected places before when using multithreaded logic.

Here's the binder code:

```
        public async Task BindModelAsync( ModelBindingContext bindingContext )
        {
            if( bindingContext == null )
                throw new ArgumentNullException( nameof( bindingContext ) );

            if( bindingContext.HttpContext?.Request == null ) return;

            // make sure the model type we're binding to has a property of ICollection<IUploadedFile>
            var fileProps = bindingContext.ModelMetadata
                .Properties
                .Where( p => p.IsEnumerableType && typeof(IUploadedFile).IsAssignableFrom(p.ElementType) );

            if( fileProps.Count() != 1 ) return;

            var fileProp = fileProps.First();

            HttpRequest request = bindingContext.HttpContext.Request;

            if( bindingContext.Model == null )
            {
                var modelCreator =
                    Expression.Lambda<Func<object>>( Expression.New( bindingContext.ModelType ) ).Compile();

                bindingContext.Model = modelCreator();
            }

            fileProp.PropertySetter( bindingContext.Model, new List<T>() );

            var boundary = MultipartRequestHelper.GetBoundary(
                           MediaTypeHeaderValue.Parse( request.ContentType ), _maxSectionSize );

            var reader = new MultipartReader( boundary, request.Body );

            var section = await reader.ReadNextSectionAsync();
            var values = new Dictionary<string, StringValues>( StringComparer.CurrentCultureIgnoreCase );
 
            while( section != null )
            {
                ContentDispositionHeaderValue contentDisposition;
                ContentDispositionHeaderValue.TryParse( section.ContentDisposition, out contentDisposition );

                if( MultipartRequestHelper.HasFileContentDisposition( contentDisposition ) )
                {
                    var name = HeaderUtilities.RemoveQuotes( contentDisposition.Name ) ?? string.Empty;

                    T newFI = new T()
                    {
                        FileName = HeaderUtilities.RemoveQuotes( contentDisposition.FileName ) ?? string.Empty
                    };

                    await section.Body.CopyToAsync( newFI.Stream );

                    ( (List<T>) fileProp.PropertyGetter( bindingContext.Model ) ).Add( newFI );
                }
                else
                {
                    if( MultipartRequestHelper.HasFormDataContentDisposition( contentDisposition ) )
                    {
                        // Content-Disposition: form-data; name="key"

                        // Do not limit the key name length here because the mulipart headers length
                        // limit is already in effect.
                        var key = HeaderUtilities.RemoveQuotes( contentDisposition.Name );

                        MediaTypeHeaderValue mediaType;
                        MediaTypeHeaderValue.TryParse( section.ContentType, out mediaType );

                        var encoding = FilterEncoding( mediaType?.Encoding );

                        using( var streamReader = new StreamReader(
                            section.Body,
                            encoding,
                            detectEncodingFromByteOrderMarks: true,
                            bufferSize: 1024,
                            leaveOpen: true ) )
                        {
                            // The value length limit is enforced by MultipartBodyLengthLimit
                            var value = await streamReader.ReadToEndAsync();
                            values.Add( key, value );
                        }
                    }
                }

                // Drains any remaining section body that has not been consumed and
                // reads the headers for the next section.
                section = await reader.ReadNextSectionAsync();
            }

            foreach( var property in bindingContext.ModelMetadata.Properties )
            {
                if( values.ContainsKey( property.PropertyName ) )
                {
                    if( property.IsEnumerableType )
                    {
                        var converter = TypeDescriptor.GetConverter( property.ElementType );

                        List<object> converted = values[ property.PropertyName ]
                            .Select( v => converter.ConvertFrom( v ) )
                            .ToList();

                        property.PropertySetter( bindingContext.Model, converted );
                    }
                    else
                    {
                        var converter = TypeDescriptor.GetConverter( property.ModelType );

                        property.PropertySetter(
                            bindingContext.Model,
                            converter.ConvertFrom( values[ property.PropertyName ][ 0 ] ) );
                    }
                }
            }

            bindingContext.Result = ModelBindingResult.Success( bindingContext.Model );
        }

```
I realize this approach doesn't "fit" well within the model binding framework (and has a number of other limitations, such as only supporting simple properties). OTOH, based on what I've read, mixing file upload information in a POST triggered by client-side code (angular in this instance) is fraught with a lot of pitfalls, so a limited working solution suits me just fine :).

Thoughts? And thanx, BTW, to the team members who posted the original version of this code over on the Entropy site.

**Comment by davidfowl** [comment]
Where is the stack trace for the exception?

**Comment by markolbert** [comment]
Oops, sorry:

> System.InvalidOperationException occurred
>   HResult=-2146233079
>   Message=Timeouts are not supported on this stream.
>   Source=mscorlib
>   StackTrace:
>        at System.IO.Stream.get_ReadTimeout()
>        at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
>        at Microsoft.AspNetCore.Mvc.Internal.DefaultComplexObjectValidationStrategy.Enumerator.MoveNext()
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType()
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType()
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitEnumerableType()
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType()
>        at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
>        at Microsoft.AspNetCore.Mvc.Internal.DefaultControllerArgumentBinder.<BindModelAsync>d__8.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at Microsoft.AspNetCore.Mvc.Internal.DefaultControllerArgumentBinder.<BindArgumentsCoreAsync>d__6.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllActionFiltersAsync>d__26.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeExceptionFilterAsync>d__25.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>        at ConnellCampaigns.AccessControlMiddleware.<Invoke>d__8.MoveNext() in C:\Programming\ConnellCampaigns\src\ConnellCampaigns\Extensions\MaintenanceMiddleware.cs:line 102
>   InnerException: 
> 

Looking at this again, I wonder if the problem is that I haven't told the MVC binding system that I bound the model? I thought that happened automatically when you set bindingContext.Result to ModelBindingResult.Success(...), but maybe there's something else that has to be done.

**Comment by dougbu** [comment]
Looks as if this issue matches #5154. Am I correct you experienced this problem using 1.0.x bits?

FYI #5154 was fixed in 1.1.0. With that fix, validation won't dive into `Stream` properties.

**Comment by markolbert** [comment]
Okay, thanx. I'll see if it goes away upon upgrade.

**Comment by rynowak** [comment]
Also if you don't want to upgrade to 1.1 for any reason the fix is **very** simple. It's just to tell MVC not to validate properties of type `Stream`

https://github.com/aspnet/Mvc/pull/5276/files#diff-bf3a0e819ebcc8e1d819dc14e1c780c3R83

```
services.AddMvc(options =>
{
options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Stream)));
})
```
