### ISSUE TITLE
Why are status codes exposed everywhere as ints?

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#5604]
As originally reported by @nathan-alden in https://github.com/aspnet/Mvc/issues/5532:

Why are status codes exposed everywhere as ints? What happened to using the HttpStatusCode enum? I am aware of the StatusCodes class that contains all the status codes as constant integers, but this is not discoverable from IntelliSense; less-experienced developers are going to type in the integer, instead. At the very least, an overload should have been provided that contained the standard HTTP status codes.

**Comment by danroth27** [comment]
See also #5605

**Comment by khellang** [comment]
We've been through this before. See https://github.com/aspnet/HttpAbstractions/pull/345.

**Comment by tpluscode** [comment]
@khellang and where did that end? I do agree that a simple int is not a great fit. But is it there to stay?

**Comment by davidfowl** [comment]
It's here to stay.
