### ISSUE TITLE
How to wrap response models in a standard success/error response envelope?

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#5606]
As originally reported by @nathan-alden in #5532:

I had code that would wrap response models in standard success/error response envelopes by using DelegatingHandlers, thus avoiding violating DRY in every action method. I have not found a way to do this in MVC 6 other than OutputFormatters, which are limited in usefulness since they have no reference to the original action method. As a result, I can't use attributes to control response behavior (e.g., allowing action methods to opt out of response envelopes with something like [ResponseEnvelopeOptOut]).

**Comment by danroth27** [comment]
@nathan-alden What kinds of things did the success/error envelopes add to the response?

**Comment by nathan-alden** [comment]
Let's say I had this code in my Web API 2 endpoint:

```
return Ok(new { prop = "value" });
```

My delegating handler would access the object being returned by using `HttpResponseMessage.Content` and wrap it in an envelope:

```
{
  "status": "success",
  "data": theObjectFromHttpResponseMessageDotContent
}
```

This was very useful in enforcing consistent response body schemas across all APIs while obviating the need for all developers to remember to construct the response envelopes themselves.

**Comment by danroth27** [comment]
Did the envelope do anything with stuff outside the body? Like headers, status code, etc.?

**Comment by nathan-alden** [comment]
Not the envelope, no, but I did have other delegating handlers or action filters that overwrote responses if the status code was 404 or 405, and also added correlation IDs to responses if one was present in the request.

**Comment by kichalla** [comment]
One way you could do the wrapping is to write a result filter which checks if a given action result is an ObjectResult and wrap the value it exposes.

**Comment by nathan-alden** [comment]
I thought I had looked at `IResultFilter` but I may have overlooked some of its capabilities. I'll take a second look. Thanks!

**Comment by danroth27** [comment]
Closing for now, but please do let us know if you find result filters don't work for you.
