### ISSUE TITLE
Class name inconsistencies with Antiforgery attributes

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Mvc#5608]
We have a class named ValidateAnti**F**orgeryTokenAttribute which is inconsistent with AutoValidateAnti**f**orgeryTokenAttribute and IgnoreAnti**f**orgeryTokenAttribute. One of these should be renamed to makes things consistent.

**Comment by rynowak** [comment]
We did this on purpose. Lots of old code uses `ValidateAntiForgeryTokenAttribute` - but it's not cased correctly. Everything new is.

**Comment by dougbu** [comment]
Side note: This is a dupe of #5178.
