### ISSUE TITLE
ActionContextAccessor behaves differently under .NETStandard1.3 vs .NET 4.5.1

### ISSUE THREAD

**Issue by tobiasbunyan** [aspnet/Mvc#5611]
_From @tobiasbunyan on December 9, 2016 8:23_

Has the same issue with **AsyncLocal** value as **HttpContextAccessor** as referenced in bug https://github.com/aspnet/HttpAbstractions/issues/723

_Copied from original issue: aspnet/HttpAbstractions#741_

**Comment by tobiasbunyan** [comment]
_From @davidfowl on December 9, 2016 8:23_

This should be moved to MVC

**Comment by Eilon** [comment]
Need to do whatever is done in https://github.com/aspnet/HttpAbstractions/issues/723.
