### ISSUE TITLE
View navigation and intellisense  broken from 1.0.1 to 1.1.0

### ISSUE THREAD

**Issue by akdurmus** [aspnet/Mvc#5612]
I have updated each dll one by one to find the library causing the issue.

 "Microsoft.AspNetCore.Mvc": "1.1.0", When I update this library the intellisense disappears from the view. And it does not give any warning whether the view file exists or not.

In 1.0.0 and 1.0.1 the following can be seen:

![screenshot](https://cloud.githubusercontent.com/assets/787313/21069466/1a744694-be72-11e6-87c8-a69f0da90a45.png)

and if you type a view which does not exist you see the warning

![error](https://cloud.githubusercontent.com/assets/787313/21069483/3e04a9b4-be72-11e6-8e08-a79c290100e8.png)

But once the library is updated to 1.1.0 the intellisense disappears:

![noerror2](https://cloud.githubusercontent.com/assets/787313/21069499/5f5e644c-be72-11e6-8032-709ae5958cc4.PNG)

![noerror](https://cloud.githubusercontent.com/assets/787313/21069504/6d181718-be72-11e6-8158-a5d15cac48b6.png)

I tried to update all libraries from nuget package manager  with pre-releases but no sucess.

![110](https://cloud.githubusercontent.com/assets/787313/21069523/9d6e74ca-be72-11e6-893c-dcd6e28ecbfe.PNG)

**Comment by DamianEdwards** [comment]
Are you using ReSharper? I don't think VS provides any IntelliSense or error checking for view file names in the box like this.

**Comment by davidfowl** [comment]
Yes, that is resharper.

**Comment by Eilon** [comment]
Yup, seems like a ReSharper issue. You can find ReSharper support here: https://resharper-support.jetbrains.com/hc/en-us
