### ISSUE TITLE
Delay on first request due to key encryption at rest

### ISSUE THREAD

**Issue by shravan2x** [aspnet/Mvc#5613]
I have an Asp.NET Core 1.1 MVC app. On every run on the app, it stalls for 3 seconds just before this is printed:

```
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\Users\name\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
```

I don't mind the log itself, but what causes the delay? Is this a bug?

**Comment by Eilon** [comment]
@blowdart should this bug move to the https://github.com/aspnet/DataProtection/ repo?

**Comment by blowdart** [comment]
Maybe. I'm not sure I would consider it a bug to be honest, the first request is always going to block until we get a key ring open.

**Comment by Eilon** [comment]
This issue was moved to aspnet/DataProtection#193
