### ISSUE TITLE
[New Feature] Asymmetric Models in Views

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Mvc#5615]
## Issue
Currently Views support a single model type with `@model`, which can be limiting. Although there are many ways to move whatever information we want between our views and controllers, having a more prescribed approach has many advantages.

## Suggestion
Have Views support two, named models - In and Out (`@In` and `@Out`), and have the View method on Controllers have an overload - View(View: viewName, In: inModel, Out: outModel) . Having these "reserved" objects provides many advantages and supports many new features.

### Current Approaches
We can overcome this by creating transport/compound objects to pass complex data to the views if we want multiple objects, but this creates an layer of class management both in our design, and in having to package and unpack these objects. We can also use ViewData, or several other approaches.

The single model restriction can lead to over posting. Using [bind] in our action signature helps with this, but leads to overly verbose code.

## Background
One of the biggest drawbacks I find with the single model constraint is related to design from a services perspective. From the user/analyst perspective, our applications use a request-response approach. If we look at the request and response models (i.e., `@model`) they are usually different. For example, a user does a search and submits a request using a SearchParameters model. The page that is returned has a different model - like a Details model. From the application perspective though, we are often working in a Solicit-Response mode. The application may send the user a form with a FormModel, soliciting the user for a response that will posted that model back an Action that will handle it. While this my seem to be a subtle difference, it causes some problems when more than a single request is involved, especially in a services or message-driven approach. Basically, if we want good traceability, when crossing from the business perspective to the technology perspective a step is needed that transforms the request-response chain into a one-way, followed by a series of solicit-responses, and (usually) ended with a notify. Much of this work can be eliminated with this approach. (See Design/Compile Time Checking at the end of this post)

## Idea
In message-driven designs we are used to specifying input messages and output messages. It would be nice to have these as "known identifier" or aliases in the framework within a view. We could declare them with:

```
@model In: InputClassType Out: OutputClassType
```

in the Controller, the View method would have an overload

```
return View(View: "ViewName", In: inputMessage, Out: outputMessage);  
```

By default, the view would return the Out object on submit.

"In" and "Out" would be available as types/type aliases inside our View. This would be very helpful for creating things like generic TagHelpers.

## Uses
Currently I can accomplish something similar this with a generic Message class. 
```c#
public class Message<TIn, TOut> {
   public TIn InputObject { get; set; }
   public TOut object Output { get; set; }
}
```

It works pretty well for most things, but there is a lot of casting, etc. going on to use it well. I've used this in several areas.

### Separating Data Concerns
I use SoC in my data layer quite a bit. I'll often have a ViewDataModel for reading (one that has display attributes, resolved references, dropdown datasets, etc.) and a paired model for writing (without all of the presentation stuff and translated references). I'll often pass them with something like M`essage<PersonReadData, PersonWriteData>`. Then, in my tags I bind to the write object, but populate from the read object: `<tag text=@In.Name value=@Out.Name/>`
### TagHelpers
In the case of paired models, there are usually many matching properties. Instead of manually assigning the in and out bindings, TagHelpers can be used to do this for us. This is a more complex example with much more framework plumbing. In this scenario, when `@model` has an In and Out, the framework creates a "virtual `@model`". The virtual model would let you skip using In. and Out. syntax. Basically, it creates `@Model` with all of the properties of both In and Out, where getters are mapped to In, and setters mapped to out. This would require a lot more work to implement, but shows where this could go.
### General Asymmetry
The earlier examples were more semi-symmetric than asymmetric. A more asymmetric example would be working with subclasses. For example, if I have a person class and a derived employee class, I can pass a populated person and empty employee, the View can populate the employee fields correctly from the person object with user interaction. Nothing we don't already do using compound objects or ViewData, but I think it is more clear.
### Views as Transforms
Views often function as transforms. Most commonly they transform state, as with a single model solicit-response Webform. But in other cases (like the person->employee above) the transform is more complex. The In/Out declaration helps explicitly define the transform specification.
### Design/Compile Time Checking
Another thing this enables is better design and compile time checking. This is another more advanced use. When I model my business processes I define my application services using a request-response model. As I said above the request and response models are often different. The standard service modeling approach defines input and output messages ("models").  These will often be implemented as controller actions. To trace they flow of a process through my controller services I need to be sure the inputs and outputs line up. If I pass my input through ViewData, I have weak traceability - there could be many things in ViewData. Using naming conventions helps, but is limited. If I explicitly declare my input in View(), I know exactly where to look, and I can even write a check into the build process to automate this form me. A huge time and quality advantage.

**Comment by Eilon** [comment]
@RandyBuchholz we reviewed this in the MVC team, and though we think there are merits to this proposal, it is a rather large architectural change to how MVC works, so we are closing this issue.
