### ISSUE TITLE
[Feature] Scaffold ViewComponent

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Mvc#5616]
This may be in the works. I didn't see an item for it, so I thought I would add one. In Visual Studio it would be nice to have -> Add New Item -> .Net Core -> ASP.NET -> MVC ViewComponent that would add a folder, ViewComponent Class, and .cshtml page for us.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#360
