### ISSUE TITLE
Does View Components Areas?

### ISSUE THREAD

**Issue by skorunka** [aspnet/Mvc#5620]
I have View Components, which are related to a specific Area only. It seems the View Component can not resolve views under paths like: "\Areas\Admin\Views\Shared\Components\Navigation"

Are the Areas supported?

**Comment by rynowak** [comment]
> I have View Components, which are related to a specific Area only.

This is not possible, view components and areas are unrelated features.  Putting `[Area(...)]` on a view component class has no meaning.

View lookup from view components uses the same set of search paths as the rest of the system, but with `Components\Navigation` appended. If the controller handling the current request is in the `Admin` area, then `\Areas\Admin\Views\Shared\Components\Navigation` will be part of the search paths.

My recommendation is, by default put views for a view component in `Views\Shared\Components\<Name>`. Use the more specific paths if you want to **override** how a component is styled for a certain part of your site.

The exception message you get when a view isn't found should include the paths are were tried, if it's still unclear I'd suggest experimenting with controllers in your `Admin` area and outside your area to see the difference.

**Comment by Eilon** [comment]
Also a dup of https://github.com/aspnet/Mvc/issues/2640, which might have some further context and info.
