### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type

### ISSUE THREAD

**Issue by rpundlik** [aspnet/Mvc#5624]
I am using saaskit multi tenancy project for multi tenant application.
I am able to create the tenant context and able to access in all controllers.
However, sometimes it give me following error

> An unhandled exception has occurred: Unable to resolve service for type 'LMS.Model.AppTenant' while attempting to activate 'LMS.Controllers.OrganizationController'.

This error occurs randomly for any controller and on any action method executed. The nature of error is not specific to any controller/action method.

I can see my code enters the TenantResolver successfully which does in fact return a Tenant but when it comes for DI to inject it into my controller it complains with the error listed

After this error occurs my application stop completely and it shows white screen.

This issue occurs on production server and not on localhost.

Any help on this !

Tenant injected in all controller like this

```
public class HomeController
    {
        public HomeController(TenantContext<AppTenant> tenantContext)
        {

        }
    }

```
and below is the extension class for where tenantContext is made injectable

```
public static class MultitenancyServiceCollectionExtensions
    {
        public static IServiceCollection AddMultitenancy<TTenant, TResolver>(this IServiceCollection services)
            where TResolver : class, ITenantResolver<TTenant>
            where TTenant : class
        {
            Ensure.Argument.NotNull(services, nameof(services));

            services.AddScoped<ITenantResolver<TTenant>, TResolver>();

            // No longer registered by default as of ASP.NET Core RC2
            services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();

			// Make Tenant and TenantContext injectable
			services.AddScoped(prov => prov.GetService<IHttpContextAccessor>()?.HttpContext?.GetTenantContext<TTenant>());
			services.AddScoped(prov => prov.GetService<TenantContext<TTenant>>()?.Tenant);

			// Make ITenant injectable for handling null injection, similar to IOptions
			services.AddScoped<ITenant<TTenant>>(prov => new TenantWrapper<TTenant>(prov.GetService<TTenant>()));

			// Ensure caching is available for caching resolvers
			var resolverType = typeof(TResolver);
            if (typeof(MemoryCacheTenantResolver<TTenant>).IsAssignableFrom(resolverType))
            {
                services.AddMemoryCache();
            }

            return services;
        }
}
```
When the white screen appears it gives me
>Network Error: 500 Internal Server Error Could not find the related path.

 I have set `TenanContext` in Session in `AppTenantResolver` class, so that I do not need to resolve tenant again and again. But this session value sometimes comes null for any action method executed. I have set like `context.Session.SetObjectAsJson("TenantContext", tenantContext)`

Why this HttpContext session comes null sometimes ? Because of this I am not able to get the tenant context

**Comment by Eilon** [comment]
@rpundlik this seems like maybe it's an issue in https://github.com/saaskit/saaskit - could you try logging an issue there?
