### ISSUE TITLE
Wrong docs ApiRequestFormat

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5625]
I suspect too much copy-paste, not enough coffee ☕️ 

https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.ApiExplorer/ApiDescription.cs#L50

**Comment by jbagga** [comment]
What is it supposed to be? 
```C#
/// <summary>
/// Gets the list of possible formats for a request.
/// </summary>
```
Anything else that I should find out to add to the `Remarks` section?

**Comment by rynowak** [comment]
I would add a similar blurb to the remarks. It will be empty if the action doesn't take a 'body' parameter.
