### ISSUE TITLE
"More than one DbContext was found" when migrating database in a vanilla project

### ISSUE THREAD

**Issue by Biarity** [aspnet/Mvc#5626]
When creating a new ASP.NET Core MVC project, then running:
`Add-Migration _some_name`,
`Update-Database`,
I get:
`More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for dotnet commands.`

Any idea why? Isn't `ApplicationDbContext` the only one there? But then running
`Update-Database -Context "ApplicationDbContext"` gives:
`No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in the same assembly as 'ApplicationDbContext'.`

However, my `ApplicationDbContext` class has the following parameterless constructor:
`public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }`
so I'm not sure why it isn't working.

Same issue on VS 2015 & VS 2017 RC 2.

**Comment by Eilon** [comment]
@divega any idea on this? Do you need more info to investigate?

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework#7297
