### ISSUE TITLE
Unable to open the project

### ISSUE THREAD

**Issue by manojjagtap1981** [aspnet/Mvc#5635]
I am using VS Premium 2013 with Update 4 and I am getting unsupported issue while opening this project.
Please advice.

Thanks
Manoj

**Comment by Eilon** [comment]
Hi, at this time you need Visual Studio 2015 Update 3 to open the projects here.

In the near future you will need Visual Studio 2017 RC.2 (or newer) to open the projects, once we switch them to the updated CSPROJ-based system.

You can download free trials and preview versions of Visual Studio from here: https://www.visualstudio.com/vs/
