### ISSUE TITLE
Make CookieName of CookieTempDataProvider configurable

### ISSUE THREAD

**Issue by axelheer** [aspnet/Mvc#5637]
The name of the cookie seems to be fixed, while other components ([Antiforgery](https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNetCore.Antiforgery/AntiforgeryOptions.cs#L32), [Session](https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionOptions.cs#L19), ...) are open for alternatives. Making this configurable seems to be a breaking change, since there is already a [public static property](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/CookieTempDataProvider.cs#L20) exposing that fixed value, though.

Is there any reason why this is "hard-coded"? Can we make it configurable instead?

I could prepare a PR for that.

**Comment by Eilon** [comment]
@axelheer this seems reasonable. If you send a PR we can certainly review it for consideration in 2.0.0.
