### ISSUE TITLE
ParameterApplicationModelConvention

### ISSUE THREAD

**Issue by fengkaka** [aspnet/Mvc#5639]
We have ActionApplicationModelConvention to wrap IActionModelConvention and provider a extent method like this:
 public static void Add(
            this IList<IApplicationModelConvention> conventions,
            IActionModelConvention actionModelConvention)
        {
            conventions.Add(new ActionApplicationModelConvention(actionModelConvention));
        }
and ControllerApplicationModelConvention and so on.
why havn't a class which name like 'ParameterApplicationModelConvention' to wrap IParameterModelConvention?

**Comment by rynowak** [comment]
You're absolutely right we need this. Logged here already and planned for 2.0.0  https://github.com/aspnet/Mvc/issues/5618
