### ISSUE TITLE
Anchor tag helper gets confused when multiple controllers have same name

### ISSUE THREAD

**Issue by denisz1** [aspnet/Mvc#5641]
We have a large solution with various subsystems. Many have controllers with identical names. We differentiate between them by using fully-qualified names.

But tag helpers get confused because of the same-named controllers.

    namespace My.Company.Office1

      [Area("Accounts")]
      public class OrderController : Controller {

          [Route("/office1/accounts/orders/create")]
          public IActionResult Create() { /* etc. */ }

      }
    }

    namespace My.Company.Office2

      [Area("Accounts")]
      public class OrderController : Controller {

          [Route("/office2/accounts/orders/create")]
          public IActionResult Create() { /* etc. */ }

      }
    }

    <a asp-area="Accounts" asp-controller="Order" asp-action="Create"></a>

That tag helper will match the second controller, i.e. the route "/office2/accounts/orders/create". You can check this: place them both in the same file, and I think the controller which is last discovered is the one chosen by the tag helper.

It would be helpful to be able to provide a fully-qualified namespace, like this:

    <a asp-area="Accounts" asp-controller="My.Company.Office2.Order" asp-action="Create"></a>

**Comment by Eilon** [comment]
Having two controllers in the same area with the same name is not supported. That's actually exactly what areas are for - allowing two controllers with the same name in the same app!

So, unfortunately, this is by design and not supported.

Alternatives include:

1. Renaming the controllers
2. Choosing a different area for each controller
3. Having a single "meta" controller with the "common" name that re-routes requests depending on the "office" identifier

And no doubt many other variations...

**Comment by denisz1** [comment]
@Eilon Ok. Note though that routing actually works perfectly fine.

It's only the `asp-controller` part of the anchor tag helper that doesn't.

**Comment by Eilon** [comment]
@denisz1 right, with attribute routes the ambiguity is solved on that side, though you could run into problems in other parts of the system that look at the `controller` and `action` of the request, such as rendering views, generating URLs to other parts of the system, etc. But ultimately this is simply not supported in MVC.

**Comment by denisz1** [comment]
@Eilon Yeah I understand.

FYI our use case is we use a "feature folder" solution instead of the folder convention of `Controllers`, `Models`, `Views`, `Areas`, etc. And in a feature folder organisation, you name most of the items the same way - so each feature has a `Controller` class, and a `Mapper` class, and `IndexViewModel` class, CRUD stuff, etc. That's why all our controllers were named identically.

Thanks anyway for clarifying.
