### ISSUE TITLE
Thinking FileVersionProvider is not locking when getting file sha512

### ISSUE THREAD

**Issue by pkellner** [aspnet/Mvc#5643]
In the FileVersionProvider

https://github.com/aspnet/Mvc/blob/9146fce4ec44abe8007eb659f2020c192bdcfa21/src/Microsoft.AspNetCore.Mvc.TagHelpers/Internal/FileVersionProvider.cs#L85

Line 85 (var fileInfo = _fileProvider.GetFileInfo(resolvedPath);) should be protected with a lock so that if a specific image tag is repeated on a page, GetFileInfo will not get called multiple times and create multiple watchers on the same file.

If this is the case, happy to fix but maybe I'm missing something not obvious.

**Comment by Eilon** [comment]
@pranavkm can you investigate and assess?

**Comment by pranavkm** [comment]
@pkellner the specific call to `GetFileInfo` happens inside of a cache miss. The second time around, it shouldn't enter the block. Additionally, `PhysicalFileProvider.Watch` caches and re-uses `IChangeToken` instances, so there really isn't an issue with dealing with multiple watchers. Do you have some data that suggests issues in this code path?

**Comment by pkellner** [comment]
Hi @pranavkm and @Eilon .  I agree that when the cache value is found that the code is threadsafe and there will be no issue.  However, when the cache is not found, the block that loads the cache (line 83-189) is not thread safe. For example, another request could be processing the same block and be at line 85, then both threads would be requesting the fileInfo.  I believe we should have the double lock protocol implemented there so that on a given image, only one fileInfo will be called. The other threads should be blocked from calling getFileInfo until the first one is allowed to complete (and then of course it should check again to make sure cache did not get loaded while it was waiting).

I was hoping to make a suggested implementation with a pull request but after forking and cloaning the repo, I'm getting the error that >NET Core SDK version 1.0.0-preview2-1-003180 is not installed and I don't know where to find that (or if I'm diong something wrong).

Anyhow, sorry if I'm missing something obvious here and the code is correct. I know you guys are swamped and not trying to drag you from real work.

**Comment by pranavkm** [comment]
> I'm getting the error that >NET Core SDK version 1.0.0-preview2-1-003180 is not installed and I don't know where to find that (or if I'm diong something wrong).

Running build.cmd should install the SDK for you under %LocalAppData%. As long as you use the same shell to launch VS, (i.e. launch `Mvc.sln` from the shell) it should pick it up. Alternatively you can install the MSI from 
https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/1.0.0-preview2-1-003180/dotnet-dev-win-x64.1.0.0-preview2-1-003180.exe.

> I believe we should have the double lock protocol implemented there so that on a given image, 

It would be great if we had some data that suggested invoking `IFileProvider.GetFileInfo` concurrently was problematic before we did any work here.

**Comment by pkellner** [comment]
Hi @pranavkm and @Eilon I need a few more words here to understand what you are looking for.  Let me ask a couple questions to help me understand.

1.  Do you agree that there is a concurrency issue inside the "if (!_cache.TryGetValue(path, out value))" block but are not sure if the problem it creates is worth addressing because it might not happen often enough to warrant a fix?

2.  Do you think that there is not a concurrency issue inside the "if (!_cache.TryGetValue(path, out value))" block and want me to produce an example that shows there is a problem?

3.  Do you think that it's OK to open multiple watchers on any given file because the fileProvider.watch can handle that and the overhead of that is not an issue when/if it happens?

Also, I installed the ...preview2-1-003180.exe successfully, but with visual studio 2015 I can not build the project without lots of errors. (build log here:  https://dl.dropbox.com/s/dmo09acujsyb4er/vserrors2015.txt?dl=0 )

I've not used the command line tools in core so did not try that.

**Comment by pranavkm** [comment]
1 & 2. Yup. We might do fewer `GetFileInfo` calls until the value is cached, but might have increased contention in having a single global lock for all lookups or the ongoing cost of using something like `Lazy<T>`. It's hard to tell if this tradeoff is worthwhile over a safe race that we currently have without having any data.

3. Like I mentioned earlier, in the ordinary case, the `IFileProvider` would be an instance of `PhysicalFileProvider`. Each instance of `PhysicalFileProvider` is associated with exactly one `FileSystemWatcher` and it does caching behind the scenes to ensure multiple invocations to `Watch` (concurrent or otherwise) return the same token. So there really shouldn't be a whole lot of costs in invoking it multiple times.

It looks like the build did not recompile the TestCommon project. From your build log:

> Skipped Rebuild All: Project: Microsoft.AspNetCore.Mvc.TestCommon, Configuration: Debug Any CPU ------

Maybe try cleaning the repo (`git clean -xdff`) with the solution closed in VS and rebuilding?

**Comment by pkellner** [comment]
Thanks @pranavkm   I feel like now we are almost on the same page.  A single lock would be terrific.  I would not even suggest considering that.  The only solution that I can think of is a thread safe collection of static lock objects, one per image.  (With an option to disable on the parameter list).  

The reason I think this is an important fix is that you can not predict edge cases well of the use of the img tag helper and I can see a scenario where some has an extremely light weight page with many images on it.  The site gets slashdot'd and the hundreds of thousands of near simultaneous requests come in and hundreds of thousands of getfileinfo and add watch calls kill the server.  

I'm happy to write the code, put a test case together, and do a pull request.  

On the build issue, I did a clean clone and build so I don't see how hit clean would help (away from my computer right now).

**Comment by pkellner** [comment]
Oops, meant horrific, not terrific.

**Comment by pranavkm** [comment]
@pkellner feel free to reopen this work item when you have some perf profiles for before \ after the change. I'm closing this for now since I don't see this show up in hot paths in any meaningful way.
