### ISSUE TITLE
Refactor/Simplify Code From for to linq?

### ISSUE THREAD

**Issue by pkellner** [aspnet/Mvc#5644]
Is it appropriate to submit pull requests to simplify code that seems like it could be simpler and easier to read?  Let me give an example:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs

Code at lines: 343-354:

        private static bool IsCharWhitespace(char ch)
        {
            for (var i = 0; i < ValidAttributeWhitespaceChars.Length; i++)
            {
                if (ValidAttributeWhitespaceChars[i] == ch)
                {
                    return true;
                }
            }
            // the character is not white space
            return false;
        }

Could be replaced with:

        private static bool IsCharWhitespace(char ch)
        {
            return ValidAttributeWhitespaceChars.Any(t => t == ch);
        }

I don't know if the linq is slower but is certainly easy to see at a glance if it is correct rather than the previous longer block that takes more though.

Happy to do the pull request on this and other similar optimizations if I see them.  Please let me know if these kind of pull requests are wanted or just nuisances to the team.

**Comment by davidfowl** [comment]
> I don't know if the linq is slower but is certainly easy to see at a glance if it is correct rather than the previous longer block that takes more though.

Usually when you see code like this it's done for performance reasons. We usually have comments that start with `// PERF:` but you can safely assume that less LINQ is usually better in framework code (especially in hot paths).

**Comment by Eilon** [comment]
This particular code is almost certainly due to perf - it's not code we would normally write that way otherwise.
