### ISSUE TITLE
Attribute Routing Not Working after migration to MSBuild

### ISSUE THREAD

**Issue by caleblloyd** [aspnet/Mvc#5646]
I recently switched to VS 2017 and MSBuild, and Attribute Routing has stopped working.

I have followed the official [attribute routing guide](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing#attribute-routing) but still everything is returning a 404.

I have a recreate of this behavior at: https://github.com/caleblloyd/aspnet-route

**Comment by Eilon** [comment]
@caleblloyd the controller in your project isn't public - could that be the cause?

Check this line: https://github.com/caleblloyd/aspnet-route/blob/master/route/contorlllers/HomeController.cs#L5

And mark the class as `public class`.

Does that solve the issue?

**Comment by Eilon** [comment]
(All controllers in MVC must be public types.)

**Comment by caleblloyd** [comment]
@Eilon sometimes it's the simple things... thanks for bailing me out 😄
