### ISSUE TITLE
Errors creating new Api Controller

### ISSUE THREAD

**Issue by MartinMason** [aspnet/Mvc#5647]
Creating a new AspNetCore project in Visual Studio 2015, add a new class, try to create a new scaffolded Api Controller, this error is received. I can reproduce everything stated in this post. Have tried every solution produced and nothing works. Creating an empty Api controller succeeds. Tooling preview 2 is dire need of an update.

http://stackoverflow.com/questions/41022748/asp-net-core-adding-controller-using-entity-framework

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#372
