### ISSUE TITLE
CancellationTokenSource is not Disposed in cache tag helpers

### ISSUE THREAD

**Issue by Funbit** [aspnet/Mvc#5649]
Inside https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/CacheTagHelper.cs#L80 (ProcessAsync method) there is a CancellationTokenSource instantiation without proper Dispose call.

Also, https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/DistributedCacheTagHelper.cs#L72 creates a new CancellationTokenSource which is not used anywhere.

I believe these places should be fixed.

**Comment by Eilon** [comment]
For https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/CacheTagHelper.cs#L80 I'm not sure what the intention is.

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/DistributedCacheTagHelper.cs#L72 is definitely wrong - the CTS isn't even used, so we can just delete it.

@sebastienros can you take a look?

**Comment by Eilon** [comment]
@sebastienros - can you take a look to see if we need to do something here? Looks like there's at least a small change we need to make?

**Comment by sebastienros** [comment]
@Funbit 

Based on our usage of the `CancellationTokenSource` there will be no `Timer` or callbacks registered, which means there is really nothing to dispose. There is also potentially a `ManualResetEvent` but I don't think it's initialized. So it should be safe in terms of memory management to not call `Dispose`.

My gut feeling would be to actually not call `Dispose` until it's proven that there is a memory leak from it, with our specific usage.
