### ISSUE TITLE
[Comment/Question] HTML Select End Tag - Odd Behavior

### ISSUE THREAD

**Issue by thyams** [aspnet/Mvc#5651]
Sample Case:
`<select id="stored-proc-picker" class="form-control" asp-for="ExportProcType" asp-items="Html.GetEnumSelectList<ExportProcTypes>()"></select>`

Works as intended. Fully populates my DOM select object with appropriate data.

Trouble Case:
`<select id="stored-proc-picker" class="form-control" asp-for="ExportProcType" asp-items="Html.GetEnumSelectList<ExportProcTypes>()" **/>**`

Emphasis on the short hand tag ending notation. The oddity is that it fully renders the select contol on page, just without any elements/databound to it. In the past however, the **element was not on the page at all** when no data was bound to it.

My question would be, can we mark this as warning in Intellisense when asp-items helper tag is utilized/detected? I just spent an hour beating my head against a wall before I realized my mistake. I am not sure if this a Browser/Render time issue or not, therefore, I don't think this is anything you guys could do to resolve and allow short hand tag notation when asp-items data binding is in use.

**Comment by Eilon** [comment]
@thyams this issue is being tracked here: https://github.com/aspnet/Razor/issues/433.

**Comment by thyams** [comment]
Cheers @Eilon
