### ISSUE TITLE
[IgnoreAntiforgeryToken] not working with .net core 1.1.0. It is working with .net core 1.0.

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Mvc#5657]
Moving this issue here... https://github.com/dotnet/core/issues/403

**Comment by Petermarcu** [comment]
@chintan3100

**Comment by Petermarcu** [comment]
To reproduce issue apply attribute [ValidateAntiForgeryToken] on class level and use [IgnoreAntiforgeryToken] on some of method

**Comment by Eilon** [comment]
@kichalla can you investigate? If you can repro, please share thoughts on whether this is patch-worthy.

cc @rynowak FYI.

**Comment by kichalla** [comment]
@chintan3100 Since there is no specific repro here, I am assuming you are seeing antiforgery validations happening, for example, on GET requests? `IgnoreAntiforgeryToken` works in context of `AutoValidateAntiforgeryTokenAttribute`. This 'auto' validate attribute, by default, ignores antiforgery validation for GET, HEAD, TRACE and OPTIONS requests. Try again with this new attribute and let us know if it does not work.

**Comment by kichalla** [comment]
I also it working in 1.0.0..investigating..

**Comment by kichalla** [comment]
I was able to repro it and this issue was fixed in the 'dev' branch few weeks back: https://github.com/aspnet/Mvc/commit/b2340d327ea3ba8e499820a1db60164c305c8107

**Comment by kichalla** [comment]
This bug was introduced as part of a fix in 1.0.2 release:
Commit: https://github.com/aspnet/Mvc/commit/f02f55c33d09206e75547061d526e1e99a3825c8
Bug for which the above fix was made: Antiforgery filter is in wrong order relative to Authorize (#5483)

**Comment by rynowak** [comment]
@kichalla - is this issue just that the order is wrong and we need to port that fix?

**Comment by kichalla** [comment]
> @kichalla - is this issue just that the order is wrong and we need to port that fix?

yes, right.

**Comment by Eilon** [comment]
Ok, we have antiforgery triage on Thursday, so let's discuss this then.

**Comment by Eilon** [comment]
Oh hmm is this actually a dup of https://github.com/aspnet/Mvc/issues/5552? If so, looks like we already intended that to go into 1.1.1, but the bug was closed prematurely because it was checked into 'dev' for 2.0.0...

**Comment by Eilon** [comment]
Per @rynowak and @ryanbrandenburg this is indeed a dup of https://github.com/aspnet/Mvc/issues/5552, so closing.
