### ISSUE TITLE
MediaType's IsSubsetOf does not work as expected

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#5661]
```c#
public IActionResult Index()
{
    var mt1 = new MediaType("text/plain");
    var mt2 = new MediaType("text/plain; charset=utf-8");
    return Content(mt1.IsSubsetOf(mt2).ToString());
}
```
1. The above action returns False
2. Where as mt2.IsSubsetOf(mt1) returns True. This is incorrect, right?

Old Web API behavior is the same as 1. here:
https://github.com/aspnet/AspNetWebStack/blob/29ded53ad9d8beb5e867150f51a201085aa46e93/test/System.Net.Http.Formatting.Test/Formatting/MediaTypeHeaderValueExtensionsTests.cs#L123

I looked at the current tests and the behavior is as 2.
https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.Core.Test/Formatters/MediaTypeTest.cs#L133

@dougbu

**Comment by dougbu** [comment]
Your test shows `IsSubsetOf()` is working correctly for both (1) and (2). `IsSubsetOf()` is _not_ commutative.

Old Web.API had / has a few bugs in this area.

**Comment by Eilon** [comment]
Right, the current behavior appears to be correct. Discussed in person with everyone.
