### ISSUE TITLE
generic http 400 Bad Request when illegal characters in request headers - would need more detail in error

### ISSUE THREAD

**Issue by andrasg** [aspnet/Mvc#5662]
Calling an API with an illegal character (non-ASCII, like `ő`) in a request header's value will result in a http 400 result and no exception on MVC side. The result does not contain any hints on what might be wrong or any callstack that could help diagnostics.
It would be great if there would be some more descriptive error (or even exception). I am using Application Insigths as well and this issue resulted in no request telemetry, no exception telemetry.

**Comment by Eilon** [comment]
@Tratcher is this happening at some lower layer of the system?

I'm not sure there would ever be an exception for this because it is illegal for the client to send this request, so a 4xx level error (without an exception) is correct.

But perhaps there are some logs written out using Microsoft.Extensions.Logging that you could observe.

**Comment by Tratcher** [comment]
WebListener or Kestrel? If it's WebListener then it's Http.Sys rejecting the request before ASP.NET even receives it. If it's Kestrel then check with @cesarbs, but yes expect requests with non-ascii headers to be rejected.

**Comment by andrasg** [comment]
I have experienced it in Kestrel. I was able to follow the request in my middlewares, and then even in my filters but then it disappeared (without an exception or anything on the output) before hitting the MVC action.
I am not expecting the request to be expected, I am merely arguing for a better error message. It took me several hours to find out what was wrong. The message I was getting only had http 400, bad request in it. Nothing in the body, nothing that would hint at the actual problem.

**Comment by Tratcher** [comment]
Which header was it? The checks we're talking about are in the server and should have prevented the request from reaching middleware. However, some of these checks may be new in Kestrel 1.1.

**Comment by andrasg** [comment]
It was a custom header called X-Application-Sys-UserId. Using 1.1 already.

**Comment by Tratcher** [comment]
@cesarbs can you repro this quickly?

**Comment by cesarbs** [comment]
The request is being rejected by Kestrel before the app or any middleware is executed. @andrasg could your client be making parallel requests and those are what you're seeing when debugging?

Nothing is being logged for this, even though it should. There's even a comment about it @ https://github.com/aspnet/KestrelHttpServer/blob/e55c62444bdd34274173b011720c03f23c4db2f5/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/FrameOfT.cs#L199, but it looks like we broke that assumption.

**Comment by cesarbs** [comment]
Filed https://github.com/aspnet/KestrelHttpServer/issues/1295.

**Comment by Eilon** [comment]
@cesarbs should we close this bug?

**Comment by andrasg** [comment]
@cesarbs, I am pretty sure I was launching one single request and tracking it through my middlewares. Will try to put together some test project to verify.

**Comment by cesarbs** [comment]
@Eilon Not yet, I want to wait for @andrasg's test results.

**Comment by andrasg** [comment]
I was not able to repro in a new sample project. Must have been dreaming... Never mind, closing the issue, thanks for the help!

**Comment by andrasg** [comment]
Tried it quickly with .net fw 452, got this on debug out:
```
Microsoft.AspNetCore.Server.Kestrel: Warning: Connection processing ended abnormally

Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: The input string contains non-ASCII or null characters.
```
When switching to net461, there was no error output at all.

**Comment by cesarbs** [comment]
@andrasg Interesting, thanks for pointing that out. I was working with the assumption that the issue afected both frameworks. Will take a close look on net452.

**Comment by andrasg** [comment]
I didn't manage to repro my original issue (request seen in middleware but not in MVC) though, so, that's at least consistent :)

**Comment by cesarbs** [comment]
@andrasg Check your Kestrel package versions when switching frameworks. I think when you switch to `net452`, you're reverting to an older version of Kestrel.
