### ISSUE TITLE
Understandable and easy routing in core?

### ISSUE THREAD

**Issue by dbol55** [aspnet/Mvc#5663]
Few things has been so discussed and annoying such as routing... does mvc core support an easy, understandable and upfront stable and static routing such as below, without use of extra overgead such as areas or a lots of attributes:

**MODELS/Order/Order.cs
CONTROLLERS/Order/OrderController.cs
VIEWS/Order/Order.cshtml**

And ofcourse could be overriden by attributes at will.

**Comment by Eilon** [comment]
Hi @dbol55 , can you provide more info about which URLs you want to map to which actions?

There are two built-in "very static" ways of using routing:

1. Using attribute routes. This means putting attributes on various controller actions, so it's not "up front".
2. Using explicit conventional routes that map to specific controller actions:
```c#
routes.MapRoute(
    name: "getproduct",
    template: "products/getproduct",
    defaults: new { controller = "Product", action = "GetProductInfo" }
);
routes.MapRoute(
    name: "updatetproduct",
    template: "products/modifyproduct",
    defaults: new { controller = "ProductUpdater", action = "UpdateProductInfo" }
);
```

Note that the URLs themselves in the "template" parameter can be pretty much whatever you want. And then each one maps to whatever controller and action you want.

**Comment by dbol55** [comment]
I would like to have urls such as:
www.site.com/
www.site.com**/A/**
www.site.com**/A/B/**

That automatically maps to:
Controllers/        => Views/ 
Controllers/a/     => Views**/A/**
Controllers/a/b/  => Views**/A/B/**

This allows me to get a understandable structure without a ton of extra routing code.
And where you can override mapping with attributes if needed.

**Comment by Eilon** [comment]
Ah, it sounds like maybe you want the upcoming Razor Pages feature, where a request is routed directly to a CSHTML page, is that right? If so, we're working on that right now.

The feature is being tracked here: https://github.com/aspnet/Mvc/issues/494
And its naming is being tracked here: https://github.com/aspnet/Mvc/issues/5208

**Comment by dbol55** [comment]
Shure that is a step in right direction especially the routing part:

www.site.com/foo/index.cshtml        => www.site.com/foo/
www.site.com/foo/bar/index.cshtml  => www.site.com/foo/bar/

And it would be great if it could be applied to traditinal mvc view engine aswell.
And it maybe could be mapped at controller namespace level something like: 

application.controllers.foo.bar.*
would look for a view in something like:
views/foo/bar/

It could be quite easy to implement, and I belive would take away a lot of trouble for many developers that find it hard to struggle with the routing part as above makes logical sense.

And also where you maybe could have something like a default "indexcontroller" that automatically maps to the root structure as foo/bar/

**Comment by Eilon** [comment]
Hi @dbol55 there are no plans to implement this exact feature. However, within MVC there are some features and extensibility points that can help you build a system that works this way.

First, check out MVC's "areas" feature, which makes it easy to have controllers "sort of" be in a namespace.

Second, we have a sample that shows how to use the namespace as part of a route, which you can check out here: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRoutingConvention
