### ISSUE TITLE
Allow AsyncLocal context to flow through the entire request pipeline

### ISSUE THREAD

**Issue by madelson** [aspnet/Mvc#5666]
I'm just getting started with porting some existing Mvc5 apps to ASP.NET Core.

We like to use AsyncLocal (previously logical call context) as a way to flow contextual information throughout a request and any background/parallely-executing tasks it might spawn (e. g. adding contextual data for logging or profiling).

I tried setting the value of my AsyncLocal in an IAsyncAuthorizationFilter, but it did not appear to flow through to the controller method.

Would it be possible to ensure consistency of execution context throughout all steps in the request pipeline?

As I said, I am very new to ASP.NET Core, so I apologize if there is an existing way of getting this to work.

**Comment by rynowak** [comment]
Async local does flow, but authorization filters are a 'leaf.

Image it like this: (warning, bad ASCII art)

```
middleware -> routing -> MVC -> Authorization Filters
                                                   ->  Resource Filters -> Model Binding -> Action Filters -> Action
                                                                                   -> Result Filters -> Result
```

That's basically what the 'happy path' looks like in terms of the async call context. For various legacy reasons the pipeline is not a set of simple decorators.

If you set something in the async call context in a resource filter it will be available for all of the subsequent processing the request does. This is a new filter stage we introduced in core for any work you want to do that *surrounds* processing but is not security-related. 

OR if the data you're working with isn't related to which MVC action was selected, then middleware is another good choice.

If this doesn't work for you if you then please tell us more about what you're trying to accomplish and we can suggest some ideas.

**Comment by rynowak** [comment]
Closing as there's been no further ask.

**Comment by madelson** [comment]
Thanks @rynowak for your previous explanation. I believe we can use the middleware concept to do what we need.
