### ISSUE TITLE
Passing the array of bytes as a view content instead of file path of view for creating a view from a database!

### ISSUE THREAD

**Issue by mastermehdi** [aspnet/Mvc#5668]
Passing the array of bytes as a view content instead of file path of view for creating a view from a database!

**Comment by Eilon** [comment]
Though there are no plans to have this built-in, you can do this today with a custom file provider.

This involves two steps:

1. Write a custom file provider. You can refer to https://github.com/aspnet/FileSystem/tree/dev/src/Microsoft.Extensions.FileProviders.Embedded to see how it's done.
2. Register the provider with MVC's Razor View Engine by adding it to `RazorViewEngineOptions.FileProviders` in the call to `.AddMvc` in your app's `Startup.cs` file in the `ConfigureServices` method.
