### ISSUE TITLE
Error MSB4025 when deploying ASP.Net MVC .Net Core app 

### ISSUE THREAD

**Issue by m2web** [aspnet/Mvc#5669]
I am trying to deploy an ASP.Net MVC .Net Core app that was created on an Ubuntu 16.04 system in Visual Studio Code. When attempting to push local git deployment to my Azure app to its Azure App Service.
In the project’s root directory, I ran the following:
`git push -u azure master`
and got the following:

> D:\home\site\repository\project.json(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
> remote: Failed exitCode=1, command=dotnet publish "project.json" --output "D:\local\Temp\8d436b77fda50dd" --configuration Release
> remote: An error has occurred during web site deployment.
> remote: 
> remote: Error - Changes committed to remote repository but deployment to website failed.
> To https://m2@myappname.scm.azurewebsites.net:443/mayappname.git
>  [new branch]      master -> master
> Branch master set up to track remote branch master from azure.

I got an almost identical error message when deploying from the identical repo on Bitbucket.

I have found references to this error when dealing with continuous integration paltforms but has anyone else seen this when trying to deploy an ASP.Net MVC .Net Core app? Here is the project.json file:
```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.EntityFrameworkCore": "1.1.*",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer":"1.1.*",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0"
  },

  "tools": {
    "BundlerMinifier.Core": "2.2.306",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
     "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.1.0-preview4-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "precompile": [ "dotnet bundle" ],
    "prepublish": [ "bower install" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },

  "tooling": {
    "defaultNamespace": "myNameSpace"
  }
}
```
**Edit:** I have created a public repo here: https://github.com/m2web/m2prayer.net.core.public
To date there is little available concerning the error that I am getting with asp.net core with Azure App Services.

**Comment by pranavkm** [comment]
You need to specify a sdk version (most likely `1.0.0-preview2-1-003177`) in your global.json. In the absence of one, the highest version available on the machine gets used. Azure App Services likely has the msbuild supporting one installed which does not work with json files unless they're migrated.

**Comment by m2web** [comment]
pranavkm, thanks for the reply and help. I assume you mean the .net core SDK, correct?
A `dotnet --version` results in `1.0.0-preview2-003131`.
I added the following to the project.json:
```
"sdk": {
      "version": "1.0.0-preview2-003131"
  }
```
The error is still the same.

**Comment by pranavkm** [comment]
@m2web - the sdk version needs to be added to the `global.json`. See https://github.com/aspnet/Mvc/blob/dev/global.json for reference.

**Comment by Eilon** [comment]
Right, it looks like it's trying to use MSBuild to build a project.json-based project, which of course won't work. Specifying the SDK version in global.json should fix this.

cc @DamianEdwards @davidebbo for FYI information as we recently discussed this.

**Comment by davidebbo** [comment]
Yes, generally, it's important for all projects to have a global.json. Without this, you're basically getting a 'random' SDK, and even if it works today you might get broken when a newer incompatible SDK appears.

**Comment by m2web** [comment]
pranavkm, Doh! I really did read your message but must have had the project.json file on the brain. After adding the global.json file with the SDK value did the trick.

**Comment by Matticusau** [comment]
Just a point as I came across with my repo. In my case I am building my website from a subdirectory of the repo. The **global.json must exist in the root of the repo**, not the site to be built.
