### ISSUE TITLE
Make ViewComponent result classes consistent with ActionResult classes

### ISSUE THREAD

**Issue by puncsky** [aspnet/Mvc#567]
The ViewComponent Result classes need to be consistent with ActionResults:

**Add public properties for testability**

**Retrieve services from the service container rather than require them to be passed in**

Classes in the folder ViewComponents, e.g.
`ContentViewComponentResult`
`ViewViewComponentResult`
`JsonViewComponentResult`
`DefaultViewComponentHelper`
`DefaultViewComponentResultHelper`
 etc. should have reachable properties for unit tests.

Follow up to #410

**Comment by yishaigalatzer** [comment]
@rynowak can you specify what exactly needs to change, so we can reassign to be executed on.

**Comment by rynowak** [comment]
@yishaigalatzer suggest closing this item. I did some work in this area not too long ago, and it seems fine now.
