### ISSUE TITLE
NullException in Microsoft.AspNetCore.Mvc.Razor.Compilation.ViewsFeatureProvider.GetViewInfoContainerType

### ISSUE THREAD

**Issue by nathannau** [aspnet/Mvc#5675]
When you load assembly from stream, Assembly.IsDynamic = false and Assembly.Location is empty (not null) so Path.GetDirectoryName(assemblyPart.Assembly.Location) return null...

So :
in file Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/ViewsFeatureProvider.cs line 61
`if (!assemblyPart.Assembly.IsDynamic && assemblyPart.Assembly.Location != null)`
must be : 
`if (!assemblyPart.Assembly.IsDynamic && !string.IsNullOrEmpty(assemblyPart.Assembly.Location))`

**Comment by pranavkm** [comment]
Would you like to send a PR for this? Here's the PR for the earlier change that added the `IsDynamic` check: https://github.com/aspnet/Mvc/commit/24d5dfb5527d46da097b56b7cfc3b28ec8f8ad3e in case you'd like to use a reference.

**Comment by Eilon** [comment]
@pranavkm feel free to fix or wait for a PR. And add a test, if possible!
