### ISSUE TITLE
Are Partial views results cached in memory? can it be controlled?

### ISSUE THREAD

**Issue by gdoron** [aspnet/Mvc#5682]
Hi,

We many (but not all) times edit a partial view but changes won't take affect until restarting the application (Ctrl+Shift+B in VS or Restart in Azure).
Is it by design? how can we disable / control it?
It's really annoying.

I experienced the same thing only once in 1.0, and now I'm working on a different 1.1 project and it happens a lot more often.

**Comment by pranavkm** [comment]
@gdoron - could you check if it's a dup of https://github.com/aspnet/Mvc/issues/5574? Using the name of a partial view as opposed to a relative path would be a workaround if it's the same issue.

**Comment by gdoron** [comment]
@pranavkm That explains why we saw it only some of the times. Thanks!

I just want to understand, what is exactly that is being cached in Views, is it the compiling of the "code behind" (not sure what's the term in MVC) class of the view?

@evgrud

**Comment by pranavkm** [comment]
> is it the compiling of the "code behind" 

Individual views get compiled to an assembly and we cache the assemblies rather than the generated code.
