### ISSUE TITLE
CodeGeneration xproj issue

### ISSUE THREAD

**Issue by Ridikk12** [aspnet/Mvc#5683]
Hi,
I have problem with xproj format.
I'm trying to write some custom scaffolding tool and i use to this Microsoft.AspNet.Scaffolding assembly.
I have to get CodeLanguage from active xproj project, but Context.ActiveProject.GetCodeLanguage() always return "unsuported".
In csproj project i dont have problem.
Maybe someone have similar problem and can help me ?

**Comment by Eilon** [comment]
The xproj file format is going away and being replaced with csproj in VS2017.

You could try asking in the https://github.com/aspnet/Tooling/issues/ repo, but given that the file format is going away, I would instead recommend looking at how to work with csproj files.
