### ISSUE TITLE
Add methods to TagBuilder to render the tags only

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#5689]
I am using a `TagBuilder` to create tags dynamically in a view. In MVC5 we could render the start and end tags independently with the same tag builder without having to render the content. If the content is part of the razor view it can't be added to the instance of the tag builder as it needs to be set with `InnerHtml`. 

A solution that I'd like would be to add two methods, `RenderStartTag()` and `RenderEndTag()`.

I have tried to use the `TagRenderMode` without success, it renders the end tag twice.
```cs
@{
    TagBuilder tag = new TagBuilder("article");
    tag.AddCssClass("big");
    tag.TagRenderMode = TagRenderMode.StartTag;
}
@tag

<div>MY CONTENT</div>

@{
    tag.TagRenderMode = TagRenderMode.EndTag;
}
@tag
```

It results in 

```html
</article>
<div>MY CONTENT</div>
</article>
```

Ideally I could just write:
```cs
@{
    TagBuilder tag = new TagBuilder("article");
    tag.AddCssClass("big");
}
@tag.RenderStartTag()

<div>MY CONTENT</div>

@tag.RenderEndTag()
```
 
Or with a syntax that would capture the razor output:
```cs
@using(TagBuilder tag = new TagBuilder("article")) 
{
    tag.AddCssClass("big");
    <div>MY CONTENT</div>
}
```

**Comment by dougbu** [comment]
@sebastienros the problem here is the `TagBuilder` reuse, specifically changing its `TagRenderMode` before it has rendered the first time. If you use two `TagBuilder`s, everything would be fine.

**Comment by sebastienros** [comment]
This is another good reason to expose specific rendering methods, that don't use the `TagRenderModel`

**Comment by Eilon** [comment]
@sebastienros - is this something you'd like to send a PR for? If not, we will close this.

**Comment by sebastienros** [comment]
Then I will, thanks.
Who should I talk to about the design?

**Comment by dougbu** [comment]
@sebastienros me

**Comment by Eilon** [comment]
Not sure how much "design" there is to do here, but I like the idea of adding `RenderStartTag()` and `RenderEndTag()` that do exactly what they say.

**Comment by sebastienros** [comment]
Not that easy after talking with @dougbu because of the bufferization. 

- We'll expose more methods representing all the available modes. `RenderStartTag`, `RenderSelfClosingTag`, `RenderBody`, `RenderEndTag`
- These methods will return a local implementation of `IHtmlContent`

**Comment by dougbu** [comment]
> These methods will return a local implementation of `IHtmlContent`

&hellip; except `RenderBody()`, that can just return `_innerHtml` 😈
