### ISSUE TITLE
Dasherized Routes

### ISSUE THREAD

**Issue by jaredcnance** [aspnet/Mvc#5691]
I'm not sure if this should go here or in the Routing repo, but I think this is more appropriate because of the initial issue. I would like routes with dasherized names (`my-entity`) to be handle just like Proper Cased names (`MyEntity`). However, I'm having trouble getting this setup.

I basically copied and pasted from [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcApplicationBuilderExtensions.cs#L64) hoping that I could just re-define the route handler:

```
public static IApplicationBuilder UseDasherizedRoutes(this IApplicationBuilder app)
        {
            if (app == null)
                throw new ArgumentNullException(nameof(app));

            // Verify if AddMvc was done before calling UseMvc
            // We use the MvcMarkerService to make sure if all the services were added.
            if (app.ApplicationServices.GetService(typeof(MvcMarkerService)) == null)
                throw new InvalidOperationException();

            var middlewarePipelineBuilder = app.ApplicationServices.GetRequiredService<MiddlewareFilterBuilder>();
            middlewarePipelineBuilder.ApplicationBuilder = app.New();

            var routes = new RouteBuilder(app)
            {
                DefaultHandler = app.ApplicationServices.GetRequiredService<DasherizedRouteHandler>(),
            };

            routes.Routes.Insert(0, AttributeRouting.CreateAttributeMegaRoute(app.ApplicationServices));

            return app.UseRouter(routes.Build());
        }
```

And in `Startup.cs` I am using

```
app.UseDasherizedRoutes();
```

with no mention of `app.UseMvc()`. However, `DasherizedRouteHandler.RouteAsync` is never called. Any ideas on what might be the issue?

**Comment by rynowak** [comment]
Attribute routing won't call the `DefaultHandler`. 

Can you describe a little more about what you're trying to accomplish? preferably with an example

**Comment by jaredcnance** [comment]
Okay, that makes sense. I would like to be able to define the route using attribute routing:
```
[Route("api/[controller]")]
public class MyEntitiesController : Controller
{
    [HttpGet]
    public IActionResult Get() {
        // ...
    }
}
```

And have the controller activated for hyphenated routes.

```
curl http://localhost:5000/api/todo-items
```

should activate the TodoItemsController.

**Comment by rynowak** [comment]
There's nothing magic about the `[controller]` token, it just does string replacement.

I'd suggest writing a convention - you can programmatically generate or modify the strings used to build the attribute routing table. https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.CustomRoutingConvention/NameSpaceRoutingConvention.cs

**Comment by jaredcnance** [comment]
Perrfect! Thanks
