### ISSUE TITLE
Image Tag (helper) displaying on the HtmlGenerationWebSite

### ISSUE THREAD

**Issue by ignatandrei** [aspnet/Mvc#5694]
The Image Tag (helper) is not displaying the images
Steps to reproduce:
1, Open the MVC.sln solution from branch rel/1.1.1
2. Go to HtmlGenerationWebSite project, set as startup
3. Run the project - it will go to `http://locahost:<port>` . Modify to `http://locahost:<port>/HtmlGeneration_Home/image`
4. Assert all images are not seeing ( red block, red versioning)
e.g. this image will not display

```html
<img src="~/images/red.png" alt="Red block" title="&lt;the title>">
```

Solution( and I will make a fork and pull request ASAP)
1. Add "
Microsoft.AspNetCore.StaticFiles": "1.1.0" 
to project,json
2. Add 
app.UseStaticFiles(); 
in the 
public void Configure(IApplicationBuilder app)
from Startup class.

**Comment by Eilon** [comment]
@dougbu any thoughts on this? Is this supposed to work? (Presumably, yes...)

**Comment by dougbu** [comment]
We don't worry too much about the end-to-end behaviour of the functional test sites. The most important thing here is that `src="~/images/red.png"` in the .cshtml results in `src="/images/red.png"` in the generated HTML.

That said, adding StaticFiles to the project has no downside.

**Comment by dougbu** [comment]
- 1840d68. Thanks very much @ignatandrei 
- tiny cleanup in cc584ad
