### ISSUE TITLE
Do something to make it easier to protect against malicious file names when processing file uploads using IFormFile

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#5696]
It would be nice if MVC did something automatically to make processing file uploads with `IFormFile` safer by default. e.g. have a filter that inspects posted file name and throws if path separator chars are found.

Consider the following code which allows a malicious file name in a file upload to be saved in a different folder via path traversal:
``` c#
[HttpPost]
public async Task<IActionResult> Upload([FromForm(Name = "data")]IFormFile file)
{
    using (var stream = file.OpenReadStream())
    {
        var path = Path.Combine(_environment.ContentRootPath, file.FileName);
        using (var output = System.IO.File.Create(path))
        {
            await stream.CopyToAsync(output);
        }
    }

    return RedirectToAction(nameof(Index));
}
```

**Comment by Eilon** [comment]
Ultimately the "problem" here is that the application is using untrusted user input, which is of course a no-no. It's no different than having a "Filename" textbox and blindly trusting that. Generally the filename used to store the data on disk would be something like a random GUID, and the original filename would be stored in a database for display purposes only. You *could* sanitize the filename (e.g. allow only A-Za-z0-9 or something like that), but that's largely an exercise in futility.

@danroth27 is going to make sure our docs reflect that `IFormFile.FileName` is not trusted and must not be used as-is to store a file.

@blowdart thoughts on this?

**Comment by blowdart** [comment]
Every time we add something like this it turns out that someone, somewhere has depended on the old behaviour. 

All the advice I've given was to use a random file name, and if you must preserve for some awful reason then you use `System.IO.Path.GetFileName()` before combining.

**Comment by rynowak** [comment]
Would it be helpful for us to build a sample of what we think is the 'right way' and clearly document exactly what the risks are?

**Comment by danroth27** [comment]
Filed https://github.com/aspnet/Docs/issues/2553 to clarify our guidance on the use of the file name property.

**Comment by rynowak** [comment]
@Eilon is there any action we want to take here? Sounds like we should just close.

**Comment by Eilon** [comment]
Yeah I think the doc update is all we need.
