### ISSUE TITLE
Simple Ajax post not working in ASP.NET MVC Core 1.1

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/Mvc#5697]
I've created a test ASP.NET Core app following this [official ASP.NET MVC Core tutorial][1]. When I click the `Test` button in the view it makes a **Ajax** call that is supposed to post the `Edit` action. But instead, I get the error shown in the image below. I've not changed any folder structure or the controller or the action name etc. Everything is exactly the same as in tutorial above. The only change is that I've added an extra **Test button** and an **Ajax** code at the end of the view. NOTE: I'm using VS2015 with all the latest updates

**Controller**:

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("ID,Genre,Price,ReleaseDate,Title")] Movie movie)
    {
        if (id != movie.ID)
        {
            return NotFound();
        }
    
        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(movie);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MovieExists(movie.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index");
        }
        return View(movie);
    }

**View** [..\views\movies\Index.cshtml]. NOTE: I've only added an extra button `<button type="button" id="testid" class="Savebtn">Test</button>
` and the `Ajax` call at the end.

    @model MovieGenreViewModel
    
    @{
        ViewData["Title"] = "Index";
    }
    
    <h2>Index</h2>
    
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <form asp-controller="Movies" asp-action="Index" method="get">
        <p>
            <select asp-for="movieGenre" asp-items="Model.genres">
                <option value="">All</option>
            </select>
    
            Title: <input type="text" name="SearchString">
            <input type="submit" value="Filter" />
        </p>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.movies[0].Genre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.movies[0].Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.movies[0].ReleaseDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.movies[0].Title)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model.movies) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReleaseDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    <button type="button" id="testid" class="Savebtn">Test</button>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>
    @section scripts
    {
        <script>
            $(document).ready(function () {
    
                $('.Savebtn').click(function () {
    
                        $.ajax({
                            url: '@Url.Action("Edit", "Movies")',
                            data: "Test data",
                            type: 'POST', //POST if you want to save, GET if you want to fetch data from server
                            success: function (obj) {
                                // here comes your response after calling the server
                                alert('Suceeded');
                            },
                            error: function (obj) {
                                alert('Something happened');
                            }
                        });
                });
            });
        </script>
    }

**Error [in Google Chrome developer tool when Test button is clicked to make an Ajax call]**:

![capture](https://cloud.githubusercontent.com/assets/10931726/22075570/7fd3f170-dd7a-11e6-8dfc-a861913a8a96.PNG)

  [1]: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model
  [2]: https://i.stack.imgur.com/lklZ4.png

**Comment by NRKirby** [comment]
Can you provide a link to a repo for the project you're working from?

**Comment by saf-itpro** [comment]
I found the error. You have to have the same input parameters in Ajax data attribute that you have in Controller action you are calling.. For example, if you have controller action **Edit(int id, string myParam){...}** you also need to have data attribute value in Ajax as **data: {id: 123, myParam: "Test data"}**

**Comment by saf-itpro** [comment]
@NRKirby Thank you for looking into the issue. I've found the error as explained in my previous comment above.

**Comment by NRKirby** [comment]
No problem - have you considered using [StackOverFlow](http://stackoverflow.com/) for questions like this?
