### ISSUE TITLE
Injecting IHostingEnvironment into IDatabaseInitializer

### ISSUE THREAD

**Issue by thiagomajesk** [aspnet/Mvc#5700]
Hi you all! 

I'm trying to seed my database by reading some json files. So I need to get access to `IHostingEnvironment.ContentRootPath` for that. The thing is that I can't inject the `IHostingEnvironment` because aparently `DbConfiguration` must have a parameterless constructor.

```c#
/*
* Database Context
*/
[DbConfigurationType(typeof(DatabaseConfiguration))]
public class DatabaseContext : DbContext
{
    public DbSet<User> Users { get; set; }

    public DatabaseContext(string nameOrConnectionString) : base(nameOrConnectionString) {   }

   /*public DatabaseContext(IHostingEnvironment  env, string nameOrConnectionString) : base(nameOrConnectionString)
   {
        // Tried to receive to flow IHostingEnvironment from Startup intead of
       // [DbConfigurationType(typeof(DatabaseConfiguration))]
        DatabaseConfiguration.SetConfiguration(new DatabaseConfiguration(env))
    }*/

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
         modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
         base.OnModelCreating(modelBuilder);
    }
}
```

```c#
/*
* Database Configuration
*/
public class DatabaseConfiguration : DbConfiguration
{
    // Can't receive injected IHostingEnvironment env because constructor must be parameterless
    public DatabaseConfiguration()
    {
        SetProviderServices("System.Data.SqlClient", SqlProviderServices.Instance);

        // Could pass IHostingEnvironment through constructor
        SetDatabaseInitializer(new DatabaseInitializer()); 
    }
}
```

```c#
/*
* Database Initializer
*/
public class DatabaseInitializer : DropCreateDatabaseAlways<DatabaseContext>
{
    private readonly IHostingEnvironment env;

    // Receives IHostingEnvironment from DatabaseConfiguration
    public DatabaseInitializer(IHostingEnvironment env)
    {
        this.env = env;
    }

    protected override void Seed(DatabaseContext context)
    {
        // Read some .json files
    }
}
```

I stumbled into another issue related here: https://github.com/aspnet/Hosting/issues/429. And I have to say that I can see the need to access `IHostingEnvironment` in other places, so we probably should make that simpler. 

I don't know if it is just me but, another thing that comes to mind is how we have to configure our projects today. The `Startup()`, `ConfigureServices()` and `Configure()`  structure seem a little bit "messy".
Sometimes I feel envy of the simplicity of the old plane `Application_Start()` (http://pastebin.com/1i4pj7g3). 

Troubles me that I have to know how ASPNET handles things "behind the scenes"; that I have to know that I have to declare my routes after registering mvc or configuring services or providers "x" and "y" in the right order because of the container. I think this process should be more streamlined and we should be able to configure our solution not caring about how the wires are connected behind the scenes.

I know of course, that a lot of things are by design, but I know too that simplification would make our lifes a lot better (see the aftermentioned example of old ASPNET MVC).

**Comment by pranavkm** [comment]
cc @divega for the `DbConfiguration` question.

**Comment by divega** [comment]
EF6 was obviously designed before ASP.NET Core and EF Core and although it uses some of it own limited DI mechanisms, it had to support behaviors from previous versions of EF which didn't have any DI concepts. As a consequence there are global root objects that cache configuration under the hood. E.g. `DbConfiguration` Is never instantiated in user code, but rather created and cached automatically by EF. Since the `DbConfiguration` is the place where services are are configured, there are no means in EF6 to inject any services into it.

The somewhat good news (if you need to use EF6 and cannot use EF Core) is that you can also set database initializers outside of the `DbConfiguration` constructor, e.g. a call to `Database.SetInitializer<DatabaseContext>(Initializer)` anywhere you can resolve services but before the context is used should probably help.

**Comment by thiagomajesk** [comment]
@divega Thanks for the helpfull explanation. I'm now invoking `DatabaseConfiguration.SetConfiguration(new DatabaseConfiguration(env))` into `Startup` ctor and flowing down the `IHostingEnvironment` to the the database initializer. 
But I have to confess that doing this on the ctor or even in `Configure` seems a bit ugly. 
I'd really like to use EF Core, but right now I think it's not a mature technology.
