### ISSUE TITLE
Parameter not set if passing multiple parameter int post

### ISSUE THREAD

**Issue by mRy0** [aspnet/Mvc#5702]
When posting to a controller with multiple parameter in the route, some parameter are not set.
I need to post data to a controller with two ids (n*n relation) and only getting the second parameter, the first is -1.
In the Route data of the Controller context all parameter are parsed fine.

Example:
Posting data to the controller with "/api/controller/42/method/1337/data"
```
 [HttpPost]
        [Route("api/controller/{idone}/method/{idtwo}/data")]
        public IActionResult AddDataToMethod(int idone, int idtwo, PostObject postData)
        {
            // idone will be -1

            //this works fine
            idone = int.Parse(ControllerContext.RouteData.Values["idone"].ToString());
```

The same method as HttpGet works fine
```
 [HttpGet]
        [Route("api/controller/{idone}/method/{idtwo}/data")]
        public IActionResult AddDataToMethod(int idone, int idtwo)
        {
            // idone will be 42

```

**Comment by rynowak** [comment]
Is another part of the request also sending a value for `idone`? (form data, query string) A form value would be used first if provided. 

If you want the value to specifically come from the route data use `[FromRoute]` on the parameter.

**Comment by Eilon** [comment]
Yeah it definitely sounds like there's a form body that also has some value for `idone`.

**Comment by mRy0** [comment]
... Ohh yes
In my example I call it "idone" for better explanation, but in real its called  "id" and in the object is a property called "Id".

I thought the post json-object would be handled in an other way as the parameters.

What will be the best practice for naming properties and parameters with same names like "id"?

**Comment by Eilon** [comment]
@mRy0 you can use the attributes that @rynowak mentioned, such as `[FromRoute]`,  `[FromQuery]`, etc. That will force the system to get the values from only that location without any fallbacks.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
