### ISSUE TITLE
EditorTemplate templates in a separate assembly

### ISSUE THREAD

**Issue by svallis** [aspnet/Mvc#5703]
Is it possible (or planned to be possible) to configure an ASP.NET Core web application to use `EditorTemplate` razor pages that are compiled into a class library/separate assembly? I've tried asking this on SO but didn't get any responses.

**Comment by Eilon** [comment]
@pranavkm @javiercn - can you use Application Parts w/ Pre-compiled views to do this? Presumably it should work, right?

@svallis can you share a link to your StackOverflow question so that we can make sure the answer appears in both places?

**Comment by svallis** [comment]
I've seen Application Parts mentioned, but always in reference to systems with both classes and razor views (e.g. Controllers and Actions, ViewComponents). If it is possible with EditorTemplate razor views, is everything based around directory structure only, or is explicit "registration" of the views required?

@Eilon http://stackoverflow.com/questions/41704188/editortemplate-templates-in-a-separate-assembly

**Comment by Eilon** [comment]
@svallis thanks, we'll have a look and get back to you.

**Comment by javiercn** [comment]
@Eilon I can't foresee any reason why it would not work. They are just "regular" views in a different folder location. Whatever works for views/partials should work for editor templates.

**Comment by svallis** [comment]
@javiercn Any idea what I might be missing beyond the following, which doesn't seem to be working for me at the moment?

- get a reference to the class module (through a random class within the component) and register it with a call to `.AddApplicationPart(library)` within `ConfigureServices()` of the main web application's `Startup.cs`
- added razor views to a `Views\Shared\EditorTemplates` folder within the class module's folder structure
- added the following to the the class module's `project.json`:
```
"buildOptions": {
  "embed": "Views/**"
}
```

The web application and class module are both v1.1.0.

**Comment by pranavkm** [comment]
@svallis - adding an `ApplicationPart` does not add it as a source for embedded views as yet (this was one of @davidfowl's feature requests we never got around to). You have to add it to the list of file providers in `RazorViewEngineOptions`. See https://github.com/aspnet/Mvc/blob/cfa9631ce80edbb78c821cba88e50a085035eacc/test/WebSites/RazorWebSite/Startup.cs#L27-L29

**Comment by svallis** [comment]
Spot on, thank you @pranavkm! I have written up what I required and answered my own SO question [here](http://stackoverflow.com/questions/41704188/editortemplate-templates-in-a-separate-assembly/41825072#41825072).
