### ISSUE TITLE
ViewComponent User Perspective [Comment]

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Mvc#5704]
I think the overall direction and work of MVC Core is great, but I'm really struggling with the entire ViewComponent approach. In my mind, I looked to VC's to be lightweight "components" that I could easily build, reuse, and extend. I'm not finding that to be the case. They seem cumbersome and restrictive. Am I missing the concept?

For what it is worth, I wanted to share a walk-though of how I tried to build a ViewComponent.

A basic scenario I thought would fit VC's was something like a search form. I could build the basic html, wrap it in some C# logic, and reuse it in my pages. Like other MVC things I would be able to relocate the files using ViewLocationExpanders, and overload it.  In this example, the "overloading" is the common case where I need an instance of an object to restrict my search parameters, and I what I have may be an instance or id. Since I have C# available I can take either, and have my instance. My first surprise was I couldn't overload Invoke - "must have exactly one public method named 'InvokeAsync' or 'Invoke'". 

OK, I'll create another VC to handle that, even though now I have to call two separate components to get a single result. I'll put them in the same folder, so they can share the partial view. Surprise two - hard pathing. VC's are always sticking "Component/[ComponentName]" in my search path. (Fascists! :)) I have problems here, (beyond the overall hard-path nature). Trivial is "Component". All of my "components" aren't ViewComponents. If you are going to steal a path segment, take the more specific - use ViewComponent. This is minor, but annoying.

The larger problem is folder bloat. I started out to create a simple reusable component. Since the component name is forced into the path, I have to create a new folder for my "overload". It feels like having to create a new class file every time I want to overload a constructor. I'm not happy, but hey, reuse... Or maybe not. That little piece of html I wanted to wrap and reuse? My VC is going to look for it in the component name folder unless I give it a full path. (And, it's going to look for "default". ??? - if everything else if bound to names, it should default to [ComponentName].cshtml). So now I need to decide if I am going to duplicate my "reuseable" in each folder, or make one folder the "master" and hard code all of the "overloads" (I may have more then one) to go there.

The need for multiple folders for a single function now brings up the need for naming strategies. I can't really group my folders with something like Components/Search/[ComponentOverloadName] because of the hard pathing. So I end up with series of components (and folders) all directly under Components - like Components/Search, Components/SearchWithInstance, Components/SearchWithId, etc.). (TotalFolders = Sum(Component.Sum(Overloads))).

Anyway, that is my user experience with ViewComponents based on how I "expected" them to work. I may have the wrong expectation, or be approaching this incorrectly. What I hoped would be two files, and a single, reusable, relocate-able, convention-based component, ended up being a handful of folders and files with the need to replicate my html, or use hard-coded view paths, and not conventions.

**Comment by Eilon** [comment]
Thank you for the feedback; we are considering some improvements and changes to View Components and will consider your feedback.

**Comment by Sonnenuntergang** [comment]
Yes, it will be convenient to make 'Invoke()' method overloadable. So when will it be true?
