### ISSUE TITLE
Malformed header causes infinite loop and never processes that request 

### ISSUE THREAD

**Issue by tomhreb** [aspnet/Mvc#5707]
GET (for example) request with malformed header causes the process to go into infinite loop, causing high CPU usage and never gets into actually processing the request.

_@blowdart: Sample header removed as not everyone will upgrade_

**Comment by blowdart** [comment]
_Removed as potential security bug. Investigation started._

**Comment by blowdart** [comment]
Investigation completed. 

Security Advisory issued : https://github.com/aspnet/Mvc/issues/5726

Fixed in 1.1.1

**Comment by rynowak** [comment]
Fixed by https://github.com/aspnet/Mvc/commit/5885feb7c01014236503b52dbd2aa6e84c0f32a9
