### ISSUE TITLE
Discussion: Removed obsolete DefaultHtmlGenerator constructor

### ISSUE THREAD

**Issue by jbagga** [aspnet/Mvc#5716]
Removed legacy constructor for `DefaultHtmlGenerator` and the `ClientValidatorCache` parameter from the new constructor

See announcement https://github.com/aspnet/Announcements/issues/215

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
