### ISSUE TITLE
Error while creating new ASP.NET Web Application

### ISSUE THREAD

**Issue by nmistry096** [aspnet/Mvc#5717]
Visual Studio 2015

1. New Project
2. Web -> ASP.NET Web Application
3. Click Ok

By doing above steps it gives me error like below snapshot

![image](https://cloud.githubusercontent.com/assets/11497594/22324237/1fa94d36-e3ce-11e6-9961-e7f50f7b59a2.png)

**Comment by Eilon** [comment]
cc @barrytang @mlorbetske

**Comment by Eilon** [comment]
This issue was moved to aspnet/Tooling#972
