### ISSUE TITLE
Taghelper - Images serialize to base64 encoding directly into html

### ISSUE THREAD

**Issue by ignatandrei** [aspnet/Mvc#5729]
I want to be able to serialize images directly to web page .
One possible use : send the file over email ( or directly as html) and not have the issue to download images from a webserver.
For this we can use  https://en.wikipedia.org/wiki/Data_URI_scheme - base 64 encoding of images.

My proposal is a tag helper asp-append-base64
e.g.
 &lt;img src="~/images/red.png" alt="Red versioned" title="Red versioned" asp-append-base64="true" /&gt;

I will submit a pull request for this ASAP.

**Comment by Eilon** [comment]
Hi @ignatandrei thank you for logging the suggestion and sending the PR. This doesn't currently align with our release plans, so we are putting this issue in the backlog and closing the PR.

If you end up releasing the tag helper as your own package on NuGet.org, we'd be happy to add a link to it from the readme of this repo.

**Comment by ignatandrei** [comment]
Thank you for the comment , @Eilon 
I have created NuGet for .NET Framework 4x , but not for .NET core.

Do you have any recommended way to create this kind of packages for .NET Core?  ( a blog post link / an msdn link?)

**Comment by Eilon** [comment]
@ignatandrei it's actually quite easy! In fact, it's hard *not* to make a package when working with .NET Core because every project by default creates a NuGet package!

**Comment by Eilon** [comment]
@ignatandrei to produce a NuGet package from your project, go to the command line, navigate to the folder of the project, and type `dotnet pack -c Release`. This will generate a "release" build of your NuGet package (and it will tell you where on disk the package was created).

**Comment by ignatandrei** [comment]
Nice. Thank you. I will put sources on github and I will update the thread.

**Comment by ignatandrei** [comment]
https://www.nuget.org/packages/AspNetCore.Mvc.ImageBase64 and source at https://github.com/ignatandrei/AspNetCoreImageTagHelper

And yes, I like that my little extensions to be added in the readme of this repo ;-)

**Comment by Eilon** [comment]
@ignatandrei I added a link, check it out. Thanks!

**Comment by ignatandrei** [comment]
Thank you!

**Comment by ryanelian** [comment]
This is gold. This should be included into the framework IMHO.
