### ISSUE TITLE
Change class-name generation for compatibility to View Compilation

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5736]
MVC is generating class names like `AspNetCore.Generated_Index` instead of names like `AspNetCore._Views_Home_Index_cshtml`. We need to use more than just the file name for generating the class name because you will end up with a lot of conflicts in view compilation.

We need to fix this and then re-enable any disabled tests in the view compilation repo.

**Comment by pranavkm** [comment]
Fixed using https://github.com/aspnet/Mvc/commit/eb820106e2e4869d952388f0cebc49c497dafa7c
