### ISSUE TITLE
Detected package downgrade: Microsoft.AspNetCore.Mvc from 0.0.0 to 1.0.1 

### ISSUE THREAD

**Issue by nukec** [aspnet/Mvc#5744]
When I add FluentValidation.AspNetCore dependency in my project.json file I get this error on restore, and can't hit into controllers while debugging:

```
Detected package downgrade: Microsoft.AspNetCore.Mvc from 0.0.0 to 1.0.1 
warn :  Project.API.Tests (>= 1.0.0) -> Project.API (>= 1.0.0) -> Project.Business (>= 1.0.0) -> FluentValidation.AspNetCore (>= 6.4.0-rc2) -> Microsoft.AspNetCore.Mvc  
warn :  Project.API.Tests (>= 1.0.0) -> Project.API (>= 1.0.0) -> Microsoft.AspNetCore.Mvc (>= 1.0.1)
```

When I remove FluentValidation.AspNetCore dependecy everything works.

Project.json:

```json
{
  "version": "1.0.0-*",

  "dependencies": {
    "Project.DAL": "1.0.0-*",
    "FluentValidation.AspNetCore": "6.4.0-rc2",
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "AutoMapper.Extensions.Microsoft.DependencyInjection": "1.1.2"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  }
}
```

Api project.json dependencies:

```json
"dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "StructureMap.Microsoft.DependencyInjection": "1.2.0",
    "AutoMapper": "5.1.1",
    "Project.Business": "1.0.0-*",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  }
```

net core sdk is 1.0.3

```json
{
  "projects": [ "src" ],
  "sdk": {
    "version": "1.0.0-preview2-003156"
  }
}
```

**Comment by davidfowl** [comment]
You need to report an issue on **FluentValidation.AspNetCore** to specify a package version of the  **Microsoft.AspNetCore.Mvc** dependency. 

/cc @JeremySkinner

**Comment by JeremySkinner** [comment]
I'll try and get that done today. Weird it didn't come up in any of my testing.

**Comment by nukec** [comment]
I tried with lower beta versions, same issue.

**Comment by JeremySkinner** [comment]
@nukec You need to upgrade to Microsoft.AspNetCore.Mvc 1.1 to use FV's aspnetcore integration, but this isn't flagged up as the FV.AspNetCore package doesn't explicitly specify that it needs MVC 1.1, as @davidfowl  said.

I've created an issue for this over on the FV issues list, feel free to continue the conversation over there.
https://github.com/JeremySkinner/FluentValidation/issues/394

**Comment by nukec** [comment]
I just created new net.core project and added fluent validation in it and same error:

> warn : Detected package downgrade: Microsoft.AspNetCore.Mvc from 0.0.0 to 1.0.1 
> warn :  WebApplication2-Test (>= 1.0.0) -> FluentValidation.AspNetCore (>= 6.4.0-beta3) -> Microsoft.AspNetCore.Mvc

**Comment by JeremySkinner** [comment]
@nukec I've not pushed out the change yet....as I said, I'll try and do it later today. Thanks for your patience.

**Comment by nukec** [comment]
Cool changed version and error is still there, but controller is hit and i guess works. thanks @JeremySkinner

**Comment by emgarten** [comment]
> @emgarten That error message is broken. It's detecting a downgrade from 0.0.0 (null) to 1.1.0

This is a known issue, it should be fixed in the current dotnet CLI.
