### ISSUE TITLE
Roslyn special warmup to improve F5 scenario performance

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#5746]
_From @Yves57 on December 29, 2016 11:14_

On my (old) computer, the startup (with Visual Studio 2017 RC debugger) of a basic Web Application (created with the wizard) takes about 8800ms between the F5 click and the end of HTML page loading.

Just for fun, I tested an stupid idea: because a long time of the start in single-threaded and because Roslyn warmup takes a long time, it could save time to compile and empty assembly in a separate thread, just to load Rosyln assemblies "in background".

So I modified the `Startup` class on a wizard-created Web Application like that:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    RoslynWarmup();

    ......
    app.UseMvc(..........);
    ......
}

private void RoslynWarmup()
{
    Task.Run(() =>
    {
        var source = "namespace Foo { public class Bar { } }";
        var sourceText = SourceText.From(source);
        .....
        // Roslyn assembly build
    }
}
```

The result are the following:
Step | Without warmup | With warmup
---- | -------------- | -----------
Action execution time | ~3400ms | ~2500ms
Request finishing time | ~3880ms | ~3080ms
F5 to HTML loading time | ~8800ms | ~8200ms

The idea is a dirty hack, but I don't know if there is a better idea in your pipe (I hope there is there is one!).

_Copied from original issue: aspnet/Razor#918_

**Comment by rynowak** [comment]
Tracking this work here - https://github.com/aspnet/Razor/issues/1739 we do plan to do this for 2.1
