### ISSUE TITLE
DateTime validation

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#575]
Need to followup on DateTime client validation behavior. We decided not to fix for MVC5.2, but we should follow up here.

Here is a link to the original bug - https://aspnetwebstack.codeplex.com/workitem/1503

**Comment by yishaigalatzer** [comment]
@DamianEdwards can you help drive the design for this?

**Comment by DamianEdwards** [comment]
I think we should re-triage this.

**Comment by rynowak** [comment]
This seems like something we should just close, or track alongside other feedback about client side validation. 

There's good info in the original bug, but a fix for this would require pulling in additional jquery plugins. I think we'd only address this if we end up replacing our client validation package.

**Comment by DamianEdwards** [comment]
Yeah date validation is still tricky. Agreed it really requires a larger change to address in any real way.

**Comment by rynowak** [comment]
Great, I've added this to #4888 - we'll use that to track this
