### ISSUE TITLE
ASP.NET MVC Core 1.1.0 - View with a for loop is not correctly assigning id property for @Html.HiddenFor

### ISSUE THREAD

**Issue by fjrodriguezcom** [aspnet/Mvc#5753]
I have a for in the view
`@for (int i = 0; i < Model.ListOfElements.Count; i++)`
and 
`@Html.HiddenFor(model => Model.ListOfElements[i].PropertyA)`

is always rendering as 
`<input type="hidden" id="PropertyA" name="PropertyA" value="X">`

same for 
 `<input asp-for="@Model.ListOfElements.PropertyA" type="hidden" />`

Any help is appreciated

**Comment by frankabbruzzese** [comment]
How is declared ListOfElements in your ViewModel? 
List, ICollection or IEnumerable?

**Comment by ruchanb** [comment]
I think this is the same issue being tracked in [#5655](https://github.com/aspnet/Mvc/issues/5655)

**Comment by dougbu** [comment]
To confirm this is the same as #5655, @fjrodriguezcom are you using something like `Model.ListOfElements.FirstOrDefault().PropertyA` elsewhere in your views?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
