### ISSUE TITLE
ASP.Net Core support for ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by mne1991** [aspnet/Mvc#5755]
Hello,

I want to ask if we are going to get ASP.Net Core support for ARM soon? Because I tried to run a very simple asp.net core web app on my RPi3, but with no success (although .Net core could successfully start a simple hello world console app!). Thank's!

I opened a question about that here:

http://stackoverflow.com/questions/42054399/error-in-running-asp-net-web-app-on-arm-processor-raspberry-pi-3-b-ubuntu-n

**Comment by crozone** [comment]
Your best bet is to follow the instructions here:

https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

However IIRC .NET Core is still being brought up on ARM. The JIT and runtime still aren't 100% and you may hit bugs.

**Comment by mne1991** [comment]
I found the solution, he is is:

https://github.com/dotnet/coreclr/issues/9168#issuecomment-277846829

**Comment by Eilon** [comment]
All of ASP.NET Core itself is managed code, so it is fully platform-independent. The few platform-specific components are Libuv (which is used by the Kestrel web server), and then many components of .NET itself, most of which is covered by https://github.com/dotnet/coreclr.
