### ISSUE TITLE
Consider adding a way to use strict comparison for routes matching

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Mvc#5757]
http://stackoverflow.com/questions/42048770/asp-net-core-openiddict-throws-an-openid-connect-response-cannot-be-returned-fr

Consider this action:

```csharp
[HttpPost("~/path")]
public IActionResult Test() => Empty();
```

Oddly, either the routing stack or MVC seems to consider `/path/` requests as valid candidates for this route/action, which is incorrect as `/path` and `/path/` are two different addresses.

Is there any particular reason for this (abusive) normalization?

/cc @Eilon @rynowak

**Comment by PinpointTownes** [comment]
> Is there any particular reason for this (abusive) normalization?

After some research, it looks like it matches what ASP.NET MVC and Web API used to do (but not WCF Web API, AFAICT), so I guess it's one of those "by design" decisions.

Unfortunately, this behavior makes the routing stack pretty much inconsistent with the rest of ASP.NET Core, where path comparisons are case-sensitive and take the trailing slash into account (e.g all the security middleware).

Since changing this behavior at this point is very unlikely, would you consider adding new semantics to enable strict comparisons? E.g:

```csharp
[HttpPost("~/path", Strict = true)]
public IActionResult Test() => Empty();
```

**Comment by Eilon** [comment]
This issue was moved to aspnet/Routing#380
