### ISSUE TITLE
Anonymous ID in dotnet core

### ISSUE THREAD

**Issue by hxq1988** [aspnet/Mvc#5758]
Can you please let me know how to get Anonymous ID in .net core mvc. In Asp.net MVC 4 i can use Request.AnonymousID but I don't known how to get it in .net core.

**Comment by davidfowl** [comment]
There's no equivalent of Request.AnonymousID in ASP.NET Core. There is no port of the anonymousIdentification feature. You'd have to write your own middleware to do this.

**Comment by aleripe** [comment]
I coded a solution on my own. It is a middleware for ASP.NET Core that mimics the old behavior.

You can find the package on NuGet as [AnonymousId (ReturnTrue.AspNetCore.Identity.Anonymous)](https://www.nuget.org/packages/ReturnTrue.AspNetCore.Identity.Anonymous) and the source code on [GitHub](https://github.com/aleripe/AnonymousId).

I'm new to the whole world of ASP.NET Core so please let me know of any bug, improvement, advice, correction...

The basic usage is:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    app.UseAnonymousId();
    ....
}
```

**Comment by Ponant** [comment]
@davidfowl , could you hint on a secure alternative or explain why there is no port of Request.AnonymousID in .Net Core?

**Comment by davidfowl** [comment]
It's not intrinsic to http so we don't want to bake anything like this into the httpcontext in asp.net core. That said, it should be a separate middleware that expose the anonymous ID as an http feature. That's one improvement that could be made to @aleripe's middleware. 

We haven't seen much demand for it in asp.net core so it hasn't been a priority.

**Comment by aleripe** [comment]
@davidfowl Can you please explain how it could be improved? I am very interested about it!

**Comment by Ponant** [comment]
@davidfowl , but it seems to be quite invoked when dealing with shopping carts and the like. I am looking at secure ways to be dealing with this kind of flow, any hint?

**Comment by aleripe** [comment]
OK, I integrated the AnonymousId generation with ASP.NET core request features.
Code to get value now is:

```
public class HomeController : Controller
{
  public ViewResult Index()
  {
      IAnonymousIdFeature feature = HttpContext.Features.Get<IAnonymousIdFeature>();
      if (feature != null)
      {
        string anonymousId = feature.AnonymousId;
      }
      ....
  }
}
```

Hope I did everything properly... :-)
