### ISSUE TITLE
Complex model binding doesn't work on POST but works with JSON.NET

### ISSUE THREAD

**Issue by gdoron** [aspnet/Mvc#5760]
Given this request POST:

	VariationRows:[{"price":"11","sku":"SKU1","combinations":{"color":"Red","size":"S"}},{"price":"22.22","sku":"","combinations":{"color":"Blue","size":"S"}},{"price":"","sku":"","combinations":{"color":"Green","size":"M"}},{"price":"55","sku":"","combinations":{"color":"Red","size":"L"}}]
	
![Full request](https://cloud.githubusercontent.com/assets/6141009/22709794/be582380-ed83-11e6-8042-8cca78b6afd7.png)
And model:

    public class CreateProductModel
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }

        [DisplayName("Vendor UPC")]
        public string Upc { get; set; }

        [Required]
        [DisplayName("Product name")]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        public decimal? Price { get; set; }

        public decimal? Discount { get; set; }

        [DisplayName("Sold on site?")]
        public bool IsSoldOnSite { get; set; }

        [Required]
        public string Url { get; set; }
        [DisplayName("Product brand")]
        public string Brand { get; set; }
        public string BrandLogoUrl { get; set; }

        public string YouTubeId { get; set; }
        public List<int> Categories { get; set; }
        public int MainCategoryId { get; set; }
        public List<int> Limitations { get; set; }
        public List<string> Images { get; set; }
        public Dictionary<int, string> LimitationsOptions { get; set; }

        public Dictionary<string, Dictionary<int, string>> CategoriesOptions { get; set; }
        public List<JsonVariationRowModel> VariationRows { get; set; }
	}
    public class JsonVariationRowModel
    {
        public Dictionary<string, string> Combinations { get; set; }
        public decimal? Price { get; set; }
        public string Sku { get; set; }

        public JsonVariationRowModel()
        {
            Combinations = new Dictionary<string, string>();
        }
    }

The model binding doesn't work for VariationRows, it's empty.

But when using JSON.NET directly:

	var obj = JsonConvert.DeserializeObject<List<JsonVariationRowModel>>(
                    "[{\"price\":\"11\",\"sku\":\"SKU1\",\"combinations\":{\"color\":\"Red\",\"size\":\"S\"}},{\"price\":\"22.22\",\"sku\":\"\",\"combinations\":{\"color\":\"Blue\",\"size\":\"S\"}},{\"price\":\"\",\"sku\":\"\",\"combinations\":{\"color\":\"Green\",\"size\":\"M\"}},{\"price\":\"55\",\"sku\":\"\",\"combinations\":{\"color\":\"Red\",\"size\":\"L\"}}]",
                    new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() });
                    
It manages to bind just fine.

Is this a bug or is it something that we do wrong?

**Comment by gdoron** [comment]
Well I think something isn't right with serializing Dictionaries in ASP.NET Core.
Another thing we tried today which failed for some reason:


Posting this:

`variations:{"51":2308}`

Expecting to get it in the controller with:

`Dictionary<int, int> variations`
Or
`Dictionary<string, int> variations`

Failed.

This succeeded: 

	Dictionary<int, int> variations = JsonConvert.DeserializeObject<Dictionary<int, int>>(Request.Form["variations"]);
	
@rynowak Is it related to something like #5123 which we discussed?

**Comment by rynowak** [comment]
The model binding system doesn't expect JSON data to show up in a form field. I'd suggest writing your own model binder for this case.

**Comment by gdoron** [comment]
@rynowak I see.
Is there a way of sending the data to a `Dictionary` on the server? If not, is it by design?

Can you please point me to somewhere explaining how to write a ModelBinder in Core?

Thanks a ton Ryan!

**Comment by rynowak** [comment]
@dougbu do we have docs on this somewhere?

**Comment by dougbu** [comment]
@rynowak sorry, I haven't memorized the model binding documentation 😈 But, in a quick check of https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding I see we don't cover custom model binders. Looks like all we've got is samples and links to those samples from various issues and questions on GitHub. Suggest you file a docs issue @rynowak 🥇

**Comment by rynowak** [comment]
@gdoron - this old blog post goes into detail about how we treat form values for a dictionary http://www.hanselman.com/blog/ASPNETWireFormatForModelBindingToArraysListsCollectionsDictionaries.aspx

If you're able to transform your data on the client from JSON into form data, that will do the trick.

-----------

If you decide instead to do this on the server side by writing a model binder, there are some examples in this issue: https://github.com/aspnet/Mvc/issues/4477

Start by writing a class that implements `IModelBinder`. In here you'll want to call the value providers with `bindingContext.ModelName`, this is equivalent to the your example above with `Request.Form["variations"])` but without hardcoding the name `variations`.

Then you'll want to JSON deserialize the text into your objects and set `bindingContext.Model`.

Lastly you'll want to use `[ModelBinder(typeof(MyModelBinder))]` attribute to attach your custom model binder to the property.

**Comment by gdoron** [comment]
Do you want me to close the issue?
Thanks.

**Comment by frankabbruzzese** [comment]
@gdoron ,
If you submit data via JQuery.ajax with a post and you don't specify mime type being json. jQuery automatically transforms json data into form data,...However, not sure, dictonary format is compatible with asp.net mvc model binder(I suppose it is not!).

Anyway, it is quite easy writing a model binder thtat is able to deserialize json string contained, say, in an hidden field (or any other form field).

You should mimic the built-in simple type model binder. Give a look to [this post](http://www.dotnet-programming.com/post/2017/02/22/Custom-Model-Binding-in-Aspnet-Core-2-Getting-Time-2b-Client-Time-Zone-Offset.aspx) of my blog that gives an example on how to do it. Obviously, you should substitute the logics of the example with a call to the Json.net deserializer.

**Comment by gdoron** [comment]
@FrankPeschel-Gallee Thanks for the reading, yeah it should be simple.
But since I needed this binder only on one place and I'm horrifically busy and lazy (mainly lazy), I ended up doing it on the controller and saved me all the hassle of creating a model binder 😞 .

Thanks.

**Comment by rynowak** [comment]
Closing since this was answered
