### ISSUE TITLE
MVC Vs WebAPI routing difference

### ISSUE THREAD

**Issue by avikenjale** [aspnet/Mvc#5762]
This issue might be raised earlier hence can be duplicate.

When we configure ASP.NET core app (MVC) we define and map routes under Startup.cs - Configure - `app.useMvc()`. And this works perfectly. 
However,  when WebAPI comes into picture, why we need to specify `[Route("api/[controller]")`  specifically?  In other way, webAPI only works with attribute routing?

Why can't Configure method handles this route configuration? Which was good option in earlier MVC/WebAPI (not core). 

Am I missing anything?

**Comment by SilverioMiranda** [comment]
You need to define a base route for your controller, and actions can use  HttpGet,HttpPost or others. This is the way how Router works

As you can see in 

> Note the presence of [controller] on line 8. Attribute-based routing now supports certain tokens, such as [controller] and [action]. These tokens are replaced at runtime with the name of the controller or action, respectively, to which the attribute has been applied. This serves to reduce the number of magic strings in the project, and it ensures the routes will be kept synchronized with their corresponding controllers and actions when automatic rename refactorings are applied.

Documentation : [https://docs.microsoft.com/en-us/aspnet/core/migration/webapi](https://docs.microsoft.com/en-us/aspnet/core/migration/webapi)
