### ISSUE TITLE
Model Binding 'N' Number of Dynamic Query Parameters

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#5770]
I have the following scenario where the following action can accept 'N' number of query parameters with a non-predetermined name and value i.e. I have no idea what query parameters someone might pass in.

```
[HttpGet("foo")]
public Task<IActionResult> Foo([FromQuery] string firstParameter)
{
    var remainingDynamicParameters = 
        this.Request.Query.ToDictionary(x => x.Key, x => x.Value.ToString());
    
    // Do Something
}
```

It would be nice if the model binder could bind these parameters to a `IDictionary<string, StringValues>` or `IDictionary<string, string>` like so:

```
[HttpGet("foo")]
public Task<IActionResult> Foo(
    [FromQuery] string firstParameter, 
    [FromQuery] IDictionary<string, StringValues> dynamicParameters)
{
    // Do Something
}
```

**Comment by dougbu** [comment]
You probably don't want model binding at all. Suggest using `HttpContext.Request.Query` directly.

**Comment by Eilon** [comment]
Closing because there are no plans to make further improvements in this area.

I would probably just use a nice-looking fancy-pants LINQ statement to do this...
