### ISSUE TITLE
Web api - conventional routing instead of attribute routing

### ISSUE THREAD

**Issue by lszomoru** [aspnet/Mvc#5772]
At the moment the Web Api project template contains a ValuesController which uses the following attribute for routing - [Route("api/[controller]")]. For prototyping purposes, I was trying to get rid of this attribute route and replace it with a MapRoute call in Startup.cs without much luck. The following code does match the first "Get" action, but not the others. 

```
routes.MapRoute(
    name: "default",
    template: "api/{controller}/{action}",
    defaults: new { action = "Get" });
```

Any help would be highly appreciated. Thanks!

**Comment by lszomoru** [comment]
Closing this issue here as it has been answered in the "routing" repo.

**Comment by Edward-Zhou** [comment]
@lszomoru Hi, I am also interested in this issue, could you share me how to achieve center routing in asp.net core web api? I want to make below code work in asp.net core.
`routes.MapRoute(
    name: "default",
    template: "api/{controller}/{action}",
    defaults: new { action = "Get" });`
