### ISSUE TITLE
asp-fallback-src is not valid code for Content Security Policy (CSP)

### ISSUE THREAD

**Issue by jaider** [aspnet/Mvc#5778]
I have a code like this:
 ```
<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
```
Even though I accept the self and cdn scripts `script-src 'self' ajax.aspnetcdn.com`, the code generated is not valid CSP and never will be executed.
It would be nice if the generated code is cleaner and approved by CSP.

![image](https://cloud.githubusercontent.com/assets/1471688/22816083/be0be352-ef2d-11e6-9b0c-87290dd7bc07.png)

https://developer.chrome.com/extensions/contentSecurityPolicy
https://www.w3.org/TR/2015/CR-CSP2-20150721/#directive-script-src

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/4300?

**Comment by mkArtakMSFT** [comment]
Yes, this is indeed a dupe. Closing this one in favor of the referenced issue.
