### ISSUE TITLE
rewrite middleware not identifying multiple slashes 

### ISSUE THREAD

**Issue by parmarnishant** [aspnet/Mvc#5779]
Problem : Redirect to url with single slash if url has multiple slashes.

http://localhost/segment1///segment2//segment3

The above url when read removes multiple slashes and shows only one slash.
I tried following methods to read url.

request.Path
Microsoft.AspNetCore.Http.Extensions.UriHelper.GetEncodedUri (request)
Microsoft.AspNetCore.Http.Extensions.UriHelper.GetDisplayUri(request)

Thanks.

**Comment by Eilon** [comment]
This issue was moved to aspnet/BasicMiddleware#212
