### ISSUE TITLE
Using embedded views -- with layouts -- from a package that supplies controllers/etc.

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#5784]
I'm trying to create a reusable module for web applications that supplies its own controllers, conventions, and so forth. So far, `IApplicationFeatureProvider<ControllerFeature>`, `ApplicationPart`, and so forth have been great -- but I'm kind of stuck on a pain point when it comes to how views are handled.

`EmbeddedFileProvider` indicates that all of the view files have been flattened, with slashes replaces by dots. That's not much of a surprise, and it's not Mvc's problem. But Mvc doesn't exactly play nice with it, either. If I add the embedded file provider to the right spot in the options, I can get part of the way there -- I have to use strings like "Views.Shared.Whatever.cshtml" and so forth, and there is never any guarantee that this won't conflict with another module or any file provider it chooses to add.

I tried wrapped the embedded file provider in my own file provider that adds a prefix and transforms the path, and added a mapping to project.json to add the prefix, but even though the view is found, the layout is then not found.

On a different attempt I was able to tweak something and get it to render but it used the main `_Layout.cshtml` from the web application and not my embedded one.

My next thought is to swap in a different `IViewEngine` within `OnResultExecuted` on a custom base controller class, but then I'm not sure how that will play with layouts and partials, still. The idea would be to have this custom view engine only look at the custom embedded file provider that transforms paths appropriately. `IRazorViewEngineFileProviderAccessor` is an internal interface and thus not 'blessed' for public usage so I'm not sure how this will play out because I don't see any obvious hooks for doing something like this.

Anyways, I'll keep trying to cook something up, and if anyone has an idea please let me know, or maybe this needs to be a feature request.

**Comment by tuespetre** [comment]
@rynowak I am going to :bug: you since you helped me a bit on the other thread about generic controllers.

I've found that I can use MSBuild metadata properties to get embedded views to keep the slashes in their names:

```
<EmbeddedResource Include="**\*.cshtml">
  <LogicalName>%(Identity)</LogicalName>
</EmbeddedResource>
```

That makes it easy to then supply a custom `IFileProvider` that can faithfully represent the view files as if they were coming from disk.

The problem I'm having now is that it's just too hard to spin up a custom instance of `RazorViewEngine` that uses this custom file provider and *only* this custom file provider. There's a complicated hierarchy of dependencies (many of which are internal) that receive injected `RazorViewEngineOptions` at various places, and there are some oddities like the fact that `IRazorPageFactoryProvider` is transient but everything it uses is a singleton.

It would be nice if there was a `RazorViewEngineFactory` or something that exposed a way to create a custom instance of `RazorViewEngine` from a supplied set of `RazorViewEngineOptions` while making sure those options were propagated down appropriately to all of the dependencies.

**Comment by rynowak** [comment]
> It would be nice if there was a RazorViewEngineFactory or something that exposed a way to create a custom instance of RazorViewEngine from a supplied set of RazorViewEngineOptions while making sure those options were propagated down appropriately to all of the dependencies.

This seems like something we could reasonably do.

Why do you want the separate view engine? for isolation?

**Comment by tuespetre** [comment]
Isolation 🏖

**Comment by rynowak** [comment]
At this point I'd also like to mention that @sebastienros showed me a demo yesterday of a very cool multimodule thing he built that puts each module in its own MVC instance. It may not be exactly what you are looking for, but it may also be valuable to compare notes.

**Comment by tuespetre** [comment]
Would like to see that -- I stumbled upon @danroth27's module strawman repo thing the other day too.

The isolated service container approach gets pretty messy though -- need to ensure that all of the 'default hosting services' like `ObjectPoolProvider`, `DiagnosticSource`, etc. are present, and then comes the configuration for what your library needs to do, and maybe you have a `DbContext` or few that need configured to be used by multiple, and... well, let's just say I backed off of that 😉

**Comment by rynowak** [comment]
I feel like at this point what we need is a canonical sample of both strategies:
1. Each module is in its own MVC instance (like Orchard2)
2. Each module has some degree of isolation, but there is one shared MVC instance (like Orchard1)

Doing either of these things gives you a million little problems to solve. It would be cool to show code that solves those *somehow* and then link to libraries that have more robust or full-featured implementations. Would this help? I know it would help me because I get fatigued from having to explain the concepts over and over.

**Comment by tuespetre** [comment]
That would be kind of really awesome to have. If we had canonical samples of both kinds of modularization available, everyone would be able to refer to (and suggest improvements to) the same place. I'm leaning toward the idea that nobody should need to introduce a 'Module' library or anything like that, but instead the samples could be reviewed and any of the more 'brittle' parts could be addressed as needed in the appropriate places (like the Hosting library providing a helper to create an isolated service container that has the required 'default services', or the Mvc library providing an easier way to make isolated instances of a `RazorViewEngine`.)

**Comment by rynowak** [comment]
> Hosting library providing a helper to create an isolated service container that has the required 'default services', or the Mvc library providing an easier way to make isolated instances of a RazorViewEngine

I think it will be a mix of both. There are definitely small wins in the core of ASP.NET to enable these scenarios, but there are also lots of concerns that need to be addressed by standalone or deeply integrated libraries. I see a sample like this first as an educational tool.

**Comment by sebastienros** [comment]
Sorry for the misunderstanding but Orchard provides MVC instances per tenants, not per module. So for each logical application. This is the big different with @danroth27 's solution. Like a typical MVC application. The confusion comes from the fact that Orchard used to have a common MVC instance for all tenants which we changed.

**Comment by pranavkm** [comment]
Given that we have Razor UI in class libraries - https://blogs.msdn.microsoft.com/webdev/2018/03/01/asp-net-core-2-1-razor-ui-in-class-libraries/ and support for an embedded file provider that preserves file names correctly (https://github.com/aspnet/FileSystem/blob/dev/src/FS.Embedded/build/netstandard2.0/Microsoft.Extensions.FileProviders.Embedded.props#L3), could this be closed? It doesn't exactly create an isolating module system, but gets the job of sharing code (controllers, models) with UI (Razor Pages, or Views).

**Comment by tuespetre** [comment]
@pranavkm yes/si/ja/oui/hai
