### ISSUE TITLE
RazorViewEngine Cache Expiration Duration Option

### ISSUE THREAD

**Issue by msfreed** [aspnet/Mvc#5786]
It looks like the cache expiration for the default RazorViewEngine is set to 20 minutes.
Why is the duration so short?
What is the reason that the compiled view is not cached for the duration of the process?
Can a configuration option be added to RazorViewEngineOptions to allow the duration to be manipulated?

Compilation can be expensive and we have some really slow request times which are due to the re-compilation of views.

**Comment by pranavkm** [comment]
@msfreed, there's multiple levels of compilation at the views. The view engine caches results of view location lookups with a 20 minute sliding expiration. Compilation results are independently cached until the contents of the cshtml file change. Do you have any traces that indicate view re-compilation is slowing down your application, I'd be happy to look at it.

**Comment by Eilon** [comment]
Closing because we don't have enough data to investigate this.
