### ISSUE TITLE
No symbols/source published

### ISSUE THREAD

**Issue by arthurborisow** [aspnet/Mvc#5787]
The issue in title. Can't debug asp.net. Is it expected behavior that the pdb is not loaded to symbols server? It makes difficult (read impossible) to navigate through source code of asp.net (especially in VS2017 where you can't include the sources of framework anymore).

**Comment by Eilon** [comment]
Hi @arthurborisow , we're tracking this for all our repos here: https://github.com/aspnet/Universe/issues/131
