### ISSUE TITLE
Web API not working with convention based routing

### ISSUE THREAD

**Issue by shravan2x** [aspnet/Mvc#5791]
I have a web API which uses convention based routing in ASP.NET Core 1.1. I have the following code in the `Configure` method of my `Startup.cs`:

    app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "api",
            template: "api/inventory",
            defaults: new { controller = "Inventory" });
    });

I have another `InventoryController.cs` class containing:

    public class InventoryController : Controller
    {
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }
    }

I expect that I will receive `["value1","value2"]` when I call `api/inventory`, but that is not the case. I receive a 404 instead. I am new to MVC and at wit's end. I'll note here that using a `RouteAttribute` makes everything work fine.

My issue is probably similar to #5762 .

**Comment by SilverioMiranda** [comment]
With your provided configuration is incorret since you not provided action name or controller name in controller route definition

For static routes like your example the best way to make route is this :
```
public class InventoryController : Controller
{
    [HttpGet("api/[controller]")]
    public IEnumerable<string> Get()
    {
        return new string[] { "value1", "value2" };
    }
}
```

**Comment by shravan2x** [comment]
As I mentioned earlier, using a `RouteAttribute` solves this. I am interested in knowing why it does not work with convention based routing.

I did not provide an action when creating my route since there is none. I would like to use `MapRoute` to call `IEnumerable<string> Get()` when `api/inventory` is called.

**Comment by Eilon** [comment]
@shravan2x this is a case where for ASP.NET Core MVC we decided to adopt MVC 5.x's conventional routing approach and not Web API 2.x's approach. With the conventional routing approach (as @SilverioMiranda mentioned), the route must specify both a controller and an action.

You can instead use attribute-routing to decorate specific controllers or actions with routes.
