### ISSUE TITLE
ModelState.Exception distinguish between 415 and 422 response code

### ISSUE THREAD

**Issue by codefactorydevelopment** [aspnet/Mvc#5796]
If we use application/json on post methods and validation fails it is very useful to know what kind of reason caused validation to fail.

One category of reasons is because input json string might be formatted incorrectly (brackets not closed, for example).
The other category is because, for example, we try to bind string to property defined as int in our mode.

Unfortunately, it seems that they both throw same exception (newtonsoft.json.jsonreaderexception) but since i would like to return different status codes for those cases (415 for first and 422 for second) question is:

Is there a way to distinguish those 2 categories of error without doing something as ugly as parsing exception message?

**Comment by Eilon** [comment]
Unfortunately we're not aware of a way for MVC to distinguish between these because the error comes from a lower-level component.

As such, we are closing this issue.
