### ISSUE TITLE
@page with an @model is overly sensitive to whitespace.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#5799]
This is probably a Razor issue but the problem is showing itself through MVC.

This works:
```
@page
@model WebApplication1.IndexModel

<p>This is from Razor: @Model.Message</p>
```

This doesn't work:
```
@page

@model WebApplication1.IndexModel

<p>This is from Razor: @Model.Message</p>
```

![image](https://cloud.githubusercontent.com/assets/2008729/22917995/c7c37d26-f23c-11e6-953b-3fbbdfa917ab.png)

**Comment by rynowak** [comment]
Isn't this almost certainly a parsing issue?

**Comment by NTaylorMullen** [comment]
> This is probably a Razor issue but the problem is showing itself through MVC.

**Comment by Eilon** [comment]
@NTaylorMullen / @ryanbrandenburg  is this still a bug? Or already fixed?

**Comment by pranavkm** [comment]
The correct fix for this would be https://github.com/aspnet/Mvc/issues/5475. We would be duplicating code in Mvc until that happens.
