### ISSUE TITLE
In a Razor page, void returning OnGet doesn't get run.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#5803]
This:

```
@page

@functions {
    public void OnGet()
    {
        Message = "From OnGet";
    }
    public string Message { get; set; } = "Default";
}
<p>The message: @Message</p>
```

Results in:
![image](https://cloud.githubusercontent.com/assets/2008729/22942070/d1922cac-f29c-11e6-843e-b22cf08bc226.png)

**Comment by ryanbrandenburg** [comment]
This seems to have been fixed, and a test was added [here](https://github.com/aspnet/Mvc/blob/85e28ae478164431904f4ac2c414c77258a35cf6/test/Microsoft.AspNetCore.Mvc.FunctionalTests/RazorPagesTest.cs#L83).
