### ISSUE TITLE
Custom ModelBinder

### ISSUE THREAD

**Issue by Sn3b** [aspnet/Mvc#5806]
Hi :)

Following instructions from the following post: https://github.com/aspnet/Mvc/issues/4477
I am still trying to understand how things fit together but I must say I am very confused... I have a similar situation where I'm trying to map a collection of derived classes but my situation is a tiny bit different.

I managed to put something together that works, but I feel it's very wrong.

So I'd like to clarify a couple of things.
1. Within the BindModelAsync, my bindingContext.ModelName is always empty (string empty), I cannot figure out why...
2. I receive the data from the post body, but as json, not as form values, and I noticed that when using Content-Type "application/json", bindingContext.ValueProvider only contains RouteValueProvider and QueryStringValueProvider. If I change to Content-Type to "application/x-www-form-urlencoded" then I get the extra FormValueProvider and JQueryFormValueProvider, what is the proper way of getting the data from json?

Thanks :)

**Comment by frankabbruzzese** [comment]
Json data are processed by a formatter not by ModelBinder. If you want to handle subclasses during Json model binding you have yo act on Json.net serializer/deserialize settings . Ps specify better your problem.

Anyway pay attention to yor code! A malicious user might use this feature to create and instance of a "Dabgerout type" thus trying a denial of service attack, or worst ....

**Comment by Sn3b** [comment]
Ah so model binding is not where I should be looking?

Ok more in details then, I created a few objects to help me filter lists, so I have:
- BooleanCriterion
- DateCriterion
- EnumCriterion
- NumericCriterion
- and TextCriterion

They all inherit from AbstractCriterion, and my controller expects either an IList< AbstractCriterion > or a ListOptions object which is a simple container for my parameter:

```csharp
    public class ListOptions
    {
        public IList< AbstractCriterion > Criteria;
        public Paging Paging;
    }
```

So I'm just trying to have my parameter filled with data when I hit the controller, the parameter (ListOptions) is just null...

**Comment by frankabbruzzese** [comment]
First of all the only way to recovery the exact type on the server side is to store somewhere the type info. Thus, for instance, if you are using Json to communicate with the browser you need to add a _type property containing a "code" of the exact subtype.

Now if your infos are submitted in Json you have to write a custom Json.Net Contract Resolver that in turns, for you abstract type calls a custom converter. 

If you submit in standard url-encoded you may use a custom model binder and during your page rendering the, type info of eah instance must be encoded either into an hidden input or by modifying somehow the field name. This way the custom model binder may come to know the type it must create.

In my Mvc Controls Toolkit I handle sub-classes both in Json and in standard url-encoded posts. I have a dictionary of all types that CAN be created as subclasses (needed to avoid a malicious user might creation of  "dangerous types"). These types have a numeric code assigned them that is used to convey type information. [Here ](https://github.com/MvcControlsToolkit/MvcControlsToolkit.Core/tree/master/src/MvcControlsToolkit.Core/ModelBinding/DerivedClasses), [here ](https://github.com/MvcControlsToolkit/MvcControlsToolkit.Core/blob/master/src/MvcControlsToolkit.Core/ModelBinding/TransformationModelBinder.cs )and [here ](https://github.com/MvcControlsToolkit/MvcControlsToolkit.Core/blob/master/src/MvcControlsToolkit.Core/ModelBinding/TransformationModelBinderProvider.cs)you may find both Custom binder and Json stuffs.Model binder stuffs are quite complex since my custom model binder do also other stuffs. Json stuffs should be easier to understand.

**Comment by Sn3b** [comment]
> First of all the only way to recovery the exact type on the server side is to store somewhere the type info. Thus, for instance, if you are using Json to communicate with the browser you need to add a _type property containing a "code" of the exact subtype.

Yes, this was already clear, I know the type up front so I know exactly what to parse as on the service side without having to do any try catch, TryParse whatsoever.

> Now if your infos are submitted in Json you have to write a custom Json.Net Contract Resolver that in turns, for you abstract type calls a custom converter.

This is what I'm less confortable with, and that I'd like to understand in greater details, do you know any example I could check out? Does the contract resolver get called from the input formatter? What's the exact process? 

Thanks for the links, I'll have a look shortly. In the mean time I have been playing with a custom input formatter but I'm having problems. Either I implement IInputFormatter but then all requests get through it and I'd like to let the default input formatter do its work for most calls, or I try to inherit JsonInputFormatter but then I don't know how to instantiate it as it requires a few things in its constructor...

**Comment by frankabbruzzese** [comment]
No need to write a custom formatter. It is enough to change JsonInputFormatter  settings to install a custom Contract Resolver.

You may change this settings in the services section:

`services.Configure<MvcJsonOptions>(o => o.SerializerSettings.ContractResolver = new RuntimeTypeContractResolver());`

Just give a look to my Contract Resolver (links in previous posts) and associated converter to write your own and then install with the code above.

**Comment by Sn3b** [comment]
@frankabbruzzese thank you very much for this crucial info, I have been able to create a simple resolver and converter (very much based on your code) that works just fine. However, it works only when my controller is expecting a parameter of type `AbstractCriterion` or an `IList< AbstractCriterion >`, now my next step is to make it work when the parameter is of type `ListOptions` which itself has a property of type `IList< AbstractCriterion >`. Is there an easy way or should I create another converter?

Here's some code:

`ListOptions`
```csharp
public class ListOptions
{
    public IList< AbstractCriterion > Criteria;
    public Paging Paging;
}
```
`CustomResolver`
```csharp
public class CustomResolver : CamelCasePropertyNamesContractResolver
{
    public override JsonContract ResolveContract( Type type )
    {
        var contract = base.ResolveContract( type );

        if ( type == typeof( AbstractCriterion ) && contract.Converter == null )
            contract.Converter = new AbstractCriterionConverter();

        return contract;
    }
}
```
`AbstractCriterionConverter`
```csharp
public class AbstractCriterionConverter : JsonConverter
{
    protected static JsonReader CopyReaderForObject( JsonReader reader, JObject jObject )
    {
        var jObjectReader = jObject.CreateReader();
        jObjectReader.Culture = reader.Culture;
        jObjectReader.DateFormatString = reader.DateFormatString;
        jObjectReader.DateParseHandling = reader.DateParseHandling;
        jObjectReader.DateTimeZoneHandling = reader.DateTimeZoneHandling;
        jObjectReader.FloatParseHandling = reader.FloatParseHandling;
        jObjectReader.MaxDepth = reader.MaxDepth;
        jObjectReader.SupportMultipleContent = reader.SupportMultipleContent;
        return jObjectReader;
    }

    public override void WriteJson( JsonWriter writer, object value, JsonSerializer serializer )
    {
        var t = JToken.FromObject( value );
        t.WriteTo( writer );
    }

    public override bool CanConvert( Type objectType )
    {
        return ( Nullable.GetUnderlyingType( objectType ) ?? objectType ) == typeof( AbstractCriterion );
    }

    public override object ReadJson( JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer )
    {
        if ( reader.TokenType == JsonToken.Null )
            return null;

        // Load JObject from stream
        var jo = JObject.Load( reader );
        // Create target object based on JObject
        JToken value;
        Type type = null;
        jo.TryGetValue( "type", out value );
        var criterionType = ( CriterionType )value.Value< int >();

        switch ( criterionType )
        {
            case CriterionType.Boolean:
                type = typeof( BooleanCriterion );
                break;
            case CriterionType.Date:
                type = typeof( DateCriterion );
                break;
            case CriterionType.Enum:
                type = typeof( EnumCriterion );
                break;
            case CriterionType.Numeric:
                type = typeof( NumericCriterion );
                break;
            case CriterionType.Text:
                type = typeof( TextCriterion );
                break;
        }

        if ( type != null && !objectType.GetTypeInfo().IsAssignableFrom( type ) )
            type = null;

        var target = Activator.CreateInstance( type ?? objectType );

        // Populate the object properties
        using ( var jObjectReader = CopyReaderForObject( reader, jo ) )
            serializer.Populate( jObjectReader, target );

        return target;
    }
}
```

**Comment by frankabbruzzese** [comment]
I should work with no modifications. 
Your contract resolver is called on each type so it will be called also on ListOptions  properties.
Pls notice contract Resolver is called just once per type, after first time converter is cached on a per-type cache. If it is not working pls debug it to understand why

**Comment by Sn3b** [comment]
Hi @frankabbruzzese, yes I have noticed it gets called for each type, but surprisingly after it gets called for `ListOptions` it doesn't get called anymore. Trying to find out why...

**Comment by Sn3b** [comment]
Ok got it working, it was because my front end wasn't sending a collection of AbstractCriterion but just 1 instance within the ListOptions object, so the incoming object didn't actually match what the controller was expecting.

I'm surprised to see that in the end the whole solution is fairly simple. I want to thank you @frankabbruzzese as without you I wouldn't have been able to find out all this, so thanks alot! :)

Stupid quesiton, is there any documentation on all this? I wasn't able to find any, but maybe I didn't look for the right thing since I was going in the model binding way to start with.

**Comment by frankabbruzzese** [comment]
Documentation is spread all over the web. ContractResolvers and Converters are  Json.Net stuffs, so they are documented there, not in Asp.net core documentation, since asp.net core just uses JSon.net to implement Json formatter.

About how to change Asp.net core Json settings, I have not seen it in the official doc, but you may find a few articles by googling the subject.

Now all dotnet stuffs are inter-mixed with other open source software, so one developers should learn to look also in 3rd parties documentation.

**Comment by Sn3b** [comment]
Ok cool, thanks again! :)
