### ISSUE TITLE
ModelValidation is allocatey

### ISSUE THREAD

**Issue by khellang** [aspnet/Mvc#5814]
We have an endpoint that gets POSTed a collection of about 2.5k results many times a second, and for some reason, MVC really wants to validate all those objects as part of the model binding process. After alle the (obvious) JSON deserialization allocations, validation comes in at the top of the list of allocated objects, both in terms of numer of objects, but also in terms of allocated bytes:

![2017-02-16_09-38-47](https://cloud.githubusercontent.com/assets/582487/23013805/889d711e-f42c-11e6-8c1e-b224c9ae1402.png)

I realize that full-blown model binding might not be the best fit for this scenario, but I think it's worth highlighting. Is there anything I can do to turn the validation off? Either for that specific type or for the action? `ValidateNeverAttribute`?

Right now, I've worked around it by replacing the default `IObjectModelValidator` with my own version that conditionally validates objects based on an attribute on the action, but I don't think that's the best solution.

I see there's been done some work on this [in the past](https://github.com/aspnet/Mvc/pull/4436), but surely there has to be some quick wins here?

**Comment by rynowak** [comment]
If you on new bits you can use https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidateNeverAttribute.cs

If you're on older bits you can use [this](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreMvcOptionsSetup.cs#L91) to achieve the same effect.

**Comment by khellang** [comment]
> If you're on older bits you can use this to achieve the same effect.

Ah, exactly what I need 😁

**Comment by rynowak** [comment]
The other thing I'd mention here is that there's a lot of `DataAnnotations.ValidationContext` allocations which I'd only expect if you've got validation attributes on your objects.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
