### ISSUE TITLE
MediaType.IsSubsetOf fails for media types with parameters

### ISSUE THREAD

**Issue by khellang** [aspnet/Mvc#5815]
Is `isSubset` supposed to be `false` here?

```csharp
var mediaType = new MediaType("application/msgpack; version=1");
var otherMediaType = new MediaType("application/msgpack");

var isSubset = otherMediaType.IsSubsetOf(mediaType);
```

I've written an `OutputFormatter` for MessagePack, but it fails if a client includes arguments in the `Accept` header.

**Comment by dougbu** [comment]
Yes, `false` is correct; `mediaType.IsSubsetOf(otherMediaType)` is `true`. IOW the parameter makes `mediaType` more specific than `otherMediaType`.

**Comment by khellang** [comment]
Then this must be a bug in the formatter selection, because surely a formatter that supports `application/msgpack` should be able to format `application/msgpack; version=1`?

**Comment by dougbu** [comment]
An **input** formatter that supports `application/msgpack` can by definition handle (deserialize) `application/msgpack; version=1` if the client sends it. But, an output formatter that supports `application/msgpack` cannot necessarily generate `application/msgpack; version=1`. Because clients are usually fairly general, you'll rarely see an `Accept` header that includes parameters.

If you have an unusual client and your output formatter can generate `application/msgpack; version=1`, include that specific media type in the supported list.

**Comment by khellang** [comment]
But it's not the media type that's the issue here. It's the parameter. The media type is a perfect match.

I don't get why I need to add a new "supported media type", only differing by a parameter, to my formatter every time there's a breaking change in my models.

The reason the version is included is because I have a result filter that looks at the parameter and maps the returned model to a representation for the specified version.

If Accept-header parameters are so rare, would it hurt to say that "we don't care about the parameters" when picking a formatter?

I guess I could always strip the parameter after I've mapped the versioned model, but that feels like a hack as well.

**Comment by dougbu** [comment]
Parameters matter and my suggestion was
> If you have an unusual client and your output formatter can generate application/msgpack; version=1, include that specific media type in the supported list.

**Comment by khellang** [comment]
> Parameters matter

Sure, they *can* matter, like the `encoding` parameter for derived classes of `TextOutputFormatter`, but why does `OutputFormatter` have to default to checking all parameters?

In this case, I'd say it would be better to accept (unknown) parameters by default and have derived classes be more strict on what they accept if any parameters make sense to them.

**Comment by khellang** [comment]
Do you have a good example of parameters that matter in the generic `OutputFormatter` case?

**Comment by rynowak** [comment]
@khellang - have your concerns here been addressed?

/cc @SteveSandersonMS

**Comment by khellang** [comment]
Yes, I think https://github.com/aspnet/Mvc/pull/6032 addresses this if I'm not mistaken.

**Comment by rynowak** [comment]
Thanks!
