### ISSUE TITLE
Suggestion: Tuple-returning Action methods

### ISSUE THREAD

**Issue by markrendle** [aspnet/Mvc#5820]
Now that we have nice Tuple syntax in C# 7.0, I thought maybe it could be used to offer an alternative, stronglier-typed return type for Action methods, especially since the `throw HttpResponseException` approach was (rightly) removed.

Something like this:

```csharp
public async Task<(Ship, int)> Get(int id)
{
  var ship = await _db.Ships.GetById(id);
  if (ship == null) return (null, 404);
  return (ship, 200);
}
```

Would enable ApiExplorer to extract more information without necessarily needing lots of Attributes.

**Comment by Eilon** [comment]
I haven't had a chance to play with Tuple syntax yet. What code does it actually generate? Just `Tuple<Ship, int>`? In other words, what would MVC be looking at in reflection to figure it out?

**Comment by rynowak** [comment]
It's `ValueTuple<Ship, int>`

The good news is that anyone can implement this with a result filter, it doesn't need to be anything intrinsic.

**Comment by Eilon** [comment]
Agreed with @rynowak . We try to be very cautious about adding features like this because they add a fair bit of complexity for a relatively uncommon scenario. You can already do something similar today by returning an anonymous object.

**Comment by rynowak** [comment]
To expand on my suggestion, if you want this write an `IResultFilter` that will check `context.Result` for an `ObjectResult`. Then if the payload of the `ObjectResult` is `ValueTuple<TSomething, int>` you set the `ObjectResult.StatusCode` to `tuple.Item2` and set the payload to `tuple.Item1`.

If you want to support XML also you need to set the declared type on the `ObjectResult` to `TSomething`.
