### ISSUE TITLE
Consume new Microsoft.AspNet.WebApi.Client.5.2.4 package

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5822]
Our Microsoft.AspNetCore.Mvc.WebApiCompatShim package currently has an indirect dependency on the Microsoft.Net.Http package. Building the shim project requires imports when targeting .NET Standard for the same reason. Both issues could be avoided if we moved to the latest Microsoft.AspNet.WebApi.Client package.

See also
- #5562, an older report of related problems
- aspnet/AspNetWebStack#45, tracking publishing the Microsoft.AspNet.WebApi.Client v5.2.4 package for realsies
- aspnet/AspNetWebStack#4, which covered adding .NET Standard 1.1. support to the Microsoft.AspNet.WebApi.Client package
- the current [Microsoft.AspNetCore.Mvc.WebApiCompatShim package](https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Microsoft.AspNetCore.Mvc.WebApiCompatShim)
- the current [Microsoft.AspNet.WebApi.Client package](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/)
- the new [Microsoft.AspNet.WebApi.Client package](https://www.myget.org/feed/aspnetwebstacknightly/package/nuget/Microsoft.AspNet.WebApi.Client)

**Comment by Eilon** [comment]
This is approved, but let's figure out the plan to actually ship the 5.2.4 wave of packages.

**Comment by dougbu** [comment]
Should I go ahead with this in the meantime i.e. with the nightly ASP.NET feed in MVC's NuGet.config?

**Comment by Eilon** [comment]
We should talk about how to do the release and see if we can just do that.

**Comment by dougbu** [comment]
Side note: Fix here should include removing the last couple of `$(PackageTargetFallback)` aka `"imports"` from the MVC repo.

**Comment by Tornhoof** [comment]
Any plans for a public aspnet/AspNetWebStack?
Just asking as aspnet/AspNetKatana ist already public and some issues in aspnet link the private repo

**Comment by dougbu** [comment]
The first priority is to publish 3.2.4 / 5.2.4 packages from aspnet/AspNetWebStack or at least the  Microsoft.AspNet.WebApi.Client.5.2.4 package on NuGet. But, yes, work to make that repo public is in progress.

**Comment by JunTaoLuo** [comment]
@Eilon were we going to remove this package? Is there an issue tracking that?

**Comment by Eilon** [comment]
Oops forgot to log an issue. I'll start a thread first. I'll actually go do that now.

**Comment by vanillajonathan** [comment]
@dougbu How is Microsoft.AspNet.WebApi.Client 5.2.4 coming along?

I would really like to see it on NuGet.

**Comment by dougbu** [comment]
@vanillajonathan the 5.2.4 package release is not yet available on NuGet. We've been consumed with `2.0.0-preview1` items and this is slated for `2.0.0-preview3`.

**Comment by smarts** [comment]
@dougbu is `2.0.0-preview3` something we can expect in 2017?

**Comment by dougbu** [comment]
@smarts see https://github.com/aspnet/Home/wiki/Roadmap

**Comment by smarts** [comment]
thanks @dougbu

**Comment by vanillajonathan** [comment]
It would be really nice with a small intermediate NuGet release of Microsoft.AspNet.WebApi.Client with just support for netstandard asap so we can write against APIs on .NET Core using `PostAsJsonAsync`.

**Comment by dougbu** [comment]
@anurse please remind me what additional change needs to happen in aspnet/AspNetWebStack for the Microsoft.AspNet.WebApi.Client.5.2.4 package to work in the new .NET 4.6.1 world. Was it just the one item?
- add a .NET 4.6.1-specific `<FrameworkReference>mscorlib</FrameworkReference>`

**Comment by anurse** [comment]
That should do it. The goal is to ensure that there is a Framework Assembly Reference to `mscorlib` in the `.NETFramework, Version=4.6.1` target framework in the final NuSpec, in order to suppress the `System.Net.Http` one that appears in the 4.5.1 target.

**Comment by joakimskoog** [comment]
Hi,

Just wondering if there's a rough TTL on this (early/late 2018?). My .NET Standard library needs to use `HttpMessageContent` for deserialisation of `HttpResponseMessage`.

**Comment by Eilon** [comment]
@joakimskoog naah 2017 we'll get this out.

**Comment by joakimskoog** [comment]
@Eilon: That's great! I would much rather utilise this solution than have to re-target my library for .NET Standard 2.0 to be able to use the compatibility shim.

**Comment by gregsdennis** [comment]
@Eilon any updates?  1 months since last post.

**Comment by Eilon** [comment]
@gregsdennis sorry no specific update at this time, but I assure you we did not forget, and this is still on our list.

**Comment by gregsdennis** [comment]
@dougbu why is this blocked?  Is it pending the resolution of some other functionality?

**Comment by Vinhaman** [comment]
I've tried to update my project to .net core 2.0 and i'm having some issues with the 5.2.3 (it builds but fails on execution due to dependencies of  System.Net.Http.Primitives ...)

Hope the 5.2.4 will come out soon so i can migrate my project

**Comment by dougbu** [comment]
Did a quick check of the current status because a lot has changed in MVC -- .NET Standard 2.0, lineups, &hellip;

1. Took a bit of work to switch MVC build's approach to grab the latest Microsoft.AspNet.WebApi.Client package. But, lineups world would not make that too difficult if starting from scratch.
2. Probably need the workaround first mentioned [above](https://github.com/aspnet/Mvc/issues/5822#issuecomment-304336977). But, the build didn't get far enough to compile or run any of the full-framework tests and confirm.
3. Hitting issues due to `FormDataCollection` being `internal` when compiled for .NET Standard. Appears some of the workarounds in the Microsoft.AspNet.WebApi.Client for .NET Standard are getting in the way. Or, perhaps, need to remove more duplicate classes from the shim.

Question for @Eilon: When we push on this again, should Microsoft.AspNet.WebApi.Client target .NET Standard 2.0 instead of the current 1.1? That'll impact how many `NETFX_CORE` special cases we can remove e.g. what we do about 3. above.

**Comment by RehanSaeed** [comment]
@Vinhaman Did you figure out the issue with `System.Net.Http.Primitives`? I can't seem to run my unit tests which use 5.2.3.

Also, the milestone says 2.1, so looks like 5.2.4 has been pushed back.

**Comment by vanillajonathan** [comment]
Should this still be in the `Microsoft.AspNet.WebApi.Client` namespace or should it be moved to the `Microsoft.AspNetCore.WebApi.Client` namespace?

**Comment by Vinhaman** [comment]
@RehanSaeed 
I had to remove the dependency completely as a workaround for it to work...
Upgrading to version 2.0 is not top priority for us and we are having other issues so for now we're still keeping the 1.1

**Comment by RehanSaeed** [comment]
A `System.Net.Http.Primitives` package does not seem to exist. StackOverflow pointed me at installing `<PackageReference Include="Microsoft.Net.Http" Version="2.2.29" />` which seems to work for now.

**Comment by gregsdennis** [comment]
Hello again.  Any updates?  ETA?

**Comment by Eilon** [comment]
@gregsdennis we are having some infrastructure issues right now that we are working through.

**Comment by YakhontovYaroslav** [comment]
I have just realized that im discussing missed FormUrlEncodedMediaTypeFormatter from Microsoft.AspNet.WebApi.Client.5.2.4 pre-release in closed issue https://github.com/aspnet/AspNetWebStack/issues/4 . 

Long story short:  FormUrlEncodedMediaTypeFormatter class is missing from .netstandard pre-release package. Here is https://github.com/aspnet/AspNetWebStack/pull/76 pull request to bring it back.

Hope this will be merged at the time of 5.2.4 release.

**Comment by challe** [comment]
Any updates?

**Comment by dougbu** [comment]
We expect to have preview ASP.NET Core 2.1 MVC packages early next year.

**Comment by marcote** [comment]
Hi there. Any updates folks?

**Comment by dougbu** [comment]
https://github.com/aspnet/Home/wiki/Roadmap shows we'll release ASP.NET Core 2.1 in "Q1-Q2 2018".

In the meantime, ASP.NET (not ASP.NET Core) packages named *-5.2.4-alpha1-171202 or *-3.2.4-alpha1-171202 are available in the https://dotnet.myget.org/gallery/aspnetwebstack-dev feed. The symbol server https://dotnet.myget.org/F/aspnetwebstack-dev/symbols/ is also populated.

The https://dotnet.myget.org/feed/aspnetwebstack-dev/package/nuget/Microsoft.AspNet.WebApi.Client package includes the .NET Standard 2.0 assembly we plan to include in the next release and then will use in Microsoft.AspNetCore.Mvc.WebApiCompatShim. But, even nightly builds of Microsoft.AspNetCore.Mvc.WebApiCompatShim won't use the newer Microsoft.AspNet.WebApi.Client until we do a public "preview1" release of that package.

**Comment by aliostad** [comment]
What is going on with `HttpMessageContent` so we were told .NET Standard 2.0 has everything... I am supposed to migrate CacheCow to support .NET Core and I need `HttpMessageContent`.

**Comment by dougbu** [comment]
@aliostad please file questions about ASP.NET in the https://github.com/aspnet/AspNetWebStack repo.

In any case, `HttpMessageContent` is present in the .NET Standard 2.0 assembly in https://dotnet.myget.org/feed/aspnetwebstack-dev/package/nuget/Microsoft.AspNet.WebApi.Client We have no reason to remove it prior to an official 5.2.4 Preview1 release.

**Comment by aliostad** [comment]
@dougbu sorry do I need to do anything to get it working?
 I am trying to target both net452 and netstandard2.0 but it cannot find `HttpMessageContent`

![image](https://user-images.githubusercontent.com/487334/33881821-eb0e621c-df2d-11e7-8d5c-cb773c6dceff.png)

**Comment by yaakov-h** [comment]
You're referencing 5.2.3 - I assume from the NuGet Gallery - not 5.2.4 (prerelease).

**Comment by aliostad** [comment]
@yaakov-h yes but that is for the benefit of `net452` and not `netstandard2.0`.

If I remove `netstandard2.0` from target, it stops complaining. Do you mean 5.2.4 has net standard bindings?

![image](https://user-images.githubusercontent.com/487334/33883572-35773efe-df34-11e7-862c-e436f91ee703.png)

**Comment by aliostad** [comment]
According to [this](https://github.com/dotnet/corefx/issues/6489), yes. It will be all fixed in the next few hours, apparently.

**Comment by dscarmoz** [comment]
What is the ETA on 5.2.4? Having the same issue Vinhaman stated 8/21 --- I've tried to update my project to .net core 2.0 and i'm having some issues with the 5.2.3 (it builds but fails on execution due to dependencies of System.Net.Http.Primitives ...)

**Comment by Vinhaman** [comment]
Hi @dscarmoz 
My workaround for this and many other problems was to change the target framework in all my projects to framework 4.6.1 (everything .net core 2 still works just fine).
Took me a few days to change everything we had but now is running smooth

**Comment by dscarmoz** [comment]
I don't think that will work for me. I'm running on a linux stack in PCF and the available buildpacks do not support it.

**Comment by dougbu** [comment]
- bab520f4dd
- aspnet/HttpClientFactory@ded365f1ec
- aspnet/Universe@cedbbd8394

**Comment by Eilon** [comment]
@dougbu should we log another bug to update to 5.2.4 RTM? Though it's not likely we'll *forget* to do that, it's good to have an item tracking stuff we know we have to do.

**Comment by dougbu** [comment]
Well, if you weren't OOF, I would have asked *you* just that 😺 I'll file one&hellip;

The other thing I would have asked an in-person @Eilon: bab520f4dd requires users to remove a previously-required `<PackageTargetFallback>` element or similar "must use PCL assembly" workaround from their projects. Should we document that as a full-blown breaking change? (I lean toward marking this bug with the label and adding a few words about the lines that should go but going no further.)

**Comment by Eilon** [comment]
Or leave the bug as-is, but post a breaking-change announcement about it. THat'll be especially helpful for release notes, etc.

**Comment by dougbu** [comment]
See #7212 for the follow-on work.

**Comment by asjafjell** [comment]
@anurse  I have upgraded a .NET4.6 library to .NET 4.6.1 and it is complaining about missing`System.Net.Http.HttpClientFactory.Create` in some tests of mine. Is this something that can be fixed by adding a `<FrameworkReference>mscorlib</FrameworkReference>` to the Nuspec?  Seems a bit odd as this will only affect consumers of my library, not making my tests green.

**Comment by dougbu** [comment]
@asjafjell please open a new issue for the problem you're seeing. Also, what is necessary to reproduce the problem and what are the details of the "complaining"?

**Comment by asjafjell** [comment]
@dougbu it seems to be automatic binding redirects that was my problem. I did not know that this would be an issue between 4.6.0 and 4.6.1, so by adding 

```
<PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup>
``` 

as indicated in dotnet/standard#481, the problem was fixed. The _complaining_, was that the method was missing runtime.
