### ISSUE TITLE
Use Consistent Case for Antiforgery/AntiForgery token attributes

### ISSUE THREAD

**Issue by ardalis** [aspnet/Mvc#5830]
Currently the casing is inconsistent between these three attributes:

- [ValidateAntiForgeryTokenAttribute](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ValidateAntiForgeryTokenAttribute.cs) (big F Forgery)
- [IgnoreAntiforgeryTokenAttribute](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/IgnoreAntiforgeryTokenAttribute.cs) (small f forgery)
- [AutoValidateAntiforgeryTokenAttribute](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/AutoValidateAntiforgeryTokenAttribute.cs) (small f forgery)

Although there are 2 small f's to 1 big F the less breaking change would probably be to change the latter two, since they're used far less frequently than the first one, I suspect. ``ValidateAntiForgeryToken`` is used in the ASP.NET Core web project templates, while the other two are not.

**Comment by rynowak** [comment]
This is intentional.

**Comment by ardalis** [comment]
What's the reasoning for it? When trying to switch between Validate... and AutoValidate... it's annoying to then also have to change F to f. I doubt most customers will run into it, but it still seems like an oversight, not an intentional choice. Should I document that it's intentional, and why? Thanks.

**Comment by rynowak** [comment]
The reasoning if that we wanted to build *everything new* with the correct casing `Antiforgery`, but had a requirement to not change the existing attribute `AntiForgery`. The fact that they are different has been brought up several times and several times we've decided to do nothing.

**Comment by ardalis** [comment]
Got it.
