### ISSUE TITLE
IControllerModelConvention and IRouteBuilder

### ISSUE THREAD

**Issue by hardhub** [aspnet/Mvc#5831]
When I am using this: `options.Conventions.Add()` to add custom convention then routes created here:

```C#
routing.MapRoute(
            name: "Version",
            template: "api/about",
            defaults: new { controller = "About", action = "Default" });
```

are not available inside `public void Apply(ControllerModel controller)` method.

But if I specify routes in attribute `[HttpGet("")]` I can get this route in convention.. so I can adjust it or create clone.

Problem that I cannot append all routes from UseMvc() in case when convention is added...

**Comment by Eilon** [comment]
Hi @hardhub, application conventions/models work only with attribute routing. They are separate from "conventional routes", which is what you have when you call `routing.MapRoute(...)`.

This is perhaps an unfortunate limitation, but the way the system is designed they need to be separate.
