### ISSUE TITLE
Binding Issue with complex data type from custom IRouter

### ISSUE THREAD

**Issue by jkljajic** [aspnet/Mvc#5833]
HI,
i have trying to build new route handler that will serve some dynamic Permalink routes from DB.
My problem is that complex binding don't work, simple binding works without problem.

This is part from custom IRouter :
```
                        var newRouteData = new RouteData(oldRouteData);
                        newRouteData.Values["controller"]="App";
                        newRouteData.Values["action"] ="Index";
                        newRouteData.Values.Add("language", PluginSiteContext.LanguageCode);
                        newRouteData.Values.Add("permaLink", _currentWebsiteLink);
                        context.RouteData = newRouteData;

                        await _defaultRouter.RouteAsync(context);
```

this is part from Controller : 

```

        [HttpGet()]
        public async Task<ActionResult> Index(Link permalLink, string language)
        {
            var permaLink2 = (Link) RouteData.Values["permaLink"];

            return View("Empty", permaLink2);
        }


```

for example permaLink is empty , language is en (is string type)
but permalink2 is ok with object initialized in IRouter

if i use attribute [FromRoute] or [FromRoute(Name="permaLink")] result also empty (NONE)

Can some one help me to solve this issue that i get correct binding result in parameters.

thanks

ps. if i need to post some working example for test pls tell me is possible, this is very important for migrate old project to dotnet core

**Comment by Eilon** [comment]
Hi @jkljajic , generally routes in ASP.NET Core work only with string data, because routes generally come from data that is parsed from a URL, and URLs are always strings. I think this is not working for you because the model binding system generally doesn't convert things *to* strings, but rather only *from* strings.

What happens if you change your controller's `language` parameter to be of the correct type, i.e. the type of the `PluginSiteContext.LanguageCode` property? I would imagine that that would work.

cc @rynowak @dougbu in case they have some further thoughts.

**Comment by jkljajic** [comment]
Hi,
Language is ok that one is string.

**Comment by jkljajic** [comment]
Hi, 
Language is strinv that is ok.

If i use complex type it will not look in routevalueprovider with name of that object it will separate that object in dictionary and look properies by every properties by it is own name

**Comment by dougbu** [comment]
Suggest stepping away from the custom `IRouter` for complex types. Instead create custom `IModelBinder` and `IModelBinderProvider` instances for your `Link` type. The binder itself should fetch the data it needs.

We don't have complete samples that do this. But, #4703 contains code that should help get you started.

**Comment by jkljajic** [comment]
Thanks fora your advice,
i have solve my issue making new IModelBinder and IModelBinderProvider.

```

public class RouteModelBinderProvider : IModelBinderProvider
    {
        public IModelBinder GetBinder(ModelBinderProviderContext context)
        {
            if (context.Metadata.IsComplexType && !context.Metadata.IsCollectionType)
            {
                return new RouteModelBinder();
            }
            return null;
        }
    }

    public class RouteModelBinder : IModelBinder
    {
        public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            ;
            var result = bindingContext.ActionContext.RouteData.Values[bindingContext.FieldName];
            if (result != null)
            {
                bindingContext.Result = ModelBindingResult.Success(result);
            }
            return Task.CompletedTask;
        }
    }

```

Only issue now is that i need to insert it before ComplexTypeModelBinderProvider this provider separate all properties. That in case "RouteData" is not needed.

**Comment by rynowak** [comment]
Closing as it sounds like the question was answered
