### ISSUE TITLE
Remove double null check from 'MediaTypeCollection .Add'

### ISSUE THREAD

**Issue by janosjanka** [aspnet/Mvc#5834]
```
public void Add(MediaTypeHeaderValue item)
{
    if (item == null)
    {
        throw new ArgumentNullException(nameof(item));
    }

    Add(item?.ToString()); // <= At this point, we already know that item cannot be null.
}
```

[https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/Formatters/MediaTypeCollection.cs#L33](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/Formatters/MediaTypeCollection.cs#L33)

**Comment by dougbu** [comment]
0e914e5

**Comment by dougbu** [comment]
Thanks very much @reaction1989!
