### ISSUE TITLE
Pages should trim quotes from route templates

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5835]
This page (HelloWorldWithRoute.cshtml):
```
@page "Some/Path/{text}"

Hello, @(ViewContext.RouteData.Values["text"])!
```

produces the route template `HelloWorldWithRoute/"Some/Path/{text}"`. The quotes should not be present in the route template.

As a workaround I'm removing the quotes from the page, but this workaround shouldn't be allowed by Razor at all.

**Comment by pranavkm** [comment]
Here's the corresponding Razor work item: https://github.com/aspnet/Razor/issues/980
