### ISSUE TITLE
bug of routing resolve

### ISSUE THREAD

**Issue by Eilyyyy** [aspnet/Mvc#5848]
hi everybody :
i create a new project and add two controllers named  FareController and CabinController like this 

```C#
public class CabinController : Controller
    {
        [HttpGet("index")]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet("{id}")]
        public IActionResult Edit(int id)
        {
            return View();
        }
    }
```

```C#
public class FareController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
```

the view do noting and just for debug.
then i access the url http://localhost:5000/fare, and then i was mistakenly in the view http://localhost:5000/cabin/edit.
my project.json like this

```JSON
"dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0"
  },
```

**Comment by rynowak** [comment]
Attribute routing does exactly what you ask. For instance you put `[HttpGet("{id}")]` on `CabinController.Edit` method, so it will any path with a single token (like `/fare' or '/17`). 

You will generally want to provide a prefix using the controller name so that routes don't overlap between controllers

```C#
[Route("cabin")]
public class CabinController : Controller
    {
        [HttpGet("index")]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet("{id}")]
        public IActionResult Edit(int id)
        {
            return View();
        }
    }
```

Now this will match `/cabin/<anything>` instead of `/<anything>`

You should take a look at https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing for all of the information

**Comment by Eilyyyy** [comment]
@rynowak thank you for your help, on your link i notice a word
 `With attribute routing the controller name and action names play no role in which action is selected.`
and i think this is why when i use the attribute route i can't rely on the route define in startup.cs. The Attribute is completely overlap the default routes. Thank you very mutch !!!
