### ISSUE TITLE
Custom RazorPage<T> stops tag helpers from working

### ISSUE THREAD

**Issue by gordon-matt** [aspnet/Mvc#5849]
When using a custom `RazorPage<T>`, the tag helpers stop working. As a simple example, I have the following:

```
public abstract class MyRazorPage<TModel> : RazorPage<TModel>
{
	//etc
}

public abstract class MyRazorPage : MyRazorPage<dynamic>
{
}
```

`@inherits MyRazorPage`

Then in my Login.cshtml page (which at the moment is just the default one, I have errors in the tag helpers, such as this one:

`<input asp-for="Email" class="form-control" />`

The error message is as follows:

"An expression tree may not contain a dynamic operation"

Is this a bug or am I missing something here?

**Comment by gordon-matt** [comment]
I decided to use the `@Html` helpers instead of the tag helpers. They don't seem to have a problem, but when running the site I get this error instead:

**ArgumentException: Property 'ViewData' is of type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]', but this method requires a value of type 'Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary`1[[Framework.Identity.Models.AccountViewModels.LoginViewModel, Framework.Identity, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. Parameter name: viewContext**

I also tried putting a **_ViewImports.cshtml** in the **/Views/Account** folder, but got the same errors as above because obviously it's still inheriting `MyRazorPage<dynamic>` from the **_ViewImports.cshtml** in the root. So I tried this as well (inside the **_ViewImports.cshtml** in the **/Views/Account** folder):

`@inherits Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>`

Same problem again.. interesting (and frustrating). So I think we definitely have some issues here.

**Comment by Eilon** [comment]
@rynowak @NTaylorMullen - any idea on this?

**Comment by rynowak** [comment]
No off the cuff idea, someone needs to try this and debug.

**Comment by pranavkm** [comment]
`public abstract class MyRazorPage : MyRazorPage<dynamic>` - maybe this It probably doesn't work if there's an `@model LoginViewModel` in the page.

**Comment by pranavkm** [comment]
This is a dup of https://github.com/aspnet/Mvc/issues/6291. Closing this and we'll use the other work item to track this.
