### ISSUE TITLE
Altering View Model with a Filter

### ISSUE THREAD

**Issue by himadrinath** [aspnet/Mvc#5858]
@Eilon @rynowak @davidfowl 
i have 3 classes **A**,**B** and **C**.
**A** and **B** class for Viewmodel those will be send from an action with separate views depending in query
but in HttpPost action will only have class **C** as a parameter.

using automapper and filter i want to convert the sending viewmodel class into class **C** before model binding. 
which filter can help me to achieve that 
how can i do that

**Comment by Eilon** [comment]
@himadrinath I think what you want to implement for this is a custom model binder that understands the conventions of your application and binds things in the appropriate manner.
