### ISSUE TITLE
RazorPage endpoints don't respect IgnoreAntiforgeryToken

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#5863]
If you add "OnPost" to a PageModel (like [this one](https://github.com/aspnet/Mvc/blob/dev/test/WebSites/RazorPagesWebSite/HelloWorldWithPageModelHandler.cs)) and decorate it with `[IgnoreAntiforgeryToken]` it will still attempt to validate Antiforgery.

**Comment by ryanbrandenburg** [comment]
According to @rynowak having attributes on these handlers isn't going to be possible.

**Comment by verysimplenick** [comment]
@rynowak , @ryanbrandenburg 
Okay, that I can do that simulate [IgnoreAntiforgeryToken] behaviour in razor pages?

**Comment by pranavkm** [comment]
@verysimplenick you should be able to annotate your Page model with the attribute and it should work now.

**Comment by verysimplenick** [comment]
@pranavkm 
yep, I already tried 
```
    [IgnoreAntiforgeryToken(Order = 1000)]
    public class OfferModel : PageModel 
...
```
But it's not working.

**Comment by pranavkm** [comment]
The validate antiforgery attribute that gets applied has an order of 1000 - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/AutoValidateAntiforgeryTokenAttribute.cs#L40 so you might need a higher `Order` for `IgnoreAntiforgeryToken` to become effective. Could you bump it up (to 1001)?

**Comment by verysimplenick** [comment]
@pranavkm Yes, it's works with Order > 1000, thanks.
Maybe need add it to docs of Razor Pages.
