### ISSUE TITLE
Target for .NET Standard 1.3

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#5864]
The only assembly that *should* need to target .NET Standard > 1.3 is the Razor assembly (since it has to load assemblies from byte[])

**Comment by pranavkm** [comment]
The API that we need `DependencyContext.Load` is only available on `netstandard1.6` @eerhardt \ @livarcocc do you see any way to to make the APIs available in `netstandard1.3`. I think the primary blocker in this case was this call https://github.com/dotnet/core-setup/blob/eca152525e19a41d489cd5845afa14982653cc0a/src/Microsoft.Extensions.DependencyModel/DependencyContextPaths.cs#L26. `Muxer` in CLI.Tools hacks around the lack of API (https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Cli.Utils/Muxer.cs#L46-L53), I'm not sure if you'd doing something similar here.

**Comment by eerhardt** [comment]
Besides the `AppContext/AppDomain.GetData` method that @pranavkm calls out above, we also need these APIs in DependencyModel that aren't available in `netstandard1.3`:

#### Assembly.GetEntryAssembly()
https://github.com/dotnet/core-setup/blob/master/src/Microsoft.Extensions.DependencyModel/DependencyContextLoader.cs#L46
https://github.com/dotnet/core-setup/blob/master/src/Microsoft.Extensions.DependencyModel/DependencyContext.cs#L84

- Only in netstandard1.5 https://apisof.net/catalog/System.Reflection.Assembly.GetEntryAssembly()

#### Assembly.Location
https://github.com/dotnet/core-setup/blob/master/src/Microsoft.Extensions.DependencyModel/DependencyContextLoader.cs#L122

- Only in netstanard1.5 https://apisof.net/catalog/System.Reflection.Assembly.Location

**Comment by pranavkm** [comment]
Thanks @eerhardt. @davidfowl closing this since I don't think this work item is doable.

**Comment by davidfowl** [comment]
hmmmmmmm
