### ISSUE TITLE
codegen crashes if out param variable is created in function call

### ISSUE THREAD

**Issue by ghosttie** [aspnet/Mvc#5869]
If I create an out param variable in the function call:

```
			if (Guid.TryParse(stringValue, out var valueAsGuid)) {
```

I get this exception:

> There was an error running the selected code generator:
> 'There was an error creating a DbContext :C:\Users\jmunro\Dropbox\Work\projects\asp.net\FileVision Application Server\FileVision Application Server\GuidHeaderModelBinder.cs(20,43): error CS1003: Syntax error, ',' expected
> C:\Users\jmunro\Dropbox\Work\projects\asp.net\FileVision Application Server\FileVision Application Server\GuidHeaderModelBinder.cs(20,39): error CS0103: The name 'var' does not exist in the current context
> C:\Users\jmunro\Dropbox\Work\projects\asp.net\FileVision Application Server\FileVision Application Server\GuidHeaderModelBinder.cs(20,43): error CS0103: The name 'valueAsGuid' does not exist in the current context
> C:\Users\jmunro\Dropbox\Work\projects\asp.net\FileVision Application Server\FileVision Application Server\GuidHeaderModelBinder.cs(21,56): error CS0103: The name 'valueAsGuid' does not exist in the current context
>    at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)'

but if I declare the variable separately:

```
			var valueAsGuid = Guid.Empty;
			if (Guid.TryParse(stringValue, out valueAsGuid)) {

```
there's no exception.

**Comment by Eilon** [comment]
@ghosttie is this happening while you're running the "Add View" or "Add Controller" scaffolding feature?

**Comment by ghosttie** [comment]
"Add Controller" - sorry, should have specified

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#410

**Comment by Eilon** [comment]
@ghosttie thanks for the clarification, I moved the bug to the right repo.
