### ISSUE TITLE
Mark .Execute method of RedirectToActionResultExecutor and RedirectToRouteResultExecutor virtual

### ISSUE THREAD

**Issue by DerPeit** [aspnet/Mvc#5874]
Is there any specific reason why the methods `void Microsoft.AspNetCore.Mvc.Internal.RedirectToActionResultExecutor.Execute(ActionContext, RedirectToActionResult)` and `void Microsoft.AspNetCore.Mvc.Internal.RedirectToRouteResultExecutor.Execute(ActionContext, RedirectToRouteResult)` are not virtual?

These types are part of the Internal namespace so I guess they are intended to be used by the framework only, but making these methods virtual would enable developers to register derived implementations at the service collection to create different redirection strategies like adding a location header for regular requests but return something like `window.location = '...'` with a content-type `text/javascript` when the resource has been requested with AJAX depending on the action and so on.

Currently this cross-cutting cannot be implemented at a single place easily. You'd either have to create a base-class for controllers and override the respective methods or implement some sort of extension methods on a controller.

**Comment by Eilon** [comment]
Hi @DerPeit I think I would prefer for this to be a different type of action result. Changing the behavior of the existing RedirectXyz methods on ControllerBase and its relation action executors would change the intention of those features. Those features are specifically designed and implemented to do an HTTP redirect with a 302/301 status code.

I would instead suggest writing a new action result type that's something like this:

```c#
// pseudo-ish code; won't compile as-is!
public class FancyRedirectResult : IActionResult
{
    public override Task ExecuteAsync(...)
    {
        if (request.IsAjax)
        {
            return DoAjaxWindowLocationRedirect(...);
        }
        else
        {
            return new RegularRedirectResult(...).ExecuteAsync(...);
        }
    }
}
```

I think this would make it clearer that this isn't just a regular redirect - it's something similar, but different.

Oh, and to the original aspect: yeah, stuff that's in the `.Internal` namespaces is not meant to be used by anything outside of the framework itself. That code can change at any time and is not supported, so even if we make the suggested change, we would still urge people to not use it.

**Comment by DerPeit** [comment]
Hi @Eilon. I see what you mean although I disagree for several reasons: First, the method names `.RedirectToRoute` and `.RedirectToAction` say nothing about _how_ the user is being redirected. Just because it behaves like this since MVC 3 (maybe earlier, I am not sure) does not necessarily mean that you cannot provide certain hooks to improve it.

As a consumer of this API I am not interested in how the user is being redirected as long as he is redirected at all. In terms of expressiveness (you said it would be clearer) even the `.Redirect...` methods would then have to be renamed to point out that they are using a location header (I don't argue for that!).

Don't get me wrong: I love ASP.NET Core for providing way better API code than MVC did before. For example: I worked in a project once where the customer required us to add a star as a suffix to labels of mandatory form fields. Though this was a cross-cutting concern it was not easy to implement. We had to write an extension method for the `HtmlHelper` as an overload to create those labels based on the model-metadata because there were no better hooks. As a result we had to adjust every label in every view. Nowadays you can simply derive from this `HtmlHelper` and register your own implementation as a service which is absolutely great. And we already have an implementation for those executors which are registered as services as well but we have no chance here. Why is that?

In my opinion these classes should even be moved out of the `.Internal` namespace (why are the classes in there public at all, that's also not quite expressive) so developers have a chance to override (not more, it's not about changing the default behavior) the behavior of _how_ results are being executed because they actually _don't_ claim _how_ they have to be executed, just declare _what_ they should do, which is totally fine.

It's an API. So why restrict developers? I always feel sad when I find a very appropriate hook for my intent and then see that I just cannot use it because of those trivials. Regardless of a method not being `virtual` or a class being `sealed` or `internal`. 😉

**Comment by rynowak** [comment]
>It's an API. So why restrict developers? I always feel sad when I find a very appropriate hook for my intent and then see that I just cannot use it because of those trivials.

This is a loaded question. We can't anticipate every need developers will have, and we can't anticipate every way you will try to address your needs.

It's not our intent to make you sad.

**Comment by rynowak** [comment]
Discussed with @Eilon - we're going to do a pass and make the `Executors` be virtual. Caveat Emptor with taking a dependency on these things as they are still `.Internal` for now.

**Comment by DerPeit** [comment]
> This is a loaded question. We can't anticipate every need developers will have, and we can't anticipate every way you will try to address your needs.
> 
> It's never our intent to make you feel sad or restricted. In this case it's probably an oversight.

It was no offense. I am perfectly fine with that. I am glad that we as a community are finally involved in the development process at all.

> One of the biggest challenges building this framework is that using DI and relying on constructor injection is also a contract. If we want to add logging to a public class that you're allowed to extend, then that's a breaking change.

That is of course true and I know that it's _very_ hard work to keep all this in mind. Unfortunately any change to a public surface can be considered as a breaking change so I guess this is our developer's life. 😄

> Replacing a service is a big hammer because you can only do it once per app, and inheritance is often a clumsy way to change behavior - as it requires us to figure out ahead of time what extension points you will need and add them as protected methods.

Not necessarily. Anticipating the need for protected methods as hooks is of course great, but in the end even making the "entry point" to an artifact (whatever that is) virtual enables customization. Concerning inheritance: Maybe it's worth to consider to extract interfaces for those executors. If these specific executors would be registered as interfaces to the DI container, one could implement decorating executors (by composition instead of inheritance) and register them instead.

> Discussed with @Eilon - we're going to do a pass and make the Executors be virtual.

Great. I really appreciate that!

**Comment by rynowak** [comment]
4d905a4110484185173be3de24b59e3b28dd6416
