### ISSUE TITLE
XmlSerializerOutputFormatter returns application/json when the actions result is a custom interface.

### ISSUE THREAD

**Issue by richwalrath** [aspnet/Mvc#5875]
I'm trying to get my WebAPI project to be able to return different object types based on the result of the execution. 

To do this I have all of my return Models/objects inherit from an empty Interface which is what is set to be returned by all of my actions. This works wonderfully for the default JSON serializer as it will actually find out the actual object type returned and serialize it accordingly. However when I try to use 'Accept: application/xml' it will always return the Content-Type application/json, with the data serialized as JSON.

Here is my current test scenario and setup:

**In Startup.ConfigureServices:**
```
services.AddMvc(config =>{
    config.RespectBrowserAcceptHeader = true;
    config.InputFormatters.Add(new XmlSerializerInputFormatter());
    config.OutputFormatters.Add(new XmlSerializerOutputFormatter());
});
```

**Create an Interface to use as a base**
```
public interface IResponse {
    // Don't put anything here.
}
```

**Create a Person Model that inherits from IResponse**
```
public class Person : IResponse {
    public string Name { get; set; }
    public int Age { get; set; }
    public string Gender { get; set; }
    public string FavoriteTopic { get; set; }
}
```

**Create a RequestResult Model that inherits from IResponse**
```
public class RequestResponse : IResponse {
    public int ID { get; set; }
    public string Status { get; set; }
    public string IssueType { get; set; }
    public string Message { get; set; }
}
```

The RequestResponse type is returned when a non-200 status result is generated or if the operation does not return a different Model for a result.

Here are a couple of Controllers I used to test against (ignore the naming convention please):

```
[Route("api/IResponse")]
public class IResponseController : Controller {
    [HttpGet]
    public IEnumerable<IResponse> Get() {
        return new IResponse[] {
            new Person { Name = "Rich", Age = 36, Gender = "Male", FavoriteTopic = "Programming" },
            new Person { Name = "Bob", Age = 64, Gender = "Male", FavoriteTopic = "Woodworking" },
            // Also you could return a RequestResponse here as well and the default JSON serializer
            // won't choke.
            new RequestResponse{ ID = 1, Status = "Error", IssueType = "Unknown", Message = "What is this doing here?" }
        };
    }
}
```

The above action will always produce a Content-Type of 'application/json' in the JSON data format even when you specify Accept to 'application/xml'.

However if you have an action defined like this:

```
[Route("api/Persons")]
public class PersonController : Controller {
    [HttpGet]
    public IEnumerable<Person> Get() {
        return new Person[] {
            new Person { Name = "Rich", Age = 36, Gender = "Male", FavoriteTopic = "Programming" },
            new Person { Name = "Bob", Age = 64, Gender = "Male", FavoriteTopic = "Woodworking" },
            // We can't mix results with this one unfortunately unless there are Models that inherit 
            // from Person..
        };
    }
}
```

By calling the above with 'Accept: application/xml' you will get back an XML response and with 'Accept: application/json' you will get back a JSON response.

It seems like the XmlSerializerOutputFormatter is failing without error and falling-back to JSON. The built-in Interface types like IEnumerable don't seem to be affected by this.

**Comment by richwalrath** [comment]
I forgot to mention I'm using: Microsoft.AspNetCore.Mvc.Formatters.Xml version 1.1.1

Also a more practical way I'm using it is as follows:

```
[Route("api/Persons")]
public class PersonController : Controller {
    [HttpGet]
    public IEnumerable<IResponse> Get() {
        try {
            // Do stuff here
           return persons;
        } catch (Exception err) {
            HttpContext.Response.StatusCode = 500;
            return new RequestResponse[] { new RequestResponse { ID = 1, Status = "Error", IssueType = "Unknown", Message = err.Message } };
        }
    }
}
```

Which works perfectly for default or application/json but does not work for application/xml.

**Comment by reaction1989** [comment]
Can you try serializing your returning Object directyl with` XmlSerializer`?

The Problem is probably that you try to return an IResponse int the first example. Despite the fact that you return different Objects.

In the second example you return an List of Person. Thats probably why it works for you.


Another question:
Why don't you just return an `IActionResult `? You could return an Error with a message.

**Comment by richwalrath** [comment]
I tried the serializing directly using the following code:
```
    IResponse result = new Person { Name = "Rich", Age = 36, Gender = "Male", FavoriteTopic = "Programming" };
    XmlSerializer serializer = new XmlSerializer(result.GetType());
    MemoryStream stream = new MemoryStream();
    XmlTextWriter writer = new XmlTextWriter(stream, Encoding.UTF8);
    serializer.Serialize(stream, result);
    writer.Close();
    stream.Close();
    string xml = Encoding.UTF8.GetString(stream.GetBuffer());
```
When executed the xml string is populated as you would expect with a serialized version of Person.

If I change it a bit to try to serialize it as an IEnumerable<IResponse> though using the code below it fails with a NotSupportedException:
```
    IEnumerable<IResponse> result = new List<IResponse>{
        new Person { Name = "Rich", Age = 36, Gender = "Male", FavoriteTopic = "Programming" },
        new Person { Name = "Bob", Age = 64, Gender = "Male", FavoriteTopic = "Woodworking" }
    };
    XmlSerializer serializer = new XmlSerializer(result.GetType());
    MemoryStream stream = new MemoryStream();
    XmlTextWriter writer = new XmlTextWriter(stream, Encoding.UTF8);
    serializer.Serialize(stream, result);
    writer.Close();
    stream.Close();
    string xml = Encoding.UTF8.GetString(stream.GetBuffer());
```

If I change the 'new List&lt;IResponse&gt;' to 'new List&lt;Person&gt;' it works but this would only fly within the block as the return type is still IEnumerable&lt;IResponse&gt; because it needs to potentially return a different object.

It also appears that XmlSerializer cannot handle sub-classes as I did the following and it failed:
```
IEnumerable<IResponse> result = new List<Person>{
        new Person { Name = "Rich", Age = 36, Gender = "Male", FavoriteTopic = "Programming" },
        new Person { Name = "Bob", Age = 64, Gender = "Male", FavoriteTopic = "Woodworking" },
        // Imagine I defined a sub-class of Person named AwesomePerson
        new AwesomePerson { Name = "Alice", Age = 42, Gender = "Female", FavoriteTopic = "Football", Why = "Because Reasons" }
    };
    XmlSerializer serializer = new XmlSerializer(result.GetType());
    MemoryStream stream = new MemoryStream();
    XmlTextWriter writer = new XmlTextWriter(stream, Encoding.UTF8);
    serializer.Serialize(stream, result); // Fails here with an InvalidOperationException
    writer.Close();
    stream.Close();
    string xml = Encoding.UTF8.GetString(stream.GetBuffer());
```

If I return IActionResult then I loose the all the magic that the default JSON output formatter gives me and I would need to manage whether XML or JSON is returned in all of my actions and I won't be able to mix types in the lists.

I personally don't care about XML as I'm a JSON guy, but I have some clients that want to use XML instead so I told them I'd check it out. It just seems a bit off that the standard output serializers cannot handle the same inputs to produce said outputs.

The only wierd thing though that might be a yet another issue is that in the first example of this reply I was able to serialize using an IResponse with the XmlSerializer, but when IResponse is the return type, 'Accept: application/xml' is set and I return a 'new Person' as a IResponse it still comes back as JSON.

So to compare the default JSON output formatter handles anything you can throw at it and the XmlSerializerOutputFormatter fails on receiving Interfaces and falls back to JSON as a response.

**Comment by danroth27** [comment]
The XML serializers tend to be very particular about making sure that whatever they serializer they can then deserializer. The formatting system will use the return type to tell the XML serializers up front what type will be serialized/deserialized. Since an interface only has enough information for serialization (not deserialization) the XML serializers refuse to serialize. This is a limitation of how the XML serializers in .NET work.

You are in fact better off returning IActionResult for your action. You can get the exact same behavior as returning an object by returning an `OkObjectResult` or just `ObjectResult` for other status codes. It's really easy to do this using the `Ok(object value)` helper method:

```c#
[Route("api/Persons")]
public class PersonController : Controller {
    [HttpGet]
    public IActionResult Get() {
        try {
            // Do stuff here
           return Ok(persons);
        } catch (Exception err) {
            HttpContext.Response.StatusCode = 500;
            return ObjectResult(500, RequestResponse[] { new RequestResponse { ID = 1, Status = "Error", IssueType = "Unknown", Message = err.Message } });
        }
    }
}
```

**Comment by richwalrath** [comment]
I'll give that a try and see how it works. It should cover what I need.

I ended up getting xml serialization to work using interfaces the ExtenededXmlSerializer and writing my own output formatter. I haven't tried mixing sub-classes yet but since I require specific type inputs and overload as needed for inputs it shouldn't be an issue using the XmlSerializerInputFormatter for that.

Thanks for your time.

**Comment by rynowak** [comment]
@richwalrath - I would suggest writing an `IResultFilter` that checks if the `context.Result` is an `ObjectResult` and then sets `ObjectResult.DeclaredType` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ObjectResult.cs#L27 based on the value of `ObjectResult.Value?.GetType()`.

The fact that the XML serializers operate based on the return type of the method is a feature and is consistent with how .NET's xml serialization works in general. A serializer is constructed based on a specified type, and can serialize derived classes, but will ignore anything they add. What I described above will deactivate this feature.
