### ISSUE TITLE
JsonPatchInputFormatter does not bind to the type 'JsonPatchDocument'

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#5880]
I am not sure why its likes this but **[this check](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonPatchInputFormatter.cs#L82)** in JsonPatchInputFormatter causes the formatter to not deserialize requests to `JsonPatchDocument` type. The scenario that I thought where supporting this would be interesting is the following(Basically one might not want to create a C# model for their documents):

```c#
        [HttpPatch]
        public IActionResult PatchABlob([FromBody] JsonPatchDocument patchDoc)
        {
            if (patchDoc != null)
            {
                var jsonBlob = GetJsonBlobFromSomeStore();

                var converter = new ExpandoObjectConverter();
                dynamic obj = JsonConvert.DeserializeObject<ExpandoObject>(jsonBlob);

                patchDoc.ApplyTo(obj);

                return Ok(obj.Name);
            }
            else
            {
                return BadRequest(ModelState);
            }
        }

        private string GetJsonBlobFromSomeStore()
        {
            return "{\"Name\":\"James\"}";
        }
```

cc @rynowak

**Comment by rynowak** [comment]
Hmm that's an interesting one, I'm not sure why we disallowed this specifically.

**Comment by Eilon** [comment]
Yeah the code there is 2 years old and it's not clear why... but also no one has asked for it, so closing this.
