### ISSUE TITLE
Tag Helper Enum shorthand syntax doesn't work for nullable enums.

### ISSUE THREAD

**Issue by NickCraver** [aspnet/Mvc#5881]
I'm working on a project with a nullable enum property in the tag helper, like this:
```c#
[HtmlTargetElement("mini-profiler", TagStructure = TagStructure.WithoutEndTag)]
public class MiniProfilerScriptTagHelper : TagHelper
{
    [HtmlAttributeName("position")]
    public RenderPosition? Position { get; set; }
}
```
Relevant enum: 
```c#
public enum RenderPosition
{
    Left = 0,
    Right = 1,
    BottomLeft = 2,
    BottomRight = 3
}
```
You can pull [the full repo here (specific commit link)](https://github.com/MiniProfiler/dotnet/tree/5c7950d58855e691432c1fa92904248e739f51fc)

I would expect the shorthand syntax to work in razor, like this:
```xml
<mini-profiler position="Right" />
```
However, that only works if `Position` is `RenderPosition` (not-nullable). When it's a nullable (`RenderPosition?`), you get an error:
> The name 'Right' does not exist in the current context.

Instead, you have to use the full version:
```xml
<mini-profiler position="@RenderPosition.Right" />
```

Can we please make this work with nullable enums too?

cc @DamianEdwards @khellang

**Comment by khellang** [comment]
The question is

1. Should this be filed in https://github.com/aspnet/Razor?
2. Is it even worth looking at, since it seems like everything is up in the air and newer bits are landing soon (which might or might not fix this).

**Comment by Eilon** [comment]
@NTaylorMullen @rynowak any thoughts on this? Any particular reason this doesn't work today?

But yeah, probably belongs in Razor repo per @khellang 's comment.

**Comment by NTaylorMullen** [comment]
Ya this doesn't work because we do: `property.PropertyType.GetTypeInfo().IsEnum`. We need to check the underlying type in the case of a nullable. Definitely a Razor issue.

**Comment by NickCraver** [comment]
Moved to Razor repo as suggested: https://github.com/aspnet/Razor/issues/1047
