### ISSUE TITLE
Add ModelState to page, and auth stuff to RazorPageOptions

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#5884]
* [x] ModelState on the page - Fixed in https://github.com/aspnet/Mvc/commit/00c38fca591564e1200a39856475a8d7573f182c
* [ ] Add AllowAnonymousToPage and AllowAnonymousToFolder extensions to RazorPagesOptions: https://github.com/aspnet/RazorPages/blob/master/src/Microsoft.AspNetCore.Mvc.RazorPages/DependencyInjection/PageModelConventionBuilderExtensions.cs#L14

**Comment by Eilon** [comment]
Some of this might have been done already. Please ensure that even if some features are already there, we also need to ensure there is proper test coverage.
