### ISSUE TITLE
Support model binding to tuples

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#5885]
Tuples seem like a nice way to define an input model for an action method.

**Comment by danroth27** [comment]
Might be nice to then also have a simple way to map the input model to your application model. See #5883.

**Comment by DamianEdwards** [comment]
Yes please!! This could be a much nicer way to protect against mass-assignment without the need to create concrete types for input models or use the (awful) Bind/NeverBind features.

So, something like this:
``` c#
[HttpPost]
public IActionResult Create((string FirstName, string LastName, DateTime BirthDate) inputCustomer)
{
    var customer = new Customer();
    ObjectMapper.Map(inputCustomer, customer);
    // Save it, blah blah
    return View();
}
```

**Comment by rynowak** [comment]
You can't put attributes on the fields of a tuple. With that limitation do you still want this?

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
