### ISSUE TITLE
HiddenFor generates unobtrusive validation attributes

### ISSUE THREAD

**Issue by mrtaikandi** [aspnet/Mvc#5886]
I'm not entirely sure if this is a bug or a security measure but currently if you use Html.HiddenFor or <input type="hidden" asp-for=""/> for a model property that has validation attributes, the tag helper will generates its equivalent data-* attributes. 

In my opinion this is not required and only increases the page size.

**Comment by frankabbruzzese** [comment]
sometimes they are useful,expecially required field validation, sometimes they are not. Often hidden fields are used to implement javascript widgets,, other times just to store something that cant be used by the user. You may put all store-only hidden fields at the end of the page grouped into an area where client validation has been disabled.

**Comment by mrtaikandi** [comment]
Good point for javascript widgets. 

But for MVC apps, IMHO we need hidden inputs for model properties that we want them back during post back but it is not important for the user. For example the ID of the entity being edited or some other readonly property that the user can see but will not be used by model binding such as `<input type="text" readonly />`

In these scenarios, I think it would be a good option to have the hidden field generator to not generate the validation attributes.

**Comment by frankabbruzzese** [comment]
You may disable validation into an arear of your view, so if you want you may concentrate all these fields there, or better put all this info into an unique field in json format, without adding any validation. You may easily implement a similar TagHelper. Here is a working implementation: [store-field example](http://examples.aspnetcore.mvc-controls.com/InputExamples/StoreModel).

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
