### ISSUE TITLE
Support referer policy in tag helpers and @Html.Link

### ISSUE THREAD

**Issue by blowdart** [aspnet/Mvc#5890]
See

https://html.spec.whatwg.org/multipage/infrastructure.html#referrer-policy-attribute

https://notes.bughunters.club/referrer-policy-168bf3328ecd#.gu0vshwkj

**Comment by Eilon** [comment]
Is this just a regular HTML attribute? If so, there's nothing to add in MVC's tag helpers or HTML helpers. You can always add whatever arbitrary HTML attributes you want.

**Comment by Eilon** [comment]
I read about it a bit more and yeah this is just a plain old HTML element attribute / HTTP header / whatever, so there's nothing stopping anyone from using it. We only need to add specific logic to MVC helpers when there needs to be some "server logic" behind it (e.g. resolving a URL, showing model state values, validation, etc.).
