### ISSUE TITLE
httpContext.RequestServices is null in OnBeforeAction event's callback

### ISSUE THREAD

**Issue by SergeyKanzhelev** [aspnet/Mvc#5895]
Investigating this issue: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/352 

It seems that `httpContext.RequestServices` is `null` while processing `OnBeforeAction` event. What would be the conditions for it to be `null`? Is it an expected behavior?

**Comment by rynowak** [comment]
The `RequestServices` is populated by this middleware https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/RequestServicesContainerMiddleware.cs which is added by default by hosting. 

AFAIK this can only happen in one of three ways:
1. The user has some code that messes with `RequestServices` or `IRequestServicesFeature`
2. The middleware that sets up request services is not configured
3. The middeware that sets up request services has completed executing, and has disposed the `IRequestServicesFeature`.

**Comment by SergeyKanzhelev** [comment]
Thanks @rynowak . Is `httpContext.Features` has a similar behavior? Or it will never be `null`? In latest Application Insights SDK we switched from keeping an object in services to keep it as a `Feature` and I wonder will should account for it being unavailable as well.


Customer says this error do not happen all the time. And in the call stack I see `ExceptionHandlerMiddleware` and `ControllerActionInvoker` so I assumed the normal execution. I can ask whether app doing something crazy with the context.

**Comment by rynowak** [comment]
I don't believe `Features` is ever disposed.

**Comment by SergeyKanzhelev** [comment]
Thanks
