### ISSUE TITLE
Port fix from #5807 to 1.1.X - Race condition in ControllerActionInvoker causes NullRef

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5899]
See #5807

We need to patch this in 1.1.X

**Comment by Eilon** [comment]
This patch fix is *approved*. Please follow the normal code review / pull request process and make sure you make the change in the correct branch.

**Comment by Eilon** [comment]
@rynowak - here's the bug we were talking about. Apparently I forgot to assign to you, sorry!

Please get the fix in ASAP.

**Comment by Eilon** [comment]
@rynowak ping.

**Comment by Eilon** [comment]
Is this still waiting on @pranavkm to unblock something?

**Comment by rynowak** [comment]
55873bcbfc17d215237d8fbb4a082fb2ff8a0fdf

**Comment by Eilon** [comment]
Preview builds of this patch fix should be available on the following feeds:

* https://dotnet.myget.org/gallery/aspnet-1-0-5-may2017-patch-public (for fixes in the 1.0.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-0-5-may2017-patch-public/api/v3/index.json
* https://dotnet.myget.org/gallery/aspnet-1-1-2-may2017-patch-public (for fixes in the 1.1.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-1-2-may2017-patch-public/api/v3/index.json

If you have a chance, please try out these preview builds and let us know if you have any feedback!
