### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by RemiBou** [aspnet/Mvc#5900]
### Unable to build 
*EIther build.cmd or build.ps1 fails*

### Functional impact
*Unable to launch the the framework code on my machine for understanding its behavior*  

### Minimal repro steps

1. git clone https://github.com/aspnet/Mvc.git
2. cd Mvc
3. ./build.cmd or ./build.ps1

### Expected result
The project builds.

### Actual result
Here is the output 
[build.cmd > log.txt results](http://pastebin.com/6aefpdhF)

dotnet --info :

> .NET Command Line Tools (1.0.0-rc4-004771)
> 
> Product Information:
>  Version:            1.0.0-rc4-004771
>  Commit SHA-1 hash:  d881d45b75
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.14393
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

**Comment by pranavkm** [comment]
The build output includes the issue:

```
The reference assemblies for framework ".NETFramework,Version=v4.5.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. 
```

You'll need the .NET452 (or higher) SDK installed - here's the first search result that popped up for it: https://www.microsoft.com/en-us/download/details.aspx?id=42637. We typically expect a version of VS installed when building on Windows which installs the SDK.

**Comment by RemiBou** [comment]
I already installed the sdk (4.6). I tried to install the one you refer to but it still doesn't build :  [Pastbin](http://pastebin.com/9PXSKxLU). And I only have VS Code installed (last version). I ran the build after rebooting and in admin mode.

Is there any documentation about building this project ?

**Comment by Eilon** [comment]
@RemiBou did you install this? https://www.microsoft.com/en-us/download/details.aspx?id=40772

**Comment by RemiBou** [comment]
yes I did, then reboot (don't know if it's needed though)

**Comment by Eilon** [comment]
Hmm that's weird then. @pranavkm / @dougbu any other guesses what could be going on here?

**Comment by dougbu** [comment]
Is the failure identical on the Linux system? `The reference assemblies for framework ".NETFramework,Version=v4.5.2" were not found.` problems on that platform were due to a package that @pranavkm fixed a few days ago. But, you might need to delete the `~/.nuget/packages/netframeworkreferenceassemblies` folder to get the update.

On Windows, @Eilon provided the download link for the .NET 4.5.1 developer pack. But, you need the 4.5.2 pack: https://www.microsoft.com/en-us/download/details.aspx?id=42637

**Comment by dougbu** [comment]
Likely a good idea to delete the `.build` (note leading period) folder in your Mvc repo.

**Comment by RemiBou** [comment]
@dougbu I'm on windows, I don't know about Linux.
After deleting .build folder, still the same : [Paste bin](http://pastebin.com/00T9PbW4)

.net 4.5.2 is already installed.

**Comment by RemiBou** [comment]
@dougbu I deleted the .build, installed the other developer pack, but still the same errors

**Comment by yuleyule66** [comment]
I also have the same problem in Visual Studio 2017 RTM, That's how I solved it:
OS:  win 10 
Steps:
1. `git clone https://github.com/aspnet/Mvc.git`
2. cd Mvc
3. ./build.cmd
Maybe the third step there will be a failure, you need to try a few times more.
If still have error, you need to try:
```
PS D:\Mvc> dotnet restore Mvc.sln --configfile NuGet.config
PS D:\Mvc> dotnet build Mvc.sln
```
If build successful on the command line, you can open the Visual Studio, and do some Settings: 
![](http://images2015.cnblogs.com/blog/250417/201703/250417-20170316113855073-2058657791.png)

Then open the Mvc.sln, and Rebuild Solution.

**Comment by RemiBou** [comment]
@yuleyule66 I'm using VS Code

**Comment by Eilon** [comment]
Closing because we haven't seen further reports of this. If anyone is still having issues, please log a new issue w/ details and we will investigate. Thanks!
