### ISSUE TITLE
Adding multiple InputTagHelper breaks "checkbox" functionality

### ISSUE THREAD

**Issue by ashleyglee** [aspnet/Mvc#5902]
As documented [here](http://stackoverflow.com/questions/42544961/asp-net-core-custom-input-tag-helper-rendering-duplicate-checkboxes), "checkbox" inputs do not work the same as all other input elements.  The fix mentioned on stackoverflow is only a hack if you are using a single InputTagHelper.

If you create a custom TagHelper that inherits from InputTagHelper, the attributes cascade for each input element, so that if you add additional functionality such as adding an additional attribute, then the attributes get picked up.  In the current code, you end up with same same number of "checkbox" and "hidden" elements as the number of InputTagHelpers you use, but only for "checkbox".  All other input elements work correctly.  Also, you can see that each new checkbox only has attributes for the specific custom InputTagHelper that is used, and the attributes don't get merged like the other input elements do.

This is what I end up with the current code:

```html
<input data-val="true" data-val-required="The UsingCreditCard field is required." id="UsingCreditCard" name="UsingCreditCard" type="checkbox" value="true" />
<input name="UsingCreditCard" type="hidden" value="false" />
<input disabled="disabled" id="UsingCreditCard" name="UsingCreditCard" type="checkbox" value="true" />
<input name="UsingCreditCard" type="hidden" value="false" />
<input data-agl="agl" id="UsingCreditCard" name="UsingCreditCard" type="checkbox" value="true" />
<input name="UsingCreditCard" type="hidden" value="false" />
```

Instead of this:

```html
<input data-agl="agl" data-val="true" data-val-required="The UsingCreditCard field is required." disabled="disabled" id="UsingCreditCard" name="UsingCreditCard" type="checkbox" value="true" />
<input name="UsingCreditCard" type="hidden" value="false" />
```

**Comment by dougbu** [comment]
The wrapping isn't necessary in the default case but it must happen some of the time.

`ViewContext.FormContext.CanRenderAtEndOfForm` is normally `true`. In that case, the `InputTagHelper` could skip wrapping the `type="checkbox"` element in the `output.Content` wrapper. I.e. it could do the same thing as for other `<input/>` `type`s:
``` c#
// This TagBuilder contains the one <input/> element of interest.
output.MergeAttributes(tagBuilder);
if (tagBuilder.HasInnerHtml)
{
    // Since this is not the "checkbox" special-case, no guarantee that output is a self-closing
    // element. A later tag helper targeting this element may change output.TagMode.
    output.Content.AppendHtml(tagBuilder.InnerHtml);
}
```

However,
- This is not correct when ``ViewContext.FormContext.CanRenderAtEndOfForm == false`. Layering would need to be available (though conditional).
- This is a (small?) breaking change that may affect developers subclassing `InputTagHelper`.
- It's not clear how important a fix would be. Calling `GenerateCheckBox()` repeatedly accidentally or on purpose is a very strange thing to do. And, `output.Content` is still used; so there's minimal performance difference (just reduces the lifetime of an `IHtmlContent` implementation).

Generally, I do not recommend we move forward with the changes you proposed in #5903. I leave it to our __Triage__ team to decide whether _some_ change would be worthwhile in this area.

**Comment by mkArtakMSFT** [comment]
Hi @ashleyglee. Thanks for contacting us. It seems this issue wasn't something we've seen much interest from the community, and it's not a priority for us at the moment. So we're going to close it for now. If the situation changes in the future and we'll see higher demand of this feature from the community, we'll reconsider it.
