### ISSUE TITLE
3 tests fail when core.autocrlf=input on Windows

### ISSUE THREAD

**Issue by ctaggart** [aspnet/Mvc#5907]
Per https://github.com/aspnet/Mvc/pull/5905#discussion_r104338394, I'm opening this bug. You can see the failed tests and the branch here:
https://ci.appveyor.com/project/ctaggart/mvc/build/18/tests

The only change was:
https://github.com/ctaggart/Mvc/commit/4800cd44cbc85eae39241b681c71d979faee54f8
```
git config --global core.autocrlf input
```

Which tells git not to change the line endings in the working directory. In-other-words, they end up with LF like they are in the git repository instead of CRLF. true & false both result in CRLF. I hacked in fixes into #5905. Please review and fix appropriately.

**Comment by dougbu** [comment]
I took a quick look at this because the fixes proposed in #5905 concerned me. Will send out a PR tomorrow morning, after confirming my changes don't break anything with `core.autocrlf=false` on Windows.

**Comment by dougbu** [comment]
b6a6b50
