### ISSUE TITLE
Code base and VS2017 question

### ISSUE THREAD

**Issue by jkvargas** [aspnet/Mvc#5908]
Hello,
I am having trouble to build the solution using the mvc.sln with visual studio 2017.
How can I build my app using the source in a way i can debug the app into the mvc source code?
I do have a controller's method with a HttpPost attribute and I would like to see how it deserialize the json into  an object of MyClass.

Thank you very much.

**Comment by Eilon** [comment]
@dougbu ?

**Comment by dougbu** [comment]
@jkvargas Visual Studio 2017 should reach RTM soon. The new version has substantial improvements over the release candidate. So, if your comment is primarily about slow performance (at worst hangs) when you have the Mvc solution open, just hang on a bit longer.

If your comment is about something else, please clarify.

**Comment by yuleyule66** [comment]
I also have the same problem in Visual Studio 2017 RTM, That's how I solved it:
OS:  win 10 
Steps:
1. `git clone https://github.com/aspnet/Mvc.git`
2. cd Mvc
3. ./build.cmd
Maybe the third step there will be a failure, you need to try a few times more.
If still have error, you need to try:
```
PS D:\Mvc> dotnet restore Mvc.sln --configfile NuGet.config
PS D:\Mvc> dotnet build Mvc.sln
```
If build successful on the command line, you can open the Visual Studio, and do some Settings: 
![](http://images2015.cnblogs.com/blog/250417/201703/250417-20170316113855073-2058657791.png)

Then open the Mvc.sln, and Rebuild Solution.

**Comment by Eilon** [comment]
With the latest builds of VS2017, especially the Update 3 Preview 1 release from this week, these issues should generally be gone.
