### ISSUE TITLE
Localization and ModelBinding

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#591]
`ValueProviderResult` needs to use the request culture to parse values. In Mvc5, we used `Thread.CurrentCulture` which would give us the request culture. HttpAbstractions doesn't expose this in any way - my guess is that this would be part of the API layer that is used to parse other things such as Content-Type etc.

**Comment by yishaigalatzer** [comment]
Get it from `CultureInfo.CurrentCulture`

**Comment by Eilon** [comment]
Need to do whatever we did in MVC 5. E.g. the Route Data value provider should use InvariantCulture, and most (or all?) of the other value providers should use CurrentCulture.

**Comment by pranavkm** [comment]
@Eilon does `CurrentCulture` reflect the request culture now?

**Comment by rynowak** [comment]
I think the point is that it will soon. Regardless of the use of middleware that sets the culture based on the thread, I think we still want to use CurrentCulture where appropriate

**Comment by Eilon** [comment]
@rynowak correct. MVC should have the "right code" as soon as possible. Not everyone will use the localization/request culture middleware anyway.

**Comment by rynowak** [comment]
Reviewed these and no action needs to be taken, we have MVC5/WebAPI2 behavior already: 
- QueryString = InvariantCulture
- RouteData = InvariantCulture
- FormData = CurrentCulture
