### ISSUE TITLE
Revisit the architecture of CompilerCache

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#5912]
@rynowak and I had a look at the CompilerCache and the design of the type looks like it could be refactored \ simplified. Creating a work item for us to revisit this.

**Comment by Eilon** [comment]
What are the general concerns?

**Comment by rynowak** [comment]
The code is wack yo.

**Comment by Eilon** [comment]
Thanks 😄

**Comment by rynowak** [comment]
Specifically the part of the API that exists is bad. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/CompilerCache.cs#L70

It's a big complicated internal thing that seems to get rewritten each time the requirements change (pages, precompilation). It would be nice to turn this into a public API that wouldn't be a disaster for someone else to use. As it stands, it would be very very hard for anyone to reuse this in writing their own `IViewEngine` even though it's general enough that you could.
