### ISSUE TITLE
AmbigousActionException on same Action

### ISSUE THREAD

**Issue by glatzert** [aspnet/Mvc#5914]
We are using conventions to set up routing to our mvc actions.
Essentially the conventions are:

Add a template like this <LastNamespaceIfNotController>/[controller]/[action]
Then add three other templates to HomeController IndexAction: "/", "/Home" and "/Home/Index"

Now - on calling Home/Index there will mutiple routes be matching.
I get the following error:

> AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:
> 
>  MyProject.Web.Controllers.HomeController.Index (MyProject.Web)
>  MyProject.Web.Controllers.HomeController.Index (MyProject.Web)

I suggest the ActionSelector.SelectBestCandidate should be extended to make that list distinct.

**Comment by rynowak** [comment]
Can you please share the code (just the action/controller definition)? That will help us figure out what's going on.

**Comment by glatzert** [comment]
Here you go:
```
    class ControllerRouteConvention : IControllerModelConvention
    {
        public void Apply(ControllerModel controller)
        {
            var hasRouteAttribute = controller.Selectors.Any(s => s.AttributeRouteModel != null);
            if (hasRouteAttribute)
                return;

            var baseNamespaces = (typeof(Controllers.ControllerBase)).Namespace.Split('.').Last();
            var controllerNamespace = controller.ControllerType.Namespace.Split('.').Last();

            var template = "/[controller]/[action]";
            if (!string.Equals(baseNamespaces, controllerNamespace, StringComparison.OrdinalIgnoreCase))
                template = $"/{controllerNamespace}{template}";

            foreach (var selector in controller.Selectors)
                selector.AttributeRouteModel = new AttributeRouteModel() { Template = template };
        }
    }

    class DefaultActionRouteConvention : IActionModelConvention
    {
        public void Apply(ActionModel action)
        {
            var isDefaultAction =
                string.Equals(action.ActionName, "index", StringComparison.OrdinalIgnoreCase) &&
                string.Equals(action.Controller.ControllerName, "home", StringComparison.OrdinalIgnoreCase);

            if (!isDefaultAction)
                return;

            SetDefaultRoute(action);
        }

        private void SetDefaultRoute(ActionModel action)
        {
            var templates = new[] { "/" };
            var selectors = action.Selectors.ToList();
            foreach (var selector in selectors)
            {
                foreach (var template in templates)
                {
                    var newSelector = new SelectorModel(selector);
                    newSelector.AttributeRouteModel = new AttributeRouteModel { Template = template };

                    action.Selectors.Add(newSelector);
                }
            }
        }
    }
```

And the controller in question here:
```
public class HomeController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (HttpContext.IsAjaxRequest())
                return PartialView("_EmptyDashboard");

            return View();
        }
    }
```

**Comment by rynowak** [comment]
This issue here is with `DefaultActionRouteConvention`. You're adding 3 new conventions, but not removing the original one so you end up with 4.

![image](https://cloud.githubusercontent.com/assets/1430011/23759294/2f1d65a6-04a1-11e7-918c-0cfe6b0201b0.png)

`action.Selectors[0]` is the original one, and it will combine with the route on the controller to match `/Home/Index`.

**Comment by glatzert** [comment]
For a quick workaround i restrained myself to "/" on the default action - and that is not making any problems for me.. 
Independent of my not-so-good usage (and probably use-case) here, I still think the AmbigousActionException is not correct here.

**Comment by Eilon** [comment]
Closing because there are no plans to make further improvements in this area.
