### ISSUE TITLE
DotNetCore-1.1.1-WindowsHosting.exe - No Download or No Longer Exists/Needed?

### ISSUE THREAD

**Issue by Wayne-Mather** [aspnet/Mvc#5917]
Hi,

I have noticed the new SDK/Runtime has been published on [https://www.microsoft.com/net/download/core](https://www.microsoft.com/net/download/core) but I see no DotNetCore-1.1.1-WindowsHosting.exe

Do I still need this product to run my sites under IIS on Windows 10/Windows 2016 Operating Systems? Or can I just publish to my existing infrastructure setup with DotNetCore.1.1.0-WindowsHosting.exe

Thanks for any information supplied.

**Comment by Eilon** [comment]
@Wayne-Mather sorry about that, we're actually working on updating that installer. We built a new version of it, and right now we're doing some testing. We should have it out later this week!

cc @muratg @joeloff

**Comment by Wayne-Mather** [comment]
@Eilon No worries at all, was just wondering if something had changed and I was not aware of it

**Comment by Eilon** [comment]
@Wayne-Mather to be honest, what changed was that we forgot we needed to update this installer, and now we're working on it 😄

**Comment by Wayne-Mather** [comment]
@Eilon if you have any early release binaries, would love to test so that I can hold back our rollout. My application is about to go run in remote areas behind satellite links and really want to deploy on the VS2017/1.1.1 train before they head out and start replicating data back to head office.

**Comment by Eilon** [comment]
@Wayne-Mather the build should be ready today or tomorrow, so hopefully you won't have to wait too long!

**Comment by Eilon** [comment]
@Wayne-Mather the build is available here: https://go.microsoft.com/fwlink/?linkid=844461

Thanks!

**Comment by muratg** [comment]
@Wayne-Mather this is ready now [https://go.microsoft.com/fwlink/?linkid=844461]

**Comment by Wayne-Mather** [comment]
@Eilon you already know, but worked without a hiccup :)

**Comment by Eilon** [comment]
Awesome!
