### ISSUE TITLE
Strings that can be parsed as a Boolean should be an acceptable value for a checkbox

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#5919]
Logging this issue to track this PR: https://github.com/aspnet/Mvc/pull/5845

> If the asp-for value is string with the values "true" or "false" the code is able to process that as valid boolean and generate a proper checkbox around that.

> However the typeof check in the GenerateCheckBox method prevents that.

cc @Elfocrash @dougbu

**Comment by dougbu** [comment]
015dafc

**Comment by dougbu** [comment]
Thanx @Elfocrash!
