### ISSUE TITLE
Crazy Idea: Convenience methods with value-tuple for URL generation

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5922]
**Today**
```
Url.Action("Edit", "Widgets", new { id = 17});
```

**Future**
```
Url.Action("Edit", "Widgets", ("id", 17));
```

This is a little less clumsy than the anonymous typed literal syntax and requires less reflection.

Example signature:
```
public static string Action(this IUrlHelper url, string action, string controller, params ValueTuple<string, object>[] values)
```

**Comment by mkArtakMSFT** [comment]
Closing this, as there was no much interest for this. Also, it's not a priority at the moment.
