### ISSUE TITLE
Visual Studio 2017 - Enable View PreCompilation?

### ISSUE THREAD

**Issue by Wayne-Mather** [aspnet/Mvc#5924]
Hi,

I saw the Scott Hunter video that said PreCompiliation on publish steps is now enabled in this release. Currently I cannot  find how to enable Razor View PreCompilation in Visual Studio 2017 (Professional).

Is there some information or do I install the Microsoft.AspNetCore.Mvc.Razor.ViewCompilation which was last published to nuget in 2016 to get this option to "Light Up"

**Comment by pranavkm** [comment]
@Wayne-Mather, this is for an earlier release, but the instructions are still the same: https://github.com/aspnet/MvcPrecompilation/issues/71

**Comment by Wayne-Mather** [comment]
@pranavkm Thanks, just adding the section to the property group of csproj fixed it for me. Because PreCompile for project.json on the fast train did not work for me I was not using it. Because of this the upgrade did not modify the csproj as required (but it did add the required nuget packages).
