### ISSUE TITLE
Tests for DefaultPageLoader

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#5927]
Currently there are no tests for DefaultPageLoader, let's add some.

**Comment by hishamco** [comment]
https://github.com/aspnet/Mvc/blob/297196baa0d4a28a4f71d0b4bba2d5b942af6190/test/Microsoft.AspNetCore.Mvc.RazorPages.Test/Internal/DefaultPageLoaderTest.cs

**Comment by ryanbrandenburg** [comment]
Yep, looks like @rynowak has taken care of this, closing.
