### ISSUE TITLE
Is there any tag helper to add prefix to img' src attribute?

### ISSUE THREAD

**Issue by xiaoxin01** [aspnet/Mvc#5929]
Hi, 

I want to do some thing like this:

```
<img src="a.jpg" asp-append-cdn=true />
```

render as:

```
<img src="http://somecdn/a.jpg" />
```

Is there any way to do this?

**Comment by Eilon** [comment]
I don't believe any built-in tag helpers do this. You could certainly write your own tag helper to do this.
