### ISSUE TITLE
Fix error message/string(s) that reference project.json

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#5931]
Such as this: https://github.com/aspnet/Mvc/blob/rel/1.1.2/src/Microsoft.AspNetCore.Mvc.Razor/Internal/DefaultRoslynCompilationService.cs#L158

And we should scan the entire repo for any other references.

Does this seem worth porting to patch releases? How obscure is this?

**Comment by DamianEdwards** [comment]
I think we should fix this (these) in the next patch.

**Comment by pranavkm** [comment]
The specific error you listed we've fixed in dev - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/DefaultRoslynCompilationService.cs#L153. We only need this work item for a patch release.

**Comment by Eilon** [comment]
Oh right I remember this. Is it broken in 1.0.x and 1.1.x?

**Comment by pranavkm** [comment]
It is. Note: It's generally less likely you'd run in to this error now since `PreserveCompilationContext` is opt-out unlike in project.json where this was opt in.

**Comment by DamianEdwards** [comment]
People starting with empty .NET Console app and then adding ASP.NET Core will hit this. We still do that in some demos, docs, etc.

**Comment by Eilon** [comment]
Ok, so putting this in 1.1.3 then.

**Comment by Eilon** [comment]
This patch fix is *approved*. Please follow the normal code review / pull request process and make sure you make the change in the correct branch.

**Comment by Eilon** [comment]
Close this bug?

**Comment by Eilon** [comment]
Preview builds of this patch fix should be available on the following feeds:

* https://dotnet.myget.org/gallery/aspnet-1-0-5-may2017-patch-public (for fixes in the 1.0.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-0-5-may2017-patch-public/api/v3/index.json
* https://dotnet.myget.org/gallery/aspnet-1-1-2-may2017-patch-public (for fixes in the 1.1.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-1-2-may2017-patch-public/api/v3/index.json

If you have a chance, please try out these preview builds and let us know if you have any feedback!
