### ISSUE TITLE
Support IsPost & IsAjaxPost properties

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#5937]
_From @hishamco on September 8, 2016 14:21_

For those who are using ASP.NET Web Pages heavily, of course they will notice that the property `IsPost` property is very handy in razor files, specially when they want to show or hide parts if the page is posted.

/cc @DamianEdwards @rynowak 

_Copied from original issue: aspnet/RazorPages#38_

**Comment by hishamco** [comment]
If you're agreed with this, I can make a design PR for this

**Comment by Eilon** [comment]
Sorry, no plans to bring the Web Pages behavior into the mix.

**Comment by hishamco** [comment]
`IsPost` is very useful for the developers instead of do the checks the `Request.Method` themselves, IMHO such property will be more valuable even it be added as extension method

**Comment by Eilon** [comment]
I think the idea is that the post-specific code would normally go in the Post/PostAsync method.

**Comment by hishamco** [comment]
Yep .. I forgot that we add those at last stage of the prototype 😄
