### ISSUE TITLE
Can we make TryUpdateModel better for "page as view model" scenario

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#5938]
_From @DamianEdwards on August 17, 2016 17:50_

[This line](https://github.com/aspnet/RazorPages/blob/master/samples/RazorPages.Samples.Web/Pages/Index.razor#L30) isn't as nice as I'd hoped: `await TryUpdateModelAsync(Customer, "Customer");`

When using the page as the view model, you have to pass the prefix name to `TryUpdateModelAsync` to get it to correctly bind values to the sub-properties. I understand why, but it seems sub-optimal.

Open to suggestions on how we might improve this.

_Copied from original issue: aspnet/RazorPages#23_

**Comment by Eilon** [comment]
_From @rynowak on August 17, 2016 17:56_

What does your form look like? Do you need to use a prefix in the form?

Alternative would be something like `await TryUpdateModelAsync(_ => Customer)` - we can get a name from the expression.

I have strong feelings in particular about MVC's autoprefixing behavior and the ambiguities it creates. I'm trying to balance my desire not to let it spread with consistence with controllers.

**Comment by Eilon** [comment]
_From @DamianEdwards on August 17, 2016 17:58_

Form is [here](https://github.com/aspnet/RazorPages/blob/master/samples/RazorPages.Samples.Web/Pages/Index.razor#L103):

``` html
<form method="post" class="form-inline">
    <div class="form-group">
        <label asp-for="Customer.Name"></label>
        <input asp-for="Customer.Name" class="form-control" />
    </div>
    <input type="submit" value="Add Customer" class="btn btn-primary" />
    <div asp-validation-summary="@ValidationSummary.All" class="text-danger"></div>
</form>
```

**Comment by Eilon** [comment]
_From @rynowak on August 17, 2016 17:59_

I see, you need the form because it's a sub-property of the 'page'. We could patternize this in a better way then like `TryUpdateProperty(_ => Customer)`

**Comment by Eilon** [comment]
_From @DamianEdwards on August 17, 2016 18:3_

`TryUpdateProperty(Customer)` would work just as well wouldn't it? Is the expression required?

**Comment by Eilon** [comment]
_From @rynowak on August 17, 2016 18:14_

The expression is required without doing compiler magic. `asp-for` works because we implement compiler magic.

We can keep turning the crank here and see if we come up with something better that isn't in the same flavour as `TryUpdateModelAsync`.

For instance if we tweaked your example:

```
<form method="post" class="form-inline" asp-scope="Customer">
    <div class="form-group">
        <label asp-for="Customer.Name"></label>
        <input asp-for="Customer.Name" class="form-control" />
    </div>
    <input type="submit" value="Add Customer" class="btn btn-primary" />
    <div asp-validation-summary="@ValidationSummary.All" class="text-danger"></div>
</form>
```

The new `asp-scope` could manipulate the form fields that are generated so that they don't use the `Customer` prefix, and then normal `TryUpdateModel` would work.

We need to do more lateral thinking on this if the expression isn't good enough.

**Comment by Eilon** [comment]
_From @rynowak on August 17, 2016 18:15_

Thinking back on this:

> The new asp-scope could manipulate the form fields that are generated so that they don't use the Customer prefix, and then normal TryUpdateModel would work.

Why isn't `@model` a good solution in this case? is it because you're building multiple forms?

**Comment by Eilon** [comment]
_From @DamianEdwards on August 17, 2016 18:24_

It seems a little awkward to set `@model Customer` when using properties directly on the page. It would generate a `Model` property and then you have to decide whether to use `@Model.Blah` or `@PageProperty.Blah` depending on the context in the HTML and page actions.

**Comment by Eilon** [comment]
_From @dougbu on August 18, 2016 16:52_

Why exactly is `Model` not available in page actions? Is that just fallout from not using the `.cshtml` extension and tooling for now?

**Comment by Eilon** [comment]
_From @DamianEdwards on August 18, 2016 19:23_

@dougbu it is. You can choose to use `@model` and it will behave as it does today, but for page-focused scenarios I think it can be a bit limiting. We're looking more at the idiomatic thing being the page **is** the view model.

**Comment by rynowak** [comment]
Parking this in "needs design" for now while we implement other kinds of binding functionality. Will revisit to see if we need this later.

**Comment by rynowak** [comment]
We think binding to properties solves all of the concerns here. If we find a gap we will reopen this
