### ISSUE TITLE
Async APIs on TempData related apis (ITempDataDictionary, ITempDataProvider etc.)

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#5941]
When TempData is used like a dictionary in an action (ex: var foo = TemData["foo"]), we load the temp data in a synchronous way. If the provider is  SessionStateTempDataProvider, where Session is stored in a database for example, we would be blocking threads. 

With support of binding TempData to controller's properties, we could consider adding async apis as the infrastructure could load the data in async way. Presence of at least a single tempdata property would result in trying to load tempdata for all the actions even though some of them might not use it, so we would be increasing the chances of threads being blocked.
Original discussion here: https://github.com/aspnet/Mvc/pull/5872#discussion_r105104332

@rynowak @DamianEdwards

**Comment by DamianEdwards** [comment]
This has come up before somewhere, I can't remember where. Customers can work around this by adding a call to load the session data async during the request pipeline, before `TempData` is used. Perhaps we could have a filter that does that, triggered by an attribute? That way, to force async loading you could just decorate your action method with an attribute. Or something else like that.

**Comment by rynowak** [comment]
I know some folks like @Tratcher discussed with me the idea of MVC eagerly loading session via a filter. Personally I like the idea of decoupling this from temp data.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Mvc/issues/6463

**Comment by rynowak** [comment]
DOPE

Yeah, and really the idea of making the temp data provider into the thing that async loads the session is just redundant with this idea, which we should probably do anyways. I'd steer someone using session to just apply that filter globally and use session for temp data since it's more better anyway.

**Comment by Eilon** [comment]
I'm closing this because if we implement https://github.com/aspnet/Mvc/issues/6463, you could solve it that way, and the default is now cookie TempData, so most people won't be impacted anyway.
