### ISSUE TITLE
__Generated__ ViewComponentTagHelper error in VS 2017 and Razor Language Services

### ISSUE THREAD

**Issue by Ponant** [aspnet/Mvc#5943]
Used the official release of VS 2017 with the [Razor Language Services](https://marketplace.visualstudio.com/items?itemName=ms-madsk.RazorLanguageServices) to properly render Tag Helpers with syntax highlighting etc. I made a new fresh project starting with .Net Core 1.1, and I can confirm that this issue is reproducible.

Create a View Component (here I call it `MainMenuViewComponent`) and invoke it in a view, say the `_Layout.cshtml`, as such

`<vc:main-menu></vc:main-menu>`

The app runs and correctly displays the result of the view component. However, close and reopen the view file (or VS 2017), and one gets

`Error CS0400 The type or namespace name '__Generated__MainMenuViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
`

Disabling Razor Language Services will remove this error, but you lose intellisense.
cc @madskristensen

**Comment by Eilon** [comment]
This issue was moved to aspnet/Razor#1074
