### ISSUE TITLE
Unable to install into NetStandard library

### ISSUE THREAD

**Issue by tidyui** [aspnet/Mvc#5946]
Hi there, I have a question. I'm porting the codebase of my CMS-library (Piranha CMS) to NetStandard and was hoping to make it cross-platform & multi-framework (.NET Core & Full .NET). As AspNetCore.Mvc can be used in both Core and Full Mvc this looked promising, **however**:

In order to provide a single admin-interface to support both frameworks I have to have a library with controllers & embedded views that are referenced from the executing application (which can be Core or Full .NET), however it appears that the package `Microsoft.AspNetCore.Mvc` can't be added to a NetStandard a library, it needs a runtime. 

What were you decisions for this design choice, or is it maybe just me doing something wrong because it's quite limiting.

Best regards

Håkan

**Comment by tidyui** [comment]
I figured out the problem, so let me clarify a bit :)

* In order to create a NetStandard library that can be consumed by both `core` and `.NET Framework` the safest choice atm seem to be `1.4` which maps to `4.6.1`.
* `Microsoft.Aspnet.Mvc` references NetStandard `1.6` **but** it is also cross-compiled against .NET `4.5.1`.
* Unfortunately this means you can't make a generic cross-framework NetStandard library that references the mvc-package without making a dual compile like the mvc-package has.

Regards

**Comment by danroth27** [comment]
You can create a single library if you instead target .NET Standard 1.6. You only need to cross compile if you want to support older .NET Framework versions.
