### ISSUE TITLE
ImATeapotResult missing

### ISSUE THREAD

**Issue by shravan2x** [aspnet/Mvc#5947]
This is _serious_ missing functionality in MVC 6. I'm aware we can do `StatusCode(418);`, but we need to be able to do `return ImATeapot();`.

Adding this would make the lives of teapot programmers a **lot** better.

On a side note:
1. We also need a `MethodNotFound()`.
2. When a corresponding action with the right method is not found in a controller, a 405 should be sent instead of a 404 (See [this](https://github.com/aspnet/Mvc/issues/388)).
3. We need the ability to send custom status descriptions (`200 OK`, `500 I'm fine`, `404 Eaten by dog`, `404 Abducted by aliens`, etc).

**Comment by Eilon** [comment]
Sorry, April 1st is still a couple weeks away! 😄

**Comment by shravan2x** [comment]
@Eilon Can we currently send custom status descriptions? I tried `return StatusCode(404, "Something");` but that wasn't quite right.

**Comment by Eilon** [comment]
@shravan2x I don't believe that's supported because it's not standard or something like that. @Tratcher would know more.

**Comment by Eilon** [comment]
Some info here: https://github.com/aspnet/HttpAbstractions/issues/395

**Comment by shravan2x** [comment]
From what I gather, the main reason for it being removed is that it is not standard and HTTP/2 removes it. This is a fairly good reason to remove it, but some points:

1. HTTP 1.1 is not going away anytime soon.
2. The majority of browsers don't care about the status description, allowing servers to modify them without an issue.
3. Enabling simpler usage allows us to play around with them, perhaps as an April fools joke or such.

I understand we would ideally abstract the entire feature away, but could there not just be an overload to allow its modification?

**Comment by Eilon** [comment]
Hey, I'm all for April Fools jokes, but unfortunately we have to balance the desire to have fun with the desire to ship this product 😄
