### ISSUE TITLE
View helper @Json.Serialize does not HTML escape by default

### ISSUE THREAD

**Issue by DaniJG** [aspnet/Mvc#5949]
The [`JsonHelper`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/JsonHelper.cs) does not HTML escape values by default and just uses whatever global JsonOutputFormatter options were configured.

As of today, it is posisble to create a new 1.1 project and write the following code on a view, which ends up in the alert being displayed:

```
@{
    var model = new
    {
        prop1 = 1,
        prop2 = "</script><script>alert('hello world');</script>",
        prop3 = false
    };
}
<script>
    var foo = @Json.Serialize(model);
</script>
```

This can be mitigated by explicitly passing the formatting options to that helper, setting JSON.Net's  [`StringEscapeHandling`](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_StringEscapeHandling.htm) option  as EscapeHtml:

`var foo = @Json.Serialize(model, new JsonSerializerSettings { StringEscapeHandling = StringEscapeHandling.EscapeHtml });`

It could also be set as the default Json formatting options, but then that would apply to any JSON included in the response of an API which might not be what you want.

`services.AddMvc().AddJsonOptions(opts => opts.SerializerSettings.StringEscapeHandling = StringEscapeHandling.EscapeHtml)`

Could this be the default behavior of `JsonHelper`  regardless of the default options? As if it would take the default options and merge them with `StringEscapeHandling` as `EscapeHtml`.

**Comment by Eilon** [comment]
Thanks, this was fixed in the recent ASP.NET Core patch releases from May 2017.
