### ISSUE TITLE
Support model binding to Razor Pages properties on page and PageModel classes

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#5952]

**Comment by pranavkm** [comment]
Would we bind properties on the page and the model or just the model if both are available?

**Comment by DamianEdwards** [comment]
It would be based on the presence of an attribute (let's start with `ModelBinder` is it?) but should match the behavior for page handler processing I think, I.e. does OnGet() on the page get called if I have a model?

**Comment by pranavkm** [comment]
> does OnGet() on the page get called if I have a model?

Nope. The model wins if it's present. Ok, seems straightforward, find properties with `ModelBinder` on the type that has the executing handler and bind them.

**Comment by DamianEdwards** [comment]
Yep, let's start there and we'll tweak after use if necessary.

**Comment by pranavkm** [comment]
@DamianEdwards \ @rynowak  - what's the behavior for model binding in GET requests? Right now I have it enabled. However if you have models with validation, the ModelState is invalid at that point. I had to do things like:

```C#
@if (Context.Request.Method == "POST")
{
   @Html.ValidationSummary()
}
```

to avoid seeing validation errors on my first GET.

**Comment by pranavkm** [comment]
I'll add a couple more functional tests for a combination of property + argument binding

**Comment by pranavkm** [comment]
Spoke to @DamianEdwards  and @rynowak offline and we decided to not model bind properties on GET requests.
