### ISSUE TITLE
Add convenience methods for redirecting from a Razor Page back to itself

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#5953]
Right now, you have to `return Redirect("/url/to/page")`. We should have a first-class method for this so that you don't have to pass in the URL, e.g. `return RedirectToSenf()`;

**Comment by rynowak** [comment]
@pranavkm - Let's make this a follow up to your current set of changes.

Add a `RedirectToPage()` and `RedirectToPage(object values)`. These call `RedirectToPage(string)` and `RedirectToPage(string, object)` respectively with the current page's name (from route values).

**Comment by rynowak** [comment]
1e7972b
