### ISSUE TITLE
Allow overriding of TempDataAttribute key so separate properties can be backed by same TempData value

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#5954]

**Comment by Eilon** [comment]
Need to figure out the scoping / prefix / naming rules for TempData in Razor Pages.

**Comment by rynowak** [comment]
@DamianEdwards ok to close?

**Comment by rynowak** [comment]
We still haven't come up with a need for this so I'm closing it. If we find a scenario where this matters we can bring it back.
