### ISSUE TITLE
Ensure trailing slash is present when generating URLs that resolve to "default document" Razor Pages, e.g. Index.cshtml

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#5955]
`/foo/bar` is different to `/foo/bar/` when the actual resource being served **is not** `/foo/bar` but rather `/foo/bar/Index.cshtml`.

We should try to ensure that the trailing slash is injected in cases where we generate or interpret URLs when we know it will server a default document, e.g. `return Redirect("~/customers")` where there is a `~/customers/Index.cshtml`

Related to #5921

**Comment by rynowak** [comment]
Parking this in "needs design" for now while we implement other kinds of URL generation functionality. Will revisit to see if we need this later.

**Comment by rynowak** [comment]
We think that this isn't needed for our key scenarios. If we find that this is important we will bring it back
