### ISSUE TITLE
Generated class for Razor Pages shows up in VS Solution Explorer when the CSHTML file is open in the editor

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#5957]
![image](https://cloud.githubusercontent.com/assets/249088/23873906/f624e348-07f0-11e7-8a02-a712a8b76692.png)

**Comment by DamianEdwards** [comment]
@rynowak @Eilon can you assign this one pls?

**Comment by rynowak** [comment]
Should we just slap an editorbrowsable.never on this?

**Comment by DamianEdwards** [comment]
Worth trying. Is that how generated files are usually suppressed?

**Comment by rynowak** [comment]
@DamianEdwards does this become a **good thing** if the names this generates aren't horrible?

**Comment by Eilon** [comment]
Should the user even know that there's this magical class that's generated? I didn't think the concern was how pretty it was.

BTW perhaps https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.compilergeneratedattribute(v=vs.110).aspx would make more sense as the attribute to use? (Assuming it does what we want.)

**Comment by JosefPihrt** [comment]
When implementing this, please make sure that generated code will be marked so it can be skipped by roslyn analyzers.

Another alternative to `CompilerGeneratedAttribute` would be to create partial class with generated content and mark it with `<auto-generated>` tag.

**Comment by rynowak** [comment]
Load Balancing to @NTaylorMullen - let's try `[CompilerGenerated]`

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Razor#1237
