### ISSUE TITLE
Use NPM and Gulp instead of Bower and Grunt

### ISSUE THREAD

**Issue by infinnie** [aspnet/Mvc#5969]
They are also easy to get started, in my opinion.

**Comment by danroth27** [comment]
We don't really use either directly. Our general philosophy is that you should use whatever client-side technology that make you happy and we will support the most popular options in our tooling. I believe we support all of these options in tooling today.

**Comment by infinnie** [comment]
What’s more, the latest stable version and the latest preview version of Bootstrap are not available on Bower. The latest version on Bower is v3.3.6 while even NuGet has v4.0.0-alpha6 available.

**Comment by ctolkien** [comment]
I think OP is referring to the templates shipped in VS2017 - the inclusion of bower (which is practically dead) is a weird one when they could just use NPM directly.

**Comment by infinnie** [comment]
@ctolkien as well as VS 2015.

**Comment by frankabbruzzese** [comment]
It is about a couple years some people is saying Bower is dead, but most of js packages still continue supporting it.

The point with npm is that packages should have the format of node.js modules,while Bower is simply neutral.

From a practical point of view a proper usage of npm modules would require a knowledge of WebPack, that people using just a few javascript in server based web pages often doesnt have. With Bower, instead, they just install the package and reference it in VS included minimizer\bundler that is super easy to use.

That is why VS default template uses Bower. 

On the other side, using Npm and Gulp is supereasy: just add a package.json and gulp file in the root of your project and you will have a great support for them. Easier adding those files for a client side techniques expert than using WebPack for a less expert one.

**Comment by ctolkien** [comment]
>From a practical point of view a proper usage of npm modules would require a knowledge of WebPack, that people using just a few javascript in server based web pages often doesnt have. With Bower, instead, they just install the package and reference it in VS included minimizer\bundler that is super easy to use.

The templates use bower for bootstrap, jquery and some jquery validation bits. There's no need to webpack or any other more complex build systems. It's literally `npm install` (as opposed to `bower install`) and then reference your assets in `node_modules` (as opposed to `bower_components`).

**Comment by frankabbruzzese** [comment]
@ctolkien ,
not exactly, at least you need gulp to move files under wwwroot, since at moments package.json is supported in the root of the project (if you want to use VS support).

Earlier VS templates contained also package.json and gulp, and used gulp to minimize and bundle js files. However, this was changed in favour of the easier to use VS minimizer/bundler. The problem being that a lot of programmers were not able to use Gulp.

Moreover, true that packages like unobtrusive validation supports npm, but in the wrong way, since they do not support modules but expose global objects, so as a matter of fact they do not conform with npm conventions. So I I am not sure it is agood idea to use their npm versions.

**Comment by frankabbruzzese** [comment]
Anyway, instead of discussing about VS default template, since, once learned how to do it, creating new VS project templates is quite easy, we may create GitHub repository that collects several As.net core Mvc templates targetting several situations

**Comment by infinnie** [comment]
https://github.com/aspnet/Tooling/issues/1021

**Comment by Aurobindoma** [comment]
Can u give me a detail procedure of how to use npm instead of bower in my visual studio 2017 15.7?
I'm a beginer. Please help me.

**Comment by danroth27** [comment]
@Aurobindoma Shawn Wildermuth has a nice blog post on using ASP.NET Core with NPM here: 
- https://wildermuth.com/2017/11/19/ASP-NET-Core-2-0-and-the-End-of-Bower

You might want to consider using LibMan:
- https://blogs.msdn.microsoft.com/webdev/2018/04/17/library-manager-client-side-content-manager-for-web-apps/
- https://blogs.msdn.microsoft.com/webdev/2018/04/18/what-happened-to-bower/
