### ISSUE TITLE
csc.exe The process was aborted due to an unhandled exception.

### ISSUE THREAD

**Issue by programmar297** [aspnet/Mvc#5974]
I published an MVC application to the server and it was running fine. Until I changed the application a bit and published it again.

The application runs fine on my local system but on the live server I get this error in the event viewer.

```
Application: csc.exe
Framework version: v4.0.30319
Explanation: The process was aborted due to an unhandled exception.
Exception information: System.MissingMethodException
stack:
    Location Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main (System.String [])
```

What is the problem?

**Comment by Eilon** [comment]
@programmar297 can you share some more info about which version of ASP.NET and MVC you're using? This sounds like MVC 5.x to me, but more info would be helpful. Also, do you know what changes you made to the app that happened before it started failing?

**Comment by nojaf** [comment]
I'm having the same problem, MVC 5 using the Roslyn compiler services.

nuget.config:
```xml
<package id="Microsoft.Net.Compilers" version="2.0.1" targetFramework="net452" developmentDependency="true" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.3" targetFramework="net452" />
```

web.config
```xml
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:6 /nowarn:1659;1699;1701" />
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:14 /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
    </compilers>
  </system.codedom>
```

My server has IIS7, could that be related?

**Comment by davidfowl** [comment]
@Eilon it is MVC 5, ASP.NET doesn't use `csc.exe`.

**Comment by nojaf** [comment]
My problem turned out to be using `Microsoft.Net.Compilers 2.0.1` on a server that has .NET 4.5.2.
The `2.01` requires .NET 4.6.
Reverting `Microsoft.Net.Compilers` to ` 1.3.2` resolved my issue.

**Comment by pranavkm** [comment]
Closing since @nojaf figured out a solution for this.
