### ISSUE TITLE
IAsyncResult doesn't write out the body string

### ISSUE THREAD

**Issue by johnnyasantoss** [aspnet/Mvc#5976]
Hello!

I'm having problems to use `IActionResult` in my project 😞 
I've been trying in many ways, to write a json into the body of a response, but unfortunately I didn't get any success so far.

#### Here's my code: 
```csharp
public class MyCustomResult : IActionResult
{
	public object Content { get; private set; }

	public MyCustomResult(object content)
	{
		Content = content ?? throw new ArgumentNullException(nameof(content));
	}

	public async Task ExecuteResultAsync(ActionContext context)
	{
		var response = context.HttpContext.Response;
		response.StatusCode = 400;
		response.Headers.Add("Help-Link", "http://www.contoso.com/help");

		var json = JsonConvert.SerializeObject(Content, Formatting.None);

		var ms = new MemoryStream();
		var bytes = Encoding.UTF8.GetBytes(json);
		int length = bytes.Length;

		await ms.WriteAsync(bytes, 0, length);

		response.ContentLength = length; //
		response.ContentType = "application/json";
		response.Body = ms;
		response.RegisterForDispose(ms);
	}
}
```

With this line `response.ContentLength = length;`, I receive a HTTP 500 with nothing written in the body, and an error in console output

```bash
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL3CKAEH83JI": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (0 of 26).
```

#### Things that I've already tried: 

 - Create a new `HttpResponse`
 - Flush the `Stream`
 - Respond without setting `Content-Type` or `Content-Lenght
 - Write directly in the stream in the body (**this works but I can't set `Content-Type` nor `Content-Lenght`**)

#### Sugestion

1. Remove the **setter** from `HttpResponse.Body`
If you can't use a different stream type or use another stream to write my response body, this has no use, right? 😖 

2. Check why the `MemoryStream` doesn't work for this case.

After some time, I finally got this. 👇 

#### Solution

```csharp
public async Task ExecuteResultAsync(ActionContext context)
{
	var response = context.HttpContext.Response;
	response.StatusCode = 400;
	response.Headers.Add("Help-Link", "http://www.pagueveloz.com.br/help");

	var json = JsonConvert.SerializeObject(Content, Formatting.None);

	var bytes = Encoding.UTF8.GetBytes(json);
	int length = bytes.Length;

        //this must be set before start writing into the stream
	response.ContentLength = length;
	response.ContentType = "application/json";

	await response.Body.WriteAsync(bytes, 0, length);
}
``` 

### Documentation

**Can anyone inform me how I suggest a example code or a change to [this][doc] documentation?**

So I can help others to get this quickly

 [doc]: https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.mvc.iactionresult

**Comment by rynowak** [comment]
I'd suggest using `ObjectResult` or one of the many built-in helper methods on `Controller` and `ControllerBase` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs#L351

**Comment by johnnyasantoss** [comment]
So no custom `IActionResult`s or the documentation repo link then? 😞

**Comment by rynowak** [comment]
Closing as this is answered. You don't need a custom action result for this, json serialization is provided by the framework.

To fix your sample code, don't write a memory stream, just write to `response.Body`. You need to set the content length and content type (all the headers) **before** writing to the body
