### ISSUE TITLE
ViewComponent tag helpers should be built with their own TagHelperDescriptor.Kind

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Mvc#5984]
Follow up to https://github.com/aspnet/Mvc/pull/5982

After the TagHelperDescriptor api cleanup, we now have a `Kind` property on TagHelperDescritptors. Currently the ViewComponent tag helpers are built with `ITagHelper` kind. They should have their own thing.

**Comment by rynowak** [comment]
This is done.
