### ISSUE TITLE
Input tag helper generates 2 inputs when adding an html attribute to TagHelperOutput Attributes collection

### ISSUE THREAD

**Issue by kshyju** [aspnet/Mvc#5986]
I extended the InputTagHelper to conditionally add `disabled="disabled"` attribute based on `asp-is-disabled` attribute.

    [HtmlTargetElement("input", Attributes = ForAttributeName)]
    public class MyCustomInput : InputTagHelper
    {
        private const string ForAttributeName = "asp-for";

        [HtmlAttributeName("asp-is-disabled")]
        public bool IsDisabled { set; get; }

        public MyCustomInput (IHtmlGenerator generator) : base(generator)
        {
        }

        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            if (IsDisabled)
            {
                var d = new TagHelperAttribute("disabled", "disabled");
                output.Attributes.Add(d);
            }
            //base.Process(context, output);   // commented for now
        }
    }

Now i use this like below

`<input type="text"  asp-for="Name" asp-is-disabled="true" />`

I hard coded true here, but it will be a C# expression which returns a boolean value. This works great. It generates the expected output.

`<input type="text" id="Name" name="Name" value="" disabled="disabled">`

But does not work when the **type is checkbox**

`<input type="checkbox"  asp-for="IsActive" asp-is-disabled="true"/>`

`IsActive `is boolean property of view model.

If i uncomment `base.Process(context, output);`, It does generate markup for  2 input elements, out of which the second one has the disabled attribute. 

```
 <input data-val="true" data-val-required="The IsActive field is required." id="IsActive" 
                             name="IsActive"  type="checkbox" value="true" />
<input name="IsActive" type="hidden" value="false" />
<input disabled="disabled" id="IsActive" name="IsActive" type="checkbox" value="true" />
<input name="IsActive" type="hidden" value="false" />
```

**Comment by Eilon** [comment]
I think this is essentially a dup of https://github.com/aspnet/Mvc/issues/5983. The way the checkbox tag helper works is that it discards the original tag itself and create two new HTML elements (one for the checkbox, one for the hidden input). Because of this, when another tag helper (such as yours) tries to modify the tag, it isn't modifying the right tag.

cc @NTaylorMullen
