### ISSUE TITLE
Add support for customizing HTML generation of select lists / groups / items

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#599]
For example we have received repeated requests for support of checkbox groups in MVC.

One approach might be to layer HTML generation for `@Html.DropDownList()` (or some new name for similar helpers) on our template infrastructure.  Generating checkbox groups would then require only creation of the appropriate template files.

This approach would still use existing code to determine the final `SelectListItem` instances to display.  IOW the first half of `HtmlHelper.GenerateSelect()` would be unchanged.

**Comment by danroth27** [comment]
Consider instead providing HTML templating support in Razor.

**Comment by pranavkm** [comment]
Some additional considerations listed here - https://github.com/aspnet/Mvc/issues/5098

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
