### ISSUE TITLE
Custom tuple variable names are not specified in API response

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5990]
_From @ChuckkNorris on March 13, 2017 18:32_

**Version Used**: 
.NET Core 1.1.1

**Steps to Reproduce**:

1. Create HTTP Get method in Controller returning a Tuple
```
[HttpGet]
public (string firstName, string lastName) Get() {
   return ("Tom", "Hanks");
}
```

2. Call Endpoint and view Result
`{ item1: "Tom", item2: "Hanks" }`

**Expected Behavior**:
Should return a json object with the keys named according to what was specified in the method.
`{ firstName: "Tom", lastName: "Hanks" }`

**Actual Behavior**:
`{ item1: "Tom", item2: "Hanks" }`

_Copied from original issue: aspnet/Home#1967_

**Comment by rynowak** [comment]
_From @Tratcher on March 17, 2017 22:53_

@rynowak?

**Comment by rynowak** [comment]
We don't currently provide this type information to JSON.Net, and I'm not entirely sure that JSON.Net would do anything with it.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.

**Comment by ChuckkNorris** [comment]
Then the workaround is to avoid using tuples as part of any API response it seems.

**Comment by Eilon** [comment]
The main problem with tuples is that they aren't really custom types. They're all just `ValueTuple<T1, T2, ...>` so the system would have to look at other metadata to "put everything together." In my opinion this indeed makes them a poor fit for APIs where you're usually interesting in having more formal type knowledge.

**Comment by ChuckkNorris** [comment]
Yea - it'd be more of a neat parlor trick for creating quick demos without needing classes.
I doubt anyone would actually use Tuples in a production application anyways.

No issues with this not being implemented - thanks for letting me know though!
