### ISSUE TITLE
How do I get line numbers in my logs?

### ISSUE THREAD

**Issue by Saticmotion** [aspnet/Mvc#5997]
I've published an asp.net core website on my server, and after getting reports of errors, I went to check my logs. There are exception, but they don't have line numbers, so it's hard to figure out what exactly went wrong. How do I enable line numbers?

Here are my dependencies. As you can see I'm on MVC 1.1.0, and I'm using the built in logging framework, Microsoft.Extensions.Logging version 1.1.1.

    "dependencies": {
		"Microsoft.AspNetCore.Razor.Tools": {
			"version": "1.0.0-preview2-final",
			"type": "build"
		},
		"Microsoft.EntityFrameworkCore.Tools": {
			"version": "1.0.0-preview2-final",
			"type": "build"
		},
		"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
			"version": "1.0.0-preview2-final",
			"type": "build"
		},
		"Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
			"version": "1.0.0-preview2-update1",
			"type": "build"
		},
		"Microsoft.Extensions.Logging": "1.1.1",
		"Microsoft.Extensions.Logging.Console": "1.1.0",
		"Microsoft.Extensions.Logging.Debug": "1.1.0",
		"Microsoft.NETCore.App": "1.1.0",
		"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
		"Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
		"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
		"Microsoft.AspNetCore.Mvc": "1.1.0",
		"Microsoft.AspNetCore.Routing": "1.1.0",
		"Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
		"Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
		"Microsoft.AspNetCore.StaticFiles": "1.1.0",
		"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
		"Microsoft.Extensions.Configuration.Json": "1.1.0",
		"Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
		"Microsoft.Extensions.Caching.Memory": "1.1.1",
		"MailKit": "1.10.1",
		"NWebsec.AspNetCore.Middleware": "1.0.0-gamma1-45",
		"Microsoft.Extensions.Configuration.Binder": "1.0.0",
		"Microsoft.AspNetCore.Session": "1.1.0",
		"Neostore.ImageSharp": "1.0.0",
		"Microsoft.EntityFrameworkCore": "1.1.1",
		"Microsoft.EntityFrameworkCore.Relational": "1.1.1",
	}

I initialize the logging framework with this code:
```
loggerFactory.AddConsole(Configuration.GetSection("Logging"));
loggerFactory.AddDebug();
```

Which reads the following section from appsettings.json:
```
	"Logging": {
		"IncludeScopes": false,
		"LogLevel": {
			"Default": "Warning",
			"System": "Warning",
			"Microsoft": "Warning"
		}
	}
```

**Comment by Eilon** [comment]
This issue was moved to aspnet/Logging#596
