### ISSUE TITLE
ScriptTagHelper uri template

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Mvc#5998]
please consider allowing more options on the ScriptTagHelper; current the version number can only be appended to the uri; however a large number of cdn have the version numbers in different locations.  a possible solution could be to provide a uri template with a token marking the location within the uri where a version number appears.

**Comment by mkArtakMSFT** [comment]
Hi @grahamehorner. Sorry for our late response. It looks like there was no much community interest in this request, hence we're going to close it for now, as it doesn't align with our priorities at the moment. /cc @DamianEdwards
