### ISSUE TITLE
FileResult forcing chunked encoding

### ISSUE THREAD

**Issue by shravan2x** [aspnet/Mvc#5999]
I have the following code in a program:

```
HttpContext.Response.ContentLength = data.Size;
return File(data.ToArray(), "image/png");
```

The program generates a PNG file and sends it back. The expected result here is that chunked encoding would not be used because the data size is explicitly declared, once via setting the `content-length` header and next because the length of the array can be determined.

In general, it is preferred that chunked encoding is not used because the client cannot monitor download progress. Is this a bug in MVC or is there a reason for this behavior? Can it be fixed?

**EDIT**: The [documentation](https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.mvc.filecontentresult) doesn't mention anything about this behavior either.

**Comment by Eilon** [comment]
@jbagga - can you take a look? It does seem like chunked encoding isn't necessary here, so not sure why that's happening.

cc @Tratcher in case you have any ideas on this...

**Comment by Tratcher** [comment]
@shravan2x 
What are the full headers received by the client?
Are you using this with IIS/Express?

**Comment by shravan2x** [comment]
@Tratcher No, I am using Kestrel. This is the full header response:

```
HTTP/1.1 200 OK
Date: Sun, 14 May 2017 01:23:50 GMT
Content-Type: image/png
Server: Kestrel
Transfer-Encoding: chunked
```

**Comment by rynowak** [comment]
I don't see anything on this code path that would un-set the content length. In fact ideally we'd be setting it for you. Someone needs to try this out and debug the issue 


We're literally just doing a `WriteAsync` and we only set the `Content-Type` and `Content-Disposition` headers.
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/FileContentResultExecutor.cs
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/FileResultExecutorBase.cs

**Comment by davidfowl** [comment]
Yea, I took a look as well. I'm assuming this bug report is a 1.x application?

**Comment by shravan2x** [comment]
@davidfowl Correct, I haven't had a chance to play around with 2.0 yet.

**Comment by davidfowl** [comment]
I can repro this.

**Comment by davidfowl** [comment]
It's the browser link middleware. Remove it and be happy 😄.

/cc @jodavis

**Comment by jbagga** [comment]
Confirmed that removing `app.UseBrowserLink()` solves the issue for 1.x. I was unable to reproduce with 2.0.

@shravan2x Can you let us know if @davidfowl's solution worked for you?

**Comment by shravan2x** [comment]
@jbagga I can confirm this. BrowserLink seems to have been causing the issue.

I haven't had a chance to play around with 2.0 yet, but you can close the issue it is fixed there.
