### ISSUE TITLE
Unable to place both value and `SelectListItem` enumeration in `ViewData` when using `@Html.DropDownList()` or `@Html.ListBox()`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#600]
Current code uses the legacy MVC approach of sharing the same `ViewData` slot for the default value and the `IEnumerable<SelectListItem>`.  This leads to user confusion and unnecessary constraints.  For example it is not currently possible to provide both a current value and the enumeration in `ViewData`.

One approach may be to find the `IEnumerable<SelectListItem>` at `{expression name}.$selectList`.  Pick your favourite name :smile_cat:

**Comment by dougbu** [comment]
as discussed in #1979, another symptom of this issue is that validation attributes are not generated when `@Html.DropDownList()` or `@Html.ListBox()` find the selected list in `ViewData`.  that additional symptom occurs because these `string`-based `<select/>` helpers find `ModelMetadata` about the select list rather than the model.

**Comment by dougbu** [comment]
updated suggested fix after a few design discussions:
- support a new, unique location for the select list in `ViewData` e.g. `ViewData["{model key}$select"]`
- to avoid compatibility breaks, check if `ViewData["{model key}$select"]` exists and fallback to `ViewData["{model key}"]` (the current `ViewData` entry) if not
- make the behaviour when `selectList: null` is passed very clear in IntelliSense for the affected methods

**Comment by pranavkm** [comment]
Should we close this?

**Comment by dougbu** [comment]
@pranavkm not sure why. `ViewData` discovery of `SelectListItem` enumerations is a confusing part of the product and the latest proposal doesn't cause compatibility breaks. Besides, this is in the `Backlog` milestone.

**Comment by mkArtakMSFT** [comment]
@dougbu, while the ask is valid, there was no any community involvement in this, which indicates that the value add here is too low. Closing this in an effort to clean up our backlog.
