### ISSUE TITLE
Change JSON formatters to be async

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#6002]
Latest JSON.Net package supports async reading and writing.
http://james.newtonking.com/archive/2017/03/21/json-net-10-0-release-1-async-performance-documentation-and-more 

cc @DamianEdwards @pranavkm @rynowak

**Comment by kichalla** [comment]
The async apis are not available on the JsonSerializer type (which we use [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonOutputFormatter.cs#L81) and [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonInputFormatter.cs#L150)) yet, so looks like we cannot move to async yet. Async support is available on JsonWriter and JsonReader but that doesn't help us here.

**Comment by kichalla** [comment]
@JamesNK Is support for exposing async api on JsonSerializer part of your future plans?

**Comment by JamesNK** [comment]
Maybe one day but not right now. It will be a lot of work

**Comment by kichalla** [comment]
Thanks @JamesNK .

Closing this issue for now as there is no action item here.

**Comment by rynowak** [comment]
There is definitely an action item here for us, it just might not be to make the formatters async.

**Comment by kichalla** [comment]
f1dd475eae83ca32950e82d5ac2facfe1eaad42e
