### ISSUE TITLE
Avoid redundant Assembly.Load call in DefaultAssemblyPartDiscoveryProvider

### ISSUE THREAD

**Issue by CoskunSunali** [aspnet/Mvc#6003]
I don't know if I am overlooking but if I am right, the assemblies are being loaded twice during the discovery of assembly parts.

Please see: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/DefaultAssemblyPartDiscoveryProvider.cs#L37-L38

**Comment by pranavkm** [comment]
Yup, would you like to send a PR to fix it?

**Comment by CoskunSunali** [comment]
Sure, will do that asap.

**Comment by CoskunSunali** [comment]
Created the PR. This was my first-ever contribution. Please kindly let me know if I was able to follow the contribution/PR guidelines correctly.

**Comment by Eilon** [comment]
BTW I doubt the assembly is actually loaded twice because I'd think everything is cached by the CLR. But still, good to clean this up!

**Comment by davidfowl** [comment]
Yep it is cached

**Comment by CoskunSunali** [comment]
If it is being cached (thankfully!) the title of the issue might be misleading, as well as the PR's title. Is it a good idea to change it?

**Comment by pranavkm** [comment]
It's still good to re-use the variable like you did. I tweaked the title a bit to reflect this. Thanks for the PR, your change was merged in https://github.com/aspnet/Mvc/commit/d2430f0f4ef869762834f794ec30662adf2c5232

**Comment by CoskunSunali** [comment]
@pranavkm Thank you for the update!
