### ISSUE TITLE
FormTagHelper does not apply on Razor Pages unless asp-antiforgery is explicitly set to true

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6006]
The `FormTagHelper` only targets `<form>` elements if various attributes are present, e.g. `asp-controller`. The default behavior of it rendering anti-forgery token fields thus only applies when these attributes are present. When used in Razor Pages however, the normal attributes are **not** used (as we're posting to another page typically), so the anti-forgery fields are not rendered unless the `asp-antiforgery` attribute is explicitly set, which is far less than ideal.

```html
<form method="post" class="form-horizontal" asp-antiforgery="true">
    <h4>Use a local account to log in.</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    ...
</form>
```

We want this to *just work* in Razor Pages, and it will be much more common there to post back to the current page, meaning no form action will need to be configured.

Shall we just make the `FormTagHelper` target all `<form>` elements by default now?

@rynowak @Eilon

**Comment by Eilon** [comment]
Let's change the `FormTagHelper` to target all `<form>` elements without restrictions on which attributes it has.

**Comment by dougbu** [comment]
The other option is to move antiforgery support into `RenderAtEndOfFormTagHelper`. That one already targets all `<form>` elements and already helps with antiforgery.

**Comment by rynowak** [comment]
@Eilon says: We think that moving this feature (`asp-antiforgery`) would be a bigger breaking change than just running `form` tag helper all of the time

**Comment by rynowak** [comment]
Load balancing

**Comment by NTaylorMullen** [comment]
5c8a161ace331d090326a1013520716db6b9a1cf

**Comment by NTaylorMullen** [comment]
@Eilon Are we announcing all MVC breaking changes together or do we want to do them as one-offs?

**Comment by Eilon** [comment]
Generally using one-offs, unless there are closely-related items.
