### ISSUE TITLE
Razor Page base classes should have HttpContext property

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6008]
The Razor Page base classes (for `Page` and `PageModel`) should have an `HttpContext HttpContext { get; }` property.

**Comment by pranavkm** [comment]
We have an `HttpContext Context {get }` property. Would this be an alias to it?

**Comment by DamianEdwards** [comment]
Not seeing it on `PageModel`. And we should call it `HttpContext` to match `Controller` I think.

**Comment by DamianEdwards** [comment]
Not seeing it on `Page` either...

**Comment by DamianEdwards** [comment]
Ah it's on `RazorPageBase`. So yeah, we should clean this up.

**Comment by rynowak** [comment]
Lots of the MVC stuff wrt naming is not consistent. I believe I made RazorPages more consistent with views than with controllers.

**Comment by DamianEdwards** [comment]
Seems slightly strange to have the `Context` property be `HttpContext` rather than the more specific `PageContext`, maybe?

**Comment by rynowak** [comment]
Perhaps it's not useful, but I'm just mentioning the reason for the choice, not trying say it's the best 👍

**Comment by Eilon** [comment]
We need to make sure we have these properties available on `Page` and `PageModel`:

```c#
public class Page / PageModel
{
    public HttpRequest Request { get; set; }
    public HttpResponse Response { get; set; }
    public HttpContext HttpContext { get; set; }
    public PageContext PageContext { get; set; }
    public ViewContext ViewContext { get; set; }
}
```

**Comment by hishamco** [comment]
@Eilon why we need to add `ViewContext` while `PageContext` already inherit from it?

Can we add `HttpContext` in `PageContext` instead? so adding on property may enough in this case

**Comment by Eilon** [comment]
@hishamco ah that's a good point about `ViewContext`. @rynowak thoughts on these two questions?

**Comment by hishamco** [comment]
Also the `Request' & 'Response` will be accessible via the newly suggested property 'HttpContext`

**Comment by Eilon** [comment]
@hishamco we still provide convenience properties. It's nice to have a lot less `.`'s in the code, plus it makes code easier to copy & paste between various pages/controllers/views/etc.

**Comment by pranavkm** [comment]
Poaching this

**Comment by pranavkm** [comment]
@Eilon do we actually want these properties to be settable? I'm not super sure there's a lot of utility in that.

**Comment by hishamco** [comment]
IMHO it should be read only, because almost of them will get their values from the `PageContext`

**Comment by hishamco** [comment]
Waiting for @Eilon thoughts ..

**Comment by DamianEdwards** [comment]
I'd think we take our lead from `ControllerBase`

**Comment by pranavkm** [comment]
The *closest* context properties are settable so in this case it'll be `PageContext`. `ViewContext` is currently settable in `Page` due to it being part of an interface contract, I'm leaving that as is.
The remainder are gettable only. `IUrlHelper` is settable in `ControllerBase`, I'll make that change in my PR: https://github.com/aspnet/Mvc/pull/6034.

**Comment by Eilon** [comment]
I think they're usually settable for testing purposes, no?

**Comment by Eilon** [comment]
Or, at least, the *main* properties (e.g. "root" properties) are usually settable. The ones that just "dot" into them for convenience probably don't need to be settable.

**Comment by pranavkm** [comment]
Yup. Here's what we have:

```C#
public class Page
{
    public PageContext PageContext { get; set; }
    public ViewContext ViewContext { get; set; }
    public ViewDataDictionary ViewData {get; }    
    public ModelStateDictionary ModelState {get; }
    public HttpRequest Request { get; }
    public HttpResponse Response { get; }
    public HttpContext HttpContext { get; }
    public ITempDataDictionary TempData { get; }

    // Injected properties (codegened on generated types)
    public IUrlHelper Url { get; set; }
    public IHtmlHelper<T> Html { get; set; }
}
```

```C#
public class PageModel
{
    public PageContext PageContext { get; set; }
    public ViewContext ViewContext { get;  }
    public HttpRequest Request { get; }
    public HttpResponse Response { get; }
    public HttpContext HttpContext { get; }

    public ViewDataDictionary ViewData {get; }    
    public ModelStateDictionary ModelState {get; }
    public IUrlHelper Url { get; set; }
    public ITempDataDictionary TempData { get; }
}
```
