### ISSUE TITLE
Working with generic viewmodel/class in mvc

### ISSUE THREAD

**Issue by rpundlik** [aspnet/Mvc#6010]
I am looking for generic solution for below implementation.

We have stored some of the database table names in one table and this table list we have populated in the dropdownlist and based on the selected table name we want to show the data with there columns in grid and the grid will have CRUD operation buttons.

For these tables we already have the models generated in the project.

But here we want to use generic view model/solution as columns(name,datatype etc) will get vary as per the table selected, so we cannot create a model which will have defined set of properties.

And to retrieve the selected table data we have written the stored procedure. But to retrieve the data returned from the stored procedure we need to provide the model name. Below is sample code

```
List<SomeModel> modelList = new List<SomeModel>();

modelList = dbcontext.Set<SomeModel>().FromSql("some sp name @tableName={0}", TableName).ToList();

return modelList;
```

So how can we create generic view model which will accept any table/model data and also, how can set that view model in dbcontext.Set<SomeModel> while executing the stored procedure ?

When I looked for the definition for dbContext.Set method
` public virtual DbSet<TEntity> Set<TEntity>() where TEntity : class;`,
it is accepting the class only and not instance/type

How can pass the class dynamically to dbContext.Set method ?

**Comment by Eilon** [comment]
This type of question seems better suited to https://stackoverflow.com/ because it is fairly broad.

If you have an Entity Framework Core specific question, please ask on https://github.com/aspnet/EntityFramework/issues.

BTW please be careful with the code you showed - it could be susceptible to a SQL injection attack, depending on where `TableName` comes from.
