### ISSUE TITLE
10 Failed razor tests on Travis

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#6017]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/214120356/log.txt

Linux passed but osx failed.

**Comment by Eilon** [comment]
These are some of the failures:

> Failed   Microsoft.AspNetCore.Mvc.FunctionalTests.ErrorPageTests.CompilationFailuresAreListedByErrorPageMiddleware
Failed   Microsoft.AspNetCore.Mvc.FunctionalTests.ViewEngineTests.RazorViewEngine_RendersPartialViews(actionName: "ViewWithoutLayout", expected: "ViewWithoutLayout-Content")
Failed   Microsoft.AspNetCore.Mvc.FunctionalTests.RazorPagesWithBasePathTest.IndexAtBasePath_IsRouteableAtRoot

Oddly, several tests failed with this:

> Error Message:
 System.IO.IOException : The request was aborted or the pipeline has finished

**Comment by Eilon** [comment]
The IOException stuff is also mentioned here: https://github.com/aspnet/Mvc/issues/6033

**Comment by Eilon** [comment]
@NTaylorMullen - can you take a look for Preview1? Anything we can do here?

**Comment by NTaylorMullen** [comment]
Sure, i'll take a look.

**Comment by NTaylorMullen** [comment]
Investigated this guy. Was not able to reproduce any issue on my Ubuntu Hyper-V VM. Ran the build suite on `dev` and on `rel/2.0.0-preview1`.

However, it still looks like there's failures on travis. Changing the travis configuration to [not run in a container](https://github.com/aspnet/Mvc/commit/66da4e7efce8557ceed77f781cf7232f4bcabbb6) and instead run in a VM seemed to resolve the issue. It's worth investigating if we have a test host issue in containers. I don't have the bandwidth to dive through that concern today (other preview1 issues popped up) but @glennc said he'd work with me to figure all those details out once I had time (looking like Monday).

**Comment by Eilon** [comment]
Ok, moved to preview2 then.

**Comment by rynowak** [comment]
Lot's more info on this here: https://github.com/aspnet/Mvc/issues/6033

**Comment by rynowak** [comment]
I'm not sure why this is still open. We've already investigated this issue and worked around it by using VMs instead of containers on travis.
