### ISSUE TITLE
Big Rock: View Compilation Tool for Pages

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6018]
We'll need to embed some more meta-data in order to make the pages work

**Comment by DamianEdwards** [comment]
@Eilon @rynowak @pranavkm this needs triaging/assigning.

**Comment by rynowak** [comment]
@pranavkm - I'm envisioning an IR pass as part of MVC's extensibility that will extract the relevant information and put it in the 'manifest'. 

Then this can be uniform for views and pages. Each one produces a generated class in one `.cs` file, and a manifest (assembly level attributes) in another `.cs` file.

This has the benefit that everything is now uniform, pages/views and compilation/precompilation.

**Comment by rynowak** [comment]
@pranavkm - please look at this after finishing up the URL generation stuff.

**Comment by DamianEdwards** [comment]
@pranavkm is this done now via 8ed55107e747594700bf652c536582ac771a5d33?

**Comment by pranavkm** [comment]
@DamianEdwards it is now that https://github.com/aspnet/MvcPrecompilation/commit/7f4aa60a456383169a374e3970cb580c88d9b08f is checked in.

**Comment by rynowak** [comment]
🍺 🌵 🏅 🔥
