### ISSUE TITLE
Update convention-based locations that partials and layouts are looked for from Razor Pages

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6019]
When a partial or layout is referred to from a Razor Page, e.g. `@await Html.PartialAsync("_LoginPartial")` and `@{ Layout = "_Layout"; }`, currently, the standard MVC-view locations are searched, which is clearly wrong.

The search order should be:
1. folder containing the current Razor Page
1. each parent folder of the above all the way to and including the configured Razor Pages root

I'm in two-minds as to whether we should also include a "Shared" folder in the paths to search while walking the folder hierarchy, like views do.

**Comment by rynowak** [comment]
> each parent folder of the above all the way to and including the configured Razor Pages root

Any thoughts about how to rationalize this with MVC views? This is a new semantic and means that the view engine has to know about the difference between pages and views.

**Comment by DamianEdwards** [comment]
I chose that because it's the same semantic as _PageImports & _PageStart (and their View counterparts) and seems logical (in my mind anyway).

Could we incorporate this into the existing logic and keep them unified?

**Comment by DamianEdwards** [comment]
We decided to drop the hierarchical bit and just look for files in same folder as current page, the configured pages root, and a `Shared` folder in each of those.

**Comment by rynowak** [comment]
I didn't think we decided anything other than to figure out what's possible 😆

**Comment by DamianEdwards** [comment]
Well OK then, let's start with that 😖

**Comment by rynowak** [comment]
The decision is to use the proposal at https://github.com/aspnet/Mvc/issues/6073#issue-219381287 - but with the second ordering of search paths in `Appendix A`. 

We're going to ignore Appendix B for now.

**Comment by rynowak** [comment]
a8eb5bee7023a2a5d49fcdaea0c25b3416a6921
