### ISSUE TITLE
Provide default select lists for `bool` and `bool?` expressions

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#602]
Similar to #438 should provide automatic (well, static) select lists for `bool` and `bool?` expressions.  This amounts to using `DefaultDisplayTemplates.TriStateValues()` (and something similar for non-`Nullable` Booleans) when the user does not pass a select list  to `@Html.DropDownList()` and `@Html.ListBox()`.

Current implementation gives up when no select list is passed or found in `ViewData`.

**Comment by dougbu** [comment]
Triage: this helper is fairly trivial but simple for customers to do themselves.  suggest we not fix this one for RC.

**Comment by danroth27** [comment]
@dougbu Could you please add a quick code sample to this bug that shows what a user would have to do to solve this problem?

**Comment by dougbu** [comment]
I wouldn't recommend using a `<select/>` for any regular `bool`.  just use a checkbox.  `<select/>` is possible but would look strange.

for `bool?`, assuming you want localization and have the resources in your resx file:
``` c#
var selectListForNullableBool = new List<SelectListItem>
{
    new SelectListItem
    {
        Text = Resources.Common_NotSet,
        Value = string.Empty,
    },
    new SelectListItem
    {
        Text = Resources.Common_True,
        Value = "true",
    },
    new SelectListItem
    {
        Text = Resources.Common_False,
        Value = "false",
    },
};
```
the first `SelectListItem` isn't :100:% required when using `Html.DropDownList[For]()` because you can call that method as follows:
``` c#
@Html.DropDownListFor(m => m.BoolQuest, selectList, optionLabel: Resources.Common_NotSet)
```
