### ISSUE TITLE
Using "..\" in a Layout path doesn't work

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6020]
Repro:
Create a Layout in the parent folder of the view and reference it like this:
`Layout = "..\\MyLayout.cshtml";`

NB: In Orchard so might affect the behavior.

**Comment by Eilon** [comment]
Does it work with forward slashes?

BTW what exactly "doesn't work"? Bad file path exception thrown? View not found? Where did it look?

**Comment by pranavkm** [comment]
I tried this out and seems to works fine. We did fix a bug in preview2 (https://github.com/aspnet/Mvc/issues/6448) where paths returned by ViewLocationExpanders that contain back slashes wouldn't have worked. Perhaps you were hitting this? Let me know if you're still seeing this in preview2 \ RTM  bits.

**Comment by jtkech** [comment]
Just tried with @sebastienros with a `<AspNetCoreVersion>2.0.0-*</AspNetCoreVersion>`.
We can confirm that `Layout = "../_Layout.cshtml"` works.

**Comment by pranavkm** [comment]
Thanks @jtkech
