### ISSUE TITLE
When ObjectResult.ContentTypes and Response.ContentType both specified, behavior is opposite of what comments imply

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Mvc#6026]
Maybe I'm misinterpreting the comments, but this looks wrong to me:

(From [ObjectResultExecutor.cs line 99](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/ObjectResultExecutor.cs#L99))
```csharp
// If the user sets the content type both on the ObjectResult (example: by Produces) and Response object,
// then the one set on ObjectResult takes precedence over the Response object
if (result.ContentTypes == null || result.ContentTypes.Count == 0)
{
    ...
}
```

The comment says that we prefer `Response.ContentType` over `objectResult.ContentTypes`. But the `if` test here doesn't implement that at all. It does the opposite: we *only* use `Response.ContentType` when `objectResult.ContentType` is null/empty.

Similar oddness appears in the corresponding test, [ExecuteAsync_ContentTypeProvidedFromResponseAndObjectResult_UsesResponseContentType](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.Core.Test/Infrastructure/ObjectResultExecutorTest.cs#L57). The test's name implies we prefer to use `Response.ContentType`, but the test logic doesn't test that at all. It doesn't set any value on `result.ContentTypes`. Instead, it tests that  `Response.ContentType` is preferred over the incoming `Accept` header (which is a desired behaviour, but unrelated to the test's name).

**Question: What is the real desired behaviour?** Would the correct fix be to change the comments to match the behaviour, or the behaviour to match the comments?

**Comment by SteveSandersonMS** [comment]
Ignore me; I did misread the comment. Behavior and comments are in fact consistent.

**Comment by rynowak** [comment]
👍 😆 👍
