### ISSUE TITLE
Why is https://github.com/aspnet/AspNetWebStack private?

### ISSUE THREAD

**Issue by jdaigle** [aspnet/Mvc#6027]
The old [CodePlex](https://aspnetwebstack.codeplex.com/) repository for the 5.x branch of ASP.NET MVC hasn't been touched in nearly two years. Granted in that time likely most resources have been focused on ASP.NET Core which is here on GitHub.

Many other CodePlex projects have already moved to GitHub (EF6, Katana, etc.). And there are [clues](https://github.com/aspnet/Mvc/issues/5258#issuecomment-246456699) that the [repository](https://github.com/aspnet/AspNetWebStack) exists that it is being [worked on](https://twitter.com/DamianEdwards/status/839506865830535169). There are even published [nightly builds](https://www.myget.org/feed/aspnetwebstacknightly/package/nuget/Microsoft.AspNet.Mvc).

But it remains unclear why the repository is *still* private. **In the spirit open source development, shouldn't the repository be public, and work done in the open?**

While Microsoft's priorities are clearly on ASP.NET Core and related projects, there are probably many customers that have heterogeneous applications (mix of older ASP.NET technology such as WebForms and services, in additional to newer MVC) that will be maintained for sometime and cannot simply be "upgraded" to ASP.NET Core. I, for one, would love to contribute fixes, enhancements, and new features to the 5.x ASP.NET MVC branch (for example; better async support).

**Comment by jdaigle** [comment]
The repository now appears to be public.

**Comment by Eilon** [comment]
Ah, yes, sorry, I meant to post an update here! It is indeed public!
