### ISSUE TITLE
Support of Microsoft.AspNetCore.Mvc on .NetStandard 1.4 or below

### ISSUE THREAD

**Issue by ankgupta067** [aspnet/Mvc#6028]
i want to create a .NetStandard 1.4 portable class library so that i can use it in .net framework 4.5.2 projects,
if i use  .NetStandard 1.6  portable class library i get an error while adding reference in .net framework 4.5.2 project as 

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll 
Additional information: Could not load file or assembly 'System.Runtime, Version=4.1.0.0

But i see that Microsoft.AspNetCore.Mvc package is not supported on .NetStandard 1.4 , is there a way to add this package in   .NetStandard 1.4 or to work around/ fix this problem?

**Comment by pranavkm** [comment]
> But i see that Microsoft.AspNetCore.Mvc package is not supported on .NetStandard 1.4

The 1.1.2 version of  `[Microsoft.AspNetCore.Mvc](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc)` targets `net451`. You should be able to use that. We're working on retargeting our class libraries to `netstandard2.0` which would change the minimum supported TFMs. Here's a table of what version of the desktop framework each of these `netstandard` versions support - https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by ankgupta067** [comment]
> (https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc) targets net451. You should be able to use that. 
i am not able to use that in netstandard1.4 portable class library dll, do i need to add a framework , right now my project.json looks like this.

{
  "supports": {},
  "dependencies": {
    "HtmlAgilityPack.NetCore": "1.5.0.1",
    "Newtonsoft.Json": "9.0.1"
  },
  "frameworks": {
    "netstandard1.4": {}
  }
}

**Comment by pranavkm** [comment]
You won't be able to reference Mvc in a `netstandard1.4` targeting project. You'll have to cross-compile it the same way Mvc does it.
