### ISSUE TITLE
Fix Ubuntu-only test flakiness

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#6033]
This problem may be in `TestHost`; assuming it's a test issue for now.
### Affected builds
Working backward through Travis builds:
#### https://travis-ci.org/aspnet/Mvc/jobs/215670472 (today)
15 failures due to `IOException` from TestHost. Details at the bottom of this issue.
#### https://travis-ci.org/aspnet/Mvc/jobs/215670049
5 failures, 4 due to `IOException` from TestHost. Mostly a subset of the above (and **Details** below) but adds `Microsoft.AspNetCore.Mvc.FunctionalTests.CompilationOptionsTests.CompilationOptions_AreUsedByViewsAndPartials` and fails in `Microsoft.AspNetCore.Mvc.FunctionalTests.RazorViewLocationSpecificationTest.PartialLayoutPaths_SpecifiedInPage_GetResolvedByViewEngine(actionName: "LayoutSpecifiedWithPartialPathInPageWithPartialPat"...)` instead of `PartialLayoutPaths_SpecifiedInPage_GetResolvedByViewEngine(actionName: "LayoutSpecifiedWithPartialPathInPageWithPartialPat"...)`.
#### https://travis-ci.org/aspnet/Mvc/jobs/215661887
8 failures due to `IOException` from TestHost. Breaks a slightly different set of tests, some overlapping those listed below.
#### https://travis-ci.org/aspnet/Mvc/jobs/215618686
26 failures, 25 due to `IOException` from TestHost.
#### https://travis-ci.org/aspnet/Mvc/jobs/214120356
10 failures, 9 due to `IOException` from TestHost.
#### https://travis-ci.org/aspnet/Mvc/jobs/213952543
11 failures, 10 due to `IOException` from TestHost.
#### https://travis-ci.org/aspnet/Mvc/jobs/213843173
15 failures due to `IOException` from TestHost.
#### https://travis-ci.org/aspnet/Mvc/jobs/213542244 (6 days ago)
24 failures, 23 due to `IOException` from TestHost.
### Details
Failed tests
- `Microsoft.AspNetCore.Mvc.FunctionalTests.ViewEngineTests.RazorViewEngine_RendersPartialViews(actionName: "ViewWithoutLayout", expected: "ViewWithoutLayout-Content")`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.RequestServicesTest.RequestServices(url: "http://localhost/RequestScopedService/FromViewComp"...)`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.RazorPagesWithBasePathTest.IndexAtBasePath_IsRouteableAtRoot`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.LinkGenerationTests.GeneratedLinks_AreNotPunyEncoded_WhenGeneratedOnViews`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.TagHelpersTest.CanRenderViewsWithTagHelpersAndUnboundDynamicAttributes_Encoded`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.RazorPagesTest.PageModel_Handler_ReturnTypeImplementsIActionResult`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.UrlResolutionTest.AppRelativeUrlsAreResolvedAndEncodedCorrectly`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.RazorPageExecutionInstrumentationTest.InstrumentedViews_RenderAsExpected`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.RazorViewLocationSpecificationTest.PartialLayoutPaths_SpecifiedInPage_GetResolvedByViewEngine(actionName: "LayoutSpecifiedWithPartialPathInPageWithPartialPat"...)`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.MvcSandboxTest.RazorPages_ReturnSuccess`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.DirectivesTest.ViewAndViewComponentsReplaceTModelTokenFromInheritedBasePages`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.BasicTests.CanRender_ViewsWithLayout(url: "Home/Index")`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlHelperOptionsTest.OverrideAppWideDefaultsInViewAndPartialView`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.RemoteAttributeValidationTest.RemoteAttribute_LeadsToExpectedValidationAttributes(areaName: "Area1", pathSegment: "/Area1")`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationTest.HtmlGenerationWebSite_GenerateEncodedResults(action: "Order", antiforgeryPath: "/HtmlGeneration_Order/Submit")`

Sample stack trace below. Many traces are consistent up to `ViewExecutor.cs(259,0)`. Occasionally that line is called from `/home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.RazorPages/Internal/PageActionInvoker.cs(383,0)`.
```
System.IO.IOException : The request was aborted or the pipeline has finished
Stack Trace:
     at Microsoft.AspNetCore.TestHost.ResponseStream.CheckNotComplete()
     at Microsoft.AspNetCore.TestHost.ResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
     at Microsoft.AspNetCore.TestHost.ResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
     at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.<FlushInternalAsync>d__26.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/ViewExecutor.cs(259,0): at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/ViewExecutor.cs(193,0): at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.ViewFeatures/PartialViewResult.cs(76,0): at Microsoft.AspNetCore.Mvc.PartialViewResult.<ExecuteResultAsync>d__26.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs(148,0): at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeResultAsync>d__15.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionInvoker.cs(860,0): at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__19.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionInvoker.cs(976,0): at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionInvoker.cs(680,0): at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionInvoker.cs(907,0): at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__21.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs(527,0): at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__18.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs(560,0): at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs(487,0): at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs(134,0): at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__13.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
  /home/travis/build/aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs(92,0): at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeAsync>d__11.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.AspNetCore.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
     at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
     at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
  /home/travis/build/aspnet/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/ViewEngineTests.cs(243,0): at Microsoft.AspNetCore.Mvc.FunctionalTests.ViewEngineTests.<RazorViewEngine_RendersPartialViews>d__19.MoveNext()
```
I removed all lines matching
```
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

One of the simpler stack traces, again removing the "I rethrew frames", was
```
 System.IO.IOException : The request was aborted or the pipeline has finished
Stack Trace:
   at Microsoft.AspNetCore.TestHost.ResponseStream.CheckNotComplete()
   at Microsoft.AspNetCore.TestHost.ResponseStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at RazorPageExecutionInstrumentationWebSite.Startup.<>c.<<Configure>b__1_0>d.MoveNext() in /home/travis/build/aspnet/Mvc/test/WebSites/RazorPageExecutionInstrumentationWebSite/Startup.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.TestConfiguration.CultureReplacerMiddleware.<Invoke>d__3.MoveNext() in /home/travis/build/aspnet/Mvc/test/WebSites/Microsoft.AspNetCore.Mvc.TestConfiguration/CultureReplacerMiddleware.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.FunctionalTests.RazorPageExecutionInstrumentationTest.<InstrumentedViews_RenderAsExpected>d__5.MoveNext() in /home/travis/build/aspnet/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/RazorPageExecutionInstrumentationTest.cs:line 33
```

**Comment by dougbu** [comment]
// @Tratcher

**Comment by Eilon** [comment]
@dougbu - can you take a first stab at investigating these?

**Comment by dougbu** [comment]
After talking with @Tratcher, I'll focus on `HttpClient` timeout settings and long-running tests.

Tried to reproduce the issue on various Linux machines (local VM, Azure F4, and Azure D15) without seeing it at all. Ran the functional tests at least 40 times per machine. But, it's possible the Travis VMs are substantially slower than anything I was using.

However, problems have not been corrected with newer CLI et cetera. Recent failed Travis builds include:
- https://travis-ci.org/aspnet/Mvc/jobs/220776056 (14 days ago)
- https://travis-ci.org/aspnet/Mvc/jobs/220629441
- https://travis-ci.org/aspnet/Mvc/jobs/219006235
- https://travis-ci.org/aspnet/Mvc/jobs/218719082
- https://travis-ci.org/aspnet/Mvc/jobs/218629141
- https://travis-ci.org/aspnet/Mvc/jobs/218342982 (21 days ago)

**Comment by dougbu** [comment]
3 tests failed in https://travis-ci.org/aspnet/Mvc/jobs/219006235, the least of the Travis runs listed in my previous comment. The tests were in 3 different classes and each is the slowest test in those classes when run in VS. The next-slowest test in each class is at least an order of magnitude faster. But, the failing tests take only 5 seconds in local testing -- not the 100 seconds required for `HttpClient` to time out.
- `Microsoft.AspNetCore.Mvc.FunctionalTests.AntiforgeryTests.SetCookieAndHeaderBeforeFlushAsync_GeneratesCookieTokenAndHeader`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.DirectivesTest.ViewInheritsBasePageFromViewStarts`
- `Microsoft.AspNetCore.Mvc.FunctionalTests.ViewEngineTests.RazorViewEngine_UpdatesViewsReferencedViaRelativePathsOnChange`

`HttpClient.Timeout` is not referenced anywhere in the MVC repo. I suspect we're dealing with a somewhat-random slowdown that's specific to Ubuntu on Travis, not Travis in general.

**Comment by dougbu** [comment]
f68bea235

**Comment by Eilon** [comment]
@dougbu - please add a note explaining why.

**Comment by dougbu** [comment]
Made f68bea235 after trying unsuccessfully to reproduce the problem locally. While Travis VMs start slower than their containers, we see failures often enough when using containers that they are not an option for this repo. (Others have reported container-specific Travis issues e.g. travis-ci/travis-ci#4691.)
