### ISSUE TITLE
Developer exception page 'Show raw exception details' only ever shows first set of details.

### ISSUE THREAD

**Issue by Stickman001** [aspnet/Mvc#6035]
When multiple exceptions are displayed (e.g. NullReferenceException, followed by an AggregateException) clicking on 'Show raw exception details' (the rawExceptionButton) only toggles the first block of raw exception code. Problem lies here:
ns("#rawExceptionButton").click(function (event) {
        var div = document.getElementById('rawException');
        div.style.display = 'inline-block';
        div.scrollIntoView(true);
        event.preventDefault();
        event.stopPropagation();

        return false;
    });

**Comment by pranavkm** [comment]
Moved to https://github.com/aspnet/Diagnostics/issues/356
