### ISSUE TITLE
Filter ITagHelperComponents

### ISSUE THREAD

**Issue by jbagga** [aspnet/Mvc#6043]
Change the constructors of `HeadTagHelper` and `BodyTagHelper` to accept new marker interfaces `IHeadTagHelperComponent` and `IBodyTagHelperComponent` respectively so:

- The `ITagHelperComponent` implementation will not need an `if` statement to check if it applies to the given HTML element.
- All `ITagHelperComponent`s will not be checked, only the ones registered in the DI (a filtered list); solving a potential performance problem 

cc @NTaylorMullen @Eilon @DamianEdwards @sebastienros

**Comment by Eilon** [comment]
@jbagga / @DamianEdwards / @NTaylorMullen / @rynowak - any thoughts on whether we should do this? It's certainly an interesting idea, and I think in general makes sense, but it also means that you couldn't write an `ITagHelperComponent` that applies to more than one element type.

**Comment by rynowak** [comment]
> The ITagHelperComponent implementation will not need an if statement to check if it applies to the given HTML element.

Do we really need new API surface to avoid an if?

> All ITagHelperComponents will not be checked, only the ones registered in the DI (a filtered list); solving a potential performance problem

I propose we revisit when/if we see enough usage of this feature to make performance a concern
