### ISSUE TITLE
Add the ability for an IActionConstraint to reject a request when nothing matches

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6046]
### The problem 

MVC/Routing now has backtracking for routes. Let's do an example:

```
GET /api/widgets 

[HttpPost("/api/widgets")]
public void UpdateWidget(Widget w) { ... }

[HttpGet("/api/{whatever}")]
public void GetWhatver() { ... }
```

The `/api/widgets` route will be *tried* first, which will match the URL path and then run the `IActionConstraint` associated with `UpdateWidgets`. Since the request is a `GET` this will not match and the route will be rejected. Then the `/api/{whatever}` route will be tried, and this will match the URL path. Since `HttpGet` matches `GET` the `GetWhatever` action will be selected.

Now let's tweak the example slightly:

```
GET /api/widgets 

[HttpPost("/api/widgets")]
public void UpdateWidget(Widget w) { ... }

[HttpPut("/api/{whatever}")]
public void DoWhatver() { ... }
```

Now when we get to `DoWhatver`, the action is not a match because `PUT != GET`. What if you wanted to respond with a 405 at this point (aspnet/Mvc#388)? Well, this is problematic for a few reasons:
1. You **don't know** if there's another route (`/api/{*bleh}`) running *after* you
2. You **don't know** the full set of candidates that were considered, so you can't generate the [Allow](https://tools.ietf.org/html/rfc7231#section-6.5.5) header

The problem with this is is that it makes it impossible for us to implement things like https://github.com/aspnet/Mvc/issues/388. As you can see from its low bug number, it's been sitting there a long time.

This came up again recently in a discussion about versioning, where a developer could not use `IActionConstraint` to implement a versioning policy; he wanted to reject the request with a custom response when it doesn't match.

### A Solution

The solution for this would mean abandoning fallback - in some limited cases. I think the set of users that rely on fallback for correctness of their API doesn't have much overlap with the set that care about versioning or HTTP spec compliance.

We'd need to add the following interface to abstractions:
```
public interface IActionConstraintEx : IActionConstraint // Name intentionally horrible
{
    RequestDelegate GetRejectionHandler(ActionConstraintContext context);
}
```

If all candidates in an `IActionConstraint` grouping were rejected, we would choose an `IActionConstraint` implementation and do a conditional cast to `IActionConstraintEx`, and repeat this until we found one.  Once we have one, run its `GetRejectionHandler`. `ActionConstraintContext` has all of the candidates, so if you want to look at their metadata, or implement a co-operative policy, you are free to do so.

If we get back a `RequestDelegate`, then we set `RouteContext.Handler` and consider action selection to be done. Routing will run the delegate, and then the pipeline is finished.

This would require some rejiggering of `IActionSelector` and friends, because they don't support anything like this in their contracts today.

## Tradeoffs

Note that if we implemented aspnet/Mvc#388 this way, you're opting out of route fall-back once you get into the action constraint stage of routing. Given the examples above, the request would be rejected with a 405 when it fails to match `POST != GET`. The allow header would only contain `POST`. because that's the only candidate we'd know about. 

I think that's an OK tradeoff, because no one implements an API this way because it's not sane.

**Comment by davidfowl** [comment]
I don't have a good feeling for all of the moving pieces here but since it's opt in it looks fine. You can have more than one action constraint on an action right? If so are they ordered?

**Comment by rynowak** [comment]
Yes

**Comment by davidfowl** [comment]
And if you wanted to implement a rejection policy for all actions on specific controllers, you can do this with application model right?

**Comment by rynowak** [comment]
You can attach action constraints with application model, yes.

**Comment by pranavkm** [comment]
@rynowak \ @JamesNK  does the dispatcher work address this?

**Comment by JamesNK** [comment]
Not currently. `IEndpointConstraint` is currently exactly the same as `IActionConstraint`, but there are plans in motion to integrate it more closely with pattern matching rather than as a secondary step.

What are your thoughts on this @rynowak?

**Comment by pranavkm** [comment]
Endpoint routing has support for this feature - https://github.com/aspnet/Mvc/pull/8185

**Comment by rynowak** [comment]
This is complete for Endpoint Routing in 2.2.0. See https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Matchers/HttpMethodMatcherPolicy.cs
