### ISSUE TITLE
$(TargetPath) or $(TargetDir) are empty on PostBuild event

### ISSUE THREAD

**Issue by marcusien** [aspnet/Mvc#6050]
Hi,

There's an issue with post build event on netstandard library.
when executing a post build event, the $(TargetDir) et $(TargetPath) macros are empty while they are not empty on the "post build event command line" wizard on visual studio.

You can reproduce it easily by 

- creating a netstandard project library
- put an `echo "Target path is : " $(TargetPath)"`
- then build the project
- take a look at output window

This works for $(SolutionDir) or other macros

**Comment by davidfowl** [comment]
Can you file that bug here github.com/dotnet/sdk

**Comment by marcusien** [comment]
Yep, it's done :)
