### ISSUE TITLE
Cannot pass complex object over RouteData into the Controller Function

### ISSUE THREAD

**Issue by SergeBerwert** [aspnet/Mvc#6051]
We experience a problem try to implement a custom route provider. We implemented a custom route provider by implementing IRoute. In this implementation, we check if the route matches. If it does we add some values to the RouteDataCollection. We give control back to the DefaultHandler. The handler evaluate the right method and calls it. But if we added instances of classes into the RouteDataCollection and expect thus in our Method parameters on our controller functions, they never show up there. We still get the instances in the RouteData insight the Controller Function, but we cannot receive it over method parameters. Everything works fine with value Types. With DateTime types we have a even stranger behavior. Then it works in some cases.

We are using the Newest version of asp mvc core with dot net framework 4.52. Visual Studio 2017 on Windows 10.

**Comment by Eilon** [comment]
@rynowak - Routing/MVC allows only strings in RouteData, correct?

Can you maybe use DataTokens on the RouteData for this, and then maybe have a value provider (or model binder) that can get data from Data Tokens to populate the controller parameters?

**Comment by rynowak** [comment]
RouteData allows any values to be placed in it, however value providers only operate based on strings.

I'd suggest starting with writing a custom `IModelBinder`

**Comment by SergeBerwert** [comment]
Hi
Thanks for responding. Not sure if i describet the problem well. I wrote some psydo code to ilustrate the problem.

```
//i have some nice data objects like this
public class NiceDataObjects
{
    public long ID { get; set; }

    public string Value1 { get; set; }

    public DataTime Timestamp { get; set; }
}


//i have a custom router implementation
public class MyRouter : IRouter
{
    private readonly IRouter _target;

    public MyRouter(IRouter target)
    {
        //storing reference to default route handeler
        _target = target;
    }

    public Task RouteAsync(RouteContext context)
    {
        if (context == null)
            throw new ArgumentNullException(nameof(context));
       
        //checking my one route table for a match
        var match = _myRoutes.Match(context);

        //leave if it don't match
        if (!match.Success)
            return TaskCache.CompletedTask;

        //add controller and action name to route data
        context.RouteData.Values["Controler"] = "MyController";
        context.RouteData.Values["Action"] = "Index";

        //add primitive type parameters
        context.RouteData.Values["Param1"] = 100;
        context.RouteData.Values["Param2"] = "Hello";

        //add an instance of my NiceDataObject
        context.RouteData.Values["Param3"] = new NiceDataObject { ID = 10, Value1 = "FooBar", Timestamp = DateTime.Now };

        //give controll back to default route handler
        return _target.RouteAsync(context);
    }
}

public class MyController : Controller
{
   //as expected method index on myController is called
   //param1 and param2 have the expected value like '100' and 'hello'
    public IActionResult Index(long param1, string param2, NiceDataObject param3)
    {
        //not param3. it allways has a new instance of NiceDataObject
        //but if i access it direct from RouteData i get the right instance
        var realParam3 = (NiceDataObject)RouteData.Values[name];
    }
}
```

**Comment by rynowak** [comment]
Yes, the description is clear. There is nothing in the model binding system that will do this by default for a complex-typed object. 

Our recommendation is to write a custom `IModelBinder`. It would look something like:
```
public class MyRouteBinder : IModelBinder
{
    public async Task BindModelAsync(ModelBindingContext bindingContext)
    {
        var key = bindingContext.ModelName;
        if (bindingContext.ActionContext.RouteData.TryGetValue(key, out var value))
        {
            bindingContext.Result = ModelBindingResult.Success(value);
        }
    }
}
```

You can use this with `[ModelBinder(typeof(MyRouteBinder))]` on your model type or parameter to wire it up.

/cc @ardalis @Rick-Anderson - this is another good example for the docs

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
