### ISSUE TITLE
Enhance Select List support to allow for option-level data-* attributes

### ISSUE THREAD

**Issue by makermanufacturer** [aspnet/Mvc#6061]
I'm looking at extending the SelectTagHelper, but I think what I want to do might be actually beneficial to a lot of developers.  Basically I want to add a specialized StringDictionary property to the SelectListItem class called AdditionalData or something to that effect.  Without any items defined this would behave exactly like the current SelectListItem does, but an entry in this dictionary would result in a data-{key} attribute being added with a value of {value} directly in the <option> tag.

The AdditionalData property could be a standard string dictionary, but then when it came time to render the items as attributes, additional code to sanitize the text in the key and value would be necessary to avoid issues when rendering the resulting HTML.  Another option is to implement those controls upon insert into the dictionary and assume the resulting text is safe upon HTML generation.

As I see it, this is an augmentation to the existing SelectListItem class which shouldn't be a breaking change as the property would be optional.  In addition, this would require a change to the functions responsible for generating Options in the implementations of the IHtmlGenerator interface.  Other than that, the implications of this change should be contained.  I would love to take this on, but I'm not sure how to proceed.

I realize some context as to the utility of this may be necessary.  The current problem I am attempting to solve is that I have a service that returns a List<SelectListItem> for my domain address objects. It returns a list of the record identifier and the entire address as a string.  For some situations I need specific elements of that address and attempting to parse the returned text isn't always appropriate.  I want to have each element of the address available as a data-* attribute to access that specific value from the selected option.

As an example: a user selects an address from the dropdown to associate it with a payment method.  The service to tokenize the payment method expects the elements of the address individually.  With this implementation it would be trivial to gather those elements from the selected option.  Without it I can either use the existing implementation and then gather the information using the record identifier or create a new Editor for the address type that does what I need, but it seems having a framework solution for this would reduce this effort for what seems like a pretty common task.

**Comment by mkArtakMSFT** [comment]
Hi @makermanufacturer . Thanks for contacting us. It seems this issue never got any traction from the community, hence we feel like it's not worth the effort.
