### ISSUE TITLE
EventID's should be unique per-category

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#6062]
According to @BrennanConroy eventId's of `LoggerMessage.Define` should be unique per category (usually the `T` in `ILogger<T>`). There's some spots where that's not true and we should fix it. Example of non-uniqueness [here](https://github.com/aspnet/Mvc/blob/d44c9aee1e0fe331158a7c9bb2c88b38d74c72e7/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreLoggerExtensions.cs#L76).

**Comment by rynowak** [comment]
Our eventIds are unique per-logger. Where is this new requirement coming from?

**Comment by Eilon** [comment]
Yeah this is news to me. The uniqueness is (category + eventid), not just (eventid).

**Comment by ryanbrandenburg** [comment]
@BrennanConroy did I misunderstand the requirements here? And @Eilon what "category" are you talking about?

**Comment by ryanbrandenburg** [comment]
In that case isn't [this](https://github.com/aspnet/Mvc/blob/d44c9aee1e0fe331158a7c9bb2c88b38d74c72e7/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreLoggerExtensions.cs#L74) and [this](https://github.com/aspnet/Mvc/blob/d44c9aee1e0fe331158a7c9bb2c88b38d74c72e7/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreLoggerExtensions.cs#L119) as called [here](https://github.com/aspnet/Mvc/blob/13b32adeae0bd13f210a166c7d1a0dcb2a917611/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs#L86) and [here](https://github.com/aspnet/Mvc/blob/13b32adeae0bd13f210a166c7d1a0dcb2a917611/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs#L268) respectively an example of us not following (category + eventid) uniqueness since they'll use the same _logger?

**Comment by rynowak** [comment]
If we have a bug we should fix it. 

But this statement has never been a practice we have followed:

> EventId's of LoggerMessage.Define should be unique within thier package. This is certainly not the case right now, so we should go through and make them all so.

**Comment by Eilon** [comment]
@ryanbrandenburg that does appear to be a specific bug in that specific case.

**Comment by ryanbrandenburg** [comment]
Updated to reflect category vs package.

**Comment by Eilon** [comment]
Ok let's fix this one offending one. I can't think of a good way to easily detect this because there's no way to tell from the various LoggerExtension methods where the log will be used, and thus what the category is.
