### ISSUE TITLE
Add ability to change Razor Pages page handler method naming convention via ApplicationModel

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6065]
People should be able to adjust the logic we use to select `OnGet`, `OnPost`, etc. via `ApplicationModel` rather than replacing the Razor Pages components. This needs to apply equally to methods on pages or page models, so should be abstracted from both. It will likely include context such as the path of the current page and the `HttpContext`.

Some example scenarios that should be possible:
- Look for a method called `OnLoad` that is run on every request type (GET, POST) in addition to the verb-specific methods
  - This might mean we need the ability to return a list of methods to call, in order
- Remove the need for the `On` prefix
- Remove the need for the verb name in the method when using the `formaction` route value, e.g. `OnCreateCustomer` instead of `OnPostCreateCustomer`

**Comment by DamianEdwards** [comment]
@rynowak @pranavkm

**Comment by rynowak** [comment]
Does this mean that we just got the conventions wrong?

**Comment by DamianEdwards** [comment]
Possibly, but that's kinda hard to tell for all cases 😄 

It seems odd to me that much of the MVC stack's conventions are configurable via Application Model, but this wouldn't be, but I'm happy to tweak the current convention and only make it configurable at a later date if enough people ask, as I acknowledge that one of the very nice things about baked-in, opinionated conventions is that it ends up with all examples looking the same and consistency is nice for learning.

**Comment by rynowak** [comment]
I'm more concerned about things like the following comment than about flexibility of naming:

> This might mean we need the ability to return a list of methods to call, in order

This is pretty fundamental. This would drastically change how filters would work for example.

-----------

I also don't want to use application model as a chance to punt on getting the right conventions about naming - `OnGet`/`OnPost` vs `OnLoad`/`OnSubmit`

**Comment by rynowak** [comment]
We haven't had any requests on for this, and we could do it at some future time, so I'm moving it to the backlog. @DamianEdwards get at me if you disagree.

**Comment by rynowak** [comment]
@DamianEdwards given that page model lets you change the name/verbs/bindings of methods, and page filters let you override selection, do you think that's suitable enough extensibility?

I don't think we need any additional work, and I suggest closing this out.

**Comment by pranavkm** [comment]
@DamianEdwards I created a sample for this when responding to a different work item - https://github.com/pranavkm/customizable-page-handlers. We could move it to Entropy if we deem it necessary.

**Comment by rynowak** [comment]
Please move sample to entropy and log a doc issue to include this info

**Comment by pranavkm** [comment]
* Sample is located here - https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRazorPageHandlers
* Doc items to expand on Razor Pages feature is here - https://github.com/aspnet/Docs/issues/4281

**Comment by danroth27** [comment]
Remove feature related labels since all we did here is add a sample.
