### ISSUE TITLE
Is there any way to extend existing taghelpers?

### ISSUE THREAD

**Issue by martonx** [aspnet/Mvc#6068]
Hi,

Is there any way to extend existing taghelpers? For example I'm using bootstrap or some custom css frameworks, and I don't want to recreate input tag helper, just I would like to add some extension which can create some default classes into input types.

`<input type="text" asp-for="myModel" class="my-formatted-text-input"></input>`
this should be great:
`<myinput type="text" asp-for="myModel"></myinput>` - and this should generate the result of the code above.

Or I would like to use HTML5 validation attributes instead of Jquery unobtrusive validations. Could I override somehow the generated validation attributes?

**Comment by NTaylorMullen** [comment]
@martonx For what you're trying to accomplish you can write a separate `TagHelper` that targets input elements and both MVC and yours will run.

**Comment by martonx** [comment]
Fine! Cold you provide some samples for it?

**Comment by NTaylorMullen** [comment]
I'd recommend checking out our various TagHelper authoring articles on how to get started [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring).
