### ISSUE TITLE
RedirectToPage doesn't trim /Index from URL

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6080]
`RedirectToPage` should trim the trailing `/Index` from the URL given that it's default anyway.

That is, doing this `return RedirectToPage("/Index");` should effectively be the same as `return Redirect("~/");`.

Obviously needs to work for sub-folders and when route values are passed as well.

**Comment by DamianEdwards** [comment]
@rynowak @pranavkm @Eilon

**Comment by rynowak** [comment]
Should we even match `/Index` - right now we create a route entry for `/` and for `/Index`? Is there value to the latter?

If we want to keep both, then `/` needs to have a better value of order so that its considered first.

**Comment by Eilon** [comment]
In the amazing new world of Razor Pages perhaps it's fine to canonicalize URLs to their simplest form?
