### ISSUE TITLE
Can load external .dll for Controllers and Views but DefaultRoslynCompilationService.Compile fails with @model / references

### ISSUE THREAD

**Issue by ThatDeveloper** [aspnet/Mvc#6084]
I am writing a plugin system for dotNetCore. I managed it, that my plugins get loaded and mvc finds the controllers and views.

OS: Windows 10 Enterprise 64-bit (but the application should run on Windows and Linux)
IDE: Visual Studio 2017
Target Framework: .NETCoreApp 1.1
Packages:
```
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.0"
```

But here is the problem:
If a view contains something like @ model it will just throw an exception.
[Exception => https://pastebin.com/ym3eCkLa](https://pastebin.com/ym3eCkLa)

I am using AddApplicationPart to add the controller and views.
I am googling now for over 3 days but I could not find a solution.
Yes, I saw many answers where they did say the code below will fix it, but it doesn't work.
```
services.Configure<RazorViewEngineOptions>(options =>
{
    var previous = options.CompilationCallback;
    options.CompilationCallback = (context) =>
    {
         previous?.Invoke(context);
         context.Compilation = context.Compilation.AddReferences(assemblies.Select(c => MetadataReference.CreateFromFile(c.Location)));
};
```

or

```
assemblies.ForEach(c => options.AdditionalCompilationReferences.Add(MetadataReference.CreateFromFile(c.Location)));
```

(where assemblies is a list of loaded assemblies (LoadFromAssemblyPath)).

I already tried so many ideas and suggestions of other stackoverflow / github issues but nothing did work. I tried it with a AppDomain polyfill but this didn't work too. (PreserveCompilationContext too)

**Comment by cldbrr** [comment]
Hi I've got the same issue ... no clues how to resolve it. Did anyone figure it out?

**Comment by rynowak** [comment]
```
> System.IO.FileNotFoundException: Could not load file or assembly 'UserPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'UserPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
         at System.Reflection.RuntimeAssembly.GetExportedTypes()
         at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
```

Your exception here is occurring when the assembly is loaded (after compilation). If the `UserPlugin` assembly is not in the application's references then it might not be loaded in the default load context.

You might need to attach to `AssemblyLoadContext.Default.AssemblyResolve` https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L450

**Comment by cldbrr** [comment]
I've tried it as well still doesn't work.

I've discovered that there is no issues if I will use default Bin folder for keeping plugins assemblies. 
If I will use other folder i.e. \Plugins for keeping assemblies then I've got error.

**Comment by rynowak** [comment]
>I've discovered that there is no issues if I will use default Bin folder for keeping plugins assemblies.
If I will use other folder i.e. \Plugins for keeping assemblies then I've got error.

Are you on desktop .NET Framework? The application `bin` folder is consider the Load Context by desktop .NET Framework - which is why that would work. If you want to use a different structure you will have to attach to the resolve events `AssemblyLoadContext.AssemblyResolve` or `AppDomainAssemblyResolve` to tell .Net where to find the assembly.

If you are building a modular/plugin sort of thing you will have to solve the issue of getting the assemblies loaded/resolved.

**Comment by rynowak** [comment]
Closing due to lack of response.
