### ISSUE TITLE
Add a validation provider that validates that non-nullable types are not null.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#609]
In Mvc 5.x, this was done as part of DataAnnotationsModelValidatorProvider. In WebAPI,  this was partly achieved by MutableObjectModelBinder. 

It would be a cleaner approach to do this as a separate validator provider. This would make it easier to toggle this behavior off (remove the item from the DI container) and move validation from binding.

**Comment by rynowak** [comment]
Addressed by the use of `PropertyHelper.GetVisibleProperties(key.ModelType)` acb657d9

**Comment by rynowak** [comment]
We decided to go back to the MVC5 semantics on this one. Not sure this bug is relevant.
