### ISSUE TITLE
Revisit conventions for naming of handler methods

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6090]
We want to make sure it's possible to make the `On` and `Async` in a handler method options.

We also want to consider if you can drop `Post` from a handler method name and just have the *handler method* portion. So `Delete()` would match the `delete` form action. In this model all public methods are considered handler methods (same exceptions for dispose).

I also want to consider, could get get away from using verbs entirely... this would mean choosing a different term to represent `GET` and `non-GET`.

**Comment by DamianEdwards** [comment]
I'm also wondering whether we should rename the "formaction" concept to be more in line with pages, e.g. "handler". I'm using it for things that expressly **aren't** form-actions, they're HTTP GET callbacks from other sites for example, and it seems to gel better with the whole "page handler" thing we have going.

Thoughts?

**Comment by rynowak** [comment]
I chose the term form action based on the HTML attribute. We could certainly revisit this

**Comment by DamianEdwards** [comment]
Yeah I know, and it made sense, but I'm finding I'm using it for more than that, and as we discussed, we could end up "hiding" that attribute via a Tag Helper in some cases anyway.

**Comment by rynowak** [comment]
297196baa0d4a28a4f71d0b4bba2d5b942af6190
