### ISSUE TITLE
Test not cleaned up and keeps listening on local port [::1]:5000

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Mvc#6092]
This causes other tests that tries to bind to that port to fail e.g. http://aspnetci/viewLog.html?buildId=197787&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest. The process that's not cleaned up is the following

```
Name	PID	Status	User name	CPU	Memory (private working set)	Command line	Description
MvcNET_ui524pqj.vvi.exe	452	Running	asplab	00 	36,620 K	"C:\BuildAgent\work\7e246aed044cebc\test\bin\Release\net46\win7-x86\FolderPublish\MvcNET_ui524pqj.vvi\bin\Debug\PublishOutput\MvcNET_ui524pqj.vvi.exe"	MvcNET_ui524pqj.vvi
```

We have to occasionally log into the agent and stop the process to fix the build.

cc @mikeharder @pranavkm @rynowak

**Comment by mikeharder** [comment]
If possible, the MVC test should use a dynamically-assigned free port rather than hardcoding port 5000.  Example:

https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs#L502-L514

**Comment by pranavkm** [comment]
Mvc doesn't have any server based tests - all our functional tests are in memory ones. This tests looks like its from WebSdk - https://github.com/aspnet/websdk/blob/dev/test/Publish/Microsoft.NET.Sdk.Publish.Tasks.Tests/EndToEnd/FolderPublish.cs

**Comment by JunTaoLuo** [comment]
This issue was moved to aspnet/websdk#177
