### ISSUE TITLE
No way to hook into the the ExecuteAsync() process.

### ISSUE THREAD

**Issue by rjamesnw** [aspnet/Mvc#6094]
There seems to be no way to intercept when `ExecuteAsync()` gets called. I think this is a big limitation.  I need to be able to execute code before and after by custom ViewPage (which inherits from RazorPage) generates the output. Any ideas?

**Comment by pranavkm** [comment]
If you're trying to do work before and after the `ViewResult` executes, you could use a result filter. There isn't a well-defined extensibility point that does work before and after the rendering individual pages, but it would help if you describe what it is that you're trying to do.

**Comment by rjamesnw** [comment]
No, that won't work for me.  I need to know the nesting level of the calls. In MVC 4 there was `System.Web.WebPages.TemplateStack` [which could be used](http://stackoverflow.com/questions/13398485/get-nesting-level-of-view-in-asp-net-mvc-4), but now there is nothing.

**Comment by rjamesnw** [comment]
Well, it seems the `RazorView` type is what calls it:

    // (RazorView.cs, line 158)
    private Task RenderPageCoreAsync(IRazorPage page, ViewContext context)
    {
        page.ViewContext = context;
        _pageActivator.Activate(page, context);
        return page.ExecuteAsync(); <---
    }
Unfortunately, the type is not injected (figures):
   
    // (RazorViewEngine.cs, line 476)
    var view = new RazorView(this, _pageActivator, viewStarts, page, _htmlEncoder);
(NEW IS GLUE, right? lol :/ )

However, seems the engine IS:

    services.TryAddSingleton<IRazorViewEngine, RazorViewEngine>();

So I'll have to experiment with creating my own engine wrapper and intercept on calls to `GetView()` and `FindView()`.

**Comment by rjamesnw** [comment]
Any the real answer is ... `ViewResultExecutor` [cheers!] ;) After more spelunking through the code, I found that an executor was used to call the first `ExecuteAsync()` in a chain of `ExecuteAsync` calls. ;)
