### ISSUE TITLE
Question about a very custom authorization situation

### ISSUE THREAD

**Issue by rykr** [aspnet/Mvc#6097]
I'm working on a site where users can create some "leagues"  and then assign admin rights to users over just certain leagues.

In some of my views I have buttons and controls for administering items related to those leagues  and I only want to show those controls if those users are signed in.  So we can't use site-wide roles.  Whether a user is an admin over a certain league is contained in one of my defined tables.  My ApplicationUser class has a List<LeagueMember> relation that contains this info.

Is there anyway to have my site load up the current user and their assigned league memberships on each page load or will I have to do that manually whenever I want to protect a control?

Thanks!

**Comment by rynowak** [comment]
If you're using cookies for auth, the user's identity will be established on every request by the presence of a cookie (after they log in). 

If you want to store some specific data with each user you'd probably want to do that thought ASP.NET identity. https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity
