### ISSUE TITLE
ModelExpression in taghelper does not get hit in CachedExpressionCompiler

### ISSUE THREAD

**Issue by jbearfoot** [aspnet/Mvc#6098]
I have implemented a taghelper that has a property of type ModelExpression. Now if I use my taghelper like:
&lt;img epi-property="@Model.PageImage" /&gt;
 then I notice that in the compiled razor view I get the expression as: 
(__model => this.Model.PageImage))
while if I instead use my taghelper as 
&lt;img epi-property="PageImage" /&gt;
then the view gets an expression like
(__model => __model.PageImage)
From what I can see in CachedExpressionCompiler through decompiler (and also when running profiling tests) the first expression fails to be cached and will be compiled each time while the later one can be cached.

I think the first one (with @) is clearer, especially if you do not have intellisense (e.g. when viewing the file in source code repository like Stash web browser).

**Comment by NTaylorMullen** [comment]
@jbearfoot the reason why the first one is not cached is because it's a capturing lambda. Due to that behavior we're unable to cache it. Feel free to re-open if you think that I've missed something.
