### ISSUE TITLE
How to setup Custom Role based Authorization?

### ISSUE THREAD

**Issue by kharlamov** [aspnet/Mvc#6100]
I am using a custom user & role storage that I have setup with my postgres database, how would one go about allowing those roles to be used by ClaimsPrincipal:

The problem I am running into right now is nothing is overriding the `ClaimsPrincipal.IsInRole` as by default the implementation is:

```
public class ClaimsPrincipal : IPrincipal
{
    public virtual bool IsInRole(string role)
    {
      return false;
    }
}
```

Using a controller action like so I am always being restricted due to the default implementation returning false:
```
    [HttpPost()]
    [Authorize(Roles = "DoItRole")]
    public JsonResult DoIt([FromBody] InputModel input) { ... }
```

**Comment by blowdart** [comment]
This question is too wide. We don't know how you authenticate, or how you then persist. Generally when you create the principle you hydrate the roles there. We don't support custom principles any more. We expect everything to be a claims principal.

**Comment by kharlamov** [comment]
I am using Google Authentication, if that helps?
```
            var info = await _signInManager.GetExternalLoginInfoAsync();
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false);
```

**Comment by blowdart** [comment]
With or without asp.net identity?

**Comment by kharlamov** [comment]
With asp.net identity.

**Comment by blowdart** [comment]
Is google auth your only auth? And you implemented a role store, or went all out an implemented a manager?

**Comment by kharlamov** [comment]
For the time being it is my only auth, and I have only changed around the role stores, nothing else.

**Comment by blowdart** [comment]
@HaoK which event would kick in here?

**Comment by kharlamov** [comment]
After digging through the Microsoft.AspNetCore.Authorization code it feels like the missing bit is that `ClaimsPrincipal` should just use `IUserRoleStore<TUser>.IsInRoleAsync` or `UserManager<TUser>.IsInRoleAsync`.

The only workaround I can think of is implementing your own through policy authorization:

Handler, Requirement:
```
    public class CustomAuthorizationHandler : IAuthorizationRequirement, IAuthorizationHandler
    {
        public IEnumerable<string> AllowedRoles { get; } 

        public MartenAuthorizationHandler(params string[] allowedRoles)
        {
            AllowedRoles = allowedRoles;
        }

        public async Task HandleAsync(AuthorizationHandlerContext context)
        {
                ...
                context.Succeed(this);
        }
    }
```

Policy, in startup:
```
    services.AddAuthorization(options => {
        options.AddPolicy("Role", x => x.Requirements.Add(new CustomAuthorizationHandler("MyRole")));
    });
```

Attribute on Action, with Policy:
```
    [Authorize(Policy = "Role")]
```

However I can't inject `UserManager<>` to get at `IsInRoleAsync` into `CustomAuthorizationHandler` because of the way the DI is setup and AddPolicy doesn't give any hooks to do so. Thoughts?

**Comment by kharlamov** [comment]
OMG, I figured it out this could not be as confusing as it is yet so simple at the same time.

**The IUserRoleStore and  IUserStore have to be the same class, then the GetRolesAsync needs to be implmented, and everything works through claims.** 

Here is the confusing bit:

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserManager.cs#L258

Here is the factory that makes it work:

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs#L96
