### ISSUE TITLE
Bundling seems to happen after files are copied

### ISSUE THREAD

**Issue by xavierpena** [aspnet/Mvc#6101]
I am trying to deploy a ASP.NET Core web application.

At the beginning of the publish process, I just have 1 file under `\wwwroot\css`: `main.css`.

After the publish process:

* In the `\publish` folder, there is only `main.css`
* In the `\wwwroot\css` folder, there is `main.css` + `main.min.css` (thus minification works, which is also what the command line message says*)

My .csproj seems correct:

	<Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
		<Exec Command="bower install --allow-root" />
		<Exec Command="dotnet bundle" />
	</Target>

	<ItemGroup>  
		<None Update="wwwroot\**\*">
		  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</None>
	</ItemGroup>

So the only thing that seems possible in this scenario is the bundling is happening AFTER the files are copied.

(*) Command line message:

    Processing wwwroot/css/site.min.css
    Minified

**Comment by Eilon** [comment]
This issue was moved to aspnet/websdk#183
