### ISSUE TITLE
Support ModeStatelDictionary.AddModelError overload that does not require ModelMetadata arg

### ISSUE THREAD

**Issue by lencharest** [aspnet/Mvc#6102]
The `ModeStatelDictionary.AddModelError` overload that takes 3 arguments uses the 3rd arg (`ModelMetadata`) only in very limited circumstances. Nevertheless, the 3rd arg may not be null. In my case, I'm forced to instantiate a `ModelMetadata` that I know is useless.

Please support a 2 argument variation that omits the `ModelMetadata` for the common case where the caller knows that the exception (2nd arg) is not one of the types that get special treatment:

```
public void AddModelError(string key, Exception exception) { ... }
```

**Comment by Eilon** [comment]
Hi @lencharest , I'm guessing the reason for this is that generally using exceptions for model state errors doesn't do much aside from flagging the field as invalid -- the exception text isn't even used. Only a few specific exceptions that are "known to be safe" (such as `FormatException`) are used to produce actual error messages - and even for those, the Message of the exception isn't used.

As such, to add a model state error with a specific error message, it's probably best to call `AddModelError(string key, string errorMessage)`.

Having said all that, I think it's certainly possible to add the overload you're asking about, but I want to make sure that it's actually what you want first 😄

**Comment by lencharest** [comment]
Actually, I'm using the 3 arg version of `AddModelError` because message strings aren't rich enough for my needs. I'm treating the exception object as a property bag (in the sense that the exceptions exist to hold contextual information about a validation error and are never thrown). What would be ideal is something like

`public void AddModelError(string key, object info)`

with a corresponding `object Info` property added to `ModelError`.

Background: I've written an action filter that performs validation of primitive action parameters that are decorated with custom attributes. For example:

`public void Get([ValidIpAddress, FromQuery] string ipAddress) { ... }`

where `ValidIpAddressAttribute` is a custom validation attribute.

My action filter calls `ValidIpAddressAttribute.IsValid(ipAddress)`. If the action parameter is invalid, it then stores an error on the model state by calling `modelState.AddModelError(parameterName, contextInfo, metadata)`, where `contextInfo` is an instance of a custom exception.

The upshot of all this is that I know that the `metadata` argument passed to `AddModelError` will never be used because I am never passing an instance of `FormatException` or `OverflowException` as the 2nd argument. Therefore, I'd like to avoid having to create the `metadata` instance at all.

**Comment by dougbu** [comment]
@lencharest one workaround is to create one `ModelMetadata` instance and store that instance in a `static` field somewhere.

How are you using the context information later? MVC keeps the exceptions around but doesn't use them anywhere (after handling the `FormatException` and `OverflowException` cases. And, custom validations that add error strings to the `ModelState` are the norm.

**Comment by lencharest** [comment]
@dougbu, the motivation for this issue is to avoid creating an object I know I don't need.

Error strings aren't rich enough for my needs. The context info is used during serialization of a validation error response. I have a formatter that iterates over the `ModelStateDictionary` and builds an error response from it. My error schema requires more information than I can get from a single string.

**Comment by dougbu** [comment]
@lencharest :ok: my previous [workaround](https://github.com/aspnet/Mvc/issues/6102#issuecomment-297770488) wasn't helpful. Why use `ModelStateDictionary` versus, say, a separate dictionary mapping the same keys (or whatever keys needed) to the additional information?

**Comment by lencharest** [comment]
@dougbu, I want to leverage the same model validation framework that is build in to ASP.NET.

**Comment by dougbu** [comment]
@lencharest as I understand it, you're using custom validators for some errors and they add additional information to the `ModelStateDictionary` which is later handled in a custom formatter. My suggestion was for those validators to place the extra information somewhere else and make it (and `ModelStateDictionary`) available to your formatter. Please let me know if I'm missing something.

**Comment by lencharest** [comment]
@dougbu, my custom validators are invoked inside the `OnActionExecuting` method of a custom `ActionFilterAttribute`. To use another object as a container for rich validation info, I'd need to inject that object into either the attribute or the `ActionExecutingContext` passed to the method. I don't think the former is possible (using the DI framework provided by ASP.NET). The latter could probably be achieved by stashing the container in `ActionExecutingContext.HttpContext.Items`, but implementing that cleanly seems like just as much work as what I've already done.

**Comment by Eilon** [comment]
Ok we should just add the requested overload that takes in the exception so that it's available later in the pipeline.

**Comment by olivertech** [comment]
Hi, I am searching for this override version without ModelMetadata, but I can´t find it. Is it finally added ?

**Comment by dougbu** [comment]
The fix was included in the ASP.NET 2.1.0 Preview 2 release e.g. https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Abstractions/2.1.0-preview2-final. Are you still on one of the 2.0.x releases?

**Comment by abigailbeets-wk** [comment]
Hi, I'm looking for this as well. I am using Microsoft.AspNetCore.Mvc 2.1.3 and I'm not getting this overload. Can you please confirm it is in this release, and if not, what release or package I should be using to access it?

**Comment by poke** [comment]
@abigailbeets-wk The method is prefixed with `Try`, that’s probably why you are not seeing it. There are two methods:
- [`TryAddModelError(String, String)`](https://docs.microsoft.com/de-de/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.modelstatedictionary.tryaddmodelerror?view=aspnetcore-2.1#Microsoft_AspNetCore_Mvc_ModelBinding_ModelStateDictionary_TryAddModelError_System_String_System_String_)
- [`TryAddModelException(String, Exception)`](https://docs.microsoft.com/de-de/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.modelstatedictionary.tryaddmodelexception?view=aspnetcore-2.1)

**Comment by abigailbeets-wk** [comment]
@poke Thank you! :)
