### ISSUE TITLE
Mismatch between process architecture being built and dotnet-razor.tooling.exe, "AMD64"

### ISSUE THREAD

**Issue by vankampenp** [aspnet/Mvc#6107]
Hi, I am getting this message when compiling on Intel. It warns that this mismatch may cause runtime errors. It seems part of the Razor Tools is compiled for AMD?

Using Razor Tools 1.1.0-preview4-final.

**Comment by Eilon** [comment]
Hi @vankampenp , it looks like you're using Visual Studio 2015, which has only "preview" tooling for ASP.NET Core. The supported tooling for ASP.NET Core is on Visual Studio 2017, which you can find here: https://www.visualstudio.com/ (including free editions).

The new tooling in VS2017 doesn't use "dotnet razor tooling" anymore, so this issue shouldn't apply anymore.

**Comment by vankampenp** [comment]
Hi Eilon,
I am getting this with Visual Studio 2017, after upgrading the project. I did not know the razor tooling could be removed. After removing the tooling the warning disappeared.

Thanks!

**Comment by Eilon** [comment]
Ah, yes, you can just remove that package! Glad you got it working!
