### ISSUE TITLE
Question: call ModelBinding manually?

### ISSUE THREAD

**Issue by nojaf** [aspnet/Mvc#6109]
Is there a way to manually call the modelbinding in custom middleware for example?

Something like:
```csharp
      app.Use(async (context, next) =>
        {
            var modelBindingService = context.Resolve<IModelBindingService>();
            Person myModel = modelBindingService.ModelBind<Person >(context.Request);

           // ... do something

            await next.Invoke();
        });
```

**Comment by rynowak** [comment]
Model binding is not a standalone service and requires lots of state that's initialized by MVC. Using model binding outside of MVC is not supported, if you manage to find something that works, there is no guarantee that it will remain working in future releases.

You can (basically) find the code here https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Internal/ModelBindingHelper.cs#L270

**Comment by nojaf** [comment]
I see, too bad. Thanks for the reply.

**Comment by nojaf** [comment]
I heard in the community stand up that Modelbinding might be refactored in the 2.1 release.
Extracted away from Mvc. Could someone confirm these plans? Is there an issue for this yet?

**Comment by rynowak** [comment]
> I heard in the community stand up that Modelbinding might be refactored in the 2.1 release.

If you heard it from @DamianEdwards then it's true that this is something *we want to do in the future*. Right now it's an idea and not a promise 😆 

The way that this works is that a list of these ideas gets prioritized, and then a smaller set of those ideas get planned and then work actually starts. Then, when something is ready it gets shipped.

Right now we're in the stage of prioritizing ideas for 2.1. Usually once we've get an understanding what's going to actually be worked on, we'll update the roadmap or make an announcement.

> Extracted away from Mvc. 

Yes. The intent would be to make something standalone. 

I'd also like to add that whatever we'd build would be more sophisticated and powerful, and it may not be 100% compatible with MVC's existing feature set. It would be possible to use MVC with the new model binding system or the old one, probably on a per-action granularity.

> Could someone confirm these plans?

No. This is something we are strongly considering for a future release. There is no official plan and no commitment from us.

> Is there an issue for this yet?

I just created #6549 for this purpose. If you have specific feedback, please put it there

**Comment by nojaf** [comment]
Thanks for the clarification @rynowak!
