### ISSUE TITLE
Decoupled View method from Controller.

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Mvc#6114]
I need to call `View("View",model)` out of a controller to render a Razor view with given dynamic model.
I think this is nice to can  render a view with it's model outside of the controller context.
thanks to consideration

**Comment by Eilon** [comment]
Hi @mikeandersun , we have a sample of rendering a Razor file to a string here: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString

**Comment by mikeandersun** [comment]
Why I have to have View related methods in a controller when my controller is an API and doesn't use view functionalities at all?

     
      ```  public virtual PartialViewResult PartialView();
        public virtual PartialViewResult PartialView(string viewName);
        public virtual PartialViewResult PartialView(object model);
        public virtual PartialViewResult PartialView(string viewName, object model);
        public virtual ViewResult View();
        public virtual ViewResult View(string viewName, object model);
        public virtual ViewResult View(object model);
        public virtual ViewResult View(string viewName);
        public virtual ViewComponentResult ViewComponent(Type componentType);
        public virtual ViewComponentResult ViewComponent(string componentName);
        public virtual ViewComponentResult ViewComponent(string componentName, object arguments);
        public virtual ViewComponentResult ViewComponent(Type componentType, object arguments);```


I thinks this methods can move to another place .I don't now where now :)

**Comment by Eilon** [comment]
@mikeandersun the Controller base class is for all controllers. I don't think anyone expects every controller to use every method. Hopefully you can just use the ones you like, and ignore the ones you don't 😄
