### ISSUE TITLE
The namespace for Controller 

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Mvc#6118]
The namespace for Controller is ` Microsoft.AspNetCore.Mvc` but it is in `Microsoft.AspNetCore.Mvc.ViewFeatures` package !

**Comment by Eilon** [comment]
Indeed, assemblies/packages and namespaces don't/can't always match. With MVC generally we recommend using the `Microsoft.AspNetCore.Mvc` package, which brings in all the requirements for ASP.NET Core MVC applications.
