### ISSUE TITLE
Can we do laravel type of routing with parameters?  

### ISSUE THREAD

**Issue by rykr** [aspnet/Mvc#6119]
The format would be something like   controller/action/param1/param2/param3  instead  of controller/action?param1=value&param2=value

**Comment by Muchiachio** [comment]
Yes you can, try using `{controller}/{action}/{param1}/{param2}/{param3}` as a route.

**Comment by rykr** [comment]
How does that work?  I tried it on my current site and it doesn't work.  Do I have to enable it somewhere?

**Comment by Muchiachio** [comment]
It's hard to explain how it works, but it should do what you want (use a different url format and map it to parameters). You can read more about routing [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing). And find information on how to enable it [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing).

So your route registration will look like this
```C#
app.UseMvc(routes =>
{
   routes.MapRoute("default", "{controller}/{action}/{param1}/{param2}/{param3}");
});
```

**Comment by rynowak** [comment]
What I'd recommend if you want to do something like this is to define your default route like @Muchiachio described, and then replace the `RouteValueProviderFactory` (`MvcOptions.ValueProviderFactories`) with one that will split the value into `param1`, `param2`, etc....

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
