### ISSUE TITLE
Loosen ViewComponent invoke restrictions

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#612]
@rynowak and I talked a bit about this in person and I found it very unappealing how in today's world we don't provide a default signature for Invoke/InvokeAsync which makes building ViewComponents inconvenient.

Potential fixes to this could be allowing 
```C#
Component.InvokeAsync("typeName", "methodName", myparams)
```
Or some derivative. Even possibly:
```C#
Component.Invoke<MyParamObject>("typeName", new MyParamObject(...))
```
Which would allow us to have a virtual Invoke/InvokeAsync signature.

Of course these are just ideas thrown around and neither may be the right solution to the problem.  We should discuss making this API simpler and easier to get started with to prevent users from writing code that never gets invoked.

**Comment by rynowak** [comment]
Clearing triage per discussion at #3211

**Comment by tuespetre** [comment]
Very much do want the syntax @rynowak demonstrated

**Comment by NTaylorMullen** [comment]
Talked about this in person and to make it as epic as possible we definitely need to sit down and think this one through :smile:

**Comment by NTaylorMullen** [comment]
After discussion we've come up with the following changes:

- Remove `Invoke` & `Render` methods on `@Component`, this leaves only `InvokeAsync`.
- Remove overloading.
- Modify `@await Component.InvokeAsync` to only support `Dictionary<string, object>` and anonymous objects as parameters.

**Comment by dougbu** [comment]
> only support `Dictionary<string, object>` and anonymous objects as parameters

FYI we have similar restrictions on `htmlAttributes` parameters in `IHtmlHelper` methods. Made the decision there to only have `object htmlAttributes` overloads and use `as IDictionary<string, object>` where necessary.

**Comment by sephiroth2m** [comment]
I have Invoke with parameter of SHORT type [Invoke(short id)], when I call @Component.Invoke(1) it throws "InvalidOperationException: Could not find an 'Invoke' method matching the parameters". But when I modify it to INT [Invoke(int id)], it works

**Comment by pranavkm** [comment]
@sephiroth2m I think that might be a still problem (due to how we reflection invoke). I'll file a separate bug for it.

**Comment by pranavkm** [comment]
@sephiroth2m, this doesn't work in general for integer values:

```C#
int x = 1;
Invoke(x); // Fails to compile

public IViewComponentResult Invoke(short y) => null;
```

You could try doing `@Component.Invoke((short)1)` and that should work.
