### ISSUE TITLE
Unskip error page functional test

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#6120]
Following commit skipped the functional test as this was blocking the mirror and is potentially a behavior change to which we need to react.

Reference files(**Note**: Rename the file extensions to `.html`):
[NewErrorPage.zip](https://github.com/aspnet/Mvc/files/915040/NewErrorPage.zip)
[OldErrorPage.zip](https://github.com/aspnet/Mvc/files/915041/OldErrorPage.zip)

cc @pranavkm @mikeharder

**Comment by kichalla** [comment]
Commit: 106b34867d7b7bba45e36ea4385e68311cad3b13

**Comment by NTaylorMullen** [comment]
08965550addf660ad1ec43d32c93987eb205192e

**Comment by pranavkm** [comment]
👍

**Comment by kichalla** [comment]
It appears this issue is resurfacing again in the mirror, probably because the corefx team merged their commits from preview1(where it regressed) to dev(where it was working when @NTaylorMullen unskipped this).

**Comment by Eilon** [comment]
@kichalla - should this issue be in preview2 then?

**Comment by kichalla** [comment]
Yes, this would be for preview2. Changed the milestone now. I re-opened this issue: https://github.com/aspnet/Diagnostics/issues/372

Commit to revert later: d916cfeaddbda9f17da1998e42af85ec8c8dc3f4

**Comment by NTaylorMullen** [comment]
@kichalla Do the right people know that this was regressed over on the coreclr team?

**Comment by kichalla** [comment]
@NTaylorMullen I created the following issue now: https://github.com/dotnet/corefx/issues/19838

**Comment by kichalla** [comment]
This has been fixed. Reverted change 3c7a2dc847b4c4fa8d0d83bc0bcb5308f2b8bca4

**Comment by NTaylorMullen** [comment]
Re-skipping for desktop applications. https://github.com/dotnet/corefx/issues/19838

**Comment by NTaylorMullen** [comment]
Working around this by adding:

```XML
<DebugType Condition="'$(TargetFrameworkIdentifier)'=='.NETFramework'">Full</DebugType>
```
