### ISSUE TITLE
Expose a way to limit what RazorPages are available

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6123]
In the context of an MVC configuration, I need to be able to filter out some of the RazorPages that are discovered.

Context: 
Orchard is made of modules. Each tenant can decide which modules will be active. Each tenant has its own MVC configuration. With the current implementation all the pages of all the modules are active, potentially exposing code that should not be executed.

Ideally I should be able to replace the `FileProvider` that the `RazorProject` is using. I could then even provide a set of fake razor pages, like from database.

**Comment by rynowak** [comment]
> Ideally I should be able to replace the FileProvider that the RazorProject is using

You can already do this.

We'll still want to provide a way for an application model convention to 'remove' pages like you can for actions.

**Comment by rynowak** [comment]
> Ideally I should be able to replace the FileProvider that the RazorProject is using
> You can already do this.

Actually I lied, we should do this too.

**Comment by rynowak** [comment]
You can do this now by implementing an `IPageApplicationModelProvider`. This will let you exclude pages from the file system and from precompilation.

Let's discuss when you have some free time and make sure this will meet your needs.

**Comment by rynowak** [comment]
Discussed with @sebastienros and he thinks this is already good enough. Closing.
