### ISSUE TITLE
Support Filters for RazorPages

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6124]
Right now filters are not executed for Razor Pages.

I use filters to inject HTML content in the views based on external rules.
Examples:
- Widgets based on the current context (User, url, time of day) independently from the view
- Inject static resources like Scripts, Styles in the Layout based on the components that are executed during the page rendering

**Comment by pranavkm** [comment]
Presumably this is means action and result filters. We support, Resource, Auth and exception filters in RazorPages as of now.

**Comment by rynowak** [comment]
In this case we're talking about result filters. We'll likely have a story similar to action filters, but different. Result filters will probably 'just work'.

**Comment by rynowak** [comment]
688e5189910634f3ade4f00bedd1cc1f71072cdc

Result filters added
