### ISSUE TITLE
Configuring JsonOutputFormatter using AddMvcCore

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#6127]
I'm trying to setup a slimline ASP.NET Core pipeline and am using `AddMvcCore` instead of `AddMvc`. I've copied this mostly from [AddMvc](https://github.com/aspnet/Mvc/blob/9f3dfd98194d94362586bd5a8c1dccec9df38a48/src/Microsoft.AspNetCore.Mvc/MvcServiceCollectionExtensions.cs), omitting the Razor related items:

```
    public void ConfigureServices(IServiceCollection services) =>
        services
            .AddMvcCore(
                options => 
                {
                    // JsonOutputFormatter not found in OutputFormatters!
                    var jsonOutputFormatter = 
                        options.OutputFormatters.OfType<JsonOutputFormatter>.First();
                    jsonOutputFormatter.SupportedMediaTypes.Add("application/ld+json");
                })
            .AddApiExplorer()
            .AddAuthorization()
            .AddFormatterMappings()
            .AddRazorViewEngine()
            .AddRazorPages()
            .AddCacheTagHelper()
            .AddDataAnnotations()
            .AddJsonFormatters()
            .AddCors();
```

I want to add a MIME type to the `JsonOutputFormatter` but it can't be found in the `OutputFormatters` collection. That said, the app can still output JSON, so I think the `JsonOutputFormatter` is being added at a later time.

**Comment by rynowak** [comment]
The `AddXyz` methods run in the order you call them.
```
services.AddMvcCore().AddJsonFormatters().AddMvcOptions(options => { // do your work here });
```
should do the trick
