### ISSUE TITLE
Add MVC Controller with views using EF in VS2017 fails when DbContext is in separate project.

### ISSUE THREAD

**Issue by bgoodearl** [aspnet/Mvc#6130]
I've created a version of the ContosoUniversity core MVC app that has the Models and Data in separate projects.  ([https://github.com/bgoodearl/cu_sample_mp](https://github.com/bgoodearl/cu_sample_mp))
When I get to the step in the [original tutorial](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro) which [describes creating a StudentsController](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro#create-a-controller-and-views), an error message appears.

![codegeneratorfailure_20170413](https://cloud.githubusercontent.com/assets/270818/25021230/77ea4496-205f-11e7-81fd-2336b84dd8cc.png)

**Comment by frankwwu** [comment]
I experienced the same problem. I further narrowed down and figured out it was the Contoso.Data project caused the error. If I separate only Contoso.Models and keep the Data in the original place, it has no problem.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#456
