### ISSUE TITLE
Support specifying ChallengeBehavior in ChallengeResult

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#6133]
In some cases you need to be able to explicitly specify the ChallengeBehavior when issuing a challenge instead of relying on the default automatic behavior. Ex when using Azure AD B2C you initiate specific identity related user experiences (like edit profile, reset password, etc) by initiating OIDC challenge. See https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c/issues/2.

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Mvc/issues/5187.
