### ISSUE TITLE
Can't generate routes to controller/action from a Razor Page

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6140]
Something like this:

```
<a asp-route-area="Orchard.Admin" asp-controller="Admin" asp-action="Index">Dashboard</a>
```

Doesn't generate the correct route, and all parameters are on the query string.

Adding `asp-route-page=null` fixes the issue but `page=null` is added to the query string.

**Comment by DamianEdwards** [comment]
@pranavkm @rynowak

**Comment by rynowak** [comment]
Pulling this into preview 1.
