### ISSUE TITLE
cshtml view returns 404 in vscode

### ISSUE THREAD

**Issue by thienedits** [aspnet/Mvc#6142]
I posted in the omnisharp repo but hopefully can get some more guidance here. I have a very simple controller returning a cshtml view. Works when project is opened in Visual Studio Code but not vscode.

https://github.com/OmniSharp/omnisharp-vscode/issues/1252

**Comment by SilverioMiranda** [comment]
Upgrade your project to NetCore 1.1 with msbuild and try again

**Comment by pranavkm** [comment]
What are you doing to run your application in vscode?

**Comment by thienedits** [comment]
@pranavkm I am going to Debug window and clicking .Net Core Launch (web)

**Comment by pranavkm** [comment]
What's the working directory set to in your application? The template assumes your content root is based off the current directory, so an incorrect directory would certainly explain the issue you're seeing here.

**Comment by thienedits** [comment]
Hi @pranavkm another dev set this up and I am not very familiar with .Net but I think its currently a folder called DiceWeb6. Inside this director there is a Controllers and Views directory

**Comment by thienedits** [comment]
here is the vscode launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "default",
            "program": "${workspaceRoot}\\bin\\Debug\\netcoreapp1.0\\DiceWeb6.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_URLS": "http://localhost:9876",
                "ASPNETCORE_ENVIRONMENT": "Development"  
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}\\Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}
```

**Comment by pranavkm** [comment]
The workspace settings seem right at first glance, but it would be useful to look at what the `ContentRoot` \ PWD is in a running application. Also, does it work if you execute `dotnet run` from the shell?

**Comment by thienedits** [comment]
yes seems running `dotnet run` works.

**Comment by pranavkm** [comment]
@thienedits, could you print out what the `ContentRoot` is from inside the process - running `Console.WriteLine(Directory.GetCurrentDirectory());` from your `Program.Main()` should suffice?

**Comment by thienedits** [comment]
@pranavkm 
```
Hosting environment: Development
Content root path: C:\pub\inferno-core\src\DiceWeb6
Now listening on: http://*:9876
Application started. Press Ctrl+C to shut down.
```

**Comment by pranavkm** [comment]
I tried setting up a using the preview2 CLI + the launchsetting.json you have (vscode auto generates something pretty identical) and it worked fine for me (this was on Ubuntu 16.04 machine, I don't have access to a OSX machine), and that seemed to work fine for me. At this point, I'd recommend updating to the RTM CLI tooling since `dotnet run` does work and I'm not sure if you're running in to a bug in the preview CLI tooling that was fixed.

**Comment by thienedits** [comment]
ok i will take a look thanks.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
