### ISSUE TITLE
Taghelpers not resolving when accessing an action with different Http(Post,Get) signature

### ISSUE THREAD

**Issue by SilverioMiranda** [aspnet/Mvc#6146]
I dont know if this is the desired behaviour but i dont see any warning about this in documentation

The example :

I have 2 actions 

```
[HttpGet("{id}/[action]")]
public ActionResult CadastrarPromocao(long id)
{
    ...
}
```
And this (it doesnt work as espected and the url generated is wrong)

```
[HttpPost("[action]")] /// <- missing {id}/
[ValidateAntiForgeryToken]
public IActionResult CadastrarPromocao(CadastrarPromocaoViewModel vm)
 {
    ...
}
```

Because i dont need the {id} i removed it from route parameters, and because of that the url generated by taghelper configured as above is : "/produtos/cadastrarpromocao?id=1"

`<a class="btn btn-info" asp-controller="Produtos" asp-action="CadastrarPromocao" asp-route-id="@Model.ProdutoId">Cadastrar promoção</a>`

And after add "{id}/[action]" to HttpPost i get the correctly url : "/produtos/1/cadastrarpromocao"

So i wanna know if 

- There is any way to define what Http* we want to use when taghelper is making the route, like asp-route-httpmethod="post" for example?
- This is the expected behaviour and i did wrong?

Thank you

**Comment by rynowak** [comment]
> There is any way to define what Http* we want to use when taghelper is making the route, like asp-route-httpmethod="post" for example?

No, routing use the combined values of `controller` and `action` to determine a set of candidates. When there are multiple candidates (two actions with the same name or two routes on a single action) routing uses a best-effort algorithm based on other route values like `id` to try and determine what you intended. So if you provide `id` and one of the routes defines a parameter `{id}`, that route becomes 'better'. The HTTP method isn't of the 'next' request isn't known or provided to routing. 

My advice first advice is to stick to the common pattern and provide the id in the route if this is a basic CRUD flow. My second advice (if you can't do that) is to use named routes where you really want to be precise. https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing#route-name

**Comment by SilverioMiranda** [comment]
Ok, thx for your explanation :)
