### ISSUE TITLE
UseStatusCodePagesWithRedirects does not work on Azure

### ISSUE THREAD

**Issue by moraleslos** [aspnet/Mvc#6147]
Have an ASP.NET core app built using only RESTful services and an SPA built with React JS and client-side routing utilizing these services. In my startup I added this line:` app.UseStatusCodePagesWithRedirects("/");` to make sure that all status code errors go back to the root and hence loads the main index page.

This works great on localhost-- any url refresh or incorrect path entered in the browser will redirect to the main index page.  However when I deploy this exact app on Azure, it will not redirect.  Checking the console it essentially shows that it doesn't even redirect-- just tries to go to the url entered and gets a 404.  So, for example, if I did https://example.com/account and hit refresh, I expect it to redirect to https://example.com. However it just goes to https://example.com/account, hence get the standard error page _"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."_

Any ideas on how to resolve this issue on azure?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Diagnostics#361
