### ISSUE TITLE
Consider adding a button Tag Helper

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6152]
We want a tag helper that we can wire up to work with form-action/handler/whatever it's called for pages.

```
<button asp-handler="delete">Delete</button>
```

**Comment by hishamco** [comment]
It's a cool idea .. I already implement such a feature
```html
<button asp-command="delete">Delete</button>
```

it would be nice if we can pass a param too
```html
<button asp-command="delete" asp-command-args="23">Delete</button>
```

**Comment by rynowak** [comment]
This is actually already done.

**Comment by hishamco** [comment]
Oh really!! I don't know about it

**Comment by hishamco** [comment]
Could you please refer to it?

**Comment by rynowak** [comment]
Yeah, right here https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/FormActionTagHelper.cs

**Comment by hishamco** [comment]
Thanks it seems like what we have seen in MVC, it would be nice if extend this to have something useful for CRUD operation, such as

```html
<button asp-command="delete" asp-command-args="23">Delete</button>
```
where `delete` is the page, `23` the id passed into the `OnGet` or `OnPost`
