### ISSUE TITLE
Constructor of ControllerModel does not set Controller property for ActionModels

### ISSUE THREAD

**Issue by Dresel** [aspnet/Mvc#6159]
Hi,

when using the `ControllerModel` constructor `public ControllerModel(ControllerModel other)` the "deep copies" of the `ActionModel`s still point to the old ControllerModel:

	public class ModelConventionTest : IApplicationModelConvention
	{
		public void Apply(ApplicationModel application)
		{
			ControllerModel oldControllerModel = application.Controllers.First();
			ControllerModel newControllerModel = new ControllerModel(oldControllerModel);

			if (newControllerModel.Actions.Any(x => x.Controller != newControllerModel))
			{
				Debug.WriteLine("1");
			}

			if (newControllerModel.Actions.All(x => x.Controller == oldControllerModel))
			{
				Debug.WriteLine("2");
			}
		}
	}

Is this by design? If not this could be maybe fixed after [copying the ActionModels](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ControllerModel.cs#L64)?

**Comment by rynowak** [comment]
This is definitely a bug.

**Comment by Dresel** [comment]
Do you want me to go for a PR?

**Comment by rynowak** [comment]
Yes if you don't mind 👍  - we need to fix the same bug for `ControllerModel`, `ActionModel`, `ParameterModel`, and `PropertyModel  - and [the relevant tests](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.Core.Test/ApplicationModel/ControllerModelTest.cs#L19) need to be udpated.
