### ISSUE TITLE
Databind byte[]

### ISSUE THREAD

**Issue by allannrodrigues** [aspnet/Mvc#6160]
I Have this class and when my form is submited the value from de form not going to controller. But when I changed the byte[] to int[] the value go to controller correctly.
```
public class ViewModel {
public byte[] IdStatusPedidoFornecedor { get; set; }
}

public class ViewModel {
public int[] IdStatusPedidoFornecedor { get; set; }
}
```
What's happening when I send an array of byte? MVC not have databind for byte array?

**Comment by rynowak** [comment]
MVC expects a byte-array to bind from a Base64-encoded string by default. This is special cased because `byte[]` is a common way to represent an blob of binary data, and Base64 is probably the most common way to send binary data over a text-based protocol. See https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/ByteArrayModelBinder.cs

If you want to prevent this from happening, you can remove the `ByteArrayModelBinderProvider` from the list of providers.

```
services.AddMvc(options => options.ModelBinderProviders.Remove(options.ModelBinderProviders.OfType<ByteArrayModelBinderProvider>().Single()));
```

**Comment by allannrodrigues** [comment]
I want send value like the inicialization of property. I'm use this case because in my database my property is a tinyint and I want use this array to make a contains in my query by entity framework without make a conversion.

How is the best way to make it?

I don't try to send a file. I'm want send a value from multiple select.

I'm make it wrong?

public class ViewModel {
public byte[] IdStatusPedidoFornecedor { get; set; } = new[]{1,2,3};
}

public class ViewModel {
public int[] IdStatusPedidoFornecedor { get; set; } = new[]{1,2,3};
}

my view(html)

<select multiple=""  class="form-control" id="IdStatusPedidoFornecedor" name="IdStatusPedidoFornecedor">
                                        <option value="">Selecione...</option>
                                    <option value="1">Pedido Aprovado</option><option value="2">Pedido Faturado</option><option value="3">Produto(s) em Rota de Entrega</option><option value="4">Entregue</option><option value="5">Reversa</option><option value="6">Cancelado</option><option value="7">Estornado</option><option value="8">Estornado Parcialmente</option><option value="9">Cancelado Parcialmente</option><option value="10">Pendente</option><option value="13">Reenviado</option><option value="16">Extraviado</option><option value="29">Resgate Aprovado</option><option value="30">Resgate Bloqueado</option><option value="31">Pedido não Concluído</option><option value="32">Transfer em Processamento</option><option value="33">Transfer Pendente</option><option value="34">Não Informado</option><option value="35">Não Informado</option><option value="36">Não Informado</option><option value="37">Pedido Aprovado</option></select>

**Comment by rynowak** [comment]
Using `byte[]` is fine, you need to remove the `ByteArrayModelBinderProvider` from the set of binders in your startup code, and then this should use the normal array behavior.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
