### ISSUE TITLE
API out-of-the-box ConflictRequestResult 

### ISSUE THREAD

**Issue by fabiomaulo** [aspnet/Mvc#6172]
Nice to have, especially for web-api, a **ConflictRequestResult** (409) and a method of Controller (as syntactic sugar).
As others cooked results (BadRequest, Accepted, Created etc.) the  ConflictRequestResult may have some overloads to include enough information for the user/app to recognize the source of the conflict.
Thanks.

**Comment by Eilon** [comment]
Seems reasonable. We need to add it to both MVC's `ControllerBase` and to Razor Pages' `PageModelBase`.

**Comment by Eilon** [comment]
See also https://github.com/aspnet/Mvc/issues/6795

**Comment by mistakenot** [comment]
Happy to have a go. Would this be a result type that only wants to live on the ControllerBase and none of the Razor Page stuff, as I presume it is API focused?

**Comment by rynowak** [comment]
> What is the case here?

Yes, this should just be added to controllerbase

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/e3ce1f52d4b5955e258e17b18ddc39d4b436268d
