### ISSUE TITLE
feature request - set s-maxage via ResponseCacheAttribute

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Mvc#6173]
_From @jimasp on April 19, 2017 15:33_

We can set max-age via the ResponseCacheAttribute.Duration property.
Could we have a corresponding property to set s-maxage?

_Copied from original issue: aspnet/ResponseCaching#119_

**Comment by JunTaoLuo** [comment]
_From @Tratcher on April 19, 2017 15:59_

That attribute lives in MVC: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ResponseCacheAttribute.cs
Please move this request over there.

**Comment by mkArtakMSFT** [comment]
Closing this as there were no much interest from community in this ask. Also, given the fact that any headers can be set manually this isn't a blocking issue.
