### ISSUE TITLE
[Feature] ViewComponentPages

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6182]
Like Razor Pages but for View Components with the handler inlined.

**Comment by rynowak** [comment]
👍

**Comment by DamianEdwards** [comment]
Wait, is this basically "write a View Component in a CSHTML file"?

**Comment by DamianEdwards** [comment]
Similar to "write a Tag Helper in a CSHTML file"

**Comment by BruinY** [comment]
I also focused on the problem, who knows

**Comment by mkArtakMSFT** [comment]
Moving this to Backlog as this is not a priority at the moment. /cc @DamianEdwards

**Comment by mkArtakMSFT** [comment]
Closing this as we have no plans to do this.
