### ISSUE TITLE
Relative page URL generation doesn't support local folder relative paths prefixed with ./

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6190]
APIs that accept relative paths for generating Page URLs, e.g. `<form asp-page="" />` and `RedirectToPage("")`, should support local folder relative URLs prefixed with `./`

Instead it appends it to the current page path and it ends up generating a URL that's app root relative with "page" in the querystring.

@pranavkm @rynowak

**Comment by rynowak** [comment]
Sounds good. 

@pranavkm @ryanbrandenburg let's figure out Monday which one of you has time to fit this into preview1.

**Comment by pranavkm** [comment]
@ryanbrandenburg can you have a look at this?

**Comment by rynowak** [comment]
Assigned to @ryanbrandenburg
