### ISSUE TITLE
Relative page URL generation should fail if a matching page can't be found

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6191]
Calling an API to generate a page URL should throw an exception if a matching page cannot be found. Its' annoying to debug situations where I've called an API to generate a page for a URL that doesn't exist (due to a typo) and it happily returns a URL that goes to the site root.

@pranavkm @rynowak

**Comment by rynowak** [comment]
you can @Eilon can duke this out then. I wanted to make that change across the board for core.

**Comment by Eilon** [comment]
This would be a huge breaking change to how routing works. We could do something MVC-specific (or even Razor Pages-specific), but that would seem out-of-place due to the inconsistency.
