### ISSUE TITLE
[Unique] Data annotation

### ISSUE THREAD

**Issue by 0mad0** [aspnet/Mvc#6195]
Currently, it's possible to ensure field uniqueness like this:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Model>()
        .HasIndex(m => m.Field)
        .IsUnique();
}
```

I'm not sure about other ways.

My proposition is to add [Unique] data annotation to simplify this process.

**Comment by frankabbruzzese** [comment]
You should submit your request to the EntityFramework core project.
