### ISSUE TITLE
razor page tests fails when core.autocrlf=input on Windows

### ISSUE THREAD

**Issue by ctaggart** [aspnet/Mvc#6205]
This looks to be a regression of #5907. cc @dougbu 

https://ci.appveyor.com/project/aspnetci/mvc/build/1.0.8623/tests
![image](https://cloud.githubusercontent.com/assets/80104/25389000/05313470-2995-11e7-9ea0-40bef6aae394.png)

This is causing the current build failure for #5905.

**Comment by ctaggart** [comment]
This is still broken. It is super easy to reproduce. You can see it broken here:
https://ci.appveyor.com/project/ctaggart/mvc/build/44

**Comment by Eilon** [comment]
@dougbu is there anything else here that you think is worth doing?

**Comment by dougbu** [comment]
6b2a702ff4

**Comment by dougbu** [comment]
Should have removed the `investigate` label a while ago 😃
