### ISSUE TITLE
asp-page-handler doesn't work correctly if asp-page isn't also specified

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6208]
See https://github.com/DamianEdwards/RazorPagesSample/blob/master/RazorPagesWebApplication/Pages/Account/Manage/ExternalLogins.cshtml#L28

It ends up with no `action` attribute being added to the form at all.

If I use `asp-route-handler` by itself it works fine.

@pranavkm @rynowak

**Comment by NTaylorMullen** [comment]
28e16ed965c3284309789cb94e595be3323292fe
8bece90c8309944f2ba0e247c829ea2c4fae7db6
