### ISSUE TITLE
Define crisp for semantics for what makes a pagemodel a pagemodel

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6210]
Consider the following:

```
public class MyModel
{
    [FromRoute]
    public int Value { get; set; }
}
```

```
@page
@model MyModel

@functions {
    public Task OnPostAsync(...) { ... } // Should this run?
}
```

Right now the decision depends on whether or not `MyModel` has a handler method. This is kinda haphazard 😞 

We need to define this semantic clearly. 

Idea:
- Naming convention based on `*Model` naming
- An attribute for a base class that says "all derived classes are pagemodels"
- Put that attribute on `PageModel`. 

This is pretty similar to what we do for controllers and VCs

**Comment by rynowak** [comment]
No one has complained.. Let's move this to preview3

**Comment by Eilon** [comment]
Discussed with @rynowak and we think that we should drop the naming convention for now.

We should just use the attribute, or any base class that has the attribute.
