### ISSUE TITLE
[Question] How to inject services into model conventions?

### ISSUE THREAD

**Issue by Dresel** [aspnet/Mvc#6214]
I didn't find any resources on how to use model conventions (e.g. `IApplicationModelConvention`) with dependency injection.

I guess conventions can't be registered in / created by the DI system, I have to build them manually and call `Conventions.Add`? How would I get registered services then? Is there a best practice how to inject services into conventions?

I found some code fragments where people used `services.BuildServiceProvider()` within `AddMvc` but I guess there is a more elegant solution?

**Comment by rynowak** [comment]
This is gross right now 😑 

I wonder if we should add some extension methods to make it better. You have to also register this as a convention:

```
public class MyConfigureOptions<TConvention> : IConfigureOptions<MvcOptions>
{
    private readonly TConvention _convention;
    public MyConfigureOptions(TConvention convention )
    {
        _convention = convention;
    }

    public void Configure(MvcOptions options) => options.Conventions.Add(_convention);
}
```

**Comment by Dresel** [comment]
Thank you, the picture gets clearer now.

Maybe you can help me with this use case. I've added an IMvcBuilder extension method. It should be able to somehow "setup" the class which gets injected into the convention from outside. This is what I've tried:

	public static IMvcBuilder AddMyThing(this IMvcBuilder mvcBuilder, Action<ClassUsedByConvention> setupAction)
	{
		mvcBuilder.Services.AddSingleton<ClassUsedByConvention>();
		mvcBuilder.Services.AddSingleton<Convention>();
		mvcBuilder.Services.AddSingleton<IConfigureOptions<MvcOptions>, ConventionConfigureOptions>();

		mvcBuilder.Services.Configure<ClassUsedByConventionOptions>(options => options.ClassUsedByConventionAction = setupAction);

		return mvcBuilder;
	}

The configuration would be an Options class:

	public class ClassUsedByConventionOptions
	{
		public Action<ClassUsedByConvention> ClassUsedByConventionAction { get; set; }
	}

And the modified convention:

	public class Convention : IApplicationModelConvention
	{
		public Convention(ClassUsedByConvention classUsedByConvention, IOptions<ClassUsedByConventionOptions> classUsedByConventionOptions)
		{
			ClassUsedByConvention = classUsedByConvention;
			ClassUsedByConventionOptions = classUsedByConventionOptions.Value;
		}

		protected ClassUsedByConventionOptions ClassUsedByConventionOptions { get; set; }

		protected ClassUsedByConvention ClassUsedByConvention { get; set; }

		public void Apply(ApplicationModel application)
		{
			ClassUsedByConventionOptions.ClassUsedByConventionAction(ClassUsedByConvention);
			ClassUsedByConvention.Apply(application);
		}
	}

Does this seem a correct way to do this for you or is there a better way with the DI system?

**Comment by rynowak** [comment]
@Dresel - we don't normally do things like this without a good reason.

```
public class ClassUsedByConventionOptions
{
	public Action<ClassUsedByConvention> ClassUsedByConventionAction { get; set; }
}
```

We'd just make `ClassUsedByConventionOptions` into a POCO that has all the knobs and dials for `ClassUsedByConvention`
```

You'd register a lamdba to configure `.Value` my mutating it or replacing it. We don't normally defer configuration of options **twice** - `.Configure(Action<TOptions>...)` is already deferred.

I'd also write `AddMyThing` like this
```
public static IMvcBuilder AddMyThing(this IMvcBuilder mvcBuilder, Action<ClassUsedByConventionOptions> setupAction)
{
	mvcBuilder.Services.AddSingleton<ClassUsedByConvention>();
	mvcBuilder.Services.AddSingleton<Convention>();
	mvcBuilder.Services.AddSingleton<IConfigureOptions<MvcOptions>, ConventionConfigureOptions>();

        if (setupAction != null)
        {
             mvcBuilder.Services.Configure<ClassUsedByConventionOptions>(setupAction);
        }
	
	return mvcBuilder;
}
```

**Comment by Dresel** [comment]
Sure, I would really appreciate that.

I'm working on a draft for an asp.net core version of [RouteLocalization](https://github.com/Dresel/RouteLocalization/tree/aspnet-core/dev). We discussed [this](https://github.com/aspnet/Mvc/issues/4774) a year ago.

This package allows fluent route localization, something like:

    setup.UseCulture("de")
      .WhereController(nameof(HomeController))
      .WhereAction(nameof(HomeController.Index))
      .TranslateAction("Willkommen");

[RouteLocalizationConvention](https://github.com/Dresel/RouteLocalization/blob/aspnet-core/dev/src/RouteLocalization.AspNetCore/RouteLocalizationConvention.cs) is the application model convention which uses the [RouteTranslator](https://github.com/Dresel/RouteLocalization/blob/aspnet-core/dev/src/RouteLocalization.AspNetCore/RouteTranslator.cs) to modify the model and add the specified translations.

Before trying to inject the convention as a service and setup the configuration with options I manually created the `RouteTranslator` instance and passed it to the also manually created `RouteLocalizationConvention` within `AddMvc`.

Now I'm looking for a way to make the integration into mvc more elegant, and [that](https://github.com/Dresel/RouteLocalization/blob/aspnet-core/dev/samples/RouteLocalization.AspNetCore.Sample/Startup.cs#L69) is what I'm currently doing at the moment.

Any feedback is appreciated.

**Comment by rynowak** [comment]
OK, I'm going to un-question this so we don't lose track of it.

@Eilon - what would you think about us doing some work to make this better?

**Comment by Eilon** [comment]
@rynowak no particular objection, seems useful. We need to do some triage / issue cleanup anyway.

**Comment by raizam** [comment]
Hi, I ended up here because I'm looking for a way to retrieve a `ModelMetadata`  for each `ParameterModel `found in an `IApplicationModelConvention`. My understanding is that I need to retrieve some service from the `IApplicationModelConvention` ? 
In fact I just need the IsComplexType property from the `ModelMetadata`
Can anyone point me to right direction? Thanks

**Comment by raizam** [comment]
After digging the sources, I just looked [how IsComplexType is set](https://github.com/aspnet/Mvc/blob/c95c2a5a6d8e1a4348d5a05f0ecba39229076cf7/src/Microsoft.AspNetCore.Mvc.Abstractions/ModelBinding/ModelMetadata.cs#L441) and implemented it my convention.

So in my case I don't need any injection, thanks anyway =)

**Comment by rynowak** [comment]
In case were curious after all, the service you were looking for was `IModelMetadataProvider`

**Comment by raizam** [comment]
thanks @rynowak, I did figure this out, but I still didn't get how to inject services in a IApplicationModelConvention, I'd need to read the magic posted above couple times =)

**Comment by rynowak** [comment]
To help make sense of the answer I gave [above](https://github.com/aspnet/Mvc/issues/6214#issuecomment-297880860), `IOptions<>` is a pattern for  configuring a POCO object via the DI system (and accessing it via the DI system.

Any class registered with DI as `IConfigureOptions<MvcOptions>` will be retrieved and called when the framework starts up. This is the mechanism that's at work behind the scenes when you call `AddMvcOptions(options => ... )`. We register an object in DI that will call your delegate.

So, the more formal way to configure `MvcOptions` is to write your own class `MyConfigureOptions<TConvention>` and put **that** in DI. Then because `MyConfigureOptions<TConvention>` is in DI, you can put `TConvention` in DI, and presto, now you've got access to services 👍

**Comment by Dresel** [comment]
Is there any work ongoing related to this "issue"? I'm just curious because I once again came across this. What I did for now is wrapping this workaround into extension methods and generic options:

```c#
public class ConfigureOptionsWithDependency<TOptions, TDependency1>
{
    public Action<TOptions, TDependency1> Action { get; set; }
}

public class ConfigureOptionsWithDependencyContainer<TOptions, TDependency1> : IConfigureOptions<TOptions>
    where TOptions : class, new()
{
    public ConfigureOptionsWithDependencyContainer(TDependency1 dependency1,
        IOptions<ConfigureOptionsWithDependency<TOptions, TDependency1>> configureOptionsWithDependency)
    {
        ConfigureOptionsWithDependency = configureOptionsWithDependency.Value;

        Dependency1 = dependency1;
    }

    public ConfigureOptionsWithDependency<TOptions, TDependency1> ConfigureOptionsWithDependency { get; set; }

    public TDependency1 Dependency1 { get; set; }

    public void Configure(TOptions options)
    {
        ConfigureOptionsWithDependency.Action(options, Dependency1);
    }
}

public static class ServiceCollectionExtension
{
    public static IServiceCollection ConfigureWithDependencies<TOptions, TDependency1>(this IServiceCollection serviceCollection, Action<TOptions, TDependency1> configureOptions) where TOptions : class, new()
    {
        serviceCollection.AddSingleton<IConfigureOptions<TOptions>, ConfigureOptionsWithDependencyContainer<TOptions, TDependency1>>();
        serviceCollection.Configure<ConfigureOptionsWithDependency<TOptions, TDependency1>>(options => { options.Action = configureOptions; });

        return serviceCollection;
    }
}
```

Then considering this Convention ...

```c#
public class SomeConvention : IApplicationModelConvention
{
    public SomeConvention(ISomeDependency someDependency)
    {
    }

    public void Apply(ApplicationModel application)
    {
    }
}
```

... you could easily do something like this without creating additional option classes:

```c#
services.AddSingleton<SomeConvention>();
services.AddSingleton<ISomeDependency, SomeDependency>();

services.ConfigureWithDependencies<MvcOptions, SomeConvention>((options, convention) =>
{
    options.Conventions.Add(convention);
});
```

This is for one dependency, but overloading with `TDependency2`, `TDependency3` etc. should be no big deal.

Is this a good solution or am I overlooking any drawbacks? Or is there even something better out now? Any feedback is appreciated.

**Comment by rynowak** [comment]
There's nothing planned here for 2.0.0. I'd like to do something like your sample for 2.1.0

**Comment by mkArtakMSFT** [comment]
Looks like the initial concern is now covered by https://github.com/aspnet/Options/issues/236. Closing this as that will cover most of the ask.
