### ISSUE TITLE
RazorPage WriteLiteral could more compact/fast-path types

### ISSUE THREAD

**Issue by benaadams** [aspnet/Mvc#6216]
Currently it uses `string` which means each time a page is rendered it needs to convert from UTF16 to the output encoding (likely utf8)
```
  IL_0019:  ldstr      "\r\nDuis sollicitudin mauris nec molestie molestie. "
    + "Etiam ipsum quam, tincidunt quis egestas non, euismod id lacus. Nulla n"
    + "isi magna, auctor vitae turpis ut, congue interdum lectus. Nulla vehicu"
    + "la, dui id venenatis tincidunt, magna lacus tristique enim, ut sodales "
    + "nulla neque quis ligula. Vivamus volutpat laoreet molestie. Pellentesqu"
    + "e elementum porta volutpat. Curabitur dui sapien, imperdiet nec velit i"
    + "nterdum, venenatis pulvinar neque. Vivamus venenatis hendrerit nunc, ve"
    + "l mattis justo tristique nec. Mauris ullamcorper posuere tellus, eget c"
    + "ongue ipsum sagittis eget. Integer ultrices sit amet nisl at venenatis."
    + " Sed vel venenatis urna, ac scelerisque augue."
IL_001e:  callvirt   instance void [Microsoft.AspNetCore.Mvc.Razor]
    Microsoft.AspNetCore.Mvc.Razor.RazorPage::WriteLiteral(object)
```

Instead they could be stored as an new type `asciiBytes` and if non-ascii chars were encountered in the compilation `utf8Bytes` in class readonly static which would be shims on `byte[]`.

This would mean they would use on average half the memory; and could if output encoding was compatible just be put directly on the wire without re-encoding. (Hence ascii/utf8 split as more encodings are compatible with ascii); then only re-encode if it needs to switch.

`string` could still be used for shorter literals (< *n* chars) e.g. tag names to make use of string interning; if a custom interning scheme wasn't to be devised.

This would allow larger chunks of html in pages to be stored and output more efficiently.

**Comment by rynowak** [comment]
This is something we've investigated in the past, and I don't know if we ever got far enough to get a concrete result out of it. The savings in static memory would be nice to have.

**Comment by rynowak** [comment]
This issue was moved to aspnet/Razor#1263
