### ISSUE TITLE
How to make automatic browsing to images from database ?

### ISSUE THREAD

**Issue by ahmedba** [aspnet/Mvc#6220]
I work in MVC 5 c# in visual studio 2015 web applications

I have table pictures in SQL server 2012 have two fields

ID

Image

ID have number of image inserted like 1,2,3,4,5

Image field store picture added

what i need actually browsing images found in table pictures in database from last image inserted to first in page

and browsing between every image and another 1 second automatically without using button or scroll

suppose i have 4 images in database in table pictures

after page open picture 4 display after 1 second picture 3 display after 1 second picture 2 display after 1 second picture 1 display .

How i do that please ?

**Comment by mht0648** [comment]
You can retrieve the data set as normal. 
Then you can reverse loop the data set or copy that data set to an empty data set in reverse order.
You have to use Asynchronous methods / Timer to browsing the images.

**Comment by Eilon** [comment]
This type of question is a better fit for a site such as https://stackoverflow.com/.
