### ISSUE TITLE
Tag Helper "asp-append-version" doesn't working as intended if called from Ajax (PartialView)

### ISSUE THREAD

**Issue by OrihuelaConde** [aspnet/Mvc#6221]
The tag helper "asp-append-version" is not working as intended if the Partial View is called by Ajax. It generates a different version number, therefore, the browser can't cache the file.

Am I doing something wrong or it is the correct behavior of the browser when working with Ajax?

From Ajax:
![captura de pantalla 2017-04-30 15 06 53](https://cloud.githubusercontent.com/assets/12591371/25567193/d19df78c-2dbe-11e7-91bd-14612e8d3d76.png)

From Action:
![captura de pantalla 2017-04-30 16 03 33](https://cloud.githubusercontent.com/assets/12591371/25567195/d6576e16-2dbe-11e7-98e1-878f09bce0c2.png)

**Comment by DamianEdwards** [comment]
Could you put together a minimal application that reproduces the issue, then place it on a GitHub site, Gist, or ZIP/TAR for download, and link it here please?

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce the issue.
