### ISSUE TITLE
Validation and fields updated during action filter execution.

### ISSUE THREAD

**Issue by nhwilly** [aspnet/Mvc#6225]
During a user's login, I issue a JWT token for authentication containing claims for a user's user id and account id.  That token is presented for each call to my API.

For *almost* every document I store, I'll need those values to be present in my final entities.  So I thought I would use an action filter to centralize the logic of extracting them, etc.

To do that, I added two fields to my data transfer POCOs and wanted the filter to populate them so by the time my controller gets the incoming model argument, it already contains the values.  The fields have been marked as required in the POCO, so validation will pick them up, if somehow they are not present. 

Automapper will then move them to my full entities so my services and repositories can work with them.

But the ModelState is already set to "invalid" by the time the action filter gets it, since at the very least, those two values haven't been filled and binding is run prior to my action filter being executed. Filling in those values may actually make the model valid.  In fact, most times it will.

In my filter code, if the incoming model inherits from an abstract class, "Accountable", I populate the fields, clear the ModelState errors and revalidate.

It works, but maybe I've gone about it all wrong.

Maybe I should keep the action filter for validation, but remove the required attributes on those two fields.  Let model binding do it's thing for other simple attributes (email, etc.)  and short circuit the request on failure.

And then use FluentValidation on my **entity** models _after_ Automapper gets finished to catch everything else, including account id and user id.

I expect to have to use Fluent anyway for more complex validation down the road.

Is there a better way?

**Comment by rynowak** [comment]
This is a great use case for writing a custom model binder. This will run alongside the built in model binders and more importantly will happen before validation.

Take a look at: https://github.com/aspnet/Docs/pull/3275 This is the docs article we've been working on for custom model binders. 

Feel free to ask more specific questions here - if you have feedback on the article we'd like to hear that as well.

**Comment by nhwilly** [comment]
Ooh.  Thanks!  I’ll check it out.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nhwilly** [comment]
Struggling with this a bit.  It seems like your example is centered around binding to something in the query string.  I'm posting a raw JSON string:

![image](https://cloud.githubusercontent.com/assets/7560842/25673556/d62a4ac8-3005-11e7-9e7b-db9ce386a175.png)


What's happening is that I only get two items in the `bindingContext.ValueProvider` collection.  
![image](https://cloud.githubusercontent.com/assets/7560842/25673460/7d47fa7c-3005-11e7-8d39-9724b464db36.png)

So naturally, it doesn't find mine.  Can you tell me what I've done wrong (or misunderstood)?  TIA

Here's my data class:

    [ModelBinder(BinderType = typeof(AccountableEntityBinder), Name ="accountable")]
    public class InvitationForCreate : Accountable
        {
        [EmailAddress]
        [Required]
        public string InviteeEmail { get; set; }
        [Required]
        public bool ConfirmBeforeUse { get; set; }
        public string InvitorIpAddress { get; set; }
    }

And this is the controller:

        [Route("")]
        [Authorize(Policy = OwnerRoleName)]
        [HttpPost]
        public async Task<IActionResult> Post([FromBody]InvitationForCreate invitation)
        {
            try...

And this is the (very incomplete) binder:

    public class AccountableEntityBinder : IModelBinder
    {
        public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            var modelName = bindingContext.BinderModelName;
            if(string.IsNullOrEmpty(modelName))
            {
                modelName = "accountable";
            }
            var valueProviderResult = bindingContext.ValueProvider.GetValue(modelName);
            bindingContext.ModelState.SetModelValue(modelName, valueProviderResult);
            var value = valueProviderResult.FirstValue;
            bindingContext.Result = ModelBindingResult.Success(value);
            return TaskCache.CompletedTask;
        }
    }

**Comment by nhwilly** [comment]
As far as the documentation goes, the text is good, but for someone just getting into this, it's not as clear as it could be from the code comments which method - the provider or the attribute - goes with which set of code, so it's a little too easy to get mixed up between the two (for me anyway).

If this helps, some of us use examples like a recipe, then fire up the debugger to try it and figure out what we missed and what we need to change for our use, or how stuff actually works.  The more clear and simple the recipe, the faster we figure out what we need to do to actually use it.

**Comment by ardalis** [comment]
Still cleaning it up - it (the sample) has better comments and is a bit cleaner now. Hoping to publish it today.

**Comment by nhwilly** [comment]
That's great.  I've tried comparing other stuff I've read about model binding, but almost everyone is trying to do something simple, instead of a more complex model.  I still can't get it to work.  

I know it's something really simple that I'm missing...

**Comment by nhwilly** [comment]
Ok, I think this is related to `context.Metadata.IsComplexType` and the fact that I don't know what that's doing.  If you would like to improve your docs, an example of posting a complex model is probably worth the effort, as that seems like a common use case.

**Comment by ardalis** [comment]
New doc will go live today. It includes this definition from the product team of Simple vs. Complex types, which is just that simple types are bound to a single input value, while complex types are bound to multiple input values. Does that help?

**Comment by nhwilly** [comment]
I'm sure it will.  

I think I missed the part where there's a binding provider for each property of a complex type and how to deal with that.  

I'll be sure to check it out as soon as it goes live.  Thanks.

**Comment by rynowak** [comment]
sorry @nhwilly - I've been out the last few days. I missed earlier that your model is coming from the body. That makes things a big more complex, but not impossible. Give me a bit and I'll get back to you with a sample.

**Comment by nhwilly** [comment]
No worries, @rynowak .  Glad there's someone to share some insight.

**Comment by rynowak** [comment]
Here's a more complete sample. Tailor it to fit you needs. I'm wondering if we need to patternize this so it's easier.

```
       public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(options =>
            {
                var body = options.ModelBinderProviders.OfType<BodyModelBinderProvider>().Single();

                options.ModelBinderProviders.Insert(
                    options.ModelBinderProviders.IndexOf(body),
                    new AccountableModelBinderProvider(body));
            });

            services.Insert(0, ServiceDescriptor.Singleton(
                typeof(IConfigureOptions<AntiforgeryOptions>),
                new ConfigureOptions<AntiforgeryOptions>(options => options.CookieName = "<choose a name>")));
        }

        public class AccountableModelBinderProvider : IModelBinderProvider
        {
            private readonly BodyModelBinderProvider _inner;

            public AccountableModelBinderProvider(BodyModelBinderProvider inner)
            {
                _inner = inner;
            }

            public IModelBinder GetBinder(ModelBinderProviderContext context)
            {
                if (typeof(Accountable).GetTypeInfo().IsAssignableFrom(context.Metadata.ModelType) &&
                    context.BindingInfo.BindingSource.CanAcceptDataFrom(BindingSource.Body))
                {
                    var ipAddress = context.Metadata.Properties["IpAddress"];
                    return new AccountableModelBinder(_inner.GetBinder(context), ipAddress);
                }

                return null;
            }
        }

        public class AccountableModelBinder : IModelBinder
        {
            private readonly IModelBinder _inner;
            private readonly ModelMetadata _ipAddressProperty;

            public AccountableModelBinder(IModelBinder inner, ModelMetadata ipAddressProperty)
            {
                _inner = inner;
                _ipAddressProperty = ipAddressProperty;
            }

            public async Task BindModelAsync(ModelBindingContext bindingContext)
            {
                await _inner.BindModelAsync(bindingContext);

                if (!bindingContext.Result.IsModelSet)
                {
                    // Binding failed, just bail out.
                    return;
                }

                if (_ipAddressProperty != null)
                {
                    var ipAddress = bindingContext.HttpContext.Connection.RemoteIpAddress.ToString();
                    _ipAddressProperty.PropertySetter(bindingContext.Result.Model, ipAddress);
                }
            }
        }
```

This adds a model binder provider that will take over whenever your model object is both derived from `Accountable` and has `[FromBody]`. This uses the body model binder to read the JSON payload into an object, and then sets the IP address (as an example).

Note that by using an approach like this (putting something like the IP address or other details) on a DTO object, you open yourself up to the client potentially setting it via JSON if you're not careful.

**Comment by nhwilly** [comment]
Wow!  Thanks.  I'd never had gotten this.  I'll give it a try on my stuff right away.

FWIW, I always assume some bored teenager is trying to jam total nonsense at my site, that's why the data I need is coming from a validated JWT token that I issue.  They can put junk in the model, but I'll overwrite it with whatever is in the token that I need.  As for the rest of the model, that get's validated normally.

**Comment by nhwilly** [comment]
I modified it to take two `context.Metadata.Properties["field name"]` and it worked great!

Thank you so much.  

I guess my only worry that this will run on _every_ request regardless of which `[FromBody]` model I'm trying to get, right?  Does that mean the reflection cost in `(typeof(Accountable).GetTypeInfo().IsAssignableFrom(context.Metadata.ModelType)` is going to be a performance hit?  I ask, because there may be more of this as the project moves on.

If it is, would it be possible to tie it to an attribute so it would only run on the endpoints where needed (like POST and PUT)?

That said, I can't believe how cool this is.  Love Asp.Net Core.

**Comment by nhwilly** [comment]
Works perfectly on an interface, too.

**Comment by nhwilly** [comment]
Oh, wait.  Never mind. That provider looks like it's cached after the first time it's run.  After that, it looks pretty efficient.  Awesome.

Too bad I have to do something else for the GETs.  Thank you so much for this...

**Comment by rynowak** [comment]
> Oh, wait. Never mind. That provider looks like it's cached after the first time it's run. After that, it looks pretty efficient. Awesome.

> Too bad I have to do something else for the GETs. Thank you so much for this...

Where does your data come from in gets?

**Comment by nhwilly** [comment]
Same place, the JWT bearer token.  I need the account id to set the partition key in a documentDb database.  I need the user id for preferences, notifications, etc.  I am also storing some permission values in there, but they're being handled by the `[Authorization]` attribute.

The idea was to eliminate the concerns of both extracting and requiring those values at the start of every controller.  That's how I got started.

But a GET requires everything to be in the query string, right?  So I can't bind to a `[FromBody]` model that way.  Or at least I haven't figured out how to.   And I don't want to kludge up the HTTP spec by doing a POST when I am just retrieving data.  That'll just make it hard for somebody else later.

I can write some extension methods or create a request object to pass to my services that contains it all if I need to.  I just really like the idea of the data transfer objects "just having" the values automatically.  And the stuff you proposed works great for POST, PUT and PATCH operations.

Unless I could find a way to jam a new object containing the values I want so that I could accept it in the signature... that would be pretty slick.

**Comment by rynowak** [comment]
> But a GET requires everything to be in the query string, right

We can model bind from the query string and from route parameters in the URL path.

If you want to use the same technique for get, yes you'd need to write a DTO for that.

**Comment by nhwilly** [comment]
I took swipe at that before you responded, thinking I might fall into it.  Not.

So I already have a DTO for the query object, let me see if I can figure this out on my own over the weekend without bothering you guys.  If not, I'll post my code and ask...

Thanks again.

**Comment by Eilon** [comment]
@nhwilly please let me know if it's ok to close this issue, or if you have any further questions. Thanks!

**Comment by nhwilly** [comment]
Oh, forgot to finish this up.  Thanks for reminding me.

I tried to apply what @rynowak showed me about binding stuff into an incoming model in the body for POST, PUT and PATCH, but I couldn't get it to work for a GET (queries _or_ routes) because `bindingContext.Result` always came back null.   I guess that makes sense.  What I ended up doing is below.  I have a feeling there's a much better way, but I really struggled trying to get it to work.

**In my controller:**
<pre style="font-family:Consolas;font-size:16;color:gainsboro;background:#1e1e1e;">[<span style="color:#4ec9b0;">HttpGet</span>(<span style="color:#d69d85;">&quot;{id}/{name}/{address}&quot;</span>)]
[<span style="color:#4ec9b0;">Validate</span>]
<span style="color:#569cd6;">public</span>&nbsp;<span style="color:#569cd6;">async</span>&nbsp;<span style="color:#4ec9b0;">Task</span>&lt;<span style="color:#b8d7a3;">IActionResult</span>&gt;&nbsp;Get(<span style="color:#569cd6;">string</span>&nbsp;id,&nbsp;<span style="color:#569cd6;">string</span>&nbsp;name,&nbsp;<span style="color:#569cd6;">string</span>&nbsp;address,&nbsp;[<span style="color:#4ec9b0;">FromRoute</span>]&nbsp;<span style="color:#4ec9b0;">AccountableClaims</span>&nbsp;claimBindings)
</pre>

**My binder provider:**
<pre style="font-family:Consolas;font-size:16;color:gainsboro;background:#1e1e1e;"><span style="color:#569cd6;">public</span>&nbsp;<span style="color:#b8d7a3;">IModelBinder</span>&nbsp;GetBinder(<span style="color:#4ec9b0;">ModelBinderProviderContext</span>&nbsp;context)
{
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">if</span>&nbsp;(<span style="color:#569cd6;">typeof</span>(<span style="color:#b8d7a3;">IClaimBindable</span>)<span style="color:#b4b4b4;">.</span>GetTypeInfo()<span style="color:#b4b4b4;">.</span>IsAssignableFrom(context<span style="color:#b4b4b4;">.</span>Metadata<span style="color:#b4b4b4;">.</span>ModelType)&nbsp;<span style="color:#b4b4b4;">&amp;&amp;</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context<span style="color:#b4b4b4;">.</span>BindingInfo<span style="color:#b4b4b4;">.</span>BindingSource<span style="color:#b4b4b4;">.</span>CanAcceptDataFrom(<span style="color:#4ec9b0;">BindingSource</span><span style="color:#b4b4b4;">.</span>Path))
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">return</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">ClaimBindingsModelBinder</span>();
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">return</span>&nbsp;<span style="color:#569cd6;">null</span>;
}
</pre>

**And my binder:**
<pre style="font-family:Consolas;font-size:16;color:gainsboro;background:#1e1e1e;"><span style="color:#569cd6;">public</span>&nbsp;<span style="color:#4ec9b0;">Task</span>&nbsp;BindModelAsync(<span style="color:#4ec9b0;">ModelBindingContext</span>&nbsp;bindingContext)
{
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">if</span>&nbsp;(bindingContext&nbsp;<span style="color:#b4b4b4;">==</span>&nbsp;<span style="color:#569cd6;">null</span>)
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">throw</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">ArgumentNullException</span>(<span style="color:#569cd6;">nameof</span>(bindingContext));
&nbsp;&nbsp;&nbsp;&nbsp;}
 
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">if</span>&nbsp;(bindingContext<span style="color:#b4b4b4;">.</span>ModelType&nbsp;<span style="color:#b4b4b4;">==</span>&nbsp;<span style="color:#569cd6;">typeof</span>(<span style="color:#4ec9b0;">IdentityClaims</span>))
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">var</span>&nbsp;boundResult&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">IdentityClaims</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AppUserId&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;bindingContext<span style="color:#b4b4b4;">.</span>HttpContext<span style="color:#b4b4b4;">.</span>User<span style="color:#b4b4b4;">.</span>FindFirst(SubjectKey)<span style="color:#b4b4b4;">?.</span>Value,
 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;};
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bindingContext<span style="color:#b4b4b4;">.</span>Result&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#4ec9b0;">ModelBindingResult</span><span style="color:#b4b4b4;">.</span>Success(boundResult);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">return</span>&nbsp;<span style="color:#4ec9b0;">TaskCache</span><span style="color:#b4b4b4;">.</span>CompletedTask;
 
&nbsp;&nbsp;&nbsp;&nbsp;}
 
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">if</span>&nbsp;(bindingContext<span style="color:#b4b4b4;">.</span>ModelType&nbsp;<span style="color:#b4b4b4;">==</span>&nbsp;<span style="color:#569cd6;">typeof</span>(<span style="color:#4ec9b0;">AccountableClaims</span>))
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">var</span>&nbsp;boundResult&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">AccountableClaims</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AccountId&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;bindingContext<span style="color:#b4b4b4;">.</span>HttpContext<span style="color:#b4b4b4;">.</span>User<span style="color:#b4b4b4;">.</span>FindFirst(AccountIdName)<span style="color:#b4b4b4;">?.</span>Value,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AppUserId&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;bindingContext<span style="color:#b4b4b4;">.</span>HttpContext<span style="color:#b4b4b4;">.</span>User<span style="color:#b4b4b4;">.</span>FindFirst(SubjectKey)<span style="color:#b4b4b4;">?.</span>Value,
 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;};
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bindingContext<span style="color:#b4b4b4;">.</span>Result&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#4ec9b0;">ModelBindingResult</span><span style="color:#b4b4b4;">.</span>Success(boundResult);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">return</span>&nbsp;<span style="color:#4ec9b0;">TaskCache</span><span style="color:#b4b4b4;">.</span>CompletedTask;
 
&nbsp;&nbsp;&nbsp;&nbsp;}
 
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">if</span>&nbsp;(bindingContext<span style="color:#b4b4b4;">.</span>ModelType&nbsp;<span style="color:#b4b4b4;">==</span>&nbsp;<span style="color:#569cd6;">typeof</span>(<span style="color:#4ec9b0;">TransactableClaims</span>))
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">var</span>&nbsp;boundResult&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">TransactableClaims</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AccountId&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;bindingContext<span style="color:#b4b4b4;">.</span>HttpContext<span style="color:#b4b4b4;">.</span>User<span style="color:#b4b4b4;">.</span>FindFirst(AccountIdName)<span style="color:#b4b4b4;">?.</span>Value,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AppUserId&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;bindingContext<span style="color:#b4b4b4;">.</span>HttpContext<span style="color:#b4b4b4;">.</span>User<span style="color:#b4b4b4;">.</span>FindFirst(SubjectKey)<span style="color:#b4b4b4;">?.</span>Value,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MerchantId<span style="color:#b4b4b4;">=</span>&nbsp;bindingContext<span style="color:#b4b4b4;">.</span>HttpContext<span style="color:#b4b4b4;">.</span>User<span style="color:#b4b4b4;">.</span>FindFirst(MerchantIdName)<span style="color:#b4b4b4;">?.</span>Value,
 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;};
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bindingContext<span style="color:#b4b4b4;">.</span>Result&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#4ec9b0;">ModelBindingResult</span><span style="color:#b4b4b4;">.</span>Success(boundResult);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">return</span>&nbsp;<span style="color:#4ec9b0;">TaskCache</span><span style="color:#b4b4b4;">.</span>CompletedTask;
 
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">return</span>&nbsp;<span style="color:#4ec9b0;">TaskCache</span><span style="color:#b4b4b4;">.</span>CompletedTask;
}
</pre>

**Comment by rynowak** [comment]
Sounds like this is resolved, If you have any more questions feel free to ask.
