### ISSUE TITLE
Getting CS0234: The type or namespace name does not exist on prod server

### ISSUE THREAD

**Issue by ErezSavir** [aspnet/Mvc#6228]
Hi

Running ubuntu 16.10 x64 server. 
Repo: https://github.com/ErezSavir/LessonManage

I have added a new view under View/Classes called AddSpecialEvent which is using a viewmodel called AddSpecialEventViewModel.

Each time I call this page, I get 
`0z1xakkb.0cu(422,765): error CS0234: The type or namespace name 'AddSpecialEventViewModel' does not exist in the namespace 'LessonManage.Models.ClassViewModels' (are you missing an assembly reference?)
`
This doesn't happen on my dev computer. It doesn't matter where I try to set the viewmodel the same error. 

But every other view under the same folders (viewmodels and views) is working.

Any ideas?

**Comment by rynowak** [comment]
Did you figure this out? what was the issue?

**Comment by ErezSavir** [comment]
Publish issue. I deleted everything from the server and published again without the ubuntu flag, dotnet publish -c Release
Then it worked.

**Comment by rynowak** [comment]
Ok thanks, we've been seeing a lot of `The type or namespace name 'blahblah' does not exist in the namespace ` issues, so I wanted to understand what this one was 👍
