### ISSUE TITLE
HttpClient, HTTP/2, IIS 8.5

### ISSUE THREAD

**Issue by toddtsic** [aspnet/Mvc#6230]
In development (Visual Studio MVC/WebApi project with built in web server), I have been successful calling apples apns api, however fail when I move to production (Windows 2012 R2).  The production WebApi application works fine, it just crashes on httpclient SendAsync to api.push.apple.com using http/2.

I can run a successful curl in production calling api.push.apple.com with all my parameters (returns 200 success code), but my httpclient code fails (generic "Error while copying content to a stream").  The code in development works great and I can send push notifications to mobile devices easily.

The curl shows successful negotiation of certificates (which I though may have been the problem as APNS requires Geo Trust Global CA root cert).

Logging shows all necessary parameters are being created (jwt token for example).

I'm stumped, would greatly appreciate assistance. ?IIS configuration, ?firewall issue...

**Comment by davidfowl** [comment]
For http client issues head to http://github.com/dotnet/corefx/
