### ISSUE TITLE
Add FSharpWebsite.fsproj to Mvc.sln

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Mvc#6238]
As per discussion: https://github.com/aspnet/Mvc/pull/6231#issuecomment-299285843

We can't do it yet because the F# tools for VS+.NETCore aren't yet shipped, so the `.fsproj` would never load in VS for anyone.

Once those tools have shipped, add this project to the solution, and check the developer experience both with and without them. As long as it's not a serious problem if you don't have the F# tools, we can go ahead. But if it is a serious problem, reconsider.

**Comment by mkArtakMSFT** [comment]
We don't want to cause noise from people who have no F# tools installed.
