### ISSUE TITLE
Custom data token association with AttributeRoutes

### ISSUE THREAD

**Issue by joshua-mng** [aspnet/Mvc#6244]
Hello, congrats on the great work being done here.

I have this problem where I can't find anywhere to apply custom data token values for the routes being generated via the attribute routes. 

Both `IActionDescriptorProvider` and `ApplicationModel` do not provide the feature I want.

Here is example: Let's say this action is inside a controller named 'ProductsController';

```
[Route]
public Product GetMyProduct(int id)
{
    return new Product();
}
```

I want to add custom data token key value pair for the route generated of this action.
It's very helpful feature, for example, when controllers are defined in external assemblies (like plugins or modules), we can associate custom data token for all the actions of all the controllers of external assemblies, and then identify the assembly (or plugin) by this data token etc ..

How can I do this currently? or do we need other extensibility?

Thanks

**Comment by rynowak** [comment]
You can do this using an `IActionModelConvention` or `IControllerModelConvention` and the `.Properties` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/ActionModel.cs#L119

You can write an attribute that implements one of these interfaces and place it on an action or controller, or register a convention in `MvcOptions` in startup code.
```
services.AddMvc(options =>
{
    options.Conventions.Add(...);
});
```

Any data you store here will be available later in `ActionDescriptor.Properties` for the action that is currently running.

**Comment by joshua-mng** [comment]
Yeah, it seems so. Thanks for the answer.

Maybe it's unrelated, but here is another question that's bugging me. LOL.

It's about IRouteValueProvider.

The documentation and source code says that it adds selected key and value to the RouteData.Values and then allows the action to be SELECTED by matching specified key value pair to the incoming RouteData.Values.

But I can't seem to find the exact source where this enforcement is being applied.

I thought there is special action constraint being added based on the IRouteValueProvider, and then ActionSelector applies this, can you explain the exact matching logic behind?

**Comment by rynowak** [comment]
>IRouteValueProvider attributes are converted to ActionDescriptor.RouteValues via the application model provider.

Yes

> If we are using conventional routing to map route templates to actions, then route template must produce matching key values which are then later used by the ActionSelector (specially Cache), this is how it USES ActionDescriptor.RouteValues in conventional routing

Yes

>  If attribute routing is used, then attribute routing DOES NOT MATCH incoming RouteData.Values to the ActionDesciptor.RouteValues, instead attribute route builds a predefined MvcAttributeRouteHandler objects for each unique route templates and already associates the actions for that route (hence no need to match), once appropriate ActionDescriptor is selected (by applying other IActionConstraints), then ActionDescriptor.RouteValues is used to populate the RouteContext.RouteValues

Yes

> The reason why I'm asking this is, I see that IRouteValueProvider is another feature that we can use to further extend default asp.net core mvc application structure, like MODULE -> AREA -> CONTROLLERS etc

Yes. We have a sample like this https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.SubAreaSample.Web/Mvc.SubAreaSample.Web.csproj

**Comment by joshua-mng** [comment]
Thanks @rynowak
