### ISSUE TITLE
app.config gets overwritten

### ISSUE THREAD

**Issue by vankampenp** [aspnet/Mvc#6245]
When including an app.config file in a project, it gets included in the <PROJECTNAME>.exe.config with every deployment. 
When reading the app.config file using ConfigurationManager.AppSettings in a referred .Net Framework library, it reads the app.config included in the <PROJECTNAME>.exe.config, not from the separately distributed file.

So it seems impossible to have different files per site, as the current app.config content is overwritten.

I have specified Build Action: None, and Do Not Copy. The file itself is not copied , but still included in the exe.config on distribution.

**Comment by Eilon** [comment]
This issue was moved to dotnet/sdk#1206
