### ISSUE TITLE
Should be possible to derive from DefaultControllerAssemblyProvider

### ISSUE THREAD

**Issue by kulmugdha** [aspnet/Mvc#625]
It should be possible derive from DefaultControllerAssemblyProvider instead of implementing IControllerAssemblyProvider.

Few of issues here:
1. I wanted to filter assembly list generated by DefaultControllerAssemblyProvider to match one more criteria. The class is not designed for overriding the IsCandidateLibrary or CandidateAssemblies method.
2. I needed to implement IControllerAssemblyProvider from scratch just to add a simple filter on top of assemblies that DefaultControllerAssemblyProvider lists.
3. As a work-around, I can have a class that contains an instance of DefaultControllerAssemblyProvider. I call CandidateAssemblies and filter the assemblies. In this case, the assemblies are already loaded, it will be very inefficient. We need to override at GetCandidateLibraries\IsCandidateLibrary level. Personally I just wanted to override IsCandidateLibrary method to provide another criteria.

**Comment by danroth27** [comment]
Dup of #1528.
