### ISSUE TITLE
Razor Views in class libraries do not have editor context awareness

### ISSUE THREAD

**Issue by BenjiZombie** [aspnet/Mvc#6253]
I have a modular ASP.NET project where some class libraries contain Razor Views that are fed using the EmbeddedFileProvider. Long story short, here's what I am facing in those views:

![image](https://cloud.githubusercontent.com/assets/1405804/25921778/b06f802e-35a4-11e7-8350-269ab9a79cb8.png)

"ViewData does not exists in the current context". Same goes for @model, etc. Everything compiles and runs fine, mind you. 

I found a previous issue here mentioning the Razor Tooling, but I am using VS 2017. 

Any ideas? Thanks

**Comment by NTaylorMullen** [comment]
Working on fixing this guy now actually. Follow https://github.com/aspnet/Razor/issues/1136 for its completion 😄
