### ISSUE TITLE
Bootstrap font rending issue randomly 

### ISSUE THREAD

**Issue by rangav** [aspnet/Mvc#6254]
Hi I published asp core website onto azure and its working fine. But i have one issue with bootstrap glyph fonts rendering. 

I am seeing the below issue randomly
![image](https://cloud.githubusercontent.com/assets/8637550/25935545/7f58dbbc-361b-11e7-89eb-ac15c80aac6f.png)
and bundle css output showing as **glyphicon-search:before{content:"î€ƒ"}**

Correct image should be 
![image](https://cloud.githubusercontent.com/assets/8637550/25935690/3488716e-361c-11e7-8f0d-29a9df742a81.png)

I am using bundleconfig to bundle the css files

Can anyone let me know how to fix this issue from reoccurring again.

**Comment by Eilon** [comment]
This issue was moved to madskristensen/BundlerMinifier#270
