### ISSUE TITLE
Better diagnostics when precompiled view lookup fails

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#6258]
*Copied from https://github.com/aspnet/Mvc/issues/4426#issuecomment-300929244*

Since razor precompilation will be on by default on the publish stage, more people will be affected by this.*

The issue I see here is that people developing on windows will hit this at runtime on production while errors will be silent at development time.

I'm ok with being careful (casing and relative paths) or to need an extra step of publish locally to test everything is working as expected. being said that, any tool/step that can improve the experience will be very appreciated.

*this = casing differences that result in precompiled lookups to fail.

**Comment by pranavkm** [comment]
cc @BartMax \ @DamianEdwards

**Comment by pranavkm** [comment]
Presumably this is less likely to happen now that we've removed case sensitivity as part of addressing https://github.com/aspnet/MvcPrecompilation/issues/37. We can re-open this if users discover other scenarios where this is problematic.

**Comment by Bartmax** [comment]
agree, looks like the right direction! 👍
