### ISSUE TITLE
Add StaticFileResult

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#6260]
If I want to return a static file from an MVC controller action, I basically need to replicate some of the logic of the static file server. To make this easier, it would be great if there was a static file result that rendered content from the web root.

```C#
public class MyController : Controller
{
     [HttpGet("/")]
     [Authorize]
     public IActionResult Get()
     {
         return StaticFile("index.htm");
     }
}
```

In the above example I'm using MVC for auth but the action result for auth'd users renders the index file. 

/cc @rynowak @danroth27 @SteveSandersonMS @Eilon

**Comment by rynowak** [comment]
I don't understand how this is different from https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs#L1201 
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/VirtualFileResultExecutor.cs#L49

Is this mostly about the mime-type mapping?

**Comment by davidfowl** [comment]
@rynowak yes, whatever the static file middleware does when it gets a file, this needs to do as well. Maybe it's  just mime mapping but I haven't looked to see if that is the only delta.

**Comment by rynowak** [comment]
We should find a way to expose and reuse that then. We don't have an O/L without a content type so it's something we could add.

**Comment by davidfowl** [comment]
@rynowak The static file result should just encapsulate that. The mime mapping could be a service.

/cc @Tratcher for awareness

**Comment by davidfowl** [comment]
Basically some of the in here (if not all) https://github.com/aspnet/StaticFiles/blob/d6c2834f95d69dfbb5a9cdd6bc54a1d510d27e4a/src/Microsoft.AspNetCore.StaticFiles/StaticFileContext.cs should be in this component.

**Comment by SteveSandersonMS** [comment]
Sounds good to me.

At first I thought it might not be necessary since applications can just combine `FileExtensionContentTypeProvider` and `FileResult` in a couple of lines to get a working result, but when you add in ETags and `Range` requests, it's way too complex to replicate in application code.

**Comment by Tratcher** [comment]
@jbagga is adding a lot of the missing functionality in https://github.com/aspnet/Mvc/pull/6150 (Ranges, conditionals, etc.).. The mime type lookup is one of the few missing pieces. The lookup is less critical from MVC, you're manually specifying the file name so you likely already know the mime type, it's not dynamic like it is for StaticFiles.

**Comment by sebastienros** [comment]
Aside from `content-type` could we also be able to specify `content-disposition`? It's important as it lets the action define the filename as seen from the client's perspective and if the client should trigger a download popup or not.

Example:
`Content-disposition: attachment;filename=reports.csv`

**Comment by Tratcher** [comment]
@sebastienros That's already available through FileDownloadName. https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Core/FileResult.cs#L41

**Comment by sebastienros** [comment]
@Tratcher great, and `attachment` ?

**Comment by Tratcher** [comment]
Yes, https://github.com/aspnet/Mvc/blob/4cca6b09f0044660d64469e3278b584a17c356e9/src/Microsoft.AspNetCore.Mvc.Core/Internal/FileResultExecutorBase.cs#L35

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Closing this as it seems most of this work has been done:
> @jbagga is adding a lot of the missing functionality in #6150 (Ranges, conditionals, etc.).. The mime type lookup is one of the few missing pieces. The lookup is less critical from MVC, you're manually specifying the file name so you likely already know the mime type, it's not dynamic like it is for StaticFiles.
