### ISSUE TITLE
Change Razor to use Assembly.Load(byte[]) and Assembly.LoadFile

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#6261]
Instead of the .NET Core specific `AssemblyLoadContext.Default`.

/cc @pranavkm

**Comment by Eilon** [comment]
@rynowak - can you spearhead this?

**Comment by rynowak** [comment]
6094c6ff520b0428b6fa8b1cc211d2533c4226b1

**Comment by rynowak** [comment]
Speared
