### ISSUE TITLE
ModelBindingContext.ValueProvider not have values using Ajax Post Data

### ISSUE THREAD

**Issue by jeanjn** [aspnet/Mvc#6262]
I implemented my own custom ComplexTypeModelBinder and works very well if I send my json in params. But now my object is very too large to send in querystring, so I should post through request body. But debugging in my ModelBinder I noticied the bindingContext.ValueProvider.GetValue(...); is always empty.

What sould be implemented to ModelBinder receive in ValueProvider the BodyData ?

Notes: 

- I need use ComplexTypeModelBinder and I paste what I think is essential to get help, if need I can paste more code.

- I read [docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding)

- I asked in [StackOverflow](http://stackoverflow.com/questions/43924647/custom-modelbinder-using-method-post)

My Code:
```

public class GersinModelBinder : ComplexTypeModelBinder
    {
        private IDictionary<ModelMetadata, IModelBinder> _propertyBinders;

        public GersinModelBinder(IDictionary<ModelMetadata, IModelBinder> propertyBinders) : base(propertyBinders)
        {
            _propertyBinders = propertyBinders;
        }

        protected override object CreateModel(ModelBindingContext bindingContext)
        {
            var result = bindingContext.ValueProvider.GetValue("Id");

            if (result == null)
            {
                return null;
            }

            int id = 0;
            try 
            {
                id = int.Parse(result.FirstValue);
            }
            catch { }

            var type = bindingContext.ModelType;
           var model = ObjectCreator.GetById(type, id);
            return model;
        }
```
```

$http({
                url: url,
                method: 'POST',
                data: $scope.model
            }).then(function (response) {
                $scope.model = response.data;
            }, function (response) {
                $scope.model = response.data;
            }).finally(function () {

            });
```

**Comment by Eilon** [comment]
Instead of a custom model binder, use the `[FromBody]` attribute on the parameter of your action method:

```c#
public IActionResult PostJsonFormData([FromBody] MyJsonDataType data)
{
    // data will have the data that was posted in JSON format
}
```
