### ISSUE TITLE
Modelbinding FromRoute attribute parameter not resolved from routedata

### ISSUE THREAD

**Issue by PeterHagen** [aspnet/Mvc#6268]
I'm using a IRouteConstraint to create a route, which will add a complex object into the route data, when it has a hit. The matching action has a parameter that should contain this route data. I suspect that this argument requires the [FromRoute] attribute for the modelbinding to work, but it doesn't give the expected result.

Here is an example. The IRouteConstraint fetches some data from the database:
```
public class WoDContentAliasRoute : IRouteConstraint
    {
        public const string RouteMatchNode = "WoDContent";

        public bool Match(
            HttpContext httpContext,
            IRouter route, 
            string parameterName,
            RouteValueDictionary values, 
            RouteDirection routeDirection)
        {
            if (routeDirection != RouteDirection.IncomingRequest)
                return false;

            string url = values["url"] as string;
            if (string.IsNullOrEmpty(url))
                return false;

            ContentModel content = httpContext.RequestServices.GetService<CmsRequestContext>().WoDHelper().FindContentByAlias(url);
            if (content != null)
                values[RouteMatchNode] = content;

            return content != null;
        }
    }
```

The route is mapped like this in startup:
```
   routes.MapRoute(
                "wodcontent",
                "{url}",
                new { controller = "wod", action = "ContentPage" },
                new { node = new WoDContentAliasRoute() }
            );
```

And this works. The request ends up on the correct action:
```
        public IActionResult ContentPage([FromRoute] ContentModel WoDContent)
        {
            if (WoDContent == null)
                throw (new PageNotFoundException());
```
But, the WoDContent parameter is actually a new and empty object, while the RouteData.Values["WoDContent"] contains the correct object. This implementation did work on MVC 4 (without the FromRoute attribute). Is this a bug?

**Comment by Eilon** [comment]
This looks like it's a good scenario for writing a custom model binder. Using constraints to change incoming data is not recommended.

@rynowak - can you share a link w/ more info?

**Comment by rynowak** [comment]
Here's our doc on writing a custom model binder. If you need help, please open a new issue and explain what's not clear. Thanks!

https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding
