### ISSUE TITLE
Typo in an error message in resource file

### ISSUE THREAD

**Issue by mikebrind** [aspnet/Mvc#6269]
Not sure how or where else to report this kind of thing:  the phrase "can only" is duplicated in this error message here: https://github.com/aspnet/Mvc/blob/f568d3c2bca0f2a427fb1bafe327bcb5980d2906/src/Microsoft.AspNetCore.Mvc.Core/Resources.resx#L407

**Comment by rynowak** [comment]
This is the right place to report this kind of issue. Thanks!

**Comment by Eilon** [comment]
@rynowak - please reassign as necessary.

**Comment by rynowak** [comment]
This was fixed in https://github.com/aspnet/Mvc/commit/42b988ad888f285df6aa19e6f93abeb7d640abca
