### ISSUE TITLE
Identity Signout with v 2.0.0-preview1-final doesn't work right

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Mvc#6279]
_From @vRITHNER on May 16, 2017 11:31_

Hi, 

## Steps to reproduce
```
From VS2017 preview, create new dotnet web mvc -auth  Individual
F5 to Debug
From a created + logged account
Click Signout
```

## Expected  behavior
returnUrl  to Home/Index not signed

## Actual behavior
```
An unhandled exception occurred while processing the request.

NullReferenceException: Object reference not set to an instance of an object.
AspNetCore._Areas_IdentityService_Views_IdentityService_InvalidLogoutRedirect_cshtml+<ExecuteAsync>d__0.MoveNext() in InvalidLogoutRedirect.cshtml, line 7
AspNetCore._Areas_IdentityService_Views_IdentityService_InvalidLogoutRedirect_cshtml+<ExecuteAsync>d__0.MoveNext() in InvalidLogoutRedirect.cshtml
+
<p class="text-warning">@Model.ErrorDescription</p>
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
....
```

## Environment data
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16193
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

Txs
-Vince

_Copied from original issue: dotnet/cli#6609_

**Comment by Eilon** [comment]
This issue was moved to aspnet/Identity#1215
