### ISSUE TITLE
Identity Register/SignIn with v 2.0.0-preview1-final doesn't work right

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Mvc#6280]
_From @vRITHNER on May 16, 2017 11:42_

## Steps to reproduce

- From VS2017 preview, create new dotnet web mvc -auth  Individual
- F5 to Debug
- From SignIn page, register new Account
- Click Register

## Expected  behavior
Create account
Redirect to Home signed

## Actual behavior
```
An unhandled exception occurred while processing the request.

AggregateException: Unhandled remote failure. (Correlation failed.)
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__20.MoveNext()

Exception: Correlation failed.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__20.MoveNext()
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__20.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

Return url:
`http://localhost:5001/tfp/IdentityService/signinsignup/oauth2/v2.0/logout?post_logout_redirect_uri=urn%3Aself%3Aaspnet%3Aidentity%3Aintegrated&state=CfDJ8FtFvJqI8W1MkXfXi3JXTy9QL3XCUDgZpUn3J7YcCvNhYhHg9Rw0m7Tp0tJVCbgoHwL8FpLnkjaN7A8A7YXKUeObIn264d_EfmK2WlrDBWIUfhzV4MJAdvF1KcZbF67usZpRpTj6NtOUlwlc8tP4i5SIykDnKcJVriNuRR3cyy_oqBLsWDVUoR0aIdeTlP1WDw&x-client-SKU=ID_NET&x-client-ver=2.1.3.0`

## Environment data
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16193
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

```

Txs
-Vince

_Copied from original issue: dotnet/cli#6610_

**Comment by Eilon** [comment]
This issue was moved to aspnet/Identity#1214
