### ISSUE TITLE
Incorrect routing with `CreatedAtActionResult`

### ISSUE THREAD

**Issue by smudge202** [aspnet/Mvc#6284]
_Note: I believe this also applies to the `CreatedAtRouteResult` class._

## Steps to replicate issue

1. `dotnet new web`
1. `dotnet add package Microsoft.AspNetCore.Mvc.Core`
1. `dotnet add package Microsoft.AspNetCore.Mvc.Formatters.Json` to avoid the `System.InvalidOperationException: 'Microsoft.AspNetCore.Mvc.MvcOptions.InputFormatters' must not be empty. At least one 'Microsoft.AspNetCore.Mvc.Formatters.IInputFormatter' is required to bind from the body.` error
1. `dotnet restore`
1. Correct `Startup`:

```csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace Test
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
            => services.AddMvcCore().AddJsonFormatters();

        public void Configure(IApplicationBuilder app)
            => app.UseMvc();
    }
}
```

6. Add `TestController`:

```csharp
using Microsoft.AspNetCore.Mvc;

namespace Test
{
	[Route("test")]
	public class TestController
	{
		[HttpGet("{id:int}")]
		public IActionResult Get([FromRoute]int id) 
			=> new OkResult();

		[HttpPost]
		public IActionResult Create([FromBody]SomeModel model)
			=> new CreatedAtActionResult(nameof(Get), nameof(TestController), new { id = 1 }, null);
	}

	public class SomeModel { }
}
```

You can confirm the `Get` endpoint is reachable (as expected):

```curl
curl -i -X GET http://localhost:5000/test/1
```

![curl-get](https://cloud.githubusercontent.com/assets/2247869/26151955/e7c12f3e-3afc-11e7-8683-03c4ff603a61.png)

However, posting to the `Create` endpoint will fail:

```curl
curl -i -X POST http://localhost:5000/test -d "{}" -H "Content-Type: application/json"
```

## Expected

Location header set to `/test/1`

## Actual

```
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

## Notes

It's possible my expectations are incorrect. However, if you change the POCO controller to normal controller and change the create method to:

```csharp
[HttpPost]
public IActionResult Create([FromBody]SomeModel model)
	=> new CreatedResult(Url.Action(nameof(Get), new { id = 1}), null);
```

This will generate the correct URL for the `Get` method:

![curl-post](https://cloud.githubusercontent.com/assets/2247869/26152326/6ba4014a-3afe-11e7-9921-deeb33fceef5.png)

I didn't expect there to be a difference in routing between `Url.Action` and classes named `*Action`.

**Comment by rynowak** [comment]
None of the URL generation features in MVC support `nameof(TestController)`. `CreatedAtActionResult` and friends expect to see `Test` not `TestController`

**Comment by smudge202** [comment]
Thanks for the response, @rynowak . I'm not sure I agree with your statement because, as shown, `Url.Action` **does** work with `nameof(TestController)`. However, if I change the Create method as you've suggested:

```csharp
[HttpPost]
public IActionResult Create([FromBody]SomeModel model)
	=> new CreatedAtActionResult(nameof(Get), "Test", new { id = 1 }, null);
```

I still get inconsistent behaviour. The `CreatedAtAction` will set the location to an absolute path (preferable in my opinion), but the `Url.Action` returns a relative path. Is there a reason for this?

**Comment by rynowak** [comment]
> Url.Action does work with nameof(TestController). However, if I change the Create method as you've suggested

I can assure you this is not the case. CreatedAtActionResult calls `Url.Action` without making any changes to the `ControllerName` value. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/CreatedAtActionResult.cs#L79 We get feedback about developers wanting to use `nameof()` with our URL generation features all the time, it's not supported. 

> I still get inconsistent behaviour. The CreatedAtAction will set the location to an absolute path (preferable in my opinion), but the Url.Action returns a relative path. Is there a reason for this?

`Url.Action` generates absolute paths - OR fully-qualified URLs depending on which overload you use. Passing in a host/authority and a scheme will always generate a fully-qualified URL (See [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/CreatedAtActionResult.cs#L79 )). 

As far as why `CreatedAtActionResult` specifically generates a fully-qualified URL for the `Location` header, I don't recall the exact reason. I think we've always done it this way going back to old WebAPI. I speculate that the reason is because RFC2616 required fully-qualified URLs in the `Location` header, even though that spec is now kinda obsolete. We've never had a reason to reevaluate since then.

To me personally, the fully-qualified URL is less work for the client and therefore better.

**Comment by smudge202** [comment]
I'm not sure further discussion is going to yield anything useful to address the inconsistencies so I'll just close this.
