### ISSUE TITLE
Asp.NET Core MVC confusing View controller with Api controller

### ISSUE THREAD

**Issue by jonatanrinckus** [aspnet/Mvc#6297]
Example: https://github.com/jonatanrinckus/RouteMvcIssue

The issue:

When I have two controller, like this:

https://github.com/jonatanrinckus/RouteMvcIssue/blob/master/RouteIssue/Controllers/SomeController.cs

with the action:

```
public IActionResult Create()
	    {
		    return View();
	    }
```
and

https://github.com/jonatanrinckus/RouteMvcIssue/blob/master/RouteIssue/Controllers/Api/SomeController.cs

with the actions:

```
public IActionResult Get()
	    {
		    return Ok("Something");
	    }

		[HttpPost]
		public IActionResult Create(object something)
		{
			return Ok();
		}
```

in my view/layout:

https://github.com/jonatanrinckus/RouteMvcIssue/blob/master/RouteIssue/Views/Shared/_Layout.cshtml

 I have:

                    <li><a asp-area="" asp-controller="Some" asp-action="Create">Some</a></li>

**or**

                    <li>@Html.ActionLink("Some Action Link", "Create", "Some")</li>

the result are: 

                    <li><a href="/Api/Some">Some</a></li>
                    <li><a href="/Api/Some">Some Action Link</a></li>

How you can see, the href is calling the Api, not the View, it happen when I have two actions with the same name, like the create action, but one is a HttpGet on the view controller and the other is a HttpPost on the api, and if I click on the link, it call the Get action on Api controller.

**Comment by rynowak** [comment]
URL generation in MVC is based on controller/action names, so if the names are the same then the attribute routed action is consider first, which is the result that you found.

A few suggestions for how you can solve your issue, pick whichever you like:
1. Give the controllers different names 
2. Use [areas](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing#areas) - if you put your API controllers in an area then you won't accidentally link to them, you will have to specify the area if you want to link to an API controller
3. Used named routes

**Comment by jonatanrinckus** [comment]
Great, using [areas](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing#areas) solve the issue and I guess is the best way.

But I think it is a bug. Why? Because the Create action on the Api controller is a Post method and not a Get method and on a Action Link or 'a' tag helper, I just can use Get Methods. Do you agree?

**Comment by jonatanrinckus** [comment]
Again, areas do not work.

If I use area, I need to specify de name of the Action, like: /api/some/get and it is not correct.

I try to add [Route("")] to the action, but it stop to work, can't get the action with /api/some/get or /api/some/ 

If I put my MapRoute like this:

```
routes.MapAreaRoute(
					name: "Api",
					areaName: "Api",
		            template: "Api/{controller}/{action?}/{id?}");
```

And a [ActionName("")], then I can acesss on /api/some/
But if I need to access with some parameter, like api/some/1 to the action:

```
public IActionResult Get(int id)
		{
			return Ok("Something" + id);
		}
```

Using [ActionName("{id}")] or [Route("{id}")], don't work.

So, how I will do a right Api, if the routes do not work?

**Comment by rynowak** [comment]
Sorry, I should have explained a bit more. You don't need to define a new conventional route for your API controllers.

Just add `[Area("API")]` to them.

**Comment by jonatanrinckus** [comment]
Ow, thanks, I was following the link.

Know it work correct.
