### ISSUE TITLE
Razor codegen for MVC doesn't sanitize keywords in class/namespace names

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6298]
The new `@namespace` directive makes it easily possible to end up with a reserved word in the class name or namespace name.

Consider the default template, and a page like:
`/Pages/registraton/class/edit.cshtml`

You'll get a generated namespace like `MyApp.registration.class` which is invalid.

**Comment by rynowak** [comment]
Razor has a list of C# keywords, let's use this to sanitize this name. Note that the code for this is in Razor.

**Comment by mkArtakMSFT** [comment]
We're mangling the generated class names now, which makes this not an issue.
