### ISSUE TITLE
All view names are case sensitive after precompiling

### ISSUE THREAD

**Issue by nickalbrecht** [aspnet/Mvc#6299]
**Issue:** It appears that once you precompile the views, all view name resolution inherits a forced case sensitivity.

**Description:** There's an inconsistency in view name resolution when letting views be compile at runtime (default) and precompiling them as part of publishing. I've tested it for both normal action views, and component views. I've also tested letting MVC determine the view name from the action, and manually specifying it as a parameter to the View() method at the end of the Action, or a Component's Invoke(). All in all, it's a pretty poor experience that by trying to gain some performance with precompiling your application, you can actually break it.

**Expected:** Ideally, the name resolution would be consistent between the two options

**Reproduce:** This is fairly easy to reproduce, and you should be able to see the same behavior simply by creating a new MVC application from the starting template, change the case of a view or two, and publish with the precompiled views step added.

**Packages referenced in my tests**
Microsoft.AspNetCore 1.1.2
Microsoft.AspNetCore.Mvc 1.1.3
Microsoft.AspNetCore.Mvc.Razor.ViewCompilation 1.1.1

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/MvcPrecompilation/issues/37
