### ISSUE TITLE
Try to eliminate service locator in AuthorizeFilter

### ISSUE THREAD

**Issue by HaoK** [aspnet/Mvc#6300]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L156

For context: https://github.com/aspnet/Mvc/pull/6288#discussion_r117570378

**Comment by Eilon** [comment]
@rynowak - thoughts on the priority of this? Seems like nice cleanup, but not high-pri, so perhaps close?

**Comment by rynowak** [comment]
sure
