### ISSUE TITLE
GetDisplayUrl (and PathBase) showing rewritten URL instead of Request URL

### ISSUE THREAD

**Issue by DaveSlinn** [aspnet/Mvc#6301]
When using IIS to perform a URL rewrite, is PathBase or GetDisplayUrl supposed to reflect the original Request, or the rewritten one?

I am using IIS URL rewrite to remove a segment of the path (i.e. remove '/shared/'), so instead of the user seeing "https://test.gms.ca/test01/api/shared/test", I want them to see "[https://test.gms.ca/test01/api/test](https://test.gms.ca/test01/api/test)".

I have the rule setup in IIS and all seems well.  The request is rewritten with an inbound rule and the controllers are responding.  However, within the controller, I am using GetDisplayUrl thinking that would give me the original request, not the actual one where the application is hosted within IIS.

I have a test controller returning the request headers and some values off the HttpRequest object from within the controller.  As you can see, PathBase is always showing the actual hosted path and GetDisplayUrl is merely reflecting that portion.  I thought GetDisplayUrl is a method to get the same URL that the user is seeing.  Am I misunderstanding what GetDisplayUrl is for?

I was thinking maybe I had to also use the ASP.NET Core Rewrite middleware to rewrite the url, but I'm not 100% sure I am doing it right.  This is what I have:
```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IServiceProvider serviceProvider)
        {
            var options = new RewriteOptions()
                .AddRewrite(@"(\d+)/api/shared/(\d+)", "$1/api/$2", false);

            app.UseRewriter(options);

            app.ConfigureCommonSettings(env, loggerFactory, Configuration, serviceProvider);
        }
```

**Comment by Eilon** [comment]
@Tratcher / @mikaelm12 - any idea where this bug should go? HttpAbstractions or BasicMiddleware?

**Comment by Tratcher** [comment]
By design. 
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/UriHelper.cs
Display refers to the escaping state, as compared to GetEncodedUrl. 
@mikalem12, does rewrite stash the original values anywhere?

**Comment by Eilon** [comment]
cc @mikaelm12 w/ proper spelling 😄

**Comment by mikaelm12** [comment]
> does rewrite stash the original values anywhere?

No. There are server variables for that but we don't support them atm
They are

> HTTP_X_ORIGINAL_URL – this server variable contains the original URL in decoded format;
> UNENCODED_URL – this server variable contains the original URL exactly as it was requested by a Web client, with all original encoding preserved

There was a discussion on it a while ago here https://github.com/aspnet/BasicMiddleware/issues/151

**Comment by DaveSlinn** [comment]
Is using the Rewrite middleware an option to override the PathBase value?

Perhaps I'm going about this the wrong way.  I have 4 separate API projects, 1 that consists of general functions, the other 3 separated by their domain concerns.  I want the URL for the common functions to appear at the top of the url and the domain specific ones to be lower, as in:

Given a Clients, Address and Countries controller in the general library (called common), I want those URLs to be:

https://api.domain.com/clients/12345
https://api.domain.com/addresses/12
https://api.domain.com/countries/12

And then I have several controllers related to administration tasks (called admin).  I want those URLs to be:

https://api.domain.com/admin/policies/123456
https://api.domain.com/admin/applications/123456
https://api.domain.com/admin/quotes/123456

I tried hosting my projects in IIS with a structure that matched this hierarchy:

api.domain.com
  common.dll
  /admin/admin.dll

but I couldn't get this to work and assumed it was because the top level project (common.dll) was intercepting all requests including ones with admin in their URL and then trying to find a controller called "admin", which doesn't exist in that project, and returning a 404.  The admin project (admin.dll) in a sub folder under common would then never see the request.

To work around this, I thought I would attempt to use URL rewrite, so that the projects would be hosted in side-by-side on IIS:

api.domain.dom
  /common/common.dll
  /admin/admin.dll

essentially I have the top level projects in a subfolder called common and then use URL rewrite to remove /common/ from the URL, but this is causing some other issues, such as when my code relies on GetDisplayUrl to build a URL for the response, it is not reflecting the rewritten URL, and I am also using Swashbuckle to create a Swagger UI, which also seems to reflect the actual hosted URL and not the rewritten one.

**Comment by Eilon** [comment]
This issue was moved to aspnet/HttpAbstractions#855
