### ISSUE TITLE
Singleton DefaultContractResolver for JsonSerializerSettingsProvider.CreateSerializerSettings

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Mvc#6303]
Today each call to `JsonSerializerSettingsProvider.CreateSerializerSettings()` will return a new settings instance with a new `DefaultContractResolver` instance.

https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonSerializerSettingsProvider.cs

It would be better for performance and memory usage if there was a static singleton `DefaultContractResolver` and the new settings returned from CreateSerializerSettings returned that singleton. Slow reflection logic is cached by the resolver and sharing it means it will be cached once

e.g.

    public static class JsonSerializerSettingsProvider
    {
        private const int DefaultMaxDepth = 32;

        // return shared resolver by default for perf so slow reflection logic is cached once
        // developers can set their own resolver after the settings are returned if desired
        private static readonly DefaultContractResolver SharedResolver = new DefaultContractResolver
        {
            NamingStrategy = new CamelCaseNamingStrategy(),
        };

        /// <summary>
        /// Creates default <see cref="JsonSerializerSettings"/>.
        /// </summary>
        /// <returns>Default <see cref="JsonSerializerSettings"/>.</returns>
        public static JsonSerializerSettings CreateSerializerSettings()
        {
            return new JsonSerializerSettings
            {
                ContractResolver = SharedResolver,

                MissingMemberHandling = MissingMemberHandling.Ignore,

                // Limit the object graph we'll consume to a fixed depth. This prevents stackoverflow exceptions
                // from deserialization errors that might occur from deeply nested objects.
                MaxDepth = DefaultMaxDepth,

                // Do not change this setting
                // Setting this to None prevents Json.NET from loading malicious, unsafe, or security-sensitive types
                TypeNameHandling = TypeNameHandling.None,
            };
        }
    }

**Comment by davidfowl** [comment]
Why does this need to be baked in? Why not just cache a static in your application?

**Comment by JamesNK** [comment]
Because I noticed that it was being recommended to devs to use that call when creating serializer settings for use with ASP.NET Core

https://github.com/aspnet/Mvc/issues/4562#issuecomment-226190759

**Comment by davidfowl** [comment]
@JamesNK is the CamelCaseNamingStrategy immutable?

**Comment by JamesNK** [comment]
No, and neither is DefaultContractResolver but the type exposed by JsonSerializerSettings is IContractResolver which just has a single method on it.

To get into trouble with modifying them a dev would need to actively cast the IContractResolver to DefaultContractResolver and then start fiddling with properties.

If they wanted to change the resolver on the settings it is much easier for them to just assign a new one, i.e.

```
var settings = JsonSerializerSettingsProvider.CreateSerializerSettings();
settings.ContractResolver = new DefaultContractResovler
{
    NamingStrategy = new SnakeCaseNamingStrategy()
};
```

**Comment by davidfowl** [comment]
> No, and neither is DefaultContractResolver but the type exposed by JsonSerializerSettings is IContractResolver which just has a single method on it.

Right, I'm not a fan of this... We could just recommend they do the right thing and store a static that they own. It also won't suddenly start affecting every where that calls this (if they did modify the value).

**Comment by JamesNK** [comment]
People want to call `JsonSerializerSettingsProvider.CreateSerializerSettings()` multiple times because they want to have different settings for `JsonInputFormatter` and `JsonOutputFormatter`.

The perf hit of using a new contract resolver isn't insignificant - https://aspnetwebstack.codeplex.com/workitem/2092

**Comment by Eilon** [comment]
We merged https://github.com/aspnet/Mvc/pull/6363. Thanks!
