### ISSUE TITLE
Best way to solver this implemetation return RederectToAction or return View

### ISSUE THREAD

**Issue by allannrodrigues** [aspnet/Mvc#6304]
I have this scenario.
One action that return a list and anothers two action, the first return a new form, and that form has a submit that return the action list. I make get and post via ajax.

I want know if my implemetantion is corect or I have use "RedirectToAction" in my SaveForm action result.

Can you explain me?
```
//Code
[HttpGet]
public IActionResult List()
{
//Logic

return View();
}

[HttpGet]
public IActionResult NewForm()
{
//Logic
return View();
}

[HttpPost]
public IActionResult SaveForm()
{
//Logic

return List();
}
```

**Comment by rynowak** [comment]
You should redirect from your `SaveForm` action. The reason to do this is to prevent duplicate form submissions. Browsers will handle this better. 

https://en.wikipedia.org/wiki/Post/Redirect/Get
