### ISSUE TITLE
SignInManager.GetExternalLoginInfoAsync returns null only on ExternalLoginConfirmation

### ISSUE THREAD

**Issue by JoshClose** [aspnet/Mvc#6305]
When getting the callback to `/Account/ExternalLoginCallback` the call to `SignInManager.GetExternalLoginInfoAsync` returns info just fine. The user then registers and the callback to `/Account/ExternalLoginConfirmation` is called and `SignInManagerGetExternalLoginInfoAsync` now returns `null`. The data isn't staying around for some reason.

If I look at requests through Fiddler, I can see in the call to `/Account/ExternalLoginCallback` that there is a cookie named `Identity.External`. When calling `/Account/ExternalLoginConfirmation`, that cookie is no longer there. I think this is the problem, but I have no clue why. In between these two calls there is a call for the `/favicon.ico` file that returns a `302` causing a call to `/Account/Login?ReturnUrl=%2Ffavicon.ico`. Both those calls still have the `Identity.External` cookie showing.

I have another project where I'm doing the same thing and it works fine, so I don't know what's causing the issue here. It's happening locally in IIS Express and on Azure. The issue is happening in Chrome but works in Edge.

Here is those methods. I have made some changes from the default.

```cs
[HttpGet]
[AllowAnonymous]
public async Task<IActionResult> ExternalLoginCallback( string returnUrl = null, string remoteError = null )
{
	if( remoteError != null )
	{
		ModelState.AddModelError( string.Empty, $"Error from external provider: {remoteError}" );
		return View( nameof( Login ) );
	}
	var info = await signInManager.GetExternalLoginInfoAsync();
	if( info == null )
	{
		return RedirectToAction( nameof( Login ) );
	}

	// Sign in the user with this external login provider if the user already has a login.
	var result = await signInManager.ExternalLoginSignInAsync( info.LoginProvider, info.ProviderKey, isPersistent: false );
	if( result.Succeeded )
	{
		logger.LogInformation( 5, "User logged in with {Name} provider.", info.LoginProvider );
		return RedirectToLocal( returnUrl );
	}

	if( result.RequiresTwoFactor )
	{
		return RedirectToAction( nameof( SendCode ), new { ReturnUrl = returnUrl } );
	}

	if( result.IsLockedOut )
	{
		return View( "Lockout" );
	}

	// If the user aleady has an account with any other provider, log them in.
	if( await LoginIfExternalProviderAlreadyAssignedAsync() )
	{
		return RedirectToLocal( returnUrl );
	}

	// If the user does not have an account, then ask the user to create an account.
	ViewData["ReturnUrl"] = returnUrl;
	ViewData["LoginProvider"] = info.LoginProvider;
	var email = info.Principal.FindFirstValue( ClaimTypes.Email );
	ViewBag.Stores = db.Stores.OrderBy( s => s.Name ).Select( s => new SelectListItem { Text = s.Name, Value = s.Id.ToString() } );

	return View( "ExternalLoginConfirmation", new ExternalLoginConfirmationViewModel { Email = email } );
}

[HttpPost]
[AllowAnonymous]
[ValidateAntiForgeryToken]
public async Task<IActionResult> ExternalLoginConfirmation( ExternalLoginConfirmationViewModel model, string returnUrl = null )
{
	if( ModelState.IsValid )
	{
		// If the user aleady has an account with any other provider, log them in.
		if( await LoginIfExternalProviderAlreadyAssignedAsync( model.Email ) )
		{
			return RedirectToLocal( returnUrl );
		}

		// Get the information about the user from the external login provider
		var info = await signInManager.GetExternalLoginInfoAsync();
		if( info == null )
		{
			return View( "ExternalLoginFailure" );
		}
		var user = new User
		{
			UserName = model.Email,
			Email = model.Email,
			FirstName = model.FirstName,
			LastName = model.LastName,
			StoreId = model.StoreId.Value
		};
		var result = await userManager.CreateAsync( user );
		if( result.Succeeded )
		{
			result = await userManager.AddLoginAsync( user, info );
			if( result.Succeeded )
			{
				await signInManager.SignInAsync( user, isPersistent: false );
				logger.LogInformation( 6, "User created an account using {Name} provider.", info.LoginProvider );
				return RedirectToLocal( returnUrl );
			}
		}
		AddErrors( result );
	}

	ViewBag.Stores = db.Stores.OrderBy( s => s.Name ).Select( s => new SelectListItem { Text = s.Name, Value = s.Id.ToString() } );

	ViewData["ReturnUrl"] = returnUrl;
	return View( model );
}

private async Task<bool> LoginIfExternalProviderAlreadyAssignedAsync( string email = null )
{
	var info = await signInManager.GetExternalLoginInfoAsync();
	if( info == null )
	{
		return false;
	}

	email = email ?? info.Principal.FindFirstValue( ClaimTypes.Email );
	if( email == null )
	{
		return false;
	}

	var user = await userManager.FindByEmailAsync( email );
	if( user == null )
	{
		return false;
	}

	var result = await userManager.AddLoginAsync( user, info );
	if( result.Succeeded )
	{
		await signInManager.SignInAsync( user, isPersistent: false );
		return true;
	}

	return false;
}

```

I can provide Fiddler logs also if needed.

**Comment by HaoK** [comment]
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L693

ExternalLoginSignInAsync will clear the external cookie if its successful

**Comment by JoshClose** [comment]
In my case, it's not successful. The `ExternalLoginConfirmation` page is shown. When this form is submitted, the cookie isn't there.

**Comment by JoshClose** [comment]
There is a request for a `favicon.ico` file that doesn't exist and it gets redirected to `/Account/Login?ReturnUrl=%2Ffavicon.ico`. The login action has this code in it

```
// Clear the existing external cookie to ensure a clean login process
await HttpContext.Authentication.SignOutAsync( externalCookieScheme );
```

I'm guessing that is what is causing the cookie to go away. 

I added a `favicon.ico` file and this issue goes away. Apparently it's a chrome issue with constantly requesting a favicon.

Why is IIS/ASP.NET redirecting to a login page for a file that doesn't exist? My default route goes to `/Home/Index` which has an `[Authorize]` attribute on it. It's not seeing the request for an `.ico` file as a static file request. Is there a config I need to do for it to be viewed as a static file in IIS or do I need to somehow ignore that route in my route config?

My routes currently look like this.

```
app.UseMvc( routes =>
{
	routes.MapRoute(
		name: "areas",
		template: "{area:exists}/{controller=Home}/{action=Index}/{id?}" );
	
	routes.MapRoute(
		name: "default",
		template: "{controller=Home}/{action=Index}/{id?}" );

	routes.MapRoute(
		name: "react",
		template: "{*url}",
		defaults: new { controller = "Home", action = "Index" } );
} );
```

**Comment by Tratcher** [comment]
The static file middleware does not send 404s, it handles the request for files it can find and otherwise calls the next middleware. This avoids false negatives and allows you to chain together multiple components that may use similar urls. It's only if something reaches the end of the pipeline without being handled that a 404 is sent. It looks like your MVC routes are picking up all requests not already handled so it never reaches the end of the pipeline.

**Comment by JoshClose** [comment]
Do you have a suggestion on a better way to do my `react` route? What I need is any url to go to `/Home/Index` because the client is rendering everything.

**Comment by rynowak** [comment]
@SteveSandersonMS - would the javascript services routing support help here?

> Do you have a suggestion on a better way to do my react route? What I need is any url to go to /Home/Index because the client is rendering everything.

**Comment by SteveSandersonMS** [comment]
Yes, `MapSpaFallbackRoute` covers that exact scenario. Details: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#routing-helper-mapspafallbackroute

**Comment by JoshClose** [comment]
Nice! Thanks!
