### ISSUE TITLE
[IgnoreAntiforgeryToken] not working for version 1.0.4

### ISSUE THREAD

**Issue by code-mogwai** [aspnet/Mvc#6306]
Steps to repro.

Add the following in Startup.cs.
```
options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
```

Add this attribute to a POST action.
```
[IgnoreAntiforgeryToken]
```

Post to this action without any `__RequestVerificationToken` form fields.

Expected result: No attempt at validation. No Antiforgery errors.

Actual result:
```
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter[1]
      Antiforgery token validation failed. The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
```

**Comment by code-mogwai** [comment]
Version 1.0.4 recommended in following Security Advisory but IgnoreAntiforgeryToken not working in this version as far as i can see. https://github.com/dotnet/corefx/issues/19535

**Comment by rynowak** [comment]
Yep, it looks like this is an issue. If you want to work around the problem yourself you can do this by setting an order on `IgnoreAntiforgeryTokenAttribute` like this:
```
[IgnoreAntiforgeryToken(Order = 1000)]
```

The value 1000 should be used to match the value that's on `AutoValidateAntiforgeryToken`

The problem here is that https://github.com/aspnet/Mvc/commit/bd9e43187310c2da9ddc3569c92539a263a970d5 didn't get merged to rel/1.0.4.

**Comment by code-mogwai** [comment]
Thanks for the work around. Does the job nicely.

**Comment by Eilon** [comment]
This patch is *approved* for 1.0.x. Please follow the patch creation instructions that were sent by email, and submit a PR to the correct branch.

**Comment by rynowak** [comment]
30a178c
