### ISSUE TITLE
Can't debug into @functions code

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#6311]
I am unable to debug into my `@functions` code in my razor page:

![image](https://cloud.githubusercontent.com/assets/1874516/26332338/1db0a0ea-3f24-11e7-85df-60db817086ec.png)

This is with VS2017 Update3 preview1

**Comment by NTaylorMullen** [comment]
Was able to reproduce this as well.

**Comment by DamianEdwards** [comment]
@NTaylorMullen can you take a look at this one please? Balance as necessary, but we'll need to figure this out of course.

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Razor#1387
