### ISSUE TITLE
Validation not run on model bound properties

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#6312]
With this page:

```html
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Mvc.RazorPages
@using System.ComponentModel.DataAnnotations

@functions {
    [BindProperty]
    [Required]
    public string Name { get; set; }

    [BindProperty]
    [Required]
    public string Email { get; set; }

    [TempData]
    public string Message { get; set; }

    public async Task<IActionResult> OnPost()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        Message = $"Thanks {Name}, we'll be in touch via {Email}!";
        return RedirectToPage("/Index");
    }
}

<html>
<body>
    <form method="post">
        <p>Please enter your contact info to hear about our fine products!</p>
        <div>
            <label asp-for="Name"></label>
            <input asp-for="Name" />
        </div>
        <div>
            <label asp-for="Email"></label>
            <input asp-for="Email" />
        </div>
        <button>Submit</button>
    </form>
</body>
</html>
```

If I post this request:

```
Name=Dan
&Email=
&__RequestVerificationToken=CfDJ8E2v2hm6429NjsEkzazgoyxyYVouQLUH1OTcWGTB-RXqV8Fvo3TK7GrmeWkP0rlxi-8gEZMvdb_sOR7-IuY0cHuCf3le2OMz9eJQlNeMadEE8QkgyHnaiLeqHtlTFc2Bg6nIq1BSiqNokR5JQ7XmxVE
```

I see `ModelState.IsValue` is `true` in my OnPost handler. I expect it to be `false` because the Email is required, but was not specified.

**Comment by rynowak** [comment]
Email has thethe value ` ` (space). `[Required]` means non-null.

**Comment by rynowak** [comment]
@dougbu - you are more familar with data annotations than I ? Do we automatically convert whitespace to null?

**Comment by danroth27** [comment]
I just checked and the Email property is actually null:

```c#
@functions {
    [BindProperty]
    [Required]
    public string Name { get; set; }

    [BindProperty]
    [Required]
    public string Email { get; set; }

    [TempData]
    public string Message { get; set; }

    public async Task<IActionResult> OnPost()
    {
        Console.WriteLine($"Is Email null = {Email==null}");
        Console.WriteLine($"ModelState.IsValid={ModelState.IsValid}");
```

Output:
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/Contact application/x-www-form-urlencoded 198
Is Email null = True
ModelState.IsValid=True
```
Is Email null = True
ModelState.IsValid=True
```

**Comment by rynowak** [comment]
Ugh, total brain fart on my part, yeah we don't have support for attributes on page properties

**Comment by dougbu** [comment]
> Do we automatically convert whitespace to `null`?

And, BTW, yes we do by default convert whitespace to `null`. Have a look at `DisplayMetadata.ConvertEmptyStringToNull` and its uses.

**Comment by DamianEdwards** [comment]
@danroth27 you use Pages all weird-like 😕 

But it's good, I would never have thought to do that 😃 Incidentally it doesn't work on `PageModel` either.

@rynowak what are your thoughts around the implications of trying to support this?

**Comment by rynowak** [comment]
> what are your thoughts around the implications of trying to support this?

We should do it in 2.1.0 along with `ValueTupleModelBinder`.

Validation attributes on parameters or controller/page/pagemodel properties are the obvious thing for someone who's never used the framework before.

**Comment by danroth27** [comment]
Sorry, not trying to be weird 😝 

Some reasons I thought it made sense to do this:
- I was trying to avoid creating additional files to keep things as simple as possible
- With MVC view you drive things like form creation based on the model, and you specify the model using `@model`. The properties on the model are used for validation on the client, right? For pages, the page class itself *is* the page model by default. It's already a class, so I assumed creating another class wasn't necessary and that that properties on my page model would get validated.
- Similar idea with page models defined as a separate class, where you point to the page model using `@model`. With MVC views the properties of the thing I point to with `@model` get validated.

Not sure if that helps, but that's where I was coming from.

**Comment by rynowak** [comment]
Closing this issue in favor of #4603 - which has a clearer description of what needs to change 😆 We still plan to address this in 2.1, I'm just choosing this one as the duplicate.

**Comment by DarrenKantar** [comment]
I found that it is working in 2.1 for [Required] but not [Compare] which gives a "Could not find a property named Winner." error message.

When I tried extending the CompareAttribute to see what's going on it seems as if the ValidationContext is a String not the PageModel so validationContext.ObjectType.GetProperty(OtherProperty) returns null.
