### ISSUE TITLE
Add support for friendly routes in pages

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#6325]
From https://github.com/aspnet/Mvc/issues/5353

Associated with each page is an application model type similar to `ControllerModel`. We'd build on top of this to provide simple runtime configuration of routes. For instance, to configure an additional route to the `/Catalog/Books.cshtml`, here's what the Startup code might look like:

```
services
    .AddMvc()
    .AddRazorPages(options =>
    {
        options.MapPageRoute("Books/{id?}", "/Catalog/Books.cshtml");
    });
```

**Comment by pranavkm** [comment]
@DamianEdwards are you ok inverting the order of parameters or would you rather keep it to mirror System.Web?

**Comment by DamianEdwards** [comment]
@pranavkm whatever order makes the most sense in the scope of ASP.NET Core MVC, nothing else.

**Comment by pranavkm** [comment]
Great. We'll also call this method `AddPageRoute` since it makes it clear that it's additive and does not replace existing routes.

**Comment by pranavkm** [comment]
FYI @mikebrind
