### ISSUE TITLE
Testing all controllers dependency injection

### ISSUE THREAD

**Issue by xaviergxf** [aspnet/Mvc#6339]
I'm writing integration tests for my application and i would like to know how to test if i correctly registered all of my dependencies on startup. How can i instantiate all controllers using a testserver and look for exceptions?

**Comment by rynowak** [comment]
There's no real substitute for sending a request to each controller. Controllers/DI can use scoped services -
 which are scoped to a request. That means that trying to instantiate the controller outside of the context of a request wouldn't be valid.

If you don't care more about determining *what* is in your application, then look at `IActionDescriptorCollectionProvider`.

**Comment by xaviergxf** [comment]
Thansk Rynowak,
   Here's the test method source code if anyone wants to do the same.

`[Fact]
        public async Task ControllersDependencyInjection()
        {
            var provider = _server.Host.Services.GetRequiredService<IActionDescriptorCollectionProvider>();
            var controllers = provider.ActionDescriptors.Items
                    .Where(x => (x as ControllerActionDescriptor)
                    .ControllerTypeInfo.AsType().IsSubclassOf(typeof(BaseController)))
                    .OfType<ControllerActionDescriptor>()
                    .Select(s=>s.ControllerName).Distinct()
                    .ToList();
            foreach (var controllerName in controllers)
            {
                var response = await _client.GetAsync($"/api/{controllerName}/{nameof(BaseController.Test)}");
                var responseContent = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                Assert.True(response.IsSuccessStatusCode, responseContent);
            }
        }`

**Comment by xaviergxf** [comment]
Thansk Rynowak,
   Here's the test method source code if anyone wants to do the same.

`[Fact]
        public async Task ControllersDependencyInjection()
        {
            var provider = _server.Host.Services.GetRequiredService<IActionDescriptorCollectionProvider>();
            var controllers = provider.ActionDescriptors.Items
                    .Where(x => (x as ControllerActionDescriptor)
                    .ControllerTypeInfo.AsType().IsSubclassOf(typeof(BaseController)))
                    .OfType<ControllerActionDescriptor>()
                    .Select(s=>s.ControllerName).Distinct()
                    .ToList();
            foreach (var controllerName in controllers)
            {
                var response = await _client.GetAsync($"/api/{controllerName}/{nameof(BaseController.Test)}");
                var responseContent = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                Assert.True(response.IsSuccessStatusCode, responseContent);
            }
        }`

**Comment by xaviergxf** [comment]
Thansk Rynowak,
   Here's the test method source code if anyone wants to do the same.

`
[Fact]
        public async Task ControllersDependencyInjection()
        {
            var provider = _server.Host.Services.GetRequiredService<IActionDescriptorCollectionProvider>();
            var controllers = provider.ActionDescriptors.Items
                    .Where(x => (x as ControllerActionDescriptor)
                    .ControllerTypeInfo.AsType().IsSubclassOf(typeof(BaseController)))
                    .OfType<ControllerActionDescriptor>()
                    .Select(s=>s.ControllerName).Distinct()
                    .ToList();
            foreach (var controllerName in controllers)
            {
                var response = await _client.GetAsync($"/api/{controllerName}/{nameof(BaseController.Test)}");
                var responseContent = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
                Assert.True(response.IsSuccessStatusCode, responseContent);
            }
        }
`

**Comment by rynowak** [comment]
Thanks. I'm going to close this issue since this was answered. Let us know if you need anything else.
