### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Internal.ActionSelector.SelectBestActions method should add the RouteContext parameter

### ISSUE THREAD

**Issue by karelz** [aspnet/Mvc#6342]
_From @cnxiaoby on May 31, 2017 10:24_

SelectBestActions 没有当前的 RouteContext 辅助信息，怎么 Returns the set of best matching actions ？？

_Copied from original issue: dotnet/core#668_

**Comment by karelz** [comment]
@cnxiaoby I don't understand your question. Are the special symbols in another non-English language? If yes, can you please translate the text to English?

**Comment by karelz** [comment]
_From @cnxiaoby on May 31, 2017 10:33_

I think that in the future version, you should add the RouteContext parameter to the SelectBestActions virtual method. When some guy override the SelectBestActions method, some information in RouteContext will help us do some business logic judgments.

**Comment by rynowak** [comment]
If you need the route data it's available through the `IRoutingFeature` in `HttpContext.Features.

Is there something else you need?

**Comment by cnxiaoby** [comment]
@rynowak else I need HttpRequest data, how can I get its? I still think that SelectBestActions with the RouteContext parameter is Context logical

**Comment by rynowak** [comment]
Oh I see, it's `SelectBestActions` - yeah we need to change this.

**Comment by Eilon** [comment]
We're out of time to do a breaking change for 2.0.0, so for 2.1.0 we could add a new method that has more parameters w/ the right data.

**Comment by mkArtakMSFT** [comment]
@rynowak, I've moved this to the `2.2.0-preview1` milestone assuming it's not a breaking change. If it is, can you please update the milestone as necessary. Thanks!

**Comment by mkArtakMSFT** [comment]
Seems related: https://github.com/aspnet/Mvc/issues/6413

**Comment by pranavkm** [comment]
The type is in the `internal` namespace and we might make it real `internal` in the future. I don't think making it easier for overriding in user scenarios is super pertinent. The recommended solution here should be to copy the code in to your app at which point you may pass whatever parameters that you need do.

**Comment by pranavkm** [comment]
See previous comment.
