### ISSUE TITLE
RenderSection is rendering incorrectly inside tag attribute

### ISSUE THREAD

**Issue by CoderProject** [aspnet/Mvc#6343]
To reproduce the issue write the RenderSection inside a tag attribute in your Layout in Shared folder:
Exp: `<body class="@RenderSection("cls",false)">`

Set the section content in a view:
`@section cls{login}`

The result is rendered as following:
`<bodylogin class>`

**Comment by Eilon** [comment]
@NTaylorMullen / @rynowak / @pranavkm - this looks pretty weird. Assigning to @NTaylorMullen to investigate.

**Comment by NTaylorMullen** [comment]
This is a duplicate of: https://github.com/aspnet/Razor/issues/677

**Comment by Eilon** [comment]
Indeed it is, and we have decided not to fix it. The linked bug has suggested alternatives.
