### ISSUE TITLE
When creating a custom ValidationAttribute, the ValidationContext always don't have a valid ServiceContainer

### ISSUE THREAD

**Issue by jlVidal** [aspnet/Mvc#6346]
Following this article: https://andrewlock.net/injecting-services-into-validationattributes-in-asp-net-core/

When creating custom `ValidationAttribute` several people already note that is impossible to access/get any service from the `GetService` method inside the `ValidationContext` class,  ServiceContainer property. Looking into the code is possible to see:

```
            var context = new ValidationContext(
                instance: container ?? validationContext.Model,
                serviceProvider: validationContext.ActionContext?.HttpContext?.RequestServices,
                items: null)
            {
                DisplayName = metadata.GetDisplayName(),
                MemberName = memberName
            };
```
https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/DataAnnotationsModelValidator.cs

Since the ActionContext was obsolete: https://stackoverflow.com/questions/37286530/actioncontext-gone-in-microsoft-aspnetcore-mvc-controller  - The service provider for a validation attribute is always null or empty. Let's make the `ValidationAttribute` great again, please fix this issue in the next patch.

**Comment by rynowak** [comment]
Are you saying that https://github.com/aspnet/Mvc/commit/328f4d648b8d921d2e9e9e3849d8afa88d56694b does not fix this issue?

It's certainly our intent that `ValidationContext` has the right service provider.

**Comment by jlVidal** [comment]
To be confirmed... Since I'm compiling against NET452  I can't test in the newer/beta version (2.0.0-preview1)  If fixed, I believe that should be explicit mentioned in the [release notes](https://github.com/aspnet/Mvc/releases/tag/rel/2.0.0-preview1) 

@rynowak thanks for the follow up anyway

**Comment by rynowak** [comment]
@jlVidal - 328f4d6 dates all the way back to 1.0.0-rc2 so I expect this to be working in whatever release you are using.

Can you please clarify for me... is this working for you or not?

**Comment by jlVidal** [comment]
It's working in new/blank project, I'm still trying to figure out why my specific solution doesn't load it correctly, and I can't request any services (always returns null)

**Comment by rynowak** [comment]
https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.validationcontext.servicecontainer(v=vs.110).aspx#Anchor_1

Yeah that's a bit of a bizzare property. I guess it's intended for you to be able to share state? Since service provider is read-only but service container is r/w.

Ok, going to close this since there's no actual ASP.NET problem. Glad you got it figured out.
