### ISSUE TITLE
The data protection operation was unsuccessful. MVC 5.0 NOT AZURE

### ISSUE THREAD

**Issue by vartig** [aspnet/Mvc#6353]
Im using ASP.NET Identity for my  user management and everything is ok in my localhost but when Im publishing and running on my website (NO AZURE) Im getting this error:

> The data protection operation was unsuccessful. This may have been caused by not having the user profile loaded for the current thread's user context, which may be the case when the thread is impersonating.

Here is my code:
```
                var provider = new Microsoft.Owin.Security.DataProtection.DpapiDataProtectionProvider("website1");
                UserManager.UserTokenProvider = new DataProtectorTokenProvider<Member, int>(provider.Create("ConfirmEmail"));
                string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);

```

**Comment by Eilon** [comment]
@vartig so you're using ASP.NET MVC 5 with ASP.NET Identity on your own site?

@HaoK / @blowdart / @Tratcher - any idea what could cause this error?

**Comment by vartig** [comment]
correct @Eilon 
although I fixed my problem using a custom class by inheriting from IDataProtectionProvider but it might be an interesting issue for your team and a useful tip for others ;)
Thanks

**Comment by rynowak** [comment]
Closing this as it seems to be resolved.
