### ISSUE TITLE
asp-for TagHelper doesn't work inside a ViewComponent (possibly others as well).

### ISSUE THREAD

**Issue by chinookproject** [aspnet/Mvc#6359]
I have a `ViewComponent` that returns a `View`. In that view I have a form with a few input fields. On those fields I added the `asp-for` attribute. But for some reason they don't work when used in a ViewComponent.

When I place the content of the view directly in, lets say, my `index.cshtml`, then all the `asp-for` tags work perfectly. Just not in combination with a ViewComponent.

I've added a demo project to show the problem.

Is this a bug?

[Demo - ViewComponent TagHelpers bug.zip](https://github.com/aspnet/Mvc/files/1050594/Demo.-.ViewComponent.TagHelpers.bug.zip)

**Comment by NTaylorMullen** [comment]
@chinookproject Your ViewComponent's view does not have an `@addTagHelper`. The reason why TagHelpers automatically light up in your other views is because you have a `_ViewImports.cshtml` sitting next to those views that have the `@addTagHelper`

**Comment by chinookproject** [comment]
Thanks! It works when I add the tag helper in the ViewCompents view file. I thought the `ViewComponent` would also pick up the imports from the `_ViewImports.cshtml`. But it makes sense now that it doesn't.

**Comment by dmitry-pavlov** [comment]
Tag helpers work fine for me in ASP.NET Core. I keep view components under Views/Shared/Components/Component1.. as described in documentation: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.1)
