### ISSUE TITLE
app.UseForwardedHeaders gives different result when run in container

### ISSUE THREAD

**Issue by singlewind** [aspnet/Mvc#6360]
We use SSL termination on Load balancer, so we use the following code to handle proper redirection of https and url generation.

```
app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });
```

When debug in windows, it behaves as expected. Even the protocol from LB is http, it will displays https.

![windows](https://cloud.githubusercontent.com/assets/7637/26767182/bd168fe8-49e0-11e7-9cd1-af4a30623e28.PNG)

However, when it hosts inside a container based on image microsoft/aspnetcore:1.1 it fails.

![linux-container](https://cloud.githubusercontent.com/assets/7637/26767197/fd91d622-49e0-11e7-9258-6254250919e3.PNG)

I reckon it can be a deep issue of Kestrel.

**Comment by singlewind** [comment]
@Tratcher , It woks with the following code to suppress the match of x-forwarded-for

```
app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedProto
            });
```

**Comment by Tratcher** [comment]
Seems like an issue with UseForwardedHeaders, please move this to the BasicMiddleware repo.

**Comment by Tratcher** [comment]
Oh, I see the problem.
https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.HttpOverrides/ForwardedHeadersOptions.cs#L63-L68
`::1` is an allowed local IP to apply forwarders on, `172.21.0.3` isn't. Adding 172.21.0.x to KnownNetworks would fix this.

**Comment by singlewind** [comment]
I know what you mean now, the local ip is dynamically generate when the container starts, I better use the local ip instead of local loop ip as known hosts.

**Comment by rynowak** [comment]
This issue was moved to aspnet/BasicMiddleware#242

**Comment by RehanSaeed** [comment]
@singlewind Did you figure out a workaround for this? I'm running an app in a Docker container behind an AWS Application Load Balancer (ALB) and `Request.IsHttps` is always returning false.

**Comment by singlewind** [comment]
@RehanSaeed, see the code above. I will post all the code anyway to you and feel free to modify. If you know your subnets of cluster, please use one of commented code for enhanced security. You need reference Microsoft.AspNetCore.HttpOverrides package if you are not using any mega package contains this one. 

`
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
                // the first local ip address for X-Forwarded-* from local
                // the second ip address mainly for docker default network, it may not apply based on the docker settings.
                // match the all ips, at the moment, it hard to know which local network it setups
                KnownNetworks =
                {
                    // new IPNetwork(IPAddress.Loopback, 8),
                    // new IPNetwork(IPAddress.Parse("172.0.0.0"), 8)
                    new IPNetwork(IPAddress.Any, 0)
                }
            });
            // not necessary use http method override, it onlys for some companies firewall blocks PUT and DELETE
            // app.UseHttpMethodOverride();
`
