### ISSUE TITLE
Html.GetEnumSelectList   do not render properly

### ISSUE THREAD

**Issue by Cuiqs76** [aspnet/Mvc#6362]
before my code as below but not render properly. the control does not render the enums.

```html
<div class="form-group">
            <label asp-for="FormNoType" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="FormNoType" asp-items="Html.GetEnumSelectList<FormNoType>()" class="form-control"/>                
                <span asp-validation-for="FormNoType" class="text-danger"></span>
            </div>
        </div>
```

And finally, I found that the html label  need to write  in the following form

```html
<select asp-for="FormNoType" asp-items="Html.GetEnumSelectList<FormNoType>()" class="form-control"></select>
```

**Comment by Eilon** [comment]
@NTaylorMullen - any idea why this might not be working right?

**Comment by NTaylorMullen** [comment]
The reason why it's not rendering correctly is due to the self-closed select element. Our TagHelpers do not modify the self-closed nature of the tag.

**Comment by yoyoys** [comment]
@NTaylorMullen is that will be a enhancement in next version?

**Comment by rynowak** [comment]
@yoyoys 

If you're referring to this, we have no plans to change this behavior. We plan to add warnings to tooling and publishing that will tell you about this.

> Our TagHelpers do not modify the self-closed nature of the tag.

**Comment by rynowak** [comment]
@NTaylorMullen @Eilon is this answered? close?

**Comment by NTaylorMullen** [comment]
Answered.
