### ISSUE TITLE
ModelState Errors contains only Exceptions and not other non-exception errors

### ISSUE THREAD

**Issue by codefactorydevelopment** [aspnet/Mvc#6364]
We have a web api project with data annotations on our properties (StringLength). Also, our properties are strongly typed so, among others, there are decimal ones.

If user submits 'aaa' (so, string) to decimal type property AND if he submits value that breaks StringLength annotation constraint what happens is we get only exception error in Model state with following in Exception field:

`{Newtonsoft.Json.JsonReaderException: Could not convert string to decimal: ABC. Path 'propertyName', line 12, position 29.   at Newtonsoft.Json.JsonReader.ReadDecimalString(String s)   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)   at Newtonsoft.Json.JsonTextReader.ReadAsDecimal()   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)}`

Problem is, why don't we get other validation errors as well?

On the other hand, if user submits model that only breaks annotation rules but no exception - then we get full collection.

**Comment by khellang** [comment]
Those are two different levels of "validation". The first one is from JSON deserialization, where the given string doesn't match the CLR type it's trying to deserialize to. Because of this, the JSON serializer is unable to create the object and MVC can't perform additional validation on it.

**Comment by codefactorydevelopment** [comment]
Huh...so how to handle this kind of situation? Does that mean we cannot give users all errors at once?

Because, end user couldn't care less if its 'can't cast string to decimal' or 'property too long'.

Is there any way around it?

**Comment by khellang** [comment]
> Does that mean we cannot give users all errors at once?

Yes, because step 1 is required before step 2. If step 1 fails, there's no way to get the errors for step 2.

> Is there any way around it?

Don't let the user send strings for decimals? I.e. validate the data on the client before sending. 😛

**Comment by codefactorydevelopment** [comment]
ok i see, thanks for clarification!

additionally, not letting users send string for decimals is fine when you control the client app but when you develop api for all kinds of third party clients its pretty much impossible.

but sure i see your point and thanks for reply!

**Comment by khellang** [comment]
> when you develop api for all kinds of third party clients its pretty much impossible.

Sure, but at that point, what can you do? What happens when a user submits syntactially invalid JSON? I think the current message is fine here. It even mentions line and position where the error is 😄

**Comment by codefactorydevelopment** [comment]
well, that is exactly why i think its not best way handled.

if json structure itself is not valid then thats completely different case/issue. in that case error like this should be handled with 415 response status code because input format itself was corrupted so server cannot even understand request.

but here its actually failure to comply with data type of the property so its not on json level but business logic / entity level.
After all, exception still ends up in ModelState.
In my opinion, its a candidate for 422 response code because, according to http specs, server did understand request format but cannot process it.

**Comment by khellang** [comment]
It's syntactically valid JSON, yes, but it's the only place where you have the actual value that was passed by the user. What would happen if you just skipped the invalid property and passed the object along to validation? At that point, the user would get back a message saying that `'PropertyName' is a required field` and the user would be equally confused. Or even worse; the value would just be left as `0.0` and saved to the database 😱 

It [looks like this behavior has been thought through](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.Formatters.Json.Test/JsonInputFormatterTest.cs#L218-L247) and it's clearly intended behavior.

**Comment by codefactorydevelopment** [comment]
(just as intro disclaimer: i dont say its not intended, i just express my surprise it being done this way for, in my opinion, obvious reasons.)

well, that highly depends on implementation. it doesnt have to be the only place.
for example, if you think about json in c# terms its just a Dictionary<string,object>. There is no reason why you couldnt do something like this:

1) check if json is semantically correct
2) create tmp Dictionary<string, object> from json
3) now, as a part of model validation, you do check if object from json with given key is castable to target type
4) if not, you just add another error in model state as you would do with any other dataannotation rule broken

**Comment by Eilon** [comment]
What @khellang mentions here is spot on.

If you have an object that you want to directly validate, you can call `TryValidateObject()` on it.
