### ISSUE TITLE
jQuery ajax request with complex data does not work with .net core 1.1 model bindings

### ISSUE THREAD

**Issue by st2forget** [aspnet/Mvc#6372]
I had posted a question here: https://stackoverflow.com/questions/44388722/net-core-model-binding-standard-different-from-net-4-6.

For example, I used this code to query data from server (.net 4.6) using jQuery (with success):
```
this.xhr = $.ajax({
    type: method,
    url: uri,
    headers: headers,
    contentType: 'json',
    data: this.data
}).done((json) => {
    resolve(json);
}).fail((e) => {});
```

Here is the request payload:
![image](https://user-images.githubusercontent.com/7732856/26870068-eb5ee0b2-4b98-11e7-9801-c9d9561282af.png)

However, after upgrade the framework to .net core 1.1, the model binding always gives me empty model with every null properties. After searching around, I figured out that, instead of using "Boundary[TopLeft][Lat]:11.140155424464904", it must be "Boundary.TopLeft.Lat.:11.140155424464904". But I don't know how to do that using jQuery because it seems like jQuery always parse data into some kind of "field[childField][2levelChildField]]" but not "field.childField.2levelChildField"

Here is the .net core action:
![image](https://user-images.githubusercontent.com/7732856/26870246-93bd601c-4b99-11e7-8ab6-eb8ba603729f.png)

Is there anyway to make .net core adapt to that?

**Comment by frankabbruzzese** [comment]
contentType for json is not 'json' but 'application/json'. jQuery doesnt recognize the content type ad uses the default content type 'application/x-www-form-urlencoded', so data  are out in the query string which is inadequate for complex nested objects. Using the right content type json will be added in the body, and you need to decorate your parameter with: [FromBody]. 

If you want to send json in 'application/x-www-form-urlencoded' format you may add yourself the query string to the url instead of specifying the data field. This way you build it adequately. However I suggest using  'application/json'.

**Comment by st2forget** [comment]
I know, just changed to application/json, and the parsed data or jQuery is still 
`
api/address/cluster-marker?Boundary%5BTopLeft%5D%5BLat%5D=10.80333487538099&Boundary%5BTopLeft%5D%5BLon%5D=106.6382437695313&Boundary%5BBottomRight%5D%5BLat%5D=10.791447007019459&Boundary%5BBottomRight%5D%5BLon%5D=106.7206412304688&Limit=100`

which is:

```
Boundary[TopLeft][Lat]:10.80333487538099
Boundary[TopLeft][Lon]:106.6382437695313
Boundary[BottomRight][Lat]:10.791447007019459
Boundary[BottomRight][Lon]:106.7206412304688
Limit:100

```

All I need to know is, is there any way to make jQuery convert data to Boundarr.TopLeft.Lat instead of Boundary[TopLeft][Lat] or is there any way to make .net core mvc allow Boundary[TopLeft][Lat] in stead of Boundarr.TopLeft.Lat?

**Comment by frankabbruzzese** [comment]
@st2forget ,
in fact the right way to submit a json object to the server is a POST request with the application/json format, thus inserting the object in the request body. In fact, according to HTTP/1.1 the server should ignore the body of a GET request, that is why  jquery always uses  'application/x-www-form-urlencoded' for get requests.

**Comment by st2forget** [comment]
So, it always uses 'application/x-www-form-urlencoded' for get requests and I know that, however, you can see that jQuery parse data as a query striing and put it on the query as my comment above or here:

![image](https://user-images.githubusercontent.com/7732856/26874773-0ddd6f0e-4ba9-11e7-82f5-168fd0d2c5aa.png)

If we use some online tools to decode the query string, we will get:
```
Boundary[TopLeft][Lat]:11.160365943678892
Boundary[TopLeft][Lon]:105.09580542499998
Boundary[BottomRight][Lat]:10.375190070026862
Boundary[BottomRight][Lon]:107.73252417499998
Center[Lat]:21.0333
Center[Lon]:105.85
Limit:10
```

The problem is, [FromQuery] attribute only read "Limit:10", but the others will be null. But, if I change the query string from above to below, it works perfectly:

```
Boundary.TopLeft.Lat:11.160365943678892
Boundary.TopLeft.Lon:105.09580542499998
Boundary.BottomRight.Lat.:10.375190070026862
Boundary.BottomRight.Lon.:107.73252417499998
Center.Lat.:21.0333
Center.Lon.:105.85
Limit:10
```

Besides, the frontend works correctly with the old framework (.net 4.6). You could take a look at https://socosy.co (currently using .net 4.6) and everything works fine. All I want to know is, why .net core 1.1 only accept parsed data as "Boundary.TopLeft.Lat" but not "Boundary[TopLeft][Lat]". jQuery or even qs package (npm) has the same parse out put which is always "Boundary[TopLeft][Lat]".

**Comment by frankabbruzzese** [comment]
Asp.net core mvc has no JsonFormatter for query string data  but only for request body, so query string data are processed by the standard model binding engine that do want dot separated identifiers, since [ and ]  are for collection and dictionary indices. Moreover, as stated [here](https://github.com/aspnet/Mvc/issues/3264#issuecomment-306548554) there are no plans to implement  a similar formatter.

Therefore, you have to change you code somehow, Either you build and adequate query string or you use a POST request and put the json in the body. I suggest the second option, since a GET request should not contain complex nested data.

**Comment by st2forget** [comment]
Well, is there anyway for me to write a custom formatter/middleware so that I could change the request "key"?
For example, when I got some data as above {Boudary[TopLeft][Lat] : "12342", Boundary[Topleft][Lng]: "12424"}, I could change it to {Boundary.TopLeft.Lat:"12342", Boundary.Topleft.Lng:"12424"}, then I will pass it to next middleware/formatter/model binding provider and everything works as usual?

Many thanks for your support.

**Comment by Eilon** [comment]
@dougbu / @rynowak - thoughts? Is this related to the general jQuery "query string format" thing we've seen several times?

**Comment by rynowak** [comment]
Yes, looks like it.

**Comment by mkArtakMSFT** [comment]
@kichalla can you please check whether this has been fixed? @rynowak thinks this may already be fixed.

**Comment by mkArtakMSFT** [comment]
@kichalla, @rynowak has confirmed that this hasn't been fixed. We should do that.
