### ISSUE TITLE
Param Problem at return View("String ViewName", string as object)

### ISSUE THREAD

**Issue by DFGBen** [aspnet/Mvc#6378]
Hey there,

I just found out that if you give a String directing to a View and also give a String as Model object to return View, the controller wont be able to find the View. Dont know why but even if I write down the whole path it would fail.

Just so you know  and maybe you can fix :)

**Comment by rynowak** [comment]
Can you please submit a code sample or link to repo that demonstrates a problem? Without that we don't know what you're talking about

**Comment by DFGBen** [comment]
string connectedUser = User.Identity.Name.ToLower().Split('\\')[1];
return View("~/Views/Shared/NotAuthorized.cshtml", connectedUser);

Now the controller can not find the view. But without the String as Object it works.

Sry if you couldnt understand what I meant

**Comment by rynowak** [comment]
It sounds like you're saying that:
```
string connectedUser = User.Identity.Name.ToLower().Split('\\')[1];
return View("~/Views/Shared/NotAuthorized.cshtml", connectedUser);
```
works fine

but
```
string connectedUser = User.Identity.Name.ToLower().Split('\\')[1];
return View("~/Views/Shared/NotAuthorized.cshtml", connectedUser);
```
Does not

Can you describe what you mean by `cannot find the view`? Are you using the [Developer Exception Page](https://github.com/aspnet/Mvc/blob/dev/samples/MvcSandbox/Startup.cs#L29)?

**Comment by DFGBen** [comment]
No.

if you do 
`string connectedUser = User.Identity.Name.ToLower().Split('\\')[1];
return View("~/Views/Shared/NotAuthorized.cshtml", connectedUser);`

it returns that the view or its master page could not be found.

if you do:
`return View("~/Views/Shared/NotAuthorized.cshtml");`
instead then it returns the view normally.

And I guess it is bcs both the view path and the parameter (Model) are strings.
Thanks in advice!

**Comment by rynowak** [comment]
> it returns that the view or its master page could not be found.

Is this MVC Core or an older version?

**Comment by DFGBen** [comment]
its mvc 5

**Comment by D4rkiii** [comment]
Workaroung to get it work:

return View(model: *YOURSTRING-VARIABLE*) 
or you have to define your model as object 
return View(*YOURSTRING-VARIABLE* as object)

Otherwise you have to define the path to your view and set your string "model" as the second parameter.

**Comment by rynowak** [comment]
Yes, @D4rkiii is correct, this is a known gotcha with MVC5. 

MVC5 has both
`View(string, string)` https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Web.Mvc/Controller.cs#L785
`View(string, object)` https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Web.Mvc/Controller.cs#L790

MVC Core has only `View(string, object)` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Controller.cs#L139

Closing as there's no plans to change MVC5 and this repo tracks MVC Core.
