### ISSUE TITLE
Offer a way to secure a Razor Page without having to configure it separately in Startup

### ISSUE THREAD

**Issue by jchadwick** [aspnet/Mvc#6379]
If I would like to secure a page (require a user to be authenticated, or belong to a role/satisfy a claim), I would expect to be able to do that right in the Page itself.

From what I can tell, the current approach is to use the `RazorPagesOptions.AuthorizeFolder()`, `RazorPagesOptions.AuthorizePage()`, etc. in the `Startup.Configure` but this is awkward for a few reasons:
- It's difficult to discover.  I have to go to another file (Startup) to try and figure out 
- Having to use a string- and URL-based approach feels like a step backward, especially when you're doing so in Startup.cs right next to all your other MVC controller- and action-based logic. 
    - Another problem with string-based approach is that the combination of `Authorize(Folder|Page)`, and `AllowAnonymousTo(Folder|Page)` increases the chances of false positives and false negatives, and makes it more difficult to diagnose such issues.

Jumping ahead to the implementation: since Razor Pages is "just MVC", I would expect this to be implemented the same as any other MVC controller or action: by adding an AuthorizeAttribute to a Page Model or page handler.

This is somewhat related to (dependent upon?) #6334.

**Comment by Eilon** [comment]
Yup, I think this is exactly what https://github.com/aspnet/Mvc/issues/6334 will help achieve.

cc @rynowak

**Comment by brockallen** [comment]
Better yet, allow for an authorization policy to be specified (rather than a list of roles).

**Comment by jchadwick** [comment]
@brockallen right.  

More importantly:  just behave as much as possible like the "standard" way of authenticating/authorizing MVC controllers and actions.

**Comment by Eilon** [comment]
All the work that we're planning to do here is covered by https://github.com/aspnet/Mvc/issues/6334, which enables applying MVC filter attributes (such as `[Authorize]`) to Page Models.
