### ISSUE TITLE
View returns 200 OK even on validation errors

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/Mvc#6380]
When returning using the `View` method in the controller it always returns a 200 OK even if there are validation errors.

```cs
[HttpPost]
public IActionResult Register(RegisterViewModel model)
{
    if (!ModelState.IsValid)
    {
        return View(ModelState); // Returns 200 OK
    }

    return View();
}
````

Shouldn't it return a 400 Bad Request when the model is not valid?

**Comment by Eilon** [comment]
You can set the status code yourself to something other than 200, e.g. `Response.StatusCode = 400`. The reason this isn't done by default is that there's no way to determine the correct status code, and responses by default always assume 200 unless there was an exception.

**Comment by vanillajonathan** [comment]
Well, wouldn't the correct status code when the model is invalid be a 400 Bad Request?

**Comment by Eilon** [comment]
@vanillajonathan the idea is that it's up to app logic to make that determination. Invalid model state might be just about any 400-level HTTP status code. It could easily be a generic 400, which just says "something you sent me is bad", or it could be a more specific 404, which would mean "you're asking me for something that doesn't exist." MVC can't know that without app logic.

**Comment by vanillajonathan** [comment]
Well, as I see it;
1. The MVC framework looks up the action in the controller, if not found the MVC framework returns 404.
2. The developer validates the model by checking `ModelState`. If invalid the MVC framework **ought** to return 400 when returning the view.
3. The developer **may** perform additional app logic to return something such as 404.

This would allow the developer to return an arbitrary status code before or after validating the model.
400 Bad Request seems like a suitable status code for an invalid model since the model is invalid because the request was "bad".
