### ISSUE TITLE
Consider moving RequireHttpsAttribute to HttpAbstractions (or somewhere else)

### ISSUE THREAD

**Issue by muratg** [aspnet/Mvc#6384]
We'd like to potentially use this in SignalR to require HTTPS usage from the Hubs.

See https://github.com/aspnet/SignalR/issues/457 

cc @davidfowl @Eilon.

If we end up doing this, we'd rather do it in 2.0.0.

**Comment by muratg** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
The attribute doesn't do anything, it can live anywhere. We moved the AuthorizeAttribute down to the Security repo for the same reason.

Are you actually going to try sharing the filter implementation code?

**Comment by Tratcher** [comment]
The RequireHttpsAttribute implements MVC abstractions like IAuthorizationFilter, it can't be moved without refactoring.

**Comment by Eilon** [comment]
Yeah I don't see how we'd do this in practice - not without a breaking change in MVC. We could move the attribute to HttpAbstractions and make it a marker attribute, and then MVC and SignalR would each have their own filter mechanisms to locate the marker attribute. But that'd be a breaking change, so not in scope for 2.1. And I'm not sure it's worth waiting for 3.0 to do this.

So, closing it.

cc @rynowak @davidfowl FYI
