### ISSUE TITLE
<a> Tag Helper - Associated VS2017 Warning

### ISSUE THREAD

**Issue by stap123** [aspnet/Mvc#6391]
When using the <a> tag helper and a target attribute simultaneously VS2017 gives a warning saying "Attribute is allowed only when 'href' is present".  I guess it's pretty obvious why it's happening as it tells us but not sure it's the desired behaviour.

Example of tag:

```
<a class="list-group-item" asp-controller="Home" asp-action="CPDRedirect" asp-route-id="2" target="_blank">View all activities</a>
```

This is obviously not stopping anything working but thought you might like to know (and it's a little annoying to have warnings when there isn't anything wrong).

If this isn't the correct repo, can you let me know the correct one and I will raise there.

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Razor#1428
