### ISSUE TITLE
Add generic overload/extension method for MvcOptions.Filters.AddService<FilterType>

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6395]
We should add an extension method to `MvcOptions.Fiters` that allows adding a service-based filter type via a generic argument, e.g.:

``` c#
services.AddMvc(options =>
        {
            options.Filters.AddService<RequireLoginFilter>();
        });
```

@rynowak @davidfowl

**Comment by Eilon** [comment]
Basically a convenience version of this: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Filters/FilterCollection.cs#L73

Should add:
1. `Add<TFilterType>()`
2. `Add<TFilterType>(int order)`
3. `AddService<TFilterType>()`
4. `AddService<TFilterType>(int order)`

**Comment by rynowak** [comment]
Also related https://github.com/aspnet/Mvc/issues/6161

**Comment by rynowak** [comment]
@jbagga - looks like we got a PR for this that will satisfy the requirements, so no need for you to take action here

**Comment by rynowak** [comment]
7166dfe

**Comment by rynowak** [comment]
Thanks @henkmollema
