### ISSUE TITLE
UnitTesting Controllers with HttpContext/Identity is a fairly complicated process 

### ISSUE THREAD

**Issue by snebjorn** [aspnet/Mvc#6399]
I had the fun idea of trying to write unit tests for the default AccountController. But it turned out to be quite the ride.
I ended up with this for my setup.

```csharp
//Usermanager mocks
var userStoreMock = Substitute.For<IUserStore<ApplicationUser>>();
var optionsMock = Substitute.For<IOptions<IdentityOptions>>();
var passwordHasherMock = Substitute.For<IPasswordHasher<ApplicationUser>>();
var userValidatorMock = Substitute.For<IEnumerable<IUserValidator<ApplicationUser>>>();
var passwordValidatorMock = Substitute.For<IEnumerable<IPasswordValidator<ApplicationUser>>>();
var lookUpNormalizerMock = Substitute.For<ILookupNormalizer>();
var identityErrorDescriberMock = Substitute.For<IdentityErrorDescriber>();
var serviceProviderMock = Substitute.For<IServiceProvider>();
var loggerMock = Substitute.For<ILogger<UserManager<ApplicationUser>>>();

var userManagerMock = Substitute.For<UserManager<ApplicationUser>>(
    userStoreMock,
    optionsMock,
    passwordHasherMock,
    userValidatorMock,
    passwordValidatorMock,
    lookUpNormalizerMock,
    identityErrorDescriberMock,
    serviceProviderMock,
    loggerMock);

//SignInManager mocks
var contextAccessorMock = Substitute.For<IHttpContextAccessor>();
var claimsPricipleFactoryMock = Substitute.For<IUserClaimsPrincipalFactory<ApplicationUser>>();
var loggerMockSM = Substitute.For<ILogger<SignInManager<ApplicationUser>>>();

var signInManagerMock = Substitute.For<SignInManager<ApplicationUser>>(
    var userManagerMock,
    contextAccessorMock,
    claimsPricipleFactoryMock,
    optionsMock,
    loggerMockSM);

var cookieOptionsMock = Substitute.For<IOptions<IdentityCookieOptions>>();
var identityOptionsMock = new IdentityCookieOptions();
cookieOptionsMock.Value.Returns(identityOptionsMock);

var emailMock = Substitute.For<IEmailSender>();
var smsMock = Substitute.For<ISmsSender>();

var loggerMockCtrl = Substitute.For<ILogger<AccountController>>();

var uut = new AccountController(userManagerMock, signInManagerMock, cookieOptionsMock, emailMock, smsMock, loggerMockCtrl);

var httpContext = Substitute.For<HttpContext>();
uut.ControllerContext = new ControllerContext
{
    HttpContext = httpContext
};
uut.TempData = Substitute.For<ITempDataDictionary>();
uut.Url = Substitute.For<IUrlHelper>();
```
And that is still missing a few things, as described here https://www.danylkoweb.com/Blog/how-to-successfully-mock-httpcontext-BT (+other stuff I probably don't know about)

It would be nice if there were some helpers or documentation on how to properly setup controllers for unit testing.
You did an awesome job on the `TestServer`. So looking for something similar that makes unit testing easier :)

**Comment by Eilon** [comment]
Yup, I agree this is a bit messy. We're planning to make testing parts of MVC apps a lot easier in our 2.1.0 release, and I think this is an especially painful area.

cc @javiercn @rynowak FYI

**Comment by snebjorn** [comment]
Brilliant, looking forward to it :)

**Comment by Eilon** [comment]
@javiercn any idea what else we can add to make this easier?

**Comment by javiercn** [comment]
Most of the things that are hard to test in here are Identity dependencies. I don't think this is necessarily an MVC issue but more of an Identity issue. 

That said, it's easier to use TestServer to write tests for these scenarios, we have some documentation about that coming up. And it will be easier to do in 2.1 with integration tests.

@HaoK Is there anything better we can do here in terms of all the identity mocks?

**Comment by javiercn** [comment]
@snebjorn 

I've put together a blog post and a sample of the approach described above. Maybe this works better for you?

The blog post is here:
https://blogs.msdn.microsoft.com/webdev/2017/12/07/testing-asp-net-core-mvc-web-apps-in-memory/

The sample is here:
https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/testing/TestingMVC

**Comment by snebjorn** [comment]
Thank you, I'll check it out
