### ISSUE TITLE
How should we attach extra data to exceptions

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#640]
Can we attach extra data to our exceptions that are more helpful in understanding/debugging the issues? What's the pattern. @yishaigalatzer has some ideas - see: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/MvcRouteHandler.cs#L54

**Comment by yishaigalatzer** [comment]
Please drive the discussion. I'd like to reach a consensus on the design and either keep what we have or remove the one place in the code that does it today.

**Comment by yishaigalatzer** [comment]
Remove the current code, it's not adding a lot of value. When we need to throw specific exception we might create a custom exception type instead. But that will happen very sparingly, e.g. `AmbiguousActionException`

**Comment by rynowak** [comment]
02f656667f8231d1be373ef523f078beeefbb23f
