### ISSUE TITLE
ArgumentNullException when using [BindProperty] on a private property

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6400]
This is not supported, but the result shouldn't be an exception with this trace:

```
ArgumentNullException: Value cannot be null.
 Parameter name: metadata
Microsoft.AspNetCore.Mvc.ViewFeatures.ModelExplorer.GetExplorerForExpression(ModelMetadata metadata, Func<object, object> modelAccessor)
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ExpressionMetadataProvider.FromLambdaExpression<TModel, TResult>(Expression<Func<TModel, TResult>> expression, ViewDataDictionary<TModel> viewData, IModelMetadataProvider metadataProvider)
Microsoft.AspNetCore.Mvc.ViewFeatures.ModelExpressionProvider.CreateModelExpression<TModel, TValue>(ViewDataDictionary<TModel> viewData, Expression<Func<TModel, TValue>> expression)
```

**Comment by rynowak** [comment]
I don't think this has anything to do with `[BindProperty]`, it's the use of a private property in a tag helper like `input` that would generate a call stack like this

**Comment by rynowak** [comment]
but yes, this is bug

**Comment by rynowak** [comment]
So what I'm planning to do here is add error checking and explain that you should not try to use tag helpers with private properties. We don't support private properties for model binding (they are ignored) so using them for tag helpers won't really have the desired effect.

**Comment by rynowak** [comment]
a23307e2b1e7934e2c8d69774cda1b36778f697b
