### ISSUE TITLE
FromRouteAttribute doesn't seem to work in Razor Pages

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6402]
```
[FromRoute]
public string Foo {get;set;}
```

With this route:
```
@page "{Foo}"
```

Foo is empty, however I can access the value with `RouteData.Values["Foo"]`

**Comment by pranavkm** [comment]
Is this on a GET request? We don't execute any model binders by default for GET requests. You have to explicitly annotate the property to state this:

```C#
[BindProperty(SupportsGet =  true)]
[FromRoute]
public string Foo { get; set; }
```

**Comment by sebastienros** [comment]
Then you can close if it's by design.

But do you mean it's model bound for some other verbs?

**Comment by rynowak** [comment]
We're going to take some action here to make pages 100% consistent with controllers.

**Comment by rynowak** [comment]
0ad9c7d4eb500f282647cc571f368030465c0730
