### ISSUE TITLE
Issue when removing an entry from PageApplicationModelProviderContext

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6403]
Related to https://github.com/aspnet/Mvc/issues/6123

I implemented my own `IPageApplicationModelProvider` and removed an entry from `context.Results`.
I can still access the Razor Page I removed, through a weird url: `http://localhost:53017/?page=%2FContact`
This url was generated with `<a asp-page="/Contact">Contact</a>`

The other pages which were not removed from `Results` work fine.

**Comment by pranavkm** [comment]
This makes sense - the route constraints don't match a page named `/Contact`, so it's constructing a match at the app root and tacking on the constraint. You'll get the same behavior if you attempt to route to a controller \ action that does not exist.

**Comment by sebastienros** [comment]
It's constructing a custom route, and I can still access the page. What I am trying to achieve is to prevent a page from being accessed. Could you give any guidance on that? That was the reason I filed #6123.

**Comment by pranavkm** [comment]
Ahh, missed the bit where it says it can still be accessed. Sounds like a bug.

**Comment by rynowak** [comment]
> I can still access the Razor Page I removed, through a weird url: http://localhost:53017/?page=%2FContact

If this is true there are some shenanigans happening.

**Comment by rynowak** [comment]
Can you please provide a repo of this?

**Comment by sebastienros** [comment]
While making a nice little repro it actually worked well

Here is the code in case someone wants a sample later:

```csharp
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.ApplicationModels;

public class CustomPageApplicationModelProvider : IPageApplicationModelProvider
{
    public int Order { get; } = 1000;

    public void OnProvidersExecuting(PageApplicationModelProviderContext context)
    {
    }

    public void OnProvidersExecuted(PageApplicationModelProviderContext context)
    {
        var itemsToRemove = context.Results.Where(x => x.RelativePath.Contains("Contact")).ToList();
        foreach(var itemToRemove in itemsToRemove)
        {
            context.Results.Remove(itemToRemove);
        }
    }
}
```
