### ISSUE TITLE
Easy way for accessing model attributes in Tag Helper

### ISSUE THREAD

**Issue by hmdhasani** [aspnet/Mvc#6404]
Let's say we have this viewmodel:

```
public class viewModel {
   [ReadOnly(true)]
   public Boolean HasAccess {set;get;} 
}
```

and in View:
`<input asp-for="HasAccess"/>`

I want to extend InputTagHelper to generate disabled html attribute when the property has ReadOnly attribute 

I need to access the list of attributes of corresponding property in TagHelper but it seems there is no way for that.
The only bad way that I found is using reflection like this:

```
public class ExtendedInputTagHelper : InputTagHelper
    {
        public ExtendedInputTagHelper(IHtmlGenerator generator)
            : base(generator) { }

        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            var modelAttributesProperty = For.Metadata.GetType().GetProperty("Attributes");
            var modelAttributes = modelAttributesProperty.GetValue(For.Metadata) as ModelAttributes;

            if (modelAttributes.PropertyAttributes.FirstOrDefault(m => m.GetType() == typeof(ReadOnlyAttribute)) is ReadOnlyAttribute readOnlyAttribute
                && readOnlyAttribute.IsReadOnly == true)
            {
                var attribute = new TagHelperAttribute("disabled", "disabled");
                output.Attributes.Add(attribute);
            }

            base.Process(context, output);
        }
    }

```

but this way does not always work. for example if we have inheritance in model and the actual type is the child of declared type this way will get attributes of parent type.

I think there must be a strange way for accessing actual model attributes but I can not find

**Comment by rynowak** [comment]
Why not use `For.Metadata.IsReadOnly`? https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/ModelBinding/ModelMetadata.cs#L235

**Comment by hmdhasani** [comment]
@rynowak I don't think it can help in my case because it is false even when I have [ReadOnly(true)]

**Comment by rynowak** [comment]
That's a little surprising to me. I searched the code and couldn't find any references to `ReadOnlyAttribute` so I think you're right. @dougbu any ideas why this might be the case.

So you have a few options as I see it. You could....
1. Keep doing what you're doing
2. Use `[Editable(false)]` which we do support
3. Implement an [IBindingMetadataProvider](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Metadata/IBindingMetadataProvider.cs) and set `IsReadOnly` yourself.

I'd choose 3, if it were me, it would look like a very simplified version of https://github.com/aspnet/Mvc/blob/c27b07ef3f8b07dfe1d1de38a8d7bf2d6a9298f4/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/DataAnnotationsMetadataProvider.cs

**Comment by dougbu** [comment]
> @dougbu any ideas why this might be the case.

With few exceptions, MVC only deals with attributes in the `System.ComponentModel.DataAnnotations` namespace. I'd therefore lean toward 2. `[Editable(AllowEdit: false)]` for this case.

That said, we do support at least one attributes from `System.ComponentModel` that is equivalent to one from `System.ComponentModel.DataAnnotations` i.e. `[DisplayName("name")]` and `[Display(Name="name")]`. Could extend the `DataAnnotationsMetadataProvider` to support `[IsReadOnly]` as it does `[Editable]`, giving priority to `[Editable]`. Of course, we might need to rename `DataAnnotationsMetadataProvider` (and its containing assembly and package 😈).

**Comment by hmdhasani** [comment]
@rynowak [Editable(false)] did the trick for me, thank you!
But let's keep the issue general as I see many other situations that some one would need to access any attributes. one another case is [DataType(DataType.MultilineText)] to generate textarea instead of input so I still think there must be an easy way for getting attributes.

**Comment by rynowak** [comment]
> But let's keep the issue general as I see many other situations that some one would need to access any attributes

If you want to by the way you can downcast to `DefaultModelMetadata` which has the attributes on it directly. Basically what you're doing by doing this is saying that you **assert** that you're relying on the default metadata implementation which is based on attributes and reflection.

If you want to do something more thorough, write an `IDisplayMetadataProvider` and store any data you want in `AdditionalValues` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Metadata/DefaultModelMetadata.cs#L165 This is the more first class way to provider extra data, as it's not coupled to reflection. You could use arbitrary logic to populate these values however you want.

**Comment by hmdhasani** [comment]
@rynowak I didn't know about `AdditionalValues 
`
That's great!

**Comment by dougbu** [comment]
> one another case is `[DataType(DataType.MultilineText)]` to generate textarea instead of input

That attribute is supported and `@Html.Display[For]()` / `@Html.Editor[For]()` already generate `<textarea></textarea>` instead of `<input/>` for that case.

This doesn't happen when using tag helpers for an unrelated reason: The in-box tag helpers with HTML5 element names intentionally _extend_ those elements e.g. adding a `value` attribute rather than replace them with something completely different. In other words, if you want `<textarea></textarea>`, use that tag.

If there's a problem here, please file a separate issue.
