### ISSUE TITLE
[Question] How to modify the model argument after binding has taken place

### ISSUE THREAD

**Issue by joacar** [aspnet/Mvc#6408]
Hi,

I have an interface `IAdvertiserRequest` that contains two properties: `UserId` and `Advertiserid`. My command models (those that request the data) implements that interface and the data that should be populated is in the users claims.

Is there any way to check that the command is assignable to `IAdvertiserRequest` and then populate those properties?

I've tried with a custom model binder but can't make it work. Secondly that doesn't feel like a correct approach since I don't want to mess with the model binding, only enrich the incomming request.

Thanks for a great job

**Comment by rynowak** [comment]
>My command models (those that request the data) implements that interface and the data that should be populated is in the users claims.

I'll let the security experts @blowdart and @haok comment on this approach.

In general if you want to do something **after** model binding has occured, use an Action Filter. https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters

**Comment by joacar** [comment]
@rynowak Thanks! 

Implemented it like

```c#
public class AdvertiserRequestEnricherActionFilter : IAsyncActionFilter
    {
        private readonly ITenantUser _user;

        public AdvertiserRequestEnricherActionFilter(ITenantUser user)
        {
            _user = user;
        }

        public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
        {
            // ReSharper disable once LoopCanBeConvertedToQuery
            // Cannot use inline variable assignment with LINQ
            foreach (var action in context.ActionArguments)
            {
                if (!(action.Value is IAdvertiserRequest request))
                {
                    continue;
                }
                request.UserId = await _user.GetUserIdAsync();
                request.AdvertiserId = await _user.GetIdAsync();
                break;
            }
            await next();
        }
    }
```

Now I can also easily change how the user attributes are fetched: either claims or database or something else.

I'll leave this open until the security experts have commented on this approach :)

**Comment by rynowak** [comment]
I think the primary concern security-wise is that you want to keep a fence between data that is subject to tampering and what is not. Anything that the default model binding system deals with is **always** submitted by another computer out there in the wild and is **always** subject to tampering and falsification.

**Comment by joacar** [comment]
Yes I've understood that all public data on view models are subject to mass-assignment issue.

Alternatively I could map incomming request with the implementation command sent to CQRS layer, as this hides the data that shouldn't be tampered with. This could be done in the controller (as I did just before implementing this) by injecting `ITenantUser` and manually set the properties or create a base controller with a method that enriches the command and copies the binded properties.

**Comment by rynowak** [comment]
>Yes I've understood that all public data on view models are subject to mass-assignment issue.

This isn't a mass-assignment issue exactly. All data that is part of an HTTP request is untrusted. If your `UserId` and `AdvertiserId` come from the request data then they are could have any values that a client wants to send.

**Comment by frankabbruzzese** [comment]
I think the ActionFilter code is safe, since the action filter always override UserId  and AdvertiserId. At least it is safe as claims sent in auth cookie are. With https, claims are safe, without it some attacks are possuble also to encrypted cookies (they may be simply stolen and re-used).

The only way to force values contained in the request is by preventing somehow the action filter execution. In theory, this might be possible if there is another "unsafe" filter in the chain. An attacker might attack the "unsafe" filter with an ad hoc input to force it to jump all pending filters execution.

**Comment by blowdart** [comment]
The core auth cookies are always encrypted, even if sent over HTTP.
