### ISSUE TITLE
With appconfig.json being read by default, how do you override this?

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Mvc#6409]
In ASP.NET Core 2, looks like logging and configuration is pre-wired for you, is there a way to override this behavior that I'm not finding? (both changing the name and properties of the appconfig.json and changing the way that logging behaves outside of adding configuration in appconfig.json?

**Comment by davidfowl** [comment]
You have a few options:
- You can add more configuration options via `IWebHostBuilder.ConfigureAppConfiguration`.
- You can avoid using `WebHost.CreateDefaultBuilder` and go back to doing it the old way.

**Comment by shawnwildermuth** [comment]
If I use CreateDefaultBuilder but then override the config and logging by creating the ConfigureAppConfiguration and ConfigureAppLogging i'm just replacing them right?  As long as I add them before I call Build, i'm fine, right?

**Comment by davidfowl** [comment]
They compose, you aren't replacing them. in 2.0.0 RTM, you'll be able to clear configuration providers and logging providers.

**Comment by shawnwildermuth** [comment]
Got it!
