### ISSUE TITLE
[Question] - hosting.json

### ISSUE THREAD

**Issue by dazinator** [aspnet/Mvc#6411]
I have just converted my project.json based solution from vs2015 to a vs2017 csproj based solution, and now I notice that the port that the executable serves the web app on has reverted to port 5000.

In startup.cs I add a json configuration file to configure the hosting:

```

 var configRootBuilder = new ConfigurationBuilder();

  configRootBuilder.SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile(appSettingsPath)
                    .AddJsonFile(hostingConfigPath, optional: true)
 ```

the `hosting.json` file looks like this:

```
{
  "server.urls": "http://localhost:57929;http://localhost:60001"
}

```

This worked prior to the upgrade, however after the upgrade, when I run the solution:

![image](https://user-images.githubusercontent.com/3176632/27294525-c16c488a-5511-11e7-90dc-217b50bebebc.png)

It appears this hosting.json file no longer has an effect.

What am I missing?

Our deployment processes relies on updating this `hosting.json` file with the correct hostname:port for the environment prior to running the app, so at the moment this process is no longer working for us.

**Comment by davidfowl** [comment]
`hosting.json` isn't special anymore. You can pass a configuration file to the code in your `Program.cs` via `IWebHostBuilder.UseConfiguration`

**Comment by dazinator** [comment]
Yup I am already doing that:

```
   var host = new WebHostBuilder()
                .UseKestrel()               
                .UseConfiguration(appConfig)
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();
```

**Comment by dazinator** [comment]
Ah looking at https://stackoverflow.com/questions/42892173/hosting-json-available-options it looks like `server.urls` may have changed to be just `urls`.. Will give that a go.

**Comment by dazinator** [comment]
Yup that was the culprit!
