### ISSUE TITLE
[Question] How to retrieve RouteValues in ActionSelector?

### ISSUE THREAD

**Issue by MarcusKohnert** [aspnet/Mvc#6413]
I've created a GitHub repo for this issue here: https://github.com/MarcusKohnert/MoreThanOneRouteHitActionSelector

I have two actions on two different controllers bound to the same route.
http://localhost/sameControllerRoute/{identifier}/values

Since there are two matching routes, the default ActionSelector fails with:
'[...] AmbiguousActionException: Multiple actions matched. [...]'
which is comprehensible.

So I thought I can implement my own ActionSelector:
https://github.com/MarcusKohnert/MoreThanOneRouteHitActionSelector/blob/master/CustomActionSelector/MoreThanOneRouteHitActionSelector.cs#L9

In there I would implement the logic that resolves the issue of multiple routes via same logic depending on the 'identifier' route value.
https://github.com/MarcusKohnert/MoreThanOneRouteHitActionSelector/blob/master/CustomActionSelector/MoreThanOneRouteHitActionSelector.cs#L27

If 'identifier' value is a --> then FirstController
If 'identifier' value is b --> then SecondController
and so on...

But I haven't found a good solution to get access to the route values in ActionSelector. Which is comprehensible as well because ModelBinding hasn't kicked in yet since MVC is still trying to figure out the Route.

A dirty solution could be to get hold of IHttpContextAccessor and regex somehow against the path.

But I'm still hoping you could provide a better idea to retrieve the route values even though ModelBinding hasn't happend yet in the request pipeline.

**Comment by rynowak** [comment]
> In there I would implement the logic that resolves the issue of multiple routes via same logic depending on the 'identifier' route value.

A much better approach for this would be to something like this https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.ActionConstraintSample.Web/CountrySpecificAttribute.cs

We're going to make what you're asking for possible in a future release, but it's intended that you use action constraints for most scenarios.

**Comment by MarcusKohnert** [comment]
Thanks for the hint to IActionConstraint and I'm glad to hear that my initial attempt to solve the problem gets adressed in a future release. thanks 👏

The problem I'll face with IActionContraint though is that I can't use (Constructor) Dependency Injection. (**Which breaks the promise of DI all the things somewhat**) 😳

**Comment by rynowak** [comment]
You absolutely can use DI.

1. Register your *real* `IActionConstraint` in DI
2. Make an attribute that implements `IActionConstraintFactory` 
3. Retrieve your *real* `IActionConstraint` and return it

**Comment by MarcusKohnert** [comment]
👍 works like a charm. Thank you very much for your help.
(Hoping to find some time to blog about it...)

**Comment by rynowak** [comment]
Keeping this item around for now to track the improvement we want to make for 2.1

**Comment by mkArtakMSFT** [comment]
@rynowak, should this be moved to `Routing` repo?

**Comment by rynowak** [comment]
I think we can close this, we've added some new extensibility points using Endpoint Routing in the routing repo that cover this need. `IActionConstraint` will remain as-is.
