### ISSUE TITLE
razor generated code should have the ubiquitous auto-generated in the comments

### ISSUE THREAD

**Issue by jimmymain** [aspnet/Mvc#6414]
The omitted `<auto-generated/>` in the comments for code files generated by the razor engine are causing [multiple issues](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2373#issuecomment-309723230) to be raised in [other projects](https://github.com/aspnet/Tooling/issues/498).

Please could we have `<auto-generated />` added as the first line of the comments in razor generated code files. 

This will **alleviate** the **huge volume of noise** being generated in code analysis when opening *.cshtml* files.

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2373
https://github.com/aspnet/Tooling/issues/498

Perhaps also consider including `#pragma warning suppress 1591` as well. Either that, or ensure that each generated comment is XML compliant.

https://github.com/dotnet/roslyn/issues/12702

**Comment by rynowak** [comment]
This issue was moved to aspnet/Razor#1449
