### ISSUE TITLE
Allow configureRoutes to override the default route.

### ISSUE THREAD

**Issue by hallatore** [aspnet/Mvc#6416]
UseMvc() always adds attributes routing first. This makes it impossible to create a route with higher priority.

Most people will likely never actually override the default attribute route. But I don't see a reason to keep it locked down like it is currently. 

The proposed change enables the scenario for custom routes that take priority over the default one. And even the possibility to remove the default route.

Pull request #6415

**Comment by Eilon** [comment]
It is deliberate that attribute routes come first. We recommend having your app implement a custom version of `UseMvc()` that has the logic that makes sense for your app.
