### ISSUE TITLE
Add Forbidden and Unauthorized methods on ControllerBase

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#6418]
Today we have Challenge and Forbid that map to the auth system. We should also have methods that map directly to the status codes like other ones.

**Comment by pranavkm** [comment]
This guy - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs#L1872?

**Comment by davidfowl** [comment]
New ones that return StatusCode(403) and StatusCode(401) + The `WWW-Authenticate` header.

**Comment by Eilon** [comment]
We should clarify the docs on the existing Challenge/Forbid methods stating that they don't simply set the HTTP status code, but rather that they go through the auth system to call Challenge/Forbid, which then typically set the HTTP status code.

**Comment by mohd-akram** [comment]
I'm also confused about when to use Challenge vs Forbid.

**Comment by mkArtakMSFT** [comment]
So seems there are multiple actions to be taken here, so splitting it up now:
1. Update the documentation: https://github.com/aspnet/Mvc/issues/7292
2. Add the new helper methods on ControllerBase: https://github.com/aspnet/Mvc/issues/7293

**Comment by mkArtakMSFT** [comment]
Hi @mohd-akram. The following StackOverflow question has an answer providing a short summary about those two concepts: https://stackoverflow.com/questions/42883946/forbidasync-vs-challengeasync-why-and-when-to-use-them
