### ISSUE TITLE
Rename TagHelperComponentTagHelper

### ISSUE THREAD

**Issue by hishamco** [aspnet/Mvc#6419]
IMHO the name `TagHelperComponentTagHelper` is too long and annoying little bit, can we consider a new name by simplifying, making this more clear and readable such as `TagHelperComponent`?!!

**Comment by rynowak** [comment]
What's the situation where you find yourself having to type this name often?

**Comment by hishamco** [comment]
I already used `TagHelperComponent` in one of my [jsLogger](https://github.com/hishamco/jsLogger/blob/master/jsLogger/TagHelpers/JavaScriptLoggingTagHelperComponent.cs#L7) repo before, but I surprised when I saw the name `TagHelperComponent` in the `BodyTagHelper` [here](https://github.com/aspnet/Mvc/blob/e681c23d5ca11dc26a4b15f955d6af8995c99b5c/src/Microsoft.AspNetCore.Mvc.Razor/TagHelpers/BodyTagHelper.cs#L15)

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.

**Comment by hishamco** [comment]
I'm just asking why we need such long name where it starts and ends with `TagHelper`?!!

**Comment by Eilon** [comment]
But this *isn't* a Tag Helper Component. This is a Tag Helper that *uses* Tag Helper Components.

**Comment by hishamco** [comment]
Thanks
