### ISSUE TITLE
Move IActionContextAccessor to Microsoft.AspNetCore.Mvc.Abstractions

### ISSUE THREAD

**Issue by bgever** [aspnet/Mvc#6421]
I have problems referencing `IActionContextAccessor` from a .NET Standard 1.4 library.
I depend on Standard 1.4, because the host app is targeting Framework 4.6.1.

Unfortunately, [`IActionContextAccessor`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/IActionContextAccessor.cs) is defined in package [Microsoft.AspNetCore.Mvc.Core 1.1.3](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Core/) which depends on .NET Standard 1.6.

However, package [Microsoft.AspNetCore.Mvc.Abstractions 1.1.3](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Abstractions/) can target .NET Standard 1.3.

Since the interface is clearly an abstraction and a fundamental part for dependency injection in libraries, Microsoft.AspNetCore.Mvc.Abstractions would be the more logical package to hold this interface and make references to.

Currently I've worked around this problem by changing the library in question to target Framework 4.6.1, since Microsoft.AspNetCore.Mvc.Core can (oddly?) target also Framework 4.5.1. However, I would like to deploy this app cross-platform therefore want to switch to Standard 1.4 instead.

**Comment by rynowak** [comment]
>Since the interface is clearly an abstraction and a fundamental part for dependency injection in libraries, Microsoft.AspNetCore.Mvc.Abstractions would be the more logical package to hold this interface and make references to.

We don't want to make the use of this interface more prominent or encouraged. There's a performance cost associated with this feature and it's not registered by default for that reason.

We don't use this anywhere in the framework, and mostly provide it for a convenience in porting code that used `HttpContext.Current` in the past.

If we did something in the future like make the current request available in the DI container, that would be the way we would first class this.

----

Note that our current development is based on netstandard2.0 which is supported by/equivalent-to net461. We have no plans to support ASP.NET Core on anything earlier than

**Comment by bgever** [comment]
Yes, I'm aware of the [announcement to also remove `IHttpContextAccessor`](https://github.com/aspnet/Hosting/issues/793) as a dependency registered by default.

However, in my application I need to have access to both `IActionContextAccessor` and `IHttpContextAccessor` in services to provide *essential functionality* for the web application:
- Multi-tenancy detection based on the incoming domain name of the request.
- Localization based on values in the RouteData.

If it's discouraged, that should be documented and not attempted to be prevented by obscurity. Moreover, I've yet to see quantitative information about the performance penalty.

I still think the interface should be defined where it makes sense, not where it's hard to get. :-)

What would be the recommended way to get access to this for ASP.NET Core 1.1 (while avoiding the accessors)? My gut feeling is I need to implement custom middleware that registers state somewhere that is later on pulled from the request context somehow?

**Comment by rynowak** [comment]
> What would be the recommended way to get access to this for ASP.NET Core 1.1 (while avoiding the accessors)? 

It's still not clear to me exactly what you mean by 'get access to this'.

The common pattern here would be to add data to the `HttpContext` either by adding to the `.Features` or `.Properties`. Then your data that is associated with the current context will flow along with it.

If you can give me an example of a concrete problem you need help with, I can give some advice.

-----------

If you want to use these features (`IActionContextAccessor`, `IHttpContextAccessor`) that's fine. There is a performance cost associated with this, and for that reason we have no plans to make them on by default.

**Comment by pranavkm** [comment]
@bgever is this still a concern? Mvc 2.x targets `netstandard2.0` that can be referenced from application targeting `net461`. This unblocks your initial concern, doesn't it?
