### ISSUE TITLE
File upload problem

### ISSUE THREAD

**Issue by rdvojmoc** [aspnet/Mvc#6422]
Problem occurs when validation is done on file and BadRequest is returned from the controller to the client (file to big, or wrong content type), connection is closed after whole file is transferred to the server and not immediately when BadRequest is set in a response  as it should be. 

![snap3677](https://user-images.githubusercontent.com/13537823/27398210-50b96a10-56b9-11e7-92b7-eb5721290b82.png)

Project that i made that reproduce problem:
[FileUpload](https://github.com/rdvojmoc/FileUpload)
There is no part which saves the file to the disk to keep things simple. Problems becomes more obvious when you upload large files ( > 1GB).

Custom model binder (only model state error is set to make things simple):
```
public class AssetBinder : IModelBinder
{
      protected readonly IHostingEnvironment _hosting;
      protected readonly FormFileOptions _fileOptions;	

      public AssetBinder(IHostingEnvironment hosting, IOptions<FormFileOptions> fileOptions)
      {
         _hosting = hosting;
			
         _fileOptions = fileOptions.Value;
      }

      public Task BindModelAsync(ModelBindingContext bindingContext)
      {
          bindingContext.ModelState.TryAddModelError("test", "test error message");
            
          return TaskCache.CompletedTask;
      }
}
```

Controller:
```
[HttpPost]
[DisableFormValueModelBinding]
public IActionResult Post(Asset asset)
{
	if (!ControllerContext.ModelState.IsValid)
	{
	       return BadRequest(ControllerContext.ModelState);
	}
	return Ok();
}
```

I'am testing on Windows 10 Pro, version 1607, build 14393.1358, 64 bit. NET Core version is 1.1 and Microsoft.AspNetCore.Mvc is 1.1.2

**Comment by rdvojmoc** [comment]
Is this wrong place for this issue?

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
Dupe https://github.com/aspnet/KestrelHttpServer/issues/1913#issuecomment-310365829
