### ISSUE TITLE
What about testing?

### ISSUE THREAD

**Issue by xlegalles** [aspnet/Mvc#6423]
It's not really an issue but still a big problem.
Lest me explain: one year ago, we began an important new project and it is mainly about micro services. It was obvious that ASP.NET Core v1 was not production ready and so we have selected .NET 4.6. We were expected Docker for Windows but did not know yet the details...
One year later it is obvious that if we want to do microservices with .NET and Docker, we have to use .NET Core.
The preview is out. Most of 3pp libraries are compatible. So it's time to migrate. But what about testing? testing controllers routing, etc. Do you have plan for it?
From my point of view, no one will use ASP.NET Core v2 (except for fun) if testing must be as painfulll as descibed in #6399? Waiting for 2.1 is not even serious and the 2.0 would be totally useless.
We just hope (and pray) that MyTested.AspNetCore.Mvc will be ready soon enough.

**Comment by davidfowl** [comment]
What specifically are you looking for, it'll be good to know if the support we're improving will address your concerns.

**Comment by xlegalles** [comment]
Actually (using ASP.NET Web API 2) we have 2 types of UT:
- routing: to verify that when we invoke a specific expected route, we get the correct controller and parameters. Just positive tests to check the entire REST API.
`WithHttpGet().TestRoute("all", x => x.GetFields(true));`
- controllers: to verify that when we invoke a controller with a specific input, we get the proper response (HTTP status code, header and body). Negative and positive tests.
`With(QueryController.GetFields, (bool?)true).ExpectHttpOK().ExpectResultDtoSequence(expectedList);`

The 'testing controller' doc page seems very complex for such basic tests. Compared to MyTested.AspNetCore.Mvc which is a bit more concise/efficient (it also tests routing). 
We also wonder how testing an ActionResult is sufficient when you know that nothing has been serialized yet? It would be a pity if we had to use a HttpClient to get the same level of confidence that we have today.

**Comment by Eilon** [comment]
In ASP.NET Core 2.1 we are planning to make testing of MVC applications much easier. Today it's generally possible, but very difficult to set up without 3rd party components, so it's good to know that there are rich 3rd party testing components.

If you have some specific suggestions on improvements we can make to unit testing MVC controllers, we will look at those.

**Comment by xlegalles** [comment]
Don't take this the wrong way, I don't want to be negative or criticize: we are still big fans of .NET/C# but the fact is that times are a bit hard for us because of the way things evolve. One year after the start of the project we have to migrate all our micro services to ASP.Net Core because of Nanoserver. We still have many problems to make Docker run smoothly on Windows with both linux/windows containers. We still don't know how to manage our c++ legacy code (that uses CLI wrappers). And now that the production code is migrated, we wonder how to manage testing. So everybody talks about microservices but the reality is that it is very difficult to implement with .NET (btw we cannot target Azure).

Concretely we have found yesterday a way to refactor our controller tests with .Net Core. So it means that we did not change the tests themselves and still do something like that: `With(QueryController.GetFields, (bool?)true).ExpectHttpOK().ExpectResultDtoSequence(expectedList);`
Again it's my opinion, but I still think that it would be better to be able to test controllers this way as it gives more confidence to verify Http status code and content (body/header) after serialization.

Routing tests are another story and I'm afraid we will have to implement something.

By the way, if I can suggest something else for 2.1 and testing, it is about consumer driven contracts: we use a PACT.Net fork but it is still very perfectible. The idea and the workflow is still good and very similar to [spring-cloud-contract](https://github.com/spring-cloud/spring-cloud-contract). This is not just theory as this kind of tests is very important for microservices architectures.

**Comment by Eilon** [comment]
@xlegalles thanks for the details!

cc @javiercn who is working on the testing area right now.

**Comment by Eilon** [comment]
@javiercn any ideas what else we can do to improve some of these scenarios?

**Comment by javiercn** [comment]
Hi, @xlegalles 

You might be interested in this post and sample about how to perform end to end test of MVC applications in memory
https://blogs.msdn.microsoft.com/webdev/2017/12/07/testing-asp-net-core-mvc-web-apps-in-memory/
https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/testing/TestingMVC

I believe that what you are looking for is something more low-level, but I would encourage you to look at the approach described in the post. It's the same approach we use to test the framework and it has worked very well for us.

It's a bit cumbersome to setup for now, but it will be streamlined in 2.1.

Hope this helps!
