### ISSUE TITLE
Extend ViewComponents shared view location.

### ISSUE THREAD

**Issue by AndreVianna** [aspnet/Mvc#6426]
In the ViewViewComponenetResult class, line 95, in the ExecuteAsync method, the code that generates the path for locating the view component has the following description:

                // This will produce a string like:
                //
                //  Components/Cart/Default
                //
                // The view engine will combine this with other path info to search paths like:
                //
                //  Views/Shared/Components/Cart/Default.cshtml
                //  Views/Home/Components/Cart/Default.cshtml
                //  Areas/Blog/Views/Shared/Components/Cart/Default.cshtml
My suggestion is that the system should generated an additional path `Components/Shared/Default` and the following additional folders should also be checked:

                //  Views/Shared/Components/Shared/Default.cshtml
                //  Views/Home/Components/Shared/Default.cshtml
                //  Areas/Blog/Views/Shared/Components/Sharedt/Default.cshtml
In this order:

                //  Views/Shared/Components/Shared/Default.cshtml
                //  Views/Shared/Components/Cart/Default.cshtml
                //  Views/Home/Components/Shared/Default.cshtml
                //  Views/Home/Components/Cart/Default.cshtml
                //  Areas/Blog/Views/Shared/Components/Shared/Default.cshtml
                //  Areas/Blog/Views/Shared/Components/Cart/Default.cshtml
This would allow to have views to be shared between the components.

**Comment by Eilon** [comment]
We could certainly make this configurable by allowing multiple search paths. (Note to @rynowak , these are called ş̨̃̂̌̃ͬ̂̓͌͟͏͓̳̯̦͍̮ͅţ͙̣͓̹̱̬̋̋̐̈́̉̕ͅu̶̲̞͓̤̺͆̔́́̌͐̐́̀ḃ̡̨ͫͥͯͨ͝͏͈̫̬͢s̸̲̫̣͔͎̼͉̙͋̀̈͌̈͛͋͗́ͯͩͭͫ̚͜.)

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.
