### ISSUE TITLE
Circular base class dependency involving 'PageModel' and 'PageModel'

### ISSUE THREAD

**Issue by mikebrind** [aspnet/Mvc#6441]
This error happens when you add a Razor Page (with page model) named "Page.cshtml" because the resulting auto-generated `PageModel` class tries to inherit itself:

```csharp
public class PageModel : PageModel
{
    public void OnGet()
    {
    }
}
```

**Comment by pranavkm** [comment]
We don't autogenerate a page model type. Did you create a model type named `PageModel`?

**Comment by pranavkm** [comment]
@prafullbhosale, is this a Scaffolding issue?

**Comment by prafullbhosale** [comment]
Nope. Scaffolding Razor Pages is not available yet. 
Looks like a Template issue. 
cc @mlorbetske, @seancpeters

**Comment by Eilon** [comment]
@mlorbetske / @seancpeters - where do the item templates for Razor Pages live? Can we get a bug filed there?

**Comment by Eilon** [comment]
This issue was moved to dotnet/templating#1010
