### ISSUE TITLE
Layout and PartialView should first search for mainviews's folder

### ISSUE THREAD

**Issue by John0King** [aspnet/Mvc#6447]
In  controller ( `TestController` ):

```C#
 return View("subfolder/index");
```
View loation:

```
Views/
    Test/
        subfolder/
            index.cshtml
            _layout.cshtml
            _partial.cshtml
    _ViewStart.cshtml  (   Layout = "_layout" )
```

MVC will not pick the `_layout.cshtml`  and `_partial.cshtml` from `subfolder` folder.

In razor View, there is property called `Path` and `ViewContext.Views.Path` , It can get the current view's absolutePath so 
I hope view can search in follow order:
1. MainViews's folder for ` _viewstart`,  `_viewimport` , `_layout` , `_partialviews`
2. /Views/Controllers/ for  ` _viewstart`,  `_viewimport` , `_layout` , `_partialviews`
3. /Views/Shared/ for  `_layout` , `_partialviews`
4. /Views/  for ` _viewstart`,  `_viewimport` 

## mvc version
version:1.1.2
famework: .net 4.6.1

**Comment by pranavkm** [comment]
Mvc will treat it as a relative path if you specify an extension to the file name. For instance, `Layout = "_Layout.cshtml";` would result in looking up the file in `/Views/Test/subfolder/_Layout.cshtml`. Similarly with the partial too. You can also write a `ViewLocationExpander` if you'd like to look for the file in the view's directory in addition to the default set of paths the view engine looks for files in. A gist of what this might look like:

```C#
public class RelativePathViewLocationExpander : IViewLocationExpander
{
   public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
   {
        if (!context.IsMainPage && context.ActionContext is ViewContext viewContext)
        {
            var viewPath = viewContext.ExecutingFilePath;
            var index = viewPath.LastIndexOf('/');
            var result = viewPath.Substring(index + 1) + context.ViewName + ".cshtml";
            
            yield return result;
        }
       
        foreach (var item in viewLocations)
        {
            yield return item;
        }
   } 
  
   ....
}
```

**Comment by John0King** [comment]
@pranavkm   In Controller ,  if I `return View("index.cshtml")`  ,  It will try to find view in `~/index.cshtml` .
Is that behaviour right ?

**Comment by pranavkm** [comment]
Yup, that's the behavior. To summarize the rules for view engine discovery:

* Any name with an extension (`.cshtml`) is treated as path.
* Paths starting with `~/` (e.g. `~/Views/Home/Index.cshtml`) are content root relative.
* Paths without a `~/` are relative to the current executing file path. If no view is currently executing, e.g. if it's a view returned from a controller, the current executing file path is the content root.

**Comment by pranavkm** [comment]
Closing this there's nothing more to do here.
