### ISSUE TITLE
How to get current AntiForgeryToken in view?

### ISSUE THREAD

**Issue by JoshClose** [aspnet/Mvc#6467]
In a controller I'm able to add an `IAntiforgery` parameter to the constructor and have it injected so that I'm able to call `IAntiforgery.GetTokens( HttpContext )` to get an `AntiforgeryTokenSet`. How can I achieve this in a view?

I need this in either every view, or a layout, so I can't pass it in from the controller.

**Comment by rynowak** [comment]
```
@inject IAntiforgery Antiforgery

@{
    var tokens = Antiforgery.GetTokens(...);
}
```
This will generate an `Antiforgery` property in the compiled view code and DI the `IAntiforgery` service.

**Comment by JoshClose** [comment]
`@inject` dang that's handy. Thanks!

**Comment by blowdart** [comment]
This is also documented on the antiforgery page.

https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery
