### ISSUE TITLE
unexpected behavior

### ISSUE THREAD

**Issue by 50774283** [aspnet/Mvc#6477]
dotnet sdk version : 2.0.0-preview2-006497

![000](https://user-images.githubusercontent.com/16589080/27763329-4d01540c-5eb4-11e7-9afe-56399ef97982.PNG)

![999](https://user-images.githubusercontent.com/16589080/27763330-4d25da84-5eb4-11e7-9fba-23e493258a02.png)

I have two questions below.

1、Why string "=//////=" is output when application just start?
2、Why string "=//////=" do not output when I visit http://localhost:5000/?branch ?

Thank you.

**Comment by davidfowl** [comment]
> 1、Why string "=//////=" is output when application just start?

Because the pipeline is built once, not per request. Handle branch runs at application startup, then the middleware added to the sub pipeline is executed per request.

> 2、Why string "=//////=" do not output when I visit http://localhost:5000/?branch ?

Because it runs once.

PS: In the future, don't paste a screenshot of the code, just paste the code 😄 .

**Comment by 50774283** [comment]
@davidfowl thank you very much.
