### ISSUE TITLE
ASPNetCore MVC interferes with Let's Encrypt installation/automatic renewal

### ISSUE THREAD

**Issue by CaptMurphy** [aspnet/Mvc#6483]
See this post :: http://www.westerndevs.com/Tools/Lets-Encrypt-ASPNET-Core/

The developer had to create a "WellKnownController" to be able to handle Let's Encrypt Installation.

My issue :: I can't use System.IO to access the challenge key, because my web host has aliased the directories, meaning I have no physical /.well-known/* folder.

Currently, I cannot use the Let's Encrypt with AspNetCore.

The only solution I can think of is to have AspNetCore explicitly NOT handle a route, and just let the web server handle the request.

If there is another way, I could really use some help.

**Comment by rynowak** [comment]
Hi, so the issue here as I can tell is that you don't have access to these files - is that correct?

Are you running behind a reverse proxy? Should the proxy be serving these files?

> The only solution I can think of is to have AspNetCore explicitly NOT handle a route, and just let the web server handle the request.

Generally this works the other way around, if the server **doesn't** handle the request then ASP.NET gets a chance to process it.

/cc @davidfowl

**Comment by CaptMurphy** [comment]
So this was resolved by some IIS configuration magic.
inside /.well-known/ folder, create **web.config**

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <remove name="aspNetCore" />
        </handlers>
    </system.webServer>
</configuration>
```

I don't know exactly what this does, but I guess this can be closed since the web server configuration fixed it.

**Comment by rynowak** [comment]
>The only solution I can think of is to have AspNetCore explicitly NOT handle a route, and just let the web server handle the request.

OK, I'll stick my foot in my mouth. This is doing what you suggested exactly. You're putting a file in that folder that says "don't let ASP.NET run for this folder".

Glad you were able to get this solved.
