### ISSUE TITLE
Changing DI/service collection for initial ConfigureServices?

### ISSUE THREAD

**Issue by kierenj** [aspnet/Mvc#6484]
My use case is a little strange, but I feel it's worth asking about..

I have an Autofac container with my app's services.  I'm hooking this up by:

1. Using `IWebHostBuilder.ConfigureServices` with `services.Add(ServiceDescriptor.Transient(typeof(IStartup), typeof(AspNetCoreStartup)));`
2. In the `AspNetCoreStartup.ConfigureServices`, adding any DI registrations from the passed-in services collection to the Autofac container
3. Returning a new `IServiceProvider` from that `ConfigureServices` which wraps the Autofac container

However, things have moved on and `AspNetCoreStartup` now has dependencies which need to come from the Autofac container.  However, /it's/ dependencies are evaluated using that initial (`IWebHostBuilder.ConfigureServices`) DI container.  `AspNetCoreStartup` is coordinating various service registrations (my own, but also `AddMvc()`).

I've been avoiding just creating concrete classes, e.g. creating a singleton instance registration for the startup class, because everything up until this point has been nice and DI-oriented.

I guess what I'm asking is, can I have my cake and eat it - specify my own service collection DI container, but have DI into the startup class using that container?

**Comment by davidfowl** [comment]
> I guess what I'm asking is, can I have my cake and eat it - specify my own service collection DI container, but have DI into the startup class using that container?

Nope.  Somewhat related to this https://github.com/aspnet/Hosting/issues/550.

**Comment by kierenj** [comment]
Thanks for the response.  I don't think so - if you're talking `IWebHostBuilder.ConfigureServices` with the delegate, I can't see a way to have the registrations from Autofac to be used by MVC.

My workaround will be to register something like a service locator/factory/`IServiceProvider` that would be injected into the startup class to allow it to access the Autofac container.  It's obviously just not as nice as declaring dependencies with constructor parameters/props.

I'll track that other issue - it seems the ideal solution.  I have a similar use case: my app logic has selectable "host roles" - can run as an MVC/Web API host, message worker process, CLI for app administration, so DI is set up separately from the web host itself.  The MVC side is "pluggable", in that an app can register it's own module (via DI) which has implements callbacks called within `Configure` and `ConfigureServices`.  So I chose a difficult path and will live with it :)

**Comment by Eilon** [comment]
This issue was moved to aspnet/Hosting#1129
