### ISSUE TITLE
Can't seem to retrieve the URL fragment

### ISSUE THREAD

**Issue by ssougnez** [aspnet/Mvc#6493]
Hi,

I'm currently creating a asp.net core web application that can use Google to login and I'm using gapi to sign in. Basically, when the user is logged in, Google redirects him to an URL like: http://server.com/route#id_token=XXX&client_id=YYY.

Now I'd like to create a middleware that intercepts the path "/route" and then retrieves the "id_token", however, in don't find in the "context.Request" object a property that would contain either the fragments or even the full URL.

I also tried using "Microsoft.AspNetCore.Http.Extensions.UriHelper.GetDisplayUrl(context.Request);" but this returns me the URL without the "#". 

I have the same behaviour when I directly type an URL with a "#" (so the issue is not in the way that Google redirects the user).

Finally, I don't kniow whether it's possible for Google to returns a "?" instead of a "#" or not, but even if it is, I think that it should be possible to retrieve the fragment of the URL (except if this is an intended behaviour, but in that case, I'd like to know why :-))

(I'm using ASP.NET Core 2.0)

**Comment by rynowak** [comment]
Browsers don't send the fragment to the server.

https://en.wikipedia.org/wiki/Fragment_identifier

> Clients are not supposed to send URI-fragments to servers when they retrieve a document, and without help from a local application (see below) fragments do not participate in HTTP redirections.[1]

/cc @javiercn

**Comment by ssougnez** [comment]
All right! Kind of wondering why google decided to use fragments instead of query string then but your answer satisfies me :-)

I close the issue.

Thanks

**Comment by rynowak** [comment]
My guess is that they don't want you (on the server) to have the token.
