### ISSUE TITLE
ModelStateEntry AttemptedValue is null in case of invalid model

### ISSUE THREAD

**Issue by peterdeme** [aspnet/Mvc#6494]
Hi,

We have a special requirement for sending back error messages to the caller and we need to make a difference between invalid or missing entries.

```csharp
foreach (var item in modelState)
{
       if (item.Value.ValidationState == ModelValidationState.Invalid)
       {
             yield return new ErrorMessageList
             {
                    Code = item.Value.AttemptedValue == null ? "missing" : "invalid",
                    Field = item.Key
              };
        }
}
```

the problem here is that the AttemptedValue is still null, if for example the number is out of range. like:

```csharp
[Range(5,10)]
public int Something { get; set; };
```

if the input is 11, then the AttemptedValue will be null.

The problem here is that there's no difference between missing or invalid parameters in the current ModelStateEntry implementation. Unfortunately, currently the only way we can differentiate them is the error message in the ModelStateEntry.
Is there any advice or any hope to fix this?

Thanks
Peter

**Comment by Eilon** [comment]
I wonder if maybe RawValue has the value you're looking for?

cc @dougbu - any ideas on this?

**Comment by dougbu** [comment]
> if the input is `11`, then the `AttemptedValue` will be `null`.

I can't see how either `RawValue` or `AttemptedValue` could be `null` when simple values are bound. But, it's `AttemptedValue` you want for this use case.

@peterdeme could you provide a simple repro, preferably as a small GitHub repo we can examine?

**Comment by peterdeme** [comment]
Sure, here's an example:

![image](https://user-images.githubusercontent.com/19969687/27878464-9ed03372-61be-11e7-8cce-937ab620ba79.png)

**Comment by dougbu** [comment]
Sorry @peterdeme that shows the symptoms you already described but tells me nothing about how your application got there. Something odd is happening and I need to see the context to understand what.

**Comment by rynowak** [comment]
Ah, this is JSON. 

JSON.NET handles deserialization of JSON data in MVC, and doesn't put anything in model state. I'm not aware of any way that you can directly accomplish what you're asking.

JSON.NET has the ability to configure a property as required using `[JsonProperty]` - this will result in an error in model state indicating that a field was missing. If you wanted to turn this into something, you'd either have to recognize their error or attach to the event on `JsonSerializer` and handle this yourself.
