### ISSUE TITLE
When enabling "Trace" logging for MVC loggers, I should be buried in log messages

### ISSUE THREAD

**Issue by anurse** [aspnet/Mvc#6498]
## Repro Steps
1. Create a new MVC App (via the template, for example)
2. Change `appsettings.Development.json` to the following

```json
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information",
      "Microsoft.AspNetCore.Mvc": "Trace"
    }
  }
}
```

3. Run the app

## Expected behavior

The below, but with each soccer ball representing log messages:

![image](https://user-images.githubusercontent.com/7574/27882571-04ffea30-6182-11e7-8a40-9c2e23374d3d.png)

## Actual Behavior

11 new log messages, all for Razor compilation. Nothing for action selection, filters, action results, etc.

**Comment by rynowak** [comment]
Can you suggest some actionable improvements in these areas?

**Comment by anurse** [comment]
I guess not, I don't have enough context as to what's going on within the pipeline to know where the logging needs to happen.

This originated because the app I was inherited was using MVC Core and had not set up the Authorization filter, so when I tried to add Authorization, nothing was working. I couldn't find anything wrong in the docs (which may be a separate issue), so I tried to turning up the logging level and was shocked at how little I got back.

Certainly, logging something about registered filters at start up, and filters run on a request (including if no filters are run) would have been helpful there, since I had already identified that Authorization was controlled by a filter from searching the code.

So yeah, this may have just been a frustration-driven issue...

**Comment by anurse** [comment]
After doing some actual experimenting with diagnostics collection, I do have some more actionable suggestions now. A lot of these are for the `Debug` (or more likely `Trace`) levels, because they would be extremely spammy at the console, but at dev time, and/or with a searchable log database (ELK, Seq, etc.), they could be much more useful.

* ActionResults (which one is executing, what they're doing)
* Model binding (what values were bound to which parameters and what source was used to bind them; the values may need to be treated like EF parameters and suppressed from log messages unless explicitly turned on)
* Each filter that runs, and what kind of filters are running at each phase
* View compilation (view being compiled, view compiled, compiled view found in cache, etc.)
* View rendering (view being rendered, view rendered)
* Tag helper activation (running tag helper X, tag helper X complete)
* Validation errors
* Exceptions that escape Controller Actions
* Controller activation
* Action selection (which action was selected and why, which were discarded and why)

/cc @davidfowl re:diagnostics improvements

**Comment by anurse** [comment]
I've managed to dig some of these out of the existing logging sources once I figured out how to turn them up to Trace, but the messages still seem a little light.

**Comment by Eilon** [comment]
@kichalla can you take a look at this and see where you feel we have large gaps in our logging? We don't want to just add new logging statements everywhere in the system because that wouldn't be useful.

**Comment by anurse** [comment]
> We don't want to just add new logging statements everywhere in the system because that wouldn't be useful

You're right about wanting to find useful things, but I think we've been way too stingy with the `Trace` log level. I'd have expected turning `Trace` on to give me messages for pretty much every individual component involved in my request. `Trace`, to me, is supposed to be a deluge of events that a human couldn't possibly keep up with. `Trace` isn't necessarily about "useful" things, it's about following (or "Tracing") the flow of execution through the whole system. `Debug` and up are for more "useful" content :)

**Comment by Eilon** [comment]
In a discussion with @rynowak we were thinking that the logged events should still have *some* meaning within the context of MVC. So, yeah, sure, log every model binder that ran, log which doodad short-circuited a process, which thingamajig caused binding to fail. But logging every enter/exit of every method is not "meaningful".

So, yes, a deluge, but not a random deluge 😄

**Comment by anurse** [comment]
Filters were another area where I needed more logging data. I had an issue where I was using MVC Core and the Authorization filter wasn't added, and I would have really appreciated having a "Filters are running..." "End of filters" message to tell me that something was missing. Granted, I did have the advance knowledge that there was a filter that was supposed to do AuthZ stuff, which isn't something everyone would have.

Entry/Exit of method is extreme, and I agree not terribly meaningful. What's important for `Trace` is tracing the flow of the request through the subsystems (Filters, Action Invokers, Model Binders, etc.). Nobody outside the team really understands which things happen when in MVC and it can be really difficult to diagnose an issue when everything looks right but is hooked up in some wrong order (or missing some key element). Tracing the flow through subsystems is meaningful and doesn't seem random to me at all.

**Comment by Eilon** [comment]
Yup, I think these are great examples of "stuff that has genuine meaning to MVC."

**Comment by kichalla** [comment]
Closing this issue with the idea that we are going to identify specify areas that need logging and open more specific issues.
