### ISSUE TITLE
pass view content as parameter to html helper in asp.net core

### ISSUE THREAD

**Issue by omuleanu** [aspnet/Mvc#6502]
hi,
in ASP.net MVC 5 I was doing something like this:
```
        public class MyTabsHelper : IHtmlString // IHtmlContent in core
        {
        IList<Tab> tabs = new List<Tab>();
       ...
        public MyTabsHelper Add(string title, Func<object, HelperResult> template)
        {
            tabs.Add(new Tab { Name = title, Content = template.Invoke(null).ToHtmlString()});
            return this;
        }
```
so in the view I could do something like this:
```
       @(Html.MyTabsHelper()
             .CssClass("foo")
             .Add("description", @<text> some text</text>)
             .Add("description", @<text> more text @Html.SomeHelper() </text>))
```

in ASP.net Core there's no ToHtmlString() for the HelperResult, 
it seems that you can't  gather all the html contents as strings and after render them all at once
-----
my current solution, and I got it using trial and error + VS intellisense 
is to just call this the first time .Add is called:
```
Html.ViewContext.Writer.Write("<maindiv html...");
// close the maindiv in ToString() method override
```
and in the Add method:
```
Html.ViewContext.Writer.Write("<div>");//simplified code
Html.ViewContext.Writer.Write(template.Invoke(null));
Html.ViewContext.Writer.Write("</div>");
```

**Comment by omuleanu** [comment]
hi, my new solution is doing this:
```
public MyTabsHelper  Add(string title, Func<object, HelperResult> templatel)
{
    var sb = new StringBuilder();
    using (var memStream = new MemoryStream())
    {                
        using (TextWriter tw = new StringWriter(sb))
        {
            var encoder = (HtmlEncoder)ai.Html.ViewContext.HttpContext.RequestServices.GetService(typeof(HtmlEncoder));

            template.Invoke(null).WriteTo(tw, encoder);             
        }
    }
    var content = sb.ToString();
    ...
}
```
would be interesting to know, maybe there's an easier way

**Comment by Eilon** [comment]
The code you have is certainly a way to make this work. An alternative is to just use a default HtmlEncoder, which would work just fine in this scenario. That's a bit simpler than getting the service from the DI container.

We considered making it easier to get the current HtmlEncoder by adding a property for it on some existing type, such as ViewContext, but the demand for this is fairly low, so we're closing this issue.

**Comment by omuleanu** [comment]
@Eilon how do you get the DefaultHtmlEncoder ?  
(from within a class that inherits IHtmlContent, but not inside the WriteTo method where you have it as a parameter )

**Comment by Eilon** [comment]
@omuleanu the `HtmlEncoder` has a static `Default` property on it: https://github.com/dotnet/corefx/blob/master/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/HtmlEncoder.cs#L21

So, you can just call `HtmlEncoder.Default` to get a default instance.
