### ISSUE TITLE
Add default ctor overload to AuthorizeFilter

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#6514]
Currently creating AuthorizeFilter requires specifying a policy. We should provide a default overload that is equivalent to specifying `[Authorize]` everywhere.

**Comment by kichalla** [comment]
Following is a way to configure a global authorization filter in ASP.NET Core. From @blowdart here: https://stackoverflow.com/a/36415213
```c#
services.AddMvc(config =>
{
    var policy = new AuthorizationPolicyBuilder()
                     .RequireAuthenticatedUser()
                     .Build();
    config.Filters.Add(new AuthorizeFilter(policy));
});
```

**Comment by kichalla** [comment]
@rynowak For a scenario like adding a global filter (ex: `options.Filters.Add(new AuthorizeFilter());`), I was wondering if its ok to get the PolicyProvider from DI in the following scenario (when `PolicyProvider == null`) https://github.com/aspnet/Mvc/blob/f0a5af2ba7916ef50d5119952a48f9b13c6600ca/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L108-L119

Currently the `AuthorizationApplicationModelProvider` builds up this filter with the policy provider from the DI, but do you see any drawbacks in evaluating this service on a per request basis?

**Comment by rynowak** [comment]
We need to get the default policy, probably best to do it on the first request and then cache
