### ISSUE TITLE
DictionaryAttributePrefix with more than 3 parts is not supported

### ISSUE THREAD

**Issue by hishamco** [aspnet/Mvc#6516]
I came across a situation that I need a property like `asp-command-args-id`, `asp-command-args-name` .. etc, unfortunately seems the current implementation does not support properties that contains more than 3 parts separated by hyphen
IMHO it doesn't matter if we have 3 or more, because all the values will be bound into a `IDictionary<string,string>`

**Comment by Eilon** [comment]
@hishamco is this specifically about tag helpers? Can you share the relevant of your tag helper code, and what syntax you're using to set it in the CSHTML file? Also, are you getting an error, or is it just doing nothing?

**Comment by hishamco** [comment]
@Eilon I was tried this last two weeks when I blogged about [Customize Razor Pages Handlers](http://hishambinateya.com/customize-razor-pages-handlers) specifically [here](https://github.com/hishamco/RazorPagesCommands/blob/master/RazorPagesCommands/TagHelpers/CommandTagHelper.cs#L21)  I tried to use `asp-command-argument-*` , but when it's doesn't work I stay with `asp-command-*` as shown [here](https://github.com/hishamco/RazorPagesCommands/blob/master/RazorPagesCommands/TagHelpers/CommandTagHelper.cs#L21)

> are you getting an error, or is it just doing nothing?

Let me try it and come back to you on this

thanks

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by hishamco** [comment]
I didn't get any respond from the team from that time, I will try to check if I can reproduce this issue and come back again
