### ISSUE TITLE
How To Warp ExceptionFilter Result?

### ISSUE THREAD

**Issue by baiyunchen** [aspnet/Mvc#6527]
When I assign a value to context.Result in IExceptionFilter, the returned data format is always Json, how to format the context.Result according to the Accept in the Request Header, for example, format it as xml.
thanks.
```C#
public void OnException(ExceptionContext context)
{

    if (!IsHandleResult(context.ActionDescriptor.GetMethodInfo().ReturnType))
    {
        return;
    }

    ApiError apiError = null;
    if (context.Exception is DataValidationException)
    {
        var validationException = context.Exception as DataValidationException;
        apiError = new ApiError(validationException.Message);
        apiError.ValidationErrors = validationException.ValidationErrors;
    }
    else
    {
        var exceptionMsg = context.Exception.GetBaseException().Message;
        string stackTrace = context.Exception.StackTrace;
        apiError = new ApiError(exceptionMsg, stackTrace);
    }
    context.HttpContext.Response.StatusCode = (int)GetStatusCode(context);
    //i want format it according to Accept
    context.Result = new ObjectResult(apiError);
    context.Exception = null;
}
```

**Comment by rynowak** [comment]
Did you register an XML formatter? https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/DependencyInjection/MvcXmlMvcBuilderExtensions.cs#L15

XML is not included by default, you have to opt into it in startup code

**Comment by baiyunchen** [comment]
@rynowak I have enabled XML support (use AddXmlSerializerFormatters() method) , and the success request has been able to return XML, only ExceptionFilter can not return XML.
thank you.

**Comment by rynowak** [comment]
Does your `ApiError` data type serialize correctly?

If you try something like this, does it generate the XML or does it throw an exception?
```
var error = new ApiError(...);

var serializer = new XmlSerializer(typeof(ApiError));  
var writer = new StringWriter();  
serializer .Serialize(writer, error);  
Console.WriteLine(writer.ToString());
```

**Comment by baiyunchen** [comment]
@rynowak ```ApiError``` is normal C# Class,But i have not tried this manual serialization, and I need try to work tomorrow because the code is on the company's computer and has not access at home.
thank you again,and tomorrow i will try to it and fllow this issue.

**Comment by baiyunchen** [comment]
@rynowak  I suddenly thought that even if ```ApiError``` can not be serialize, it should throw an can not be serialized exception  should not return a Json data.

**Comment by rynowak** [comment]
> I suddenly thought that even if ApiError can not be serialize, it should throw an can not be serialized exception should not return a Json data

That is not the case. We don't attempt to serialize types for which we cannot create a serializer.

**Comment by baiyunchen** [comment]
@rynowak The problem has been solved, and as you said,```ApiError``` can not be serializer to XML due to the lack of a no parameteless constructor.
thank you again.

**Comment by rynowak** [comment]
Great, thanks for the update.
