### ISSUE TITLE
JSON conversion does not format dynamic properties as expected

### ISSUE THREAD

**Issue by alastairs** [aspnet/Mvc#6529]
## Reproduction
I'm writing a controller action in a Web API scenario. I have defined the following response object to be returned in a `201 Created` response:

```csharp
public class MyResponse
{
    // Other stuff not interesting here

    public dynamic Links { get; } = new ExpandoObject();
}
```

In my controller action, I set these links as follows:
```csharp
response.Links.DoSomething = Url.Action(nameof(DoSomething));
response.Links.Self = Url.Action(nameof(GetThis));
```

## Expected behaviour
The JSON should match that returned if `Links` is defined as an `object`, i.e.,
```json
{
  "links": {
    "doSomething": "/route/to/do/something",
    "self": "/route/to/self"
  }
}
```

## Actual behaviour
The properties of `Links` are not correctly converted to JSON, and retain the case defined when setting the links in the controller action (i.e., C# CamelCasing rather than JSON pascalCasing):
```json
{
  "links": {
    "DoSomething": "/route/to/do/something",
    "Self": "/route/to/self"
  }
}
```
This looks really odd.

## Workaround
I can work around this by defining my response as follows:
```csharp
public class MyResponse
{
    // Other stuff not interesting here

    public object Links { get; set; };
}
```
and setting `Links` as follows in my controller action:
```csharp
response.Links = new {
    DoSomething = Url.Action(nameof(DoSomething)),
    Self = Url.Action(nameof(GetThis))
};
```
but this causes me big problems in trying to test these links are set in the response, and I have to go to the lengths of defining a type for each `Links` collection, or using a Dictionary. I prefer the conciseness of the dynamic object 😉 

### Another workaround?
Is there another workaround I can apply, perhaps hooking into MVC's JSON writer, to solve this across my codebase in a neater fashion?

**Comment by rynowak** [comment]
You should go look at JSON.NET's documentation http://www.newtonsoft.com/json/help/html/Introduction.htm

MVC does not control json serialization, we use JSON.NET. 

You can modify the shared settings like: `services.AddMvc().AddJsonOptions(options => ... );

**Comment by alastairs** [comment]
@rynowak Thanks for the quick reply, and the link to the documentation. It looks as though Json.NET has good support for `ExpandoObject`s out of the box, and a thorough search through the documentation and more widely has not yet turned up anything related to the bug I described above. I've also looked through the options available on `SerialiazerSettings` as you described, to no avail.

Maybe I'm missing something obvious. I'm confused why there is a difference between the output for static objects vs. dynamic objects as described above.

**Comment by rynowak** [comment]
@JamesNK - any thoughts?

**Comment by JamesNK** [comment]
ExpandoObject is a dictionary. There is a flag on NamingStrategy to apply camel casing to dictionary keys to get the behavior you want.

**Comment by alastairs** [comment]
Perfect, that's worked a treat. Thanks @JamesNK! For future reference, I added the following to my `Startup.cs`:

```csharp
services.AddMvc().AddJsonOptions(options =>
{
    var contractResolver = new CamelCasePropertyNamesContractResolver();
    contractResolver.NamingStrategy.ProcessDictionaryKeys = true;
    options.SerializerSettings.ContractResolver = contractResolver;
});
```

**Comment by rynowak** [comment]
Thanks @JamesNK - I'm going to remember `contractResolver.NamingStrategy.ProcessDictionaryKeys = true;` - we get questions about this a lot.
