### ISSUE TITLE
Request.Body consumed even when no action parameter is model bound to body

### ISSUE THREAD

**Issue by gunndabad** [aspnet/Mvc#6530]
We're using a third party library that reads Request.Body from inside an action method. When we have any parameters at all, even if the parameter is not model bound from the body, reads to Request.Body return an empty stream.

```
[HttpPost]
public IActionResult Foo() {
  // Request.Body returns data
}
```

```
[HttpPost]
public IActionResult Foo([FromServices] IWhatever thing) {
  // Request.Body returns an empty stream
}
```

Is this the intended behaviour?

**Comment by rynowak** [comment]
Is the request using content-type: `application/x-www-form-urlencoded` or `multipart/form-data`. If so then it's intended. You can change this behavior by using a resource filter like so: https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Filters/DisableFormValueModelBindingAttribute.cs

**Comment by gunndabad** [comment]
Yeh it's application/x-www-form-urlencoded. Thanks for info.
