### ISSUE TITLE
Move TempDataAttribute into Microsoft.AspNetCore.Mvc namespace

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#6542]
`TempDataAttribute` is used frequently enough that it should live in the Microsoft.AspNetCore.Mvc namespace.

@DamianEdwards

**Comment by rynowak** [comment]
Yes, this is wrong, it should be in `Microsoft.AspNetCore.Mvc`

**Comment by DamianEdwards** [comment]
Is this going to require a templates change then? @danroth27 @rynowak

**Comment by danroth27** [comment]
@Eilon Yeah, we should get into the habit of opening template bugs when we make runtime changes that affect the templates: https://github.com/dotnet/templating/issues/1091
