### ISSUE TITLE
Add RedirectToAction overload that takes no arguments

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#6543]
It's pretty common to have a get and post actions with the same name, where the post action redirects to the get action. We should add a RedirectToAction overload that redirects using the current action name.

**Comment by danroth27** [comment]
Same thing for RedirectToPage

**Comment by Eilon** [comment]
There already is a parameterless `RedirectToPage()`: https://github.com/aspnet/Mvc/blob/579aca0121799cca39fcf1a78425cce1f29d0efd/src/Microsoft.AspNetCore.Mvc.RazorPages/PageModel.cs#L1300

**Comment by Eilon** [comment]
Let's add the new overload. Let's make sure the XML docs for the new method are clear about what the methods does (specifically, that it uses the current request's selected controller/action).

**Comment by kichalla** [comment]
4f18d99d021b33141a8747d63b2303040c8bd9dc
