### ISSUE TITLE
CustomAttributes not accesible via IModelBinderProvider

### ISSUE THREAD

**Issue by soycabanillas** [aspnet/Mvc#6545]
Having this:

    public class UnixDateTimeModelBinderProvider : IModelBinderProvider
    {
        [CanBeNull]
        public IModelBinder GetBinder(
            [NotNull] ModelBinderProviderContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (context.Metadata.UnderlyingOrModelType == typeof(DateTime))
            {
                return new UnixDateTimeModelBinder();
            }

            return null;
        }
    }

I want to choose which IModelBinderProvider to use based on a CustomAttribute, not only the data type, something like this:

    if (context.Metadata.UnderlyingOrModelType == typeof(DateTime))
    {
        if (context.Metadata.CustomAttributes.TypeOf<MyCustomAttribute>.Any)
        {
            return new AnotherDateTimeModelBinder();
        }
        return new UnixDateTimeModelBinder();
    }
    return null;

The problem is that there is no CustomAttributes property on context.Metadata.

After reading [here](http://bradwilson.typepad.com/blog/2010/01/why-you-dont-need-modelmetadataattributes.html) (an old post but still relevant IMHO) why the Attributes/CustomAttributes should not be available by default on the Metadata, I've tried to port the code offered as a guidance without success.

First, the DataAnnotationsModelMetadataProvider is no more #2522. The solution for that specific issue was to implement an IDisplayMetadataProvider, but I think that this doesn't apply in order to make available the CustomAttributes to the IModelBinderProvider. I tried implementing IBindingMetadataProvider, but it doesn't offer a way of getting the CustomAttributes nor putting them in a AdditionalValues to be inspected by the IModelBinderProvider.

What I would like to accomplish here, is to choose an IModelBinder based on information provided by the ApiExplorer or a kind of reflection mechanism that allows me to pick the right IModelBinder based on CustomAttributes.

**Comment by Eilon** [comment]
@dougbu / @rynowak - any idea how to do this w/ attributes from a model binder (provider)?

**Comment by dougbu** [comment]
@soycabanillas use `AdditionalValues`: Add an entry to `context.DisplayMetadata.AdditionalValues` in an `IMetadataDetailsProvider` implementation and read it from `context.Metadata.AdditionalValues` in your `IModelBinderProvider`.

**Comment by rynowak** [comment]
You can also downcast to `DefaultModelMetadata` in your MBP. *attributes* are a detail of the default model metadata provider, if you have a dependency on that, then coupling yourself to that implementation is appropriate.

**Comment by pranavkm** [comment]
Looks like both @dougbu \ @rynowak had suggestions for your original question. Feel free to open a new issue if you have further questions.
