### ISSUE TITLE
IRazorViewEngine.FindView and precompiled Views

### ISSUE THREAD

**Issue by xaph0n** [aspnet/Mvc#6546]
I'm working through a requirement to generate a fairly customized email and instead of using a string builder, I thought I would try to use Razor views to handle the logic of what should be displayed.

I followed along with [this](https://ppolyzos.com/2016/09/09/asp-net-core-render-view-to-string/) resource, which works great until I publish the project.  What I've discovered is that if the views are precompiled (so that the views folder doesn't exist), the razor view engine can't find the view.  

I did take a look in the Website.PrecompiledViews and I see the view there. Also, if I go out to the publish folder and add the views folder and add the view it finds it without issue. 

Github issue that somebody is experiencing the same thing: [github issue](https://stackoverflow.com/questions/40964918/pre-compiled-razor-view-to-string-with-asp-net-core?newreg=a0b063625df949fb8dc89ccd6716d4f4)

Thanks for the help.

**Comment by pranavkm** [comment]
We made a change to precompilation as part of `2.0.0-preview2` that made view lookups case insensitive for precompiled views. Prior to this, on Windows machines, view lookups would have performed case insensitive lookups during build, but once published the precompiled view lookup would have been case sensitive. If you're on older builds, could you ensure if your casing matches the paths on disk? If you're using preview2 or later, a repro app would help.

**Comment by xaph0n** [comment]
Thanks for getting back to me.  Unfortunately it doesn't appear to be a casing issue as the case of path matches.

For reference this is what shows in the object browser for the PrecompiledViews:
AspNetCore._Views_CCP_EmailBodyFees_cshtml
Path of the view:
~/Views/CCP/EmailBodyFees.cshtml
String passed for the search:
CCP/EmailBodyFees

I've also tried each of these for the viewName paramater of IRazorViewEngine.FindView:
~/Views/CCP/EmailBodyFees
~/Views/CCP/EmailBodyFees.cshtml
EmailBodyFees
EmailBodyFees.cshtml

**Comment by pranavkm** [comment]
I looked at the guide that you pointed to and I have a hunch that your search paths aren't working because the `ActionDescriptor` that's passed to `FindView` doesn't have enough metadata to perform a lookup (for instance, the Controller route value isn't set). You should be able to instead use `GetView("/Views/CPP/EmailBodyFees.cshtml")` to lookup a view by an exact path. Relevant code `ViewResult` uses to lookup a view: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ViewResultExecutor.cs#L79-L84. Does that help?

**Comment by xaph0n** [comment]
That seems to be a good hunch.  The view seems to be returning with GetView instead of FindView.  Thank you very much for the help.
