### ISSUE TITLE
Question on Authorize attribute in Razor Pages

### ISSUE THREAD

**Issue by Ponant** [aspnet/Mvc#6550]
I tried to put in the authorize attribute but it somewhat lamentably fails. How do you require authorization/authentication with a redirect to login page with razor pages? The docs do not mention this and they do not mention attribute routing neither.

**Comment by pranavkm** [comment]
Support for filters in PageModels landed as part of 2..0.0 and hasn't made it to any of our public releases. Are you using our nightlies?

**Comment by christiansparre** [comment]
I'm also playing around with the new razor pages bits. Great that it is coming, was trying everything and could not understand what I was doing wrong. @DamianEdwards better not deploy live.asp.net from that preview branch he did on youtube :)

**Comment by rynowak** [comment]
Closing this as the question was answered. Thanks
