### ISSUE TITLE
Question on checkbox behavior on form post

### ISSUE THREAD

**Issue by Elfocrash** [aspnet/Mvc#6551]
So what i have is a form of which one input field is of type checkbox.
This is not bound to a model it is just a normal checkbox input field.
When i post the form i can see this input field's name in the HttpContext.Request.Form only if it is selected and it has the value "on". If i don't select it it doesn't appear at all.
Shouldn't it appear no matter if it is selected on not and have values like "true" or "false"?

**Comment by rynowak** [comment]
Nope. What you're describing is what browsers do.

If you take a look at `@Html.Checkbox` and similar things in MVC, you'll see that we generate an extra hidden field with the value false: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/HtmlHelper.cs#L721

**Comment by Elfocrash** [comment]
But that is true only for the tag and html helper checkboxes that use model binding right?
Not for "raw" checkbox input fields inside a form.

**Comment by rynowak** [comment]
> But that is true only for the tag and html helper checkboxes that use model binding right?
> Not for "raw" checkbox input fields inside a form.

Yep.

The way browsers do checkboxes by default isn't ideal for model binding, that's why we generate the extra field.

Closing since it sounds like this was answered.
