### ISSUE TITLE
Use Microsoft.NET.Sdk isntead of FSharp.NET.Sdk for .net core sdk 2.0

### ISSUE THREAD

**Issue by enricosada** [aspnet/Mvc#6554]
ref test project https://github.com/aspnet/Mvc/blob/9ea37a1bbbb463e70d8cc020659c705a58387c0c/test/WebSites/FSharpWebSite/FSharpWebSite.fsproj

the `fsharp.net.sdk` is deprecated in sdk 2.0, now F# is bundled in `Microsoft.NET.Sdk`, more info in https://github.com/dotnet/netcorecli-fsc/wiki/How-to-migrate-1.0-projects-to-2.0

**Comment by Eilon** [comment]
Given that the F# project isn't in the main solution, and that it was for a limited case, I'm putting this in 2.1.
