### ISSUE TITLE
Searching for `aspnetcore.mvc` doesn't show Microsoft.AspNetCore.Mvc in results

### ISSUE THREAD

**Issue by Mardoxx** [aspnet/Mvc#6557]
1 Open VS2017,
2. search for `aspnetcore.mvc`
3. retrieve useless results!

Not sure how nuget search ranks things... but I'd expect `Microsoft.AspNetCore.Mvc` with 2.4mil (or even `.Core` with 3mil) downloads to rank above some non-ms package with 170 downloads!

**Comment by pranavkm** [comment]
Seems like this is a feedback for the NuGet team. https://github.com/nuget/Home is where you should log this issue.
