### ISSUE TITLE
Add In-Memory and Distributed Cache Attributes

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#6559]
The `[ResponseCache]` only adds caching HTTP headers and does not actually cache the response like the old `[OutputCache]` did. We have the `cache` and `distributed-cache` tag helpers but these are only useful for MVC views. We also have the `IMemoryCache` and `IDistributedCache` services but these will not let you easily cache the response body itself without some effort.

I think there needs to be two attributes `[InMemoryCache]` and `[DistributedCache]` which could use the `IMemoryCache` and `IDistributedCache` services under the covers. These could have similar properties to the `[ResponseCache]` including `CacheProfileName` so that it could be configured elsewhere.

**Comment by rynowak** [comment]
Thanks 👍

**Comment by Tratcher** [comment]
How close does https://github.com/aspnet/responsecaching come to fulfilling your in memory caching requirements? It reacts to the headers set by [ResponseCache].

**Comment by RehanSaeed** [comment]
I had not spotted that `VaryByQueryKeys` had been added in 1.1.0. My only other issue is that nothing is cached if the Authorization HTTP header is present but I'll raise a separate issue for that. Thanks!
