### ISSUE TITLE
Create an @attribute directive that enables adding attributes to the generated class for a Razor view/page

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6562]
Like the title says.

Would be used mostly in Razor Pages to allow addition of filter attributes to generated pages via `_ViewImports.cshtml` so that it wasn't required to put on every `PageModel` separately or via inheritance.

``` html
@page
@attribute Authorize
@attribute MyAwesomeFitlerAttribute("args too")
@model MyPageModel

You need to be authorized to see me
```

@rynowak @ajaybhargavb

**Comment by mkArtakMSFT** [comment]
@DamianEdwards, seems there has been no community interested in this for a while. If you feel strong about this, please let me know and we'll reconsider it.

**Comment by DamianEdwards** [comment]
Folks in the community generally ask a different, scenario-focused question, e.g. can I use authorize attribute on Razor Pages rather than doing it in code? This would enable that.

We should consider what this would like taking into consideration the changes coming in Razor vNext.

**Comment by rynowak** [comment]
Would it make more sense for us to add `@authorize` (and also `@authorize "<policy name>") in 3.0? That would be very scenario focused and wouldn't require a lot of compiler work.

**Comment by rynowak** [comment]
I could also see the feedback from this coming, where people want all of the various other things you can do with authorizeattribute other than setting a policy name.

**Comment by rynowak** [comment]
I could also anticipate users wanting a directive for `@allowanonymous` so that you could put `@authorize` in a view imports

**Comment by DamianEdwards** [comment]
I think you're demonstrating exactly why we thought just allowing attributes would be easier 😊

**Comment by rynowak** [comment]
Well, its not really easier, it's porbably a lot more work. It is more flexible.
