### ISSUE TITLE
Razor compilation - cache?

### ISSUE THREAD

**Issue by dazinator** [aspnet/Mvc#6564]
So my web application references a nuget package, which contains an embedded razor view.

When i build the web application, and look in the bin/debug folder, and look inside the referenced assembly, i can see the view. The model declaration is `@model EditProfileViewModel`

In a much older version of this nuget package, the model declaration used to be `@model IndexViewModel`.
When I run the application and browse to the page I am getting this:

![image](https://user-images.githubusercontent.com/3176632/28382717-030180d2-6cb7-11e7-8783-f3cd457ece8a.png)

It seems to be picking up the older version of this view from somewhere..

Is there some sort of disk based cache that gets used perhaps? Or could, for some reason, the assembly be being loaded from an old nuget package rather than from the referenced assembly that I am expecting?

**Comment by pranavkm** [comment]
We don't have any disk based caching for view compilation. For netcoreapp2.0, the {AppName}.deps.json file in the output directory should tell you the version of packages that are loaded by the application. Can you verify it's referencing the version you expect it to?

**Comment by dazinator** [comment]
Thank you. That's good to know that there is no caching causing this. I'll continue to investigate. I am guessing this must be application code going wrong somewhere as we have a lot of custom stuff in place around view and assembly resolution. I will close for now and raise if I verify an issue.
