### ISSUE TITLE
Unit-testing tag helpers?

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#6567]
I tried to unit-test my tag helper, however, calling Process() with appropriate TagHelperContext & TagHelperOutput does not produce the desired results (we wanted to assert output.Content, however, it is empty). It looks like there is additional magic going on behind the scenes.

We're looking for a way to assert the final HTML the tag helper is producing. How to do that?

We're using ASP.NET Core 1.1 by the way.

**Comment by NTaylorMullen** [comment]
Hi @drauch take a look at some of our TagHelper unit tests [here](https://github.com/aspnet/Mvc/tree/dev/test/Microsoft.AspNetCore.Mvc.TagHelpers.Test). 

If you'd like to assert the final HTML the `TagHelperOutput` is an `IHtmlContent` so you can have it write itself to a `TextWriter` via `WriteTo` to view the final content.
