### ISSUE TITLE
TagHelper & <pre> tag

### ISSUE THREAD

**Issue by hishamco** [aspnet/Mvc#6575]
I come a cross situation to show an TagHelper as html inside `<pre>` tag without render it. Is there a built-in solution to solve this issue?

**Comment by NTaylorMullen** [comment]
@hishamco you can always prefix your TagHelper with a `!` to have it not be a `TagHelper`. Example: `<!environment ...></!environment>`

**Comment by hishamco** [comment]
Yep, but this will not render the TagHelper as it is in the page, I though there another way rather than using html entities `&lt;environment ...&gt;&lt;/!environment&gt;`

**Comment by NTaylorMullen** [comment]
@hishamco not sure I follow then. Could you provide an example?

**Comment by hishamco** [comment]
If you have look to my example here https://github.com/hishamco/My.AspNetCore.Mvc.TagHelpers/blob/master/samples/My.AspNetCore.Mvc.TagHelpers.Sample/Pages/TagHelpers/GravatarTagHelper.cshtml#L7

I'd like to show the user the html markup for the `GravatarTagHelper`, before render that actual tag helper underneath. The result should be like this:
```html
<gravatar email="hishamco_2007@yahoo.com" />
```
The `<pre>` tag is suitable for render the html tags as it's, nothing but the ASP.NET will render the tag helper even it's inside the `<pre>` tag

**Comment by NTaylorMullen** [comment]
@hishamco I'd think that `<!gravatar email="hishamco_2007@yahoo.com" />` would produce the results you're looking for. I assume it does not, so what does it generate?

**Comment by hishamco** [comment]
Yep it generate it in the source file, but it will not render it in the browser

**Comment by Eilon** [comment]
@hishamco you'd need to HTML encode the rendering of the content of the `<pre>` tag for it to render the way you want. I'd recommend writing an additional Tag Helper that HTML encodes its content. In the CSHTML you'd write something like this:

```html
<gravatar email="hishamco_2007@yahoo.com" />

Source:

<pre>
    <html-encode>
        <gravatar email="hishamco_2007@yahoo.com" />
    </html-encode>
</pre>
```

And the new `<html-encode>` tag helper would just take its InnerContent and HTML encode it, and then render it.

**Comment by hishamco** [comment]
Thanks @Eilon, nothing but (me or any developer) will expect a natural behavior which is `<pre>` should render it's content as its instead of doing anything extra

IMHO it will be nice if we can escape the tag helper rendering if it's inside the `<pre>`, something similar to what @NTaylorMullen suggested before by using the `!` operator

**Comment by Eilon** [comment]
`<pre>` still requires that its contents be HTML encoded, that's standard HTML behavior.

BTW I did have a mistake in my previous post (that I've since corrected), which is that the `!` is needed so that the tag helper won't "run" and you just see the markup.

**Comment by hishamco** [comment]
Seems the simplest way is to write a tag helper for `<pre>` and encode it's content

**Comment by Eilon** [comment]
I don't see us ever doing that because that would be a huge break from how HTML works. It's critical for tag helpers that modify existing HTML tags to preserve their semantics. The tag helpers typically only *add* functionality and convenience, they never change the intrinsic behavior of elements.

**Comment by hishamco** [comment]
A useful case for this, if you wanna write docs or lesson about the tag helpers and show the audience how they can use the tag helpers in the markup without render them

**Comment by Eilon** [comment]
Not saying it isn't useful, just that I don't see us shipping such a thing. But feel free to write one 😄

**Comment by hishamco** [comment]
Sure  😄
