### ISSUE TITLE
Attribute to generate “action” method for <form> tag builder (including query string)

### ISSUE THREAD

**Issue by AndreiMaz** [aspnet/Mvc#6576]
The built-in FormTagHelper supports "asp-action", "asp-controller", "asp-route" and other attributes. They work fine. But I don't want to manually specify their values for each form. Is it possible to automatically generate "action" attribute based on the current page URL?

After looking at implementation of FormTagHelper I see it uses IHtmlGenerator. When I manually invoke IHtmlGenerator.GenerateForm(this.ViewContext, null,null,null,"post", null) in my view, then it works just great. The form is generated automatically with a valid "action" method (including query string). But can I get the same result with FormTagBuilder?

According to this implementation I need the following line of code to be invoked in FormTagBuilder. But with "action" and "controller" set to null

```c#
tagBuilder = Generator.GenerateForm(
                        ViewContext,
                        Action,
                        Controller,
                        Fragment,
                        routeValues,
                        method: null,
                        htmlAttributes: null);
```

Looks like `asp-all-route-data="@null"` will work. It looks ugly but it works

It would be great if you can add a new "asp-generate-action" (or any other name) attribute. If set to "true", then it'll automatially generate the "action" attribute of the form

-----

Edited for style only by @Eilon.

**Comment by dougbu** [comment]
@AndreiMaz beyond "looks ugly", what is your objection to `asp-all-route-data="@null"`?

**Comment by AndreiMaz** [comment]
@dougbu it's just undocumented workaround. There should a developer-friendly way to generation "action". For example, "asp-generate-action" (or any other name)

**Comment by Eilon** [comment]
@dougbu - we added this to the new project you created so we can discuss as a group.

This should probably be super easy to add. We could defined a new `asp-self-form` attribute (name TBD) that does exactly what `Html.BeginForm()` does.

**Comment by dougbu** [comment]
@AndreiMaz the browser will always submit to the current URL when the `action` attribute is not specified. Why is an explicit attribute value necessary here?

**Comment by mkArtakMSFT** [comment]
Closing as there was no response for a long period of time. Feel free to reopen this, if you feel it's something you really need.
