### ISSUE TITLE
RPS throughput drops with the increased number of unused assemblies

### ISSUE THREAD

**Issue by KKhurin** [aspnet/Mvc#658]
Repro steps (not super strict from perf perspective but they will demonstrate the problem):
1. Create a simple MVC page (or use MVC music store)
2. Run stress (tinyget5  -l:150000 -r:port### -x:8 localhost /home would do for this demo)
3. Measure the RPS throughput (web service/Get requests/s if hosted in IIS)
4. Create a script that constantly touches index.cshtml file and run it for a while
5. Monitor perf counter for loaded assemblies, wait for the number of assemblies to reach 5K
6. Stop the script that touches .cshtml files and compare the throughput with the doubled number of assemblies

In my simplistic tests I see this:

Assemblies      150
RPS                 270

Assemblies      7500
RPS                 180

I haven't done profiling to determine what causes the degradation but it is very consistent and reproducible.

**Comment by yishaigalatzer** [comment]
@KKhurin is this still a thing?

**Comment by KKhurin** [comment]
Nope. I don't see any obvious drop in the throughput with increased number of loaded assemblies.

I do see the old assemblies and delegates still being referenced but I didn't reach the memory pressure high enough to cause any noticeable effect on performance.
