### ISSUE TITLE
Combination of asp-fallback-href & asp-append-version

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#6583]
Hi!

We're having the following script tag:

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=">

Now we want to use the `asp-append-version` caching feature for the _asp-fallback-src_. How to add asp-append-version without having the version hash on the CDN src as well?

**Comment by pranavkm** [comment]
@drauch adding `asp-append-version` should do exactly what you're asking for. It does append versions to non-disk based resources, but should append a version to the fallback resource on disk. Are you seeing otherwise?

**Comment by drauch** [comment]
Thank you for your answer. This clarifies our question - no, we are not seeing it otherwise, we just weren't sure if the behavior is guaranteed.
