### ISSUE TITLE
.NET Core :  response type always json not xml with ICollection

### ISSUE THREAD

**Issue by xav-stargate** [aspnet/Mvc#6585]
Hey,

I use this contribution for return json or xml depending "Accept" header.
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/formatting

It's work with a simple object, but when I add a ICollection the return is always JSON.
The return type of the controller is IActionResult.
To solve this issue I use List instead of ICollection.

This behaviour is normal ?

Source : https://stackoverflow.com/questions/45281541/mvc-net-core-response-type-always-json-not-xml-with-icollection/45282641#45282641

**Comment by rynowak** [comment]
This can happen if the XML serializer does not support `ICollection<>`. You'll have to refer to the docs for DataContractSerializer or or XmlSerializer for details depending on which one you are using. 

We plan to make this better in the future by adding some logging/diagnostics.
