### ISSUE TITLE
TempDataAttribute should allow the key to be configurable

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#6590]
[TempData("SomeValue")]
public int MyProperty { get; set; }

Temp data attribute should allow for a key that is different from the property name when retrieving data from the temp data dictionary. Other model binders offer this type of lightweight mapping

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/5954 which was closed.

**Comment by javiercn** [comment]
My scenario:
I'm saving a bunch of stuff on TempData using the type name as the key (with nameof)
```
TempData[nameof(Movie)] = sessionAndShow.Show.MovieId;
TempData[nameof(Show)] = sessionAndShow.Show.Id;
TempData[nameof(Session)] = sessionAndShow.Session.Id;
```
When I bind the properties back I want them to be named

```
public int MovieId { get; set; }
public int ShowId { get; set; }
public int SessionId { get; set; }
```

In general, these types of ad-hoc mappings are very common and we should support them in the same way we support them on other model binders. This is an unnecessary restriction on this binding mechanism.

**Comment by Eilon** [comment]
@javiercn in your scenario why are MVC's `TempData` property and Razor Pages' `[TempData]` scenario both being used?

**Comment by javiercn** [comment]
I was trying out things. It could "easily" be an MVC to Razor Page scenario. That said, I think TempData bound properties work in a very specific way, so I'm not sure if allowing a name override would make sense.

**Comment by Eilon** [comment]
Sure, I just think that crossing TempData between those two is a much less important scenario. Is there a problem to solve where it's using only Razor Pages or only MVC?

**Comment by pranavkm** [comment]
This was fixed as part of https://github.com/aspnet/Mvc/commit/ccb67931268f9396652a22044e3563a98b2a5c8f. There's a `Key` property on the attribute that you can optionally set. As of 2.1.0, the keys also default to the property name, without a prefix, so you could do something along the lines of `TempData[nameof(MyModel.PropertyName)]`
