### ISSUE TITLE
Consider making auth for Pages hierarchical.

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#6592]
There is already a strong sense of hierarchy on Razor pages through the filesystem structure.

Based on that, I would like to be able to specialize the auth configuration based on the specificity of the folder. For example:

I would like to express a general auth requirement for my pages (authorize but allow anonymous) and be able to override that requirement for some specific pages/folders (as shown below).

```
rpo.Conventions.AuthorizeFolder("/")
      .AllowAnonymousToFolder("/")
      .AuthorizeFolder("/Subfolder"))
```

The result of the code above would be that /Subfolder always requires the user to be authorized. None of the configurations applied to "/" are applied to pages inde "/Subfolder" because a more specific configuration was defined.

**Comment by hishamco** [comment]
> There is already a strong sense of hierarchy on Razor pages through the filesystem structure.

I'm totally agree with you @javiercn, but the my logical understanding about the setup that you made above is the last call will win

> None of the configurations applied to "/" are applied to pages inde "/Subfolder" because a more specific configuration was defined.

I'm not sure why it should applied to pages inside "/Subfolder"

**Comment by Eilon** [comment]
We need to revisit how authorization combines and stacks. There's potentially a lot we can do here, but it requires some bigger changes to auth processing.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
