### ISSUE TITLE
Provide a scoped way to keep around temp data binded to properties

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#6593]
When TempData is applied to a property there is no way of specifying that you want to keep that property (which makes F5 fail).

Given that the dictionary key for a property marked with TempData can't be computed (the runtime prefixes it in some private way to avoid collisions with user added data) there is no way to just do TempData.Keep("PropertyName") so the attribute should enable this through a property on the attribute.

**Comment by Eilon** [comment]
Hmm does it make sense as a static attribute? I think when you call `Keep()` you want to do it selectively as opposed to statically set on a property.

**Comment by javiercn** [comment]
@eilon you can call Keep(key) but the problem is that when using TempDataAttribute the key is unknown and an implementation detail (there's no guarantee it won't change). Besides that, having it as a property on the attribute keeps all the behavior in one place and makes it declarative which is less error prone.

**Comment by Eilon** [comment]
My point is that I think it's unlikely to want to statically set Keep=true. The scenarios for Keep are generally such that it is a dynamic decision made at runtime. So, I'm not sure having a way of statically setting it would ever be useful.

**Comment by javiercn** [comment]
I don't think it's unreasonable at all wanting to maintain "property behavior" while on a page using TempData. I can come to page A from page B (page A sets some temp data) and want to perform multiple actions on Page A (though handlers) (Post Redirect Get to the same page) and want to keep the data while I'm in that page. The data will dissapear from the tempdata dictionary the next time its ignored or used on a property in a page with keep=false.

We can talk more about this if you want. We discussed it with @pranavkm and @DamianEdwards and makes sense for them.

**Comment by hishamco** [comment]
IMHO it doesn't make sense because the intent of the `TempData` to store the data temporary, on other hand the session state is right option for the case that you proposed

**Comment by Eilon** [comment]
> The data will dissapear from the tempdata dictionary the next time its ignored 

That's not true. TempData sticks around *until it is used*. And that's related to why I think `Keep()` needs to be conditional. You would only set Keep=true if you got TempData **and** you need to redirect to another page and preserve that TempData. In the case where you don't redirect, you must not set Keep=true or else the data will stick around too long.

Can you give a concrete example where you'd always want Keep=true on a property?

**Comment by javiercn** [comment]
@eilon I haven't looked at the implementation, but just based on the first test. What you say it's not true https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.FunctionalTests/TempDataTestBase.cs

**Comment by javiercn** [comment]
I made a fool of myself. The request consumes the data, but tests below it suggest that you keep the data while performing redirects. I'll take a deeper look and come back to it.

**Comment by javiercn** [comment]
Based on discussions and clarifications on how TempData works, what we should do here is provide an imperative API to allow preserving a specific property captured through the TempData attribute, given that the property implicitly reads the data from TempData for binding and that the temp data key is opaque to the user.

**Comment by Eilon** [comment]
This seems more reasonable 😄

**Comment by Eilon** [comment]
We could add an extension method to TempData called `KeepProperty(string propertyName)` (or similar), that applied the same "munging" logic to properties and then called `Keep(string key)` (or whatever).

**Comment by pranavkm** [comment]
As of 2.1.0, the computed key is the property name by default. `ITempDataDictionary.Keep` should work out of the box. Closing since there isn't anything more to do here.

**Comment by javiercn** [comment]
> should work out of the box

Should work or works :trollface:
