### ISSUE TITLE
Provide an easier way to call html helper methods within a tag helper

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#6594]
Right now, you can inject an IHtmlHelper instance on the constructor but it needs to be manually contextualized. We do this for views, so it would be nice to do it for TagHelpers too.

```
((IViewContextAware)Helper).Contextualize(ViewContext); 
```

**Comment by Eilon** [comment]
Though this isn't ideal, there are no plans to make changes in this area.
