### ISSUE TITLE
Error if upgraded to 2.1.0-preview1-26462

### ISSUE THREAD

**Issue by malichishti** [aspnet/Mvc#6595]
Hi,

I have created an empty Web ASP.NET CORE Project using VS2017 15.3
If i update  **Microsoft.AspNetCore.All** to **2.1.0-preview1-26462** i get following error upon running the project:
![image](https://user-images.githubusercontent.com/17155996/28654542-9ba5a67a-72d8-11e7-86a9-ee7e2c820417.png)

**Comment by Eilon** [comment]
Hi @malichishti , do you have the latest .NET Core 2.x preview build as well? I think you'll need that to make sure you have a matching runtime for ASP.NET Core 2.1 preview to run on.

**Comment by malichishti** [comment]
that solved it, thank you.
