### ISSUE TITLE
Consider removing [HttpGet] from Login action in default template to fix infinite redirection loop

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Mvc#6597]
In the default template, `AccountController` has two `Login` actions, one with `[HttpGet]` and the other with `[HttpPost]`. Neither of them accepts HEAD, so if a browser does make a HEAD request to `/Account/Login`, no routes will match.

That's reasonable on its own, but causes problems in conjunction with `MapSpaFallbackRoute`. This will see that no routes have matched, tries to serve a fallback route. If that fallback route itself has `[Authorize]`, then we'll serve a 302 to `/Account/Login`, and hence create an infinite redirection loop. This only affects browsers that make `HEAD` requests (regular `GET`/`POST` isn't affected), but apparently [this does happen sometimes in the wild as reported here](https://github.com/aspnet/JavaScriptServices/issues/1153).

We could avoid this by changing the default template so that, of the two `Login` actions, one still has `[HttpPost]`, but the other has no method filter (and hence would accept `HEAD`, `OPTIONS`, etc.).

This solution seems like it would be fine - I haven't thought of any drawbacks with it. Other solutions such as changing `[Authorize]` or `MapSpaFallbackRoute` to behave differently when they see `HEAD`/`OPTIONS`/etc. requests would be a bigger breaking change, and probably not the right behaviour anyway, since developers would expect those middleware pieces to handle all HTTP methods consistently.

**Comment by rynowak** [comment]
In general it seems like the issue here is that we just flat out have the wrong behavior when we reject a request due to HTTP method mismatch. That would be the biggest breaking change though, so the template change is probably the right one.

**Comment by mkArtakMSFT** [comment]
Hi @SteveSandersonMS.

Closing this issue now, as we've moved all the identity stuff into Razor pages  and the page model will now handle the `HEAD` requests with `OnGet` handler.
