### ISSUE TITLE
Support TempData attribute properties on all activated types

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6601]
The `[TempData]` backed properties are currently only supported on pages and controllers. We should extend it to work on all activated types, including:
- View Components
- Partials 
- Tag Helpers

**Comment by hishamco** [comment]
Can we support complex types to be stored in the `TempData` too?

**Comment by DamianEdwards** [comment]
It's a bit of a Pandora's Box due to the implications of round-tripping objects beyond primitive values. Perhaps we could support POCOs by serializing to JSON, so it would be limited to public primitive members, and perhaps that could be composed via a separate attribute and filter.

**Comment by pranavkm** [comment]
We tried making `ViewData` work on partial models and it turned out to be difficult since we don't manage the type's lifetime. We can consider supporting `TempData` properties on tag helpers if we get enough customer feedback.
