### ISSUE TITLE
Update default Razor search paths to include ~/[PagesRoot]/Shared

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6604]
Based on feedback, I'd like to update the default Razor search paths.

We should add *~/[PagesRoot]/Shared/* to the search paths for Layouts, Partials, and Field Templates. This should be true whether searching from the context of a rendered Page or View. When searching from a Page, this path should be **before** *~/Views/Shared/*, and when searching from a View it should be **after** *~/Views/Shared/*.

**Comment by hishamco** [comment]
Happy to heard that, I faced this issue long time back in my [Bloggy](https://github.com/hishamco/bloggy) repo, when I blogged about Theming support in RazorPages
