### ISSUE TITLE
Provide a way within the Page/PageModel to run code before any handler runs

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#6606]
MVC controllers have a similar feature in which a controller implements IActionFilter and you can override OnActionExecuting and OnActionExecuted to do something before and after any action runs in the context of the controller.

This is even more useful in pages as many of the pages are "task" oriented and the initialization logic is likely to be repeated on get and post requests.

**Comment by hishamco** [comment]
@javiercn you can do what you want in different ways:

1- Have a look to this https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.RazorPages/Filters/IPageFilter.cs, 

2- Also you can extend the `PageModel` and run your code before the handlers

**Comment by javiercn** [comment]
To be clear, I want PageModel to implement IPageFilter or have the framework consider the Page a filter if it implements IPageFilter. in the exact same way Controllers are action filters.

The advantage of doing this is that your filter is limited to handlers in your page and you can take advantage of everything on the PageModel (DI services, model bound properties, etc.) without having to perform casts.

**Comment by rynowak** [comment]
The plan here for 2.1.0 is to allow your page model to implement a page filter. This fills the scenario to initialize some state without the need for a new concept
