### ISSUE TITLE
Consider renaming RequestSizeLimit to RequestBodySizeLimit

### ISSUE THREAD

**Issue by jkotalik** [aspnet/Mvc#6610]
The attribute name "RequestSizeLimit" seems to imply that the whole HttpRequest size is checked, rather than just the body size. Similar naming conventions are used by both Kestrel and HttpSys.

**Comment by Eilon** [comment]
I assume that would be a breaking change?

**Comment by halter73** [comment]
It could be done in a non-breaking way by deprecating the old attribute and adding an identical attribute with a new name. I'm not sure whether it's worth it though.

**Comment by Eilon** [comment]
Yeah we couldn't do the full fix until 3.0... how important is this?

**Comment by jkotalik** [comment]
Probably not very important. I just found a discrepancy and wanted to point it out.

**Comment by jkotalik** [comment]
I'd say either leave it for 3.0 or disregard it.

**Comment by Eilon** [comment]
Yeah this would be a "correct" change but at this point it's not worth it.
