### ISSUE TITLE
Run functional tests (web tests) without disabling shadow copying

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#6613]
We really like being able to compile while running our tests in the background. However, if we disable shadow copying in our tests we run into https://github.com/aspnet/Razor/issues/1212 . The workaround presented in that issue works, however, it includes disabling shadow copying which is a real downer.

According to https://github.com/aspnet/Mvc/issues/6233 there should be a fix in 2.x, but as far as I can see (e.g., here: https://github.com/aspnet/Mvc/commit/35152d5933ca885aaa3633301d344e7a58b20cd7) shadow copying still needs to be disabled.

Can anyone elaborate WHICH assemblies have to be loaded in our web tests so that Razor can find the necessary dependencies?

If it is of any help: we are targeting ASP.NET Core 1.1 and .NET Framework(!) 4.7.

**Comment by drauch** [comment]
I've found that the following hackaround (code must run before web application is started):

      var webClientAssembly = typeof (Startup).Assembly;

      // The path where the shadow copy of the assembly resides
      var webClientAssemblyLocationDirectory = Path.GetDirectoryName(webClientAssembly.Location).AssertNotNull();

      // The original path from where the assembly has been loaded
      var webClientAssemblyCodeBaseDirectory = Path.GetDirectoryName(new Uri(webClientAssembly.CodeBase).AbsolutePath).AssertNotNull();

      var depsFileName = $"{webClientAssembly.GetName().Name}.deps.json";
      var depsFile = new FileInfo(Path.Combine(webClientAssemblyCodeBaseDirectory, depsFileName));
      if (!depsFile.Exists)
      {
        throw new InvalidOperationException(
          $"Can't find '{depsFile}'. This file is required for Razor to know the compilation context. There should"
          + "be a copy of the file in your web client\'s bin directory.");
      }

      // Copy deps file to shadow copy location
      File.Copy(depsFile.FullName, Path.Combine(webClientAssemblyLocationDirectory, depsFile.Name));

Is there any catch with this solution? Any counter arguments, or hints as to why we would run into troubles later on?

**Comment by rynowak** [comment]
The reason to disable shadow copying is that ASP.NET Core needs access to static files, views, and the `.deps.json` file to function correctly. What you have here basically looks the same to me as the MSBuild snippet from this example https://github.com/aspnet/Razor/issues/1212#issuecomment-297885722

```
<!--
    Work around https://github.com/NuGet/Home/issues/4412. MVC uses DependencyContext.Load() which looks next to a .dll
    for a .deps.json. Information isn't available elsewhere. Need the .deps.json file for all web site applications.
  -->
  <Target Name="CopyDepsFiles" AfterTargets="Build" Condition="'$(TargetFramework)'!=''">
    <ItemGroup>
      <DepsFilePaths Include="$([System.IO.Path]::ChangeExtension('%(_ResolvedProjectReferencePaths.FullPath)', '.deps.json'))" />
    </ItemGroup>

    <Copy SourceFiles="%(DepsFilePaths.FullPath)" DestinationFolder="$(OutputPath)" Condition="Exists('%(DepsFilePaths.FullPath)')" />
  </Target>
```

Can you be specific about what problems you are having with shadow copying off?

**Comment by drauch** [comment]
Static files and views should be accessible by setting the appropriate content root path, so this should not affect shadow copying.

The reference assemblies should be - if loaded correctly - shadow copied as well, so I don't really see why this should be a blocker for shadow copying. Indeed, manually searching for assemblies must be done relative to the original assemlby's CodeBase not its Location (maybe that's the bug?).

The MSBuild snippet shown by you is not enough, we have it in place as well. It ensures that the deps.json file is being copied to the build output of the integration test project (normally it would only be in the build output of the SUT (the web project), and would not be copied to the integration test project although the integr. test project depends on the web project). So this manual MSBuild task copies the deps.json file by hand to the integration test project's output folder. However, that's not enough, at the momennt I still have to copy the deps.json file to the shadow copy location, which should normally not be necessary.

**Comment by rynowak** [comment]
OK, well based on the points here it sounds like you understand what's required to make this work for you.

**Comment by drauch** [comment]
Yes, as I stated in my initial post I've found a workaround to my problem. Still I have these two open questions:

1) Is this actually a problem in the Razor engine and should be fixed, so that such a workaround is no longer necessary?

2) Is my workaround feasible in the eyes of you insiders. Does the approach _really_ work, or is it just enough to run my first tests and I will run into troubles later on?

**Comment by rynowak** [comment]
> Is this actually a problem in the Razor engine and should be fixed, so that such a workaround is no longer necessary?

This is a fundamental requirement. The deps file needs to be present so that we can find the compilation settings and reference assemblies to use. Our test package that we're developing will include this snippet of msbuild code by default so that you don't have to put it everywhere, but the deps file always needs to be present.

> Is my workaround feasible in the eyes of you insiders. Does the approach really work, or is it just enough to run my first tests and I will run into troubles later on?

It sounds to me like you've covered everything. This approach should work fine. Everything here is just files on disk, so as long as you're willing to make sure that those files are also copied to the right places, that should be fine.

**Comment by drauch** [comment]
Ad 1) I'm afraid you missed my point. Is it a bug, that the assembly is trying to locate the deps file / its references at the assembly's _Location_ instead of the assembly's _CodeBase_ (which seems to be the case, as the deps file is found only if copied to the shadow copy location manually).

Ad 2) OK, let's hope so...

**Comment by rynowak** [comment]
Ah yes I was missing the point on that. Let me check on that and see what I can find out

**Comment by pranavkm** [comment]
Looping in @eerhardt since the deps file discovery is in DependencyModel. Should https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.Extensions.DependencyModel/DependencyContextLoader.cs#L118 use `Assembly.CodeBase` instead of `Assembly.Location` to support shadow copy scenarios?

**Comment by Eilon** [comment]
@pranavkm what further action is required from us here? Do we need to file bugs elsewhere? Any code changes or investigations left for us to do?

**Comment by pranavkm** [comment]
Ping @eerhardt . Should https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.Extensions.DependencyModel/DependencyContextLoader.cs#L118 use `Assembly.Codebase` to support shadow copied binaries?

**Comment by eerhardt** [comment]
I'm not sure, it's been like that since the beginning:  https://github.com/dotnet/core-setup/commit/7ce1e267f7d922e014c668d901a2e5a16f3fddf3.

Can you open a bug in core-setup for it?  We can evaluate it there.

**Comment by pranavkm** [comment]
Done - https://github.com/dotnet/core-setup/issues/3308. Closing this since there's nothing further to do from our end.
