### ISSUE TITLE
Input tag helper doesn't set the value field on inputs with type month correctly.

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#6615]
Razor code:
```
<input type="month" asp-for="Checkout.CreditCardDetails.Expires" value="@Model.CurrentCustomer?.CreditCard?.Expires" />
```

Html generated:
```
 <input type="month" value="12/1/2019 12:00:00 AM -08:00" data-val="true" data-val-required="The Expires field is required." id="Checkout_CreditCardDetails_Expires" name="Checkout.CreditCardDetails.Expires" />
```

Error in chrome: 
```
The specified value "12/1/2019 12:00:00 AM -08:00" does not conform to the required format.  The format is "yyyy-MM" where yyyy is year in four or more digits, and MM is 01-12.
```

**Comment by Eilon** [comment]
What does your data look like for the `Expires` property? Is it an int or a string? Or is it a DateTime? If it's a DateTime, which it seems like given the error you have, I would fully expect this: you're passing in an entire date where only a month is needed. Perhaps pass in `@Model.CurrentCustomer?.CreditCard?.Expires.Month`? Though, I'd warn that using a `DateTime` (or `DateTimeOffset`) is probably not the right data structure. You probably want two `int` properties, one for Year, one for Month.

**Comment by javiercn** [comment]
@eilon I don't agree. DateTimeOffset is the right structure to represent a point in time (in this case with year and month accuracy). Representing a month and a year with two integers is devoid of any semantics and places a lot of burden on the developer (you need to do all the validation, parsing, etc yourself).

type=month with a given datetime or datetimeoffset should just render the month and year of that date correctly. The data is sent by the HTML5 control in the right way, but its not formatted in the correct way by the server when generating the HTML and this causes the data to not roundtrip. You can workaround it by formatting the data with ToString("yyyy-MM") but the control should do it automatically for you.

**Comment by Eilon** [comment]
Ah, you know what, it appears I had a misconception about the month picker. It's actually a year+month picker. Thanks, HTML5!

I agree we should format this data type correctly for that HTML5 input type. We already do similar things for other date-related inputs.

**Comment by javiercn** [comment]
@Eilon Should we also support input type=week?

**Comment by Eilon** [comment]
@javiercn seems reasonable.

**Comment by jbagga** [comment]
Filed the issue [here ](https://github.com/aspnet/Mvc/issues/7034) to support "week"
