### ISSUE TITLE
Alternatives to authentication branching

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Mvc#6617]
I guess the most popular usage of authentication branching was to disable automatic challenge for a particular paths. How can it be achieved now?

Maybe adding a property to AuthorizeAttribute will be the case? Or some kind of authorization filter that will have a predicate to determine if challenge required?

@HaoK, @PinpointTownes, what do you think?

**Comment by Eilon** [comment]
@xperiandri can you share more info about what you are trying to achieve?

**Comment by xperiandri** [comment]
@Eilon, enable automatic challenge for some path like [here](https://github.com/openiddict/openiddict-core/blob/release/samples/Mvc.Server/Startup.cs#L150)

``` C#
app.UseWhen(context => context.Request.Path.StartsWithSegments("/api"), branch =>
{
    // Add a middleware used to validate access
    // tokens and protect the API endpoints.
    branch.UseOAuthValidation();
});

app.UseWhen(context => !context.Request.Path.StartsWithSegments("/api"), branch =>
{
    branch.UseIdentity();

    branch.UseGoogleAuthentication(new GoogleOptions
...
});


```

**Comment by davidfowl** [comment]
@xperiandri The recommendation is to use auth schemes to target specific scenarios like this instead of forking the middleware pipeline.

**Comment by xperiandri** [comment]
Is there a sample?
Do you mean like for API use Bearer scheme but for View use Cookie scheme?

**Comment by davidfowl** [comment]
> Do you mean like for API use Bearer scheme but for View use Cookie scheme?

Yes.

> Is there a sample?

I scanned docs.asp.net and I can't find a sample anywhere 😞 . The dev branch of openiddict-core has a sample:

https://github.com/openiddict/openiddict-core/blob/b7359dd93d6b81cb0268eb60c9d68d6340429b71/samples/Mvc.Server/Controllers/ResourceController.cs#L20

https://github.com/openiddict/openiddict-core/blob/b7359dd93d6b81cb0268eb60c9d68d6340429b71/samples/Mvc.Server/Controllers/UserinfoController.cs#L25

/cc @blowdart @Tratcher @HaoK

**Comment by HaoK** [comment]
See https://github.com/aspnet/AuthSamples/tree/dev/samples/VirtualSchemes.PathSchemeSelection which will be the new sample for how to pick auth scheme based on a per request basis
