### ISSUE TITLE
Relevant message must be logged when AddAuthorization is missing and AuthorizeAttribute is used

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Mvc#6618]
Why the hell `Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler:Information: Identity.Application was not authenticated. Failure message: Unprotect ticket failed` message is logged when `AddAuthorization` has not been called after `AddMvcCore`???

Why CookieAuthenticationHandler exists in pipeline at all?
I did specify scheme!
``` C#
[Authorize(AuthenticationSchemes = OAuthValidationDefaults.AuthenticationScheme)]
[HttpGet("~" + Routes.UserInfoEndpoint), Produces("application/json")]
[ProducesResponseType(typeof(JObject), (int)HttpStatusCode.OK)]
[ProducesResponseType(typeof(OpenIdConnectResponse), (int)HttpStatusCode.BadRequest)]
public async Task<IActionResult> UserInfo()
```

I'd searched for 2 days why `OAuthValidation` did not work. Thanks to @PinpointTownes that he noticed which causes the issue.

**Comment by rynowak** [comment]
`AddMvcCore` is the minimal possible MVC configuration, it does not include authz.

**Comment by xperiandri** [comment]
@rynowak, that is why I ask how `CookieAuthenticationHandler` can be called

**Comment by PinpointTownes** [comment]
> AddMvcCore is the minimal possible MVC configuration, it does not include authz.

IMHO, it really should, for 3 reasons:
  - The authorization components are already part of the Core package. Updating `AddMvcCore()` to register the authorization filter by default wouldn't require changing the existing layering.
  - It makes "MVC Core core" not super safe OOTB, as authentication can't be enforced using `[Authorize]` if `AddMvcCore().AddAuthorization()` is not explicitly called.
  - It's an insanely common source of pain, which is extremely hard to debug for beginners.

**Comment by Eilon** [comment]
@PinpointTownes the `AddMvcCore()` method is a very, *very* low-level API, used for only the most advanced scenarios that require using the most basic building blocks of MVC. If we add too much to it, we'll get requests for `AddMvcCoreCore()` 😄 

I think usually when we see someone calling `AddMvcCore()`, there's no good reason for it, and `AddMvc()` is the better API to use.

Is there a particular reason to use `AddMvcCore()` in this scenario? What "extra" parts of MVC are problematic?

**Comment by PinpointTownes** [comment]
> @PinpointTownes the AddMvcCore() method is a very, very low-level API, used for only the most advanced scenarios that require using the most basic building blocks of MVC.

I don't doubt it is, but unfortunately that's not really how it's perceived by many (most?) people, who often consider it as an _à la carte_ extension that allows them to selectively reference and register the packages/components they need :sweat_smile: 

> I think usually when we see someone calling AddMvcCore(), there's no good reason for it, and AddMvc() is the better API to use.

"good reason" sounds like a subjective concept to me :sweat_smile:

AFAICT, `AddMvcCore()` is often used by API writers to register MVC's core components without all the views/Razor stuff, which helps make apps lighter and reduce their memory footprint. It's a personal jugement, but that really seems a strong reason to avoid using `AddMvc()`.

**Comment by xperiandri** [comment]
> AFAICT, AddMvcCore() is often used by API writers to register MVC's core components without all the views/Razor stuff, which helps make apps lighter and reduce their memory footprint.

I do that exactly because of this reason

**Comment by davidfowl** [comment]
Maybe we need another method `AddMvcApi()` 😄

**Comment by Eilon** [comment]
Indeed, would adding an `AddMvcApi()` method resolve this situation?

Somewhat of an aside: I see claims such as "to reduce memory usage" but they're rarely substantiated. I just made a simple app using ASP.NET Core 2.0.0 Preview 2 default MVC template. I compared using `return Content("Hi!!!");` from the `HomeController` between `AddMvc()` and `AddMvcCore()` (running in "Production" env), and then made a few requests to the site from a browser. These are the results:

| API  | Working Set  | Private Bytes |
|---|---|---|
| `AddMvc()`  | 49MB  | 18MB  |
| `AddMvcCore()`  | 38MB  | 14MB  |

So, while there's clearly a difference between the two, bear in mind that in the `AddMvcCore()` case I didn't "add anything back," such as auth, so the real world difference should end up being somewhat smaller. Though, the difference in private bytes was already very small in absolute terms. Of course, if you *actually* render views, it's certainly heavier.

**Comment by xperiandri** [comment]
Nevertheless message is irrelevant and if authorization is not added calling `CookieAuthenticationHandler` looks strange

**Comment by PinpointTownes** [comment]
> Though, the difference in private bytes was already very small in absolute terms.

Well, in relative terms, it's a `+~29%` overhead when using `AddMvc()` :sweat_smile:

But you're probably right, it's likely not worth it in most cases (except maybe when you deploy your app on memory/disk-limited devices like Raspberry-like micro-machines).

In the future, maybe it would be a good idea to update `AddMvcCore()`'s to reflect what you said?

**Comment by Eilon** [comment]
@xperiandri I agree the message is not great in that scenario. Can you show us the relevant parts of your Startup.cs so that we can replicate the behavior and figure out a solution?

@PinpointTownes I agree we can make the message in AddMvcCore clearer. I logged https://github.com/aspnet/Mvc/issues/6632 to improve those comments.

**Comment by xperiandri** [comment]
Try sample from OpenIddict
https://github.com/openiddict/openiddict-core/tree/dev/samples/Mvc.Server

Just call
``` C#
.AddMvcCore(config => config.ReturnHttpNotAcceptable = true)
    .AddFormatterMappings()
    .AddDataAnnotations()
    .AddJsonFormatters()
```
instead of `AddMvc()`
And then try to call API


My configuration
``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Boilerplate.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Aistant.Auth
{
    /// <summary>
    /// The main start-up class for the application.
    /// </summary>
    public class Startup
    {
        /// <summary>
        /// Gets or sets the application configuration, where key value pair settings are stored. See
        /// http://docs.asp.net/en/latest/fundamentals/configuration.html
        /// </summary>
        private readonly IConfiguration _configuration;

        /// <summary>
        /// The environment the application is running under. This can be Development, Staging or Production by default.
        /// To set the hosting environment on Windows:
        /// 1. On your server, right click 'Computer' or 'My Computer' and click on 'Properties'.
        /// 2. Go to 'Advanced System Settings'.
        /// 3. Click on 'Environment Variables' in the Advanced tab.
        /// 4. Add a new System Variable with the name 'ASPNETCORE_ENVIRONMENT' and value of Production, Staging or
        /// whatever you want. See http://docs.asp.net/en/latest/fundamentals/environments.html
        /// </summary>
        private readonly IHostingEnvironment _hostingEnvironment;

        /// <summary>
        /// Gets or sets the port to use for HTTPS. Only used in the development environment.
        /// </summary>
        private readonly int? _sslPort;

        /// <summary>
        /// Initializes a new instance of the <see cref="Startup"/> class.
        /// </summary>
        /// <param name="configuration">
        /// Application configuration properties.
        /// </param>
        /// <param name="env">
        /// The environment the application is running under.
        /// This can be Development, Staging or Production by default.
        /// </param>
        public Startup(IConfiguration configuration, IHostingEnvironment env)
        {
            _configuration = configuration;
            _hostingEnvironment = env;
            _sslPort = configuration.GetValue<int>("iisSettings:iisExpress:sslPort");

            Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter.IsTracingDisabled = true;
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddCaching()
                .AddCustomOptions(this._configuration)
                .AddCustomRouting()
                .AddResponseCaching()
                .AddCustomResponseCompression(this._configuration)

                .AddDbContext<ApplicationDbContext>(options =>
                {
                    options.UseInMemoryDatabase("Aistant.Auth");
                    options.UseOpenIddict<AistantApplication, AistantAuthorization, AistantScope, AistantToken, Guid>();
                })

                .AddIdentity<ApplicationUser, UserRole>()
                    .AddEntityFrameworkStores<ApplicationDbContext>()
                    .AddDefaultTokenProviders()
                    .Services

                .AddAuthentication()
                    .AddOAuthValidation()
                    .Services

                .AddOpenIddict()

                .AddMvcCore(config => config.ReturnHttpNotAcceptable = true)
                    .AddFormatterMappings()
                    .AddDataAnnotations()
                    .AddJsonFormatters()
                    .AddCustomJsonOptions()
                    .AddCustomCors()
                    .AddCustomMvcOptions(this._configuration, this._hostingEnvironment)
                    .Services

                .AddScoped<IUserClaimsPrincipalFactory<ApplicationUser>, UserClaimsPrincipalFactory>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app
                // Require HTTPS to be used across the whole site. Also set a custom port to use for SSL in
                // Development. The port number to use is taken from the launchSettings.json file which Visual
                // Studio uses to start the application.
                .UseRewriter(
                    new RewriteOptions().AddRedirectToHttps(StatusCodes.Status301MovedPermanently, this._sslPort))
                .UseResponseCaching()
                .UseResponseCompression()
                .UseCors(CorsPolicyName.AllowAny)
                .UseIf(env.IsDevelopment(),
                    x => x
                        .UseDebugging()
                        .UseDeveloperErrorPages())
                .UseStrictTransportSecurityHttpHeader()
                .UsePublicKeyPinsHttpHeader()
                .UseAuthentication()
                .UseMvc()
                .UseWelcomePage(new PathString("/"));

            app.ApplicationServices.InitializeUsersAsync().GetAwaiter().GetResult();
            app.ApplicationServices.InitializeAppsAsync(System.Threading.CancellationToken.None).GetAwaiter().GetResult();
        }
    }
}
```

``` C#
public static IMvcCoreBuilder AddCustomJsonOptions(this IMvcCoreBuilder builder)
 => builder.AddJsonOptions(
        options =>
        {
            // Parse dates as DateTimeOffset values by default. You should prefer using DateTimeOffset over
            // DateTime everywhere. Not doing so can cause problems with time-zones.
            options.SerializerSettings.DateParseHandling = DateParseHandling.DateTimeOffset;
            // Output enumeration values as strings in JSON.
            options.SerializerSettings.Converters.Add(new StringEnumConverter());
        });

public static IMvcCoreBuilder AddCustomMvcOptions(
    this IMvcCoreBuilder builder,
    IConfiguration configuration,
    IHostingEnvironment hostingEnvironment)
 => builder.AddMvcOptions(
        options =>
        {
            // Controls how controller actions cache content from the config.json file.
            var cacheProfileSettings = configuration.GetSection<CacheProfileSettings>();
            foreach (var keyValuePair in cacheProfileSettings.CacheProfiles)
            {
                options.CacheProfiles.Add(keyValuePair);
            }

            if (hostingEnvironment.IsDevelopment())
            {
                // Lets you pass a format parameter into the query string to set the response type:
                // e.g. ?format=application/json. Good for debugging.
                options.Filters.Add(new FormatFilterAttribute());
            }

            // Check model state for null or invalid models and automatically return a 400 Bad Request.
            options.Filters.Add(new ValidateModelStateAttribute());

            // Remove string and stream output formatters. These are not useful for an API serving JSON or XML.
            options.OutputFormatters.RemoveType<StreamOutputFormatter>();
            options.OutputFormatters.RemoveType<StringOutputFormatter>();

            // Returns a 406 Not Acceptable if the MIME type in the Accept HTTP header is not valid.
            options.ReturnHttpNotAcceptable = true;
        });
```

**Comment by mkArtakMSFT** [comment]
Hi.

Closing this issue as the linked issue is now complete. If you think there's some other action missing here, please reopen this issue and we can continue the discussion.
