### ISSUE TITLE
DefaultControllerFactory should throw if the controller is a value type

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#662]
Might want to expand it to include more things (static \ abstract) etc and provide a meaningful message.

**Comment by Eilon** [comment]
I'm not sure it's that important to throw for value types, because who would do that. But other cases such as generic types, abstract types, etc. we should look at to ensure we're safe and provide good errors.

**Comment by rynowak** [comment]
Keep in mind that this will only happen if you build your own action descriptors. We already filter out all of these kinds of things during discovery.
