### ISSUE TITLE
How can I append version to razor code block paths

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Mvc#6620]
I need to append the version to the following paths, and I have to use razor code blocks due to the conditional comments preventing the HTML being parsed:

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        
        
        
        <link rel="stylesheet/less" href="~/less/site.less" />
        

How can I achieve this?

I know for the last link element I can do the following:
`<link rel="stylesheet/less" href="~/less/site.less" asp-append-version="true" />`

But I have no way of appending the version to the other link elements.

**Comment by pranavkm** [comment]
> I have to use razor code blocks due to the conditional comments preventing the HTML being parsed

@NTaylorMullen is this a known issue?

**Comment by Matthew-Bonner** [comment]
In my view Razor is working as expected, I wouldn't expect Razor to parse comments and that is exactly what conditional comments are. The problem here is that File​Version​Provider is internal, and is hard to inject into a Razor template because of the dependencies that need to be fulfilled.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen is this a known issue?

Ya, as of today this is by-design. In Razor we parse the comments but we don't truly understand the browser switches that you're using. To workaround your issue you can utilize `@Html.Raw("<!--[if lt IE 9]>")` and so forth.

**Comment by Matthew-Bonner** [comment]
The workaround works but reduces the legibility of the HTML:

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        @Html.Raw("")
        @Html.Raw("")
        
        <link rel="stylesheet/less" href="~/less/site.less" asp-append-version="true" />

**Comment by Matthew-Bonner** [comment]
Happy to close if there are no plans to change this.

**Comment by NTaylorMullen** [comment]
Ya this is a bit out of scope for us. Thanks for understanding 😄
