### ISSUE TITLE
AuthorizeFilter always returns 401

### ISSUE THREAD

**Issue by epot** [aspnet/Mvc#6622]
I added a dummy AuthorizationHandler with a IAuthorizationRequirement that does not do anything, but the code is never reached and asp.net core returns a 401 without any details. I read https://stackoverflow.com/questions/37276005/asp-net-core-policy-based-authorization-ends-with-401-unauthorized but my case seems to be different as my user is authenticated after exiting the AuthenticationHandler callback. Can I debug somehow what is happening?

**Comment by epot** [comment]
I found the following logs:

Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed for user: exxxx@xxxx.com.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult: Information: Executing ChallengeResult with authentication schemes ().
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Executed action Gna.Controller.test (Gna) in 28.5914ms

**Comment by Eilon** [comment]
This issue was moved to aspnet/Security#1350
