### ISSUE TITLE
Support the use of nameof with Controller methods such as RedirectToAction

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Mvc#6624]
In a controller action, I would like to be able to do the following:
return RedirectToAction(nameof(WelcomeController.Index), nameof(WelcomeController));

So that when a controller or action name changes, Visual Studio can update the code, making changes to the codebase less likely to break anything.

If you are happy for me to do so, I will create a PR which takes the name of the controller and if it ends with "Controller" the text is truncated.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/5853.
