### ISSUE TITLE
Microsoft.AspNetCore.SpaServices 1.1.1- MapSpaFallbackRoute is not using Attribute routing

### ISSUE THREAD

**Issue by Meyhem** [aspnet/Mvc#6626]
Hi. I am attempting to use fallback route for SPA app (Angular 4) with MapSpaFallbackRoute.
When destination Action is using routing by Attributes the SPA handler appears to do nothing and server is returning 404. 
Sample routing config:
```
app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}");
    routes.MapSpaFallbackRoute(
        name: "spa-fallback",
        defaults: new { controller = "Home", action = "Index" });
});
```
And designated controller implementation:
```
[Route("/")]
public class HomeController : Controller
{
    [Route("")]
    public IActionResult Index()
    {
        return File("ngdist/index.html", "text/html");
    }
}
```
However when I remove the attribute routing, fallback route is working just fine. The 'default' route mapped with MapRoute appears to have no effect in this issue (tested without it).

**Comment by Eilon** [comment]
Hi @Meyhem , attribute routing and "conventional" routing are mutually exclusive when it comes to matching controller actions. That is, a given controller action will be handled by only one or the other, and never both.

So, in your case the fix would be to remove the attribute routes from the controller and action to enable the conventional MapSpaFallbackRoute to handle it.
