### ISSUE TITLE
Make AddMvcCore() API summary clearer

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#6632]
These two overloads could use some better text:

1. https://github.com/aspnet/Mvc/blob/17f6b17a6dc0e76606b091187a4e43a184656c89/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L32-L34
2. https://github.com/aspnet/Mvc/blob/17f6b17a6dc0e76606b091187a4e43a184656c89/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L94-L96

The summary description should be clearer about what it does, and perhaps about what it doesn't do. Perhaps saying something like, "services such as authorization, views, X, Y, Z need to be added explicitly."

Note: This came about from https://github.com/aspnet/Mvc/issues/6618

**Comment by rynowak** [comment]
257d202a14e5ae1a0f66f7b4636acb86ab0f47bc
