### ISSUE TITLE
API endpoint only accepts GET when it should accept POST

### ISSUE THREAD

**Issue by yongjp94** [aspnet/Mvc#6636]
Upon days of investigation and posting on online forums, I feel that this may be a bug.
I have attached a link to a stackoverflow question that I posted regarding this problem.

https://stackoverflow.com/questions/45553296/api-endpoint-only-allows-get-when-it-should-take-post

Thank you.

**Comment by pranavkm** [comment]
Seems like this was an issue with Web API 2.0 (and not Asp.Net Core Mvc). If so, https://github.com/aspnet/aspnetwebstack would be the right place to file this issue.

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetWebStack#55
