### ISSUE TITLE
Allow a controller to exist in multiple areas

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Mvc#6637]
At present a controller may only exist in a single area using the AreaAttribute; it would be good to allow a controller to exist in multiple areas and/or all areas, instead of having to create a Controller that derives from a base class for each area.

**Comment by Eilon** [comment]
I don't believe we have any plans to support this, it hasn't been a common request. Usually people dislike the old MVC1-5 behavior where by mistake a controller might end up in multiple areas!

@rynowak thoughts on this?

**Comment by grahamehorner** [comment]
@Eilon if you could decorate a controller explicitly with multiple areas that would be great, or would it be better to have multiple route for the same controller with a prefix that is the same as a area or a preminant redirect?

**Comment by Eilon** [comment]
@grahamehorner I'll discuss with the team and we'll get back to you.

**Comment by rynowak** [comment]
You can do this btw with a convention. /cc @jbagga - relevant to your work

**Comment by Eilon** [comment]
Ah, if we have a neat snippet of code that does this, I think that's ok for now. This isn't an area (*ahem*) that we've gotten a lot of feedback on, so a sample might be sufficient in the meantime.

**Comment by Eilon** [comment]
Assigning to @jbagga to come up with a sample (if possible!).

**Comment by rynowak** [comment]
Yep. My hope is that we can make a quick sample and then use it as a test. @jbagga - I'm on the hook to help out with this if you get stuck

**Comment by jbagga** [comment]
Working on a sample

**Comment by jbagga** [comment]
@grahamehorner Here is the sample https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.ControllerForMultipleAreasSample

Closing for now since we have a sample that addresses the issue.
