### ISSUE TITLE
Razor view @model bug in Preview 2

### ISSUE THREAD

**Issue by nickalbrecht** [aspnet/Mvc#6641]
I have a view that uses the following model definition
`@model KeyValuePair<string, string>?`

I use ? because KeyValuePair is a struct and I need it to be nullable. This worked in 1.1 but I just tried to upgrade my site to Preview 2 to see if there are any bugs, and I'm getting the following error on the `?` character

> Unexpected literal following the 'model' directive. Expected 'line break'.

Note, that as a work around, I can define my model as `@model Nullable<KeyValuePair<string, string>>` instead, it just means I have to change all of my views and this seems like an unintended change in the new version.

**Comment by pranavkm** [comment]
cc @NTaylorMullen \ @ajaybhargavb

**Comment by ajaybhargavb** [comment]
I can reproduce this. Looking in to it.

**Comment by ajaybhargavb** [comment]
Moved this to https://github.com/aspnet/Razor/issues/1607 as this is a Razor parser issue.
