### ISSUE TITLE
IActionResult Un-necessary Casting with Ternary Expression

### ISSUE THREAD

**Issue by napalm684** [aspnet/Mvc#6642]
The following webapi method does not behave with a ternary (I believe this to be incorrect).

Nuget Version: Microsoft.AspNetCore.Mvc v1.1.3

```
        [HttpPost]
        [Route("{id:int}/notes")]
        public IActionResult CreateNote([FromRoute] int id, [FromBody] Dtos.NoteData note)
        {
            //This works but resharper reports it as an un-necessary cast which is true
            //remove the IActionResult cast on both and the types cannot be implicitly converted?
            //Remove the cast on one (not both) it also works
            return _noteService.CreateNote(id, note) == true
                ? (IActionResult) Ok()
                : (IActionResult) NotFound();

            //This also works without casts, but the if seems verbose and un-necessary
            //var result = _noteService.CreateNote(id, note);

            //if(result == OperationResult.NotFound)
            //    return NotFound();
            //else
            //    return Ok();
        }
```

**Comment by davidfowl** [comment]
I believe what you want to do is file a complaint on dotnet/Roslyn. The web framework doesn't control this behavior.

Just FYI, his has been the behavior since the beginning. Why we could have done (if we had a time machine) would be to make those methods return IActionResult instead of the specific type of result. At this point it's too big of a breaking change

**Comment by napalm684** [comment]
@davidfowl I thought the same thing, this is strange since technically both derive IActionResult in their dependency graphs.  I swear I had done this in other projects with success, must have been different scenarios (and it wasn't in the new core world - not sure if that matters or if the problem exists in both).
