### ISSUE TITLE
Is 2.0 released?

### ISSUE THREAD

**Issue by nvivo** [aspnet/Mvc#6649]
Just opened my nuget feed, and all packages appear as upgradeable to 2.0.

Nuget shows me: 
![image](https://user-images.githubusercontent.com/202449/29240999-33e6cfe8-7f47-11e7-9a42-db9a2b9193bc.png)

But I don't see any announcements and the repository shows preview2 as the last release.
Real or mistake?

**Comment by TDSchreur** [comment]
I see the same, but i can't upgrade to Microsoft.AspNetCore.All 2.0.0
Restore fails with message;  Unable to find package Microsoft.AspNetCore.MiddlewareAnalysis with version (>= 2.0.0)

**Comment by erwinwildenburg** [comment]
@TDSchreur yes, me neighter, it has been uploaded to NuGet but not yet indexed it says.

**Comment by Zonciu** [comment]
Uninstall the Microsoft.AspNetCore.All package and install packages singly will work.
I'd upgrade packages to 2.0, SDK to 2.0 last build, it works fine.

**Comment by erwinwildenburg** [comment]
@Zonciu  I downloaded it from NuGet.org, extracted it with 7zip in "C:\Users\[user]\.dotnet\NuGetFallbackFolder\microsoft.aspnetcore.middlewareanalysis\2.0.0" and calculated the hash with:
``` powershell
(Get-FileHash -Algorithm SHA512 "C:\Users\[user]\.dotnet\NuGetFallbackFolder\microsoft.aspnetcore.middlewareanalysis\2.0.0\micro
soft.aspnetcore.middlewareanalysis.2.0.0.nupkg").Hash | Out-File "C:\Users\[user]\.dotnet\NuGetFallbackFolder\microsoft.aspnetcore.middlewareanalysis\2.0.0\microsoft.aspnetcore.middlewareanalysis.2.0.0.nupkg.sha512"
```
Where did you get the SDK from?

**Comment by Zonciu** [comment]
@erwinwildenburg https://github.com/dotnet/cli/tree/release/2.0.0#installers-and-binaries

**Comment by nvivo** [comment]
Looks like it's official now: https://github.com/aspnet/Mvc/releases/tag/rel%2F2.0.0

I'm closing this.

**Comment by benaadams** [comment]
Might want the blog post for official announcement https://blogs.msdn.microsoft.com/webdev/2017/08/14/announcing-asp-net-core-2-0/
