### ISSUE TITLE
Use the real type of the model when validating properties using `DataAnnotationsModelValidator`

### ISSUE THREAD

**Issue by Nillerr** [aspnet/Mvc#6650]
**Given** the following models:
```C#
public sealed class AttributeValueModel
{
    [Required]
    public AttributeValueTypeModel Type { get; set; }
}

public abstract class AttributeValueTypeModel
{
    [Required]
    public string Type { get; set; }

    public sealed class TextAttributeValueTypeModel : AttributeValueTypeModel
    {
        [Required]
        public string Value { get; set; }
    }
}
```

And a custom model binder that handles binding the following input:
```
POST http://localhost:5001/attribute/valuemodel/1548
Type.Type: Text
Type.Value: foo
```

Such that an instance of `AttributeValueTypeModel.TextAttributeValueTypeModel` is assigned to the `Type` property of the model `AttributeValueModel`, and that instance has it's `Type` and `Value` properties set to `Text` and `foo` accordingly.

To an action:
```C#
public ActionResult(int id, AttributeValueModel model)
```

**When** calling `ModelState.IsValid` from within that action.

**Then** I expect the `DataAnnotationsModelValidator` will validate using the actual type of the value assigned to `ModelValidationContext.Model`, causing the result of `ModelState.IsValid` to be `true`. The current behaviour causes the result to be `False`.

**Comment by Nillerr** [comment]
The same implementation (Models, ModelBinder & Action) works as expected using ASP.NET MVC 5, where validation is performed on the actual type of the model.

**Comment by Eilon** [comment]
@Nillerr thanks for the report, we'll take a look.

**Comment by rynowak** [comment]
The model binding should add an entry to `ValidationState` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/ModelBinding/ModelBindingContext.cs#L100 with the metadata that you want to use for validation.

**Comment by Eilon** [comment]
We are not planning to make a change to model binding and validation specifically for this, but there is sufficient extensibility and customizability in model binding as @rynowak mentions.
