### ISSUE TITLE
Where is repo for ASP.NET NOT Core MVC?

### ISSUE THREAD

**Issue by Korporal** [aspnet/Mvc#6651]
I'm looking for the repo for ASP.Net MVC but not Core. I'm trying to find the repo that contains the project template used for:

ASP.NET We Application (.NET Framework) for Web API.

**Comment by davidfowl** [comment]
The project template isn't part of the github repository but the source code is here https://github.com/aspnet/AspNetWebStack

**Comment by Korporal** [comment]
@davidfowl - Many thanks Dave, much appreciated.
