### ISSUE TITLE
Multiple Identities with different token providers

### ISSUE THREAD

**Issue by Elfocrash** [aspnet/Mvc#6656]
## Intro

On my application I need to have two different Identities with different options for each Identity.
What I initially did is to simply add the identities with `services.AddIdentity<AdminUser, IdentityRole>`, `services.AddIdentity<User, IdentityRole>`
and do a `.AddDefaultTokenProviders()` at the end of the call, as the project does anyway.

## The problem
The problem is that when i have two identities and i call `.AddDefaultTokenProviders()` only the second call's tokens stay in the dictionary. That is because the system is checking if token providers with those names exist and if they do it replaces them with the latter.
The problem is that the IdentityOptions is a Singeton.
The error i was getting was `"No IUserTokenProvider named 'PasswordResetTokenProvider' is registered."`

My next idea after diving into the code was to remove the `.AddDefaultTokenProviders()` and manually add 3 calls for my providers ex. `.AddTokenProvider("UserDefault",                    typeof(DataProtectorTokenProvider<>).MakeGenericType(typeof(User)))` (and the respective ones for email and phone).

Then i manually set the token provider to be used in the User managers created for each identity like this: `optionsAccessor.Value.Tokens.PasswordResetTokenProvider = "UserDefault";`

However every time i needed to call a user manager the code was stepping in both managers (or there are cases where i need both). Because the `optionsAccessor.Value.Tokens.PasswordResetTokenProvider`, `optionsAccessor.Value.Tokens.ChangeEmailTokenProvider` and `optionsAccessor.Value.Tokens.EmailConfirmationTokenProvider` are system wide value, only the one set last will be used.
This makes the system unable to user the correct token.

## The workaround
The way I worked around it is by adding the `IHttpContextAccessor` in my usermanager and checking Route values to see if the request is coming by a specific area, controller and action.

Obviously this is very hacky and I am not happy with it.
I know that the correct way would be to use claims and roles to give different permissions to separate admin users and normal users, but the app I'm buying had this separation as a requirement on a higher level (Potentially the need to store them in a centralized database away from the other records, different cookie persistence values etc).

## Suggestion
To me it looks like the problem is that we use a Dictionary that limits the keys to one value.
The second `.AddDefaultTokenProviders()` call should probably throw an exception saying that i have something with that name already registered.
Another thing would be that instead of using a Dictionary, we use a data structure that allows key-value combination checks. That way we can have "Default"-"AUserManager" and "Default" - "BUserManager" but the code retrieves the one appropriate for this specific usermanager requesting it.

What are your thoughts on this?
Was Identity never build around the idea of having multiple ones?

**Comment by davidfowl** [comment]
This should be moved to http://github.com/aspnet/Identity/.

**Comment by davidfowl** [comment]
https://github-issue-mover.appspot.com/ 😄

**Comment by Elfocrash** [comment]
This issue was moved to aspnet/Identity#1360
