### ISSUE TITLE
Publish failed after upgrading to 2.0 RTM

### ISSUE THREAD

**Issue by thiennn** [aspnet/Mvc#6659]
In my projects, modules are dynamically loaded at runtime, and I need to turn off PrecompiledViews by adding

```xml
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <PreserveCompilationContext>false</PreserveCompilationContext>
```
I worked fine, but after upgrading to 2.0 RTM. I got the following error

Severity	Code	Description	Project	File	Line	Suppression State
Error The command ""dotnet" exec --runtimeconfig "C:\WebApplication15\bin\Release\netcoreapp2.0\WebApplication15.deps.json" "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 1.	WebApplication15		0

**Comment by davidfowl** [comment]
Add:

```xml
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
```

**Comment by thiennn** [comment]
It works, thanks

**Comment by nmg196** [comment]
Where do you add that? Which file?

**Comment by geringanetor** [comment]
@nmg196  in your project right-click and Edit your csproj. Then in <ProperyGroup></PropertyGroup> add it. Regards
