### ISSUE TITLE
Relax `string.IsNullOrEmpty(fullName)` checks slightly

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#6662]
Most HTML and tag helpers throw `ArgumentException`s when `id` and `name` attributes would both be empty e.g. the checks avoid an "unnamed `<input/>` element". See https://www.w3.org/TR/html5/dom.html#the-id-attribute and https://www.w3.org/TR/html5/forms.html#naming-form-controls:-the-name-attribute for more information about HTML requirements in this area.

The existing checks don't handle cases such as `<input asp-for="@Model" id="prefix" name="Prefix"/>` or `Html.ListBox(string.Empty, htmlAttributes: new { id = "prefix", name = "prefix" })` in top-level views. Suggestion is to allow a `null` or empty `fullName` when `htmlAttributes` already contains the necessary attributes.

Tag helpers might get a bit more complicated because most do not pass information about existing attributes into the `IHtmlGenerator`. They could special-case existing `id` and `name` attributes when both exist.

----

Not a great idea to pull the conditions up from `DefaultHtmlGenerator` and into the various callers. That would duplicate error checks, complicate those callers, and break outside code using the existing `IHtmlGenerator` implementation.

**Comment by Eilon** [comment]
> The existing checks don't handle cases such as `<input asp-for="@Model" id="prefix" name="Prefix"/>` or `Html.ListBox(string.Empty, htmlAttributes: new { id = "prefix", name = "prefix" })` in top-level views. 

What does "don't handle" mean here? Does something not work? What is the current behavior, and what is the expected/desired behavior? And when would someone encounter this situation?

**Comment by dougbu** [comment]
- "don't handle" == throw an `ArgumentException`
- MVC HTML and tag helpers _always_ disallow expressions with an empty id / name. But, users can provide ids and names.
- I'm suggesting allowing / not throwing for these cases _if_ users have overridden both attributes.
- Users would likely encounter this when creating top-level views for simple types.

**Comment by Eilon** [comment]
Ok I think I'm starting to get it. The expression `@Model` is perfectly valid, but *it results in an empty id / name*? Is that the crux of this? And then even though the developer has provided their own id / name, MVC says "boo hiss, *I* didn't get to create the name, so no one gets to play"?

**Comment by dougbu** [comment]
@Eilon with the added proviso that MVC only has a hissy fit when the _entire_ name is empty i.e. it's handling an unusually-simple top-level view, you have described the children exactly right.

**Comment by dougbu** [comment]
ecedbd5372
