### ISSUE TITLE
After updating ( 1.1 to 2.0 )  the StaticFiles can't be found in the root path.

### ISSUE THREAD

**Issue by NMSLanX** [aspnet/Mvc#6665]
## Question:
1、   
         project:    webapi core1.1
         nuget:     Microsoft.AspNetCore.StaticFiles
         file:          wwwroot/Index.html
         ok:          "http://xxxxx/Index.html" return "hello world"
        operation: **right-click "Controller Folder" --> "Add(D)" --> "controller(T)" --> select any and "Add".**
        error:       "http://xxxxx/Index.html" return "http://xxxxx/Index.html/".

2、  
         project:   webapi core 1.1
         nuget:     Microsoft.AspNetCore.StaticFiles
         file:          wwwroot/Index.html
         ok:          "http://xxxxx/Index.html" return "hello world" 
         operation: **update to core2.0**
         error:       "http://xxxxx/Index.html" return "http://xxxxx/Index.html/".

**Comment by davidfowl** [comment]
Can you provide a sample that worked before that now fails?  Preferably a github repository.

**Comment by NMSLanX** [comment]
Hi David:
          Here is the github repository.  [#6665](https://github.com/NMSLanX/WebApi_6665).

**Comment by davidfowl** [comment]
Just for future reference so you know how to diagnose these issues. Turn logging on to a high verbosity level like trace or debug:

Change this line

https://github.com/NMSLanX/WebApi_6665/blob/3f2a5c8603e0803efa6c328a8b8d878a4d189d59/Error/Actual/WebApiOne/WebApiOne/Startup.cs#L46

To:

```C#
loggerFactory.AddConsole(LogLevel.Trace);
```

The log immediately shows the problem:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:64780/Index.html/
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[5]
      The request path /Index.html/index.html does not match an existing file
```

I ran the WebApiOne project under Error. It seems like it 404s without the upgrade to 2.0, are you sure it's related? 

Also, I'm not sure this has anything to do with MVC.

**Comment by Eilon** [comment]
This issue was moved to aspnet/StaticFiles#210
