### ISSUE TITLE
Asp.Net MVC 5 app not working after VS 15.2 update to 15.3

### ISSUE THREAD

**Issue by alfeg** [aspnet/Mvc#6666]
After updating VS 15.2 to Vs 15.3 I were blocked with an issue.

Asp.net app suddenly report that it cannot load some assemblies

```
Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

If I build same project with 15.2 version - everything works perfectly

I've pushed project with repro: https://github.com/alfeg/vs15_3repro

Steps:
- Build project with VS 15.2. 
-- Ctrl+F5 on `REPRO.UI.Headquarters` web project.
-- Should open page with Hello World
- Build same project with VS 15.3
-- Ctrl+F5 on `REPRO.UI.Headquarters` web project.
-- `Could not load file or assembly ...` message appear

I've try to change some binding redirects, but has no luck, and this breaks build with 15.2 studio.

Any idea how to resolve, or where I should report this issue?

**Comment by davidfowl** [comment]
I would report MVC 5 issues on github.com/aspnet/aspnetwebStack/. This repository is for MVC Core.

**Comment by MaximRouiller** [comment]
WIthout forgetting that if you really want to upgrade to ASP.NET MVC Core, there's always the possibility of migrating to the new stack!

https://docs.microsoft.com/en-us/aspnet/core/migration/

If you try it out, please let us know!

**Comment by MaximRouiller** [comment]
In the midtime, I've moved the issue to the right repository and will follow up with you @alfeg.

**Comment by EIDIVANDI** [comment]
Do you use Nunit in your solution? 

as a proposition , just remove the NetStandardLibrary and reinstall it

**Comment by Eilon** [comment]
Closing because the issue was moved to https://github.com/aspnet/AspNetWebStack/issues/57. Thanks!
