### ISSUE TITLE
UrlHelperExtensions should have overloads with RouteValueDictionary

### ISSUE THREAD

**Issue by grokky1** [aspnet/Mvc#6667]
Before Core, `UrlHelper` had overloads that used `RouteValueDictionary`.

Now [`UrlHelperExtensions`](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/UrlHelperExtensions.cs) only accepts `object` and that is a real hassle to use. When needing to add/remove/merge items, you need to use reflection and dynamic, etc.

Please add dictionary support, like it used to be.

**Comment by Eilon** [comment]
Actually, you don't have to! You can pass in a `RouteValueDictionary` as the `values` parameter of any of those APIs, and it'll just work! Internally there's a helper method that does a bunch of checks for different types - `RouteValueDictionary`, `IDictionary<string, object>`, or a POCO (object with properties) - and it does the right conversion based on those.

You can find it here:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Routing/UrlHelper.cs#L226-L255

**Comment by grokky1** [comment]
@Eilon Wow that's really useful behavior!! I've been struggling with this for nothing 😄

It is important to document this, in the methods' doc comments... Otherwise no one will know (and besides it needs to be part of the contract). Is there some place I can make such a request?

**Comment by Eilon** [comment]
@grokky1 - that's a fair point - I logged https://github.com/aspnet/Mvc/issues/6670 to track updating the comments.
