### ISSUE TITLE
`ValidationSummaryTagHelper` should not suppress output

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#6668]
The `ValidationSummaryTagHelper` should act more like other in-box tag helpers. Specifically, `<div asp-validation-summary="ModelOnly">content</div>` should generate `<div>content</div>` instead of suppressing the `<div>` element and its content.

From https://github.com/aspnet/Mvc/issues/6638#issuecomment-322689648:
> __Omitting a tag I've explicitly asked for is really unhelpful.__

MVC Core helpers do exactly this in a few cases. For HTML helpers, the behaviour matches earlier releases e.g. MVC 5.2.3 and likely shouldn't change now. For tag helpers, it's more about the common substrate than back-compatibility though MVC Core 1.x has been out for a while now.

The behaviour of tag helpers is inconsistent in cases similar to those where HTML helpers would do nothing at all:
- `<div asp-validation-summary="ModelOnly">content</div>` generates nothing (suppresses output) when client-side validation is disabled or the model itself is valid
- Oddly, `<div asp-validation-summary="None">content</div>` generates `<div>content</div>`
- `<label asp-for="PropertyWithEmptyDisplayName">content</label>` generates `<label>content</label>`. (As noted in #6638, generation here should include the `for` attribute.)
- `<span asp-validation-for="ValidProperty">content</span>` generates `<span>content</span>`

---- 

This issue should _not_ be broadened to apply to all in-box tag helpers. The `<condition>` and `<environment>` tag helpers must suppress output to work at all. The `<cache>` and `<distributed-cache>` tag helpers call `SuppressOutput()` to remove the elements but element bodies are not suppressed.

**Comment by mkArtakMSFT** [comment]
Closing this as there doesn't seem like any customer-feedback regarding this bug.
