### ISSUE TITLE
Clarify doc comments for special types for route-related 'values' parameters

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#6670]
In the various URL helper extension methods there is a `values` parameter that can be a `RouteValueDictionary`, `IDictionary<string, object>`, or a POCO (object with properties), and it does the right conversion based on those. The doc comments of these overloads lack information on the two special types, so we should add details on those.

https://github.com/aspnet/Mvc/blob/036dae292f0017a128170ea2d04fa7f06e353b38/src/Microsoft.AspNetCore.Mvc.Core/UrlHelperExtensions.cs#L53

@javiercn - can you propose new text for this type of parameter, and then make the change everywhere? Should check the Routing repo in case there is a similar need there.

**Comment by javiercn** [comment]
We can make a remark that IDictionary implementations will be treated in a special way. What about an addendum that says.
In case the object implements IDictionary<string,string> the contents will be used as the values.

**Comment by Eilon** [comment]
Two things:

1. I don't see any logic specifically for `IDictionary<string, string>`, just `IDictionary<string, object>`.
2. What about RVD, which is also special-cased? I think it's worth pointing out this specific type, even though it's also just an `IDictionary<string, object>`.

Can you show what we say for HTML attributes?

**Comment by javiercn** [comment]
https://github.com/aspnet/Mvc/blob/3a710c3d64557a97bae248446987d357711fffc4/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Rendering/HtmlHelperLinkExtensions.cs#L54

**Comment by javiercn** [comment]
The comment doesn't make a specific mention about RVD, you are right is IDictionary<string,object> it was a typo from me.

**Comment by Eilon** [comment]
Actually I was referring to comments like this (for HTML attributes, not route values):
https://github.com/aspnet/Mvc/blob/3a710c3d64557a97bae248446987d357711fffc4/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Rendering/HtmlHelperLinkExtensions.cs#L101-L105

But indeed, we need to also fix the places you found - where we talk a little bit about route values, but don't mention RVD.

**Comment by danroth27** [comment]
Not worth doing - closing
