### ISSUE TITLE
ASP.NET Core 2.0 issue w/ Chrome 61 (Beta Channel)

### ISSUE THREAD

**Issue by mguinness** [aspnet/Mvc#6673]
### Title
ValidateAntiforgeryToken authorization filter returns "Bad Request" due to missing antiforgery cookie that occurs when using Chrome 61 over HTTP (works for HTTPS).

### Functional impact
Unable to use ValidateAntiForgeryToken on a controller accessed over HTTP.

### Minimal repro steps
1. Install latest version of Chrome from beta channel
2. Create new ASP.NET 2.0 Core Web Application w/ Individual User Accounts
3. Run project using HTTP not HTTPS (see launchSettings.json for correct profile)
4. Browse to http://localhost:XXXXX/Account/Login
5. Attempt login and it should fail with 400 Bad Request

### Expected result
Form should be validated and controller action should be invoked

### Actual result
Form fails validation and returns bad request result

### Further technical details
Using Fiddler, I can see hidden form field __RequestVerificationToken, but cookie .AspNetCore.Antiforgery.XXXXX missing

**Comment by mguinness** [comment]
@follesoe Upon further testing, it appears that cookies aren't accepted on localhost domain.  If you browse instead to http://127.0.0.1:XXXXX/Account/Login the cookie is set.

**Comment by rynowak** [comment]
This seems like a big issue. @blowdart @Tratcher are you aware of anything here. 

@follesoe @mguinness - is anything showing up in the chrome developer tools console when you visit the home page?

**Comment by mguinness** [comment]
@rynowak There is nothing showing in dev console.  For some reason Chrome is ignoring the Set-Cookie header in the server response.

I was able to repo using the code below (cookie isn't set).  The weird thing is that if I rename the cookie it works.  Maybe I need some sleep :)

```
Response.Cookies.Append(".AspNetCore.Antiforgery.04ys_sjWUWs", "test");
```

**Comment by blowdart** [comment]
Are you selecting "Remember me?" by any chance? There was an old Chrome bug about this - https://bugs.chromium.org/p/chromium/issues/detail?id=551906

**Comment by follesoe** [comment]
Nothing particular showing up @rynowak - the error does not persist if I browse the site on https (I'm serving the site on https://localhost:44353 and http://localhost:5000). So could there be a change in Chrome around cookies, localhost and none https sites?

**Comment by ericlaw1979** [comment]
Can someone share a SAZ or a full set of headers in which the `Set-Cookie` response header appeared?

**Comment by blowdart** [comment]
Sounds like a chrome issue. Could you open a chrome bug at https://crbug.com/new, and then link it here so they can get in touch if needed?

**Comment by mguinness** [comment]
I think I discovered the issue here, but the resolution is less clear.  It appears that Google is proposing an amendment to [RFC 6265](http://httpwg.org/http-extensions/draft-ietf-httpbis-cookie-alone.html) to remove the ability for a non-secure origin to overwrite cookies whose secure flag is set.

This was filed as a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=698839) but was closed as by design.  I understand the rationale, but I really think they should log a warning message in the developer console instead of just ignoring the cookie.

**Comment by blowdart** [comment]
@ericlaw1979 - Did you uninstall VS never to return again? :)

So, first request that hits a form;

```
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Expires: -1
Vary: Accept-Encoding
Server: Kestrel
Set-Cookie: Identity.External=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax
Set-Cookie: .AspNetCore.Antiforgery.njf-wR4IQ4M=CfDJ8MDzKK8qS1RGhpttTTAUW5xOgUoKEw2bykry4oclhSsgwrRUind_guaYCL9ggmN41OvUslCLObwYWdtNYFCKJWkj4VMHfiv4AIZRuoOn1jprO9dYrD26KZlv42eOCRh50gVy_XW4EA079dSs5wEy3sE; path=/; samesite=strict; httponly
Set-Cookie: .AspNetCore.Mvc.CookieTempDataProvider=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=strict
X-Frame-Options: SAMEORIGIN
X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNcYmRvcnJhbnNcRG9jdW1lbnRzXFZpc3VhbCBTdHVkaW8gMjAxN1xQcm9qZWN0c1xXZWJBcHBsaWNhdGlvbjVcV2ViQXBwbGljYXRpb241XEFjY291bnRcTG9naW4=?=
X-Powered-By: ASP.NET
Date: Tue, 22 Aug 2017 20:38:24 GMT
```

.AspNetCore.Antiforgery.njf-wR4IQ4M is the cookie in question

**Comment by blowdart** [comment]
@mguinness Ah, you hit HTTPS first?

**Comment by ericlaw1979** [comment]
It seems entirely reasonable to file a feature request for a console warning on a cookie rejected due to the Strict Secure Cookies feature (https://www.chromestatus.com/features/4506322921848832).

**Comment by blowdart** [comment]
And you can turn samesite=strict off in the anti-forgery configuration.

This should go away in 2.1 where we're planning to force HTTPS everywhere by default in the templates, and default to using it as well. If we ship it.

**Comment by mguinness** [comment]
@blowdart Yep, I had previously logged in via HTTPS.  Later I had switched to HTTP and couldn't log in, it was a real head scratcher and I wasted a fair bit of time trying to troubleshoot with nothing to go on.

I'm not the first developer to hit this issue and I'm sure I won't be the last.  Although not ideal, is it possible to expand the error message in ValidateAntiforgeryTokenAuthorizationFilter.cs to alert users to this issue?

Personally I don't think forcing HTTPS is a great decision, but I'll let other members of the community chime in with their thoughts.

**Comment by ericlaw** [comment]
Do the cookies need to have the same names across protocols? Can you add the protocol to the hash used to generate the Cookie name?

**Comment by blowdart** [comment]
That's an interesting idea - hey @rynowak ...

**Comment by Eilon** [comment]
We need to come up with a design to fix this. I'm not super happy with any of the proposals I've heard so far. I'll set up a mtg to discuss.

**Comment by blowdart** [comment]
As an aside our general (and the industry at large's) recommendation is once you go SSL you don't drop back.

@mguinness Is this "just" in your dev environment, or would your production apps drop back down to HTTP after HTTPS?

**Comment by mguinness** [comment]
@blowdart This is just the dev environment, the production environment is SSL only.  The only complaint I have is that browsers implementing this change (including Edge) must display a warning in the console instead of silently ignoring the cookie.

**Comment by blowdart** [comment]
Ah cool. We're hopefully making everything HTTPS by default for 2.1 which should mitigate this somewhat.

**Comment by Eilon** [comment]
Ok here's what we settled on doing:

We will make sure that all cookies set by ASP.NET Core (except the auth cookies) will default to `CookieSecurePolicy.None`. These are the cookies we're looking at:
- [Session](https://github.com/aspnet/Session)
- [TempData](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/CookieTempDataProviderOptions.cs) (an MVC feature)
- [Antiforgery](https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNetCore.Antiforgery/AntiforgeryOptions.cs)
- [Localization](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/CookieRequestCultureProvider.cs)

We are not changing the auth cookie default behavior because auth should not be taking place over an HTTP connection.

@natemcmaster - any idea if there are other cookies we need to consider?

All - Please let us know your feedback or if you see any issues with this.

Note: We plan to fix this for ASP.NET Core 2.1.0. In the meantime please use the workarounds previously mentioned.

**Comment by Eilon** [comment]
Tagging @blowdart @Tratcher @rynowak @davidfowl just to make sure your inboxes are bumped with our conclusions.

**Comment by natemcmaster** [comment]
> any idea if there are other cookies we need to consider?

@Eilon  I think your list covers it, but it would be good to double check by searching our code base for anywhere `Microsoft.AspNetCore.Http.CookieBuilder` is used.

**Comment by Eilon** [comment]
@natemcmaster thanks.

@kichalla - please search our codebase to check and see if there are any other cookies we need to consider changing.

**Comment by kichalla** [comment]
Following is the status of this issue:
- Session (We already set cookie policy to None here, so its a no-op in this repo)
- TempData (an MVC feature) (Fix has been checked in)
- Antiforgery (Fix has been checked in)
- Localization (We do not set any cookie ourselves. We look for a cookie with a specific name in the CookieRequestCultureProvider. The user developing the application is responsible of setting the cookie explicitly)

I did not find any other references to CookieBuilder (apart from the Security and Identity repos)

https://github.com/aspnet/Mvc/commit/b2f9ad1b6755526537f002b6e9690943d5e8b6fc
https://github.com/aspnet/Antiforgery/commit/12e9430d89b85c1be0029ba2cded7840b2c59999
