### ISSUE TITLE
ASP.NET Core WebApi performance vs WCF

### ISSUE THREAD

**Issue by SWarnberg** [aspnet/Mvc#6675]
Hi,

I just started to investigate to use this cool new ASP.NET Core 2.0 WebApi technology for a new service layer, instead of using legacy WCF.
However, my initial tests shows that it's much slower than WCF. Is this expected or are there ways to tweak ASP.NET Core / MVC to perform in par with WCF?

In my tests I created the exact same service operation in WebApi and WCF (SOAP), which returns a simple object with three properties. Using SoapUI for load test, I got more than 4 times slower response times from the REST service compared to the WCF SOAP service (133ms vs 33ms). It didn't matter if the host was IIS, Kestrel or Docker, loaclly or in Azure. I got the same result.
Also tested with different clients like Postman and WPF.

/Staffan

**Comment by Eilon** [comment]
@SWarnberg it's hard to say what the expected performance differences are without knowing all the details. Even small differences in the code can cause huge performance changes.

Can you share the code of your tests (both WCF and ASP.NET Core 2.0) so that we can investigate?

**Comment by SWarnberg** [comment]
Sure. I created two projects. Both are basically untouched from the default templates, except that I now return a single "User" object. You can download it here: [https://1drv.ms/u/s!AjOlUiKuao5Iq2Q53Xz_2xOiqU6f](url)

The interesting thing here is that these projects gets the performance difference as I describe above when using the debugger (both in Debug and Release mode). However, when using Ctrl+F5, the performance in the WebApi is excellent and on par with, or better than, the WCF service.

However, my initial comparison I did before I wrote this post was on Azure, and the WebApi service was hosted with Docker. Is Docker behaving as poor as the debugger?

/Staffan

**Comment by Eilon** [comment]
Thanks for sharing the apps. (BTW it's often easier to push things to GitHub as a public repo so that the code is browseable and linkable, but a ZIP works fine too!)

Running with a debugger attached will do all kinds of odd things because there are some parts of the code that check if the debugger is attached and do "extra" stuff to make it more debugger-friendly, so that could certainly explain some of it.

As to Docker, that's a whole different story.

I recommend checking that the ASP.NET Core app is running in "Production" mode (ASPNETCORE_ENVIRONMENT either not set, or set to "Production").

@natemcmaster - any idea if we've heard anything about perf issues when running in Docker?

cc @davidfowl @rynowak @mikeharder FYI/thoughts

**Comment by SWarnberg** [comment]
OK, now I also added Docker support and published it to Azure here: [http://webapi2020170817082850.azurewebsites.net/api/users](url).
The average response time I get in a load test is 47ms, which is not as good as my more complex WCF service in Azure (that returns the object from memory cache), which has an average response time of 33ms.

**Comment by SWarnberg** [comment]
Hmm, I think I may have found the issue here. I just published the simple WCF service to Azure as well, and it performed quite poorly. It turned out that it got created in South Central USA, just as my first REST service. My first WCF service and last REST service was published to Europe where I'm situated. Hence, both those services respond much faster.
Never thought the location was so important.

But still, even though I ensured to have "Production" set, it feels Docker is a bit worse performance-wise. Could it be that it's in beta?

**Comment by Eilon** [comment]
Where were you hosting Docker? On Azure? If so, using which Azure service?

**Comment by natemcmaster** [comment]
> any idea if we've heard anything about perf issues when running in Docker?

No issues I'm aware of. @SWarnberg what is your docker setup? When doing your perf investigations, remember that Docker containers may not have access to the full machine resources. If you're using Linux containers on a Windows server, you're actually running a container inside a VM, and the VM itself will have limited resources.

**Comment by SWarnberg** [comment]
I'm closing this for now since the major problem was a regional issue with Azure. I can live with the local debugger is slower than debugging WCF services. I'm guessing it will be quicker in future versions.
