### ISSUE TITLE
Revisit the unwrapping code in ControllerActionInvoker

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#6679]
There's about a 150 lines of code we have in `ControllerActionInvoker` to massage the returned value to an `IActionResult`: https://github.com/aspnet/Mvc/blob/ccf9b2ec976147eb8452d8f3d50b446815765f48/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionInvoker.cs#L326-L412. Adding support for a new return type results in several dozens of lines of code and conditions making it pretty hard to manage and extend. We should see if this could be simplified.

Related item: The current code path performs reflection (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionInvoker.cs#L407-L411) to determine if a type is an `IActionResult`. We should change the code to avoid this.

**Comment by Eilon** [comment]
Please earn maximum 💯 points.
