### ISSUE TITLE
C# 7 features do not work in Razor partial view (2.0)

### ISSUE THREAD

**Issue by vaindil** [aspnet/Mvc#6681]
Prior to 2.0 it was possible to use C# 7 features in Razor views by setting the relevant property in `.AddRazorOptions()`. This was removed with #6487. The [new method](https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.0#razor-support-for-c-71) is to set `<LangVersion>` in the project file, but this has had no effect. Specifically, I have a partial view that uses a tuple as its model, yet I get the same error that was thrown pre-2.0 when the `AddRazorOptions()` property wasn't set:

> Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: 'One or more compilation failures occurred:
> C:\path\to\file\_MyPartialView.cshtml(1,8): Error RZ9999: The 'model' directive expects a type name.'

The model is declared in the view like this:

    @model (string Title, List<My.Class.Here> Logs)

My .csproj file is laid out like this (there's more, of course):

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
```

**Comment by vaindil** [comment]
Sorry, I'm an idiot, found it [here](https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.0#razor-support-for-c-71).

**Comment by vaindil** [comment]
Edited the issue and reopening, I was previously incorrect.

**Comment by vaindil** [comment]
Despite the fact that this did work pre-2.0, it looks like this was officially added in aspnet/Razor#1613. I'll close this one.

**Comment by rynowak** [comment]
No worries. FYI for anyone looking at this, 7.0 is the default now, but we take the language version from your project file. 

We removed the options from `RazorOptions` to avoid confusion. Most of the options you could set on the `RazorOptions` that affect Roslyn/C# would have unpredictable/unsupported results, including setting the language version that way.

The truth is that you're limited to the subset of language features that Razor supports. For instance setting 7.0 in the past did not automatically get you tuple support everywhere, we had to implement features in Razor to make this work right.
