### ISSUE TITLE
Build fluent API for app model conventions

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#6682]
We should build a fluent API for app model conventions that allows:
1. Easily selecting (i.e. querying) the objects to apply conventions to (e.g. Razor pages, controllers)
2. Easily setting a convention on the selected objects (e.g. applying filters)

See https://github.com/aspnet/Mvc/issues/6630 for previous discussion and an example of filter ideas.

**Comment by mkArtakMSFT** [comment]
We're closing this as it seems this will require a considerable amount of work and is not really a priority.
