### ISSUE TITLE
Upgrade to aspnet core 2.0 changed [Produces("text/html")], now requires ContentResult + ContentType

### ISSUE THREAD

**Issue by Meai** [aspnet/Mvc#6686]
This used to work:

        [HttpGet("")]
        [Produces("text/html")]
        public string Get()
        {
            return "<html><body>Hello World</body></html>";
        }

Now in 2.0 only this works, [Produces("text/html")] doesnt seem to have an effect:

```
        [HttpGet("")]
        public ContentResult Get()
        {
            return new ContentResult()
            {
                Content = "<html><body>Hello World</body></html>",
                ContentType = "text/html",
            };
        }
```

**Comment by alexsandro-xpt** [comment]
Is this a bug?

**Comment by Eilon** [comment]
I think this is the same issue as https://github.com/aspnet/Mvc/issues/6657, which was a deliberate change from ASP.NET Core MVC 1.x to 2.0. Can you look through the other issue and see if the workarounds listed there work for you?

**Comment by Meai** [comment]
well it looks similar, but I dont see how the proposed solution there is a solution at all. A global rule that makes all strings into text/html? And the [Produces()] is still weirdly not doing anything I guess?
Doesnt make sense to me

**Comment by Eilon** [comment]
@rynowak any further thoughts on this?

**Comment by rynowak** [comment]
> A global rule that makes all strings into text/html?

This is a setting that says that the "text" formatter is capable of responding with strings to requests for text/html. We're careful not to allow clients to decide from an unbounded list what the content type will be - this would be a security issue. 

We limit this list to `text/plain` by default for obviousness - this means that when you return a string, the formatter is *allowed* to say that's it's `text/plain`. We could consider adding `text/html` to this list by default - I don't think it would break anything else and wouldn't cause confusion.

The original issue that we sought to fix here was that the `StringOutputFormatter` could also write `text/json` or `text/xml` which prevented the other formatters from running when you wanted to serialize a string using JSON or XML.

> And the [Produces()] is still weirdly not doing anything I guess?

Produces works based on what formatters support. It indicates a preference or specification a content type from a set of possible content types. In this case `text/html` isn't in the list of possible content types.

---------------------------------

The combo of `[Produces]` + returning the data directly (`return "Hello, World!";`) goes through formatters, and uses content negotiation to decide something that you've already decided - that this string should be output verbatim, and that the content type should be `text/html`. Using `Content(...)` just does that directly.

**Comment by Eilon** [comment]
Closing as a dup of https://github.com/aspnet/Mvc/issues/6657, which has further thoughts on what we might do in the future.
