### ISSUE TITLE
The 'model` directive must appear at the start of the line.

### ISSUE THREAD

**Issue by mvermef** [aspnet/Mvc#6687]
System.NullReferenceException in Microsoft.AspNetCore.Mvc.ViewFeatures.dll
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException
Error RZ9999: The 'model` directive must appear at the start of the line.

Partial within a Partial both have viewmodels.

https://stackoverflow.com/questions/45773120/aspnetcore-2-0-mvc-model-must-appear-at-the-start-line

**Comment by Eilon** [comment]
Hmm I wonder if there's a Unicode Byte Order Mark (BOM) at the start of the file that's causing this? Can you open the CSHTML file in a hex editor (VS has one built-in) and see what's there?

**Comment by Eilon** [comment]
cc @pranavkm @rynowak @NTaylorMullen

**Comment by mvermef** [comment]
You know that is so freaking odd, why wouldn't that have been caught in 1.1.2?  It appears that is exactly what the deal was.  Thanks Eilon!

**Comment by davidfowl** [comment]
It still shouldn't null ref.

**Comment by mvermef** [comment]
while it does work  **Microsoft.AspNetCore.Mvc.ViewFeatures** is still throwing about 10 of those NREs and everything processes correctly, anything I can provide or pull for you?

**Comment by mvermef** [comment]
I think know why and its probably my mistake for thinking it would work that way, thought I read something to the nature that it would bind correctly.  **It was brain fart between Razor Pages and Razor Views with complex property binding** 

Where NewUser = ApplicationUser in the ViewModel

     <div class="col-md-8">
                    <input asp-for="NewUser.FirstName" class="form-control" />
                    <span asp-validation-for="NewUser.FirstName" class="text-danger"></span>
                </div>

**Comment by Eilon** [comment]
@pranavkm can you investigate and shed some light on this? This looks very odd...

**Comment by rynowak** [comment]
> It still shouldn't null ref.

MVC's property evaluation code will throw and handle null ref for cases like: `<span asp-validation-for="NewUser.FirstName" class="text-danger"></span>`  It's something that's awful, but we've never put significant time into trying to fix it.

**Comment by pranavkm** [comment]
@rynowak aren't all of those are first chance exceptions that shouldn't propogate to user code? The stack trace above made it look like they were seeing the exceptions in the error page.

**Comment by mvermef** [comment]
They never made it to error page, they were swallowed. Only in debug output couple.

**Comment by pranavkm** [comment]
Ahh, nevermind then. We explicitly try-catch those: https://github.com/aspnet/Mvc/blob/a23307e2b1e7934e2c8d69774cda1b36778f697b/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ExpressionMetadataProvider.cs#L89. @Eilon \ @rynowak 

(a) Do we want to further investigate the BOM issue? Seems like we should just support it out of the box.
(b) Do we want to look at alternatives to the try-catch in the model evaluation?

**Comment by rynowak** [comment]
Yeah, we should see what kinds of things break this check

**Comment by pranavkm** [comment]
@mvermef any chance you have a repro app for this? VS defaults to storing UTF8 files with a BOM, and the .NET FileStream APIs we use handle BOMs just as well.

**Comment by mvermef** [comment]
Negative, only thing I can add is that it was related to copy and paste from an example of doing modal dialogs with coding from around the web, but the idea was 3-4 lines code savings with the use of a partials, and being able to use headermodel and footermodel for specifying options like title, button text, single button etc.

In the end I would put money that the BOM that was copied was the result.  Compared to hand coded Partials the extra crap at the front of the file was culprit, which didn't show until looking via binary editor.

**Comment by mvermef** [comment]
There was no exact signature to the BOM.

**Comment by pranavkm** [comment]
@mvermef do you recall if it was it UTF8 BOM (`EF BB BF`) or just a bunch of non-printable UTF8 chars? The latter might explain the oddity we see here.

**Comment by mvermef** [comment]
Unreadable

**Comment by pranavkm** [comment]
Gotcha. I guess there really isn't much we could do here. Having stray leading chars isn't very common and accounting for that in the parser wouldn't be a sensible thing to do. We've closed issues around the null-ref in the past (eg. https://github.com/aspnet/Mvc/issues/4826). I'll go ahead and close this unless somebody feels strongly about it.

**Comment by mvermef** [comment]
@pranavkm I found the BOM that was at the front of the file it was in an unchanged file in my local repo on desktop... EF BB BF EF BB BF
