### ISSUE TITLE
WebRootPath is still null in netcoreapp2.0 under IIS

### ISSUE THREAD

**Issue by aliveli186** [aspnet/Mvc#6688]
WebRootPath is still null in netcoreapp2.0 when run under IIS 8.5 on Windows Server 2012 R2.
This issue is present since the earlier versions.
This error only happens when the project is published on a server, when run on IIS Express from Visual Studio it works without problem.

The workaround is to set it manually.
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    // WebRootPath == null workaround.
    if (string.IsNullOrWhiteSpace(env.WebRootPath))
        env.WebRootPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
}
```

**Comment by davidfowl** [comment]
Hmm I've never heard about this problem. Do you have a repro?

**Comment by aliveli186** [comment]
@davidfowl I'm don't know how to make it but you can try yourself. But you need to publish it to IIS.

```
[Route("api/v1/Tests/[controller]")]
public class Test1Controller : Controller
{
    private readonly IHostingEnvironment _environment;

    public Test1Controller(IHostingEnvironment environment)
    {
        _environment = environment;
    }

    [HttpGet]
    public IActionResult Get()
    {
        var isNull = _environment.WebRootPath == null;

        return Ok($"isNull: {isNull}");
    }
}
```

**Comment by davidfowl** [comment]
@aliveli186 Do you have a wwwroot folder on the machine you deployed to? That's likely the problem.

**Comment by aliveli186** [comment]
@davidfowl You caught me. :) No I don't have such folder since it's an API project.
I need to access some files in one of the controllers which made me to extract the path from the environment WebRootPath.

**Comment by davidfowl** [comment]
> I need to access some files in one of the controllers which made me to extract the path from the environment WebRootPath.

Files from where?

**Comment by aliveli186** [comment]
Files from the root directory where the API is.
Root/Settings <--- Here
Root/wwwroot

Why there is no such problem under IIS Express?

**Comment by davidfowl** [comment]
> Files from the root directory where the API is.

You shouldn't be using the webroot for find that folder. The ContentRoot is what you want.

> Why there is no such problem under IIS Express? 

@aliveli186 The folder likely exists during dev but then web deploy (or whatever deployment process you're using) isn't copying empty folders over to your deployment server.

**Comment by aliveli186** [comment]
@davidfowl Thank you for the tips.
