### ISSUE TITLE
Formatters: BufferedMediaTypeFormatter and MediaTypeFormatter 

### ISSUE THREAD

**Issue by takazm** [aspnet/Mvc#6689]
Trying to implement a custom HalFormatter (HATEOAS)  for Web Api in ASP.Net core 2.0 but none of these 2 types seem to be available.  Package references set to Microsoft.AspnetCore.All.  Am i missing something? Were these retired?

**Comment by khellang** [comment]
You probably want to take a look at `OutputFormatter`, `TextOutputFormatter` or `JsonOutputFormatter`.

**Comment by rynowak** [comment]
Do you really want a custom formatter for HAL?  I don't know exactly what you're doing, but it seems more likely to be simpler to implement as a combination of object model and filters.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this. It seems that there exist other ways to do what's being discussed here.

**Comment by takazm** [comment]
I eventually implemented thus by deriving from jsonoutputformatter

**Comment by Eilon** [comment]
Glad to hear!
