### ISSUE TITLE
Open MVC Project with vs 2017 15.3 cpu always 100%

### ISSUE THREAD

**Issue by JamesYing** [aspnet/Mvc#6691]
When I open the mvc source with vs 2017 15.3, the cpu always 100%, I restored the nuget packages and restart my compute, but it always 100......

**Comment by pranavkm** [comment]
We typically use `Mvc.NoFun.sln` since it has fewer projects, but any crashes or hangs in tooling should be reported via the VS Feedback tool (it's on the top right of the window).

**Comment by JamesYing** [comment]
hi pranavkm, thanks for your reply. I think it because of nuget packages restored failed

**Comment by Eilon** [comment]
Closing because this needs to be reported through VSFeedback - that goes directly to the right team with all the required info.
