### ISSUE TITLE
HttpContext.GetRouteData() no loger works in aspnet core 2.0

### ISSUE THREAD

**Issue by maciejjarzynski** [aspnet/Mvc#6693]
Hello,
I have a code in ModelBinder (when requesting for the action from controller) which takes RouteData object out of the Features by the extension method for HttpContext:
`var routeData = ctx.HttpContext.GetRouteData()`

After the migration to ASP NET Core 2.0 the `IRoutingFeature` no longer contains correct `RouteData` object - `Values` taken from the route set by `HttpPost` attributes are empty, where they shouldn't be.

On the other hand, the proper `RouteData` object with correct `Values` resides in `ActionContext.RouteData'`.

Is it a bug, or an intended change?

**Comment by rynowak** [comment]
This is not an intended change. Do you have a link to an app that reproduces this issue?

**Comment by maciejjarzynski** [comment]
Hi, I was trying to separate that issue from my project, but to no avail. I still have some paths to try, though.

**Comment by maciejjarzynski** [comment]
After the successful attempt to isolate the problem, it occured to be a bug in `Microsoft.AspNetCore.Mvc.Versioning: 2.0.0-preview2-final`.
Link to the issue:
https://github.com/Microsoft/aspnet-api-versioning/issues/176
