### ISSUE TITLE
how to use Component in razor pages

### ISSUE THREAD

**Issue by BruinY** [aspnet/Mvc#6699]
I like.net 2.0 the new features of the core razor pages, but how the razor pages using MVC Component feature

**Comment by mikebrind** [comment]
Are you asking about _View_ components? If so, you use them in the same way as in an MVC application. You can call `await Component.InvokeAsync(...)` or you can use the view component tag helper: [https://docs.microsoft.com/en-gb/aspnet/core/mvc/views/view-components#invoking-a-view-component-as-a-tag-helper](https://docs.microsoft.com/en-gb/aspnet/core/mvc/views/view-components#invoking-a-view-component-as-a-tag-helper).

**Comment by Eilon** [comment]
Indeed, we need a bit more info. View components should work exactly the same in Razor Pages as they do in MVC Razor views.

**Comment by BruinY** [comment]
Exactly, I just change the content of the original MVC to use razor pages to deal with.I prefer the razor pages to develop this way

**Comment by Eilon** [comment]
Ok then it doesn't sound like there's an issue here.

If you are still having an issue, please log a new issue with details about what you tried, what didn't work, and what version you are using.
