### ISSUE TITLE
Is there a class or something like ActionFilterAttribute for ViewComponents?

### ISSUE THREAD

**Issue by hamidmayeli** [aspnet/Mvc#6700]
Hi all,

Is there a class or something like ActionFilterAttribute, Middleware, Binding etc for ViewComponents to manipulate the passed model?
I have some ViewComponents which have common preprocessing on their models.
```
    public class FooModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class FirstViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(FooModel model)
        {
            return View(model);
        }
    }

    public class SecondViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(FooModel model)
        {
            return View(model);
        }
    }
```

I need to use it like this: `@await Component.InvokeAsync(typeof(FirstViewComponent), new {Id = 1})` And the filter or middleware do this before the method be invoked.

```
    public void Process(TModel model)
    {
        var foo = (FooModel) model;
        foo.Name = LoadFromDatabase(foo.Id);
    }
```
In addition, I need to have access to contexts too.

**Comment by Eilon** [comment]
I don't believe there's anything like filters for view components - @rynowak , is there?

**Comment by rynowak** [comment]
Nope, we don't have anything like this.

**Comment by hamidmayeli** [comment]
@Eilon @rynowak
Thank you for the replay. So what is the solution?

**Comment by Eilon** [comment]
@rynowak could you do this from within a model binder? Do those run "normally" for view components, or is parameter binding done via a different mechanism?

**Comment by rynowak** [comment]
There is no model binding for View Components, your code runs your code. 

The closest/best thing I think you can do is to subclass and replace the `DefaultViewComponentHelper`.

**Comment by Eilon** [comment]
Closing because there are no plans to make changes to this area.
