### ISSUE TITLE
Routes in 2.0 does not work the same as 1.1

### ISSUE THREAD

**Issue by Code-DJ** [aspnet/Mvc#6702]
I have the following routes. This works fine on 1.1, but does not on 2.0.

A call to Entries using "Home/Entries/2" continues to pass 1 to the Entries method in HomeController.

If I change the Entries method to Entries(string id, int pageNo), I see 2 coming into the id variable and 1 into pageNo variable.

```C#
// Startup.cs

routes.MapRoute(
    name: "Entries",
    template: "{controller=Home}/Entries/{pageNo=1}"
);

routes.MapRoute(
    name: "Default",
    template: "{controller=Home}/{action=Entries}/{id?}/{pageNo=1}"
);

// HomeController.cs

public IActionResult Entries(int pageNo)
public ActionResult Category(string id, int pageNo)
```

Changing the routes to the following fixes the issue:

```c#
routes.MapRoute(
    name: "Entries",
    template: "Home/Entries/{pageNo}",
    defaults: new { controller = "Home", action = "Entries", pageNo = 1 }
);

routes.MapRoute(
    name: "Default",
    template: "{controller}/{action}/{id?}/{pageNo}",
    defaults: new { controller = "Home", action = "Entries", pageNo = 1 }
);

```

Created based on discussion in #6660 

---

Changed formatting only by @Eilon.

**Comment by kichalla** [comment]
Few things to note here:
- Try changing the following route:
```
routes.MapRoute(
    name: "Entries",
    template: "{controller=Home}/Entries/{pageNo=1}"
);
```

To

```
routes.MapRoute(
    name: "Entries",
    template: "{controller=Home}/{action=Entries}/{pageNo=1}"
);
```
You should now see a request to `Home/Entries/2` will pass 2

- Also your following route fix isn't the same as the above route as the template here is static (the `Home/Entries` part):
```
routes.MapRoute(
    name: "Entries",
    template: "Home/Entries/{pageNo}",
    defaults: new { controller = "Home", action = "Entries", pageNo = 1 }
);
```
For matter of correctness, this route should be like below:
```
routes.MapRoute(
    name: "Entries",
    template: "{controller}/{action}/{pageNo}",
    defaults: new { controller = "Home", action = "Entries", pageNo = 1 }
);
```

**Comment by Code-DJ** [comment]
@kichalla That is the problem. If I try the new route you gave, it breaks a call to Category - sends null value to id.

```C#
routes.MapRoute(
                    name: "Entries",
                    template: "{controller}/{action}/{pageNo}",
                    defaults: new { controller = "Home", action = "Entries", pageNo = 1 }
                );

                routes.MapRoute(
                    name: "Default",
                    template: "{controller}/{action}/{id?}/{pageNo}",
                    defaults: new { controller = "Home", action = "Entries", pageNo = 1 }
                );
```

**Comment by kichalla** [comment]
To be clear, the code snippet you mentioned in the original post does not work as you would expect even in 1.1. And the behavior that you are seeing (related to Category being broken is expected as the request url would batch the first route) is expected as you have a more generic matching route in the beginning.

Prefer having more specific routes (or use attribute routing) in this case:

```c#
routes.MapRoute(
    name: "Category",
    template: "Home/Category/{id}/{pageNo?}",
    defaults: new { controller = "Home", action = "Category", pageNo = 1 }
);

routes.MapRoute(
    name: "Entries",
    template: "Home/Entries/{pageNo?}",
    defaults: new { controller = "Home", action = "Entries", pageNo = 1 }
);
```

**Comment by Code-DJ** [comment]
The code snippet I mentioned in the original post works correctly on 1.1. Works for Entries and Category. It does not work on 2.0.

Changing the first route to a static route (as shown in the original post) fixes the issue on 2.0.

Frankly for me, if you provide me with routes that work for the following I will be happy and will let you decide if the routes should continue to work as is between 1.1 and 2.0

/
/Home/Entries
/Home/Entries/1
/Home/Category/foo
/Home/Category/foo/1

Where the number is pageNo, foo is the id

**Comment by kichalla** [comment]
You could use the following routes for the scenarios that you listed above. Ordering the routes from most specific to least specific.
```c#
app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "Category",
        template: "Home/Category/{id}/{pageNo?}",
        defaults: new { controller = "Home", action = "Category", pageNo = 1 }
    );

    routes.MapRoute(
        name: "Entries",
        template: "{controller=Home}/{action=Entries}/{pageNo=1}"
    );
});
```

**Comment by Code-DJ** [comment]
I was mistaken. I had played with 1.1 on my local machine and had assumed that code was on the server. The following route works on .net 4.6 which is what I have deployed to the server:

```C#
routes.MapRoute(
    name: "Entries",
    template: "{controller=Home}/Entries/{pageNo=1}"
);

routes.MapRoute(
    name: "Default",
    template: "{controller=Home}/{action=Entries}/{id?}/{pageNo=1}"
);
```

Based on @kichalla it looks like that never worked on .net core.
Since I have more than one routes that require an optional {id} and {pageNo} and only one route "Entries" that doesn't need {id}, only needs an optional {pageNo}, I will continue to use the following that works:

```C#
 routes.MapRoute(
    name: "Entries",
    template: "Home/Entries/{pageNo}",
    defaults: new { controller = "Home", action = "Entries", pageNo = 1 }
);

routes.MapRoute(
    name: "Default",
    template: "{controller}/{action}/{id?}/{pageNo}",
    defaults: new { controller = "Home", action = "Entries", pageNo = 1 }
);
```
