### ISSUE TITLE
Custom TagHelper that binds Scripts src attribute + asp-append-version="true" destroys script tag output

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#6703]
If you have the following TagHelper:
```C#
public class ScriptTagHelper : TagHelper
{
    public string Src { get; set; }
}
```

The following:
```HTML
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
```

Results in the following HTML:
```HTML
<script></script>
<script src="/lib/bootstrap/dist/js/bootstrap.js?v=Cr6N6zNN4bp0OwTQOZ6Z66M2r-2dpy_EwKMCyZ-SOMg" src="/lib/bootstrap/dist/js/bootstrap.js"></script>

```

**Comment by Eilon** [comment]
Is the "bug" in the existing ScriptTagHelper because it's doing something weird?

**Comment by NTaylorMullen** [comment]
> Is the "bug" in the existing ScriptTagHelper because it's doing something weird?

Possibly. I did not investigate thoroughly. The two TagHelpers  that are probably causing the issue are the `UrlResolutionTagHelper` and the `ScriptTagHelper`

**Comment by Eilon** [comment]
Was this your own find, or is it from another discussion? That would help establish the priority.

**Comment by NTaylorMullen** [comment]
@madskristensen discovered it.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, can you please look into this?

**Comment by NTaylorMullen** [comment]
So this issue is due to the `UrlResolutionTagHelper` running prior to every other TagHelper in the system and then expecting specific URLs to exist on `TagHelperOutput`. 

So in the case described in this issue we have a user written `ScriptTagHelper` that binds `Src`. This binding process removes the `src` attribute from `TagHelperOutput` prior to ANY TagHelper running. Therefore, when the `UrlResolutionTagHelper` runs before the `ScriptTagHelper` it ends up not seeing any `src` attribute.

This behavior as odd as it seems is by design. The reason why is that any TagHelper that binds an attribute takes control of that attributes rendering. Since the user written `TagHelper`s bound `Src` attribute is never re-propagated onto the `TagHelperOutput` it then destroys the final Script output.

Solutions to this problem are:
1. Have the user written `TagHelper` perform any logic on that src and then add it back to the `TagHelperOutput.Attributes`.
2. Run your own custom TagHelper prior to the UrlResolutionTagHelper (< -2000)
