### ISSUE TITLE
asp.net core 2.0  with net461 and win7-x64 doesn't work

### ISSUE THREAD

**Issue by John0King** [aspnet/Mvc#6709]
The default asp.net core 2.0 template   with `<TargetFramework>net461</TargetFramework>`  and   `<RuntimeIdentitifer>win7-x64</RuntimeIdentitifer>`   doesn't work .
It throw:
```
BadImageFormatException: 未能加载文件或程序集“dotnet-aspnet-codegenerator-design”或它的某一个依赖项。试图加载格式不正确的程序。
```

**Comment by pranavkm** [comment]
Might be a dup of https://github.com/aspnet/Scaffolding/issues/601. cc @prafullbhosale

**Comment by prafullbhosale** [comment]
Yup, that is correct. It is the same issue. The workaround is to remove the package reference `Microsoft.VisualStudio.Web.CodeGeneration.Design` (This will disable scaffolding)
