### ISSUE TITLE
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.TempDataSerializer' cannot serialize an object of type

### ISSUE THREAD

**Issue by cgountanis** [aspnet/Mvc#6711]
I would like to store a ViewModel into TempData for a wizard type of functionality. I get that error when I try and store a simple class even with [Serializable] on top of class. Recommendations?

**Comment by Eilon** [comment]
@cgountanis the TempData serializer currently supports only a limited set of data types for simplicity. It supports a few primitive types such as int, string, and bool, and simple containers of those types, such as lists. The `[Serializable]` attribute has no effect on this.

We'll discuss this with the team to see what we can change here.

**Comment by cgountanis** [comment]
Using this solution for now, seems to work well.

https://stackoverflow.com/questions/34638823/store-complex-object-in-tempdata-in-mvc-6

**Comment by Eilon** [comment]
@cgountanis yeah I think that suggestion is the way to go if you need custom data types in TempData.

**Comment by Eilon** [comment]
We'll consider opening up the TempData default serializer to support whatever Json.NET supports, though there are no plans to do that at this time.

We can also consider making the TempData serializer itself pluggable (which I think it was in MVC 5.x).

**Comment by Eilon** [comment]
Actually, closing this as a dup of https://github.com/aspnet/Mvc/issues/4190, which is an older bug.
