### ISSUE TITLE
Simplified Chinese characters are garbled in project files

### ISSUE THREAD

**Issue by HeMinzhang** [aspnet/Mvc#6716]
I use Visual Studio community 2017  15.3.1 create a asp.net core 2.0 angular project.But simplified Chinese characters garbled.
I convert 
project\ClientApp\app\components\app\app.component.html project\ClientApp\app\components\home\home.component.html
project\ClientApp\app\components\fetchdata\fetchdata.component.html

Ansi file format to uft8 file.
simplified Chinese characters show normal.Can you fix the bug?

**Comment by Eilon** [comment]
@HeMinzhang we need more information to understand this issue. Can you please upload an app to GitHub so that we can investigate?

**Comment by khellang** [comment]
Sounds like an issue with the templates and which encoding is used when scaffolding a project...

**Comment by Eilon** [comment]
Certainly could be.

@SteveSandersonMS - these files look like they're from the SPA template - is there any weird file encoding going on there? I think we normally do UTF-8 without BOM.

**Comment by SteveSandersonMS** [comment]
@Eilon It looks like we're inconsistent about whether files include a BOM or not. Most (but not all) of the `cshtml` ones in `StarterWeb-CSharp` (i.e., MVC starter site) **do** have BOMs, whereas most of them (possibly all, didn't check) in `RazorWebPages-CSharp` **do not** have BOMs.

As a specific example, the MVC starter site's [`TwoFactorAuthentication.cshtml`](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Views/Manage/TwoFactorAuthentication.cshtml) does *not* have a BOM, whereas the file [`SetPassword.cshtml`](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Views/Manage/SetPassword.cshtml) alongside it in the same directory *does* have a BOM.

The SPA templates most similar to the RazorWebPages one in that they don't have BOMs except for some `.cs` files that were apparently originally copied from something like StarterWeb-CSharp`.

The net result of all this is that if you paste a simplified Chinese character into a non-BOM file and save it in VS, then VS will prompt you asking for permission to "change the encoding" (by which it means save with a BOM). If you say yes, all is well. If you say no, well, garbling ensues.

**What to do about it**

At the very least we should be deliberate and consistent about where BOMs are used or not.

As for a general policy, the Unicode spec is ambiguous:

> Use of a BOM is neither required nor recommended for UTF-8 [[source](https://stackoverflow.com/a/2223926)]

... but do they mean *"we recommend that you don't"*, or do they mean *"we are neutral on this subject and offer no recommendation"*? Aside from the extra 3 bytes per file and loss of compatibility with ancient pre-UTF-8 editors, I'm not sure if there's any drawback to putting in BOMs everywhere.

It would certainly help developers avoid issues with this if we did put BOMs on all the text files.

**Comment by HeMinzhang** [comment]
[WebApplication1.zip](https://github.com/aspnet/Mvc/files/1285090/WebApplication1.zip)

**Comment by Eilon** [comment]
@SteveSandersonMS I think that phrasing is generally used to mean "it is not required and it is not recommended to use," which agrees with what I've heard from others - i.e. don't use a BOM.

But either way, I completely agree that all the template files need to be consistent. And beyond that, we need a test that checks for BOM presence (or un-presence).

@rynowak / @Tratcher - I think maybe you've had opinions on BOMs before. Any thoughts on this?

**Comment by Tratcher** [comment]
UTF-8 encode all the files. The BOM should only be excluded when transmitting over the network, as the encoding is specified in a header.

**Comment by Eilon** [comment]
Everything here is already all UTF-8. The question is only whether the files on disk should have a BOM or not.

**Comment by Tratcher** [comment]
Yes? How else do you save the encoding for the file? In additional metadata?

**Comment by rynowak** [comment]
Yeah, I'm not the expert on this. We should talk to the tooling team.

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#5
