### ISSUE TITLE
UseStatusCodePagesWithReExecute does not re-execute

### ISSUE THREAD

**Issue by irashid25** [aspnet/Mvc#6717]
Hi all,

I am trying to add custom error pages to my application (asp.net core 2.0 - VS 15.3.1) using UseStatusCodePagesWithReExecute.

My startup's Configure method looks like so:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            //if (env.IsDevelopment())
            //{
            //app.UseDeveloperExceptionPage();
            //}
            //else
            //{
            app.UseStatusCodePagesWithReExecute("/Home/Errors/{0}");
            //}

            app.UseStaticFiles();

            loggerFactory.AddNLog();
            app.AddNLogWeb();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```
My default Home controller is shown below:

```
    [Route("Home")]
    [Route("")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Route("")]
        [Route("Index")]
        public string Index()
        {
            throw new NotImplementedException();
        }

        [Route("Errors/{errorCode}")]
        public IActionResult Errors(string errorCode)
        {
            var requestedUrl = HttpContext.Features.Get<IStatusCodeReExecuteFeature>()?.OriginalPath;
            switch (errorCode)
            {
                case "404":
                    return View(errorCode);
                // Log error including requested URL
                case "500":
                    // add logging
                    return View(errorCode);
                default:
                    // add logging
                    return View("Error");
            }
        }
    }
```
On startup the index action is called and a not implementation exception is thrown. I would then *expect* another request to be executed to the Errors action (with an errorcode of 500) where i a display a custom error page.  

Instead the Errors action is not called and all i get in the browser is a blank page. The browser console does show the standard "the server responded with a status of 500...".

Can anyone shed any light on on why the errors action is not called?

Thanks.

**Comment by Eilon** [comment]
I started taking a look at this and I'm not sure exactly why this isn't working.

I did notice some problems in the original code, such as the action name being `Errors`, yet sometimes it returns `View("Error")`, and in the default ASP.NET Core templates the error view is `Error.cshtml`, so the mix of Error vs. Errors is sometimes a problem.

But I still can't seem to get the re-execute to work...

Also cc @Tratcher in case you have any ideas.

**Comment by Tratcher** [comment]
UseStatusCodePagesWithReExecute is for status code responses without bodies (e.g empty 404). It is not for exceptions. You're looking for UseExceptionHandler.

**Comment by irashid25** [comment]
Hi

Thanks for looking into this.
@Tratcher - I found a blog post that also does what i am trying to do. 
https://andrewlock.net/re-execute-the-middleware-pipeline-with-the-statuscodepages-middleware-to-create-custom-error-pages/

The reason why i want to go down this path is that if there is error in the application, i want to send back an appropriate error response so that it is semantically correct.

**Comment by Tratcher** [comment]
Nothing in that post is referring to exceptions, only to status code responses. You can use both UseExceptionHandler and UseStatusCodePagesWithReExecute in your app to handle both scenarios.

**Comment by irashid25** [comment]
@Tratcher I can see where you coming from now.

Just a couple of questions before you/I close this issue:

1. Will i be able to use the exceptionhandler to send back appropriate status codes? For example, if my action method handles an exception and displays a custom error page, will a 500 server error be delivered in the response or a 302 redirect to the error page? I will check this out myself, but if the answer is no, then what are my options. You mentioned i can use both, then how could i use them to show a custom error view and send the correct error status code back to the browser?
2. Does you advice apply to an application that contains both MVC and WebApi controllers?

Thanks

**Comment by Tratcher** [comment]
Yes, your action method for handling exceptions can generate any response it wants, including setting the status code.
Things get more interesting for MVC + WebApi apps. You may have to check the Accept header to decide how to format your error response.

UseStatusCodePagesWithReExecute makes more sense for MVC views than it does for WebApis. WebApi clients tend to check the status code and don't care if there's an empty body.

**Comment by irashid25** [comment]
Thanks @Tratcher 

That makes a lot of sense.
