### ISSUE TITLE
Way to remove BOM from JsonResult response (ASP NET Core 1.1)

### ISSUE THREAD

**Issue by Frank591** [aspnet/Mvc#6719]
I have simple .net core wep api application with contoller method like that

```
   [HttpGet("{id}")]
    public ActionResult  Get(int id)
    {
        var myObj= _testRepository.TryGetById(id);
        if (myObj== null)
        {
            return new NotFoundResult();
        }
        return new JsonResult(myObj);

    }
```

curl -ivs --raw for this method returns json response with BOM symbols.

Response example:
```
92
{"id":767,"gender":"f","birth_date":-278121600}
0
```

How can i remove BOM from response?

**Comment by Frank591** [comment]
Some additional information:

After some research inside JsonResultExecutor i  got net steps:
1.
```
  private static Encoding GetEncodingFromCharset(StringSegment charset)
    {
      if (charset.Equals("utf-8", StringComparison.OrdinalIgnoreCase))
        return Encoding.UTF8;
          ...
```
2.
```
 public static Encoding UTF8
    {
      get
      {
        return (Encoding) UTF8Encoding.s_default;
      }
    }
```
3.
```
  public class UTF8Encoding : Encoding
  {
    internal static readonly UTF8Encoding s_default = new UTF8Encoding(true);
```

Why all JsonResult responses applys BOM by default and how i can change that behavior to remove BOM?

**Comment by rynowak** [comment]
This code path should use `HttpResponseStreamWriter` which does not write a bom regardless of the encoding used.  Have you done something to customize this? Also ASCII 92 is `\` and isn't part of the UTF8 bom

**Comment by rynowak** [comment]
Actually, I believe what you're looking at here is [chunked transfer encoding. ](https://en.wikipedia.org/wiki/Chunked_transfer_encoding).

I'm guessing that `{"id":767,"gender":"f","birth_date":-278121600}` was originally 92 characters long and you removed from the person information from it.

**Comment by Eilon** [comment]
Yeah this is exactly chunked transfer encoding.

However, I'm not sure by what mechanism you can change from chunked to buffered.

@Tratcher - what's the trick for that?

**Comment by Tratcher** [comment]
Clients transparently filter out the chunking. You're only seeing it because of the `--raw` flag.

**Comment by Eilon** [comment]
@Frank591 it would also be helpful to us to understand if there's a particular problem you're experiencing, or if it's just curiosity about the wire format.

**Comment by Frank591** [comment]
Thanks for answer. Now i understand, that is actually chunked transfer encoding.
Here full answer example from kestrel:

```
HTTP/1.1 200 OK
Date: Sat, 26 Aug 2017 12:28:58 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

60
{"id":582,"place":"Площадь","country":"Япония","city":"Ньюква","distance":86}
0

```
But is there way to disable that behavior for api controller or method? 
Rigth now i am using `ContentResult ` as workaround, but `JsonResult ` seems better if chunked transfer encoding can be disabled.
 PS Sorry for my bad English

**Comment by Tratcher** [comment]
Why do you need to disable it? Most clients already remove the chunking for you.

The only way to disable it is to fully buffer the response and determine the content-length. Here's a sample that buffers all responses in middleware, but I don't know of a way to do this only for one MVC action.
https://github.com/aspnet/BasicMiddleware/blob/793a49fe111d86895f22300297fa70f710459406/src/Microsoft.AspNetCore.Buffering/ResponseBufferingMiddleware.cs#L19

**Comment by Frank591** [comment]
> Why do you need to disable it? Most clients already remove the chunking for you.
I have troubles when get requests from IOS app. Unfortunately communication with IOS app developers is very bad, and they can't (or don't want) fix that. So fix on side of my API quicker and cheaper.
Thanks for answers and link! Will try to use that.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
