### ISSUE TITLE
RazorEngine and LazyMetadataReferenceFeature circular dependency problem when property injection is enabled

### ISSUE THREAD

**Issue by hikalkan** [aspnet/Mvc#6732]
Hi,

I'm using Autofac as DI container. I (somehow) enabled property injection for all services. Now, I'm getting stackoverflow exception because of circular dependency between RazorEngine and LazyMetadataReferenceFeature.

RazorEngine is registered as Singleton with a factory method like that (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/DependencyInjection/MvcRazorMvcCoreBuilderExtensions.cs#L158):

````C#
services.TryAddSingleton(s =>
{
    return RazorEngine.Create(b =>
    {
        RazorExtensions.Register(b);

        // Roslyn + TagHelpers infrastructure
        var metadataReferenceFeature = s.GetRequiredService<LazyMetadataReferenceFeature>(); //HERE!!!
        b.Features.Add(metadataReferenceFeature);
        b.Features.Add(new Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature());

        // TagHelperDescriptorProviders (actually do tag helper discovery)
        b.Features.Add(new Microsoft.CodeAnalysis.Razor.DefaultTagHelperDescriptorProvider());
        b.Features.Add(new ViewComponentTagHelperDescriptorProvider());
    });
});
````

And LazyMetadataReferenceFeature has a public RazorEngine property with setter (that causes the to property injection - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/LazyMetadataReferenceFeature.cs#L27):

````C#
public class LazyMetadataReferenceFeature : IMetadataReferenceFeature
{
    private readonly RazorReferenceManager _referenceManager;

    public LazyMetadataReferenceFeature(RazorReferenceManager referenceManager)
    {
        _referenceManager = referenceManager;
    }

    ...

    public RazorEngine Engine { get; set; }  //HERE!!!
}
````

So, can you remove setter. You can add a ``SetEngine(...)`` method if you need it.

You can say that "just do not enable property-injection for classes of Asp.Net Core MVC framework). I may do it with Autofac. But some other DI frameworks has property-injection built in (like Castle Windsor). I suggest you to design classes property-injection in mind since it's a widely used technique (even you may add it to default DI system in the future).

**Comment by pranavkm** [comment]
cc @rynowak 

@hikalkan is there a way to set up Autofac to specifically ignore some properties for DI? `IMetadataReferenceFeature.Engine` is meant to be assigned when a feature is registered with the engine and isn't meant to be activated via DI.

**Comment by Eilon** [comment]
I would imagine that there would be all kinds of problems like this across ASP.NET/EF Core with automatic property injection. None of the types in these libraries were designed with property injection in mind, and I'm pretty sure that can't change without it being a huge breaking change.

**Comment by hikalkan** [comment]
@pranavkm I don't know if specific properties can be excluded without modifying those classes. I will try to solve it by enabling property injection only for classes in my own assemblies. Thanks.

@Eilon I understand it. I takes huge effort to find and fix all of them. However, at least, you should discuss it in your team because property injection is a very common technique.

Thank you for your responses.
