### ISSUE TITLE
how can I add public validate in BasePageModel

### ISSUE THREAD

**Issue by JamesYing** [aspnet/Mvc#6735]
I created a BasePageModel on my project and All pagemodel inheit it.
Now I want to check a property , if the property is null goto the anthor page.It look like identity authorize.
I added a validate function at BasePageModel construction, but the Response is null.
Please help me tell me how can I added a public validate function and redirect another page.

Thanks

**Comment by Eilon** [comment]
Hi @JamesYing , can you show the code of your project (either the entire project, or just the relevant parts of the code) so that we can investigate?

If you have a method on your `BasePageModel` class you can certainly just call it from within your page code and then do whatever you want.
