### ISSUE TITLE
Area Route not working after upgrading to Core 2.0

### ISSUE THREAD

**Issue by simonpbond** [aspnet/Mvc#6737]
I have two areas in my project:

`Client` and `Web`

The **client** area uses attribute routes (as it's mostly an api and easier that way).

The **web** area is for the web portal and has routes setup in the startup.cs:

`routes.MapRoute("web_route", "{controller}/{action}/{id?}",  
defaults: new { area = "Web", controller = "Home", action = "Index" }, constraints: new { area = "Web" });`  

The above used to make the default always route to my web area (for the web portal).
After upgrading to .NET Core 2.0 it no longer seems to work.

The strange thing is, it works perfect when accessing via the **https** site, but only fails when trying to access via the **http** site (iisexpress).

I have tested the default web app template, both **http** and **https** work, this only breaks on http when I add my route (above) back, leaving me only with **https** access.

I should also point out I'm using AspNetCore.All v2.1.0-preview1-26869 , as I'm using SignalR Core in the project (same build number).

**Comment by Eilon** [comment]
Routing doesn't ever look at the incoming scheme (HTTP vs. HTTPS), so this is quite odd. Maybe there's some other component in the way that's changing the URL? Are you using any other middleware, such as the URL Rewrite middleware, or anything else that might affect the URL?

**Comment by simonpbond** [comment]
@Eilon  
Had nothing to do with .Net Core 2.0
It was (Home Controller) [RequireHttps] attribute. 

The problem is always in the most logical place!
