### ISSUE TITLE
Support Code Generation participation in TagHelpers

### ISSUE THREAD

**Issue by hishamco** [aspnet/Mvc#6739]

**Comment by NTaylorMullen** [comment]
Hey @hishamco we've done a lot of work in this area over in `aspnet/Razor`. I encourage you to take a look at how we handle `TagHelperIntermediateNode`s during the code generation process.

**Comment by hishamco** [comment]
Of course I will do, I knew it's a huge work item, but it will give a developers more power to create crazy stuff 😄 such as generate `Item` in `ReapeaterTagHelper` or ImageTagHelper enhancement [here](https://github.com/aspnet/Mvc/issues/2249#issuecomment-100026138)

**Comment by Eilon** [comment]
Do we have specific concrete scenarios for what this would be for? What isn't possible (or is too difficult) to do with the current API?

**Comment by hishamco** [comment]
I wrote a blog post two weeks ago [Why we do not have a TagHelper Interceptor?](http://www.hishambinateya.com/why-we-do-not-have-a-taghelper-interceptor), to explain the needs of code generation participation

I don't think the current APIs allow us to participate in the code generation, @DamianEdwards yesterday in the ASP.NET Standup Community said "This is a huge work item"

IMHO enabling such feature will allow us to do more than what the current `TagHelper`, these are some of the use cases:
1- Generate a custom fields or properties such as `Item` in `RepeaterTagHelper` to allow us to hold the current item in the current collection
2- Doing crazy stuff with `ImageTagHelper`, you can refer to @DamianEdwards comment [here](https://github.com/aspnet/Mvc/issues/2249#issuecomment-100026138)
3- And much more ..

**Comment by rynowak** [comment]
> "This is a huge work item"

**Comment by hishamco** [comment]
Exactly!!

**Comment by Eilon** [comment]
Closing because there are no plans to implement this in the near future. When we think it's a suitable work item for a release, we'll start a new discussion and gather broader inputs to come up with a design.
