### ISSUE TITLE
Response cache doesn't work on reazor pages

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#6747]
_From @cyrusel on September 1, 2017 8:7_

I configured ResponseCache in configure and configure services sections and then put response cache attribute in a simple razor page before Page model class but it didn't work. Form method is "get" and no special feature has implemented to prevent response cache to work. 
Where should response cahce attribute be placed in razor pages? why it doesn't work? (asp.net core 2.0 final release)

Thanx

_Copied from original issue: aspnet/ResponseCaching#136_

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/6437. The feature unfortunately did not make it in to 2.0.0 RTM. It's not entirely painless, but you could look at the PR to enable it in 2.1 - https://github.com/aspnet/Mvc/commit/900a5c7c4c789e71bf18e8e90bf9b28b4e51013f - if you'd like to port it over to your 2,0 application.
