### ISSUE TITLE
Testing via Postman with Cookie based Auth

### ISSUE THREAD

**Issue by paulpatarinski** [aspnet/Mvc#6748]
I have a dotnet core app using Cookie based auth 

Startup.cs

```
  app.UseCookieAuthentication(new CookieAuthenticationOptions()
      {
        AuthenticationScheme = "Cookies",
        AutomaticChallenge = true,
        SlidingExpiration = true,
        ExpireTimeSpan = expireTimespan
      });
```

I am trying to write integration tests for some of the endpoints using Postman & having trouble figuring out how do I obtain a valid session cookie without using the browser to login? Tried following the steps suggested in [this stackoverflow](https://stackoverflow.com/questions/39081232/asp-net-weapi-authorization-postman)...no luck.

**Comment by Eilon** [comment]
I would think you'd need to simulate a client doing the login process in order to get a cookie. I'm not sure there's any other way in - otherwise I think that'd be a security problem.

@javiercn - any thoughts on this w/ the testing infrastructure you've been working on?

**Comment by javiercn** [comment]
I'm not sure how you are writing the test. If you are sending HTTP requests and responses from Postman I would imagine you need to get a cookie by just login on the website, opening the developer tools, copying the cookie and putting it as a header on your HTTP requests.

That said, I'm not sure how you are writing E2E tests, so I can't really offer you guidance.
Alternatively you can look at some of the tests we write in memory that deal with cookies. Like here https://github.com/aspnet/Identity/blob/dev/test/Microsoft.AspnetCore.Identity.Service.FunctionalTests/TraditionalWebApplicationTests.cs#L22

**Comment by Eilon** [comment]
To fully automate this you wouldn't use dev tools to get a cookie because that cookie would not be valid once you automate the test (which I believe is the purpose of this exercise). You need to automate the login process to submit a username/password and get back the cookie and then use that cookie on the subsequent request(s).

**Comment by paulpatarinski** [comment]
@javiercn sorry made an unfair assumption that you are familiar with Postman. Postman has several different clients (chrome extension,win/osx desktop).  More info [here ](https://www.getpostman.com/). It is similar in functionality to the fiddler composer with the added ability to make assertions against the http response. The solution you mentioned of using the browser to get the cookie & copy/pasting it as a header works, but as @Eilon mentioned is not a viable solution for automation (since it includes manually retrieving the cookie).

**Comment by javiercn** [comment]
I'm not sure postman is the right tool for the job here. The only way to get a real cookie is to either log in (and pass it along to the next request you send if you can do so) or have an endpoint where you can forge one and pass it to the next request you craft.

IMO, postman is the wrong tool for the job here. I would suggest you look at the test that I pointed you as an alternative approach or at some of the functional tests we have on MVC that run the entire test in memory and just use a plain HTTP Client to do everything.

**Comment by Eilon** [comment]
@javiercn - can you point @paulpatarinski at examples of tests we have that might be doing something similar?
