### ISSUE TITLE
Using AddApplicationPart(typeof(Startup.Assembly)) makes Razor Pages throw AmbiguousActionException

### ISSUE THREAD

**Issue by rmja** [aspnet/Mvc#6749]
To discover controllers in the target assembly when integration testing (different from the integration test assembly) I usually do:

```
services
   .AddMvc()
   .AddApplicationPart(typeof(Startup).Assembly));
```

This all works fine when the executing assembly is different than `typeof(Startup).Assembly`, which it is when integration testing.

When _not_ testing, the `.AddApplicationPart(typeof(Startup).Assembly))` seems to be re-adding the default executing assembly. As a consequence I see the folllowing behavior:

It seems as if [this line](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.RazorPages/Internal/CompiledPageRouteModelProvider.cs#L96) returns all the discovered razor pages duplicated as can be seen in the screenshot:

![image](https://user-images.githubusercontent.com/2112306/29980117-9a55a2fc-8f48-11e7-94ab-97106c17c50a.png)

I guess the problem has to do with the adding [here](https://github.com/aspnet/Mvc/blob/1c4b0fcdf38320b2f02c0bb7c31df5bd391ace07/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreMvcBuilderExtensions.cs#L81) where it is not checked whether the assembly is already existing.

**Comment by Eilon** [comment]
@javiercn @pranavkm - any ideas on this?

**Comment by pranavkm** [comment]
We don't de-duplicate application parts. Consequently views for the same path are re-discovered via two instances of the same assembly part. One option is to de-duplicate it in the input i.e. `ApplicationPartManager.ApplicationParts`. Presumably this would avoid additional work during controller discovery, redundant references to view compilation etc. The other alternative is to perform the de-duping in the `ViewsFeatureProvider` \ `CompiledPageActionDescriptorProvider` i.e. avoid doing work if we've already seen the exact instance of `RazorPageAttribute`.

**Comment by javiercn** [comment]
@pranavkm Is absolutely right. If you add additional parts you are responsible to make sure you are not adding duplicates. I would just check if the part is already there before adding it.

**Comment by rmja** [comment]
@javiercn ok. So I guess I have to see if the assembly I am adding is the executing one or not, as it is there already by default.  This just seems to be something that could hit others when integration testing, and the thrown exception  doesn't give any good indication about what is causing the issue.

**Comment by rmja** [comment]
For anyone that hits this issue, this is an extension method I wrote to get around the problem:

```
        public static IMvcCoreBuilder TryAddApplicationPart(this IMvcCoreBuilder builder, Assembly assembly)
        {
            builder.ConfigureApplicationPartManager(manager =>
            {
                if (!manager.ApplicationParts.OfType<AssemblyPart>().Any(x => x.Assembly == assembly))
                {
                    manager.ApplicationParts.Add(new AssemblyPart(assembly));
                }
            });

            return builder;
        }
```
