### ISSUE TITLE
Extension point after action has been resolved and before model binding

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Mvc#6761]
Hi, I want to write a plugin for Mvc and I need it to execute code after the action has been resolved but before model binding has started so I can access the request stream before it is read.

`ActionFilterAttribute` is the most talked about option but `OnActionExecutionAsync` is run after model binding has completed and so the request stream has already been read.

What options are available?

**Comment by JamesNK** [comment]
(I know I could write middleware that reads the request body into a memory stream and replaces the request body stream but I want to have access to the action so the request body is only replaced when needed)

**Comment by rynowak** [comment]
[Resource Filter](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters#resource-filters) sound slike what you need

**Comment by JamesNK** [comment]
Looks good. Documentation on https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters is great.

 Thanks!
