### ISSUE TITLE
HTTP 404 with ASP.NET Core  when controllers are added from a seperate assembly

### ISSUE THREAD

**Issue by midumitr** [aspnet/Mvc#6762]
Im trying to build a multitenant application with parallel piplines per tenant in order to configure each tenant. 
If i reference the assemblies that contains the controllers in the main app the controllers are discovered and returns 200 when i call them. 
If the controller is not referenced and i load it dinamically , the controller is found but returns 404 when i call any action from it. 
For this i create a new WebHost with CreateDefaultBuilder and i load the services from the assemblies in ConfigureServices(). I use the service provider created to replace the one in httpcontext.RequestServices 
See this exemple:  https://www.strathweb.com/2017/04/running-multiple-independent-asp-net-core-pipelines-side-by-side-in-the-same-application/ 
In MVC i add all the assemblies as parts and call AddControllersAsServices() just in case that are not resolved. 
I use Asp.Net Core 2.0.0 and the assemblies are netstandard2.0

**Comment by rmja** [comment]
You need to

```
services.AddMvc().AddApplicationPart(theOtherAssembly);
```

**Comment by midumitr** [comment]
I used that but does not work 
First i used it like this  : 
foreach (var assembly in assemblies)
                {
                    builder.AddApplicationPart(assembly); 
                }

Like this the controller was not even detected. I used Swagger to see the controllers. I noticed that the controller and the services from the assembly are registered in the ServiceCollection but as i said returns 404

I change that to this  : 
var dir = new DirectoryInfo(@"C:\packages");

                var parts = new List<ApplicationPart>();
                foreach (var item in dir.GetFileSystemInfos("*.dll"))
                {
                    var assembly = Assembly.LoadFrom(item.FullName);
                    var ass = DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts(Path.GetFileNameWithoutExtension(item.FullName));
                    parts.AddRange(ass);

               
                    
                }
                foreach (var item in parts)
                {
                    builder.PartManager.ApplicationParts.Add(item);
                }
                
 builder.AddControllersAsServices(); 


With this swagger now see the controller but is i still get 404

**Comment by Eilon** [comment]
@javiercn - any ideas on this?

**Comment by midumitr** [comment]
Note that this worked fine in version 1.0,

**Comment by javiercn** [comment]
A couple of questions:
Can you provide your startup code?

Can you inject an ActionDescriptorCollectionProvider.cs into your action and list all the actiondescriptors in there to make sure your controllers are there?

We haven't changed anything in that area since 1.1 so I'm not sure what can be happening in your case.

**Comment by midumitr** [comment]
Hi,  

Thanks for the reply. I created this git https://github.com/midumitr/ModularCoreApp
Please have a look.

**Comment by javiercn** [comment]
Hi, I've looked at your sample for a while and it doesn't seem to be any problem with application parts. Your controllers get discovered and your actions are present. I'm more inclined to think that you have some problem somewhere in your pipeline. In your case you are building the entire pipeline on each request and that strikes me as wrong. Given the type of application that you are trying to build, I would suggest you look at something like Orchard. You can find a basic sample at  https://github.com/OrchardCMS/OrchardCore.Samples

**Comment by alexsandro-xpt** [comment]
I guess it's not about a multi tenant application, but a modular application.

**Comment by midumitr** [comment]
Hi, thanks for the reply. I found the problem, and as you mentioned was in the pipeline that i was building. 
You can close this issue. I solved it. Thanks for looking into it.
