### ISSUE TITLE
New Razor Page doesn't have Intellisense

### ISSUE THREAD

**Issue by jchadwick** [aspnet/Mvc#6764]
After creating a new Razor Page using the Razor Page item template in VS 2017 15.3.0 and Microsoft.AspNetCore.All v2.0.0, the .cshtml file is opened but Intellisense does not work until you close the file and re-open it.

**Comment by NTaylorMullen** [comment]
Hey @jchadwick sorry to hear that! Although the item template vs. scaffolding are slightly different beasts I believe this is related to https://github.com/aspnet/Scaffolding/issues/514.

@Eilon where do we file item template issues?

**Comment by Eilon** [comment]
@NTaylorMullen you mean issues w/ the *contents* of item templates?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen you mean issues w/ the contents of item templates?

Sorry, no. Issues with how they result in the editor being opened.

**Comment by jchadwick** [comment]
The contents are fine.  If you close the view and re-open it again everything works fine.

**Comment by Eilon** [comment]
@NTaylorMullen - talk to @barrytang to find out where to file.

**Comment by barrytang** [comment]
@phenning, I believe this is fixed in 15.3. Can you confirm?

/cc @mlorbetske @balachir

**Comment by jchadwick** [comment]
Are you talking about VS?  I'm using 15.3.0.

**Comment by A7medRamadan** [comment]
i have the same issue, there is no Intellisense with the new Razor pages

**Comment by phenning** [comment]
@barrytang 

I was not able to repro this on latest builds when starting with a new Razor web application and creating new pages in the Pages folder.

I was able to repro this though if I started with an MVC template and create new razor pages without first adding a @namespace directive to either the cshtml file itself or via a _ViewImports.cshtml file. 

The workaround of closing and reopening does not appear to work for me unless the namespace is present though.

If I update/add the expected namespace to the _ViewImports.cshtml before creating the item template, the issue does not reproduce either.

**Comment by jchadwick** [comment]
@phenning  I have that issue with @namespace as well, but that's a different issue in addition to this. :)

**Comment by barrytang** [comment]
I talked to Phil and Mike offline and this is fixed in 15.4 not 15.3. I ported the issue to https://developercommunity.visualstudio.com/content/problem/108727/new-razor-page-doesnt-have-intellisense.html. If you follow it, you will get notified when 15.4 is available publicly.

**Comment by Eilon** [comment]
Ok sounds like this issue can be closed then.
