### ISSUE TITLE
How to get ASP.NET Core MVC Filters from HttpContext

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#6767]
I'm trying to write some middleware and need to know if the current action method (if any) has a particular filter attribute, so I can change behaviour based it's existence.

So is it possible to get a filters collection of type `IList<IFilterMetadata>` like you do on the `ResourceExecutingContext` when you are implementing an `IResourceFilter`?

**Comment by rynowak** [comment]
We're going to be doing some work to enable scenarios like this in the future. Today there is no straightforward way to do this as the decision about *what* action has been chosen hasn't been made until after middleware run.

If you can provide more information about what you're trying to do we can try to help.

/cc @davidfowl

**Comment by RehanSaeed** [comment]
I'm looking into porting my `RedirectToCanonicalUrl` MVC filter to be based on the ASP.NET Core URL rewrite middleware because I thought that would reduce the number of redirects to get from a HTTP and non-canonical URL to a HTTPS and canonical URL (but it looks like I [might be wrong](https://github.com/aspnet/BasicMiddleware/issues/262)).

I use `IOptions<RouteOptions>` for the `AppendTrailingSlash` and `LowercaseUrls` settings and then
I use marker attributes `[NoTrailingSlash]` and `[NoLowercaseQueryString]` on action methods to change the behaviour of the canonical URL generation process. Since `[RedirectToCanonicalUrl]` is an MVC filter, I currently have access to `IList<IFilterMetadata>` through the `ResourceExecutingContext`.

**Comment by rynowak** [comment]
That's a pretty cool usage of metadata to scope behavior. Sad that there's no easy way to make this work today but this is the kind of thing we're looking to enable with some work in 2.1

**Comment by RehanSaeed** [comment]
Cool, will wait for 2.1 and the result of https://github.com/aspnet/BasicMiddleware/issues/262 to port my filter.

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue.   We'll consider your feedback as part of an existing issue we're tracking as part of our planning.

**Comment by sakopov** [comment]
As far as I understand this is still not available, is this correct?

**Comment by rynowak** [comment]
Correct, there has been no change in this area and no will be no change in 2.2
