### ISSUE TITLE
@inherits does not work on asp.net core 2 razor pages

### ISSUE THREAD

**Issue by HolyOne** [aspnet/Mvc#6769]
I tried inheriting the page with many base page classes, tried many examples.
It seems it does not work or there is no example around yet

**Comment by pranavkm** [comment]
@HolyOne could you elaborate on what sort of issues did you run in to when you used `@inherits` in your page? By default, Razor Pages requires that your base class derive from https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.RazorPages/PageBase.cs. Besides this, the `@inherits` sample from https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor#inherits should work just the same with Razor Pages.

**Comment by HolyOne** [comment]
I created a new ASP.net Core 2.0 project, I selected Web Application. (Razor Pages not MVC)

I created a new class, the exactly same one from the example you provided

`
public abstract class CustomRazorPage<TModel> : RazorPage<TModel>
{
    public string CustomText { get; } = "Hello World.";
}
`

I added this line at to top of one the sample pages (Contact.cshtml) , (I also tried it under the @page directive)

The error output I get is


`
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

Generated Code
One or more compilation references are missing. Ensure that your project is referencing 'Microsoft.NET.Sdk.Web' and the 'PreserveCompilationContext' property is not set to false.

The type or namespace name 'MenuViewPage<>' does not exist in the namespace 'WebApplication3' (are you missing an assembly reference?)
    public class Index_Page : WebApplication3.MenuViewPage<IndexModel>
'Index_Page.ExecuteAsync()': no suitable method found to override
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
The name 'StartTagHelperWritingScope' does not exist in the current context
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
The name 'EndTagHelperWritingScope' does not exist in the current context
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
The name 'BeginContext' does not exist in the current context
            BeginContext(71, 502, true);
The name 'WriteLiteral' does not exist in the current context
            WriteLiteral(@"
The name 'EndContext' does not exist in the current context
            EndContext();
The name 'BeginContext' does not exist in the current context
            BeginContext(573, 71, false);
The name 'CreateTagHelper' does not exist in the current context
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
The name 'Write' does not exist in the current context
            Write(__tagHelperExecutionContext.Output);
`

**Comment by pranavkm** [comment]
@HolyOne try using `public abstract class CustomRazorPage : Microsoft.AspNetCore.Mvc.RazorPages.Page`. The name `RazorPage<T>` is a bit misleading since it has to do with cshtml files in general and not Razor Pages model of programming.

**Comment by HolyOne** [comment]
So Razor Pages project type does not support base pages at all?
Is it planned to be added in the future or is it purposely not allowed to be used for coders to use @inject or something?

I think Razor Pages project type must have base pages too. I need it for a few good reasons, especialy for translation purposes with minimal extra typing.

**Comment by pranavkm** [comment]
It does. It specifically needs to derive from `Page`. Continuing from my previous comment, adding ` @inherits CustomRazorPage`  (note the absence of a generic type parameter) should just work. Summarizing:

```C#
public abstract class CustomRazorPage : RazorPage { public string CustomText { get; } = "Hello World."; }

// cshtml
@page
@inherits CustomRazorPage
@model MyModel
```

should get the job done.

**Comment by HolyOne** [comment]
Doesnt work also

![customrazorpage](https://user-images.githubusercontent.com/293601/30184874-22f2fd56-9428-11e7-980e-d3de595838de.gif)

**Comment by pranavkm** [comment]
@HolyOne you're right. Looks like we might have an issue where we allow types deriving from `PageBase` to be considered a page while requiring it to derive from `Page` in another location. Try updating your base class to 
`public abstract class CustomRazorPage : Page { public string CustomText { get; } = "Hello World."; }`

I verified it works locally. 

@rynowak, doing `public abstract class CustomRazorPage : PageBase { public string CustomText { get; } = "Hello World."; }` ends up throwing later on the pipeline: 

`InvalidOperationException: Page created by 'Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DefaultPageActivatorProvider' must be an instance of 'Microsoft.AspNetCore.Mvc.RazorPages.Page'.` versus the `DefaultApplicationModelProvider` requires types to derive from `PageBase`. I guess we missed a check when redoing the type hierarchy.

**Comment by rynowak** [comment]
Yeah, we should fix that.

**Comment by HolyOne** [comment]
Thanks
So when should I expect a fix? version 2.1 ?

**Comment by pranavkm** [comment]
Yup, we'll fix the base type in 2.1. In the meanwhile, having your base type derive from `Page` works. Doesn't that address your initial concern?

**Comment by HolyOne** [comment]
Oh yes inheriting from Page works
Thankss this was what I was looking for

**Comment by HolyOne** [comment]
I have another problem,
Now, @inherits CustomRazorPage works on my pages
but it does not work in _ViewStart or _ViewImports
So I need to write it to all pages

**Comment by pranavkm** [comment]
`_ViewStart`s are executed as vanilla Razor views, so it doesn't quite make sense to have them inherit from the `Page` \ `PageBase` types. That said, putting a type that derives from `PageBase` on a `_ViewImports` does throw an exception. I'll get this sorted for 2.1.0. For the current release, the best workaround is to explicitly add an `@inherits Microsoft.AspNetCore.Mvc.Razor.RazorPage<TModel>` to your `_ViewStart.cshtml` if you add a `@inherits CustomRazorPage` to your `_ViewImports.cshtml`. If there's specific issues you're running in to with your app, feel free to post a repro here and I can suggest some workarounds.

**Comment by jdvachal** [comment]
I'm getting the same exception as above:
`The name 'PageContext' does not exist in the current context`

I've followed your suggestion to add the @inherits to my _ViewStart
```
@inherits Microsoft.AspNetCore.Mvc.Razor.RazorPage<TModel>
@{
    Layout = "_Layout";
}
```
I then have the following in my _ViewImport
`@inherits ProjectRazorPageBase<TModel>`

The base class is defined as follows:
`public abstract class ProjectRazorPageBase<TModel> : FrameworkRazorPageBase<TModel>`

The framework base class is defined as follows:
`public abstract class FrameworkRazorPageBase<TModel> : RazorPage<TModel>`

The framework base class contains (among other things) hooks into the localization manager we're using.

Any possible workarounds here?

**Comment by HolyOne** [comment]
So .net 2.1 is out.
My code works well if I write this on top of my page

> @inherits BaseWeb.Web.BasePage

But how to make all my pages inherit from my base page? _ViewImports and _ViewStart dont work.

**Comment by pranavkm** [comment]
Could you start a new issue for this? `@inherits` in _ViewImports.cshtml should work.
