### ISSUE TITLE
FileExtension localization problem

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#6771]
_From @Stefanone91 on September 1, 2017 9:9_

Hello everyone,
I'm trying to localize the error message of "FileExtension" attribute but it seems not working.
I've successfully implemented the localization for "Required" attribute as explained in the official ASP.NET core guide.
I've created a simple project to reproduce the issue:
Inside the "registration" page i've added an input elemente for file upload wich is linked to RegisterViewModel, containing the "Immagine" IFormFile variable.
This IFormFile has the Required attribute and the FileExtension attribute. They are working well but not the translation of FileExtension's ErrorMessage .

Link to GIT:
https://github.com/Stefanone91/LocalizationFileSizeIssue

_Copied from original issue: aspnet/Localization#412_

**Comment by Eilon** [comment]
Hmm, it looks like we simply never added support for this attribute! Not sure why.

@dougbu @rynowak @danroth27 - any guesses as to why we never did it? We just forgot?

**Comment by Eilon** [comment]
BTW by "never added support" I mean in MVC - I'll move the bug.

**Comment by Eilon** [comment]
Seems like we need to:
1. Add an adapter here: https://github.com/aspnet/Mvc/tree/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal
2. Use the adapter here: https://github.com/aspnet/Mvc/blob/305748a800bf00573e602905712045cc0bdfd267/src/Microsoft.AspNetCore.Mvc.DataAnnotations/ValidationAttributeAdapterProvider.cs

**Comment by dougbu** [comment]
Not sure how this slipped through.

We also need to use the adapter on the client side.

**Comment by kichalla** [comment]
I found the following issue while researching about this attribute:
https://github.com/dotnet/corefx/issues/8913#issuecomment-279552672

So `FileExtensionAttribute` only works on `string` input here and not on types like `IFormFile`. Just wanted to check with you if we considered this when we triaged it.

cc @Eilon @dougbu

**Comment by Eilon** [comment]
I think from our discussion in person, we concluded that:
1. This attribute is meant only for `string` properties (where the user types in a file name manually, such as in Word 365 online, where you have to type in the name of the document to save it)
   * It makes perfect sense to localize the attribute. We should enable this for server & client validation
2. Using this attribute on any other type of property, such as one of type `IFormFile`, will continue to throw. That's just how this attribute works and I do not recommend we try to give it alternative behavior.

**Comment by kichalla** [comment]
https://github.com/aspnet/Mvc/commit/a96fb68690e6d2c30e95dfd23dbe34e94bb1009a
https://github.com/aspnet/jquery-validation-unobtrusive/commit/e7444c9ab5512d455069815e23b954ce2e7b2518
