### ISSUE TITLE
Manually rendering Razor precompiled views

### ISSUE THREAD

**Issue by briman0094** [aspnet/Mvc#6773]
My ASP.NET Core 2.0 site uses some `.cshtml` files as e-mail templates. I have a custom service that uses the `IRazorViewEngine` service to render views to a string. This works completely fine in Dev where the View files are sourced from the `.cshtml` files at runtime. However, in Production, the view engine can't find the template views and throws an error when the site tries to render an e-mail.

I am unsure if this is because the precompilation detects that the views are not used by any controllers and excludes them, or if `IRazorViewEngine.FindView` cannot load views that have been precompiled.

I can't include the `.cshtml` files in Production because the hosting server runs CentOS, and apparently runtime view compilation is not supported on Linux (it throws an error about not finding the `Microsoft.Win32.Registry` module).

Is there a way around this issue, or perhaps a better way of manually rendering a view? I considered just having a controller action that renders each template and having the e-mail service call the action, but I don't want users to have access to rendering the templates unless it's via an actual e-mail sent to them.

**Comment by pranavkm** [comment]
@briman0094 your issue might be a dup of https://github.com/aspnet/Mvc/issues/6672. The most likely solution in your case is to use `IViewEngine.GetView` which is meant for path-based lookups and pass in path rather than a name. 

e.g. 
`IViewEngine.FindView("Foo/Bar") -> IViewEngine.GetView("/Views/Foo/Bar.cshtml")`

**Comment by Eilon** [comment]
Yes this does sound like a dup of https://github.com/aspnet/Mvc/issues/6672.
