### ISSUE TITLE
How difficult will be to have a Code Generator for the MVC rails like ?

### ISSUE THREAD

**Issue by dinooz** [aspnet/Mvc#6775]
I wonder how difficult will be to bring a C# code generator to automagically create all the mehtods, relationships generated from a basic models to speedup the creation of projects ?

Perhaps this needs to build a new project almost like yeoman or rails generator to based on some DB Model create and wire all the required project.

**Comment by Eilon** [comment]
We do have something like this: the Code Generator Scaffolding feature that has command line tools and a Visual Studio UI for generating controllers and pages.

Here's a doc on how to do it with Razor Pages: https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model

Though the scaffolding works with regular MVC apps as well.

Is that what you're looking for?

**Comment by dinooz** [comment]
Close... have been working with K2 Forms and is really awesome, the way it works.
Define the SQL Data
Setup Data Sources as Service Instanace / then Smart Objects. [ Build CRUD of the SQL or Data Source]
Use the graphical interface to build the form and put some buttons calling actions and rules.
That's all the form is ready.

Taking that to the command like rails like, will be also cool, since will wire everything together. making super easy and simple get thing moving. Making it Simple is complex, but a lot more can be achieved.

Dinooz

**Comment by Eilon** [comment]
Ah, I see, so this is about scaffolding an entire database (all tables + all relationships) in one command?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#621
