### ISSUE TITLE
Razor Pages: pages files structure creates hard-coded namespace hierarchy

### ISSUE THREAD

**Issue by JohnyL** [aspnet/Mvc#6776]
I have created sample ASP.NET Core Razor Pages app (VS 2017 15.4.0 Preview 1).
I have the following folders structure:
1. Strategy class (in OrdersContext.cs file)
Data\
---OrdersContext.cs

Its code:
```
namespace FrezaWeb.Data
{
    public class Strategy { }
}
```

2. Edit page
Pages\
---Dictionaries\
------Strategy\
---------Edit.cshtml
------------Edit.cshtml.cs
------------Edit_page

The code of EditModel:

```
using FrezaWeb.Data;

namespace FrezaWeb.Pages.Dictionaries // <- Note the absence of "Strategy" namespace
{
    public class EditModel
    {
        public Strategy Strategy { get; set; } // <== HERE'S THE PROBLEM
    }
}
```
I want to use Strategy class from FrezaWeb.Data namespace. I removed "Strategy" namespace from "FrezaWeb.Pages.Dictionaries.Strategy" - and this would solve the problem. However, Visual Studio STILL thinks there's a Strategy namespace! A picture is worth a thousand words:
![Razor Pagez Error](https://i.imgur.com/mTCsZEx.png)

**Comment by Eilon** [comment]
@NTaylorMullen @rynowak any ideas on this?

**Comment by rynowak** [comment]
Yes, this an issue with Razor tooling.

Right now when we open a document in the editor (`edit.cshtml`) it's opened in the project it lives in. This isn't how compilation actually works, it's just an artifact of VS. This is something we plan to change in the future, but right now it's pretty fundamental to our tooling experience.

The namespace of the generated C# code of `edit.cshtml` is in the `FrezaWeb.Pages.Dictionaries.Strategy` namespace, which is causing your problem. 

If you want to have fine-grained control of the namespace of the generated code you can use `@namespace` in the razor file to configure it.

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Tooling/issues/883
