### ISSUE TITLE
Enum editor template implemented with select tag helper

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#6778]
We have an Enum.cshtml editor template, which is implemented using the select tag helper like so:

    @model Enum
    <select asp-for="@Model" asp-items="@Html.GetEnumSelectList(ViewData.ModelMetadata.UnderlyingOrModelType)">
</select>

We call it with the HTML helper `EditorFor()` like so:

    @Html.EditorFor(m => m.EnumProp, new { htmlAttributes = { @class = "form-control" }} );

However, the additional HTML attributes are ignored and not yet rendered - of course, as our editor template is not yet using them. As far as I know they are contained in `ViewData["htmlAttributes"]` - now my question:

How to pass those htmlAttributes on to the select tag helper?

**Comment by Eilon** [comment]
Hmm good question! If you know exactly which attributes you're expecting, I think you could do this:

```html
<select asp-for="@Model" asp-items="@Html.GetEnumSelectList(ViewData.ModelMetadata.UnderlyingOrModelType)"
    class="@ViewData["class"]"
    foo="@ViewData["foo"]"
    bar="@ViewData["bar"]"
>
```

And any attributes that aren't in the dictionary will be completely omitted. That is, is `bar` isn't in `htmlAttributes` then it won't render `bar=""` or `bar`, it won't render the attribute at all.

But I can't think of any built-in way to have it add all attributes in the dictionary to the tag helper directly.

Maybe you'd need to write your own tag helper that also targets `<select>` tags that supports a new property such as `extraHtmlAttributes="@someDictionary` and it would add them all?

@dougbu @NTaylorMullen @rynowak @DamianEdwards - any thoughts on this scenario?

**Comment by drauch** [comment]
I unfortunately don't know which HTML attributes I'm expecting. The own select-tag-helper solution is a hackaround at best :( Would be much better, if ASP.NET Core would support the scenario out-of-the-box. I guess all people writing their own display/editor templates (which is still the way to go, is it?) run into this problem sooner or later.

**Comment by Eilon** [comment]
Yeah maybe we could build-in support for "adding extra elements as HTML attributes" as some kind of built-in tag helper. I'll discuss with others in the team.

**Comment by dougbu** [comment]
A few thoughts:
- @DamianEdwards's [Tag Helper Pack](https://github.com/DamianEdwards/TagHelperPack) doesn't solve this e.g. see [here](https://github.com/DamianEdwards/TagHelperPack/blob/master/src/TagHelperPack/EditorForTagHelper.cs)
- But, we need some mechanism for this if we're going to solve #6782 end-to-end.
  - Using the template from a tag helper is only half the story. Less if we don't include a viable replacement for the `htmlAttributes` property in `additionalViewData` when invoking the template.
- Special-casing the `htmlAttributes` entry in the dictionary, especially if it's explicit e.g. `asp-add-html-attributes="true"` (as @Eilon suggests) strikes me as a good idea even though we've mostly avoided using `ViewData` within tag helpers.
  - Really dislike anything that creates a separate mechanism for the ambient HTML attributes available for use in a template. Should be possible to consume the attributes in both HTML and tag helpers.

**Comment by Eilon** [comment]
Moving to backlog for now.

BTW another alternative is of course to use HTML helpers rather than tag helpers, though this bug is indeed specifically about tag helpers. The HTML helpers do allow having "extra HTML attributes," which is what makes it easier to implement there.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
