### ISSUE TITLE
Convert some 'basic' 4XX responses into 'problem' responses

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6786]
* [ ] Add a filter
* [ ] Include correlation id if available
* [ ] Ensure analyzer works (#8288)

--------
* RFC 7807
* Use ProblemDescription as the preferred format for "error" responses from API endpoints.
* Introduce a new attribute that assumes that your API confers to some expectations. Expectations:
    (a) Any API which participates in model binding will have model state errors
    (b) API accepting id parameters will 404.
    (c) More ...?
* On the API description end, this means we will add a provider to enhance the description based on these expectations. See https://github.com/aspnet/Mvc/issues/6785
* On the output end, we'll add a filter \ change the execution to return a ProblemDescription if the action result matches one of our expectations.
* Introduce new types that allow modifying what the shape of the error description is. We'll produce a ProblemDescription and allow users to modify it's shape.

**Comment by pranavkm** [comment]
We're not doing a filter. The plan is to use action result execution extensibility to do this.

**Comment by rynowak** [comment]
Reactivating this to track the work, which wasn't completed 😆

**Comment by danroth27** [comment]
@pranavkm @rynowak What work is still pending here?

**Comment by rynowak** [comment]
100% of it.

**Comment by pranavkm** [comment]
Setting up a meeting with @rynowak for Monday to figure out how much work this would be. This should give us an idea on what we want to do with this item for preview1.

**Comment by tomkerkhove** [comment]
This might be a stupid question, but I presume that:
- Default flow for exception in controller will also use the new format?
- I have the capability to return new format results in exception handler?

**Comment by pranavkm** [comment]
> Default flow for exception in controller will also use the new format?

No, it's primarily meant to convert ActionResult with error status codes to errors.

> I have the capability to return new format results in exception handler?
Yup. The plan would be to have some way to customize what the format looks like. Right now, you could do this for ApiControllers using `ApiBehaviorOptions.InvalidModelStateResponseFactory`. e.g. https://github.com/aspnet/Mvc/blob/dev/test/WebSites/BasicWebSite/Startup.cs#L37-L47

**Comment by pranavkm** [comment]
Moving this out to preview2. We need to design this which we did not get around to as part of this release.
