### ISSUE TITLE
Add swagger tool for build-time swagger generation

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6787]

**Comment by Grauenwolf** [comment]
Any word on what this will actually entail?

**Comment by rynowak** [comment]
@Grauenwolf we've been working with @Rsuter over at https://github.com/RSuter/NSwag to try and fill some gaps with the swagger story.

Short term:
- Filling some gaps in swagger for ASP.NET Core ApiExplorer
- Some contributions from us to NSwag adding support for ApiExplorer in his existing tools

Long term:
- Some kind of extensible code generation story for client code and DTOs

-- 
We've been contributing to NSwag since it largely ticks all of these boxes already. Anything that we'd provide is going to be a layer on top that makes it possible plug in different tools like AutoRest

**Comment by shaggygi** [comment]
@pranavkm should this also be moved to the Ready column within project page?  Just curious.

**Comment by pranavkm** [comment]
@shaggygi done!

**Comment by pranavkm** [comment]
Closing this in favor of https://github.com/aspnet/Mvc/issues/7947
