### ISSUE TITLE
Port part of fix to 2.0.x for: Returning a file, accept-ranges headers, and browser behaviors #6780

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#6792]
See https://github.com/aspnet/Mvc/issues/6780

In the patch we can't add new APIs, so we should change the default behavior to be the 1.x behavior (i.e. no new headers by default). But, we should add a quirks mode switch to use the 2.0.0 behavior in case someone really wants it.

TODO: Need to figure out exactly which result types to patch. Definitely want to fix `FileContentResult`. Definitely **don't** want to fix `Physical/VirtualFileResult`. But not sure whether we want to change `FileStreamResult` (@Eilon thinks we *should* fix this).

See https://github.com/Eilon/QuirksModeSwitchSample for how to do quirks in general. And here's a specific example: https://github.com/aspnet/Mvc/commit/eec16ff8b03c1b212076e31ea49c082a3c1d6850

cc @Tratcher

**Comment by Eilon** [comment]
Tagging @jbagga to put in details of what we want to fix.

**Comment by Eilon** [comment]
This patch bug is **approved** for the 2.0.x patch. Please send a PR to the `feature/2.0.1` branch and get it reviewed and merged. When we have the `rel/2.0.1` branches ready please port the commit to that branch.

**Comment by jbagga** [comment]
`FileStreamResult` and `FileContentResult` will default to 1.x behavior and not add range headers. Adding a quirks mode switch to both in case range processing is desired

cc @Tratcher

**Comment by Eilon** [comment]
> `FileStreamResult` and `FileContentResult` will default to 1.x behavior and not add range headers.

This sounds good to me as the new default.

Does there need to be any way aside from quirks switches to get the range headers to show up? (Perhaps it's fine if not; I'm just not sure.)

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon
