### ISSUE TITLE
BundleConfig Styles.Render

### ISSUE THREAD

**Issue by BlueColorDemon** [aspnet/Mvc#6794]
![uz n 12 yt 1j v4lton](https://user-images.githubusercontent.com/7866267/30195017-617a3402-9489-11e7-8f52-e86bf9325e7e.png)
![6_5in skih002m 0xpm2 g0](https://user-images.githubusercontent.com/7866267/30195016-6179ef92-9489-11e7-8c3d-ebf439c58282.png)

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetWebOptimization#2
