### ISSUE TITLE
How I can skip all the validation of a model base on one of its property

### ISSUE THREAD

**Issue by hamidmayeli** [aspnet/Mvc#6797]
How I can skip all the validation of a model base on one of its property. For instance, if the `WillBeDeleted` property of the object is true the validator skips all the validation rules.

```C#
	namespace ViewModel
	{
		public class ContactForm : IViewModel
		{
			[ValidateNever]
			public Contact Item { get; set; }

			public Category Category { get; set; }

			[Required, DisplayName("First name")]
			[StringLength(200, ErrorMessage = "First name should not exceed 200 characters.")]
			public string FirstName { get; set; }

			[Required, DisplayName("Last name")]
			[StringLength(200, ErrorMessage = "Last name should not exceed 200 characters.")]
			public string LastName { get; set; }
			
			public List<TelephonesSubForm> Telephones { get; set; } = new List<TelephonesSubForm>();

			public List<EmailsSubForm> Emails { get; set; } = new List<EmailsSubForm>();

			public class TelephonesSubForm : IViewModel
			{
				public bool MustBeDeleted { get; set; }

				[Required]
				public TelephoneAndEmailType Type { get; set; }

				[Required]
				[StringLength(200, MinimumLength = 10, ErrorMessage = "Telephone should not exceed 200 characters.")]
				public string Telephone { get; set; }
			}

			public class EmailsSubForm
			{
				public bool MustBeDeleted { get; set; }

				[Required]
				public TelephoneAndEmailType Type { get; set; }

				[Required]
				[StringLength(200, MinimumLength = 10, ErrorMessage = "Email should not exceed 200 characters.")]
				public string Email { get; set; }
			}
		}
	}
```

In the given sample model, when the MustBeDeleted is true it means that the item of email or telephone will be deleted on the save action.

I have searched and found that several questions about conditional (custom) validation and they are suggesting to remove the specific keys from the ModelState before checking the validation state of it. Like [this](https://stackoverflow.com/questions/2417113/asp-net-mvc-conditional-validation) one.

In addition, I know that It is possible to inherit validation attributes (RequiredAttribute, StringLength, etc) and override the IsValid method. As a sample, I provide one of them.

```C#
    public class RequiredWhenItIsNotDeletingAttribute : RequiredAttribute
	{
		string DeletingProperty;

		/// <summary>
		/// Check if the object is going to be deleted skip the validation.
		/// </summary>
		/// <param name="deletingProperty">The boolean property which shows the object will be deleted.</param>
		public RequiredWhenItIsNotDeletingAttribute(string deletingProperty = "MustBeDeleted") =>
			DeletingProperty = deletingProperty;

		protected override ValidationResult IsValid(object value, ValidationContext validationContext)
		{
			var property = validationContext.ObjectType.GetProperty(DeletingProperty);

			if((bool)property.GetValue(validationContext.ObjectInstance))
				return ValidationResult.Success;

			return base.IsValid(value, validationContext);
		}
	}
```

**Comment by hamidmayeli** [comment]
Dear @Eilon,
May I ask you about this requirement in my project?
I thank you in advance for your attention.

**Comment by Eilon** [comment]
Hi @hamidmayeli this type of question is probably better suited for a forum such as StackOverflow, using the `asp.net-core-mvc` tag. I'm closing this issue because it does not appear to be a bug in ASP.NET Core MVC.

**Comment by hamidmayeli** [comment]
Hi @Eilon, 
Thank you for your replay.
In fact, I wanted to offer the feature because I guess it would be useful.

**Comment by Vasimovic** [comment]
I think this would be useful as well, I run into this problem often
