### ISSUE TITLE
Best way to use HttpClient in ASP.NET Core

### ISSUE THREAD

**Issue by amdnaji** [aspnet/Mvc#6802]
Hi,
I am using  HttpClient in our ASP.NET core application but i found this [article](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client) has the below note.

> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Especially in server applications, creating a new HttpClient instance for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors.

Then after more search i found another [article ](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/).

According to the articles the solution is to use single instance of HttpClient throughout the life of an application, so I decided to use Singleton DI for HttpClient but again there is an issue with singleton regarding DNS change according to this [issue ](https://github.com/dotnet/corefx/issues/11224).
So my question what will be the best way to use HttpClient in ASP.NET Core.
Thanks.

**Comment by khellang** [comment]
> So my question what will be the best way to use HttpClient in ASP.NET Core.

The best way, in general, is to use a single instance.

I've never had any problems with DNS resolution and `HttpClient`, but that might not always be the case, as you can see in the issue you linked.

So the answer, as usual, is "it depends". If you're hitting servers that frequently change IP adresses, it might be a problem. In that case, it might be an idea to do some kind of `HttpClient` management, where you periodically swap and return a new instance.

**Comment by amdnaji** [comment]
@khellang Thanks a lot for your answer 👍
