### ISSUE TITLE
SetMediaTypeMappingFormat doesn't recoginize first overload

### ISSUE THREAD

**Issue by JohnyL** [aspnet/Mvc#6803]
![MediaTypeHeaderValue.Parse error](https://i.imgur.com/dbB6pBU.png)

**Comment by rynowak** [comment]
This uses https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/MediaTypeHeaderValue.cs#L17 which is in the `Microsoft.Net.Http.Headers` namespace. 

Why not just pass the value as a string?

**Comment by davidfowl** [comment]
Related to https://github.com/aspnet/HttpAbstractions/issues/813

/cc @Eilon @Tratcher

**Comment by Eilon** [comment]
Closing because this does not appear to be a bug in MVC.

@davidfowl - yeah the current situation isn't ideal, but renaming the types is a huge cost for customers. I don't think we've seen this problem much at all to justify a drastic change.
