### ISSUE TITLE
XmlSerializerOutputFormatter in version 2.0.0.0 of the assembly is not working as expected

### ISSUE THREAD

**Issue by DerrenAusten** [aspnet/Mvc#6805]
I have an ASP.NET Core 1.1 and 2.0 app setup as follows:

`Startup.cs`

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc(options => options.OutputFormatters.Add(new XmlSerializerOutputFormatter()));
}
```

`HomeController.cs`

```c#
        [HttpPost("api/stuff")]
        [Produces("application/xml")]
        public IActionResult Stuff()
        {
            XDocument xmlDocument = new XDocument(
                new XDeclaration("1.0", "UTF-8", "yes"),
                new XElement("Response",
                    new XElement("Say",
                        new XAttribute("voice", "alice"),
                        new XAttribute("language", "en-GB"),
                        new XText("Hello caller")
                    )
                )
            );

            return new ObjectResult(xmlDocument.ToString());
        }
```

The 1.1 version (assembly version 1.1.3.0) returns:

```xml
<Response>
    <Say voice="alice" language="en-GB">Hello caller</Say>
</Response>
```

The 2.0 version (assembly version 2.0.0.0) returns:

```xml
<string>&lt;Response&gt;
  &lt;Say voice="alice" language="en-GB"&gt;Hello caller&lt;/Say&gt;
&lt;/Response&gt;</string>
```

Am I doing something wrong here?

**Comment by Eilon** [comment]
I think that instead of:

```c#
            return new ObjectResult(xmlDocument.ToString());
```

You want to remove the call to `.ToString()`, and do this:

```c#
            return new ObjectResult(xmlDocument);
```

Can you give that a try?

**Comment by DerrenAusten** [comment]
Yeah, without the `ToString()` I get back a 406 response.

**Comment by Eilon** [comment]
@rynowak - any idea what the trick is for this?

**Comment by rynowak** [comment]
since you're building the response as a string yourself `return Content(xmlDocument.ToString(), "application/xml");`

**Comment by rynowak** [comment]
Should we consider adding a formatter that can deal with XDocument and friends? Our built-in formatters don't do this because we just call the XML serializer.

**Comment by DerrenAusten** [comment]
The `ContentResult` thing works, thanks.

**Comment by Eilon** [comment]
@rynowak - it seems reasonable, but maybe not a high priority?

**Comment by rynowak** [comment]
Yeah this has been the first request for something like this

**Comment by Eilon** [comment]
Closing because there are no plans to implement this. If we see higher demand for this we will reconsider.
