### ISSUE TITLE
HTTP Error 502.3 - Bad Gateway for users not in roles on controller Authorize attribute 

### ISSUE THREAD

**Issue by AlanBarber** [aspnet/Mvc#6806]
Running latest 2.0 core project upgraded from 1.1 core, azure ad authentication with user roles

On a controller I have setup the following

    [Authorize(Roles = "Manager")]

If the user is in the Manager role it works fine and they can access pages on that controller but any user not in the role are getting a generic iis error

    HTTP Error 502.3 - Bad Gateway
    The specified CGI application encountered an error and the server terminated the process.

This happens both in local debugging as well as when deployed to an Azure website.

I was assuming a 401 or 403 error but regardless In the startup.cs I have 

    app.UseExceptionHandler("/Home/Error");

So I'm not sure why it's not redirecting to the error page I setup either.

**Comment by Eilon** [comment]
When doing local debugging can you try to enable catching all exceptions and see if there's some hidden exception being thrown?

Here's how to do it:

First, open the Exception Settings window:
![image](https://user-images.githubusercontent.com/202643/30341285-57b0bc6a-97aa-11e7-834d-5a18c640c17a.png)

Then, enable catching all exceptions:
![image](https://user-images.githubusercontent.com/202643/30341304-6a3d2468-97aa-11e7-8589-736673daaf4b.png)

And then when you run your app with the debugger, you can see if there are some hidden exceptions getting thrown.

Also cc @Tratcher and @HaoK in case you guys have ever seen anything like this.

**Comment by Tratcher** [comment]
There's a known issue with Forbid. See https://github.com/aspnet/Security/issues/1415#issuecomment-328576682

**Comment by Eilon** [comment]
Oh, that issue. Looks like @davidfowl has a workaround listed here: https://github.com/aspnet/Security/issues/1376#issuecomment-323556698

And we'll have this fixed in 2.1.

Closing this bug as a dup.
