### ISSUE TITLE
Default value of GroupName in ApiExplorerSettingsAttribute

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/Mvc#6810]
Hi,
as it is now necessary to opt-in into ApiExplorer by using the ``[ApiExplorerSettings(IgnoreApi = false)]``, which works on a BaseController (as the attribute is inherited) but currently there is no way to generically set the GroupName to something Controller specific. It would be great if you either support [controller] placeholder (like in the RoutePrefixAttribute) or some property which sets the value to the ControllerName (e.g. ValuesController) or provide a default mechanism which always opts-in into ApiExplorer and sets the necessary values automatically.

I followed the tutorial https://andrewlock.net/introduction-to-the-apiexplorer-in-asp-net-core by @andrewlock. There is not much information on how to use the apiexplorer besides How-To use Swagger https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?tabs=visual-studio

**Comment by Eilon** [comment]
@rynowak thoughts on this?

**Comment by rynowak** [comment]
Here's an example of code that does this https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/test/WebSites/ApiExplorerWebSite/ApiExplorerVisibilityEnabledConvention.cs

**Comment by Tornhoof** [comment]
Thank you for that Link, yes this solves the problem quite nicely.

**Comment by mynkow** [comment]
10x @rynowak . Here is the code for reference:
```
    // Enables ApiExplorer for controllers that haven't explicitly configured it.
    // This is part of the test that validates that ApiExplorer can be configured via convention
    public class ApiExplorerVisibilityEnabledConvention : IApplicationModelConvention
    {
        public void Apply(ApplicationModel application)
        {
            foreach (var controller in application.Controllers)
            {
                if (controller.ApiExplorer.IsVisible == null)
                {
                    controller.ApiExplorer.IsVisible = true;
                    controller.ApiExplorer.GroupName = controller.ControllerName;
                }
            }
        }
    }
```
