### ISSUE TITLE
.net core centos 7.2 A large amount of view folders are not updated in time, so you need to restart applications

### ISSUE THREAD

**Issue by qibucloud** [aspnet/Mvc#6814]
`https://github.com/aspnet/Mvc/issues/6793`
https://github.com/aspnet/Mvc/issues/6793
@Eilon @DamianEdwards @pranavkm @RickyLin
Through the exclusion test, now I am quite sure that the strange cache was caused by the excessive number of folders. After I reduced the amount of the folders and restarted the application, everything became normal. But when I put all the folders back and restarted the application, the problem came out again.
Could you please help me to analyze what is the reason of this problem? Could you please try to help me to solve this problem?
Thank you so much!

**Comment by RickyLin** [comment]
This issue was closed as #6793 was closed.
