### ISSUE TITLE
Model does not serialize to the camelCase by default

### ISSUE THREAD

**Issue by jsdmitry** [aspnet/Mvc#6819]
I am returning a data of the IEnumerable type as a Model of View. And I wait for that a Model has will properties with camelCase formatting as when getting a data from WebApi controller.

**Comment by Eilon** [comment]
Hi @jsdmitry can you show us what your code looks like? Camel case should be the default ever since ASP.NET Core 1.0.0: https://github.com/aspnet/Announcements/issues/194

cc @dougbu

**Comment by jsdmitry** [comment]
I resolved this issue, the problem was in my application.
