### ISSUE TITLE
Api Response should have a way to represent a default response type

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#6828]
Swagger \ OpenAPI has a way to represent a `default` error response for all errors. See https://swagger.io/docs/specification/describing-responses#default. We don't have a good way to represent this. For the time being, we're resorting to using `StatusCode=0` to indicate this.

**Comment by mkArtakMSFT** [comment]
@pranavkm, please handle this during the assigned milestone timeframe.

**Comment by danroth27** [comment]
I think we need to do something here for 2.1. Using `StatusCode=0` adds a bunch of noise to the Swagger document that isn't standard.

**Comment by rynowak** [comment]
@pranavkm - my thought about this is that we should undo a few things we did in 2.1 to make the edges less ragged?

Ideas I had:
- keep problemdetails (the class)
- keep the new problemdetails overloads on controller
- Make the 'error filter' use the old style of bad request
- Get rid of the automatic 'default' response we add to api explorer. 


Thoughts?

**Comment by pranavkm** [comment]
3. I think this makes sense. We don't have the E2E behavior baked as yet and there's a way for users to upgrade to the ProblemDetails response using https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ApiBehaviorOptions.cs#L25. 

4. Would we bring this back if we do get the story around `Default` response sorted? Having the filter, but not the default error response seems like a impedance mismatch.

**Comment by rynowak** [comment]
Maybe.

**Comment by rynowak** [comment]
All of this still stuff we want to do as soon as possible. I'm talking about preview1 in particular

**Comment by pranavkm** [comment]
Coolio. I'll get on this once I'm done fixing Razor

**Comment by pranavkm** [comment]
Addressed the new property in NSwag and Swashbuckle.
