### ISSUE TITLE
How can I use localization in my Razor Page project

### ISSUE THREAD

**Issue by JamesYing** [aspnet/Mvc#6829]
Hi guys,
I want use localization on my razor page project, I  registed the localization service in startup:
`services.AddLocalization(options => options.ResourcesPath = "Resources");
            services.AddMvc()
                .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
                .AddRazorPagesOptions(options =>
                {
                    options.Conventions.AuthorizeFolder("/Account/Manage");
                    options.Conventions.AuthorizePage("/Account/Logout");
                });`
In the View, I inject the IViewLocalizer, but when i run the project, it throw a exception:
  IndexOutOfRangeException: Index was outside the bounds of the array.
    Microsoft.AspNetCore.Mvc.Localization.ViewLocalizer.BuildBaseName(string path)

The exception from ViewLocalizer.Contextualize, the viewContext.View.Path is empty, so it throw this exception.

So, How can I use localization in my Razor Page project?

**Comment by DamianEdwards** [comment]
This looks like a bug as ideally `IViewLocalizer` should work in Razor Pages.

In the meantime, you can inject and use the `IStringLocalizerFactory` type instead and use it to create an `IStringLocalizer`.

**Comment by DamianEdwards** [comment]
@pranavkm @rynowak

**Comment by JamesYing** [comment]
@DamianEdwards Thanks

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/6694. We fixed this for 2.1.0. @Eilon it'll be nice to port this to 2.0.x since view localization is is completely broken.

**Comment by DamianEdwards** [comment]
Agree with @pranavkm that we should patch this in 2.0.x

**Comment by enrico-padovani** [comment]
Do you have a practical example of how to solve the problem? Or do I have to switch back to regular MVC for getting it work? Thanks

**Comment by rynowak** [comment]
https://github.com/aspnet/Mvc/issues/6694#issuecomment-324132018
