### ISSUE TITLE
Logging of JSON result executor

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Mvc#6830]
The `JsonResultExecutor` logs the complete object using the `Information` log level:

https://github.com/aspnet/Mvc/blob/776c2604f82b1ff76e0a03ba5497ea616b8172a2/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/MvcJsonLoggerExtensions.cs#L22-L25

and 

https://github.com/aspnet/Mvc/blob/776c2604f82b1ff76e0a03ba5497ea616b8172a2/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/JsonResultExecutor.cs#L118

Logging the complete object may result in the logs being spammed with large messages. It seems to me that either logging the type _name_ is enough, or lower the log level to `Debug` or `Trace`.

Currently I'm avoiding this behavior by applying a filter:
```cs
.ConfigureLogging((hostingContext, builder) =>
{
    // Don't log information messages of JSON result executor since it logs the complete output
    builder.AddFilter("Microsoft.AspNetCore.Mvc.Formatters.Json.Internal", LogLevel.Warning);

    // ...
})
```

What are the thoughts on others about this?

**Comment by rynowak** [comment]
We just changed this to log the type 9db92dc6a7bfc22a62ff12053244201c38390da5

**Comment by henkmollema** [comment]
How could I miss that? 🤔 
Anyway, thanks!
