### ISSUE TITLE
Many of the important methods are too hard to reach in Razor Pages

### ISSUE THREAD

**Issue by HolyOne** [aspnet/Mvc#6832]
I know the old Server.MapPath method and routing parameters can be reached with different ways in Razor pages, I think they should be much easier to access.

I spent long time finding many of the very necessary methods.

Although I know you have good reasons to implement Accessor Classes, I think a static helper class should be provided for easier access to return values/objects from them.

**Comment by Eilon** [comment]
@HolyOne can you provide more details on the exact methods and functionality you're looking for? Server.MapPath is an API from ASP.NET 4.x and was never in ASP.NET Core at all.

**Comment by HolyOne** [comment]
I know it is not in asp.net core, thats what I am talking about.

For example 

Microsoft.AspNetCore.Http.IHttpContextAccessor hca =  new Microsoft.AspNetCore.Http.HttpContextAccessor();

I know this is not hard to write. But if you are expecting Razor Pages to be easier to dive into, you should provide much easier acccess to common objects just like in old webforms ( you can write whatever code under the helper classes)

If I want to get urlhelper inside a class

   var MyUriHelper=  (Microsoft.AspNetCore.Mvc.IUrlHelper)hca.HttpContext.RequestServices.GetService(typeof(Microsoft.AspNetCore.Mvc.IUrlHelper));

this seems ugly

And for Server.Mappath in .net Core ,
https://www.codeproject.com/Tips/1184221/Server-MapPath-Equivalent-in-ASP-NET-Core

Yes 3 lines may not be much, But imagine a new user, (Who dont want to look up every line in stackoverflow, every time he needs) he has to try combinations of 3 in a number of classes and variables that makes sense to him.

In prior asp.net I used Server.MapPath, In Php I used only __DIR_ .

I know what you do is the right way, more testable etc... 
But adding some helper classes to reach common construtcts like Mappath, Reaching the exact copy of Request and Response in the view would make it super easy for new comers. You can also add a warning to this super easy to use class, like if you use this your code wont be testable.

**Comment by davidfowl** [comment]
@HolyOne why would you ever new up the http context accessor. 

> But if you are expecting Razor Pages to be easier to dive into, you should provide much easier acccess to common objects just like in old webforms ( you can write whatever code under the helper classes)

There's no expectation that Razor Pages is like php for aspx. It's just MVC but merging the VM (view model and C) the controller. 

Can you give more specific examples of what is hard to do? The Request and Response objects exist on the Page itself maybe you missed that?

Is it just the `Server.MapPath` equivalent you're looking for? Are you trying to read a file?

**Comment by HolyOne** [comment]
I am trying to make a custom localization in Razor Pages (Not asp.net s localization but my own)

For that I need to get Local Path name of the View file.

I also need to get the language parameter from route, MVC routing settings dont work with Razor Pages, a global @page {routevar?}  declaration cant be set in PageStart etc... but thats another long story.

These are the things I could do with a little research in the previous asp.net versions but I spent hours with this one. Thats why I thought reaching these should have been easier since Razor Pages targets an easier approach than MVC

**Comment by HolyOne** [comment]
@davidfowl In asp.net core 2 razor pages,
What is the correct way to get the root path of the website?

I am trying to get the local path of the url I am visiting so I can load its custom translation file which is with the same name in the application root

It has been 2 days im researching to get this path =)

**Comment by hishamco** [comment]
> What is the correct way to get the root path of the website?

Simply you can use `IHostingEnvironment`, it doesn't matter if you're using MVC or RazorPages

**Comment by HolyOne** [comment]
Sorry I didnt understand the core concept at first. looked for static methods for some basic things a few months ago.
Now I understand. It is not hard but it is necessary complexity.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
