### ISSUE TITLE
Port to 2.0.1: Input fields don't emit (and thus round-trip) offset value when binding against DateTimeOffset fields

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#6834]
Original bug we fixed in 2.1.0: https://github.com/aspnet/Mvc/issues/6648

Given that this change is slightly riskier, I recommend we add a quirk mode switch.

* General info on how to do quirks mode switches: https://github.com/Eilon/QuirksModeSwitchSample
* Specific example where we've used a quirks mode switch: https://github.com/aspnet/Mvc/commit/eec16ff8b03c1b212076e31ea49c082a3c1d6850#diff-a1f8bcbb57a17693451764623b946cb1R154

cc @DamianEdwards

**Comment by Eilon** [comment]
This patch bug is **approved** for the 2.0.x patch. Please send a PR to the `feature/2.0.1` branch and get it reviewed and merged. When we have the `rel/2.0.1` branches ready please port the commit to that branch.

**Comment by dougbu** [comment]
6041c6b9 and fd9cb087 in feature/2.0.1

**Comment by dougbu** [comment]
> When we have the `rel/2.0.1` branches ready please port the commit to that branch.

@Eilon to be clear: We're not merging all of `feature/2.0.1` into `rel/2.0.1` in one blast? Should I leave this bug open until I do that second port?

**Comment by dougbu** [comment]
FYI same commits are now in `rel/2.0.1`.

**Comment by Eilon** [comment]
We can do it whichever way. I think doing all in one blast is fine.

**Comment by Eilon** [comment]
But leaving the bug closed is fine.

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon
