### ISSUE TITLE
async  "OnReady" in controllers

### ISSUE THREAD

**Issue by Ibro** [aspnet/Mvc#6835]
Would it be possible and make sense to have something like OnReady async method inside of controllers? Would help with scenarios where we are repeating async code usage inside of various methods.
/cc @DamianEdwards

**Comment by Eilon** [comment]
It's not exactly clear what "OnReady" represents. However, all the stages available to controllers and pages are available via filters. We have a doc on filters here: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters

**Comment by Ibro** [comment]
I am aware of that. However, that's not so convenient. This would be one-time only, and it would be something that happens after controller instance is created. Since constructors can't be async, we could use this method. During community stand-up, Damian mentioned that something like this could be implemented for Razor Pages.

**Comment by DamianEdwards** [comment]
I believe you can do it in a Controller by making the controller itself a filter for itself. This is how we're going to solve this for Razor Pages too.

**Comment by Eilon** [comment]
Ah, yes, that's covered here: https://github.com/aspnet/Mvc/issues/6606

So, yes, we do plan on having a fairly easy way to do this.
