### ISSUE TITLE
Convert null-valued results to NotFoundResult in ActionResult<>

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#6848]
Consider the following API:

```C#
public async Task<ActionResult<Contact>> Get(int id)
{
    var contact = await DbContext.Contacts.Where(item => item.ContactId == id).SingleOrDefaultAsync();
    if (contact == null)
    {
        return NotFound();
    }
    
    return contact;
}
```

We could reduce this by assuming ActionResult<T>(null) indicates a NotFoundResult rather than an ObjectResult with a null value (which is what we do now). Resulting code:

```C#
public Task<ActionResult<Contact>> Get(int id)
{
    return DbContext.Contacts.Where(item => item.ContactId == id).SingleOrDefaultAsync();
}
```

**Comment by pranavkm** [comment]
Since the type is new, we could build this behavior in to `ActionResult<T>`: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ActionResultOfT.cs#L53-L59. However, it would be nicer if it had bells and whistles to disable this behavior.

**Comment by Eilon** [comment]
This is specifically for `[ApiController]` conventions?

cc @rynowak

**Comment by rynowak** [comment]
I'm really not a big fan of this, it's been brought up before and I didn't like it then

**Comment by rynowak** [comment]
Closing this, we've discussed it and feel like it's a little inconsistent and non-obvious. We can't always guess whether you wanted a 200, 204 or 404.

**Comment by pranavkm** [comment]
Moving this out to preview2 for design work
