### ISSUE TITLE
I have a name puzzle about Content in MVC

### ISSUE THREAD

**Issue by doublnt** [aspnet/Mvc#6850]
Here is the defaults MVC folder structure.
![img3](https://user-images.githubusercontent.com/13679242/30576418-54a2d18a-9d3a-11e7-952e-9defa7419c8e.png)
Why Content is call Content, Why not use Contents?

**Comment by Eilon** [comment]
You have finally unlocked the secret code of ASP.NET MVC, congratulations!

I hereby award you TEN free copies of ASP.NET MVC, limited to personal use only! You'll also be invited to the FREE public preview of ASP.NET Core MVC 2.1 when it is available!

😄

**Comment by doublnt** [comment]
I search specially to find the different meaning of `Content` and `Contents`,  I found this below, maybe can explain why using `Content`, but not `Contents`. 

**In the singular, “content” usually refers to:**
* The entirety of information contained in something. The story of a novel or the subject of an illustration can be called their “content”. Just like “information”, content is always uncountable when used in this sense. **The word is most commonly used in reference to the content of a website, as in,**
> Most websites contain mostly ads with very little content.

* The amount of a substance contained in something else. It may be either countable or uncountable. We can speak of “salt content” or “fat content” in foods, “alcohol content” in drinks, and so on, e.g.
> Bacon has (a) very high salt content.

**In the plural, “contents” refer to the things contained in something:**
* In a concrete sense. We can speak of the “contents of a bag”, “contents of a bottle”, “contents of the stomach”, etc., for instance,
> He dropped a bottle and spilled its contents all over the floor.

* In an abstract sense. Traditionally, pieces of information contained in a written document are called its “contents”. You may say,
> She has lost the letter and remained unaware of its contents.

&emsp;Using the singular “content” in this case is becoming increasingly more common but is still considered wrong by many. The distinction is rather subtle; if you consider the contents of a document to be separate pieces of information, you should use “contents” (which is usually the case with a letter). If you refer to them as a whole, you should use “content”—it makes more sense to say that “the book contains violent content” than “the book contains violent contents”.

**Reference** 
*[ 'Content' VS ' Contents' in English](https://jakubmarian.com/content-vs-contents-in-english/)

**Comment by mkArtakMSFT** [comment]
Hi.

It seems there is no action here for us to take here, so we're going to close this issue. If you believe that this is something important to you, you can submit a suggestion at https://visualstudio.uservoice.com,
