### ISSUE TITLE
Razor Page does compile but VS shows errors when dash/hyphen used in file name

### ISSUE THREAD

**Issue by mehowq** [aspnet/Mvc#6854]
There is still (2.1.0-preview1-007211) an issue with IntelliSense in Visual Studio 2017 (15.4.0 preview 2.0) with the filenames containing dashes.

In order to reproduce:

- create a new razor page e.g. razorpagetest.cshtml
- in the code add ViewData["Title"] = "Test123";
- save and close the file
- rename razorpagetest.cshtml to razor-pagetest.cshtml
- save and close the file
- reopen the file and you will see errors on the errors list (although it builds OK)

**Comment by Eilon** [comment]
@pranavkm - any ideas?

cc @rynowak

**Comment by hishamco** [comment]
This remind me with an old bug https://github.com/aspnet/Mvc/issues/6296

**Comment by Eilon** [comment]
@hishamco good catch! Assigning this to @rynowak then...

**Comment by rynowak** [comment]
This was fixed in https://github.com/aspnet/Razor/pull/1366 - I believe that means that it's fixed in VS 15.5
