### ISSUE TITLE
Overlapping attribute routes doesn't result in ambiguous action match error

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#6861]
When I have these two actions and make a request to `api/values` I expected to get an ambiguous action match error, but instead the first action gets hit:

```c#
    [Route("api/[controller]")]
    public class ValuesController : ControllerBase
    {
        // GET: api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        [HttpGet("{id?}")]
        public string Get(int id)
        {
            return "value";
        }
    }
```

Shouldn't this request result in an error?

**Comment by rynowak** [comment]
No, the `{id?}` route has lower precedence. Attribute routing builds a tree that processed routes an order that processed the most specific entries first.
