### ISSUE TITLE
Use page handler when OnGetAsync

### ISSUE THREAD

**Issue by troncomputers** [aspnet/Mvc#6863]
Hi!
Is there a chance for working handler when OnGetAsync?
I've got a form when I have different SQL Query and I want to seperate them with asp-page-handler but it doesn't work. There are 2 pages Index (when you type filter data like dateFrom, dateTo, taskType) and Result with filtered data. Reason why I did it that way is when I want to go back to Index the browser won't ask me for submit form again.
```html
<form method="get" action="/Raporty/Result">
<!--form stuff goes here-->
<button type="submit" asp-page-handler="Old">Old</button>
<button type="submit" asp-page-handler="Standard">Standard</button>
</form>
```
In Result.cshtml.cs
```cs
 public async Task<IActionResult> OnGetOldAsync(string dateFrom, string dateTo, string taskType)
 {
        #stuff here
 }
 public async Task<IActionResult> OnGetStandardAsync(string dateFrom, string dateTo, string taskType)
{
        #stuff here
}
```
Do handlers works only with method='post'?

**Comment by pranavkm** [comment]
This should work. Handlers are supported on both Get and Post methods.

**Comment by Eilon** [comment]
@pranavkm - can you try to repro?

**Comment by pranavkm** [comment]
Yeah, this works just fine.
