### ISSUE TITLE
Refactoring Http Result helpers in ControllerBase to use lambda syntax.

### ISSUE THREAD

**Issue by mistakenot** [aspnet/Mvc#6864]
It was suggested in a PR comment by @pranavkm  (https://github.com/aspnet/Mvc/pull/6851/files#r139845791) that a new ControllerBase Http Result helper could be written with one line instead of three using the new lambda syntax for brevity.

Is it worth refactoring all such methods in the class to use the lambda syntax to make the class a bit shorter? 

I'm guessing it would only work with methods that just consist of a return statement, as there are some that do additional checks before creating the Result instance.

I don't mind doing the work, but want to check before hand.

**Comment by Eilon** [comment]
If you want to send a PR that cleans up some of the existing methods that'd certainly be fine! We don't generally go back and replace all "old syntax" with new syntax, though we do tend to write new code using new syntax (where appropriate). But, if you have some free time, it'd be quite welcome!
