### ISSUE TITLE
Allow for route initialization before the first request

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Mvc#6867]
This is a follow up on #1989.

On my embedded instrument, I try to improve the (perceived) performance.

I have already created an `ApplicationPartManager`, `ApplicationPart` and `ControllerFeatureProvider` so I can avoid the entire assembly scanning and just list the controllers types that should be available in my code. This already improves startup nicely.

However, after my SPA has loaded in the browser and the first MVC request hits the pipeline, there's a considerable amount of waiting involved until this request is actually handled (close to three seconds). This is mainly due to the first-time initialization of [GetTreeRouter](https://github.com/aspnet/Mvc/blob/rel/2.0.0/src/Microsoft.AspNetCore.Mvc.Core/Internal/AttributeRoute.cs#L66). In addition, when my SPA happens to issue more than one initial request, all that initialization work is done twice (or thrice) because the `_router` member is null for all those initial requests.

The entire router initialization currently happens enclosed within the MVC code and there's just nothing to hook into (that I could find). So to remedy that, I have inlined the code from `UseMvc` call (ouch, this includes the `.Internal` namespace) and on the result of `CreateAttributeMegaRoute`, I call the private `GetTreeRouter` via reflection (OUCH! :smile: ). That way the `_router` field is initialized only once and before the first request.
This saves me more than two seconds on the first MVC request.

I'd really like to see a supported way to do this.

**Comment by Eilon** [comment]
@Tragetaschen have you looked at any profiler data to see where the ~3 seconds are spent? That's an awful lot of time to be spent just in the tree router - unless the app has millions of routes.

@sebastienros  - can you take a look at this to see what's going on?

cc @rynowak

**Comment by Tragetaschen** [comment]
@Eilon That's on a single-core ARMv7 with less than 1GHz to begin with. Also, there were three "first" requests in flight and three ThreadPool threads tried to initialize the internal data structures. I'm not worried about the time it actually takes.

As a "profiler" I instrumented Autofac's service resolution with a StopWatch and on the first request, I could see the creation of the `TreeRouteHandler` followed by a large number of `MvcAttributeRouteHandler` being created.

**Comment by Eilon** [comment]
Ah, interesting. That certainly explains why it's *soooo* slow, but perhaps we need to optimize some logic here anyway. Thanks!

**Comment by mkArtakMSFT** [comment]
Ping @sebastienros

**Comment by sebastienros** [comment]
Summary:
1- `GetTreeRouter` is relatively slow. Are there way to optimize it? Maybe it's unnecessary baed on Dispatching work going on, or at least measure it.
2- `GetTreeRouter` is called more than once if many requests are sent during its initialization. Could this be fixed simply with a `SemaphoreSlim`?
3- Eventually provide a way to initialize `GetTreeRouter` without requiring the first request, warmup.

**Comment by mkArtakMSFT** [comment]
Thanks @sebastienros.
@danroth27, is this a scenario we'd like to invest in or its a special case we'd like to leave as is?
FYI: I do take into consideration the fact that the Dispatcher work will have some improvements here.

**Comment by mkArtakMSFT** [comment]
The decision here is to make sure that the initialization happens once.

**Comment by mkArtakMSFT** [comment]
@JamesNK, @rynowak, @kichalla please review this issue in the context of the `Dispatcher` work and if there is work to be done, please either move this into the `aspnet/routing` repo or create a new one, and  close this one.

**Comment by mkArtakMSFT** [comment]
Thanks @JamesNK. Closing this one in favor of the reference issue in aspnet/routing.
