### ISSUE TITLE
ApiDescription requires a way to represent OperationId

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#6872]
Essentially a stable name that is inferred from the controller \ action name.

**Comment by rynowak** [comment]
@pranavkm - what's the value of us owning this vs swashbuckle or nswag?

**Comment by pranavkm** [comment]
Yeah, this can be done. 

* Swashbuckle uses the route to generate it - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/1b8e109cdb2e21b57584ef4596a0d1a13af8b7eb/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/ApiDescriptionExtensions.cs#L35-L51. 

* NSwag's current reflection based code generates it using the controller \ action name: 
https://github.com/RSuter/NSwag/blob/a3134b1a728ef8094dd05cf083e6e5f54dfa98df/src/NSwag.SwaggerGeneration.WebApi/WebApiToSwaggerGenerator.cs#L237-L257

The advantage of having it on `ApIDescription` with an Mvc attribute to represent it is that you don't need library specific annotations if you'd like to control the value.

**Comment by rynowak** [comment]
I'm close this then since there isn't a clear enough value to US implementing it. Telling people to use NSwag or Swashbuckle's annotations to configure this is a good solution until we have this need to use this data somehow.

/cc @danroth27
