### ISSUE TITLE
RemoteAttribute not creating correct URL when route contains an area and no explicit routes defined

### ISSUE THREAD

**Issue by ctorx** [aspnet/Mvc#6878]
The `RemoteAttribute.GetUrl()` method is not returning the correct URL when an action lives inside of an area and no explicit route is defined in Startup.cs

You can see this if you only use attribute routing and decorate a view model property with the `RemoteAttribute` and specify values pointing to an Action within an Area.

I attempted to debug using symbols that were available and was able to narrow the issue down to somewhere behind `RouteCollection.GetVirtualPath()` in `Microsoft.AspNetCore.Routing`.

The `GetVirtualPath()` method iterates all `IRouters` (in my case only a single `Microsoft.AspNetCore.Mvc.Internal.AttributeRoute`) and calls` GetVirtualPath()` using the provided `VirtualPathContext`, which in this case comes from a `UrlHelper` newed up in the `RemoteAttribute.GetUrl()` method.

I've verified that the area name provided to the `RemoteAttribute` constructor is included in the Values property on `VirtualPathContext`.

The call to `AttributeRoute.GetVirtualPath()`  in this scenario is consistently returning `null`.

I was unable to locate any public symbols for `Microsoft.AspNetCore.Mvc.Internal.AttributeRoute` so I could not debug further.

**Comment by Eilon** [comment]
@jbagga can you take a look? If you haven't seen the `RemoteAttribute` validator before I can walk you through it.

**Comment by jbagga** [comment]
@ctorx Can you share your `Startup` code that maps to area routes? I am unsure what you mean by 

> no explicit route is defined in Startup.cs

Do you have anything similar to this?
```
                routes.MapRoute(
                    "areaRoute",
                    "{area:exists}/{controller}/{action}",
                    new { controller = "Home", action = "Index" });
```

**Comment by jbagga** [comment]
Here is a quick sample https://github.com/jbagga/RemoteAttributeInArea

Can you take a look and let me know what is different in your app?

**Comment by ctorx** [comment]
I am using attribute routing.  Attribute routing for areas seems to work everywhere else such as Url.Action() etc.  I am only having an issue with the Remote Attribute.

Just to be clear, I have no route templates defined in Startup.cs.  If I add one it works, but I shouldn't have to add one -- that's the point of attribute routing.  :)

**Example:**

```
[Area("TheArea")]
[Route("the-area")]
public class TheAreaController : Controller
{
     [HttpGet]
     [Route("the-area-action")]
     public async Task<IActionResult> TheAreaAction()
     {
          // do stuff
     }
}
```

**Comment by jbagga** [comment]
I am unable to repro the issue. I updated the sample to use attribute routing but it still works. Can you provide a sample or more information?

**Comment by ctorx** [comment]
Are your changes committed ?  If so, I can pull down the repo on try on my
side.

**Comment by jbagga** [comment]
Yes, the sample [here](https://github.com/jbagga/RemoteAttributeInArea) is updated to use attribute routing.

**Comment by jbagga** [comment]
Closing this for now as the issue cannot be reproduced.

@ctorx If you run into it again, please provide more information and I can look into it then!
