### ISSUE TITLE
asp.net core frequently create and exit threads

### ISSUE THREAD

**Issue by tiandian** [aspnet/Mvc#6883]
## Steps to reproduce
1. use vs2017 asp.net core template to generate a asp .net core 2.0 program WebApplication1

2. dotnet publish --runtime win7-x86

3. run WebApplication1.exe (or run use "dotnet WebApplication1.dll")

4. use Procmon.exe to Monitor WebApplication1.exe, check the "Show progcess and thread activity" button,
then you will see that WebApplication1.exe will frequently create and exit threads, every 2 second will create and exit a thread, see below picture:
![a](https://user-images.githubusercontent.com/5468699/30772347-0aa8db24-a08c-11e7-8d49-79f28c885250.png)

## Expected  behavior
Don't frequently create and exit threads

## Actual behavior
any asp.net core 2.0 program will frequently create and exit threads.

## Environment data
`dotnet --info` output:

```
D:\Download\ConsoleApp1>dotnet --info

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by davidfowl** [comment]
Welcome to async await and the thread pool in general. What are you actually asking for here? This isn't a bug it's by design.

**Comment by tiandian** [comment]
If this is not a bug, then please close this issue.

because my asp.net core program has a deaklock problem, so i find every possible problems, 
then i occasionally found asp.net core will frequently create and exit threads.
then i test a .net core console program, it will not frequently create and exit threads, only asp.net core program will  frequently create and exit threads.
 
But anyway frequently create and exit thread is not a good design, otherwise why there has a threadpool? 

thanks!

**Comment by davidfowl** [comment]
> because my asp.net core program has a deaklock problem

If you have a dump or a repro then that would help.

> then i occasionally found asp.net core will frequently create and exit threads.

ASP.NET doesn't create custom threads, it uses the thread pool.

> But anyway frequently create and exit thread is not a good design, otherwise why there has a threadpool?

That might be a question for http://github.com/dotnet/corefx

**Comment by tiandian** [comment]
my asp.net core 2 program didn't crash, it just deadlock.
so there has no dump, 
when my asp.net core program deadlock,  vs2017 can't break it,  browser can't connect it.
because vs2017 can't debug it, so i has no way to find the problem code.

my program have 5 thread to download 3000 web pages use HttpClient as below, it often deaklock when after download some pages,  i has below code to download pages:

```
var client = new HttpClient(....)
var response = client.GetAsync(url, this._TokenSource.Token).GetAwaiter().GetResult();
if (response.IsSuccessStatusCode)
{
                string responseStr = response.Content.ReadAsStringAsync().GetAwaiter().GetResult(); 

....
}
```
I know the line string **responseStr = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();**  will cause deadlock, because when i comment this line, then there will not deadlock.

because my program dont crash, so i use DebugDiag from here https://blogs.msdn.microsoft.com/debugdiag/ to create a full Dump, i don't know where it would help.
if it helps, i will attach it to here, but it has 40M after compress to 7z.
or can you tell me how to create a dump for a deadlock program, then i can do it.

thanks!
