### ISSUE TITLE
WhiteList Interface Binding

### ISSUE THREAD

**Issue by granthoff1107** [aspnet/Mvc#6884]
I'm creating a white list interface binder, which inherits from ComplexTypeModel Binder.
In Order to bind I need to create binders for each of the types properties, but the type is suppose to be resolved at runtime, so depending on the information passed through the http request is how I am going to resolve the properties to bind.

```
public IModelBinder GetBinder(ModelBinderProviderContext context)
{
    if (!context.Metadata.IsCollectionType &&
        (context.Metadata.ModelType.GetTypeInfo().IsInterface ||
         context.Metadata.ModelType.GetTypeInfo().IsAbstract) &&
        (context.BindingInfo.BindingSource == null ||
        !context.BindingInfo.BindingSource
        .CanAcceptDataFrom(BindingSource.Services)))
    {
         //context.MetadataProvider.GetMetadataForType();
         var propertyBinders = new Dictionary<ModelMetadata, IModelBinder>();
         for (var i = 0; i < context.Metadata.Properties.Count; i++)
         {
             var property = context.Metadata.Properties[i];
             propertyBinders.Add(property, context.CreateBinder(property));
         }
        return new InterfaceBinder(this._options, propertyBinders);
    }

    return null;
}
```

Can I Get Access to the HttpRequest from the  `ModelBinderProviderContext` or is that something that Is cached and only run once?

If it is cached, is there a way I can modify the property binders at runtime, to create or remove properties based on the dynamically resolved type?

**Comment by frankabbruzzese** [comment]
Contexts objects are specific for each different request, otherwise they would be named differently. However, I don't remember `ModelBinderProviderContext ` allows access to HttpRequest ??? 
You may access HttpRequest from within the `ModelBindingContext `object that is passed to the Model Binder `BindModelAsync` method.

**Comment by granthoff1107** [comment]
@frankabbruzzese  Thanks for answering me,  I'm trying to modify a tutorial you wrote, Awesome Job by the way  you're the only person I saw who had an up to date tutorial that when over complex model binding.

My Issue is that the Complex Model Binder takes in a predetermined list of properties to the it's base,  I'm not exactly sure why, I can't determine my concrete type until my request is made, but by then the Complex Model binder already has it's properties set.

I'm trying to create a nested scope on the binding context, and then just using the ModelMetadataMap Reference to repopulate the dictionary, If that doesn't work I'll write a custom DynamicComplexTypeModel Binder.  I don't see any other way around it.

**Comment by granthoff1107** [comment]
I wrote a hack to solve the issue.  Basically we resolve our type at run time, and then we override our binding context scope to pretend we're of that type,  When we close our scope we copy our values back to our original scope.

As a Note we have to redefine IModelBinder on the Binder class so that when the base casts down to an IModelBinder it will call the proper bindModelAsync.    This is working but Ideally I should have redefined the ComplexModelBinder as a DynamicComplexModelBinder, because this is reliant on implementation details

```
    //Redefine IModelBinder so that when the ModelBinderProvider Casts it to an 
    //IModelBinder it uses our new BindModelAsync
    public class InterfaceBinder : ComplexTypeModelBinder, IModelBinder
    {
        public new Task BindModelAsync(ModelBindingContext bindingContext)
        {
            var propertyNames = bindingContext.HttpContext.Request.Query
                .Select(x => x.Key.Trim());

            var modelName = bindingContext.ModelName;
            if (false == string.IsNullOrEmpty(modelName))
            {
                modelName = modelName + ".";
                propertyNames = propertyNames
                    .Where(x => x.StartsWith(modelName, StringComparison.OrdinalIgnoreCase))
                    .Select(x => x.Remove(0, modelName.Length));
            }

            //split always returns original object if empty
            propertyNames = propertyNames.Select(p => p.Split('.')[0]);
            var type = ResolveTypeFromCommonProperties(propertyNames, bindingContext.ModelType);

            ModelBindingResult result;
            ModelStateDictionary modelState;
            object model;
            using (var scope = CreateNestedBindingScope(bindingContext, type))
            {
                 base.BindModelAsync(bindingContext);
                result = bindingContext.Result;
                modelState = bindingContext.ModelState;
                model = bindingContext.Model;
            }

            bindingContext.ModelState = modelState;
            bindingContext.Result = result;
            bindingContext.Model = model;

            return Task.FromResult(0);
        }

        protected override object CreateModel(ModelBindingContext bindingContext)
        {
            return Activator.CreateInstance(bindingContext.ModelType);
        }

        protected NestedScope CreateNestedBindingScope(ModelBindingContext bindingContext, Type type)
        {
            var modelMetadata = this._binderProviderContext.MetadataProvider.GetMetadataForType(type);
            
            //TODO: don't create this everytime this should be cached
            this._propertyMap.Clear();
            for (var i = 0; i < modelMetadata.Properties.Count; i++)
            {
                var property = modelMetadata.Properties[i];
                var binder = this._binderProviderContext.CreateBinder(property);
                this._propertyMap.Add(property, binder);
            }

            return bindingContext.EnterNestedScope(modelMetadata, bindingContext.ModelName, bindingContext.ModelName, null);
        }

    }
```
