### ISSUE TITLE
Port fix to 2.0.1: Zero Content-Length for static file 304 #6875

### ISSUE THREAD

**Issue by jbagga** [aspnet/Mvc#6887]
Porting fix to only set Content-Length when serving body and not for 304 or 412 responses

See #6875 

cc @Eilon @Tratcher

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon

**Comment by shravan2x** [comment]
I just tried the new `2.0.3-*` version. The content-length issue does indeed seem to be fixed.

The `Microsoft.AspNetCore.All` package included all of the packages in the published output. As I remember, it should only have included the ones that were actually used. Is this a side-effect of the pre release package system itself?

**Comment by Eilon** [comment]
@shravan2x actually when *publishing* an app, by default *none* of the packages references by `Microsoft.AspNetCore.All` should be in the published output. Only a few ASP.NET/EF Core-related packages might be there, and of course various 3rd party packages might be there.

Can you show what command you ran and what's in the publish output folder?

**Comment by shravan2x** [comment]
@Eilon I've seen that in ASP.NET Core 2.0 this is indeed the case. The number of packages is far lower than 1.0. However, when I ran the new `2.0.3-*` package, I remember seeing all packages, just as in `1.x`. I used the default "Publish to Folder" option in VS2017 (the latest version, 15.4 I think).

I will test again in the next few days and report back with more info.

**Comment by Eilon** [comment]
@shravan2x if you publish the app as a self-contained (also known as "standalone") app, it will contain all of ASP.NET Core *and* even all of .NET Core. I believe there's an option in the publish dialog to enable this, but it isn't the default setting.

If you can show what files are in the output folder that would help figure this out.

**Comment by shravan2x** [comment]
Sorry I haven't found time to check yet. I will definitely do it this weekend.

**Comment by shravan2x** [comment]
@Eilon I just tried publishing on `2.0.3-0` again, it worked as expected. I was likely mistaken earlier.

Looking forward to seeing this in release!

**Comment by Eilon** [comment]
@shravan2x thanks for confirming!
