### ISSUE TITLE
Colons in Request.Path always get unencoded

### ISSUE THREAD

**Issue by dustinsoftware** [aspnet/Mvc#6889]
### Title
Colons in Request.Path always get unencoded

### Functional impact
If a client sends a url with any colons in the path, e.g. `/a%3A1`, Request.Path will be set to `/a:1`. There appears to be no way to get the original, encoded form of the Path.

When computing an HMAC+SHA1 OAuth signature, access to the unmodified path is needed, or the signature will not match what was sent by the client.

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*

1. dotnet new webapi
2. Add a single catch all route:
```
    [HttpGet("{id}")]
    public string Get(string id) => $"{Request.Path}\n";
```
3. Run `curl http://localhost:5000/a%3A1`

### Expected result
Response is `/a%3A1`

### Actual result
Response is `/a:1`

### Further technical details
This is using .NET Core 2.0, tested on both Mac and Windows.

**Comment by benaadams** [comment]
Use `RawTarget` from `IHttpRequestFeature`?

Isn't on the DefaultHttpRequest object so you'll have to get it from the `HttpContext` features:

`context.Features.Get<IHttpRequestFeature>().RawTarget`

**Comment by dustinsoftware** [comment]
Thanks for the fast response! That works. :)

**Comment by Eilon** [comment]
cc @Tratcher FYI

But otherwise closing this issue since it was answered. Thanks @benaadams !
