### ISSUE TITLE
Url.Action with Route parameters in Controller Route

### ISSUE THREAD

**Issue by Tadimsky** [aspnet/Mvc#6890]
I'm having an issue using `Url.Action` to generate an absolute Url.
I moved a route parameter that is shared by all actions in the Controller into the `Route` parameter for the _whole controller_ and that seems to have broken the ability to generate a Url.

Here is a stub version of the Controller:

    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/whiteboards/{whiteboardId}/thumbnail")]
    public class ThumbnailController : Controller
    {
        public ThumbnailController()
        {
        }
        // GET api/v1/whiteboards/<id>/thumbnail
        [HttpGet]
        public async Task<Stream> Get(string whiteboardId)
        {
            Response.ContentType = "image/jpeg";
            return <data from store>;
        }

        // POST api/v1/whiteboards/<id>/thumbnail
        [HttpPost]
        public async Task Post(string whiteboardId)
        {
            <store thumbnail in store>
        }
    }

This is the code that I'm using to generate the Uri:

    return new Uri(Url.Action(new UrlActionContext
    {
        Controller = "Thumbnail",
        Action = "Get",
        Values = new
        {
            whiteboardId = 10
        },
        Protocol = Request.Scheme
    }));

However, this is returning `null`.

Switching it back to the following works, but doesn't look as good as we now have duplicated part of the route.

    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/whiteboards")]
    public class ThumbnailController : Controller
    {
        public ThumbnailController()
        {
        }
        // GET api/v1/whiteboards/<id>/thumbnail
        [HttpGet("{whiteboardId}/thumbnail")]
        public async Task<Stream> Get(string whiteboardId)
        {
            Response.ContentType = "image/jpeg";
            return <data from store>;
        }

        // POST api/v1/whiteboards/<id>/thumbnail
        [HttpPost("{whiteboardId}/thumbnail")]
        public async Task Post(string whiteboardId)
        {
            <store thumbnail in store>
        }
    }

Is this intended for it to not work? It would be really nice if it did, but maybe there is something that messes up the route generation when we do this?
Is using a parameter in the `Route` attribute in the constructor even supported/recommended at all?

**Comment by khellang** [comment]
What if you explicitly mark the `whiteboardId` parameter with `[FromRoute]`?

**Comment by Tadimsky** [comment]
Still seems to return `null` unfortunately 😞

**Comment by Tadimsky** [comment]
I haven't seen this be fixed, still relevant issue.

**Comment by mkArtakMSFT** [comment]
Thanks for confirmation, @Tadimsky.
@dougbu, can you please investigate this? Thanks!

**Comment by mkArtakMSFT** [comment]
Hi @Tadimsky.
If you explicitly specify the version in the route values, where you're generating the URL, does that help?

**Comment by Tadimsky** [comment]
@mkArtakMSFT so should I do:

```c#
return new Uri(Url.Action(new UrlActionContext
{
    Controller = "Thumbnail",
    Action = "Get",
    Values = new
    {
        whiteboardId = 10,
        version: 2.0
    },
    Protocol = Request.Scheme
}));
```

**Comment by rynowak** [comment]
Yes, that's what we're asking, what's the outcome when you do that?

In general these kinds of problems appear due to how route value invalidation occurs. It's briefly touched upon [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1#url-generation), but values are used from the ambient values until the first 'different' value is encountered - based on the lexical order of the parameters from left to right.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
