### ISSUE TITLE
RazorPages: ModelState.IsValid is always true when validating primitive properties on a Page Model.

### ISSUE THREAD

**Issue by asalvo** [aspnet/Mvc#6891]
When OnPost is called for the following page model. ModelState.IsValid always returns true regardless if the values for Username, Password and Email are valid. The ModelState appears to be fully populated if I inspect it by setting a breakpoint in the OnPost. 

If I try call TryValidateModel(this) in OnPost first, an exception is thrown (The requested operation is invalid for DynamicMethod). However, if I set a breakpoint in the OnPost, and run TryValidateModel(this) in the Immediate Window, I get the same exception, but, upon continuing, IsValid has finally changed to false, with the correct properties identified as having validation errors in the ModelState object. 

```
public class SignUpModel : PageModel
    {
        [BindProperty]
        [Required, StringLength(250)]
        public string Username { get; set; }

        [BindProperty]
        [Required, StringLength(250)]
        public string Password { get; set; }

        [BindProperty]
        [Required, EmailAddress, StringLength(250)]
        public string Email { get; set; }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            return RedirectToPage("/Index");
        }
    }
```

**Comment by pranavkm** [comment]
@asalvo this would be a dup of https://github.com/aspnet/Mvc/issues/6790. As of 2.0.0, Mvc did not support validation (or the `BindRequiredAttribute`) on top level properties and parameters. Putting these properties in a data bound model would be a possible workaround until 2.1.0 is out.
