### ISSUE TITLE
NTLM and cookie authentication

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#6893]
Our application uses windows authentication by default, however, for testing purposes, if a certain cookie is set, it should authenticate using cookie authentication.

So in the testing environment we tried to add the following to our pipeline:

    app.UseCookieAuthentication (new CookieAuthenticationOptions ()
      {
        AuthenticationScheme = "TestingCookieAuthenticationScheme",
        AutomaticAuthenticate = true,
        AutomaticChallenge = false,
        CookieName = "TestingCookieAuthenticationSchemeCookie"
      });

Our testers can surf to a special controller where they can login as any user (again, the controller is only available in our testing environment). The controller action looks like this:

    public async Task<IActionResult> SwitchUser (string user)
    {
      var nameClaim = new Claim("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name", user);
      var claimsIdentity = new ClaimsIdentity(new[] { nameClaim });
      await HttpContext.Authentication.SignInAsync("TestingCookieAuthenticationScheme", new ClaimsPrincipal(claimsIdentity));

      return View();
    }

However, even when the cookie is present (checked this via F12 tools), the `User.Identity.Name` still shows the NTLM authenticated user and not the cookie-authenticated user.

What are we doing wrong?

(ASP.NET Core 1.1)

**Comment by davidfowl** [comment]
Why don't the schemes match? You configured the cookie with the "TestingCookieAuthenticationSchemeCookie" scheme but then signed in with the "WebTestingCookieAuthenticationScheme" scheme.

Are you expecting the user to have both the windows identity and the cookie identity? Is the windows identity always there?

**Comment by drauch** [comment]
@davidfowl : Sorry, that's been a copy&paste error when creating a minimal repro sample. Actually they are the same, re-checked it & fixed in the original post.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Security#1467
