### ISSUE TITLE
Different behavior of HttpContextAccessor between windows and Linux

### ISSUE THREAD

**Issue by tiayi** [aspnet/Mvc#6899]
` 
services.AddTransient<HttpContextAccessor>().AddScoped<IOCRService>(provider => `
       `    {`
              ` //  provider.GetRequiredService<HttpContextAccessor>().HttpContext Is Always Null On  Linux Docker microsoft/aspnetcore:2 `
                
`var accessor = ActivatorUtilities.GetServiceOrCreateInstance<HttpContextAccessor>(provider);`
`var logger = provider.GetRequiredService<ILogger<Startup>>();`

` logger.LogWarning("accessor ==null ? " + (accessor == null));`
`                logger.LogWarning("accessor.HttpContext ==null ? " + (accessor.HttpContext == null));`
`                return ActivatorUtilities.CreateInstance<FakeOCR>(provider);`

`}`
`provider.GetRequiredService<HttpContextAccessor>().HttpContext`  Is Always Null On  Linux Docker microsoft/aspnetcore:2

**Windows is Ok.**
**Docker image microsoft/aspnetcore:2 is base on debian.**

**Comment by tiayi** [comment]
I seem to have used the wrong way to inject HttpContextAccessor.
The right ways is injecting IHttpContextAccessor,HttpContextAccessor.
But it also has different behavior between two plantforms.

**Comment by khellang** [comment]
It is also supposed to be registered as a singleton...

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/aspnet/HttpAbstractions/issues/946
