### ISSUE TITLE
How to implement ASP MVC CORE 2 DefaultControllerFactor

### ISSUE THREAD

**Issue by McKabue** [aspnet/Mvc#6900]
[I want to be able to call server side functionality by name instead of route. i have succeeded in doing that by creating a special action that receives a name of the other action to call and then return the result of that other action....[ VIEW THE QUESTION AT STACKOVERFLOW - ITS VERY LONG] ](https://stackoverflow.com/questions/46501242/how-to-implement-asp-mvc-core-2-defaultcontrollerfactor)

**Comment by Eilon** [comment]
I'm not sure I've fully understood the problem or what the intended behavior is.

It sounds to me that this could be solved by having a *single route* that responds to all requests in a single MVC controller action.

You can do it like this in your Startup.cs file:

```c#
routes.MapRoute(
    name: "default",
    template: "{*everything}",
    defaults: new { controller = "Home", action = "Index" });
```

And then you'd have one controller with one action:

```c#
public IActionResult Index(string everything)
{
    // do whatever you want here, and the 'everything' parameter will have
    // all the text in the URL
}
```

**Comment by McKabue** [comment]
+hello @Eilon  , 
i have created a route the resolves other routes by name. it works very well, but i want to implement a `DefaultControllerFactory` to achieve that behavior in a clean way...
this method there resolves other routes by name ::
`
[HttpPost(Name = "route")]
        public async Task Route([FromQuery]string route)
        {
            try
            {
                route = route?.UrlDecode();
                var _actions = Routes();
                var _action = _actions.FirstOrDefault(a => a?.Name == route || RouteMatcher.Parse(route, a?.Templates));
                if (_action.Name == "route") _action = _actions.FirstOrDefault(a => a?.Name == "routes");
                ActionDescriptor _actionDescriptor = _action?.Descriptor;

                this.RouteData.Values["action"] = _action.Action;
                this.RouteData.Values["controller"] = _action.Controller;

                ActionContext actionContext = new ActionContext(this.HttpContext, this.RouteData, _actionDescriptor);

                var services = HttpContext.RequestServices;
                var invokerFactory = services.GetRequiredService<IActionInvokerFactory>();
                var invoker = invokerFactory.CreateInvoker(actionContext);
                await invoker.InvokeAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
        }`

but how do i do that by utilizing the [DefaultControllerFactory](https://docs.microsoft.com/en-us/dotnet/api/Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory?view=aspnetcore-2.0)

**Comment by Eilon** [comment]
In general terms it involves implementing `CreateController` to use whatever logic you want to create a controller. It would be helpful if you can narrow it down to the specific problem you're having; it's difficult for us to debug this type of problem.

**Comment by McKabue** [comment]
+ @Eilon i have tried to create a controller inside DefaultControllerFactory
`ControllerContext _cc = new ControllerContext(actionContext);
DefaultControllerFactory dc = new DefaultControllerFactory(_controllerActivator, _propertyActivators);
var returnController = _controllerActivator.Create(_cc);
var c = dc.CreateController(_cc);
return returnController;`
but when the action is in a different controller, it results in a cast error [cannot convert from the new controller to current type]

**Comment by McKabue** [comment]
<code>
namespace Application.MvcRouter
{    
    public class CustomControllerFactory : DefaultControllerFactory
    {
        private IControllerActivator _controllerActivator;
        private IEnumerable<IControllerPropertyActivator> _propertyActivators;
        private IRouter _router;
        private IActionDescriptorCollectionProvider _actionDescriptorCollectionProvider;    
        public CustomControllerFactory(IRouter router, IActionDescriptorCollectionProvider actionDescriptorCollectionProvider, IControllerActivator controllerActivator, IEnumerable<IControllerPropertyActivator> propertyActivators) 
            : base(controllerActivator, propertyActivators)
        {
            _controllerActivator = controllerActivator;
            _propertyActivators = propertyActivators;
            _router = router;
            _actionDescriptorCollectionProvider = actionDescriptorCollectionProvider;
        }

        public override object CreateController(ControllerContext context)
        {
            //var controllerActionDescriptor = context.ActionDescriptor as ControllerActionDescriptor;
            try
            {
                if (context.HttpContext.Request.Path == "/api/route/name")
                {
                    var _actions = _actionDescriptorCollectionProvider.ActionDescriptors.Items.Select(a => new
                    {
                        Action = a.RouteValues["action"],
                        Controller = a.RouteValues["controller"],
                        Name = a?.AttributeRouteInfo?.Name ?? "/",
                        Template = a?.AttributeRouteInfo?.Template,
                        HttpMethods = (a?.ActionConstraints?.FirstOrDefault(m => m.GetType() == typeof(HttpMethodActionConstraint)) as HttpMethodActionConstraint)?.HttpMethods,
                        Descriptor = a
                    });

                    var _action = _actions.FirstOrDefault(a => /*a?.Name == name ||*/ (RouteMatcher.Match("{controller=Home}/{action=Index}/{id?}", a?.Name)?.Any() ?? false));
                    ActionDescriptor _actionDescriptor = _action?.Descriptor;

                    //https://github.com/aspnet/Home/issues/1543
                    context.RouteData.Values["action"] = _action.Action;
                    context.RouteData.Values["controller"] = _action.Controller;
                    context.HttpContext.Request.Path = $"{_action.Name}";
                    ActionContext actionContext = new ActionContext(context.HttpContext, context.RouteData, _actionDescriptor);

                    var services = context.HttpContext.RequestServices;
                    var invokerFactory = services.GetRequiredService<IActionInvokerFactory>();
                    var invoker = invokerFactory.CreateInvoker(actionContext);
                    invoker.InvokeAsync().Wait();

                    //ControllerContext _cc = new ControllerContext(actionContext);
                    //DefaultControllerFactory dc = new DefaultControllerFactory(_controllerActivator, _propertyActivators);
                    ////https://stackoverflow.com/questions/30167867/manually-create-controllers-in-mvc-6-with-custom-icontrollerfactory-implementati
                    //var returnController = _controllerActivator.Create(_cc);
                    //var c = dc.CreateController(_cc);
                    //return returnController;
                }
                return base.CreateController(context);
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        //public override void ReleaseController(ControllerContext context, object controller)
        //{

        //}
    }

    public static class RouteMatcher
    {
        // This method extracts the default argument values from the template.
        private static RouteValueDictionary GetDefaults(RouteTemplate parsedTemplate)
        {
            var result = new RouteValueDictionary();
            foreach (var parameter in parsedTemplate.Parameters)
            {
                if (parameter.DefaultValue != null)
                {
                    result.Add(parameter.Name, parameter.DefaultValue);
                }
            }
            return result;
        }

        //https://stackoverflow.com/questions/40125980/path-to-routevaluedictionary-in-asp-net-core
        public static RouteValueDictionary Match(string routeTemplate, string requestPath)
        {
            var values = new RouteValueDictionary();
            try
            {
                var template = TemplateParser.Parse(routeTemplate);
                var matcher = new TemplateMatcher(template, GetDefaults(template));
                var moduleMatch = matcher.TryMatch(requestPath, values);
                return values;
            }
            catch (Exception e)
            {
                return values;
            }
        }

        public static bool Parse(string requestPath, params string[] routeTemplates)
        {
            return requestPath.HasValue() && routeTemplates.Any(t => t.HasValue() && Match(t, requestPath).Any());
        }

    }
}
<code/>

**Comment by Eilon** [comment]
@McKabue it would be helpful if you could help narrow down where the specific problem is. It is unclear where in the code there's a problem.

**Comment by McKabue** [comment]
@Eilon i want to be able to implement `DefaultControllerFactory` so that i can invoke the any action in any controller...

**Comment by Eilon** [comment]
@McKabue I understand that, but it isn't clear exactly where you're having a problem. The scenario you describe is not very common, and it isn't clear what part of the code isn't working. I recommend running the code in the VS debugger and stepping through the code line-by-line to see where it doesn't work.
