### ISSUE TITLE
PackageReference without version

### ISSUE THREAD

**Issue by wangkanai** [aspnet/Mvc#6901]
How did you reference a package without the version and get them included?
```
<PackageReference Include="Microsoft.Extensions.Caching.Memory" />
<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
```

**Comment by pranavkm** [comment]
cc @natemcmaster

**Comment by rynowak** [comment]
This is build magic on our side. We manage the versions of our dependencies are part of a series of build steps.

**Comment by henkmollema** [comment]
Is there a way to make this work in Visual Studio? It looks like VS (15.3.5) doesn't like this which makes development of the ASP.NET Core stack pretty clumsy.

**Comment by pranavkm** [comment]
@henkmollema you have to run `build[cmd|sh] /t:Restore` (https://github.com/aspnet/Mvc#building-from-source) from the command line before launching the sln in VS.

**Comment by henkmollema** [comment]
I could have sworn I ran that and VS was still very upset with 1000s of build errors and no intellisense. I'll make sure I call `build.cmd /t:Restore` next time and see if it works. Thanks anyways! 😄

**Comment by Eilon** [comment]
We're working on clarifying some of the steps for working with these projects. We've done some magic for the source build because we have to coordinate a build of 50+ GitHub repos so we have to go a bit beyond the usual stuff.
