### ISSUE TITLE
Add 'global scope' result filters

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6904]
We have an major design issue - there's no way to register a result filter that runs for **all** results.

Result filters do this thing where they only run on the 'happy path' - you don't get to run for an action result that comes from an exception filter for example.

This breaks down if you want to implement a policy that needs to run for **all** results of a given type. Things we ship in the box that are designed to work with **all** result doesn't do so today - examples: `[Produces]` and `OnResultExecuting` on controllers.

This hasn't come up yet, but imagine you want to implement an exception filter that will short-circuit and return some data to be serialized for an API client. Well this won't take advantage of `[Produces]` today, because that code won't run.

-------------------

I propose we fix this by adding a new interface `IGlobalResultFilter` that derives from `IResultFilter` -  and also `IAsyncGlobalResultResult`. We should also retrofit `[Produces]` with this new interface.

This will work seemlessly on the 'happy path' because the executor will just run these new filters in order with the old ones - they are result filters after all.

The current code in here https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs#L144 needs to be updated to call `IGlobalResultFilter`s.

**Comment by Eilon** [comment]
@rynowak let me know if you want to load-balance.

**Comment by rynowak** [comment]
I got this started already and handed it off to @pranavkm because he asked to take it over 😆 

https://github.com/aspnet/Mvc/tree/rynowak/super-result-filter

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/7105.
