### ISSUE TITLE
ViewBag & Razor Pages

### ISSUE THREAD

**Issue by hishamco** [aspnet/Mvc#6907]
After I wrote my blog post [Bring ViewBag Back to Razor Pages](http://www.hishambinateya.com/bring-viewbag-back-to-razor-pages) @DamianEdwards is very sad because the `ViewBag` is `dynamic`  😄  and I mentioned that the better way to use page model properties

But the things that surprised me, why we have the `ViewBag` in Razor Page?!! while the intend to use the `ViewData` or any other mechanism in the future

**Comment by pranavkm** [comment]
It's a result of type hierarchy. `PageBase` derives from `RazorPageBase` which had ViewBag as property. Removing it now would be a breaking change, but we would encourage users to use `ViewData` \ https://github.com/aspnet/Mvc/issues/6525 feature whenever it becomes available.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
