### ISSUE TITLE
Figure out what to do about ProblemDetails::Type

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6913]
Today we're just putting in `about:blank` because we don't have a good URI for this. We should see if there is something smarter we can do.

**Comment by khellang** [comment]
For generic status code details, I've just used links to httpstatus.es in the past 😝

**Comment by mkArtakMSFT** [comment]
@danroth27 FYI

**Comment by danroth27** [comment]
@glennc @rynowak is Problem Details in scope for 2.2?

**Comment by glennc** [comment]
It is now.

**Comment by mkArtakMSFT** [comment]
Talked to @glennc regarding this. The intent here is to redirect to some manageable link if the destination is external, so we can control it if necessary.
@pranavkm, if this is not done, can you please handle this? Thanks!

**Comment by pranavkm** [comment]
> The intent here is to redirect to some manageable link if the destination is external, so we can control it if necessary.

We default to pointing to IETF RFCs and have a way to customize it at startup via options. Addressed as part of https://github.com/aspnet/Mvc/issues/8289
