### ISSUE TITLE
Encrypted dll doesn't work

### ISSUE THREAD

**Issue by srana863** [aspnet/Mvc#6918]
I have encrypted my application's dll with crypto obfuscator v2015 (my development environment is VS2017). It does the encryption. But problem is when i publish it on IIS10, it doesn't work. (Error Http Error 502.5 Process failure).

**Comment by Eilon** [comment]
Hi @srana863 can you share more info about this? We do not have enough information to investigate this. Can you attach a debugger to the process and see if any exceptions are thrown?

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
