### ISSUE TITLE
IFormFileCollection - System.ObjectDisposedException: 'Cannot access a disposed object.'

### ISSUE THREAD

**Issue by shammelburg** [aspnet/Mvc#6919]
I am trying to change each file in my IFormFileCollection to a stream to then upload to either Azure/AWS.

System.ObjectDisposedException: 'Cannot access a disposed object.' is thrown after the first file has successfully been uploaded.

I have followed the [Docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads)

and posted it on [StackOverflow](https://stackoverflow.com/questions/46583225/iformfilecollection-saving-multiple-files-from-stream)

**Comment by davidfowl** [comment]
Do not use async void. Use async Task.
