### ISSUE TITLE
Optional body parameters no longer work since upgrading to .NET Core 2.0

### ISSUE THREAD

**Issue by ben-foster-cko** [aspnet/Mvc#6920]
I have an action filter that automatically checks `ModelState` and returns `400` if it's not valid.

We have a few actions that have optional body parameters, for example:

```
        // POST api/values
        [HttpPost]
        public IActionResult Post([FromBody]SomeClass request = null)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            return Ok();
        }
```

Specifying the default value of `null` used to be enough to mark them as optional. Since upgrading to ASP.NET Core 2.0 I get the following response:

```
{
  "": [
    "A non-empty request body is required."
  ]
}
```

**Comment by ben-foster-cko** [comment]
It looks like the null handling behavior was changed in [this PR](https://github.com/aspnet/Mvc/commit/90acd055fe0e58ac131471435b28679a00ee7ed6#diff-114dc2a6d98896f96f7252280899afcd).

There is a new option `AllowEmptyInputInBodyModelBinding` that is `false` by default. If you want to handle the null values yourself you'll need to set this to `true`.

**Comment by hmvs** [comment]
Would be nice to have something like [FromBody(AllowNull=true)] instead of having this behavior for all the methods.
