### ISSUE TITLE
Add setter to MvcJsonOptions.SerializerSettings.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#6921]
From https://github.com/aspnet/Home/issues/2226

@Maly-Lemire 

I had an override for JsonSettings with all my desired configuration.
I have to reproduce everything in AddJsonOptions because I cannot directly set SerializerSettings.

**Comment by khellang** [comment]
Same as https://github.com/aspnet/Mvc/issues/6816?

**Comment by pranavkm** [comment]
Yup, sounds like it.

**Comment by pranavkm** [comment]
@Maly-Lemire, see https://github.com/aspnet/Mvc/issues/6816#issuecomment-329221624 for an explanation as to why the property isn't settable. Closing this as dup.
