### ISSUE TITLE
Mvc Web App template in docker generates incorrect URL

### ISSUE THREAD

**Issue by smitpatel** [aspnet/Mvc#6923]
Steps:
1. Create new ASP.NET Core Web Application
2. Choose Web Application template for 2.0
3. Add individual accounts auth
4. Enable Docker support for windows.

Restore packages/build solution etc.
Press F5
Expected output:
Website from template is opened in browser.
Actual output:
Browser fails to load website. The website URL in browser is http://172.21.203.31/https://localhost:44341/

**Comment by Eilon** [comment]
@natemcmaster - any ideas on this? Presumably a tooling issue? Do you know where those issues go?

**Comment by natemcmaster** [comment]
Yes, I'm supposing this is a VS issue. You can use the Report an Issue feature in VS or try your luck here: https://github.com/microsoft/dockertools

**Comment by Eilon** [comment]
This issue was moved to Microsoft/DockerTools#50
