### ISSUE TITLE
AddSingleton breaks in 2.0?

### ISSUE THREAD

**Issue by HarelM** [aspnet/Mvc#6924]
I'm in the middle of migrating my project from netcoreapp1.1 to netcoreapp2.0.
My code it at the following repository:
https://github.com/IsraelHikingMap/Site
There is a branch called NetStandard2.0 there where I updated the code in order to move from 1.1 to 2.0.
Most of the code stayed the same but a new bug started to appear after the migration:
I have a class there called LRUCache which caches the recently logged users - it is registered in the following class as **singleton**:
https://github.com/IsraelHikingMap/Site/blob/8d70dab7c0ea8fe63993d78fd1c30e8e7ca97fa4/IsraelHiking.API/RegisterApi.cs#L34
When running the project I see two instances with different hash code:
The first is here:
https://github.com/IsraelHikingMap/Site/blob/8d70dab7c0ea8fe63993d78fd1c30e8e7ca97fa4/IsraelHiking.Web/OsmAccessTokenValidator.cs#L17
and the second is here:
https://github.com/IsraelHikingMap/Site/blob/8d70dab7c0ea8fe63993d78fd1c30e8e7ca97fa4/IsraelHiking.API/Controllers/OsmController.cs#L39

When using the immediate window for those different flows I get those hash codes:
_cache.GetHashCode()
37382511
_cache.GetHashCode()
44927025

Am I crazy? Did I miss-configured something? Am I the only one who is reporting this?
Thanks ahead!

**Comment by Eilon** [comment]
`GetHashCode()` is not necessarily the best way to determine if two objects are the same because the type could have a buggy implementation of it... but in the case of this app that doesn't appear to be a problem.

Nevertheless, are you able to confirm whether they're actually the same instance or not? In VS you can "tag" an item in the watch window (right-click it and "add object tag") and see if they're truly the same, as opposed to just odd behavior with the hash code? Or set a breakpoint in the LRUCache constructor?

Also adding @pakrym in case he has thoughts on this.

This is definitely super weird, and does not appear to be expected...

**Comment by HarelM** [comment]
I know for sure that this is not the same instance as this class has a dictionary and one instance has it empty while the other has it with one item.
GetHashCode was just to illustrate that it's not the same one.

**Comment by pakrym** [comment]
@HarelM can you provide smaller repro or give instructions on how to run your site and reproduce the bug. I tried running it yesterday but got

```
D:\temp\Site\IsraelHiking.Web [NetStansards2.0 +0 ~1 -0]> dotnet run
Using launch settings from D:\temp\Site\IsraelHiking.Web\Properties\launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\pakrymet\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.

Unhandled Exception: System.ArgumentException: The directory name C:\Users\osmhike\Documents\GitHub\IsraelHiking\Map\English\ is invalid.
Parameter name: path
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at IsraelHiking.Web.Startup.SetupStaticFiles(IApplicationBuilder app)
   at IsraelHiking.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at IsraelHiking.Web.Program.Main(String[] args)
```

**Comment by HarelM** [comment]
I'll see if I can create a smaller reproduction.
Meanwhile you can run it from visual studio in debug mode or edit the appsettings.production.json file to point to an existing folder in your file system - this is a static files location the site is using, if the folder does not exists it throws.
you can also copy the appsetting.json and override appsettings.production.json.
The instructions on how to debug and run the site can be found here:
https://github.com/IsraelHikingMap/Site#setting-up-the-project-for-development

**Comment by Eilon** [comment]
This issue was moved to aspnet/DependencyInjection#595
