### ISSUE TITLE
Implicit translations for implicit validation!

### ISSUE THREAD

**Issue by aureole82** [aspnet/Mvc#6929]
ASP.NET MVC has a great feature: Implicit translations for default error messages and/or implicit validation!
Let's take this model:

```csharp
public class MyModel {
    public int Id { get; set; }
    public int MyInt { get; set; }
    public DateTime MyDateTime { get; set; }
    [Required] public string MyString { get; set; }
}
```

All I have to do is changing the `CurrentUICulture`:
![grafik](https://user-images.githubusercontent.com/4819891/31329924-889ddff0-acdc-11e7-90fe-f8a6a906713b.png)

**Please tell me where's the feature gone in ASP MVC Core?**

------
Please keep in mind
- The official documentation "Globalization and localization in ASP.NET Core" (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) ignores this question. Following those instructions would end up in adding thousands of validation attributes (implicit validation becomes explicit validation). Even worse: Each validation attribute must have the `ErrorMessage` specified. Even worse, part 2: Each `ErrorMessage` must get the translated string provided by a resource file (*.resx), one per model. Since I cannot use placeholder (e.g. `"The {0} field is required."`) I have to do that for each property in each model. That's insane!
- I know there are proposals out there to add explicit validation with the help of an `IValidationMetadataProvider`, e.g. https://blogs.msdn.microsoft.com/mvpawardprogram/2017/05/09/aspnetcore-mvc-error-message/. But I won't accept these ones as an answer. There are too error-prone. Even worse: The example spoils the complete concept of localization by pinning the error message to a single resource class.

Please tell me that I don't have to write hundreds of lines just to get the status quo!

**Comment by mkArtakMSFT** [comment]
Hi @aureole82.
Sorry for our late response.
Is this ask still relevant or should this issue be closed? Thanks!

**Comment by aureole82** [comment]
Yes, @ryanbrandenburg's issue [dotnet/corefx/issues/25128](https://github.com/dotnet/corefx/issues/25128) has addressed the right audience. Thanks alot, guys!
Maybe you could mark my issue as duplicate...

**Comment by ryanbrandenburg** [comment]
Yeah, I'll close as duplicate.
