### ISSUE TITLE
"page" variable in Razor breaks in 2.0?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Mvc#6931]
I have a `_Pagination.cshtml` view that uses a `page` variable, like this:
```
@model Daniel15.Web.ViewModels.Shared.PaginationModel
...
	@for (var page = 1; page <= Model.TotalPages; page++)
	{
		if (page == Model.CurrentPage)
		{
			<strong>@page</strong>
		}
		else
		{
			<a href="@Model.UrlGenerator(page)">@page</a>
		}	
	}
```

After upgrading from 1.1 to 2.0, I'm hitting this error:
```
The 'page` directive must appear at the start of the line.
+
			<strong>@page</strong>
The 'page' directives value(s) must be separated by whitespace.
+
			<strong>@page</strong>
The 'page` directive must appear at the start of the line.
+
			<a href="@Model.UrlGenerator(page)">@page</a>
The 'page' directive may only occur once per document.
+
			<a href="@Model.UrlGenerator(page)">@page</a>
The 'page' directives value(s) must be separated by whitespace.
+
			<a href="@Model.UrlGenerator(page)">@page</a>
```

I guess this is due to Razor pages (https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/) using the `@page` directive (and thus disallowing usage of variables called `page` within Razor), however, shouldn't this be mentioned in the upgrade notes? It's not in the migration docs: https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/

**Comment by Eilon** [comment]
Yup this is indeed a bug in 2.0.0, see https://github.com/aspnet/Mvc/issues/6706

We will have this fixed in the upcoming 2.0 patch. Sorry you ran into this!

**Comment by rynowak** [comment]
#6706 tracks the use of 'page' as a route parameter when **not** using razor pages. This is about the usage in Razor code.

Unfortunately any new directive we add becomes a reserved word in Razor.

**Comment by Daniel15** [comment]
> Unfortunately any new directive we add becomes a reserved word in Razor.

Which is fine, but please include it in the upgrade documentation. Right now, it's an undocumented breaking change.

**Comment by Eilon** [comment]
@Daniel15 I posted https://github.com/aspnet/Announcements/issues/272 in our list of breaking changes. Sorry for missing this! (These announcement issues are linked to from the migration doc at https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/)

**Comment by John0King** [comment]
@Eilon @Daniel15  why not just use `@razorpage`   or `@razor-page`  as the directive  for razor pages,  nobody use it as a variable .

**Comment by Eilon** [comment]
@John0King well, for now it's too late to change it because it already shipped. But that's something good for us to keep in mind when adding other new directives or reserved words.

**Comment by John0King** [comment]
@Eilon  My concern is that `page` is probably a very common variable in web development, at least 60% website use the it as a query  parameter for paging , and will create a `page` variable to display and dealing with it.

and other side,  change current razor pages to use new directive is easy,  search every .cshtml file and replace `^@page\s` to the new directive
