### ISSUE TITLE
test async call not effectiveness in asp.net core

### ISSUE THREAD

**Issue by MohammadAkbari** [aspnet/Mvc#6937]
I want to test effectiveness async request vs sync request in asp.net core 2.0. For this in Program file set Kestrel ThreadCount option to 1.

```
public class Program
{
    public static void Main(string[] args)
    {
        var host = new WebHostBuilder()
            //.UseKestrel(options =>  //core 1.1
            //{
            //  options.ThreadCount = 1;
            //})
            .UseLibuv(options=> options.ThreadCount = 1) //core 2.0
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseIISIntegration()
            .UseStartup<Startup>()
            .UseApplicationInsights()
            .Build();

        host.Run();
    }
}
```

Then write simple code in the controller for call async method. in Index action set the start time to ViewBag, then call Doing function async, finally set end time to ViewBag.

```
public class HomeController : Controller
{
    public async Task<IActionResult> Index()
    {
        ViewBag.Start = DateTime.Now;

        await Doing();

        ViewBag.Finish = DateTime.Now;

        return View();
    }

    public async Task Doing()
    {
        await Task.Delay(5000);
    }
}
```

View Code is:

```
<div class="row">
    Start: @ViewBag.Start
</div>
<div class="row">
    Finish: @ViewBag.Finish
</div>
```
After run app and browsing page in two browsers Simultaneously, I expected that two request start time be approximately equal. but in the result, after the first request finished, second is started.

Output in two browsers for

```
Start: 10/10/2017 10:16:36 AM
Finish: 10/10/2017 10:16:43 AM

Start: 10/10/2017 10:16:43 AM
Finish: 10/10/2017 10:16:50 AM 
```
What is wrong in my test or concept?

**Comment by Eilon** [comment]
FYI this was posted here as well: https://stackoverflow.com/questions/46661499/async-call-not-effectiveness-in-asp-net-core

**Comment by mkArtakMSFT** [comment]
Hi @MohammadAkbari.
Is this issue still relevant? Are you still facing this issue, or should we close it?

**Comment by poke** [comment]
I cannot actually reproduce this anymore with 2.0. I believe I could confirm OP’s observation before but I cannot anymore.

**Comment by mkArtakMSFT** [comment]
Thanks @poke.
We'll close this issue then. Given that this was filed a while ago, it is probably fixed now.
