### ISSUE TITLE
Utilizing the HTMLHelper.Editor to render a template editor causes issues with custom string editor

### ISSUE THREAD

**Issue by Tarig0** [aspnet/Mvc#6939]
If you use a view with the following code
```html
@model IEnumerable<Ninja>
<table>
<thead><tr><th>name</th></tr></thead>
<tbody class="template">@Html.Editor("Template","Ninja","Ninja[{0}]")</tbody><!--Stops at next level-->
<tbody>@HtmlEditorForModel()</tbody> <!--Works-->
</table>
```
```html
@model Ninja
<tr>
@Html.EditorFor(m=>m.Name)
</tr>
```

This will cause the string type to be visited and not allow me to use an editor template for my string property.

I suggest changing the default visited to Object, or add a generic Editor function that will take the intended visited type

**Comment by Eilon** [comment]
Hi @Tarig0 I'm not sure I understand the issue you describe. Can you provide more info about what is happening, and what you expected to happen?

In general the Editor/Display templates go through a series of types to figure out what to render. They might start out with an explicitly-requested type, and otherwise walk up the type hierarchy and interface hierarchy to find a "best" match. So, in genera, "Object" will always be the last template to try, because it's the least-specific one.

**Comment by Tarig0** [comment]
The issue is the 

Html.Editor("template","EditorForComplexType")

will eventually reach this line when generating the EditorForComplexType view

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ExpressionMetadataProvider.cs#L194

This then causes the Editorfor(m=>m.stringProp) to be skipped since the "String" type was already visited, but in reality the "ComplexType" is what was really visited

**Comment by dougbu** [comment]
@Tarig0 how is the `Template` property defined? I suspect that expression name is invalid and your view work work fine if the first attempt were changed to `@Html.Editor(string.Empty,"Ninja")`.

Separately, the third parameter to `EditorFor(....)` is not a format string, it's a prefix for generated HTML field names. Probably best not to use that parameter unless you're changing `ViewData.TemplateInfo.HtmlFieldPrefix` elsewhere or your actions bind with non-default model names.

**Comment by dougbu** [comment]
@Tarig0 please close this issue if your problem is solved. If the problem still exists, please provide a small repro project, preferably as a GitHub repo.

**Comment by Tarig0** [comment]
This does not work for my case. string.empty assumes I want to pass the current model down to the editor view when I want to pass a null instance of a different type.

The "Template" string is there to force a null model to be passed to the editor template.

I think a function like @Html.Editor<Ninja>("template","htmlprefix") would be for what I want in this case

**Comment by Tarig0** [comment]
I have a work around by adding the line
```c#
ViewData["Template"] = new Ninja();
```
but I would rather not have to create an instance of the class I need.

**Comment by Tarig0** [comment]
I'll see about creating a sample repo with a slightly more complex example

**Comment by dougbu** [comment]
@Tarig0 your original example compares two completely different things then: `@HtmlEditorForModel()` is the same as calling `@Html.Editor(string.Empty)` -- that'll iterate through the `IEnumerable<Ninja>`, displaying fields for all entries in the collection.

`@Html.Editor("Template")` doesn't work unless there's a `Template` entry in `ModelState` or `ViewData`. Without that entry, MVC knows nothing about this `Template`, can't find metadata, and assumes `string`.

If you want `@Html.Editor(...)` to create fields for a non-existent row, you probably want something like
``` c#
Ninja ninja = null;
@Html.EditorFor(m => ninja, nameof(Ninja), "[0]")
```
Note I haven't tested the above. `ninja` may need to be non-`null` for some reason I haven't considered.

**Comment by Tarig0** [comment]
I guess this is more of a suggestion now, but I think it would make sense to be able to provide the Html.Editor with a type so it can handle generating a template editor in cases where you want the front end to be able to generate a new row based on the template.
