### ISSUE TITLE
Unable to find source code for UriHelper

### ISSUE THREAD

**Issue by lukepuplett** [aspnet/Mvc#6940]
Hello, sorry if this is the wrong way to go about this but I am trying to find the source code for the Microsoft.AspNetCore.Http.Extensions.UriHelper class, apparently in 

Assembly Microsoft.AspNetCore.Http.Extensions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60

Specifically I have a null ref coming from GetDisplayUrl() under unit testing and I would like to look at the source so I can figure out how to fake my HttpRequest.

I can't find the code anywhere, I assume its in this repo but I've obviously tried Googling it and searching in some other repos.

Is there a general trick for finding code?

**Comment by rynowak** [comment]
I think this is what you're looking for: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/UriHelper.cs

A good trick is to go to https://github.com/aspnet and use the search box **at the top**.

Also, anything `Microsoft.Extensions` or `Microsoft.AspNetCore` should be findable in our github org.

**Comment by lukepuplett** [comment]
Thanks! I now see the error of my ways.

I was searching ~/aspnet/Home thinking that was the root, and then ~/aspnet/Mvc for the life of me didn't think to navigate up one level to ~/aspnet

(sigh)
