### ISSUE TITLE
TryUpdateModelAsync problems with Razor Pages 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Mvc#6941]
Code to reproduce the bug at https://github.com/Rick-Anderson/TryUpdateModelAsync

To reproduce the bug:

*  Run the project and tap on **Students** (`http://localhost:xxx/Students`)
* Tap **Create** and submit. The scaffolded code works.
* Tap **Create TryUpdateModelAsync** and submit. That code doesn't work.

[Code bug  here](https://github.com/Rick-Anderson/TryUpdateModelAsync/blob/master/ContosoUniversity/ContosoUniversity/Pages/Students/Create2.cshtml.cs#L34-L63)

**Comment by dougbu** [comment]
The problem is passing in an empty prefix. The prefix used [here](https://github.com/Rick-Anderson/TryUpdateModelAsync/blob/20321c186f9b29f7b99d9b5b68b1e5ca1ed155e0/ContosoUniversity/ContosoUniversity/Pages/Students/Create2.cshtml.cs#L45) should be `"Student"` or `"student"` to match the `<input/>`s in the form.

**Comment by Rick-Anderson** [comment]
@dougbu changed to [Student](https://github.com/Rick-Anderson/TryUpdateModelAsync/blob/master/ContosoUniversity/ContosoUniversity/Pages/Students/Create2.cshtml.cs#L45) - no joy

This is exactly the same code used in a [MVC controller](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud#update-the-edit-page), and no prefix was used there.

**Comment by dougbu** [comment]
I made the following two one line changes and everything lit up.
```
--- a/ContosoUniversity/ContosoUniversity/Pages/Students/Create2.cshtml.cs
+++ b/ContosoUniversity/ContosoUniversity/Pages/Students/Create2.cshtml.cs
@@ -42,11 +42,12 @@ namespace ContosoUniversity.Pages.Students

             if (await TryUpdateModelAsync<Student>(
                 emptyStudent,
-                "",
+                "student",
                 s => s.FirstMidName, s => s.LastName, s => s.EnrollmentDate))
             {
                 try
                 {
+                    _context.Students.Add(emptyStudent);
                     await _context.SaveChangesAsync();
                     return RedirectToPage("./Index");
```

**Comment by janis-veinbergs** [comment]
Yeah, [Razor Pages tutorial](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.1#update-the-edit-page) has slightly different code (contains prefix)
