### ISSUE TITLE
Unit Testing Page Model Throws Null Ref On ModelState check

### ISSUE THREAD

**Issue by scottsauber** [aspnet/Mvc#6943]
While testing Razor Pages, when I create a new PageModel, it throws a null reference exception when doing the ModelState.IsValid check.  The NRE is on ModelState itself.

This seems to be a change from the way MVC's ModelState "just worked" when newing up the controller.

For instance (some Arrange code removed for brevity)...

In MVC:
```csharp
var controller = new AccountController(dependency1, dependency2);
var result = await controller.Login(new LoginViewModel()));
// **Does NOT** throw NRE on ModelState.IsValid check
```

In Razor Pages:
```csharp
var loginModel = new LoginModel(dependency1, dependency2);
var result = await loginModel.OnPostAsync();
// **DOES** throw NRE on ModelState.IsValid check, because ModelState is null.
```

This is bit of an annoyance.

/cc @DamianEdwards

**Comment by rynowak** [comment]
You should be able to work around this for now by instantiating a `PageContext` and setting it.

We should fix this, all of this stuff needs to 'just work'

**Comment by scottsauber** [comment]
Appreciate the quick response!  Was just digging around into how to fix this, so that helps!  Thanks!

Any plans on this being on the roadmap for say 2.1?

**Comment by scottsauber** [comment]
`IUrlHelper` also throws a null ref

**Comment by Eilon** [comment]
This would be good as part of our efforts to make testing great.

**Comment by hishamco** [comment]
@javiercn I think this need to be closed

**Comment by javiercn** [comment]
@hishamco Nope. There's a PR out for fixing it but its not merged.

**Comment by hishamco** [comment]
What about this commit https://github.com/aspnet/Mvc/commit/316fb0ec63634ce591a8c0227b10588bfb0fa015?

**Comment by scottsauber** [comment]
@hishamco - that's just to the branch.  PR open here - https://github.com/aspnet/Mvc/pull/6953

**Comment by hishamco** [comment]
I see, it's my bad .. sorry
