### ISSUE TITLE
Two actions with same Http<Method> attributes result in ambiguity on ubuntu

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#6945]
_From @Petermarcu on October 12, 2017 20:38_

@distomin opened this here: https://github.com/dotnet/core/issues/1026

uname -a
Linux N46JV 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
dotnet --version
2.0.0
dotnet new webapi

Add 2 actions in a controller with the same attribute (HttpGet for example)
[HttpPost]
public Product Action4([FromForm]Product product)
[HttpPost]
public Product Action5([FromBody]Product product)

build the project, run the project and make http request.

fail: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[1]
      Request matched multiple actions resulting in ambiguity
... Microsoft.AspNetCore.Mvc.Internal.AmbiguousActionException: Multiple actions matched.

They say it works on Windows platform correctly.

_Copied from original issue: aspnet/Home#2241_

**Comment by pranavkm** [comment]
It's likely that the two actions have the same attribute route and this isn't an OS specific issue. Could you share a complete sample that reproduces this error?

**Comment by Eilon** [comment]
Indeed, we would need a complete repro app to try this out. This is very unlikely to be an OS-specific issue.

**Comment by distomin** [comment]
Guys, here you are 
https://github.com/distomin/aspnet-mvc-issue-6945
Enjoy :)

**Comment by pranavkm** [comment]
I see the same behavior on Windows, so this isn't is OS specific. You should be able to 

(a) Use specific routes for the two actions:

```C#
[Route("api/[controller]/[action]")]
public class ValuesController : Controller
...
```

OR 
* Use `ConsumesAttribute` to do the action discrimination:
```C#
[HttpPost]
[Consumes("application/json")]
public void PostJson([FromBody]string value)
{
}
```

**Comment by distomin** [comment]
Sorry guys,
I took this code from this course
https://courses.edx.org/courses/course-v1:Microsoft+DEV247x+2T2017/courseware/136fe0473993431b8d77b141d46b3319/4c475ca120f540748baaff8768eb1992/?child=first
And after little discussion there I was told that the code works fine on Windows,
so I thought it is platform related issue.

'Consumes' attribute works perfect.
Thank you!

**Comment by Eilon** [comment]
Ok sounds like this issue is good to close...
