### ISSUE TITLE
How to debug  the source  code on  my local machine ?

### ISSUE THREAD

**Issue by wjkhappy14** [aspnet/Mvc#6949]
I want to research the  MVC deeply  by  myself ,but when i  download this  code and open  with vs2017  the .Sln file, can't build ,many  errors .

someone can help me ?

**Comment by pranavkm** [comment]
@wjkhappy14 have you looked at the instructions for building from source (https://github.com/aspnet/Mvc#building-from-source)?

**Comment by Eilon** [comment]
@wjkhappy14 please provide more details about the exact errors you have. A screenshot or copy/paste the errors would be very helpful.

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
