### ISSUE TITLE
HttpRequestMessageExtensions.CreateResponse<T> should not accept T==HttpStatusCode

### ISSUE THREAD

**Issue by jerickmsft** [aspnet/Mvc#6952]
In an audit of our code base, we found that there were many calls that looked like:
`return Request.CreateResponse(HttpStatusCode.NotFound);`
that, due to a refactor, were actually resolving to this:
`HttpResponseMessage CreateResponse<T>(this HttpRequestMessage request, T value)`
This would make the service return a 200 with a body that says "NotFound".  This is clearly not the intent of the programmer.

Possible solutions would be:
1) Add a more specific extension that specifically targets HttpStatusCode (e.g.System.Net.Http.Formatting has one)
2) Throw if T is HttpStatusCode

[See also](https://github.com/aspnet/AspNetWebStack/issues/67)

**Comment by owenhuyn** [comment]
I don't exactly know if this is possible but you can add:
`HttpResponseMessage CreateResponse(this HttpRequestMessage request, HttpStatusCode statusCode)`

**Comment by mkArtakMSFT** [comment]
@jerickmsft, thanks for your feedback. However, we do not plan to add a new overload, as that would be a breaking change.
