### ISSUE TITLE
FormTagHelper support for asp-protocol (& asp-host)

### ISSUE THREAD

**Issue by synercoder** [aspnet/Mvc#6954]
Currently the difference between the `AnchorTagHelper` and the `FormTagHelper` is the following:

|                    | Anchor | Forms |
|--------------------|--------|-------|
| asp-action         | ✔      | ✔     |
| asp-controller     | ✔      | ✔     |
| asp-area           | ✔      | ✔     |
| asp-page           | ✔      | ✔     |
| asp-page-handler   | ✔      | ✔     |
| asp-fragment       | ✔      | ✔     |
| asp-host           | ✔      |       |
| asp-protocol       | ✔      |       |
| asp-route          | ✔      | ✔     |
| asp-all-route-data | ✔      | ✔     |
| asp-route-*        | ✔      | ✔     |

Since the `AnchorTagHelper` supports protocol and host, I don't think it should be too difficult to add support for them in the `FormTagHelper`. If need be I can try to make a PR for it.

I needed the ability to set the protocol on a form (to create a absolute url), and while checking the documentation/source code I found that there wasn't currently support for it on the forms tag.

Should I create a PR, or is this omitted/disabled for a reason?

**Comment by synercoder** [comment]
Alright, I did some digging in the code (scout work for a possible PR), to properly add the support, there needs to be a breaking change made to `IHtmlGenerator`. Because three extra methods need to be added.

[breakingchanges.netcore.json.txt](https://github.com/aspnet/Mvc/files/1384603/breakingchanges.netcore.json.txt)

As per guidelines: @Eilon and @DamianEdwards

**Comment by synercoder** [comment]
Another option would be to edit `DefaultHtmlGenerator` to expose `TagBuilder GenerateFormCore(ViewContext viewContext, string action, string method, object htmlAttributes)` as a static internal, and call that method from `DefaultHtmlGeneratorExtensions`. That way no breaking changes have to appear, but then extension method class for `IHtmlGenerator` for rely on the implentation of the class, which is a bad no no in my opinion.

**Comment by mkArtakMSFT** [comment]
@DamianEdwards, any thoughts regarding this? Thanks!

**Comment by DamianEdwards** [comment]
Legitimate request but unlikely to get prioritized unless the cost is extremely low (e.g. XS).

**Comment by mkArtakMSFT** [comment]
Thanks @DamianEdwards. Closing this then, as it seems this is not a priority at the moment.
