### ISSUE TITLE
Want features for data annotation 

### ISSUE THREAD

**Issue by amitsaini12345** [aspnet/Mvc#6955]
Please bring features to share common data annotations between each entity or model.  I will be no need to define separate separate data annotations for each properties of each entity.  

It would be more easy and bring code reusablity more if one can declare common data annotations of different properties because we see that common data annotation is like max length 50, int,  required etc. Are used to once and common for all entities.

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#24738
