### ISSUE TITLE
I cant reach post method of a subpage in asp.net Core Razor Pages

### ISSUE THREAD

**Issue by HolyOne** [aspnet/Mvc#6956]
I want to write code for my post method under the same page.
I know i can do that with handlers but I cant write asp-page-handler in my javascripts

Here is my form

```html
<form action="/mypage/mysubpage" method="post">
    <input type="text" name="test" value="t" />
    <input type="submit" />
</form>
```

I think the debugger should come to this line, just like as if i assigned a handler to it
but it doesnt.

`        public void OnPostMysubpage()
        {
            ViewData["msg"] = "oh yeah";
        }`

Is there an alternative way?

**Comment by hishamco** [comment]
Where is your form? please explain the case that you are trying to do in more details, to give you a clear answer

**Comment by mgasparel** [comment]
The handler can be specified in the url query string, ie:
`page?handler=mysubpage`

It can also be specified in the route, ie:
`page/mysubpage`

but this requires the route to be defined in the @page directive, ie:
`@page "{handler?}"`

**Comment by Eilon** [comment]
@rynowak do you know the answer to this?

**Comment by hishamco** [comment]
You can do it using JavaScript by passing the handler via querystring

**Comment by HolyOne** [comment]
Why should I post it via querystring? I have  @page "{handler?}" on my page.
shouldnt it post to /mypage/mysubpage ?

**Comment by hishamco** [comment]
Basically the handler name passed in via querystring, but this can passed via routing if you're using `@page "{handler}"`. I already did something similar [here](https://github.com/hishamco/RazorPagesCommands/blob/master/RazorPagesCommands/TagHelpers/CommandTagHelper.cs#L45)

So what you need to do to set the action property of the form to `YourPage.cshtml?handler=YouHandler` using javascript

**Comment by rynowak** [comment]
Hi @HolyOne - does this example show what you're looking for? https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?tabs=visual-studio#multiple-handlers-per-page

**Comment by hishamco** [comment]
@rynowak as @HolyOne mentioned in the first thread, he wanna call the handler from JavaScript, seems the solution that I gave previously is enough to do that using JavaScript

**Comment by rynowak** [comment]
Then it's just a URL that you need. You can generate one with `Url.Page("./", new { handler = "subpage" })`

**Comment by scottsauber** [comment]
This might be loosely related, but why is it in the default templates we need the Logout POST action to be a MVC Controller action and not a Razor Page Page Handler?

Seems like if you make a Logout Page with no Get page handler and only a Post page handler that it should just work.  I've tried to make it a Razor Page with just a Post handler and it doesn't seem to work.

I get that it's not "truly a page" in that case, because there's no HTML being served, but it is a little annoying to have to bounce over to the Controllers folder to view the Logout process of an app.  Just my 2c.

**Comment by rynowak** [comment]
Closing this because it seems like it's been answered. If I missed anything people create a new issue.
