### ISSUE TITLE
Url.Page() can not use path-based route if a custom route has been added

### ISSUE THREAD

**Issue by mgasparel** [aspnet/Mvc#6957]
After adding a custom route to my Index page, I am no longer able to generate URLs using the default path-based routes in Razor Pages.

Here is my custom route that allows me to add paging to the Index page, ie: `http://localhost:5000/page/2`

```
.AddRazorPagesOptions(options =>
{
    options.Conventions.AddPageRoute("/Index", "page/{pageNum}");
});
```

After adding that route, the following now returns null:
`Url.Page("/Index");`

Also, the following now throws *InvalidOperationException: No page named '/Index' matches the supplied values.*
`RedirectToPage("/Index");`

From what I can tell, this is the default behavior, based on the XML Documentation on the AddPageRoute method:
>The page can be routed via route in addition to the default set of path based routes. **All links generated for this page will use the specified route.**

Am I missing something, or is there no way to use the default path-based route after I start adding additional routes for a page?

**Comment by hishamco** [comment]
I tried all the scenarios that you mentioned before and everything working as expected, could you please show me your route in the razor page, also let us know which version you are using?

**Comment by mgasparel** [comment]
I made a small sample to reproduce at [https://github.com/mgasparel/url-repro](https://github.com/mgasparel/url-repro)

What I'm hoping to achieve is to have the following routes satisfied by a single page:
http://localhost:5000
http://localhost:5000/page/2
http://localhost:5000/page/3

Adding my custom page route in Startup.cs seems to do thr trick, but it also seems to mess up URL generation for the Index page. For example, Url.Page("/Index") returns null, *except* when you are on one of the paged routes. (If you are on http://localhost:5000/page/3, links generated for the Index page point to http://localhost:5000/page/3)

**Comment by hishamco** [comment]
It seems you miss the route segment in the `Index` page, try to modify the Index.cshtml page directive to:
```html
@page "{pageNum}"
```

BTW the url http://localhost:5000 will not work after the routing unless you mark the routing segment as optional parameter in the page directive

**Comment by mgasparel** [comment]
Marking the routing segment as optional does not work because the route includes the hardcoded segment "page/"... if I do this, then my generated url ends up pointing to http://localhost:5000/page

This also doesn't solve the issue that on any given page, the current route values are used to generate URLs unless they are explicitly cleared.

I did come up with a disgusting hack though!
`options.Conventions.AddPageRoute("/Index", "{s:regex(^page$)?}/{pageNum?}");`

Now this works on all pages:
`Url.Page("/Index", new { s = "", pageNum = "" })`

Similarly, you can get taghelpers working:
`<a asp-page="/Index" asp-route-pageNum="" asp-route-s="">Home</a>`

Would love to hear about any way to clean this up!

**Comment by hishamco** [comment]
What if you're using the one that I mentioned before?

**Comment by mgasparel** [comment]
using the page directive `@page {pageNum?}` works great, but maps urls to `http://localhost/2` instead of 'http://localhost/page/2`

**Comment by hishamco** [comment]
http://localhost/page/2 should works, because you already configure the routing above

**Comment by mgasparel** [comment]
If I keep the route declaration in Startup.cs, then yes, `http://localhost/page/2` works fine. However, URL generation for my index page *always* has a `/page` segment.

For example, `<a asp-page="/Index">` generates a link that points to `http://localhost/page/`

**Comment by hishamco** [comment]
Of course, so that's why I used `@page {pageNum}` instead of `@page {pageNum?}` 😄

**Comment by mgasparel** [comment]
But as you said, this breaks `http://localhost:5000` which is not an acceptable tradeoff.

**Comment by hishamco** [comment]
Yep because you override the default rout, this will definitely support all the cases that you mentioned before:
```
services.AddMvc()
     .AddRazorPagesOptions(options =>
     {
          options.Conventions.AddPageRoute("/Index", "");
          options.Conventions.AddPageRoute("/Index", "page/{pageNum}");
     });
```

**Comment by mgasparel** [comment]
aha! `options.Conventions.AddPageRoute("/Index", "");` is what I was looking for! Thanks!

Soooooo close! Unfortunately link generation is still always using the second route, so my Index route will still always point to the current route. So if I'm on `http://localhost:5000/page/2` then `<a asp-page="/Index">` will generate a link to `http://localhost:5000/page/2` and I can't seem to find a way to prevent it. 

Side question: will link generation always use the first matching route on the stack?

**Comment by hishamco** [comment]
If you're in the `http://localhost:5000/page/2` the `<a asp-page="/Index">` will generate `http://localhost:5000/page/2` because it's already defined in the route table, I'm not sure why you need to prevent it?!!

**Comment by mgasparel** [comment]
Just so I can easily generate links to the homepage or redirect the user after login etc...

**Comment by hishamco** [comment]
The easiest way is to avoid using `/Index` in the link, because It will generate the url based on the current route.
FYI don't forgot you're using the same page for all the routes

**Comment by mgasparel** [comment]
Appreciate the help @hishamco 

Thanks for the patience 👍
