### ISSUE TITLE
Hosting Http.Sys in production environment

### ISSUE THREAD

**Issue by rahulsahay19** [aspnet/Mvc#6958]
Hi Team,

Wanted to understand one thing. Let's say, I have written ASP.NET Core MVC application which is hosted on Http.Sys. Therefore, currently what I do, I navigate to published folder and there run **dotnet app.dll**. Server gets started and it starts to listen requests. However, this also opened dotnet console window, which is ok if I am doing development on local machine.

But, let's say I would like to take the published folder and deploy on server. Therefore, if I run the same command **dotnet app.dll**, server will get launched and start listening as well, I believe. But, it will have the same console window remain opened there. Is there any way to start the server as a background process, I mean server should keep running but cmd prompt shouldn't be there.

Thanks,
Rahul

**Comment by Eilon** [comment]
This issue was moved to aspnet/HttpSysServer#404
