### ISSUE TITLE
How to return a friendly view for 404?

### ISSUE THREAD

**Issue by HeroWong95** [aspnet/Mvc#6959]
I want return a friendly view(using '_Layout.cshtml')

- Call method 'ControllerBase.NotFound()'
- Wrong Url

**Comment by HeroWong95** [comment]
The method 'ControllerBase.NotFound()' is defined as
`public virtual NotFoundResult NotFound();`
If this method is defined as
`public virtual IActionResult NotFound();`
Only need return a 'ViewResult' object
`return new ViewResult
{
    StatusCode = 404,
    ViewName = "NotFound"
};`

**Comment by hishamco** [comment]
Have a look to a [Diagnostics](https://github.com/aspnet/Diagnostics) repo. Also I remember that I did something similar when I blogged about [Create Configurable Error Pages in ASP.NET Core](http://www.hishambinateya.com/create-configurable-error-pages-in-asp.net-core) long time back
