### ISSUE TITLE
Razor Pages Error with Section and TagHelpers 

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Mvc#6964]
Razor pages throws an error when working with sections.
PostData is class declared inside the backing cs file.

This works
```
<label asp-for="PostData.PostId"></label>
@section detailsSection {
}
```
Moving the TagHelp into a section produces and error.
`A local or parameter named '__model' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter`
```
@section detailsSection {
    <label asp-for="PostData.PostId"></label>
}
```
Moving it to a partial works
```
@section detailsSection {
    @Html.Partial("PostData", @Model.PostData)
}
```

**Comment by NTaylorMullen** [comment]
Hi @RandyBuchholz this is a known issue. Stay tuned for a patch release that fixes this 😄 

Duplicate: https://github.com/aspnet/Razor/issues/1614
