### ISSUE TITLE
Layout/PartialView access inconsistency

### ISSUE THREAD

**Issue by isonil** [aspnet/Mvc#6966]
In views:

Layout requires .cshtml extension:
`Layout = "/Views/Shared/_Layout.cshtml";`

But partial views don't:
`@await Html.PartialAsync("Foo/_BarPartial")`

I would expect this to be consistent.

**Comment by NTaylorMullen** [comment]
@isonil Layout shouldn't require the extension. When you provide a `/` prefix to your path you're saying you know exactly where to find a specific view. If you provide the syntax much like what you're doing in the `PartialAsync` call you're telling MVC to try and find the view based on its knowledge of where Views can live.

**Comment by isonil** [comment]
Ah, so with `/` you always have to specify the extension. Still feels a bit weird but at least it's consistent. Thanks for clarifying.

**Comment by NTaylorMullen** [comment]
No problem at all.
