### ISSUE TITLE
Seems IEnumerable has special casing when checking view's declared model compatibility

### ISSUE THREAD

**Issue by Tarig0** [aspnet/Mvc#6967]
Say I have a view with the following
```c#
@model IEnuermable<Animal>
```
and I have a controller which passes a List[Cat] object, this will work

if I change to IList I get a model is not compatible error.
```c#
@model IList<Animal>
```

**Comment by Eilon** [comment]
@Tarig0 can you show the exact error you're getting, and also let us know which version of ASP.NET Core MVC you're using?

**Comment by Tarig0** [comment]
Sorry I could have sworn I mentioned the model is List<Cat>

InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'System.Collections.Generic.List`1[Cat]', but this ViewDataDictionary instance requires a model item of type 'System.Collections.Generic.IList`1[Animal]'.

**Comment by Eilon** [comment]
Hmm it looks like covariance (or whatever) isn't playing nicely here.

@rynowak any idea how we ought to handle this?

This is the offending code: https://github.com/aspnet/Mvc/blob/c27b07ef3f8b07dfe1d1de38a8d7bf2d6a9298f4/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/ViewDataDictionary.cs#L489-L523

**Comment by rynowak** [comment]
This is how covariance works in C#.  MVC does not do anything special, we just follow the rules. Considering that `@Model` has a defined/known type in the view, you need to give us a model object that can be assigned to that type. 

If you tried the following, it would not compile:
```
IList<Animal> animals = new List<Cat>();
```

Here's the reason why this isn't supported - assume it were allowed:
```
IList<Cat> cats = new List<Cat>();
IList<Animal> animals = cats;
animals.Add(new Dog("Fido"));

// At this point 'animals' and 'cats' both refer to a List<Cat> which contains a Dog.
Cat cat = cats.First(); // Cats and Dogs living together!!!
```

What you're trying to do will work fine if you use `IEnumerable<Animal>` or `IReadOnlyList<Animal>`. You can see that `IReadOnlyList<>` has the `out` variance annotation https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Collections/Generic/IReadOnlyList.cs#L11 which is what you're looking for.

**Comment by rynowak** [comment]
Closing this as by-design. Please let us know if this explanation doesn't make sense

**Comment by Tarig0** [comment]
💥 Well that makes sense once I read enough about covariance. Thanks for pointing me twoards the ReadOnlyList
