### ISSUE TITLE
Fix MvcSandbox to not auto-refresh every 1 second.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#6968]
Remove the meta refresh from the `_Layout.cshtml`

**Comment by pranavkm** [comment]
Tsck tsck @javiercn

**Comment by javiercn** [comment]
Cause you could just have fixed it in less time that it took to open the issue.

**Comment by rynowak** [comment]
But then you wouldn't learn a lesson about personal responsibility

**Comment by NTaylorMullen** [comment]
> Cause you could just have fixed it in less time that it took to open the issue.

Can't 😄. It's part of a patch branch, don't want to churn those branches until the next patch release which hasn't happened yet. This can only be done in the future.

**Comment by javiercn** [comment]
717dc2639237dcfeafc11e5cbb2efb935324b3fd
