### ISSUE TITLE
Response being truncated when outputting event stream when IIS Express is reverse proxying

### ISSUE THREAD

**Issue by svallis** [aspnet/Mvc#6969]
I made a repo with simple test case for this issue. Clone and run the below and hit `/sse-test` and things work great when serving from Kestrel directly, but causes some inconsistent truncation when running through Visual Studio and IIS Express.

https://github.com/svallis/SseTest/

Here's the only real bit of code added to the repo after a `dotnet new mvc`:

https://github.com/svallis/SseTest/blob/master/Controllers/HomeController.cs#L38-L55

The output on Kestrel looks right and ends up complete:

```
1 of 5
2 of 5
3 of 5
4 of 5
5 of 5
```

The output under IIS Express is truncated:

```
1 of 5
2 of 5
3 of 5
4 of 5
5
```

I'm guessing this is some kind of response caching or other interference at play. What would be the correct way to get around it? Weirdly enough, using static strings works fine on both, it's only when the data is dynamic that problems seem to occur. The larger and more complex the data gets, the less deterministic the output seems to become.

**Comment by svallis** [comment]
I found https://github.com/SignalR/SignalR/issues/273 which suggested a working fix for this, adding the following to `web.config`:

```
<location path="sse-test">
  <system.webServer>
    <urlCompression doDynamicCompression="false"/>
  </system.webServer>
</location>
```

The referenced issue also suggests that _"There is no fix, it's a limitation of IIS classic mode and nothing can be done about it."_ Is that still the case, or is there a cleaner fix now we're in the .NET Core world? While the above solution works, it requires remembering to sync your web.config rules with your SSE endpoints. Worse, when it does fail it's hard to spot - the truncation just causes messages to be received late, and only the last one in the example above is never fully parsed (due to the client never seeing the terminating newlines).

**Comment by Eilon** [comment]
@Tratcher any ideas on this? And maybe what repo this bug should go to?

**Comment by Tratcher** [comment]
You can't do StatusCode(200) after writing to the body, it throws. Check your app logs to confirm. Change the action return type to void. On kestrel the flush gets the data out first, but in IIS it gets buffered by the response compression and dropped by the exception.

**Comment by Eilon** [comment]
Ah, indeed, it's dangerous to mix MVC's delayed action results along with writing directly to the response stream. You'll want to do one or the other; never both.

So, either set the status code explicitly in the action and then write directly to the stream, returning nothing from the MVC action, **or** do *everything* in an MVC action result (e.g. a custom action result that you would write).

**Comment by svallis** [comment]
Thanks @Tratcher - that was certainly an issue as well, but doesn't solve the core issue I had.

The response caching issue, although it manifests in a far less unpleasant way now and the final event is written out in full, still means events are delayed until the following event. This is what it looks like when running:

![Animated GIF](https://i.imgur.com/xbvwh5A.gif)

Events aren't processed until the newlines are received by the browser, which happens during the flush on the following event.

**Comment by Tratcher** [comment]
Yes, that's a limitation of IIS's response buffering as explained in the SignalR thread.
