### ISSUE TITLE
asp-for binds to incorrect value if view model has property with same name as route placeholder

### ISSUE THREAD

**Issue by joacar** [aspnet/Mvc#6972]
[AspNetCoreMVcBugs (2).zip](https://github.com/aspnet/Mvc/files/1397825/AspNetCoreMVcBugs.2.zip)
![bug](https://user-images.githubusercontent.com/439028/31764159-ac66751e-b4c0-11e7-93b5-ff03959c97c4.PNG)

**Comment by Eilon** [comment]
@joacar the tag helpers and HTML helpers in MVC have a prioritized list of where they get values from. They can get values from Model State's "attempted values" (which has results from model binding, which includes the values that went into method parameters, route data, etc.), values from ViewData (e.g. data that was explicitly set in a controller), or other places. You can see some of this logic [here](https://github.com/aspnet/Mvc/blob/35601f95b345d0ef938fb21ce1c51f5a67a1fb62/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/HtmlHelper.cs#L1158-L1182).

In this case what appears to be happening is that the `<input asp-for="id">` tag is getting its value from the highest-priority source, which is model state's "attempted values," which got its value from the action method having a parameter named `id`, and that had a value of `10`, which came from the route template that matched.
