### ISSUE TITLE
Simplified Chinese characters are garbled

### ISSUE THREAD

**Issue by Varorbc** [aspnet/Mvc#6979]
# Env:

vs2017 15.4.1

.net core 2.0.2

# Test One

        Console.WriteLine("中文");

![image](https://user-images.githubusercontent.com/5714438/31859365-7a8f2eee-b73d-11e7-8edf-3a854d4e4334.png)

result is success

# Test Two

        public IActionResult Index()
        {
            return Ok("中文");
        }

![image](https://user-images.githubusercontent.com/5714438/31859390-2aebc48c-b73e-11e7-859f-b28afdbd4b4c.png)

result is success too

#Test Three

            app.Run(async context =>
            {
                await context.Response.WriteAsync("中文");
            });

![image](https://user-images.githubusercontent.com/5714438/31859456-ee2a7e52-b73e-11e7-91a8-c9cb8c2b9af8.png)

result is failure

#Test Four

            app.Run(async (context) =>
            {
                Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                await context.Response.WriteAsync("中文");
            });

![image](https://user-images.githubusercontent.com/5714438/31859597-abecd970-b740-11e7-9586-0f135ebb63bb.png)

result is failure too

**Comment by John0King** [comment]
@Varorbc  You didn't response the correct `charset` header to browser
