### ISSUE TITLE
.net Core should support other kinds of localization

### ISSUE THREAD

**Issue by HolyOne** [aspnet/Mvc#6980]
I have used all .net project types for the last 10 years, and resource localization is always a nightmare.
I always ended up writing my own localization classes for every project to make it usable.

Please add support for native "gettext"
I can add support for native gettext myself but I have to modify base pages, base classes, and it is a pain. In the newer technologies I cant add gettext to data annotiations.

At least give us a chance to apply gettext in data annotations. 
For data annotations to support "gettext" localization, I should be able to write this.

`   [MaxLength(10, ErrorMessage= _("BloggerName must be 10 characters or less"))]
    public string BloggerName { get; set; }
`

But i cant put the const text in a dummy function, so i am unable to apply gettext here.

_(by the way why am I writing "10" here? Writing  {MaxLength} would be much better.)_

Why I am requesting gettext? Because I can use gettext localization in my delphi, php, c++ and many project types easily. It has its own tools to generate resource files from the code by simple text processing. And i use one method of localization with powerful tools in all my projects in all languages.

**Comment by mkArtakMSFT** [comment]
Hi @HolyOne. Thanks for submitting this proposal. We're closing this issue as it seems there has been no community interest in this ask.
