### ISSUE TITLE
Does FileStreamResponse in ControllerBase gets disposed?

### ISSUE THREAD

**Issue by codefactorydevelopment** [aspnet/Mvc#6981]
Trying to browse through the code but cannot find relevant place.

When returning `FileStreamResult` from controller, does the stream get disposed or should we make sure we call `HttpContext.Response.RegisterForDispose(stream)`?

thanks

**Comment by Eilon** [comment]
@jbagga can you take a look and see what MVC does here?

**Comment by jbagga** [comment]
> To dispose of it indirectly, use a language construct such as using (in C#)

https://msdn.microsoft.com/en-us/library/system.io.stream(v=vs.110).aspx#Remarks

The [using block on the FileResultExecutorBase](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/FileResultExecutorBase.cs#L342) disposes of the stream.

**Comment by Eilon** [comment]
@jbagga ah, so it does get disposed? I guess we can close the issue?

**Comment by jbagga** [comment]
Yeah we can! @codefactorydevelopment let us know if you have any further questions.
