### ISSUE TITLE
Base class for ViewResult and PartialViewResult

### ISSUE THREAD

**Issue by rjperes** [aspnet/Mvc#6984]
Since ViewResult and PartialViewResult share so much (properties and execution), why not have them inherit from a, abstract base class and just override ExecuteResultAsync, or some abstract method?

**Comment by Eilon** [comment]
They probably could have shared a base class for consolidating a bit of code, but I don't think it would have proven very useful - at least, no one has asked for it yet. That is, where would anyone use a new `ViewResultBase` type and operate only on that base type?

As a side note, ASP.NET MVC 1-5 did have a [`ViewResultBase`](https://github.com/aspnet/AspNetWebStack/blob/62d0b2df0bcca848a8e0848fd1866928df15528e/src/System.Web.Mvc/ViewResultBase.cs)

So, if there are concrete scenarios where having a base class (or an interface, or whatever) would prove useful, we would certainly consider it.

In the meantime closing this issue - we can reactivate if there are specific scenarios to consider.

**Comment by rynowak** [comment]
This is already a thing - all of the significant logic is shared, reusable, and extensible. 

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/ViewExecutor.cs

**Comment by rjperes** [comment]
This is not a big thing, granted, but since we (Microsoft+community) are making a fresh start, why not do it right? ViewResult and PartialViewResult and ViewResultExecutor and PartialViewResultExecutor share 99% of the code, the only difference I see (I may be wrong, though) is that ViewResultExecutor sets IsMainPage to true and PartialViewResultExecutor does not. It may be important to inspect an action result (in a filter, likely) to see if it is returning a view, in which case, a check of "context.Result is ViewResultBase" is easier than "context.Result is ViewResult || context.Result is PartialViewResult". Happy to contribute with a PR if you see value in it.

**Comment by Eilon** [comment]
@rjperes it isn't about right and wrong, it's a design choice. We felt that code factored by encapsulation is better than code factored by derivation.

**Comment by rjperes** [comment]
@Eilon: a good discussion to be held elsewhere! :-)
I just wanted to highlight that we have a lot of code duplication, that's all.
As I said, it's no big deal, happy for this to remain closed.

**Comment by Eilon** [comment]
@rjperes no worries, it's good to discuss these things and share thoughts!
