### ISSUE TITLE
Add vary-by-culture Attribute to Cache Tag Helpers

### ISSUE THREAD

**Issue by Rabadash8820** [aspnet/Mvc#6986]
I have numerous Views with large sections of markup that do not change unless the user changes their language preferences.  I prefer the CookieRequestCultureProvider to handle language selection, so when I want to cache these Views, I have to use code like below.  This feels quite verbose to me, for what I imagine is a fairly common use case in production apps; namely, caching by request culture.

```html
<cache vary-by-cookie="@CookieRequestCultureProvider.DefaultCookieName">
    <!-- Other markup... -->
</cache>
```

It would be great if the `<cache>` element included some kind of `vary-by-culture` attribute out of the box which, turning the above code into:

```html
<cache vary-by-culture="true">
    <!-- Other markup... -->
</cache>
```

Not only is this syntax cleaner, but it would also be `RequestCultureProvider`-agnostic, I think, as the caching mechanism could read the request culture from `HttpContext`'s `IRequestCultureFeature`, which could be set by query string, cookie, database, or whatever.  The only debate is probably whether to use Culture or UI Culture.  I would err on the side of UI Culture, but perhaps the cache key could be some kind of concatenation of both?

**Comment by Rabadash8820** [comment]
For the record, I have already made a patch that would implement this attribute, but I wanted to get some feedback on the idea for making a PR.  The patch uses the (hashed) UI Culture as the cache key.

**Comment by frankabbruzzese** [comment]
@Rabadash8820 ,
What about something like:

`<cache vary-by="@CultureInfo.CurrentUICulture.Name">
            ......
</cache>`

It doesn't depend on the way you handle culture (cookie or whatever).

**Comment by Rabadash8820** [comment]
Hm, don't know why I didn't think of that!  So I guess the question is, would `vary-by-culture` still be a syntactic sugar worth having?

**Comment by Rabadash8820** [comment]
Also, is my understanding here correct?

- The request localization middleware (added to the pipeline with `UseRequestLocalization()`) sets `CultureInfo.Current(UI)Culture`
- Views are parsed by the MVC middleware (added with `UseMvc()`)
- Therefore, as long as `UseMvc()` comes last in the middleware pipeline, the `<cache>` element in your above  solution will be cached correctly according to culture

**Comment by mkArtakMSFT** [comment]
Hi @Rabadash8820. 
While the proposal you have is valid, this is not something we've heard requests about hence we're closing this request for now. If the community interest in this request grows, we'll reconsider our position.
