### ISSUE TITLE
AddApplicationPart with loaded Assembly throw "Cannot find compilation library location for package"

### ISSUE THREAD

**Issue by epic2001** [aspnet/Mvc#6992]
Hi, I want to add external mvc controllers and compiled views to my asp.net core mvc webapp like plugin.

This sample code (in Startup Configuration) throw "InvalidOperationException: Cannot find compilation library location for package 'WebAI'":
```
var dllFullPath = @"C:\_\WebAI.dll";
var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(dllFullPath);
services.AddMvc()
    .AddApplicationPart(assembly);
```

Following the workaround at [https://github.com/dotnet/core-setup/issues/2981#issuecomment-322572374](url) I got the same exception:
```
var dllFullPath = @"C:\_\WebAI.dll";
var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(dllFullPath);
services.AddMvc()
    .ConfigureApplicationPartManager(manager =>
    {
        var oldMetadataReferenceFeatureProvider = manager.FeatureProviders.First(f => f is MetadataReferenceFeatureProvider);
        manager.FeatureProviders.Remove(oldMetadataReferenceFeatureProvider);
        manager.FeatureProviders.Add(new ReferencesMetadataReferenceFeatureProvider());
    })
    .AddApplicationPart(assembly);
```

Thank you!

**Comment by pranavkm** [comment]
Might be a dup of https://github.com/aspnet/Mvc/issues/6934. Notes from previous investigation - https://github.com/aspnet/Mvc/issues/6934#issuecomment-336544322.

**Comment by mkArtakMSFT** [comment]
Closing this as there was no any additional feedback in this area. Assuming that this was either a user problem, or indeed a dup of the referenced issue.
