### ISSUE TITLE
AttributeRouteModel does not get created for empty [HttpGet] attribute

### ISSUE THREAD

**Issue by Dresel** [aspnet/Mvc#6994]
When using an empty [HttpGet] attribute like this

    public class HomeController : Controller
    {
        [HttpGet()]
        public IActionResult Index() => Content("Hello World");
    }

the AttributeRouteModel will not be created:

     public class TestConvention : IApplicationModelConvention
    {
        public void Apply(ApplicationModel application)
        {
            // This returns Null
            var model = application.Controllers.First().Actions.First().Selectors.First().AttributeRouteModel;
        }
    }

When using the attribute like this `[HttpGet("")]` the model gets created though. Is this intended? I'm asking because I'm relying on the model and this is quite a drawback. Thanks.

**Comment by rynowak** [comment]
This is (sadly) by design. An `[HttpGet]` without a string means conventional routing.

What's the big blocker to creating the model yourself if you want everything to be attribute routed?

**Comment by Dresel** [comment]
Oh ok, missed that. Thanks for your fast reply.
