### ISSUE TITLE
[Authorize] attributes on Controller + Model do not combine.

### ISSUE THREAD

**Issue by HaoK** [aspnet/Mvc#6995]
Original issue: https://github.com/aspnet/Security/issues/1489

The expected behavior of [Authorize] on Controller + [Authorize(Policy = "Method"] on a method would be a combined policy that merges a default Authorize attribute and the method policy.  This should result in basically the "Method" Policy.

Today this merging/combining is broken, AuthorizationFilterContext ends up with two AuthorizeFilters (one for each attribute), and both filters are run, which effectively means there is no combining, and each attribute's policy is run.  

Normally this is fine as merging of authorization requirements is safe.  The problem is when the policies require different authentication schemes.  So if `[Authorize]` on the controller uses the default cookies authentication, but the method uses bearer, the controller challenge will 'win' since the attributes were not merged (when in actuality after merging, the method only uses the "bearer" scheme which should be the only one that's challenged)

**Comment by HaoK** [comment]
Note: the behavior basically is the Controller's attribute will be challenged, while the method attribute's schemes will not be challenged as that filter is never hit at all.

**Comment by HaoK** [comment]
Met with @rynowak @Tratcher @javiercn to discuss this, and the proposed fix is relatively straight forward, we'll add a new flag in MvcOptions to control whether all authorize attributes are merged into a single authorize filter instead of the current behavior where each level (global/controller/action) each get a filter.

I'll submit a PR as the next step.

**Comment by HaoK** [comment]
@rynowak so shockingly, implementing the new combining behavior is not as trivial as I imagined(hoped?)

Combining the controller/action authorize filter should be pretty straightforward, but what about global filters that were added explicitly like: `.AddMvc(opt=> opt.Filters.Add(new AuthorizeFilter(policy))`  

Is it reasonable to manipulate the filters and replace all AuthorizeFilters with a new single combined AuthorizeFilter (in the first index) of the filter collection?

**Comment by rynowak** [comment]
> Is it reasonable to manipulate the filters and replace all AuthorizeFilters with a new single combined AuthorizeFilter (in the first index) of the filter collection?

We need to check the global auth filter is `GetType() == typeof(AuthorizeFilter)` first, but then it should be fine. We need to handle the case where the developer subclassed.

**Comment by HaoK** [comment]
So from sniffing around the code, my initial thought is to add a new MvcOptions.CombineAuthorizeFilters flag, and to have ResourceInvoker's ctor look at this flag and then do the combination before it builds the FilterCursor.

@rynowak does that sound like the right direction, or is there a better approach?

**Comment by HaoK** [comment]
73bd09dc1c8abe2ff71cd33679fa17ebd04ff189

**Comment by mguinness** [comment]
@HaoK Which release did this fix make it into?  I tried [Microsoft.AspNetCore.All](https://www.nuget.org/packages/Microsoft.AspNetCore.All/2.0.8) but I still get the issue.

**Comment by HaoK** [comment]
It should be in everything after 2.1-preview1

**Comment by mguinness** [comment]
So it's not getting backported to 2.0 then?  A little disappointing since it's a bug.  Unfortunately I can't use 2.1 yet as the EF Core provider I use doesn't support it.  What workarounds are available, create a derived AuthorizeAttribute?

**Comment by HaoK** [comment]
Don't put attributes on the controller or anywhere else, just put a single one on your actions

**Comment by mguinness** [comment]
Yeah, but I have around 20 actions on this controller so not ideal.  At least the documentation at [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.0) should be updated to note this issue.
