### ISSUE TITLE
<select> with GetEnumSelectList loses state when browsing back

### ISSUE THREAD

**Issue by breyed** [aspnet/Mvc#6996]
Consider a page with a control like this, which lets you choose a value from a `State` enum:

``` HTML
<select asp-for="State" asp-items="Html.GetEnumSelectList<State>()"></select>
```

1. Set State to something besides the default choice.
2. Enter text into text input controls on the same form.
3. Click Submit. This causes a post to some page.
4. Click the browser Back button.

#### Result:
Notice that the text controls all retain their previous values. Notice that the select control has its previous value - but only for a moment. It quickly gets reset to the default value.

#### Desired result:
The select control retains its previous value (just like the text controls do).

**Comment by ctolkien** [comment]
> Notice that the select control has its previous value - but only for a moment. It quickly gets reset to the default value.

What JavaScript have you got running on the site? I doubt this is an issue with MVC. Are you able to spin off a repro?

**Comment by breyed** [comment]
The site uses jQuery 2.2.3 and Angular 1.5.5. If I remove both, the problem goes away.

The cause of the problem is the `selected="selected"` attribute that the tag helper adds to the first option.

For a repro, create a page with jQuery and Angular, a form, and this Razor:

``` HTML
<select asp-for="State" asp-items="Html.GetEnumSelectList<System.DateTimeKind>()"></select>
<select><option value="1" selected="selected">1</option><option value="2">2</option></select>
<select><option value="1">1</option><option value="2">2</option></select>
```

Set all the selections to their second options. Submit the form; then browse back. The first two selections will revert; the third will not.

Why does the tag helper add `selected="selected"`, since the first item is already the default?

**Comment by ctolkien** [comment]
>Why does the tag helper add selected="selected"

Because that is the value of `State` ?

>The site uses jQuery 2.2.3 and Angular 1.5.5. If I remove both, the problem goes away.

So this is a client side issue.

**Comment by breyed** [comment]
Good explanation. Changing the view model so that `State` is initialized as -1 (for which there is no enumeration field) solved the problem.
