### ISSUE TITLE
ProducesResponseTypeAttribute doesn't accept System.Net.HttpStatusCode

### ISSUE THREAD

**Issue by snebjorn** [aspnet/Mvc#6997]
https://github.com/aspnet/Mvc/blob/79e576b86c040d676dcd96a6e666dc75f79da211/src/Microsoft.AspNetCore.Mvc.Core/ProducesResponseTypeAttribute.cs#L14

It would be neat if you've able to do this:
`[ProducesResponseType(typeof(SomeType), HttpStatusCode.OK)]`

Or even better:
`[ProducesResponseType<SomeType>(HttpStatusCode.OK)]`

Instead of:
`[ProducesResponseType(typeof(SomeType), (int) HttpStatusCode.OK)]`

**Comment by pranavkm** [comment]
@javiercn \ @Eilon this is in the same vein as https://github.com/aspnet/Mvc/pull/6902. Should we just do a pass through our user facing APIs and add an HttpStatusCode overload where possible?

**Comment by mkArtakMSFT** [comment]
@pranavkm, is this fixed already?

**Comment by javiercn** [comment]
[ProducesResponseType(typeof(SomeType), (int) HttpStatusCode.OK)]

You can just use Microsoft.AspNetCore.Http.StatusCodes instead.

We could also consider an external PR for this

**Comment by Tratcher** [comment]
👎 Asp.Net Core does not make use of System.Net.HttpStatusCode, the enum type was poorly designed and should not be perpetuated in new API. Use Microsoft.AspNetCore.Http.StatusCodes instead.

**Comment by mkArtakMSFT** [comment]
Thanks @javiercn, @pranavkm.
After discussing this with @danroth27 and @Tratcher and decided this is not a direction we want these APIs to extend toward. Instead, as @Tratcher suggested, consider using the `Microsoft.AspNetCore.Http.StatusCodes` type instead.

**Comment by cwe1ss** [comment]
> @Tratcher  👎 Asp.Net Core does not make use of System.Net.HttpStatusCode, the enum type was poorly designed and should not be perpetuated in new API. Use Microsoft.AspNetCore.Http.StatusCodes instead.

Out of interest, what's the problem with that enum?

**Comment by Tratcher** [comment]
Status codes are not a closed set, any code between 100 and 999 is allowed. Enums work best for closed sets where all of the values are known.  That enum does not even include all the standardized codes. It also has multiple entries for some codes. I've found the usability to be lacking as it obscures the actual status code from you.

**Comment by cwe1ss** [comment]
@Tratcher thank you for the explanation! Sounds good!!
