### ISSUE TITLE
Test framework that works well with DI?

### ISSUE THREAD

**Issue by Rexota** [aspnet/Mvc#7000]
I've a few services and want to test them with dependency injection:

``` cs
services.AddScoped<IAccountService, AccountService>();
services.AddScoped<IMarketService, MarketService>();
services.AddScoped<IOrderService, OrderService>();
services.AddScoped<IAnnouncementService, AnnouncementService>();
services.AddScoped<IPageService, PageService>();
services.AddScoped<ITicketService, TicketService>();
services.AddTransient<IEmailSender, EmailSender>();
```

I know xunit doesn't support DI. Any suggestion? I'm having hard time to find tutorials etc.

**Comment by davidfowl** [comment]
What exactly are you trying to do? Are you testing an MVC application?

**Comment by Rexota** [comment]
It's web api application. I want to test the services I registered through DI, not the controllers..

**Comment by Eilon** [comment]
You could test this using functional tests. I'm not aware of any particular pattern or library specifically for testing dependency injection in an app.
