### ISSUE TITLE
Publishing Asp.net Core 2.0 / net461 / x86 using visual studio GUI does not work

### ISSUE THREAD

**Issue by wind-rider** [aspnet/Mvc#7001]
I'm trying to publish an asp.net core 2.0 project targeting the full .Net Framework to a folder using the gui in Visual Studio 15.5.0 preview 2.

The error I'm getting is:

```
Project is targeting runtime 'win7-x86' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.targets	19	
```

However, when I run it locally in IIS Express, it builds and runs fine.

**Comment by Eilon** [comment]
@pranavkm any idea on this?

**Comment by wind-rider** [comment]
with "using the gui" I meant: right-click on the project and click publish

**Comment by pranavkm** [comment]
@wind-rider could you share a sample app?

**Comment by pranavkm** [comment]
Feel free to reopen this issue once you have a sample to share. I suspect there's a outdated version of the SDK that might be causing this.

**Comment by candritzky** [comment]
I have exactly the same problem with VS 2017 15.6.2. A repro is attached.
[AspNetCoreTest.zip](https://github.com/aspnet/Mvc/files/1811129/AspNetCoreTest.zip)

**Comment by pranavkm** [comment]
@candritzky could you also share these additional files from your app's directory:

* `AspNetCoreTest.deps.json` from the output directory `bin\Debug` or `bin\Release` of the application? 
* `project.assets.json`, `AspNetCoreTest.csproj.nuget.g.targets` from the obj directory

I tried building your repro app and it looks fine to me. I don't see a reference to `Microsoft.NETCore.App`, perhaps there's some caching \ staleness involved here.

**Comment by candritzky** [comment]
@pranavkm Yes, seems to be some caching problem with VS2017. Happened only after I created a new ASP.NET Core project, then selected "Edit .csproj", changed the <TargetFramework> from netcoreapp2.0 to net461, build, publish --> error. After unloading and reloading the solution file, it worked.

Thanks for you quick replies. Let's close this issue again.

**Comment by pranavkm** [comment]
It's likely that the auto-imports that NuGet adds for you aren't being removed when you change the TFM. I'd encourage you to file an VS feedback item for this since it's primarily tooling focused - perhaps doing something as simple as Clean on the project any time target frameworks change might be a reasonable solution.
