### ISSUE TITLE
Localization doesn't work unless you add a package that isnt from microsoft

### ISSUE THREAD

**Issue by smartprogrammer93** [aspnet/Mvc#7002]
Hello,

I had a similar issue to this person as the link below,

https://stackoverflow.com/questions/39132868/localization-in-asp-net-core-mvc-not-working-unable-to-locate-resource-file

and the solution proposed on that page worked.

I was wondering why is this not documented. And why its required to install a package isnt even from microsoft.

Regards

**Comment by Eilon** [comment]
@smartprogrammer93 can you explain exactly what doesn't work? All the `QueryStringRequestCultureProvider` does is set the current request's culture based on the query string.

Using custom tag helpers for localization seems unrelated to me.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
