### ISSUE TITLE
Output of "dotnet new mvc" doesn't work immediately with VS code

### ISSUE THREAD

**Issue by wizofaus** [aspnet/Mvc#7004]
After running "dotnet new mvc", the directory is missing tasks.json and has an incomplete launch.json (with a number of templated parameters that need to be manually filled in).  I can't see any reason why "dotnet new mvc" can't do this itself so that the solution can just be debugged immediately with VS Code.
Using dotnet 2.0, VS Code 1.17.
Sorry if this is more of a VS Code issue than aspnet/mvc one.

**Comment by pranavkm** [comment]
@mlorbetske would this belong in https://github.com/dotnet/templating?

**Comment by mlorbetske** [comment]
Seems like it'd be more of a fit for aspnet/templating since it's for adding VS Code artifacts to the Web project templates.

**Comment by wizofaus** [comment]
FWIW this doesn't seem to be specific to this template - in general whatever template I use doesn't work inside VS Code without seemingly unnecessary tweaking. Maybe it's more of an issue with VS Code given you can build/run the resulting project using the dotnet command.  Or it might just be my computer...

**Comment by wizofaus** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/1167 seems to capture the same issue I'm seeing.
