### ISSUE TITLE
CSharpCompiler does not honor the DebugType setting specified in the project

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7006]

**Comment by pranavkm** [comment]
cc @rynowak \ @Eilon 

Related note: In the past, we used to produce portable pdbs all the time on CoreCLR and full pdbs on Windows when the right set of components were available. This was simple to do using an `#idfef`. When we moved to `netstandard2.0`, we realized this was no longer possible unless we cross-compiled. Full-pdbs on CoreCLR + Windows mostly work (Stack traces get read, VS break points work etc), but have issues with tools \ IDEs that only support portable pdbs (such as Omnisharp). That said if we address this issue and honor the project `DebugType` setting, we would generate the right kind of pdb all the time.

**Comment by Eilon** [comment]
So this is about Razor view compilation not respecting the app's programmatic preferences for Razor view compilation?

**Comment by pranavkm** [comment]
We pick up a couple of the compilation settings in the app's project file and apply it to the compilation of the Razor's generated C# content. Things like `LanguageVersion`, `WarningsAsErrors`. We have access to the project's `DebugType` setting, we just missed using it as part of compilation. 

> So this is about Razor view compilation not respecting the app's programmatic preferences for Razor view compilation?

We don't have a way to programmatically specify this value.

**Comment by rynowak** [comment]
Related: https://github.com/OmniSharp/omnisharp-vscode/issues/1816#issuecomment-340140488

We use windows pdbs if possible, but that's not good for omnisharp/vscode.

**Comment by pranavkm** [comment]
@mkArtakMSFT self assigning for 2.1.0-preview1 milestone. This involves relatively small work for a decent payoff.
