### ISSUE TITLE
asp-format not respected due to datetime-local

### ISSUE THREAD

**Issue by zoinkydoink** [aspnet/Mvc#7007]
It seems that the html tag helper is adding stuff i dont think i want?
I have the following

`<input  asp-for="EndDateTimeUTC" class="form-control" asp-format="{0:yyyy-MM-ddThh:mm}">`

which produces 

`<input class="form-control valid" type="datetime-local" data-val="true" data-val-required="The EndDateTimeUTC field is required." id="EndDateTimeUTC" name="EndDateTimeUTC" value="2017-10-31T12:17" aria-required="true" aria-invalid="false" aria-describedby="EndDateTimeUTC-error">`

Which makes the value of the textbox `10/31/2017 12:17 PM`

I also tried 
`     [DisplayFormat(DataFormatString = "{0:yyyy-MM-ddThh:mm}", ApplyFormatInEditMode = true)]
        public DateTime EndDateTimeUTC { get; set; }
`

I simply want to force the textbox to show what ever format I want and not stick its nose in and put a datetime-local which seems to mess everything up.

What is the approperiate way to have a textbox show the format i want.
The reason I need it in a specific format is because I am trying to use Any+Time control https://www.ama3.com/anytime/ I have to sync the format applied to the textbox and what i set in the control for me not to get warnings by jquery that my date format are not stanard

**Comment by Eilon** [comment]
@zoinkydoink if you set `type="text"` on your `<input>` tag, does that fix it? I think that might override ASP.NET Core's default processing of data types in input tag.

cc @dougbu in case you have more thoughts on this.

**Comment by zoinkydoink** [comment]
i gave up trying, i went back to Html.TextBoxFor

**Comment by dougbu** [comment]
@zoinkydoink please confirm: The `asp-format` is honored i.e. `value="2017-10-31T12:17" ` is what you expected. However, the `type="datetime-local"` addition isn't what you want.

Also, `<input type="text" ... />` in the .cshtml file should lead to `input="text"` in the generated HTML, If that didn't happen, we have a bug.

FYI `[Datatype("text")]` or `[UIHint("text")]` should avoid the need for `type="text"` in every `<input/>` tag helper.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
