### ISSUE TITLE
asp-for now not working when casting in asp.net core 2

### ISSUE THREAD

**Issue by taylorjandrew** [aspnet/Mvc#7008]
The asp-for casting shown below used to work in core 1.0 and core 1.1 but now doesn't in core 2.0?
`<input asp-for="@(Model as ServiceOperative).JobTitleClient" class="form-control" />`
It now gives the following error -
**InvalidOperationException: Templates can be used only with field access, property access, single-dimension array index, or single-parameter custom indexer expressions.**
The following gets round the initial error, but then renders the name/id as somodel_JobTitleClient - which then will not bind to the object server-side
`var somodel = (Model as ServiceOperative);`
`<input asp-for="@somodel.JobTitleClient" class="form-control" />`

I tried a bunch of alternatives to the above but had to revert to using @Html.EditorFor for now...   =painful rework   :(

**Comment by Eilon** [comment]
@pranavkm can you take a look? Presumably we changed our expression generator here...

Also cc @rynowak

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Razor#2065
