### ISSUE TITLE
Port CSharpCompiler does not honor the DebugType setting specified in the project to patch release

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7010]
Work item: https://github.com/aspnet/Mvc/issues/7006

We could consider taking this in a patch since it affects Razor debugging in VS Code (and possibly other IDEs that don't support full pdbs). https://github.com/OmniSharp/omnisharp-vscode/issues/1816

**Comment by Eilon** [comment]
Not planning to patch this.
