### ISSUE TITLE
Razor page rendering doesn't wait for OnGet and OnGetAsync to complete

### ISSUE THREAD

**Issue by zippy1981** [aspnet/Mvc#7011]
Using an ASP.NET App run from the console and the ASP.NET logging I've determined that `public async void OnGetAsync()` or `public async void OnGet()` will start to execute before the razor page is executed, but the Pages don't wait for the function to complete before they fire.

I can fix this by removing the `async` keywords and replacing `await Foo()` with `Foo.Result()`. However, everything I understand (which is not as much as I should) about `async`, `await` and `System.Threading.Tasks` seems to indicate this is  a bad idea.

On to code proof. Here is a code-behind:

    public class IndexModel : PageModel
    {
        
        [BindProperty]
        public ILogger<IndexModel> Logger { get; }

        [BindProperty]
        public string JsonValue { get; private set; }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private void LogIncrement([CallerMemberName]string caller = null)
        {
            Logger.LogDebug($"Counter {caller} - {_counter++}");
        }

        public IndexModel
            (ILogger<IndexModel> logger)
        {
            Logger = logger;
            LogIncrement();
        }
		
        public async void OnGetAsync()
        {
            LogIncrement();
            
			var client = new HttpClient();
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, "http://localhost:2919/api/values");
            Logger.LogTrace("Http client created");

            var response = await client.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                JsonValue = await response.Content.ReadAsStringAsync();
            }
            Logger.LogTrace("Done with OnGet()");
        }
    }

And the page for it:

	@page
	@using Microsoft.Extensions.Logging
	@model IndexModel
	@{
		ViewData["Title"] = "Home page";
	}
	 
	@{ Model.Logger.LogTrace("Top of Razor view"); }
	   

	<div class="row">
	@{
		<div class="col-md-offset-3 col-md-6 text-center">
			<pre>@Model.JsonValue</pre>
		</div>
	}
	</div>

		
	@{ Model.Logger.LogTrace("Bottom of Razor view"); }

If I run this and hit the index page twice I get the following in the console log:

	Hosting environment: Development
	Content root path: C:\Users\zippy\Documents\Visual Studio 2017\Projects\WebApplication1\WebApplication1
	Now listening on: http://localhost:19494
	Application started. Press Ctrl+C to shut down.
	dbug: WebApplication1.Pages.IndexModel[0]
		  Counter .ctor - 0
	dbug: WebApplication1.Pages.IndexModel[0]
		  Counter OnGetAsync - 1
	trce: WebApplication1.Pages.IndexModel[0]
		  Top of Razor view
	trce: WebApplication1.Pages.IndexModel[0]
		  Bottom of Razor view
	trce: WebApplication1.Pages.IndexModel[0]
		  Http client created
	trce: WebApplication1.Pages.IndexModel[0]
		  Done with OnGet()
	dbug: WebApplication1.Pages.IndexModel[0]
		  Counter .ctor - 2
	dbug: WebApplication1.Pages.IndexModel[0]
		  Counter OnGetAsync - 3
	trce: WebApplication1.Pages.IndexModel[0]
		  Http client created
	trce: WebApplication1.Pages.IndexModel[0]
		  Top of Razor view
	trce: WebApplication1.Pages.IndexModel[0]
		  Bottom of Razor view
	trce: WebApplication1.Pages.IndexModel[0]
		  Done with OnGet()

So we enter `OnGetAsync()` and as soon as we call something with `await` whatever control is returned to (presumably `PageActionInvoker` from my limited investigation) isn't waiting for `OnGetAsync()` to complete before it starts to render the page.

We also know that each time the page is called, a new instance of the code behind class is created. So yes I could move logic into the constructor. That seems like a bad idea though.

**Comment by rynowak** [comment]
You need to define the handler methods as `async Task` not `async void`. We're looking at building an analyzer that will warn about cases like this in the future.

**Comment by zippy1981** [comment]
Thanks, that did it.
