### ISSUE TITLE
IUrlHelper Link - Ignore Properties

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [aspnet/Mvc#7016]
Hi!

I'm using IUrlHelper to create paging links.

Like:
`urlHelper.Link(RouteName, ObjectWithPagingData)`

That works and it generates the URL.

However that same object has some public properties I'd like to ignore and not include.
But even decorating the property like so, it ends up in the URL:
```
 [IgnoreDataMember]
        [JsonIgnore]
        [XmlIgnore]
        public Int32? ServerPageNumber
```

Is there a different attribute/way of doing this I need to use, or is this some kind of bug?

Thanks for the help!

**Comment by Eilon** [comment]
Hi @OpenSpacesAndPlaces , there is currently no way to do this directly.

There are two alternatives:
1. Create a new type that has only the properties you want to be included in the route
2. Use a dictionary type instead, and include only the keys/values you want to be included in the route
