### ISSUE TITLE
ViewContext not resolved on TagHelperComponent

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Mvc#7017]
When inheriting from `TagHelperComponent` or `TagHelperComponentTagHelper` the _ViewContext_ property is not being set.

**Repro steps**
1. Create a class inheriting from `TagHelperComponent`
2. Add _ViewContext_ property like below
3. Run app

```c#
[ViewContext]
public ViewContext ViewContext { get; set; }
```

**Expected**
The _ViewContext_ property be set so it can be consumed in the `Process` and `ProcessAsync` methods.

**Actual**
The _ViewContext_ property is null

**Comment by NTaylorMullen** [comment]
We need to add the logic to contextualize components before they run.

**Comment by Eilon** [comment]
@NTaylorMullen so this already happens for Tag Helpers, but not Tag Helper Components?

**Comment by NTaylorMullen** [comment]
@Eilon correct. We have a custom activator for TagHelpers but not for TagHelperComponents.

**Comment by Eilon** [comment]
Got it, this seems reasonable to me.

@jbagga / @rynowak - any concerns about adding this to 2.1?
