### ISSUE TITLE
I met a mistake：Multipart body length limit 16384 exceeded

### ISSUE THREAD

**Issue by ynanech** [aspnet/Mvc#7019]
I use the middle to achieve large file upload, but encountered a mistake, I should be how to solve?

![0](https://user-images.githubusercontent.com/20282409/32305424-7721496a-bfb0-11e7-87c6-afe55d0ba76e.png)
![1](https://user-images.githubusercontent.com/20282409/32305435-7f86eb50-bfb0-11e7-8dfa-a5bc07f46119.png)
![2](https://user-images.githubusercontent.com/20282409/32305441-84bdc5c6-bfb0-11e7-9891-e0e5dfb2960c.png)

_All of the settings below are invalid_

```c#
public void ConfigureServices(IServiceCollection services)
    {      
        services.Configure<FormOptions>(x =>
        {
            x.ValueLengthLimit = int.MaxValue;
            x.MultipartBodyLengthLimit = int.MaxValue;
            x.MultipartHeadersLengthLimit = int.MaxValue;
        });

        services.AddMvc();
    }
```

**Comment by Eilon** [comment]
@Tratcher any idea on this limit?

**Comment by Tratcher** [comment]
Some multipart bodies include preamble data before the first mutipart section. MultipartReader automatically drains that portion but limits it to 16k. There's not currently a way to configure this behavior.
See https://github.com/aspnet/HttpAbstractions/blob/c0f937239a0a099b73c67c96ab9e1c875952f67f/src/Microsoft.AspNetCore.WebUtilities/MultipartReader.cs#L48-L50

Do you know why your upload includes a large preamble section? This is likely unintentional.

**Comment by Eilon** [comment]
@Tratcher parking this on your plate until we can figure out what's wrong.

**Comment by ynanech** [comment]
@Tratcher @Eilon  
Thank you for your help.
I want to adjust the limit, but the setting is invalid, I want to achieve a separate file upload service through the middleware, I test only upload a 31.7KB file, it is temporarily unable to achieve this idea, I refer to this tutorial:
[https://docs.microsoft.com/zh-cn/aspnet/core/mvc/models/file-uploads#uploading-large-files-with-streaming](url)

**Comment by Tratcher** [comment]
What client are you using for the upload? An HTML form in a browser? Which browser?

Can you share a Fiddler trace of the upload? From your description it contains unexpected content.

**Comment by ynanech** [comment]
@Tratcher 
I use Postman to upload, and this is the fiddler content
![5](https://user-images.githubusercontent.com/20282409/32361695-d333a0a2-c09d-11e7-898d-e93a33603bfe.png)


This is the test code:
`
    public class FileStreamUploadMiddleware
    {
        private readonly RequestDelegate _next;

        public FileStreamUploadMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task Invoke(HttpContext context)
        {
            var boundary = HeaderUtilities.RemoveQuotes(context.Request.ContentType);
            var reader = new MultipartReader(boundary.Value, context.Request.Body);
            reader.HeadersLengthLimit = int.MaxValue;
            var section = await reader.ReadNextSectionAsync();
            while (section != null)
            {
                ContentDispositionHeaderValue contentDisposition;
                var hasContentDispositionHeader = ContentDispositionHeaderValue.TryParse(section.ContentDisposition, out contentDisposition);

                if (hasContentDispositionHeader)
                {
                    if (HasFileContentDisposition(contentDisposition))
                    {
                        //保存文件
                    }
                }
                section = await reader.ReadNextSectionAsync();
            }
        }

        #region Helper
        public static bool IsMultipartContentType(string contentType)
        {
            return !string.IsNullOrEmpty(contentType)
                   && contentType.IndexOf("multipart/", StringComparison.OrdinalIgnoreCase) >= 0;
        }
        public static bool HasFileContentDisposition(ContentDispositionHeaderValue contentDisposition)
        {
            // Content-Disposition: form-data; name="myfile1"; filename="Misc 002.jpg"
            return contentDisposition != null
                   && contentDisposition.DispositionType.Equals("form-data")
                   && (!string.IsNullOrEmpty(contentDisposition.FileName.Value)
                       || !string.IsNullOrEmpty(contentDisposition.FileNameStar.Value));
        }
        #endregion
    }

`

**Comment by Tratcher** [comment]
Can you save and upload that Fiddler trace? I need to see the request body.

**Comment by ynanech** [comment]
Is this one?
[4_Full.txt](https://github.com/aspnet/Mvc/files/1441054/4_Full.txt)

**Comment by Tratcher** [comment]
The request looks normal, but I see you're retrieving the boundary incorrectly.
`var boundary = HeaderUtilities.RemoveQuotes(context.Request.ContentType);`
The linked sample code does this instead:
```
    var boundary = MultipartRequestHelper.GetBoundary(
        MediaTypeHeaderValue.Parse(Request.ContentType),
        _defaultFormOptions.MultipartBoundaryLengthLimit);
```

**Comment by ynanech** [comment]
I don't know how to express my feelings. I'm too tired. My code is the same as the core part of the official sample code. Can you look at the code with my heart?
[https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/MultipartRequestHelper.cs](url)
` public static string GetBoundary(MediaTypeHeaderValue contentType, int lengthLimit)
        {
            var boundary = HeaderUtilities.RemoveQuotes(contentType.Boundary);
            if (string.IsNullOrWhiteSpace(boundary))
            {
                throw new InvalidDataException("Missing content-type boundary.");
            }

            if (boundary.Length > lengthLimit)
            {
                throw new InvalidDataException(
                    $"Multipart boundary length limit {lengthLimit} exceeded.");
            }

            return boundary;
        }`

**Comment by Tornhoof** [comment]
What @Tratcher is referring to:
You use:
``var boundary = HeaderUtilities.RemoveQuotes(context.Request.ContentType);``
``context.Request.ContentType`` is in your request ``multipart/form-data; boundary=----WebKitFormBoundary8Su1nBMUX1qEXx1z``, you need to first parse it, because you're only interested in the **boundary** parameter

In the reference code you posted, contentType is already a parsed ``MediaTypeHeaderValue``, take a close look at your screenshot it says ``contentType.Boundary``, and take a look at the method signature it says ``MediaTypeHeaderValue``, so yes you need to do exactly what @Tratcher  said, parse the content-Type to ``MediaTypeHeaderValue`` then take the property ``Boundary`` and strip the (optional) quotes.
e.g.
```csharp
var parsedContentType = MediaTypeHeaderValue.Parse(context.Request.ContentType);
var boundary = HeaderUtilities.RemoveQuotes(parsedContentType.Boundary);
```

**Comment by ynanech** [comment]
I am sorry, I ignored this small detail, thank you very much for the patience solution. thank
