### ISSUE TITLE
GET request with json body

### ISSUE THREAD

**Issue by mrahhal** [aspnet/Mvc#7020]
I have a GET action that accepts a complex body (json). Turns out this doesn't work outside of the box.

Is this by design? And what is the recommended approach for this use case?

**Comment by Eilon** [comment]
@rynowak / @Tratcher - any idea on whether the current support for GET-with-body is deliberate?

**Comment by Tratcher** [comment]
This is by design. Very few HTTP stacks allow GET to have a body. You need to use POST or similar.
