### ISSUE TITLE
Razor Pages do not appear to support ViewBag variables

### ISSUE THREAD

**Issue by KenSpr** [aspnet/Mvc#7026]
Neither Razor pages (with the ```@page``` directive) nor their C# code-behind files seem to support ViewBag.  For instance copying C# code from an existing Asp.net Core 2.0 MVC controller causes compile-error when ViewBag is encountered. The same is true for Razor Pages: the razor-page code (with an @page directive) does not recognize references to ViewBag variables. 

We think that 'Pages' are great for aspects of a complex project and intend to use both MVC and Pages together but we would prefer not having to change fundamentals like page-variable storage. We understand that ViewBag is not recommended for new code in favor of ViewData, however, in our opinion, since Asp.Net Core 2.n MVC Controllers and Razor Views both support ViewBag variables, we think that Asp.Net Core 2.n 'Razor Pages' should also support ViewBag. Otherwise, it is difficult to move code between the two mechanisms. This also infringes on 'separation of concerns' because developers have to coordinate variable storage details rather than just adding '@page' to the top of a page (as explained in MS documentation).

**Comment by scottsauber** [comment]
See this discussion here - https://github.com/aspnet/Mvc/issues/6754#issuecomment-326763351.  ViewBag was intentionally left out.

**Comment by Eilon** [comment]
Correct, per https://github.com/aspnet/Mvc/issues/6754#issuecomment-326763351, we are not planning on adding ViewBag to Razor Pages.
