### ISSUE TITLE
Hiding inherited methods in a controller

### ISSUE THREAD

**Issue by rootwalla** [aspnet/Mvc#7030]
Hello, I apologise if this was asked before, if it was I would appreciate a link to it, as I could not find it myself.
I am using aspnetcore 2.0 to create a restful API service.
Now, in order to maximise code reuse I would like to use the inheritance pattern for my API version increments and I've run into a considerable problem.

Here is some pseudo-code:
```c#
namespace v1
{
    [Route("v1")]
    public class SomeController : ControllerBase
    {
        [HttpGet("something/")]
        public object SomeMethod()
        {
            return 1;
        }
		
	[HttpGet("athing/")]
	public object AnotherMethod()
	{
            return "a";
	}
    }
}
namespace v2
{
    [Route("v2")]
    public class SomeController : v1.SomeController
    {
        [HttpGet("something/")]
        public new object SomeMethod()
        {
            return 2;
        }
    }
}
```
Calling `GET v2/athing/` works fine, calling `GET v2/something/` throws a: `AmbiguousActionException: Multiple actions matched`
Thus my question, what is the appropriate way to hide inherited members in a controller?

Thank you for your time and effort.

EDIT: made the sample a little clearer.

**Comment by Eilon** [comment]
There is no direct support for this in ASP.NET Core MVC. You might be able to write a custom controller convention to change this behavior. Here's a different sample showing some other capabilities of controller conventions: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.GenericControllers - perhaps you can use the code as a reference and adapt it to your needs.

I think if you instead make the method `virtual` you can then *override* the method, and avoid using the `new` keyword.

cc @rynowak in case you have other thoughts.

**Comment by rootwalla** [comment]
The problem appears due to the duplication of the HttpGet attribute, not so much implementation.
Thus my solution was to introduce an abstract class at the beginning of the stack, thus:
```c#
namespace v1
{
	public abstract class SomeAbstract : ControllerBase
	{
		[HttpGet("something/")]
		public abstract object SomeMethod();
		
		[HttpGet("athing/")]
		public abstract object AnotherMethod();
	}
	
	[Route("v1")]
	public class SomeController : SomeAbstract
	{
		public override object SomeMethod()
		{
			return 1;
		}
		
		public override object AnotherMethod()
		{
		    return "a";
		}
	}
}
namespace v2
{
	[Route("v2")]
	public class SomeController : v1.SomeController
	{
		public override object SomeMethod()
		{
			return 2;
		}
	}
}
```
Notice that the child implementations declare only route attributes, that way the httpGet of individual leafs are declared only once.

Thanks again for the time and effort (on this and on the whole mvc)
