### ISSUE TITLE
Add @using before @page shows 404

### ISSUE THREAD

**Issue by hishamco** [aspnet/Mvc#7032]
Is this by intention or is it a bug?

/cc @rynowak @NTaylorMullen

**Comment by NTaylorMullen** [comment]
By design. `@page` must be at the top of the file.

**Comment by hishamco** [comment]
Strange!! I remembered from ASP.NET WebPages before that we can @using before @inherits

Is there any reason why we can't use @using before?

**Comment by NTaylorMullen** [comment]
> Is there any reason why we can't use @using before?

We do a "quick" parse of each Razor file on disk by only looking at the first directive in order to determine routing information 😄. If the directive could be anywhere we'd have to parse more of the file significantly impacting startup perf.

**Comment by hishamco** [comment]
But we can look for the lines that starts with the `@` symbol instead to parse the entire file, IMHO this will not affect the performance too much and we're free to use `@using` before `@page`
