### ISSUE TITLE
Support input type "week"

### ISSUE THREAD

**Issue by jbagga** [aspnet/Mvc#7034]
Similar to #6615

**Comment by jbagga** [comment]
There is no straightforward way to format dates to week number and .NET does not completely follow ISO 8601 https://blogs.msdn.microsoft.com/shawnste/2006/01/24/iso-8601-week-of-year-format-in-microsoft-net/
@dougbu @Eilon 
There will be some additional logic to check for last and first weeks because we may need to change the provided year for corner cases.

**Comment by dougbu** [comment]
@jbagga do you mean you need to implement [Shawn Steele (MSFT)](https://social.msdn.microsoft.com/profile/Shawn+Steele+%28MSFT%29)'s approach, with the "if the requirement is to compute a date in the 2004W536" complication? Is there more to it e.g. needing to implement a `ICustomFormatter` / `IFormatProvider` pair (or pairs)?

**Comment by jbagga** [comment]
The former. Which isn't super complicated. I have it working for HTML helpers, working on tag helpers now. Just FYI that it isn't as straightforward as "month". I don't think we need `ICustomFormatter` or `IFormatProvider`.
