### ISSUE TITLE
Allow the use of exceptions instead of IActionResult - Needed for Swagger, RAML, etc.

### ISSUE THREAD

**Issue by Grauenwolf** [aspnet/Mvc#7036]
Here is an example of problematic code:

```csharp
public async Task<IActionResult> DoSomething(Contract contract)
{
    if (!ModelState.IsValid)
        return BadRequest(ModelState);

    var updatedContract = await _Service.SaveAsync(contract);
    return Ok(updatedContract);
}
```

Because the return type is a generic value instead of a specific one there is no way for IDL generators such as Swagger or RAML to determine what the response format will be. 

Furthermore, this eliminates type checking of the return value. If updatedContract is the wrong type, the compiler won't catch the error.

**Comment by tverboon** [comment]
It is possible to decorate your actions:

```csharp
[ProducesResponseType(typeof(Contract), (int)HttpStatusCode.OK)]
[ProducesResponseType(typeof(ErrorModel), (int)HttpStatusCode.BadRequest)]
public async Task<IActionResult> DoSomething(Contract contract)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

            var updatedContract = await _Service.SaveAsync(contract);
         return Ok(updatedContract);
    }
```
Does this help?

**Comment by Grauenwolf** [comment]
I don't know yet, but at first glance that appears to be a very clumsy workaround. That's the kind of thing you'd do in a typeless language like VBScript.

**Comment by khellang** [comment]
I'd be interested in seeing an example, like the one mentioned above, written in a way that lets you get the metadata you're talking about. Let's see how clumsy the alternatives are 😉

**Comment by Grauenwolf** [comment]
You get the metadata the same way you always have, using standard reflection. 

    public async Task<IContract> DoSomething(Contract contract)
    {
        if (!ModelState.IsValid)
            throw new HttpException(BadRequest);

            var updatedContract = await _Service.SaveAsync(contract);
         return updatedContract;
    }

And you notify the caller of error states the same way we've always done, using exceptions. (And a filter to convert them into the correct HTTP status code. But you need that anyways for handling exceptions from internal methods.)

Benefits:

* It uses idiomatic C# code
* Normal reflection works.
* Return values are type checked
* All IDL generators (e.g. Swagger) understand it.
* No risk of the attribute not matching the actual return type

**Comment by Grauenwolf** [comment]
I'm not saying that IActionResult shouldn't exist. We do need access to the plumbing some times. But in a typical project the vast majority of the controllers shouldn't know that even exists.

**Comment by rynowak** [comment]
We've already added for 2.1 (not talked about much yet sadly) `ActionResult<T>` to address this gap.

`ActionResult<T>` is convertible from both `T` and `ActionResult` which makes it act like a discriminated union.

**Comment by BladeWise** [comment]
@rynowak As far as I could see, while `ActionResult<T>` is nicely 'unwrapped' (i.e. Swagger picks `T` as the result model), inheriting from `ActionResult<T>` does not yield the same result.
Consider a class that wraps a 'standardized' result object, used to shape the response of the API (`Result<T>`), and an `ActionResult<T>`-derived class used to simplify the generic definition (`ApiResult<T>`):

``` C#
    public class Result<T>
    {
        public string Message { get; set; }
        public T Value { get; set; }
    }

   public class ApiResult<TValue> : ActionResult<Result<TValue>>
   {
        public static implicit operator ApiResult<TValue>(TValue value)
        {
            return new ApiResult<TValue>(value);
        }

        public static implicit operator ApiResult<TValue>(Result<TValue> value)
        {
            return new ApiResult<TValue>(value);
        }

        public static implicit operator ApiResult<TValue>(ActionResult result)
        {
            return new ApiResult<TValue>(result);
        }
        
        public ApiResult(TValue value)
                : base(new Result<TValue>
                       {
                               Value = value
                       })
        {
        }

        public ApiResult(Result<TValue> value)
                : base(value)
        {
        }

        public ApiResult(ActionResult result)
                : base(result)
        {
        }
    }
``` 
In such a case while an action defined as
``` C#
        [HttpGet("Strings")]
        public async Task<ActionResult<Result<IEnumerable<string>>>> GetStringsAsync()
        {
            await Task.CompletedTask;
            return new Result<IEnumerable<string>>
                   {
                           Value = new[]
                                   {
                                           "a", "b"
                                   }
                   };
        }
``` 
yields the following swagger
![good](https://user-images.githubusercontent.com/127625/37081436-baf90f7e-21e9-11e8-95c3-405b9f0c778e.PNG)

an action defined using the `ActionResult<T>`-derived class does not unwrap (notice the `result` property and the actual `Result<T>` wrapped in a `value` property, both inherited from `ActionResult<T>`):
``` C#
        [HttpGet("Strings2")]
        public async Task<ApiResult<IEnumerable<string>>> GetStrings2Async()
        {
            await Task.CompletedTask;
            return new Result<IEnumerable<string>>
                   {
                           Value = new[]
                                   {
                                           "a", "b"
                                   }
                   };
        }
``` 
![bad](https://user-images.githubusercontent.com/127625/37081791-d6385a3c-21ea-11e8-98fb-d6ec74a9a63c.PNG)

 Is this an unsupported scenario? Is it possible to create a custom class that acts like `ActionResult<T>` or extend the `ActionResult<T>` to other classes?

**Comment by pranavkm** [comment]
@BladeWise tracking your issue here - https://github.com/aspnet/Mvc/issues/7451

**Comment by mkArtakMSFT** [comment]
@rynowak, is there any other action we should take here?

**Comment by rynowak** [comment]
We did `ActionResult<T>` to improve this kind of scenario.

We have no plans to introduce something like `HttpResponseException`. This should be closed.
