### ISSUE TITLE
WebApplicationTestFixture Should Find the Project under Test

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#7037]
According to the [announcement](https://github.com/aspnet/Announcements/issues/275) the `WebApplicationTestFixture` traverses the directory tree upwards to find the solution but then assumes the project file is at the same level.

> "It appends `<<AssemblyName>>` to the folder in which it found the .sln file and set that as the content root."

It would not be that much more work to traverse the directory in the reverse direction from the solution directory to look for a directory with the name `<<AssemblyName>>`. I've been using this technique successfully myself for some time and I think that it should be the default behaviour (convention over configuration). If someone has something different they want to do, they can override this behaviour.

As it is, `WebApplicationTestFixture` will definately require me to override it to make it useful. With some sensible defaults, it could be made useful without doing so. 

See also [WebApplicationTestFixture should provide a default WebHostBuilder](https://github.com/aspnet/Mvc/issues/7038)

**Comment by epignosisx** [comment]
I second the suggestion. I’ve been following the same directory structure the ASP.NET Core repos use in my apps:

src/
test/
MySolution.sln

With this layout WebApplicationTestFixture will not be able to find the web project inside the **src** directory. If it is not desired to traverse down, at least consider covering this directory structure.

**Comment by javiercn** [comment]
@Eilon We follow the default pattern that VS and the CLI generate. I originally started with /src/<<AssemblyName>> and we move it to just be /<<AssemblyName>>. I'm not opposed to having /src/... as a fallback but I would balance it to the fact that you just need to override WebApplicationFixture and put your convention. And that will work for all your projects. If you want more control there are WebHostBuilder extensions that can be used directly instead of WebApplicationFixture.

I'm against traversing from top to bottom because of the issues @Eilon mentions.

@rynowak Any thoughts?

**Comment by RehanSaeed** [comment]
If you are planning on adding `/src/...`, could you also add `/source/...`. I've never been a fan of acronyms.

**Comment by javiercn** [comment]
_For triage:_ 

This can be easily achieved by extending ```WebApplicationTestFixture``` and calling the constructor below with the path to your assembly. You only need to extend this class once to reflect your convention and can be used in all your tests.
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationTestFixture.cs#L60

```csharp
public class MyConventionFixture<TStartup> : WebApplicationTestFixture<TStartup> where TStartup : class
{
    public MyAppsFixture() : base(Path.Combine("src",typeof(TStartup).Assembly.GetName().Name)){}
}
```

**Comment by mkArtakMSFT** [comment]
Let's add support to look up only the "src" folder, as that's the most common structure people have.

**Comment by javiercn** [comment]
@mkArtakMSFT I actually had a better idea the other day, but want to chat with @rynowak about it.

**Comment by javiercn** [comment]
Done in https://github.com/aspnet/Mvc/commit/908e7a863bdbd6e229594c6637713cb2f2a6f63b
