### ISSUE TITLE
Make `IHttpRequestStreamReaderFactory` public

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7044]
This interface is currently pub-internal. An implementation is necessary when creating `BodyModelBinderProvider` or `BodyModelBinder` instances. This is necessary in user code when creating resource filters that parse the request body. For example, ASP.NET Core WebHooks does this in a few places e.g. https://github.com/aspnet/WebHooks/blob/be8571953a0124c0877f777e8fb5bb17329204ab/src/Microsoft.AspNetCore.WebHooks.Receivers.Stripe/Filters/StripeVerifyNotificationIdFilter.cs.

For reference: https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Core/Internal/IHttpRequestStreamReaderFactory.cs

**Comment by rynowak** [comment]
We should do this in 2.1 - that doesn't immediately help webhooks, but will help it remain stable in the future.

**Comment by dougbu** [comment]
FYI @mkArtakMSFT and @danroth27: I've got time to do this one and have moved it into Preview1.

**Comment by dougbu** [comment]
afc75a8296
