### ISSUE TITLE
Add ViewComponentResult helper methods to Page \ PageModel

### ISSUE THREAD

**Issue by pushqrdx** [aspnet/Mvc#7051]
In the underlying `PageModel` i want to return a ViewComponent from a OnGet request. I am trying return ViewComponent("ComponentName"); but it throws an error `non-invocable member ViewComponent`

**Comment by pranavkm** [comment]
@pushqrdx `PageModel` is missing the `ViewComponent` helper factory methods. You could define a custom base class with these methods (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Controller.cs#L204-L276) or return an instance of `ViewComponentResult` from your handler method.

@rynowak \ @DamianEdwards were the ViewComponent family of helpers also intentionally not ported over or did we just miss porting them?

**Comment by pushqrdx** [comment]
@pranavkm You saved me, is there any reason it isn't there ?

**Comment by pranavkm** [comment]
@pushqrdx returning view components from a handler isn't a pattern we expect users to commonly use in a page-focused workflow. One of my suggestions from the earlier comment or perhaps a couple of extension methods should do the trick in your case.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please handle this?

**Comment by pranavkm** [comment]
@mkArtakMSFT we specifically chose not to port the helper over - see https://github.com/aspnet/Mvc/issues/5846. Is the plan to port them?

**Comment by mkArtakMSFT** [comment]
@pranavkm, yes, let's do it. We've just synced up with @rynowak regarding this too.
