### ISSUE TITLE
Model Validation fails when validating a collection of an abstract base-class

### ISSUE THREAD

**Issue by wertzui** [aspnet/Mvc#7057]
### Model Validation fails when validating a collection of an abstract base-class
I have the following classes:

```
public abstract class ModelBase
{
}
public class Model : ModelBase
{
    [Range(1, int.MaxValue)]
    public int NumberA { get; set; }
}
```

When validating `new ModelBase[] { new Model { Number A = 0 } }` the `ModelState` is still valid.

### Minimal repro steps
I created a simple repro of this bug
1. Clone https://github.com/wertzui/ModelValidationTest
2. Execute the Tests

### Expected result
I expect `TestMultiple` to pass (an error in the ModelState should be generated)

### Actual result
No error in the ModelState is generated

### Further technical details
TestModelMetadataProvider and TestModelValidatorProvider are copied from the main MVC repo.

I already had a look at the MVC source code and it seems as if the `DefaultCollectionValidationStrategy` will use the metadata of the collection type (ModelBase) as the metadata for each entry in the collection.
This leads to the outcome that only properties on the ModelBase class will be validated, but not properties on the Model class.

**Comment by Eilon** [comment]
I believe this is currently by-design. @dougbu / @rynowak - can you confirm? I figured we must have had past discussions on this but I can't find them.

**Comment by dougbu** [comment]
The model binding and validation systems do use *defined* types by default when picking binders and validators to apply. But, it's relatively simple to define an `IModelBinder` / `IModelBinderProvider` pair to handle types chosen at runtime. For example, the binder may add a `ValidationStateEntry` for the runtime type (`Model` in the above case).

That said, I recommend using a single concrete model for a specific action. Add new actions if you need to dynamically receive different information.

**Comment by dougbu** [comment]
WRT previous issues discussing binding or validating abstract types, please see #6765 and #4703. There are likely more&hellip;

**Comment by Eilon** [comment]
Closing because we are not planning to make changes in this area.
