### ISSUE TITLE
TemplateBuilder does not correctly overwrite the value in the user supplied format

### ISSUE THREAD

**Issue by jbagga** [aspnet/Mvc#7059]
The `TemplateBuilder` conditions for formatting the value were not in the right order and the supplied format (as `EditFormatString` and `DisplayFormatString`) were formatting a value already formatted in the `ModelMetadata.IsEnum` block https://github.com/aspnet/Mvc/commit/5fffd464cd874891a31a8cf14258aaecc099f932#diff-ba280b63c56b14f4e63ae0bc9f11f7eaL104 and https://github.com/aspnet/Mvc/commit/5fffd464cd874891a31a8cf14258aaecc099f932#diff-ba280b63c56b14f4e63ae0bc9f11f7eaL130

This was fixed as part of #7045 
See commit 5fffd46 

cc @dougbu

**Comment by dougbu** [comment]
Impact of this bug was `enum` specifiers in the user's format string would not work properly, likely causing runtime failures. `[DisplayFormat(DataFormatString = "{0:X}")]` on an `enum` property would not format it in hex in the generated HTML.
