### ISSUE TITLE
与System.Net.Http.dll 这个版本4.6.25220.1及 以上版本不兼容

### ISSUE THREAD

**Issue by ghd258** [aspnet/Mvc#7060]
与System.Net.Http.dll 这个版本4.6.25220.1及 以上版本不兼容，如果不引用会自动增加 System.Net.Http.dll 4.6.25514.4这个版本，但是在NuGet就没有4.6.25514.4这个版本号；引用了System.Net.Http.dll 这个版本4.6.25220.1及 以上版本会把项目的引用Dll变为感叹号

**Comment by Eilon** [comment]
Dup
