### ISSUE TITLE
PasswordValidator Null Argument Exception Bug

### ISSUE THREAD

**Issue by tianvan** [aspnet/Mvc#7062]
Even though I set the passwordRequireLength at ConfigurationService, when I call the PasswordValidator in the controller, null argument exception will throw if the password is empty.
```c#
private UserManager<AppUser> _userManager;
        private IUserValidator<AppUser> _userValidator;
        private IPasswordValidator<AppUser> _passwordValidator;
        private IPasswordHasher<AppUser> _passwordHasher;

        public AdminController(UserManager<AppUser> userManager, IUserValidator<AppUser> userValidator, IPasswordValidator<AppUser> passwordValidator, IPasswordHasher<AppUser> passwordHasher)
        {
            _userManager = userManager;
            _userValidator = userValidator;
            _passwordValidator = passwordValidator;
            _passwordHasher = passwordHasher;
        }
```

```c#
IdentityResult validPassword = await _passwordValidator.ValidateAsync(_userManager, user, password);
                if (!validPassword.Succeeded)
                {
                    AddErrorsFromResult(validPassword);
                }
                else
                {
                    user.PasswordHash = _passwordHasher.HashPassword(user, password);
                }
```

ArgumentNullException: Value cannot be null.
Parameter name: password
Microsoft.AspNetCore.Identity.PasswordValidator.ValidateAsync(UserManager<TUser> manager, TUser user, string password)

**Comment by Eilon** [comment]
In the controller action did you first check for `ModelState.IsValid`? If not, then it is probably not safe to call into Identity to do the password checks because the data entry was already invalid.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
