### ISSUE TITLE
ModelState.IsValid returning true when email is not valid

### ISSUE THREAD

**Issue by AdnanCukur** [aspnet/Mvc#7063]
```
        [Required]
        [EmailAddress]
        public string Email { get; set; }
```

When I post the email "aoao@aooa" ModelState.IsValid returns true
All the other attributes in my object are validating fine.

**Comment by ctolkien** [comment]
The validation for email address validation is naive and only designed to catch the most egregious errors:

https://github.com/dotnet/corefx/blob/8b04d0a18a49448ff7c8ee63239cd6d2a2be7e14/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs#L19

**Comment by Eilon** [comment]
Correct, this is currently by design. There was little value in doing the full RFC check for valid emails because it was a huge level of complexity that didn't add much value.
