### ISSUE TITLE
Razor Pages: Route parameter "asp-route-action"

### ISSUE THREAD

**Issue by biqas** [aspnet/Mvc#7065]
Not sure if it is intended or a bug.

If you have a form inside a razor page and you create a button inside the form which has the following asp route parameters "asp-route-action" then the page is going to the first default MapRoute definition and not to the post method defined in the Razor Page. (I guess to reproduce this, you need at least more then one routes defined in the startup)

```html
<form method="post">
    <button asp-route-action="some value"></button>
</form>
```

> asp-route-**action** is causing the problem.

**ASP Core 2.0**

**Comment by lugrugzo** [comment]
You should use `asp-page-handler="edit"` property in button. So it will call this post method defined by you:

```cs
public async Task<IActionResult> OnPostRejectAsync(int id)
{
    //stuff
            
    return RedirectToPage();
}
```

**Comment by biqas** [comment]
@lugrugzo I know how to use the handlers, the problem here was, if you use the specific route parameter name "action" ("asp-route-action") then ASP Core is going to do something else as you would expect.
