### ISSUE TITLE
Non locale safe RFC 3339 time strings cause browsers to reject (date)time values

### ISSUE THREAD

**Issue by avertes** [aspnet/Mvc#7067]
I believe this is a severe issue, as it causes browsers to reject datetime and time values when pages are served with affected locales.

InputTagHelper has definitions of RFC 3399 date and time formats, which use ":" as time separator. Unfortunately ":" is also .Net time separator, which gets different values depending on locale.

For example in it-IT locale, datetime-local was formatted as "2017-11-19T22.52.29.223" instead of correct format "2017-11-19T22:52:29.223". 

This can be easily corrected by replacing time separator ":" with "\\:" which results in fixed ":" without substitutions. I have provided fix with pull request #7066

**Comment by Eilon** [comment]
@jbagga / @dougbu - can you take a look at https://github.com/aspnet/Mvc/pull/7066 and merge? This does sound broken.

**Comment by dougbu** [comment]
Yes this is a bug. Good catch @avertes.

**Comment by dougbu** [comment]
ee5535203e
Thanks again @avertes.
