### ISSUE TITLE
Core 2 MVC (WCF to SSRS Execution) project Needs Administrator IIS AppPool to Work?

### ISSUE THREAD

**Issue by cgountanis** [aspnet/Mvc#7072]
Can anyone shed some light on a solution for this? The last thing I feel comfortable doing is giving an IIS application pool identity too much power.

Works fine within IIS Express (Visual Studio), once hosted under IIS you need to give it major user rights to work. I tried giving it elevated appPool virtual user rights on the web folder. I tried playing with the IIS authentication settings, seems to ignore all of that.

I have tied a million different settings and all the old solutions for .NET are not helpful in this case.

I am at a loss on this one and it is very frustrating any help would be great.

```
// Init the basic http binding.
var basicHttpBinding = new BasicHttpBinding()
{
	MaxReceivedMessageSize = int.MaxValue,
	MaxBufferSize = int.MaxValue,
	ReaderQuotas = XmlDictionaryReaderQuotas.Max
};

// Set the binding security mode based on the url scheme.
if (new Uri(model.ReportServerUrl).Scheme.ToUpper() == "HTTPS")
{
	basicHttpBinding.Security.Mode = BasicHttpSecurityMode.Transport;
}
else
{
	basicHttpBinding.Security.Mode = BasicHttpSecurityMode.TransportCredentialOnly;
}

// Binding client security transport settings.
basicHttpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;

// Create the report execution service soap client.
var serviceSoapClient = new ReportExecutionServiceSoapClient(basicHttpBinding, new EndpointAddress($"{model.ReportServerUrl}/ReportExecution2005.asmx"));

// Credentials.
serviceSoapClient.ClientCredentials.Windows.AllowedImpersonationLevel = System.Security.Principal.TokenImpersonationLevel.Impersonation;
serviceSoapClient.ClientCredentials.Windows.ClientCredential = new NetworkCredential(model.Username, model.Password, model.Domain);

// Init the trusted user header.
var trustedUserHeader = new TrustedUserHeader();

// Load report and get response.
var loadReportResponse = serviceSoapClient.LoadReportAsync(trustedUserHeader, model.ReportPath, null).Result;

// Create execution header using load report response information.
var executionHeader = new ExecutionHeader
{
	ExecutionID = loadReportResponse.executionInfo.ExecutionID
};

// Parameters.
var reportParameters = model.Parameters.ToArray();
var setExecutionParametersResponse = serviceSoapClient.SetExecutionParametersAsync(executionHeader, trustedUserHeader, reportParameters, "en-us").Result;

// Render request.
var renderRequest = new RenderRequest(executionHeader, trustedUserHeader, model.ReportFormat, null);

// Render response.
var renderResponse = serviceSoapClient.RenderAsync(renderRequest).Result;
```

**Comment by Eilon** [comment]
@Tratcher any ideas on this?

@cgountanis the code you show doesn't seem related to ASP.NET Core or MVC. What's the connection between the code in the issue and the problem you are running into?

**Comment by cgountanis** [comment]
Once you publish it you need an extreme amount of permissions to make it work. I'm not sure where to put this but the final product has to be usable otherwise what's the point?

**Comment by cgountanis** [comment]
Simply put this is a Core2 MVC app consuming a Core2 class Library, code above, and the final product is a published set of files that should work within IIS without having to run the apppool as administrator.

**Comment by Tratcher** [comment]
They've filed variants of the same issue in 5+ repos now. The normal app pool identity has very minimal local account permissions, and no domain permissions.

Which administrator account did you use? The machine or domain administrator?

And are the credentials you pass in here: `new NetworkCredential(model.Username, model.Password, model.Domain);` domain credentials?

**Comment by cgountanis** [comment]
No the machines are separate and they're not on a domain so basically I'm sending a username password and blank domain to the SSRS server. It's always worked in the past with. Net 4.5 and it works in this application in Visual Studio debug but as soon as you host in IIS you need massive permissions on the apppool to get it to communicate with the remote server. So to clarify the user and password that's being sent is not part of any domain or even a user that's on the web server basically just basic plain text  user Authentication. The username and password that's being sent is however a Windows user on the SSRS server. Pretty basic stuff and it's always worked in the past especially when Microsoft supported the report viewer has a NUGET package. But let's not go down that road...

**Comment by cgountanis** [comment]
Also it works locally in Visual Studio with basic and windows security type. Works perfectly using either one and I am connecting to the SSRS server remotely even through a VPN and I've had no issues.

**Comment by Tratcher** [comment]
Does your Net 4.5 IIS application have authentication enabled for incoming requests?

One of the larger differences for ASP.NET Core in IIS is that it does not impersonate the authenticated user. All actions are performed by the app pool identity unless you do explicit impersonation. It's possible the operations WCF is trying to perform don't work with the app pool identity but would work with the authenticated user.

There's a long writeup about impersonation here: https://github.com/dotnet/corefx/issues/9996#issuecomment-308538004

**Comment by cgountanis** [comment]
I'll check out the right up in detail appreciate the help. It's really strange that it works in Visual Studio on a machine that has nothing in common with the remote machine user wise which means the impersonation and the credentials are working fine in Visual Studio but once hosted in IIS I feel it needs access to some Library that I'm not sure about yet that's my best guess maybe something in the core runtime.

**Comment by Tratcher** [comment]
I expect VS works because IIS Express runs with your identity, not with the restricted IIS app pool identity.

**Comment by cgountanis** [comment]
Yeah that makes sense but what file is it accessing or not able to access under IIS, maybe in general it's just having an issue with the communication foundation or the usage of being that it's a restricted user. I have to read that write up to see if it mentioned something about this.

**Comment by cgountanis** [comment]
I honestly don't think it has anything to do with impersonation because it's not on a domain and the user does not even exist on the local machine so it has to be about some kind of communication or some library that it does not have access to maybe an inner workings of of the operating system that it doesn't have access to. I honestly have no clue I've been struggling with this for about a week. And there's no way we can run the apppool as administrator 🤓

**Comment by Tratcher** [comment]
There's not much else anyone else can do to help you without an end-to-end repro setup. If that's something you can assemble and publish to a github repo then we can get somebody to take a look (WCF?). Otherwise I suggest contacting MS support so they can help debug it in your own environment.

**Comment by cgountanis** [comment]
I understand that. I don't really accept that though. I think anyone that's building a soap endpoint connection application is going to run into this problem. Stops on the internet it's not always going to be on the domain and have matching users or be run as an Azure web service. I'd like to try hosting this in Kestral or maybe Linux and see if I run into the same problem.

**Comment by cgountanis** [comment]
Not sure this is an MVC issue just trying to find some help, someone's had to run into the apppool issue or maybe they know a way to figure out what folders to give access to etc...
