### ISSUE TITLE
How pass the TempData in ExceptionFilterAttribute

### ISSUE THREAD

**Issue by Jenan** [aspnet/Mvc#7074]
Hello,

I have tried to create the `Exception filter` for my controller like this:

```
public class ControllerExceptionFilterAttribute : ExceptionFilterAttribute
    {
        private readonly IHostingEnvironment _hostingEnvironment;

        public ControllerExceptionFilterAttribute(
            IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }

        public override void OnException(ExceptionContext context)
        {

            //How construct a temp data here which I want to pass to error page?
            var result = new ViewResult
            {
                ViewName = "Error"
            };

            context.ExceptionHandled = true; // mark exception as handled
            context.Result = result;
        }
    }
```

I need in `OnException `method work with `TempData `- how can I set some exception information to `TempData `in this place? I have used this TempData to some notification.

There is missing something like this: `context.Controller.TempData["notification"]` - Controller property was probable removed. :)

Thank you.

**Comment by Eilon** [comment]
Hi @Jenan , from the `ExceptionContext` you can get the `HttpContext`, and then from the `HttpContext` you can get the Temp Data the same way that the `Controller` class itself gets it:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Controller.cs#L65-L66
