### ISSUE TITLE
Make ObjectResult inherit from StatusCodeResult

### ISSUE THREAD

**Issue by simondel** [aspnet/Mvc#7078]
The current [Microsoft.AspNetCore.Mvc.ObjectResult](https://docs.microsoft.com/nl-nl/dotnet/api/microsoft.aspnetcore.mvc.objectresult?view=aspnetcore-2.0) does not inherit from [Microsoft.AspNetCore.Mvc.StatusCodeResult](https://docs.microsoft.com/nl-nl/dotnet/api/microsoft.aspnetcore.mvc.statuscoderesult?view=aspnetcore-2.0). Adding this would offer a nice abstraction, as there would be a single class derived from ActionResult with a StatusCode property.

**Comment by Eilon** [comment]
Unfortunately that would be a breaking change.

* StatusCodeResult.StatusCode is a required `int` property: https://github.com/aspnet/Mvc/blob/008a562bf5b1ab89e4b83c60faaabd1d12ffcb82/src/Microsoft.AspNetCore.Mvc.Core/StatusCodeResult.cs#L30
* ObjectResult.StatusCode is a nullable `int?` property: https://github.com/aspnet/Mvc/blob/008a562bf5b1ab89e4b83c60faaabd1d12ffcb82/src/Microsoft.AspNetCore.Mvc.Core/ObjectResult.cs#L33

(It can be done without a breaking change, but it would be very cumbersome with two properties named `StatusCode`.)

**Comment by Mardoxx** [comment]
😢

**Comment by Mardoxx** [comment]
This is dumb, why not just do it? https://github.com/aspnet/Announcements/issues?q=is%3Aissue+is%3Aopen+label%3A%22Breaking+change%22

**Comment by Eilon** [comment]
Hi @Mardoxx , we're working on a "minor release", which is 2.1, which has a very high bar for making breaking changes. In general we make breaking changes only in major releases, which will be 3.0. Also, the benefit has to outweigh the cost. In this case the benefit is quite small, and the cost of a breaking change is considered very high.

**Comment by Mardoxx** [comment]
@Eilon will this make [3.0](https://github.com/aspnet/Mvc/labels/breaking-change)? 😋
