### ISSUE TITLE
Render ViewComponent as string from controller

### ISSUE THREAD

**Issue by ekarimi** [aspnet/Mvc#7079]
Hi,
Rendering viewcomponent as string can be pretty handy in some situations.
I searched but couldn't find anything or there were really complex ( not for the lack of trying, just wanna know if there is a simpler solution ).

Can anyone point me to the right direction?
for example :
`
string html= ViewComponent(typeof(SomeViewComponent)).RenderAsString()
`
or anything gets me that.

**Comment by Eilon** [comment]
Hi @ekarimi , this type of question is likely better suited to a site such as https://stackoverflow.com/questions/tagged/asp.net-core-mvc, using the `asp.net-core-mvc` tag.
