### ISSUE TITLE
DisplayAttribute.Name don't support Scaffolding Template

### ISSUE THREAD

**Issue by JamesYing** [aspnet/Mvc#7082]
hi man, i created a model and areas.
model:
```
public class TestModel{
    [Display(Name="SiteName")]
    public string SiteName{get;set;}
}
```

And I generator a view page use Scaffolding 'Create' template into Areas/Views/Test

If correctly, it show the 'SiteName' for 'SiteName' property, but now, it's show empty,like this:
```
<label asp-for="SiteName"></label> 
<input class="form-control" asp-for="SiteName">
<span class="text-danger" asp-validation-for="SiteName"></span>
```
If i generator it to /Views/Test, it's correctly.

Kindly check it ,Thanks

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#657
