### ISSUE TITLE
TOTP asp.net Identity ManageController.EnableAuthenticator  AddModelError 

### ISSUE THREAD

**Issue by arlenniu** [aspnet/Mvc#7084]
public async Task<IActionResult> EnableAuthenticator(EnableAuthenticatorViewModel model)

error------
 if (!is2faTokenValid)
            {
                ModelState.AddModelError("**model.Code**", "Verification code is invalid.");
                return View(model);
            }

ok----
 if (!is2faTokenValid)
            {
                ModelState.AddModelError("**Code**", "Verification code is invalid.");
                return View(model);
            }

**Comment by Eilon** [comment]
@blowdart any ideas on this? Is it a bug in the template?

**Comment by blowdart** [comment]
Uh, @danroth27 ?

**Comment by danroth27** [comment]
This issue was moved to aspnet/templating#166
