### ISSUE TITLE
EntityFrameworkCore.Tools and CodeGeneration.Design added into project

### ISSUE THREAD

**Issue by ole1986** [aspnet/Mvc#7088]
After I have updated to Visual Studio version 15.4.5 I noticed two new PackageReferences are added to my Microsoft.NET.Sdk.Web project (ASP .NET Core MVC)

```
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" />
```

Also when I now want to publish to its remote using Web Deploy several files are added to the destination.

![image](https://user-images.githubusercontent.com/4850116/33322907-1b992716-d44b-11e7-8120-ebfc9b9ecdd0.png)

I am actually scared only about the second *.exe file being available on a production server.
Can i safely remove these two Package references as built is successful without them?

**Comment by Eilon** [comment]
It should be perfectly safe to have them published to the server.

However, how exactly did they get added to the project to begin with? Just updating the version of VS shouldn't cause that to happen.

**Comment by Eilon** [comment]
@bricelam / @natemcmaster any idea how these might have shown up?

**Comment by natemcmaster** [comment]
I believe VS adds these when you attempt to scaffold code for the first time in a project. cc @prafullbhosale

@ole1986 you can trim these from publish output by adding "PrivateAssets="all" to the package reference.
```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" PrivateAssets="All" />
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" PrivateAssets="All" />
```

**Comment by ole1986** [comment]
I noticed that I already have the PrivateAssets=All for the EntityFrameworkCore.Design assembly which I wondered was also published in the remote through Web Deploy - but that may some "obsolete"  issue.

Anyway,
I actually noted these two files being added only because git shows the project file as modified. I actually did not changed anything special...

@natemcmaster can you describe what exactly means scaffold in this case?

**Comment by natemcmaster** [comment]
By scaffold, I meant Add -> New Scaffolded Item... This will automatically add some project references to your project.
![image](https://user-images.githubusercontent.com/2696087/33345406-22390172-d441-11e7-8e89-587623765f6e.png)

**Comment by ole1986** [comment]
This can possibly be the reason. I might have clicked this by mistake.

Trying to reproduce it and will close the issue once confirmed.

Thank you

**Comment by ole1986** [comment]
I could reproduce it by adding a scaffolded item.. So I must have mistakenly added that...
Issue can be closed - Thank you
