### ISSUE TITLE
Allow registration of ModelMetadataDetailsProviders via DI

### ISSUE THREAD

**Issue by gabrielsadaka** [aspnet/Mvc#7090]
With the introduction of the `FromBody` attribute to ASP.NET MVC in the core framework a lot of actions in my project will require modification and in an attempt to avoid those changes I am trying to create a `IBindingMetadataProvider` that will automatically set the `BindingMetadata.BindingSource` to `BindingSource.Body` for AJAX JSON Posts.

This requires access to the `HttpRequest` and since it is not available in `BindingMetadataProviderContext` I need to retrieve it via DI which requires a global static container because I can't use constructor injection for `IBindingMetadataProvider` implementations since `MvcOptions.ModelMetadataDetailsProviders` is a list of already instantiated objects not types that will later be retrieved via DI. 

Please see the code that I am currently using below;

``` 
public class AjaxBindingMetadataProvider : IBindingMetadataProvider
{
    public void CreateBindingMetadata(BindingMetadataProviderContext context)
    {
        var httpContext = GlobalStaticContainer.GetInstance<HttpContext>();
        if (httpContext.Request.IsAjaxJsonRequest() && httpContext.Request.Method == HttpMethods.Post)
        {
            context.BindingMetadata.BindingSource = BindingSource.Body;
        }
    }
}
```

Although it works having to use a global static container is not ideal and I would prefer to be able to register them similar to filters like this `options.ModelMetadataDetailsProviders.Add<AjaxBindingMetadataProvider>();`.

I am happy to submit a PR to add this feature, I would like some feedback on the idea first though.

**Comment by dougbu** [comment]
@gabrielsadaka `IMetadataDetailsProvider`s including `IBindingMetadataProvider` help to initialize `ModelMetadata` instances that are used for the lifetime of an application. If the same action is used for Ajax and non-Ajax requests, changing the metadata based on first request using that action may do exactly the wrong thing for the second request.

I suggest adding another action as well as a constraint to choose between the two actions based on your criteria. If that doesn't work for your scenario, one fallback would be to implement an `IModelBinder` that handles binding one or more types differently when it's an Ajax request.

**Comment by gabrielsadaka** [comment]
@dougbu In our scenario we can guarantee that all of the requests to a particular action are made with a single request type as we have strict validation on all of our actions.

The reasoning behind not allowing the registration of the `IMetadataDetailsProvider`s via DI does make sense though. 

I will see if I can achieve the same result with an `IModelBinder`. 

Thanks for the advice @dougbu.
