### ISSUE TITLE
Suggestion: A UseJsonExceptionPage extension method.

### ISSUE THREAD

**Issue by PureKrome** [aspnet/Mvc#7094]
A common scenario of ASP.NET MVC is to have a 'restful' WebApi 'back end' server accepting requests and returning results in json or xml (generally). Typical scenario's for a SPA webapp or an API for others to consume.

As part of this scenario/setup, errors could occur. From `500 Internal Error` to others like a `400 Bad Request` (the consumer of this MVC WebApi hasn't provided legit data in the request payload).

If the MVC WebApi is returning JSON for all requests (lets not talk about `conneg` just yet ...) but a 400+ "error" occurs, then I would like to think that these errors _also_ should be in a JSON format also.

Right now, I believe the solution the developer needs to do is:

1. Add `UseExceptionHandler(..)` to their `applicationBuilder`.
2. Create and wire up their own `RequestDelegate` method that actually deals with the exception, packages it up into some custom error view model, the write this to the the response.
3. If there's CORS, then also make sure these are added back to the response header. Otherwise, the browser (if SPA) won't be able to 'read' this error payload response.

Here's an example:

```
app.UseExceptionHandler(options => 
    options.Run(async httpContext => await ExceptionResponseAsync(httpContext, corsPolicyName)));

...

private static async Task ExceptionResponseAsync(HttpContext httpContext,
                                                    string corsPolicyName)
{
    if (!string.IsNullOrWhiteSpace(corsPolicyName))
    {
        await ReApplyCorsPolicyToHeaderAsync(httpContext, corsPolicyName).ConfigureAwait(false);
    }

    var exceptionFeature = httpContext.Features.Get<IExceptionHandlerPathFeature>() ?? new ExceptionHandlerFeature
    {
        Error = new Exception("An unhandled and unexpected error has occured. Ro-roh :~(.")
    };

    await ConvertExceptionToJsonResponseAsync(exceptionFeature,
                                                httpContext.Response);
}

private static Task ConvertExceptionToJsonResponseAsync(IExceptionHandlerPathFeature exceptionFeature,
                                                        HttpResponse response)
{
    // Custom code here.
    var apiErrors = new List<ApiErrors>(); // A list of all the errors which have occured.
 
   // Check what type of Exception this is. It could be some custom one ... or just a normal
   // BCL exception (Exception, ArgumentNullException, etc..)

    // Project the exception data into our custom list of apiErrors.

    // Write the error data to the response.
    var json = JsonConvert.SerializeObject(apiErrors, JsonHelpers.JsonSerializerSettings);
    response.StatusCode = (int) statusCode; // Could be 400, 500, etc. Based on Exception type.
    response.ContentType = "application/json";
    return response.WriteAsync(json);
}
```

You get the idea. 

So given an exception, we need to (somehow) send back some json exception data so our consumers (SPA's, other back end servers, etc) can gracefully expect -and- handle errors/non-happy-path scenario's.

There's a fair bit of boilerplate code that occurs (and also omitted) in the same code above.

There is a point where some _custom code_ could occur. For example, this bit:

> // Check what type of Exception this is. 

and

> // Project the exception data into our custom list of apiErrors.

so this is a great way to allow the developers to customize the `ApiError`'s collection or whatever 'error view model' they end up converting to JSON and then sending down the response.

So basically, would be really nice if there's a way we (developers) can send back any errors as json and have the ability to plug in our own `Func<object, IExceptionHandlerPathFeature, HttpResponse>` which will allow use to define our own error view model, which is then used by the boiler-plate code to be written out to the response.

Now - conneg. Um .. I don't know how this works now :( I know what conneg is .. but I'm not sure if a consumer asks for all responses to be xml ... so then serialization AND `response.ContentType` would reflect that the conneg-request.

Anyways - hoping to start a discussion about this.

Final note: I do understand that the [DeveloperPageExceptionExtension](https://github.com/aspnet/Diagnostics/tree/dev/src/Microsoft.AspNetCore.Diagnostics/DeveloperExceptionPage) is actually part of the [ASP.NET/Diagnostics](https://github.com/aspnet/Diagnostics) repo, so I'm not sure if this is the correct repo to ask this question.

Thank you kindly team for reading this - keep up the awesome work!

----
Here's some unicorn tax as a reward for reading through this suggestion and to help make you smile and think "yeah - this idea has a tiny bit of merit .. lets discuss this further!" :

![](https://media.giphy.com/media/l0HlN5Y28D9MzzcRy/giphy.gif)

**Comment by pranavkm** [comment]
@PureKrome we're working on a couple of enhancements in HTTP API targeted scenarios for 2.1.0. One of these was to have leverage [ProblemDetails](https://tools.ietf.org/html/rfc7807) as the default format for describing error responses. https://github.com/aspnet/Mvc/issues/6786 is the tracking item although it's a bit sparse on details.

**Comment by PureKrome** [comment]
Oh wow - this is great news! I'll close this issue and subscribe to #6786 . Here's hoping it makes it into release 2.1.0 🤞 

Thanks again @pranavkm for the reply - much appreciated!
