### ISSUE TITLE
Support BadRequest on PageModel

### ISSUE THREAD

**Issue by jbagga** [aspnet/Mvc#7095]
According to [this](https://github.com/aspnet/Mvc/issues/5846) issue `BadRequest` should not be needed in `PageModel`.

But in this PR https://github.com/aspnet/templating/pull/168#discussion_r154213722 we think replacing an `ApplicationException` with `BadRequest` on the `PageModel` makes sense.

cc @Eilon

**Comment by Eilon** [comment]
@rynowak @DamianEdwards - any objections?

We're proceeding with this anyway because it seems like a good addition, but if you have major objections... we can arm wrestle for it.
