### ISSUE TITLE
DeveloperExceptionPage not working when TempData is combined with sessions

### ISSUE THREAD

**Issue by pconfig** [aspnet/Mvc#7103]
When i have a controller which has a property marked "TempData" and i throw an exception in one the actions, the DeveloperExceptionPage is not showing up. I just receive a default HTTP 500 response.

This only happens when I have "services.AddMvc().AddSessionStateTempDataProvider();" in my ConfigureServices method. When i replace it with "services.AddMvc();", the problem is gone.

Please note that sessions are configured properly and the TempData is actually working. It's just the exception page that is not showing anymore. When there is no property which is marked as TempData, the exception page also shows up as expected.

I'm on AspNetCore v2.0.3 with Visual Studio 2017

**Comment by Svek** [comment]
Maybe it's the order of your services? There is an important note about the ordering on the Microsoft Docs.
I would suspect that `AddMvc()` has to go last.

did you try this?
```
services.AddSessionStateTempDataProvider();
services.AddMvc();
```

**Comment by pconfig** [comment]
That doesn't work as AddSessionStateTempDataProvider() only works on IMvcBuilder

I've actually got the ordering from the docs here:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?tabs=aspnetcore2x#tempdata

**Comment by Svek** [comment]
Oh... I think my earlier statement was all wrong anyway. If I recall correctly, the ordering is for the request/response pipeline which is under the `Configure()` method.

Whereas (for example) the `app.UseDeveloperExceptionPage();` must come before `app.UseMvc();`

**Comment by pranavkm** [comment]
This is likely a dup of https://github.com/aspnet/Mvc/issues/6598. @kichalla is there a workaround they could use for this until a fix is released?

**Comment by kichalla** [comment]
One workaround (as mentioned in #6598) is to register Session middleware before DeveloperExceptionPage middleware. The affect of this is that as any exceptions that happen in Session middleware are not caught in DeveloperExceptionPage. But since DeveloperExceptionPage is used during development scenarios, probably this side effect is minimized.

**Comment by mkArtakMSFT** [comment]
Closing as a dupe.
