### ISSUE TITLE
How to receive InputStream in AspNetCore

### ISSUE THREAD

**Issue by shaddockblack** [aspnet/Mvc#7104]
How to receive InputStream in AspNetCore
HttpRequest  use  text/xml or application/xml
it will return 415 unsupported media type

**Comment by mkArtakMSFT** [comment]
The documentation here shows how to access InputStream:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.request?view=aspnetcore-2.0#Microsoft_AspNetCore_Http_HttpContext_Request 

Also, this one will help you with XmlFormatters configuration:
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding#binding-formatted-data-from-the-request-body
