### ISSUE TITLE
Razor Page Testing with IUrlHelper

### ISSUE THREAD

**Issue by scottsauber** [aspnet/Mvc#7106]
Could be something dumb I'm doing or something I'm missing, but wasn't sure if it was related to some of the Testing improvements on Razor Pages like on #6943.

I'm trying to create an absolute URL in my Razor Page page handler and pass that upstream to my "backend" (handler using MediatR, not that it really matters) so my backend doesn't know it's talking to ASP.NET Core or not.  It just needs a URL that ultimately gets e-mailed out to the user.

When I try to use `UrlHelper.Page("PageName")` I get a Null Ref Exception on something inside the stack at `(IUrlHelper urlHelper, String pageName, String pageHandler, Object values, String protocol, String host, String fragment)` that I can't see without debugging through.  Something in `UrlHelperExtensions` is dying before it delegates to `RouteUrl`.

And yes, my UrlHelper isn't null, I'm passing in a [Fake one](https://gist.github.com/scottsauber/fe204c7f83c43436a826d4884de10e27).  I've tried other approaches to no avail.  Pretty close to just wrapping IUrlHelper behind something else, but I'd rather not do that if I can help it.

Any pointers on how not to cause a null ref here?

**Comment by mkArtakMSFT** [comment]
@scottsauber, can you please share a sample project we could use to repro the issue?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
