### ISSUE TITLE
Partial view Menu - Send info to view

### ISSUE THREAD

**Issue by JesperPetersenDk** [aspnet/Mvc#7108]
I make this from _Layout.cshtml

in the Menu.cshtml:

```
@page
@model NewWebsite_SITE_2018.Pages.View.ViewBar_Info.MenuModel

@foreach (var item in Model.GetListMenu)
{
    <a>@item.Name</a>
}
```

Error  its:
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'NewWebsite_SITE_2018.Pages.IndexModel', but this ViewDataDictionary instance requires a model item of type 'NewWebsite_SITE_2018.Pages.View.ViewBar_Info.MenuModel'.

What I'm trying to do is in my layout, so I'll call my menu so come on the single page.

**Comment by pranavkm** [comment]
@JesperPetersenDk to clarify, is this what's happening in your application:

```
// _Layout.cshtml
@model IndexModel

// Menu.cshtml
@model MenuModel
@{ Layout = "_Layout"; }
```

If so, this wouldn't quite work. Mvc requires that _ViewStarts and _Layout rendered as part of a view have the same model. One way to pass the data to your Layout would be use `ViewData`.
