### ISSUE TITLE
Html.DisplayFor does not find the template with @inherits declaration

### ISSUE THREAD

**Issue by nenadvicentic** [aspnet/Mvc#7113]
When display template contains `@inherits` clause in related `_ViewImports.cshtml` file, method `@Html.DisplayFor(...)` cannot find the template.

As soon as `@inherits` clause is removed, display template is found and rendered.

I did not test further, but I would assume that `@Html.DisplayForModel`, `@Html.EditorFor` and `@Html.EditorForModel` behave in a similar manner.

**Comment by mkArtakMSFT** [comment]
@nenadvicentic, can you pleas share a sample project with a repro?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
