### ISSUE TITLE
Update property type check in SaveTempDataPropertyFilterBase to match TempDataSerializer requirements

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7115]
Follow up to #6591 - I was working on a template change where I was passing around a `string[]` via TempData. This works fine because the serializer supports arrays of primitives. However, applying `TempDataAttribute` on a property fails saying the property is not a primitive or string type. We should either update the check in the property to match the serializer or remove it entirely and let the serialized determine if it can correctly round trip a property.

**Comment by pranavkm** [comment]
cc @kichalla

**Comment by mkArtakMSFT** [comment]
Thanks @pranavkm. @kichalla , what about just removing the validation from the property, as @pranavkm suggested?
