### ISSUE TITLE
Consider adding a feature to ActionModel that allows modifying the "effective" filter sequence

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7117]
## Scenario:

My application adds a set of global filters. In one specific action, I'd like to remove one or more of these filters using an action model convention. There isn't any good way to do this since the global list is maintained by the `ApplicationModel` instance that's shared by all controller \ actions. 

One possible way of implementing this might be to expose an `EffectiveFilters` on `ActionModel` that is copy on write collection of global, controller and action filters. We'd use this to calculate the final result in the action descriptor builder.

**Comment by rynowak** [comment]
Maybe there's a straightforward way to do this, but if we do more of this kind of thing, I'd want to start over and redesign application model 😢 

Providing the hierarchy of global->controller->action was a mistake. The underlying data should be represented as a list of actions, and controllers should be a Linq query.

**Comment by mkArtakMSFT** [comment]
Seems like there is no customer request for this.
