### ISSUE TITLE
When razor page and folder have same name, the parameter is null

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#7118]
_From @andrew-vandenbrink on December 8, 2017 7:8_

This is a bit difficult to explain,
Here is the directory structures,

alpha/beta.cshtml
alpha.cshtml

Notice the alpha.cshtml and alpha folder
The content of the functions on alpha.cshtml and beta.cshtml is the same with difference in PageModel's name.

```
public class Parameter{
public string id{get;set;}
}

public IActionResult OnGetReadData([FromQuery] Parameter parameter){
...
}
```

when I call 
GET /alpha/ReadData?id=abc
It works fine as expected
```
public IActionResult OnGetReadData([FromQuery] Parameter parameter){
//parameter.id = "abc" 
}
```

but when I call
GET /alpha/beta/ReadData?id=abc

```
public IActionResult OnGetReadData([FromQuery] Parameter parameter){
//parameter.id is null here
}
```

Is this a bug ?

_Copied from original issue: aspnet/Razor#1807_

**Comment by andrew-vandenbrink** [comment]
Another one

```
public class GetQuery
        {            
            public string query { get; set; }
        }

//GET /zeta?query=abc
public async Task<IActionResult> OnGetAsync([FromQuery] GetQuery query)
 {
//query.query is null here
}

//GET /zeta?query=abc
public async Task<IActionResult> OnGetAsync([FromQuery] GetQuery x)
 {
//x.query ="abc"
}
```

**Comment by rynowak** [comment]
Using the same name for a parameter name and a property name of the corresponding model will cause model binding to behave this way. Model binding is going to look for `parameter.parameter` and `parameter.id` (in your first example)

Its not ideal, but a fix would change the defaults for everyone and would be massively breaking.

If you want a solution, use `[FromQuery(Name="")]` that will force it to do what you expect. We plan to add an analyzer for this in the future.

**Comment by andrew-vandenbrink** [comment]
ok, i can live with x as variable name...
but for the first issue when there is same name of razor page and folder?

**Comment by andrew-vandenbrink** [comment]
@rynowak the first issue is different as the parameter name and property name already different

![image](https://user-images.githubusercontent.com/12871379/34030921-4dc58a28-e16f-11e7-8f35-b63942407557.png)

**Comment by rynowak** [comment]
Ok then someone needs to investigate this then... @Eilon @mkArtakMSFT

**Comment by Eilon** [comment]
@andrew-vandenbrink thanks for the report and the details, we'll get someone to take a look at this.

**Comment by mkArtakMSFT** [comment]
@andrew-vandenbrink, I've just validated the scenario you're describing here, but it worked just fine (see the image below). What version of the framework are you targeting? Can you share the project with a repro? 

![image](https://user-images.githubusercontent.com/34246760/34135813-b283509e-e417-11e7-839b-6792c0331689.png)

**Comment by andrew-vandenbrink** [comment]
@mkArtakMSFT  Looks like the first issue is a false alarm

**Comment by mkArtakMSFT** [comment]
Thanks for confirming, @andrew-vandenbrink.
