### ISSUE TITLE
How to use Request.Url in razor page?

### ISSUE THREAD

**Issue by tronjs** [aspnet/Mvc#7123]
Hi, I am using ASP.net Core web app razor page (not MVC), not sure if I am missing something, but I can not to find any way to use some helpful properties from Request.Url e.g: Request.Url.PathAndQuery, etc...
Thanks

**Comment by rynowak** [comment]
> ASP.net Core web app razor page (not MVC),

Razor Pages is an MVC feature and this is the MVC repo - so I'm going to assume that you mean that you're using a Razor Page and not a Controller 😆 

This works the same as in a View returned from a Controller. The `HttpContext` is available using the `Context` property

```
<p>@Context.Request.....</p>
```

**Comment by tronjs** [comment]
ok thanks for the answer.
