### ISSUE TITLE
RenderViewToString does not work when a RazorPage file is rendered as a view

### ISSUE THREAD

**Issue by lucassklp** [aspnet/Mvc#7126]
Here is my PageModel:
![image](https://user-images.githubusercontent.com/5818762/33959656-5874a094-e02f-11e7-8e36-178c44774a17.png)

```C#    
   public class AccountCreatedSuccessfullyModel : PageModel
    {
        public string Name { get; private set; } = "Teste";
        public string Email { get; private set; } = "Oi";

        public AccountCreatedSuccessfullyModel(string name, string email) : base()
        {

        }

        public void OnGet()
        {
        }
    }
```

So, i try to instantiate it, using 'new' keyword, and it shows that ModelState and RouteData threw exceptions, as image below says:
![image](https://user-images.githubusercontent.com/5818762/33959559-0dd3efcc-e02f-11e7-8b9a-cbf44a6bba29.png)

Then I get in exception page:
![image](https://user-images.githubusercontent.com/5818762/33959602-312fd7c4-e02f-11e7-9262-aa64f6a28c61.png)

The source code can be found at:
https://github.com/lucassklp/DefaultArchitecture

The steps to reproduce is only trying to get the route /api/account.

Someone knows the cause of exception?

**Comment by mkArtakMSFT** [comment]
Hi @lucassklp. Why are you instantiating the Page Model ? What are you trying to accomplish?

**Comment by lucassklp** [comment]
Hi @mkArtakMSFT, I'm trying to make a template mail sender, which will take a Razor template then send it as email. I found a way to get the template's HTML thought a code that needs the Page and PageModel. So, that's why I need to instantiate the PageModel.

**Comment by pranavkm** [comment]
@lucassklp I'm going to have to dig in to why the model in this case in your case, but I wanted to make sure you understand that even though rendering a Razor Page as a regular view *could* render the contents, none of the page execution pipeline would run. This includes, things like property binding \ handler method execution etc.

**Comment by lucassklp** [comment]
I really don't know if using Razor to do this is the best form to resolve this problem, but still better than making the HTML and CSS hardcoded. If you guys has some sugestion to do, feel free to say!

**Comment by pranavkm** [comment]
@lucassklp in a Razor Page, the value of the `Model` property comes from the `PageContext` that does not get initialized as part of `RenderAsync`. You can specifically initialize it's value before rendering it:
Here are the changes you'd have to do:

```C#
if (viewResult.View == null)
{
    throw ...
}

var viewDictionary = new ViewDataDictionary<T>(new EmptyModelMetadataProvider(), new ModelStateDictionary())
{
    Model = model
};

if (viewResult.View is RazorView razorView && razorView.RazorPage is PageBase razorPage)
{
    // For RazorPages, explicitly set the model on the generated type.
    razorPage.PageContext = new PageContext(actionContext)
    {
        ViewData = viewDictionary,
    };
}

...
```

Feel free to re-open the issue if you have any further questions.
