### ISSUE TITLE
RenderPartial does not accept ViewDataDictionary and Model to be passed in

### ISSUE THREAD

**Issue by knightmeister** [aspnet/Mvc#7127]
Hi

See relevant SO question here: https://stackoverflow.com/questions/47781692/viewdatadictionary-model-is-correct-failing-when-calling-renderpartial/47802253#47802253

I am porting from .NET MVC 5 to .NET Core. I noticed there is no overload for `RenderPartial` which accepts a model and `ViewDataDictionary`. I tried setting the model in the `VIewDataDictionary` but found it was being overridden with the parent model.

I took a look at the code and noticed that `RenderPartial` is just wrapping `RenderPartialAsync`. I believe the line 291 (https://github.com/aspnet/Mvc/blob/e6c716444db33f63572ded447a760c7391b4bf79/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Rendering/HtmlHelperPartialExtensions.cs) - should read

``` c#
var result = htmlHelper.RenderPartialAsync(partialViewName, viewData.Model ?? htmlHelper.ViewData.Model, viewData);
```
Instead of what is currently there:

``` c#
var result = htmlHelper.RenderPartialAsync(partialViewName, htmlHelper.ViewData.Model, viewData);
```
I resolved my issue by using the `RenderPartialAsync` method, which allows me to specify both a `ViewDataDictionary` and a Model.

**Comment by mkArtakMSFT** [comment]
Hey @dougbu, at what point this change has been made? Was this change made in .Net Core 1.0 or later timeframe?

**Comment by dougbu** [comment]
@mkArtakMSFT what "change" are you asking about? We're simply missing a `RenderPartial(...)` overload in ASP.NET Core. That is, that overload has never existed in https://github.com/aspnet/Mvc Looks like a straight-up gap.

And, no, `viewData.Model ?? htmlHelper.ViewData.Model` is incorrect and would break back-compatibility with both ASP.NET MVC and earlier ASP.NET Core MVC releases.

Separately, `await RenderPartialAsync(...)` is more than a workaround for the missing overload. The synchronous extensions for `async` helpers ease migrations from ASP.NET MVC 4 or 5 but aren't ideal. Better to use `await` in the generated `async` method than to nest async -> sync -> async transitions.

**Comment by mkArtakMSFT** [comment]
@knightmeister, looks like you've figured out the right way to handle it already, using the `RenderPartialAsync`.

**Comment by dougbu** [comment]
&hellip; that said, we should keep this issue open and add the missing extension method. Agreed @mkArtakMSFT?

**Comment by mkArtakMSFT** [comment]
@dougbu, I'll leave this for you to handle.

**Comment by dougbu** [comment]
1fa1d7df3e

**Comment by dougbu** [comment]
@mkArtakMSFT FYI I've corrected the milestone because this fix is in.
