### ISSUE TITLE
AssociatedModelMetadataProvider can get confused when dealing with properties eclipsed via the "new" operator

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#713]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.ModelBinding/Metadata/AssociatedMetadataProvider.cs#L120

When dealing with a property that is hidden via new, the property info shows up twice, once for the base type and once for the new property. They are looked up by name, and consequently, we could end up setting the property on the base type rather than the new one. 

Super edgy case, but might be worth tracking

**Comment by rynowak** [comment]
Addressed by acb657d9
