### ISSUE TITLE
InvalidDataException: Form key or value length limit 2048 exceeded.

### ISSUE THREAD

**Issue by omnoms** [aspnet/Mvc#7132]
This is despite implementing the attribute that is mentioned in #481 and trying to post a file to the method.

```C#
        [RequestSizeLimit(2147483648)]
        [HttpPost("UploadFiles")]
        public async Task<IActionResult> Post(IFormFile file)
```

What else/wherelse can I configure this to allow larger files?

Steps to reproduce:
- Create a new ASP.NET Core 2 Webapi project (Core 2.0.3 SDK)
- Modify the POST method in the valuescontroller.cs to match the above.
- Use Postman or your favourite tool to create a POST request with a file in it.

![image](https://user-images.githubusercontent.com/7261863/33988484-c486f8c8-e0c4-11e7-83b1-7d2f15735e9a.png)

**Comment by mkArtakMSFT** [comment]
Hi @omnoms. As you can see from the thread you've pointed to, we've added a new RequestFormLimitsAttribute attribute to configure the size limitation. As that's not released yet, you can look into how it used to be done in one of our samples, available [here](https://github.com/aspnet/Entropy/commit/d02700499ccf1a834aa6fab2c42e46d7a0f29063#diff-0e48b37f98ec9efe1cbe5f5259f15e39). You can use the removed attribute code (from the sample) and use it to configure the limit. Hope this helps.

**Comment by omnoms** [comment]
I've now implemented the attribute, but the it doesn't really map the form-data sent to the method.

I.e. I'm sending 2 files in the "files" key as form-data, it hits the method, but the files are not mapped properly to List<IFormFile> files... I get gibberish and a new exception... 

I'll have to do more testing once I have more time.

**Comment by mkArtakMSFT** [comment]
@omnoms, do you have any updates regarding this?

**Comment by mkArtakMSFT** [comment]
@omnoms, please let us know if you are still facing this issue. If so, please also provide a sample project to repro it.

**Comment by omnoms** [comment]
I'm currently on parental leave and not much time to do further testing. So it's fine to close this, however the issue prevails with the standard settings. The workaround will have to do for now.
