### ISSUE TITLE
Model Binding, complex type binder: it is impossible to create  property list at run time. 

### ISSUE THREAD

**Issue by rpokrovskij** [aspnet/Mvc#7133]
Asp Core 2.

Use case: I have a meta model (as a class that at runtime has static instance) where it is described which fields are editable that means should be binded in MVC Controller. So I want to generate property list at run-time. When Asp.Core MVC standard binding model provides me only one possibility: to use `BindAttribute`.

My plan would be inherit from `ComplexTypeModelBinder`, setup it with static (means created at runtime property list) and override CanBindProperty for specific action.

```
public class GroupsController 
    {
        #region Meta
        static ControllerMeta<Group, int?> meta = new ControllerMeta<Group, int?>(/* ... */);

        class CreateFieldsModelBinder : FieldsModelBinder<Group>
        {
            public CreateFieldsModelBinder() : base(meta.CreateActionBindedFields) { }
        }

        class EditFieldsModelBinder : FieldsModelBinder<Group>
        {
            public EditFieldsModelBinder() : base(meta.EditActionBindedFields) { }
        }
        #endregion

        public async Task<IActionResult> Create()
        {
            // ...
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([ModelBinder(typeof(CreateFieldsModelBinder))] Group entity)
        {
            // ...
        }

        public async Task<IActionResult> Edit(int? id)
        {
            // ...
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([ModelBinder(typeof(EditFieldsModelBinder))] Group entity)
        {
            // ...
        }
    }

```

There FieldsModelBinder could be inherited from ComplexTypeModelBinder.

What is worst: there are no easy way to  inherit class from `ComplexTypeModelBinder `since its constructor accepts IModelMetadataProvider which is not easy to construct without PRIVATE DefaultModelBinderProviderContext. May be it is possible to skip DefaultModelBinderProviderContext  , but that means solution will skip binder cache and will be extremely ineffective.

P.S. I even do not understand how to create my own ComplexTypeModelBinder that can be used in place with ModelBinder without inheriting ComplexTypeModelBinder since it is not clear how to accept all registered binders for concrete simple type.

**Comment by frankabbruzzese** [comment]
@rpokrovskij , model binders are created by model binder providers that pass them the right data. On my blog I have a complete series of post on how to build model binders. The one below is about inheriting from the complex model binder: http://www.dotnet-programming.com/post/2017/03/17/Custom-Model-Binding-in-Aspnet-Core-2-Model-Binding-Interfaces.aspx

**Comment by rpokrovskij** [comment]
@frankabbruzzese I have started from your articles. 
But I do not need providers, because in my use case "generate binder from model" I know exactly where to use my custom binder (one light binder per action) - so point it in the attribute is enough. What I need form mvc binding infratructure is to access to simple types "bindings/converters" (string -> datetime) .

Also I can't understand should I use the  EnterNestedScope or not. I'm not understand it role.

Here I just stopped trying to understand how to get the registered simple types "bindings/converters"

```
    public class FieldsModelBinder<T> : IModelBinder
    {
        private readonly Dictionary<string, Action<T,string>> propertyBinders;
        private readonly Func<T> constructor;

        public FieldsModelBinder(Func<T> constructor, Dictionary<string, Action<T, string>> propertyBinders)
        {
            this.constructor = constructor;
            this.propertyBinders = propertyBinders;
        }

        public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            T t = constructor();
            foreach (var pair in propertyBinders)
            {
                var propertyName = pair.Key;
                var valueProvider = bindingContext.ValueProvider;
                var propertyValueProviderResult = valueProvider.GetValue(propertyName);
                if (propertyValueProviderResult == ValueProviderResult.None)
                {
                    bindingContext.Result = ModelBindingResult.Failed();
                    return Task.CompletedTask;
                }
                else
                {
                    var value = propertyValueProviderResult.FirstValue;
                    var action = pair.Value;
                    action(t, value);
                }
            }
            bindingContext.Result = ModelBindingResult.Success(t);
            return Task.CompletedTask;
        }
    }
```

Usage:

```

public class GroupsController : RoutineController
    {
        #region Meta
        static ControllerMeta<Group, int?> meta = new ControllerMeta<Group, int?>( 
              // options how to configure meta 
        );

        class CreateFieldsModelBinder : FieldsModelBinder<Group>
        {
            public CreateFieldsModelBinder(IModelMetadataProvider metadataProvider) : base(
                metadataProvider, meta.Constructor, meta.CreateBindedFields) { }
        }

        class EditFieldsModelBinder : FieldsModelBinder<Group>
        {
            public EditFieldsModelBinder(IModelMetadataProvider metadataProvider) : base(
                metadataProvider, meta.Constructor, meta.EditBindedFields) { }
        }
        #endregion

        CrudRoutineControllerConsumer<Group, int?> consumer;
        public GroupsController(IConfigurationRoot  configurationRoot) :base(configurationRoot)
        {
            consumer = new CrudRoutineControllerConsumer<Group, int?>(this, meta, (action, userContext) => userContext.HasPrivilege(Privilege.ConfigureSystem));
        }

        public async Task<IActionResult> Create()
        {
            // ...
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([ModelBinder(typeof(CreateFieldsModelBinder))] Group entity)
        {
            // ...
        }

        public async Task<IActionResult> Edit(int? id)
        {
            // ...
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([ModelBinder(typeof(EditFieldsModelBinder))] Group entity)
        {
            // ...
        }
    }
```

**Comment by rpokrovskij** [comment]
You wrote "Create a meta data provider"... and register it globally and provide to it global meta model... So the architecture pushes me to register each peace of functionality globally (even if it can be accessed from the BI it is still global and only because it should work with MVC bindings model). 

And it is not easy how you wrote, I spend several days even to understand most of what you are talking and writing, but still do no understand how to get default simple type binders inside the  IModelBinder.BindModelAsync  method (having defaul modelBindingContext and modelMetadataProvider that was get on BI). From code I see that they exists somewhere in DefaultModelBinderProvider cache.   Either I can't evaluate is it compex or not to implement my own IMetadataProvider (there are no samples in the internet, actually even your most comprehensive articles are not going so far).

**Comment by frankabbruzzese** [comment]
In this custom complex model binder I create a nested scope to pass it a custom metadata provider:
https://github.com/MvcControlsToolkit/MvcControlsToolkit.Core/blob/master/src/MvcControlsToolkit.Core/ModelBinding/TransformationModelBinder.cs

Give a look to the code near .EnterNestedScope. You can't call directly another model binder, but you may invoke the whole model binding process on custom data and providers, then the framework creates the right contexts an invoke model binders properly.

Th code of the custom meta data provider is here:
https://github.com/MvcControlsToolkit/MvcControlsToolkit.Core/blob/master/src/MvcControlsToolkit.Core/ModelBinding/DiffMetaData.cs

It extracts all property of a subclass that are not contained in its superclass. You may modify it to fulfill your needs.

**Comment by rpokrovskij** [comment]
@frankabbruzzese thank you, you are great. But I should say it is too much for me. To get this working  developer should become an ASP Model Binding guru (second after you, without a chance to be a first). I do not have such ambitions. Since  my goal is generate controllers from meta I  have a possibility to popup an entity from http request directly in method. It will be 100 times quicker (both developing and performance of the solution).

**Comment by mkArtakMSFT** [comment]
Thank you, @frankabbruzzese for your effort here.
@rpokrovskij, do you have any specific proposal here?

**Comment by rpokrovskij** [comment]
@mkArtakMSFT my proposals are 1) to provide a sample with @frankabbruzzese proposed solution. it is a real case, there is nothing very specific  "to create Binded properties list" run time. But it is too complex to try explain it in words "go and implement your own IMetadataProvider " (where there are no samples of it). 
What about solution specific to me: since I understand that controller generation runtime do not need to use model binding at all and can parse form data directly I went this way; but still would be nice to have possibility 2) to get default primitive type parser (registered in model binding system). I didn't found the easy possibility to get e.g. default datetime binder parser method.

**Comment by mkArtakMSFT** [comment]
@rpokrovskij, unfortunately we have no any plans to make such improvements in this area.
