### ISSUE TITLE
TDD friendliness and IActionResults

### ISSUE THREAD

**Issue by Mardoxx** [aspnet/Mvc#7134]
>ASP.NET Core MVC includes many features that enable fast, TDD-friendly development

TDD is meant to be incremental, and future code changes should not break existing tests -- as far as I understand it?.

If we have a controller method which returns an `IActionResult` via `BadRequest()` we can create a test to take the `IActionResult` check it can cast to `StatusCodeResult` and read status code. That's fine.

However if we then decide to return some message with this e.g. return `BadRequest(ModelState)` which returns `BadRequestObjectResult` we would expect not to have to change any tests here... However this is not the case as there is no shared interface between `BadRequestResult` and `BadRequestObjectResult` to expose the status code.

I suppose my question is... Why does `ObjectResult` not inherit from `StatusCodeResult`, or implement a common interface which exposes the status code of the result?

Hope this makes sense!

**Comment by mkArtakMSFT** [comment]
Hi @Mardoxx. Please have a look at: https://github.com/aspnet/Mvc/issues/7078.
