### ISSUE TITLE
Add format filter mapping for xml formatters

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#7139]
Seems like we [added](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/MvcJsonMvcOptionsSetup.cs#L82) mapping only for json formatter

We should do something similar to xml formatters too
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/Internal/MvcXmlSerializerMvcOptionsSetup.cs#L36
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Xml/Internal/MvcXmlDataContractSerializerMvcOptionsSetup.cs#L38

**Comment by kichalla** [comment]
I realized this could be a breaking change. Example:

If a user has the following code currently (because we didn't add the format mapping earlier) and I checked in my change (where I set the mapping xml => **application/xml**), then they would now see `application/xml` instead of `text/xml` as the mapped content type. 

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc(o =>
    {
        o.FormatterMappings.SetMediaTypeMappingForFormat(
            "xml",
            MediaTypeHeaderValue.Parse("text/xml"));
    })
    .AddXmlDataContractSerializerFormatters() // the options setup of this is run after the above
    .AddXmlSerializerFormatters(); // the options setup of this is run after the above
}
```

**Workaround:** 
It could be fixed if the user did the following if I check-in my change, but I am not sure if we are ok with it now.
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc()
                .AddXmlDataContractSerializerFormatters()
                .AddXmlSerializerFormatters();

    services.Configure<MvcOptions>(o =>
    {
        o.FormatterMappings.SetMediaTypeMappingForFormat(
            "xml",
            MediaTypeHeaderValue.Parse("text/xml"));
    });
}
```
That said, had we not have this bug and had mappings in before, then the user still would have done like the workaround as that is how options work.

cc @rynowak @Eilon

**Comment by Eilon** [comment]
Exactly which mapping(s) would you want to be added by default?

**Comment by kichalla** [comment]
> Exactly which mapping(s) would you want to be added by default?

Just like the JsonOutputFormatter which has 'json' => 'application/json', I was thinking of using 'xml' => 'application/xml'

**Comment by kichalla** [comment]
We could set the mapping conditionally though (we can consider it similar to how we conditionally register our DI services without overriding any user defined ones). I sent out the following PR now: https://github.com/aspnet/Mvc/pull/7217

**Comment by Eilon** [comment]
I'm actually not clear on what these mappings do. Does it map `json` as a MIME type to the `application/json` MIME type? If so, why? (I wouldn't have thought that `json` is ever used as a MIME type.) And if it's not that, then what is it?

**Comment by Eilon** [comment]
Also changing from `task` to `bug` because this affects product code one way or another.

**Comment by kichalla** [comment]
> I'm actually not clear on what these mappings do. Does it map json as a MIME type to the application/json MIME type? If so, why? (I wouldn't have thought that json is ever used as a MIME type.) And if it's not that, then what is it?

It's for scenarios where users cannot add/modify the Accept header. Like one could type in the format in a browser url

**Comment by Eilon** [comment]
Ok, but then why would we support these seemingly non-standard MIME types? I would sooner *delete* the bogus JSON one before adding another bogus XML one, no? (I'm not actually suggesting that, though, because it'd be a breaking change.)

**Comment by Eilon** [comment]
Oh wait, is this for when you do like `example.com/documents/1234abc?format=xml`?

**Comment by kichalla** [comment]
> Oh wait, is this for when you do like example.com/documents/1234abc?format=xml?

Yes, right (also we now support the format in the route: `/1234abc.xml`)

**Comment by rynowak** [comment]
> I'm actually not clear on what these mappings do. 

Yeah this is for cases like `example.com/documents/1234abc?format=xml?`

I'd low key suggest that we remove this feature in a future breaking changes release, or move it to a samples repo. I haven't seen anyone use it, and it's very outmoded at this point.

**Comment by Eilon** [comment]
@rynowak so what do you suggest we do with this issue here? Not do it?

**Comment by rynowak** [comment]
We might as well merge it, it's done :) If someone is happy about this feature I'd be happy to be wrong

**Comment by Eilon** [comment]
Okie.

**Comment by Eilon** [comment]
But it's marked preview2 😮 Whatever.

**Comment by kichalla** [comment]
> But it's marked preview2 😮 Whatever.

Yeah, I missed changing the milestone to Preview1. Fixed it now.

**Comment by kichalla** [comment]
https://github.com/aspnet/Mvc/commit/2aae8774f65cf4c1071fd4c1cb3d60ac573be6a6
