### ISSUE TITLE
Cshtml based helpers in App_Code in Mvc v6

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#714]
The notion of App_Code doesn't exist in the k-project system, but do we continue to support cshtml helpers (shared @helpers) in Mvc 6?

**Comment by andresmoschini** [comment]
+1

Is this issue documented in any place? Do you think that it will be included for official release?

**Comment by DamianEdwards** [comment]
This will not make it for RTM but we will likely revisit it when we start looking at building a new Web Pages replacement.

**Comment by Eilon** [comment]
Closing because we have no plans to support this. We'll look at alternatives such as writing tag helpers using CSHTML.
