### ISSUE TITLE
SerializableError is technically a Dictionary<string, string[]>

### ISSUE THREAD

**Issue by totht91** [aspnet/Mvc#7141]
I've just found out that the `SerializableError` class is derives from `Dictionary<string, object>` but technically used as `Dictionary<string, string[]>` [link](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/SerializableError.cs#L49-L55). 

Could you provide some information why does this class not derive from `Dictionary<string, string[]>`?

Maybe related: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/379

**Comment by rynowak** [comment]
In theory you could use any serializable object as the *values* - using `string[]` is just the common case. As to why it's important?  In theory you could have some structured data as the value, which would serialize like so (contrived example):
```
{
  "key1":
  {
    "errorCode": "....",
    "message": "...",
  },
  "key2":
  {
    "errorCode": "....",
    "message": "...",
  }
}
```

I haven't personally seen any usage of this class with different values, but I'm sure someone out there is doing it. Changing this would be a breaking change that would likely break library authors which means we'd probably never be able to change it - assuming we wanted to.

-----

To that end, we're introducing [`ValidationProblemDetails]`(https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ValidationProblemDetails.cs) in 2.1 and planning to add more support for [RFC 7807](https://tools.ietf.org/html/rfc7807) in places where the framework generates errors.

RFC 7807 unfortunately doesn't say anything about the preferred format for communicating business logic validation errors, but we plan on standardizing on `Dictionary<string, string[]>` as it's what most javascript front end frameworks seem able to accept.

**Comment by totht91** [comment]
Thanks
