### ISSUE TITLE
dynamic routing in Razor Pages

### ISSUE THREAD

**Issue by sreejukg** [aspnet/Mvc#7146]
How can I control the razor pages routing. For e.g.  consider the scenario

In the file system, I have the following files. 
a.cshtml
b.cshtml

now when the user request site/1 to render a.cshtml and site/2 to render b.cshtml. I would like to do this mapping during run time. Please suggest

**Comment by pranavkm** [comment]
@sreejukg you can use `AddPageRoute` on `RazorPagesOptions.Conventions` to do this. For e.g. https://github.com/aspnet/Mvc/blob/47287c508ee43c4f30b8000400fda1b01f68bfe2/test/WebSites/RazorPagesWebSite/Startup.cs#L23.

There's also a work item to support `RouteAttribute` on a page \ page models - https://github.com/aspnet/Mvc/issues/6605

**Comment by sreejukg** [comment]
How can I do routing during runtime, for e.g. 
I have the below pa
/products/electronics/1
/products/electronics/2
I have a database entry for each products and I have a field that indicates whether product video is available for the product. Now based on this field I would like to route the request to 
/TemplateWithVideo
/TemplateWithoutVideo
The routing should happen runtime, the moment the option changed in the database, the request should route to the corresponding template. How can I achieve this.
