### ISSUE TITLE
Ensure RazorPages in an area are not route-able through root based paths when root directory and area root directory overlap

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7147]
See https://github.com/aspnet/Mvc/pull/7135#discussion_r157549019 for further discussion

Consider this scenario:

```
/Areas/First.cshtml
/Areas/MyArea/Pages/Second.cshtml
where RootDirectory = /, AreaRootDirectory = /Areas
```

In this case, we want to ensure that the two routes registered are /Areas/First and /MyArea/Second

**Comment by rynowak** [comment]
We should report `/Areas/First.cshtml` as a warning, and perhaps ignore it. It's in the areas root, which takes precedence, but it can't be assigned an area.
