### ISSUE TITLE
Update compatibility settings

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#7157]
# Summary

With the new compatibility settings infrastructure, we need to update our existing compatibility settings and other behavior changes to make our philosophy for how these should work.

Here's a most-wanted list of our settings and progress:
- [x] `MvcOptions.AllowBindingUndefinedValueToEnumType` 82e3224
- [x] `MvcOptions.InputFormatterExceptionModelStatePolicy` bf61ce2 
- [x] `MvcOptions.SuppressJsonDeserializationExceptionMessagesInModelState` 2e73bab
- [x] `RazorPagesOptions.EnableAreas` 49bdcfb
- [x] `MvcOptions.CombineAuthorizationFilters` d342ebf
- [x] Then re-enable the `CompatibilitySwitchIntegrationTest` tests (in PR)  https://github.com/aspnet/Mvc/pull/7207

## MvcOptions.AllowBindingUndefinedValueToEnumType

This already has the right default. We need to change the value in 2.1 and update the docs for this.

## MvcOptions.InputFormatterExceptionModelStatePolicy

This already has the right default. We need to change the value in 2.1 and update the docs for this.

## MvcOptions.SuppressJsonDeserializationExceptionMessagesInModelState

This already has the wrong default. We need to change the value in 2.0 and update the docs for this.

## MvcOptions.CombineAuthorizationFilters

Once this is merged we need to add the compatibility switch, update docs and then add it to tests

## RazorPagesOptions.EnableAreas

This needs a compatibility switch and related infrastructure. Per naming guidelines this should be renamed to `AllowAreas`. This also needs to be added to tests

**Comment by rynowak** [comment]
@kichalla had a dope idea about whether or not all of these should be enums instead of booleans. Let's plan to discuss this when we're all back in the office after new years.

**Comment by rynowak** [comment]
This is done 👍 😆 👍 :canada:

**Comment by HeMinzhang** [comment]
I finally found the answer, it is great!
