### ISSUE TITLE
How to publish a self-contained project with customized view folder?

### ISSUE THREAD

**Issue by yhvicey** [aspnet/Mvc#7159]
dotnet version: 2.1.2

Here's my project folder structure:

```
(root)
|-- src
|   `-- Views
|       `-- Index.html
```

I configured `ViewLocationFormats` in Startup.cs like this:

```csharp
services.Configure<RazorViewEngineOptions>(options =>
{
    options.ViewLocationFormats.Clear();
    options.ViewLocationFormats.Add("/src/Views/{0}.html");
});
```

When I published and run my project I got an exception when I visit Home/Index:

```
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/src/Views/Index.html
```

Open `<project-name>.PrecompiledViews.dll` in ILSpy, there isn't any class in it.
And if I copied `src/Views` folder to publish folder another exception will occur:

```
System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
```

Even if I set `MvcRazorCompileOnPublish` to false in .csproj file the same exception will still present.
So how to customize self-contained project's view folder and publish it correctly?

**Comment by pranavkm** [comment]
@yhvicey there's quite a few pieces of the Razor system that assume the `cshtml` extension. I'd recommend using it to avoid issues like this. If you do insist on having the extension, add the file to precompilation using [`MvcRazorFilesToCompile`](https://github.com/aspnet/MvcPrecompilation#options) option:

```xml
<ItemGroup>
  <MvcRazorFilesToCompile Include="@(Content)" Condition="'%(Extension)'=='.cshtml'" />
  <MvcRazorFilesToCompile Include="src/Views/Index.html" />
</ItemGroup>
```

**Comment by yhvicey** [comment]
@pranavkm It works after I changed .html to .cshtml. Thanks.
