### ISSUE TITLE
Determine if the temp data cookie is considered essential

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#7160]
RE: aspnet/Security#1561

When this new policy is applied all non-essential cookies will be suppressed. We need to determine if temp data cookie is considered essential by default.

Does MVC issue any other cookies?

@blowdart

**Comment by rynowak** [comment]
I personally think it should be non-essential, but we should make sure users can configure this. I'd say our guidance is that it's non-essential, but plenty of folks will consider it essential (per-app basis).

If you are using temp data for key functionality, there are all kinds of ways you could break. GDPR just adds another. It's very similar to the kinds of guarantees that are associated with sessions. If you really **need** session to be reliable for your app to function, you have to do some work to get there, but it's a choice that you've made.

----

> Does MVC issue any other cookies?

I can only think of temp data. We transitively depend on auth, temp data, and session, we but we don't create those cookies directly.

**Comment by Tratcher** [comment]
It's already configurable here:
https://github.com/aspnet/Mvc/blob/350c4ec4f6b377749e00b421ba5540badcb4c808/src/Microsoft.AspNetCore.Mvc.ViewFeatures/CookieTempDataProviderOptions.cs#L39

**Comment by blowdart** [comment]
Now we need to define essential :) Are there other ways of passing temp data without a cookie? If so, this is not essential.

**Comment by rynowak** [comment]
Yes, you can use session. BTW in case it's not clear, I'm already arguing that it's non-essential.

Would we say that our guidance if you're under GDPR is to use session and declare that as essential?

**Comment by Eilon** [comment]
And MVC "depends" on the anti-forgery cookie.

**Comment by Eilon** [comment]
From a discussion with @Tratcher and @mkArtakMSFT we need to take one of the following actions:
1. Mark the cookie as essential
2. Mark the cookie explicitly as non-essential, even though it's the default, but also place a comment there stating why we decided that

**Comment by mkArtakMSFT** [comment]
Guys, it seems we all agree here that TempData cooke is not essential. @kichalla, can you please make the required change?

**Comment by kichalla** [comment]
I was planning to the following:
- Mark the cookie explicitly as non-essential and a (private) comment in our code.

Questions:
- Should we throw an exception when CookieTempDataProvider is being instantiated by checking the options and if false?. This way the users immediately know that they need to explicitly configure it to true.
- If we set this to be non-essential by default, when users upgrade to 2.1.0 it would be a breaking change? Wondering how can use compatibility switch for this as we expose the cookiebuilder directly https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/CookieTempDataProviderOptions.cs#L39

**Comment by Tratcher** [comment]
That exception sounds overkill. If consent has been given then it will work fine.

The compat issue is being handled at by the CookiePolicy options. There's no breaking change for existing apps, behavior will only change for new apps.

**Comment by danroth27** [comment]
We need to revisit this. We have identity logic in the templates that rely on temp data in order to work.
