### ISSUE TITLE
JSON naming strategy not being applied to @model

### ISSUE THREAD

**Issue by simpadat** [aspnet/Mvc#7166]
I'm in the process of updating a MVC website to .Net Core and run into this issue: https://github.com/aspnet/Mvc/issues/4842

Which is fine. I applied the fix to get the proper serialisation, but ran into an issue where passing a model to a page via @model. The property names are being camelCased even though I've told MVC to use the DefaultContractResolver.

**Startup.cs:**
```
    services
        .AddMvc()
        .AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());
```

**Model**
```
    public class Grade
    {
        public int Id { get; set; }
        public string Description { get; set; }
    }
```

**Controller**
```
        public ActionResult EditGrade(int id)
        {
            var grade = _service.LoadGrade(id);
            return View("GradeEdit", grade);
        }
```

**View**
```
@model Grade
```

**Browser**
```
{id: 20, description: 'Test Data'}
```

**Comment by mkArtakMSFT** [comment]
@simpadat, can you please share the full project with a repro?

**Comment by simpadat** [comment]
I've created a simple reproduction of the issue here: https://github.com/simpadat/TestMvcNaming

Hopefully not just a combination of using React.ASPNET with MVC...

**Comment by John0King** [comment]
I believe  it's an issure of  React.AspNet

**Comment by mkArtakMSFT** [comment]
@simpadat, this indeed looks like an issue with React.AspNet. You should file a new issue with the owners of that package: https://github.com/reactjs/react.net
