### ISSUE TITLE
Improve MVC logging at INFO level

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#7171]
I think we have a few important gaps in the logging info that comes from MVC by default (`INFO`). You can **almost** use the log statements to understand your performance, but we need to add 3-4 things to make is useful.

Here's the current state - with some of my notes..
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/Home/About
-- The above comes from hosting and represents the entire request

-- We're missing right here a log statement that MVC has selected an action and started
-- executing it. We have logging for this, but it's only on in debug. Ideally this would include
-- the routing information as well, as this is commonly mixed up by users.

info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Sample.Controllers.HomeController.About (Sample) with arguments ((null)) - ModelState is Valid
-- The above represents the beginning of executing the action method. This text isn't great
-- and should be improved. We should improve formatting to look more like an actual method
-- signature. The ((null)) is just gross. We should consider simplifying ModelState is Valid to
-- use 'valid' or 'invalid'

-- We're missing right here a log statement that the action method finished and the timing.
-- We actually have this but it's only on in debug.

info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/About.cshtml.

-- We're missing right here a log statement about the time that the action result took to execute.
-- I think most of our action results have these, but they should include a duration in ALL cases,
-- even if the timing is always trivial. This reassures folks even if there will never be a problem.

-- the below represents the end of the MVC pipeline
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Sample.Controllers.HomeController.About (Sample) in 96.351ms
      
-- The below comes from hosting and represents the entire request
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 5099.661ms 200 text/html; charset=utf-8
```

Problems:
- Can't easily tell when MVC matched an action and what route it used
- Can't tell how much time was spend in user code (action method)
- Can't tell how much time was spend in user code (views)

These are all things I think you should get at a glance at the info level.

-----

Things I would change:
- [ ] [this statement](https://github.com/aspnet/Mvc/blob/c8cabde1f16980e8596f31b697786b049bd9d997/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreLoggerExtensions.cs#L107) needs to be INFO and provide more information
- [ ] [this statement](https://github.com/aspnet/Mvc/blob/c8cabde1f16980e8596f31b697786b049bd9d997/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreLoggerExtensions.cs#L127) should have its formatting and text improved, it's clunky in common cases
- [ ] [this statement](https://github.com/aspnet/Mvc/blob/c8cabde1f16980e8596f31b697786b049bd9d997/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreLoggerExtensions.cs#L132) needs to be INFO and should include timing
- [ ] Add timings to the 'end' logging of all action results, and make sure it's on at INFO level.

Overall, this means that MVC would end up with 6 logging statements for INFO level. Does that seem like too much? If we need to optimize this, we could probable get it down to 4. I do think that the missing timings at INFO level are a problem.

**Comment by mkArtakMSFT** [comment]
@jbagga, can you please look into this?
