### ISSUE TITLE
Loading Controllers at Runtime

### ISSUE THREAD

**Issue by AceCoderLaura** [aspnet/Mvc#7177]
Loading a dll into the appdomain does **not** cause the controller within to be hosted.

```
foreach (var dll in Directory.GetFiles(@"bin\Debug\net461\Controllers"))
{
    var fileBytes = File.ReadAllBytes(dll);
    System.Reflection.Assembly.Load(fileBytes);
}
```

Controller (in a dll in the Controllers folder):
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OnTheFlyControllers
{
    [Route("api/[controller]")]
    public class CityController : Controller
    {
        // GET api/City
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "Melbourne", "Brisbane" };
        }

        // GET api/City/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "New York";
        }

        // POST api/City
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}
```
What do I have to do to get it hosting as though it were referenced at compile time?

Sample here:
https://www.dropbox.com/s/nph2le655p219io/MvcSample.7z?dl=0

**Comment by khellang** [comment]
I haven't tested this, but I think something like this might work:

 1. Implement `IActionDescriptorChangeProvider` and register the implementation in the service collection. You should be able to use this to invalidate the action descriptor cache and reload new action descriptors based off your application parts.
 2. Inject `ApplicationPartManager` and add the new assembly as using an `AssemblyPart`.
 3. Inject the (previously registered) `IActionDescriptorChangeProvider` and signal the change token after you've added the new assemblies to the part manager.

**Comment by pranavkm** [comment]
@khellang's suggestion sounds workable. We generally don't dereference properties off of `ApplicationPartManager`, so things like the `ControllerActionDescriptorProvider` always get the "current" values, and controller discovery should just work. That said, like options types, I'm not certain if `ApplicationPartManager` is designed to be modified at runtime. There are types like Razor reference manager which cache values https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/DefaultRazorReferenceManager.cs#L34-L39 once for the duration of the app's lifetime. 

Adding a custom `ActionDecriptorProvider` that loads controllers from runtime loaded assemblies might be a better approach in terms of ensuring we don't inadvertently break the behavior of `ControllerActionDescriptorProvider`, but @khellang's solution would certainly be fewer lines of code.

**Comment by khellang** [comment]
> We generally don't dereference properties off of `ApplicationPartManager`, so things like the `ControllerActionDescriptorProvider` always get the "current" values, and controller discovery should just work.

Right, but `ControllerActionDescriptorProvider` itself uses it to get the controller types, right? And the default `IActionDescriptorCollectionProvider` caches descriptors, so it needs to be invalidated to fetch descriptors from controllers in new application parts.

As I said, I haven't tested this, but from looking at the code, it seems like it should work, event if it necessarily wasn't designed to be used this way :wink:

**Comment by alexsandro-xpt** [comment]
@AceCoderLaura Is this tips above work? Are you testing within View .cshtml files?

**Comment by AceCoderLaura** [comment]
I'm testing with the sample project provided. I'll start testing these options now.

**Comment by AceCoderLaura** [comment]
`IServiceCollection.AddMvc().AddApplicationPart(myControllerAssembly);`
Works great. Nothing else is required.

Thanks, all.
