### ISSUE TITLE
Dynamic Routing 

### ISSUE THREAD

**Issue by sreejukg** [aspnet/Mvc#7178]
I am posting this based on #7146  
How can I do routing during runtime, for e.g.
I have the below pa
/products/electronics/1
/products/electronics/2
I have a database entry for each products and I have a field that indicates whether product video is available for the product. Now based on this field I would like to route the request to
/TemplateWithVideo
/TemplateWithoutVideo
The routing should happen runtime, the moment the option changed in the database, the request should route to the corresponding template. How can I achieve this.

**Comment by danroth27** [comment]
If you want to render a different template depending on whether the product has an associated product video or not, you can do that with an `@if` statement in your Razor page without having to route to a different page. See https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor#control-structures for details.

**Comment by sreejukg** [comment]
I don't want to do it inside razor page, instead, I want to select which razor page to render during runtime. How can i do that?

**Comment by Vasimovic** [comment]
Why not use a controller instead and an if statement that returns the desired view

**Comment by sreejukg** [comment]
What I am trying to do is to render a particular razor page during runtime. I would like to understand the various possibilities.
