### ISSUE TITLE
Support RFC 6570 URI templates in IUrlHelper

### ISSUE THREAD

**Issue by markusbrueckner** [aspnet/Mvc#7179]
When trying to generate RFC 6570-compliant URI templates, Url.Action (and cousins) step on my toes quite a bit. Suppose I have a URL-handler like this
```csharp
[HttpGet("/some/path/{id}")]
public IActionResult GetSomething(string id)
{
...
}
```
When trying to get a route for this using `Url.Action`, I have to set the `id` portion of the value object or else no URL will be returned. What I ideally want would be a URL like `/some/path/{id}` in case the id is missing. Simply setting the value to `"{id}"` does not work, since the helper URL-encodes the braces, giving me `"%7Bid%7D"`. My current solution is to do a `.Replace()` on the resulting string, which is cumbersome, to say the least. Is there any better way to go about this?

**Comment by mkArtakMSFT** [comment]
@markusbrueckner, just to confirm I understand your ask properly: you're looking for a way to generate a parametrized route. In the example you've provided, that would be "/some/path/{id}" as specified in the routing template.

@rynowak, any thoughts regarding this?

**Comment by danroth27** [comment]
The route template syntax used in ASP.NET Core is not RFC 6570 compliant and we don't have any plans to make it so. Changing the behavior of how link generation works would also be a significant breaking change.
