### ISSUE TITLE
HttpPost in POCO Controller, without FromBody

### ISSUE THREAD

**Issue by WinInsider** [aspnet/Mvc#7182]
How to receive *complex type* from JSON body of HTTP POST request in POCO controller without FromBody attribute?

**Comment by mkArtakMSFT** [comment]
Hey @WinInsider, why don't you want to use the FromBody attribute? In ASP.NET Web API that attribute was "assumed" and implicit for complex types. In ASP.NET Core, that attribute is not assumed, but required, so users should explicitly specify it for complex types. In the coming release of ASP.NET Core, we are looking to bring back that convention.

**Comment by WinInsider** [comment]
I am totally hooked on POCO Controllers, architecturally is such a purist approach... The driving motivation is to not have any "noise", without [ApiController], [HttpPost], or [FromBody]... POCO Controllers are very light (no external  type dependency) on "user code".

Please do consider bringing back implicit inference of complex types.

Am using .net core in new project (for web api middle tier), and is awesome, so much configuration which can be done in Startup.cs, and everything else is just clean "user code"
