### ISSUE TITLE
Where should the CSS file associated with a single page be placed

### ISSUE THREAD

**Issue by TimRowe** [aspnet/Mvc#7189]
In ASP.NET MVC5, we can put the css in view folder.
But in ASP.NET Core, view folder shoud not contain css/js.
We can put the global css/js in wwwroor. But how about the resource file just associated with single page?
Any suggestions？

**Comment by m-henderson** [comment]
just organize the css file in your www/css folder. Then link to it in _Layout.cshtml.

**Comment by TimRowe** [comment]
![image](https://user-images.githubusercontent.com/5651857/34571382-57eb1b4a-f1a9-11e7-9909-24a346c26ea7.png)

**Comment by mkArtakMSFT** [comment]
@TimRowe, your static files should be in wwwroot folder. However, it's possible to organize it as you wish. If you're looking for community opinion on this topic, StackOverflow may be a better place for this question.
