### ISSUE TITLE
AddMvc/DefaultAssemblyPartDiscoveryProvider don't load parts in app assembly

### ISSUE THREAD

**Issue by derhally** [aspnet/Mvc#7191]
Controllers will not load from the main entry point assembly if the startup or configuration of the app is in assembly other than the entry point assembly.

In this scenario we are providing a library that contains all the startup and configuration functionality for our app.   Developer use that to bootstrap their app.   Their controllers won't be loaded if they exist in an an assembly that that is not in the dependency list of that library.

I would expect AddMvc() to get the entrypoint assembly and use that as the main way to find all the assembly that should be checked for parts.

You can reproduce this with the attached project.

[WebApplication1.zip](https://github.com/aspnet/Mvc/files/1603484/WebApplication1.zip)

When you run the sample, the default request to <host>/api/values will fail.

If you edit the Program.cs file and replace `UseStartup<WebStuff.Startup>()` with `UseStartup<.Startup>()` and rerun the app.  Then the request will work correctly.

I expect all controllers in the running "appdomain" to be loaded regardless what startup is being used.

**Comment by derhally** [comment]
As a workaround I modified the `Startup.ConfigureServices` in my framework assembly to do the following

```csharp
ApplicationPartManager partManager = new ApplicationPartManager();
var entryAssembly = Assembly.GetEntryAssembly();
var parts = DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts(entryAssembly.FullName);
foreach (var part in parts)
{
    partManager.ApplicationParts.Add(part);
}
services.AddSingleton(partManager);

services.AddMvc();
```

However, not sure this should be something we are required to do.

**Comment by DamianEdwards** [comment]
I believe this is by design. Did you try overriding the application's understanding of the "application" assembly like this? https://github.com/DamianEdwards/AspNetCoreVbHybrid/blob/master/VbHybrid/Program.cs#L23

**Comment by DamianEdwards** [comment]
And by "by design" I mean we scan only the "application" assembly, which is configurable and isn't necessarily the entry point assembly, but rather the one that the `Startup` class is located in.

**Comment by khellang** [comment]
You can also set it to `null`, which will make it fall back to the entry assembly 😊

**Comment by derhally** [comment]
Thanks @DamianEdwards, that works for me and is better than the workaround that I was doing.

@khellang , passing in null gives me an exception

```
System.ArgumentException
  HResult=0x80070057
  Message=A valid non-empty application name must be provided.
  Source=Microsoft.AspNetCore.Hosting
  StackTrace:
   at Microsoft.AspNetCore.Hosting.Internal.HostingEnvironmentExtensions.Initialize(IHostingEnvironment hostingEnvironment, String applicationName, String contentRootPath, WebHostOptions options)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplication1.Program.BuildWebHost(String[] args) in C:\Users\zeid\source\repos\WebApplication1\WebApplication1\Program.cs:line 14
   at WebApplication1.Program.Main(String[] args) in C:\Users\zeid\source\repos\WebApplication1\WebApplication1\Program.cs:line 10
```

**Comment by khellang** [comment]
> @khellang , passing in null gives me an exception

Ah, sorry, looks like the code to handle `null` in application name was changed for 2.1, so it's not yet released: https://github.com/aspnet/Hosting/pull/1178
