### ISSUE TITLE
Consider Accept-Charset when resolving content encoding for view results and jsonresult

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#7203]
Filing this after working on the issue https://github.com/aspnet/Mvc/issues/7188 : Question: specifing non dafault encoding

We currently do not consider Accept-Charset when trying to find the response content's encoding to be used. Following are the places we currently use the `ResponseContentTypeHelper` type to resolve the encoding:
https://github.com/aspnet/Mvc/search?utf8=%E2%9C%93&q=ResolveContentTypeAndEncoding&type=

**Comment by mkArtakMSFT** [comment]
Thanks @kichalla. Assigning back to you so you can handle it.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
