### ISSUE TITLE
Not able to build project

### ISSUE THREAD

**Issue by abhinavnigam** [aspnet/Mvc#7210]
After cloning the the sourcecode. While executing  "dotnet build mvc.sln". Getting below error

C:\Program Files\dotnet\sdk\2.1.3\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.

**Comment by rynowak** [comment]
Please use the instructions here: https://github.com/aspnet/Home/wiki/Building-from-source
(Linked from https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md and https://github.com/aspnet/Home/blob/MVC/CONTRIBUTING.md)

Let us know if there's a problem with these instructions

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
