### ISSUE TITLE
Consume RTM Microsoft.AspNet.WebApi.Client.5.2.4 package

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7212]
Follow-on to #5822.

Blocked until the RTM Microsoft.AspNet.WebApi.Client.5.2.4 package ships. But, we should fix this issue soon after that release.

**Comment by mkArtakMSFT** [comment]
The packages now are available. @dougbu

**Comment by dougbu** [comment]
- 049caf0c10
- aspnet/HttpClientFactory@101106fe78
- aspnet/Universe@0891903596
