### ISSUE TITLE
Action Filters returns an empty body in asp.net-core 2.0

### ISSUE THREAD

**Issue by jernejk** [aspnet/Mvc#7214]
I have same problem as https://github.com/aspnet/Mvc/issues/5594 and the potential fix doesn't work.
When Result is set, status code is changed (422) but response is empty.

I tried different combinations of setting up the `actionExecutedContext.Exception` and `actionExecutedContext.ExceptionHandled`.

Initial code:
``` CSharp
public override void OnActionExecuted(ActionExecutedContext actionExecutedContext)
{
    if (actionExecutedContext.Exception is ModelValidationException validationException)
    {
        var result = new BadRequestObjectResult(validationException.Errors) { StatusCode = 422 };
        actionExecutedContext.Exception = null;
        actionExecutedContext.ExceptionHandled = true;
        actionExecutedContext.Result = result;
    }

    base.OnActionExecuted(actionExecutedContext);
}
```

As well as suggested workaround:
``` CSharp
public override void OnActionExecuted(ActionExecutedContext actionExecutedContext)
{
    if (actionExecutedContext.Exception is ModelValidationException validationException)
    {
        actionExecutedContext.ExceptionHandled = false; // mark exception as handled
        actionExecutedContext.HttpContext.Response.Clear();
        actionExecutedContext.HttpContext.Response.StatusCode = 422;
        actionExecutedContext.HttpContext.Response.ContentType = new MediaTypeHeaderValue("application/json").ToString();
        string json = JsonConvert.SerializeObject(validationException.Errors);
        actionExecutedContext.HttpContext.Response.WriteAsync(json, Encoding.UTF8).Wait();
    }

    base.OnActionExecuted(actionExecutedContext);
}
```

It works as expected on `OnActionExecuting`:
``` CSharp
public override void OnActionExecuting(ActionExecutingContext actionContext)
{
    if (!actionContext.ModelState.IsValid)
    {
        //422 - Unprocessable Entity
        var result = new BadRequestObjectResult(actionContext.ModelState) { StatusCode = 422 };
        actionContext.Result = result;
    }
}
```
 
Edit:
The `ValidationException.Errors` is `Dictionary<string, IEnumerable<string>>` so that JSON structure is consistent with `actionContext.ModelState`.

**Comment by rathorer** [comment]
I changed `actionExecutedContext.ExceptionHandled = true;` to 
`actionExecutedContext.ExceptionHandled = false;`.
It worked for me.

**Comment by mkArtakMSFT** [comment]
@rynowak, @dougbu what is the expected behavior in the first sample @rathorer has shared?

**Comment by rynowak** [comment]
It's expected that 
```
context.Result = new BadRequestResult(...)
```

Will short-circuit the chain of exception filters and will execute the provided action result. None of the other properties should have any effect if context.Result is set. This is a bug

**Comment by rynowak** [comment]
Wait, never mind, this is an action filter not an exception filter.

**Comment by rynowak** [comment]
It's expected that setting `ActionExecutedContext.Result` to a result value will **replace** the action result returned by the method and cause the new action result to run if the action is considered successful.
Setting:
```
actionExecutedContext.Exception = null;
```
OR
```
actionExecutedContext.ExceptionHandled = true;
```

Should mark the action as successful.

Do you have a repro project you can share for this?

**Comment by jernejk** [comment]
@rathorer solution worked!
It seems I haven't used `actionExecutedContext.ExceptionHandled = false;` for all of the combinations.

@rynowak I'll create a repro where having `actionExecutedContext.ExceptionHandled = true;` didn't work properly on the weekend.

Thanks for the help, we can now do proper validation for the forms. :)

**Comment by mkArtakMSFT** [comment]
@jernejk, have you got a chance to prepare a sample repro project so we can investigate it?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
