### ISSUE TITLE
Merge release/2.0.0 changes back to dev

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Mvc#7222]
The 2.0.2 patch went out today. To make sure we are keeping dev and release branches in sync, let's merge the release/2.0.0 branch back to dev.

FYI I started to do this, but there were a bunch of changes that I'm not familiar with. Not sure what should be brought back into dev or not.

cc @pranavkm

**Comment by pranavkm** [comment]
I can merge this in.

**Comment by pranavkm** [comment]
Merged in https://github.com/aspnet/Mvc/commit/b196708a3e0bca4820f2002e063fabe979afde1b
