### ISSUE TITLE
Support conflict resolution when multiple precompiled views have the same path 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7223]
When a path collision occurs in ViewsFeatureProvider, we need to resolve conflicts. 

1. If the path comes from a view that belongs to the app, use it.
2. If neither comes from the app, throw.

**Comment by DamianEdwards** [comment]
Is this needed to make overriding the `_ViewStart.cshtml` from pages in an Area in a referenced library (e.g. Identity UI) work? I'm trying to make the pages from the library use the application's Layout like we discussed but it doesn't seem to have any affect.

@rynowak

**Comment by rynowak** [comment]
This is needed to allow the *app* to override a *libraries* - when using precompilation. This is also needed to allow a *library* to override a *library*.

Overriding anything with a runtime-compiled view should be working. If you have having problems you either don't have up to date bits, or it's a bug.

**Comment by rynowak** [comment]
MSIT has my laptop so I have no access to the build stuff unfortunately.

Are you trying to override a view in a library with a runtime-compiled view? Do you have this in a repo somewhere I can see? 

Identity has not been updated yet to use precompiled views, it's still using a file provider.

**Comment by DamianEdwards** [comment]
@rynowak it seems Identity UI's option configure is running first, so it ends up with the `ManifestEmbeddedFileProvider` being first in the list, rather than last. I'm assuming this issue will go away when Identity UI changes to use compiled views. Or we can update it to use `IPostConfigureOptions`.

**Comment by rynowak** [comment]
yeah, if this is identity then it sounds like that's you're issue. You could write your own configure options to reorder the providers. It's a little gross but it will work.

**Comment by DamianEdwards** [comment]
@rynowak yep done that, it works. @pranavkm is going to update Identity UI to see if we can fix quickly for now.
