### ISSUE TITLE
Remove project file elements added for WebApiCompatShim in 2.0

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7229]
The Microsoft.AspNetCore.Mvc.WebApiCompatShim package now depends on the latest (5.2.4-preview1) Microsoft.AspNet.WebApi.Client package. That dependency includes a new .NET Standard 2.0 assembly. This assembly supports all platforms the Microsoft.AspNetCore.Mvc.WebApiCompatShim package supports and includes the full Web API Client feature set.

When upgrading projects using the Microsoft.AspNetCore.Mvc.WebApiCompatShim package to our nightly builds or the forthcoming 2.1.0-preview1 release, we recommend removing the following elements from the project file. (Of course, some projects may need the elements for other reasons.)
``` xml
<PackageTargetFallback>$(PackageTargetFallback);portable-net451+win8</PackageTargetFallback>
<DisableImplicitAssetTargetFallback>true</DisableImplicitAssetTargetFallback>
```

FYI the `<PackageTargetFallback>` element caused the application to build and run against the Portable Class Library (PCL) assembly from the Microsoft.AspNet.WebApi.Client package.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/bab520f4dd358dfd6fa22c727670a7a06a8b25f9#diff-eccb1a9de7356cf6e272d8724c19cd0cL12
