### ISSUE TITLE
Allow libraries to opt out of implicitly including precompiled views/pages when referenced by an application

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7239]
By default precompiled views/pages in libraries are included by default. 

This is not always the right thing to do as it can result in invalid/insecure behavior by default when those views/pages require further configuration, (like authentication).
And might cause very hard to debug issues by the fact that those views might get included by a transitive package reference without the user having any idea where they are coming from.

If we want to support 3rd party libraries that ship UI, We need to support allowing libraries to opt-out from including their views/pages implicitly so that they can force the user to perform a gesture that fully configures all the components they depend on to work in a correct and safe way.

With the alternative way of including views in class libraries (using an embedded file provider) this is already possible, as an explicit gesture is required to allow the view engine to find views embedded in the assembly, allowing library authors to force the user to perform an explicit gesture to configure all the required components for the library to work.

**Comment by mkArtakMSFT** [comment]
Leaving this to preview2, as we want to have proper design around this.

**Comment by javiercn** [comment]
@mkArtakMSFT I'm confused about this. I thought the plan was to do it.

**Comment by javiercn** [comment]
We are tagging the main assembly that contains the views with an additional metadata attribute (manually for preview1) that specifies additional dependencies (for example precompilation assemblies)

Our default assembly part discovery provider takes this metadata into account when building the initial list of application parts and any assembly that was referenced as an additional reference gets added as an AdditionalAssemblyPart. These additional parts don't contribute references to the list of metadata references for runtime view compilation.

**Comment by rynowak** [comment]
We're tracking this item for preview 2 to complete the full end to end. It should be possible to configure this in MSBuild when creating a library. There were a few other polish things we thought of.

**Comment by javiercn** [comment]
Reopening this to track the E2E. All work for preview1 is in.

**Comment by DamianEdwards** [comment]
Did we capture what we discussed about this recently?

**Comment by pranavkm** [comment]
> Did we capture what we discussed about this recently?

@DamianEdwards, sorry, what was this about?
