### ISSUE TITLE
502.5 Process Failure - Deploy to IIS

### ISSUE THREAD

**Issue by Eonasdan** [aspnet/Mvc#7243]
I have a .net core 2 MVC app. It runs fine via IISExpress in VS but as soon as I deploy it to IIS I get 502.5 in the browser and logs give me:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions,
Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
   at Project.Web.Core.Program.BuildWebHost(String[] args) in PATH\Project\Project.Web.Core\Program.cs:line 15
   at Project.Web.Core.Program.Main(String[] args) in PATH\Project\Project.Web.Core\Program.cs:line 11
```

Coping `Microsoft.Extensions.Configuration.Abstractions.dll` from the nuget package doesn't seem to make a difference. I'm reference 2.0.0 nuget in all layers of my n-tier project.

I've read several of the other issues here and SO posts, none of which has helped me. My publish profile deletes all files in the deploy directory. I have cleared nuget cache, I've cleaned and rebuilt and deleted bin folders.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, could you please provide us with a minimalistic repro project that illustrates the problem?

**Comment by Eonasdan** [comment]
here you go. I shrank it down as best I could. It works on IISExpress but not when I deploy it to my IIS on Win 10. I didn't bother trying to deploy it to my server since if it won't work locally where I have all the dev stuff install it definitely won't work on my old Server '12

https://github.com/Eonasdan/test.core.project

**Comment by mkArtakMSFT** [comment]
Thanks for providing the repro project. One of our team members will look into it and get back to you.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please investigate this?

**Comment by Eonasdan** [comment]
any progress on this? It's blocking my deployment :( @pranavkm does it help to say that I like your avatar image? :D

**Comment by mkArtakMSFT** [comment]
@Eonasdan, can you please confirm, that you have the **ASP.NET Core Windows Server Hosting** bundle installed? If not, that will be the most probable reason for the issue you're facing.
You'll be able to download the bundle from: https://www.microsoft.com/net/download/windows

**Comment by Eonasdan** [comment]
@mkArtakMSFT yes. I have 2.0.5 install. Just to be sure I did redownload and do a repair install and restarted IIS. Same result
![image](https://user-images.githubusercontent.com/1006516/35363468-1db838d8-0138-11e8-8a20-fdf67851a4c4.png)

**Comment by Eonasdan** [comment]
@mkArtakMSFT I just tried to deploy this project to a brand new Azure Web App (through VS -> Publish) and I'm greeted with the same error.

**Comment by mkArtakMSFT** [comment]
Thanks for the info, @Eonasdan. We'll update the thread as soon as we get to investigate this.

**Comment by pranavkm** [comment]
Your project is excluding packages that are required for the application to function - for instance - https://github.com/Eonasdan/test.core.project/blob/master/Akron.Web.Core/Akron.Web.Core.csproj#L96. Removing `PrivateAssets="All"` should fix this. That said, I'd highly recommend removing individual package references and replacing it with a reference to [`Microsoft.AspNetCore.All`](https://www.nuget.org/packages/Microsoft.AspNetCore.All/2.0.5). Have a look at what a File -> New project looks like and use that as a template to remove individual AspNetCore's package references.

**Comment by Eonasdan** [comment]
I know what file new project does. I personally don't like the giant meta package because it's impossible to remove individual packages from it. That said removing `PrivateAssets` from all packages EXCEPT!! `Microsoft.VisualStudio.Web.CodeGeneration.Design` did the trick.

**Comment by pranavkm** [comment]
> I personally don't like the giant meta package because it's impossible to remove individual packages from it. 

Is there a reason you wouldn't want to reference the metapackage? For 2.0.0, the packages come from the runtime store, 2.1.0, these would come from a shared runtime - https://github.com/aspnet/Announcements/issues/287. In either case, if you have the corresponding SDK installed, you shouldn't see any of the packages in the output.
