### ISSUE TITLE
Remove the need to set the content root relative to the solution file on functional tests

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7244]
We can have a build time solution as part of our build. The snippet below emits an assemblymetadatareference attribute per referenced project dll containing the dll for the dependent project as part of the key and the content root as the value.

```csharp
[assembly: AssemblyMetadata("Microsoft.AspNetCore.Testing.ContentRoot[dependency.dll]", "C:\\work\\test\\assemblyattribute\\dependency")]
```

```xml
  <Target 
      Name="AddContentRootForProjectReferences"
      BeforeTargets="BeforeCompile"
      DependsOnTargets="PrepareForBuild;GetReferenceAssemblyPaths">
    <ItemGroup>
      <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
        <_Parameter1>Microsoft.AspNetCore.Testing.ContentRoot[$([System.IO.Path]::GetFileName(%(_ResolvedProjectReferencePaths.FullPath)))]</_Parameter1>
        <_Parameter2>$([System.IO.Path]::GetDirectoryName(%(_ResolvedProjectReferencePaths.MSBuildSourceProjectFile)))</_Parameter2>
      </AssemblyAttribute>
    </ItemGroup>
  </Target>
```

The testing framework simply needs to read the assembly attributes from the current assembly to find one that matches the assembly in TStartup and set the content root to that. This will help enable shadow copy scenarios without having to worry about the content of the files.

/cc: @rynowak @pranavkm Thoughts? I think this is dope and cheap and we can get rid of the content root issue for good

**Comment by pranavkm** [comment]
Is there another itemgroup you could use to get to resolved path `_ResolvedProjectReferencePaths` is a private property of the SDK, so we couldn't reliably use it in our code. Apart from that, the idea certainly sounds pretty cool

**Comment by Eilon** [comment]
@mkArtakMSFT I'm changing this to an 'enhancement' because this is a feature of our testing helpers for public consumption, not just a fix for our own builds.

**Comment by javiercn** [comment]
Done in https://github.com/aspnet/Mvc/commit/908e7a863bdbd6e229594c6637713cb2f2a6f63b
