### ISSUE TITLE
FileVersionProvider doesn't work with escaped urls

### ISSUE THREAD

**Issue by xt0rted** [aspnet/Mvc#7245]
I've noticed that not all of my images are receiving cache breakers when using `asp-append-version="true"` and after looking into it more I've found it's only when the path is escaped.

This will receive a cache breaker
```html
<img asp-append-version="true" src="/content/images/some folder/file.jpg">
```

This will not receive a cache breaker
```html
<img asp-append-version="true" src="/content/images/some%20folder/file.jpg">
```

I'm using the `FileVersionProvider` in my own tag helpers to apply cache breakers to a few other tags/attributes (meta tags & `srcset`) and I'm seeing the issue there as well. In those instances if I unescape the path before passing it into `FileVersionProvider.AddFileVersionToPath()` then a cache breaker is applied to it.

Is this behavior expected, or should escaped paths be unescaped before looking them up on disk?

The reason I'm escaping these paths is I've run into issues in older versions of iOS Safari that sometimes don't load the resource if it has spaces in it, and it makes my `srcset` parsing much simpler. For now this isn't a big deal since the files affected aren't changing, but if they do the only way to make sure they all work is to rename the folders so they don't have a space in them.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. One of our team members will look into it and get back to you.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen can you please look into this?

**Comment by NTaylorMullen** [comment]
> Is this behavior expected, or should escaped paths be unescaped before looking them up on disk?

Yup, this behavior is expected. You should not be asking the disk for escaped paths since the idea of escaping paths doesn't translate well to the file system.

I'd recommend creating a TagHelper that runs on any tags you're concerned with **after** the `ImageTagHelper`/`UrlResolutionTagHelper`. That way you can escape any necessary paths prior to your page being sent over the wire.
