### ISSUE TITLE
Add overloads to PageConventions to support areas

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7246]
`[Page|Folder]RouteModelConvention` and `[Page|Folder]ApplicationModelConvention` work by matching `ViewEnginePath` with no support for additional filtering. To make these conventions work for areas, we need to accept an additional parameter the "area" that filters models that belong the specified area. 

Here's the additional set of public API we would need:

* AddAreaPageRoute
* AllowAnonymousToAreaFolder
* AllowAnonymousToAreaPage
* AuthorizeAreaFolder
* AuthorizeAreaPage

We could also add overloads to our existing methods to support passing in this additional value. e.g. ` AddPageRoute(string areaName, string pageName, string route)` although the order in which parameters appear makes this less appealing.

**Comment by pranavkm** [comment]
cc @danroth27

**Comment by rynowak** [comment]
Sorry, can you provide a description and example of the concrete problem that needs to be solved?

**Comment by pranavkm** [comment]
Consider this application:

```
- Areas
    - Identity
        - Pages
            - Profile.cshtml
- Pages
    - Index.cshtml
```

The ViewEnginePath for Profile.cshtml is `/Profile` with a RVD `{ Area = Identity }`. There is no way to specifically add conventions for the area today. You could do `AuthorizeFolder("/")` but that would be incorrect.
I'll leave the rest as an exercise to the reader.

**Comment by rynowak** [comment]
> The ViewEnginePath for Profile.cshtml is /Profile

This doesn't seem right. Isn't the path `/Areas/Identity/Pages/Profile.cshtml`? How do we distinguish `/Pages/Profile.cshtml` and `/Areas/Identity/Pages/Profile.cshtml

**Comment by pranavkm** [comment]
Here's what the descriptors for the two look like:

```
RelativePath = /Areas/Identity/Pages/Profile.cshtml
VEP = /Profile
Route = Identity/Profile
RouteValues = [ Area = Identity, PageName = /Profile ]

RelativePath = /Pages/Profile.cshtml
VEP = /Profile
Route = Profile
RouteValues = [ PageName = /Profile ]
```

We match based on VEP in the conventions - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.RazorPages/ApplicationModels/PageConventionCollection.cs#L242-L244 hence the ambiguity.

**Comment by rynowak** [comment]
This sounds to me like ViewEnginePath is broken when areas are involved, and thus can't be used for **anything**. We now need to take a look at anywhere we use view engine path.

The conventions should use `RelativePath` - in the case of non-areas we should prepend the root before processing. In the case of areas we should prepend the area path.

Can you share the signatures of the APIs you're trying to add? Let's try to lock those down

**Comment by pranavkm** [comment]
### User facing

```C#
PageConventionCollection AllowAnonymousToAreaPage(this PageConventionCollection conventions, string areaName, string pageName);
PageConventionCollection AllowAnonymousToAreaFolder(this PageConventionCollection conventions, string areaName, string folderPath);
PageConventionCollection AuthorizeAreaPage(this PageConventionCollection conventions, string areaName, string string pageName, string policy = null);
PageConventionCollection AuthorizeAreaFolder(this PageConventionCollection conventions, string areaName, string string folderPath, string policy = null);
PageConventionCollection AddAreaPageRoute(this PageConventionCollection conventions, string areaName, string string pageName, string route);
```

### Infrastructral
```C#
IPageApplicationModelConvention AddAreaPageApplicationModelConvention(string areaName, string pageName, Action<PageApplicationModel> action);
IPageApplicationModelConvention AddAreaFolderApplicationModelConvention(string areaName, string folderPath, Action<PageApplicationModel> action);

IPageRouteModelConvention AddAreaPageRouteModelConvention(string areaName, string pageName, Action<PageRouteModel> action);
IPageRouteModelConvention AddAreaFolderRouteModelConvention(string areaName, string folderPath, Action<PageRouteModel> action);
```

**Comment by rynowak** [comment]
looks good

**Comment by pranavkm** [comment]
FYI @mkArtakMSFT  self assigning this for preview1.
