### ISSUE TITLE
Have consistent casing for JSON properties in dynamic returns

### ISSUE THREAD

**Issue by nefcanto** [aspnet/Mvc#7256]
Create a simple project, as simple as the default template provided in Visual Studio.

Now create a simple Human class:

```
public class Human 
{
    public string Name { get; set; }
}
```

Now have two services, one returning an instance of a human class, and one returning a dynamic result, that has a property which is an instance of a Human class:

```
return new Human
{
   Name = "someone"
};
```

and

```
dyanmic result = new ExpandoObject();
result.Name = "someone";
result.Human = new Human
{
    Name = "anotherone"
};
return result;
```

And this is the result JSON:

```
{
    "name": "someone"
}
```

and 

```
{
    "Name": "someone",
    "Human": {
        "name": "anotherone"
    }
}
```

As you can see when a dynamic model is created on the fly and returned, camelCasing is not applied on it consistently.

**Comment by khellang** [comment]
I think this might be because `ExpandoObject` implements `IDictionary<string, object>` and it's treated as a dictionary.

Newtonsoft.Json won't change dictionary keys by default because that means they won't roundtrip. If you want to enable camelCasing for dictionary keys, you can change it:

```csharp
services.AddMvc().AddJsonOptions(o => o.SerializerSettings.NamingStrategy = new CamelCaseNamingStrategy { ProcessDictionaryKeys = true });
```

**Comment by mkArtakMSFT** [comment]
Hi @nefcanto. Did @khellang's suggestion work for you?

**Comment by rynowak** [comment]
We might want to consider changing our default. This continues to surprise users

**Comment by khellang** [comment]
About special-casing `dynamic`/`ExpandoObject` or changing the `ProcessDictionaryKeys` default?

**Comment by rynowak** [comment]
`ProcessDictionaryKeys`. We don't special case anything in MVC, we just configure JSON.NET's public settings.

**Comment by mkArtakMSFT** [comment]
@danroth27, what do you think about @rynowak's suggestion regarding changing the defaults?

**Comment by khellang** [comment]
I think changing the default is a Very Bad Idea™ because dictionaries would change when round-tripping. Isn't that the reason why `ProcessDictionaryKeys` is `false` by default? @JamesNK?

You might think a lot of people are getting tripped up and surprised by *not* changing dictionary keys by default, but I have a sneaky feeling the backlash would be pretty hard if you changed the default 🤔

**Comment by rynowak** [comment]
I'm just suggesting we consider it 😆

**Comment by JamesNK** [comment]
`ExpandoObject` is serialized as a dictionary because it is a dictionary, you just happen to be using dynamic to set values instead of the indexer like so...

```
ExpandoObject result = new ExpandoObject();
result["Name"] = "someone";
result["Human"] = new Human
{
    Name = "anotherone"
};
return result;
```

**Comment by rynowak** [comment]
@JamesNK - do you have any thoughts about the idea of using changing the default for casing of keys? 

We change the default to camel case between MVC5 and MVC Core 1. We continue to get the feedback that users are caught out by the distinction between dictionaries and objects (which aren't distinct in js).

**Comment by JamesNK** [comment]
I imagine there are more situations where dictionary keys shouldn't be serialized.

```
User u = new User();
u.Name = "James";
u.Roles = new Dictionary<string, bool>
{
    ["ROLE-ADMIN"] = true,
    ["ROLE-MANAGER"] = false
};
```

Applying camel case to "ROLE-ADMIN" and "ROLE-MANAGER" wouldn't be wanted.

**Comment by nefcanto** [comment]
As the feedback of creating many applications for different business solutions, my suggestion is to have a super camelCasing and PascalCasing option that can be easily configured.
That is, as the developer as soon as I configure camelCasing explicitly, I know that EVERYTHING going to client would be camelCased, and I take the responsibility.
Even I suggest creating an enumeration with long explaining names:

public enum CasingForAnyJsonReturned
{
    CamelCased,
    PascalCased
}

That I think can be a wrapper for special Newtonsoft.Json configuration under the hood. If they chose camelCasing explicitly, then even a middleware can be injected into the pipeline behind the scenes that changes the casing of ANYTHING JSON going back to the user from anywhere.

**Comment by JamesNK** [comment]
You can definitely configure casing.

https://stackoverflow.com/questions/35772387/jsonserializersettings-and-asp-net-core
https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Serialization_CamelCaseNamingStrategy.htm

**Comment by mkArtakMSFT** [comment]
I feel like it's too late to change the casing. For several years people adopted to current casing, plus so many articles/blog posts cover the topic. This will be a breaking change. Instead, we should consider an easier way to configure casing.
What about extension methods for UseCamelCasing() and UsePascalCasing() ?

**Comment by AlexejTimonin** [comment]
Is this still "up-for-grabs"? I've implemented (for my own learning sake) two extension methods on `MvcJsonOptions`, `UseCamelCasing()` and `UsePascalCasing()`. From user perspective this translates to:
camelCase: `services.AddMvc().AddJsonOptions(o => o.UseCamelCasing());`
PascalCase: `services.AddMvc().AddJsonOptions(o => o.UsePascalCasing());`

If this is still "up-for-grabs" I would like to work on this.

**Comment by rynowak** [comment]
Yes, go ahead 👍

**Comment by AlexejTimonin** [comment]
To make JSON.NET camelCase `ExpandoObject`  the property `DefaultContractResolver.NamingStrategy.ProcessDictionaryKeys` must be set to `true` as already pointed out in this issue. By doing so, users may experience odd serialization behaviour if string keys in dictionary contain chars that are not letters as separators. Here is a test to illustrate it :

        public void Will_Improperly_CamelCase_DictionaryKeys_ThatContain_Dashes()
        {
            // Arrange
            var options = new MvcJsonOptions();
            var resolver = options.SerializerSettings.ContractResolver as DefaultContractResolver;
            resolver.NamingStrategy = new CamelCaseNamingStrategy { ProcessDictionaryKeys = true };
            var dictionary = new Dictionary<string, bool>
            {
                ["HELLO-WORLD"] = true
            };

            // Act
            var actual = JsonConvert.SerializeObject(
                value: dictionary,
                formatting: options.SerializerSettings.Formatting,
                settings: options.SerializerSettings);

            // Assert
            var expected = "{\"hellO-WORLD\":true}";
            Assert.Equal(expected, actual);
        }

Is this acceptable behaviour for `UseCamelCasing()` extension method?

**Comment by AlexejTimonin** [comment]
I've a question about `UsePascalCasing()` extension method. It looks like JSON.NET does not have out of the box PascalCasing `NamingStrategy`. It does however offer `DefaultNamingStrategy` which does not change property names and dictionary keys. Maybe the `UsePascalCasing()` method should be named something like `UseCodeConventionCasing()` or `UseDefaultCasing()`? From my understanding up to this point, there has never been any PascalCase strategy in JSON.NET, people assume PascalCase because C# convention is to use PascalCase for public "anything", but in reality JSON.NET never applied any casing but used the casing as it is in the code, it feels wrong to name the method `UsePascalCasing` since under the hood there will not be any specific PascalCase implementation, unless you want to have custom `PascalCaseNamingStrategy` in MVC.

**Comment by JamesNK** [comment]
UseDefaultCasing would be confusing because the default in MVC is camel. I would call it UseMemberCasing

**Comment by pranavkm** [comment]
Merged in https://github.com/aspnet/Mvc/commit/52c1e942c66da065f93e90e9e83ed50afc497607. Thanks for the PR @AlexejTimonin!
