### ISSUE TITLE
Move the basic functionality of file streaming to a lower level API

### ISSUE THREAD

**Issue by jbagga** [aspnet/Mvc#7259]
See https://github.com/aspnet/Mvc/issues/7208#issuecomment-356588707

@Tratcher @dustinmoris

**Comment by rynowak** [comment]
This isn't an MVC issue 😆 - *a lower level* implies non-MVC

**Comment by jbagga** [comment]
I'll move it to Home and @Eilon can decide which label. Thanks!

**Comment by jbagga** [comment]
This issue was moved to aspnet/Home#2807
