### ISSUE TITLE
InputTagHelper showing route value instead of model value

### ISSUE THREAD

**Issue by achandlerwhite** [aspnet/Mvc#7260]
Hello, this is real head scratcher.

I am finding that the input tag helper is ignoring model values and instead using route values. It occurs when the route has a parameter with the same name as a model property (case insensitive) and the action method has a parameter that MVC binds to the route parameter.

The model class:
```
class ViewModel
{
  public string Name { get; set; }
  public string Identifier { get; set; }
}
```

The route in Startup is defined as:
```
{controller=Home}/{action=Index}/{identifier?}
```

The action method:
```
ActionResult Details(string identifier, string name = "")
{
  var model = new ViewModel { Name = "MyName", Identifier = "perm-id-123" }
  return View(model);
}
```

The Razor:
```
@model ViewModel
...
<input asp-for="Name" />
<input asp-for="Identifier" />
...
```

With this setup I would expect the input element to render the with values of "MyName" and "perm-id-123", but if an "identifier" value is in the route it is rendered instead of "perm-id-123"! And if there were a query parameter called 'name' that was bound to the action method parameter then that value will also render instead if "MyName".

This might be by design, but the documentation says asp-for="Property" equates to `model => model.Property`... and this isn't what I'm observing.

Thanks!

**Comment by achandlerwhite** [comment]
Also, here is my system info:

```
acw-mbp:tag-helper-bug acw$ dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by iscifoni** [comment]
Can you share a project who reproduce the problem, I have tryed but it works correctly

**Comment by achandlerwhite** [comment]
Sure, I made a sample project here: [https://github.com/achandlerwhite/tag-helper-bug](https://github.com/achandlerwhite/tag-helper-bug)

Thanks for taking a look. Running the project as is and clicking the link on the Index page will show the results.

**Comment by achandlerwhite** [comment]
@iscifoni Let me know if there is anything further I can do to help report this issue. Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. One of our team members will look into it and get back to you.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this one?

**Comment by iscifoni** [comment]
@achandlerwhite i'm sorry for the long time waiting

@pranavkm I think to have found where is the problem.
(https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L1290) At this line the value is replaced whit ModelStateI tem value if present, but, i think, this is to do only if useViewData is true otherwise not. 

Correct ? or this is by design ?

**Comment by pranavkm** [comment]
@iscifoni it's intentional. There's some detailed explanation around it here - https://github.com/aspnet/Mvc/issues/1517#issuecomment-62244133 which boils down to - in a round-trip scenario, (e.g. when model validation fails), you want to your form to print the values the user posted and not the initial values from the model. 

https://github.com/aspnet/Mvc/issues/1517#issuecomment-62477491 has some suggested workarounds.

**Comment by iscifoni** [comment]
@pranavkm  Ok, remove items from ModelState (ModelState.Remove("Identifier")) could be a good workaround, so when   GetModelStateValue is called it will not found the item and enter in the then case of the if (https://github.com/aspnet/Mvc/blob/381ac2946cc0b4809d38617aa5ab8cae72024ab7/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L1290).

Reading always value from ModelState could expose me to a code injection attack ? I Think Yes.

**Comment by iscifoni** [comment]
@achandlerwhite  

this works

```
        public IActionResult WidgetDetails(string identifier = "identifier", string name = "")
        {
            var widget = new Widget { Name = "My Widget", Identifier = "widget-identifier-123" };
            ModelState.Remove("Name");
            ModelState.Remove("Identifier");

            return View(widget);
        }

```

**Comment by achandlerwhite** [comment]
Thanks everyone for the responses. I see now that it's due to the model state binding behavior. I was confused because in this situation I wasn't posting anything, but technically to the route parameters constitute a model.

Instead of the workaround @iscifoni presented, I'm more inclined to change the razor markup:
```
<input asp-for="@Model.Identifier" />
```
This explicitly has it use the object I passed into view rather than the implied ModelState. Is there any reason I shouldn't be doing that?

Also in the documentation here:
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms in the section "Expression Names" the phrase

>  `asp-for="Property1"` becomes `m => m.Property1`

 is an oversimplification because its using values from ModelState, not the actual Model object, right?

**Comment by iscifoni** [comment]
@achandlerwhite yes is used a modelstate, modelvalue is used if the idem is not present in the modelstate

**Comment by pranavkm** [comment]
> Reading always value from ModelState could expose me to a code injection attack ? I Think Yes.

@blowdart do you want to take this? @dougbu or I could explain the workflow.

@dougbu do we have write up on how model expressions are interpreted in Mvc? We could add those to our docs.

**Comment by blowdart** [comment]
@iscifoni How do you think this is code injection attack? Everything put in the form is HtmlAtrributeEncoded. Sure, you can inject a value into a form, but it's just going to be a value because it's encoded.

**Comment by dougbu** [comment]
@pranavkm the interpretation of a model expression i.e. where the value will be found is covered pretty thoroughly for HTML helpers in their doc comments. But, we have nothing similar for tag helpers.
- **Hint** Tag helpers work about the same as the corresponding expression-based HTML helper e.g. `<textarea/>` interprets `asp-for` about the same way `Html.TextAreaFor(...)` interprets the passed expression.

We also haven't duplicated this information on the documentation site.

**Comment by pranavkm** [comment]
We updated the docs to include a snippet about possible sources for a model expression. See https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms#expression-names.

**Comment by achandlerwhite** [comment]
@pranavkm  Awesome, thanks!
