### ISSUE TITLE
Unable to serve static index.html

### ISSUE THREAD

**Issue by dzoech** [aspnet/Mvc#7261]
When creating a new Core Web Application, serving an index.html file as a static file is not working. However, other html files (e.g. test.html) do work.

Version 2.0.5

Repro:

1. Create a new ASP.NET Core WebApplication (with a new solution).
2. Rebuild solution to get rid of NuGet warnings.
3. Add an index.html file in the wwwroot folder.
4. Configure to use static files:
```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles();
        }
```

5. Run (no difference when using IIS Express).
6. Result: The index.html cannot be displayed, error 404.

When I add another html file to wwwroot, I can navigate there in the browser and it is displayed successfully.

**Comment by talanc** [comment]
Add `app.UseDefaultFiles();` before `app.UseStaticFiles();`

For more information: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?tabs=aspnetcore2x#serve-a-default-document

**Comment by talanc** [comment]
Use you also just use `app.UseFileServer();`

For more information: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?tabs=aspnetcore2x#usefileserver

**Comment by mkArtakMSFT** [comment]
Hi @dzoech. Do you experience the same error when you try to navigate to index.html explicitly (http://localhost:5000/index.html - or some other port you've configured)?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
