### ISSUE TITLE
Spelling error in problem details title for invalid request

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#7263]
occured -> occurred

```json
{
  "errors": {
    "Name": [
      "The Name field is required."
    ]
  },
  "type": null,
  "title": "One or more validation errors occured.",
  "status": null,
  "detail": null,
  "instance": null
}
```

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/aspnet/Mvc/commit/ebdb3c650a04e7b5f1c734ac0c01347dec900b10.  See https://github.com/aspnet/Mvc/commit/ebdb3c650a04e7b5f1c734ac0c01347dec900b10#diff-ff7fe9279f6e18451702ed2ec62d2faaR416
