### ISSUE TITLE
CORS not working at all on ASP.NET Core 2.0 Web API project

### ISSUE THREAD

**Issue by murat0058** [aspnet/Mvc#7265]
CORS not working at all on ASP.NET Core 2.0 Web API project

**Comment by javiercn** [comment]
Can you provide an example of what is not working?

**Comment by murat0058** [comment]
Failed to load http://localhost:47861/api/v1/values/muratdogan: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. 

a small sample Asp.net Core 2.0 WebApi user Can you know how to share sample json data with ajax or jquery in html page?
