### ISSUE TITLE
Add a property to PartialTagHelper that no-ops if the view cannot be found

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Mvc#7268]
Please consider adding an required parameter to the @Html.Partial similar to @RenderSection

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us.
To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve?

**Comment by grahamehorner** [comment]
@mkArtakMSFT currently the @RenderSection("", required: true/false) is only allowed from a layout, and the section is optional; using an @Html.Partial is allowed from a layout/page/view, however @Html.Partial doesn't allow for the required/optional and therefore requires the partial to be discovered in the view locations.

When constructing generic templates or plugins that may/may not have areas of html to inject/populate the template in a give location; you can't use @section or @html.partial (given no required flag) and therefore the only option is to create a custom taghelper; it would be good IMHO to allow an optional required parameter on the @Html.Partial extension method.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, any thoughts regarding this?

**Comment by NTaylorMullen** [comment]
This is equivalent to https://github.com/aspnet/Mvc/issues/7515 but for the Html Helper. As a side note we've been cautious as to where we invest our energy in regards to HtmlHelpers. This would be something to run by @DamianEdwards.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen, is this something which can be achieved using newer concepts like partial tag helper ?

Yes that's what [this](https://github.com/aspnet/Mvc/issues/7515) issue addresses.

**Comment by mkArtakMSFT** [comment]
Thanks @NTaylorMullen.
@DamianEdwards, any thoughts?

**Comment by DamianEdwards** [comment]
It's as reasonable as #7515, i.e. if we did that we'd likely do this too. Not likely to get priority in the next release though.

**Comment by grahamehorner** [comment]
@DamianEdwards IMHO html helpers/tag helpers should have parity where possible, but totally understand that these are low on priority, maybe good for an up-for-grabs labelling 🤔🤟

**Comment by pranavkm** [comment]
Updated the title. Thanks to @AlexejTimonin's PR, there's an `optional` attribute on the `PartialTagHelper`. Specifying this would cause the tag helper to no-op if the view cannot be located. E.g.

`<partial name="_MyPartial" optional />`

**Comment by pranavkm** [comment]
Follow up comment: we want to focus on evolving tag helpers over adding additional features to HtmlHelpers, so I think this does solve this issue. https://github.com/aspnet/Mvc/issues/7515 is slightly related, but isn't the same problem as this one. That requires attempting to perform a fallback lookup without an option to no-op if neither view is found. That can be addressed independently of this issue.
