### ISSUE TITLE
UrlHelper issues due to mixing Controller Action and Razor Pages

### ISSUE THREAD

**Issue by MV10** [aspnet/Mvc#7269]
Aspects of the Razor Pages extensions to `IUrlHelper` have misleading Intellisense descriptions. I read somewhere that most of the docs are auto-generated from code comments, so that's why I'm raising the issue here instead of the docs repo, but the corresponding high-level descriptions in the [documentation]((https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.iurlhelper?view=aspnetcore-2.0)) are also misleading. I'd like to request that the summaries in the code be improved. I have a couple of examples.

All seven of the `Page` overrides use the same description:

> Generates a URL with an absolute path for the specified `pageName`.

The problem is that five of the seven methods only generate relative paths. Only the two lengthy [`Page`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.urlhelperextensions.page?view=aspnetcore-2.0#Microsoft_AspNetCore_Mvc_UrlHelperExtensions_Page_Microsoft_AspNetCore_Mvc_IUrlHelper_System_String_System_String_System_Object_System_String_System_String_) methods that require the programmer to explicitly (and somewhat tediously) provide the scheme and host will produce an absolute path (and the "scheme" parameter is confusingly named "protocol" which would be the wrong property to pass from `Request`).

Worse yet, since the `Page` helpers don't support the tilde convention (they return `null` if the page path begins with a tilde), there's no way to use `Content` with  the output of `Page`, which seems like a natural assumption as a first attempt to produce a fully-qualified URL. Currently [`IUrlHelper.Content`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Routing/UrlHelper.cs#L231) is described as:

> Converts a virtual (relative) path to an application absolute path.

One must actually go to the `Content` [doc page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.iurlhelper.content?view=aspnetcore-2.0#Microsoft_AspNetCore_Mvc_IUrlHelper_Content_System_String_) to read the Remarks to discover that this is an Controller Action-oriented method because it requires a leading tilde to work at all.

I've seen several StackOverflow Q&As where the answers suggest things like writing custom extensions to prepend `Request.Scheme` and `Request.Host` using string formatting, so it doesn't seem as if the correct use of `IUrlHelper` is particularly obvious or discoverable.

I know member names like `Content` are probably set in stone for compatibility reasons but I feel the Intellisense and docs deserve a bit more attention.

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue. We'll consider clarifying the docs in one of the upcoming releases.
