### ISSUE TITLE
Consider support for models with open generics in MVC views

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#727]
See UserVoice suggestion here: https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/2706166-support-for-generics-in-razor-view.

**Comment by Eilon** [comment]
Closing because we are not planning to implement this.

**Comment by mansoor-omrani** [comment]
Is it possible to open this topic again?

**Comment by Eilon** [comment]
@mansoor-omrani of course. Do you have an interesting scenario to share on this?

**Comment by mansoor-omrani** [comment]
I think so.

It might be slightly long to describe the scenario and write it codes.

Should I post the whole story and its code here?

**Comment by Eilon** [comment]
@mansoor-omrani it might make more sense to post a new issue that covers the scenario you're after. We can then decide how it is best to implement it.

**Comment by pranavkm** [comment]
Btw, I know @javiercn was asking about something similar.

**Comment by mansoor-omrani** [comment]
@Elion The topic is the same, but ok. I post the idea/feedback as a new issue as you say.

This way the excavating the previous idea out of the dusts might make it be implemented eventually. I believe it is a useful feature. Although implementing it is a little tricky, I think it is feasible.

@pranavkm I couldn't find @javiercn's post. Could you direct me to his post?

**Comment by rynowak** [comment]
> This way the excavating the previous idea out of the dusts might make it be implemented eventually. I believe it is a useful feature. Although implementing it is a little tricky, I think it is feasible.

What would you use this for and why is it hard using the existing feature set? Can you provide an example?

**Comment by kramffud** [comment]
Where is this? I can't believe I haven't seen what I consider to be an overwhelming Use Case for this, albeit one at which I am fully aware of the countless eyes that will roll. Send in a generic model collection, reflect on its items' property names for column headers and then iterate through the list to display those items' values in rows. Reflection, slow, I get it. But how much dev time would be saved for simple key/value lookup lists, like Country? Let the eye rolling begin.

**Comment by javiercn** [comment]
@kramffud You can do that without having an IEnumerable<T> as a model. In fact our default templated html helpers already do this for you.
