### ISSUE TITLE
base ViewController with ViewData losing values 

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Mvc#7279]
I have a base ViewController 'MyBaseViewController' which inherits from Controller, 'MyBaseViewController' has a number of private const string which get placed into ViewData[".."], MyViewController inherits from MyBaseViewController and also adds items into the ViewData  however when a View attempts to access the ViewData and values populated by the controller and the base controller the ViewData is null?

**Comment by danroth27** [comment]
Thanks for reporting this issue. Could you please provide a simplified project that reproduces this issue so that we can take a look?

**Comment by grahamehorner** [comment]
@danroth27  https://github.com/grahamehorner/AspNetCoreMvcViewDataIssue

**Comment by mkArtakMSFT** [comment]
Thanks. One of our team members will look into it and get back to you.

**Comment by pranavkm** [comment]
@grahamehorner sorry, I just got around to look at this issue. Your repro app seems to be deleted. Could you make it available again?

**Comment by grahamehorner** [comment]
@pranavkm yes no problem, it’s late here in uk so will do that ASAP and will repo in new project tomorrow thanks

**Comment by grahamehorner** [comment]
@pranavkm please see GitHub repo https://github.com/grahamehorner/AspNetCoreIssues

**Comment by pranavkm** [comment]
@grahamehorner `ViewDataDictionary` is property activated, the property value is replaced by the property activated instance after the controller is instantiated blowing away the instance that was mutated in the constructor. This behavior is documented in https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controller.viewdata?view=aspnetcore-2.0#Remarks. The fact that the property is non-null in the constructor is to support unit testing scenarios. I'm going to call this more explicitly in our docs.

As for a fix, I'd recommend moving the code you have in your constructor in to action filter (e.g. `OnActionExecuting`).

**Comment by pranavkm** [comment]
https://github.com/aspnet/Mvc/pull/7371 adds more clarity to the remarks section.

**Comment by grahamehorner** [comment]
@pranavkm while I understand why the activator would initialise the propriety when the construct is not present or if the property is not initialised, IMHO I would have expected the values not to be overwritten when explicitly set in the constructor of the controller or a based class. Is this the same for ViewBag ? what was the reason/decision behind clearing/wiping the ViewData when set in a constructor ?

IT A DEFINITE GOTYA

**Comment by pranavkm** [comment]
@grahamehorner the fact that it's non-null in the ctor is a side-effect of supporting unit testing for controllers. It's initialized with incorrect values so using it as part of initialization would be incorrect. We could have it throw if it's not-empty, but I'd like to see if having the updated documentation is a sufficient deterrent.

**Comment by grahamehorner** [comment]
@pranavkm definitely needs to be called out, hopefully other won’t fall into the trap of using ViewData in the constructor, for a work-around I’m using DI to injection a IDictionary that I pass around and populate in the constructor and base class. Thanks for looking at this, and yes IMHO an exception or a compiler error is preferable to nothing.
