### ISSUE TITLE
UrlHelper should not depend on ActionContext

### ISSUE THREAD

**Issue by mnmr** [aspnet/Mvc#7280]
I think it's insane that UrlHelper depends on so much request-infrastructure: it is just bad design. For instance, to use UrlHelper from a SignalR Hub (which has access to none of this stuff), you need to manually hack stuff together ([as done here](https://stackoverflow.com/questions/46096068/asp-net-core-2-0-creating-urlhelper-without-request)). 

But clearly, since it possible to have a working UrlHelper without a valid request, why even require it in the first place? 

If there is some obscure scenario where it's really needed, provide overloads that allows one to pass in a context, instead of making it really hard to obtain the class in the first place.

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue.   We'll consider your feedback as part of an existing issue we're tracking [here](https://github.com/aspnet/Home/issues/2819).
