### ISSUE TITLE
ModelState.IsValid is false while there is no error but there are properties with state equal to Unvalidated

### ISSUE THREAD

**Issue by SherifRefaat** [aspnet/Mvc#7289]
This is my model structure

```
public class PostEdit
{
	public String Body { get; set; }
	public Int32 Id { get; set; }
	public List<PostPicture> PostPictures { get; set; }
	public String Title { get; set; }
	public Int32 WorkshopId { get; set; }
}

public class PostPicture
{
	public Int32 Id { get; set; }
	public Boolean IsActive { get; set; }
	public String Path { get; set; }
}
```

Here is my [ModelState object.](https://drive.google.com/file/d/1dXUernP2LhZJk8_sGmGzQ9VicMx88eFp/view?usp=sharing)

I have reviewed this issue: https://github.com/aspnet/Mvc/issues/4978

but I still don't understand what is the source of the issue nor what I am supposed to do.

Thanks.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, could you please provide us with a minimalistic repro project that illustrates the problem?
