### ISSUE TITLE
TagHelper Generic type as attribute

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Mvc#7298]
I would like to write a set of tag helpers which accept an instance type of a SignalR hub, and generates/outputs javascript boilerplate code for the use with in the browser.  Is the possible ?

**Comment by mkArtakMSFT** [comment]
@DamianEdwards, any thoughts about this? /cc @davidfowl

**Comment by mkArtakMSFT** [comment]
@rynowak, any thoughts regarding this?

**Comment by Eilon** [comment]
@grahamehorner - can you show what kind of code you plan on writing? What does the tag helper look like, and where would the generic type fit in?

**Comment by rynowak** [comment]
> any thoughts regarding this?

Usually when these scenarios are brought up there's a straightforward solution that doesn't require generics. We know that building features like this could be done, but it would require significant tooling and language work to build a reasonable experience. We haven't yet found a scenario that justifies the cost.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
