### ISSUE TITLE
Referencing an AspNet Core Web application

### ISSUE THREAD

**Issue by crmabs** [aspnet/Mvc#7303]
My general goal is to be able to add HTTP endpoint to any of my future applications in order to issue commands or monitor them from outside. Kestrel seems to be a rather elegant solution for that.
In the past few days I made some attempts to achieve this but I failed terribly. This has to do with the fact that in the past year so much happened and several -maybe too many in my case- article came out for different versions of .Net Core offering different workarounds / solutions for similar issues. Ironically the more I read about it the more confused I got. Most of them were already fixed issues or related to older version of Asp.Net Core.
I assume there must be a supersimple solution for my problem which truely aligns with the coding style of the new .Net Core project templates. Lovely stuff, congratulations for the participants!

I'd like to develop / debug the solution on usual way from within VS but I can't get it done. Actually I tried many options with slightly different results but none of them worked. Probably I missed the one proper combination of steps. 

[screenshot](https://pasteboard.co/H4JECxx.png)
This image shows the behaviour running the project from VS.

In order to demonstrate the issue I created a simple out of the box solution which can be found here: [repo](https://github.com/crmabs/Referenced-AspNet-Core-2-web-app)
I deliberately kept everything intact so the example is as clean as possible. 
- The ConsoleApp project simulates the application I'd like add the HTTP endoint to. 
- WebAppWithRazor project prepresents the component which is the HTTP endpoint.
So ConsoleApp references WebAppWithRazor.
It's VS2017 15.5.5 that I'm using.

Eventually I found a workaround to run the published solution but it only works from console - outside of VS.
I refuse to believe that there is no other way. :)

1: Add this to the .csproj of the web application:
`<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>`
As a result it will output a "refs" folder with a lot of .dlls to a path something like:
....\ReferenceWebApp\WebAppWithRazor\bin\Release\PublishOutput\refs 

2: Publish both projects

3: From the web application's publish folder copy "WebAppWithRazor.deps.json" file and "refs" folder to the publish output of the referencing project. 

Any help would be appreciated!

**Comment by davidfowl** [comment]
I'm still confused on exactly what you're trying to do.

**Comment by crmabs** [comment]
Hi David,
The easiest demonstration is to clone this, and try running the ConsoleApp, and just simply try connecting to the Kestrel it fires up. It should immediately show my issue in the browser. 
https://github.com/crmabs/Referenced-AspNet-Core-2-web-app
It should look like this:
https://pasteboard.co/H4JECxx.png
It will take 2 minutes to try it out.

Longer version:
I try to reference an Asp.Net Core web app into another project (in our case it's a simple cosole app). The referenced project would provide HTTP admin endpoint for the app in question. 
 Let's say I'll have a renderer and using the HTTP interface I can expose all kinds of monitoring and command interfaces.  If I'm not mistaken VLC has this kind of thing.
 The point is the reusability / separation of the Asp.Net Core app. 

Many thanks for your time!

**Comment by crmabs** [comment]
Hi, Many thanks for guiding me through the maze! 
As you requested I created a question on StackOverflow.
https://stackoverflow.com/questions/48539705/referencing-an-asp-net-core-mvc-project

Well, to be honest my only reason posting this here 'coz I wanted davidfowl to see / answer my question. :) I almost succeeded. Have nice day!
