### ISSUE TITLE
InputFormatters: Adding additional content types is hard

### ISSUE THREAD

**Issue by dasMulli** [aspnet/Mvc#7306]
I recently implemented handling of browser's [CSP reports](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#Sample_violation_report) in an asp.net core app and it turned out to be quite hard.

The problem is that these reports are sent (at least by chrome) using `application/csp-report` as content type header. It took me a while to figure out how to correctly configure MVC to process the request, as I was only receiving 415 responses.

I ended up with a startup code that feels quite hacky (and I'm still unsure if that's actually a correct approach):
```c#
services.AddMvc(options =>
{
    // add csp report media type to the json input formatter
    // the json patch formatter derives from the json formatter
    // so use the first one supporting application/json
    options.InputFormatters
        .OfType<JsonInputFormatter>()
        .First(formatter => formatter.SupportedMediaTypes.Contains("application/json"))
        .SupportedMediaTypes.Add("application/csp-report");
})
```

The bad experience is that it took me quite some time to figure out how the input formatters worked and without browsing the source code on GitHub, I wouldn't have been able to make it it work (e.g. knowing about the json patch formatter's relationship with the normal json formatter). Google only returned useful results for adding content type mappings for responses.

I propose doing one or more of the following:

1. Add an easier to use API about how to handle non-standard content types for requests that map to one of the already implemented input formatters.
2. Add some common content types like `application/csp-report` to the provided input formatters.
3. Add a documentation sample for handling custom content types OR a sample for handling CSP reports that includes this.

**Comment by mkArtakMSFT** [comment]
Hi @dasMulli. Thanks for your feedback.
The Custom formatters are actually something we do have documentation for at https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-formatters, which also includes a sample project.

You can use this (very similar to what you've got) sample to do what you're looking for:

```
services.AddMvc(options=>
{
    options
    .InputFormatters
    .Where(item=>item.GetType() == typeof(JsonInputFormatter))
    .Cast<JsonInputFormatter>()
    .Single()
    .SupportedMediaTypes
    .Add("application/csp-report");
});
```

It doesn't really make sense for us to add another layer of simplification over that. As for registering the media `application/csp-report` media type, it's something specific to the application at this point.
That said, we do have some plans to add support for CSPs on our backlog. When we decide that we do that work, we may bring in the requested media type through a separate helper method.
