### ISSUE TITLE
asp.net mvc template app crashes with exceptions on raspian ARM

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#7309]
_From @livarcocc on January 28, 2018 1:19_

_From @Buzze11 on January 27, 2018 11:32_

## Steps to reproduce

    1. create example mvc app with "dotnet new mvc -n test"
    2. Disable HttpsRedirect comment out (//app.UseHttpsRedirection();)
    3. Disable Cookie Policies comment out (//app.UseCookiePolicy();)
    4. publish with "dotnet publish -r linux-arm" and deploy it to the raspberry pi
    5. run app on raspberry device with ./test
    6. place a webrequest from any browser to the server

## Expected  behavior
MVC Example App shows up in browser window

## Actual behavior
- Exceptions get thrown.

- Even without modifying the example app (not deactivating https) the app is throwing exceptions on requests.

## Environment data
`dotnet --info` output:
Product Information:
Version: 2.2.0-preview1-007947
Commit SHA-1 hash: e8f7ddd01b

Runtime Environment:
OS Name: Windows
OS Version: 10.0.10586
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\2.2.0-previe

Microsoft .NET Core Shared Framework Host

Version : 2.1.0-preview1-26116-04
Build : eeb3a84e2142aba791fe003564b8afd048c45ff9

[Exception.log](https://github.com/dotnet/cli/files/1670022/Exception.log)

_Copied from original issue: dotnet/cli#8490_

_Copied from original issue: aspnet/Home#2831_

**Comment by Eilon** [comment]
_From @rynowak on January 28, 2018 2:39_

@mkArtakMSFT @javiercn @pranavkm this is a crash in the view loading codepath that's been getting lots of changes lately. This is a possible 2.1.0-preview1 regression.

**Comment by Eilon** [comment]
_From @mkArtakMSFT on January 28, 2018 5:10_

@NTaylorMullen, can you please handle this? Thanks!

**Comment by Eilon** [comment]
_From @pranavkm on January 28, 2018 20:40_

Looks like a dup of https://github.com/aspnet/templating/issues/233 that was fixed by https://github.com/aspnet/Mvc/commit/b20e35e76abf78f3f99e52e336ff429083b9cb8c. Would be good to determine if this still reproduces using a newer runtime, but my guess is this was likely fixed.

**Comment by Eilon** [comment]
_From @Buzze11 on January 28, 2018 21:59_

Today I installed the latest SDK & Runtime and tested again. The Issue is still reproducable.

**Comment by NTaylorMullen** [comment]
Hey @Buzze11 I tried your scenario and all worked once I updated my runtime versions. Could you try your scenario one more time but with the following changes:

1. Add a NuGet feed to https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
2. Update the created projects csproj to use AspNetCore.All 2.1.0-preview1-28183

**Comment by NTaylorMullen** [comment]
Closing for now. @Buzze11 feel free to re-open if your issue still persists.
