### ISSUE TITLE
Architectural diagrams

### ISSUE THREAD

**Issue by mirsaeedi** [aspnet/Mvc#7315]
Our team is doing a research about architectural properties of aspnet core. I want to know if there is any available diagram and explationtion about the architecure of the framework and its components. I couldnt find any relevant material on google.

**Comment by mkArtakMSFT** [comment]
Hi @mirsaeedi. We do have a bunch of guidelines as well as samples available on https://www.microsoft.com/net/learn/architecture. Feel free to look through those.

**Comment by mirsaeedi** [comment]
@mkArtakMSFT Thanks for your response. But I meant the architecture of the framework itself, not aspnet core based applications. Would you please help me with that? Is there any information about the layers of the framework and relations between its main components? In our research, we want to inspect the code to find out the differences between the actual architecture and the conceptual architecture.
