### ISSUE TITLE
performance issue with asp.net core mvc + angular

### ISSUE THREAD

**Issue by mchenx** [aspnet/Mvc#7318]
I have run a few tests recently by using AB (Apache Bench) and noticed the performance for asp.net core 2.0 mvc looks good to me, over 1,000 requests/sec for accessing /home (300 requests, 100 concurrency)

But when I created the asp.net core mvc + angular, I got only 14 requests/sec performance for accessing /home, way slower (300 requests, 100 concurrency)

I am wondering if there is anything wrong with my test setup. 
Has anyone encountered this kind of issue?

I tried this on both windows 10 and macOS 10.13, similar outcome

After investigate a bit, I think it runs slow for two reasons：
1   the site created by using angular template renders page on server side as there is the asp-prerender-module="ClientApp/dist/main-server" attribute in <app> node

2  it uses IIS

After removed the asp-prerender-module attribute and ran the site by executing "dotnet run" (which means using kestrel directly), I got over 460 requests/sec on a desktop pc.

However, when I tried to deploy the site on Azure Web App, but it seems I can only deploy it using IIS, which  turned out very slow, just like running on iis express locally.

Any way this is not an issue that relates to asp.net core.. I'll looking to the aspNetCoreModule for IIS.

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/JavaScriptServices#1510

**Comment by mchenx** [comment]
I take back the perf issue caused by aspNetCoreModule, after re-deployed to IIS 10, it works fine, got over 1300 requests/sec
