### ISSUE TITLE
DefaultAuthorizationService fails second time through when having a global AuthorizeFilter and a decorated AuthorizeAttribute

### ISSUE THREAD

**Issue by timdoke** [aspnet/Mvc#7319]
I have an output like the below.. (I changed some of the names to be generic).

There doesn't seem to be a way to disable the second call to the DefaultAuthorizationService when you have a global AuthorizationFilter defined and an AuthorizationAttribute decorated on an api method.  The first call goes through the global filter and the second seems to go through the attribute.  What I would like to do, is disable the global filter when the method is decorated with an AuthorizationAttribute and only use the authentication schemes (preferably just successful on one of the schemes but it seems to call both) from the attribute.  I tried creating my own version of the AuthorizeFilter but this default filter still seems to get called from somewhere.  Also, the authorization I already passed seems to get ignored the second time through for some reason.  The policy is only a ValidUserAuthorizationPolicy..

Workflow.Audit.Service> info: MyCustomTokenAuthenticationHandler[8]
Workflow.Audit.Service>       AuthenticationScheme: MyTokenType was successfully authenticated.
Workflow.Audit.Service> info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
Workflow.Audit.Service>       Authorization was successful for user: myUser.
Workflow.Audit.Service> info: MyCustomTokenAuthenticationHandler[8]
Workflow.Audit.Service>       AuthenticationScheme: MyTokenType was successfully authenticated.
Workflow.Audit.Service> info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
Workflow.Audit.Service>       Authorization failed for user: (null).
Workflow.Audit.Service> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
Workflow.Audit.Service>       Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Workflow.Audit.Service> info: Microsoft.AspNetCore.Mvc.ForbidResult[1]
Workflow.Audit.Service>       Executing ForbidResult with authentication schemes (MyTokenType).
Workflow.Audit.Service> info: MyCustomTokenAuthenticationHandler[13]
Workflow.Audit.Service>       AuthenticationScheme: MyTokenType was forbidden.
Workflow.Audit.Service> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Workflow.Audit.Service>       Executed action ValuesController.Post (Solution) in 597.3095ms
Workflow.Audit.Service> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]

**Comment by kichalla** [comment]
@HaoK This seems to be another requirement where users would like to have an override functionality. (i.e Authorization policy decorated on an action overrides the one registered as a global filter).

**Comment by HaoK** [comment]
Yeah this should be fixed by turning on the new CombineAuthorizeFilters flag added in 2.1 as part of the fix to https://github.com/aspnet/Mvc/issues/6995

**Comment by HaoK** [comment]
Basically if you combine the default policy with your actual policy, you typically will the correct behavior @timdoke

**Comment by kichalla** [comment]
@HaoK but isn't this a different scenario? like CombineAuthorizeFilters requires all policies to be satisfied, right? but in this scenario only the policy decorated on the action needs to be satisfied.

**Comment by timdoke** [comment]
I tried to do something like this inside my authorization filter.  Yet somehow, that default authorization service was being called from somewhere else..

`public class GenericAuthorizationFilter : AuthorizeFilter, IAuthorizationFilter
    {
        public GenericAuthorizationFilter(AuthorizationPolicy policy) : base(policy)
        {
            
        }


        public void OnAuthorization(AuthorizationFilterContext context)
        {
            Task.Run(async () => await OnAuthorizationAsync(context));

        }

        public override async Task OnAuthorizationAsync(AuthorizationFilterContext context)
        {
            //https://andrewlock.net/introduction-to-authorisation-in-asp-net-core/
            var effectivePolicy = Policy;
            if (effectivePolicy == null)
            {
                effectivePolicy = await AuthorizationPolicy.CombineAsync(PolicyProvider, AuthorizeData);
            }
            
            if (effectivePolicy == null)
            {
                return;
            }

            // Allow Anonymous skips all authorization
            if (context.Filters.Any(item => item is IAllowAnonymousFilter))
            {
                return;
            }

            var ps = new PathString("/swagger");
            if (context.HttpContext.Request.Path.StartsWithSegments(ps))
            {
                return;
            }

            HashSet<string> schemes = new HashSet<string>();

            foreach (var scheme in effectivePolicy.AuthenticationSchemes)
            {
                schemes.Add(scheme);
            }

            //override the global policy if there is a policy set on the filter
            //there can be more than one defined; the global, the one set on a method, etc

            var authFilters = context.Filters.OfType<AuthorizeFilter>().ToList();

            if (authFilters.Count > 1)
            {
                schemes.Clear();
                foreach (var f in authFilters)
                {
                    if (!(f is GenericAuthorizationFilter))
                    {
                        foreach (var s in f.Policy.AuthenticationSchemes)
                        {
                            schemes.Add(s);
                        }
                    }
                }
            }`

**Comment by HaoK** [comment]
Its a permutation of the same issue.

If you add a global authorization filter, that means you want that policy applied globally...on all actions, so the correct behavior is to verify that a combined policy of all of the requirements in global filters, and anything on the action are met.

This is fine normally for the authorization requirements.  The issues is when different authentication schemes are involved, in @timdoke case, he mentions there is API involved, so likely this is the same issue where the default global policies is requiring a cookie, while the action policy is targeting only bearer, so when you don't combine the two, and try to access the API without a cookie, the global filter will reject and redirect to the login page...even if you have a bearer token.

**Comment by timdoke** [comment]
This looks pretty similar to https://github.com/aspnet/Mvc/issues/6995..  Not sure if it's exactly the same because even if the behavior was different, shouldn't it still work?  @HaoK.  During the second execution, the user wasn't even populated..   

With the new updates for 2.1, would we be able to have default multiple authentication schemes (my company uses at least three) and then be able to decorate an api with a custom scheme (say basic for a automated call) and then have all four schemes work on that method?  And then the three work everywhere else..

**Comment by timdoke** [comment]
Let me clarify.. If I have a global authentication filter and then I decorate an api method with the exact same scheme, it also fails..

**Comment by kichalla** [comment]
@timdoke I tried the following now and it _might_ work for your scenario. Here I am not inheriting from `AuthorizeFilter` on purpose. Try it out and see if it works for you.

```c#
public class GlobalAuthorizeFilter : IAsyncAuthorizationFilter
{
    private readonly AuthorizeFilter _innerFilter;

    public GlobalAuthorizeFilter(AuthorizeFilter innerFilter)
    {
        _innerFilter = innerFilter;
    }

    public Task OnAuthorizationAsync(AuthorizationFilterContext context)
    {
        if (IsGlobalFilterTheClosestAuthorizeFilterToTheAction(context.Filters))
        {
            return _innerFilter.OnAuthorizationAsync(context);
        }

        return Task.CompletedTask;
    }

    private bool IsGlobalFilterTheClosestAuthorizeFilterToTheAction(IList<IFilterMetadata> filters)
    {
        for (var i = filters.Count - 1; i >= 0; i--)
        {
            var filter = filters[i];

            if (filter is GlobalAuthorizeFilter)
            {
                return true;
            }
            else if (filter is AuthorizeFilter)
            {
                return false;
            }
            else
            {
                continue;
            }
        }
        return false;
    }
}
```

**Comment by timdoke** [comment]
Thanks @kichalla.. I'll check it out.  I think what you're trying to do, is use dependency injection to get the actual authorization filter that's been registered, and then only use one of the two?  What I thought was happening, however, was that the authorization was being called from another source (taking out my authorization filter implementation didn't make any difference).  

Does this sort of control the flow of those executions?  My own version (which to be fair, did inherit from AuthorizeFilter) didn't seem to affect the flow of the default authorization filter.  

Regardless, I'll let you know what happens..

**Comment by timdoke** [comment]
Bummer.. Looks like the same problem happened @kichalla.

I tried just passing my authorizationfilter with policy to it.  It failed again with the below message.  Unfortunately, it still tried to validate it again after succeeding the first time.  

One other interesting thing -- it returns with a 403 error code.  I don't set a 403 error code anywhere.  That has to be coming from the second authorization service.  It is also still hitting both the scheme from the AuthorizationAttribute and from the global AuthorizationFilter..  I tried forcing the global filter to succeed (referred to below as MyGlobalToken)  -- that didn't make any difference.  Is there anything else you want me to try?  Does this still look like the bug you referred to @HaoK?  

Workflow.Audit.Service> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Workflow.Audit.Service>       Request starting HTTP/1.1 GET http://localhost:32162/api/values/5  
Workflow.Audit.Service> info: TRTA.LoneStar.NETCore.Security.CoreAuthentication.MyGlobalTokenAuthenticationHandler[8]
Workflow.Audit.Service>       AuthenticationScheme: MyGlobalToken was successfully authenticated.
Workflow.Audit.Service> info: TRTA.LoneStar.NETCore.Security.CoreAuthentication.BasicTokenAuthenticationHandler[8]
Workflow.Audit.Service>       AuthenticationScheme: Basic was successfully authenticated.
Workflow.Audit.Service> info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
Workflow.Audit.Service>       Authorization failed for user: (null).
Workflow.Audit.Service> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
Workflow.Audit.Service>       Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Workflow.Audit.Service> info: Microsoft.AspNetCore.Mvc.ForbidResult[1]
Workflow.Audit.Service>       Executing ForbidResult with authentication schemes (Basic).
Workflow.Audit.Service> info: TRTA.LoneStar.NETCore.Security.CoreAuthentication.BasicTokenAuthenticationHandler[13]
Workflow.Audit.Service>       AuthenticationScheme: Basic was forbidden.
Workflow.Audit.Service> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Workflow.Audit.Service>       Executed action Workflow.Audit.Service.Controllers.ValuesController.Get (Workflow.Audit.Service) in 4053.4662ms
Workflow.Audit.Service> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Workflow.Audit.Service>       Request finished in 6107.0071ms 403

**Comment by HaoK** [comment]
The workaround for that bug is to avoid using global attributes or any on the base controller, and specifying everything you want in the attribute on every action.

**Comment by mkArtakMSFT** [comment]
We're closing this issue as both the workaround as well as the long-term fix have been provided.

**Comment by timdoke** [comment]
@HaoK, @mkArtakMSFT, @kichalla  is there a full example somewhere of using multiple authentication schemes on authorization attributes?  I couldn't find one.

**Comment by HaoK** [comment]
`[Authorize(AuthenticationSchemes = "Scheme1,Scheme2")] should do the trick, you can also set it on the policy as well if you don't want to use the auth policy

**Comment by timdoke** [comment]
@HaoK I'm more wondering about the minimum code required in the startup.  I removed everything I had before, and I was getting some weird errors (very similar to what's on this original issue; I thought maybe I needed to clean, etc, but that didn't make any difference).  I did services.addAuthentication with my schemes added via extension  methods, put in app.UseAuthentication, and app.UseMvc.
