### ISSUE TITLE
the default file watch sometimes does not work in Linux containers

### ISSUE THREAD

**Issue by xinyanmsft** [aspnet/Mvc#7320]
We found this during our internal testing. It happens sometimes (with low frequency).

OS: Linux container, docker 1.12

Create a dotnet core MVC application using the default template. Deploy to a Docker container running inside AKS (docker v1.12). Modifies Contact.cshtml file via file copying. The process is launched via 'dotnet run --no-restore --no-build --no-launch-profile'.

In most cases, the file change is picked up. However sometimes changes to the .cshtml file wasn't picked up.

We are switching to use  ENV DOTNET_USE_POLLING_FILE_WATCHER=true as a work around.

**Comment by mkArtakMSFT** [comment]
Hi @xinyanmsft. The solution you came up is our recommendation when running in a docker container.
