### ISSUE TITLE
Add HtmlHelper to MVC Controller like the UrlHelper

### ISSUE THREAD

**Issue by jonmeyerson** [aspnet/Mvc#7321]
I have a dynamic views which are assembled together at runtime. example a string like 

"`<div>[PlaceHolder1]</div>Hello World<div>[PlaceHolder2]</div>`"
in which I loop through the string and replace elements in square brackets with a razor view using Html.Partial()

I have been able to get this functionality to work but think it should be added to the framework.

Below is my implementation to create a HTMLHelper in a controller

```
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Mvc.ViewFeatures.Internal;
using Microsoft.Extensions.Options;
using System.IO;
using System.Text.Encodings.Web;
using System.Threading.Tasks;


    public class HelperGenerator
    {
        private readonly IHtmlGenerator _htmlGenerator;
        private readonly ICompositeViewEngine _compositeViewEngine;
        private readonly IModelMetadataProvider _modelMetadataProvider;
        private readonly IViewBufferScope _viewBufferScope;
        private readonly IActionContextAccessor _actionContextAccessor;
        private readonly HtmlHelperOptions _htmlHelperOptions;

        public HelperGenerator(IHtmlGenerator htmlGenerator, ICompositeViewEngine compositeViewEngine, IModelMetadataProvider modelMetadataProvider, IViewBufferScope viewBufferScope, IActionContextAccessor actionContextAccessor, IOptions<MvcViewOptions> options)
        {
            _htmlGenerator = htmlGenerator;
            _compositeViewEngine = compositeViewEngine;
            _modelMetadataProvider = modelMetadataProvider;
            _viewBufferScope = viewBufferScope;
            _actionContextAccessor = actionContextAccessor;
            _htmlHelperOptions = options.Value.HtmlHelperOptions;
        }
        public IHtmlHelper HtmlHelper(ViewDataDictionary ViewData, ITempDataDictionary TempData)
        {
            var helper = new HtmlHelper(_htmlGenerator, _compositeViewEngine, _modelMetadataProvider, _viewBufferScope, HtmlEncoder.Default, UrlEncoder.Default);
            var viewContext = new ViewContext(_actionContextAccessor.ActionContext,
               new FakeView(),
               ViewData,
               TempData,
               TextWriter.Null,
               _htmlHelperOptions);
            helper.Contextualize(viewContext);
            return helper;
        }
        private class FakeView : IView
        {
            public string Path => "View";

            public Task RenderAsync(ViewContext context)
            {
                return Task.FromResult(0);
            }
        }
    }
```

**Comment by Eilon** [comment]
This code:

> `               new FakeView(),`

Is precisely the reason why we don't have it built in. The HtmlHelper types requires a ViewContext instance, but unless you fake a bunch of data in it, it can't be constructed. The problem with putting fake data in it is that it is a mismatch of expectations when someone sees it. It would look like you have a real HtmlHelper, but really a lot of stuff just won't work on it.

Maybe there's another way to accomplish what you're trying to do?

**Comment by jonmeyerson** [comment]
Well, i'll look into more what part of the IView is used, but from what i see in my use, it renders and continues render subsequent HtmlHelpers correctly. I'm not sure what stuff wouldn't work. 

How about if the method signature was changed to have the IView passed in with it?

**Comment by Eilon** [comment]
It depends on each specific helper. For some helpers it doesn't matter much because they just do a "standalone" simple operation. But for others, such as maybe `Html.Partial`, they probably need a lot more context and "real-ness."

**Comment by mkArtakMSFT** [comment]
Hi @jonmeyerson. As @Eilon has mentioned already, the proposed suggestion is not technically feasible. We're closing the issue.
