### ISSUE TITLE
Analyzer that checks for correct usage of model binding related attributes

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#7324]
Recommend `BindAttribute` over `ModelBinderAttribute`. See https://github.com/aspnet/Mvc/issues/6944.

**Comment by mkArtakMSFT** [comment]
We have multiple other issues covering this ask:
- https://github.com/aspnet/Mvc/issues/7711
- https://github.com/aspnet/Mvc/issues/7415
