### ISSUE TITLE
How can I surpress validation when binding for a specific enum property on an input model while allowing custom validation to affect the ModelState?

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Mvc#7325]
I want to allow for the query string `?OutputFormat=` but when this happens the model state is invalid, which makes sense.

I can work around the issue by doing the following:

    public ImageFormat? Format { get; set; }

    [BindNever]
    public ImageFormat OutputFormat
    {
        get
        {
            return Format ?? ImageFormat.Png;
        }
    }

But this is messy, so what I would really like is the option to be able to set a default value for when this is the case, like so:

    public ImageFormat OutputFormat { get; set; } = ImageFormat.Png;

So when the OutputFormat query string is empty, the value is set to `ImageFormat.Png`.

I don't want to set the OutputFormat property to nullable because I don't want to have to cast it to a non-nullable all over the place as I don't like passing around null values.

There is an option to prevent binding undefined values in the MvcOptions for v2.1:
SuppressBindingUndefinedValueToEnumType

But what I would like is for this to be expanded so that there is also the option:
AllowBindingEmptyValueToEnumType

Which, if set to true, will bind an empty value to the first value in the enum or a default value specified.

I can see by the following line that there is a check to see if the type is nullable or not, and if the type is nullable then the error is not added to the model state:
https://github.com/aspnet/Mvc/blob/c922b0b90dc95407e1f59510f953d220442f96a1/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/SimpleTypeModelBinder.cs#L141

But this is not desirable on a large codebase.

Again, another alternative is to do something like the following in the controller:
`ImageFormat imageFormat = model.OutputFormat ?? ImageFormat.Png;`

But I don't want to have to do that either, as I'm looking for an option that can provide a consistent way to allow empty query string argument values just like if the type was a string.

Other non-nullable types such as int have the same problem.

For instance `?width=` causes a problem, but with baked in support for a default value we could avoid any issues.

Maybe what is needed is support for a default value for non-nullable types so that if the value is not set we can avoid everything blowing up.

So this is what I propose:

    public class ImageViewModel
    {
            public string Id { get; set; }
            [FromQuery(DefaultValueWhemEmpty=ImageFormat.Png)]
            public ImageFormat OutputFormat { get; set; }
            [FromQuery(DefaultValueWhemEmpty=0)]
            public int Width { get; set; }
    }

Or support for an AllowBindingEmptyValueToEnumType setting and

    public class ImageViewModel
    {
            public string Id { get; set; }
            public ImageFormat OutputFormat { get; set; } = ImageFormat.Png;
            public int Width { get; set; } = 0;
    }

**Comment by Matthew-Bonner** [comment]
Basically, I want enums to bind but in the event that binding results in an invalid value, I want to be able to suppress the invalid value from affecting the ModelState and just use a default value, presumably the best thing to do here is create a new attribute that will need to be baked into code that deals with validation?

**Comment by Matthew-Bonner** [comment]
Basically, I want enums to bind but in the event that binding results in an invalid value, I want to be able to suppress the invalid value from affecting the ModelState and revert to using a default value, presumably the best thing to do here is create a new attribute that will need to be baked into code that deals with validation? Either that or I think I need to define my own way of dealing with binding values, is this a possibility?

**Comment by Matthew-Bonner** [comment]
Just to add to this, I can work around the issue using custom model binding but this is an ugly solution. I would have expected this to be out of the box functionality so I think this is a bug.

**Comment by Matthew-Bonner** [comment]
There is an option to prevent binding undefined values in the MvcOptions for v2.1:
SuppressBindingUndefinedValueToEnumType

But what I would like is for this to be expanded so that there is also the option:
BindEmptyValueToEnumType

Which, if set to true, will bind an empty value to the first value in the enum.

Can you confirm whether you like this idea or not, if you do I will submit a PR.

**Comment by Matthew-Bonner** [comment]
Also note that there is an `AllowEmptyInputInBodyModelBinding`, so an equivalent `AllowEmptyInputInQueryStringModelBinding` might suffice.

**Comment by Matthew-Bonner** [comment]
I can see by the following line that there is a check to see if the type is nullable or not, and if the type is nullable then the error is not added to the model state:
https://github.com/aspnet/Mvc/blob/c922b0b90dc95407e1f59510f953d220442f96a1/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/SimpleTypeModelBinder.cs#L141

But as I said earlier, this is not desirable on a large codebase.

Again, another alternative is to do something like the following in the controller:
`ImageFormat imageFormat = model.OutputFormat ?? ImageFormat.Png;`

But I don't want to have to do that either, as I'm looking for an option that can provide a consistent way to allow empty query string argument values just like if the type was a string.

Other non-nullable types such as int have the same problem.

For instance `?width=` causes a problem, but with baked in support for a default value we could avoid any issues.

Maybe what is needed is support for a default value for nullable types so that if the value is not set we can avoid everything blowing up.

So this is what I propose:

    public class ImageViewModel
    {
            public string Id { get; set; }
            [DefaultWhenEmpty(ImageFormat.Png)]
            public ImageFormat OutputFormat { get; set; }
            [DefaultWhenEmpty(0)]
            public int Width { get; set; }
    }

**Comment by mkArtakMSFT** [comment]
Hi @Matthew-Bonner. The behavior you're observing is by-design. And it seems you've found the right way to do it. We haven't seen much demand for the scenario you're describing, so we do not think adding a specific feature for it is necessary.
