### ISSUE TITLE
Can I submit tag helpers for "readonly" and "disabled" attributes?

### ISSUE THREAD

**Issue by robertmiles3** [aspnet/Mvc#7333]
Is it acceptable for me to put in a PR for a couple new tag helpers? I have written custom ones locally to handle `readonly` and `disabled` tags on elements. I think these would be widely used and helpful for many people if we had `asp-readonly` and `asp-disabled` helpers.

Currently, the following will NOT work as it outputs an empty `disabled` attribute (which is valid for disabling):

    disabled="@(someBool ? "disabled" : "")"

However, this *does* work fine and does *not* output any `disabled` attribute:
    
    disabled="@(someBool ? "disabled" : null)"

IMHO, it would be a better developer experience if we (a) did *not* have to use the longwinded ternary operator and (b) did *not* have to remember to use `null` instead of `""`. Instead, it would be great to have something like (that I have written locally)...

    asp-disabled="someBool"

If this is good, let me know, and I'll put in a PR.

**Comment by Eilon** [comment]
I think all you have to do for minimizable properties is set `disabled="@isDisabed"` and Razor does the right thing, no? I thought it's smart with `bool` values and if it's `false` it omits the attribute entirely, and if it's `true` is sets it to `foo="foo"`?

**Comment by robertmiles3** [comment]
Wow, just tested, and you're right. TIL something new. Sweet, closing this (and deleting my tag helpers). Carry on...

**Comment by Eilon** [comment]
Awesome! 😄

**Comment by robertmiles3** [comment]
@Eilon On a similar note, what about a `asp-roles-include` and `asp-roles-exclude`? I wrote this up locally also, and it has served well. Of course, you might surprise me and say there's already a built-in way.

**Comment by Eilon** [comment]
@robertmiles3 do they conditionally show/hide an HTML element based on the role(s) the user is in? I think it's been considered before and we didn't feel it was a high enough value, mostly because it's not too different from a regular `@if(...)` statement. We had a discussion on this a while back in this issue: https://github.com/aspnet/Mvc/issues/6750

But, feel free to log a new suggestion if you have any specific thoughts.

**Comment by robertmiles3** [comment]
Yes, they operate like that. I actually took the existing `environment` tag helper and reworked it for roles. IMO, I would rather see something like this in certain scenarios rather than curly braces everywhere which also annoy my layout OCD, haha.

But, I understand. Just thought I'd throw it out there in case it was deemed useful.

**Comment by Eilon** [comment]
Understood, thanks!
