### ISSUE TITLE
Binding with [FromBody] results in model being null when JSON grows

### ISSUE THREAD

**Issue by hmelis** [aspnet/Mvc#7334]
I'm having an issue where code that works without problems suddenly stops working when the POSTed JSON reaches a certain size (I haven't been able to determine the exact size due to time constraints).

The setup is a Web API with client apps POSTing JSON.

The controller method is defined as
```
[Route("Create")]
[HttpPost]
public IActionResult CreateShipment([FromBody] CreateShipmentRequest request)
```
The model consists of some global info and then a list of objects for each item in a shipment. When that list consists of 20 items, everything is fine. For a larger shipment (nearly 600 items), the model is null and the ModelState is invalid.

I have attached a TraceWriter to the JSON serializer but it gives me no output at all for the large shipment. So basically, nothing indicates an error or exception of some kind. It's like there is no JSON at all. Using Wireshark, I have determined that the JSON is sent to the Web API.

The strange thing is that if I add the following code to Startup.cs Configure(), it suddenly starts working for the large shipment:
```
app.Use(async (context, next) =>
{
    var requestBodyStream = new MemoryStream();
    var originalRequestBody = context.Request.Body;

    await context.Request.Body.CopyToAsync(requestBodyStream);
    requestBodyStream.Seek(0, SeekOrigin.Begin);

    context.Request.Body = requestBodyStream;

    await next.Invoke();
    context.Request.Body = originalRequestBody;
});
```
I have also attached the incoming HTTP request: [request.txt](https://github.com/aspnet/Mvc/files/1702541/request.txt)

**Comment by mkArtakMSFT** [comment]
Hi @hmelis. Can you please check the exceptions in the items of the `ModelState` object. You should see some exception there which would be the reason for the failure you're observing.
Most probably you're hitting the request size limit. If so, we're planning to fix this in the next release of ASP.NET Core.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
