### ISSUE TITLE
Is model validation attributes ordered?

### ISSUE THREAD

**Issue by WHATSAF** [aspnet/Mvc#7335]
I want to know the sequence of the validation.
For instance:
```
[Phone]
[StringLength(13)]
public string PhoneNumber{get;set;}
```
And the `PhoneNumber` get a value `"abc"`. 
As i known, the attributes execution is randomized. So if it'll validate whether the PhoneNumber is a Phone, or validate the PhoneNumber's length equal 13 first?

**Comment by mkArtakMSFT** [comment]
Hi @WHATSAF. There is no mechanism to order validation based on these attributes. The only thing we do is that we try to validate the properties with `RequiredAttribute` attributes applied.
