### ISSUE TITLE
How to validate serialized JSON String

### ISSUE THREAD

**Issue by markusvt** [aspnet/Mvc#7336]
I got a model "Hersteller", that contains a List of objects "IEnumerable<Rabatt>".
The class "Rabatt" looks like this:
```
public class Rabatt
{
  public String Name { get; set; }
  public double Value { get; set; }
}
```

On the client, there is a jquery-based list that the user can extend on his own and fill the Name and Value attributes. Before the submit of the pages, that list ist serialized into a hidden-field, that is marked as the following:
`<input type="hidden" class="rabatteHidden" asp-for="@Model.RabatteString" value="" />`

When the data is posted to the server, i want to validate that that serialized string contains valid data, like "the Name must not be empty" and "the Value must be a Number".
For that I created a custom Validator

```
 public class RabattListValidator : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            String rabattString = (string)value;
            try
            {
                var Rabatte = Json.deserialize<IEnumerable<Rabatt>>(rabattString);
                if(Rabatte.Any(r => String.IsNullOrWhiteSpace(r.Name)))
                {
                    return new ValidationResult("Für alle Rabatte muss ein Name angegeben sein.");
                }
            }
            catch (Exception)
            {
                return new ValidationResult("Es müssen korrekt formatierte Werte der Form 0,00 für alle angegebenen Rabatte angegeben werden");
            }

            return ValidationResult.Success;
        }
    }
```

And in the "Hersteller" class I got the following:
```
        [NotMapped]
        [RabattListValidator(ErrorMessage = "Rabatte müssen korrekt formatiert sein")]
        public String RabatteString
        {
            get { return Json.serialize(Rabatte); }
            set
            {
                Rabatte = Json.deserialize<IEnumerable<Rabatt>>(value);
            }
        }

        [NotMapped]
        public IEnumerable<Rabatt> Rabatte
        {
            get; set;
        }
```

My problem now is: when the posted data contains invalid data in the form, that the Value is not a number but e.g. an empty string, my validator does not work. I get an Exception that says, that the value could not be converted into a double. But my validator was supposed to prevent that kind of exception. 
If I enter a correct number but omit the name, my validator works as expected. So i assume during model binding, the value of the "RabattString" is first put into the model and then that value is validated. 

Can you tell me what I did wrong or how to improve it? Is there a way to validate the posted JSON String before it is put into the model?

**Comment by gortok** [comment]
It sounds like you want a custom model binder, not a validator?

**Comment by markusvt** [comment]
Hmm the model-binding works for well-formed data pretty well: the string ist put into the model and the model deserializes it. Just the validation doesn't work. 
Do you think a custom model binder would solve this issue?

**Comment by mkArtakMSFT** [comment]
Hi @markusvt.
Why are you trying to transfer data as string? Why don't you just allow `Rabbat` type parameters to be auto-bound using the `FromBodyAttribute` attribute?

**Comment by markusvt** [comment]
I got a pretty complex formular there. The entity "Hersteller" I want to update is pretty complex with several direct properties and also mutliple lists of other objects, like that IEnumerable<Rabatt>. 

Right now in the controller I just use  
```bool rslt = await TryUpdateModelAsync<Hersteller>(b);```
where b is the entity.

At some point in the past I figured out it worked pretty well to just set a Json-Serialized String of an object-list (in this case the "RabatteString" property)

But in either case, I think even if I would change the binding of that attribute, the validation problem still stays no? If there is no correct formated number put in the Value  part of the Rabatt, then there will be an exception when trying to deserialize that.

**Comment by mkArtakMSFT** [comment]
@markusvt, the way validation works is that model binding happens first, and then the validation works over already bound model.
Is your expectation here is to get a default value (0) in case of an empty string, rather than an error? Try to change the type of the `Value` property to `double?`.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
