### ISSUE TITLE
TagHelper asp-page produce unwanted "page=" in url

### ISSUE THREAD

**Issue by ckams** [aspnet/Mvc#7337]
According to [the documentation][1],  I only have to write something like this:

    <a asp-page="/Index">Home</a>

For getting this:

    <a href="/Index">Home</a>

But when I try, I get this:

    href="/?page=%2FIndex"

My route:

    routes.MapRoute
    (
        name: "areas",
        template: "{area:exists}/{controller=Home}/{action=Index}/{id?}"
    );

  [1]: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper#asp-page

**Comment by pranavkm** [comment]
Do you have a Razor Page at `/Pages/Index.cshtml`? The `asp-page` attribute is specifically meant for Razor Pages.

**Comment by ckams** [comment]
No there is no such page.

**Comment by pranavkm** [comment]
Like the doc says, the `asp-page` is specifically designed for Razor Pages. If your application only has controllers and actions, you'd need to use [`asp-controller`](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper#asp-controller) and [`asp-action`](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper#asp-action). 

In your case, you'd likely want `asp-action="Index"`

**Comment by ckams** [comment]
Wait, when you write "/Pages/Index.cshtml" you mean exactly `/Pages/Index.cshtml` (what I understood) or any page that matches this 'pattern' like `/Customers/Index`?
Because I do have pages like these, for example `/Customers/Index`…

**Comment by pranavkm** [comment]
> @pranavkm Wait, when you write "/Pages/Index.cshtml" you mean exactly /Pages/Index.cshtml

Yes. `asp-page` takes the page name which is derived from the path. For instance, 
 the page name for the file at `Pages/Customers/Index.cshtml` is `/Customers/Index`. Link generation looked for a file at `Pages/Index.cshtml` and could not find it. It then treats it as an ordinary route value which results in it being appended to the url. You'll see similar behavior if you do `asp-controller="NotExistent"` for instance.

**Comment by ckams** [comment]
Okay, as [this part](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper#asp-page) is in MVC's doc, I thought that was mean Razor syntax… not Razor page.

Off topic, why Razor Page doc is inside MVC's doc, as Razor is not MVC but much more like MVVM?

Anyway thanks.

**Comment by davidfowl** [comment]
Razor Pages is part of the MVC framework ( as strange as that sounds)
