### ISSUE TITLE
@Html.DisplayFor dramatically increases rendering time of razor pages

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#7340]
This has been discovered as part of an experiment @rynowak did while investigating https://github.com/aspnet/Mvc/issues/6111.

**Comment by Eilon** [comment]
Reduces or increases? If it reduces, isn't that a good thing?

**Comment by mkArtakMSFT** [comment]
Fixed!

**Comment by mkArtakMSFT** [comment]
Closing as the decision is to track only this work as part of the original issue: https://github.com/aspnet/Mvc/issues/6111

**Comment by dougbu** [comment]
@mkArtakMSFT should this bug be marked as a `duplicate`?

And, just to be clear, was your "Fixed!" [comment](https://github.com/aspnet/Mvc/issues/7340#issuecomment-364576011) somewhat sarcastic?

**Comment by Eilon** [comment]
"Fixed" was in reference to my comment about the incorrect title.

Don't really care what labels are on bugs that weren't 3-Done.
