### ISSUE TITLE
HTTP response code 404 output Cache-Control header

### ISSUE THREAD

**Issue by tangdf** [aspnet/Mvc#7341]
Demo code:
```csharp
    public class HomeController : Controller
    {
        [ResponseCache(Duration = 60 * 60)]
        public IActionResult Index()
        {
            return NotFound();
        }
}
```

https://github.com/aspnet/Mvc/blob/aeab6e295efdc0b1d89c375b62a84fe3b6ba969e/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResponseCacheFilter.cs#L165-L175

The HTTP response code is 404( or 401 ), also output cache header  `Cache-Control: public,max-age=3600`.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. We're going to consider this in one of our future releases.

**Comment by tangdf** [comment]
When the database crashes, the index page will always display errors in 60 seconds.

```C#
    [CustomExceptionFilter]
    public class HomeController : Controller
    {
        [ResponseCache(Duration = 60)]
        public IActionResult Index()
        {
            SqlConnectionStringBuilder sqlConnectionStringBuilder = new SqlConnectionStringBuilder
            {
                DataSource = "***",
                UserID = "sa",
                Password = "***",
                InitialCatalog = "tempdb"
            };
            using (SqlConnection sqlConnection = new SqlConnection(sqlConnectionStringBuilder.ConnectionString))
            {
                sqlConnection.Open();
                using (SqlCommand sqlCommand = new SqlCommand("select getdate()", sqlConnection))
                {
                    DateTime dateTime = (DateTime)sqlCommand.ExecuteScalar();
                    ViewData["Time"] = dateTime;
                }
            }

            return View();
        }
    }

    public class CustomExceptionFilterAttribute : ExceptionFilterAttribute
    {
        public override void OnException(ExceptionContext context)
        {
            context.Result = new RedirectResult("home/error");
        }
    }
```

**Comment by pranavkm** [comment]
You could call `context.HttpContext.Response.Clear()` in your exception filter prior to setting the result. That would match what the ExceptionHandlerMiddlware does: https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L71. Another suggestion - if you aren't doing particularly interesting in the filter besides redirecting, you could let the ExceptionHandlerMiddleware - `app.UseExceptionHandler("/HomeError")` - handle this for you.

**Comment by tangdf** [comment]
I insist that the results should be cached only if the response is 200.

https://github.com/aspnet/Mvc/blob/c09575dbd0aa9c27aaa5617335ecb35c3d5706fe/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResponseCacheFilterExecutor.cs#L127-L131


The above code should be changed to the following:

```c#
                cacheControlValue = $"{cacheControlValue}max-age={Duration}";

                Task OutputCacheHeader(object state)
                {
                    HttpContext c = (HttpContext)state;
                    if (c.Response.StatusCode == 200)
                        c.Response.Headers[HeaderNames.CacheControl] = cacheControlValue;
                    return Task.CompletedTask;
                }

                context.HttpContext.Response.OnStarting(OutputCacheHeader, context.HttpContext);
```

**Comment by khellang** [comment]
I think this is an issue with the exception filter rather than the response cache. There's a reason the exception handler middleware clears the response.

It even has an `OnStarting` callback to clear caching headers; https://github.com/aspnet/Diagnostics/blob/8dce01f654962580e22e7c96ad4f313574407a40/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L108-L113, so why shouldn't the exception filter do the same?

**Comment by tangdf** [comment]
Ok, I've got it.

**Comment by khellang** [comment]
Just to be clear; I didn't mean there's anything wrong with *your* exception filter - I think this is a framework concern. MVC shouldn't allow resources produced with an exception filter to be cached.
