### ISSUE TITLE
ApiController should not return errors as application/problem+json

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#7344]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/ApiBehaviorOptionsSetup.cs#L39

We missed this during cleanup. We're not using problem anywhere in MVC's code, so this is wrong. Put another way... we don't assume that you want to use problem, and we don't wire it up for you.

**Comment by pranavkm** [comment]
@mkArtakMSFT \ @danroth27 could we triage this for preview2? It's a small cleanup

**Comment by mkArtakMSFT** [comment]
@jbagga, can you please handle this? Thanks!
