### ISSUE TITLE
`RazorPagesOptions.RootDirectory` is (confusingly) used for two purposes

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7345]
The `RootDirectory` option controls both the root folder for pages not in an area and the relative folder for pages within an area-specific folder. The documentation for `RootFolder` doesn't cover this though the `AllowAreas` doc comments do mention the odd `<c>/{AreaRootDirectory}/AreaName/{RootDirectory}/</c>` folder choice.

For example, after changing `RootFolder` to `/`, I needed to move all pages within the `/Pages` folder up one level. But, unexpectedly, I needed to also move `/Areas/MyArea/Pages/*.*` up to `/Areas/MyArea`.

Should have a separate option for the `AreaRootDirectory`-relative folder containing area-specific pages.

----
One alternative would be to remove or deprecate the `RazorPagesOptions.RootDirectory` and `RazorPagesOptions.AreaRootDirectory` properties. Then, recommend setting the formats directly in `RazorViewEngineOptions`. Could provide `RazorViewEngineOptions` extension methods to make that easier.

**Comment by pranavkm** [comment]
This can be closed now. We no longer use this property to calculate the Pages directory under `Areas`. See https://github.com/aspnet/Mvc/issues/7608
