### ISSUE TITLE
Setting `RazorPagesOptions.AreaRootDirectory` and `RootDirectory` to same folder breaks all searches

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7347]
Change `Startup.ConfigureServices(...)` to include
``` c#
            services
                .AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
                .AddRazorPagesOptions(options =>
                {
                    options.AreaRootDirectory = "/";
                    options.RootDirectory = "/";
                });
```

Expected: At worst, some confusing between area-specific and non-area pages. 
Actual: 404s for all pages, even full paths such as https://localhost:44312/About or https://localhost:44312/MyArea/Index

**Comment by dougbu** [comment]
Problem may be more general. 404s seem to be the new norm when only `AreaRootDirectory` is changed to `/`. In that case i.e. with `RootDirectory` set to its `/Pages` default, all page searches fail whether looking for an area-specific page or not.

**Comment by pranavkm** [comment]
We specifically disallow files that are under the area route to be reachable via their non-area route. They should however be routeable if they are located in `/[AreaName]/[FileName].cshtml`. What's the path of the files on disk?

**Comment by dougbu** [comment]
With the configuration shown above,
```
root / About.cshtml
          Contact.cshtml
          Index.cshtml
          MyArea / About.cshtml
                          Contact.cshtml
                           Index.cshtml
          Shared / *
```
And, nothing is routable.

**Comment by pranavkm** [comment]
As part of addressing https://github.com/aspnet/Mvc/issues/7608, we removed the option to modify the AreaPagesRoot. This is no longer a valid scenario.
