### ISSUE TITLE
Setting `RazorPagesOptions.AllowAreas` to `false` does not disable area pages

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7348]
Change `Startup.ConfigureServices` to include
``` c#
            services
                .AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_0)
                .AddRazorPagesOptions(options =>
                {
                    options.AllowAreas = false;
                });
```

Expected: All area-related pages result in 404s.
Actual: See the usual content of pages such as https://localhost:44312/Identity/Account/Manage or https://localhost:44312/MyArea

Note either `CompatibilityVersion.Version_2_0` or `AllowAreas == false` should have been sufficient to disable areas.

**Comment by pranavkm** [comment]
Is this specifically with pages from a precompiled class library? I can't reproduce this with files on disk.

**Comment by dougbu** [comment]
No, problem wasn't specific to area pages in a library. I also cleaned and rebuilt my solution a few times to ensure I wasn't testing older code. Then again, my test app does use area pages from a library -- the Identity.UI pages in particular.

Which SDK build are you testing with? I'm using 2.1.300-preview1-008117.

I'll test this again with 2.1.300-preview1-008123 later today.

**Comment by dougbu** [comment]
Turns out the problem was my `Startup` calls `IdentityBuilder.AddDefaultUI()`. This has the unexpected behaviour of enabling a `IPostConfigureOptions<RazorPagesOptions>` implementation (`IdentityDefaultUIConfigureOptions<{IdentityUserType}>`) which **overrides** this user's `RazorPagesOptions.AllowAreas` setting.

Side note: That configuration setup also overrides user `StaticFileOptions.FileProvider` settings. Fortunately, other options properties set in `IdentityDefaultUIConfigureOptions<{IdentityUserType}>` seem to be additive.

Will move this issue to the Identity repo.

**Comment by mkArtakMSFT** [comment]
@dougbu, can you please confirm this is not the case for usual (local) views? /cc @javiercn

**Comment by dougbu** [comment]
This issue was moved to aspnet/Identity#1626
