### ISSUE TITLE
Do not require `pageName` parameters to start with a '/'

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7349]
`pageName` parameters in `PageConventionCollection` extension methods are documented as *relative* paths. Though the examples show leading slashes, it's unexpected that this extra character is required.

e.g.
```
An error occurred while starting the application.
ArgumentException: 'Contact' is not a valid page name. A page name is path relative to the Razor Pages root directory that starts with a leading forward slash ('/') and does not contain the file extension e.g "/Users/Edit".
Parameter name: pageName
Microsoft.AspNetCore.Mvc.ApplicationModels.PageConventionCollection.EnsureValidPageName(string pageName)

ArgumentException: 'Contact' is not a valid page name. A page name is path relative to the Razor Pages root directory that starts with a leading forward slash ('/') and does not contain the file extension e.g "/Users/Edit".
 Parameter name: pageName
Microsoft.AspNetCore.Mvc.ApplicationModels.PageConventionCollection.EnsureValidPageName(string pageName)
Microsoft.AspNetCore.Mvc.ApplicationModels.PageConventionCollection.AddAreaPageRouteModelConvention(string areaName, string pageName, Action<PageRouteModel> action)
Microsoft.Extensions.DependencyInjection.PageConventionCollectionExtensions.AddAreaPageRoute(PageConventionCollection conventions, string areaName, string pageName, string route)
Pages.areas._207.Startup+<>c.<ConfigureServices>b__4_3(RazorPagesOptions options) in Startup.cs
-
            services
                .AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_0)
                .AddRazorPagesOptions(options =>
                {
                    options.AllowAreas = false;
                    options.Conventions
                        .AddAreaPageRoute(areaName: "MyArea", pageName: "Contact", route: "/MyContact")
                        .AuthorizeAreaPage(areaName: "MyArea", pageName: "Contact");
                });
        }
        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
...
```

**Comment by rynowak** [comment]
We should improve the documentation. This is intended. Page names can appear in lots of places, and in some of them the leading `/` is semantically significant.

**Comment by mkArtakMSFT** [comment]
@dougbu, the example here does show the leading slash: https://github.com/aspnet/Mvc/blob/dbff416be60ad6accccb4afa33785e7db660152e/src/Microsoft.AspNetCore.Mvc.RazorPages/DependencyInjection/PageConventionCollectionExtensions.cs#L90-L96

Do you expect another line explicitly stating that it's required?

**Comment by dougbu** [comment]
@mkArtakMSFT I expect either the property setter would auto-add the leading slash when it's missing or the requirements would be clear in the doc comments. An example is not the same thing as a specified requirement.

Might also be clearer if the setter threw an `ArgumentException` rather than waiting 'til the convention sees the issue.

**Comment by Eilon** [comment]
Property setters should not munge data. Allow valid input; throw on invalid input. The user needs to fix their code.

**Comment by dougbu** [comment]
@Eilon I'm fine with non-munging (though we at least a few setters that munch `null` into `string.Empty`). Do you mean (a) change nothing or (b) add an `ArgumentException` in this setter?

**Comment by Eilon** [comment]
I just mean "should;" there are no absolutes (aside from this absolute!). null/empty-string is a trivial case, so not worried about that. This sounds like a case for throwing. No opinions on when/where it should throw.

**Comment by mkArtakMSFT** [comment]
Closing as by-design.
