### ISSUE TITLE
`[BindProperty]` does not work on controller classes

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7350]
The [ASP.NET Core 2.1 Roadmap](https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/#mvc) mentions placing `[BindProperty]` on a controller class will bind all properties in the controller. This is not the case.

For example, with
``` c#
public class VController : Controller
{
    [BindProperty(SupportsGet = false)]
    public string FirstName { get; set; } = "John";

    [BindProperty(SupportsGet = false)]
    public string LastName { get; set; } = "Smith";

    // ...
}
```
both `FirstName` and `LastName` are model bound. With
``` c#
[BindProperty(SupportsGet = false)]
public class VController : Controller
{
    public string FirstName { get; set; } = "John";

    public string LastName { get; set; } = "Smith";

    // ...
}
```
neither property is bound.

**Comment by mkArtakMSFT** [comment]
@pranavkm, what are your thoughts about this one? Did we ever implemented this, or not?

**Comment by pranavkm** [comment]
Yup, this is an issue. We could put this off until RC since a fix should not involve any new types \ APIs.

**Comment by mkArtakMSFT** [comment]
Thanks guys. All yours, @pranavkm.

**Comment by tebrizetayi** [comment]
Is it ready? Because I have debugged many times this issue, but there are no changes.I would like to contribute to this issue.

**Comment by mkArtakMSFT** [comment]
HI @tebrizetayi. We need to evaluate this again, as some changes have been made in this area. So you'll first need to confirm that this is still the case. If so, sure we will gladly consider your PR. @pranavkm, please don't start this work yet.

**Comment by tebrizetayi** [comment]
[BindProperty(SupportsGet = false)]
    public class HomeController : Controller
    {
        public string Name { get; set; }
        public int Age { get; set; }
    }
     [HttpPost]
     public IActionResult Post()
     {
          return View();
     }
    <form asp-action="Post" asp-controller="Home" method="post">
    <input name="Name" type="text" />
    <input name="Age" type="text" />
    <input type="submit" />
    </form>

After posting the form, the Age equals to 0  and Name equals to null.

**Comment by pranavkm** [comment]
I looked at this and `ModelMetadata` changes (https://github.com/aspnet/Mvc/commit/c515cece8ed8a39b8163c3ba35024bcc79716ca0) didn't address this. We'll need to make a specific change for this.
