### ISSUE TITLE
Question: Why are `[BindProperty]` and `[BindNever]` in different namespaces?

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7351]
I suspect we can do nothing about this for back-compatibility reasons. But, it's strange `[BindProperty]` is in the Microsoft.AspNetCore.Mvc namespace while `[BindNever]` is in Microsoft.AspNetCore.Mvc.ModelBinding.

More generally, the split between the two namespaces leaves Microsoft.AspNetCore.Mvc.ModelBinding under-populated. Attributes in Microsoft.AspNetCore.Mvc include `[Bind]`, `[BindProperty]`, `[FromBody]` (and similar), and `[ModelBinder]`. Attributes in Microsoft.AspNetCore.Mvc.ModelBinding include `[BindingBehavior]`, `[BindNever]`, and `[BindRequired]`.

**Comment by Eilon** [comment]
What do you suggest be done?

**Comment by dougbu** [comment]
It was a question. But, if the answer is "dunno" or "ooops" and not "shrug" or "by design", I suggest we add new attributes in the Microsoft.AspNetCore.Mvc namespace that work like `[BindingBehavior]`, `[BindNever]`, and `[BindRequired]`. The new attributes would also different names e.g. `[BindBehavior]`, `[BindingNever]` and `[BindingRequired]`.

**Comment by mkArtakMSFT** [comment]
Those attributes are already released. Can't simply change it now.
