### ISSUE TITLE
Add tests for `[BindingBehavior]` applied to page model properties

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7353]
Found while verifying #6811.

Though `IsBindingAllowed` and `IsBindingRequired` are likely now set correctly in `ModelMetadata` -- as part of the #6790 fixes, `[BindRequired]`, `[BindNever]` and so on do not impact model binding of page model properties.

For example
``` c#
[BindProperty(SupportsGet = false)]
[BindRequired]
public string Required { get; set; }
```
works as expected if the `Required` property is in a controller. But no model error occurs when the same property is in page model. (In both cases, the form does not include an `<input/>` field for `Required`.)

**Comment by dougbu** [comment]
Note this issue basically means #6811 was not fixed.

**Comment by mkArtakMSFT** [comment]
@dougbu, looking through the details of the referenced issue it seems it was closed intentionally, without any action as that was called out as the best approach - to do nothing.
@pranavkm, is this a valid exception, or this should still be acted on so we get to consistency between Controllers and Razor Pages?

**Comment by pranavkm** [comment]
Might be a dup of https://github.com/aspnet/Mvc/issues/7358, although it would be good to verify this and add tests to cover this specific scenario.

**Comment by dougbu** [comment]
#7358 is about `[Validation]` subclasses while this is about `[BindRequired]`. It's still possible fixing #7358 fixed these too. Or, another of our changes in this area may have fixed `[BindRequired]` in page model scenarios.

Should check if these symptoms occur with Preview 2 bits.

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please evaluate whether this is still the case, and whether there is still any action here or not.

**Comment by pranavkm** [comment]
This was addressed as part of https://github.com/aspnet/Mvc/issues/7358. What it does need is a test or two.

**Comment by dougbu** [comment]
a6199bbfba
