### ISSUE TITLE
`[BindProperty(BinderType = typeof(SimpleTypeModelBinder)]` no longer works

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7354]
Though we've added new constructors to most model binders in a backward-compatible fashion, the change actually breaks a scenario. For example, `[BindProperty(BinderType = typeof(SimpleTypeModelBinder)]` and `[ModelBinder(BinderType = typeof(SimpleTypeModelBinder)]` now result in
```
An unhandled exception occurred while processing the request.
InvalidOperationException: Multiple constructors accepting all given argument types have been found in type 'Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinder'. There should only be one applicable constructor.
Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, out ConstructorInfo matchingConstructor, out Nullable<int>[] parameterMap)

Stack Query Cookies Headers
InvalidOperationException: Multiple constructors accepting all given argument types have been found in type 'Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinder'. There should only be one applicable constructor.
Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, out ConstructorInfo matchingConstructor, out Nullable<int>[] parameterMap)
Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinder..ctor(Type binderType)
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
...
```

**Comment by mkArtakMSFT** [comment]
This is an effect of ActivatorUtilities/multiple constructors issue. This specific use-case is not common, so this is a low priority issue.

**Comment by mkArtakMSFT** [comment]
The real fix will be handled by a fix we consider for https://github.com/aspnet/Mvc/issues/7330

**Comment by dougbu** [comment]
@pranavkm I believe I was updating a project I'd used in previous validation rounds when I hit this. But, I don't think I have that test system anymore.

In any case, I'll retry the scenario with `typeof(BodyTypeModelBinder)` and see if I hid an `ActivatorUtilities` issue with that type too.

**Comment by pranavkm** [comment]
A bit of a tangent, but the current solution for disambiguating ctors in `ActivatorUtilities` is to annotate the preferred one with an attribute. If we run in to this sort of scenario frequently enough, we could consider adding a negative preference to ctors with `Obsolete` attribute. That said, so far most of the ctors that we've added generally add additional parameters that come from DI which lends itself to the disambiguation algorithm.

**Comment by mkArtakMSFT** [comment]
Closing this as it seems the underlying issue has been fixed already: https://github.com/aspnet/Home/issues/2871
