### ISSUE TITLE
`[BindProperty(Name = "...")]` property has unexpected impact if on page model class

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7355]
For example,
```
[BindProperty(Name = "the")]
public class IndexModel : PageModel
{
    public string FirstName { get; set; } = "John";
}
```
The `FirstName` property is bound to a ~~`firstname`~~ `the` field. ~~Neither `the` nor~~ `the.firstname` field~~s~~ will not bind to this property. That is, the class-level `Name` is not used as a prefix. A prefix is what I expected.

The `Name` property *does* work fine when the `[BindProperty]` (or `[Bind]` &hellip;) attribute is associated with a page model property. The problem is specific to specifying the `Name` on the class.

**Comment by dougbu** [comment]
Think my application had not completely rebuilt after I added the `Name` attribute. In the scenario shown above, `FirstName` is bound to a field named `the`. There is still some confusion e.g.
``` c#
[BindProperty(Name = "the", SupportsGet = false)]
public class IndexModel : PageModel
{
    public string FirstName { get; set; } = "John";

    [BindProperty(SupportsGet = true)]
    public string LastName { get; set; } = "Smith";

    // ...
}
```
Though the `LastName` property does *not* have an override of the `Name` , it is bound to the `lastname` field.

It's also a surprising that the class-level `Name` is the default model name for all fields in the page model, not a prefix. Basically, users should only specify `Name` at the class level if the page model only contains one property.

Updating the bug title&hellip;

**Comment by dougbu** [comment]
The general issue is `IModelNameProvider`, `IBinderTypeProviderMetadata`, and so on implementations on a property always override an implementation on the containing type, even when the `Name`, `BinderType` or whatever property value is `null`. It's great that users can override a class-level attribute but ugly this happens implicitly, especially with `[BindProperty]` because that implements a fair number of metadata interfaces.

For example, the following page model
``` c#
[BindProperty(BinderType = typeof(RandomModelBinder)]
public class IndexModel : PageModel
{
    public string FirstName { get; set; }

    [BindProperty]
    public string LastName { get; set; }

    [ModelBinder(Name = "Name")]
    public string FullName { get; set; }

    // ...
}
```
Will use the `RandomModelBinder` when binding the `FirstName` field but the default (likely `SimpleTypeModelBinder`) model binder for `LastName` and `FullName`.

**Comment by dougbu** [comment]
Another oddity:
``` c#
[BindProperty(SupportsGet = true)]
public class IndexModel : PageModel
{
    public string FirstName { get; set; } = "John";

    [BindProperty(BinderType = typeof(RandomModelBinder))]
    public string LastName { get; set; } = "Smith";

    // ...
}
```
The `LastName` property will *not* support GET requests. However if the applied attribute is instead `[BindProperty(BinderType = typeof(RandomModelBinder))]`, `LastName` will support GET requests. IOW, the two ways of specifying the binder type have unexpectedly different semantics.

**Comment by mkArtakMSFT** [comment]
@dougbu, can you please render a table of scenarios which are broken? It's a bit scattered now. Thanks!

**Comment by dougbu** [comment]
I'm not sure of the current behaviour since we made significant changes in this area during Preview 2. But, the Preview 1 behaviour was something like:

| | no page model attribute | `[BindProperty]` on page model | `[BindProperty(Name = "the")]` on page model |
| ---- | ---------------------- | ----------------------------------- | ----------------------------------- |
| no property attribute | binds to "firstName" field | binds to "firstName" field | binds to "the" field |
| `[BindProperty]` on property | binds to "firstName" field | binds to "firstName" field | binds to "firstName" field |
| `[BindProperty(Name = "prop")]` on property | binds to "prop" field | binds to "prop" field | binds to "prop" field |

Table looks stranger when using a different property at one level or the other: Behaves like the `[BindProperty]` row or column w.r.t. whatever isn't specified.

Summarizing:
- Even default values of the `[BindProperty]` (`false`, `null`, &hellip;) on a property override what was specified on the containing class
  - I expected properties of the two `[BindProperty]` attributes to be merged
- `Name` value of `[BindProperty]` on page model class is a very odd default for the field name of _all_ properties in that class
  - I expected this value to be used as a prefix for names (explicit or not) of fields corresponding to the contained properties
  - changing the name of fields for every property doesn't make much sense

**Comment by mkArtakMSFT** [comment]
@dougbu, having the `Name` value to act as a prefix isn't intuitive and would most likely introduce more confusion. 
@danroth27 and I discussed this and feel like having `Name` property specified on class-level `BindProperty` attribute is odd. What about having an analyzer to result in at least warnings in those situations?
@DamianEdwards what do you think?

**Comment by dougbu** [comment]
> having the `Name` value to act as a prefix isn't intuitive

:ok: though we have other `Name` values in binding attributes that act as prefixes. For example, `BindAttribute.Name` is `public` but `readonly`; it's set using a `Prefix` property.
> What about having an analyzer to result in at least warnings in those situations?

That WFM

**Comment by pranavkm** [comment]
I think this can be closed. `BindProperty` no longer applies to types.

**Comment by mkArtakMSFT** [comment]
Closing as this is obsolete already.
