### ISSUE TITLE
Consider marking RequireHttpsAttribute as obsolete

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7359]
We recommend that you do HTTPS redirection for the whole application using the HTTPS redirection middleware instead. This has the advantage that it works across multiple environments and detects the appropiate ports automatically in the most common cases during development and production.

The scenario where only part of your app is HTTPS is still supported (although discouraged) by using the middleware as a filter.

We should consider a new attribute for libraries [Https] or [EnforceHttps] that allows an endpoint to be marked as requiring HTTPS and produce a 400 response when called by HTTP. This will allow libraries to create endpoints and have a strong guarantee that the endpoints they expose will not be called under HTTP.

**Comment by Eilon** [comment]
Some thoughts/questions for the sake of discussion:
1. Are there any scenarios where `RequireHttpsAttribute` still makes sense?
2. Exactly what would the obsolete message say? (I.e. what's the replacement API?)
3. I like the idea of the new attribute that is proposed - can you log a separate bug for that?

**Comment by mkArtakMSFT** [comment]
Thinking about static resources - what is the benefit of having things like images to transferred over HTTPS? @javiercn, @Eilon

**Comment by Eilon** [comment]
To ensure they came from the origin you expect, that they haven't been tampered with, and to prevent eavesdropping. Same as for any other HTTPS scenario.

**Comment by javiercn** [comment]
Pretty much what @Eilon mentioned. Some concrete examples:
* If you serve a script over HTTP on an HTTPS origin, it will not execute (it's what is called active content)
  * If for some reason the script were to execute, I would be able to evaluate random code on your web page, which means everything else useless.
 * Some wireless endpoints have been know to use proxies to inject content on the pages you visit.
* If you serve images or other content over HTTP I can replace those images with adds or similar things.

**Comment by mkArtakMSFT** [comment]
Let's have this around for now. We can come back to this in the future.

**Comment by mkArtakMSFT** [comment]
Closed as we don't want to break anyone here. So we'll continue with having the `RequireHttpsAttribute` attribute as is.
