### ISSUE TITLE
`[Required]` rarely detects errors in top-level nodes

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7360]
`[Required]` on top-level nodes works with `string` and few other types. This goes beyond `ValueType`s, the usual `[Required]` / `[BindRequired]` discussion point. (That part's inherent in `[Required]`'s semantics.) `[Required]` also does not catch the expected errors on pretty much any collection or complex type if it's a top-level node.

Consider the following action and a `<form>` containing no `<input/>` fields:
``` c#
[HttpPost("/Ints")]
public IActionResult Ints([Required] int[] ints)
{
    // ...
}
```
In this scenario, `ModelState.IsValid` will always be `true`.

Because `ints` is an action parameter, model binding considers it a top-level node and provides a non-`null` default value. In this case, the default value is an empty array. Importantly, this default is chosen *before* validation. So `[Required]` is passed the empty array and sees nothing amiss.

One possibility would be to move our `IsTopLevelNode` special cases out of model binding and into `ParameterBinder` and other model binding callers. This would allow providing default values after validation.

**Comment by mkArtakMSFT** [comment]
Hi @dougbu. Will this behavior repro for not only `int[]` but any other arrays/objects too?
In other words, will this also always result in `ModelState.IsValid` to be true:

```csharp
[HttpPost("/Ints")]
public IActionResult Ints([Required] Customer[] ints)
{
    // ...
}
```

**Comment by dougbu** [comment]
@mkArtakMSFT please see the first paragraph of the description above. `int[]` is just an example.

**Comment by mkArtakMSFT** [comment]
Closing this as this seems to be by-design and changing behavior will be a breaking change, which is undesirable.

**Comment by dougbu** [comment]
Reactivating after a quick confirmation chat w/ @rynowak.

There's no breaking change if we fixed this bug. We haven't previously supported `[Validation]` attributes (including `[Required]`) on a top-level node.

Further, the current behaviour means `[Required]` behaves differently for top-level nodes than for a property further down the model tree. For example,
- When the submitted form has no fields for a `[Required] int[]` (pick your favourite non-`string`, non-value type) parameter, no validation errors are detected
- When the submitted form has no fields for a `[Required] int[]` property, the expected validation errors are added to `ModelState`

**Comment by dougbu** [comment]
@mkArtakMSFT I'm clearing the milestone and assignment to make it clear this should be triaged again.

**Comment by dougbu** [comment]
Clearing the rest of the labels and adding `super-triage`. Believe the idea is to add an MVC analyzer that detects `[Required]` on top-level, non-`string` nodes (parameters and controller or page model properties), perhaps on all parameters and properties that have collection or complex types.

(May make sense to edit the title if I understand the plan.)
## Rationale
`[Required]` on a complex type can only mean "at least one of the properties in this POCO object must have a non-`null` default value or be model bound".  That's not particularly meaningful compared to specifying `[Required]` on the required properties or implementing `IValidatableObject` to ensure the correct property combinations are non-`null`.

`[Required]` on a collection can only mean "this collection must have a non-`null` default value or have at least one model bound entry". Since the default value may be empty, top-level collections are always non-`null`, and `[MinLength(1)]` always succeeds when a property is `null`, this gets pretty confusing pretty quick. Analyzer should recommend using `[MinLength(1)]` on top-level nodes (`[Required]` is irrelevant here) and `[MinLength(1), Required]` elsewhere.
## Separately
Because `[Required]` is meant to be used together with many `ValidationAttribute`s may also be worthwhile recommending adding `[Required]` where a nullable property is missing it but another `ValidationAttribute` exists.

/cc @rynowak @Eilon @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
Closing in favor of https://github.com/aspnet/Mvc/issues/7415, which will track the only outcome from this issue.

**Comment by dougbu** [comment]
In case someone refers to this issue later: Removed the earlier **Separately** section because "optional but, if it exists, &hellip;" validations are just fine.
