### ISSUE TITLE
Dependency Injection for IClientModelValidator

### ISSUE THREAD

**Issue by ExcaliburVT** [aspnet/Mvc#7361]
I realize this is a edge case and perhaps someone can offer an alternative I have not thought of.

Example:

Policy "PrivilegedUser" defined by user having one or more of a set of claims.

Data entry form has field X, Y and Z.  Non-Privileged users are required to enter all 3 but PrivilegedUsers are required only for the first two.

I can create a validation attribute for domain objects that recognizes the policy and acts appropriately since the validationcontext implements GetService.

However i cannot create a client side validator with IClientModelValidator as I have no access to the IAuthorizationService to execute AuthorizeAsync with the user from the HttpContext.  If I could, i could decide to inject data-val-required on the element or not.

-------
Known options:
Duplicate the policy check against the User's claims within the AddValidation method.  This is not optimal as a developer may not know to change multiple locations to update a policy (comments can try to help but we all know that doesn't always work).

Custom required validator that checks a javascript method placed in the Layout that returns true/false for the result of the Policy on the User.  This risks future changes made to unobtrusive validation that are not reflected in the custom method.

Thanks!

**Comment by mkArtakMSFT** [comment]
Hi @ExcaliburVT .
>However i cannot create a client side validator with IClientModelValidator as I have no access to the IAuthorizationService to execute AuthorizeAsync with the user from the HttpContext. If I could, i could decide to inject data-val-required on the element or not.

You can get to `HttpContext` from the AddService method, navigating through the `context` as follows:
```
context.ActionContext.HttpContext
```

From there you can also access the `RequestServices` and have access to anything you have had configured in Startup.

**Comment by ExcaliburVT** [comment]
@mkArtakMSFT Exactly what I was looking for.  Didn't realize it was buried in the HttpContext thank you!
