### ISSUE TITLE
Create a new [Https] attribute that enforces HTTPS on a given endpoint

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7363]
This is useful for libraries that expose endpoints to enforce that HTTPS is used on the environments they are consumed. For example libraries with UI for authentication flows. The attribute (and associated filter) will send back a 400 on incoming HTTP calls and will possibly allow you to configure a callback to know that this is happening (for example to revoke/blacklist disclosed credentials).

**Comment by mkArtakMSFT** [comment]
EnforceHttpsAttribute will be an option...

**Comment by mkArtakMSFT** [comment]
Closing this at the moment, as there doesn't seem yet any customer need. We'll reconsider this, if we'll see customers asking for it.
