### ISSUE TITLE
Attribute Routing: Come up with a good scheme for generating route group tokens

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#737]
Attribute routing is based on comparisons of a generated string token that is unique to each group. Right now the generation of these tokens is super naive and uses relatively long strings. We should implement something smarter.

**Comment by yishaigalatzer** [comment]
@rynowak this issue seems obscure, is there a real thing left to do here?

**Comment by rynowak** [comment]
@yishaigalatzer @javiercn I'd suggest we close this item and revisit if/when we look at attribute route perf. If this is a bottleneck, and worth improving, we'll surely reach that conclusion during future perf analysis.
