### ISSUE TITLE
Razor page from class library not found if another cshtml(not razorpage) exists at the same path in the referencing app

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Mvc#7372]
Repro:
- Create a page Foo.cshtml in the class library (With precompilation enabled) which contains `@page "/foo"` at the top of the file
- Create an app referencing the class library and create a regular razor file (not page) Foo.cshtml in the same relative location
- Run the app and go to localhost:5001/foo

Expected:
Finds the page from the class library

Actual:
404

Note: This is not a very common scenario. Just filed this issue for awareness.

**Comment by javiercn** [comment]
This is expected (by design). The contract is that whatever .cshtml file in your app that is at the same path than something compiled in a library wins over it. We don't make any distinction on whether it is a view or a page.
