### ISSUE TITLE
Unable to use method name with `asp-page-handler`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7375]
With a page model containing
``` c#
public class IndexModel : PageModel
{
    public IActionResult OnPost()
    {
        return new NotFoundObjectResult($"Executing unsupported handler '{RouteData.Values["handler"]}'.");
    }

    public IActionResult OnPostIntegrals([MinLength(6), Required] int[] ints)
    {
        // ...
        return Page();
    }
}
```
and a page containing
``` html
<form method="post" asp-page-handler="@nameof(IndexModel.OnPostIntegrals)">
    <input type="submit" value="Save nothing" />
</form>
```
Clicking "Save nothing" causes a 404 response, not execution of the named handler method. This feels very much like the oft-complained-about inability to use `<form method="post" controller="@nameof({ControllerClass})">`. (That one mainly has a back-compatibility rationale.)

Suggest we either change page routing to look for a method matching the `handler` route (or query) value (without prepending `On{HTTP Method}`, then falling back to the current method naming) or change the `<form>` tag helper to trim the start of names beginning with `OnGet`, `OnPost` et cetera.

(Found while playing around with #7362.)

**Comment by Eilon** [comment]
1. Is there something missing from the bug's title?
2. What exactly is the issue here? That the C# identifier doesn't match the `handler` of the `<form>`? That's by design and we really don't like doing fallbacks. Fallbacks are their own source of pain. We just have 1 way to do things and you either do it that way or you customize the system. (Yes, exceptions to this abound, but it's a route we try not to go down.)

**Comment by DamianEdwards** [comment]
Like Eilon says, this is by design. The method name conventions can be changed by folks who feel super strong about them, but these are the defaults.

**Comment by dougbu** [comment]
Could one of you please catch me tomorrow and spell out the rationale for this design? I get the leaning away from fallbacks. I'm not understanding why the system needs to prepend `On{HTTP Method}` to the `handler` route value (only one method is of interest per form).

**Comment by DamianEdwards** [comment]
It was an aesthetic choice more than anything. We looked at a bunch of options during the development of pages and settled on this one, while making the conventions changeable. We said we'd explore adding further pre-defined conventions that folks could choose from if we got strong feedback, but we didn't, so we haven't. I don't see a need to revisit this again.

**Comment by dougbu** [comment]
FYI only: It's relatively simple to change handler names to match method names. For example,
``` c#
public class FullNamePageApplicationModelProvider : IPageApplicationModelProvider
{
    // Must execute after DefaultPageApplicationModelProvider. Otherwise, Order isn't too important.
    public int Order => 0;

    public void OnProvidersExecuting(PageApplicationModelProviderContext context)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        for (var i = 0; i < context.PageApplicationModel.HandlerMethods.Count; i++)
        {
            var handler = context.PageApplicationModel.HandlerMethods[i];

            // Leave simply-named handlers like OnPost() alone.
            if (!string.IsNullOrEmpty(handler.HandlerName))
            {
                // Do *not* trim "On{HTTP method}" from the start or "Async" from the end of the chosen
                // HandlerName, allowing nameof(method) in asp -page-handler attributes.
                handler.HandlerName = handler.MethodInfo.Name;
            }
        }
    }

    public void OnProvidersExecuted(PageApplicationModelProviderContext context)
    {
        // no-op
    }
}
```
