### ISSUE TITLE
Default Model Name

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#7386]
_From @hishamco on February 14, 2018 23:3_

What I see quite often in almost if it's in all the Razor Pages, that we need to specify the model using the `@model`
```html
@page
@model ProductModel
```
for Product.cshtml, and
```html
@page
@model CustomerModel
```
for Customer.cshtml

Can we introduce a new option that allow us to set the model by convention `{PageName}Model` unless we need to use a different name

_Copied from original issue: aspnet/Home#2877_

**Comment by Eilon** [comment]
_From @mkArtakMSFT on February 14, 2018 23:36_

Thanks @hishamco for your proposal. @rynowak this can eliminate the need for the explicit `@model` type definition. Will anything prevent us from supporting this?

**Comment by Eilon** [comment]
_From @mkArtakMSFT on February 14, 2018 23:37_

@DamianEdwards FYI

**Comment by Eilon** [comment]
@mkArtakMSFT can you move to the appropriate repo? Not sure if this is MVC or Razor.

**Comment by Eilon** [comment]
_From @hishamco on February 15, 2018 12:38_

@Eilon can I move this to MVC, or @mkArtakMSFT has a suitable way to move it

**Comment by mkArtakMSFT** [comment]
@DamianEdwards, sounds like a reasonable ask. Moved this to the next release milestone to consider later.

**Comment by DamianEdwards** [comment]
Not aligned with planned scope for next release. Sugges moving it to backlog.

**Comment by rynowak** [comment]
I don't understand why we would do something like this. The current experience is straightforward and comprehensible.

**Comment by mkArtakMSFT** [comment]
Closing this issue as we have no plans to do this.
