### ISSUE TITLE
Consider having precompiled views/pages throw when there is a conflict between views provided by two LIBRARIES

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#7387]
Today we support disambiguation between precompiled views using a rule that a view present in the **application** can win over views present in libraries.

If you have a **conflict between libraries** the result is implementation defined, but will not throw.

@DamianEdwards and I think we should reconsider this approach, it's not very friendly and which it's consistent with File Providers, it's not consistent from things like controllers or view components.

**Comment by mkArtakMSFT** [comment]
I agree that throwing in case of ambiguity is better. Do we have a solution in that case? Something similar to prefixes/namespaces. From the discussion with @rynowak it sounded that it's not possible at the moment. What it'll take us to make this possible? What information do we miss to bring support for this? @DamianEdwards, do you think this is an effort worth pursuing?
/cc @pranavkm

**Comment by DamianEdwards** [comment]
Doesn't align with our planned scope for next release. I'd wait for feedback on this.

**Comment by mkArtakMSFT** [comment]
Thanks @Damian. Closing this now and let's see whether there will be any customer asks similar to this.
