### ISSUE TITLE
.Net Core ExecuteReader GetSchemaTable() method not returning the BaseTableName and more details.

### ISSUE THREAD

**Issue by ezra2310** [aspnet/Mvc#7389]
Hi,

In .Net Core ExecuteReader.GetSchemaTable() method not returning the BaseTableName and more details of the query will executed.

I'm created an console application in Core .Net 2.0. The below code has written and do some R&D. Its working in .net Framework 4x version and get all schema details as BaseTablename,BaseColumn,etc.... But in Core .Net 2.0 the BaseTableName was not returning.

Im tried in various way but still im not got the route. Can you please help me how to get the BaseTableName and all those details.

Its very important R&D undergoing. Can you anybody please help me ??

SqlConnection sqlCnn = new SqlConnection(connetionString);
sqlCnn.Open();
SqlCommand sqlCmd = new SqlCommand(sql, sqlCnn);

SqlDataReader sqlReader = sqlCmd.ExecuteReader(CommandBehavior.KeyInfo);

List<string> gotTableNames = new List<string>();
DataTable schemaTable = sqlReader.GetSchemaTable();

foreach (DataRow dr in schemaTable.Rows)
{
   string data = Convert.ToString(dr["BaseTableName"]);
   if (!gotTableNames.Contains(data))
   {
      gotTableNames.Add(data);
   }
}

return string.Join(",", gotTableNames);

**Comment by Vasimovic** [comment]
I don't think this is related to the MVC repository; Anyhow, I was able to reproduce the problem; works in  full framework 4.+ as expected, returns blank data in netcoreapp2.0:

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            SqlConnection sqlCnn = new SqlConnection("Server=(local);Database=Master;Trusted_Connection=True;");
            sqlCnn.Open();
            SqlCommand sqlCmd = new SqlCommand("select name, database_id, create_date from sys.databases;", sqlCnn);

            SqlDataReader sqlReader = sqlCmd.ExecuteReader();

            var gotTableNames = new List<string>();
            DataTable schemaTable = sqlReader.GetSchemaTable();

            if (schemaTable != null)
            {
                foreach (DataRow dr in schemaTable.Rows)
                {
                    string data = dr["BaseTableName"].ToString();
                    if (gotTableNames.Contains(data)) continue;
                    gotTableNames.Add(data);
                }
            }

            Console.WriteLine(string.Join(",", gotTableNames));
            Console.ReadLine();
        }
    }
}

**Comment by ezra2310** [comment]
Hi Vasi,
My query is not sys tables. It’s normal join query.

 E.g. : select p.id [id_person],a.id [id_address],* from person [p] inner join address [a] on [p].addess_id = [a].id

The above one is my query. 
If this query will execute by ExecuteReader.GetSchemaTable() in.net framework 4+  I will return the BaseTableName and Basecolumn and AliasColumn name in DataTabel. 

But in netcoreapp2.0 it not returning also those details of executed query by Reader. 

In netcoreapp2.0 it just return the column name and data type. It’s normally we can get.

This my problem. Because the Join will be more table and dynamic representation of sql have to show in visual that is aim behind this scene

**Comment by Vasimovic** [comment]
@ezra2310, I understand, as I mention, I confirmed it does not work with netcoreapp2.0 

You need to submit the issue to the **correct** [CoreFx](https://github.com/dotnet/corefx/issues) repository, this is the ASP.NET MVC repository

**Comment by mkArtakMSFT** [comment]
@Eilon, can you please redirect this as necessary? Seems ADO.NET related.

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#27283
