### ISSUE TITLE
RedirectToPage invokes previously-executed controller (when [Authorize] on redirected to page)

### ISSUE THREAD

**Issue by tmandekic** [aspnet/Mvc#7392]
I have a form inside a Razor page (lets call it MyFirstPage.cshtml). 
On form-submit, the code behind calls and executes action on another controller (UserController.PostRegisterUserAsync) followed by a call to RedirectToPage("/MySecondPage"). 
MySecondPage requires B2C authorization (it has [Authorize] attribute on it).
This correctly causes MySecondPage to load, but it also re-executes UserController (constructor) and UserController.PostRegisterUserAsync. If I remove [Authorize] attribute on MySecondPage, it works ok (there is no second call to UserController.PostRegisterUserAsync)

UserController:

    [Route("api/[controller]")]
    public class UserController : Controller
    {
        public IHostingEnvironment _environment;
        private readonly ILogger _logger;
		
        public UserController(IHostingEnvironment env)
        {
            _logger = new LoggerFactory().CreateLogger<UserController>();
            _environment = env;
        }
		
        [HttpPost("register")]
        public async Task<IActionResult> PostRegisterUserAsync([FromBody]UserObject myUserObject, 
        CancellationToken cancellationToken)
        {
            // process user registration
        }
    }

in Startup.cs:
`services.AddTransient<UserController, UserController>();`

myFirstPage.cshtml.cs:

    public class MyFirstPageModel : PageModel
    {
        private UserController  _userController ;
        private UserObject _user;

        public MyFirstPageModel( UserController userController)
        {
             _userController = userController;
        }

        public async Task<IActionResult> OnPostMethodAsync(CancellationToken cancellationToken)
        {
            await _userController.PostRegisterUserAsync(_user, cancellationToken);
            return RedirectToPage("/mySecondPage");
        }
    }

MySecondPage:

    [Authorize]
    public class MySecondPageModel : PageModel
    {
        // code
    }

How to prevent that second (unexpected) call to the UserController, without removing [Authorize] on MySecondPage?

**Comment by pranavkm** [comment]
What does the content for `MySecondPage` look like? There really isn't anything intrinsic in Razor Pages that cause it call unrelated controller methods.

**Comment by mkArtakMSFT** [comment]
Hi @tmandekic. Thanks for reporting the issue. Please provide us with a small repro project to investigate.

**Comment by tmandekic** [comment]
After lots of debugging, it turns out there is a handler in my authorization part that was invoking this controller. Closing the issue. Thank you.
