### ISSUE TITLE
Precompiled views are not being used even when they are available

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Mvc#7397]
Looks like this is a regression. I can see PrecompiledViews.dll being generated with all the CompiledViewItems but the views are being compiled on the first request.

cc @pranavkm @rynowak 

@mikeharder, this is the reason for the perf regression we were seeing.

**Comment by pranavkm** [comment]
Self assigning this for investigation

**Comment by pranavkm** [comment]
Resolved in https://github.com/aspnet/Razor/commit/b538ceba9365a018eadc48bbe57dc9b2a76cbd90
