### ISSUE TITLE
Unexpected default path of view component views

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7398]
For example, create a view component named "Menu" and invoke it from a view used in a controller named "Home". In the view component's `Invoke()` method, call `View("Menu.cshtml")`.
## Expected
Finds Menu.cshtml in the default location for this component and controller pair aka the first location searched when using the view name `"Menu"`: `Views/Home/Components/Menu/Menu.cshtml`
## Actual
Finds Menu.cshtml in the *controller*'s default view folder: `Views/Home/Menu.cshtml`
## Not found case
Doing the same thing without a matching `Menu.cshtml` file confirms the name is treated as a relative path, not a name to search for.
```
InvalidOperationException: The view 'Components/Menu/Menu.cshtml' was not found. The following locations were searched:
 /Views/Home/Menu.cshtml
```
### Additional logging issue
Though the locations searched are correct, the `Message` is not. `Components/Menu/Menu.cshtml` and `Views/Home/Components/Menu/Menu.cshtml` are not checked. MVC is logging with an edited "view name" that's never used because Menu.cshtml is a relative path.
## Documentation
The view component documentation (https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components) does not mention passing a relative path to `View(...)` within a view component.
## Suggestions
1. Allow users to opt into using `~/Views/{Controller}/Components/{Component}/` as the default path for relative paths passed to `View(...)` within a  view component. Because view components have been around for a release or so, can't change the default path (i.e. the `ViewContext.ExecutingFilePath` on entering `Invoke()`) without a breaking change. Likely need another `RazorViewEngineOptions` or `MvcViewOptions` property.
  This is based on an assumption that the root cause is `ExecutingFilePath` doesn't change from the view invoking the component i.e. where `Component.Invoke[Async](...)` was called.
2. Correct the failed search `Exception.Message` to use the original view name or path.
3. Document the interpretation of relative paths with and without the new property set.
## First scenario details
``` c#
public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

[ViewComponent(Name = "Menu")]
public class MenuComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View("Menu.cshtml");
    }
}
```
### Views/Home/Index.cshtml
``` html
<div class="row">
    @await Component.InvokeAsync("Menu")
</div>
```
### Views/Home/Components/Menu/Menu.cshtml
Exists but is not invoked
### Views/Home/Menu.cshtml
``` html
<h2>Menu.cshtml in controller (@Path).</h2>
```

**Comment by pranavkm** [comment]
Nope. The lookup's always been busted. This was a suggestion to fix the behavior.

**Comment by mkArtakMSFT** [comment]
Closing this as there has been no community interest in fixing this behavior.
