### ISSUE TITLE
ApiExplorer documents required properties confusingly 

### ISSUE THREAD

**Issue by nphmuller** [aspnet/Mvc#7399]
On ASP.NET Core 2.0, but this also affects older versions. See [this repo](https://github.com/nphmuller/ApiExplorer_IsRequired) for a working repro.

Say I have the following controller action and model:
``` c#
[Route("controller")]
public class MyController : ControllerBase
{
    [HttpPost]
    public void MyAction(MyModel model) { }
}

public class MyModel
{
    public int Param1 { get; set; }
}
```

When I check the `ModelMetadata` of the `ApiParameterDescription` from `Param1` the property `IsRequired` is set to true. See the following code which is part of `Startup.cs`:
``` c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    var apiDescriptionsProvider = app.ApplicationServices.GetRequiredService<IApiDescriptionGroupCollectionProvider>();
    var parameterDescription = apiDescriptionsProvider.ApiDescriptionGroups.Items.Single().Items.Single().ParameterDescriptions.Single();
    var isRequired = parameterDescription.ModelMetadata.IsRequired;
}
```

This is probably because Param1 is a non-nullable and hence always required technically. The reason I think this is confusing however, is because ApiExplorer is used to document the behaviour of your API. 

The IsRequired property suggests that the request should always contain this property, which is not true because if a non-nullable parameter is not included in the (for example json) request, it's simply set to its default value. This means the ModelState.IsValid property always returns true, which means that excluding this property from a request will never result in a BadRequest response.

See for example the discussion over here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/599

Swashbuckle uses ApiExplorer to create a swagger.json file, which described the API. Because of this confusing behaviour it's more difficult for Swashbuckle to document which parameters are actually required from an API consumer's perspective.

**Comment by mkArtakMSFT** [comment]
Hi @nphmuller. Thanks for contacting us. 

@dougbu, can you please look into this?

**Comment by dougbu** [comment]
@nphmuller sounds like Swashbuckle is misinterpreting `ModelBinding.IsRequired`. (ApiExplorer doesn't reference the property.) That property has different client- and server-side meanings: The client-side interpretation shouldn't be relevant to Swashbuckle. Server-side, `ModelBinding.IsRequired` means the value must be non-`null` after model binding; it does not mean a value must be submitted.

Swashbuckly should use `ModelMetadata.IsBindingRequired` to determine whether the application requires something to be submitted. The application has complete control of that property, using `[BindRequired]` and `[DataContract]`.

BTW it would be a significant breaking change for the `ModelMetadata.IsRequired` value to change e.g. if it were not `true` for all value types.

**Comment by dougbu** [comment]
Fixed `ModelBinding` -> `ModelMetadata` typo in previous response.

**Comment by nphmuller** [comment]
@dougbu What I'm trying to determine is which parameters would result in a BadRequest response if they're not part of the request. The BadRequest is generated when the `ModelState.IsValid` property in the controller is false.

What property can I use in the ModelMetaData to determine this? Because `ModelMetaData.IsBindingRequired` still gives false for an `int?` that is decorated with a `RequiredAttribute`.

See this example:
``` c#
public class MyRequestModel
{
    public int Param1 { get; set; }
    // ModelMetadata.IsRequired: true
    // ModelMetadata.IsBindingRequired: false
    // ModelState.IsValid when not in the json request: true

    [Required]
    public int Param2 { get; set; }
    // ModelMetadata.IsRequired: true
    // ModelMetadata.IsBindingRequired: false
    // ModelState.IsValid when not in the json request: true

    public int? Param3 { get; set; }
    // ModelMetadata.IsRequired: false
    // ModelMetadata.IsBindingRequired: false
    // ModelState.IsValid when not in the json request: true

    [Required]
    public int? Param4 { get; set; }
    // ModelMetadata.IsRequired: true
    // ModelMetadata.IsBindingRequired: false
    // ModelState.IsValid when not in the json request: false
}
```

**Comment by dougbu** [comment]
> trying to determine is which parameters would result in a BadRequest response if they're not part of the request

As you've demonstrated, `ModelMetadata.IsRequired` doesn't give you this information. In broad strokes:
1. Actions may choose not to check `ModelState.IsValid`, to substitute default values, or whatever. Returning a `BadRequest` response is *optional*.
1. If `ModelMetadata.IsBindingRequired == true` and no value is submitted for the associated property, `ModelState.IsValid` will be `false`.
1. If `ModelMetadata.IsRequired == true`, no value is submitted for the associated property, the property has a nullable type (a class or `Nullable<T>`), and the property does not have a non-`null` default value, `ModelState.IsValid` will be `false`.

**Comment by domaindrivendev** [comment]
@dougbu - thanks for your insight. From what you've described, the semantics around `BindRequired` and `IsBindingRequired` appear to be well aligned to the `required` field in Swagger/JsonSchema, and therefore might be the most appropriate way for Swashbuckle to infer it's value. However, I've noticed `BindRequired` has no effect for body parameters, i.e. parameters that are explicitly decorated with `FromBody`. Is there something I'm missing here?

**Comment by nphmuller** [comment]
@dougbu 
First of all, thanks for the detailed reponse.

> 1. Actions may choose not to check ModelState.IsValid

True but in ASP.NET Core 2.1 the `ApiController` attribute will automatically return a 400 when `ModelState.IsValid` is false, so it will become more common.

> 2 + 3

So the suggested approach would be something like this?
``` c#
private bool DocumentAsRequiredInSwaggerDocs(ApiParameterDescription desc)
{
   var modelMetaData = desc.ModelMetaData;
    if (modelMetadata.IsBindingRequired)
        return true;
    if (modelMetadata.IsRequired && IsNullable(desc.Type) && GetDefaultValue(desc.Type) == null)
        return true;

    return false;
}
```

Would it be in the use-case of ApiExplorer to provide the above code out-of-the-box? If so, consider this a feature request. :)

**Comment by nphmuller** [comment]
@dougbu First of all: thanks for the detailed response.

> 1 Actions may choose not to check `ModelState.IsValid`

True, but since the `ApiController` attribute in 2.1 will default to a 400 response when `ModelState.IsValid` is false it will become more common.

> 2 + 3

I've taken these directions and written the following method. I've also added a case for parameters from path.
``` c#
private bool IsRequiredInRequest(ApiParameterDescription desc)
{
    var modelMetadata = desc.ModelMetadata;
    if (desc.RouteInfo?.IsOptional == false)
        return true;
    if (modelMetadata.IsBindingRequired)
        return true;
    if (modelMetadata.IsRequired && modelMetadata.IsReferenceOrNullableType && HasDefaultNullValue(desc))
        return true;

    return false;
}

private bool HasDefaultNullValue(ApiParameterDescription desc)
{
    var modelMetadata = desc.ModelMetadata;

    switch (modelMetadata.MetadataKind)
    {
        case ModelMetadataKind.Property:
            var container = Activator.CreateInstance(modelMetadata.ContainerType);
            var propertyInfo = container.GetType().GetProperty(modelMetadata.PropertyName);
            return propertyInfo.GetValue(container) == null;

        // Never triggered in ASP.NET Core 2.0, but might be in 2.1. This is because
        // modelMetadata.IsRequired is always false in 2.0, since validation attributes
        // directly on on action parameters aren't support. In 2.1 however this is support,
        // so this case might be hit then.
        case ModelMetadataKind.Type:
            var controllerParameterDescriptor = desc.ParameterDescriptor as ControllerParameterDescriptor;
            if (controllerParameterDescriptor == null)
                throw new NotSupportedException("No way to determine the default value.");
            return controllerParameterDescriptor.ParameterInfo.HasDefaultValue ?
                controllerParameterDescriptor.ParameterInfo.DefaultValue == null :
                true;

        default:
            throw new NotSupportedException();
    }

}
```

Is there an easier way to implement `HasDefaultNullValue(...)`? Or an easier way to implement this in general? It feels weird to have to write this many code for something that feels like a typical use-case for ApiExplorer: Figuring out which parameters are required in the request. Should every user be able to figure this out on their own?

**Comment by nphmuller** [comment]
I also noticed another problem: the `ParameterDescriptor` property on `ControllerParameterDescriptor` doesn't exist in version 1.x. So there would be no (straightforward) way to implement `case ModelMetadataKind.Type:` in `HasDefaultNullValue()`.

Not that big a deal though, since query parameters have `modelMetadata.IsRequired` always set to false on ASP.NET Core < 2.1.

**Comment by mkArtakMSFT** [comment]
Thanks @dougbu, @nphmuller. It seems the only ask left here is to make it easier to understand whether given request parameter is required or not. Hence, marking this as an enhancement an putting this onto our backlog for future consideration.

**Comment by mkArtakMSFT** [comment]
Apparently this was already addressed as part of https://github.com/aspnet/Mvc/issues/7563.
