### ISSUE TITLE
Memory Leak in ASP.NET 2.0.5

### ISSUE THREAD

**Issue by karthicksu** [aspnet/Mvc#7400]
I'm developing an web app using asp.net core. When I run the app in VS 2017 (15.5.5) with Diagnostic tools enabled, memory is constantly increasing at-least 10 to 20MB per click. I thought the app has a memory leak and troubleshooting the app for many hours and I've landed on this link https://blog.markvincze.com/troubleshooting-high-memory-usage-with-asp-net-core-on-kubernetes/

I have created a new project from ASP.NET Core - Web Application Template which has few razor pages and returns HTML. When I refresh the page continuously (like a smoke test) the memory gradually increases from 200MB to 500MB and even more...

have a look on [this](https://www.screencast.com/t/Fpe348hEU)

As suggested in Mark Vincze blog, I've added following config in .csproj

`<PropertyGroup> 
    <ServerGarbageCollection>false</ServerGarbageCollection>
</PropertyGroup>`

Unfortunately it doesn't help. Memory still increases gradually. 

All ASP.NET Packages are up-to-date https://www.screencast.com/t/iaQVx9bH5Y1
OS: Windows 10 (1709)
IDE: Visual Studio 2017 (15.5.5) 
ASP.NET 2.0.5

Steps to reproduce:
1) Create a project in Visual Studio (ASP.NET Core - Web Application)
2) Run the project with Diagnostic tools enabled
3) Refresh the page continuously and watch the diagnostic tool
4) Memory will increase gradually.

**Comment by mkArtakMSFT** [comment]
Hi @karthicksu.

Thanks for reporting this issue. One of our engineers will investigate this and get back to you as soon as we'll get more data.

/cc: @DamianEdwards, @Eilon , @rynowak, @danroth27

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this one? Thanks

**Comment by muratg** [comment]
@karthicksu How long did you run the experiment for?  I'd expect to see the memory grow up to a point and stay constant even with additional requests after that. I'd be curious to understand why if not.

**Comment by karthicksu** [comment]
@muratg I got it! The last two experiments was without the following tag in .csproj, and the solution was not properly built. 
`<PropertyGroup> <ServerGarbageCollection>false</ServerGarbageCollection> </PropertyGroup>`

When I run the project without the tag ServerGarbageCollection, memory usage increases from 200MB to 579MB, after that it stays constant. This time the experiment ran up to 7min. 579MB is still higher when compare to ASP.NET MVC 5 in .NET framework. 

However, when using the tag ServerGarbageCollection in .csproj it memory usage stays less as 98MB. This is expected result which is nice. 

Do you we need to use tag ServerGarbageCollection false always to reduce the memory usage? and will this work in hosting environments (shared hosting, docker)?

**Comment by muratg** [comment]
@karthicksu It depends on what you want your performance goals are, what your load profile looks like and probably other factors.  Having "high memory usage" is not necessarily bad thing on itself and there are good reasons for ServerGarbageCollection feature (for more information, see https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcserver-element)

**Comment by karthicksu** [comment]
@muratg Thanks for the reply, provided link helps to understand the behavior of GC. It seems, in .NET Framework, by default **ServerGarbageCollection** is set to **false**. Therefore, it doesn't increase the memory usage. 

It would be great if the same default value (**ServerGarbageCollection** set to **false**) in .NET Core also.

**Comment by davidfowl** [comment]
@karthicksu ASP.NET applications on .NET Framework set it to true by default as well.

**Comment by karthicksu** [comment]
@davidfowl 

Is this [https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcserver-element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcserver-element) different from ASP.NET configuration?

[Screenshot](https://www.screencast.com/t/927tVJMv)

**Comment by davidfowl** [comment]
Yes. ASP.NET uses server GC by default.

**Comment by mkArtakMSFT** [comment]
Thanks everyone. Closing the issue as the behavior observed is by-design.

**Comment by danroth27** [comment]
@amigin Please open a new issue in the [Home](https://github.com/aspnet/home/issues) repo with details about your app so that we can try to investigate the issue.
