### ISSUE TITLE
.net core2.1  And .net Core 2.0(My English is not good)

### ISSUE THREAD

**Issue by zhanglong19891129** [aspnet/Mvc#7403]
It Failed When I bulid the source code  in VS2017 (latest edition) . 
It‘s Message such as : VS2017 does not support.net CORE2.1 needs to switch to.net CORE 2.0.
How do I switch?

**Comment by mkArtakMSFT** [comment]
Hi @zhanglong19891129. Can you please provide more details about what your'e trying to do? Are you trying to build our source code?

**Comment by zhanglong19891129** [comment]
@mkArtakMSFT  yeah, The first step is to run the build.cmd.   But It's Failed when downloading the package  of  https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.300-preview2-008173/dotnet-sdk-2.1.300-preview2-008173-win-x64.zip . So It thrown exception : VS2017 does not support .net core2.1 needs to switch to .net core2.0  when I  build solution in VS2017 .

**Comment by zhanglong19891129** [comment]
![k_j nv i yzuujy74 egv](https://user-images.githubusercontent.com/17588408/36712514-2364f234-1bc4-11e8-8618-ef9c14672363.png)

![qq 20180227134018](https://user-images.githubusercontent.com/17588408/36712529-2fd20eb2-1bc4-11e8-8a18-16c12d7dd54c.png)
![qq 20180227133658](https://user-images.githubusercontent.com/17588408/36712539-35f1e9d4-1bc4-11e8-899e-0796eb35ec6a.png)

**Comment by pranavkm** [comment]
@natemcmaster any guesses on why the CLI download might fail?

**Comment by natemcmaster** [comment]
CDN issues? https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.300-preview2-008173/dotnet-sdk-2.1.300-preview2-008173-win-x64.zip works for me.

**Comment by mkArtakMSFT** [comment]
@zhanglong19891129, are you able to download the https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.300-preview2-008173/dotnet-sdk-2.1.300-preview2-008173-win-x64.zip manually?

**Comment by zhanglong19891129** [comment]
@mkArtakMSFT yes,I have downloaded it manually

**Comment by natemcmaster** [comment]
Extract the zip to `%USERPROFILE%\.dotnet\x64`. You will likely have to do this for a few other things to. Our build scripts will frequently try to pull from  https://dotnetcli.azureedge.net.

**Comment by natemcmaster** [comment]
By the way, why are you trying to build our source code? I may be pointing out the obvious, but if you are just trying to use MVC in your own application, you do not need to build it yourself: you can get MVC from NuGet.org.

**Comment by zhanglong19891129** [comment]
@natemcmaster  this problem is come from building source code . I just want understand how it's working by running  the unit testing application.

**Comment by zhanglong19891129** [comment]
@natemcmaster  I  run  build.cmd successful today.  
![qq 20180228162826](https://user-images.githubusercontent.com/17588408/36777590-00fac25a-1ca5-11e8-9a56-1f974c823250.png)
But It's still have some problems  :
![qq 20180228162719](https://user-images.githubusercontent.com/17588408/36777621-22f22f88-1ca5-11e8-866b-16f77a2a5467.png)
![qq 20180228162826](https://user-images.githubusercontent.com/17588408/36777641-36677348-1ca5-11e8-97f4-a2cbeaba0700.png)

**Comment by mkArtakMSFT** [comment]
@zhanglong19891129, the release version of VS won't show the .NET Core 2.1 target framework, as it's not aware of it. To see it you can install the latest preview release of VS.

**Comment by mkArtakMSFT** [comment]
Closing this issue, as all the open questions have been addressed.

**Comment by zhanglong19891129** [comment]
@mkArtakMSFT       MVS    community 2017  preview .  version: 15.6.0 preview 6.0 Is not work. The target framework is still empty. ? It's need Enterprise or professional?

**Comment by natemcmaster** [comment]
I think you are seeing https://github.com/dotnet/project-system/issues/800. Because the test project has multiple target frameworks, VS is leaving that box empty. The test projects in aspnetcore target netcoreapp2.0, netcoreapp2.1, and net461. This is how we define multiple frameworks:

https://github.com/aspnet/Mvc/blob/b6144142feb9509566c3251e2d1a7fa49c3d7817/test/Directory.Build.props#L4-L9
https://github.com/aspnet/Mvc/blob/e35d0bc43f8e02112f8eea416cbaafbdbcb93d3c/test/Microsoft.AspNetCore.Mvc.RazorPages.Test/Microsoft.AspNetCore.Mvc.RazorPages.Test.csproj#L4

**Comment by zhanglong19891129** [comment]
@mkArtakMSFT  @natemcmaster  thanks
