### ISSUE TITLE
How to localize DataAnnotations with custom IStringLocalizer

### ISSUE THREAD

**Issue by lkubis** [aspnet/Mvc#7404]
I'm following the article [Globalization and localization in ASP.NET Core -
 DataAnnotations localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization#dataannotations-localization), but I'm not able to make it running.

What I have is:

**MyStringLocalizer**

    public class MystringLocalizer : IStringLocalizer
    {
        private readonly Dictionary<string, string> _data =
            new Dictionary<string, string>()
            {
                { "Global.Name", "Name Localied" }
            };

        public IEnumerable<LocalizedString> GetAllStrings(bool includeParentCultures)
        {
            return _data.Select(x => new LocalizedString(x.Key, x.Value));
        }

        public IStringLocalizer WithCulture(CultureInfo culture)
        {
            throw new NotImplementedException();
        }

        LocalizedString IStringLocalizer.this[string name] =>
            new LocalizedString(name, _data[name]);

        LocalizedString IStringLocalizer.this[string name, params object[] arguments] =>
            new LocalizedString(name, _data[name]);
    }

**Index (markup)**

    @page
    @using System.Globalization
    @using Microsoft.AspNetCore.Mvc.RazorPages
    @using Microsoft.Extensions.Localization
    @model WebApp.Pages.IndexModel
    
    @inject IStringLocalizer Localizer
    
    <div>Global.Name: "@Localizer["Global.Name"]"</div>
    <label asp-for="Model.Name"></label>
    <input asp-for="Model.Name"></input>
    
**Index (code-behind)**

    public class IndexModel : PageModel
    {
        [BindProperty]
        public IndexViewModel Model { get;set; }
    }

    public class IndexViewModel
    {
        [Display(Name = "Global.Name")]
        [Required(ErrorMessage = "Global.Name")]
        public string Name { get; set; }
    }

**Registration at Startup**

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc()
                .AddDataAnnotationsLocalization(options => {
                    options.DataAnnotationLocalizerProvider = (type, factory) =>
                        new MyStringLocalizer();
            });;

            services.AddSingleton<IStringLocalizer, MyStringLocalizer>();
        }    
    }

But when I navigate to Index page, the value inside div works fine, but label has just text **Name** and also error message while submitting form is **Name** too.

Is there anything what I've missed?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use localization in ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, can you please assist with this request? Thanks!

**Comment by ryanbrandenburg** [comment]
@lkubis I tried to reproduce this by doing `dotnet new razor` then makes the changes you posted above and it worked as expected, giving "Name Localied" out of the localizer and as the label for Model.Name.

In order to help further I would need a full repro app as a github repo so that I can see the exact code that's not working, as something seems to have been lost in the copy.

**Comment by lkubis** [comment]
I apologize, but after another review of my code, I found out that the problem was on my side. I was doing such a complicated things in ConfigureServices method, and after simplification, it started to work as expected. Thanks

**Comment by ryanbrandenburg** [comment]
No worries, glad we could help!
