### ISSUE TITLE
Execute Razor page from Middleware

### ISSUE THREAD

**Issue by sreejukg** [aspnet/Mvc#7405]
I am planning to write a middleware that sends a razor page back to the user. the user may use get/post with all other features. The Middleware need to execute a particular razor based on some values stored in the database. I am interested to view multiple options.

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us.
To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve?

**Comment by sreejukg** [comment]
Hello sorry for being late. The notifications are not delivered. Let me try to explain the scenario.

Consider the below two requests

/SpecialOffer/Electronics/TV/42/Model1 
/SpecialOffer/Electronics/TV/42/Model2

I would like to render two separate razor pages for handling these requests. So I wrote a routing middleware that matches the request. Now if the match is found in my middleware, I need to send the corresponding razor page as the response. 

Hope this is clear, let me know if you need further clarifications.

**Comment by pranavkm** [comment]
You could have two physical files located at those paths or use [`AddPageRoute`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.pageconventioncollectionextensions.addpageroute?view=aspnetcore-2.0#Microsoft_Extensions_DependencyInjection_PageConventionCollectionExtensions_AddPageRoute_Microsoft_AspNetCore_Mvc_ApplicationModels_PageConventionCollection_System_String_System_String_) to map a path to the page.

**Comment by sreejukg** [comment]
Thanks for the response. but I am looking for a completely dynamic option. So placing file in the categories option is ruled out by default.

Let me try to explain more clearly. If I have several products in my db, with meta data that will be used to build the route. Now I need to add a column in database for template, that will specify the name of razor page template name. From a middleware, I will search for a match in db and if found, I need the razor page specified in the db column to be sent as the response. 

Can you advise whether the second option  (AddPageRoute) can be used here?

**Comment by mkArtakMSFT** [comment]
@pranav, can you please help out with this ask? Thanks!

**Comment by sebastienros** [comment]
Maybe not based on Razor Pages directly, but you could just intercept a single route, with a single controller, and from the action based on the route parameter load different views. You can return something like this:

```
public IActionResult Display(string category, string model)
{
  var viewModel = BuildViewModel(category, model); // from database or services
  var viewName = LoadViewNameFromDatabase(category, model); // from database or services

  return View(viewName, viewModel);
}
```

**Comment by sebastienros** [comment]
You can use another technique which is using a custom route that will get all the request and find a match, then fallback to the other routes if it couldn't find any match. See an example in Orchard Core:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Autoroute/Routing/AutorouteRoute.cs

And how it's inserted in the list of routes as the first element:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Autoroute/Startup.cs#L65

**Comment by sreejukg** [comment]
This seems the way. Will look into this and post my feedback.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
