### ISSUE TITLE
AspNetCore 2.1 breaks integration with 3rd party validation libraries

### ISSUE THREAD

**Issue by JeremySkinner** [aspnet/Mvc#7412]
Hi, I maintain the [FluentValidation](github.com/jeremyskinner/fluentvalidation) project which contains integration components with AspNetCore. 

Unfortunately 2.1 preview 1 breaks this integration. In previous versions, it was possible to implement a custom `IObjectModelValidator`. This worked as the entry point for the validation process where I could then customize the validation behaviour by providing a custom `ValidationVisitor` (as custom ModelValidatorProviders do not provide enough extensibility). 

In the 2.1-preview1 release it seems that the IObjectModelValidator is never resolved from the service provider anymore, and instead validation is kicked off by the `ParameterBinder` class instead. Unfortunately the `EnforceBindRequiredAndValidate` method is private, so I can't just override this method to supply my own ValidationVisitor, and instead have to override the `BindModelAsync` method and duplicate all the code in here. 

1) Please can `ParameterBinder.EnforceBindRequiredAndValidate` be made virtual? (Or alternatively, introduce a new protected method called `CreateAndInvokeValidationVisitor` or something like that which is then called by ParameterBinder.EnforceBindRequiredAndValidate) 
2) Is `IObjectModelValidator` not supposed to be used anymore? If so, should it be marked as obsolete?
3) Is there any documentation on when the new ModelMetadataKind.Parameter is used vs ModelMetadataKind.Type?

Also could you provide some background information on this change? (Or point me to a previous discussion if there was one that I missed) 

Thanks

//cc @rynowak

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. One of our team members will look into it and get back to you.

**Comment by mkArtakMSFT** [comment]
@dougbu, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
Thanks @dougbu!

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please look into this when you'll be back? Thanks!

**Comment by BladeWise** [comment]
@JeremySkinner Any chance for a preview package including the (temporary?) fix?

**Comment by JeremySkinner** [comment]
@BladeWise Not for preview1 - will be aiming for preview2. Please follow this issue if you want to track progress. https://github.com/JeremySkinner/FluentValidation/issues/698
