### ISSUE TITLE
Make IErrorDescriptionFactory internal or remove it

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7414]
Another fit and polish item from KodKod work. We have a type, but haven't fleshed out it's design. We should make the interface internal or remove it so we can design it to have the right shape once we have all the pieces.

**Comment by pranavkm** [comment]
cc @rynowak

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg , can you please handle this? Thanks!
