### ISSUE TITLE
Create a new Analyzer to warn users from using `Html.Partial`

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#7417]

**Comment by pranavkm** [comment]
Out of curiosity, why an analyzer versus just marking the method `Obsolete`? If we eventually make https://github.com/aspnet/Mvc/issues/7416 work, it's likely that we'll be forced to remove this method.

**Comment by pranavkm** [comment]
The reason to not use the `Obsolete` attribute is that suppressing it in Razor using `#pragma` is not trivial. The plan here is to ship an independent analyzer, not part of `Microsoft.AspNetCore.Mvc.Analyzers` for this.
