### ISSUE TITLE
RazorPages ViewEngine with customizable file extensions.

### ISSUE THREAD

**Issue by tb-mtg** [aspnet/Mvc#7419]
The RazorPages view engine (RazorViewEngine) only support cshtml.

Can the hard coded instances of "cshtml" be removed and replace with a property or something to be able to make a custom RazorViewEngine that supports to any file/page/view extension?

For example in files:
* Microsoft.AspNetCore.Mvc.Razor.Internal.xxxMicrosoft.AspNetCore.Mvc.Razor.Internal.FileProviderRazorProject (RazorFileExtension)
* Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionDescriptorChangeProvider (_searchPattern)
* Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider (ViewStartFileName)
* Microsoft.AspNetCore.Mvc.ApplicationModels.PageConventionCollection (EnsureValidPageName)
* Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageSelectorModel (IndexFileName)
* Microsoft.AspNetCore.Mvc.RazorPages.Internal.RazorPagesRazorViewEngineOptionsSetup (Configure uses RazorViewEngine.ViewExtension)
* Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine (ViewExtension & ViewStartFileName)
* Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewEngineOptionsSetup (Configure)

**Comment by Eilon** [comment]
See also: https://github.com/aspnet/Razor/issues/2125

@tb-mtg can you provide info on why you want to change this?

**Comment by tb-mtg** [comment]
I'm trying to implement a RazorViewEngine that supports VBHTML & RazorPages as there has been no support for this feature after it was not included in ASP.Net Core Web Applications.

**Comment by mkArtakMSFT** [comment]
Hi @tb-mtg. Unfortunately we have no any plans to support any other file extensions but `cshtml`. That said, we won't be able to provide a mechanism to configure/change the extension.
