### ISSUE TITLE
Converting active razor views as pdf

### ISSUE THREAD

**Issue by M1991** [aspnet/Mvc#7420]
I am using asp.net mvc, I have a view which shows an image and some details with css classes and sessions over it. The issue is that i am able to get the view with image, its details but unable to get the same with pdf format.

As of now its converting to the view as pdf but with errors
>  object reference not set to instance of an object

![pdf_conversion](https://user-images.githubusercontent.com/22197822/36838736-ff5c844e-1d65-11e8-87ed-5e49b5f6681d.jpg)

It may be because of active sessions on which the values are stored.
I tried using third party libs Rotativa, SelectPdf.

> My view is an background image and 6 session object (decimal & string values) placed on different areas above the image

Please comment if any further explanation is required. 

Below is the function for Pdf conversion

`public static void PdfConvtrFunction()
        {
            SelectPdf.HtmlToPdf converter = new SelectPdf.HtmlToPdf();           
            SelectPdf.PdfDocument doc = converter.ConvertUrl("Url_Path");  //Current active view
            doc.Save(System.Web.HttpContext.Current.Server.MapPath("~/Uploads/test.pdf"));  //save in local, send from local, delete from local
            doc.Close();
        }`

Further it will save the pdf, attach it to a mail and send the same.
is there any option to convert an active/current view to pdf ?
Thanks in advance.

**Comment by mkArtakMSFT** [comment]
Hi @M1991. The issue you're describing is not related to ASP.NET. You should rather file the issue with the product owners of the library you're using for PDF conversion.
