### ISSUE TITLE
Web Api not returning error message

### ISSUE THREAD

**Issue by khanusman** [aspnet/Mvc#7425]
POST action is returning 400 bad error. However, its not returning the error message. I am overriding OnActionExecuting method on ActionFilterAttribute class and I do see ModelState populated and validation errors are also visible in watch, please see the snap,

![image](https://user-images.githubusercontent.com/5824941/36865027-5836a13a-1d5c-11e8-9651-6a423d937913.png)

I have POST action implemented like this. Its simply returning updated object from the database.

    [HttpPost]
    [ODataRoute()]
    public async Task<IActionResult> Post([FromBody]ComponentDTO baseComponent)
        {
        Component component = _mapper.Map<Component>(baseComponent);

        var result = await _repo.AddDocumentIntoCollectionAsync(component);
        return Created(result);
        }

Any idea, what i maybe doing wrong ?

**Comment by mkArtakMSFT** [comment]
@pranavkm, do you have any ideas about this one? Thanks

**Comment by mkArtakMSFT** [comment]
@khanusman, can you please provide more details about the setup (framework version, target ? Or just share the project or a sample one so we can repro the issue?

**Comment by pranavkm** [comment]
>  do you have any ideas about this one?

Not entirely sure why this wouldn't work. But it'd be useful to have a more detailed sample to diagnose the issue.

**Comment by pranavkm** [comment]
@khanusman feel free to reopen the issue once you've have a repro application available.
