### ISSUE TITLE
Port Microsoft.AspNet.WebApi.Core to support .NET Standard 2.0

### ISSUE THREAD

**Issue by eriawan** [aspnet/Mvc#7428]
# Problem

Current Microsoft.AspNet.WebApi.Core (a.k.a. [System.Web.Http in the code](https://github.com/aspnet/AspNetWebStack/tree/master/src/System.Web.Http)) release (5.2,4) is targeted to .NET 4.5, although it depends on Microsoft.AspNet.WebApi.Client v. 5.2.4 that supports .NET Standard 2.0 nicely. 
It is quite problematic to use Microsoft.AspNet.WebApi.Core nuget in a .NET Standard 2.0 project. It may compile, but the resulting assembly will not run. 
Also looking at the current code in master branch, the csproj is still using .NET 4.5 and VS 2012 csproj model.

# Suggestion

Port Microsoft.AspNet.WebApi.Core to support multiple TFM of .NET Standard 2.0 _and_ .NET Framework 4.6.1, 4.7.1 instead of the existing TFM of unsupported .NET Framework 4.5.

If this got accepted, I'd start a PR to refactor and retarget this Microsoft.AspNet.WebApi.Core to update this to support multiple TFM of:

-  .NET Standard 2.0 (hence this will be easy to be used in .NET FW 4.7.1 project)
- .NET Standard 1.6 (to ease compatibility with .NET FW 4.6.1 project)
- .NET Framework 4.6.1 (for non- .NET Standard project)

I welcome feedback.

cc @Eilon

**Comment by eriawan** [comment]
Sorry, I think I got wrong repo. I closed this

**Comment by danroth27** [comment]
@eriawan The repo you probably want is https://github.com/aspnet/aspnetwebstack.

**Comment by eriawan** [comment]
@danroth27 
yes, thanks!
