### ISSUE TITLE
Will not grab my Newpassword - does not match any available view

### ISSUE THREAD

**Issue by JesperPetersenDk** [aspnet/Mvc#7429]
That's when, for example, I'm getting a user on the page. and sends a kind of welcome email to person. then it tells me:

ArgumentNullException: Value cannot be null. Parameter name: Email/NewPassword does not match any available view

It is the case that my registered user is in Account and when I send mail, it is in a folder at Views/Email/NewPassword.

[I have used the information contained here.](https://ppolyzos.com/2016/09/09/asp-net-core-render-view-to-string/)

Email in Views

When I try to "call" the area that I would like to get hold of, I'll do it here. And This piece of code I use in my account controller.

```
var resultMail = await _viewRenderService.RenderToStringAsync("Email/NewPassword", viewModel);
var client = new SendGridClient(m.AzureName());
var from = new EmailAddress(m.MailFrom(), m.NameFromUsername());
var to = new EmailAddress(mail, UserValue.Navn);
var plainTextContent = Regex.Replace(resultMail, "<[^>]*>", "");
var msg = MailHelper.CreateSingleEmail(from, to, title, plainTextContent: plainTextContent,
var resulta = client.SendEmailAsync(msg);
In with - RenderToStringAsync
```

Where errors like happens there is where I have written "the error is here".

```
public async Task<string> RenderToStringAsync(string viewName, object model)
    {
        var httpContext = new DefaultHttpContext { RequestServices = _serviceProvider };
        var actionContext = new ActionContext(httpContext, new RouteData(), new ActionDescriptor());

        using (var sw = new StringWriter())
        {
            var viewResult = _razorViewEngine.FindView(actionContext, viewName, false);

            //the error is here
            if (viewResult.View == null)
            {
                throw new ArgumentNullException($"{viewName} does not match any available view");
            }

            var viewDictionary = new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary())
            {
                Model = model
            };

            var viewContext = new ViewContext(actionContext, viewResult.View, viewDictionary, new TempDataDictionary(actionContext.HttpContext, _tempDataProvider),
                sw,
                new HtmlHelperOptions()
            );

            await viewResult.View.RenderAsync(viewContext);
            return sw.ToString();
        }
    }
```

**Comment by mkArtakMSFT** [comment]
Hi @JesperPetersenDk.
The first parameter to the `IRazorViewEngine.FindView` method should be the relative path (excluding the `Views` folder and the file extension) to the `cshtml` view template. In your case, you've mentioned that the view template you refer to is in the `Views/Email/NewPassword` folder, which should not be the case. So to correct path to place your template in would be `Views/Email/NewPassword.cshtml`. And in that case your call would stay exactly as is:
```csharp
var resultMail = await _viewRenderService.RenderToStringAsync("Email/NewPassword", viewModel);
```

**Comment by JesperPetersenDk** [comment]
Unfortunately, it does not work in any way.

**Comment by JesperPetersenDk** [comment]
[is this the way you think it should be? because right now it still makes mistakes.](https://imgur.com/a/J0WmC)

Error:

ArgumentNullException: Value cannot be null.
Parameter name: Views/Email/NewPassword.cshtml does not match any available view
