### ISSUE TITLE
How do we deal with flowing cancellation tokens

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#743]
Also consider how they can get injected into activated objects

**Comment by yishaigalatzer** [comment]
We should do the work for (at least as far as I can tell)

`FileResult`
`StreamFormatter`

Other `CopyToAsync` if/where we use them

**Comment by yishaigalatzer** [comment]
This is depending on having a `ClientCancellationToken` available as well as request aborted token.

**Comment by rynowak** [comment]
Blocked on aspnet/HttpAbstractions#197

**Comment by kichalla** [comment]
Closing this issue as this feature has been cut.
