### ISSUE TITLE
Overriding Generic Controller` name from Application Controller Feature

### ISSUE THREAD

**Issue by granthoff1107** [aspnet/Mvc#7436]
When Creating a generic controller in .Net Core 2.0 you may have some code which looks like this

    public class GenericControllerFeatureProvider : IApplicationFeatureProvider<ControllerFeature>
    {
        

        public void PopulateFeature(IEnumerable<ApplicationPart> parts, ControllerFeature feature)
        {
            foreach (var entityConfig in _entityConfigurations)
            {
                var entityType = entityConfig.Type;
                var typeName = entityType.Name + "Controller";
                if (!feature.Controllers.Any(t => t.Name == typeName))
                {
                    var controllerType = typeof(GenericController<>)
                        .MakeGenericType(entityType.AsType())
                        .GetTypeInfo();
                       // this doesn't work how can I override the controller name?
                       //feature.Controllers.Add(controllerType, entityConfig.ControllerName);
                }
            }
        }
    }

Normally you may set a naming convention like so:

    public class GenericControllerNameConvention : Attribute, IControllerModelConvention
    {
        public void Apply(ControllerModel controller)
        {
            if (controller.ControllerType.GetGenericTypeDefinition() != 
                typeof(GenericController<>))
            {
                return;
            }

            var entityType = controller.ControllerType.GenericTypeArguments[0];
            controller.ControllerName = entityType.Name;
        }
    }

However there are cases when the user want's to create there own custom name, which cannot be determined from the typeinfo.  Adding a controller only has an overload for typeInfo, how can I add a custom name for my controller?

**Comment by javiercn** [comment]
`IApplicationFeatureProvider<ControllerFeature>` is only responsible for determining what types are controllers. You can configure the name for your controllers through ApplicationModel. See https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model

To achieve what you want you need to do it in two stages. Stage 1 adds the types to the list of controllers in the controllersfeature as you are doing right now. Stage 2 detects the controllers you added during the configurations phase and changes the name.

Hope this helps.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by granthoff1107** [comment]
@javiercn that's a bit frusterating but better than having to dynamically generate an assembly with attributes on it

**Comment by granthoff1107** [comment]
@javiercn I do not see the section for overriding the controller names,  am I missing something?
