### ISSUE TITLE
Custom ModelBinder for IEnumerable<class> using multipart/form-data fires ModelBinder infinitely

### ISSUE THREAD

**Issue by spudcud** [aspnet/Mvc#7439]
### Title
A custom ModelBinder is being used to take Excel like data and is necessary to handle data type conversions. The ModelBinder is firing correctly but then keeps getting hit with incrementing indexes forever. 2.1 Preview 1 is being used now but I have not tried this in any previous Core version. This sample is a simplified version to show this problem but all of the working pieces are in place.

[WebApplication2.zip](https://github.com/aspnet/Mvc/files/1781751/WebApplication2.zip)

### Functional impact
This ModelBinder existed in old MVC app that we are converting to Core 2.1 Preview 1 and in bringing this ModelBinder over it was found to be unusable as it essentially loops forever.

### Minimal repro steps
Attached is a sample app that demonstrates the problem. Click the button on the Index and it will hit a Download action on the HomeController that uses the GridCellModelBinder. If a breakpoint is put in the GridCellModelBinder you can see that `a_bindingContext.ModelName` is correct but then simply keeps going and going.

The data being sent is:
```
cells: [
   {
      Col: 0,
      Row: 0,
      Value: 'Col 0 Row 0',
      CellImageTextOverlay: null,
      TreatAsString: true
   }, {
      Col: 1,
      Row: 0,
      Value: 'Col 1 Row 0',
      CellImageTextOverlay: null,
      TreatAsString: true
   }
...
]
```
and is put into FormData to be passed to the controller and expected to be bound into `IEnumerable<GridCell>`.

### Expected result
The ModelBinder should only fire for the data that is passed from the UI.

### Actual result
The action never finishes because the ModelBinder is called over and over infinitely.

### Further technical details
None

**Comment by mkArtakMSFT** [comment]
Thanks for reporting the issue.
@kichalla, can you please look into this?

**Comment by kichalla** [comment]
Notes:
Data is being posted in the following format:

```
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryBP98kpw2eoASfu6P
```
```
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[0].Col"

0
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[0].Row"

0
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[0].Value"

Col 0 Row 0
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[0].TreatAsString"

true
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[1].Col"

1
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[1].Row"

0
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[1].Value"

Col 1 Row 0
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[1].TreatAsString"

true
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[2].Col"

2
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[2].Row"

0
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[2].Value"

Col 2 Row 0
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[2].TreatAsString"

true
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[3].Col"

0
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[3].Row"

1
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[3].Value"

Col 0 Row 1
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[3].TreatAsString"

true
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[4].Col"

1
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[4].Row"

1
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[4].Value"

Col 1 Row 1
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[4].TreatAsString"

true
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[5].Col"

2
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[5].Row"

1
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[5].Value"

Col 2 Row 1
------WebKitFormBoundaryBP98kpw2eoASfu6P
Content-Disposition: form-data; name="cells[5].TreatAsString"

true
------WebKitFormBoundaryBP98kpw2eoASfu6P--
```

**Comment by kichalla** [comment]
@spudcud

Thanks for the repro application. I was able to repro the issue and here is the reason it was happening that way.

The CollectionModelBinder(CMB) tries to bind the individual GridCell items and each of these individual items is handled by your custom binder. The CMB tries builds up the model names with prefixes like cells[0], cells[1] and would go on until cells[int.MaxValue] if the child model binder does not indicate that it no longer can bind the item. So you could try fixing your custom model binder by having the following check in it:

```c#
if (!valueProvider.ContainsPrefix(a_bindingContext.ModelName))
{
    return Task.CompletedTask;
}
```

I have tried this fix myself and was able to hit the action with the populated data.

**Comment by spudcud** [comment]
@kichalla I have added this check and I am also able to get past this issue. Is this working as designed or will there be a permanent change to not require this?

**Comment by kichalla** [comment]
As per my understanding, this is working as expected.
For example, instead of a custom model binder if you are trying to bind request data to a collection of boolean, then the CollectionModelBinder(CMB) delegates the task of binding the actual bool to the SimpleTypeModelBinder (STMB) and this STMB [indicates ](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/SimpleTypeModelBinder.cs#L64-L72)if it found the value from the value providers or not. This stops the CMB from proceeding with furthers indices.
cc @dougbu, if I missed anything.

**Comment by spudcud** [comment]
Okay, thank you @kichalla. This documentation is what I was using in order to convert our old one and it didn't mention anything about this. It may help other people if it is spelled out more. [Custom Model Binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding). Obviously the example is very different from what I was doing so it is hard to show what is needed for this scenario.

Thank you for pointing me in the right direction. Loving Core btw :).

**Comment by mkArtakMSFT** [comment]
Thanks folks!
