### ISSUE TITLE
Should Value helpers use EditFormatString?

### ISSUE THREAD

**Issue by maxtoroq** [aspnet/Mvc#7442]
If both input and editor helpers use EditFormatString, shouldn't the Value[For[Model]] helpers do the same?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @maxtoroq. The Value helpers are currently targeted at `display` scenarios and not `edit` scenarios. Changing them would be a breaking change. Closing this as we have not heard sufficient number of requests about this to consider it.

**Comment by maxtoroq** [comment]
Not according to [MSDN](https://msdn.microsoft.com/en-us/library/system.web.mvc.html.valueextensions):

> Provides a mechanism to create custom HTML markup compatible with the ASP.NET MVC model binders and templates.
