### ISSUE TITLE
Custom conventions mess with multipart/form-data for uploading files

### ISSUE THREAD

**Issue by nefcanto** [aspnet/Mvc#7445]
I'm trying to reduce boilerplate codes as much as possible. Instead of writing `[FromBody]` everywhere, I wrote a custom model binding convention to always bind from body for complex types:

```
    public class ReferenceTypeBodyJsonBindingConvention : IActionModelConvention
    {
        public void Apply(ActionModel action)
        {
            if (action == null)
            {
                throw new ArgumentNullException(nameof(action));
            }
            foreach (var parameter in action.Parameters)
            {
                if (!parameter.ParameterInfo.ParameterType.IsValueType && parameter.ParameterInfo.ParameterType.FullName != typeof(string).FullName)
                {
                    parameter.BindingInfo = parameter.BindingInfo ?? new BindingInfo();
                    parameter.BindingInfo.BindingSource = BindingSource.Body;
                }
            }
        }
    }
```

As soon as I add this convention, uploading files result in *415 Unsupported Media Type* error:

```
services.AddMvc(options =>
{
      options.Conventions.Add(new ReferenceTypeBodyJsonBindingConvention());
})
```

I don't understand it. And no breakpoint of my code gets hit after enabling this convention.

I'm not sure 100% but I think it's a bug. Since my convention has many if parts, and if it's the culprit, then it should be hit at least.

Can you guide me in this regards?

**Comment by pranavkm** [comment]
There's a `FormFile` binding source for files. In, 2.1.0, we set the right `BindingSource` for form file types by default - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/DefaultApplicationModelProvider.cs#L446-L452,

**Comment by nefcanto** [comment]
Thanks for the guidance. Based on the link you sent me, I changed my code as follow:

```
public class ReferenceTypeBodyJsonBindingConvention : IActionModelConvention
{
	public void Apply(ActionModel action)
	{
		if (action == null)
		{
			throw new ArgumentNullException(nameof(action));
		}
		foreach (var parameter in action.Parameters)
		{
			if (!parameter.ParameterInfo.ParameterType.IsValueType && parameter.ParameterInfo.ParameterType.FullName != typeof(string).FullName)
			{
				parameter.BindingInfo = parameter.BindingInfo ?? new BindingInfo();
				parameter.BindingInfo.BindingSource = BindingSource.Body;
			}
			else if (IsFormFileType(parameter.ParameterInfo.ParameterType))
			{
				parameter.BindingInfo = parameter.BindingInfo ?? new BindingInfo();
				parameter.BindingInfo.BindingSource = BindingSource.FormFile;
			}
		}
	}

	private static bool IsFormFileType(Type parameterType)
	{
		return parameterType == typeof(IFormFile) || parameterType == typeof(IFormFileCollection) || typeof(IEnumerable<IFormFile>).IsAssignableFrom(parameterType);
	}
}
```

The problem is not solved. The point is, this code is never hit. I mean breakpoints I set in this code are not activated and are not hit. Had they hit, I would be able to solve the problem myself by trial and error. But now I'm stuck totally. Any ideas?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nefcanto. @pranavkm, can you please investigate this? Thanks!

**Comment by pranavkm** [comment]
Sorry, this fell off my plate. Investigating this today.

**Comment by pranavkm** [comment]
@nefcanto I can't reproduce the issue you're seeing. The convention works just fine. Here's an app I tried this out on: https://github.com/pranavkm/7445
