### ISSUE TITLE
Correct way of using MvcTestFixture's for multiple tests

### ISSUE THREAD

**Issue by tbertenshaw** [aspnet/Mvc#7449]
After Following the Example in [Preview of Function testing in Mvc apps](https://blogs.msdn.microsoft.com/webdev/2018/03/05/asp-net-core-2-1-0-preview1-functional-testing-of-mvc-applications/)
 I added one more test in the same class and it seems that the same httpclient is being used. Is this correct behaviour?

![image](https://user-images.githubusercontent.com/2010002/37091587-a1093da2-2200-11e8-9182-0471b7f8916d.png)

Code Below 
  ```csharp
 public class TestingMvcFunctionalTests : IClassFixture<TestingMvcTestFixture<Startup>>
    {
        public TestingMvcFunctionalTests(TestingMvcTestFixture<Startup> fixture)
        {
            Client = fixture.Client;
            Client.BaseAddress = new Uri("https://localhost");
        }

        public HttpClient Client { get; }

        [Fact]
        public async Task GetHomePage()
        {
            // Arrange & Act
            var response = await Client.GetAsync("/");

            // Assert
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        }
        [Fact]
        public async Task GetAboutPage()
        {
            // Arrange & Act
            var response = await Client.GetAsync("/About");

            // Assert
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        }
    }
    public class TestingMvcTestFixture<TStartup> : WebApplicationTestFixture<TStartup> where TStartup : class
    {
        public TestingMvcTestFixture()
            : base("src/TestingMvc") { }
    }
```

**Comment by mkArtakMSFT** [comment]
Hi @tbertenshaw. Thanks for bringing this up with us. This is indeed an issue in our blog post, and we'll address it shortly.
@danroth27 FYI

**Comment by mkArtakMSFT** [comment]
@javiercn FYI

**Comment by javiercn** [comment]
There is an overload on the fixture to create a client with a given base address. You can also stash the factory in a property and create one client per test instead.

**Comment by danroth27** [comment]
Blog post is now updated to use `CreateClient` method to create new `Httpclient` instances.
