### ISSUE TITLE
Apply Input Formatter at Action level?

### ISSUE THREAD

**Issue by dazinator** [aspnet/Mvc#7450]
I note from the docs that in order to use a custom formatter you have to apply it globally:

```csharp
services.AddMvc(options =>
{
    options.InputFormatters.Insert(0, new VcardInputFormatter());
});
```

However I didn't notice any option to apply a Formatter for specific Action method/s can this be done?

**Comment by mkArtakMSFT** [comment]
Hi @dazinator. You can use the `ProducesAttribute` and `ConsumesAttribute` on action level, to enforce certain formatting. You an read more about formatting with those attributes [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/formatting#forcing-a-particular-format).

**Comment by dazinator** [comment]
@mkArtakMSFT - Thanks - I found information on that page about the `ProducesAttribute` but nothing about the `ConsumesAttribute`. Should this be added to the docs?

**Comment by danroth27** [comment]
ConsumesAttribute is covered under model binding: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding#bind-formatted-data-from-the-request-body
