### ISSUE TITLE
Question: Any samples for localization for Core 2.x?

### ISSUE THREAD

**Issue by Legends** [aspnet/Mvc#7453]
Any samples for localization?

I have downloaded localization [sample](https://github.com/aspnet/Entropy/tree/dev/samples/Localization.StarterWeb) but it was core 1.x.
I moved a resx file to another location, started the app, localization didn't work anymore.
Ok, moved it back to the folder where it was before.... no way, localization was broken.
I experience this a lot with 1.x core apps, but core 2.x seems to much more stable...

Are there any 2.x samples for localization?

**Comment by Eilon** [comment]
@Legends in general everything that worked in ASP.NET Core 1.x should work the same in 2.x, though of course many bugs were fixed and features were added. Did you have a specific question about localization in 2.x?

**Comment by Legends** [comment]
Just reading through the docs, but I think I will stick with the traditional way....
Found a samples `rel/2.0_preview` branch, will try this one...

**Comment by Legends** [comment]
@Eilon Do you have a sample, how to do it the traditional way, it looks like "PublicResXFileCodeGenerator" is not supported anymore...
