### ISSUE TITLE
@inherits in _ViewImports.cshtml dont work on asp.net core 2

### ISSUE THREAD

**Issue by HolyOne** [aspnet/Mvc#7454]
I am trying to make a base page class in Razor Pages, this is my basepage

```
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BaseWeb.Web
{
    public abstract class BasePage:Page 
    {
        public string Test(string str) {

            return str;
        }
    }
}
```

then in Index.cshtml,  I inherit my page from this class this is how I do it
`@inherits BaseWeb.Web.BasePage`

But I can't inherit all my pages from my BasePage class by putting this line in _ViewImports.cshtml

If I put the same line in ViewImports,, I get this kind of error

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @HolyOne.
@pranavkm can you please look into this? Thanks

**Comment by pranavkm** [comment]
@HolyOne this seems to work fine. See https://github.com/pranavkm/7454/blob/master/Pages/_ViewImports.cshtml#L2

Could you get me a app that reproduces the problem you're running in to?

**Comment by HolyOne** [comment]
Sorry you are right
This works perfectly, I think I forgot to put abstract when derieving from
page or something :(
