### ISSUE TITLE
NullDisplayText et al. cannot be localized in display metadata provider

### ISSUE THREAD

**Issue by ridercz** [aspnet/Mvc#7458]
I'm writing [custom display metadata provider](https://github.com/ridercz/Altairis.ConventionalMetadataProviders/blob/master/Altairis.ConventionalMetadataProviders/ConventionalDisplayMetadataProvider.cs).

The `DisplayName`, `Placeholder` and `Description` properties are of type `Func<string>`, which allows to make localization while app is running, depending on current UI culture.

For other properties, like `NullDisplayText` or `FormatString` the property is a `string` so it can't be localized. These properties are important for localization as well, because you might want to display things like _nothing_ or _never_ and localize them trough the app.

**Comment by dougbu** [comment]
@ridercz thank you for your feedback. We're closing this issue as this is fixed in our working code base. Please move from ASP.NET Core MVC version 2.0.1 to 2.1.0 Preview 1. You'll then benefit from our #6730 fix.
