### ISSUE TITLE
MVC Core application hosted on IIS gives Cryptographic Exception

### ISSUE THREAD

**Issue by baffourt** [aspnet/Mvc#7460]
Hi,
We are getting CryptographicException with inner exception UnauthorizedAccessException with an IIS hosted mvc core 1.1 web app. If we just serve the application with dotnet application.dll. It runs fine without the error.
The full stack trace is attached
![image](https://user-images.githubusercontent.com/8023875/37187435-2f6409f0-2342-11e8-9ae6-270f9217b76b.png)

The Program.cs file
![image](https://user-images.githubusercontent.com/8023875/37187556-b5812388-2342-11e8-9875-7e1b3a092707.png)
Startup file
![image](https://user-images.githubusercontent.com/8023875/37187611-eca71048-2342-11e8-8a54-70d764c2debf.png)
![image](https://user-images.githubusercontent.com/8023875/37187650-188bc744-2343-11e8-8687-c718fc42179c.png)

Please help

**Comment by alexwiese** [comment]
What user are you running the AppPool as? Are you running with Load User Profile as `false`?

**Comment by baffourt** [comment]
user with AppPool is ApplicationPoolIdentity. I changed it to LocalSystem and it works. Will be trying the second option as well. The application used to work as it was, nothing changed but it started giving this error suddenly.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The behavior you're observing is because of the permissions of the user your application pool uses.
@Tratcher, do we have any guidance in docs about how to configure IIS in these scenarios?
/cc @blowdart

**Comment by Tratcher** [comment]
@shirhatti @natemcmaster

**Comment by blowdart** [comment]
Weird, permissions don't just change on their on.

You'd need to ACL the directory so the application pool ID has Modify access and ensure you turn inheritance of those permissions on.

**Comment by mkArtakMSFT** [comment]
@baffourt, did the provided suggestions solve your issue?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
