### ISSUE TITLE
How I can access app settings in web project from class library without pass it from controller.  

### ISSUE THREAD

**Issue by WaedSaleh** [aspnet/Mvc#7462]
In old version we use  WebConfigurationManager class to get the value from web config , how I can do the same for mvc core

**Comment by mkArtakMSFT** [comment]
Hi @WaedSaleh. We have a new [Configuration API](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration) in ASP.NET Core, which is available through the DI.
Your controller can accept an `IConfiguration` parameter through the constructor and it'll be resolved through the DI system.

You can also access it directly through the `HttpContext.RequestServices` property.

**Comment by WaedSaleh** [comment]
Hi @mkArtakMSFT I don't want to access it by the controller . I would like class library access it directly
