### ISSUE TITLE
Create an API to dynamically generate forms

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Mvc#7463]
We have a third-party dll which supplies a schema for a form that needs to be output on our website.

Once the website is running, when a specific page is accessed, we need to combine their schema with data to determine the input fields we need to render.

Currently, there is no API to do this.

In Web Forms we can dynamically generate a form, but in ASP.NET Core 2 we can't.

There are several other programmers who have came across this issue and have tried to put together a solution:
https://stackoverflow.com/questions/44804579/creating-dynamic-forms-with-net-core

It would be good if there was an API available to be able to port across this functionality.

**Comment by danroth27** [comment]
What kind of schema is this based on? And what kind of data are you trying to combine it with?

In Razor you can write code to conditionally render whatever form inputs you want:

```
@if (<your conditional logic here>) 
{
    <input ... />
}
```

Maybe it would help to see how you used to do this in ASP.NET Web Forms?

**Comment by Matthew-Bonner** [comment]
We have 2 different situations we have to deal with:

1. Data in the form of XML & we then transform the XML using an XSL stylesheet into HTML.
We want to move away from XML and XSLT for performance reasons.

We don't want to use Razor to generate the form, we want to parse the XML to POCO objects and then parse the POCO objects into controls (a bit like web forms) and then parse the POCO objects into HTML (we could use Razor for the last part but if we write this then an API is introduced we will be left with a whole bunch of redundant code).

2. We have an interop which provides classes which we then map to controls in web forms. We don't want to do a lot of heavy lifting here either.

We also might be moving away from Razor, so being able to generate HTML that can be embedded into a SPA web app is another use case for what the API should be able to support, in a similar fashion t Control.RenderControl in web forms.

**Comment by mkArtakMSFT** [comment]
Hi @Matthew-Bonner.
Thank you for your suggestion. We think this does not fit with the goals ASP.NET is targeting.
