### ISSUE TITLE
Rationale for using X-Powered-By and Server response headers

### ISSUE THREAD

**Issue by daveabrock** [aspnet/Mvc#7467]
Here's some typical responses I get from a client calling a Web API in ASP.NET Core (screenshot taken from Postman):

![image](https://user-images.githubusercontent.com/275862/37244185-c6c99784-244a-11e8-883e-a80958558428.png)

I'm wondering what the rationale is for including the `X-Powered-By` and `Server` header values (I understand this has been occurring long before Core was conceived). In this day and age, I wonder why we are giving the client (and anyone with bad intentions) more than they need to know. Of course, I know that the platform is very secure but it still makes me wonder.

Maybe there is a good reason - could someone fill me in or provide feedback?

**Comment by mkArtakMSFT** [comment]
@rynowak, what do you think? //cc @DamianEdwards, @blowdart

**Comment by DamianEdwards** [comment]
X-Powered-By comes from IIS, not ASP.NET Core. You can remove it in configuration if you wish. The Server header is required by spec. Anything other than random values there would identify the server, and even the pattern of random values might be enough to identify too.

**Comment by blowdart** [comment]
There are other ways to work out what the web server is than just the headers too, heck I had IIS configured to say it was Apache and nmap still got it right. There's no real security risk in returning a server string, and like Damian says the specs required it. 

X-Powered-By is another question, but it's easy enough to remove in web.config, as is the Server header should you be concerned.

**Comment by daveabrock** [comment]
Thanks for the quick feedback, guys. Yeah, I know how to exclude these from the response, but I was just wondering. The `Server` header being part of the spec makes sense. I've never been a fan of `X-Powered-By` as I've always seen it as advertising in a header, but I forgot it is part of IIS. Thanks again!

**Comment by pranavkm** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
