### ISSUE TITLE
Consuming the ApplicationModel?

### ISSUE THREAD

**Issue by JakenVeina** [aspnet/Mvc#7468]
Within ASP.NET Core...

Is it possible for me to consume the current `ApplicationModel`, rather than just inject conventions into it? I.E. can I get an instance of it outside of an MVC class, and use it to configure other parts of my application?

I'm trying to setup a joint WebApi/SignalR app, where all the main API methods are provided by MVC controllers, and SignalR simply provides a mechanism for clients to subscribe to events that MVC controllers fire off for certain data changes. I want to have clients be able to subscribe to only the events they need, through SignalR, which means I need some way for the events service to maintain a list of valid events. I'd like to have each controller define the events it can generate, rather than having events defined both in the controller code and in the SignalR code. My thought for doing this was...

```csharp
[Route("api/[controller]")]
[ApiEvent("created")]
[ApiEvent("modified")]
[ApiEvent("deleted")]
public class NewsPostsController : ControllerBase { }
```

This would define events with the names "api/newsposts/created", "api/newsposts/modified", and "api/newsposts/deleted" that are registered on the ControllerModel itself. I've actually got this part working properly, but I can't seem to find any mechanism to have my `ApiEventsService` get an instance of the `ApplicationModel`, so it can lookup whether a given event name is valid, or assemble a master list on startup of all the valid events.

**Comment by rynowak** [comment]
If you want to **read** data after it's been initialized, you should start with `IActionDescriptorCollectionProvider`. 

The application models are like the *recipe* for the action descriptors. They go away once the cake is in the oven 😆

**Comment by JakenVeina** [comment]
Yeah, that makes sense, the more I look at the code. So, how about a different question?

What would I need to do to write an `IApplictionModelConvention` that takes attributes from controller classes and uses them to route actions on a different controller. For example...

```csharp
[Route("api/events")]
public class ApiEventsController
{
    public Task<IActionResult> Subscribe();

    public Task<IActionResult> Unsubscribe();
}

[Route("api/[controller]")]
[ApiEvent("created")]
[ApiEvent("modified")]
[ApiEvent("deleted")]
public class NewsPostsController
{
    [HttpGet]
    public Task<IActionResult> Get();

    [HttpGet("{id}")]
    public Task<IActionResult> Get(int id);

    [HttpPut]
    public Task<IActionResult> Put();

    [HttpPut("{id}")]
    public Task<IActionResult> Put(int id);

    [HttpDelete("{id}")]
    public Task <IActionResult> Delete(int id);
}
```

... such that we end up with the following routings ...

```
GET /api/newsposts => NewsPostsController.Get()
GET /api/newsposts/{id} => NewsPostsController.Get(id)
PUT /api/newsposts => NewsPostsController.Put()
PUT /api/newsposts/{id} => NewsPostsController.Put(id)
DELETE /api/newsposts/{id} => NewsPostsController.Delete(id)
POST /api/newsposts/{eventName}/subscribe => ApiEventsController.Subscribe()
POST /api/newsposts/{eventName}/unsubscribe => ApiEventsController.Unsubscribe()
```

I got as far as this, within an `IApplicationModelConvention.Apply()` method...

```csharp
var apiEventsController = application.Controllers
    .First(x => x.ControllerType.Name == nameof(ApiEventsController));

var subscribeMethodInfo = typeof(ApiEventsController)
    .GetMethod(nameof(ApiEventsController.Subscribe));
var unsubscribeMethodInfo = typeof(ApiEventsController)
    .GetMethod(nameof(ApiEventsController.Unsubscribe));

var subscribeAction = new ActionModel(subscribeMethodInfo, new object[0])
{
                
};

var selector = new SelectorModel()
{
    AttributeRouteModel = new AttributeRouteModel()
    {
        Template = "api/test/somethinghappened/subscribe"
    }
};

subscribeAction.Selectors.Add(selector);

apiEventsController.Actions.Add(subscribeAction);
```

Am I on the right track?

**Comment by rynowak** [comment]
Sure, that seems like it would work. Remember that each route template on an action will be concatenated with the route template on the controller.

So you might want to specify `"somethinghappened/subscribe"` instead of `"api/test/somethinghappened/subscribe"`

**Comment by JakenVeina** [comment]
Thanks for the time, all.
