### ISSUE TITLE
Format Date issue with querystring return get, change format

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#7471]
_From @shpsyte on February 2, 2018 16:6_

# Date format issue for GET METHOD ON CONTROLLER

I'm developing an application and I get this "error", I have a data model and I have datetime properties set.

In the first GET on the page, Date format is correct, eg: dd/mm/yyyy (as defined in the data model)

But after the Second GET  the date format is changed to mm/dd/yyyy (in back end) but in view is dd/mm/yyyy
 in post I receive mm/dd/yyy but in View I see dd/mm/yyyy 

It's vary crazy

# General

I'm using .Net Core 2.0 + Bootstrap (No using any jquery, but i try too)...

For some issues, chek and details i put on GIT for reproduce this issue [REP ISSUE DATE](https://github.com/shpsyte/issueNetCoreDaet)

_Copied from original issue: dotnet/core#1252_

**Comment by Eilon** [comment]
_From @shpsyte on February 3, 2018 13:37_

any ?

**Comment by Eilon** [comment]
_From @Petermarcu on March 11, 2018 16:24_

@muratg @Eilon @ajcvickers Is this somewhere in MVC/EF?

**Comment by Eilon** [comment]
@shpsyte I suspect this is because of the following behavior in MVC:

1. Model binding (the thing that generates the parameters for your action method) will use the Invariant Culture for parsing dates from the query string
2. But rendering the output in `<input type="text" asp-for="dueDateStart" class="form-control">` will use the *current culture*

Because these two cultures are often different, this can create unexpected results.

I think you can change the `<input>` tag to remove the `type="text"` and MVC will generate the correct date markup, which I think will work correctly.

cc @dougbu @rynowak

**Comment by dougbu** [comment]
@shpsyte removing `type="text"` may allow the browser to use date widgets for your `DateTime` fields. Whether that happens depends on the browser. The widgets hide any formatting (while making the formatting more constrained due to browser restrictions). Either way, MVC will generate the correct HTML for those widgets without `type="text"`.

Also recommend using `<form method="form">` to consistently use the current culture for all user input, not just `DateTime` fields.

**Comment by Eilon** [comment]
@dougbu what's `<form method="form">` ?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by alvisemion** [comment]
I'had the same problem.
I've resolved with this code:

I've created the model binder that parse correctly date time
```
public class DateTimeModelBinder : IModelBinder
    {
        public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            if (bindingContext == null)
            {
                throw new ArgumentNullException(nameof(bindingContext));
            }

            if (bindingContext.ModelType != typeof(DateTime?))
            {
                return Task.CompletedTask;
            }

            var modelName = GetModelName(bindingContext);

            var valueProviderResult = bindingContext.ValueProvider.GetValue(modelName);
            if (valueProviderResult == ValueProviderResult.None)
            {
                return Task.CompletedTask;
            }

            bindingContext.ModelState.SetModelValue(modelName, valueProviderResult);

            var dateToParse = valueProviderResult.FirstValue;

            if (string.IsNullOrEmpty(dateToParse))
            {
                return Task.CompletedTask;
            }

            var dateTime = ParseDate(bindingContext, dateToParse);

            bindingContext.Result = ModelBindingResult.Success(dateTime);

            return Task.CompletedTask;
        }

        private DateTime? ParseDate(ModelBindingContext bindingContext, string dateToParse)
        {
            string[] dateFormats = new string[] {
                "dd/MM/yyyy",
                "dd/MM/yyyy HH\\:mm\\:ss"
            };

            if (dateFormats == null)
            {
                return ParseDateTime(dateToParse);
            }

            return ParseDateTime(dateToParse, dateFormats );
        }

        private string GetModelName(ModelBindingContext bindingContext)
        {
            // The "Name" property of the ModelBinder attribute can be used to specify the
            // route parameter name when the action parameter name is different from the route parameter name.
            // For instance, when the route is /api/{birthDate} and the action parameter name is "date".
            // We can add this attribute with a Name property [DateTimeModelBinder(Name ="birthDate")]
            // Now bindingContext.BinderModelName will be "birthDate" and bindingContext.ModelName will be "date"
            if (!string.IsNullOrEmpty(bindingContext.BinderModelName))
            {
                return bindingContext.BinderModelName;
            }

            return bindingContext.ModelName;
        }

        public DateTime? ParseDateTime(
            string dateToParse,
            string[] formats = null,
            IFormatProvider provider = null,
            DateTimeStyles styles = DateTimeStyles.AssumeLocal)
        {
            var CUSTOM_DATE_FORMATS = new string[]
                {
                "dd/MM/yyyy",
                "dd/MM/yyyy HH\\:mm\\:ss"
                };

            if (formats == null)
            {
                formats = CUSTOM_DATE_FORMATS;
            }

            DateTime validDate;

            foreach (var format in formats)
            {
                if (format.EndsWith("Z"))
                {
                    if (DateTime.TryParseExact(dateToParse, format,
                             provider,
                             DateTimeStyles.AssumeUniversal,
                             out validDate))
                    {
                        return validDate;
                    }
                }

                if (DateTime.TryParseExact(dateToParse, format,
                         provider, styles, out validDate))
                {
                    return validDate;
                }
            }

            return null;
        }
    }
```

Then i've created a modelbinder provider that use model binder.
```
public class DateCultureItaliaModelBinderProvider : IModelBinderProvider
    {
        public IModelBinder GetBinder(ModelBinderProviderContext context)
        {
            if (context.Metadata.ModelType == typeof(DateTime?))
            {
                return new DateTimeModelBinder();
            }

            return null;
        }
    }
```

Then i've configured my services:

```
 services.AddMvc(o =>
           {
               // Date time format
               o.ModelBinderProviders.Insert(0, new DateCultureItaliaModelBinderProvider());
           })
```
This way every date is well parsed in all my models in all actions.

**Comment by jigarce** [comment]
It works Thanks
