### ISSUE TITLE
Model binder for nested type (collection of interfaces)

### ISSUE THREAD

**Issue by Crypt32** [aspnet/Mvc#7477]
I'm having an issue with model binding when posting object that contains interfaces. I'm using ASP.NET MVC Core 2.0, web api. Consider the following scenario:

```C#
public class OuterClass : IOuterClass {
    public string Prop1 { get; set; }
    // this comes from interface, so I can't change the signature
    public IList<INestedClass> NestedCollection { get; } = new List<INestedClass>();
}
// I made an implementation for this INestedClass interface
public class NestedClass : INestedClass {
    public string Prop1 { get; set; }
    public string Prop2 { get; set; }
}
```
These classes reside in separate class library (not in MVC project, but I believe it doesn't really matter).

Now, my controller:
```C#
[HttpPost]
public IActionResult Post([FromBody] OuterClass createDto) {
    if (createDto == null || !ModelState.IsValid) {
        return BadRequest(new InvalidOperationException().Message);
    }
    // do POST stuff
}
```
This works as long as I don't try to post nested collection. When I do, `createDto` is always `null`. Obviously, default model binder cannot figure which type to use when building the collection. Therefore I need to write custom model binder and inherit from IModelBinder. There I should provide concrete type to use in `NestedCollection` collection. I tried to create empty model binder (which does nothing just to look what is happening).

```C#
public class NestedObjectModelBinder : IModelBinder {
    public Task BindModelAsync(ModelBindingContext bindingContext) {
        var property = bindingContext.ModelName; // returns empty string
        var value = bindingContext.ValueProvider.GetValue(property); // returns empty object
        bindingContext.Result = ModelBindingResult.Success(new OuterClass());
        return Task.CompletedTask;
    }
}
```
and update controller signature:
```C#
[HttpPost]
public IActionResult Post([ModelBinder(BinderType = typeof(NestedObjectModelBinder)][FromBody] OuterClass createDto) {
// do stuff
}
```
When posting data (from Postman) `NestedObjectModelBinder` is called. However, it shows outer object type. I have no idea how to create model binder (and let MVC to call it) for nested interface collection and help model binder to get the right type to use for it. Any thoughts?

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
Since you're deserializing JSON, all you need to do here is configure `JsonSerializerSettings` to create the right type for your interface. Something along the lines of:

```C#
public class INestedClassConverter : CustomCreationConverter<INestedClass>
{
    public override INestedClass Create(Type objectType) => new NestedClass();
}

// Startup

services.AddMvc().AddJsonOptions(options =>
{
    options.SerializerSettings.Converters.Add(new INestedClassConverter());
});
```

You don't need to create a ModelBinder unless you also want to support binding form-url encoded data.

**Comment by Crypt32** [comment]
Will this approach work when model is interface too? Say, action signature:

`public IActionResult Post([FromBody] IOuterClass createDto)`

 I know, it is an anti-pattern to use interfaces in bindings, but sometimes it is useful.

**Comment by Crypt32** [comment]
Perfect man!
