### ISSUE TITLE
Add a framework specific reference to Microsoft.DiaSymReader.Native to Microsoft.AspNetCore.Mvc.Razor

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7478]
The goal is to reference it in places where we'd generate full pdbs which is desktop .NET.

**Comment by ShadowDancer** [comment]
@pranavkm 
I would like rather to have option to force portable pdbs than packing few mb assembly for my self-contained apps.

Maybe referencing this explicite should be optional for guys who need windows pdbs?

**Comment by pranavkm** [comment]
For 2.1.0, Razor compilation uses the `DebugType` that the project specifies, so if you're targeting CoreCLR, you shouldn't see this reference and view compilation should produce portable pdbs. Unfortunately, support for portable pdbs in desktop hasn't landed as yet. To have good stack traces, and a nice developer exception page experience, we have to generate full pdbs on desktop targeting applications. https://github.com/aspnet/templating/issues/222. I was initially hoping we'd fix this in the templates, which lets users opt out if they don't care about this, but there were concerns that it would further complicate an already messy desktop template. 

Feel free to chime in on the linked issue, perhaps you may sway @DamianEdwards

**Comment by pranavkm** [comment]
Pre-req for https://github.com/aspnet/templating/issues/222
