### ISSUE TITLE
Fragile handling of array indices when rewriting JQuery request data

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7484]
Follow-on for aspnet/Mvc#7423&hellip;

The `JQueryFormValueProviderFactory` and `JQueryQueryStringValueProviderFactory` attempt to special case array indices when rewriting keys. The code checks only the first character of the key, not the entire key. The created value providers may contain partially-rewritten keys e.g. `[0abc].a0bc` when the whole string should be rewritten.

Naive fix is to rewrite bracket syntax to dot notation only when _all_ characters within the brackets are numeric. This would remove some inconsistency from the model binding system.

Might seem more correct to go in the opposite direction and rewrite only when the bracketed "key" looks like a valid C# property name. But, this may cause breaking changes and ignores `[ModelBinder(Name = "<whatever>")]` and other ways to give properties almost-any name.

----
Suggest first step is to get the aspnet/Mvc#7423 fix in. Then, experiment to see if there are scenarios where this oddity leads to user-visible issues. For example, can model binding arrays of complex types hit issues with the existing value provider factories?

**Comment by mkArtakMSFT** [comment]
Closing this as this is not a priority at the moment.
