### ISSUE TITLE
Include excluded files from project programatically

### ISSUE THREAD

**Issue by M1991** [aspnet/Mvc#7486]
I am trying to build an application that creates an image by Drawing and saves to Temp folder in server. But that file is excluded from project automatically. How to add this file again as I am unable to use the excluded file.
Error:  File is being used by another process.

My Code:
              `var p = new Microsoft.Build.Evaluation.Project(@"C:\projects\BabDb\test\test.csproj");
                    p.AddItem("Folder", @"C:\projects\BabDb\test\test2");
                    p.AddItem("Compile", @"C:\projects\BabDb\test\test2\Class1.cs");
                    p.Save();`

I suppose this function is not valid when the file is in remote server.
How will I able to resolve this.
Please comment for any update.
Thanks in advance.

**Comment by Eilon** [comment]
In .NET Core projects all files within the project folder are included, unless they are explicitly excluded. Because this is not an MVC issue, I'm closing it. This question might be better suited to https://github.com/microsoft/msbuild/issues.
