### ISSUE TITLE
Confused About Areas in Razor Pages - 2.1-Preview

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Mvc#7487]
Razor Pages in MVC: https://github.com/aspnet/Mvc/issues/6926
Areas in Razor Pages: https://github.com/aspnet/Mvc/pull/7135

I don't understand the need for `Areas` in Razor pages, especially when it adds complexity to something clean and simple, and breaks things. 

It seems that this idea came from `6926` to let MVC users use Razor Pages in MVC. The end result seems that for those of us that don't want to use MVC (and Areas) Razor Pages get broken/complicated for a trivial use case. I thought Razor Pages were an alternative to MVC.

"Areas" are already defined by your page hierarchy. To a Razor Page user, the concept of `Area` doesn't have distinct meaning. An `Area` is a folder under `Pages`. What does adding `Areas` give the Razor Page user? If the idea is to allow multiple page roots, then do that, but don't add the meaningless/redundant concept of `Areas` to Razor Pages. If you need it for implementation, hide it.

### Problem
I updated a simple Razor Pages site that worked fine to 2.1. The site doesn't use `Identity`. After the update, I now get a string of warnings about `Areas` and `Identity`:
```
The page at '/Areas/Identity/Pages/Account/AccessDenied.cshtml' is located under the area root directory '/Areas'...
```

### Reproduce
Create a new Razor Page site.
Retarget your base
```
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1).AddRazorPagesOptions(
        options => {
            options.RootDirectory = "/Processes";
         });
```
I now get a string of warnings.

What is the point of this? As a simple Razor Page user I didn't add any areas or authorization/identity, but now I'm getting these "strange" warnings.

What is the point of Razor Pages if you are going to turn them into MVC or let MVC use cases drive their design? If the driving need is for MVC users, than change MVC to use Razor Pages they way they were cleanly designed.

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback, @RandyBuchholz.
@kichalla, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
Ping @kichalla

**Comment by RandyBuchholz** [comment]
@pranavkm

> Could you share some details about how you set your app up?

 I'm just setting up the application using the default settings.
 Create a new `ASP.Net Core Web Application`, select `Web Application`, target `ASP.Net Core 2.1`, and `No Authentication`.

In `Startup.cs`, replace 
```
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
``` 

with
```
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1).AddRazorPagesOptions(
        options => {
            options.RootDirectory = "/Processes";
         });
```
Rename the `Pages` folder `Processes`.

Run the application. It will run correctly, but in the Output window you will see the warnings. E.g.,

```
Microsoft.AspNetCore.Mvc.RazorPages.Internal.CompiledPageRouteModelProvider:Warning: The page at '/Areas/Identity/Pages/Account/ResetPasswordConfirmation.cshtml' is located under the area root directory '/Areas' but does not follow the path format '/Areas/Processes/Directory/FileName.cshtml
```

**Comment by pranavkm** [comment]
@RandyBuchholz any chance you could zip up the project directory and share it here? I see these warnings if I select Individual auth, but not for the No Authentication scenario.

**Comment by RandyBuchholz** [comment]
Here you go.
[IdentityErrors.zip](https://github.com/aspnet/Mvc/files/1885214/IdentityErrors.zip)

**Comment by pranavkm** [comment]
@RandyBuchholz thanks. Looks like the warnings you were seeing were problematic in preview1. I don't see the warnings as part of preview2. Your work item did point out issues that occur with the area directory (if you opted in to Individual Auth) when you modify the RootDirectory. We're using https://github.com/aspnet/Mvc/issues/7608 to track addressing this for rc1.

Hope this addresses your concerns. Feel free to try out our preview2 bits once they're available. Hopefully it's less intrusive this time around and you don't see superfluous warnings.
