### ISSUE TITLE
Model binding accesses read-only properties in post-back

### ISSUE THREAD

**Issue by mnmr** [aspnet/Mvc#7489]
I have a simple edit model, which contains a few computed/read-only properties. When posting to a controller method, the model validation engine accesses these properties, causing an exception.

However, it does not make sense to access or attempt to validate a read-only property.

Additionally, all properties are marked with [BindNever], which seems to have no effect on this behavior.

The controller method takes a single parameter (the edit model) decorated with [FromForm].

Using 2.1.0-preview2-30355.

**Comment by mkArtakMSFT** [comment]
Hi @mnmr. `BindNever` doesn't prevent validation. To explicitly opt-out properties from validation, consider using `ValidateNeverAttribute` attribute.
