### ISSUE TITLE
 Deserializing Web Api parameter fails in case of large json

### ISSUE THREAD

**Issue by shubham1413** [aspnet/Mvc#7490]
I have a Asp.Net Core 2.0 Web API service that has a HTTP Post Method that contains a byte[] parameter which fails to get deserialized when larger JSON like 30 mb is sent as body content thus having null value. But for small json it's been able to deserialize properly into byte array.

Basically what i am trying to do is i have to send byte array to Asp.Net Core 2.0 Web Api endpoint that will upload this payload as blob storage in azure. Below is the code for Api and the calling code to this Api
Note here payload parameter is having null value:

```
 public class MyBlobController : Controller
        {

    [HttpPost("UploadPayload/{containerName}/{blobName}")]
    public async Task<string> UploadPayload([FromBody] byte[] payload,string containerName, string blobName)

       {

        //code for uploading blob

        }
    }

```
Calling code for this end point
```
var jsondata = JsonConvert.SerializeObject(payloadData);//payload is large byte array

        HttpContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");
        //Instantiating the HttpClient. 
        {
            var HttpClientInstance = new HttpClient();

            HttpClientInstance.DefaultRequestHeaders.Clear();
            HttpClientInstance.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));
            HttpClientInstance.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        }
        HttpResponseMessage apiResponse = null;
        //Sending a post request to the Blob Api.
        apiResponse = await HttpClientInstance.PostAsync("http://localhost:8999/api/MyBlob/UploadPayload/mycontainer/myblob", content);
````
I have also gone through this link https://github.com/aspnet/Announcements/issues/267 that tells us how to change the Maximum limit size of HTTP Post request i have also enabled that setting such that it is able to accept large request but still no luck with deserialization. Please suggest something that could be really useful to resolve this use case

**Comment by mkArtakMSFT** [comment]
Hi @shubham1413. Can you please share a repro project for us to investigate? Also, have you checked what are the `ModelState` errors, when you send big JSON file?

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please work with @shubham1413 on this? Thanks!

**Comment by kichalla** [comment]
@shubham1413 Can you do what @mkArtakMSFT suggested? Also you needn't serialize the byte array into json and then deserialize it back. You can post the data as StreamContent in HttpClient and read the request body as stream from within the action method

**Comment by kichalla** [comment]
Closing this issue now as we haven't heard back. Feel free to re-open this issue with more details as requested above.
