### ISSUE TITLE
Razor Pages and Filters

### ISSUE THREAD

**Issue by Dmitry44** [aspnet/Mvc#7494]
Hi!
I am trying to use ExceptionFilterAttribute on razor pages. It works fine on the top of PageModel:

```
[ApiExceptionFilter]
public class EditModel : PageModelBase
```

But it doesn't work on page handler:

```
[ApiExceptionFilter]
public async Task<IActionResult> OnGetAsync(int id)
```

Is it possible to use filters on the handler level?

**Comment by mkArtakMSFT** [comment]
@pranavkm, do you know whether this is supported or not and if yes, how should it be used? A reference to a doc would be ideal. Thanks!

**Comment by pranavkm** [comment]
Filters for Razor Pages must be applied either globally (via `MvcOptions.Filters`) or on `PageModel` instances. You cannot apply filters to individual handler methods. We're adding docs for filters in Razor Pages as part of https://review.docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/filter?branch=pr-en-us-5835, https://github.com/aspnet/Docs/pull/5835#pullrequestreview-109790703

**Comment by Rick-Anderson** [comment]
External folks can only see the PR https://github.com/aspnet/Docs/pull/5835
 https://review.docs.ms.com links are internal only

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
