### ISSUE TITLE
Razor Pages Feature - Search for Page by Folder Name

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Mvc#7496]
## Proposal
In addition to serving `index` and `default` as default pages for Razor Page routes, the routing engine also searches for a Razor Page with a name that matches the name of the containing folder.

Given the folders/files:
```
Pages
   Action1
      SubAction
          SubAction.cshtml
```

It would be nice to be able to use the route
```
Action/SubAction
```
instead of 
```
Action/SubAction/SubAction
```
This providers a cleaner url without having to clutter the application with many `index` or `default` pages, and use clearer naming.

**Comment by mkArtakMSFT** [comment]
@rynowak, do you have any thoughts regarding this? Thanks.

**Comment by mkArtakMSFT** [comment]
Ping @rynowak

**Comment by rynowak** [comment]
This is not something we're planning on doing. The convention of using `Index` to map to the directory without a filename is an old and familiar convention. If you want to do something like this for your own applications, it should be possible using `IPageRouteModelConvention` to change the routes during startup.
