### ISSUE TITLE
Multiple validation schemes

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#7498]
_From @incompletude on January 6, 2018 6:10_

I'm not sure I have a issue but I'm not sure how to approach these problems and I hope you guys can point me to the right direction. 

The first problem is related to the `[Required]` and `[BindRequired]` DataAnnotations. Seems to me a bit hacky to make my Id property nullable so I can use the Required parameter. I tried `[BindRequired]` parameter instead, and it doesn't make a difference, I get a valid model state no matter what.

```
    public class Category
    {
        [Required]
        public virtual int? Id { get; set; }
        public virtual string Name { get; set; }
    }

    [HttpPost]
    public IActionResult Post([FromBody]Category category)
    {
    }

    public class ModelStateValidationFilter : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (context.ModelState.IsValid == false)
            {
                var errors = context.ModelState
                    .SelectMany(x => x.Value.Errors, (y, z) => z.Exception == null ? z.ErrorMessage : z.Exception.Message);
                context.Result = new ObjectResult(new { type = "model", errors }) { StatusCode = 422 };
            }
            base.OnActionExecuting(context);
        }
    }
```

Currently, I use the following code so I can get different validation schemes for different http verbs. It looks extremely ugly to me. Is there a native more elegant way to achieve this considering I use a catch all errors filter?
```
    public class Category
    {
        public virtual int? Id { get; set; }
        public virtual string Name { get; set; }
        public virtual Permission Permission { get; set; }
    }

    public class CategoryCreate : Category
    {
        [Required]
        public override string Name { get; set; }
    }

    public class CategoryUserCreate : Category
    {
        [Required]
        public override int? Id { get; set; }
        [Required]
        public override Permission Permission { get; set; }
    }

    [HttpPost]
    public IActionResult Post1([FromBody]CategoryCreate category)
    {
    }

    [HttpPost]
    public IActionResult Post2([FromBody]CategoryUserCreate category)
    {
    }
```
Nice work, thank you all.

  

_Copied from original issue: dotnet/core#1193_

**Comment by Eilon** [comment]
_From @Petermarcu on March 18, 2018 16:55_

@Eilon

**Comment by mkArtakMSFT** [comment]
@dougbu, can you please share your thoughts here? Thanks!

**Comment by incompletude** [comment]
Regarding this topic,

I have given up using a catch-all automatic filter. 
I adopted using NULLABLEs, but I disagree completely with the pattern.
I'm manipulating the model state individually in each end point.

Not the best solution, could be better, but looks good enough.

```
    public static class ModelStateExtension
    {
        public static void Validate(this ModelStateDictionary modelState)
        {
            if (!modelState.IsValid)
            {
                var errors = modelState.ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value.Errors
                        .Select(e => e.Exception == null ? e.ErrorMessage : e.Exception.Message).ToArray())
                        .Where(m => m.Value.Count() > 0)
                            .Select(error => new Error { Key = error.Key, Value = error.Value }).ToList();

                throw new BadRequestException(errors);
            }
        }
    }

        [HttpGet]
        public IActionResult Get()
        {
            ModelState.Remove("id");
            ModelState.Remove("name");
            ModelState.Validate();

            ...
        }
```

**Comment by dougbu** [comment]
@incompletude I would appreciate your help understanding your exact issue or issues.

For example, when exactly does `[BindRequired]` not "make a difference"?
- If this is within a model type used with `[FromBody]`, note `[BindRequired]` is an MVC attribute and none of the deserializers (input formatters) understand it. In fact, only the MVC model binding system understands `[BindRequired]`.

And, what about your `ModelStateExtension` would like us to comment on?
- FYI my first thought is that serializing ` e.Exception.Message` from the `ModelState` can easily leak internal information about your web application.

----
> The required attribute must work for value types accordingly.

You're correct non-`Nullable` value types can't fail a `[Required]` validation.

MVC simply calls `[Required]` attributes when they are associated with properties the validation system visits. And, `[Required]` is a .NET Framework `ValidationAttribute` with well-documented semantics: Properties are invalid if they are `null`, the empty string, or contain only whitespace.

**Comment by dougbu** [comment]
> trying to have a complete automatic catch-all validation filter

Thanks for the focus.

I recommend you stick exclusively with `ValidationAttribute`s and ensure initial values for mandatory properties are invalid. Use `[Required]` on properties of complex types but something else on value types.

For example,
``` c#
    public class CategoryUserCreate : Category
    {
        [Range(0, int.MaxValue)]
        public override int Id { get; set; } = -1;
        [Required]
        public override Permission Permission { get; set; }
    }
```

**Comment by incompletude** [comment]
That is a nice idea.

**Comment by incompletude** [comment]
This is a very good idea. Gonna try that. Thx you so much for your time.

**Comment by dougbu** [comment]
For `public Boolean? Active { get; set; }`, I suggest defining a tri-state `enum` containing `Invalid`, `True` and `False` or sticking with `bool?`.

**Comment by mkArtakMSFT** [comment]
Thanks @dougbu. @incompletude, do the suggestions provided by @dougbu address your issue?

**Comment by incompletude** [comment]
Not really. But I better understand the limitations. Thx you all for your time.

**Comment by dougbu** [comment]
@incompletude thank-you for your feedback. We're closing this issue as the questions asked here have been answered.
