### ISSUE TITLE
ASPNET CORE MVC not working with External DotNet Standard Library

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#7499]
_From @Phoenigore on December 27, 2017 17:1_

# Issue Title

ASPNET CORE MVC not working with External DotNet Standard Library

# General

When you want to use a DotNet Standard Library 2.0 project into AspNet Core MVC Project from another solution, the AspNetCore MVC program crash with this error.

InvalidOperationException: Cannot find compilation library location for package 'Name.Of.DotNetStandard2.0Project'
Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List<string> assemblies).

The same test with an AspNet MVC 4.6 Framework project is a success

Regards

_Copied from original issue: dotnet/core#1184_

**Comment by Eilon** [comment]
_From @dasMulli on December 28, 2017 17:50_

How do you reference the library? a project reference or a dll reference?

**Comment by Eilon** [comment]
_From @nefcanto on January 1, 2018 12:37_

I also get this annoying error.

> Cannot find compilation library location for package 'Holism.Framework'

I'm trying to reuse my `.cshtml` files in other projects.
I have a simple class library that includes some `.cshtml` files. I've added them as embedded resources according to this [SO question](https://stackoverflow.com/questions/47726991/how-to-reuse-views-pages-in-asp-net-core-mvc).

Then I've added an application part for that assembly to my MVC service configuration.

I've also added that class library's output DLL file as a dll reference to the MVC project. Yet when I want to access that view, I get the aforementioned error.

**Comment by Eilon** [comment]
_From @Petermarcu on March 18, 2018 16:54_

@Eilon

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
@nefcanto you likely need to set [`<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>`](https://github.com/aspnet/MvcPrecompilation#options) in your csproj. 

@Phoenigore could you share more about how your project's set up?

**Comment by pranavkm** [comment]
@Phoenigore feel free to reopen the issue once you have an app available.
