### ISSUE TITLE
Calling TryValidateModel(object) created unnecessary errors when using [Required] on string properties

### ISSUE THREAD

**Issue by Groman123** [aspnet/Mvc#7513]
I'm using RazorPages and I have some troubles validating the user inputs. 

As I learned from #6891 validating the PageModel always returns true at the moment. 
I observed this bug in my program, so as mentioned as a workaround, wrapping the whole model properties as a in a dedicated viewmodel class seems to be a legal option to me.

This approach works nearly perfect, except for the fact that when I'm manually validating my viewmodel with TryValidateModel(object), I get some strange behaviour with my strings properties which are notated as [Required].
After the manual validation, where are double errors for these string fields...
One validation for key "StringValueProp" one for "model.StringValueProp".

With behaviour printing out the ValidationSummary isn't usable because all non-filled required string fields are displayed two times.

**Comment by kichalla** [comment]
Could you share a repro for this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Groman123. @kichalla, assigning this to you for further investigation. Thanks!

**Comment by kichalla** [comment]
@Groman123 I unable to repro the issue you are seeing at my end. A repro could help.

**Comment by kichalla** [comment]
Closing this issue now as we haven't received any responses yet. Feel free to re-open it with additional details.
