### ISSUE TITLE
Feature Request: Custom HTMLHelper Form CSS Classes

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Mvc#7514]
Currently the HtmlHelper CSS classes are static strings:

https://github.com/aspnet/Mvc/blob/ecedbd5372a8460055eefd269938d0b26e826d3c/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/HtmlHelper.cs#L25-L30

Frameworks like Bootstrap 3 and now 4 have lots of special styling around these same elements, but they use different values (ex. `is-valid`, `is-invalid`,`invalid-feedback`, `invalid-tooltip`, etc. more at https://getbootstrap.com/docs/4.0/components/forms/#validation)

I understand that we can write our own CSS rules to match this functionality, but it would be much nicer if we could just customize these values as part of MVC's configuration. That way we can easily tie into existing UI framework validation classes that provide much of the same functionality.

--

*Note: I searched around for similar requests but couldn't find anything. My apologies if this is already posted somewhere else.*

**Comment by mkArtakMSFT** [comment]
Hi @kspearrin.
Are you essentially looking for a mechanism to customize those `readonly` strings' values?

**Comment by kspearrin** [comment]
@mkArtakMSFT Yes.

**Comment by mkArtakMSFT** [comment]
This is actually something we've thought about https://github.com/aspnet/Mvc/issues/4888

**Comment by mkArtakMSFT** [comment]
Closing this issue in regards to the bigger effort which encapsulates this (referenced above).
