### ISSUE TITLE
Support for fallback attribute in partial taghelper to support library scenarios

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7515]
It would be neat if we can have the ability to optionally render a partial (similar to sections) either optionally or with a fallback. This is useful for libraries packing UI to allow easier composition with applications.

For example, a library could do something like

`<partial name="./_LoginPartial.cshtml" fallback="_LoginPartial />` to indicate:

Try and render that view from the main app or use the fallback if not found.

Similarly this allows UI in libraries to define "gaps" in pages/views that the consuming app can use.

/cc: @DamianEdwards

**Comment by mkArtakMSFT** [comment]
This is a valid ask and we should consider it for the future releases.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/dc2ae93c3f37ff7f44c2d09f68065b19db6a3245
