### ISSUE TITLE
Using special characters in names of properties causes an exception.

### ISSUE THREAD

**Issue by ag-petrov** [aspnet/Mvc#7533]
If we have the following model. 
```
public class SampleModel
    {
        public string gelöscht
        {
            get;
            set;
        }
    }
```
And add a view that has an editor for this property like shown below, an exception will be thrown.

```
@model TestProject.Models.SampleModel

@Html.TextBoxFor(m => m.gelöscht);
```

**Comment by Eilon** [comment]
@ag-petrov can you show what exception you're getting?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by ag-petrov** [comment]
Accept my apolgoies for the delay. Here is the exception I am getting when running the above configuration.
![error](https://user-images.githubusercontent.com/11816882/38232802-0952df5a-3721-11e8-9869-cab869f75145.PNG)

**Comment by Eilon** [comment]
Was the file saved with UTF-8 encoding (no BOM)? This looks to me like the file itself is just in the wrong format...

**Comment by ag-petrov** [comment]
After further testing it did turn out to be related to the encoding. I am marking this as closed.
