### ISSUE TITLE
IRazorViewEngine.FindView can't find precompiled view when application is deployed

### ISSUE THREAD

**Issue by NiekGr** [aspnet/Mvc#7535]
Dear Maintainers,

I use the following code in an MVC project to render an email to string:
(https://ppolyzos.com/2016/09/09/asp-net-core-render-view-to-string/)
```
public async Task<string> RenderAsync(string viewName, Model model)
        {
            var httpContext = new DefaultHttpContext { RequestServices = _serviceProvider };
            var actionContext = new ActionContext(httpContext, new RouteData(), new ActionDescriptor());

            using (var sw = new StringWriter())
            {
                var viewResult = _razorViewEngine.FindView(actionContext, viewName, false);

                if (viewResult.View == null)
                {
                    throw new ArgumentException($"{viewName} does not match any available view. searched: {String.Join(", ", viewResult.SearchedLocations)}");
                }
```

When running in Debug or Release mode everything works fine, but when I deploy my application, FindView does not find the view. Using dotPeek I can see my views in PrecompiledViews.dll beside my MVC views. "_Views_Mail_HelloWorld_cshtml"

Calling RenderAsync("Mail/HelloWorld", model) throws the ArgumentException shown in the code. FindView has the following SearchedLocations:
"/Views//Mail/HelloWorld.cshtml", "/Views/Shared/Mail/HelloWorld.cshtml", Notice the double / in the first view.

I am using AspNetCore.All 2.0.6, I do not know which IIS version I am using at this moment.

Can FindView be used to find precompiled view? If you can is this the right way? And are the double slashes in the location FindView searches correct?

**Comment by pranavkm** [comment]
Likely a dup of https://github.com/aspnet/Mvc/issues/6672, https://github.com/aspnet/Mvc/issues/6676. We made this API a bit more robust in 2.1.0. For 2.0.x, 

1. Change the code inside `RenderAsync` to include calls to both `GetView` and `FindView`. See https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs#L64-L84
2. Lookup the view using a path `/Views/Mail/HelloWorld.cshtml`, rather than by name.

**Comment by NiekGr** [comment]
Thank you @pranavkm.

But what does this mean for Layouts I'm loading in my templates? Do they also need to include the path?

**Comment by pranavkm** [comment]
The answer is likely yes, at least until you've updated to 2.1.0.

**Comment by NiekGr** [comment]
Thank you very much for helping.

Still leaves me with one question. Is the double slash in the searchlocation a bug?

**Comment by pranavkm** [comment]
It's an issue with the way `RenderAsync` is set up. The default view location lookup string looks like 'Views/{1}/{0}.cshtml` where {1} -> Controller Name, {0} -> View name. In the ordinary case, Controller always has a value. `RenderAsync` sets up an empty `ActionDescriptor` which does not have a controller name or a route value to infer the controller name from. Consequently you get the two slashes from the `null` value.

**Comment by NiekGr** [comment]
I really appreciate helping me out @pranavkm.

**Comment by NiekGr** [comment]
> But what does this mean for Layouts I'm loading in my templates? Do they also need to include the path?
Turns out this is not the case
