### ISSUE TITLE
Save an image to client temp folder, shows GDI+ error

### ISSUE THREAD

**Issue by M1991** [aspnet/Mvc#7539]
I am developing an application and everything works fine for development server but these codes don not work on remote server, application hosted at www.*****.org

Application flow : 
I have 2 jpeg files in server images folder(inside the application). What the code does is takes the 1st image, writes on it(using system.drawing) and saves to client temp folder. Again, that saved image is retrieved from clients temp folder and with a pdf writer it writes that image to pdf.

Below is the provided code for opening, writing and saving to clients temp folder

//Original Image.jpg path 
`Bitmap bitMapImage = new System.Drawing.Bitmap(Server.MapPath("~/images /NextflexAssemblyCustomerFinal.jpg")); `    
               ` Graphics graphicImage = Graphics.FromImage(bitMapImage);`   
               ` var resTemp = Path.GetTempPath();`    
               ` using (MemoryStream memoryt = new MemoryStream())`   
               ` {`      
           `using (FileStream fs = new FileStream(resTemp, FileMode.Create, FileAccess.ReadWrite))`     
                    `{`     
                   ///All drawing are done here
                  `  bitMapImage.Save((resTemp + @"\test.jpg"), ImageFormat.Jpeg); `  //Save path to clients machine
                    `byte[] bytes = memoryt.ToArray();
                     fs.Write(bytes, 0, bytes.Length);
                    }
                }
                     `

I tried saving to application temp folder, but it automatically exclude that newly created image from application and throws an file not found error. #7486 
Can anyone look into this code, I might have done some mistake.
Thanks.

**Comment by Eilon** [comment]
@M1991 can you provide a sample project and detailed steps to reproduce this issue?

**Comment by M1991** [comment]
How will the stuff work : //Comments on line-end
I have a sample image in server images folder. I need to edit that image and save a copy (without modifying the original) to server temp folder(Error occurs here) . Now, the recently saved image needs to be converted to pdf and attach to a mail (this parts works fine)

    var resTemp = Server.MapPath("~/Temp/" + User.Identity.Name);  //  Destination image in server temp folder
    MemoryStream memoryt = new MemoryStream();
    using (FileStream fs = new FileStream(resTemp, FileMode.Create, FileAccess.ReadWrite))`
        {
            Bitmap bitMapImage = new System.Drawing.Bitmap(Server.MapPath("~/images/OringinalImage.jpg"));   //Oringinal source image, not to be modified
            Graphics graphicImage = Graphics.FromImage(bitMapImage);                 
            bitMapImage.RotateFlip(RotateFlipType.Rotate90FlipNone);
            graphicImage.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.AntiAlias;                   
            graphicImage.DrawString(DateTime.Today.ToShortDateString(), new System.Drawing.Font("Century Gothic", 12, FontStyle.Regular), SystemBrushes.WindowText, new Point(1260, 30));  //Writing to the image
            graphicImage.DrawString(dDtls.drawPartno.ToString(), new System.Drawing.Font("Century Gothic", 12, FontStyle.Regular), SystemBrushes.WindowText, new Point(800, 30));  //Writing to the image
            bitMapImage.Save(resTemp, ImageFormat.Jpeg);  // Unable to save, GDI+ error throws here
            byte[] bytes = memoryt.ToArray();
            fs.Write(bytes, 0, bytes.Length);
      }

Error Trace : 
       
![image](https://user-images.githubusercontent.com/22197822/37893515-e33c6b2a-30f8-11e8-91da-3903565dd49c.png)

Will this be fine ? Please comment. Thanks for going through.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is not a question regarding ASP.NET Core MVC. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
