### ISSUE TITLE
Add tests for route data constraints in url-generation/matching

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#754]
This would be something like subareas. We want a functional test to make sure the scenario stays working. Needs to include conventional routing and attribute routing.

**Comment by rynowak** [comment]
@Eilon @danroth27 - this is a great example of what I was ranting and raving about the other day. This is more like a sample with a few tests than it is like a precheckin functional test suite.

**Comment by Eilon** [comment]
Can all the Ryans together sync tomorrow on what form this should take? If you have an idea on what a subareas-like app could look like let's build it out. I'm sure it'll come in handy for various questions we see.
