### ISSUE TITLE
Feature Request/Question: Ability to easily author/inject new directives for Razor?

### ISSUE THREAD

**Issue by fir3pho3nixx** [aspnet/Mvc#7540]
Currently, I cannot find an easy way to author/inject custom directives into Razor whilst using ASPNET Core Mvc(Kestrel). 

I can see that the `@Inject` directive gets registered within razor [here](https://github.com/aspnet/Razor/blob/2f79b90af5cbd9499f012c204f5bf4bb413ae61b/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/RazorExtensions.cs#L20). Now if I wanted to inject a custom directive to MVC on startup how would I achieve that easily? Imagining for a second I wanted to create a '@FooInjector'. 

I can see you offer access to [RazorViewEngineOptions](https://github.com/aspnet/Mvc/blob/dfa085afaf4ddb0b1063eed35e070d6189acaca2/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngineOptions.cs) is this potentially where you guys would expose something like this?

**Comment by rynowak** [comment]
We plan on enabling this kind of thing once we have support for it in tooling. 

While it would be possible for us to provide support for this in the runtime/compiler right now, the tools would not understand the new directives and would produce errors.

**Comment by mkArtakMSFT** [comment]
@rynowak, do we have a separate issue tracking this work, or should we use this one for tracking?

**Comment by rynowak** [comment]
We don't have an **issue** for it, but its on our roadmap and planning documents.

If you're deeply passionate about having an issue for it, then Razor repo is the right place to track.

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Razor#2234

**Comment by fir3pho3nixx** [comment]
@mkArtakMSFT you are a troll! 

Razor already supports this!

I need this through kestrel using aspnet mvc ....
