### ISSUE TITLE
Main application assembly not being included in the list of parts

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7544]
I'm doing new webapi and I can't hit api/values. The reason is the part for the application assembly is not being added to the list of application parts.

Manually adding the part fixes the problem. @rynowak @pranavkm.

![image](https://user-images.githubusercontent.com/6995051/37873063-8884167c-2fc9-11e8-8d97-186d4e0197a3.png)

Aside from that I also discovered out that there are other assemblies of our framework that show up as parts. 
We should exclude them by default and plug them in as parts only when a gesture is made to turn the features on. We can do this with the new partfactory support.

/cc: @SteveSandersonMS for JavaScriptServices

**Comment by pranavkm** [comment]
Should be addressed via https://github.com/aspnet/Razor/commit/1e11b5fa955e30b3ddf0410a81a957bcca7224ac. Using https://github.com/aspnet/templating/issues/400 to verify the issue is resolved once we have an updated CLI
