### ISSUE TITLE
Exception or log wrong asp-controller asp-action

### ISSUE THREAD

**Issue by zokiad** [aspnet/Mvc#7545]
Hi,

It is not a bug but I think it is a request.

Currently, we can generate a link like:

```html
<a asp-controller="Home" asp-action="IndexWrong">...</a>
```

But if asp-controller or asp-action are wrong (not found). There are no warning.
I do similar error several time: I write a wrong asp-action and my link generate is by default /. If I don't test the link manually, I wannot know my error.

Perhaps, it should generate an exception ?

**Comment by mkArtakMSFT** [comment]
Thanks @zokiad.
@rynowak, @NTaylorMullen is there a way we can improve this experience? With razor compilation can we just add turn this into a build error or warning? Thanks!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
