### ISSUE TITLE
ApplicationPartFactory fails to load factory when in a dynamically loaded assembly.

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7547]
* Load an assembly dynamically (for example in Startup with Assembly.LoadFile)
* Try to get its factory by calling ApplicationPartFactory.GetApplicationPartFactory(assembly)

It fails around here:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/ProvideApplicationPartFactoryAttribute.cs#L45

I do believe it's because of the call to Type.GetType, so we can consider switching to constructor with the type.
* For people building libraries the constructor taking a Type is a better option
* On the razor side of this, we can just have a task emit the c# file with the assembly attribute itself and include it on the compilation.
* Passing the fully qualified type, including the assembly is not very user friendly (In the testing package we allow simple assembly names for that reason).

**Comment by mkArtakMSFT** [comment]
@javiercn, what are you trying to do? Share details about the scenario please.

**Comment by mkArtakMSFT** [comment]
Closing this as there is a workaround to the problem you've been facing and this is not a common scenario users will face.

**Comment by los93sol** [comment]
What is the workaround for this issue?

**Comment by pranavkm** [comment]
The workaround is to put the factory in an assembly that's already part of the load context.
