### ISSUE TITLE
Implement custom routing inside a controller similar to routing middleware

### ISSUE THREAD

**Issue by jchannon** [aspnet/Mvc#7550]
In the routing middleware you can do something like so:

```
app.UseRouter(r =>
{
    var contactRepo = new InMemoryContactRepository();
 
    r.MapGet("contacts", async (request, response, routeData) =>
    {
        var contacts = await contactRepo.GetAll();
        await response.WriteJson(contacts);
    });
 
    r.MapGet("contacts/{id:int}", async (request, response, routeData) =>
    {
        var contact = await contactRepo.Get(Convert.ToInt32(routeData.Values["id"]));
        if (contact == null)
        {
            response.StatusCode = 404;
            return;
        }
 
        await response.WriteJson(contact);
    });
});
```

Works fine if you have two routes however what if I wanted a controller with multiple routes and multiple controllers with the same routing design eg.

```
    public class HomeController : Controller
    {
        public HomeController(IContactsRepository contactsRepo)
        {
            Get("/contacts", async (req, res, routeData) => await res.WriteAsync(contactsRepo.GetAll()));
        }
    }
```

Is there a way to implement a controller with different routing implementations but keep action results etc?

**Comment by jchannon** [comment]
Ping @DamianEdwards @davidfowl 😄

**Comment by mkArtakMSFT** [comment]
Hi @jchannon.
Doesn't the attribute routing satisfy your scenario? Why wouldn't you just define an action method with an attribute route?

/cc @rynowak

**Comment by jchannon** [comment]
Because I dislike attributes anywhere.

**Comment by mkArtakMSFT** [comment]
Unfortunately, we do not plan to change the existing routing model to cover the proposed scenario.
However, you can use `ApplicationModel` to come up with a routing model you like. Here is an example to help you get started with that: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRoutingConvention

**Comment by jchannon** [comment]
Looks like have already implemented what I'm asking
https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.Modules/DemoModule.cs

So when are you rolling that design into MVC? :)

**Comment by davidfowl** [comment]
Never 😄 . Feel free to take it and add it to Botwin.

**Comment by jchannon** [comment]
Don't need to take it, Botwin already does it :)

**Comment by jchannon** [comment]
Was just thinking of binning Botwin if MVC did the routing but guess I'll
keep going with it :)
