### ISSUE TITLE
ApiController Put methods can recieve null [FromBody]'s if the request times out at the right moment.

### ISSUE THREAD

**Issue by DanFTRX** [aspnet/Mvc#7551]
I've been seeing incidents where my ApiControllers receive a null [FromBody] tagged argument.  Upon further digging with the following debugging code:

    [HttpPut]
    public async Task<IActionResult> Put([FromBody]Example example)
    {
        if (example == null)
        {
            CheckNullFromBodyModelState(ModelState);
            return StatusCode((int) HttpStatusCode.BadRequest);
        }
        return Ok();
    }
    
    public static void CheckNullFromBodyModelState(ModelStateDictionary modelState)
    {
        if (modelState.ErrorCount != 0)
        {
            foreach (var entry in modelState.Values.Cast<ModelStateEntry>())
            {
                foreach (var error in entry.Errors)
                {
                    log(error.Exception);
                }
            }
        }
    }

I ended up tracing the issue to the timing of when a request times out.  If it times out at certain times during BodyModel binding, the controller will still be called, but with a null parameter as the body was not parsed fully.  (Shown below is an example stack trace of such a timeout)

    
    Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed():0
    Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result):0
    Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult():45
    Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.ReadableBufferAwaitable.GetResult():0
     
    Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody+<ReadAsync>d__22.MoveNext():139
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):68
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
    System.Runtime.CompilerServices.TaskAwaiter`1.GetResult():0
     
    Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream+<ReadAsyncInternal>d__21.MoveNext():135
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):68
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
    System.Runtime.CompilerServices.TaskAwaiter`1.GetResult():0
     
    Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream+<ReadAsync>d__35.MoveNext():350
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):68
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
    System.Runtime.CompilerServices.TaskAwaiter`1.GetResult():0
     
    Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions+<DrainAsync>d__3.MoveNext():386
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):68
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
    System.Runtime.CompilerServices.TaskAwaiter.GetResult():0
     
    Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter+<ReadRequestBodyAsync>d__10.MoveNext():295
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):68
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
    System.Runtime.CompilerServices.TaskAwaiter`1.GetResult():0
     
    Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder+<BindModelAsync>d__7.MoveNext():472

I believe this behavior is incorrect, and that the ApiController method shouldn't be invoked if the request has already timed out.

**Comment by pranavkm** [comment]
cc @halter73 \ @Tratcher

**Comment by Tratcher** [comment]
From the stack this is a JSON body, correct?

**Comment by DanFTRX** [comment]
Yes

**Comment by Tratcher** [comment]
@pranavkm is the model binder swallowing the exception for canceled requests?

**Comment by pranavkm** [comment]
cc @kichalla \ @dougbu who are more familiar with this area.

We handle json parsing exceptions, but don't swallow arbitrary exceptions. That said, in 1.0 \ 1.1, you could get an null instance if the request body was empty (https://github.com/aspnet/Mvc/issues/4750), maybe this is a variant of the same issue? What version of ASP.NET are you on @DanFTRX ?

**Comment by DanFTRX** [comment]
I am running ASP.NET 2.0.5, and I am also 100% confident that the request body is not empty.

**Comment by DanFTRX** [comment]
It appears to me that [this commit](https://github.com/aspnet/Mvc/commit/83c3ac62fb9187c75689a26e9749046825cdd04b#diff-366db0fc1964d1d3b1154cfee3b4b4deR180) would have fixed the symptoms I am seeing,  I can't be 100% sure, but I believe that the code change there is not in the release I am getting for the Microsoft.AspNetCore.All nuget package version 2.0.5.   So I think if those times can be confirmed by someone more familiar with the release schedules/dates/versions, this could be closed as already fixed.

**Comment by pranavkm** [comment]
@Tratcher you're right. Mvc <= 2.0.0 did swallow all formatter exceptions. @DanFTRX the issue was addressed in 2.1.0 which is our upcoming release. You could verify the fix by trying out our 2.1.0-preview1 bits (see https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-now-available/)

**Comment by DanFTRX** [comment]
Yeah I figured once I found that commit.   I can just leave null checks in my controllers until the full 2.1.0 release
