### ISSUE TITLE
embedded power bi results in microsoft login box

### ISSUE THREAD

**Issue by toy-opensource** [aspnet/Mvc#7555]
there is an excellent example for how to embed powerbi **App Owns Data** here:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embed-sample-app-owns-data/

however this example is for running on the .net platform
and some of the routines used in the example dont exist for aspnetcore

there is another excellent post about someone attempting to do the same thing:
https://community.powerbi.com/t5/Developer/Embed-Power-BI-dashboard-in-ASP-Net-core/td-p/273279

so first i built the standard .net version according to the first example
and then i tried to migrate to aspnetcore incorporating fixes from the second link

here are the urls im using:
    private static readonly string AuthorityUrl = "https://login.windows.net/common/oauth2/authorize/";
    private static readonly string ResourceUrl = "https://analysis.windows.net/powerbi/api";
    private static readonly string ApiUrl = "https://api.powerbi.com/";
    private static readonly string EmbedUrl = "https://app.powerbi.com/";

and the result is - 
the microsoft login box - not cool
can anyone tell me if they have actually embedded powerbi into aspnetcore?
if you have - can you give me a coupla hints on how to get real data back?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Home#3004
