### ISSUE TITLE
Razor Page contain IFormFiles bug - doesn't bind at all/correctly.

### ISSUE THREAD

**Issue by jonathh21** [aspnet/Mvc#7562]
Hi,

I am running into an issue where I am trying to post using a bound model containing 2 'Files' (IFormFile).

A simple form just won't post and bind 'out of the box'.

**cshtml**

```
<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <input asp-for="FileForm.FileOne"/>
        <input asp-for="FileForm.FileTwo"/>

       <input type="submit" value="Submit" class="button submit"/>
    </div>
</form>
```

**Model**

```
    public class FileForm
    {
        public IFormFile FileOne { get; set; }
        public IFormFile FileTwo { get; set; }
    }

```
**PageModel**
```
    public class IndexModel : PageModel
    {
        [BindProperty]
        public FileForm FileForm { get; set; }

        public void OnGet()
        {

        }

        public void OnPost()
        {

        }
    }
```

If you select a file and Submit the FileForm contains nothing. 

However if you add something to the model like a text input the binding works... also I notice that if you manipulate the name of the FileForms enroute or force them using name='' to be just 'FileOne'/'FileTwo'  it works.

It feels like the model binder is getting its knickers in a twist and can't 'see' the containing 'FileForm' type.

Any help gratefully received.

**Comment by mkArtakMSFT** [comment]
Hi @jonathh21.
It seems that your *cshtml* binds the same file `FileOne` to both `input` fields.
Can you please confirm that the issue remains, if you fix the cshtml?

**Comment by jonathh21** [comment]
Hi thanks for getting back to me. That is a typo in this example. Sorry about that. 

The problem remains.

**Comment by mkArtakMSFT** [comment]
Thanks for confirming, @jonathh21. We know that the experience in this situation is not ideal, and we plan to approach it from a broader perspective in the next release. In the meantime, you can use a different workaround and assign the name to the `BindProperty` attribute to fix it, as follows:
```csharp
[BindProperty(Name="FileForm")]
public FileForm FileForm { get; set; }
```

Please give it a try.

**Comment by jonathh21** [comment]
Hi - thanks for looking into this for me.

I can confirm that this workaround does indeed 'fix' it.

So is this a bug or a feature?

Thanks again.

**Comment by mkArtakMSFT** [comment]
Hi @jonathh21. Sorry for our late response.
We still aren't sure about how we will move forward with the fix here.

**Comment by dougbu** [comment]
Self-assigning since @pranavkm and I agree the approach in #8446 is less icky.

@mkArtakMSFT @danroth27 this bug is Pri 2 while #8446 was Pri 1. Which priority is correct?

**Comment by dougbu** [comment]
Not just one commit: c13e2498a8, 47d6d4e82c, c73b13f544
