### ISSUE TITLE
Add IsRequired, DefaultValue to ApiParameterDescription

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#7563]
This is low hanging fruit that we just missed for whatever reason. This means that Swashbuckle/NSwag and other libraries that produce swagger can't see default values when they apply to query string parameters, and can't tell when a parameter should be documented as 'required'.

This makes a lot more sense for us to add now that we have validation on parameters.

We currently only support default values for route parameters via https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/ApiExplorer/ApiParameterDescription.cs

The fix for would look like:
- Add `ApiParameterDescription.IsRequired` and `ApiParameterDescription.DefaultValue`
- Deprecate `ApiParameterRouteInfo.DefaultValue` - the new parameter handles more cases
- Update `DefaultApiDescriptionProvider` to add new logic to set these

By default most parameters will be **optional** because that's **the truth** of MVC. 

Now that we support validation of parameter nodes we can actually provide this data. A parameter should be considered required if it:
- Is `[FromBody]`
- Has `[BindRequired]` 
- Is a required route parameter

We may need to polish that list of conditions a bit, but that's a good start.

**Comment by mkArtakMSFT** [comment]
Thanks @rynowak. Do you think this is something we should push for during `preview2` timeframe?

**Comment by rynowak** [comment]
I don't think this is time critical. It would be nice to have for rc since it rounds out work we did in 2.1.0 but I think that depends on the costing.
