### ISSUE TITLE
ConflictResult should inherit from ContentResult, not StatusCodeResult

### ISSUE THREAD

**Issue by gregbair** [aspnet/Mvc#7565]
[ConflictResult](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/ConflictResult.cs) inherits from StatusCodeResult, which does not have a Content property. However, [RFC 2616 explicitly says](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) for this status code:

> The response body SHOULD include enough information for the user to recognize the source of the conflict. Ideally, the response entity would include enough information for the user or user agent to fix the problem; however, that might not be possible and is not required.

We are not able to specify a response body using this class.

To satisfy this, it should inherit from ContentResult instead.

**Comment by mkArtakMSFT** [comment]
@rynowak, any objections to make the change? The ask seems reasonable. Also, the `ConflictResult` has been introduced in `preview1`, so we still have time to fix this in `preview2`.

**Comment by gregbair** [comment]
I did not know that the ConflictObjectResult and Conflict method existed on the ControllerBase in 2.1.0. We're working in 2.0, where this does not exist. I'll close this.
