### ISSUE TITLE
Token based authentication in ASP.NET Core

### ISSUE THREAD

**Issue by aswanevelder** [aspnet/Mvc#7567]
Is it possible to build in the ability to generate tokens for APIs as is done in standard ASP.NET? There are plenty of examples online of building a JWT Authentication middleware but it will be greatly appreciated if this is just standard included.

**Comment by pranavkm** [comment]
cc @blowdart \ @HaoK

**Comment by blowdart** [comment]
It's possible, it's not something we provide in the box

For prebuilt things I suggest looking at [Identity Server](http://identityserver.io/) or [openiddict](https://github.com/openiddict).

**Comment by Eilon** [comment]
This issue was moved to aspnet/Identity#1716
