### ISSUE TITLE
ModelState overridden by Model

### ISSUE THREAD

**Issue by fugaku** [aspnet/Mvc#7569]
Hi,

I'm using ASP.NET Core 2.0 MVC and I'm trying to use the PRG pattern following the usage of TempData [here](https://andrewlock.net/post-redirect-get-using-tempdata-in-asp-net-core/).
This TempData will act as a holder for the previous ModelState so that we can use previous model value in case of an invalid model state after post.

```csharp
    public class HomeController : Controller
    {
        [HttpGet]
        [ImportModelState]
        public ActionResult Index()
        {
            MyModel model = new MyModel();
            return View(model);
        }

        [HttpPost]
        [ExportModelState]
        public ActionResult Index(MyModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Success", new { start = model.StartDate, end = model.EndDate });
            }
        }

        [HttpGet]
        public ActionResult Success(DateTime? start, DateTime? end)
        {
            var model = new MyModel
            {
                StartDate = start,
                EndDate = end
            };
            return View(model);
        }
    }
```
With the model 
```csharp
    public class MyModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [DisplayName("Start: ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? StartDate { get; set; }

        [Required]
        [DisplayName("End: ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? EndDate { get; set; }
    }
```
The issue happens when I'm trying to render the `StartDate` or `EndDate` property using a TagHelper.
The input element is always empty when there is an invalid model state eventhough the previous value is imported successfully from the `TempData` to the current `ModelState` using an `ActionFilterAttribute`

```csharp
    public class ImportModelStateAttribute : ModelStateTransfer
    {
        public override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            var controller = filterContext.Controller as Controller;
            var serialisedModelState = controller?.TempData[Key] as string;

            if (serialisedModelState != null)
            {
                //Only Import if we are viewing
                if (filterContext.Result is ViewResult)
                {
                    var modelState = ModelStateHelpers.DeserialiseModelState(serialisedModelState);
                    filterContext.ModelState.Merge(modelState);
                }
                else
                {
                    //Otherwise remove it.
                    controller.TempData.Remove(Key);
                }
            }

            base.OnActionExecuted(filterContext);
        }
    }
```
The value is then null on the taghelper's property on the `For.Model`
```csharp
    public class DatePickerTagHelper : TagHelper
    {
        IHtmlGenerator generator;
        public DatePickerTagHelper(IHtmlGenerator generator)
        {
            this.generator = generator;
        }

        [HtmlAttributeNotBound]
        [ViewContext]
        public ViewContext ViewContext { get; set; }

        [HtmlAttributeName("for")]
        public ModelExpression For { get; set; }

        [HtmlAttributeName("value")]
        public string Value { get; set; }

        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            output.SuppressOutput();
            var value = Value;
            var format = "yyyy-MM-dd";
            if (string.IsNullOrEmpty(value))
            {
                if (For != null && For.Model != null)
                {
                    var dt = DateTime.Parse(For.Model.ToString());
                    value = dt.ToString(format);
                }
            }
            var textbox = generator.GenerateTextBox(ViewContext, For.ModelExplorer, For.Name, value, format, null);
            textbox.Attributes["value"] = value;
            textbox.AddCssClass("form-control");
            output.Content.AppendHtml(textbox);
        }
    }
```

What am I doing wrong here?

Please see my repro [here](https://github.com/fugaku/testmodelstate)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @fugaku.
@dougbu, do you have any thoughts regarding this?

**Comment by dougbu** [comment]
Restoring the `ModelState` does not affect `For.Model` in any way. What does change is how MVC's HTML and tag helpers display the values. And what's missing here is that support in `DatePickerTagHelper`.

Recommend changing the `generator.GenerateTextBox(...)` to pass `value: null`. The HTML generator will then use the `ModelState` value.

----
Separately, why is `DatePickerTagHelper` required? The MVC `<input/>` tag helper should do the right thing (use the right format for a date picker) here i.e. the `[DisplayFormat]` attributes should be sufficient. (FYI could instead add `[DataType(DataType.Date)]` to use the same format.) Is something not working when you use the in-box tag helper?

**Comment by fugaku** [comment]
Passing the `value: null` does make it use the `ModelState` value. But the `DatePickerTagHelper` can no longer be set a value from the Model. 

How can I set the value from Model instead if the `ModelState` is not avaialble for it ?

--------------------------------

> Separately, why is DatePickerTagHelper required?

This is because I'm also using it to set other things such as
- Setup common css class for all datepicker
- Setup a datepicker js for a custom calendar control

If I'm using an MVC `<input/>` tag helper then I will have to set those up manually for every control.

**Comment by dougbu** [comment]
Avoid `For.Model` here; use `For.ModelExplorer` when calling the `IHtmlGenerator`.

Probably better to subclass `InputTagHelper` and add what you need after `base.Process(...)` returns.

**Comment by fugaku** [comment]
> Avoid For.Model here; use For.ModelExplorer when calling the IHtmlGenerator.

I'm already using the `For.ModelExplorer`

> Probably better to subclass InputTagHelper and add what you need after base.Process(...) returns.

So you're saying to leave the generation of `<input/>` element to the `InputTagHelper`. 
How do I access the `<input/>` element after that, let's say to add a css class to it ?

**Comment by dougbu** [comment]
> I'm already using the `For.ModelExplorer`

I'm saying there's no reason to set an explicit value because the `IHtmlGenerator` handles retrieving the value from `ModelState` and `InputTagHelper` handles using the specified format string.

> How do I access the `<input/>` element after that, let's say to add a css class to it ?

Make additional changes to the `TagHelperOutput parameter after the `base` method returns. `InputTagHelper` mostly updates `TagHelperOutput.Attributes` and your helper can do the same.

**Comment by mkArtakMSFT** [comment]
@fugaku, did the suggestions resolve your issue?

**Comment by fugaku** [comment]
Yes the suggestion resolve the issue. 
I'm avoiding setting the value explicitly and let the `IHtmlGenerator` to handle the value instead.
Thanks for the help.
