### ISSUE TITLE
HelperResult \ DefineSection needs to support await blocks

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#757]
Sections defined by @section are generated as 
``C#
DefineSection("foo, writer => { });
``

If the block inside the section does async operations, compilation will fail. We'd need to generate async blocks instead. 

This might need additional changes to `Write` and `WriteTo` methods to unwrap Tasks when rendering.

**Comment by yishaigalatzer** [comment]
We are going to remove support `@helpers` and thus this issue is not required.
