### ISSUE TITLE
PhysicalFileResult does not respond 304 Not Modified

### ISSUE THREAD

**Issue by jeremyVignelles** [aspnet/Mvc#7572]
I have an issue with ASP.net core (2.0.300 IIRC) : 

# Code
In my controller method, I have this kind of code:

```
[HttpGet]
public FileResult MyMethod() {
   return new PhysicalFileResult("Path/To/File", "image/jpeg");
}
```

# Expected
When I get this route with my browser, I'm expecting to see 200 the first time, and then 304.

# Actual result : 
Every time, the picture is reloaded, with a result of 200.

# Facts
- The first request happens normally, and the server replies with the `Last-Modification` header
- My browser then sets the `If-Modified-Since` header with the value it got from the first query.
- Replaying the request with `If-Modified-Since` one second later causes the server to answer with a 304

# Digging into the code
The value received here is the raw value of the modification time from the disk : 
https://github.com/aspnet/Mvc/blob/66c13ae5e56782b5129f65cb774524e9619795e1/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/PhysicalFileResultExecutor.cs#L135

Is that possible that PhysicalFileResultExecutor gets a value with microseconds, which is bigger than the value of the `If-Modified-Since` header that contains only times down to the second?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jeremyVignelles.
@Tratcher, any thoughts regarding this? Thanks!

**Comment by Tratcher** [comment]
I'd expect any rounding error to go the other way, truncating the client's last modified date so it was always less than the file system one. @jbagga can debug this. Start here and work backwards:
https://github.com/aspnet/Mvc/blob/66c13ae5e56782b5129f65cb774524e9619795e1/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/FileResultExecutorBase.cs#L228

**Comment by mkArtakMSFT** [comment]
Thanks @Tratcher.
@kichalla, how big of a change will the fix be?
