### ISSUE TITLE
Question about feature folders and serving static files inside them

### ISSUE THREAD

**Issue by valeriob** [aspnet/Mvc#7577]
Hi,
since i started with mvc i've alwasy organized my code in feature folders and not in the standard MVC pattern, so for example something like this : 
![image](https://user-images.githubusercontent.com/1522516/38134468-87242c42-3413-11e8-9ecb-b70108121cfe.png)

Before aspnet core we could easely serve static files from the project root, now that the wwwroot is used i would like to understand what's the best way to achieve this goal.

I configured the StaticFileMiddleware like the documentation suggests :

```c#
     app.UseStaticFiles(new StaticFileOptions
{
                FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "MyArea")),
                RequestPath = "/MyArea"
            });
```

and i can serve static asset located inside the feature folder, **but the asp-append-version='true' tag helper options is not working,** like @DamianEdwards explained here https://github.com/aspnet/Mvc/issues/7459 .

I experimented a bit with that concept and i tried removing the custom StaticFile configuration and implemented a custom PhysicalFileProvider.

```c#
   .ConfigureServices((ctx, services) =>
                  {
                      var myArea = new CustomPhysicalFileProvider(Directory.GetCurrentDirectory(), "MyArea");
                      var compositeFp = new CompositeFileProvider(ctx.HostingEnvironment.WebRootFileProvider, myArea);
                      ctx.HostingEnvironment.WebRootFileProvider = compositeFp;
                  })
```

The problem is that the standard CompositeFileProvider/PhysicalFileProvider works by merging all the folder like they where the same one and it "loses" the relative path "MyArea" while serving, for instance :

Configure 2  PhysicalFileProvider with those roots
PhysicalFileProvider => \wwwroot\
PhysicalFileProvider => \MyArea\resource.js
and merge them with CompositeFileProvider

Given this phisical resource \MyArea\resource.js i have to use the following path in the script tag to make it work

`<script src="~/resource.js">`

instead of 

`<script src="~/MyArea/resource.js">`

The PhysicalFileProvider basically checks if the request contains the relative subfolder 

```c#
        public IFileInfo GetFileInfo(string subpath)
        {
            if (subpath.StartsWith(_relativeFolder))
            {
                var relative = subpath.Substring(_relativeFolder.Length);
                return _p.GetFileInfo(relative);
            }
            else
            {
                return _p.GetFileInfo(subpath);
            }
        }
```

Is there a better approach to do this ? i should i just change all my scripts to use the relative path ?
Thanks

[WebApplication1.zip](https://github.com/aspnet/Mvc/files/1863392/WebApplication1.zip)

**Comment by mkArtakMSFT** [comment]
Hi @valeriob.
You've actually got it right and we'd do the same in this situation.
