### ISSUE TITLE
Any plan to include a cscss file type?

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/Mvc#7585]
Is there any plan to include a dynamically-generated css file type at some point?

I would appreciate to be able to generate dynamically some parts of the css, including some localization rules issues, calculations or whatever other things that require a smarter comutation.

**Comment by kshyju** [comment]
Include where ? Can you be a little more specific ?

**Comment by JeanCollas** [comment]
Sure.
In a Asp.Net Core project, we have cshtml files. I would like to be able to do exactly the same (generate a file), but for css files.
I don't know exactly how it could be served, maybe a specific CssController, in which we have routes, and where we can build a model, and pass it to a view of type cscss, which would output a CSS file.
And can be exactly the same thing for javascript.

This would allow to build dynamic apps, potentially build much lighter CSS files depending on the user querying the site, but also personalized, depending for example on the browser calling or the specific preferences the user has set. 

I see many applications of this.  It could in some cases do some less/sass job, but dynamically, depending on the user characteristics: changing the colors depending on the country or language of the user for example to take into account cultural differences (green buttons are rose in japan if I understood well). And could be adjusted for ltr / rtl depending on the language.
All that on a single entry-point with some parameters.

**Comment by kshyju** [comment]
Here is an idea. You can write a custom helper method which will generate the url for the css file. The helper method will analyze the current request headers and generate a unique url for that combination (Ex : If the request is coming from a mobile browser), we will create a unique url for that. Now, to serve the css, you can define a route (controller action method) which returns the CSS file. The request to this route is the url we generated earlier while rendering the HTML for the page. Your code can serve the specific css file back to the browser (this css file can be dynamically built (bundle to single file, if you have modular js approach) and cached for future requests until the hash changes).

**Comment by JeanCollas** [comment]
Thanks for your comment, however the issue is not at all to route to a specific static CSS file, but really to build a CSS dynamically, depending on anything I want, can be a color changing each hour, the font-size depending on the eyes' color of the user or anything else. 
The current issue with CSS is that they are static (even if pre-computed, they remain based on a static definition).

Some use-cases would imply that dynamic files may even allow users to customize the website appearance as much as they want.

**Comment by Eilon** [comment]
Sorry, there are no plans to build such a feature into ASP.NET Core at this time. If you feel there would be broader interest in this type of feature, this might be a great opportunity to start up your own project!
