### ISSUE TITLE
Login by email, not by username

### ISSUE THREAD

**Issue by BolatovAlau** [aspnet/Mvc#7588]
Asp.Net MVC wants to log in by username, not by email. I think mostly web apps log in by emails, not by username. And, Let's think that user changed his username, and he forgot it?!  But, he surely knows his email, so he should be logged in by email, not by username!

`PasswordSignInAsync(string UserName, string Password, bool RememberMe, bool shouldLockout)`

should be replaced by

`PasswordSignInAsync(string Email, string Password, bool RememberMe, bool shouldLockout)`

Currently I use (Account, Login) which was
```
var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);

var userid = UserManager.FindByEmail(model.Email)?.Id;
```

like this

```
var user = UserManager.FindByEmail(model.Email);

var result = await SignInManager.PasswordSignInAsync(user.UserName, model.Password, model.RememberMe, shouldLockout: false);

var userid = user?.Id;
```
Sorry for perfect English

**Comment by BolatovAlau** [comment]
and in the ForgotPassword method:

` var user = await UserManager.FindByNameAsync(model.Email);`

it wants to find a user using the name, but the parameter is an email!

it also should be replaced by

`var user = await UserManager.FindByEmailAsync(model.Email);`

**Comment by Eilon** [comment]
This issue was moved to aspnet/templating#427
