### ISSUE TITLE
More context in IApiResponseMetadataProvider or extension points to DefaultApiDescriptionProvider

### ISSUE THREAD

**Issue by BladeWise** [aspnet/Mvc#7594]
At the moment the `DefaultApiDescriptionProvider` is able to auto-generate an `ApiResponseType` having a 200 status code whose type is the runtime return type (see [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ApiExplorer/DefaultApiDescriptionProvider.cs#L439)), but this kind of functionality cannot be attained by the developer unless a specific `ProducesResponseTypeAttribute` is used on every action, passing the defined return type explicitly.

It would be nice if such runtime return type (or a more informative context) could be somehow accessed while providing the response type metadata, so that it would be possible to declare 'global' filters.
An example could better explain the purpose: let's say my Api will always return 400 and 500 providing an `Error` result, and 200 with the return type defined on the action unless a more specific 2xx is already specified for the action. I would like to avoid to decorate every action/controller with such information and would prefer to register filters to define this default behavior globally:
``` C#
services.AddMvc(o =>
                {
                    o.Filters.Add(new ProducesResponseTypeAttribute(typeof(Error), StatusCodes.Status400BadRequest)); // Error during model validation
                    o.Filters.Add(new ProducesResponseTypeAttribute(typeof(Error), StatusCodes.Status500InternalServerError)); // Error during execution (exception)
                    o.Filters.Add(new ProducesSuccessResponseTypeAttribute(StatusCodes.Status200OK)); // Default status code associated to the actual runtime return type of the action
                })
```
The `ProducesSuccessResponseTypeAttribute` could implement a more informative interface to determine if the action already has a specific _success_ response type defined and append 200 if not.
The current return type metadata resolution strategy would play nicely with this approach, since filters declared on leaves will override the default behavior.

Another possible approach would be to have a new extension point that allows the developer to resolve/manipulate the api response types programmatically, something like
``` C#
public interface IApiResponseTypesMetadataProvider
{
     IReadOnlyList<ApiResponseType> GetApiResponseTypes(ActionDescription description, IEnumerable<IApiResponseMetadataProvider> providers);
}
```

Ultimately, this behavior could be achieved replacing the `DefaultApiDescriptionProvider`, but since it lacks virtual methods or other extension points, we need to re-implement it copying and pasting the existing code...

**Comment by BladeWise** [comment]
After some digging I understood that `IApiDescriptionProvider` are actually composeable, so I could implement what I needed adding a custom provider to the pipeline, yet it feels quite a hack since some code has to be ripped out of the `DefaultApiDescriptionProvider`.

This is the provider I am using to automatically add a 200 result if no 2xx result has been already defined for an action:
``` C#
public class DefaultSuccessResponseTypeApiDescriptionProvider : IApiDescriptionProvider
{
    private static Type GetDeclaredReturnType(ControllerActionDescriptor action)
    {
        var declaredReturnType = action.MethodInfo.ReturnType;
        if (declaredReturnType == typeof(void) || declaredReturnType == typeof(Task))
            return typeof(void);

        var unwrappedType = declaredReturnType;
        if (declaredReturnType.IsGenericType && declaredReturnType.GetGenericTypeDefinition() == typeof(Task<>))
            unwrappedType = declaredReturnType.GetGenericArguments()[0];

        if (declaredReturnType.IsGenericType && declaredReturnType.GetGenericTypeDefinition() == typeof(ActionResult<>))
            unwrappedType = declaredReturnType.GetGenericArguments()[0];

        return typeof(IActionResult).IsAssignableFrom(unwrappedType) ? null : unwrappedType;
    }

    private static IApiResponseMetadataProvider[] GetResponseMetadataAttributes(ControllerActionDescriptor action)
    {
        return action.FilterDescriptors?.Select(fd => fd.Filter)
                        .OfType<IApiResponseMetadataProvider>()
                        .ToArray();
    }

    private static Type GetRuntimeReturnType(Type declaredReturnType)
    {
        return declaredReturnType == typeof(object) ? null : declaredReturnType;
    }

    private readonly IModelMetadataProvider _modelMetadataProvider;

    private readonly IList<IOutputFormatter> _outputFormatters;

    public int Order => -999;

    public DefaultSuccessResponseTypeApiDescriptionProvider(IOptions<MvcOptions> optionsAccessor, IModelMetadataProvider modelMetadataProvider)
    {
        _outputFormatters = optionsAccessor.Value.OutputFormatters;
        _modelMetadataProvider = modelMetadataProvider;
    }

    public void OnProvidersExecuting(ApiDescriptionProviderContext context)
    {
        if (context == null)
            throw new ArgumentNullException(nameof(context));
        var metadataProviders = _outputFormatters.OfType<IApiResponseTypeMetadataProvider>()
                                                    .ToList();
        const int defaultSuccessStatusCode = StatusCodes.Status200OK;
        foreach (var result in context.Results.Where(x => x.ActionDescriptor is ControllerActionDescriptor && x.SupportedResponseTypes.All(y => y.StatusCode / 100 != 2)))
        {
            var actionDescriptor = (ControllerActionDescriptor)result.ActionDescriptor;
            var contentTypes = new MediaTypeCollection();
            var responseMetadataAttributes = GetResponseMetadataAttributes(actionDescriptor);
            if (responseMetadataAttributes != null)
                foreach (var metadataAttribute in responseMetadataAttributes)
                    metadataAttribute.SetContentTypes(contentTypes);
            if (contentTypes.Count == 0)
                contentTypes.Add((string)null);

            var returnType = GetRuntimeReturnType(GetDeclaredReturnType(actionDescriptor));
            if (returnType == typeof(void))
            {
                result.SupportedResponseTypes.Add(new ApiResponseType
                                                    {
                                                            StatusCode = defaultSuccessStatusCode,
                                                            Type = returnType
                                                    });
            }
            else
            {
                var apiResponseType = new ApiResponseType
                                        {
                                                StatusCode = defaultSuccessStatusCode,
                                                ModelMetadata = _modelMetadataProvider.GetMetadataForType(returnType),
                                                Type = returnType
                                        };

                foreach (var contentType in contentTypes)
                foreach (var metadataProvider in metadataProviders)
                {
                    var supportedContentTypes = metadataProvider.GetSupportedContentTypes(contentType, returnType);
                    if (supportedContentTypes != null)
                        foreach (var str in supportedContentTypes)
                            apiResponseType.ApiResponseFormats.Add(new ApiResponseFormat
                                                                    {
                                                                            Formatter = (IOutputFormatter)metadataProvider,
                                                                            MediaType = str
                                                                    });
                }

                result.SupportedResponseTypes.Add(apiResponseType);
            }
        }
    }

    public void OnProvidersExecuted(ApiDescriptionProviderContext context)
    {
    }
}
```

I still think it could be worth to have a better extension point to plug-in a bit of logic used to determine the actual result types of an action.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @BladeWise.
@rynowak, @pranavkm any thoughts?

**Comment by rynowak** [comment]
Hi @BladeWise - sorry for the delay, it just dropped off my radar.

We intended for the providers to be composable, but I think we got some things wrong by not separating our computation into phases. You could probably simplify that code a great deal by just hardcoding content types if you don't actually do content negotiation.

> I still think it could be worth to have a better extension point to plug-in a bit of logic used to determine the actual result types of an action.

This kind of request is something we've tracking for a while now. https://github.com/aspnet/Mvc/pull/6936

Currently "attribute soup" is only want to configure this in MVC. You might have a better experience trying to use Swashbuckle or NSwag's extensibility directly.

**Comment by BladeWise** [comment]
Thanks @rynowak, I suppose you are right, but I preferred to try playing nicely with ApiExplorer, instead of brute-forcing the swagger code generation.
In the end I could achieve what I needed and was not a painful expreience, so even provider composition is not so bad.
Unfortunately, a well described API does not play nicely with client auto-generation in this case, at least with AutoREST, since you lose strong-typed clients by declaring different response types for each status code... but that's another story... :(

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback, @BladeWise.
I'm closing this issue as we already track the main concerns raised here in different issues. Hopefully we'll be able to address those quite soon.
