### ISSUE TITLE
Bundling and minification broken

### ISSUE THREAD

**Issue by ipjohnson** [aspnet/Mvc#7596]
I know that bundling and minification were removed from MVC proper but the replacement documented by ms [here](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?tabs=visual-studio%2Caspnetcore2x) is broken with [bootstrap 4](https://github.com/madskristensen/BundlerMinifier/issues/218) and has been for a year+ with no fix in sight.

I understand the desire to lean on open source to not have to reinvent the wheel but this seems like a huge feature gap and one that is very painful. At some point developers want to be productive and not have to find new solutions to problems that had been solved.

@davidfowl , @Eilon any thoughts?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Home#3023
