### ISSUE TITLE
Suggestion: Allow using interfaces for controllers

### ISSUE THREAD

**Issue by aelij** [aspnet/Mvc#7597]
We're building a microservices-based system using Service Fabric and MVC, and many of the services are internal. In order to ease the development of those services, I've created an `IApplicationModelProvider` (a bit [hacky](https://gist.github.com/aelij/7a6f8c51deaa14b4f3783122afc2242b) but works) that also reads route and verb attributes from interfaces which are shared between services. This makes them very easy to consume. Essentially turning MVC to RPC-style calls.

For example:

```csharp
[ContractRoute("api/foo")]
public interface IFooService
{
    [HttpGet("{type}"]
    Task<List<Foo>> GetFoo([FromRoute] string type);
    [HttpPost]
    Task<Foo> UpdateFoo([FromBody] Foo foo);
}
```

The controller just implements the interface with no attributes at all.

I've also written a Roslyn analyzer and code generator that creates clients from those interfaces using `HttpClient` and the `Microsoft.AspNet.WebApi.Client` package. The analyzer checks the contract for:

* Valid route template syntax
* Match route parameters with method parameters
* All parameters have binding attributes (implicit not allowed)

Some of those diagnostics could probably be used by any controller.

Note this is not meant to replace Swagger, which is great for public APIs.

**Comment by mkArtakMSFT** [comment]
Hi @aelij. Can you please provide more details about the scenario and why do you do that? Thanks!

**Comment by aelij** [comment]
@mkArtakMSFT

The idea is that with services that are in the same repo/solution, using Swagger is a bit of a hassle. If both the controller and the generated client implement the same interface, they're always in sync, and that's guaranteed at compile time. If I changed the contract, I'd have to change the implementation and the call site.

The idea is somewhat similar to [Refit](https://github.com/paulcbetts/refit) but instead of a separate interface for the client with different attributes, I use MVC's attributes, and write them just once.

This makes the development of a system with a large amount of non-public services much simpler IMO.

**Comment by mkArtakMSFT** [comment]
Thank you for your feature request. We'll consider this feature during the next release planning period and update the status of this issue accordingly. To help us prioritize this feature correctly, please make sure you provide as much information as possible about the scenarios and their importance.

**Comment by mikeandersun** [comment]
[This](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Endpoints/UserInfoEndpoint.cs) may give an inspire.

**Comment by mkArtakMSFT** [comment]
Hi @aelij.

This sounds like an interesting idea. If you'd like to build something like this, and hit any blockers we'd be interested in learning about these to unblock you, if possible.
