### ISSUE TITLE
Razor Pages do not use localized page files

### ISSUE THREAD

**Issue by jaska45** [aspnet/Mvc#7600]
I want to localize complete Razor page files. I tried to do in the same way as it works in MVC. This means that I add localized cshtml files. For example for Index.cshtml I added Index.fi.cshtml that is identical to the original English page file except strings are in Finnish. Then I configured Startup.cs with the normal localization related settings and ran the application. Finnish page file did not load. 

Is this supposed to work? If not can you implement it. Localizing a large web application by using resx strings is just too complicated for developers. I use an excellent localization tool that can make localized cshtml files very easily and keeps them in sync with the original files.

I am using ASP.NET Core 2.1.0-preview1-final

[Razor.zip](https://github.com/aspnet/Mvc/files/1877652/Razor.zip)

**Comment by jaska45** [comment]
This seems to be duplicate of [](https://github.com/aspnet/Mvc/issues/7332)

**Comment by mkArtakMSFT** [comment]
Thanks @jaska45. Correct, this is a dup, so closing to track only in one place.
