### ISSUE TITLE
A complex action parameter isn't shown as required when marked with `RequiredAttribute`

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#7603]
Using 2.1.0-preview2:

When configuring the following two APIs on the controller:
```csharp
[HttpPost]
public IActionResult ApiWithComplexParameters(Movie nonRequired, [Required]Movie required)
{
    return Ok();
}

[HttpPost("/custom")]
public IActionResult ApiWithSimpleParameters(string nonRequiredParam, [Required]string requiredParam){
    return Ok();
}
```

Swagger shows only the `string requiredParam` as required and the red asterisk isn't shown for the `Movie required` parameter:
![image](https://user-images.githubusercontent.com/34246760/38382737-95f0174e-38bf-11e8-9baa-5390e693a2d7.png)
![image](https://user-images.githubusercontent.com/34246760/38382755-a024e55a-38bf-11e8-8ef8-abeac9ca025e.png)

**Comment by dougbu** [comment]
Suggest this issue duplicates #7360. We closed that issue and instead plan to add an analyzer about using `[Required]` on top-level nodes (#7415).

**Comment by mkArtakMSFT** [comment]
Agree, this would fall into the same category. Closing as dupe of https://github.com/aspnet/Mvc/issues/7360
