### ISSUE TITLE
Remove root directory customization options for Razor Pages areas

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7608]
Loosely based on https://github.com/aspnet/Mvc/issues/7487

`RazorPageOptions.RootDirectory` is used to determine two things today (https://github.com/aspnet/Mvc/issues/7345), the "Pages" directory at the root as also the "Pages" directory in the area root. If a user changes the value for one, Identity UI for instance would be completely broken. We could fix this by stashing more metadata in the library that says what these values were at the time the library was complied. However, things start getting more hairy if the user now wants to override Razor Pages (we'll limit ourselves to that in this issue) from the library in the app. They have to 

a) Know the paths that the library author choose.
b) Put Razor Pages in locations that the app will not serve by default. They will only get served as virtue of overriding a path from a library, which is not how the override behavior works by default.

My proposal is to make the area page lookup paths non-configurable i.e. it's always `/Areas/{AreaName}/Pages` and encourage library authors to standardize around this. Once patterns emerge and we have more feedback about the kind of options authors want, we can design features around it.

**Comment by pranavkm** [comment]
cc @DamianEdwards \ @rynowak

**Comment by DamianEdwards** [comment]
This seems like the most sensible tactical change at this stage.

**Comment by DamianEdwards** [comment]
We need to do this in rc1 of course.

**Comment by pranavkm** [comment]
Yup. Self assigning for 2.1.0-rc1.
