### ISSUE TITLE
Encrypt the Secrets.JSON 

### ISSUE THREAD

**Issue by j0nimost** [aspnet/Mvc#7611]
Recently as i was working on a team project I saw a developer store encryption Keys in the Secrets.Json for sure this is not advisable but according to him storing the Key inside a class then pushing the code to a version control accessible to other team members was worse. Obviously this meant he had to access the Secrets.JSON at all times be it in Production or Development environments. I would be nice to have the Secrets.JSON encrypted and Partially accessible that is only certain Json Objects are accessible at run time in regardless of the environment.

**Comment by Eilon** [comment]
What is `Secrets.Json`? Is this in reference to [user-secrets](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=visual-studio)?

We highly recommend avoiding checking in *any* secrets into source control. The user-secrets tool is designed to store *development time secrets* in a location outside of source control.

cc @blowdart

**Comment by j0nimost** [comment]
Oh i see. I actually thought i can be used on production. Thanks for clearing that up.
