### ISSUE TITLE
fail to apply Guid route constraint?

### ISSUE THREAD

**Issue by JerryBian** [aspnet/Mvc#7612]
I am not quite sure whether I did it wrong. From [doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing#route-constraint-reference) it seems following is valid for routing, but when I tried to access it always return 404.

```
[Route("/test/{id:guid}")]
public IActionResult Test([FromRoute]Guid id)
{
    Trace.TraceInformation(id.ToString());
    return Ok();
}
```

e.g. http://localhost:63950/test/826510d7-00b7-42cc-aeea-6f455f19ec4b

Do I need to setup somewhere to enable Guid support for routing? Thanks.

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please look into this? Thanks!

**Comment by JerryBian** [comment]
How to reproduce is rather easy.

Create an application with VS's default ASP.NET Core MVC template, and put above `Action` method to `HomeController`, that's it.

cc @kichalla

**Comment by mkArtakMSFT** [comment]
Thanks @JerryBian!

**Comment by kichalla** [comment]
@JerryBian  I am unable to repro this scenario in 2.0.3 or the latest version.

**Comment by JerryBian** [comment]
ah, I can't explain. I am trying to post a demo for you this morning, so I created things from scratch, and you guess what: it works.

Thanks for you time anyway, I think we can close this issue now.

cc @mkArtakMSFT @kichalla

**Comment by mkArtakMSFT** [comment]
Thanks @JerryBian. Glad things worked out well for you.
