### ISSUE TITLE
Razor Pages looses query param "page"

### ISSUE THREAD

**Issue by tidyui** [aspnet/Mvc#7613]
First off, this seems **extremely odd**, but I can reproduce it over and over and I can't get around it. My page is getting a bunch of query parameters, everything is working except **one** which never gets any value. This param is named `page`, and is simply passed in as paging to a blog archive.

I've just taken out the piece not working into a simple test page and the error is the same:

    @page
    @model TestModel
    @functions {
        public class TestModel : PageModel
        {
            public string Id { get; set; }
            public int? Page { get; set; }
            public int? Year { get; set; }

            public void OnGet(string id, int? page = null, int? year = null)
            {
                Id = id;
                Page = page;
                Year = year;
            }
        }   
    }

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10">
                Id: @Model.Id<br>
                Page: @Model.Page<br>
                Year: @Model.Year
            </div>
        </div>
    </div>

Requesting the page with the following shows no input for the parameter page when rendered.

    GET localhost:5000/test?id=1234&page=5&year=2018

**However**, if I just change the name of the param from `page` to `pagenum` it starts to work. This is however not possible for me as the parameter is given to me from middleware which is not in my application. 

    @page
    @model TestModel
    @functions {
        public class TestModel : PageModel
        {
            public string Id { get; set; }
            public int? Page { get; set; }
            public int? Year { get; set; }

            public void OnGet(string id, int? pagenum = null, int? year = null)
            {
                Id = id;
                Page = pagenum;
                Year = year;
            }
        }   
    }

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10">
                Id: @Model.Id<br>
                Page: @Model.Page<br>
                Year: @Model.Year
            </div>
        </div>
    </div>

Now, executing the following request shows data for all params:

    GET localhost:5000/test?id=1234&pagenum=5&year=2018

As there's no difference between the two except the name of the querystring param, I'm starting to wonder what's going on in the background :)

Regards

**Comment by pranavkm** [comment]
The term `page` (like `controller`, `action`, and `area`) is reserved for routing in Razor Pages. Using a different name like `pagenum` would be the easiest solution here.

**Comment by tidyui** [comment]
Aha, is this documented somewhere, because I couldn't find any information about it? The param `page` is unfortunately quite a common name for any application with paged lists. Is there a particular reason for reserving such obvious names for internal routing when something a bit more obfuscated, like `aspnet_routing_page` could've been used?

Anyway, since I control the code of the framework passing in the parameter I can add a compatibility param with a different name for when it's used with Razor Pages and not MVC.

Thanks for the quick response!

Regards

**Comment by mkArtakMSFT** [comment]
Thanks @pranavkm.
@danroth27, is this something we have documentation on?

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/issues/5915
