### ISSUE TITLE
TempData doesn't work in the presence of a cookie consent policy

### ISSUE THREAD

**Issue by ericwj** [aspnet/Mvc#7616]
By default, the template used by `dotnet new web` for example sets up the `CookiePolicyOptions` to always require consent:

```CS
services.Configure<CookiePolicyOptions>(options => {
	// This lambda determines whether user consent for non-essential cookies is needed
	// for a given request.
	options.CheckConsentNeeded = context => true;
	options.MinimumSameSitePolicy = SameSiteMode.None;
});
```

The temp data cookie written by [CookieTempDataProvider](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/CookieTempDataProvider.cs#L103) is not marked as essential, meaning that no temp data cookie is written if the user has not given consent. However, temp data imho almost exclusively deals with the kind of cookies for which consent is never needed. In the first place because it is quite hard to make them survive very long.

The behavior described can afaik only be modified site-wide by marking the temp data cookie as essential, using for example the following code in `Startup.cs`:

```CS
public void ConfigureServices(IServiceCollection services) {
	services.Configure<CookieTempDataProviderOptions>(options => {
		options.Cookie.IsEssential = true;
	});
	...
}
```

Without it, no temp data cookie is ever written for as long as there is no consent cookie (yet). This makes for a poor experience for pages that require a bit of temp data to work, even if these uses are well within the uses for which consent is never needed.

I think the temp data cookie should be marked essential by default or in the templates.

`CookieTempDataProvider` does not allow to provide a distinction in any way between essential and non-essential data on a case-by-case basis. This is probably the real issue here if it is considered inappropriate to mark all temp data cookies essential without exception by default. I wouldn't mind.

Certainly it is a bad idea to have temp data not work by default, having to guard every use of it at every turn.

**Comment by Eilon** [comment]
cc @blowdart @javiercn @Tratcher 

I recall we had some discussion about which cookies should require consent and the TempData cookie was not considered essential due to what it is typically used for. I think we decided that because TempData is so ephemeral (it can disappear so easily), it would be difficult to consider it essential because if it was so essential it wouldn't be so ephemeral.

**Comment by javiercn** [comment]
That was the outcome of that discussion. This is by design.

**Comment by blowdart** [comment]
Yes, by design. Darned GDPR.

**Comment by Tratcher** [comment]
CookiePolicyOptions has some callbacks on a per-cookie basis that can override the behavior, but they're pretty clumsy. In practice you must either have consent or mark your cookie as essential.

**Comment by ericwj** [comment]
`CookiePolicyOptions.OnAppendCookie` => `AppendCookieContext` yeah but why am I here and what for

While talking about this, there a way to make this code vastly better? I figure I can shorten it a bit by taking a dependency, but that is a pattern I would have to repeat in every place I use this method.

```
public static bool IsPrivacyPolicyAccepted(this HttpContext httpContext) {
	var cookie = httpContext
		.RequestServices
		.GetRequiredService<IOptions<CookiePolicyOptions>>()
		.Value
		.ConsentCookie
		.Name;
	var present = httpContext
		.Request
		.Cookies
		.TryGetValue(cookie, out var value);
	return 0 == string.Compare("yes", value, ignoreCase: true);
}
```

Thanks in advance

**Comment by Tratcher** [comment]
`httpContext.Get<ITrackingConsentFeature>().CanTrack`
https://github.com/aspnet/HttpAbstractions/blob/a6bdb9b1ec6ed99978a508e71a7f131be7e4d9fb/src/Microsoft.AspNetCore.Http.Features/ITrackingConsentFeature.cs#L12-L25

**Comment by ericwj** [comment]
Thanks!

**Comment by ericwj** [comment]
`[CS1061](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1061)` on `HttpContext.Get<T>()` though. Was that a shorthand? Cute!
