### ISSUE TITLE
AddPageRoute doesn't remove Index when it should

### ISSUE THREAD

**Issue by kevin-jing** [aspnet/Mvc#7624]
I use the following code to change the default page:
`            services.AddMvc().AddRazorPagesOptions(options =>
            {
                options.Conventions.AddPageRoute("/Transactions/Index", "");
            });`

But receive an error:
An unhandled exception occurred while processing the request.
AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:

Page: /Index
Page: /Transactions/Index
Microsoft.AspNetCore.Mvc.Internal.ActionSelector.SelectBestCandidate(RouteContext context, IReadOnlyList<ActionDescriptor> candidates)

The workaround is to rename Index.cshtml, but could you fix this issue?

**Comment by pranavkm** [comment]
There are two pages in your application with the same route. `AddPageRoute` will not affect routes in the application (this could include other controller actions if you're mixing controllers and Razor Pages). The user's responsible for configuring the application the right way.

**Comment by kevin-jing** [comment]
So what's the right method to change the default page?
