### ISSUE TITLE
WebApplicationFactory should provide a virtual Dispose() method

### ISSUE THREAD

**Issue by martincostello** [aspnet/Mvc#7631]
The `WebApplicationFactory<T>` class in Microsoft.AspNetCore.Mvc.Testing should provide the standard `protected virtual void Dispose(bool disposing)` method to allow derived classes to override the method to dispose of resources they might create themselves.

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue. We agree that this seems to be a bug and we've assigned one of our team members to look into this based on its priority.

**Comment by martincostello** [comment]
I can do a PR to add this for 2.1.0 if wanted? Otherwise in 2.2.0 would it be a breaking change to the public contract?

**Comment by rynowak** [comment]
Feel free to send us a pr, that would be helpful 👍
