### ISSUE TITLE
Verify the fix for MVC.Testing incompatible with conventional routing in current MVC apps using the shared runtime

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7632]
Verifying that the changes here work E2E.

Original issue: https://github.com/aspnet/Mvc/issues/7617

**Comment by pranavkm** [comment]
Self assigning so I can verify this once we have a build of everything.

**Comment by mkArtakMSFT** [comment]
@pranavkm, should this be a verification issue instead?

**Comment by pranavkm** [comment]
Verified this using M.A.App and M.A.All v2.1.0-rc1-30639.
