### ISSUE TITLE
Update MSBuild targets in Microsoft.AspNetCore.Mvc.Testing to not use AssemblyAttribute

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7647]
This breaks when the user sets GenerateAssemblyInfo to false and we plan to update all the places where we use it.

**Comment by mkArtakMSFT** [comment]
This doesn't look like a high priority issue, so will wait for more feedback regarding this ask.

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please add a cost to this? Thanks!

**Comment by javiercn** [comment]
It's pretty much done. I put a PR a while ago when we were determining if we were taking it on ask mode. Given it current status, I'll just address @pranavkm feedback on it and merge it when I have some time. It's not at all urgent.

**Comment by javiercn** [comment]
We don't have plans to do this. We can revisit in the future as the scenario is unlikely to happen on test projects.
