### ISSUE TITLE
data-val-number is not added to int fields

### ISSUE THREAD

**Issue by thegodliek** [aspnet/Mvc#7652]
I've tested this using the MVC visual studio template (not razor pages), the unobtrusive data tag for int fields are not added to the html output, for example:

the view model class:
`public int Test { get; set; }`

the razor view:
`<input asp-for="Test" class="form-control" />`

the html result:
`<input class="form-control" data-val="true" data-val-required="The Test field is required." id="Test" name="Test" value="" type="number">`

The problem is that now if I enter a text that is not a number, I'm getting the default jquery.validate message " Please enter a valid number. ", but if I manually add the data-val-number="some message", I get correctly the message I want.

Any thoughts?

thank you

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @thegodliek.
From where do you expect the `some message` part be picked up?
@kichalla any thoughts regarding this?

**Comment by kichalla** [comment]
@thegodliek which browser are you using? most of the modern browsers understand `type=number` in the generated html and do not allow to enter non-numeric text in it. Would like to understand how you are seeing the error message if you cannot enter the non-numeric text to begin with.

**Comment by thegodliek** [comment]
@kichalla I've tested it on almost all major browsers, Yes I can enter non-numeric text.

**Comment by thegodliek** [comment]
@mkArtakMSFT when I add the data-val-number attribute manually, it's picked up by the jquery.validation.unobtrusive library, please correct me if I'm wrong.

**Comment by mkArtakMSFT** [comment]
@thegodliek, you're right, Edge doesn't respect it, while Chrome does.
Still, I'd like to know how do you envision the experience? From where do you expect the validation message to be picked up? In the situation where you manually specify `data-val-number="some message"` you do provide the `some message` part explicitly. In case of the razor view and the model class that information is still missing. Do you expect some default message to be shown?

**Comment by thegodliek** [comment]
> In case of the razor view and the model class that information is still missing.

This is part of the problem, there is no way I can change that message in my model, there are no attribute that can be used for this.

In the classic MVC days, you change the `data-val-number` message by using

`ClientDataTypeModelValidatorProvider.ResourceClassKey = "someresourcekey";`

and put a resource key named `FieldMustBeNumeric` with the message you wanted, possibly localized.

In dotnet core MVC I can't do that, the `data-val-number` isn't rendered, and there's no way as far I can tell to customize this message using attributes in the view model or even resource keys like the above example.

This is the main issue, we can't customize the validation message for `input type=number` using resources that allows us to localize and customize client validation messages unless we add the data attribute manually which feels a bit hacky and nonstandard specially when you can use resource files for other client side validation messages no problem.

**Comment by kichalla** [comment]
I will back to this after my current task. Based on our offline discussions with @dougbu , we will mostly not fix this as it would be a breaking change, but I am thinking of a workaround which is simple and would apply to all integer models across the app (for example, using EditorTemplates)

**Comment by kichalla** [comment]
This is by design as the `number` validation of jquery-validation is not what you expect it to be and we default to brower's validation. (more info: https://stackoverflow.com/a/16728588). Even if you were using a workaround (like to add `data-val-numner` manually) for this the end user experience is incorrect.

**Comment by thegodliek** [comment]
2 Points here, 

First, as mentioned in the thread, default browser's validation doesn't work in all browsers to it's not really a thing to rely about.

Second, this doesn't really address the core issue which is, we still cannot change the validation message of integers in the view model just like we do in other validations, which is in my opinion an inconstant design.

thank you for your reply.
