### ISSUE TITLE
Remove checked in msbuild.binlog from Mvc

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7664]
* [  ] Delete the file
* [  ] Delete the file from existence (https://rtyley.github.io/bfg-repo-cleaner)

**Comment by pranavkm** [comment]
cc @javiercn

**Comment by jbagga** [comment]
The tool requires a force push (not just push) so this cannot be done. cc @pranavkm

**Comment by pranavkm** [comment]
😿
