### ISSUE TITLE
Add existing MVC applications as perf tests

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#7668]
We should add our two existing (simple) test apps as workloads for the aspnet/benchmarks system

https://github.com/aspnet/Performance/tree/dev/testapp/BasicViews
https://github.com/aspnet/Performance/tree/dev/testapp/BasicApi

/cc @sebastienros

**Comment by mkArtakMSFT** [comment]
Closing this as a dupe of https://github.com/aspnet/Mvc/issues/7805
