### ISSUE TITLE
Url.IsLocalUrl should return true when Scheme & Host match

### ISSUE THREAD

**Issue by epignosisx** [aspnet/Mvc#7669]
Url.IsLocalUrl returns false for all absolute urls even when the absolute url matches the current request url.

It would be ideal if for absolute urls it would return true if Scheme & Host match. Similar to what's done here:

https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Utility/Extensions/HttpRequestExtensions.cs#L94-L101

**Comment by blowdart** [comment]
That's not what IsLocalUrl is for. It's to indicate a non-absolute URL. Whilst I can see your argument the current behaviour is baked into too many places to change it.
