### ISSUE TITLE
How to publish console app as a WebJob rather than Web App

### ISSUE THREAD

**Issue by Liero** [aspnet/Mvc#7677]
Hi,
I have a console app that I want to deploy as web job. It's based on [Entropy/samples/Mvc.RenderViewToString/](https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString) sample.

The problem is, that is uses `Microsoft.NET.Sdk.Web` rather than `Microsoft.NET.Sdk` in order to render the razor views although it is not web application.

When I invoke the publish dialog, it publishes it as web app, not as web job. When I replace <strike>Microsoft.NET.Sdk.Web</strike> with Microsoft.NET.Sdk, it shows the correct web job publish dialog, but then I get runtime exception when I try to invoke the razor view.

```
<Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Sdk.Publish">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess\TACS.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Settings.job">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="MyProject.ReminderWebJob.cmd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>
</Project>
```

**Comment by mkArtakMSFT** [comment]
Hi @Liero.
What are you trying to do? WebJobs supposed to be running in background and have no UI.
Why are you trying to do that?

**Comment by Liero** [comment]
@mkArtakMSFT:
I have application, that is supposed to be running on the background without UI, just like the Mvc.RenderViewToString sample does. My WebJob is supposed to send email reminders, but in order to use Razor as "mail templates" I had to reference the web sdk

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this one? Thanks!

**Comment by pranavkm** [comment]
> but then I get runtime exception when I try to invoke the razor view.

What's the exception you're seeing? You likely need to set `<PreserveCompilationContext>true</PreserveCompilationContext>` in your app - my guess is Razor compilation cannot find reference assemblies to compile against.

**Comment by Liero** [comment]
@pranavkm, you are right about the exception and setting PreserveCompilationContext does help indeed.

This solves my situation (feel free to close the issue), but:

it's still unclear to me, why project using Microsoft.NET.Sdk cannot compile the views without PreserveCompilationContext and Microsoft.NET.Sdk.Web can. What are side effects of PreserveCompilationContext.

**Comment by pranavkm** [comment]
1. PreserveCompilationContext results in the app including reference assemblies in the output along with metadata in the deps file. The side effect is a larger deploy\publish size. These are only ever required if you're doing runtime compilation. Most desktop applications don't do this, which is why you it's only enabled by default by the Web Sdk. 

> are you sure that the project SDK should determine how the app will be published?

The Web.Sdk is opinionated about the kind of target you're deploying it and shows a dialog best suited for their targets. Not sure if there's a way to change this behavior - you could try asking at https://github.com/aspnet/websdk.
