### ISSUE TITLE
VirtualFileResult throws FileNotFoundException

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#7681]
I did an experiment (https://github.com/aspnet/AuthSamples/pull/37) where I re-implemented some of StaticFiles using MVC in order to add auth support. VirtualFileResult was not well suited for this.

I started with `File(virtualPath, ...)` but it throws a FileNotFoundException if the virtualPath does not exist. A 404 would be more appropriate. So I took my IFileProvider, looked up the IFileInfo, and checked if it existed. But now there's no File(...) overload that accepts my IFileInfo. There's also no overload that accepts an IFileProvider.

I ended up with code like this:
```
        [Authorize]
        [Route("Authorized/{*file}")]
        public IActionResult Get(string file)
        {
            // VirtualFileResult throws if the file doesn't exist.
            var fileInfo = Files.GetFileInfo(file);
            if (!fileInfo.Exists)
            {
                // https://github.com/aspnet/Home/issues/2537
                return ServeDirectory(file);
            }

            if (_contentTypes.TryGetContentType(file, out var contentType))
            {
                var fileResult = File(file, contentType);
                fileResult.FileProvider = Files;
                return fileResult;
            }

            return NotFound();
        }
```

The code I would rather write would be something like this:
```
        [Authorize]
        [Route("Authorized/{*file}")]
        public IActionResult Get(string file)
        {
            var fileInfo = Files.GetFileInfo(file);
            if (fileInfo.IsDirectory)
            {
                return ServeDirectory(file);
            }

            if (_contentTypes.TryGetContentType(file, out var contentType))
            {
                return File(fileInfo, contentType);
            }

            return NotFound();
        }
```
@javiercn @jbagga

**Comment by mkArtakMSFT** [comment]
This seems to be a whole new feature request, which will be "add support for MVC to act like a file server". So far we haven't received any ask like that, so closing this for now.
