### ISSUE TITLE
BindPropertyAttribute.SupportsGet should work on HEAD requests when fuzzy matching is enabled

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7688]
As part of https://github.com/aspnet/Mvc/pull/7510, we made page selectors support HEAD requests when a GET request appears. However, `BindPropertyAttribute.SupportsGet` continues to be limited to HEAD requests.

**Comment by pranavkm** [comment]
cc @DamianEdwards \ @rynowak \ @mkArtakMSFT 

I think we might want to take this in RTM. There isn't a very obvious "right design" for this and I want to run this by @rynowak once he's in rather than push a PR through today.

**Comment by rynowak** [comment]
That seems reasonable, I'm a little worried on the impact for controllers, but generally this feature would be used with `[Route]` to handle `HEAD` requests.

We haven't really tried to solve the problem of what to do about `HEAD` for APIs

**Comment by pranavkm** [comment]
When I spoke to @DamianEdwards he wanted the fuzzy matching to work only in Razor Pages (since the feature is currently limited to it).

**Comment by mkArtakMSFT** [comment]
Parking for 2.1.0 for now as it's not yet clear what we're going to do here. Given that, this may even be pushed out to `2.2` release.
Unless @DamianEdwards you believe this is super critical to be included as part of `2.1`.

**Comment by pranavkm** [comment]
@kichalla do we still need to do this?

**Comment by mkArtakMSFT** [comment]
@kichalla, I'm waiting for a PR for this to go out, so I can request an approval.

**Comment by kichalla** [comment]
Actually there's no action item here as it's already fixed. However, I had earlier sent a PR which adds some tests. https://github.com/aspnet/Mvc/pull/7717

**Comment by mkArtakMSFT** [comment]
Excellent. As these are only test changes, go ahead with merging the PR.

**Comment by kichalla** [comment]
https://github.com/aspnet/Mvc/commit/cb97a93fff5f70b9c919de0855158ae16dbfc400
