### ISSUE TITLE
MvcServiceCollectionExtensions.AddMvc needs to return an Mvc specific collection

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#769]
This would enable the pattern that SignalR-Server uses - https://github.com/aspnet/SignalR-Server/blob/dev/samples/SignalRSample.Web/Startup.cs#L13-L14

```C#
.AddMvc()
.SetupOptions(mvcOptions => {
   mvcOptions.AntiForgery...
});
```

**Comment by ianhong** [comment]
@yishaigalatzer  and @danroth27 
Not sure if we still want to do this? I think this is already fixed. 

In MVC, we can do 
                    services.AddMvc();
                    services.ConfigureMvcOptions(options =>
                    {
                        options.Filters.Add(typeof(PassThroughAttribute), order: 17);
                    });

In SignalR we can do
                services.AddSignalR(options =>
                {
                    options.Hubs.EnableDetailedErrors = true;

                    // options.Hubs.RequireAuthentication();
                });

I don't see many differences here except AddSignalR requiring Action<SignalROptions> configureOptions. But, in MVC this is a part of the ConfigureMvcOptions method..

**Comment by pranavkm** [comment]
Might want to ping @davidfowl \ @HaoK  to see what design for `ConfigureOptions` we landed on. Would be helpful for us to be consistent across EF, SignalR and Mvc.

**Comment by ianhong** [comment]
@rynowak 
I'm closing this issue, but please add more details about the decision that you made..

**Comment by rynowak** [comment]
Per response to the original issue, we recently added the following:
```
services.AddMvc().ConfigureMvc(o => { ... });
```
