### ISSUE TITLE
Controller Generator Failure

### ISSUE THREAD

**Issue by pthorsley** [aspnet/Mvc#7691]
Getting this error when trying to create a new controller of any type (mvc or api).

"There was an error running the selected code generator:
'There was an error running the template C:\Users\<username>\.nuget\packages\microsoft.visualstudio.web.codegenerators.mvc\2.1.0-preview2-final\Templates\ControllerGenerator\ApiEmptyController.cshtml: Template Processing Failed:(4,47): error CS0234: The type or namespace name 'Hosting' does not exist in the namespace 'Microsoft.AspNetCore.Razor' ( are you missing an assembly reference?) 
(10,41): error CS0234: The Type or namespace 'Hosting' does not exist in the namespace 'Microsoft.AspNetCore.Razor' ( are you missing an assembly reference?)' 

I have two projects in this solution:
1. Project One is a .Net Core React project based on Core not .Net Framework.
2. Project Two is a .Net Core Class Library project based on Core that controls the data access. 

HEY HAVE FOUND WORK AROUND BY CHANGING LIBRARIES!!!!!

So I went to project two and went back a version these two libraries:
Microsoft.VisualStudio.Web.CodeGeneration.Design   Now: 2.0.2   Was: 2.1.0-preview2-final
Microsoft.EntityFrameworkCore.Tools  Now: 2.0.2  Was: 2.1.0-preview2-final

Fixed for now,

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @pthorsley.
@pranavkm, any thoughts regarding this?

**Comment by mkArtakMSFT** [comment]
Can you please share a minimalistic repro project to help us investigate the issue you're facing, @pthorsley. Thanks!

**Comment by pranavkm** [comment]
This is an issue in Scaffolding. Could you move it to https://github.com/aspnet/Scaffolding?

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Scaffolding#771
