### ISSUE TITLE
Write an analyzer that flags async void actions

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#7694]
e.g. https://github.com/aspnet/Home/issues/3082

`async void` actions break the request processing flow. These methods should be using `async Task`.

Proposal: Write an analyzer to flag these as warnings / errors in controllers.

**Comment by pranavkm** [comment]
We have an analyzer for this in our experimental analyzers package `Microsoft.AspNetCore.Mvc.Analyzers.Experimental`. The plan is to eventually make it part of the shipping analyzers package.

**Comment by pranavkm** [comment]
There's a sort of meta issue for analyzers here - https://github.com/aspnet/specs/issues/110. Perhaps this could be tracked there?

**Comment by mkArtakMSFT** [comment]
Perfect, closing this one then. Please add any comments there (though the link is already created) as necessary.
