### ISSUE TITLE
Naming mismatch IUrlHelper extensions vs Request

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/Mvc#7697]
We have this extension 

    string RouteUrl(this IUrlHelper helper, string routeName, object values, string protocol, string host, string fragment)

If we do the following in a razor view, this is not correct:

    @Url.RouteUrl("routename", new {parameter=1}, Context.Request.Protocol, Context.Request.Host.Value, "myhash")

It actually expects

    @Url.RouteUrl("routename", new {parameter=1}, Context.Request.Scheme, Context.Request.Host.Value, "myhash")

A bit confusing? Easy to fix, but not as intuitive as it could be.

**Comment by rynowak** [comment]
It's not easy to fix. Renaming a parameter is a source-breaking-change

**Comment by JeanCollas** [comment]
@rynowak I totally agree with this, but keeping the naming would also mean building on something that may not be right. 

Which one is the best choice?

To advocate the change, I believe that in the concerned functions, all parameters are mandatory, and therefore named parameters should have been used in very few cases.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JeanCollas.
While we agree that the naming isn't ideal, we won't be able to make this change because this will be breaking one.
