### ISSUE TITLE
InvalidOperationException on new project based on VS docker template.

### ISSUE THREAD

**Issue by mrukas** [aspnet/Mvc#7699]
### Title
InvalidOperationException on new project based on VS docker template.

### Functional impact
It prevents a newly created project from running.

### Minimal repro steps
Setup a project based on the following Visual Studio Project Settings:

- .NET Core
- ASP.NET Core 2.0
- Web Application (Model-View-Controller)
- Authentcation: Individual User Accounts - Store user accounts in-app
- Enable Docker Support (OS: Windows)

Start debugging with the docker configuration.

### Expected result
If you start debugging with docker, the app should start up. A project created with a VS template should work without further configuration.

### Actual result
The following exception gets thrown during `BuildWebHost(args).Run();`

`System.InvalidOperationException: 'HTTPS endpoints can only be configured using KestrelServerOptions.Listen().'`

### Additional Info
A project with the same configuration but without docker support works out of the box.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mrukas.
Can you also share the VS version you use?

**Comment by mkArtakMSFT** [comment]
@danroth27, can you please redirect this as necessary? Thanks!

**Comment by danroth27** [comment]
@mrukas I've confirmed that this should be working in VS2017 15.7 Preview 4, so please make sure that you have the latest VS2017 preview release installed (https://www.visualstudio.com/vs/preview/).

**Comment by danroth27** [comment]
I'm going to go ahead and close this, but if you're still running into issues after installing the latest Visual Studio 2017 preview please let us know!
