### ISSUE TITLE
[implementation] Revisit FormContext storage in HttpContext

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#77]
Each request gets a default `FormContext` instance for use when rendering inputs and providing their validation attributes outside `@Html.BeginForm()` ... `@Html.EndForm()`.  Likely this default instance should either be shared beyond the lifetime of the containing `ViewContext` (e.g. stored in the `HttpContext`) or lazy-initialized.
Further we probably will not need to store explicitly-created `FormContext` instances in the `HttpContext` once we get `ViewContext` flowing and updating correctly.
Look at this issue after we've got `@Html.Partial()`, child actions, and the templated helpers (`@Html.Display[For[Model]]()` and `@Html.Editor[For[Model]]()`) in place.

**Comment by rynowak** [comment]
This appears to be addressed by 94db3c39
