### ISSUE TITLE
.net core mvc is not properly applying displaytemplates for classes derived from abstract class

### ISSUE THREAD

**Issue by vflame** [aspnet/Mvc#7705]
It appears that asp.net core isn't evaluating the runtime type of derived classes and applying the appropriate DisplayTemplate. This issue is occurring with MVC web apps targeting .Net core 2.1.0-preview2-final. It works as expected with MVC web apps targeting .NET framework 4.7.

On a side note, is it possible to pass in a base class to the Model and have the existing tag/html helpers recursively resolve (i.e., downcast) the runtime derived type without using DisplayTemplates? I know this can be done with custom htmlhelpers but feel that this would be a welcomed feature, especially for data annotations/attributes such as [Display] and [DisplayFormat] that are specific to the derived classes. 

To reproduce:

MyModel.cs
```c#
  public abstract class MyModel
    {
        //Should not see DisplayTemplate applied to base class, unless a DisplayTemplate is explicitly defined for the base class.
        [DisplayFormat(DataFormatString = "should not see this")]
        public abstract decimal str { get; set; }
    }

    public class HasDisplayTemplate : MyModel
    {
        [DisplayFormat(DataFormatString = "HasDisplayTemplate{0}")]
        public override decimal str { get; set; } = .01m;
    }

    public class NoDisplayTemplate : MyModel
    {
        [DisplayFormat(DataFormatString = "NoDisplayTemplate{0}")]
        public override decimal str { get; set; } = .02m;
    }
```

HasDisplayTemplate.cshtml (~/View/Shared/DisplayTemplates/HasDisplayTemplate.cshtml)
```c#
@model WebApplication3.Models.HasDisplayTemplate
@Html.DisplayFor(x => x.str) | <text>displaytemplate rendered</text>
```

Index.cshtml called by controller
```c#
@model IEnumerable<MyModel>

<div class="row">
    <ul>
        @foreach (var transaction in Model)
        {
            <li>
                @Html.DisplayFor(x => transaction)
            </li>
        }
    </ul>
</div>
```

HomeController
```c#
public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var data = new List<MyModel>()
            {
            };

            data.Add(new HasDisplayTemplate());
            data.Add(new HasDisplayTemplate());
            data.Add(new NoDisplayTemplate());
            data.Add(new NoDisplayTemplate());
            data.Add(new HasDisplayTemplate());

            return View(data);

        }
}
```

Expected html markup (produced by web app targeting .net 4.7):
```html
<ul>
    <li>
        HasDisplayTemplate0.01 | <text>displaytemplate rendered</text>
    </li>
    <li>
        HasDisplayTemplate0.01 | <text>displaytemplate rendered</text>
    </li>
    <li>
        <div class="display-label">str</div>
        <div class="display-field">NoDisplayTemplate0.02</div>

    </li>
    <li>
        <div class="display-label">str</div>
        <div class="display-field">NoDisplayTemplate0.02</div>

    </li>
    <li>
        HasDisplayTemplate0.01 | <text>displaytemplate rendered</text>
    </li>

</ul>
```

html markup produced by webapp targeting .net core 2.1 preview 2
```html
<ul>
    <li>
        <div class="display-label">str</div>
        <div class="display-field">HasDisplayTemplate0.01</div>

    </li>
    <li>
        <div class="display-label">str</div>
        <div class="display-field">HasDisplayTemplate0.01</div>

    </li>
    <li>
        <div class="display-label">str</div>
        <div class="display-field">NoDisplayTemplate0.02</div>

    </li>
    <li>
        <div class="display-label">str</div>
        <div class="display-field">NoDisplayTemplate0.02</div>

    </li>
</ul>
```

Specs:
Visual studio 2017 15.7
Windows 10
.NET Core 2.1.0 preview 2 final

**Comment by vflame** [comment]
Further testing shows that recursive/nested properties are properly resolved with DisplayTemplates in .NET 4.7 but not in .NET core 2.1 preview 2.

**Comment by mkArtakMSFT** [comment]
Thanks for providing detailed information, @vflame.
@dougbu can you please look into this? Thanks!

**Comment by dougbu** [comment]
This sounds like the intended behaviour. ASP.NET had a few inconsistencies in this area. In particular, `DisplayFor` and similar methods use the declared type of the model i.e. `MyModel` in your scenario.

To render the runtime type, use `Display` instead e.g.
``` html
@model IReadOnlyList<MyModel>

<div class="row">
    <ul>
        @for (var i = 0; i < Model.Count; i++)
        {
            <li>
                @Html.Display("[@i]")
            </li>
        }
    </ul>
</div>
```

----
My apologies for any errors above. I don't have time to test this this week.

**Comment by dougbu** [comment]
Yes, as I said earlier
> ASP.NET had a few inconsistencies in this area.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
