### ISSUE TITLE
Unable to pass a null param through view component helper tag

### ISSUE THREAD

**Issue by Tarig0** [aspnet/Mvc#7708]
I have a view component that needs to be able to understand the difference between a null and empty string. when I use the following the view component is still retrieving an empty string.

```html
<vc:product-line-list exclude="@(Enumerable.Empty<string>())" selected="@ViewData["selected"]" has-key-nomen="@null"></vc:product-line-list>
```

I have tried making the default of hasKeyNomen to be null but to no avail.

**Comment by Tarig0** [comment]
I would like to be able to either not pass in the argument or have the explicit null be honored in the executeAsync call

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Tarig0.
@NTaylorMullen, any suggestions here?

**Comment by NTaylorMullen** [comment]
@Tarig0 sadly this isn't yet possible. However, we do have an issue over in the Razor repo tracking this: https://github.com/aspnet/Razor/issues/1266

To workaround this limitation for now you can use the `@await Component.InvokeAsync(...)` syntax

**Comment by Tarig0** [comment]
That tracks the omission but how about the null binding to string.empty?

**Comment by Tarig0** [comment]
OK I switched to using string.empty, "*" and "real" as my three branches.

So because the function is expecting a string, and all the tag helper sets all attributes as required and the attribute type is string it will not allow a specified null to go through

I'm don't understand why that is a case, say I have a variable that could be null I now need to do an if statement in the view to omit the attribute when it is null instead of just passing the variable.

Either way this is a razor issue

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Tarig0. We're closing this issue in favor to the issue @NTaylorMullen  has pointed out to.
