### ISSUE TITLE
Unable to test web site with Microsoft.AspNetCore.App dependency

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7710]
Found while verifying aspnet/Release#302.

## Repro steps
1. create empty folder e.g. `md netCore21RC1Api`
2. `cd netCore21RC1Api`
3. `dotnet new webapi --name netCore21RC1Api --output .\netCore21RC1Api\`
4. `dotnet new xunit --name XUnitTest --output .\XUnitTest\`
5. `dotnet new sln`
6. `dotnet sln add .\netCore21RC1Api\netCore21RC1Api.csproj`
7. `dotnet sln add .\XUnitTest\XUnitTest.csproj`
8. ` dotnet add .\XUnitTest\XUnitTest.csproj reference .\netCore21RC1Api\netCore21RC1Api.csproj`
9. `dotnet add .\XUnitTest\XUnitTest.csproj package Microsoft.AspNetCore.Mvc.Testing -v 2.1.0-rc1-30661`
10. create an `xunit.runner.json` file in the .\XUnitTest directory containing at least
  ``` json
  {
    "shadowCopy": false
  }
  ```
  - This setting [should](https://xunit.github.io/docs/configuring-with-json.html#items) be irrelevant for .NET Core 2.1 tests. Including it just in case&hellip;
11. `dotnet build`
12. Confirm app and test project work fine separately (with project reference but that's it):
    a. `cd netCore21RC1Api`
    b. `dotnet run --no-build`
    c. browse to https://localhost:5001/api/values
    d. kill the app
    e. `cd ..\XUnitTest\`
    f. `dotnet test --no-build`

13. Update .\UnitTest1.cs to contain:
  ``` c#
  using System;
  using System.Net;
  using System.Net.Http;
  using System.Threading.Tasks;
  using Microsoft.AspNetCore.Mvc.Testing;
  using netCore21RC1Api;
  using Xunit;

  namespace XUnitTest
  {
    public class UnitTest1 : IClassFixture<WebApplicationFactory<Startup>>
    {
        private readonly WebApplicationFactory<Startup> _factory;

        public UnitTest1(WebApplicationFactory<Startup> factory)
        {
            _factory = factory;
        }

        [Fact]
        public void Test1()
        {
        }

        [Fact]
        public async Task Values_Succeeds()
        {
            // Arrange
            var client = _factory.CreateDefaultClient();

            // Act
            var response = await client.GetAsync("/api/values");

            // Assert
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        }
    }
  }
  ```
14. `dotnet build`
15. `dotnet test --no-build`

### Expected
A successful run of both tests.

### Actual
The `XUnitTest.UnitTest1.Values_Succeeds` test fails with no error given. `XUnitTest.UnitTest1.Test1` still works fine. (Both tests fail if the server is started in the constructor i.e. the `CreateDefaultClient()` was not placed in a single test.)

### Execution in Visual Studio
Visual Studio's Test Explorer window provides more information about the failure:
![image](https://user-images.githubusercontent.com/6431421/39275499-52bacbfa-489a-11e8-9e04-33e6209521cf.png)

## Details
`dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008662
 Commit:    6ae1926fb0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008662\

Host (useful for support):
  Version: 2.1.0-rc1-26423-06
  Commit:  b50a96ee38

.NET Core SDKs installed:
  2.1.200-preview-007474 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007517 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007576 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007587 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008523 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008662 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30552 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-rc1-30661 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30552 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-rc1-30661 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26403-06 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1-26423-06 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by dougbu** [comment]
This problem does not occur when using just packages e.g. start the above repro steps with
1. md net461RC1Api
2. cd net461RC1Api
3. dotnet new webapi --name net461RC1Api --output .\net461RC1Api\ --target-framework-override net461
4. dotnet new xunit --name XUnitTest --output .\XUnitTest\ --target-framework-override net461

The packages-only workaround succeeds with .NET Core 2.1 as well i.e.
1. edit the above .NET 4.6.1 projects to target that TFM:
``` xml
<TargetFramework>netcoreapp2.1</TargetFramework>
```
2. `rm -Recurse .\net461RC1Api\bin\, .\net461RC1Api\obj\, .\XUnitTest\bin\, .\XUnitTest\obj\`
3. `dotnet build`
4. `cd  .\XUnitTest\`
5. `dotnet test --no-build`
6. observe 2 successful tests

**Comment by dougbu** [comment]
I've updated the original description to contain the correct `UnitTest1.cs` file for API tests.

**Comment by dougbu** [comment]
And, I forgot to mention including the following in XUnitTest.csproj:
``` xml
<ItemGroup>
  <None Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>
```

**Comment by dougbu** [comment]
One workaround is to explicitly reference the shared runtime "package" from the test project:
``` xml
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rc1-30661" />
```
But, this isn't discoverable at all.

**Comment by dougbu** [comment]
Put another way, the reference to the Microsoft.AspNetCore package is getting lost in the transitive references. Need that package to pick up the `WebHost.CreateDefaultBuilder(string[])` method.

**Comment by dougbu** [comment]
Assigning to @JunTaoLuo because he's taking the first crack at determining why `dotnet restore` isn't working the way we expect with `<ProjectReference ... />`s and shared runtimes.

**Comment by JunTaoLuo** [comment]
My suspicion is that this is related to our recent changes in making Microsoft.AspNetCore.App implicitly defined. I'm going to test it some more.

**Comment by d0apga** [comment]
Hi, [aspnet/home](https://github.com/aspnet/Home#aspnet-core) says aspnet@preview 's version: 2.1.0-rc1-30682, but where to download from?

**Comment by JunTaoLuo** [comment]
@d0apga take a look at the download page: https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1.

**Comment by JunTaoLuo** [comment]
The current thinking is that we will not change any changes to the web sdk to allow the reference to the metapackages Microsoft.AspNetCore.App and Microsoft.AspNetCore.All to be flowed transitively. 

This is because even if we were to make the transitive references flow, the build msbuild targets will not. This means that while the app will be run on the latest aspnetcore shared frameworks via roll-forward, the test project will not. This discrepancy in the binaries loaded is dangerous and we would like to avoid that by requiring the same logic to be applied to the test project. To do this, the test project will need:
1. An implicit reference to the aspnetcore metapackages like `<PackageReference Include="Microsoft.AspNetCore.App" />`.
2. Change the SDK from `Microsoft.NET.Sdk` to `Microsoft.NET.Sdk.Web`

This is something that we'll need to do via documentation and I'm not sure how to make this requirement discoverable.

**Comment by dougbu** [comment]
> This is because even if we were to make the transitive references flow, the build msbuild targets will not.

What makes references to the meta-packages special in this context? Other dependencies of a referenced project flow without causing MSBuild issues.

If I'm understanding, we changed the meta-packages to be treated as `PrivateAssets='All'` when brought in implicitly. Is it not possible to revert that change?

----
Am I correct _any_ project (e.g. a unit test project exercising a service implementation) referring to a web project can hit his issue? If yes, a fix in Microsoft.AspNetCore.Mvc.Testing is insufficient.

**Comment by JunTaoLuo** [comment]
There are some email discussions on what other solutions we might have for this issue.

**Comment by muratg** [comment]
Folks, this is in the 2.1.0 milestone.  Any product changes we epect to do in 2.1?  If so, we'll need to send this to shiproom ASAP.

**Comment by JunTaoLuo** [comment]
The final decision is not to make any changes in 2.1.0. The expectation is that the user will need to make the aforementioned changes where the test project will need:
1. An implicit reference to the aspnetcore metapackages like <PackageReference Include="Microsoft.AspNetCore.App" />.
2. Change the SDK from Microsoft.NET.Sdk to Microsoft.NET.Sdk.Web

We will explore creating templates for better guidance/discoverability. 

cc @dougbu @javiercn is there any documentation we need to update for this?

FYI closing since we will not be making any code changes to address this issue.

**Comment by guardrex** [comment]
@JunTaoLuo Little confused about why I'm *not broken* given the discussion here and on #7617. I set up the test project for the integration testing sample like this ...

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="Always" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RazorPagesProject\RazorPagesProject.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.1.0-rc1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>

</Project>
```
... note the lack of use of Web SDK and the lack of a package reference for the App package.

It didn't seem to have a problem (except for a bunch of package warnings). Seems to run ok ...

```
Total tests: 14. Passed: 14. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 14.8748 Seconds
```

Is there a delta between what I'm doing with the integration testing sample and what's being addressed here? Do you still want me to change this to Web SDK and use the App package in the test project?

If you'd like to see the whole sample, I put it over here :point_right: https://github.com/guardrex/IntegrationTestingSample

**Comment by guardrex** [comment]
@JunTaoLuo Nevermind ... I read your remarks and surmise the answer is 'yes' to my rubber :duck: question. I'll cover it in the topic updates.

**Comment by guardrex** [comment]
Side note tho: It's choking on having ...

```xml
<Content Include="xunit.runner.json" CopyToOutputDirectory="Always" 
         CopyToPublishDirectory="PreserveNewest" />
```

> error : Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'xunit.runner.json' 

Seems ok tho removing the `Content Include` ...

```
Total tests: 14. Passed: 14. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 12.8168 Seconds
```
... but still getting hundreds of package ref errors. We can look at that later on the PR.
```
    212 Warning(s)
    0 Error(s)
```

**Comment by JunTaoLuo** [comment]
Adding the Microsoft.AspNetCore.App reference and changing the sdk isn't always required to make the tests pass. @guardrex in your case, the tests work because you are referencing the .App package explicitly and specifying the version. Normally, the templates do not have a version number and our implicit version logic would have marked the package with PrivateAssets=All. Since that did not happen, all of the transitive references were maintained and your tests would be able to load any assembly that the app requires.

However, the msbuild properties will not be flowed transitively and you can end up in a scenario where your app runs on a different framework than the tests so the recommendation is still to add a reference to Microsoft.AspNetCore.App and changing to Sdk.Web. What are the package ref error you are seeing?

**Comment by guardrex** [comment]
@JunTaoLuo There was no error ... that was my question ... I was wondering *why I wasn't getting an error*. I wasn't repro-ing what's in this issue.

> you are referencing the .App package explicitly and specifying the version

I wasn't referencing the package (and I wasn't using Web SDK). The test app was working with ...

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="Always" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RazorPagesProject\RazorPagesProject.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>

</Project>
```

It works just as well with the updates you recommended ...

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RazorPagesProject\RazorPagesProject.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>

</Project>
```
... but with just a couple of other changes not mentioned:
* `<OutputType>Exe</OutputType>` removed
* `Content Include="xunit.runner.json"` removed (but the JSON file still in the project root)

I've already updated the new integration testing topic with the changes you recommended. Unless you want me to revert those, I think we're good. :+1:

**Comment by dougbu** [comment]
> `<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rc1-final" />`

@guardrex this is _not_ the recommended reference anymore. That was an early workaround I found while initially debugging the issue.

Instead, please use and recommend leaving the `Version` choice to the Web SDK:
``` xml
<PackageReference Include="Microsoft.AspNetCore.App" />
```

**Comment by guardrex** [comment]
@dougbu Hum ... ok ... first time I'm hearing about this ... been heads-down busy on docs issues and still receiving news on upcoming bits. Thanks for letting me know.
