### ISSUE TITLE
Greater precedence for ActionResult<T>

### ISSUE THREAD

**Issue by austindrenski** [aspnet/Mvc#7713]
I'm working with `2.1.0-preview2-final` and trying to get `ApiDescription` to report that a method returning `Task<ActionResult<T>>` translates into an endpoint with a response type of `T` on success.

Based on the current implementation, it looks like `ActionResult<T>` is only being set for `Status200OK` when there are ___no__ other filters_ at play:

https://github.com/aspnet/Mvc/blob/1b9372f5b0c490209d49e6051f5f1b615094f399/src/Microsoft.AspNetCore.Mvc.ApiExplorer/DefaultApiDescriptionProvider.cs#L418-L440

Based on the announcement, I expected `ActionResult<T>` to be used for `Status200OK` _before_ the attributes were considered, allowing explicit attributes to overrule the inference from `ActionResult<T>`:

> We want to embrace the OpenAPI specification (previously called “Swagger”) and make Web APIs built with ASP.NET Core more descriptive. Today you need a lot of “attribute soup” to get a reasonable OpenAPI spec from ASP.NET Core. We plan to introduce __an opinionated layer__ that infers the possible responses based on what you’re likely to have done with your actions (__attributes still win when you want to be explicit__).
https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/#mvc 

### Questions

1. Is the current behavior intentional/frozen for 2.1?
2. If it isn't frozen, is the team be open to a pull request in this area?

### Potential change
```c#
// Set the OK response to the runtime type by default.
if (type != null)
{
    objectTypes[StatusCodes.Status200OK] = type;
}

// Register the attributes, potentially overriding the default OK response.
var contentTypes = new MediaTypeCollection();
if (responseMetadataAttributes != null)
{
    foreach (var metadataAttribute in responseMetadataAttributes)
    {
        metadataAttribute.SetContentTypes(contentTypes);

        if (metadataAttribute.Type != null)
        {
            objectTypes[metadataAttribute.StatusCode] = metadataAttribute.Type;
        }
    }
}
```

**Comment by rynowak** [comment]
@austindrenski - can you give an example of what you're doing (code sample) and what you expect the behavior should be vs what it is? I'm not sure I totally understand what you're asking.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and/or we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
