### ISSUE TITLE
MvcRouteHandler and IActionContextAccessor Registration

### ISSUE THREAD

**Issue by dazinator** [aspnet/Mvc#7718]
I am having a problem when calling `UseMvc` (asp.net core 2.0). It says that it cannot resolve `MvcRouteHandler` because there is no `IActionContextAccessor` registered.

I have looked here: https://github.com/aspnet/Mvc/blob/599d1a502ef358678202345ced2d11ddca0754f3/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L260

I can see that indeed `MvcRouteHandler` is registered as a singleton, but I can't see `IActionContextAccessor` being registered anywhere. `MvcRouteHandler` seems to require this as a dependency so I am wondering how this is resolved.

Please can you clarify how / where `IActionContextAccessor` get's registered?

**Comment by dazinator** [comment]
Perhaps this is because I am using `structuremap` which selects the greediest constructor by default.
I can see `MvcRouterHandler` has a couple of constructors, and its the greediest one that requires the `IActionContextAccessor`..

**Comment by khellang** [comment]
The StructureMap adapter has a special constructor selector that should consider registered services when picking a ctor. The default one just picks the greediest. See https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/blob/master/src/StructureMap.Microsoft.DependencyInjection/AspNetConstructorSelector.cs

**Comment by mkArtakMSFT** [comment]
Hi @dazinator.
You can write an `IActionContextAccessor` which no-ops, and register that as a singleton, which will allow you to work around the problem you're facing.
