### ISSUE TITLE
Can't accept multiple IFormFile

### ISSUE THREAD

**Issue by bpaczkowski** [aspnet/Mvc#7719]
Accepting a single `IFormFile` works fine, but when using `List<IFormFile>` or any other IFormFile collection type, the resulting collection is empty.

I'm using ASP.NET Core version 2.1.0-preview2-final on .NET Framework 4.6.2 on Windows.

**Comment by bpaczkowski** [comment]
`IFormCollection.Files` does work and I can retrieve the files I sent without issues, so I guess that's a workaround, thanks! I also tried with `IFormFileCollection` as an argument by the way, but that was empty as well.

**Comment by kichalla** [comment]
@bpaczkowski In the cases where you see empty, can you check how ModelState looks like? Any errors in them?

**Comment by bpaczkowski** [comment]
No errors in the `ModelState`. In the logs however:

```
2018-04-30 14:44:27.0579 DEBUG Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinder: Attempting to bind model of type 'System.Collections.Generic.List`1[Microsoft.AspNetCore.Http.IFormFile]' using the name '' in request data ...
2018-04-30 14:44:27.0579 DEBUG Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinder: No files found in the request to bind the model to.
2018-04-30 14:44:27.0579 DEBUG Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinder: Done attempting to bind model of type 'System.Collections.Generic.List`1[Microsoft.AspNetCore.Http.IFormFile]' using the name ''.
```

**Comment by kichalla** [comment]
@bpaczkowski Your `List<IFormFile>` should have worked as I see we have tests verifying that scenario. Could you share the following details or you could just give a repro app if it makes it easier for you.

- Version of MVC you are using
- The raw request data being sent to the server
- Action signature

**Comment by bpaczkowski** [comment]
* Version of MVC: `2.1.0-preview2-final`
* Raw request:
```
POST / HTTP/1.1
Host: localhost
User-Agent: curl/7.58.0
Accept: */*
Content-Length: 193
Content-Type: multipart/form-data; boundary=------------------------5513761d97e5b660

--------------------------5513761d97e5b660
Content-Disposition: form-data; name="file"; filename="file.txt"
Content-Type: text/plain

fooBar.
--------------------------5513761d97e5b660--
```

* Action signature, though I'm not sure if that's what you meant: `public async Task<MyClass> UploadFile(List<IFormFile> files)`

**Comment by kichalla** [comment]
Try changing `name="file"` to `name="files"` to match with the name of the actual parameter name. 

However I am puzzled when you say this just works when you change your action to be `UploadFile(IFormFileCollection files)` and using `name="file"`, is this true or was it a oversight at your end?

**Comment by bpaczkowski** [comment]
`IFormCollection` works with any name, even empty one.

I changed name to `files` and `IFormFileCollection` and `List<IFormFile>` both started working, but to be honest, this is not something I would expect, it should ignore the name in my opinion. At least every other framework I used ignored it.

**Comment by bpaczkowski** [comment]
Notice I mention both `IFormFileCollection` and `IFormCollection`, 2 different interfaces. The former doesn't work with any name, the latter does. It would be nice if there was some way to keep the `IFormCollection` behavior, one use case I have in mind is when you want to make sure one and only one file is sent, something you can't validate if you could just use a different form-data name to make the file "invisible".

**Comment by khellang** [comment]
`IFormCollection` has a different binder (`FormCollectionModelBinder`). This probably doesn't care about the parameter name. But it seems that `FormFileModelBinder` *does* care about the parameter name.

**Comment by kichalla** [comment]
I read the following line too fast
> IFormCollection works with any name, even empty one.

@bpaczkowski The behavior that you are seeing is by design. `IFormCollection` is just the whole bag of data that is posted in a request so it does not depend on the name.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by kichalla** [comment]
This would create an inconsistent experience IMO. For example, if I there is a `List<string> names` parameter, a user can expect it to work here too.

**Comment by pranavkm** [comment]
Perhaps limit this to `IFormFileCollection`? The name for `IFormCollection` parameter \ properties isn't considered today, perhaps there's already precedence?

**Comment by ranouf** [comment]
The Binding issue seems to be fixed in .Net Core 2.2 nightly builds. 
source: https://github.com/aspnet/Mvc/issues/8527#issuecomment-425978956
