### ISSUE TITLE
Provide an option to log request body when deserialization fails

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#7722]
Related to issue: https://github.com/aspnet/Home/issues/3105

Writing an exception filter to log the request body feels too much work for a scenario(bad data in request body) which feels common:

- Should we provide an option for logging request body when deserialization fails? If request body is buffered(default), we log it otherwise we don't.
-  Should we log for non-formatters scenario i.e regular ModelBinding too to keep the experience consistent? I believe we always buffer the request body in case of this.

Not sure if there would be security concerns about logging request body data.

**Comment by mkArtakMSFT** [comment]
This doesn't seem to be something we'd do, as it'll require buffering, which is not worth only for logging. Also, this seems to be a test-only scenario request.
