### ISSUE TITLE
Please add implicit conversions to ObjectResult + other implementations of Actionresult prior to shipping AspNetCore 2.1

### ISSUE THREAD

**Issue by taori** [aspnet/Mvc#7724]
![grafik](https://user-images.githubusercontent.com/5545184/39485318-b27334dc-4d78-11e8-81f9-66607f7cb986.png)

As you can see in the picture i am unable to do ternary syntax on my condition because there is no implicit conversion between ObjectResult and BadRequestResult (according to the diagnostic).

Is my desired syntax that odd? It would be cool if the if + else was not necessary. Not sure whether this is a syntax limitation of roslyn or aspnetcore.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us regarding this, @taori. However, this is not an MVC issue, rather a language issue. So we're closing this as external.

**Comment by taori** [comment]
@mkArtakMSFT As i was typing an issue for dotnet/roslyn i realized that they probably cannot fix it either? If there were a Microsoft.AspNetCore.Mvc.Core.IActionResult<T> interface (instead of just https://github.com/aspnet/Mvc/blob/1aeaf69f87cbf91f4f56183eb1254f69a50b406a/src/Microsoft.AspNetCore.Mvc.Core/ActionResultOfT.cs as a sealed class) roslyn would support this use case if ObjectResult implemented that interface. 

If ActionResults would implement this imaginary IActionResult<T> that ternary expression should work.

![grafik](https://user-images.githubusercontent.com/5545184/39550395-64654228-4e61-11e8-9a0f-abf6a2a0d366.png)
