### ISSUE TITLE
AcceptedResult should be a StatusCodeResult

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [aspnet/Mvc#7730]
Most of the status action results follow the rule that *Result is a StatusCodeResult and *ObjectResult is an ObjectResult. The AcceptedResult makes people confused and might cause trouble if they have their custom OutputFormatter. I suggest that create a AcceptedObjectResult to replace the original AcceptedResult, then make the AcceptedResult inherits StatusCodeResult.

**Comment by mkArtakMSFT** [comment]
Actually, it seems that the type in question `AcceptedResult` has been release, so the proposal is a breaking change, which is something we try to avoid as much as possible. That said, we won't be changing this as there are customers using it the way it is already.

**Comment by rynowak** [comment]
We would not make a breaking change in this area just to improve the naming. 

@ClassicDarkChocolate - for context, what's there is the combination of what was present in old WebAPI and old MVC with as few breaking changes from those systems as possible.
