### ISSUE TITLE
Action locked in a single-threaded system

### ISSUE THREAD

**Issue by yhnbgfd** [aspnet/Mvc#7738]
#### Is this a Bug or Feature request?:
Bug 

#### Steps to reproduce or link to a repro project:
This is my repo to reproduce the problem : https://github.com/yhnbgfd/aspnetcore2.1-bug-test

#### Description of the problem:
In a ```single-core single-threaded``` operating system, use HttpClient in an Action and loop multiple times to call another local Action. For example, the api/Values/TestGet interface in the sample code calls the API/Values/{id} interface. , After frequent calls to api/Values/TestGet, it will cause api/Values/TestGet interface to be blocked. At this time, you can only restart the application to recover.  
  
After testing, this problem does not occur in non-monolithic, non-single-threaded environments. The .net core 2.0 version does not exhibit this problem.  
  
More Detailed Test Cases View ValuesController.  
    
In my actual project, there is the await keyword(await httpClient.PostAsync), so I still can't find the cause of the problem. 

```
        [HttpGet("Test")]
        public IActionResult Test()
        {
            HttpClient httpClient = new HttpClient();
            for (int i = 0; i < 100; i++)
            {
                httpClient.GetStringAsync($"http://localhost:5000/api/Values/{i}");
            }
            return Content($"{DateTime.Now} Finish");
        }
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.All : 2.1.0-preview2-final

**Comment by khellang** [comment]
You should take a look at [Diagnosing issues in ASP.NET Core applications](https://vimeo.com/254635669). They talk about (and demo) quite a few issues like these.

**Comment by khellang** [comment]
The "bug" in this case, is that you're never waiting for the `GetStringAsync` call to finish. You should either `await` it in the loop, or collect all the tasks and `await Task.WhenAll` at the end of the method.

**Comment by yhnbgfd** [comment]
@khellang thank you for your reply.  
These two pieces of code are the codes in my project. They also have the above problems. The test code was written by me on a temporary basis, so there are many areas that are not well thought out, but only under the single-threaded operating system, this phenomenon will only appear under the 2.1 version. Is this the problem of the 2.1 version?


```
        [HttpGet("GetTicketTest")]
        public async Task<IActionResult> GetTicketTestAsync([FromServices]IHttpClientFactory httpClientFactory, int num = 1)
        {
            var http = httpClientFactory.CreateClient("localhost");
            try
            {
                using (var con = DatabaseService.ReadOnlyMySql)
                {
                    for (int j = 0; j < num; j++)
                    {
                        var json = new JObject(
                            new JProperty("Priority", 0)).ToString(Formatting.None);
                        var content = new StringContent(json, Encoding.UTF8, "application/json");
                        await http.PostAsync("/api/QueueMachine/GetTicket", content);
                    }
                    return Ok();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
                return BadRequest();
            }
            finally
            {
                http.Dispose();
            }
        }
```

```
        [HttpGet("ThreadGetTicketTest")]
        public async Task<IActionResult> ThreadGetTicketTestAsync([FromServices]IHttpClientFactory httpClientFactory, int num = 1, int thread = 3)
        {
            try
            {
                using (IDbConnection con = DatabaseService.ReadOnlyMySql)
                {
                    Task[] tasks = new Task[thread];
                    for (int i = 0; i < thread; i++)
                    {
                        tasks[i] = Task.Run(async () =>
                        {
                            var http = httpClientFactory.CreateClient("localhost");
                            try
                            {
                                for (int j = 0; j < num; j++)
                                {
                                    var json = new JObject(
                                        new JProperty("BranchId", "1"),
                                        new JProperty("CustomerName", "bb")).ToString(Formatting.None);
                                    var content = new StringContent(json, Encoding.UTF8, "application/json");
                                    await http.PostAsync("/api/QueueMachine/GetTicket", content);
                                }
                            }
                            finally
                            {
                                http.Dispose();
                            }
                        });
                    }
                    Task.WaitAll(tasks);
                    return Ok();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
                return BadRequest();
            }
        }
```

**Comment by yhnbgfd** [comment]
I updated my test code,and still have that problem：
```
        [HttpGet("TestGet")]
        public IActionResult TestGet()
        {
            List<Task> tasks = new List<Task>();
            using (HttpClient httpClient = new HttpClient())
            {
                for (int i = 0; i < 100; i++)
                {
                    var task = httpClient.GetStringAsync($"http://localhost:5000/api/Values/{i}");
                    tasks.Add(task);
                }
                Task.WaitAll(tasks.ToArray());
            }
            return Content($"{DateTime.Now.ToString("HH:mm:ss.fff")} Finish");
        }
```
Then I created a console application, but he is normal：
```
        static void Main(string[] args)
        {
            List<Task> tasks = new List<Task>();
            using (HttpClient httpClient = new HttpClient())
            {
                for (int i = 0; i < 100; i++)
                {
                    var task = httpClient.GetStringAsync($"http://localhost:5000/api/Values/{i}");
                    tasks.Add(task);
                }
                Task.WaitAll(tasks.ToArray());
            }

            Console.WriteLine("Hello World!");
            Console.ReadLine();
        }
```

**Comment by khellang** [comment]
I think it would be better to use `await Task.WhenAll` instead. Also, 100 concurrent requests sounds a bit... excessive?

**Comment by yhnbgfd** [comment]
@khellang I just tried what you said ```await Task.WhenAll```,but still have that problem.
```
        [HttpGet("TestGet")]
        public async Task<IActionResult> TestGetAsync()
        {
            List<Task> tasks = new List<Task>();
            using (HttpClient httpClient = new HttpClient())
            {
                for (int i = 0; i < 100; i++)
                {
                    var task = httpClient.GetStringAsync($"http://localhost:5000/api/Values/{i}");
                    tasks.Add(task);
                }
                await Task.WhenAll(tasks);
            }
            return Content($"{DateTime.Now.ToString("HH:mm:ss.fff")} Finish");
        }
```
Because I wrote an interface for generating simulation data and tested the performance of the interface by the way, so it called a lot of local interfaces. I had been on a multi-core computer so I had no problems. Until recently I moved the project to a single platform. The nuclear single-threaded computer only discovered this problem.

**Comment by mkArtakMSFT** [comment]
Hi @yhnbgfd.

In your example you're actually not reusing the `HttpClient` instances. So every time your `TestGetAsync` action is called, a new `HttpClient` instance is created. Try to euse the `HttpClient` instance by defining such a member on the controller level. Then, just refer to it from your API.

/cc: @rynowak

**Comment by yhnbgfd** [comment]
@mkArtakMSFT hi，I tried to reuse httpclient, the problem is still
but when I upgraded to 2.1.0-rc1-final, the problem was fixed
