### ISSUE TITLE
MemoryStream CopyTo method does not work over REST if the file size is more (approx. >100KB)

### ISSUE THREAD

**Issue by Kalyan1989** [aspnet/Mvc#7740]
#### Is this a Bug or Feature request?:
This is bug observed while writing REST service for downloading file to temporary location over server machine. The same code works fine on client side.

#### Steps to reproduce or link to a repro project:
Client code: Client.cs

```csharp
 var FirmwareFilePath = "D:\\baccfg.dll";
 using (var memoryStream = new System.IO.MemoryStream())
            {
                using (var fileStream = new System.IO.FileStream(
                    FirmwareFilePath,
                    System.IO.FileMode.Open,
                    System.IO.FileAccess.Read))
                {
                    fileStream.CopyTo(memoryStream);
                }
                memoryStream.Position = 0;
          fwUpdateResult = networkService.PostFirmwareUpdate( RequestParam.Default, memoryStream);
 }
```

Server code: Server.cs

```csharp
PostFirmwareUpdate(IRequestParam requestParam, Stream firmwareFileStream))
        {
            var tempFilePath = System.IO.Path.GetTempFileName();                                                                 
            using (var memoryStream = new System.IO.MemoryStream())
            {
                firmwareFileStream.CopyTo(memoryStream); 
//Control is not coming out of this CopyTo process and timeout is happening
                  memoryStream.Position = 0;
                using (var fileStream = new System.IO.FileStream(
                    tempFilePath,
                    System.IO.FileMode.Create,
                    System.IO.FileAccess.Write))
                {
                    memoryStream.WriteTo(fileStream);
                }
            }              
}
```         
#### Description of the problem:
For .xml file size of 2KB, the code works fine and temp file is getting created at server.
But if I use file with extension like .dll, .7z with file size more than 100-200 KB, the code stucks in CopyTo function call.

**Comment by khellang** [comment]
How does this relate to ASP.NET MVC? I can't see any MVC-specific code in here. 

Maybe you could psuh a repro project to GitHub and link it here?

**Comment by mkArtakMSFT** [comment]
Hi @Kalyan1989. As @khellang had pointed out, this has nothing to do with MVC. We're closing this issue. Consider opening a new one in https://github.com/dotnet/corefx repo, as that seems to be a better place for this.
