### ISSUE TITLE
partial view bug of MVC website in .NET Core 2.1 RC1

### ISSUE THREAD

**Issue by hez2010** [aspnet/Mvc#7747]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce or link to a repro project:
I use .NET Core 2.1.300-rc1 to create a new MVC web app with individual authentication, then I use identity scaffolder (visual studio -> right click my project -> add -> new scaffolded item -> identity) and specify layout file with "~/Views/Shared/_Layout.cshtml" to generate identity related code in Areas/Identity automatically.

Related project: https://github.com/hez2010/hjudgeNEW -> hjudgeWeb
you can change ~/Views/Shared/_Layout.cshtml line 48 to \<partial name="_LoginPartial" /> (remove ".cshtml") to reproduce the problem.

#### Description of the problem:
When I try to build, the compiler warns me that I need to use \<partial /> instead of @Html.Partial. Of course I can replace @Html.Partial to \<partial /> manually, but why not generate code with \<partial /> automatically at the beginning?

And then I run the website, when I navigated to Login/Register page in browser, I found that the _LoginPartial View could not be loaded correctly that it still remained \<a asp-area="Identity" asp-page="/Account/Login">\</a> but not \<a href="/Identity/Account/Login">\</a> in HTML source so that I could not click Login or Register again. Also, I changed the navbar style in _LoginPartial.cshtml but when I navigated to Login/Register page, it restored to original styles.

Normally (in home page): 
![1](https://user-images.githubusercontent.com/14960345/39738273-c877d280-52bc-11e8-9910-5713f9ecd59c.png)

But in Login/Register page:
![2](https://user-images.githubusercontent.com/14960345/39738272-c82af82a-52bc-11e8-9a10-937d111a9013.png)

But after I changed the code in _Layout.cshtml:
\<partial name="_LoginPartial" />   ----->   \<partial name="_LoginPartial.cshtml" />, it works again. 

![3](https://user-images.githubusercontent.com/14960345/39738348-29041e10-52bd-11e8-961c-51675cf87edd.png)

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
v2.1.0-rc1-final

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hez2010.
@javiercn, can you please look into this? Do we have anything to do here, or is this pure scaffolding issue?

**Comment by javiercn** [comment]
Thanks for bringing this up to our attention @hez2010.

@mkArtakMSFT I do believe both to be scaffolding issues. I think they are both fixed for RTM. @seancpeters can confirm this.

For the issue regarding Html.Partial is a matter of changing it to use the partial tag helper.
For the issue regarding the link not working, you are likely missing the line that enables the tag helpers on the page (typically on a view imports file).

See https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ItemTemplates/content/ViewImports/_ViewImports.cshtml#L2 for an example.

I'm closing this bug as there's nothing to do on the MVC side and the issues have been addressed in scaffolding for RTM.
