### ISSUE TITLE
Enum Display attribute localization not translated by DataAnnotationLocalizerProvider

### ISSUE THREAD

**Issue by tverboon** [aspnet/Mvc#7748]
#### Is this a Bug or Feature request?:
Bug or By Design

#### Steps to reproduce or link to a repro project:
```razor
<select class="form-control" asp-for="Period" asp-items="Html.GetEnumSelectList<ReportPeriod>()">
</select>
```

```csharp
namespace MyApp.Mvc.Models
{
    public enum ReportPeriod
    {
        [Display(Name = "Custom")]
        Custom = 0,
        [Display(Name = "Today")]
        Today
    }
```
#### Description of the problem:
I have registered a DataAnnotationLocalizerProvider in the Startup and was actually expecting the translations to be defined in the corresponding resource file, but the Display Names weren't translated, although it should work according: #5197

Doing some digging in the code, I found that Enums are localized with their own localizer: https://github.com/aspnet/Mvc/blob/26454fb1da36191ee43b59b956f6e9f2d945a3a7/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/DataAnnotationsMetadataProvider.cs#L185

The other DisplayAttributes use: https://github.com/aspnet/Mvc/blob/26454fb1da36191ee43b59b956f6e9f2d945a3a7/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/DataAnnotationsMetadataProvider.cs#L107

Not sure if this is by design and why. I expected to use the `DataAnnotationLocalizerProvider` I specified in Startup as it is working for the other Display attributes.

I got it working by adding a resource file with the right name and translations.

**Comment by mkArtakMSFT** [comment]
Hi @tverboon. Thanks for contacting us.
Can you share the repro project as a git repo? That would help us a lot.

**Comment by tverboon** [comment]
Hi @mkArtakMSFT,

Got a git repo: https://github.com/tverboon/enum-localization

In the final commit, everything is localized by using two resx files. Commit before that, only Name label is localized.

**Comment by mkArtakMSFT** [comment]
Thanks @tverboon. @ryanbrandenburg, can you please look into this? Thanks!

**Comment by ryanbrandenburg** [comment]
@tverboon this definitely reproduces, and as you noted it's not intended behavior. I can make a fix, but it's technically a breaking change in case someone took a dependency on Enum DataAnnotations not using `DataAnnotationLocalizerProvider`. @mkArtakMSFT I guess the determination is on you for if/when we take this, but my vote would be yes.

**Comment by ryanbrandenburg** [comment]
I talked it over with @mkArtakMSFT and our plan is to put this in behind a compatibility switch for now, with an issue filed on 3.0.0 to remove the compat switch and only support the corrected behavior.

**Comment by mkArtakMSFT** [comment]
Removed the `breaking-change` label, as we're going with a compat switch, which will eliminate the breaking change. We'll remove (hence introduce the breaking change) the compatibility switch in 3.0.
