### ISSUE TITLE
JWT types are not interpreted properly

### ISSUE THREAD

**Issue by vaindil** [aspnet/Mvc#7760]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce or link to a repro project:
[Repro project is attached here](https://github.com/aspnet/Mvc/files/1989091/JWTClaimTypeRepro.zip). You can get the token with a POST to `/token`, then you can get the claim types that are in the JWT by calling GET `/token/test` with the JWT sent via normal bearer authorization.

#### Description of the problem:
I'm setting claims of several types in the attached example. I'll use `sub` in this issue but all of the types have the same problem, you can see the others in the attached project.

The `sub` claim type is set using `JwtRegisteredClaimNames.Sub`, which is a constant set to `sub`. This is correct, of course. The JWT that's output has the property named `sub`, as it should be. This can be verified on [JWT.io](https://jwt.io). When MVC reads the token from the Authorization header, however, it interprets the type as a URL. This makes it very difficult to actually get these types from the JWT--if I create a claim with type `JwtRegisteredClaimNames.Sub`, I should be able to get that claim like this:

```
User.FindFirst(JwtRegisteredClaimNames.Sub)
```

This does not work for the comparison though, the above returns null even though that claim actually does exist.

#### Version of `Microsoft.AspNetCore.App`:
2.1.0-rc1-final
.NET Core SDK: 2.1.300-rc1-008673

**Comment by kichalla** [comment]
cc @Tratcher @HaoK

**Comment by khellang** [comment]
This isn't a bug, it's by design. The JWT handler translates the claim types from the JWT standard into .NET claim types. If you want to disable this, you should clear the inbound claim type map:

```csharp
JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();
```

**Comment by vaindil** [comment]
Sorry, I didn't know what repo to put this in. :/

That seems very strange to me, that I would need to create the token with one type but access it with another. But that's not a question for here, as you said, so I'll close this. Thank you, and sorry!

**Comment by khellang** [comment]
> Thank you, and sorry!

Hey, no need to be sorry. You're not the first to find this weird, and certainly won't be the last.

It's been discussed back and forth in thw community for years. Here's one issue; https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/415
