### ISSUE TITLE
Provide a helper method to enable HTTPS in functional tests

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#7765]
#### Is this a Bug or Feature request?:
Feature

#### Description of the problem:
The HTTPS middleware doesn't redirect by default if we can't infer the HTTPS port. We want to provide a helper method on the WebApplicationFactory so that its easy to setup for functional tests.

When not enabled, customers will think that the testing infrastructure is broken when its not.

**Comment by mkArtakMSFT** [comment]
Closing this as this is not a priority for 2.2 milestone.
