### ISSUE TITLE
Standard Error Response Provider

### ISSUE THREAD

**Issue by jonmeyerson** [aspnet/Mvc#7766]
#### Is this a Bug or Feature request?:
Feature Request / Question

#### Steps to reproduce or link to a repro project:
1. Include API Versioning and initiate a bad request with an invalid version. 
2. Violate the expected modelstate on a request with ValidateModelAttribute applied.
##### Startup.cs
```
services.AddMvcCore()
.AddVersionedApiExplorer(options =>
            {
                options.GroupNameFormat = "'v'VVV";
            }).Services.AddMvc()
            .Services.AddApiVersioning()
```
##### ValidateModelAttribute.cs
```
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
    public class ValidateModelAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (!context.ModelState.IsValid)
            {
                context.Result = new BadRequestObjectResult(context.ModelState);
            }
        }
    }
```
##### Controller.cs
 ```
  [Route("api/[controller]")]
    [ApiVersion("1.0")]
    [ValidateModel]
    [ProducesResponseType(typeof(Dictionary<string, string[]>), StatusCodes.Status400BadRequest)]
    public class TestController : ControllerBase
    {
        [HttpPost]
        public IActionResult Test([FromBody]TestModel model)
        {
            return Ok();
        }
    }

    public class TestModel
    {
        [Required]
        [EmailAddress]
        public string TestEmail { get; set; }
    }
```
Sample 400 Responses:
```
{
  "error": {
    "code": "InvalidApiVersion",
    "message": "The HTTP resource that matches the request URI 'http://localhost:38305/api/Test?api-version=f' does not support the API version 'f'.",
    "innerError": null
  }
}
```
```
{
  "TestEmail": [
    "The TestEmail field is not a valid e-mail address."
  ]
}
```
#### Description of the problem:
I am trying to standardize response types per error code as recommended in [api guidelines](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#710-response-formats), but have run into an issue when using  BadRequestObjectResult and [api versionsing](https://github.com/Microsoft/aspnet-api-versioning) because one returns a Dictionary<string, string[]> and the other returns an object with [Code, Message and InnerError](https://github.com/Microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/DefaultErrorResponseProvider.cs#L35)  they return different return types for the same status code. 
I believe a [Response provider like the one used in api-versioning](https://github.com/Microsoft/aspnet-api-versioning/wiki/Error-Response-Provider) should be configurable in the MVC framework and used globally to have a standard response format for status codes.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
```
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="2.2.0" />
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jonmeyerson. One of our team members will look into it and get back to you.

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please investigate this one? Thanks!

**Comment by pranavkm** [comment]
You could build something like this for controllers annotated with `ApiControllerAttribute` using https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ApiBehaviorOptions.cs#L25. The plan is to standardize around `ProblemDetails` - https://github.com/aspnet/Mvc/issues/6786 for API error responses in the future.

**Comment by rynowak** [comment]
API Versioning isn't a project we maintain/support.

**Comment by jonmeyerson** [comment]
I Updated the project to 2.1-rc-1 and now have these attributes on the controller. 
```
 [ApiController]
 [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
```
As for the api versioning i removed it since it did not seem to allow consistency for status code / return types

**Comment by mkArtakMSFT** [comment]
Hi @jonmeyerson.
We're closing this issue as we'll cover it as part of the other issue @pranavkm has linked to.
