### ISSUE TITLE
Name cshtml views in ASP.NET Core

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/Mvc#7771]
I don't know if this is the proper repository or https://github.com/aspnet/Razor but as I am using ASP.NET Core, I am posting here.

I am wondering if it would be complicated to have a mechanism to "name" the views, like for routes, instead of relying on the file path of these views? 

It would be helpful when building modules, instead of calling `/Views/Module1/DisplayView.cshtml` to call from any view `Module1DisplayView`

An proposal of implementation would be to add a @name keyword at the beginning of the cshtml view:

    public static class Module1Views 
    {
        public const string Module1DisplayView = "Module1DisplayView";
    }

at the top of cshtml:

    @name Module1Views.Module1DisplayView
    @model Module1DisplayViewModel

then:

    @Html.PartialNamed(Module1Views.Module1DisplayView, module1Model)

**Comment by mkArtakMSFT** [comment]
Hi @JeanCollas.
While this is a good idea in general, this is not something we plan to invest in the near future.

**Comment by JeanCollas** [comment]
Fine. 
Any specific reason? The roadmap is already full? This is not in line with the strategy? Not in line with design practice? Too complicated to set-up? ...?

I guess I will have to do my own home-made implementation :(
