### ISSUE TITLE
Services.CreateScope() in IWebhost not working anymore

### ISSUE THREAD

**Issue by whizkidwwe1217** [aspnet/Mvc#7772]
#### Is this a Bug or Feature request?:
Bug

#### Description of the problem:
Before I upgraded to 2.1 preview2, creating a database in startup (Program.cs) works perfectly by instantiating a new service by calling host.Services.CreateScope()

```csharp
public static void Main(string[] args)
{
      var host = BuildWebHost(args);
 
      using (var scope = host.Services.CreateScope())
      {
             var services = scope.ServiceProvider;
             var ds = services.GetService<CatalogDataSource>();
             /// do some stuff here like migrations etc.
      }

      host.Run()
}

 public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder()
   ///...... truncated for brevity
```
In 2.1 preview 2, the return type has been changed from IWebHost to IWebHostBuilder. I tried

```csharp
public static void Main(string[] args)
{
      var host = CreateWebHostBuilder(args).Build();
 
      using (var scope = host.Services.CreateScope())
      {
             var services = scope.ServiceProvider;
             var ds = services.GetService<CatalogDataSource>();
             /// do some stuff here like migrations etc.
      }

      host.Run()
}

 public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
   ///...... truncated for brevity
```
The latter don't work. How can I migrate the database during startup like in the previous version?

**Comment by whizkidwwe1217** [comment]
@davidfowl There's no error. The issue is that it doesn't get executed. I tried to put a breakpoint in the Main method but the debugger doesn't seem to hit it.

**Comment by whizkidwwe1217** [comment]
@davidfowl My goal is to execute the extension method MigrateCatalog that takes an IWebHost parameter, so I can get the my migration services from the DI and then create the database. In the version 2.1 preview 2, it doesn't work anymore. Seems like it doesn't get executed, instead it goes straight to the http middleware without resulting to 'can't open database error'.

![image](https://user-images.githubusercontent.com/1977391/39959558-e36149e6-5645-11e8-8276-153909acb3f1.png)

![image](https://user-images.githubusercontent.com/1977391/39959581-331472d8-5646-11e8-9db7-505806f59775.png)

**Comment by davidfowl** [comment]
So you’re saying if you put a break point inside MigrateCatalog the function doesn’t run?

**Comment by whizkidwwe1217** [comment]
@davidfowl It doesn't even breaks into the Main method.

**Comment by whizkidwwe1217** [comment]
@davidfowl Asp.net doesn't even respect the Main function. I even deleted the Program.cs and still runs and goes directly into the Startup.cs. Why is it happening?

**Comment by whizkidwwe1217** [comment]
@davidfowl I think I have figured it out already. I tried digging into the VS code configurations and found out that I have to change the program path since I've changed the target framework.
![image](https://user-images.githubusercontent.com/1977391/39963126-a5798f80-5695-11e8-9c56-34d6230bb775.png)

I will now close this issue. Thanks!

**Comment by ivanromakh** [comment]
Cool examples
