### ISSUE TITLE
ViewBag can not pass anonymous object

### ISSUE THREAD

**Issue by hez2010** [aspnet/Mvc#7773]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce or link to a repro project:
In Controller:
```c#
public IActionResult Test() {
    ViewBag.Test = new { A = 1, B = 2};
    return View();
}
```
In View:
```html
<p>A = @ViewBag.Test.A</p>
<p>B = @ViewBag.Test.B</p>
```
#### Description of the problem:
the result should be:
A = 1
B = 2
but actually it threw an exception: RuntimeBinderException: 'object' does not contain a definition for 'A'

the same, if I use ViewData to pass the anonymous object, and in View I cast the object to dynamic type, it will also throw the exception when I try to access its members.

**Comment by pranavkm** [comment]
This is a limitation of the language. Anonymous types are internal to the assembly they are defined in. Views are compiled in an assembly different than your application's. Using a model to pass structured data would be our recommendation. You might also have success using value tuples

**Comment by hez2010** [comment]
@pranavkm but I found that I can use Reflection in View to get the name, type and value of the anonymous object successfully. Why not implement it with reflection by default?

in View:
```cs
@{
    foreach (var i in ViewBag.Test.GetType().GetProperties())
    {
        <p>
            @i.Name: @i.PropertyType = @i.GetValue(ViewBag.Test)
        </p>
    }
}
```

it will shows:
```
A: System.Int32 = 1
B: System.Int32 = 2
```
