### ISSUE TITLE
Configure Razor Pages in Area without the Pages folder

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Mvc#7775]
Is it possible to configure Razor pages to find the `Index.cshtml` directly under the folder for the area **name**?

This is how my project structure look like without the `Pages` folder.

- Areas
  - App
      - _Layout.cshtml
      - _ViewImports.cshtml
      - _ViewStart.cshtml
      - Index.cshtml
      - Index.cshtml.cs
- Controllers
- Models
- Views
- wwwroot
- Program.cs
- Startup.cs

**Comment by pranavkm** [comment]
It is not for 2.1.0. Views in Areas go inside the Views directory and we wanted to mirror that by default. We started with the option to allow changing it, but didn't have a good solution in place to not have it affect Razor Pages from 3rd party libraries (e.g. https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.UI). Besides preference, was there a specific reason you were looking to have it appear directly under the Area directory?

**Comment by marcuslindblom** [comment]
Ok I see.

The main reason is to only to get rid of the folder for cosmetic reasons.
