### ISSUE TITLE
question: will you please explain lables using in this repository 

### ISSUE THREAD

**Issue by kishan3034** [aspnet/Mvc#7776]
1-ready means anyone can work on it. is it correct?

**Comment by kishan3034** [comment]
I went through code and engineering guide lines. But didn't find anything about labels. How we are using and what it means.

**Comment by kishan3034** [comment]
thanks @mkArtakMSFT. if i’m  interested to work on non up-for-grabs label items, is it fine. i want to contribute to this repo. want to start with bugs.

**Comment by mkArtakMSFT** [comment]
Feel free to ping us on the specific issue you're interested in, @kishan3034. In general that's always welcome! It's just that `up-for-grabs` issues are known to be self contained so those will be easier to start with.

**Comment by kishan3034** [comment]
Thanks @mkArtakMSFT. I'll ping.
