### ISSUE TITLE
Multi-tenant Razor Pages not possible?

### ISSUE THREAD

**Issue by seriouz** [aspnet/Mvc#7779]
#### Is this a Bug or Feature request?:
Feature

#### Description of the problem:
How to use RazorPages in an multi tenant szenario? I have two root folders:
The base root `/Pages` folder and a root folder `/Tenants/*` where every tenant has its own folder with its RazorPages which can override or extend the base.
I don't know how this is possible currently, beside setting the `RootDirectoy` to `/` so that the discovery process scans all folders of the project.

```csharp
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
                .AddRazorPagesOptions(options => {
                    options.RootDirectory = "/";
                });
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`: 2.1.0-rc1-final

**Comment by mkArtakMSFT** [comment]
Thanks for your feature request, @seriouz.
As this is not a priority for the upcoming milestone, we're going to move this to the Backlog to consider in the future.
