### ISSUE TITLE
XmlSerializerOutputFormatter throws InvalidCastException on async method

### ISSUE THREAD

**Issue by aguacongas** [aspnet/Mvc#7782]
#### Is this a Bug or Feature request?:
Bug, regression

#### Steps to reproduce or link to a repro project:
- Create an Asp.Net Core api project
- Update package to use 2.1.0-rc1-final
``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-rc1-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
  </ItemGroup>

</Project>
```
- Add XmlSerializerOutputFormatter in MVC option
``` csharp
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(options =>
            {
                options.OutputFormatters.Add(new XmlSerializerOutputFormatter());
            });
        }
```
- Update a ValuesController method to use async 
``` csharp
 public async Task<IEnumerable<string>> Get()
        {
            return await Task.FromResult(new string[] { "value1", "value2" });
        }
```
- run the project
- send a request using Accept: application/xml
``` 
GET /api/values HTTP/1.1
Host: localhost:61519
Accept: application/xml
```

#### Description of the problem:
An `InvalidCastException` is thrown  

> InvalidCastException: Unable to cast object of type &#x27;System.String[]&#x27; to type &#x27;System.Threading.Tasks.Task`1[System.Collections.Generic.IEnumerable`1[System.String]]&#x27;.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.All Version="2.1.0-rc1-final"

**Comment by mkArtakMSFT** [comment]
@aguacongas, thanks for contacting us.
@dougbu, can you please investigate this? Thanks!

**Comment by aguacongas** [comment]
@dougbu If I apply the workaround, will that work with the fix ?

**Comment by dougbu** [comment]
Yes, if you apply the workaround, you'll still be fine after picking up @pranavkm's fix.
