### ISSUE TITLE
Dependency Injection into IViewLocationExpander implementing class

### ISSUE THREAD

**Issue by guylando** [aspnet/Mvc#7786]
Is it possible to use constructor Dependency Injection in a class implementing IViewLocationExpander?
It is initialized in Startup.cs ConfigureServices

                .AddRazorOptions(options =>
                {
                    options.ViewLocationExpanders.Add(new CustomViewLocationExpander());
                })
So it seems a problem to inject into the constructor.
Is there some solution?

**Comment by pranavkm** [comment]
You could use `ConfigureOptions` do this: `services.AddOptions<RazorViewEngineOptions>().ConfigureOptions<ICustomService>(options => ...)`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by guylando** [comment]
@pranavkm @mkArtakMSFT 
I don't understand the answer.
I want to inject something into CustomViewLocationExpander class constructor. I don't understand how the answer allows me to do that.

**Comment by pranavkm** [comment]
```C#
// CustomViewLocationExpander
class CustomViewLocationExpander
{
   public CustomViewLocationExpander(ISomeService service1, IDifferent service2) { }
}


// Startup
services.AddTransient<ISomeService, SomeServiceImpl>();
services.AddTransient<IDifferent, Different>();
services.AddTransient<CustomViewLocationExpander>();
ervices.AddOptions<RazorViewEngineOptions>().ConfigureOptions<CustomViewLocationExpander>((options, expander) => options.ViewLocationExpanders.Add(expander));
```

**Comment by guylando** [comment]
how does the code
`
services.AddOptions<RazorViewEngineOptions>().ConfigureOptions
`
integrate with the code
`
services.AddMvc().AddRazorOptions(options =>
                {
                    options.FileProviders.Clear();
                    options.FileProviders.Add(new PhysicalFileProvider(...));
                }).AddJsonOptions().AddDataAnnotationsLocalization().AddViewLocalization()
`
does it come after it, before it? instead of it?

thanks

**Comment by guylando** [comment]
I have put it AFTER .addRazorOptions and it seems to work, thanks
