### ISSUE TITLE
Question: Custom Page Handler Routing, sample doesn't work

### ISSUE THREAD

**Issue by xmlapi** [aspnet/Mvc#7787]
I want to map a razor page to the following routes: /edit-vehicle OR /new-vehicle (must be same page but with different handlers)

Below is the code for the Vehicle Razor Page:
```
 public class VehicleModel : PageModel
    {
        public string Name { get; set; }

        public void OnNewVehicle(int id)
        {
            this.Name = "New Vehicle";
        }

        public void OnGet(int id)
        {
            this.Name = "Edit Vehicle";
        }
    }
```
Below is the startup.cs code for the page:
```
     services.AddMvc().AddRazorPagesOptions(options =>
            {
                options.Conventions.AddPageRoute("/Vehicle", "{handler:regex(edit-vehicle|new-vehicle)}/{id}");
            });
```

I tried the AddPageApplicationModelConvention sample too but it doesn't seem to work. It always goes into the "OnGet" method

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
Hi @xmlapi.

Have you tried to take out the dashes `-` from the handle names? That may work.

**Comment by xmlapi** [comment]
We want to keep friendly URLs so we don't want to remove the dashes. Basically, we're trying to replicate the functionality of MVC Controllers but keeping the "Controller Logic" and "View Logic" together.

So Vehicle Razor Page is actually a "Controller" with multiple "actions" that can be performed: Get Vehicle [Get], New Vehicle [Get], New ProtoType Vehicle [get], Delete Vehicle [POST] and we want to stick with the friendly URL convention of /get-vehicle, /new-vehicle, /new-prototype-vehicle, /delete-vehicle instead of /vehicle/get-vehicle, /vehicle/new-vehicle etc

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please suggest how this can be achieved?

**Comment by pranavkm** [comment]
In the default case, handler names are constructed from the method names and they are exact matched to the values from route. In you case, you are attempting to match `new-vehicle` to the method `NewVehicle` (you have a second issue there, the naming convention requires you to name it `OnGetNewVehicle`). You might be able to use a default value for your handler name so the handler selection just works. Something along the lines of `options.Conventions.AddPageRoute("/Vehicle", "new-vehicle/{id}/{handler=NewVehicle}");`

That said, Razor Pages the kind of routing you're attempting to do here - which is a route per handler method - is not how Razor Pages is fundamentally designed to work. Something more in line with the design philosophy is to have a page her unique route you'd like while using partials and layouts to share common page content.

**Comment by pranavkm** [comment]
Feel free to reopen the issue if you have additional questions.
