### ISSUE TITLE
Make types which own disposable resources disposable

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#7788]
This came up in the following PR, where some types which own disposable resources aren't actually disposable: https://github.com/aspnet/Mvc/pull/7780
After a discussion regarding that it seems there was a design decision to not do that for singleton types as there is no much value.
However, there are cases where the types are used in testing for example, where it ends up created and not disposed for prolonged period of time.
Things which fall into the same bucket are:
- `MvcViewOptions`
- `RazorViewEngineOptions`
- many more

This issue is filed to revisit that design decision.

**Comment by rynowak** [comment]
> After a discussion regarding that it seems there was a design decision to not do that for singleton types as there is no much value.

I've never heard of this.

In general we don't have much that's disposable.  This is worth looking at, but I expect the impact of this to be really limited.

**Comment by mkArtakMSFT** [comment]
Doesn't look like there's much we will act on as from disposable types ownership perspective even the above mentioned types should not be disposed.
