### ISSUE TITLE
using await async inside ExpandViewLocations IViewLocationExpander

### ISSUE THREAD

**Issue by guylando** [aspnet/Mvc#7792]
The logic inside our ExpandViewLocations method of our custom IViewLocationExpander requires to make a call to an async method. Using .Wait() is known to cause deadlocks so the preferred way it to use await however ExpandViewLocations does not return a task so cant have the async keyword.

So how to call async method inside ExpandViewLocations?

Thanks

**Comment by pranavkm** [comment]
Unfortunately none of the lookup code path in view engines is async today (See https://github.com/aspnet/Mvc/issues/7416). You'd have to block or write your expanders in a way that they do not need to be async.

A bit of a tangent, StackOverflow is better suited for these kinds of questions. You get a larger audience of people who might have come up with independent solutions for things like this.

**Comment by guylando** [comment]
On the other hand you benefit from the awareness of functionary\feature requirements from your users (me) :)
Thanks for the answer.

**Comment by guylando** [comment]
And by the way I have workarounds for stuff like this but was looking for the proper Microsoft solution when asking here.
