### ISSUE TITLE
ASP.NET Core 2.1 'Feature' Project Structure Not Working

### ISSUE THREAD

**Issue by zeus82** [aspnet/Mvc#7796]
I'm trying to port a ASP.NET Core 2.0 project to 2.1.  It uses the feature layout:

    Website.csproj
        |--Features
            |--Home
                |--HomeController.cs
                |--Index.cshtml
                |--About.cshtml
                |--Contact.cshtml
                |--Privacy.cshtml

This is how I configure Mvc:

    services
        .AddMvc()
        .AddRazorOptions(options =>
        {
            // {0} - Action Name
            // {1} - Controller Name
            // {2} - Area Name
            // {3} - Feature Name
            // Replace normal view location entirely
            options.ViewLocationFormats.Clear();
            options.ViewLocationFormats.Add("/Features/{3}/{1}/{0}.cshtml");
            options.ViewLocationFormats.Add("/Features/{3}/{0}.cshtml");
            options.ViewLocationFormats.Add("/Features/Shared/{0}.cshtml");
            options.ViewLocationExpanders.Add(new FeatureViewLocationExpander());
        })
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_1); // This line is new to 2.1, there is nothing like this in my 2.0 project

This is my ViewLocationExpander:

	public class FeatureViewLocationExpander : IViewLocationExpander
	{
		public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
		{
			// Error checking removed for brevity
			var controllerActionDescriptor =
			  context.ActionContext.ActionDescriptor as ControllerActionDescriptor;
			string featureName = controllerActionDescriptor.Properties["feature"] as string; //KeyNotFound Exception
			foreach (var location in viewLocations)
			{
				yield return location.Replace("{3}", featureName);
			}
		}

		public void PopulateValues(ViewLocationExpanderContext context)
		{
		}
	}

In 2.1 I get a KeyNotFoundException on  `controllerActionDescriptor.Properties["feature"]`, Anyone know how to make this work in 2.1?

**Comment by zeus82** [comment]
I actually go past this error by using the ControllerTypeInfo to figure out the name of the folder the controller is in (this only works if the namespace matches the folder structure) but now I get an error when I go to any of the identity pages saying 

```
InvalidOperationException: The layout view '/Views/Shared/_Layout.cshtml' could not be located. The following locations were searched:
 /Views/Shared/_Layout.cshtml
```
It isn't searching any of my other routes!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @zeus82.
@pranavkm, can you please look into this?

**Comment by pranavkm** [comment]
> The layout view '/Views/Shared/_Layout.cshtml' could not be located.

That looks like you're requesting the Layout view by path and not by name. `ViewLocationFormats` and `ViewLocationExpanders` are only used if you look up a view by name e.g. `Layout = "_Layout";`

**Comment by zeus82** [comment]
Your right about that... I had to edit the `_ViewStart.cshtml` in `/Areas/Identity/Pages`.  I updated it to point to /Views/Shared/_Layout.cshtml

But the `FeatureViewLocationExpander `still feels kinda hacky.    Here is what I had to do to get it working:

```
public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
		{
			// Error checking removed for brevity

			if (context.ActionContext.ActionDescriptor is ControllerActionDescriptor controllerActionDescriptor)
			{
				//var featureName = controllerActionDescriptor.Properties["feature"] as string;
				var parts = controllerActionDescriptor.ControllerTypeInfo.FullName.Split('.');
				var featureName = parts[parts.Length - 2];

				foreach (var location in viewLocations)
				{
					yield return location.Replace("{3}", featureName);
				}
			}
			else // Requests for 'Identity' pages
			{
				var locations = new List<string>
				{
					"/Features/Shared/{0}.cshtml"
				};
				locations.AddRange(viewLocations);

				foreach (var l in locations)
					yield return l;
			}
		}
```

**Comment by pranavkm** [comment]
> In 2.1 I get a KeyNotFoundException on controllerActionDescriptor.Properties["feature"]

Where is this being set from?

**Comment by zeus82** [comment]
Its being set in the 'ExpandViewLocations' method of my 'FeatureViewLocationExpander' class

**Comment by pranavkm** [comment]
Mutating `ActionDescriptor.Properties` outside of the [application model](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.0) isn't recommended. It's not thread safe, so you might run in to concurrency issues. My recommendation would be to calculate (possibly using a filter attribute) and set it as part of a convention. 

That said, I'm not sure what your question is at this point. Is there a regression compared to 2.0?

**Comment by zeus82** [comment]
I don't think there is a regression... I think I missed something went I moved my project to 2.1

Sorry.
