### ISSUE TITLE
ApiControllerAttribute's binding of complex parameter cannot be overridden.

### ISSUE THREAD

**Issue by jamiewinder** [aspnet/Mvc#7799]
I want to use the new `[ApiController]` attribute for the automatic '400 if model state is invalid behaviour', but still be explicit about the binding of parameters. For example:
```c#
[HttpGet]
public async Task<ActionResult> GetItems(
            CancellationToken cancel,
            [FromQuery]OffsetDateTime fromTime,
            [FromQuery]OffsetDateTime toTime)
```
I have a custom model binder for handling those NodaTime types, but they're receiving `null` as the model value, presumably because ASP.NET is still trying to read them from the body because of the ApiController attribute. If I remove the attribute it works again. 

I had assumed that by being explicit about the binding source on the method, it'd override the  behaviour defined by a controller attribute, but this doesn't seem to be the case?

(As an aside, can I opt-in *just* the model state handling, but not the other behaviours of `ApiController`?)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jamiewinder.
@pranavkm, does the ApiController convention take priority even in this case? Shouldn't custom model binders be respected for API controller actions?

**Comment by pranavkm** [comment]
@jamiewinder the `FromQuery` attributes should take precedence over auto inferred sources. 

a) Have you tried setting `LogLevel` to `Trace` in your app? Usually it should give you hints about what's causing the issue.
b) A repro app would also help to dig in to this.

You could configure [`ApiBehaviorOptions.SuppressInferBindingSourcesForParameters`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ApiBehaviorOptions.cs#L48) to disable the binding source inference. That said, it would be great if we could get some of your feedback on why you'd like to disable it. We want the feature set in ApiController to be both intuitive and non-intrusive and intend on building further experiences (analyzers and code fixes) that assume these defaults.

**Comment by jamiewinder** [comment]
a. I've tried calling the following on my `IWebHostBuilder`:
```c#
.ConfigureLogging(logging => logging.SetMinimumLevel(LogLevel.Trace))
```
Is that what you meant? It didn't seem to give me any extra information about model binding...?

b. I'll send one when I can.

I don't particular like the inference of where the parameters should come from, but I don't particularly mind so long as I can override it. In this case I'm using the NodaTime library rather than the BCL types, but we can see that complex types such as `DateTimeOffset` are being automatically treated as something very different to a `OffsetDateTime` when they are basically the same thing. 

The ASP.NET team have wisely made it possible to extract a `DateTimeOffset` from the query or route, but to enforce the same behaviour on other types, just because they're 'complex' seems strange. I should add I'm still relatively new to ASP.NET Core so there may be a good reason for it.

Conversely, the behaviour of 'reject with a 400 Bad Request if any part of the model binding fails' seems obvious to me. 

Again, I don't particularly mind if I can override it with an explicit `FromQuery` as I like to be an explicit as possible about this anyway.

**Comment by pranavkm** [comment]
Does this work:

```c#
.ConfigureLogging(factory =>
                {
                    factory
                        .AddConsole()
                        .AddDebug()
                       .SetMinimumLevel(LogLevel.Trace);
                })
```

**Comment by jamiewinder** [comment]
I've set up a small reproduction here:
https://github.com/jamiewinder/AspNetCoreApiControllerIssue

Browsing to `/api/withoutapi?time=2018-05-21T00:00:00Z` should echo the time from the query. 
Browsing to `/api/withapi?time=2018-05-21T00:00:00Z` will return a 400 with a model validation error

The code for the controllers is the same except for the `ApiController` attribute. I've also added a comment in `Startup.cs` around the `ApiBehaviorOptions` workaround you mentioned - it doesn't seem to have the expected effect?

**Comment by jamiewinder** [comment]
With the logging setup as you suggested, I get the following:

To `/withapi`:
```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:44357/api/withapi?time=2018-05-21T00:00:00Z  
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Route matched with {action = "Echo", controller = "WithApi"}. Executing action AspNetCoreApiControllerExample.Controllers.WithApiController.Echo (AspNetCoreApiControllerExample)
Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor:Information: Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.SerializableError'.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action AspNetCoreApiControllerExample.Controllers.WithApiController.Echo (AspNetCoreApiControllerExample) in 2.4333ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 11.4805ms 400 application/json; charset=utf-8

```
To `/withoutapi`:
```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:44357/api/withoutapi?time=2018-05-21T00:00:00Z  
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Route matched with {action = "Echo", controller = "WithoutApi"}. Executing action AspNetCoreApiControllerExample.Controllers.WithoutApiController.Echo (AspNetCoreApiControllerExample)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method AspNetCoreApiControllerExample.Controllers.WithoutApiController.Echo (AspNetCoreApiControllerExample) with arguments (2018-05-21T00:00:00Z) - Validation state: Valid
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action method AspNetCoreApiControllerExample.Controllers.WithoutApiController.Echo (AspNetCoreApiControllerExample), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.0611ms.
Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor:Information: Executing ObjectResult, writing value of type 'System.String'.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action AspNetCoreApiControllerExample.Controllers.WithoutApiController.Echo (AspNetCoreApiControllerExample) in 6.2025ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 13.0016ms 200 text/plain; charset=utf-8
```

**Comment by pranavkm** [comment]
Looks like you're running in to another side-effect of one of the issues we discovered late in with ApiControllers - https://github.com/aspnet/Mvc/issues/7609. Essentially `ModelName` gets lost in transition which results in the behavior you're seeing. I've filed an issue to port this to an upcoming patch. 

In the meanwhile, here's a workaround you could use that should continue working once we'v addressed the issue. In your binder,

```C#
// Workaround for https://github.com/aspnet/Mvc/issues/7609. bindingContext.ModelName may be an empty string.
var modelName = bindingContext.ModelName;
if (string.IsNullOrEmpty(modelName) && bindingContext.IsTopLevelObject)
{
    modelName = bindingContext.ModelMetadata.ParameterName;
}

var val = bindingContext.ValueProvider.GetValue(modelName);
```

**Comment by pranavkm** [comment]
I'm going to close this as dup since we've already tracking the underlying issue (https://github.com/aspnet/Mvc/issues/7609 and https://github.com/aspnet/Mvc/issues/7804). Feel free to reopen if you have further questions.

**Comment by jamiewinder** [comment]
I think this is still an issue in 2.1?

**Comment by pranavkm** [comment]
@jamiewinder unfortunately yes. We're addressing this in our upcoming 2.1.1 patch release.
