### ISSUE TITLE
Port fix for https://github.com/aspnet/Mvc/issues/7609 to 2.1.1

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7804]
Issue: https://github.com/aspnet/Mvc/issues/7609

**Comment by pranavkm** [comment]
cc @mkArtakMSFT

**Comment by kichalla** [comment]
PR related to this https://github.com/aspnet/Mvc/pull/7814

**Comment by mkArtakMSFT** [comment]
@kichalla, is this ready to be closed now?
