### ISSUE TITLE
Remove compat switch for Enum DataAnnotation localization

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#7810]
In #7748 we decided to fix the fact that Enum localization didn't use DataAnnotationLocalizerProvider behind a compat switch because it was a breaking change. For 3.0.0 we should remove that compat switch and only support the new behavior (usage of DataAnnotationLocalizerProvider).

**Comment by pranavkm** [comment]
Tracked via https://github.com/aspnet/Mvc/issues/7820
