### ISSUE TITLE
What is the replacement for ITraceWriter per request tracing Infra in asp.net core 2.1

### ISSUE THREAD

**Issue by chuanboz** [aspnet/Mvc#7822]
In asp.net, based on [Tracing in ASP.NET Web API 2](https://docs.microsoft.com/en-us/aspnet/web-api/overview/testing-and-debugging/tracing-in-aspnet-web-api), there is ITraceWriter interface and you could do something like below to enable tracing for infra logic.

```C#
public static void Register(HttpConfiguration config)
{
    config.Services.Replace(typeof(ITraceWriter), new SimpleTracer());
}
```

I don't see this Api exists anymore for asp.net core, and I tried to search on internet but also does not see anyone mention a replacement solution.

In the past, we leveraged this in our production service to trace the execution flow to help trouble-shooting latency issue, what is the replacement for it in asp.net core 2.1?

**Comment by mkArtakMSFT** [comment]
Hi @chuanboz.

Logging is the new telemetry solution in ASP.NET Core. You can read more about it at: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.0&tabs=aspnetcore2x

**Comment by chuanboz** [comment]
hi, @mkArtakMSFT 

thanks for the reference link, I did read that before I ask this here. 

from what I understand from that article, the ILogger and ILoggerFactory is registered as singleton, so there will be only one instance across all requests, while ITraceWriter is created per request so it could be used to trace request execution flow.

At a minimal, as ITraceWriter is publicly documented as the way to do per request tracing, there shall be some example to demonstrate how to achieve the same thing before with ILogger/ILoggerFactory.

for example, it shall demonstrate how to register ILogger/ILoggerFactory as request scope rather than singleton, and whether that shall conflict with the scope validation for other MVC built-in component that used ILogger in constructor but register as singleton.
