### ISSUE TITLE
OData expand filter

### ISSUE THREAD

**Issue by jrote1** [aspnet/Mvc#783]
The feature in the OData 4 spec where you can filter expanded properties is missing. Will this be added in? 

Example 90: all categories and for each category all related products with a discontinued date equal to null 
http://host/service/Categories?$expand=Products($filter=DiscontinuedDate eq null)

**Comment by yishaigalatzer** [comment]
@dotnetwise wrong repo.

**Comment by dotnetwise** [comment]
what's a good one?

**Comment by yishaigalatzer** [comment]
Aspnetwebstack.codeplex.com

**Comment by dotnetwise** [comment]
You mean this one?
https://aspnetwebstack.codeplex.com/workitem/2046

**Comment by yishaigalatzer** [comment]
Yes that is it. I've pinged the team looks like it is not in 5.4 but I will let them confirm.
