### ISSUE TITLE
IRazorViewEngine.FindView Precompiled Views and Non compiled views different behaviors

### ISSUE THREAD

**Issue by smartcodinghub** [aspnet/Mvc#7830]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):

1. Have a view in a non root path (/Views/Controller/View).
2. Use FindView with a Path like: 'MyTemplates/MyView' which isn't in the default paths.
3. When the view is not compile, it finds a View. When its compiled no.

#### Description of the problem:

The reason is the path that it tests. When it isn't compiled, it test 'Views//MyTemplates/MyView.cshtml' and the File methods its uses can succesfully find the view. But when its compiled, it can't find it, as it isn't a correct Path.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

2.0.6

#### Correction

They must behave the same, and probably the precompiled behavior is the good one, as Views//Controller/View is not a correct path. Its pretty annoying to have different behaviors when publishing.

**Comment by pranavkm** [comment]
Likely a dup of https://github.com/aspnet/Mvc/issues/7535. See my comments here - https://github.com/aspnet/Mvc/issues/7535#issuecomment-375738070. Does that help?

**Comment by smartcodinghub** [comment]
I have no issue here, I just changed ViewLocationFormats and its ok. The actual issue is the different behavior between compiled and no compiled views. This is because when you are working on visual studio you think it works as it can find views with a double slash (because there's no controller) but, when you publish, it stops working, which can be a hard issue to find. Especially for new Net developers.

**Comment by pranavkm** [comment]
> The actual issue is the different behavior between compiled and no compiled views. 

Yup, we addressed the differences as part of the 2.1.0 release. More pertinently, as of 2.1.0, in the default case, views are compiled as part of build. If there are other issues in this area that we haven't addressed they should show up during your regular dev builds.

**Comment by mkArtakMSFT** [comment]
Closing this as a dupe.
