### ISSUE TITLE
Accessing action arguments from IResultFilter

### ISSUE THREAD

**Issue by ayepirate** [aspnet/Mvc#7831]
Is this possible to access values of my actions from `IResultFilter`? It's possible from `IActionFilter` using `ActionExecutingContext.ActionArguments`.

Is there any way to do this from `IResultFilter`?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by ayepirate** [comment]
@pranavkm should work, thanks :)
