### ISSUE TITLE
how to load razor page from file, excute it and get the html result?

### ISSUE THREAD

**Issue by xjfnet** [aspnet/Mvc#7832]
we can load webpage from file, exute it and get the thml result with asp.net mvc 5
```cs
var page = WebPageBase.CreateInstanceFromVirtualPath(path);
using (var writer = new StringWriter())
{
    page.ExecutePageHierarchy(new WebPageContext(new HttpContextWrapper(HttpContext.Current), page, null), writer);
    var html = writer.ToString();
}
```

but how to do that with asp.net core?

**Comment by mkArtakMSFT** [comment]
Hi @xjfnet.
We have a sample detailing a similar scenario, which is available at https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString

**Comment by pranavkm** [comment]
For Mvc 5, I'd look at something like https://github.com/Antaris/RazorEngine
