### ISSUE TITLE
ViewResultExecutor changed behavior

### ISSUE THREAD

**Issue by rjamesnw** [aspnet/Mvc#7836]
#### Is this a Bug or Feature request?:
Not sure.

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
Create a new type derived from `ViewResultExecutor`.  i.e.:
```
public class TestViewResultExecutor : ViewResultExecutor
{
    public override async Task ExecuteAsync(} 
    {  // <-- put breakpoint here
            var viewPage = (view as RazorView)?.RazorPage as IViewPageRenderEvents;

            var renderContext = null; // (set to null for this test only; not null in actual source)

            viewPage?.OnBeforeRenderView(renderContext); // EVENT ON CUSTOM VIEW

            try
            {
                await base.ExecuteAsync(actionContext, view, viewResult);
            }
            catch (Exception ex) when (actionContext.HttpContext.Response.Body.CanWrite)
            {
                var result = viewPage?.OnRenderException(renderContext, ex); // EVENT ON CUSTOM VIEW
                if (result == null) throw ex;
                result.WriteTo(actionContext.HttpContext.Response.Body);
            }

            if (renderContext?.HasFilter == true)
                renderContext.ApplyOutputFilter(); // (CUSTOM POST FILTERIG)

            viewPage?.OnAfterRenderView(renderContext); // EVENT ON CUSTOM VIEW
    }
}

public interface IViewPageRenderEvents
{
    void OnViewFound(ActionContext actionContext, ViewResult viewResult, ViewEngineResult searchResult);
    IHtmlContent OnRenderException(IViewPageRenderContext renderContext, Exception ex);
    void OnBeforeRenderView(IViewPageRenderContext renderContext);
    void OnViewActivated(IRazorPage page, ViewContext context);
    void OnAfterRenderView(IViewPageRenderContext renderContext);
}

public interface IViewPageRenderContext { /*etc.*/ } 

// *** Don't forget to register the new type BEFORE you add MVC ***
 services.TryAddSingleton<ViewResultExecutor, TestViewResultExecutor>();
```

1. Create a new proejct.
2. Register the new executor (add the service BEFORE MVC).
3. Create an index.cshtml page that loads a partial view, and in that partial view load one more partial view.
4. The breakpoint (as noted in the code) used to be hit for every view (including partials).

#### Description of the problem:
I have similar code to the above that is now broken.  It used to be that the breakpoint was hit for EVERY view (INCLUDING `_layout.cshtml`).  This is no longer the case.  I don't see any notes that this behaviour was a breaking change.  I use this to detected nested page renders, which allows be to build a stack (since you guys didn't bother to port over the `System.Web.WebPages.TemplateStack` _idea_).  If this is not a bug then please suggest another way to detect nested pages.

**Comment by pranavkm** [comment]
>  It used to be that the breakpoint was hit for EVERY view (INCLUDING _layout.cshtml)

Is this a change in behavior from Mvc Core 1.0 \ 1.1? If so a repro app, would definitely help. Generally the ViewExecutor is only invoked once for each instance of `ViewResult` \ `PartialViewResult` - calls to partials, layouts, don't go through the executor.

**Comment by rjamesnw** [comment]
Sorry but you're wrong - it used to be invoked for every view, otherwise, I would not have built it that way in the first place. ;)  This was working fine last year, and I just loaded the project recently and now it doesn't work.  I did this because I confirmed by the MVC source code (I downloaded the source last year) that this indeed worked as expected; now it does not.  I don't have a working test project as this is part of a much larger project, but I can try to make one, when I have time.

**Comment by rjamesnw** [comment]
BTW: Creating a project to run the code is not the point.  The main question is how to detect nested view rendering order?  This used to be available via `System.Web.WebPages.TemplateStack`, but that is no longer available in ASP.Net Core.  I was originally able to hook into this process and implement my own event system.  If someone else has a better method, I can just use that instead.  ;)

**Comment by rjamesnw** [comment]
FYI: I found a workaround that seems to be ok, but it only executes for views that are not the layout view.  I created a custom 'CompositeViewEngine' object and an IView proxy (wrapper) to hook into the renders. This is acceptable for now.

**Comment by pranavkm** [comment]
An alternative to writing a custom view engine instance might be to register a `DiagnosticListener` and listen to [`OnBeforeViewPage`](https://github.com/aspnet/Mvc/blob/f4a86f5511064d3d7ef238ac862c3e73b412b5cd/test/Microsoft.AspNetCore.Mvc.TestDiagnosticListener/TestDiagnosticListener.cs#L234-L248). Some details on using DiagnosticSource - https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md#consuming-data-with-diagnosticlistener. It should tell you what page is about to execute including layout and view start pages.

**Comment by rjamesnw** [comment]
Interesting, I'll check it out, thanks. :)

**Comment by pranavkm** [comment]
> Would this have any major performance issues?

It shouldn't have significant perf costs, but I'd measure it.

On a tangent, we do have some plans on making the view rendering pipeline have something akin to filters so it's more straightforward to write something like this. Unfortunately that's not in scope for the 2.2 release. 

Closing this issue since it looks like you have a solution. Feel free to reopen if you have further questions.
