### ISSUE TITLE
How to override model state error message in asp.net Core 2.1?

### ISSUE THREAD

**Issue by embryologist** [aspnet/Mvc#7840]
#### Is this a Bug or Feature request?:
Question

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
shown below

#### Description of the problem:

I can't seem to be able to override the error message from model state validation for `int` or nullable ones `int?`. In the previous versions of Asp.Net Core I used to receive that the input is not valid, now I am getting this unfriendly error,

> {"streetNo":["Could not convert string to integer: abc. Path 'cityId',
> line 24, position 23."]}

so I am trying to work around it using custom validation attribute,

I created this class,

     public class IsInt : ValidationAttribute {
            public IsInt () : base () { }
    
            public override bool IsValid (object value) {
                Console.WriteLine (value);
                if (value.IsNullObject ()) {
                    return true;
                } else {
                    if (value.GetType () == typeof (int?)) {
                        return true;
    
                    } else {
                        return false;
                    }
                }
            }
            protected override ValidationResult IsValid (
                Object value,
                ValidationContext validationContext) {
    
                var message = "Only number is allowed";
                return new ValidationResult (message);
            }
        }

and I implement it this way,

    [IsInt]
    public int? StreetNo { get; set; }

The validation attribute does not seem to work as intended, if I enter a string, i.e. "abc" I still receive the mentioned model error message, it only works if the string has numbers in it, i.e. "83444"

What am I missing here?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @embryologist.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
@embryologist this particular error message comes from Json.NET, specifically https://github.com/JamesNK/Newtonsoft.Json/blob/a82acace469cd0302231a8216af73d0b60b25770/Src/Newtonsoft.Json/JsonReader.cs#L462

In previous versions, this error message was suppressed and replaced by a generic message. We addressed complaints that the message was too generic recently and now flow `JsonReaderException` and `JsonSerializationException` messages through by default. To restore the previous behaviour, add the following to your `ConfigureServices(...)` method:
``` c#
services.AddMvc()
    .AddJsonOptions(options => options.AllowInputFormatterExceptionMessages = false);
```

----
With respect to overriding the generic message: When serializing the `ModelStateDictionary`, the message will be the hard-coded string `"The input was not valid."`. But, when generating HTML, the default message (`"The value '{0}' is invalid."`) can be overridden using `DefaultModelBindingMessageProvider.SetValueIsInvalidAccessor(...)`. That method is reachable from `MvcOptions` or in an `IBindingMetadataProvider` implementation.

**Comment by embryologist** [comment]
@mkArtakMSFT @dougbu 
Thanks so much, that definitely solved the issue.
