### ISSUE TITLE
Method Attribute on Razor Pages.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#7842]
#### Is this a Bug or Feature request?:
Question / Feature request

#### Description of the problem:
```
public class MyPageModel : PageModel {
  [HttpGet]
  [Authorize] // does nothing
  public void OnGet() { }

  [HttpPost]
  [AllowAnonymous] // does nothing
  public async Task<ActionResult> OnPost()
}
```` 

Is it possible to use attributes per method on Razor Pages ?
_(i know the code provided does not work)_
If it doesn't, I suggest an error or warning as it may lead to filter sensitive data.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Bartmax.
The `Authorize` attribute is not applicable to page handlers. You can apply it on the page model level, though.
This is a quesiton which keeps coming up and we plan to provide a guidance here by introducing an analyzer, which will work developers from doing that: https://github.com/aspnet/Mvc/issues/7684

**Comment by Bartmax** [comment]
> is a quesiton which keeps coming up
that suggests this issue should be treated as Feature Request then 😄
