### ISSUE TITLE
HTTP call not redirected to HTTPS when using WebApplicationFactory

### ISSUE THREAD

**Issue by a-vishar** [aspnet/Mvc#7843]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
Use HttpsRedirection, and create a test which calls using HTTP.

`var options = new WebApplicationFactoryClientOptions`
`{`
`BaseAddress = new Uri(@"https://localhost:443"),`
`AllowAutoRedirect = true`
`};`

`var factory = new WebApplicationFactory<Startup>();`
`client = factory.CreateClient(options);`
`response = client.GetAsync("/").Result;`

#### Description of the problem:
When the application receives the call (via the above test), it is using unsecured HTTP instead of HTTPS as expected.

It's worth nothing that the HSTS and HttpsRedirection options are used:

```
            services.AddHsts(options =>
            {
                options.ExcludedHosts.Clear();
            });

            services.AddHttpsRedirection(options =>
            {
                options.RedirectStatusCode = StatusCodes.Status301MovedPermanently; 
            });
```

#### Expected Behaviour
For the call to be redirected and processed via HTTPS.

#### Version
`Microsoft.AspNetCore.All 2.1.0`:

**Comment by mkArtakMSFT** [comment]
Hi @a-vishar.

From the thread at: https://github.com/aspnet/Mvc/issues/7757
> we changed the redirection middleware to avoid redirecting when we can't know the HTTPS port. We no longer infer 443, given that its not setup in the test context, the original request simply goes through.

It seems you're missing the configuration for the HTTPS port: https://github.com/aspnet/BasicMiddleware/blob/1c0918c1f19d3eee220c76a0203bb3d4235f60e1/samples/HttpsPolicySample/Startup.cs#L25

**Comment by a-vishar** [comment]
That solves my problem, thanks!

I'd like to suggest the documentation be updated with a little "Note" to explain this situation.  As it stands the [Enforcing SSL](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio) docs don't indicate that for unit tests you must manually set the port.
