### ISSUE TITLE
Adding controller hangs Visual Studio

### ISSUE THREAD

**Issue by donnyv** [aspnet/Mvc#7844]
#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
Uninstall Nuget package Microsoft.EntityFrameworkCore.SqlServer and then use Visual Studio right click to create a new controller.

#### Description of the problem:
When using Visual Studio to create a new controller. The process hangs because it installs Microsoft.EntityFrameworkCore.SqlServer nuget package. When you try again after install, it works.

Why do you need this reference just to add a new controller?

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue, @donnyv.
@vijayrkn, seems this is caused by the scaffolder. Will move to the appropriate repo now.

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Scaffolding#806
