### ISSUE TITLE
Script Tag Helper asp-fallback-src fails integrity check

### ISSUE THREAD

**Issue by ghost** [aspnet/Mvc#7845]
#### Is this a Bug or Feature request?:
Bug 

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):

1.  Create a reference to a CDN, using a local fallback and an integrity check, such as:
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    asp-fallback-src="~/js/jquery.min.js"
    asp-fallback-test="window.jQuery"
    crossorigin="anonymous"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
</script>
```
2. Make sure the local file (jquery.min.js) is not binary equal to the CDN version. 
3. Change the CDN source to a non valid URI, such as using a non existent version 9.9.9. 
4. Fallback to local occurs, but the error occurs because integrity hash doesn't match, and this error thrown:
`Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:48888/js/jquery.min.js' with computed SHA-256 integrity 'oozPintQUive6gzYPN7KIhwY/B+d8+5rPTxI1ZkgaFU='. The resource has been blocked.`

#### Description of the problem:
The problem is that although the local trusted file can be text equal, if it is not binary equal it generates a different hash doesn't match the CDN hosted version. The resolution would involve not testing the local file copy (already trusted) against the integrity. To maintain backwards compliance, a new attribute should be added called ignore-fallback-integrity, and when set to true would ignore the integrity check on the fallback file. 

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.0

**Comment by pranavkm** [comment]
> can be text equal, if it is not binary equal

Out of curiosity, how does this happen?

**Comment by jmhmaine** [comment]
Age old problem with Windows vs Unix line endings...

**Comment by mkArtakMSFT** [comment]
Hi @joshhurley.
This is not something we would do at the moment. However, if you're interesting in submitting a PR for this, we'd happily take it.

**Comment by mkArtakMSFT** [comment]
So to summarize the approach we'd like to be taken here:
1. Introduce a new boolean property `asp-fallback-intergrity-check`
2. It should have default value of `true`, which will behave exactly as it does now
3. When set to `false` the integrity check for fallback file should be disabled

**Comment by jmhmaine** [comment]
@mkArtakMSFT, I tried searching the code base to find the location of the integrity attribute, but couldn't find it. If you could point me to the right location I can take a look at the source and Unit Test work needed. Thanks.

**Comment by mkArtakMSFT** [comment]
@joshhurley,
`integrity` is a native property of the HTML `script` tag: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
You should really just not render it, if the tag helper fallback happens.

**Comment by jmhmaine** [comment]
@mkArtakMSFT , I was looking for where the integrity property was rendered in the code base. I tried a simple search within GitHub but it didn't return any hits: https://github.com/aspnet/Mvc/search?q=integrity&unscoped_q=integrity

**Comment by StefanoP73** [comment]
@jmhmaine,
all the native properties of the HTML are reported as they are written so you can't find the integrity property in the code

@mkArtakMSFT,
I think that `asp-fallback-intergrity-check` is a good solution but this eliminate the security of the integrity check! It's possible to add also something like `asp-fallback-intergrity` with a value valid for the integry of the fallback?
So we are the possibility to disable the integrity check of fallback or insert a valid integrity for it that replace the original one

**Comment by jmhmaine** [comment]
@StefanoP73, the fallback is normally a local file, which you would trust since it is a file you are in control of from creation to deployment. Creating an integrity hash for local files wouldn't add value, only a burn to the user implementing. 


@mkArtakMSFT / @StefanoP73 , do you know of any location in the codebase where remove a native property from an HTML tag? I want to following an existing pattern -- if it exists.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, any suggestions regarding how to remove the `integrity` property?

**Comment by NTaylorMullen** [comment]
@jmhmaine if you're l looking to remove an unbound TagHelper attribute (something that the TagHelper doesn't special case/doesn't highlight purple) i'd recommend writing a TagHelper. Something like:

```C#
// Target any tag which has an integrity attribute, could also be more specific here if you want to scope the integrity removal.
[HtmlTargetElement(Attributes = "integrity")]
public class IntegrityRemovalTagHelper : TagHelper
{
    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        // Could do more logic here to only remove integrity when it makes sense, up to you
        output.Attributes.RemoveAll("integrity");
    }
}
```

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, parking this on your plate so you can track the proposed PR and close this, when the PR will be merged.

**Comment by NTaylorMullen** [comment]
2599e0f5cc00085bf3d97b0c52b080af0cea0233
8a77ed23d344c7e438d2772016be3c95f5291ae5
