### ISSUE TITLE
Allow Anchor Tag Helper to Output Directly to Query String

### ISSUE THREAD

**Issue by bgribaudo** [aspnet/Mvc#7846]
Anchor Tag Helper does not provide a way to _directly_ request that it output a query string. 

Currently, any route data values (e.g. `asp-all-route-data`, `asp-route-`) that do not match a route parameter are output on the query string. For example, the link below will be output containing `?value=view`.

    @{ var data = new Dictionary<string, string> { ["value"] = "view" }; }
    <a asp-all-route-data="@data">Some Link</a>

However, relying on route data to build the query string can bite in a couple scenarios:

*  When a desired query string parameter's name is also a route parameter name, its value will be used for the route parameter instead of being output on the query string. In the example above, if `data` was instead defined as `var data = new Dictionary<string, string> { ["action"] = "view" };` and the site was using the standard route map template of `{controller=Home}/{action=Index}/{id?}`, the link rendered would point to **action** view (e.g. `/SomeController/view`), instead of containing the intended query string of `?action=view`.
* Anchor Tag Helper's route data expects each parameter to have a single value. Query strings support multiple values per parameter name. (Related: #7826).

The above two scenarios can bite when trying to write generic code that outputs a query string. I've seen code examples along the lines of `<a asp-all-route-data="Context.Request.Query.ToDictionary(q => q.Key, q => q.Value.ToString())">`. People writing code like this may not realize that there are corner cases where may not work as expected.

This is a feature request to extend Anchor Tag Helper by adding something like `asp-all-query-data` and `asp-query-` (e.g. `asp-query-someParameterName`). Both would accept and properly render enumerable and non-enumerable values

````
<a asp-query-action="view"> -- someLink?action=view
<a asp-all-query-data=Context.Request.Query> -- outputs current request's query string

@{ var data = new[] { "a", "b" }; }
<a asp-value=@data> -- someLink?value=a&value=b

@{ var data = new Dictionary<string, IEnumerable<string>> { ["value"] = new[] { "a", "b" } }; }
<a asp-all-query-data=@data> -- someLink?value=a&value=b
````

**Comment by bgribaudo** [comment]
Related: #7367

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @bgribaudo.
This indeed is a related issue, which we'll consider with the other one you've referred to.
As you've already linked these two, we're closing this on and we'll review this ask also, when will be deciding on the exact approach to take for the other issue.

**Comment by bgribaudo** [comment]
Thank you, @mkArtakMSFT!
