### ISSUE TITLE
asp-for is rendering child property value instead of parent

### ISSUE THREAD

**Issue by data-handler** [aspnet/Mvc#7850]
### Minimal repro steps

1. Create Model with child 

```
public class CompanyAddress
    {
        public Guid Id { get; set; }
        public Company Company { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string Postcode { get; set; }
    }

public class Company
    {        
        public Guid Id { get; set; }
        public string Name { get; set; }        
        public CompanyType Type { get; set; }
    }
```

2. Create View with Parent Model

```
.................
@model CompanyAddress

<form asp-controller="Company" asp-action="Save" data-ajax="true" data-ajax-method="POST" data-ajax-success="onCompanySaved" id="editCompanyForm">    
    <input asp-for="Id" type="hidden">
    <input asp-for="Company.Id" type="hidden">        
</form>
```

3. Create Controller Action to return PartialView with populated parent model
```
public async Task<IActionResult> Edit(Guid id)
        {
            var model = await _companyAddressRepository.GetByIdAsync(id);
            return PartialView(model);
        }
```

4. View rendered page in browser
In my case, I am calling the Action using JQuery ajax
![image](https://user-images.githubusercontent.com/7189305/40843792-09757b34-65aa-11e8-9f2e-19ca30d534a7.png)

### Expected result
Value for hidden input using asp-for="Id" should equal Model Id

### Actual result
Value for hidden input using asp-for="Id" equals child Id (Model.Company.Id)

### Further technical details

csproj file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="2.8.391" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0" />    
  </ItemGroup>
  
</Project>
```

- I have confirmed via debug that the model passed to the view has the correct values for parent and child Id properties.
- When using asp-for helper, the value for both hidden inputs equals the child Id (Company.Id)
- When using the following syntax for the parent Id input, the value rendered is correct
<input id="Id" name="Id" type="hidden" value="@Model.Id" />

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @data-handler.
@NTaylorMullen can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
@data-handler could you provide a repro project based off of the default project template? I'm not able to reproduce it myself:

![image](https://user-images.githubusercontent.com/2008729/40854920-cd06d4a8-6587-11e8-859e-c3a234d34b09.png)
![image](https://user-images.githubusercontent.com/2008729/40854951-e762ea26-6587-11e8-83df-89b52a873564.png)
![image](https://user-images.githubusercontent.com/2008729/40854860-99494380-6587-11e8-876e-49598ccdd19f.png)

**Comment by data-handler** [comment]
Well I have to apologise. I don't know how or why, but this issue is resolved today.
Once again, my apologies for wasting your time.
