### ISSUE TITLE
ApiController: Body is used as binding source for complex objects for GET-only actions

### ISSUE THREAD

**Issue by rmja** [aspnet/Mvc#7851]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
In a controller attributed with `ApiController`, create an action marked with `HttpGet`. Let the action take a complex model as a parameter. A HTTP 400 is returned when requesting the action. Example snippet:

```c#
[ApiController]
public class TestController
{
    [HttpGet("/Test")]
    public async Task<IActionResult> Test(TestQuery query)
    {
       var result = await _mediator.Send(query, HttpContext.RequestAborted);

       return Ok(result);
    }
}
```

#### Description of the problem:
It seems as if the `ApiBehaviorApplicationModelProvider` [does not take into account](https://github.com/aspnet/Mvc/blob/418aac57f4aa962c153485ee9a7b08a5e48a3a7e/src/Microsoft.AspNetCore.Mvc.Core/Internal/ApiBehaviorApplicationModelProvider.cs#L228) whether the action is marked with GET. As GET request never can have a body according to the HTTP spec, it seems awkward that it can be used as a binding source for complex objects.

It would be really useful if something like this was added to `InferBindingSourceForParameter()`:
```c#
if (parameter.Action.Selectors.SelectMany(x => x.ActionConstraints).OfType<HttpMethodActionConstraint>().SelectMany(x => x.HttpMethods).All(x => x == "GET"))
{
    return BindingSource.Query;
}
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1

**Comment by rmja** [comment]
Any class, here is one:
```c#
public class TestQuery
{
    public int AParameterExpectedToBeReadFromTheQuery { get; set; }
}
```

**Comment by davidfowl** [comment]
I just want to know why you want to bind a complex object from the query string.

**Comment by mkArtakMSFT** [comment]
Hi @rmja.
We've decided to keep that logic straight forward to avoid confusion. One of the reasons is that using a complex type as a parameter for binding from query string is not so common.
You can simply apply the `FromQuery` attribute to the `query` parameter in your action, and it'll fix the issue.
We will consider creating a new analyzer to warn users about this behavior in the future, if we see that this becomes a point of confusion for a lot of developers.

/cc @pranavkm

**Comment by rmja** [comment]
So I guess its a feature and not a bug; In Denmark we have the saying: "You can choose between plague or cholera" :-)

I can see that there is an option to opt out from the binding behavior [here](https://github.com/aspnet/Mvc/blob/418aac57f4aa962c153485ee9a7b08a5e48a3a7e/src/Microsoft.AspNetCore.Mvc.Core/Internal/ApiBehaviorApplicationModelProvider.cs#L145), but where do I set the `SuppressInferBindingSourcesForParameters` globally in the Startup? In that way I can continue as before but still get the other benifits from the `ApiController`. Having to spay out `FromQuery` in some few hundred actions seems like a bad option. I already have the `FromBody`s there.

**Comment by vladislav-karamfilov** [comment]
@rmja , I think what you are looking for is here: https://docs.microsoft.com/en-us/aspnet/core/web-api/index?view=aspnetcore-2.1#binding-source-parameter-inference (the last part of this section)

**Comment by rmja** [comment]
@vladislav-karamfilov Yes, perfect, thank you!

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you advice how to configure this globally?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
