### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Analyzers.AvoidHtmlPartialAnalyzer cannot be created

### ISSUE THREAD

**Issue by twsouthwick** [aspnet/Mvc#7852]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
I'm updating a project to use ASP.NET Core 2.1, and am receiving some warnings about analyzers not being able to be created while running in Visual Studio.

#### Description of the problem:
Getting error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8032	An instance of analyzer Microsoft.AspNetCore.Mvc.Analyzers.AvoidHtmlPartialAnalyzer cannot be created from C:\Users\[user]\.nuget\packages\microsoft.aspnetcore.mvc.analyzers\2.1.0\analyzers\dotnet\cs\Microsoft.AspNetCore.Mvc.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	PortabilityService.Gateway	C:\Users\[user]\Projects\Software\dotnet-apiport\src\backend\PortabilityService.Gateway\CSC	1	N/A

```

The change in question is here: https://github.com/Microsoft/dotnet-apiport/pull/669

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

```
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0" />
```

**Comment by pranavkm** [comment]
What version of VS do you have? Asp.Net Core 2.1.0 requires VS 15.7 or newer and that should ship with Roslyn 2.8.0.

**Comment by twsouthwick** [comment]
15.7.2

**Comment by pranavkm** [comment]
Looks like a dup of https://github.com/dotnet/core/issues/1543. https://github.com/dotnet/core/issues/1543#issuecomment-389936577 has possible workaround for this. https://github.com/Microsoft/vsts-image-generation/issues/133 tracks creating an updated image with VS 15.7 on it.

**Comment by twsouthwick** [comment]
Those look to be about VSTS or using 15.6. I'm seeing this locally on a 15.7.2 install

**Comment by pranavkm** [comment]
Ahh, I thought you were seeing this on VSTS since your PR was broken there with this error. 

Could you look up your `devenv.exe.config` and verify it has the right version listed in it? On my box, it's located at `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe.config` and says

```xml
<!-- Redirects for Roslyn modules, these are normally added through pkgdef but we need them here for ngen purposes -->
<dependentAssembly>
  <assemblyIdentity name="Microsoft.CodeAnalysis.CSharp" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
  <bindingRedirect oldVersion="0.0.0.0-2.8.0.0" newVersion="2.8.0.0"/>
</dependentAssembly>
...
<dependentAssembly>
  <assemblyIdentity name="Microsoft.CodeAnalysis" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
  <bindingRedirect oldVersion="0.0.0.0-2.8.0.0" newVersion="2.8.0.0"/>
</dependentAssembly>
```

Maybe it's busted?

**Comment by twsouthwick** [comment]
Hmm I'm seeing the same thing as you

**Comment by pranavkm** [comment]
@jaredpar have you seen other reports of this error?

**Comment by jaredpar** [comment]
Are u getting this during build or just opening in VS?

**Comment by twsouthwick** [comment]
During build

**Comment by lyptt** [comment]
I'm getting this too during builds

**Comment by pranavkm** [comment]
@jaredpar are there any specific details we should be asking of @twsouthwick \ @lyptt? Mvc's analyzer binaries are compiled against Roslyn 2.8.0 packages which should be installed as part of 2.1 Sdk and VS 15.7.

**Comment by jaredpar** [comment]
If it's happening during build then we need to track down the actual csc being invoked here. The most likely problem is it's a pre-15.7 csc. It should be possible to see the csc being used by looking at the binary log file from a build and looking at the Csc task that is used for build.

**Comment by pranavkm** [comment]
@twsouthwick \ @lyptt you can get binary logs in VS by installing this extension - https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools. You could also get us the diagnostic text log from VS by changing the build output verbosity and copying the contents from the `Build` option in the `Output` window:

![image](https://user-images.githubusercontent.com/174281/41427626-5fffa38c-6fbc-11e8-9880-c76a977b2f63.png)

**Comment by twsouthwick** [comment]
I went to try to repro it and I'm not seeing it now. Since logging the issue, I've had to flatten my machine and have a fresh install of 15.7. @lyptt Are you able to get any of these logs?

**Comment by pranavkm** [comment]
@twsouthwick seeing that a fresh install fixed it, I'm going to guess it's likely bad machine state or a an issue with setup. If you or @lyptt run in this again, feel free to reopen this issue.
