### ISSUE TITLE
AutoValidateAntiforgeryTokenAttribute does not validate requests when registered globally by type.

### ISSUE THREAD

**Issue by plioi** [aspnet/Mvc#7855]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):

As correctly described by Andrew Lock in https://andrewlock.net/automatically-validating-anti-forgery-tokens-in-asp-net-core-with-the-autovalidateantiforgerytokenattribute/ you can set up the AutoValidateAntiForgeryTokenAttribute globally like so:

```cs
public class Startup  
{
  public void ConfigureServices(IServiceCollection services)
  {
    services.AddMvc(options =>
    {
        options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
    });
  }
}
```

However, if you use the type-based overload of Add instead, the attribute has no effect and antiforgery tokens are no longer validated:

```cs
public class Startup  
{
  public void ConfigureServices(IServiceCollection services)
  {
    services.AddMvc(options =>
    {
        options.Filters.Add<AutoValidateAntiforgeryTokenAttribute>();
    });
  }
}
```

#### Description of the problem:

It's unclear how the attribute would be silently ignored. In the same app, I register my own action filters by `<Type>` and they behave as expected. It would be quite easy for a developer to read the documentation, write their implementation with the "equivalent" `<Type>` overload and have a false sense that they have set up validation correctly.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

```xml
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.4" />
```

**Comment by kichalla** [comment]
@plioi thanks for reporting this issue. I can repro the issue and its a bug. Seems like we haven't tested this for a while now.

**Comment by kichalla** [comment]
IMO we should _not_ allow users to provide a type which already implements `IFilterFactory` to filter factories like `ServiceFilterAttribute` or `TypeFilterAttribute`.
Suggest we check the filter type's interfaces for IFilterFactory and throw with a clear message.

@rynowak your thoughts?

**Comment by rynowak** [comment]
Sounds good to me.

**Comment by mkArtakMSFT** [comment]
@pranavkm, reassigning this to you.
