### ISSUE TITLE
InvalidModelStateResponseFactory does not seem to be working

### ISSUE THREAD

**Issue by Eneuman** [aspnet/Mvc#7858]
Version: .Net Core 2.1 RTW, Visual Studio 15.7.2

Even though I added a custom InvalidModelStateResponseFactory like this:
```

services.Configure<ApiBehaviorOptions>(options =>
      {
        options.InvalidModelStateResponseFactory = context =>
        {
          var problemDetails = new ValidationProblemDetails(context.ModelState)
          {
            Type = "https://asp.net/core",
            Title = "",
            Status = StatusCodes.Status400BadRequest,
            Detail = "Please refer to the errors property for additional details.",
            Instance = context.HttpContext.Request.Path
          };

          return new BadRequestObjectResult(problemDetails)
          {
            ContentTypes = { "application/problem+json", "application/problem+xml" }
          };
        };
      });


```

The response is a normal BadRequest.

You can reproduce it like this:
1) Create new .Net Core 2.1, Web API Application (no HTTPS support or docker support)
2) Add the code above to the startup.cs class
3) Start debugging
4) Enter the following url: 
`http://localhost:<port>/api/values/9999999999999999999999999999999999`

The respons is this: 
`{"id":["The value '9999999999999999999999999999999999' is not valid."]}`

I was hoping to get a ValidationProblemDetails response.

Looking through the .Net Core 2.1 source code, I cannot find any test that tests this behavior. Has this been overlooked?

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please look into this? Thanks!

**Comment by kichalla** [comment]
@Eneuman Are you having the above code block _before_ the call to `AddMvc`? I believe what you are seeing is the order in which `Configure<ApiBehaviorOptions>` is executed (or in general any `Configure<Some-Options>`. If you have a list of `Configure<ApiBehaviorOptions>`, they are executed in that order and the options instance is mutated as it passes through each of them. So to fix your issue, you could add your code block after the call to `AddMvc`.

@HaoK Any ideas here on how to avoid stomping onto a user defined configure options? is the solution for users to use `PostConfigure<>`?

**Comment by HaoK** [comment]
Yeah its most likely ordering, PostConfigure is effectively the same as moving it to the end of all the configures.  Its only really necessary when you code that's called after you also adds configures and you want to ensure you go after them...

**Comment by Eneuman** [comment]
@kichalla Yeah, you are right. Im adding the options Before the call to `AddMvc`. I'm gonna rearrange the code and see if it works. Posting findings here when done. Do you want me to close this issue if it works?

**Comment by kichalla** [comment]
> Posting findings here when done. Do you want me to close this issue if it works?

Yes, please. Thanks!

**Comment by RehanSaeed** [comment]
@Eneuman Have you tried your code with `ReturnHttpNotAcceptable = true`? I'm getting 406Not Acceptable responses when I use `InvalidModelStateResponseFactory` as you have done.

**Comment by RehanSaeed** [comment]
I'm trying to get `InvalidModelStateResponseFactory` working nicely with Swagger, `ReturnHttpNotAcceptable = true` and custom media types:

```
services.AddMvcOptions(
    options =>
    {
        var jsonInputFormatterMediaTypes = options
            .InputFormatters
            .OfType<JsonInputFormatter>()
            .First()
            .SupportedMediaTypes;
        var jsonOutputFormatterMediaTypes = options
            .OutputFormatters
            .OfType<JsonOutputFormatter>()
            .First()
            .SupportedMediaTypes;
        jsonInputFormatterMediaTypes.Insert(0, "application/vnd.restful+json");
        jsonOutputFormatterMediaTypes.Insert(0, "application/vnd.restful+json");
        jsonOutputFormatterMediaTypes.Add("application/problem+json");

        options.ReturnHttpNotAcceptable = true;
});
```

@Eneuman With your code, I keep getting 406 Not Acceptable responses when attempting to return a problem details response. Setting `ReturnHttpNotAcceptable` to `false` fixes the problem but that's not what I want. Swagger is sending an `Accept` HTTP header with a value of `application/json`, so in theory, everything should just work.
