### ISSUE TITLE
In place update (publish) fails on Ubuntu 16.04 with ASP.NET Core 2.1

### ISSUE THREAD

**Issue by vbougay** [aspnet/Mvc#7860]
We were running and updating our ASP.Net Core 2.0 app on Ubuntu 16.04 for a while. We simply ran 

`dotnet publish --configuration Release  --output /var/apps/<appname> `

to replace the previous build with a new one and it worked just fine. The old build was replaced by a new one on the fly and changes were picked up by ASP.NET. We use supervisor service to get the app up and running continuously in a setup recommended by Scott Hanselman in https://www.hanselman.com/blog/PublishingAnASPNETCoreWebsiteToACheapLinuxVMHost.aspx.

We have migrated to 2.1 and noticed that it's no longer possible to do in place update because the same publish command fails:

`/usr/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(168,5): error MSB3021: Unable to copy file "obj/Release/netcoreapp2.1/App.pdb" to "/var/apps/<appname>/App.pdb". The process cannot access the file '/var/apps/<appname>/App.pdb' because it is being used by another process. [/var/reps/mvp/App/App.csproj]`

I'm not sure whether it's ASP.NET issue or it's related to .NET Core/build system. 

Now we have to stop supervisor service and shut down app first, then perform publish and launch it back. It's not just inconvenient, but leads to short downtimes of our app we would like to avoid.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @vbougay.

@davidfowl, is this something we've ever supported?

**Comment by shirhatti** [comment]
This is expected behavior.

My recommendation is to use two different virtual hosts/server blocks in your nginx configuration and swap between the two when you want to upgrade your application (similar to a blue-green deployment).

**Comment by shirhatti** [comment]
Ahh! I missed the part where you claim that it worked it 2.0 and no longer works in 2.1. That surprises me. I don't believe we ever made that guarantee in 2.0.

**Comment by vbougay** [comment]
@shirhatti Thanks for the clarification!

It's our first project based on Core, but we did many more with the classic ASP.NET MVC and IIS and it was always supported scenario there so we expected the same behavior with ASP.NET Core and it worked just fine on 2.0. Would be nice to keep it going with 2.1 though.

**Comment by davidfowl** [comment]
I’m not 100% sure why this ever worked before (on 2.0). Maybe you were getting lucky?

**Comment by vbougay** [comment]
@davidfowl With many years of experience with ASP.NET MVC/IIS you take it almost as granted and that "downgrade" feels like a regression. I would do some research over the weekend to see how it worked in our case. Is there a chance that  .NET runtime was not locking application files for whatever reason and ASP.NET engine was detecting changes and simply terminated/restarted dotnet process?

**Comment by davidfowl** [comment]
Nothing in ASP.NET Core detects changes and restarts the application. The files are locked in place when running.

**Comment by mkArtakMSFT** [comment]
Thank you for your feedback.
We're closing this issue as the behavior discussed seems to be by design.
