### ISSUE TITLE
Question/Feature: Don't load method parameter (Notmapped?)

### ISSUE THREAD

**Issue by xmlapi** [aspnet/Mvc#7863]
I'm using Razor Pages 2.1 and have the following PageModel:
```C#
public class IndexModel : PageModel {
   public OnGetAsync(int? id, bool isPostBack = false) {
         //load object from db
        //if IsPostBack == false, assign properties from db object to Model object
   }

   public OnPostAsync(int? id) {
        await OnGetAsync(id, true);
        if(!Model.IsValid) return Page();
        //save model to db
   }
}
```

Basically, when posting, I want to load some of the model and page properties from the DB. 

While the above code works, unfortunately it's possible to set the isPostBack argument to true in a GET request. Is there a way to prevent that? Perhaps a NotMapped property so that it is only set internally from from the IndexModel code...and not from the HTTP GET/POST collection.

I can always have a separate method "LoadFromDB" but it's more verbose.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
Hi @xmlapi.
Rather than having the `isPostBack` as a parameter on the handler, consider have it as a property on the PageModel, which will get its value from the `TempData`, where you set the actual flag on the previous request. That's just one way you can achieve what you want.

**Comment by pranavkm** [comment]
I'd recommend refactoring your code so you're not calling handlers from other handlers. Just makes the code a lot simpler no:

```C#
public class IndexModel : PageModel {
   public OnGetAsync(int? id) {
        InitializeModel(id, false);
   }

   public OnPostAsync(int? id) {
        InitializeModel(id, true);
        if(!Model.IsValid) return Page();
        //save model to db
   }
   
   private void InitializeModel(int id, bool isPostback)
   {
       ...
   }
}
```

Keeps the two concerns separate.
