### ISSUE TITLE
taghelper input/select use query string, not model to get value

### ISSUE THREAD

**Issue by zokiad** [aspnet/Mvc#7865]
Hi,

I have a form with a input text:
```
<form method="get">
    <input asp-for="text" />
    <p>The value of Model.text is @Model.text</p>
    <input value="Submit" type="submit" />
</form>
```

Input text is associated to model:

```
    public class TestModel
    {
        public string text { get; set; }
    }
```

In my action, I modify my text and pass model to view:

```
        public IActionResult Index(TestModel model)
        {
            model.text = "My text define in Index action";
            return View(model);
        }
```

See the solution test:
[TestAspFor.zip](https://github.com/aspnet/Mvc/files/2069587/TestAspFor.zip)

**Issue:**
Now, i edit the input text with "Hello" text and click on submit. The form is submitted to new url:

http://localhost:5000/?text=Hello

The input is not initialised with Model.text but with the query string text.
Input should be always initialized with value of model,not of query string. Else, it is not possible to modify the value of an input/select.

With .net framework, the behavior is: input is always inialized with model value.

**Comment by zokiad** [comment]
Workaround:
ModelState.Remove(nameof(model.text))

is it a behavior by design ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @zokiad.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
This behaviour is by design. `ModelState` values ensure what the user submitted is round-tripped to the next view, even if a value cannot be written into the model.

@zokiad your "workaround" is the intended option when an action (or page handler) corrects or otherwise updates what the user submitted.
