### ISSUE TITLE
[question] is it possible to update a parameter's model binder from an action filter?

### ISSUE THREAD

**Issue by smarts** [aspnet/Mvc#7868]
example parameter declaration from controller action (`bar` is the parameter that I want to run through `MyFilter`, which is both a resource filter and model binder):
```csharp
[TypeFilter(typeof(MyFilter))]
[HttpPost("{id}")]
public Task<IActionResult> Foo([FromRoute(Name="id")] Bar bar, [FromBody] Baz baz) { … }
```
filter implementation:
```
var params = get parameters of a particular type and binding source from resourceExecutingContext.ActionDescriptor.Parameters
for each p in params
  var vpr = get value provider result for p.BindingInfo.BinderModelName
  if (vpr == ValueProviderResult.None) throw exception
  var response = get value from external data source using vpr.Values as ID
  if (response is not found) return NotFoundResult
  cache response content in current request
  p.BindingInfo.BinderType = GetType()
  p.BindingInfo.BindingSource = BindingSource.Custom;
```
model binder implementation:
```
var value = get cached content from request
bindingContext.Result = ModelBindingResult.Success(value)
```

the model binder implementation is never reached

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@smarts, it's not possible to modify the model binder used for a specific parameter.

**Comment by rynowak** [comment]
`You can apply a custom model binder to a parameter using `[ModelBinder]` https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.1#custom-model-binder-sample

This doc shows usage on a class, but it also works on action parameters

**Comment by smarts** [comment]
thanks @rynowak , but I was trying to avoid having to specify both the resource filter AND a model binder. I.e., I want the resource filter to _imply_ a type of model binder for all parameters of a particular type.

@mkArtakMSFT i'm wondering what [the documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1#filter-types) means when it says the following about resource filters:
> They run before model binding, so they can influence model binding.

**Comment by rynowak** [comment]
So in general if what you're looking for is to operate on a value after its been modelbound, you want an action filter. That will let you see the values that the action is going to see.

**Comment by smarts** [comment]
That's not what i want @rynowak . I want to take an incoming primitive value (think a number or a string) and turn it into a complex object (e.g., looking the object up in a database by ID). That's could be done via model binding. The catch is that I also want to control the response if that I can't do the transformation, which is outside the purview of model binding. Hence the resource filter. However, since the resource filter and the desired model binding will always work in conjunction, and all the model binding needs in order to do its job is to know which route value to grab, I didn't want to have to specify both the resource filter AND a model binder. I wanted the resource filter to force the model binder for a particular parameter.

**Comment by rynowak** [comment]
> I want to take an incoming primitive value (think a number or a string) and turn it into a complex object (e.g., looking the object up in a database by ID). That could be done via model binding.

An action filter will also let you add/replace a value in the action arguments. 

Do you *actually* need this to happen during the model binding pass? Does the object need to be validated? Is there user input or are you looking something up by ID?
