### ISSUE TITLE
[Patch] ProducesResponseType doesn't infer the type from ActionResult<T>

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7875]
Issue tracking porting https://github.com/aspnet/Mvc/issues/7871 to 2.1.x

**Comment by muratg** [comment]
Approved for 2.1.3.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/82f7f2aab88f1b9af15f60df3830ed327b2d5a89. PR https://github.com/aspnet/Mvc/issues/7875
