### ISSUE TITLE
Circular dependency exception in Startup.Configure

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aspnet/Mvc#7878]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
https://github.com/MaximBalaganskiy/AspNetCircularDependency

#### Description of the problem:
I am injecting `IEnumerable<IHttpContextAccessor> httpContextAccessors` into my db context to track a user name who changes records. It is `IEnumerable` to be able to reuse the context in a Windows Service project where there is no http context.

In the `Startup.Configure` method I used to get an instance of a  seeding service which has a dependency on a `RoleManager` to create default roles. In Asp.Net Core 2.1 this throws an exception
```
System.InvalidOperationException: 'A circular dependency was detected for the service of type 'Microsoft.AspNetCore.Http.IHttpContextAccessor'.
Microsoft.AspNetCore.Identity.RoleManager<Microsoft.AspNetCore.Identity.IdentityRole>(Microsoft.AspNetCore.Identity.AspNetRoleManager<Microsoft.AspNetCore.Identity.IdentityRole>) -> Microsoft.AspNetCore.Identity.IRoleValidator<Microsoft.AspNetCore.Identity.IdentityRole>(Microsoft.AspNetCore.Identity.RoleValidator<Microsoft.AspNetCore.Identity.IdentityRole>) -> Microsoft.AspNetCore.Http.IHttpContextAccessor(Microsoft.AspNetCore.Http.HttpContextAccessor) -> Microsoft.AspNetCore.Http.IHttpContextAccessor'
```

StackTrace:
```
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain.CheckCircularDependency(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at WebApplication1.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceScopeFactory serviceScopeFactory) in C:\Users\max\source\repos\WebApplication1\WebApplication1\Startup.cs:line 59
```
Roughly this is demonstrated in the aforementioned repository which is a default 2.1 web application template with a couple of additional classes.

Removing line `Startup.cs:59` fixes the issue even though `RoleManager` is injected into `Index.cshtml.cs` as well. 
Strangely enough, injecting just `IHttpContextAccessor httpContextAccessor` fixed it as well.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`: 
2.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MaximBalaganskiy.
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
@HaoK Can you take a look at this?

**Comment by HaoK** [comment]
Yeah so the role managers depend on IHttpContextAccessor and the stores, which depend on DbContext, its likely something in how you inject the IEnumerable context accessors which is causing this usse.

What exactly does that look like?

**Comment by MaximBalaganskiy** [comment]
https://github.com/MaximBalaganskiy/AspNetCircularDependency/blob/bf454146ca34af927204c93d2dc0b1f6fb28d2a4/WebApplication1/MyContext.cs#L14

**Comment by HaoK** [comment]
So this only fails when you try to do it in Configure, but works when you do it normally via the Controller?

Here's the circular ref in call stack of the error you included above

```
Microsoft.AspNetCore.Identity.RoleManager<Microsoft.AspNetCore.Identity.IdentityRole>
(Microsoft.AspNetCore.Identity.AspNetRoleManager<Microsoft.AspNetCore.Identity.IdentityRole>) ->

 Microsoft.AspNetCore.Identity.IRoleValidator<Microsoft.AspNetCore.Identity.IdentityRole>(Microsoft.AspNetCore.Identity.RoleValidator<Microsoft.AspNetCore.Identity.IdentityRole>) ->

 Microsoft.AspNetCore.Http.IHttpContextAccessor(Microsoft.AspNetCore.Http.HttpContextAccessor) -> Microsoft.AspNetCore.Http.IHttpContextAccessor'
```

**Comment by MaximBalaganskiy** [comment]
Yes, only in configure and only when injecting an enumerable. Also, I don't
see the dependency of RoleValidator on the accessor in the source code

**Comment by MaximBalaganskiy** [comment]
And accessor itself does not inject anything

**Comment by HaoK** [comment]
Does injecting `IEnumerable<IHttpContextAccessor>` satistify services that are looking for `IHttpContextAccessor`?  Or does it clobber anything even?

**Comment by MaximBalaganskiy** [comment]
It injects fine except for the Configure method. Used to work in 2.0 as well

**Comment by HaoK** [comment]
There is no http context yet in Configure, which is probably the issue.

**Comment by MaximBalaganskiy** [comment]
There is an accessor which is injected. Again, it all works when a single
instance is injected. Have you tried rubning the repo project?

**Comment by HaoK** [comment]
Again, the line that stands out as something that likely won't work is: `It is IEnumerable to be able to reuse the context in a Windows Service project where there is no http context.`

Identity is meant to be scoped, and not captured like this outside of a request like this.  I don't doubt what you are seeing.

**Comment by MaximBalaganskiy** [comment]
Using enumerable is a totally legitimate way of injecting an optional
dependency. I'm not injecting a context, I'm injecting an accessor. If it
does not exist in the scope I will get an empty list. And this was working
in 2.0.

According to the source code neither RoleVaidator nor HttpContextAccessor
do not depend on each other directly or indirectly. If they were injecting
a single instance wouldn't work either. That is why I think it is a bug.

**Comment by HaoK** [comment]
Ok i'll take a look to see what might have changed between 2.0 and 2.1

**Comment by HaoK** [comment]
This is weird, this repros in your app, but if I copy the startup registrations and context into a 2.2 identity sln, it doesn't repro, 

@pakrym do you own DI right now?  Can you take a look to see what's going on?

It seems strange that changing https://github.com/MaximBalaganskiy/AspNetCircularDependency/blob/bf454146ca34af927204c93d2dc0b1f6fb28d2a4/WebApplication1/MyContext.cs#L13 to a single IHttpContextAccessor instead of IEnumerable would work.  This seems like a bug in the Circular reference detection logic possibly?

**Comment by HaoK** [comment]
The other quirk of this repro is that the role manager is being resolved inside of Configure (the normal usage pattern where the manager is created normally via injection works fine)

**Comment by MaximBalaganskiy** [comment]
I simplified it a bit - in a real project I resolve a seed service which in
its turn depends on a role manager

**Comment by pakrym** [comment]
I'll take a look.

**Comment by mkArtakMSFT** [comment]
@pakrym, do you have any updates regarding this?

**Comment by pakrym** [comment]
Filed https://github.com/aspnet/Home/issues/3232
