### ISSUE TITLE
How can i access URL of path in MVC Core 

### ISSUE THREAD

**Issue by rishabhack** [aspnet/Mvc#7879]
Unable to access Url.ActionContext.View.Path
I have to show on particual Path/View/Action Call

How can i get path in ASP.Net Core MVC
in quick watcher Url.ActionContext.View.Path it shows value but can't use gives error

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by rishabhack** [comment]
ok Sure thanks & apology
