### ISSUE TITLE
AddApplicationPart Does Not Load FSharp Definitions

### ISSUE THREAD

**Issue by valainisgt** [aspnet/Mvc#7880]
#### Bug:
Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
https://github.com/valainisgt/AddApplicationPart-FSharp

#### Description of the problem:
I have a C# asp.net core application targeting net47 that acts as the host and a separate F# .net core class library targeting net47 that contains all of the controller definitions.

When configuring the application in the Startup class, I use the IMvcBuilder.AddApplicationPart extension method to tell the framework that the controllers are located in a different assembly.

However, each request comes back with a 404.

EDIT: Worth nothing that the compiled DLL file from the F# project does not have any version info on it.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @valainisgt.
@pranavkm, can you please look into this?

**Comment by pranavkm** [comment]
MVC does not look for controllers in nested classes. Your controller is inside a module, which is essentially a static class. In addition, you don't need to add the class library as an application part explicitly. MVC registers all referenced binaries as application parts as long as they in turn transitively reference MVC.
