### ISSUE TITLE
Return PartialAsync from Razor Pages Page handler

### ISSUE THREAD

**Issue by iforlife** [aspnet/Mvc#7885]
#### Is this a Bug or Feature request?:
Feature request

#### Description of the problem:
It will be very useful to be able to return the equivalent of `@await Html.PartialAsync(...)` , but for the page handler

```
public async Task<IActionResult> OnPostCreateAsync()
{
    //some logic
    return await PartialAsync(partialViewName, model, viewData);
}
```

**Comment by pranavkm** [comment]
cc @DamianEdwards

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @iforlife.
While this is a resonable ask, it doesn't align with our priorities for the upcoming release.
Moving this issue to the Backlog for now so we can review it in the future.

**Comment by pranavkm** [comment]
@iforlife if you'd like to send a PR for this, we'd be happy to consider it. Here's a recent change to add support for a helper method to Razor Page \ PageModel that you may use as a template: https://github.com/aspnet/Mvc/commit/26454fb1da36191ee43b59b956f6e9f2d945a3a7

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/dee479fda712e35cf740239587e438a8143850d8
