### ISSUE TITLE
How does the "AuthorizeAttribute" work?

### ISSUE THREAD

**Issue by rocketRobin** [aspnet/Mvc#7890]
#### This is a question!

- How the authorize attribute choose a authentication scheme?

The authentication progress is in the authentication middleware and this is before mvc middleware.wheh the request approch mvc action the authentication end. but the the attribute still can choose a scheme why? 

I have been plagued by this problem for a long time.

**Comment by mkArtakMSFT** [comment]
Hi @rocketRobin.
Looks like the part you'r missing is the Authorization filters. You can read more about filters here: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1

Hope this helps.
On the side note, for questions like these we recommend people to use StackOverflow, as that way they will get much faster answers to their questions.

**Comment by javiercn** [comment]
Thanks for contacting us.

You might have more than one authorization scheme active in your application at the same time. You can have for example cookies and jwt bearer for an app that has a website component and an API component.

In those cases you can specify the authentication scheme in you authorize attribute to filter the identity of the user to that particular scheme. Its also worth noting that only one authentication scheme is active by default, so if you have multiple, the authentication for the additional ones happens on the authorize filter.

Hope this helps answer your question. Closing this as there's no other action to be taken here.
