### ISSUE TITLE
First commit

### ISSUE THREAD

**Issue by Matthiee** [aspnet/Mvc#7891]
What are good labels for a first commit?

**Comment by proggmatic** [comment]
"Initial create" or "First commit" ))

**Comment by mkArtakMSFT** [comment]
Hi @Matthiee.
What are you trying to do? Are you looking for issues you can handle as your first contribution?

**Comment by Matthiee** [comment]
@mkArtakMSFT yes I'm looking for issues to handle as my first contirbution.

**Comment by mkArtakMSFT** [comment]
That's great. You can look for issues marked with `up-for-grabs` label. It's available across multiple repos in aspnet organization. Here are all the `up-for-grabs` issues in `aspnet/mvc` repo: https://github.com/aspnet/mvc/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs
