### ISSUE TITLE
Add support for custom validation attributes on parameters 

### ISSUE THREAD

**Issue by abatishchev** [aspnet/Mvc#7893]
#### Is this a Bug or Feature request?:

Featiure

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):

>preferrably 

You got a typo in the template, it's preferably, correct? :)

#### Description of the problem:

I'm looking whether the following is possible, and if not then whether it would be made possible in the future:

```c#
public class PersonController
{
    public IActionResult Get([MyStringValidator]string name)
        => Ok("Hello " + name);
}
public class MyStringValidator : ValidationAttribute
{
    public bool IsValid(object value)
        => (value as string) == "Alex";
}
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

Microsoft.AspNetCore version 2.1.0

/cc @pranavkm 

Thanks,
Alex

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @abatishchev.
@glennc, any thoughts regarding this ask?

**Comment by mkArtakMSFT** [comment]
And thanks for noticing the type - fixing now.

**Comment by abatishchev** [comment]
You know, the problem for me right now is that I don't get any validation kicked-in. Neither this, nor what was available earlier (using [Required] or [BindRequired] on post request model).

**Comment by pranavkm** [comment]
Do you have a repro app? This works fine for me as long as there's a value for the `name` parameter:

```C#
public class PersonController : Controller
{
    public IActionResult Get([MyStringValidator]string name)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }
    
        return Ok("Hello " + name);
    }
}
public class MyStringValidator : ValidationAttribute
{
    public override bool IsValid(object value)
        => (value as string) == "Alex";
}
```

**Comment by abatishchev** [comment]
It works fine in small ASP.NET Core .ENT 4.6.2 application, even within SF. Will investigate more what's wrong with my real app.

**Comment by abatishchev** [comment]
The issue was that I was using `AddMvcCore` rather than `AddMvc`. Do you know whether the doc states that clearly?

**Comment by pranavkm** [comment]
We generally don't recommend using `AddMvcCore` unless you know what you're doing. See the remarks section for the API - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L111-L119

**Comment by abatishchev** [comment]
Right. My application is Web API only so I though it would be sufficient. Won't use `AddMvcCore` anymore, kind of. Thanks!
