### ISSUE TITLE
Custom action invoker

### ISSUE THREAD

**Issue by ydyote** [aspnet/Mvc#7899]
Hello, 

is it possible to create a custom default action invoker like this? http://techfunda.com/howto/925/controller-action-invoker

because I need it for e.g. setting default REST response when an exception happened and this have to be set before the response serialization to http response content, logging stuff, custom authorization not dependent on middleware but on the actual action which is about to execute etc.

please let me know if this is possible right now (in asp.net core (2.1) mvc or if it will be possible in the future.

P.S.:
I found https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Core/Internal/ActionInvokerFactory.cs
https://github.com/aspnet/Mvc/blob/599d1a502ef358678202345ced2d11ddca0754f3/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionInvoker.cs
https://github.com/aspnet/Mvc/blob/e0188c4936f54eddbc984b8598e8cc62c72adf25/src/Microsoft.AspNetCore.Mvc.RazorPages/Internal/PageActionInvoker.cs

and maybe if it is possible to inherit from them and replace them in the action invoker factory it will be ok but from ControllerActionInvoker you cannot inherit right now, because of the internal constructor.

Thank you for the response.

**Comment by pranavkm** [comment]
Could you elaborate a bit on what you are attempting to with a custom invoker. Typically, a [set of filters](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1) should get meet most of your requirements.

**Comment by ydyote** [comment]
Thanks for your reply,

I took my time and looked at those filters.

They are not suitable for my needs because I need an ambient context accessible from within the action.
I want my own db connection handling, authorization etc. and for this good place was in the invoker.

Filters current code flow:
Filter A In -> Filter A Out -> Filter B In -> Filter B Out..

I need this kind of sync flow:
FIlter A In -> Filter B In -> Filter B Out -> Filter A Out..

Because the usage will be like this:

PrepareDatabaseConnection(() => {
  PrepareAuthenticationContext(() => {
      InvokeControllerAction();
  });
});

(ofc this would be configurable, what will be prepared and what won't)
and then you will have access to it within the actions, everything prepared for you.

and it could be used globally for every controller in the application.

**Comment by mkArtakMSFT** [comment]
Closing per @rynowak 's response.
