### ISSUE TITLE
No default AddHttpsRedirection() overload

### ISSUE THREAD

**Issue by abatishchev** [aspnet/Mvc#7900]
#### Is this a Bug or Feature request?:

Both

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

First:

>Install-Package Microsoft.AspNetCore.HttpsPolicy -Version 2.1.0

Then have code:

```c#
public override void ConfigureServices(IServiceCollection services)
{
    services.AddHttpsRedirection();
}
```

#### Description of the problem:

I don't want to change the default options and use everything as is. But the code doesn't compile as there is no overload accepting no `options`. instead I have to pass empty lambda:

```c#
public override void ConfigureServices(IServiceCollection services)
{
    services.AddHttpsRedirection(options => { });
}
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

2.1.0

**Comment by vladislav-karamfilov** [comment]
You should use `app.UseHttpsRedirection()` in the `Startup.Configure()` method (not `services.AddHttpsRedirection()` in `Startup.ConfigureServices()`). Only if you want to configure the HTTPS port and/or the redirect status code you'll need to use the `services.AddHttpsRedirection()` in `Startup.ConfigureServices()`. But if you don't want to configure them there's no need to call this method.

**Comment by abatishchev** [comment]
I just followed the usual configuration method names convention: Add* and then Use*. And sometime Use doesn't work without Add. So again the usual practice to have both of them, just in case.

So you're sayng that for HttpRedirection there is no need to call Add until I want to change the defaults? Can it be still added to follow the rest?

**Comment by vladislav-karamfilov** [comment]
Yes, there's no need to call the Add method unless you want to change the defaults. I believe you can still add it if you want consistency.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by abatishchev** [comment]
Please add an emty Add() method for consistency with the rest, thus for better readability.

**Comment by barry-schneider** [comment]
When you use `app.UseHttpsRedirection()` and the the SSL port is not configured using 'services.AddHttpsRedirection()' then the port must be set using:

-  HTTPS_PORT environment variable
-  IServerAddressesFeature

If neither of these are configured, then will not redirect to SSL based on the the function [TryGetHttpsPort](https://github.com/aspnet/BasicMiddleware/blob/f320511b63da35571e890d53f3906c7761cd00a1/src/Microsoft.AspNetCore.HttpsPolicy/HttpsRedirectionMiddleware.cs#L106)
