### ISSUE TITLE
ASP.NET Core 2.0 File post using Form Tag helper doesn't work, but works well with Razor syntex

### ISSUE THREAD

**Issue by inabeel** [aspnet/Mvc#7901]
#### Is this a Bug or Feature request?:
It is a bug in ASP.NET Post

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):
I am working on simple ASP.NET Core Form, and posting file using simple post using form tag helper
<form id="frmAdvancedProfile" asp-controller="Profile" asp-action="SaveNetworkProfile" method="post" enctype="multipart/form-data">

and Input tag:
`<input name="File" type="file" class="form-control" placeholder="">`

Then in Controller, file is always null
```public IActionResult SaveNetworkProfile(PortalsEditVM model, string Contacts, IFormFile file)```

While when i replaced form tag helper with Razor syntex:
@using (Html.BeginForm("SaveNetworkProfile", "Profile", FormMethod.Post, new { enctype = "multipart/form-data" }))

It starts working fine.

#### Description of the problem:
Form tag helper is not posting the file correctly.

`Microsoft.AspNetCore.All`: 2.0.8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @inabeel.
Can you share a repro project so we can investigate?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
