### ISSUE TITLE
Json Contract Resolver with Controllers loaded via WebApiCompatShim

### ISSUE THREAD

**Issue by woodne** [aspnet/Mvc#7903]
#### Is this a Bug or Feature request?:

Bug

#### Steps to reproduce (preferrably a link to a GitHub repo with a repro project):

https://github.com/woodne/webapi-compat-shim-json

1. Load the above project and run
2. GET http://localhost:5000/new/api/values and http://localhost:5000/old/api/values
3. See that the casing of the two is different, the mvc 6 controller has the correct serializer settings, but the old one loaded via the compatshim is not getting the camel case contract resolver.

#### Description of the problem:

When loading ApiController via the WebApiCompatShim, it does not seem to respect the json options, so it does not get the contract resolver that I prefer. I can't seem to see a way to set the settings explicitly for the old controllers. This is difficulty because we have dozens of controllers/models with our old application controllers that would require a lot of work to explicitly add the correct name explicitly in the DataMember attribute, and would prefer for the Contract resolver to work for these controllers.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

Microsoft.AspNetCore.Mvc

**Comment by pranavkm** [comment]
`WebApiCompatShim` has it's different set of options \ formatters and needs to be configured differently from Mvc. You can configure it after your call to `AddWebApiConventions`

```C#
services.Configure<WebApiCompatShimOptions>(options =>
{
   var jsonFormatter = options.Formatters.OfType<JsonMediaTypeFormatter>().First();
   jsonFormatter.SerializerSettings.ContractResolver = new DefaultContractResolver
   {
       NamingStrategy = new CamelCaseNamingStrategy(),
   };
});
```

**Comment by woodne** [comment]
@pranavkm Thanks! This is exactly what I needed.
