### ISSUE TITLE
JsonIgnore not working when using JsonHelper.Serialize on object

### ISSUE THREAD

**Issue by joetherod** [aspnet/Mvc#7917]
Bug:
JsonIgnore not working when using JsonHelper.Serialize on object
AspnetCore 2.0 - MVC Core App

When Calling the JsonHelper from Razor, it still trys to serialize the property when it has the [JsonIgnore] attribute.

Is there another attribute to use to ensure that a property its not serialized when calling that helper method in razor??

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, any thoughts?

**Comment by NTaylorMullen** [comment]
@joetherod I tried reproing your issue from the default Razor Page and MVC project templates but was not able to:
![image](https://user-images.githubusercontent.com/2008729/41442139-942336fa-6fea-11e8-96f1-5ecedc8b6129.png)

Would you mind providing a simple repro app derived from the default project templates?

**Comment by joetherod** [comment]
@NTaylorMullen I did as you did in another project and it worked as expected. I verified my code change and did it on the wrong model property. My bad. Thanks for the quick response and sorry for wasting your time.
