### ISSUE TITLE
How to post-process response after IValidatableObject validation failed?

### ISSUE THREAD

**Issue by abatishchev** [aspnet/Mvc#7920]
#### Is this a Bug or Feature request?:

Question.

#### Description of the problem:

I have a model that implements `IValidatableObject`, e.g. `class Person : IValidatableObject`. Sometimes this validation fails so web app returns 400 Bad Request. All good.

But how can inject into the pipeline afterwards and alter the response? I integrate with a service that requires all responses to be formatted in specific way.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.0.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by abatishchev** [comment]
Sure, I'll ask there. I just wanted to know how to do that *right* rather than just how to do that

**Comment by mkArtakMSFT** [comment]
@kichalla, suggestions?

**Comment by abatishchev** [comment]
Here's what I've got so far:
```c#
internal sealed class RolloutResultFilter : ResultFilterAttribute
{
    public override void OnResultExecuting(ResultExecutingContext context)
    {
        // call base first to get context.Result assigned
        base.OnResultExecuting(context);

        RolloutResponseErrorDetail CreateError(KeyValuePair<string, object> pair)
        {
            return new RolloutResponseErrorDetail(
                ((IEnumerable<string>)pair.Value).Single(),
                "RolloutParameter",
                pair.Key);
        }

        switch (context.Result)
        {
            case BadRequestObjectResult badResult:
            {
                var error = (SerializableError)badResult.Value;
                var controller = (ControllerBase)context.Controller;
                context.Result = controller.Rollout(
                    HttpStatusCode.BadRequest,
                    DeploymentState.Failed,
                    "Rollout parameter errors",
                    error.Select(CreateError));
                break;
            }
        }
    }
}
```

What concerns me that status code is still 200, not 400 already. What likely means I'm ittle to early in the pipeline.

Can I override the filter that handles validation failures and assigned response result?

**Comment by pranavkm** [comment]
The status code isn't set until the result actually executes. 

* If you're using `ApiController`, there's an action filter that produces a `BadRequest` from the model state dictionary. You can use [`ApiBehaviorOptions.InvalidModelStateDictionaryFactory`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ApiBehaviorOptions.cs#L25) to dictate it's behavior.

* For a regular controller, the action is responsible for producing the bad request, so you can do whatever you'd like as part of producing the result.

**Comment by abatishchev** [comment]
@pranavkm, `options.InvalidModelStateResponseFactory` worked like a charm. Thanks, appreciate!
