### ISSUE TITLE
Dynamic model attributes

### ISSUE THREAD

**Issue by adams85** [aspnet/Mvc#7929]
#### Is this a Bug or Feature request?:
Kind of a FR.

#### Description of the problem:
After upgrading from 2.0 to 2.1, I noticed the constructors of [Microsoft.AspNetCore.Mvc.ModelBinding.ModelAttributes](https://github.com/aspnet/Mvc/blob/78fc49ba0c8ad7859e1f3a8aa6c3d17c7cd11f5a/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Metadata/ModelAttributes.cs) are marked as obsolete to be removed in a future version.

In my projects I use these constructors to add validation attributes to my models dynamically (see [this code](https://github.com/adams85/aspnetskeleton/blob/3815ac31a653c40ae7870c725c911e7d168f0127/source/Web/UI/Infrastructure/Models/DynamicModelMetadataProvider.cs#L38)).

So please reconsider removing them from the public interface. It'd be ok to make them protected since a wrapper class still could be created in that case. At least provide some overloads for the suggested replacement methods (GetAttributesForType, GetAttributesForProperty) accepting these supplementary attributes.

#### Version of `Microsoft.AspNetCore.Mvc`: 2.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @adams85.
@pranavkm, @kichalla what would be the alternative approach to what @adams85 is trying to do?

**Comment by pranavkm** [comment]
@dougbu thoughts on this?

**Comment by dougbu** [comment]
@adams85 I recommend focusing on adding the validators you want, not on updating the base attribute collection. For example [`DataAnnotationsMetadataProvider.CreateValidationMetadata(...)`](https://github.com/aspnet/Mvc/blob/edf4e8fd9e238409f77c34ebd66d8ed8be332962/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/DataAnnotationsMetadataProvider.cs#L313-L339) copies attributes from `ModelAttributes` (the `context.Attributes` property) into the `context.ValidationMetadata.ValidatorMetadata` collection. Your `IValidationMetadataProvider` implementation could do something similar but use `_modelAttributesProvider.GetTypeAttributes(...)` as the source.

**Comment by adams85** [comment]
Hi guys! Thanks for the fast reply!

@dougbu Browsing the code it seems your suggestion would work for validation attributes. However, I configure **all the model attributes run-time** (DisplayAttribute, etc.) (It's my bad since in my original post I wrote about validation attributes only.)

Anyway, I've looked into the DataAnnotationsMetadataProvider class but inheriting that won't solve my problem. I could do something like this:

```
    public class DynamicDataAnnotationsMetadataProvider : DataAnnotationsMetadataProvider, IMetadataDetailsProvider, IBindingMetadataProvider, IDisplayMetadataProvider, IValidationMetadataProvider
    {
        readonly IDynamicModelAttributesProvider _modelAttributesProvider;

        public DynamicDataAnnotationsMetadataProvider(IOptions<MvcDataAnnotationsLocalizationOptions> options, IStringLocalizerFactory stringLocalizerFactory, IDynamicModelAttributesProvider modelAttributesProvider) : 
            base(options, stringLocalizerFactory)
        {
            _modelAttributesProvider = modelAttributesProvider;
        }

        void IDisplayMetadataProvider.CreateDisplayMetadata(DisplayMetadataProviderContext context)
        {
                   void IDisplayMetadataProvider.CreateDisplayMetadata(DisplayMetadataProviderContext context)
        {
            // A) context.Attributes property is read-only --> won't work
            // context.Attributes = context.Attributes.Concat(...);

            // B) context.Attributes is IReadOnlyList --> won't work
            // context.Attributes.Add(...);

            // C) context.TypeAttributes, context.PropertyAttributes: the same as above

            // D) DisplayMetadataProviderContext ctor takes ModelAttributes as well ---> obsolete ctors
            // context = new DisplayMetadataProviderContext(context.Key, new ModelAttributes(...));

            // ???

            base.CreateDisplayMetadata(context);
        }        

        // ...
    }
```

So I see no solution in the case of display attributes. Moreover, this path would be much more complicated than just simply add the dynamic attributes to the base attribute collection as I've done it so far.

**Comment by dougbu** [comment]
@adams85 why did you choose to inherit from `DataAnnotationsMetadataProvider` instead of doing something similar -- updating `context.ValidationMetadata.ValidatorMetadata` based on your `IValidationMetadataProvider`?

The `DisplayMetadata` case is somewhat different because your `IDisplayMetadataProvider` would need to set individual properties and not just add `ValidationAttribute`s to a collection. That is, change the metadata directly instead of adding attributes for the built-in `IMetadataDetailsProvider` implementations to handle.

**Comment by dougbu** [comment]
@mkArtakMSFT @danroth27 @rynowak  the `ModelAttributes` constructors are not currently intended to be used directly. (The only reason the non-`[Obsolete]` constructor is not `private` is for use in tests.) Instead, MVC calls the `static` methods on the type and those methods always reflect over actual types, properties and parameters. And, I believe we would always recommend updating `BindingMetadata`, `DisplayMetadata` and `ValidationMetadata` over messing with the reflected attributes.

That said, we _could_ make the main constructor `public` and point users toward replacing `DefaultModelMetadataProvider` with a subclass that overrides `CreatePropertyDetails(...)`, `CreateTypeDetails(...)` and `CreateParameterDetails(...)`.

Thoughts?

**Comment by adams85** [comment]
@dougbu I chose to inherit from DataAnnotationsMetadataProvider to reuse code: CreateDisplayMetadata function is ~250 lines of code and I'd not like to copy them if I don't have to.

**Comment by adams85** [comment]
As a matter of fact, I setup the model binding in run-time (via a fluent API - for architectural reasons) instead of build-time. Apart from this, these "dynamic" model attributes belongs to model types and its properties just like as they were applied as regular attributes in code.

So I don't think it'd be some kind of evil to add them to the reflected ModelAttributes. I still think this is the cleanest way (which not involves copying a lot of framework code).

**Comment by dougbu** [comment]
@adams85 there's no reason to copy any framework code. The `IMetadataDetailsProvider` implementations are registered (in `MvcOptions`) as a collection. While it's possible to replace `MvcOptions.ModelMetadataDetailsProviders` entries, _adding_ providers is the supported and recommended way to affect the final `ModelMetadata`. MVC for example uses that mechanism to add the `DataAnnotationsMetadataProvider` and other `IMetadataDetailsProvider` implementations.

**Comment by dougbu** [comment]
@adams85 to reiterate: What you are trying to do is change the `ModelMetadata` of parameters, properties and types. To do that, set `BindingMetadata`, `DisplayMetadata` and `ValidationMetadata` values in additional `IMetadataDetailsProvider` implementations.

**Comment by adams85** [comment]
@dougbu: I'm afraid there's still some misunderstooding so I put together a code sample that shows clearly what happens when I create my own `IMetadataDetailsProvider` implementation:

```
    // Interface of my dynamic data annotations provider 
    public interface IDynamicModelAttributesProvider
    {
        Attribute[] GetTypeAttributes(Type containerType);
        Attribute[] GetPropertyAttributes(Type containerType, string propertyName);
    }

    // The suggested IMetadataDetailsProvider implementation
    public class DynamicMetadataProvider : IMetadataDetailsProvider, IBindingMetadataProvider, IDisplayMetadataProvider, IValidationMetadataProvider
    {
        readonly IDynamicModelAttributesProvider _dynamicAttributesProvider;

        public DynamicMetadataProvider(IDynamicModelAttributesProvider modelAttributesProvider)
        {
            _dynamicAttributesProvider = modelAttributesProvider;
        }

        IEnumerable<Attribute> GetDynamicAttributes(ModelMetadataIdentity key)
        {
            switch (key.MetadataKind)
            {
                case ModelMetadataKind.Type:
                    return _dynamicAttributesProvider.GetTypeAttributes(key.ModelType);
                case ModelMetadataKind.Property:
                    return _dynamicAttributesProvider.GetPropertyAttributes(key.ContainerType, key.Name);
                default:
                    return Enumerable.Empty<Attribute>();
            }
        }

        public void CreateBindingMetadata(BindingMetadataProviderContext context)
        {
            var attributes = GetDynamicAttributes(context.Key);

            // COPIED from DataAnnotationsMetadataProvider.CreateBindingMetadata()
            var editableAttribute = context.Attributes.OfType<EditableAttribute>().FirstOrDefault();
            if (editableAttribute != null)
            {
                context.BindingMetadata.IsReadOnly = !editableAttribute.AllowEdit;
            }
        }

        public void CreateValidationMetadata(ValidationMetadataProviderContext context)
        {
            var attributes = GetDynamicAttributes(context.Key);

            // COPIED from DataAnnotationsMetadataProvider.CreateValidationMetadata()
            foreach (var attribute in context.Attributes.OfType<ValidationAttribute>())
            {
                // If another provider has already added this attribute, do not repeat it.
                // This will prevent attributes like RemoteAttribute (which implement ValidationAttribute and
                // IClientModelValidator) to be added to the ValidationMetadata twice.
                // This is to ensure we do not end up with duplication validation rules on the client side.
                if (!context.ValidationMetadata.ValidatorMetadata.Contains(attribute))
                {
                    context.ValidationMetadata.ValidatorMetadata.Add(attribute);
                }
            }
        }

        public void CreateDisplayMetadata(DisplayMetadataProviderContext context)
        {
            var attributes = GetDynamicAttributes(context.Key);

            // Now what???
            // It seems I must COPY here that 250 lines from DataAnnotationsMetadataProvider.CreateDisplayMetadata()...
        }
    }
```

Do you see now that if I do what you suggest, I must copy almost the full DataAnnotationsMetadataProvider class instead of reusing that code? It's no wonder: in my project I supply only the ordinary data annotation attributes. Just not in build-time but run-time.

So my problem actually can be reduced to the following: **how can I reuse the code of  DataAnnotationsMetadataProvider?** As BindingMetadataProviderContext, DisplayMetadataProviderContext, etc. classes cannot be modified it seems that the only way is what I have done.

**Comment by dougbu** [comment]
@adams85 why does `IDynamicModelAttributesProvider` exist at all? Instead of using "dynamic" attributes, directly make the metadata changes needed.

**Comment by adams85** [comment]
@dougbu  why does IDynamicModelAttributesProvider exist at all? 
I mentioned it already. To be able to apply data annotations to types and its properties in run-time instead of design-time. To be able to do something like this:

```
 builder.Model<ChangePasswordModel>().Property(m => m.CurrentPassword)
                    .Apply(new DisplayAttribute() { Name = T["Current password"] })
                    .Apply(new RequiredAttribute().Localize())
                    .Apply(new DataTypeAttribute(DataType.Password));

                builder.Model<ChangePasswordModel>().Property(m => m.NewPassword)
                    .Apply(new DisplayAttribute() { Name = T["New password"] })
                    .Apply(new RequiredAttribute().Localize())
                    .Apply(new DataTypeAttribute(DataType.Password))
                    .Apply(new StringLengthAttribute(100) { MinimumLength = 6, ErrorMessage = T["The {0} must be at least {2} characters long."] });

                builder.Model<ChangePasswordModel>().Property(m => m.ConfirmPassword)
                    .Apply(new DisplayAttribute() { Name = T["Confirm password"] })
                    .Apply(new DataTypeAttribute(DataType.Password))
                    .Apply(new CompareAttribute(nameof(NewPassword)) { ErrorMessage = T["The password and confirmation password must match."] });
```

I'll gladly explain you in private why I need this but I don't think this should be discussed here as it's way off the subject.

So what if you remove obsolete from those ctors (or make them protected)? It's worked so far, they did no harm to anyone. You wouldn't introduce a breaking change, I would be happy and we could close this issue. :D

**Comment by dougbu** [comment]
@adams85 there already is a way to dynamically change the `ModelMetadata`. And, it can be done fluently e.g. https://github.com/aspnet/Mvc/blob/58aa16ee696a00fb40d91a4011c2c5f890ea983d/test/Microsoft.AspNetCore.Mvc.Core.TestCommon/TestModelMetadataProvider.cs#L99-L106 and https://github.com/aspnet/Mvc/blob/58aa16ee696a00fb40d91a4011c2c5f890ea983d/test/Microsoft.AspNetCore.Mvc.Core.TestCommon/TestModelMetadataProvider.cs#L99-L106 to change `BindingMetadata` for a `Type`. It isn't clear we need a second mechanism to change `ModelMetadata`.

To continue that example, our tests would use
``` c#
var provider = new TestModelMetadataProvider();
provider
    .ForProperty<ChangePasswordModel>(nameof(ChangePasswordModel.CurrentPassword))
    .DisplayDetails(dd => dd.DisplayName = () => "Current password");
```
to reach the same end as
``` c#
builder
    .Model<ChangePasswordModel>()
    .Property(m => m.CurrentPassword)
    .Apply(new DisplayAttribute() { Name = T["Current password"] });
```
Your expression-based approach would also work fine.

Why are you focused on adding data annotation attributes instead of changing the various details directly?

**Comment by adams85** [comment]
@dougbu Alright, this may work for me at first glance. It'll take some time to refactor my projects but let it be if you propose this solution.

I'll rewrite some of my code to see if my solution can be completely replaced to yours without any gotchas. I'll get back to you soon, and hopefully we can close this issue.

Until then, thank you for your help!
