### ISSUE TITLE
ServiceFilterAttribute UnhandledException

### ISSUE THREAD

**Issue by steveoh** [aspnet/Mvc#7934]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
```cs
public void ConfigureServices(IServiceCollection services)
{
  // ...
  services.AddScoped<TestServiceFilter>();
}

    public class TestServiceFilter
    {
        private readonly RequestDelegate _next;

        public TestServiceFilter(RequestDelegate next)
        {
            _next = next;
        }

        public Task Invoke(HttpContext httpContext)
        {

            return _next(httpContext);
        }
    }

   [ServiceFilter(typeof(TestServiceFilter))]
    public class TestController : Controller
    {
        [HttpGet]
         public IActionResult Index() {
             return Json("ok");
     	 }
     }
```

#### Description of the problem:
Adding a middleware filter using the ServiceFilterAttribute throws 

```
InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.RequestDelegate' while attempting to activate 'Middleware.TestServiceFilter'.
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

`.App` = `2.1.0`

this may belong in [DI](https://github.com/aspnet/DependencyInjection) but I'm not sure?

**Comment by pranavkm** [comment]
Did you mean to write a [middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-2.1#imiddleware)?

**Comment by steveoh** [comment]
@pranavkm, I wrote a middleware and then "used" it. That applied it globally, but I only wanted it applied to a specific controller or routes. I thought the MiddlewareFilter or ServiceFilter this was the way to accomplish that but I must be confused.

**Comment by pranavkm** [comment]
You have to let Mvc know of the middleware pipeline to use it. See the docs here - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1#using-middleware-in-the-filter-pipeline. Something along the lines of:

```C#
public class TestServicePipeline  
{
    public void Configure(IApplicationBuilder applicationBuilder) 
    {
        applicationBuilder.UseMiddleware<TestServiceMiddleware>();
    }
}

[MiddlewareFilter(typeof(TestServicePipeline))]
public IActionResult Index() { }
```

**Comment by steveoh** [comment]
@pranavkm I updated my last comment. See the DI requirement.

**Comment by steveoh** [comment]
Ok, I switched this to an `IAsyncResourceFilter` as I believe that is the more corrector option.
