### ISSUE TITLE
In 2.0 ObjectResult.DeclaredType masked Task. In 2.1 it does not.

### ISSUE THREAD

**Issue by brockallen** [aspnet/Mvc#7937]
When upgrading my API projects from 2.0 to 2.1 I had many of my integration tests start to fail.

As part of my API infrastructure, I have an IActionFilter and in OnActionExecuted the ActionExecutedContext's Result is being checked for types of ObjectResult. 

In 2.0, for action methods that return `Task<Foo>` the ObjectResult's DeclaredType was `typeof(Foo)`, but in 2.1 the ObjectResult's DeclaredType is now `typeof(Task<Foo>)`. While more accurate, it's a breaking behavior change as existing code was relying upon the masking of the Task as part of the return type.

I don't really know what is to be done with this issue. I did update my action filters to now handle the DeclaredType that are `Task<Foo>`, but this is technically a breaking change from 2.0 to 2.1. Breaking changes are a PITA.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/7782. We are addressing this in the upcoming 2.1.1 release. https://github.com/aspnet/Mvc/issues/7782#issuecomment-389300695 has a possible workaround. Alternatively, the 2.1.1 bits with the fix are nearly ready and you could give it a try:

* https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1
* MyGet feed with packages: https://dotnet.myget.org/f/dotnet-core/api/v3/index.json
