### ISSUE TITLE
Add few razor pages to the Routing functional test website

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#7940]
Since we are going to use Routing website to run both regular & dispatcher based tests, it would be good, maybe, couple of razor pages and add functional tests which cover request matching & url generation (from pages-to-pages, pages-to-mvc, mvc-to-pages etc.) This can give us a minimal E2E experience.

cc @JamesNK

**Comment by ajaybhargavb** [comment]
4d98ea801e0b9650142679bc4017e947e6701d97
