### ISSUE TITLE
[Feature request] ModelState ErrorObjectProvider

### ISSUE THREAD

**Issue by ZBAGI** [aspnet/Mvc#7945]
According to [Microsoft REST API Guidelines](https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses) error DTO should not only contains target and error message but also unique code of error and preferebly validation parameters (for example: `"minLength": "6", "maxLength": "64",` ). That gives front-end more flexibility. ModelState as is today does not allow you to create anything like it. It only let you see target and already composed message. Without ugly regex hack there is no way to separate data from message.

It would be helpful to introduce some sort of `ErrorObjectProvider` and `ErrorObject`. Basically `ErrorObjectProvider` would be feed with the attribute that failed and returned `ErrorObject`. Then list of `ErrorObject's` would be provided alongside `ModelStateDictionary`.

**Comment by ZBAGI** [comment]
Either i don't understand you or do not understood me. There is no direct reference in ModelState to model that failed validation itself. All you get is `ModelStateDictionary` with model name and message. Yes you could loop ActionContext parameters to find out model based on model name, but it's as ugly as regexing error message.

> In a form of data-val-<validation_name>-<param_name>="<value>".

What do you mean ? That looks like some sort of view parameter (html ?) I referring .net core **API**. There is no need for error DTO in other then type of projects.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ZBAGI.
@glennc, @danroth27 what do you think regarding this one?

**Comment by danroth27** [comment]
This sounds like a reasonable scenario. This will require some design work to figure out a reasonable way to provide the validation parameters. @rynowak may have some more thoughts on this.

**Comment by rynowak** [comment]
This is already something we're planning to do, I'm not sure where it's tracked. @pranavkm -?

**Comment by pranavkm** [comment]
https://github.com/aspnet/Mvc/issues/6560 would be the tracking issue.

**Comment by mkArtakMSFT** [comment]
Closing this issue as a dupe with the one @pranavkm has referenced - #6560
