### ISSUE TITLE
Microsoft.AspNetCore.App 2.1.1 application run problem

### ISSUE THREAD

**Issue by proggmatic** [aspnet/Mvc#7946]
#### Is this a Bug or Feature request?:
???

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
1. create new mvc app via "dotnet new mvc"
2. update "Microsoft.AspNetCore.App" package to "2.1.1"
3. dotnet run

#### Description of the problem:
I have updated Microsoft.AspNetCore.App to version 2.1.1
then i got error in console

The specified framework 'Microsoft.AspNetCore.App', version '2.1.1' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.0 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

I didn't find any updates of sdk or runtime on https://aka.ms/dotnet-download

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @proggmatic.
The issue you're facing here is tracked at https://github.com/aspnet/Home/issues/3241.
Closing this issue as a duplicate.
