### ISSUE TITLE
Remove the Json method from Controller

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/Mvc#7948]
The `Json` method in [`Controller`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Controller.cs) is redundant because JSON can already be returned using the `Ok` method.

Perhaps the `Json` method could be removed from the `Controller` class and the [`JsonResult`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonResult.cs) class could be removed.

**Comment by pranavkm** [comment]
There are [overloads](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controller.json?view=aspnetcore-2.1#Microsoft_AspNetCore_Mvc_Controller_Json_System_Object_Newtonsoft_Json_JsonSerializerSettings_) for the `Json` helper methods that don't have an `ObjectResult` equivalent. Additionally, it's a breaking change to remove types or APIs, and there aren't any compelling reasons to remove this type or helper method.

**Comment by khellang** [comment]
Also, they're not functionally equivalent. `Ok` involves conneg, `Json` hard codes the response to `application/json`.
