### ISSUE TITLE
[Feature request] Make routes configurable through DI

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [aspnet/Mvc#7953]
When plugging in external class libraries to Mvc, it would be nice to call their `serviceCollection.AddPluggableStuff()` and have them add routes.

To require library consumers to use the callback syntax of `AddMvc()`, and then call something like `routes.AddPluggableStuffRoutes()` feels very redundant.

So, in my `AddPluggableStuff` (I'm the one making the external class library), I could ideally do something like:

            serviceCollection.Configure<MvcRouteOptions>(opts =>
                opts.Routes.MapRoute(
                "PoetryPortal",
                "Admin",
                new { controller = "PoetryPortal", action = "Index" });
            );

I don't think this is possible using todays code base?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @bjorn-ali-goransson.
@kichalla, @JamesNK - is this something Dispatcher work will cover? If so, please either close as a dupe or move this to the `aspnet/routing` repo.

**Comment by kichalla** [comment]
> @kichalla, @JamesNK - is this something Dispatcher work will cover? If so, please either close as a dupe or move this to the aspnet/routing repo.

At the moment these routes cannot be configured through DI in MVC part of Dispatcher work. I will move this issue to Routing repo.

**Comment by kichalla** [comment]
This issue was moved to aspnet/Routing#575

**Comment by bjorn-ali-goransson** [comment]
Thanks @mkArtakMSFT , didn't think of the fact that Routing had its own repo and thus also its own issue tracker. Cheers
