### ISSUE TITLE
Testhost process exited with error: It was not possible to find any compatible framework version The specified framework 'Microsoft.NETCore.App', version '2.2.0-preview1-26618-02' was not found.

### ISSUE THREAD

**Issue by kishanAnem** [aspnet/Mvc#7954]
I think this is definitely this is not  bug.

I've installed this runtime 3.0.0-preview1-26621-01 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]. But still vs looking for 2.2.0-preview1-26618-02'.

Please help me how to fix this. or provide a link to install  this version 2.2.0-preview1-26618-02 

[21-06-2018 23:03:33 Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.2.0-preview1-26618-02' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.0-preview1-001100-00 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.0-preview1-26216-03 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.0-preview1-26527-01 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.0-preview1-26609-01 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.0-preview1-26609-02 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.0.0-preview1-26621-01 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by pranavkm** [comment]
Here's some details on how the roll forward semantics work - https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/roll-forward-on-no-candidate-fx.md#default-behavior. You need a compatible preview version for this to work. In addition, we generally do not recommend using pre-release versions in production applications.
