### ISSUE TITLE
Combining InvalidModelStateResponseFactory with ReturnHttpNotAcceptable

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#7964]
#### Is this a Bug or Feature request?: 

Possibly a Bug, Probably me Not Understanding

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

There is a fully working code sample at https://github.com/Dotnet-Boxed/Templates/tree/problem-details/Source/Content/ApiTemplate . Here is a summary of the code at play:

I'm trying to get `InvalidModelStateResponseFactory` working nicely with Swagger, `ReturnHttpNotAcceptable = true` and custom media types:

```csharp
services.AddMvcOptions(
    options =>
    {
        var jsonInputFormatterMediaTypes = options
            .InputFormatters
            .OfType<JsonInputFormatter>()
            .First()
            .SupportedMediaTypes;
        var jsonOutputFormatterMediaTypes = options
            .OutputFormatters
            .OfType<JsonOutputFormatter>()
            .First()
            .SupportedMediaTypes;
        jsonInputFormatterMediaTypes.Insert(0, "application/vnd.restful+json");
        jsonOutputFormatterMediaTypes.Insert(0, "application/vnd.restful+json");
        jsonOutputFormatterMediaTypes.Add("application/problem+json");

        options.ReturnHttpNotAcceptable = true;
});
services.Configure<ApiBehaviorOptions>(options =>
    {
        options.InvalidModelStateResponseFactory = context =>
        {
            var problemDetails = new ValidationProblemDetails(context.ModelState)
            {
                Type = "https://asp.net/core",
                Title = $"{context.ModelState.ErrorCount} validation errors occurred.",
                Status = StatusCodes.Status400BadRequest,
                Detail = "Please refer to the errors property for additional details.",
                Instance = context.HttpContext.Request.Path
            };

          return new BadRequestObjectResult(problemDetails)
          {
            ContentTypes = { "application/problem+json", "application/problem+xml" }
          };
        };
      });

[Route("[controller]")]
[ApiController]
public class CarController : ControllerBase
{
        [HttpPost("", Name = "PostCar")]
        [ProducesResponseType(typeof(Car), StatusCodes.Status201Created)]
        [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
        public Task<IActionResult> Post(
            [FromBody] SaveCar car,
            CancellationToken cancellationToken)
}
```

#### Description of the problem:

I keep getting 406 Not Acceptable responses when attempting to return a problem details response. Setting `ReturnHttpNotAcceptable` to `false` fixes the problem but I'd like to enable both. Swagger is sending an `Accept` HTTP header with a value of `application/json`, so in theory, everything should just work right?

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

2.1.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @RehanSaeed.
@kichalla, can you please look into this? Thanks!

**Comment by kichalla** [comment]
@RehanSaeed In your `InvalidModelStateResponseFactory`, you are explicitly setting the content types to be used for that response and since the client asked(with an Accept header of `application\json`) a response with a specific content-type, a 406 is returned. Why explicitly set the ContentTypes here? 

```c#
return new BadRequestObjectResult(problemDetails)
          {
            ContentTypes = { "application/problem+json", "application/problem+xml" }
          };
```

**Comment by RehanSaeed** [comment]
@kichalla Ok, I understand that but returning a `Content-Type` HTTP header containing `application/problem+json` is valid and even more 'correct' in this case. When the requests `Accept` HTTP header is set to `application/json`, `application/problem+json` is valid because it is a subtype of `application/json`.

Perhaps the real problem here is that `ReturnHttpNotAcceptable` does not take subtypes into consideration.

**Comment by kichalla** [comment]
That's a good point. I will investigate further and update this thread.

**Comment by kichalla** [comment]
Thanks for reporting @RehanSaeed, I have added a new issue for this case https://github.com/aspnet/Mvc/issues/7964 and closing this in favor of it.
