### ISSUE TITLE
[Feature request] Composite ValidationAttribute

### ISSUE THREAD

**Issue by ZBAGI** [aspnet/Mvc#7965]
In typical validation scenario usually there are more then one condition. For example in case of validating Name we may want to validate length and characters used. To do so we would need to add two `ValidationAttribute` . Like so:
```
     [StringLength(20), RegularExpression(@"^[a-zA-Z]$")] public string Name { get; set; };
```
Now, If we would like to reuse that rule in other names (for example. User name, role name, system name and so on...)  we would need to introduce static class with parameters (to centralize rules) and copy/paste all attributes to new place. What if we want to add condition ? Well then we need to update all places where we want to validate it. That is extremely impractical and may lead to mistakes when copy pasting.

Alternative way is to create own `ValidationAttribute` that will contain an instances of `ValidationAttribute`'s, That is way more elegant solution as now we have one attribute that controls all validation conditions. And if we ever would like to change something we would need to change it only in attribute without thinking where it was used. Additionally it looks way cleaner:
```
     [Name] public string Name { get; set; };
```

But then downside of it is that you lose possibility to prompt more then one error. As in current design one `ValidationAttribute` can only represent one validation error. So when your name is too long and contains forbidden characters, you are out of luck. User will be prompt one error at the time.

Please consider `CompositeValidationAttribute` that instead of `IsValid` method would implement `GetValidationAttributes`  which would return `ValidationAttribute` instances. Which then would be applied to model.

**Comment by AlexejTimonin** [comment]
Hi, I know this is a feature request but I've encountered something similar and solved it by implementing my own ValidationAttribute that acts as composite attribute. I've create github repo with an example on how I solved it. If you need to solve this problem in your project maybe you can get some inspiration. 
The project can be found here: [CompositeValidationAttributeExample](https://github.com/AlexejTimonin/CompositeValidationAttribute) (This is an example, make adjustments as needed).
This is how it looks on a model: [Person.cs](https://github.com/AlexejTimonin/CompositeValidationAttribute/blob/master/CompositeValidationAttributeExample/Person.cs)
Attribute implementation: [CompositeValidationAttribute.cs](https://github.com/AlexejTimonin/CompositeValidationAttribute/blob/master/CompositeValidationAttributeExample/CompositeValidationAttribute.cs)
These are validation models: [NameValidation.cs](https://github.com/AlexejTimonin/CompositeValidationAttribute/blob/master/CompositeValidationAttributeExample/NameValidation.cs) and [EmailAddressValidation.cs](https://github.com/AlexejTimonin/CompositeValidationAttribute/blob/master/CompositeValidationAttributeExample/EmailAddressValidation.cs)

**Comment by ZBAGI** [comment]
Thanks @AlexejTimon. That is for sure less ugly and some way acceptable solution. It will do the trick for now until (hopefully) there will be build in solution.

**Comment by ZBAGI** [comment]
In fact, you can simplify your example with abstract class. Thus removing gathering validation attributes via reflection.[ Here is how i would (more or less) i would do it](https://github.com/ZBAGI/CompositeValidationAttribute) (if i could have combined messages).

**Comment by AlexejTimonin** [comment]
@ZBAGI I've made some changes to CompositeValidationAttribute, it now implements IModelValidator interface ([changes](https://github.com/AlexejTimonin/CompositeValidationAttribute/commit/06f0cf98acc65995e5def337fcf18a9067c70e49)) this way you can output several error messages instead of combined error messages. Maybe your regex will work on that. I think I see your problem more clearly now, it would be nice to have something like this out of the box and be able to return json objects in the result array instead of only strings, that way the client can programmatically detect errors.

**Comment by mkArtakMSFT** [comment]
Thanks for helping out with this, @AlexejTimonin.
Would you be interested in submitting a PR to us?
/cc @pranavkm

**Comment by AlexejTimonin** [comment]
I will submitt PR, @mkArtakMSFT

**Comment by pranavkm** [comment]
Merged in https://github.com/aspnet/Mvc/commit/d4beab5d09bb28e970063f7da9fe916b99514c5c

**Comment by pranavkm** [comment]
Closing discussion: A `Microsoft.AspNetCore.Mvc.DataAnnotations.ValidationProviderAttribute` was added to support this feature. Sample usage looks like so:

```C#
public class ValidationProviderAttributeModel
{
    [Name]
    public string FirstName { get; set; }
}

public class NameAttribute : ValidationProviderAttribute
{
    public override IEnumerable<ValidationAttribute> GetValidationAttributes()
    {
        return new List<ValidationAttribute>
        {
            new RequiredAttribute(),
            new RegularExpressionAttribute(pattern: "[A-Za-z]*"),
            new StringLengthAttribute(maximumLength: 5)
        };
    }
}
```

**Comment by veikkoeeva** [comment]
Oh, extremely interesting! In which release, or a rough estimate date, would this be available in a official release?

Cheers @AlexejTimonin and @ZBAGI !

**Comment by pranavkm** [comment]
The feature is part of the 2.2.0-preview1 release. https://github.com/aspnet/Announcements/issues/307 has some rough estimates for when the release is meant to go RTM.
