### ISSUE TITLE
Port "Validation occurs against declared type rather than real type" to 2.1.x

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7968]
Issue: https://github.com/aspnet/Mvc/issues/7952

**Comment by dougbu** [comment]
Stealing this one since we're going with an expansion of #8019

**Comment by dougbu** [comment]
Reassigning because we're taking @pranavkm's fix (#8049)

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/174c5eaa6c8370a4d3c4ba898aee9e7a5904720c
