### ISSUE TITLE
Port #7770 fix to 2.1.2 or 2.1.3

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#7970]
Suggest we port the #7770 fix (49c653e) to the next 2.1 patch. Basically `[ApiController]` causes a regression in some scenarios.

/cc @Eilon @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
Given the super simple workaround customers facing this issue can apply, I don't think this will get approved as a patch candidate. Still, I will try to get this approved in Shiproom.

**Comment by mkArtakMSFT** [comment]
Actually, thinking more about this, this is not even close to the bar for a patch. Closing this.

**Comment by dougbu** [comment]
@mkArtakMSFT we introduced the #7770 regression in a _patch_ (2.1.1). I'm surprised fix for that doesn't meet the bar for a subsequent patch. We shouldn't break scenarios in a patch -- ever.

In addition, the `IFormFileCollection` workaround may be simple but isn't particularly obvious.
