### ISSUE TITLE
code changed in file launchSettings.json not considred on ctlr+f5 

### ISSUE THREAD

**Issue by Rimbik** [aspnet/Mvc#7971]
#### Request:
Please auto save the file 'launchSettings.json ' on F5 or ctlr+f5 

#### Steps to reproduce
1. Change some setting in file:  launchSettings.json for example change the port number
2. Do not press Ctrl + S *normal habit
3. Run the App using ctlr+f5

#### Description of the problem:
Seems the app runs with old setting without considering the new changes in file unlike .cs file
when we change anything in .cs file it does not need explicit save.

**Comment by pranavkm** [comment]
@barrytang should this go through VS feedback?

**Comment by Rimbik** [comment]
yes, please

**Comment by barrytang** [comment]
Yes, please use the [Report a Problem](https://developercommunity.visualstudio.com/) tool.
