### ISSUE TITLE
Port DefaultAssemblyPartDiscoveryProvider throws KeyNotFoundException if a library does not have runtime components to 1.1

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#7983]
Original issue: https://github.com/aspnet/Mvc/issues/5690

Further reading: https://github.com/aspnet/Home/issues/3132

**Comment by mkArtakMSFT** [comment]
Holding on to this for as an SDK fix will probably cover this.

**Comment by pranavkm** [comment]
SDK PR tracking the fix - https://github.com/dotnet/sdk/pull/2382

**Comment by pranavkm** [comment]
Verified that the issue reported in https://github.com/aspnet/Home/issues/3132 is addressed as part of Sdk version 2.1.401. We can avoid taking a patch fix for this for now.

**Comment by pranavkm** [comment]
Unfortunately the fix doesn't cover other (legitimate) scenarios - https://github.com/aspnet/Home/issues/3435. Reopening to see if there's interest in patching this.

**Comment by mkArtakMSFT** [comment]
Closing this as this doesn't meet the bar as well as there are workarounds available.
