### ISSUE TITLE
ModelState.IsValid = true when the maximum number of errors is exceeded.

### ISSUE THREAD

**Issue by benjcallaghan** [aspnet/Mvc#7992]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

1. Create a new ASP.NET Core 2.1 Web API project.
1. Create a complex model with at least one validation rule (e.g. [Required]).
1. Create a POST method on an [ApiController] that takes a List<T> of that model.
1. Run the application and POST 500 objects to that method, with each object having a validation error.
1. In the debugger,  and see the following results:
  - The controller action is executed (i.e. the request was not short-circuited by the automatic HTTP 400 response)
  - ModelState.ErrorCount = 200 (default max errors allowed)
  - ModelState.HasReachedMaxErrors = true
  - ModelState.IsValid = true

#### Description of the problem:

I am working on a project where large amounts (over one thousand) of objects are being POST'd to an API Controller in ASP.NET Core 2.1. It is possible for each of these objects to have a validation error. In this scenario, the maximum number of errors is reached, and HasReachedMaxErrors is set to true. However, the automatic 400 response is bypassed, and my code reads ModelState.IsValid = true. The validation errors are visible inside of the ModelState, with most of those errors listed as "Skipped". The relevant line of code is

```
public bool IsValid
{
    get
    {
        return ValidationState == ModelValidationState.Valid || ValidationState == ModelValidationState.Skipped;
    }
}
```

I understand that having a maximum number of errors is a performance benefit, but reaching that limit should imply that the request is definitely wrong. Instead, validation is skipped, and the request is deemed valid.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

`Microsoft.AspNetCore.App` 2.1.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @benjcallaghan.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
@benjcallaghan checking `IsValid` after exceeding `MaxAllowedErrors`, I can't duplicate this issue. I suspect there's some detail of your scenario that leads to the behaviour you described.

In order for us to investigate this issue further, could you please provide a minimal repro project that illustrates the problem, preferably hosted in a GitHub repo?

**Comment by benjcallaghan** [comment]
I have created a minimal repro project here: https://github.com/benjcallaghan/TestModelErrors

This project has a test server and client. The server exposes two nearly identical routes. One includes a CancellationToken as a parameter, the other does not. The client builds up 1000 objects, each with a single validation error, and sends that batch to each endpoint. The maximum number of errors was left at the default 200.

I discovered that the presence of the CancellationToken parameter altered the behavior of the ModelState. The method with the token produces the results I originally reported. The method without the token produces the correct result of HTTP 400 with the error messages in the body. Removing the CancellationToken from the original project also fixed the behavior there.

```
    // IsValid = true with 200 errors
    [HttpPost("withToken")]
    public IActionResult PostWithToken(TransactionCollection request, CancellationToken token) {
      return Ok(new { IsValid = ModelState.IsValid, MaxErrorsReached = ModelState.HasReachedMaxErrors, Errors = ModelState.ErrorCount });
    }

    // IsValid = false with 200 errors
    [HttpPost("noToken")]
    public IActionResult PostWithoutToken(TransactionCollection request) {
      return Ok(new { IsValid = ModelState.IsValid, MaxErrorsReached = ModelState.HasReachedMaxErrors, Errors = ModelState.ErrorCount });
    }
```

**Comment by dougbu** [comment]
@benjcallaghan thanks again for this report. The problem here is `CancellationTokenModelBinder` suppresses validation for the `CancellationToken` parameter and the root `ModelStateDictionary` node. This _unconditionally_ overwrites the `Invalid` state of the root node.

## Workaround
Reverse the order of the action parameters (putting the `CancellationToken` parameter first) and you'll get the expected behaviour.

**Comment by dougbu** [comment]
@mkArtakMSFT @danroth27 we should fix this issue.

FYI on second glance, the problem is here https://github.com/aspnet/Mvc/blob/a6987cc1cde88663e16430db9b4ebc1372b2c4f9/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidationVisitor.cs#L196-L200

That will suppress validation for the entire `ModelStateDictionary` if `HasReachedMaxErrors` is already true when validating a parameter with an empty prefix (like a `CancellationToken` but not limited to that case).

The root cause is the code passes `string.Empty` into `SuppressValidation(...)`. Only `null` is special cased (to no-op) in that method. Looks like we fixed a problem with values not expected in the `ModelStateDictionary` in some, but not all, code paths.

**Comment by mkArtakMSFT** [comment]
@dougbu, is there a workaround available? I'm thinking about taking this into a patch for 2.1 too.

**Comment by dougbu** [comment]
@mkArtakMSFT this is now my most urgent concern, correct?

**Comment by dougbu** [comment]
@benjcallaghan please open a separate issue about XML formatting. That does not appear related and may occur whenever the response is an `IDictionary<string, string>` that contains an empty key. Problem may also be specific to the XML serializer you're using.

**Comment by mkArtakMSFT** [comment]
https://github.com/aspnet/Mvc/issues/8055

**Comment by dougbu** [comment]
f2608c2ff4
