### ISSUE TITLE
System.UriFormatException : Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by nulltoken** [aspnet/Mvc#7997]
Hello,

It's possible I may have found a bug (or at the very least a surprising behavior :wink: ).

Running an integration test, using the TestServer, against an Mvc backed API (monitored by ApplicationInsights), throws a `UriFormatException`.

It looks like (cf. the screenshots below) that the host being parsed end up being `"localhost,localhost"`.

I've managed to trim down the code as much as possible into a repro case available at https://github.com/nulltoken/UriFormatException

Beware, that looks pretty random. The repro case breaks most of time with one failing test, and from time to time two tests fail.

FWIW, removing this **[line](https://github.com/nulltoken/UriFormatException/blob/master/test/Tests/Repro.cs#L15-L16)** from the repro case makes the problem disappear.

Versions:
- .Net Core 2.1.1
- ApplicationInsightsAspNetCore 2.4-beta1

![hostingapplication](https://user-images.githubusercontent.com/92363/42164098-2f079508-7e05-11e8-98f3-1c763618ea3c.jpg)

![uriext](https://user-images.githubusercontent.com/92363/42164112-39c5463e-7e05-11e8-9055-259fbc283999.jpg)

**Comment by nulltoken** [comment]
FWIW this was working against .NET Core 2.0.5

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Hosting#1481
