### ISSUE TITLE
Typo in Microsoft.AspNetCore.Mvc.Testing.targets

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/Mvc#7998]
#### Is this a Bug or Feature request?:
Typo

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
See target 'CopyAditionalFiles' in https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Testing/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Testing.targets

#### Description of the problem:
It should be named 'CopyAdditionalFiles', I do not know if that target is included anywhere with that specific name and/or with a properly written name.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Master on Git

**Comment by pranavkm** [comment]
cc @javiercn

**Comment by javiercn** [comment]
Thanks for contacting us.

This is indeed a typo. However it doesn't functionally affect any part of the product so we don't consider very valuable to fix it.

Closing this issue as we won't be taking any further actions.
