### ISSUE TITLE
Setting Default Page to razor Login in MVC application

### ISSUE THREAD

**Issue by traceyjas** [aspnet/Mvc#8001]
#### Description of the problem:
I want the default page in the application to be the Identity/Account/Login Page. This is a MVC application and that is a razor page. How can this be achieved?

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.All

**Comment by AlexejTimonin** [comment]
Add the following to your `ConfigureServices` method in `Startup.cs`

            services
                .AddMvc()
                .AddRazorPagesOptions(options =>
                {
                    options.Conventions.AddPageRoute(pageName: "/Identity/Account/Login", route: "");
                })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

**Comment by traceyjas** [comment]
Thanks. This did not work however

**Comment by AlexejTimonin** [comment]
Alright, if you're talking about the login page that ships with MVC template, then the configuration should look like this:

ConfigureServices method:

            services
                .AddMvc()
                .AddRazorPagesOptions(options =>
                {
                    options.Conventions.AddAreaPageRoute(
                        areaName: "Identity",
                        pageName: "/Account/Login",
                        route: "");
                })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

Configure method:

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action}/{id?}");
            });

I've uploaded working example [here](https://github.com/AlexejTimonin/LoginAsIndexInMvc)

Maybe there is more elegant way of doing this?

**Comment by traceyjas** [comment]
Thank you. It worked. ;)
