### ISSUE TITLE
Return razor page without redirect

### ISSUE THREAD

**Issue by Msender** [aspnet/Mvc#8002]
#### Is this a Bug or Feature request?:
Feature request

#### Description of the problem:
Add overload to PageModel.Page Method that should accept a page name and return that page without a redirect, the same as we have with the Controller.View method.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.Mvc

**Comment by pranavkm** [comment]
> that should accept a page name and return that page without a redirect

The architecture of Razor Pages isn't designed to support the kind of thing you're suggesting. Think of each page as a controller action - by the time you get to it, authorization, model binding etc for the current page have already executed and cannot be re-executed for the other page. If all you need is the render the other page as a "view", consider returning a [partial](https://github.com/aspnet/Mvc/issues/7885) from the page or refactor the cshtml to use partials to render the view you care about.

**Comment by Msender** [comment]
OK, Thanks

**Comment by rpokrovskij** [comment]
But how error page is shown then (when razor page code fails)? There are no redirect - so there is a way to switch to new pageModel without redirect.
