### ISSUE TITLE
Make ControllerBase.User virtual so it can be mocked 

### ISSUE THREAD

**Issue by SimonCropp** [aspnet/Mvc#8003]
Make `ControllerBase.User` virtual so it can be mocked for testing purposes

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs#L195

Seems most other members are virtual, so it would seem reasonable.

**Comment by pranavkm** [comment]
Making a member `virtual` is a breaking change (see https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#members). There isn't a strong enough case to justify this change. I'd recommend setting the `User` instance on the mocked `HttpContext` instance.

**Comment by SimonCropp** [comment]
workaround for the next person

```
var controller = new MyController()
{
    ControllerContext = new ControllerContext
    {
        HttpContext = new DefaultHttpContext
        {
            User = new ClaimsPrincipal()
        }
    }
};
```

not that this is not really a viable long term solution, since it requires knowledge of the internal workings of ControllerBase to know it is even possible

**Comment by SimonCropp** [comment]
@pranavkm breaking change is not enough of a reason to close an issue. it just means it should be scheduled for the next major.

>I'd recommend setting the User instance on the mocked HttpContext instance. 

that is not the solution either. see my above workaround. 

is there doco on how to achieve the above

**Comment by SimonCropp** [comment]
bump

**Comment by pranavkm** [comment]
I guess setting it up the way you did is the way to go. Feel free to add it here - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.1#unit-testing - to document it. I've added this issue as a line item to a larger tracking issue of things to do in 3.0 - https://github.com/aspnet/Mvc/issues/7820.
