### ISSUE TITLE
Access RoutingTable/RoutingData in middleware

### ISSUE THREAD

**Issue by RoarkeRandall** [aspnet/Mvc#8008]
#### Is this a Bug or Feature request?:
Feature Request

#### Description of the problem:

I'd like to write a middleware that logs the routing path and the status code of the response...
so if we have  a controller:

```
[Route("api/v1/[controller]")]
public class FooController : BaseController
{
      HttpGet("{id}")]
      public IActionResult Get(int id) 
...
}
```

I'd like to be able to log `api/v1/foo/{id}` resulted in a `500`, or something along those lines. I can get close to this with RouteData, but that isn't available in middleware. Is there a routing table available that I could match the request path on?

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @RoarkeRandall.
This is actually something the Dispatcher work we do in aspnet/Routing repo will solve.
Here is an issue we have tracking the high level work: https://github.com/aspnet/Routing/issues/523
Closing this as a dupe.
