### ISSUE TITLE
IFormFile Bug 

### ISSUE THREAD

**Issue by cristian1975** [aspnet/Mvc#8013]
If you upload a excel file to a web api endpoint, IFormFile objects from Request.Form.Files collection has bigger size than the original excel file and if you try to open the uploaded file from the upload folder is in incorrect format. The method to upload a file is taken from .net core 2.1 documentation site:
```csharp
using (var stream = new FileStream(filePath, FileMode.Create))
{
    await formFile.CopyToAsync(stream);
}
```
where fromFile is IFormFile type.
This bug is happen from .net core version 2.0.6 and above.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem?

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Home/issues/3304
