### ISSUE TITLE
Can it possible to use StateServer implement distributed cache in asp.net core like asp.net.

### ISSUE THREAD

**Issue by TimRowe** [aspnet/Mvc#8020]
Question as the title.
Because I want to set multi processes and shared the session, but I don't want to use Redis.
In ASP.NET4, it can set 
<sessionState mode="StateServer" stateConnectionString="tcpip=loopback:42424" timeout="20" />
This feature can use in ASP.NET Core ?

**Comment by Tratcher** [comment]
No, session depends on IDistributedCache for storage. We have providers for Redis and SQL, or you can provide your own implementation.
https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1

**Comment by TimRowe** [comment]
@Tratcher  Thanks, I have knew.

**Comment by TimRowe** [comment]
Can I use both memory cache and distributed cache? sometimes memory cache is fast.

**Comment by Tratcher** [comment]
In theory, but we haven't built any tiered caching implementations.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
