### ISSUE TITLE
[Question] How to get HTTP response code from ActionResult<T>

### ISSUE THREAD

**Issue by codenesium** [aspnet/Mvc#8023]
In my unit tests with IActionResult I could check the type and cast it to StatusCodeResult to check that I'm getting the validation error I want. With ActionResult<T> I don't see how to get the status code. This is what I had before.
```
IActionResult response = await controller.Patch(default(int), patch);

response.Should().BeOfType<StatusCodeResult>();
                        (response as StatusCodeResult).StatusCode.Should().Be((int)HttpStatusCode.NotFound);
```

**Comment by pranavkm** [comment]
You could look at the `ActionResult<T>.Result` property.

**Comment by codenesium** [comment]
Thanks. I was way overthinking that.

```
 (response.Result as StatusCodeResult).StatusCode.Should().Be((int)HttpStatusCode.NotFound);
```
