### ISSUE TITLE
ExceptionHandlerMiddleware log message too generic

### ISSUE THREAD

**Issue by kanadaj** [aspnet/Mvc#8025]
Using ASP.NET Core 2.1.1, the error message logged by the ExceptionHandlerMiddleware is far too generic.

It really feels like the default handler should either use `Exception.Message` or the type of the `Exception` as part of the logged message for the sake of being able to identify at least the exception type from the log message.

![image](https://user-images.githubusercontent.com/3247357/42399367-70c9f1a8-8165-11e8-8313-dab6c178cf1a.png)

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Home#3303
