### ISSUE TITLE
Video streaming from URL

### ISSUE THREAD

**Issue by ColorTwist** [aspnet/Mvc#8029]
Version: ASP.NET Core API 2.1.X

I am streaming a video from a url to target:
 
```
 private  HttpClient _client { get; } = new HttpClient();
 public async Task <IActionResult> Get(string SourceVideoURL, CancellationToken CT) 
      {
           CT.ThrowIfCancellationRequested();
           try
           {
              Stream _stream = await _client.GetStreamAsync(SourceVideoURL);
              FileStreamResult response = File(_stream, "video/mp4", true); 
             //Stream back to target
              return response;
           }
           catch (System.Exception ex) 
           {
            //Won't trigger when stream is canceled by user, Like close browser.
            //TODO: Cancel streams
           }
        
      }
 
```
It works, However,
This is the big question, 
I want to signal the streaming that the user interrupted the streaming allowing me immediately close the API GET Video streaming And not wait for the FileStreamResult or Asp.net core to handle that.

The catch here won't trigger.

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
A) Be very careful about creating a new HttpClient instance per request. See port exhaustion.
B) Why isn't `stream` returned by `_client` used in your code? Should `_stream` have been `stream`?
C) HttpContext.RequestAborted is the CancellationToken you need to listen to for client disconnects. @pranavkm why isn't FileStreamResult honoring that?

**Comment by ColorTwist** [comment]
Hello,
A) Correct, Fixed in question
B) Correct, Fixed in question
C) Good question :)

**Comment by pranavkm** [comment]
> HttpContext.RequestAborted is the CancellationToken you need to listen to for client disconnects. @pranavkm why isn't FileStreamResult honoring that?

Haven't debugged through the code, but it looks like it should: https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/FileResultExecutorBase.cs#L368-L375

**Comment by ColorTwist** [comment]
It seems so, but I can't seem to make the streaming work (FileStreamResult) with CancellationToken as shown in inisital question.

**Comment by Tratcher** [comment]
Your catch block won't be triggered since the streaming is completed after your method exits. Did you check the logs for cancellations?

**Comment by ColorTwist** [comment]
I see, In the logs i do not see cancellation. 
How do you suggest to implement the streaming for it to cancel the stream if interrupted by user ?
Honestly, can't find example for this.

**Comment by cortex93** [comment]
Your question is more related to HttpClient which have known issues with cancellation support.
Have you tried registering a lambda on the Cancellation Token to forcefully close your stream ?
`CT.Register(() => _stream.Close());`

Also, the GetStreamAsync implementation will read the response headers with no way to cancel. If your backend server has slow header response time, you may want to use the GetAsync(requestUri, HttpCompletionOption.ResponseHeadersRead, CT) overload. And then, return the stream from the response.Content.

By the way, you can instantiate HttpClient if you use the constructor overload with HttpClientHandler. Keep HttpClientHandler instances low to avoid resource exhaustion but keep in mind that reusing it, you will lose some isolation (security vs performance).

I didn't try this: 

```
var clientHandler = GetSharedHttpClientHandler();
HttpClient httpClient = new HttpClient(clientHandler);
HttpResponseMessage response = await httpClient.GetAsync(SourceVideoURL, HttpCompletionOption.ResponseHeadersRead, ct).ConfigureAwait(false);
response.EnsureSuccessStatusCode();
HttpContent c = response.Content;
Stream _stream = c != null ? await c.ReadAsStreamAsync().ConfigureAwait(false) : Stream.Null;
ct.Register(() => _stream.Close());
return File(_stream, "video/mp4", true);
```

**Comment by cortex93** [comment]
return new HttpClientHandler();

But think about Tratcher and I said about creating too many instances of it

**Comment by ColorTwist** [comment]
Hello,

A) I would appreciate to see GetSharedHttpClientHandler() example (like you and Tracther suggested).
B) I tried the code, it is working, but i am not sure if I should see cancellation token in the logs. Not sure it canceled or not.

> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://videostaaaa.co/23523523 
> info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
>       Policy execution successful.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Route matched with {action = "Get", controller = "Stream", page = ""}. Executing action MyAPI.Controllers.StreamController.Get (MyAPI)
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method MyAPI.Controllers.StreamController.Get (MyAPI) with arguments (1mB0tP1I-14, System.Threading.CancellationToken) - Validation state: Valid
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action method MyAPI.Controllers.StreamController.Get (MyAPI), returned result Microsoft.AspNetCore.Mvc.FileStreamResult in 614.2241ms.
> info: Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor[2]
>       Executing Microsoft.AspNetCore.Mvc.FileStreamResult, sending file with download name '' ...

**Comment by pranavkm** [comment]
>  I would appreciate to see GetSharedHttpClientHandler() example

I have no idea what that method does, but you should consider using `IHttpClientFactory`. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1 has more details

> I tried the code, it is working, but i am not sure if I should see cancellation token in the logs. Not sure it canceled or not.

Killing the client aborts the request just fine:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:56105/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Index", controller = "Home", page = ""}. Executing action MvcSandbox.Controllers.HomeController.Index (MvcSandbox)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method MvcSandbox.Controllers.HomeController.Index (MvcSandbox) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method MvcSandbox.Controllers.HomeController.Index (MvcSandbox), returned result Microsoft.AspNetCore.Mvc.VirtualFileResult in 1.4742ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.VirtualFileResultExecutor[1]
      Executing Microsoft.AspNetCore.Mvc.VirtualFileResult, sending file 'ReallyLargeFile.txt' with download name '' ...
info: Microsoft.AspNetCore.Server.Kestrel[34]
      Connection id "0HLF8T7U965DV", Request id "0HLF8T7U965DV:00000001": the application aborted the connection.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action MvcSandbox.Controllers.HomeController.Index (MvcSandbox) in 4475.311ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 4712.322ms 200 application/octet-stream
```

From your logs, it looks like the request finished prior to the client cancelling.

**Comment by ColorTwist** [comment]
I implemented IHttpClientFactory, very nice. thank you for sharing.

**Comment by davidfowl** [comment]
Aborts may be slightly broken when behind IIS

**Comment by ColorTwist** [comment]
Yes, behind IIS 10 .. Question is, should it work with IIS 10 or not...
