### ISSUE TITLE
Add FromItems Attribute for Model Binding

### ISSUE THREAD

**Issue by Kahbazi** [aspnet/Mvc#8030]
Right now there are `[FromHeader]`, `[FromQuery]`, `[FromRoute]`, `[FromForm]` , `[FromServices]` and `[FromBody]` for model binding for mvc actions.

Can you also add a `[FromItems(string key)]` which uses `HttpContext.Items` to bind model?

It can be useful to set values on middlewares before MVC and access it more easily on actions.

**Comment by mkArtakMSFT** [comment]
Hi @Kahbazi. The framework has all the extensibility points for you to create your custom binder attributes. This is not something we plan to do in the framework in the near future.
Look at how the existing attributes are handled in the code.
