### ISSUE TITLE
ActionLink regenerate wrong text when use accent

### ISSUE THREAD

**Issue by zokiad** [aspnet/Mvc#8031]
Hi,

I use .net core 2.1.

When you write:

 @Html.ActionLink("éàëèêî", "Action")

Generated html is:
`<a href="/action">������</a>`

### **Issue:**
Wrong character conversion to html of the parameter linkText

**Comment by masterjs** [comment]
@zokiad I often had this in one of my ASPNET Core app when somehow many of my .CSHTML were given the encoding  "Western European (Windows) - Codepage 1252". When I changed it to "Unicode (UTF-8 with signature) - Codepage 65001" the accents started to show as expected. 

I do not know if there's a better fix, but it got me through.

Hope this help!

**Comment by mkArtakMSFT** [comment]
Hey @zokiad.
Please give @masterjs's suggestion a try. That will most probably do it.

**Comment by zokiad** [comment]
Hi,

The enconding of my view was ANSI.

I modified encoding of file to UTF-8-BOM. And this workaround fix the issue.

Thank you for your help.

**Comment by mkArtakMSFT** [comment]
Thanks for confirming!
