### ISSUE TITLE
How To Use Blazor With MVC

### ISSUE THREAD

**Issue by Sheko007** [aspnet/Mvc#8033]
Feature request?:

#### Description of the problem:

Can't Use Blazor With MVC 

 Microsoft.AspNetCore.App

**Comment by mkArtakMSFT** [comment]
@Sheko007, what are the issues you're facing? What version of ASP.NET Core are you trying to use it with?
/cc @danroth27, @rynowak

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Blazor#1106
