### ISSUE TITLE
"dotnet watch run" does not take changes in partial views

### ISSUE THREAD

**Issue by reyou** [aspnet/Mvc#8038]
I initially thought it is tooling issue, and created issue at https://github.com/aspnet/DotNetTools/issues/459 but I got redirected here.

#### Is this a Bug or Feature request?:
BUG

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
To reproduce:
- Create partial view `.\Views\Partials\TopNavigationBar.cshtml`
- Add some HTML elements
-  Render view in `_Layout.cshtml` with `@Html.Partial("../Partials/TopNavigationBar")`
- `dotnet watch run --launch-profile local`

Do some changes in TopNavigationBar.cshtml. Changes remain same on last page open in browser. For example if I am on localhost:/users/index view, if I hit F5, nothing changes, but some other pages like Home Page takes changes.
This happens same if I run it from VS 2017.

#### Description of the problem:
Partial View changes does not take effect on last browsed page at browser unless rebuild action taken.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
**Env**: .net core 2.1
**App**: MVC Web App

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @reyou.
@pranavkm, didn't we have a similar issue?

**Comment by pranavkm** [comment]
Perhaps this - https://github.com/aspnet/Razor/issues/2466. MVC independently watches and recompiles cshtml files on change without having to rebuild your application (or running `dotnet watch`). Do you have a repro app demonstrating the issue?

**Comment by reyou** [comment]
I will try to create a one. Sorry the one I was working private one.

**Comment by reyou** [comment]
I am not sure what was the cause of the problem, but I could not re-create issue for sample project.
Then I upgraded my visual studio (and it updated .net core along with it) and problem has gone.

I will close this issue for now, may be it was very specific scenario, and it is almost impossible to re-create.

Thanks!
