### ISSUE TITLE
Controller cache attribute in asp net core?

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8042]
_From @ChristopherRobinSuperStar on June 23, 2018 13:6_

Is it possible to use [ResponseCache()] attribute with SqlDependency and ServiceBroker in asp net core 2.1?
If it's not, please add this feature. It was very useful in asp net mvc earlier:
```
[OutputCache(Duration = Int32.MaxValue, SqlDependency = "DBNAME:DEPENDENCY_TABLE_NAME", Location = System.Web.UI.OutputCacheLocation.Server)]
public ActionResult Index()
{
}
```

_Copied from original issue: aspnet/Home#3259_

**Comment by Eilon** [comment]
_From @pranavkm on June 29, 2018 15:0_

@JunTaoLuo \ @Tratcher is this something you could do with the response cache middleware?

**Comment by Eilon** [comment]
_From @Tratcher on June 29, 2018 15:46_

Certainly not at the moment. I'm not even quite sure how you'd implement that.

**Comment by mkArtakMSFT** [comment]
We won't be able to do it without the support of the ResponseCache middleware.
