### ISSUE TITLE
how to add assembly info to PrecompiledViews dll generated by dot net core 2.0

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8044]
_From @parthakbari on July 4, 2018 5:37_

# how to add assembly info to PrecompiledViews dll generated by dot net core 2.0

# General

views in my .net core 2.0 project is getting generated in PrecompiledViews dll..

How to add the assembly info to this dll, information such as company name, copyrights etc..

Tried to some tag in project file but didn't work

      `<PropertyGroup Label="Assembly">
           <AssemblyName>HegicMvc_Poc.PrecompiledViews</AssemblyName>
           <PackageId>Library</PackageId>
           <Product>Library</Product>
           <Authors>StackOverflow Answer</Authors>
           <Company>Test</Company>
           <Description>Library</Description>
           <Copyright>Copyright © 2016 - 2017 Test</Copyright>
           <Version>2.0.0</Version>
           <AssemblyVersion>1.0.0</AssemblyVersion>
           <FileVersion>1.0.0</FileVersion>
      </PropertyGroup>` 

Is there any way to do this?

_Copied from original issue: dotnet/core#1751_

**Comment by pranavkm** [comment]
_From @Petermarcu on July 9, 2018 21:9_

@Eilon @muratg

**Comment by pranavkm** [comment]
_From @Eilon on July 9, 2018 21:46_

@pranavkm can you move this issue to the appropriate repo and answer it?

I believe the short answer is: by default the precompiled views assembly will use the same metadata as the app's metadata, though there might also be a way to customize it beyond that.

**Comment by pranavkm** [comment]
There really isn't any way to change this with MVC precompilation. That said, we're deprecating the precompilation tool in favor of build time compilation using the Razor Sdk. This copies over a bunch of metadata from the app's settings (such as `Product`, `Copyright` etc) while also allows for additional cs files to be included as part of compile. See https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.1#properties for details.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
