### ISSUE TITLE
Asp.Net Core 2.1 with .Net Framework 4.6.1 error after deployment using visual studio publish

### ISSUE THREAD

**Issue by paragpkulkarni** [aspnet/Mvc#8048]
This is a bug for Asp.Net Core 2.1.1 targetting Full framework 4.6.1

#### I am trying to deploy Asp.Net Core 2.1 application with target framework 4.6.1 on server. I am using visual studio 2017 v15.7.2 to publish the application. After publishing I am copying the publish folder on the server where deployment is intended. Everything works fine on local machine. But when I am trying to run the application on the server , it is throwing the exception ".Net Framework 4.6.1 not installed, please install it.".

Initially I though framework is not installed, but when I checked I saw the following frameworks are installed on the server

1.  Microsoft .Net Core Runtime - 2.0.5 (x64)
2.  Microsoft .Net Core Runtime - 2.0.5 (x86)
3.  Microsoft .Net Core Runtime - 2.1.1 (x64)
4.  Microsoft .Net Core Runtime - 2.1.1 (x86)
5.  Microsoft .Net Core SDK2.1.301 (x64)
6.  Microsoft .Net 4.5 Multi-Targetting Pack
7.  Microsoft .Net 4.5.1 Multi-Targetting Pack
8.  Microsoft .Net 4.5.1 Multi-Targetting Pack(ENU)
9. Microsoft .Net 4.5.1 SDK
10  Microsoft .Net 4.5.2 Multi-Targetting Pack
11. Microsoft .Net 4.5.2 Multi-Targetting Pack(ENU)
12. Microsoft .Net 4.6.1 SDK
13.  Microsoft .Net 4.6.1 Targetting Pack
14.  Microsoft .Net 4.6.1 Targetting Pack(ENU)

Version - Asp.Net Core 2.1.1. SDK version - 2.1.300

Here is a [link](https://github.com/paragpkulkarni/SampleApp)  for .csproj file.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @paragpkulkarni.
Can you give more details about the `server` you refer to? Is that an IIS, IISExpress, or just a file share you'tr trying to publish to?

**Comment by paragpkulkarni** [comment]
Here is a version number from the registry  **393297**
OS version- **Windows Server 2012 R2 Standard**

**Comment by mkArtakMSFT** [comment]
Thanks @paragpkulkarni.
It seems you have .Net Framework 4.6 installed on your machine.

The update to .Net Framework 4.6.1 should be available through Windows Update.  Here is a KB article about the update and the ways to install it: https://support.microsoft.com/en-us/help/3102467/the-net-framework-4-6-1-for-windows-server-2012-r2-on-windows-update
