### ISSUE TITLE
Editing a view while debugging it in Razor UI library doesn't refresh browser output.

### ISSUE THREAD

**Issue by flatproject** [aspnet/Mvc#8059]
#### Is this a Bug or Feature request?:
Not sure, it might be a Bug or I simply might need some guidance which I cannot find anywhere else.

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Create a new Razor UI class, add some views. Link the library to your main project, run the project, try to edit the razor view code in the shared library, refresh page on browser, output on browser doesn't refresh.

#### Description of the problem:
When adding razor views in Razor UI library I cannot fix errors and continue debug. The page will not refresh. I have to stop the debug session and start again.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Latest stable versions of everything on nuget. 2.1.1

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Razor/issues/2426.
