### ISSUE TITLE
Is there a way to add a default page convention that looks at the folder name

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8060]
_From @JohnGoldsmith on July 12, 2018 13:25_

Hi,

Is there a way to add a routing convention for Razor Pages that allows you to use the parent folder name as a default route?

For example, if I have `Pages/Products`, folder structure I'd prefer to have a default page named `Products.cshtml` and for `Pages/Services`, `Services.cshtml` (as opposed to having to use `Index.cshtml` in both cases).

This is just to make things clearer in code ie the model would then be name ProductsModel and all open tabs in Visual Studio wouldn't have to say "Index.."

Thanks

John 

_Copied from original issue: aspnet/Home#3320_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JohnGoldsmith.
@kichalla, can you please answer the above question?

**Comment by pranavkm** [comment]
Here's the part that calculates routes for "Index.cshtml" Razor pages - https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.RazorPages/Internal/PageRouteModelFactory.cs#L67-L79. You could do something similar looking at the path in a route model convention. Alternatively, you could define absolute routes for your page e.g. `@page /Products` to avoid having to write a convention.

**Comment by JohnGoldsmith** [comment]
That's great.  Thanks very much @pranavkm 

I've gone for the directive approach for the time being, as it seems to be the lightest touch and I'm not dealing with lots of pages.

For anyone else who (like me) wants more details on @page directive you can find it over here:
[](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio#custom-routes)

Thanks again Pranav.
