### ISSUE TITLE
Cannot implicitly convert type 'System.Collections.Generic.IEnumerable<T>' to 'Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.IEnumerable<T>>

### ISSUE THREAD

**Issue by fspataro** [aspnet/Mvc#8061]
Hi

I'm not sure if this is a bug or expected functionality.  It's easy enough to code around, so it's more of a question about why it works this way... If it's expected functionality, it might be worthwhile to add a note about this type of conversion in the [documentation](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-2.1#actionresultt-type).
 
To reproduce use the example/template "ValuesController" in the WebAPI project template. 

1. Using VS2017, create a default WebAPI project template 
2. Open the ValuesController.cs file
3. In the first method Get() change the mock line from string[] to IEnumerable<string> with either a cast or .AsEnumerable(), etc.  
4. Build/compile fails with: 

Cannot implicitly convert type 'System.Collections.Generic.IEnumerable<string>' to 'Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.IEnumerable<string>>'	

example:

```
// GET api/values
[HttpGet]
public ActionResult<IEnumerable<string>> Get()
{
	//works as string[] 
	//var values = new string[] { "value1", "value2" };	

	//fails as IEnumerable<string>
	var values = (IEnumerable<string>)new string[] { "value1", "value2" };

	return values;

	//original template/mock line
	//return new string[] { "value1", "value2" };
}
```

The documentation says one of the "benefits" of ActionType<T> is:

* Implicit cast operators support the conversion of both T and ActionResult to ActionResult<T>

The method signature is IEnumerable<string> so it seems like this cast should be "implicit".  I suspect the variable needs to be materialized as a class rather than the interface for the implicit cast.  

It's not a big deal but in general my "manager/service" methods used in the controller return an IEnumerable<T> as well so it ends up having as lot of extraneous .ToList() being added.   Mostly just "feels" icky... 

I'm currently working in  `Microsoft.AspNetCore.App` 2.1.1 but I think I've noticed it way back...

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Home/issues/3224, https://github.com/aspnet/Mvc/issues/7981. It's an language limitation that we cannot do much about. Doing a `ToList` would be the way to go

**Comment by fspataro** [comment]
Thanks @pranavkm! I suspected it was something along those lines and was more curious than anything and my google didn't catch that issue item on the first page ;)

Closing.
