### ISSUE TITLE
CLSCompliant attribute for ASP.Net Core views

### ISSUE THREAD

**Issue by hdkesting** [aspnet/Mvc#8074]
I am not quite sure whether this is a Bug or a Feature request.
I already have a question about this issue on [StackOverflow](https://stackoverflow.com/questions/51082036/clscompliant-attribute-for-asp-net-core-views), but got no answers.

In short:
* I have an ASP.Net Core MVC project (v2.1) project with CodeAnalysis Analyzer
* This gives a build warning: "warning CA1014: Mark assemblies with CLSCompliant" on the Views assembly
* There is already a `[assembly: System.CLSCompliant(false)]` on the main web project and that attribute is visible in the main dll
* But the Views are compiled into a separate assembly, which doesn't have this attribute - which is what the analyzer complains about

I think the Views assembly should use *all* the same assembly-level attributes as are defined for the main web project (not just the specific copyright and version related ones). Or there should be a way to specify attributes for this extra assembly.

**Comment by pranavkm** [comment]
You can use the [`RazorCompile` itemgroup](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.1#properties) to compile arbitrary files in to your Razor views assembly. Something along the lines of 

```xml
<ItemGroup>
   <RazorCompile Include="AssemblyInfo.cs" />
</ItemGroup>
```

**Comment by hdkesting** [comment]
I had to use "Properties/AssemblyInfo.cs", but that worked!
