### ISSUE TITLE
Name collisions can remove `ModelValidationState.Invalid` from entries

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#8078]
#### Is this a Bug or Feature request?:
bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
https://github.com/dougbu/NameCollisionLoseInvalid

#### Description of the problem:
When name collisions occur between model bound parameters and properties, later validation may overwrite `ModelValidationState.Invalid` entries. This requires
- A name collision e.g. `[FromRoute] int id, [FromQuery(Name = "id")] string identifier`
- Earlier entry is invalid e.g. http://localhost:5000/api/values/notAnInt
- Later entry is `null` but model is set e.g. http://localhost:5000/api/values/notAnInt?id
- Later entry must also not be implicitly or explicitly required i.e. not of a non-`Nullable` value type or have associated `[BindRequired]` or `[Required]` attributes

Problematic code is here: https://github.com/aspnet/Mvc/blob/f12f9b46ed5cc848a36db1fa9933c35b3eb60351/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidationVisitor.cs#L103-L110

Suggest last condition should be:
``` c#
entry != null && entry.ValidationState != ModelValidationState.Invalid
```
(Overwriting `Valid` with `Valid` is fine, as is losing `Skipped` or `Unvalidated`.)

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Looks as if problem existed as far back as 1.0.0 RC2. See 8a502dbe5d

**Comment by mkArtakMSFT** [comment]
@dougbu, looks like you've already fixed this. If so, feel free to mark this as done. Thanks!

**Comment by dougbu** [comment]
@mkArtakMSFT I didn't fix this -- yet. I found the problem while fixing #7963 and #7992.

**Comment by dougbu** [comment]
556880872d
