### ISSUE TITLE
dll with RazorPages lead to FileNotFound exception

### ISSUE THREAD

**Issue by seriouz** [aspnet/Mvc#8084]
#### Is this a Bug or Feature request?:
Its a bug:

I have a dll with Razor views and RazorPages. This dll gets loaded as plugin on Startup() via `ApplicationPartManager.ApplicationParts.Add(new CompiledRazorAssemblyPart(assembly));` on my main ASPNET.Core application.
When i access the normal views they get displayed. But the RazorPages lead to

```
FileNotFoundException: Could not load the specified file.
System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)

FileNotFoundException: Could not load file or assembly 'Tenants.FirstOne, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
System.Signature.GetSignature(Void* pCorSig, int cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
System.Reflection.RuntimePropertyInfo.get_Signature()
System.Reflection.RuntimePropertyInfo.get_PropertyType()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.DefaultPageApplicationModelProvider.CreateModel(PageActionDescriptor actionDescriptor, TypeInfo pageTypeInfo)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.DefaultPageApplicationModelProvider.OnProvidersExecuting(PageApplicationModelProviderContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.DefaultPageLoader.Load(PageActionDescriptor actionDescriptor)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler+<>c__DisplayClass12_0.<RouteAsync>b__0(HttpContext c)
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I am using **2.1.301**

Edit: The RazorPages are **getting** displayed when i add the project of the plugin as **project reference** to the main project.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @seriouz.We will need a repro project to investigate this. Can you please share it as a repo in GitHub?
/cc @pranavkm, can you please look into this when a repro will be provided?

**Comment by seriouz** [comment]
Sure, i'll upload a sample project!

**Comment by mkArtakMSFT** [comment]
Hi @seriouz.

After another review of this ask it seems this is more related to the way module management is organized in your app. At this point, our guidance is to look at a module system such as the one Orchard Core provides. Orchard Core modules allow you to build modules as NuGet packages that can be added to your application on the fly. And you can use them as a low level framework without adopting the entire Orchard CMS infrastructure. Check out https://github.com/OrchardCMS/OrchardCore.Samples to see what this looks like.
