### ISSUE TITLE
Customizing Route template token replacement without IApplicationModelProvider

### ISSUE THREAD

**Issue by sgwatgit** [aspnet/Mvc#8089]
#### Is this a Bug or Feature request?:

Feature request

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

Creating a `IApplicationModelProvider` that inherits from `DefaultApplicationModelProvider` in order to customize the token replacement in `RouteAttribute` templates.

```csharp
public class CustomControllerNameApplicationModelProvider : DefaultApplicationModelProvider
{
    public CustomControllerNameApplicationModelProvider(IOptions<MvcOptions> mvcOptionsAccessor, IModelMetadataProvider modelMetadataProvider) 
        : base(mvcOptionsAccessor, modelMetadataProvider)
    {

    }

    protected override ControllerModel CreateControllerModel(TypeInfo typeInfo)
    {
        var controllerModel = base.CreateControllerModel(typeInfo);

        controllerModel.ControllerName = PascalToKebabCase(controllerModel.ControllerName);

        return controllerModel;
    }

    private string PascalToKebabCase(string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;

        return Regex.Replace(
            value,
            "(?<!^)([A-Z][a-z]|(?<=[a-z])[A-Z])",
            "-$1",
            RegexOptions.Compiled)
            .Trim()
            .ToLower();
    }
}
```
Register in `Startup.cs`
```csharp
services.AddTransient<IApplicationModelProvider, CustomControllerNameApplicationModelProvider>();
```

#### Description of the problem:

When using the `RouteAttribute` on an Api controller, the `[controller]` token is a great way to automatically generate the route from the controller name.

Unfortunately this only allows for a direct replacement of this token with the controller name minus the `Controller` suffix as seen [here](https://github.com/aspnet/Mvc/blob/a67d9363e22be8ef63a1a62539991e1da3a6e30e/src/Microsoft.AspNetCore.Mvc.Core/Internal/DefaultApplicationModelProvider.cs#L170).

I can overcome this by modifying the `ControllerModel` created by the `DefaultApplicationModelProvider`, but this seems both heavy handed (overriding types in `Microsoft.AspNetCore.Mvc.Internal;`) and dangerous (other things could rely on `ControllerModel.ControllerName`.

I would prefer to have a token replacement strategy that I could customize where the token is parsed out and the value is retrieved [here](https://github.com/aspnet/Mvc/blob/a67d9363e22be8ef63a1a62539991e1da3a6e30e/src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels/AttributeRouteModel.cs#L374).

As it stands I end up not using `Route("api/[controller]")` when my controller names are more than one word (eg `UserManagementController`, `ShoppingCartAdministrationController` would be `user-management` and `shopping-cart-administration`) and hardcode the path instead. This isn't any different than what I did in Web Api 2, but I don't want some controllers to use the token and others to be hardcoded, so they're all hardcoded.

I've tested this out and it works but I'm very very skeptical of my solution.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sgwatgit.
@pranavkm, do we have a mechanism to achieve this today?

**Comment by sgwatgit** [comment]
Ah, thanks for the direction - I looked through that documentation but I don't think the connection clicked for me at the time.

Would I need to apply the attribute implementing `IControllerModelConvention` to all controllers explicitly / via a "BaseController"?
Can it be applied automatically in some way?

**Comment by pranavkm** [comment]
You could apply a convention as part of the start up - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.1#sample-modifying-the-applicationmodel

**Comment by sgwatgit** [comment]
Thanks for the help - I think I can get it working from here.
