### ISSUE TITLE
Use IApiDescriptionGroupCollectionProvider in external application

### ISSUE THREAD

**Issue by BackDoorMan00** [aspnet/Mvc#8093]
I want to achieve something similar to `IDesignTimeDbContextFactory<TContext>` but use `IApiDescriptionGroupCollectionProvider` in an external console application. Is this hard to accomplish?

I use `IApiDescriptionGroupCollectionProvider` for client generation and it currently runs every time I run the server (in `Program.Main`) which in my opinion is bad. I would like to create a separate tool for it. Would you suggest any solution or should I be using OpenAPI?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@pranavkm FYI

**Comment by pranavkm** [comment]
It's expected that you get an instance of `IApiDescriptionGroupCollectionProvider` and query it every time. It has versioning associated with it and may produce different results. Have a look at NSwag's swagger generation - https://github.com/RSuter/NSwag/wiki/AspNetCoreToSwaggerGenerator - that produces a OpenAPI 2.0 document from an `IApiDescriptionGroupCollectionProvider`
