### ISSUE TITLE
Documentation? How to use WebApplicationFactory without CreateClient?

### ISSUE THREAD

**Issue by NetTecture** [aspnet/Mvc#8094]
2.1.0 current version.

I am writing integration tests and for the simple reason of "this is how a framework we use is desigend" that I can not change, I can not use the CreateClient method.

I need to have a URL that I pass into the framework so it can create it's own HttpClients. The WebFactory itself also has no property that can be used to create a valid URL.

Simple as it is - how do I create my own HttpClient to run against a WebFactory hosted website? Any documentation? Seems not.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @NetTecture.
@javiercn, can you please look into this?

**Comment by javiercn** [comment]
Thanks for reaching out.

@NetTecture Can you provide more details on what you are trying to do? I’m not sure I understand.

**Comment by javiercn** [comment]
@NetTecture If your third party component doesn't accept a given instance of HTTP client there is nothing we can do about it. The HTTP Client is the central piece to talking to the server in memory.

You can access and define the url used by the server in WAF.ClientOptions.BaseUrl or by calling CreateClient(new WAFClientOptions)

It's also considered a good practice to take in HTTP client as a dependency and not blindly new one up as its meant to be a singleton and allows for people customizing the HTTP pipeline.

Closing this issue as there's nothing we can do here and the URL is already exposed. See https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1#aspnet-core-integration-tests for docs
