### ISSUE TITLE
Deprecate APIs exposing Roslyn types

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#8096]
See https://github.com/aspnet/Mvc/issues/8079 for details.

This issue covers the part in 2.2 milestone to mark the APIs as `Obsolete`.

**Comment by mkArtakMSFT** [comment]
@pranavkm, I guess this should turn to `2 - Working` now, shouldn't it?

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/0726b8b98b9741e5b611e690dfc88646b1226881
