### ISSUE TITLE
How to get the root url before the request?

### ISSUE THREAD

**Issue by tiandian** [aspnet/Mvc#8101]
#### Is this a Bug or Feature request?:
Feature request

In asp.net mvc, we can get the root ur from HttpRuntime.AppDomainAppVirtualPath.

But in asp.net core, there is no HttpRuntime.AppDomainAppVirtualPath, so we can't get the website's root url before the request is start, this is very inconvenience,

I see someone open a issue here: https://github.com/aspnet/dnx/issues/13, but it is not resolved and closed.

So I want ask how to get the root url before the requse is start?
Then I can open a browser after the webserver is start.

Thanks.

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
It's not possible. You need to read this information directly from config. The server does not read the endpoint configuration until it's ready to start the application (after Startup). Even then, that information would be inaccurate much of the time due to reverse proxy setups like IIS, Nginx, docker, etc..

Why do you need the value outside of the context of a request?

**Comment by tiandian** [comment]
@Tratcher  
`It's not possible. `
But the old asp.net MVC can do this by HttpRuntime.AppDomainAppVirtualPath, I just need the HttpRuntime.AppDomainAppVirtualPath's value,  why asp.net core mvc can't give this value?

`You need to read this information directly from config`
No, the config is not right, 
because the root url can be changed by pass --server.urls "http://*:8000" or  ASPNETCORE_URLS=http://+:80.
we need run it in a docker, we need change the url or the port by pass the argument to the asp.net core.

`The server does not read the endpoint configuration until it's ready to start the application (after Startup).`
If we can get this value after Startup will be ok.

`Even then, that information would be inaccurate much of the time due to reverse proxy setups like IIS, Nginx, docker, etc..`
I just want send the request to myself in the asp.net core, so I only need a local root url, the local root url will be confirmed after start,  it is not related to IIS, Nginx, docker..

`Why do you need the value outside of the context of a request?`
Because I need open my site's home page immediately in my asp.net core program after my site is start. 
I may run my program as a desktop program, but I don't want packet it with electron(too big), I only need open it in a local webbrowser.

see below code:

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
			......
        }

        public void Configure(IApplicationBuilder app)
        {

			......
            OpenBrowser();
        }

        private void OpenBrowser()
        {
            string rootUrl = ..... ???;
            ProcessStartInfo psi = new ProcessStartInfo("chrome", "--app=\"" + rootUrl + "\"") { UseShellExecute = true };
            try
            {
                Process.Start(psi);
            }
            catch
            {
                try
                {
                    psi.FileName = "firefox";
                    psi.Arguments = rootUrl;
                    Process.Start(psi);
                }
                catch
                {
                    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                    {
                        psi.FileName = "edge";
                    }
                    else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                    {
                        psi.FileName = "safari";
                    }
                    try
                    {
                        Process.Start(psi);
                    }
                    catch
                    {
                    }
                }
            }
        }
    `}`

So I only need the old MVC's HttpRuntime.AppDomainAppVirtualPath's value.

Thanks.

**Comment by Tratcher** [comment]
The architecture is completely different. The old MVC never started your app until the first request had been received so it had that information available.

What you're trying to do can't be done in Startup, but it can be done in Main.
```
        public static void Main()
        {
            var host = BuildWebHost(null);
            host.Start();
            var serveraddress = host.ServerFeatures.Get<IServerAddressesFeature>();
            OpenBrowser(serverAddresses.Addresses);

            host.WaitForShutdown();
        }

        private static IWebHost BuildWebHost(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
        }
```

**Comment by tiandian** [comment]
@Tratcher,  the above code is very useful, thanks.
