### ISSUE TITLE
options.OutputFormatters.Add(new XmlResponseOutputFormatter()) Reports supported content type but doesn't work

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/Mvc#8109]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
`

                        var builder = services.AddMvcCore(options =>
			{
				options.OutputFormatters.Clear();
				options.InputFormatters.Clear();

				options.RespectBrowserAcceptHeader = true;
				options.ReturnHttpNotAcceptable = true;

				options.InputFormatters.Add(new XmlDataContractSerializerInputFormatter(options));
				options.OutputFormatters.Add(new XmlDataContractSerializerOutputFormatter());

			})
			.SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
				.AddApiExplorer()
				.AddVersionedApiExplorer(o =>
				{
					o.GroupNameFormat = "'v'VVV";
					o.SubstituteApiVersionInUrl = true;
					o.DefaultApiVersion = new ApiVersion(1, 0);
					o.AssumeDefaultVersionWhenUnspecified = true;
				})
				.AddAuthorization()
				.AddDataAnnotations()
				.AddRazorPages()
				.AddFormatterMappings()
				.AddCors();

`

#### Description of the problem:
Using the above in a blank MVC core site the content type is reported as supported (in swagger) however actually trying to request application/xml or text/xml using the Accept header fails with a 406 response code.

I've tried this with IQueryable/IEnumerable Lists. It fails every time. It appears to be something to do with having to return Ok(<result>) instead of just <result> in ActionResult<IQueryable<>>.  Sometimes VS.NET accepts just return <result> and other times it says that it cannot be cast to ActionResult<<result>> and I can't see any reason why it's ok sometimes but not others.

Other types will work fine if I add the formatters. Json works fine, the contrib project for bson will work fine, even a custom formatter for atom will work fine. But xml won't respond properly when requested.

In the logs the only thing written is:

Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector:Warning: No output formatter was found for content type 'application/xml' to write the response.
Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor:Warning: No output formatter was found for content type 'application/xml' to write the response.

In that specific case this is the signature of the method:

		[HttpGet("List")]
		[AllowAnonymous]
		public override ActionResult<IQueryable<PaymentMethodDto>> List()
		{
			return Ok(Repository.List()); //This is just IQueryable<PaymentMethodDto>
		}

Note also that the method is executed, and then throws saying it can't find the output formatter.

PaymentMethodDto is decorated like so:

    [DataContract]
    public class PaymentMethodDto : BaseDtoWithId
    {
        /// <summary>
        /// Name
        /// </summary>
        [DataMember]
        [StringLength(150), Required]
        public string Name { get; set; }
        ….
}

BaseDtoWithId has [DataContract] on it as well.

And my json formatter that does work has json settings to use DataContract as well.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.2

**Comment by pranavkm** [comment]
Both kinds of Xml output formatters will inspect the type to determine if that's something they could serialize. It's likely that the actual type returned by `Repo.List()` isn't serializable which is why you're seeing the 406. For instance, returning `Enumerable.Empty<string>().AsQueryable()` fails for me with an error logged saying

> System.Runtime.Serialization.InvalidDataContractException: Type 'System.Linq.EnumerableQuery`1[System.String[]]' cannot be serialized.

In general, you almost never want to return the queryable returned by EF (or another ORM) to the client without first materializing it. If serializing the queryable throws part way through, you could an incomplete response (see https://github.com/aspnet/Mvc/issues/7915#issuecomment-397070711) with a 200 OK Status. Those tend to be hard to discover and debug.

Secondary to the reported issue, a couple more suggestions

* unless you're [familiar](http://benfoster.io/blog/bare-metal-apis-with-aspnet-core-mvc) with what you're getting in to, I'd recommend using `AddMvc` as opposed to doing `AddMvcCore`, especially when you seem to also be using Razor Pages. 

* Use the builder extensions [AddXmlDataContractSerializerFormatters](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.mvcxmlmvccorebuilderextensions.addxmldatacontractserializerformatters?view=aspnetcore-2.1) to wire up the Xml formatter.

**Comment by JohnGalt1717** [comment]
Thanks. I've been out of the office. Will do a sample on Monday.

The objects are definitely serializable. I can manually serialize to xml, they serialize just fine in full fat web API which this is being ported from. 

We return iqueryable for odata support so it isn't optional.

**Comment by pranavkm** [comment]
> We return iqueryable for odata support so it isn't optional.

Are you using https://www.nuget.org/packages/Microsoft.AspNetCore.OData? They have their own formatters (from what I can tell) and don't rely on the XmlFormatters to serialize IQueryable instances.

**Comment by JohnGalt1717** [comment]
Yes I am, but I use the simple version instead of the /odata endpoints (that whole thing is a mess of complexity that doesn't need to exist and they need to release a light version that just gives you the querying and TotalCount in result and nothing else cause most people don't want nor, need nor want the security issues with the full package)

You can use it inline with MVC .NET and have your IQueryable endpoints allow $filter, $search, $top, $Skip etc. and it will respond accordingly with filters if you return an IQueryable (and only if you do)

But then MVC core has issues because you have to return Ok() instead of the IQueryable and the Xml formatters don't work properly.

**Comment by pranavkm** [comment]
Do you have a repro app for this? I'm not super familiar with your app's set up so it's hard to figure out what needs to be addressed.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
