### ISSUE TITLE
Does model binding work for Ajax Posts

### ISSUE THREAD

**Issue by adriaanp** [aspnet/Mvc#811]
I have this:
`public async Task<IActionResult> Post(TaskInput input)`

And calling this method via ajax post, but the input Parameter is always null?

**Comment by ChrisProlls** [comment]
I'm trying to do the same as @adriaanp but it still doesn't work (I posted on stackoverflow : http://goo.gl/ycjV7k), and I don't find any solution for the moment. Are there news about it ?

**Comment by yishaigalatzer** [comment]
Use [FromBody] for json posts
