### ISSUE TITLE
How To Bind Model Value From Body by Custom Binder

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8110]
_From @Edward-Zhou on July 18, 2018 9:33_

I am trying this document [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.1), I could get the model value when passing by `Query String`.
But, I want to bind the model to Request Body, how could I fetch value from Request body when I sending request with `application/json`.

_Copied from original issue: aspnet/Home#3338_

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by Edward-Zhou** [comment]
Before asking in `StackOverflow`, I am wondering whether my requirement is possible. I already researched in StackOverflow, but did not find any related information about this.

**Comment by dougbu** [comment]
@Edward-Zhou one option is to write `CustomModelBinder` as a wrapper around the existing `BodyModelBinder`. The wrapper could change property values, map the returned model to something different, et cetera. (A few of the built-in binders e.g. [`CollectionModelBinder`](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/CollectionModelBinder.cs) and [`ComplexTypeModelBinder`](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/ComplexTypeModelBinder.cs) use inner model binders. See also the corresponding `IModelBinderProvider` implementations e.g. [`CollectionModelBinderProvider`](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/CollectionModelBinderProvider.cs).)

Another possibility is to rewrite [`BodyModelBinder`](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/BodyModelBinder.cs) in your `CustomModelBinder`, adding or removing whatever you need. If you take this approach, I'll be interested to hear your reasons.

Might also wrap `BodyModelBinder` to make it more "something" in `CustomModelBinder`. I doubt this would be valuable in this context. But, I did this in aspnet/WebHooks. (The "something" there was mainly usability in request filters.) See  the [`WebHookRequestReader`](https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNetCore.WebHooks.Receivers/WebHookRequestReader.cs) in that repo.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
