### ISSUE TITLE
How to Bind a model from Request Parameters manually inside an action?

### ISSUE THREAD

**Issue by amirhmi** [aspnet/Mvc#8115]
I have a General Action that is called for different purposes and will do some common acts and then call the proper specific method to do additional acts that are necessary for each purpose. Each of these methods has its own parameter list(like any normal asp action) and I want to reuse the ASP binding system in my general action to create instance of these parameters and pass them to the method.
here is a simplified version of what I want to do:

```
public async Task<IActionResult> GeneralAction(string actionName){
//do some common acts (like creating event)
var newEvent = CreateEvent(.....);


if(actionName = "action1"){
     //here I want to call Action1() so I need create an instance of student from request
     var student = ....//getting student from request
     Action1(student, newEvent);
}


}

public void Action1(Student student, Event newEvent)
{
//do specific acts here
}

```

**Comment by pranavkm** [comment]
Have you tried [`TryUpdateModel`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.tryupdatemodelasync?view=aspnetcore-2.1#Microsoft_AspNetCore_Mvc_ControllerBase_TryUpdateModelAsync__1___0_)?

**Comment by amirhmi** [comment]
Thank you so much 
It works
@pranavkm
