### ISSUE TITLE
How to get used InputFormatter and OutputFormatter in ActionFilter?

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8128]
_From @MhAllan on July 23, 2018 3:47_

Hi,

So I have added Message Pack formatter beside Json. now in an action filter I want to get that formatter to deserialize some request header. how can I get access to the current formatter?

_Copied from original issue: aspnet/Home#3349_

**Comment by Eilon** [comment]
_From @khellang on July 23, 2018 8:57_

I don't think there's an easy way to get a specific formatter. A formatter does quite a few more things than just serializing an object, like setting headers, determining encoding, writing to the response body etc.

I would recommend just serializing the header yourself. If you need some kind of conneg, you could look at the `ObjectResultExecutor` and maybe copy some code.

**Comment by AlexejTimonin** [comment]
@MhAllan this is how you can get specific formatter from within ActionFilterAttribute:
````c#
    public class FooAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuted(ActionExecutedContext context)
        {
            var options = context
                .HttpContext
                .RequestServices
                .GetService(serviceType: typeof(IOptions<MvcOptions>)) as IOptions<MvcOptions>;

            var mvcOptions = options.Value;
            var messagePackInputFormatter = mvcOptions.InputFormatters
                .FirstOrDefault(formatter => formatter is MessagePackInputFormatter);
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            // Magic
        }
    }

**Comment by MhAllan** [comment]
Lovely, many thanks @AlexejTimonin
