### ISSUE TITLE
Model binding fails with POST action parameter name "model"

### ISSUE THREAD

**Issue by ygoe** [aspnet/Mvc#8133]
#### Is this a Bug or Feature request?:

Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

Write a controller action that accepts the POST form data in a parameter of a structured type. Name the parameter `config` or `model`. Example:

```
[HttpPost]
public IActionResult Edit(EditViewModel model)
{
    // Inspect model contents here. It will be empty if the name is 'model'.
    // The data will be there is the parameter name is different.
}
```

#### Description of the problem:

When the action parameter name is called `model`, it receives absolutely no data at all. When it has any other name (I tried `config` and `viewModel`), then the form data correctly appears in the action argument.

I believe that the name of the method should be irrelevant. Since it is a complex type, it cannot be filled directly, and all its members should be considered individually instead. Naming the parameter `model` seems to prevent all this from happening.

Looking a bit closer, I found that the `EditViewModel` class contains a property named `Model`. The HTML form probably also has this field. So this might be the source of confusion. I still believe that complex types should not be filled directly but only their members instead. Controller actions will silently break if somebody adds a field to the class with the same name (case-insentitive) of the action parameter. And after all, this binding won't work anyway, as we can see here.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

Microsoft.AspNetCore.All 2.1.2

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/3735. The behavior is by design - however we're going to [try using an analyzer](https://github.com/aspnet/Mvc/issues/7753) to provide some tooling guidance in this scenario.
