### ISSUE TITLE
Is there a way to compile a razor view in code. As in System.Web namespace: BuildManager.CreateInstanceFromVirtualPath

### ISSUE THREAD

**Issue by joetherod** [aspnet/Mvc#8141]
Is there a way to compile a razor view in code. As in System.Web namespace: BuildManager.CreateInstanceFromVirtualPath?

Currently, our CMS manages creating pages for a site. We allow them to edit the razor views. We compile them to verify changes using BuildManager.CreateInstanceFromVirtualPath which is in the System.Web namespace.
Is there a similar library in aspnet core to do this and can be used in class library?

**Comment by Eilon** [comment]
We have a sample here, but it's a bit old: https://github.com/aspnet/Entropy/tree/master/samples/Mvc.RenderViewToString

@ajaybhargavb / @NTaylorMullen / @rynowak - do we have any updated guidance on this? Or is that sample still state of the art?

**Comment by NTaylorMullen** [comment]
The RenderViewToString sample is fine if you have a dependency on MVC. If you don't you'll need to look at running your Razor output through Roslyn. Here's how we do that in [MVC](https://github.com/aspnet/Mvc/blob/10ce77b9ca8435aead7369ff854a50fffbf4d235/src/Microsoft.AspNetCore.Mvc.Razor/Internal/RazorViewCompiler.cs#L405).
