### ISSUE TITLE
Productize analyzer that complains if there's an explicit Modelstate.IsValid check for ApiController instances

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8146]
An analyzer + codefix exists in the experimental package - https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Analyzers.Experimental/ApiActionsDoNotRequireExplicitModelValidationCheckAnalyzer.cs. There's interest in productizing it.

**Comment by mkArtakMSFT** [comment]
@pranavkm, so the ApiController already does this for you, correct? So the intention here is to tell the customer that the additional check you have is unnecessary?

**Comment by pranavkm** [comment]
> So the intention here is to tell the customer that the additional check you have is unnecessary?

Yup
