### ISSUE TITLE
Need help!!

### ISSUE THREAD

**Issue by jcpc91** [aspnet/Mvc#8148]
#### Is this a Bug or Feature request?:
need help

#### Description of the problem:
i have this folders, paths in my proyect

**-wwwroot/**
**-pages/**
**--Administration/**
**---Curses/**
**----/Index.cshtml**
**---Oferts/**
**----/Index.cshtml**

i need generate an anchor in pages/Curses/Index.cshtml like this

```html
<a href="../Administration/Oferts">Oferts</a>
```

i'm usin tag-helpr
 asp-page

i try this

```html
<a asp-page="../Oferts">Oferts</a>
<a asp-page="../Adinistrator/Oferts">Oferts</a>
<a asp-page="~/Adinistrator/Oferts">Oferts</a>
```

and doesnt work

thanks for u help!!
sorry bad inglish

**Comment by pranavkm** [comment]
`<a asp-page="../Adinistrator/Oferts">Oferts</a>`

Think you have a typo there, should be `<a asp-page="../Administrator/Oferts">Oferts</a>`
