### ISSUE TITLE
Changing parameter names in IParameterModelConvention

### ISSUE THREAD

**Issue by jacobslusser** [aspnet/Mvc#8155]
#### Is this a Bug or Feature request?:
Bug?

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Create a class that implements `IParameterModelConvention` and register the convention with MVC, e.g:
```cs
services.AddMvc(options =>
{
    options.Conventions.Add(new SnakeCaseParameterModelConvention());
});
``` 

#### Description of the problem:
Setting the `ParameterModel.ParameterName` property changes the name of the property as expected, however, breaks model binding.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.App v2.1

I'm attempting to use snake_case across the board on my APIs. One of the things I'm stuck on is getting things like query parameters to be snake_case publicly (e.g. `first_name`) but be normal C# camelCase in the app, (e.g. `firstName`). Changing the controller name works exactly as expected and doesn't break any of the model binding to the actual controller:

```cs
public class SnakeCaseControllerModelConvention : IControllerModelConvention
{
    public void Apply(ControllerModel controller)
    {
        controller.ControllerName = Utils.ToSnakeCase(controller.ControllerName);
    }
}

```
However, the same does not hold true for parameters. Changing their name breaks the model binding and values are no longer getting set., e.g. this does not work as expected:

```cs
public class SnakeCaseParameterModelConvention : IParameterModelConvention
{
    public void Apply(ParameterModel parameter)
    {
        parameter.ParameterName = Utils.ToSnakeCase(parameter.ParameterName);
    }
}
```

I'm under the impression this is the right place to make that kind of change, however, if there is a better place please let me know.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @shanselman.
@pranavkm, can you please look into this? Thanks!

**Comment by jacobslusser** [comment]
I was able to get the behavior I was hoping for by changing my code to the following:

```cs
public void Apply(ParameterModel parameter)
{
    parameter.BindingInfo.BinderModelName = Utils.ToSnakeCase(parameter.ParameterName);
}
```
Apparently, it is either the `BindingInfo.BinderModelName` or the `ModelMetadata.BinderModelName` property that must be set.

Is there a preference for one of the other? Why two locations?

The properties are read from here and here:

[https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Internal/DefaultModelBindingContext.cs#L225](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Internal/DefaultModelBindingContext.cs#L225)

[https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L241](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ParameterBinder.cs#L241)

Please confirm this is the correct location I should be modifying?

If so, I think the documentation and consistency of "conventions" could be improved. The documentation states that the `ControllerModel.ControllerName` property influences the model binding of a controller -- which is true, but the same is not true of `ParameterModel.ParameterName`. See:

[https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.1#conventions](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.1#conventions)

**Comment by jacobslusser** [comment]
I'm going to assume I answered my own question and close this.
