### ISSUE TITLE
MeidaType's subtype with suffix should be a subset of a subtype without suffix

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#8156]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Add the following 2 tests to the `IsSubsetOf_ReturnsTrueWhenExpected` test in `Microsoft.AspNetCore.Mvc.Formatters.MediaTypeTest` and they fail
```c#
[InlineData("application/json", "application/vnd.restful+json")]
[InlineData("application/json", "application/problem+json")]
```
#### Description of the problem:
According to https://tools.ietf.org/html/rfc6839#section-2, content like `application/problem+json` should be able to be processed as though its `application\json` too, but currently we don't consider `application/problem+json` as a subtype.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.3 and latest

**Comment by Eilon** [comment]
Tagging @dougbu and @jkotalik who I think both have a great deal of knowledge on this matter.

**Comment by dougbu** [comment]
@kichalla and I discussed this, reviewed the spec(s), and I agree it's a bug.

**Comment by jkotalik** [comment]
I can take this one if we just need to get it in preview-1. Would this apply to both MediaTypeHeaderValue and MVC's MediaType?

**Comment by jkotalik** [comment]
I'll go ahead and assign myself to both. I'll crunch them out when I have a spare moment in the next week.
