### ISSUE TITLE
Model binding of datetime set value of Date  field to NULL if date is more than the 12th day of the month.

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8159]
_From @nabinkjha on July 26, 2018 10:40_

 When any datetime field is posted the datetime always remains as mm/DD/yyyy format.
The **startup.cs** file contains the following code.

```c#
public CultureInfo EnGbCulture = new CultureInfo("en-GB");
 public void ConfigureServices(IServiceCollection services)
        {
 services.Configure<RequestLocalizationOptions>(options =>
            {
               options.DefaultRequestCulture = new RequestCulture(EnGbCulture);
                options.SupportedCultures = new List<CultureInfo> { EnGbCulture };
            });
        }
  public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            CultureInfo.DefaultThreadCurrentCulture = EnGbCulture;
            CultureInfo.DefaultThreadCurrentUICulture = EnGbCulture;
            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture(EnGbCulture),
                // Formatting numbers, dates, etc.
                SupportedCultures = new List<CultureInfo> { EnGbCulture },
                // UI strings that we have localized.
                SupportedUICultures = new List < CultureInfo > { EnGbCulture },
                RequestCultureProviders = new List<IRequestCultureProvider>
                    {
                    new QueryStringRequestCultureProvider { },
                    new CookieRequestCultureProvider { },
            },
            });
}
```

_Copied from original issue: aspnet/Home#3359_

**Comment by Eilon** [comment]
@nabinkjha how was the data posted? In the form? Query string? Can you show the model type, MVC controller action, and the CSHTML view code as well?

**Comment by nabinkjha** [comment]
The data is send using GET method of the jquery ajax. There is SearchPersonModel binded in the view. The datetime field is correct in query string but model fails to convert the datetime in dd/MM/yyyy . It works fine in form submit and ajax POST, but for ajax GET method the model always keep the datetime in US format. 
The hack code I have used is as follows

 **public async Task<IActionResult> Search(PersonSearchModel model)
        {
            DateTime dateOfBirth;
            DateTime.TryParse(Request.Query["DateOfBirth"].LastOrDefault(),out dateOfBirth);
            model = InitializeModel(model);
            if (model.DateOfBirth != dateOfBirth&& dateOfBirth != DateTime.MinValue)
            {
                model.DateOfBirth = dateOfBirth;
            }
            var result = await _customerApiClient.GetPersons(model);
            PopulateValuesFromLookup(result);
            return PartialView(result);
        }**

**Comment by mkArtakMSFT** [comment]
Hi @nabinkjha.
Please provide us with a repro project, so we can investigate this. Thanks!

**Comment by nabinkjha** [comment]
https://github.com/nabinkjha/DateTimeLocalization/tree/master/GetSearchDemo

The demo project is very simple and it just tell the user what values are selected for search. The DateOfBirth value always get updated to mm/DD/yyyy format and hence when the user type 13/01/2012 it becomes NULL.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by TechLearner2** [comment]
@ryanbrandenburg  Is there any update on this ?

**Comment by ryanbrandenburg** [comment]
Sounds like you want a custom model binder. An example like [this](https://gist.github.com/vickramravichandran/f06d63bfb50f27e6549978b7538d214c) might be overkill for your case, but I think it shows the general idea of what you want to do well. You would probably want to bind on `bindingContext.ModelTYpe.GetProperty(modelName)` instead of `bindingCOntext.ActionContext.ActionDescriptor.Parameters` though.

Another thing to consider is if you want to handle that kind of type conversion on the UI side or the server side. You'll need some way of informing your users of the expected format in order to avoid them thinking 1/2/1989 is February 1st (or vice versa.).

Does that answer your question?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by nabinkjha** [comment]
Hi,
Thanks for the answer. It seems that the model binding for GET will only work when the date time is in US format and for all other cultures bespoke code has to be written to get the DATE in correct format for GET (POST works fine) method.

**Comment by jgoyvaerts** [comment]
@ryanbrandenburg can you explain the reasoning why the datetime parsing in a query only parses yyyy/mm/DD or mm/DD/yyyy dates, and doesn't parse DD/mm/yyyy correctly even when all cultures are correctly set?

Is there a configuration you can change which changes the default parsing from US parsing to something else?

And yes, I'm aware of the ability to create custom model binders, just wondering why the default is like it is

**Comment by ryanbrandenburg** [comment]
@jgoyvaerts if you still have concerns in this area feel free to open a new issue. Your comments are likely to get missed or lost track of if you make them on closed issues.
