### ISSUE TITLE
Razor Pages not generating appropriate anchor tags

### ISSUE THREAD

**Issue by bdparrish** [aspnet/Mvc#8165]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
https://github.com/bdparrish/razor-pages-bug

#### Description of the problem:
There seems to be an issue with the application finding all of the razor pages in the project.  It cannot find some available files under `/Pages`.

I am attempting to create a simple web application using razor pages. The rendered anchor tag for Create does not seem to be built correctly.

`<a href>Create</a>`

My application seems to not have `/Facility/Create` as a valid url even if I manually go there. Is there something else that I am suppose to be doing to get the anchor tag to render as `<a href="/Facility/Create">Create</a>` and for the application to know about `/Facility/Create`.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
=== Visual Studio Community 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: 6079dd37-d7ed-472b-893a-55acfaeec1bf
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.7
	2.0.5
	2.0.4
	2.0.0
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.200
	2.1.105
	2.1.4
	2.1.3
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: Not found

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 21 20:07:39 PDT 2018
    root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64

**Comment by bdparrish** [comment]
I have been able to get past this.  I renamed the `/Facility` directory to `/Facilities` and everything is working as advertised.  It looks like because I had a folder with the same name as a model that it was not parsed correctly by razor pages?  Does that make sense?

**Comment by mkArtakMSFT** [comment]
Hi @bdparrish.
Glad that you've found solution to the problem you've been facing.
@pranavkm, do we have a convention which may result in the observed behavior?

**Comment by bdparrish** [comment]
@pranavkm - So that seems to have fixed it, but why the silent error?  Is there something I can do to make it so I know if the compiler is complaining about something like that?  It seems very silent.  All I see is that my links are not being created but I don't know why?

**Comment by pranavkm** [comment]
There's planned work for 2.2.0 to add an option to routing that would flag complain when it encounters a scenario like this. Here's the issue - https://github.com/aspnet/Routing/issues/553.

**Comment by bdparrish** [comment]
@pranavkm - since you pointing out the parsing error.  I have gone back to some other oddities.  It also fails silently when I was converting MVC to Razor Pages...

```html
<a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
```

converted

```html
<a asp-page="Edit" asp-route-id="@item.Id">Edit</a>
```

if you miss the `asp-page` attribute conversion, then it will not complain, but it will just not create a proper `href` attribute in the anchor tag.

**Comment by pranavkm** [comment]
Right - all of these are the same class of behavior with routing in 2.1.0 or lower. Link generation in routing attempts to match these constraints (`Action=Edit`, `Id={Some Number}`) to a route. It silently falls back to an empty string when no route matches. The goal of the linked issue is to produce better diagnostics for these scenarios.
