### ISSUE TITLE
[Feature request] Required attribute and empty collections

### ISSUE THREAD

**Issue by ZBAGI** [aspnet/Mvc#8169]
In `RequiredAttribute`, empty string are treated as missing data however empty collections are allowed. Is there a reason for that ? There should be `AllowEmptyCollections` besides `AllowEmptyStrings`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ZBAGI.
@dougbu, can you please answer this question? Thanks!

**Comment by dougbu** [comment]
@ZBAGI `[Required]` is not part of ASP.NET Core. Instead it comes from the underlying framework -- .NET Framework or .NET Core. I suggest making your request in the [dotnet/corefx](https://github.com/dotnet/corefx) repo.

FYI the source for this attribute is [here](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/RequiredAttribute.cs).

**Comment by dougbu** [comment]
Marking this as `external` and closing.
