### ISSUE TITLE
Documentation of `RefreshSignInAsync` is misleading

### ISSUE THREAD

**Issue by Whathecode** [aspnet/Mvc#8172]
#### Is this a Bug or Feature request?:
This is a documentation bug report, in the sense that the [`SignInManager.RefreshSignInAsync` documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.signinmanager-1.refreshsigninasync?view=aspnetcore-2.1) is highly misleading.

#### Description of the problem:
The current documentation on this method states:

> Regenerates the user's application cookie, whilst preserving the
> existing AuthenticationProperties like rememberMe, as an asynchronous
> operation.
>
> Parameters
> **user** The user whose sign-in cookie should be refreshed.

This has [lead me](https://stackoverflow.com/q/51571852/590790) and at least [one other user](https://stackoverflow.com/q/45347956/590790) down the wrong path, in that we believed we could pass a different user than the currently logged in user to this method in order to refresh their claims (i.e., next time they perform a request). Instead, what happens is the currently logged in user becomes logged in as this other user which was passed to `RefreshSignInAsync`.

I read the documentation prior to using this call, but could not derive from the current documentation this is what would happen (and I still cannot).

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.All

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Whathecode.
@javiercn, can you please review the current documentation and see what kind of changes are required there? Thanks!

**Comment by javiercn** [comment]
@haok as he’s the owner

**Comment by HaoK** [comment]
@blowdart can you move this issue over to the identity repo?

**Comment by blowdart** [comment]
This issue was moved to aspnet/Identity#1900

**Comment by javiercn** [comment]
Closing this one as there’s no further action to be taken here.
