### ISSUE TITLE
FlakyTest: ExecuteAsync_ErrorDuringSerialization_DoesNotCloseTheBrackets

### ISSUE THREAD

**Issue by jkotalik** [aspnet/Mvc#8175]
https://ci3.dot.net/job/aspnet_Mvc/job/release_2.2/job/windows-Configuration_Release_prtest/187/console

**Comment by pranavkm** [comment]
cc @kichalla

**Comment by Eilon** [comment]
@mkArtakMSFT - please assign ASAP.

**Comment by kichalla** [comment]
Discussed with @jkotalik. He ran into this issue while running the build locally. Looking at CI history this test never failed, so I am going to close this

![image](https://user-images.githubusercontent.com/6559784/43477744-d2cce190-94b0-11e8-9745-04afe944ad01.png)

**Comment by pranavkm** [comment]
This test, or another variant, seem to fail very consistently on VSTS. E.g.

* https://dotnet.visualstudio.com/public/_build/results?buildId=9312&view=logs
* https://dotnet.visualstudio.com/public/_build/results?buildId=8283&view=logs

Might need some more investigation

**Comment by kichalla** [comment]
Thanks @pranavkm ...reopening it
