### ISSUE TITLE
BindRequired doesn't work for arrays

### ISSUE THREAD

**Issue by StevenLiekens** [aspnet/Mvc#8180]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Create a controller action that expects an array of values FromQuery.
Slap a `BindRequired` attribute on the array param.

```csharp
[HttpGet("todos")]
public ActionResult<string[]> GetTodosOnDays([BindRequired, FromQuery] string[] days)
{
    if (!ModelState.IsValid)
    {
        return BadRequest(ModelState);
    }
    return TodosApi.GetTodosOnDays(days);
}
```

Example usage for the happy path:
```
GET http://localhost:5000/todos?days=Friday&days=Saturday

200 OK

[ "work hard", "party hard" ]
```

#### Description of the problem:

Doing a GET without a query string doesn't invalidate `ModelState`

`GET http://localhost:5000/todos`

```csharp
[HttpGet("todos")]
public ActionResult<string[]> GetTodosOnDays([BindRequired, FromQuery] string[] days)
{
    // days.Length == 0
    // ModelState.IsValid == true
    if (!ModelState.IsValid)
    {
        // never reached
        return BadRequest(ModelState);
    }
    // crash
    return TodosApi.GetTodosOnDays(days);
}
```

Expected result:

```
400 Bad Request

{
    "days": [
        "A value for the 'days' property was not provided."
    ]
}
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @StevenLiekens.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
@StevenLiekens please provide your `Startup` class. I suspect `MvcOptions.AllowValidatingTopLevelNodes` is `false`.

And, to confirm: You're not seeing anything unexpected on the happy path?

**Comment by StevenLiekens** [comment]
I can provide my startup class but not until tomorrow.

For now all I can tell you is that BindRequired does work for simple types like string. Does that give you any new insight?

**Comment by dougbu** [comment]
> Does that give you any new insight?

Yes, you're hitting one of the MVC quirks: The `CollectionModelBinder` and its subclasses (including the `ArrayModelBinder`) create default / empty collections when no data is available for type-level models such as a parameter. This happens long before `ParameterBinder` checks `ModelMetadata,IsBindingRequired`.

Put another way, `[BindRequired]` would work as intended with non-collection top-level models or with properties within that model.

I'll chat with a few people here about whether `CollectionModelBinder` should honour `ModelMetadata,IsBindingRequired` when `MvcOptions.AllowValidatingTopLevelNodes` is set.

**Comment by StevenLiekens** [comment]
Ok ok thanks for the clear explanation.

> whether CollectionModelBinder should honour ModelMetadata.IsBindingRequired

Well according to the docs, yes.
> If true then the model value is considered required by model binding and must have a value supplied in the request to be considered valid.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.modelmetadata.isbindingrequired?view=aspnetcore-2.1#Microsoft_AspNetCore_Mvc_ModelBinding_ModelMetadata_IsBindingRequired

**Comment by dougbu** [comment]
FYI the fix we discussed is to change `CollectionModelBinder` and `ComplexTypeModelBinder` to special-case the combination of `bindingContext.IsTopLevelObject`, `MvcOptions.AllowValidatingTopLevelNodes` and no available data. When in that situation, the binders should add a `ModelStateError` but otherwise behave as they do today i.e. still otherwise appear to bind successfully and ensure action parameters remain non-`null`.

**Comment by dougbu** [comment]
**@** **Triage** I'm costing this larger than XS only because we lack realistic tests of `[BindRequired]` on top-level collections and complex types.

**Comment by StevenLiekens** [comment]
I guess another workaround is to make the array a property of a complex type?

```csharp
public class StringArrayDto
{
    [BindRequired]
    string[] values { get; set; }
}
```

```csharp
public ActionResult<string[]> GetTodosOnDays([ FromQuery] StringArrayDto days);
```

```
GET http://localhost:5000/todos?days.values=Friday&days.values=Saturday
```

(Not tested)

**Comment by dougbu** [comment]
@StevenLiekens yes, that should work fine. It requires changing your actions and models but that's not as messy as my second suggestion. I prefer checking `days.Length == 0` but it's just a preference.

**Comment by dougbu** [comment]
@mkArtakMSFT @danroth27 what is the priority of this fix?

**Comment by dougbu** [comment]
5c8dfef15e

**Comment by StevenLiekens** [comment]
Thanks
