### ISSUE TITLE
Referencing a class library with precompiled views as a DLL

### ISSUE THREAD

**Issue by svallis** [aspnet/Mvc#8181]
Is this scenario supported? I expected things to "just work", but have run into some issues trying to link to pages within an embedded MVC area in a class library.

I've set things up with a test MVC project `Master`, one library `Lib1` which is referenced normally, and one library `Lib2` which is referenced using a `HintPath` to the DLL. The actual referencing is working fine and I can see both libraries from the application, but trying to link to an MVC view in `Lib2` doesn't work.

An excerpt from the `Master.csproj` (I wasn't sure if it was necessary to reference the `.Views.dll` manually - tried it both ways to no avail):

```
  <ItemGroup Label="Internal References">
    <ProjectReference Include="..\Lib1\Lib1.csproj" />
  </ItemGroup>

  <ItemGroup Label="External References">
    <Reference Include="Lib2">
      <HintPath>..\..\External\Lib2\bin\Debug\netcoreapp2.1\Lib2.dll</HintPath>
    </Reference>
    <Reference Include="Lib2.Views">
      <HintPath>..\..\External\Lib2\bin\Debug\netcoreapp2.1\Lib2.Views.dll</HintPath>
    </Reference>
  </ItemGroup>
```

The code in both libraries (which use `Microsoft.NET.Sdk.Razor` as their SDK) is identical except for the names `Lib1` and `Lib2`:

```
using System;
using Microsoft.AspNetCore.Mvc;

namespace Lib1.Areas.Lib1.Controllers
{
    [Area(nameof(Lib1))]
    [Route("[area]/[controller]/[action]")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}
```

And the links are being written out using the built in tag helper:

```
<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
<li><a asp-area="Lib1" asp-controller="Home" asp-action="Index">Lib1</a></li>
<li><a asp-area="Lib2" asp-controller="Home" asp-action="Index">Lib2</a></li>
```

And this outputs the following markup to the browser:

```
<li><a href="/">Home</a></li>
<li><a href="/Lib1/Home/Index">Lib1</a></li>
<li><a href="/?area=Lib2">Lib2</a></li>
```

It looks like the application is simply not discovering the routes that should be exposed by `Lib2`. Switching `Lib2` to use the `ProjectReference` style reference makes it immediately start working, so it seems there's nothing wrong with the code or the library itself - just the way it's being referenced.

**Comment by pranavkm** [comment]
> Switching Lib2 to use the ProjectReference style reference makes it immediately start working

That's the intended design. MVC's startup specifically looks for controllers in assemblies that reference one of MVC's packages (directly or transitively). References to binaries on disk do not contain this information. You could possibly add these [assemblies as application parts](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/ApplicationPartManager.cs#L61-L65) but I'd recommend using a project reference.

**Comment by svallis** [comment]
Thanks for the quick answer @pranavkm. What's the suggested method of manually distributing a binary library containing embedded views, or is this just not a supported scenario?

**Comment by pranavkm** [comment]
NuGet packages work really well for this. Executing `dotnet pack` on a project would retain details of a project's dependencies in the nuspec that MVC can use.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
