### ISSUE TITLE
Flaky test: OnProvidersExecuting_CachesEntries

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#8186]
This test [fails](http://aspnetci/viewLog.html?buildId=520779&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:
```
System.BadImageFormatException : The signature is incorrect.
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
@mkArtakMSFT please assign.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
Issue with Moq - https://github.com/castleproject/Core/issues/193. Using https://github.com/aspnet/Mvc/issues/8157 to track upgrading the dependency.

**Comment by ryanbrandenburg** [comment]
If this is an ongoing issue you're better off leaving this issue open and marking it as blocked. If you close it and it fails again the bot is just going to open up a new issue.

**Comment by pranavkm** [comment]
Assigning to @dougbu. This can be closed when https://github.com/aspnet/Mvc/issues/8157 is fixed.

**Comment by dougbu** [comment]
Closing as the upgrade (aspnet/AspNetCore@904c9d3623) more than two weeks ago seems to have cleared all similar failures.
