### ISSUE TITLE
Attribute Routing: Resolve Name + Token Replacement

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#819]
Consider the following:

```
[Route("Products/[action]", Name = "Products")]
public class ProductsController
{
    public void Add() { }
    public void Buy() { }
}
```

This will fail because it creates two routes with the same name. We need to come up with something for this scenario.

**Comment by kirthik** [comment]
Fix checked in - 9d2b1822d9e93bf74e3f1df8096b6bb2d6d43371
