### ISSUE TITLE
Can't build the raw source code of mvc release 2.2

### ISSUE THREAD

**Issue by nicholasyin** [aspnet/Mvc#8196]
Just downloaded the latest 2.2 release mvc source code but can't build anyway, without any code modification. The error turns out to be the loading of project 'RazorPagesClassLibrary', as shown here:

![image](https://user-images.githubusercontent.com/17007651/43565084-0893ff50-965c-11e8-9fdc-091120038759.png)

**Comment by nicholasyin** [comment]
In case interested, here's the VS About:

![image](https://user-images.githubusercontent.com/17007651/43565154-5082a564-965c-11e8-8cb0-350e72d6e01e.png)

**Comment by AlexejTimonin** [comment]
Hello, did you follow the building from source [instructions](https://github.com/aspnet/Home/wiki/Building-from-source)?

**Comment by pranavkm** [comment]
Seems like an issue with VS installation. I'd recommend trying out some of the suggestions from https://stackoverflow.com/questions/49432666/project-file-is-incomplete-expected-imports-are-missing

**Comment by nicholasyin** [comment]
@AlexejTimonin Following the link you provided seemed to solve my issue. One more thing about a successful build, for me, is I had to turn off the windows defender real-time protection during the build time in order to let it sign using some public key.
