### ISSUE TITLE
Route pattern matching issue on route '/r{token}' or simillar

### ISSUE THREAD

**Issue by pikax** [aspnet/Mvc#8197]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
create a new dotnet project
`dotnet new webapi`

go to the Controller/ValuesController and add the action

``` C#
        [Route("/r{token}")]
        public string Test(string token)
        {
            return token;
        }
```
debug and go to:
`https://localhost:44325/rRR` 

The action is not executed, but it works with /r**test**
It seems if you add the same starting character(**r**) in the middle of the **{token}** it fails to match the route.

``` C#
       [Route("/i{token}")]
        public string Test2(string token)
        {
            return token;
        }

// https://localhost:44325/iteIst doesn't work
```

#### Description of the problem:
Route matching issue.  (see the code example above)

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @pikax.
@kichalla, can you please look into this? Thanks!
/cc @rynowak, @JamesNK

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Routing#733
