### ISSUE TITLE
ActionConstraints added to PageRouteModel.SelectorModel do not get copied to the action descriptor

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8207]

**Comment by dougbu** [comment]
@pranavkm what is the impact of these particular `ActionConstraint`s not being copied to the `ActionDescriptor`?

**Comment by pranavkm** [comment]
You can't write a convention that adds constraints, for instance - https://github.com/aspnet/Entropy/pull/282/files#diff-968c24dbacefec17f9577c9a54289aaeR28
