### ISSUE TITLE
WebApi: errors added in action filters don't trigger 400 error

### ISSUE THREAD

**Issue by Spaier** [aspnet/Mvc#8222]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
```cs
    [Route("api/[controller]/[action]")]
    [Produces("application/json")]
    [ApiController]
    public class SampleController : ControllerBase
    {
        [AddSampleError]
        public ActionResult Api1()
        {
            return NoContent();
        }
    }

    public class AddSampleErrorAttribute : ActionFilterAttribute
    {
        public override Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
        {
            context.ModelState.AddModelError("sample-error", "Sample Error");
            return base.OnActionExecutionAsync(context, next);
        }
    }
```

repro: [repository](https://github.com/Spaier/action-filter-errors-are-ignored-repro)

#### Description of the problem:
Errors added in action filters are ignored by automatic model validation.
Model state isn't valid, but 204 code is returned instead of 400.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`: 2.1.2

**Comment by pranavkm** [comment]
`ModelStateInvalidFilter` that produces the bad request is a global action filter that runs before your action filter. Consider using a resource filter instead to do model validation.

**Comment by Spaier** [comment]
@pranavkm, Thanks for your help. My attribute changes `ActionArguments` so instead, I set `Order` to `-2001`.
