### ISSUE TITLE
ActionResults Returned formatters and contentTypes rendered as JSON

### ISSUE THREAD

**Issue by rodolfocop** [aspnet/Mvc#8229]
#### Question:
Hi, I have a question, I have json that return in my controllers API  returning with the object always the following extra lines.

I need to just send the value, without these parameters and without my JSON.

### **Actual results**
```
{
   "value": [
            {
                "id": 10101010,
                "arq_tipe": "pdf",
                "acess_code": "LW00848834LPTLWLPT"
            }
        ],
    "formatters": [],
    "contentTypes": [],
    "declaredType": null,
    "statusCode": 200
}
```

### **Expected results**

```
{
		[
            {
                "id": 10101010,
                "arq_tipe": "pdf",
                "acess_code": "LW00848834LPTLWLPT"
            }
		]
}

```
### **I found a way to do that filter**

```
public class Fix4960ActionFilter : IActionFilter
{
    public void OnActionExecuting(ActionExecutingContext context) { }

    public void OnActionExecuted(ActionExecutedContext context)
    {
        var objectResult = context.Result as ObjectResult;
        if (objectResult?.Value is IActionResult)
        {
            context.Result = (IActionResult)objectResult.Value;
        }
    }
}
```
There is a better way?

[Same Problem ](https://github.com/aspnet/Mvc/issues/4960)

**Comment by pranavkm** [comment]
@rodolfocop could you share a repro app?

**Comment by rodolfocop** [comment]
@pranavkm I can not share a repository because it is an institutional project. 
I was able to solved with filter. 
However resolve in my 
services.ConfigureMVC();
With this, 
```
services.AddMvc(options =>
{
   options.OutputFormatters.Remove(new XmlDataContractSerializerOutputFormatter());
   options.UseCentralRoutePrefix(new RouteAttribute("api"));
IncludeRequestBody = true, IncludeHeaders = true });
   }).AddJsonOptions(options =>
   {
       options.SerializerSettings.Formatting = Formatting.Indented;
       options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
   });

```
 [But this problem is identical to what I have](https://github.com/aspnet/Mvc/issues/4960)

**Comment by pranavkm** [comment]
I'm not seeing this with a 2.1 app. This works correctly in a 2.1 app and that's the scenario for the issue you linked:

```C#
public object Get(int id)
{
    return new ObjectResult("value");
}
```

The only scenario I can think of that could cause you to return the `ObjectResult` rather than the value of it was it if were wrapped in `ActionResult<>` which is not supported. E.g. 

```C#
public ActionResult<ObjectResult>> Get(int id)
{
    return new ObjectResult("value");
}
```

Feel free to reopen the issue if you have a sample repro for this. You're welcome to start with a brand new application and update it to reproduce the issue. The filter is a reasonable workaround if you continue seeing this but aren't able to provide a repro app.

**Comment by rodolfocop** [comment]
Hi, @pranavkm thanks for the reply.
But this solution does not solve my question, once I get a repo I will reopen the question
Thanks for everything.
