### ISSUE TITLE
Can RazorPages and razor be used in a project at the same time?

### ISSUE THREAD

**Issue by ghd258** [aspnet/Mvc#8232]
Can RazorPages and razor be used in a project at the same time?

Are there any examples of whether RazorPages or razor can be used in a project at the same time?

**Comment by mkArtakMSFT** [comment]
Hi @ghd258.
Yes, that is absolutely possible. Feel free to check out the documentation at: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio
