### ISSUE TITLE
TempData not working if UseCookiePolicy placed before UseMvc

### ISSUE THREAD

**Issue by hmdhasani** [aspnet/Mvc#8233]
After Migrating to ASP Core 2.1 TempData not working and was always null after working for a day around this finally I find the reason:

in Startup.Configure():
app.UseCookiePolicy(); should be after app.UseMVC();

This is unexpected and I did not find any document about it.
And in the migration documentation (https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#changes-to-startup) app.UseCookiePolicy(); is before app.UseMVC();

I think there must be some documentation about it (if it can not be fixed) so other people don't get encounter by this.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hmdhasani.
@kichalla, can you please look into this? If this is pure documentation issue, we may need to ask the owners of the `migration docs` to update those.

**Comment by kichalla** [comment]
I haven't seen reports like these before and imagine it would have broken for other folks too. 

@hmdhasani Could you share a standalone repro for this?

**Comment by hmdhasani** [comment]
OK, I have created an "ASP Net Core Web Application" and enabled TempData usage and Added a Default Controller for checking TempData
In Startup.cs I have moved app.UseCookiePolicy(); to 1 line before UseMVC() and TempData broke.
here it is:
https://github.com/hmdhasani/TempDataBug

you should see http://localhost:56356/Default/Index for testing.

**Comment by kichalla** [comment]
@hmdhasani Thanks for the repro. I looked at it and following would fix the problem you are seeing.

```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
    }

    app.UseCookiePolicy();

    app.UseSession();

    app.UseStaticFiles();

    app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "{controller}/{action}");
    });
}
```

**Comment by hmdhasani** [comment]
@kichalla  thanks for the response.
My main issue is how some one should know the "Right" Order .I searched for it but did not find any documentation about how to order middlewares right and had to test many orderings to get to the right ordering.
I think there should some explanation about middlewares ordering.
