### ISSUE TITLE
Keep the Value property when casting ObjectResult into ActionResult

### ISSUE THREAD

**Issue by dvoituron** [aspnet/Mvc#8235]
I'm creating a WebAPI, in ASP.NET Core 2.1, that returns a typed value (int in my example). To do this, I return a result using the **Ok(object)** method. This method returns an **ObjectResult** that is implicitly converted to **ActionResult<T>**.

The result of this conversion gives me an **ActionResult<T>** object with a **Result** property contains a reference to my **ObjectResult**, and with a **Value** property contains the value default(T) (zero in my case of using an integer).

```CSharp
[HttpGet()]
public ActionResult<int> GetMyNumber()
{
	var x = new ActionResult<int>(123);     // x.Value = 123; x.Result = null;
	var y = (ActionResult<int>)Ok(123);     // y.Value = 0;   y.Result.Value = 123;

	// Example of return where GetMyNumber().Value = 0
	return Ok(123);
}
```

My question is: **_Why the y.Value property does not also contain my data (123) also present in y.Result.Value?_**
During unit tests (among others), it is easier to recover the content of the **y.Value** property. Instead of checking which property contains a value.

If you find this interesting, you should adapt the **Microsoft.AspNetCore.Mvc.ActionResult<T>** class to add this implicit conversion method. It converts an **ObjectResult** by assigning the **Result** and **Value** properties.

```CSharp
// Class Microsoft.AspNetCore.Mvc.ActionResult<T>
public TValue Value { get; private set; }

public static implicit operator ActionResult<TValue>(ObjectResult result)
{
	return  new ActionResult<TValue>(result) { Value = result.Value };
}
```

CC @pranavkm

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dvoituron.
The behavior you're observing is by design.
The reason is because we don't special case simple types.
For your particular scenario (the unit test), you should already know what the value should return - hence you can just check for the `Result` property.

**Comment by dvoituron** [comment]
Thanks for your answer. I understand.  But this is not only valid for simple types. 123 is used for the example.

**Comment by mkArtakMSFT** [comment]
Sure 123 was an example.
Here is more context. The `Value` property your are looking for is defined on the `ObjectResult` and not the `ActionResult`. So we'll need to cast it to ObjectResult and assign then only assign the `Value`. All that adds up unnecessary complexity to the current implementation, which we think is not something of great value.

**Comment by dvoituron** [comment]
Yes, it's a choice.
That's not realy a problem... I've created an extension method to get the value. 

```
public static T GetValue<T>(this ActionResult<T> action)
        {
            if (action.Value != null)
                return action.Value;
            else
                return (T)Convert.ChangeType((action.Result as ObjectResult)?.Value, typeof(T));
        }
```
