### ISSUE TITLE
UrlHelperBase is not thread-safe

### ISSUE THREAD

**Issue by vdachev** [aspnet/Mvc#8244]
I'm not sure if it is a bug or an intended but the default implementation of `IUrlHelper` - [`UrlBuilder`](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/Routing/UrlHelper.cs) is not thread-safe and it doesn't seem to be mentioned explicitly in the documentation.

This seems to be due to the use of a shared `StringBuilder` in its base class [`UrlBuilderBase`](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/Routing/UrlHelperBase.cs).

We came across this issue when trying to project a `ParallelQuery` instance to a list of URLs to an `IEnumerable` of URLs.

Some of the ways to address this issue that come to my mind include:

- Introduce a lock on the `StringBuilder` in the `UrlBuilderBase`.
- Make the `GetStringBuilder` virtual and override it in a thread-safe implementation of the `IUrlHelper`.
.
- Point the fact the `UrlBuilder` is not thread-safe in the documentation.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @vdachev.
Making UrlBuilderBase thread safe was never a goal , hence the behavior you're describing here is by design.

**Comment by mkArtakMSFT** [comment]
As for documenting it, it would mean to add the same line of comment to the documentation for 95% of the classes in ASP.Net Core. Instead, sticking with the model of documenting only the thread-safe classes is much preferable.
/cc @rynowak
