### ISSUE TITLE
Remote Validation in Razor Pages

### ISSUE THREAD

**Issue by OrihuelaConde** [aspnet/Mvc#8245]
Is there a way to use Remote Validation in Razor Pages or I should create a controller for that purpose?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
/cc @NTaylorMullen

**Comment by OrihuelaConde** [comment]
Thank your for your reply, but If the answer to my question is "No" then it is a feature request.

**Comment by NTaylorMullen** [comment]
I assume what you mean by remote validation is to validate content on the server. If that's the case you'll need to create a control or API of somesort and pass the bits you want to validate to it.

**Comment by NTaylorMullen** [comment]
You might be able to make it work in a RazorPage handler if you return the same bits as mentioned here https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.1#remote-validation

**Comment by OrihuelaConde** [comment]
@NTaylorMullen I've tried with a Razor Page Handler but the atribute [Remote] need a controller. When I pass a Page Model it generate an IO exception saying that can't find the controller, indeed, because it is a Page Model.
I solved this with an API controller but for the proposse of Razor Page it is not feasible. The [Remote] atribute should work with a Page Model Handler.

**Comment by NTaylorMullen** [comment]
Thanks for giving that a try @OrihuelaConde! I feel as though this is definitely a bug then. I'll mark it as so and let the higher powers decide if it's something we want to tackle 😄

**Comment by mkArtakMSFT** [comment]
@OrihuelaConde, would you be interested in sending us a PR for this?
