### ISSUE TITLE
Does using _viewstart.cshtml to set layout pages *and* @inject properties make sense

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#825]
In MVC5 the `_viewstart.cshtml` file was executed only for "full" views and never for partial views. This was important because `_viewstart.cshtml` is used most often to set common layout pages for a folder of views. And, of course, partial views generally don't use layout pages (they *can*, but rarely do).

As I was logging https://github.com/aspnet/Mvc/issues/824 I got to thinking about the new design of `_viewstart.cshtml` because mixing the settings for layout pages and the new DI property `@inject` feature doesn't sound entirely right to me because of the partial page issue.

In MVC 5 there were two slightly distinct concepts: views (which have `_viewstart.cshtml`), and partial views (which have nothing).

@pranavkm @yishaigalatzer @davidfowl @lodejard

**Comment by yishaigalatzer** [comment]
Can you please set up the design discussion for this?

**Comment by pranavkm** [comment]
### Design discussion notes

* Introduce a new file _GlobalImport.cshtml. Directives from this file are implicitly included to all views that are within its folder hierarchy (same hierarchy behavior as _ViewStart \ web.config).
* _ViewStart does what it does in Mvc 5 (does not push directives). Does not run before Partials \ Layouts.
* Remove @Layout directive
