### ISSUE TITLE
URL rewrite doesn't work for non-regex

### ISSUE THREAD

**Issue by lonix1** [aspnet/Mvc#8254]
ASP.NET Core 2.1 (2.1.302)

I want to rewrite `/favicon.ico` to `/images/favico.ico`.

So I [followed the docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting#regex-examples) and did this in `Startup.cs` at the end of `Configure()` (after `app.UseMvc()`, I hope that's correct?):

````csharp
app.UseRewriter(new RewriteOptions()
  .AddRewrite("favicon.ico", "images/favicon.ico", skipRemainingRules:true));
````

But that gave me a 404.

So I thought maybe I need to use a dummy regex:

````csharp
app.UseRewriter(new RewriteOptions()
  .AddRewrite("^(favicon.ico)$", "images/favicon.ico", skipRemainingRules:true));
````

And that also gave me a 404.

This was confirmed by [other people](https://stackoverflow.com/questions/51787969/url-rewriting-in-asp-net-core-2-1-without-regex) on SO, so it's either a bug, or the documentation is wrong (in which case please correct me).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @lonix1.
Please provide us with a minimalistic repro project so we can investigate the issue.

**Comment by kichalla** [comment]
cc @jkotalik

**Comment by jkotalik** [comment]
Seems like a bug, will look into it in the 2.2 timeframe.

**Comment by mkArtakMSFT** [comment]
@jkotalik, should this be moved to a different repo?

**Comment by jkotalik** [comment]
Home with the tag BasicMiddleware.

**Comment by jkotalik** [comment]
Oops: just BasicMiddleware.

**Comment by gsdnano** [comment]
This can be reproduced by taking the example at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-2.1&tabs=aspnetcore2x and commenting out the app.Run command at the end of the Configure function. The url rewrite example will then 404 no matter the replacement url. This is using core 2.1 and Microsoft.AspNetCore.Rewrite 2.1.1.

**Comment by lonix1** [comment]
Once this bug is resolved, please also give us some guidance (or better yet, update the docs) about the implications of putting this before/after/between `app.UseStaticFiles()` and `app.UseMvc()`, or whether it should be at the beginning/end of `Configure()` i.e. the beginning/end of the pipeline.

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/BasicMiddleware#355
