### ISSUE TITLE
MemoryPoolViewBufferScope Dispose result in System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by werynguyen** [aspnet/Mvc#8260]
#### Is this a Bug or Feature request?:
Seem like a bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
After migrating our high traffic aspnetcore app to Core 2.1.2, we start receiving this error
```
System.ArgumentNullException: Value cannot be null.
Parameter name: array
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Return(T[] array, Boolean clearArray)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.MemoryPoolViewBufferScope.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesFeature.Dispose()
   at Microsoft.AspNetCore.Http.HttpResponse.<>c.<.cctor>b__30_1(Object disposable)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FireOnCompletedAwaited(Stack`1 onCompleted)
```
#### Description of the problem:
This happen about once every 5000 requests and very intermittently. We thought that this could be a concurrency locking issue as it always happens in pair but recently one of our apps report this error not in pair.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

```
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Antiforgery" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Redis" Version="0.4.1" />
```

We run on our app in docker container using microsoft/dotnet:2.1.2-aspnetcore-runtime-stretch-slim as base image.

Could anyone please suggest if you have any clue on why this happen?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @werynguyen.
@pranavkm, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
@werynguyen, In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by pranavkm** [comment]
@werynguyen, are you attempting to render the a single view instance in parallel? That might be one way you'd get in to this situation. That said, a repo app would certainly help.

**Comment by werynguyen** [comment]
@pranavkm Thank for the suggestion, yes, we are using a custom code to render view into string and return this as html content in json format. Our render to string method is similar to the one on this post by [ppolyzos](https://ppolyzos.com/2016/09/09/asp-net-core-render-view-to-string/). I will create a repo to illustrate how this is done in our project.

**Comment by pranavkm** [comment]
@werynguyen it's likely that you're running in to the same sort of issue as https://github.com/aspnet/Mvc/issues/5106. It's likely that you're re-using the equivalent of `IViewRenderService` (from the post) across multiple scopes which is something that type isn't designed to support. If you're using the rendered in a controller, ensure it's registered as a scoped service. If you're consuming it in code outside of the context of a HTTP request, you have to create a scope and resolve the service from it: https://github.com/aspnet/Entropy/blob/master/samples/Mvc.RenderViewToString/Program.cs#L41-L57

Feel free to reopen this issue if you'r still seeing the issue and have a sample that you could share.
