### ISSUE TITLE
Razor Pages intellisense for Static Files outside wwwroot

### ISSUE THREAD

**Issue by tb-mtg** [aspnet/Mvc#8261]
Is it possible to still have intellisense in razor pages (.cshtml) if I add another static file provider as shown below.  Currently intellisense only show files inside wwwroot.

> app.UseStaticFiles(new StaticFileOptions()
> {
>     FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "MyPages")),
>     RequestPath = "/MyPages"
> });

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen can you please answer this question? Thanks!

**Comment by NTaylorMullen** [comment]
@tb-mtg, it's definitely not possible via the Startup class. It might be possible via another tooling configuration however. @madskristensen do you happen to know if there's a tooling configuration approach that lets you configure additional static file intellisense?

**Comment by madskristensen** [comment]
@NTaylorMullen I'm not aware of that, but @BillHiebert might know?

**Comment by BillHiebert** [comment]
You can tell VS which folder to use by setting the WebRootFolder property in the csproj project file. 

`<WebRootFolder>MyPages</WebRootFolder>`

**Comment by danroth27** [comment]
Why would you make your Razor Pages (.cshtml files) available as static files?

**Comment by tb-mtg** [comment]
I don’t want to particularly make .cshtml files available as static, more want the razor page specific stylesheets & javascripts (.css & .js) file types stored in the same location under the pages folder rather than having to replicate the same folder structure under wwwroot.

For example:

\Pages\About.cshtml
\Pages\About.cshtml.cs
\Pages\About.js
\Pages\About.css

I know I could put these in inline <style> & <script> tags inside the .cshtml file but I thought the best practice is to have separate files for these types.

Or is there a better way to accomplish this.

**Comment by NTaylorMullen** [comment]
> file types stored in the same location under the pages folder rather than having to replicate the same folder structure under wwwroot.

I'd recommend against adding your .css & .js files to the `Pages` folder (they should only exist in wwwroot). The .cshtml files that exist in the Pages folder exist there because they are transformed into C# and run to generate a response for a specific request at runtime. Basically .cshtml files don't truly represent client side static pages. Content in the wwwroot represents static content that's accessible to a person browsing your website.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
