### ISSUE TITLE
Filter not setting response code 

### ISSUE THREAD

**Issue by colangelo-david** [aspnet/Mvc#8263]
#### Bug

There seems to be an issue setting response codes with filters in dotnet core 

#### Steps to reproduce

The code Im using is (generally as follows) 

The filter 
```
namespace Project.Filters
{
    public class TokenAuth : Attribute, IActionFilter
    {
        //before
        public void OnActionExecuting(ActionExecutingContext context)
        {           
            //force the 403 case 
            if(true){
                context.Result = new API_Unauthorized();
                return;
            }
            //else let them pass if we are all good
        }
        public void OnActionExecuted(ActionExecutedContext context)
        {
            //do nothing after
        }
    }
```

The custom Action 
```
using Microsoft.AspNetCore.Mvc;

namespace Project.REST.Errors
{
    public class API_Unauthorized : ActionResult
    {
        public void ExecuteResult(ControllerContext context)
        {
            // Set the response code to 403.
            context.HttpContext.Response.StatusCode = 403;
        }

        public void ExecuteResultAsync(ControllerContext context)
        {
            // Set the response code to 403.
            context.HttpContext.Response.StatusCode = 403;
        }
    }
}

```

For a complete picture, the endpoint in the controller 

```
[HttpOptions("/api/AnEndpoint")]
[HttpPost("/api/AnEndpoint")]
[EnableCors("AllowAllOrigins")] 
[ServiceFilter(typeof(TokenAuth))]
public JsonResult AnEndpoint([FromBody] AnEndpointRequest request){
      var doNothing = 1; 
      return Json(doNothing);  
}
```

#### Description

Everything seems to be operating more or less fine however there seems to be a response code error. With the above code is executed a 403 should be returned (we are forcing that path). However what I am actually seeing is that a 200 is always returned no matter what. This appears to be a bug where by the context.HttpContext.Response.StatusCode is being overwritten in the execution chain somewhere.

**Comment by pranavkm** [comment]
Your custom action isn't overriding [`ExecuteResult`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.actionresult.executeresult?view=aspnetcore-2.1). Perhaps that's your issue?

**Comment by pranavkm** [comment]
Closing because this looks like a bug in your code. Feel free to reopen if you have further questions.

**Comment by colangelo-david** [comment]
@pranavkm 

im a bit confused, my custom action result does override `ExecuteResult` (see code above, this is where im hard setting the response code as 403)  and my understanding is that the filter does not over ride that. Where should I be overriding `ExecuteResult` that im not?

**Comment by pranavkm** [comment]
Should be something along the lines of

```C#
public class API_Unauthorized : ActionResult
{
    public override void ExecuteResult(ActionContext context)
    {
        // Set the response code to 403.
        context.HttpContext.Response.StatusCode = 403;
    }
}
```
