### ISSUE TITLE
[FromBody] inference for simple types

### ISSUE THREAD

**Issue by alexdresko** [aspnet/Mvc#8267]
Both https://github.com/aspnet/Mvc/blob/504da3c565a9a159365b4564dba5f2cd7d059e7f/src/Microsoft.AspNetCore.Mvc.Core/Internal/ApiBehaviorApplicationModelProvider.cs#L229 and https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#binding-source-parameter-inference confirm that `[FromBody]` is only inferred for complex types. 

Why is that? Can the logic be enhanced to search the body for parameter values if they're not found on the query string? 

`Microsoft.AspNetCore.App`: 2.1.1

**Comment by kjbetz** [comment]
Maybe you know this and are asking that they add more to make it better...

But, if needed you can add `[FromBody]` to a parameter and it will pick it up.

**Comment by alexdresko** [comment]
@kjbetz Correct. I'm aware of the fix, but it wasn't obvious at first. I thought we'd be able to just remove all instances of `[FromBody]` from our application and it would continue to work as it always has. I've already submitted a PR in an attempt to clarify the documentation. At this point, I'm just curious if the functionality can be changed. And, if not, why. 

Thanks for clarifying my original question, though.

**Comment by kjbetz** [comment]
@alexdresko Ahh... maybe I need to re-read some of the updated 2.1 stuff too. I know they improved some things, but at a quick glance it didn't fix what I'm trying to do too. I have complex types and I decorate them with both `[FromRoute]` and `[FromBody]` to get the parameters I need.

**Comment by pranavkm** [comment]
> Why is that? Can the logic be enhanced to search the body for parameter values if they're not found on the query string?

The goal of parameter inference is meant to be easy to reasonable and intuitive. The problem with any form of fallback behavior makes it difficult to reason about the parameter source. Additionally, we want to be able to document ApiControllers using ApiExplorer \ OpenAPI. [The Swagger spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object) doesn't allow associating multiple sources for a parameter. A design that would be difficult to document would be a poor choice.

**Comment by alexdresko** [comment]
@pranavkm Seems reasonable. Thanks for the explanation. @kjbetz might find that explanation useful as well. Closing the issue.
