### ISSUE TITLE
CSRF Redirect Link in Fresh .NET Core 2.1.302 SDK ASP.NET Core template is incorrect

### ISSUE THREAD

**Issue by gortok** [aspnet/Mvc#8268]
#### Is this a Bug or Feature request?:

Bug
#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

1. Create a new ASP.NET Core web application using the .NET Core 2.1.302 SDK (reproducible on Mac OS command line and on VS 2017 15.7.6) using the following command:

```
 dotnet new webapi --auth Windows
```

2. Go to the `ValuesController.cs` file, and make note of the following text:

```
// For more information on protecting this API from Cross Site Request Forgery (CSRF) attacks, see https://go.microsoft.com/fwlink/?LinkID=717803
```
3. Click on the link; the redirect takes you to here: 

https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-2.1

The link should take you to here:

https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1

#### Description of the problem:

Redirect link in template to LinkId=717803 is incorrect and redirects you to the page on XSS; where it should redirect you to the page about CSRF, as indicated in the comment text.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @gortok.
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Templating#675
