### ISSUE TITLE
MVC Core Template set to operate with Windows Authentication in Visual Studio 15.7.6 does not generate a template that uses Windows Authentication

### ISSUE THREAD

**Issue by gortok** [aspnet/Mvc#8270]
#### Is this a Bug or Feature request?:

Bug
#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
1.  Open Visual Studio 2017 15.7.6.
2. Click "New", "ASP.NET Core-> MVC (Model/View/Controller)",
3. click "change authentication" -> "Windows Authentication", 
4. click "OK".
#### Description of the problem:

The generated project template does not include any bits necessary for Windows Authentication. No [Authorize] attribute; no authentication controller, no changes in the Startup.cs to use Windows Authentication, nothing.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @gortok.
Can you please share the output from the `dotnet --info`?

**Comment by gortok** [comment]
@mkArtakMSFT that’s what the comments above show, for both windows and mac

**Comment by gortok** [comment]
Sorry, I left those comments in this ticket: https://github.com/aspnet/Mvc/issues/8269#issuecomment-413004801 I’ll paste them here too when I get a chance.

**Comment by phenning** [comment]
@gortok Did you have any success in removing the %userprofile%\.templateengine\vs-2017.3 folder? I just reinstalled the 15.7.6 version you are using and uninstalled newer .NET Core SDKs and was not able to reproduce the problem either. 

One thing to note, for the MVC template, you shouldn't see any Authorize attributes on the HomeController. Looking at the template content for MVC, it looks like enabling Windows authentication should only result in windowsAuthentication to be set to true in the launchSettings.json file. For the Web API template, there should also be authorize attributes added to the ValueController.

**Comment by mkArtakMSFT** [comment]
@gortok, did the suggestion from @phenning help you solve the problem?

**Comment by gortok** [comment]
Those did not have an effect. I’m trying it again with the .400 sdk to see.

**Comment by gortok** [comment]
I've updated Visual Studio 2017 to 15.8.1; and this problem no longer occurs.
