### ISSUE TITLE
aspnet:MaxJsonDeserializerMembers in asp.net core

### ISSUE THREAD

**Issue by mgolois** [aspnet/Mvc#8273]
Hello,

I'm currently migrating from apps from .net framework 5, asp.net mvc 4 to .net core asp.net mvc.
I would like to know if there are equivalence in .net core for settings like:

- aspnet:MaxJsonDeserializerMembers
- UnobtrusiveJavaScriptEnabled

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mgolois.
@pranavkm, can you please answer this question?

**Comment by pranavkm** [comment]
*  aspnet:MaxJsonDeserializerMembers

@JamesNK, is there an equivalent setting for `aspnet:MaxJsonDeserializerMembers`. From the docs,

> aspnet:MaxJsonDeserializerMembers - Specifies the limit of the maximum number of items that can be present in any dictionary deserialized by the JavaScriptSerializer type.

Applying `MaxLengthAttribute` would produce a validation error, but it doesn't look like it affects deserialization.

* `UnobtrusiveJavaScriptEnabled` - [`HtmlHelperOptions.ClientValidationEnabled`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.viewfeatures.htmlhelperoptions.clientvalidationenabled?view=aspnetcore-2.1) would be the equivalent. That said, ASP.NET Core Mvc by default supports unobtrusive validation, so you don't need to explicitly enable it like MVC 4.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by pranavkm** [comment]
Bump @JamesNK

**Comment by JamesNK** [comment]
Ah, I missed this.

No there is no equivalent to `aspnet:MaxJsonDeserializerMembers` in Json.NET. The only limit is depth.

**Comment by pranavkm** [comment]
@mgolois looks like you have your answers.

**Comment by mgolois** [comment]
Thank you all!
