### ISSUE TITLE
Custom error page w/ ValidateAntiforgeryTokenAuthorizationFilter

### ISSUE THREAD

**Issue by lol768** [aspnet/Mvc#8276]
#### Is this a Bug or Feature request?:

Question.

How do I specify a custom error page to return when the CSRF token is invalid? A `Content-Length` 0, HTTP 400 white page isn't very helpful when things go wrong.

**Comment by mkArtakMSFT** [comment]
@javier, can you please answer the above question?

**Comment by javiercn** [comment]
@lol768 Thanks for contacting us.

An invalid antiforgery token is a developer/application error and not something that a user would normally run into. That said, you can create a result filter that upon 400 resolves IAntiforgery from DI and calls the method below and then redirects to a custom page to show a more descriptive error. https://github.com/aspnet/Antiforgery/blob/master/src/Microsoft.AspNetCore.Antiforgery/IAntiforgery.cs#L48

Closing this as there's no further action to be taken here.
