### ISSUE TITLE
Feature: Strongly Typed Form based on Action or user specified model. 

### ISSUE THREAD

**Issue by AdamHess** [aspnet/Mvc#8277]
#### Is this a Bug or Feature request?:
Feature

#### Description of the feature

Often data required to generate a view is starkly different than data required to be posted to a controller. 

While its not great practice, a common technique is to feed to domain model entities directly into a view for an Add/Update entity form. However, The data required to be posted back is different then the exact model as there are some domain specific rules and modifications made on the server side. 

With that being said, "asp-for" has become syntactic sugar for accessing model properties defined for the view, but does not do much for the model posted back to the server or mapping to the model sent to the server. 

I propose something along the following: 
```
@model ViewModelClass

<form asp-action="SampleAction" asp-form-model="FormModelClass">
   <input asp-for="FormModelClassProperty" asp-view-model-mapping="ViewModelClassProperty" />
</form> 

//In the controller
public IActionResult SampleAction(FormModelClass model) {
//execute
}
```

A corollary to  this  is if the action, controller, area are specified, the form should be able to infer the asp-form-model based on the method signature. 

Part of implementing this would require a rule that this is only usable for actions with only one parameter. 

Alternatively, instead of specifying the asp-form-model, the action could look at only the Action signature and use the model defined there. This would allow for multiple function parameters and still provide the nice static typing. 

One bonus of this would reduce the need for tools like AutoMapper

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AdamHess.
Looks like you're proposing to move the mapping logic to the view, but it seems like this is better handled in the actual controller action. We did look into adding an object mapper to ASP.NET Core, but the feedback from the community was to not do that and use Automapper instead.
