### ISSUE TITLE
Suggestion: Per request cache implementation

### ISSUE THREAD

**Issue by Eneuman** [aspnet/Mvc#8282]
Hi

In todays MicroServices orientated world, you often find your self doing multiple calls to http services from different components in your system.

As an example, when rendering a web page, you might have a ViewComponent that checks if the user has permission (by calling a policy http service) and the controler it self also checks for permission by calling the same service. Multiple calls to the same service retreiving the same result.

Caching can fix this, but then you need to handle evict policies and if you are running on kubernetes or services fabric, you have to implement a distributes cache. Making the call to the distributed cache can take longer, because of network latency and serialization of result, then acually hitting your service twice.

So... How about implementing a "PerRequestCache". This can easily be done like this:

```
  public interface IPerRequestCacheService
  {
    Task<T> GetAsync<T>(PerRequestCachingService.PerRequestCachingType typ, int id, Func<Task<T>> getValueDelegate);
  }

 public class PerRequestCachingService : IPerRequestCacheService
  {
    public enum PerRequestCachingType
    {
      Type1,
      Type2,
      Type3
    }

    private IHttpContextAccessor _httpContextAccessor;

    public PerRequestCachingService(IHttpContextAccessor httpContextAccessor)
    {
      _httpContextAccessor = httpContextAccessor;
    }

    public async Task<T> GetAsync<T>(PerRequestCachingType typ, int id, Func<Task<T>> getValueDelegate)
    {
      var cacheKey = $"{typ.ToString()}_{id}";
      if (_httpContextAccessor.HttpContext.Items.ContainsKey(cacheKey))
      {
        return (T)_httpContextAccessor.HttpContext.Items[cacheKey];
      }
      else
      {
        var value = await getValueDelegate();
        _httpContextAccessor.HttpContext.Items.Add(cacheKey, value);
        return value;
      }
    }

  }
```
and then used like this:

```
      var permissions = await _perRequestCacheService.GetAsync(Services.PerRequestCachingService.PerRequestCachingType.Type1, userId, async () =>
      {
        return await _permissionClient.GetPermissionsAsync(userId);
      });
```

but shouldn't this exist in MVC (out of the box)?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Eneuman.
This is not something we plan to do. There are too many factors involved here making this a good concern for an application to handle. Think about the caching strategy or the lifetime management of the cached items.

**Comment by davidfowl** [comment]
I don’t think we need something frost class for this. A scoped service is enough and would be strongly typed (you could image a ScopedCache\<T\>)

**Comment by Eneuman** [comment]
@khellang Of course the ViewComponent is not doing any http calls, it's calls are capsuled under a service using Clean Architectur design, following SOLID principals and implemented the same way as the eShop reference architectur etc.. . The code is there to show/disscuss a way to use the HttpContext.Items as a temporary "cache" to store generic information for the request.

@mkArtakMSFT But thats excaly what I want to achive. If involving the cache you get all thoose problems you describe. I'm looking at a way to use the HttpContext.Items to store information for the request and then throw it away.

**Comment by Eneuman** [comment]
@davidfowl Currently I have it in a scoped service and it's working fine. But I see alot of example where MicroServices architects are using Distributed Caching as a way of solving everything. And they often run into problems with evicting/update the cache. First it's the performance issue, so they impliment a local cache with a distributed upstream cache, but then they run into trouble with syncing it. Alot of times the problem can be solved without caching, by implementing something similar to my code above. As I said, it's easy to do, just this might be something for the MVC package :)

Whats the size limit of storing data in HttpContext.Items?

**Comment by khellang** [comment]
> Whats the size limit of storing data in HttpContext.Items?

How much memory do you have? 😉

**Comment by Eneuman** [comment]
So no size limits :) 
Any performance issues if it grows?

**Comment by khellang** [comment]
It's just a dictionary with a special indexer;

https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http/Features/ItemsFeature.cs#L13
https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http/Internal/ItemsDictionary.cs#L23

**Comment by Eneuman** [comment]
I see.
So, creating a Scoped service that has a dictionary will probobly be excaly the same as using the HttpContext.Items. So what purpose does HttpContext.Items actually have? Just for compabillity and that it existed in old MVC?

**Comment by khellang** [comment]
> So, creating a Scoped service that has a dictionary will probobly be excaly the same as using the HttpContext.Items.

Exactly.

> So what purpose does HttpContext.Items actually have? Just for compabillity and that it existed in old MVC?

It's often used to allow components or middleware to communicate when they operate at different points in time during a request and have no direct way to pass parameters.

**Comment by Eneuman** [comment]
So it comes down to performance :)
Using a Scoped Service with a Dictionary will create new objects and adds allocations.
Using a HttpContext.Items with a singleton service doesn't.

Premature Optimization for the win ;)

**Comment by khellang** [comment]
Not really. Accessing `HttpContext.Items` also allocates an `ItemsFeature` instance; https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http/DefaultHttpContext.cs#L19 Performance is not an argument here.

**Comment by Eneuman** [comment]
Ok, so If I don't access it, it will not allocate.
Good to know :)

Then Scoped Service is probobly the best way to do this.
Thanks for the info!
