### ISSUE TITLE
ApiExplorer with POCO Controllers

### ISSUE THREAD

**Issue by WinInsider** [aspnet/Mvc#8283]
**Question**: How would one go about generating WebAPI ApiExplorer json file / output for POCO Controllers? Given that AddApiExplorer() works only with controllers with [Route("...")] Attributes? 

I have my own implementation of IApiDescriptionProvider, however this is not enough as exception on line [245](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Internal/ControllerActionDescriptorBuilder.cs#L245) is thrown because ControllerActionDescriptorBuilder.IsAttributeRoutedAction() return false.

Is there some extensibility point in MVC that one could set value to ControllerActionDescriptor.AttributeRouteInfo.Template; which seems to be required by ControllerActionDescriptorBuilder.IsAttributeRoutedAction() … to return true? … and to get ApiExplorer json file / output for POCO Controllers generated...

I do hope MVC team will continue to improve/invest in POCO Controller in effort to reduce "attribute soup".

**Comment by pranavkm** [comment]
Can you share what you're doing with your custom `IApiDescriptionProvider`? You could just choose to use a [different heuristic](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.ApiExplorer/DefaultApiDescriptionProvider.cs#L108-L114) to determine if an action should appear in ApiExplorer.

**Comment by WinInsider** [comment]
After closer examination of what I have done... is my fault... been over engineering … unnecessary have set ApplicationModel.ApiExplorer.IsVisible= true

.NET Core MVC rooks with POCO Controllers... :)
