### ISSUE TITLE
Layout rendering bug

### ISSUE THREAD

**Issue by hez2010** [aspnet/Mvc#8284]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
1. mkdir test
2. cd test
3. dotnet new mvc --auth Individual
4. scaffold all identity codes, using ~/Views/Shared/_Layout.cshtml as layout file
5. run the web app and register an account
6. click your username and go to account management

#### Description of the problem:
1. In the account management view, the code has set ViewData["Title"] but actually while rendering _Layout.cshtml, ViewData["Title"] becomes null so the website title becomes " - test"
2. In Two-factor authentication settings page, after you click "Add authenticator app", the highlight of navigator disappeared, but actually in the code we have set the current page to "TwoFactorAuthentication" in ViewData
3. As we can see, the account management use an independent layout file (as child layout), and the layout file refers the layout file in ~/Views/Shared (as parent layout), but the ViewData and ViewBag in  can not be passed from child layout to its parent layout, therefore, we can draw the conclusion that ViewData and ViewBag can not pass between different layout files. Obviously it's a bug.

**Comment by pranavkm** [comment]
This would be a dup of https://github.com/aspnet/Mvc/issues/7675. We've addressed this as part of 2.2 One way to fix this in 2.1 would be to use ``ViewContext.ViewData["Title"] = "..."` rather than assigning it to the `ViewData` instance on the page.

**Comment by pranavkm** [comment]
Thanks for the detailed report. Closing since no further action needs to be taken here.
