### ISSUE TITLE
Per response cache duration

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Mvc#8285]
_From @JonasSamuelsson on August 17, 2018 12:58_

I'm using response caching and need to set the cache duration based on the content of the response.  
It would be nice if the caching middleware didn't overwrite the cache control header if it exists, I could then do something like thing

``` cs
[HttpGet, ResponseCache(Duration = 10)] // default cache duration 10 seconds
public object Get()
{
   Response.Headers[HeaderNames.CacheControl] = "public,max-age=60"; // override cache duration
   return new { message = "hello" };
}
```

_Copied from original issue: aspnet/Home#3436_

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
Do you have a more complete sample of what you are trying to do and what the expectation is? 

* In the absence of the ResponseCache middleware, specifying a header in the action works just fine - the `ResponseCacheFilter` executes first setting the header, followed by the actual action - so you're pretty free to modify it. 

* If you're specifically talking about the ResponseCache middleware, the middleware caches the initial request and the request does not get to MVC until there is a cache miss.

**Comment by JonasSamuelsson** [comment]
Yes, I do want to use the caching middleware and would like to have the ability to set the cache duration based on some criteria that isnt known until the request is executed.

I have a situation where I the cache duration is stored in a database together with the data I'm returning.

Simplified example:
``` cs
[HttpGet, ResponseCache(Duration = 10)]
public async Task<IASyncResult> Get(int id)
{
   var item = await db.Items.FirstOrDefaultAsync(x => x.Id == id);

   if (item == null)
      return NotFound();

   if (item.CacheDuration.HasValue)
      Response.Headers[HeaderNames.CacheControl] = $"public,max-age={item.CacheDuration}";

   return Ok(item.Body);
}
```

**Comment by pranavkm** [comment]
@JonasSamuelsson the sample code you listed action works just fine. If I try running it, I can see the the cache header from the action body being used. Do you have a repro app showing otherwise?

**Comment by JonasSamuelsson** [comment]
So it does, I must have screwed something up when I tried it first, I guess I'm all good then =)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
