### ISSUE TITLE
CreatedAtRoute mistakes path parameter for query parameter

### ISSUE THREAD

**Issue by MikaelUmaN** [aspnet/Mvc#8286]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

Given a Get method in a Controller:

```
    [HttpGet(Name = "GetInstrumentView")]
    [Route("{id:int}")]
    public InstrumentView GetInstrumentView([FromRoute] int id, ...)
```

Then this 
`return CreatedAtRoute("GetInstrumentView", new {id}, createdView);`

call at the end of a HttpPost method ->

#### Description of the problem:

Leads to a location header:
http://localhost:8081/instruments?id=155

whereas I expected
http://localhost:8081/instruments/155

I cannot find detailed information about this method in documentation, it just says [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.createdatroute?view=aspnetcore-2.1#Microsoft_AspNetCore_Mvc_ControllerBase_CreatedAtRoute_System_String_System_Object_System_Object_) which is not very helpful.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.2.0

**Comment by pranavkm** [comment]
Try using `[HttpGet("{id:int}", Name = "GetInstrumentView")]`. The code above is adding two separate routes - the `HttpGet` with an empty template and one with "{id:int}" which is not what you want here.

**Comment by MikaelUmaN** [comment]
Thank you very much. I was unaware I created two different routes! Sorry for mistakenly creating this issue.
