### ISSUE TITLE
Create custom routing with areas

### ISSUE THREAD

**Issue by Chrissx** [aspnet/Mvc#8291]
#### Is this a Bug or Feature request?:
Question ( Feature request )

#### Description of the problem:
Is there a way to define custom routing with areas in MVC? I saw examples which using IControllerModelConvention and rewrite controller convensiton but currently there is no example in the documentation for Areas. 

I have a following url 
**/example-area/example-controller/action-name**

I would like to map it for the following convention
Area : ExampleArea
Controller : ExampleController
Action : ActionName

Is there a way to modify, replace area based conventions with implementing a custom **IApplicationModelConvention** without using attribute based routing? 

I would like to keep the standard behaviour except the kebab based convention.

Enviroment: ASP .NET core 2.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Chrissx.
@rynowak, can you please look into this one? Thanks!

**Comment by rynowak** [comment]
> Is there a way to modify, replace area based conventions with implementing a custom IApplicationModelConvention without using attribute based routing?

No. Attribute routing is the mechanism that gives you control over the URLs. If you want, you could write a convention that adds attribute routes to your controllers/actions/areas. 

We're considering doing a feature like this in 2.2 but we have no immediate eta.

**Comment by Chrissx** [comment]
Thanks :) Is there any way to access the controllers current Area? 

On that case I can add manually the attribute routes inside the custom convention. Could you please point me out some example or implementation that I can take a look?

**Comment by rynowak** [comment]
The area would be in the route values. You can also use the `[...]` syntax which will do token replacement https://github.com/aspnet/Entropy/blob/master/samples/Mvc.CustomRoutingConvention/NameSpaceRoutingConvention.cs#L22

**Comment by Chrissx** [comment]
My only problem is the [area] only present if I specify in the controller level. What I would like to access is the default convention based area ( folder structure based ).
Do I need to always specify the [Area] attribute in every controller?

**Comment by rynowak** [comment]
> the default convention based area ( folder structure based )

Areas is based on an attribute in aspnet core. We don't know what folder your code was in when it was compiled. You could make some inferences if you want based on the namespace.

**Comment by Chrissx** [comment]
I see yes its my mistake. I had an assumption MVC automatically build  the metadata based on the folder structure. 
Thanks for helping out!
