### ISSUE TITLE
Can't use action parameter with properties decorated with [FromQuery] within ApiController

### ISSUE THREAD

**Issue by Deilan** [aspnet/Mvc#8292]
#### Is this a Bug or Feature request?:
Not sure

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Repro project: https://github.com/deilan-issues-samples/Mvc.Issues/tree/master/Mvc.Issues.N8292

1. Create a controller with an action and query object:
```csharp
[Route("api/[controller]")]
[ApiController]
public class ValuesController : ControllerBase
{
    // GET api/values
    [HttpGet]
    public ActionResult<IEnumerable<string>> Get(GetQuery query)
    {
        return new[] { "value1", "value2" };
    }
}

public class GetQuery
{
    [FromQuery]
    public string Filter { get; set; }
    [FromQuery]
    public string Sort { get; set; }
    [FromQuery]
    public string Page { get; set; }
    [FromQuery]
    public string PageSize { get; set; }
    [FromQuery]
    public string Locale { get; set; }
}
```

2. Make a request to the `Get` action.

**Expected result**: `["value1", "value2"]`
**Actual result**: `{"":["The input was not valid."]}`

#### Description of the problem:
If a controller is decorated with [[ApiController]](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#annotate-class-with-apicontrollerattribute) attribute and it's action accepts an instance of a class with a properties decorated with `[FromRoute]`, `[FromBody]`, etc., or even without any properties at all, then any request to this action always results in an error message: `{"":["The input was not valid."]}`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Deilan.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/8135. The parameter inference for `ApiControllers` doesn't look at model binding attributes on the properties of the parameter model. It basically goes - is `GetQuery` a complex type, then assume it's a `FromBody` parameter. One way to workaround this would be to set `FromQuery` on the actual parameter.
