### ISSUE TITLE
Net Core SDK 2.1.400 ignore _ViewStart on Areas views on publish

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8293]
_From @alca259 on August 18, 2018 19:6_

After upgrade to VS 15.8.1 and Net Core SDK 2.1.400, the _ViewStart on Areas views are ignored, only then publish to folder.

Steps: 
- Create a project with one Area
- Setup a dummy controller with a file _ViewStart.cshtml in the root of Views folder
- Load a layout or write something in the log
- Publish to local folder
- Copy to a IIS Site with native code and the same SDK installed.
- Access to dummy controller inside of the area

Sample log:
- Users controller have specified layout on Index view
- Roles controller not have specified layout on Index view, it take Layout from _ViewStart.cshtml

[AttachedLog.txt](https://github.com/aspnet/Home/files/2299811/AttachedLog.txt)
[LogFirstCall.txt](https://github.com/aspnet/Home/files/2299812/LogFirstCall.txt)

_Copied from original issue: aspnet/Home#3438_

**Comment by pranavkm** [comment]
_From @alca259 on August 20, 2018 14:23_

I was did more test. The _ViewImports.cshtml, _ViewStart.cshtml and _Layout.cshtml inside of a Area are ignored on publish. Works well in visual studio in debug and release.

**Comment by pranavkm** [comment]
Can you share a repro app or the folder structure? Looking at the logs, it looks like these were all the views that MVC discovered under the areas directory:

```
dbug: Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Areas/Diaries/Views/Diary/Index.cshtml'.
dbug: Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Areas/Diaries/Views/Emotion/Index.cshtml'.
dbug: Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Areas/Security/Views/Roles/Index.cshtml'.
dbug: Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Areas/Security/Views/Users/Index.cshtml'.
```

**Comment by alca259** [comment]
Project structure
![image](https://user-images.githubusercontent.com/3340608/44357453-6165de00-a4b2-11e8-8f64-5ade8606e166.png)

I create a [new blank projec](https://github.com/alca259/NetCoreDemo/tree/master/WebApp)t and works well, but i don't know why, because i copy the files from my original project.

**Comment by pranavkm** [comment]
Does cleaning + rebuilding your original project work? If that doesn't work, could you run `dotnet build /bl` and attach the log file (`msbuild.binlog`)? That said, if the issue is resolved in a blank project, do you think it's still worthwhile investigating this further?

**Comment by alca259** [comment]
Ok, so sorry. It's not a bug. I don't know why my csproj is corrupted and remove views from compilation.
![image](https://user-images.githubusercontent.com/3340608/44357843-70995b80-a4b3-11e8-9643-609e249f1321.png)

![image](https://user-images.githubusercontent.com/3340608/44357855-7c851d80-a4b3-11e8-937f-8a7a624284ff.png)
