### ISSUE TITLE
Make HTML rendering deferred (IHtmlContent)

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#830]
Currently `TemplateRenderer.Render` returns a string which gets converted to HtmlString. This causes it to produce a new StringWriter buffer. We could have it return a HelperResult instead - it's consumed in the same way, but would avoid the extra buffer allocation.

**Comment by yishaigalatzer** [comment]
If a template ever renders a large portion of text > 80K there is definitely a major LOH issue that will cause pauses and lots of CPU spent in GC

**Comment by yishaigalatzer** [comment]
@NTaylorMullen please tie this to the TagHelper Content change when working with @sornaks

**Comment by sornaks** [comment]
Note to self: Move `HelperResult` to `Razor.Runtime`.

**Comment by sornaks** [comment]
https://github.com/aspnet/Mvc/commit/f2540f9ba19937f79c1a780ef12dd9a9d5cd84a6
