### ISSUE TITLE
Finding Embedded View With RazorViewEngine

### ISSUE THREAD

**Issue by mmillican** [aspnet/Mvc#8309]
We currently have an app that uses embedded views to allow us to package the views (and other classes) as a Nuget package.

We're having an issue using `IRazorViewEngine.FindView(...)` to find these embedded views; the views render fine otherwise. 

Note that the call to `FindView()` is being done in a class library (ie "Shared") but the views are in the "Web" project.

We are adding the `EmbeddedFileProvider` to the view engine like this:

```c#
public static RazorViewEngineOptions AddAdminEmbeddedViews(this RazorViewEngineOptions options)
{
    options.FileProviders.Add(new EmbeddedFileProvider(
        typeof(Startup).GetTypeInfo().Assembly, ExampleProject.Web"));

    return options;
}
```

Using various path formats such as the following do not work:

- `Areas.Admin.Views.ControllerName.ViewName`
- `/Areas/Admin/Views/ControllerName/ViewName[.cshtml]` (I would not expect this to work here though)

Is this supported? If so, what are we missing or how should the views be referenced?

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please look into this? Thanks!

**Comment by mmillican** [comment]
I considered using Razor Pages, but it would be a significant change for this particular use case. It turns out that adding `~/` to the path works for us.

**Comment by javiercn** [comment]
@mmillican razor class libraries doesn’t require you to use razor pages
