### ISSUE TITLE
403 Error debugging Core 2.1 MVC with IIE Express

### ISSUE THREAD

**Issue by jastralfu** [aspnet/Mvc#8314]
I think this is a bug but am not entirely sure.  I have created an ASP.NET Core 2.1 MVC Web app with the default template.  I have changed nothing with the default application save for updating the IIS Express applicationhost.config to enable SSL by changing the access sslFlags to sslFlags="Ssl, SslNegotiateCert, SslRequireCert".  When I debug from Visual Studio 2017 I get the following error:
Unable to start process C:\Program Files\dotnet\dotnet.exe.  The web server request failed with status code 403, Forbidden.
From the HttpFailure and the IIS Express TraceLogFile files it seems as though IIS Express is trying to open the http url rather than the https url.  The launchsettings.json has an SSL port defined but it is not using it.  
If I run the application without debugging (ctrl + f5) the site opens using the https url and prompts for a client certificate.  Is this a bug or am I missing something?

To reproduce this 
1) create a new ASP.NET Core 2.1 Web MVC Applicationproject enabling https with no authentication.
2) Update the applicationhost.config file in the .vs/config folder of the project and replace access sslFlags="None"  with access sslFlags="Ssl, SslNegotiateCert, SslRequireCert".
3) Debug with IIS Express (f5).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jastralfu.
@javiercn, can you please help out with this? Thanks!

**Comment by javiercn** [comment]
@BillHiebert Can you take a look at this?

**Comment by javiercn** [comment]
@jastralfu Thanks for contacting us.

Seems like you are trying to use client certificates with asp.net core in VS. As far as I understand this is not a supported scenario, as VS needs to ping the app to see if the server is up and the client certificate negotiation prevents it (I believe).

See https://github.com/aspnet/SignalR/issues/2259 for more details on a similar issue.

@Tratcher can provide more details.

Closing this issue as there's no further action to be taken here.

**Comment by jastralfu** [comment]
@javiercn  Not sure I understand why this is happening.  The application that is being pinged is the http url not the https url.  The 403 is from trying to access an SSL site thru the http url.  I read the SignalR link you included and I can attach to the dotnet.exe process once the app is up and running using ctrl+f5. 
 How do I get in touch with @Tratcher for a more detailed explanation?

**Comment by javiercn** [comment]
@jastralfu He'll look at this and provide more details. I think this is not well supported by VS. Not sure what the alternatives are.

**Comment by jastralfu** [comment]
Thank you.  One more thing, this scenario works without issue with the full .NET framework.  I realize Core is very different but I would love to know what changed and if this will be fixed in some future release.

**Comment by javiercn** [comment]
.NET Core uses ANCM (ASP.NET Core module) while ASP.NET is more deeply integrated with IIS. As a result of that, VS needs to ping the .NET Core app to know when it can attach the debugger. By having a client cert, it can’t stablish the connection to the server and hence it fails to detect the app is up and running and attach the debugger.

You could try changing the order/setting up ASPNETCORE_URLS on the IIS Express launch profile with the http address being the first one, and see if that works to workaround the problem.

If not, I suggest you file a bug through Visual Studio (right top corner, Report a Problem) and that way they can look at the issue and decide what to do.
