### ISSUE TITLE
MvcRazorCompileOnPublish Error

### ISSUE THREAD

**Issue by JulienM28** [aspnet/Mvc#8316]
Since the last version of ASP .Net Core (2.1.3)

When I try to publish I get this error

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""dotnet" exec --runtimeconfig "C:\Team Foundation\BookStarter\BookStarter\bin\Release\netcoreapp2.1\BookStarter.runtimeconfig.json" --depsfile "C:\Team Foundation\BookStarter\BookStarter\bin\Release\netcoreapp2.1\BookStarter.deps.json" "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.1.1\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp2.1\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code -2147450730.	BookStarter		0	

Ihave to comment <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
to avoid this.

What should be the solution for this issue?

Thanks

**Comment by pranavkm** [comment]
We're deprecating the precompilation and recommend using [RazorSdk](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.1) instead. The way to use it would be to remove `MvcRazorCompileOnPublish` from your csproj

**Comment by JulienM28** [comment]
I may have missed something but Razor SDK doesn't look like to be used for full web app.

The SDK Page says:
For web applications, ensure your app is targeting Microsoft.NET.Sdk.Web SDK.

So I'm confused about what to do.

Thanks.

**Comment by pranavkm** [comment]
`Microsoft.NET.Sdk.Web` bundles `Microsoft.NET.Sdk.Razor`, so you wouldn't need to change that. What you do need to do is to not explicitly opt in to using precompilation. The most gestures to do that include

a) Setting `<MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>` in your csproj
b) Setting `<RazorCompileToolset>PrecompilationTool</RazorCompileToolset>` in your csproj.

**Comment by JulienM28** [comment]
You said to remove  MvcRazorCompileOnPublish because it's deprecated.

I see:
RazorCompileOnBuild : When true, compiles and emits the Razor assembly as part of building the project. Defaults to true.
RazorCompileOnPublish : When true, compiles and emits the Razor assembly as part of publishing the project. Defaults to true.

So I just need to add <RazorCompileToolset>PrecompilationTool</RazorCompileToolset> ?

**Comment by pranavkm** [comment]
> So I just need to add PrecompilationTool ?

Nope, adding that would disable Razor Sdk. Like I said earlier, by default you get Razor Sdk. Adding either of those properties in your project file would opt out of it.

**Comment by JulienM28** [comment]
Thank you, It works fine now
