### ISSUE TITLE
Rendering parts of page based on given criteria

### ISSUE THREAD

**Issue by JoshClose** [aspnet/Mvc#8321]
I'm looking into using this pjax library. https://github.com/MoOx/pjax A pjax request will have a header `X-PJAX-Selectors` that contains the parts of the page that need to be rendered. I'd like to create pages as normal and when a pjax request happens, only render the html elements that match the selectors.

What are some options for accomplishing this? 

I was thinking that maybe I could create a custom tag helper where I specify the selector or maybe I can take the generated HTML and strip out anything that doesn't match that filter. Both of these would require me to intercept the output of the razor page to manipulate it. Where is the best place to do that?

I'm not sure where the best place is to begin.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, can you please advice on available options? Thanks!

**Comment by NTaylorMullen** [comment]
@JoshClose there isn't a great way to accomplish what you're looking for sadly. My suggestion would be to create a middleware that wraps the entire response of your server => parse it with angle sharp or some other Html parsing library => apply your selector logic.

**Comment by JoshClose** [comment]
Is angle sharp fast enough? That is my ideal scenario.

What I'm currently doing is using some custom tag helpers. `<pjax-show></pjax-show` `<pjax-hide></pjax-hide>` `<div pjax-hide="true">` `<div pjax-selector=".my-selector">` This means I need to duplicate code and duplicate properties.

**Comment by JoshClose** [comment]
I hadn't seen AngleSharp before. I think this will do exactly what I need.

**Comment by JoshClose** [comment]
@NTaylorMullen How would I do this? If I register middleware after `app.UseMvc`, it never gets called.

**Comment by JoshClose** [comment]
I think I found something that will work. Let me know if this is wrong. https://stackoverflow.com/questions/27452734/modifying-the-raw-html-output-from-mvc-6

**Comment by NTaylorMullen** [comment]
@JoshClose your middleware has to happen before the `app.UseMvc` and you need to capture the output of the Mvc middleware to properly parse it.

The stackoverflow link you provided will work.

**Comment by JoshClose** [comment]
Thanks. This seems to work pretty well.

```cs
public async Task InvokeAsync(HttpContext context)
{
	// Intercept the content written to the body.
	var originalBodyStream = context.Response.Body;
	var captureBodyStream = new MemoryStream();
	context.Response.Body = captureBodyStream;

	// Run the MVC middleware.
	await next(context);

	captureBodyStream.Position = 0;
	var reader = new StreamReader(captureBodyStream);
	var body = await reader.ReadToEndAsync();
	using (captureBodyStream) { }

	// Manipulate body here.

	using (var newBodyStream = new MemoryStream())
	using (var writer = new StreamWriter(newBodyStream))
	{
		writer.Write(body);
		writer.Flush();
		newBodyStream.Position = 0;
		await newBodyStream.CopyToAsync(originalBodyStream);
	}
}
```
