### ISSUE TITLE
HttpConfiguration.IncludeErrorDetailPolicy in .NetCore

### ISSUE THREAD

**Issue by mgolois** [aspnet/Mvc#8332]
Hello,
Currently migrating code from .NET 4 mvc app to .Net Core 2.1 mvc app.
Previously, we were able to set this policy for webapi errors; does this have an equivalence in .Net Core
`HttpConfiguration.IncludeErrorDetailPolicy = IncludeErrorDetailPolicy.Always`

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by pranavkm** [comment]
@mgolois there isn't a direct equivalent to `IncludeErrorDetailPolicy`.  The closest approximations would be to 

a) Globally add a exception filter and configure the filter to process the exception
b) Configure an instance of [`ExceptionHandlerMiddleware`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.1#configuring-a-custom-exception-handling-page) to point to an action that can process the exception.

**Comment by mgolois** [comment]
Thank you, @pranavkm !
