### ISSUE TITLE
[Question] - Razor Pages Compilation

### ISSUE THREAD

**Issue by dazinator** [aspnet/Mvc#8340]
#### Is this a Bug or Feature request?:
Sorry - it's a plea for some hints

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
~~Can provide sample if needed.~~
https://github.com/dazinator/Dotnettency.Samples/tree/aspnetcore20/src/Sample.RazorPages
- set startup project to Sample.RazorPages, then browse on localhost:5000-5002

#### Description of the problem:

TLDR: I have an issue where razor compilation is failing and I am not sure why - looking for some pointers or hints as to why all of a sudden it can't find any references. I am also wondering if there is a "minimal" Razor pages sample anywhere that shows a `csproj` with just the razor pages packages, not entire mvc stack, and just the startup code to configure only razor pages without any additional parts of the stack like Mvc. My scenario is not common, as I am developing a `multitenancy` library aimed to help others, and I am dealing with concepts such as forking middleware pipeline on a per tenant basis, as well as per tenant DI containers (IServiceProviders).

## Some Background
I am working on an open source multi-tenancy library.

It works at a high level through a middleware that does the following things:

-  Identifies the tenant for the current request.
-  Builds a child container for the current tenant if one doesn't exist. This allows services to be registered on a per tenant basis. This tenant container has it's own `IServiceProvider`. 
 - Sets `HttpContext.RequestServices` to a `scoped` version of the tenant's `IServiceProvider` - disposed of at the end of the request.
- Builds a middleware pipeline for each tenant, when the first request for that tenant is received. It does this by invoking a delegate similar to `Startup.Configure(IApplicationBuilder app, IHostingEnvironment env)` but when it passes in an `IApplicationBuilder` it first sets `appBuilder.ApplicationServices` to the `IServiceProvider` for the current tenants container. This means any IApplicationBuilder extension methods get to see the services at the current tenant level when that tenant's middleware pipeline is configured. This delegate also has access to the current Tenant, so the developer can optionally include middleware in that pipeline based on the current Tenant's details. 
- Invokes the built middleware pipeline for the current tenant (i.e where the request should be handled).

This is all working nicely so far, and I have some working samples, the latest of which shows multi-tenant cookie authentication working in this paradigm: https://github.com/dazinator/Dotnettency.Samples/tree/aspnetcore20/src/Sample.Authentication/

In the above example, the authentication middleware is added to the tenant's middleware pipeline (browse on localhost:5000) if you browse on localhost:5002) which is a different tenant, there is no authentication middleware in that tenants pipeline at all.

### Issue
I am now working on a sample that attempts to configure Razor Pages under this paradigm - i.e register razor pages at the tenant container level rather than `ApplicationServices`, and use the middleware at the tenant middleware pipeline level.

However when I do this I see that Razor compilation starts failing:

> dbug: Dotnettency.AspNetCore.MiddlewarePipeline.TenantPipelineMiddleware[0]
      Tenant Pipeline Middleware - Executing Pipeline.
Application MiddlewareStarting: Microsoft.AspNetCore.Diagnostics.WelcomePageMiddleware; /
Application MiddlewareStarting: Microsoft.AspNetCore.Builder.RouterMiddleware; /
Application MiddlewareException: Microsoft.AspNetCore.Builder.RouterMiddleware; One or more compilation failures occurred:
npetcvie.s1j(4,44): error CS0234: The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(4,89): error CS0518: Predefined type 'System.String' is not defined or imported
npetcvie.s1j(4,113): error CS0518: Predefined type 'System.Type' is not defined or imported
npetcvie.s1j(8,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(9,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(10,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(11,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(14,36): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(15,73): error CS0234: The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(18,67): error CS1983: The return type of an async method must be void, Task or Task<T>
npetcvie.s1j(18,39): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
npetcvie.s1j(32,49): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(32,118): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(34,49): error CS0234: The type or namespace name 'IUrlHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(34,71): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(36,49): error CS0234: The type or namespace name 'IViewComponentHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(36,87): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(38,59): error CS0234: The type or namespace name 'IJsonHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.Rendering' (are you missing an assembly reference?)
npetcvie.s1j(38,83): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(40,59): error CS0234: The type or namespace name 'IHtmlHelper<>' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.Rendering' (are you missing an assembly reference?)
npetcvie.s1j(40,71): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(40,71): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(40,119): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(41,49): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(41,81): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(41,81): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(42,16): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(42,16): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(18,67): error CS0115: '_Pages_Index_cshtml.ExecuteAsync()': no suitable method found to override
npetcvie.s1j(31,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(31,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(33,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(33,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(35,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(35,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(37,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(37,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(39,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(39,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(26,13): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(26,13): error CS0103: The name 'BeginContext' does not exist in the current context
npetcvie.s1j(26,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
npetcvie.s1j(26,30): error CS0518: Predefined type 'System.Int32' is not defined or imported
npetcvie.s1j(26,35): error CS0518: Predefined type 'System.Boolean' is not defined or imported
npetcvie.s1j(27,13): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(27,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
npetcvie.s1j(27,26): error CS0518: Predefined type 'System.String' is not defined or imported
npetcvie.s1j(28,13): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(28,13): error CS0103: The name 'EndContext' does not exist in the current context
npetcvie.s1j(18,67): error CS0161: '_Pages_Index_cshtml.ExecuteAsync()': not all code paths return a value
npetcvie.s1j(41,231): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(41,231): error CS0103: The name 'PageContext' does not exist in the current context
npetcvie.s1j(41,163): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(41,195): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(41,195): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
F:\Repos\Dotnettency.Samples\src\Sample.RazorPages\Pages\Index.cshtml(4,5): error CS0518: Predefined type 'System.Object' is not defined or imported
F:\Repos\Dotnettency.Samples\src\Sample.RazorPages\Pages\Index.cshtml(4,5): error CS0103: The name 'Layout' does not exist in the current context
Application MiddlewareException: Microsoft.AspNetCore.Diagnostics.WelcomePageMiddleware; One or more compilation failures occurred:
npetcvie.s1j(4,44): error CS0234: The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(4,89): error CS0518: Predefined type 'System.String' is not defined or imported
npetcvie.s1j(4,113): error CS0518: Predefined type 'System.Type' is not defined or imported
npetcvie.s1j(8,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(9,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(10,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(11,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(14,36): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(15,73): error CS0234: The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(18,67): error CS1983: The return type of an async method must be void, Task or Task<T>
npetcvie.s1j(18,39): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
npetcvie.s1j(32,49): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(32,118): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(34,49): error CS0234: The type or namespace name 'IUrlHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(34,71): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(36,49): error CS0234: The type or namespace name 'IViewComponentHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(36,87): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(38,59): error CS0234: The type or namespace name 'IJsonHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.Rendering' (are you missing an assembly reference?)
npetcvie.s1j(38,83): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(40,59): error CS0234: The type or namespace name 'IHtmlHelper<>' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.Rendering' (are you missing an assembly reference?)
npetcvie.s1j(40,71): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(40,71): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(40,119): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(41,49): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(41,81): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(41,81): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(42,16): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(42,16): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(18,67): error CS0115: '_Pages_Index_cshtml.ExecuteAsync()': no suitable method found to override
npetcvie.s1j(31,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(31,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(33,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(33,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(35,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(35,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(37,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(37,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(39,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(39,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(26,13): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(26,13): error CS0103: The name 'BeginContext' does not exist in the current context
npetcvie.s1j(26,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
npetcvie.s1j(26,30): error CS0518: Predefined type 'System.Int32' is not defined or imported
npetcvie.s1j(26,35): error CS0518: Predefined type 'System.Boolean' is not defined or imported
npetcvie.s1j(27,13): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(27,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
npetcvie.s1j(27,26): error CS0518: Predefined type 'System.String' is not defined or imported
npetcvie.s1j(28,13): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(28,13): error CS0103: The name 'EndContext' does not exist in the current context
npetcvie.s1j(18,67): error CS0161: '_Pages_Index_cshtml.ExecuteAsync()': not all code paths return a value
npetcvie.s1j(41,231): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(41,231): error CS0103: The name 'PageContext' does not exist in the current context
npetcvie.s1j(41,163): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(41,195): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(41,195): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
F:\Repos\Dotnettency.Samples\src\Sample.RazorPages\Pages\Index.cshtml(4,5): error CS0518: Predefined type 'System.Object' is not defined or imported
F:\Repos\Dotnettency.Samples\src\Sample.RazorPages\Pages\Index.cshtml(4,5): error CS0103: The name 'Layout' does not exist in the current context
Application MiddlewareException: Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass4_1; One or more compilation failures occurred:
npetcvie.s1j(4,44): error CS0234: The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(4,89): error CS0518: Predefined type 'System.String' is not defined or imported
npetcvie.s1j(4,113): error CS0518: Predefined type 'System.Type' is not defined or imported
npetcvie.s1j(8,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(9,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(10,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(11,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(14,36): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(15,73): error CS0234: The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(18,67): error CS1983: The return type of an async method must be void, Task or Task<T>
npetcvie.s1j(18,39): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
npetcvie.s1j(32,49): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(32,118): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(34,49): error CS0234: The type or namespace name 'IUrlHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(34,71): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(36,49): error CS0234: The type or namespace name 'IViewComponentHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(36,87): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(38,59): error CS0234: The type or namespace name 'IJsonHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.Rendering' (are you missing an assembly reference?)
npetcvie.s1j(38,83): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(40,59): error CS0234: The type or namespace name 'IHtmlHelper<>' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.Rendering' (are you missing an assembly reference?)
npetcvie.s1j(40,71): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(40,71): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(40,119): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(41,49): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(41,81): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(41,81): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(42,16): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(42,16): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
npetcvie.s1j(18,67): error CS0115: '_Pages_Index_cshtml.ExecuteAsync()': no suitable method found to override
npetcvie.s1j(31,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(31,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(33,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(33,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(35,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(35,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(37,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(37,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(39,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
npetcvie.s1j(39,10): error CS0518: Predefined type 'System.Void' is not defined or imported
npetcvie.s1j(26,13): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(26,13): error CS0103: The name 'BeginContext' does not exist in the current context
npetcvie.s1j(26,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
npetcvie.s1j(26,30): error CS0518: Predefined type 'System.Int32' is not defined or imported
npetcvie.s1j(26,35): error CS0518: Predefined type 'System.Boolean' is not defined or imported
npetcvie.s1j(27,13): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(27,13): error CS0103: The name 'WriteLiteral' does not exist in the current context
npetcvie.s1j(27,26): error CS0518: Predefined type 'System.String' is not defined or imported
npetcvie.s1j(28,13): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(28,13): error CS0103: The name 'EndContext' does not exist in the current context
npetcvie.s1j(18,67): error CS0161: '_Pages_Index_cshtml.ExecuteAsync()': not all code paths return a value
npetcvie.s1j(41,231): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(41,231): error CS0103: The name 'PageContext' does not exist in the current context
npetcvie.s1j(41,163): error CS0234: The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)
npetcvie.s1j(41,195): error CS0518: Predefined type 'System.Object' is not defined or imported
npetcvie.s1j(41,195): error CS0246: The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?)
F:\Repos\Dotnettency.Samples\src\Sample.RazorPages\Pages\Index.cshtml(4,5): error CS0518: Predefined type 'System.Object' is not defined or imported
F:\Repos\Dotnettency.Samples\src\Sample.RazorPages\Pages\Index.cshtml(4,5): error CS0103: The name 'Layout' does not exist in the current context

I know this is not your standard development pattern. However, supporting multitenant applications is a primary goal for my library and I think will be useful to a number of people. Any helpful information / hints / or pointers you might be able to give as to why `RazorCompilation` might start failing in this way and where I might want to be looking - would be very helpful / and appreciated. Also if there is a minimal RazorPages example somewhere that shows configuring and using razor pages with the minimal api surface and packages that would also be good - as opposed to pulling in the entire mvc stack.

#### 

```xml
 <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.9" />
 <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.4" />
<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
```

**Comment by pranavkm** [comment]
@dazinator AddMvc does a very atypical thing to set up the application - it attempts to resolve an [`IHostingEnvironment` instance from the `ServiceCollection`](https://github.com/aspnet/Mvc/blob/2.0.4/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L66) which is used to determine what assemblies should become parts in the `ApplicationPartManager`. The `ServiceCollection` is empty when `AddMvc` is called here - https://github.com/dazinator/Dotnettency.Samples/blob/aspnetcore20/src/Sample.RazorPages/Startup.cs#L54. Adding `IHostingEnvironment` to `tenantServices` gets the views to compile correctly

```C#
tenantServices.AddSingleton(_environment);

// This runs to configure each tenant's container, when tenant is browsed for first time.
tenantServices.AddMvc();
```

Application parts are also used in controller discovery, so you'd want this to be set up correctly even if you a build-time view compilation model.

**Comment by dazinator** [comment]
@pranavkm - oh wow! Thank you so much for this - this was a better response than I could have hoped for and it explains an oversight on my part. I didn't consider that the `ServiceCollection` that is created by default has a bunch of registrations in by default, (like IHostingEnvironment) _and_ that other configuration methods, like AddMvc() need access to these. This gives me some stuff to rethink.
Many Thanks :-)

**Comment by dazinator** [comment]
@pranavkm - [If I disable `ApplicationInsights`](https://github.com/dazinator/Dotnettency.Samples/blob/aspnetcore20/src/Sample.RazorPages/Program.cs#L16), the sample now works :-)

So now I am looking at what could be special about `ApplicationInsights.` - I'd like to keep support for ideally.

The stack trace is saying that something tries to resolve a `JavascriptSnippet` but the necessary necessary constructor parameter `System.Text.Encodings.Web.JavaScriptEncoder encoder` cannot be resolved.

I have tried ensuring that all services from the root `ServiceCollection` (not just IHostEnvironment) are also available in the `IServiceCollection` for each tenant, but this didn't fix the problem.

```
              // tenantServices.AddSingleton(_environment);
              foreach (var item in services) // this is the application level `ServiceCollection`.
              {
                     tenantServices.Add(item);
               }
              // This runs to configure each tenant's container, when tenant is browsed for first time.
              tenantServices.AddMvc();
```

Im wondering what I could be missing still.

**Comment by dazinator** [comment]
If I register the web encoders at `ApplicationServices` level: `services.AddWebEncoders(); ` then tenant level Insights works as it is now able to resolve its `JavascriptSnippet`. I haven't managed to figure out why `RequestServices` is not being used for this resolution, as I have verified that the web encoder is registered and available from `RequestServices`.

**Comment by dazinator** [comment]
It looks like ITagHelperComponentManager was changed to use `RequestServices..` but perhaps that change was made after 2.0.0 and as I am on 2.0.0 I am still seeing the issue: https://github.com/aspnet/Mvc/commit/d27e66a8fc2ec610bd9b6cd5afc452e4fdfc0e77#diff-bf85100f11c10aedb285b010de0037f3R69

I'll try 2.1.0
