### ISSUE TITLE
Add feature to turn off precompiled views from being updated (non updatable, precompiled views)

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#8362]
#### Is this a Bug or Feature request?:

Feature

#### Description of the problem:
MVC still watches files for applications that don't have any views on disk. It should be possible to turn this behavior off completely when the application doesn't expect views on disk to override precompiled ones. 

There are some other benefits to adding this feature:
- File watching for views is off (which seems to cause issues on certain OSes)
- We do less work at runtime and there's no need to allocate change tokens for every view since nothing can change.

**Comment by rynowak** [comment]
Should we infer the default value of this option based on the environment? Or did you have in mind that we'd just allow people to turn of view recompilation if they want to.

**Comment by pranavkm** [comment]
MVC also [uses file watchers](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.TagHelpers/Internal/FileVersionProvider.cs#L57) for the Link \ Script TagHelpers, although it's pay for play. Would we have a single switch to turn off all of file watching in MVC?

**Comment by davidfowl** [comment]
>  Should we infer the default value of this option based on the environment? Or did you have in mind that we'd just allow people to turn of view recompilation if they want to.

We usually do that in the template but maybe it's not so bad to infer the default that can be changed by users.

**Comment by pranavkm** [comment]
> it's not so bad to infer the default that can be changed by users.

This would be a first, no?

**Comment by pranavkm** [comment]
@davidfowl in my current implementation (https://github.com/aspnet/Mvc/pull/8369), all I do is turn off file watching. Views still get compiled at runtime, they don't recompile when the file changes.
