### ISSUE TITLE
Assembly.CodeBase is incorrectly parsed in RelatedAssemblyAttribute if the path contains # character

### ISSUE THREAD

**Issue by peterhuene** [aspnet/Mvc#8367]
_From @Petermarcu on August 31, 2018 18:56_

@noorrocks commented on [Wed Aug 29 2018](https://github.com/dotnet/core/issues/1904)

# Issue Title

dotnet run System.ArgumentNullException: for a simple program with new installation of .netcore 2.1.401

# General

Trying to get started with .netcore programming. Followed the basic tut from asp.net website but failed.

https://www.asp.net/get-started

I get the error (attached) after dotnet run command. 

[Powershell output](https://codeshare.io/5w3X9p)

This is my first ever program after a fresh installation of the latest SDK (as of now). I have tried console app and it works fine. Even a simple app with 'web' template works ok and display 'Hello World' in the browser. However, as soon as I add 'services.addMVC' to the app it breaks with the same error. I have done all my research and tried a lot of things, but not sure what is happening.

Program files:
[Files](https://app.box.com/s/kzsy7t5tzmg93ykqkhvxbyci1l5zgre7)

---

@noorrocks commented on [Thu Aug 30 2018](https://github.com/dotnet/core/issues/1904#issuecomment-417336820)

After wrestling with this problem for two days, finally, I have caught the issue.

if you see the 'powershell output', my project directory is ' Directory: C:\#NIN\dotnetcore'

Somehow, it doesn't like the '#' in a folder name. I created a new folder without '#' and it worked like a charm.

I was also able to reproduce this problem on a different PC.

Please note that it only bothers the '#' if it's at the root folder name. Down the chain, it works OK.

This issue can be marked as a **known issue**, I think.

_Copied from original issue: dotnet/cli#9932_

**Comment by peterhuene** [comment]
_From @livarcocc on August 31, 2018 20:56_

@peterhuene can you take a look?

**Comment by peterhuene** [comment]
The exception is coming from ASP.NET MVC:

```
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError, Func`2 fileExists, Func`2 loadFile)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute.GetRelatedAssemblies(Assembly assembly, Boolean throwOnError)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.GetRelatedAssemblies(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.GetAssemblyItem(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.ResolveFromDependencyContext(DependencyContext dependencyContext)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationAssembliesProvider.ResolveAssemblies(Assembly entryAssembly)+MoveNext()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String entryAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at try1.Startup.ConfigureServices(IServiceCollection services) in C:\#NIN\dotnetcore\tryx\try1\Startup.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at try1.Program.Main(String[] args) in C:\#NIN\dotnetcore\tryx\try1\Program.cs:line 17
```

Having ` C:\#NIN\` as the root of this path appears to be tripping up the MVC `RelatedAssemblyAttribute`.

I suspect [this line](https://github.com/aspnet/Mvc/blob/a67d9363e22be8ef63a1a62539991e1da3a6e30e/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/RelatedAssemblyAttribute.cs#L118) might be treating `#` as an anchor, resulting in a root directory returned, which then gets converted to `null` by `Path.GetDirectoryName` and passed to `Path.Combine`, resulting in the exception.  Just a guess, though.

I'll move this to ASP.NET MVC.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this?

**Comment by mkArtakMSFT** [comment]
@noorrocks, this seems to indeed be caused by the `#` character in the path. Simply moving bits to a different folder would solve the issue. Feel free to send us a PR with the fix.

**Comment by LiryChen** [comment]
Hey, I am a first-timer looking for open source tasks to start off. I found this issue pretty interesting. Could I claim it? Is there anyone I can reach out to when I need help to understand the code and the issue?

**Comment by pranavkm** [comment]
> Could I claim it?

Sure, feel free to send us a PR. [Our wiki](https://github.com/aspnet/Home/blob/master/CONTRIBUTING.md#contributing-code-and-content) has some instructions for contributing code.

With regards to this specific exception, the issue lies here - https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/RelatedAssemblyAttribute.cs#L118-L121. The method is provided a URI to an assembly that looks like so: `file://c:/#NIN/dotnetcore/tryx/try1` and it's attempting to turn it into a path: `C:\#NIN\dotnetcore\tryx\try1`. The problem is `Uri.LocalPath` contains only the segment `C:\`, and the rest of the path is stashed away in the fragment. 

One way to fix it might be to try to reconstruct the separate components. Another alternative might be to [not use the URI path](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/RelatedAssemblyAttribute.cs#L123) if it happens to contain a query or fragment component. Hope this helps.

**Comment by LiryChen** [comment]
Sounds great! I will look into that!

**Comment by obayit** [comment]
> > Could I claim it?
> 
> Sure, feel free to send us a PR. [Our wiki](https://github.com/aspnet/Home/blob/master/CONTRIBUTING.md#contributing-code-and-content) has some instructions for contributing code.
> 
> With regards to this specific exception, the issue lies here - https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/RelatedAssemblyAttribute.cs#L118-L121. The method is provided a URI to an assembly that looks like so: `file://c:/#NIN/dotnetcore/tryx/try1` and it's attempting to turn it into a path: `C:\#NIN\dotnetcore\tryx\try1`. The problem is `Uri.LocalPath` contains only the segment `C:\`, and the rest of the path is stashed away in the fragment.
> 
> One way to fix it might be to try to reconstruct the separate components. Another alternative might be to [not use the URI path](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/RelatedAssemblyAttribute.cs#L123) if it happens to contain a query or fragment component. Hope this helps.

I think the correct path is file:///c:#NIN/dotnetcore/tryx/try1
According to this article: 
>Incorrect: file:////applib/products/a%2Db/ abc%5F9/4148.920a/media/start.swf
>Correct: file://applib/products/a-b/abc_9/4148.920a/media/start.swf
https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/

**Comment by obayit** [comment]
@mkArtakMSFT  I think this problem is really hard and should not be labled "up-for-grabs"!

Also if you can help me with something: I tried to fix it but don't know how to actually test it by running "dotnet run". how can I use the newly built mvc DLLs?

**Comment by LiryChen** [comment]
Yeah I was looking at the code but had no idea how to start. Sorry I don't think I can work on this.

**Comment by sqdavid** [comment]
Hey! I think its up for grabs?
Would like to take a chance =] if so, let me know
Thanks

**Comment by pranavkm** [comment]
@sqdavid all yours to try 👍

**Comment by sqdavid** [comment]
yay! hope can find another issue I can help with =]

**Comment by obayit** [comment]
@sqdavid  is it ok to just ignore assemblies containing the # character?

**Comment by mkArtakMSFT** [comment]
>how can I use the newly built mvc DLLs?

@obayit, you could update the dependencies of the https://github.com/aspnet/Mvc/blob/release/2.2/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj project and that would give you a fully functional MVC app with your custom dependencies.

**Comment by obayit** [comment]
> > how can I use the newly built mvc DLLs?
> 
> @obayit, just noticed your comment. Just to make sure I answered your question, you could update the dependencies of the https://github.com/aspnet/Mvc/blob/release/2.2/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj project and that would give you a fully functional MVC app with your custom dependencies.

Do you mean that I should write a test function to make sure my fix worked?

**Comment by sqdavid** [comment]
> @sqdavid is it ok to just ignore assemblies containing the # character?

My first implementation was reconstructing Codebase using the fragment, but, as @pranavkm commented in my PR, usually we can trust LocalPath =]

https://github.com/aspnet/Mvc/pull/8556#discussion_r223122587

**Comment by sqdavid** [comment]
> > > how can I use the newly built mvc DLLs?
> > 
> > 
> > @obayit, just noticed your comment. Just to make sure I answered your question, you could update the dependencies of the https://github.com/aspnet/Mvc/blob/release/2.2/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj project and that would give you a fully functional MVC app with your custom dependencies.
> 
> Do you mean that I should write a test function to make sure my fix worked?

I built 3 new Unit Tests to validate my PR, but if you do a "dotnet run" you could test this specific implementation =]
