### ISSUE TITLE
Add support for kebab casing controllers and actions

### ISSUE THREAD

**Issue by rustd** [aspnet/Mvc#837]
**Edit:** We want to support updating the controller name and action name from Pascal cases to kebab case using an application convention:

e.g.

```c#
public class TodoListController
{
     public class IActionResult AddItem([FromBody]Item item)
     {
         ...
     }
}
```

Is accessible (with default routes) through `/TodoList/AddItem`

By applying the suggested application convention globally (or to the controller) the url will now be `/todo-list/add-item`, this should apply both to incoming urls as well a link generation.

Related to - aspnet/routing#140

**Original comment:**
Porting this from ASP.NET User voice site. https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/2047045-add-stuff-like-a-lowercaseroute-to-core
Following is an example of what we need to support. http://lowercaseroutesmvc.codeplex.com/

**Comment by yishaigalatzer** [comment]
@rosieks we don't plan to add support for pluralization.

When it comes to modifying controller name, it is rather easy by applying a global application convention. We can consider building one in the box as part of this, but it is definitely doable by the user.

@NTaylorMullen can you please make your code from tag helpers available publically

**Comment by NTaylorMullen** [comment]
A snippet to convert from `PascalCase` to lower-kebab (DocumentType => document-type) for reference:

```C#
var name = "DocumentType";
var regex = new Regex("(?<!^)((?<=[a-zA-Z0-9])[A-Z][a-z])|((?<=[a-z])[A-Z])", RegexOptions.None);

// Outputs "document-type"
Console.WriteLine(regex.Replace(name, "-$1$2").ToLowerInvariant());

// Other outputs:
// SomeThing => some-thing
// capsONInside => caps-on-inside
// CAPSOnOUTSIDE => caps-on-outside
// ALLCAPS => allcaps
// One1Two2Three3 => one1-two2-three3
// ONE1TWO2THREE3 => one1two2three3
// First_Second_ThirdHi => first_second_third-hi
```

We do this in `TagHelper`s.

**Comment by OlsonDev** [comment]
+1
