### ISSUE TITLE
PagedBufferedTextWriter creates too many async statemachines 

### ISSUE THREAD

**Issue by benaadams** [aspnet/Mvc#8370]
`PagedBufferedTextWriter` is used to allow sync writes from `IHtmlContent` types without blocking threads and gumming up the async nature of ASP.NET Core.

However it acts overly conservatively in case something has been sync written when it normally hasn't. This causes lots of additional async statemachines to be created:

1 request in the RazorRendering benchmarkapp https://github.com/aspnet/Mvc/pull/8366 currently creates 9,764 FlushAsync statemachines and 8,774 WriteAsync statemachines

![image](https://user-images.githubusercontent.com/1142958/44939983-7e879000-ad81-11e8-9650-95d867849141.png)

**Comment by mkArtakMSFT** [comment]
Thanks @benaadams.
