### ISSUE TITLE
Redundant check ' if (actionContext == null) ' in ActionContext.cs

### ISSUE THREAD

**Issue by nour-s** [aspnet/Mvc#8374]
I'm not sure if this is the right way to report this, but please let me know how to do it better.

It is a minor observation, that checking 

https://github.com/aspnet/Mvc/blob/a67d9363e22be8ef63a1a62539991e1da3a6e30e/src/Microsoft.AspNetCore.Mvc.Abstractions/ActionContext.cs#L39

is useless, because if that's true, it would fail earlier at
https://github.com/aspnet/Mvc/blob/a67d9363e22be8ef63a1a62539991e1da3a6e30e/src/Microsoft.AspNetCore.Mvc.Abstractions/ActionContext.cs#L33-L38

when calling the base class's constructor.

**Comment by HassanHashemi** [comment]
You can submit a PR.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nour-s.
Indeed this seems redundant. Would you be interested in submitting a PR with the fix?

**Comment by HassanHashemi** [comment]
@nour-s @mkArtakMSFT 
here it is
https://github.com/aspnet/Mvc/pull/8379
