### ISSUE TITLE
Debugging ASP.NET Source From Visual Studio

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Mvc#8375]
#### Is this a Bug or Feature request?:
Question

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

- Start a new ASP.NET Core project -> MVC type
- Configure remote debugging: [Debugging ASP.NET Core 2.0 Source Code](https://www.stevejgordon.co.uk/debugging-asp-net-core-2-source)
- Set a breakpoint on `SelectCandidates` (reference: [Debugging ASP.NET Core 2.0 source code - breakpoints](https://blog.reyno.co.uk/debugging-asp-net-core-source-code/))
   - That should set a break point on `Microsoft.AspNetCore.Mvc.Internal.SelectCandidates`
- F5 and step through the code in `SelectCandidates`

#### Description of the problem:

- Stepping through the code, via F10, skips over lines
- Many of the variable values cannot be inspected

> cannot obtain value of the local variable or argument because it is not available at this instruction pointer, possibly because it has been optimized away.

>Cannot evaluate expression because a thread is stopped at a point where garbage collection is impossible, possibly because the code is optimized.	

![trouble debugging asp net core source](https://user-images.githubusercontent.com/14079228/44957355-6f96ff80-ae9f-11e8-9f9a-35e3aabb9ca7.gif)

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

2.0.0

#### Questions

- Where can/should I report issues around this experience?
- Are there any official docs on this?
- I assume a lot of the behavior I'm seeing is because I'm trying to debug `Release` assemblies.  Are `Debug` build assemblies available?

**Comment by spottedmahn** [comment]
Reference: [Developer Community -> Debugging ASP.NET Core -> The following breakpoint cannot be set](https://developercommunity.visualstudio.com/content/problem/326187/debugging-aspnet-core-the-following-breakpoint-can.html)

**Comment by mkArtakMSFT** [comment]
Hi @spottedmahn.
@pranavkm, I assume this is because of compiler optimizations for `Release` build, correct? So what will be the options?

**Comment by pranavkm** [comment]
> ,I assume this is because of compiler optimizations for Release build, correct?

Yup. 

>  Are Debug build assemblies available?

We do not build or publish Debug builds on our CI.

> So what will be the options?

Usually I rebuild the branch or tag locally and replace the binaries.

**Comment by mkArtakMSFT** [comment]
Thanks @pranavkm.
@spottedmahn, so seems that the behavior you're observing is by design. Please consider using the suggestion from @pranavkm to achieve what you want.

**Comment by spottedmahn** [comment]
Hi @mkArtakMSFT  and @pranavkm - thanks for the replies!

Any thoughts on these questions?

>Where can/should I report issues around this experience?

>Are there any official docs on this?

**Comment by mkArtakMSFT** [comment]
@spottedmahn, the experience is an effect of compiler optimizations. So it's expected to behave like that. Hence, this is not really an issue by any means.
Regarding the official docs, are you looking for docs on the compiler optimization topic?

**Comment by spottedmahn** [comment]
Hi @mkArtakMSFT 👋

>the experience is an effect of compiler optimizations. So it's expected to behave like that. Hence, this is not really an issue by any means.

I understand.  I was using the term "issue" loosely.  The Github version of an "issue".  Where should I be posting questions/issues/feedback regarding this feature?

>Regarding the official docs, are you looking for docs on the compiler optimization topic?

No.  Official doc pages on [setting VS up](https://www.stevejgordon.co.uk/debugging-asp-net-core-2-source).  And [setting breakpoints](https://blog.reyno.co.uk/debugging-asp-net-core-source-code/).

**Comment by mkArtakMSFT** [comment]
I don't think that will get any traction, but sure, you can send a feedback by clicking the `Send feedback`  button in the top right side of the VS window:
![image](https://user-images.githubusercontent.com/34246760/45124746-50f36b80-b120-11e8-9728-7f2fbe5c4c97.png)
