### ISSUE TITLE
Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error MSB6003: The specified task executable "dotnet" could not be run. The specified executable is not a valid application for this OS platform

### ISSUE THREAD

**Issue by edem-e-akoussanh** [aspnet/Mvc#8380]
#### Is this a Bug or Feature request?:
Bug: Unable to build and run Asp.Net Core 2.1 projects.

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
1.  dotnet new mvc
2.  build and run

#### Description of the problem:
Any Asp.net core 2.1 project ends up with this error, during build and run:
1>------ Build started: Project: WebApplication1, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.1\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error MSB6003: The specified task executable "dotnet" could not be run. The specified executable is not a valid application for this OS platform.
1>Done building project "WebApplication1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I tried uninstalling dotnet sdk and re-installing but problem still persists. 

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <UserSecretsId>aspnet-WebApplication1-B780E107-3B99-4B5A-9A15-493D503F8A95</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.3" PrivateAssets="All" />
  </ItemGroup>

</Project>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @edem-e-akoussanh.
@pranavkm, can you please investigate this? Thanks!

**Comment by pranavkm** [comment]
Could you run `dotnet --info`? I wonder if you have both 32 and 64-bit dotnet installed on your machine and the 32-bit exe appears earlier in PATH.

**Comment by pranavkm** [comment]
Would you mind running `dotnet clean; dotnet build /bl` on the project and attaching the msbuild.binlog file? We could tell the path to the exe that the failing task is attempting to resolve. Perhaps that should give us some clues.

**Comment by edem-e-akoussanh** [comment]
[msbuild.zip](https://github.com/aspnet/Mvc/files/2349666/msbuild.zip)

**Comment by pranavkm** [comment]
@edem-e-akoussanh the build log you attached says that it succeeded (doesn't contain the error you initially reported). Are you still seeing the original issue?

**Comment by edem-e-akoussanh** [comment]
I just noticed by using the dotnet build /bl command, build is successful and app can run.

However, upon initial project creation in VS, same error persists for .net core 2.1 projects. It doesn't behave so with .net core 2.0 projects.

I might have to use the CLI to build /bl before running .net core 2.1 projects.

I'd consider it a workaround in the meantime....

**Comment by edem-e-akoussanh** [comment]
Thanks for the support guys....

**Comment by pranavkm** [comment]
Hmm, it might be that VS is referencing a 32-bit SDK. Here's a couple of suggestions I'd try:

1) Try removing 32-bit SDKs (Using Programs & Features) if they're installed.
2) Repair the 64-bit SDK. This should add it to your path.
3) Restart VS so that it refreshes env variables.

If you still see this issue persist, feel free to reopen this issue.
