### ISSUE TITLE
ModelValidation EmailAddress is buggy

### ISSUE THREAD

**Issue by Kris0** [aspnet/Mvc#8381]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Create a Model with a Single Property string, annotate it with [EmailAddress] and a View with a input that binds the value of the input to the model.

Now type as Email:
SomeThing@.com 

#### Description of the problem:

See the ModelState beeing valid.

#### Version `Microsoft.AspNetCore.All`:
2.0.5

**Comment by mkArtakMSFT** [comment]
Thanks for filing this issue. We will investigate this as part of the referenced issue which also you've filed.

**Comment by dougbu** [comment]
@Kris0 the `[EmailAddress]` attribute is not part of ASP.NET Core. Instead, it ships with .NET Framework and .NET Core.

I believe .NET has had issues related to this attribute rejecting valid email addresses. At the moment, the .NET Core version does little more than confirm the value contains an `'@'`. Suggest using a `[RegularExpression]` attribute with the patterns your application supports (though this has performance implications). The .NET Framework version may be more complicated.

FYI the .NET Core source is found [here](https://github.com/dotnet/corefx/blob/35fed5e0ddb8225bd9bcb1de330ca675227a3a7b/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs).
