### ISSUE TITLE
Url Annotation is buggy

### ISSUE THREAD

**Issue by Kris0** [aspnet/Mvc#8382]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Create a Model with a Single Property string, annotate it with [Url] and a View with a input that binds the value of the input to the model.

Now type as Url:
https://httpsblabla

#### Description of the problem:
See the ModelState beeing valid.

#### Version Microsoft.AspNetCore.All:
2.0.5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Kris0.
Can you please share a repro project for us to investigate (ideally as a github repo).

@dougbu, can you please investigate this? Thanks!

**Comment by mkArtakMSFT** [comment]
Seems related: https://github.com/aspnet/Mvc/issues/8381

**Comment by dougbu** [comment]
@Kris0 the `[Url]` attribute is not part of ASP.NET Core. Instead, it ships with .NET Framework and .NET Core.

I believe .NET has had issues related to this attribute rejecting valid URLs. At the moment, the .NET Core version does little more than confirm the value starts with a recognized scheme. Suggest using a `[RegularExpression]` attribute with the patterns your application supports (though this has performance implications). The .NET Framework version may be more complicated.

By the way, https://httpsblabla is a completely valid URL on a private network.

FYI the .NET Core source is found [here](https://github.com/dotnet/corefx/blob/35fed5e0ddb8225bd9bcb1de330ca675227a3a7b/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/UrlAttribute.cs).

**Comment by Kris0** [comment]
Thank you for the information. I already use [RegularExpression] in my projects instead of the [URL] or the [EmailAddress] annotations. Yes you are absolutely right, https://httpsblabla is a valid URI in a private network but i think most people would assume we talk about absolute addresses in the www if we see the annotation URL. Maybe it should be renamed in URI ? (or maybe that's just my opinion?)
