### ISSUE TITLE
ASP.NET Core 2.1.0 breaks attribute-routed endpoints in applications targeting Microsoft.NET.Sdk

### ISSUE THREAD

**Issue by strawd** [aspnet/Mvc#8388]
#### Is this a Bug or Feature request?:

Bug or breaking change

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

1. Run `dotnet new webapi`
2. Run `dotnet run`
3. Make a request, ex. run `curl -k https://localhost:5001/api/values` and verify that the response is a `200 OK`
4. Stop the application
5. Edit the project file to change the `Sdk` attribute to `Microsoft.NET.Sdk` and add `<OutputType>Exe</OutputType>` to the first `<PropertyGroup>` tag
6. Run `dotnet run`
7. Make the same request as before, and observe that the response is now `404 Not Found`

#### Description of the problem:

We found that updating from `Microsoft.AspNetCore.All` version 2.0.9 to version 2.1.0 or switching to the `Microsoft.AspNetCore.App` package (which starts at version 2.1.0) breaks applications exposing attribute-routed web APIs when the SDK of the project is `Microsoft.NET.Sdk`, as opposed to `Microsoft.NET.Sdk.Web`.

After updating the dependency, all of the web API endpoints return a 404 error early in the pipeline instead of processing through to the controller. We see the following logged by the framework:

```
TRACE Microsoft.AspNetCore.Server.Kestrel            Begin Scope: ConnectionId:0HLGJ95MK9TK0
DEBUG Microsoft.AspNetCore.Server.Kestrel            Connection id "0HLGJ95MK9TK0" started.
TRACE Microsoft.AspNetCore.Hosting.Internal.WebHost  Begin Scope: RequestId:0HLGJ95MK9TK0:00000001 RequestPath:<path>
DEBUG Microsoft.AspNetCore.Hosting.Internal.WebHost  Request starting HTTP/1.1 GET <uri> application/json
DEBUG Microsoft.AspNetCore.Builder.RouterMiddleware  Request did not match any routes.
DEBUG Microsoft.AspNetCore.Builder.RouterMiddleware  Request did not match any routes.
DEBUG Microsoft.AspNetCore.Server.Kestrel            Connection id "0HLGJ95MK9TK0" completed keep alive response.
INFO  Microsoft.AspNetCore.Hosting.Internal.WebHost  Request finished in 197.7742ms 404
TRACE Microsoft.AspNetCore.Hosting.Internal.WebHost  End Scope: RequestId:0HLGJ95MK9TK0:00000001 RequestPath:<path>
```

We found that explicit routes do still work as expected, so the issue only affects attribute routing. The issue existed whether we used 2.0 conventions or 2.1 conventions (using `CompatibilityVersion.Version_2_1` and the `[ApiController]` attribute).

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

Issue observed in `Microsoft.AspNetCore.App` and `Microsoft.AspNetCore.All` versions 2.1.0, 2.1.1, 2.1.2 and 2.1.3.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @strawd.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
> Edit the project file to change the Sdk attribute to Microsoft.NET.Sdk and add <OutputType>Exe</OutputType> to the first <PropertyGroup> tag

MVC 2.1.0 requires compilation context to be available. Compilation context tells it if a library references MVC which is used as a filter to skip assemblies that are deemed unlikely to have controllers. Microsoft.NET.Sdk does not set `<PreserveCompilationContext>true</PreserveCompilationContext>` which would explain why you're seeing this.

**Comment by mattzink** [comment]
Would an acceptable fix then just be to set `<PreserveCompilationContext>true</PreserveCompilationContext>` in the csproj that contains controllers? That seems to fix the issue.

**Comment by pranavkm** [comment]
That would help. @natemcmaster \ @JunTaoLuo is there anything about the AspNetCore.App metapackage that requires referencing the Web Sdk?

**Comment by natemcmaster** [comment]
> is there anything about the AspNetCore.App metapackage that requires referencing the Web Sdk?

Only the Web Sdk works with a versionless PackageRef to AspNetCore.App. If you can't use the web Sdk for other reasons, you can easily workaround by adding the Version attribute to the PackageReference element.

**Comment by mattzink** [comment]
@natemcmaster Is it correct that for the AspNetCore.App package version that the major & minor numbers match the corresponding runtime version, and the third number is always zero?

**Comment by pranavkm** [comment]
> Is it correct that for the AspNetCore.App package version that the major & minor numbers match the corresponding runtime version, and the third number is always zero?

That's not entirely correct - https://github.com/aspnet/websdk/blob/master/src/Web/Microsoft.NET.Sdk.Web.Targets/Sdk.DefaultItems.targets#L41

**Comment by natemcmaster** [comment]
It was our intention to keep it at "2.1.0", but we made a mistake and had to bump the package to 2.1.1. Our hope is that in 2.2, the implicit package version will stay at "2.2.0".

**Comment by mariotacke** [comment]
Our team just ran into the same problem. We are using `<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.5" />`. The `PreserveCompilationContext` fix works, but we are unsure whether there are other implications of this or not. Can you clarify @mattzink ? Also, is this documented anywhere?
