### ISSUE TITLE
Specifying ProducesAttribute stops the use of API conventions

### ISSUE THREAD

**Issue by steveoh** [aspnet/Mvc#8389]
#### Is this a Bug or Feature request?:
Bug or misunderstanding of feature and possibly a feature request

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

Consider having multiple api methods with different 200 generic response types and different method names and signatures but all the other status codes produce the same result object. I think this is a pretty typical/common scenario for api's.

```cs
/// <response code="400">yada</response>
/// <response code="404">yada</response>
/// <response code="500">yada</response>
[HttpGet]
[ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ApiResponseContainer<Result>))]
[ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(ApiResponseContainer))]
[ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(ApiResponseContainer))]
[ProducesResponseType(StatusCodes.Status500InternalServerError, Type = typeof(ApiResponseContainer))]
[Route("yadayada")]
public async Task<ObjectResult> Method(string a, string b, [FromQuery] Object options)
```

I tried to remove the duplication into a convention.

```cs
public static MyConvention {
[ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(ApiResponseContainer))]
[ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(ApiResponseContainer))]
[ProducesResponseType(StatusCodes.Status500InternalServerError, Type = typeof(ApiResponseContainer))]
public static void Default() {}
}
```

```cs
[HttpGet]
[ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ApiResponseContainer<Result>))]
[ApiConventionMethod(typeof(MyConvention), nameof(MyConvention.Default))]
[Route("yadayada")]
public async Task<ObjectResult> Method(string a, string b, [FromQuery] Object options)
```

#### Description of the problem:
It appears you cannot merge existing method attributes with an api convention method because it's not a feature/implemented or that it wasn't applied because the signatures don't match. When I tried this, only the xml comments where being used in the doc.

I would like `[ApiConventionTypeMatch(ApiConventionTypeMatchBehavior.Any)]` to work on method and parameter signatures (if that is the reason of my issue) in order to remove some of the doc code into a convention that can be reused across the api. 

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

```
dotnet --version
2.2.100-preview1-009349
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.0-preview1-35029"/>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @steveoh.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
> It appears you cannot merge existing method attributes with an api convention method

Yes, that's the intended design. Specifying a `ProducesResponseType` attribute on an action in treated as a gesture to opt out of conventions; there isn't a merge semantic for the two. One way to use a convention in your particular scenario would be to

a) Add a `[ProducesResponseType(StatusCodes.Status200OK)]` to the convention 
b) Remove `ProducesResponseType` attributes from your action 
c) Return a `ActionResult<ApiResponseContainer<Result>>` from your action

**Comment by steveoh** [comment]
Thanks, I will try that and get back to you!

**Comment by steveoh** [comment]
@pranavkm That seems to partially fix the issue. The `ProducesResponseType.Type` is not coming through from the convention attributes for the 400, 404, and 500. 

I would like to continue to display that in the open api docs.

The type does come through for the 200 based on the action result.

Is there a way to preserve the types from the convention?

I'm noticing that the convention isn't working at all actually. The 400, 404, and 500 are only coming through because of the xml comments.

https://github.com/steveoh/webapi-core/commit/1a0424708227296ee710f3d88b3f50258b8ccb0d is the commit to use the convention. Do you see any issues with this?

**Comment by pranavkm** [comment]
The issue crops up because of the `ProducesAttribute` on your controller - https://github.com/steveoh/webapi-core/commit/1a0424708227296ee710f3d88b3f50258b8ccb0d#diff-55e8ad701f9604df8e02389acd507e77L29.  Going back to my previous comment, the opt-out semantics is basically the presence of one or more filters that implement `IApiResponseTypeMetadataProvider`. Both `ProducesAttribute` and `ProducesResponseTypeAttribute` implement this contract, so it basically knocks the convention out.

The behavior does seem a bit surprising, I'll see if we can tweak the behavior to allow specifying `ProducesAttribute` on an action or a controller while still allowing a convention to apply.

**Comment by pranavkm** [comment]
cc @rynowak \ @glennc

**Comment by rynowak** [comment]
If [Produces] with no types breaks conventions that's a bug and it needs to be fixed

**Comment by steveoh** [comment]
@pranavkm I upgraded to 2.2 preview 2 and if I remove

```cs
[Produces("application/json")]
```

from my controller the conventions are applied. But I cannot specify the content type in the conventions so I need to keep that on my controller. In doing so, the other conventions are still opting out. 

I'm using the `Produces(string contentType)` usage, not a `Type` so I feel as though it should be working.

Thoughts?

**Comment by pranavkm** [comment]
@steveoh the fix went in to preview3 - MVC will continue applying conventions when a `Produces("some-content-type")` is applied to the action or the controller.  @ryanbrandenburg is there a way @steveoh could try out the preview3 nightlies? I'm not entirely sure where the builds are for it.

**Comment by ryanbrandenburg** [comment]
preview3 nightly packages are [here](https://dotnet.myget.org/gallery/aspnetcore-dev). The nightly shared framework can be found [here](https://github.com/aspnet/Universe#aspnet-core-shared-framework).

**Comment by steveoh** [comment]
OK thanks. How in the future would I know which release the code is in? Is there an obvious way to know?

**Comment by pranavkm** [comment]
> Would it be in the nightlies because milestone preview 3 is still in progress?

Yup.

> How in the future would I know which release the code is in?

The fix is in the preview3 release which is likely to be out mid-October. We usually do an annoucement for it like so - https://blogs.msdn.microsoft.com/webdev/2018/09/12/asp-net-core-2-2-0-preview2-now-available/
