### ISSUE TITLE
新人求助，lambda表达式查询出错

### ISSUE THREAD

**Issue by GreenHand-Ben** [aspnet/Mvc#8393]
![image](https://user-images.githubusercontent.com/42233756/45142423-19052a80-b1eb-11e8-9922-150666002bc0.png)
代码不是我写的，是公司老员工写的，请问出现这样的错误是怎么回事，小白求助，勿喷。。

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GreenHand-Ben.It's not clear what the issue is here and what your'e running into.
Can you please provide more details about the scenario as well as share with us a simple repro project?

**Comment by GreenHand-Ben** [comment]
Sorry, This is my company project, I have no examples in my hands. I can't make it public at will. Thank you very much.

**Comment by mkArtakMSFT** [comment]
@GreenHand-Ben, unfortunately there is not enough information for us to assist you in any way.
