### ISSUE TITLE
Add Assembly at Runtime #7316

### ISSUE THREAD

**Issue by ErcinDedeoglu** [aspnet/Mvc#8394]
https://github.com/aspnet/Mvc/issues/7316#issue-292684543

**Comment by pranavkm** [comment]
Can you share a repro app?

**Comment by ErcinDedeoglu** [comment]
https://github.com/ErcinDedeoglu/Swashbuckle.AspNetCore.Issue1

**Comment by pranavkm** [comment]
Seems to be working fine - what exactly is the issue you're seeing?
![image](https://user-images.githubusercontent.com/174281/45231830-510b7c80-b282-11e8-9c07-99e067e42cf3.png)

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
