### ISSUE TITLE
Providing a base path from "outside" does no longer work (migration from 1.1.x to 2.1.x)

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#8398]
In our web tests we host a Kestrel server for our web assembly, in 1.x we did it in the following way:

    var webHost = new WebHostBuilder()
      .UseContentRoot(webClientProjectDirectory)
      .UseEnvironment("WebTesting")
      .UseSetting(WebHostDefaults.ApplicationKey, applicationAssemblyName)
      .UseStartup<TStartup>()
      .UseUrls(url)
      .UseKestrel()
      .Build();

Moving to 2.x we used the new program pattern instead:

    var host = WebHost.CreateDefaultBuilder()
      .UseContentRoot(webClientProjectDirectory)
      .UseEnvironment("WebTesting")
      .UseStartup<TStartup>()
      .UseUrls(url)
      .Build();

However, now we run into the following problem:

> System.InvalidOperationException : A path base can only be configured using IApplicationBuilder.UsePathBase().

What's the correct way to do this?

**Comment by drauch** [comment]
It looks like the problem is with UseUrls() if the URL contains a base path. If we remove the base path it works. However, we want to apply such a base path FROM OUTSIDE? (please don't tell me to call UseBasePath inside Startup.Configure ;))

**Comment by drauch** [comment]
Not providing the base path via UseUrls() and instead using UseBasePath() also seems to prevent the UseStatusCodePagesWithReExecute to use the correct root path, i.e., a path of "/Error" in UseStatusCodePagesWithReExecute does not use the configured base path.

**Comment by pranavkm** [comment]
@JunTaoLuo is this the same issue as https://github.com/aspnet/Home/issues/3495?

**Comment by JunTaoLuo** [comment]
Though this is the same error, I think the scenario is different.

@drauch what do you mean by "from outside"? Is the requirement here to set the base path based on an environment variable? If so, I think it would be easiest to set two separate environment variables, one for the url and one for the path base and call UseUrls and UseBasePath on the two environment variables. While we have an explicit configuration key for urls: https://github.com/aspnet/Hosting/blob/master/src/Microsoft.AspNetCore.Hosting.Abstractions/WebHostDefaults.cs#L17, we don't have one for base path: https://github.com/aspnet/Hosting/issues/1120. You'll need to set and read your own environment variable with a custom name.

**Comment by JunTaoLuo** [comment]
Unfortunately we don't have a first class way of doing this on the WebHostBuilder. The issue I linked https://github.com/aspnet/Hosting/issues/1120 is the enhancement that would address this. Closing as dupe cc @Tratcher @davidfowl. 

@drauch The closest thing I can think of to what you want to do is to create a StartupFilter that adds the call to UsePathBase:
```c#
    public class PathBaseStartupFilter : IStartupFilter
    {
        public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
        {
            return builder =>
            {
                builder.UsePathBase(Environment.GetEnvironmentVariable("CUSTOM_PATH_BASE"));
                next(builder);
            };
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureServices(services =>
                {
                    services.AddTransient<IStartupFilter, PathBaseStartupFilter>();
                })
                .UseStartup<Startup>();
    }
```

**Comment by drauch** [comment]
@JunTaoLuo : Thank you for the workaround! Hope that https://github.com/aspnet/Hosting/issues/1120 will be implemented!
