### ISSUE TITLE
Cannot find reference assembly Microsoft.AspNetCore.Mvc.Razor.ViewCompilation-x64.exe

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#8399]
In our web tests we host our web application (in-process) using Kestrel. While running the actual web application works, it fails to do so in our web tests. The error is:

> Cannot find reference assembly 'Microsoft.AspNetCore.Mvc.Razor.ViewCompilation-x64.exe' file for package Microsoft.AspNetCore.Mvc.Razor.ViewCompilation-x64

ViewCompilation is probably disabled, as we target the full .NET framework and do not reference the ViewCompilation.dll ... so I'm a little bit surprised to see the exe missing.

What are we doing wrong?

**Comment by drauch** [comment]
Maybe ViewCompilation is on, the error is gone after setting MvcRazorCompileOnPublish to false in the csproj.

Don't we need to package reference the ViewCompilation package in order to enable view compilation when targeting .NET full framework?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @drauch.
What is the SDK version you're using?

**Comment by pranavkm** [comment]
> Don't we need to package reference the ViewCompilation package in order to enable view compilation when targeting .NET full framework?

That sounds right. Do you see a reference to it when you search for the ViewCompilation package in solution explorer? It should tell you what project's referencing it.

**Comment by drauch** [comment]
@mkArtakMSFT :  2.1.401

@pranavkm : No, a grep search for "ViewCompilation" in my solution does not bring up any results.

**Comment by pranavkm** [comment]
Strange, perhaps you have stale targets and props files in your obj directory? I tried this in a clean app and don't see any signs of the precompilation tool executing. Can you try doing a clean build and see if the problem still appears? If so, could you share project?

**Comment by mkArtakMSFT** [comment]
@drauch, did @pranavkm 's suggestion solve your issue?

**Comment by drauch** [comment]
No, not really. We're living with view compilation explicitly disabled in the csproj now, so we are currently not going to invest more time into this issue.

It's still weird ... maybe referencing an ASP.NET Core web application project from a unit test project hinders the automatic disable mechanism?

**Comment by pranavkm** [comment]
> It's still weird ... maybe referencing an ASP.NET Core web application project from a unit test project hinders the automatic disable mechanism?

Any chance you could share a repro app? It's super strange that targets from the package execute without references to the package.

**Comment by drauch** [comment]
We'll not find the time to do a repro, sorry. Hint though: we've now also removed all runtime identifiers referencing win7-x86 and switching compilation to AnyCPU - now view compilation works. Can probably be closed. Thanks for engaging!
