### ISSUE TITLE
WebApplicationFactory WithWebHostBuilder configuration priority seems wrong

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8406]
_From @jdmichel on Wednesday, 05 September 2018 20:31:59_

I'm trying to upgrade an integration test and related app from aspnetcore 2.0 to 2.1, and running into problems with configuration settings and WebApplicationFactory. 

If I use the following code, then the existing setting in appsetting.json takes precedence over the setting for the test.

```c#
// From the integration test constructor...
var client = factory.WithWebHostBuilder(builder =>
            {
                builder.UseSetting("Foo:Bar", "True");
            }).CreateClient();
```

If I remove the setting from appsettings.json then I get the value from the setting above. 
It seems that WithWebHostBuilder() is adding a new provider at the head of the list instead of the tail. I think you would always want the programmatic UseSetting to take precedence over all the other configuration providers. 

My workaround is to keep using the previous code which used TestServer explicitly like so:

```c#
_server = new TestServer(WebHost.CreateDefaultBuilder().UseStartup<Startup>());
var client = _server.CreateClient();
```

This reads settings from a local copy of the appsettings.json file from the integration test directory, but at least it works.

Since switching to 2.1 these tests all get BadRequest for every client call (the controller isn't even called) and I'm not sure why. Which is why I tried to update the tests to use the WebApplicationFactory. 

Something here seems to be an undocumented breaking change.

_Copied from original issue: aspnet/Home#3502_

**Comment by javiercn** [comment]
@jdmichel Thanks for reaching out.

WebApplicationFactory doesn't setup any specific configuration settings for your app.

I think what you should do is call 
```csharp
builder.ConfigureAppConfiguration((ctx, config) => {
    config.AddInMemoryCollection(new Dictionary<string,string>{
      ["Foo:Bar"] = "Baz";
    });
});
```

To add testing specific settings. For more details look how the default app setup is done in the link below.

https://github.com/aspnet/MetaPackages/blob/master/src/Microsoft.AspNetCore/WebHost.cs#L169

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
