### ISSUE TITLE
Start ASP.NET Core 2.0 Programmatically

### ISSUE THREAD

**Issue by Ghislain1** [aspnet/Mvc#8408]
I just want to start ASP.Net Web Api  by clicking a Button(WPF) from any Any WPF-App(.Net Framework).

Repro steps:

1. Start WPF App
2. Press e.g. Start Button
Expected: The server started and listenning on ...!

Is that possible?

**Comment by mkArtakMSFT** [comment]
@Ghislain1, did you get your issue resolved?

**Comment by Ghislain1** [comment]
@mkArtakMSFT 
The issue is still busted me.
The [similar question](https://stackoverflow.com/questions/50796931/launch-asp-net-core-web-api-programmatically) has been asked in StackOverflow

Do you have any idea to solve this problem?
Thank in advanced.
Ghis  from Germany.

**Comment by mkArtakMSFT** [comment]
@Ghislain1, here is another sample which showcases the same thing while referencing an existing ASP.NET Core web application project: https://github.com/mkArtakMSFT/Samples/tree/master/WpfAspNetCoreReference

**Comment by Ghislain1** [comment]
@mkArtakMSFT 
I sent a pull resquest, please can you review it. because i m not able to start the app
Thank you
