### ISSUE TITLE
Templates show up on some projects and not others.  Why?

### ISSUE THREAD

**Issue by Joebeazelman** [aspnet/Mvc#8427]
I am writing a NopCommerce plugin.  In NopCommerce's Visual Studio 2017 solution file, there are several standard plugins created as independent NetCore 2.1 library projects. If I right-click on any of their projects and select "new item from template", I am able to see and select MVC template items.  

For my project, however, I don't see these templates, but I did see standard and WPF ones.  I carefully compared my project configuration with their plugins and I couldn't find any differences.  After an hour of research, I discovered that by changing the project SDK the MVC templates showed up:

```
<Project SDK="Microsoft.NET.Sdk.Razor">
  ...
</Project>

instead of:

<Project SDK="Microsoft.NET.Sdk">
  ...
</Project>
```

This is clearly a bug.  All of the other plugins were recognized as MVC projects even though they are not configured as Microsoft.NET.Sdk.Razor.  Is Visual Studio caching the configuration information or stored in some cryptic location?  

Why are you guys constantly solving complexity by adding more complexity? Developing on the .NET platform officially unmanageable.  Developers are embracing alternative development strategies because of small, constant and time consuming issues like this.  Get your act together or find another line of business like growing turnips!

**Comment by mkArtakMSFT** [comment]
@Joebeazelman, since this is specific to VS experience, this feedback needs to go through `VS Feedback` tool. You can follow the instructions in this link: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017
