### ISSUE TITLE
When using the default API conventions the swagger doc generated by swashbuckle contains responses for status code "0"

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#8431]
When using the default API conventions the swagger doc generated by swashbuckle contains responses for status code "0".

```
"responses": {
    "200": {
        "description": "Success",
        "schema": {
            "$ref": "#/definitions/Pet"
        }
    },
    "404": {
        "description": "Not Found",
        "schema": {
            "$ref": "#/definitions/ProblemDetails"
        }
    },
    "0": {
        "schema": {
            "$ref": "#/definitions/ProblemDetails"
        }
    }
}
```

Is the "0" supposed to be "default" instead? Is this an issue with ASP.NET Core or Swashbuckle?

**Comment by rynowak** [comment]
IIRC this is a new feature that we added, Swashbuckle would need to update. We didn't have a representation before for 'default' status codes.

**Comment by mkArtakMSFT** [comment]
@rynowak, is there an issue in Swashbuckle repo tracking this?

Is this handled better by NSwag?

**Comment by pranavkm** [comment]
Thought I sent them a PR to address this - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/797/files. Maybe there's a bug.

**Comment by mkArtakMSFT** [comment]
Closing as external.
