### ISSUE TITLE
Question on RP partial view discovery

### ISSUE THREAD

**Issue by guardrex** [aspnet/Mvc#8432]
#### Is this a Bug or Feature request?:

Possible bug; possibly an *ID-10T error*

This is for work on the partial views doc expansion that covers RP: https://github.com/aspnet/Docs/issues/8188

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

https://github.com/guardrex/PartialViewsSample

#### Description of the problem:

The RP app here mirrors the layout and functionality of our current [MVC partial views sample app](https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/views/partial/sample/PartialViewsSample).

* Pages
  * ArticlesRP
    * ReadRP.cshtml
    * ReadRP.cshtml.cs
  * Shared
    * _AuthorPartialRP.cshtml
  * _AuthorPartialRP.cshtml

The ReadRP page (*Pages/ReadRP.cshtml*) calls for the partial by name (without a file extension):

```cshtml
@page
@model ReadRPModel

<h2>@Model.Article.Title</h2>
@*Pass the author's name to Pages\Shared\_AuthorPartialRP.cshtml*@
@await Html.PartialAsync("_AuthorPartialRP", Model.Article.AuthorName)
@Model.Article.PublicationDate
```

The code file (*ReadRP.cshtml.cs*) provides `Article` as a property of the page model ...

```csharp
public class ReadRPModel : PageModel
{
    public Article Article { get; private set; }

    public void OnGet()
    {
        Article = GetArticle();
    }

    private Article GetArticle()
    {
        var article = new Article
        {
            ...
        };
        article.Sections.Add({ ... });
        article.Sections.Add({ ... });
        article.Sections.Add({ ... });
        return article;
    }
}
```

`_AuthorPartialRP` exists in two files:

* In the *Shared* folder (*Pages/Shared/_AuthorPartialRP.cshtml*):

  ```cshtml
  @model string
  <div>
      <h3>@Model</h3>
      This partial view from /Pages/Shared/_AuthorPartialRP.cshtml.<br />
  </div>
  ```

* In the *Pages* folder (*Pages/_AuthorPartialRP.cshtml*):

  ```cshtml
  <div>
      <h3>Microsoft Docs (Razor Pages)</h3>
      Follow us at <a href="https://twitter.com/docsmsft">twitter.com/docsmsft</a>.
  </div>
  ```

Unlike the MVC approach, where the *Shared* partial view is used, the call in the ReadRP page for  `_AuthorPartialRP` **actually renders the `_AuthorPartialRP.cshtml` file in the _Pages_ folder and not from the _Shared_ folder**. It's not discovering/using the partial in the RP *Shared* folder.

<img width="234" alt="capture" src="https://user-images.githubusercontent.com/1622880/45267463-5a3b4b80-b432-11e8-9fb3-82e329d373ab.PNG">

Have I missed a concept? ... or is this a 🐞 candidate?

#### Version of `Microsoft.AspNetCore.App`

2.1.3

**Comment by mikebrind** [comment]
Partial discovery in Razor Pages is not the same as in MVC (where there is no _Pages_ folder by default). The search locations for partials in RP are (in order)

```
The current page's folder (if not Pages)
/Pages/_AuthorPartialRP.cshtml
/Pages/Shared/_AuthorPartialRP.cshtml
/Views/Shared/_AuthorPartialRP.cshtml
```

Change the name of the partial in the `PartialAsync` call to one that doesn't exist and re-run the page. You will get an error message detailing all the locations that were searched.

If you want to force the framework to pick one of a number of partials that share the same name, you can pass a relative path as the first parameter instead:

```
@await Html.PartialAsync("/Pages/Shared/_AuthorPartialRP", Model)
```

**Comment by guardrex** [comment]
Thanks @mikebrind ... by-design then. I'll document it this way. Thanks again.
