### ISSUE TITLE
UseStatusCodePagesWithReExecute behaves differently in 2.1.x (migration from 1.1.x)

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#8437]
Hi!

We migrated from ASP.NET Core 1.1.x to 2.1.x and run into problems with our `UseStatusCodePagesWithReExecute()` middleware.

Using `UseStatusCodePagesWithReExecute("/Error")` behaves different now. Previously, if the user was at `https://server/WebApp/12345` and run into an exception we could obtain `12345` from the route values when executing the Error controller action. Now it is not possible anymore.

Are the route values cleared in some way now? Why is this behaving differently? How to obtain `12345` when executing the Error action?

Maybe related:
Before upgrading we hosted our application at `https://server/WebApp/`, which is no longer possible in ASP.NET Core 2.1.x. We must host it at `https://server/` now and use `UsePathBase("/WebApp")` instead.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @drauch.
@rynowak, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Diagnostics#478
