### ISSUE TITLE
Unable to use client certificate authentication with WebApplicationFactory

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8439]
_From @karelz on Friday, 07 September 2018 14:12:44_

_From @vdachev on September 7, 2018 13:1_

Hello,

I'm trying to set up an integration test for a web application that uses certificate authentication. I use the following code fragment to instantiate the `HttpClient`:
```csharp
var factory = new WebApplicationFactory<Startup>();
HttpClient client = factory.CreateClient();
```
However, I want to pass a client certificate when requesting a resource. The problem is, the client certificate collection is stored in the `HttpClientHandler` but I could not find a way to provide the `WebApplicationFactory` constructor with an instance to the `HttpClientHandler`, neither I found a way to access it through the `HttpClient` or `WebApplicationFactory` instances.

Could you please hint me of a way to achieve that?

_Copied from original issue: dotnet/corefx#32159_

_Copied from original issue: aspnet/Home#3518_

**Comment by Eilon** [comment]
_From @Tratcher on Friday, 07 September 2018 15:19:49_

Client certificates are a TLS transport feature and WebApplicationFactory only uses an in-memory transport so there's no TLS involved, this isn't going to work out of the box.

WebApplicationFactory.TestServer does give you another way to do this though. Rather than using CreateClient, you can instead use CreateRequest and directly populate any server side fields you need for the test like the HttpContext.Connection.ClientCertificate.

**Comment by Eilon** [comment]
_From @vdachev on Monday, 10 September 2018 05:27:04_

Okay, that makes sense.

However, the `Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory<TEntryPoint>` has `Server` property that provides a `Microsoft.AspNetCore.TestHost.TestServer.CreateRequest` method returns a `Microsoft.AspNetCore.TestHost.RequestBuilder` instance. The latter holds references to the test server itself and an `System.Net.Http.HttpRequestMessage`, both of which don't seem to provide an (obvious) access neither to the HTTP connection, nor the HTTP context.

P.S. Meanwhile, I found that the `Microsoft.AspNetCore.TestHost.TestServer` class provides a `SendAsync` method with a `configureContext` parameter.

**Comment by Eilon** [comment]
_From @Tratcher on Monday, 10 September 2018 05:32:40_

Ah you're right, SendAsync(configureContext...) is the method you want.

**Comment by javiercn** [comment]
This is not something that WAF is concerned with. You could achieve this with WAF by registering an IStartupFilter instance where you setup the request given for example, an incoming header.

```csharp
public class CustomWAF : WebApplicationFactory<Startup>
{
    public override IWebHostBuilder ConfigureWebHost(IWebHostBuilder builder)
    {
       var myLoadedCerts = LoadCerts();
        builder.ConfigureServices(services => services.AddSingleton<IStartupFilter>(new CertificateConfiguration(myLoadedCerts));
    }
}

public class CertificateConfiguration : IStartupFilter
{
    public IDictionary<string, X509Certificate2> Certificates { get; }

    public CertificateConfiguration(IDictionary<string,X509Certificate2> certs) => Certificates = certs;

    public  Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
    {
        return builder => {
             builder.Use((ctx, nxt) =>{
                 if(ctx.Request.Headers.TryGetValue("X-Testing-ClientCert", our var key) &&
                    Certificates.TryGetValue(key, out var clientCert)){
                     ctx.Connection.ClientCertificate = clientCert;
                 }
                 return nxt();
             });
             next(builder);
        }
    }
}

public async Task MyTest()
{
    var client = Factory.CreateClient();
    var request = new HttpRequestMessage("GET","/");
    request.Headers.TryAddWithoutValidation("X-Testing-ClientCert", "CertificateKey");
    var response = await client.SendAsync(request);
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
