### ISSUE TITLE
Razor class lib: .cshtml changes at design time

### ISSUE THREAD

**Issue by seriouz** [aspnet/Mvc#8445]
I recently opened the issue #8443 but i am not very happy with the answer.
My main problem is, that in my Aspnet core MVC project i have many descendant Razor class lib projects. Now when i change one of the .cshtml files in any of the projects and press F5 no change is visible. Of course the razor class libs are precompiled. So i thought i disable the precompilation with `<RazorCompileOnBuild>false</RazorCompileOnBuild>`. But now the views (files) are no longer found, because they are laying outside of the main project in the View folders of the razor class lib projects.

How can i get a good experience at design time? To compile a razor class lib and restart the mvc app recently for small changes is not very effective. My idea with implementing a [IViewLocationExpander](https://github.com/seriouz/DelocatedRazorViews/blob/master/src/ExtractedViewLocationExpander.cs) [does not work](https://github.com/aspnet/Mvc/issues/8443#issuecomment-420340649).

**Comment by pranavkm** [comment]
@seriouz here's another discussion about this - https://github.com/aspnet/Razor/issues/2426 with a `dotnet-watch` based solution to addressing this. The VSTS issue linked from https://github.com/dotnet/project-system/issues/3163 says it's still active.
