### ISSUE TITLE
Httpcontext is null

### ISSUE THREAD

**Issue by mattman73** [aspnet/Mvc#8449]
#### Is this a Bug or Feature request?:
Help

#### Description of the problem:
Hi all
I need some help I have been working on a way to load a page from within the program.cs file but I can not work out how this is done I have look on the web to find the answer but for the life of me, I cannot find anything that will work.
What I'm looking to do is after a lookup I need to load the page again with an added searchstring, I have all the code doing the look up and cross-checking but I'm unable to get the code to redirect to the page again with the added searchstring.
I have tried to DI the Httpcontecxt but this keeps returning null.
any pointers would be great.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.aspnetcore.app 2.1.0

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
Hi @mattman73.
Did you get a solution to your question already? Assuming you've already posted it on StackOverflow, did you?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by mattman73** [comment]
Hi I did post on StackOverflow but no one has come back with a fix or a better way to get the information from HttpContext as it always returns null.
