### ISSUE TITLE
Test Controller Logic with [ApiController] attribute

### ISSUE THREAD

**Issue by r3dlin3** [aspnet/Mvc#8456]
#### Is this a Bug or Feature request?:
Bug apparently

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
I have created a repo (https://github.com/r3dlin3/test-controller-logic) based on:

- .Net Core 2.1 samples : https://github.com/aspnet/Docs/tree/master/aspnetcore/web-api/define-controller/samples
- Added a test project (based on xunit) with Moq

#### Description of the problem:
My controller `ProductsController` inherits from `ControllerBase` ans has the attribute `[ApiController]`.
All validation of the model has been erased.

I have one test with a validation error
```c#
        [Fact]
        public async Task Create_ReturnsBadRequest_GivenInvalidModel()
        {
            // Arrange & Act
            var mockRepo = new Mock<IProductsRepository>();
            var controller = new ProductsController(mockRepo.Object);
            controller.ModelState.AddModelError("error","some error");

            // Act
            var result = await controller.CreateAsync(product: null);

            // Assert
            Assert.IsType<BadRequestObjectResult>(result);
        }
```

The test fails with the following error:

     System.NullReferenceException : Object reference not set to an instance of an object.

I was expecting an invalid request.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.3" />

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @r3dlin3.
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
@r3dlin3 You need to setup the controllercontext on the controller
```csharp
var controller = new ProductsController(mockRepo.Object);
controller.ControllerContext = new ControllerContext(...)
controller.ModelState.AddModelError("error","some error");
```

Closing this issue as the question has been answered

**Comment by rynowak** [comment]
Additionally - unit tests call **your method**. The Bad Request response comes from the framework. If you want tests for framework level things, you will need to write integration tests

**Comment by r3dlin3** [comment]
Unfortunately, integration does not work neither...
I'll write an example.

________________________________

**Comment by r3dlin3** [comment]
Adding `controller.ControllerContext = new ControllerContext()` did not change anything
