### ISSUE TITLE
Possible bug when using tag helpers for multiple Model properties with the same name

### ISSUE THREAD

**Issue by Rabadash8820** [aspnet/Mvc#8457]
#### Is this a Bug or Feature request?:
Possibly a bug?  If not then feature request, or at least request for a workaround :P

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
1. Clone my super simple [MultipleInputTagHelper](https://github.com/Rabadash8820/MultipleInputTagHelper) project
2. Run it
3. Inspect the generated markup of the Index page

#### Description of the problem:
The linked project contains a Model class called `PersonModel` like this:

```cs
    public class PersonModel {

        [Required]
        public string Name { get; set; }
        [Range(18, 150)]
        public int Age { get; set; }

        public PersonModel Mother { get; set; }
        public PersonModel Father { get; set; }

    }
```

I also have a Partial View (`_Person.cshtml`), for rendering the Name/Age fields of a particular `PersonModel`.  In the `Index` View, I try to load this Partial View three times, once for a particular person, once for their `Mother`, and once for their `Father`, like this:

```html
    <partial name="_Person" model="Model" />

    <fieldset>
        <legend>@nameof(Model.Mother)</legend>
        @{ ViewData["ParentPrefix"] = nameof(Model.Mother); }
        <partial name="_Person" model="Model.Mother" view-data="ViewData" />
    </fieldset>

    <fieldset>
        <legend>@nameof(Model.Father)</legend>
        @{ ViewData["ParentPrefix"] = nameof(Model.Father); }
        <partial name="_Person" model="Model.Father" view-data="ViewData" />
    </fieldset>
```

The Partial View then uses `<input>` and `<label>` tag helpers to generate the respective elements, prefixing the generated `id`s and `name`s with a "parent prefix" to keep them unique, like this:

```cs
@{
    string parentPrefix = (string)ViewData["ParentPrefix"];
    if (!string.IsNullOrEmpty(parentPrefix)) {
        parentPrefix += ".";
    }
}

<label for="@parentPrefix@nameof(PersonModel.Name)" asp-for="Name"></label>
<input id="@parentPrefix@nameof(PersonModel.Name)" name="@parentPrefix@nameof(PersonModel.Name)" asp-for="Name" />
```

For this silly little example, it would've been easy enough to use `asp-for="Name"`, `asp-for="Father.Name"`, and `asp-for="Mother.Name"`.  However, in the actual app that I'm working on, there are many more fields involved, so having a Partial View that can output the `Mother` *or* `Father` fields is very important for staying DRY.  Unfortunately, the `<input>` tag helper appears to only add `data-val-*` attributes to the first instance of a particular field.  For example, with `Name`:

```html
<label for="Name">Name</label>
<input id="Name" name="Name" type="text" data-val="true" data-val-required="The Name field is required." value="Dan" />
<fieldset>
  <legend>Mother</legend> 
  <label for="Mother.Name">Name</label>
  <input id="Mother.Name" name="Mother.Name" type="text" value="Jennifer" />   
</fieldset>
<fieldset>
  <legend>Father</legend>
  <label for="Father.Name">Name</label>
  <input id="Father.Name" name="Father.Name" type="text" value="David" />
</fieldset>
```

I have poured over the source code for both [jQuery Unobtrusive Validation](https://github.com/aspnet/jquery-validation-unobtrusive/blob/master/src/jquery.validate.unobtrusive.js) and the [InputTagHelper](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.TagHelpers/InputTagHelper.cs), and cannot figure out why the subsequent `asp-for` tag helpers are not generating all attributes.  I even tried making my own "`ControlPrefixTagHelper`" that would add a prefix (e.g., `Mother.`) to an `<input>`'s `asp-for` attribute before the `InputTagHelper` is processed, but there's apparently no way to modify `asp-for` in the `TagHelperOutput`!  Short of duplicating my Partial View into separate, child/Mother/Father files, is there some work around for what I'm trying to do?

#### Version of `Microsoft.AspNetCore.App`: 2.1.1

No logs or Exceptions to report.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Rabadash8820.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
@Rabadash8820 an easier of handling a scenario like this is to use `<partial for="Father" />` and let the `PartialTagHelper` take care of invoking `_Person.cshtml` correctly.

----
FYI passing around prefixes and overriding `id` and `name` attributes doesn't help MVC determine the models are unique. If you want to work at this low level i.e. not use `<partial for="Father" />`, change `ViewData.TemplateInfo.HtmlFieldPrefix` before each `<partial/>` element. Don't worry about `ViewData["ParentPrefix"]` or manual prefixes at all.

There's also no reason to pass the `ViewData` into `PartialTagHelper` in this scenario. In fact, passing the current `ViewData` in means `_Person.cshtml` gets an odd mix of information -- some relevant only in the parent view and its model.

**Comment by mkArtakMSFT** [comment]
@Rabadash8820, did @dougbu's suggestion help you overcome the issue?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
