### ISSUE TITLE
[Bug] IRequestCultureFeature is unavailable in TagHelperComponent

### ISSUE THREAD

**Issue by hishamco** [aspnet/Mvc#8463]
I have some localization contribution into https://github.com/simplcommerce/SimplCommerce today after a long time of investigation working on this [bug](https://github.com/simplcommerce/SimplCommerce/issues/573) I can confirm there's a localization bug, but seems MVC related.

Simply I created a `LanguageDirectionTagHelperComponent` as it's shown [here](https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Localization/TagHelpers/LanguageDirectionTagHelperComponent.cs), this [line](https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Localization/TagHelpers/LanguageDirectionTagHelperComponent.cs#L26) is made me crazy 😄 it just fetch the `IRequestCultureFeature` in the first request and 'null` for other requests. Another strange thing is `IRequestCultureFeature` working fine in views, so that why I filed the issue in this repo, perhaps something `TagHelperComponent` related

FYI I test the above `TagComponentHelper` in the Localization.StarterWeb sample from entropy repo to confirm it's not `SimplCommerce` bug

dotenet--version -> `2.2.0-preview1-007947`

/cc @rynowak @pranavkm @ryanbrandenburg

**Comment by mkArtakMSFT** [comment]
Thanks @hishamco.
@NTaylorMullen, can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
@hishamco I tried replicating this on Localization.StarterWeb with the following:

![image](https://user-images.githubusercontent.com/2008729/45653957-9c960580-ba8e-11e8-8077-0dfc301e0d9e.png)

And all worked:

![image](https://user-images.githubusercontent.com/2008729/45654015-c5b69600-ba8e-11e8-9dac-f25f227e7439.png)

One thing I did have to change was the `.GetLanguageDirection()` (removed it).

Would you mind providing a simple repro?

**Comment by hishamco** [comment]
`.GetLanguageDirection()` is just an extension method, I will try to provide a sample repo. but one more thing did you try it for all the requests except the first one?

**Comment by NTaylorMullen** [comment]
> but one more thing did you try it for all the requests except the first one?

Yup, always succeeds for me.

**Comment by hishamco** [comment]
Nope, I registered as singleton

**Comment by hishamco** [comment]
It works fine as expected with the **Scope**, but I'm wondering why the `IRequestCultureFeature` is not fetched if it registered as a singleton

**Comment by NTaylorMullen** [comment]
> It works fine as expected with the **Scope**, but I'm wondering why the `IRequestCultureFeature` is not fetched if it registered as a singleton

Your dependency on `IHttpContextAccessor` only works properly when accessed via a Scoped dependency because the available HttpContext changes on each request. WHen you register the service as a Singleton it only ever gets the first requests value.

**Comment by hishamco** [comment]
But I registered the TagHelperComponent as singleton, I don't think that will change the behavior of other dependencies

thanks

**Comment by NTaylorMullen** [comment]
> But I registered the TagHelperComponent as singleton

It's more about the singleton depending on a scoped service (IHttpContextAccessor). The singleton is constructed once where the scoped service is re-created every request.

**Comment by hishamco** [comment]
Yep .. yep, I was thinking about the registered service only not about there dependencies

thanks a lot
