### ISSUE TITLE
[Bug] JsonSerializerSettings are not used correctly in JsonResultExecutor's ExecuteAsync

### ISSUE THREAD

**Issue by ManuelHaas** [aspnet/Mvc#8466]
`JsonResultExecutor `(Mvc/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/JsonResultExecutor.cs):
`ExecuteAsync `function uses JsonTextWriter's StringEscapeHandling property instead of serializerSettings of JsonSerializer. 
Problematic line 129 in JsonResultExecutor.cs:
`jsonSerializer.Serialize(jsonWriter, result.Value);`

`JsonResultExecutor `is used in class `JsonResult `which is used in class `Controller `in Method `Json(object data, JsonSerializerSettings serializerSettings)`

So the following code does NOT return html escaped json:
```
[HttpGet]
public async Task<JsonResult> Search4User(SearchRequest data)
{
	...
	var settings = new JsonSerializerSettings
	{
		StringEscapeHandling = StringEscapeHandling.EscapeHtml,
		ContractResolver = new CamelCasePropertyNamesContractResolver()
	};
	return Json(new { success = true, result = searchResult }, settings);
}
```

#### Version of `Microsoft.AspNetCore.Mvc` : 2.1.1.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ManuelHaas.
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
> So the following code does NOT return html escaped json:

 `StringEscapeHandling` determines how string values in the JSON document are escaped, it does not HTML escape the actual json object. Can you show what your expected output is and how it's different?

**Comment by ManuelHaas** [comment]
@pranavkm if `StringEscapeHandling ` will be set to `StringEscapeHandling.EscapeHtml` the expected output is json where html tags (if existing) are encoded. But the `StringEscapeHandling `property set in `JsonSerializerSettings` will be ignored in the above scenario.

I would expect the same behaviour as in the following statement where it works:
```
@{
var settings = new JsonSerializerSettings
	{
		StringEscapeHandling = StringEscapeHandling.EscapeHtml,
		ContractResolver = new CamelCasePropertyNamesContractResolver()
	};
var vmData =  Json.Serialize(Model.Data, settings);
}
```

**Comment by pranavkm** [comment]
Seems to work fine - https://github.com/pranavkm/repro/blob/8446/Controllers/HomeController.cs

Output using default settings (https://github.com/pranavkm/repro/blob/8446/Controllers/HomeController.cs#L30-L33)

```
{"success":true,"result":{"someText":"<div class=\"some-css\"><h1>Hello world</h1></div>"}}
```

Output using `StringEscapeHandling.EscapeHtml` (https://github.com/pranavkm/repro/blob/8446/Controllers/HomeController.cs#L20-L28) which looks correct

```
   {"success":true,"result":{"someText":"\u003cdiv class=\u0022some-css\u0022\u003e\u003ch1\u003eHello world\u003c/h1\u003e\u003c/div\u003e"}}
```

Feel free to reopen this issue once you have a repro app demonstrating the bug.
