### ISSUE TITLE
Implicitly set content type for ObjectResults containing ProblemDetails

### ISSUE THREAD

**Issue by khellang** [aspnet/Mvc#8467]
A user of my problem details middleware filed an issue (https://github.com/khellang/Middleware/issues/5) thinking something was wrong with my middleware when seeing that `ProblemDetails` responses came back with `Content-Type: application/json` in some cases and `Content-Type: application/problem+json` in other cases.

The issue turned out to be MVC writing the response in the first case, and my middleware handling the response in the second case.

It would be nice if MVC could implicitly add `application/problem+json` and `application/problem+xml` to the result `ContentTypes` if no content type has been added already, so it ends up with the correct `Content-Type` header in the response.

// @pranavkm @rynowak

**Comment by pranavkm** [comment]
> It would be nice if MVC could implicitly add application/problem+json and application/problem+xml to the result ContentTypes

Over here - https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ObjectResult.cs#L54-L57?

**Comment by khellang** [comment]
Yeah, something like that, but I think `OnFormatting` might be too late in the pipeline?
