### ISSUE TITLE
Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error MSB6003: The specified task executable "dotnet" could not be run. The system cannot find the file specified

### ISSUE THREAD

**Issue by kiasyn** [aspnet/Mvc#8468]
#### Is this a Bug or Feature request?:
Bug: Unable to build asp.net core 2.1 projects on build server

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Repo: https://github.com/kiasyn/test-project-dotnet-build-error
This is just an empty .net core 2.1 web site created by visual studio.

#### Description of the problem:
Build server is Bamboo
Using MSbuild v15.0 (64 bit) to build with command line switches: /p:Configuration=Debug /p:CreatePackageOnPublish=true

Get this error when building:
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.1\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error MSB6003: The specified task executable "dotnet" could not be run. The system cannot find the file specified [E:\build\TEST-TEST-JOB1\testproject\TestProject1\TestProject1.csproj]
(ResolveTagHelperRazorGenerateInputs target) -> 
  C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.1\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error MSB6003: The specified task executable "dotnet" could not be run. The system cannot find the file specified [E:\build\TEST-TEST-JOB1\testproject\TestProject1\TestProject1.csproj]

Full build log here:
[build.log](https://github.com/aspnet/Mvc/files/2390444/build.log)

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspnetCore.App 2.1.1-2.1.4

#### output of dotnet.txt ####
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.1 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kiasyn.
Sounds like this is related to the Bamboo agents, as the error seems to indicate that the dotnet.exe is not found. The location should be in the path environment variable, which may be something not setup on those agents.
We suggest filing an issue with them, unless you have a mechanism to set the path yourself.

**Comment by kiasyn** [comment]
thank you @mkArtakMSFT - it did end up being a path issue (due to a java issue)

For anyone else searching, this ended up being the issue:
https://confluence.atlassian.com/bamkb/bamboo-or-remote-agent-does-not-pick-up-the-path-environment-variable-correctly-when-running-as-a-windows-service-323982768.html
