### ISSUE TITLE
Verbose messages in build log about System.ComponentModel.Annotations

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#8483]
One of our dependencies references System.ComponentModel.Annotations. ASP.NET Core references it too (via a NuGet package). Therefore we receive a LOT of the following build messages when executing our build:

> C:\Program Files\dotnet\sdk\2.1.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(41,5): message NETSDK1041: Encountered conflict between 'Platform:System.ComponentModel.Annotations.dll' and 'CopyLocal:C:\Users\<myuser>\.nuget\packages\system.componentmodel.annotations\4.5.0\lib\net461\System.ComponentModel.Annotations.dll'.  NETSDK1033: Choosing 'CopyLocal:C:\Users\<myuser>\.nuget\packages\system.componentmodel.annotations\4.5.0\lib\net461\System.ComponentModel.Annotations.dll' because AssemblyVersion '4.2.1.0' is greater than '4.0.10.0'. [C:\Development\<ourrepo>\src\<ourproj>\<ourproj>.csproj]

Are those ok? Can we safely ignore them? Why are they printed out in non-verbose mode? Should this be moved to verbose mode? It's irritating ;-)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @drauch.
We actually don't own the package you reference here.

@Petermarcu, is this something you have context on?

**Comment by mkArtakMSFT** [comment]
@weshaggard, do you have context on this?

**Comment by weshaggard** [comment]
The conflict resolution sounds right if you are referencing a higher version the ASP.NET platform is. As for why the log message I though it was at a lower importance level and should be anywhere but a diag log.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
