### ISSUE TITLE
Different JsonSerializerSettings per Controller

### ISSUE THREAD

**Issue by YZahringer** [aspnet/Mvc#8485]
#### Is this a Bug or Feature request?:
Feature request

#### Description of the problem:
How to use a different JsonSerializerSettings on different controllers? Or how to overwrite the default settings for a Controller?

I have a Controller that is more "strict":
````cs
TypeNameHandling = TypeNameHandling.All;
NullValueHandling = NullValueHandling.Include;
DefaultValueHandling = DefaultValueHandling.Include;
MissingMemberHandling = MissingMemberHandling.Error;
````

Other controllers are not "strict" and work with the default settings.

The only solution is to create a custom JsonInputFormatter/JsonOutputFormatter and put it a specific SupportedMediaType?

**Comment by pranavkm** [comment]
You could use [`Controller.Json`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controller.json?view=aspnetcore-2.1) or [`JsonResult`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.jsonresult?view=aspnetcore-2.1) that lets you specify a serializer settings.

**Comment by YZahringer** [comment]
Thank you for the answer. And for the Input?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
