### ISSUE TITLE
Move Microsoft.AspNetCore.Mvc.ApplicationParts to Microsoft.Extensions.somewhere

### ISSUE THREAD

**Issue by AlseinX** [aspnet/Mvc#8488]
When I am writing my projects, things that I have met are like these:
I need type scanning and attribute based configuration for modules.
There is an application part manager in Microsoft.AspNetCore.Mvc.ApplicationParts which is well featured for the requirement.
It is only in Mvc so I cannot simply use it for other scenes.
I have to create my own for a unified module management of my projects.
I am using Mvc so I need to create an integration from my own implementation to `Microsoft.AspNetCore.Mvc.ApplicationParts`
What a bad practice.

The type scanning things are compatible with most projects that are managed by IoC containers. It is reasonable to move it elsewhere out of `AspNetCore`, making it a mainstream standard implementation of type scanning things, just like `System.IServiceProvider` and `Microsoft.Extensions.DependencyInjection` for dependency injection things.
Thus there would be a unified way for type scanning no matter Mvc is used.
For example, the SignalR hubs would be able to be scanned and the routing would be configured by attributes, just like Mvc controllers, and the user customized services that matches a certain convention would be auto registered, without any other external redundant scanning.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AlseinX.
We have no plans to change this. Besides, it'll be a breaking chnage.
