### ISSUE TITLE
Memory Cache Limits

### ISSUE THREAD

**Issue by joetherod** [aspnet/Mvc#8496]
In .NET 4.0 we have the ability to set memory limits as below.
```xml
<system.runtime.caching>
        <memoryCache>
            <namedCaches>
                <add name="Default" cacheMemoryLimitMegabytes="0" physicalMemoryLimitPercentage="50" />
            </namedCaches>
        </memoryCache>
    </system.runtime.caching>
```

In core, in order to do limits, you have to set the size of the object you are inserting, then you can set the SizeLimit. But, how are you suppose to get the size of each entry that is fast and efficient? In 4.0 it would manage the available memory for the app and for the cache based on a percentage of the available memory on the server. Can this be done for core when you have containers running on windows and linux. There are also other features that were not ported over, like getting all keys of the objects in memory. This limits the use of using In Memory Cache in core. Can it be extended? The use of in memory cache is the speed since it is by reference. Using other stores requires serialization, and for my case that is too expensive on the cpu.

**Comment by rynowak** [comment]
So the major challenge here is that the APIs that System.Runtime.Caching uses to get the size of objects and memory usage in didn't exist in NET Core 1.0. I realize that System.Runtime.Caching is now part of netstandard2.0, but I'm not sure if it includes the features that @joetherod  is asking about.

It looks like they have support for memory pressure on **windows only** and throw on other platforms: https://github.com/dotnet/corefx/blob/e0ba7aa8026280ee3571179cc06431baf1dfaaac/src/System.Runtime.Caching/src/System/Runtime/Caching/MemoryCacheStatistics.cs#L150

I theory we could make an adapter that allows you to use this with our memory caching API - or if this meets your goals @joetherod  you could try using `System.Runtime.Caching.MemoryCache` directly.

@davidfowl @DamianEdwards @sebastienros  - is there anything we can share about ideas or plans in this area?

**Comment by joetherod** [comment]
@rynowak I'll take a look at using System.Runtime.Caching.MemoryCache.

**Comment by davidfowl** [comment]
This is something we're looking at for 3.0 for the memory cache. We're looking to get a new GC event added that we can subscribe to for memory pressure (in a cross platform way) so that we can clear the cache.

**Comment by davidfowl** [comment]
This issue was moved to aspnet/Caching#421
