### ISSUE TITLE
ProblemDetails Property Casing

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/Mvc#8501]
#### Is this a Bug or Feature request?:
A bit of both

#### Description of the problem:
The new ProblemDetails feature https://github.com/aspnet/Mvc/blob/d09c3c9e2889e9e1c41cdcf3b45f3d724f98fc9f/src/Microsoft.AspNetCore.Mvc.Core/ProblemDetails.cs
is based on https://tools.ietf.org/html/rfc7807
That rfc specifies property names like ``type`` for the details object.
Currently the above implementation does not specifically set the property names during serialization, but instead relies on the JsonOutputFormatter to be camel-Cased.
I suggest that the property names are annotated with the specific property names to be used, to ensure the property names are according to the rfc and do not suddenly change if a differently cased formatter is used.

There are multiple ways to do so:
1. using ``[JsonProperty]`` Attribute -> This will only work with the JSON.NET output formatter
2. using ``[DataMember(Name=...]`` Attribute -> This will work with most/all formatters, as pretty much every serializer I found supports this annotation

As you already have a ProblemDetailsWrapper.cs with customized reading/writing  for the XML formatter, the DataMember annotations shouldn't pose a problem.

I'd personally prefer 2. as it will work with other formatters/serializers, i.e. Jil, Utf8Json, SpanJson et. al.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Tornhoof.
@glennc, what are your thoughts regarding this?
