### ISSUE TITLE
JsonInputFormatter do not take Json.Net ErrorContext Member property into account

### ISSUE THREAD

**Issue by MaxDeg** [aspnet/Mvc#8509]
#### Is this a Bug or Feature request?:
A Bug (related to this ticket #4607)

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Creating a MVC application with an action handling POST request and taking a json payload. If the payload contains a property of type `int` that is required (marked with `JsonProperty(Required = Required.Always)`), the resulting error do not show the field name.

#### Description of the problem:
The Member property of the ErrorContext given by Json.Net is not taken into account when adding a Error in the ModelState. Only the Path property is used.

As stated here https://github.com/aspnet/Mvc/issues/4607#issuecomment-338202476 the Member property should be used but this is not the case.
When looking into the JsonInputFormatter (https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonInputFormatter.cs#L285) you see that the "key" variable used to add an error in model state do not use the Member property which is the one that contains the json field with which an error is associated.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
2.1.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MaxDeg.
@pranavkm, can you please look into this? Thanks!

**Comment by rynowak** [comment]
@MaxDeg - do you have an example of what you're actually seeing vs what you expect?

Model state errors are based on the model's property names intentionally. I understand this is not useful in all scenarios, but it's the way it happens to work. 

@mkArtakMSFT  - this is something we should look at changing in a future release. The feedback overfloweth, and I'm not sure who is being served by the current approach.

**Comment by dougbu** [comment]
@JamesNK in which cases will `ErrorContext.Path` not include the current `Member` string? We need the whole path and it is incomplete in at least the scenario when no data is provided for a required property. However I doubt we can simply append `Member.ToString()` unconditionally.

@MaxDeg the comments in  #4607 were about providing a reasonable `Message`, not the `ModelState` key used.

**Comment by JamesNK** [comment]
Member could be null if there is an error caused by the root object.

**Comment by dougbu** [comment]
@JamesNK but when will `Path` not include `Member`? In this scenario, `Path` is empty but `Member` is `"id"`.

Our error handler (in `JsonInputFormatter`) exclusively uses `ErrorContext.Path` when choosing the `ModelState` key but perhaps it should use `Member` instead of or in addition to `Path`. My concern is duplicating part of `Path` if we blindly combine `Path` and `Member`.

**Comment by JamesNK** [comment]
Ah I see. Well `Path` is the current location in JSON while `Member` indicates the .NET member that caused the error. There are lots of situations where they don't line up, e.g. https://github.com/JamesNK/Newtonsoft.Json/blob/7217c484e9705b5e76585c8b7fcd489c8e021c23/Src/Newtonsoft.Json.Tests/Serialization/SerializationErrorHandlingTests.cs#L494-L511

**Comment by dougbu** [comment]
@MaxDeg FYI @JamesNK and I took this offline a few days ago. We haven't resolved how our error handler could safely (i.e. without getting confused when the full path ends with `Name.Name` or `[0][0]`) use the `Member` property.
