### ISSUE TITLE
Map Json to Action parameters

### ISSUE THREAD

**Issue by hez2010** [aspnet/Mvc#8510]
#### Is this a Bug or Feature request?:
Feature request

#### Description of the problem:
Currently in order to use json, I have to write:
In Controller:  
```c#
public class Model
{
    public string Param1 { get; set; }
    public int Param2 { get; set; }
    ....
}

[HttpPost]
public IActionResult Test([FromBody]Model param) {  }
```
In frontend js:
```js
fetch('/[Controller]/Test', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({ param1: 'test', param2: 123 })
});
```

But it will be better if it can be written just like form submission:
In Controller:  
```c#
[HttpPost]
public IActionResult Test(string param1, int param2) {  }
```
In frontend js:
```js
fetch('/[Controller]/Test', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({ param1: 'test', param2: 123 })
});
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.App`: 2.1.4

**Comment by pranavkm** [comment]
https://github.com/aspnet/Mvc/issues/5306#issuecomment-249616041 has some suggestions on how you'd go about doing this. That said, we don't have plans to add support for doing this out of the box.
