### ISSUE TITLE
Binding tries to instantiate a non-null property of abstract type

### ISSUE THREAD

**Issue by Oblomoff** [aspnet/Mvc#8514]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

Download attached solution [WebApp.zip](https://github.com/aspnet/Mvc/files/2429330/WebApp.zip) and run it. Try to submit the form.

#### Description of the problem:
Binding to a property of abstract type leads to exception:
InvalidOperationException: Could not create an instance of type 'WebApp.Pages.InputModelBase'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. **Alternatively, set the 'Input' property to a non-null value in the 'WebApp.Pages.IndexModel' constructor.**

But even then 'Input' property set to a non-null value it does not help.

Why binding tries to instantiate a non-null property???

```CSharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {
        public IndexModel()
        {
            // 'Input' property set to a non-null value in the 'WebApp.Pages.IndexModel' constructor.
            Input = new InputModel();
        }

        // Here is InvalidOperationException:
        // Could not create an instance of type 'WebApp.Pages.InputModelBase'. Model bound complex
        // types must not be abstract or value types and must have a parameterless constructor.
        // Alternatively, set the 'Input' property to a non-null value in the
        // 'WebApp.Pages.IndexModel' constructor.
        [BindProperty]
        public InputModelBase Input { get; set; }
    }

    public class InputModel : InputModelBase
    {
        public override string Message { get; set; } = "Hello!";
    }

    public abstract class InputModelBase
    {
        public abstract string Message { get; set; }
    }
}

```

#### Version of  `Microsoft.AspNetCore.App`

2.1.4

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Oblomoff.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
@Oblomoff this restriction is present only at the top level when model binding. Any existing value of a controller or page model is consistently ignored during model binding.

Two workarounds:
1. Make the property `internal` or `private` and use `await TryUpdateModelAsync(Input)` in a `Post(...)` method in `InputModel`
2. Move use of the `abstract` class down a level e.g.
``` c#
public class IndexModel : PageModel
{
    [BindProperty]
    public InputModelWrapper Wrapper { get; set; }
}

public class InputModelWrapper
{
    public InputModelBase Input { get; set; } = new InputModel();
}
```

**Comment by dougbu** [comment]
@Oblomoff we would appreciate more details about your scenario.
- Why is it necessary for the page model property to be `abstract`?
  - If it's for polymorphism, don't do it. Create distinct page handlers with parameters of the concrete types needed and (if the property is needed) set it in the handler. 
  - If it's for information hiding i.e. not binding some properties of a concrete type, don't do it. Use the concrete type and annotate properties with `[BindNever]` to hide them.
- If either or the alternatives above do not work in your scenario, why?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
