### ISSUE TITLE
XmlDictionaryReader.CreateTextReader overload which supports Encoding is missing

### ISSUE THREAD

**Issue by sornaks** [aspnet/Mvc#852]
This overload is missing in ProjectK:
```c#
public static XmlDictionaryReader CreateTextReader(
	Stream stream,
	Encoding encoding,
	XmlDictionaryReaderQuotas quotas,
	OnXmlDictionaryReaderClose onClose
)
```
Link: http://msdn.microsoft.com/en-us/library/aa346768(v=vs.110).aspx

This is used by ASP .NET vNext during Deserialization of Xml input.

**Comment by danroth27** [comment]
@sornaks I believe this overload is now available.

**Comment by sornaks** [comment]
Yes, the overload is available. Let me update it..
