### ISSUE TITLE
Rename targets, package, and some metadata for client code generation

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#8523]
#### Is this a Bug or Feature request?
Enhancement that's part of #7947

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project)
Observe names of targets in [Microsoft.Extensions.ApiDescription.Client.targets](https://github.com/aspnet/Mvc/blob/9d109f59561be19817b5504df0b66de7c95c733f/src/Microsoft.Extensions.ApiDescription.Client/build/Microsoft.Extensions.ApiDescription.Client.targets). Note the `..._Core`, `..._Inner`, and `DefaultDocumentGenerator` names are nouns. The expected names of 3rd party targets are also nouns.

#### Description of the problem
As @rynowak [observes](https://github.com/aspnet/Mvc/pull/8515/files#r221436113) in the #8515 PR, "MSBuild targets are verbs not nouns".

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`
See the [features/client.code.generation](https://github.com/aspnet/Mvc/tree/feature/client.code.generation) branch. That work is intended for the 2.2 Preview 3 milestone.

**Comment by mkArtakMSFT** [comment]
@dougbu, for the priority - you decide what it should be. If this is something we can't change after releasing, we should do it!

**Comment by dougbu** [comment]
Bumping up the priority and renaming from "Change code generation target names to be verbs".

Rename package to `Microsoft.Extensions.ApiDescription.Design` because, as @rynowak said offline, "it sounds like a like a library that is used as an HTTP client, rather than a library to produce them".

Rename tasks assembly to  `Microsoft.Extensions.ApiDescription.Tasks` to match MSBuild conventions.

Probably worth changing the default namespace in `Microsoft.Extensions.ApiDescription.Tasks` to match the assembly. And, change the default namespace in the tool projects to `Microsoft.Extensions.ApiDescription.Tool` since the tool and task projects no longer share code.

Use same names for metadata in `ServiceProjectReference` as defined in `ProjectReference`. Note project properties such as `$(TargetFramework)` are _not_ automatically overridden using `ProjectReference` metadata.

**Comment by dougbu** [comment]
Turns out there's not much overlap (beyond `%(Identity)` of course) between the `@(ServiceProjectReference)` and `@(ProjectReference)`. See https://github.com/Microsoft/msbuild/blob/90506c8f6c5e4b82a09bafa6ae62a41e9e7367bb/src/MSBuild/Microsoft.Build.CommonTypes.xsd#L549 and https://docs.microsoft.com/en-ca/visualstudio/msbuild/common-msbuild-project-items?view=vs-2017#projectreference

The one exception to the above is `%(Targets)` which `@(ServiceProjectReference)` items currently lack. Should default to empty which will build the `$(MSBuildProjectDefaultTargets)` of the referenced project.

But, *could* align with project properties such as `$(Configuration)`, `$(Platform)` and `$(TargetFramework)` (see https://docs.microsoft.com/en-ca/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2017). My original thought was to prepend `Project` in all project-related `@(ServiceProjectReference)` metadata names to make them consistent and somewhat separate from other values. I lean toward keeping that separation. Thoughts @rynowak?

**Comment by dougbu** [comment]
28b1f967c0
