### ISSUE TITLE
Problem loading editor template when Areas are applied

### ISSUE THREAD

**Issue by ag-petrov** [aspnet/Mvc#8526]
Given an application that uses areas and has the following folder structure.

```
\Areas
	\Admin
	          \Views
			\Home
			\Shared
				\EditorTemplates
```
If inside the **EditorTemplates** there is a view called **Custom.chtml** loading it using dynamically is possible only by providing the full path to the view. For example if we are loadining it using the following code.

```csharp
private string GetEditorForModel(IHtmlHelper htmlHelper, string templateName, object additionalViewData)
{
  //....
  IHtmlContent editorContent;

  if (templateName.HasValue())
  {
    editorContent = htmlHelper.EditorForModel(templateName, additionalViewData);
  }
```

Calling **GetEditorForModel("Custom", ....)** will not work while calling **GetEditorForModel("~/Areas/Admin/Views/Shared/EditorTemplates/Custom.cshtml", .....)** will.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ag-petrov.
In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by ag-petrov** [comment]
Hi @mkArtakMSFT , [here ](https://drive.google.com/open?id=1qQE8VwFIvxRTFwAmhM7I6IrHWBMY6RFe) is a small sample that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ag-petrov.
@NTaylorMullen, can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
Hi @ag-petrov in your `ViewContextForType` you're not passing in the pre-existing view context's `RouteData` so it doesn't know it's coming from an `Area`.

Aka:
```C#
public static ViewContext ViewContextForType<T>(this ViewContext viewContext, IModelMetadataProvider metadataProvider)
{
    var actionContext = new ActionContext(viewContext.HttpContext, viewContext.RouteData, new ActionDescriptor());
...
```

Adding `RouteData` to the newly constructed `ActionContext` makes things work.

**Comment by ag-petrov** [comment]
@NTaylorMullen thank you. I did not see that.
