### ISSUE TITLE
IEnumerable<IFormFile> is not correctly binding when part names are indexed

### ISSUE THREAD

**Issue by ranouf** [aspnet/Mvc#8527]
Hi,

I have an Issue when I try to upload Files from my Angular 6 app to .net core web api.

Here is my C# classes:
   ```
 public class SampleDetailsDto 
    {
        public Guid Id{ get; set; }
        [Required]
        public string Text { get; set; }
        public string ImageUrl { get; set; }
        public IEnumerable<IFormFile> Files { get; set; }
        public IList<SampleItemDto> SampleItems { get; set; }
    }
    public class SampleItemDto : EntityDto<Guid?>, IAuditedDto, IDeleteAuditedDto
    {
        public Guid Id{ get; set; }
        [Required]
        public string Text { get; set; }
        public string ImageUrl { get; set; }
        public IEnumerable<IFormFile> Files { get; set; }
    }
```

My C# Controller:

```
        [Route("{id:guid}")]
        public async Task<IActionResult> UpdateAsync([FromRoute]Guid id, [FromForm] SampleDetailsDto dto)
        {
              Console.Write(dto.Files?.Length); // return null
              return OK();
       }

```
![image](https://user-images.githubusercontent.com/1764519/46158581-29d61880-c24c-11e8-828c-a7b16dbb3ebb.png)
As you can see Files are null.

But if I look in the request:
![image](https://user-images.githubusercontent.com/1764519/46158648-512ce580-c24c-11e8-942d-3651f96fd02b.png)

With more details:
![image](https://user-images.githubusercontent.com/1764519/46158699-6c97f080-c24c-11e8-877d-92000dbbcc5e.png)

As we can see the Files are correctly sent to the server, in the name we can see that there are supposed to be correctly bind to the DTO which is not the case.

I read here: https://github.com/aspnet/Mvc/issues/7719 that It s recommended to use IFormCollection, so yes, I can see all the Files uploaded, but they are all in one property called "Files" instead of being linked to SampleDetailsDto or ChildSampleDto.

I did a really basic repository, so you will be able to test the problem:
https://github.com/ranouf/TestMultipleUpload

Did you notice this bug too? Did you find a way to patch it?

note: this bug was originally created here: https://github.com/dotnet/core/issues/1967

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ranouf.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
> note: this bug was originally created here: dotnet/core#1967

This is the correct place to file this issue. Suggest closing dotnet/core#1967.

> Did you notice this bug too?

Thank you for your feedback. We're closing this issue as we think this is fixed in our working code base. Would you be able to try our nightly builds and see if the issue is resolved for you? (The #8311 fix was made only a couple of weeks ago, after the most recent 2.2 preview release on NuGet.org.)

Nightly builds are available from https://dotnet.myget.org/gallery/aspnetcore-dev.

Alternatively, the workaround is to remove `[FromForm]` (which is technically incorrect for `IFormFile`) from the `dto` parameter. But due to #7770, that might not work unless you're using one of the 2.2 preview releases (which are available on NuGet.org).

**Comment by ranouf** [comment]
Thanks @dougbu ! 

Last question, if I use the nightly build, will I be able to deploy it on Azure?

**Comment by dougbu** [comment]
@ranouf see https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.2

**Comment by ranouf** [comment]
Thanks

**Comment by ranouf** [comment]
I followed your advices:
- I added the last version of AspNetCoreRuntime in csproj (https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/AspNetCoreRuntime.2.2.x64) ( for other people who want to do it, do not forget to add a new nuget Source in VS: https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json)
- I remove [FromForm] before the Dto and replaced it by [FromBody]

I now have an error 400 when I post the request. 

Here is what I post:

> ------WebKitFormBoundary4JBB3jcAGh0A72fE
> Content-Disposition: form-data; name="name"
> 
> asda
> ------WebKitFormBoundary4JBB3jcAGh0A72fE
> Content-Disposition: form-data; name="files[0]"; filename="19763265060_05f2ff50bb_o.jpg"
> Content-Type: image/jpeg
> 
> 
> ------WebKitFormBoundary4JBB3jcAGh0A72fE
> Content-Disposition: form-data; name="files[1]"; filename="19925044056_474370724c_o.jpg"
> Content-Type: image/jpeg
> 
> 
> ------WebKitFormBoundary4JBB3jcAGh0A72fE
> Content-Disposition: form-data; name="children[0].name"
> 
> qqq
> ------WebKitFormBoundary4JBB3jcAGh0A72fE
> Content-Disposition: form-data; name="children[0].files[0]"; filename="19763733839_c60669a986_o.jpg"
> Content-Type: image/jpeg
> 
> 
> ------WebKitFormBoundary4JBB3jcAGh0A72fE
> Content-Disposition: form-data; name="children[0].files[1]"; filename="19119802213_79cc08f259_o (1).jpg"
> Content-Type: image/jpeg
> 
> 
> ------WebKitFormBoundary4JBB3jcAGh0A72fE--

the response is:
{"":["The input was not valid."]}

https://github.com/ranouf/TestMultipleUpload/commit/7f0049430965008dbf0762fd8109d224ac911e66

Do I miss something?

**Comment by dougbu** [comment]
> I remove `[FromForm]` before the Dto and replaced it by `[FromBody]`

Remove both attributes entirely. When using any release from NuGet.org, you do not have the #8311 fix.

**Comment by ranouf** [comment]
I removed [FromBody]
I added a new source in VS (https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json)
I added <PackageReference Include="AspNetCoreRuntime.2.2.x64" Version="2.2.0-preview3-35365" /> in the CSProj
From what I understand, it should work, but I still have an error 400.
![image](https://user-images.githubusercontent.com/1764519/46309241-ca4c7580-c589-11e8-829f-5d8741d7493f.png)

Do I need to change something in the client request? (the client request is configured here: https://github.com/ranouf/TestMultipleUpload/blob/46572ca99dd71a1db48866afc4b8b1a49a1bc875/client/src/app/services/api.services.extensions.ts#L22)
Do I need to do something else server side?

Thanks

**Comment by ranouf** [comment]
I removed [FromBody]
I added a new source in VS (https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json)
I added <PackageReference Include="AspNetCoreRuntime.2.2.x64" Version="2.2.0-preview3-35365" /> in the CSProj
I installed 'Release/2.2.1XX
(2.2.x Runtime)' from (https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries)

From what I understand, it should work, but I still have an error 410.
![image](https://user-images.githubusercontent.com/1764519/46309855-a853f280-c58b-11e8-80c0-094e01a8ac15.png)

Do I need to change something in the client request? (the client request is configured here: https://github.com/ranouf/TestMultipleUpload/blob/46572ca99dd71a1db48866afc4b8b1a49a1bc875/client/src/app/services/api.services.extensions.ts#L22)
Do I need to do something else server side?

Thanks

**Comment by ranouf** [comment]
Hi, @dougbu , sorry to relaunch you, when you have time, could you answer, You are currently the only one who seem to have found the correct solution :)

**Comment by dougbu** [comment]
@ranouf I'm hoping to try things out locally later today or perhaps tomorrow morning.

**Comment by dougbu** [comment]
@ranouf I'm unable to use the repro solution due to its high number of dependencies and issues blocking progress. Right now `npm run start` in the client directory writes some output, ending with `Compiled successfully` then does nothing more.

Please test with 2.2 Preview 3 i.e. nightly packages
- create a NuGet.config file in the solution root containing
  ``` xml
  <?xml version="1.0" encoding="utf-8"?>
  <configuration>
    <packageSources>
      <add key="dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
      <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    </packageSources>
  </configuration>
  ```
- download a nightly 2.2 SDK from https://github.com/dotnet/core-sdk
- create a global.json file in the solution root containing
  ``` json
  {
    "sdk": {
      "version": "2.2.100-preview2-009404"
    }
  }
  ```
  The version above should match whatever you downloaded above.

Note you don't need the AspNetCoreRuntime.2.2.x64 package for local testing. In addition, that package is unlikely to override enough to be sure the app is using ASP.NET Core MVC 2.2 Preview 3 packages.

If the above does not resolve your concern, we need more information about the failure. In that case, please write a functional test or two in C# demonstrating what the TestMultipleUpload.Api project is doing that you don't expect and reopen this issue with the new repro and details. (The problem is specific to the submitted request, not the technology used to make that request.)

**Comment by ranouf** [comment]
Thanks :)

I will try that probably tommorow or monday.

**Comment by ranouf** [comment]
Hi,

here are more explanation how to launch the repo:
**Server side:**
Open the TestMultipleUpload.sln
Click on Ctrl+F5 (of F5) to launch the server
On going to https://localhost:44344/api/family, you will "["value1","value2"]" which means the server is ready.

**Client side**
in the client folder, to install all the dependancies, run  `npm install`

![image](https://user-images.githubusercontent.com/1764519/46541643-96739780-c88a-11e8-870b-02679f6725d8.png)

Note: sometimes, npm fails, remove the node_modules folder and re run `npm install`

then still in the same folder, to build the app, run `npm run start` 
![image](https://user-images.githubusercontent.com/1764519/46541978-57921180-c88b-11e8-89b6-eec7a0658934.png)

and then launch http://localhost:4200
![image](https://user-images.githubusercontent.com/1764519/46542148-b5265e00-c88b-11e8-98e2-b2cdb8b0b310.png)
Fill the fields
Add Pictures
You can add new child by clicking Add.
Then click Save

In chome inspection, in Network Tab, you can see the request failed:
![image](https://user-images.githubusercontent.com/1764519/46542282-0898ac00-c88c-11e8-95bc-c7e4acd8cb81.png)

here are the form data details:
------WebKitFormBoundarynZ1QPMAJQjq6RTi7
Content-Disposition: form-data; name="name"

Parent
------WebKitFormBoundarynZ1QPMAJQjq6RTi7
Content-Disposition: form-data; name="files[0]"; filename="19925095426_7b3af99df3_o.jpg"
Content-Type: image/jpeg


------WebKitFormBoundarynZ1QPMAJQjq6RTi7
Content-Disposition: form-data; name="children[0].name"

Child 0
------WebKitFormBoundarynZ1QPMAJQjq6RTi7
Content-Disposition: form-data; name="children[0].files[0]"; filename="19925095426_7b3af99df3_o.jpg"
Content-Type: image/jpeg


------WebKitFormBoundarynZ1QPMAJQjq6RTi7
Content-Disposition: form-data; name="children[0].files[1]"; filename="19950324155_5321a6eb7e_o.jpg"
Content-Type: image/jpeg


------WebKitFormBoundarynZ1QPMAJQjq6RTi7--


Next post, I will test your suggestions :)

**Comment by ranouf** [comment]
I followed your instructions.

The current version installed is:
![image](https://user-images.githubusercontent.com/1764519/46546313-b01adc00-c896-11e8-83e9-85fc91ceabc5.png)

I can see the new version installed:
![image](https://user-images.githubusercontent.com/1764519/46546357-ca54ba00-c896-11e8-9065-19641c1e775c.png)

In my csproj, I had:
    <PackageReference Include="AspNetCoreRuntime.2.2.x64" Version="2.2.0-preview3-35364" />

I was not sure if I have to do with it, I try to update with nugget, but I have an infinite loading
![image](https://user-images.githubusercontent.com/1764519/46546791-1bb17900-c898-11e8-8e74-42b9fbf79c73.png)


I now have many errors with the API project and I m not able to launch it anymore:
![image](https://user-images.githubusercontent.com/1764519/46546694-d1c89300-c897-11e8-9478-e3256d78a030.png)

I m not sure what I have to do now?

**Comment by dougbu** [comment]
@ranouf 
> then launch http://localhost:4200

This and later steps were what I was missing. The latest issue is not the `IFormFile` collections per se. Instead, `[ApiController]` changes the binding source of the entire `ParentDto` to `BindingSource.Form` and that doesn't support a form URL-encoded body. That leads to the `415` response.

Restoring the `[FromForm]` (which works in ASP.NET Core MVC 2.2) unearths another issue: The submitted filenames should match the property i.e. not be indexed. A supported submission would have
```
Content-Disposition: form-data; name="files"; filename="19925095426_7b3af99df3_o.jpg"
...
Content-Disposition: form-data; name="children[0].files"; filename="19925095426_7b3af99df3_o.jpg"
...
Content-Disposition: form-data; name="children[0].files"; filename="19950324155_5321a6eb7e_o.jpg"
```
I'm not sure how to change your code to submit the files with the above names.

----
Separately, as I said above
> Note you don't need the AspNetCoreRuntime.2.2.x64 package for local testing. In addition, that package is unlikely to override enough to be sure the app is using ASP.NET Core MVC 2.2 Preview 3 packages.

and
> The version above should match whatever you downloaded above.

A mismatch here may lead to the errors you've highlighted.

**Comment by dougbu** [comment]
@ranouf I changed https://github.com/ranouf/TestMultipleUpload/blob/46572ca99dd71a1db48866afc4b8b1a49a1bc875/client/src/app/services/api.services.extensions.ts#L63

to
``` TypeScript
this.appendFormData(formData, data[i], root);
```
and your sample worked perfectly

**Comment by ranouf** [comment]
Thanks for your quick answer :)

I added you as collaborator to the repository so you can push your modifications.

**Comment by dougbu** [comment]
> I added you as collaborator to the repository so you can push your modifications.

Doesn't look like I have sufficient access to create a branch. But, I've already provided the NuGet.config and global.json files. Beyond that (and the need to align versions between global.json and the SDK),
``` diff
diff --git a/client/src/app/services/api.services.extensions.ts b/client/src/app/services/api.services.extensions.ts
index 609d58db27..f7768746fe 100644
--- a/client/src/app/services/api.services.extensions.ts
+++ b/client/src/app/services/api.services.extensions.ts
@@ -60,7 +60,7 @@ export class FamilyServiceExtensions extends FamilyService {
       formData.append(root, data);
     } else if (Array.isArray(data)) {
       for (var i = 0; i < data.length; i++) {
-        this.appendFormData(formData, data[i], root + '[' + i + ']');
+        this.appendFormData(formData, data[i], root);
       }
     } else if (typeof data === 'object' && data) {
       for (var key in data) {
diff --git a/server/TestMultipleUpload.Api/Controllers/FamilyController.cs b/server/TestMultipleUpload.Api/Controllers/FamilyController.cs
index 9b0cc9697a..40b73cb3f3 100644
--- a/server/TestMultipleUpload.Api/Controllers/FamilyController.cs
+++ b/server/TestMultipleUpload.Api/Controllers/FamilyController.cs
@@ -21,13 +21,15 @@ namespace TestMultipleUpload.Api.Controllers
         // POST api/values
         [HttpPost]
         [ProducesResponseType(typeof(ParentDto), (int)HttpStatusCode.OK)]
-        public IActionResult Post(ParentDto dto)
+        public IActionResult Post([FromForm] ParentDto dto)
         {
             Console.Write("Parent Name:" + dto.Name);
+
             if (dto.Files != null)
             {
                 Console.Write("Parent files:" + dto.Files.Count());
diff --git a/server/TestMultipleUpload.Api/TestMultipleUpload.Api.csproj b/server/TestMultipleUpload.Api/TestMultipleUpload.Api.csproj
index 3070978f46..3897728dd0 100644
--- a/server/TestMultipleUpload.Api/TestMultipleUpload.Api.csproj
+++ b/server/TestMultipleUpload.Api/TestMultipleUpload.Api.csproj
@@ -6,13 +6,8 @@
     <LangVersion>latest</LangVersion>
   </PropertyGroup>

-  <ItemGroup>
-    <Folder Include="wwwroot\" />
-  </ItemGroup>
-
   <ItemGroup>
     <PackageReference Include="Microsoft.AspNetCore.App" />
-    <PackageReference Include="AspNetCoreRuntime.2.2.x64" Version="2.2.0-preview3-35364" />
   </ItemGroup>

 </Project>
```

I removed the AspNetCoreRuntime.2.2.x64 dependency only because I apparently do not have the correct extension to support the `AzureSiteExtension` package type. I normally see this type of package referenced only in the Azure Portal.

**Comment by dougbu** [comment]
Unassigning issue that's on the backlog&hellip;

**Comment by ranouf** [comment]
Hi @dougbu ,

Great thanks for your help! It s finally working correctly :)
Here is the last push:
https://github.com/ranouf/TestMultipleUpload/commit/eab8ff287fff3bd464d9c02860dce83474c5a75c

I had to modify the api.services.extensions.ts part to separate array of file from array of object.

The issue was from client part, but It s an interesting case for people who want to upload files to a .net core app.

Thanks again!
