### ISSUE TITLE
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Mvc#8531]
_From @dilushi on October 1, 2018 9:23_

I'm getting below error when trying to start the .Net Core API deployed on IIS. Tried many workarounds but still couldn't resolve this issue. Appreciate any support on this.

> 2018-10-01T10:10:42.6383743+01:00 0HLH7FMNJ4U50:00000002 [ERR] Connection id ""0HLH7FMNJ4U50"", Request id ""0HLH7FMNJ4U50:00000002"": An unhandled exception was thrown by the application. (560e7d32)
> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
>    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    at System.Reflection.RuntimeAssembly.get_DefinedTypes()
>    at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
>    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
>    at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
>    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
>    at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
>    at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
> 2018-10-01T10:10:42.6385488+01:00 0HLH7FMNJ4U50:00000002 [INF] Request finished in 11.3774ms 500  (791a596a)
> 

#.NET Core 2.0, #API, #IIS

_Copied from original issue: aspnet/KestrelHttpServer#2969_

**Comment by JunTaoLuo** [comment]
@dilushi this looks like MVC had issues loading assemblies. You should be able to see more information if you examine the LoaderExceptions as recommended in the error message. Can you share your project files with us and let us know the environment you are running on including the version of the shared framework and the dotnet SDK?  cc @pranavkm in case you know of any issues with loading assemblies.

**Comment by dilushi** [comment]
hi @pranavkm , if you have any experience on a similar issue, could you please let me know if any workaround to resolve this issue? Appreciate your support on this.
Thank you.

**Comment by mkArtakMSFT** [comment]
@dilushi, how did you manage to add a SOAP service reference to a .Net Core project?

**Comment by mkArtakMSFT** [comment]
I don't believe it's something supported. @glennc, can you please confirm?

**Comment by dilushi** [comment]
hi @mkArtakMSFT 
Added the service reference using Connected Services in Visual Studio.
I have uploaded a sample project.
https://github.com/dilushi/NetCoreAndASMX

Thank you.

**Comment by rynowak** [comment]
We should consider also special casing this during `BuildModel` and rethrowing a more descriptive error. We know that this is a likely place for an assembly or type load failure, and type load failures aren't easy to debug.

**Comment by pranavkm** [comment]
@dilushi sorry for the delay, I just got around to trying your scenario out. I was able to build \ publish and run your application without issues. The `NETCoreApi` app you pointed to is running on .NET Core (as opposed on .NET Framework) so the GAC isn't really involved here. .NET Core ships it's own copy of the ServiceModel assembly, so copying the one from .NET Framework is likely not be the correct thing to do.

Do you have more details on what the actual loader exception was? Might help explain what was causing the error you were seeing. 

@rynowak filed https://github.com/aspnet/Mvc/issues/8692 to track suggestion

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
