### ISSUE TITLE
ModelBinding regression in 2.1.3

### ISSUE THREAD

**Issue by Suchiman** [aspnet/Mvc#8536]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
https://github.com/Suchiman/MvcRegression
```csharp
[ApiController]
[Route("api/[controller]")]
public class TestController : Controller
{
    [HttpPost]
    public void Test(List<TestClass> filters = null)
    {
    }
}

public class TestClass
{
    public string Test { get; set; }
}
```
1. Set breakpoint in the Test method of the TestController
2. Issue following post request
```
POST https://localhost:44333/api/Test/ HTTP/1.1
Content-Type: application/json
Accept: application/json
Host: localhost:44333
Content-Length: 37

[{"test":"value1"},{"test":"value2"}]
```
3. Inspect the filters argument

#### Description of the problem:
After Upgrading from 
```csproj
<PackageReference Include="Microsoft.AspNetCore" Version="2.1.3" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.2" />
```
to
```csproj
<PackageReference Include="Microsoft.AspNetCore" Version="2.1.4" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.3" />
```
`filters` will be an empty list, while it used to be populated with the two elements that were posted in the previous Version.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Suchiman.
This issue has been fixed in 2.1.5 release: https://github.com/aspnet/Mvc/issues/8206

**Comment by mkArtakMSFT** [comment]
@Suchiman, in the meantime, you can decorate the `filters` parameter with `[FromBody]` attribute to avoid the issue.

**Comment by mkArtakMSFT** [comment]
Ok, so after some discussion, we've decided to move forward with the following approach. Going forward, the top-level parameters for API Controllers will infer the below listed binding sources:
| Parameter type | Binding source |
| ------------- | ------------- |
| Simple type  | Query |
| Complex type  | Body  |
| Simple collection | Body  |
| Complex collection  | Body  |

**Comment by thrane** [comment]
I have seen a similar issue when updating from 2.1.402 -> 2.1.403. Where I have a controller with the [ApiController], that has an action that accepts an array that worked in 2.1.402, but the array is empty in 2.1.403. 
If I add [FromBody] to the array it works in 2.1.403

**Comment by dougbu** [comment]
Reassigning because this fits in with 2.2.0 work @pranavkm is doing.

@pranavkm #7712 is closed but please mention it in your commit description so viewers know what we're doing in that case has changed slightly.

**Comment by Suchiman** [comment]
I just upgraded to 2.2 and this issue still occurs.
Since i have a List of a class, this should work according to the specified behavior?

Parameter type | Binding source
-- | --
Complex collection | Body

**Comment by dougbu** [comment]
@Suchiman the decisions we made w.r.t. `[ApiController]` changed a few times. In 2.2.0, two `ApiBehaviorOptions` properties control the behavior. They are `SuppressInferBindingSourcesForParameters` (which turns all inference off when `true`) and `AllowInferringBindingSourceForCollectionTypesAsFromQuery` (which changes the inference for all collection types from `BindingSource.Body` to `BindingSource.Query`). Complex collections are no longer a special case.

**Comment by Suchiman** [comment]
@dougbu so if i follow your explanation, since i don't set `SuppressInferBindingSourcesForParameters`, then not setting `AllowInferringBindingSourceForCollectionTypesAsFromQuery` means all collection types have `BindingSource.Body` so this should work for the sample provided in the top post, but it doesn't.

**Comment by dougbu** [comment]
@Suchiman should have mentioned earlier that this is is a closed issue and not something we're tracking anymore.

More specifically, 2.2.0 (not one of the previews) should not special-case collections when inferring binding sources unless `AllowInferringBindingSourceForCollectionTypesAsFromQuery == true`; collections are treated as complex types. Note `AllowInferringBindingSourceForCollectionTypesAsFromQuery ` defaults to `true` if your `Startup` lacks `SetCompatibilityVersion(CompatibilityVersion.Version_2_2)`.

**Comment by Suchiman** [comment]
@dougbu Ahhh gotcha, i failed to up the `CompatibilityVersion`. Although I'm suprised, this is a breaking change, as this used to work in 2.1 and was changed in a servicing release, and then kept for 2.2 and restoring that feature requires increasing the `CompatibilityVersion`.
