### ISSUE TITLE
Abstract to Concrete class Model binding

### ISSUE THREAD

**Issue by joetherod** [aspnet/Mvc#8539]
In MVC4/5 I was able to create a custom model binder that would allow me to have an action method take in an abstract class to save. The binder would determine the concrete model class and set it. When it went to the action call the abstract type was now the concrete type with all of the posted values set.

In MVC Core, it is not working.
In MVC4 I set the model meta data as below in the CreateModel method of my custom ModelBinder
```csharp
bindingContext.ModelMetadata = ModelMetadataProviders.Current.GetMetadataForType(null, model.GetType());
bindingContext.ModelMetadata.Model = model;
```
In MVC Core, I have a dependency for IModelMetadataProvider modelMetadataProvider.
then:
```csharp
bindingContext.ModelMetadata = _modelMetadataProvider.GetMetadataForType(model.GetType());
```
When the action method is called in Core, the type for the model is concrete, but the values are not set.
Is there something else that needs to be done in the ModelBinder for Core? It is registered.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @joetherod.
It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by joetherod** [comment]
I found the question asked on stackoverflow. One response was to use reflection of the model to set the values from the ValueProvider. The poster then asked why should we now do that when in prior versions of MVC we didnt have to. I asked here since at times things are not one to one when working in core and was hoping there was a better solution than using refection especially since the previous version done it for you.

**Comment by mkArtakMSFT** [comment]
@dougbu, do you have any suggestions regarding this? Thanks!

**Comment by dougbu** [comment]
The general patterns for binding to an abstract type are:
1. If it's for polymorphism, don't do it. Create distinct actions with parameters of the concrete types needed.
2. If it's for information hiding i.e. not binding some properties of a concrete type, don't do it. Use the concrete type and annotate properties with `[BindNever]` to hide them.
3. If the abstract type is still required for some reason (what reason?), create `IModelBinder` and `IModelBinderProvider` implementations specific to the abstract type. The new provider should be added before the `ComplexTypeModelBinderProvider` in `MvcOptions.ModelBinderProviders`. The new binder should be instantiated with a `ComplexTypeModelBinder` and use that to bind the concrete type (after updating the `ModelMetadata`) as shown above. If the concrete type lacks a parameterless constructor, the new binder must instantiate the instance and update `bindingContext.Model` before calling the `ComplexTypeModelBinder`.

**Comment by joetherod** [comment]
I am trying the third option and getting this exception when calling the await _modelBinder.BindModelAsync(bindingContext) on the ComplexTypeModelBinder.

System.Collections.Generic.KeyNotFoundException: 'The given key 'Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadata' was not present in the dictionary.'

**Comment by dougbu** [comment]
You need to write more code. The `ComplexTypeModelBinder` needs to be instantiated with `ModelMetadata` for the concrete type.

**Comment by joetherod** [comment]
Still getting same exception. when calling await complexTypeModelBinder.BindModelAsync(bindingContext);

`public async Task BindModelAsync(ModelBindingContext bindingContext)
        {
            if (bindingContext == null)
            {
                throw new ArgumentNullException(nameof(bindingContext));
            }

            var valueProviderResult = bindingContext.ValueProvider.GetValue(nameof(ConfigurationType));
            var model = _configurations.FirstOrDefault(f => f.ConfigurationType.ToString()
                .Equals(valueProviderResult.FirstValue, StringComparison.OrdinalIgnoreCase));

            if (model != null)
            {
                bindingContext.ModelMetadata = _modelMetadataProvider.GetMetadataForType(model.GetType());
                bindingContext.Model = model;

                var propertyBinders = new Dictionary<ModelMetadata, IModelBinder>
                {
                    {bindingContext.ModelMetadata, this}
                };

                var complexTypeModelBinder = new ComplexTypeModelBinder(propertyBinders, _loggerFactory);

                await complexTypeModelBinder.BindModelAsync(bindingContext);
                if (!bindingContext.Result.IsModelSet)
                {
                    return;
                }

                bindingContext.Result = ModelBindingResult.Success(model);

                //foreach (var modelMetadataProperty in bindingContext.ModelMetadata.Properties)
                //{
                //    bindingContext.ModelState.SetModelValue(modelMetadataProperty.Name, bindingContext.ValueProvider.GetValue(modelMetadataProperty.Name));
                //}

                //foreach (var pi in bindingContext.ModelType.GetProperties())
                //{
                //    ModelStateEntry value;
                //    if (bindingContext.ModelState.TryGetValue(pi.Name, out value))
                //    {
                //        if (pi.SetMethod != null && value?.RawValue != null)
                //        {
                //            pi.SetValue(model, value.RawValue);
                //        }
                //    }
                //}

                //bindingContext.Result = ModelBindingResult.Success(model);
            }
        }`

**Comment by joetherod** [comment]
i found this and it works. Basically what you said. 
http://www.palmmedia.de/Blog/2018/5/13/aspnet-core-model-binding-of-abstract-classes

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
