### ISSUE TITLE
Throw a clearer exception when a model type has a ref-struct-typed property

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#8552]
When a model type has a property of a ref-struct type, the error message that they see is pretty gnarly, and doesn't include the details about what type or property cause the problem. We need to report a clearer error.

Please see for more details: https://github.com/aspnet/Mvc/issues/8545

**Comment by rynowak** [comment]
I'm editing the title and original post because the description is much too broad to be achievable.

Was: `In situations, when model binding is unable to bind, the exception thrown should indicate the parameter failed to be bound.`

**Comment by rynowak** [comment]
After some discussion here, I think the safest fix for 2.2 is to go with just skipping ref struct properties on models. We'll make our `PropertyHelper` infrastructure just ignore them. That's the least impacting change. The major worry here is that new releases of .NET Core will add more spans to things, and break existing code. That would happen even if we throw a good error.

**Comment by rynowak** [comment]
Done.

**Comment by rynowak** [comment]
note that it's unclear at this point whether this change is included in preview3 or RTM - but the fix is in the code.
