### ISSUE TITLE
Routing does not work for URI templates containing the "azuredeploy" child segment

### ISSUE THREAD

**Issue by AlexeyEvlampiev** [aspnet/Mvc#8573]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

- Create  the following controller:
```csharp
namespace WebApplication1.Controllers
{
    using System.Collections.Generic;
    using Diesel.Core;
    using Microsoft.AspNetCore.Mvc;

    [ApiController]
    [Route("api/brokers")]    
    public class BrokersController : ControllerBase
    {
        [Route("{brokerId:required}/{resource:regex(^azuredeplo\\w)}")]
        [HttpGet()]
        public IEnumerable<string> Get(string brokerId)
        {
            return new string[] { "value1", "value2" };
        }
    }
}
```
- Browse to:
1) "api/brokers/my-broker/azuredeplox"
2) "api/brokers/my-broker/azuredeploy"
3) "api/brokers/my-broker/azuredeploz"

Expected: all 3 requests are routed to the "Get" action
Actual: "api/brokers/my-broker/azuredeploy" requests result in 404 (not found)

#### Description of the problem:
The "api/brokers/{brokerId}/azuredeploy" route cannot be established

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.App (2.1.1)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AlexeyEvlampiev.
I could not repro this issue with the 2.1.4 bits: 
![image](https://user-images.githubusercontent.com/34246760/46685657-d9937a80-cbaa-11e8-8945-1600d2d8579f.png)
Can you update the dependencies to the latest 2.1.x release and confirm that the issue is fixed?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
