### ISSUE TITLE
Disable "Automatic HTTP 400 responses" for an individual action

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8575]
_From @simonvane on Tuesday, 09 October 2018 11:37:17_

The "Automatic HTTP 400 responses" functionality added in ASP.NET Core 2.1 is working out really well in most cases. However, I have one action where I need to do some pre-processing before the validation run.

I don't want to lose the functionality for all actions by setting SuppressModelStateInvalidFilter = true. I'd like to be able to say "don't validate" for this action, perhaps with a SuppressModelStateInvalidFilterAttribute on the action.

That way I could retain the benefit but handle special cases myself.

Is there a way to achieve this at the moment?

Thank you.

_Copied from original issue: aspnet/Home#3600_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @simonvane.
@pranavkm, can you please answer this question? Thanks!

**Comment by pranavkm** [comment]
@simonvane there isn't a gesture to disable the filter on a per-action basis, but writing a convention to do this should be fairly trivial:

```C#
[ApiController]
public class PersonController
{
    [SuppressModelStateInvalidFilter]
    public ActionResult<Person> Get() => new Person();
}

public class SuppressModelStateInvalidFilterAttribute : Attribute, IActionModelConvention
{
    public void Apply(ActionModel action)
    {
        for (var i = 0; i < action.Filters.Count; i++)
        {
            if (action.Filters[i] is ModelStateInvalidFilter)
            {
                action.Filters.RemoveAt(i);
                break;
            }
        }
    }
}
```

**Comment by simonvane** [comment]
Thanks a lot @pranavkm, that worked a charm for me.

Just for a bit of context for other people looking at this, here's what I ended up with in my controller action:

`if (model == null)
{
    return BadRequest(ModelState);
}

model.Property = valueFromPath;

ModelState.Clear();
if (TryValidateModel(model) == false)
{
    return BadRequest(ModelState);
}

// Happy path
`
