### ISSUE TITLE
RouteValueProvider and SimpleTypeModelBinder cannot handle DateTimeOffset in several cultures. 

### ISSUE THREAD

**Issue by Danielku15** [aspnet/Mvc#8578]
#### Is this a Bug or Feature request?: 
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

- Run the Microsoft.AspNet.OData.Test.DateTimeTest.FunctionsWorksOnDateTime unit test of the [OData/WebApi](https://github.com/OData/WebApi) project on a system where the DefaultCulture is having a different date format than the InvariantCulture. 
- To force this you can add the following line in the `DateTimeTest.GetClient` method. With en-US the test is green, with de-CH it fails
```csharp
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.GetCultureInfo("de-CH");
```

#### Description of the problem:

The RouteValueProvider uses `.ToString()` to convert the route value to string. and then provides a culture along the result.  But actually the RouteValueProvider must use `System.Convert.ToString(value, culture)` to properly convert the object with the correct culture to a string: 

https://github.com/aspnet/Mvc/blob/9daf5ff7a4e092b3a84c060c44148d7d5d40b5c3/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/RouteValueProvider.cs#L94-L95

The SimpleTypeModelBinder uses a TypeConverter to convert it then back to an object using the culture from the ValueProvider:

https://github.com/aspnet/Mvc/blob/a67d9363e22be8ef63a1a62539991e1da3a6e30e/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/SimpleTypeModelBinder.cs#L102-L105

This fails if the current culture is not matching the culture defined by the RouteValueProvider. My CurrentCulture is "de-CH" but the ValueProvider has detected somehow InvariantCulture. This leads to a wrong serialization.

```csharp
DateTimeOffset(DateTime.Parse("2012-12-22T01:02:03+01:00")).ToString()
== "22.12.2012 01:02:03 +01:00" //(de-CH)
```

The DateTimeOffsetConverter will try to parse it with InvariantCulture expecting the format `12/22/2012 01:02:03 +01:00` and will fail with an exception. 

The result in my case is that the `CalcBirthday` function gets "0001-01-01T00:00:00.0000000+00:00" as parameter (default value). 

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

Microsoft.AspNetCore.Mvc 2.0.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Danielku15.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
@Danielku15 the [OData/WebApi](https://github.com/OData/WebApi) repo is rather large. For example, I see multiple `DateTimeTest` classes. Could you provide a minimal repro showing the issue, preferably in a separate GitHub repo?

Nonetheless, I took a quick glance at the code and suspect the client thread's culture is not visible to the service. Suggest calling `IMvcBuilder.AddMvcLocalization()` in your `Startup` class. (`IMvcBuilder` is what `AddMvc()` returns.)

**Comment by Danielku15** [comment]
I was able to reproduce the error and uploaded [gist here](https://gist.github.com/Danielku15/4b2f12a45dbe69c9c61eeca91e98daa1). 

A thing that was not that clear to me before, is that as a prerequisite you need to have a module which fills already deserialized objects into the `RouteValueDictionary` to cause the exception. 

In OData when you call a function a special `IRoutingConstraint` and `ODataPath` fill the parameter values into the `RouteValueDictionary`. A OData request like `http://localhost/odata/DateTimeModels(2)/Default.CalcBirthday(dto=2012-12-22T01:02:03Z)` will fill a "dto" RouteValue with a `DateTimeOffset` object. In my reproduction I needed to also setup a infrastructure like this. 

Then the RouteValueProvider serializes it again to a CurrentCulture string via `.ToString()` and attemps a load afterwards via the TypeConverter using InvariantCulture and throws. 

It is anyhow strange that there happens a back and forth conversion of objects via string. IMHO the `ValueProviderResult` class should hold objects, not strings and directly provide the object for binding. The `SimpleTypeModelBinder` then could check if the `IValueProvider` already provided the expected target type and only do a conversion if needed. Of course a lot of infrastructure seems to be based on this and cannot be simply changed. For me it does not fit well that the RouteData supports full objects but the model binder then expects everything to be convertable via `.ToString()` and `IValueConverter`.

Of course the OData library could theoretically fill string values into the RouteValueDictionary to make it work but this would not fit well with many features of the OData parser and models.

**Comment by dougbu** [comment]
@Danielku15 it is inconsistent that `RouteValueProvider` serializes values using the current culture but creates the `ValueProviderResult` using its `Culture` (`InvariantCulture` by default). Correcting this inconsistency i.e. using `Culture` when serializing values is the most we can do in the 2.2 release. To change the `ValueProviderResult` as you suggest would be a significant breaking change.

Even this `RouteValueProvider` change is a slight break. But, none of our tests fail when using `Convert.ToString(value, Culture)`. That implies the use of the current culture was unintended.

My main concern is `RouteValueProvider` can be instantiated with a specific `CultureInfo` i.e. `InvariantCulture` is just the default. Other places where we convert values from a `RouteValueDictionary` to strings don't have similar overrides. I'm double-checking to confirm the strings are used as programmatic tokens in those other places but it looks good so far.

----
@danroth27 @mkArtakMSFT I'm marking this as a bug. We should use `InvariantCulture` or the configured `CultureInfo` when serializing `RouteValueDictionary` values.

**Comment by Danielku15** [comment]
@dougbu It totally agree that it makes most sense to fix only the bug in a first go with the serialization.

I mostly wanted to highlight that this area looks a bit strange regarding the back-and-forth serialization so you become aware of it. Maybe you want to consider if for a future design change. I guess performance wise it does not make a too big difference today as in most cases the RouteValues are strings anyhow. Only in special scenarios like for OData functions where URL binding is done different we have some objects that are undergoing this roundtrip.

**Comment by dougbu** [comment]
@mkArtakMSFT @danroth27 what is the priority of this issue?

FYI I've found several places where we convert `RouteValueDictionary` entries to strings using `ToString()`. Fixed them all but haven't added tests yet.

Fun fact: Exactly 0 tests fail with the changes in place 😈

**Comment by dougbu** [comment]
c74a945dda
