### ISSUE TITLE
TypeFilterAttribute does not honor IsReusable on initial requests if simultaneous

### ISSUE THREAD

**Issue by ti82** [aspnet/Mvc#8579]
Bug

Here is my ConnectionLimitAttribute which I use to limit connections to a controller action, and return a 503 if the limit has been reached:

```
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public class ConnectionLimitAttribute : TypeFilterAttribute
    {
        /// <summary>
        /// Creates a new instance of the <see cref="ConnectionLimitAttribute"/> class.
        /// </summary>
        public ConnectionLimitAttribute(int limit) : base(typeof(ConnectionLimitImpl))
        {
            // Pass the connection limit argument to the implementation
            this.Arguments = new object[] { limit };
            this.IsReusable = true;
        }

        class ConnectionLimitImpl : IResourceFilter
        {
            private readonly ILogger<ConnectionLimitAttribute> logger;
            private readonly int limit;
            private readonly string id;

            private static object safe = new object();

            private int connectionCount;
            
            /// <summary>
            /// Creates a new instance of the <see cref="ConnectionLimitImpl"/> class.
            /// </summary>
            /// <param name="limit">The number of simultaneous connections to allow.</param>
            public ConnectionLimitImpl(int limit, ILoggerFactory loggerFactory)
            {
                this.id = Guid.NewGuid().ToString("D").ToUpperInvariant();

                this.limit = limit;
                this.logger = loggerFactory.CreateLogger<ConnectionLimitAttribute>();
            }

            /// <summary>
            /// Implementation of the <see cref="IResourceFilter"/> interface.
            /// </summary>
            public void OnResourceExecuted(ResourceExecutedContext context)
            {
                lock (safe)
                {
                    // The resource has been executed so the connectionCount can be decremented
                    this.logger.LogInformation($"REQUEST {context.HttpContext.TraceIdentifier} CONNECTION {this.id} RELEASED");
                    Interlocked.Decrement(ref this.connectionCount);
                }
            }

            /// <summary>
            /// Implementation of the <see cref="IResourceFilter"/> interface.
            /// </summary>
            public void OnResourceExecuting(ResourceExecutingContext context)
            {
                // Need to lock around full conditional because two very close requests could
                // get past the CompareExchange and into the Increment
                lock (safe)
                {
                    // Check the connectionCount against the limit and respond appropriately
                    if (limit == Interlocked.CompareExchange(ref this.connectionCount, this.limit, this.limit))
                    {
                        this.logger.LogInformation($"REQUEST {context.HttpContext.TraceIdentifier} CONNECTION {this.id} REJECTED");
                        // Indicate that the connection limit was exceeded with a HTTP 503 response
                        context.Result = new StatusCodeResult(StatusCodes.Status503ServiceUnavailable);
                    }
                    else
                    {
                        // Increment the connectionCount and let the pipeline continue
                        Interlocked.Increment(ref this.connectionCount);
                        this.logger.LogInformation($"REQUEST {context.HttpContext.TraceIdentifier} CONNECTION {this.id} ACQUIRED");
                    }
                }
            }
        }        
    }
```

My app has a single controller method, where this attribute is set to 1. Note the use of IsReusable = true in the Impl constructor. If, when the service is first started, there are several connections rapidly, it does not reuse the filter initially:

info: ConnectionLimitAttribute[0]
      REQUEST 0HLHEK2IQQTF9:00000001 CONNECTION 9AABD770-14D1-40F6-8930-9C3EBB5F9A8C ACQUIRED
info: ConnectionLimitAttribute[0]
      REQUEST 0HLHEK2IQQTF8:00000001 CONNECTION 27903C64-5CF4-4E7F-9B06-D341135918FF ACQUIRED
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://127.0.0.1:5020/alg/run multipart/form-data; boundary="26fbf333-5412-43eb-b739-9c46d83447c8" 1756239
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://127.0.0.1:5020/alg/run multipart/form-data; boundary="c6e6a6bf-0db7-4c25-8931-f2be9c7084ef" 1756239
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "PostAsync", controller = "Algorithm"}. Executing action AlgorithmController.PostAsync (AlgorithmHostService)
info: ConnectionLimitAttribute[0]
      REQUEST 0HLHEK2IQQTFA:00000001 CONNECTION 9AABD770-14D1-40F6-8930-9C3EBB5F9A8C REJECTED
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://127.0.0.1:5020/alg/run multipart/form-data; boundary="60cb7f2c-f4ab-4b2a-b3a0-33ebf66cb7f5" 1756239
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "PostAsync", controller = "Algorithm"}. Executing action AlgorithmController.PostAsync (AlgorithmHostService)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "PostAsync", controller = "Algorithm"}. Executing action AlgorithmController.PostAsync (AlgorithmHostService)
info: ConnectionLimitAttribute[0]
      REQUEST 0HLHEK2IQQTFC:00000001 CONNECTION 9AABD770-14D1-40F6-8930-9C3EBB5F9A8C REJECTED
info: ConnectionLimitAttribute[0]
      REQUEST 0HLHEK2IQQTFB:00000001 CONNECTION 9AABD770-14D1-40F6-8930-9C3EBB5F9A8C REJECTED

Nowhere in the documentation at https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1 is this concurrency issue discussed, hence I did not expect this behavior.

**Comment by rynowak** [comment]
We haven't been super clear about this in the documentation - but what is there says (emphasis mine):

```
/// Gets a value that indicates if the result of <see cref="CreateInstance(IServiceProvider)"/>
/// **can** be reused across requests.
```

In general it's not safe to assume that the framework makes a guarantee (constructs a single instance) that isn't mentioned.

----

I assume that what you want to do here is use this filter for rate-limiting all traffic to certain actions? My suggestion would be to move that functionality in a service that you access via DI, and then make the filter basically just plug it in. This grows up nicely since you can use the service in other places if applicable.

If you really like this approach and want guarantee of a single filter instance per attribute, I'd suggest implementing `IFilterFactory` yourself.

**Comment by ti82** [comment]
I'm not sure I understand how this is supposed to work. I made a new version that implements IFilterFactory.

`[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public class ConnectionLimitAttribute : Attribute, IFilterFactory
    {
        private static ConnectionLimitImpl filterImpl;
        private static object safe = new object();
        private readonly int limit;

        /// <summary>
        /// Creates a new instance of the <see cref="ConnectionLimitAttribute"/> class.
        /// </summary>
        public ConnectionLimitAttribute(int limit)
        {
            this.limit = limit;
        }

        public bool IsReusable => true;

        public IFilterMetadata CreateInstance(IServiceProvider serviceProvider)
        {
            ////if (null == filterImpl)
            ////{
            ////    lock (safe)
            ////    {
            ////        if (null == filterImpl)
            ////        {
            ////            ILoggerFactory logger = serviceProvider.GetService(typeof(ILoggerFactory)) as ILoggerFactory;

            ////            filterImpl = new ConnectionLimitImpl(this.limit, logger);
            ////        }
            ////    }
            ////}
            ILoggerFactory logger = serviceProvider.GetService(typeof(ILoggerFactory)) as ILoggerFactory;
            return new ConnectionLimitImpl(this.limit, logger);
        }

        class ConnectionLimitImpl : IResourceFilter
        {
            private readonly ILogger<ConnectionLimitAttribute> logger;
            
            private readonly string id;
            private readonly int limit;
            private static object safe = new object();

            private int connectionCount;
            
            /// <summary>
            /// Creates a new instance of the <see cref="ConnectionLimitImpl"/> class.
            /// </summary>
            /// <param name="limit">The number of simultaneous connections to allow.</param>
            public ConnectionLimitImpl(int limit, ILoggerFactory loggerFactory)
            {
                this.id = Guid.NewGuid().ToString("D").ToUpperInvariant();

                this.limit = limit;
                this.logger = loggerFactory.CreateLogger<ConnectionLimitAttribute>();
            }

            /// <summary>
            /// Implementation of the <see cref="IResourceFilter"/> interface.
            /// </summary>
            public void OnResourceExecuted(ResourceExecutedContext context)
            {
                lock (safe)
                {
                    // The resource has been executed so the connectionCount can be decremented
                    this.logger.LogInformation($"REQUEST {context.HttpContext.TraceIdentifier} CONNECTION {this.id} RELEASED");
                    Interlocked.Decrement(ref this.connectionCount);
                }
            }

            /// <summary>
            /// Implementation of the <see cref="IResourceFilter"/> interface.
            /// </summary>
            public void OnResourceExecuting(ResourceExecutingContext context)
            {
                // Need to lock around full conditional because two very close requests could
                // get past the CompareExchange and into the Increment
                lock (safe)
                {
                    // Check the connectionCount against the limit and respond appropriately
                    if (limit == Interlocked.CompareExchange(ref this.connectionCount, this.limit, this.limit))
                    {
                        this.logger.LogInformation($"REQUEST {context.HttpContext.TraceIdentifier} CONNECTION {this.id} REJECTED");
                        // Indicate that the connection limit was exceeded with a HTTP 503 response
                        context.Result = new StatusCodeResult(StatusCodes.Status503ServiceUnavailable);
                    }
                    else
                    {
                        // Increment the connectionCount and let the pipeline continue
                        Interlocked.Increment(ref this.connectionCount);
                        this.logger.LogInformation($"REQUEST {context.HttpContext.TraceIdentifier} CONNECTION {this.id} ACQUIRED");
                    }
                }
            }
        }        
    }`

The code above creates again creates multiple instances for simultaneous requests. If I uncomment the singleton implementation, that obviously works, but that leaves me with a single instance for all controller actions at which point I lose the flexibility and could just use a global filter with simpler code.

Can you elaborate on what you mean by making a service which is plugged in by a filter? Would I need action context to know which filter instance to use based on the decorated controller action?

**Comment by pranavkm** [comment]
You'd want `ConnectionLimitAttribute` to be registered in DI as a singleton and use `ServiceFilterAttribute` to fetch it. DI should ensure there is only one instance of the service created.

**Comment by rynowak** [comment]
So correct me if I'm wrong, you want each attribute to return a single instance of the filter ... so the code you have currently commented out in `CreateInstance` is what you want.

**Comment by ti82** [comment]
I wanted each attribute to have an independent limit and counter, scoped to the action. With the singleton in my commented code, any action with ConnectionLimit would share the same implementation, and the limit would be set by the first action regardless of any others. The other effect is that they'd be sharing the counter, so two separate actions collide. That's why I brought up having context, so the implementation could have some mapping from action->limit&counter variables to avoid collisions, but I am not familiar enough to know if that's a possibility.

But the more I thought about this, I came to the conclusion that I only really need to limit my one resource intensive operation, and anything else wouldn't need one. So I am going to go with the singleton and not over-engineer this for a problem that I don't currently have.

Your comments are much appreciated!
