### ISSUE TITLE
Get service from WebApplicationFactory

### ISSUE THREAD

**Issue by simonvane** [aspnet/Mvc#8581]
I want to set up my tests using `WebApplicationFactory<T>` as detailed in [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/test/integration-tests?view=aspnetcore-2.1).

Before some of my tests I need to use a service configured in the real Startup class to set things up.
The problem I have is that I can't see a way to get a service from the factory.

I could get a service from `factory.Server` using `factory.Host.Services.GetRequiredService<ITheType>();` except that `factory.Server` is null until `factory.CreateClient()` has been called.

Is there any way that I am missing to get a service using the factory?

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @simonvane.
@javiercn, can you please look into this? Thanks!

**Comment by simonvane** [comment]
Thanks @javiercn.

In most of my tests I fake out the external dependencies but in a few of my tests I needs to run the real system to make sure DI / configuration is set up correctly. In order to run that set of tests I need to get the real service for one of the external systems and use it to create an organization in the external system to run the tests against.

So I would like to call `factory.Host.Services.GetRequiredService<ITheType>();' the constructor of the test fixture then run a set of tests, perhaps with changes to what is injected per test.

Unfortunately, until `factory.CreateClient()` gets called `factory.Server` is null. So I could call `factory.CreateClient()` before I call `factory.Server` but this seems like strange behaviour so I was wary of doing that in case it changed in future.

Does that make sense?

**Comment by javiercn** [comment]
@simonvane You can do initialization as described in here https://github.com/aspnet/Mvc/issues/8439#issuecomment-420362661

Alternatively you can simply call Program.CreateWebHostBuilder(Array<string>.Empty()).Build().Services

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
