### ISSUE TITLE
Make `AnsiTextWriter` disposable

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#8592]
#### Is this a Bug or Feature request?
Bug that's part of #7947.

#### Description of the problem
The `dotnet-getdocument` tool's inside man (`GetDocument.Insider.dll` and `GetDocument.Insider.exe`) included in the Microsoft.Extensions.ApiDescription.Design package includes an `AnsiTextWriter` which wraps a `TextWriter`. Since `TextWriter` is disposable, `AnsiTextWriter` should be disposable. See https://github.com/aspnet/Mvc/pull/8585/files/5cd86977eda1d06e6619e3f75bded8ee40761a2c#diff-5c5b5339e8860132f6ec780706eac317R11 and @mkArtakMSFT's comment [here](https://github.com/aspnet/Mvc/pull/8585/files/5cd86977eda1d06e6619e3f75bded8ee40761a2c#r224618340) in PR #8585.

`AnsiConsole` wraps an `AnsiTextWriter` instance but is never instantiated (its wrapped  `AnsiTextWriter` instance is `static`). Therefore, `AnsiConsole` doesn't need to be `IDisposable`.

##### Note
`AnsiTextWriter` should be removed as part of #8566. Should close this issue if we do that one first.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`
See the [features/client.code.generation](https://github.com/aspnet/Mvc/tree/feature/client.code.generation) branch. That work is intended for the 2.2 Preview 3 milestone.

**Comment by mkArtakMSFT** [comment]
Closing this per @rynowak 's response to my comment in the referenced PR.
