### ISSUE TITLE
Mimic CreateXXX methods from TestServer in WebApplicationFactory

### ISSUE THREAD

**Issue by cortex93** [aspnet/Mvc#8603]
Currently, WebApplicationFactory only expose CreateHttpClient.

I have a use case where I use HttpClient factory to create the client. The IHttpMessageHandlerBuilderFilter allow to configure the PrimaryHandler but the only way to get a test HttpMessageHandler, is to call CreateClient first to initialize the Server property, then use this Server property.
I think the same applies if you want to test websocket calls.

It would be easier to have the same set of Create method as TestServer or if we must use the property, having a way to call EnsureServer publicly.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @cortex93.
@javiercn, what do you think about this?

**Comment by javiercn** [comment]
@cortex93 I'm not sure I understand what your scenario is here, can you describe at a higher level what you are trying to achieve?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
