### ISSUE TITLE
LinkGeneration + PathBase plans

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8605]
Consider:

```C#
app.Map("/test", subApp =>
{
    subApp.Run(async context =>
    {
        var linkGenerator = context.RequestServices.GetRequiredService<LinkGenerator>();
        var url = linkGenerator.GetPathByAction(context, "Index", "Home");

        await context.Response.WriteAsync($"<a href=\"{url}\">Click me</a>");
    });
});

app.UseMvc(routes =>
{
    routes.MapRoute("default", "{controller=Home}/{action}");
});
```

The path generated by `LinkGenerator` uses the `PathBase` of the current request and incorrectly produces `/test/Home/Index`. Are there any plans to try and get link generation to work correctly with middleware branches? Since the branch participates in link generation, I'd expect ~~global~~ routing to be aware of it.

**Comment by rynowak** [comment]
This is all working as intended but it's a little vexxing. This is something that will be worth calling out explicitly in the documentation.

**Comment by mkArtakMSFT** [comment]
@rynowak, I'm not sure it's you or @JamesNK who will handle writing the documentation. Please reassign as necessary.

**Comment by rynowak** [comment]
Thanks! This one will be me I think.

**Comment by rynowak** [comment]
Closing this since I've added it to the info I gave the doc writers.
