### ISSUE TITLE
Extensions Package for DataAnnotations: Recursively validating an entire object graph

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8606]
_From @spottedmahn on Sunday, 14 October 2018 17:52:02_

Can the code that validates an object graph in ASP.NET Core MVC be moved to a `Microsoft.Extensions` package to allow for re-use outside of MVC?

---

### Background

I wanted to validate an object and I learned of this limitation on the `Validator`:

>It does not recursively validate the property values of the object.

Source: [Validator.TryValidateObject Method](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.validator.tryvalidateobject?view=netcore-2.1)

### MVC Does this, 🤔

But I know ASP.NET Core MVC validates the whole object graph.  How can I use it?

It seems that [`Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVistor`](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidationVisitor.cs) seems to do the magic but it seems to be tied to MVC based upon the dependencies:

```csharp
public ValidationVisitor(
            ActionContext actionContext,
            IModelValidatorProvider validatorProvider,
            ValidatorCache validatorCache,
            IModelMetadataProvider metadataProvider,
            ValidationStateDictionary validationState)
        { .... }
```

### Additional Notes

Reference: [StackOverflow post](https://stackoverflow.com/questions/7663501/dataannotations-recursively-validating-an-entire-object-graph/7665862)

Open Source Package to validate the object graph: [reustmd/DataAnnotationsValidatorRecursive](https://github.com/reustmd/DataAnnotationsValidatorRecursive)

_Copied from original issue: aspnet/AspNetCore#3626_

**Comment by Eilon** [comment]
Even though this is a request to move functionality *out* of MVC, the discussion might as well begin with the MVC folks.

**Comment by rynowak** [comment]
We would consider doing something like this if we attempted to decouple model binding and validation from MVC in the future. I don't think we should make a new package if we don't have a plan to use it ourselves and it doesn't fill a critical need that our users have. We have a track record of doing a bad job when we build something we don't use.

@spottedmahn I'd suggest copying validation visitor out of MVC and customizing the code, then publishing your own package. The details of it are indeed quite coupled to MVC. You'll have to define a few core capabilities to make this work.
- How do you determine what types/properties to consider?
- How to find/construct/cache validators?
- What to do with errors?

**Comment by spottedmahn** [comment]
Copy that, thanks 🙏 @rynowak

**Comment by spottedmahn** [comment]
close-me, thanks @Eilon
