### ISSUE TITLE
Difference in method constraint with 2.1 and endpoint routing

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8609]
Not necessarily a bug, but a difference in routing behavior between 2.1 and endpoint that needed to be noted:

Consider:
```C#
[Route("/[controller]/[action]")]
[Test]
public class HomeController : Controller
{
    [HttpDelete]
    public IActionResult Index() => View("/Pages/Index.cshtml");

    public IActionResult Index2() => View("/Pages/Index.cshtml");

}

public class Test : Attribute, IActionHttpMethodProvider
{
    public IEnumerable<string> HttpMethods => new[] { "GET", "PUT" };
}
```

With 2.1 routing, GET, PUT, DELETE on /Home/Index -> 404
With 2.2 routing, GET, PUT on /Home/Index -> 405. DELETE -> 200

Filing an issue so we know are aware of this change in behavior

**Comment by rynowak** [comment]
This is something that no user would try and it didn't do anything useful in 2.1 - note that all of these result in a 404 in 2.1. I think we can ignore this.

**Comment by shawnwildermuth** [comment]
You likely don't need to use 2.1 compat completely, just turn off endpoint routing:

```
services.AddMvc().SetCompatibilityVersion( CompatibilityVersion. 
  .AddMvcOptions( opt => opt.EnableEndpointRouting = false );
```

**Comment by mkArtakMSFT** [comment]
Closing this per @rynowak's comment.
