### ISSUE TITLE
ViewBag doesn't propagate back to parent

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Mvc#861]
Run MusicStore and look at the title of the page. Notice that the property coming from the ViewBag is empty and the title is " - Music store"

cc @pranavkm - for code
cc @Praburaj - this could be checked as part of the automation

This is blocking the sample I'm working on

**Comment by VaclavElias** [comment]
HI @victorhurdugaci, @Praburaj  was this issue resolved?

When I set ViewBag.Title in the Controller I can see it in my ViewComponent View and Layout meta.

1) I can override it in the ViewComponent class and see in my ViewComponent View but the Layout meta displays the one defined in the Controller.

2) I can override it in ViewComponent View and see in my ViewComponent View but the Layout meta displays the one defined in the Controller.

Shouldn't it propagate also to Layout from ViewComponent class or ViewComponent View?

If this is intended for ViewComponent what is the way around as I need to display my Title and Description In Layout which get defined in ViewComponent class.

Thank you.

**Comment by VaclavElias** [comment]
I think I have never been aware that Partials and ViewComponents have got its own ViewBags and found a way around from your collagues :) https://github.com/aspnet/Mvc/issues/3143
