### ISSUE TITLE
Unable to map error codes to custom problem details via `ApiBehaviorOptions`

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#8611]
In my controller (`ApiController`) the action returns `BadRequest()`:

```csharp
return BadRequest();
```

In the startup I have the following mapping defined:
```csharp
services.Configure<ApiBehaviorOptions>(options =>
{
    options.ClientErrorMapping.Add(400, new ClientErrorData { Link = "sample link", Title = "fake error customized" });
});
```
But this has no effect and client gets the usual `ProblemDetails` error - no matter whether I have that mapping or not:

```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "Bad Request",
    "status": 400,
    "traceId": "0HLHJ0KNGN7K7:00000002"
}
```

**Comment by pranavkm** [comment]
Likely the same cause as https://github.com/aspnet/Mvc/issues/8564. The order of when `Configure` is called matters. Using https://github.com/aspnet/Mvc/pull/8618 as a way to make this less brittle.

**Comment by pranavkm** [comment]
Introduced a new API to allow configuring `ApiBehaviorOptions`. The guidance is to use `IMvcBuilder.ConfigureApiBehaviorOptions` to configure the app over `services.Configure<ApiBehaviorOptions>`
