### ISSUE TITLE
Pre-compiled Razor pages don't have underscores applied to route table correctly.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#8617]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
1. `dotnet new razor`
2. Rename `Pages/Privacy.cshtml` => `Pages/_Privacy.cshtml`
4. `dotnet run`
5. Try hitting `/_Privacy`

#### Description of the problem:
The `_Privacy` Razor page is routable. However, if you were to set `<RazorCompileOnBuild>false</RazorCompileOnBuild>` it would not be.

/cc @pranavkm

**Comment by pranavkm** [comment]
Updated title to reflect the current behavior. Any Razor file with an `@page` will now be served
