### ISSUE TITLE
custom multi value model binder and asp-all-route-data are hard to work with

### ISSUE THREAD

**Issue by schmitch** [aspnet/Mvc#8622]
#### Is this a Bug or Feature request?:

Feature Request

#### Description of the problem:

Follow up from: https://github.com/aspnet/Mvc/issues/7826#issuecomment-431190806

Currently when creating a Custom multi value Model Binder, for whatever reason it's not easy to work with the `asp-all-route-data` because `asp-all-route-data` does not support multiple values for the same keys, so that means that the modle binder needs to handle keys with indexes, in most cases people can actually just extend from `CollectionModelBinder`, but not always will that work since that means that you can't have custom logic, how the value is extracted or how the value will be used inside the model. i.e. binding complex objects is way harder than when we work with simple keys.

currently what can be done, is that some logic of `CollectionModelBinder`, but I think the only sane way would be to actually have consistent keys, even with the `asp-all-route-data` tag helper or deprecate the old one for one that supports multiple values per key.

At the moment it's easier to actually not use tag helpers and instead build the string yourself that should be linked to, if it is a complex model.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @schmitch.
@rynowak, what will be your thoughts regarding this?

**Comment by schmitch** [comment]
currently I the easiest case would be model binder that loads data from the database:

```
 var modelName = bindingContext.BinderModelName;
            if (string.IsNullOrEmpty(modelName))
            {
                return;
            }

            var valueProviderResult = bindingContext.ValueProvider.GetValue(modelName);
            if (valueProviderResult.Length <= 0)
            {
                return;
            }

            var additionalDictionary = await _additionalService.DictionaryWithKeywords(clientId);

            var additionals = new Dictionary<string, AdditionalData>();

            foreach (var stringValue in valueProviderResult)
            {
                var split = stringValue.IndexOf('~');
                if (split != -1)
                {
                    var key = stringValue.Substring(0, split);
                    var value = stringValue.Substring(split + 1);

                    if (additionalDictionary.ContainsKey(key))
                    {
                        var additional = additionalDictionary[key];
                        var data = additional.ToData(value);
                        additionals[data.ToString()] = data;
                    }
                }
            }

            bindingContext.Result = ModelBindingResult.Success(additionals.Values.ToList());
```

i.e. our key value looks like that `additional=KEY~VALUE` and we bind our Model to something like that:
```
class AdditionalData {
public int Id ...
public string Title ...
public string Value ...
... other data
}
```

currently this is just one of our custom model binders and probably the simpliest, I also think basically every use case of a multi value model binder would have problems when binding these [0], [x] objects.

**Comment by rynowak** [comment]
Routing does support multiple values - though it might not be what you want.  You can pass any `IEnumerable` as a route value and it will be appended to the query string by repeating the key.

Ex:
```
Url.Action("Products", "Buy", new { product = new string[] { "Soap", "Celery", "Milk", }} ); 
```

Produces:
```
/Products/Buy?product=Soap&product=Celery&product=Milk
```

Does this help or are you looking for something else?

**Comment by mkArtakMSFT** [comment]
@schmitch, can you please confirm that @rynowak's suggestion resolves your issue?

**Comment by schmitch** [comment]
well to be fair multiple values can be used as route values already, even without `Url.Action`, by just creating the string by yourself.
`Url.Action` makes things even more confusing, since obvisiously the implementation differs from `asp-all-route-data`, which makes this issue even worse.

**Comment by rynowak** [comment]
You can do the same thing with `asp-all-route-data`  - if the value is an `IEnumerable<>` it will get serialized  to the query string as multiple values.

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback, @schmitch.
We're closing this issue as this is not something we plan to change.
