### ISSUE TITLE
[BindRequired] validation attribute does not work in case of [FromBody] model binder

### ISSUE THREAD

**Issue by olegkaliuga** [aspnet/Mvc#8631]
Hi all,

Here is code snippet to reproduce mentioned behaviour:

```csharp
[HttpPost]
public IActionResult Post([FromBody] Model model)
{
      if (!ModelState.IsValid)
      {
             return BadRequest(ModelState);
      }
      return Ok();
}

public class Model
{
       [BindRequired]
       public int Price { get; set; }
}
```
If we send empty json object {}, the action will return Ok result (however, I expect BadRequest result, because Price value was not provided at all)

`Microsoft.AspNetCore.All`: 2.1.5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @olegkaliuga.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
`[BindRequired]` is not relevant when using input formatters aka `[FromBody]`. The separation comes from formatters relying on external serializers / deserializers, none of which understand `[BindRequired]`.

To do something similar, either make `Price` a `string`, use `[Required]` and parse the string in your action or give `Price` an invalid default value e.g. `-1` in this case.
