### ISSUE TITLE
Reevaluate the naming of View Components Default.cshtml

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Mvc#8632]
#### Is this a Bug or Feature request?:
Feature

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

- Create a few [View Components ](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components)
- Open them all up
- Confused now? 😊

#### Description of the problem:
Naming the files `Default.cshtml` makes it really hard to know what file you are in. If I open 5 components up then I have 5 tabs in VS that all say `Default.cshtml`.

>We recommend you name the view file Default.cshtml

[Source](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.1#view-search-path)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @spottedmahn.
This is not something we plan to change in the near future.
