### ISSUE TITLE
Feature Request: FromClaimAttribute(string claimName)

### ISSUE THREAD

**Issue by jholovacs** [aspnet/Mvc#8634]
#### Is this a Bug or Feature request?:
Feature Request

#### Description of the problem:
When collecting data for a controller endpoint, sometimes the information is available in the ClaimsPrincipal.  I think it would make a lot of sense to have a FromClaimAttribute in addition to FromRouteAttribute, FromBodyAttribute, etc for supplying an endpoint with parameter data that will be needed by the controller to perform its function.  Usage would be something like:

```csharp
public async IActionResult<FooClass> GetMyFoo([FromClaim("username")] string username, [FromBody] BarModel model)
{
    var foo = await _fooService.GetFooForUserWithParameters(username, model);
    return Ok(foo);
}
```

The advantage here is:

1. This becomes easier to test; less scaffolding is necessary (you don't need to mock a ClaimsPrincipal to test this method)
2. (IMHO) this keeps the method "cleaner" in the sense that the method doesn't need to "get" a dependency, it's provided for it (which is a very SOLIDish kinda thing)

Thoughts?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jholovacs.
We'll consider this feature during the next release planning period and update the status of this issue accordingly.

**Comment by mkArtakMSFT** [comment]
Thanks for your feature request, @jholovacs.
After reviewing this ask we've decided that this is not something we will do as part of the ASP.NET Core framework. If you wish to implement it yourself, The way we did added the `HeaderModelBinder` would be a good example to follow: https://github.com/aspnet/Mvc/pull/7294
