### ISSUE TITLE
TryValidateModel throws exception when unit tested

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#8640]
_From @mmulhearn on Wednesday, 24 October 2018 16:29:52_

When attempting to run a unit test against an ApiController in ASP.NET Core, TryValidateModel throws an exception that ObjectValidator is null.  When trying to set the property, I can't seem to figure out what properties should be set to what.  I can inject the DefaultObjectValidator, but it always passes, even when I purposefully set bad values to my model.

[There was a bug opened for this years ago](https://github.com/aspnet/Mvc/issues/3586) that I found but the only solution seemed to be mocking, which I don't want to do because I want the test to legit fail should I pass it bad data to ensure everything is configured correctly in the controller.

    public UserTests()
        {
            ICompositeMetadataDetailsProvider p = new DefaultCompositeMetadataDetailsProvider(new IMetadataDetailsProvider[]
            {
                new DefaultValidationMetadataProvider(),
                new DefaultBindingMetadataProvider() 
            });
            IModelMetadataProvider metadataProvider = new DefaultModelMetadataProvider(p);
            var objectValidator = new DefaultObjectValidator(metadataProvider, new List<IModelValidatorProvider>
            {
                new DefaultModelValidatorProvider()
            });

            Controller = new UserController
            {
                ObjectValidator = objectValidator
            };
        }`

Setting up a controller should be much easier than this and object validation should be initialized by default. At the very least there should be some documentation somewhere regarding how to initialize this property outside of the full request pipeline.

_Copied from original issue: aspnet/AspNetCore#3714_

**Comment by mkArtakMSFT** [comment]
_From @mmulhearn on Wednesday, 24 October 2018 16:42:32_

I ended up creating my own IObjectModelValidator, which I'm not sure is the best approach, but it seems to work.

```
public class TestingObjectValidator : IObjectModelValidator
    {
        public ControllerBase Controller { get; set; }

        public void Validate(ActionContext actionContext, ValidationStateDictionary validationState, string prefix, object model)
        {
            var validationContext = new ValidationContext(model, null, null);
            var validationResults = new List<ValidationResult>();
            Validator.TryValidateObject(model, validationContext, validationResults, true);
            foreach (var validationResult in validationResults)
            {
                Controller.ModelState.AddModelError(validationResult.MemberNames.FirstOrDefault() ?? string.Empty, validationResult.ErrorMessage);
            }
        }
    }
```

```
public UserTests()
        {
            Controller = new UserController();
            var objectValidator = new TestingObjectValidator
            {
                Controller = Controller
            };
            Controller.ObjectValidator = objectValidator;
        }
```

I would still like to see a fix so this doesn't need to be done.  Who knows if I'm missing a configuration or edge case that is addressed in the full pipeline.

**Comment by mkArtakMSFT** [comment]
_From @mkArtakMSFT on Wednesday, 24 October 2018 17:00:47_

Thanks for contacting is, @mmulhearn.
@pranavkm, is the approach taken here one we'd recommend, or is there a better way to do this?

**Comment by pranavkm** [comment]
> I want the test to legit fail should I pass it bad data to ensure everything is configured correctly in the controller.

We believe that unit tests should focus on the code inside the controller and not on the underlying framework. Our doc has a pretty detailed guidance on how to author unit tests for controllers - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.1. What you're looking for sounds like an integration test and the doc here - https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1 has a pretty detailed walkthrough on what it would comprise of and how you'd write one.

**Comment by mmulhearn** [comment]
I disagree with your assessment.  For instance, good REST APIs pass IDs in the URL, such as /product/1.  The model for that action may contain a property for that product ID, such as UpdateProduct.Id.  Technically, the caller is already passing the ID via the URL, so making them also pass it in the body of the PUT/POST is repetitive.  Therefore, it could technically make sense for the controller to take what data IS passed in the body (such as an updated product name), created the model, then assign the ID property on the model in the controller method body:

```
public async Task<IActionResult> UpdateProduct(int id, UpdateProduct model)
{
    model.Id = id;
    UpdateProject(model); // or whatever
}
```

In this case, you would disable model validation in your app config, then run a "revalidation" on the model.  In this setup, you'd want to test a couple things:

1. That validation is being run at all
2. The validation on the data is valid
3. The DataAnnotation attributes (custom or otherwise) are property validating as expected

ObjectValidator is very much part of a valid unit test.

**Comment by poke** [comment]
> ObjectValidator is very much part of a valid unit test.

Only if you mock it though. If you want to rely on the real implementation, then you are doing an integration test, and then you should just run the full integration test stack.

In any case: You do not need to know how to properly set up a validator.
