### ISSUE TITLE
calling RenderBody in a layout breaks async rendering (when tasks created before but awaited after)

### ISSUE THREAD

**Issue by Igorbek** [aspnet/Mvc#8644]
#### Is this a Bug or Feature request?
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

Repro project: https://github.com/Igorbek/aspnetcore-mvc-async-render-issue

- run and navigate to index page
- it is expected to render in ~3s (`Task.Delay`)
- first it renders ok
- refresh page a few times
- you may first see inconsistent in rendering order
- then see `ArgumentOutOfRangeException` exception thrown at `System.Collections.Generic.List<T>.RemoveAt(int index)` at `Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.MemoryPoolViewBufferScope.GetPage(int pageSize)`

#### Description of the problem:

The page uses a layout that starts a few tasks with rendering async partials. The partials intentionally have a delay of 3s before rendering.
When layout awaits these tasks after calling `RenderBody`, async rendering breaks.

```cshtml
@ {
  var task1 = Html.PartialAsync(...);
  var task2 = Html.PartialAsync(...);
}
@RenderBody()
@await task1
@await task2
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

- `Microsoft.AspNetCore.App@2.1.1`
- `Microsoft.AspNetCore.Mvc@2.1.3`
- also tested with 2.2 preview3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Igorbek.
@pranavkm, can you please investigate this? Thanks!

**Comment by pranavkm** [comment]
The `Task` produced as a result of `PartialAsync` will continue to execute in the background which puts you firmly in multi-threaded territory. None of the view rendering APIs in MVC are thread safe, what you're attempting to do isn't a supported scenario.

**Comment by pranavkm** [comment]
> I am curious, what is the point of async rendering then if you cannot run them in parallel.

async in views is to allow for performing non-blocking calls. Most parts of the framework aren't designed to be thread safe, so it's difficult to recommend a solution where independent components can work concurrently in isolation. Your best bet would be to do the work up front as part of your controller action where you can do parallel work and forward the results to the view.
