### ISSUE TITLE
MvcCoreMvcOptionsSetup incorrectly marks IFormCollection with BindingSource=FormFile

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8669]
This ultimately doesn't have an affect on the `FormFileModelBinder` since it looks at the type, but the value is incorrect: https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/MvcCoreMvcOptionsSetup.cs#L107

**Comment by mkArtakMSFT** [comment]
Closing as the value is neglectable. Also - nobody complained about this ever!
