### ISSUE TITLE
CompilationFailedException for cshtml files over 20MB

### ISSUE THREAD

**Issue by Blastnsmash** [aspnet/Mvc#8684]
#### Is this a Bug or Feature request?:
I dont know - it may be intended but hoping for an override?

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Serve up a cshtml page that's over 20MB in size

#### Description of the problem:
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: 'One or more compilation failures occurred:
error CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.'

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

2.1.3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Blastnsmash.
Can you give us more information regarding your scenario. It's unclear what you're trying to do.

**Comment by mkArtakMSFT** [comment]
@Blastnsmash, the error you're seeing is a limitation in Roslyn. You can work around that by trying to split your view content into multiple Views. A sample project with a repro would allow us to give you a better guidance.

**Comment by Blastnsmash** [comment]
Is it possible to tell MVC to specifically not process certain elements on the page? For example, most of the content is actually static content and should be ignored. Namely all the svg elements.

**Comment by mkArtakMSFT** [comment]
@Blastnsmash, can you host a similar file (cshtml) in GitHub or just share the portion of it here with some comments instead of huge SVG conent so we can see what it looks like?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by Blastnsmash** [comment]
Thanks for the suggestion, breaking up the document into either partial views or view components works just fine - it also helps Visual Studio handle large documents. I apologize for the delay. Thanks again.
