### ISSUE TITLE
Is it possible to provide an independent object validator for Model

### ISSUE THREAD

**Issue by xiaotupansy** [aspnet/Mvc#8688]
#### Is this a Bug or Feature request?:
Feature request

What I want is an independent object validator for Model that can be used anywhere without binding to Controller.

Here's the sample usage:
`ObjectValidator<MyModel>.Validate(myModelEntity) returns true or false.`

Like json schema.
https://github.com/tdegrunt/jsonschema
Sample json schema code for validation:
var validate = require('jsonschema').validate;
console.log(validate(4, {"type": "number"}));

And I hope that I can specify the properties that should be validated without validating the whole model.
Here's the sample usage:
```
ObjectValidator<MyModel>.Validate(m=>m.Name,"111") returns true or false.
ObjectValidator<MyModel>.Validate("Name","111") returns true or false.
```

**Comment by rynowak** [comment]
We have no plans to provide something like this in the framework. MVC's validation features are deeply tied to details of how the framework understands model objects and how it tracks validation errors.
