### ISSUE TITLE
Trying to return json from page handler but it's returning html code (Razor Pages)

### ISSUE THREAD

**Issue by troncomputers** [aspnet/Mvc#8698]
#### Is this a Bug or Feature request?:
Bug (I think)

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Just try to return json from page handler.
```
public class Customer
{
     public int ID { get; set; }
     public string Code { get; set; }
     public string Name { get; set; }
}
```
Index.cshtml.cs
```
public JsonResult PageData()
{
    Customer c = new Customer();
    c.ID = 1;
    c.Code = "TEST";
    c.Name = "Test Customer Pro";

    return new JsonResult(tn);
}
//or
public IActionResult PageData()
{
    Customer c = new Customer();
    c.ID = 1;
    c.Code = "TEST";
    c.Name = "Test Customer Pro";

    return new JsonResult(tn);
}
```
Index.cshtml
```
<a asp-page-handler="PageData" class="btn btn-secondary text-primary mt-3">
   <span class="btn-icon">
       <i class="la la-plus"></i>Customer
   </span>
</a>
```

#### Description of the problem:
Page handler returns html not json. I'm trying to use DataTables helper:
[LZorglub/DataTables.AspnetCore.Mvc](https://github.com/LZorglub/DataTables.AspnetCore.Mvc)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @troncomputers.
You should use a certain naming convention so the handler is hit.
Try to rename the handler to `OnGetPageData` but leave the `asp-page-handler="PageData"`.

**Comment by troncomputers** [comment]
OMG, yes. I'm sorry...
