### ISSUE TITLE
Pass generic type/list to ViewComponent's Invoke method 

### ISSUE THREAD

**Issue by fabercs** [aspnet/Mvc#8699]
#### Description of the problem:
I want to make a generic list component in my application. List components are called as follows;
`@await Component.InvokeAsync("ListComponent", new { list = Model.List, columnsList= "Subject,Description" })`

The list in `Model.List` contains a `List<T>` where `T` is a type derived from a base `IEntity`.
Here the components `Invoke`
```
public IViewComponentResult Invoke(List<Entity> list // <== strong type , string columnsList)
{
    // omitted for brevity
    return View("Default", list);
}
```
this works fine, however when change to this list starts coming `null`.

```
public IViewComponentResult Invoke(List<IEntity> list // <== generic type , string columnsList)
{
    // omitted for brevity
    return View("Default", list);
}
```
Is there a way to make this work with generic types?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @fabercs.
@dougbu, can you please look into this? Thanks!

**Comment by fabercs** [comment]
@mkArtakMSFT , @dougbu  I have checked my code with a refreshed eye and `Invoke` parameter name and anonymous type parameter name in caller were mismatching.  No worries.
