### ISSUE TITLE
HtmlFieldPrefix generated with "z_"

### ISSUE THREAD

**Issue by Steveiwonder** [aspnet/Mvc#8709]
#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Create a form 
```html
@{
    ViewData.TemplateInfo.HtmlFieldPrefx = "__Prefix";
}
<form>
<input asp-for="FirstName" />
</form>
```
#### Description of the problem:
When using any HtmlFieldPrefix that begins `__` (double underscore) the output html is incorrect, it converts the first `_` to `z` for the id only

So the above form would look like:
```html
<form>
<input name="__FirstName" id="z_FirstName" />
</form>
```

I can reproduce this in a clean MVC project.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Steveiwonder.
@NTaylorMullen, can you please look into this? Thanks!
