### ISSUE TITLE
Trouble building source

### ISSUE THREAD

**Issue by TKharaishvili** [aspnet/Mvc#8710]
After cloning the master branch and running `build.cmd`, I ran into the following problem:

![image](https://user-images.githubusercontent.com/4363170/48266595-45d2f980-e449-11e8-8df0-10ccd6efbb64.png)

It might be relevant to note that running it with the compile flag - `build.cmd /t:compile` - works successfully.

Afterwards I tried to open the solution - `Mvc.sln`, but found no luck there either as a number of projects are failing to load:

![image](https://user-images.githubusercontent.com/4363170/48266797-f214e000-e449-11e8-9639-20cb5d837484.png)

If I try to reload them, the `Project file is incomplete. Expected imports are missing.` error message shows up.

P.S. I realize that this a fairly annoying issue and you guys have more important ones to deal with. 
I appreciate the help very much.

**Comment by pranavkm** [comment]
@TKharaishvili can you a list the tests that are failing? I was able to build the repo successfully now, so it might be a machine specific (possibly locale specific) test failure. 

See https://github.com/aspnet/AspNetCore/wiki/Building-from-source#building-in-visual-studio--code for steps required to build from source.

**Comment by TKharaishvili** [comment]
@pranavkm rearranging path variables did the trick, I can now build it successfully with VS. 
Thank you so much and I hope I didn't cost you too much time. I'm now gonna close the issue.
