### ISSUE TITLE
Move Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute to a non-internal namespace

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8711]
As part of https://github.com/aspnet/Mvc/pull/8706, `RazorInjectAttribute` was left in the `.Internal` namespace since it's referenced by Razor codegen. Tracking issue to address this

**Comment by rynowak** [comment]
Note that this will require https://github.com/aspnet/Razor/issues/2612 to be completed also or VS will show errors for 3.0 apps.

**Comment by pranavkm** [comment]
Moving this would break RCLs compiled in 2.x that reference the type from the `.Internal` namespace. Since the attribute appears in code that rzc produced, it would be a poor choice to punish users by moving the type and forcing the RCL to be rebuilt. Closing this.
