### ISSUE TITLE
[pubinternal] QueryCollection

### ISSUE THREAD

**Issue by MarcusKohnert** [aspnet/Mvc#8713]
#### Description of the problem: #8689 
`Microsoft.AspNetCore.Http.Internal.QueryCollection`

#### Use case:
In UnitTests we instantiate concrete objects of type `QueryCollection` to assign those instances to httpContext.Request.Query to establish a test context.

``` csharp
httpContext.Request.Query = new QueryCollection(new Dictionary<string, StringValues>
{
	{ "key1", "value1" },
	{ "key2", "value2" }
})
```

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
Does the pubternal effort extend beyond the MVC packages?

**Comment by pranavkm** [comment]
Not that I know of. @MarcusKohnert the type's not in one of the namespaces listed in the linked issue, there are no current plans to change it's `pubternal` status.

**Comment by MarcusKohnert** [comment]
👍 alright. Sorry for the confusion. Only searched for .Internal in our code base. Is this `pubinternal` thing a common pattern? I've never heard about it before. Will keep an eye out in the future.

**Comment by Tratcher** [comment]
It's common in our code base. I haven't seen it elsewhere.
