### ISSUE TITLE
Provide features required to allow OrchardCore to enable setting up routes correctly

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8729]
OrchardCore uses pubinternal types `MvcRouteHandler`, `AttributeRouting` : https://github.com/OrchardCMS/OrchardCore/blob/d729a2048a4390380d99e7be9f7968ff8f8e9271/src/OrchardCore/OrchardCore.Mvc.Core/ModularTenantRouteBuilder.cs. Need to come up with a design for for it in 3.0 now that these types are no longer public

**Comment by pranavkm** [comment]
cc @JamesNK \ @sebastienros

**Comment by JamesNK** [comment]
Both of those types are related to old routing. Ideally Orchard should start using endpoint routing when it moves to 3.0

**Comment by sebastienros** [comment]
Can I already do that for 2.2? That something I want to do ASAP, as I need to use LinkGenerator.

**Comment by JamesNK** [comment]
*kind of*

Not in an officially supported way. You could define Orchard endpoints in your own data source and register it using DI, and hook up the middleware using pub internal methods, but both of those integration points will change in 3.0, and you'll need to update to use the new mechanisms when upgrading to 3.0.

**Comment by mkArtakMSFT** [comment]
@sebastienros, @pranavkm  should we just delay this untill the required APIs from EndpointRouting are exposed?
@JamesNK, will these be available in 3.0.0-preview1 or preview2?

**Comment by JamesNK** [comment]
Preview 1

**Comment by sebastienros** [comment]
I don't think we should delay any of these changes, there won't be many opportunity for users to realize what's broken, and for us to change them if necessary.

**Comment by mkArtakMSFT** [comment]
Well, as the changes are in preview1, there is nothing else to be done here. Closing now. @sebastienros, you'll be able to consume those as soon as preview1 will ship.
