### ISSUE TITLE
Follow up PR https://github.com/aspnet/Mvc/pull/8324/files

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8736]
Merging PR https://github.com/aspnet/Mvc/pull/8324/files before the repo gets merged. Tracking any additional review work using this item. cc @dou

**Comment by dougbu** [comment]
@pranavkm it looks to me like @AlexejTimonin addressed my comments on #8324. What work remains?

**Comment by pranavkm** [comment]
> What work remains?

I guess nothing 👍. Closing in that case
