### ISSUE TITLE
Editor Template Tag Helper incorrectly naming name attribute

### ISSUE THREAD

**Issue by brackers17** [aspnet/Mvc#8740]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
`output.Attributes.SetAttribute("Id", AspFor.Name);`

#### Description of the problem:
When creating my own custom tag helper I use ModelExpression.Name to set the name attribute for the element. 

This works except in editor/display templates where it sets the name incorrectly to the property name instead of the prefix then the property name. 

For example if you have list of person objects with age properties, the tag helper should set the name attribute to `[0].Age` but it just sets to `Age`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @brackers17.
@NTaylorMullen, can you please look into this? Thanks!

**Comment by brackers17** [comment]
Hey @NTaylorMullen, that's perfect thank you! Is there a way I could have found that out myself? Without having to contact yourselves?

**Comment by NTaylorMullen** [comment]
> Is there a way I could have found that out myself? Without having to contact yourselves?

The best way would be to inspect the code in this repo. To make things even easier though I'd suggest by adding Microsoft's public symbol server and debugging through MVC when you encounter unexpected issues such as this. 😄
