### ISSUE TITLE
Change version of code-gen to 0.1.0-pre

### ISSUE THREAD

**Issue by glennc** [aspnet/Mvc#8746]
We want this to be the version that we ship our initial preview release.

**Comment by dougbu** [comment]
@glennc `-pre`, `-preview1` (like past preview releases) or `-alpha1` (like current `master` builds)

**Comment by mkArtakMSFT** [comment]
Let's go with `0.1.0-preview1`. This is what I agreed with @DamianEdwards

**Comment by dougbu** [comment]
3fe61d6
