### ISSUE TITLE
RazorPages crash on MacOS

### ISSUE THREAD

**Issue by wilsonrivera** [aspnet/Mvc#8762]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
I'm actually not really sure what triggers this, I just created a new Razor Pages project, but haven't been to find a way to replicate it with 100% accuracy.

#### Description of the problem:
When the project is running, I get the following exception that causes the project to crash:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Http.ActiveHandlerTrackingEntry.Timer_Tick()
   at Microsoft.Extensions.Http.ActiveHandlerTrackingEntry.<>c.<.cctor>b__22_0(Object s)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
`2.2.0-preview3-35497`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @wilsonrivera.
@rynowak is this something familiar?

@wilsonrivera, it would really help to get a repro project.

**Comment by wilsonrivera** [comment]
This can be closed. After some extra research, I figured out the issue isn't with Razor Pages itself but with HttpClientFactory

Issue for reference: https://github.com/aspnet/HttpClientFactory/issues/194
