### ISSUE TITLE
Multilingual in .net core

### ISSUE THREAD

**Issue by amh1979** [aspnet/Mvc#8763]
#### Is this a Bug or Feature request?:
discussion

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
https://github.com/aspnet/Mvc/

#### Description of the problem:
Multilingual in .net core

#### Version of `Microsoft.AspNetCore.Mvc` 

Is there any way to automatically use Culture of the current process?
write JSON of datetime or Executor Razor page
e.g.: Microsoft.AspNetCore.Mvc.Formatters.Json/JsonOutputFormatter.cs

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg FYI

**Comment by amh1979** [comment]
It's just a suggestion.

**Comment by ryanbrandenburg** [comment]
I don't really follow the suggestion. If it's that we should use `CultureInfo.CurrentCulture` to select our localization language then we already do, [check out the documentation here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2).

If the question is something else please clarify. Snippets of code with current vs proposed results are particularly helpful for this kind of request.

**Comment by amh1979** [comment]
Okay, I can only rewrite JsonOutputFormatter and not use the default JsonSerializerSettings
