### ISSUE TITLE
What's the repo that contains ASP.NET MVC for the .NET framework and not the ASP.NET Core one?

### ISSUE THREAD

**Issue by ghost** [aspnet/Mvc#8779]
I am looking for the source of the `FilterAttributeFilterProvider` class in ASP.NET MVC 5.2.6 for the .NET framework 4.5.2?

This one looks like it is the ASP.NET Core MVC repo.

Where can I find the source for the plain original vanilla ASP.NET MVC?

PS: I am looking for the source because all the decompilers I know of and have do not reverse-engineer lambda's. They just show the compiler generated output of lambdas like so:

```
[IteratorStateMachine(typeof(<GetFilters>d__5))]
public virtual IEnumerable<Filter> GetFilters(ControllerContext controllerContext, 
    ActionDescriptor actionDescriptor) 
{     
  return new <GetFilters>d__5(-2) { <>4__this = this, 
               <>3__controllerContext = controllerContext, 
              <>3__actionDescriptor = actionDescriptor }; 
}
```

**Comment by benaadams** [comment]
AspNetWebStack https://github.com/aspnet/AspNetWebStack

**Comment by ghost** [comment]
Like!

Thank you!  :+1:
