### ISSUE TITLE
able to run MVCsandbox app from cmd.exe. but not able from vs2019 and 2017 previews.(It is not a bug. Need help.)

### ISSUE THREAD

**Issue by kishanAnem** [aspnet/Mvc#8780]
It is not a bug. Need help.
I've rebased aspnet/mvc
after ran build.cmd.
able to run MVCsandbox app from cmd.exe. 
but not able from vs2019 and 2017 previews.

[MVCsandboxEventLog.zip](https://github.com/aspnet/Mvc/files/2654476/MVCsandboxEventLog.zip)
VS2019 Path:
C:\Program Files (x86)\Intel\iCLS Client\;
C:\Program Files\Intel\iCLS Client\;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\Git\cmd;C:\WINDOWS\system32;
C:\WINDOWS;C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files\CMake\bin;
C:\WINDOWS\System32\OpenSSH\;
C:\Users\kishan\AppData\Local\Microsoft\WindowsApps;
C:\systeminternals;C:\ProgramData\kishan\GitHubDesktop\bin;
C:\Users\kishan\.dotnet\tools;
C:\Program Files\Microsoft VS Code\bin;
C:\Users\kishan\AppData\Local\GitHubDesktop\bin;
C:\Users\kishan\AppData\Local\Microsoft\WindowsApps;
C:\Users\kishan\.dotnet\x64;

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kishanAnem.
Our engineering team is heads down handling critical issues and unfortunately, we're unable to answer questions of this nature. Your best bet would be to look through the repo and find a solution for yourself. Sorry for not being able to assist you. Hope you'll be able to handle it yourself.
