### ISSUE TITLE
Open API Analyzers behave different from VSCode -> VSforMac -> VS17

### ISSUE THREAD

**Issue by rspaulino** [aspnet/Mvc#8783]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
create a new WebAPI project, add Open API Analyzers and open it on VSCode, VSforMac, VS17

#### Description of the problem:
VS17 give expected behavior of the feature which are squiggles line and Quick fixes options.
VSforMac give you only warning messages but not Quick fixes options.
VSCode give you none.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
   <TargetFramework>netcoreapp2.2</TargetFramework>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Api.Analyzers" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="NSwag.AspNetCore" Version="12.0.5" />
<img width="1188" alt="screen shot 2018-12-09 at 10 04 34 am" src="https://user-images.githubusercontent.com/378671/49699030-dfe9a700-fb99-11e8-9a18-7e9a5c273954.png">
<img width="932" alt="screen shot 2018-12-09 at 10 04 14 am" src="https://user-images.githubusercontent.com/378671/49699031-dfe9a700-fb99-11e8-85df-6f14a3a9fac0.png">
<img width="1120" alt="screen shot 2018-12-09 at 10 03 53 am" src="https://user-images.githubusercontent.com/378671/49699032-dfe9a700-fb99-11e8-8d96-329196a94b82.png">

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rspaulino. The behavior your're seeing is by design. 
We have no control over how much support for analyzers different IDE-s provide. You can provide your feedback to VSCode and/or VS for Mac if you wish.
