### ISSUE TITLE
Support @Inject, @model, @using declaration in viewstart

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#881]
Related discussion: https://github.com/aspnet/Mvc/issues/825

The plan is to have any directives declared in _ViewStart affect pages in the hierarchy. For instance `@using MyNamespace` declared in the root _ViewStart wouid cause a `using MyNamespace;` to be generated in all views in the application. 

The merge strategy happens on a per-directive basis - for instance for @inject are merged by name`@inject FooType Html` in _ViewStart and `@inject BarType Html` in the page would result in the latter being chosen. 

The token `TModel` would represent the model of the current page. When adding a directive to a page, the token would be replaced by the value specified by @model.

**Comment by Shazwazza** [comment]
I had this working a very long time ago but have upgraded my sln to dnx and MVC6 beta4 and no the @inject on a _ViewStart page doesn't seem to propagate to views using it. It could be something I'm doing wrong or is it a known issue?

**Comment by pranavkm** [comment]
@Shazwazza we added a new file `_GlobalImport.cshtml` to import these directives. The idea was to avoid repurposing `_ViewStart` to support this feature. See - https://github.com/aspnet/Mvc/pull/2020

**Comment by Shazwazza** [comment]
great thanks, will give it a try
