### ISSUE TITLE
Auto-generate HTTP Allow header when we fail to match on HTTP method

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#893]
When we fail to match because of HTTP method constraints, we should auto-generate a 405 response with an Allow header listing the possible methods.

**Comment by yishaigalatzer** [comment]
We should also have a way to turn the behavior off.

**Comment by yishaigalatzer** [comment]
@rynowak there is no major need to get the feature in for RC, but I would like to verify we can do it without breaking the architecture. We could make it as simple as just making the basic determination and storing the data on the request, and have later a middleware that does the conversion.

I think this will end up being quite complex when you have multiple routes competing for the action where they all fail for different reasons. So lets give it a quick glance and see how doable it is.
