### ISSUE TITLE
Compare performance of output conneg.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#898]
Some allocation profiling data from 3000 requests to a simple just enough header info to trigger all of the conneg code paths.

![image](https://cloud.githubusercontent.com/assets/1430011/10795215/06412f60-7d56-11e5-841f-706975edfcb3.png)

`& ab -n $iterations -c 16 -T application/json -p post_pet.txt -H "Accept: application/json; q=0.9, application/xml; q=0.6" -H "Accept-Charset: utf-8" $url`

This is responsible for about 1mb of 75mb allocations total. It's worth just removing all of the Linq from here and replacing with `IList<>` + indexing.

**Comment by rynowak** [comment]
Updated with some measurements. I didn't go super deep here, but it's clear we should just remove all of the Linq. I think for now that's good enough, and we have bigger fish to try in terms of perf.

**Comment by rynowak** [comment]
Resolving based on https://github.com/aspnet/Mvc/commit/1312ed8b7171a73a6c80b3e6a9bc91e8cf95942e
