### ISSUE TITLE
Cache Common Header Values.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#918]
For Input and output formatters the supported media types should come from a cached pool. #868 , #896

**Comment by yishaigalatzer** [comment]
@Tratcher do you think this kind of class belongs in HttpAbstractions for common Content types?

**Comment by Tratcher** [comment]
I hesitate to provide statics like that because the header types like MediaTypeHeaderValue are mutable.

**Comment by yishaigalatzer** [comment]
Depends on aspnet/HttpAbstractions#177

**Comment by rynowak** [comment]
Closing this out after some discussion. The example provided above can't work because a `MediaTypeHeaderValue` can't be const, and so can't be used in an attribute.

If we have a perf issue, we'll drive it another way.
