### ISSUE TITLE
Model-binding does not fail validation when invalid Enum 'value' is supplied

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#924]
Request # 1: `/Products/Index?category=1` and value for category is `Movies`, which is expected
**Request # 2**: `/Products/Index?category=10` and value for category is '10'...Here we should rather make the model state invalid with appropriate error...currently the model state is valid.

Action:
`public IActionResult Index(CategoryType category)`

```C#
public enum CategoryType
{
    Books,
    Movies,
    Cars
}
```

**Comment by yishaigalatzer** [comment]
We are thinking that this behavior is fine and by design. 
We can at some point implement a `[StrictEumBehavior]` validation attribute if asked for by users.
