### ISSUE TITLE
Model-binding : Support data annotation based property names for data coming from Url too

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#925]
Scenario:
I would like to support following urls:
`GET /jobs/search?q=azure`
`GET /jobs/search?q=C#&ids=903854&ids=385754`

Issue:
Currently we do not support binding by data annotations attributes based property names...it will be good to support this...I haven't tried the workaround, but looking at the following post, the amount of code that he had to write is just insane..
http://ole.michelsen.dk/blog/bind-a-model-property-to-a-different-named-query-string-field/

``` C#
public class JobSearchCriteria
{
    [Display(Name = "ids")]
    public List<int> JobIds { get; set; }

    [Display(Name = "q")]
    public string SearchTerm { get; set; }
}

public class JobsController : Controller
{
    [HttpGet]
    public IActionResult Search(JobSearchCriteria criteria)
    {
        throw new NotImplementedException();
    }
}
```

I agree that `Display` attribute here probably is not really ideal, but I think we should provide an easy way for supporting aliases...

**Comment by tuespetre** [comment]
It seems that `[Bind(Prefix = "")]`, `[FromQuery]`, and so forth will allow for this with the binding of incoming models, but the `DefaultHtmlGenerator` does not appear to be respecting the prefixes and names when generating the names for the HTML controls.

**Comment by dougbu** [comment]
@tuespetre we support name customization when binding as well as during HTML generation but the mechanism is not the same. `[Bind(Prefix="name")]` and similar attributes control names used during model binding and validation. On the other hand, you must override the automatically-chosen `name`s and `id`s to do the same during HTML generation e.g. `<input asp-for="SearchTerm" name="q" id="q"/>`.

**Comment by tuespetre** [comment]
The separation makes sense; would there be a way to control it with a custom metadata provider though?

- Derek Gray

**Comment by dougbu** [comment]
> would there be a way to control it with a custom metadata provider though?

Not today. You need to _completely_ override the way HTML and tag helpers generate `name`s and `id`s.

@tuespetre it's true some scenarios involving `[Bind(Prefix="name")]` don't have all the end-to-end pieces in place. Part of that was not being sure those scenarios involved views. Could you describe the model binding -> views end-to-end story that needs custom `name`s and `id`s a bit more?

**Comment by javiercn** [comment]
I agree with @danroth but it's more complicated than it looks like as other things need to be taken into consideration, like how would the scenarios look like in the presence of JSON.NET attributes

**Comment by tuespetre** [comment]
@dougbu I don't know that element ids really have a place in the story as they are only consumed by client scripts. But the ability to specify that a model's properties should be bound from a specifically named query or form parameter doesn't seem very complete if the code generating the form elements doesn't automatically use those specified names and prefixes. There are two cases I can think of where I would be using such functionality today:

- Decoupling parameter names from model property names to prevent link breakage
- 'Vanity' parameters (?s=asc&q=is:open&p=2 instead of ?Query.SearchText=is:open&Query.CurrentPage=2&Query.SortOrder=DefaultAscending)

**Comment by Eilon** [comment]
Closing because we are not planning to implement this.
