### ISSUE TITLE
<inheritdoc /> support is missing

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#928]
Turns out our XML comment syntax isn't perfect.  The result is a few missing words and sometimes undocumented methods (though comments exist for them).

One aspect of this, not fixed in the PR I'm about to send out, is `<inheritdoc />` is presently non-operational.  This is a Sandcastle custom tag (see [here](http://www.ewoodruff.us/shfbdocs/html/79897974-ffc9-4b84-91a5-e50c66a0221d.htm)) and our current infrastructure doesn't seem to support it.  So for example `HtmlHelper` does not inherit any documentation from `IHtmlHelper` and the class has limited IntelliSense available.

**Comment by yishaigalatzer** [comment]
@divega @davidfowl are we planning to make a framework wide support for `inheritdoc`?

**Comment by yishaigalatzer** [comment]
ping, we need this for in visual studio dependency. @rowanmiller showed me something that we might be able to leverage here

**Comment by rowanmiller** [comment]
Sand Castle has a component that can be used to just produce an IntelliSense file (without all the other things Sand Castle does) - http://ewsoftware.github.io/SHFB/html/1fcdf9d3-06fb-4a7b-a584-f55b6ea5baae.htm.

Sand Castle isn't super lightweight and I'm not sure if there is a way to run it without having to install a bunch of stuff... so we may not want to take the dependency.

**Comment by yishaigalatzer** [comment]
CC @muratg @danroth27

**Comment by danroth27** [comment]
@terrajobst We should track supporting inheritdoc as part of our API ref doc work.

**Comment by terrajobst** [comment]
Agreed. I wonder whether we should ask the compilers to merge in the appropriate elements form the base method; they sure have the context.

@DustinCampbell

**Comment by Eilon** [comment]
@dougbu do you know if this is still an issue with the XML docs that we generate?

Apparently DocFx already supports this, so no issue for our docs web site.

**Comment by dougbu** [comment]
The XML docs that we generate just pass `<inheritdoc />` through, even if the referenced member is in the same assembly e.g.
``` xml
<member name="M:Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(System.String,System.Func{System.String,Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCacheContext})">
  <inheritdoc />
</member>        
```

The remaining question is: What tools that consume those docs understand `<inheritdoc />`. Visual Studio's Object Browser does not (shows no doc comments for these members) but DocFx apparently does. ILSpy is somewhere in the middle -- it displays `<inheritdoc/>` (and, no, it's not a link).

**Comment by Eilon** [comment]
Does it work in Intellisense?

**Comment by dougbu** [comment]
Right, I went to sleep part-way through answering 😺

IntelliSense in Visual Studio and the VS Code / C# extension equivalent do __not__ pick up documentation for members that use `<inheritdoc />`.

#### Separately&hellip;

Visual Studio creates an XML doc outline when you type `///` before a member. In the case of an `interface` implementation or `override`, the outline neither copies the base documentation nor uses `<inheritdoc />`. The empty XML just gets in the way.

VS Code and the C# extension don't currently support these automatic XML snippets.

**Comment by Eilon** [comment]
Understood, thanks!

**Comment by dougbu** [comment]
BTW I suggested a Roslyn extension to implement `<inheritdoc />` because (back then) only Sandcastle recognized the element. Seemed expedient to improve our *.xml files rather than ask everyone else to support `<inheritdoc />`. It would enlarge those files but we've got documentation gaps everywhere except DocFx.

Would be nice if Roslyn itself implemented `<inheritdoc />`. But, they seem to have enough on their plates and an extension is at least theoretically possible.

**Comment by dougbu** [comment]
> an extension is at least theoretically possible.

I was thinking of Roslyn generators and that feature was cut. Without at least a new Roslyn hook, we'd need to post-process the generated XML files e.g. in a MSBuild task that is given the assembly and the `@(References)` item group.

**Comment by danroth27** [comment]
@dend does the api ref system support inheritdoc?

**Comment by pranavkm** [comment]
This issue's being tracked as a C# language feature here - https://github.com/dotnet/csharplang/issues/313. There's also a 3rd party tool that post processes the generated doc comments - https://www.inheritdoc.io. I'd much rather we just wait for the feature to land and close this issue. We haven't done any work on this issue forever 🥀

**Comment by dend** [comment]
Today, we don't support this capability in our managed reference pipeline.  I suggest reading [this conversation](https://github.com/mono/api-doc-tools/issues/152) about the plans on it.

**Comment by pranavkm** [comment]
@dend we generally over ever use `<inheritdoc />` without attributes in our code. It sounds like if the plans come to fruition, the docs would light up correctly without us having to change things in our repo?
