### ISSUE TITLE
Visitors should not print out design time mappings for inherited chunks

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#945]
The `SyntaxTreeNode` and `SourceLocation` line mappings for an inherited chunk reflect the ones from the original _ViewStart and not the current page. Printing these out would be incorrect. Unfortunately setting it to null doesn't work since it causes some visitors to null ref.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/2321

**Comment by NTaylorMullen** [comment]
:+1:
