### ISSUE TITLE
_ViewStart generation should be different from regular view pages.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#952]
_ViewStarts are currently codegened as `RazorPage<T>` where T defaults to dynamic. Additionally, with changes to `MvcRazorHost` to inherit directives from ancestor `_ViewStart`, we pull in directives from ancestors. This behavior also currently applies to `_ViewStart`. This results in injected helpers such as `IHtmlHelper<T>` etc to be created as properties and later activated

The suggestion is to

1. Make `_ViewStart` derive from `RazorPage` 
2. Make `_ViewStart` not inherit directives from parent `_ViewStart` and the default injected directives.

**Comment by yishaigalatzer** [comment]
This requires a lot of work, for seemingly a very minimal benefit
