### ISSUE TITLE
Add Functional tests for Model Binders other than ByteArrayModelBinder.

### ISSUE THREAD

**Issue by sornaks** [aspnet/Mvc#977]

**Comment by danroth27** [comment]
@sornaks Can you please take a look at the tests we added model binding and see if this issue can be closed?

**Comment by sornaks** [comment]
This issue can be closed. More tests were added - https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.FunctionalTests/ModelBindingTest.cs
