### ISSUE TITLE
ViewStartProvider \ ViewStartUtility can cache results on a per directory basis

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#980]
The code might move from ViewStartProvider once this change goes in - https://github.com/aspnet/Mvc/pull/946/files#diff-3b8b6fe6d5352a75ce9e1fa8b0a2185dR38, but we can certainly cache the results on a per-directory basis for the lifetime of an app.

**Comment by yishaigalatzer** [comment]
Unless this shows up in profiles, or we get user feedback for this, lets not spend more time here.
